= 79A.70 - Washington state parks foundation.
:toc:

== 79A.70.005 - Findings.
The legislature finds that:

. State parks are a valuable asset to the people of the state of Washington, contributing to their health, education, and well-being;

. Well maintained state parks are an attraction and contribute significantly to the economic well-being of the state of Washington;

. Well maintained state parks encourage the appreciation of the natural resources and natural beauty of the state of Washington;

. There is an increasing demand for more state parks and more state parks services;

. There are individuals and groups who desire to contribute to the continued vitality of the state parks system;

. Providing a tax-deductible method for individuals and groups to contribute is an effective way of increasing available funds to improve the state parks system; and

. It is in the public interest to create a nonprofit foundation to provide such a method for individuals and groups to contribute to the preservation, restoration, and enhancement of the state parks system.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6147-S.SL.pdf?cite=2000%20c%2025%20§%201[2000 c 25 § 1]; ]

== 79A.70.010 - Purpose.
The purpose of the Washington state parks foundation is to solicit support for the state parks system, [to] cooperate with other organizations, and to encourage gifts to support and improve the state parks.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6034.SL.pdf?cite=2014%20c%2086%20§%206[2014 c 86 § 6]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6147-S.SL.pdf?cite=2000%20c%2025%20§%202[2000 c 25 § 2]; ]

== 79A.70.020 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Foundation" means the Washington state parks foundation created in RCW 79A.70.030.

. "State parks" means that system of parks administered by the commission under this title.

. "Eligible grant recipients" includes any and all of the activities of the commission in carrying out the provisions of this title and friends groups or other organizations that propose projects or programs solely for the benefit of state parks.

. "Eligible projects" means any project, action, program, or part of any project, action, or program that serves to preserve, restore, improve, or enhance the state parks.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6034.SL.pdf?cite=2014%20c%2086%20§%207[2014 c 86 § 7]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6147-S.SL.pdf?cite=2000%20c%2025%20§%203[2000 c 25 § 3]; ]

== 79A.70.030 - Washington state parks foundation—Establishment—Board of directors. (Effective until January 1, 2022.)
. By September 1, 2000, the commission shall file articles of incorporation in accordance with the Washington nonprofit corporation act, chapter 24.03 RCW, to establish the Washington state parks foundation. The foundation shall not be an agency, instrumentality, or political subdivision of the state and shall not disburse public funds.

. The foundation shall have a board of directors consisting of up to fifteen members, whose terms, method of appointment, and authority must be in accordance with the Washington nonprofit corporation act, chapter 24.03 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6034.SL.pdf?cite=2014%20c%2086%20§%208[2014 c 86 § 8]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6147-S.SL.pdf?cite=2000%20c%2025%20§%204[2000 c 25 § 4]; ]

== 79A.70.040 - Foundation's duties—Grant process.
. The foundation shall actively solicit contributions from individuals and groups for the benefit of the state parks.

. The foundation shall develop criteria for guiding themselves in either the creation of an endowment, or the making of grants to eligible grant recipients and eligible projects in the state parks, or both.

. A competitive grant process shall be conducted at least annually by the foundation to award funds for the benefit of state parks. Competitive grant applications shall only be submitted to the foundation by the commission, friends groups, or other organizations with projects or programs solely for the benefit of state parks.  Grants shall be awarded to eligible projects consistent with the criteria developed by the foundation.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6034.SL.pdf?cite=2014%20c%2086%20§%209[2014 c 86 § 9]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6147-S.SL.pdf?cite=2000%20c%2025%20§%205[2000 c 25 § 5]; ]

== 79A.70.050 - Foundation moneys not to supplant preexisting funding.
Money provided to the state parks by the foundation shall not be used to supplant preexisting funding sources.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6147-S.SL.pdf?cite=2000%20c%2025%20§%206[2000 c 25 § 6]; ]

