= 79A.15 - Acquisition of habitat conservation and outdoor recreation lands.
:toc:

== 79A.15.005 - Findings.
The legislature finds:

. That Washington possesses an abundance of natural wealth in the form of forests, mountains, wildlife, waters, and other natural resources, all of which help to provide an unparalleled diversity of outdoor recreation opportunities and a quality of life unmatched in this nation;

. That as the state's population grows, the demand on these resources is growing too, placing greater stress on today's already overcrowded public recreational lands and facilities, and resulting in a significant loss of wildlife habitat and lands of unique natural value;

. That public acquisition and development programs have not kept pace with the state's expanding population;

. That private investment and employment opportunities in general and the tourist industry in particular are dependent upon the continued availability of recreational opportunities and our state's unique natural environment;

. That if current trends continue, some wildlife species and rare ecosystems will be lost in the state forever and public recreational lands will not be adequate to meet public demands;

. That there is accordingly a need for the people of the state to reserve certain areas of the state, in rural as well as urban settings, for the benefit of present and future generations.

It is therefore the policy of the state to acquire as soon as possible the most significant lands for wildlife conservation and outdoor recreation purposes before they are converted to other uses, and to develop existing public recreational land and facilities to meet the needs of present and future generations.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990ex1c14.pdf?cite=1990%201st%20ex.s.%20c%2014%20§%201[1990 1st ex.s. c 14 § 1]; ]

== 79A.15.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Acquisition" means the purchase on a willing seller basis of fee or less than fee interests in real property. These interests include, but are not limited to, options, rights of first refusal, conservation easements, leases, and mineral rights.

. "Board" means the recreation and conservation funding board.

. "Confer" means a dialogue between project sponsors and local county and city officials with the purpose of early review of potential projects. The dialogue may include any matter relevant to a particular project, which may include but need not be limited to: Project purpose and scope; project elements; estimated project cost; costs and benefits to the community; plans for project management and maintenance; and public access.

. "Critical habitat" means lands important for the protection, management, or public enjoyment of certain wildlife species or groups of species, including, but not limited to, wintering range for deer, elk, and other species, waterfowl and upland bird habitat, fish habitat, and habitat for endangered, threatened, or sensitive species.

. "Farmlands" means any land defined as: (a) "Farm and agricultural land" in RCW 84.34.020(2); and (b) "farm and agricultural conservation land" in RCW 84.34.020(8).

. "Forestlands" means any land defined as "timberland" in RCW 84.34.020(3).

. "Local agencies" means a city, county, town, federally recognized Indian tribe, special purpose district, port district, or other political subdivision of the state providing services to less than the entire state.

. "Multiple benefits" means recreational uses that are compatible with habitat conservation or resources uses or management practices that are compatible with and provide the ability to achieve additional conservation benefits.

. "Natural areas" means areas that have, to a significant degree, retained their natural character and are important in preserving rare or vanishing flora, fauna, geological, natural historical, or similar features of scientific or educational value.

. "Nonprofit nature conservancies" means organizations as defined in RCW 84.34.250.

. "Riparian habitat" means land adjacent to water bodies, as well as submerged land such as streambeds, which can provide functional habitat for salmonids and other fish and wildlife species. Riparian habitat includes, but is not limited to, shorelines and near-shore marine habitat, estuaries, lakes, wetlands, streams, and rivers.

. "Special needs populations" means physically restricted people or people of limited means.

. "State agencies" means the state parks and recreation commission, the department of natural resources, the department of enterprise services, and the department of fish and wildlife.

. "Trails" means public ways constructed for and open to pedestrians, equestrians, or bicyclists, or any combination thereof, other than a sidewalk constructed as a part of a city street or county road for exclusive use of pedestrians.

. "Urban wildlife habitat" means lands that provide habitat important to wildlife in proximity to a metropolitan area.

. "Water access" means boat or foot access to marine waters, lakes, rivers, or streams.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6227-S.SL.pdf?cite=2016%20c%20149%20§%202[2016 c 149 § 2]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5024.SL.pdf?cite=2015%20c%20225%20§%20126[2015 c 225 § 126]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1957-S.SL.pdf?cite=2009%20c%20341%20§%201[2009 c 341 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1813.SL.pdf?cite=2007%20c%20241%20§%2026[2007 c 241 § 26]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5396-S.SL.pdf?cite=2005%20c%20303%20§%201[2005 c 303 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990ex1c14.pdf?cite=1990%201st%20ex.s.%20c%2014%20§%202[1990 1st ex.s. c 14 § 2]; ]

== 79A.15.020 - Habitat conservation account.
The habitat conservation account is established in the state treasury. The board shall administer the account in accordance with chapter 79A.25 RCW and this chapter, and shall hold it separate and apart from all other money, funds, and accounts of the board.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1813.SL.pdf?cite=2007%20c%20241%20§%2027[2007 c 241 § 27]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2399-S.SL.pdf?cite=2000%20c%2011%20§%2065[2000 c 11 § 65]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990ex1c14.pdf?cite=1990%201st%20ex.s.%20c%2014%20§%203[1990 1st ex.s. c 14 § 3]; ]

== 79A.15.030 - Allocation and use of moneys—Grants.
. Moneys appropriated prior to July 1, 2016, for this chapter shall be divided as follows:

.. Appropriations for a biennium of forty million dollars or less must be allocated equally between the habitat conservation account and the outdoor recreation account.

.. If appropriations for a biennium total more than forty million dollars, the money must be allocated as follows: (i) Twenty million dollars to the habitat conservation account and twenty million dollars to the outdoor recreation account; (ii) any amount over forty million dollars up to fifty million dollars shall be allocated as follows: (A) Ten percent to the habitat conservation account; (B) ten percent to the outdoor recreation account; (C) forty percent to the riparian protection account; and (D) forty percent to the farmlands preservation account; and (iii) any amounts over fifty million dollars must be allocated as follows: (A) Thirty percent to the habitat conservation account; (B) thirty percent to the outdoor recreation account; (C) thirty percent to the riparian protection account; and (D) ten percent to the farmlands preservation account.

. Beginning July 1, 2016, moneys appropriated for this chapter must be allocated as follows: (a) Forty-five percent to the habitat conservation account; (b) forty-five percent to the outdoor recreation account; and (c) ten percent to the farm and forest account.

. Moneys deposited in these accounts shall be invested as authorized for other state funds, and any earnings on them shall be credited to the respective account.

. All moneys deposited in the habitat conservation, outdoor recreation, and farm and forest accounts shall be allocated as provided under RCW 79A.15.040, 79A.15.050, and 79A.15.130 as grants to state or local agencies or nonprofit nature conservancies for acquisition, development, and renovation within the jurisdiction of those agencies, subject to legislative appropriation. The board may use or permit the use of any funds appropriated for this chapter as matching funds where federal, local, or other funds are made available for projects within the purposes of this chapter. Moneys appropriated to these accounts that are not obligated to a specific project may be used to fund projects from lists of alternate projects from the same account in biennia succeeding the biennium in which the moneys were originally appropriated.

. Projects receiving grants for development, recreational access, or fee simple acquisition of land under this chapter must be accessible for public recreation and outdoor education unless the board specifically approves limiting public access in order to protect sensitive species, water quality, or public safety.

. The board may make grants to an eligible project from the habitat conservation, outdoor recreation, and farm and forest accounts and any one or more of the applicable categories under such accounts described in RCW 79A.15.040, 79A.15.050, and 79A.15.130.

. The board may accept private donations to the habitat conservation account, the outdoor recreation account, and the farm and forest account for the purposes specified in this chapter.

. The board may retain a portion of the funds appropriated for this chapter for its office for the administration of the programs and purposes specified in this chapter. The portion of the funds retained for administration may not exceed: (a) The actual administration costs averaged over the previous five biennia as a percentage of the legislature's new appropriation for this chapter; or (b) the amount specified in the appropriation, if any. Each biennium the percentage specified under (a) of this subsection must be approved by the office of financial management and submitted along with the prioritized lists of projects to be funded in RCW 79A.15.060, 79A.15.070, and 79A.15.130.

. Habitat and recreation land and facilities acquired or developed with moneys appropriated for this chapter may not, without prior approval of the board, be converted to a use other than that for which funds were originally approved. The board shall adopt rules and procedures governing the approval of such a conversion.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6227-S.SL.pdf?cite=2016%20c%20149%20§%203[2016 c 149 § 3]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1392.SL.pdf?cite=2015%20c%20183%20§%201[2015 c 183 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1957-S.SL.pdf?cite=2009%20c%20341%20§%202[2009 c 341 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1813.SL.pdf?cite=2007%20c%20241%20§%2028[2007 c 241 § 28]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5396-S.SL.pdf?cite=2005%20c%20303%20§%202[2005 c 303 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2399-S.SL.pdf?cite=2000%20c%2011%20§%2066[2000 c 11 § 66]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990ex1c14.pdf?cite=1990%201st%20ex.s.%20c%2014%20§%204[1990 1st ex.s. c 14 § 4]; ]

== 79A.15.040 - Habitat conservation account—Distribution and use of moneys.
. Moneys appropriated for this chapter prior to July 1, 2016, to the habitat conservation account shall be distributed in the following way:

.. Not less than forty percent through June 30, 2011, at which time the amount shall become forty-five percent, for the acquisition and development of critical habitat;

.. Not less than thirty percent for the acquisition and development of natural areas;

.. Not less than twenty percent for the acquisition and development of urban wildlife habitat; and

.. Not less than ten percent through June 30, 2011, at which time the amount shall become five percent, shall be used by the board to fund restoration and enhancement projects on state lands. Only the department of natural resources and the department of fish and wildlife may apply for these funds to be used on existing habitat and natural area lands.

. Moneys appropriated beginning July 1, 2016, for this chapter to the habitat conservation account shall be distributed in the following way:

.. Not less than thirty-five percent for the acquisition and development of critical habitat;

.. Not less than twenty-five percent for the acquisition and development of natural areas;

.. Not less than fifteen percent for the acquisition or enhancement or restoration of riparian habitat;

.. Not less than fifteen percent for the acquisition and development of urban wildlife habitat; and

.. Not less than ten percent or three million dollars, whichever is less, for the board to fund restoration and enhancement projects on state lands. Any amount above three million dollars must be distributed for the purposes of (c) of this subsection.

. [Empty]
.. In distributing these funds, the board retains discretion to meet the most pressing needs for critical habitat, natural areas, riparian protection, and urban wildlife habitat, and is not required to meet the percentages described in subsections (1) and (2) of this section in any one biennium.

.. If not enough project applications are submitted in a category within the habitat conservation account to meet the percentages described in subsections (1) and (2) of this section in any biennium, the board retains discretion to distribute any remaining funds to the other categories within the account.

. State agencies and nonprofit nature conservancies may apply for acquisition and development funds for natural areas projects under subsection (1)(b) of this section.

. State and local agencies and nonprofit nature conservancies may apply for acquisition and development funds for critical habitat, urban wildlife habitat, and riparian protection projects under this section. Other state agencies not defined in RCW 79A.15.010, such as the department of transportation and the department of corrections, may enter into interagency agreements with state agencies to apply in partnership for riparian protection funds under this section.

. The department of natural resources, the department of fish and wildlife, and the state parks and recreation commission may apply for restoration and enhancement funds to be used on existing state-owned lands.

. [Empty]
.. Any lands that have been acquired with grants under this section by the department of fish and wildlife are subject to an amount in lieu of real property taxes and an additional amount for control of noxious weeds as determined by RCW 77.12.203.

.. Any lands that have been acquired with grants under this section by the department of natural resources are subject to payments in the amounts required under the provisions of RCW 79.70.130 and 79.71.130.

. Except as otherwise conditioned by RCW 79A.15.140 or 79A.15.150, the board in its evaluating process shall consider the following in determining distribution priority:

.. Whether the entity applying for funding is a Puget Sound partner, as defined in RCW 90.71.010;

.. Effective one calendar year following the development and statewide availability of model evergreen community management plans and ordinances under RCW 35.105.050, whether the entity receiving assistance has been recognized, and what gradation of recognition was received, in the evergreen community recognition program created in RCW 35.105.030; and

.. Whether the project is referenced in the action agenda developed by the Puget Sound partnership under RCW 90.71.310.

. After January 1, 2010, any project designed to address the restoration of Puget Sound may be funded under this chapter only if the project is not in conflict with the action agenda developed by the Puget Sound partnership under RCW 90.71.310.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6227-S.SL.pdf?cite=2016%20c%20149%20§%204[2016 c 149 § 4]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2844-S2.SL.pdf?cite=2008%20c%20299%20§%2029[2008 c 299 § 29]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5372-S.SL.pdf?cite=2007%20c%20341%20§%2034[2007 c 341 § 34]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1813.SL.pdf?cite=2007%20c%20241%20§%2029[2007 c 241 § 29]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5396-S.SL.pdf?cite=2005%20c%20303%20§%203[2005 c 303 § 3]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1165-S.SL.pdf?cite=1999%20c%20379%20§%20917[1999 c 379 § 917]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6063-S.SL.pdf?cite=1997%20c%20235%20§%20718[1997 c 235 § 718]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990ex1c14.pdf?cite=1990%201st%20ex.s.%20c%2014%20§%205[1990 1st ex.s. c 14 § 5]; ]

== 79A.15.050 - Outdoor recreation account—Distribution and use of moneys.
. Moneys appropriated prior to July 1, 2016, for this chapter to the outdoor recreation account shall be distributed in the following way:

.. Not less than thirty percent to the state parks and recreation commission for the acquisition and development of state parks, with at least fifty percent of the money for acquisition costs;

.. Not less than thirty percent for the acquisition, development, and renovation of local parks, with at least fifty percent of this money for acquisition costs;

.. Not less than twenty percent for the acquisition, renovation, or development of trails;

.. Not less than fifteen percent for the acquisition, renovation, or development of water access sites, with at least seventy-five percent of this money for acquisition costs; and

.. Not less than five percent for development and renovation projects on state recreation lands. Only the department of natural resources and the department of fish and wildlife may apply for these funds to be used on their existing recreation lands.

. Moneys appropriated beginning July 1, 2016, for this chapter to the outdoor recreation account shall be distributed in the following way:

.. Not less than thirty percent to the state parks and recreation commission for the acquisition and development of state parks, with at least forty percent but no more than fifty percent of the money for acquisition costs;

.. Not less than thirty percent for the acquisition, development, and renovation of local parks, with at least forty percent but no more than fifty percent of this money for acquisition costs;

.. Not less than twenty percent for the acquisition, renovation, or development of trails;

.. Not less than ten percent for the acquisition, renovation, or development of water access sites, with at least seventy-five percent of this money for acquisition costs; and

.. Not less than ten percent or three million dollars, whichever is less, for development and renovation projects on state recreation lands. Any amount above three million dollars must be distributed for the purposes of (d) of this subsection.

. [Empty]
.. In distributing these funds, the board retains discretion to meet the most pressing needs for state and local parks, trails, and water access sites, and is not required to meet the percentages described in subsections (1) and (2) of this section in any one biennium.

.. If not enough project applications are submitted in a category within the outdoor recreation account to meet the percentages described in subsections (1) and (2) of this section in any biennium, the board retains discretion to distribute any remaining funds to the other categories within the account.

. Only the state parks and recreation commission may apply for acquisition and development funds for state parks under subsections (1)(a) and (2)(a) of this section.

. Only local agencies may apply for acquisition, development, or renovation funds for local parks under subsections (1)(b) and (2)(b) of this section.

. Only state and local agencies may apply for funds for trails under subsections (1)(c) and (2)(c) of this section.

. Only state and local agencies may apply for funds for water access sites under subsections (1)(d) and (2)(d) of this section.

. Only the department of natural resources and the department of fish and wildlife may apply for funds for development and renovation projects on existing state recreation lands under subsections (1)(e) and (2)(e) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6227-S.SL.pdf?cite=2016%20c%20149%20§%205[2016 c 149 § 5]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1813.SL.pdf?cite=2007%20c%20241%20§%2030[2007 c 241 § 30]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5396-S.SL.pdf?cite=2005%20c%20303%20§%204[2005 c 303 § 4]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1136-S.SL.pdf?cite=2003%20c%20184%20§%201[2003 c 184 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1165-S.SL.pdf?cite=1999%20c%20379%20§%20941[1999 c 379 § 941]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1165-S.SL.pdf?cite=1999%20c%20379%20§%20920[1999 c 379 § 920]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990ex1c14.pdf?cite=1990%201st%20ex.s.%20c%2014%20§%206[1990 1st ex.s. c 14 § 6]; ]

== 79A.15.060 - Habitat conservation account—Acquisition policies and priorities.
. The board may adopt rules establishing acquisition policies and priorities for distributions from the habitat conservation account.

. Except as provided in RCW 79A.15.030(8), moneys appropriated for this chapter may not be used by the board to fund staff positions or other overhead expenses, or by a state, regional, or local agency to fund operation or maintenance of areas acquired under this chapter.

. Moneys appropriated for this chapter may be used by grant recipients for costs incidental to acquisition, including, but not limited to, surveying expenses, fencing, noxious weed control, and signing.

. The board may not approve a local project where the local agency share is less than the amount to be awarded from the habitat conservation account.

. In determining acquisition priorities with respect to the habitat conservation account, the board shall consider, at a minimum, the following criteria:

.. For critical habitat and natural areas proposals:

... Multiple benefits for the project;

... Whether, and the extent to which, a conservation easement can be used to meet the purposes for the project;

... Community support for the project based on input from, but not limited to, local citizens, local organizations, and local elected officials;

... The project proposal's ongoing stewardship program that includes estimated costs of maintaining and operating the project including, but not limited to, control of noxious weeds and detrimental invasive species, and that identifies the source of the funds from which the stewardship program will be funded;

.. Recommendations as part of a watershed plan or habitat conservation plan, or a coordinated regionwide prioritization effort, and for projects primarily intended to benefit salmon, limiting factors, or critical pathways analysis;

.. Immediacy of threat to the site;

.. Uniqueness of the site;

.. Diversity of species using the site;

... Quality of the habitat;

.. Long-term viability of the site;

.. Presence of endangered, threatened, or sensitive species;

.. Enhancement of existing public property;

.. Consistency with a local land use plan, or a regional or statewide recreational or resource plan, including projects that assist in the implementation of local shoreline master plans updated according to RCW 90.58.080 or local comprehensive plans updated according to RCW 36.70A.130;

.. Educational and scientific value of the site;

.. Integration with recovery efforts for endangered, threatened, or sensitive species;

.. The statewide significance of the site;

.. Habitat benefits for the feeding, nesting, and reproduction of all pollinators, including honey bees.

.. For urban wildlife habitat proposals, in addition to the criteria of (a) of this subsection:

... Population of, and distance from, the nearest urban area;

... Proximity to other wildlife habitat;

... Potential for public use; and

... Potential for use by special needs populations.

.. For riparian protection proposals, the board must consider, at a minimum, the following criteria:

... Whether the project continues the conservation reserve enhancement program. Applications that extend the duration of leases of riparian areas that are currently enrolled in the conservation reserve enhancement program are eligible. These applications are eligible for a conservation lease extension of at least twenty-five years of duration;

... Whether the projects are identified or recommended in a watershed plan, salmon recovery plan, or other local plans, such as habitat conservation plans, and these must be highly considered in the process;

... Whether there is community support for the project;

... Whether the proposal includes an ongoing stewardship program that includes control of noxious weeds, detrimental invasive species, and that identifies the source of the funds from which the stewardship program will be funded;

.. Whether there is an immediate threat to the site;

.. Whether the quality of the habitat is improved or, for projects including restoration or enhancement, the potential for restoring quality habitat including linkage of the site to other high quality habitat;

.. Whether the project is consistent with a local land use plan or a regional or statewide recreational or resource plan. The projects that assist in the implementation of local shoreline master plans updated according to RCW 90.58.080 or local comprehensive plans updated according to RCW 36.70A.130 must be highly considered in the process;

.. Whether the site has educational or scientific value;

... Whether the site has passive recreational values for walking trails, wildlife viewing, the observation of natural settings, or other multiple benefits; and

.. Whether the project provides habitat benefits for the feeding, nesting, and reproduction of all pollinators, including honey bees.

.. Moneys appropriated for this chapter to riparian protection projects must be distributed for the acquisition or enhancement or restoration of riparian habitat. All enhancement or restoration projects, except those qualifying under (c)(i) of this subsection, must include the acquisition of a real property interest in order to be eligible.

. Before November 1st of each even-numbered year, the board shall recommend to the governor a prioritized list of all projects to be funded under RCW 79A.15.040. The governor may remove projects from the list recommended by the board and shall submit this amended list in the capital budget request to the legislature. The list shall include, but not be limited to, a description of each project and any particular match requirement, and describe for each project any anticipated restrictions upon recreational activities allowed prior to the project.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5552-S.SL.pdf?cite=2019%20c%20353%20§%2012[2019 c 353 § 12]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6227-S.SL.pdf?cite=2016%20c%20149%20§%206[2016 c 149 § 6]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1957-S.SL.pdf?cite=2009%20c%20341%20§%203[2009 c 341 § 3]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5348.SL.pdf?cite=2009%20c%2016%20§%201[2009 c 16 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1813.SL.pdf?cite=2007%20c%20241%20§%2031[2007 c 241 § 31]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5396-S.SL.pdf?cite=2005%20c%20303%20§%208[2005 c 303 § 8]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2399-S.SL.pdf?cite=2000%20c%2011%20§%2067[2000 c 11 § 67]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1165-S.SL.pdf?cite=1999%20c%20379%20§%20918[1999 c 379 § 918]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6063-S.SL.pdf?cite=1997%20c%20235%20§%20719[1997 c 235 § 719]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990ex1c14.pdf?cite=1990%201st%20ex.s.%20c%2014%20§%207[1990 1st ex.s. c 14 § 7]; ]

== 79A.15.065 - Grants through habitat conservation account—Statement of environmental benefits—Development of outcome-focused performance measures.
In providing grants through the habitat conservation account, the board shall require grant applicants to incorporate the environmental benefits of the project into their grant applications, and the board shall utilize the statement of environmental benefits in the grant application and review process. The board shall also develop appropriate outcome-focused performance measures to be used both for management and performance assessment of the grant program. To the extent possible, the board should coordinate its performance measure system with other natural resource-related agencies as defined in RCW 43.41.270. The board shall consult with affected interest groups in implementing this section.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1813.SL.pdf?cite=2007%20c%20241%20§%2032[2007 c 241 § 32]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1785-S.SL.pdf?cite=2001%20c%20227%20§%208[2001 c 227 § 8]; ]

== 79A.15.070 - Acquisition and development priorities—Generally.
. In determining which state parks proposals and local parks proposals to fund, the board shall use existing policies and priorities.

. Except as provided in RCW 79A.15.030(8), moneys appropriated for this chapter may not be used by the board to fund staff or other overhead expenses, or by a state, regional, or local agency to fund operation or maintenance of areas acquired under this chapter.

. Moneys appropriated for this chapter may be used by grant recipients for costs incidental to acquisition and development, including, but not limited to, surveying expenses, fencing, and signing.

. The board may not approve a project of a local agency where the share contributed by the local agency is less than the amount to be awarded from the outdoor recreation account. The local agency's share may be reduced or waived if the project meets the needs of an underserved population or a community in need, as defined by the board.

. The board may adopt rules establishing acquisition policies and priorities for the acquisition and development of trails and water access sites to be financed from moneys in the outdoor recreation account.

. In determining the acquisition and development priorities, the board shall consider, at a minimum, the following criteria:

.. For trails proposals:

... Community support for the project;

... Immediacy of threat to the site;

... Linkage between communities;

... Linkage between trails;

.. Existing or potential usage;

.. Consistency with a local land use plan, or a regional or statewide recreational or resource plan, including projects that assist in the implementation of local shoreline master plans updated according to RCW 90.58.080 or local comprehensive plans updated according to RCW 36.70A.130;

.. Availability of water access or views;

.. Enhancement of wildlife habitat; and

... Scenic values of the site.

.. For water access proposals:

... Community support for the project;

... Distance from similar water access opportunities;

... Immediacy of threat to the site;

... Diversity of possible recreational uses;

.. Public demand in the area; and

.. Consistency with a local land use plan, or a regional or statewide recreational or resource plan, including projects that assist in the implementation of local shoreline master plans updated according to RCW 90.58.080 or local comprehensive plans updated according to RCW 36.70A.130.

. Before November 1st of each even-numbered year, the board shall recommend to the governor a prioritized list of all projects to be funded under RCW 79A.15.050. The governor may remove projects from the list recommended by the board and shall submit this amended list in the capital budget request to the legislature. The list shall include, but not be limited to, a description of each project and any particular match requirement, and describe for each project any anticipated restrictions upon recreational activities allowed prior to the project.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6227-S.SL.pdf?cite=2016%20c%20149%20§%207[2016 c 149 § 7]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1813.SL.pdf?cite=2007%20c%20241%20§%2033[2007 c 241 § 33]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5396-S.SL.pdf?cite=2005%20c%20303%20§%209[2005 c 303 § 9]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2399-S.SL.pdf?cite=2000%20c%2011%20§%2068[2000 c 11 § 68]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1165-S.SL.pdf?cite=1999%20c%20379%20§%20919[1999 c 379 § 919]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6063-S.SL.pdf?cite=1997%20c%20235%20§%20720[1997 c 235 § 720]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990ex1c14.pdf?cite=1990%201st%20ex.s.%20c%2014%20§%208[1990 1st ex.s. c 14 § 8]; ]

== 79A.15.080 - Recommended project list—Board authority to obligate funds—Legislature's authority.
The board shall not sign contracts or otherwise financially obligate funds from the habitat conservation account, the outdoor recreation account, or the farm and forest account as provided in this chapter before the legislature has appropriated funds for a specific list of projects. The legislature may remove projects from the list recommended by the governor.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6227-S.SL.pdf?cite=2016%20c%20149%20§%208[2016 c 149 § 8]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1813.SL.pdf?cite=2007%20c%20241%20§%2034[2007 c 241 § 34]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5396-S.SL.pdf?cite=2005%20c%20303%20§%2010[2005 c 303 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990ex1c14.pdf?cite=1990%201st%20ex.s.%20c%2014%20§%209[1990 1st ex.s. c 14 § 9]; ]

== 79A.15.090 - Condemnation.
Moneys made available under this chapter for land acquisition shall not be used to acquire land through condemnation.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990ex1c14.pdf?cite=1990%201st%20ex.s.%20c%2014%20§%2010[1990 1st ex.s. c 14 § 10]; ]

== 79A.15.110 - Review of proposed project application.
State or local agencies or nonprofit nature conservancies shall review the proposed project application and confer with the county or city with jurisdiction over the project area prior to applying for funds for the acquisition of property under this chapter. The appropriate county or city legislative authority may, at its discretion, submit a letter to the board identifying the authority's position with regard to the acquisition project. The board shall make the letters received under this section available to the governor and the legislature when the prioritized project list is submitted under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6227-S.SL.pdf?cite=2016%20c%20149%20§%209[2016 c 149 § 9]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1813.SL.pdf?cite=2007%20c%20241%20§%2036[2007 c 241 § 36]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5396-S.SL.pdf?cite=2005%20c%20303%20§%205[2005 c 303 § 5]; ]

== 79A.15.120 - Riparian protection account—Use of funds.
. The riparian protection account is established in the state treasury. The board must administer the account in accordance with chapter 79A.25 RCW and this chapter, and hold it separate and apart from all other money, funds, and accounts of the board.

. Moneys appropriated for this chapter to the riparian protection account must be distributed for the acquisition or enhancement or restoration of riparian habitat. All enhancement or restoration projects, except those qualifying under subsection (9)(a) of this section, must include the acquisition of a real property interest in order to be eligible.

. State and local agencies and lead entities under chapter 77.85 RCW, nonprofit nature conservancy organizations or associations, and the conservation commission may apply for acquisition and enhancement or restoration funds for riparian habitat projects under subsection (1) of this section. Other state agencies not defined in RCW 79A.15.010, such as the department of transportation and the department of corrections, may enter into interagency agreements with state agencies to apply in partnership for funds under this section.

. The board may adopt rules establishing acquisition policies and priorities for distributions from the riparian protection account.

. Except as provided in *RCW 79A.15.030(7), moneys appropriated for this section may not be used by the board to fund staff positions or other overhead expenses, or by a state, regional, or local agency to fund operation or maintenance of areas acquired under this chapter.

. Moneys appropriated for this section may be used by grant recipients for costs incidental to restoration and acquisition, including, but not limited to, surveying expenses, fencing, and signing.

. The board may not approve a local project where the local agency or nonprofit nature conservancy organization or association share is less than the amount to be awarded from the riparian protection account. In-kind contributions, including contributions of a real property interest in land may be used to satisfy the local agency's or nonprofit nature conservancy organization's or association's share.

. State agencies receiving grants for acquisition of land under this section must pay an amount in lieu of real property taxes equal to the amount of tax that would be due if the land were taxable as open space land under chapter 84.34 RCW except taxes levied for any state purpose, plus an additional amount for control of noxious weeds equal to that which would be paid if such lands were privately owned. The county assessor and county legislative authority shall assist in determining the appropriate calculation of the amount of tax that would be due.

. In determining acquisition priorities with respect to the riparian protection account, the board must consider, at a minimum, the following criteria:

.. Whether the project continues the conservation reserve enhancement program. Applications that extend the duration of leases of riparian areas that are currently enrolled in the conservation reserve enhancement program shall be eligible. Such applications are eligible for a conservation lease extension of at least twenty-five years of duration;

.. Whether the projects are identified or recommended in a watershed planning process under chapter 247, Laws of 1998, salmon recovery planning under chapter 77.85 RCW, or other local plans, such as habitat conservation plans, and these must be highly considered in the process;

.. Whether there is community support for the project;

.. Whether the proposal includes an ongoing stewardship program that includes control of noxious weeds, detrimental invasive species, and that identifies the source of the funds from which the stewardship program will be funded;

.. Whether there is an immediate threat to the site;

.. Whether the quality of the habitat is improved or, for projects including restoration or enhancement, the potential for restoring quality habitat including linkage of the site to other high quality habitat;

.. Whether the project is consistent with a local land use plan, or a regional or statewide recreational or resource plan. The projects that assist in the implementation of local shoreline master plans updated according to RCW 90.58.080 or local comprehensive plans updated according to RCW 36.70A.130 must be highly considered in the process;

.. Whether the site has educational or scientific value; and

.. Whether the site has passive recreational values for walking trails, wildlife viewing, or the observation of natural settings.

. Before November 1st of each even-numbered year, the board will recommend to the governor a prioritized list of projects to be funded under this section. The governor may remove projects from the list recommended by the board and will submit this amended list in the capital budget request to the legislature. The list must include, but not be limited to, a description of each project and any particular match requirement.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1957-S.SL.pdf?cite=2009%20c%20341%20§%204[2009 c 341 § 4]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5348.SL.pdf?cite=2009%20c%2016%20§%202[2009 c 16 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1813.SL.pdf?cite=2007%20c%20241%20§%2037[2007 c 241 § 37]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5396-S.SL.pdf?cite=2005%20c%20303%20§%206[2005 c 303 § 6]; ]

== 79A.15.130 - Farm and forest account—Use of funds.
. The farm and forest account is established in the state treasury. The board will administer the account in accordance with chapter 79A.25 RCW and this chapter, and hold it separate and apart from all other money, funds, and accounts of the board. Moneys appropriated for this chapter to the farm and forest account must be distributed for the acquisition and preservation of farmlands and forestlands in order to maintain the opportunity for agricultural and forest management activity upon these lands.

. Moneys appropriated beginning July 1, 2016, for this chapter shall be divided as follows:

.. Not less than ninety percent for the acquisition and preservation of farmlands.

.. Not less than ten percent for the acquisition and preservation of forestlands.

. Moneys appropriated for this chapter to the farm and forest account may be distributed for: (a) The acquisition of a less than fee simple interest in farmlands or forestland, such as a conservation easement or lease; (b) the enhancement or restoration of ecological functions on those properties; or (c) both. In order for a farmland or forestland preservation grant to provide for an environmental enhancement or restoration project, the project must include the acquisition of a real property interest.

. Cities, counties, nonprofit nature conservancies, and the conservation commission may apply for acquisition and enhancement or restoration funds for farmland or forestland preservation projects within their jurisdictions under subsection (1) of this section.

. The board may adopt rules establishing acquisition and enhancement or restoration policies and priorities for distributions from the farm and forest account.

. The acquisition of a property interest in a project under this section does not provide a right of access to the property by the public unless explicitly provided for in a conservation easement or other form of deed restriction.

. Except as provided in RCW 79A.15.030(8), moneys appropriated for this section may not be used by the board to fund staff positions or other overhead expenses, or by cities, counties, nonprofit nature conservancies, or the conservation commission to fund operation or maintenance of areas acquired under this chapter.

. Moneys appropriated for this section may be used by grant recipients for costs incidental to restoration and acquisition, including, but not limited to, surveying expenses, fencing, noxious weed control, and signing.

. The board may not approve a local project where the local agency's or nonprofit nature conservancies' share is less than the amount to be awarded from the farm and forest account. In-kind contributions, including contributions of a real property interest in land, may be used to satisfy the local agency's or nonprofit nature conservancies' share.

. In determining the acquisition priorities for farmland projects, the board must consider, at a minimum, the following criteria:

.. Community support for the project;

.. A recommendation as part of a limiting factors or critical pathways analysis, a watershed plan or habitat conservation plan, or a coordinated regionwide prioritization effort;

.. The likelihood of the conversion of the site to nonagricultural or more highly developed usage;

.. Consistency with a local land use plan, or a regional or statewide recreational or resource plan. The projects that assist in the implementation of local shoreline master plans updated according to RCW 90.58.080 or local comprehensive plans updated according to RCW 36.70A.130 must be highly considered in the process;

.. Benefits to salmonids;

.. Benefits to other fish and wildlife habitat;

.. Integration with recovery efforts for endangered, threatened, or sensitive species;

.. The viability of the site for continued agricultural production, including, but not limited to:

.. Soil types;

... On-site production and support facilities such as barns, irrigation systems, crop processing and storage facilities, wells, housing, livestock sheds, and other farming infrastructure;

... Suitability for producing different types or varieties of crops;

... Farm-to-market access;

.. Water availability; and

... Other community values provided by the property when used as agricultural land, including, but not limited to:

... Viewshed;

... Aquifer recharge;

... Occasional or periodic collector for stormwater runoff;

... Agricultural sector job creation;

.. Migratory bird habitat and forage area; and

.. Educational and curriculum potential.

. In allotting funds for environmental enhancement or restoration projects, the board will require the projects to meet the following criteria:

.. Enhancement or restoration projects must further the ecological functions of the farmlands;

.. The projects, such as fencing, bridging watercourses, replanting native vegetation, replacing culverts, clearing of waterways, etc., must be less than fifty percent of the acquisition cost of the project including any in-kind contribution by any party;

.. The projects should be based on accepted methods of achieving beneficial enhancement or restoration results; and

.. The projects should enhance the viability of the preserved farmland to provide agricultural production while conforming to any legal requirements for habitat protection.

. In determining the acquisition priorities for forestland projects, the board must consider, at a minimum, the following criteria:

.. Community support for the project;

.. A recommendation as part of a limiting factors or critical pathways analysis, a watershed plan or habitat conservation plan, or a coordinated regionwide prioritization effort;

.. The likelihood of conversion of the site to nontimber or more highly developed use;

.. Consistency with a local land use plan, or a regional or statewide recreational or resource plan. The projects that assist in the implementation of local shoreline master plans updated according to RCW 90.58.080 or local comprehensive plans updated according to RCW 36.70A.130 must be highly considered in the process;

.. Multiple benefits of the project;

.. Project attributes, including but not limited to:

... Clean air and water;

... Stormwater management;

... Wildlife habitat; and

... Potential for carbon sequestration.

. In allotting funds for environmental enhancement or restoration projects, the board must require the projects to meet the following criteria:

.. Enhancement or restoration projects must further the ecological functions of the forestlands;

.. The projects, such as fencing, bridging watercourses, replanting native vegetation, replacing culverts, etc., must be less than fifty percent of the acquisition cost of the project including any in-kind contribution by any party;

.. The projects should be based on accepted methods of achieving beneficial enhancement or restoration results;

.. The projects should enhance the viability of the preserved forestland to provide timber production while conforming to any legal requirements for habitat protection.

. Before November 1st of each even-numbered year, the board will recommend to the governor a prioritized list of all projects to be funded under this section. The governor may remove projects from the list recommended by the board and must submit this amended list in the capital budget request to the legislature. The list must include, but not be limited to, a description of each project and any particular match requirement.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6227-S.SL.pdf?cite=2016%20c%20149%20§%2010[2016 c 149 § 10]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1957-S.SL.pdf?cite=2009%20c%20341%20§%205[2009 c 341 § 5]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1813.SL.pdf?cite=2007%20c%20241%20§%2038[2007 c 241 § 38]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5396-S.SL.pdf?cite=2005%20c%20303%20§%207[2005 c 303 § 7]; ]

== 79A.15.140 - Puget Sound partners.
When administering funds under this chapter, the committee shall give preference only to Puget Sound partners, as defined in RCW 90.71.010, in comparison to other entities that are eligible to be included in the definition of Puget Sound partner. Entities that are not eligible to be a Puget Sound partner due to geographic location, composition, exclusion from the scope of the Puget Sound action agenda developed by the Puget Sound partnership under RCW 90.71.310, or for any other reason, shall not be given less preferential treatment than Puget Sound partners.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5372-S.SL.pdf?cite=2007%20c%20341%20§%2035[2007 c 341 § 35]; ]

== 79A.15.150 - Administering funds—Preference to an evergreen community.
When administering funds under this chapter, the recreation and conservation funding board shall give preference only to an evergreen community recognized under RCW 35.105.030 in comparison to other entities that are eligible to receive evergreen community designation. Entities not eligible for designation as an evergreen community shall not be given less preferential treatment than an evergreen community.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2844-S2.SL.pdf?cite=2008%20c%20299%20§%2034[2008 c 299 § 34]; ]

