= 79A.30 - Washington state horse park.
:toc:

== 79A.30.005 - Findings—Purpose.
The legislature finds that:

. Horses are part of a large, highly diverse, and vital industry which provides significant economic, employment, recreational, and educational contributions to residents of and visitors to the state of Washington;

. Currently there is no adequate facility in the Pacific Northwest with the acreage, services, and capacity to host large regional horse shows, national championships, or Olympics-quality events to showcase and promote this important Washington industry;

. Establishing a first-class horse park facility in Washington would meet important needs of the state's horse industry, attract investment, enhance recreational opportunities, and bring new exhibitors and tourists to the state from throughout the region and beyond; and

. A unique opportunity exists to form a partnership between state, county, and private interests to create a major horse park facility that will provide public recreational opportunities and statewide economic and employment benefits.

It is the purpose of this legislation to create the framework for such a partnership to facilitate development of the Washington state horse park. It is further the intent of the legislature that the state horse park shall be developed in stages, based on factors such as the availability of funds, equipment, and other materials donated by private sources; the availability and willingness of volunteers to work on park development; and the availability of revenues generated by the state horse park as it is developed and utilized.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5403-S.SL.pdf?cite=1995%20c%20200%20§%201[1995 c 200 § 1]; ]

== 79A.30.010 - Definitions.
Unless the context clearly indicates otherwise, the definitions in this section apply throughout this chapter.

. "Authority" means the Washington state horse park authority authorized to be created in RCW 79A.30.030.

. "Commission" means the Washington state parks and recreation commission.

. "Horses" includes all domesticated members of the taxonomic family Equidae, including but not limited to horses, donkeys, and mules.

. "State horse park" means the Washington state horse park established in RCW 79A.30.020.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2399-S.SL.pdf?cite=2000%20c%2011%20§%2083[2000 c 11 § 83]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5403-S.SL.pdf?cite=1995%20c%20200%20§%202[1995 c 200 § 2]; ]

== 79A.30.020 - Park established—Site approval—Ownership of land—Development, promotion, operation, management, and maintenance.
. The Washington state horse park is hereby established, to be located at a site approved by the commission. In approving a site for the state horse park, the commission shall consider areas with large blocks of land suitable for park development, the distance to various population centers in the state, the ease of transportation to the site for large vehicles traveling along either a north-south or an east-west corridor, and other factors deemed important by the commission.

. Ownership of land for the state horse park shall be as follows:

.. The commission is vested with and shall retain ownership of land provided by the state for the state horse park. Any lands acquired by the commission after July 23, 1995, for the state horse park shall be purchased under chapter 79A.15 RCW. The legislature encourages the commission to provide a long-term lease of the selected property to the Washington state horse park authority at a minimal charge. The lease shall contain provisions ensuring public access to and use of the horse park facilities, and generally maximizing public recreation opportunities at the horse park, provided that the facility remains available primarily for horse-related activities.

.. Land provided for the state horse park by the county in which the park is located shall remain in the ownership of that county unless the county determines otherwise. The legislature encourages the county to provide a long-term lease of selected property to the Washington state horse park authority at a minimal charge.

.. If the authority acquires additional lands through donations, grants, or other means, or with funds generated from the operation of the state horse park, the authority shall retain ownership of those lands. The authority shall also retain ownership of horse park site improvements paid for by or through donations or gifts to the authority.

. Development, promotion, operation, management, and maintenance of the state horse park is the responsibility of the authority created in RCW 79A.30.030.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2399-S.SL.pdf?cite=2000%20c%2011%20§%2084[2000 c 11 § 84]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5403-S.SL.pdf?cite=1995%20c%20200%20§%203[1995 c 200 § 3]; ]

== 79A.30.030 - Washington state horse park authority—Formation—Powers—Articles of incorporation—Board.
. A nonprofit corporation may be formed under the nonprofit corporation provisions of chapter 24.03 RCW to carry out the purposes of this chapter. Except as provided in RCW 79A.30.040, the corporation shall have all the powers and be subject to the same restrictions as are permitted or prescribed to nonprofit corporations and shall exercise those powers only for carrying out the purposes of this chapter and those purposes necessarily implied therefrom. The nonprofit corporation shall be known as the Washington state horse park authority. The articles of incorporation shall provide that it is the responsibility of the authority to develop, promote, operate, manage, and maintain the Washington state horse park. The articles of incorporation shall provide for appointment of directors and other conduct of business consistent with the requirements of this chapter.

. [Empty]
.. The articles of incorporation shall provide for an eleven-member board of directors for the authority, all appointed by the commission. Board members shall serve three-year terms, except that two of the original appointees shall serve one-year terms, and two of the original appointees shall serve two-year terms. Of the board members appointed pursuant to chapter 31, Laws of 2013, one shall serve an initial one-year term, one shall serve an initial two-year term, and two shall serve an initial term of three years. A board member may serve consecutive terms.

.. The articles of incorporation shall provide that the commission appoint board members as follows:

... One board member shall represent the interests of the commission;

... One board member shall represent the interests of the county in which the park is located. In making this appointment, the commission shall solicit recommendations from the county legislative authority; and

... Nine board members shall represent the geographic and sports discipline diversity of equestrian interests in the state, and at least three of these members shall have business experience relevant to the organization of horse shows or operation of a horse show facility. In making these appointments, the commission shall solicit recommendations from a variety of active horse-related organizations in the state.

. The articles of incorporation shall include a policy that provides for the preferential use of a specific area of the horse park facilities at nominal cost for horse groups associated with youth groups and individuals with disabilities.

. The commission shall make appointments to fill board vacancies for positions authorized under subsection (2) of this section, upon additional solicitation of recommendations from the board of directors.

. The board of directors shall perform their duties in the best interests of the authority, consistent with the standards applicable to directors of nonprofit corporations under RCW 24.03.127.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5212.SL.pdf?cite=2013%20c%2031%20§%202[2013 c 31 § 2]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1371-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2021%20§%2032[2011 1st sp.s. c 21 § 32]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2399-S.SL.pdf?cite=2000%20c%2011%20§%2085[2000 c 11 § 85]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5403-S.SL.pdf?cite=1995%20c%20200%20§%204[1995 c 200 § 4]; ]

== 79A.30.040 - Washington state horse park authority—Powers.
To meet its responsibility for developing, promoting, operating, managing, and maintaining the state horse park, the authority is empowered to do the following:

. Exercise the general powers authorized for any nonprofit corporation as specified in RCW 24.03.035. All debts of the authority shall be in the name of the authority and shall not be debts of the state of Washington for which the state or any state agency shall have any obligation to pay; and the authority may not issue bonds. Neither the full faith and credit of the state nor the state's taxing power is pledged for any indebtedness of the authority;

. Employ and discharge at its discretion employees, agents, advisors, and other personnel;

. Apply for or solicit, accept, administer, and dispose of grants, gifts, and bequests of money, services, securities, real estate, or other property. However, if the authority accepts a donation designated for a specific purpose, the authority shall use the donation for the designated purpose;

. Establish, revise, collect, manage, and expend such fees and charges at the state horse park as the authority deems necessary to accomplish its responsibilities;

. Make such expenditures as are appropriate for paying the administrative costs and expenses of the authority and the state horse park;

. Authorize use of the state horse park facilities by the general public and by and for compatible nonequestrian events as the authority deems reasonable, so long as the primacy of the center for horse-related purposes is not compromised;

. Insure its obligations and potential liability;

. Enter into cooperative agreements with and provide for private nonprofit groups to use the state horse park facilities and property to raise money to contribute gifts, grants, and support to the authority for the purposes of this chapter;

. Grant concessions or leases at the state horse park upon such terms and conditions as the authority deems appropriate, but in no event shall the term of a concession or lease exceed twenty-five years. Concessions and leases shall be consistent with the purposes of this chapter and may be renegotiated at least every five years; and

. Generally undertake any and all lawful acts necessary or appropriate to carry out the purposes for which the authority and the state horse park are created.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5403-S.SL.pdf?cite=1995%20c%20200%20§%205[1995 c 200 § 5]; ]

== 79A.30.050 - Collaboration by authority and state on projects of shared interest—Cooperation with groups for youth recreational activities.
. If the authority and state agencies find it mutually beneficial to do so, they are authorized to collaborate and cooperate on projects of shared interest. Agencies authorized to collaborate with the authority include but are not limited to: The commission for activities and projects related to public recreation; the department of agriculture for projects related to the equine agricultural industry; the *department of community, trade, and economic development with respect to community and economic development and tourism issues associated with development of the state horse park; Washington State University with respect to opportunities for animal research, education, and extension; the department of ecology with respect to opportunities for making the state horse park's waste treatment facilities a demonstration model for the handling of waste to protect water quality; and with local community colleges with respect to programs related to horses, economic development, business, and tourism.

. The authority shall cooperate with 4-H clubs, pony clubs, youth groups, and local park departments to provide youth recreational activities. The authority shall also provide for preferential use of an area of the horse park facility for youth and the disabled at nominal cost.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5403-S.SL.pdf?cite=1995%20c%20200%20§%206[1995 c 200 § 6]; ]

