= 42.08 - Official bonds.
:toc:

== 42.08.005 - Official bonds—Payment of premiums.
See RCW 48.28.040.

[ ]

== 42.08.010 - Scope of coverage.
The official bond of a public officer, to the state, or to any county, city, town or other municipal or public corporation of like character therein, shall be deemed a security to the state, or to such county, city, town or other municipal or public corporation, as the case may be, and also to all persons severally, for the official delinquencies against which it is intended to provide.

[ Code 1881 § 652; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20135%20§%20655[1877 p 135 § 655]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20152%20§%20592[1869 p 152 § 592]; RRS § 958; ]

== 42.08.020 - Who may maintain action.
When a public officer by official misconduct or neglect of duty, shall forfeit his or her official bond or render his or her sureties therein liable upon such bond, any person injured by such misconduct or neglect, or who is by law entitled to the benefit of the security, may maintain an action at law thereon in his or her own name against the officer and his or her sureties to recover the amount to which he or she may by reason thereof be entitled.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%2095[2012 c 117 § 95]; Code 1881 § 653; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20135%20§%20656[1877 p 135 § 656]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20152%20§%20593[1869 p 152 § 593]; RRS § 959; ]

== 42.08.030 - Leave of court required.
Before an action can be commenced by a plaintiff, other than the state, or the municipal or public corporation named in the bond, leave shall be obtained of the court or judge thereof where the action is triable. Such leave shall be granted upon the production of a certified copy of the bond and an affidavit of the plaintiff, or some person in his or her behalf, showing the delinquency. But if the matter set forth in his or her affidavit be such that, if true, the party applying would clearly not be entitled to recover in the action, the leave shall not be granted. If it does not appear from the complaint that the leave herein provided for has been granted, the defendant, on motion, shall be entitled to judgment of nonsuit; if it does, the defendant may controvert the allegation, and if the issue be found in his or her favor, judgment shall be given accordingly.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%2096[2012 c 117 § 96]; Code 1881 § 654; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20136%20§%20657[1877 p 136 § 657]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20152%20§%20594[1869 p 152 § 594]; RRS § 960; ]

== 42.08.040 - Judgment no bar to further action.
A judgment in favor of a party for one delinquency shall not preclude the same or another party from maintaining another action on the same bond for another delinquency.

[ Code 1881 § 655; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20136%20§%20658[1877 p 136 § 658]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20153%20§%20595[1869 p 153 § 595]; RRS § 961; ]

== 42.08.050 - Recoveries limited to amount of bond.
In an action upon an official bond, if judgments have been recovered against the surety therein other than by confession, equal in the aggregate to the penalty or any part thereof of such bond, and if such recovery be established on the trial, judgment shall not be given against such surety for an amount exceeding such penalty, or such portion thereof as is not already recovered against him or her.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%2097[2012 c 117 § 97]; Code 1881 § 656; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20136%20§%20659[1877 p 136 § 659]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20153%20§%20596[1869 p 153 § 596]; RRS § 962; ]

== 42.08.060 - Form of official bonds.
All official bonds required by law of officers shall be in form, joint and several, and made payable to the state of Washington, in such penal sum and with such conditions as may be required by law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c34.pdf?cite=1890%20p%2034%20§%201[1890 p 34 § 1]; RRS § 9930; ]

== 42.08.070 - Effect of bonds.
Every official bond executed by any officer pursuant to law shall be deemed and taken to be in force, and shall be obligatory upon the principal and sureties therein for any and all breach of the condition or conditions thereof committed during the time such officer shall continue to discharge any of the duties of, or hold such office, and every such bond shall be deemed to be in force and obligatory upon the principal and sureties therein for the faithful discharge of all duties which may be required of such officer by any law enacted subsequent to the execution of such bond, and such condition shall be expressed therein.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c34.pdf?cite=1890%20p%2034%20§%202[1890 p 34 § 2]; RRS § 9931; ]

== 42.08.080 - Who may bring action on bond.
Every official bond executed by any officer pursuant to law, shall be in force and obligatory upon the principal and sureties therein, to and for the state of Washington, and to and for the use and benefit of all persons who may be injured or aggrieved by the wrongful act or default of such officer, in his official capacity, and any person so injured or aggrieved may bring suit on such bond in his or her own name without an assignment thereof.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c34.pdf?cite=1890%20p%2034%20§%203[1890 p 34 § 3]; RRS § 9932; ]

== 42.08.090 - Defective bonds validated.
Whenever any such official bond shall not contain the substantial matter or condition or conditions required by law, or there shall be any defect in the approval or filing thereof, such bond shall not be void so as to discharge such officer and his or her sureties, but they shall be bound to the state, or party interested, and the state or such party may, by action instituted in any court of competent jurisdiction, suggest the defect of such bond or such approval or filing, and recover his or her proper and equitable demand or damages from such officer, and the person or persons, who intended to become, and were included in such bond as sureties.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%2098[2012 c 117 § 98]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c35.pdf?cite=1890%20p%2035%20§%204[1890 p 35 § 4]; RRS § 9933; ]

== 42.08.100 - Approval and filing.
The official bonds of officers shall be approved and filed as follows, to wit: The official bond of the secretary of state shall be approved by the governor and filed in the office of the state auditor. The official bonds of all other state officers required by law to give bonds, except as otherwise expressly provided by law, shall be approved by the governor and filed in the office of the secretary of state.

The official bonds of all county and township officers, except the county superintendent of schools, shall be approved by the board of county commissioners, if in session, and if not in session, by the chair of such board, and filed and recorded in the office of the county clerk of their respective counties: PROVIDED, That the bond of the county clerk shall be recorded in the office of the county auditor and filed in the office of the county treasurer.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%2099[2012 c 117 § 99]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c157.pdf?cite=1955%20c%20157%20§%2011[1955 c 157 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c35.pdf?cite=1890%20p%2035%20§%205[1890 p 35 § 5]; RRS § 9934; ]

== 42.08.110 - Procedure when bond of county or township officer is insufficient.
Whenever the sureties, or any one of them, in the official bond of any county or township officer shall die, remove from the state, become insolvent or insufficient, or the penalty of such bond shall become insufficient, on account of recoveries had thereon, or otherwise, it shall be the duty of the board of county commissioners of the proper county, of their own motion, or on the showing of any person, supported by affidavit, to summon any such officer to appear before them at a stated time, not less than five days after service of such summons, and show cause why he or she should not execute an additional official bond with good and sufficient sureties.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20100[2012 c 117 § 100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c35.pdf?cite=1890%20p%2035%20§%206[1890 p 35 § 6]; RRS § 9935; ]

== 42.08.120 - Additional bond.
Should such officer, after due notice, fail to appear at the time appointed, the matter may be heard and determined in his or her absence; if after examination the board of county commissioners shall be of opinion that the bond of such officer has become insufficient from any cause whatever, they shall require an additional bond with such security as may be deemed necessary, which said additional bond shall be executed and filed within such time as the board of county commissioners may order; and if any such officer shall fail to execute and file such additional bond within the time prescribed by such order, his or her office shall become vacant.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20101[2012 c 117 § 101]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c36.pdf?cite=1890%20p%2036%20§%207[1890 p 36 § 7]; RRS § 9936; ]

== 42.08.130 - Remedy when bond of state officer becomes insufficient.
Whenever the official bond of any state officer shall become insufficient from any cause whatever, the like proceedings may be had before the superior court of the county in which said state officer holds his or her office with reference thereto: PROVIDED, That such proceedings may be commenced by a written motion supported by affidavit.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20102[2012 c 117 § 102]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c36.pdf?cite=1890%20p%2036%20§%208[1890 p 36 § 8]; RRS § 9937; ]

== 42.08.140 - Force of additional bond.
Every such additional bond shall be of like force and obligation upon the principal and sureties therein, and shall subject the officer and his or her sureties to the same liabilities as are prescribed respecting the original bonds of officers.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20103[2012 c 117 § 103]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c36.pdf?cite=1890%20p%2036%20§%209[1890 p 36 § 9]; RRS § 9938; ]

== 42.08.150 - Number of sureties.
Unless otherwise expressly provided, there shall be at least two sureties upon the official bond of every officer.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c36.pdf?cite=1890%20p%2036%20§%2010[1890 p 36 § 10]; RRS § 9939; ]

== 42.08.160 - Justification of sureties.
In all cases where official bonds are required or may be hereafter required, from state, county, township, or precinct officers, the officer or officers whose duty it is or may be to approve such bonds, shall not accept or approve any such bonds except such bond be that of a surety company, unless the sureties thereon shall severally justify before an officer authorized to administer oaths as follows: (1) On a bond given by a state or county officer that he or she is a resident and freeholder within this state, and on a bond given by a township or precinct officer that he or she is a resident and freeholder within the county in which such township or precinct is situated. (2) That he or she is worth double the amount for which he or she becomes surety over and above all his or her debts and liabilities, in property situated within this state which is not exempt from seizure and sale under execution.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20104[2012 c 117 § 104]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1901c14.pdf?cite=1901%20c%2014%20§%201[1901 c 14 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c36.pdf?cite=1890%20p%2036%20§%2011[1890 p 36 § 11]; RRS § 9940; ]

== 42.08.170 - Liability of sureties.
When the penal sum of any bond amounts to more than two thousand dollars, the sureties may become severally liable for portions, not less than five hundred dollars, of such penal sum, making in the aggregate at least two sureties for the whole penal sum.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c37.pdf?cite=1890%20p%2037%20§%2012[1890 p 37 § 12]; RRS § 9941; ]

== 42.08.180 - Release of sureties.
Release of sureties (1937 act), see chapter 19.72 RCW.

[ ]

