= 42.20 - Misconduct of public officers.
:toc:

== 42.20.020 - Powers may not be delegated for profit.
Every public officer who, for any reward, consideration, or gratuity paid or agreed to be paid, shall, directly or indirectly, grant to another the right or authority to discharge any function of his or her office, or permit another to perform any of his or her duties, shall be guilty of a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20113[2012 c 117 § 113]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%2083[1909 c 249 § 83]; RRS § 2335; ]

== 42.20.030 - Intrusion into and refusal to surrender public office.
Every person who shall falsely personate or represent any public officer, or who shall willfully intrude himself or herself into a public office to which he or she has not been duly elected or appointed, or who shall willfully exercise any of the functions or perform any of the duties of such officer, without having duly qualified therefor, as required by law, or who, having been an executive or administrative officer, shall willfully exercise any of the functions of his or her office after his or her right to do so has ceased, or wrongfully refuse to surrender the official seal or any books or papers appertaining to such office, upon the demand of his or her lawful successor, shall be guilty of a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20114[2012 c 117 § 114]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%2084[1909 c 249 § 84]; RRS § 2336; ]

== 42.20.040 - False report.
Every public officer who shall knowingly make any false or misleading statement in any official report or statement, under circumstances not otherwise prohibited by law, shall be guilty of a gross misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%2098[1909 c 249 § 98]; RRS § 2350; ]

== 42.20.050 - Public officer making false certificate.
Every public officer who, being authorized by law to make or give a certificate or other writing, shall knowingly make and deliver as true such a certificate or writing containing any statement which he or she knows to be false, in a case where the punishment thereof is not expressly prescribed by law, shall be guilty of a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20115[2012 c 117 § 115]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20128[1909 c 249 § 128]; RRS § 2380; ]

== 42.20.060 - Falsely auditing and paying claims.
Every public officer, or person holding or discharging the duties of any public office or place of trust under the state or in any county, town or city, a part of whose duty it is to audit, allow or pay, or take part in auditing, allowing or paying, claims or demands upon the state or such county, town or city, who shall knowingly audit, allow or pay, or, directly or indirectly, consent to or in any way connive at the auditing, allowance or payment of any claim or demand against the state or such county, town or city, which is false or fraudulent or contains any charge, item or claim which is false or fraudulent, shall be guilty of a gross misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20129[1909 c 249 § 129]; RRS § 2381; ]

== 42.20.070 - Misappropriation and falsification of accounts by public officer.
Every public officer, and every other person receiving money on behalf or for or on account of the people of the state or of any department of the state government or of any bureau or fund created by law in which the people are directly or indirectly interested, or for or on account of any county, city, town, or any school, diking, drainage, or irrigation district, who:

. Appropriates to his or her own use or the use of any person not entitled thereto, without authority of law, any money so received by him or her as such officer or otherwise; or

. Knowingly keeps any false account, or makes any false entry or erasure in any account, of or relating to any money so received by him or her; or

. Fraudulently alters, falsifies, conceals, destroys, or obliterates any such account; or

. Willfully omits or refuses to pay over to the state, its officer or agent authorized by law to receive the same, or to such county, city, town, or such school, diking, drainage, or irrigation district or to the proper officer or authority empowered to demand and receive the same, any money received by him or her as such officer when it is a duty imposed upon him or her by law to pay over and account for the same,

is guilty of a class B felony and shall be punished by imprisonment in a state correctional facility for not more than fifteen years.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20219[2003 c 53 § 219]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2263-S.SL.pdf?cite=1992%20c%207%20§%2037[1992 c 7 § 37]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20317[1909 c 249 § 317]; RRS § 2569; Code 1881 § 890; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20202%20§%2092[1873 p 202 § 92]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%2091%20§%2083[1854 p 91 § 83]; ]

== 42.20.080 - Other violations by officers.
Every officer or other person mentioned in RCW 42.20.070, who shall willfully disobey any provision of law regulating his or her official conduct in cases other than those specified in said section, shall be guilty of a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20116[2012 c 117 § 116]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20318[1909 c 249 § 318]; RRS § 2570; ]

== 42.20.090 - Misappropriation, etc., by treasurer.
Every state, county, city, or town treasurer who willfully misappropriates any moneys, funds, or securities received by or deposited with him or her as such treasurer, or who shall be guilty of any other malfeasance or willful neglect of duty in his or her office, is guilty of a class C felony and shall be punished by imprisonment in a state correctional facility for not more than five years or by a fine of not more than five thousand dollars.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20220[2003 c 53 § 220]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2263-S.SL.pdf?cite=1992%20c%207%20§%2038[1992 c 7 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20319[1909 c 249 § 319]; RRS § 2571; ]

== 42.20.100 - Failure of duty by public officer a misdemeanor.
Whenever any duty is enjoined by law upon any public officer or other person holding any public trust or employment, their wilful neglect to perform such duty, except where otherwise specially provided for, shall be a misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%2016[1909 c 249 § 16]; RRS § 2268; Code 1881 § 889; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%2090%20§%2082[1854 p 90 § 82]; ]

== 42.20.110 - Improper conduct by certain justices.
It shall be a misdemeanor for any judge or justice of any court not of record, during the hearing of any cause or proceeding therein, to address any person in his or her presence in unfit, unseemly, or improper language.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20117[2012 c 117 § 117]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c115.pdf?cite=1911%20c%20115%20§%201[1911 c 115 § 1]; RRS § 2696-1; ]

