= 42.26 - Agency vendor payment revolving fund—Petty cash accounts.
:toc:

== 42.26.020 - Disbursements—Deposits to cover.
The amount to be disbursed from the vendor payment revolving fund on behalf of an agency electing to utilize such fund shall be deposited therein by the agency on or before the day prior to scheduled disbursement. The deposit shall be made from funds held by the agency outside the state treasury pursuant to law and which are properly chargeable for the disbursement. Disbursements from the revolving fund created by this chapter shall be by warrant in accordance with the provisions of RCW 43.88.160.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c60.pdf?cite=1969%20ex.s.%20c%2060%20§%202[1969 ex.s. c 60 § 2]; ]

== 42.26.030 - Regulations.
The director of financial management shall adopt such regulations as may be necessary or desirable to implement the provisions of this chapter relating to the establishment of an agency vendor payment revolving fund.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c151.pdf?cite=1979%20c%20151%20§%2074[1979 c 151 § 74]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c60.pdf?cite=1969%20ex.s.%20c%2060%20§%203[1969 ex.s. c 60 § 3]; ]

== 42.26.040 - Petty cash accounts—Authorized—Advancements.
The state treasurer is authorized to advance moneys from treasury funds to state agencies for the purpose of establishing petty cash accounts. Any agency may petition the office of financial management for the establishment of a petty cash account. The maximum amount of such accounts shall be based on the special needs of the petitioning agency and shall be subject to approval by the office of financial management. The amount so advanced shall be reflected in the state treasurer's accounts as an amount due from the agency to the fund or account from which the advance was made.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c151.pdf?cite=1979%20c%20151%20§%2075[1979 c 151 § 75]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977c40.pdf?cite=1977%20c%2040%20§%201[1977 c 40 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c60.pdf?cite=1969%20ex.s.%20c%2060%20§%204[1969 ex.s. c 60 § 4]; ]

== 42.26.050 - Request for petty cash advancement—Approval.
The agency requesting a petty cash account or an increase in the amount of petty cash advanced under the provisions of this chapter shall submit its request to the director of financial management in the form and detail prescribed by him or her. The agency's written request and the approval authorized by this chapter shall be the only documentation or certification required as a condition precedent to the issuance of such warrant. A copy of his or her approval shall be forwarded by the director of financial management to the state treasurer.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20122[2012 c 117 § 122]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c151.pdf?cite=1979%20c%20151%20§%2076[1979 c 151 § 76]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c60.pdf?cite=1969%20ex.s.%20c%2060%20§%205[1969 ex.s. c 60 § 5]; ]

== 42.26.060 - Restrictions on use of petty cash account—Expenditures—Reimbursement.
The use of the petty cash account shall be restricted to miscellaneous petty or emergency expenditures, refunds legally payable by an agency, and for cash change to be used in the transaction of the agency's official business. All expenditures made from petty cash shall be charged to an existing appropriation for such purpose, except expenditures chargeable against funds for which no appropriation is required by law. All expenditures or refunds made from petty cash shall be reimbursed out of and charged to the proper appropriation or fund at the close of each month and such other times as may be necessary.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c60.pdf?cite=1969%20ex.s.%20c%2060%20§%206[1969 ex.s. c 60 § 6]; ]

== 42.26.070 - Custodian of petty cash account—Bond.
The head of the agency or an employee designated by him or her shall have full responsibility as custodian for the petty cash account and its proper use under this chapter and applicable regulations of the director of financial management. The custodian of the petty cash account shall be covered by a surety bond in the full amount of the account at all times and all advances to it, conditioned upon the proper accounting for and legal expenditure of all such funds, in addition to other conditions required by law.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20123[2012 c 117 § 123]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c151.pdf?cite=1979%20c%20151%20§%2077[1979 c 151 § 77]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c60.pdf?cite=1969%20ex.s.%20c%2060%20§%207[1969 ex.s. c 60 § 7]; ]

== 42.26.080 - Violation of petty cash account requirements.
If a post audit by the state auditor discloses the amount of the petty cash account of any agency under this chapter to be excessive or the use of the account to be in violation of requirements governing its operation, the director of financial management may require the return of the account or of the excessive amount to the state treasury for credit to the fund from which the advance was made.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c151.pdf?cite=1979%20c%20151%20§%2078[1979 c 151 § 78]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c60.pdf?cite=1969%20ex.s.%20c%2060%20§%208[1969 ex.s. c 60 § 8]; ]

== 42.26.090 - Regulations for petty cash and accounts.
The director of financial management shall adopt such regulations as may be necessary or desirable to implement the provisions of this chapter. Such regulation shall include but not be limited to, (1) defining limitations on the use of petty cash, and (2) providing accounting and reporting procedures for operation of the petty cash account.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c151.pdf?cite=1979%20c%20151%20§%2079[1979 c 151 § 79]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c60.pdf?cite=1969%20ex.s.%20c%2060%20§%209[1969 ex.s. c 60 § 9]; ]

== 42.26.900 - Effective date—1969 ex.s. c 60.
This chapter shall take effect July 1, 1969.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c60.pdf?cite=1969%20ex.s.%20c%2060%20§%2012[1969 ex.s. c 60 § 12]; ]

