= 42.41 - Local government whistleblower protection.
:toc:

== 42.41.010 - Policy.
It is the policy of the legislature that local government employees should be encouraged to disclose, to the extent not expressly prohibited by law, improper governmental actions of local government officials and employees. The purpose of this chapter is to protect local government employees who make good-faith reports to appropriate governmental bodies and to provide remedies for such individuals who are subjected to retaliation for having made such reports.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6321-S.SL.pdf?cite=1992%20c%2044%20§%201[1992 c 44 § 1]; ]

== 42.41.020 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. [Empty]
.. "Improper governmental action" means any action by a local government officer or employee:

... That is undertaken in the performance of the officer's or employee's official duties, whether or not the action is within the scope of the employee's employment; and

... That is in violation of any federal, state, or local law or rule, is an abuse of authority, is of substantial and specific danger to the public health or safety, or is a gross waste of public funds.

.. "Improper governmental action" does not include personnel actions including but not limited to employee grievances, complaints, appointments, promotions, transfers, assignments, reassignments, reinstatements, restorations, reemployments, performance evaluations, reductions in pay, dismissals, suspensions, demotions, violations of the local government collective bargaining and civil service laws, alleged labor agreement violations, reprimands, or any action that may be taken under chapter 41.08, 41.12, 41.14, 41.56, 41.59, or 53.18 RCW or RCW 54.04.170 and 54.04.180.

. "Local government" means any governmental entity other than the state, federal agencies, or an operating system established under chapter 43.52 RCW. It includes, but is not limited to cities, counties, school districts, and special purpose districts.

. "Retaliatory action" means: (a) Any adverse change in a local government employee's employment status, or the terms and conditions of employment including denial of adequate staff to perform duties, frequent staff changes, frequent and undesirable office changes, refusal to assign meaningful work, unwarranted and unsubstantiated letters of reprimand or unsatisfactory performance evaluations, demotion, transfer, reassignment, reduction in pay, denial of promotion, suspension, dismissal, or any other disciplinary action; or (b) hostile actions by another employee towards a local government employee that were encouraged by a supervisor or senior manager or official.

. "Emergency" means a circumstance that if not immediately changed may cause damage to persons or property.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1159-S.SL.pdf?cite=1994%20c%20210%20§%201[1994 c 210 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6321-S.SL.pdf?cite=1992%20c%2044%20§%202[1992 c 44 § 2]; ]

== 42.41.030 - Right to report improper governmental action—Policies and procedures.
. Every local government employee has the right to report to the appropriate person or persons information concerning an alleged improper governmental action.

. The governing body or chief administrative officer of each local government shall adopt a policy on the appropriate procedures to follow for reporting such information and shall provide information to their employees on the policy. Local governments are encouraged to consult with their employees on the policy.

. The policy shall describe the appropriate person or persons within the local government to whom to report information and a list of appropriate person or persons outside the local government to whom to report. The list shall include the county prosecuting attorney.

. Each local government shall permanently post a summary of the procedures for reporting information on an alleged improper governmental action and the procedures for protection against retaliatory actions described in RCW 42.41.040 in a place where all employees will have reasonable access to it. A copy of the summary shall be made available to any employee upon request.

. A local government may require as part of its policy that, except in the case of an emergency, before an employee provides information of an improper governmental action to a person or an entity who is not a public official or a person listed pursuant to subsection (3) of this section, the employee shall submit a written report to the local government. Where a local government has adopted such a policy under this section, an employee who fails to make a good faith attempt to follow the policy shall not receive the protections of this chapter.

. If a local government has failed to adopt a policy as required by subsection (2) of this section, an employee may report alleged improper government action directly to the county prosecuting attorney or, if the prosecuting attorney or an employee of the prosecuting attorney participated in the alleged improper government action, to the state auditor. The cost incurred by the state auditor in such investigations shall be paid by the local government through the municipal revolving account authorized in RCW 43.09.282.

. The identity of a reporting employee shall be kept confidential to the extent possible under law, unless the employee authorizes the disclosure of his or her identity in writing.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1583.SL.pdf?cite=1995%20c%20213%20§%201[1995 c 213 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6321-S.SL.pdf?cite=1992%20c%2044%20§%203[1992 c 44 § 3]; ]

== 42.41.040 - Retaliatory action unlawful—Relief by whistleblower—Penalty.
. It is unlawful for any local government official or employee to take retaliatory action against a local government employee because the employee provided information in good faith in accordance with the provisions of this chapter that an improper governmental action occurred.

. In order to seek relief under this chapter, a local government employee shall provide a written notice of the charge of retaliatory action to the governing body of the local government that:

.. Specifies the alleged retaliatory action; and

.. Specifies the relief requested.

. The charge shall be delivered to the local government no later than thirty days after the occurrence of the alleged retaliatory action. The local government has thirty days to respond to the charge of retaliatory action and request for relief.

. Upon receipt of either the response of the local government or after the last day upon which the local government could respond, the local government employee may request a hearing to establish that a retaliatory action occurred and to obtain appropriate relief as defined in this section. The request for a hearing shall be delivered to the local government within fifteen days of delivery of the response from the local government, or within fifteen days of the last day on which the local government could respond.

. Within five working days of receipt of the request for hearing, the local government shall apply to the state office of administrative hearings for an adjudicative proceeding before an administrative law judge. Except as otherwise provided in this section, the proceedings shall comply with RCW 34.05.410 through 34.05.598.

. The employee, as the initiating party, must prove his or her claim by a preponderance of the evidence. The administrative law judge shall issue a final decision consisting of findings of fact, conclusions of law, and judgment no later than forty-five days after the date the request for hearing was delivered to the local government. The administrative law judge may grant specific extensions of time beyond this period of time for rendering a decision at the request of either party upon a showing of good cause, or upon his or her own motion.

. Relief that may be granted by the administrative law judge consists of reinstatement, with or without back pay, and such injunctive relief as may be found to be necessary in order to return the employee to the position he or she held before the retaliatory action and to prevent any recurrence of retaliatory action. The administrative law judge may award costs and reasonable attorneys' fees to the prevailing party.

. If a determination is made that retaliatory action has been taken against the employee, the administrative law judge may, in addition to any other remedy, impose a civil penalty personally upon the retaliator of up to three thousand dollars payable by each person found to have retaliated against the employee and recommend to the local government that any person found to have retaliated against the employee be suspended with or without pay or dismissed. All penalties recovered shall be paid to the local government administrative hearings account created in RCW 42.41.060.

. The final decision of the administrative law judge is subject to judicial review under the arbitrary and capricious standard. Relief ordered by the administrative law judge may be enforced by petition to superior court.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6321-S.SL.pdf?cite=1992%20c%2044%20§%204[1992 c 44 § 4]; ]

== 42.41.045 - Prohibition on intimidation of whistleblower—Nondisclosure of protected information.
. A local government official or employee may not use his or her official authority or influence, directly or indirectly, to threaten, intimidate, or coerce an employee for the purpose of interfering with that employee's right to disclose information concerning an improper governmental action in accordance with the provisions of this chapter.

. Nothing in this section authorizes an individual to disclose information prohibited by law.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1159-S.SL.pdf?cite=1994%20c%20210%20§%202[1994 c 210 § 2]; ]

== 42.41.050 - Exemptions.
Any local government that has adopted or adopts a program for reporting alleged improper governmental actions and adjudicating retaliation resulting from such reporting shall be exempt from this chapter if the program meets the intent of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6321-S.SL.pdf?cite=1992%20c%2044%20§%206[1992 c 44 § 6]; ]

== 42.41.060 - Local government administrative hearings account.
The local government administrative hearings account is created in the custody of the state treasurer. All receipts from penalties in RCW 42.41.040 and the surcharges under RCW 43.09.2801 shall be deposited into the account. Expenditures from the account may be used only for administrative hearings under this chapter. Only the chief administrative law judge or his or her designee may authorize expenditures from the account. The account is subject to allotment procedures under chapter 43.88 RCW, but no appropriation is required for expenditures.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6321-S.SL.pdf?cite=1992%20c%2044%20§%207[1992 c 44 § 7]; ]

== 42.41.900 - Construction.
This chapter shall not be construed to permit disclosures that would diminish the rights of any person to the continued protection of confidentiality of communications where statute or common law provides such protection.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6321-S.SL.pdf?cite=1992%20c%2044%20§%205[1992 c 44 § 5]; ]

== 42.41.901 - Effective dates—1992 c 44.
Sections 1 through 10 of this act shall take effect January 1, 1993. Section 11 of this act shall take effect July 1, 1992.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6321-S.SL.pdf?cite=1992%20c%2044%20§%2013[1992 c 44 § 13]; ]

