= 42.60 - Religious affiliation nondisclosure.
:toc:

== 42.60.010 - Findings.
The legislature finds and declares the following:

. Washington state celebrates the rich cultural heritage and diversity of its residents; and

. Freedom of religion and protection from persecution on the basis of religion is one of the founding ideals of the nation.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2097.SL.pdf?cite=2018%20c%20303%20§%201[2018 c 303 § 1]; ]

== 42.60.020 - Prohibitions—Government agencies and public employees.
A state or local government agency or public employee shall not:

. Provide or disclose to federal government authorities personally identifiable information regarding the religious beliefs, practices, or affiliation of any individual, except where the employee is a witness to a crime;

. Use public funds, facilities, property, equipment, or personnel to assist in creation, implementation, or enforcement of any government program compiling a list, registry, or database of personally identifiable information about individuals based on religious beliefs, practice, or affiliation, for law enforcement or immigration purposes; or

. Make personally identifiable information from agency databases available, including any databases maintained by private vendors contracting with the agency, to anyone or any entity for the purpose of investigation or enforcement under any government program compiling a list, registry, or database of individuals based on religious belief, practice, or affiliation, or national origin, or ethnicity for law enforcement or immigration purposes.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2097.SL.pdf?cite=2018%20c%20303%20§%203[2018 c 303 § 3]; ]

== 42.60.030 - Prohibitions—Law enforcement agencies.
State and local law enforcement agencies shall not:

. Collect information on the religious belief, practice, or affiliation of any individual except (a) as part of a criminal investigation of an individual based on reasonable suspicion that the individual has engaged in criminal activity, and when there is a nexus between the criminal activity and the specific information collected about religious belief, practice, or affiliation, or (b) where necessary to provide religious accommodations; or

. Use public funds, facilities, property, equipment, or personnel to investigate, enforce, or assist in the investigation or enforcement of any criminal, civil, or administrative violation, or warrant for a violation, of any requirement that individuals register with the federal government or any federal agency based on religion.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2097.SL.pdf?cite=2018%20c%20303%20§%204[2018 c 303 § 4]; ]

== 42.60.040 - Agreements in conflict with chapter.
Any agreements in existence on June 7, 2018, that make any state or local government agency information or database available in conflict with the terms of this chapter are terminated on that date to the extent of the conflict.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2097.SL.pdf?cite=2018%20c%20303%20§%205[2018 c 303 § 5]; ]

