= 71.02 - Mental illness—Reimbursement of costs for treatment.
:toc:

== 71.02.490 - Authority over patient—Federal agencies, private establishments.
The United States veterans' administration, or other United States government agency, or the chief officer of a private facility shall have the same powers as are conferred upon the superintendent of a state hospital with reference to retention, transfer, parole, or discharge of mentally ill persons ordered hospitalized in their facilities.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c25.pdf?cite=1959%20c%2025%20§%2071.02.490[1959 c 25 § 71.02.490]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c139.pdf?cite=1951%20c%20139%20§%2026[1951 c 139 § 26]; ]

== 71.02.900 - Construction and purpose—1959 c 25.
The provisions of this chapter shall be liberally construed so that persons who are in need of care and treatment for mental illness shall receive humane care and treatment and be restored to normal mental condition as rapidly as possible with an avoidance of loss of civil rights where not necessary, and with as little formality as possible, still preserving all rights and all privileges of the person as guaranteed by the Constitution.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c25.pdf?cite=1959%20c%2025%20§%2071.02.900[1959 c 25 § 71.02.900]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c139.pdf?cite=1951%20c%20139%20§%201[1951 c 139 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c198.pdf?cite=1949%20c%20198%20§%201[1949 c 198 § 1]; Rem. Supp. 1949 § 6953-1; ]

