= 71.06 - Sexual psychopaths.
:toc:

== 71.06.005 - Application of chapter.
With respect to sexual psychopaths, this chapter applies only to crimes or offenses committed before July 1, 1984.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c209.pdf?cite=1984%20c%20209%20§%2027[1984 c 209 § 27]; ]

== 71.06.010 - Definitions.
As used in this chapter, the following terms shall have the following meanings:

"Psychopathic personality" means the existence in any person of such hereditary, congenital, or acquired condition affecting the emotional or volitional rather than the intellectual field and manifested by anomalies of such character as to render satisfactory social adjustment of such person difficult or impossible.

"Sexual psychopath" means any person who is affected in a form of psychoneurosis or in a form of psychopathic personality, which form predisposes such person to the commission of sexual offenses in a degree constituting him or her a menace to the health or safety of others.

"Sex offense" means one or more of the following: Abduction, incest, rape, assault with intent to commit rape, indecent assault, contributing to the delinquency of a minor involving sexual misconduct, sodomy, indecent exposure, indecent liberties with children, carnal knowledge of children, soliciting or enticing or otherwise communicating with a child for immoral purposes, vagrancy involving immoral or sexual misconduct, or an attempt to commit any of the said offenses.

"Minor" means any person under eighteen years of age.

"Department" means department of social and health services.

"Court" means the superior court of the state of Washington.

"Superintendent" means the superintendent of a state institution designated for the custody, care, and treatment of sexual psychopaths or psychopathic delinquents.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20430[2012 c 117 § 430]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c354.pdf?cite=1985%20c%20354%20§%2032[1985 c 354 § 32]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c80.pdf?cite=1977%20ex.s.%20c%2080%20§%2042[1977 ex.s. c 80 § 42]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c292.pdf?cite=1971%20ex.s.%20c%20292%20§%2065[1971 ex.s. c 292 § 65]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c65.pdf?cite=1961%20c%2065%20§%201[1961 c 65 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c25.pdf?cite=1959%20c%2025%20§%2071.06.010[1959 c 25 § 71.06.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c184.pdf?cite=1957%20c%20184%20§%201[1957 c 184 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c223.pdf?cite=1951%20c%20223%20§%202[1951 c 223 § 2]; 1949 c 198 §§ 25 and 40; Rem. Supp. 1949 §§ 6953-25 and 6953-40; ]

== 71.06.020 - Sexual psychopaths—Petition.
Where any person is charged in the superior court in this state with a sex offense and it appears that such person is a sexual psychopath, the prosecuting attorney may file a petition in the criminal proceeding, alleging that the defendant is a sexual psychopath and stating sufficient facts to support such allegation. Such petition must be filed and served on the defendant or his or her attorney at least ten days prior to hearing on the criminal charge.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20431[2012 c 117 § 431]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c25.pdf?cite=1959%20c%2025%20§%2071.06.020[1959 c 25 § 71.06.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c223.pdf?cite=1951%20c%20223%20§%203[1951 c 223 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c198.pdf?cite=1949%20c%20198%20§%2026[1949 c 198 § 26]; Rem. Supp. 1949 § 6953-26; ]

== 71.06.030 - Procedure on petition—Effect of acquittal on criminal charge.
The court shall proceed to hear the criminal charge. If the defendant is convicted or has previously pleaded guilty to such charge, judgment shall be pronounced, but the execution of the sentence may be deferred or suspended, as in other criminal cases, and the court shall then proceed to hear and determine the allegation of sexual psychopathy. Acquittal on the criminal charge shall not operate to suspend the hearing on the allegation of sexual psychopathy: PROVIDED, That the provisions of RCW 71.06.140 authorizing transfer of a committed sexual psychopath to a correctional institution shall not apply to the committed sexual psychopath who has been acquitted on the criminal charge.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c104.pdf?cite=1967%20c%20104%20§%201[1967 c 104 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c25.pdf?cite=1959%20c%2025%20§%2071.06.030[1959 c 25 § 71.06.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c223.pdf?cite=1951%20c%20223%20§%204[1951 c 223 § 4]; ]

== 71.06.040 - Preliminary hearing—Evidence—Detention in hospital for observation.
At a preliminary hearing upon the charge of sexual psychopathy, the court may require the testimony of two duly licensed physicians, physician assistants, or psychiatric advanced registered nurse practitioners who have examined the defendant. If the court finds that there are reasonable grounds to believe the defendant is a sexual psychopath, the court shall order said defendant confined at the nearest state hospital for observation as to the existence of sexual psychopathy. Such observation shall be for a period of not to exceed ninety days. The defendant shall be detained in the county jail or other county facilities pending execution of such observation order by the department.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6445-S.SL.pdf?cite=2016%20c%20155%20§%2010[2016 c 155 § 10]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1071-S.SL.pdf?cite=2009%20c%20217%20§%2010[2009 c 217 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c25.pdf?cite=1959%20c%2025%20§%2071.06.040[1959 c 25 § 71.06.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c223.pdf?cite=1951%20c%20223%20§%205[1951 c 223 § 5]; ]

== 71.06.050 - Preliminary hearing—Report of findings.
Upon completion of said observation period, the superintendent of the state hospital shall return the defendant to the court, together with a written report of his or her findings as to whether or not the defendant is a sexual psychopath and the facts upon which his or her opinion is based.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20432[2012 c 117 § 432]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c25.pdf?cite=1959%20c%2025%20§%2071.06.050[1959 c 25 § 71.06.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c223.pdf?cite=1951%20c%20223%20§%206[1951 c 223 § 6]; ]

== 71.06.060 - Preliminary hearing—Commitment, or other disposition of charge.
After the superintendent's report has been filed, the court shall determine whether or not the defendant is a sexual psychopath. If said defendant is found to be a sexual psychopath, the court shall commit him or her to the secretary of social and health services for designation of the facility for detention, care, and treatment of the sexual psychopath. If the defendant is found not to be a sexual psychopath, the court shall order the sentence to be executed, or may discharge the defendant as the case may merit.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20433[2012 c 117 § 433]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20129[1979 c 141 § 129]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c104.pdf?cite=1967%20c%20104%20§%202[1967 c 104 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c25.pdf?cite=1959%20c%2025%20§%2071.06.060[1959 c 25 § 71.06.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c223.pdf?cite=1951%20c%20223%20§%207[1951 c 223 § 7]; ]

== 71.06.070 - Preliminary hearing—Jury trial.
A jury may be demanded to determine the question of sexual psychopathy upon hearing after return of the superintendent's report. Such demand must be in writing and filed with the court within ten days after filing of the petition alleging the defendant to be a sexual psychopath.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c25.pdf?cite=1959%20c%2025%20§%2071.06.070[1959 c 25 § 71.06.070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c223.pdf?cite=1951%20c%20223%20§%2014[1951 c 223 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c198.pdf?cite=1949%20c%20198%20§%2038[1949 c 198 § 38]; Rem. Supp. 1949 § 6953-38; ]

== 71.06.080 - Preliminary hearing—Construction of chapter—Trial, evidence, law relating to criminally insane.
Nothing in this chapter shall be construed as to affect the procedure for the ordinary conduct of criminal trials as otherwise set up by law. Nothing in this chapter shall be construed to prevent the defendant, his or her attorney, or the court of its own motion, from producing evidence and witnesses at the hearing on the probable existence of sexual psychopathy or at the hearing after the return of the superintendent's report. Nothing in this chapter shall be construed as affecting the laws relating to the criminally insane or the insane criminal, nor shall this chapter be construed as preventing the defendant from raising the defense of insanity as in other criminal cases.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20434[2012 c 117 § 434]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c25.pdf?cite=1959%20c%2025%20§%2071.06.080[1959 c 25 § 71.06.080]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c223.pdf?cite=1951%20c%20223%20§%2015[1951 c 223 § 15]; ]

== 71.06.091 - Postcommitment proceedings, releases, and further dispositions.
A sexual psychopath committed pursuant to RCW 71.06.060 shall be retained by the superintendent of the institution involved until in the superintendent's opinion he or she is safe to be at large, or until he or she has received the maximum benefit of treatment, or is not amenable to treatment, but the superintendent is unable to render an opinion that he or she is safe to be at large. Thereupon, the superintendent of the institution involved shall so inform whatever court committed the sexual psychopath. The court then may order such further examination and investigation of such person as seems necessary, and may at its discretion, summon such person before it for further hearing, together with any witnesses whose testimony may be pertinent, and together with any relevant documents and other evidence. On the basis of such reports, investigation, and possible hearing, the court shall determine whether the person before it shall be released unconditionally from custody as a sexual psychopath, released conditionally, returned to the custody of the institution as a sexual psychopath, or transferred to the department of corrections to serve the original sentence imposed upon him or her. The power of the court to grant conditional release for any such person before it shall be the same as its power to grant, amend, and revoke probation as provided by chapter 9.95 RCW. When the sexual psychopath has entered upon the conditional release, the indeterminate sentence review board shall supervise such person pursuant to the terms and conditions of the conditional release, as set by the court: PROVIDED, That the superintendent of the institution involved shall never release the sexual psychopath from custody without a court release as herein set forth.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20435[2012 c 117 § 435]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c136.pdf?cite=1981%20c%20136%20§%2064[1981 c 136 § 64]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20130[1979 c 141 § 130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c104.pdf?cite=1967%20c%20104%20§%203[1967 c 104 § 3]; ]

== 71.06.100 - Postcommitment proceedings, releases, and further dispositions—Hospital record to be furnished court, indeterminate sentence review board.
Where under RCW 71.06.091 the superintendent renders his or her opinion to the committing court, he or she shall provide the committing court, and, in the event of conditional release, the indeterminate sentence review board, with a copy of the hospital medical record concerning the sexual psychopath.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20436[2012 c 117 § 436]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c104.pdf?cite=1967%20c%20104%20§%204[1967 c 104 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c25.pdf?cite=1959%20c%2025%20§%2071.06.100[1959 c 25 § 71.06.100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c223.pdf?cite=1951%20c%20223%20§%2010[1951 c 223 § 10]; ]

== 71.06.120 - Credit for time served in hospital.
Time served by a sexual psychopath in a state hospital shall count as part of his or her sentence whether such sentence is pronounced before or after adjudication of his or her sexual psychopathy.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20437[2012 c 117 § 437]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c25.pdf?cite=1959%20c%2025%20§%2071.06.120[1959 c 25 § 71.06.120]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c223.pdf?cite=1951%20c%20223%20§%2013[1951 c 223 § 13]; ]

== 71.06.130 - Discharge pursuant to conditional release.
Where a sexual psychopath has been conditionally released by the committing court, as provided by RCW 71.06.091 for a period of five years, the court shall review his or her record and when the court is satisfied that the sexual psychopath is safe to be at large, said sexual psychopath shall be discharged.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20438[2012 c 117 § 438]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c104.pdf?cite=1967%20c%20104%20§%205[1967 c 104 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c25.pdf?cite=1959%20c%2025%20§%2071.06.130[1959 c 25 § 71.06.130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c223.pdf?cite=1951%20c%20223%20§%2012[1951 c 223 § 12]; 1949 c 198 § 28, part; Rem. Supp. 1949 § 6953-28, part; ]

== 71.06.135 - Sexual psychopaths—Release of information authorized.
In addition to any other information required to be released under this chapter, the department is authorized, pursuant to RCW 4.24.550, to release relevant information that is necessary to protect the public, concerning a specific sexual psychopath committed under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c3.pdf?cite=1990%20c%203%20§%20120[1990 c 3 § 120]; ]

== 71.06.140 - State hospitals for care of sexual psychopaths—Transfers to correctional institutions—Examinations, reports.
The department may designate one or more state hospitals for the care and treatment of sexual psychopaths: PROVIDED, That a committed sexual psychopath who has been determined by the superintendent of such mental hospital to be a custodial risk, or a hazard to other patients may be transferred by the secretary of social and health services, with the consent of the secretary of corrections, to one of the correctional institutions within the department of corrections which has psychiatric care facilities. A committed sexual psychopath who has been transferred to a correctional institution shall be observed and treated at the psychiatric facilities provided by the correctional institution. A complete psychiatric examination shall be given to each sexual psychopath so transferred at least twice annually. The examinations may be conducted at the correctional institution or at one of the mental hospitals. The examiners shall report in writing the results of said examinations, including recommendations as to future treatment and custody, to the superintendent of the mental hospital from which the sexual psychopath was transferred, and to the committing court, with copies of such reports and recommendations to the superintendent of the correctional institution.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c136.pdf?cite=1981%20c%20136%20§%2065[1981 c 136 § 65]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20131[1979 c 141 § 131]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c104.pdf?cite=1967%20c%20104%20§%206[1967 c 104 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c25.pdf?cite=1959%20c%2025%20§%2071.06.140[1959 c 25 § 71.06.140]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c223.pdf?cite=1951%20c%20223%20§%2011[1951 c 223 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c198.pdf?cite=1949%20c%20198%20§%2037[1949 c 198 § 37]; Rem. Supp. 1949 § 6953-37; ]

== 71.06.260 - Hospitalization costs—Sexual psychopaths—Financial responsibility.
At any time any person is committed as a sexual psychopath the court shall, after reasonable notice of the time, place and purpose of the hearing has been given to persons subject to liability under this section, inquire into and determine the financial ability of said person, or his or her parents if he or she is a minor, or other relatives to pay the cost of care, meals and lodging during his or her period of hospitalization. Such cost shall be determined by the department of social and health services. Findings of fact shall be made relative to the ability to pay such cost and a judgment entered against the person or persons found to be financially responsible and directing the payment of said cost or such part thereof as the court may direct. The person committed, or his or her parents or relatives, may apply for modification of said judgment, or the order last entered by the court, if a proper showing of equitable grounds is made therefor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20439[2012 c 117 § 439]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c354.pdf?cite=1985%20c%20354%20§%2033[1985 c 354 § 33]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20132[1979 c 141 § 132]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c25.pdf?cite=1959%20c%2025%20§%2071.06.260[1959 c 25 § 71.06.260]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c26.pdf?cite=1957%20c%2026%20§%201[1957 c 26 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c223.pdf?cite=1951%20c%20223%20§%2027[1951 c 223 § 27]; ]

== 71.06.270 - Availability of records.
The records, files, and other written information prepared by the department of social and health services for individuals committed under this chapter shall be made available upon request to the department of corrections or the *board of prison terms and paroles for persons who are the subject of the records who are committed to the custody of the department of corrections or the board of prison terms and paroles.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c196.pdf?cite=1983%20c%20196%20§%205[1983 c 196 § 5]; ]

