= 71.09 - Sexually violent predators.
:toc:

== 71.09.010 - Findings.
The legislature finds that a small but extremely dangerous group of sexually violent predators exist who do not have a mental disease or defect that renders them appropriate for the existing involuntary treatment act, chapter 71.05 RCW, which is intended to be a short-term civil commitment system that is primarily designed to provide short-term treatment to individuals with serious mental disorders and then return them to the community. In contrast to persons appropriate for civil commitment under chapter 71.05 RCW, sexually violent predators generally have personality disorders and/or mental abnormalities which are unamenable to existing mental illness treatment modalities and those conditions render them likely to engage in sexually violent behavior. The legislature further finds that sex offenders' likelihood of engaging in repeat acts of predatory sexual violence is high. The existing involuntary commitment act, chapter 71.05 RCW, is inadequate to address the risk to reoffend because during confinement these offenders do not have access to potential victims and therefore they will not engage in an overt act during confinement as required by the involuntary treatment act for continued confinement. The legislature further finds that the prognosis for curing sexually violent offenders is poor, the treatment needs of this population are very long term, and the treatment modalities for this population are very different than the traditional treatment modalities for people appropriate for commitment under the involuntary treatment act.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5122-S.SL.pdf?cite=2001%20c%20286%20§%203[2001 c 286 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c3.pdf?cite=1990%20c%203%20§%201001[1990 c 3 § 1001]; ]

== 71.09.015 - Finding—Intent—Clarification.
The legislature finds that presentation of evidence related to conditions of a less restrictive alternative that are beyond the authority of the court to order, and that would not exist in the absence of a court order, reduces the public respect for the rule of law and for the authority of the courts. Consequently, the legislature finds that the decision in In re the Detention of Casper Ross, 102 Wn. App 108 (2000), is contrary to the legislature's intent. The legislature hereby clarifies that it intends, and has always intended, in any proceeding under this chapter that the court and jury be presented only with conditions that would exist or that the court would have the authority to order in the absence of a finding that the person is a sexually violent predator.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5122-S.SL.pdf?cite=2001%20c%20286%20§%201[2001 c 286 § 1]; ]

== 71.09.020 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Department" means the department of social and health services.

. "Health care facility" means any hospital, hospice care center, licensed or certified health care facility, health maintenance organization regulated under chapter 48.46 RCW, federally qualified health maintenance organization, federally approved renal dialysis center or facility, or federally approved blood bank.

. "Health care practitioner" means an individual or firm licensed or certified to engage actively in a regulated health profession.

. "Health care services" means those services provided by health professionals licensed pursuant to RCW 18.120.020(4).

. "Health profession" means those licensed or regulated professions set forth in RCW 18.120.020(4).

. "Less restrictive alternative" means court-ordered treatment in a setting less restrictive than total confinement which satisfies the conditions set forth in RCW 71.09.092. A less restrictive alternative may not include placement in the community protection program as pursuant to RCW 71A.12.230.

. "Likely to engage in predatory acts of sexual violence if not confined in a secure facility" means that the person more probably than not will engage in such acts if released unconditionally from detention on the sexually violent predator petition. Such likelihood must be evidenced by a recent overt act if the person is not totally confined at the time the petition is filed under RCW 71.09.030.

. "Mental abnormality" means a congenital or acquired condition affecting the emotional or volitional capacity which predisposes the person to the commission of criminal sexual acts in a degree constituting such person a menace to the health and safety of others.

. "Personality disorder" means an enduring pattern of inner experience and behavior that deviates markedly from the expectations of the individual's culture, is pervasive and inflexible, has onset in adolescence or early adulthood, is stable over time and leads to distress or impairment. Purported evidence of a personality disorder must be supported by testimony of a licensed forensic psychologist or psychiatrist.

. "Predatory" means acts directed towards: (a) Strangers; (b) individuals with whom a relationship has been established or promoted for the primary purpose of victimization; or (c) persons of casual acquaintance with whom no substantial personal relationship exists.

. "Prosecuting agency" means the prosecuting attorney of the county where the person was convicted or charged or the attorney general if requested by the prosecuting attorney, as provided in RCW 71.09.030.

. "Recent overt act" means any act, threat, or combination thereof that has either caused harm of a sexually violent nature or creates a reasonable apprehension of such harm in the mind of an objective person who knows of the history and mental condition of the person engaging in the act or behaviors.

. "Risk potential activity" or "risk potential facility" means an activity or facility that provides a higher incidence of risk to the public from persons conditionally released from the special commitment center. Risk potential activities and facilities include: Public and private schools, school bus stops, licensed day care and licensed preschool facilities, public parks, publicly dedicated trails, sports fields, playgrounds, recreational and community centers, churches, synagogues, temples, mosques, public libraries, public and private youth camps, and others identified by the department following the hearings on a potential site required in RCW 71.09.315. For purposes of this chapter, "school bus stops" does not include bus stops established primarily for public transit.

. "Secretary" means the secretary of social and health services or the secretary's designee.

. "Secure community transition facility" means a residential facility for persons civilly committed and conditionally released to a less restrictive alternative under this chapter. A secure community transition facility has supervision and security, and either provides or ensures the provision of sex offender treatment services. Secure community transition facilities include but are not limited to the facility established pursuant to RCW 71.09.250(1)(a)(i) and any community-based facilities established under this chapter and operated by the secretary or under contract with the secretary.

. "Secure facility" means a residential facility for persons civilly confined under the provisions of this chapter that includes security measures sufficient to protect the community. Such facilities include total confinement facilities, secure community transition facilities, and any residence used as a court-ordered placement under RCW 71.09.096.

. "Sexually violent offense" means an act committed on, before, or after July 1, 1990, that is: (a) An act defined in Title 9A RCW as rape in the first degree, rape in the second degree by forcible compulsion, rape of a child in the first or second degree, statutory rape in the first or second degree, indecent liberties by forcible compulsion, indecent liberties against a child under age fourteen, incest against a child under age fourteen, or child molestation in the first or second degree; (b) a felony offense in effect at any time prior to July 1, 1990, that is comparable to a sexually violent offense as defined in (a) of this subsection, or any federal or out-of-state conviction for a felony offense that under the laws of this state would be a sexually violent offense as defined in this subsection; (c) an act of murder in the first or second degree, assault in the first or second degree, assault of a child in the first or second degree, kidnapping in the first or second degree, burglary in the first degree, residential burglary, or unlawful imprisonment, which act, either at the time of sentencing for the offense or subsequently during civil commitment proceedings pursuant to this chapter, has been determined beyond a reasonable doubt to have been sexually motivated, as that term is defined in RCW 9.94A.030; or (d) an act as described in chapter 9A.28 RCW, that is an attempt, criminal solicitation, or criminal conspiracy to commit one of the felonies designated in (a), (b), or (c) of this subsection.

. "Sexually violent predator" means any person who has been convicted of or charged with a crime of sexual violence and who suffers from a mental abnormality or personality disorder which makes the person likely to engage in predatory acts of sexual violence if not confined in a secure facility.

. "Total confinement facility" means a secure facility that provides supervision and sex offender treatment services in a total confinement setting. Total confinement facilities include the special commitment center and any similar facility designated as a total confinement facility by the secretary.

. "Treatment" means the sex offender specific treatment program at the special commitment center or a specific course of sex offender treatment pursuant to RCW 71.09.092 (1) and (2).

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1059.SL.pdf?cite=2015%20c%20278%20§%202[2015 c 278 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5718-S.SL.pdf?cite=2009%20c%20409%20§%201[2009 c 409 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6630-S2.SL.pdf?cite=2006%20c%20303%20§%2010[2006 c 303 § 10]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5991.SL.pdf?cite=2003%20c%20216%20§%202[2003 c 216 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5550-S.SL.pdf?cite=2003%20c%2050%20§%201[2003 c 50 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6594-S.SL.pdf?cite=2002%20c%2068%20§%204[2002 c 68 § 4]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6272.SL.pdf?cite=2002%20c%2058%20§%202[2002 c 58 § 2]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6151-S.SL.pdf?cite=2001%202nd%20sp.s.%20c%2012%20§%20102[2001 2nd sp.s. c 12 § 102]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5122-S.SL.pdf?cite=2001%20c%20286%20§%204[2001 c 286 § 4]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5088-S2.SL.pdf?cite=1995%20c%20216%20§%201[1995 c 216 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6104-S.SL.pdf?cite=1992%20c%20145%20§%2017[1992 c 145 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990ex1c12.pdf?cite=1990%201st%20ex.s.%20c%2012%20§%202[1990 1st ex.s. c 12 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c3.pdf?cite=1990%20c%203%20§%201002[1990 c 3 § 1002]; ]

== 71.09.025 - Notice to prosecuting attorney prior to release.
. [Empty]
.. When it appears that a person may meet the criteria of a sexually violent predator as defined in *RCW 71.09.020(16), the agency with jurisdiction shall refer the person in writing to the prosecuting attorney of the county in which an action under this chapter may be filed pursuant to RCW 71.09.030 and the attorney general, three months prior to:

... The anticipated release from total confinement of a person who has been convicted of a sexually violent offense;

... The anticipated release from total confinement of a person found to have committed a sexually violent offense as a juvenile;

... Release of a person who has been charged with a sexually violent offense and who has been determined to be incompetent to stand trial pursuant to RCW 10.77.086(4); or

... Release of a person who has been found not guilty by reason of insanity of a sexually violent offense pursuant to **RCW 10.77.020(3).

.. The agency shall provide the prosecuting agency with all relevant information including but not limited to the following information:

... A complete copy of the institutional records compiled by the department of corrections relating to the person, and any such out-of-state department of corrections' records, if available;

... A complete copy, if applicable, of any file compiled by the indeterminate sentence review board relating to the person;

... All records relating to the psychological or psychiatric evaluation and/or treatment of the person;

... A current record of all prior arrests and convictions, and full police case reports relating to those arrests and convictions; and

.. A current mental health evaluation or mental health records review.

.. The prosecuting agency has the authority, consistent with ***RCW 72.09.345(3), to obtain all records relating to the person if the prosecuting agency deems such records are necessary to fulfill its duties under this chapter. The prosecuting agency may only disclose such records in the course of performing its duties pursuant to this chapter, unless otherwise authorized by law.

.. The prosecuting agency has the authority to utilize the inquiry judge procedures of chapter 10.27 RCW prior to the filing of any action under this chapter to seek the issuance of compulsory process for the production of any records necessary for a determination of whether to seek the civil commitment of a person under this chapter. Any records obtained pursuant to this process may only be disclosed by the prosecuting agency in the course of performing its duties pursuant to this chapter, or unless otherwise authorized by law.

. The agency, its employees, and officials shall be immune from liability for any good-faith conduct under this section.

. As used in this section, "agency with jurisdiction" means that agency with the authority to direct the release of a person serving a sentence or term of confinement and includes the department of corrections, the indeterminate sentence review board, and the department of social and health services.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5718-S.SL.pdf?cite=2009%20c%20409%20§%202[2009 c 409 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6310.SL.pdf?cite=2008%20c%20213%20§%2011[2008 c 213 § 11]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5122-S.SL.pdf?cite=2001%20c%20286%20§%205[2001 c 286 § 5]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5088-S2.SL.pdf?cite=1995%20c%20216%20§%202[1995 c 216 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2262-S.SL.pdf?cite=1992%20c%2045%20§%203[1992 c 45 § 3]; ]

== 71.09.030 - Sexually violent predator petition—Filing.
. A petition may be filed alleging that a person is a sexually violent predator and stating sufficient facts to support such allegation when it appears that: (a) A person who at any time previously has been convicted of a sexually violent offense is about to be released from total confinement; (b) a person found to have committed a sexually violent offense as a juvenile is about to be released from total confinement; (c) a person who has been charged with a sexually violent offense and who has been determined to be incompetent to stand trial is about to be released, or has been released, pursuant to RCW 10.77.086(4); (d) a person who has been found not guilty by reason of insanity of a sexually violent offense is about to be released, or has been released, pursuant to RCW * 10.77.020(3), 10.77.110 (1) or (3), or 10.77.150; or (e) a person who at any time previously has been convicted of a sexually violent offense and has since been released from total confinement and has committed a recent overt act.

. The petition may be filed by:

.. The prosecuting attorney of a county in which:

... The person has been charged or convicted with a sexually violent offense;

... A recent overt act occurred involving a person covered under subsection (1)(e) of this section; or

... The person committed a recent overt act, or was charged or convicted of a criminal offense that would qualify as a recent overt act, if the only sexually violent offense charge or conviction occurred in a jurisdiction other than Washington; or

.. The attorney general, if requested by the county prosecuting attorney identified in (a) of this subsection. If the county prosecuting attorney requests that the attorney general file and prosecute a case under this chapter, then the county shall charge the attorney general only the fees, including filing and jury fees, that would be charged and paid by the county prosecuting attorney, if the county prosecuting attorney retained the case.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5718-S.SL.pdf?cite=2009%20c%20409%20§%203[2009 c 409 § 3]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6310.SL.pdf?cite=2008%20c%20213%20§%2012[2008 c 213 § 12]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5088-S2.SL.pdf?cite=1995%20c%20216%20§%203[1995 c 216 § 3]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2262-S.SL.pdf?cite=1992%20c%2045%20§%204[1992 c 45 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990ex1c12.pdf?cite=1990%201st%20ex.s.%20c%2012%20§%203[1990 1st ex.s. c 12 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c3.pdf?cite=1990%20c%203%20§%201003[1990 c 3 § 1003]; ]

== 71.09.040 - Sexually violent predator petition—Probable cause hearing—Judicial determination—Transfer to total confinement facility upon probable cause determination.
. Upon the filing of a petition under RCW 71.09.030, the judge shall determine whether probable cause exists to believe that the person named in the petition is a sexually violent predator. If such determination is made the judge shall direct that the person be taken into custody and notify the office of public defense of the potential need for representation.

. Within seventy-two hours after a person is taken into custody pursuant to subsection (1) of this section, the court shall provide the person with notice of, and an opportunity to appear in person at, a hearing to contest probable cause as to whether the person is a sexually violent predator. In order to assist the person at the hearing, within twenty-four hours of service of the petition, the prosecuting agency shall provide to the person or his or her counsel a copy of all materials provided to the prosecuting agency by the referring agency pursuant to RCW 71.09.025, or obtained by the prosecuting agency pursuant to RCW 71.09.025(1) (c) and (d). At this hearing, the court shall (a) verify the person's identity, and (b) determine whether probable cause exists to believe that the person is a sexually violent predator. At the probable cause hearing, the state may rely upon the petition and certification for determination of probable cause filed pursuant to RCW 71.09.030. The state may supplement this with additional documentary evidence or live testimony. The person may be held in total confinement at the county jail until the trial court renders a decision after the conclusion of the seventy-two hour probable cause hearing. The county shall be entitled to reimbursement for the cost of housing and transporting the person pursuant to rules adopted by the secretary.

. At the probable cause hearing, the person shall have the following rights in addition to the rights previously specified: (a) To be represented by counsel , and if the person is indigent as defined in RCW 10.101.010, to have office of public defense contracted counsel appointed as provided in RCW 10.101.020; (b) to present evidence on his or her behalf; (c) to cross-examine witnesses who testify against him or her; (d) to view and copy all petitions and reports in the court file. The court must permit a witness called by either party to testify by telephone. Because this is a special proceeding, discovery pursuant to the civil rules shall not occur until after the hearing has been held and the court has issued its decision.

. If the probable cause determination is made, the judge shall direct that the person be transferred to the custody of the department of social and health services for placement in a total confinement facility operated by the department. In no event shall the person be released from confinement prior to trial.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6493-S.SL.pdf?cite=2012%20c%20257%20§%204[2012 c 257 § 4]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5718-S.SL.pdf?cite=2009%20c%20409%20§%204[2009 c 409 § 4]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5122-S.SL.pdf?cite=2001%20c%20286%20§%206[2001 c 286 § 6]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5088-S2.SL.pdf?cite=1995%20c%20216%20§%204[1995 c 216 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c3.pdf?cite=1990%20c%203%20§%201004[1990 c 3 § 1004]; ]

== 71.09.045 - Indigent defense services—Activities beyond the scope of representation by the office of public defense.
The following activities, unless provided as part of investigation and preparation for any hearing or trial under this chapter, are beyond the scope of representation of an attorney under contract with the office of public defense pursuant to chapter 2.70 RCW for the purposes of providing indigent defense services in sexually violent predator civil commitment proceedings:

. Investigation or legal representation challenging the conditions of confinement at the special commitment center or any secure community transition facility;

. Investigation or legal representation for making requests under the public records act, chapter 42.56 RCW;

. Legal representation or advice regarding filing a grievance with the department as part of its grievance policy or procedure;

. Such other activities as may be excluded by policy or contract with the office of public defense.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6493-S.SL.pdf?cite=2012%20c%20257%20§%208[2012 c 257 § 8]; ]

== 71.09.050 - Trial—Rights of parties.
. Within forty-five days after the completion of any hearing held pursuant to RCW 71.09.040, the court shall conduct a trial to determine whether the person is a sexually violent predator. The trial may be continued upon the request of either party and a showing of good cause, or by the court on its own motion in the due administration of justice, and when the respondent will not be substantially prejudiced. The prosecuting agency shall have a right to a current evaluation of the person by experts chosen by the state. The judge may require the person to complete any or all of the following procedures or tests if requested by the evaluator: (a) A clinical interview; (b) psychological testing; (c) plethysmograph testing; and (d) polygraph testing. The judge may order the person to complete any other procedures and tests relevant to the evaluation. The state is responsible for the costs of the evaluation. At all stages of the proceedings under this chapter, any person subject to this chapter shall be entitled to the assistance of counsel, and if the person is indigent as defined in RCW 10.101.010, the court, as provided in RCW 10.101.020, shall appoint office of public defense contracted counsel to assist him or her. The person shall be confined in a secure facility for the duration of the trial.

. Whenever any indigent person is subjected to an evaluation under this chapter, the office of public defense is responsible for the cost of one expert or professional person to conduct an evaluation on the person's behalf. When the person wishes to be evaluated by a qualified expert or professional person of his or her own choice, the expert or professional person must be permitted to have reasonable access to the person for the purpose of such evaluation, as well as to all relevant medical and psychological records and reports. In the case of a person who is indigent, the court shall, upon the person's request, assist the person in obtaining an expert or professional person to perform an evaluation or participate in the trial on the person's behalf. Nothing in this chapter precludes the person from paying for additional expert services at his or her own expense.

. The person, the prosecuting agency, or the judge shall have the right to demand that the trial be before a twelve-person jury. If no demand is made, the trial shall be before the court.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6493-S.SL.pdf?cite=2012%20c%20257%20§%205[2012 c 257 § 5]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6870.SL.pdf?cite=2010%201st%20sp.s.%20c%2028%20§%201[2010 1st sp.s. c 28 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5718-S.SL.pdf?cite=2009%20c%20409%20§%205[2009 c 409 § 5]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5088-S2.SL.pdf?cite=1995%20c%20216%20§%205[1995 c 216 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c3.pdf?cite=1990%20c%203%20§%201005[1990 c 3 § 1005]; ]

== 71.09.055 - Expert evaluations of indigent persons—Costs.
. The office of public defense is responsible for the cost of one expert or professional person conducting an evaluation on an indigent person's behalf as provided in RCW 71.09.050, 71.09.070, or 71.09.090.

. Expert evaluations are capped at ten thousand dollars, to include all professional fees, travel, per diem, and other costs. Partial evaluations are capped at five thousand five hundred dollars and expert services apart from an evaluation, exclusive of testimony at trial or depositions, are capped at six thousand dollars.

. The office of public defense will pay for the costs related to the evaluation of an indigent person by an additional examiner or in excess of the stated fee caps only upon a finding by the superior court that such appointment or extraordinary fees are for good cause.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6493-S.SL.pdf?cite=2012%20c%20257%20§%209[2012 c 257 § 9]; ]

== 71.09.060 - Trial—Determination—Commitment procedures.
. The court or jury shall determine whether, beyond a reasonable doubt, the person is a sexually violent predator. In determining whether or not the person would be likely to engage in predatory acts of sexual violence if not confined in a secure facility, the fact finder may consider only placement conditions and voluntary treatment options that would exist for the person if unconditionally released from detention on the sexually violent predator petition. The community protection program under RCW 71A.12.230 may not be considered as a placement condition or treatment option available to the person if unconditionally released from detention on a sexually violent predator petition. When the determination is made by a jury, the verdict must be unanimous.

If, on the date that the petition is filed, the person was living in the community after release from custody, the state must also prove beyond a reasonable doubt that the person had committed a recent overt act. If the state alleges that the prior sexually violent offense that forms the basis for the petition for commitment was an act that was sexually motivated as provided in *RCW 71.09.020(15)(c), the state must prove beyond a reasonable doubt that the alleged sexually violent act was sexually motivated as defined in RCW 9.94A.030.

If the court or jury determines that the person is a sexually violent predator, the person shall be committed to the custody of the department of social and health services for placement in a secure facility operated by the department of social and health services for control, care, and treatment until such time as: (a) The person's condition has so changed that the person no longer meets the definition of a sexually violent predator; or (b) conditional release to a less restrictive alternative as set forth in RCW 71.09.092 is in the best interest of the person and conditions can be imposed that would adequately protect the community.

If the court or unanimous jury decides that the state has not met its burden of proving that the person is a sexually violent predator, the court shall direct the person's release.

If the jury is unable to reach a unanimous verdict, the court shall declare a mistrial and set a retrial within forty-five days of the date of the mistrial unless the prosecuting agency earlier moves to dismiss the petition. The retrial may be continued upon the request of either party accompanied by a showing of good cause, or by the court on its own motion in the due administration of justice provided that the respondent will not be substantially prejudiced. In no event may the person be released from confinement prior to retrial or dismissal of the case.

. If the person charged with a sexually violent offense has been found incompetent to stand trial, and is about to be or has been released pursuant to RCW 10.77.086(4), and his or her commitment is sought pursuant to subsection (1) of this section, the court shall first hear evidence and determine whether the person did commit the act or acts charged if the court did not enter a finding prior to dismissal under RCW 10.77.086(4) that the person committed the act or acts charged. The hearing on this issue must comply with all the procedures specified in this section. In addition, the rules of evidence applicable in criminal cases shall apply, and all constitutional rights available to defendants at criminal trials, other than the right not to be tried while incompetent, shall apply. After hearing evidence on this issue, the court shall make specific findings on whether the person did commit the act or acts charged, the extent to which the person's incompetence or developmental disability affected the outcome of the hearing, including its effect on the person's ability to consult with and assist counsel and to testify on his or her own behalf, the extent to which the evidence could be reconstructed without the assistance of the person, and the strength of the prosecution's case. If, after the conclusion of the hearing on this issue, the court finds, beyond a reasonable doubt, that the person did commit the act or acts charged, it shall enter a final order, appealable by the person, on that issue, and may proceed to consider whether the person should be committed pursuant to this section.

. Except as otherwise provided in this chapter, the state shall comply with RCW 10.77.220 while confining the person. During all court proceedings where the person is present, the person shall be detained in a secure facility. If the proceedings last more than one day, the person may be held in the county jail for the duration of the proceedings, except the person may be returned to the department's custody on weekends and court holidays if the court deems such a transfer feasible. The county shall be entitled to reimbursement for the cost of housing and transporting the person pursuant to rules adopted by the secretary. The department shall not place the person, even temporarily, in a facility on the grounds of any state mental facility or regional habilitation center because these institutions are insufficiently secure for this population.

. A court has jurisdiction to order a less restrictive alternative placement only after a hearing ordered pursuant to RCW 71.09.090 following initial commitment under this section and in accord with the provisions of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5718-S.SL.pdf?cite=2009%20c%20409%20§%206[2009 c 409 § 6]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6310.SL.pdf?cite=2008%20c%20213%20§%2013[2008 c 213 § 13]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6630-S2.SL.pdf?cite=2006%20c%20303%20§%2011[2006 c 303 § 11]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5122-S.SL.pdf?cite=2001%20c%20286%20§%207[2001 c 286 § 7]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2905.SL.pdf?cite=1998%20c%20146%20§%201[1998 c 146 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5088-S2.SL.pdf?cite=1995%20c%20216%20§%206[1995 c 216 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990ex1c12.pdf?cite=1990%201st%20ex.s.%20c%2012%20§%204[1990 1st ex.s. c 12 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c3.pdf?cite=1990%20c%203%20§%201006[1990 c 3 § 1006]; ]

== 71.09.070 - Annual examinations of persons committed under chapter—Suspension of section.
. Each person committed under this chapter shall have a current examination of his or her mental condition made by the department at least once every year.

. The evaluator must prepare a report that includes consideration of whether:

.. The committed person currently meets the definition of a sexually violent predator;

.. Conditional release to a less restrictive alternative is in the best interest of the person; and

.. Conditions can be imposed that would adequately protect the community.

. The department, on request of the committed person, shall allow a record of the annual review interview to be preserved by audio recording and made available to the committed person.

. The evaluator must indicate in the report whether the committed person participated in the interview and examination.

. The department shall file the report with the court that committed the person under this chapter. The report shall be in the form of a declaration or certification in compliance with the requirements of chapter 5.50 RCW and shall be prepared by a professionally qualified person as defined by rules adopted by the secretary. A copy of the report shall be served on the prosecuting agency involved in the initial commitment and upon the committed person and his or her counsel.

. [Empty]
.. The committed person may retain, or if he or she is indigent and so requests, the court may appoint a qualified expert or a professional person to examine him or her, and such expert or professional person shall have access to all records concerning the person.

.. Any report prepared by the expert or professional person and any expert testimony on the committed person's behalf is not admissible in a proceeding pursuant to RCW 71.09.090, unless the committed person participated in the most recent interview and evaluation completed by the department.

. If an unconditional release trial is ordered pursuant to RCW 71.09.090, this section is suspended until the completion of that trial. If the individual is found either by jury or the court to continue to meet the definition of a sexually violent predator, the department must conduct an examination pursuant to this section no later than one year after the date of the order finding that the individual continues to be a sexually violent predator. The examination must comply with the requirements of this section.

. During any period of confinement pursuant to a criminal conviction, or for any period of detention awaiting trial on criminal charges, this section is suspended. Upon the return of the person committed under this chapter to the custody of the department, the department shall initiate an examination of the person's mental condition. The examination must comply with the requirements of subsection (1) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5017-S.SL.pdf?cite=2019%20c%20232%20§%2025[2019 c 232 § 25]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1059.SL.pdf?cite=2015%20c%20278%20§%201[2015 c 278 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2148-S.SL.pdf?cite=2011%202nd%20sp.s.%20c%207%20§%201[2011 2nd sp.s. c 7 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5122-S.SL.pdf?cite=2001%20c%20286%20§%208[2001 c 286 § 8]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5088-S2.SL.pdf?cite=1995%20c%20216%20§%207[1995 c 216 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c3.pdf?cite=1990%20c%203%20§%201007[1990 c 3 § 1007]; ]

== 71.09.080 - Rights of persons committed under this chapter—Use of personal computers regulated.
. Any person subjected to restricted liberty as a sexually violent predator pursuant to this chapter shall not forfeit any legal right or suffer any legal disability as a consequence of any actions taken or orders made, other than as specifically provided in this chapter, or as otherwise authorized by law.

. [Empty]
.. Any person committed or detained pursuant to this chapter shall be prohibited from possessing or accessing a personal computer if the resident's individualized treatment plan states that access to a computer is harmful to bringing about a positive response to a specific and certain phase or course of treatment.

.. A person who is prohibited from possessing or accessing a personal computer under (a) of this subsection shall be permitted to access a limited functioning personal computer capable of word processing and limited data storage on the computer only that does not have: (i) Internet access capability; (ii) an optical drive, external drive, universal serial bus port, or similar drive capability; or (iii) the capability to display photographs, images, videos, or motion pictures, or similar display capability from any drive or port capability listed under (b)(ii) of this subsection.

. Any person committed pursuant to this chapter has the right to adequate care and individualized treatment. The department of social and health services shall keep records detailing all medical, expert, and professional care and treatment received by a committed person, and shall keep copies of all reports of periodic examinations made pursuant to this chapter. All such records and reports shall be made available upon request only to: The committed person, his or her attorney, the prosecuting agency, the court, the protection and advocacy agency, or another expert or professional person who, upon proper showing, demonstrates a need for access to such records.

. At the time a person is taken into custody or transferred into a facility pursuant to a petition under this chapter, the professional person in charge of such facility or his or her designee shall take reasonable precautions to inventory and safeguard the personal property of the persons detained or transferred. A copy of the inventory, signed by the staff member making it, shall be given to the person detained and shall, in addition, be open to inspection to any responsible relative, subject to limitations, if any, specifically imposed by the detained person. For purposes of this subsection, "responsible relative" includes the guardian, conservator, attorney, spouse, parent, adult child, or adult brother or sister of the person. The facility shall not disclose the contents of the inventory to any other person without consent of the patient or order of the court.

. Nothing in this chapter prohibits a person presently committed from exercising a right presently available to him or her for the purpose of obtaining release from confinement, including the right to petition for a writ of habeas corpus.

. No indigent person may be conditionally released or unconditionally discharged under this chapter without suitable clothing, and the secretary shall furnish the person with such sum of money as is required by RCW 72.02.100 for persons without ample funds who are released from correctional institutions. As funds are available, the secretary may provide payment to the indigent persons conditionally released pursuant to this chapter consistent with the optional provisions of RCW 72.02.100 and 72.02.110, and may adopt rules to do so.

. If a civil commitment petition is dismissed, or a trier of fact determines that a person does not meet civil commitment criteria, the person shall be released within twenty-four hours of service of the release order on the superintendent of the special commitment center, or later by agreement of the person who is the subject of the petition.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6493-S.SL.pdf?cite=2012%20c%20257%20§%206[2012 c 257 § 6]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6308.SL.pdf?cite=2010%20c%20218%20§%202[2010 c 218 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5718-S.SL.pdf?cite=2009%20c%20409%20§%207[2009 c 409 § 7]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5088-S2.SL.pdf?cite=1995%20c%20216%20§%208[1995 c 216 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c3.pdf?cite=1990%20c%203%20§%201008[1990 c 3 § 1008]; ]

== 71.09.085 - Medical care—Contracts for services—Authorization to act on behalf of civilly committed residents.
. Notwithstanding any other provisions of law, the secretary may enter into contracts with health care practitioners, health care facilities, and other entities or agents as may be necessary to provide basic medical care to residents. The contracts shall not cause the termination of classified employees of the department rendering the services at the time the contract is executed.

. In contracting for services, the secretary is authorized to provide for indemnification of health care practitioners who cannot obtain professional liability insurance through reasonable effort, from liability on any action, claim, or proceeding instituted against them arising out of the good faith performance or failure of performance of services on behalf of the department. The contracts may provide that for the purposes of chapter 4.92 RCW only, those health care practitioners with whom the department has contracted shall be considered state employees.

. To the extent that federal law allows and financial participation is available, the secretary or secretary’s designee is authorized to act on behalf of a civilly committed resident for the purposes of applying for medicare and medicaid benefits, veterans health benefits, or other health care benefits or reimbursement available as a result of participation in a health care exchange as defined by the affordable care act.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5693.SL.pdf?cite=2015%20c%20271%20§%201[2015 c 271 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6272.SL.pdf?cite=2002%20c%2058%20§%201[2002 c 58 § 1]; ]

== 71.09.090 - Petition for conditional release to less restrictive alternative or unconditional discharge—Procedures—Suspension of section.
. If the secretary determines that the person's condition has so changed that either: (a) The person no longer meets the definition of a sexually violent predator; or (b) conditional release to a less restrictive alternative is in the best interest of the person and conditions can be imposed that adequately protect the community, the secretary shall authorize the person to petition the court for conditional release to a less restrictive alternative or unconditional discharge. The petition shall be filed with the court and served upon the prosecuting agency responsible for the initial commitment. The court, upon receipt of the petition for conditional release to a less restrictive alternative or unconditional discharge, shall within forty-five days order a hearing.

. [Empty]
.. Nothing contained in this chapter shall prohibit the person from otherwise petitioning the court for conditional release to a less restrictive alternative or unconditional discharge without the secretary's approval. The secretary shall provide the committed person with an annual written notice of the person's right to petition the court for conditional release to a less restrictive alternative or unconditional discharge over the secretary's objection. The notice shall contain a waiver of rights. The secretary shall file the notice and waiver form and the annual report with the court. If the person does not affirmatively waive the right to petition, the court shall set a show cause hearing to determine whether probable cause exists to warrant a hearing on whether the person's condition has so changed that: (i) He or she no longer meets the definition of a sexually violent predator; or (ii) conditional release to a proposed less restrictive alternative would be in the best interest of the person and conditions can be imposed that would adequately protect the community.

.. [Empty]
... The committed person shall have a right to have an attorney represent him or her at the show cause hearing, which may be conducted solely on the basis of affidavits or declarations, but the person is not entitled to be present at the show cause hearing. At the show cause hearing, the prosecuting agency shall present prima facie evidence establishing: (A) That the committed person continues to meet the definition of a sexually violent predator; and (B) that a less restrictive alternative is not in the best interest of the person and conditions cannot be imposed that adequately protect the community.

...(A) If the state produces prima facie evidence that the committed person continues to be a sexually violent predator, then the state's burden under (b)(i)(A) of this subsection is met and an unconditional release trial may not be ordered unless the committed person produces evidence satisfying: Subsection (4)(a) of this section; and subsection (4)(b) (i) or (ii) of this section.

(B) If the state produces prima facie evidence that a less restrictive alternative is not appropriate for the committed person, then the state's burden under (b)(i)(B) of this subsection is met, and a conditional release trial may not be ordered unless the committed person:

(I) Produces evidence satisfying: Subsection (4)(a) of this section; and subsection (4)(b) (i) or (ii) of this section; and

(II) Presents the court with a specific placement satisfying the requirements of RCW 71.09.092.

... In making the showing required under (b)(i) of this subsection, the state may rely exclusively upon the annual report prepared pursuant to RCW 71.09.070. The committed person may present responsive affidavits or declarations to which the state may reply.

.. If the court at the show cause hearing determines that either: (i) The state has failed to present prima facie evidence that the committed person continues to meet the definition of a sexually violent predator and that no proposed less restrictive alternative is in the best interest of the person and conditions cannot be imposed that would adequately protect the community; or (ii) probable cause exists to believe that the person's condition has so changed that: (A) The person no longer meets the definition of a sexually violent predator; or (B) release to a proposed less restrictive alternative would be in the best interest of the person and conditions can be imposed that would adequately protect the community, then the court shall set a hearing on either or both issues.

.. If the court has not previously considered the issue of release to a less restrictive alternative, either through a trial on the merits or through the procedures set forth in RCW 71.09.094(1), the court shall consider whether release to a less restrictive alternative would be in the best interests of the person and conditions can be imposed that would adequately protect the community, without considering whether the person's condition has changed. The court may not find probable cause for a trial addressing less restrictive alternatives unless a proposed less restrictive alternative placement meeting the conditions of RCW 71.09.092 is presented to the court at the show cause hearing.

. [Empty]
.. At the hearing resulting from subsection (1) or (2) of this section, the committed person shall be entitled to be present and to the benefit of all constitutional protections that were afforded to the person at the initial commitment proceeding. The prosecuting agency shall represent the state and shall have a right to a jury trial and to have the committed person evaluated by experts chosen by the state. The prosecuting agency shall have a right to a current evaluation of the person by experts chosen by the state. The judge may require the person to complete any or all of the following procedures or tests if requested by the evaluator: (i) A clinical interview; (ii) psychological testing; (iii) plethysmograph testing; and (iv) polygraph testing. The judge may order the person to complete any other procedures and tests relevant to the evaluation. The state is responsible for the costs of the evaluation. The committed person shall also have the right to a jury trial and the right to have experts evaluate him or her on his or her behalf and the court shall appoint an expert if the person is indigent and requests an appointment.

.. Whenever any indigent person is subjected to an evaluation under (a) of this subsection, the office of public defense is responsible for the cost of one expert or professional person conducting an evaluation on the person's behalf. When the person wishes to be evaluated by a qualified expert or professional person of his or her own choice, such expert or professional person must be permitted to have reasonable access to the person for the purpose of such evaluation, as well as to all relevant medical and psychological records and reports. In the case of a person who is indigent, the court shall, upon the person's request, assist the person in obtaining an expert or professional person to perform an evaluation or participate in the hearing on the person's behalf. Nothing in this chapter precludes the person from paying for additional expert services at his or her own expense.

.. If the issue at the hearing is whether the person should be unconditionally discharged, the burden of proof shall be upon the state to prove beyond a reasonable doubt that the committed person's condition remains such that the person continues to meet the definition of a sexually violent predator. Evidence of the prior commitment trial and disposition is admissible. The recommitment proceeding shall otherwise proceed as set forth in RCW 71.09.050 and 71.09.060.

.. If the issue at the hearing is whether the person should be conditionally released to a less restrictive alternative, the burden of proof at the hearing shall be upon the state to prove beyond a reasonable doubt that conditional release to any proposed less restrictive alternative either: (i) Is not in the best interest of the committed person; or (ii) does not include conditions that would adequately protect the community. Evidence of the prior commitment trial and disposition is admissible.

. [Empty]
.. Probable cause exists to believe that a person's condition has "so changed," under subsection (2) of this section, only when evidence exists, since the person's last commitment trial, or less restrictive alternative revocation proceeding, of a substantial change in the person's physical or mental condition such that the person either no longer meets the definition of a sexually violent predator or that a conditional release to a less restrictive alternative is in the person's best interest and conditions can be imposed to adequately protect the community.

.. A new trial proceeding under subsection (3) of this section may be ordered, or a trial proceeding may be held, only when there is current evidence from a licensed professional of one of the following and the evidence presents a change in condition since the person's last commitment trial proceeding:

... An identified physiological change to the person, such as paralysis, stroke, or dementia, that renders the committed person unable to commit a sexually violent act and this change is permanent; or

... A change in the person's mental condition brought about through positive response to continuing participation in treatment which indicates that the person meets the standard for conditional release to a less restrictive alternative or that the person would be safe to be at large if unconditionally released from commitment.

.. For purposes of this section, a change in a single demographic factor, without more, does not establish probable cause for a new trial proceeding under subsection (3) of this section. As used in this section, a single demographic factor includes, but is not limited to, a change in the chronological age, marital status, or gender of the committed person.

. The jurisdiction of the court over a person civilly committed pursuant to this chapter continues until such time as the person is unconditionally discharged.

. During any period of confinement pursuant to a criminal conviction, or for any period of detention awaiting trial on criminal charges, this section is suspended.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2271.SL.pdf?cite=2018%20c%20131%20§%202[2018 c 131 § 2]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6493-S.SL.pdf?cite=2012%20c%20257%20§%207[2012 c 257 § 7]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2148-S.SL.pdf?cite=2011%202nd%20sp.s.%20c%207%20§%202[2011 2nd sp.s. c 7 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6870.SL.pdf?cite=2010%201st%20sp.s.%20c%2028%20§%202[2010 1st sp.s. c 28 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5718-S.SL.pdf?cite=2009%20c%20409%20§%208[2009 c 409 § 8]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5582.SL.pdf?cite=2005%20c%20344%20§%202[2005 c 344 § 2]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5122-S.SL.pdf?cite=2001%20c%20286%20§%209[2001 c 286 § 9]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5088-S2.SL.pdf?cite=1995%20c%20216%20§%209[1995 c 216 § 9]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2262-S.SL.pdf?cite=1992%20c%2045%20§%207[1992 c 45 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c3.pdf?cite=1990%20c%203%20§%201009[1990 c 3 § 1009]; ]

== 71.09.092 - Conditional release to less restrictive alternative—Findings.
Before the court may enter an order directing conditional release to a less restrictive alternative, it must find the following: (1) The person will be treated by a treatment provider who is qualified to provide such treatment in the state of Washington under chapter 18.155 RCW; (2) the treatment provider has presented a specific course of treatment and has agreed to assume responsibility for such treatment and will report progress to the court on a regular basis, and will report violations immediately to the court, the prosecutor, the supervising community corrections officer, and the superintendent of the special commitment center; (3) housing exists in Washington that is sufficiently secure to protect the community, and the person or agency providing housing to the conditionally released person has agreed in writing to accept the person, to provide the level of security required by the court, and immediately to report to the court, the prosecutor, the supervising community corrections officer, and the superintendent of the special commitment center if the person leaves the housing to which he or she has been assigned without authorization; (4) the person is willing to comply with the treatment provider and all requirements imposed by the treatment provider and by the court; and (5) the person will be under the supervision of the department of corrections and is willing to comply with supervision requirements imposed by the department of corrections.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5718-S.SL.pdf?cite=2009%20c%20409%20§%209[2009 c 409 § 9]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5088-S2.SL.pdf?cite=1995%20c%20216%20§%2010[1995 c 216 § 10]; ]

== 71.09.094 - Conditional release to less restrictive alternative—Verdict.
. Upon the conclusion of the evidence in a hearing held pursuant to RCW 71.09.090 or through summary judgment proceedings prior to such a hearing, if the court finds that there is no legally sufficient evidentiary basis for a reasonable jury to find that the conditions set forth in RCW 71.09.092 have been met, the court shall grant a motion by the state for a judgment as a matter of law on the issue of conditional release to a less restrictive alternative.

. Whenever the issue of conditional release to a less restrictive alternative is submitted to the jury, the court shall instruct the jury to return a verdict in substantially the following form: Has the state proved beyond a reasonable doubt that either: (a) The proposed less restrictive alternative is not in the best interests of respondent; or (b) does not include conditions that would adequately protect the community? Answer: Yes or No.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5122-S.SL.pdf?cite=2001%20c%20286%20§%2011[2001 c 286 § 11]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5088-S2.SL.pdf?cite=1995%20c%20216%20§%2011[1995 c 216 § 11]; ]

== 71.09.096 - Conditional release to less restrictive alternative—Judgment—Conditions—Annual review.
. If the court or jury determines that conditional release to a less restrictive alternative is in the best interest of the person and includes conditions that would adequately protect the community, and the court determines that the minimum conditions set forth in RCW 71.09.092 and in this section are met, the court shall enter judgment and direct a conditional release.

. The court shall impose any additional conditions necessary to ensure compliance with treatment and to protect the community. If the court finds that conditions do not exist that will both ensure the person's compliance with treatment and protect the community, then the person shall be remanded to the custody of the department of social and health services for control, care, and treatment in a secure facility as designated in RCW 71.09.060(1).

. If the service provider designated by the court to provide inpatient or outpatient treatment or to monitor or supervise any other terms and conditions of a person's placement in a less restrictive alternative is other than the department of social and health services or the department of corrections, then the service provider so designated must agree in writing to provide such treatment, monitoring, or supervision in accord with this section. Any person providing or agreeing to provide treatment, monitoring, or supervision services pursuant to this chapter may be compelled to testify and any privilege with regard to such person's testimony is deemed waived.

. Prior to authorizing any release to a less restrictive alternative, the court shall impose such conditions upon the person as are necessary to ensure the safety of the community. The court shall order the department of corrections to investigate the less restrictive alternative and recommend any additional conditions to the court. These conditions shall include, but are not limited to the following: Specification of residence, prohibition of contact with potential or past victims, prohibition of alcohol and other drug use, participation in a specific course of inpatient or outpatient treatment that may include monitoring by the use of polygraph and plethysmograph, monitoring through the use of global positioning satellite [global positioning system] technology, supervision by a department of corrections community corrections officer, a requirement that the person remain within the state unless the person receives prior authorization by the court, and any other conditions that the court determines are in the best interest of the person or others. A copy of the conditions of release shall be given to the person and to any designated service providers.

. [Empty]
.. Prior to authorizing release to a less restrictive alternative, the court shall consider whether it is appropriate to release the person to the person's county of commitment. To ensure equitable distribution of releases, and prevent the disproportionate grouping of persons subject to less restrictive orders in any one county, or in any one jurisdiction or community within a county, the legislature finds it is appropriate for releases to a less restrictive alternative to occur in the person's county of commitment, unless the court determines that the person's return to his or her county of commitment would be inappropriate considering any court-issued protection orders, victim safety concerns, the availability of appropriate treatment or facilities that would adequately protect the community, negative influences on the person, or the location of family or other persons or organizations offering support to the person. When the department or court assists in developing a placement under this section which is outside of the county of commitment, and there are two or more options for placement, it shall endeavor to develop the placement in a manner that does not have a disproportionate effect on a single county.

.. If the committed person is not conditionally released to his or her county of commitment, the department shall provide the law and justice council of the county in which the person is conditionally released with notice and a written explanation.

.. For purposes of this section, the person's county of commitment means the county of the court which ordered the person's commitment.

.. This subsection (5) does not apply to releases to a secure community transition facility under RCW 71.09.250.

. Any service provider designated to provide inpatient or outpatient treatment shall monthly, or as otherwise directed by the court, submit to the court, to the department of social and health services facility from which the person was released, to the prosecuting agency, and to the supervising community corrections officer, a report stating whether the person is complying with the terms and conditions of the conditional release to a less restrictive alternative.

. Each person released to a less restrictive alternative shall have his or her case reviewed by the court that released him or her no later than one year after such release and annually thereafter until the person is unconditionally discharged. Review may occur in a shorter time or more frequently, if the court, in its discretion on its own motion, or on motion of the person, the secretary, or the prosecuting agency so determines. The sole question to be determined by the court is whether the person shall continue to be conditionally released to a less restrictive alternative. The court in making its determination shall be aided by the periodic reports filed pursuant to subsection (6) of this section and the opinions of the secretary and other experts or professional persons.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1059.SL.pdf?cite=2015%20c%20278%20§%203[2015 c 278 § 3]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5718-S.SL.pdf?cite=2009%20c%20409%20§%2010[2009 c 409 § 10]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5122-S.SL.pdf?cite=2001%20c%20286%20§%2012[2001 c 286 § 12]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5088-S2.SL.pdf?cite=1995%20c%20216%20§%2012[1995 c 216 § 12]; ]

== 71.09.098 - Revoking or modifying terms of conditional release to less restrictive alternative—Hearing—Custody pending hearing on revocation or modification.
. Any service provider submitting reports pursuant to *RCW 71.09.096(6), the supervising community corrections officer, the prosecuting agency, or the secretary's designee may petition the court for an immediate hearing for the purpose of revoking or modifying the terms of the person's conditional release to a less restrictive alternative if the petitioner believes the released person: (a) Violated or is in violation of the terms and conditions of the court's conditional release order; or (b) is in need of additional care, monitoring, supervision, or treatment.

. The community corrections officer or the secretary's designee may restrict the person's movement in the community until the petition is determined by the court. The person may be taken into custody if:

.. The supervising community corrections officer, the secretary's designee, or a law enforcement officer reasonably believes the person has violated or is in violation of the court's conditional release order; or

.. The supervising community corrections officer or the secretary's designee reasonably believes that the person is in need of additional care, monitoring, supervision, or treatment because the person presents a danger to himself or herself or others if his or her conditional release under the conditions imposed by the court's release order continues.

. [Empty]
.. Persons taken into custody pursuant to subsection (2) of this section shall:

... Not be released until such time as a hearing is held to determine whether to revoke or modify the person's conditional release order and the court has issued its decision; and

... Be held in the county jail, at a secure community transition facility, or at the total confinement facility, at the discretion of the secretary's designee.

.. The court shall be notified before the close of the next judicial day that the person has been taken into custody and shall promptly schedule a hearing.

. Before any hearing to revoke or modify the person's conditional release order, both the prosecuting agency and the released person shall have the right to request an immediate mental examination of the released person. If the conditionally released person is indigent, the court shall, upon request, assist him or her in obtaining a qualified expert or professional person to conduct the examination.

. At any hearing to revoke or modify the conditional release order:

.. The prosecuting agency shall represent the state, including determining whether to proceed with revocation or modification of the conditional release order;

.. Hearsay evidence is admissible if the court finds that it is otherwise reliable; and

.. The state shall bear the burden of proving by a preponderance of the evidence that the person has violated or is in violation of the court's conditional release order or that the person is in need of additional care, monitoring, supervision, or treatment.

. [Empty]
.. If the court determines that the state has met its burden referenced in subsection (5)(c) of this section, and the issue before the court is revocation of the court's conditional release order, the court shall consider the evidence presented by the parties and the following factors relevant to whether continuing the person's conditional release is in the person's best interests or adequate to protect the community:

... The nature of the condition that was violated by the person or that the person was in violation of in the context of the person's criminal history and underlying mental conditions;

... The degree to which the violation was intentional or grossly negligent;

... The ability and willingness of the released person to strictly comply with the conditional release order;

... The degree of progress made by the person in community-based treatment; and

.. The risk to the public or particular persons if the conditional release continues under the conditional release order that was violated.

.. Any factor alone, or in combination, shall support the court's determination to revoke the conditional release order.

. If the court determines the state has met its burden referenced in subsection (5)(c) of this section, and the issue before the court is modification of the court's conditional release order, the court shall modify the conditional release order by adding conditions if the court determines that the person is in need of additional care, monitoring, supervision, or treatment. The court has authority to modify its conditional release order by substituting a new treatment provider, requiring new housing for the person, or imposing such additional supervision conditions as the court deems appropriate.

. A person whose conditional release has been revoked shall be remanded to the custody of the secretary for control, care, and treatment in a total confinement facility as designated in RCW 71.09.060(1). The person is thereafter eligible for conditional release only in accord with the provisions of RCW 71.09.090 and related statutes.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5718-S.SL.pdf?cite=2009%20c%20409%20§%2011[2009 c 409 § 11]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/3205.SL.pdf?cite=2006%20c%20282%20§%201[2006 c 282 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5122-S.SL.pdf?cite=2001%20c%20286%20§%2013[2001 c 286 § 13]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5088-S2.SL.pdf?cite=1995%20c%20216%20§%2013[1995 c 216 § 13]; ]

== 71.09.110 - Department of social and health services—Duties—Reimbursement.
The department of social and health services shall be responsible for the costs relating to the treatment of persons committed to their custody whether in a secure facility or under a less restrictive alternative as provided in this chapter. Reimbursement may be obtained by the department for the cost of care and treatment of persons committed to its custody whether in a secure facility or under a less restrictive alternative pursuant to RCW 43.20B.330 through 43.20B.370.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6493-S.SL.pdf?cite=2012%20c%20257%20§%2010[2012 c 257 § 10]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6870.SL.pdf?cite=2010%201st%20sp.s.%20c%2028%20§%203[2010 1st sp.s. c 28 § 3]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5088-S2.SL.pdf?cite=1995%20c%20216%20§%2014[1995 c 216 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c3.pdf?cite=1990%20c%203%20§%201011[1990 c 3 § 1011]; ]

== 71.09.111 - Department of social and health services—Disclosures to the prosecuting agency.
The department of social and health services shall provide to the prosecuting agency a copy of all reports made by the department to law enforcement in which a person detained or committed under this chapter is named or listed as a suspect, witness, or victim, as well as a copy of all reports received from law enforcement.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5718-S.SL.pdf?cite=2009%20c%20409%20§%2012[2009 c 409 § 12]; ]

== 71.09.112 - Department of social and health services—Jurisdiction and revocation of conditional release after criminal conviction—Exception.
A person subject to court order under the provisions of this chapter who is thereafter convicted of a criminal offense remains under the jurisdiction of the department and shall be returned to the custody of the department following: (1) Completion of the criminal sentence; or (2) release from confinement in a state, federal, or local correctional facility. Any conditional release order shall be immediately revoked upon conviction for a criminal offense.

This section does not apply to persons subject to a court order under the provisions of this chapter who are thereafter sentenced to life without the possibility of release.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5718-S.SL.pdf?cite=2009%20c%20409%20§%2013[2009 c 409 § 13]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6287.SL.pdf?cite=2002%20c%2019%20§%201[2002 c 19 § 1]; ]

== 71.09.115 - Record check required for employees of secure facility.
. The safety and security needs of the secure facility operated by the department of social and health services pursuant to RCW 71.09.060(1) make it vital that employees working in the facility meet necessary character, suitability, and competency qualifications. The secretary shall require a record check through the Washington state patrol criminal identification system under chapter 10.97 RCW and through the federal bureau of investigation. The record check must include a fingerprint check using a complete Washington state criminal identification fingerprint card. The criminal history record checks shall be at the expense of the department. The secretary shall use the information only in making the initial employment or engagement decision, except as provided in subsection (2) of this section. Further dissemination or use of the record is prohibited.

. This section applies to all current employees hired prior to June 6, 1996, who have not previously submitted to a department of social and health services criminal history records check. The secretary shall use the information only in determining whether the current employee meets the necessary character, suitability, and competency requirements for employment or engagement.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6398-S.SL.pdf?cite=1996%20c%2027%20§%201[1996 c 27 § 1]; ]

== 71.09.120 - Release of information authorized.
. In addition to any other information required to be released under this chapter, the department is authorized, pursuant to RCW 4.24.550, to release relevant information that is necessary to protect the public, concerning a specific sexually violent predator committed under this chapter.

. The department and the courts are authorized to release to the office of public defense records needed to implement the office's administration of public defense in these cases, including research, reports, and other functions as required by RCW 2.70.020 and 2.70.025. The office of public defense shall maintain the confidentiality of all confidential information included in the records.

. The inspection or copying of any nonexempt public record by persons residing in a civil commitment facility for sexually violent predators may be enjoined following procedures identified in RCW 42.56.565. The injunction may be requested by:

.. An agency or its representative;

.. A person named in the record or his or her representative;

.. A person to whom the request specifically pertains or his or her representative.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6493-S.SL.pdf?cite=2012%20c%20257%20§%2011[2012 c 257 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c3.pdf?cite=1990%20c%203%20§%201012[1990 c 3 § 1012]; ]

== 71.09.130 - Notice of escape or disappearance.
In the event of an escape by a person committed under this chapter from a state institution or the disappearance of such a person while on conditional release, the superintendent or community corrections officer shall notify the following as appropriate: Local law enforcement officers, other governmental agencies, the person's relatives, and any other appropriate persons about information necessary for the public safety or to assist in the apprehension of the person.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5088-S2.SL.pdf?cite=1995%20c%20216%20§%2016[1995 c 216 § 16]; ]

== 71.09.135 - McNeil Island—Escape planning, response.
The emergency response team for McNeil Island shall plan, coordinate, and respond in the event of an escape from the special commitment center or the secure community transition facility.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5991.SL.pdf?cite=2003%20c%20216%20§%206[2003 c 216 § 6]; ]

== 71.09.140 - Notice of conditional release or unconditional discharge—Notice of escape and recapture.
. At the earliest possible date, and in no event later than thirty days before conditional release or unconditional discharge, except in the event of escape, the department of social and health services shall send written notice of conditional release, unconditional discharge, or escape, to the following:

.. The chief of police of the city, if any, in which the person will reside or in which placement will be made under a less restrictive alternative;

.. The sheriff of the county in which the person will reside or in which placement will be made under a less restrictive alternative; and

.. The sheriff of the county where the person was last convicted of a sexually violent offense, if the department does not know where the person will reside.

The department shall notify the state patrol of the release of all sexually violent predators and that information shall be placed in the Washington crime information center for dissemination to all law enforcement.

. The same notice as required by subsection (1) of this section shall be sent to the following if such notice has been requested in writing about a specific person found to be a sexually violent predator under this chapter:

.. The victim or victims of any sexually violent offenses for which the person was convicted in the past or the victim's next of kin if the crime was a homicide. "Next of kin" as used in this section means a person's spouse, parents, siblings, and children;

.. Any witnesses who testified against the person in his or her commitment trial under RCW 71.09.060; and

.. Any person specified in writing by the prosecuting agency.

Information regarding victims, next of kin, or witnesses requesting the notice, information regarding any other person specified in writing by the prosecuting agency to receive the notice, and the notice are confidential and shall not be available to the committed person.

. If a person committed as a sexually violent predator under this chapter escapes from a department of social and health services facility, the department shall immediately notify, by the most reasonable and expedient means available, the chief of police of the city and the sheriff of the county in which the committed person resided immediately before his or her commitment as a sexually violent predator, or immediately before his or her incarceration for his or her most recent offense. If previously requested, the department shall also notify the witnesses and the victims of the sexually violent offenses for which the person was convicted in the past or the victim's next of kin if the crime was a homicide. If the person is recaptured, the department shall send notice to the persons designated in this subsection as soon as possible but in no event later than two working days after the department learns of such recapture.

. If the victim or victims of any sexually violent offenses for which the person was convicted in the past or the victim's next of kin, or any witness is under the age of sixteen, the notice required by this section shall be sent to the parents or legal guardian of the child.

. The department of social and health services shall send the notices required by this chapter to the last address provided to the department by the requesting party. The requesting party shall furnish the department with a current address.

. Nothing in this section shall impose any liability upon a chief of police of a city or sheriff of a county for failing to request in writing a notice as provided in subsection (1) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6493-S.SL.pdf?cite=2012%20c%20257%20§%2012[2012 c 257 § 12]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5088-S2.SL.pdf?cite=1995%20c%20216%20§%2017[1995 c 216 § 17]; ]

== 71.09.200 - Escorted leave—Definitions.
For purposes of RCW 71.09.210 through 71.09.230:

. "Escorted leave" means a leave of absence from a facility housing persons detained or committed pursuant to this chapter under the continuous supervision of an escort.

. "Escort" means a correctional officer or other person approved by the superintendent or the superintendent's designee to accompany a resident on a leave of absence and be in visual or auditory contact with the resident at all times.

. "Resident" means a person detained or committed pursuant to this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5088-S2.SL.pdf?cite=1995%20c%20216%20§%2018[1995 c 216 § 18]; ]

== 71.09.210 - Escorted leave—Conditions.
The superintendent of any facility housing persons detained or committed pursuant to this chapter may, subject to the approval of the secretary, grant escorted leaves of absence to residents confined in such institutions to:

. Go to the bedside of the resident's wife, husband, child, mother or father, or other member of the resident's immediate family who is seriously ill;

. Attend the funeral of a member of the resident's immediate family listed in subsection (1) of this section; and

. Receive necessary medical or dental care which is not available in the institution.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5088-S2.SL.pdf?cite=1995%20c%20216%20§%2019[1995 c 216 § 19]; ]

== 71.09.220 - Escorted leave—Notice.
A resident shall not be allowed to start a leave of absence under RCW 71.09.210 until the secretary, or the secretary's designee, has notified any county and city law enforcement agency having jurisdiction in the area of the resident's destination.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5088-S2.SL.pdf?cite=1995%20c%20216%20§%2020[1995 c 216 § 20]; ]

== 71.09.230 - Escorted leave—Rules.
. The secretary is authorized to adopt rules providing for the conditions under which residents will be granted leaves of absence and providing for safeguards to prevent escapes while on leaves of absence. Leaves of absence granted to residents under RCW 71.09.210, however, shall not allow or permit any resident to go beyond the boundaries of this state.

. The secretary shall adopt rules requiring reimbursement of the state from the resident granted leave of absence, or the resident's family, for the actual costs incurred arising from any leave of absence granted under the authority of RCW 71.09.210 (1) and (2). No state funds shall be expended in connection with leaves of absence granted under RCW 71.09.210 (1) and (2) unless the resident and the resident's immediate family are indigent and without resources sufficient to reimburse the state for the expenses of such leaves of absence.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5088-S2.SL.pdf?cite=1995%20c%20216%20§%2021[1995 c 216 § 21]; ]

== 71.09.250 - Transition facility—Siting.
. [Empty]
.. The secretary is authorized to site, construct, occupy, and operate (i) a secure community transition facility on McNeil Island for persons authorized to petition for a less restrictive alternative under RCW 71.09.090(1) and who are conditionally released; and (ii) a special commitment center on McNeil Island with up to four hundred four beds as a total confinement facility under this chapter, subject to appropriated funding for those purposes. The secure community transition facility shall be authorized for the number of beds needed to ensure compliance with the orders of the superior courts under this chapter and the federal district court for the western district of Washington. The total number of beds in the secure community transition facility shall be limited to twenty-four, consisting of up to fifteen transitional beds and up to nine pretransitional beds. The residents occupying the transitional beds shall be the only residents eligible for transitional services occurring in Pierce county. In no event shall more than fifteen residents of the secure community transition facility be participating in off-island transitional, educational, or employment activity at the same time in Pierce county. The department shall provide the Pierce county sheriff, or his or her designee, with a list of the fifteen residents so designated, along with their photographs and physical descriptions, and the list shall be immediately updated whenever a residential change occurs. The Pierce county sheriff, or his or her designee, shall be provided an opportunity to confirm the residential status of each resident leaving McNeil Island.

.. For purposes of this subsection, "transitional beds" means beds only for residents who are judged by a qualified expert to be suitable to leave the island for treatment, education, and employment.

. [Empty]
.. The secretary is authorized to site, either within the secure community transition facility established pursuant to subsection (1)(a)(i) of this section, or within the special commitment center, up to nine pretransitional beds.

.. Residents assigned to pretransitional beds shall not be permitted to leave McNeil Island for education, employment, treatment, or community activities in Pierce county.

.. For purposes of this subsection, "pretransitional beds" means beds for residents whose progress toward a less secure residential environment and transition into more complete community involvement is projected to take substantially longer than a typical resident of the special commitment center.

. Notwithstanding RCW 36.70A.103 or any other law, this statute preempts and supersedes local plans, development regulations, permitting requirements, inspection requirements, and all other laws as necessary to enable the secretary to site, construct, occupy, and operate a secure community transition facility on McNeil Island and a total confinement facility on McNeil Island.

. To the greatest extent possible, until June 30, 2003, persons who were not civilly committed from the county in which the secure community transition facility established pursuant to subsection (1) of this section is located may not be conditionally released to a setting in that same county less restrictive than that facility.

. As of June 26, 2001, the state shall immediately cease any efforts in effect on such date to site secure community transition facilities, other than the facility authorized by subsection (1) of this section, and shall instead site such facilities in accordance with the provisions of this section.

. The department must:

.. Identify the minimum and maximum number of secure community transition facility beds in addition to the facility established under subsection (1) of this section that may be necessary for the period of May 2004 through May 2007 and provide notice of these numbers to all counties by August 31, 2001; and

.. Develop and publish policy guidelines for the siting and operation of secure community transition facilities.

. [Empty]
.. The total number of secure community transition facility beds that may be required to be sited in a county between June 26, 2001, and June 30, 2008, may be no greater than the total number of persons civilly committed from that county, or detained at the special commitment center under a pending civil commitment petition from that county where a finding of probable cause had been made on April 1, 2001. The total number of secure community transition facility beds required to be sited in each county between July 1, 2008, and June 30, 2015, may be no greater than the total number of persons civilly committed from that county or detained at the special commitment center under a pending civil commitment petition from that county where a finding of probable cause had been made as of July 1, 2008.

.. Counties and cities that provide secure community transition facility beds above the maximum number that they could be required to site under this subsection are eligible for a bonus grant under the incentive provisions in RCW 71.09.255. The county where the special commitment center is located shall receive this bonus grant for the number of beds in the facility established in subsection (1) of this section in excess of the maximum number established by this subsection.

.. No secure community transition facilities in addition to the one established in subsection (1) of this section may be required to be sited in the county where the special commitment center is located until after June 30, 2008, provided however, that the county and its cities may elect to site additional secure community transition facilities and shall be eligible under the incentive provisions of RCW 71.09.255 for any additional facilities meeting the requirements of that section.

. In identifying potential sites within a county for the location of a secure community transition facility, the department shall work with and assist local governments to provide for the equitable distribution of such facilities. In coordinating and deciding upon the siting of secure community transition facilities, great weight shall be given by the county and cities within the county to:

.. The number and location of existing residential facility beds operated by the department of corrections or the mental health division of the department of social and health services in each jurisdiction in the county; and

.. The number of registered sex offenders classified as level II or level III and the number of sex offenders registered as homeless residing in each jurisdiction in the county.

. [Empty]
.. "Equitable distribution" means siting or locating secure community transition facilities in a manner that will not cause a disproportionate grouping of similar facilities either in any one county, or in any one jurisdiction or community within a county, as relevant; and

.. "Jurisdiction" means a city, town, or geographic area of a county in which distinct political or judicial authority may be exercised.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5991.SL.pdf?cite=2003%20c%20216%20§%203[2003 c 216 § 3]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6151-S.SL.pdf?cite=2001%202nd%20sp.s.%20c%2012%20§%20201[2001 2nd sp.s. c 12 § 201]; ]

== 71.09.252 - Transition facilities—Agreements for regional facilities.
. To encourage economies of scale in the siting and operation of secure community transition facilities, the department may enter into an agreement with two or more counties to create a regional secure community transition facility. The agreement must clearly identify the number of beds from each county that will be contained in the regional secure community transition facility. The agreement must specify which county must contain the regional secure community transition facility and the facility must be sited accordingly. No county may withdraw from an agreement under this section unless it has provided an alternative acceptable secure community transition facility to house any displaced residents that meets the criteria established for such facilities in this chapter and the guidelines established by the department.

. A regional secure community transition facility must meet the criteria established for secure community transition facilities in this chapter and the guidelines established by the department.

. The department shall count the beds identified for each participating county in a regional secure community transition facility against the maximum number of beds that could be required for each county under RCW 71.09.250(7)(a).

. An agreement for a regional secure community transition facility does not alter the maximum number of beds for purposes of the incentive grants under RCW 71.09.255 for the county containing the regional facility.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6594-S.SL.pdf?cite=2002%20c%2068%20§%2018[2002 c 68 § 18]; ]

== 71.09.255 - Transition facilities—Incentive grants and payments.
. Upon receiving the notification required by RCW 71.09.250, counties must promptly notify the cities within the county of the maximum number of secure community transition facility beds that may be required and the projected number of beds to be needed in that county.

. The incentive grants and payments provided under this section are subject to the following provisions:

.. Counties and the cities within the county must notify each other of siting plans to promote the establishment and equitable distribution of secure community transition facilities;

.. Development regulations, ordinances, plans, laws, and criteria established for siting must be consistent with statutory requirements and rules applicable to siting and operating secure community transition facilities;

.. The minimum size for any facility is three beds; and

.. The department must approve any sites selected.

. Any county or city that makes a commitment to initiate the process to site one or more secure community transition facilities by one hundred twenty days after March 21, 2002, shall receive a planning grant as proposed and approved by the *department of community, trade, and economic development.

. Any county or city that has issued all necessary permits by May 1, 2003, for one or more secure community transition facilities that comply with the requirements of this section shall receive an incentive grant in the amount of fifty thousand dollars for each bed sited.

. To encourage the rapid permitting of sites, any county or city that has issued all necessary permits by January 1, 2003, for one or more secure community transition facilities that comply with the requirements of this section shall receive a bonus in the amount of twenty percent of the amount provided under subsection (4) of this section.

. Any county or city that establishes secure community transition facility beds in excess of the maximum number that could be required to be sited in that county shall receive a bonus payment of one hundred thousand dollars for each bed established in excess of the maximum requirement.

. No payment shall be made under subsection (4), (5), or (6) of this section until all necessary permits have been issued.

. The funds available to counties and cities under this section are contingent upon funds being appropriated by the legislature.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6594-S.SL.pdf?cite=2002%20c%2068%20§%208[2002 c 68 § 8]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6151-S.SL.pdf?cite=2001%202nd%20sp.s.%20c%2012%20§%20204[2001 2nd sp.s. c 12 § 204]; ]

== 71.09.260 - Transition facilities not limited to residential neighborhoods.
The provisions of chapter 12, Laws of 2001 2nd sp. sess. shall not be construed to limit siting of secure community transition facilities to residential neighborhoods.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6151-S.SL.pdf?cite=2001%202nd%20sp.s.%20c%2012%20§%20206[2001 2nd sp.s. c 12 § 206]; ]

== 71.09.265 - Transition facilities—Distribution of impact.
. The department shall make reasonable efforts to distribute the impact of the employment, education, and social services needs of the residents of the secure community transition facility established pursuant to RCW 71.09.250(1) among the adjoining counties and not to concentrate the residents' use of resources in any one community.

. The department shall develop policies to ensure that, to the extent possible, placement of persons eligible in the future for conditional release to a setting less restrictive than the facility established pursuant to RCW 71.09.250(1) will be equitably distributed among the counties and within jurisdictions in the county.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6151-S.SL.pdf?cite=2001%202nd%20sp.s.%20c%2012%20§%20208[2001 2nd sp.s. c 12 § 208]; ]

== 71.09.275 - Transition facility—Transportation of residents.
. If the department does not provide a separate vessel for transporting residents of the secure community transition facility established in RCW 71.09.250(1) between McNeil Island and the mainland, the department shall:

.. Separate residents from minors and vulnerable adults, except vulnerable adults who have been found to be sexually violent predators.

.. Not transport residents during times when children are normally coming to and from the mainland for school.

. The department shall designate a separate waiting area at the points of debarkation, and residents shall be required to remain in this area while awaiting transportation.

. The department shall provide law enforcement agencies in the counties and cities in which residents of the secure community transition facility established pursuant to RCW 71.09.250(1)(a)(i) regularly participate in employment, education, or social services, or through which these persons are regularly transported, with a copy of the court's order of conditional release with respect to these persons.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5991.SL.pdf?cite=2003%20c%20216%20§%204[2003 c 216 § 4]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6151-S.SL.pdf?cite=2001%202nd%20sp.s.%20c%2012%20§%20211[2001 2nd sp.s. c 12 § 211]; ]

== 71.09.280 - Transition facility—Release to less restrictive placement.
When considering whether a person civilly committed under this chapter and conditionally released to a secure community transition facility is appropriate for release to a placement that is less restrictive than that facility, the court shall comply with the procedures set forth in RCW 71.09.090 through 71.09.096. In addition, the court shall consider whether the person has progressed in treatment to the point that a significant change in the person's routine, including but not limited to a change of employment, education, residence, or sex offender treatment provider will not cause the person to regress to the point that the person presents a greater risk to the community than can reasonably be addressed in the proposed placement.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6151-S.SL.pdf?cite=2001%202nd%20sp.s.%20c%2012%20§%20212[2001 2nd sp.s. c 12 § 212]; ]

== 71.09.285 - Transition facility—Siting policy guidelines.
. Except with respect to the secure community transition facility established pursuant to RCW 71.09.250, the secretary shall develop policy guidelines that balance the average response time of emergency services to the general area of a proposed secure community transition facility against the proximity of the proposed site to risk potential activities and facilities in existence at the time the site is listed for consideration.

. In no case shall the policy guidelines permit location of a facility adjacent to, immediately across a street or parking lot from, or within the line of sight of a risk potential activity or facility in existence at the time a site is listed for consideration. "Within the line of sight" means that it is possible to reasonably visually distinguish and recognize individuals.

. The policy guidelines shall require that great weight be given to sites that are the farthest removed from any risk potential activity.

. The policy guidelines shall specify how distance from the location is measured and any variations in the measurement based on the size of the property within which a proposed facility is to be located.

. The policy guidelines shall establish a method to analyze and compare the criteria for each site in terms of public safety and security, site characteristics, and program components. In making a decision regarding a site following the analysis and comparison, the secretary shall give priority to public safety and security considerations. The analysis and comparison of the criteria are to be documented and made available at the public hearings prescribed in RCW 71.09.315.

. Policy guidelines adopted by the secretary under this section shall be considered by counties and cities when providing for the siting of secure community transition facilities as required under RCW 36.70A.200.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6594-S.SL.pdf?cite=2002%20c%2068%20§%205[2002 c 68 § 5]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6151-S.SL.pdf?cite=2001%202nd%20sp.s.%20c%2012%20§%20213[2001 2nd sp.s. c 12 § 213]; ]

== 71.09.290 - Other transition facilities—Siting policy guidelines.
The secretary shall establish policy guidelines for the siting of secure community transition facilities, other than the secure community transition facility established pursuant to RCW 71.09.250(1)(a)(i), which shall include at least the following minimum requirements:

. The following criteria must be considered prior to any real property being listed for consideration for the location of or use as a secure community transition facility:

.. The proximity and response time criteria established under RCW 71.09.285;

.. The site or building is available for lease for the anticipated use period or for purchase;

.. Security monitoring services and appropriate backup systems are available and reliable;

.. Appropriate mental health and sex offender treatment providers must be available within a reasonable commute; and

.. Appropriate permitting for a secure community transition facility must be possible under the zoning code of the local jurisdiction.

. For sites which meet the criteria of subsection (1) of this section, the department shall analyze and compare the criteria in subsections (3) through (5) of this section using the method established in RCW 71.09.285.

. Public safety and security criteria shall include at least the following:

.. Whether limited visibility between the facility and adjacent properties can be achieved prior to placement of any person;

.. The distance from, and number of, risk potential activities and facilities, as measured using the policies adopted under RCW 71.09.285;

.. The existence of or ability to establish barriers between the site and the risk potential facilities and activities;

.. Suitability of the buildings to be used for the secure community transition facility with regard to existing or feasibly modified features; and

.. The availability of electronic monitoring that allows a resident's location to be determined with specificity.

. Site characteristics criteria shall include at least the following:

.. Reasonableness of rental, lease, or sale terms including length and renewability of a lease or rental agreement;

.. Traffic and access patterns associated with the real property;

.. Feasibility of complying with zoning requirements within the necessary time frame; and

.. A contractor or contractors are available to install, monitor, and repair the necessary security and alarm systems.

. Program characteristics criteria shall include at least the following:

.. Reasonable proximity to available medical, mental health, sex offender, and chemical dependency treatment providers and facilities;

.. Suitability of the location for programming, staffing, and support considerations;

.. Proximity to employment, educational, vocational, and other treatment plan components.

. For purposes of this section "available" or "availability" of qualified treatment providers includes provider qualifications and willingness to provide services, average commute time, and cost of services.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5991.SL.pdf?cite=2003%20c%20216%20§%205[2003 c 216 § 5]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6151-S.SL.pdf?cite=2001%202nd%20sp.s.%20c%2012%20§%20214[2001 2nd sp.s. c 12 § 214]; ]

== 71.09.295 - Transition facilities—Security systems.
. Security systems for all secure community transition facilities shall meet the following minimum qualifications:

.. The security panel must be a commercial grade panel with tamper-proof switches and a key-lock to prevent unauthorized access.

.. There must be an emergency electrical supply system which shall include a battery backup system and a generator.

.. The system must include personal panic devices for all staff.

.. The security system must be capable of being monitored and signaled either by telephone through either a land or cellular telephone system or by private radio network in the event of a total dial-tone failure or through equivalent technologies.

.. The department shall issue photo-identification badges to all staff which must be worn at all times.

. Security systems for the secure community transition facility established pursuant to RCW 71.09.250(1) shall also include a fence and provide the maximum protection appropriate in a civil facility for persons in less than total confinement.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6151-S.SL.pdf?cite=2001%202nd%20sp.s.%20c%2012%20§%20215[2001 2nd sp.s. c 12 § 215]; ]

== 71.09.300 - Transition facilities—Staffing.
Secure community transition facilities shall meet the following minimum staffing requirements:

. At any time the census of a facility is six or fewer residents, all staff shall be classified as residential rehabilitation counselor II or have a classification that indicates an equivalent or higher level of skill, experience, and training.

. [Empty]
.. For the secure transition facility located on McNeil Island, the direct care staffing level shall be at least three qualified, trained staff as described in subsection (3) of this section, unless there are no residents housed at the facility, in which case the facility need not staff to this ratio.

.. For the secure community transition facility located in Seattle, the direct care staffing level shall be at least two qualified, trained staff as described in subsection (3) of this section, unless there are no residents housed at the facility, in which case the facility need not staff to this ratio.

. Before being assigned to a facility, all staff must have received training in sex offender issues, self-defense, and crisis de-escalation skills in addition to departmental orientation and, as appropriate, management training. All staff with resident treatment or care duties must participate in ongoing in-service training.

. All staff must pass a departmental background check and the check is not subject to the limitations in chapter 9.96A RCW. A person who has been convicted of a felony, or any sex offense, may not be employed at the secure community transition facility or be approved as an escort for a resident of the facility.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1247-S.SL.pdf?cite=2011%20c%2019%20§%201[2011 c 19 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5991.SL.pdf?cite=2003%20c%20216%20§%201[2003 c 216 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6151-S.SL.pdf?cite=2001%202nd%20sp.s.%20c%2012%20§%20216[2001 2nd sp.s. c 12 § 216]; ]

== 71.09.305 - Transition facility residents—Monitoring, escorting.
. Unless otherwise ordered by the court:

.. Residents of a secure community transition facility shall wear electronic monitoring devices at all times. To the extent that electronic monitoring devices that employ global positioning system technology are available and funds for this purpose are appropriated by the legislature, the department shall use these devices.

.. At least one staff member, or other court-authorized and department-approved person must escort each resident when the resident leaves the secure community transition facility for appointments, employment, or other approved activities. Escorting persons must supervise the resident closely and maintain close proximity to the resident. The escort must immediately notify the department of any serious violation, as defined in RCW 71.09.325, by the resident and must immediately notify law enforcement of any violation of law by the resident. The escort may not be a relative of the resident or a person with whom the resident has, or has had, a dating relationship as defined in RCW 26.50.010.

. Staff members of the special commitment center and any other total confinement facility and any secure community transition facility must be trained in self-defense and appropriate crisis responses including incident de-escalation. Prior to escorting a person outside of a facility, staff members must also have training in the offense pattern of the offender they are escorting.

. Any escort must carry a cellular telephone or a similar device at all times when escorting a resident of a secure community transition facility.

. The department shall require training in offender pattern, self-defense, and incident response for all court-authorized escorts who are not employed by the department or the department of corrections.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6594-S.SL.pdf?cite=2002%20c%2068%20§%206[2002 c 68 § 6]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6151-S.SL.pdf?cite=2001%202nd%20sp.s.%20c%2012%20§%20217[2001 2nd sp.s. c 12 § 217]; ]

== 71.09.310 - Transition facility residents—Mandatory escorts.
Notwithstanding the provisions of RCW 71.09.305, residents of the secure community transition facility established pursuant to RCW 71.09.250(1) must be escorted at any time the resident leaves the facility.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6151-S.SL.pdf?cite=2001%202nd%20sp.s.%20c%2012%20§%20218[2001 2nd sp.s. c 12 § 218]; ]

== 71.09.315 - Transition facilities—Public notice, review, and comment.
. Whenever the department operates, or the secretary enters into a contract to operate, a secure community transition facility except the secure community transition facility established pursuant to RCW 71.09.250(1), the secure community transition facility may be operated only after the public notification and opportunities for review and comment as required by this section.

. The secretary shall establish a process for early and continuous public participation in establishing or relocating secure community transition facilities. The process shall include, at a minimum, public meetings in the local communities affected, as well as opportunities for written and oral comments, in the following manner:

.. If there are more than three sites initially selected as potential locations and the selection process by the secretary or a service provider reduces the number of possible sites for a secure community transition facility to no fewer than three, the secretary or the chief operating officer of the service provider shall notify the public of the possible siting and hold at least two public hearings in each community where a secure community transition facility may be sited.

.. When the secretary or service provider has determined the secure community transition facility's location, the secretary or the chief operating officer of the service provider shall hold at least one additional public hearing in the community where the secure community transition facility will be sited.

.. When the secretary has entered negotiations with a service provider and only one site is under consideration, then at least two public hearings shall be held.

.. To provide adequate notice of, and opportunity for interested persons to comment on, a proposed location, the secretary or the chief operating officer of the service provider shall provide at least fourteen days' advance notice of the meeting to all newspapers of general circulation in the community, all radio and television stations generally available to persons in the community, any school district in which the secure community transition facility would be sited or whose boundary is within two miles of a proposed secure community transition facility, any library district in which the secure community transition facility would be sited, local business or fraternal organizations that request notification from the secretary or agency, and any person or property owner within a one-half mile radius of the proposed secure community transition facility. Before initiating this process, the department of social and health services shall contact local government planning agencies in the communities containing the proposed secure community transition facility. The department of social and health services shall coordinate with local government agencies to ensure that opportunities are provided for effective citizen input and to reduce the duplication of notice and meetings.

. If local government land use regulations require that a special use or conditional use permit be submitted and approved before a secure community transition facility can be sited, and the process for obtaining such a permit includes public notice and hearing requirements similar to those required under this section, the requirements of this section shall not apply to the extent they would duplicate requirements under the local land use regulations.

. This section applies only to secure community transition facilities sited after June 26, 2001.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6151-S.SL.pdf?cite=2001%202nd%20sp.s.%20c%2012%20§%20219[2001 2nd sp.s. c 12 § 219]; ]

== 71.09.320 - Transition facilities—Operational advisory boards.
. The secretary shall develop a process with local governments that allows each community in which a secure community transition facility is located to establish operational advisory boards of at least seven persons for the secure community transition facilities. The department may conduct community awareness activities to publicize this opportunity. The operational advisory boards developed under this section shall be implemented following the decision to locate a secure community transition facility in a particular community.

. The operational advisory boards may review and make recommendations regarding the security and operations of the secure community transition facility and conditions or modifications necessary with relation to any person who the secretary proposes to place in the secure community transition facility.

. The facility management must consider the recommendations of the community advisory boards. Where the facility management does not implement an operational advisory board recommendation, the management must provide a written response to the operational advisory board stating its reasons for its decision not to implement the recommendation.

. The operational advisory boards, their members, and any agency represented by a member shall not be liable in any cause of action as a result of its recommendations unless the advisory board acts with gross negligence or bad faith in making a recommendation.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6151-S.SL.pdf?cite=2001%202nd%20sp.s.%20c%2012%20§%20220[2001 2nd sp.s. c 12 § 220]; ]

== 71.09.325 - Transition facilities—Conditional release—Reports—Violations.
. The secretary shall adopt a violation reporting policy for persons conditionally released to less restrictive alternative placements. The policy shall require written documentation by the department and service providers of all violations of conditions set by the department, the department of corrections, or the court and establish criteria for returning a violator to the special commitment center or a secure community transition facility with a higher degree of security. Any conditionally released person who commits a serious violation of conditions shall be returned to the special commitment center, unless arrested by a law enforcement officer, and the court shall be notified immediately and shall initiate proceedings under RCW 71.09.098 to revoke or modify the less restrictive alternative placement. Nothing in this section limits the authority of the department to return a person to the special commitment center based on a violation that is not a serious violation as defined in this section. For the purposes of this section, "serious violation" includes but is not limited to:

.. The commission of any criminal offense;

.. Any unlawful use or possession of a controlled substance; and

.. Any violation of conditions targeted to address the person's documented pattern of offense that increases the risk to public safety.

. When a person is conditionally released to a less restrictive alternative under this chapter and is under the supervision of the department of corrections, notice of any violation of the person's conditions of release must also be made to the department of corrections.

. Whenever the secretary contracts with a service provider to operate a secure community transition facility, the contract shall include a requirement that the service provider must report to the department of social and health services any known violation of conditions committed by any resident of the secure community transition facility.

. The secretary shall document in writing all violations, penalties, actions by the department of social and health services to remove persons from a secure community transition facility, and contract terminations. The secretary shall compile this information and submit it to the appropriate committees of the legislature on an annual basis. The secretary shall give great weight to a service provider's record of violations, penalties, actions by the department of social and health services or the department of corrections to remove persons from a secure community transition facility, and contract terminations in determining whether to execute, renew, or renegotiate a contract with a service provider.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6151-S.SL.pdf?cite=2001%202nd%20sp.s.%20c%2012%20§%20221[2001 2nd sp.s. c 12 § 221]; ]

== 71.09.330 - Transition facilities—Contracted operation—Enforcement remedies.
Whenever the secretary contracts with a provider to operate a secure community transition facility, the secretary shall include in the contract provisions establishing intermediate contract enforcement remedies.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6151-S.SL.pdf?cite=2001%202nd%20sp.s.%20c%2012%20§%20222[2001 2nd sp.s. c 12 § 222]; ]

== 71.09.335 - Conditional release from total confinement—Community notification.
A conditional release from a total confinement facility to a less restrictive alternative is a release that subjects the conditionally released person to the registration requirements specified in RCW 9A.44.130 and to community notification under RCW 4.24.550.

When a person is conditionally released to the secure community transition facility established pursuant to RCW 71.09.250(1), the sheriff must provide each household on McNeil Island with the community notification information provided for under RCW 4.24.550.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6151-S.SL.pdf?cite=2001%202nd%20sp.s.%20c%2012%20§%20223[2001 2nd sp.s. c 12 § 223]; ]

== 71.09.340 - Conditionally released persons—Employment, educational notification.
An employer who hires a person who has been conditionally released to a less restrictive alternative must notify all other employees of the conditionally released person's status. Notification for conditionally released persons who enroll in an institution of higher education shall be made pursuant to the provisions of RCW 9A.44.130 related to sex offenders enrolled in institutions of higher education and RCW 4.24.550. This section applies only to conditionally released persons whose court-approved treatment plan includes permission or a requirement for the person to obtain education or employment and to employment positions or educational programs that meet the requirements of the court-approved treatment plan.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6151-S.SL.pdf?cite=2001%202nd%20sp.s.%20c%2012%20§%20224[2001 2nd sp.s. c 12 § 224]; ]

== 71.09.341 - Transition facilities—Authority of department—Effect of local regulations.
The minimum requirements set out in RCW 71.09.285 through 71.09.340 are minimum requirements to be applied by the department. Nothing in this section is intended to prevent a city or county from adopting development regulations, as defined in RCW 36.70A.030, unless the proposed regulation imposes requirements more restrictive than those specifically addressed in RCW 71.09.285 through 71.09.340. Regulations that impose requirements more restrictive than those specifically addressed in these sections are void. Nothing in these sections prevents the department from adding requirements to enhance public safety.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6594-S.SL.pdf?cite=2002%20c%2068%20§%207[2002 c 68 § 7]; ]

== 71.09.342 - Transition facilities—Siting—Local regulations preempted, when—Consideration of public safety measures.
. After October 1, 2002, notwithstanding RCW 36.70A.103 or any other law, this section preempts and supersedes local plans, development regulations, permitting requirements, inspection requirements, and all other laws as necessary to enable the department to site, construct, renovate, occupy, and operate secure community transition facilities within the borders of the following:

.. Any county that had five or more persons civilly committed from that county, or detained at the special commitment center under a pending civil commitment petition from that county where a finding of probable cause has been made, on April 1, 2001, if the department determines that the county has not met the requirements of RCW 36.70A.200 with respect to secure community transition facilities. This subsection does not apply to the county in which the secure community transition facility authorized under RCW 71.09.250(1) is located; and

.. Any city located within a county listed in (a) of this subsection that the department determines has not met the requirements of RCW 36.70A.200 with respect to secure community transition facilities.

. The department's determination under subsection (1)(a) or (b) of this section is final and is not subject to appeal under chapter 34.05 or 36.70A RCW.

. When siting a facility in a county or city that has been preempted under this section, the department shall consider the policy guidelines established under RCW 71.09.285 and 71.09.290 and shall hold the hearings required in RCW 71.09.315.

. Nothing in this section prohibits the department from:

.. Siting a secure community transition facility in a city or county that has complied with the requirements of RCW 36.70A.200 with respect to secure community transition facilities, including a city that is located within a county that has been preempted. If the department sites a secure community transition facility in such a city or county, the department shall use the process established by the city or county for siting such facilities; or

.. Consulting with a city or county that has been preempted under this section regarding the siting of a secure community transition facility.

. [Empty]
.. A preempted city or county may propose public safety measures specific to any finalist site to the department. The measures must be consistent with the location of the facility at that finalist site. The proposal must be made in writing by the date of:

... The second hearing under RCW 71.09.315(2)(a) when there are three finalist sites; or

... The first hearing under RCW 71.09.315(2)(b) when there is only one site under consideration.

.. The department shall respond to the city or county in writing within fifteen business days of receiving the proposed measures. The response shall address all proposed measures.

.. If the city or county finds that the department's response is inadequate, the city or county may notify the department in writing within fifteen business days of the specific items which it finds inadequate. If the city or county does not notify the department of a finding that the response is inadequate within fifteen business days, the department's response shall be final.

.. If the city or county notifies the department that it finds the response inadequate and the department does not revise its response to the satisfaction of the city or county within seven business days, the city or county may petition the governor to designate a person with law enforcement expertise to review the response under RCW 34.05.479.

.. The governor's designee shall hear a petition filed under this subsection and shall make a determination within thirty days of hearing the petition. The governor's designee shall consider the department's response, and the effectiveness and cost of the proposed measures, in relation to the purposes of this chapter. The determination by the governor's designee shall be final and may not be the basis for any cause of action in civil court.

.. The city or county shall bear the cost of the petition to the governor's designee. If the city or county prevails on all issues, the department shall reimburse the city or county costs incurred, as provided under chapter 34.05 RCW.

.. Neither the department's consideration and response to public safety conditions proposed by a city or county nor the decision of the governor's designee shall affect the preemption under this section or the department's authority to site, construct, renovate, occupy, and operate the secure community transition facility at that finalist site or at any finalist site.

. Until June 30, 2009, the secretary shall site, construct, occupy, and operate a secure community transition facility sited under this section in an environmentally responsible manner that is consistent with the substantive objectives of chapter 43.21C RCW, and shall consult with the department of ecology as appropriate in carrying out the planning, construction, and operations of the facility. The secretary shall make a threshold determination of whether a secure community transition facility sited under this section would have a probable significant, adverse environmental impact. If the secretary determines that the secure community transition facility has such an impact, the secretary shall prepare an environmental impact statement that meets the requirements of RCW 43.21C.030 and 43.21C.031 and the rules promulgated by the department of ecology relating to such statements. Nothing in this subsection shall be the basis for any civil cause of action or administrative appeal.

. In no case may a secure community transition facility be sited adjacent to, immediately across a street or parking lot from, or within the line of sight of a risk potential activity or facility in existence at the time a site is listed for consideration unless the site that the department has chosen in a particular county or city was identified pursuant to a process for siting secure community transition facilities adopted by that county or city in compliance with RCW 36.70A.200. "Within the line of sight" means that it is possible to reasonably visually distinguish and recognize individuals.

. This section does not apply to the secure community transition facility established pursuant to RCW 71.09.250(1).

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5550-S.SL.pdf?cite=2003%20c%2050%20§%202[2003 c 50 § 2]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6594-S.SL.pdf?cite=2002%20c%2068%20§%209[2002 c 68 § 9]; ]

== 71.09.343 - Transition facilities—Contract between state and local governments.
. At the request of the local government of the city or county in which a secure community transition facility is initially sited after January 1, 2002, the department shall enter into a long-term contract memorializing the agreements between the state and the city or county for the operation of the facility. This contract shall be separate from any contract regarding mitigation due to the facility. The contract shall include a clause that states:

.. The contract does not obligate the state to continue operating any aspect of the civil commitment program under this chapter;

.. The operation of any secure community transition facility is contingent upon sufficient appropriation by the legislature. If sufficient funds are not appropriated, the department is not obligated to operate the secure community transition facility and may close it; and

.. This contract does not obligate the city or county to operate a secure community transition facility.

. Any city or county may, at their option, contract with the department to operate a secure community transition facility.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6594-S.SL.pdf?cite=2002%20c%2068%20§%2016[2002 c 68 § 16]; ]

== 71.09.344 - Transition facilities—Mitigation agreements.
. Subject to funds appropriated by the legislature, the department may enter into negotiation for a mitigation agreement with:

.. The county and/or city in which a secure community transition facility sited after January 1, 2002, is located;

.. Each community in which the persons from those facilities will reside or regularly spend time, pursuant to court orders, for regular work or education, or to receive social services, or through which the person or persons will regularly be transported to reach other communities; and

.. Educational institutions in the communities identified in (a) and (b) of this subsection.

. Mitigation agreements are limited to the following:

.. One-time training for local law enforcement and administrative staff, upon the establishment of a secure community transition facility.

... Training between local government staff and the department includes training in coordination, emergency procedures, program and facility information, legal requirements, and resident profiles.

... Reimbursement for training under this subsection is limited to:

(A) The salaries or hourly wages and benefits of those persons who receive training directly from the department; and

(B) Costs associated with preparation for, and delivery of, training to the department or its contracted staff by local government staff or contractors;

.. Information coordination:

... Information coordination includes database infrastructure establishment and programming for the dissemination of information among law enforcement and the department related to facility residents.

... Reimbursement for information coordination is limited to start-up costs;

.. One-time capital costs:

... One-time capital costs are off-site costs associated with the need for increased security in specific locations.

... Reimbursement for one-time capital costs is limited to actual costs; and

.. Incident response:

... Incident response costs are law enforcement and criminal justice costs associated with violations of conditions of release or crimes by residents of the secure community transition facility.

... Reimbursement for incident response does not include private causes of action.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6594-S.SL.pdf?cite=2002%20c%2068%20§%2017[2002 c 68 § 17]; ]

== 71.09.345 - Alternative placement—Authority of court.
Nothing in chapter 12, Laws of 2001 2nd sp. sess. shall operate to restrict a court's authority to make less restrictive alternative placements to a committed person's individual residence or to a setting less restrictive than a secure community transition facility. A court-ordered less restrictive alternative placement to a committed person's individual residence is not a less restrictive alternative placement to a secure community transition facility.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6151-S.SL.pdf?cite=2001%202nd%20sp.s.%20c%2012%20§%20226[2001 2nd sp.s. c 12 § 226]; ]

== 71.09.350 - Examination and treatment only by certified providers—Exceptions.
. Examinations and treatment of sexually violent predators who are conditionally released to a less restrictive alternative under this chapter shall be conducted only by certified sex offender treatment providers or certified affiliate sex offender treatment providers under chapter 18.155 RCW unless the court or the department of social and health services finds that: (a) The treatment provider is employed by the department; or (b)(i) all certified sex offender treatment providers or certified affiliate sex offender treatment providers become unavailable to provide treatment within a reasonable geographic distance of the person's home, as determined in rules adopted by the department of social and health services; and (ii) the evaluation and treatment plan comply with the rules adopted by the department of social and health services.

A treatment provider approved by the department of social and health services under (b) of this subsection, who is not certified by the department of health, shall consult with a certified sex offender treatment provider during the person's period of treatment to ensure compliance with the rules adopted by the department of health. The frequency and content of the consultation shall be based on the recommendation of the certified sex offender treatment provider.

. A treatment provider, whether or not he or she is employed or approved by the department of social and health services under subsection (1) of this section or otherwise certified, may not perform or provide treatment of sexually violent predators under this section if the treatment provider has been:

.. Convicted of a sex offense, as defined in RCW 9.94A.030;

.. Convicted in any other jurisdiction of an offense that under the laws of this state would be classified as a sex offense as defined in RCW 9.94A.030; or

.. Suspended or otherwise restricted from practicing any health care profession by competent authority in any state, federal, or foreign jurisdiction.

. Nothing in this section prohibits a qualified expert from examining or evaluating a sexually violent predator who has been conditionally released for purposes of presenting an opinion in court proceedings.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5718-S.SL.pdf?cite=2009%20c%20409%20§%2014[2009 c 409 § 14]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2849-S.SL.pdf?cite=2004%20c%2038%20§%2014[2004 c 38 § 14]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6151-S.SL.pdf?cite=2001%202nd%20sp.s.%20c%2012%20§%20404[2001 2nd sp.s. c 12 § 404]; ]

== 71.09.360 - Treatment of persons on conditional release by certified providers in underserved counties—Notification.
To facilitate the equitable geographic distribution of conditional releases under this chapter, the department shall notify the secretary of health, or the secretary's designee, whenever a sex offender treatment provider in an underserved county has been contracted to provide treatment services to persons on conditional release under this chapter, in which case the secretary of health shall waive any fees for the initial issue, renewal, and reissuance of a credential for the provider under chapter 18.155 RCW. An underserved county is any county identified by the department as having an inadequate supply of qualified sex offender treatment providers to achieve equitable geographic distribution of conditional releases under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6641-S.SL.pdf?cite=2020%20c%20266%20§%206[2020 c 266 § 6]; ]

== 71.09.800 - Rules.
The secretary shall adopt rules under the administrative procedure act, chapter 34.05 RCW, for the oversight and operation of the program established pursuant to this chapter. Such rules shall include provisions for an annual inspection of the special commitment center; requirements for treatment plans and the retention of records; and guidelines for attorneys to follow when bringing legal materials into secure facilities. Guidelines for attorneys shall not interfere with attorney-client privilege.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1836-S.SL.pdf?cite=2013%20c%2043%20§%202[2013 c 43 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2345-S.SL.pdf?cite=2000%20c%2044%20§%201[2000 c 44 § 1]; ]

== 71.09.903 - Construction—Chapter applicable to state registered domestic partnerships—2009 c 521.
For the purposes of this chapter, the terms spouse, marriage, marital, husband, wife, widow, widower, next of kin, and family shall be interpreted as applying equally to state registered domestic partnerships or individuals in state registered domestic partnerships as well as to marital relationships and married persons, and references to dissolution of marriage shall apply equally to state registered domestic partnerships that have been terminated, dissolved, or invalidated, to the extent that such interpretation does not conflict with federal law. Where necessary to implement chapter 521, Laws of 2009, gender-specific terms such as husband and wife used in any statute, rule, or other law shall be construed to be gender neutral, and applicable to individuals in state registered domestic partnerships.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%20159[2009 c 521 § 159]; ]

