= 71.12 - Private establishments.
:toc:

== 71.12.455 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Department" means the department of health.

. "Elopement" means any situation in which an admitted patient of a psychiatric hospital who is cognitively, physically, mentally, emotionally, and/or chemically impaired wanders, walks, runs away, escapes, or otherwise leaves a psychiatric hospital or the grounds of a psychiatric hospital prior to the patient's scheduled discharge unsupervised, unnoticed, and without the staff's knowledge.

. "Establishment" and "institution" mean:

.. Every private or county or municipal hospital, including public hospital districts, sanitariums, homes, psychiatric hospitals, residential treatment facilities, or other places receiving or caring for any person with mental illness, mentally incompetent person, or chemically dependent person; and

.. Beginning January 1, 2019, facilities providing pediatric transitional care services.

. "Immediate jeopardy" means a situation in which the psychiatric hospital's noncompliance with one or more statutory or regulatory requirements has placed the health and safety of patients in its care at risk for serious injury, serious harm, serious impairment, or death.

. "Pediatric transitional care services" means short-term, temporary, health and comfort services for drug exposed infants according to the requirements of this chapter and provided in an establishment licensed by the department of health.

. "Psychiatric hospital" means an establishment caring for any person with mental illness or substance use disorder excluding acute care hospitals licensed under chapter 70.41 RCW, state psychiatric hospitals established under chapter 72.23 RCW, and residential treatment facilities as defined in this section.

. "Residential treatment facility" means an establishment in which twenty-four hour on-site care is provided for the evaluation, stabilization, or treatment of residents for substance use, mental health, co-occurring disorders, or for drug exposed infants.

. "Secretary" means the secretary of the department of health.

. "Technical assistance" means the provision of information on the state laws and rules applicable to the regulation of psychiatric hospitals, the process to apply for a license, and methods and resources to avoid or address compliance problems. Technical assistance does not include assistance provided under chapter 43.05 RCW.

. "Trained caregiver" means a noncredentialed, unlicensed person trained by the establishment providing pediatric transitional care services to provide hands-on care to drug exposed infants. Caregivers may not provide medical care to infants and may only work under the supervision of an appropriate health care professional.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2426-S.SL.pdf?cite=2020%20c%20115%20§%206[2020 c 115 § 6]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5152-S.SL.pdf?cite=2017%20c%20263%20§%202[2017 c 263 § 2]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5986-S.SL.pdf?cite=2001%20c%20254%20§%201[2001 c 254 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2452.SL.pdf?cite=2000%20c%2093%20§%2021[2000 c 93 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c80.pdf?cite=1977%20ex.s.%20c%2080%20§%2043[1977 ex.s. c 80 § 43]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c25.pdf?cite=1959%20c%2025%20§%2071.12.455[1959 c 25 § 71.12.455]; prior:  1949 c 198 § 53; Rem. Supp. 1949 § 6953-52a; ]

== 71.12.460 - License to be obtained—Penalty.
No person, association, county, municipality, public hospital district, or corporation, shall establish or keep, for compensation or hire, an establishment as defined in this chapter without first having obtained a license therefor from the department of health, complied with rules adopted under this chapter, and paid the license fee provided in this chapter. Any person who carries on, conducts, or attempts to carry on or conduct an establishment as defined in this chapter without first having obtained a license from the department of health, as in this chapter provided, is guilty of a misdemeanor and on conviction thereof shall be punished by imprisonment in a county jail not exceeding six months, or by a fine not exceeding one thousand dollars, or by both such fine and imprisonment. The managing and executive officers of any corporation violating the provisions of this chapter shall be liable under the provisions of this chapter in the same manner and to the same effect as a private individual violating the same.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5986-S.SL.pdf?cite=2001%20c%20254%20§%202[2001 c 254 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2452.SL.pdf?cite=2000%20c%2093%20§%2022[2000 c 93 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c9.pdf?cite=1989%201st%20ex.s.%20c%209%20§%20226[1989 1st ex.s. c 9 § 226]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20133[1979 c 141 § 133]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c25.pdf?cite=1959%20c%2025%20§%2071.12.460[1959 c 25 § 71.12.460]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c198.pdf?cite=1949%20c%20198%20§%2054[1949 c 198 § 54]; Rem. Supp. 1949 § 6953-53; ]

== 71.12.470 - License application—Fees.
Every application for a license shall be accompanied by a plan of the premises proposed to be occupied, describing the capacities of the buildings for the uses intended, the extent and location of grounds appurtenant thereto, and the number of patients proposed to be received therein, with such other information, and in such form, as the department of health requires. The application shall be accompanied by the proper license fee. The amount of the license fee shall be established by the department of health under RCW 43.70.110.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2452.SL.pdf?cite=2000%20c%2093%20§%2023[2000 c 93 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c75.pdf?cite=1987%20c%2075%20§%2019[1987 c 75 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c201.pdf?cite=1982%20c%20201%20§%2014[1982 c 201 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c25.pdf?cite=1959%20c%2025%20§%2071.12.470[1959 c 25 § 71.12.470]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c198.pdf?cite=1949%20c%20198%20§%2056[1949 c 198 § 56]; Rem. Supp. 1949 § 6953-55; ]

== 71.12.480 - Examination before granting license—Inspection and technical assistance to psychiatric hospitals after granting license.
. The department of health shall not grant any such license until it has made an examination of all phases of the operation of the establishment necessary to determine compliance with rules adopted under this chapter including the premises proposed to be licensed and is satisfied that the premises are substantially as described, and are otherwise fit and suitable for the purposes for which they are designed to be used, and that such license should be granted.

. During the first two years of licensure for a new psychiatric hospital or any existing psychiatric hospital that changes ownership after July 1, 2020, the department shall provide technical assistance, perform at least three unannounced inspections, and conduct additional inspections of the hospital as necessary to verify the hospital is complying with the requirements of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2426-S.SL.pdf?cite=2020%20c%20115%20§%207[2020 c 115 § 7]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2452.SL.pdf?cite=2000%20c%2093%20§%2024[2000 c 93 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c9.pdf?cite=1989%201st%20ex.s.%20c%209%20§%20227[1989 1st ex.s. c 9 § 227]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20134[1979 c 141 § 134]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c25.pdf?cite=1959%20c%2025%20§%2071.12.480[1959 c 25 § 71.12.480]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c198.pdf?cite=1949%20c%20198%20§%2057[1949 c 198 § 57]; Rem. Supp. 1949 § 6953-56; ]

== 71.12.485 - Fire protection—Duties of chief of the Washington state patrol.
Standards for fire protection and the enforcement thereof, with respect to all establishments to be licensed hereunder, shall be the responsibility of the chief of the Washington state patrol, through the director of fire protection, who shall adopt such recognized standards as may be applicable to such establishments for the protection of life against the cause and spread of fire and fire hazards. The department of health, upon receipt of an application for a license, or renewal of a license, shall submit to the chief of the Washington state patrol, through the director of fire protection, in writing, a request for an inspection, giving the applicant's name and the location of the premises to be licensed. Upon receipt of such a request, the chief of the Washington state patrol, through the director of fire protection, or his or her deputy shall make an inspection of the establishment to be licensed, and if it is found that the premises do not comply with the required safety standards and fire regulations as promulgated by the chief of the Washington state patrol, through the director of fire protection, he or she shall promptly make a written report to the establishment and the department of health as to the manner and time allowed in which the premises must qualify for a license and set forth the conditions to be remedied with respect to fire regulations. The department of health, applicant or licensee shall notify the chief of the Washington state patrol, through the director of fire protection, upon completion of any requirements made by him or her, and the director of fire protection or his or her deputy shall make a reinspection of such premises. Whenever the establishment to be licensed meets with the approval of the chief of the Washington state patrol, through the director of fire protection, he or she shall submit to the department of health a written report approving same with respect to fire protection before a full license can be issued. The chief of the Washington state patrol, through the director of fire protection, shall make or cause to be made inspections of such establishments at least annually. The department of health shall not license or continue the license of any establishment unless and until it shall be approved by the chief of the Washington state patrol, through the director of fire protection, as herein provided.

In cities which have in force a comprehensive building code, the provisions of which are determined by the chief of the Washington state patrol, through the director of fire protection, to be equal to the minimum standards of the chief of the Washington state patrol, through the director of fire protection, for such establishments, the chief of the fire department, provided the latter is a paid chief of a paid fire department, shall make the inspection with the chief of the Washington state patrol, through the director of fire protection, or his or her deputy, and they shall jointly approve the premises before a full license can be issued.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5093-S.SL.pdf?cite=1995%20c%20369%20§%2061[1995 c 369 § 61]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c9.pdf?cite=1989%201st%20ex.s.%20c%209%20§%20228[1989 1st ex.s. c 9 § 228]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%20122[1986 c 266 § 122]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20135[1979 c 141 § 135]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c224.pdf?cite=1959%20c%20224%20§%201[1959 c 224 § 1]; ]

== 71.12.490 - Expiration and renewal of license.
All licenses issued under the provisions of this chapter shall expire on a date to be set by the department of health. No license issued pursuant to this chapter shall exceed thirty-six months in duration. Application for renewal of the license, accompanied by the necessary fee as established by the department of health under RCW 43.70.110, shall be filed with that department, not less than thirty days prior to its expiration and if application is not so filed, the license shall be automatically canceled.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c9.pdf?cite=1989%201st%20ex.s.%20c%209%20§%20229[1989 1st ex.s. c 9 § 229]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c75.pdf?cite=1987%20c%2075%20§%2020[1987 c 75 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c201.pdf?cite=1982%20c%20201%20§%2015[1982 c 201 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c247.pdf?cite=1971%20ex.s.%20c%20247%20§%204[1971 ex.s. c 247 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c25.pdf?cite=1959%20c%2025%20§%2071.12.490[1959 c 25 § 71.12.490]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c198.pdf?cite=1949%20c%20198%20§%2059[1949 c 198 § 59]; Rem. Supp. 1949 § 6953-58; ]

== 71.12.500 - Examination of premises as to compliance with the chapter, rules, and license—License changes.
The department of health may at any time examine and ascertain how far a licensed establishment is conducted in compliance with this chapter, the rules adopted under this chapter, and the requirements of the license therefor. If the interests of the patients of the establishment so demand, the department may, for just and reasonable cause, suspend, modify, or revoke any such license. RCW 43.70.115 governs notice of a license denial, revocation, suspension, or modification and provides the right to an adjudicative proceeding.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2452.SL.pdf?cite=2000%20c%2093%20§%2025[2000 c 93 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c9.pdf?cite=1989%201st%20ex.s.%20c%209%20§%20230[1989 1st ex.s. c 9 § 230]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c175.pdf?cite=1989%20c%20175%20§%20137[1989 c 175 § 137]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20136[1979 c 141 § 136]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c25.pdf?cite=1959%20c%2025%20§%2071.12.500[1959 c 25 § 71.12.500]; prior:  1949 c 198 § 58; Rem. Supp. 1949 § 6953-57; ]

== 71.12.510 - Examination and visitation in general.
The department of health may at any time cause any establishment as defined in this chapter to be visited and examined.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2452.SL.pdf?cite=2000%20c%2093%20§%2026[2000 c 93 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c25.pdf?cite=1959%20c%2025%20§%2071.12.510[1959 c 25 § 71.12.510]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c198.pdf?cite=1949%20c%20198%20§%2060[1949 c 198 § 60]; Rem. Supp. 1949 § 6953-59; ]

== 71.12.520 - Scope of examination.
Each such visit may include an inspection of every part of each establishment. The representatives of the department of health may make an examination of all records, methods of administration, the general and special dietary, the stores and methods of supply, and may cause an examination and diagnosis to be made of any person confined therein. The representatives of the department of health may examine to determine their fitness for their duties the officers, attendants, and other employees, and may talk with any of the patients apart from the officers and attendants.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2452.SL.pdf?cite=2000%20c%2093%20§%2027[2000 c 93 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c9.pdf?cite=1989%201st%20ex.s.%20c%209%20§%20231[1989 1st ex.s. c 9 § 231]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20137[1979 c 141 § 137]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c25.pdf?cite=1959%20c%2025%20§%2071.12.520[1959 c 25 § 71.12.520]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c198.pdf?cite=1949%20c%20198%20§%2061[1949 c 198 § 61]; Rem. Supp. 1949 § 6953-60; ]

== 71.12.530 - Conference with management—Improvement.
The representatives of the department of health may, from time to time, at times and places designated by the department, meet the managers or responsible authorities of such establishments in conference, and consider in detail all questions of management and improvement of the establishments, and may send to them, from time to time, written recommendations in regard thereto.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c9.pdf?cite=1989%201st%20ex.s.%20c%209%20§%20232[1989 1st ex.s. c 9 § 232]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20138[1979 c 141 § 138]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c25.pdf?cite=1959%20c%2025%20§%2071.12.530[1959 c 25 § 71.12.530]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c198.pdf?cite=1949%20c%20198%20§%2062[1949 c 198 § 62]; Rem. Supp. 1949 § 6953-61; ]

== 71.12.540 - Recommendations to be kept on file—Records of inmates.
The authorities of each establishment as defined in this chapter shall place on file in the office of the establishment the recommendations made by the department of health as a result of such visits, for the purpose of consultation by such authorities, and for reference by the department representatives upon their visits. Every such establishment shall keep records of every person admitted thereto as follows and shall furnish to the department, when required, the following data: Name, age, sex, marital status, date of admission, voluntary or other commitment, name of physician, physician assistant, or psychiatric advanced registered nurse practitioner, diagnosis, and date of discharge.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6445-S.SL.pdf?cite=2016%20c%20155%20§%2011[2016 c 155 § 11]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1071-S.SL.pdf?cite=2009%20c%20217%20§%2011[2009 c 217 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c9.pdf?cite=1989%201st%20ex.s.%20c%209%20§%20233[1989 1st ex.s. c 9 § 233]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20139[1979 c 141 § 139]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c25.pdf?cite=1959%20c%2025%20§%2071.12.540[1959 c 25 § 71.12.540]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c198.pdf?cite=1949%20c%20198%20§%2063[1949 c 198 § 63]; Rem. Supp. 1949 § 6953-62; ]

== 71.12.550 - Local authorities may also prescribe standards.
This chapter shall not prevent local authorities of any city, or city and county, within the reasonable exercise of the police power, from adopting rules and regulations, by ordinance or resolution, prescribing standards of sanitation, health and hygiene for establishments as defined in this chapter, which are not in conflict with the provisions of this chapter, and requiring a certificate by the local health officer, that the local health, sanitation and hygiene laws have been complied with before maintaining or conducting any such institution within such city or city and county.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c25.pdf?cite=1959%20c%2025%20§%2071.12.550[1959 c 25 § 71.12.550]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c198.pdf?cite=1949%20c%20198%20§%2064[1949 c 198 § 64]; Rem. Supp. 1949 § 6953-63; ]

== 71.12.560 - Voluntary patients—Receipt authorized—Application—Report.
The person in charge of any private institution, hospital, or sanitarium which is conducted for, or includes a department or ward conducted for, the care and treatment of persons who are mentally ill or deranged may receive therein as a voluntary patient any person suffering from mental illness or derangement who is a suitable person for care and treatment in the institution, hospital, or sanitarium, who voluntarily makes a written application to the person in charge for admission into the institution, hospital or sanitarium. At the expiration of fourteen continuous days of treatment of a patient voluntarily committed in a private institution, hospital, or sanitarium, if the period of voluntary commitment is to continue, the person in charge shall forward to the office of the department of social and health services a record of the voluntary patient showing the name, residence, date of birth, sex, place of birth, occupation, social security number, marital status, date of admission to the institution, hospital, or sanitarium, and such other information as may be required by rule of the department of social and health services.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=1994%20sp.s.%20c%207%20§%20441[1994 sp.s. c 7 § 441]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c145.pdf?cite=1974%20ex.s.%20c%20145%20§%201[1974 ex.s. c 145 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c142.pdf?cite=1973%201st%20ex.s.%20c%20142%20§%201[1973 1st ex.s. c 142 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c25.pdf?cite=1959%20c%2025%20§%2071.12.560[1959 c 25 § 71.12.560]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c198.pdf?cite=1949%20c%20198%20§%2065[1949 c 198 § 65]; Rem. Supp. 1949 § 6953-64; ]

== 71.12.570 - Communications by patients—Rights.
No person in an establishment as defined in this chapter shall be restrained from sending written communications of the fact of his or her detention in such establishment to a friend, relative, or other person. The physician in charge of such person and the person in charge of such establishment shall send each such communication to the person to whom it is addressed. All persons in an establishment shall have no less than all rights secured to involuntarily detained persons by RCW 71.05.217 and to voluntarily admitted or committed persons pursuant to RCW 71.05.050 and 71.05.380.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5720-S2.SL.pdf?cite=2020%20c%20302%20§%20114[2020 c 302 § 114]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20440[2012 c 117 § 440]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c142.pdf?cite=1973%201st%20ex.s.%20c%20142%20§%202[1973 1st ex.s. c 142 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c25.pdf?cite=1959%20c%2025%20§%2071.12.570[1959 c 25 § 71.12.570]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c198.pdf?cite=1949%20c%20198%20§%2066[1949 c 198 § 66]; Rem. Supp. 1949 § 6953-65; ]

== 71.12.590 - Revocation of license for noncompliance—Exemption as to Christian Science establishments.
Failure to comply with any of the provisions of RCW 71.12.550 through 71.12.570 or the requirements of RCW 71.34.375 shall constitute grounds for revocation of license: PROVIDED, HOWEVER, That nothing in this chapter or the rules and regulations adopted pursuant thereto shall be construed as authorizing the supervision, regulation, or control of the remedial care or treatment of residents or patients in any establishment, as defined in this chapter conducted in accordance with the practice and principles of the body known as Church of Christ, Scientist.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5187-S.SL.pdf?cite=2011%20c%20302%20§%204[2011 c 302 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c3.pdf?cite=1983%20c%203%20§%20180[1983 c 3 § 180]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c25.pdf?cite=1959%20c%2025%20§%2071.12.590[1959 c 25 § 71.12.590]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c198.pdf?cite=1949%20c%20198%20§%2068[1949 c 198 § 68]; Rem. Supp. 1949 § 6953-67; ]

== 71.12.595 - Suspension of license—Noncompliance with support order—Reissuance.
The department of health shall immediately suspend the license or certificate of a person who has been certified pursuant to RCW 74.20A.320 by the department of social and health services as a person who is not in compliance with a support order or a *residential or visitation order. If the person has continued to meet all other requirements for reinstatement during the suspension, reissuance of the license or certificate shall be automatic upon the department of health's receipt of a release issued by the department of social and health services stating that the licensee is in compliance with the order.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3901.SL.pdf?cite=1997%20c%2058%20§%20860[1997 c 58 § 860]; ]

== 71.12.640 - Prosecuting attorney shall prosecute violations.
The prosecuting attorney of every county shall, upon application by the department of social and health services, the department of health, or its authorized representatives, institute and conduct the prosecution of any action brought for the violation within his or her county of any of the provisions of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20441[2012 c 117 § 441]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c9.pdf?cite=1989%201st%20ex.s.%20c%209%20§%20234[1989 1st ex.s. c 9 § 234]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20140[1979 c 141 § 140]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c25.pdf?cite=1959%20c%2025%20§%2071.12.640[1959 c 25 § 71.12.640]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c198.pdf?cite=1949%20c%20198%20§%2055[1949 c 198 § 55]; Rem. Supp. 1949 § 6953-54; ]

== 71.12.670 - Licensing, operation, inspection—Adoption of rules.
The department of health shall adopt rules for the licensing, operation, and inspections of establishments and institutions and the enforcement thereof.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2452.SL.pdf?cite=2000%20c%2093%20§%2028[2000 c 93 § 28]; ]

== 71.12.680 - Pediatric transitional care services—Requirements.
. An establishment providing pediatric transitional care services to drug exposed infants must demonstrate that it is capable of providing services for children who:

.. Are no more than one year of age;

.. Have been exposed to drugs before birth;

.. Require twenty-four hour continuous residential care and skilled nursing services as a result of prenatal substance exposure; and

.. Are referred to the establishment by the department of social and health services, regional hospitals, and private parties.

. After January 1, 2019, no person may operate or maintain an establishment that provides pediatric transitional care services without a license under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5152-S.SL.pdf?cite=2017%20c%20263%20§%203[2017 c 263 § 3]; ]

== 71.12.682 - Pediatric transitional care services—Rules not considered new service category.
For the purposes of this chapter, the rules for pediatric transitional care services are not considered as a new department of social and health services service category.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5152-S.SL.pdf?cite=2017%20c%20263%20§%204[2017 c 263 § 4]; ]

== 71.12.684 - Pediatric transitional care services—Rules, requirements.
The secretary must, in consultation with the department of social and health services, adopt rules on pediatric transitional care services. The rules must:

. Establish requirements for medical examinations and consultations which must be delivered by an appropriate health care professional;

. Require twenty-four hour medical supervision for children receiving pediatric transitional services in accordance with the staffing ratios established under subsection (3) of this section;

. Include staffing ratios that consider the number of registered nurses or licensed practical nurses employed by the establishment and the number of trained caregivers on duty at the establishment. These staffing ratios may not require more than:

.. One registered nurse to be on duty at all times;

.. One registered nurse or licensed practical nurse to eight infants; and

.. One trained caregiver to four infants;

. Require establishments that provide pediatric transitional care services to prepare weekly plans specific to each infant in their care and in accordance with the health care professional's standing orders. The health care professional may modify an infant's weekly plan without reexamining the infant if he or she determines the modification is in the best interest of the child. This modification may be communicated to the registered nurse on duty at the establishment who must then implement the modification. Weekly plans are to include short-term goals for each infant and outcomes must be included in reports required by the department;

. Ensure that neonatal abstinence syndrome scoring is conducted by an appropriate health care professional;

. Establish drug exposed infant developmental screening tests for establishments that provide pediatric transitional care services to administer according to a schedule established by the secretary;

. Require the establishment to collaborate with the department of social and health services to develop an individualized safety plan for each child and to meet other contractual requirements of the department of social and health services to identify strategies to meet supervision needs, medical concerns, and family support needs;

. Establish the maximum amount of days an infant may be placed at an establishment;

. Develop timelines for initial and ongoing parent-infant visits to nurture and help develop attachment and bonding between the child and parent, if such visits are possible. Timelines must be developed upon placement of the infant in the establishment providing pediatric transitional care services;

. Determine how transportation for the infant will be provided, if needed;

. Establish on-site training requirements for caregivers, volunteers, parents, foster parents, and relatives;

. Establish background check requirements for caregivers, volunteers, employees, and any other person with unsupervised access to the infants under the care of the establishment; and

. Establish other requirements necessary to support the infant and the infant's family.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5152-S.SL.pdf?cite=2017%20c%20263%20§%205[2017 c 263 § 5]; ]

== 71.12.686 - Pediatric transitional care services—Duties of the department of social and health services.
After referral by the department of social and health services of an infant to an establishment approved to provide pediatric transitional care services, the department of social and health services:

. Retains primary responsibility for case management and must provide consultation to the establishment regarding all placements and permanency planning issues, including developing a parent-child visitation plan;

. Must work with the department and the establishment to identify and implement evidence-based practices that address current and best medical practices and parent participation; and

. Work with the establishment to ensure medicaid-eligible services are so billed.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5152-S.SL.pdf?cite=2017%20c%20263%20§%206[2017 c 263 § 6]; ]

== 71.12.688 - Pediatric transitional care services—Facilities not subject to construction review.
Facilities that provide pediatric transitional care services that are in existence on July 23, 2017, are not subject to construction review by the department for initial licensure.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5152-S.SL.pdf?cite=2017%20c%20263%20§%207[2017 c 263 § 7]; ]

== 71.12.700 - Psychiatric hospitals—Technical assistance.
. Any psychiatric hospital may request from the department or the department may offer to any psychiatric hospital technical assistance. The department may not provide technical assistance during an inspection or during the time between when an investigation of a psychiatric hospital has been initiated and when such investigation is resolved.

. The department may offer group training to psychiatric hospitals licensed under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2426-S.SL.pdf?cite=2020%20c%20115%20§%202[2020 c 115 § 2]; ]

== 71.12.710 - Psychiatric hospitals—Noncompliance—Penalties.
. In any case in which the department finds that a licensed psychiatric hospital has failed or refused to comply with applicable state statutes or regulations, the department may take one or more of the actions identified in this section, except as otherwise limited in this section.

.. When the department determines the psychiatric hospital has previously been subject to an enforcement action for the same or similar type of violation of the same statute or rule, or has been given any previous statement of deficiency that included the same or similar type of violation of the same or similar statute or rule, or when the psychiatric hospital failed to correct noncompliance with a statute or rule by a date established or agreed to by the department, the department may impose reasonable conditions on a license. Conditions may include correction within a specified amount of time, training, or hiring a department-approved consultant if the hospital cannot demonstrate to the department that it has access to sufficient internal expertise.

.. [Empty]
... In accordance with the authority the department has under RCW 43.70.095, the department may assess a civil fine of up to ten thousand dollars per violation, not to exceed a total fine of one million dollars, on a hospital licensed under this chapter when the department determines the psychiatric hospital has previously been subject to an enforcement action for the same or similar type of violation of the same statute or rule, or has been given any previous statement of deficiency that included the same or similar type of violation of the same or similar statute or rule, or when the psychiatric hospital failed to correct noncompliance with a statute or rule by a date established or agreed to by the department.

... Proceeds from these fines may only be used by the department to provide training or technical assistance to psychiatric hospitals and to offset costs associated with licensing psychiatric hospitals.

... The department shall adopt in rules under this chapter specific fine amounts in relation to the severity of the noncompliance.

... If a licensee is aggrieved by the department's action of assessing civil fines, the licensee has the right to appeal under RCW 43.70.095.

.. In accordance with RCW 43.70.095, the department may impose civil fines of up to ten thousand dollars for each day a person operates a psychiatric hospital without a valid license. Proceeds from these fines may only be used by the department to provide training or technical assistance to psychiatric hospitals and to offset costs associated with licensing psychiatric hospitals.

.. The department may suspend admissions of a specific category or categories of patients as related to the violation by imposing a limited stop placement. This may only be done if the department finds that noncompliance results in immediate jeopardy.

... Prior to imposing a limited stop placement, the department shall provide a psychiatric hospital written notification upon identifying deficient practices or conditions that constitute an immediate jeopardy, and the psychiatric hospital shall have twenty-four hours from notification to develop and implement a department-approved plan to correct the deficient practices or conditions that constitute an immediate jeopardy. If the deficient practice or conditions that constitute immediate jeopardy are not verified by the department as having been corrected within the same twenty-four hour period, the department may issue the limited stop placement.

... When the department imposes a limited stop placement, the psychiatric hospital may not admit any new patients in the category or categories subject to the limited stop placement until the limited stop placement order is terminated.

... The department shall conduct a follow-up inspection within five business days or within the time period requested by the psychiatric hospital if more than five business days is needed to verify the violation necessitating the limited stop placement has been corrected.

... The limited stop placement shall be terminated when:

(A) The department verifies the violation necessitating the limited stop placement has been corrected or the department determines that the psychiatric hospital has taken intermediate action to address the immediate jeopardy; and

(B) The psychiatric hospital establishes the ability to maintain correction of the violation previously found deficient.

.. The department may suspend new admissions to the psychiatric hospital by imposing a stop placement. This may only be done if the department finds that noncompliance results in immediate jeopardy and is not confined to a specific category or categories of patients or a specific area of the psychiatric hospital.

... Prior to imposing a stop placement, the department shall provide a psychiatric hospital written notification upon identifying deficient practices or conditions that constitute an immediate jeopardy, and the psychiatric hospital shall have twenty-four hours from notification to develop and implement a department-approved plan to correct the deficient practices or conditions that constitute an immediate jeopardy. If the deficient practice or conditions that constitute immediate jeopardy are not verified by the department as having been corrected within the same twenty-four hour period, the department may issue the stop placement.

... When the department imposes a stop placement, the psychiatric hospital may not admit any new patients until the stop placement order is terminated.

... The department shall conduct a follow-up inspection within five business days or within the time period requested by the psychiatric hospital if more than five business days is needed to verify the violation necessitating the stop placement has been corrected.

... The stop placement order shall be terminated when:

(A) The department verifies the violation necessitating the stop placement has been corrected or the department determines that the psychiatric hospital has taken intermediate action to address the immediate jeopardy; and

(B) The psychiatric hospital establishes the ability to maintain correction of the violation previously found deficient.

.. The department may suspend, revoke, or refuse to renew a license.

. [Empty]
.. Except as otherwise provided, RCW 43.70.115 governs notice of the imposition of conditions on a license, a limited stop placement, stop placement, or the suspension, revocation, or refusal to renew a license and provides the right to an adjudicative proceeding. Adjudicative proceedings and hearings under this section are governed by the administrative procedure act, chapter 34.05 RCW. The application for an adjudicative proceeding must be in writing, state the basis for contesting the adverse action, including a copy of the department's notice, be served on and received by the department within twenty-eight days of the licensee's receipt of the adverse notice, and be served in a manner that shows proof of receipt.

.. When the department determines a licensee's noncompliance results in immediate jeopardy, the department may make the imposition of conditions on a licensee, a limited stop placement, stop placement, or the suspension of a license effective immediately upon receipt of the notice by the licensee, pending any adjudicative proceeding.

... When the department makes the suspension of a license or imposition of conditions on a license effective immediately, a licensee is entitled to a show cause hearing before a presiding officer within fourteen days of making the request. The licensee must request the show cause hearing within twenty-eight days of receipt of the notice of immediate suspension or immediate imposition of conditions. At the show cause hearing the department has the burden of demonstrating that more probably than not there is an immediate jeopardy.

... At the show cause hearing, the presiding officer may consider the notice and documents supporting the immediate suspension or immediate imposition of conditions and the licensee's response and must provide the parties with an opportunity to provide documentary evidence and written testimony, and to be represented by counsel. Prior to the show cause hearing, the department must provide the licensee with all documentation that supports the department's immediate suspension.

... If the presiding officer determines there is no immediate jeopardy, the presiding officer may overturn the immediate suspension or immediate imposition of conditions.

... If the presiding officer determines there is immediate jeopardy, the immediate suspension or immediate imposition of conditions shall remain in effect pending a full hearing.

.. If the secretary sustains the immediate suspension or immediate imposition of conditions, the licensee may request an expedited full hearing on the merits of the department's action. A full hearing must be provided within ninety days of the licensee's request.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2426-S.SL.pdf?cite=2020%20c%20115%20§%203[2020 c 115 § 3]; ]

== 71.12.720 - Psychiatric hospitals—Reporting.
. Every psychiatric hospital licensed under this chapter shall report to the department every patient elopement and every death that meets the circumstances specified in subsection (2) of this section that occurs on the hospital grounds within three days of the elopement or death to the department's complaint intake system or another reporting mechanism specified by the department in rule.

. The patient or staff deaths that must be reported to the department under subsection (1) of this section include the following:

.. Patient death associated with patient elopement;

.. Patient suicide;

.. Patient death associated with medication error;

.. Patient death associated with a fall;

.. Patient death associated with the use of physical restraints or bedrails; and

.. Patient or staff member death resulting from a physical assault.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2426-S.SL.pdf?cite=2020%20c%20115%20§%208[2020 c 115 § 8]; ]

== 71.12.900 - Construction—Chapter applicable to state registered domestic partnerships—2009 c 521.
For the purposes of this chapter, the terms spouse, marriage, marital, husband, wife, widow, widower, next of kin, and family shall be interpreted as applying equally to state registered domestic partnerships or individuals in state registered domestic partnerships as well as to marital relationships and married persons, and references to dissolution of marriage shall apply equally to state registered domestic partnerships that have been terminated, dissolved, or invalidated, to the extent that such interpretation does not conflict with federal law. Where necessary to implement chapter 521, Laws of 2009, gender-specific terms such as husband and wife used in any statute, rule, or other law shall be construed to be gender neutral, and applicable to individuals in state registered domestic partnerships.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%20160[2009 c 521 § 160]; ]

