= 71.20 - Local funds for community services.
:toc:

== 71.20.100 - Expenditures of county funds subject to county fiscal laws.
Expenditures of county funds under this chapter shall be subject to the provisions of chapter 36.40 RCW and other statutes relating to expenditures by counties.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c110.pdf?cite=1967%20ex.s.%20c%20110%20§%2010[1967 ex.s. c 110 § 10]; ]

== 71.20.110 - Tax levy directed—Allocation of funds for federal matching funds purposes.
. In order to provide additional funds for the coordination and provision of community services for persons with developmental disabilities or mental health services, the county governing authority of each county in the state must budget and levy annually a tax in a sum equal to the amount which would be raised by a levy of two and one-half cents per thousand dollars of assessed value against the taxable property in the county, or as such amount is modified pursuant to subsection (2) or (3) of this section, to be used for such purposes. However, all or part of the funds collected from the tax levied for the purposes of this section may be transferred to the state of Washington, department of social and health services, for the purpose of obtaining federal matching funds to provide and coordinate community services for persons with developmental disabilities and mental health services. In the event a county elects to transfer such tax funds to the state for this purpose, the state must grant these moneys and the additional funds received as matching funds to service-providing community agencies or community boards in the county which has made such transfer, pursuant to the plan approved by the county, as provided by chapters 71.24 and 71.28 RCW and by chapter 71A.14 RCW, all as now or hereafter amended.

. The amount of a levy allocated to the purposes specified in this section may be reduced in the same proportion as the regular property tax levy of the county is reduced by chapter 84.55 RCW.

. [Empty]
.. The amount of a levy allocated to the purposes specified in this section may be modified from the amount required by subsection (1) of this section as follows:

... If the certified levy is reduced from the preceding year's certified levy, the amount of the levy allocated to the purposes specified in this section may be reduced by no more than the same percentage as the certified levy is reduced from the preceding year's certified levy;

... If the certified levy is increased from the preceding year's certified levy, the amount of the levy allocated to the purposes specified in this section must be increased from the amount of the levy so allocated in the previous year by at least the same percentage as the certified levy is increased from the preceding year's certified levy. However, the amount of the levy allocated to the purposes specified in this section does not have to be increased under this subsection (3)(a)(ii) for the portion of a certified levy increase resulting from a voter-approved increase under RCW 84.55.050 that is dedicated to a specific purpose; or

... If the certified levy is unchanged from the preceding year's certified levy, the amount of the levy allocated to the purposes specified in this section must be equal to or greater than the amount of the levy so allocated in the preceding year.

.. For purposes of this subsection, "certified levy" means the property tax levy for general county purposes certified to the county assessor as required by RCW 84.52.070, excluding any amounts certified under chapters 84.69 and 84.68 RCW.

. Subsections (2) and (3) of this section do not preclude a county from increasing the levy amount in subsection (1) of this section to an amount that is greater than the change in the regular county levy.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1432-S.SL.pdf?cite=2013%20c%20123%20§%201[2013 c 123 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c176.pdf?cite=1988%20c%20176%20§%20910[1988 c 176 § 910]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c3.pdf?cite=1983%20c%203%20§%20183[1983 c 3 § 183]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c155.pdf?cite=1980%20c%20155%20§%205[1980 c 155 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c71.pdf?cite=1974%20ex.s.%20c%2071%20§%208[1974 ex.s. c 71 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c195.pdf?cite=1973%201st%20ex.s.%20c%20195%20§%2085[1973 1st ex.s. c 195 § 85]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c84.pdf?cite=1971%20ex.s.%20c%2084%20§%201[1971 ex.s. c 84 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c47.pdf?cite=1970%20ex.s.%20c%2047%20§%208[1970 ex.s. c 47 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c110.pdf?cite=1967%20ex.s.%20c%20110%20§%2016[1967 ex.s. c 110 § 16]; ]

