= 89.50 - Washington food policy forum.
:toc:

== 89.50.010 - Findings—Purpose.
. The legislature finds that:

.. Numerous governmental agencies, state programs, and private entities share goals and missions relating to food, nutrition, agriculture, health, education, and economic development through sustained agricultural production and improved access to nutritious foods;

.. The food and agriculture industry generates fifty-one billion dollars annually, employs one hundred sixty thousand people, and contributes thirteen percent to the state's economy;

.. Agriculture is a leading employer in the state, produces over three hundred different crops, and is composed of many diverse types of agricultural endeavors;

.. Small and direct marketing farms are a significant sector in Washington's agricultural industry. Eighty-five percent of farms in Washington state are classified as small farms. Washington is among the top ten states in the nation for the number of farms engaging in direct sales to local and regional markets. Because of their scale, diversity of agricultural products, engagement in value-added processing, and use of local and direct sales channels, these farms tend not to be represented by commodity commissions and traditional agricultural organizations;

.. The state of Washington continues to lose farmland every year to nonfarming uses;

.. The state's food system is the network of people and activities connecting growing and harvesting, processing, distribution, consumption, and residue utilization, as well as associated government and nongovernment institutions, regulations, and programs;

.. More than ten percent of Washington households experience food insecurity or hunger and many public and charitable organizations are engaged in the distribution of food and food benefits to those in need, so there exists an opportunity to build on connections between these organizations and farmers to enhance the delivery of Washington-produced food to various food programs;

.. The current food system in the state of Washington is complex and directly affected by the activities and policies of multiple federal and state agencies and local governments;

.. Small and mid-scale farms in Washington provide local food and maintain a vibrant culture of agriculture. Although several programs exist to support small and mid-scale farm operations, there are opportunities to evaluate the effectiveness of these programs to reduce duplication of effort, streamline service delivery, and expand access to the farmers; and

.. The work done by the regional food policy councils in the state can serve as a model for local efforts to bring together community, government, business, and agricultural interests, and improved communication between these local activities, combined with state efforts, could strengthen the state food policy system.

. The legislature recognizes the need to understand the impacts of governmental rules and regulations on the viability of small and mid-scale agriculture.

. The purpose of this chapter is to provide for the establishment of a forum to: (a) Increase the sales of Washington farm products through direct marketing and other regional supply chains; (b) reduce food insecurity in Washington; (c) identify opportunities to improve coordination between local and regional food policy councils and state and federal agencies; (d) identify current rules and regulations impeding the viability of small and mid-scale agriculture; and (e) identify new policies that would improve the viability of small and mid-scale agriculture.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=2020%20c%20246%20§%201[2020 c 246 § 1]; ]

== 89.50.020 - Washington food policy forum established.
. The Washington food policy forum is established as a public-private partnership and its purpose is to develop recommendations to advance the following food system goals:

.. To increase the availability of Washington-grown foods throughout the state, including by increasing direct marketing sales and consumption of Washington-grown foods;

.. To expand and promote programs that bring healthy and nutritious Washington-grown foods to Washington residents, including increased public and private purchasing of Washington food products for schools, adult care programs, and other publicly funded food programs;

.. To examine ways to encourage retention of an adequate number of farmers for small and mid-scale farms, meet the educational needs for the next generation of farmers, and provide for the continued economic viability of Washington food production, processing, and distribution in the state;

.. To reduce food insecurity and hunger in the state; and

.. To identify ways to improve coordination and communication among city, county, regional, and state food policy entities and communication between these entities and state agencies.

. Recommendations of the food policy forum must consider, but not be limited to, ways in which the following may help achieve each of the goals identified under subsection (1) of this section:

.. Increased collaboration and communication between local, state, and federal governments and agencies;

.. Innovative public-private partnerships that can leverage private and public market influence, such as through institutional purchasing and contracts;

.. Improvements to state or federal laws or regulations or funding relevant to the small and mid-scale farming interactions with the food system and food security in the state;

.. Improvements in state or federal program implementation relevant to small and mid-scale farming interactions with the food system and food security in the state;

.. Identification of additional federal, state, local, and private investments needed to accomplish the recommendations; and

.. Defining and describing the variety of agriculture in the state utilizing farm acreage, farm business type, crop and agricultural product type, and defining what the term "local" means in the context of food production and distribution.

. In developing its recommendations, the food policy forum:

.. Shall coordinate with appropriate local, state, and federal agencies, tribes, and nongovernmental organizations to avoid duplication of effort;

.. Shall solicit public input through public hearings or informational sessions;

.. May conduct research and analysis as needed within financial resources available to the forum; and

.. May form an advisory committee or committees to address issues identified by the forum and that are within the guidelines of subsection (1) of this section, as requiring additional study or particular expertise.

. The directors of the state conservation commission and the department of agriculture are responsible for appointing participating members of the food policy forum and no appointment may be made unless each director concurs in the appointment. In making appointments, the directors must attempt to ensure a diversity of knowledge, experience, and perspectives reflecting the issues to be addressed by the forum including, but not limited to:

.. State and federal government employees, including academia;

.. Related nonprofit and community organizations; and

.. The food industry, including food production, processing, distribution, marketing, and retail sales.

. A majority of the participating members appointed by the directors must appoint an administrative chair for the forum.

. In addition to members appointed by the directors, four legislators may serve on the food policy forum in an ex officio capacity. Legislative participants must be appointed as follows:

.. The speaker of the house of representatives shall appoint one member from each of the two largest caucuses of the house of representatives; and

.. The president of the senate shall appoint one member from each of the two largest caucuses of the senate.

. Each member of the food policy forum shall serve without compensation but may be reimbursed for travel expenses as authorized in RCW 43.03.050 and 43.03.060.

. Staff for the food policy forum must be provided by the state conservation commission and the department of agriculture. The state conservation commission and the department of agriculture are jointly responsible for transmitting the recommendations of the food policy forum to the legislature, consistent with RCW 43.01.036, by October 29, 2021, and every odd-numbered year thereafter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=2020%20c%20246%20§%202[2020 c 246 § 2]; ]

