= 3.02 - Courts of limited jurisdiction.
:toc:

== 3.02.010 - Court of limited jurisdiction defined.
For purposes of this chapter, a court of limited jurisdiction is any court organized under Titles 3, 35, or 35A RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c162.pdf?cite=1980%20c%20162%20§%201[1980 c 162 § 1]; ]

== 3.02.020 - Review of proceedings.
Review of the proceedings in a court of limited jurisdiction shall be by the superior court, the procedure for which may be established by supreme court rule.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c162.pdf?cite=1980%20c%20162%20§%202[1980 c 162 § 2]; ]

== 3.02.030 - Record of proceedings.
The supreme court may, by court rule, establish a method of making a record of the proceedings of a court of limited jurisdiction for purposes of review.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c162.pdf?cite=1980%20c%20162%20§%203[1980 c 162 § 3]; ]

== 3.02.040 - Electronic recording equipment.
The administrator for the courts may be consulted for advice on the selection, installation, and operation of any electronic recording equipment in courts of limited jurisdiction.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1111-S.SL.pdf?cite=2016%20c%2074%20§%203[2016 c 74 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c162.pdf?cite=1980%20c%20162%20§%204[1980 c 162 § 4]; ]

== 3.02.045 - Use of collection agencies and attorneys to collect unpaid amounts—Interest to agency authorized—Credit or debit card use—Assessment of amounts paid for collection as court costs.
. Courts of limited jurisdiction may use collection agencies under chapter 19.16 RCW for purposes of collecting unpaid penalties on infractions, criminal fines, costs, assessments, civil judgments, or forfeitures that have been imposed by the courts. Courts of limited jurisdiction may enter into agreements with one or more attorneys or collection agencies for collection of outstanding penalties, fines, costs, assessments, and forfeitures. These agreements may specify the scope of work, remuneration for services, and other charges deemed appropriate. Such agreements may authorize collection agencies to retain all or any portion of the interest collected on these accounts.

. Courts of limited jurisdiction may use credit cards or debit cards for purposes of billing and collecting unpaid penalties, fines, costs, assessments, and forfeitures so imposed. Courts of limited jurisdiction may enter into agreements with one or more financial institutions for the purpose of the collection of penalties, fines, costs, assessments, and forfeitures. The agreements may specify conditions, remuneration for services, and other charges deemed appropriate.

. Servicing of delinquencies by collection agencies or by collecting attorneys in which the court retains control of its delinquencies shall not constitute assignment of debt.

. For purposes of this section, the term debt shall include penalties, fines, costs, assessments, or forfeitures imposed by the courts.

. The court may assess as court costs the moneys paid for remuneration for services or charges paid to collecting attorneys, to collection agencies, or, in the case of credit cards, to financial institutions.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1680-S.SL.pdf?cite=1995%20c%20291%20§%201[1995 c 291 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5098.SL.pdf?cite=1995%20c%2038%20§%201[1995 c 38 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5372-S2.SL.pdf?cite=1994%20c%20301%20§%201[1994 c 301 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c266.pdf?cite=1987%20c%20266%20§%201[1987 c 266 § 1]; ]

== 3.02.050 - Discovery rules in civil cases.
By January 1, 1982, the supreme court shall adopt rules providing for discovery in civil cases in the courts of limited jurisdiction.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c331.pdf?cite=1981%20c%20331%20§%208[1981 c 331 § 8]; ]

== 3.02.060 - Judge pro tempore appointments.
A judge pro tempore may be authorized under RCW 3.50.090 or 35.20.200 whenever a judge of the municipal court serves on a judicial commission, board, or committee established by the legislature or the chief justice of the supreme court. The judge pro tempore shall be compensated as specified in RCW 3.50.090 or 35.20.200.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2407.SL.pdf?cite=2000%20c%20165%20§%202[2000 c 165 § 2]; ]

== 3.02.070 - Applicability of courts open to all act.
The provisions of RCW 2.28.300 through 2.28.330 apply to courts of limited jurisdiction.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2567-S.SL.pdf?cite=2020%20c%2037%20§%207[2020 c 37 § 7]; ]

