= 3.70 - Magistrates' association.
:toc:

== 3.70.010 - District and municipal court judges' association established.
There is established in the state an association, to be known as the Washington state district and municipal court judges' association, membership in which shall include all duly elected or appointed and qualified judges of courts of limited jurisdiction, including but not limited to district judges and municipal court judges.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6067.SL.pdf?cite=1994%20c%2032%20§%203[1994 c 32 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c3.pdf?cite=1987%20c%203%20§%202[1987 c 3 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c258.pdf?cite=1984%20c%20258%20§%2050[1984 c 258 § 50]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c299.pdf?cite=1961%20c%20299%20§%20123[1961 c 299 § 123]; ]

== 3.70.020 - Formalities—Meetings.
Members of the Washington state district and municipal court judges' association may either amend the present bylaws of the association, adopt a constitution, or provide for bylaws only, electing officers as provided therein and doing all things necessary and proper to formally establish a permanent Washington state district and municipal court judges' association. The association may meet each year at a time established by the association's governing board. Meetings shall be held in the state of Washington.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6067.SL.pdf?cite=1994%20c%2032%20§%204[1994 c 32 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c258.pdf?cite=1984%20c%20258%20§%2051[1984 c 258 § 51]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c299.pdf?cite=1961%20c%20299%20§%20124[1961 c 299 § 124]; ]

== 3.70.030 - Expenses of members.
For attendance at the annual meetings of the association, beginning in 1962 and thereafter, a judge of a court of limited jurisdiction shall be entitled to receive reimbursement for judge's reasonable travel expenses as provided in RCW 43.03.050 and 43.03.060 from the county or city responsible for the operating cost of the court over which he or she presides while attending meetings of the association. The per diem and transportation or mileage allowance authorized by this section shall not be paid to any judge for more than five days in any one calendar year.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c258.pdf?cite=1984%20c%20258%20§%2052[1984 c 258 § 52]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c299.pdf?cite=1961%20c%20299%20§%20125[1961 c 299 § 125]; ]

== 3.70.040 - Duties.
The Washington state district and municipal court judges' association shall:

. Continuously survey and study the operation of the courts served by its membership, the volume and condition of business of such courts, the methods of procedure therein, the work accomplished, and the character of the results;

. Promulgate suggested rules for the administration of the courts of limited jurisdiction not inconsistent with the law or rules of the supreme court relating to such courts;

. Report annually to the supreme court as well as the governor and the legislature on the condition of business in the courts of limited jurisdiction, including the association's recommendations as to needed changes in the organization, operation, judicial procedure, and laws or statutes implemented or enforced in these courts.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6067.SL.pdf?cite=1994%20c%2032%20§%205[1994 c 32 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c258.pdf?cite=1984%20c%20258%20§%2053[1984 c 258 § 53]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c162.pdf?cite=1980%20c%20162%20§%2010[1980 c 162 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c299.pdf?cite=1961%20c%20299%20§%20126[1961 c 299 § 126]; ]

