= 52.08 - Withdrawal.
:toc:

== 52.08.001 - Actions subject to review by boundary review board.
Actions taken under chapter 52.08 RCW may be subject to potential review by a boundary review board under chapter 36.93 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c84.pdf?cite=1989%20c%2084%20§%2044[1989 c 84 § 44]; ]

== 52.08.011 - Withdrawal authorized.
Territory within a fire protection district may be withdrawn from the district in the same manner provided by law for withdrawal of territory from water-sewer districts, as provided by chapter 57.28 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1264.SL.pdf?cite=1999%20c%20153%20§%2061[1999 c 153 § 61]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c230.pdf?cite=1984%20c%20230%20§%2054[1984 c 230 § 54]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c111.pdf?cite=1955%20c%20111%20§%201[1955 c 111 § 1]; ]

== 52.08.021 - Withdrawal by incorporation of part of district.
The incorporation of any previously unincorporated land lying within a fire protection district shall operate to automatically withdraw such lands from the fire protection district.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c237.pdf?cite=1959%20c%20237%20§%205[1959 c 237 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c111.pdf?cite=1955%20c%20111%20§%202[1955 c 111 § 2]; ]

== 52.08.025 - City may not be included within district—Exceptions—Withdrawal of city.
Effective January 1, 1960, every city or town, or portion thereof, which is situated within the boundaries of a fire protection district shall become automatically removed from such fire protection district, and no fire protection district shall thereafter include any city or town, or portion thereof, within its boundaries except as provided for in RCW 52.02.020, 52.04.061, 52.04.071, 52.04.081, 52.04.101, and 52.04.161.

However, if the area which incorporates or is annexed includes all of a fire protection district, the fire protection district, for purposes of imposing regular property taxes, shall continue in existence: (1)(a) Until the first day of January in the year in which the initial property tax collections of the newly incorporated city or town will be made, if a resolution is adopted under RCW 52.04.161 precluding annexation of the city or town to the district; (b) until the city or town is withdrawn from the fire protection district, if no such resolution is adopted and no ballot proposition under RCW 52.04.161 is approved; or (c) indefinitely, if such a ballot proposition is approved; or (2) until the first day of January in the year the annexing city or town will collect its property taxes imposed on the newly annexed area. The members of the city or town council or commission shall act as the board of commissioners to impose, receive, and expend these property taxes.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1911.SL.pdf?cite=1993%20c%20262%20§%202[1993 c 262 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c234.pdf?cite=1986%20c%20234%20§%2035[1986 c 234 § 35]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%20119[1985 c 7 § 119]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c179.pdf?cite=1979%20ex.s.%20c%20179%20§%206[1979 ex.s. c 179 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c237.pdf?cite=1959%20c%20237%20§%206[1959 c 237 § 6]; ]

== 52.08.035 - City withdrawn to determine fire and emergency medical protection methods—Contracts—Joint operations—Sale, lease, etc., of property.
A city or town encompassing territory withdrawn under chapter 52.08 RCW shall determine the most effective and feasible fire protection and emergency medical protection for the withdrawn territory, or any part thereof, and the legislative authority of the city or town and the commissioners of the fire protection district may, without limitation of any other powers provided by law:

. Enter into contracts to the same extent as fire protection districts and cities and towns may enter into contracts under authority of *RCW 52.12.031(3), and

. Sell, purchase, rent, lease, or exchange property of every nature.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c230.pdf?cite=1984%20c%20230%20§%2055[1984 c 230 § 55]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c237.pdf?cite=1959%20c%20237%20§%208[1959 c 237 § 8]; ]

== 52.08.041 - Taxes and assessments unaffected.
The provisions of RCW 57.28.110 shall apply to territory withdrawn from a fire protection district under the provision of chapter 52.08 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%20120[1985 c 7 § 120]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c237.pdf?cite=1959%20c%20237%20§%207[1959 c 237 § 7]; ]

== 52.08.051 - Commissioners residing in territory withdrawn—Vacancy created.
Fire protection district commissioners residing in territory withdrawn from a fire protection district shall be replaced in the manner provided for the filling of vacancies in RCW 52.14.050.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c230.pdf?cite=1984%20c%20230%20§%2056[1984 c 230 § 56]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c237.pdf?cite=1959%20c%20237%20§%209[1959 c 237 § 9]; ]

