= 52.18 - Benefit charges.
:toc:

== 52.18.010 - Benefit charges authorized—Exemptions—Amounts—Limitations—Annual review.
. Pursuant to an approved initial or continued benefit charge authorized under RCW 52.18.050, the board of fire commissioners of a fire protection district may by resolution, for fire protection district purposes authorized by law, fix and impose a benefit charge on personal property and improvements to real property which are located within the fire protection district on the date specified and which have or will receive the benefits provided by the fire protection district, to be paid by the owners of the properties.

. A benefit charge does not apply to:

.. Personal property and improvements to real property owned or used by any recognized religious denomination or religious organization as, or including, a sanctuary or for purposes related to the bona fide religious ministries of the denomination or religious organization, including schools and educational facilities used for kindergarten, primary, or secondary educational purposes or for institutions of higher education and all grounds and buildings related thereto, but not including personal property and improvements to real property owned or used by any recognized religious denomination or religious organization for business operations, profit-making enterprises, or activities not including use of a sanctuary or related to kindergarten, primary, or secondary educational purposes or for institutions of higher education; and

.. Any of the following tax-exempt properties, provided such entity is not required to pay a fire protection charge under subsection (8) of this section:

... Property of housing authorities that is exempt from property taxes under RCW 35.82.210;

... Property of nonprofit entities providing rental housing for very low-income households or providing space for the placement of a mobile home for a very low-income household that is exempt from property taxes under RCW 84.36.560;

... Property of nonprofit homes for the aging that is exempt from property taxes under RCW 84.36.041;

... Property of nonprofit organizations, corporations, or associations providing housing for eligible persons with developmental disabilities that is exempt from property taxes under RCW 84.36.042;

.. Property of nonprofit organizations providing emergency or transitional housing for low-income homeless persons or victims of domestic violence who are homeless for personal safety reasons that is exempt from property taxes under RCW 84.36.043;

.. Property of the state housing finance commission that is exempt from property taxes under RCW 84.36.135; and

.. Property of nonprofit corporations operating sheltered workshops for persons with disabilities that is exempt from property taxes under RCW 84.36.350.

. A benefit charge may apply to a tax-exempt property included in subsection (2)(b) of this section if the tax-exempt property is located in a fire protection district that:

.. Is less than four square miles in size;

.. Has approved a benefit charge prior to May 5, 2017; and

.. Has a population exceeding nineteen thousand people as of May 5, 2017, as determined by the office of financial management.

. A limited benefit charge may apply to property or improvements owned by a Christmas tree grower as defined in RCW 15.13.250(4) so long as the property or improvement is located on land that has been approved as farm and agricultural land with standing crops under chapter 84.34 RCW. For such property or improvement, a benefit charge may not exceed the reduction in property tax that results from the imposition of a benefit charge, as required under RCW 52.18.065.

. The aggregate amount of such benefit charges in any one year shall not exceed an amount equal to sixty percent of the operating budget for the year in which the benefit charge is to be collected: PROVIDED, That it shall be the duty of the county legislative authority or authorities of the county or counties in which the fire protection district is located to make any necessary adjustments to assure compliance with such limitation and to immediately notify the board of fire commissioners of any changes thereof.

. A benefit charge imposed shall be reasonably proportioned to the measurable benefits to property resulting from the services afforded by the district. It is acceptable to apportion the benefit charge to the values of the properties as found by the county assessor or assessors modified generally in the proportion that fire insurance rates are reduced or entitled to be reduced as the result of providing the services. Any other method that reasonably apportions the benefit charges to the actual benefits resulting from the degree of protection, which may include but is not limited to the distance from regularly maintained fire protection equipment, the level of fire prevention services provided to the properties, or the need of the properties for specialized services, may be specified in the resolution and shall be subject to contest on the ground of unreasonable or capricious action or action in excess of the measurable benefits to the property resulting from services afforded by the district. The board of fire commissioners may determine that certain properties or types or classes of properties are not receiving measurable benefits based on criteria they establish by resolution. A benefit charge authorized by this chapter shall not be applicable to the personal property or improvements to real property of any individual, corporation, partnership, firm, organization, or association maintaining a fire department and whose fire protection and training system has been accepted by a fire insurance underwriter maintaining a fire protection engineering and inspection service authorized by the state insurance commissioner to do business in this state, but such property may be protected by the fire protection district under a contractual agreement.

. For administrative purposes, the benefit charge imposed on any individual property may be compiled into a single charge, provided that the district, upon request of the property owner, provide an itemized list of charges for each measurable benefit included in the charge.

. [Empty]
.. At the annual review of the fire benefit charge mandated by RCW 52.18.060(2), if a fire service agency has identified:

... A tax-exempt property under subsection (2)(b) of this section as having a substantial increase in requested emergency services over the previous year; or

... A new tax-exempt property that is similar in size, population, and geographic location as another such tax-exempt property as having an increase in requested emergency services;

then the tax-exempt property and the fire service agency must work together, in good faith, to address the problem by implementing community risk reduction efforts. The community risk reduction plan may include but is not limited to wellness programs and community action plans.

.. At the subsequent annual review, if the heightened service requirements have not been reasonably addressed by the joint mitigation efforts, and the tax-exempt property owner has not acted in good faith:

... The property is subject to assessment of the fire benefit charge in the subsequent year, subject to approval by the board of fire commissioners as outlined in RCW 52.18.060(2); or

... The respective tax-exempt property shall pay the fire service agency a fire protection charge payment in lieu of a benefit charge. The fire protection charge shall be an amount equivalent to the benefit rates for similarly situated properties for that year.

.. All tax-exempt properties identified under subsection (2)(b) of this section and all local fire service agencies are encouraged to work collaboratively to develop and implement programs to address proper usage of fire service resources for residents of the housing properties.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1467-S.SL.pdf?cite=2017%20c%20196%20§%205[2017 c 196 § 5]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6285-S.SL.pdf?cite=1998%20c%2016%20§%201[1998 c 16 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c294.pdf?cite=1990%20c%20294%20§%201[1990 c 294 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c63.pdf?cite=1989%20c%2063%20§%2028[1989 c 63 § 28]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c325.pdf?cite=1987%20c%20325%20§%201[1987 c 325 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%20122[1985 c 7 § 122]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c126.pdf?cite=1974%20ex.s.%20c%20126%20§%201[1974 ex.s. c 126 § 1]; ]

== 52.18.020 - Personal property, improvements to real property—Defined.
The term "personal property" for the purposes of this chapter shall include every form of tangible personal property, including but not limited to, all goods, chattels, stock in trade, estates, or crops: PROVIDED, That all personal property not assessed and subjected to ad valorem taxation under Title 84 RCW, all property under contract or for which the district is receiving payment for as authorized by RCW 52.30.020 and all property subject to the provisions of chapter 54.28 RCW, or all property that is subject to a contract for services with a fire protection district, shall be exempt from the benefit charge imposed under this chapter: PROVIDED FURTHER, That the term "personal property" shall not include any personal property used for farming, field crops, farm equipment or livestock: AND PROVIDED FURTHER, That the term "improvements to real property" shall not include permanent growing crops, field improvements installed for the purpose of aiding the growth of permanent crops, or other field improvements normally not subject to damage by fire.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c294.pdf?cite=1990%20c%20294%20§%202[1990 c 294 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c325.pdf?cite=1987%20c%20325%20§%202[1987 c 325 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%20123[1985 c 7 § 123]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c126.pdf?cite=1974%20ex.s.%20c%20126%20§%202[1974 ex.s. c 126 § 2]; ]

== 52.18.030 - Resolution establishing benefit charges—Contents—Listing—Collection.
The resolution establishing benefit charges as specified in RCW 52.18.010 shall specify, by legal geographical areas or other specific designations, the charge to apply to each property by location, type, or other designation, or other information that is necessary to the proper computation of the benefit charge to be charged to each property owner subject to the resolution. The county assessor of each county in which the district is located shall determine and identify the personal properties and improvements to real property which are subject to a benefit charge in each fire protection district and shall furnish and deliver to the county treasurer of that county a listing of the properties with information describing the location, legal description, and address of the person to whom the statement of benefit charges is to be mailed, the name of the owner, and the value of the property and improvements, together with the benefit charge to apply to each. These benefit charges shall be certified to the county treasurer for collection in the same manner that is used for the collection of fire protection charges for forestlands protected by the department of natural resources under RCW 76.04.610 and the same penalties and provisions for collection shall apply.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c294.pdf?cite=1990%20c%20294%20§%203[1990 c 294 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c63.pdf?cite=1989%20c%2063%20§%2029[1989 c 63 § 29]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c325.pdf?cite=1987%20c%20325%20§%203[1987 c 325 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c100.pdf?cite=1986%20c%20100%20§%2053[1986 c 100 § 53]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c126.pdf?cite=1974%20ex.s.%20c%20126%20§%203[1974 ex.s. c 126 § 3]; ]

== 52.18.040 - Reimbursement of county for administration and collection expenses.
Each fire protection district shall contract, prior to the imposition of a benefit charge, for the administration and collection of the benefit charge by each county treasurer, who shall deduct a percent, as provided by contract to reimburse the county for expenses incurred by the county assessor and county treasurer in the administration of the resolution and this chapter. The county treasurer shall make distributions each year, as the charges are collected, in the amount of the benefit charges imposed on behalf of each district, less the deduction provided for in the contract.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c294.pdf?cite=1990%20c%20294%20§%204[1990 c 294 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c63.pdf?cite=1989%20c%2063%20§%2030[1989 c 63 § 30]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c325.pdf?cite=1987%20c%20325%20§%204[1987 c 325 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c126.pdf?cite=1974%20ex.s.%20c%20126%20§%204[1974 ex.s. c 126 § 4]; ]

== 52.18.050 - Voter approval of benefit charges required—Election—Ballot.
. [Empty]
.. The initial imposition of a benefit charge authorized by this chapter must be approved by not less than sixty percent of the voters of the district voting at a general election or at a special election called by the district for that purpose.

.. An election held for the initial imposition of a benefit charge must be held not more than twelve months prior to the date on which the first charge is to be assessed.

.. A benefit charge approved at an election expires in six or fewer years as authorized by the voters unless subsequently reapproved by the voters.

. Ballot measures calling for the initial imposition of a benefit charge must be submitted so as to enable voters favoring the authorization of a benefit charge to vote "Yes" and those opposed to vote "No," and the ballot question must be as follows:

"Shall . . . . . . county fire protection district No. . . . . be authorized to impose benefit charges each year for . . . . (insert number of years not to exceed six) years, not to exceed an amount equal to sixty percent of its operating budget, and be prohibited from imposing an additional property tax under RCW 52.16.160?

YESNO□□"

YES

NO

□

□"

. [Empty]
.. The continued imposition of a benefit charge authorized by this chapter may be approved for six consecutive years, ten consecutive years, or permanently.

A ballot measure calling for the continued imposition of a benefit charge for six consecutive years or ten consecutive years must be approved by a majority of the voters of the district voting at a general election or at a special election called by the district for that purpose.

A ballot measure calling for the continued imposition of a benefit charge as a permanent benefit charge must be approved by not less than sixty percent of the voters of the district voting at a general election or at a special election called by the district for that purpose.

.. Ballot measures calling for the continued imposition of a benefit charge must be submitted so as to enable voters favoring the continued imposition of the benefit charge to vote "Yes" and those opposed to vote "No." The ballot question must be substantially in the following form:

"Shall . . . . . . county fire protection district No. . . . . be authorized to continue voter-authorized benefit charges. . . . . (insert "each year for six consecutive years," "each year for ten consecutive years," or "permanently"), not to exceed an amount equal to sixty percent of its operating budget, and be prohibited from imposing an additional property tax under RCW 52.16.160?

YESNO□□"

YES

NO

□

□"

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6415-S.SL.pdf?cite=2020%20c%2099%20§%201[2020 c 99 § 1]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1467-S.SL.pdf?cite=2017%20c%20196%20§%204[2017 c 196 § 4]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5332-S.SL.pdf?cite=2013%20c%2049%20§%201[2013 c 49 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6285-S.SL.pdf?cite=1998%20c%2016%20§%202[1998 c 16 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c294.pdf?cite=1990%20c%20294%20§%205[1990 c 294 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c27.pdf?cite=1989%20c%2027%20§%201[1989 c 27 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c325.pdf?cite=1987%20c%20325%20§%205[1987 c 325 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c126.pdf?cite=1974%20ex.s.%20c%20126%20§%205[1974 ex.s. c 126 § 5]; ]

== 52.18.060 - Public hearing—Required—Report—Benefit charge resolution to be filed—Notification to property owners.
. Not less than ten days nor more than six months before the election at which the proposition to impose the benefit charge is submitted as provided in this chapter, the board of fire commissioners of the district shall hold a public hearing specifically setting forth its proposal to impose benefit charges for the support of its legally authorized activities which will maintain or improve the services afforded in the district. A report of the public hearing shall be filed with the county treasurer of each county in which the property is located and be available for public inspection.

. Prior to November 15 of each year the board of fire commissioners shall hold a public hearing to review and establish the fire district benefit charges for the subsequent year.

All resolutions imposing or changing the benefit charges shall be filed with the county treasurer or treasurers of each county in which the property is located, together with the record of each public hearing, before November 30 immediately preceding the year in which the benefit charges are to be collected on behalf of the district.

After the benefit charges have been established, the owners of the property subject to the charge shall be notified of the amount of the charge.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c294.pdf?cite=1990%20c%20294%20§%206[1990 c 294 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c63.pdf?cite=1989%20c%2063%20§%2031[1989 c 63 § 31]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c325.pdf?cite=1987%20c%20325%20§%206[1987 c 325 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c126.pdf?cite=1974%20ex.s.%20c%20126%20§%206[1974 ex.s. c 126 § 6]; ]

== 52.18.065 - Property tax limited if benefit charge imposed.
A fire protection district that imposes a benefit charge under this chapter shall not impose all or part of the property tax authorized under RCW 52.16.160.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c294.pdf?cite=1990%20c%20294%20§%207[1990 c 294 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c325.pdf?cite=1987%20c%20325%20§%209[1987 c 325 § 9]; ]

== 52.18.070 - Review board.
After notice has been given to the property owners of the amount of the charge, the board of fire commissioners of a fire protection district imposing a benefit charge under this chapter shall form a review board for at least a two-week period and shall, upon complaint in writing of a party aggrieved owning property in the district, reduce the charge of a person who, in their opinion, has been charged too large a sum, to a sum or amount as they believe to be the true, fair, and just amount.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c294.pdf?cite=1990%20c%20294%20§%208[1990 c 294 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c325.pdf?cite=1987%20c%20325%20§%207[1987 c 325 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c126.pdf?cite=1974%20ex.s.%20c%20126%20§%207[1974 ex.s. c 126 § 7]; ]

== 52.18.080 - Model resolution.
The Washington fire commissioners association, as soon as practicable, shall draft a model resolution to impose the fire protection district benefit charge authorized by this chapter and may provide assistance to fire protection districts in the establishment of a program to develop benefit charges.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c294.pdf?cite=1990%20c%20294%20§%209[1990 c 294 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c325.pdf?cite=1987%20c%20325%20§%208[1987 c 325 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c126.pdf?cite=1974%20ex.s.%20c%20126%20§%208[1974 ex.s. c 126 § 8]; ]

== 52.18.090 - Exemptions.
A person who is receiving the exemption contained in RCW 84.36.381 through 84.36.389 shall be exempt from any legal obligation to pay a portion of the charge imposed by this chapter according to the following.

. A person who meets the income limitation contained in RCW 84.36.381(5)(a) and does not meet the income limitation contained in RCW 84.36.381(5)(b) (i) or (ii) shall be exempt from twenty-five percent of the charge.

. A person who meets the income limitation contained in RCW 84.36.381(5)(b)(i) shall be exempt from fifty percent of the charge.

. A person who meets the income limitation contained in RCW 84.36.381(5)(b)(ii) shall be exempt from seventy-five percent of the charge.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c294.pdf?cite=1990%20c%20294%20§%2010[1990 c 294 § 10]; ]

