= 52.22 - Special proceedings.
:toc:

== 52.22.011 - Legislative validation.
The respective areas, organized and established or attempted to be organized and established under the authority granted in Title 52 RCW which since their organization and establishment or attempted organization and establishment have continuously maintained their organization as fire protection districts established under the authority of these statutes are declared to be properly organized fire protection districts existing under and by virtue of the statutes having in each case, the boundaries set forth in the respective organization proceedings of each of them as shown by the files and records in the offices of the legislative authority or authorities and auditor or auditors of the county or counties in which the particular area lies.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c63.pdf?cite=1989%20c%2063%20§%2033[1989 c 63 § 33]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c230.pdf?cite=1984%20c%20230%20§%2066[1984 c 230 § 66]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c230.pdf?cite=1947%20c%20230%20§%201[1947 c 230 § 1]; Rem. Supp. 1947 § 5654-151o; ]

== 52.22.021 - Special proceedings for judicial confirmation of organization, bonds, warrants, contracts, etc.
The board of fire commissioners of a fire protection district now existing or which may be organized under the laws of this state may commence a special proceeding in the superior court of the state of Washington. These proceedings for the organization of the fire district, for the formation of any local improvement district therein, or proceedings for the authorization, issuance, and sale of coupon or registered warrants or general obligation bonds issued pursuant to RCW 52.16.061, either of the fire district or for a local improvement district therein, or both, whether the bonds or coupon or registered warrants have been sold, or proceedings for any contract of the district involving the fire district or any local improvement district therein, and any other proceedings that may affect the legality of the proceedings concerned or any or all of the proceedings above outlined, may be judicially examined, approved, and confirmed.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c230.pdf?cite=1984%20c%20230%20§%2067[1984 c 230 § 67]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c167.pdf?cite=1983%20c%20167%20§%20130[1983 c 167 § 130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c255.pdf?cite=1947%20c%20255%20§%201[1947 c 255 § 1]; Rem. Supp. 1947 § 5654-153a; ]

== 52.22.031 - Petition.
The board of fire commissioners of the fire protection district shall file in the superior court of the county in which the fire protection district was organized, a petition requesting in effect that the proceedings be examined, approved, and confirmed by the court. The petition shall state the facts showing any of the proceedings that the petition asks the court to examine, approve, and confirm, but need allege only generally that the fire protection district was properly organized and that the first board of fire commissioners was properly elected.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c230.pdf?cite=1984%20c%20230%20§%2068[1984 c 230 § 68]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c255.pdf?cite=1947%20c%20255%20§%202[1947 c 255 § 2]; Rem. Supp. 1947 § 5654-153b; ]

== 52.22.041 - Hearing date to be fixed—Notice.
The court shall fix the time for the hearing of the petition and direct the clerk of the court to give notice of the filing of the petition and of the time and place fixed for the hearing. The notice shall state the time and place of the hearing of the petition and that any person interested in the proceedings sought by the petition to be examined, approved, and confirmed by the court, may on or before the date of the hearing of the petition, answer the petition. The petition may be referred to and described in the notice as the petition of the board of fire commissioners of . . . . . . county fire protection district No. . . . . . . . . . (giving the county and its number or any other name by which it is officially designated), requesting that the proceedings (naming them as set out in the request of the petition), be examined, approved, and confirmed by the court, and shall be signed by the clerk.

The notice shall be given by posting and publishing for the same length of time that the notice of the hearing on the petition before the county legislative body to form the district was required by law to be posted and published, and it may be published in any legal newspaper designated in the order of the court fixing the time and place of the hearing of the petition and directing the clerk of the court to give notice thereof.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c230.pdf?cite=1984%20c%20230%20§%2069[1984 c 230 § 69]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c255.pdf?cite=1947%20c%20255%20§%203[1947 c 255 § 3]; Rem. Supp. 1947 § 5654-153c; ]

== 52.22.051 - Answer of petition.
A person interested in the fire protection district, or in a local improvement district therein, involved in the petition or in any proceedings sought by the petition to be examined, approved, and confirmed by the court, may answer the petition. The statutes of this state respecting answers to verified complaints are applicable to answers to the petition. The person so answering the petition shall be the defendant in the special proceeding, and the board of fire commissioners shall be the plaintiff. Every material statement of the petition not specifically controverted by the answer must, for purposes of the special proceedings, be taken as true, and each person failing to answer the petition is deemed to admit as true all the material statements of the petition.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c230.pdf?cite=1984%20c%20230%20§%2070[1984 c 230 § 70]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c255.pdf?cite=1947%20c%20255%20§%204[1947 c 255 § 4]; Rem. Supp. 1947 § 5654-153d; ]

== 52.22.061 - Pleading and practice—Motion for new trial.
The rules of pleading and practice governing civil actions are applicable to the special proceedings provided for except where inconsistent with this chapter. A motion for a new trial must be made upon the minutes of the court and in case of an order granting a new trial, the order must specify the issue to be reexamined at the new trial. The findings of the court on the other issues shall not be affected by the order granting a new trial.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c230.pdf?cite=1984%20c%20230%20§%2071[1984 c 230 § 71]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c255.pdf?cite=1947%20c%20255%20§%205[1947 c 255 § 5]; Rem. Supp. 1947 § 5654-153e; ]

== 52.22.071 - Jurisdiction of court.
At the hearing of the special proceedings, the court has power and jurisdiction to examine and determine the legality and validity of, and to approve and confirm, each and all of the proceedings for the organization of the fire protection district and for the formation of any local improvement district therein under the law relating to such districts from and including the petition for the organization of the fire district and for the formation of any local improvement district therein and all other proceedings which affect the legality of the districts, or the validity and legality of any coupon or registered warrants or bonds either of the fire district or for a local improvement district therein and all proceedings conducted by the fire district for a contract of the district involving the fire district or a local improvement district therein, and any other proceeding which may affect the legality of the proceedings concerned.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c230.pdf?cite=1984%20c%20230%20§%2072[1984 c 230 § 72]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c167.pdf?cite=1983%20c%20167%20§%20131[1983 c 167 § 131]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c255.pdf?cite=1947%20c%20255%20§%206[1947 c 255 § 6]; Rem. Supp. 1947 § 5654-153f; ]

== 52.22.081 - Minor irregularities to be disregarded.
The court has full authority and jurisdiction to consider any question of laches, estoppel, and other infirmities in the position and claims of the defendants, to question the legality of the proceedings sought by the plaintiff to be confirmed by the court, and to pass upon and determine them. The court, in inquiring into the regularity, legality, and correctness of the proceedings sought by the board of fire commissioners in its petition to be examined, approved, and confirmed by the court, must disregard any error, irregularity, or omission which does not affect the substantial rights of the parties to the special proceedings. The court may approve and confirm the proceedings in part, and disapprove and declare illegal or invalid other or subsequent parts of the proceedings, or it may approve and confirm all of the proceedings, and make and enter its decree accordingly.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c230.pdf?cite=1984%20c%20230%20§%2073[1984 c 230 § 73]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c255.pdf?cite=1947%20c%20255%20§%207[1947 c 255 § 7]; Rem. Supp. 1947 § 5654-153g; ]

== 52.22.091 - Costs.
The court shall find and determine, in these special proceedings, whether the notice of the filing of the petition and of the time and place of hearing on the petition has been properly posted and published for the time and in the manner prescribed in this chapter. The costs of the special proceedings may be allowed and apportioned between all the parties, in the court's discretion.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c230.pdf?cite=1984%20c%20230%20§%2074[1984 c 230 § 74]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c255.pdf?cite=1947%20c%20255%20§%208[1947 c 255 § 8]; Rem. Supp. 1947 § 5654-153h; ]

== 52.22.101 - Appellate review.
Appellate review of an order granting or refusing a new trial, or from the judgment, in the special proceedings must be taken by the party aggrieved within thirty days after the entry of the order or the judgment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c202.pdf?cite=1988%20c%20202%20§%2050[1988 c 202 § 50]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c230.pdf?cite=1984%20c%20230%20§%2075[1984 c 230 § 75]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c255.pdf?cite=1947%20c%20255%20§%209[1947 c 255 § 9]; Rem. Supp. 1947 § 5654-153i; ]

== 52.22.111 - Districts governed by Title 52 RCW.
All fire protection districts are governed by Title 52 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c230.pdf?cite=1984%20c%20230%20§%2086[1984 c 230 § 86]; ]

