= 52.33 - Fire departments—Performance measures.
:toc:

== 52.33.010 - Intent.
The legislature intends for fire protection districts and regional fire [protection] service authorities to set standards for addressing the reporting and accountability of substantially career fire departments, and to specify performance measures applicable to response time objectives for certain major services. The legislature acknowledges the efforts of the international city/county management association, the international association of fire chiefs, and the national fire protection association for the organization and deployment of resources for fire departments. The arrival of first responders with automatic external defibrillator capability before the onset of brain death, and the arrival of adequate fire suppression resources before flash-over is a critical event during the mitigation of an emergency, and is in the public's best interest. For these reasons, this chapter contains performance measures, comparable to that research, relating to the organization and deployment of fire suppression operations, emergency medical operations, and special operations by substantially career fire departments. This chapter does not, and is not intended to, in any way modify or limit the authority of fire protection districts and regional fire protection service authorities to set levels of service.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1756-S.SL.pdf?cite=2005%20c%20376%20§%20301[2005 c 376 § 301]; ]

== 52.33.020 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Advanced life support" means functional provision of advanced airway management, including intubation, advanced cardiac monitoring, manual defibrillation, establishment and maintenance of intravenous access, and drug therapy.

. "Aircraft rescue and firefighting" means the firefighting actions taken to rescue persons and to control or extinguish fire involving or adjacent to aircraft on the ground.

. "Brain death" as defined by the American heart association means the irreversible death of brain cells that begins four to six minutes after cardiac arrest.

. "Fire department" means a fire protection district or a regional fire protection service authority responsible for firefighting actions, emergency medical services, and other special operations in a specified geographic area. The department must be a substantially career fire department, and not a substantially volunteer fire department.

. "Fire suppression" means the activities involved in controlling and extinguishing fires.

. "First responder" means provision of initial assessment and basic first-aid intervention, including cardiac pulmonary resuscitation and automatic external defibrillator capability.

. "Flash-over" as defined by national institute of standards and technology means when all combustibles in a room burst into flame and the fire spreads rapidly.

. "Marine rescue and firefighting" means the firefighting actions taken to prevent, control, or extinguish fire involved in or adjacent to a marine vessel and the rescue actions for occupants using normal and emergency routes for egress.

. "Response time" means the time immediately following the turnout time that begins when units are en route to the emergency incident and ends when units arrive at the scene.

. "Special operations" means those emergency incidents to which the fire department responds that require specific and advanced training and specialized tools and equipment.

. "Turnout time" means the time beginning when units receive notification of the emergency to the beginning point of response time.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1756-S.SL.pdf?cite=2005%20c%20376%20§%20302[2005 c 376 § 302]; ]

== 52.33.030 - Policy statement—Service delivery objectives.
. Every fire protection district and regional fire protection service authority shall maintain a written statement or policy that establishes the following:

.. The existence of a fire department;

.. Services that the fire department is required to provide;

.. The basic organizational structure of the fire department;

.. The expected number of fire department employees; and

.. Functions that fire department employees are expected to perform.

. Every fire protection district and regional fire protection service authority shall include service delivery objectives in the written statement or policy required under subsection (1) of this section. These objectives shall include specific response time objectives for the following major service components, if appropriate:

.. Fire suppression;

.. Emergency medical services;

.. Special operations;

.. Aircraft rescue and firefighting;

.. Marine rescue and firefighting; and

.. Wildland firefighting.

. Every fire protection district and regional fire protection service authority, in order to measure the ability to arrive and begin mitigation operations before the critical events of brain death or flash-over, shall establish time objectives for the following measurements:

.. Turnout time;

.. Response time for the arrival of the first arriving engine company at a fire suppression incident and response time for the deployment of a full first alarm assignment at a fire suppression incident;

.. Response time for the arrival of a unit with first responder or higher level capability at an emergency medical incident; and

.. Response time for the arrival of an advanced life support unit at an emergency medical incident, where this service is provided by the fire department.

. Every fire protection district and regional fire protection service authority shall also establish a performance objective of not less than ninety percent for the achievement of each response time objective established under subsection (3) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1756-S.SL.pdf?cite=2005%20c%20376%20§%20303[2005 c 376 § 303]; ]

== 52.33.040 - Annual evaluations—Annual report.
. Every fire protection district and regional fire protection service authority shall evaluate its level of service and deployment delivery and response time objectives on an annual basis. The evaluations shall be based on data relating to level of service, deployment, and the achievement of each response time objective in each geographic area within the jurisdiction of the fire protection district and regional fire protection service authority.

. Beginning in 2007, every fire protection district and regional fire protection service authority shall issue an annual written report which shall be based on the annual evaluations required by subsection (1) of this section.

.. The annual report shall define the geographic areas and circumstances in which the requirements of this standard are not being met.

.. The annual report shall explain the predictable consequences of any deficiencies and address the steps that are necessary to achieve compliance.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1756-S.SL.pdf?cite=2005%20c%20376%20§%20304[2005 c 376 § 304]; ]

