= 71A.26 - Client rights.
:toc:

== 71A.26.010 - Minimum rights.
The rights set forth in this chapter are the minimal rights guaranteed to all clients of the administration, and are not intended to diminish rights set forth in other state or federal laws that may contain additional rights.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1651-S2.SL.pdf?cite=2020%20c%20271%20§%201[2020 c 271 § 1]; ]

== 71A.26.020 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Administration" means the division of the department responsible for providing services to eligible persons, but does not include the division of the department responsible for the licensing and certification of services and facilities for eligible persons.

. "Assessment" has the same meaning as defined in RCW 71A.10.020.

. "Client" means a person who has a developmental disability as defined in RCW 71A.10.020 and has been determined to be eligible to receive services under chapter  71A.16 RCW.

. "Department" means the department of social and health services.

. "Developmental disabilities ombuds" means the office created under chapter 43.382 RCW.

. "Eligible person" has the same meaning as defined in RCW 71A.10.020.

. "Legal representative" means a parent of a client under age eighteen, a court-appointed guardian or limited guardian under Title 11 RCW if the subject matter is within the scope of the guardianship order, or any other person authorized by law to act for the client.

. "Necessary supplemental accommodation representative" means an individual who receives copies of administration correspondence in order to help a client or eligible person understand the documents and exercise the client or eligible person's rights. The necessary supplemental accommodation representative is identified by the client or eligible person when the client or eligible person does not have a legal guardian and is requesting or receiving services from the administration.

. "Provider" means an individual, a facility, or an agency that is one or more of the following: Licensed, certified, contracted by the department, or state operated to provide services to administration clients.

. "Restraint" includes:

.. Physical restraint, which is a manual method, obstacle, or physical or mechanical device, material, or equipment attached or adjacent to the client's body that restricts freedom of movement or access to the client's body, is used for discipline or convenience, and is not required to treat the client's medical symptoms; and

.. Chemical restraint, which is a psychopharmacologic drug that is used for discipline or convenience and is not required to treat the client's medical symptoms.

. "Restriction" means a limitation on the client's use or enjoyment of property, social activities, or engagement in the community.

. "Service plan" means any plan required by the department to deliver the services authorized by the administration to the client.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1651-S2.SL.pdf?cite=2020%20c%20271%20§%202[2020 c 271 § 2]; ]

== 71A.26.030 - Client rights—Notification.
. The administration must notify the individual and the individual's legal representative or necessary supplemental accommodation representative of the rights set forth in this chapter upon determining the individual is an eligible person. The notification the administration provides must be in written form. The administration must document the date that the notification required in this subsection was provided.

. The administration must notify a client and a client's legal representative or necessary supplemental accommodation representative of the rights set forth in this chapter upon conducting a client's assessment. The notification the administration provides must be in written form. The administration must document the date that the notification required in this subsection was provided.

. The client has the right to exercise autonomy and choice free from provider interference. This includes the client's rights to:

.. Be free from sexual, physical, and mental abuse, corporal punishment, and involuntary seclusion;

.. Be free from discrimination based on race, color, creed, national origin, religion, sex, age, disability, marital and family status, gender identity, or sexual orientation;

.. Make choices regarding the type of food available within the client's resources and service plan;

.. Have visitors at the client's home and associate with persons of the client's choosing and subject to limitations as negotiated with the client's housemates;

.. Control the client's schedule and choose activities, schedules, and health care that meet the client's needs;

.. Information about the treatment ordered by the client's health care provider and help plan how the treatment will be implemented;

.. Be free from unnecessary medication, restraints, and restrictions;

.. Vote, participate in the democratic process, and help people with getting elected to office;

.. Manage the client's money or choose a person to assist;

.. Be part of the community;

.. Make choices about the client's life;

.. Choose the clothes and hairstyle the client wears;

.. Furnish and decorate the client's bedroom to the client's preferences or furnish and decorate the client's home to the client's preferences subject to agreement with the client's housemates;

.. Seek paid employment;

.. Receive the services that the client agrees to receive;

.. Decide whether or not to participate in research after the research has been explained to the client, and after the client or the client's legal representative gives written consent for the client to participate in the research; and

.. Be free from financial exploitation.

. The client has the right to participate in the administration's service planning. This includes the client's right to:

.. Be present and provide input on the client's service plans written by the administration and providers;

.. Have meaningful opportunities to lead planning processes;

.. Have the client's visions for a meaningful life and the client's goals for education, employment, housing, relationships, and recreation included in the planning process;

.. Choose an advocate to attend the planning processes with the client; and

.. Have access to current and accurate information about recreation, education, and employment opportunities available in the client's community.

. The client has the right to access information about services and health care. This includes the client's right to:

.. View a copy of all of the client's service plans;

.. Possess full copies of the client's current service plans;

.. Review copies of the policies and procedures for any service the client receives, at any time. This includes policies and procedures about how the client may file a complaint to providers and the department;

.. Examine the results of the department's most recent survey or inspection conducted by state surveyors or inspectors, statements of deficiency, and plans of correction in effect with respect to the client's provider and the client's residence. The client's service provider must assist the client with locating and accessing this information upon the client's request; and

.. Receive written notification of enforcement actions taken by the department against the client's provider. The administration's case manager or designee must provide notification to the client and the client's legal representative or necessary supplemental accommodation representative within twenty days, excluding weekends and holidays, of the date of enforcement. For purposes of this subsection, a "provider" means an entity that provides residential services received by a client that is operated by or contracted through the administration. An enforcement action that requires this notification includes:

... Conditions placed on the provider certification or license;

... Suspension or limited suspension of referrals or admissions;

... Imposition of provisional certification or decertification; or

... Denial, suspension, or revocation of a license or certification.

. The client has the right to file complaints and grievances, and to request appeals. This includes the client's right to:

.. Appeal any decision by the department that denies, reduces, or terminates the client's eligibility, services, or choice of provider as defined in federal medicaid law and state public assistance laws;

.. Submit grievances to the client's provider about the client's services or other concerns. This includes, but is not limited to, concerns about the behavior of other people where the client lives. The provider must maintain a written policy on the grievance process that includes timelines and possible remedies. If a grievance is unresolved, the provider must provide the client with information on how to submit the grievance to the department;

.. File complaints and grievances, and request appeals without penalty or retaliation by the department or providers; and

.. Receive information about how to obtain accommodation for disability in the appeal process.

. The client has the right to privacy and confidentiality. This includes the client's right to:

.. Personal privacy and confidentiality of the client's personal records;

.. Communicate privately, including the right to send and receive mail and email, and the right to use a telephone in an area where calls can be made without being overheard; and

.. Meet with and talk privately with the client's friends and family.

. The client has rights during discharge, transfer, and termination of services as set forth in this subsection.

.. Clients that are residents of a long-term care facility that is licensed under chapter 18.20, 72.36, or  70.128 RCW have the rights set forth in RCW 70.129.110.

.. Clients that receive certified community residential services have the right to:

... Remain with the client's provider. Services must not be terminated unless the provider determines and documents that:

(A) The provider cannot meet the needs of the client;

(B) The client's safety or the safety of other individuals in the facility or residence is endangered;

(C) The client's health or the health of other individuals in the facility or residence would otherwise be endangered; or

(D) The provider ceases to operate.

... Receive written notice from the provider of any potential termination of services at least thirty days before such termination, except when there is a health and safety emergency that requires termination of service, in which case notice shall be provided at least seventy-two hours before the date of termination. The notice must be provided to the client and the client's legal representative or necessary supplemental accommodation representative. The notice must include:

(A) The reason for termination of services; and

(B) The effective date of termination of services.

... Receive a transition plan at least two days before the effective date of the termination of services, or if the termination was based on a health and safety emergency receive a transition plan within two days of the administration's receipt of notice for emergency termination. The administration must provide the client and the client's legal representative or necessary supplemental accommodation representative with the plan. The plan must include:

(A) The location where the client will be transferred;

(B) The mode of transportation to the new location; and

(C) The name, address, and telephone number of the developmental disabilities ombuds.

.. A provider that provides services to clients in a residence owned by the provider must exhaust the procedures for termination of services prior to the commencement of any unlawful detainer action under RCW 59.12.030.

. The client has the right to access advocates. The client has the right to receive information from agencies acting as client advocates, and be afforded the opportunity to contact these agencies. The provider must not interfere with the client's access to any of the following:

.. Any representative of the state;

.. The resident's individual physician;

.. The developmental disabilities ombuds; or

.. Any representative of the organization designated to implement the protection and advocacy program pursuant to RCW 71A.10.080.

. If a client is subject to a guardianship order pursuant to *chapter 11.88 RCW, the rights of the client under this chapter are exercised by the client's guardian if the subject matter is within the scope of the guardianship order.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1651-S2.SL.pdf?cite=2020%20c%20271%20§%203[2020 c 271 § 3]; ]

== 71A.26.040 - Rules.
The department shall adopt rules as necessary to inform clients and providers of the client rights set forth in this chapter. The department shall adopt rules as necessary to provide oversight and enforcement of provider practices relating to these rights for providers licensed or certified by the department.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1651-S2.SL.pdf?cite=2020%20c%20271%20§%204[2020 c 271 § 4]; ]

== 71A.26.050 - Private right of action.
Nothing in this chapter limits an existing private right of action against the department, the administration, or the state of Washington. Nothing in this chapter creates a private right of action against the department, the administration, or the state of Washington.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1651-S2.SL.pdf?cite=2020%20c%20271%20§%205[2020 c 271 § 5]; ]

