= 71A.24 - Intensive behavior support services.
:toc:

== 71A.24.005 - Intent.
The legislature recognizes that the number of children who have developmental disabilities along with intense behaviors is increasing, and more families are seeking out-of-home placement for their children.

The legislature intends to create services and to develop supports for these children, family members, and others involved in the children's lives to avoid disruption to families and eliminate the need for out-of-home placement.

The legislature directs the department to maintain a federal waiver through which services may be provided to allow children with developmental disabilities and intense behaviors to maintain permanent and stable familial relationships. The legislature intends for these services to be locally based and offered as early as possible to avoid family disruption and out-of-home placement.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5117-S.SL.pdf?cite=2009%20c%20194%20§%201[2009 c 194 § 1]; ]

== 71A.24.010 - Role of department—Eligibility.
. To the extent funding is appropriated for this purpose, intensive behavior support services may be provided by the department, directly or by contract, to children who have developmental disabilities and intense behaviors and to their families.

. The department shall be the lead administrative agency for children's intensive behavior support services and shall:

.. Collaborate with appropriate parties to develop and implement the intensive in-home support services program within the division of developmental disabilities;

.. Use best practices and evidence-based practices;

.. Provide coordination and planning for the implementation and expansion of intensive in-home services;

.. Contract for the provision of intensive in-home and planned out-of-home services;

.. Monitor and evaluate services to determine whether the program meets standards identified in the service contracts;

.. Collect data regarding the number of families served, and costs and outcomes of the program;

.. Adopt appropriate rules to implement the program;

.. License out-of-home respite placements on a timely basis; and

.. Maintain an appropriate staff-to-client ratio.

. A child may receive intensive behavior support services when the department has determined that:

.. The child is under the age of twenty-one;

.. The child has a developmental disability and has been determined eligible for these services;

.. The child/family acuity scores are high enough in the assessment conducted by the division of developmental disabilities to indicate the child's behavior puts the child or family at significant risk or is very likely to require an out-of-home placement;

.. The child meets eligibility for the home and community-based care waiver;

.. The child resides in his or her family home or is temporarily in an out-of-home placement with a plan to return home;

.. The family agrees to participate in the program and complete the care and support steps outlined in the completed individual support plan; and

.. The family is not subject to an unresolved child protective services referral.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5117-S.SL.pdf?cite=2009%20c%20194%20§%202[2009 c 194 § 2]; ]

== 71A.24.020 - Intensive behavior support services—Core team.
. Intensive behavior support services under the program authorized in RCW 71A.24.010 shall be provided through a core team of highly trained individuals, either directly or by contract.

. The intensive behavior support services shall be designed to enhance the child's and parent's skills to manage behaviors, increase family and personal self-sufficiency, improve functioning of the family, reduce stress on children and families, and assist the family to locate and use other community services.

. The core team shall have the following characteristics and responsibilities:

.. Expertise in behavior management, therapies, and children's crisis intervention, or the ability to access such specialized expertise;

.. Ability to coordinate the array of services and supports needed to stabilize the family;

.. Ability to conduct transition planning as an individual and the individual's family leave the program; and

.. Ability to authorize and coordinate the services in the family's home and other environments, such as schools and neighborhoods.

. The following types of services constitute intensive behavior support services:

.. Behavior management and consultation;

.. Environmental adaptations;

.. Motor vehicle adaptations;

.. Therapy equipment and supplies;

.. Personal care;

.. Specialized diet goods and services;

.. In-home respite and planned out-of-home respite;

.. Intensive training to intervene effectively with the child for families and other individuals and partners working with the child in all domains, including the school and individualized education plan team; and

.. Coordination and planning.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5117-S.SL.pdf?cite=2009%20c%20194%20§%203[2009 c 194 § 3]; ]

