= 29A.04 - General provisions.
:toc:

== 29A.04.001 - Scope of definitions.
Words and phrases as defined in this chapter, wherever used in Title 29A RCW, shall have the meaning as in this chapter ascribed to them, unless where used the context thereof shall clearly indicate to the contrary or unless otherwise defined in the chapter of which they are a part.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20101[2003 c 111 § 101]; 1965 c 9 § 29.01.005. For like prior law see 1907 c 209 § 1, part; RRS § 5177, part; ]

== 29A.04.008 - Ballot and related terms.
As used in this title:

. "Ballot" means, as the context implies, either:

.. The issues and offices to be voted upon in a jurisdiction or portion of a jurisdiction at a particular primary, general election, or special election;

.. A facsimile of the contents of a particular ballot whether printed on a paper ballot or ballot card or as part of a voting machine or voting device;

.. A physical or electronic record of the choices of an individual voter in a particular primary, general election, or special election; or

.. The physical document on which the voter's choices are to be recorded;

. "Paper ballot" means a piece of paper on which the ballot for a particular election or primary has been printed, on which a voter may record his or her choices for any candidate or for or against any measure, and that is to be tabulated manually;

. "Ballot card" means any type of card or piece of paper of any size on which a voter may record his or her choices for any candidate and for or against any measure and that is to be tabulated on a vote tallying system;

. "Sample ballot" means a printed facsimile of all the issues and offices on the ballot in a jurisdiction and is intended to give voters notice of the issues, offices, and candidates that are to be voted on at a particular primary, general election, or special election;

. "Provisional ballot" means a ballot issued to a voter who would otherwise be denied an opportunity to vote a regular ballot, for any reason authorized by the Help America Vote Act, including but not limited to the following:

.. The voter's name does not appear in the list of registered voters for the county;

.. There is an indication in the voter registration system that the voter has already voted in that primary, special election, or general election, but the voter wishes to vote again;

.. There is a question on the part of the voter concerning the issues or candidates on which the voter is qualified to vote;

.. Any other reason allowed by law.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=2013%20c%2011%20§%201[2013 c 11 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5124-S.SL.pdf?cite=2011%20c%2010%20§%201[2011 c 10 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5408.SL.pdf?cite=2007%20c%2038%20§%201[2007 c 38 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5499-S.SL.pdf?cite=2005%20c%20243%20§%201[2005 c 243 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6453.SL.pdf?cite=2004%20c%20271%20§%20102[2004 c 271 § 102]; ]

== 29A.04.010 - By mail.
"By mail" means delivery of a completed original voter registration application by mail to a county auditor or the office of the secretary of state.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5227.SL.pdf?cite=2019%20c%20391%20§%202[2019 c 391 § 2]; ]

== 29A.04.013 - Canvassing.
"Canvassing" means the process of examining ballots or groups of ballots, subtotals, and cumulative totals in order to determine the official returns of a primary, special, or general election and includes the tabulation of any votes that were not previously tabulated.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=2013%20c%2011%20§%202[2013 c 11 § 2]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5124-S.SL.pdf?cite=2011%20c%2010%20§%202[2011 c 10 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20103[2003 c 111 § 103]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c59.pdf?cite=1990%20c%2059%20§%203[1990 c 59 § 3]; ]

== 29A.04.019 - Counting center.
"Counting center" means the facility or facilities designated by the county auditor to count and canvass ballots.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5124-S.SL.pdf?cite=2011%20c%2010%20§%203[2011 c 10 § 3]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20104[2003 c 111 § 104]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1593-S.SL.pdf?cite=1999%20c%20158%20§%201[1999 c 158 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c59.pdf?cite=1990%20c%2059%20§%204[1990 c 59 § 4]; ]

== 29A.04.025 - County auditor.
"County auditor" means the county auditor in a noncharter county or the officer, irrespective of title, having the overall responsibility to maintain voter registration and to conduct state and local elections in a charter county.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20105[2003 c 111 § 105]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c106.pdf?cite=1984%20c%20106%20§%201[1984 c 106 § 1]; ]

== 29A.04.031 - Date of mailing.
For registered voters voting by mail, "date of mailing" means the date of the postal cancellation on the envelope in which the ballot is returned to the election official by whom it was issued. For all service and overseas voters, "date of mailing" means the date stated by the voter on the declaration.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5124-S.SL.pdf?cite=2011%20c%2010%20§%204[2011 c 10 § 4]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20106[2003 c 111 § 106]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c346.pdf?cite=1987%20c%20346%20§%203[1987 c 346 § 3]; ]

== 29A.04.037 - Disabled voter.
"Disabled voter" means any registered voter who qualifies for special parking privileges under RCW 46.19.010, or who is defined as blind under RCW 74.18.020, or who qualifies to require assistance with voting under RCW 29A.40.160.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5124-S.SL.pdf?cite=2011%20c%2010%20§%205[2011 c 10 § 5]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201103[2010 c 161 § 1103]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20107[2003 c 111 § 107]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c346.pdf?cite=1987%20c%20346%20§%204[1987 c 346 § 4]; ]

== 29A.04.043 - Election.
"Election" when used alone means a general election except where the context indicates that a special election is included. "Election" when used without qualification does not include a primary.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20108[2003 c 111 § 108]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c59.pdf?cite=1990%20c%2059%20§%205[1990 c 59 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c9.pdf?cite=1965%20c%209%20§%2029.01.050[1965 c 9 § 29.01.050]; prior: 1907 c 209 § 1, part; RRS § 5177(c). See also  1950 ex.s. c 14 § 3; ]

== 29A.04.055 - Election officer.
"Election officer" includes any officer who has a duty to perform relating to elections under the provisions of any statute, charter, or ordinance.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20110[2003 c 111 § 110]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c9.pdf?cite=1965%20c%209%20§%2029.01.060[1965 c 9 § 29.01.060]; ]

== 29A.04.058 - Election official.
"Election official" when pertaining to voter registration includes any staff member of the office of the secretary of state or a staff member of the county auditor's office.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5227.SL.pdf?cite=2019%20c%20391%20§%201[2019 c 391 § 1]; ]

== 29A.04.061 - Elector. (Effective until January 1, 2022.)
"Elector" means any person who possesses all of the qualifications to vote under Article VI of the state Constitution.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20111[2003 c 111 § 111]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c346.pdf?cite=1987%20c%20346%20§%202[1987 c 346 § 2]; ]

== 29A.04.067 - Filing officer.
"Filing officer" means the county or state officer with whom declarations of candidacy for an office are required to be filed under this title.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20112[2003 c 111 § 112]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c59.pdf?cite=1990%20c%2059%20§%2077[1990 c 59 § 77]; ]

== 29A.04.070 - Future voter.
"Future voter" means a United States citizen and Washington state resident, age sixteen or seventeen, who wishes to provide information related to voter registration to the appropriate state agencies.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1513-S2.SL.pdf?cite=2018%20c%20109%20§%202[2018 c 109 § 2]; ]

== 29A.04.073 - General election.
"General election" means an election required to be held on a fixed date recurring at regular intervals.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20113[2003 c 111 § 113]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c9.pdf?cite=1965%20c%209%20§%2029.01.070[1965 c 9 § 29.01.070]; ]

== 29A.04.079 - Infamous crime.
An "infamous crime" is a crime punishable by death in the state penitentiary or imprisonment in a state or federal correctional facility. Neither an adjudication in juvenile court pursuant to chapter 13.40 RCW, nor a conviction for a misdemeanor or gross misdemeanor, is an "infamous crime."

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=2013%20c%2011%20§%203[2013 c 11 § 3]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=2009%20c%20369%20§%201[2009 c 369 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20114[2003 c 111 § 114]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2263-S.SL.pdf?cite=1992%20c%207%20§%2031[1992 c 7 § 31]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c9.pdf?cite=1965%20c%209%20§%2029.01.080[1965 c 9 § 29.01.080]; prior: Code 1881 § 3054; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1865%20p%2025%20§%205[1865 p 25 § 5]; RRS § 5113; ]

== 29A.04.086 - Major political party.
"Major political party" means a political party whose nominees for president and vice president received at least five percent of the total vote cast at the last presidential election. A political party qualifying as a major political party under this section retains such status until the next presidential election at which the presidential and vice presidential candidates of that party do not achieve at least five percent of the vote.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=2013%20c%2011%20§%204[2013 c 11 § 4]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6453.SL.pdf?cite=2004%20c%20271%20§%20103[2004 c 271 § 103]; ]

== 29A.04.091 - Measures.
"Measure" includes any proposition or question submitted to the voters.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20117[2003 c 111 § 117]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c9.pdf?cite=1965%20c%209%20§%2029.01.110[1965 c 9 § 29.01.110]; ]

== 29A.04.097 - Minor political party.
"Minor political party" means a political organization other than a major political party.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20116[2003 c 111 § 116]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c9.pdf?cite=1965%20c%209%20§%2029.01.100[1965 c 9 § 29.01.100]; prior:  1955 c 102 § 8; prior: 1907 c 209 § 26, part; RRS § 5203, part; ]

== 29A.04.109 - Overseas voter.
"Overseas voter" means any elector of the state of Washington outside the territorial limits of the United States.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=2009%20c%20369%20§%202[2009 c 369 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20119[2003 c 111 § 119]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c346.pdf?cite=1987%20c%20346%20§%206[1987 c 346 § 6]; ]

== 29A.04.110 - Partisan office.
"Partisan office" means a public office for which a candidate may indicate a political party preference on his or her declaration of candidacy and have that preference appear on the primary and general election ballot in conjunction with his or her name. The following are partisan offices:

. United States senator and United States representative;

. All state offices, including legislative, except (a) judicial offices and (b) the office of superintendent of public instruction;

. All county offices except (a) judicial offices and (b) those offices for which a county home rule charter provides otherwise.

[ 2005 c 2 § 4 (Initiative Measure No. 872, approved November 2, 2004); ]

== 29A.04.121 - Precinct.
"Precinct" means a geographical subdivision for voting purposes that is established by a county legislative authority.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20121[2003 c 111 § 121]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c9.pdf?cite=1965%20c%209%20§%2029.01.120[1965 c 9 § 29.01.120]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c1.pdf?cite=1933%20c%201%20§%202[1933 c 1 § 2]; RRS § 5114-2; prior:  1915 c 16 § 1; RRS § 5114; ]

== 29A.04.127 - Primary.
"Primary" or "primary election" means a procedure for winnowing candidates for public office to a final list of two as part of a special or general election. Each voter has the right to cast a vote for any candidate for each office without any limitation based on party preference or affiliation, of either the voter or the candidate.

[ 2005 c 2 § 5 (Initiative Measure No. 872, approved November 2, 2004); http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20122[2003 c 111 § 122]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c9.pdf?cite=1965%20c%209%20§%2029.01.130[1965 c 9 § 29.01.130]; prior: 1907 c 209 § 1, part; RRS § 5177(a). See also  1950 ex.s. c 14 § 2; ]

== 29A.04.133 - Qualified.
"Qualified" when pertaining to a winner of an election means that for such election:

. The results have been certified;

. Any required bond has been posted; and

. The winner has taken and subscribed an oath or affirmation in compliance with the appropriate statute, or if none is specified, that he or she will faithfully and impartially discharge the duties of the office to the best of his or her ability. This oath or affirmation shall be administered and certified by any officer or notary public authorized to administer oaths, without charge therefor.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2152.SL.pdf?cite=2007%20c%20374%20§%201[2007 c 374 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20123[2003 c 111 § 123]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c126.pdf?cite=1979%20ex.s.%20c%20126%20§%202[1979 ex.s. c 126 § 2]; ]

== 29A.04.139 - Recount.
"Recount" means the process of retabulating ballots and producing amended election returns based on that retabulation, even if the vote totals have not changed.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20124[2003 c 111 § 124]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1644-S.SL.pdf?cite=2001%20c%20225%20§%201[2001 c 225 § 1]; ]

== 29A.04.145 - Registered voter.
"Registered voter" means any elector who has completed the statutory registration procedures established by this title. The terms "registered voter" and "qualified elector" are synonymous.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20125[2003 c 111 § 125]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c346.pdf?cite=1987%20c%20346%20§%207[1987 c 346 § 7]; ]

== 29A.04.151 - Residence.
"Residence" for the purpose of registering and voting means a person's permanent address where he or she physically resides and maintains his or her abode. However, no person gains residence by reason of his or her presence or loses his or her residence by reason of his or her absence:

. While employed in the civil or military service of the state or of the United States;

. While engaged in the navigation of the waters of this state or the United States or the high seas;

. While a student at any institution of learning;

. While confined in any public prison.

Absence from the state on business shall not affect the question of residence of any person unless the right to vote has been claimed or exercised elsewhere.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20126[2003 c 111 § 126]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c178.pdf?cite=1971%20ex.s.%20c%20178%20§%201[1971 ex.s. c 178 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c9.pdf?cite=1965%20c%209%20§%2029.01.140[1965 c 9 § 29.01.140]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c181.pdf?cite=1955%20c%20181%20§%201[1955 c 181 § 1]; prior:  Code 1881 § 3051; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1865%20p%2025%20§%202[1865 p 25 § 2]; RRS § 5110.  Code 1881 § 3053; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1866%20p%208%20§%2011[1866 p 8 § 11]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1865%20p%2025%20§%204[1865 p 25 § 4]; RRS § 5111; ]

== 29A.04.163 - Service voter.
"Service voter" means any elector of the state of Washington who is a member of the armed forces under 42 U.S.C. Sec. 1973 ff-6 while in active service, is a member of a reserve component of the armed forces, is a student or member of the faculty at a United States military academy, is a member of the merchant marine of the United States, or is a member of a religious group or welfare agency officially attached to and serving with the armed forces of the United States.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=2009%20c%20369%20§%203[2009 c 369 § 3]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20127[2003 c 111 § 127]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5906.SL.pdf?cite=1991%20c%2023%20§%2013[1991 c 23 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c346.pdf?cite=1987%20c%20346%20§%208[1987 c 346 § 8]; ]

== 29A.04.169 - Short term.
"Short term" means the brief period of time starting upon certification of the general election or issuance of a certificate of election, and ending with the start of the next full term, and is applicable only when there has been a vacancy in the office after the last election at which such office could have been voted upon for an unexpired term. Short term elections are always held in conjunction with elections for the full term for the office.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=2013%20c%2011%20§%206[2013 c 11 § 6]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20130[2003 c 111 § 130]; 1975-'76 2nd ex.s. c 120 § 14; ]

== 29A.04.175 - Special election.
"Special election" means any election that is not a general election and may be held in conjunction with a general election or primary.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20129[2003 c 111 § 129]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c9.pdf?cite=1965%20c%209%20§%2029.01.170[1965 c 9 § 29.01.170]; Code 1881 § 3056; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1865%20p%2027%20§%202[1865 p 27 § 2]; RRS § 5155; ]

== 29A.04.180 - Total confinement. (Effective January 1, 2022.)
"Total confinement" has the same meaning as in RCW 9.94A.030, but a sentence of total confinement does not include confinement imposed as a sanction for a community custody violation under RCW 9.94A.633(1).

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1078-S.SL.pdf?cite=2021%20c%2010%20§%204[2021 c 10 § 4]; ]

== 29A.04.205 - State policy.
It is the policy of the state of Washington to encourage every eligible person to register to vote and to participate fully in all elections, and to protect the integrity of the electoral process by providing equal access to the process while guarding against discrimination and fraud. The election registration laws and the voting laws of the state of Washington must be administered without discrimination based upon race, creed, color, national origin, sex, or political affiliation.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20132[2003 c 111 § 132]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1739-S.SL.pdf?cite=2001%20c%2041%20§%201[2001 c 41 § 1]; ]

== 29A.04.206 - Voters' rights.
. The rights of Washington voters are protected by its constitution and laws and include the following fundamental rights:

.. The right of qualified voters to vote at all elections;

.. The right of absolute secrecy of the vote. No voter may be required to disclose political faith or adherence in order to vote;

.. The right to cast a vote for any candidate for each office without any limitation based on party preference or affiliation, of either the voter or the candidate.

. Nothing in subsection (1)(b) or (c) of this section alters or supersedes RCW 29A.56.020 through 29A.56.050, which govern presidential primary elections.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5273.SL.pdf?cite=2019%20c%207%20§%207[2019 c 7 § 7]; 2005 c 2 § 3 (Initiative Measure No. 872, approved November 2, 2004); ]

== 29A.04.210 - Registration required—Exception.
Except for service and overseas voters, only persons registered to vote shall be permitted to vote:

. At any election held for the purpose of electing persons to public office;

. At any recall election of a public officer;

. At any election held for the submission of a measure to any voting constituency;

. At any primary election.

This section does not apply to elections where being registered to vote is not a prerequisite to voting.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=2009%20c%20369%20§%204[2009 c 369 § 4]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20133[2003 c 111 § 133]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c9.pdf?cite=1965%20c%209%20§%2029.04.010[1965 c 9 § 29.04.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c181.pdf?cite=1955%20c%20181%20§%208[1955 c 181 § 8]; prior:  1933 c 1 § 22, part; RRS § 5114-22, part.   1933 c 1 § 23; RRS § 5114-23. See also  1935 c 26 § 3; RRS § 5189; ]

== 29A.04.216 - County auditor—Duties—Exceptions.
The county auditor of each county shall be ex officio the supervisor of all primaries and elections, general or special, and it shall be the county auditor's duty to provide places for holding such primaries and elections; to provide the supplies and materials necessary for the conduct of elections; and to publish and post notices of calling such primaries and elections in the manner provided by law. The auditor shall also apportion to the county, each city, town, or district, and to the state of Washington, its share of the expense of such primaries and elections. This section does not apply to general or special elections for any city, town, or district that is not subject to RCW 29A.04.321 and 29A.04.330, but all such elections must be held and conducted at the time, in the manner, and by the officials (with such notice, requirements for filing for office, and certifications by local officers) as provided and required by the laws governing such elections. State and federal offices are to be considered one entity for purposes of election cost proration and reimbursement.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2421-S.SL.pdf?cite=2020%20c%20337%20§%203[2020 c 337 § 3]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=2013%20c%2011%20§%207[2013 c 11 § 7]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5124-S.SL.pdf?cite=2011%20c%2010%20§%206[2011 c 10 § 6]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6453.SL.pdf?cite=2004%20c%20271%20§%20104[2004 c 271 § 104]; ]

== 29A.04.220 - County auditor—Public notice of availability of services.
The county auditor shall provide public notice of the availability of registration and voting aids, assistance to elderly and disabled persons, and procedures for voting calculated to reach elderly and disabled persons not later than public notice of the closing of registration for a primary or election.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5124-S.SL.pdf?cite=2011%20c%2010%20§%207[2011 c 10 § 7]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20135[2003 c 111 § 135]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1291-S.SL.pdf?cite=1999%20c%20298%20§%2018[1999 c 298 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c205.pdf?cite=1985%20c%20205%20§%2010[1985 c 205 § 10]; ]

== 29A.04.223 - Vote by mail impacts on voters with disabilities—Mitigation—Advisory committee, plan.
. The legislature finds that the elimination of polling places resulting from the transition to vote by mail creates barriers that restrict the ability of many voters with disabilities from achieving the independence and privacy in voting provided by the accessible voting devices required under the help America vote act. Counties must take appropriate steps to mitigate these impacts and to address the obligation to provide voters with disabilities an equal opportunity to vote independently and privately, to the extent that this can be achieved without incurring undue administrative and financial burden.

. Each county shall establish and maintain an advisory committee that includes persons with diverse disabilities and persons with expertise in providing accommodations for persons with disabilities. The committee shall assist election officials in developing a plan to identify and implement changes to improve the accessibility of elections for voters with disabilities. The plan shall include recommendations for the following:

.. The number of voting centers that will be maintained in order to ensure that people with disabilities have reasonable access to accessible voting devices, and a written explanation for how the determination was made;

.. The locations of ballot drop-off facilities, voting centers, and other election-related functions necessary to maximize accessibility to persons with disabilities;

.. Outreach to voters with disabilities on the availability of disability accommodation, including in-person disability access voting;

.. Transportation of voting devices to locations convenient for voters with disabilities in order to ensure reasonable access for voters with disabilities; and

.. Implementation of the provisions of the help America vote act related to persons with disabilities.

Counties must update the plan at least annually. The election review staff of the secretary of state shall review and evaluate the plan in conformance with the review procedure identified in RCW 29A.04.570.

. Counties may form a joint advisory committee to develop the plan identified in subsection (2) of this section if no more than one of the participating counties has a population greater than seventy thousand.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5124-S.SL.pdf?cite=2011%20c%2010%20§%2044[2011 c 10 § 44]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5902-S.SL.pdf?cite=2010%20c%20215%20§%205[2010 c 215 § 5]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2479-S.SL.pdf?cite=2006%20c%20207%20§%207[2006 c 207 § 7]; ]

== 29A.04.230 - Secretary of state as chief election officer.
The secretary of state through the election division shall be the chief election officer for all federal, state, county, city, town, and district elections that are subject to this title. The secretary of state shall keep records of elections held for which he or she is required by law to canvass the results, make such records available to the public upon request, and coordinate those state election activities required by federal law.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20137[2003 c 111 § 137]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6188-S.SL.pdf?cite=1994%20c%2057%20§%204[1994 c 57 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c9.pdf?cite=1965%20c%209%20§%2029.04.070[1965 c 9 § 29.04.070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c200.pdf?cite=1963%20c%20200%20§%2023[1963 c 200 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c161.pdf?cite=1949%20c%20161%20§%2012[1949 c 161 § 12]; Rem. Supp. 1949 § 5147-2; ]

== 29A.04.235 - Election laws for county auditors.
The secretary of state shall ensure that each county auditor is provided with the most recent version of the election laws of the state, as contained in this title. Where amendments have been enacted after the last compilation of the election laws, he or she shall ensure that each county auditor receives a copy of those amendments before the next primary or election.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5124-S.SL.pdf?cite=2011%20c%2010%20§%208[2011 c 10 § 8]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20138[2003 c 111 § 138]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c9.pdf?cite=1965%20c%209%20§%2029.04.060[1965 c 9 § 29.04.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c209.pdf?cite=1907%20c%20209%20§%2016[1907 c 209 § 16]; RRS § 5193.   1889 p 413 § 34; RRS § 5299; ]

== 29A.04.250 - Toll-free media and web page.
The secretary of state shall provide a toll-free media and web page designed to allow voter communication with the office of the secretary of state.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20141[2003 c 111 § 141]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1739-S.SL.pdf?cite=2001%20c%2041%20§%205[2001 c 41 § 5]; ]

== 29A.04.255 - Electronic documents—Acceptance.
The secretary of state or a county auditor shall accept and file in his or her office electronic transmissions of the following documents:

. Declarations of candidacy;

. County canvass reports;

. Voters' pamphlet statements;

. Arguments for and against ballot measures that will appear in a voters' pamphlet;

. Requests for recounts;

. Certification of candidates and measures by the secretary of state;

. Direction by the secretary of state for the conduct of a recount;

. Requests for ballots;

. Any other election related document authorized by rule adopted by the secretary of state under RCW 29A.04.611.

The acceptance by the secretary of state or the county auditor is conditional upon the document being filed in a timely manner, being legible, and otherwise satisfying the requirements of state law or rules with respect to form and content.

 The secretary may by rule require that the original of any document, a copy of which is filed by electronic transmission under this section, also be filed by a deadline established by the secretary by rule.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5171-S.SL.pdf?cite=2011%20c%20349%20§%201[2011 c 349 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1000.SL.pdf?cite=2011%20c%20348%20§%201[2011 c 348 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5124-S.SL.pdf?cite=2011%20c%2010%20§%209[2011 c 10 § 9]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6417.SL.pdf?cite=2004%20c%20266%20§%205[2004 c 266 § 5]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20142[2003 c 111 § 142]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5043.SL.pdf?cite=1991%20c%20186%20§%201[1991 c 186 § 1]; ]

== 29A.04.311 - Primaries.
Primaries for general elections to be held in November, and the election of precinct committee officers, must be held on the first Tuesday of the preceding August.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5171-S.SL.pdf?cite=2011%20c%20349%20§%202[2011 c 349 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6236.SL.pdf?cite=2006%20c%20344%20§%201[2006 c 344 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6453.SL.pdf?cite=2004%20c%20271%20§%20105[2004 c 271 § 105]; ]

== 29A.04.321 - State and local general elections—Statewide general election—Exceptions—Special county elections.
. All state, county, city, town, and district general elections for the election of federal, state, legislative, judicial, county, city, town, and district officers, and for the submission to the voters of the state, county, city, town, or district of any measure for their adoption and approval or rejection, shall be held on the first Tuesday after the first Monday of November, in the year in which they may be called. A statewide general election shall be held on the first Tuesday after the first Monday of November of each year. However, the statewide general election held in odd-numbered years shall be limited to (a) city, town, and district general elections as provided for in RCW 29A.04.330, or as otherwise provided by law; (b) the election of federal officers for the remainder of any unexpired terms in the membership of either branch of the Congress of the United States; (c) the election of state and county officers for the remainder of any unexpired terms of offices created by or whose duties are described in Article II, section 15, Article III, sections 16, 17, 19, 20, 21, 22, and 23, and Article IV, sections 3 and 5 of the state Constitution and RCW 2.06.080; (d) the election of county officers in any county governed by a charter containing provisions calling for general county elections at this time; and (e) the approval or rejection of state measures, including proposed constitutional amendments, matters pertaining to any proposed constitutional convention, initiative measures and referendum measures proposed by the electorate, referendum bills, and any other matter provided by the legislature for submission to the electorate.

. A county legislative authority may call a special county election by presenting a resolution to the county auditor prior to the proposed election date. A special election called by the county legislative authority shall be held on one of the following dates as decided by such governing body:

.. The second Tuesday in February;

.. The fourth Tuesday in April;

.. The day of the primary as specified by RCW 29A.04.311; or

.. The first Tuesday after the first Monday in November.

. A resolution calling for a special election on a date set forth in subsection (2)(a) and (b) of this section must be presented to the county auditor at least sixty days prior to the election date. A resolution calling for a special election on a date set forth in subsection (2)(c) of this section must be presented to the county auditor no later than the Friday immediately before the first day of regular candidate filing. A resolution calling for a special election on a date set forth in subsection (2)(d) of this section must be presented to the county auditor no later than the day of the primary.

. In addition to the dates set forth in subsection (2)(a) through (d) of this section, a special election to validate an excess levy or bond issue may be called at any time to meet the needs resulting from fire, flood, earthquake, or other act of God. Such county special election shall be noticed and conducted in the manner provided by law.

. This section shall supersede the provisions of any and all other statutes, whether general or special in nature, having different dates for such city, town, and district elections, the purpose of this section being to establish mandatory dates for holding elections. This section shall not be construed as fixing the time for holding primary elections, or elections for the recall of any elective public officer.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1919-S.SL.pdf?cite=2015%20c%20146%20§%201[2015 c 146 § 1]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=2013%20c%2011%20§%208[2013 c 11 § 8]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5171-S.SL.pdf?cite=2011%20c%20349%20§%203[2011 c 349 § 3]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1018-S.SL.pdf?cite=2009%20c%20413%20§%202[2009 c 413 § 2]; 2009 c 413 § 1; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6236.SL.pdf?cite=2006%20c%20344%20§%202[2006 c 344 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6453.SL.pdf?cite=2004%20c%20271%20§%20106[2004 c 271 § 106]; ]

== 29A.04.330 - City, town, and district general and special elections—Exceptions.
. All city, town, and district general elections shall be held throughout the state of Washington on the first Tuesday following the first Monday in November in the odd-numbered years.

This section shall not apply to:

.. Elections for the recall of any elective public officer;

.. Public utility districts, conservation districts, or district elections at which the ownership of property within those districts is a prerequisite to voting, all of which elections shall be held at the times prescribed in the laws specifically applicable thereto;

.. Consolidation proposals as provided for in RCW 28A.315.235 and nonhigh capital fund aid proposals as provided for in chapter 28A.540 RCW; and

.. Special flood control districts consisting of three or more counties.

. The county auditor, as ex officio supervisor of elections, upon request in the form of a resolution of the governing body of a city, town, or district, presented to the auditor prior to the proposed election date, shall call a special election in such city, town, or district, and for the purpose of such special election he or she may combine, unite, or divide precincts. Such a special election shall be held on one of the following dates as decided by the governing body:

.. The second Tuesday in February;

.. The fourth Tuesday in April;

.. The day of the primary election as specified by RCW 29A.04.311; or

.. The first Tuesday after the first Monday in November.

. A resolution calling for a special election on a date set forth in subsection (2)(a) and (b) of this section must be presented to the county auditor at least sixty days prior to the election date. A resolution calling for a special election on a date set forth in subsection (2)(c) of this section must be presented to the county auditor no later than the Friday immediately before the first day of regular candidate filing. A resolution calling for a special election on a date set forth in subsection (2)(d) of this section must be presented to the county auditor no later than the day of the primary.

. In addition to subsection (2)(a) through (d) of this section, a special election to validate an excess levy or bond issue may be called at any time to meet the needs resulting from fire, flood, earthquake, or other act of God, except that no special election may be held between the first day for candidates to file for public office and the last day to certify the returns of the general election other than as provided in subsection (2)(c) and (d) of this section. Such special election shall be conducted and notice thereof given in the manner provided by law.

. This section shall supersede the provisions of any and all other statutes, whether general or special in nature, having different dates for such city, town, and district elections, the purpose of this section being to establish mandatory dates for holding elections.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1919-S.SL.pdf?cite=2015%20c%20146%20§%202[2015 c 146 § 2]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=2013%20c%2011%20§%209[2013 c 11 § 9]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5171-S.SL.pdf?cite=2011%20c%20349%20§%204[2011 c 349 § 4]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1018-S.SL.pdf?cite=2009%20c%20413%20§%204[2009 c 413 § 4]; 2009 c 413 § 3; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5705-S.SL.pdf?cite=2009%20c%20144%20§%203[2009 c 144 § 3]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6236.SL.pdf?cite=2006%20c%20344%20§%203[2006 c 344 § 3]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6417.SL.pdf?cite=2004%20c%20266%20§%206[2004 c 266 § 6]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20145[2003 c 111 § 145]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6572-S.SL.pdf?cite=2002%20c%2043%20§%202[2002 c 43 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6061.SL.pdf?cite=1994%20c%20142%20§%202[1994 c 142 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6213.SL.pdf?cite=1992%20c%2037%20§%202[1992 c 37 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20562[1990 c 33 § 562]; 1989 c 4 § 10 (Initiative Measure No. 99); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c167.pdf?cite=1986%20c%20167%20§%206[1986 c 167 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c3.pdf?cite=1980%20c%203%20§%202[1980 c 3 § 2]; 1975-'76 2nd ex.s. c 111 § 2; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c123.pdf?cite=1965%20c%20123%20§%203[1965 c 123 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c9.pdf?cite=1965%20c%209%20§%2029.13.020[1965 c 9 § 29.13.020]; prior:  1963 c 200 § 1; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c55.pdf?cite=1955%20c%2055%20§%201[1955 c 55 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c101.pdf?cite=1951%20c%20101%20§%201[1951 c 101 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c161.pdf?cite=1949%20c%20161%20§%201[1949 c 161 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1927c182.pdf?cite=1927%20c%20182%20§%201[1927 c 182 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c53.pdf?cite=1923%20c%2053%20§%202[1923 c 53 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c61.pdf?cite=1921%20c%2061%20§%202[1921 c 61 § 2]; Rem. Supp. 1949 § 5144; ]

== 29A.04.340 - Elections in certain first-class school districts.
. In each county with a population of two hundred ten thousand or more, first-class school districts containing a city of the first-class shall hold their elections biennially as provided in RCW 29A.04.330.

. Except as provided in RCW 28A.343.610, the directors to be elected may be elected for terms of six years and until their successors are elected, qualified, and assume office in accordance with *RCW 29A.20.040.

. If the board of directors of a school district pursuant to subsection (1) of this section reduces the length of the term of office for school directors in the district from six to four years, the reduction in the length of term must not affect the term of office of any incumbent director without his or her consent, and a provision must be made to appropriately stagger future elections of school directors.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5327-S.SL.pdf?cite=2009%20c%20107%20§%204[2009 c 107 § 4]; ]

== 29A.04.410 - Costs borne by constituencies.
Every county, city, town, and district, and the state is liable for its proportionate share of the costs when such elections are held in conjunction with other elections held under RCW 29A.04.321 and 29A.04.330.

Whenever any county, city, town, or district, or the state holds any primary or election, general or special, on an isolated date, all costs of such elections must be borne by the county, city, town, or district concerned, or the state as appropriate.

The purpose of this section is to clearly establish that the county is not responsible for any costs involved in the holding of any city, town, district, state, or federal election.

In recovering such election expenses, including a reasonable proration of administrative costs, the county auditor shall certify the cost to the county treasurer with a copy to the clerk or auditor of the city, town, or district concerned, or the secretary of state as appropriate. Upon receipt of such certification relating to a city, town, or district, the county treasurer shall make the transfer from any available and appropriate city, town, or district funds to the county current expense fund or to the county election reserve fund if such a fund is established. Each city, town, or district must be promptly notified by the county treasurer whenever such transfer has been completed. However, in those districts wherein a treasurer, other than the county treasurer, has been appointed such transfer procedure does not apply, but the district shall promptly issue its warrant for payment of election costs. State and federal offices are to be considered one entity for purposes of election cost proration and reimbursement.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2421-S.SL.pdf?cite=2020%20c%20337%20§%201[2020 c 337 § 1]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=2013%20c%2011%20§%2010[2013 c 11 § 10]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20146[2003 c 111 § 146]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c123.pdf?cite=1965%20c%20123%20§%205[1965 c 123 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c9.pdf?cite=1965%20c%209%20§%2029.13.045[1965 c 9 § 29.13.045]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c200.pdf?cite=1963%20c%20200%20§%207[1963 c 200 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c257.pdf?cite=1951%20c%20257%20§%205[1951 c 257 § 5]; ]

== 29A.04.420 - State share.
. Whenever federal officers, state officers, or measures are voted upon at a state primary or general election held under RCW 29A.04.321, the state of Washington shall assume a prorated share of the costs of that state primary or general election for the federal and state offices and measures, including the prorated cost of return postage, required to be included on return envelopes pursuant to RCW 29A.40.091.

. Whenever a primary or vacancy election is held to fill a vacancy in the position of United States senator or United States representative under chapter 29A.28 RCW, the state of Washington shall assume a prorated share of the costs of that primary or vacancy election.

. The county auditor shall apportion the state's share of these expenses when prorating election costs under RCW 29A.04.410 and in accordance with the state budgeting, accounting, and reporting system, shall file such expense claims with the secretary of state.

. The secretary of state shall include in his or her biennial budget requests sufficient funds to carry out this section. Reimbursements for election costs shall be from appropriations specifically provided by law for that purpose.

. State and federal offices are to be considered one entity for purposes of election cost proration and reimbursement.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2421-S.SL.pdf?cite=2020%20c%20337%20§%202[2020 c 337 § 2]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5063-S.SL.pdf?cite=2019%20c%20161%20§%202[2019 c 161 § 2]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=2013%20c%2011%20§%2011[2013 c 11 § 11]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20147[2003 c 111 § 147]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c45.pdf?cite=1985%20c%2045%20§%202[1985 c 45 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c144.pdf?cite=1977%20ex.s.%20c%20144%20§%204[1977 ex.s. c 144 § 4]; 1975-'76 2nd ex.s. c 4 § 1; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c4.pdf?cite=1973%20c%204%20§%202[1973 c 4 § 2]; ]

== 29A.04.430 - Reimbursement payment—Availability of funds.
. For any reimbursement of election costs under RCW 29A.04.420, the secretary of state shall pay within thirty days after the receipt of a properly executed and documented voucher for such expenses and the entry of an allotment from specifically appropriated funds for this purpose until those funds are exhausted. If funds appropriated for this purpose are not sufficient to pay all claims, the secretary of state shall include a budget request to the legislature during the next legislative session for sufficient funds for reimbursement of all remaining claims and shall pay all properly executed and documented vouchers to the counties within thirty days of allotment of specifically appropriated funds for this purpose. The secretary of state shall promptly notify any county that submits an incomplete or inaccurate voucher for reimbursement under RCW 29A.04.420.

. Funding provided in this section to counties for election costs in even-numbered years is retrospective and prospective reimbursement under RCW 43.135.060 for any new or increased responsibilities under this title.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2421-S.SL.pdf?cite=2020%20c%20337%20§%204[2020 c 337 § 4]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20148[2003 c 111 § 148]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c167.pdf?cite=1986%20c%20167%20§%207[1986 c 167 § 7]; ]

== 29A.04.440 - Election account.
. The election account is created in the state treasury.

. The following receipts must be deposited into the account:

Amounts received from the federal government under Public Law 107-252 (October 29, 2002), known as the "Help America Vote Act of 2002," including any amounts received under subsequent amendments to the act;

amounts appropriated or otherwise made available by the state legislature for the purposes of carrying out activities for which federal funds are provided to the state under Public Law 107-252, including any amounts received under subsequent amendments to the act;

and such other amounts as may be appropriated by the legislature to the account.

. Moneys in the account may be spent only after appropriation. Expenditures from the account may be made only to facilitate the implementation of Public Law 107-252.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6417.SL.pdf?cite=2004%20c%20266%20§%202[2004 c 266 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5374.SL.pdf?cite=2003%20c%2048%20§%201[2003 c 48 § 1]; ]

== 29A.04.450 - Local government grant program.
The secretary of state shall establish a competitive local government grant program to solicit and prioritize project proposals from county election offices. Potential projects [project] proposals must be new projects designed to help the county election office comply with the requirements of the Help America Vote Act (P.L. 107-252). Grant funds will not be allocated to fund existing statutory functions of local elections [election] offices, and in order to be eligible for a grant, local election offices must maintain an elections budget at or above the local elections budget by July 1, 2004.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6419-S.SL.pdf?cite=2004%20c%20267%20§%20201[2004 c 267 § 201]; ]

== 29A.04.460 - Grant program—Administration.
The secretary of state will administer the grant program and disburse funds from the election account established in the state treasury by the legislature in chapter 48, Laws of 2003. Only grant proposals from local government election offices will be reviewed. The secretary of state and any local government grant recipient shall enter into an agreement outlining the terms of the grant and a payment schedule. The payment schedule may allow the secretary of state to make payments directly to vendors contracted by the local government election office from Help America Vote Act (P.L. 107-252) funds. The secretary of state shall adopt any rules necessary to facilitate this section.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6419-S.SL.pdf?cite=2004%20c%20267%20§%20202[2004 c 267 § 202]; ]

== 29A.04.470 - Grant program—Advisory committee.
. The secretary of state shall create an advisory committee and adopt rules governing project eligibility, evaluation, awarding of grants, and other criteria for administering the local government grant program, which may include a preference for grants that include a match of local funds.

. The advisory committee shall review grant proposals and establish a prioritized list of projects to be considered for funding by the third Tuesday in May of each year beginning in 2004 and continuing as long as funds in the election account established by RCW 29A.04.440 are available. The grant award may have an effective date other than the date the project is placed on the prioritized list, including money spent previously by the county that would qualify for reimbursement under the Help America Vote Act (P.L. 107-252).

. Examples of projects that would be eligible for local government grant funding include, but are not limited to the following:

.. Replacement or upgrade of voting equipment, including the replacement of punch card voting systems;

.. Purchase of additional voting equipment, including the purchase of equipment to meet the disability requirements of the Help America Vote Act (P.L. 107-252);

.. Purchase of new election management system hardware and software capable of integrating with the statewide voter registration system required by the Help America Vote Act (P.L. 107-252);

.. Development and production of election worker training materials;

.. Voter education programs;

.. Publication of a local voters' pamphlet;

.. Toll-free access system to provide notice of the outcome of provisional ballots; and

.. Training for local election officials.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5124-S.SL.pdf?cite=2011%20c%2010%20§%2010[2011 c 10 § 10]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6419-S.SL.pdf?cite=2004%20c%20267%20§%20203[2004 c 267 § 203]; ]

== 29A.04.510 - Election administration and certification board—Generally.
. The Washington state election administration and certification board is established and has the responsibilities and authorities prescribed by this chapter. The board is composed of the following members:

.. The secretary of state or the secretary's designee;

.. The state director of elections or the director's designee;

.. Four county auditors appointed by the Washington state association of county auditors or their alternates who are county auditors designated by the association to serve as such alternates, each appointee and alternate to serve at the pleasure of the association;

.. One member from each of the two largest political party caucuses of the house of representatives designated by and serving at the pleasure of the legislative leader of the respective caucus;

.. One member from each of the two largest political party caucuses of the senate designated by and serving at the pleasure of the legislative leader of the respective caucus; and

.. One representative from each major political party, designated by and serving at the pleasure of the chair of the party's state central committee.

. The board shall elect a chair from among its number; however, neither the secretary of state nor the state director of elections nor their designees may serve as the chair of the board. A majority of the members appointed to the board constitutes a quorum for conducting the business of the board. Chapter 42.30 RCW, the Open Public Meetings Act, and RCW 42.30.035 regarding minutes of meetings, apply to the meetings of the board.

. Members of the board shall serve without compensation. The secretary of state shall reimburse members of the board, other than those who are members of the legislature, for travel expenses in accordance with RCW 43.03.050 and 43.03.060. Members of the board who are members of the legislature shall be reimbursed as provided in chapter 44.04 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5316.SL.pdf?cite=2017%203rd%20sp.s.%20c%2025%20§%2031[2017 3rd sp.s. c 25 § 31]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20149[2003 c 111 § 149]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2319-S.SL.pdf?cite=1992%20c%20163%20§%203[1992 c 163 § 3]; ]

== 29A.04.520 - Appeals.
The board created in RCW 29A.04.510 shall review appeals filed under RCW 29A.04.550 or 29A.04.570. A decision of the board regarding the appeal must be supported by not less than a majority of the members appointed to the board. A decision of the board regarding an appeal filed under RCW 29A.04.570 concerning an election review conducted under that section is final. If a decision of the board regarding an appeal filed under RCW 29A.04.550 includes a recommendation that a certificate be issued, the secretary of state, upon the recommendation of the board, shall issue the certificate.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20150[2003 c 111 § 150]; ]

== 29A.04.525 - Complaint procedures.
The state-based administrative complaint procedures required in the Help America Vote Act (P.L. 107-252) and detailed in administrative rule apply to all primary, general, and special elections administered under this title.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6419-S.SL.pdf?cite=2004%20c%20267%20§%20401[2004 c 267 § 401]; ]

== 29A.04.530 - Duties of secretary of state.
The secretary of state shall:

. Establish and operate, or provide by contract, training and certification programs for state and county elections administration officials and personnel, including training on election laws, the various types of election law violations, and discrimination;

. Administer tests for state and county officials and personnel who have received such training and issue certificates to those who have successfully completed the training and passed such tests;

. Maintain a record of those individuals who have received such training and certificates; and

. Provide the staffing and support services required by the board created under RCW 29A.04.510.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6122-S.SL.pdf?cite=2009%20c%20415%20§%208[2009 c 415 § 8]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2477.SL.pdf?cite=2006%20c%20206%20§%201[2006 c 206 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5499-S.SL.pdf?cite=2005%20c%20243%20§%202[2005 c 243 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20151[2003 c 111 § 151]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1739-S.SL.pdf?cite=2001%20c%2041%20§%2011[2001 c 41 § 11]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2319-S.SL.pdf?cite=1992%20c%20163%20§%205[1992 c 163 § 5]; ]

== 29A.04.540 - Training of administrators.
A person having responsibility for the administration or conduct of elections shall, within eighteen months of undertaking those responsibilities, receive general training regarding the conduct of elections and specific training regarding their responsibilities and duties as prescribed by this title or by rules adopted by the secretary of state under this title. Included among those persons for whom such training is mandatory are the following:

. Secretary of state elections division personnel;

. County elections administrators under RCW 36.22.220; and

. Any other person or group charged with election administration responsibilities if the person or group is designated by rule adopted by the secretary of state as requiring the training.

Neither this section nor RCW 29A.04.530 may be construed as requiring an elected official to receive training or a certificate of training as a condition for seeking or holding elective office or as a condition for carrying out constitutional duties.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5124-S.SL.pdf?cite=2011%20c%2010%20§%2011[2011 c 10 § 11]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6122-S.SL.pdf?cite=2009%20c%20415%20§%209[2009 c 415 § 9]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20152[2003 c 111 § 152]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2319-S.SL.pdf?cite=1992%20c%20163%20§%206[1992 c 163 § 6]; ]

== 29A.04.550 - Denial of certification—Review and appeal.
. A decision of the secretary of state to deny certification under RCW 29A.04.530 must be entered in the manner specified for orders under the Administrative Procedure Act, chapter 34.05 RCW. Such a decision is not effective for a period of twenty days following the date of the decision, during which time the person denied certification may file a petition with the secretary of state requesting the secretary to reconsider the decision and to grant certification. The petitioner shall include in the petition, an explanation of the reasons why the initial decision is incorrect and certification should be granted, and may include a request for a hearing on the matter. The secretary of state shall reconsider the matter if the petition is filed in a proper and timely manner. If a hearing is requested, the secretary of state shall conduct the hearing within sixty days after the date on which the petition is filed. The secretary of state shall render a final decision on the matter within ninety days after the date on which the petition is filed.

. Within twenty days after the date on which the secretary of state makes a final decision denying a petition under this section, the petitioner may appeal the denial to the board created in RCW 29A.04.510. In deciding appeals, the board shall restrict its review to the record established when the matter was before the secretary of state. The board shall affirm the decision if it finds that the record supports the decision and that the decision is not inconsistent with other decisions of the secretary of state in which the same standards were applied and certification was granted. Similarly, the board shall reverse the decision and recommend to the secretary of state that certification be granted if the board finds that such support is lacking or that such inconsistency exists.

. Judicial review of certification decisions will be as prescribed under RCW 34.05.510 through 34.05.598, but is limited to the review of board decisions denying certification.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20153[2003 c 111 § 153]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2319-S.SL.pdf?cite=1992%20c%20163%20§%207[1992 c 163 § 7]; ]

== 29A.04.560 - Election review section.
An election review section is established in the elections division of the office of the secretary of state. Permanent staff of the elections division, trained and certified as required by RCW 29A.04.540, shall perform the election review functions prescribed by RCW 29A.04.570. The staff may also be required to assist in training, certification, and other duties as may be assigned by the secretary of state to ensure the uniform and orderly conduct of elections in this state.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20154[2003 c 111 § 154]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2319-S.SL.pdf?cite=1992%20c%20163%20§%208[1992 c 163 § 8]; ]

== 29A.04.570 - Review of county election procedures.
. [Empty]
.. The election review staff of the office of the secretary of state shall conduct a review of election-related policies, procedures, and practices in an affected county or counties:

... If the unofficial returns of a primary or general election for a position in the state legislature indicate that a mandatory recount is likely for that position; or

... If unofficial returns indicate a mandatory recount is likely in a statewide election or an election for federal office.

Reviews conducted under (a)(ii) of this subsection shall be performed in as many selected counties as time and staffing permit. Reviews conducted as a result of mandatory recounts shall be performed between the time the unofficial returns are complete and the time the recount is to take place, if possible.

.. In addition to conducting reviews under (a) of this subsection, the election review staff shall also conduct such a review in a county at least once every five years, in conjunction with a county primary or special or general election, at the direction of the secretary of state or at the request of the county auditor. If staffing or budget levels do not permit a five-year election cycle for reviews, then reviews must be done as often as possible. If any resident of this state believes that an aspect of a primary or election has been conducted inappropriately in a county, the resident may file a complaint with the secretary of state. The secretary shall consider such complaints in scheduling periodic reviews under this section.

.. Before an election review is conducted in a county, the secretary of state shall provide the county auditor of the affected county and the chair of the state central committee of each major political party with notice that the review is to be conducted. When a periodic review is to be conducted in a county at the direction of the secretary of state under (b) of this subsection, the secretary shall provide the affected county auditor not less than thirty days' notice.

. Reviews shall be conducted in conformance with rules adopted under RCW 29A.04.630. In performing a review in a county under this chapter, the election review staff shall evaluate the policies and procedures established for conducting the primary or election in the county and the practices of those conducting it. As part of the review, the election review staff shall issue to the county auditor and the members of the county canvassing board a report of its findings and recommendations regarding such policies, procedures, and practices. A review conducted under this chapter shall not include any evaluation, finding, or recommendation regarding the validity of the outcome of a primary or election or the validity of any canvass of returns nor does the election review staff have any jurisdiction to make such an evaluation, finding, or recommendation under this title.

. The county auditor or the county canvassing board shall respond to the review report in writing, listing the steps that will be taken to correct any problems listed in the report. Within one year of issuance of the response provided by the county auditor or county canvassing board, the secretary of state shall verify that the county has taken the steps to correct the problems noted in the report.

. The county auditor of the county in which a review is conducted under this section or a member of the canvassing board of the county may appeal the findings or recommendations of the election review staff regarding the review by filing an appeal with the board created under RCW 29A.04.510.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6122-S.SL.pdf?cite=2009%20c%20415%20§%2010[2009 c 415 § 10]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1749.SL.pdf?cite=2005%20c%20240%20§%201[2005 c 240 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20155[2003 c 111 § 155]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5565.SL.pdf?cite=1997%20c%20284%20§%201[1997 c 284 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2319-S.SL.pdf?cite=1992%20c%20163%20§%209[1992 c 163 § 9]; ]

== 29A.04.575 - Visits to elections offices, facilities.
The secretary of state, or any staff of the elections division of the office of secretary of state, may make unannounced on-site visits to county election offices and facilities to observe the handling, processing, counting, or tabulation of ballots.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6417.SL.pdf?cite=2004%20c%20266%20§%201[2004 c 266 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1106.SL.pdf?cite=2003%20c%20109%20§%201[2003 c 109 § 1]; ]

== 29A.04.580 - County auditor and review staff.
The county auditor may designate any person who has been certified under this chapter, other than the auditor, to participate in a review conducted in the county under this chapter. Each county auditor and canvassing board shall cooperate fully during an election review by making available to the reviewing staff any material requested by the staff. The reviewing staff shall have full access to the county's election material. If ballots are reviewed by the staff, they shall be reviewed in the presence of the canvassing board or its designees. Ballots shall not leave the custody of the canvassing board. During the review and after its completion, the review staff may make appropriate recommendations to the county auditor or canvassing board, or both, to bring the county into compliance with the training required under this chapter, and the laws or rules of the state of Washington, to safeguard election material or to preserve the integrity of the elections process.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5124-S.SL.pdf?cite=2011%20c%2010%20§%2012[2011 c 10 § 12]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20156[2003 c 111 § 156]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2319-S.SL.pdf?cite=1992%20c%20163%20§%2010[1992 c 163 § 10]; ]

== 29A.04.590 - Election assistance and clearinghouse program.
The secretary of state shall establish within the elections division an election assistance and clearinghouse program, which shall provide regular communication between the secretary of state, local election officials, and major and minor political parties regarding newly enacted elections legislation, relevant judicial decisions affecting the administration of elections, and applicable attorney general opinions, and which shall respond to inquiries from elections administrators, political parties, and others regarding election information. This section does not empower the secretary of state to offer legal advice or opinions, but the secretary may discuss the construction or interpretation of election law, case law, or legal opinions from the attorney general or other competent legal authority.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20157[2003 c 111 § 157]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2319-S.SL.pdf?cite=1992%20c%20163%20§%2011[1992 c 163 § 11]; ]

== 29A.04.611 - Rules by secretary of state.
The secretary of state as chief election officer shall make reasonable rules in accordance with chapter 34.05 RCW not inconsistent with the federal and state election laws to effectuate any provision of this title and to facilitate the execution of its provisions in an orderly, timely, and uniform manner relating to any federal, state, county, city, town, and district elections. To that end the secretary shall assist local election officers by devising uniform forms and procedures.

In addition to the rule-making authority granted otherwise by this section, the secretary of state shall make rules governing the following provisions:

. The maintenance of voter registration records;

. The preparation, maintenance, distribution, review, and filing of precinct maps;

. Standards for the design, layout, and production of ballots;

. The examination and testing of voting systems for certification;

. The source and scope of independent evaluations of voting systems that may be relied upon in certifying voting systems for use in this state;

. Standards and procedures for the acceptance testing of voting systems by counties;

. Standards and procedures for testing the programming of vote tallying software for specific primaries and elections;

. Standards and procedures for the preparation and use of each type of certified voting system including procedures for the operation of counting centers where vote tallying systems are used;

. Standards and procedures to ensure the accurate tabulation and canvassing of ballots;

. Consistency among the counties of the state in the preparation of ballots, the operation of vote tallying systems, and the canvassing of primaries and elections;

. Procedures to ensure the secrecy of a voter's ballot when a small number of ballots are counted;

. The use of substitute devices or means of voting when a voting device is found to be defective, the counting of votes cast on the defective device, the counting of votes cast on the substitute device, and the documentation that must be submitted to the county auditor regarding such circumstances;

. Procedures for the transportation of sealed containers of voted ballots or sealed voting devices;

. The acceptance and filing of documents via electronic transmission;

. Voter registration applications and records;

. The use of voter registration information in the conduct of elections;

. The coordination, delivery, and processing of voter registration records accepted by driver licensing agents or the department of licensing;

. The coordination, delivery, and processing of voter registration records accepted by agencies designated by the governor to provide voter registration services;

. Procedures to receive and distribute voter registration applications by mail;

. Procedures for a voter to change his or her voter registration address within a county by telephone;

. Procedures for a voter to change the name under which he or she is registered to vote;

. Procedures for canceling dual voter registration records and for maintaining records of persons whose voter registrations have been canceled;

. Procedures for the electronic transfer of voter registration records between county auditors and the office of the secretary of state;

. Procedures and forms for declarations of candidacy;

. Procedures and requirements for the acceptance and filing of declarations of candidacy by electronic means;

. Procedures for the circumstance in which two or more candidates have a name similar in sound or spelling so as to cause confusion for the voter;

. Filing for office;

. The order of positions and offices on a ballot;

. Sample ballots;

. Independent evaluations of voting systems;

. The testing, approval, and certification of voting systems;

. The testing of vote tallying software programming;

. Standards and procedures to prevent fraud and to facilitate the accurate processing and canvassing of ballots, including standards for the approval and implementation of hardware and software for automated signature verification systems;

. Standards and procedures to guarantee the secrecy of ballots;

. Uniformity among the counties of the state in the conduct of elections;

. Standards and procedures to accommodate overseas voters and service voters;

. The tabulation of paper ballots;

. The accessibility of voting centers;

. The aggregation of precinct results if reporting the results of a single precinct could jeopardize the secrecy of a person's ballot;

. Procedures for conducting a statutory recount;

. Procedures for filling vacancies in congressional offices if the general statutory time requirements for availability of ballots, certification, canvassing, and related procedures cannot be met;

. Procedures for the statistical sampling of signatures for purposes of verifying and canvassing signatures on initiative, referendum, and recall election petitions;

. Standards and deadlines for submitting material to the office of the secretary of state for the voters' pamphlet;

. Deadlines for the filing of ballot titles for referendum bills and constitutional amendments if none have been provided by the legislature;

. Procedures for the publication of a state voters' pamphlet;

. Procedures for conducting special elections regarding nuclear waste sites if the general statutory time requirements for availability of ballots, certification, canvassing, and related procedures cannot be met;

. Procedures for conducting partisan primary elections;

. Standards and procedures for the proper conduct of voting on accessible voting devices;

. Standards for voting technology and systems used by the state or any political subdivision to be accessible for individuals with disabilities, including nonvisual accessibility for the blind and visually impaired, in a manner that provides the same opportunity for access and participation, including privacy and independence, as other voters;

. All data formats for transferring voter registration data on electronic or machine-readable media for the purpose of administering the statewide voter registration list required by the Help America Vote Act (P.L. 107-252);

. Defining the interaction of electronic voter registration election management systems employed by each county auditor to maintain a local copy of each county's portion of the official state list of registered voters;

. Provisions and procedures to implement the state-based administrative complaint procedure as required by the Help America Vote Act (P.L. 107-252);

. Facilitating the payment of local government grants to local government election officers or vendors; and

. Standards for the verification of signatures on ballot declarations.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5124-S.SL.pdf?cite=2011%20c%2010%20§%2013[2011 c 10 § 13]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=2009%20c%20369%20§%205[2009 c 369 § 5]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2479-S.SL.pdf?cite=2006%20c%20207%20§%201[2006 c 207 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2477.SL.pdf?cite=2006%20c%20206%20§%202[2006 c 206 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6453.SL.pdf?cite=2004%20c%20271%20§%20151[2004 c 271 § 151]; ]

== 29A.04.620 - Rules.
The secretary of state as chief election officer may make rules in accordance with chapter 34.05 RCW to facilitate the operation, accomplishment, and purpose of the presidential primary authorized in RCW * 29A.56.010 through 29A.56.060. The secretary of state shall adopt rules consistent with this chapter to comply with national or state political party rules.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20162[2003 c 111 § 162]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5852.SL.pdf?cite=1995%201st%20sp.s.%20c%2020%20§%204[1995 1st sp.s. c 20 § 4]; 1989 c 4 § 7 (Initiative Measure No. 99); ]

== 29A.04.630 - Joint powers and duties with board.
. The secretary of state and the board created in RCW 29A.04.510 shall jointly adopt rules, in the manner specified for the adoption of rules under the Administrative Procedure Act, chapter 34.05 RCW, governing:

.. The training of persons officially designated by major political parties as elections observers under this title, and the training and certification of election administration officials and personnel;

.. The policies and procedures for conducting election reviews under RCW 29A.04.570; and

.. The policies and standards to be used by the board in reviewing and rendering decisions regarding appeals filed under RCW 29A.04.570.

. The board created in RCW 29A.04.510 may adopt rules governing its procedures.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20163[2003 c 111 § 163]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2319-S.SL.pdf?cite=1992%20c%20163%20§%204[1992 c 163 § 4]; ]

== 29A.04.900 - Continuation of existing law.
The provisions of this title insofar as they are substantially the same as statutory provisions repealed by this chapter, and relating to the same subject matter, shall be construed as restatements and continuations, and not as new enactments.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20158[2003 c 111 § 158]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c9.pdf?cite=1965%20c%209%20§%2029.98.010[1965 c 9 § 29.98.010]; ]

== 29A.04.901 - Headings and captions not part of law.
Chapter headings, part, subpart, and section or subsection captions, as used in this title do not constitute any part of the law.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20159[2003 c 111 § 159]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c9.pdf?cite=1965%20c%209%20§%2029.98.020[1965 c 9 § 29.98.020]; ]

== 29A.04.902 - Invalidity of part not to affect remainder.
If any provision of this title, or its application to any person or circumstance is held invalid, the remainder of the title, or the application of the provision to other persons or circumstances is not affected.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20160[2003 c 111 § 160]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c9.pdf?cite=1965%20c%209%20§%2029.98.030[1965 c 9 § 29.98.030]; ]

