= 29A.12 - Voting systems.
:toc:

== 29A.12.005 - "Voting system."
As used in this chapter, "voting system" means:

. The total combination of mechanical, electromechanical, or electronic equipment including, but not limited to, the software, firmware, and documentation required to program, control, and support the equipment, that is used:

.. To define ballots;

.. To cast and count votes;

.. To report or display election results from the voting system;

.. To maintain and produce any audit trail information; and

.. To perform an audit under RCW 29A.60.185; and

. The practices and associated documentation used:

.. To identify system components and versions of such components;

.. To test the system during its development and maintenance;

.. To maintain records of system errors and defects;

.. To determine specific system changes to be made to a system after the initial qualification of the system; and

.. To make available any materials to the voter such as notices, instructions, forms, or paper ballots.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2406-S.SL.pdf?cite=2018%20c%20218%20§%205[2018 c 218 § 5]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=2013%20c%2011%20§%2021[2013 c 11 § 21]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6419-S.SL.pdf?cite=2004%20c%20267%20§%20601[2004 c 267 § 601]; ]

== 29A.12.010 - Authority for use.
At any primary or election in any county, votes may be cast, registered, recorded, or counted by means of voting systems that have been approved under RCW 29A.12.020.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20301[2003 c 111 § 301]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c59.pdf?cite=1990%20c%2059%20§%2017[1990 c 59 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c109.pdf?cite=1967%20ex.s.%20c%20109%20§%2012[1967 ex.s. c 109 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c9.pdf?cite=1965%20c%209%20§%2029.33.020[1965 c 9 § 29.33.020]; prior:  1913 c 58 § 1, part; RRS § 5300, part.   1913 c 58 § 18; RRS § 5318; ]

== 29A.12.020 - Inspection and test by secretary of state—Report.
The secretary of state shall inspect, evaluate, and publicly test all voting systems or components of voting systems that are submitted for review under RCW 29A.12.030. The secretary of state shall determine whether the voting systems conform with all of the requirements of this title, the applicable rules adopted in accordance with this title, and with generally accepted safety requirements. The secretary of state shall transmit a copy of the report of any examination under this section, within thirty days after completing the examination, to the county auditor of each county.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20302[2003 c 111 § 302]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c59.pdf?cite=1990%20c%2059%20§%2018[1990 c 59 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c40.pdf?cite=1982%20c%2040%20§%201[1982 c 40 § 1]; ]

== 29A.12.030 - Submitting system or component for examination.
The manufacturer or distributor of a voting system or component of a voting system may submit that system or component to the secretary of state for examination under RCW 29A.12.020.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20303[2003 c 111 § 303]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c59.pdf?cite=1990%20c%2059%20§%2019[1990 c 59 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c40.pdf?cite=1982%20c%2040%20§%202[1982 c 40 § 2]; ]

== 29A.12.040 - Independent evaluation.
. The secretary of state may rely on the results of independent design, engineering, and performance evaluations in the examination under RCW 29A.12.020 if the source and scope of these independent evaluations are specified by rule.

. The secretary of state may contract with experts in mechanical or electrical engineering or data processing to assist in examining a voting system or component. The manufacturer or distributor who has submitted a voting system for testing under RCW 29A.12.030 shall pay the secretary of state a deposit to reimburse the cost of any contract for consultation under this section and for any other unrecoverable costs associated with the examination of a voting system or component by the manufacturer or distributor who submitted the voting system or component for examination.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20304[2003 c 111 § 304]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c59.pdf?cite=1990%20c%2059%20§%2020[1990 c 59 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c40.pdf?cite=1982%20c%2040%20§%203[1982 c 40 § 3]; ]

== 29A.12.050 - Approval required—Modification.
If voting systems or devices or vote tallying systems are to be used for conducting a primary or election, only those that have the approval of the secretary of state or had been approved under this chapter or the former chapter 29.34 RCW before March 22, 1982, may be used. Any modification, change, or improvement to any voting system or component of a system that does not impair its accuracy, efficiency, or capacity or extend its function, may be made without reexamination or reapproval by the secretary of state under RCW 29A.12.020.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20305[2003 c 111 § 305]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c59.pdf?cite=1990%20c%2059%20§%2021[1990 c 59 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c40.pdf?cite=1982%20c%2040%20§%204[1982 c 40 § 4]; ]

== 29A.12.060 - Maintenance and operation.
The county auditor of a county in which voting systems are used is responsible for the preparation, maintenance, and operation of those systems and may employ and direct persons to perform some or all of these functions.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20306[2003 c 111 § 306]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c59.pdf?cite=1990%20c%2059%20s%2022[1990 c 59 s 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c9.pdf?cite=1965%20c%209%20§%2029.33.130[1965 c 9 § 29.33.130]; prior:  1955 c 323 § 2; prior: 1935 c 85 § 1, part; 1919 c 163 § 23, part; 1915 c 114 § 5, part; 1913 c 58 § 10, part; RRS § 5309, part; ]

== 29A.12.070 - Acceptance and vulnerability tests.
An agreement to purchase or lease a voting system or a component of a voting system is subject to that system or component passing:

. An acceptance test sufficient to demonstrate that the equipment is the same as that certified by the secretary of state and that the equipment is operating correctly as delivered to the county; and

. A vulnerability test conducted by a federal or state public entity which includes participation by local elections officials.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1251-S.SL.pdf?cite=2020%20c%20101%20§%203[2020 c 101 § 3]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20307[2003 c 111 § 307]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6398.SL.pdf?cite=1998%20c%2058%20§%201[1998 c 58 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c59.pdf?cite=1990%20c%2059%20§%2023[1990 c 59 § 23]; ]

== 29A.12.080 - Requirements for approval.
No voting device shall be approved by the secretary of state unless it:

. Secures to the voter secrecy in the act of voting;

. Permits the voter to vote for any person for any office and upon any measure that he or she has the right to vote for;

. Correctly registers all votes cast for any and all persons and for or against any and all measures;

. Provides that a vote for more than one candidate cannot be cast by one single operation of the voting device or vote tally system except when voting for president and vice president of the United States; and

. Except for functions or capabilities unique to this state, has been tested and certified by an independent testing authority designated by the United States election assistance commission.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=2013%20c%2011%20§%2022[2013 c 11 § 22]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2479-S.SL.pdf?cite=2006%20c%20207%20§%202[2006 c 207 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20308[2003 c 111 § 308]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c59.pdf?cite=1990%20c%2059%20§%2026[1990 c 59 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c40.pdf?cite=1982%20c%2040%20§%206[1982 c 40 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c361.pdf?cite=1977%20ex.s.%20c%20361%20§%2066[1977 ex.s. c 361 § 66]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c6.pdf?cite=1971%20ex.s.%20c%206%20§%201[1971 ex.s. c 6 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c109.pdf?cite=1967%20ex.s.%20c%20109%20§%2018[1967 ex.s. c 109 § 18]; ]

== 29A.12.085 - Paper record.
Beginning on January 1, 2006, all direct recording electronic voting devices must produce a paper record of each vote that may be accepted or rejected by the voter before finalizing his or her vote. This record may not be removed from the voting center, and must be human readable without an interface and machine readable for counting purposes. If the device is programmed to display the ballot in multiple languages, the paper record produced must be printed in the language used by the voter. Rejected records must either be destroyed or marked in order to clearly identify the record as rejected. Paper records produced by direct recording electronic voting devices are subject to all the requirements of chapter 29A.60 RCW for ballot handling, preservation, reconciliation, transit, and storage. The paper records must be preserved in the same manner and for the same period of time as ballots.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5124-S.SL.pdf?cite=2011%20c%2010%20§%2022[2011 c 10 § 22]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5395-S.SL.pdf?cite=2005%20c%20242%20§%201[2005 c 242 § 1]; ]

== 29A.12.101 - Requirements of tallying systems for approval.
The secretary of state shall not approve a vote tallying system unless it:

. Correctly counts votes on ballots on which the proper number of votes have been marked for any office or issue;

. Ignores votes marked for any office or issue where more than the allowable number of votes have been marked, but correctly counts the properly voted portions of the ballot;

. Accumulates a count of the specific number of ballots tallied for each precinct, total votes by candidate for each office, and total votes for and against each issue of the ballot in that precinct;

. Produces precinct and cumulative totals in printed form; and

. Except for functions or capabilities unique to this state, has been tested and certified by an independent testing authority designated by the United States election assistance commission.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2479-S.SL.pdf?cite=2006%20c%20207%20§%203[2006 c 207 § 3]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6453.SL.pdf?cite=2004%20c%20271%20§%20109[2004 c 271 § 109]; ]

== 29A.12.110 - Record of programming—Devices sealed.
In preparing a voting device for a primary or election, a record shall be made of the programming installed in each device. Except where provided by a rule adopted under RCW 29A.04.611, after being prepared for a primary or election, each device shall be sealed with a uniquely numbered seal. The programmed memory pack for each voting device must be sealed into the device during final preparation and logic and accuracy testing. Except in the case of a device breakdown or error in programming, the memory pack must remain sealed in the device until after 8:00 p.m. on the day of the primary, special election, or general election.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5124-S.SL.pdf?cite=2011%20c%2010%20§%2023[2011 c 10 § 23]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20311[2003 c 111 § 311]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c59.pdf?cite=1990%20c%2059%20§%2025[1990 c 59 § 25]; ]

== 29A.12.120 - Counting center personnel—Instruction, requirements.
. Before each state primary or general election at which voting systems are to be used, the county auditor shall instruct all counting center personnel who will operate a voting system in the proper conduct of their voting system duties.

. The county auditor may waive instructional requirements for counting center personnel who have previously received instruction and who have served for a sufficient length of time to be fully qualified to perform their duties. The county auditor shall keep a record of each person who has received instruction and is qualified to serve at the subsequent primary or election.

. No person may operate a voting system in a counting center at a primary or election unless that person has received the required instruction and is qualified to perform his or her duties in connection with the handling and tallying of ballots for that primary or election.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=2013%20c%2011%20§%2023[2013 c 11 § 23]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5124-S.SL.pdf?cite=2011%20c%2010%20§%2024[2011 c 10 § 24]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20312[2003 c 111 § 312]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c59.pdf?cite=1990%20c%2059%20§%2029[1990 c 59 § 29]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c361.pdf?cite=1977%20ex.s.%20c%20361%20§%2069[1977 ex.s. c 361 § 69]; ]

== 29A.12.130 - Tallying systems—Programming tests.
At least three days before each state primary or general election, the office of the secretary of state shall provide for the conduct of tests of the programming for each vote tallying system to be used at that primary or general election. The test must verify that the system will correctly count the vote cast for all candidates and on all measures appearing on the ballot at that primary or general election. The test shall verify the capability of the vote tallying system to perform all of the functions that can reasonably be expected to occur during conduct of that particular primary or election. If any error is detected, the cause shall be determined and corrected, and an errorless total shall be produced before the primary or election.

Such tests shall be observed by at least one representative from each major political party, if representatives have been appointed by the respective major political parties and are present at the test, and shall be open to candidates, the press, and the public. The county auditor and any political party observers shall certify that the test has been conducted in accordance with this section. Copies of this certification shall be retained by the secretary of state and the county auditor. All programming materials, test results, and test ballots shall be securely sealed until the day of the primary or general election.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20313[2003 c 111 § 313]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6398.SL.pdf?cite=1998%20c%2058%20§%202[1998 c 58 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c59.pdf?cite=1990%20c%2059%20§%2032[1990 c 59 § 32]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c361.pdf?cite=1977%20ex.s.%20c%20361%20§%2073[1977 ex.s. c 361 § 73]; ]

== 29A.12.140 - Operating procedures.
The secretary of state may publish recommended procedures for the operation of the various vote tallying systems that have been approved. These procedures allow the office of the secretary of state to restrict or define the use of approved systems in elections.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20314[2003 c 111 § 314]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6398.SL.pdf?cite=1998%20c%2058%20§%203[1998 c 58 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c59.pdf?cite=1990%20c%2059%20§%2034[1990 c 59 § 34]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c361.pdf?cite=1977%20ex.s.%20c%20361%20§%2075[1977 ex.s. c 361 § 75]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c109.pdf?cite=1967%20ex.s.%20c%20109%20§%2032[1967 ex.s. c 109 § 32]; ]

== 29A.12.150 - Recording requirements.
The secretary of state shall not certify under this title any voting device or machine for use in conducting a primary or general or special election in this state unless the device or machine correctly records on a separate ballot the votes cast by each elector for any person and for or against any measure and such separate ballots are available for audit purposes after such a primary or election.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=2013%20c%2011%20§%2024[2013 c 11 § 24]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20315[2003 c 111 § 315]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6219.SL.pdf?cite=1998%20c%20245%20§%2026[1998 c 245 § 26]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1201-S.SL.pdf?cite=1991%20c%20363%20§%2030[1991 c 363 § 30]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c184.pdf?cite=1990%20c%20184%20§%201[1990 c 184 § 1]; ]

== 29A.12.160 - Blind or visually impaired voter accessibility.
. At each voting center, at least one voting unit certified by the secretary of state shall provide access to individuals who are blind or visually impaired.

. For purposes of this section, the following definitions apply:

.. "Accessible" includes receiving, using, selecting, and manipulating voter data and controls.

.. "Nonvisual" includes synthesized speech, Braille, and other output methods.

.. "Blind and visually impaired" excludes persons who are both deaf and blind.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5124-S.SL.pdf?cite=2011%20c%2010%20§%2025[2011 c 10 § 25]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6419-S.SL.pdf?cite=2004%20c%20267%20§%20701[2004 c 267 § 701]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6417.SL.pdf?cite=2004%20c%20266%20§%203[2004 c 266 § 3]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1222-S.SL.pdf?cite=2003%20c%20110%20§%201[2003 c 110 § 1]; ]

== 29A.12.180 - Disclosure of security breaches by manufacturer or distributor.
. A manufacturer or distributor of a voting system or component of a voting system that is certified by the secretary of state under RCW 29A.12.020 shall disclose to the secretary of state and attorney general any breach of the security of its system immediately following discovery of the breach if:

.. The breach has, or is reasonably likely to have, compromised the security, confidentiality, or integrity of an election in any state; or

.. Personal information of residents in any state was, or is reasonably believed to have been, acquired by an unauthorized person as a result of the breach and the personal information was not secured. For purposes of this subsection, "personal information" has the meaning given in RCW 19.255.010.

. Notification under subsection (1) of this section must be made in the most expedient time possible and without unreasonable delay.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2406-S.SL.pdf?cite=2018%20c%20218%20§%206[2018 c 218 § 6]; ]

== 29A.12.190 - Decertification.
. The secretary of state may decertify a voting system or any component of a voting system and withdraw authority for its future use or sale in the state if, at any time after certification, the secretary of state determines that:

.. The system or component fails to meet the standards set forth in applicable federal guidelines;

.. The system or component was materially misrepresented in the certification application;

.. The applicant has installed unauthorized modifications to the certified software or hardware; or

.. Any other reason authorized by rule adopted by the secretary of state.

. The secretary of state may decertify a voting system or any component of a voting system and withdraw authority for its future use or sale in the state if the manufacturer or distributor of the voting system or component thereof fails to comply with the notification requirements of RCW 29A.12.180.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2406-S.SL.pdf?cite=2018%20c%20218%20§%207[2018 c 218 § 7]; ]

== 29A.12.200 - Security breach identification and reporting.
. The secretary of state must annually consult with the Washington state fusion center, state chief information officer, and each county auditor to identify instances of security breaches of election systems or election data.

. To the extent possible, the secretary of state must identify whether the source of a security breach, if any, is a foreign entity, domestic entity, or both.

. By December 31st of each year, the secretary of state must submit a report to the governor, state chief information officer, Washington state fusion center, and the chairs and ranking members of the appropriate legislative committees from the senate and house of representatives that includes information on any instances of security breaches identified under subsection (1) of this section and options to increase the security of the election systems and election data, and to prevent future security breaches. The report, and any related material, data, or information provided pursuant to subsection (1) of this section or used to assemble the report, may only be distributed to, or otherwise shared with, the individuals specifically mentioned in this subsection (3).

. For the purposes of this section:

.. "Foreign entity" means an entity that is not organized or formed under the laws of the United States, or a person who is not domiciled in the United States or a citizen of the United States.

.. "Security breach" means a breach of the election system or associated data where the system or associated data has been penetrated, accessed, or manipulated by an unauthorized person.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1251-S.SL.pdf?cite=2020%20c%20101%20§%202[2020 c 101 § 2]; ]

