= 29A.08 - Voters and registration.
:toc:

== 29A.08.010 - Minimum information required for voter registration.
. The minimum information provided on a voter registration application that is required in order to place a voter registration applicant on the voter registration rolls includes:

.. Name;

.. Residential address;

.. Date of birth;

.. A signature attesting to the truth of the information provided on the application; and

.. A check or indication in the box confirming the individual is a United States citizen.

. The residential address provided must identify the actual physical residence of the voter in Washington, as defined in RCW 29A.04.151, with detail sufficient to allow the voter to be assigned to the proper precinct and to locate the voter to confirm his or her residence for purposes of verifying qualification to vote under Article VI, section 1 of the state Constitution. A residential address may be either a traditional address or a nontraditional address. A traditional address consists of a street number and name, optional apartment number or unit number, and city or town, as assigned by a local government, which serves to identify the parcel or building of residence and the unit if a multiunit residence. A nontraditional address consists of a narrative description of the location of the voter's residence, and may be used when a traditional address has not been assigned or affixed to the voter's residence or when a voter resides on an Indian reservation or Indian lands, pursuant to the conditions in RCW 29A.08.112.

. All other information supplied is ancillary and not to be used as grounds for not registering an applicant to vote.

. Modification of the language of the official Washington state voter registration form by the voter will not be accepted and will cause the rejection of the registrant's application.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5079-S.SL.pdf?cite=2019%20c%206%20§%201[2019 c 6 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=2009%20c%20369%20§%206[2009 c 369 § 6]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6362-S.SL.pdf?cite=2006%20c%20320%20§%202[2006 c 320 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5743-S.SL.pdf?cite=2005%20c%20246%20§%202[2005 c 246 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6419-S.SL.pdf?cite=2004%20c%20267%20§%20102[2004 c 267 § 102]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20201[2003 c 111 § 201]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6188-S.SL.pdf?cite=1994%20c%2057%20§%209[1994 c 57 § 9]; ]

== 29A.08.020 - Registration date.
Unless the context clearly requires otherwise, for voter registration applicants, the date the voter registration application is received by an election official will be used as the registration date for the purpose of registering and meeting the registration cutoff deadline.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5227.SL.pdf?cite=2019%20c%20391%20§%203[2019 c 391 § 3]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=2013%20c%2011%20§%2012[2013 c 11 § 12]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6419-S.SL.pdf?cite=2004%20c%20267%20§%20103[2004 c 267 § 103]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20204[2003 c 111 § 204]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6188-S.SL.pdf?cite=1994%20c%2057%20§%2030[1994 c 57 § 30]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5511-S2.SL.pdf?cite=1993%20c%20434%20§%201[1993 c 434 § 1]; ]

== 29A.08.030 - Notices, various.
The definitions set forth in this section apply throughout this chapter, unless the context clearly requires otherwise.

. "Verification notice" means a notice sent by the county auditor or secretary of state to a voter registration applicant and is used to verify or collect information about the applicant in order to complete the registration. The verification notice must be designed to include a postage prepaid, preaddressed return form by which the applicant may verify or send information.

. "Acknowledgment notice" means a notice sent by nonforwardable mail by the county auditor or secretary of state to a registered voter to acknowledge a voter registration transaction, which can include initial registration, transfer, or reactivation of an inactive registration. An acknowledgment notice may be a voter registration card.

. "Identification notice" means a notice sent to a provisionally registered voter to confirm the applicant's identity.

. "Confirmation notice" means a notice sent to a registered voter by first-class forwardable mail at the address indicated on the voter's permanent registration record and to any other address at which the county auditor or secretary of state could reasonably expect mail to be received by the voter in order to confirm the voter's residence address. The confirmation notice must be designed to include a postage prepaid, preaddressed return form by which the registrant may verify the address information.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=2009%20c%20369%20§%207[2009 c 369 § 7]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5743-S.SL.pdf?cite=2005%20c%20246%20§%203[2005 c 246 § 3]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6419-S.SL.pdf?cite=2004%20c%20267%20§%20104[2004 c 267 § 104]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20203[2003 c 111 § 203]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6188-S.SL.pdf?cite=1994%20c%2057%20§%2033[1994 c 57 § 33]; ]

== 29A.08.105 - Official list, secretary of state—County auditor.
. In compliance with the Help America Vote Act (P.L. 107-252), the centralized statewide voter registration list maintained by the secretary of state is the official list of eligible voters for all elections.

. In all counties, the county auditor shall be the chief registrar of voters for every precinct within the county.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=2009%20c%20369%20§%208[2009 c 369 § 8]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6419-S.SL.pdf?cite=2004%20c%20267%20§%20105[2004 c 267 § 105]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20205[2003 c 111 § 205]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1291-S.SL.pdf?cite=1999%20c%20298%20§%204[1999 c 298 § 4]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6188-S.SL.pdf?cite=1994%20c%2057%20§%208[1994 c 57 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c211.pdf?cite=1984%20c%20211%20§%203[1984 c 211 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c48.pdf?cite=1980%20c%2048%20§%201[1980 c 48 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c202.pdf?cite=1971%20ex.s.%20c%20202%20§%204[1971 ex.s. c 202 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c9.pdf?cite=1965%20c%209%20§%2029.07.010[1965 c 9 § 29.07.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c251.pdf?cite=1957%20c%20251%20§%204[1957 c 251 § 4]; prior: 1939 c 15 § 1, part; 1933 c 1 § 3, part; RRS § 5114-3, part; prior: 1891 c 104 §§ 1, part, 2, part; RRS §§ 5116, part, 5117, part; ]

== 29A.08.107 - Applicant information for registration—Provisional registration—Exception.
. If the driver's license number, state identification card number, or last four digits of the social security number provided by the applicant match the information maintained by the Washington department of licensing or the social security administration, and the applicant provided all information required by RCW 29A.08.010, the applicant must be registered to vote. 

. If the driver's license number, state identification card number, or last four digits of the social security number provided by the applicant do not match the information maintained by the Washington department of licensing or the social security administration, or if the applicant does not provide a Washington driver's license, a Washington state identification card, or a social security number, the applicant must be provisionally registered to vote. An identification notice must be sent to the voter to obtain the correct driver's license number, state identification card number, last four digits of the social security number, or one of the following forms of alternate identification:

.. Valid photo identification;

.. A valid enrollment card of a federally recognized Indian tribe in Washington state;

.. A copy of a current utility bill;

.. A current bank statement;

.. A copy of a current government check;

.. A copy of a current paycheck; or

.. A government document, other than a voter registration card, that shows both the name and address of the voter.

. The ballot of a provisionally registered voter may not be counted until the voter provides a driver's license number, a state identification card number, or the last four digits of a social security number that matches the information maintained by the Washington department of licensing or the social security administration, or until the voter provides alternate identification. The identification must be provided no later than the day before certification of the primary or election. If the voter provides one of the forms of identification in subsection (2) of this section, the voter's registration status must be changed from provisionally registered to registered.

. A provisional registration must remain on the official list of registered voters through at least two general elections for federal office. If, after two general elections for federal office, the voter still has not verified his or her identity, the provisional registration may be canceled.

. The requirements of this section do not apply to an overseas or service voter who registers to vote by signing the return envelope of an absentee ballot, or to a registered voter transferring his or her registration.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=2009%20c%20369%20§%209[2009 c 369 § 9]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5743-S.SL.pdf?cite=2005%20c%20246%20§%204[2005 c 246 § 4]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6419-S.SL.pdf?cite=2004%20c%20267%20§%20106[2004 c 267 § 106]; ]

== 29A.08.110 - Auditor's procedure. (Effective until January 1, 2022.)
. For persons registering under RCW 29A.08.120, 29A.08.123, 29A.08.170, 29A.08.330, 29A.08.340, 29A.08.362, and 29A.08.365, an application is considered complete only if it contains the information required by RCW 29A.08.010. The applicant is considered to be registered to vote as of the original date of receipt, or when the person will be at least eighteen years old by the next election, whichever is applicable. As soon as practicable, the auditor shall record the appropriate precinct identification, taxing district identification, and date of registration on the voter's record in the state voter registration list. The secretary of state shall, pursuant to RCW 29A.04.611, establish procedures to enable new or updated voter registrations to be recorded on an expedited basis. Any mailing address provided shall be used only for mail delivery purposes, and not for precinct assignment or residency purposes. Within sixty days after the receipt of an application or transfer, the auditor shall send to the applicant, by first-class nonforwardable mail, an acknowledgment notice identifying the registrant's precinct and containing such other information as may be required by the secretary of state. The postal service shall be instructed not to forward a voter registration card to any other address and to return to the auditor any card which is not deliverable.

. If an application is not complete, the auditor shall promptly mail a verification notice to the applicant. The verification notice shall require the applicant to provide the missing information. If the applicant provides the required information within forty-five days, the applicant shall be registered to vote as of the original date of application. The applicant shall not be placed on the official list of registered voters until the application is complete.

. Once a future voter is no longer in pending status, as described in RCW 29A.08.615, his or her application to sign up to register to vote is no longer pending and is subject to this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5227.SL.pdf?cite=2019%20c%20391%20§%205[2019 c 391 § 5]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6021-S.SL.pdf?cite=2018%20c%20112%20§%202[2018 c 112 § 2]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2595-S2.SL.pdf?cite=2018%20c%20110%20§%20101[2018 c 110 § 101]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1513-S2.SL.pdf?cite=2018%20c%20109%20§%204[2018 c 109 § 4]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=2009%20c%20369%20§%2010[2009 c 369 § 10]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5743-S.SL.pdf?cite=2005%20c%20246%20§%205[2005 c 246 § 5]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6419-S.SL.pdf?cite=2004%20c%20267%20§%20107[2004 c 267 § 107]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20206[2003 c 111 § 206]; prior:  1994 c 57 § 32; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5511-S2.SL.pdf?cite=1993%20c%20434%20§%206[1993 c 434 § 6]; ]

== 29A.08.112 - Voters without traditional residential addresses.
. No person registering to vote, who meets all the qualifications of a registered voter in the state of Washington, shall be disqualified because he or she lacks a traditional residential address. A voter who lacks a traditional residential address will be registered and assigned to a precinct based on the location provided.

. For the purposes of this section, a voter who resides in a shelter, park, motor home, marina, unmarked home, or other identifiable location that the voter deems to be his or her residence lacks a traditional address. A voter who registers under this section must provide a valid mailing address, and must still meet the requirement in Article VI, section 1 of the state Constitution that he or she live in the area for at least thirty days before the election.

. A nontraditional residential address may be used when a voter resides on an Indian reservation or on Indian lands.

. A federally recognized tribe may designate one or more tribal government buildings to serve as a residential address or mailing address or both for voters living on an Indian reservation or on Indian lands. However, a voter may not use a tribally designated building as the voter's residential address if the building is in a different precinct than where the voter lives.

. A person who has a traditional residential address and does not reside on an Indian reservation or on Indian lands must use that address for voter registration purposes and is not eligible to register under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5079-S.SL.pdf?cite=2019%20c%206%20§%202[2019 c 6 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6362-S.SL.pdf?cite=2006%20c%20320%20§%203[2006 c 320 § 3]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5743-S.SL.pdf?cite=2005%20c%20246%20§%206[2005 c 246 § 6]; ]

== 29A.08.115 - Registration by other than auditor or secretary of state.
A person or organization collecting voter registration application forms must transmit the forms to the secretary of state or a county auditor within five business days. The registration date on such forms will be the date they are received by the secretary of state or county auditor.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=2009%20c%20369%20§%2011[2009 c 369 § 11]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5743-S.SL.pdf?cite=2005%20c%20246%20§%208[2005 c 246 § 8]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6419-S.SL.pdf?cite=2004%20c%20267%20§%20108[2004 c 267 § 108]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20207[2003 c 111 § 207]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c202.pdf?cite=1971%20ex.s.%20c%20202%20§%2015[1971 ex.s. c 202 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c9.pdf?cite=1965%20c%209%20§%2029.07.110[1965 c 9 § 29.07.110]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c251.pdf?cite=1957%20c%20251%20§%2011[1957 c 251 § 11]; prior: 1947 c 68 § 1, part; 1945 c 95 § 1, part; 1933 c 1 § 6, part; Rem. Supp. 1947 § 5114-6, part; prior: 1919 c 163 § 6, part; 1915 c 16 § 6, part; 1901 c 135 § 5, part; 1893 c 45 § 1, part; 1889 p 415 § 6, part; RRS § 5124, part; ]

== 29A.08.120 - Registration by mail.
Any elector of this state may register to vote by mail under this title.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6419-S.SL.pdf?cite=2004%20c%20267%20§%20109[2004 c 267 § 109]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20208[2003 c 111 § 208]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5511-S2.SL.pdf?cite=1993%20c%20434%20§%203[1993 c 434 § 3]; ]

== 29A.08.123 - Registration electronically.
. A person who has a valid Washington state driver's license, state identification card, or tribal identification may submit a voter registration application electronically on the secretary of state's website. A person who has a valid tribal identification card may submit a voter registration electronically on the secretary of state's website if the secretary of state is able to obtain a copy of the applicant's signature from the federal government or the tribal government.

. The applicant must attest to the truth of the information provided on the application by affirmatively accepting the information as true.

. The applicant must affirmatively assent to use of his or her driver's license, state identification card, or tribal identification card signature for voter registration purposes.

. A voter registration application submitted electronically is otherwise considered a registration by mail.

. For each electronic application, the secretary of state must obtain a digital copy of the applicant's driver's license or state identification card signature from the department of licensing or tribal identification issuing authority.

. The secretary of state may employ additional security measures to ensure the accuracy and integrity of voter registration applications submitted electronically.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5079-S.SL.pdf?cite=2019%20c%206%20§%203[2019 c 6 § 3]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1528.SL.pdf?cite=2007%20c%20157%20§%201[2007 c 157 § 1]; ]

== 29A.08.125 - Database of voter registration records.
. The office of the secretary of state shall maintain a statewide voter registration database. This database must be a centralized, uniform, interactive computerized statewide voter registration list that contains the name and registration information of every registered voter in the state.

. The statewide list is the official list of registered voters for the conduct of all elections.

. The statewide list must include, but is not limited to, the name, date of birth, residence address, signature, gender, and date of registration of every legally registered voter in the state.

. A unique identifier must be assigned to each registered voter in the state.

. The database must be coordinated with other government databases within the state including, but not limited to, the department of corrections, the department of licensing, the department of health, the administrative office of the courts, and county auditors. The database may also be coordinated with the databases of election officials in other states.

. Authorized employees of the secretary of state and each county auditor must have immediate electronic access to the information maintained in the database.

. Voter registration information received by each county auditor must be electronically entered into the database. The office of the secretary of state must provide support, as needed, to enable each county auditor to enter and maintain voter registration information in the state database.

. The secretary of state has data authority over all voter registration data.

. The voter registration database must be designed to accomplish at a minimum, the following:

.. Comply with the help America vote act of 2002 (P.L. 107-252);

.. Identify duplicate voter registrations;

.. Identify suspected duplicate voters;

.. Screen against any available databases maintained by other government agencies to identify voters who are ineligible to vote due to a felony conviction, lack of citizenship, or mental incompetence;

.. Provide images of voters' signatures for the purpose of checking signatures on initiative and referendum petitions;

.. Provide for a comparison between the voter registration database and the department of licensing change of address database;

.. Provide access for county auditors that includes the capability to update registrations and search for duplicate registrations;

.. Provide for the cancellation of registrations of voters who have moved out of state; and

.. Provide for the storage of pending registration records for all future voters who have not yet reached eighteen years of age in a manner that these records will not appear on the official list of registered voters until the future registrant is no longer in pending status as defined under RCW 29A.08.615.

. The secretary of state may, upon agreement with other appropriate jurisdictions, screen against any available databases maintained by election officials in other states and databases maintained by federal agencies including, but not limited to, the federal bureau of investigation, the federal court system, the federal bureau of prisons, and the bureau of citizenship and immigration services.

. The database shall retain information regarding previous successful appeals of proposed cancellations of registrations in order to avoid repeated cancellations for the same reason.

. Each county auditor shall maintain a list of all registered voters within the county that are contained on the official statewide voter registration list. In addition to the information maintained in the statewide database, the county database must also maintain the applicable taxing district and precinct codes for each voter in the county, and a list of elections in which the individual voted.

. Each county auditor shall allow electronic access and information transfer between the county's voter registration system and the official statewide voter registration list.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1513-S2.SL.pdf?cite=2018%20c%20109%20§%207[2018 c 109 § 7]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=2009%20c%20369%20§%2012[2009 c 369 § 12]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5743-S.SL.pdf?cite=2005%20c%20246%20§%209[2005 c 246 § 9]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6419-S.SL.pdf?cite=2004%20c%20267%20§%20110[2004 c 267 § 110]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20209[2003 c 111 § 209]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1084-S.SL.pdf?cite=1993%20c%20408%20§%2011[1993 c 408 § 11]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1072.SL.pdf?cite=1991%20c%2081%20§%2022[1991 c 81 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c127.pdf?cite=1974%20ex.s.%20c%20127%20§%2012[1974 ex.s. c 127 § 12]; ]

== 29A.08.130 - Count of registered voters—Inactive voters.
Election officials shall not include inactive voters in the count of registered voters for the purpose of dividing precincts, determining voter turnout, or other purposes in law for which the determining factor is the number of registered voters.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5124-S.SL.pdf?cite=2011%20c%2010%20§%2014[2011 c 10 § 14]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=2009%20c%20369%20§%2013[2009 c 369 § 13]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20210[2003 c 111 § 210]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6188-S.SL.pdf?cite=1994%20c%2057%20§%2040[1994 c 57 § 40]; ]

== 29A.08.135 - Updating information.
. When a person who has previously registered to vote in another state applies for voter registration in Washington, the person shall provide on the registration form all information needed to cancel any previous registration. Notification must be made to the state elections office of the applicant's previous state of registration.

. A county auditor receiving official information that a voter has registered to vote in another state shall immediately cancel that voter's registration on the official state voter registration list.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=2009%20c%20369%20§%2014[2009 c 369 § 14]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6419-S.SL.pdf?cite=2004%20c%20267%20§%20111[2004 c 267 § 111]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20211[2003 c 111 § 211]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1739-S.SL.pdf?cite=2001%20c%2041%20§%206[2001 c 41 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c184.pdf?cite=1975%201st%20ex.s.%20c%20184%20§%201[1975 1st ex.s. c 184 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c153.pdf?cite=1973%20c%20153%20§%202[1973 c 153 § 2]; ]

== 29A.08.140 - Voter registration deadlines.
. In order to vote in any primary, special election, or general election, a person who is not registered to vote in Washington must:

.. Submit a registration application that is received by an election official no later than eight days before the day of the primary, special election, or general election. For purposes of this subsection (1)(a), "received" means: (i) Being physically received by an election official by the close of business of the required deadline; or (ii) for applications received online or electronically, by midnight, of the required deadline; or

.. Register in person at a county auditor's office, the division of elections if in a separate city from the county auditor's office, a voting center, a student engagement hub, or other location designated by the county auditor no later than 8:00 p.m. on the day of the primary, special election, or general election.

. [Empty]
.. In order to change a residence address for voting in any primary, special election, or general election, a person who is already registered to vote in Washington may update his or her registration by:

... Submitting an address change using a registration application or making notification via any non-in-person method that is received by election officials no later than eight days before the day of the primary, special election, or general election; or

... Appearing in person, at a county auditor's office, the division of elections if in a separate city from the county auditor's office, a voting center, or other location designated by the county auditor, no later than 8:00 p.m. on the day of the primary, special election, or general election to be in effect for that primary, special election, or general election.

.. A registered voter who fails to update his or her residential address by this deadline may vote according to his or her previous registration address.

. To register or update a voting address in person at a county auditor's office, a voting center, or other location designated by the county auditor, a person must appear in person at a county auditor's office, a voting center, or other location designated by the county auditor at a time when the facility is open and complete the voter registration application by providing the information required by RCW 29A.08.010.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6313.SL.pdf?cite=2020%20c%20208%20§%2022[2020 c 208 § 22]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5227.SL.pdf?cite=2019%20c%20391%20§%204[2019 c 391 § 4]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6021-S.SL.pdf?cite=2018%20c%20112%20§%201[2018 c 112 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5124-S.SL.pdf?cite=2011%20c%2010%20§%2015[2011 c 10 § 15]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=2009%20c%20369%20§%2015[2009 c 369 § 15]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/3041.SL.pdf?cite=2006%20c%2097%20§%201[2006 c 97 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6419-S.SL.pdf?cite=2004%20c%20267%20§%20112[2004 c 267 § 112]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20212[2003 c 111 § 212]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1648.SL.pdf?cite=1993%20c%20383%20§%202[1993 c 383 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c3.pdf?cite=1980%20c%203%20§%204[1980 c 3 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c127.pdf?cite=1974%20ex.s.%20c%20127%20§%204[1974 ex.s. c 127 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c202.pdf?cite=1971%20ex.s.%20c%20202%20§%2020[1971 ex.s. c 202 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c9.pdf?cite=1965%20c%209%20§%2029.07.160[1965 c 9 § 29.07.160]; prior:  1947 c 68 § 2; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c1.pdf?cite=1933%20c%201%20§%209[1933 c 1 § 9]; Rem. Supp. 1947 § 5114-9; ]

== 29A.08.150 - Expense of registration.
The expense of registration in all rural precincts must be paid by the county. The expense of registration in all precincts lying wholly within a city or town must be paid by the city or town. Registration expenses for this section include both active and inactive voters.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20214[2003 c 111 § 214]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c9.pdf?cite=1965%20c%209%20§%2029.07.030[1965 c 9 § 29.07.030]; 1939 c 82 § 1, part; 1933 c 1 § 4, part; RRS § 5114-4, part; prior:  1891 c 104 § 4; RRS § 5119; ]

== 29A.08.161 - No link between voter and ballot choice—Exception.
No record may be created or maintained by a state or local governmental agency or a political organization that identifies a voter with the information marked on the voter's ballot, except the declarations made under RCW 29A.56.050(2).

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5273.SL.pdf?cite=2019%20c%207%20§%206[2019 c 7 § 6]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6453.SL.pdf?cite=2004%20c%20271%20§%20107[2004 c 271 § 107]; ]

== 29A.08.166 - Party affiliation not required.
Under no circumstances may an individual be required to affiliate with, join, adhere to, express faith in, or declare a preference for, a political party or organization upon registering to vote.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6453.SL.pdf?cite=2004%20c%20271%20§%20108[2004 c 271 § 108]; ]

== 29A.08.170 - Registration at age sixteen and seventeen. (Effective until January 1, 2022.)
. A person may sign up to register to vote if he or she is sixteen or seventeen years of age, as part of the future voter program.

. A person who signs up to register to vote may not vote until reaching eighteen years of age, and his or her name may not be added to the statewide voter registration database list of voters until such time as he or she will be eighteen years of age by the next election.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1513-S2.SL.pdf?cite=2018%20c%20109%20§%205[2018 c 109 § 5]; ]

== 29A.08.172 - Registration at age sixteen and seventeen—Application by mail. (Effective until January 1, 2022.)
. A person who has attained sixteen years of age may sign up to register to vote, as part of the future voter program, by submitting a voter registration application by mail.

. The applicant must attest to the truth of the information provided on the application by affirmatively accepting the information as true.

. If signing up to register by mail, the person must provide a signature for voter registration purposes.

. The applicant must affirmatively acknowledge that he or she will not vote until his or her eighteenth birthday.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1513-S2.SL.pdf?cite=2018%20c%20109%20§%206[2018 c 109 § 6]; ]

== 29A.08.174 - Registration at age sixteen and seventeen—Application electronically. (Effective until January 1, 2022.)
. A person who has attained sixteen years of age and has a valid Washington state driver's license or identicard may sign up to register to vote as part of the future voter program, by submitting a voter registration application electronically on the secretary of state's website.

. The applicant must attest to the truth of the information provided on the application by affirmatively accepting the information as true.

. If signing up to register electronically, the applicant must affirmatively assent to the use of his or her driver's license or identicard signature for voter registration purposes.

. The applicant must affirmatively acknowledge that he or she will not vote until his or her eighteenth birthday.

. For each electronic registration application, the secretary of state must obtain a digital copy of the applicant's driver's license or identicard signature from the department of licensing.

. The secretary of state may employ additional security measures to ensure the accuracy and integrity of voter preregistration applications submitted electronically.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1513-S2.SL.pdf?cite=2018%20c%20109%20§%2014[2018 c 109 § 14]; ]

== 29A.08.210 - Application—Contents. (Effective until January 1, 2022.)
An applicant for voter registration shall complete an application providing the following information concerning his or her qualifications as a voter in this state:

. The former address of the applicant if previously registered to vote;

. The applicant's full name;

. The applicant's date of birth;

. The address of the applicant's residence for voting purposes;

. The mailing address of the applicant if that address is not the same as the address in subsection (4) of this section;

. The sex of the applicant;

. The applicant's Washington state driver's license number, Washington state identification card number, or the last four digits of the applicant's social security number if he or she does not have a Washington state driver's license or Washington state identification card;

. A check box allowing the applicant to indicate that he or she is a member of the armed forces, national guard, or reserves, or that he or she is an overseas voter;

. A check box allowing the applicant to acknowledge that he or she is at least eighteen years old or is at least sixteen years old and will vote only after he or she reaches the age of eighteen;

. Clear and conspicuous language, designed to draw the applicant's attention, stating that the applicant must be a United States citizen in order to register to vote;

. A check box and declaration confirming that the applicant is a citizen of the United States;

. The following warning:

"If you knowingly provide false information on this voter registration form or knowingly make a false declaration about your qualifications for voter registration you will have committed a class C felony that is punishable by imprisonment for up to five years, a fine of up to ten thousand dollars, or both."

. The oath required by RCW 29A.08.230 and a space for the applicant's signature; and

. Any other information that the secretary of state determines is necessary to establish the identity of the applicant and prevent duplicate or fraudulent voter registrations.

This information shall be recorded on a single registration form to be prescribed by the secretary of state.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1513-S2.SL.pdf?cite=2018%20c%20109%20§%208[2018 c 109 § 8]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=2009%20c%20369%20§%2016[2009 c 369 § 16]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5743-S.SL.pdf?cite=2005%20c%20246%20§%2011[2005 c 246 § 11]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20216[2003 c 111 § 216]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6188-S.SL.pdf?cite=1994%20c%2057%20§%2011[1994 c 57 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c143.pdf?cite=1990%20c%20143%20§%207[1990 c 143 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c21.pdf?cite=1973%201st%20ex.s.%20c%2021%20§%203[1973 1st ex.s. c 21 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c202.pdf?cite=1971%20ex.s.%20c%20202%20§%209[1971 ex.s. c 202 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c9.pdf?cite=1965%20c%209%20§%2029.07.070[1965 c 9 § 29.07.070]; 1947 c 68 § 3, part; 1933 c 1 § 11, part; Rem. Supp. 1947 § 5114-11, part; prior: 1921 c 177 § 7, part; 1915 c 16 § 8, part; 1901 c 135 § 4, part; 1893 c 45 § 3, part; 1889 p 416 § 8, part; RRS § 5126, part; ]

== 29A.08.220 - Application—Format.
. The secretary of state shall specify by rule the format of all voter registration applications. These applications shall be compatible with existing voter registration records. An applicant for voter registration shall be required to complete only one application and to provide the required information other than his or her signature no more than one time. These applications shall also contain information for the voter to update his or her registration.

. Any application format specified by the secretary for use in registering to vote in state and local elections shall satisfy the requirements of the National Voter Registration Act of 1993 (P.L. 103-31) and the Help America Vote Act of 2002 (P.L. 107-252) for registering to vote in federal elections.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=2013%20c%2011%20§%2013[2013 c 11 § 13]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6419-S.SL.pdf?cite=2004%20c%20267%20§%20115[2004 c 267 § 115]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20217[2003 c 111 § 217]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6188-S.SL.pdf?cite=1994%20c%2057%20§%2018[1994 c 57 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c143.pdf?cite=1990%20c%20143%20§%209[1990 c 143 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c21.pdf?cite=1973%201st%20ex.s.%20c%2021%20§%207[1973 1st ex.s. c 21 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c202.pdf?cite=1971%20ex.s.%20c%20202%20§%2018[1971 ex.s. c 202 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c9.pdf?cite=1965%20c%209%20§%2029.07.140[1965 c 9 § 29.07.140]; prior:   1933 c 1 § 30; RRS § 5114-30.  1933 c 1 § 13, part; RRS § 5114-13, part; ]

== 29A.08.230 - Oath of applicant. (Effective until January 1, 2022.)
For all voter registrations, the registrant shall sign the following oath:

"I declare that the facts on this voter registration form are true. I am a citizen of the United States, I will have lived at this address in Washington for at least thirty days immediately before the next election at which I vote, I am at least sixteen years old, I am not disqualified from voting due to a court order, and I am not under department of corrections supervision for a Washington felony conviction."

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6313.SL.pdf?cite=2020%20c%20208%20§%204[2020 c 208 § 4]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=2013%20c%2011%20§%2014[2013 c 11 § 14]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=2009%20c%20369%20§%2017[2009 c 369 § 17]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20218[2003 c 111 § 218]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6188-S.SL.pdf?cite=1994%20c%2057%20§%2012[1994 c 57 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c143.pdf?cite=1990%20c%20143%20§%208[1990 c 143 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c21.pdf?cite=1973%201st%20ex.s.%20c%2021%20§%204[1973 1st ex.s. c 21 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c202.pdf?cite=1971%20ex.s.%20c%20202%20§%2010[1971 ex.s. c 202 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c9.pdf?cite=1965%20c%209%20§%2029.07.080[1965 c 9 § 29.07.080]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c1.pdf?cite=1933%20c%201%20§%2012[1933 c 1 § 12]; RRS § 5114-12; ]

== 29A.08.260 - Production, supply, and distribution.
. All registration applications required under RCW 29A.08.210 and 29A.08.340 shall be produced and furnished by the secretary of state to the county auditors and the department of licensing.

. The county auditor shall distribute forms by which a person may register to vote by mail and transfer any previous registration in this state. The county auditor shall keep a supply of voter registration forms in his or her office at all times for political parties and others interested in assisting in voter registration, and shall make every effort to make these forms generally available to the public. The county auditor shall provide voter registration forms to city and town clerks, state offices, schools, fire stations, public libraries, and any other locations considered appropriate by the auditor or secretary of state for extending registration opportunities to all areas of the county. After the initial distribution of voter registration forms to a given location, a representative designated by the official in charge of that location shall notify the county auditor of the need for additional voter registration supplies.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=2013%20c%2011%20§%2015[2013 c 11 § 15]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=2009%20c%20369%20§%2018[2009 c 369 § 18]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6419-S.SL.pdf?cite=2004%20c%20267%20§%20118[2004 c 267 § 118]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20221[2003 c 111 § 221]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5511-S2.SL.pdf?cite=1993%20c%20434%20§%204[1993 c 434 § 4]; ]

== 29A.08.270 - Information in foreign languages.
In order to encourage the broadest possible voting participation by all eligible citizens, the secretary of state shall produce voter registration information in the foreign languages required of state agencies.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20139[2003 c 111 § 139]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1739-S.SL.pdf?cite=2001%20c%2041%20§%203[2001 c 41 § 3]; ]

== 29A.08.310 - Voter registration in state offices, facilities, colleges.
. The governor, in consultation with the secretary of state, shall designate agencies to provide voter registration services in compliance with federal statutes.

. A federally recognized tribe may request that the governor designate one or more state facilities or state-funded facilities or programs that are located on the lands of the requesting Indian tribe or that are substantially engaged in providing services to Indian tribes, as selected by the tribe, to provide voter registration services. This provision does not alter the state's obligations under the national voter registration act.

. Each state agency designated shall provide voter registration services for employees and the public within each office of that agency.

. The secretary of state shall design and provide a standard notice informing the public of the availability of voter registration, which notice shall be posted in each state agency where such services are available.

. Each institution of higher education shall put in place an active prompt on its course registration website, or similar website that students actively and regularly use, that, if selected, will link the student to the secretary of state's voter registration website. The prompt must ask the student if he or she wishes to register to vote.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5079-S.SL.pdf?cite=2019%20c%206%20§%204[2019 c 6 § 4]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=2009%20c%20369%20§%2019[2009 c 369 § 19]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20222[2003 c 111 § 222]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2332.SL.pdf?cite=2002%20c%20185%20§%203[2002 c 185 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6188-S.SL.pdf?cite=1994%20c%2057%20§%2010[1994 c 57 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c211.pdf?cite=1984%20c%20211%20§%202[1984 c 211 § 2]; ]

== 29A.08.320 - Registration or transfer at designated agencies—Form and application.
. A person may register to vote or transfer a voter registration when he or she applies for service or assistance and with each renewal, recertification, or change of address at agencies designated under RCW 29A.08.310.

. A prospective applicant shall initially be offered a form approved by the secretary of state designed to determine whether the person wishes to register to vote. The form must comply with all applicable state and federal statutes regarding content.

The form shall also contain a box that may be checked by the applicant to indicate that he or she declines to register.

If the person indicates an interest in registering or has made no indication as to a desire to register or not register to vote, the person shall be given a mail-in voter registration application or a prescribed agency application as provided by RCW 29A.08.330.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6419-S.SL.pdf?cite=2004%20c%20267%20§%20119[2004 c 267 § 119]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6417.SL.pdf?cite=2004%20c%20266%20§%207[2004 c 266 § 7]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20223[2003 c 111 § 223]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6188-S.SL.pdf?cite=1994%20c%2057%20§%2027[1994 c 57 § 27]; ]

== 29A.08.330 - Registration at designated agencies—Procedures. (Effective until January 1, 2022.)
. The secretary of state shall prescribe the method of voter registration for each designated agency. The agency shall use either the state voter registration by mail form with a separate declination form for the applicant to indicate that he or she declines to register at this time, or the agency may use a separate form approved for use by the secretary of state.

. The person providing service at the agency shall offer voter registration services to every client whenever he or she applies for service or assistance and with each renewal, recertification, or change of address. The person providing service shall give the applicant the same level of assistance with the voter registration application as is offered to fill out the agency's forms and documents, including information about age and citizenship requirements for voter registration.

. The person providing service at the agency shall determine if the prospective applicant wants to register to vote or update his or her voter registration by asking the following question:

"Do you want to register or sign up to vote or update your voter registration?"

If the applicant chooses to register, sign up, or update a registration, the service agent shall ask the following:

.. "Are you a United States citizen?"

.. "Are you at least eighteen years old or are you at least sixteen years old and will you vote only after you turn eighteen?"

If the applicant answers in the affirmative to both questions, the agent shall then provide the applicant with a voter registration form and instructions and shall record that the applicant has requested to sign up to vote, register to vote, or update a voter registration. If the applicant answers in the negative to either question, the agent shall not provide the applicant with a voter registration application.

. If an agency uses a computerized application process, it may, in consultation with the secretary of state, develop methods to capture simultaneously the information required for voter registration during a person's computerized application process.

. Each designated agency shall transmit the applications to the secretary of state or appropriate county auditor within three business days and must be received by the election official by the required voter registration deadline.

. Information that is otherwise disclosable under this chapter cannot be disclosed on the future voter until the person reaches eighteen years of age, except for the purpose of processing and delivering ballots.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5227.SL.pdf?cite=2019%20c%20391%20§%206[2019 c 391 § 6]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1513-S2.SL.pdf?cite=2018%20c%20109%20§%2018[2018 c 109 § 18]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=2013%20c%2011%20§%2016[2013 c 11 § 16]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=2009%20c%20369%20§%2020[2009 c 369 § 20]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5743-S.SL.pdf?cite=2005%20c%20246%20§%2014[2005 c 246 § 14]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20224[2003 c 111 § 224]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1739-S.SL.pdf?cite=2001%20c%2041%20§%207[2001 c 41 § 7]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6188-S.SL.pdf?cite=1994%20c%2057%20§%2028[1994 c 57 § 28]; ]

== 29A.08.340 - Registration or update of registration with driver's license or identification card application or renewal.
. A person may register to vote or update his or her voter registration when he or she applies for or renews a driver's license or identification card under chapter 46.20 RCW.

. To register to vote or update a registration, the applicant shall provide the information required by RCW 29A.08.010.

. The driver licensing agent shall record that the applicant has requested to register to vote or update a voter registration.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=2013%20c%2011%20§%2017[2013 c 11 § 17]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20225[2003 c 111 § 225]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1739-S.SL.pdf?cite=2001%20c%2041%20§%2016[2001 c 41 § 16]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1291-S.SL.pdf?cite=1999%20c%20298%20§%206[1999 c 298 § 6]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6188-S.SL.pdf?cite=1994%20c%2057%20§%2021[1994 c 57 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c143.pdf?cite=1990%20c%20143%20§%201[1990 c 143 § 1]; ]

== 29A.08.350 - Duties of department of licensing, secretary of state.
The department of licensing shall produce and transmit to the secretary of state the following information from the records of each individual who requested a voter registration or update at a driver's license facility: The name, address, date of birth, gender of the applicant, the driver's license number, signature image, and the date on which the application for voter registration or update was submitted. The secretary of state shall process the registrations and updates as an electronic application.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2595-S2.SL.pdf?cite=2018%20c%20110%20§%20106[2018 c 110 § 106]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=2013%20c%2011%20§%2018[2013 c 11 § 18]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=2009%20c%20369%20§%2021[2009 c 369 § 21]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6419-S.SL.pdf?cite=2004%20c%20267%20§%20120[2004 c 267 § 120]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20226[2003 c 111 § 226]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6188-S.SL.pdf?cite=1994%20c%2057%20§%2022[1994 c 57 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c143.pdf?cite=1990%20c%20143%20§%202[1990 c 143 § 2]; ]

== 29A.08.355 - Automatic registration—Enhanced driver's licenses and identicards. (Effective until September 1, 2023.)
The department of licensing shall implement an automatic voter registration system so that a person age eighteen years or older who meets requirements for voter registration and has received or is renewing an enhanced driver's license or identicard issued under RCW 46.20.202 or is changing the address for an existing enhanced driver's license or identicard pursuant to RCW 46.20.205 may be registered to vote or update voter registration information at the time of registration, renewal, or change of address, by automated process if the department of licensing record associated with the applicant contains the data required to determine whether the applicant meets requirements for voter registration under RCW 29A.08.010, other information as required by the secretary of state, and includes a signature image. The person must be informed that his or her record will be used for voter registration and offered an opportunity to decline to register.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2595-S2.SL.pdf?cite=2018%20c%20110%20§%20102[2018 c 110 § 102]; ]

== 29A.08.357 - Automatic registration—Enhanced driver's licenses and identicards—Application submission.
. If the applicant in RCW 29A.08.355 does not decline registration, the application is submitted pursuant to RCW 29A.08.350.

. For each such application, the secretary of state must obtain a digital copy of the applicant's signature image from the department of licensing.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2595-S2.SL.pdf?cite=2018%20c%20110%20§%20103[2018 c 110 § 103]; ]

== 29A.08.359 - Automatic registration—Enhanced driver's licenses and identicards—Procedure—Auditor duties—Confidentiality. (Effective until September 1, 2023.)
. [Empty]
.. For persons age eighteen years and older registering under RCW 29A.08.355, an application is considered complete only if it contains the information required by RCW 29A.08.010 and other information as required by the secretary of state. The applicant is considered to be registered to vote as of the original date of issuance or renewal or date of change of address of an enhanced driver's license or identicard issued under RCW 46.20.202 or change of address for an existing enhanced driver's license or identicard pursuant to RCW 46.20.205. The information must be transmitted in an expedited manner and must be received by an election official by the required voter registration deadline. The auditor shall record the appropriate precinct identification, taxing district identification, and date of registration on the voter's record in the state voter registration list. Any mailing address provided shall be used only for mail delivery purposes, and not for precinct assignment or residency purposes. Within sixty days after the receipt of an application or transfer, the auditor shall send to the applicant, by first-class nonforwardable mail, an acknowledgment notice identifying the registrant's precinct and containing such other information as may be required by the secretary of state. The United States postal service shall be instructed not to forward a voter registration card to any other address and to return to the auditor any card which is not deliverable.

.. An auditor may use other means to communicate with potential and registered voters such as, but not limited to, email, phone, or text messaging. The alternate form of communication must not be in lieu of the first-class mail requirements. The auditor shall act in compliance with all voter notification processes established in federal law.

. If an application is not complete, the auditor shall promptly mail a verification notice to the applicant. The verification notice must require the applicant to provide the missing information. If the applicant provides the required information within forty-five days, the applicant must be registered to vote. The applicant must not be placed on the official list of registered voters until the application is complete.

. If the prospective registration applicant declines to register to vote or the information provided by the department of licensing does not indicate citizenship, the information must not be included on the list of registered voters.

. The department of licensing is prohibited from sharing data files used by the secretary of state to certify voters registered through the automated process outlined in RCW 29A.08.355 with any federal agency, or state agency other than the secretary of state. Personal information supplied for the purposes of obtaining a driver's license or identicard is exempt from public inspection pursuant to RCW 42.56.230.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5227.SL.pdf?cite=2019%20c%20391%20§%208[2019 c 391 § 8]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2595-S2.SL.pdf?cite=2018%20c%20110%20§%20104[2018 c 110 § 104]; ]

== 29A.08.362 - Automatic registration—Health benefit exchange.
. Beginning July 1, 2019, the health benefit exchange shall provide the following information to the secretary of state's office for consenting Washington healthplanfinder applicants who affirmatively indicate that they are interested in registering to vote, including applicants who file changes of address, who reside in Washington, are age eighteen years or older, and are verified citizens, for voter registration purposes:

.. Names;

.. Traditional or nontraditional residential addresses;

.. Mailing addresses, if different from the traditional or nontraditional residential address; and

.. Dates of birth.

. The health benefit exchange shall consult with the secretary of state's office to ensure that sufficient information is provided to allow the secretary of state to obtain a digital copy of the person's signature when available from the department of licensing and establish other criteria and procedures that are secure and compliant with federal and state voter registration and privacy laws and rules.

. If applicable, the health benefit exchange shall report any known barriers or impediments to implementation of this section to the appropriate committees of the legislature and the governor no later than December 1, 2018.

. If the health benefit exchange determines, in consultation with the health care authority, that implementation of chapter 110, Laws of 2018 requires changes subject to approval from the centers for medicare and medicaid services, participation of the health benefit exchange is contingent on receiving that approval.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2595-S2.SL.pdf?cite=2018%20c%20110%20§%20201[2018 c 110 § 201]; ]

== 29A.08.365 - Automatic voter registration—Other agencies.
. The governor shall make a decision, in consultation with the office of the secretary of state, as to whether each agency identified in subsection (3) of this section shall implement automatic voter registration. The final decision is at the governor's sole discretion.

. [Empty]
.. Each agency identified in subsection (3) of this section shall submit a report to the governor and appropriate legislative committees no later than December 1, 2018, describing:

... Steps needed to implement automatic voter registration under chapter 110, Laws of 2018 by July 1, 2019;

... Barriers to implementation, including ways to mitigate those barriers; and

... Applicable federal and state privacy protections for voter registration information.

.. In preparing the report required under this subsection, the agency may consult with the secretary of state's office to determine automatic voter registration criteria and procedures.

. This section applies to state agencies, other than the health benefit exchange, providing public assistance or services to persons with disabilities, designated pursuant to RCW 29A.08.310(1), that collect, process, and store the following information as part of providing assistance or services:

.. Names;

.. Traditional or nontraditional residential addresses;

.. Dates of birth;

.. A signature attesting to the truth of the information provided on the application for assistance or services; and

.. Verification of citizenship information, via social security administration data match or manually verified by the agency during the client transaction.

. Once an agency has implemented automatic voter registration, it shall continue to provide automatic voter registration unless legislation is enacted that directs the agency to do otherwise.

. Agencies may not begin verifying citizenship as part of an agency transaction for the sole purpose of providing automatic voter registration.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2595-S2.SL.pdf?cite=2018%20c%20110%20§%20202[2018 c 110 § 202]; ]

== 29A.08.370 - Automatic registration—Registration of person ineligible to vote.
. If a person who is ineligible to vote becomes, in the rare occasion, registered to vote under RCW 29A.08.355 or 29A.08.362 in the absence of a knowing violation by that person of RCW 29A.84.140, that person shall be deemed to have performed an authorized act of registration and such act may not be considered as evidence of a claim to citizenship.

. Unless a person willfully and knowingly votes or attempts to vote knowing that he or she is not entitled to vote, a person who is ineligible to vote and becomes registered to vote under RCW 29A.08.355 or 29A.08.362, and subsequently votes or attempts to vote in an election held after the effective date of the person's registration, is not guilty of violating RCW 29A.84.130, and shall be deemed to have performed an authorized act, and such act may not be considered as evidence of a claim to citizenship.

. A person who is ineligible to vote, who successfully completes the voter registration process under RCW 29A.08.355 or 29A.08.362 or votes in an election, must have their voter registration, or record of vote, removed from the voter registration database and any other application records.

. Should an ineligible individual become registered to vote, the office of the secretary of state and the relevant agency shall jointly determine the cause.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2595-S2.SL.pdf?cite=2018%20c%20110%20§%20203[2018 c 110 § 203]; ]

== 29A.08.375 - Automatic registration—Rule-making authority.
The office of the secretary of state may adopt rules to implement automatic voter registration under chapter 110, Laws of 2018.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2595-S2.SL.pdf?cite=2018%20c%20110%20§%20207[2018 c 110 § 207]; ]

== 29A.08.410 - Address change within county—Deadlines.
A registered voter who changes his or her residence from one address to another within the same county may transfer his or her registration to the new address in one of the following ways:

. Sending the county auditor a request stating both the voter's present address and the address from which the voter was last registered received by an election official eight days prior to a primary or election;

. Appearing in person before the county auditor, or at a voting center or other location designated by the county auditor, and making such a request up until 8:00 p.m. on the day of the primary or election;

. Telephoning or emailing the county auditor to transfer the registration by eight days prior to a primary or election;

. Submitting a voter registration application received by an election official by eight days prior to a primary or election;

. Submitting information to the department of licensing and received by an election official by eight days prior to a primary or election;

. Submitting voter registration information through the health benefit exchange and received by an election official by eight days prior to a primary or election; or

. Submitting information to an agency designated under RCW 29A.08.365 and received by an election official by eight days prior to a primary or election once automatic voter registration is implemented at the agency.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5227.SL.pdf?cite=2019%20c%20391%20§%207[2019 c 391 § 7]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6021-S.SL.pdf?cite=2018%20c%20112%20§%203[2018 c 112 § 3]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2595-S2.SL.pdf?cite=2018%20c%20110%20§%20204[2018 c 110 § 204]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=2009%20c%20369%20§%2022[2009 c 369 § 22]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20228[2003 c 111 § 228]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6188-S.SL.pdf?cite=1994%20c%2057%20§%2035[1994 c 57 § 35]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1072.SL.pdf?cite=1991%20c%2081%20§%2023[1991 c 81 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c184.pdf?cite=1975%201st%20ex.s.%20c%20184%20§%202[1975 1st ex.s. c 184 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c202.pdf?cite=1971%20ex.s.%20c%20202%20§%2024[1971 ex.s. c 202 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c9.pdf?cite=1965%20c%209%20§%2029.10.020[1965 c 9 § 29.10.020]; prior:  1955 c 181 § 4; prior: 1933 c 1 § 14, part; RRS § 5114-14, part; prior: 1919 c 163 § 9, part; 1915 c 16 § 9, part; 1889 p 417 § 12, part; RRS § 5129, part; ]

== 29A.08.420 - Transfer to another county.
A registered voter who changes his or her residence from one county to another county must do so by submitting a voter registration form or by submitting information to the department of licensing, the health benefit exchange, or an agency designated under RCW 29A.08.365 once automatic voter registration is implemented at the agency. The county auditor of the voter's new county shall transfer the voter's registration from the county of the previous registration.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2595-S2.SL.pdf?cite=2018%20c%20110%20§%20205[2018 c 110 § 205]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=2009%20c%20369%20§%2023[2009 c 369 § 23]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6419-S.SL.pdf?cite=2004%20c%20267%20§%20122[2004 c 267 § 122]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20229[2003 c 111 § 229]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1133-S.SL.pdf?cite=1999%20c%20100%20§%203[1999 c 100 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6188-S.SL.pdf?cite=1994%20c%2057%20§%2036[1994 c 57 § 36]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1072.SL.pdf?cite=1991%20c%2081%20§%2024[1991 c 81 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c361.pdf?cite=1977%20ex.s.%20c%20361%20§%2026[1977 ex.s. c 361 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c202.pdf?cite=1971%20ex.s.%20c%20202%20§%2026[1971 ex.s. c 202 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c9.pdf?cite=1965%20c%209%20§%2029.10.040[1965 c 9 § 29.10.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c1.pdf?cite=1933%20c%201%20§%2015[1933 c 1 § 15]; RRS § 5114-15; ]

== 29A.08.440 - Voter name change.
A registered voter who changes his or her name shall notify the county auditor regarding the name change by submitting a notice clearly identifying the name under which he or she is registered to vote, the voter's new name, and the voter's residence, and providing a signature of the new name, or by submitting a voter registration application.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5124-S.SL.pdf?cite=2011%20c%2010%20§%2016[2011 c 10 § 16]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=2009%20c%20369%20§%2025[2009 c 369 § 25]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20231[2003 c 111 § 231]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6188-S.SL.pdf?cite=1994%20c%2057%20§%2037[1994 c 57 § 37]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1072.SL.pdf?cite=1991%20c%2081%20§%2025[1991 c 81 § 25]; ]

== 29A.08.510 - Death.
The registrations of deceased voters may be canceled from voter registration lists as follows:

. Periodically, the registrar of vital statistics of the state shall prepare a list of persons who resided in each county, for whom a death certificate was transmitted to the registrar and was not included on a previous list, and shall supply the list to the secretary of state.

The secretary of state shall compare this list with the registration records and cancel the registrations of deceased voters.

. In addition, each county auditor may also use government agencies and newspaper obituary articles as a source of information for identifying deceased voters and canceling a registration. The auditor must verify the identity of the voter by matching the voter's date of birth or an address. The auditor shall record the date and source of the information in the cancellation records.

. In addition, any registered voter may sign a statement, subject to the penalties of perjury, to the effect that to his or her personal knowledge or belief another registered voter is deceased. This statement may be filed with the county auditor or the secretary of state. Upon the receipt of such signed statement, the county auditor or the secretary of state shall cancel the registration from the official state voter registration list.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=2009%20c%20369%20§%2026[2009 c 369 § 26]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6419-S.SL.pdf?cite=2004%20c%20267%20§%20124[2004 c 267 § 124]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20232[2003 c 111 § 232]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1133-S.SL.pdf?cite=1999%20c%20100%20§%201[1999 c 100 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6188-S.SL.pdf?cite=1994%20c%2057%20§%2041[1994 c 57 § 41]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c110.pdf?cite=1983%20c%20110%20§%201[1983 c 110 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c202.pdf?cite=1971%20ex.s.%20c%20202%20§%2029[1971 ex.s. c 202 § 29]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c9.pdf?cite=1965%20c%209%20§%2029.10.090[1965 c 9 § 29.10.090]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c32.pdf?cite=1961%20c%2032%20§%201[1961 c 32 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c1.pdf?cite=1933%20c%201%20§%2020[1933 c 1 § 20]; RRS § 5114-20; ]

== 29A.08.515 - Incapacitation, guardianship. (Effective until January 1, 2022.)
Upon receiving official notice that a court has imposed a guardianship for an incapacitated person and has determined that the person is incompetent for the purpose of rationally exercising the right to vote, under *chapter 11.88 RCW, if the incapacitated person is a registered voter in the county, the county auditor shall cancel the incapacitated person's voter registration.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6419-S.SL.pdf?cite=2004%20c%20267%20§%20125[2004 c 267 § 125]; ]

== 29A.08.520 - Felony conviction—Provisional and permanent restoration of voting rights. (Effective until January 1, 2022.)
. For a felony conviction in a Washington state court, the right to vote is provisionally restored as long as the person is not under the authority of the department of corrections. For a felony conviction in a federal court or any state court other than a Washington state court, the right to vote is restored as long as the person is no longer incarcerated.

. [Empty]
.. Once the right to vote has been provisionally restored, the sentencing court may revoke the provisional restoration of voting rights if the sentencing court determines that a person has willfully failed to comply with the terms of his or her order to pay legal financial obligations.

.. If the person has failed to make three payments in a twelve-month period and the county clerk or restitution recipient requests, the prosecutor shall seek revocation of the provisional restoration of voting rights from the court.

.. To the extent practicable, the prosecutor and county clerk shall inform a restitution recipient of the recipient's right to ask for the revocation of the provisional restoration of voting rights.

. If the court revokes the provisional restoration of voting rights, the revocation shall remain in effect until, upon motion by the person whose provisional voting rights have been revoked, the person shows that he or she has made a good faith effort to pay as defined in RCW 10.82.090.

. The county clerk shall enter into a database maintained by the administrator for the courts the names of all persons whose provisional voting rights have been revoked, and update the database for any person whose voting rights have subsequently been restored pursuant to subsection (6) of this section.

. At least twice a year, the secretary of state shall compare the list of registered voters to a list of felons who are not eligible to vote as provided in subsections (1) and (3) of this section. If a registered voter is not eligible to vote as provided in this section, the secretary of state or county auditor shall confirm the match through a date of birth comparison and suspend the voter registration from the official state voter registration list. The secretary of state or county auditor shall send to the person at his or her last known voter registration address and at the department of corrections, if the person is under the authority of the department, a notice of the proposed cancellation and an explanation of the requirements for provisionally and permanently restoring the right to vote and reregistering. To the extent possible, the secretary of state shall time the comparison required by this subsection to allow notice and cancellation of voting rights for ineligible voters prior to a primary or general election.

. The right to vote may be permanently restored by one of the following for each felony conviction:

.. A certificate of discharge issued by the sentencing court, as provided in RCW 9.94A.637;

.. A court order restoring the right, as provided in RCW 9.92.066;

.. A final order of discharge issued by the indeterminate sentence review board, as provided in RCW 9.96.050; or

.. A certificate of restoration issued by the governor, as provided in RCW 9.96.020.

. For the purposes of this section, a person is under the authority of the department of corrections if the person is:

.. Serving a sentence of confinement in the custody of the department of corrections; or

.. Subject to community custody as defined in RCW 9.94A.030.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=2013%20c%2011%20§%2019[2013 c 11 § 19]; 2009 c 369 § 27; 2013 c 11 § 95; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1517.SL.pdf?cite=2009%20c%20325%20§%201[2009 c 325 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5743-S.SL.pdf?cite=2005%20c%20246%20§%2015[2005 c 246 § 15]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6419-S.SL.pdf?cite=2004%20c%20267%20§%20126[2004 c 267 § 126]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20233[2003 c 111 § 233]; prior:  1994 c 57 § 42; ]

== 29A.08.540 - Records preservation.
Registration records of persons whose voter registrations have been canceled as authorized under this title must be preserved in the manner prescribed by rule by the secretary of state. Information from such canceled registration records is available for public inspection and copying to the same extent established by RCW 29A.08.710 for other voter registration information.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6419-S.SL.pdf?cite=2004%20c%20267%20§%20127[2004 c 267 § 127]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20235[2003 c 111 § 235]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1072.SL.pdf?cite=1991%20c%2081%20§%2026[1991 c 81 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c202.pdf?cite=1971%20ex.s.%20c%20202%20§%2032[1971 ex.s. c 202 § 32]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c156.pdf?cite=1965%20ex.s.%20c%20156%20§%201[1965 ex.s. c 156 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c9.pdf?cite=1965%20c%209%20§%2029.10.110[1965 c 9 § 29.10.110]; prior:  1961 c 32 § 2; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c85.pdf?cite=1947%20c%2085%20§%205[1947 c 85 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c1.pdf?cite=1933%20c%201%20§%2021[1933 c 1 § 21]; Rem. Supp. 1947 § 5114-21; ]

== 29A.08.610 - Dual registration or voting detection.
The secretary of state shall conduct an ongoing list maintenance program designed to detect persons registered in more than one county or voting in more than one county in an election. This program must be applied uniformly throughout the state and must be nondiscriminatory in its application. 

The office of the secretary of state shall search the statewide voter registration list to find registered voters with the same date of birth and similar names. Once the potential duplicate registrations are identified, the secretary of state shall refer the potential duplicate registrations to the appropriate county auditors, who shall compare the signatures on each voter registration record and, after confirming that a duplicate registration exists properly resolve the duplication.

If a voter is suspected of voting in two or more counties in an election, the county auditors in each county shall cooperate without delay to determine the voter's county of residence. The county auditor of the county of residence of the voter suspected of voting in two or more counties shall take action under RCW 29A.84.010 without delay.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=2009%20c%20369%20§%2028[2009 c 369 § 28]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6419-S.SL.pdf?cite=2004%20c%20267%20§%20129[2004 c 267 § 129]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20237[2003 c 111 § 237]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1739-S.SL.pdf?cite=2001%20c%2041%20§%2010[2001 c 41 § 10]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1133-S.SL.pdf?cite=1999%20c%20100%20§%204[1999 c 100 § 4]; ]

== 29A.08.615 - "Active," "inactive" registered voters—"Pending" registrations.
. Registered voters are divided into two categories, "active" and "inactive." All registered voters are classified as active, unless assigned to inactive status by the county auditor.

. Persons signing up to register to vote as future voters as defined under RCW 29A.04.070 are classified as "pending" until the person will be at least eighteen years of age by the next election.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1513-S2.SL.pdf?cite=2018%20c%20109%20§%209[2018 c 109 § 9]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20238[2003 c 111 § 238]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6188-S.SL.pdf?cite=1994%20c%2057%20§%2034[1994 c 57 § 34]; ]

== 29A.08.620 - Change of address information for mail ballots—Assignment of voter to inactive status—Confirmation notice.
. Each county auditor must request change of address information from the postal service for all mail ballots.

. The county auditor shall transfer the registration of a voter and send an acknowledgment notice to the new address informing the voter of the transfer if change of address information received by the county auditor from the postal service, the department of licensing, or another agency designated to provide voter registration services indicates that the voter has moved within the county.

. The county auditor shall place a voter on inactive status and send to all known addresses a confirmation notice and a voter registration application if change of address information received by the county auditor from the postal service, the department of licensing, or another agency designated to provide voter registration services indicates that the voter has moved from one county to another.

. The county auditor shall place a voter on inactive status and send to all known addresses a confirmation notice if any of the following occur:

.. Any document mailed by the county auditor to a voter is returned by the postal service as undeliverable without address correction information; or

.. Change of address information received from the postal service, the department of licensing, or another state agency designated to provide voter registration services indicates that the voter has moved out of the state.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5124-S.SL.pdf?cite=2011%20c%2010%20§%2017[2011 c 10 § 17]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=2009%20c%20369%20§%2029[2009 c 369 § 29]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6419-S.SL.pdf?cite=2004%20c%20267%20§%20130[2004 c 267 § 130]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6417.SL.pdf?cite=2004%20c%20266%20§%208[2004 c 266 § 8]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20239[2003 c 111 § 239]; prior:  1994 c 57 § 38; ]

== 29A.08.625 - Voting by inactive or canceled voters.
. A voter whose registration has been made inactive under this chapter and who requests to vote at an ensuing election before two federal general elections have been held must be allowed to vote a regular ballot applicable to the registration address, and the voter's registration restored to active status.

. A voter whose registration has been properly canceled under this chapter shall vote a provisional ballot. The voter shall mark the provisional ballot in secrecy, the ballot placed in a security envelope, the security envelope placed in a provisional ballot envelope, and the reasons for the use of the provisional ballot noted.

. Upon receipt of such a voted provisional ballot the auditor shall investigate the circumstances surrounding the original cancellation. If he or she determines that the cancellation was in error, the voter's registration must be immediately reinstated, and the voter's provisional ballot must be counted. If the original cancellation was not in error, the voter must be afforded the opportunity to reregister at his or her correct address, and the voter's provisional ballot must not be counted.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=2009%20c%20369%20§%2030[2009 c 369 § 30]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20240[2003 c 111 § 240]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6188-S.SL.pdf?cite=1994%20c%2057%20§%2047[1994 c 57 § 47]; ]

== 29A.08.630 - Return of inactive voter to active status—Cancellation of registration.
The county auditor shall return an inactive voter to active voter status if, prior to the passage of two federal general elections, the voter:

. Notifies the auditor of a change of address;

. Responds to a confirmation notice with information that he or she continues to reside at the registration address; or

. Votes or attempts to vote in a primary, special election, or general election. If the inactive voter fails to provide such a notice or take such an action within that period, the auditor shall cancel the person's voter registration.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=2009%20c%20369%20§%2031[2009 c 369 § 31]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6419-S.SL.pdf?cite=2004%20c%20267%20§%20131[2004 c 267 § 131]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20241[2003 c 111 § 241]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6188-S.SL.pdf?cite=1994%20c%2057%20§%2039[1994 c 57 § 39]; ]

== 29A.08.635 - Confirmation notices—Form, contents.
Confirmation notices must be on a form prescribed by, or approved by, the secretary of state and must request that the voter confirm that he or she continues to reside at the address of record and desires to continue to use that address for voting purposes. The notice must inform the voter that if the voter does not respond to the notice and does not vote in either of the next two federal general elections, his or her voter registration will be canceled.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=2009%20c%20369%20§%2032[2009 c 369 § 32]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20242[2003 c 111 § 242]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6188-S.SL.pdf?cite=1994%20c%2057%20§%2045[1994 c 57 § 45]; ]

== 29A.08.640 - Confirmation notice—Response, auditor's action.
. If the response to the confirmation notice from the voter indicates that the voter has moved within the county, the auditor shall transfer the voter's registration and send the voter an acknowledgment notice.

. If the response from the voter indicates that the voter moved out of the county, but within the state, the auditor shall cancel the voter's registration and notify the county auditor of the voter's new county of residence.

. If the response from the voter indicates that the voter has left the state, the auditor shall cancel the voter's registration on the official state voter registration list.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=2009%20c%20369%20§%2033[2009 c 369 § 33]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6419-S.SL.pdf?cite=2004%20c%20267%20§%20132[2004 c 267 § 132]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20243[2003 c 111 § 243]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6188-S.SL.pdf?cite=1994%20c%2057%20§%2046[1994 c 57 § 46]; ]

== 29A.08.710 - Originals and automated files—Public disclosure.
. The county auditor shall have custody of the original voter registration records and voter registration sign up records for each county. The original voter registration form must be filed without regard to precinct and is considered confidential and unavailable for public inspection and copying. An automated file of all registered voters must be maintained pursuant to RCW 29A.08.125. An auditor may maintain the automated file in lieu of filing or maintaining the original voter registration forms if the automated file includes all of the information from the original voter registration forms including, but not limited to, a retrievable facsimile of each voter's signature.

. [Empty]
.. The following information contained in voter registration records or files regarding a voter or a group of voters is available for public inspection and copying, except as provided in RCW 40.24.060 and (b) of this subsection: The voter's name, address, political jurisdiction, gender, date of birth, voting record, date of registration, and registration number. No other information from voter registration records or files is available for public inspection or copying.

.. The personally identifiable information of individuals who are under the age of eighteen are exempt from public inspection and copying until the subject of the record is eighteen years of age, except for the purpose of processing and delivering ballots.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1513-S2.SL.pdf?cite=2018%20c%20109%20§%2010[2018 c 109 § 10]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5743-S.SL.pdf?cite=2005%20c%20246%20§%2017[2005 c 246 § 17]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6419-S.SL.pdf?cite=2004%20c%20267%20§%20133[2004 c 267 § 133]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20246[2003 c 111 § 246]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6188-S.SL.pdf?cite=1994%20c%2057%20§%2017[1994 c 57 § 17]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1072.SL.pdf?cite=1991%20c%2081%20§%2021[1991 c 81 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c202.pdf?cite=1971%20ex.s.%20c%20202%20§%2017[1971 ex.s. c 202 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c9.pdf?cite=1965%20c%209%20§%2029.07.130[1965 c 9 § 29.07.130]; 1933 c 1 § 13, part; RRS § 5114-13, part; ]

== 29A.08.720 - Registration, voting records—As public records—Information furnished—Restrictions, confidentiality.
. In the case of voter registration records received through the health benefit exchange, the department of licensing, or an agency designated under RCW 29A.08.310, the identity of the office or agency at which any particular individual registered to vote must be used only for voter registration purposes, is not available for public inspection, and shall not be disclosed to the public. Any record of a particular individual's choice not to register to vote at an office of the department of licensing or a state agency designated under RCW 29A.08.310 is not available for public inspection and any information regarding such a choice by a particular individual shall not be disclosed to the public. Information that is otherwise disclosable under this chapter cannot be disclosed on the future voter until the person reaches eighteen years of age, except for the purpose of processing and delivering ballots.

. [Empty]
.. Subject to the restrictions of RCW 29A.08.710 and 40.24.060, and (b) of this subsection, precinct lists and current lists of registered voters are public records and must be made available for public inspection and copying under such reasonable rules and regulations as the county auditor or secretary of state may prescribe. The county auditor or secretary of state shall promptly furnish current lists of registered voters in his or her possession, at actual reproduction cost, to any person requesting such information. The lists shall not be used for the purpose of mailing or delivering any advertisement or offer for any property, establishment, organization, product, or service or for the purpose of mailing or delivering any solicitation for money, services, or anything of value. However, the lists and labels may be used for any political purpose. The county auditor or secretary of state must provide a copy of RCW 29A.08.740 to the person requesting the material that is released under this section.

.. The personally identifiable information of individuals who are under the age of eighteen are exempt from public inspection and copying until the subject of the record is eighteen years of age, except for the purpose of processing and delivering ballots.

. For the purposes of this section, "political purpose" means a purpose concerned with the support of or opposition to any candidate for any partisan or nonpartisan office or concerned with the support of or opposition to any ballot proposition or issue. "Political purpose" includes, but is not limited to, such activities as the advertising for or against any candidate or ballot measure or the solicitation of financial support.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2595-S2.SL.pdf?cite=2018%20c%20110%20§%20206[2018 c 110 § 206]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1513-S2.SL.pdf?cite=2018%20c%20109%20§%2011[2018 c 109 § 11]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5124-S.SL.pdf?cite=2011%20c%2010%20§%2018[2011 c 10 § 18]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=2009%20c%20369%20§%2034[2009 c 369 § 34]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5743-S.SL.pdf?cite=2005%20c%20246%20§%2018[2005 c 246 § 18]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6417.SL.pdf?cite=2004%20c%20266%20§%209[2004 c 266 § 9]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20247[2003 c 111 § 247]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6188-S.SL.pdf?cite=1994%20c%2057%20§%205[1994 c 57 § 5]; 1975-'76 2nd ex.s. c 46 § 1; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c127.pdf?cite=1974%20ex.s.%20c%20127%20§%202[1974 ex.s. c 127 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c111.pdf?cite=1973%201st%20ex.s.%20c%20111%20§%202[1973 1st ex.s. c 111 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c202.pdf?cite=1971%20ex.s.%20c%20202%20§%203[1971 ex.s. c 202 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c156.pdf?cite=1965%20ex.s.%20c%20156%20§%206[1965 ex.s. c 156 § 6]; ]

== 29A.08.740 - Violations of restricted use of registered voter data—Penalties—Liabilities.
. Any person who uses registered voter data furnished under RCW 29A.08.720 for the purpose of mailing or delivering any advertisement or offer for any property, establishment, organization, product, or service or for the purpose of mailing or delivering any solicitation for money, services, or anything of value is guilty of a class C felony punishable by imprisonment in a state correctional facility for a period of not more than five years or a fine of not more than ten thousand dollars or both such fine and imprisonment, and is liable to each person provided such advertisement or solicitation, without the person's consent, for the nuisance value of such person having to dispose of it, which value is herein established at five dollars for each item mailed or delivered to the person's residence. However, a person who mails or delivers any advertisement, offer, or solicitation for a political purpose is not liable under this section unless the person is liable under subsection (2) of this section. For purposes of this subsection, two or more attached papers or sheets or two or more papers that are enclosed in the same envelope or container or are folded together are one item. Merely having a mailbox or other receptacle for mail on or near the person's residence is not an indication that the person consented to receive the advertisement or solicitation. A class action may be brought to recover damages under this section, and the court may award a reasonable attorney's fee to any party recovering damages under this section.

. Each person furnished data under RCW 29A.08.720 shall take reasonable precautions designed to assure that the data is not used for the purpose of mailing or delivering any advertisement or offer for any property, establishment, organization, product, or service or for the purpose of mailing or delivering any solicitation for money, services, or anything of value. However, the data may be used for any political purpose. Where failure to exercise due care in carrying out this responsibility results in the data being used for such purposes, then such person is jointly and severally liable for damages under subsection (1) of this section along with any other person liable under subsection (1) of this section for the misuse of such data.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5743-S.SL.pdf?cite=2005%20c%20246%20§%2019[2005 c 246 § 19]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20249[2003 c 111 § 249]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20176[2003 c 53 § 176]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1291-S.SL.pdf?cite=1999%20c%20298%20§%202[1999 c 298 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2263-S.SL.pdf?cite=1992%20c%207%20§%2032[1992 c 7 § 32]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c127.pdf?cite=1974%20ex.s.%20c%20127%20§%203[1974 ex.s. c 127 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c111.pdf?cite=1973%201st%20ex.s.%20c%20111%20§%204[1973 1st ex.s. c 111 § 4]; ]

== 29A.08.760 - Computer file—Duplicate copy—Restrictions and penalties.
The secretary of state shall provide a duplicate copy of the master statewide computer file or electronic data file of registered voters to the consolidated technology services agency for purposes of creating the jury source list without cost. The information contained in a voter registration application is exempt from inclusion until the applicant reaches age eighteen. Information that is otherwise disclosable under this chapter cannot be disclosed on the future voter until the person reaches eighteen years of age, except for the purpose of processing and delivering ballots. Restrictions as to the commercial use of the information on the statewide computer tape or data file of registered voters, and penalties for its misuse, shall be the same as provided in RCW 29A.08.720 and 29A.08.740.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1513-S2.SL.pdf?cite=2018%20c%20109%20§%2012[2018 c 109 § 12]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5931-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2043%20§%20813[2011 1st sp.s. c 43 § 813]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=2009%20c%20369%20§%2035[2009 c 369 § 35]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6419-S.SL.pdf?cite=2004%20c%20267%20§%20134[2004 c 267 § 134]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20251[2003 c 111 § 251]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1063.SL.pdf?cite=1995%20c%20135%20§%202[1995 c 135 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5973.SL.pdf?cite=1993%20c%20441%20§%202[1993 c 441 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1084-S.SL.pdf?cite=1993%20c%20408%20§%2010[1993 c 408 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c226.pdf?cite=1977%20ex.s.%20c%20226%20§%201[1977 ex.s. c 226 § 1]; 1975-'76 2nd ex.s. c 46 § 3; ]

== 29A.08.770 - Records concerning accuracy and currency of voters lists.
The secretary of state and each county auditor shall maintain for at least two years and shall make available for public inspection and copying all records concerning the implementation of programs and activities conducted for the purpose of insuring the accuracy and currency of official lists of eligible voters. These records must include lists of the names and addresses of all persons to whom notices are sent and information concerning whether or not each person has responded to the notices. These records must contain lists of all persons removed from the list of eligible voters and the reasons why the voters were removed. The personally identifiable information of individuals who are under the age of eighteen are exempt from public inspection and copying until the subject of the record is eighteen years of age, except for the purpose of processing and delivering ballots.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1513-S2.SL.pdf?cite=2018%20c%20109%20§%2019[2018 c 109 § 19]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6419-S.SL.pdf?cite=2004%20c%20267%20§%20135[2004 c 267 § 135]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20252[2003 c 111 § 252]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6188-S.SL.pdf?cite=1994%20c%2057%20§%207[1994 c 57 § 7]; ]

== 29A.08.775 - Use and maintenance of statewide list.
Only voters who appear on the official statewide voter registration list are eligible to participate in elections. Each county shall maintain a copy of that county's portion of the state list. The county must ensure that voter registration data used for the production, issuance, and processing of ballots in the administration of each election are the same as the official statewide voter registration list.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5124-S.SL.pdf?cite=2011%20c%2010%20§%2019[2011 c 10 § 19]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5743-S.SL.pdf?cite=2005%20c%20246%20§%2020[2005 c 246 § 20]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6419-S.SL.pdf?cite=2004%20c%20267%20§%20136[2004 c 267 § 136]; ]

== 29A.08.810 - Basis for challenging a voter's registration—Who may bring a challenge—Challenger duties. (Effective until January 1, 2022.)
. Registration of a person as a voter is presumptive evidence of his or her right to vote. A challenge to the person's right to vote must be based on personal knowledge of one of the following:

.. The challenged voter has been convicted of a felony and the voter's civil rights have not been restored;

.. The challenged voter has been judicially declared ineligible to vote due to mental incompetency;

.. The challenged voter does not live at the residential address provided, in which case the challenger must either:

... Provide the challenged voter's actual residence on the challenge form; or

... Submit evidence that he or she exercised due diligence to verify that the challenged voter does not reside at the address provided and to attempt to contact the challenged voter to learn the challenged voter's actual residence, including that the challenger personally:

(A) Sent a letter with return service requested to the challenged voter's residential address provided, and to the challenged voter's mailing address, if provided;

(B) Visited the residential address provided and contacted persons at the address to determine whether the voter resides at the address and, if not, obtained and submitted with the challenge form a signed affidavit subject to the penalties of perjury from a person who owns or manages property, resides, or is employed at the address provided, that to his or her personal knowledge the challenged voter does not reside at the address as provided on the voter registration;

(C) Searched local telephone directories, including online directories, to determine whether the voter maintains a telephone listing at any address in the county;

(D) Searched county auditor property records to determine whether the challenged voter owns any property in the county; and

(E) Searched the statewide voter registration database to determine if the voter is registered at any other address in the state;

.. The challenged voter will not be eighteen years of age by the next election; or

.. The challenged voter is not a citizen of the United States.

. A person's right to vote may be challenged by another registered voter or the county prosecuting attorney.

. The challenger must file a signed affidavit subject to the penalties of perjury swearing that, to his or her personal knowledge and belief, having exercised due diligence to personally verify the evidence presented, the challenged voter either is not qualified to vote or does not reside at the address given on his or her voter registration record based on one of the reasons allowed in subsection (1) of this section. The challenger must provide the factual basis for the challenge, including any information required by subsection (1)(c) of this section, in the signed affidavit. The challenge may not be based on unsupported allegations or allegations by anonymous third parties. All documents pertaining to the challenge are public records.

. Challenges based on a felony conviction under RCW 29A.08.520 must be heard according to RCW 29A.08.520 and rules adopted by the secretary of state.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5124-S.SL.pdf?cite=2011%20c%2010%20§%2020[2011 c 10 § 20]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6362-S.SL.pdf?cite=2006%20c%20320%20§%204[2006 c 320 § 4]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20253[2003 c 111 § 253]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1739-S.SL.pdf?cite=2001%20c%2041%20§%209[2001 c 41 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c288.pdf?cite=1987%20c%20288%20§%201[1987 c 288 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c30.pdf?cite=1983%201st%20ex.s.%20c%2030%20§%202[1983 1st ex.s. c 30 § 2]; ]

== 29A.08.820 - Times for filing challenges—Hearings—Treatment of challenged ballots.
. Challenges must be filed with the county auditor of the county in which the challenged voter is registered no later than forty-five days before the election. The county auditor presides over the hearing.

. Only if the challenged voter registered to vote less than sixty days before the election, or changed residence less than sixty days before the election without transferring his or her registration, may a challenge be filed not later than ten days before any primary or election, general or special, or within ten days of the voter being added to the voter registration database, whichever is later.

.. If the challenge is filed within forty-five days before an election at which the challenged voter is eligible to vote, a notation of the challenge must be made immediately in the voter registration system, and the county canvassing board presides over the hearing.

.. If the challenge is filed before the challenged voter's ballot is received, the ballot must be treated as a challenged ballot.

.. If the challenge is filed after the challenged voter's ballot is received, the challenge cannot affect the current election.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=2013%20c%2011%20§%2020[2013 c 11 § 20]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5124-S.SL.pdf?cite=2011%20c%2010%20§%2021[2011 c 10 § 21]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6362-S.SL.pdf?cite=2006%20c%20320%20§%205[2006 c 320 § 5]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20254[2003 c 111 § 254]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c288.pdf?cite=1987%20c%20288%20§%202[1987 c 288 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c30.pdf?cite=1983%201st%20ex.s.%20c%2030%20§%203[1983 1st ex.s. c 30 § 3]; ]

== 29A.08.835 - County auditor to publish voter challenges on the internet—Ongoing notification requirements.
The county auditor shall, within seventy-two hours of receipt, publish on the auditor's internet website the entire content of any voter challenge filed under chapter 29A.08 RCW. Immediately after publishing any voter challenge, the county auditor shall notify any person who requests to receive such notifications on an ongoing basis.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6362-S.SL.pdf?cite=2006%20c%20320%20§%201[2006 c 320 § 1]; ]

== 29A.08.840 - County auditor duties—Dismissal of challenges—Notification—Hearings—Counting or cancellation of ballots.
. If the challenge is not in proper form or the factual basis for the challenge does not meet the legal grounds for a challenge, the county auditor may dismiss the challenge and notify the challenger of the reasons for the dismissal. A challenge is not in proper form if it is incomplete on its face or does not substantially comply with the form issued by the secretary of state.

. If the challenge is in proper form and the factual basis meets the legal grounds for a challenge, the county auditor must notify the challenged voter and provide a copy of the affidavit. The county auditor shall also provide to any person, upon request, a copy of all materials provided to the challenged voter. If the challenge is to the residential address provided by the voter, the challenged voter must be provided notice of the exceptions allowed in RCW 29A.08.112 and 29A.04.151, and Article VI, section 4 of the state Constitution. A challenged voter may transfer or reregister until the day before the election. The county auditor must schedule a hearing and notify the challenger and the challenged voter of the time and place for the hearing.

. All notice must be by certified mail to the address provided in the voter registration record, and any other addresses at which the challenged voter is alleged to reside or the county auditor reasonably expects the voter to receive notice. The challenger and challenged voter may either appear in person or submit testimony by affidavit.

. The challenger has the burden to prove by clear and convincing evidence that the challenged voter's registration is improper. The challenged voter must be provided a reasonable opportunity to respond. If the challenge is to the residential address provided by the voter, the challenged voter may provide evidence that he or she resides at the location described in his or her voter's registration records, or meets one of the exceptions allowed in RCW 29A.08.112 or 29A.04.151, or Article VI, section 4 of the state Constitution. If either the challenger or challenged voter fails to appear at the hearing, the challenge must be resolved based on the available facts.

. If the challenge is based on an allegation under RCW 29A.08.810(1) (a), (b), (d), or (e) and the canvassing board sustains the challenge, the challenged ballot shall not be counted. If the challenge is based on an allegation under RCW 29A.08.810(1)(c) and the canvassing board sustains the challenge, the board shall permit the voter to correct his or her voter registration and any races and ballot measures on the challenged ballot that the voter would have been qualified to vote for had the registration been correct shall be counted.

. If the challenger fails to prove by clear and convincing evidence that the registration is improper, the challenge must be dismissed and the pending challenged ballot must be accepted as valid. Challenged ballots must be resolved before certification of the election. The decision of the county auditor or canvassing board is final subject only to judicial review by the superior court under chapter 34.05 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6362-S.SL.pdf?cite=2006%20c%20320%20§%206[2006 c 320 § 6]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20256[2003 c 111 § 256]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c288.pdf?cite=1987%20c%20288%20§%204[1987 c 288 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c30.pdf?cite=1983%201st%20ex.s.%20c%2030%20§%205[1983 1st ex.s. c 30 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c202.pdf?cite=1971%20ex.s.%20c%20202%20§%2034[1971 ex.s. c 202 § 34]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c225.pdf?cite=1967%20c%20225%20§%203[1967 c 225 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c156.pdf?cite=1965%20ex.s.%20c%20156%20§%203[1965 ex.s. c 156 § 3]; ]

== 29A.08.850 - Challenge of registration—Forms, availability.
The secretary of state must provide forms for voter registration challenges, and the county auditor must make such forms available. A challenge is not required to be submitted on the provided voter challenge form, but may be prepared using an official electronic voter challenge form template provided by the auditor or secretary of state that has been printed and signed by the challenger for submission.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6362-S.SL.pdf?cite=2006%20c%20320%20§%207[2006 c 320 § 7]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20257[2003 c 111 § 257]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1072.SL.pdf?cite=1991%20c%2081%20§%2027[1991 c 81 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c202.pdf?cite=1971%20ex.s.%20c%20202%20§%2035[1971 ex.s. c 202 § 35]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c156.pdf?cite=1965%20ex.s.%20c%20156%20§%204[1965 ex.s. c 156 § 4]; ]

