= 29A.64 - Recounts.
:toc:

== 29A.64.011 - Application—Requirements—Application of chapter.
An officer of a political party or any person for whom votes were cast in a primary who did not qualify for the general election may file a written application for a recount of the votes or a portion of the votes cast at that primary for all persons for whom votes were cast for that office.

An officer of a political party or any person for whom votes were cast at any election may file a written application for a recount of the votes or a portion of the votes cast at that election for all candidates for election to that office.

Any group of five or more registered voters may file a written application for a recount of the votes or a portion of the votes cast upon any question or issue. They shall designate one of the members of the group as chair and shall indicate the voting residence of each member of the group.

An application for a recount of the votes cast for an office or on a ballot measure must be filed with the officer with whom filings are made for the jurisdiction.

An application for a recount must specify whether the recount will be done manually or by the vote tally system. A recount done by the vote tally system must use programming that recounts and reports only the office or ballot measure in question. The county shall also provide for a test of the logic and accuracy of that program.

An application for a recount must be filed within two business days after the county canvassing board or secretary of state has declared the official results of the primary or election for the office or issue for which the recount is requested.

This chapter applies to the recounting of votes cast by paper ballots and to the recounting of votes recorded on ballots counted by a vote tally system.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5171-S.SL.pdf?cite=2011%20c%20349%20§%2023[2011 c 349 § 23]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6453.SL.pdf?cite=2004%20c%20271%20§%20177[2004 c 271 § 177]; ]

== 29A.64.021 - Mandatory.
. If the official canvass of all of the returns for any office at any primary or election reveals that the difference in the number of votes cast for a candidate apparently qualified for the general election ballot or elected to any office, and the number of votes cast for the closest apparently defeated opponent is less than two thousand votes and also less than one-half of one percent of the total number of votes cast for both candidates, the county canvassing board shall conduct a recount of all votes cast on that position.

.. Whenever such a difference occurs in the number of votes cast for candidates for a position the declaration of candidacy for which was filed with the secretary of state, the secretary of state shall, within three business days of the day that the returns of the primary or election are first certified by the canvassing boards of those counties, direct those boards to recount all votes cast on the position.

.. [Empty]
... For statewide elections, if the difference in the number of votes cast for the apparent winner and the closest apparently defeated opponent is less than one thousand votes and also less than one-fourth of one percent of the total number of votes cast for both candidates, the votes shall be recounted manually or as provided in subsection (3) of this section.

... For elections not included in (b)(i) of this subsection, if the difference in the number of votes cast for the apparent winner and the closest apparently defeated opponent is less than one hundred fifty votes and also less than one-fourth of one percent of the total number of votes cast for both candidates, the votes shall be recounted manually or as provided in subsection (3) of this section.

. A mandatory recount shall be conducted in the manner provided by RCW 29A.64.030, 29A.64.041, and 29A.64.061. No cost of a mandatory recount may be charged to any candidate.

. The apparent winner and closest apparently defeated opponent for an office for which a manual recount is required under subsection (1)(b) of this section may select an alternative method of conducting the recount. To select such an alternative, the two candidates shall agree to the alternative in a signed, written statement filed with the election official for the office. The recount shall be conducted using the alternative method if: It is suited to the balloting system that was used for casting the votes for the office; it involves the use of a vote tallying system that is approved for use in this state by the secretary of state; and the vote tallying system is readily available in each county required to conduct the recount. If more than one balloting system was used in casting votes for the office, an alternative to a manual recount may be selected for each system.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=2013%20c%2011%20§%2066[2013 c 11 § 66]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5499-S.SL.pdf?cite=2005%20c%20243%20§%2019[2005 c 243 § 19]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6453.SL.pdf?cite=2004%20c%20271%20§%20178[2004 c 271 § 178]; ]

== 29A.64.030 - Deposit of fees—Notice—Public proceeding.
An application for a recount shall state the office or ballot measure for which a recount is requested, and whether the request is for all precincts or only a portion of the precincts in that jurisdiction. The person filing an application for a manual recount shall, at the same time, deposit with the county canvassing board or secretary of state, in cash or by certified check, a sum equal to twenty-five cents for each ballot cast in the jurisdiction or portion of the jurisdiction for which the recount is requested as security for the payment of any costs of conducting the recount. If the application is for a machine recount, the deposit must be equal to fifteen cents for each ballot. These charges shall be determined by the county canvassing board or boards under RCW 29A.64.081.

The county canvassing board shall determine the date, time, and place or places at which the recount will be conducted. Not less than one day before the date of the recount, the county auditor shall notify the applicant or affected parties and, if the recount involves an office, to any person for whom votes were cast for that office of the date, time, and place of the recount. Each person entitled to receive notice of the recount may attend, witness the recount, and be accompanied by counsel.

Proceedings of the canvassing board are public under chapter 42.30 RCW. Subject to reasonable and equitable guidelines adopted by the canvassing board, all interested persons may attend and witness a recount.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=2013%20c%2011%20§%2067[2013 c 11 § 67]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5171-S.SL.pdf?cite=2011%20c%20349%20§%2024[2011 c 349 § 24]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5499-S.SL.pdf?cite=2005%20c%20243%20§%2020[2005 c 243 § 20]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%201603[2003 c 111 § 1603]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1644-S.SL.pdf?cite=2001%20c%20225%20§%205[2001 c 225 § 5]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1072.SL.pdf?cite=1991%20c%2081%20§%2036[1991 c 81 § 36]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c54.pdf?cite=1987%20c%2054%20§%205[1987 c 54 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c361.pdf?cite=1977%20ex.s.%20c%20361%20§%2099[1977 ex.s. c 361 § 99]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c9.pdf?cite=1965%20c%209%20§%2029.64.020[1965 c 9 § 29.64.020]; prior:  1961 c 50 § 2; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c215.pdf?cite=1955%20c%20215%20§%202[1955 c 215 § 2]; ]

== 29A.64.041 - Procedure—Request to stop—Observers.
. At the time and place established for a recount, the canvassing board or its duly authorized representatives, in the presence of all witnesses who may be in attendance, shall open the sealed containers containing the ballots to be recounted, and shall recount the votes for the offices or issues for which the recount has been ordered. Ballots shall be handled only by the members of the canvassing board or their duly authorized representatives.

 The canvassing board shall not permit the tabulation of votes for any nomination, election, or issue other than the ones for which a recount was applied for or required.

. At any time before the ballots from all of the precincts listed in the application for the recount have been recounted, the applicant may file with the board a written request to stop the recount.

. The recount may be observed by persons representing the candidates affected by the recount or the persons representing both sides of an issue that is being recounted. Witnesses shall be permitted to observe the ballots and the process of tabulating the votes, but they shall not be permitted to handle the ballots. The observers may not make a record of the names, addresses, or other information on the ballots, declarations, or lists of voters unless authorized by the superior court. The secretary of state or county auditor may limit the number of observers to not less than two on each side if, in his or her opinion, a greater number would cause undue delay or disruption of the recount process.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5124-S.SL.pdf?cite=2011%20c%2010%20§%2063[2011 c 10 § 63]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6453.SL.pdf?cite=2004%20c%20271%20§%20179[2004 c 271 § 179]; ]

== 29A.64.050 - Partial recount requiring complete recount.
When a partial recount of votes cast for an office or issue changes the result of the election, the canvassing board or the secretary of state, if the office or issue is being recounted at his or her direction, shall order a complete recount of all ballots cast for the office or issue for the jurisdiction in question.

This recount will be conducted in a manner consistent with RCW 29A.64.021.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=2013%20c%2011%20§%2068[2013 c 11 § 68]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%201605[2003 c 111 § 1605]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1644-S.SL.pdf?cite=2001%20c%20225%20§%207[2001 c 225 § 7]; ]

== 29A.64.061 - Amended abstracts.
. Upon completion of the canvass of a recount, the canvassing board shall prepare and certify an amended abstract showing the votes cast in each precinct for which the recount was conducted. Copies of the amended abstracts must be transmitted to the same officers who received the abstract on which the recount was based.

. If the office or issue for which the recount was conducted was filed with the county auditor, the canvassing board shall file the amended abstract with the original results of that election or primary.

. If the office or issue for which a recount was conducted was filed with the secretary of state, the secretary of state shall canvass the amended abstracts and shall file an amended abstract with the original results of that election. The secretary of state may require that the amended abstracts be certified by each canvassing board on a uniform date.

. An amended abstract certified under this section supersedes any prior abstract of the results for the same offices or issues at the same primary or election.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=2013%20c%2011%20§%2069[2013 c 11 § 69]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5499-S.SL.pdf?cite=2005%20c%20243%20§%2021[2005 c 243 § 21]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6453.SL.pdf?cite=2004%20c%20271%20§%20180[2004 c 271 § 180]; ]

== 29A.64.070 - Limitation.
After the original count, canvass, and certification of results, the votes cast in any single precinct may not be recounted and the results recertified more than twice.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%201607[2003 c 111 § 1607]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1644-S.SL.pdf?cite=2001%20c%20225%20§%209[2001 c 225 § 9]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1571-S.SL.pdf?cite=1991%20c%2090%20§%203[1991 c 90 § 3]; ]

== 29A.64.081 - Expenses—Charges. (Effective until July 1, 2021.)
The canvassing board shall determine the expenses for conducting a recount of votes.

The cost of the recount shall be deducted from the amount deposited by the applicant for the recount at the time of filing the request for the recount, and the balance shall be returned to the applicant. If the costs of the recount exceed the deposit, the applicant shall pay the difference. No charges may be deducted by the canvassing board from the deposit for a recount if the recount changes the result of the nomination or election for which the recount was ordered.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6453.SL.pdf?cite=2004%20c%20271%20§%20181[2004 c 271 § 181]; ]

== 29A.64.090 - Statewide measures—When mandatory—Cost at state expense—Statewide advisory votes of the people.
When the official canvass of returns of any election reveals that the difference in the number of votes cast for the approval of a statewide measure and the number of votes cast for the rejection of such measure is less than two thousand votes and also less than one-half of one percent of the total number of votes cast on such measure, the secretary of state shall direct that a recount of all votes cast on such measure be made on such measure, in the manner provided by RCW 29A.64.041 and 29A.64.061, and the cost of such recount will be at state expense. This section does not apply to any statewide advisory vote of the people that was placed on the ballot pursuant to RCW 43.135.041 and the secretary of state shall not direct any recount for any statewide advisory vote of the people.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2623.SL.pdf?cite=2016%20c%20204%20§%201[2016 c 204 § 1]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=2013%20c%2011%20§%2070[2013 c 11 § 70]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%201609[2003 c 111 § 1609]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1644-S.SL.pdf?cite=2001%20c%20225%20§%2011[2001 c 225 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c82.pdf?cite=1973%20c%2082%20§%201[1973 c 82 § 1]; ]

== 29A.64.100 - Statewide measures—Funds for additional expenses.
Each county auditor shall file with the secretary of state a statement listing only the additional expenses incurred whenever a mandatory recount of the votes cast on a state measure is made as provided in RCW 29A.64.090. The secretary of state shall include in his or her biennial budget request a provision for sufficient funds to carry out the provisions of this section. Payments hereunder shall be from appropriations specifically provided for such purpose by law.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%201610[2003 c 111 § 1610]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c144.pdf?cite=1977%20ex.s.%20c%20144%20§%205[1977 ex.s. c 144 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c82.pdf?cite=1973%20c%2082%20§%202[1973 c 82 § 2]; ]

