= 29A.76 - Redistricting.
:toc:

== 29A.76.010 - Counties, municipal corporations, and special purpose districts.
. It is the responsibility of each county, municipal corporation, and special purpose district with a governing body comprised of internal director, council, or commissioner districts not based on statutorily required land ownership criteria to periodically redistrict its governmental unit, based on population information from the most recent federal decennial census.

. Within forty-five days after receipt of federal decennial census information applicable to a specific local area, the commission established in RCW 44.05.030 shall forward the census information to each municipal corporation, county, and district charged with redistricting under this section.

. Except as otherwise provided in chapter 301, Laws of 2018, no later than eight months after its receipt of federal decennial census data, the governing body of the municipal corporation, county, or district shall prepare a plan for redistricting its internal or director districts.

. The plan shall be consistent with the following criteria:

.. Each internal director, council, or commissioner district shall be as nearly equal in population as possible to each and every other such district comprising the municipal corporation, county, or special purpose district.

.. Each district shall be as compact as possible.

.. Each district shall consist of geographically contiguous area.

.. Population data may not be used for purposes of favoring or disfavoring any racial group or political party.

.. To the extent feasible and if not inconsistent with the basic enabling legislation for the municipal corporation, county, or district, the district boundaries shall coincide with existing recognized natural boundaries and shall, to the extent possible, preserve existing communities of related and mutual interest.

. During the adoption of its plan, the municipal corporation, county, or district shall ensure that full and reasonable public notice of its actions is provided. Before adopting the plan, the municipal corporation, county, or district must:

.. Publish the draft plan and hold a meeting, including notice and comment, within ten days of publishing the draft plan and at least one week before adopting the plan; and

.. Amend the draft as necessary after receiving public comments and resubmit any amended draft plan for additional written public comment at least one week before adopting the plan.

. [Empty]
.. Any registered voter residing in an area affected by the redistricting plan may request review of the adopted local plan by the superior court of the county in which he or she resides, within fifteen days of the plan's adoption. Any request for review must specify the reason or reasons alleged why the local plan is not consistent with the applicable redistricting criteria. The municipal corporation, county, or district may be joined as respondent. The superior court shall thereupon review the challenged plan for compliance with the applicable redistricting criteria set out in subsection (4) of this section.

.. If the superior court finds the plan to be consistent with the requirements of this section, the plan shall take effect immediately.

.. If the superior court determines the plan does not meet the requirements of this section, in whole or in part, it shall remand the plan for further or corrective action within a specified and reasonable time period.

.. If the superior court finds that any request for review is frivolous or has been filed solely for purposes of harassment or delay, it may impose appropriate sanctions on the party requesting review, including payment of attorneys' fees and costs to the respondent municipal corporation, county, or district.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2887-S.SL.pdf?cite=2018%20c%20301%20§%208[2018 c 301 § 8]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5171-S.SL.pdf?cite=2011%20c%20349%20§%2026[2011 c 349 § 26]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%201901[2003 c 111 § 1901]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c13.pdf?cite=1984%20c%2013%20§%204[1984 c 13 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c16.pdf?cite=1983%20c%2016%20§%2015[1983 c 16 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c2.pdf?cite=1982%20c%202%20§%2027[1982 c 2 § 27]; ]

== 29A.76.020 - Boundary information.
The legislative authority of each county and each city, town, and special purpose district which lies within the county shall provide the county auditor accurate information describing its geographical boundaries and the boundaries of its director, council, or commissioner districts and shall ensure that the information provided to the auditor is kept current.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=2013%20c%2011%20§%2077[2013 c 11 § 77]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%201902[2003 c 111 § 1902]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5156-S.SL.pdf?cite=1991%20c%20178%20§%202[1991 c 178 § 2]; ]

== 29A.76.040 - Maps and census correspondence lists—Apportionment—Duties of secretary of state.
. With regard to functions relating to census, apportionment, and the establishment of legislative and congressional districts, the secretary of state shall:

.. Coordinate and monitor precinct mapping functions of the county auditors and county engineers;

.. Maintain official state base maps and correspondence lists and maintain an index of all such maps and lists;

.. Furnish to the United States bureau of the census as needed for the decennial census of population, current, accurate, and easily readable versions of maps of all counties, cities, towns, and other areas of this state, which indicate current precinct boundaries together with copies of the census correspondence lists.

. The secretary of state shall serve as the state liaison with the United States bureau of census on matters relating to the preparation of maps and the tabulation of population for apportionment purposes.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%201904[2003 c 111 § 1904]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c278.pdf?cite=1989%20c%20278%20§%202[1989 c 278 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c128.pdf?cite=1977%20ex.s.%20c%20128%20§%204[1977 ex.s. c 128 § 4]; 1975-'76 2nd ex.s. c 129 § 2; ]

== 29A.76.050 - Voluntary change to electoral system—Use of population data regarding political parties.
In any change to its electoral system under RCW 29A.92.040 or preparation of a redistricting plan under RCW 29A.92.040, political subdivisions may use population data regarding political parties only to the extent necessary to ensure compliance with chapter 113, Laws of 2018 or federal law.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6002-S.SL.pdf?cite=2018%20c%20113%20§%20502[2018 c 113 § 502]; ]

