= 29A.28 - Vacancies.
:toc:

== 29A.28.030 - United States senate.
When a vacancy occurs in the representation of this state in the senate of the United States, the governor shall make a temporary appointment to that office until the people fill the vacancy by election as provided in this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20703[2003 c 111 § 703]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c45.pdf?cite=1985%20c%2045%20§%203[1985 c 45 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c9.pdf?cite=1965%20c%209%20§%2029.68.070[1965 c 9 § 29.68.070]; prior:  1921 c 33 § 1; RRS § 3798; ]

== 29A.28.041 - Congress—Special election.
. Whenever a vacancy occurs in the United States house of representatives or the United States senate from this state, the governor shall order a special election to fill the vacancy.

. Within ten days of such vacancy occurring, he or she shall issue a writ of election fixing a date for the primary at least seventy days after issuance of the writ, and fixing a date for the election at least seventy days after the date of the primary. If the vacancy is in the office of United States representative, the writ of election shall specify the congressional district that is vacant.

. If the vacancy occurs less than eight months before a general election and before the close of the filing period for that general election, the special primary and special vacancy election must be held in concert with the state primary and general election in that year.

. If the vacancy occurs on or after the first day for filing under RCW 29A.24.050 and on or before the close of the filing period, a special filing period of three normal business days shall be fixed and notice thereof given to all media, including press, radio, and television within the area in which the vacancy election is to be held, to the end that, insofar as possible, all interested persons will be aware of such filing period. 

. If the vacancy occurs later than the close of the filing period, a special primary and vacancy election to fill the position shall be held after the next general election but, in any event, no later than the ninetieth day following the general election.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=2013%20c%2011%20§%2034[2013 c 11 § 34]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5171-S.SL.pdf?cite=2011%20c%20349%20§%2014[2011 c 349 § 14]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6236.SL.pdf?cite=2006%20c%20344%20§%2012[2006 c 344 § 12]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6453.SL.pdf?cite=2004%20c%20271%20§%20118[2004 c 271 § 118]; ]

== 29A.28.050 - Congress—Notices of special primary and election.
After calling a special primary and special vacancy election to fill a vacancy in the United States house of representatives or the United States senate from this state, the governor shall immediately notify the secretary of state who shall, in turn, immediately notify the county auditor of each county wholly or partly within which the vacancy exists.

Each county auditor shall publish notices of the special primary and the special vacancy election at least once in any legal newspaper published in the county, as provided by RCW 29A.52.355.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=2013%20c%2011%20§%2035[2013 c 11 § 35]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20705[2003 c 111 § 705]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c45.pdf?cite=1985%20c%2045%20§%205[1985 c 45 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex2c36.pdf?cite=1973%202nd%20ex.s.%20c%2036%20§%205[1973 2nd ex.s. c 36 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c9.pdf?cite=1965%20c%209%20§%2029.68.100[1965 c 9 § 29.68.100]; 1909 ex.s. c 25 § 2, part; RRS § 3800, part; ]

== 29A.28.061 - Congress—General, primary election laws to apply—Time deadlines, modifications.
The general election laws and laws relating to partisan primaries shall apply to the special primaries and vacancy elections provided for in chapter 29A.28 RCW to the extent that they are not inconsistent with the provisions of these sections. Statutory time deadlines relating to availability of ballots, certification, canvassing, and related procedures that cannot be met in a timely fashion may be modified for the purposes of a specific primary or vacancy election under this chapter by the secretary of state through emergency rules adopted under RCW 29A.04.611.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=2013%20c%2011%20§%2036[2013 c 11 § 36]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5124-S.SL.pdf?cite=2011%20c%2010%20§%2028[2011 c 10 § 28]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6453.SL.pdf?cite=2004%20c%20271%20§%20119[2004 c 271 § 119]; ]

