= 29A.32 - Voters' pamphlets.
:toc:

== 29A.32.010 - Printing and distribution.
The secretary of state shall, whenever at least one statewide measure or office is scheduled to appear on the general election ballot, print and distribute a voters' pamphlet.

The secretary of state shall distribute the voters' pamphlet to each household in the state, to public libraries, and to any other locations he or she deems appropriate. The secretary of state shall also produce taped or Braille transcripts of the voters' pamphlet, publicize their availability, and mail without charge a copy to any person who requests one.

The secretary of state may make the material required to be distributed by this chapter available to the public in electronic form. The secretary of state may provide the material in electronic form to computer bulletin boards, print and broadcast news media, community computer networks, and similar services at the cost of reproduction or transmission of the data.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20801[2003 c 111 § 801]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5643.SL.pdf?cite=1999%20c%20260%20§%201[1999 c 260 § 1]; ]

== 29A.32.020 - Prohibition against deceptively similar campaign materials.
No person or entity may publish or distribute any campaign material that is deceptively similar in design or appearance to a voters' pamphlet that was published by the secretary of state during the ten-year period before the publication or distribution of the campaign material by the person or entity. The secretary of state shall take reasonable measures to prevent or to stop violations of this section. Such measures may include, among others, petitioning the superior court for a temporary restraining order or other appropriate injunctive relief. In addition, the secretary may request the superior court to impose a civil fine on a violator of this section. The court is authorized to levy on and recover from each violator a civil fine not to exceed the greater of: (1) Two dollars for each copy of the deceptive material distributed, or (2) one thousand dollars. In addition, the violator is liable for the state's legal expenses and other costs resulting from the violation. Any funds recovered under this section must be transmitted to the state treasurer for deposit in the general fund.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20802[2003 c 111 § 802]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c41.pdf?cite=1984%20c%2041%20§%201[1984 c 41 § 1]; ]

== 29A.32.031 - Contents.
The voters' pamphlet published or distributed under RCW 29A.32.010 must contain:

. Information about each measure for an advisory vote of the people and each ballot measure initiated by or referred to the voters for their approval or rejection as required by RCW 29A.32.070;

. In even-numbered years, statements, if submitted, from candidates for the office of president and vice president of the United States, United States senator, United States representative, governor, lieutenant governor, secretary of state, state treasurer, state auditor, attorney general, commissioner of public lands, superintendent of public instruction, insurance commissioner, state senator, state representative, justice of the supreme court, judge of the court of appeals, or judge of the superior court. Candidates may also submit campaign contact information and a photograph not more than five years old in a format that the secretary of state determines to be suitable for reproduction in the voters' pamphlet;

. In odd-numbered years, if any office voted upon statewide appears on the ballot due to a vacancy, then statements and photographs for candidates for any vacant office listed in subsection (2) of this section must appear;

. Contact information for the public disclosure commission established under RCW 42.17A.100, including the following statement: "For a list of the people and organizations that donated to state and local candidates and ballot measure campaigns, visit www.pdc.wa.gov." The statement must be placed in a prominent position, such as on the cover or on the first two pages of the voters' pamphlet. The secretary of state may substitute such language as is necessary for accuracy and clarity and consistent with the intent of this section;

. Contact information for major political parties;

. A brief statement explaining the deletion and addition of language for proposed measures under RCW 29A.32.080;

. A list of all student engagement hubs as designated under RCW 29A.40.180; and

. Any additional information pertaining to elections as may be required by law or in the judgment of the secretary of state is deemed informative to the voters.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6313.SL.pdf?cite=2020%20c%20208%20§%2011[2020 c 208 § 11]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5507-S.SL.pdf?cite=2013%20c%20283%20§%202[2013 c 283 § 2]; 2018 c 112 § 5; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1048-S.SL.pdf?cite=2011%20c%2060%20§%2013[2011 c 60 § 13]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6122-S.SL.pdf?cite=2009%20c%20415%20§%202[2009 c 415 § 2]; 2008 c 1 § 12 (Initiative Measure No. 960, approved November 6, 2007); http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6453.SL.pdf?cite=2004%20c%20271%20§%20121[2004 c 271 § 121]; ]

== 29A.32.032 - Party preference.
The voters' pamphlet must also contain the political party preference or independent status where a candidate appearing on the ballot has expressed such a preference on his or her declaration of candidacy.

[ 2005 c 2 § 11 (Initiative Measure No. 872, approved November 2, 2004); ]

== 29A.32.040 - Explanatory statements.
. Explanatory statements prepared by the attorney general under RCW 29A.32.070 (3) and (4) must be written in clear and concise language, avoiding legal and technical terms when possible. Statements are initiated by written request from the secretary of state, and must be filed with the secretary of state by the date provided in the request.

. When the explanatory statements for a measure initiated by petition are filed with the secretary of state, the secretary of state shall immediately provide the text of the statements to the person proposing the measure and any others who have made written request for notification of the exact language of the statements. When the statements for a measure referred to the ballot by the legislature are filed with the secretary of state, the secretary of state shall immediately provide the text of the statements to the presiding officer of the senate, the presiding officer of the house of representatives, the prime sponsor, and any others who have made written request for notification of the exact language of the statements.

. A person dissatisfied with the statements may appeal to the superior court of Thurston county within five days of the filing date. A copy of the petition and a notice of the appeal must be served on the secretary of state and the attorney general. The court shall examine the measure, the statements, and objections, and may hear arguments. The court shall render its decision and certify to and file with the secretary of state a statement it determines will meet the requirements of this chapter, and within the timelines identified by the secretary of state.

The decision of the superior court is final, and its statement is the established explanatory statement. The appeal must be heard without costs to either party.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2055.SL.pdf?cite=2015%20c%20171%20§%201[2015 c 171 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6122-S.SL.pdf?cite=2009%20c%20415%20§%203[2009 c 415 § 3]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20804[2003 c 111 § 804]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5643.SL.pdf?cite=1999%20c%20260%20§%203[1999 c 260 § 3]; ]

== 29A.32.060 - Arguments.
Committees shall write and submit arguments advocating the approval or rejection of each statewide ballot issue and rebuttals of those arguments. The secretary of state, the presiding officer of the senate, and the presiding officer of the house of representatives shall appoint the initial two members of each committee. In making these committee appointments the secretary of state and presiding officers of the senate and house of representatives shall consider legislators, sponsors of initiatives and referendums, and other interested groups known to advocate or oppose the ballot measure. Committees must have the explanatory and fiscal impact statements available before preparing their arguments.

The initial two members may select up to four additional members, and the committee shall elect a chairperson. The remaining committee member or members may fill vacancies through appointment.

After the committee submits its initial argument statements to the secretary of state, the secretary of state shall transmit the statements to the opposite committee. The opposite committee may then prepare rebuttal arguments. Rebuttals may not interject new points.

The voters' pamphlet may contain only argument statements prepared according to this section. Arguments may contain graphs and charts supported by factual statistical data and pictures or other illustrations. Cartoons or caricatures are not permitted.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2055.SL.pdf?cite=2015%20c%20171%20§%202[2015 c 171 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20806[2003 c 111 § 806]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5643.SL.pdf?cite=1999%20c%20260%20§%204[1999 c 260 § 4]; ]

== 29A.32.070 - Format, layout, contents.
The secretary of state shall determine the format and layout of the voters' pamphlet published under RCW 29A.32.010. The secretary of state shall print the pamphlet in clear, readable type on a size, quality, and weight of paper that in the judgment of the secretary of state best serves the voters. The pamphlet must contain a table of contents. Measures and arguments must be printed in the order specified by RCW 29A.72.290.

The secretary of state's name may not appear in the voters' pamphlet in his or her official capacity if the secretary is a candidate for office during the same year. His or her name may only be included as part of the information normally included for candidates.

The voters' pamphlet must provide the following information for each statewide issue on the ballot except measures for an advisory vote of the people whose requirements are provided in subsection (11) of this section:

. The legal identification of the measure by serial designation or number;

. The official ballot title of the measure;

. A statement prepared by the attorney general explaining the law as it presently exists;

. A statement prepared by the attorney general explaining the effect of the proposed measure if it becomes law;

. The fiscal impact statement prepared under RCW 29A.72.025;

. The total number of votes cast for and against the measure in the senate and house of representatives, if the measure has been passed by the legislature;

. An argument advocating the voters' approval of the measure together with any statement in rebuttal of the opposing argument;

. An argument advocating the voters' rejection of the measure together with any statement in rebuttal of the opposing argument;

. Each argument or rebuttal statement must be followed by the names of the committee members who submitted them, and may be followed by a telephone number that citizens may call to obtain information on the ballot measure;

. The full text of the measure;

. Two pages shall be provided in the general election voters' pamphlet for each measure for an advisory vote of the people under RCW 43.135.041 and shall consist of the serial number assigned by the secretary of state under RCW 29A.72.040, the short description formulated by the attorney general under RCW 29A.72.283, the tax increase's most up-to-date ten-year cost projection, including a year-by-year breakdown, by the office of financial management under RCW 43.135.031, and the names of the legislators, and their contact information, and how they voted on the increase upon final passage so they can provide information to, and answer questions from, the public. For the purposes of this subsection, "names of legislators, and their contact information" includes each legislator's position (senator or representative), first name, last name, party affiliation (for example, Democrat or Republican), city or town they live in, office phone number, and office email address.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1858.SL.pdf?cite=2016%20c%2083%20§%201[2016 c 83 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6122-S.SL.pdf?cite=2009%20c%20415%20§%205[2009 c 415 § 5]; 2008 c 1 § 13 (Initiative Measure No. 960, approved November 6, 2007); http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20807[2003 c 111 § 807]; prior:  2002 c 139 § 2; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5643.SL.pdf?cite=1999%20c%20260%20§%205[1999 c 260 § 5]; ]

== 29A.32.080 - Amendatory style.
Statewide ballot measures that amend existing law must be printed in the voters' pamphlet so that language proposed for deletion is enclosed by double parentheses and has a line through it. Proposed new language must be underlined. A statement explaining the deletion and addition of language must appear as follows: "Any language in double parentheses with a line through it is existing state law and will be taken out of the law if this measure is approved by voters. Any underlined language does not appear in current state law but will be added to the law if this measure is approved by voters."

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20808[2003 c 111 § 808]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5643.SL.pdf?cite=1999%20c%20260%20§%206[1999 c 260 § 6]; ]

== 29A.32.090 - Arguments—Rejection, dispute.
. If in the opinion of the secretary of state any argument or statement offered for inclusion in the voters' pamphlet in support of or opposition to a measure or candidate contains obscene matter or matter that is otherwise prohibited by law from distribution through the mail, the secretary may petition the superior court of Thurston county for a judicial determination that the argument or statement may be rejected for publication or edited to delete the matter. The court shall not enter such an order unless it concludes that the matter is obscene or otherwise prohibited for distribution through the mail.

. A candidate's statement submitted for inclusion in the voters' pamphlet shall not contain false or misleading statements about the candidate's opponent. A false or misleading statement shall be considered "libel or defamation per se" if the statement tends to expose the candidate to hatred, contempt, ridicule, or obloquy, or to deprive him or her of the benefit of public confidence or social intercourse, or to injure him or her in his or her business or occupation. If a candidate believes his or her opponent has libeled or defamed him or her, the candidate may commence an action under subsection (3) of this section.

. [Empty]
.. A person who believes that he or she may be defamed by an argument or statement offered for inclusion in the voters' pamphlet in support of or opposition to a measure or candidate may petition the superior court of Thurston county for a judicial determination that the argument or statement may be rejected for publication or edited to delete the defamatory statement.

.. The court shall not enter such an order unless it concludes that the statement is untrue and that the petitioner has a very substantial likelihood of prevailing in a defamation action.

.. An action under this subsection (3) must be filed and served no later than the tenth day after the deadline for the submission of the argument or statement to the secretary of state.

.. If the secretary of state notifies a person named or identified in an argument or statement of the contents of the argument or statement within three days after the deadline for submission to the secretary, then neither the state nor the secretary is liable for damages resulting from publication of the argument or statement unless the secretary publishes the argument or statement in violation of an order entered under this section. Nothing in this section creates a duty on the part of the secretary of state to identify, locate, or notify the person.

. Parties to a dispute under this section may agree to resolve the dispute by rephrasing the argument or statement, even if the deadline for submission to the secretary has elapsed, unless the secretary determines that the process of publication is too far advanced to permit the change. The secretary shall promptly provide any such revision to any committee entitled to submit a rebuttal argument. If that committee has not yet submitted its rebuttal, its deadline to submit a rebuttal is extended by five days. If it has submitted a rebuttal, it may revise it to address the change within five days of the filing of the revised argument with the secretary.

. In an action under this section the committee or candidate must be named as a defendant, and may be served with process by certified mail directed to the address contained in the secretary's records for that party. The secretary of state shall be a nominal party to an action brought under subsection (3) of this section, solely for the purpose of determining the content of the voters' pamphlet. The superior court shall give such an action priority on its calendar.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1286-S.SL.pdf?cite=2009%20c%20222%20§%203[2009 c 222 § 3]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20809[2003 c 111 § 809]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5643.SL.pdf?cite=1999%20c%20260%20§%208[1999 c 260 § 8]; ]

== 29A.32.100 - Arguments—Public inspection.
. An argument or statement submitted to the secretary of state for publication in the voters' pamphlet is not available for public inspection or copying until:

.. In the case of candidate statements, (i) all statements by all candidates who have filed for a particular office have been received, except those who informed the secretary that they will not submit statements, or (ii) the deadline for submission of statements has elapsed;

.. In the case of arguments supporting or opposing a measure, (i) the arguments on both sides have been received, unless a committee was not appointed for one side, or (ii) the deadline for submission of arguments has elapsed; and

.. In the case of rebuttal arguments, (i) the rebuttals on both sides have been received, unless a committee was not appointed for one side, or (ii) the deadline for submission of arguments has elapsed.

. Nothing in this section prohibits the secretary from releasing information under RCW 29A.32.090.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=2013%20c%2011%20§%2037[2013 c 11 § 37]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20810[2003 c 111 § 810]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5643.SL.pdf?cite=1999%20c%20260%20§%209[1999 c 260 § 9]; ]

== 29A.32.110 - Photographs.
All photographs of candidates submitted for publication must conform to standards established by the secretary of state by rule. No photograph may reveal clothing or insignia suggesting the holding of a public office.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20811[2003 c 111 § 811]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5643.SL.pdf?cite=1999%20c%20260%20§%2010[1999 c 260 § 10]; ]

== 29A.32.121 - Candidates' statements—Length.
. The maximum number of words for statements submitted by candidates is as follows: State representative, one hundred words; state senator, judge of the superior court, judge of the court of appeals, justice of the supreme court, and all state offices voted upon throughout the state, except that of governor, two hundred words; president and vice president, United States senator, United States representative, and governor, three hundred words.

. Arguments written by committees under RCW 29A.32.060 may not exceed two hundred fifty words in length.

. Rebuttal arguments written by committees may not exceed seventy-five words in length.

. The secretary of state shall allocate space in the pamphlet based on the number of candidates or nominees for each office.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6453.SL.pdf?cite=2004%20c%20271%20§%20168[2004 c 271 § 168]; ]

== 29A.32.210 - Authorization—Contents—Format. (Effective until July 1, 2021.)
At least ninety days before any primary or general election, or at least forty days before any special election held under RCW 29A.04.321 or 29A.04.330, the legislative authority of any county or first-class or code city may adopt an ordinance authorizing the publication and distribution of a local voters' pamphlet. The pamphlet shall provide information on all measures within that jurisdiction and may, if specified in the ordinance, include information on candidates within that jurisdiction. If both a county and a first-class or code city within that county authorize a local voters' pamphlet for the same election, the pamphlet shall be produced jointly by the county and the first-class or code city. If no agreement can be reached between the county and first-class or code city, the county and first-class or code city may each produce a pamphlet. Any ordinance adopted authorizing a local voters' pamphlet may be for a specific primary, special election, or general election or for any future primaries or elections. The format of any local voters' pamphlet shall, whenever applicable, comply with the provisions of this chapter regarding the publication of the state candidates' and voters' pamphlets.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=2013%20c%2011%20§%2038[2013 c 11 § 38]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20813[2003 c 111 § 813]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c106.pdf?cite=1984%20c%20106%20§%203[1984 c 106 § 3]; ]

== 29A.32.220 - Notice of production—Local governments' decision to participate.
. Not later than ninety days before the publication and distribution of a local voters' pamphlet by a county, the county auditor shall notify each city, town, or special taxing district located wholly within that county that a pamphlet will be produced. 

. If a voters' pamphlet is published by the county for a primary or general election, the pamphlet shall be published for the elective offices and ballot measures of the county and for the elective offices and ballot measures of each unit of local government located entirely within the county which will appear on the ballot at that primary or election. However, the offices and measures of a first-class or code city shall not be included in the pamphlet if the city publishes and distributes its own voters' pamphlet for the primary or election for its offices and measures. The offices and measures of any other town or city are not required to appear in the county's pamphlet if the town or city is obligated by ordinance or charter to publish and distribute a voters' pamphlet for the primary or election for its offices and measures and it does so.

If the required appearance in a county's voters' pamphlet of the offices or measures of a unit of local government would create undue financial hardship for the unit of government, the legislative authority of the unit may petition the legislative authority of the county to waive this requirement. The legislative authority of the county may provide such a waiver if it does so not later than sixty days before the publication of the pamphlet and it finds that the requirement would create such hardship.

. If a city, town, or district is located within more than one county, the respective county auditors may enter into an interlocal agreement to permit the distribution of each county's local voters' pamphlet into those parts of the city, town, or district located outside of that county.

. If a first-class or code city authorizes the production and distribution of a local voters' pamphlet, the city clerk of that city shall notify any special taxing district located wholly within that city that a pamphlet will be produced. Notification shall be provided in the manner required or provided for in subsection (1) of this section.

. A unit of local government located within a county and the county may enter into an interlocal agreement for the publication of a voters' pamphlet for offices or measures not required by subsection (2) of this section to appear in a county's pamphlet.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20814[2003 c 111 § 814]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6063-S.SL.pdf?cite=1994%20c%20191%20§%201[1994 c 191 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c106.pdf?cite=1984%20c%20106%20§%204[1984 c 106 § 4]; ]

== 29A.32.230 - Administrative rules.
The county auditor or, if applicable, the city clerk of a first-class or code city shall, in consultation with the participating jurisdictions, adopt and publish administrative rules necessary to facilitate the provisions of any ordinance authorizing production of a local voters' pamphlet. Any amendment to such a rule shall also be adopted and published. Copies of the rules shall identify the date they were adopted or last amended and shall be made available to any person upon request. One copy of the rules adopted by a county auditor and one copy of any amended rules shall be submitted to the county legislative authority. One copy of the rules adopted by a city clerk and one copy of any amended rules shall be submitted to the city legislative authority. These rules shall include but not be limited to the following:

. Deadlines for decisions by cities, towns, or special taxing districts on being included in the pamphlet;

. Limits on the length and deadlines for submission of arguments for and against each measure;

. The basis for rejection of any explanatory or candidates' statement or argument deemed to be libelous or otherwise inappropriate. Any statements by a candidate shall be limited to those about the candidate himself or herself;

. Limits on the length and deadlines for submission of candidates' statements;

. An appeal process in the case of the rejection of any statement or argument.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20815[2003 c 111 § 815]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c106.pdf?cite=1984%20c%20106%20§%205[1984 c 106 § 5]; ]

== 29A.32.241 - Contents.
. The local voters' pamphlet shall include but not be limited to the following:

.. Appearing on the cover, the words "official local voters' pamphlet," the name of the jurisdiction producing the pamphlet, and the date of the election or primary;

.. A list of jurisdictions that have measures or candidates in the pamphlet;

.. Information on how a person may register to vote and obtain a ballot;

.. The text of each measure accompanied by an explanatory statement prepared by the prosecuting attorney for any county measure or by the attorney for the jurisdiction submitting the measure if other than a county measure. All explanatory statements for city, town, or district measures not approved by the attorney for the jurisdiction submitting the measure shall be reviewed and approved by the county prosecuting attorney or city attorney, when applicable, before inclusion in the pamphlet;

.. The arguments for and against each measure submitted by committees selected pursuant to RCW 29A.32.280;

.. A list of all student engagement hubs in the county as designated under RCW 29A.40.180; and

.. For partisan primary elections, information on how to vote the applicable ballot format and an explanation that minor political party candidates and independent candidates will appear only on the general election ballot.

. The county auditor's name may not appear in the local voters' pamphlet in his or her official capacity if the county auditor is a candidate for office during the same year. His or her name may only be included as part of the information normally included for candidates.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6313.SL.pdf?cite=2020%20c%20208%20§%2012[2020 c 208 § 12]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1858.SL.pdf?cite=2016%20c%2083%20§%202[2016 c 83 § 2]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5124-S.SL.pdf?cite=2011%20c%2010%20§%2029[2011 c 10 § 29]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6453.SL.pdf?cite=2004%20c%20271%20§%20123[2004 c 271 § 123]; ]

== 29A.32.250 - Candidates, when included.
If the legislative authority of a county or first-class or code city provides for the inclusion of candidates in the local voters' pamphlet, the pamphlet shall include the statements from candidates and may also include those candidates' photographs.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20817[2003 c 111 § 817]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c106.pdf?cite=1984%20c%20106%20§%207[1984 c 106 § 7]; ]

== 29A.32.260 - Mailing.
As soon as practicable before the primary, special election, or general election, the county auditor, or if applicable, the city clerk of a first-class or code city, as appropriate, shall mail the local voters' pamphlet to every residence in each jurisdiction that has included information in the pamphlet. The county auditor or city clerk, as appropriate, may choose to mail the pamphlet to each registered voter in each jurisdiction that has included information in the pamphlet, if in his or her judgment, a more economical and effective distribution of the pamphlet would result.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5124-S.SL.pdf?cite=2011%20c%2010%20§%2030[2011 c 10 § 30]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20818[2003 c 111 § 818]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c106.pdf?cite=1984%20c%20106%20§%208[1984 c 106 § 8]; ]

== 29A.32.270 - Cost.
The cost of a local voters' pamphlet shall be considered an election cost to those local jurisdictions included in the pamphlet and shall be prorated in the manner provided in RCW 29A.04.410.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20819[2003 c 111 § 819]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c106.pdf?cite=1984%20c%20106%20§%209[1984 c 106 § 9]; ]

== 29A.32.280 - Arguments advocating approval or disapproval—Preparation by committees.
For each measure from a unit of local government that is included in a local voters' pamphlet, the legislative authority of that jurisdiction shall, not later than the resolution deadline, formally appoint a committee to prepare arguments advocating voters' approval of the measure and shall formally appoint a committee to prepare arguments advocating voters' rejection of the measure. The authority shall appoint persons known to favor the measure to serve on the committee advocating approval and shall, whenever possible, appoint persons known to oppose the measure to serve on the committee advocating rejection. Each committee shall have not more than three members, however, a committee may seek the advice of any person or persons. If the legislative authority of a unit of local government fails to make such appointments by the prescribed deadline, the county auditor shall whenever possible make the appointments.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1919-S.SL.pdf?cite=2015%20c%20146%20§%203[2015 c 146 § 3]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5221-S.SL.pdf?cite=2003%20c%20111%20§%20820[2003 c 111 § 820]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6063-S.SL.pdf?cite=1994%20c%20191%20§%202[1994 c 191 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c106.pdf?cite=1984%20c%20106%20§%2010[1984 c 106 § 10]; ]

