= 58.09 - Surveys—Recording.
:toc:

== 58.09.010 - Purpose—Short title.
The purpose of this chapter is to provide a method for preserving evidence of land surveys by establishing standards and procedures for monumenting and for recording a public record of the surveys. Its provisions shall be deemed supplementary to existing laws relating to surveys, subdivisions, platting, and boundaries.

This chapter shall be known and may be cited as the "Survey Recording Act".

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c50.pdf?cite=1973%20c%2050%20§%201[1973 c 50 § 1]; ]

== 58.09.020 - Definitions.
As used in this chapter:

. "Land surveyor" shall mean every person authorized to practice the profession of land surveying under the provisions of chapter 18.43 RCW, as now or hereafter amended.

. "*Washington coordinate system" shall mean that system of plane coordinates as established and designated by chapter 58.20 RCW.

. "Survey" shall mean the locating and monumenting in accordance with sound principles of land surveying by or under the supervision of a licensed land surveyor, of points or lines which define the exterior boundary or boundaries common to two or more ownerships or which reestablish or restore general land office corners.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c50.pdf?cite=1973%20c%2050%20§%202[1973 c 50 § 2]; ]

== 58.09.030 - Compliance with chapter required.
Any land surveyor engaged in the practice of land surveying may prepare maps, plats, reports, descriptions, or other documentary evidence in connection therewith.

Every map, plat, report, description, or other document issued by a licensed land surveyor shall comply with the provisions of this chapter whenever such map, plat, report, description, or other document is filed as a public record.

It shall be unlawful for any person to sign, stamp, or seal any map, report, plat, description, or other document for filing under this chapter unless he or she be a land surveyor.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%2018002[2010 c 8 § 18002]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c50.pdf?cite=1973%20c%2050%20§%203[1973 c 50 § 3]; ]

== 58.09.040 - Records of survey—Contents—Filing—Replacing corner, filing record.
After making a survey in conformity with sound principles of land surveying, a land surveyor may file a record of survey with the county auditor in the county or counties wherein the lands surveyed are situated.

. It shall be mandatory, within ninety days after the establishment, reestablishment, or restoration of a corner on the boundary of two or more ownerships or general land office corner by survey that a land surveyor shall file with the county auditor in the county or counties wherein the lands surveyed are situated a record of such survey, in such form as to meet the requirements of this chapter, which through accepted survey procedures, shall disclose:

.. The establishment of a corner which materially varies from the description of record;

.. The establishment of one or more property corners not previously existing;

.. Evidence that reasonable analysis might result in alternate positions of lines or points as a result of an ambiguity in the description;

.. The reestablishment of lost government land office corners.

. When a licensed land surveyor, while conducting work of a preliminary nature or other activity that does not constitute a survey required by law to be recorded, replaces, or restores an existing or obliterated general land office corner, it is mandatory that, within ninety days thereafter, he or she shall file with the county auditor in the county in which said corner is located a record of the monuments and accessories found or placed at the corner location, in such form as to meet the requirements of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%2018003[2010 c 8 § 18003]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c50.pdf?cite=1973%20c%2050%20§%204[1973 c 50 § 4]; ]

== 58.09.050 - Records of survey—Processing—Requirements.
The records of survey to be filed under authority of this chapter shall be processed as follows:

. [Empty]
.. The record of survey filed under RCW 58.09.040(1) shall be an original map, eighteen by twenty-four inches, that is legibly drawn in black ink on mylar and is suitable for producing legible prints through scanning, microfilming, or other standard copying procedures.

.. The following are allowable formats for the original that may be used in lieu of the format set forth under (a) of this subsection:

... Photo mylar with original signatures;

... Any standard material as long as the format is compatible with the auditor's recording process and records storage system. This format is only allowed in those counties that are excepted from permanently storing the original document as required in RCW 58.09.110(5);

... An electronic version of the original if the county has the capability to accept electronic signatures which meet the standards provided by the rules adopted by the Washington state board of registration for professional engineers and land surveyors, and can import electronic files into an imaging system. The electronic version shall be a standard raster file format acceptable to the county.

A two inch margin on the left edge and a one-half inch margin on other edges of the map shall be provided. The auditor shall reject for recording any maps not suitable for producing legible prints through scanning, microfilming, or other standard copying procedures.

. Information required by RCW 58.09.040(2) shall be filed on a standard form eight and one-half inches by fourteen inches as designed and prescribed by the department of natural resources. The auditor shall reject for recording any records of corner information not suitable for producing legible prints through scanning, microfilming, or other standard copying procedures. An electronic version of the standard form may be filed if the county has the capability to accept electronic signatures which meet the standards provided by the rules adopted by the Washington state board of registration for professional engineers and land surveyors, and can import electronic files into an imaging system. The electronic version shall be a standard raster file format acceptable to the county.

. Two legible prints of each record of survey as required under the provisions of this chapter shall be furnished to the county auditor in the county in which the survey is to be recorded. The auditor, in those counties using imaging systems, may require only the original, and fewer prints, as needed, to meet the requirements of their duties. If any of the prints submitted are not suitable for scanning or microfilming the auditor shall not record the original.

. Legibility requirements are set forth in the recorder's checklist under RCW 58.09.110.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2085[2020 c 57 § 85]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1908.SL.pdf?cite=2019%20c%20132%20§%206[2019 c 132 § 6]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1542.SL.pdf?cite=1999%20c%2039%20§%201[1999 c 39 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c50.pdf?cite=1973%20c%2050%20§%205[1973 c 50 § 5]; ]

== 58.09.060 - Records of survey, contents—Record of corner, information.
. The record of survey as required by RCW 58.09.040(1) shall show:

.. All monuments found, set, reset, replaced, or removed, describing their kind, size, and location and giving other data relating thereto;

.. Bearing trees, corner accessories or witness monuments, basis of bearings, bearing and length of lines, scale of map, and north arrow;

.. Name and legal description of tract in which the survey is located and ties to adjoining surveys of record;

.. Certificates required by RCW 58.09.080;

.. Any other data necessary for the intelligent interpretation of the various items and locations of the points, lines and areas shown.

. The record of corner information as required by RCW 58.09.040(2) shall be on a standard form showing:

.. An accurate description and location, in reference to the corner position, of all monuments and accessories found at the corner;

.. An accurate description and location, in reference to the corner position, of all monuments and accessories placed or replaced at the corner;

.. Basis of bearings used to describe or locate such monuments or accessories;

.. Corollary information that may be helpful to relocate or identify the corner position;

.. Certificate required by RCW 58.09.080.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c50.pdf?cite=1973%20c%2050%20§%206[1973 c 50 § 6]; ]

== 58.09.070 - Coordinates—Map showing control scheme required.
When coordinates in the *Washington coordinate system are shown for points on a record of survey map, the map may not be recorded unless it also shows, or is accompanied by a map showing, the control scheme through which the coordinates were determined from points of known coordinates.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c50.pdf?cite=1973%20c%2050%20§%207[1973 c 50 § 7]; ]

== 58.09.080 - Certificates—Required—Forms.
Certificates shall appear on the record of survey map as follows:

SURVEYOR'S CERTIFICATE

This map correctly represents a survey made by me or under my direction in conformance with the requirements of the Survey Recording Act at the request of . . . . . . . . . in . . . . . ., (year) . . . .

 Name of Person (Signed and Sealed) . . . . Certificate No. . . . .

 

Name of Person

 

(Signed and Sealed) . . . .

 

Certificate No. . . . .

AUDITOR'S CERTIFICATE

Filed for record this . . . . day of . . . . . ., (year) . . . . at . . . . .M. in book . . . . of . . . . at page . . . . at the request of . . . . . . . . .

 (Signed) . . . . County Auditor

 

(Signed) . . . .

 

County Auditor

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2359-S.SL.pdf?cite=2016%20c%20202%20§%2034[2016 c 202 § 34]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c50.pdf?cite=1973%20c%2050%20§%208[1973 c 50 § 8]; ]

== 58.09.090 - When record of survey not required.
. A record of survey is not required of any survey:

.. When it has been made by a public officer in his or her official capacity and a reproducible copy thereof has been filed with the county engineer of the county in which the land is located. A map so filed shall be indexed and kept available for public inspection. A record of survey shall not be required of a survey made by the United States bureau of land management. A state agency conducting surveys to carry out the program of the agency shall not be required to use a land surveyor as defined by this chapter;

.. When it is of a preliminary nature;

.. When a map is in preparation for recording or shall have been recorded in the county under any local subdivision or platting law or ordinance;

.. When it is a retracement or resurvey of boundaries of platted lots, tracts, or parcels shown on a filed or recorded and surveyed subdivision plat or filed or recorded and surveyed short subdivision plat in which monuments have been set to mark all corners of the block or street centerline intersections, provided that no discrepancy is found as compared to said recorded information or information revealed on other subsequent public survey map records, such as a record of survey or city or county engineer's map. If a discrepancy is found, that discrepancy must be clearly shown on the face of the required new record of survey. For purposes of this exemption, the term discrepancy shall include:

... A nonexisting or displaced original or replacement monument from which the parcel is defined and which nonexistence or displacement has not been previously revealed in the public record;

... A departure from proportionate measure solutions which has not been revealed in the public record;

... The presence of any physical evidence of encroachment or overlap by occupation or improvement; or

... Differences in linear and/or angular measurement between all controlling monuments that would indicate differences in spatial relationship between said controlling monuments in excess of 0.50 feet when compared with all locations of public record: That is, if these measurements agree with any previously existing public record plat or map within the stated tolerance, a discrepancy will not be deemed to exist under this subsection.

. Surveys exempted by foregoing subsections of this section shall require filing of a record of corner information pursuant to RCW 58.09.040(2).

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%2018004[2010 c 8 § 18004]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5557-S.SL.pdf?cite=1992%20c%20106%20§%201[1992 c 106 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c50.pdf?cite=1973%20c%2050%20§%209[1973 c 50 § 9]; ]

== 58.09.100 - Filing fee.
The charge for filing any record of survey and/or record of corner information shall be fixed by the board of county commissioners.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c50.pdf?cite=1973%20c%2050%20§%2010[1973 c 50 § 10]; ]

== 58.09.110 - Duties of county auditor.
The auditor shall accept for recording those records of survey and records of corner information that are in compliance with the recorder's checklist as jointly developed by a committee consisting of the survey advisory board and two representatives from the Washington state association of county auditors. This checklist shall be adopted in rules by the department of natural resources.

. The auditor shall keep proper indexes of such record of survey by the name of owner and by quarter-quarter section, township, and range, with reference to other legal subdivisions.

. The auditor shall keep proper indexes of the record of corner information by section, township, and range.

. After entering the recording data on the record of survey and all prints received from the surveyor, the auditor shall send one of the surveyor's prints to the department of natural resources in Olympia, Washington, for incorporation into the statewide survey records repository. However, the county and the department of natural resources may mutually agree to process the original or an electronic version of the original in lieu of the surveyor's print.

. After entering the recording data on the record of corner information the auditor shall send a legible copy, suitable for scanning, to the department of natural resources in Olympia, Washington. However, the county and the department of natural resources may mutually agree to process the original or an electronic version of the original in lieu of the copy.

. The auditor shall permanently keep the original document filed using storage and handling processes that do not cause excessive deterioration of the document. A county may be excepted from the requirement to permanently store the original document if it has a document scanning, filming, or other process that creates a permanent, archival record that meets or surpasses the standards as adopted in rule by the division of archives and records management in chapter 434-663 or 434-677 WAC. The auditor must be able to provide full-size copies upon request. The auditor shall maintain a copy or image of the original for public reference.

. If the county has the capability to accept electronic signatures which meet the standards provided by the rules adopted by the Washington state board of registration for professional engineers and land surveyors, and can import electronic files into an imaging system, the auditor may accept for recording electronic versions of the documents required by this chapter. The electronic version shall be a standard raster file format acceptable to the county.

. This section does not supersede other existing recording statutes.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2086[2020 c 57 § 86]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1908.SL.pdf?cite=2019%20c%20132%20§%207[2019 c 132 § 7]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1542.SL.pdf?cite=1999%20c%2039%20§%202[1999 c 39 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c50.pdf?cite=1973%20c%2050%20§%2011[1973 c 50 § 11]; ]

== 58.09.120 - Monuments—Requirements.
Any monument set by a land surveyor to mark or reference a point on a property or land line shall be permanently marked or tagged with the certificate number of the land surveyor setting it. If the monument is set by a public officer it shall be marked by an appropriate official designation.

Monuments set by a land surveyor shall be sufficient in number and durability and shall be efficiently placed so as not to be readily disturbed in order to assure, together with monuments already existing, the perpetuation or reestablishment of any point or line of a survey.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c50.pdf?cite=1973%20c%2050%20§%2012[1973 c 50 § 12]; ]

== 58.09.130 - Monuments disturbed by construction activities—Procedure—Requirements.
When adequate records exist as to the location of subdivision, tract, street, or highway monuments, such monuments shall be located and referenced by or under the direction of a land surveyor at the time when streets or highways are reconstructed or relocated, or when other construction or activity affects their perpetuation. Whenever practical a suitable monument shall be reset in the surface of the new construction. In all other cases permanent witness monuments shall be set to perpetuate the location of preexisting monuments. Additionally, sufficient controlling monuments shall be retained or replaced in their original positions to enable land lines, property corners, elevations and tract boundaries to be reestablished without requiring surveys originating from monuments other than the ones disturbed by the current construction or activity.

It shall be the responsibility of the governmental agency or others performing construction work or other activity to provide for the monumentation required by this section. It shall be the duty of every land surveyor to cooperate with such governmental agency or other person in matters of maps, field notes, and other pertinent records. Monuments set to mark the limiting lines of highways, roads, or streets shall not be deemed adequate for this purpose unless specifically noted on the records of the improvement works with direct ties in bearing or azimuth and distance between those and other monuments of record.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c50.pdf?cite=1973%20c%2050%20§%2013[1973 c 50 § 13]; ]

== 58.09.140 - Noncompliance grounds for revocation of land surveyor's license.
Noncompliance with any provision of this chapter, as it now exists or may hereafter be amended, shall constitute grounds for revocation of a land surveyor's authorization to practice the profession of land surveying and as further set forth under RCW 18.43.105 and 18.43.110.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c50.pdf?cite=1973%20c%2050%20§%2014[1973 c 50 § 14]; ]

