= 58.04 - Boundaries.
:toc:

== 58.04.001 - Purpose—Remedies.
The purpose of this chapter is to provide alternative procedures for fixing boundary points or lines when they cannot be determined from the existing public record and landmarks or are otherwise in dispute. This chapter does not impair, modify, or supplant any other remedy available at law or equity.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6266-S.SL.pdf?cite=1996%20c%20160%20§%201[1996 c 160 § 1]; ]

== 58.04.003 - Definition of surveyor.
As used in this chapter, "surveyor" means every person authorized to practice the profession of land surveying under the provisions of chapter 18.43 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6266-S.SL.pdf?cite=1996%20c%20160%20§%202[1996 c 160 § 2]; ]

== 58.04.007 - Affected landowners may resolve dispute over location of a point or line—Procedures.
Whenever a point or line determining the boundary between two or more parcels of real property cannot be identified from the existing public record, monuments, and landmarks, or is in dispute, the landowners affected by the determination of the point or line may resolve any dispute and fix the boundary point or line by one of the following procedures:

. If all of the affected landowners agree to a description and marking of a point or line determining a boundary, they shall document the agreement in a written instrument, using appropriate legal descriptions and including a survey map, filed in accordance with chapter 58.09 RCW. The written instrument shall be signed and acknowledged by each party in the manner required for a conveyance of real property. The agreement is binding upon the parties, their successors, assigns, heirs and devisees and runs with the land. The agreement shall be recorded with the real estate records in the county or counties in which the affected parcels of real estate or any portion of them is located;

. If all of the affected landowners cannot agree to a point or line determining the boundary between two or more parcels of real estate, any one of them may bring suit for determination as provided in RCW 58.04.020.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6266-S.SL.pdf?cite=1996%20c%20160%20§%203[1996 c 160 § 3]; ]

== 58.04.011 - Authorization to enter upon any land or waters for purpose of resolving dispute.
Any surveyor authorized by the court and the surveyor's employees may, without liability for trespass, enter upon any land or waters and remain there while performing the duties as required in RCW 58.04.001 through 58.04.007 and this section. The persons named in this section may, without liability for trespass, investigate, construct, or place a monument or reference monuments for the position of any land boundary mark or general land office corner or mark and subdivisional corners thereof. Persons entering lands under the authority of RCW 58.04.001 through 58.04.007 and this section must exercise due care not to damage property while on land or waters performing their duties, and are liable for property damage, if any, caused by their negligence or willful misconduct. Where practical, the persons named in this section must announce and identify themselves and their intention before entering upon private property in the performance of their duties.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6266-S.SL.pdf?cite=1996%20c%20160%20§%204[1996 c 160 § 4]; ]

== 58.04.015 - Disturbing a survey monument—Penalty—Cost.
A person who intentionally disturbs a survey monument placed by a surveyor in the performance of the surveyor's duties is guilty of a gross misdemeanor and is liable for the cost of the reestablishment.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6266-S.SL.pdf?cite=1996%20c%20160%20§%205[1996 c 160 § 5]; ]

== 58.04.020 - Suit to establish lost or uncertain boundaries—Mediation may be required.
. Whenever the boundaries of lands between two or more adjoining proprietors have been lost, or by time, accident or any other cause, have become obscure, or uncertain, and the adjoining proprietors cannot agree to establish the same, one or more of the adjoining proprietors may bring a civil action in equity, in the superior court, for the county in which such lands, or part of them are situated, and that superior court, as a court of equity, may upon the complaint, order such lost or uncertain boundaries to be erected and established and properly marked.

. The superior court may order the parties to utilize mediation before the civil action is allowed to proceed.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6266-S.SL.pdf?cite=1996%20c%20160%20§%208[1996 c 160 § 8]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1886%20p%20104%20§%201[1886 p 104 § 1]; RRS § 947; ]

== 58.04.030 - Commissioners—Survey and report.
Said court may, in its discretion, appoint commissioners, not exceeding three competent and disinterested persons, one or more of whom shall be practical surveyors, residents of the state, which commissioners shall be, before entering upon their duties, duly sworn to perform their said duties faithfully, and the said commissioners shall thereupon, survey, erect, establish and properly mark said boundaries, and return to the court a plat of said survey, and the field notes thereof, together with their report. Said report shall be advisory and either party may except thereto, in the same manner as to a report of referees.

[ http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1886%20p%20105%20§%202[1886 p 105 § 2]; RRS § 948; ]

== 58.04.040 - Proceedings, conduct of—Costs.
The proceedings shall be conducted as other civil actions, and the court, on final decree, shall apportion the costs of the proceedings equitably, and the cost so apportioned, shall be a lien upon the said lands, severally, as against any transfer or incumbrance made of, or attaching to said lands, from the time of the filing of the complaint: PROVIDED, A notice of lis pendens, is filed in the auditor's office of the proper county, in accordance with law.

[ http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1886%20p%20105%20§%203[1886 p 105 § 3]; RRS § 949; ]

