= 58.22 - State base mapping system.
:toc:

== 58.22.010 - Legislative intent.
It is the intent of the legislature to establish a coordinated system of state base maps to assist all levels of government to more effectively provide the information to meet their responsibilities for resource planning and management.

It is further the legislature's intent to eliminate duplication, to insure compatibility, and to create coordination through a uniform base which all agencies will use.

It is in the interest of all citizens in the state of Washington that a state base mapping system be established to make essential base maps available at cost to all users, both public and private.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c159.pdf?cite=1973%201st%20ex.s.%20c%20159%20§%201[1973 1st ex.s. c 159 § 1]; ]

== 58.22.020 - Establishment and maintenance—Standards.
The department of natural resources shall establish and maintain a state base mapping system. The standards for the state base mapping system shall be:

. A series of fifteen minute United States geological survey quadrangle map separates at a scale of one to 48,000 (one inch equals 4,000 feet) covering the entire state;

. A series of seven and one-half minute United States geological survey quadrangle map separates at a scale of one to 24,000 (one inch equals 2,000 feet) for urban areas; including but not limited to those identified as urban by the state department of transportation for the United States department of transportation.

All features and symbols added to the quadrangle separates shall meet as nearly as is practical national map accuracy standards and specifications as defined by the United States geological survey for their fifteen minute and seven and one-half minute quadrangle map separates.

Each quadrangle shall be revised by the department of natural resources as necessary to reflect current conditions.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%20367[1984 c 7 § 367]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c159.pdf?cite=1973%201st%20ex.s.%20c%20159%20§%202[1973 1st ex.s. c 159 § 2]; ]

== 58.22.030 - United States geological survey quadrangle map separates—Acquisition by state agencies.
Any state agency purchasing or acquiring United States geological survey quadrangle map separates shall do so through the department of natural resources.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c159.pdf?cite=1973%201st%20ex.s.%20c%20159%20§%203[1973 1st ex.s. c 159 § 3]; ]

== 58.22.040 - United States geological survey quadrangle map separates—State depository.
The department of natural resources shall be the primary depository of all United States geological survey quadrangle map separates for state agencies: PROVIDED, That any state agency may maintain duplicate copies.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c159.pdf?cite=1973%201st%20ex.s.%20c%20159%20§%204[1973 1st ex.s. c 159 § 4]; ]

== 58.22.050 - Availability of map separates—Powers and duties of department.
. All United States geological survey quadrangle map separates shall be available at cost to all state agencies, local agencies, the federal government, and any private individual or company through duplication and purchase.

The department shall coordinate all requests for the use of United States geological survey quadrangle map separates and shall provide advice on how to best use the system.

. The department shall maintain a catalogue showing all United States geological survey quadrangle map separates available. The department shall also catalogue information describing additional separates or products created by users. Copies of maps made for any state or local agency shall be available to any other state or local agency.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c159.pdf?cite=1973%201st%20ex.s.%20c%20159%20§%205[1973 1st ex.s. c 159 § 5]; ]

