= 46.04 - Definitions.
:toc:

== 46.04.010 - Scope and construction of terms.
Terms used in this title shall have the meaning given to them in this chapter except where otherwise defined, and unless where used the context thereof shall clearly indicate to the contrary.

Words and phrases used herein in the past, present or future tense shall include the past, present and future tenses; words and phrases used herein in the masculine, feminine or neuter gender shall include the masculine, feminine and neuter genders; and words and phrases used herein in the singular or plural shall include the singular and plural; unless the context thereof shall indicate to the contrary.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.010[1961 c 12 § 46.04.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%202[1959 c 49 § 2]; prior:  1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part; 1923 c 181 § 1, part; 1921 c 96 § 2, part; 1919 c 59 § 1, part; 1917 c 155 § 1, part; 1915 c 142 § 2, part; RRS § 6313, part.  1937 c 189 § 1, part; RRS § 6360-1, part; 1929 c 180 § 1, part; 1927 c 309 § 2, part; RRS § 6362-2, part; ]

== 46.04.011 - 4-H license plates.
"4-H license plates" means special license plates issued under RCW 46.18.200 that display the "4-H" logo.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2299-S.SL.pdf?cite=2012%20c%2065%20§%202[2012 c 65 § 2]; ]

== 46.04.013 - Affidavit of loss.
"Affidavit of loss" means a written statement confirming that the certificate of title, registration certificate, gross weight license, validation tab, or decal has been lost, stolen, destroyed, or mutilated. The statement must be in a form prescribed by the director.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20101[2010 c 161 § 101]; ]

== 46.04.014 - Agent.
"Agent," for the purposes of entering into the standard contract required under RCW 46.01.140(1), means any county auditor or other individual, government, or business entity other than a subagent that is appointed to carry out vehicle registration and certificate of title functions for the department.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20102[2010 c 161 § 102]; ]

== 46.04.015 - Alcohol concentration.
"Alcohol concentration" means (1) grams of alcohol per two hundred ten liters of a person's breath, or (2) grams of alcohol per one hundred milliliters of a person's blood.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5141-S.SL.pdf?cite=1995%20c%20332%20§%2017[1995 c 332 § 17]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6047-S.SL.pdf?cite=1994%20c%20275%20§%201[1994 c 275 § 1]; ]

== 46.04.020 - Alley.
"Alley" means a public highway not designed for general travel and used primarily as a means of access to the rear of residences and business establishments.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.020[1961 c 12 § 46.04.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%203[1959 c 49 § 3]; prior: 1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.022 - Amateur radio operator license plates.
"Amateur radio operator license plates" means special license plates displaying amateur radio call letters assigned by the federal communications commission.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20103[2010 c 161 § 103]; ]

== 46.04.028 - Armed forces license plate collection.
"Armed forces license plate collection" means the collection of six separate license plate designs issued under RCW 46.18.210. Each license plate design displays a symbol representing one of the five branches of the armed forces, and one representing the national guard.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20104[2010 c 161 § 104]; ]

== 46.04.030 - Arterial highway.
"Arterial highway" means every public highway, or portion thereof, designated as such by proper authority.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.030[1961 c 12 § 46.04.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%204[1959 c 49 § 4]; prior: 1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.040 - Authorized emergency vehicle.
"Authorized emergency vehicle" means any vehicle of any fire department, police department, sheriff's office, coroner, prosecuting attorney, Washington state patrol, ambulance service, public or private, which need not be classified, registered or authorized by the state patrol, or any other vehicle authorized in writing by the state patrol.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c330.pdf?cite=1987%20c%20330%20§%20701[1987 c 330 § 701]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.040[1961 c 12 § 46.04.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%205[1959 c 49 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c40.pdf?cite=1953%20c%2040%20§%201[1953 c 40 § 1]; prior:  1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part.  1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.050 - Auto stage.
"Auto stage" means any motor vehicle used for the purpose of carrying passengers together with incidental baggage and freight or either, on a regular schedule of time and rates: PROVIDED, That no motor vehicle shall be considered to be an auto stage where substantially the entire route traveled by such vehicle is within the corporate limits of any city or town or the corporate limits of any adjoining cities or towns.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.050[1961 c 12 § 46.04.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%206[1959 c 49 § 6]; prior:  1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part; 1923 c 181 § 1, part; 1921 c 96 § 2, part; 1919 c 59 § 1, part; 1917 c 155 § 1, part; 1915 c 142 § 1, part; RRS § 6313, part.  1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.060 - Axle.
"Axle" means structure or structures in the same or approximately the same transverse plane with a vehicle supported by wheels and on which or with which such wheels revolve.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.060[1961 c 12 § 46.04.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%207[1959 c 49 § 7]; prior:  1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part; 1923 c 181 § 1, part; RRS § 6313, part.  1937 c 189 § 1, part; RRS § 6360-1, part; 1929 c 180 § 1, part; 1927 c 309 § 2, part; RRS § 6362-2, part; ]

== 46.04.071 - Bicycle.
"Bicycle" means every device propelled solely by human power, or an electric-assisted bicycle as defined in RCW 46.04.169, upon which a person or persons may ride, having two tandem wheels either of which is sixteen inches or more in diameter, or three wheels, any one of which is twenty inches or more in diameter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5723-S.SL.pdf?cite=2019%20c%20403%20§%202[2019 c 403 § 2]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6434-S.SL.pdf?cite=2018%20c%2060%20§%202[2018 c 60 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c55.pdf?cite=1982%20c%2055%20§%204[1982 c 55 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c155.pdf?cite=1965%20ex.s.%20c%20155%20§%2086[1965 ex.s. c 155 § 86]; ]

== 46.04.077 - Breast cancer awareness license plates.
"Breast cancer awareness license plates" means special license plates issued under RCW 46.18.200 that display a symbol or artwork recognizing breast cancer awareness.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2700.SL.pdf?cite=2014%20c%2077%20§%206[2014 c 77 § 6]; ]

== 46.04.079 - Business day.
"Business day" means Monday through Friday and excludes Saturday, Sunday, and state and federal holidays.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20106[2010 c 161 § 106]; ]

== 46.04.080 - Business district.
"Business district" means the territory contiguous to and including a highway when within any six hundred feet along such highway there are buildings in use for business or industrial purposes, including but not limited to hotels, banks, or office buildings, railroad stations, and public buildings which occupy at least three hundred feet of frontage on one side or three hundred feet collectively on both sides of the highway.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975c62.pdf?cite=1975%20c%2062%20§%202[1975 c 62 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.080[1961 c 12 § 46.04.080]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%209[1959 c 49 § 9]; prior: 1937 c 189 § 1, part; RRS § 6360-1, part; 1929 c 180 § 1, part; 1927 c 309 § 2, part; RRS § 6362-2, part; ]

== 46.04.083 - Cab and chassis.
"Cab and chassis" means an incomplete vehicle manufactured and sold with only a cab, frame, and running gear.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20107[2010 c 161 § 107]; ]

== 46.04.085 - Camper.
"Camper" means a structure designed to be mounted upon a motor vehicle which provides facilities for human habitation or for temporary outdoor or recreational lodging and which is five feet or more in overall length and five feet or more in height from its floor to its ceiling when fully extended, but shall not include motor homes as defined in RCW 46.04.305.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c231.pdf?cite=1971%20ex.s.%20c%20231%20§%202[1971 ex.s. c 231 § 2]; ]

== 46.04.090 - Cancel.
"Cancel," in all its forms, means invalidation indefinitely.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c61.pdf?cite=1979%20c%2061%20§%201[1979 c 61 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.090[1961 c 12 § 46.04.090]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2010[1959 c 49 § 10]; prior:  1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part.  1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.094 - Cargo extension.
"Cargo extension" means a device that connects to the left and right side of a motor home or travel trailer frame and (1) becomes part of the frame, (2) does not pivot on a hitch, and (3) has an axle with two wheels, acting as a tag axle, to safely carry the weight of the cargo.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2598-S.SL.pdf?cite=2016%20c%2022%20§%203[2016 c 22 § 3]; ]

== 46.04.100 - Center line.
"Center line" means the line, marked or unmarked, parallel to and equidistant from the sides of a two-way traffic roadway of a highway except where otherwise indicated by painted lines or markers.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975c62.pdf?cite=1975%20c%2062%20§%203[1975 c 62 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.100[1961 c 12 § 46.04.100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2011[1959 c 49 § 11]; prior: 1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.110 - Center of intersection.
"Center of intersection" means the point of intersection of the center lines of the roadway of intersecting public highways.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.110[1961 c 12 § 46.04.110]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2012[1959 c 49 § 12]; prior: 1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.115 - Chauffeur.
"Chauffeur" means a person authorized by the department under this title to drive a limousine, and, if operating in a port district that regulates limousines under RCW 46.72A.030(2), meets the licensing requirements of that port district.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2551.SL.pdf?cite=1996%20c%2087%20§%201[1996 c 87 § 1]; ]

== 46.04.118 - Circular intersection.
. "Circular intersection" means an intersection characterized by a circulatory roadway, generally circular in design, located in the center of the intersection. A circular intersection encompasses the area bounded by the outermost curb line or, if there is no curb, the edge of the pavement, and includes crosswalks on any entering or exiting roadway.

. "Circular intersection" includes:

.. Roundabouts;

.. Rotaries; and

.. Traffic circles.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6084-S.SL.pdf?cite=2020%20c%20199%20§%201[2020 c 199 § 1]; ]

== 46.04.120 - City street.
"City street" means every public highway, or part thereof located within the limits of cities and towns, except alleys.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.120[1961 c 12 § 46.04.120]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2013[1959 c 49 § 13]; prior:  1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part.  1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.123 - Collectible vehicle.
"Collectible vehicle" means a vehicle that complies with the following:

. Is of unique or rare design, of limited production, and an object of curiosity;

. Is maintained primarily for use in car club activities, exhibitions, parades, or other functions of public interest or for a private collection, and is used only infrequently for other purposes; and

. Has collectible vehicle or classic automobile insurance coverage that restricts the collectible vehicle mileage or use, or both, and requires the owner to have another vehicle for personal use.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2359.SL.pdf?cite=2014%20c%2072%20§%202[2014 c 72 § 2]; ]

== 46.04.125 - Collector.
"Collector" means the owner of one or more vehicles described in RCW 46.18.220(1) who collects, purchases, acquires, trades, or disposes of the vehicle or parts of it, for his or her personal use, in order to preserve, restore, and maintain the vehicle for hobby or historical purposes.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20108[2010 c 161 § 108]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5250-S.SL.pdf?cite=1996%20c%20225%20§%202[1996 c 225 § 2]; ]

== 46.04.126 - Collector vehicle.
"Collector vehicle" means any motor vehicle or travel trailer that is at least thirty years old.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1480-S.SL.pdf?cite=2015%20c%20200%20§%204[2015 c 200 § 4]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5581.SL.pdf?cite=2009%20c%20142%20§%202[2009 c 142 § 2]; ]

== 46.04.1261 - Collector vehicle license plate.
"Collector vehicle license plate" means a special license plate that may be assigned to a vehicle that is more than thirty years old.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20109[2010 c 161 § 109]; ]

== 46.04.127 - Collegiate license plates.
"Collegiate license plates" means license plates that display a depiction of the name and mascot or symbol of a state university, regional university, or state college as defined in RCW 28B.10.016.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6089-S.SL.pdf?cite=1994%20c%20194%20§%201[1994 c 194 § 1]; ]

== 46.04.130 - Combination of vehicles.
"Combination of vehicles" means every combination of motor vehicle and motor vehicle, motor vehicle and trailer or motor vehicle and semitrailer.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c154.pdf?cite=1963%20c%20154%20§%2026[1963 c 154 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.130[1961 c 12 § 46.04.130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2014[1959 c 49 § 14]; prior:  1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part.  1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.136 - Commercial trailer.
"Commercial trailer" means a trailer that is principally used to transport commodities, merchandise, produce, freight, or animals.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20110[2010 c 161 § 110]; ]

== 46.04.140 - Commercial vehicle.
"Commercial vehicle" means any vehicle the principal use of which is the transportation of commodities, merchandise, produce, freight, animals, or passengers for hire.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.140[1961 c 12 § 46.04.140]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2015[1959 c 49 § 15]; prior:  1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part.  1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.142 - Confidential license plates.
"Confidential license plates" and "undercover license plates" mean standard issue license plates assigned to vehicles owned or operated by public agencies. These license plates are used as specifically authorized under RCW 46.08.066.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20111[2010 c 161 § 111]; ]

== 46.04.143 - Converter gear.
"Converter gear" means an auxiliary axle, booster axle, dolly, or jeep axle.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20112[2010 c 161 § 112]; ]

== 46.04.150 - County road.
"County road" means every public highway or part thereof, outside the limits of cities and towns and which has not been designated as a state highway.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.150[1961 c 12 § 46.04.150]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2016[1959 c 49 § 16]; prior:  1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part.  1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.160 - Crosswalk.
"Crosswalk" means the portion of the roadway between the intersection area and a prolongation or connection of the farthest sidewalk line or in the event there are no sidewalks then between the intersection area and a line ten feet therefrom, except as modified by a marked crosswalk.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.160[1961 c 12 § 46.04.160]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2017[1959 c 49 § 17]; prior: 1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.161 - Custom vehicle.
"Custom vehicle" means any motor vehicle that:

. Is at least thirty years old and of a model year after 1948 or was manufactured to resemble a vehicle at least thirty years old and of a model year after 1948; and

. Has alterations to one or more of the major component parts listed in RCW 46.80.010 that change the appearance or performance of the vehicle from the original manufacturer's design or has a body constructed from nonoriginal materials.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5585-S.SL.pdf?cite=2011%20c%20114%20§%203[2011 c 114 § 3]; ]

== 46.04.1615 - Data services.
"Data services" means the practice of providing data sets to governmental entities and businesses, as authorized or required by law.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5152-S.SL.pdf?cite=2021%20c%2093%20§%201[2021 c 93 § 1]; ]

== 46.04.162 - Department.
The term "department" shall mean the department of licensing unless a different department is specified.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c158.pdf?cite=1979%20c%20158%20§%20126[1979 c 158 § 126]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975c25.pdf?cite=1975%20c%2025%20§%204[1975 c 25 § 4]; ]

== 46.04.163 - Director.
The term "director" shall mean the director of licensing unless the director of a different department of government is specified.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c158.pdf?cite=1979%20c%20158%20§%20127[1979 c 158 § 127]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975c25.pdf?cite=1975%20c%2025%20§%205[1975 c 25 § 5]; ]

== 46.04.164 - Disabled American veteran license plates.
"Disabled American veteran license plates" means special license plates issued to a veteran, as defined in RCW 41.04.007, who meets the requirements provided in RCW 46.18.235.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20113[2010 c 161 § 113]; ]

== 46.04.165 - Driveaway-towaway operation.
"Driveaway-towaway operation" means any operation in which any motor vehicle, trailer or semitrailer, singly or in combination, new or used, constitutes the commodity being transported when one set or more wheels of any such vehicle are on the roadway during the course of transportation, whether or not any such vehicle furnishes the motive power.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c154.pdf?cite=1963%20c%20154%20§%2027[1963 c 154 § 27]; ]

== 46.04.167 - Driver education.
Whenever the term "driver education" is used in the code, it shall be defined to mean "traffic safety education".

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c218.pdf?cite=1969%20ex.s.%20c%20218%20§%2012[1969 ex.s. c 218 § 12]; ]

== 46.04.168 - Driving privilege withheld.
"Driving privilege withheld" means that the department has revoked, suspended, or denied a person's Washington state driver's license, permit to drive, driving privilege, or nonresident driving privilege.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1294-S.SL.pdf?cite=1999%20c%206%20§%202[1999 c 6 § 2]; ]

== 46.04.169 - Electric-assisted bicycle—Class 1 electric-assisted bicycle—Class 2 electric-assisted bicycle—Class 3 electric-assisted bicycle.
"Electric-assisted bicycle" means a bicycle with two or three wheels, a saddle, fully operative pedals for human propulsion, and an electric motor. The electric-assisted bicycle's electric motor must have a power output of no more than seven hundred fifty watts. The electric-assisted bicycle must meet the requirements of one of the following three classifications:

. "Class 1 electric-assisted bicycle" means an electric-assisted bicycle in which the motor provides assistance only when the rider is pedaling and ceases to provide assistance when the bicycle reaches the speed of twenty miles per hour;

. "Class 2 electric-assisted bicycle" means an electric-assisted bicycle in which the motor may be used exclusively to propel the bicycle and is not capable of providing assistance when the bicycle reaches the speed of twenty miles per hour; or

. "Class 3 electric-assisted bicycle" means an electric-assisted bicycle in which the motor provides assistance only when the rider is pedaling and ceases to provide assistance when the bicycle reaches the speed of twenty-eight miles per hour and is equipped with a speedometer.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6434-S.SL.pdf?cite=2018%20c%2060%20§%201[2018 c 60 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5968.SL.pdf?cite=1997%20c%20328%20§%201[1997 c 328 § 1]; ]

== 46.04.1695 - Electric personal assistive mobility device (EPAMD).
"Electric personal assistive mobility device" (EPAMD) means (1) a self-balancing device with two wheels not in tandem, designed to transport only one person by an electric propulsion system with an average power of seven hundred fifty watts (one horsepower) having a maximum speed on a paved level surface, when powered solely by such a propulsion system while ridden by an operator weighing one hundred seventy pounds, of less than twenty miles per hour or (2) a self-balancing device with one wheel designed to transport only one person by an electric propulsion system with an average power of two thousand watts (two and two-thirds horsepower) having a maximum speed on a paved level surface, when powered solely by such a propulsion system, of less than twenty miles per hour.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1884.SL.pdf?cite=2015%20c%20145%20§%202[2015 c 145 § 2]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6316.SL.pdf?cite=2002%20c%20247%20§%201[2002 c 247 § 1]; ]

== 46.04.1697 - Electronic commerce.
"Electronic commerce" may include, but is not limited to, transactions conducted over the Internet or by telephone or other electronic means.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5428-S.SL.pdf?cite=2004%20c%20249%20§%201[2004 c 249 § 1]; ]

== 46.04.1698 - Empty scale weight.
"Empty scale weight" means the weight of a vehicle as it stands without a load.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20114[2010 c 161 § 114]; ]

== 46.04.1699 - Endangered wildlife license plates.
"Endangered wildlife license plates" means special license plates that display a symbol or artwork symbolizing endangered wildlife in Washington state.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20115[2010 c 161 § 115]; ]

== 46.04.170 - Explosives.
"Explosives" means any chemical compound or mechanical mixture that is commonly used or intended for the purpose of producing an explosion, and which contains any oxidizing or combustible units or other ingredients in such proportions, quantities or packing that an ignition by fire, by friction, by concussion, by percussion or by detonation of any part of the compound mixture may cause such a sudden generation of highly heated gases that the resultant gaseous pressures are capable of producing destructible effects on contiguous objects or of destroying life or limb.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.170[1961 c 12 § 46.04.170]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2018[1959 c 49 § 18]; prior: 1937 c 189 § 1, part; RRS § 6360-1, part. Cf.  1951 c 102 § 3; ]

== 46.04.174 - Facial recognition matching system.
"Facial recognition matching system" means a system that compares the biometric template derived from an image of an applicant or holder of a driver's license, permit, or identicard with the biometric templates derived from the images in the department's negative file.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6150-S.SL.pdf?cite=2012%20c%2080%20§%203[2012 c 80 § 3]; ]

== 46.04.180 - Farm tractor.
"Farm tractor" means every motor vehicle designed and used primarily as a farm implement for drawing plows, mowing machines, and other implements of husbandry.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.180[1961 c 12 § 46.04.180]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2019[1959 c 49 § 19]; prior:  1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part.  1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.181 - Farm vehicle.
"Farm vehicle" means any vehicle other than a farm tractor or farm implement which is: (1) Designed and/or used primarily in agricultural pursuits on farms for the purpose of transporting machinery, equipment, implements, farm products, supplies and/or farm labor thereon and is only incidentally operated on or moved along public highways for the purpose of going from one farm to another or between locations supporting farming operations; or (2) for purposes of RCW 46.25.050, used to transport agricultural products, farm machinery, farm supplies, or any combination of these materials to or from a farm.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5616.SL.pdf?cite=2013%20c%20299%20§%203[2013 c 299 § 3]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6423-S.SL.pdf?cite=2012%20c%20130%20§%201[2012 c 130 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c202.pdf?cite=1967%20c%20202%20§%201[1967 c 202 § 1]; ]

== 46.04.182 - Farmer.
"Farmer" means any person, firm, partnership or corporation engaged in farming. If a person, firm, partnership or corporation is engaged in activities in addition to that of farming, the definition shall only apply to that portion of the activity that is defined as farming in RCW 46.04.183.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c281.pdf?cite=1969%20ex.s.%20c%20281%20§%2058[1969 ex.s. c 281 § 58]; ]

== 46.04.183 - Farming.
"Farming" means the cultivation and tillage of the soil, dairying, the production, cultivation, growing, and harvesting of any agricultural or horticultural commodities (except forestry or forestry operations), the raising of livestock, bees, fur-bearing animals, or poultry, and any practices performed on a farm as an incident to or in conjunction with such farming operations.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c281.pdf?cite=1969%20ex.s.%20c%20281%20§%2059[1969 ex.s. c 281 § 59]; ]

== 46.04.186 - Fixed load vehicle.
"Fixed load vehicle" means a commercial vehicle that has a structure or machinery permanently attached such as, but not limited to, an air compressor, a bunk house, a conveyor, a cook house, a donkey engine, a hoist, a rock crusher, a tool house, or a well drilling machine. Fixed load vehicles are not capable of carrying any additional load other than the structure or machinery permanently attached.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20116[2010 c 161 § 116]; ]

== 46.04.187 - Flammable liquid.
"Flammable liquid" means any liquid which has a flash point of 70° Fahrenheit, or less, as determined by a Tagliabue or equivalent closed cup test device.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.210[1961 c 12 § 46.04.210]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2022[1959 c 49 § 22]; prior: 1937 c 189 § 1, part; RRS § 6360-1, part. Cf.  1951 c 102 § 3; ]

== 46.04.190 - For hire vehicle.
"For hire vehicle" means any motor vehicle used for the transportation of persons for compensation, except auto stages and ride-sharing vehicles.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c111.pdf?cite=1979%20c%20111%20§%2013[1979 c 111 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.190[1961 c 12 § 46.04.190]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2020[1959 c 49 § 20]; prior:  1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part; 1923 c 181 § 1, part; 1921 c 96 § 2, part; 1919 c 59 § 1, part; 1917 c 155 § 1, part; 1915 c 142 § 2, part; RRS § 6313, part.  1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.192 - Former prisoner of war license plates.
"Former prisoner of war license plates" means special license plates that may be issued to former prisoners of war as authorized under RCW 46.18.235.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20117[2010 c 161 § 117]; ]

== 46.04.193 - Fred Hutch license plates.
"Fred Hutch license plates" means special license plates issued under RCW 46.18.200 that display the logo of the Fred Hutchinson cancer research center.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1568-S.SL.pdf?cite=2017%20c%2025%20§%204[2017 c 25 § 4]; ]

== 46.04.194 - Garbage truck.
"Garbage truck" means a truck specially designed and used exclusively for garbage or refuse operations.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c68.pdf?cite=1983%20c%2068%20§%201[1983 c 68 § 1]; ]

== 46.04.1945 - Golf cart.
"Golf cart" means a gas-powered or electric-powered four-wheeled vehicle originally designed and manufactured for operation on a golf course for sporting purposes and has a speed attainable in one mile of not more than twenty miles per hour. A golf cart is not a nonhighway vehicle or off-road vehicle as defined in RCW 46.04.365.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5061.SL.pdf?cite=2011%20c%20171%20§%2012[2011 c 171 § 12]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6207-S.SL.pdf?cite=2010%20c%20217%20§%203[2010 c 217 § 3]; ]

== 46.04.1951 - Gonzaga University alumni association license plates.
"Gonzaga University alumni association license plates" means license plates issued under RCW 46.18.200 that display a symbol or artwork recognizing the efforts of the Gonzaga University alumni association in Washington state.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5061.SL.pdf?cite=2011%20c%20171%20§%2013[2011 c 171 § 13]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5833.SL.pdf?cite=2005%20c%2085%20§%202[2005 c 85 § 2]; ]

== 46.04.1953 - Gross vehicle weight rating.
"Gross vehicle weight rating" means the value specified by the manufacturer as the maximum load weight of a single vehicle.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20118[2010 c 161 § 118]; ]

== 46.04.196 - Helping Kids Speak license plates.
"Helping Kids Speak license plates" means license plates that display a symbol of an organization that supports programs that provide free diagnostic and therapeutic services to children who have a severe delay in language or speech development.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6688-S.SL.pdf?cite=2004%20c%2048%20§%202[2004 c 48 § 2]; ]

== 46.04.197 - Highway.
Highway means the entire width between the boundary lines of every way publicly maintained when any part thereof is open to the use of the public for purposes of vehicular travel.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c155.pdf?cite=1965%20ex.s.%20c%20155%20§%2087[1965 ex.s. c 155 § 87]; ]

== 46.04.199 - Horseless carriage license plate.
"Horseless carriage license plate" is a special license plate that may be assigned to a vehicle that is at least forty years old.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1813-S.SL.pdf?cite=2017%20c%20147%20§%201[2017 c 147 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20120[2010 c 161 § 120]; ]

== 46.04.200 - Hours of darkness.
"Hours of darkness" means the hours from one-half hour after sunset to one-half hour before sunrise, and any other time when persons or objects may not be clearly discernible at a distance of five hundred feet.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.200[1961 c 12 § 46.04.200]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2021[1959 c 49 § 21]; prior: 1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.204 - Hybrid motor vehicle.
"Hybrid motor vehicle" means a motor vehicle that uses multiple power sources or fuel types for propulsion and meets the federal definition of a hybrid motor vehicle.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20121[2010 c 161 § 121]; ]

== 46.04.209 - Identity information.
. "Identity information" means information that identifies an individual, or may be used to determine the identity of an individual, including:

.. Federal tax identification number or employer identification number;

.. Residential and mailing address, but not the five-digit zip code;

.. Email address;

.. Telephone number;

.. Registered and legal vehicle owner name;

.. Gender;

.. Place of birth;

.. Voter information status; and

.. Selective service information.

. "Personal information" has the same meaning as in RCW 42.56.590.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5152-S.SL.pdf?cite=2021%20c%2093%20§%202[2021 c 93 § 2]; ]

== 46.04.215 - Ignition interlock device.
"Ignition interlock device" means breath alcohol analyzing ignition equipment or other biological or technical device certified in conformance with RCW 43.43.395 and rules adopted by the state patrol and designed to prevent a motor vehicle from being operated by a person who has consumed an alcoholic beverage.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2466-S.SL.pdf?cite=2010%20c%20268%20§%201[2010 c 268 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1872.SL.pdf?cite=2005%20c%20200%20§%201[2005 c 200 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1940.SL.pdf?cite=1997%20c%20229%20§%209[1997 c 229 § 9]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6047-S.SL.pdf?cite=1994%20c%20275%20§%2023[1994 c 275 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c247.pdf?cite=1987%20c%20247%20§%203[1987 c 247 § 3]; ]

== 46.04.217 - Ignition interlock driver's license.
"Ignition interlock driver's license" means a permit issued to a person by the department that allows the person to operate a noncommercial motor vehicle with an ignition interlock device while the person's regular driver's license is suspended, revoked, or denied.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3254-S2.SL.pdf?cite=2008%20c%20282%20§%201[2008 c 282 § 1]; ]

== 46.04.220 - Intersection area.
. "Intersection area" means the area embraced within the prolongation or connection of the lateral curb lines, or, if none then the lateral boundary lines of the roadways of two or more highways which join one another at, or approximately at, right angles, or the area within which vehicles traveling upon different highways joining at any other angle may come in conflict.

. Where a highway includes two roadways thirty feet or more apart, then every crossing of each roadway of such divided highway by an intersecting highway shall be regarded as a separate intersection. In the event such intersecting highway also includes two roadways thirty feet or more apart, then every crossing of two roadways of such highways shall be regarded as a separate intersection.

. The junction of an alley with a street or highway shall not constitute an intersection.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975c62.pdf?cite=1975%20c%2062%20§%204[1975 c 62 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.220[1961 c 12 § 46.04.220]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2023[1959 c 49 § 23]; prior: 1937 c 189 § 1, part; RRS § 6360-1, part; 1929 c 180 § 1, part; 1927 c 309 § 2, part; RRS § 6362-2, part; ]

== 46.04.240 - Intersection control area.
"Intersection control area" means intersection area, together with such modification of the adjacent roadway area as results from the arc of curb corners and together with any marked or unmarked crosswalks adjacent to the intersection.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.240[1961 c 12 § 46.04.240]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2025[1959 c 49 § 25]; prior: 1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.249 - Keep Kids Safe license plates.
"Keep Kids Safe license plates" means license plates issued under RCW 46.18.200 that display artwork recognizing efforts to prevent child abuse and neglect in Washington state.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5061.SL.pdf?cite=2011%20c%20171%20§%2014[2011 c 171 § 14]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1097-S.SL.pdf?cite=2005%20c%2053%20§%202[2005 c 53 § 2]; ]

== 46.04.251 - Kit vehicle.
"Kit vehicle" means a passenger car or light truck assembled from a manufactured kit, and is either (1) a complete kit consisting of a prefabricated body and chassis used to construct a new vehicle, or (2) a kit consisting of a prefabricated body to be mounted on an existing vehicle chassis and drivetrain, commonly referred to as a donor vehicle.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5250-S.SL.pdf?cite=1996%20c%20225%20§%205[1996 c 225 § 5]; ]

== 46.04.260 - Laned highway.
"Laned highway" means a highway the roadway of which is divided into clearly marked lanes for vehicular traffic.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.260[1961 c 12 § 46.04.260]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2027[1959 c 49 § 27]; prior: 1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.265 - Law enforcement memorial license plates.
"Law enforcement memorial license plates" means license plates issued under RCW 46.18.200 that display a symbol honoring law enforcement officers in Washington killed in the line of duty.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5061.SL.pdf?cite=2011%20c%20171%20§%2015[2011 c 171 § 15]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6148-S.SL.pdf?cite=2004%20c%20221%20§%202[2004 c 221 § 2]; ]

== 46.04.270 - Legal owner.
"Legal owner" means a person having a security interest in a vehicle perfected in accordance with chapter 46.12 RCW or the registered owner of a vehicle unencumbered by a security interest or the lessor of a vehicle unencumbered by a security interest.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975c25.pdf?cite=1975%20c%2025%20§%201[1975 c 25 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.270[1961 c 12 § 46.04.270]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2028[1959 c 49 § 28]; prior: 1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part; ]

== 46.04.271 - Light truck.
"Light truck" means a motor vehicle manufactured as a truck with a declared gross weight of twelve thousand pounds or less.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20122[2010 c 161 § 122]; ]

== 46.04.272 - Lightweight stud.
. "Lightweight stud" means a stud intended for installation and use in a vehicle tire. As used in this title, this means a stud that is recommended by the manufacturer of the tire for the type and size of the tire and that:

.. Weighs no more than 1.5 grams if the stud conforms to Tire Stud Manufacturing Institute (TSMI) stud size 14 or less;

.. Weighs no more than 2.3 grams if the stud conforms to TSMI stud size 15 or 16; or

.. Weighs no more than 3.0 grams if the stud conforms to TSMI stud size 17 or larger.

. A lightweight stud may contain any materials necessary to achieve the lighter weight.

. Subsection (1) of this section does not apply to retractable studs as described in RCW 46.37.420.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5206.SL.pdf?cite=2007%20c%20140%20§%201[2007 c 140 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5384.SL.pdf?cite=1999%20c%20219%20§%201[1999 c 219 § 1]; ]

== 46.04.274 - Limousine.
"Limousine" means a category of for hire, chauffeur-driven, unmetered, unmarked luxury motor vehicles. The director in consultation with the Washington state patrol will by rule define the categories of limousines.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/3001.SL.pdf?cite=2006%20c%2098%20§%201[2006 c 98 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2551.SL.pdf?cite=1996%20c%2087%20§%202[1996 c 87 § 2]; ]

== 46.04.276 - Limousine carrier.
"Limousine carrier" means a person engaged in the transportation of a person or group of persons, who, under a single contract, acquires, on a prearranged basis, the use of a limousine to travel to a specified destination or for a particular itinerary. The term "prearranged basis" refers to the manner in which the carrier dispatches vehicles.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2551.SL.pdf?cite=1996%20c%2087%20§%203[1996 c 87 § 3]; ]

== 46.04.280 - Local authorities.
"Local authorities" includes every county, municipal, or other local public board or body having authority to adopt local police regulations under the Constitution and laws of this state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.280[1961 c 12 § 46.04.280]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2029[1959 c 49 § 29]; prior:  1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part; 1923 c 181 § 1, part; 1921 c 96 § 2, part; 1919 c 59 § 1, part; 1917 c 155 § 1, part; 1915 c 142 § 2, part; RRS § 6313, part.  1937 c 189 § 1, part; RRS § 6360-1, part; 1929 c 180 § 1, part; 1927 c 309 § 2, part; RRS § 6362-2, part; ]

== 46.04.290 - Marked crosswalk.
"Marked crosswalk" means any portion of a roadway distinctly indicated for pedestrian crossing by lines or other markings on the surface thereof.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.290[1961 c 12 § 46.04.290]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2030[1959 c 49 § 30]; prior: 1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.292 - Market value threshold amount.
"Market value threshold amount" means an amount set by rule by the department that is used to determine, together with the age of the vehicle, whether vehicle certificates of title for vehicles aged six years through twenty years should be identified as having been previously destroyed or reported as an insurance total loss.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20123[2010 c 161 § 123]; ]

== 46.04.294 - Medal of Honor.
"Medal of Honor" means the Medal of Honor military decoration presented by the president of the United States, in the name of congress.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2397.SL.pdf?cite=2014%20c%20181%20§%204[2014 c 181 § 4]; ]

== 46.04.295 - Medium-speed electric vehicle.
"Medium-speed electric vehicle" means a self-propelled, electrically powered four-wheeled motor vehicle, equipped with a roll cage or crush-proof body design, whose speed attainable in one mile is more than twenty-five miles per hour but not more than thirty-five miles per hour and otherwise meets or exceeds the federal regulations set forth in 49 C.F.R. Sec. 571.500.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6346-S.SL.pdf?cite=2010%20c%20144%20§%201[2010 c 144 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1820.SL.pdf?cite=2007%20c%20510%20§%202[2007 c 510 § 2]; ]

== 46.04.300 - Metal tire.
"Metal tire" includes every tire, the bearing surface of which in contact with the highway is wholly or partly of metal or other hard, nonresilient material.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.300[1961 c 12 § 46.04.300]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2031[1959 c 49 § 31]; prior:  1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part.  1937 c 189 § 1, part; RRS § 6360-1, part; 1929 c 180 § 1, part; 1927 c 309 § 2, part; RRS § 6362-2, part; ]

== 46.04.301 - Military affiliate radio system license plates.
"Military affiliate radio system license plates" means special license plates displaying official military affiliate radio system call letters assigned by the United States department of defense.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20124[2010 c 161 § 124]; ]

== 46.04.302 - Mobile home, manufactured home.
"Mobile home" or "manufactured home" means a structure, designed and constructed to be transportable in one or more sections, and is built on a permanent chassis, and designed to be used as a dwelling with or without a permanent foundation when connected to the required utilities that include plumbing, heating, and electrical systems contained therein. The structure must comply with the national mobile home construction and safety standards act of 1974 as adopted by chapter 43.22 RCW if applicable. Manufactured home does not include a modular home. A structure which met the definition of a "manufactured home" at the time of manufacture is still considered to meet this definition notwithstanding that it is no longer transportable.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1057-S.SL.pdf?cite=1993%20c%20154%20§%201[1993 c 154 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c343.pdf?cite=1989%20c%20343%20§%2024[1989 c 343 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c337.pdf?cite=1989%20c%20337%20§%201[1989 c 337 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c22.pdf?cite=1977%20ex.s.%20c%2022%20§%201[1977 ex.s. c 22 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c231.pdf?cite=1971%20ex.s.%20c%20231%20§%204[1971 ex.s. c 231 § 4]; ]

== 46.04.303 - Modular home.
"Modular home" means a factory-assembled structure designed primarily for use as a dwelling when connected to the required utilities that include plumbing, heating, and electrical systems contained therein, does not contain its own running gear, and must be mounted on a permanent foundation. A modular home does not include a mobile home or manufactured home.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c250.pdf?cite=1990%20c%20250%20§%2017[1990 c 250 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c231.pdf?cite=1971%20ex.s.%20c%20231%20§%205[1971 ex.s. c 231 § 5]; ]

== 46.04.304 - Moped.
"Moped" means a motorized device designed to travel with not more than three wheels in contact with the ground and having an electric or a liquid fuel motor with a cylinder displacement not exceeding fifty cubic centimeters which produces no more than two gross brake horsepower (developed by a prime mover, as measured by a brake applied to the driving shaft) that is capable of propelling the device at not more than thirty miles per hour on level ground.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5482.SL.pdf?cite=2009%20c%20275%20§%201[2009 c 275 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c250.pdf?cite=1990%20c%20250%20§%2018[1990 c 250 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c330.pdf?cite=1987%20c%20330%20§%20702[1987 c 330 § 702]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c213.pdf?cite=1979%20ex.s.%20c%20213%20§%201[1979 ex.s. c 213 § 1]; ]

== 46.04.305 - Motor homes.
"Motor homes" means motor vehicles originally designed, reconstructed, or permanently altered to provide facilities for human habitation, which include lodging and cooking or sewage disposal, and is enclosed within a solid body shell with the vehicle, but excludes a camper or like unit constructed separately and affixed to a motor vehicle.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c250.pdf?cite=1990%20c%20250%20§%2019[1990 c 250 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c231.pdf?cite=1971%20ex.s.%20c%20231%20§%203[1971 ex.s. c 231 § 3]; ]

== 46.04.310 - Motor truck.
"Motor truck" means any motor vehicle designed or used for the transportation of commodities, merchandise, produce, freight, or animals.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.310[1961 c 12 § 46.04.310]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2032[1959 c 49 § 32]; prior:  1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part; 1923 c 181 § 1, part; 1921 c 96 § 2, part; 1919 c 59 § 1, part; 1917 c 155 § 1, part; 1915 c 142 § 2, part; RRS § 6313, part.  1937 c 189 § 1, part; RRS § 6360-1, part; 1929 c 180 § 1, part; 1927 c 309 § 2, part; RRS § 6362-2, part; ]

== 46.04.320 - Motor vehicle.
. "Motor vehicle" means a vehicle that is self-propelled or a vehicle that is propelled by electric power obtained from overhead trolley wires but not operated upon rails.

. "Motor vehicle" includes:

.. A neighborhood electric vehicle as defined in RCW 46.04.357;

.. A medium-speed electric vehicle as defined in RCW 46.04.295; and

.. A golf cart for the purposes of chapter 46.61 RCW.

. "Motor vehicle" excludes:

.. An electric personal assistive mobility device;

.. A power wheelchair;

.. A golf cart, except as provided in subsection (2) of this section;

.. A moped, for the purposes of chapter 46.70 RCW; and

.. A personal delivery device as defined in RCW 46.75.010.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1325-S.SL.pdf?cite=2019%20c%20214%20§%206[2019 c 214 § 6]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6207-S.SL.pdf?cite=2010%20c%20217%20§%201[2010 c 217 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1820.SL.pdf?cite=2007%20c%20510%20§%201[2007 c 510 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5450.SL.pdf?cite=2003%20c%20353%20§%201[2003 c 353 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1937.SL.pdf?cite=2003%20c%20141%20§%202[2003 c 141 § 2]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6316.SL.pdf?cite=2002%20c%20247%20§%202[2002 c 247 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.320[1961 c 12 § 46.04.320]; prior:  1959 c 49 § 33; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c384.pdf?cite=1955%20c%20384%20§%2010[1955 c 384 § 10]; prior:  1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part; 1923 c 181 § 1, part; 1921 c 96 § 2, part; 1919 c 59 § 1, part; 1917 c 155 § 1, part; 1915 c 142 § 2, part; RRS § 6313, part.  1937 c 189 § 1, part; RRS § 6360-1, part; 1929 c 180 § 1, part; 1927 c 309 § 2, part; RRS § 6362-2, part; ]

== 46.04.330 - Motorcycle.
"Motorcycle" means a motor vehicle designed to travel on not more than three wheels, not including any stabilizing conversion kits, on which the driver:

. Rides on a seat or saddle and the motor vehicle is designed to be steered with a handlebar; or

. Rides on a seat in a partially or completely enclosed seating area that is equipped with safety belts and the motor vehicle is designed to be steered with a steering wheel.

"Motorcycle" excludes a farm tractor, a power wheelchair, an electric personal assistive mobility device, a motorized foot scooter, an electric-assisted bicycle, and a moped.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1334-S.SL.pdf?cite=2013%20c%20174%20§%201[2013 c 174 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5482.SL.pdf?cite=2009%20c%20275%20§%202[2009 c 275 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1937.SL.pdf?cite=2003%20c%20141%20§%203[2003 c 141 § 3]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6316.SL.pdf?cite=2002%20c%20247%20§%203[2002 c 247 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c250.pdf?cite=1990%20c%20250%20§%2020[1990 c 250 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c213.pdf?cite=1979%20ex.s.%20c%20213%20§%202[1979 ex.s. c 213 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.330[1961 c 12 § 46.04.330]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2034[1959 c 49 § 34]; prior:  1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part; 1923 c 181 § 1, part; 1921 c 96 § 2, part; 1919 c 59 § 1, part; 1917 c 155 § 1, part; 1915 c 142 § 2, part; RRS § 6313, part.  1937 c 189 § 1, part; RRS § 6360-1, part; 1929 c 180 § 1, part; 1927 c 309 § 2, part; RRS § 6362-2, part; ]

== 46.04.332 - Motor-driven cycle.
"Motor-driven cycle" means every motorcycle, including every motor scooter, with a motor that produces not to exceed five brake horsepower (developed by a prime mover, as measured by a brake applied to the driving shaft). A motor-driven cycle does not include a moped, a power wheelchair, a motorized foot scooter, or an electric personal assistive mobility device.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5450.SL.pdf?cite=2003%20c%20353%20§%207[2003 c 353 § 7]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1937.SL.pdf?cite=2003%20c%20141%20§%204[2003 c 141 § 4]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6316.SL.pdf?cite=2002%20c%20247%20§%204[2002 c 247 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c213.pdf?cite=1979%20ex.s.%20c%20213%20§%203[1979 ex.s. c 213 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c154.pdf?cite=1963%20c%20154%20§%2028[1963 c 154 § 28]; ]

== 46.04.336 - Motorized foot scooter.
"Motorized foot scooter" means a device with two or three wheels that has handlebars, a floorboard that can be stood upon while riding, and is powered by an internal combustion engine or electric motor that has a maximum speed of no greater than twenty miles per hour on level ground.

For purposes of this section, a motor-driven cycle, a moped, an electric-assisted bicycle, or a motorcycle is not a motorized foot scooter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1772-S.SL.pdf?cite=2019%20c%20170%20§%201[2019 c 170 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5482.SL.pdf?cite=2009%20c%20275%20§%203[2009 c 275 § 3]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5450.SL.pdf?cite=2003%20c%20353%20§%206[2003 c 353 § 6]; ]

== 46.04.340 - Muffler.
"Muffler" means a device consisting of a series of chambers, or other mechanical designs for the purpose of receiving exhaust gas from an internal combustion engine and effective in reducing noise resulting therefrom.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.340[1961 c 12 § 46.04.340]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2035[1959 c 49 § 35]; prior: 1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.350 - Multiple lane highway.
"Multiple lane highway" means any highway the roadway of which is of sufficient width to reasonably accommodate two or more separate lanes of vehicular traffic in the same direction, each lane of which shall be not less than the maximum legal vehicle width and whether or not such lanes are marked.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975c62.pdf?cite=1975%20c%2062%20§%205[1975 c 62 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.350[1961 c 12 § 46.04.350]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2036[1959 c 49 § 36]; prior: 1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.355 - Municipal transit vehicle.
Municipal transit vehicle includes every motor vehicle, streetcar, train, trolley vehicle, and any other device, which (1) is capable of being moved within, upon, above, or below a public highway, (2) is owned or operated by a city, county, county transportation authority, public transportation benefit area, regional transit authority, or metropolitan municipal corporation within the state, and (3) is used for the purpose of carrying passengers together with incidental baggage and freight on a regular schedule.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6326.SL.pdf?cite=2004%20c%20118%20§%202[2004 c 118 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c167.pdf?cite=1984%20c%20167%20§%202[1984 c 167 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c76.pdf?cite=1974%20ex.s.%20c%2076%20§%204[1974 ex.s. c 76 § 4]; ]

== 46.04.3551 - Music Matters license plates.
"Music Matters license plates" means special license plates issued under RCW 46.18.200 that display the "Music Matters" logo.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1329-S.SL.pdf?cite=2011%20c%20229%20§%202[2011 c 229 § 2]; ]

== 46.04.356 - Natural person.
"Natural person" means a human being.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20125[2010 c 161 § 125]; ]

== 46.04.357 - Neighborhood electric vehicle.
"Neighborhood electric vehicle" means a self-propelled, electrically powered four-wheeled motor vehicle whose speed attainable in one mile is more than twenty miles per hour and not more than twenty-five miles per hour and conforms to federal regulations under Title 49 C.F.R. Part 571.500.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5450.SL.pdf?cite=2003%20c%20353%20§%202[2003 c 353 § 2]; ]

== 46.04.358 - New motor vehicle.
"New motor vehicle" means any motor vehicle that (1) is self-propelled and is required to be registered and titled under this title, (2) has not been previously titled to a retail purchaser or lessee, and (3) is not a used vehicle as defined under RCW 46.04.660.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20126[2010 c 161 § 126]; ]

== 46.04.360 - Nonresident.
"Nonresident" means any person whose residence is outside this state and who is temporarily sojourning within this state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.360[1961 c 12 § 46.04.360]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2037[1959 c 49 § 37]; prior:  1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part.  1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.363 - Off-road motorcycle.
"Off-road motorcycle" means a motorcycle as defined in RCW 46.04.330 that is labeled by the manufacturer's statement or certificate of origin as intended for "off-road use only" or a similar message stamped into the frame of the motorcycle, contained in the owner's manual, or affixed to any part of the motorcycle.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5800-S.SL.pdf?cite=2011%20c%20121%20§%201[2011 c 121 § 1]; ]

== 46.04.365 - Off-road vehicle.
"Off-road vehicle" or "ORV" means a nonstreet registered vehicle when used for recreational purposes on nonhighway roads, trails, or a variety of other natural terrain. "Off-road vehicle" or "ORV" includes, but is not limited to, all-terrain vehicles, motorcycles, four-wheel drive vehicles, and dune buggies.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20127[2010 c 161 § 127]; ]

== 46.04.370 - Operator or driver.
"Operator or driver" means every person who drives or is in actual physical control of a vehicle.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975c62.pdf?cite=1975%20c%2062%20§%206[1975 c 62 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c32.pdf?cite=1967%20c%2032%20§%201[1967 c 32 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.370[1961 c 12 § 46.04.370]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2038[1959 c 49 § 38]; prior:  1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part; 1923 c 181 § 1, part; 1921 c 96 § 2, part; RRS § 6313, part.  1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.372 - ORV registration.
"ORV registration" means a registration certificate or decal issued under the laws of this state pertaining to the registration of off-road vehicles under chapter 46.09 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20128[2010 c 161 § 128]; ]

== 46.04.380 - Owner.
"Owner" means a person who has a lawful right of possession of a vehicle by reason of obtaining it by purchase, exchange, gift, lease, inheritance or legal action whether or not the vehicle is subject to a security interest and means registered owner where the reference to owner may be construed as either to registered or legal owner.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975c25.pdf?cite=1975%20c%2025%20§%202[1975 c 25 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.380[1961 c 12 § 46.04.380]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2039[1959 c 49 § 39]; prior: 1937 c 189 § 1, part; RRS § 6360-1, part; 1929 c 180 § 1, part; 1927 c 309 § 2, part; RRS § 6362-2, part; ]

== 46.04.3802 - Ownership in doubt.
"Ownership in doubt" means that a vehicle or vessel owner is unable to obtain satisfactory evidence of ownership or releases of interest and is permitted to apply for a three-year registration period without a certificate of title or a three-year period with a bond covering the certificate of title.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20129[2010 c 161 § 129]; ]

== 46.04.381 - Park or parking.
"Park or parking" means the standing of a vehicle, whether occupied or not, otherwise than temporarily for the purpose of and while actually engaged in loading or unloading property or passengers.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975c62.pdf?cite=1975%20c%2062%20§%209[1975 c 62 § 9]; ]

== 46.04.3815 - Parts car.
[ NOTES:; ]

== 46.04.382 - Passenger car.
"Passenger car" means every motor vehicle except motorcycles and motor-driven cycles, designed for carrying ten passengers or less and used for the transportation of persons.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c154.pdf?cite=1963%20c%20154%20§%2029[1963 c 154 § 29]; ]

== 46.04.385 - Personalized license plates.
"Personalized license plates" means license plates that display the license plate number assigned to the vehicle or camper for which the license plate number was issued in a combination of letters or numbers, or both, requested by the owner of the vehicle or camper in accordance with chapter 46.18 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20131[2010 c 161 § 131]; ]

== 46.04.400 - Pedestrian.
"Pedestrian" means any person who is afoot or who is using a wheelchair, a power wheelchair, or a means of conveyance propelled by human power other than a bicycle.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1937.SL.pdf?cite=2003%20c%20141%20§%205[2003 c 141 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c241.pdf?cite=1990%20c%20241%20§%201[1990 c 241 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.400[1961 c 12 § 46.04.400]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2041[1959 c 49 § 41]; prior: 1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.405 - Person.
"Person" includes every natural person, firm, copartnership, corporation, association, or organization.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.405[1961 c 12 § 46.04.405]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2042[1959 c 49 § 42]; prior:  1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part.  1937 c 189 § 1, part; RRS § 6360-1, part; 1929 c 180 § 1, part; 1927 c 309 § 2, part; RRS § 6362-2, part; ]

== 46.04.408 - Photograph, picture, negative.
"Photograph," along with the terms "picture" and "negative," means a pictorial representation, whether produced through photographic or other means, including, but not limited to, digital data imaging.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c250.pdf?cite=1990%20c%20250%20§%2021[1990 c 250 § 21]; ]

== 46.04.410 - Pneumatic tires.
"Pneumatic tires" includes every tire of rubber or other resilient material designed to be inflated with compressed air to support the load thereon.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.410[1961 c 12 § 46.04.410]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2043[1959 c 49 § 43]; prior:  1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part.  1937 c 189 § 1, part; RRS § 6360-1, part; 1929 c 180 § 1, part; 1927 c 309 § 2, part; RRS § 6362-2, part; ]

== 46.04.414 - Pole trailer.
"Pole trailer" means every vehicle without motive power designed to be drawn by another vehicle and attached to the towing vehicle by means of a reach, or pole, or by being boomed or otherwise secured to the towing vehicle, and ordinarily used for transporting long or irregular shaped loads such as poles, pipes, logs or structural members capable, generally, of sustaining themselves as beams between the supporting connections.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.414[1961 c 12 § 46.04.414]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2044[1959 c 49 § 44]; prior:  1951 c 56 § 1; ]

== 46.04.4141 - Police officer.
Police officer means every officer authorized to direct or regulate traffic or to make arrests for violations of traffic regulations.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c155.pdf?cite=1965%20ex.s.%20c%20155%20§%2089[1965 ex.s. c 155 § 89]; ]

== 46.04.415 - Power wheelchair.
"Power wheelchair" means any self-propelled vehicle capable of traveling no more than fifteen miles per hour, usable indoors, designed as a mobility aid for individuals with mobility impairments, and operated by such an individual.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1937.SL.pdf?cite=2003%20c%20141%20§%201[2003 c 141 § 1]; ]

== 46.04.416 - Private carrier bus.
"Private carrier bus" means every motor vehicle designed for the purpose of carrying passengers (having a seating capacity for eleven or more persons) used regularly to transport persons in furtherance of any organized agricultural, religious or charitable purpose. Such term does not include buses operated by common carriers under a franchise granted by any city or town or the Washington public utilities commission.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c100.pdf?cite=1970%20ex.s.%20c%20100%20§%203[1970 ex.s. c 100 § 3]; ]

== 46.04.420 - Private road or driveway.
"Private road or driveway" includes every way or place in private ownership and used for travel of vehicles by the owner or those having express or implied permission from the owner, but not by other persons.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.420[1961 c 12 § 46.04.420]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2045[1959 c 49 § 45]; prior: 1937 c 189 § 1, part; RRS § 6360-1, part; 1929 c 180 § 1, part; 1927 c 309 § 2, part; RRS § 6362-2, part; ]

== 46.04.422 - Private use single-axle trailer.
"Private use single-axle trailer" means a trailer owned by a natural person and used for the private noncommercial use of the owner.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20132[2010 c 161 § 132]; ]

== 46.04.429 - Professional firefighters and paramedics license plates.
"Professional firefighters and paramedics license plates" means license plates issued under RCW 46.18.200 that display a symbol denoting professional firefighters and paramedics.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5061.SL.pdf?cite=2011%20c%20171%20§%2017[2011 c 171 § 17]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2910-S.SL.pdf?cite=2004%20c%2035%20§%202[2004 c 35 § 2]; ]

== 46.04.435 - Public scale.
"Public scale" means every scale under public or private ownership which is certified as to its accuracy and which is available for public weighing.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.435[1961 c 12 § 46.04.435]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2047[1959 c 49 § 47]; ]

== 46.04.437 - Purple heart license plates.
"Purple heart license plates" means special license plates that may be assigned to a motor vehicle required to display one or two license plates, excluding vehicles registered under chapter 46.87 RCW, upon terms and conditions established by the department, to recipients of the Purple Heart medal or to another qualified person.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1328-S.SL.pdf?cite=2011%20c%20332%20§%202[2011 c 332 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20133[2010 c 161 § 133]; ]

== 46.04.440 - Railroad.
"Railroad" means a carrier of persons or property upon vehicles, other than streetcars, operated upon stationary rails, the route of which is principally outside cities and towns.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.440[1961 c 12 § 46.04.440]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2048[1959 c 49 § 48]; prior:  1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part.  1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.450 - Railroad sign or signal.
"Railroad sign or signal" means any sign, signal, or device erected by authority of a public body or official or by a railroad and intended to give notice of the presence of railroad tracks or the approach of a railroad train.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.450[1961 c 12 § 46.04.450]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2049[1959 c 49 § 49]; prior: 1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.455 - Reasonable grounds.
"Reasonable grounds," when used in the context of a law enforcement officer's decision to make an arrest, means probable cause.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5141-S.SL.pdf?cite=1995%20c%20332%20§%2019[1995 c 332 § 19]; ]

== 46.04.460 - Registered owner.
"Registered owner" means the person whose lawful right of possession of a vehicle has most recently been recorded with the department.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975c25.pdf?cite=1975%20c%2025%20§%203[1975 c 25 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.460[1961 c 12 § 46.04.460]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2050[1959 c 49 § 50]; prior: 1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part; ]

== 46.04.462 - Registration.
"Registration" means the registration certificate or license plates issued under the laws of this state pertaining to the registration of vehicles.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20134[2010 c 161 § 134]; ]

== 46.04.464 - Renewal notice.
"Renewal notice" means the notice to renew a vehicle registration sent to the registered owner by the department.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20135[2010 c 161 § 135]; ]

== 46.04.465 - Rental car.
. "Rental car" means a passenger car, as defined in RCW 46.04.382, that is used solely by a rental car business for rental to others, without a driver provided by the rental car business, for periods of not more than thirty consecutive days.

. "Rental car" does not include:

.. Vehicles rented or loaned to customers by automotive repair businesses while the customer's vehicle is under repair;

.. Vehicles licensed and operated as taxicabs.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2964-S.SL.pdf?cite=1992%20c%20194%20§%201[1992 c 194 § 1]; ]

== 46.04.466 - Rental car business.
"Rental car business" means a person engaging within this state in the business of renting rental cars, as determined under rules of the department of licensing.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2964-S.SL.pdf?cite=1992%20c%20194%20§%205[1992 c 194 § 5]; ]

== 46.04.467 - Rental trailer.
"Rental trailer" means a trailer, as defined in RCW 46.04.620, that is used solely by a rental car business for rental to others for periods of not more than thirty consecutive days.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1347.SL.pdf?cite=2020%20c%2011%20§%202[2020 c 11 § 2]; ]

== 46.04.468 - Report of sale.
"Report of sale" means a document or electronic record transaction that when properly completed and filed protects the seller of a vehicle from certain criminal and civil liabilities arising from use of the vehicle by another person after the vehicle has been sold or a change in ownership has occurred.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20136[2010 c 161 § 136]; ]

== 46.04.470 - Residence district.
"Residence district" means the territory contiguous to and including a public highway not comprising a business district, when the property on such public highway for a continuous distance of three hundred feet or more on either side thereof is in the main improved with residences or residences and buildings in use for business.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.470[1961 c 12 § 46.04.470]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2051[1959 c 49 § 51]; prior: 1937 c 189 § 1, part; RRS § 6360-1, part; 1929 c 180 § 1, part; 1927 c 309 § 2, part; RRS § 6362-2, part; ]

== 46.04.480 - Revoke.
"Revoke," in all its forms, means the invalidation for a period of one calendar year and thereafter until reissue. However, under the provisions of RCW 46.20.285, 46.20.311, 46.20.265, or 46.61.5055, and chapters 46.32 and 46.65 RCW, the invalidation may last for a period other than one calendar year.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1304-S.SL.pdf?cite=2007%20c%20419%20§%204[2007 c 419 § 4]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5141-S.SL.pdf?cite=1995%20c%20332%20§%2010[1995 c 332 § 10]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6047-S.SL.pdf?cite=1994%20c%20275%20§%2038[1994 c 275 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c148.pdf?cite=1988%20c%20148%20§%208[1988 c 148 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c407.pdf?cite=1985%20c%20407%20§%201[1985 c 407 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c165.pdf?cite=1983%20c%20165%20§%2014[1983 c 165 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c165.pdf?cite=1983%20c%20165%20§%2013[1983 c 165 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c62.pdf?cite=1979%20c%2062%20§%207[1979 c 62 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.480[1961 c 12 § 46.04.480]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2052[1959 c 49 § 52]; prior:  1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part.  1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.485 - Ride share license plates.
"Ride share license plates" means special license plates issued for motor vehicles that are used primarily for commuter ride sharing as defined in *RCW 46.74.010.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20137[2010 c 161 § 137]; ]

== 46.04.490 - Road tractor.
"Road tractor" includes every motor vehicle designed and used primarily as a road building vehicle in drawing road building machinery and devices.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.490[1961 c 12 § 46.04.490]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2053[1959 c 49 § 53]; prior:  1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part.  1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.500 - Roadway.
"Roadway" means that portion of a highway improved, designed, or ordinarily used for vehicular travel, exclusive of the sidewalk or shoulder even though such sidewalk or shoulder is used by persons riding bicycles. In the event a highway includes two or more separated roadways, the term "roadway" shall refer to any such roadway separately but shall not refer to all such roadways collectively.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977c24.pdf?cite=1977%20c%2024%20§%201[1977 c 24 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.500[1961 c 12 § 46.04.500]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2054[1959 c 49 § 54]; prior:  1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part.  1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.510 - Safety zone.
"Safety zone" means the area or space officially set apart within a roadway for the exclusive use of pedestrians and which is protected or is marked or indicated by painted marks, signs, buttons, standards, or otherwise, so as to be plainly discernible.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.510[1961 c 12 § 46.04.510]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2055[1959 c 49 § 55]; prior: 1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.514 - Salvage vehicle.
"Salvage vehicle" means a vehicle whose certificate of title has been surrendered to the department under RCW 46.12.600 due to the vehicle's destruction or declaration as a total loss or for which there is documentation indicating that the vehicle has been declared salvage or has been damaged to the extent that the owner, an insurer, or other person acting on behalf of the owner, has determined that the cost of parts and labor plus the salvage value has made it uneconomical to repair the vehicle. "Salvage vehicle" does not include a motor vehicle having a model year designation of a calendar year that is at least six years before the calendar year in which the vehicle was wrecked, destroyed, or damaged, unless, after June 13, 2002, and immediately before the vehicle was wrecked, destroyed, or damaged, the vehicle had a retail fair market value of at least the then market value threshold amount and has a model year designation of a calendar year not more than twenty years before the calendar year in which the vehicle was wrecked, destroyed, or damaged.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20138[2010 c 161 § 138]; ]

== 46.04.516 - San Juan Islands license plates.
"San Juan Islands license plates" means license plates issued under RCW 46.18.200 that display a symbol or artwork recognizing the San Juan Islands in Washington state.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1996.SL.pdf?cite=2019%20c%20177%20§%204[2019 c 177 § 4]; ]

== 46.04.518 - Scale weight.
"Scale weight" means the weight of a vehicle without a load.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20139[2010 c 161 § 139]; ]

== 46.04.521 - School bus.
School bus means every motor vehicle used regularly to transport children to and from school or in connection with school activities, which is subject to the requirements set forth in the most recent edition of "Specifications for School Buses" published by the state superintendent of public instruction, but does not include buses operated by common carriers in urban transportation of school children or private carrier buses operated as school buses in the transportation of children to and from private schools or school activities.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1246-S.SL.pdf?cite=1995%20c%20141%20§%201[1995 c 141 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c155.pdf?cite=1965%20ex.s.%20c%20155%20§%2090[1965 ex.s. c 155 § 90]; ]

== 46.04.522 - Seattle Mariners license plates.
"Seattle Mariners license plates" means special license plates issued under RCW 46.18.200 that display a symbol or artwork recognizing the Seattle Mariners.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5746-S.SL.pdf?cite=2018%20c%2067%20§%207[2018 c 67 § 7]; ]

== 46.04.5221 - Seattle NHL hockey special license plates.
"Seattle NHL hockey special license plates" means special license plates issued under RCW 46.18.200 that display the logo of the national hockey league team based in Seattle.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2669.SL.pdf?cite=2020%20c%20129%20§%204[2020 c 129 § 4]; ]

== 46.04.523 - Seattle Seahawks license plates.
"Seattle Seahawks license plates" means special license plates issued under RCW 46.18.200 that display a symbol or artwork recognizing the Seattle Seahawks.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5152-S.SL.pdf?cite=2013%20c%20286%20§%207[2013 c 286 § 7]; ]

== 46.04.524 - Seattle Sounders FC license plates.
"Seattle Sounders FC license plates" means special license plates issued under RCW 46.18.200 that display a symbol or artwork recognizing Seattle Sounders FC.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5152-S.SL.pdf?cite=2013%20c%20286%20§%206[2013 c 286 § 6]; ]

== 46.04.525 - Seattle University license plates.
"Seattle University license plates" means special license plates issued under RCW 46.18.200 that display a symbol or artwork recognizing Seattle University.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2100.SL.pdf?cite=2014%20c%206%20§%205[2014 c 6 § 5]; ]

== 46.04.526 - Secured party.
"Secured party" has the same meaning as in *RCW 62A.1-201.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20140[2010 c 161 § 140]; ]

== 46.04.527 - Security interest.
"Security interest" has the same meaning as in RCW 62A.1-201.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20141[2010 c 161 § 141]; ]

== 46.04.530 - Semitrailer.
"Semitrailer" includes every vehicle without motive power designed to be drawn by a vehicle, motor vehicle, or truck tractor and so constructed that an appreciable part of its weight and that of its load rests upon and is carried by such other vehicle, motor vehicle, or truck tractor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c149.pdf?cite=1979%20ex.s.%20c%20149%20§%201[1979 ex.s. c 149 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.530[1961 c 12 § 46.04.530]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2057[1959 c 49 § 57]; prior:  1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part.  1937 c 189 § 1, part; RRS § 6360-1, part; 1929 c 180 § 1, part; 1927 c 309 § 2, part; RRS § 6362-2, part; ]

== 46.04.535 - Share the road license plates.
"Share the road license plates" means special license plates displaying a symbol or artwork recognizing an organization that promotes bicycle safety and awareness education. Share the road license plates commemorate the life of Cooper Jones.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20142[2010 c 161 § 142]; ]

== 46.04.540 - Sidewalk.
"Sidewalk" means that property between the curb lines or the lateral lines of a roadway and the adjacent property, set aside and intended for the use of pedestrians or such portion of private property parallel and in proximity to a public highway and dedicated to use by pedestrians.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.540[1961 c 12 § 46.04.540]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2058[1959 c 49 § 58]; prior: 1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.542 - Ski & ride Washington license plates.
"Ski & ride Washington license plates" means special license plates displaying a symbol or artwork recognizing the Washington snowsports industry.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20143[2010 c 161 § 143]; ]

== 46.04.545 - Snow bike.
"Snow bike" means a motorcycle or off-road motorcycle that has been modified with a conversion kit to include (1) an endless belt tread or cleats or similar means for the purposes of propulsion on snow and (2) a ski or sled type runner for the purposes of steering.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1436-S.SL.pdf?cite=2019%20c%20262%20§%204[2019 c 262 § 4]; ]

== 46.04.546 - Snowmobile.
"Snowmobile" means a self-propelled vehicle that is capable of traveling over snow or ice that (1) utilizes as its means of propulsion an endless belt tread or cleats, or any combination of these or other similar means of contact with the surface upon which it is operated, (2) is steered wholly or in part by skis or sled type runners, and (3) is not otherwise registered as, or subject to, the motor vehicle excise tax in the state of Washington.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20145[2010 c 161 § 145]; ]

== 46.04.550 - Solid tire.
"Solid tire" includes every tire of rubber or other resilient material which does not depend upon inflation with compressed air for the support of the load thereon.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.550[1961 c 12 § 46.04.550]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2059[1959 c 49 § 59]; prior:  1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part.  1937 c 189 § 1, part; RRS § 6360-1, part; 1929 c 180 § 1, part; 1927 c 309 § 2, part; RRS § 6362-2, part; ]

== 46.04.551 - Special highway construction equipment.
. "Special highway construction equipment" means any vehicle that is (a) designed and used primarily for the grading of highways, the paving of highways, earth moving, and other construction work on highways, (b) not designed or used primarily to transport persons or property on a public highway, and (c) only incidentally operated or moved over the highway.

. "Special highway construction equipment" includes, but is not limited to, road construction and maintenance machinery that is designed and used for the purposes described under subsection (1) of this section, such as portable air compressors, air drills, asphalt spreaders, bituminous mixers, bucket loaders, track laying tractors, ditchers, leveling graders, finishing machines, motor graders, paving mixers, road rollers, scarifiers, earthmoving scrapers and carryalls, lighting plants, welders, pumps, power shovels and draglines, and self-propelled and tractor-drawn earthmoving equipment and machinery, including dump trucks and tractor-dump trailer combinations that (a) are in excess of the legal width, (b) because of their length, height, or unladen weight, may not be moved on a public highway without the permit specified in RCW 46.44.090 and are not operated laden except within the boundaries of the project limits as defined by the contract, and other similar types of construction equipment, or (c) are driven or moved upon a public highway only for the purpose of crossing the highway from one property to another, provided that the movement does not exceed five hundred feet and the vehicle is equipped with wheels or pads that will not damage the roadway surface.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20144[2010 c 161 § 144]; ]

== 46.04.552 - Special mobile equipment.
"Special mobile equipment" means every vehicle not designed or used primarily for the transportation of persons or property and only incidentally operated or moved over a highway, including but not limited to: Ditch digging apparatus, well boring apparatus and road construction and maintenance machinery such as asphalt spreaders, bituminous mixers, bucket loaders, tractors other than truck tractors, ditchers, leveling graders, finishing machines, motor graders, road rollers, scarifiers, earthmoving carryalls and scrapers, power shovels and draglines, and self-propelled cranes and earthmoving equipment. The term does not include house trailers, dump trucks, truck mounted transit mixers, cranes or shovels or other vehicles designed for the transportation of persons or property to which machinery has been attached.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c17.pdf?cite=1973%201st%20ex.s.%20c%2017%20§%201[1973 1st ex.s. c 17 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c5.pdf?cite=1972%20ex.s.%20c%205%20§%201[1972 ex.s. c 5 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c154.pdf?cite=1963%20c%20154%20§%2030[1963 c 154 § 30]; ]

== 46.04.553 - Sport utility vehicle.
"Sport utility vehicle" means a high performance motor vehicle weighing six thousand pounds or less, designed to carry ten passengers or less or designated as a sport utility vehicle by the manufacturer.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20146[2010 c 161 § 146]; ]

== 46.04.554 - Square dancer license plates.
"Square dancer license plates" means special license plates displaying a symbol of square dancers.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20147[2010 c 161 § 147]; ]

== 46.04.555 - Stand or standing.
"Stand or standing" means the halting of a vehicle, whether occupied or not, otherwise than temporarily for the purpose of and while actually engaged in receiving or discharging passengers.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975c62.pdf?cite=1975%20c%2062%20§%2010[1975 c 62 § 10]; ]

== 46.04.556 - Standard issue license plates.
"Standard issue license plates" means license plates that are held for general issue, and does not mean personalized license plates or any other special license plate.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20148[2010 c 161 § 148]; ]

== 46.04.559 - State flower license plates.
"State flower license plates" means special license plates issued under RCW 46.18.200 that display the Washington state flower.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2299-S.SL.pdf?cite=2012%20c%2065%20§%203[2012 c 65 § 3]; ]

== 46.04.560 - State highway.
"State highway" includes every highway or part thereof, which has been designated as a state highway or branch thereof, by legislative enactment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975c62.pdf?cite=1975%20c%2062%20§%207[1975 c 62 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.560[1961 c 12 § 46.04.560]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2060[1959 c 49 § 60]; prior: 1929 c 180 § 1, part; 1927 c 309 § 2, part; RRS § 6362-2, part; ]

== 46.04.565 - Stop.
"Stop" when required means complete cessation from movement.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975c62.pdf?cite=1975%20c%2062%20§%2011[1975 c 62 § 11]; ]

== 46.04.566 - Stop or stopping.
"Stop or stopping" when prohibited means any halting even momentarily of a vehicle, whether occupied or not, except when necessary to avoid conflict with other traffic or in compliance with the directions of a police officer or traffic control sign or signal.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975c62.pdf?cite=1975%20c%2062%20§%2012[1975 c 62 § 12]; ]

== 46.04.570 - Streetcar.
"Streetcar" means a vehicle other than a train for transporting persons or property and operated upon stationary rails principally within cities and towns.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.570[1961 c 12 § 46.04.570]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2061[1959 c 49 § 61]; prior:  1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part.  1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.572 - Street rod vehicle.
"Street rod vehicle" means a motor vehicle that:

. Is a 1948 or older vehicle or the vehicle was manufactured after 1948 to resemble a vehicle manufactured before 1949; and

. Has alterations to one or more of the major component parts listed in RCW 46.80.010 that change the appearance or performance of the vehicle from the original manufacturer's design or has a body constructed from nonoriginal materials.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5585-S.SL.pdf?cite=2011%20c%20114%20§%201[2011 c 114 § 1]; ]

== 46.04.574 - Subagency.
"Subagency" means the licensing office in which vehicle title and registration functions are carried out by a subagent.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20149[2010 c 161 § 149]; ]

== 46.04.575 - Subagent.
"Subagent" means a person or governmental entity recommended by a county auditor or other agent and who is appointed by the director to provide vehicle registration and certificate of title services under contract with the county auditor or other agent.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20150[2010 c 161 § 150]; ]

== 46.04.580 - Suspend.
"Suspend," in all its forms and unless a different period is specified, means invalidation for any period less than one calendar year and thereafter until reinstatement.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6047-S.SL.pdf?cite=1994%20c%20275%20§%2028[1994 c 275 § 28]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c250.pdf?cite=1990%20c%20250%20§%2022[1990 c 250 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.580[1961 c 12 § 46.04.580]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2062[1959 c 49 § 62]; prior:  1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part.  1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.581 - Tab.
"Tab" or "license tab" means a sticker issued by the department and affixed to the rear license plate to identify the vehicle license expiration month and year for a specific vehicle.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20151[2010 c 161 § 151]; ]

== 46.04.582 - Tandem axle.
"Tandem axle" means any two or more consecutive axles whose centers are less than seven feet apart.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c6.pdf?cite=1988%20c%206%20§%201[1988 c 6 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c149.pdf?cite=1979%20ex.s.%20c%20149%20§%202[1979 ex.s. c 149 § 2]; ]

== 46.04.585 - Temporarily sojourning.
"Temporarily sojourning," as the term is used in chapter 46.04 RCW, shall be construed to include any nonresident who is within this state for a period of not to exceed six months in any one year.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.585[1961 c 12 § 46.04.585]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2063[1959 c 49 § 63]; prior:  1955 c 89 § 6; ]

== 46.04.586 - THC concentration.
"THC concentration" means nanograms of delta-9 tetrahydrocannabinol per milliliter of a person's whole blood. THC concentration does not include measurement of the metabolite THC-COOH, also known as carboxy-THC.

[ 2013 c 3 § 3 (Initiative Measure No. 502, approved November 6, 2012); ]

== 46.04.587 - Total loss vehicle.
"Total loss vehicle" means a vehicle that has been reported to the department as destroyed by an insurance company, self-insurer, or the vehicle owner or the owner's authorized representative.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20152[2010 c 161 § 152]; ]

== 46.04.588 - Tow dolly.
"Tow dolly" means a trailer equipped with between one and three axles designed to connect to a tow bar on the rear of a motor vehicle that is used to tow another vehicle. The front or rear wheels of the towed vehicle are secured to and rest on the tow dolly.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20153[2010 c 161 § 153]; ]

== 46.04.589 - Tracked all-terrain vehicle.
"Tracked all-terrain vehicle" means any "wheeled all-terrain vehicle" as defined in RCW 46.09.310 and weighing less than two thousand pounds in stock configuration, with tracks or a combination of tracks and skis installed in place of the standard low-pressure tires.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5016.SL.pdf?cite=2021%20c%2086%20§%202[2021 c 86 § 2]; ]

== 46.04.590 - Traffic.
"Traffic" includes pedestrians, ridden or herded animals, vehicles, streetcars, and other conveyances either singly or together, while using any public highways for purposes of travel.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.590[1961 c 12 § 46.04.590]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2064[1959 c 49 § 64]; prior:  1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part.  1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.600 - Traffic control signal.
"Traffic control signal" means any traffic device, whether manually, electrically, or mechanically operated, by which traffic alternately is directed to stop or proceed or otherwise controlled.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.600[1961 c 12 § 46.04.600]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2065[1959 c 49 § 65]; prior: 1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.611 - Traffic-control devices.
Official traffic-control devices means all signs, signals, markings and devices not inconsistent with Title 46 RCW placed or erected by authority of a public body or official having jurisdiction, for the purpose of regulating, warning or guiding traffic.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c155.pdf?cite=1965%20ex.s.%20c%20155%20§%2088[1965 ex.s. c 155 § 88]; ]

== 46.04.620 - Trailer.
"Trailer" includes every vehicle without motive power designed for being drawn by or used in conjunction with a motor vehicle constructed so that no appreciable part of its weight rests upon or is carried by such motor vehicle, but does not include a municipal transit vehicle, or any portion thereof. "Trailer" does not include a cargo extension.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2598-S.SL.pdf?cite=2016%20c%2022%20§%202[2016 c 22 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c76.pdf?cite=1974%20ex.s.%20c%2076%20§%203[1974 ex.s. c 76 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.620[1961 c 12 § 46.04.620]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2067[1959 c 49 § 67]; prior:  1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part; 1923 c 181 § 1, part; 1921 c 96 § 2, part; 1919 c 59 § 1, part; 1917 c 155 § 1, part; RRS § 6313, part.  1937 c 189 § 1, part; RRS § 6360-1, part; 1929 c 180 § 1, part; 1927 c 309 § 2, part; RRS § 6362-2, part; ]

== 46.04.621 - Transit permit.
"Transit permit" means a document that authorizes a person to operate a vehicle on a public highway of this state solely for the purpose of obtaining the necessary documentation to complete and apply for a Washington certificate of title or vehicle registration. Unlimited use of the vehicle is prohibited when operated under a transit permit.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20154[2010 c 161 § 154]; ]

== 46.04.622 - Park trailer.
"Park trailer" or "park model trailer" means a travel trailer designed to be used with temporary connections to utilities necessary for operation of installed fixtures and appliances. The trailer's gross area shall not exceed four hundred square feet when in the setup mode. "Park trailer" excludes a mobile home.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c337.pdf?cite=1989%20c%20337%20§%202[1989 c 337 § 2]; ]

== 46.04.62240 - Share the Road license plates.
"Share the Road license plates" means license plates that commemorate the life of Cooper Jones and display a symbol of an organization that promote[s] bicycle safety and awareness education in communities throughout Washington.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1254.SL.pdf?cite=2005%20c%20426%20§%202[2005 c 426 § 2]; ]

== 46.04.62250 - Signal preemption device.
"Signal preemption device" means a device that is capable of altering the normal operation of a traffic control signal. Any such device manufactured by a vehicle manufacturer is not a signal preemption device for purposes of this section if the primary purpose of the device is any purpose other than the preemption of traffic signals and the device's ability to alter traffic signals is unintended and incidental to the device's primary purpose.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1113-S.SL.pdf?cite=2005%20c%20183%20§%201[2005 c 183 § 1]; ]

== 46.04.62260 - Ski & Ride Washington license plates.
"Ski & Ride Washington license plates" means license plates issued under RCW 46.18.200 that display a symbol or artwork recognizing the efforts of the Washington snowsports industry in this state.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5061.SL.pdf?cite=2011%20c%20171%20§%2018[2011 c 171 § 18]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1116-S.SL.pdf?cite=2005%20c%20220%20§%202[2005 c 220 § 2]; ]

== 46.04.623 - Travel trailer.
"Travel trailer" means a trailer built on a single chassis transportable upon the public streets and highways that is designed to be used as a temporary dwelling without a permanent foundation and may be used without being connected to utilities.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c337.pdf?cite=1989%20c%20337%20§%203[1989 c 337 § 3]; ]

== 46.04.630 - Train.
"Train" means a vehicle propelled by steam, electricity, or other motive power with or without cars coupled thereto, operated upon stationary rails, except streetcars.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.630[1961 c 12 § 46.04.630]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2068[1959 c 49 § 68]; prior:  1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part.  1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.640 - Trolley vehicle.
"Trolley vehicle" means a vehicle the motive power for which is supplied by means of a trolley line and which may or may not be confined in its operation to a certain portion of the roadway in order to maintain trolley line contact.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.640[1961 c 12 § 46.04.640]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2069[1959 c 49 § 69]; prior:  1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part.  1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.650 - Tractor.
"Tractor" means every motor vehicle designed and used primarily for drawing other vehicles and not so constructed as to carry a load other than a part of the weight of the vehicle and load so drawn.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c18.pdf?cite=1986%20c%2018%20§%201[1986 c 18 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975c62.pdf?cite=1975%20c%2062%20§%208[1975 c 62 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.650[1961 c 12 § 46.04.650]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2070[1959 c 49 § 70]; prior:  1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312, part.  1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.652 - Transportation network company.
"Transportation network company" means a corporation, partnership, sole proprietorship, or other entity that operates in this state, and uses a digital network to connect passengers with transportation network company drivers to provide prearranged rides.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5152-S.SL.pdf?cite=2021%20c%2093%20§%203[2021 c 93 § 3]; ]

== 46.04.653 - Truck.
"Truck" means every motor vehicle designed, used, or maintained primarily for the transportation of property.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c18.pdf?cite=1986%20c%2018%20§%202[1986 c 18 § 2]; ]

== 46.04.655 - Truck tractor.
"Truck tractor" means every motor vehicle designed and used primarily for drawing other vehicles but so constructed as to permit carrying a load in addition to part of the weight of the vehicle and load so drawn.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c18.pdf?cite=1986%20c%2018%20§%203[1986 c 18 § 3]; ]

== 46.04.660 - Used vehicle.
"Used vehicle" means a vehicle which has been sold, bargained, exchanged, given away, or title transferred from the person who first took title to it from the manufacturer or first importer, dealer, or agent of the manufacturer or importer, and so used as to have become what is commonly known as "secondhand" within the ordinary meaning thereof.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.660[1961 c 12 § 46.04.660]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c49.pdf?cite=1959%20c%2049%20§%2071[1959 c 49 § 71]; prior:  1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part.  1937 c 189 § 1, part; RRS § 6360-1, part; ]

== 46.04.670 - Vehicle (as amended by 2019 c 170).
"Vehicle" includes every device capable of being moved upon a public highway and in, upon, or by which any persons or property is or may be transported or drawn upon a public highway, including bicycles. "Vehicle" does not include power wheelchairs or devices other than bicycles moved by human or animal power or used exclusively upon stationary rails or tracks. Mopeds are not considered vehicles or motor vehicles for the purposes of chapter 46.70 RCW. Bicycles and motorized foot scooters are not considered vehicles for the purposes of chapter 46.12, 46.16A, or 46.70 RCW or RCW 82.12.045. Electric personal assistive mobility devices and motorized foot scooters are not considered vehicles or motor vehicles for the purposes of chapter 46.12, 46.16A, 46.29, 46.37, or 46.70 RCW. A golf cart is not considered a vehicle, except for the purposes of chapter 46.61 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1772-S.SL.pdf?cite=2019%20c%20170%20§%202[2019 c 170 § 2]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5061.SL.pdf?cite=2011%20c%20171%20§%2019[2011 c 171 § 19]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6207-S.SL.pdf?cite=2010%20c%20217%20§%202[2010 c 217 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20155[2010 c 161 § 155]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1937.SL.pdf?cite=2003%20c%20141%20§%206[2003 c 141 § 6]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6316.SL.pdf?cite=2002%20c%20247%20§%205[2002 c 247 § 5]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2224-S.SL.pdf?cite=1994%20c%20262%20§%202[1994 c 262 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1081-S.SL.pdf?cite=1991%20c%20214%20§%202[1991 c 214 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c213.pdf?cite=1979%20ex.s.%20c%20213%20§%204[1979 ex.s. c 213 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.04.670[1961 c 12 § 46.04.670]; prior:  1959 c 49 § 72; prior:  1943 c 153 § 1, part; 1937 c 188 § 1, part; Rem. Supp. 1943 § 6312-1, part.  1937 c 189 § 1, part; RRS § 6360-1, part; 1929 c 180 § 1, part; 1927 c 309 § 2, part; RRS § 6362-2, part; ]

== 46.04.671 - Vehicle license fee.
"Vehicle license fee" means a fee collected by the state of Washington as a license fee, as that term is construed in Article II, section 40 of the state Constitution, for the act of registering a vehicle under chapter 46.16A RCW. "Vehicle license fee" does not include license plate fees, or taxes and fees collected by the department for other jurisdictions.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5061.SL.pdf?cite=2011%20c%20171%20§%2020[2011 c 171 § 20]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20156[2010 c 161 § 156]; ]

== 46.04.672 - Vehicle or pedestrian right-of-way.
"Vehicle or pedestrian right-of-way" means the right of one vehicle or pedestrian to proceed in a lawful manner in preference to another vehicle or pedestrian approaching under such circumstances of direction, speed, and proximity as to give rise to danger of collision unless one grants precedence to the other.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975c62.pdf?cite=1975%20c%2062%20§%2013[1975 c 62 § 13]; ]

== 46.04.681 - Vintage snowmobile.
"Vintage snowmobile" means a snowmobile manufactured at least thirty years ago.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20157[2010 c 161 § 157]; ]

== 46.04.683 - Washington apples license plate.
"Washington apples license plate" means a special license plate under RCW 46.18.200 that displays the Washington apple logo.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6032.SL.pdf?cite=2020%20c%2093%20§%204[2020 c 93 § 4]; ]

== 46.04.685 - Washington farmers and ranchers license plates.
"Washington farmers and ranchers license plates" means special license plates issued under RCW 46.18.200 that display a symbol or artwork recognizing Washington farmers and ranchers.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2017-S.SL.pdf?cite=2016%20c%2036%20§%205[2016 c 36 § 5]; ]

== 46.04.691 - Washington Lighthouses license plates.
"Washington Lighthouses license plates" means license plates issued under RCW 46.18.200 that display a symbol or artwork recognizing the efforts of lighthouse environmental programs in Washington state.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5061.SL.pdf?cite=2011%20c%20171%20§%2021[2011 c 171 § 21]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5424.SL.pdf?cite=2005%20c%2048%20§%202[2005 c 48 § 2]; ]

== 46.04.6910 - Washington state aviation license plates.
"Washington state aviation license plates" means special license plates issued under RCW 46.18.200 that display images of a Stearman biplane and Mount Rainier.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1400.SL.pdf?cite=2017%20c%2011%20§%205[2017 c 11 § 5]; ]

== 46.04.6911 - Washington state parks license plates.
"Washington state parks license plates" means special license plates displaying a symbol or artwork recognizing Washington state parks as premier destinations of uncommon quality that preserve significant natural, cultural, historical, and recreational resources.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20158[2010 c 161 § 158]; ]

== 46.04.6912 - Washington state wrestling license plates.
"Washington state wrestling license plates" means special license plates issued under RCW 46.18.200 that display a symbol or artwork recognizing Washington state wrestling.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1830-S.SL.pdf?cite=2016%20c%2015%20§%205[2016 c 15 § 5]; ]

== 46.04.6913 - Washington tennis license plates.
"Washington tennis license plates" means special license plates issued under RCW 46.18.200 that display a symbol or artwork recognizing tennis in Washington state.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2262.SL.pdf?cite=2016%20c%2016%20§%205[2016 c 16 § 5]; ]

== 46.04.6915 - Washington's fish license plate collection.
"Washington's fish license plate collection" means the collection of fish license plate designs. Each license plate design displays a distinct symbol or artwork, to include steelhead, recognizing the fish of Washington.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6200.SL.pdf?cite=2016%20c%2030%20§%202[2016 c 30 § 2]; ]

== 46.04.692 - Washington's National Park Fund license plates.
"Washington's National Park Fund license plates" means license plates issued under RCW 46.18.200 that display a symbol or artwork recognizing the efforts of Washington's National Park Fund in preserving Washington's national parks for future generations in Washington state.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5061.SL.pdf?cite=2011%20c%20171%20§%2022[2011 c 171 § 22]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5832-S.SL.pdf?cite=2005%20c%20177%20§%202[2005 c 177 § 2]; ]

== 46.04.693 - Washington's wildlife license plate collection.
"Washington's wildlife license plate collection" means the collection of three separate license plate designs. Each license plate design displays a distinct symbol or artwork, to include bear, deer, and elk, recognizing the wildlife of Washington.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20159[2010 c 161 § 159]; ]

== 46.04.705 - We love our pets license plates.
"We love our pets license plates" means license plates issued under RCW 46.18.200 that display a symbol or artwork recognizing the efforts of the Washington state federation of animal care and control agencies in Washington state that assists local member agencies of the federation to promote and perform spay/neuter surgery of Washington state pets, in order to reduce pet overpopulation.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5061.SL.pdf?cite=2011%20c%20171%20§%2023[2011 c 171 § 23]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5977.SL.pdf?cite=2005%20c%2071%20§%202[2005 c 71 § 2]; ]

== 46.04.710 - Wheelchair conveyance.
"Wheelchair conveyance" means any vehicle specially manufactured or designed for the transportation of a physically or medically impaired wheelchair-bound person. The vehicle may be a separate vehicle used in lieu of a wheelchair or a separate vehicle used for transporting the impaired person while occupying a wheelchair. The vehicle shall be equipped with a propulsion device capable of propelling the vehicle within a speed range established by the state patrol. The state patrol may approve and define as a wheelchair conveyance, a vehicle that fails to meet these specific criteria but is essentially similar in performance and application to vehicles that do meet these specific criteria.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c330.pdf?cite=1987%20c%20330%20§%20703[1987 c 330 § 703]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c200.pdf?cite=1983%20c%20200%20§%201[1983 c 200 § 1]; ]

== 46.04.714 - Wild on Washington license plates.
"Wild on Washington license plates" means special license plates that display a symbol or artwork symbolizing wildlife viewing in Washington state.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20161[2010 c 161 § 161]; ]

== 46.04.900 - Construction—Title applicable to state registered domestic partnerships—2009 c 521.
For the purposes of this title, the terms spouse, marriage, marital, husband, wife, widow, widower, next of kin, and family shall be interpreted as applying equally to state registered domestic partnerships or individuals in state registered domestic partnerships as well as to marital relationships and married persons, and references to dissolution of marriage shall apply equally to state registered domestic partnerships that have been terminated, dissolved, or invalidated, to the extent that such interpretation does not conflict with federal law. Where necessary to implement chapter 521, Laws of 2009, gender-specific terms such as husband and wife used in any statute, rule, or other law shall be construed to be gender neutral, and applicable to individuals in state registered domestic partnerships.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%20112[2009 c 521 § 112]; ]

