= 46.53 - Abandoned recreational vehicles.
:toc:

== 46.53.010 - Registered tow truck operators, vehicle wreckers, scrap processors, and scrap metal businesses may apply for cost reimbursement for towing, transporting, storing, dismantling, and disposing abandoned recreational vehicles—Department to develop rules—Stakeholder work group.
. A registered tow truck operator, as defined in RCW 46.55.010, vehicle wrecker, as defined in RCW 46.80.010, or scrap processor, as defined in RCW 46.79.010, and scrap metal businesses, as defined in RCW 19.290.010, may apply to the department on a form prescribed by the department for cost reimbursement for the towing, transport, storage, dismantling, and disposal of abandoned recreational vehicles from public property.

. The department may only use funds under RCW 46.68.175 for cost reimbursement for the towing, transport, storage, dismantling, and disposal of abandoned recreational vehicles. The department may not authorize reimbursements that total more than ten thousand dollars per vehicle for which cost reimbursements are requested.

. After consulting with the 2017 stakeholder group, the department may develop rules including, but not limited to, towing, transport, storage, dismantling, and disposal rates, application form and contents, and cost reimbursement and the reimbursement process, to implement this section.

. The department shall convene a stakeholder work group every two years, with the first meeting to be held within twelve months of rule adoption, to make recommendations on rule amendments.

. For the purposes of this section, an "abandoned recreational vehicle" means a camper, motor home, or travel trailer that has been impounded from public property, abandoned pursuant to chapter 46.55 RCW, and received no bids at auction, or declared an abandoned junk vehicle by a law enforcement officer, pursuant to chapter 46.55 RCW, while on public property.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6437-S.SL.pdf?cite=2018%20c%20287%20§%205[2018 c 287 § 5]; ]

