= 46.65 - Washington habitual traffic offenders act.
:toc:

== 46.65.010 - State policy enunciated.
It is hereby declared to be the policy of the state of Washington:

. To provide maximum safety for all persons who travel or otherwise use the public highways of this state; and

. To deny the privilege of operating motor vehicles on such highways to persons who by their conduct and record have demonstrated their indifference for the safety and welfare of others and their disrespect for the laws of the state, the orders of her courts and the statutorily required acts of her administrative agencies; and

. To discourage repetition of criminal acts by individuals against the peace and dignity of the state and her political subdivisions and to impose increased and added deprivation of the privilege to operate motor vehicles upon habitual offenders who have been convicted repeatedly of violations of traffic laws.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c284.pdf?cite=1971%20ex.s.%20c%20284%20§%203[1971 ex.s. c 284 § 3]; ]

== 46.65.020 - Habitual offender defined.
As used in this chapter, unless a different meaning is plainly required by the context, an habitual offender means any person, resident or nonresident, who has accumulated convictions or findings that the person committed a traffic infraction as defined in RCW 46.20.270, or, if a minor, has violations recorded with the department of licensing, for separate and distinct offenses as described in either subsection (1) or (2) below committed within a five-year period, as evidenced by the records maintained in the department of licensing: PROVIDED, That where more than one described offense is committed within a six-hour period such multiple offenses shall, on the first such occasion, be treated as one offense for the purposes of this chapter:

. Three or more convictions, singularly or in combination, of the following offenses:

.. Vehicular homicide as defined in RCW 46.61.520;

.. Vehicular assault as defined in RCW 46.61.522;

.. Driving or operating a motor vehicle while under the influence of intoxicants or drugs;

.. Driving a motor vehicle while his or her license, permit, or privilege to drive has been suspended or revoked as defined in RCW 46.20.342(1)(b);

.. Failure of the driver of any vehicle involved in an accident resulting in the injury or death of any person or damage to any vehicle which is driven or attended by any person to immediately stop such vehicle at the scene of such accident or as close thereto as possible and to forthwith return to and in every event remain at, the scene of such accident until he or she has fulfilled the requirements of RCW 46.52.020;

.. Reckless driving as defined in RCW 46.61.500;

.. Being in physical control of a motor vehicle while under the influence of intoxicating liquor or any drug as defined in RCW 46.61.504; or

.. Attempting to elude a pursuing police vehicle as defined in RCW 46.61.024;

. Twenty or more convictions or findings that the person committed a traffic infraction for separate and distinct offenses, singularly or in combination, in the operation of a motor vehicle that are required to be reported to the department of licensing other than the offenses of driving with an expired driver's license and not having a driver's license in the operator's immediate possession. Such convictions or findings shall include those for offenses enumerated in subsection (1) of this section when taken with and added to those offenses described herein but shall not include convictions or findings for any nonmoving violation. No person may be considered an habitual offender under this subsection unless at least three convictions have occurred within the three hundred sixty-five days immediately preceding the last conviction.

The offenses included in subsections (1) and (2) of this section are deemed to include offenses under any valid town, city, or county ordinance substantially conforming to the provisions cited in subsections (1) and (2) [of this section] or amendments thereto, and any federal law, or any law of another state, including subdivisions thereof, substantially conforming to the aforesaid state statutory provisions.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%209078[2010 c 8 § 9078]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5266-S.SL.pdf?cite=1991%20c%20293%20§%207[1991 c 293 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c164.pdf?cite=1983%20c%20164%20§%207[1983 c 164 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c188.pdf?cite=1981%20c%20188%20§%201[1981 c 188 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c136.pdf?cite=1979%20ex.s.%20c%20136%20§%2094[1979 ex.s. c 136 § 94]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c62.pdf?cite=1979%20c%2062%20§%201[1979 c 62 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c284.pdf?cite=1971%20ex.s.%20c%20284%20§%204[1971 ex.s. c 284 § 4]; ]

== 46.65.030 - Transcript or abstract of conviction record certified—As prima facie evidence.
The director of the department of licensing shall certify a transcript or abstract of the record of convictions and findings of traffic infractions as maintained by the department of licensing of any person whose record brings him or her within the definition of an habitual offender, as defined in RCW 46.65.020, to the hearing officer appointed in the event a hearing is requested. Such transcript or abstract may be admitted as evidence in any hearing or court proceeding and shall be prima facie evidence that the person named therein was duly convicted by the court wherein such conviction or holding was made of each offense shown by such transcript or abstract; and if such person denies any of the facts as stated therein, he or she shall have the burden of proving that such fact is untrue.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c209.pdf?cite=1983%20c%20209%20§%201[1983 c 209 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c136.pdf?cite=1979%20ex.s.%20c%20136%20§%2095[1979 ex.s. c 136 § 95]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c62.pdf?cite=1979%20c%2062%20§%202[1979 c 62 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c284.pdf?cite=1971%20ex.s.%20c%20284%20§%205[1971 ex.s. c 284 § 5]; ]

== 46.65.060 - Department findings—Revocation of license—Stay by department.
If the department finds that such person is not an habitual offender under this chapter, the proceeding shall be dismissed, but if the department finds that such person is an habitual offender, the department shall revoke the operator's license for a period of seven years: PROVIDED, That the department may stay the date of the revocation if it finds that the traffic offenses upon which it is based were caused by or are the result of alcoholism and/or drug addiction as evaluated by a program approved by the department of social and health services, and that since his or her last offense he or she has undertaken and followed a course of treatment for alcoholism and/or drug treatment in a program approved by the department of social and health services; such stay shall be subject to terms and conditions as are deemed reasonable by the department. Said stay shall continue as long as there is no further conviction for any of the offenses listed in RCW 46.65.020(1). Upon a subsequent conviction for any offense listed in RCW 46.65.020(1) or violation of any of the terms or conditions of the original stay order, the stay shall be removed and the department shall revoke the operator's license for a period of seven years.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5374.SL.pdf?cite=1999%20c%20274%20§%207[1999 c 274 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c101.pdf?cite=1985%20c%20101%20§%202[1985 c 101 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c188.pdf?cite=1981%20c%20188%20§%202[1981 c 188 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c62.pdf?cite=1979%20c%2062%20§%203[1979 c 62 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c83.pdf?cite=1973%201st%20ex.s.%20c%2083%20§%201[1973 1st ex.s. c 83 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c284.pdf?cite=1971%20ex.s.%20c%20284%20§%208[1971 ex.s. c 284 § 8]; ]

== 46.65.065 - Revocation of habitual offender's license—Request for hearing, scope—Right to appeal.
. Whenever a person's driving record, as maintained by the department, brings him or her within the definition of an habitual traffic offender, as defined in RCW 46.65.020, the department shall forthwith notify the person of the revocation in writing by certified mail at his or her address of record as maintained by the department. If the person is a nonresident of this state, notice shall be sent to the person's last known address. Notices of revocation shall inform the recipient thereof of his or her right to a formal hearing and specify the steps which must be taken in order to obtain a hearing. Within fifteen days after the notice has been given, the person may, in writing, request a formal hearing. If such a request is not made within the prescribed time the right to a hearing is waived. A request for a hearing stays the effectiveness of the revocation.

. Upon receipt of a request for a hearing, the department shall schedule a hearing in the county in which the person making the request resides, and if [the] person is a nonresident of this state, the hearing shall be held in Thurston county. The department shall give at least ten days notice of the hearing to the person.

. The scope of the hearings provided by this section is limited to the issues of whether the certified transcripts or abstracts of the convictions, as maintained by the department, show that the requisite number of violations have been accumulated within the prescribed period of time as set forth in RCW 46.65.020 and whether the terms and conditions for granting stays, as provided in RCW 46.65.060, have been met.

. Upon receipt of the hearing officer's decision, an aggrieved party may appeal to the superior court of the county in which he or she resides, or, in the case of a nonresident of this state, in the superior court of Thurston county, for review of the revocation. Notice of appeal must be filed within thirty days after receipt of the hearing officer's decision or the right to appeal is waived. Review by the court shall be de novo and without a jury.

. The filing of a notice of appeal does not stay the effective date of the revocation.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c337.pdf?cite=1989%20c%20337%20§%2010[1989 c 337 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c62.pdf?cite=1979%20c%2062%20§%205[1979 c 62 § 5]; ]

== 46.65.070 - Period during which habitual offender not to be issued license.
No license to operate motor vehicles in Washington shall be issued to an habitual offender (1) for a period of seven years from the date of the license revocation except as provided in RCW 46.65.080, and (2) until the privilege of such person to operate a motor vehicle in this state has been restored by the department of licensing as provided in this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6293-S2.SL.pdf?cite=1998%20c%20214%20§%202[1998 c 214 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c250.pdf?cite=1990%20c%20250%20§%2062[1990 c 250 § 62]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c62.pdf?cite=1979%20c%2062%20§%204[1979 c 62 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c284.pdf?cite=1971%20ex.s.%20c%20284%20§%209[1971 ex.s. c 284 § 9]; ]

== 46.65.080 - Four-year petition for license restoration—Reinstatement of driving privilege.
At the end of four years, the habitual offender may petition the department of licensing for the return of his or her operator's license and upon good and sufficient showing, the department of licensing may, wholly or conditionally, reinstate the privilege of such person to operate a motor vehicle in this state.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%209079[2010 c 8 § 9079]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6293-S2.SL.pdf?cite=1998%20c%20214%20§%203[1998 c 214 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c158.pdf?cite=1979%20c%20158%20§%20181[1979 c 158 § 181]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c284.pdf?cite=1971%20ex.s.%20c%20284%20§%2010[1971 ex.s. c 284 § 10]; ]

== 46.65.100 - Seven-year petition for license restoration—Reinstatement of driving privilege.
At the expiration of seven years from the date of any final order finding a person to be an habitual offender and directing him or her not to operate a motor vehicle in this state, such person may petition the department of licensing for restoration of his or her privilege to operate a motor vehicle in this state. Upon receipt of such petition, and for good cause shown, the department of licensing shall restore to such person the privilege to operate a motor vehicle in this state upon such terms and conditions as the department of licensing may prescribe, subject to the provisions of chapter 46.29 RCW and such other provisions of law relating to the issuance or revocation of operators' licenses.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%209080[2010 c 8 § 9080]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6293-S2.SL.pdf?cite=1998%20c%20214%20§%204[1998 c 214 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c158.pdf?cite=1979%20c%20158%20§%20182[1979 c 158 § 182]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c284.pdf?cite=1971%20ex.s.%20c%20284%20§%2012[1971 ex.s. c 284 § 12]; ]

== 46.65.900 - Construction—Chapter supplemental.
Nothing in this chapter shall be construed as amending, modifying, or repealing any existing law of Washington or any existing ordinance of any political subdivision relating to the operation or licensing of motor vehicles, the licensing of persons to operate motor vehicles or providing penalties for the violation thereof or shall be construed so as to preclude the exercise of regulatory powers of any division, agency, department, or political subdivision of the state having the statutory power to regulate such operation and licensing.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c284.pdf?cite=1971%20ex.s.%20c%20284%20§%2014[1971 ex.s. c 284 § 14]; ]

== 46.65.910 - Short title.
This chapter shall be known and may be cited as the "Washington Habitual Traffic Offenders Act."

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c284.pdf?cite=1971%20ex.s.%20c%20284%20§%2018[1971 ex.s. c 284 § 18]; ]

