= 46.66 - Washington auto theft prevention authority.
:toc:

== 46.66.010 - Authority established—Members.
. The Washington auto theft prevention authority is established. The authority shall consist of the following members, appointed by the governor:

.. The executive director of the Washington association of sheriffs and police chiefs, or the executive director's designee;

.. The chief of the Washington state patrol, or the chief's designee;

.. Two police chiefs;

.. Two sheriffs;

.. One prosecuting attorney;

.. A representative from the insurance industry who is responsible for writing property and casualty liability insurance in the state of Washington;

.. A representative from the automobile industry; and

.. One member of the general public.

. In addition, the authority may, where feasible, consult with other governmental entities or individuals from the public and private sector in carrying out its duties under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1001-S3.SL.pdf?cite=2007%20c%20199%20§%2020[2007 c 199 § 20]; ]

== 46.66.020 - Meetings—Officers—Terms.
. The Washington auto theft prevention authority shall initially convene at the call of the executive director of the Washington association of sheriffs and police chiefs, or the executive director's designee, no later than the third Monday in January 2008. Subsequent meetings of the authority shall be at the call of the chair or seven members.

. The authority shall annually elect a chairperson and other such officers as it deems appropriate from its membership.

. Members of the authority shall serve terms of four years each on a staggered schedule to be established by the first authority. For purposes of initiating a staggered schedule of terms, some members of the first authority may initially serve two years and some members may initially serve four years.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1001-S3.SL.pdf?cite=2007%20c%20199%20§%2021[2007 c 199 § 21]; ]

== 46.66.030 - Powers, duties.
. The Washington auto theft prevention authority may obtain or contract for staff services, including an executive director, and any facilities and equipment as the authority requires to carry out its duties.

. The director may enter into contracts with any public or private organization to carry out the purposes of this section and RCW 46.66.010, 46.66.020, and 46.66.040 through 46.66.080.

. The authority shall review and make recommendations to the legislature and the governor regarding motor vehicle theft in Washington state. In preparing the recommendations, the authority shall, at a minimum, review the following issues:

.. Determine the scope of the problem of motor vehicle theft, including:

... Particular areas of the state where the problem is the greatest;

... Annual data reported by local law enforcement regarding the number of reported thefts, investigations, recovered vehicles, arrests, and convictions; and

... An assessment of estimated funds needed to hire sufficient investigators to respond to all reported thefts.

.. Analyze the various methods of combating the problem of motor vehicle theft;

.. Develop and implement a plan of operation; and

.. Develop and implement a financial plan.

. The authority is not a law enforcement agency and may not gather, collect, or disseminate intelligence information for the purpose of investigating specific crimes or pursuing or capturing specific perpetrators. Members of the authority may not exercise general authority peace officer powers while acting in their capacity as members of the authority, unless the exercise of peace officer powers is necessary to prevent an imminent threat to persons or property.

. The authority shall annually report its activities, findings, and recommendations during the preceding year to the legislature by December 31st.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1001-S3.SL.pdf?cite=2007%20c%20199%20§%2022[2007 c 199 § 22]; ]

== 46.66.040 - Gifts, grants, conveyances.
The Washington auto theft prevention authority may solicit and accept gifts, grants, bequests, devises, or other funds from public and private sources to support its activities.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1001-S3.SL.pdf?cite=2007%20c%20199%20§%2023[2007 c 199 § 23]; ]

== 46.66.050 - Removal of member—Grounds—Replacement.
The governor may remove any member of the Washington auto theft prevention authority for cause including but not limited to neglect of duty, misconduct, malfeasance or misfeasance in office, or upon written request of two-thirds of the members of the authority under this chapter. Upon the death, resignation, or removal of a member, the governor shall appoint a replacement to fill the remainder of the unexpired term.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1001-S3.SL.pdf?cite=2007%20c%20199%20§%2024[2007 c 199 § 24]; ]

== 46.66.060 - Members—Compensation and travel expenses.
Members of the Washington auto theft prevention authority who are not public employees shall be compensated in accordance with RCW 43.03.250 and shall be reimbursed for travel expenses incurred in carrying out the duties of the authority in accordance with RCW 43.03.050 and 43.03.060.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1001-S3.SL.pdf?cite=2007%20c%20199%20§%2025[2007 c 199 § 25]; ]

== 46.66.070 - Members—Immunity.
Any member serving in their official capacity on the Washington auto theft prevention authority, or either their employer or employers, or other entity that selected the members to serve, are immune from a civil action based upon an act performed in good faith.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1001-S3.SL.pdf?cite=2007%20c%20199%20§%2026[2007 c 199 § 26]; ]

== 46.66.080 - Washington auto theft prevention authority account.
. The Washington auto theft prevention authority account is created in the state treasury, subject to appropriation. All revenues from the traffic infraction surcharge in RCW 46.63.110(7)(b) and all receipts from gifts, grants, bequests, devises, or other funds from public and private sources to support the activities of the auto theft prevention authority must be deposited into the account. Expenditures from the account may be used only for activities relating to motor vehicle theft, including education, prevention, law enforcement, investigation, prosecution, and confinement. During the 2011-2013, 2013-2015, and 2015-2017 fiscal biennia, the legislature may appropriate moneys from the Washington auto theft prevention authority account for criminal justice purposes and community building and may transfer funds to the state general fund such amounts as reflect the excess fund balance of the account.

. The authority shall allocate moneys appropriated from the account to public agencies for the purpose of establishing, maintaining, and supporting programs that are designed to prevent motor vehicle theft, including:

.. Financial support to prosecution agencies to increase the effectiveness of motor vehicle theft prosecution;

.. Financial support to a unit of local government or a team consisting of units of local governments to increase the effectiveness of motor vehicle theft enforcement;

.. Financial support for the procurement of equipment and technologies for use by law enforcement agencies for the purpose of enforcing motor vehicle theft laws; and

.. Financial support for programs that are designed to educate and assist the public in the prevention of motor vehicle theft.

. The costs of administration shall not exceed ten percent of the moneys in the account in any one year so that the greatest possible portion of the moneys available to the authority is expended on combating motor vehicle theft.

. Prior to awarding any moneys from the Washington auto theft prevention authority account for motor vehicle theft enforcement, the auto theft prevention authority must verify that the financial award includes sufficient funding to cover proposed activities, which include, but are not limited to: (a) State, municipal, and county offender and juvenile confinement costs; (b) administration costs; (c) law enforcement costs; (d) prosecutor costs; and (e) court costs, with a priority being given to ensuring that sufficient funding is available to cover state, municipal, and county offender and juvenile confinement costs.

. Moneys expended from the Washington auto theft prevention authority account under subsection (2) of this section shall be used to supplement, not supplant, other moneys that are available for motor vehicle theft prevention.

. Grants provided under subsection (2) of this section constitute reimbursement for purposes of RCW 43.135.060(1).

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6052-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%204%20§%20964[2015 3rd sp.s. c 4 § 964]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5034-S.SL.pdf?cite=2013%202nd%20sp.s.%20c%204%20§%20985[2013 2nd sp.s. c 4 § 985]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1087-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2050%20§%20958[2011 1st sp.s. c 50 § 958]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1086-S.SL.pdf?cite=2011%20c%205%20§%20915[2011 c 5 § 915]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1244-S.SL.pdf?cite=2009%20c%20564%20§%20945[2009 c 564 § 945]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1001-S3.SL.pdf?cite=2007%20c%20199%20§%2027[2007 c 199 § 27]; ]

== 46.66.900 - Findings—Intent—Short title—2007 c 199.
See notes following RCW 9A.56.065.

[ ]

