= 46.73 - Private carrier drivers.
:toc:

== 46.73.010 - Qualifications and hours of service.
The Washington state patrol may adopt rules establishing standards for qualifications and hours of service of drivers for private carriers as defined by *RCW 81.80.010(6). Such standards shall correlate with and, as far as reasonable, conform to the regulations contained in Title 49 C.F.R., Chapter 3, Subchapter B, Parts 391 and 395, on July 28, 1985.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5513.SL.pdf?cite=2005%20c%20319%20§%20120[2005 c 319 § 120]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c333.pdf?cite=1985%20c%20333%20§%201[1985 c 333 § 1]; ]

== 46.73.020 - Federal funds as necessary condition.
The delegation of rule-making authority contained in RCW 46.73.010 is conditioned upon the continued receipt of federal funds or grants for the support of state enforcement of such rules. Within ninety days of finding that federal funds or grants are withdrawn or not renewed, the Washington state patrol and the Washington utilities and transportation commission shall repeal any and all rules adopted under RCW 46.73.010.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c333.pdf?cite=1985%20c%20333%20§%202[1985 c 333 § 2]; ]

== 46.73.030 - Penalty.
A violation of any rule adopted by the Washington state patrol under RCW 46.73.010 is a traffic infraction.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c333.pdf?cite=1985%20c%20333%20§%203[1985 c 333 § 3]; ]

