= 46.71 - Automotive repair.
:toc:

== 46.71.005 - Legislative recognition.
The automotive repair industry supports good communication between auto repair facilities and their customers. The legislature recognizes that improved communications and accurate representations between automotive repair facilities and the customers will: Increase consumer confidence; reduce the likelihood of disputes arising; clarify repair facility lien interests; and promote fair and nondeceptive practices, thereby enhancing the safety and reliability of motor vehicles serviced by auto repair facilities in the state of Washington.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1766-S.SL.pdf?cite=1993%20c%20424%20§%201[1993 c 424 § 1]; ]

== 46.71.011 - Definitions.
For purposes of this chapter:

. An "aftermarket body part" or "nonoriginal equipment manufacturer body part" is an exterior body panel or nonstructural body component manufactured by someone other than the original equipment manufacturer and supplied through suppliers other than those in the manufacturer's normal distribution channels.

. "Automotive repair" includes but is not limited to:

.. All repairs to vehicles subject to chapter 46.16A RCW that are commonly performed in a repair facility by a motor vehicle technician including the diagnosis, installation, exchange, or repair of mechanical or electrical parts or units for any vehicle, the performance of any electrical or mechanical adjustment to any vehicle, or the performance of any service work required for routine maintenance or repair of any vehicle. However, commercial fleet repair or maintenance transactions involving two or more vehicles or ongoing service or maintenance contracts involving vehicles used primarily for business purposes are not included;

.. All work in facilities that perform one or more specialties within the automotive repair service industry including, but not limited to, body collision repair, refinishing, brake, electrical, exhaust repair or installation, frame, unibody, front-end, radiators, tires, transmission, tune-up, and windshield; and

.. The removal, replacement, or repair of exterior body panels, the removal, replacement, or repair of structural and nonstructural body components, the removal, replacement, or repair of collision damaged suspension components, and the refinishing of automotive components.

. "Automotive repair facility" or "repair facility" means any person, firm, association, or corporation who for compensation engages in the business of automotive repair or diagnosis, or both, of malfunctions of motor vehicles subject to licensure under chapter 46.16A RCW and repair and refinishing auto-body collision damage as well as overall refinishing and cosmetic repairs.

. A "rebuilt" part consists of a used assembly that has been dismantled and inspected with only the defective parts being replaced.

. A "remanufactured" part consists of a used assembly that has been dismantled with the core parts being remachined and all other parts replaced with new parts so as to provide performance comparable to that found originally.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5061.SL.pdf?cite=2011%20c%20171%20§%2092[2011 c 171 § 92]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1766-S.SL.pdf?cite=1993%20c%20424%20§%202[1993 c 424 § 2]; ]

== 46.71.015 - Estimates—Invoices—Recordkeeping requirements.
. Except as otherwise provided in RCW 46.71.025, all estimates that exceed one hundred dollars shall be in writing and include the following information: The date; the name, address, and telephone number of the repair facility; the name, address, and telephone number, if available, of the customer or the customer's designee; if the vehicle is delivered for repair, the year, make, and model of the vehicle, the vehicle license plate number or last eight digits of the vehicle identification number, and the odometer reading of the vehicle; a description of the problem reported by the customer or the specific repairs requested by the customer; and a choice of alternatives described in RCW 46.71.025.

. Whether or not a written estimate is required, parts and labor provided by an automotive repair facility shall be clearly and accurately recorded in writing on an invoice and shall include, in addition to the information listed in subsection (1) of this section, the following information: A description of the repair or maintenance services performed on the vehicle; a list of all parts supplied, identified by name and part number, if available, part kit description or recognized package or shop supplies, if any, and an indication whether the parts supplied are rebuilt, or used, if applicable or where collision repair is involved, aftermarket body parts or nonoriginal equipment manufacturer body parts, if applicable; the price per part charged, if any, and the total amount charged for all parts; the total amount charged for all labor, if any; and the total charge. Parts and labor do not need to be separately disclosed if pricing is expressed as an advertised special by the job, a predisclosed written repair menu item, or a routine service package.

. Notwithstanding subsection (2) of this section, if the repair work is performed under warranty or without charge to the customer, other than an applicable deductible, the repair facility shall provide either an itemized list of the parts supplied, or describe the service performed on the vehicle, but the repair facility is not required to provide any pricing information for parts or labor.

. A copy of the estimate, unless waived, shall be provided to the customer or customer's designee prior to providing parts or labor as required under RCW 46.71.025. A copy of the invoice shall be provided to the customer upon completion of the repairs.

. Only material omissions, under this section, are actionable in a court of law or equity.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1766-S.SL.pdf?cite=1993%20c%20424%20§%203[1993 c 424 § 3]; ]

== 46.71.021 - Disposition of replaced parts.
Except for parts covered by a manufacturer's or other warranty or parts that must be returned to a distributor, remanufacturer, or rebuilder, the repair facility shall return replaced parts to the customer at the time the work is completed if the customer requested the parts at the time of authorization of the repair. If a customer at the time of authorization of the repair requests the return of a part that must be returned to the manufacturer, remanufacturer, distributor, recycler, or rebuilder, or must be disposed of as required by law, the repair facility shall offer to show the part to the customer. The repair facility need not show a replaced part if no charge is being made for the replacement part.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1766-S.SL.pdf?cite=1993%20c%20424%20§%204[1993 c 424 § 4]; ]

== 46.71.025 - Written estimate required—Alternatives—Authorization to exceed—Exceptions.
. Except as provided in subsections (3) and (4) of this section, a repair facility prior to providing parts or labor shall provide the customer or the customer's designee with a written price estimate of the total cost of the repair, including parts and labor, or where collision repair is involved, aftermarket body parts or nonoriginal equipment manufacturer body parts, if applicable, or offer the following alternatives:

"YOU ARE ENTITLED TO A WRITTEN PRICE ESTIMATE FOR THE REPAIRS YOU HAVE AUTHORIZED. YOU ARE ALSO ENTITLED TO REQUIRE THE REPAIR FACILITY TO OBTAIN YOUR ORAL OR WRITTEN AUTHORIZATION TO EXCEED THE WRITTEN PRICE ESTIMATE. YOUR SIGNATURE OR INITIALS WILL INDICATE YOUR SELECTION.

1. I request an estimate in writing before you begin repairs. Contact me if the price will exceed this estimate by more than ten percent.

2. Proceed with repairs but contact me if the price will exceed $. . . . . .

3. I do not want a written estimate.

. . . . . . . . . . . . .    (Initial or signature)

Date:  . . . . . . . .    Time:  . . . . . . . ."

. The repair facility may not charge the customer more than one hundred ten percent, exclusive of retail sales tax, of the total shown on the written price estimate. Neither of these limitations apply if, before providing additional parts or labor the repair facility obtains either the oral or written authorization of the customer, or the customer's designee, to exceed the written price estimate. The repair facility or its representative shall note on the estimate the date and time of obtaining an oral authorization, the additional parts and labor required, the estimated cost of the additional parts and labor, or where collision repair is involved, aftermarket body parts or nonoriginal equipment manufacturer body parts, if applicable, the name or identification number of the employee who obtains the authorization, and the name and telephone number of the person authorizing the additional costs.

. A written estimate shall not be required when the customer's motor vehicle or component has been brought to an automotive repair facility's regular place of business without face-to-face contact between the customer and the repair facility. Face-to-face contact means actual in-person discussion between the customer or his or her designee and the agent or employee of the automotive repair facility authorized to intake vehicles or components. However, prior to providing parts and labor, the repair facility must obtain either the oral or written authorization of the customer or the customer's designee. The repair facility or its representative shall note on the estimate or repair order the date and time of obtaining an oral authorization, the total amount authorized, the name or identification number of the employee who obtains the authorization, and the name of the person authorizing the repairs.

. [Empty]
.. A written estimate is not required for the repair of any vehicle that:

... Qualifies for a horseless carriage license plate as defined in RCW 46.04.199 or a collector vehicle license plate as defined in RCW 46.04.1261;

... Is a street rod vehicle as defined in RCW 46.04.572 or a custom vehicle as defined in RCW 46.04.161; or

... Is a parts car, which, for the purposes of this section, means a motor vehicle that is owned by a collector to furnish parts for restoration or maintenance of a vehicle described in RCW 46.18.220(1) or 46.18.255(1), thus enabling a collector to preserve, restore, and maintain such a vehicle.

.. This subsection does not prohibit a customer seeking repair services for one of the vehicles listed under this subsection from requesting a written estimate, which may be provided at the discretion of the agent or employee of the automotive repair facility, and in which case the repair facility shall provide notification and documentation advising the customer that the requested repairs will be furnished on a time and materials basis, to be billed at least every two weeks.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6005-S.SL.pdf?cite=2012%20c%2027%20§%201[2012 c 27 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1766-S.SL.pdf?cite=1993%20c%20424%20§%205[1993 c 424 § 5]; ]

== 46.71.031 - Required signs.
An automotive repair facility shall post in a prominent place on the business premises one or more signs, readily visible to customers, in the following form:

"YOUR CUSTOMER RIGHTS

YOU ARE ENTITLED BY LAW TO:

1.

A WRITTEN ESTIMATE FOR REPAIRS WHICH WILL COST MORE THAN ONE HUNDRED DOLLARS, UNLESS WAIVED OR ABSENT FACE-TO-FACE CONTACT (SEE ITEM 4 BELOW);

2.

RETURN OR INSPECTION OF ALL REPLACED PARTS, IF REQUESTED AT TIME OF REPAIR AUTHORIZATION;

3.

AUTHORIZE ORALLY OR IN WRITING ANY REPAIRS WHICH EXCEED THE ESTIMATED TOTAL PRESALES TAX COST BY MORE THAN TEN PERCENT;

4.

AUTHORIZE ANY REPAIRS ORALLY OR IN WRITING IF YOUR VEHICLE IS LEFT WITH THE REPAIR FACILITY WITHOUT FACE-TO-FACE CONTACT BETWEEN YOU AND THE REPAIR FACILITY PERSONNEL.

IF YOU HAVE AUTHORIZED A REPAIR IN ACCORDANCE WITH THE ABOVE INFORMATION YOU ARE REQUIRED TO PAY FOR THE COSTS OF THE REPAIR PRIOR TO TAKING THE VEHICLE FROM THE PREMISES."

The first line of each sign shall be in letters not less than one and one-half inch in height and the remaining lines shall be in letters not less than one-half inch in height.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1766-S.SL.pdf?cite=1993%20c%20424%20§%206[1993 c 424 § 6]; ]

== 46.71.035 - Failure to comply with estimate requirements.
An automotive repair facility that fails to comply with the estimate requirements of RCW 46.71.025 is barred from recovering in an action to recover for automotive repairs any amount in excess of one hundred ten percent of the amount authorized by the customer, or the customer's designee, unless the repair facility proves by a preponderance of the evidence that its conduct was reasonable, necessary, and justified under the circumstances. In an action to recover for automotive repairs the prevailing party may, at the discretion of the court, recover the costs of the action and reasonable attorneys' fees.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1766-S.SL.pdf?cite=1993%20c%20424%20§%207[1993 c 424 § 7]; ]

== 46.71.041 - Liens barred for failure to comply.
A repair facility that fails to comply with RCW 46.71.021, 46.71.025, or 46.71.031 is barred from asserting a possessory or chattel lien for the amount of the unauthorized parts or labor upon the motor vehicle or component.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1766-S.SL.pdf?cite=1993%20c%20424%20§%208[1993 c 424 § 8]; ]

== 46.71.045 - Unlawful acts or practices.
Each of the following acts or practices are unlawful:

. Advertising that is false, deceptive, or misleading. A single or isolated media mistake does not constitute a false, deceptive, or misleading statement or misrepresentation under this section;

. Materially understating or misstating the estimated price for a specified repair procedure;

. Retaining payment from a customer for parts not delivered or installed or a labor operation or repair procedure that has not actually been performed;

. Unauthorized operation of a customer's vehicle for purposes not related to repair or diagnosis;

. Failing or refusing to provide a customer, upon request, a copy, at no charge, of any document signed by the customer;

. Retaining duplicative payment from both the customer and the warranty or extended service contract provider for the same covered component, part, or labor;

. Charging a customer for unnecessary repairs. For purposes of this subsection "unnecessary repairs" means those for which there is no reasonable basis for performing the service. A reasonable basis includes, but is not limited to: (a) That the repair service is consistent with specifications established by law or the manufacturer of the motor vehicle, component, or part; (b) that the repair is in accordance with accepted industry standards; or (c) that the repair was performed at the specific request of the customer.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1766-S.SL.pdf?cite=1993%20c%20424%20§%209[1993 c 424 § 9]; ]

== 46.71.051 - Copy of warranty.
The repair facility shall make available, upon request, a copy of any express warranty provided by the repair facility to the customer that covers repairs performed on the vehicle.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1766-S.SL.pdf?cite=1993%20c%20424%20§%2010[1993 c 424 § 10]; ]

== 46.71.060 - Retention of price estimates and invoices.
Every automotive repair facility shall retain and make available for inspection, upon request by the customer or the customer's authorized representative, true copies of the written price estimates and invoices required under this chapter for at least one year after the date on which the repairs were performed. Such copies may be maintained as electronic records and not as hard copies as long as the repair facility is capable of printing the records in hard copy upon request of the customer or the customer's authorized representative.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6326-S.SL.pdf?cite=2016%20sp.s.%20c%2016%20§%202[2016 sp.s. c 16 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1766-S.SL.pdf?cite=1993%20c%20424%20§%2011[1993 c 424 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c62.pdf?cite=1982%20c%2062%20§%207[1982 c 62 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c280.pdf?cite=1977%20ex.s.%20c%20280%20§%206[1977 ex.s. c 280 § 6]; ]

== 46.71.070 - Consumer Protection Act—Defense.
The legislature finds that the practices covered by this chapter are matters vitally affecting the public interest for the purpose of applying the Consumer Protection Act, chapter 19.86 RCW. Violations of this chapter are not reasonable in relation to the development and preservation of business. A violation of this chapter is an unfair or deceptive act in trade or commerce and an unfair method of competition for the purpose of applying the Consumer Protection Act, chapter 19.86 RCW. In an action under chapter 19.86 RCW due to an automotive repair facility's charging a customer an amount in excess of one hundred ten percent of the amount authorized by the customer, a violation shall not be found if the automotive repair facility proves by a preponderance of the evidence that its conduct was reasonable, necessary, and justified under the circumstances.

Notwithstanding RCW 46.64.050, no violation of this chapter shall give rise to criminal liability under that section.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1766-S.SL.pdf?cite=1993%20c%20424%20§%2012[1993 c 424 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c62.pdf?cite=1982%20c%2062%20§%209[1982 c 62 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c280.pdf?cite=1977%20ex.s.%20c%20280%20§%207[1977 ex.s. c 280 § 7]; ]

== 46.71.080 - Notice of chapter to vehicle owners.
Whenever a vehicle license renewal form under RCW 46.16A.110 is given to the registered owner of any vehicle, the department of licensing shall give to the owner written notice of the provisions of this chapter in a manner prescribed by the director of licensing.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5061.SL.pdf?cite=2011%20c%20171%20§%2093[2011 c 171 § 93]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c62.pdf?cite=1982%20c%2062%20§%2010[1982 c 62 § 10]; ]

== 46.71.090 - Notice of chapter to repair facilities.
When the department of revenue issues a registration certificate under RCW 82.32.030 to an automotive repair facility, it must give written notice to the person of the requirements of this chapter in a manner prescribed by the director of revenue, including by electronic means. The department of revenue must also post information about the requirements of this chapter on its public web site.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5275-S.SL.pdf?cite=2015%20c%2086%20§%20201[2015 c 86 § 201]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1766-S.SL.pdf?cite=1993%20c%20424%20§%2013[1993 c 424 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c62.pdf?cite=1982%20c%2062%20§%2011[1982 c 62 § 11]; ]

== 46.71.100 - Transporter's license allowed.
Any automotive repair facility may apply for a transporter's license under chapter 46.76 RCW for the purpose of evaluating vehicles in need of repair, or that have been repaired, on the public roads of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1742.SL.pdf?cite=2018%20c%2016%20§%205[2018 c 16 § 5]; ]

