= 46.74 - Ride sharing.
:toc:

== 46.74.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly indicates otherwise.

. "Commuter ride sharing" means a car pool or van pool arrangement whereby one or more fixed groups not exceeding fifteen persons each including the drivers, and (a) not fewer than five persons including the drivers, or (b) not fewer than four persons including the drivers where at least two of those persons are confined to wheelchairs when riding, are transported in a passenger motor vehicle with a gross vehicle weight not exceeding ten thousand pounds, excluding special rider equipment, between their places of abode or termini near such places, and their places of employment or educational or other institutions, each group in a single daily round trip where the drivers are also on the way to or from their places of employment or educational or other institution.

. "Flexible commuter ride sharing" means a car pool or van pool arrangement whereby a group of at least two but not exceeding fifteen persons including the driver is transported in a passenger motor vehicle with a gross vehicle weight not exceeding ten thousand pounds, excluding special rider equipment, between their places of abode or termini near such places, and their places of employment or educational or other institutions, where the driver is also on the way to or from his or her place of employment or educational or other institution.

. "Persons with special transportation needs" has the same meaning as provided in RCW 81.66.010.

. "Ride sharing for persons with special transportation needs" means an arrangement whereby a group of persons with special transportation needs, and their attendants, is transported by a public social service agency or a private, nonprofit transportation provider, as defined in RCW 81.66.010, serving persons with special needs, in a passenger motor vehicle as defined by the department to include small buses, cutaways, and modified vans not more than twenty-eight feet long: PROVIDED, That the driver need not be a person with special transportation needs.

. "Ride-sharing operator" means the person, entity, or concern, not necessarily the driver, responsible for the existence and continuance of commuter ride sharing, flexible commuter ride sharing, or ride sharing for persons with special transportation needs. The term "ride-sharing operator" includes but is not limited to an employer, an employer's agent, an employer-organized association, a state agency, a county, a city, a public transportation benefit area, or any other political subdivision that owns or leases a ride-sharing vehicle.

. "Ride-sharing promotional activities" means those activities involved in forming a commuter ride-sharing arrangement or a flexible commuter ride-sharing arrangement, including but not limited to receiving information from existing and prospective ride-sharing participants, sharing that information with other existing and prospective ride-sharing participants, matching those persons with other existing or prospective ride-sharing participants, and making assignments of persons to ride-sharing arrangements.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6333-S.SL.pdf?cite=2014%20c%2097%20§%20501[2014 c 97 § 501]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5894.SL.pdf?cite=2009%20c%20557%20§%205[2009 c 557 § 5]; prior:  1997 c 250 § 8; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1023.SL.pdf?cite=1997%20c%2095%20§%201[1997 c 95 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6699-S.SL.pdf?cite=1996%20c%20244%20§%202[1996 c 244 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c111.pdf?cite=1979%20c%20111%20§%201[1979 c 111 § 1]; ]

== 46.74.020 - Exclusion from for hire vehicle laws.
Ride-sharing vehicles are not deemed for hire vehicles and do not fall within the provisions of chapter 46.72 RCW or any other provision of Title 46 RCW affecting for hire vehicles, whether or not the ride-sharing operator receives compensation.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c111.pdf?cite=1979%20c%20111%20§%202[1979 c 111 § 2]; ]

== 46.74.030 - Operators.
The operator and the driver of a commuter ride-sharing vehicle or a flexible commuter ride-sharing vehicle shall be held to a reasonable and ordinary standard of care, and are not subject to ordinances or regulations which relate exclusively to the regulation of drivers or owners of motor vehicles operated for hire, or other common carriers or public transit carriers. No person, entity, or concern may, as a result of engaging in ride-sharing promotional activities, be liable for civil damages arising directly or indirectly (1) from the maintenance and operation of a commuter ride-sharing or flexible commuter ride-sharing vehicle; or (2) from an intentional act of another person who is participating or proposing to participate in a commuter ride-sharing or flexible commuter ride-sharing arrangement, unless the ride-sharing operator or promoter had prior, actual knowledge that the intentional act was likely to occur and had a reasonable ability to prevent the act from occurring.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1513-S.SL.pdf?cite=1997%20c%20250%20§%209[1997 c 250 § 9]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6699-S.SL.pdf?cite=1996%20c%20244%20§%203[1996 c 244 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c111.pdf?cite=1979%20c%20111%20§%203[1979 c 111 § 3]; ]

