= 46.82 - Driver training schools.
:toc:

== 46.82.280 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Behind-the-wheel instruction" means instruction in an approved driver training school instruction vehicle according to and inclusive of the required curriculum. Behind-the-wheel instruction is characterized by driving experience.

. "Classroom" means a space dedicated to and used exclusively by a driver training instructor for the instruction of students. With prior department approval, a branch office classroom may be located within alternative facilities, such as a public or private library, school, community college, college or university, or a business training facility.

. "Classroom instruction" means that portion of a traffic safety education course that is characterized by classroom-based student instruction using the required curriculum conducted by or under the direct supervision of a licensed instructor or licensed instructors.

. "Director" means the director of the department of licensing of the state of Washington.

. "Driver training education course" means a course of instruction in traffic safety education approved and licensed by the department of licensing that consists of classroom and behind-the-wheel instruction that follows the approved curriculum.

. "Driver training school" means a commercial driver training school engaged in the business of giving instruction, for a fee, in the operation of automobiles.

. "Enrollment" means the collecting of a fee or the signing of a contract for a driver training education course. "Enrollment" does not include the collecting of names and contact information for enrolling students once a driver training school is licensed to instruct.

. "Fraudulent practices" means any conduct or representation on the part of a driver training school owner or instructor including:

.. Inducing anyone to believe, or to give the impression, that a license to operate a motor vehicle or any other license granted by the director may be obtained by any means other than those prescribed by law, or furnishing or obtaining the same by illegal or improper means, or requesting, accepting, or collecting money for such purposes;

.. Operating a driver training school without a license, providing instruction without an instructor's license, verifying enrollment prior to being licensed, misleading or false statements on applications for a commercial driver training school license or instructor's license or on any required records or supporting documentation;

.. Failing to fully document and maintain all required driver training school records of instruction, school operation, and instructor training;

.. Issuing a driver training course certificate without requiring completion of the necessary behind-the-wheel and classroom instruction.

. "Instructor" means any person employed by or otherwise associated with a driver training school to instruct persons in the operation of an automobile.

. "Owner" means an individual, partnership, corporation, association, or other person or group that holds a substantial interest in a driver training school.

. "Person" means any individual, firm, corporation, partnership, or association.

. "Place of business" means a designated location at which the business of a driver training school is transacted or its records are kept.

. "Student" means any person enrolled in an approved driver training course.

. "Substantial interest holder" means a person who has actual or potential influence over the management or operation of any driver training school. Evidence of substantial interest includes, but is not limited to, one or more of the following:

.. Directly or indirectly owning, operating, managing, or controlling a driver training school or any part of a driver training school;

.. Directly or indirectly profiting from or assuming liability for debts of a driver training school;

.. Is an officer or director of a driver training school;

.. Owning ten percent or more of any class of stock in a privately or closely held corporate driver training school, or five percent or more of any class of stock in a publicly traded corporate driver training school;

.. Furnishing ten percent or more of the capital, whether in cash, goods, or services, for the operation of a driver training school during any calendar year; or

.. Directly or indirectly receiving a salary, commission, royalties, or other form of compensation from the activity in which a driver training school is or seeks to be engaged.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1481-S.SL.pdf?cite=2017%20c%20197%20§%208[2017 c 197 § 8]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2617-S2.SL.pdf?cite=2010%201st%20sp.s.%20c%207%20§%2019[2010 1st sp.s. c 7 § 19]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2095-S.SL.pdf?cite=2009%20c%20101%20§%201[2009 c 101 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2829.SL.pdf?cite=2006%20c%20219%20§%202[2006 c 219 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c80.pdf?cite=1986%20c%2080%20§%201[1986 c 80 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c51.pdf?cite=1979%20ex.s.%20c%2051%20§%201[1979 ex.s. c 51 § 1]; ]

== 46.82.285 - Application of uniform regulation of business and professions act.
The uniform regulation of business and professions act, chapter 18.235 RCW, governs unlicensed practice, the issuance and denial of licenses, and the discipline of licensees under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2829.SL.pdf?cite=2006%20c%20219%20§%201[2006 c 219 § 1]; ]

== 46.82.290 - Administration of chapter—Adoption of rules.
. The director shall be responsible for the administration and enforcement of the law pertaining to driver training schools as set forth in this chapter.

. The director is authorized to adopt and enforce such reasonable rules as may be consistent with and necessary to carry out this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c51.pdf?cite=1979%20ex.s.%20c%2051%20§%202[1979 ex.s. c 51 § 2]; ]

== 46.82.300 - Driver instructors' advisory committee.
[ NOTES:; ]

== 46.82.310 - School licenses—Insurance.
. No person shall engage in the business of conducting a driver training school without a license issued by the director for that purpose. The school's license must be displayed before the school may:

.. Schedule, enroll, or engage any students in a course of instruction;

.. Issue a verification of enrollment to any student; or

.. Begin any classroom or behind-the-wheel instruction.

. An application for a driver training school license shall be filed with the director, containing such information as prescribed by the director, including a uniform business identifier number, accompanied by an application fee as set by rule of the department, which shall in no event be refunded. Before an application for a driver training school license is approved, the business practices, facilities, records, vehicles, and insurance of the proposed school must be inspected and reviewed by authorized representatives of the director. If an application is approved by the director, the applicant shall be granted a license valid for a period of one year from the date of issuance.

. A driver training school may apply for a license to establish a branch office or branch classroom by filing an application with the director, containing such information as prescribed by the director, accompanied by an application fee as set by rule of the department, which shall in no event be refunded. Before an application for a license to establish a branch office or branch classroom is approved, the business practices, facilities, records, vehicles, and insurance of the proposed branch location must be inspected and reviewed by authorized representatives of the director. If an application is approved by the director, the applicant shall be granted a license valid for a period of one year from the date of issuance.

. The annual fee for renewal of a school or branch location license shall be set by rule of the department. Subject to the department's inspection of the business, the director shall issue a license certificate to each licensee which shall be conspicuously displayed in the place of business of the licensee. If the director has not received a renewal application postmarked on or before the date a license expires the license will be marked late. If the renewal application and fee are not received within thirty days after expiration of the license, the license will be void requiring a new application as provided for in this chapter, including payment of all fees. Instruction may not be given beyond the thirty days from the expiration of the license.

. The person to whom a driver training school license has been issued must notify the director in writing within ten business days after any change is made in the officers, directors, or location of the place of business of the school.

. Except as otherwise permitted by rule of the department, a change involving the ownership of a driver training school requires a new license application, including payment of all fees.

.. The owner relinquishing the business must notify the director in writing within ten business days.

.. The new owner must submit an application and fee as prescribed by rule of the department for transfer of the school's license to the director within ten business days.

.. Upon receipt of the required notification and the application and fees for license transfer, the director shall permit continuance of the business for a period not to exceed sixty days from the date of transfer pending approval of the new application for a school license.

.. The transferred license shall remain subject to suspension, revocation, or denial in accordance with RCW 46.82.350 and 46.82.360.

. Evidence of liability insurance coverage for the instruction vehicles and the building premises of the driver training school must be filed with the director prior to the issuance or renewal of a school license, and shall meet the following standards:

.. Coverage must be provided by a company authorized to do business in Washington state;

.. Automobile liability coverage shall be in the amount of not less than one million dollars, and shall include property damage and uninsured motorists coverage;

.. The required coverage shall be maintained in full force and effect for the term of the school license;

.. Changes in insurance coverage due to cancellation or expiration require notification of the director and proof of continuing coverage within ten working days following any change; and

.. Coverage shall be issued in the name of the school and identify the covered locations and vehicles.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2095-S.SL.pdf?cite=2009%20c%20101%20§%203[2009 c 101 § 3]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2829.SL.pdf?cite=2006%20c%20219%20§%204[2006 c 219 § 4]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6814-S.SL.pdf?cite=2002%20c%20352%20§%2024[2002 c 352 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c51.pdf?cite=1979%20ex.s.%20c%2051%20§%204[1979 ex.s. c 51 § 4]; ]

== 46.82.320 - Instructor's license.
. No person affiliated with a driver training school shall give instruction in the operation of an automobile for a fee without a license issued by the director for that purpose. An application for an original or renewal instructor's license shall be filed with the director, containing such information as prescribed by this chapter and by the director, accompanied by an application fee set by rule of the department, which shall in no event be refunded. An application for a renewal instructor's license must be accompanied by proof of the applicant's continuing professional development that meets the standards adopted by the director. If the applicant satisfactorily meets the application requirements as prescribed in RCW 46.82.330, the applicant shall be granted a license valid for a period of two years from the date of issuance. An applicant for a renewal instructor's license is not required to retake the examination specified in RCW 46.82.330 to renew his or her instructor's license if his or her original instructor's license is unexpired or has not been expired for longer than six months before submission of his or her renewal application.

. The director shall issue a license certificate to each qualified applicant.

.. An employing driver training school must conspicuously display an instructor's license at its established place of business and display copies of the instructor's license at any branch office where the instructor provides instruction.

.. Unless revoked, canceled, or denied by the director, the license shall remain the property of the licensee in the event of termination of employment or employment by another driver training school.

.. If the director has not received a renewal application on or before the date a license expires, the license is void, requiring a new application as provided for in this chapter, including payment of all fees, as well as an examination subject to the exception in subsection (1) of this section.

.. If revoked, canceled, or denied by the director, the license must be surrendered to the department within ten days following the effective date of such action.

. Each licensee shall be provided with a wallet-size identification card by the director at the time the license is issued which shall be in the instructor's immediate possession at all times while engaged in instructing.

. The person to whom an instructor's license has been issued shall notify the director in writing within ten days of any change of employment or termination of employment, providing the name and address of the new driver training school by whom the instructor will be employed.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1481-S.SL.pdf?cite=2017%20c%20197%20§%209[2017 c 197 § 9]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2095-S.SL.pdf?cite=2009%20c%20101%20§%204[2009 c 101 § 4]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2829.SL.pdf?cite=2006%20c%20219%20§%205[2006 c 219 § 5]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6814-S.SL.pdf?cite=2002%20c%20352%20§%2025[2002 c 352 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c337.pdf?cite=1989%20c%20337%20§%2018[1989 c 337 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c80.pdf?cite=1986%20c%2080%20§%202[1986 c 80 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c51.pdf?cite=1979%20ex.s.%20c%2051%20§%205[1979 ex.s. c 51 § 5]; ]

== 46.82.325 - Background checks for school personnel.
. Instructors, owners, and other persons affiliated with a school who have regularly scheduled, unsupervised contact with students are required to have a background check through the Washington state patrol criminal identification system and through the federal bureau of investigation. The background check shall also include a fingerprint check using a fingerprint card. Persons covered by this section must have their background rechecked under this subsection every five years.

. In addition to the background check required under subsection (1) of this section, persons covered by this section must have a background check through the Washington criminal identification system at the time of application for any renewal license.

. The cost of the background check shall be paid by the person.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2095-S.SL.pdf?cite=2009%20c%20101%20§%205[2009 c 101 § 5]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2829.SL.pdf?cite=2006%20c%20219%20§%206[2006 c 219 § 6]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2560-S.SL.pdf?cite=2002%20c%20195%20§%204[2002 c 195 § 4]; ]

== 46.82.330 - Instructor's license—Application—Requirements.
. The application for an instructor's license shall document the applicant's fitness, knowledge, skills, and abilities to teach the classroom and behind-the-wheel instruction portions of a driver training education program in a commercial driver training school.

. An applicant shall be eligible to apply for an original instructor's certificate if the applicant possesses and meets the following qualifications and conditions:

.. Has been licensed to drive for five or more years and possesses a current and valid Washington driver's license or is a resident of a jurisdiction immediately adjacent to Washington state and possesses a current and valid license issued by such jurisdiction, and does not have on his or her driving record any of the violations or penalties set forth in (a)(i), (ii), or (iii) of this subsection. The director shall have the right to examine the driving record of the applicant from the department of licensing and from other jurisdictions and from these records determine if the applicant has had:

... Not more than one moving traffic violation within the preceding twelve months or more than two moving traffic violations in the preceding twenty-four months;

... No drug or alcohol-related traffic violation or incident within the preceding three years. If there are two or more drug or alcohol-related traffic violations in the applicant's driving history, the applicant is no longer eligible to be a driving instructor; and

... No driver's license suspension, cancellation, revocation, or denial within the preceding two years, or no more than two of these occurrences in the preceding five years;

.. Is a high school graduate or the equivalent and at least twenty-one years of age;

.. Has completed an acceptable application on a form prescribed by the director;

.. Has satisfactorily completed a course of instruction in the training of drivers acceptable to the director that is no less than sixty hours in length and includes instruction in classroom and behind-the-wheel teaching methods and supervised practice behind-the-wheel teaching of driving techniques; and

.. Has paid an examination fee as set by rule of the department and has successfully completed an instructor's examination.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1481-S.SL.pdf?cite=2017%20c%20197%20§%2010[2017 c 197 § 10]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2617-S2.SL.pdf?cite=2010%201st%20sp.s.%20c%207%20§%2021[2010 1st sp.s. c 7 § 21]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2095-S.SL.pdf?cite=2009%20c%20101%20§%206[2009 c 101 § 6]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2829.SL.pdf?cite=2006%20c%20219%20§%207[2006 c 219 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c51.pdf?cite=1979%20ex.s.%20c%2051%20§%206[1979 ex.s. c 51 § 6]; ]

== 46.82.340 - Duplicate license certificates.
In case of the loss, mutilation, or destruction of a driver training school license certificate or an instructor's license certificate, the director shall issue a duplicate thereof upon proof of the facts and payment of a fee as set by rule of the department.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2829.SL.pdf?cite=2006%20c%20219%20§%208[2006 c 219 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c51.pdf?cite=1979%20ex.s.%20c%2051%20§%207[1979 ex.s. c 51 § 7]; ]

== 46.82.350 - Suspension, revocation, or denial of licenses—Causes enumerated.
The director may suspend, revoke, deny, or refuse to renew an instructor's license or a driver training school license, or impose such other disciplinary action authorized under RCW 18.235.110, upon determination that the applicant, licensee, or owner has engaged in unprofessional conduct as defined by RCW 18.235.130 or for any of the following causes:

. Upon determination that the licensee has made a false statement or concealed any material fact in connection with the application or license renewal;

. Upon determination that the applicant, licensee, owner, or any person directly or indirectly interested in the driver training school's business has been convicted of a felony, or any crime involving violence, dishonesty, deceit, indecency, degeneracy, or moral turpitude;

. Upon determination that the applicant, licensee, owner, or any person directly or indirectly interested in the driver training school's business previously held a driver training school license which was revoked, suspended, or refused renewal by the director;

. Upon determination that the applicant, licensee, or owner does not have an established place of business as required by this chapter;

. Upon determination that the applicant or licensee has failed to require all persons with financial interest in the driver training school to be signatories to the application;

. Upon determination that the applicant, licensee, or owner has committed fraud, induced another to commit fraud, or engaged in fraudulent practices in relation to the business conducted under the license, or has induced another to resort to fraud in relation to securing for himself, herself, or another a license to drive a motor vehicle;

. Upon determination that the applicant, licensee, or owner has engaged in conduct that could endanger the educational welfare or personal safety of students or others;

. Upon determination that a licensed instructor no longer possesses and meets the qualifications and conditions set out in RCW 46.82.330(2)(a); or

. Upon determination that the applicant, licensee or owner failed to satisfy or fails to satisfy the other conditions stated in this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2829.SL.pdf?cite=2006%20c%20219%20§%209[2006 c 219 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c51.pdf?cite=1979%20ex.s.%20c%2051%20§%208[1979 ex.s. c 51 § 8]; ]

== 46.82.360 - Suspension, revocation, or denial of licenses—Failure to comply with specified business practices.
The license of any driver training school or instructor may be suspended, revoked, denied, or refused renewal, or such other disciplinary action authorized under RCW 18.235.110 may be imposed, for failure to comply with the business practices specified in this section.

. No place of business shall be established nor any business of a driver training school conducted or solicited within one thousand feet of an office or building owned or leased by the department of licensing in which examinations for drivers' licenses are conducted. The distance of one thousand feet shall be measured along the public streets by the nearest route from the place of business to such building.

. Any automobile used by a driver training school or an instructor for instruction purposes must be equipped with:

.. Dual controls for foot brake and clutch, or foot brake only in a vehicle equipped with an automatic transmission;

.. An instructor's rear view mirror; and

.. A sign in legible, printed English letters displayed on the back or top, or both, of the vehicle that:

... Is not less than twenty inches in horizontal width or less than ten inches in vertical height;

... Has the words "student driver," "instruction car," or "driving school" in letters at least two and one-half inches in height near the top;

... Has the name and telephone number of the school in similarly legible letters not less than one inch in height placed somewhere below the aforementioned words;

... Has lettering and background colors that make it clearly readable at one hundred feet in clear daylight;

.. Is displayed at all times when instruction is being given.

. Instruction may not be given by an instructor to a student who is under the age of fifteen, and behind-the-wheel instruction may not be given by an instructor to a student in an automobile unless the student possesses a current and valid instruction permit issued pursuant to RCW 46.20.055 or a current and valid driver's license.

. No driver training school or instructor shall advertise or otherwise indicate that the issuance of a driver's license is guaranteed or assured as a result of the course of instruction offered.

. No driver training school or instructor shall utilize any types of advertising without using the full, legal name of the school and identifying itself as a driver training school. Instruction vehicles and equipment, classrooms, driving simulators, training materials and services advertised must be available in a manner as might be expected by the average person reading the advertisement.

. A driver training school shall have an established place of business owned, rented, or leased by the school and regularly occupied and used exclusively for the business of giving driver instruction. The established place of business of a driver training school shall be located in a district that is zoned for business or commercial purposes or zoned for conditional use permits for schools, trade schools, or colleges. However, the use of public or private schools does not alleviate the driver training school from securing and maintaining an established place of business or from using its own classroom on a regular basis as required under this chapter.

.. The established place of business, branch office, or classroom or advertised address of any such driver training school shall not consist of or include a house trailer, residence, tent, temporary stand, temporary address, bus, telephone answering service if such service is the sole means of contacting the driver training school, a room or rooms in a hotel or rooming house or apartment house, or premises occupied by a single or multiple-unit dwelling house.

.. A driver training school may lease classroom space within a public or private school that is recognized and regulated by the office of the superintendent of public instruction to conduct student instruction as approved by the director. However, such use of public or private classroom space does not alleviate the driver training school from securing and maintaining an established place of business nor from using its own classroom on a regular basis as required by this chapter.

.. To classify as a branch office or classroom the facility must be within a thirty-five mile radius of the established place of business. The department may waive or extend the thirty-five mile restriction for driver training schools located in counties below the median population density.

.. Nothing in this subsection may be construed as limiting the authority of local governments to grant conditional use permits or variances from zoning ordinances.

. No driver training school or instructor shall conduct any type of instruction or training on a course used by the department of licensing for testing applicants for a Washington driver's license.

. Each driver training school shall maintain its student, instructor, vehicle, insurance, and operating records at its established place of business.

.. Student records must include the student's name, address, and telephone number, date of enrollment and all dates of instruction, the student's instruction permit or driver's license number, the type of training given, the total number of hours of instruction, and the name and signature of the instructor or instructors.

.. Vehicle records shall include the original insurance policies and copies of the vehicle registration for all instruction vehicles.

.. Student and instructor records shall be maintained for three years following the completion of the instruction. Vehicle records shall be maintained for five years following their issuance. All records shall be made available for inspection upon the request of the department.

.. Upon a transfer or sale of school ownership the school records shall be transferred to and become the property and responsibility of the new owner.

. Each driver training school shall, at its established place of business, display, in a place where it can be seen by all clients, a copy of the required curriculum furnished by the department. Copies of the required curriculum are to be provided to driver training schools and instructors by the director.

. Driver training schools and instructors shall submit to periodic inspections of their business practices, facilities, records, and insurance by authorized representatives of the director of the department of licensing.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1481-S.SL.pdf?cite=2017%20c%20197%20§%2011[2017 c 197 § 11]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2095-S.SL.pdf?cite=2009%20c%20101%20§%207[2009 c 101 § 7]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2829.SL.pdf?cite=2006%20c%20219%20§%2010[2006 c 219 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c337.pdf?cite=1989%20c%20337%20§%2019[1989 c 337 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c51.pdf?cite=1979%20ex.s.%20c%2051%20§%209[1979 ex.s. c 51 § 9]; ]

== 46.82.370 - Suspension, revocation, or denial of licenses—Appeal of action—Emergency suspension—Hearing, notice and procedure.
Upon notification of suspension, revocation, denial, or refusal to renew a license under this chapter, a driver training school or instructor shall have the right to appeal the action being taken. An appeal may be made to the director, who shall cause a hearing to be held in accordance with chapter 34.05 RCW. Filing an appeal shall stay the action pending the hearing and the director's decision. Upon conclusion of the hearing, the director shall issue a decision on the appeal.

. A license may, however, be temporarily suspended by the director without notice pending any prosecution, investigation, or hearing where such emergency action is warranted. A licensee or applicant entitled to a hearing shall be given due notice thereof.

. The sending of a notice of a hearing by registered mail to the last known address of a licensee or applicant in accordance with chapter 34.05 RCW shall be deemed due notice.

. The director or the director's authorized representative shall preside over the hearing and shall have the power to subpoena witnesses, administer oaths to witnesses, take testimony of any person, and cause depositions to be taken. A subpoena issued under the authority of this section shall be served in the same manner as a subpoena issued by a court of record. Witnesses subpoenaed under this section and persons other than officers or employees of the department of licensing shall be entitled to the same fees and mileage as are allowed in civil actions in courts of law.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2829.SL.pdf?cite=2006%20c%20219%20§%2011[2006 c 219 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c51.pdf?cite=1979%20ex.s.%20c%2051%20§%2010[1979 ex.s. c 51 § 10]; ]

== 46.82.380 - Appeal from action or decision of director.
Any action or decision of the director may, after a hearing is held as provided in this chapter, be appealed by the party aggrieved to the superior court of the county in which the place of business is located or where the aggrieved person resides.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c51.pdf?cite=1979%20ex.s.%20c%2051%20§%2011[1979 ex.s. c 51 § 11]; ]

== 46.82.390 - Penalty.
A violation of any provision of this chapter shall be a misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c51.pdf?cite=1979%20ex.s.%20c%2051%20§%2012[1979 ex.s. c 51 § 12]; ]

== 46.82.400 - Chapter not applicable to educational institutions.
This chapter shall not apply to or affect in any manner courses of instruction offered in high schools, vocational-technical schools, colleges, or universities which are now or hereafter established, nor shall it be applicable to instructors in any such high schools, vocational-technical schools, colleges, or universities: PROVIDED, That such course or courses are conducted by such schools in a like manner to their other regular courses. If such course is conducted by any commercial school as herein identified on a contractual basis, such school and instructors must qualify under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c51.pdf?cite=1979%20ex.s.%20c%2051%20§%2013[1979 ex.s. c 51 § 13]; ]

== 46.82.410 - Disposition of moneys collected.
All moneys collected from driver training school licenses and instructor licenses shall be deposited in the highway safety fund.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c250.pdf?cite=1990%20c%20250%20§%2073[1990 c 250 § 73]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c51.pdf?cite=1979%20ex.s.%20c%2051%20§%2014[1979 ex.s. c 51 § 14]; ]

== 46.82.420 - Required curriculum—Revocation of license for failure to teach.
. The department and the office of the superintendent of public instruction shall jointly develop and maintain a required curriculum as specified in RCW 28A.220.035. The department shall furnish to each qualifying applicant for an instructor's license or a driver training school license a copy of such curriculum.

. In addition to information on the safe, lawful, and responsible operation of motor vehicles on the state's highways, the required curriculum shall include information on:

.. Intermediate driver's license issuance, passenger and driving restrictions and sanctions for violating the restrictions, and the effect of traffic violations and collisions on the driving privileges;

.. The effects of alcohol and drug use on motor vehicle operators, including information on drug and alcohol related traffic injury and mortality rates in the state of Washington and the current penalties for driving under the influence of drugs or alcohol;

.. Motorcycle awareness, approved by the director, to ensure new operators of motor vehicles have been instructed in the importance of safely sharing the road with motorcyclists;

.. Bicycle safety, to ensure that operators of motor vehicles have been instructed in the importance of safely sharing the road with bicyclists; and

.. Pedestrian safety, to ensure that operators of motor vehicles have been instructed in the importance of safely sharing the road with pedestrians.

. Should the director be presented with acceptable proof that any licensed instructor or driver training school is not showing proper diligence in teaching the required curriculum, the instructor or school shall be required to appear before the director and show cause why the license of the instructor or school should not be revoked for such negligence. If the director does not accept such reasons as may be offered, the director may revoke the license of the instructor or school, or both.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1481-S.SL.pdf?cite=2017%20c%20197%20§%2012[2017 c 197 § 12]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2617-S2.SL.pdf?cite=2010%201st%20sp.s.%20c%207%20§%2022[2010 1st sp.s. c 7 § 22]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2564.SL.pdf?cite=2008%20c%20125%20§%203[2008 c 125 § 3]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5273.SL.pdf?cite=2007%20c%2097%20§%203[2007 c 97 § 3]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2829.SL.pdf?cite=2006%20c%20219%20§%2012[2006 c 219 § 12]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6439.SL.pdf?cite=2004%20c%20126%20§%202[2004 c 126 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1919-S.SL.pdf?cite=1991%20c%20217%20§%203[1991 c 217 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c51.pdf?cite=1979%20ex.s.%20c%2051%20§%2015[1979 ex.s. c 51 § 15]; ]

== 46.82.430 - Instructional material requirements.
Instructional material used in driver training schools shall include information on the proper use of the left-hand lane by motor vehicles on multilane highways and on bicyclists' and pedestrians' rights and responsibilities and suggested riding procedures in common traffic situations.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2439-S.SL.pdf?cite=1998%20c%20165%20§%206[1998 c 165 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c93.pdf?cite=1986%20c%2093%20§%205[1986 c 93 § 5]; ]

== 46.82.440 - Military training or experience.
An applicant with military training or experience satisfies the training or experience requirements of this chapter unless the director determines that the military training or experience is not substantially equivalent to the standards of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1418.SL.pdf?cite=2011%20c%20351%20§%2019[2011 c 351 § 19]; ]

== 46.82.441 - Spouses of military personnel—Licensure.
The director shall develop rules consistent with RCW 18.340.020 for the licensure of spouses of military personnel.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5969-S.SL.pdf?cite=2011%202nd%20sp.s.%20c%205%20§%206[2011 2nd sp.s. c 5 § 6]; ]

== 46.82.450 - Administration of knowledge and driving portions of driver licensing examination—Rules—Department oversight authority.
. Driver training schools may administer the portions of the driver licensing examination that test the applicant's knowledge of traffic laws and ability to safely operate a motor vehicle as authorized under RCW 46.20.120(6).

. The director shall adopt rules to regulate the administration of the knowledge and driving portions of the driver licensing examination. The rules must include, but are not limited to, the following provisions:

.. Limitations or requirements that determine which driver training schools may administer the knowledge portion of the examination;

.. Limitations or requirements that determine which driver training schools may administer the driving portion of the examination;

.. Requirements for the content and method of conducting the examinations to ensure consistency with industry practices;

.. Requirements for recordkeeping;

.. A requirement that all driver training school employees conducting driver licensing examinations meet the same qualifications and education and training standards as department employees who conduct such examinations, to the extent necessary to conduct the written and driving skills portions of the examinations;

.. Requirements related to whether a driver training school staff member may provide both driver training instruction and the driver licensing examination to any one student;

.. Requirements for retesting and expiring examination results;

.. Requirements for the department to monitor outcomes for applicants who take a driver licensing examination through a driver training school and to make the outcomes available to the public;

.. Requirements for annual auditing, which must include the collection of current information regarding insurance, curriculums, instructors' names and licenses, and a selection of random student files to review for accuracy; and

.. Sanctions for violations of the rules adopted under this section.

. Before a driver training school may provide a portion of the driver licensing examination, it must enter into an agreement with the department that, at a minimum, contains provisions that:

.. Allow the department to conduct random examinations, inspections, and audits without prior notice;

.. Allow the department to conduct on-site inspections at least annually;

.. Allow the department to test, at least annually, a random sample of the drivers approved by the driver training school for licensure and to cancel any driver's license that may have been issued to any driver selected for testing who refuses to be tested; and

.. Reserve to the department the right to take prompt and appropriate action against a driver training school that fails to comply with state or federal standards for a driver licensing examination or to comply with any terms of the agreement.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1635-S.SL.pdf?cite=2011%20c%20370%20§%206[2011 c 370 § 6]; ]

== 46.82.901 - Coordination of responsibilities with the office of the superintendent of public instruction—2017 c 197.
See RCW 28A.220.901.

[ ]

