= 46.80 - Vehicle wreckers.
:toc:

== 46.80.005 - Legislative declaration.
The legislature finds and declares that the distribution and sale of vehicle parts in the state of Washington vitally affects the general economy of the state and the public interest and the public welfare, and that in order to promote the public interest and the public welfare and in the exercise of its police power, it is necessary to regulate and license vehicle wreckers and dismantlers, the buyers-for-resale, and the sellers of secondhand vehicle components doing business in Washington, in order to prevent the sale of stolen vehicle parts, to prevent frauds, impositions, and other abuses, and to preserve the investments and properties of the citizens of this state.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5685-S.SL.pdf?cite=1995%20c%20256%20§%203[1995 c 256 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c253.pdf?cite=1977%20ex.s.%20c%20253%20§%201[1977 ex.s. c 253 § 1]; ]

== 46.80.010 - Definitions.
The definitions set forth in this section apply throughout this chapter.

. "Core" means a major component part received by a vehicle wrecker in exchange for a like part sold by the vehicle wrecker, is not resold as a major component part except for scrap metal value or for remanufacture, and the vehicle wrecker maintains records for three years from the date of acquisition to identify the name of the person from whom the core was received.

. "Established place of business" means a building or enclosure which the vehicle wrecker occupies either continuously or at regular periods and where his or her books and records are kept and business is transacted and which must conform with zoning regulations.

. "Interim owner" means the owner of a vehicle who has the original certificate of title for the vehicle, which certificate has been released by the person named on the certificate and assigned to the person offering to sell the vehicle to the wrecker.

. "Major component part" includes at least each of the following vehicle parts: (a) Engines and short blocks; (b) frame; (c) transmission and/or transfer case; (d) cab; (e) door; (f) front or rear differential; (g) front or rear clip; (h) quarter panel; (i) truck bed or box; (j) seat; (k) hood; (l) bumper; (m) fender; and (n) airbag. The director may supplement this list by rule.

. "Vehicle wrecker" means every person, firm, partnership, association, or corporation engaged in the business of buying, selling, or dealing in vehicles of a type required to be registered under the laws of this state, for the purpose of wrecking, dismantling, disassembling, or substantially changing the form of a vehicle, or who buys or sells integral secondhand parts of component material thereof, in whole or in part, or who deals in secondhand vehicle parts.

. "Wrecked vehicle" means a vehicle which is disassembled or dismantled or a vehicle which is acquired with the intent to dismantle or disassemble and never again to operate as a vehicle, or a vehicle which has sustained such damage that its cost to repair exceeds the fair market value of a like vehicle which has not sustained such damage, or a damaged vehicle whose salvage value plus cost to repair equals or exceeds its fair market value, if repaired, or a vehicle which has sustained such damage or deterioration that it may not lawfully operate upon the highways of this state for which the salvage value plus cost to repair exceeds its fair market value, if repaired; further, it is presumed that a vehicle is a wreck if it has sustained such damage or deterioration that it may not lawfully operate upon the highways of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201138[2010 c 161 § 1138]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%209097[2010 c 8 § 9097]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5666-S.SL.pdf?cite=1999%20c%20278%20§%201[1999 c 278 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5685-S.SL.pdf?cite=1995%20c%20256%20§%204[1995 c 256 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c253.pdf?cite=1977%20ex.s.%20c%20253%20§%202[1977 ex.s. c 253 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.80.010[1961 c 12 § 46.80.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c262.pdf?cite=1947%20c%20262%20§%201[1947 c 262 § 1]; Rem. Supp. 1947 § 8326-40; ]

== 46.80.020 - License required—Penalty.
. [Empty]
.. Except as provided in (b) of this subsection, it is unlawful for a person to engage in the business of wrecking vehicles without having first applied for and received a license.

.. As defined in *chapter 70.95 RCW, a solid waste disposal site that is compliant with all applicable regulations may wreck a nonmotorized abandoned recreational vehicle, as defined in RCW 46.53.010.

. [Empty]
.. Except as provided in (b) of this subsection, a person or firm engaged in the unlawful activity described in this section is guilty of a gross misdemeanor.

.. A second or subsequent offense is a class C felony punishable according to chapter 9A.20 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6437-S.SL.pdf?cite=2018%20c%20287%20§%208[2018 c 287 § 8]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20253[2003 c 53 § 253]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5685-S.SL.pdf?cite=1995%20c%20256%20§%205[1995 c 256 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c158.pdf?cite=1979%20c%20158%20§%20192[1979 c 158 § 192]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c253.pdf?cite=1977%20ex.s.%20c%20253%20§%203[1977 ex.s. c 253 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c7.pdf?cite=1971%20ex.s.%20c%207%20§%201[1971 ex.s. c 7 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c32.pdf?cite=1967%20c%2032%20§%2094[1967 c 32 § 94]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.80.020[1961 c 12 § 46.80.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c262.pdf?cite=1947%20c%20262%20§%202[1947 c 262 § 2]; Rem. Supp. 1947 § 8326-41; ]

== 46.80.030 - Application for license—Contents.
Application for a vehicle wrecker's license or renewal of a vehicle wrecker's license shall be made on a form for this purpose, furnished by the department of licensing, and shall be signed by the vehicle wrecker or his or her authorized agent and shall include the following information:

. Name and address of the person, firm, partnership, association, or corporation under which name the business is to be conducted;

. Names and residence address of all persons having an interest in the business or, if the owner is a corporation, the names and addresses of the officers thereof;

. Certificate of approval of the chief of police of any city or town having a population of over five thousand persons and in all other instances a member of the Washington state patrol certifying that:

.. The applicant has an established place of business at the address shown on the application; and

.. In the case of a renewal of a vehicle wrecker's license, the applicant is in compliance with this chapter and the provisions of Title 46 RCW, relating to registration and certificates of title: PROVIDED, That the above certifications in any instance can be made by an authorized representative of the department of licensing;

. Any other information that the department may require.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%209098[2010 c 8 § 9098]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5305.SL.pdf?cite=2001%20c%2064%20§%2013[2001 c 64 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c250.pdf?cite=1990%20c%20250%20§%2072[1990 c 250 § 72]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c158.pdf?cite=1979%20c%20158%20§%20193[1979 c 158 § 193]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c253.pdf?cite=1977%20ex.s.%20c%20253%20§%204[1977 ex.s. c 253 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c7.pdf?cite=1971%20ex.s.%20c%207%20§%202[1971 ex.s. c 7 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c13.pdf?cite=1967%20ex.s.%20c%2013%20§%201[1967 ex.s. c 13 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c32.pdf?cite=1967%20c%2032%20§%2095[1967 c 32 § 95]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.80.030[1961 c 12 § 46.80.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c262.pdf?cite=1947%20c%20262%20§%203[1947 c 262 § 3]; Rem. Supp. 1947 § 8326-42; ]

== 46.80.040 - Issuance of license—Fee.
The application, together with a fee of twenty-five dollars, and a surety bond as provided in RCW 46.80.070, shall be forwarded to the department. Upon receipt of the application the department shall, if the application is in order, issue a vehicle wrecker's license authorizing the wrecker to do business as such and forward the fee to the state treasurer, to be deposited in the motor vehicle fund. Upon receiving the certificate the owner shall cause it to be prominently displayed in the place of business, where it may be inspected by an investigating officer at any time.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5685-S.SL.pdf?cite=1995%20c%20256%20§%206[1995 c 256 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c7.pdf?cite=1971%20ex.s.%20c%207%20§%203[1971 ex.s. c 7 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c32.pdf?cite=1967%20c%2032%20§%2096[1967 c 32 § 96]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.80.040[1961 c 12 § 46.80.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c262.pdf?cite=1947%20c%20262%20§%204[1947 c 262 § 4]; Rem. Supp. 1947 § 8326-43; ]

== 46.80.050 - Expiration, renewal—Fee.
A license issued on this application remains in force until suspended or revoked and may be renewed annually upon reapplication according to RCW 46.80.030 and upon payment of a fee of ten dollars. A vehicle wrecker who fails or neglects to renew the license before the assigned expiration date shall pay the fee for an original vehicle wrecker license as provided in this chapter.

Whenever a vehicle wrecker ceases to do business as such or the license has been suspended or revoked, the wrecker shall immediately surrender the license to the department.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5685-S.SL.pdf?cite=1995%20c%20256%20§%207[1995 c 256 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c109.pdf?cite=1985%20c%20109%20§%207[1985 c 109 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c7.pdf?cite=1971%20ex.s.%20c%207%20§%204[1971 ex.s. c 7 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c13.pdf?cite=1967%20ex.s.%20c%2013%20§%202[1967 ex.s. c 13 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c32.pdf?cite=1967%20c%2032%20§%2097[1967 c 32 § 97]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.80.050[1961 c 12 § 46.80.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c262.pdf?cite=1947%20c%20262%20§%205[1947 c 262 § 5]; Rem. Supp. 1947 § 8326-44; ]

== 46.80.060 - License plates, indicator tabs—Fee—Display.
The vehicle wrecker shall obtain a special set of license plates or an indicator tab pursuant to RCW 46.55.065 in addition to the regular licenses and plates required for the operation of such vehicles. The special plates must be displayed on vehicles owned and/or operated by the wrecker and used in the conduct of the business. The fee for these plates shall be five dollars for the original plates and two dollars for each additional set of plates bearing the same license number. A wrecker with more than one licensed location in the state may use special plates bearing the same license number for vehicles operated out of any of the licensed locations.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2612-S.SL.pdf?cite=2018%20c%20135%20§%209[2018 c 135 § 9]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5685-S.SL.pdf?cite=1995%20c%20256%20§%208[1995 c 256 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.80.060[1961 c 12 § 46.80.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c273.pdf?cite=1957%20c%20273%20§%2021[1957 c 273 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c262.pdf?cite=1947%20c%20262%20§%206[1947 c 262 § 6]; Rem. Supp. 1947 § 8326-45; ]

== 46.80.070 - Bond.
Before issuing a vehicle wrecker's license, the department shall require the applicant to file with the department a surety bond in the amount of one thousand dollars, running to the state of Washington and executed by a surety company authorized to do business in the state of Washington. The bond shall be approved as to form by the attorney general and conditioned upon the wrecker conducting the business in conformity with the provisions of this chapter. Any person who has suffered any loss or damage by reason of fraud, carelessness, neglect, violation of the terms of this chapter, or misrepresentation on the part of the wrecking company, may institute an action for recovery against the vehicle wrecker and surety upon the bond. However, the aggregate liability of the surety to all persons shall in no event exceed the amount of the bond.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5685-S.SL.pdf?cite=1995%20c%20256%20§%209[1995 c 256 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c253.pdf?cite=1977%20ex.s.%20c%20253%20§%205[1977 ex.s. c 253 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c7.pdf?cite=1971%20ex.s.%20c%207%20§%205[1971 ex.s. c 7 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c32.pdf?cite=1967%20c%2032%20§%2098[1967 c 32 § 98]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.80.070[1961 c 12 § 46.80.070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c262.pdf?cite=1947%20c%20262%20§%207[1947 c 262 § 7]; Rem. Supp. 1947 § 8326-46; ]

== 46.80.080 - Records—Penalty.
. Every vehicle wrecker shall maintain books or files in which the wrecker shall keep a record and a description of:

.. Every vehicle wrecked, dismantled, disassembled, or substantially altered by the wrecker; and

.. Every major component part acquired by the wrecker; together with a bill of sale signed by a seller whose identity has been verified and the name and address of the person, firm, or corporation from whom the wrecker purchased the vehicle or part. Major component parts other than cores shall be further identified by the vehicle identification number of the vehicle from which the part came.

. The record shall also contain the following data regarding the wrecked or acquired vehicle or vehicle that is the source of a major component part other than a core:

.. The certificate of title number (if previously titled in this or any other state);

.. Name of state where last registered;

.. Number of the last license number plate issued;

.. Name of vehicle;

.. Motor or identification number and serial number of the vehicle;

.. Date purchased;

.. Disposition of the motor and chassis;

.. Yard number assigned by the licensee to the vehicle or major component part, which shall also appear on the identified vehicle or part; and

.. Such other information as the department may require.

. The records shall also contain a bill of sale signed by the seller for other minor component parts acquired by the licensee, identifying the seller by name, address, and date of sale.

. The records shall be maintained by the licensee at his or her established place of business for a period of three years from the date of acquisition.

. The record is subject to inspection at all times during regular business hours by members of the police department, sheriff's office, members of the Washington state patrol, or officers or employees of the department.

. A vehicle wrecker shall also maintain a similar record of all disabled vehicles that have been towed or transported to the vehicle wrecker's place of business or to other places designated by the owner of the vehicle or his or her representative. This record shall specify the name and description of the vehicle, name of owner, number of license plate, condition of the vehicle and place to which it was towed or transported.

. Failure to comply with this section is a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5666-S.SL.pdf?cite=1999%20c%20278%20§%202[1999 c 278 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5685-S.SL.pdf?cite=1995%20c%20256%20§%2010[1995 c 256 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c253.pdf?cite=1977%20ex.s.%20c%20253%20§%206[1977 ex.s. c 253 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c7.pdf?cite=1971%20ex.s.%20c%207%20§%206[1971 ex.s. c 7 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c32.pdf?cite=1967%20c%2032%20§%2099[1967 c 32 § 99]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.80.080[1961 c 12 § 46.80.080]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c262.pdf?cite=1947%20c%20262%20§%208[1947 c 262 § 8]; Rem. Supp. 1947 § 8326-47; ]

== 46.80.090 - Reports to department—Evidence of ownership.
Within thirty days after acquiring a vehicle, the vehicle wrecker shall furnish a written report to the department. This report shall be in such form as the department shall prescribe and shall be accompanied by evidence of ownership as determined by the department. No vehicle wrecker may acquire a vehicle, including a vehicle from an interim owner, without first obtaining evidence of ownership as determined by the department. For a vehicle from an interim owner, the evidence of ownership may not require that a title be issued in the name of the interim owner as required by RCW 46.12.650. The vehicle wrecker shall furnish a monthly report of all acquired vehicles. This report shall be made on forms prescribed by the department and contain such information as the department may require. This statement shall be signed by the vehicle wrecker or an authorized representative and the facts therein sworn to before a notary public, or before an officer or employee of the department designated by the director to administer oaths or acknowledge signatures, pursuant to RCW 46.01.180.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201139[2010 c 161 § 1139]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5666-S.SL.pdf?cite=1999%20c%20278%20§%203[1999 c 278 § 3]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5685-S.SL.pdf?cite=1995%20c%20256%20§%2011[1995 c 256 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c158.pdf?cite=1979%20c%20158%20§%20194[1979 c 158 § 194]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c253.pdf?cite=1977%20ex.s.%20c%20253%20§%207[1977 ex.s. c 253 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c7.pdf?cite=1971%20ex.s.%20c%207%20§%207[1971 ex.s. c 7 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c32.pdf?cite=1967%20c%2032%20§%20100[1967 c 32 § 100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.80.090[1961 c 12 § 46.80.090]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c262.pdf?cite=1947%20c%20262%20§%209[1947 c 262 § 9]; Rem. Supp. 1947 § 8326-48; ]

== 46.80.100 - Cancellation of bond.
If, after issuing a vehicle wrecker's license, the bond is canceled by the surety in a method provided by law, the department shall immediately notify the principal covered by the bond and afford the principal the opportunity of obtaining another bond before the termination of the original. If the principal fails, neglects, or refuses to obtain a replacement, the director may cancel or suspend the vehicle wrecker's license. Notice of cancellation of the bond may be accomplished by sending a notice by first-class mail using the last known address in department records for the principal covered by the bond and recording the transmittal on an affidavit of first-class mail.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5685-S.SL.pdf?cite=1995%20c%20256%20§%2012[1995 c 256 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c253.pdf?cite=1977%20ex.s.%20c%20253%20§%208[1977 ex.s. c 253 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c32.pdf?cite=1967%20c%2032%20§%20101[1967 c 32 § 101]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.80.100[1961 c 12 § 46.80.100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c262.pdf?cite=1947%20c%20262%20§%2010[1947 c 262 § 10]; Rem. Supp. 1947 § 8326-49; ]

== 46.80.110 - License penalties, civil fines, criminal penalties.
. The director or a designee may, pursuant to the provisions of chapter 34.05 RCW, by order deny, suspend, or revoke the license of a vehicle wrecker, or assess a civil fine of up to five hundred dollars for each violation, if the director finds that the applicant or licensee has:

.. Acquired a vehicle or major component part other than by first obtaining title or other documentation as provided by this chapter;

.. Willfully misrepresented the physical condition of any motor or integral part of a vehicle;

.. Sold, had in the wrecker's possession, or disposed of a vehicle or any part thereof when he or she knows that the vehicle or part has been stolen, or appropriated without the consent of the owner;

.. Sold, bought, received, concealed, had in the wrecker's possession, or disposed of a vehicle or part thereof having a missing, defaced, altered, or covered manufacturer's identification number, unless approved by a law enforcement officer;

.. Committed forgery or misstated a material fact on any title, registration, or other document covering a vehicle that has been reassembled from parts obtained from the disassembling of other vehicles;

.. Committed any dishonest act or omission that the director has reason to believe has caused loss or serious inconvenience as a result of a sale of a vehicle or part thereof;

.. Failed to comply with any of the provisions of this chapter or with any of the rules adopted under it, or with any of the provisions of Title 46 RCW relating to registration and certificates of title of vehicles;

.. Procured a license fraudulently or dishonestly;

.. Been convicted of a crime that directly relates to the business of a vehicle wrecker and the time elapsed since conviction is less than ten years, or suffered any judgment within the preceding five years in any civil action involving fraud, misrepresentation, or conversion. For the purposes of this section, conviction means in addition to a final conviction in either a federal, state, or municipal court, an unvacated forfeiture of bail or collateral deposited to secure a defendant's appearance in court, the payment of a fine, a plea of guilty, or a finding of guilt regardless of whether the sentence is deferred or the penalty is suspended.

. In addition to actions by the department under this section, it is a gross misdemeanor to violate subsection (1)(a), (b), or (h) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5685-S.SL.pdf?cite=1995%20c%20256%20§%2013[1995 c 256 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c337.pdf?cite=1989%20c%20337%20§%2017[1989 c 337 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c253.pdf?cite=1977%20ex.s.%20c%20253%20§%209[1977 ex.s. c 253 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c7.pdf?cite=1971%20ex.s.%20c%207%20§%208[1971 ex.s. c 7 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c13.pdf?cite=1967%20ex.s.%20c%2013%20§%203[1967 ex.s. c 13 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c32.pdf?cite=1967%20c%2032%20§%20102[1967 c 32 § 102]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.80.110[1961 c 12 § 46.80.110]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c262.pdf?cite=1947%20c%20262%20§%2011[1947 c 262 § 11]; Rem. Supp. 1947 § 8326-50; ]

== 46.80.121 - False or unqualified applications.
If a person whose vehicle wrecker license has previously been canceled for cause by the department files an application for a license to conduct business as a vehicle wrecker, or if the department is of the opinion that the application is not filed in good faith or that the application is filed by some person as a subterfuge for the real person in interest whose license has previously been canceled for cause, the department may refuse to issue the person a license to conduct business as a vehicle wrecker.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5685-S.SL.pdf?cite=1995%20c%20256%20§%2014[1995 c 256 § 14]; ]

== 46.80.130 - All storage at place of business—Screening required—Penalty.
. It is unlawful for a vehicle wrecker to keep a vehicle or any integral part thereof in any place other than the established place of business, designated in the certificate issued by the department, without permission of the department.

. All premises containing vehicles or parts thereof shall be enclosed by a wall or fence of such height as to obscure the nature of the business carried on therein. To the extent reasonably necessary or permitted by the topography of the land, the department may establish specifications or standards for the fence or wall. The wall or fence shall be painted or stained a neutral shade that blends in with the surrounding premises, and the wall or fence must be kept in good repair. A living hedge of sufficient density to prevent a view of the confined area may be substituted for such a wall or fence. Any dead or dying portion of the hedge shall be replaced.

. Violation of subsection (1) of this section is a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5685-S.SL.pdf?cite=1995%20c%20256%20§%2015[1995 c 256 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c7.pdf?cite=1971%20ex.s.%20c%207%20§%209[1971 ex.s. c 7 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c13.pdf?cite=1967%20ex.s.%20c%2013%20§%204[1967 ex.s. c 13 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c32.pdf?cite=1967%20c%2032%20§%20103[1967 c 32 § 103]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c117.pdf?cite=1965%20c%20117%20§%201[1965 c 117 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.80.130[1961 c 12 § 46.80.130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c262.pdf?cite=1947%20c%20262%20§%2013[1947 c 262 § 13]; Rem. Supp. 1947 § 8326-52; ]

== 46.80.140 - Rules.
The director is hereby authorized to promulgate and adopt reasonable rules and regulations not in conflict with provisions hereof for the proper operation and enforcement of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c32.pdf?cite=1967%20c%2032%20§%20104[1967 c 32 § 104]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.80.140[1961 c 12 § 46.80.140]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c262.pdf?cite=1947%20c%20262%20§%2014[1947 c 262 § 14]; Rem. Supp. 1947 § 8326-53; ]

== 46.80.150 - Inspection of licensed premises and records.
It shall be the duty of the chiefs of police, or the Washington state patrol, in cities having a population of over five thousand persons, and in all other cases the Washington state patrol, to make periodic inspection of the vehicle wrecker's licensed premises and records provided for in this chapter during normal business hours, and furnish a certificate of inspection to the department in such manner as may be determined by the department. In any instance, an authorized representative of the department may make the inspection.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5685-S.SL.pdf?cite=1995%20c%20256%20§%2016[1995 c 256 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c142.pdf?cite=1983%20c%20142%20§%209[1983 c 142 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c253.pdf?cite=1977%20ex.s.%20c%20253%20§%2010[1977 ex.s. c 253 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c7.pdf?cite=1971%20ex.s.%20c%207%20§%2010[1971 ex.s. c 7 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c13.pdf?cite=1967%20ex.s.%20c%2013%20§%205[1967 ex.s. c 13 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c32.pdf?cite=1967%20c%2032%20§%20105[1967 c 32 § 105]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.80.150[1961 c 12 § 46.80.150]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c262.pdf?cite=1947%20c%20262%20§%2015[1947 c 262 § 15]; Rem. Supp. 1947 § 8326-54; ]

== 46.80.160 - Municipal compliance.
Any municipality or political subdivision of this state that now has or subsequently makes provision for the regulation of vehicle wreckers shall comply strictly with the provisions of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5685-S.SL.pdf?cite=1995%20c%20256%20§%2017[1995 c 256 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.80.160[1961 c 12 § 46.80.160]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c262.pdf?cite=1947%20c%20262%20§%2016[1947 c 262 § 16]; Rem. Supp. 1947 § 8326-55; ]

== 46.80.170 - Violations—Penalties.
Unless otherwise provided by law, it is a misdemeanor for any person to violate any of the provisions of this chapter or the rules adopted under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5685-S.SL.pdf?cite=1995%20c%20256%20§%2018[1995 c 256 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c253.pdf?cite=1977%20ex.s.%20c%20253%20§%2011[1977 ex.s. c 253 § 11]; ]

== 46.80.180 - Cease and desist orders—Fines.
. If it appears to the director that an unlicensed person has engaged in an act or practice constituting a violation of this chapter, or a rule adopted or an order issued under this chapter, the director may issue an order directing the person to cease and desist from continuing the act or practice. The director shall give the person reasonable notice of and opportunity for a hearing. The director may issue a temporary order pending a hearing. The temporary order remains in effect until ten days after the hearing is held and becomes final if the person to whom the notice is addressed does not request a hearing within fifteen days after receipt of the notice.

. The director may assess a fine of up to one thousand dollars with the final order for each act or practice constituting a violation of this chapter by an unlicensed person.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5685-S.SL.pdf?cite=1995%20c%20256%20§%2019[1995 c 256 § 19]; ]

== 46.80.190 - Subpoenas.
. The department of licensing or its authorized agent may examine or subpoena any persons, books, papers, records, data, vehicles, or vehicle parts bearing upon the investigation or proceeding under this chapter.

. The persons subpoenaed may be required to testify and produce any books, papers, records, data, vehicles, or vehicle parts that the director deems relevant or material to the inquiry.

. The director or an authorized agent may administer an oath to the person required to testify, and a person giving false testimony after the administration of the oath is guilty of perjury in the first degree under RCW 9A.72.020.

. A court of competent jurisdiction may, upon application by the director, issue to a person who fails to comply, an order to appear before the director or officer designated by the director, to produce documentary or other evidence touching the matter under investigation or in question.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20254[2003 c 53 § 254]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5685-S.SL.pdf?cite=1995%20c%20256%20§%2020[1995 c 256 § 20]; ]

== 46.80.200 - Wholesale motor vehicle auction dealers.
. A wholesale motor vehicle auction dealer may:

.. Sell any classification of motor vehicle;

.. Sell only to motor vehicle dealers and vehicle wreckers licensed under Title 46 RCW by the state of Washington or licensed by any other state; or

.. Sell a motor vehicle belonging to the United States government, the state of Washington, or a political subdivision to nonlicensed persons as may be required by the contracting public agency. However, a publicly owned "wrecked vehicle" may be sold to motor vehicle dealers and vehicle wreckers licensed under Title 46 RCW by the state of Washington or licensed by any other state.

. If the wholesale motor vehicle auction dealer knows that a vehicle is a "wrecked vehicle," the dealer must disclose this fact on the bill of sale.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2501.SL.pdf?cite=1998%20c%20282%20§%206[1998 c 282 § 6]; ]

== 46.80.900 - Liberal construction.
The provisions of this chapter shall be liberally construed to the end that traffic in stolen vehicle parts may be prevented, and irresponsible, unreliable, or dishonest persons may be prevented from engaging in the business of wrecking vehicles or selling used vehicle parts in this state and reliable persons may be encouraged to engage in businesses of wrecking or reselling vehicle parts in this state.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5685-S.SL.pdf?cite=1995%20c%20256%20§%2021[1995 c 256 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c253.pdf?cite=1977%20ex.s.%20c%20253%20§%2013[1977 ex.s. c 253 § 13]; ]

