= 46.81A - Motorcycle skills education program.
:toc:

== 46.81A.001 - Purpose.
It is the purpose of this chapter to provide the motorcycle riders of the state with an affordable motorcycle skills education program in order to promote motorcycle safety awareness.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c227.pdf?cite=1988%20c%20227%20§%201[1988 c 227 § 1]; ]

== 46.81A.010 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Department" means the department of licensing.

. "Director" means the director of licensing.

. "Motorcycle" has the same meaning as provided in RCW 46.04.330 and excludes off-road motorcycles.

. "Motorcycle skills education program" means a motorcycle rider skills training program to be administered by the department.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1334-S.SL.pdf?cite=2013%20c%20174%20§%203[2013 c 174 § 3]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5450.SL.pdf?cite=2003%20c%20353%20§%2011[2003 c 353 § 11]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5229-S.SL.pdf?cite=2003%20c%2041%20§%204[2003 c 41 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c227.pdf?cite=1988%20c%20227%20§%202[1988 c 227 § 2]; ]

== 46.81A.020 - Powers and duties of director, department.
. The director shall administer and enforce the law pertaining to the motorcycle skills education program as set forth in this chapter.

. The director may adopt and enforce reasonable rules that are consistent with this chapter.

. The director shall revise the Washington motorcycle safety program to:

.. Institute separate novice and advanced motorcycle skills education courses for both two-wheeled and three-wheeled motorcycles that are each a minimum of eight hours;

.. Encourage the use of loaned or used motorcycles for use in the motorcycle skills education course if the instructor approves them;

.. Require all instructors for two-wheeled motorcycles to conduct at least three classes in a one-year period, and all instructors for three-wheeled motorcycles to conduct at least one class in a one-year period, to maintain their teaching eligibility.

. The department may enter into agreements to review and certify that a private motorcycle skills education course meets educational standards equivalent to those required of courses conducted under the motorcycle skills education program. An agreement entered into under this subsection must provide that the department may conduct periodic audits to ensure that educational standards continue to meet those required for courses conducted under the motorcycle skills education program, and that the costs of the review, certification, and audit process will be borne by the party seeking certification.

. The department shall adopt rules to establish a motorcycle operator subsidy program, which may address testing costs, offer financial need-based subsidies for motorcycle training, and employ other strategies to improve access to motorcycle ridership.

. The department shall obtain and compile information from applicants for a motorcycle endorsement regarding whether they have completed a state approved or certified motorcycle skills education course.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1116-S.SL.pdf?cite=2019%20c%2065%20§%202[2019 c 65 § 2]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5274-S.SL.pdf?cite=2013%20c%2033%20§%201[2013 c 33 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5273.SL.pdf?cite=2007%20c%2097%20§%202[2007 c 97 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5229-S.SL.pdf?cite=2003%20c%2041%20§%205[2003 c 41 § 5]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6282-S.SL.pdf?cite=2002%20c%20197%20§%202[2002 c 197 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6219.SL.pdf?cite=1998%20c%20245%20§%2091[1998 c 245 § 91]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5101.SL.pdf?cite=1993%20c%20115%20§%202[1993 c 115 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c227.pdf?cite=1988%20c%20227%20§%203[1988 c 227 § 3]; ]

== 46.81A.030 - Deposit of gifts.
The director may receive gifts, grants, or endowments from private sources which shall be deposited in the motorcycle safety [education] account within the highway safety fund.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c227.pdf?cite=1988%20c%20227%20§%204[1988 c 227 § 4]; ]

