= 46.87 - Proportional registration.
:toc:

== 46.87.010 - Applicability—Implementation.
This chapter applies to proportional registration and reciprocity granted under the provisions of the international registration plan (IRP). This chapter shall become effective and be implemented beginning with the 1988 registration year.

. The director may adopt and enforce rules deemed necessary to implement and administer this chapter.

. Owners having a fleet of apportionable vehicles operating in two or more IRP member jurisdictions may elect to proportionally register the vehicles of the fleet under the provisions of the IRP and this chapter in lieu of full or temporary registration as provided for in chapter 46.16A RCW.

. If a due date or an expiration date falls on a Saturday, Sunday, or a state legal holiday, such period is automatically extended through the end of the next business day.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%201[2015 c 228 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5061.SL.pdf?cite=2011%20c%20171%20§%2095[2011 c 171 § 95]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201140[2010 c 161 § 1140]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1259.SL.pdf?cite=2005%20c%20194%20§%201[2005 c 194 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2015[1987 c 244 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c18.pdf?cite=1986%20c%2018%20§%2022[1986 c 18 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c380.pdf?cite=1985%20c%20380%20§%201[1985 c 380 § 1]; ]

== 46.87.020 - Definitions.
Provisions and terms used in this chapter have the meaning given to them in the international registration plan (IRP), in chapter 46.04 RCW, or as otherwise defined in this section. Definitions given to terms by the IRP prevail unless given a different meaning in this chapter or in rules adopted under authority of this chapter.

. "Adequate records" are records maintained by the owner of the fleet sufficient to enable the department to verify the distances reported in the owner's application for apportioned registration and to evaluate the accuracy of the owner's distance accounting system.

. "Apportionable vehicle" has the meaning given by the IRP, except that it does not include vehicles with a declared gross weight of twelve thousand pounds or less.

. "Cab card" is a certificate of registration issued for a vehicle.

. "Credentials" means cab cards, apportioned plates, temporary operating authority, and validation tabs issued for proportionally registered vehicles.

. "Declared combined gross weight" means the total unladen weight of any combination of vehicles plus the maximum weight of the load to be carried on the combination of vehicles as declared by the registrant.

. "Declared gross weight" means the total unladen weight of any vehicle plus the maximum weight of the load to be carried on the vehicle as declared by the registrant. In the case of a bus, auto stage, or a passenger-carrying for hire vehicle with a seating capacity of more than six, the declared gross weight is determined by multiplying one hundred fifty pounds by the number of seats in the vehicle, including the driver's seat, and adding this amount to the unladen weight of the vehicle. If the resultant gross weight is not listed in RCW 46.17.355, it must be increased to the next higher gross weight authorized in chapter 46.44 RCW.

. "Department" means the department of licensing.

. "Fleet" means one or more apportionable vehicles.

. "In-jurisdiction distance" means the total distance, in miles, accumulated in a jurisdiction during the reporting period by vehicles of the fleet while they were a part of the fleet.

. "IRP" means the international registration plan.

. "Jurisdiction" means and includes a state, territory or possession of the United States, the District of Columbia, the Commonwealth of Puerto Rico, a foreign country, and a state or province of a foreign country.

. "Motor carrier" means an entity engaged in the transportation of goods or persons. "Motor carrier" includes a for-hire motor carrier, private motor carrier, exempt motor carrier, registrant licensed under this chapter, motor vehicle lessor, and motor vehicle lessee.

. "Owner" means a person or business who holds the legal title to a vehicle, or if a vehicle is the subject of an agreement for its conditional sale with the right of purchase upon performance of the conditions stated in the agreement and with an immediate right of possession vested in the conditional vendee, or if a vehicle is subject to a lease, contract, or other legal arrangement vesting right of possession or control, for security or otherwise, or if a mortgagor of a vehicle is entitled to possession, then the owner is deemed to be the person or business in whom is vested right of possession or control.

. [(14)] "Person" means any individual, partnership, association, public or private corporation, limited liability company, or other type of legal or commercial entity, including its members, managers, partners, directors, or officers.

. [(15)] "Prorate percentage" is the factor applied to the total proratable fees and taxes to determine the apportionable fees required for registration in a jurisdiction. It is determined by dividing the in-jurisdiction distance for a particular jurisdiction by the total distance.

. [(16)] "Registrant" means a person, business, or corporation in whose name or names a vehicle or fleet of vehicles is registered.

. [(17)] "Registration year" means the twelve-month period during which the credentials issued by the base jurisdiction are valid.

. [(18)] "Reporting period" means the period of twelve consecutive months immediately prior to July 1st of the calendar year immediately preceding the beginning of the registration year for which apportioned registration is sought. If the fleet registration period commences in October, November, or December, the reporting period is the period of twelve consecutive months immediately preceding July 1st of the current calendar year.

. [(19)] "Total distance" means all distance operated by a fleet of apportioned vehicles. "Total distance" includes the full distance traveled in all vehicle movements, both interjurisdictional and intrajurisdictional, including loaded, unladen, deadhead, and bobtail distances. Distance traveled by a vehicle while under a trip lease is considered to have been traveled by the lessor's fleet. All distance, both interstate and intrastate, accumulated by vehicles of the fleet is included in the fleet distance.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%202[2015 c 228 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201141[2010 c 161 § 1141]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1259.SL.pdf?cite=2005%20c%20194%20§%202[2005 c 194 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5429.SL.pdf?cite=2003%20c%2085%20§%201[2003 c 85 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1459.SL.pdf?cite=1997%20c%20183%20§%202[1997 c 183 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2224-S.SL.pdf?cite=1994%20c%20262%20§%2012[1994 c 262 § 12]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1379.SL.pdf?cite=1993%20c%20307%20§%2012[1993 c 307 § 12]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1995.SL.pdf?cite=1991%20c%20163%20§%204[1991 c 163 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c42.pdf?cite=1990%20c%2042%20§%20111[1990 c 42 § 111]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2016[1987 c 244 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c380.pdf?cite=1985%20c%20380%20§%202[1985 c 380 § 2]; ]

== 46.87.022 - Rental trailers—Fleet vehicle registration.
Owners of rental trailers and semitrailers over six thousand pounds gross vehicle weight used solely in pool fleets must fully register a portion of the pool fleet in this state. To determine the percentage of total fleet vehicles that must be registered in this state, divide the gross revenue received in the reporting period for the use of the rental vehicles arising from rental transactions occurring in this state by the total revenue received in the reporting period for the use of the rental vehicles arising from rental transactions in all jurisdictions in which the vehicles are operated. Apply the resulting percentage to the total number of vehicles that must be registered in this state. Vehicles registered in this state must be representative of the vehicles in the fleet according to age, size, and value.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%203[2015 c 228 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c250.pdf?cite=1990%20c%20250%20§%2074[1990 c 250 § 74]; ]

== 46.87.025 - Vehicles titled in owner's name.
All vehicles being added to a Washington fleet or those vehicles that make up a new Washington fleet must be titled in the name of the owner at time of registration.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%204[2015 c 228 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c250.pdf?cite=1990%20c%20250%20§%2075[1990 c 250 § 75]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2017[1987 c 244 § 17]; ]

== 46.87.030 - Part-year registration—Credit for unused fees.
. When application to register a vehicle in an existing fleet is made, the Washington apportioned fees must be reduced by one-twelfth for each full month that has elapsed from the time an application for registration is received in the department. The prorate percentage previously established for the fleet must be used in the computation of the apportionable fees and taxes due.

. If a vehicle is withdrawn from a fleet during the period it is registered under this chapter, the registrant of the fleet must notify the department on forms prescribed by the department. The department may require the registrant to surrender credentials issued to the vehicle. If a vehicle is completely removed from the service of the fleet, the unused portion of the license fee paid under RCW 46.17.355, reduced by one-twelfth for each month and fraction thereof elapsing between the first day of the month of the current registration year and the date the notice of removal is received in the department, must be credited to the registrant's fleet proportional registration account. Credit must be applied against the license fee liability for subsequent additions of vehicles to the fleet during the registration year or for additional license fees due under RCW 46.17.355 or be due upon audit under RCW 46.87.310. If any credit is less than fifteen dollars, the credit must not be entered. In lieu of credit, the registrant may transfer the unused portion of the license fee for the vehicle to the new owner, in which case it must remain with the vehicle for which it was originally paid. An amount may not be credited against fees other than those for the registration year from which the credit was obtained and an amount may not be refunded.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%205[2015 c 228 § 5]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201142[2010 c 161 § 1142]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1259.SL.pdf?cite=2005%20c%20194%20§%203[2005 c 194 § 3]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1459.SL.pdf?cite=1997%20c%20183%20§%203[1997 c 183 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1379.SL.pdf?cite=1993%20c%20307%20§%2013[1993 c 307 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2018[1987 c 244 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c18.pdf?cite=1986%20c%2018%20§%2023[1986 c 18 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c380.pdf?cite=1985%20c%20380%20§%203[1985 c 380 § 3]; ]

== 46.87.040 - Purchase of additional gross weight.
Additional gross weight may be purchased to the limits authorized under chapter 46.44 RCW. Registration must be for the remainder of the registration year, including the full registration month in which the vehicle is initially registered at the higher gross weight. The apportionable fee initially paid to the state of Washington, reduced by the number of full registration months the license was in effect, must be deducted from the total fee due. A credit or refund may not be given for a reduction of gross weight.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%206[2015 c 228 § 6]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2224-S.SL.pdf?cite=1994%20c%20262%20§%2013[1994 c 262 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2019[1987 c 244 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c380.pdf?cite=1985%20c%20380%20§%204[1985 c 380 § 4]; ]

== 46.87.050 - Deposit of fees.
Each day the department must forward to the state treasurer the fees collected under this chapter and, within ten days of the end of each registration quarter, a detailed report identifying the amount to be deposited to each account for which fees are required. Such fees must be deposited pursuant to RCW 46.68.035.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%207[2015 c 228 § 7]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1259.SL.pdf?cite=2005%20c%20194%20§%204[2005 c 194 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2020[1987 c 244 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c380.pdf?cite=1985%20c%20380%20§%205[1985 c 380 § 5]; ]

== 46.87.060 - Apportionment of fees.
The apportionment of fees to IRP member jurisdictions must be in accordance with the provisions of the IRP agreement.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%208[2015 c 228 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2021[1987 c 244 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c380.pdf?cite=1985%20c%20380%20§%206[1985 c 380 § 6]; ]

== 46.87.070 - Reciprocity for trailers, semitrailers, pole trailers.
Trailers, semitrailers, and pole trailers properly based in jurisdictions other than Washington and displaying currently registered license plates issued by the jurisdictions are granted vehicle registration reciprocity in this state. Unless registered under the provisions of the IRP as a pool fleet, such trailers, semitrailers, and pole trailers must be operated in combination with an apportioned power unit to qualify for reciprocity. If pole trailers are not required to be licensed separately by a member jurisdiction, they may be operated in this state without displaying a base license plate.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%209[2015 c 228 § 9]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1259.SL.pdf?cite=2005%20c%20194%20§%205[2005 c 194 § 5]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5535-S.SL.pdf?cite=1993%20c%20123%20§%201[1993 c 123 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1704-S.SL.pdf?cite=1991%20c%20339%20§%209[1991 c 339 § 9]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1995.SL.pdf?cite=1991%20c%20163%20§%205[1991 c 163 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c42.pdf?cite=1990%20c%2042%20§%20112[1990 c 42 § 112]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2022[1987 c 244 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c380.pdf?cite=1985%20c%20380%20§%207[1985 c 380 § 7]; ]

== 46.87.080 - Credentials—Design, procedures—Issuance, denial, suspension, revocation.
. Upon making satisfactory application and payment of fees and taxes for proportional registration under this chapter, the department must issue credentials. License plates must be displayed as required under RCW 46.16A.200(5). The license plates must be of a design determined by the department. The license plates must be treated with reflectorized material and clearly marked with the words "WASHINGTON" and "APPORTIONED," both words to appear in full and without abbreviation.

. The cab card is the certificate of registration for the vehicle. The cab card must contain the name and address of the registrant as maintained in the records of the department, the license plate number assigned to the vehicle, the vehicle identification number, and other information the department may require. The cab card must be signed by the registrant, or a designated person if the registrant is a business, and must always be carried in the vehicle.

. The apportioned license plates are not transferable. License plates must be legible and remain with the vehicle until the department requires them to be removed.

. Validation tab(s) of a design determined by the department must be affixed to the license plate(s) as prescribed by the department and indicate the month and year for which the vehicle is registered.

. A fleet vehicle properly registered is deemed to be fully registered in this state for any type of legal movement or operation. In instances in which a permit or grant of authority is required for interstate or intrastate operation, the vehicle must not be operated in interstate or intrastate commerce unless the owner is granted the appropriate operating authority and the vehicle is being operated in conformity with that permit or operating authority.

. The department may deny, suspend, or revoke the credentials authorized under subsection (1) of this section to any person: (a) Who formerly held any type of license, registration, credentials, or permit issued by the department pursuant to chapter 46.16A, 46.44, 46.85, 46.87, or 82.38 RCW that has been revoked for cause, which cause has not been removed; (b) who is a subterfuge for the real party in interest whose license, registration, credentials, or permit issued by the department pursuant to chapter 46.16A, 46.44, 46.85, 46.87, or 82.38 RCW and has been revoked for cause, which cause has not been removed; (c) who, as a person, individual licensee, or officer, partner, director, owner, or managing employee of a nonindividual licensee, has had a license, registration, or permit issued by the department pursuant to chapter 46.16A, 46.44, 46.85, 46.87, or 82.38 RCW that has been revoked for cause, which cause has not been removed; (d) who has an unsatisfied debt to the state assessed under either chapter 46.16A, 46.44, 46.85, 46.87, 82.38, or 82.44 RCW; or (e) who, as a person, individual licensee, officer, partner, director, owner, or managing employee of a nonindividual licensee, has been prohibited from operating as a motor carrier by the federal motor carrier safety administration or Washington state patrol and the cause for such prohibition has not been satisfied.

. Before such denial, suspension, or revocation under subsection (6) of this section, the department must grant the applicant, registrant, or owner an informal hearing and at least ten days written notice of the time and place of the hearing.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%2010[2015 c 228 § 10]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1883-S.SL.pdf?cite=2013%20c%20225%20§%20609[2013 c 225 § 609]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5061.SL.pdf?cite=2011%20c%20171%20§%2097[2011 c 171 § 97]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1259.SL.pdf?cite=2005%20c%20194%20§%206[2005 c 194 § 6]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2917-S.SL.pdf?cite=1998%20c%20115%20§%201[1998 c 115 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1379.SL.pdf?cite=1993%20c%20307%20§%2014[1993 c 307 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2023[1987 c 244 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c380.pdf?cite=1985%20c%20380%20§%208[1985 c 380 § 8]; ]

== 46.87.090 - Replacement of license plates, cab card, validation tabs—Fees.
. To replace license plates, a cab card, or validation tab(s), the registrant must apply to the department on forms furnished by the department.

.. A fee of ten dollars is charged for two license plates. The department must issue new license plates with validation tabs and a new cab card.

.. A fee of two dollars is charged for each cab card.

.. A fee of two dollars is charged for each validation year tab.

. All fees collected under this section must be deposited in the motor vehicle fund.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%2011[2015 c 228 § 11]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2224-S.SL.pdf?cite=1994%20c%20262%20§%2014[1994 c 262 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2024[1987 c 244 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c18.pdf?cite=1986%20c%2018%20§%2024[1986 c 18 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c380.pdf?cite=1985%20c%20380%20§%209[1985 c 380 § 9]; ]

== 46.87.120 - Report of actual distance accumulated on applications.
. An application for proportional registration of a fleet must state the actual distance accumulated by the fleet during the reporting period. If operations were not conducted by the fleet during the reporting period, the application must contain a department determined average per vehicle distance of the fleet in all jurisdictions.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%2012[2015 c 228 § 12]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1259.SL.pdf?cite=2005%20c%20194%20§%207[2005 c 194 § 7]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1459.SL.pdf?cite=1997%20c%20183%20§%204[1997 c 183 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c42.pdf?cite=1990%20c%2042%20§%20113[1990 c 42 § 113]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2025[1987 c 244 § 25]; ]

== 46.87.130 - Transaction fee.
The department must collect a vehicle transaction fee each time a vehicle is added to a Washington fleet, and each time the registration of a Washington fleet vehicle is renewed. The exact amount of the vehicle transaction fee must be fixed by rule, but must not exceed ten dollars. This fee must be deposited in the motor vehicle fund.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%2013[2015 c 228 § 13]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1259.SL.pdf?cite=2005%20c%20194%20§%208[2005 c 194 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2026[1987 c 244 § 26]; ]

== 46.87.140 - Application—Filing, contents—Fees and taxes—Assessments, due date.
. Any owner of one or more fleets of apportionable vehicles may, in lieu of registration of the vehicles under chapter 46.16A RCW, register the vehicles of each fleet by filing a proportional registration application with the department. The application must contain the following information and other information the department may require:

.. A description and identification of each vehicle in the fleet.

.. An original or renewal application must be accompanied by a distance schedule for each fleet.

.. The USDOT number issued to the registrant and the USDOT number of the motor carrier responsible for the safety of each vehicle, if different.

.. The taxpayer identification number of the registrant and the motor carrier responsible for the safety of each vehicle, if different.

. Each application must, at the time and in the manner required by the department, be supported by payment of a fee computed as follows:

.. Divide the in-jurisdiction distance for each jurisdiction by the total distance and carry the answer to the nearest thousandth of a percent (three places beyond the decimal, e.g. 10.543 percent). This factor is known as the prorate percentage.

.. Determine the apportionable fees and taxes required for each vehicle in the fleet based on the applicable fees and taxes under the laws of each jurisdiction.

Fees and taxes for vehicles of Washington fleets and foreign jurisdiction fleets operating in Washington are those prescribed under RCW 46.17.315, 46.17.355, and 82.38.075. If, during the registration period, the lessor of an apportioned vehicle changes and the vehicle remains in the fleet of the registrant, the department must only charge those fees prescribed for the issuance of new apportioned license plates, validation tabs, and cab card.

.. Multiply the total, apportionable fees or taxes for each vehicle by the prorate percentage applicable to each jurisdiction and round the results to the nearest cent.

.. Add the total fees and taxes determined in (c) of this subsection for each vehicle to the nonapportionable fees and taxes required under the laws of each jurisdiction. Nonapportionable fees required for vehicles of Washington fleets are the administrative fee required under RCW 82.38.075, the vehicle transaction fee pursuant to RCW 46.87.130, and the commercial vehicle safety inspection [enforcement] fee in RCW 46.17.315.

.. The amount due and payable is the sum of the fees and taxes calculated for each jurisdiction in which the fleet is registered.

. All assessments for taxes and fees are due and payable in United States funds on the date presented or mailed to the registrant at the address listed in the proportional registration records of the department. The registrant may petition for reassessment of the fees or taxes due within thirty days of the date of original service.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%2014[2015 c 228 § 14]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5061.SL.pdf?cite=2011%20c%20171%20§%2098[2011 c 171 § 98]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201143[2010 c 161 § 1143]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1259.SL.pdf?cite=2005%20c%20194%20§%209[2005 c 194 § 9]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5429.SL.pdf?cite=2003%20c%2085%20§%202[2003 c 85 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1459.SL.pdf?cite=1997%20c%20183%20§%205[1997 c 183 § 5]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1704-S.SL.pdf?cite=1991%20c%20339%20§%2010[1991 c 339 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c42.pdf?cite=1990%20c%2042%20§%20114[1990 c 42 § 114]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2027[1987 c 244 § 27]; ]

== 46.87.150 - Overpayment, underpayment—Refund, additional amount owed.
If a person pays a fee or tax that amounts to an overpayment of ten dollars or more, the person is entitled to a refund of the entire amount of the overpayment, regardless of whether or not a refund has been requested. This subsection does not preclude a person from applying for a refund of an overpayment if the overpayment is less than ten dollars. If the department or its agents fail to assess and collect the full amount of fees or taxes owed, which underpayment is ten dollars or more, the department must collect the additional amount owed.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%2015[2015 c 228 § 15]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2660.SL.pdf?cite=1996%20c%2091%20§%201[1996 c 91 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2028[1987 c 244 § 28]; ]

== 46.87.190 - Suspension or cancellation of benefits.
The department may suspend or cancel the exemptions, benefits, or privileges granted under chapter 46.85 RCW or this chapter to any person who violates any of the conditions or terms of the IRP or who violates the laws or rules of this state relating to the operation or registration of vehicles.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%2016[2015 c 228 § 16]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1259.SL.pdf?cite=2005%20c%20194%20§%2010[2005 c 194 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2032[1987 c 244 § 32]; ]

== 46.87.200 - Refusal of registration—Federal heavy vehicle use tax.
The department must refuse registration of a vehicle if the applicant has failed to furnish proof, acceptable to the department, that the federal heavy vehicle use tax imposed under 26 U.S.C. Sec. 4481 has been suspended or paid.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%2017[2015 c 228 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2033[1987 c 244 § 33]; ]

== 46.87.220 - Gross weight computation.
The gross weight of a vehicle is the scale weight of the vehicle, plus the scale weight of any trailer, semitrailer, converter gear, or pole trailer to be towed by it, to which must be added the maximum weight of the load to be carried on it or towed by it as declared by the licensee as long as it does not exceed the weight limitations prescribed under chapter 46.44 RCW.

The gross weight in the case of a bus, auto stage, or passenger-carrying for hire vehicle with a seating capacity over six, is the scale weight of the bus, auto stage, or passenger-carrying for hire vehicle plus the seating capacity, including the operator's seat, computed at one hundred fifty pounds per seat.

If the resultant gross weight, according to this section, is not listed in RCW 46.17.355, it must be increased to the next higher gross weight listed pursuant to chapter 46.44 RCW.

A vehicle or combination of vehicles found to be loaded beyond the licensed gross weight of the vehicle or combination of vehicles must be cited and handled under RCW 46.16A.540 and 46.16A.545.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%2018[2015 c 228 § 18]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201144[2010 c 161 § 1144]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2035[1987 c 244 § 35]; ]

== 46.87.230 - Responsibility for unlawful acts or omissions.
Whenever an act or omission is declared to be unlawful under chapter 46.12, 46.16A, or 46.44 RCW or this chapter, and the operator of the vehicle is not the owner or lessee of the vehicle but is operating or moving the vehicle with the express or implied permission of the owner or lessee, the operator and the owner or lessee are both subject to this chapter, with the primary responsibility to be that of the owner or lessee.

If the person operating the vehicle at the time of the unlawful act or omission is not the owner or the lessee of the vehicle, that person is fully authorized to accept the citation or notice of infraction and execute the promise to appear on behalf of the owner or lessee.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%2019[2015 c 228 § 19]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5061.SL.pdf?cite=2011%20c%20171%20§%2099[2011 c 171 § 99]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2036[1987 c 244 § 36]; ]

== 46.87.240 - Relationship of department with other jurisdictions.
To administer the provisions of the IRP, the department may act in a quasi-agency relationship with other jurisdictions. The department may collect and forward applicable registration fees and taxes to other jurisdictions on behalf of the applicant or another jurisdiction and may take other action that facilitates the administration of the IRP.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%2020[2015 c 228 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2037[1987 c 244 § 37]; ]

== 46.87.250 - Authority of chapter.
This chapter constitutes complete authority for the registration of vehicles upon a proportional registration basis without reference to or application of any other statutes of this state except as expressly provided in this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%2021[2015 c 228 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2038[1987 c 244 § 38]; ]

== 46.87.260 - Alteration or forgery of credential—Penalty.
Any person who alters, forges, or causes to be altered or forged any credential, or holds or uses any credential knowing the credential to have been altered or forged, is guilty of a class B felony punishable according to chapter 9A.20 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%2022[2015 c 228 § 22]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20255[2003 c 53 § 255]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2039[1987 c 244 § 39]; ]

== 46.87.280 - Effect of other registration.
This chapter does not require any vehicle to be proportionally registered if it is otherwise properly registered for operation on the highways of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%2023[2015 c 228 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2041[1987 c 244 § 41]; ]

== 46.87.290 - Refusal, cancellation of credentials—Procedures, penalties.
. If the department determines at any time that an applicant for proportional registration of a vehicle or vehicles is not entitled to credentials, the department may refuse to issue credentials for the vehicle or vehicles and, after notice, cancel any existing credentials. The department must send the notice of cancellation by first-class mail, addressed to the owner of the vehicle or vehicles at the owner's address as it appears in the proportional registration records of the department. It is unlawful for any person to drive or operate the vehicle(s) until proper credentials have been issued.

. Any person driving or operating the vehicle(s) after the refusal of the department to issue credentials or the suspension, revocation, or cancellation of the credentials is guilty of a gross misdemeanor.

. A vehicle that has been driven or operated in violation of this section may be impounded by the Washington state patrol, county sheriff, or city police in a manner directed for such cases by the chief of the Washington state patrol until proper credentials have been issued.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%2024[2015 c 228 § 24]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20256[2003 c 53 § 256]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1459.SL.pdf?cite=1997%20c%20183%20§%206[1997 c 183 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2042[1987 c 244 § 42]; ]

== 46.87.294 - Refusal under federal prohibition, placement of out-of-service order.
The department must refuse to register a vehicle if the registrant or motor carrier responsible for the safety of the vehicle has been prohibited from operating by the federal motor carrier safety administration. The department may not register a vehicle if the Washington state patrol has placed an out-of-service order on the vehicle's department of transportation number, as defined in RCW 46.16A.010.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%2025[2015 c 228 § 25]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5061.SL.pdf?cite=2011%20c%20171%20§%20100[2011 c 171 § 100]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1304-S.SL.pdf?cite=2007%20c%20419%20§%2015[2007 c 419 § 15]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5429.SL.pdf?cite=2003%20c%2085%20§%203[2003 c 85 § 3]; ]

== 46.87.296 - Suspension, revocation under federal prohibition—Placement of out-of-service order.
The department must suspend or revoke the credentials of a vehicle if the registrant or motor carrier responsible for the safety of the vehicle has been prohibited from operating by the federal motor carrier safety administration. The department may not register a vehicle if the Washington state patrol has placed an out-of-service order on the vehicle's department of transportation number, as defined in RCW 46.16A.010.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%2026[2015 c 228 § 26]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5061.SL.pdf?cite=2011%20c%20171%20§%20101[2011 c 171 § 101]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1304-S.SL.pdf?cite=2007%20c%20419%20§%2016[2007 c 419 § 16]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5429.SL.pdf?cite=2003%20c%2085%20§%204[2003 c 85 § 4]; ]

== 46.87.300 - Appeal of suspension, revocation, cancellation, refusal.
The suspension, revocation, cancellation, or refusal by the director, or the director's designee, of the credentials issued under this chapter is conclusive unless the person whose credentials are suspended, revoked, canceled, or refused appeals to the superior court of Thurston county, or at the person's option if a resident of Washington, to the superior court of his or her county of residence, for the purpose of having the suspension, revocation, cancellation, or refusal of the credentials set aside. Notice of appeal must be filed within ten calendar days after service of the notice of suspension, revocation, cancellation, or refusal. Upon the filing of the appeal, the court must issue an order to the director to show cause why the credentials should not be granted or reinstated. The director must respond to the order within ten days after the date of service of the order upon the director. Service must be in the manner prescribed for service of summons and complaint in other civil actions. Upon the hearing on the order to show cause, the court must hear evidence concerning matters related to the suspension, revocation, cancellation, or refusal of the credentials and enter judgment either affirming or setting aside the suspension, revocation, cancellation, or refusal.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%2027[2015 c 228 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2043[1987 c 244 § 43]; ]

== 46.87.310 - Application records—Preservation, audit—Additional assessments, penalties, refunds.
An owner must preserve the records on which the owner's application for apportioned registration is based for a period of three years following the close of the registration year. The owner must make records available to the department for audit as to the accuracy and adequacy of records, computations, and payments at a location designated by the department. The department must assess and collect any unpaid fees and taxes due affected jurisdictions and provide credits for any overpayments of apportionable fees and taxes to the jurisdictions affected. If the records produced by the owner for the audit fail to meet the criteria for adequate records, or are not produced within thirty calendar days after a written request by the department, the department must impose on the owner an assessment in the amount of twenty percent of the total apportionable fees paid or found due because of appropriate adjustment for the registration of the fleet in the registration year to which records pertain. In the instance of a second offense, the department must impose upon the owner an assessment in the amount of fifty percent of the total apportionable fees paid or found due because of appropriate adjustment for the registration of the fleet in the registration year to which records pertain. In the instance of a third or any subsequent offense, the department must impose upon the owner an assessment in the amount of one hundred percent of the total apportionable fees paid or found due because of appropriate adjustment for the registration of the fleet in the registration year to which records pertain. The department must distribute the amount of assessments it collects under this section on a pro rata basis to the other jurisdictions in which the fleet was registered or required to be registered.

If the owner fails to maintain complete records as required under this section, the department may attempt to reconstruct or reestablish such records.

The department may conduct joint audits of any owner with other jurisdictions. An assessment for deficiency or claim for credit may not be made for any period for which records are no longer required. Any fees, taxes, penalties, or interest due and owing the state upon audit bear interest at the rate of one percent per month, or fraction thereof, from the first day of the calendar month after the amount should have been paid until the date of payment. If the audit discloses a deliberate and willful intent to evade the requirements of payment under RCW 46.87.140, a penalty of ten percent of the amount owed, in addition to any other assessments authorized under this chapter, must be assessed.

If the audit discloses that an overpayment in excess of ten dollars has been made, the department must refund the overpayment to the owner. Overpayments must bear interest at the rate of eight percent per annum from the date on which the overpayment was incurred until the date of payment.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%2028[2015 c 228 § 28]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2660.SL.pdf?cite=1996%20c%2091%20§%202[1996 c 91 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1379.SL.pdf?cite=1993%20c%20307%20§%2015[1993 c 307 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2044[1987 c 244 § 44]; ]

== 46.87.320 - Departmental audits, investigations—Subpoenas.
The department may initiate and conduct audits and investigations to establish the existence of any alleged violations of or noncompliance with this chapter or any rules adopted under it.

For the purpose of any audit, investigation, or proceeding under this chapter, the director or any designee of the director may administer oaths and affirmations, subpoena witnesses, compel their attendance, take evidence, and require the production of any books, paper, correspondence, memoranda, agreements, or other documents or records that the department deems relevant or material to the inquiry.

In case of contumacy or refusal to obey a subpoena issued to any person, any court of competent jurisdiction may issue an order requiring that person to appear before the director or the officer designated by the director to produce testimony or other evidence touching the matter under audit, investigation, or in question. Failure to obey an order of the court may be punishable by contempt.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%2029[2015 c 228 § 29]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2045[1987 c 244 § 45]; ]

== 46.87.330 - Assessments—When due, penalties—Reassessment—Petition, notice, service—Injunctions, writs of mandate restricted.
An owner of vehicles against whom an assessment is made under RCW 46.87.310 may petition for reassessment within thirty days after service of notice of the assessment upon the owner. If the petition is not filed within the thirty-day period, the amount of the assessment becomes final.

If a petition for reassessment is filed within the thirty-day period, the department must reconsider the assessment and, if the petitioner has requested in the petition, grant the petitioner an oral hearing and give the petitioner ten days notice of the time and place of the hearing. The department may continue the hearing from time to time. The decision of the department upon a petition for reassessment becomes final thirty days after service upon the petitioner of notice of the decision.

Every assessment made under RCW 46.87.310 becomes due and payable at the time it is served on the owner. If the assessment is not paid in full when it becomes final, the department must add a penalty of ten percent of the amount of the assessment.

Any notice of assessment, reassessment, oral hearing, or decision required under this section must be served personally or by mail. If served by mail, service is deemed to have been accomplished on the date the notice was deposited in the United States mail and mailed to the owner's address as it appears in the proportional registration records of the department.

An injunction or writ of mandate or other legal or equitable process may not be issued in any suit, action, or proceeding in any court against any officer of the state to prevent or enjoin the collection under this chapter of any fee or tax or any amount of fee or tax required to be collected, except as specifically provided for in chapter 34.05 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%2030[2015 c 228 § 30]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2660.SL.pdf?cite=1996%20c%2091%20§%203[1996 c 91 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2046[1987 c 244 § 46]; ]

== 46.87.335 - Mitigation of assessments.
Except in the case of violations of filing a false or fraudulent application, if the department deems mitigation of penalties, fees, and interest to be reasonable, it may mitigate such assessments giving consideration to the degree and extent of the lack of records and reporting errors. The department may ascertain the facts regarding recordkeeping and payment penalties in lieu of more elaborate proceedings under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%2031[2015 c 228 § 31]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2224-S.SL.pdf?cite=1994%20c%20262%20§%2015[1994 c 262 § 15]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1704-S.SL.pdf?cite=1991%20c%20339%20§%205[1991 c 339 § 5]; ]

== 46.87.340 - Assessments—Lien for nonpayment.
. If a person liable for the payment of fees and taxes fails to pay the amount, including any interest and penalty, together with costs incurred, there must be a lien in favor of the state upon all franchises, property, and rights to property, whether real or personal, belonging to or acquired, whether the property is employed by such person for personal or business use or is in the control of a trustee, receiver, or assignee. The lien is effective from the date fees and taxes were due and payable until the amount is satisfied. The lien has priority over any lien or encumbrance except liens of other fees and taxes having priority by law.

. The department must file with any county auditor or other agent a statement of claim and lien specifying the amount of delinquent fees, taxes, penalties, and interest owed.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%2032[2015 c 228 § 32]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1379.SL.pdf?cite=1993%20c%20307%20§%2016[1993 c 307 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2047[1987 c 244 § 47]; ]

== 46.87.350 - Delinquent obligations—Notice—Restriction on credits or property—Default judgments—Lien.
If a person is delinquent in the payment of any obligation, the department may give notice of the amount of the delinquency, in person or by mail, to persons having possession or control of credits or personal and real property belonging to the person, or owing any debts to the person. Any person notified may not transfer or dispose of credits, personal and real property, or debts without the consent of the department. A person notified must, within twenty days after receipt of the notice, advise the department of any credits, personal and real property, or debts in his or her possession, under his or her control or owing by him or her, and must immediately deliver the credits, personal and real property, or debts to the department.

If a person fails to timely answer the notice, a court may render judgment by default against the person.

The notice and order to withhold and deliver constitutes a continuing lien on property of the person. The department must include in the notice to withhold and deliver "continuing lien." The effective date of a notice to withhold and deliver is the date of service.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%2033[2015 c 228 § 33]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2224-S.SL.pdf?cite=1994%20c%20262%20§%2016[1994 c 262 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2048[1987 c 244 § 48]; ]

== 46.87.360 - Delinquent obligations—Collection by department—Seizure of property, notice, sale.
If a person is delinquent in the payment of any obligation, and the delinquency continues after notice and demand for payment, the department must collect the amount due. The department must seize any property subject to the lien of the fees, taxes, penalties, and interest and sell it at public auction. Notice of the intended sale and its time and place must be given to the person and to all persons with an interest in the property. The notice must be published at least ten days before the date set for the sale in a newspaper of general circulation published in the county in which the property will be sold. If there is no newspaper of general circulation in the county, the notice must be posted in three public places in the county for a period of ten days. The notice must contain a description of the property, a statement of the amount due, the name of the person, and a statement that unless the amount due is paid on or before the time in the notice the property will be sold.

The department must sell the property and deliver to the purchaser a bill of sale or deed. If the moneys received exceed the amount due from the person, the excess must be returned to the person with a receipt. If any person having an interest in or lien upon the property has filed notice with the department before the sale, the department must withhold payment of any excess to the person pending determination of the rights of the respective parties by a court of competent jurisdiction. If the receipt of the person is not available, the department must deposit the excess with the state treasurer as trustee for the person or his or her heirs, successors, or assigns.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%2034[2015 c 228 § 34]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%209101[2010 c 8 § 9101]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2049[1987 c 244 § 49]; ]

== 46.87.370 - Warrant for final assessments—Lien on property.
When an assessment becomes final, the department may file with the clerk of any county within the state a warrant in the amount of fees, taxes, penalties, interest, and a filing fee under RCW 36.18.012(10). The warrant constitutes a lien upon the title to, and interest in, all real and personal property of the person against whom the warrant is issued. The warrant is sufficient to support the issuance of writs of execution and writs of garnishment in favor of the state.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%2035[2015 c 228 § 35]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1793-S.SL.pdf?cite=2001%20c%20146%20§%206[2001 c 146 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2050[1987 c 244 § 50]; ]

== 46.87.390 - Remedies cumulative.
The remedies of the state in this chapter are cumulative, and no action taken by the department may be construed to be an election on the part of the state or any of its officers to pursue any remedy under this chapter to the exclusion of any other remedy provided for in this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2052[1987 c 244 § 52]; ]

== 46.87.400 - Civil immunity.
. The director, the state of Washington, and its political subdivisions are immune from civil liability arising from the issuance of a vehicle license to a nonroadworthy vehicle.

. No suit or action may be commenced or prosecuted against the director or the state of Washington by reason of any act done or omitted to be done in the administration of the duties and responsibilities imposed upon the director under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2053[1987 c 244 § 53]; ]

== 46.87.410 - Bankruptcy proceedings—Notice.
A licensee who files a petition in bankruptcy, or against whom a petition for bankruptcy is filed, must notify the department within ten days of the filing, including the name and location of the court in which [the] petition is filed.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5297.SL.pdf?cite=2015%20c%20228%20§%2036[2015 c 228 § 36]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1459.SL.pdf?cite=1997%20c%20183%20§%201[1997 c 183 § 1]; ]

== 46.87.910 - Short title.
This chapter may be known and cited as "Proportional Registration."

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2054[1987 c 244 § 54]; ]

