= 46.85 - Reciprocal or proportional registration of vehicles.
:toc:

== 46.85.010 - Declaration of policy.
It is the policy of this state to promote and encourage the fullest possible use of its highway system by authorizing the making and execution of vehicle reciprocal or proportional registration agreements, arrangements and declarations with other states, provinces, territories, and countries with respect to vehicles registered in this and such other states, provinces, territories, and countries thus contributing to the economic and social development and growth of this state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%208[1987 c 244 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c106.pdf?cite=1963%20c%20106%20§%201[1963 c 106 § 1]; ]

== 46.85.020 - Definitions.
The definitions set forth in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Jurisdiction" means and includes a state, territory, or possession of the United States, the District of Columbia, the Commonwealth of Puerto Rico, a foreign country, and a state or province of a foreign country.

. "Owner" means a person, business firm, or corporation who holds the legal title to a vehicle, or in the event a vehicle is the subject of an agreement for the conditional sale thereof with the right of purchase upon performance of the conditions stated in the agreement and with an immediate right of possession vested in the conditional vendee, or in the event a vehicle is subject to a lease, contract, or other legal arrangement vesting right of possession or control, for security or otherwise, or in the event a mortgagor of a vehicle is entitled to possession, then the owner shall be deemed to be such person in whom is vested right of possession or control.

. "Properly registered," as applied to place of registration, means:

.. The jurisdiction where the person registering the vehicle has his or her legal residence; or

.. In the case of a commercial vehicle, the jurisdiction in which it is registered if the commercial enterprise in which such vehicle is used has a place of business therein, and, if the vehicle is most frequently dispatched, garaged, serviced, maintained, operated, or otherwise controlled in or from such place of business, and, the vehicle has been assigned to such place of business; or

.. In the case of a commercial vehicle, the jurisdiction where, because of an agreement or arrangement between two or more jurisdictions, or pursuant to a declaration, the vehicle has been registered as required by said jurisdiction.

In case of doubt or dispute as to the proper place of registration of a vehicle, the department shall make the final determination, but in making such determination, may confer with departments of the other jurisdictions affected.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%209100[2010 c 8 § 9100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%209[1987 c 244 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c173.pdf?cite=1985%20c%20173%20§%202[1985 c 173 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c227.pdf?cite=1982%20c%20227%20§%2018[1982 c 227 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c222.pdf?cite=1981%20c%20222%20§%201[1981 c 222 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c106.pdf?cite=1963%20c%20106%20§%202[1963 c 106 § 2]; ]

== 46.85.030 - Departmental entry into multistate proportional registration agreement, International Registration Plan.
The department of licensing shall have the authority to execute agreements, arrangements, or declarations to carry out the provisions of chapter 46.87 RCW and this chapter.

If the department enters into a multistate proportional registration agreement which requires this state to perform acts in a quasi agency relationship, the department may collect and forward applicable registration fees and applications to other jurisdictions on behalf of the applicant or on behalf of another jurisdiction and may take such other action as will facilitate the administration of such agreement.

If the department enters into a multistate proportional registration agreement which prescribes procedures applicable to vehicles not specifically described in chapter 46.87 RCW, such as but not limited to "owner-operator" or "rental" vehicles, it shall promulgate rules taking exception to or accomplishing the procedures prescribed in such agreement.

It is the purpose and intent of this subsection to facilitate the membership in the International Registration Plan and at the same time allow the department to continue to participate in such agreements and compacts as may be necessary and desirable in addition to the International Registration Plan.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2010[1987 c 244 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c227.pdf?cite=1982%20c%20227%20§%2019[1982 c 227 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c222.pdf?cite=1981%20c%20222%20§%202[1981 c 222 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c92.pdf?cite=1977%20ex.s.%20c%2092%20§%201[1977 ex.s. c 92 § 1]; 1975-'76 2nd ex.s. c 34 § 137; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c32.pdf?cite=1967%20c%2032%20§%20113[1967 c 32 § 113]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c106.pdf?cite=1963%20c%20106%20§%203[1963 c 106 § 3]; ]

== 46.85.040 - Authority for reciprocity agreements—Provisions—Reciprocity standards.
The department may enter into an agreement or arrangement with the duly authorized representatives of another jurisdiction, granting to vehicles or to owners of vehicles which are properly registered or licensed in such jurisdiction and for which evidence of compliance is supplied, benefits, privileges, and exemptions from the payment, wholly or partially, of any taxes, fees, or other charges imposed upon such vehicles or owners with respect to the operation or ownership of such vehicles under the laws of this state. Such an agreement or arrangement shall provide that vehicles properly registered or licensed in this state when operated upon highways of such other jurisdiction shall receive exemptions, benefits, and privileges of a similar kind or to a similar degree as are extended to vehicles properly registered or licensed in such jurisdiction when operated in this state. Each such agreement or arrangement shall, in the judgment of the department, be in the best interest of this state and the citizens thereof and shall be fair and equitable to this state and the citizens thereof, and all of the same shall be determined on the basis and recognition of the benefits which accrue to the economy of this state from the uninterrupted flow of commerce.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c173.pdf?cite=1985%20c%20173%20§%203[1985 c 173 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c227.pdf?cite=1982%20c%20227%20§%2020[1982 c 227 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c106.pdf?cite=1963%20c%20106%20§%204[1963 c 106 § 4]; ]

== 46.85.050 - Base state registration reciprocity.
An agreement or arrangement entered into, or a declaration issued under the authority of chapter 46.87 RCW or this chapter may contain provisions authorizing the registration or licensing in another jurisdiction of vehicles located in or operated from a base in such other jurisdiction which vehicles otherwise would be required to be registered or licensed in this state; and in such event the exemptions, benefits, and privileges extended by such agreement, arrangement, or declaration shall apply to such vehicles, when properly licensed or registered in such base jurisdiction.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2011[1987 c 244 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c106.pdf?cite=1963%20c%20106%20§%205[1963 c 106 § 5]; ]

== 46.85.060 - Declarations of extent of reciprocity, when—Exemptions, benefits, and privileges—Rules.
In the absence of an agreement or arrangement with another jurisdiction, the department may examine the laws and requirements of such jurisdiction and declare the extent and nature of exemptions, benefits and privileges to be extended to vehicles properly registered or licensed in such other jurisdiction, or to the owners of such vehicles, which shall, in the judgment of the department, be in the best interest of this state and the citizens thereof and which shall be fair and equitable to this state and the citizens thereof, and all of the same shall be determined on the basis and recognition of the benefits which accrue to the economy of this state from the uninterrupted flow of commerce. Declarations of exemptions, benefits, and privileges issued by the department shall include at least the following exemptions:

. Nonresident persons not employed in this state may operate a vehicle in this state that is currently licensed in another jurisdiction for a period not to exceed six months in any continuous twelve-month period.

. Nonresident persons employed in this state may operate vehicles not to exceed twelve thousand pounds registered gross vehicle weight that are currently licensed in another jurisdiction if no permanent, temporary, or part-time residence is maintained in this state for a period greater than six months in any continuous twelve-month period.

. A vehicle or a combination of vehicles, not exceeding a registered gross or combined gross vehicle weight of twelve thousand pounds, which is properly base licensed in another jurisdiction and registered to a bona fide business in that jurisdiction is not required to obtain Washington vehicle license registration except when such vehicle is owned or operated by a business or branch office of a business located in Washington.

. The department of licensing, after consultation with the department of revenue, shall adopt such rules as it deems necessary for the administration of these exemptions, benefits, and privileges.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c142.pdf?cite=1987%20c%20142%20§%204[1987 c 142 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c353.pdf?cite=1985%20c%20353%20§%203[1985 c 353 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c227.pdf?cite=1982%20c%20227%20§%2021[1982 c 227 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c106.pdf?cite=1963%20c%20106%20§%206[1963 c 106 § 6]; ]

== 46.85.070 - Extension of reciprocal privileges to lessees authorized.
An agreement, or arrangement entered into, or a declaration issued under the authority of this chapter, may contain provisions under which a leased vehicle properly registered by the lessor thereof may be entitled, subject to terms and conditions stated therein, to the exemptions, benefits and privileges extended by such agreement, arrangement or declaration.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c106.pdf?cite=1963%20c%20106%20§%207[1963 c 106 § 7]; ]

== 46.85.080 - Automatic reciprocity, when.
On and after July 1, 1963, if no agreement, arrangement or declaration is in effect with respect to another jurisdiction as authorized by this chapter, any vehicle properly registered or licensed in such other jurisdiction and for which evidence of compliance is supplied shall receive, when operated in this state, the same exemptions, benefits and privileges granted by such other jurisdiction to vehicles properly registered in this state. Reciprocity extended under this section shall apply to commercial vehicles only when engaged exclusively in interstate commerce.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c106.pdf?cite=1963%20c%20106%20§%208[1963 c 106 § 8]; ]

== 46.85.090 - Suspension of reciprocity benefits.
Agreements, arrangements or declarations made under the authority of this chapter may include provisions authorizing the department to suspend or cancel the exemptions, benefits, or privileges granted thereunder to an owner who violates any of the conditions or terms of such agreements, arrangements, or declarations or who violates the laws of this state relating to motor vehicles or rules and regulations lawfully promulgated thereunder.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2012[1987 c 244 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c106.pdf?cite=1963%20c%20106%20§%209[1963 c 106 § 9]; ]

== 46.85.100 - Agreements to be written, filed, and available for distribution.
All agreements, arrangements, or declarations or amendments thereto shall be in writing and shall be filed with the department. Upon becoming effective, they shall supersede the provisions of RCW 46.16A.160, chapter 46.87 RCW, or this chapter to the extent that they are inconsistent therewith. The department shall provide copies for public distribution upon request.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5061.SL.pdf?cite=2011%20c%20171%20§%2094[2011 c 171 § 94]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c244.pdf?cite=1987%20c%20244%20§%2013[1987 c 244 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c227.pdf?cite=1982%20c%20227%20§%2022[1982 c 227 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c32.pdf?cite=1967%20c%2032%20§%20114[1967 c 32 § 114]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c106.pdf?cite=1963%20c%20106%20§%2010[1963 c 106 § 10]; ]

== 46.85.110 - Reciprocity agreements in effect at time of act.
All reciprocity and proportional registration agreements, arrangements and declarations relating to vehicles in force and effect at the time this chapter becomes effective shall continue in force and effect at the time this chapter becomes effective and until specifically amended or revoked as provided by law or by such agreements or arrangements.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c106.pdf?cite=1963%20c%20106%20§%2011[1963 c 106 § 11]; ]

== 46.85.900 - Chapter part of and supplemental to motor vehicle registration law.
This chapter shall be, and construed as, a part of and supplemental to the motor vehicle registration law of this state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c106.pdf?cite=1963%20c%20106%20§%2030[1963 c 106 § 30]; ]

== 46.85.910 - Constitutionality.
If any phrase, clause, subsection or section of this chapter shall be declared unconstitutional or invalid by any court of competent jurisdiction, it shall be conclusively presumed that the legislature would have enacted this chapter without the phrase, clause, subsection or section so held unconstitutional or invalid and the remainder of the chapter shall not be affected as a result of said part being held unconstitutional or invalid.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c106.pdf?cite=1963%20c%20106%20§%2031[1963 c 106 § 31]; ]

== 46.85.920 - Repeal and saving.
The following acts or parts of acts and RCW sections are hereby repealed:

. Sections 46.84.010, 46.84.030, 46.84.040, 46.84.050, 46.84.060, 46.84.070, 46.84.080, 46.84.090 and 46.84.100, chapter 12, Laws of 1961 and RCW 46.84.010, 46.84.030, 46.84.040, 46.84.050, 46.84.060, 46.84.070, 46.84.080, 46.84.090 and 46.84.100;

. Section 46.84.020, chapter 12, Laws of 1961 as amended by section 37, chapter 21, Laws of 1961 extraordinary session and RCW 46.84.020;

. Sections 1, 2, 3, and 4, chapter 266, Laws of 1961 and RCW 46.84.110, 46.84.120, 46.84.130 and 46.84.140; and

. Sections 38, 39, and 40, chapter 21, Laws of 1961 extraordinary session and RCW 46.84.150, 46.84.160 and 46.84.170.

Such repeals shall not be construed as affecting any existing right acquired under the statutes repealed, nor as affecting any proceeding instituted thereunder, nor any rule, regulation or order promulgated thereunder, nor any administrative action taken thereunder, nor the term of office or appointment or employment of any person appointed or employed thereunder.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c106.pdf?cite=1963%20c%20106%20§%2032[1963 c 106 § 32]; ]

== 46.85.930 - Effective date—1963 c 106.
This chapter shall take effect and be in force on and after July 1, 1963.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c106.pdf?cite=1963%20c%20106%20§%2033[1963 c 106 § 33]; ]

== 46.85.940 - Section captions not a part of the law.
Section captions as used in this chapter shall not constitute any part of the law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c106.pdf?cite=1963%20c%20106%20§%2034[1963 c 106 § 34]; ]

