= 46.98 - Construction.
:toc:

== 46.98.010 - Continuation of existing law.
The provisions of this title insofar as they are substantially the same as statutory provisions repealed by this chapter, and relating to the same subject matter, shall be construed as restatements and continuations, and not as new enactments.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.98.010[1961 c 12 § 46.98.010]; ]

== 46.98.020 - Provisions to be construed in pari materia.
The provisions of this title shall be construed in pari materia even though as a matter of prior legislative history they were not originally enacted in the same statute. The provisions of this title shall also be construed in pari materia with the provisions of Title 47 RCW, and with other laws relating to highways, roads, streets, bridges, ferries and vehicles. This section shall not operate retroactively.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.98.020[1961 c 12 § 46.98.020]; ]

== 46.98.030 - Title, chapter, section headings not part of law.
Title headings, chapter headings, and section or subsection headings, as used in this title do not constitute any part of the law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.98.030[1961 c 12 § 46.98.030]; ]

== 46.98.040 - Invalidity of part of title not to affect remainder.
If any provision of this title or its application to any person or circumstance is held invalid, the remainder of the title, or the application of the provision to other persons or circumstances is not affected.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.98.040[1961 c 12 § 46.98.040]; ]

== 46.98.050 - Repeals and saving—1961 c 12.
See 1961 c 12 s 46.98.050.

[ ]

== 46.98.060 - Emergency—1961 c 12.
This act is necessary for the immediate preservation of the public peace, health and safety, the support of the state government and its existing institutions and shall take effect immediately.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c12.pdf?cite=1961%20c%2012%20§%2046.98.060[1961 c 12 § 46.98.060]; ]

