= 54.36 - Liability to other taxing districts.
:toc:

== 54.36.010 - Definitions.
As used in this chapter:

"Public utility district" means public utility district or districts or a joint operating agency or agencies.

"Construction project" means the construction of generating facilities by a public utility district. It includes the relocation of highways and railroads, by whomever done, to the extent that it is occasioned by the overflowing of their former locations, or by destruction or burying incident to the construction.

"Base-year enrollment" means the number of pupils enrolled in a school district on the first of May next preceding the date construction was commenced.

"Subsequent-year enrollment" means the number of pupils enrolled in a school district on any first of May after construction was commenced.

"Construction pupils" means pupils who have a parent who is a full time employee on the construction project and who moved into the school district subsequent to the first day of May next preceding the day the construction was commenced.

"Nonconstruction pupils" means other pupils.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c10.pdf?cite=1975%201st%20ex.s.%20c%2010%20§%201[1975 1st ex.s. c 10 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c154.pdf?cite=1973%201st%20ex.s.%20c%20154%20§%2099[1973 1st ex.s. c 154 § 99]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c137.pdf?cite=1957%20c%20137%20§%201[1957 c 137 § 1]; ]

== 54.36.020 - Increased financial burden on school district—Determination of number of construction pupils.
When as the result of a public utility district construction project a school district considers it is suffering an increased financial burden in any year during the construction project, it shall determine the number of construction pupils enrolled in the school district on the first of May of such year.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c137.pdf?cite=1957%20c%20137%20§%202[1957 c 137 § 2]; ]

== 54.36.030 - Compensation of school district for construction pupils—Computation.
If the subsequent-year enrollment exceeds one hundred and three percent of the base-year enrollment, the public utility district shall compensate the school district for a number of construction pupils computed as follows:

. If the subsequent-year enrollment of nonconstruction pupils is less than the base-year enrollment, compensation shall be paid for the total number of all pupils minus one hundred and three percent of the base-year enrollment.

. If the subsequent-year enrollment of nonconstruction pupils is not less than the base-year enrollment, compensation shall be paid for the total number of construction pupils minus three percent of the base-year enrollment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c137.pdf?cite=1957%20c%20137%20§%203[1957 c 137 § 3]; ]

== 54.36.040 - Compensation of school district for construction pupils—Amount to be paid.
The compensation to be paid per construction pupils as computed in RCW 54.36.030 shall be one-third of the average per-pupil cost of the local school district, for the school year then current.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c137.pdf?cite=1957%20c%20137%20§%204[1957 c 137 § 4]; ]

== 54.36.050 - Compensation of school district for construction pupils—How paid when more than one project in the same school district.
If more than one public utility district or joint operating agency is carrying on a construction project in the same school district, the number of construction pupils for whom the school district is to receive compensation shall be computed as if the projects were constructed by a single agency. The public utility districts or joint operating agencies involved shall divide the cost of such compensation between themselves in proportion to the number of construction pupils occasioned by the operations of each.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c137.pdf?cite=1957%20c%20137%20§%205[1957 c 137 § 5]; ]

== 54.36.060 - Power to make voluntary payments to school district for capital construction.
Public utility districts are hereby authorized to make voluntary payments to a school district for capital construction if their construction projects cause an increased financial burden for such purpose on the school district.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c137.pdf?cite=1957%20c%20137%20§%206[1957 c 137 § 6]; ]

== 54.36.070 - Increased financial burden on county or other taxing district—Power to make payments.
Public utilities are hereby authorized to make payments to a county or other taxing district in existence before the commencement of construction on the construction project which suffers an increased financial burden because of their construction projects, but such amount shall not be more than the amount by which the property taxes levied against the contractors engaged in the work on the construction project failed to meet said increased financial burden.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c137.pdf?cite=1957%20c%20137%20§%207[1957 c 137 § 7]; ]

== 54.36.080 - Funds received by school district—Equalization apportionment.
The funds paid by a public utility district to a school district under the provisions of this chapter shall not be considered a school district receipt by the superintendent of public instruction in determining equalization apportionments under *RCW 28.41.080.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c137.pdf?cite=1957%20c%20137%20§%208[1957 c 137 § 8]; ]

