= 79.70 - Natural area preserves.
:toc:

== 79.70.010 - Purpose.
The purpose of this chapter is to establish a state system of natural area preserves and a means whereby the preservation of these aquatic and land areas can be accomplished.

All areas within the state, except those which are expressly dedicated by law for preservation and protection in their natural condition, are subject to alteration by human activity. Natural lands, together with the plants and animals living thereon in natural ecological systems, are valuable for the purposes of scientific research, teaching, as habitats of rare and vanishing species, as places of natural historic and natural interest and scenic beauty, and as living museums of the original heritage of the state.

It is, therefore, the public policy of the state of Washington to secure for the people of present and future generations the benefit of an enduring resource of natural areas by establishing a system of natural area preserves, and to provide for the protection of these natural areas.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c119.pdf?cite=1972%20ex.s.%20c%20119%20§%201[1972 ex.s. c 119 § 1]; ]

== 79.70.020 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Department" means the department of natural resources.

. "Natural areas" and "natural area preserves" include such public or private areas of land or water which have retained their natural character, although not necessarily completely natural and undisturbed, or which are important in preserving rare or vanishing flora, fauna, geological, natural historical or similar features of scientific or educational value and which are acquired or voluntarily registered or dedicated by the owner under this chapter.

. "Public lands" and "state lands" have the meaning set out in RCW 79.02.010.

. "Council" means the natural heritage advisory council as established in RCW 79.70.070.

. "Commissioner" means the commissioner of public lands.

. "Important bird area" means those areas jointly identified by the natural heritage program and a qualifying nonprofit organization using internationally recognized scientific criteria. These areas have been found to be necessary to conserve populations of wild waterfowl, upland game birds, songbirds, and other birds native to and migrating through Washington, and contain the habitats that birds are dependent upon for breeding, migration, shelter, and sustenance.

. "Instrument of dedication" means any written document intended to convey an interest in real property pursuant to chapter 64.04 RCW.

. "Natural heritage resources" means the plant community types, aquatic types, unique geologic types, and special plant and animal species and their critical habitat as defined in the natural heritage plan established under RCW 79.70.030.

. "Plan" means the natural heritage plan as established under RCW 79.70.030.

. "Program" means the natural heritage program as established under RCW 79.70.030.

. "Qualifying nonprofit organization" means a national nonprofit organization, or a branch of a national nonprofit organization, that conserves and restores natural ecosystems, focusing on birds, other wildlife, and their habitat.

. "Register" means the Washington register of natural area preserves as established under RCW 79.70.030.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2650-S.SL.pdf?cite=2004%20c%20180%20§%204[2004 c 180 § 4]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20548[2003 c 334 § 548]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c189.pdf?cite=1981%20c%20189%20§%201[1981 c 189 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c119.pdf?cite=1972%20ex.s.%20c%20119%20§%202[1972 ex.s. c 119 § 2]; ]

== 79.70.030 - Powers of department.
In order to set aside, preserve, and protect natural areas within the state, the department is authorized, in addition to any other powers, to:

. Establish the criteria for selection, acquisition, management, protection, and use of such natural areas, including:

.. Limiting public access to natural area preserves consistent with the purposes of this chapter. Where appropriate, and on a case-by-case basis, a buffer zone with an increased low level of public access may be created around the environmentally sensitive areas;

.. Developing a management plan for each designated natural area preserve. The plan must identify the significant resources to be conserved consistent with the purposes of this chapter and identify the areas with potential for low-impact public and environmental educational uses. The plan must specify the types of management activities and public uses that are permitted, consistent with the purposes of this chapter. The department must make the plans available for review and comment by the public, and state, tribal, and local agencies, prior to final approval;

. Cooperate or contract with any federal, state, or local governmental agency, private organizations, or individuals in carrying out the purpose of this chapter;

. Consistent with the plan, acquire by gift, devise, purchase, grant, dedication, or means other than eminent domain, the fee or any lesser right or interest in real property which shall be held and managed as a natural area;

. Acquire by gift, devise, grant, or donation any personal property to be used in the acquisition and/or management of natural areas;

. Inventory existing public, state, and private lands in cooperation with the council to assess possible natural areas to be preserved within the state;

. Maintain a natural heritage program to provide assistance in the selection and nomination of areas containing natural heritage resources for registration or dedication. The program shall maintain a classification of natural heritage resources, an inventory of their locations, and a data bank for such information. The department shall cooperate with the department of fish and wildlife in the selection and nomination of areas from the data bank that relate to critical wildlife habitats. Information from the data bank shall be made available to public and private agencies and individuals for environmental assessment and proprietary land management purposes. Usage of the classification, inventory, or data bank of natural heritage resources for any purpose inconsistent with the natural heritage program is not authorized;

. Prepare a natural heritage plan which shall govern the natural heritage program in the conduct of activities to create and manage a system of natural areas that includes natural resources conservation areas, and may include areas designated under the research natural area program on federal lands in the state;

.. The plan shall list the natural heritage resources to be considered for registration and shall provide criteria for the selection and approval of natural areas under this chapter;

.. The department shall provide opportunities for input, comment, and review to the public, other public agencies, and private groups with special interests in natural heritage resources during preparation of the plan;

.. Upon approval by the council and adoption by the department, the plan shall be updated and submitted biennially to the appropriate committees of the legislature for their information and review. The plan shall take effect ninety days after the adjournment of the legislative session in which it is submitted unless the reviewing committees suggest changes or reject the plan; and

. Maintain a state register of natural areas containing significant natural heritage resources to be called the Washington register of natural area preserves. Selection of natural areas for registration shall be in accordance with criteria listed in the natural heritage plan and accomplished through voluntary agreement between the owner of the natural area and the department. No privately owned lands may be proposed to the council for registration without prior notice to the owner or registered without voluntary consent of the owner. No state or local governmental agency may require such consent as a condition of any permit or approval of or settlement of any civil or criminal proceeding or to penalize any landowner in any way for failure to give, or for withdrawal of, such consent.

.. The department shall adopt rules as authorized by RCW 43.12.065 and 79.70.030(1) and chapter 34.05 RCW relating to voluntary natural area registration.

.. After approval by the council, the department may place sites onto the register or remove sites from the register.

.. The responsibility for management of registered natural area preserves shall be with the preserve owner. A voluntary management agreement may be developed between the department and the owners of the sites on the register.

.. Any public agency may register lands under provisions of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20549[2003 c 334 § 549]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6575-S.SL.pdf?cite=2002%20c%20284%20§%201[2002 c 284 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2590.SL.pdf?cite=1994%20c%20264%20§%2061[1994 c 264 § 61]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c36.pdf?cite=1988%20c%2036%20§%2054[1988 c 36 § 54]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c189.pdf?cite=1981%20c%20189%20§%203[1981 c 189 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c119.pdf?cite=1972%20ex.s.%20c%20119%20§%203[1972 ex.s. c 119 § 3]; ]

== 79.70.040 - Powers as to transactions involving public lands deemed natural areas—Alienation of lands designated natural area preserves.
The department is further authorized to purchase, lease, set aside, or exchange any public lands which are deemed to be natural areas: PROVIDED, That the appropriate state land trust receives the fair market value for any interests that are disposed of: PROVIDED, FURTHER, That such transactions are approved by the board of natural resources.

An area consisting of public land designated as a natural area preserve shall be held in trust and shall not be alienated except to another public use upon a finding by the department of natural resources of imperative and unavoidable public necessity.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2321-S.SL.pdf?cite=2004%20c%20199%20§%20228[2004 c 199 § 228]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c119.pdf?cite=1972%20ex.s.%20c%20119%20§%204[1972 ex.s. c 119 § 4]; ]

== 79.70.060 - Legislative findings—Natural heritage resources.
The legislature finds:

. That it is necessary to establish a process and means for public and private sector cooperation in the development of a system of natural areas. Private and public landowners should be encouraged to participate in a program of natural area establishment which will benefit all citizens of the state;

. That there is a need for a systematic and accessible means for providing information concerning the locations of the state's natural heritage resources; and

. That the natural heritage advisory council should utilize a specific framework for natural heritage resource conservation decision making through a classification, inventory, priority establishment, acquisition, and management process known as the natural heritage program. Future natural areas should avoid unnecessary duplication of already protected natural heritage resources including those which may already be protected in existing publicly owned or privately dedicated lands such as nature preserves, natural areas, natural resources conservation areas, parks, or wilderness.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6575-S.SL.pdf?cite=2002%20c%20284%20§%202[2002 c 284 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c189.pdf?cite=1981%20c%20189%20§%202[1981 c 189 § 2]; ]

== 79.70.070 - Natural heritage advisory council.
. The natural heritage advisory council is hereby established. The council shall consist of fifteen members, ten of whom shall be chosen as follows and who shall elect from the council's membership a chairperson:

.. Five individuals, appointed by the commissioner, who shall be recognized experts in the ecology of natural areas and represent the public, academic, and private sectors. Desirable fields of expertise are biological and geological sciences; and

.. Five individuals, appointed by the commissioner, who shall be selected from the various regions of the state. At least one member shall be or represent a private forestland owner and at least one member shall be or represent a private agricultural landowner.

. Members appointed under subsection (1) of this section shall serve for terms of four years.

. In addition to the members appointed by the commissioner, the director of the department of fish and wildlife, the director of the department of ecology, the supervisor of the department of natural resources, the director of the state parks and recreation commission, and the director of the recreation and conservation office, or an authorized representative of each agency officer, shall serve as ex officio, nonvoting members of the council.

. Any vacancy on the council shall be filled by appointment for the unexpired term by the commissioner.

. In order to provide for staggered terms, of the initial members of the council:

.. Three shall serve for a term of two years;

.. Three shall serve for a term of three years; and

.. Three shall serve for a term of four years.

. Members of the natural preserves advisory committee serving on July 26, 1981, shall serve as members of the council until the commissioner appoints a successor to each. The successor appointment shall be specifically designated to replace a member of the natural preserves advisory committee until all members of that committee have been replaced. A member of the natural preserves advisory committee is eligible for appointment to the council if otherwise qualified.

. Members of the council shall serve without compensation. Members shall be reimbursed for travel expenses as provided in RCW 43.03.050 and 43.03.060 as now or hereafter amended.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1813.SL.pdf?cite=2007%20c%20241%20§%2024[2007 c 241 § 24]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2797.SL.pdf?cite=1998%20c%2050%20§%201[1998 c 50 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2590.SL.pdf?cite=1994%20c%20264%20§%2062[1994 c 264 § 62]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c36.pdf?cite=1988%20c%2036%20§%2055[1988 c 36 § 55]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c189.pdf?cite=1981%20c%20189%20§%204[1981 c 189 § 4]; ]

== 79.70.080 - Council duties.
. The council shall:

.. Meet at least annually and more frequently at the request of the chairperson;

.. Recommend policy for the natural heritage program through the review and approval of the natural heritage plan;

.. Advise the department, the department of fish and wildlife, the state parks and recreation commission, and other state agencies managing state-owned land or natural resources regarding areas under their respective jurisdictions which are appropriate for natural area registration or dedication;

.. Advise the department of rules and regulations that the council considers necessary in carrying out this chapter;

.. Review and approve area nominations by the department or other agencies for registration and review and comment on legal documents for the voluntary dedication of such areas;

.. Recommend whether new areas proposed for protection be established as natural area preserves, natural resources conservation areas, a combination of both, or by some other protected status; and

.. Review and comment on management plans proposed for individual natural area preserves.

. From time to time, the council shall identify areas from the natural heritage data bank which qualify for registration. Priority shall be based on the natural heritage plan and shall generally be given to those resources which are rarest, most threatened, or under-represented in the heritage conservation system on a statewide basis. After qualifying areas have been identified, the department shall advise the owners of such areas of the opportunities for acquisition or voluntary registration or dedication.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6575-S.SL.pdf?cite=2002%20c%20284%20§%203[2002 c 284 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2590.SL.pdf?cite=1994%20c%20264%20§%2063[1994 c 264 § 63]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c36.pdf?cite=1988%20c%2036%20§%2056[1988 c 36 § 56]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c189.pdf?cite=1981%20c%20189%20§%205[1981 c 189 § 5]; ]

== 79.70.090 - Dedication of property as natural area.
. The owner of a registered natural area, whether a private individual or an organization, may voluntarily agree to dedicate the area as a natural area by executing with the state an instrument of dedication in a form approved by the council. The instrument of dedication shall be effective upon its recording in the real property records of the appropriate county or counties in which the natural area is located. The county assessor in computing assessed valuation shall take into consideration any reductions in property values and/or highest and best use which result from natural area dedication.

. A public agency owning or managing a registered natural area preserve may dedicate lands under the provisions of this chapter.

. The department shall adopt rules as authorized by RCW 43.12.065 and 79.70.030(1) relating to voluntary natural area dedication and defining:

.. The types of real property interests that may be transferred;

.. Real property transfer methods and the types of consideration of payment possible;

.. Additional dedication provisions, such as natural area management, custody, use, and rights and privileges retained by the owner; and

.. Procedures for terminating dedication arrangements.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20550[2003 c 334 § 550]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c189.pdf?cite=1981%20c%20189%20§%206[1981 c 189 § 6]; ]

== 79.70.100 - Public hearing—Establishment of boundary.
The department shall hold a public hearing in the county where the majority of the land in a proposed natural area preserve is located prior to establishing the boundary.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2797.SL.pdf?cite=1998%20c%2050%20§%202[1998 c 50 § 2]; ]

== 79.70.110 - Important bird areas.
. The program may use information collected by a qualifying nonprofit organization to recognize important bird areas. The program should, to the greatest extent possible, coordinate with and use internationally agreed-upon, scientific criteria and protocols developed by a qualifying nonprofit organization to officially recognize these sites throughout Washington. Prior to using information collected by a qualifying nonprofit organization, the program must verify that the information was collected by individuals trained in scientific data collection, wildlife biology, or ornithology.

. When the program recognizes an important bird area, that information will be included in the program's data bank. An important bird area shall not be designated as a natural area or a natural area preserve unless that area satisfies the substantive and procedural requirements for becoming a natural area or natural area preserve under this chapter.

. The qualifying nonprofit organization that collected the information used to recognize important bird areas should be available to work with interested landowners, businesses, and state and local governments to identify ways to maintain or enhance the important bird areas.

. The recognition of private property as an important bird area under this chapter, or the inclusion of private property in the program's data bank, does not confer nor imply any rights of access or trespass onto the important bird area without full knowledge and consent of the owner pursuant to any state statutory and common laws dealing with trespass and access to private property.

. Recognition of an important bird area does not require or create critical area designation under chapter 36.70A RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2650-S.SL.pdf?cite=2004%20c%20180%20§%202[2004 c 180 § 2]; ]

== 79.70.120 - Important bird area—Recognition requirements.
Prior to recognizing an important bird area under this chapter, the department must:

. Publish notice of the proposed important bird area in the Washington state register;

. Publish notice of the proposed important bird area in a newspaper of general circulation in the county where the proposed important bird area is located; and

. Conduct at least one public hearing in the county where the proposed important bird area is located.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2650-S.SL.pdf?cite=2004%20c%20180%20§%203[2004 c 180 § 3]; ]

== 79.70.130 - Distribution of amount in lieu of real property taxes, weed control assessment.
The state treasurer, on behalf of the department, must distribute to counties for all lands acquired for the purposes of this chapter an amount in lieu of real property taxes equal to the amount of tax that would be due if the land were taxable as open space land under chapter 84.34 RCW except taxes levied for any state purpose, plus an additional amount equal to the amount of weed control assessment that would be due if such lands were privately owned. The county assessor and county legislative authority shall assist in determining the appropriate calculation of the amount of tax that would be due. The county shall distribute the amount received under this section in lieu of real property taxes to all property taxing districts except the state in appropriate tax code areas the same way it would distribute local property taxes from private property. The county shall distribute the amount received under this section for weed control to the appropriate weed district.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5396-S.SL.pdf?cite=2005%20c%20303%20§%2011[2005 c 303 § 11]; ]

== 79.70.900 - Construction—1972 ex.s. c 119.
Nothing in this chapter is intended to supersede or otherwise affect any existing legislation.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c119.pdf?cite=1972%20ex.s.%20c%20119%20§%206[1972 ex.s. c 119 § 6]; ]

