= 79.38 - Access roads.
:toc:

== 79.38.010 - Acquisition of property for access to public lands.
In addition to any authority otherwise granted by law, the department shall have the authority to acquire lands, interests in lands, and other property for the purpose of affording access by road to public lands from any public highway.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2321-S.SL.pdf?cite=2004%20c%20199%20§%20221[2004 c 199 § 221]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20499[2003 c 334 § 499]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c44.pdf?cite=1961%20c%2044%20§%201[1961 c 44 § 1]; ]

== 79.38.020 - Exchange of easement rights.
To facilitate the carrying out of the purpose of this chapter, the department may:

. Grant easements, rights-of-way, and permits to cross public lands to any person in exchange for similar rights over lands not under its jurisdiction;

. Enter into agreements with any person or agency relating to purchase, construction, reconstruction, maintenance, repair, regulation, and use of access roads or public roads used to provide access to public lands;

. Dispose, by sale, exchange, or otherwise, of any interest in an access road in the event it determines such interest is no longer necessary for the purposes of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2321-S.SL.pdf?cite=2004%20c%20199%20§%20222[2004 c 199 § 222]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c204.pdf?cite=1981%20c%20204%20§%201[1981 c 204 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c44.pdf?cite=1961%20c%2044%20§%202[1961 c 44 § 2]; ]

== 79.38.030 - Use of roads by purchasers of valuable materials.
Purchasers of valuable materials from public lands may use access roads or public roads for the removal of such materials where the rights acquired by the state will permit, but use shall be subject to the right of the department:

. To impose reasonable terms for the use, construction, reconstruction, maintenance, and repair of such access roads; and

. To impose reasonable charges for the use of such access roads or public roads which have been constructed or reconstructed through funding by the department.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2321-S.SL.pdf?cite=2004%20c%20199%20§%20223[2004 c 199 § 223]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20500[2003 c 334 § 500]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c204.pdf?cite=1981%20c%20204%20§%202[1981 c 204 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c44.pdf?cite=1961%20c%2044%20§%203[1961 c 44 § 3]; ]

== 79.38.040 - Permits for use of roads.
Whenever the department finds that it is for the best interest of the state and where the rights acquired by the state will permit, the department may grant permits for the use of access roads to any person. Any permit issued under the authority of this section shall be subject to reasonable regulation by the department. Such regulation shall include, but is not limited to, the following matters:

. Requirements for construction, reconstruction, maintenance, and repair;

. Limitations as to extent and time of use;

. Provision for revocation at the discretion of the department; and

. Charges for use.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20501[2003 c 334 § 501]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c44.pdf?cite=1961%20c%2044%20§%204[1961 c 44 § 4]; ]

== 79.38.050 - Access road revolving fund.
The department shall create, maintain, and administer a revolving fund, to be known as the access road revolving fund in which shall be deposited all moneys received by it from users of access roads as payment for costs incurred or to be incurred in maintaining, repairing, and reconstructing access roads, or public roads used to provide access to public lands. The department may use moneys in the fund for the purposes for which they were obtained without appropriation by the legislature.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2321-S.SL.pdf?cite=2004%20c%20199%20§%20224[2004 c 199 § 224]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20502[2003 c 334 § 502]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c204.pdf?cite=1981%20c%20204%20§%203[1981 c 204 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c44.pdf?cite=1961%20c%2044%20§%205[1961 c 44 § 5]; ]

== 79.38.060 - Use of moneys not deposited in revolving fund.
All moneys received by the department from users of access roads that are not deposited in the access road revolving fund shall be paid as follows:

. To reimburse the state fund or account from which expenditures have been made for the acquisition, construction, or improvement of the access road or public road, and upon full reimbursement, then

. To the funds or accounts for which the public lands, to which access is provided, are pledged by law or constitutional provision, in which case the department shall make an equitable apportionment between funds and accounts so that no fund or account shall benefit at the expense of another.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2321-S.SL.pdf?cite=2004%20c%20199%20§%20225[2004 c 199 § 225]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20503[2003 c 334 § 503]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c204.pdf?cite=1981%20c%20204%20§%204[1981 c 204 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c44.pdf?cite=1961%20c%2044%20§%206[1961 c 44 § 6]; ]

== 79.38.070 - Department-county agreements for improvement of access roads.
The department may enter into agreements with the county to:

. Identify public roads used to provide access to state forestlands in need of improvement;

. Establish a time schedule for the improvements;

. Advance payments to the county to fund the road improvements. However, no more than fifty percent of the access road revolving fund shall be eligible for use as advance payments to counties. The department shall assess the fund on January 1st and July 1st of each year to determine the amount that may be used as advance payments to counties for road improvements; and

. Determine the equitable distribution, if any, of costs of such improvements between the county and the state through negotiation of terms and conditions of any resulting repayment to the fund or funds financing the improvements.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20224[2003 c 334 § 224]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c204.pdf?cite=1981%20c%20204%20§%205[1981 c 204 § 5]; ]

