= 79.71 - Washington natural resources conservation areas.
:toc:

== 79.71.010 - Legislative findings.
The legislature finds that: (1) There is an increasing and continuing need by the people of Washington for certain areas of the state to be conserved, in rural as well as urban settings, for the benefit of present and future generations; (2) such areas are worthy of conservation for their outstanding scenic and ecological values and provide opportunities for low-impact public use; (3) in certain cases acquisition of property or rights in property is necessary to protect these areas for public purposes; and (4) there is a need for a state agency to act in an effective and timely manner to acquire interests in such areas and to develop appropriate management strategies for conservation purposes.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5612-S.SL.pdf?cite=1991%20c%20352%20§%201[1991 c 352 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c472.pdf?cite=1987%20c%20472%20§%201[1987 c 472 § 1]; ]

== 79.71.020 - Characteristics of lands considered for conservation purposes.
Lands possessing the following characteristics are considered by the legislature to be worthy of consideration for conservation purposes:

. Lands identified as having high priority for conservation, natural systems, wildlife, and low-impact public use values;

. An area of land or water, or land and water, that has flora, fauna, geological, archaeological, scenic, or similar features of critical importance to the people of Washington and that has retained to some degree or has reestablished its natural character;

. Examples of native ecological communities; and

. Environmentally significant sites threatened with conversion to incompatible or ecologically irreversible uses.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5612-S.SL.pdf?cite=1991%20c%20352%20§%202[1991 c 352 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c472.pdf?cite=1987%20c%20472%20§%202[1987 c 472 § 2]; ]

== 79.71.030 - Definitions.
As used in this chapter:

"Commissioner" means the commissioner of public lands.

"Department" means the department of natural resources.

"Conservation purposes" include but are not limited to: (1) Maintaining, enhancing, or restoring ecological systems, including but not limited to aquatic, coastal, riparian, montane, and geological systems, whether such systems be unique or typical to the state of Washington; (2) maintaining exceptional scenic landscapes; (3) maintaining habitat for threatened, endangered, and sensitive species; (4) enhancing sites for primitive recreational purposes; and (5) outdoor environmental education.

"Low-impact public use" includes public recreation uses and improvements that do not adversely affect the resource values, are appropriate to the maintenance of the site in a relatively unmodified natural setting, and do not detract from long-term ecological processes.

"Management activities" may include limited production of income from forestry, agriculture, or other resource management activities, if such actions are consistent with the other purposes and requirements of this chapter.

"Natural resources conservation area" or "conservation area" means an area having the characteristics identified in RCW 79.71.020.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5612-S.SL.pdf?cite=1991%20c%20352%20§%203[1991 c 352 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c472.pdf?cite=1987%20c%20472%20§%203[1987 c 472 § 3]; ]

== 79.71.040 - Acquisition of property for natural resources conservation areas—Designation.
The department is authorized to acquire property or less than fee interests in property, as defined by RCW 64.04.130, by all means, except eminent domain, for creating natural resources conservation areas, where acquisition is the best way to achieve the purposes of this chapter. Areas acquired or assembled by the department for conservation purposes will be designated as "Washington natural resources conservation areas."

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c472.pdf?cite=1987%20c%20472%20§%204[1987 c 472 § 4]; ]

== 79.71.050 - Transfer of trust land for natural resources conservation areas—Use of proceeds.
The department is authorized to transfer fee simple interest or less than fee interests in trust land, as defined by Article XVI of the Washington Constitution, for the creation of natural resources conservation areas, provided the owner of the trust land receives full fair market value compensation for all rights transferred. The proceeds from such transfers shall be used for the exclusive purpose of acquiring real property to replace those interests utilized for the conservation area in order to meet the department's fiduciary obligations and to maintain the productive land base of the various trusts.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5612-S.SL.pdf?cite=1991%20c%20352%20§%204[1991 c 352 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c472.pdf?cite=1987%20c%20472%20§%205[1987 c 472 § 5]; ]

== 79.71.060 - Public hearing on proposed conservation area.
The department shall hold a public hearing in the county where the majority of the land in the proposed natural resources conservation area is located prior to establishing the boundary. An area proposed for designation must contain resources consistent with characteristics identified in RCW 79.71.020.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5612-S.SL.pdf?cite=1991%20c%20352%20§%205[1991 c 352 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c472.pdf?cite=1987%20c%20472%20§%206[1987 c 472 § 6]; ]

== 79.71.070 - Management plans for designated areas.
The department shall develop a management plan for each designated area. The plan shall identify the significant resources to be conserved consistent with the purposes of this chapter and identify the areas with potential for low-impact public and environmental educational uses. The plan shall specify what types of management activities and public uses that are permitted, consistent with the conservation purposes of this chapter. The department shall make such plans available for review and comment by the public and other state, tribal, and local agencies, prior to final approval by the commissioner.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5612-S.SL.pdf?cite=1991%20c%20352%20§%206[1991 c 352 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c472.pdf?cite=1987%20c%20472%20§%207[1987 c 472 § 7]; ]

== 79.71.080 - Administration of natural resources conservation areas—Management agreements and activities.
The department is authorized to administer natural resources conservation areas and may enter into management agreements for these areas with federal agencies, state agencies, local governments, and private nonprofit conservancy corporations, as defined in RCW 64.04.130, when such agreements are consistent with the purposes of acquisition as defined in the adopted management plan. All management activities within a Washington natural resources conservation area will conform with the plan. Any moneys derived from the management of these areas in conformance with the adopted plan shall be deposited in the natural resources conservation areas stewardship account.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5612-S.SL.pdf?cite=1991%20c%20352%20§%207[1991 c 352 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c472.pdf?cite=1987%20c%20472%20§%208[1987 c 472 § 8]; ]

== 79.71.090 - Natural resources conservation areas stewardship account.
There is hereby created the natural resources conservation areas stewardship account in the state treasury to ensure proper and continuing management of land acquired or designated pursuant to this chapter. Funds for the stewardship account shall be derived from appropriations of state general funds, federal funds, grants, donations, gifts, bond issue receipts, securities, and other monetary instruments of value. Income derived from the management of natural resources conservation areas shall also be deposited in this stewardship account.

Appropriations from this account to the department shall be expended for no other purpose than the following: (1) To manage the areas approved by the legislature in fulfilling the purposes of this chapter; (2) to manage property acquired as natural area preserves under chapter 79.70 RCW; (3) to manage property transferred under the authority and appropriation provided by the legislature to be managed under chapter 79.70 RCW or this chapter or acquired under chapter 79A.15 RCW; and (4) to pay for operating expenses for the natural heritage program under chapter 79.70 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2399-S.SL.pdf?cite=2000%20c%2011%20§%2025[2000 c 11 § 25]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1058-S.SL.pdf?cite=1991%20sp.s.%20c%2013%20§%20118[1991 sp.s. c 13 § 118]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5612-S.SL.pdf?cite=1991%20c%20352%20§%208[1991 c 352 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c472.pdf?cite=1987%20c%20472%20§%209[1987 c 472 § 9]; ]

== 79.71.100 - Designation of certain areas as natural resources conservation areas.
The legislature hereby designates certain areas as natural resources conservation areas:

. The Mt. Si conservation area (King County), RCW 79A.05.725, is hereby designated the Mt. Si natural resources conservation area. The department is directed to continue its management of this area and to develop a plan for its continued conservation and use by the public. In accordance with Article XVI of the Washington state Constitution, any available private lands and trust lands located within the designated boundaries of the Mt. Si conservation area shall be leased or acquired in fee from the appropriate trust at fair market value using funds appropriated for that purpose.

. Trust lands and state-owned land on Cypress Island (Skagit County) are hereby designated as the Cypress Island natural resources conservation area. Any available private lands necessary to achieve the purposes of this section shall be acquired by the department of natural resources using funds appropriated for that purpose. Trust lands located within the designated boundaries of the Cypress Island natural resources conservation area shall be leased or acquired in fee from the appropriate trust at fair market value.

. Woodard Bay (Thurston County) is hereby designated the Woodard Bay natural resources conservation area. The department is directed to acquire property available in Sec. 18, T.19N, R1W using funds appropriated for that purpose.

. The area adjacent to the Dishman Hills natural area (Spokane County) is hereby designated the Dishman Hills natural resources conservation area. The department is directed to acquire property available in Sec. 19, 29 and 30, T.25N, R44E, using funds appropriated for that purpose.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2399-S.SL.pdf?cite=2000%20c%2011%20§%2026[2000 c 11 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c472.pdf?cite=1987%20c%20472%20§%2010[1987 c 472 § 10]; ]

== 79.71.120 - Elk river natural resources conservation area—Transfer of management—Hunting opportunities.
The property currently designated as the Elk river natural area preserve is transferred from management under chapter 79.70 RCW as a natural area preserve to management under chapter 79.71 RCW as a natural resources conservation area. The legislature finds that hunting is a suitable low-impact public use within the Elk river natural resources conservation area. The department of natural resources shall incorporate this legislative direction into the management plan developed for the Elk river natural resources conservation area. The department shall work with the department of fish and wildlife to identify hunting opportunities compatible with the area's conservation purposes.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1056-S.SL.pdf?cite=1997%20c%20371%20§%201[1997 c 371 § 1]; ]

== 79.71.130 - Distribution of amount in lieu of real property taxes, weed control assessment.
The state treasurer, on behalf of the department, must distribute to counties for all lands acquired for the purposes of this chapter an amount in lieu of real property taxes equal to the amount of tax that would be due if the land were taxable as open space land under chapter 84.34 RCW except taxes levied for any state purpose, plus an additional amount equal to the amount of weed control assessment that would be due if such lands were privately owned. The county assessor and county legislative authority shall assist in determining the appropriate calculation of the amount of tax that would be due. The county shall distribute the amount received under this section in lieu of real property taxes to all property taxing districts except the state in appropriate tax code areas the same way it would distribute local property taxes from private property. The county shall distribute the amount received under this section for weed control to the appropriate weed district.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5396-S.SL.pdf?cite=2005%20c%20303%20§%2012[2005 c 303 § 12]; ]

