= 79.10 - Land management authorities and policies.
:toc:

== 79.10.010 - Reports.
. It shall be the duty of the department to report, and recommend, to each session of the legislature, any changes in the law relating to the methods of handling the public lands of the state that the department may deem advisable.

. The department shall provide a comprehensive biennial report to reflect the previous fiscal period. The report shall include, but not be limited to, descriptions of all department activities including: Revenues generated, program costs, capital expenditures, personnel, special projects, new and ongoing research, environmental controls, cooperative projects, intergovernmental agreements, the adopted sustainable harvest compared to the sales program, and outlines of ongoing litigation, recent court decisions, and orders on major issues with the potential for state liability. The report shall describe the status of the resources managed and the recreational and commercial utilization. The report must be delivered to the appropriate committees of the legislature and made available to the public.

. The department shall provide annual reports to the respective trust beneficiaries, including each county. The report shall include, but not be limited to, the following: Acres sold, acres harvested, volume from those acres, acres planted, number of stems per acre, acres precommercially thinned, acres commercially thinned, acres partially cut, acres clear cut, age of final rotation for acres clear cut, and the total number of acres off base for harvest and an explanation of why those acres are off base for harvest.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20433[2003 c 334 § 433]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1826-S.SL.pdf?cite=1997%20c%20448%20§%203[1997 c 448 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c505.pdf?cite=1987%20c%20505%20§%2076[1987 c 505 § 76]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c93.pdf?cite=1985%20c%2093%20§%203[1985 c 93 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1927c255.pdf?cite=1927%20c%20255%20§%20196[1927 c 255 § 196]; RRS § 7797-196; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c114.pdf?cite=1907%20c%20114%20§%201[1907 c 114 § 1]; RRS § 7801; ]

== 79.10.020 - Department authority to accept land.
The department is hereby authorized, when in its judgment it appears advisable, to accept on behalf of the state, any grant of land within the state which shall then become a part of the state forests. No grant may be accepted until the title has been examined and approved by the attorney general of the state and a report made to the board of natural resources of the result of the examination.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c100.pdf?cite=1986%20c%20100%20§%2048[1986 c 100 § 48]; ]

== 79.10.030 - Management of acquired lands—Land acquired by escheat suitable for park purposes.
. Except as provided in subsection (2) of this section, the department shall manage and control all lands acquired by the state by escheat or under RCW 79.19.010 through 79.19.110 and all lands acquired by the state by deed of sale or gift or by devise, except such lands which are conveyed or devised to the state to be used for a particular purpose.

. When land is acquired by the state by escheat which because of its location or features may be suitable for park purposes, the department shall notify the state parks and recreation commission. The department and the commission shall jointly evaluate the land for its suitability for park purposes, based upon the features of the land and the need for park facilities in the vicinity. Where the department and commission determine that such land is suitable for park purposes, it shall be offered for transfer to the commission, or, in the event that the commission declines to accept the land, to the local jurisdiction providing park facilities in that area. When so offered, the payment required by the recipient agency shall not exceed the costs incurred by the department in managing and protecting the land since receipt by the state.

. The department may review lands acquired by escheat since January 1, 1983, for their suitability for park purposes, and apply the evaluation and transfer procedures authorized by subsection (2) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20398[2003 c 334 § 398]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5255-S.SL.pdf?cite=1993%20c%2049%20§%201[1993 c 49 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c222.pdf?cite=1984%20c%20222%20§%2013[1984 c 222 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1927c255.pdf?cite=1927%20c%20255%20§%20154[1927 c 255 § 154]; RRS § 7797-154; ]

== 79.10.040 - Gifts of land for offices.
Any county, city or town is authorized and empowered to convey to the state of Washington any lands owned by such county, city or town upon the selection of such lands by the department and the department is hereby authorized to select and accept conveyances of lands from such counties, cities or towns, suitable for use by the department as locations for offices, warehouses and machinery storage buildings in the administration of the forestry laws and lands of the state of Washington: PROVIDED, HOWEVER, No consideration shall be paid by the state nor by the department for the conveyance of such lands by such county, city or town.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c128.pdf?cite=1988%20c%20128%20§%2025[1988 c 128 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c125.pdf?cite=1937%20c%20125%20§%201[1937 c 125 § 1]; RRS § 5812-3c. FORMER PART OF SECTION: 1937 c 125 § 2 now codified as RCW  76.12.045; ]

== 79.10.050 - Gifts of county or city land for offices, warehouses, etc.—Use of lands authorized.
The department is authorized to use such lands for the purposes hereinbefore expressed and to improve said lands and build thereon any necessary structures for the purposes hereinbefore expressed and expend in so doing such funds as may be authorized by law therefor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c128.pdf?cite=1988%20c%20128%20§%2026[1988 c 128 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c125.pdf?cite=1937%20c%20125%20§%202[1937 c 125 § 2]; RRS § 5812-3d; ]

== 79.10.060 - Compliance with local ordinances, when.
The department may comply with county or municipal zoning ordinances, laws, rules, or regulations affecting the use of public lands where such regulations are consistent with the treatment of similar private lands.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2321-S.SL.pdf?cite=2004%20c%20199%20§%20209[2004 c 199 § 209]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20544[2003 c 334 § 544]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c234.pdf?cite=1971%20ex.s.%20c%20234%20§%2013[1971 ex.s. c 234 § 13]; ]

== 79.10.070 - Management of public lands within watershed area providing water supply for city or town—Lake Whatcom municipal watershed pilot project—Report—Exclusive method of condemnation by city or town for watershed purposes.
. In the management of public lands lying within the limits of any watershed over and through which is derived the water supply of any city or town, the department may alter its land management practices to provide water with qualities exceeding standards established for intrastate and interstate waters by the department of ecology. However, if such alterations of management by the department reduce revenues from, increase costs of management of, or reduce the market value of public lands the city or town requesting such alterations shall fully compensate the department.

. The department shall initiate a pilot project for the municipal watershed delineated by the Lake Whatcom hydrographic boundaries to determine what factors need to be considered to achieve water quality standards beyond those required under chapter 90.48 RCW and what additional management actions can be taken on state trust lands that can contribute to such higher water quality standards. The department shall establish an advisory committee consisting of a representative each of the city of Bellingham, Whatcom county, the Whatcom county water district 10, the department of ecology, the department of fish and wildlife, and the department of health, and three general citizen members to assist in this pilot project. In the event of differences of opinion among the members of the advisory committee, the committee shall attempt to resolve these differences through various means, including the retention of facilitation or mediation services.

. The pilot project in subsection (2) of this section shall be completed by June 30, 2000. The department shall defer all timber sales in the Lake Whatcom hydrographic boundaries until the pilot project is complete.

. Upon completion of the study, the department shall provide a report to the natural resources committee of the house of representatives and to the natural resources, parks, and recreation committee of the senate summarizing the results of the study.

. The exclusive manner, notwithstanding any provisions of the law to the contrary, for any city or town to acquire by condemnation ownership or rights in public lands for watershed purposes within the limits of any watershed over or through which is derived the water supply of any city or town shall be to petition the legislature for such authority. Nothing in RCW 79.44.003 and this chapter shall be construed to affect any existing rights held by third parties in the lands applied for.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20332[2003 c 334 § 332]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5536-S2.SL.pdf?cite=1999%20c%20257%20§%201[1999 c 257 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c234.pdf?cite=1971%20ex.s.%20c%20234%20§%2011[1971 ex.s. c 234 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1927c255.pdf?cite=1927%20c%20255%20§%2032[1927 c 255 § 32]; RRS § 7797-32; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c147.pdf?cite=1915%20c%20147%20§%202[1915 c 147 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c223.pdf?cite=1909%20c%20223%20§%203[1909 c 223 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c256.pdf?cite=1907%20c%20256%20§%206[1907 c 256 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1901c148.pdf?cite=1901%20c%20148%20§%201[1901 c 148 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1899c129.pdf?cite=1899%20c%20129%20§%201[1899 c 129 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1897c89.pdf?cite=1897%20c%2089%20§%2012[1897 c 89 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c178.pdf?cite=1895%20c%20178%20§%2023[1895 c 178 § 23]; ]

== 79.10.080 - Classification of land after timber removed.
When the merchantable timber has been sold and actually removed from any state lands, the department may classify the land, and may reserve from any future sale such portions thereof as may be found suitable for reforestation, and in such case, shall enter such reservation in its records. All lands reserved shall not be subject to sale or lease. The commissioner shall certify all such reservations for reforestation so made, to the board. It shall be the duty of the department to protect such lands, and the remaining timber thereon, from fire and to reforest the same.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20340[2003 c 334 § 340]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c257.pdf?cite=1959%20c%20257%20§%2016[1959 c 257 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1927c255.pdf?cite=1927%20c%20255%20§%2041[1927 c 255 § 41]; RRS § 7797-41; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c147.pdf?cite=1915%20c%20147%20§%202[1915 c 147 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c223.pdf?cite=1909%20c%20223%20§%203[1909 c 223 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c256.pdf?cite=1907%20c%20256%20§%206[1907 c 256 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1901c148.pdf?cite=1901%20c%20148%20§%201[1901 c 148 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1899c129.pdf?cite=1899%20c%20129%20§%201[1899 c 129 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1897c89.pdf?cite=1897%20c%2089%20§%2012[1897 c 89 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c178.pdf?cite=1895%20c%20178%20§%2023[1895 c 178 § 23]; ]

== 79.10.090 - Economic analysis of state lands held in trust—Scope—Use.
Periodically at intervals to be determined by the board, the department shall cause an economic analysis to be made of those state lands held in trust, where the nature of the trust makes maximization of the economic return to the beneficiaries of income from state lands the prime objective. The analysis shall be by specific tracts, or where such tracts are of similar economic characteristics, by groupings of such tracts.

The most recently made analysis shall be considered by the department in making decisions as to whether to sell or lease state lands, standing timber or crops thereon, or minerals therein, including but not limited to oil and gas and other hydrocarbons, rocks, gravel, and sand.

The economic analysis shall include, but shall not be limited to the following criteria: (1) Present and potential sale value; (2) present and probable future returns on the investment of permanent state funds; (3) probable future inflationary or deflationary trends; (4) present and probable future income from leases or the sale of land products; and (5) present and probable future tax income derivable therefrom specifically including additional state, local, and other tax revenues from potential private development of land currently used primarily for grazing and other similar low priority use; such private development would include, but not be limited to, development as irrigated agricultural land.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20320[2003 c 334 § 320]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c131.pdf?cite=1969%20ex.s.%20c%20131%20§%201[1969 ex.s. c 131 § 1]; ]

== 79.10.100 - Concept to be utilized, when.
The legislature hereby directs that a multiple use concept be utilized by the department in the administration of public lands where such a concept is in the best interests of the state and the general welfare of the citizens thereof, and is consistent with the applicable provisions of the various lands involved.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2321-S.SL.pdf?cite=2004%20c%20199%20§%20210[2004 c 199 § 210]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20534[2003 c 334 § 534]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c234.pdf?cite=1971%20ex.s.%20c%20234%20§%201[1971 ex.s. c 234 § 1]; ]

== 79.10.110 - "Multiple use" defined.
"Multiple use" as used in RCW 79.10.070, 79.44.003, and this chapter shall mean the management and administration of state-owned lands under the jurisdiction of the department to provide for several uses simultaneously on a single tract and/or planned rotation of one or more uses on and between specific portions of the total ownership consistent with the provisions of RCW 79.10.100.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20535[2003 c 334 § 535]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c234.pdf?cite=1971%20ex.s.%20c%20234%20§%202[1971 ex.s. c 234 § 2]; ]

== 79.10.120 - Multiple uses compatible with financial obligations of trust management—Other uses permitted, when.
Multiple uses additional to and compatible with those basic activities necessary to fulfill the financial obligations of trust management may include but are not limited to:

. Recreational areas;

. Recreational trails for both vehicular and nonvehicular uses developed or maintained consistent with RCW 79.10.500;

. Special educational or scientific studies;

. Experimental programs by the various public agencies;

. Special events;

. Hunting and fishing and other sports activities;

. Maintenance of pollinator habitat and habitat beneficial for the feeding, nesting, and reproduction of all pollinators, including honey bees;

. Nonconsumptive wildlife activities as defined by the board of natural resources;

. Maintenance of scenic areas;

. Maintenance of historical sites;

. Municipal or other public watershed protection;

. Greenbelt areas;

. Public rights-of-way;

. Other uses or activities by public agencies.

If such additional uses are not compatible with the financial obligations in the management of trust land they may be permitted only if there is compensation from such uses satisfying the financial obligations.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5552-S.SL.pdf?cite=2019%20c%20353%20§%205[2019 c 353 § 5]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=2014%20c%20114%20§%204[2014 c 114 § 4]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5006-S.SL.pdf?cite=2003%20c%20182%20§%202[2003 c 182 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c234.pdf?cite=1971%20ex.s.%20c%20234%20§%205[1971 ex.s. c 234 § 5]; ]

== 79.10.125 - Land open to public for fishing, hunting, and nonconsumptive wildlife activities.
All state lands hereafter leased for grazing or agricultural purposes shall be open and available to the public for purposes of hunting and fishing, and for nonconsumptive wildlife activities, as defined by the board of natural resources, unless closed to public entry because of fire hazard or unless the department gives prior written approval and the area is lawfully posted by lessee to prohibit hunting and fishing, and nonconsumptive wildlife activities, thereon in order to prevent damage to crops or other land cover, to improvements on the land, to livestock, to the lessee, or to the general public, or closure is necessary to avoid undue interference with carrying forward a departmental or agency program. In the event any such lands are so posted it shall be unlawful for any person to hunt or fish, or pursue nonconsumptive wildlife activities, on any such posted lands. Such lands shall not be open and available for wildlife activities when access could endanger crops on the land or when access could endanger the person accessing the land.

The department shall insert the provisions of this section in all new grazing and agricultural leases.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20371[2003 c 334 § 371]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5006-S.SL.pdf?cite=2003%20c%20182%20§%201[2003 c 182 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c109.pdf?cite=1979%20ex.s.%20c%20109%20§%209[1979 ex.s. c 109 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c46.pdf?cite=1969%20ex.s.%20c%2046%20§%201[1969 ex.s. c 46 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c257.pdf?cite=1959%20c%20257%20§%2029[1959 c 257 § 29]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c171.pdf?cite=1947%20c%20171%20§%201[1947 c 171 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1927c255.pdf?cite=1927%20c%20255%20§%2061[1927 c 255 § 61]; RRS § 7797-61; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c147.pdf?cite=1915%20c%20147%20§%204[1915 c 147 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1903c79.pdf?cite=1903%20c%2079%20§%204[1903 c 79 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1897c89.pdf?cite=1897%20c%2089%20§%2019[1897 c 89 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c178.pdf?cite=1895%20c%20178%20§%2032[1895 c 178 § 32]; ]

== 79.10.130 - Scope of department's authorized activities.
. The department is hereby authorized to carry out all activities necessary to achieve the purposes of this section and RCW 79.10.060, 79.10.070, 79.10.100 through 79.10.120, 79.10.200 through 79.10.330, 79.44.003, and 79.105.050 including, but not limited to:

.. Planning, construction, and operation of conservation, recreational sites, areas, roads, and trails developed or maintained consistent with RCW 79.10.500, by itself or in conjunction with any public agency, nonprofit organization, volunteer, or volunteer organization, including entering cooperative agreements for these purposes;

.. Planning, construction, and operation of special facilities for educational, scientific, conservation, or experimental purposes by itself or in conjunction with any other public or private agency, including entering cooperative agreements for these purposes;

.. Improvement of any lands to achieve the purposes of this section and RCW 79.10.060, 79.10.070, 79.10.100 through 79.10.120, 79.10.200 through 79.10.330, 79.44.003, and 79.105.050, including entering cooperative agreements with public agencies, nonprofit organizations, volunteers, and volunteer organizations for these purposes;

.. Entering cooperative agreements with public agencies, nonprofit organizations, volunteers, and volunteer organizations regarding the use of lands managed by the department for the purpose of providing a benefit to lands managed by the department, including but not limited to the following benefits: The utilization of such lands for watershed purposes; carrying out restoration and enhancement projects on such lands, such as improving, restoring, or enhancing habitat that provides for plant or animal species protection; improving, restoring, or enhancing watershed conditions; removing nonnative vegetation and providing vegetation management to restore, enhance, or maintain properly functioning conditions of the local ecosystem; and other similar projects on these lands that provide long-term environmental and other land management benefits, provided that the cooperative agreements are consistent with land management obligations;

.. Authorizing individual volunteers and volunteer organizations to conduct restoration and enhancement projects on lands managed by the department through cooperative agreements authorized in this section or other arrangements that are consistent with land management obligations and that do not require the volunteers to pay a fee for the cooperative agreement purpose;

.. Authorizing the receipt of gifts of personal property, services, and other items of value for the purposes of this section, as well as the exchange of consideration in cooperative agreements authorized under this section;

.. The authority to make such leases, contracts, agreements, or other arrangements as are necessary to accomplish the purposes of this section and RCW 79.10.060, 79.10.070, 79.10.100 through 79.10.120, 79.10.200 through 79.10.330, 79.44.003, and 79.105.050. However, nothing in this section shall affect any existing requirements for public bidding or auction with private agencies or parties, except that agreements or other arrangements may be made with public schools, colleges, universities, governmental agencies, nonprofit organizations, volunteers, and volunteer organizations. In addition, nothing in this section is intended to conflict with the department's trust obligations.

. The definitions in this subsection apply throughout this section unless the context clearly requires otherwise.

.. "Nonprofit organization" means: (i) Any organization described in section 501(c)(3) of the internal revenue code of 1986 (26 U.S.C. Sec. 501(c)(3)) and exempt from tax under section 501(a) of the internal revenue code; or (ii) any not-for-profit organization that is organized and conducted for public benefit and operated primarily for charitable, civic, educational, religious, welfare, or health purposes.

.. "Volunteer" or "volunteer organization" means an individual or entity performing services for a nonprofit organization or a governmental entity who does not receive compensation, other than reasonable reimbursement or allowances for expenses actually incurred, or any other thing of value, in excess of five hundred dollars per year. "Volunteer" includes a volunteer serving as a director, officer, trustee, or direct service volunteer.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=2014%20c%20114%20§%205[2014 c 114 § 5]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5634-S.SL.pdf?cite=2013%20c%2015%20§%201[2013 c 15 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20540[2003 c 334 § 540]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c472.pdf?cite=1987%20c%20472%20§%2012[1987 c 472 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c234.pdf?cite=1971%20ex.s.%20c%20234%20§%207[1971 ex.s. c 234 § 7]; ]

== 79.10.140 - Outdoor recreation—Construction, operation, and maintenance of primitive facilities—Right-of-way and public access—Use of state and federal outdoor recreation funds.
The department is authorized:

. To construct, operate, and maintain primitive outdoor recreation and conservation facilities on lands under its jurisdiction which are of primitive character when deemed necessary by the department to achieve maximum effective development of such lands and resources consistent with the purposes for which the lands are held. This authority shall be exercised only after review by the recreation and conservation funding board and determination by the recreation and conservation funding board that the department is the most appropriate agency to undertake such construction, operation, and maintenance. Such review is not required for campgrounds designated and prepared or approved by the department;

. To acquire right-of-way and develop public access to lands under the jurisdiction of the department and suitable for public outdoor recreation and conservation purposes;

. To receive and expend funds from federal and state outdoor recreation funding measures for the purposes of this section and RCW 79A.50.110.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1813.SL.pdf?cite=2007%20c%20241%20§%2023[2007 c 241 § 23]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20122[2003 c 334 § 122]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c472.pdf?cite=1987%20c%20472%20§%2013[1987 c 472 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c100.pdf?cite=1986%20c%20100%20§%2051[1986 c 100 § 51]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c64.pdf?cite=1967%20ex.s.%20c%2064%20§%201[1967 ex.s. c 64 § 1]; ]

== 79.10.200 - Multiple use land resource allocation plan—Adoption—Factors considered.
The department may adopt a multiple use land resource allocation plan for all or portions of the lands under its jurisdiction providing for the identification and establishment of areas of land uses and identifying those uses which are best suited to achieve the purposes of RCW 79.10.060, 79.10.070, 79.10.100 through 79.10.120, 79.10.130, 79.10.200 through 79.10.330, 79.44.003, and 79.105.050. Such plans shall take into consideration the various ecological conditions, elevations, soils, natural features, vegetative cover, pollinator habitat, climate, geographical location, values, public use potential, accessibility, economic uses, recreational potentials, local and regional land use plans or zones, local, regional, state, and federal comprehensive land use plans or studies, and all other factors necessary to achieve the purposes of RCW 79.10.060, 79.10.070, 79.10.100 through 79.10.120, 79.10.130, 79.10.200 through 79.10.330, 79.44.003, and 79.105.050.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5552-S.SL.pdf?cite=2019%20c%20353%20§%206[2019 c 353 § 6]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20542[2003 c 334 § 542]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c234.pdf?cite=1971%20ex.s.%20c%20234%20§%209[1971 ex.s. c 234 § 9]; ]

== 79.10.210 - Public lands identified and withdrawn.
For the purpose of providing increased continuity in the management of public lands and of facilitating long range planning by interested agencies, the department is authorized to identify and to withdraw from all conflicting uses at such times and for such periods as it shall determine appropriate, limited acreages of public lands under its jurisdiction. Acreages so withdrawn shall be maintained for the benefit of the public and, in particular, of the public schools, colleges, and universities, as areas in which may be observed, studied, enjoyed, or otherwise utilized the natural ecological systems thereon, whether such systems be unique or typical to the state of Washington. Nothing herein is intended to or shall modify the department's obligation to manage the land under its jurisdiction in the best interests of the beneficiaries of granted trust lands.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20539[2003 c 334 § 539]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c234.pdf?cite=1971%20ex.s.%20c%20234%20§%206[1971 ex.s. c 234 § 6]; ]

== 79.10.220 - Conferring with other agencies.
The department may confer with other public and private agencies to facilitate the formulation of policies and/or plans providing for multiple use concepts. The department is empowered to hold public hearings from time to time to assist in achieving the purposes of RCW 79.10.060, 79.10.070, 79.10.100 through 79.10.120, 79.10.130, 79.10.200 through 79.10.330, 79.44.003, and * 79.90.456.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20543[2003 c 334 § 543]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c234.pdf?cite=1971%20ex.s.%20c%20234%20§%2010[1971 ex.s. c 234 § 10]; ]

== 79.10.240 - Department's existing authority and powers preserved.
Nothing in RCW 79.10.060, 79.10.070, 79.10.100 through 79.10.120, 79.10.130, 79.10.200 through 79.10.330, 79.44.003, and * 79.90.456 shall be construed to affect or repeal any existing authority or powers of the department in the management or administration of the lands under its jurisdiction.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20546[2003 c 334 § 546]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c234.pdf?cite=1971%20ex.s.%20c%20234%20§%2012[1971 ex.s. c 234 § 12]; ]

== 79.10.250 - Existing withdrawals for state park and state game purposes preserved.
Nothing in RCW 79.10.060, 79.10.070, 79.10.100 through 79.10.120, 79.10.130, 79.10.200 through 79.10.330, 79.44.003, and * 79.90.456 shall be construed to affect, amend, or repeal any existing withdrawal of public lands for state park or state game purposes.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20547[2003 c 334 § 547]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c234.pdf?cite=1971%20ex.s.%20c%20234%20§%2015[1971 ex.s. c 234 § 15]; ]

== 79.10.280 - Land use data bank—Contents, source.
. The department shall design expansion of its land use data bank to include additional information that will assist in the formulation, evaluation, and updating of intermediate and long-range goals and policies for land use, population growth and distribution, urban expansion, open space, resource preservation and utilization, and other factors which shape statewide development patterns and significantly influence the quality of the state's environment. The system shall be designed to permit inclusion of other lands in the state and will do so as financing and time permit.

. Such data bank shall contain any information relevant to the future growth of agriculture, forestry, industry, business, residential communities, and recreation; the wise use of land and other natural resources which are in accordance with their character and adaptability; the conservation and protection of the soil, air, water, pollinator habitat, and forest resources; the protection of the beauty of the landscape; and the promotion of the efficient and economical uses of public resources.

The information shall be assembled from all possible sources, including but not limited to, the federal government and its agencies, all state agencies, all political subdivisions of the state, all state operated universities and colleges, and any source in the private sector. All state agencies, all political subdivisions of the state, and all state universities and colleges are directed to cooperate to the fullest extent in the collection of data in their possession. Information shall be collected on all areas of the state but collection may emphasize one region at a time.

. The data bank shall make maximum use of computerized or other advanced data storage and retrieval methods. The department is authorized to engage consultants in data processing to ensure that the data bank will be as complete and efficient as possible.

. The data shall be made available for use by any governmental agency, research organization, university or college, private organization, or private person as a tool to evaluate the range of alternatives in land and resource planning in the state.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5552-S.SL.pdf?cite=2019%20c%20353%20§%207[2019 c 353 § 7]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20545[2003 c 334 § 545]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c234.pdf?cite=1971%20ex.s.%20c%20234%20§%2016[1971 ex.s. c 234 § 16]; ]

== 79.10.300 - Definitions.
Unless the context clearly requires otherwise the definitions in this section apply throughout RCW 79.10.310, 79.10.320, and 79.10.330.

. "Arrearage" means the summation of the annual sustainable harvest timber volume since July 1, 1979, less the sum of state timber sales contract default volume and the state timber sales volume deficit since July 1, 1979.

. "Default" means the volume of timber remaining when a contractor fails to meet the terms of the sales contract on the completion date of the contract or any extension thereof and timber returned to the state under *RCW 79.01.1335.

. "Deficit" means the summation of the difference between the department's annual planned sales program volume and the actual timber volume sold.

. "Planning decade" means the ten-year period covered in the forestland management plan adopted by the board.

. "Sustainable harvest level" means the volume of timber scheduled for sale from state-owned lands during a planning decade as calculated by the department and approved by the board.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20537[2003 c 334 § 537]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c159.pdf?cite=1987%20c%20159%20§%202[1987 c 159 § 2]; ]

== 79.10.310 - "Sustained yield plans" defined.
"Sustained yield plans" as used in RCW 79.10.070, 79.44.003, and this chapter shall mean management of the forest to provide harvesting on a continuing basis without major prolonged curtailment or cessation of harvest.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20536[2003 c 334 § 536]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c234.pdf?cite=1971%20ex.s.%20c%20234%20§%203[1971 ex.s. c 234 § 3]; ]

== 79.10.320 - Sustainable harvest program.
The department shall manage the state-owned lands under its jurisdiction which are primarily valuable for the purpose of growing forest crops on a sustained yield basis insofar as compatible with other statutory directives. To this end, the department shall periodically adjust the acreages designated for inclusion in the sustained yield management program and calculate a sustainable harvest level.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20538[2003 c 334 § 538]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c159.pdf?cite=1987%20c%20159%20§%203[1987 c 159 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c234.pdf?cite=1971%20ex.s.%20c%20234%20§%204[1971 ex.s. c 234 § 4]; ]

== 79.10.330 - Arrearages—End of decade.
If an arrearage exists at the end of any planning decade, the department shall conduct an analysis of alternatives to determine the course of action regarding the arrearage which provides the greatest return to the trusts based upon economic conditions then existing and forecast, as well as impacts on the environment of harvesting the additional timber. The department shall offer for sale the arrearage in addition to the sustainable harvest level adopted by the board of natural resources for the next planning decade if the analysis determined doing so will provide the greatest return to the trusts.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c159.pdf?cite=1987%20c%20159%20§%204[1987 c 159 § 4]; ]

== 79.10.340 - Sustainable harvest sale.
The board of natural resources shall offer for sale the sustainable harvest as identified in the 1984-1993 forestland management program, or as subsequently revised. In the event that decisions made by entities other than the department cause a decrease in the sustainable harvest the department shall offer additional timber sales from state-managed lands.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c424.pdf?cite=1989%20c%20424%20§%209[1989 c 424 § 9]; ]

== 79.10.400 - Cooperative agreements.
The department with regard to state forestlands and state lands is hereby authorized to enter into cooperative agreements with the United States of America, Indian tribes, and private owners of timberland providing for coordinated forest management, including time, rate, and method of cutting timber and method of silvicultural practice on a sustained yield unit.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20510[2003 c 334 § 510]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c128.pdf?cite=1988%20c%20128%20§%2067[1988 c 128 § 67]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c123.pdf?cite=1941%20c%20123%20§%201[1941 c 123 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c130.pdf?cite=1939%20c%20130%20§%201[1939 c 130 § 1]; Rem. Supp. 1941 § 7879-11; ]

== 79.10.410 - Cooperative units.
The department is hereby authorized and directed to determine, define, and declare informally the establishment of a sustained yield unit, comprising the land area to be covered by any such cooperative agreement and include therein such other lands as may be later acquired by the department and included under the cooperative agreement.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20511[2003 c 334 § 511]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c128.pdf?cite=1988%20c%20128%20§%2068[1988 c 128 § 68]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c130.pdf?cite=1939%20c%20130%20§%202[1939 c 130 § 2]; RRS § 7879-12; ]

== 79.10.420 - Limitations on agreements.
The department shall agree that the cutting from combined national forestlands, state forestlands, and state lands will be limited to the sustained yield capacity of these lands in the management unit as determined by the contracting parties and approved by the board for state forestlands and by the department for state lands. Cooperation with the private contracting party or parties shall be contingent on limitation of production to a specified amount as determined by the contracting parties and approved by the board for state forestlands and by the department for state lands and shall comply with the other conditions and requirements of such cooperative agreement.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20512[2003 c 334 § 512]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c128.pdf?cite=1988%20c%20128%20§%2069[1988 c 128 § 69]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c130.pdf?cite=1939%20c%20130%20§%203[1939 c 130 § 3]; RRS § 7879-13; ]

== 79.10.430 - Easements—Life of agreements.
The private contracting party or parties shall enjoy the right of easement over state forestlands and state lands included under said cooperative agreement for railway, road, and other uses necessary to the carrying out of the agreement. This easement shall be only for the life of the cooperative agreement and shall be granted without charge with the provision that payment shall be made for all merchantable timber cut, removed, or damaged in the use of such easement, payment to be based on the contract stumpage price for timber of like value and species and to be made within thirty days from date of cutting, removal, and/or damage of such timber and appraisal thereof by the department.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20513[2003 c 334 § 513]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c128.pdf?cite=1988%20c%20128%20§%2070[1988 c 128 § 70]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c123.pdf?cite=1941%20c%20123%20§%202[1941 c 123 § 2]; Rem. Supp. 1941 § 7879-13a; ]

== 79.10.440 - Sale agreements.
During the period when any such cooperative agreement is in effect, the timber on the state forestlands and state lands which the department determines shall be included in the sustained yield unit may, from time to time, be sold at not less than its appraised value as approved by the department for state lands and the board for state forestlands, due consideration being given to existing forest conditions on all lands included in the cooperative management unit and such sales may be made in the discretion of the department and the contracting party or parties in the cooperative sustained yield agreement. These sale agreements shall contain such provisions as are necessary to effectually permit the department to carry out the purpose of this section and in other ways afford adequate protection to the public interests involved.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20514[2003 c 334 § 514]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c128.pdf?cite=1988%20c%20128%20§%2071[1988 c 128 § 71]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c130.pdf?cite=1939%20c%20130%20§%204[1939 c 130 § 4]; RRS § 7879-14; ]

== 79.10.450 - Minimum price.
The sale of timber upon state forestland and state land within such sustained yield unit or units shall be made for not less than the appraised value thereof as heretofore provided for the sale of timber on state lands. However, if in the judgment of the department, it is to the best interests of the state to do so, the timber or any such sustained yield unit or units may be sold on a stumpage or scale basis for a price per thousand not less than the appraised value thereof. The department shall reserve the right to reject any and all bids if the intent of this chapter will not be carried out. Permanency of local communities and industries, prospects of fulfillment of contract requirements, and financial position of the bidder shall all be factors included in this decision.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20515[2003 c 334 § 515]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c128.pdf?cite=1988%20c%20128%20§%2072[1988 c 128 § 72]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c130.pdf?cite=1939%20c%20130%20§%205[1939 c 130 § 5]; RRS § 7879-15; ]

== 79.10.460 - Contracts—Requirements.
A written contract shall be entered into with the successful bidder which shall fix the time when logging operations shall be commenced and concluded and require monthly payments for timber removed as soon as scale sheets have been tabulated and the amount of timber removed during the month determined, or require payments monthly in advance at the discretion of the board or the department. The board and the department shall designate the price per thousand to be paid for each species of timber and shall provide for supervision of logging operations, the methods of scaling and report, and shall require the purchaser to comply with all laws of the state of Washington with respect to fire protection and logging operation of the timber purchased; and shall contain such other provisions as may be deemed advisable.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20516[2003 c 334 § 516]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c130.pdf?cite=1939%20c%20130%20§%206[1939 c 130 § 6]; RRS § 7879-16; ]

== 79.10.470 - Transfer or assignment of contracts.
No transfer or assignment by the purchaser shall be valid unless the transferee or assignee is acceptable to the department and the transfer or assignment approved by it in writing.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20517[2003 c 334 § 517]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c128.pdf?cite=1988%20c%20128%20§%2073[1988 c 128 § 73]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c123.pdf?cite=1941%20c%20123%20§%203[1941 c 123 § 3]; Rem. Supp. 1941 § 7879-16a; ]

== 79.10.480 - Performance bond—Cash deposit.
The purchaser shall, at the time of executing the contract, deliver a performance bond or sureties acceptable in regard to terms and amount to the department, but such performance bond or sureties shall not exceed ten percent of the estimated value of the timber purchased computed at the stumpage price and at no time shall exceed a total of fifty thousand dollars. The purchaser shall also be required to make a cash deposit equal to twenty percent of the estimated value of the timber purchased, computed at the stumpage bid. Upon failure of the purchaser to comply with the terms of the contract, the performance bond or sureties may be forfeited to the state upon order of the department.

At no time shall the amount due the state for timber actually cut and removed exceed the amount of the deposit as set forth in this section. The amount of the deposit shall be returned to the purchaser upon completion and full compliance with the contract by the purchaser, or it may, at the discretion of the purchaser, be applied on final payment on the contract.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20518[2003 c 334 § 518]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c128.pdf?cite=1988%20c%20128%20§%2074[1988 c 128 § 74]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c123.pdf?cite=1941%20c%20123%20§%204[1941 c 123 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c130.pdf?cite=1939%20c%20130%20§%207[1939 c 130 § 7]; Rem. Supp. 1941 § 7879-17; ]

== 79.10.500 - Recreational trail policy—Development.
. The department must develop and implement, through an inclusive stakeholder process managed by the department, an official recreational trail policy that is consistent with this section and the management mandate of the department.

. [Empty]
.. The recreational trail policy developed by the department under this section must provide that recreational trails be developed and managed in a manner that ensures the following principles are satisfied:

... Causing the least impact to the land;

... Providing environmental and water quality protection; and

... Maintaining the lowest construction and maintenance costs that are reasonable.

.. The department should use trail standards developed by the United States forest service as primary guidelines for trail construction and maintenance. However, the department must develop its own construction standards and best management practices when the primary guidelines are deemed insufficient or inapplicable.

.. Trails developed or maintained consistent with a recreational trail policy developed under this section must comply with Title 79 RCW and all applicable state laws and rules, including those administered by the department of ecology.

.. After developing the recreational trail policy required in this section, and when developing or assessing recreational trail systems, the department should evaluate existing nondesignated trails for compliance with trail standards and incorporate those trails, when compliant and consistent with the standards, into comprehensive recreational management plans.

. When appropriate, the department should incorporate public input on new and existing trail systems, and if deemed appropriate, the department should support formal or informal public forums to allow members of the local community to share concerns and ideas or organize themselves for volunteer trail maintenance.

. [Empty]
.. A recreational trail policy developed by the department under this section must provide for the department to enter into a hold harmless agreement with all volunteers coordinating with the department under the policy or enter into other agreements that limit the department's liability from the actions of volunteers.

.. Whenever volunteers or volunteer organizations are authorized to perform activities or carry out projects under this subsection, the volunteers or members of the organizations may not be considered employees or agents of the department and the department is not subject to any liability whatsoever arising out of volunteer activities or projects. The liability of the department to volunteers and members of the volunteer organizations is limited in the same manner as provided for in RCW 4.24.210.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=2014%20c%20114%20§%202[2014 c 114 § 2]; ]

== 79.10.510 - Recreational facilities and trails—Local government permits.
The department should work with representatives of local governments to find efficiencies in gaining local government permits for the development and maintenance of recreational facilities and trails. If barriers to permitting efficiencies require legislative action to overcome, then the department must provide options for solutions to the appropriate committees of the legislature.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=2014%20c%20114%20§%203[2014 c 114 § 3]; ]

== 79.10.520 - Prioritizing investments on forest health treatments.
. [Empty]
.. Subject to the availability of amounts appropriated for this specific purpose, the department shall, to the extent feasible given all applicable trust responsibilities, develop and implement a policy for prioritizing investments on forest health treatments to protect state lands and state forestlands, as those terms are defined in RCW 79.02.010, to: (i) Reduce wildfire hazards and losses from wildfire; (ii) reduce insect infestation and disease; and (iii) achieve cumulative impact of improved forest health and resilience at a landscape scale.

.. The prioritization policy in (a) of this subsection must consider whether state lands and state forestlands are within an area that is subject to a forest health hazard warning or order pursuant to RCW 76.06.180.

. [Empty]
.. The department's prioritization of state lands and state forestlands must be based on an evaluation of the economic and noneconomic value of:

... Timber or other commercial forest products removed during any mechanical treatments;

... Timber or other commercial forest products likely to be spared from damage by wildfire;

... Homes, structures, agricultural products, and public infrastructure likely to be spared from damage by wildfire;

... Impacts to recreation and tourism; and

.. Ecosystem services such as water quality, air quality, or carbon sequestration.

.. The department's evaluation of economic values may rely on heuristic techniques.

. The definitions in this subsection apply throughout this section and RCW 79.10.530 and 79.64.130 unless the context clearly requires otherwise.

.. "Forest health" has the same meaning as defined in RCW 76.06.020.

.. "Forest health treatment" or "treatment" means actions taken by the department to restore forest health including, but not limited to, sublandscape assessment and project planning, site preparation, reforestation, mechanical treatments including timber harvest, road realignment for fire protection and aquatic improvements, and prescribed burning.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1711-S2.SL.pdf?cite=2017%20c%20248%20§%201[2017 c 248 § 1]; ]

== 79.10.530 - Identification of lands for forest health treatment—Prioritized list—Report to the legislature.
. [Empty]
.. Subject to the availability of amounts appropriated for this specific purpose, consistent with the prioritization policy developed pursuant to RCW 79.10.520, and to the extent feasible given all applicable trust responsibilities, the department must identify areas of state lands and state forestlands that would benefit from forest health treatments at the landscape level for the next twenty years, and ones that would benefit the most during the following six years, and prioritize and list specific lands for treatment during the subsequent biennium. The department shall update this list by November 15th of each even-numbered year.

.. To expedite initial treatments under chapter 248, Laws of 2017, for the 2017-2019 biennium the department may prioritize and, if funds are appropriated for this purpose, address lands for treatment that are currently identified by the department as pilot treatment projects.

. In order to develop a prioritized list that evaluates forest health treatments at a landscape scale, the department should consult with and take into account the land management plans and activities of nearby landowners, if available, including federal agencies, other state agencies, local governments, tribes, and private property owners, in addition to any statewide assessments done by the department. The department may include federally, locally, or privately managed lands on the list. The department may fund treatment on these lands provided that the treatments are funded with nontrust funds, and provided that the treatments produce a net benefit to the health of state lands and state forestlands.

. By December 1st of each even-numbered year, the department must submit a report to the legislature consistent with the requirements of RCW 43.01.036, to the office of financial management, and to the board of natural resources. The report must include:

.. A brief summary of the department's progress towards treating the state lands and state forestlands included on the preceding biennium's prioritization list;

.. A list of lands prioritized for forest health treatments in the next biennium, including state lands and state forestlands prioritized for treatment pursuant to subsection (1) of this section;

.. Recommended funding amounts required to carry out the treatment activities for the next biennium, including a summary of potential nontimber revenue sources that could finance specific forest health treatments pursuant to RCW 79.10.520, including but not limited to ecosystem services such as water and carbon sequestration as well as insurance and fire mitigation; and

.. A summary of trends in forest health conditions.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1711-S2.SL.pdf?cite=2017%20c%20248%20§%202[2017 c 248 § 2]; ]

