= 79.145 - Marine plastic debris.
:toc:

== 79.145.001 - Intent—2005 c 155.
See RCW 79.105.001.

[ ]

== 79.145.010 - Intent.
The legislature finds that the public health and safety is threatened by an increase in the amount of plastic garbage being deposited in the waters and on the shores of the state. To address this growing problem, the commissioner appointed the marine plastic debris task force which presented a state action plan in October 1988. It is necessary for the state of Washington to implement the action plan in order to:

. Cleanup and prevent further pollution of the state's waters and aquatic lands;

. Increase public awareness;

. Coordinate federal, state, local, and private efforts;

. Foster the stewardship of the aquatic lands of the state.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1491-S.SL.pdf?cite=2005%20c%20155%20§%20901[2005 c 155 § 901]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c23.pdf?cite=1989%20c%2023%20§%201[1989 c 23 § 1]; ]

== 79.145.020 - Definitions.
As used in this chapter:

. "Department" means the department of natural resources.

. "Action plan" means the marine plastic debris action plan of October 1988 as presented to the commissioner by the marine plastic debris task force.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1491-S.SL.pdf?cite=2005%20c%20155%20§%20902[2005 c 155 § 902]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c23.pdf?cite=1989%20c%2023%20§%202[1989 c 23 § 2]; ]

== 79.145.030 - Coordinating implementation—Rules.
The department shall have the authority to coordinate implementation of the action plan with appropriate state agencies including the parks and recreation commission and the departments of ecology and fish and wildlife. The department is authorized to adopt, in consultation with affected agencies, the necessary rules to provide for the cleanup and to prevent pollution of the waters of the state and aquatic lands by plastic and other marine debris.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1491-S.SL.pdf?cite=2005%20c%20155%20§%20903[2005 c 155 § 903]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2590.SL.pdf?cite=1994%20c%20264%20§%2065[1994 c 264 § 65]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c23.pdf?cite=1989%20c%2023%20§%203[1989 c 23 § 3]; ]

== 79.145.040 - Agreements with other entities.
The department may enter into intergovernmental agreements with federal or state agencies and agreements with private parties deemed necessary by the department to carry out the provisions of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c23.pdf?cite=1989%20c%2023%20§%204[1989 c 23 § 4]; ]

== 79.145.050 - Employees—Information clearinghouse contracts.
The department is the designated agency to coordinate implementation of the action plan and is authorized to hire such employees as are necessary to coordinate the action plan among state and federal agencies, the private sector, and interested public groups and organizations. The department is authorized to contract, through an open bidding process, with interested parties to act as the information clearinghouse for marine plastic debris related issues.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1491-S.SL.pdf?cite=2005%20c%20155%20§%20904[2005 c 155 § 904]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c23.pdf?cite=1989%20c%2023%20§%205[1989 c 23 § 5]; ]

== 79.145.060 - Grants, funds, or gifts.
The department is authorized to accept, receive, disburse, and administer grants or funds or gifts from any source including private individuals, public entities, and the federal government to supplement the funds appropriated to carry out the purposes of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1491-S.SL.pdf?cite=2005%20c%20155%20§%20905[2005 c 155 § 905]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c23.pdf?cite=1989%20c%2023%20§%206[1989 c 23 § 6]; ]

