= 53.19 - Personal service contracts.
:toc:

== 53.19.005 - Intent.
The legislature hereby establishes a policy of open competition for all personal service contracts entered into by port districts unless specifically exempted under this chapter. It is further the intent to provide differentiation between the competitive procurement procedures for personal and professional services contracts.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3274-S2.SL.pdf?cite=2008%20c%20130%20§%205[2008 c 130 § 5]; ]

== 53.19.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Commission" means the elected oversight body of an individual port.

. "Competitive solicitation" means a documented formal process providing an equal and open opportunity to qualified parties and culminating in a selection based on criteria, in which criteria other than price may be the primary basis for consideration. The criteria may include such factors as the consultant's fees or costs, ability, capacity, experience, reputation, responsiveness to time limitations, responsiveness to solicitation requirements, quality of previous performance, and compliance with statutes and rules relating to contracts or services.

. "Consultant" means an independent individual or firm contracting with a port to perform a service or render an opinion or recommendation according to the consultant's methods and without being subject to the control of the port except as to the result of the work. The port monitors progress under the contract and authorizes payment.

. "Emergency" means a set of unforeseen circumstances beyond the control of the port that either:

.. Present a real, immediate threat to the proper performance of essential functions; or

.. May result in material loss or damage to property, bodily injury, or loss of life if immediate action is not taken.

. "Evidence of competition" means documentation demonstrating that the port has solicited responses from multiple firms in selecting a consultant.

. "Personal service" means professional or technical expertise provided by a consultant to accomplish a specific study, project, task, or other work statement which may not reasonably be required in connection with a public works project meeting the definition in RCW 39.04.010(4). "Personal service" does not include purchased services as defined under subsection (8) of this section or professional services procured using the competitive selection requirements in chapter 39.80 RCW.

. "Personal service contract" means an agreement, or any amendment thereto, with a consultant for the rendering of personal services to the port.

. "Purchased services" means services provided by a vendor to accomplish routine, continuing, and necessary functions. "Purchased services" includes, but is not limited to, services for equipment maintenance and repair; operation of a physical plant; security; computer hardware and software maintenance; data entry; key punch services; and computer time-sharing, contract programming, and analysis.

. "Sole source" means a consultant providing professional or technical expertise of such a unique nature that the consultant is clearly and justifiably the only practicable source to provide the service. The justification shall be based on the uniqueness of the service, sole availability at the location required, or warranty or defect correction service obligations of the consultant.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3274-S2.SL.pdf?cite=2008%20c%20130%20§%206[2008 c 130 § 6]; ]

== 53.19.020 - Exceptions.
All personal service contracts shall be entered into pursuant to competitive solicitation, except for:

. Emergency contracts;

. Sole source contracts;

. Contract amendments;

. Contracts between a consultant and a port of less than fifty thousand dollars. However, contracts of fifty thousand dollars or greater but less than two hundred thousand dollars shall have documented evidence of competition. Ports shall not structure contracts to evade these requirements; and

. Other specific contracts or classes or groups of contracts exempted from the competitive solicitation process by the commission when it has been determined that a competitive solicitation process is not appropriate or cost-effective.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3274-S2.SL.pdf?cite=2008%20c%20130%20§%207[2008 c 130 § 7]; ]

== 53.19.030 - Emergency contracts.
Emergency contracts shall be filed with the commission and made available for public inspection within seven working days following the commencement of work or execution of the contract, whichever occurs first. Documented justification for emergency contracts shall be provided to the commission when the contract is filed.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3274-S2.SL.pdf?cite=2008%20c%20130%20§%208[2008 c 130 § 8]; ]

== 53.19.040 - Sole source contracts.
. Sole source contracts shall be filed with the commission and made available for public inspection prior to the proposed starting date of the contract. Documented justification for sole source contracts shall be provided to the commission when the contract is filed. For sole source contracts of fifty thousand dollars or more, documented justification shall include evidence that the port attempted to identify potential consultants.

. The commission shall ensure that the costs, fees, or rates negotiated in filed sole source contracts of fifty thousand dollars or more are reasonable.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3274-S2.SL.pdf?cite=2008%20c%20130%20§%209[2008 c 130 § 9]; ]

== 53.19.050 - Compliance with chapter—Civil penalties—Auditing—Prosecution.
A port commissioner or employee shall not expend any funds for personal service contracts subject to this chapter unless the port has complied with the competitive procurement and other requirements of this chapter. The port commissioner or employee executing the personal service contracts is responsible for compliance with the requirements of this chapter. Willful and intentional failure to comply with the requirements of this chapter subjects the port commissioner or employee to a civil penalty in the amount of three hundred dollars. A consultant who knowingly violates this chapter in seeking or performing work under a personal services contract is subject to a civil penalty of three hundred dollars or twenty-five percent of the amount of the contract, whichever is greater. The state auditor is responsible for auditing violations of this chapter through its regular financial and accountability audits. The attorney general is responsible for prosecuting violations of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3274-S2.SL.pdf?cite=2008%20c%20130%20§%2010[2008 c 130 § 10]; ]

== 53.19.060 - Changes in scope of work—Amendments to contracts.
. Substantial changes in the scope of work specified in the contract or which are substantial additions to the scope of work specified in the formal solicitation document shall be submitted to the commission for a determination as to whether the change warrants the work to be awarded as a new contract.

. An amendment or amendments to personal service contracts, if the value of the amendment or amendments, whether singly or cumulatively, exceeds fifty percent of the value of the original contract must be filed with the commission and made available for public inspection prior to the proposed starting date of services under the amendments.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3274-S2.SL.pdf?cite=2008%20c%20130%20§%2011[2008 c 130 § 11]; ]

== 53.19.070 - Application of chapter restricted.
This chapter does not apply to:

. Contracts specifying a fee of less than fifty thousand dollars;

. Contracts awarded to companies that furnish a service where the tariff is established by the utilities and transportation commission or other public entity;

. Intergovernmental agreements awarded to any governmental entity, whether federal, state, or local and any department, division, or subdivision thereof;

. Contracts awarded for services to be performed for a standard fee, when the standard fee is established by the contracting agency or any other governmental entity and a like contract is available to all qualified applicants;

. Contracts for services that are necessary to the conduct of collaborative research if prior approval is granted by the funding source;

. Contracts for professional services which are entered into under chapter 39.80 RCW; and

. Contracts for the employment of expert witnesses for the purposes of litigation or legal services to supplement the expertise of port staff.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3274-S2.SL.pdf?cite=2008%20c%20130%20§%2012[2008 c 130 § 12]; ]

== 53.19.080 - Management of contracts—Guidelines.
. The municipal research [and] services center, in cooperation with the Washington public ports association, shall develop guidelines for the effective and efficient management of personal service contracts by all ports. The guidelines must, at a minimum, include:

.. Accounting methods, systems, measures, and principles to be used by ports and consultants;

.. Precontract procedures for selecting potential consultants based on their qualifications and ability to perform;

.. Incorporation of performance measures and measurable benchmarks in contracts, and the use of performance audits;

.. Uniform contract terms to ensure contract performance and compliance with port, state, and federal standards;

.. Proper payment and reimbursement methods to ensure that the port receives full value for taxpayer moneys, including cost settlements and cost allowance;

.. Postcontract procedures, including methods for recovering improperly spent or overspent moneys for disallowance and adjustment;

.. Adequate contract remedies and sanctions to ensure compliance;

.. Monitoring, fund tracking, risk assessment, and auditing procedures and requirements;

.. Financial reporting, record retention, and record access procedures and requirements;

.. Procedures and criteria for terminating contracts for cause or otherwise; and

.. Any other subject related to effective and efficient contract management.

. The municipal research [and] services center shall submit a status report on the guidelines required by subsection (1) of this section to the governor and the appropriate standing committees of the legislature no later than December 1, 2008.

. The Washington public ports association shall publish a guidebook for use by ports containing the guidelines developed under subsection (1) of this section.

. The municipal research [and] services center and the Washington public ports association shall each make the guidelines available on their web sites.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3274-S2.SL.pdf?cite=2008%20c%20130%20§%2013[2008 c 130 § 13]; ]

== 53.19.090 - Commission policies—Ports to follow.
. A port entering into or amending personal service contracts shall follow the policies adopted by the commission, which shall be based on guidelines developed pursuant to RCW 53.19.080.

. This section applies to ports entering into or renewing contracts after January 1, 2010.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3274-S2.SL.pdf?cite=2008%20c%20130%20§%2014[2008 c 130 § 14]; ]

== 53.19.100 - Training course.
The Washington public ports association shall provide a training course for port personnel responsible for executing and managing personal service contracts. The course must contain training on effective and efficient contract management under the guidelines established under RCW 53.19.080. Port districts shall require port employees responsible for executing or managing personal service contracts to complete the training course to the satisfaction of the commission.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3274-S2.SL.pdf?cite=2008%20c%20130%20§%2015[2008 c 130 § 15]; ]

