= 53.20 - Harbor improvements.
:toc:

== 53.20.010 - Adoption of harbor improvement plan.
It shall be the duty of the port commission of any port district, before creating any improvements hereunder, to adopt a comprehensive scheme of harbor improvement in the port district, after a public hearing thereon, of which notice shall be published once a week for two consecutive weeks in a newspaper of general circulation in the port district, and no expenditure for the carrying on of any harbor improvements shall be made by the port commission other than the necessary salaries, including engineers, clerical and office expenses of the port district, and the cost of engineering, surveying, preparation and collection of data necessary for the making and adoption of a general scheme of harbor improvements in the port district, unless and until the comprehensive scheme of harbor improvement has been so officially adopted by the port commission.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c469.pdf?cite=1985%20c%20469%20§%2051[1985 c 469 § 51]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c166.pdf?cite=1943%20c%20166%20§%203[1943 c 166 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c62.pdf?cite=1913%20c%2062%20§%206[1913 c 62 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c92.pdf?cite=1911%20c%2092%20§%206[1911 c 92 § 6]; Rem. Supp. 1943 § 9694; ]

== 53.20.020 - Improvement to follow plans adopted.
When such general plans shall have been adopted or approved, as aforesaid, every improvement to be made by said commission shall be made substantially in accordance therewith unless and until such general plans shall have been officially changed by the port commission after a public hearing thereon, of which at least ten days' notice shall be published in a newspaper in general circulation in such port district.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c24.pdf?cite=1947%20c%2024%20§%201[1947 c 24 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c62.pdf?cite=1913%20c%2062%20§%207[1913 c 62 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c92.pdf?cite=1911%20c%2092%20§%207[1911 c 92 § 7]; Rem. Supp. 1947 § 9695; ]

== 53.20.030 - Improvements—Ownership of.
No improvements shall be acquired or constructed, by the port district, unless such improvements shall, when completed, be the property of such port district, the county in which such port district is located, any city within such port district, the state of Washington or the United States of America, and the funds of such port district may be expended in the acquirement or construction of any harbor improvement embraced in such general plan adopted as in this chapter provided in conjunction with the county in which such port district is located, any city in such port district, the state of Washington or the United States of America, or all or any of them.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c30.pdf?cite=1979%20ex.s.%20c%2030%20§%209[1979 ex.s. c 30 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c62.pdf?cite=1913%20c%2062%20§%208[1913 c 62 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c92.pdf?cite=1911%20c%2092%20§%208[1911 c 92 § 8]; RRS § 9696; ]

== 53.20.040 - Fifty percent of cost of local improvement may be paid from general fund.
Whenever any improvement shall be ordered, payment for which shall be made in part from assessments against property specially benefited, not more than fifty percent of the cost thereof shall ever be borne by the entire port district, nor shall any sum be contributed by it to any improvement acquired or constructed with or by any other body, exceed [exceeding] such amount, unless a majority vote of the electors of the port district shall consent to or ratify the making of such expenditure.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c92.pdf?cite=1911%20c%2092%20§%2011[1911 c 92 § 11]; RRS § 9698; ]

== 53.20.050 - Local improvements upon majority petition.
Whenever a petition signed by one hundred freeholders in the district to be therein described, shall be filed with the port commission, asking that any portion of the general plan adopted be ordered, and defining the boundaries of a local improvement district to be assessed in whole or in part to pay the cost thereof, it shall be the duty of the port commission to fix a date for hearing on the petition, after which it may alter the boundaries of the proposed district and prepare and adopt detail plans of any such local improvement, declare the estimated cost thereof, what proportion of the cost shall be borne by the proposed local improvement district, and what proportion of the cost, if any, but in any event not to exceed fifty percent, shall be borne by the entire port district. At any time within two years thereafter, upon petition of the owners of a majority of the lands in the proposed local improvement district, fixed by the port commission, as shown in the office of the auditor of the county, asking that the improvement be ordered, the port commission shall forthwith by resolution order the improvement, provide the general funds of the port district to be applied thereto, acquire all lands necessary therefor, pay all damages caused thereby, and commence in the name of the port district such eminent domain proceedings and supplemental assessment or reassessment proceedings to pay all eminent domain awards as may be necessary to entitle the port district to proceed with such work, and shall thereafter proceed with the work, and shall make and file with the county treasurer its roll levying special assessments in the amount to be paid by special assessment against the property situated within the local improvement district in proportion to the special benefits to be derived by the property in the local improvement district from the improvement. Before the approval of the roll a notice shall be published once a week for two consecutive weeks in one or more newspapers of general circulation in the local improvement district, stating that the roll is on file and open to inspection in the office of the clerk of the port commission, and fixing a time not less than fifteen nor more than thirty days from the date of the first publication of the notice within which protests must be filed with the clerk of the port commission against any assessments shown thereon, and fixing a time when a hearing shall be held by the commission on the protests. After the hearing the port commission may alter any and all assessments shown on the roll and may then by resolution approve the same, but in the event of any assessment being raised a new notice similar to the first notice shall be given, after which final approval of the roll may be made by the port commission. Any person feeling aggrieved by any such assessments shall perfect an appeal to the superior court of the county within ten days after the approval in the manner now provided by law for appeals from assessments levied by cities of the first class in this state. Engineering and office expenses in all cases shall be borne by the general district.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c469.pdf?cite=1985%20c%20469%20§%2052[1985 c 469 § 52]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c92.pdf?cite=1911%20c%2092%20§%2010[1911 c 92 § 10]; RRS § 9697; ]

