= 53.29 - Trade center act.
:toc:

== 53.29.010 - Declaration of purpose.
It is declared to be the finding of the legislature of the state of Washington that:

. The servicing functions and activities connected with the oceanborne and overseas airborne trade and commerce of port districts, including customs clearance, shipping negotiations, cargo routing, freight forwarding, financing, insurance arrangements and other similar transactions which are presently performed in various, scattered physical and electronic locations in the districts should be centralized to provide for more efficient and economical transportation of persons and more efficient and economical physical or electronic facilities and services for the exchange and buying, selling and transportation of commodities and other property in world trade and commerce;

. Unification, at a single, centrally located physical or electronic site of a facility of commerce, i.e., a trade center, accommodating the functions and activities described in subsection (1) of this section and the appropriate governmental, administrative and other services connected with or incidental to transportation and security of persons and property and the promotion and protection of port commerce, and providing a central locale for exhibiting, and otherwise promoting the exchange and buying and selling of commodities and property in world trade and commerce, will materially assist in preserving the material and other benefits of a prosperous port community;

. The undertaking of the aforesaid unified trade center project by a port district or the Washington public ports association has the single object of preserving, and will aid in the promotion, security, and preservation of, the economic well-being of port districts and the state of Washington and is found and determined to be a public purpose.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2450.SL.pdf?cite=2002%20c%20145%20§%201[2002 c 145 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c425.pdf?cite=1989%20c%20425%20§%205[1989 c 425 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c56.pdf?cite=1967%20c%2056%20§%201[1967 c 56 § 1]; ]

== 53.29.015 - Definitions.
The definitions in this section apply throughout RCW 53.29.020 and 53.29.030 unless the context clearly requires otherwise.

. "Person" has the same meaning as defined in the electronic signatures in global and national commerce act (15 U.S.C. Sec. 7006 (8)) in effect on June 13, 2002.

. "Transaction" has the same meaning as defined in the electronic signatures in global and national commerce act (15 U.S.C. Sec. 7006 (13)) in effect on June 13, 2002. However, "transaction" also includes actions relating to governmental affairs.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2450.SL.pdf?cite=2002%20c%20145%20§%204[2002 c 145 § 4]; ]

== 53.29.020 - Power to establish trade centers—Facilities authorized.
In addition to all other powers granted to port districts, any such district, the Washington public ports association, or the federation of Washington ports as described in RCW 53.06.070 may acquire, as provided for other port properties in RCW 53.08.010, construct, develop, operate and maintain all land or other property interests, buildings, structures or other improvements, and may participate in transactions necessary to provide, electronically or otherwise, facilities or to exercise powers or purposes of a trade center including but not limited to the following electronic or physical facilities:

. A facility consisting of one or more structures, improvements and areas for the centralized accommodation of public and private agencies, persons and facilities in order to afford improved service to waterborne and airborne import and export trade and commerce;

. Facilities for the promotion of such import and export trade and commerce, inspection, testing, display and appraisal facilities, foreign trade zones, terminal and transportation facilities, office meeting rooms, auditoriums, libraries, language translation services, storage, warehouse, marketing and exhibition facilities, facilities for federal, state, county and other municipal and governmental agencies providing services relating to the foregoing and including, but not being limited to, customs houses and customs stores, and other incidental facilities and accommodations.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2450.SL.pdf?cite=2002%20c%20145%20§%202[2002 c 145 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c425.pdf?cite=1989%20c%20425%20§%206[1989 c 425 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c56.pdf?cite=1967%20c%2056%20§%202[1967 c 56 § 2]; ]

== 53.29.030 - Cooperation with other entities—Annual service fee for support of local government.
. In carrying out the powers authorized by this chapter and chapter 53.06 RCW, port districts and the Washington public ports association are authorized to cooperate, act, and invest jointly with other public and private agencies and persons, including, but not limited to, the federal government, the state, other ports and municipal corporations, other states and their political subdivisions, and private nonprofit trade promotion groups and associate development organizations.

. Port districts operating trade center buildings or operating association or federation trade centers, shall pay an annual service fee to the county treasurer wherein the center is located for municipal services rendered to the trade center building. The measure of such service fee shall be equal to three percent of the gross rentals received from the nongovernmental tenants of such trade center building. Such proceeds shall be distributed by the county treasurer as follows: Forty percent to the school district, forty percent to the city, and twenty percent to the county wherein the center is located: PROVIDED, That if the center is located in an unincorporated area, twenty percent shall be allocated to the fire district, forty percent to the school district, and forty percent to the county.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2450.SL.pdf?cite=2002%20c%20145%20§%203[2002 c 145 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c425.pdf?cite=1989%20c%20425%20§%207[1989 c 425 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c56.pdf?cite=1967%20c%2056%20§%203[1967 c 56 § 3]; ]

== 53.29.900 - Short title—Liberal construction—Powers cumulative.
This chapter, which may be known and cited as the "Trade Center Act", shall be liberally construed, its purpose being to provide port districts, and their related association and federation, with additional powers to provide trade centers and to promote and encourage trade, tourism, travel, and economic development in a coordinated and efficient manner through the ports of the state of Washington. The powers herein granted shall be in addition to all others granted to port districts.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c425.pdf?cite=1989%20c%20425%20§%208[1989 c 425 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c56.pdf?cite=1967%20c%2056%20§%204[1967 c 56 § 4]; ]

