= 53.35 - Budgets.
:toc:

== 53.35.010 - Preliminary budget.
On or before the 15th day of September of each year each port commission shall prepare a preliminary budget of the port district for the ensuing fiscal year showing the estimated expenditures and the anticipated available funds from which all expenditures are to be paid.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c159.pdf?cite=1959%20c%20159%20§%201[1959 c 159 § 1]; ]

== 53.35.020 - Publication of notice of preliminary budget and hearing.
Following the preparation of the preliminary budget, the port commission shall publish a notice stating that the preliminary budget of the port district has been prepared and placed on file at the office of the port district; that a copy thereof may be obtained by any taxpayer at an address set forth in the notice; that the commission will meet at a date, hour and place set forth in the notice, such date to be not earlier than September 15th and not later than the first Tuesday following the first Monday in October, for the purpose of fixing and adopting the final budget of the port district for the ensuing year. The notice shall be published once each week for two consecutive weeks in a legal newspaper of the district, or if there is none, in any newspaper of general circulation in the county, the first publication to be not less than nine days nor more than twenty days prior to the date of the hearing.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c159.pdf?cite=1959%20c%20159%20§%202[1959 c 159 § 2]; ]

== 53.35.030 - Hearing—Final budget.
On the day set by the notice provided for in RCW 53.35.020 the commission shall meet at the place and hour designated for the purpose of a hearing on the budget and adoption of a final budget. Any person may present objections to the preliminary budget following which the commission shall, by resolution adopt a final budget.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c159.pdf?cite=1959%20c%20159%20§%203[1959 c 159 § 3]; ]

== 53.35.040 - Final budget to be filed with county commissioners.
It shall be the duty of the commissioners of port districts, for the purpose of levying port district taxes, to file with the clerk of the board of county commissioners on or before the Wednesday next following the first Monday in October in each year a certified copy of such final budget which shall specify the amounts to be raised by taxation on the assessed valuation of the property in the port district.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c159.pdf?cite=1959%20c%20159%20§%204[1959 c 159 § 4]; ]

== 53.35.045 - Alternate date for filing final budget.
Notwithstanding any provision of law to the contrary, the board of commissioners of a port district may file with the clerk of the county legislative authority a certified copy of the port district final budget, provided for in RCW 53.35.040, on the first Monday in December. The board of port commissioners may also set other dates relating to the budget process, including but not limited to the dates set in RCW 53.35.010 and 53.35.020 to conform to the alternate date for final budget filing.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c19.pdf?cite=1974%20ex.s.%20c%2019%20§%201[1974 ex.s. c 19 § 1]; ]

== 53.35.050 - Supplemental budgets.
A port commission may adopt by resolution one or more supplemental budgets at any time during the fiscal year. Such supplemental budget shall be adopted only after public hearing. Notice of such hearing shall be given by a single publication of notice of the date, place and hour of the hearing in a legal newspaper of the district, or if there is none, in any newspaper of general circulation in the county, the publication of such notice to be at least five days and not more than fifteen days prior to the hearing date.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c159.pdf?cite=1959%20c%20159%20§%205[1959 c 159 § 5]; ]

== 53.35.060 - Fiscal year.
The fiscal year for a port district shall be the calendar year.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c159.pdf?cite=1959%20c%20159%20§%206[1959 c 159 § 6]; ]

== 53.35.070 - Chapter exclusive method for budgets.
The provisions of this chapter shall constitute the exclusive requirement and authority for the preparation, adoption, certification and filing of port district budgets.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c159.pdf?cite=1959%20c%20159%20§%207[1959 c 159 § 7]; ]

