= 53.44 - Funding and refunding indebtedness—1947 act.
:toc:

== 53.44.010 - Funding and refunding authorized.
The board of commissioners of any port district of the state may fund or refund any of the general bonded indebtedness and/or warrants of the district now or hereafter existing and accrued interest thereon, and may combine various series and/or issues of warrants and/or bonds into a single issue of funding or refunding bonds, by the issuance of general obligation funding or refunding bonds, when the board, by resolution, finds, determines, and declares that such proposed funding or refunding will inure to the benefit and credit of the district and will not result in an increase of the district's indebtedness or in an increase in the rate of interest borne by the indebtedness so funded or refunded. Such funding or refunding may be accomplished by the sale of said funding or refunding bonds or by their exchange for the bonds and/or warrants to be refunded. General obligation bonds of a port district which do not provide for prior redemption, may also be refunded with the consent of the holders thereof. Such bonds shall be issued in accordance with chapter 39.46 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c186.pdf?cite=1984%20c%20186%20§%2042[1984 c 186 § 42]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c239.pdf?cite=1947%20c%20239%20§%201[1947 c 239 § 1]; Rem. Supp. 1947 § 5623-1; ]

== 53.44.030 - Maturities—Payment.
Such funding or refunding bonds shall run for a period of not exceeding twenty years from date thereof. The board may apply to the payment of the funding or refunding bonds and to the prior redemption thereof any other moneys or funds belonging to the district which are legally available for such purpose.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c186.pdf?cite=1984%20c%20186%20§%2043[1984 c 186 § 43]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c239.pdf?cite=1947%20c%20239%20§%203[1947 c 239 § 3]; Rem. Supp. 1947 § 5623-3; ]

