= 53.57 - Port development authority.
:toc:

== 53.57.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Port commission" means a port commission governed by chapter 53.12 RCW of a port district that either singly or jointly creates a port development authority under the provisions of this chapter.

. "Port district" or "port districts" means a port district or port districts that are located in a county with a population of more than eight hundred thousand on July 24, 2015.

. "Port public development authority" or "port development authority" means a port public development authority created by a single port district or jointly created by two port districts in accordance with RCW 53.57.020.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1170-S.SL.pdf?cite=2015%20c%2035%20§%202[2015 c 35 § 2]; ]

== 53.57.020 - Port development authority—Creation—Powers—Joint exercise of authority.
. A port district or two port districts that act jointly in accordance with subsection (3) of this section may by resolution:

.. Create a port development authority solely to manage maritime activities of the port district or districts; and

.. Transfer to any port development authority created under this section, with or without consideration, any funds, real or personal property, property interests, or services.

. Port development authorities created under subsection (1) of this section may:

.. Administer and execute federal grants or programs;

.. Receive and administer private funds, goods, or services for any lawful public purpose related to maritime activities of the port district or districts; and

.. Perform any lawful public purpose or public function related to maritime activities of the port district or districts, including exercise any powers of the port district or districts that created the port development authority, subject to limitations provided in this chapter.

. Two port districts, each located in a county with a population of more than eight hundred thousand on July 24, 2015, may jointly exercise the authority provided in this section under an agreement for joint or cooperative action executed in accordance with the interlocal cooperation act, chapter 39.34 RCW.

. Any resolution to create a port development authority that is adopted by a port district under this section must limit the liability of the port development authority to the assets and property of the port development authority.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1170-S.SL.pdf?cite=2015%20c%2035%20§%203[2015 c 35 § 3]; ]

== 53.57.030 - Governance—Organization—Management authority.
. The affairs, operations, and funds of a port development authority must be governed by the port district or districts that created the port development authority. Each port district governing the port development authority must oversee the affairs, operations, and funds of the port development authority exclusively through the elected port commission of the port district. If the port development authority is jointly created by more than one port district under RCW 53.57.020, then the port development authority must be managed by each port district as a member of the port development authority, in accordance with the terms of this section and the charter for the port development authority. Each port district member shall act in such capacity through its own elected commissioners.

. Any port district that creates a port development authority under RCW 53.57.020 must provide for the organization and operation of the port development authority, oversee the affairs, operations, and funds of the port development authority in order to correct any deficiency, and ensure that the purposes of each program undertaken are reasonably accomplished.

. A port development authority, in managing maritime activities of a port district or districts under this chapter, may:

.. Own and sell real and personal property;

.. Contract with individuals, associations, corporations, the state, and the United States;

.. Sue and be sued;

.. Loan and borrow funds;

.. Issue bonds, notes, and other evidences of indebtedness;

.. Transfer funds, real or personal property, property interests, or services; and

.. Perform community services related to maritime activities managed by the port development authority.

. Port development authorities do not have the power of eminent domain or the power to levy taxes or special assessments.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1170-S.SL.pdf?cite=2015%20c%2035%20§%204[2015 c 35 § 4]; ]

== 53.57.040 - Agreements with government entities—Bonds, notes, or other evidence of indebtedness—Special funds.
. For the management of maritime activities, port districts and port development authorities are authorized to enter into an agreement with the federal government, any federal agency or department, and any state agency or political subdivision of the state, and pursuant to the agreement:

.. Receive and expend, or cause to be received and expended by a trustee or custodian, federal or private funds for any lawful public purpose related to management of maritime activities of the port district or port development authority;

.. Issue bonds, notes, or other evidences of indebtedness that are guaranteed or otherwise secured by funds or other instruments provided by or through the federal government; and

.. Agree to repay and reimburse for any liability of a guarantor of bonds, notes, or other evidences of indebtedness issued by the port district or port development authority.

. A port district or port development authority may pledge as security for any bond, note, or other evidence of indebtedness, or for any obligation to repay or reimburse the guarantor of a bond, note, or evidence of indebtedness, its right, title, and interest to or in the following:

.. Any federal grant or payment received by the port district or port development authority, or that may be received in the future;

.. Property and revenues that may be obtained directly or indirectly from the use of any federal or private funds received by the port district or port development authority under subsection (1) of this section;

.. Payments received or owing from any person as a result of the lending of any federal or private funds received by the port district or port development authority under subsection (1) of this section;

.. Any proceeds under (a), (b), or (c) of this subsection (2), and any securities or investments in which (a), (b), or (c) of this subsection (2) and any associated proceeds are invested; and

.. Any interest or other earnings on (a), (b), (c), or (d) of this subsection (2).

. [Empty]
.. A port district or port development authority may establish one or more special funds relating to any or all of the sources listed in subsection (2)(a) through (e) of this section. The port district or port development authority may use funds from a special fund to pay:

... The principal, interest, premium, if any, and other amounts payable on any bond, note, or other evidence of indebtedness authorized under this section; and

... Any amounts owing on obligations for repayment or reimbursement of guarantors of bonds, notes, or other evidences of indebtedness as authorized under this section.

.. A port district or port development authority may contract with a financial institution to act as trustee or custodian to: (i) Receive, administer, and expend any federal or private funds; (ii) collect, administer, and make payments from any special fund authorized under this subsection (3); or (iii) perform the functions authorized under both (b)(i) and (ii) of this subsection (3). The trustee or custodian may also perform other duties and functions in connection with authorized transactions.

.. If any bond, note, other evidence of indebtedness, or related agreement complies with subsection (4) of this section, then any of the funds held by a trustee or custodian, or by a port development authority, do not constitute public moneys or funds of a port district, and must be kept segregated and set apart from other funds at all times.

. [Empty]
.. If a port development authority loans or grants federal or private funds to a private party, or uses federal or private funds to guarantee any obligations of a private party, then any bond, note, or other evidence of indebtedness issued or entered into for the purpose of receiving the federal or private funds, or any agreement to repay or reimburse guarantors, are not obligations of a port district. These obligations may be paid only from:

... A special fund established in accordance with subsection (3) of this section;

... Any security pledged in accordance with this section; or

... Both (a)(i) and (ii) of this subsection (4).

.. Any bond, note, or other evidence of indebtedness to which this subsection (4) applies must contain a recital establishing that the bond, note, or evidence of indebtedness is not an obligation of the port district or the state, and that neither the faith and credit, nor the taxing power of the state, any subdivision or agency of the state, or any port district is pledged to pay the principal, interest, or premium, if any, on the bond, note, or evidence of indebtedness.

.. Any bond, note, other evidence of indebtedness, or other obligation to which this subsection (4) applies may not be included in any computation for purposes of limitations on indebtedness.

. For the purposes of this section, "lawful public purpose" includes any use of funds related to management of the maritime activities of a port district or port development authority, including loans of funds to public or private parties authorized by an agreement with the United States or any federal department or agency through which federal or private funds are obtained or authorized under the federal laws and regulations pertinent to the agreement.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1170-S.SL.pdf?cite=2015%20c%2035%20§%205[2015 c 35 § 5]; ]

== 53.57.050 - Powers, authorities, rights—Jurisdiction.
Powers, authorities, or rights expressly or impliedly granted to any port district or agents of the port district under the provisions of this chapter are not operable, applicable, or effective beyond the boundaries of the port district, unless so provided by contract between the port district and a county, a city, or another port district in accordance with an agreement for joint or cooperative action under the interlocal cooperation act, chapter 39.34 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1170-S.SL.pdf?cite=2015%20c%2035%20§%206[2015 c 35 § 6]; ]

== 53.57.060 - Applicable laws.
A port development authority created under this chapter must comply with applicable laws including, but not limited to, the following:

. Requirements concerning local government audits by the state auditor and applicable accounting requirements set forth in chapter 43.09 RCW;

. The public records act, chapter 42.56 RCW;

. Prohibitions on using facilities for campaign purposes under RCW 42.17A.555;

. The open public meetings act, chapter 42.30 RCW;

. The code of ethics for municipal officers under chapter 42.23 RCW; and

. Local government whistleblower protection laws set forth in chapter 42.41 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1170-S.SL.pdf?cite=2015%20c%2035%20§%207[2015 c 35 § 7]; ]

== 53.57.070 - Transfer of real property—Notice requirements—Approval process.
. In transferring real property to a port development authority under RCW 53.57.020, the port district or districts creating the port development authority must impose appropriate deed restrictions necessary to ensure the continued use of the property for the public purpose for which the property is transferred.

. A port development authority must provide written notice at least thirty days prior to any proposed sale or encumbrance of real property that was transferred by a port district to the port development authority under RCW 53.57.020(1). The port development authority must, at a minimum, provide notice to:

.. The port commission of the port district that transferred the real property;

.. Each local newspaper of general circulation within the boundaries of the port district; and

.. Each local radio station, television station, or other news medium that has submitted to the port development authority a written request to receive notification.

. [Empty]
.. A port development authority may sell or encumber property transferred by a port district under RCW 53.57.020(1) only after approval of the sale or encumbrance by the port development authority at a public meeting. Notice of the public meeting must be: (i) Provided in accordance with RCW 42.30.080; and (ii) published at least twice in a local newspaper of general circulation no fewer than seven days and no more than two weeks before the public meeting.

.. Nothing in this section may be construed to prevent the port development authority from holding an executive session during a regular or special meeting in accordance with RCW 42.30.110(1)(c).

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1170-S.SL.pdf?cite=2015%20c%2035%20§%208[2015 c 35 § 8]; ]

== 53.57.080 - Insolvency or dissolution—Satisfaction of liabilities.
. If a port development authority is insolvent or dissolved, the superior court of a county in which the port development authority operates has jurisdiction and authority to appoint trustees or receivers of the assets and property of the port development authority and to supervise the trusteeship or receivership.

. All liabilities incurred by a port development authority must be satisfied exclusively from the assets and properties of the port development authority. No creditor or other person has any right of action against the port district or districts creating the port development authority on account of any debts, obligations, or liabilities of the port development authority.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1170-S.SL.pdf?cite=2015%20c%2035%20§%209[2015 c 35 § 9]; ]

