= 12.08 - Pleadings.
:toc:

== 12.08.010 - When pleadings take place.
The pleadings in justice's court shall take place upon the appearance of the parties, unless they shall have been previously filed or unless the justice shall, for good cause shown, allow a longer time than the time of appearance.

[ Code 1881 § 1756; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20344%20§%2055[1873 p 344 § 55]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20231%20§%2043[1854 p 231 § 43]; RRS § 1778; ]

== 12.08.020 - What constitute pleadings.
The pleadings in the justice's court shall be:

. The complaint of the plaintiff, which shall state in a plain and direct manner the facts constituting the cause of action.

. The answer of the defendant, which may contain a denial of the complaint, or any part thereof; and also a statement, in a plain and direct manner, of any facts constituting a defense.

. When the answer sets up a setoff, by way of defense, the reply of the plaintiff.

[ Code 1881 § 1757; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20344%20§%2056[1873 p 344 § 56]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20231%20§%2044[1854 p 231 § 44]; RRS § 1779; ]

== 12.08.030 - Pleadings oral or written.
The pleadings in justices' courts may be oral or in writing.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c89.pdf?cite=1957%20c%2089%20§%2011[1957 c 89 § 11]; Code 1881 § 1758; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20344%20§%2057[1873 p 344 § 57]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20231%20§%2045[1854 p 231 § 45]; RRS § 1780; ]

== 12.08.040 - Docketing or filing.
When the pleadings are oral, the substance of them shall be entered by the justice in his or her docket. When in writing they shall be filed in his or her office and a reference made to them in his or her docket. Pleadings shall not be required to be in any particular form, but shall be such as to enable a person of common understanding to know what is intended.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%203018[2010 c 8 § 3018]; Code 1881 § 1759; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20345%20§%2058[1873 p 345 § 58]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20231%20§%2046[1854 p 231 § 46]; RRS § 1781; ]

== 12.08.050 - Denial of knowledge or information—Effect.
A statement in an answer or reply, that the party has not sufficient knowledge or information, in respect to a particular allegation in the previous pleadings of the adverse party to form a belief, shall be deemed equivalent to a denial.

[ Code 1881 § 1760; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20345%20§%2059[1873 p 345 § 59]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20231%20§%2047[1854 p 231 § 47]; RRS § 1782; ]

== 12.08.060 - Pleading account or instrument.
When the cause of action, or setoff, arises upon an account or instrument for the payment of money only, it shall be sufficient for the party to deliver the account or instrument, or a copy thereof, to the court, and to state that there is due to him or her thereon, from the adverse party, a specified sum, which he or she claims to recover or setoff. The court may, at the time of pleading, require that the original account, or instrument, be exhibited to the inspection of the adverse party, with liberty to copy the same; or if not so exhibited, may prohibit its being given in evidence.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%203019[2010 c 8 § 3019]; Code 1881 § 1761; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20345%20§%2060[1873 p 345 § 60]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20231%20§%2048[1854 p 231 § 48]; RRS § 1783; ]

== 12.08.070 - Verification.
Every complaint, answer, or reply shall be verified by the oath of the party pleading; or if he or she be not present, by the oath of his or her attorney or agent, to the effect that he or she believes it to be true. The verification shall be oral, or in writing, in conformity with the pleading verified.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%203020[2010 c 8 § 3020]; Code 1881 § 1762; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20345%20§%2061[1873 p 345 § 61]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20232%20§%2049[1854 p 232 § 49]; RRS § 1784; ]

== 12.08.080 - Uncontroverted allegations—Effect.
Every material allegation in a complaint, or relating to a setoff in an answer, not denied by the pleading of the adverse party, shall, on the trial, be taken to be true, except that when a defendant, who has not been served with a copy of the complaint, fails to appear and answer, the plaintiff cannot recover without proving his or her case.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%203021[2010 c 8 § 3021]; Code 1881 § 1763; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20345%20§%2062[1873 p 345 § 62]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20232%20§%2050[1854 p 232 § 50]; RRS § 1785; ]

== 12.08.090 - Objections to pleadings—Amendment.
Either party may object to a pleading by his or her adversary, or to any part thereof that is not sufficiently explicit for him or her to understand it, or that it contains no cause of action or defense although it be taken as true. If the court deem the objection well-founded, it shall order the pleading to be amended; and if the party refuse to amend, the defective pleading shall be disregarded.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%203022[2010 c 8 § 3022]; Code 1881 § 1764; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20345%20§%2063[1873 p 345 § 63]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20232%20§%2051[1854 p 232 § 51]; RRS § 1786; ]

== 12.08.100 - Variance between pleading and proof.
A variance between the proof on the trial, and the allegations in a pleading, shall be disregarded as immaterial, unless the court be satisfied that the adverse party has been misled to his or her prejudice thereby.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%203023[2010 c 8 § 3023]; Code 1881 § 1765; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20346%20§%2064[1873 p 346 § 64]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20232%20§%2052[1854 p 232 § 52]; RRS § 1787; ]

== 12.08.110 - Amendments—Continuance.
The pleadings may be amended at any time before the trial, or during the trial, or upon appeal, to supply any deficiency or omissions in the allegations or denials, necessary to support the action or defense, when by such amendment substantial justice will be promoted. If the amendment be made after the issue, and it be made to appear to the satisfaction of the court that a continuance is necessary to the adverse party in consequence of such amendment, a continuance shall be granted. The court may also, in its discretion, require as a condition of an amendment, the payment of costs to the adverse party.

[ Code 1881 § 1766; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20346%20§%2065[1873 p 346 § 65]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20232%20§%2053[1854 p 232 § 53]; RRS § 1788; ]

== 12.08.120 - Setoff—Pleading.
To entitle a defendant to any setoff he or she may have against the plaintiff, he or she must allege the same in his or her answer; and the statutes regulating setoffs in the superior court, shall in all respects be applicable to a setoff in a justice's court, if the amount claimed to be setoff, after deducting the amount found due to the plaintiff, be within the jurisdiction of the justice of the peace; judgment may, in like manner, be rendered by the justice in favor of the defendant, for the balance found due the plaintiff.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%203024[2010 c 8 § 3024]; Code 1881 § 1767; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20346%20§%2066[1873 p 346 § 66]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20232%20§%2054[1854 p 232 § 54]; RRS § 1789; ]

