= 12.20 - Judgments.
:toc:

== 12.20.010 - Judgment of dismissal.
Judgment that the action be dismissed, without prejudice to a new action, may be entered, with costs, in the following cases:

. When the plaintiff voluntarily dismisses the action before it is finally submitted.

. When he or she fails to appear at the time specified in the notice, upon continuance, or within one hour thereafter.

. When it is objected at the trial, and appears by the evidence that the action is brought in the wrong precinct; but if the objection be taken and overruled, it shall be cause only of reversal or appeal; if not taken at the trial it shall be deemed waived, and shall not be cause of reversal.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%203034[2010 c 8 § 3034]; Code 1881 § 1780; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20348%20§%2079[1873 p 348 § 79]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20349%20§%2061[1863 p 349 § 61]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20236%20§%2080[1854 p 236 § 80]; RRS § 1857; ]

== 12.20.020 - Judgment by default.
When the defendant fails to appear and plead at the time specified in the notice, or within one hour thereafter, judgment shall be given as follows:

. When the defendant has been served with a true copy of the complaint, judgment shall be given without further evidence for the sum specified therein;

. In other cases, the justice shall hear the evidence of the plaintiff, and render judgment for such sum only as shall appear by the evidence to be just, but in no case exceed the amount specified in the complaint.

. The justice shall have full power at any time after a judgment has been given by default for failure of the defendant to appear and plead at the proper time, to vacate and set aside said judgment for any good cause and upon such terms as he or she shall deem sufficient and proper. Such judgment shall only be set aside upon five days notice in writing served upon the plaintiff or the plaintiff's attorney and filed with the justice within ten days after the entry of the judgment. The justice shall hear the application to set aside such judgment either upon affidavits or oral testimony as he or she may deem proper. In case such judgment is set aside the making of the application for setting the same aside shall be considered an entry of general appearance in the case by the applicant, and the case shall duly proceed to a trial upon the merits: PROVIDED, That, no justice of the peace shall pay out or turn over money or property received by him or her by virtue of any default judgment until the expiration of the ten days for moving to set aside such default judgment has expired.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%203035[2010 c 8 § 3035]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c41.pdf?cite=1915%20c%2041%20§%201[1915 c 41 § 1]; Code 1881 § 1781; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20349%20§%2079[1873 p 349 § 79]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20349%20§%2062[1863 p 349 § 62]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20237%20§%2081[1854 p 237 § 81]; RRS § 1858; ]

== 12.20.030 - Judgment on merits.
Upon the verdict of a jury, the justice shall immediately render judgment thereon. When the trial is by the justice, judgment shall be entered within three days after the close of the trial.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c89.pdf?cite=1957%20c%2089%20§%2013[1957 c 89 § 13]; Code 1881 § 1783; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20350%20§%2082[1873 p 350 § 82]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20237%20§%2083[1854 p 237 § 83]; RRS § 1859; ]

== 12.20.040 - Tender—Effect of, on judgment.
If the defendant, at any time before the trial, offer in writing to allow judgment to be taken against him or her for a specified sum, the plaintiff may immediately have judgment therefor, with costs then accrued; but if he or she do not accept such offer before the trial, and fail to recover on the trial of the action, a sum greater than the offer, such plaintiff shall not recover any costs that may accrue after he or she shall have been notified of the offer of the defendant, but such costs shall be adjudged against him or her, and if he or she recover, deducted from his or her recovery. But the offer and failure to accept it, shall not be given in evidence to affect the recovery, otherwise than as to costs, as above provided.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%203036[2010 c 8 § 3036]; Code 1881 § 1784; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20350%20§%2083[1873 p 350 § 83]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20350%20§%2065[1863 p 350 § 65]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20237%20§%2084[1854 p 237 § 84]; RRS § 1860; ]

== 12.20.050 - Setoff—Limitation of judgment.
When the setoff of the defendant proved shall exceed the claim of the plaintiff, and such excess in amount exceed the jurisdiction of a justice of the peace, the court shall allow such amount as is necessary to cancel the plaintiff's claim, and give the defendant a judgment for costs; but in such case, the court shall not render judgment for any further sum in favor of the defendant.

[ Code 1881 § 1768; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20346%20§%2067[1873 p 346 § 67]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20232%20§%2055[1854 p 232 § 55]; RRS § 1861; ]

== 12.20.060 - Judgment for costs—Attorney's fee—Costs in civil actions for the recovery of money only.
. When the prevailing party in district court is entitled to recover costs as authorized in RCW 4.84.010 in a civil action, the judge shall add the amount thereof to the judgment; in case of failure of the plaintiff to recover or of dismissal of the action, the judge shall enter up a judgment in favor of the defendant for the amount of his or her costs; and in case any party so entitled to costs is represented in the action by an attorney, the judge shall include attorney's fees in the amount provided in RCW 4.84.080 as part of the costs: PROVIDED, HOWEVER, That the plaintiff shall not be entitled to such attorney fee unless he or she obtains, exclusive of costs, a judgment in the sum of fifty dollars or more: AND PROVIDED FURTHER, That if the plaintiff obtains judgment, exclusive of costs, of at least fifty dollars but less than two hundred dollars, the judge shall include attorney fees of one hundred twenty-five dollars as part of the costs.

. [Empty]
.. In any district court civil action for the recovery of money only, the plaintiff will be considered the prevailing party for the purpose of awarding costs, including a statutory attorney fee, if: (i) The defendant makes full or partial payment of the amounts sought by the plaintiff prior to the entry of judgment; and (ii) before such payment is tendered, the plaintiff has notified the defendant in writing that the full or partial payment of the amounts sued for might result in an award of costs. The plaintiff is not entitled to a statutory attorney fee unless the amount prayed for, exclusive of costs, is fifty dollars or more, and if the amount prayed for, exclusive of costs, is at least fifty dollars but less than two hundred dollars, the judgment must include a statutory attorney fee of one hundred twenty-five dollars as part of the costs.

.. For the purposes of this section, "plaintiff" includes a counterclaimant, cross-claimant, and third-party plaintiff, and "defendant" includes a party defending a counterclaim, cross-claim, or third-party claim.

.. A party may demand, offer, or accept payment of statutory costs before the entry of judgment in an action.

.. This section may not be construed to (a) [(i)] authorize an award of costs if the action is resolved by a negotiated settlement or (b) [(ii)] limit or bar the operation of cost-shifting provisions of other statutes or court rules.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1022-S.SL.pdf?cite=2009%20c%20240%20§%203[2009 c 240 § 3]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6527-S.SL.pdf?cite=2004%20c%20123%20§%202[2004 c 123 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5157-S.SL.pdf?cite=1993%20c%20341%20§%201[1993 c 341 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c240.pdf?cite=1985%20c%20240%20§%202[1985 c 240 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c258.pdf?cite=1984%20c%20258%20§%2089[1984 c 258 § 89]; 1975-'76 2nd ex.s. c 30 § 1; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c43.pdf?cite=1915%20c%2043%20§%201[1915 c 43 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c12.pdf?cite=1893%20c%2012%20§%201[1893 c 12 § 1]; Code 1881 § 1785; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20350%20§%2084[1873 p 350 § 84]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20237%20§%2085[1854 p 237 § 85]; RRS § 1862; ]

== 12.20.070 - Proceedings where title to land is involved.
If it appear on the trial of any cause before a justice of the peace, from the evidence of either party, that the title to lands is in question, which title shall be disputed by the other, the justice shall immediately make an entry thereof in his or her docket, and cease all further proceedings in the cause, and shall certify and return to the superior court of the county, a transcript of all the entries made in his or her docket, relating to the cause, together with all the process and other papers relating to the action, in the same manner, and within the same time, as upon an appeal; and thereupon the parties shall file their pleadings, and the superior court shall proceed in the cause to final judgment and execution, in the same manner as if the said action had been originally commenced therein, and the cost shall abide the event of the suit.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%203037[2010 c 8 § 3037]; Code 1881 § 1868; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20369%20§%20167[1873 p 369 § 167]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20235%20§%2069[1854 p 235 § 69]; RRS § 1863; ]

