= 12.36 - Small claims appeals.
:toc:

== 12.36.010 - Appeal in small claims action authorized.
Any person wishing to appeal a judgment or decision in a small claims action may, in person or by his or her agent, appeal to the superior court of the county where the judgment was rendered or decision made: PROVIDED, There shall be no appeal allowed unless the amount in controversy, exclusive of costs, exceeds two hundred fifty dollars: PROVIDED FURTHER, That an appeal from the court's determination or order on a traffic infraction proceeding may be taken only in accordance with RCW 46.63.090(5).

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5295-S.SL.pdf?cite=1997%20c%20352%20§%207[1997 c 352 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c136.pdf?cite=1979%20ex.s.%20c%20136%20§%2021[1979 ex.s. c 136 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c58.pdf?cite=1929%20c%2058%20§%201[1929 c 58 § 1]; RRS § 1910; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1905c20.pdf?cite=1905%20c%2020%20§%201[1905 c 20 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c29.pdf?cite=1891%20c%2029%20§%201[1891 c 29 § 1]; Code 1881 § 1858; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20367%20§%20156[1873 p 367 § 156]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20252%20§%20160[1854 p 252 § 160]; ]

== 12.36.020 - Appeal—Procedure—Notice filing—Fee—Bond or undertaking—Service—Costs of record preparation.
. To appeal a judgment or decision in a small claims action, an appellant shall file a notice of appeal in the district court, pay the statutory superior court filing fee, post the required bond or undertaking, and serve a copy of the notice of appeal on all parties of record within thirty days after the judgment is rendered or decision made.

. No appeal may be allowed, nor proceedings on the judgment or decision stayed, unless a bond or undertaking shall be executed on the part of the appellant and filed with and approved by the district court. The bond or undertaking shall be executed with two or more personal sureties, or a surety company as surety, to be approved by the district court, in a sum equal to twice the amount of the judgment and costs, or twice the amount in controversy, whichever is greater, conditioned that the appellant will pay any judgment, including costs, as may be rendered on appeal. No bond is required if the appellant is a county, city, town, or school district.

. When an appellant has filed a notice of appeal, paid the statutory superior court filing fee and the costs of preparation of the complete record as set forth in *RCW 3.62.060(7), and posted the bond or undertaking as required, the clerk of the district court shall immediately file a copy of the notice of appeal, the filing fee, and the bond or undertaking with the superior court.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2907.SL.pdf?cite=1998%20c%2052%20§%201[1998 c 52 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5295-S.SL.pdf?cite=1997%20c%20352%20§%208[1997 c 352 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c58.pdf?cite=1929%20c%2058%20§%202[1929 c 58 § 2]; RRS § 1911; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c29.pdf?cite=1891%20c%2029%20§%201[1891 c 29 § 1]; Code 1881 § 1859; 1873 p 367 §§ 157, 158; 1854 p 252 §§ 161, 162; ]

== 12.36.030 - Stay of proceedings—Procedures—Return of property upon stay—Enforcement upon denial.
When an appeal and any necessary bond or undertaking are properly filed in superior court pursuant to RCW 12.36.020(3), the appellant may move in superior court to stay all further proceedings in the district court. If the stay is granted, all further proceedings in district court on the judgment shall be suspended. If proceedings have commenced on motion of the appellant the court may order the proceedings halted and such process recalled.

If any property is held pursuant to such proceedings at the time the stay is granted and the process recalled, such property shall be returned immediately to the party entitled to such property.

If the requested stay is denied, or no stay is requested, the judgment will be enforced in superior court in the same manner as any other judgment rendered in that court.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2907.SL.pdf?cite=1998%20c%2052%20§%202[1998 c 52 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5295-S.SL.pdf?cite=1997%20c%20352%20§%209[1997 c 352 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c58.pdf?cite=1929%20c%2058%20§%203[1929 c 58 § 3]; RRS § 1912; Code 1881 § 1861; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20368%20§%20160[1873 p 368 § 160]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20252%20§%20164[1854 p 252 § 164]; ]

== 12.36.050 - Certification of record by district court—Transmittal to superior court—Powers of superior court upon transmittal.
. Within fourteen days after a small claims appeal has been filed in superior court by the clerk of the district court pursuant to RCW 12.36.020(3), the complete record as defined in subsection (2) of this section shall be made and certified by the clerk of the district court to be correct. The clerk shall then immediately transmit the complete record to superior court. The superior court shall then become possessed of the cause. All further proceedings shall be in the superior court, including enforcement of any judgment rendered. Any superior court procedures such as arbitration or other methods of dispute resolution may be utilized by the superior court in its discretion.

. The complete record shall consist of a transcript of all entries made in the district court docket relating to the case, together with all the process and other papers relating to the case filed with the district court and a contemporaneous recording made of the proceeding.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5491.SL.pdf?cite=2001%20c%20156%20§%201[2001 c 156 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2907.SL.pdf?cite=1998%20c%2052%20§%203[1998 c 52 § 3]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5295-S.SL.pdf?cite=1997%20c%20352%20§%2010[1997 c 352 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c58.pdf?cite=1929%20c%2058%20§%205[1929 c 58 § 5]; RRS §§ 1914, 1915; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c29.pdf?cite=1891%20c%2029%20§%204[1891 c 29 § 4]; Code 1881 § 1863; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20368%20§%20162[1873 p 368 § 162]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20252%20§%20166[1854 p 252 § 166]; ]

== 12.36.055 - Trial of an appeal from small claims judgment.
. The appeal from a small claims judgment or decision shall be de novo upon the record of the case, as entered by the district court.

. Any cases heard in superior court pursuant to this section may be heard by a duly appointed commissioner. As used in this chapter "judge" includes any duly appointed commissioner.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5491.SL.pdf?cite=2001%20c%20156%20§%202[2001 c 156 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5295-S.SL.pdf?cite=1997%20c%20352%20§%2011[1997 c 352 § 11]; ]

== 12.36.080 - No dismissal for defective bond—Notice.
No appeal under this chapter shall be dismissed on account of any defect in the bond on appeal, if, within ten days of notice to appellant of such defect, the appellant executes and files in the court currently possessed of the cause such bond as should have been executed at the time of taking the appeal, and pay all costs that may have accrued by reason of such defect.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2907.SL.pdf?cite=1998%20c%2052%20§%204[1998 c 52 § 4]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5295-S.SL.pdf?cite=1997%20c%20352%20§%2012[1997 c 352 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c58.pdf?cite=1929%20c%2058%20§%207[1929 c 58 § 7]; RRS § 1917; Code 1881 § 1867; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20369%20§%20165[1873 p 369 § 165]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20253%20§%20169[1854 p 253 § 169]; ]

== 12.36.090 - Judgment against appellant and sureties.
In all cases of appeal to the superior court under this chapter, if the judgment is against the appellant, in whole or in part, such judgment shall be rendered against the appellant and his or her sureties on the bond on appeal.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5295-S.SL.pdf?cite=1997%20c%20352%20§%2013[1997 c 352 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c58.pdf?cite=1929%20c%2058%20§%208[1929 c 58 § 8]; RRS § 1918; Code 1881 § 1867; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20369%20§%20166[1873 p 369 § 166]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20253%20§%20170[1854 p 253 § 170]; ]

