= 27.34 - State historical societies—Historic preservation.
:toc:

== 27.34.010 - Purpose.
The legislature finds that those articles and properties which illustrate the history of the state of Washington should be maintained and preserved for the use and benefit of the people of the state. It is the purpose of this chapter to designate the two state historical societies as trustees of the state for these purposes, and to establish:

. A comprehensive and consistent statewide policy pertaining to archaeology, history, historic preservation, and other historical matters;

. Statewide coordination of historical programs; and

. A coordinated budget for all state historical agencies.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5139.SL.pdf?cite=1993%20c%20101%20§%209[1993 c 101 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c91.pdf?cite=1983%20c%2091%20§%201[1983 c 91 § 1]; ]

== 27.34.020 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter:

. "Advisory council" means the advisory council on historic preservation.

. "Department" means the department of archaeology and historic preservation.

. "Director" means the director of the department of archaeology and historic preservation.

. "Federal act" means the national historic preservation act of 1966 (Public Law 89-655; 80 Stat. 915).

. "Heritage barn" means any large agricultural outbuilding used to house animals, crops, or farm equipment, that is over fifty years old and has been determined by the department to: (a) Be eligible for listing on the Washington heritage register or the national register of historic places; or (b) have been listed on a local historic register and approved by the advisory council. In addition to barns, "heritage barn" includes agricultural resources such as milk houses, sheds, silos, or other outbuildings, that are historically associated with the working life of the farm or ranch, if these outbuildings are on the same property as a heritage barn.

. "Heritage council" means the Washington state heritage council.

. "Historic preservation" includes the protection, rehabilitation, restoration, identification, scientific excavation, and reconstruction of districts, sites, buildings, structures, and objects significant in American and Washington state history, architecture, archaeology, or culture.

. "Preservation officer" means the state historic preservation officer as provided for in RCW 43.334.020.

. "Project" means programs leading to the preservation for public benefit of historical properties, whether by state and local governments or other public bodies, or private organizations or individuals, including the acquisition of title or interests in, and the development of, any district, site, building, structure, or object that is significant in American and Washington state history, architecture, archaeology, or culture, and property used in connection therewith, or for its development.

. "State historical agencies" means the state historical societies and the department.

. "State historical societies" means the Washington state historical society and the eastern Washington state historical society.

. "Cultural resource management plan" means a comprehensive plan which identifies and organizes information on the state of Washington's historic, archaeological, and architectural resources into a set of management criteria, and which is to be used for producing reliable decisions, recommendations, and advice relative to the identification, evaluation, and protection of these resources.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2115-S.SL.pdf?cite=2007%20c%20333%20§%205[2007 c 333 § 5]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5056-S2.SL.pdf?cite=2005%20c%20333%20§%2013[2005 c 333 § 13]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1014.SL.pdf?cite=1995%20c%20399%20§%2013[1995 c 399 § 13]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5139.SL.pdf?cite=1993%20c%20101%20§%2010[1993 c 101 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%209[1986 c 266 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c91.pdf?cite=1983%20c%2091%20§%202[1983 c 91 § 2]; ]

== 27.34.060 - State historical societies—Budget requests.
Each state historical society shall submit its budget requests to the heritage council for review and comment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c91.pdf?cite=1983%20c%2091%20§%206[1983 c 91 § 6]; ]

== 27.34.070 - State historical societies—Powers and duties—Rules.
. Each state historical society is designated a trustee for the state whose powers and duties include but are not limited to the following:

.. To collect, catalog, preserve, and interpret objects, manuscripts, sites, photographs, and other materials illustrative of the cultural, artistic, and natural history of this state;

.. To operate state museums and assist and encourage cultural and historical studies and museum interpretive efforts throughout the state, including those sponsored by local historical organizations, and city, county, and state agencies;

.. To engage in cultural, artistic, and educational activities, including classes, exhibits, seminars, workshops, and conferences if these activities are related to the basic purpose of the society;

.. To plan for and conduct celebrations of significant events in the history of the state of Washington and to give assistance to and coordinate with state agencies, local governments, and local historical organizations in planning and conducting celebrations;

.. To create one or more classes of membership in the society;

.. To engage in the sale of various articles which are related to the basic purpose of the society;

.. To engage in appropriate fund-raising activities for the purpose of increasing the self-support of the society;

.. To accept gifts, grants, conveyances, bequests, and devises, of real or personal property, or both, in trust or otherwise, and sell, lease, exchange, invest, or expend the same or the proceeds, rents, profits, and income therefrom except as limited by the donor's terms. The governing boards of the state historical societies shall adopt rules to govern and protect the receipt and expenditure of the proceeds, rents, profits, and income of all such gifts, grants, conveyances, bequests, and devises;

.. To accept on loan or lend objects of historical interest, and sell, exchange, divest itself of, or refuse to accept, items which do not enhance the collection;

.. To charge general or special admission fees to its museums or exhibits and to waive or decrease such fees as it finds appropriate; and

.. To strengthen cultural and historical organizations statewide by providing grants at the discretion of the society in support of organizational capacity building, public programming, educational programming, outreach, collections management, and exhibitions as funding allows.

. All objects, sites, manuscripts, photographs, and all property, including real property, now held or hereafter acquired by the state historical societies shall be held by the societies in trust for the use and benefit of the people of Washington state.

. Each historical society is authorized to adopt rules under chapter 34.05 RCW to carry out the policies and purposes of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2837.SL.pdf?cite=2020%20c%2048%20§%201[2020 c 48 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5056-S2.SL.pdf?cite=2005%20c%20333%20§%2014[2005 c 333 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c91.pdf?cite=1983%20c%2091%20§%207[1983 c 91 § 7]; ]

== 27.34.075 - Educational publications printing.
The provisions of chapter 43.19 RCW shall not apply to the printing of educational publications of the state historical societies.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5024.SL.pdf?cite=2015%20c%20225%20§%2023[2015 c 225 § 23]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2334-S.SL.pdf?cite=1994%20c%2082%20§%202[1994 c 82 § 2]; ]

== 27.34.080 - State historical societies—Appointment of directors—Removal.
The governing board of each state historical society shall appoint its respective director with the consent of the governor. The governor may remove a director for cause or if a majority of the society's governing board votes for removal.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c91.pdf?cite=1983%20c%2091%20§%208[1983 c 91 § 8]; ]

== 27.34.200 - Archaeology and historic preservation—Legislative declaration.
The legislature hereby finds that the promotion, enhancement, perpetuation, and use of structures, sites, districts, buildings, and objects of historic, archaeological, architectural, and cultural significance is desirable in the interest of the public pride and general welfare of the people of the state; and the legislature further finds that the economic, cultural, and aesthetic standing of the state can be maintained and enhanced by protecting the heritage of the state and by preventing the destruction or defacement of these assets; therefore, it is hereby declared by the legislature to be the public policy and in the public interest of the state to designate, preserve, protect, enhance, and perpetuate those structures, sites, districts, buildings, and objects which reflect outstanding elements of the state's historic, archaeological, architectural, or cultural heritage, for the inspiration and enrichment of the citizens of the state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c91.pdf?cite=1983%20c%2091%20§%2010[1983 c 91 § 10]; ]

== 27.34.220 - Director—Powers.
The director or the director's designee is authorized:

. To promulgate and maintain the Washington heritage register of districts, sites, buildings, structures, and objects significant in American or Washington state history, architecture, archaeology, and culture, and to prepare comprehensive statewide historic surveys and plans and research and evaluation of surveyed resources for the preparation of nominations to the Washington heritage register and the national register of historic places, in accordance with criteria approved by the advisory council established under RCW 27.34.250. Nominations to the national register of historic places shall comply with any standards and regulations promulgated by the United States secretary of the interior for the preservation, acquisition, and development of such properties. Nominations to the Washington heritage register shall comply with rules adopted under this chapter.

. To establish a program of matching grants-in-aid to public agencies, public or private organizations, or individuals for projects having as their purpose the preservation for public benefit of properties that are significant in American or Washington state history, architecture, archaeology, and culture.

. To promote historic preservation efforts throughout the state, including private efforts and those of city, county, and state agencies.

. To enhance the effectiveness of the state preservation program through the initiation of legislation, the use of varied funding sources, the creation of special purpose programs, and contact with state, county, and city officials, civic groups, and professionals.

. To spend funds, subject to legislative appropriation and the availability of funds, where necessary to assist the Indian tribes of Washington state in removing prehistoric human remains for scientific examination and reburial, if the human remains have been unearthed inadvertently or through vandalism and if no other public agency is legally responsible for their preservation.

. To consult with the governor and the legislature on issues relating to the conservation of the man-made environment and their impact on the well-being of the state and its citizens.

. To charge fees for professional and clerical services provided by the *office.

. To adopt such rules, in accordance with chapter 34.05 RCW, as are necessary to carry out RCW 27.34.200 through 27.34.280.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5551.SL.pdf?cite=1997%20c%20145%20§%201[1997 c 145 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c505.pdf?cite=1987%20c%20505%20§%208[1987 c 505 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2011[1986 c 266 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c64.pdf?cite=1985%20c%2064%20§%202[1985 c 64 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c91.pdf?cite=1983%20c%2091%20§%2012[1983 c 91 § 12]; ]

== 27.34.230 - Director—Duties.
The director or the director's designee shall:

. Receive, administer, and disburse such gifts, grants, and endowments from private sources as may be made in trust or otherwise for the purposes of RCW 27.34.200 through 27.34.220 or the federal act; and

. Develop and implement a cultural resource management plan.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5056-S2.SL.pdf?cite=2005%20c%20333%20§%2015[2005 c 333 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2012[1986 c 266 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c91.pdf?cite=1983%20c%2091%20§%2013[1983 c 91 § 13]; ]

== 27.34.240 - Apportionment of grants.
The amounts made available for grants to the public agencies, public or private organizations, or individuals for projects for each fiscal year shall be apportioned among program applicants by the director or the director's designee, with the advice of the preservation officer, in accordance with needs as contained in statewide archaeology and historic preservation plans developed by the department.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2013[1986 c 266 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c91.pdf?cite=1983%20c%2091%20§%2014[1983 c 91 § 14]; ]

== 27.34.250 - Advisory council on historic preservation—Members.
. There is hereby established an advisory council on historic preservation, which shall be composed of nine members appointed by the governor as follows:

.. A representative of a local or state heritage organization;

.. Six members of the public who are interested and experienced in matters to be considered by the council including the fields of history, architecture, and archaeology;

.. A representative from the Washington archaeological community; and

.. A native American.

. Each member of the council shall serve a four-year term.

. A vacancy in the council shall not affect its powers, but shall be filled in the same manner as the original appointment for the balance of the unexpired term.

. The chairperson of the council shall be designated by the governor.

. Five members of the council shall constitute a quorum.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1468.SL.pdf?cite=1995%20c%20150%20§%201[1995 c 150 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1923.SL.pdf?cite=1993%20c%20185%20§%201[1993 c 185 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5139.SL.pdf?cite=1993%20c%20101%20§%2012[1993 c 101 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c91.pdf?cite=1983%20c%2091%20§%2015[1983 c 91 § 15]; ]

== 27.34.260 - Advisory council—Compensation and reimbursement of members.
The directors of the state historical societies shall serve as members of the advisory council on historic preservation without additional compensation. All other members of the advisory council shall be reimbursed for travel expenses incurred in the performance of the duties of the council in accordance with RCW 43.03.050 and 43.03.060.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c91.pdf?cite=1983%20c%2091%20§%2018[1983 c 91 § 18]; ]

== 27.34.270 - Advisory council—Duties.
The advisory council shall:

. Advise the governor and the department on matters relating to historic preservation; recommend measures to coordinate activities of state and local agencies, private institutions, and individuals relating to historic preservation; and advise on the dissemination of information pertaining to such activities; and

. Review and recommend nominations for the national register of historic places to the preservation officer and the director.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5551.SL.pdf?cite=1997%20c%20145%20§%202[1997 c 145 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2014[1986 c 266 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c91.pdf?cite=1983%20c%2091%20§%2017[1983 c 91 § 17]; ]

== 27.34.280 - Advisory council, heritage council—Financial and administrative services.
The department shall provide administrative and financial services to the advisory council on historic preservation and to the Washington state heritage council.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2015[1986 c 266 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c91.pdf?cite=1983%20c%2091%20§%2016[1983 c 91 § 16]; ]

== 27.34.330 - Heritage capital projects—Proposals for funding—Prioritized list.
The Washington state historical society shall establish a competitive process to solicit proposals for and prioritize heritage capital projects for potential funding in the state capital budget. The society shall adopt rules governing project eligibility and evaluation criteria. Application for funding of specific projects may be made to the society by local governments, public development authorities, nonprofit corporations, tribal governments, and other entities, as determined by the society. The society, with the advice of leaders in the heritage field, including but not limited to representatives from the office of the secretary of state, the eastern Washington state historical society, and the department of archaeology and historic preservation, shall establish and submit a prioritized list of heritage capital projects to the governor and the legislature in the society's biennial capital budget request. The list shall include a description of each project, the amount of recommended state funding, and documentation of nonstate funds to be used for the project. The total amount of recommended state funding for projects on a biennial project list shall not exceed ten million dollars. The prioritized list shall be developed through open and public meetings and the amount of state funding shall not exceed thirty-three and thirty-three one-hundredths percent of the total cost of the project. The nonstate portion of the total project cost may include cash, the value of real property when acquired solely for the purpose of the project, and in-kind contributions. The department shall not sign contracts or otherwise financially obligate funds under this section until the legislature has approved a specific list of projects. In contracts for grants authorized under this section, the society shall include provisions requiring that capital improvements be held by the grantee for a specified period of time appropriate to the amount of the grant and that facilities be used for the express purpose of the grant. If the grantee is found to be out of compliance with provisions of the contract, the grantee shall repay to the state general fund the principal amount of the grant plus interest calculated at the rate of interest on state of Washington general obligation bonds issued most closely to the date of authorization of the grant.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=2015%203rd%20sp.s.%20c%203%20§%207014[2015 3rd sp.s. c 3 § 7014]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6384-S.SL.pdf?cite=2006%20c%20371%20§%20232[2006 c 371 § 232]; 2006 c 371 § 231; 2005 c 333 § 16; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1577-S.SL.pdf?cite=2005%20c%20160%20§%203[2005 c 160 § 3]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1222-S.SL.pdf?cite=1999%20c%20295%20§%202[1999 c 295 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1507-S.SL.pdf?cite=1995%20c%20182%20§%202[1995 c 182 § 2]; ]

== 27.34.350 - Governor's award for excellence in teaching history.
. Many people throughout the state contribute significantly to the promotion of historical study as a means to give the state's citizens a better sense of the past. The Washington state historical society recognizes the accomplishments of many men and women in the teaching professions whose skill and achievement in the inculcating of historic values are not given the recognition nor the support they deserve or given the encouragement to continue their work.

. The governor's award for excellence in teaching history is created to annually recognize teachers and public and private nonprofit historical organizations that have organized, conducted, published, or offered on a consistently exemplary basis, outstanding activities that promote a better understanding and appreciation of the state's history. One cash award to an individual teacher and one cash award to an organization shall be made each year. The sums described in this section shall be raised through solicitations from private donors.

. The Washington state historical society's board of trustees shall make the final determination of award recipients.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5674.SL.pdf?cite=1997%20c%20263%20§%201[1997 c 263 § 1]; ]

== 27.34.360 - Women's history consortium—Created—Washington state historical society as managing agency.
. A women's history consortium is created with the Washington state historical society as the managing agency. To ensure geographic, demographic, and subject matter diversity, the consortium shall be managed by a board of advisors representing a range of perspectives, including private citizens, business, labor, historical societies, colleges and universities, educators, tribes, and public officials. Appointment of the board of advisors must be completed by September 30, 2005.

. The consortium is attached to the Washington state historical society as the managing agency. Accordingly, the agency shall:

.. Direct and supervise the budgeting, recordkeeping, recording, and related administrative and clerical functions of the consortium;

.. Include the consortium's budgetary requests in the society's departmental budget;

.. Collect all nonappropriated revenues for the consortium and deposit them in the proper fund or account;

.. Provide staff support for the consortium;

.. Print and disseminate for the consortium any required notices, rules, or orders adopted by the consortium; and

.. Allocate or otherwise provide office space for the consortium as may be necessary.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5707.SL.pdf?cite=2005%20c%20391%20§%202[2005 c 391 § 2]; ]

== 27.34.365 - Women's history consortium—Board of advisors.
The board of advisors shall consist of fifteen members. The director of the state historical society shall appoint eleven members to the board of advisors. Two members of the senate, one each representing the two largest caucuses of the senate, shall be appointed by the president of the senate, and two members of the house of representatives, one each representing the two largest caucuses of the house of representatives, shall be appointed by the speaker of the house of representatives.

The women's history consortium board of advisors may meet no more than two times per calendar year. If state funds are not available for travel, the board may meet on a voluntary basis at members' expense.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2617-S2.SL.pdf?cite=2010%201st%20sp.s.%20c%207%20§%20124[2010 1st sp.s. c 7 § 124]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5707.SL.pdf?cite=2005%20c%20391%20§%203[2005 c 391 § 3]; ]

== 27.34.370 - Women's history consortium—Responsibilities of board of advisors.
Key responsibilities of the board of advisors include:

. Organizational and fiscal planning, management, and oversight;

. Adopting criteria and procedures for consortium membership and member responsibilities;

. Identifying short-term and long-term priorities of the consortium, with special emphasis on short-term priorities relating to preserving historical information from the last several decades before it is lost;

. Appointing special committees and task forces including people from consortium members and nonmembers to assist with the consortium's tasks; and

. Developing recommendations for statewide commemoration of the centennial of the adoption in 1910 of the fifth amendment to the Washington state Constitution, guaranteeing women's suffrage.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5707.SL.pdf?cite=2005%20c%20391%20§%204[2005 c 391 § 4]; ]

== 27.34.375 - Women's history consortium—Responsibilities.
Within available resources, the consortium responsibilities include:

. Compiling a comprehensive index of existing historically relevant materials and making it available in electronic and print form;

. Identifying topics, historical periods, materials, or activities not well represented in publicly accessible collections and developing strategies for making them publicly available, including topics related to motherhood and the accomplishments of mothers in Washington;

. Encouraging collection and preservation of materials important to understanding Washington women's history, with special emphasis on the last several decades;

. Referring potential donors of historical materials to appropriate museums, archives, libraries, and other organizations throughout the state;

. Developing protocols for protection of donations, loans, leases, and purchases of historically relevant materials;

. Encouraging exhibit development and sharing among member organizations and others;

. Encouraging public access and educational institution access to women's history information, materials, and exhibits;

. Seeking private donations to assist with consortium work; 

. Developing a concept for a grant program;

. Developing a volunteer program; and

. Encouraging development of curriculum materials.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5707.SL.pdf?cite=2005%20c%20391%20§%205[2005 c 391 § 5]; ]

== 27.34.380 - Women's history consortium—Report to the legislature.
The consortium board of advisors shall provide a report to the appropriate committees of the legislature by December 1, 2006, addressing the following:

. Progress on activities identified in RCW 27.34.370 and 27.34.375; and

. Consortium needs and plans for the future.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5707.SL.pdf?cite=2005%20c%20391%20§%206[2005 c 391 § 6]; ]

== 27.34.390 - Vancouver national historic reserve.
The legislature affirms that the state of Washington is partner in the Vancouver national historic reserve as mandated under Public Law 104-333: The omnibus parks and public lands management act of 1996. As such, the state will take an active role in supporting the protection, preservation, interpretation, and rehabilitation of the Vancouver national historic reserve.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5032-S.SL.pdf?cite=2007%20c%20138%20§%202[2007 c 138 § 2]; ]

== 27.34.395 - Vancouver national historic reserve—Designated partner representative—Duties of Washington state historical society.
The legislature affirms that the Washington state historical society is the state's designated partner representative for the Vancouver national historic reserve. Accordingly, the Washington state historical society shall:

. Participate in the regularly scheduled coordination meetings of the Vancouver national historic reserve partners;

. Participate in the development of management, education, and interpretive plans and policies associated with the Vancouver national historic reserve; and

. Develop and submit to the office of financial management and the legislature operating and capital budget requests concurrent with the biennial cycle and oversee the management of all funds appropriated by the state for the Vancouver national historic reserve.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1853.SL.pdf?cite=2017%20c%20117%20§%201[2017 c 117 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5032-S.SL.pdf?cite=2007%20c%20138%20§%203[2007 c 138 § 3]; ]

== 27.34.400 - Heritage barn preservation program.
. The Washington state heritage barn preservation program is created in the department.

. The director, in consultation with the heritage barn preservation advisory board, shall conduct a thematic study of Washington state's barns. The study shall include a determination of types, an assessment of the most unique and significant barns in the state, and a condition and needs assessment of historic barns in the state.

. [Empty]
.. The department, in consultation with the heritage barn preservation advisory board, shall establish a heritage barn recognition program. To apply for recognition as a heritage barn, the barn owner shall supply to the department photos of the barn, photos of the farm and surrounding landscape, a brief history of the farm, and a construction date for the barn.

.. Three times a year, the governor's advisory council on historic places shall review the list of barns submitted by the department for formal recognition as a heritage barn.

. Eligible applicants for heritage barn preservation fund awards include property owners, nonprofit organizations, and local governments.

. To apply for support from the heritage barn preservation fund, an applicant must submit an application to the department in a form prescribed by the department. Applicants must provide at least fifty percent of the cost of the project through in-kind labor, the applicant's own moneys, or other funding sources.

. The following types of projects are eligible for funding:

.. Stabilization of endangered heritage barns and related agricultural buildings, including but not limited to repairs to foundations, sills, windows, walls, structural framework, and the repair and replacement of roofs; and

.. Work that preserves the historic character, features, and materials of a historic barn.

. In making awards, the advisory board shall consider the following criteria:

.. Relative historical and cultural significance of the barn;

.. Urgency of the threat and need for repair;

.. Extent to which the project preserves historic character and extends the useful life of the barn or associated agricultural building;

.. Visibility of the barn from a state designated scenic byway or other publicly traveled way;

.. Extent to which the project leverages other sources of financial assistance;

.. Provision for long-term preservation;

.. Readiness of the applicant to initiate and complete the project; and

.. Extent to which the project contributes to the equitable geographic distribution of heritage barn preservation fund awards across the state.

. In awarding funds, special consideration shall be given to barns that are:

.. Still in agricultural use;

.. Listed on the national register of historic places; or

.. Outstanding examples of their type or era.

. The conditions in this subsection must be met by recipients of funding in order to satisfy the public benefit requirements of the heritage barn preservation program.

.. Recipients must execute a contract with the department before commencing work. The contract must include a historic preservation easement for between five to fifteen years depending on the amount of the award. The contract must specify public benefit and minimum maintenance requirements.

.. Recipients must proactively maintain their historic barn for a minimum of ten years.

.. Public access to the exterior of properties that are not visible from a public right-of-way must be provided under reasonable terms and circumstances, including the requirement that visits by nonprofit organizations or school groups must be offered at least one day per year.

. All work must comply with the United States secretary of the interior's standards for the rehabilitation of historic properties; however, exceptions may be made for the retention or installation of metal roofs on a case-by-case basis.

. The heritage barn preservation fund shall be acknowledged on any materials produced and in publicity for the project. A sign acknowledging the fund shall be posted at the worksite for the duration of the preservation agreement.

. Projects must be initiated within one year of funding approval and completed within two years, unless an extension is provided by the department in writing.

. If a recipient of a heritage barn preservation fund award, or subsequent owner of a property that was assisted by the fund, takes any action within ten years of the funding award with respect to the assisted property such as dismantlement, removal, or substantial alteration, which causes it to be no longer eligible for listing in the Washington heritage register, the fund shall be repaid in full within one year.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2115-S.SL.pdf?cite=2007%20c%20333%20§%202[2007 c 333 § 2]; ]

== 27.34.410 - Heritage barn preservation fund.
. The heritage barn preservation fund is created as an account in the state treasury. All receipts from appropriations and private sources must be deposited into the account. Moneys in the account may be spent only after appropriation. Expenditures from the account may be used only to provide assistance to owners of heritage barns in Washington state in the stabilization and restoration of their barns so that these historic properties may continue to serve the community.

. The department shall minimize the amount of funds that are used for program administration, which shall include consultation with the department of enterprise services' barrier-free facilities program for input regarding accessibility for people with disabilities where public access to historic barns is permitted.

. The primary public benefit of funding through the heritage barn preservation program is the preservation and enhancement of significant historic properties that provide economic benefit to the state's citizens and enrich communities throughout the state.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5024.SL.pdf?cite=2015%20c%20225%20§%2024[2015 c 225 § 24]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2115-S.SL.pdf?cite=2007%20c%20333%20§%204[2007 c 333 § 4]; ]

== 27.34.415 - Cemeteries—Burial sites—Centralized database.
The department of archaeology and historic preservation shall develop and maintain a centralized database and geographic information systems spatial layer of all known cemeteries and known sites of burials of human remains in Washington state. The information in the database is subject to public disclosure, except as provided in RCW 42.56.300; exempt information is available by confidentiality agreement to federal, state, and local agencies for purposes of environmental review, and to tribes in order to participate in environmental review, protect their ancestors, and perpetuate their cultures.

Information provided to state and local agencies under this section is subject to public disclosure, except as provided in RCW 42.56.300.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2624-S2.SL.pdf?cite=2008%20c%20275%20§%206[2008 c 275 § 6]; ]

== 27.34.420 - Washington state historic cemetery preservation capital grant program.
. The Washington state historic cemetery preservation capital grant program is created in the department.

. The capital grant program is intended to benefit the public by preserving outstanding examples of the state's historical heritage, enabling historic cemeteries to continue to serve their communities, and honoring the military veterans buried within them.

. Subject to appropriation, grants may be awarded each biennium for construction, renovation, or rehabilitation projects that preserve the historic character, features, and materials of the cemetery, or that maintain or improve the functions of the cemetery.

. A capital grant award may not exceed fifty thousand dollars, adjusted biennially for inflation. The department may not require applicants to provide matching funds.

. Eligible applicants for capital grants include cemetery property owners, nonprofit organizations, and local governments.

. Applications for the capital grant program must be submitted to the department in a form and manner prescribed by the department. The applications must include a history of the cemetery which the department shall maintain on file.

. The director shall establish a committee to review applications. The committee shall consist of at least five members with expertise or association with historic preservation, cemetery associations, local cemetery boards, and other associations or professional organizations the director deems appropriate. When evaluating and prioritizing projects, the committee shall consider the following criteria:

.. The relative historical significance of the cemetery;

.. Whether the proposed project will result in lower costs of maintenance and operations; and

.. The relative percentage of military burials in the cemetery.

. The conditions in this subsection must be met by recipients of funding in order to satisfy the public benefit requirements of the historic cemetery preservation capital grant program.

.. The committee shall provide the department a prioritized list of projects for funding. The department and grant recipient must execute a contract before work on the grant project begins. The contract must specify public benefit and minimum maintenance requirements.

.. Grant recipients must proactively maintain their historic cemetery for a minimum of ten years.

.. Public access to the exterior of properties that are not visible from a public right-of-way must be provided under reasonable terms and circumstances, including the requirement that visits by nonprofit organizations or school groups must be offered at least one day per year. Tribal access must be provided under reasonable terms and circumstances to historic cemeteries in which there are Indian burials.

. Projects must be initiated within one year of funding approval and completed within two years, unless an extension is provided in writing by the department.

. If a recipient of an historic cemetery preservation capital grant, or subsequent owner of a property that was assisted by a grant, takes any action within ten years of the award with respect to the assisted property such as dismantlement, removal, substantial alteration, or any other action inconsistent with the property's status as a cemetery, the grant must be repaid in full within one year.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2637.SL.pdf?cite=2016%20c%20102%20§%201[2016 c 102 § 1]; ]

== 27.34.900 - Historic Lord mansion.
The building and grounds designated as Block 2, Grainger's Addition to the City of Olympia, County of Thurston, acquired by the state under senate joint resolution No. 18, session of 1939, is hereby designated a part of the state capitol, to be known as the historic Lord mansion.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1853.SL.pdf?cite=2017%20c%20117%20§%202[2017 c 117 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5139.SL.pdf?cite=1993%20c%20101%20§%2013[1993 c 101 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c253.pdf?cite=1981%20c%20253%20§%203[1981 c 253 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c44.pdf?cite=1941%20c%2044%20§%203[1941 c 44 § 3]; Rem. Supp. 1941 § 8265-6; ]

== 27.34.906 - Pickett House—In trust—Reverter.
Said chapter, by acceptance of such conveyance, shall be deemed to have agreed to hold said property in trust for the state of Washington, and to maintain and keep the same open to the public as an historical site, and, in case of its failure so to do, title to said property shall revert to the state of Washington.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c31.pdf?cite=1965%20c%2031%20§%202[1965 c 31 § 2]; ]

== 27.34.910 - Effective date—1983 c 91.
This act is necessary for the immediate preservation of the public peace, health, and safety, the support of the state government and its existing public institutions, and shall take effect June 30, 1983.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c91.pdf?cite=1983%20c%2091%20§%2027[1983 c 91 § 27]; ]

== 27.34.916 - Effective date—1993 c 101.
This act is necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and shall take effect July 1, 1993.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5139.SL.pdf?cite=1993%20c%20101%20§%2017[1993 c 101 § 17]; ]

