= 27.48 - Preservation of historical materials.
:toc:

== 27.48.010 - Public purpose declared—Powers of counties and municipalities.
The storage, preservation and exhibit of historical materials, including, but not restricted to, books, maps, writings, newspapers, ancient articles, and tools of handicraft, antiques, artifacts, and relics is declared to be a public project carried on for public purpose and the legislative body of any county, city or town, may provide quarters therefor within the territorial limits thereof and may provide funds necessary for the proper operation of any such institution already in operation, or otherwise provide for the preservation of historical material covered by this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c47.pdf?cite=1957%20c%2047%20§%201[1957 c 47 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c160.pdf?cite=1949%20c%20160%20§%201[1949 c 160 § 1]; Rem. Supp. 1949 § 8265-9; ]

== 27.48.040 - Capitol furnishings preservation committee—Capitol furnishings preservation committee account.
. Unless the context clearly requires otherwise, the definitions in this subsection apply throughout this section.

.. "State capitol group" includes the legislative building, the insurance building, the Cherberg building, the John L. O'Brien building, the Newhouse building, the Pritchard building, and the temple of justice building. "State capitol group" also includes the general administration building if the building is repurposed to serve a different function or substantially remodeled.

.. "Historic furnishings" means furniture, fixtures, and artwork fifty years of age or older.

. The capitol furnishings preservation committee is established to:

.. Promote and encourage the recovery and preservation of the original and historic furnishings of the state capitol group;

.. Prevent future loss of historic furnishings; and

.. Review and advise future remodeling and restoration projects as they pertain to historic furnishings. The committee's authority does not extend to the placement of any historic furnishings within the state capitol group.

. The capitol furnishings preservation committee account is created in the custody of the state treasurer. All receipts designated for the account from appropriations and from other sources must be deposited into the account. Expenditures from the account may be used only to finance the activities of the capitol furnishings preservation committee. Only the director of the Washington state historical society or the director's designee may authorize expenditures from the account when authorized to do so by the committee. The account is subject to allotment procedures under chapter 43.88 RCW, but an appropriation is not required for expenditures.

. The committee may:

.. Authorize the director of the Washington state historical society or the director's designee to expend funds from the capitol furnishings preservation committee account for limited purposes of purchasing and preserving historic furnishings of the state capitol group;

.. Accept monetary donations, grants, and donations of historic furnishings from, but not limited to, (i) current and former legislators, state officials, and lobbyists; (ii) the families of former legislators, state officials, and lobbyists; and (iii) the general public. Moneys received under this section must be deposited in the capitol furnishings preservation committee account;

.. Engage in or encourage fund-raising activities including soliciting charitable gifts, grants, or donations specifically for the limited purpose of the recovery of the original and historic furnishings; and

.. Engage in interpretive and educational activities, including displaying historic furnishings.

. The membership of the committee shall include:

.. Two members of the house of representatives, one from each major caucus, appointed by the speaker of the house of representatives;

.. Two members of the senate, one from each major caucus, appointed by the president of the senate;

.. The chief clerk of the house of representatives or the chief clerk's designee;

.. The secretary of the senate or the secretary's designee;

.. The governor or the governor's designee;

.. The lieutenant governor or the lieutenant governor's designee;

.. A representative from the office of the secretary of state, the office of the state treasurer, the office of the state auditor, and the office of the insurance commissioner;

.. A representative from the supreme court;

.. A representative from the Washington state historical society, the department of enterprise services, and the Thurston regional planning council, each appointed by the governor; and

.. Six private citizens, appointed by the governor.

. Original or historic furnishings from the state capitol group are not surplus property under chapter 43.19 RCW or other authority unless designated as such by the committee.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5176.SL.pdf?cite=2015%20c%2024%20§%201[2015 c 24 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1132-S2.SL.pdf?cite=1999%20c%20343%20§%202[1999 c 343 § 2]; ]

== 27.48.050 - Fund-raising for preservation and restoration of the state legislative building.
State officers and state employees, as those terms are defined in RCW 42.52.010, may engage in or encourage fund-raising activities including the solicitation of charitable gifts, grants, or donations specifically for the limited purpose of preservation and restoration of the state legislative building and related educational exhibits and programs.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2907.SL.pdf?cite=2002%20c%20167%20§%202[2002 c 167 § 2]; ]

