= 74.08 - Eligibility generally—Standards of assistance.
:toc:

== 74.08.025 - Eligibility for public assistance—Temporary assistance for needy families—Limitations for drug or alcohol-dependent persons.
. Public assistance may be awarded to any applicant:

.. Who is in need and otherwise meets the eligibility requirements of department assistance programs; and

.. Who has not made a voluntary assignment of property or cash for the purpose of qualifying for an assistance grant; and

.. Who is not an inmate of a public institution except as a patient in a medical institution or except as an inmate in a public institution who could qualify for federal aid assistance: PROVIDED, That the assistance paid by the department to recipients in nursing homes, or receiving nursing home care, may cover the cost of clothing and incidentals and general maintenance exclusive of medical care and health services. The department may pay a grant to cover the cost of clothing and personal incidentals in public or private medical institutions and institutions for tuberculosis. The department shall allow recipients in nursing homes to retain, in addition to the grant to cover the cost of clothing and incidentals, wages received for work as a part of a training or rehabilitative program designed to prepare the recipient for less restrictive placement to the extent permitted under Title XIX of the federal social security act.

. Any person otherwise qualified for temporary assistance for needy families who is assessed through the state alcohol and substance abuse program as drug or alcohol-dependent and requiring treatment to become employable shall be required by the department to participate in a drug or alcohol treatment program as a condition of benefit receipt.

. Pursuant to 21 U.S.C. 862a(d)(1), the department shall exempt individuals from the eligibility restrictions of 21 U.S.C. 862a(a)(1) and (2) to ensure eligibility for temporary assistance for needy families benefits and federal food assistance.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1603-S2.SL.pdf?cite=2019%20c%20343%20§%201[2019 c 343 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5921-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2042%20§%207[2011 1st sp.s. c 42 § 7]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5213-S2.SL.pdf?cite=2005%20c%20174%20§%202[2005 c 174 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6411.SL.pdf?cite=2004%20c%2054%20§%205[2004 c 54 § 5]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3901.SL.pdf?cite=1997%20c%2058%20§%20101[1997 c 58 § 101]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981ex1c6.pdf?cite=1981%201st%20ex.s.%20c%206%20§%209[1981 1st ex.s. c 6 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c8.pdf?cite=1981%20c%208%20§%208[1981 c 8 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c79.pdf?cite=1980%20c%2079%20§%201[1980 c 79 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c169.pdf?cite=1971%20ex.s.%20c%20169%20§%201[1971 ex.s. c 169 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c31.pdf?cite=1967%20ex.s.%20c%2031%20§%201[1967 ex.s. c 31 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c26.pdf?cite=1959%20c%2026%20§%2074.08.025[1959 c 26 § 74.08.025]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c174.pdf?cite=1953%20c%20174%20§%2019[1953 c 174 § 19]; ]

== 74.08.030 - Old age assistance eligibility requirements.
In addition to meeting the eligibility requirements of RCW 74.08.025, an applicant for old age assistance must be an applicant who:

. Has attained the age of sixty-five: PROVIDED, That if an applicant for old age assistance is already on the assistance rolls in some other program or category of assistance, such applicant shall be considered eligible the first of the month immediately preceding the date on which such applicant will attain the age of sixty-five; and

. Is a resident of the state of Washington.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c169.pdf?cite=1971%20ex.s.%20c%20169%20§%202[1971 ex.s. c 169 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c248.pdf?cite=1961%20c%20248%20§%201[1961 c 248 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c26.pdf?cite=1959%20c%2026%20§%2074.08.030[1959 c 26 § 74.08.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c174.pdf?cite=1953%20c%20174%20§%2020[1953 c 174 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c165.pdf?cite=1951%20c%20165%20§%201[1951 c 165 § 1]; 1951 c 1 § 5 (Initiative Measure No. 178, approved November 7, 1950); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c6.pdf?cite=1949%20c%206%20§%204[1949 c 6 § 4]; Rem. Supp. 1949 § 9998-33d; ]

== 74.08.043 - Need for personal and special care—Authority to consider in determining living requirements.
In determining the living requirements of otherwise eligible applicants and recipients of supplemental security income and benefits under RCW 74.62.030 and 43.185C.220, the department is authorized to consider the need for personal and special care and supervision due to physical and mental conditions.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2082-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2036%20§%2027[2011 1st sp.s. c 36 § 27]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2782-S2.SL.pdf?cite=2010%201st%20sp.s.%20c%208%20§%2024[2010 1st sp.s. c 8 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981ex1c6.pdf?cite=1981%201st%20ex.s.%20c%206%20§%2012[1981 1st ex.s. c 6 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c8.pdf?cite=1981%20c%208%20§%2011[1981 c 8 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c172.pdf?cite=1969%20ex.s.%20c%20172%20§%2010[1969 ex.s. c 172 § 10]; ]

== 74.08.044 - Need for personal and special care—Licensing—Rules and regulations.
The department is authorized to promulgate rules and regulations establishing eligibility for alternate living arrangements, and license the same, including minimum standards of care, based upon need for personal care and supervision beyond the level of board and room only, but less than the level of care required in a hospital or a nursing facility as defined in the federal social security act.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1890.SL.pdf?cite=1991%20sp.s.%20c%208%20§%205[1991 sp.s. c 8 § 5]; 1975-'76 2nd ex.s. c 52 § 1; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c172.pdf?cite=1969%20ex.s.%20c%20172%20§%2011[1969 ex.s. c 172 § 11]; ]

== 74.08.045 - Need for personal and special care—Purchase of personal and special care by department.
The department may purchase such personal and special care at reasonable rates established by the department from substitute homes and intermediate care facilities providing [provided] this service is in compliance with standards of care established by the regulations of the department.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c172.pdf?cite=1969%20ex.s.%20c%20172%20§%2012[1969 ex.s. c 172 § 12]; ]

== 74.08.046 - Energy assistance allowance.
There is designated to be included in the public assistance payment level a monthly energy assistance allowance. The allowance shall be excluded from consideration as income for the purpose of determining eligibility and benefit levels of food stamp or benefits program recipients to the maximum extent exclusion is authorized by federal law. The allowance shall be calculated on a seasonal basis for the period of November 1st through April 30th.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2692.SL.pdf?cite=1998%20c%2079%20§%2014[1998 c 79 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c127.pdf?cite=1982%20c%20127%20§%201[1982 c 127 § 1]; ]

== 74.08.050 - Applications for grants.
Application for a grant in any category of public assistance shall be made to the county office by the applicant or by another on his or her behalf, and shall be reduced to writing upon standard forms prescribed by the department, and a written acknowledgment of receipt of the application by the department shall be given to each applicant at the time of making application.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20198[2013 c 23 § 198]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c169.pdf?cite=1971%20ex.s.%20c%20169%20§%203[1971 ex.s. c 169 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c26.pdf?cite=1959%20c%2026%20§%2074.08.050[1959 c 26 § 74.08.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c174.pdf?cite=1953%20c%20174%20§%2026[1953 c 174 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c6.pdf?cite=1949%20c%206%20§%206[1949 c 6 § 6]; Rem. Supp. 1949 § 9998-33f; ]

== 74.08.055 - Verification of applications—Electronic applications—Penalty.
. Each applicant for or recipient of public assistance shall complete and sign a physical application or, if available, electronic application for assistance which shall contain or be verified by a written declaration that it is signed under the penalties of perjury. The department may make electronic applications available. The secretary, by rule and regulation, may require that any other forms filled out by applicants or recipients of public assistance shall contain or be verified by a written declaration that it is made under the penalties of perjury and such declaration shall be in lieu of any oath otherwise required, and each applicant shall be so informed at the time of the signing. The application and signature verification shall be in accordance with federal requirements for that program.

. Any applicant for or recipient of public assistance who willfully makes and signs any application, statement, other paper, or electronic record which contains or is verified by a written declaration that it is made under the penalties of perjury and which he or she does not believe to be true and correct as to every material matter is guilty of a class B felony punishable according to chapter 9A.20 RCW.

. As used in this section:

.. "Electronic record" means a record created, generated, sent, communicated, received, or stored by electronic means.

.. "Sign" includes signing by physical signature, if available, or electronic signature. An application must contain a signature in either physical or, if available, electronic form.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2089[2020 c 57 § 89]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1270.SL.pdf?cite=2009%20c%20201%20§%201[2009 c 201 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20366[2003 c 53 § 366]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20323[1979 c 141 § 323]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c26.pdf?cite=1959%20c%2026%20§%2074.08.055[1959 c 26 § 74.08.055]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c174.pdf?cite=1953%20c%20174%20§%2027[1953 c 174 § 27]; ]

== 74.08.060 - Action on applications—Ineligibility of inmates—Employment and training services.
The department shall approve or deny the application within forty-five days after filing, and shall immediately notify the applicant in writing of its decision. If the department is not able within forty-five days, despite due diligence, to secure all information necessary to establish eligibility, the department shall continue to secure such information. If such information, when established, makes the applicant eligible, the department shall pay the grant from the date of authorization or forty-five days after the date of application, whichever is earlier, except that the department shall not make payments for any period of time in which the applicant is ineligible for public assistance as an inmate of a public institution under RCW 74.08.025(1)(c).

The department may, in respect to work requirements, provide employment and training services, including job search, job placement, work orientation, and necessary support services to verify eligibility.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6024-S.SL.pdf?cite=2009%20c%20198%20§%201[2009 c 198 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c335.pdf?cite=1985%20c%20335%20§%204[1985 c 335 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981ex1c6.pdf?cite=1981%201st%20ex.s.%20c%206%20§%2013[1981 1st ex.s. c 6 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c173.pdf?cite=1969%20ex.s.%20c%20173%20§%206[1969 ex.s. c 173 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c26.pdf?cite=1959%20c%2026%20§%2074.08.060[1959 c 26 § 74.08.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c174.pdf?cite=1953%20c%20174%20§%2028[1953 c 174 § 28]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c6.pdf?cite=1949%20c%206%20§%207[1949 c 6 § 7]; Rem. Supp. 1949 § 9998-33g; ]

== 74.08.080 - Grievances—Departmental and judicial review.
. [Empty]
.. A public assistance applicant or recipient who is aggrieved by a decision of the department or an authorized agency of the department has the right to an adjudicative proceeding. A current or former recipient who is aggrieved by a department claim that he or she owes a debt for an overpayment of assistance or food stamps or food stamp benefits transferred electronically, or both, has the right to an adjudicative proceeding.

.. An applicant or recipient has no right to an adjudicative proceeding when the sole basis for the department's decision is a state or federal law that requires an assistance adjustment for a class of recipients.

. The adjudicative proceeding is governed by the Administrative Procedure Act, chapter 34.05 RCW, and this subsection.

.. The applicant or recipient must file the application for an adjudicative proceeding with the secretary within ninety days after receiving notice of the aggrieving decision.

.. The hearing shall be conducted at the local community services office or other location in Washington convenient to the appellant.

.. The appellant or his or her representative has the right to inspect his or her department file and, upon request, to receive copies of department documents relevant to the proceedings free of charge.

.. The appellant has the right to a copy of the tape recording of the hearing free of charge.

.. The department is limited to recovering an overpayment arising from assistance being continued pending the adjudicative proceeding to the amount recoverable up to the sixtieth day after the secretary's receipt of the application for an adjudicative proceeding.

.. If the final adjudicative order is made in favor of the appellant, assistance shall be paid from the date of denial of the application for assistance or thirty days following the date of application for temporary assistance for needy families or forty-five days after date of application for all other programs, whichever is sooner; or in the case of a recipient, from the effective date of the local community services office decision.

.. This subsection applies only to an adjudicative proceeding in which the appellant is an applicant for or recipient of medical assistance or the limited casualty program for the medically needy and the issue is his or her eligibility or ineligibility due to the assignment or transfer of a resource. The burden is on the department to prove by a preponderance of the evidence that the person knowingly and willingly assigned or transferred the resource at less than market value for the purpose of qualifying or continuing to qualify for medical assistance or the limited casualty program for the medically needy. If the prevailing party in the adjudicative proceeding is the applicant or recipient, he or she is entitled to reasonable attorney's fees.

. When a person files a petition for judicial review as provided in RCW 34.05.514 of an adjudicative order entered in a public assistance program, no filing fee shall be collected from the person and no bond shall be required on any appeal. In the event that the superior court, the court of appeals, or the supreme court renders a decision in favor of the appellant, said appellant shall be entitled to reasonable attorneys' fees and costs. If a decision of the court is made in favor of the appellant, assistance shall be paid from date of the denial of the application for assistance or thirty days after the application for temporary assistance for needy families or forty-five days following the date of application, whichever is sooner; or in the case of a recipient, from the effective date of the local community services office decision.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2692.SL.pdf?cite=1998%20c%2079%20§%2015[1998 c 79 § 15]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1089-S.SL.pdf?cite=1997%20c%2059%20§%2012[1997 c 59 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c175.pdf?cite=1989%20c%20175%20§%20145[1989 c 175 § 145]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c202.pdf?cite=1988%20c%20202%20§%2058[1988 c 202 § 58]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971c81.pdf?cite=1971%20c%2081%20§%20136[1971 c 81 § 136]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c172.pdf?cite=1969%20ex.s.%20c%20172%20§%202[1969 ex.s. c 172 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c26.pdf?cite=1959%20c%2026%20§%2074.08.080[1959 c 26 § 74.08.080]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c174.pdf?cite=1953%20c%20174%20§%2031[1953 c 174 § 31]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c6.pdf?cite=1949%20c%206%20§%209[1949 c 6 § 9]; Rem. Supp. 1949 § 9998-33i; ]

== 74.08.090 - Rule-making authority and enforcement.
The department is hereby authorized to make rules and regulations not inconsistent with the provisions of this title to the end that this title shall be administered uniformly throughout the state, and that the spirit and purpose of this title may be complied with. The department shall have the power to compel compliance with the rules and regulations established by it. Such rules and regulations shall be filed in accordance with the Administrative Procedure Act, as it is now or hereafter amended, and copies shall be available for public inspection in the office of the department and in each county office.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c173.pdf?cite=1969%20ex.s.%20c%20173%20§%205[1969 ex.s. c 173 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c26.pdf?cite=1959%20c%2026%20§%2074.08.090[1959 c 26 § 74.08.090]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c174.pdf?cite=1953%20c%20174%20§%205[1953 c 174 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c6.pdf?cite=1949%20c%206%20§%2010[1949 c 6 § 10]; Rem. Supp. 1949 § 9998-33j; ]

== 74.08.100 - Age and residency verification—Felony.
Proof of age and length of residence in the state of any applicant may be established as provided by the rules and regulations of the department: PROVIDED, That if an applicant is unable to establish proof of age or length of residence in the state by any other method he or she may make a statement under oath of his or her age on the date of application or the length of his or her residence in the state, before any judge of the superior court, any judge of the court of appeals, or any justice of the supreme court of the state of Washington, and such statement shall constitute sufficient proof of age of applicant or of length of residence in the state: PROVIDED HOWEVER, That any applicant who willfully makes a false statement as to his or her age or length of residence in the state under oath before a judge of the superior court, a judge of the court of appeals, or a justice of the supreme court, as provided above, shall be guilty of a class B felony punishable according to chapter 9A.20 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20367[2003 c 53 § 367]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971c81.pdf?cite=1971%20c%2081%20§%20137[1971 c 81 § 137]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c26.pdf?cite=1959%20c%2026%20§%2074.08.100[1959 c 26 § 74.08.100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c6.pdf?cite=1949%20c%206%20§%2011[1949 c 6 § 11]; Rem. Supp. 1949 § 9998-33k; ]

== 74.08.105 - Out-of-state recipients.
No assistance payments shall be made to recipients living outside the state of Washington unless in the discretion of the secretary there is sound social reason for such out-of-state payments: PROVIDED, That the period for making such payments when authorized shall not exceed the length of time required to satisfy the residence requirements in the other state in order to be eligible for a grant in the same category of assistance as the recipient was eligible to receive in Washington.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20325[1979 c 141 § 325]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c26.pdf?cite=1959%20c%2026%20§%2074.08.105[1959 c 26 § 74.08.105]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c174.pdf?cite=1953%20c%20174%20§%2039[1953 c 174 § 39]; ]

== 74.08.210 - Grants not assignable nor subject to execution.
Grants awarded under this title shall not be transferable or assignable, at law or in equity, and none of the money paid or payable under this title shall be subject to execution, levy, attachment, garnishment, or other legal process, or to the operation of bankruptcy or insolvency law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c26.pdf?cite=1959%20c%2026%20§%2074.08.210[1959 c 26 § 74.08.210]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c1.pdf?cite=1941%20c%201%20§%2016[1941 c 1 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c182.pdf?cite=1935%20c%20182%20§%2017[1935 c 182 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c29.pdf?cite=1933%20c%2029%20§%2013[1933 c 29 § 13]; Rem. Supp. 1941 § 9998-49; ]

== 74.08.260 - Federal act to control in event of conflict.
If any plan of administration of this title submitted to the federal security agency shall be found to be not in conformity with the federal social security act by reason of any conflict of any section, portion, clause or part of this title and the federal social security act, such conflicting section, portion, clause or part of this title is hereby declared to be inoperative to the extent that it is so in conflict, and such finding or determination shall not affect the remainder of this title.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c26.pdf?cite=1959%20c%2026%20§%2074.08.260[1959 c 26 § 74.08.260]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c6.pdf?cite=1949%20c%206%20§%2017[1949 c 6 § 17]; Rem. Supp. 1949 § 9998-33q; ]

== 74.08.278 - Central operating fund established.
In order to comply with federal statutes and regulations pertaining to federal matching funds and to provide for the prompt payment of initial grants and adjusting payments of grants the secretary is authorized to make provisions for the cash payment of assistance by the secretary or county administrators by the establishment of a central operating fund. The secretary may establish such a fund with the approval of the state auditor from moneys appropriated to the department for the payment of benefits under RCW 74.62.030 in a sum not to exceed one million dollars. Such funds shall be deposited as agreed upon by the secretary and the state auditor in accordance with the laws regulating the deposits of public funds. Such security shall be required of the depository in connection with the fund as the state treasurer may prescribe. Moneys remaining in the fund shall be returned to the general fund at the end of the biennium, or an accounting of proper expenditures from the fund shall be made to the state auditor. All expenditures from such central operating fund shall be reimbursed out of and charged to the proper program appropriated by the use of such forms and vouchers as are approved by the secretary of the department and the state auditor. Expenditures from such fund shall be audited by the director of financial management and the state auditor from time to time and a report shall be made by the state auditor and the secretary as are required by law.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2082-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2036%20§%2028[2011 1st sp.s. c 36 § 28]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2782-S2.SL.pdf?cite=2010%201st%20sp.s.%20c%208%20§%2025[2010 1st sp.s. c 8 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20327[1979 c 141 § 327]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c26.pdf?cite=1959%20c%2026%20§%2074.08.278[1959 c 26 § 74.08.278]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c174.pdf?cite=1953%20c%20174%20§%2042[1953 c 174 § 42]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c261.pdf?cite=1951%20c%20261%20§%201[1951 c 261 § 1]; ]

== 74.08.280 - Payments to persons incapable of self-care—Protective payee services.
If any person receiving public assistance has demonstrated an inability to care for oneself or for money, the department may direct the payment of the installments of public assistance to any responsible person, social service agency, or corporation or to a legally appointed guardian for his or her benefit. The state may contract with persons, social service agencies, or corporations approved by the department to provide protective payee services for a fixed amount per recipient receiving protective payee services to cover administrative costs. The department may by rule specify a fee to cover administrative costs. Such fee shall not be withheld from a recipient's grant.

If the state requires the appointment of a guardian for this purpose, the department shall pay all costs and reasonable fees as fixed by the court.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20199[2013 c 23 § 199]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c406.pdf?cite=1987%20c%20406%20§%2010[1987 c 406 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20328[1979 c 141 § 328]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c26.pdf?cite=1959%20c%2026%20§%2074.08.280[1959 c 26 § 74.08.280]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c174.pdf?cite=1953%20c%20174%20§%2040[1953 c 174 § 40]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c156.pdf?cite=1937%20c%20156%20§%207[1937 c 156 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c182.pdf?cite=1935%20c%20182%20§%2010[1935 c 182 § 10]; RRS § 9998-10; ]

== 74.08.283 - Services provided to attain self-care.
The department is authorized to provide such social and related services as are reasonably necessary to the end that applicants for or recipients of public assistance are helped to attain self-care.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c228.pdf?cite=1963%20c%20228%20§%2016[1963 c 228 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c26.pdf?cite=1959%20c%2026%20§%2074.08.283[1959 c 26 § 74.08.283]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c63.pdf?cite=1957%20c%2063%20§%206[1957 c 63 § 6]; ]

== 74.08.290 - Suspension of payments—Need lapse—Imprisonment—Conviction under RCW  74.08.331.
The department is hereby authorized to suspend temporarily the public assistance granted to any person for any period during which such person is not in need thereof.

If a recipient is convicted of any crime or offense, and punished by imprisonment, no payment shall be made during the period of imprisonment.

If a recipient is convicted of unlawful practices under RCW 74.08.331, no payment shall be made for a period to be determined by the court, but in no event less than six months upon the first conviction and no less than twelve months for a second or subsequent violation. This suspension of public assistance shall apply regardless of whether the recipient is subject to complete or partial confinement upon conviction, or incurs some lesser penalty.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5652.SL.pdf?cite=1995%20c%20379%20§%202[1995 c 379 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c26.pdf?cite=1959%20c%2026%20§%2074.08.290[1959 c 26 § 74.08.290]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c174.pdf?cite=1953%20c%20174%20§%2038[1953 c 174 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c182.pdf?cite=1935%20c%20182%20§%2012[1935 c 182 § 12]; RRS § 9998-12; ]

== 74.08.331 - Unlawful practices—Obtaining assistance—Disposal of realty—Penalties.
. Any person who by means of a willfully false statement, or representation, or impersonation, or a willful failure to reveal any material fact, condition, or circumstance affecting eligibility or need for assistance, including medical care, surplus commodities, and food stamps or food stamp benefits transferred electronically, as required by law, or a willful failure to promptly notify the county office in writing as required by law or any change in status in respect to resources, or income, or need, or family composition, money contribution and other support, from whatever source derived, including unemployment insurance, or any other change in circumstances affecting the person's eligibility or need for assistance, or other fraudulent device, obtains, or attempts to obtain, or aids or abets any person to obtain any public assistance to which the person is not entitled or greater public assistance than that to which he or she is justly entitled is guilty of theft in the first degree under RCW 9A.56.030 and upon conviction thereof shall be punished by imprisonment in a state correctional facility for not more than fifteen years.

. Any person who by means of a willfully false statement or representation or by impersonation or other fraudulent device aids or abets in buying, selling, or in any other way disposing of the real property of a recipient of public assistance without the consent of the secretary is guilty of a gross misdemeanor and upon conviction thereof shall be punished by imprisonment for up to three hundred sixty-four days in the county jail or a fine of not to exceed one thousand dollars or by both.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5168-S.SL.pdf?cite=2011%20c%2096%20§%2053[2011 c 96 § 53]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20368[2003 c 53 § 368]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2692.SL.pdf?cite=1998%20c%2079%20§%2016[1998 c 79 § 16]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3901.SL.pdf?cite=1997%20c%2058%20§%20303[1997 c 58 § 303]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2263-S.SL.pdf?cite=1992%20c%207%20§%2059[1992 c 7 § 59]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20329[1979 c 141 § 329]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c34.pdf?cite=1965%20ex.s.%20c%2034%20§%201[1965 ex.s. c 34 § 1]; ]

== 74.08.335 - Transfers of property to qualify for assistance.
Temporary assistance for needy families and benefits under RCW 74.62.030 and 43.185C.220 shall not be granted to any person who has made an assignment or transfer of property for the purpose of rendering himself or herself eligible for the assistance. There is a rebuttable presumption that a person who has transferred or transfers any real or personal property or any interest in property within two years of the date of application for the assistance without receiving adequate monetary consideration therefor, did so for the purpose of rendering himself or herself eligible for the assistance. Any person who transfers property for the purpose of rendering himself or herself eligible for assistance, or any person who after becoming a recipient transfers any property or any interest in property without the consent of the secretary, shall be ineligible for assistance for a period of time during which the reasonable value of the property so transferred would have been adequate to meet the person's needs under normal conditions of living: PROVIDED, That the secretary is hereby authorized to allow exceptions in cases where undue hardship would result from a denial of assistance.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2082-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2036%20§%2029[2011 1st sp.s. c 36 § 29]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2782-S2.SL.pdf?cite=2010%201st%20sp.s.%20c%208%20§%2026[2010 1st sp.s. c 8 § 26]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1089-S.SL.pdf?cite=1997%20c%2059%20§%2013[1997 c 59 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c79.pdf?cite=1980%20c%2079%20§%202[1980 c 79 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20330[1979 c 141 § 330]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c26.pdf?cite=1959%20c%2026%20§%2074.08.335[1959 c 26 § 74.08.335]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c174.pdf?cite=1953%20c%20174%20§%2033[1953 c 174 § 33]; ]

== 74.08.338 - Real property transfers for inadequate consideration.
When the consideration for a deed executed and delivered by a recipient is not paid, or when the consideration does not approximate the fair cash market value of the property, such deed shall be prima facie fraudulent as to the state and the department may proceed under RCW 43.20B.660.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c75.pdf?cite=1987%20c%2075%20§%2040[1987 c 75 § 40]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20331[1979 c 141 § 331]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c26.pdf?cite=1959%20c%2026%20§%2074.08.338[1959 c 26 § 74.08.338]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c174.pdf?cite=1953%20c%20174%20§%2037[1953 c 174 § 37]; ]

== 74.08.340 - No vested rights conferred.
All assistance granted under this title shall be deemed to be granted and to be held subject to the provisions of any amending or repealing act that may hereafter be enacted, and no recipient shall have any claim for compensation, or otherwise, by reason of his or her assistance being affected in any way by such amending or repealing act. There is no legal entitlement to public assistance.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20200[2013 c 23 § 200]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3901.SL.pdf?cite=1997%20c%2058%20§%20102[1997 c 58 § 102]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c26.pdf?cite=1959%20c%2026%20§%2074.08.340[1959 c 26 § 74.08.340]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c182.pdf?cite=1935%20c%20182%20§%2021[1935 c 182 § 21]; RRS § 9998-21; ]

== 74.08.370 - Old age assistance grants charged against general fund.
All old age assistance grants under this title shall be a charge against and payable out of the general fund of the state. Payment thereof shall be by warrant drawn upon vouchers duly prepared and verified by the secretary of the department of social and health services or his or her official representative.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20201[2013 c 23 § 201]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c106.pdf?cite=1973%20c%20106%20§%2033[1973 c 106 § 33]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c26.pdf?cite=1959%20c%2026%20§%2074.08.370[1959 c 26 § 74.08.370]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c182.pdf?cite=1935%20c%20182%20§%2024[1935 c 182 § 24]; RRS § 9998-24. FORMER PART OF SECTION:  1935 c 182 § 25; RRS § 9998-25, now codified as RCW  74.08.375; ]

== 74.08.380 - Acceptance of federal act.
The state hereby accepts the provisions of that certain act of the congress of the United States entitled, An Act to provide for the general welfare by establishing a system of federal old age benefits, and by enabling the several states to make more adequate provisions for aged persons, blind persons, dependent and crippled children, maternal and child welfare, public health, and the administration of their unemployment compensation laws; to establish a social security board; to raise revenue; and for other purposes, and such other act with like or similar objects as may be enacted.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c26.pdf?cite=1959%20c%2026%20§%2074.08.380[1959 c 26 § 74.08.380]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c156.pdf?cite=1937%20c%20156%20§%2012[1937 c 156 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c182.pdf?cite=1935%20c%20182%20§%2026[1935 c 182 § 26]; RRS § 9998-26; ]

== 74.08.390 - Research, projects, to effect savings by restoring self-support—Waiver of public assistance requirements.
The department of social and health services may conduct research studies, pilot projects, demonstration projects, surveys and investigations for the purpose of determining methods to achieve savings in public assistance programs by means of restoring individuals to maximum self-support and personal independence and preventing social and physical disablement, and for the accomplishment of any of such purposes may employ consultants or enter into contracts with any agency of the federal, state or local governments, nonprofit corporations, universities or foundations.

Pursuant to this authority the department may waive the enforcement of specific statutory requirements, regulations, and standards in one or more counties or on a statewide basis by formal order of the secretary. The order establishing the waiver shall provide alternative methods and procedures of administration, shall not be in conflict with the basic purposes, coverage, or benefits provided by law, shall not be general in scope but shall apply only for the duration of such a project and shall not take effect unless the secretary of health, education and welfare of the United States has agreed, for the same project, to waive the public assistance plan requirements relative to statewide uniformity.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20332[1979 c 141 § 332]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c173.pdf?cite=1969%20ex.s.%20c%20173%20§%207[1969 ex.s. c 173 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c228.pdf?cite=1963%20c%20228%20§%2017[1963 c 228 § 17]; ]

== 74.08.580 - Electronic benefit cards—Prohibited uses—Violations.
. Any person receiving public assistance is prohibited from using electronic benefit cards or cash obtained with electronic benefit cards:

.. For the purpose of participating in any of the activities authorized under chapter 9.46 RCW;

.. For the purpose of parimutuel wagering authorized under chapter 67.16 RCW;

.. To purchase lottery tickets or shares authorized under chapter 67.70 RCW;

.. For the purpose of participating in or purchasing any activities located in a tattoo, body piercing, or body art shop licensed under chapter 18.300 RCW;

.. To purchase cigarettes as defined in RCW 82.24.010 or tobacco products as defined in RCW 82.26.010;

.. To purchase any items regulated under Title 66 RCW; or

.. For the purpose of purchasing or participating in any activities in any location listed in subsection (2) of this section.

. The following businesses must disable the ability of ATM and point-of-sale machines located on their business premises to accept the electronic benefit card:

.. Taverns licensed under RCW 66.24.330;

.. Beer/wine specialty stores licensed under RCW 66.24.371 except if the licensee is an authorized supplemental nutrition assistance program or women, infants, and children retailer;

.. Nightclubs licensed under RCW 66.24.600;

.. Bail bond agencies regulated under chapter 18.185 RCW;

.. Gambling establishments licensed under chapter 9.46 RCW;

.. Tattoo, body piercing, or body art shops regulated under chapter 18.300 RCW;

.. Adult entertainment venues with performances that contain erotic material where minors under the age of eighteen are prohibited under RCW 9.68A.150; and

.. Any establishments where persons under the age of eighteen are not permitted.

. The department must notify the licensing authority of any business listed in subsection (2) of this section that such business has continued to allow the use of the electronic benefit card in violation of subsection (2) of this section.

. Only the recipient, an eligible member of the household, or the recipient's authorized representative may use an electronic benefit card or the benefit and such use shall only be for the respective benefit program purposes. Unless a recipient's family member is an eligible member of the household, the recipient's authorized representative, an alternative cardholder, or has been assigned as a protective payee, no family member may use the benefit card. The recipient shall not sell, or attempt to sell, exchange, or donate an electronic benefit card or any benefits to any other person or entity.

. The first violation of subsection (1) of this section by a recipient constitutes a class 4 civil infraction under RCW 7.80.120. Second and subsequent violations of subsection (1) of this section constitute a class 3 civil infraction under RCW 7.80.120.

.. The department shall notify, in writing, all recipients of electronic benefit cards that any violation of subsection (1) of this section could result in legal proceedings and forfeiture of all cash public assistance.

.. Whenever the department receives notice that a person has violated subsection (1) of this section, the department shall notify the person in writing that the violation could result in legal proceedings and forfeiture of all cash public assistance.

.. The department shall assign a protective payee to the person receiving public assistance who violates subsection (1) of this section two or more times.

. In assigning a personal identification number to an electronic benefit card, the department shall not routinely use any sequence of numbers that appear on the card except in circumstances resulting from in-state or national disasters. Personal identification numbers assigned to electronic benefit cards issued to support the distribution of benefits when there is a disaster may include a sequence of numbers that appears on the card.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6136.SL.pdf?cite=2020%20c%2064%20§%201[2020 c 64 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6386-S.SL.pdf?cite=2012%20c%20253%20§%202[2012 c 253 § 2]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5921-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2042%20§%2014[2011 1st sp.s. c 42 § 14]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2767-S.SL.pdf?cite=2002%20c%20252%20§%201[2002 c 252 § 1]; ]

== 74.08.582 - Electronic benefit cards—Names of two or more persons.
A person who has in his or her possession or under his or her control electronic benefit cards issued in the names of two or more persons and who is not authorized by those persons to have any of the cards in his or her possession is guilty of a misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6386-S.SL.pdf?cite=2012%20c%20253%20§%203[2012 c 253 § 3]; ]

== 74.08.900 - Limited application.
Nothing in this chapter except RCW * 74.08.070 and 74.08.080 applies to **chapter 74.50 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c3.pdf?cite=1989%20c%203%20§%203[1989 c 3 § 3]; ]

