= 74.18 - Department of services for the blind.
:toc:

== 74.18.010 - Intent.
The purposes of this chapter are to promote employment and independence of blind persons in the state of Washington through their complete integration into society on the basis of equality, and to encourage public acceptance of the abilities of blind persons.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5705.SL.pdf?cite=2003%20c%20409%20§%202[2003 c 409 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c194.pdf?cite=1983%20c%20194%20§%201[1983 c 194 § 1]; ]

== 74.18.020 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Department" means an agency of state government called the department of services for the blind.

. "Director" means the director of the department of services for the blind. The director is appointed by the governor with the consent of the senate.

. "Rehabilitation council for the blind" means the body of members appointed by the governor in accordance with the provisions of RCW 74.18.070 to advise the state agency.

. "Blind person" means a person who: (a) Has no vision or whose vision with corrective lenses is so limited that the individual requires alternative methods or skills to do efficiently those things that are ordinarily done with sight by individuals with normal vision; (b) has an eye condition of a progressive nature which may lead to blindness; or (c) is blind for purposes of the business enterprise program as set forth in RCW 74.18.200 through 74.18.230 in accordance with requirements of the Randolph-Sheppard Act of 1936.

. "Telephonic reading service" means audio information provided by telephone, including the acquisition and distribution of daily newspapers and other information of local, state, or national interest.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5705.SL.pdf?cite=2003%20c%20409%20§%203[2003 c 409 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c194.pdf?cite=1983%20c%20194%20§%202[1983 c 194 § 2]; ]

== 74.18.030 - Department created.
There is hereby created an agency of state government to be known as the department of services for the blind. The department shall deliver services to blind persons to the extent that appropriations are made available, provided that applicants meet the eligibility criteria for services authorized by this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c194.pdf?cite=1983%20c%20194%20§%203[1983 c 194 § 3]; ]

== 74.18.040 - Director—Appointment—Salary.
The executive head of the department shall be the director of the department of services for the blind. The director shall be appointed by the governor, with the consent of the senate, and hold office at the pleasure of the governor. The director's salary shall be fixed by the governor in accordance with the provisions of RCW 43.03.040.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c194.pdf?cite=1983%20c%20194%20§%204[1983 c 194 § 4]; ]

== 74.18.045 - Telephonic reading service.
. [Empty]
.. The director shall provide access to a telephonic reading service for blind persons and persons with disabilities.

.. The director shall establish criteria for eligibility for blind persons and persons with disabilities who may receive the telephonic reading services. The criteria may be based upon the eligibility criteria for persons who receive services established by the national library service for the blind and print disabled of the library of congress.

. The director may enter into contracts or other agreements that he or she determines to be appropriate to provide telephonic reading services pursuant to this section.

. The director may expand the type and scope of materials available on the telephonic reading service in order to meet the local, regional, or foreign language needs of blind or visually impaired residents of this state. The director may also expand the scope of services and availability of telephonic reading services by current methods and technologies that may be developed. The director may inform current and potential patrons of the availability of telephonic reading services through appropriate means, including, but not limited to, direct mailings, direct telephonic contact, and public service announcements.

. The director may expend moneys from the business enterprises revolving account accrued from vending machine sales in state and local government buildings, as well as donations and grants, for the purpose of supporting the cost of activities described in this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2390.SL.pdf?cite=2020%20c%20274%20§%2065[2020 c 274 § 65]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5705.SL.pdf?cite=2003%20c%20409%20§%204[2003 c 409 § 4]; ]

== 74.18.050 - Appointment of personnel.
The director may appoint such personnel as necessary, none of whom shall be members of the rehabilitation council for the blind. The director and other personnel who are assigned substantial responsibility for formulating agency policy or directing and controlling a major administrative division, together with their confidential secretaries, up to a maximum of six persons, shall be exempt from the provisions of chapter 41.06 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5705.SL.pdf?cite=2003%20c%20409%20§%205[2003 c 409 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c194.pdf?cite=1983%20c%20194%20§%205[1983 c 194 § 5]; ]

== 74.18.060 - Department—Powers and duties.
The department shall:

. Serve as the sole agency of the state for contracting for and disbursing all federal and state funds appropriated for programs established by and within the jurisdiction of this chapter, and make reports and render accounting as may be required;

. Adopt rules, in accordance with chapter 34.05 RCW, necessary to carry out the purposes of this chapter;

. Negotiate agreements with other state agencies to provide services so that individuals of any age who are blind or are both blind and otherwise disabled receive the most beneficial services.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5705.SL.pdf?cite=2003%20c%20409%20§%206[2003 c 409 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c194.pdf?cite=1983%20c%20194%20§%206[1983 c 194 § 6]; ]

== 74.18.070 - Rehabilitation council for the blind—Membership.
. There is hereby created the rehabilitation council for the blind. The rehabilitation council shall consist of the minimum number of voting members to meet the requirements of the rehabilitation council required under the federal rehabilitation act of 1973 as now or hereafter amended. A majority of the voting members shall be blind persons. Rehabilitation councilmembers shall be residents of the state of Washington, and shall be appointed in accordance with the categories of membership specified in the federal rehabilitation act of 1973 as now or hereafter amended. The director of the department shall be an ex officio, nonvoting member.

. The governor shall appoint members of the rehabilitation council for terms of three years, except that the initial appointments shall be as follows: (a) Three members for terms of three years; (b) two members for terms of two years; and (c) other members for terms of one year. Vacancies in the membership of the rehabilitation council shall be filled by the governor for the remainder of the unexpired term.

. The governor may remove members of the rehabilitation council for cause.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5705.SL.pdf?cite=2003%20c%20409%20§%207[2003 c 409 § 7]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2853.SL.pdf?cite=2000%20c%2057%20§%201[2000 c 57 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c194.pdf?cite=1983%20c%20194%20§%207[1983 c 194 § 7]; ]

== 74.18.080 - Rehabilitation council for the blind—Meetings—Travel expenses.
. The rehabilitation council for the blind shall meet officially with the director of the department quarterly to perform the duties enumerated in RCW 74.18.090. Additional meetings of the rehabilitation council may be convened at the call of the chairperson or of a majority of the members. The rehabilitation council shall elect a chairperson from among its members for a term of one year or until a successor has been elected.

. Rehabilitation councilmembers shall receive reimbursement for travel expenses incurred in the performance of their official duties in accordance with RCW 43.03.050 and 43.03.060.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2853.SL.pdf?cite=2000%20c%2057%20§%202[2000 c 57 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c194.pdf?cite=1983%20c%20194%20§%208[1983 c 194 § 8]; ]

== 74.18.090 - Rehabilitation council for the blind—Powers.
The rehabilitation council for the blind may:

. Provide counsel to the director in developing, reviewing, making recommendations, and agreeing on the department's state plan for vocational rehabilitation, budget requests, permanent rules concerning services to blind persons, and other major policies which impact the quality or quantity of services for blind persons;

. Undertake annual reviews with the director of the needs of blind persons, the effectiveness of the services and priorities of the department to meet those needs, and the measures that could be taken to improve the department's services;

. Annually make recommendations to the governor and the legislature on issues related to the department, other state agencies, or state laws which have a significant effect on the opportunities, services, or rights of blind persons;

. Advise and make recommendations to the governor on the criteria and qualifications pertinent to the selection of the director;

. Perform additional functions as required by the federal rehabilitation act of 1973 as now or hereafter amended.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5705.SL.pdf?cite=2003%20c%20409%20§%208[2003 c 409 § 8]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2853.SL.pdf?cite=2000%20c%2057%20§%203[2000 c 57 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c194.pdf?cite=1983%20c%20194%20§%209[1983 c 194 § 9]; ]

== 74.18.100 - Rehabilitation council for the blind—Director to consult.
It shall be the duty of the director to consult in a timely manner with the rehabilitation council for the blind on the matters enumerated in RCW 74.18.090. The director shall provide appropriate departmental resources for the use of the rehabilitation council in conducting its official business.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2853.SL.pdf?cite=2000%20c%2057%20§%204[2000 c 57 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c194.pdf?cite=1983%20c%20194%20§%2010[1983 c 194 § 10]; ]

== 74.18.110 - Receipt of gifts, grants, and bequests.
The department may receive, accept, and disburse gifts, grants, conveyances, devises, and bequests from public or private sources, in trust or otherwise, if the terms and conditions thereof will provide services for blind persons in a manner consistent with the purposes of this chapter and with other provisions of law. Any money so received shall be deposited in the state treasury for investment or expenditure in accordance with the conditions of its receipt.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5705.SL.pdf?cite=2003%20c%20409%20§%209[2003 c 409 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c194.pdf?cite=1983%20c%20194%20§%2011[1983 c 194 § 11]; ]

== 74.18.120 - Administrative hearing—Appeal—Rules.
. An applicant or eligible person who is dissatisfied with a decision, action, or inaction made by the department or its agents regarding that person's eligibility or department services provided to that person is entitled to an administrative hearing. Such administrative hearings shall be conducted pursuant to chapter 34.05 RCW by an administrative law judge.

. The applicant or eligible individual may appeal final decisions issued following administrative hearings under RCW 34.05.510 through 34.05.598.

. The department shall develop rules governing other processes for dispute resolution as required under the federal rehabilitation act of 1973.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5705.SL.pdf?cite=2003%20c%20409%20§%2010[2003 c 409 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c175.pdf?cite=1989%20c%20175%20§%20150[1989 c 175 § 150]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c194.pdf?cite=1983%20c%20194%20§%2012[1983 c 194 § 12]; ]

== 74.18.123 - Background checks—Individuals having unsupervised access to persons with significant disabilities—Rules.
. The department shall investigate the conviction records, pending charges, and disciplinary board final decisions of individuals acting on behalf of the department who will or may have unsupervised access to persons with significant disabilities as defined by the federal rehabilitation act of 1973. This includes:

.. Current employees of the department;

.. Applicants seeking or being considered for any position with the department; and

.. Any service provider, contractor, student intern, volunteer, or other individual acting on behalf of the department.

. The investigation shall consist of a background check as allowed through the Washington state criminal records privacy act under RCW 10.97.050, the Washington state patrol criminal identification system under RCW 43.43.832 through 43.43.834, and the federal bureau of investigation. The background check shall include a fingerprint check using a complete Washington state criminal identification fingerprint card. If the applicant or service provider has had a background check within the previous two years, the department may waive the requirement.

. When necessary, applicants may be employed and service providers may be engaged on a conditional basis pending completion of the background check.

. The department shall use the information solely to determine the character, suitability, and competence of employees, applicants, service providers, contractors, student interns, volunteers, and other individuals in accordance with RCW 41.06.475.

. The department shall adopt rules addressing procedures for undertaking background checks which shall include, but not be limited to, the following:

.. The manner in which the individual will be provided access to and review of information obtained based on the background check required;

.. Assurance that access to background check information shall be limited to only those individuals processing the information at the department;

.. Action that shall be taken against a current employee, service provider, contractor, student intern, or volunteer who is disqualified from a position because of a background check not previously performed.

. The department shall determine who will pay costs associated with the background check.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5705.SL.pdf?cite=2003%20c%20409%20§%2011[2003 c 409 § 11]; ]

== 74.18.127 - Confidentiality of personal information, records—Rules.
. Personal information and records obtained and retained by the department concerning applicants and eligible individuals are confidential, are not subject to public disclosure, and may be released only in accordance with law or with this provision.

. The department shall adopt rules and develop contract language to safeguard the confidentiality of all personal information, including photographs and lists of names. Rules and contract language shall ensure that:

.. Specific safeguards are established to protect all current and future stored personal information;

.. Specific safeguards and procedures are established for the release of personal health information in accordance with the health insurance portability and accountability act of 1996, 45 C.F.R. 160 through 45 C.F.R. 164;

.. All applicants and eligible individuals and, as appropriate, those individuals' representatives, service providers, cooperating agencies, and interested persons are informed upon initial intake of the confidentiality of personal information and the conditions for accessing and releasing this information;

.. All applicants or their representatives are informed about the department's need to collect personal information and the policies governing its use, including: (i) Identification of the authority under which information is collected; (ii) explanation of the principal purposes for which the department intends to use or release the information; (iii) explanation of whether providing requested information to the department is mandatory or voluntary and the effects of not providing requested information; (iv) identification of those situations in which the department requires or does not require informed written consent of the individual before information may be released; and (v) identification of other agencies to which information is routinely released; and

.. An explanation of department policies and procedures affecting personal information will be provided at intake or on request to each individual in that individual's native language and in an appropriate format including but not limited to braille, audio recording, electronic media, or large print.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5705.SL.pdf?cite=2003%20c%20409%20§%2012[2003 c 409 § 12]; ]

== 74.18.130 - Vocational rehabilitation—Eligibility.
The department shall provide a program of vocational rehabilitation to assist blind persons to overcome barriers to employment and to develop skills necessary for employment and independence. Applicants eligible for vocational rehabilitation services shall be blind persons who also meet eligibility requirements as specified in the federal rehabilitation act of 1973.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5705.SL.pdf?cite=2003%20c%20409%20§%2013[2003 c 409 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c194.pdf?cite=1983%20c%20194%20§%2013[1983 c 194 § 13]; ]

== 74.18.140 - Vocational rehabilitation—Services.
The department shall ensure that vocational rehabilitation services in accordance with requirements under the federal rehabilitation act of 1973 are available to meet the identified requirements of each eligible individual in preparing for, securing, retaining, or regaining an employment outcome that is consistent with the individual's strengths, resources, priorities, concerns, abilities, capabilities, interests, and informed choice.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5705.SL.pdf?cite=2003%20c%20409%20§%2014[2003 c 409 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c194.pdf?cite=1983%20c%20194%20§%2014[1983 c 194 § 14]; ]

== 74.18.150 - Vocational rehabilitation—Grants of equipment and material.
The department may grant to eligible participants in the vocational rehabilitation program equipment and materials in accordance with the provisions related to transfer of capital assets as set forth by the office of financial management in the state administrative and accounting manual, provided that the equipment or materials are required by the individual's plan for employment and are used in a manner consistent therewith. The department shall adopt rules to implement this section.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5705.SL.pdf?cite=2003%20c%20409%20§%2015[2003 c 409 § 15]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2187.SL.pdf?cite=1996%20c%207%20§%201[1996 c 7 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c194.pdf?cite=1983%20c%20194%20§%2015[1983 c 194 § 15]; ]

== 74.18.170 - Rehabilitation or habilitation facilities authorized.
The department may establish, construct, and/or operate rehabilitation or habilitation facilities to provide instruction in alternative skills necessary to adjust to blindness or substantial vision loss, to assist blind persons to develop increased confidence and independence, or to provide other services consistent with the purposes of this chapter. The department shall adopt rules concerning selection criteria for participation, services, and other matters necessary for efficient and effective operation of such facilities.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5705.SL.pdf?cite=2003%20c%20409%20§%2016[2003 c 409 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c194.pdf?cite=1983%20c%20194%20§%2016[1983 c 194 § 16]; ]

== 74.18.180 - Services for independent living.
. The department may provide a program of independent living services for blind persons who are not seeking vocational rehabilitation services.

. Independent living services may include, but are not limited to, instruction in adaptive skills of blindness, counseling regarding adjustment to vision loss, and provision of adaptive devices that enable service recipients to participate in the community and maintain or increase their independence.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5705.SL.pdf?cite=2003%20c%20409%20§%2017[2003 c 409 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c194.pdf?cite=1983%20c%20194%20§%2018[1983 c 194 § 18]; ]

== 74.18.190 - Services to blind children and their families.
. The department may offer services to assist blind children and their families to learn skills and locate resources which increase the child's ability for personal development and participation in society.

. Services provided under this section may include:

.. Direct consultation with blind children and their families to provide needs assessment, counseling, developmental training, adaptive skills, and information regarding other available resources;

.. Consultation and technical assistance in all sectors of society, at the request of a blind child, his or her family, or a service provider working with the child or family, to assure the blind child's rights to participate fully in educational, vocational, and social opportunities. The department is encouraged to establish working agreements and arrangements with community organizations and other state agencies which provide services to blind children.

. To facilitate the coordination of services to blind children and their families, the office of superintendent of public instruction and the department of services for the blind shall negotiate an interagency agreement providing for coordinated service delivery and the sharing of information between the two agencies, including an annual register of blind students in the state of Washington.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c194.pdf?cite=1983%20c%20194%20§%2019[1983 c 194 § 19]; ]

== 74.18.200 - Business enterprises program—Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply in RCW 74.18.200 through 74.18.230.

. "Business enterprises program" means a program operated by the department under the federal Randolph-Sheppard Act, 20 U.S.C. Sec. 107 et seq., and under this chapter in support of blind persons operating vending businesses in public buildings.

. "Vending facility" means any stand, snack bar, cafeteria, or business at which food, tobacco, sundries, or other retail merchandise or service is sold or provided.

. "Vending machine" means any coin-operated machine that sells or provides food, tobacco, sundries, or other retail merchandise or service.

. "Blind person" means a person whose central visual acuity does not exceed 20/200 in the better eye with correcting lenses or whose visual acuity, if better than 20/200, is accompanied by a limit to the field of vision in the better eye to such a degree that its widest diameter subtends an angle of no greater than twenty degrees. In determining whether an individual is blind, there shall be an examination by a physician skilled in diseases of the eye, or by an optometrist, whichever the individual selects.

. "Licensee" means a blind person licensed by the state of Washington under the Randolph-Sheppard Act, this chapter, and the rules issued hereunder.

. "Public building" means any building and immediately adjacent outdoor space associated therewith, such as a patio or entryway, which is: (a) Owned by the state of Washington or any political subdivision thereof or any space leased by the state of Washington or any political subdivision thereof in any privately-owned building; and (b) dedicated to the administrative functions of the state or any political subdivision. However, this term shall not include property under the jurisdiction and control of a local board of education without the consent of such board.

. "Priority" means the department has first and primary right to operate the food service and vending facilities, including vending machines, on federal, state, county, municipal, and other local government property except those otherwise exempted by statute. Such right may, at the sole discretion of the department, be waived in the event that the department is temporarily unable to assert the priority.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5705.SL.pdf?cite=2003%20c%20409%20§%2018[2003 c 409 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c97.pdf?cite=1985%20c%2097%20§%201[1985 c 97 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c194.pdf?cite=1983%20c%20194%20§%2020[1983 c 194 § 20]; ]

== 74.18.210 - Business enterprises program—Purposes.
The department shall maintain or cause to be maintained a business enterprises program for blind persons to operate vending facilities in public buildings. The purposes of the business enterprises program are to implement the Randolph-Sheppard Act and thereby give priority to qualified blind persons in operating vending facilities on federal property, to make similar provisions for vending facilities in public buildings in the state of Washington and thereby increase employment opportunities for blind persons, and to encourage blind persons to become successful, independent business persons.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5705.SL.pdf?cite=2003%20c%20409%20§%2019[2003 c 409 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c194.pdf?cite=1983%20c%20194%20§%2021[1983 c 194 § 21]; ]

== 74.18.220 - Business enterprises program—Vending facilities in public buildings.
. The department is authorized to license blind persons to operate vending facilities and vending machines on federal property and in public buildings.

. The state, political subdivisions thereof, and agencies of the state, or political subdivisions thereof shall give priority to licensees in the operation of vending facilities and vending machines in public buildings.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c194.pdf?cite=1983%20c%20194%20§%2022[1983 c 194 § 22]; ]

== 74.18.230 - Business enterprises revolving account.
. There is established in the state treasury an account known as the business enterprises revolving account.

. The net proceeds from any vending machine operation in a public building, other than an operation managed by a licensee, shall be made payable to the business enterprises program, which will pay only the blind vendors' portion, at the subscriber's rate, for the purpose of funding a plan of health insurance for blind vendors, as provided in RCW 41.05.225. Net proceeds, for purposes of this section, means gross sales less state sales tax and a fair minimum return to the vending machine owner or service provider, which return shall be a reasonable amount to be determined by the department.

. All federal moneys in the business enterprises revolving account shall be expended only for development and expansion of locations, equipment, management services, and payments to licensees in the business enterprises program.

. The business enterprises program shall be supported by the business enterprises revolving account and by income which may accrue to the department pursuant to the federal Randolph-Sheppard Act.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5705.SL.pdf?cite=2003%20c%20409%20§%2020[2003 c 409 § 20]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1741-S.SL.pdf?cite=2002%20c%2071%20§%202[2002 c 71 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5984.SL.pdf?cite=1993%20c%20369%20§%201[1993 c 369 § 1]; 1991 sp.s. c 13 §§ 19, 116; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c97.pdf?cite=1985%20c%2097%20§%202[1985 c 97 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c57.pdf?cite=1985%20c%2057%20§%2072[1985 c 57 § 72]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c194.pdf?cite=1983%20c%20194%20§%2023[1983 c 194 § 23]; ]

== 74.18.901 - Conflict with federal requirements.
If any part of this chapter is found to be in conflict with federal requirements which are a condition precedent to the allocation of federal funds to the state, the conflicting part of this chapter is hereby declared to be inoperative solely to the extent of the conflict, and the findings or determination shall not affect the operation of the remainder of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c194.pdf?cite=1983%20c%20194%20§%2025[1983 c 194 § 25]; ]

