= 74.12 - Temporary assistance for needy families.
:toc:

== 74.12.010 - Definitions.
For the purposes of the administration of temporary assistance for needy families, the term "dependent child" means any child in need under the age of eighteen years who is living with a relative as specified under federal temporary assistance for needy families program requirements, in a place of residence maintained by one or more of such relatives as his or her or their homes. The term a "dependent child" shall, notwithstanding the foregoing, also include a child who would meet such requirements except for his or her removal from the home of a relative specified above as a result of a judicial determination that continuation therein would be contrary to the welfare of such child, for whose placement and care the state department of social and health services or the county office is responsible, and who has been placed in a licensed or approved child care institution or foster home as a result of such determination and who: (1) Was receiving an aid to families with dependent children grant for the month in which court proceedings leading to such determination were initiated; or (2) would have received aid to families with dependent children for such month if application had been made therefor; or (3) in the case of a child who had been living with a specified relative within six months prior to the month in which such proceedings were initiated, would have received aid to families with dependent children for such month if in such month he or she had been living with such a relative and application had been made therefor, as authorized by the social security act.

"Temporary assistance for needy families" means money payments, services, and remedial care with respect to a dependent child or dependent children and the needy parent or relative with whom the child lives.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20204[2013 c 23 § 204]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5798.SL.pdf?cite=1999%20c%20120%20§%201[1999 c 120 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1089-S.SL.pdf?cite=1997%20c%2059%20§%2016[1997 c 59 § 16]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2350.SL.pdf?cite=1992%20c%20136%20§%202[1992 c 136 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c41.pdf?cite=1983%201st%20ex.s.%20c%2041%20§%2040[1983 1st ex.s. c 41 § 40]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981ex1c6.pdf?cite=1981%201st%20ex.s.%20c%206%20§%2023[1981 1st ex.s. c 6 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c8.pdf?cite=1981%20c%208%20§%2021[1981 c 8 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20350[1979 c 141 § 350]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex2c31.pdf?cite=1973%202nd%20ex.s.%20c%2031%20§%201[1973 2nd ex.s. c 31 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c173.pdf?cite=1969%20ex.s.%20c%20173%20§%2013[1969 ex.s. c 173 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c37.pdf?cite=1965%20ex.s.%20c%2037%20§%201[1965 ex.s. c 37 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c228.pdf?cite=1963%20c%20228%20§%2018[1963 c 228 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c265.pdf?cite=1961%20c%20265%20§%201[1961 c 265 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c26.pdf?cite=1959%20c%2026%20§%2074.12.010[1959 c 26 § 74.12.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c63.pdf?cite=1957%20c%2063%20§%2010[1957 c 63 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c174.pdf?cite=1953%20c%20174%20§%2024[1953 c 174 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c242.pdf?cite=1941%20c%20242%20§%201[1941 c 242 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c114.pdf?cite=1937%20c%20114%20§%201[1937 c 114 § 1]; Rem. Supp. 1941 § 9992-101; ]

== 74.12.030 - Eligibility.
In addition to meeting the eligibility requirements of RCW 74.08.025, as now or hereafter amended, an applicant for temporary assistance for needy families must be a needy child who is a resident of the state of Washington.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1089-S.SL.pdf?cite=1997%20c%2059%20§%2017[1997 c 59 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c169.pdf?cite=1971%20ex.s.%20c%20169%20§%206[1971 ex.s. c 169 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c228.pdf?cite=1963%20c%20228%20§%2019[1963 c 228 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c26.pdf?cite=1959%20c%2026%20§%2074.12.030[1959 c 26 § 74.12.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c174.pdf?cite=1953%20c%20174%20§%2023[1953 c 174 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c242.pdf?cite=1941%20c%20242%20§%202[1941 c 242 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c114.pdf?cite=1937%20c%20114%20§%204[1937 c 114 § 4]; Rem. Supp. 1941 § 9992-104; ]

== 74.12.035 - Additional eligibility requirements—Students—Exceptions.
. Children over eighteen years of age and under nineteen years of age who are full-time students reasonably expected to complete a program of secondary school, or the equivalent level of vocational or technical training, before reaching nineteen years of age are eligible to receive temporary assistance for needy families: PROVIDED HOWEVER, That if such students do not successfully complete such program before reaching nineteen years of age, the assistance rendered under this subsection during such period shall not be a debt due the state.

. Children with disabilities who are eighteen years of age and under twenty-one years of age and who are full-time students whose education is being provided in accordance with RCW 28A.155.020 are eligible to receive temporary assistance for needy families benefits.

. The department is authorized to grant exceptions to the eligibility restrictions for children eighteen years of age and under twenty-one years of age under subsections (1) and (2) of this section only when it determines by reasonable, objective criteria that such exceptions are likely to enable the children to complete their high school education, high school equivalency certificate as provided in RCW 28B.50.536, or vocational education.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1686-S.SL.pdf?cite=2013%20c%2039%20§%2029[2013 c 39 § 29]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5798.SL.pdf?cite=1999%20c%20120%20§%202[1999 c 120 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1089-S.SL.pdf?cite=1997%20c%2059%20§%2018[1997 c 59 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c335.pdf?cite=1985%20c%20335%20§%201[1985 c 335 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981ex2c10.pdf?cite=1981%202nd%20ex.s.%20c%2010%20§%203[1981 2nd ex.s. c 10 § 3]; ]

== 74.12.240 - Services provided to help attain maximum self-support and independence of parents and relatives.
The department is authorized to provide such social and related services as are reasonably necessary to encourage the care of dependent children in their own homes or in the homes of relatives, to help maintain and strengthen family life and to help such parents or relatives to attain maximum self-support and personal independence consistent with the maintenance of continuing parental care and protection. In the provision of such services, maximum utilization of other agencies providing similar or related services shall be effected.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c26.pdf?cite=1959%20c%2026%20§%2074.12.240[1959 c 26 § 74.12.240]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c63.pdf?cite=1957%20c%2063%20§%208[1957 c 63 § 8]; ]

== 74.12.250 - Payment of grant to another—Limited guardianship.
If the department, after investigation, finds that any applicant for assistance under this chapter or any recipient of funds under this chapter would not use, or is not utilizing, the grant adequately for the needs of his or her child or children or would dissipate the grant or is dissipating such grant, or would be or is unable to manage adequately the funds paid on behalf of said child and that to provide or continue payments to the applicant or recipient would be contrary to the welfare of the child, the department may make such payments to another individual who is interested in or concerned with the welfare of such child and relative: PROVIDED, That the department shall provide such counseling and other services as are available and necessary to develop greater ability on the part of the relative to manage funds in such manner as to protect the welfare of the family. Periodic review of each case shall be made by the department to determine if said relative is able to resume management of the assistance grant. If after a reasonable period of time the payments to the relative cannot be resumed, the department may request the attorney general to file a petition in the superior court for the appointment of a guardian for the child or children. Such petition shall set forth the facts warranting such appointment. Notice of the hearing on such petition shall be served upon the recipient and the department not less than ten days before the date set for such hearing. Such petition may be filed with the clerk of superior court and all process issued and served without payment of costs. If upon the hearing of such petition the court is satisfied that it is for the best interest of the child or children, and all parties concerned, that a guardian be appointed, he or she shall order the appointment, and may require the guardian to render to the court a detailed itemized account of expenditures of such assistance payments at such time as the court may deem advisable.

It is the intention of this section that the guardianship herein provided for shall be a special and limited guardianship solely for the purpose of safeguarding the assistance grants made to dependent children. Such guardianship shall terminate upon the termination of such assistance grant, or sooner on order of the court, upon good cause shown.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20205[2013 c 23 § 205]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3901.SL.pdf?cite=1997%20c%2058%20§%20506[1997 c 58 § 506]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c228.pdf?cite=1963%20c%20228%20§%2021[1963 c 228 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c206.pdf?cite=1961%20c%20206%20§%201[1961 c 206 § 1]; ]

== 74.12.255 - Teen applicants' living situation—Criteria—Presumption—Protective payee—Adoption referral.
. The department shall determine, after consideration of all relevant factors and in consultation with the applicant, the most appropriate living situation for applicants under eighteen years of age, unmarried, and either pregnant or having a dependent child or children in the applicant's care. An appropriate living situation shall include a place of residence that is maintained by the applicant's parents, parent, legal guardian, or other adult relative as their or his or her own home and that the department finds would provide an appropriate supportive living arrangement. It also includes a living situation maintained by an agency that is licensed under chapter 74.15 RCW that the department finds would provide an appropriate supportive living arrangement. Grant assistance shall not be provided under this chapter if the applicant does not reside in the most appropriate living situation, as determined by the department.

. An unmarried minor parent or pregnant minor applicant residing in the most appropriate living situation, as provided under subsection (1) of this section, is presumed to be unable to manage adequately the funds paid to the minor or on behalf of the dependent child or children and, unless the minor provides sufficient evidence to rebut the presumption, shall be subject to the protective payee requirements provided for under RCW 74.12.250 and 74.08.280.

. The department shall consider any statements or opinions by either parent of the unmarried minor parent or pregnant minor applicant as to an appropriate living situation for the minor and his or her children, whether in the parental home or other situation. If the parents or a parent of the minor request, they or he or she shall be entitled to a hearing in juvenile court regarding designation of the parental home or other relative placement as the most appropriate living situation for the pregnant or parenting minor.

The department shall provide the parents or parent with the opportunity to make a showing that the parental home, or home of the other relative placement, is the most appropriate living situation. It shall be presumed in any administrative or judicial proceeding conducted under this subsection that the parental home or other relative placement requested by the parents or parent is the most appropriate living situation. This presumption is rebuttable.

. In cases in which the minor is unmarried and unemployed, the department shall, as part of the determination of the appropriate living situation, make an affirmative effort to provide current and positive information about adoption including referral to community-based organizations for counseling and provide information about the manner in which adoption works, its benefits for unmarried, unemployed minor parents and their children, and the meaning and availability of open adoption.

. For the purposes of this section, "most appropriate living situation" shall not include a living situation including an adult male who fathered the qualifying child and is found to meet the elements of rape of a child as set forth in RCW 9A.44.079.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3901.SL.pdf?cite=1997%20c%2058%20§%20501[1997 c 58 § 501]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2798-S2.SL.pdf?cite=1994%20c%20299%20§%2033[1994 c 299 § 33]; ]

== 74.12.260 - Persons to whom grants shall be made—Proof of use for benefit of children.
Temporary assistance for needy families grants shall be made to persons specified in RCW 74.12.010 as amended or such others as the federal department of health, education and welfare shall recognize for the sole purposes of giving benefits to the children whose needs are included in the grant paid to such persons. The recipient of each temporary assistance for needy families grant shall be and hereby is required to present reasonable proof to the department of social and health services as often as may be required by the department that all funds received in the form of a temporary assistance for needy families grant for the children represented in the grant are being spent for the benefit of the children.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1089-S.SL.pdf?cite=1997%20c%2059%20§%2021[1997 c 59 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20351[1979 c 141 § 351]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c228.pdf?cite=1963%20c%20228%20§%2022[1963 c 228 § 22]; ]

== 74.12.280 - Rules for coordination of services.
The department is hereby authorized to adopt rules that will provide for coordination between the services provided pursuant to chapter 74.13 RCW and the services provided under the temporary assistance for needy families program in order to provide welfare and related services which will best promote the welfare of such children and their families and conform with the provisions of Public Law 87-543 (HR 10606).

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1089-S.SL.pdf?cite=1997%20c%2059%20§%2022[1997 c 59 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c3.pdf?cite=1983%20c%203%20§%20191[1983 c 3 § 191]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c228.pdf?cite=1963%20c%20228%20§%2024[1963 c 228 § 24]; ]

== 74.12.290 - Suitability of home—Evaluation.
The department of social and health services shall, during the initial and any subsequent determination of eligibility, evaluate the suitability of the home in which the dependent child lives, consideration to be given to physical care and supervision provided in the home; social, educational, and the moral atmosphere of the home as compared with the standards of the community; the child's physical and mental health and emotional security, special needs occasioned by the child's physical disabilities or illnesses, if any; the extent to which desirable factors outweigh the undesirable in the home; and the apparent possibility for improving undesirable conditions in the home.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2390.SL.pdf?cite=2020%20c%20274%20§%2060[2020 c 274 § 60]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20352[1979 c 141 § 352]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c228.pdf?cite=1963%20c%20228%20§%2025[1963 c 228 § 25]; ]

== 74.12.300 - Grant during period required to eliminate undesirable conditions.
If the home in which the child lives is found to be unsuitable, but there is reason to believe that elimination of the undesirable conditions can be effected, and the child is otherwise eligible for aid, a grant shall be initiated or continued for such time as the state department of social and health services and the family require to remedy the conditions.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20353[1979 c 141 § 353]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c228.pdf?cite=1963%20c%20228%20§%2026[1963 c 228 § 26]; ]

== 74.12.310 - Placement of child with other relatives.
When intensive efforts over a reasonable period have failed to improve the home conditions, the department shall determine if any other relatives specified by the social security act are maintaining a suitable home and are willing to take the care and custody of the child in their home. Upon an affirmative finding the department shall, if the parents or relatives with whom the child is living consent, take the necessary steps for placement of the child with such other relatives, but if the parents or relatives with whom the child lives refuse their consent to the placement then the department shall file a petition in the juvenile court for a decree adjudging the home unsuitable and placing the dependent child with such other relatives.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c228.pdf?cite=1963%20c%20228%20§%2027[1963 c 228 § 27]; ]

== 74.12.320 - Placement of child pursuant to chapter  13.04 RCW.
If a diligent search reveals no other relatives as specified in the social security act maintaining a suitable home and willing to take custody of the child, then the department may file a petition in the appropriate juvenile court for placement of the child pursuant to the provisions of chapter 13.04 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c228.pdf?cite=1963%20c%20228%20§%2028[1963 c 228 § 28]; ]

== 74.12.330 - Assistance not to be denied for want of relative or court order.
Notwithstanding the provisions of this chapter a child otherwise eligible for aid shall not be denied such assistance where a relative as specified in the social security act is unavailable or refuses to accept custody and the juvenile court fails to enter an order removing the child from the custody of the parent, relative or guardian then having custody.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c228.pdf?cite=1963%20c%20228%20§%2029[1963 c 228 § 29]; ]

== 74.12.340 - Day care.
. The department is authorized to adopt rules governing the provision of day care as a part of child welfare services when the secretary determines that a need exists for such day care and that it is in the best interests of the child, the parents, or the custodial parent and in determining the need for such day care priority shall be given to geographical areas having the greatest need for such care and to members of low-income groups in the population. If the family is financially able to pay part or all of the costs of such care, fees shall be imposed and paid according to the financial ability of the family.

. This section does not affect the authority of the department of children, youth, and families to adopt rules governing child day care and early learning programs.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6287.SL.pdf?cite=2018%20c%2058%20§%207[2018 c 58 § 7]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2964-S2.SL.pdf?cite=2006%20c%20265%20§%20208[2006 c 265 § 208]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c154.pdf?cite=1973%201st%20ex.s.%20c%20154%20§%20111[1973 1st ex.s. c 154 § 111]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c228.pdf?cite=1963%20c%20228%20§%2030[1963 c 228 § 30]; ]

== 74.12.350 - Child's income set aside for future needs—Irrevocable trusts—Educational accounts.
The department of social and health services is hereby authorized to promulgate rules and regulations in conformity with the provisions of Public Law 87-543 to allow all or any portion of a dependent child's earned or other income to be set aside for the identifiable future needs of the dependent child which will make possible the realization of the child's maximum potential as an independent and useful citizen.

The transfer into, or accumulation of, a child's income or resources in an irrevocable trust account is hereby allowed. The amount allowable is four thousand dollars. The department will provide income assistance recipients with clear and simple information on how to set up educational accounts, including how to assure that the accounts comply with federal law by being adequately earmarked for future educational use, and are irrevocable.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2798-S2.SL.pdf?cite=1994%20c%20299%20§%2031[1994 c 299 § 31]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20354[1979 c 141 § 354]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c226.pdf?cite=1963%20c%20226%20§%201[1963 c 226 § 1]; ]

== 74.12.361 - Supplemental security income program—Enrollment of disabled persons.
The department shall actively develop mechanisms for the income assistance program, the medical assistance program, and the community services administration to facilitate the enrollment in the federal supplemental security income program of disabled persons currently part of assistance units receiving temporary assistance for needy families benefits.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1089-S.SL.pdf?cite=1997%20c%2059%20§%2023[1997 c 59 § 23]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2798-S2.SL.pdf?cite=1994%20c%20299%20§%2035[1994 c 299 § 35]; ]

== 74.12.400 - Reduce reliance on aid—Work and job training—Family planning—Staff training.
The department shall train financial services and social work staff who provide direct service to recipients of temporary assistance for needy families to:

. Effectively communicate the transitional nature of temporary assistance for needy families and the expectation that recipients will enter employment;

. Actively refer clients to the job opportunities and basic skills program;

. Provide social services needed to overcome obstacles to employability; and

. Provide family planning information and assistance, including alternatives to abortion, which shall be conducted in consultation with the department of health.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1089-S.SL.pdf?cite=1997%20c%2059%20§%2024[1997 c 59 § 24]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2798-S2.SL.pdf?cite=1994%20c%20299%20§%202[1994 c 299 § 2]; ]

== 74.12.410 - Family planning information—Cooperation with the superintendent of public instruction.
. At the time of application or reassessment under this chapter the department shall offer or contract for family planning information and assistance, including alternatives to abortion, and any other available locally based unintended pregnancy prevention programs, to prospective and current recipients of temporary assistance for needy families.

. The department shall work in cooperation with the superintendent of public instruction to reduce the rate of abortions and unintended pregnancies in Washington state.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5629.SL.pdf?cite=2009%20c%20303%20§%202[2009 c 303 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3901.SL.pdf?cite=1997%20c%2058%20§%20601[1997 c 58 § 601]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2798-S2.SL.pdf?cite=1994%20c%20299%20§%203[1994 c 299 § 3]; ]

== 74.12.450 - Application for assistance—Report on suspected child abuse or neglect—Notice to parent about application, location of child, and family reconciliation act.
. Whenever the department receives an application for assistance on behalf of a child under this chapter and an employee of the department has reason to believe that the child has suffered abuse or neglect, the employee shall cause a report to be made as provided under chapter 26.44 RCW.

. Whenever the department approves an application for assistance on behalf of a child under this chapter, the department shall make a reasonable effort to determine whether the child is living with a parent of the child. Whenever the child is living in the home of a relative other than a parent of the child, the department shall make reasonable efforts to notify the parent with whom the child has most recently resided that an application for assistance on behalf of the child has been approved by the department and shall advise the parent of his or her rights under this section, RCW 74.12.460, and *sections 4 and 5 of this act, unless good cause exists not to do so based on a substantiated claim that the parent has abused or neglected the child.

. Upon written request of the parent, the department shall notify the parent of the address and location of the child, unless there is a current investigation or pending case involving abuse or neglect by the parent under chapter 13.34 RCW.

. The department shall notify and advise the parent of the provisions of the family reconciliation act under chapter 13.32A RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5244-S.SL.pdf?cite=1995%20c%20401%20§%202[1995 c 401 § 2]; ]

== 74.12.460 - Notice to parent—Required within seven days of approval of application.
The department shall make reasonable efforts to notify the parent under RCW 74.12.450(2) as soon as reasonably possible, but no later than seven days after approval of the application by the department.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5244-S.SL.pdf?cite=1995%20c%20401%20§%203[1995 c 401 § 3]; ]

== 74.12.900 - Welfare reform implementation—1994 c 299.
The revisions to the temporary assistance for needy families program and job opportunities and basic skills training program shall be implemented by the department of social and health services on a statewide basis.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1089-S.SL.pdf?cite=1997%20c%2059%20§%2028[1997 c 59 § 28]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2798-S2.SL.pdf?cite=1994%20c%20299%20§%2012[1994 c 299 § 12]; ]

