= 74.13 - Child welfare services.
:toc:

== 74.13.010 - Declaration of purpose.
The purpose of this chapter is to safeguard, protect, and contribute to the welfare of the children of the state, through a comprehensive and coordinated program of child welfare services provided by both the department and agencies providing for: Social services and facilities for children who require guidance, care, control, protection, treatment, or rehabilitation; setting of standards for social services and facilities for children; cooperation with public and voluntary agencies, organizations, and citizen groups in the development and coordination of programs and activities in behalf of children; and promotion of community conditions and resources that help parents to discharge their responsibilities for the care, development, and well-being of their children.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6407.SL.pdf?cite=2018%20c%20284%20§%2034[2018 c 284 § 34]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2106-S2.SL.pdf?cite=2009%20c%20520%20§%2049[2009 c 520 § 49]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c30.pdf?cite=1965%20c%2030%20§%202[1965 c 30 § 2]; ]

== 74.13.013 - Finding—Accreditation of children's services.
The legislature finds that accreditation of children's services by an independent entity can significantly improve the quality of services provided to children and families. Accreditation involves an ongoing commitment to meeting nationally recognized standards of practice in child welfare and holds organizations accountable for achieving improved outcomes for children.

Accreditation is a structured process designed to facilitate organizational change and improvement within individual local offices. Standards require improved case management, documentation, internal case management practices, and accountability. Accreditation requires the establishment of clear communication with biological parents, foster and adoptive parents, providers, the courts, and members of the community.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1249-S2.SL.pdf?cite=2001%20c%20265%20§%201[2001 c 265 § 1]; ]

== 74.13.020 - Definitions. (Effective until January 1, 2021.)
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Case management" means convening family meetings, developing, revising, and monitoring implementation of any case plan or individual service and safety plan, coordinating and monitoring services needed by the child and family, caseworker-child visits, family visits, and the assumption of court-related duties, excluding legal representation, including preparing court reports, attending judicial hearings and permanency hearings, and ensuring that the child is progressing toward permanency within state and federal mandates, including the Indian child welfare act.

. "Child" means:

.. A person less than eighteen years of age; or

.. A person age eighteen to twenty-one years who is eligible to receive the extended foster care services authorized under RCW 74.13.031.

. "Child protective services" has the same meaning as in RCW 26.44.020.

. "Child welfare services" means social services including voluntary and in-home services, out-of-home care, case management, and adoption services which strengthen, supplement, or substitute for, parental care and supervision for the purpose of:

.. Preventing or remedying, or assisting in the solution of problems which may result in families in conflict, or the neglect, abuse, exploitation, or criminal behavior of children;

.. Protecting and caring for dependent, abused, or neglected children;

.. Assisting children who are in conflict with their parents, and assisting parents who are in conflict with their children, with services designed to resolve such conflicts;

.. Protecting and promoting the welfare of children, including the strengthening of their own homes where possible, or, where needed;

.. Providing adequate care of children away from their homes in foster family homes or day care or other child care agencies or facilities.

"Child welfare services" does not include child protection services.

. "Child who is a candidate for foster care" means a child who the department identifies as being at imminent risk of entering foster care but who can remain safely in the child's home or in a kinship placement as long as services or programs that are necessary to prevent entry of the child into foster care are provided, and includes but is not limited to a child whose adoption or guardianship arrangement is at risk of a disruption or dissolution that would result in a foster care placement. The term includes a child for whom there is reasonable cause to believe that any of the following circumstances exist:

.. The child has been abandoned by the parent as defined in RCW 13.34.030 and the child's health, safety, and welfare is seriously endangered as a result;

.. The child has been abused or neglected as defined in chapter 26.44 RCW and the child's health, safety, and welfare is seriously endangered as a result;

.. There is no parent capable of meeting the child's needs such that the child is in circumstances that constitute a serious danger to the child's development;

.. The child is otherwise at imminent risk of harm.

. "Department" means the department of children, youth, and families.

. "Extended foster care services" means residential and other support services the department is authorized to provide to dependent children. These services include, but are not limited to, placement in licensed, relative, or otherwise approved care, or supervised independent living settings; assistance in meeting basic needs; independent living services; medical assistance; and counseling or treatment.

. "Family assessment" means a comprehensive assessment of child safety, risk of subsequent child abuse or neglect, and family strengths and needs that is applied to a child abuse or neglect report. Family assessment does not include a determination as to whether child abuse or neglect occurred, but does determine the need for services to address the safety of the child and the risk of subsequent maltreatment.

. "Medical condition" means, for the purposes of qualifying for extended foster care services, a physical or mental health condition as documented by any licensed health care provider regulated by a disciplining authority under RCW 18.130.040.

. "Nonminor dependent" means any individual age eighteen to twenty-one years who is participating in extended foster care services authorized under RCW 74.13.031.

. "Out-of-home care services" means services provided after the shelter care hearing to or for children in out-of-home care, as that term is defined in RCW 13.34.030, and their families, including the recruitment, training, and management of foster parents, the recruitment of adoptive families, and the facilitation of the adoption process, family reunification, independent living, emergency shelter, residential group care, and foster care, including relative placement.

. "Performance-based contracting" means the structuring of all aspects of the procurement of services around the purpose of the work to be performed and the desired results with the contract requirements set forth in clear, specific, and objective terms with measurable outcomes. Contracts shall also include provisions that link the performance of the contractor to the level and timing of reimbursement.

. "Permanency services" means long-term services provided to secure a child's safety, permanency, and well-being, including foster care services, family reunification services, adoption services, and preparation for independent living services.

. "Prevention and family services and programs" means specific mental health prevention and treatment services, substance abuse prevention and treatment services, and in-home parent skill-based programs that qualify for federal funding under the federal family first prevention services act, P.L. 115-123. For purposes of this chapter, prevention and family services and programs are not remedial services or family reunification services as described in RCW 13.34.025(2).

. "Primary prevention services" means services which are designed and delivered for the primary purpose of enhancing child and family well-being and are shown, by analysis of outcomes, to reduce the risk to the likelihood of the initial need for child welfare services.

. "Secretary" means the secretary of the department.

. "Supervised independent living" includes, but is not limited to, apartment living, room and board arrangements, college or university dormitories, and shared roommate settings. Supervised independent living settings must be approved by the department or the court.

. "Unsupervised" has the same meaning as in RCW 43.43.830.

. "Voluntary placement agreement" means, for the purposes of extended foster care services, a written voluntary agreement between a nonminor dependent who agrees to submit to the care and authority of the department for the purposes of participating in the extended foster care program.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1900.SL.pdf?cite=2019%20c%20172%20§%207[2019 c 172 § 7]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6407.SL.pdf?cite=2018%20c%20284%20§%2036[2018 c 284 § 36]; 2018 c 284 § 35; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6287.SL.pdf?cite=2018%20c%2058%20§%2051[2018 c 58 § 51]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6222-S.SL.pdf?cite=2018%20c%2034%20§%203[2018 c 34 § 3]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1661-S2.SL.pdf?cite=2017%203rd%20sp.s.%20c%206%20§%20401[2017 3rd sp.s. c 6 § 401]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5740-S.SL.pdf?cite=2015%20c%20240%20§%202[2015 c 240 § 2]; prior:  2013 c 332 § 8; 2013 c 332 § 7; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5565-S.SL.pdf?cite=2013%20c%20162%20§%205[2013 c 162 § 5]; 2013 c 162 § 4; prior:  2012 c 259 § 7; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2264-S2.SL.pdf?cite=2012%20c%20205%20§%2012[2012 c 205 § 12]; prior:  2011 c 330 § 4; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6832-S.SL.pdf?cite=2010%20c%20291%20§%203[2010 c 291 § 3]; prior:  2009 c 520 § 2; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1961-S2.SL.pdf?cite=2009%20c%20235%20§%203[2009 c 235 § 3]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1493-S2.SL.pdf?cite=1999%20c%20267%20§%207[1999 c 267 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c155.pdf?cite=1979%20c%20155%20§%2076[1979 c 155 § 76]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c291.pdf?cite=1977%20ex.s.%20c%20291%20§%2021[1977 ex.s. c 291 § 21]; 1975-'76 2nd ex.s. c 71 § 3; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c292.pdf?cite=1971%20ex.s.%20c%20292%20§%2066[1971 ex.s. c 292 § 66]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c30.pdf?cite=1965%20c%2030%20§%203[1965 c 30 § 3]; ]

== 74.13.021 - Developmentally disabled child—Defined.
As used in this chapter, " developmentally disabled child" is a child who has a developmental disability as defined in RCW 71A.10.020 and whose parent, guardian, or legal custodian and with the department mutually agree that services appropriate to the child's needs cannot be provided in the home.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2557.SL.pdf?cite=1998%20c%20229%20§%203[1998 c 229 § 3]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5710-S2.SL.pdf?cite=1997%20c%20386%20§%2015[1997 c 386 § 15]; ]

== 74.13.025 - Counties may administer and provide services under RCW  13.32A.197—Plan for at-risk youth required.
Any county or group of counties may make application to the department in the manner and form prescribed by the department to administer and provide the services established under RCW 13.32A.197. Any such application must include a plan or plans for providing such services to at-risk youth.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1661-S2.SL.pdf?cite=2017%203rd%20sp.s.%20c%206%20§%20402[2017 3rd sp.s. c 6 § 402]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6208-S.SL.pdf?cite=1998%20c%20296%20§%201[1998 c 296 § 1]; ]

== 74.13.029 - Dependency established—Social worker's duty to provide document containing information.
Once a dependency is established under chapter 13.34 RCW, the department employee assigned to the case shall provide the dependent child age twelve years and older with a document containing the information described in RCW 74.13.031(18). The department employee shall explain the contents of the document to the child and direct the child to the department's web site for further information. The department employee shall document, in the electronic data system, that this requirement was met.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1091-S.SL.pdf?cite=2019%20c%2064%20§%2025[2019 c 64 § 25]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5020-S.SL.pdf?cite=2011%20c%2089%20§%2017[2011 c 89 § 17]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5811-S.SL.pdf?cite=2009%20c%20491%20§%208[2009 c 491 § 8]; ]

== 74.13.031 - Duties of department—Child welfare services—Children's services advisory committee.
. The department shall develop, administer, supervise, and monitor a coordinated and comprehensive plan that establishes, aids, and strengthens services for the protection and care of runaway, dependent, or neglected children.

. Within available resources, the department shall recruit an adequate number of prospective adoptive and foster homes, both regular and specialized, i.e. homes for children of ethnic minority, including Indian homes for Indian children, sibling groups, children with disabilities or behavioral health conditions, teens, pregnant and parenting teens, and the department shall annually report to the governor and the legislature concerning the department's success in: (a) Meeting the need for adoptive and foster home placements; (b) reducing the foster parent turnover rate; (c) completing home studies for legally free children; and (d) implementing and operating the passport program required by RCW 74.13.285. The report shall include a section entitled "Foster Home Turn-Over, Causes and Recommendations."

. The department shall investigate complaints of any recent act or failure to act on the part of a parent or caretaker that results in death, serious physical or emotional harm, or sexual abuse or exploitation, or that presents an imminent risk of serious harm, and on the basis of the findings of such investigation, offer child welfare services in relation to the problem to such parents, legal custodians, or persons serving in loco parentis, and/or bring the situation to the attention of an appropriate court, or another community agency. An investigation is not required of nonaccidental injuries which are clearly not the result of a lack of care or supervision by the child's parents, legal custodians, or persons serving in loco parentis. If the investigation reveals that a crime against a child may have been committed, the department shall notify the appropriate law enforcement agency.

. As provided in RCW 26.44.030, the department may respond to a report of child abuse or neglect by using the family assessment response.

. The department shall offer, on a voluntary basis, family reconciliation services to families who are in conflict.

. The department shall monitor placements of children in out-of-home care and in-home dependencies to assure the safety, well-being, and quality of care being provided is within the scope of the intent of the legislature as defined in RCW 74.13.010 and 74.15.010. Under this section children in out-of-home care and in-home dependencies and their caregivers shall receive a private and individual face-to-face visit each month. The department shall randomly select no less than ten percent of the caregivers currently providing care to receive one unannounced face-to-face visit in the caregiver's home per year. No caregiver will receive an unannounced visit through the random selection process for two consecutive years. If the caseworker makes a good faith effort to conduct the unannounced visit to a caregiver and is unable to do so, that month's visit to that caregiver need not be unannounced. The department is encouraged to group monthly visits to caregivers by geographic area so that in the event an unannounced visit cannot be completed, the caseworker may complete other required monthly visits. The department shall use a method of random selection that does not cause a fiscal impact to the department.

The department shall conduct the monthly visits with children and caregivers to whom it is providing child welfare services.

. The department shall have authority to accept custody of children from parents and to accept custody of children from juvenile courts, where authorized to do so under law, to provide child welfare services including placement for adoption, to provide for the routine and necessary medical, dental, and mental health care, or necessary emergency care of the children, and to provide for the physical care of such children and make payment of maintenance costs if needed. Except where required by Public Law 95-608 (25 U.S.C. Sec. 1915), no private adoption agency which receives children for adoption from the department shall discriminate on the basis of race, creed, or color when considering applications in their placement for adoption.

. The department shall have authority to provide temporary shelter to children who have run away from home and who are admitted to crisis residential centers.

. The department shall have authority to purchase care for children.

. The department shall establish a children's services advisory committee which shall assist the secretary in the development of a partnership plan for utilizing resources of the public and private sectors, and advise on all matters pertaining to child welfare, licensing of child care agencies, adoption, and services related thereto. At least one member shall represent the adoption community.

. [Empty]
.. The department shall provide continued extended foster care services to nonminor dependents who are:

... Enrolled in a secondary education program or a secondary education equivalency program;

... Enrolled and participating in a postsecondary academic or postsecondary vocational education program;

... Participating in a program or activity designed to promote employment or remove barriers to employment;

... Engaged in employment for eighty hours or more per month; or

.. Not able to engage in any of the activities described in (a)(i) through (iv) of this subsection due to a documented medical condition.

.. To be eligible for extended foster care services, the nonminor dependent must have been dependent at the time that he or she reached age eighteen years. If the dependency case of the nonminor dependent was dismissed pursuant to RCW 13.34.267, he or she may receive extended foster care services pursuant to a voluntary placement agreement under RCW 74.13.336 or pursuant to an order of dependency issued by the court under RCW 13.34.268. A nonminor dependent whose dependency case was dismissed by the court may request extended foster care services before reaching age twenty-one years. Eligible nonminor dependents may unenroll and reenroll in extended foster care through a voluntary placement agreement an unlimited number of times between ages eighteen and twenty-one.

.. The department shall develop and implement rules regarding youth eligibility requirements.

.. The department shall make efforts to ensure that extended foster care services maximize medicaid reimbursements. This must include the department ensuring that health and mental health extended foster care providers participate in medicaid, unless the condition of the extended foster care youth requires specialty care that is not available among participating medicaid providers or there are no participating medicaid providers in the area. The department shall coordinate other services to maximize federal resources and the most cost-efficient delivery of services to extended foster care youth.

.. The department shall allow a youth who has received extended foster care services, but lost his or her eligibility, to reenter the extended foster care program an unlimited number of times through a voluntary placement agreement when he or she meets the eligibility criteria again.

. The department shall have authority to provide adoption support benefits, or relative guardianship subsidies on behalf of youth ages eighteen to twenty-one years who achieved permanency through adoption or a relative guardianship at age sixteen or older and who meet the criteria described in subsection (11) of this section.

. The department shall refer cases to the division of child support whenever state or federal funds are expended for the care and maintenance of a child, including a child with a developmental disability who is placed as a result of an action under chapter 13.34 RCW, unless the department finds that there is good cause not to pursue collection of child support against the parent or parents of the child. Cases involving individuals age eighteen through twenty shall not be referred to the division of child support unless required by federal law.

. The department shall have authority within funds appropriated for foster care services to purchase care for Indian children who are in the custody of a federally recognized Indian tribe or tribally licensed child-placing agency pursuant to parental consent, tribal court order, or state juvenile court order. The purchase of such care is exempt from the requirements of chapter 74.13B RCW and may be purchased from the federally recognized Indian tribe or tribally licensed child-placing agency, and shall be subject to the same eligibility standards and rates of support applicable to other children for whom the department purchases care.

Notwithstanding any other provision of RCW 13.32A.170 through 13.32A.200, 43.185C.295, 74.13.035, and 74.13.036, or of this section all services to be provided by the department under subsections (4), (7), and (8) of this section, subject to the limitations of these subsections, may be provided by any program offering such services funded pursuant to Titles II and III of the federal juvenile justice and delinquency prevention act of 1974.

. Within amounts appropriated for this specific purpose, the department shall provide preventive services to families with children that prevent or shorten the duration of an out-of-home placement.

. The department shall have authority to provide independent living services to youths, including individuals who have attained eighteen years of age, and have not attained twenty-three years of age, who are or have been in the department's care and custody, or who are or were nonminor dependents.

. The department shall consult at least quarterly with foster parents, including members of the foster parent association of Washington state, for the purpose of receiving information and comment regarding how the department is performing the duties and meeting the obligations specified in this section and RCW 74.13.250 regarding the recruitment of foster homes, reducing foster parent turnover rates, providing effective training for foster parents, and administering a coordinated and comprehensive plan that strengthens services for the protection of children. Consultation shall occur at the regional and statewide levels.

. [Empty]
.. The department shall, within current funding levels, place on its public web site a document listing the duties and responsibilities the department has to a child subject to a dependency petition including, but not limited to, the following:

... Reasonable efforts, including the provision of services, toward reunification of the child with his or her family;

... Sibling visits subject to the restrictions in RCW 13.34.136(2)(b)(ii);

... Parent-child visits;

... Statutory preference for placement with a relative or other suitable person, if appropriate; and

.. Statutory preference for an out-of-home placement that allows the child to remain in the same school or school district, if practical and in the child's best interests.

.. The document must be prepared in conjunction with a community-based organization and must be updated as needed.

. [Empty]
.. The department shall have the authority to purchase legal representation for parents or kinship caregivers, or both, of children who are at risk of being dependent, or who are dependent, to establish or modify a parenting plan under RCW 13.34.155 or chapter 26.09, 26.26A, or 26.26B RCW or secure orders establishing other relevant civil legal relationships authorized by law, when it is necessary for the child's safety, permanence, or well-being. The department's purchase of legal representation for kinship caregivers must be within the department's appropriations. This subsection does not create an entitlement to legal representation purchased by the department and does not create judicial authority to order the department to purchase legal representation for a parent or kinship caregiver. Such determinations are solely within the department's discretion. The term "kinship caregiver" as used in this section means a caregiver who meets the definition of "kin" in RCW 74.13.600(1), unless the child is an Indian child as defined in RCW 13.38.040 and 25 U.S.C. Sec. 1903. For an Indian child as defined in RCW 13.38.040 and 25 U.S.C. Sec. 1903, the term "kinship caregiver" as used in this section means a caregiver who is an "extended family member" as defined in RCW 13.38.040(8).

.. The department is encouraged to work with the office of public defense parent representation program and the office of civil legal aid to develop a cost-effective system for providing effective civil legal representation for parents and kinship caregivers if it exercises its authority under this subsection.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2390.SL.pdf?cite=2020%20c%20274%20§%2061[2020 c 274 § 61]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1900.SL.pdf?cite=2019%20c%20172%20§%208[2019 c 172 § 8]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5333-S.SL.pdf?cite=2019%20c%2046%20§%205045[2019 c 46 § 5045]; prior:  2018 c 284 § 37; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6453-S2.SL.pdf?cite=2018%20c%2080%20§%201[2018 c 80 § 1]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6222-S.SL.pdf?cite=2018%20c%2034%20§%205[2018 c 34 § 5]; prior:  2017 3rd sp.s. c 20 § 7; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1867-S.SL.pdf?cite=2017%20c%20265%20§%202[2017 c 265 § 2]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5740-S.SL.pdf?cite=2015%20c%20240%20§%203[2015 c 240 § 3]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2335.SL.pdf?cite=2014%20c%20122%20§%202[2014 c 122 § 2]; prior:  2013 c 332 § 10; 2013 c 332 § 9; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5235.SL.pdf?cite=2013%20c%2032%20§%202[2013 c 32 § 2]; 2013 c 32 § 1; prior:  2012 c 259 § 8; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2592-S.SL.pdf?cite=2012%20c%2052%20§%202[2012 c 52 § 2]; prior:  2011 c 330 § 5; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1697-S.SL.pdf?cite=2011%20c%20160%20§%202[2011 c 160 § 2]; prior:  2009 c 520 § 51; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5811-S.SL.pdf?cite=2009%20c%20491%20§%207[2009 c 491 § 7]; 2009 c 235 § 4; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1961-S2.SL.pdf?cite=2009%20c%20235%20§%202[2009 c 235 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6792-S.SL.pdf?cite=2008%20c%20267%20§%206[2008 c 267 § 6]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1624-S.SL.pdf?cite=2007%20c%20413%20§%2010[2007 c 413 § 10]; prior:  2006 c 266 § 1; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2985-S.SL.pdf?cite=2006%20c%20221%20§%203[2006 c 221 § 3]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2554-S.SL.pdf?cite=2004%20c%20183%20§%203[2004 c 183 § 3]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1259-S.SL.pdf?cite=2001%20c%20192%20§%201[2001 c 192 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1493-S2.SL.pdf?cite=1999%20c%20267%20§%208[1999 c 267 § 8]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2556-S.SL.pdf?cite=1998%20c%20314%20§%2010[1998 c 314 § 10]; prior:  1997 c 386 § 32; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2046-S2.SL.pdf?cite=1997%20c%20272%20§%201[1997 c 272 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5029.SL.pdf?cite=1995%20c%20191%20§%201[1995 c 191 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c146.pdf?cite=1990%20c%20146%20§%209[1990 c 146 § 9]; prior:  1987 c 505 § 69; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c170.pdf?cite=1987%20c%20170%20§%2010[1987 c 170 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c246.pdf?cite=1983%20c%20246%20§%204[1983 c 246 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c118.pdf?cite=1982%20c%20118%20§%203[1982 c 118 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c298.pdf?cite=1981%20c%20298%20§%2016[1981 c 298 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c165.pdf?cite=1979%20ex.s.%20c%20165%20§%2022[1979 ex.s. c 165 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c155.pdf?cite=1979%20c%20155%20§%2077[1979 c 155 § 77]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c291.pdf?cite=1977%20ex.s.%20c%20291%20§%2022[1977 ex.s. c 291 § 22]; 1975-'76 2nd ex.s. c 71 § 4; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c101.pdf?cite=1973%201st%20ex.s.%20c%20101%20§%202[1973 1st ex.s. c 101 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c172.pdf?cite=1967%20c%20172%20§%2017[1967 c 172 § 17]; ]

== 74.13.0311 - Services provided under deferred prosecution order.
The department may provide child welfare services pursuant to a deferred prosecution plan ordered under chapter 10.05 RCW. Child welfare services provided under this chapter pursuant to a deferred prosecution order may not be construed to prohibit the department from providing services or undertaking proceedings pursuant to chapter 13.34 or 26.44 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6407.SL.pdf?cite=2018%20c%20284%20§%2038[2018 c 284 § 38]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2106-S2.SL.pdf?cite=2009%20c%20520%20§%2052[2009 c 520 § 52]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2382-S.SL.pdf?cite=2002%20c%20219%20§%2013[2002 c 219 § 13]; ]

== 74.13.035 - Crisis residential centers—Annual records, contents—Multiple licensing.
Crisis residential centers shall compile yearly records which shall be transmitted to the department and which shall contain information regarding population profiles of the children admitted to the centers during each past calendar year. Such information shall include but shall not be limited to the following:

. The number, age, and sex of children admitted to custody;

. Who brought the children to the center;

. Services provided to children admitted to the center;

. The circumstances which necessitated the children being brought to the center;

. The ultimate disposition of cases;

. The number of children admitted to custody who ran away from the center and their ultimate disposition, if any;

. Length of stay.

The department may require the provision of additional information and may require each center to provide all such necessary information in a uniform manner.

A center may, in addition to being licensed as such, also be licensed as a family foster home or group care facility and may house on the premises juveniles assigned for foster or group care.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c155.pdf?cite=1979%20c%20155%20§%2081[1979 c 155 § 81]; ]

== 74.13.036 - Implementation of chapters  13.32A and  13.34 RCW.
. The department shall oversee implementation of chapter 13.34 RCW and chapter 13.32A RCW. The oversight shall be comprised of working with affected parts of the criminal justice and child care systems as well as with local government, legislative, and executive authorities to effectively carry out these chapters. The department shall work with all such entities to ensure that chapters 13.32A and 13.34 RCW are implemented in a uniform manner throughout the state.

. The department shall develop a plan and procedures, in cooperation with the statewide advisory committee, to insure the full implementation of the provisions of chapter 13.32A RCW. Such plan and procedures shall include but are not limited to:

.. Procedures defining and delineating the role of the department and juvenile court with regard to the execution of the child in need of services placement process;

.. Procedures for designating department staff responsible for family reconciliation services;

.. Procedures assuring enforcement of contempt proceedings in accordance with RCW 13.32A.170 and 13.32A.250; and

.. Procedures for the continued education of all individuals in the criminal juvenile justice and child care systems who are affected by chapter 13.32A RCW, as well as members of the legislative and executive branches of government.

There shall be uniform application of the procedures developed by the department and juvenile court personnel, to the extent practicable. Local and regional differences shall be taken into consideration in the development of procedures required under this subsection.

. In addition to its other oversight duties, the department shall:

.. Identify and evaluate resource needs in each region of the state;

.. Disseminate information collected as part of the oversight process to affected groups and the general public;

.. Educate affected entities within the juvenile justice and child care systems, local government, and the legislative branch regarding the implementation of chapters 13.32A and 13.34 RCW;

.. Review complaints concerning the services, policies, and procedures of those entities charged with implementing chapters 13.32A and 13.34 RCW; and

.. Report any violations and misunderstandings regarding the implementation of chapters 13.32A and 13.34 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6407.SL.pdf?cite=2018%20c%20284%20§%2039[2018 c 284 § 39]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2106-S2.SL.pdf?cite=2009%20c%20520%20§%2054[2009 c 520 § 54]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2327-S.SL.pdf?cite=2009%20c%20518%20§%205[2009 c 518 § 5]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1561.SL.pdf?cite=2003%20c%20207%20§%202[2003 c 207 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2217-S2.SL.pdf?cite=1996%20c%20133%20§%2037[1996 c 133 § 37]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5439-S2.SL.pdf?cite=1995%20c%20312%20§%2065[1995 c 312 § 65]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c175.pdf?cite=1989%20c%20175%20§%20147[1989 c 175 § 147]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c505.pdf?cite=1987%20c%20505%20§%2070[1987 c 505 § 70]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c257.pdf?cite=1985%20c%20257%20§%2011[1985 c 257 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c298.pdf?cite=1981%20c%20298%20§%2018[1981 c 298 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c155.pdf?cite=1979%20c%20155%20§%2082[1979 c 155 § 82]; ]

== 74.13.037 - Transitional living programs for youth in the process of being emancipated—Rules.
Within available funds appropriated for this purpose, the department shall establish, through performance-based contracts with private vendors, transitional living programs for youth who are being assisted by the department in being emancipated as part of their permanency plan under chapter 13.34 RCW. These programs shall be licensed under rules adopted by the department.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2106-S2.SL.pdf?cite=2009%20c%20520%20§%2055[2009 c 520 § 55]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5578-S.SL.pdf?cite=1997%20c%20146%20§%209[1997 c 146 § 9]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2217-S2.SL.pdf?cite=1996%20c%20133%20§%2039[1996 c 133 § 39]; ]

== 74.13.039 - Runaway hotline.
The department shall maintain a toll-free hotline to assist parents of runaway children. The hotline shall provide parents with a complete description of their rights when dealing with their runaway child.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1661-S2.SL.pdf?cite=2017%203rd%20sp.s.%20c%206%20§%20403[2017 3rd sp.s. c 6 § 403]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=1994%20sp.s.%20c%207%20§%20501[1994 sp.s. c 7 § 501]; ]

== 74.13.042 - Petition for order compelling disclosure of record or information.
If the department is denied lawful access to records or information, or requested records or information is not provided in a timely manner, the department may petition the court for an order compelling disclosure.

. The petition shall be filed in the juvenile court for the county in which the record or information is located or the county in which the person who is the subject of the record or information resides. If the person who is the subject of the record or information is a party to or the subject of a pending proceeding under chapter 13.32A or 13.34 RCW, the petition shall be filed in such proceeding.

. Except as otherwise provided in this section, the persons from whom and about whom the record or information is sought shall be served with a summons and a petition at least seven calendar days prior to a hearing on the petition. The court may order disclosure upon ex parte application of the department, without prior notice to any person, if the court finds there is reason to believe access to the record or information is necessary to determine whether the child is in imminent danger and in need of immediate protection.

. The court shall grant the petition upon a showing that there is reason to believe that the record or information sought is necessary for the health, safety, or welfare of the child who is currently receiving child welfare services.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6407.SL.pdf?cite=2018%20c%20284%20§%2040[2018 c 284 § 40]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2106-S2.SL.pdf?cite=2009%20c%20520%20§%2056[2009 c 520 § 56]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5885-S.SL.pdf?cite=1995%20c%20311%20§%2014[1995 c 311 § 14]; ]

== 74.13.045 - Complaint resolution process.
The department shall develop and implement an informal, nonadversarial complaint resolution process to be used by clients of the department, foster parents, and other affected individuals who have complaints regarding a department policy or procedure, the application of such a policy or procedure, or the performance of an entity that has entered into a performance-based contract with the department, related to programs administered under this chapter. The process shall not apply in circumstances where the complainant has the right under Title 13, 26, or 74 RCW to seek resolution of the complaint through judicial review or through an adjudicative proceeding.

Nothing in this section shall be construed to create substantive or procedural rights in any person. Participation in the complaint resolution process shall not entitle any person to an adjudicative proceeding under chapter 34.05 RCW or to superior court review. Participation in the process shall not affect the right of any person to seek other statutorily or constitutionally permitted remedies.

The department shall develop procedures to assure that clients and foster parents are informed of the availability of the complaint resolution process and how to access it. The department shall incorporate information regarding the complaint resolution process into the training for foster parents and department caseworkers.

The department shall compile complaint resolution data including the nature of the complaint and the outcome of the process.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6407.SL.pdf?cite=2018%20c%20284%20§%2041[2018 c 284 § 41]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2106-S2.SL.pdf?cite=2009%20c%20520%20§%2057[2009 c 520 § 57]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6219.SL.pdf?cite=1998%20c%20245%20§%20146[1998 c 245 § 146]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5916-S.SL.pdf?cite=1991%20c%20340%20§%202[1991 c 340 § 2]; ]

== 74.13.055 - Foster care—Length of stay.
The department shall adopt rules pursuant to chapter 34.05 RCW which establish goals as to the maximum number of children who will remain in foster care for a period of longer than twenty-four months.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6407.SL.pdf?cite=2018%20c%20284%20§%2042[2018 c 284 § 42]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2106-S2.SL.pdf?cite=2009%20c%20520%20§%2058[2009 c 520 § 58]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6219.SL.pdf?cite=1998%20c%20245%20§%20147[1998 c 245 § 147]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c118.pdf?cite=1982%20c%20118%20§%201[1982 c 118 § 1]; ]

== 74.13.060 - Secretary as custodian of funds of person placed with department or its agent—Authority—Limitations—Termination.
. The secretary or his or her designees or delegatees shall be the custodian without compensation of such moneys and other funds of any person which may come into the possession of the secretary during the period such person is placed with the department or an entity with which it has entered into a performance-based contract pursuant to chapter 74.13 RCW. As such custodian, the secretary shall have authority to disburse moneys from the person's funds for the following purposes only and subject to the following limitations:

.. For such personal needs of such person as the secretary may deem proper and necessary.

.. Against the amount of public assistance otherwise payable to such person. This includes applying, as reimbursement, any benefits, payments, funds, or accrual paid to or on behalf of said person from any source against the amount of public assistance expended on behalf of said person during the period for which the benefits, payments, funds or accruals were paid.

. All funds held by the secretary as custodian may be deposited in a single fund, the receipts and expenditures therefrom to be accurately accounted for by him or her on an individual basis. Whenever, the funds belonging to any one person exceed the sum of five hundred dollars, the secretary may deposit said funds in a savings and loan association account on behalf of that particular person.

. When the conditions of placement no longer exist and public assistance is no longer being provided for such person, upon a showing of legal competency and proper authority, the secretary shall deliver to such person, or the parent, person, or agency legally responsible for such person, all funds belonging to the person remaining in his or her possession as custodian, together with a full and final accounting of all receipts and expenditures made therefrom.

. The appointment of a guardian for the estate of such person shall terminate the secretary's authority as custodian of said funds upon receipt by the secretary of a certified copy of letters of guardianship. Upon the guardian's request, the secretary shall immediately forward to such guardian any funds of such person remaining in the secretary's possession together with full and final accounting of all receipts and expenditures made therefrom.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2106-S2.SL.pdf?cite=2009%20c%20520%20§%2059[2009 c 520 § 59]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c169.pdf?cite=1971%20ex.s.%20c%20169%20§%207[1971 ex.s. c 169 § 7]; ]

== 74.13.062 - Eligible relatives appointed as guardians—Receipt and expenditure of federal funds—Implementation of subsidy program—Department to adopt rules—Relative guardianship subsidy agreements.
. The department shall adopt rules consistent with federal regulations for the receipt and expenditure of federal funds and implement a subsidy program for eligible relatives appointed by the court as a guardian under RCW 13.36.050.

. For the purpose of licensing a relative seeking to be appointed as a guardian and eligible for a guardianship subsidy under this section, the department shall, on a case-by-case basis, and when determined to be in the best interests of the child:

.. Waive nonsafety licensing standards; and

.. Apply the list of disqualifying crimes in the adoption and safe families act, unless doing so would compromise the child's safety, or would adversely affect the state's ability to continue to obtain federal funding for child welfare related functions.

. Relative guardianship subsidy agreements shall be designed to promote long-term permanency for the child, and may include provisions for periodic review of the subsidy amount and the needs of the child.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1661-S2.SL.pdf?cite=2017%203rd%20sp.s.%20c%206%20§%20404[2017 3rd sp.s. c 6 § 404]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2680-S.SL.pdf?cite=2010%20c%20272%20§%2012[2010 c 272 § 12]; ]

== 74.13.065 - Out-of-home care—Social study required.
. The department shall conduct a social study whenever a child is placed in out-of-home care under the supervision of the department. The study shall be conducted prior to placement, or, if it is not feasible to conduct the study prior to placement due to the circumstances of the case, the study shall be conducted as soon as possible following placement.

. The social study shall include, but not be limited to, an assessment of the following factors:

.. The physical and emotional strengths and needs of the child;

.. Emotional bonds with siblings and the need to maintain regular sibling contacts;

.. The proximity of the child's placement to the child's family to aid reunification;

.. The possibility of placement with the child's relatives or extended family;

.. The racial, ethnic, cultural, and religious background of the child;

.. The least-restrictive, most family-like placement reasonably available and capable of meeting the child's needs; and

.. Compliance with RCW 13.34.260 regarding parental preferences for placement of their children.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6407.SL.pdf?cite=2018%20c%20284%20§%2043[2018 c 284 § 43]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2106-S2.SL.pdf?cite=2009%20c%20520%20§%2060[2009 c 520 § 60]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6702-S.SL.pdf?cite=2002%20c%2052%20§%208[2002 c 52 § 8]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5885-S.SL.pdf?cite=1995%20c%20311%20§%2026[1995 c 311 § 26]; ]

== 74.13.070 - Moneys in possession of secretary not subject to certain proceedings.
None of the moneys or other funds which come into the possession of the secretary under chapter 169, Laws of 1971 ex. sess. shall be subject to execution, levy, attachment, garnishment or other legal process or other operation of any bankruptcy or insolvency law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c169.pdf?cite=1971%20ex.s.%20c%20169%20§%208[1971 ex.s. c 169 § 8]; ]

== 74.13.075 - Sexually aggressive youth—Defined—Services—Expenditure of treatment funds—Tribal jurisdiction—Information sharing and confidentiality.
. For the purposes of funds appropriated for the treatment of sexually aggressive youth, the term "sexually aggressive youth" means those juveniles who:

.. Have been abused and have committed a sexually aggressive act or other violent act that is sexual in nature; and

... Are in the care and custody of the state or a federally recognized Indian tribe located within the state; or

... Are the subject of a proceeding under chapter 13.34 RCW or a child welfare proceeding held before a tribal court located within the state; or

.. Cannot be detained under the juvenile justice system due to being under age twelve and incompetent to stand trial for acts that could be prosecuted as sex offenses as defined by RCW 9.94A.030 if the juvenile was over twelve years of age, or competent to stand trial if under twelve years of age.

. The department may offer appropriate available services and treatment to a sexually aggressive youth and his or her parents or legal guardians as provided in this section and may refer the child and his or her parents to appropriate treatment and services available within the community, regardless of whether the child is the subject of a proceeding under chapter 13.34 RCW.

. In expending these funds, the department shall establish in each region a case review committee to review all cases for which the funds are used. In determining whether to use these funds in a particular case, the committee shall consider:

.. The age of the juvenile;

.. The extent and type of abuse to which the juvenile has been subjected;

.. The juvenile's past conduct;

.. The benefits that can be expected from the treatment;

.. The cost of the treatment; and

.. The ability of the juvenile's parent or guardian to pay for the treatment.

. The department may provide funds, under this section, for youth in the care and custody of a tribe or through a tribal court, for the treatment of sexually aggressive youth only if: (a) The tribe uses the same or equivalent definitions and standards for determining which youth are sexually aggressive; and (b) the department seeks to recover any federal funds available for the treatment of youth.

. A juvenile's status as a sexually aggressive youth, and any protective plan, services, and treatment plans and progress reports provided with these funds are confidential and not subject to public disclosure by the department. This information shall be shared with relevant juvenile care agencies, law enforcement agencies, and schools, but remains confidential and not subject to public disclosure by those agencies.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2106-S2.SL.pdf?cite=2009%20c%20520%20§%2061[2009 c 520 § 61]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1419-S.SL.pdf?cite=2009%20c%20250%20§%202[2009 c 250 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2512.SL.pdf?cite=1994%20c%20169%20§%201[1994 c 169 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1110.SL.pdf?cite=1993%20c%20402%20§%203[1993 c 402 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5494.SL.pdf?cite=1993%20c%20146%20§%201[1993 c 146 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c3.pdf?cite=1990%20c%203%20§%20305[1990 c 3 § 305]; ]

== 74.13.077 - Sexually aggressive youth—Transfer of surplus funds for treatment.
The secretary is authorized to transfer surplus, unused treatment funds from the civil commitment center operated under chapter 71.09 RCW to the division of children and family services to provide treatment services for sexually aggressive youth.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2106-S2.SL.pdf?cite=2009%20c%20520%20§%2062[2009 c 520 § 62]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1110.SL.pdf?cite=1993%20c%20402%20§%204[1993 c 402 § 4]; ]

== 74.13.080 - Group care placement—Prerequisites for payment.
The department shall not make payment for any child in group care placement unless the group home is licensed and the department has the custody of the child and the authority to remove the child in a cooperative manner after at least seventy-two hours notice to the child care provider; such notice may be waived in emergency situations. However, this requirement shall not be construed to prohibit the department from making or mandate the department to make payment for Indian children placed in facilities licensed by federally recognized Indian tribes pursuant to chapter 74.15 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c170.pdf?cite=1987%20c%20170%20§%2011[1987 c 170 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c118.pdf?cite=1982%20c%20118%20§%202[1982 c 118 § 2]; ]

== 74.13.1051 - Foster youth education and plans for the future—Memoranda of understanding among agencies—Transfer of responsibilities from the department—Indicators relating to education outcomes.
. In order to proactively support foster youth to complete high school, enroll and complete postsecondary education, and successfully implement their own plans for their futures, the department, the student achievement council, and the office of the superintendent of public instruction shall enter into, or revise existing, memoranda of understanding that:

.. Facilitate student referral, data and information exchange, agency roles and responsibilities, and cooperation and collaboration among state agencies and nongovernmental entities; and

.. Effectuate the transfer of responsibilities from the department to the office of the superintendent of public instruction with respect to the programs in RCW 28A.300.592, and from the department to the student achievement council with respect to the program in RCW 28B.77.250 in a smooth, expedient, and coordinated fashion.

. The student achievement council and the office of the superintendent of public instruction shall establish a set of indicators relating to the outcomes provided in RCW 28A.300.590 and 28A.300.592 to provide consistent services for youth, facilitate transitions among contractors, and support outcome-driven contracts. The student achievement council and the superintendent of public instruction shall collaborate with nongovernmental contractors and the department to develop a list of the most critical indicators, establishing a common set of indicators to be used in the outcome-driven contracts in RCW 28A.300.590 and 28A.300.592.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2711-S.SL.pdf?cite=2020%20c%20233%20§%203[2020 c 233 § 3]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1661-S2.SL.pdf?cite=2017%203rd%20sp.s.%20c%206%20§%20405[2017 3rd sp.s. c 6 § 405]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1999-S4.SL.pdf?cite=2016%20c%2071%20§%206[2016 c 71 § 6]; ]

== 74.13.107 - Child and family reinvestment account—Methodology for calculating savings resulting from reductions in foster care caseloads and per capita costs.
[ Reviser's note: RCW  74.13.107 was amended by 2017 3rd sp.s. c 6 § 406 without reference to its repeal by  2017 3rd sp.s. c 20 § 15. It has been decodified for publication purposes under RCW  1.12.025; ]

== 74.13.110 - Contracted services performance improvement account.
. The department of children, youth, and families contracted services performance improvement account is created in the state treasury. Moneys in the account may be spent only after appropriation. Moneys in the account may be expended solely to improve contracted services provided to clients under the agency's program areas, including child welfare, early learning, family support, and adolescents, to support (a) achieving permanency for children; (b) improving foster home retention and stability of placements; (c) improving and increasing placement options for youth in out-of-home care; (d) preventing out-of-home placement; and (e) achieving additional, measurable department of children, youth, and families outcome goals adopted by the department.

. Revenues to the department of children, youth, and families contracted services performance improvement account consist of: (a) Legislative appropriations; and (b) any other public or private funds appropriated to or deposited in the account.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5955-S.SL.pdf?cite=2019%20c%20470%20§%2016[2019 c 470 § 16]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5890-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%2020%20§%2014[2017 3rd sp.s. c 20 § 14]; ]

== 74.13.170 - Therapeutic family home program for youth in custody under chapter  13.34 RCW.
The department may, through performance-based contracts with agencies, implement a therapeutic family home program for up to fifteen youth in the custody of the department under chapter 13.34 RCW. The program shall strive to develop and maintain a mutually reinforcing relationship between the youth and the therapeutic staff associated with the program.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6407.SL.pdf?cite=2018%20c%20284%20§%2044[2018 c 284 § 44]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2106-S2.SL.pdf?cite=2009%20c%20520%20§%2070[2009 c 520 § 70]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1608-S.SL.pdf?cite=1991%20c%20326%20§%202[1991 c 326 § 2]; ]

== 74.13.232 - Services to homeless families.
The department's duty to provide services to homeless families with children is set forth in RCW 43.20A.790 and in appropriations provided by the legislature for implementation of the comprehensive plan for homeless families with children.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2106-S2.SL.pdf?cite=2009%20c%20520%20§%2050[2009 c 520 § 50]; ]

== 74.13.250 - Preservice training—Foster parents.
. Preservice training is recognized as a valuable tool to reduce placement disruptions, the length of time children are in care, and foster parent turnover rates. Preservice training also assists potential foster parents in making their final decisions about foster parenting and assists social service agencies in obtaining information about whether to approve potential foster parents.

. Foster parent preservice training shall include information about the potential impact of placement on foster children; social service agency administrative processes; the requirements, responsibilities, expectations, and skills needed to be a foster parent; attachment, separation, and loss issues faced by birth parents, foster children, and foster parents; child management and discipline; birth family relationships; information on the limits of the adoption support program as provided in RCW 74.13A.020(4); and helping children leave foster care. Preservice training shall assist applicants in making informed decisions about whether they want to be foster parents. Preservice training shall be designed to enable the agency to assess the ability, readiness, and appropriateness of families to be foster parents. As a decision tool, effective preservice training provides potential foster parents with enough information to make an appropriate decision, affords potential foster parents an opportunity to discuss their decision with others and consider its implications for their family, clarifies foster family expectations, presents a realistic picture of what foster parenting involves, and allows potential foster parents to consider and explore the different types of children they might serve.

. Foster parents shall complete preservice training before the issuance of a foster care license, except that the department may, on a case by case basis, issue a written waiver that allows the foster parent to complete the training after licensure, so long as the training is completed within ninety days following licensure.

. All components of the foster parent preservice training shall be made available online. The department shall allow individuals to complete as much online preservice training as is practicable while requiring that some preservice training be completed in person.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2256-S.SL.pdf?cite=2018%20c%2020%20§%201[2018 c 20 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2106-S2.SL.pdf?cite=2009%20c%20520%20§%2071[2009 c 520 § 71]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5811-S.SL.pdf?cite=2009%20c%20491%20§%2010[2009 c 491 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c284.pdf?cite=1990%20c%20284%20§%202[1990 c 284 § 2]; ]

== 74.13.260 - On-site monitoring program.
Regular on-site monitoring of foster homes to assure quality care improves care provided to children in family foster care. An on-site monitoring program shall be established by the department to assure quality care and regularly identify problem areas. Monitoring shall be done by the department on a random sample basis of no less than ten percent of the total licensed family foster homes licensed by the department on July 1 of each year.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6219.SL.pdf?cite=1998%20c%20245%20§%20148[1998 c 245 § 148]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c284.pdf?cite=1990%20c%20284%20§%204[1990 c 284 § 4]; ]

== 74.13.270 - Respite care.
. The legislature recognizes the need for temporary short-term relief for foster parents who care for children with emotional, mental, or physical disabilities. For purposes of this section, respite care means appropriate, temporary, short-term care for these foster children placed with licensed foster parents. The purpose of this care is to give the foster parents temporary relief from the stresses associated with the care of these foster children. The department shall design a program of respite care that will minimize disruptions to the child and will serve foster parents within these priorities, based on input from foster parents, foster parent associations, and reliable research if available.

. [Empty]
.. For the purposes of this section, and subject to funding appropriated specifically for this purpose, short-term support shall include case aides who provide temporary assistance to foster parents as needed with the overall goal of supporting the parental efforts of the foster parents except that this assistance shall not include overnight assistance. The department shall contract with nonprofit community-based organizations in each region to establish a statewide pool of individuals to provide the support described in this subsection. These individuals shall be employees or volunteers with the nonprofit community-based organization and shall have the appropriate training, background checks, and qualifications as determined by the department. Short-term support as described in this subsection shall be available to all licensed foster parents in the state as funding is available and shall be phased in by geographic region. To obtain the assistance of a case aide for this purpose, the foster parent may request the services from the nonprofit community-based organization and the nonprofit community-based organization may offer assistance to licensed foster families. If the requests for the short-term support provided in this subsection exceed the funding available, the nonprofit community-based organization shall have discretion to determine the assignment of case aides. The nonprofit community-based organization shall report all short-term support provided under this subsection to the department.

.. Subject to funding appropriated specifically for this purpose, the Washington state institute for public policy shall prepare an outcome evaluation of the short-term support described in this subsection. The evaluation will, to the maximum extent possible, assess the impact of the short-term support services described in this subsection on the retention of foster homes and the number of placements a foster child receives while in out-of-home care as well as the return on investment to the state. The institute shall submit a preliminary report to the appropriate committees of the legislature and the governor by December 1, 2018, that describes the initial implementation of these services and descriptive statistics of the families utilizing these services. A final report shall be submitted to the appropriate committees of the legislature by June 30, 2021. At no cost to the institute, the department shall provide all data necessary to discharge this duty.

.. Costs associated with case aides as described in this subsection shall not be included in the forecast.

.. Pursuant to *RCW 41.06.142(3), performance-based contracting under (a) of this subsection is expressly mandated by the legislature and is not subject to the processes set forth in *RCW 41.06.142 (1), (4), and (5).

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5955-S.SL.pdf?cite=2019%20c%20470%20§%2029[2019 c 470 § 29]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5890-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%2020%20§%201[2017 3rd sp.s. c 20 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c284.pdf?cite=1990%20c%20284%20§%208[1990 c 284 § 8]; ]

== 74.13.280 - Client information.
. Except as provided in RCW 70.02.220, whenever a child is placed in out-of-home care by the department or with an agency, the department or agency shall share information known to the department or agency about the child and the child's family with the care provider and shall consult with the care provider regarding the child's case plan. If the child is dependent pursuant to a proceeding under chapter 13.34 RCW, the department or agency shall keep the care provider informed regarding the dates and location of dependency review and permanency planning hearings pertaining to the child.

. Information about the child and the child's family shall include information known to the department or agency as to whether the child is a sexually reactive child, has exhibited high-risk behaviors, or is physically assaultive or physically aggressive, as defined in this section.

. Information about the child shall also include information known to the department or agency that the child:

.. Has received a medical diagnosis of fetal alcohol syndrome or fetal alcohol effect;

.. Has been diagnosed by a qualified mental health professional as having a mental health disorder;

.. Has witnessed a death or substantial physical violence in the past or recent past; or

.. Was a victim of sexual or severe physical abuse in the recent past.

. Any person who receives information about a child or a child's family pursuant to this section shall keep the information confidential and shall not further disclose or disseminate the information except as authorized by law. Care providers shall agree in writing to keep the information that they receive confidential and shall affirm that the information will not be further disclosed or disseminated, except as authorized by law.

. Nothing in this section shall be construed to limit the authority of the department or an agency to disclose client information or to maintain client confidentiality as provided by law.

. The department may share the following mental health treatment records with a care provider, even if the child does not consent to releasing those records, if the department has initiated treatment pursuant to RCW 71.34.600 through 71.34.670:

.. Diagnosis;

.. Treatment plan and progress in treatment;

.. Recommended medications, including risks, benefits, side effects, typical efficacy, dose, and schedule;

.. Psychoeducation about the child's mental health;

.. Referrals to community resources;

.. Coaching on parenting or behavioral management strategies; and

.. Crisis prevention planning and safety planning.

. The department may not share substance use disorder treatment records with a care provider without the written consent of the child except as permitted by federal law.

. For the purposes of this section:

.. "Sexually reactive child" means a child who exhibits sexual behavior problems including, but not limited to, sexual behaviors that are developmentally inappropriate for their age or are harmful to the child or others.

.. "High-risk behavior" means an observed or reported and documented history of one or more of the following:

... Suicide attempts or suicidal behavior or ideation;

... Self-mutilation or similar self-destructive behavior;

... Fire-setting or a developmentally inappropriate fascination with fire;

... Animal torture;

.. Property destruction; or

.. Substance or alcohol abuse.

.. "Physically assaultive or physically aggressive" means a child who exhibits one or more of the following behaviors that are developmentally inappropriate and harmful to the child or to others:

... Observed assaultive behavior;

... Reported and documented history of the child willfully assaulting or inflicting bodily harm; or

... Attempting to assault or inflict bodily harm on other children or adults under circumstances where the child has the apparent ability or capability to carry out the attempted assaults including threats to use a weapon.

.. "Care provider" means a person with whom a child is placed in out-of-home care, or a designated official for a group care facility licensed by the department.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1874-S2.SL.pdf?cite=2019%20c%20381%20§%2021[2019 c 381 § 21]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6407.SL.pdf?cite=2018%20c%20284%20§%2045[2018 c 284 § 45]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1679-S.SL.pdf?cite=2013%20c%20200%20§%2028[2013 c 200 § 28]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2106-S2.SL.pdf?cite=2009%20c%20520%20§%2072[2009 c 520 § 72]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1287-S.SL.pdf?cite=2007%20c%20409%20§%206[2007 c 409 § 6]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5321-S.SL.pdf?cite=2007%20c%20220%20§%204[2007 c 220 § 4]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1102.SL.pdf?cite=2001%20c%20318%20§%203[2001 c 318 § 3]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2046-S2.SL.pdf?cite=1997%20c%20272%20§%207[1997 c 272 § 7]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5885-S.SL.pdf?cite=1995%20c%20311%20§%2021[1995 c 311 § 21]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5916-S.SL.pdf?cite=1991%20c%20340%20§%204[1991 c 340 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c284.pdf?cite=1990%20c%20284%20§%2010[1990 c 284 § 10]; ]

== 74.13.283 - Washington state identicards—Foster youth.
. For the purpose of assisting foster youth in obtaining a Washington state identicard, submission of the information and materials listed in this subsection from the department to the department of licensing is sufficient proof of identity and residency and shall serve as the necessary authorization for the youth to apply for and obtain a Washington state identicard:

.. A written signed statement prepared on department letterhead, verifying the following:

... The youth is a minor who resides in Washington;

... Pursuant to a court order, the youth is dependent and the department is the legal custodian of the youth under chapter 13.34 RCW or under the interstate compact on the placement of children;

... The youth's full name and date of birth;

... The youth's social security number, if available;

.. A brief physical description of the youth;

.. The appropriate address to be listed on the youth's identicard; and

.. Contact information for the appropriate person with the department.

.. A photograph of the youth, which may be digitized and integrated into the statement.

. The department may provide the statement and the photograph via any of the following methods, whichever is most efficient or convenient:

.. Delivered via first-class mail or electronically to the headquarters office of the department of licensing; or

.. Hand-delivered to a local office of the department of licensing by a department caseworker.

. A copy of the statement shall be provided to the youth who shall provide the copy to the department of licensing when making an in-person application for a Washington state identicard.

. To the extent other identifying information is readily available, the department shall include the additional information with the submission of information required under subsection (1) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6407.SL.pdf?cite=2018%20c%20284%20§%2046[2018 c 284 § 46]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2106-S2.SL.pdf?cite=2009%20c%20520%20§%2073[2009 c 520 § 73]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6792-S.SL.pdf?cite=2008%20c%20267%20§%207[2008 c 267 § 7]; ]

== 74.13.285 - Passports—Information to be provided to foster parents.
. Within available resources, the department shall prepare a passport containing all known and available information concerning the mental, physical, health, and educational status of the child for any child who has been in a foster home for ninety consecutive days or more. The passport shall contain education records obtained pursuant to RCW 28A.150.510. The passport shall be provided to a foster parent at any placement of a child covered by this section. The department shall update the passport during the regularly scheduled court reviews required under chapter 13.34 RCW.

New placements shall have first priority in the preparation of passports.

. In addition to the requirements of subsection (1) of this section, the department shall, within available resources, notify a foster parent before placement of a child of any known health conditions that pose a serious threat to the child and any known behavioral history that presents a serious risk of harm to the child or others.

. The department shall hold harmless the provider for any unauthorized disclosures caused by the department.

. Any foster parent who receives information about a child or a child's family pursuant to this section shall keep the information confidential and shall not further disclose or disseminate the information, except as authorized by law. Such individuals shall agree in writing to keep the information that they receive confidential and shall affirm that the information will not be further disclosed or disseminated, except as authorized by law.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6407.SL.pdf?cite=2018%20c%20284%20§%2047[2018 c 284 § 47]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2106-S2.SL.pdf?cite=2009%20c%20520%20§%2074[2009 c 520 § 74]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1287-S.SL.pdf?cite=2007%20c%20409%20§%207[2007 c 409 § 7]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2684.SL.pdf?cite=2000%20c%2088%20§%202[2000 c 88 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2046-S2.SL.pdf?cite=1997%20c%20272%20§%205[1997 c 272 § 5]; ]

== 74.13.287 - Intent—Infant, foster family health.
The legislature intends to establish a policy with the goal of ensuring that the health and well-being of both infants in foster care and the families providing for their care are protected.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/3081-S.SL.pdf?cite=2004%20c%2040%20§%201[2004 c 40 § 1]; ]

== 74.13.288 - Blood-borne pathogens—Testing.
The department of health shall develop recommendations concerning evidence-based practices for testing for blood-borne pathogens of children under one year of age who have been placed in out-of-home care and shall identify the specific pathogens for which testing is recommended.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2106-S2.SL.pdf?cite=2009%20c%20520%20§%2075[2009 c 520 § 75]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/3081-S.SL.pdf?cite=2004%20c%2040%20§%202[2004 c 40 § 2]; ]

== 74.13.289 - Blood-borne pathogens—Client information—Training.
. Upon any placement, the department shall inform each out-of-home care provider if the child to be placed in that provider's care is infected with a blood-borne pathogen, and shall identify the specific blood-borne pathogen for which the child was tested if known by the department.

. All out-of-home care providers licensed by the department shall receive training related to blood-borne pathogens, including prevention, transmission, infection control, treatment, testing, and confidentiality.

. Any disclosure of information related to HIV must be in accordance with RCW 70.02.220.

. The department of health shall identify by rule the term "blood-borne pathogen" as used in this section.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6407.SL.pdf?cite=2018%20c%20284%20§%2048[2018 c 284 § 48]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1679-S.SL.pdf?cite=2013%20c%20200%20§%2029[2013 c 200 § 29]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2106-S2.SL.pdf?cite=2009%20c%20520%20§%2076[2009 c 520 § 76]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/3081-S.SL.pdf?cite=2004%20c%2040%20§%203[2004 c 40 § 3]; ]

== 74.13.290 - Fewest possible placements for children—Preferred placements.
. To provide stability to children in out-of-home care, placement selection shall be made with a view toward the fewest possible placements for each child. If possible, the initial placement shall be viewed as the only placement for the child. Pursuant to RCW 13.34.060 and 13.34.130, placement of the child with a relative or other suitable person is the preferred option. The use of short-term interim placements of thirty days or less to protect the child's health or safety while the placement of choice is being arranged is not a violation of this principle.

. If a child has been previously placed in out-of-home care and is subsequently returned to out-of-home care, and the department cannot locate an appropriate and available relative or other suitable person, the preferred placement for the child is in a foster family home where the child previously was placed, if the following conditions are met:

.. The foster family home is available and willing to care for the child;

.. The foster family is appropriate and able to meet the child's needs; and

.. The placement is in the best interest of the child.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5431-S.SL.pdf?cite=2009%20c%20482%20§%201[2009 c 482 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c284.pdf?cite=1990%20c%20284%20§%2011[1990 c 284 § 11]; ]

== 74.13.300 - Notification of proposed placement changes.
. Whenever a child has been placed in a foster family home by the department and the child has thereafter resided in the home for at least ninety consecutive days, the department shall notify the foster family at least five days prior to moving the child to another placement, unless:

.. A court order has been entered requiring an immediate change in placement;

.. The child is being returned home;

.. The child's safety is in jeopardy; or

.. The child is residing in a receiving home or a group home.

. If the child has resided in a foster family home for less than ninety days or if, due to one or more of the circumstances in subsection (1) of this section, it is not possible to give five days' notification, the department shall notify the foster family of proposed placement changes as soon as reasonably possible.

. This section is intended solely to assist in minimizing disruption to the child in changing foster care placements. Nothing in this section shall be construed to require that a court hearing be held prior to changing a child's foster care placement nor to create any substantive custody rights in the foster parents.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6407.SL.pdf?cite=2018%20c%20284%20§%2049[2018 c 284 § 49]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2106-S2.SL.pdf?cite=2009%20c%20520%20§%2077[2009 c 520 § 77]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c284.pdf?cite=1990%20c%20284%20§%2012[1990 c 284 § 12]; ]

== 74.13.310 - Foster parent training.
Adequate foster parent training has been identified as directly associated with increasing the length of time foster parents are willing to provide foster care and reducing the number of placement disruptions for children. Placement disruptions can be harmful to children by denying them consistent and nurturing support. Foster parents have expressed the desire to receive training in addition to the foster parent training currently offered. Foster parents who care for more demanding children, such as children with severe disabilities, would especially benefit from additional training. The department shall develop additional training for foster parents that focuses on skills to assist foster parents in caring for children with disabilities.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2390.SL.pdf?cite=2020%20c%20274%20§%2062[2020 c 274 § 62]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6407.SL.pdf?cite=2018%20c%20284%20§%2050[2018 c 284 § 50]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2106-S2.SL.pdf?cite=2009%20c%20520%20§%2078[2009 c 520 § 78]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c284.pdf?cite=1990%20c%20284%20§%2013[1990 c 284 § 13]; ]

== 74.13.315 - Child care for foster parents attending meetings or training.
The department may provide child care for all foster parents who are required to attend department-sponsored meetings or training sessions. If the department does not provide such child care, the department, where feasible, shall conduct the activities covered by this section in the foster parent's home or other location acceptable to the foster parent.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6407.SL.pdf?cite=2018%20c%20284%20§%2051[2018 c 284 § 51]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2106-S2.SL.pdf?cite=2009%20c%20520%20§%2079[2009 c 520 § 79]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2046-S2.SL.pdf?cite=1997%20c%20272%20§%206[1997 c 272 § 6]; ]

== 74.13.325 - Foster care and adoptive home recruitment program.
Within available resources, the department shall increase the number of adoptive and foster families available to accept children through an intensive recruitment and retention program.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6407.SL.pdf?cite=2018%20c%20284%20§%2052[2018 c 284 § 52]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2106-S2.SL.pdf?cite=2009%20c%20520%20§%2081[2009 c 520 § 81]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2046-S2.SL.pdf?cite=1997%20c%20272%20§%203[1997 c 272 § 3]; ]

== 74.13.330 - Responsibilities of foster parents.
Foster parents are responsible for the protection, care, supervision, and nurturing of the child in placement. As an integral part of the foster care team, foster parents shall, if appropriate and they desire to: Participate in the development of the service plan for the child and the child's family; assist in family visitation, including monitoring; model effective parenting behavior for the natural family; and be available to help with the child's transition back to the natural family.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1333-S.SL.pdf?cite=2007%20c%20410%20§%207[2007 c 410 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c284.pdf?cite=1990%20c%20284%20§%2023[1990 c 284 § 23]; ]

== 74.13.332 - Rights of foster parents.
Foster parents have the right to be free of coercion, discrimination, and reprisal in serving foster children, including the right to voice grievances about treatment furnished or not furnished to the foster child.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1102.SL.pdf?cite=2001%20c%20318%20§%201[2001 c 318 § 1]; ]

== 74.13.333 - Rights of foster parents—Complaints—Investigation—Notice of any personnel action—Report.
. A foster parent who believes that a department employee has retaliated against the foster parent or in any other manner discriminated against the foster parent because:

.. The foster parent made a complaint with the office of the family and children's ombuds, the attorney general, law enforcement agencies, or the department provided information, or otherwise cooperated with the investigation of such a complaint;

.. The foster parent has caused to be instituted any proceedings under or related to Title 13 RCW;

.. The foster parent has testified or is about to testify in any proceedings under or related to Title 13 RCW;

.. The foster parent has advocated for services on behalf of the foster child;

.. The foster parent has sought to adopt a foster child in the foster parent's care; or

.. The foster parent has discussed or consulted with anyone concerning the foster parent's rights under this chapter or chapter 74.15 or 13.34 RCW, may file a complaint with the office of the family and children's ombuds.

. The ombuds may investigate the allegations of retaliation. The ombuds shall have access to all relevant information and resources held by or within the department by which to conduct the investigation. Upon the conclusion of its investigation, the ombuds shall provide its findings in written form to the department.

. The department shall notify the office of the family and children's ombuds in writing, within thirty days of receiving the ombuds's findings, of any personnel action taken or to be taken with regard to the department employee.

. The office of the family and children's ombuds shall also include its recommendations regarding complaints filed under this section in its annual report pursuant to RCW 43.06A.030. The office of the family and children's ombuds shall identify trends which may indicate a need to improve relations between the department and foster parents.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6407.SL.pdf?cite=2018%20c%20284%20§%2053[2018 c 284 § 53]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20206[2013 c 23 § 206]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2106-S2.SL.pdf?cite=2009%20c%20520%20§%2082[2009 c 520 § 82]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5811-S.SL.pdf?cite=2009%20c%20491%20§%2011[2009 c 491 § 11]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2988-S.SL.pdf?cite=2004%20c%20181%20§%201[2004 c 181 § 1]; ]

== 74.13.334 - Department procedures to respond to foster parents' complaints.
The department shall develop procedures for responding to recommendations of the office of the family and children's ombuds as a result of any and all complaints filed by foster parents under RCW 74.13.333.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6407.SL.pdf?cite=2018%20c%20284%20§%2054[2018 c 284 § 54]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20207[2013 c 23 § 207]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2106-S2.SL.pdf?cite=2009%20c%20520%20§%2083[2009 c 520 § 83]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2988-S.SL.pdf?cite=2004%20c%20181%20§%202[2004 c 181 § 2]; ]

== 74.13.335 - Foster care—Reimbursement—Property damage.
Within available funds and subject to such conditions and limitations as may be established by the department or by the legislature in the omnibus appropriations act, the department shall reimburse foster parents for property damaged or destroyed by foster children placed in their care. The department shall establish by rule a maximum amount that may be reimbursed for each occurrence. The department shall reimburse the foster parent for the replacement value of any property covered by this section. If the damaged or destroyed property is covered and reimbursed under an insurance policy, the department shall reimburse foster parents for the amount of the deductible associated with the insurance claim, up to the limit per occurrence as established by the department.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1661-S2.SL.pdf?cite=2017%203rd%20sp.s.%20c%206%20§%20407[2017 3rd sp.s. c 6 § 407]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1619-S.SL.pdf?cite=1999%20c%20338%20§%202[1999 c 338 § 2]; ]

== 74.13.336 - Extended foster care services.
. A youth who has reached age eighteen years may request extended foster care services authorized under RCW 74.13.031 at any time before he or she reaches the age of twenty-one years if:

.. The dependency proceeding of the youth was dismissed pursuant to RCW 13.34.267(4) at the time that he or she reached age eighteen years; or

.. The court, after holding the dependency case open pursuant to RCW 13.34.267(1), has dismissed the case because the youth became ineligible for extended foster care services.

. [Empty]
.. Upon a request for extended foster care services by a youth pursuant to subsection (1) of this section, a determination that the youth is eligible for extended foster care services, and the completion of a voluntary placement agreement, the department shall provide extended foster care services to the youth.

.. In order to continue receiving extended foster care services after entering into a voluntary placement agreement with the department, the youth must agree to the entry of an order of dependency within one hundred eighty days of the date that the youth is placed in extended foster care pursuant to a voluntary placement agreement.

. A youth may enter into a voluntary placement agreement for extended foster care services. A youth may transition among the eligibility categories identified in RCW 74.13.031 while under the same voluntary placement agreement, provided that the youth remains eligible for extended foster care services during the transition.

. "Voluntary placement agreement," for the purposes of this section, means a written voluntary agreement between a nonminor dependent who agrees to submit to the care and authority of the department for the purposes of participating in the extended foster care program.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6222-S.SL.pdf?cite=2018%20c%2034%20§%204[2018 c 34 § 4]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5405-S2.SL.pdf?cite=2013%20c%20332%20§%205[2013 c 332 § 5]; ]

== 74.13.338 - Driver's license support for foster youth.
. Subject to the availability of funds appropriated for this specific purpose, the department shall contract with a private nonprofit organization that agrees to work collaboratively with independent living providers and the department and is selected after a competitive application process to provide driver's license support for foster youth, including youth receiving extended foster care services.

. The nonprofit organization selected pursuant to subsection (1) of this section shall provide support for foster youth ages fifteen through twenty-one, including youth receiving extended foster care services, in navigating the driver's licensing process. This support must include:

.. Reimbursement of fees necessary for a foster youth to obtain a driver's instruction permit, an intermediate license, and a standard or enhanced driver's license, including any required examination fees, as described in chapter 46.20 RCW;

.. Reimbursement of fees required for a foster youth to complete a driver training education course, if the foster youth is under the age of eighteen, as outlined in chapter 46.82 or 28A.220 RCW;

.. Reimbursement of the increase in motor vehicle liability insurance costs incurred by foster parents, relative placements, or other foster placements adding a foster youth to his or her motor vehicle liability insurance policy, with a preference on reimbursements for those foster youth who practice safe driving and avoid moving violations and at-fault collisions.

. By December 1, 2019, the nonprofit organization selected pursuant to subsection (1) of this section shall submit a report to the department and the appropriate committees of the legislature, including the transportation committees of the legislature, documenting the number of foster youth served by the program; the average cost per youth served; the extent to which foster youth report any negative outcomes of the program, including a foster parent's inappropriate use of a foster youth's driving authorization; and recommendations for future policy or statutory or funding changes necessary to more effectively allow foster youth to obtain drivers' licenses and motor vehicle liability insurance.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1808-S.SL.pdf?cite=2017%20c%20206%20§%201[2017 c 206 § 1]; ]

== 74.13.341 - Transition plan—Qualification for developmental disability services.
With respect to youth who will be aging out of foster care, the department shall invite representatives from the department of social and health services division of behavioral health and recovery, the disability services administration, the economic services administration, and the juvenile justice and rehabilitation administration to the youth's shared planning meeting that occurs between age seventeen and seventeen and one-half that is used to develop a transition plan. It is the responsibility of the department to include these agencies in the shared planning meeting. If foster youth who are the subject of this meeting may qualify for developmental disability services pursuant to Title 71A RCW, the department shall direct these youth to apply for these services and provide assistance in the application process.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6287.SL.pdf?cite=2018%20c%2058%20§%2049[2018 c 58 § 49]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5740-S.SL.pdf?cite=2015%20c%20240%20§%204[2015 c 240 § 4]; ]

== 74.13.500 - Disclosure of child welfare records—Factors—Exception.
. Consistent with the provisions of chapter 42.56 RCW and applicable federal law, the secretary, or the secretary's designee, shall disclose information regarding the abuse or neglect of a child, the investigation of the abuse, neglect, or near fatality of a child, and any services related to the abuse or neglect of a child if any one of the following factors is present:

.. The subject of the report has been charged in an accusatory instrument with committing a crime related to a report maintained by the department in its case and management information system;

.. The investigation of the abuse or neglect of the child by the department or the provision of services by the department has been publicly disclosed in a report required to be disclosed in the course of their official duties, by a law enforcement agency or official, a prosecuting attorney, any other state or local investigative agency or official, or by a judge of the superior court;

.. There has been a prior knowing, voluntary public disclosure by an individual concerning a report of child abuse or neglect in which such individual is named as the subject of the report; or

.. The child named in the report has died and the child's death resulted from abuse or neglect or the child was in the care of, or receiving services from the department at the time of death or within twelve months before death.

. The secretary is not required to disclose information if the factors in subsection (1) of this section are present if he or she specifically determines the disclosure is contrary to the best interests of the child, the child's siblings, or other children in the household.

. Except for cases in subsection (1)(d) of this section, requests for information under this section shall specifically identify the case about which information is sought and the facts that support a determination that one of the factors specified in subsection (1) of this section is present.

. For the purposes of this section, "near fatality" means an act that, as certified by a physician, places the child in serious or critical condition. The secretary is under no obligation to have an act certified by a physician in order to comply with this section.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6407.SL.pdf?cite=2018%20c%20284%20§%2055[2018 c 284 § 55]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2106-S2.SL.pdf?cite=2009%20c%20520%20§%2084[2009 c 520 § 84]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1133-S.SL.pdf?cite=2005%20c%20274%20§%20351[2005 c 274 § 351]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1810.SL.pdf?cite=1999%20c%20339%20§%201[1999 c 339 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5770-S.SL.pdf?cite=1997%20c%20305%20§%202[1997 c 305 § 2]; ]

== 74.13.505 - Disclosure of child welfare records—Information to be disclosed.
For purposes of RCW 74.13.500, the following information shall be disclosable:

. The name of the abused or neglected child;

. The determination made by the department of the referrals, if any, for abuse or neglect;

. Identification of child protective or other services provided or actions, if any, taken regarding the child named in the report and his or her family as a result of any such report or reports. These records include but are not limited to administrative reports of fatality, fatality review reports, case files, inspection reports, and reports relating to social work practice issues; and

. Any actions taken by the department in response to reports of abuse or neglect of the child.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5770-S.SL.pdf?cite=1997%20c%20305%20§%203[1997 c 305 § 3]; ]

== 74.13.510 - Disclosure of child welfare records—Consideration of effects.
In determining under RCW 74.13.500 whether disclosure will be contrary to the best interests of the child, the secretary, or the secretary's designee, must consider the effects which disclosure may have on efforts to reunite and provide services to the family.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5770-S.SL.pdf?cite=1997%20c%20305%20§%204[1997 c 305 § 4]; ]

== 74.13.515 - Disclosure of child welfare records—Fatalities.
For purposes of RCW 74.13.500(1)(d), the secretary must make the fullest possible disclosure consistent with chapter 42.56 RCW and applicable federal law in cases of all fatalities of children who were in the care of, or receiving services from, the department at the time of their death or within the twelve months previous to their death.

If the secretary specifically determines that disclosure of the name of the deceased child is contrary to the best interests of the child's siblings or other children in the household, the secretary may remove personally identifying information.

For the purposes of this section, "personally identifying information" means the name, street address, social security number, and day of birth of the child who died and of private persons who are relatives of the child named in child welfare records. "Personally identifying information" shall not include the month or year of birth of the child who has died. Once this personally identifying information is removed, the remainder of the records pertaining to a child who has died must be released regardless of whether the remaining facts in the records are embarrassing to the unidentifiable other private parties or to identifiable public workers who handled the case.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6407.SL.pdf?cite=2018%20c%20284%20§%2056[2018 c 284 § 56]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2106-S2.SL.pdf?cite=2009%20c%20520%20§%2085[2009 c 520 § 85]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1133-S.SL.pdf?cite=2005%20c%20274%20§%20352[2005 c 274 § 352]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5770-S.SL.pdf?cite=1997%20c%20305%20§%205[1997 c 305 § 5]; ]

== 74.13.520 - Disclosure of child welfare records—Information not to be disclosed.
Except as it applies directly to the cause of the abuse or neglect of the child and any actions taken by the department in response to reports of abuse or neglect of the child, nothing in RCW 74.13.500 through 74.13.515 is deemed to authorize the release or disclosure of the substance or content of any psychological, psychiatric, therapeutic, clinical, or medical reports, evaluations, or like materials, or information pertaining to the child or the child's family.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5770-S.SL.pdf?cite=1997%20c%20305%20§%206[1997 c 305 § 6]; ]

== 74.13.525 - Disclosure of child welfare records—Immunity from liability.
The department, when acting in good faith, is immune from any criminal or civil liability, except as provided under RCW 42.56.550, for any action taken under RCW 74.13.500 through 74.13.520.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6407.SL.pdf?cite=2018%20c%20284%20§%2057[2018 c 284 § 57]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2106-S2.SL.pdf?cite=2009%20c%20520%20§%2086[2009 c 520 § 86]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1133-S.SL.pdf?cite=2005%20c%20274%20§%20353[2005 c 274 § 353]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5770-S.SL.pdf?cite=1997%20c%20305%20§%207[1997 c 305 § 7]; ]

== 74.13.530 - Child placement—Conflict of interest.
. No child may be placed or remain in a specific out-of-home placement under this chapter or chapter 13.34 RCW when there is a conflict of interest on the part of any adult residing in the home in which the child is to be or has been placed. A conflict of interest exists when:

.. There is an adult in the home who, as a result of: (i) His or her employment; and (ii) an allegation of abuse or neglect of the child, conducts or has conducted an investigation of the allegation; or

.. The child has been, is, or is likely to be a witness in any pending cause of action against any adult in the home when the cause includes: (i) An allegation of abuse or neglect against the child or any sibling of the child; or (ii) a claim of damages resulting from wrongful interference with the parent-child relationship of the child and his or her biological or adoptive parent.

. For purposes of this section, "investigation" means the exercise of professional judgment in the review of allegations of abuse or neglect by: (a) Law enforcement personnel; (b) persons employed by, or under contract with, the state; (c) persons licensed to practice law and their employees; and (d) mental health professionals as defined in chapter 71.05 RCW.

. The prohibition set forth in subsection (1) of this section may not be waived or deferred by the department under any circumstance or at the request of any person, regardless of who has made the request or the length of time of the requested placement.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6407.SL.pdf?cite=2018%20c%20284%20§%2058[2018 c 284 § 58]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2106-S2.SL.pdf?cite=2009%20c%20520%20§%2087[2009 c 520 § 87]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1102.SL.pdf?cite=2001%20c%20318%20§%204[2001 c 318 § 4]; ]

== 74.13.540 - Independent living services.
Independent living services include assistance in achieving basic educational requirements such as a high school equivalency certificate as provided in RCW 28B.50.536, enrollment in vocational and technical training programs offered at the community and vocational colleges, and obtaining and maintaining employment; and accomplishing basic life skills such as money management, nutrition, preparing meals, and cleaning house. A baseline skill level in ability to function productively and independently shall be determined at entry. Performance shall be measured and must demonstrate improvement from involvement in the program. Each recipient shall have a plan for achieving independent living skills by the time the recipient reaches age twenty-one. The plan shall be written within the first thirty days of placement and reviewed every ninety days. A recipient who fails to consistently adhere to the elements of the plan shall be subject to reassessment by the professional staff of the program and may be declared ineligible to receive services.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1686-S.SL.pdf?cite=2013%20c%2039%20§%2030[2013 c 39 § 30]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1259-S.SL.pdf?cite=2001%20c%20192%20§%202[2001 c 192 § 2]; ]

== 74.13.550 - Child placement—Policy of educational continuity.
It is the policy of the state of Washington that, whenever practical and in the best interest of the child, children placed into foster care shall remain enrolled in the schools they were attending at the time they entered foster care.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1058-S.SL.pdf?cite=2003%20c%20112%20§%202[2003 c 112 § 2]; ]

== 74.13.560 - Educational continuity—Protocol development.
. The administrative regions of the department shall, in collaboration with school districts within their region as required by RCW 28A.225.360, develop protocols specifying specific strategies for communication, coordination, and collaboration regarding the status and progress of children in out-of-home care placed in the region. The purpose of the protocols is to maximize the educational continuity and achievement for children in out-of-home care. The protocols must include methods to assure effective sharing of information, consistent with RCW 28A.225.330.

. The protocols required by this section must also include protocols for making best interest determinations for students in out-of-home care that comply with RCW 28A.225.350. The protocols for making best interest determinations for students in out-of-home care must be implemented before changing the school placement of a student.

. For the purposes of this section, "out-of-home care" has the same meaning as in RCW 13.34.030.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6407.SL.pdf?cite=2018%20c%20284%20§%2059[2018 c 284 § 59]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2684-S.SL.pdf?cite=2018%20c%20139%20§%204[2018 c 139 § 4]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2106-S2.SL.pdf?cite=2009%20c%20520%20§%2088[2009 c 520 § 88]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1058-S.SL.pdf?cite=2003%20c%20112%20§%203[2003 c 112 § 3]; ]

== 74.13.570 - Oversight committee—Duties.
. The department shall establish an oversight committee composed of staff from the office of the superintendent of public instruction, the student achievement council, foster youth, former foster youth, foster parents, and advocacy agencies to develop strategies for maintaining foster children in the schools they were attending at the time they entered foster care and to promote opportunities for foster youth to participate in postsecondary education or training.

. The duties of the oversight committee shall include, but are not limited to:

.. Developing strategies for school-based recruitment of foster homes;

.. Monitoring the progress of current pilot projects that assist foster children to continue attending the schools they were attending at the time they entered foster care;

.. Overseeing the expansion of the number of pilot projects;

.. Promoting the use of best practices, throughout the state, demonstrated by the pilot projects and other programs relating to maintaining foster children in the schools they were attending at the time they entered foster care;

.. Informing the legislature of the status of efforts to maintain foster children in the schools they were attending at the time they entered foster care;

.. Assessing the scope and nature of statewide need among current and former foster youth for assistance to pursue and participate in postsecondary education or training opportunities;

.. Identifying available sources of funding available in the state for services to former foster youth to pursue and participate in postsecondary education or training opportunities;

.. Reviewing the effectiveness of activities in the state to support former foster youth to pursue and participate in postsecondary education or training opportunities;

.. Identifying new activities, or existing activities that should be modified or expanded, to best meet statewide needs; and

.. Reviewing on an ongoing basis the progress toward improving educational and vocational outcomes for foster youth.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6287.SL.pdf?cite=2018%20c%2058%20§%2058[2018 c 58 § 58]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2483-S2.SL.pdf?cite=2012%20c%20229%20§%20594[2012 c 229 § 594]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1079-S.SL.pdf?cite=2005%20c%2093%20§%202[2005 c 93 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1058-S.SL.pdf?cite=2003%20c%20112%20§%204[2003 c 112 § 4]; ]

== 74.13.580 - Educational stability during shelter care hearing—Protocol development.
The department shall work with the administrative office of the courts to develop protocols to ensure that educational stability is addressed during the shelter care hearing.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1058-S.SL.pdf?cite=2003%20c%20112%20§%205[2003 c 112 § 5]; ]

== 74.13.590 - Tasks to be performed based on available resources.
The department shall perform the tasks provided in RCW 74.13.550 through 74.13.580 based on available resources.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6407.SL.pdf?cite=2018%20c%20284%20§%2060[2018 c 284 § 60]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2106-S2.SL.pdf?cite=2009%20c%20520%20§%2089[2009 c 520 § 89]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1058-S.SL.pdf?cite=2003%20c%20112%20§%206[2003 c 112 § 6]; ]

== 74.13.600 - Kinship caregivers—Definition—Placement of children with kin a priority—Strategies.
. For the purposes of this section, "kin" means persons eighteen years of age or older to whom the child is related by blood, adoption, or marriage, including marriages that have been dissolved, and means: (a) Any person denoted by the prefix "grand" or "great"; (b) sibling, whether full, half, or step; (c) uncle or aunt; (d) nephew or niece; or (e) first cousin.

. The department shall plan, design, and implement strategies to prioritize the placement of children with willing and able kin when out-of-home placement is required.

These strategies must include at least the following:

.. Development of standardized, statewide procedures to be used when searching for kin of children prior to out-of-home placement. The procedures must include a requirement that documentation be maintained in the child's case record that identifies kin, and documentation that identifies the assessment criteria and procedures that were followed during all kin searches. The procedures must be used when a child is placed in out-of-home care under authority of chapter 13.34 RCW, when a petition is filed under RCW 13.32A.140, or when a child is placed under a voluntary placement agreement. To assist with implementation of the procedures, the department shall request that the juvenile court require parents to disclose to the department all contact information for available and appropriate kin within two weeks of an entered order. For placements under signed voluntary agreements, the department shall encourage the parents to disclose to the department all contact information for available and appropriate kin within two weeks of the date the parent signs the voluntary placement agreement.

.. Development of procedures for conducting active outreach efforts to identify and locate kin during all searches. The procedures must include at least the following elements:

... Reasonable efforts to interview known kin, friends, teachers, and other identified community members who may have knowledge of the child's kin, within sixty days of the child entering out-of-home care;

... Increased use of those procedures determined by research to be the most effective methods of promoting reunification efforts, permanency planning, and placement decisions;

... Contacts with kin identified through outreach efforts and interviews under this subsection as part of permanency planning activities and change of placement discussions;

... Establishment of a process for ongoing contact with kin who express interest in being considered as a placement resource for the child; and

.. A requirement that when the decision is made to not place the child with any kin, the department provides documentation as part of the child's individual service and safety plan that clearly identifies the rationale for the decision and corrective action or actions the kin must take to be considered as a viable placement option.

. Nothing in this section shall be construed to create an entitlement to services or to create judicial authority to order the provision of services to any person or family if the services are unavailable or unsuitable or the child or family is not eligible for such services.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6407.SL.pdf?cite=2018%20c%20284%20§%2061[2018 c 284 § 61]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2106-S2.SL.pdf?cite=2009%20c%20520%20§%2090[2009 c 520 § 90]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1233-S.SL.pdf?cite=2003%20c%20284%20§%201[2003 c 284 § 1]; ]

== 74.13.621 - Kinship care oversight committee.
. Within existing resources, the department shall establish an oversight committee to monitor, guide, and report on kinship care recommendations and implementation activities. The committee shall:

.. Draft a kinship care definition that is restricted to persons related by blood, marriage, or adoption, including marriages that have been dissolved, or for a minor defined as an "Indian child" under the federal Indian child welfare act (25 U.S.C. Sec. 1901 et seq.), the definition of "extended family member" under the federal Indian child welfare act, and a set of principles. If the committee concludes that one or more programs or services would be more efficiently and effectively delivered under a different definition of kin, it shall state what definition is needed, and identify the program or service in the report. It shall also provide evidence of how the program or service will be more efficiently and effectively delivered under the different definition. The department shall not adopt rules or policies changing the definition of kin without authorizing legislation;

.. Monitor and provide consultation on the implementation of recommendations contained in the 2002 kinship care report, including but not limited to the recommendations relating to legal and respite care services and resources;

.. Partner with nonprofit organizations and private sector businesses to guide a public education awareness campaign;

.. Assist with developing future recommendations on kinship care issues; and

.. Coordinate with the kinship care legal aid coordinator to develop, expand, and deliver training materials designed to help pro bono and low bono attorneys provide legal advice and assistance to kinship caregivers on matters that relate to their ability to meet physical, mental, social, educational, and other needs of children and youth in their care.

. The department shall consult with the oversight committee on its efforts to better collaborate and coordinate services to benefit kinship care families.

. The oversight committee must consist of a minimum of thirty percent kinship caregivers, who shall represent a diversity of kinship families. Statewide representation with geographic, ethnic, and gender diversity is required. Other members shall include representatives of the department, representatives of relevant state agencies, representatives of the private nonprofit and business sectors, child advocates, representatives of Washington state Indian tribes as defined under the federal Indian welfare act (25 U.S.C. Sec. 1901 et seq.), and representatives of the legal or judicial field. Birth parents, foster parents, and others who have an interest in these issues may also be included.

. To the extent funding is available, the department may reimburse nondepartmental members of the oversight committee for costs incurred in participating in the meetings of the oversight committee.

. The kinship care oversight committee shall update the legislature and governor annually on committee activities, with each update due by December 1st.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5651.SL.pdf?cite=2019%20c%20465%20§%202[2019 c 465 § 2]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5883-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%201%20§%20982[2017 3rd sp.s. c 1 § 982]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6052-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%204%20§%20970[2015 3rd sp.s. c 4 § 970]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5034-S.SL.pdf?cite=2013%202nd%20sp.s.%20c%204%20§%20996[2013 2nd sp.s. c 4 § 996]; 2011 1st sp.s. c 50 § 965; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1244-S.SL.pdf?cite=2009%20c%20564%20§%20954[2009 c 564 § 954]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1280-S.SL.pdf?cite=2005%20c%20439%20§%201[2005 c 439 § 1]; ]

== 74.13.631 - School-aged youth in out-of-home care—School placement options.
. Consistent with the provisions for making best interest determinations established in RCW 28A.225.350 and 74.13.560, the department shall provide youth residing in out-of-home care the opportunity to remain enrolled in the school he or she was attending prior to out-of-home placement, unless the safety of the youth is jeopardized, or a relative or other suitable person placement approved by the department is secured for the youth, or it is determined not to be in the youth's best interest to remain enrolled in the school he or she was attending prior to out-of-home placement. If the parties in the dependency case disagree regarding which school the youth should be enrolled in, the youth may remain enrolled in the school of origin until the disagreement is resolved in court, unless the department determines that the youth is in immediate danger by remaining enrolled in the school of origin.

. Unless otherwise directed by the court, the educational responsibilities of the department for school-aged youth residing in out-of-home care are the following:

.. To collaboratively discuss and document school placement options and plan necessary school transfers during the family team decision-making meeting;

.. To notify the receiving school and the school of origin that a youth residing in foster care is transferring schools;

.. To request and secure missing academic records or medical records required for school enrollment within ten business days;

.. To document the request and receipt of academic records in the individual service and safety plan;

.. To pay any unpaid fees or fines due by the youth to the school or school district;

.. To notify all legal parties when a school disruption occurs; and

.. To document factors that contributed to any school disruptions.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2684-S.SL.pdf?cite=2018%20c%20139%20§%205[2018 c 139 § 5]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1566-S2.SL.pdf?cite=2013%20c%20182%20§%206[2013 c 182 § 6]; ]

== 74.13.632 - School-aged youth in out-of-home care—Educational experiences and progress—Reports.
. A university-based child welfare research entity shall include in its reporting the educational experiences and progress of students in out-of-home care with the department. This data must be disaggregated in the smallest units allowable by law that do not identify an individual student, in order to learn which of the department's offices and school districts are experiencing the greatest success and challenges in achieving quality educational outcomes with students in out-of-home care with the department.

. By January 1, 2015 and annually thereafter, the university-based child welfare research entity must submit a report to the legislature. To the extent possible, the report should include, but is not limited to, information on the following measures for a youth who is a dependent pursuant to chapter 13.34 RCW:

.. Aggregate scores from the Washington state kindergarten readiness assessment;

.. Aggregate scores from the third grade statewide student assessment in reading;

.. Number of youth graduating from high school with a documented plan for postsecondary education, employment, or military service;

.. Number of youth completing one year of postsecondary education, the equivalent of first-year student credits, or achieving a postsecondary certificate; and

.. Number of youth who complete an associate or bachelor's degree.

. The report must identify strengths and weaknesses in practice and recommend to the legislature strategy and needed resources for improvement.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6287.SL.pdf?cite=2018%20c%2058%20§%2048[2018 c 58 § 48]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1566-S2.SL.pdf?cite=2013%20c%20182%20§%207[2013 c 182 § 7]; ]

== 74.13.640 - Child fatality reviews.
. [Empty]
.. The department shall conduct a child fatality review in the event of a fatality suspected to be caused by child abuse or neglect of any minor who is in the care of the department or receiving services described in this chapter or who has been in the care of the department or received services described in this chapter within one year preceding the minor's death.

.. The department shall consult with the office of the family and children's ombuds to determine if a child fatality review should be conducted in any case in which it cannot be determined whether the child's death is the result of suspected child abuse or neglect.

.. The department shall ensure that the fatality review team is made up of individuals who had no previous involvement in the case, including individuals whose professional expertise is pertinent to the dynamics of the case.

.. Upon conclusion of a child fatality review required pursuant to this section, the department shall within one hundred eighty days following the fatality issue a report on the results of the review, unless an extension has been granted by the governor. Reports must be distributed to the appropriate committees of the legislature, and the department shall create a public web site where all child fatality review reports required under this section must be posted and maintained. A child fatality review report completed pursuant to this section is subject to public disclosure and must be posted on the public web site, except that confidential information may be redacted by the department consistent with the requirements of RCW 13.50.100, 68.50.105, 74.13.500 through 74.13.525, chapter 42.56 RCW, and other applicable state and federal laws.

.. The department shall develop and implement procedures to carry out the requirements of this section.

. [Empty]
.. In the event of a near fatality of a child who is in the care of or receiving services described in this chapter from the department or who has been in the care of or received services described in this chapter from the department within one year preceding the near fatality, the department shall promptly notify the office of the family and children's ombuds. The department may conduct a review of the near fatality at its discretion or at the request of the office of the family and children's ombuds.

.. In the event of a near fatality of a child who is in the care of or receiving services described in this chapter from the department or who has been in the care of or received services described in this chapter from the department within three months preceding the near fatality, or was the subject of an investigation by the department for possible abuse or neglect, the department shall promptly notify the office of the family and children's ombuds and the department shall conduct a review of the near fatality.

.. "Near fatality" means an act that, as certified by a physician, places the child in serious or critical condition.

. In any review of a child fatality or near fatality in which the child was placed with or received services from an agency pursuant to a contract with the department, the department and the fatality review team shall have access to all records and files regarding the child or otherwise relevant to the review that have been produced or retained by the agency.

. [Empty]
.. A child fatality or near fatality review completed pursuant to this section is subject to discovery in a civil or administrative proceeding, but may not be admitted into evidence or otherwise used in a civil or administrative proceeding except pursuant to this section.

.. A department employee responsible for conducting a child fatality or near fatality review, or member of a child fatality or near fatality review team, may not be examined in a civil or administrative proceeding regarding (i) the work of the child fatality or near fatality review team, (ii) the incident under review, (iii) his or her statements, deliberations, thoughts, analyses, or impressions relating to the work of the child fatality or near fatality review team or the incident under review, or (iv) the statements, deliberations, thoughts, analyses, or impressions of any other member of the child fatality or near fatality review team, or any person who provided information to the child fatality or near fatality review team, relating to the work of the child fatality or near fatality review team or the incident under review.

.. Documents prepared by or for a child fatality or near fatality review team are inadmissible and may not be used in a civil or administrative proceeding, except that any document that exists before its use or consideration in a child fatality or near fatality review, or that is created independently of such review, does not become inadmissible merely because it is reviewed or used by a child fatality or near fatality review team. A person is not unavailable as a witness merely because the person has been interviewed by or has provided a statement for a child fatality or near fatality review, but if called as a witness, a person may not be examined regarding the person's interactions with the child fatality or near fatality review including, without limitation, whether the person was interviewed during such review, the questions that were asked during such review, and the answers that the person provided during such review. This section may not be construed as restricting the person from testifying fully in any proceeding regarding his or her knowledge of the incident under review.

.. The restrictions set forth in this section do not apply in a licensing or disciplinary proceeding arising from an agency's effort to revoke or suspend the license of any licensed professional based in whole or in part upon allegations of wrongdoing in connection with a minor's death or near fatality reviewed by a child fatality or near fatality review team.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6407.SL.pdf?cite=2018%20c%20284%20§%2062[2018 c 284 § 62]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5888-S2.SL.pdf?cite=2015%20c%20298%20§%201[2015 c 298 § 1]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20209[2013 c 23 § 209]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1105-S.SL.pdf?cite=2011%20c%2061%20§%202[2011 c 61 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2106-S2.SL.pdf?cite=2009%20c%20520%20§%2091[2009 c 520 § 91]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6206-S2.SL.pdf?cite=2008%20c%20211%20§%201[2008 c 211 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2984-S.SL.pdf?cite=2004%20c%2036%20§%201[2004 c 36 § 1]; ]

== 74.13.650 - Foster parent critical support and retention program.
A foster parent critical support and retention program is established to retain foster parents who care for sexually reactive children, physically assaultive children, or children with other high-risk behaviors, as defined in RCW 74.13.280. Services shall consist of short-term therapeutic and educational interventions to support the stability of the placement. The department shall enter into performance-based contracts with agencies to provide this program.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6407.SL.pdf?cite=2018%20c%20284%20§%2063[2018 c 284 § 63]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2106-S2.SL.pdf?cite=2009%20c%20520%20§%2092[2009 c 520 § 92]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5321-S.SL.pdf?cite=2007%20c%20220%20§%207[2007 c 220 § 7]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/3115-S2.SL.pdf?cite=2006%20c%20353%20§%202[2006 c 353 § 2]; ]

== 74.13.660 - Foster parent critical support and retention program—Availability, assessment, training, referral.
Under the foster parent critical support and retention program, foster parents who care for sexually reactive children, physically assaultive children, or children with other high-risk behaviors, as defined in RCW 74.13.280, shall receive:

. Availability at any time of the day or night to address specific concerns related to the identified child;

. Assessment of risk and development of a safety and supervision plan;

. Home-based foster parent training utilizing evidence-based models; and

. Referral to relevant community services and training provided by the local department office or community agencies.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6287.SL.pdf?cite=2018%20c%2058%20§%2057[2018 c 58 § 57]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5321-S.SL.pdf?cite=2007%20c%20220%20§%208[2007 c 220 § 8]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/3115-S2.SL.pdf?cite=2006%20c%20353%20§%203[2006 c 353 § 3]; ]

== 74.13.670 - Care provider immunity for allegation of failure to supervise a sexually reactive, physically assaultive, or physically aggressive youth—Conditions.
. A care provider may not be found to have abused or neglected a child under chapter 26.44 RCW or be denied a license pursuant to chapter 74.15 RCW and RCW 74.13.031 for any allegations of failure to supervise in which:

.. The allegations arise from the child's conduct that is substantially similar to prior behavior of the child, and:

... The child is a sexually reactive youth, exhibits high-risk behaviors, or is physically assaultive or physically aggressive as defined in RCW 74.13.280, and this information and the child's prior behavior was not disclosed to the care provider as required by RCW 74.13.280; and

... The care provider did not know or have reason to know that the child needed supervision as a sexually reactive or physically assaultive or physically aggressive youth, or because of a documented history of high-risk behaviors, as a result of the care provider's involvement with or independent knowledge of the child or training and experience; or

.. The child was not within the reasonable control of the care provider at the time of the incident that is the subject of the allegation, and the care provider was acting in good faith and did not know or have reason to know that reasonable control or supervision of the child was necessary to prevent harm or risk of harm to the child or other persons.

. Allegations of child abuse or neglect that meet the provisions of this section shall be designated as "unfounded" as defined in RCW 26.44.020.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2106-S2.SL.pdf?cite=2009%20c%20520%20§%2093[2009 c 520 § 93]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5321-S.SL.pdf?cite=2007%20c%20220%20§%205[2007 c 220 § 5]; ]

== 74.13.680 - Foster care to twenty-one program—Termination.
. Within amounts appropriated for this specific purpose, the department shall continue to operate the state-funded foster care to twenty-one program for three years after June 7, 2012, at which point the program shall cease to operate.

. The department shall not have the authority to enroll any new youth under this program after June 7, 2012, and shall only serve eligible youth enrolled prior to that date.

. The purpose of the foster care to twenty-one program is to serve youth ages eighteen to twenty-one who are enrolled and participating in a postsecondary academic or postsecondary vocational program.

. A youth participating in this program may, within amounts appropriated for this specific purpose, continue to receive placement services until the youth reaches his or her twenty-first birthday or is no longer enrolled in and participating in a postsecondary program, whichever is earlier.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2592-S.SL.pdf?cite=2012%20c%2052%20§%203[2012 c 52 § 3]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1128-S2.SL.pdf?cite=2011%20c%20330%20§%208[2011 c 330 § 8]; ]

== 74.13.690 - Child welfare measurements.
. A university-based child welfare research entity and the department, in collaboration with other stakeholders, shall develop measurements in the areas of safety, permanency, and well-being, using existing and available data. Measurements must be calculated from data used in the routine work of the state agencies' data and information technology departments. Any new record linkage or data-matching activities required in fulfillment of this section may be performed by the research entity pursuant to agreements developed under subsection (6) of this section.

. For the purposes of this section, "state agencies" means any agency or subagency providing data used in the integrated client database maintained by the research and data analysis division of the department. Any exchange of data must be in accordance with applicable federal and state law.

. All measurements must use a methodology accepted by the scientific community. All measurements must address any disproportionate racial and ethnic inequality. The initial measurements must be developed by December 1, 2013.

. The measurements may not require the state agencies to revise their data collection systems, and may not require the state agencies to provide individually identifiable information.

. The state agencies shall provide the research entity with all measurement data related to the measurements developed under this section at least quarterly beginning July 1, 2014. The research entity shall make any nonidentifiable data publicly available. The research entity shall report on the data to the legislature and the governor annually starting December 31, 2014.

. By January 1, 2014, the state agencies shall execute agreements with the research entity to enable sharing of data pursuant to RCW 42.48.020 sufficient to comply with this section.

. The fact that the research entity has chosen to use a specific measure, use a specific baseline, or compare any measure to a baseline is not admissible as evidence of negligence by the department in a civil action.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1774-S.SL.pdf?cite=2013%20c%20205%20§%202[2013 c 205 § 2]; ]

== 74.13.695 - Validated tool to assess care needs.
The office of innovation, alignment, and accountability must develop a single validated tool to assess the care needs of foster children. Once the validated tool is available for use on a statewide basis, the department of children, youth, and families must use the tool for assessing the care needs of foster children, including but not limited to whether the department should provide foster children with behavioral rehabilitation services. The department must notify the caseload forecast council, the office of financial management, and the appropriate fiscal committees of the legislature when it begins statewide use of the validated tool.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2008.SL.pdf?cite=2018%20c%20208%20§%203[2018 c 208 § 3]; ]

== 74.13.700 - Denial or delay of licensure or approval of unsupervised access to children. (Effective until January 1, 2021.)
. In determining the character, suitability, and competence of an individual, the department may not:

.. Deny or delay a license or approval of unsupervised access to children to an individual solely because of a crime or civil infraction involving the individual or entity revealed in the background check process that does not fall within the categories of disqualifying crimes described in the adoption and safe families act of 1997 or does not relate directly to child safety, permanence, or well-being; or

.. Delay the issuance of a license or approval of unsupervised access to children by requiring the individual to obtain records relating to a crime or civil infraction revealed in the background check process that does not fall within the categories of disqualifying crimes described in the adoption and safe families act of 1997 or does not relate directly to child safety, permanence, or well-being.

. If the department determines that an individual does not possess the character, suitability, or competence to provide care or have unsupervised access to a child, it must provide the reasons for its decision in writing with copies of the records or documents related to its decision to the individual within ten days of making the decision.

. For purposes of this section, "individual" means a relative as defined in RCW 74.15.020(2)(a), an "other suitable person" under chapter 13.34 RCW, a person pursuing licensing as a foster parent, or a person employed or seeking employment by a business or organization licensed by the department or with whom the department has a contract to provide care, supervision, case management, or treatment of children in the care of the department. "Individual" does not include long-term care workers defined in *RCW 74.39A.009(17)(a) whose background checks are conducted as provided in RCW 74.39A.056.

. The department or its officers, agents, or employees may not be held civilly liable based upon its decision to grant or deny unsupervised access to children if the background information it relied upon at the time the decision was made did not indicate that child safety, permanence, or well-being would be a concern.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6095-S.SL.pdf?cite=2014%20c%2088%20§%204[2014 c 88 § 4]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5565-S.SL.pdf?cite=2013%20c%20162%20§%202[2013 c 162 § 2]; ]

== 74.13.705 - Background checks—Out-of-state requests—Fees.
The department shall charge a fee to process a request made by a person in another state for an individual's child abuse or neglect history in this state or other background history on the individual possessed by the department. All proceeds from the fees collected must go directly to aiding the cost associated with the department conducting background checks.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5565-S.SL.pdf?cite=2013%20c%20162%20§%203[2013 c 162 § 3]; ]

== 74.13.710 - Out-of-home care—Childhood activities—Prudent parent standard.
. For the purposes of this section, "caregiver" means a person with whom a child is placed in out-of-home care, or a designated official for a group care facility licensed by the department.

. This section applies to all caregivers providing for children in out-of-home care.

. Caregivers have the authority to provide or withhold permission without prior approval of the caseworker, department, or court to allow a child in their care to participate in normal childhood activities based on a reasonable and prudent parent standard.

.. Normal childhood activities include, but are not limited to, extracurricular, enrichment, and social activities, and may include overnight activities outside the direct supervision of the caregiver for periods of over twenty-four hours and up to seventy-two hours.

.. The reasonable and prudent parent standard means the standard of care used by a caregiver in determining whether to allow a child in his or her care to participate in extracurricular, enrichment, and social activities. This standard is characterized by careful and thoughtful parental decision making that is intended to maintain a child's health, safety, and best interest while encouraging the child's emotional and developmental growth.

. Any authorization provided under this section must comply with provisions included in an existing safety plan established by the department or court order.

. [Empty]
.. Caseworkers shall discuss the child's interest in and pursuit of normal childhood activities in their monthly health and safety visits and describe the child's participation in normal childhood activities in the individual service and safety plan.

.. Caseworkers shall also review a child's interest in and pursuit of normal childhood activities during monthly meetings with parents. Caseworkers shall communicate the opinions of parents regarding their child's participation in normal childhood activities so that the parents' wishes may be appropriately considered.

. Neither the caregiver nor the department may be held liable for injuries to the child that occur as a result of authority granted in this section unless the action or inaction of the caregiver or the department resulting in injury constitutes willful or wanton misconduct.

. This section does not remove or limit any existing liability protection afforded by law.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6479-S.SL.pdf?cite=2014%20c%20104%20§%201[2014 c 104 § 1]; ]

== 74.13.715 - Family connections program—Report to legislature. (Expires June 30, 2022.)
. Beginning September 1, 2020, the department shall contract with an external organization or organizations with experience serving youth or families receiving out-of-home care services to implement and operate the family connections program, which facilitates interaction between a parent of a child found to be dependent pursuant to chapter 13.34 RCW and in out-of-home care and the individual with whom the child is placed.

. The external organization or organizations contracted to implement and operate the family connections program shall implement and operate the family connections program in one location west of the crest of the Cascade mountains, and one location east of the crest of the Cascade mountains.

. Families may be referred to the family connections program by a caseworker, an attorney, a guardian ad litem as defined in RCW 13.34.030, a parent ally, an office of public defense social worker, or the court.

. After receiving a referral, the family connections program shall determine whether an in-person meeting between a parent of a child found to be dependent pursuant to chapter 13.34 RCW and in out-of-home care and the individual with whom the child is placed is appropriate. If the family connections program determines that such a meeting is appropriate, the family connections program shall then determine whether:

.. The parent of a child found to be dependent pursuant to chapter 13.34 RCW and in out-of-home care and the individual with whom the child is placed are willing to participate in an in-person meeting; and

.. Safety concerns exist such that an in-person meeting should not occur.

. If the family connections program determines that an in-person meeting should occur following the analysis required by subsection (4) of this section, the family connections program shall provide a referral to the family connections program team. The family connections program team shall include a parent ally and an experienced caregiver. After receiving a referral, the family connections program team shall:

.. Ensure that the parent ally contact the parent to prepare for an in-person meeting between the parent and caregiver;

.. Ensure that the experienced caregiver contact the caregiver to prepare for an in-person meeting between the parent and caregiver;

.. Convene an in-person meeting between the parent and caregiver; and

.. Provide ongoing support to the parent and caregiver following the in-person meeting.

. If the family connections program determines that an in-person meeting should not occur following the analysis required under subsection (4) of this section, the family connections program team shall facilitate the exchange of information between the parent and caregiver in an appropriate manner that does not include an in-person meeting. The format of this exchange of information may include written messages, phone calls, or videoconferencing. The family connections program shall routinely reevaluate whether an in-person meeting should occur using the analysis required under subsection (4) of this section.

. The department shall collect data and measure outcomes for families engaging in the family connections program. By September 1, 2021, and in compliance with RCW 43.01.036, the department shall submit a report to the relevant committees of the legislature that details:

.. Data collected for the family connections program;

.. Outcomes for families engaging in the family connections program; and

.. The department's plan on how to expand the family connections program statewide.

. The definitions in this subsection apply throughout this section:

.. "Experienced caregiver" means:

... An individual who is or has received a foster-family home license pursuant to chapter 74.15 RCW or an equivalent license from another state; or

... An individual who cared for a child who was removed from his or her parent pursuant to chapter 13.34 RCW and who has a kin relationship to that child pursuant to RCW 74.13.600.

.. "Parent ally" has the same meaning as provided in RCW 2.70.060.

. This section expires June 30, 2022.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2525-S.SL.pdf?cite=2020%20c%2033%20§%202[2020 c 33 § 2]; ]

== 74.13.720 - Certificates of parental improvement—Issuance—Standards—Rules—Liability. (Effective January 1, 2021.)
. The department shall develop and implement a process by which an individual who is the subject of a founded finding of negligent treatment or maltreatment or physical abuse as defined in RCW 26.44.020 or by rule or an individual whose child was found by a court to be dependent as a result of a finding that the individual abused or neglected their child pursuant to RCW 13.34.030(6)(b) may request the secretary issue a certificate of parental improvement.

. The secretary shall respond to a request for a certificate of parental improvement and notify the requestor of the secretary's determination to issue or deny that request within sixty days of the receipt of a complete request.

. The secretary shall issue a certificate of parental improvement if, on a more probable than not basis, the requestor has the character, suitability, and competence to care for children and meets the other requirements of this section.

. The secretary may not issue a certificate of parental improvement to any individual if:

.. Fewer than five years have passed since the requestor's last founded finding of child abuse or neglect as defined in RCW 26.44.020;

.. Fewer than two years have passed since the secretary's denial of an individual's request for a certificate of parental improvement;

.. The requestor has a final founded finding for sexual abuse, sexual exploitation, or physical abuse if the conduct that was the basis for the physical abuse finding involved cutting, burning, interfering with a child's breathing, shaking a child under three, or threatening a child with a deadly weapon;

.. The requestor has any conviction or pending criminal investigation for:

... Any felony offense involving the physical neglect of a child under chapter 9A.42 RCW;

... Any felony offense under chapter 9A.32 or 9A.36 RCW involving a physical injury or death of a child;

... Any felony domestic violence offense committed against a family or household member as defined in chapter 10.99 RCW;

... A felony offense against a child under chapter 9.68A RCW;

.. Any of the following felony offenses:

(A) Any felony defined under any law as a class A felony or an attempt to commit a class A felony;

(B) Criminal solicitation of or criminal conspiracy to commit a class A felony;

(C) Manslaughter in the first or second degree;

(D) Indecent liberties;

(E) Kidnapping in the second degree;

(F) Arson in the second degree;

(G) Extortion in the first degree;

(H) Robbery in the second degree;

(I) Drive-by shooting; and

(J) Vehicular homicide; or

.. Any out-of-state, federal, or state conviction for a felony offense that is comparable to an offense listed in this subsection (4)(d); or

.. The individual applying for a certificate of parental improvement has already received one certificate of parental improvement and is the alleged perpetrator in a subsequent, final founded finding of child abuse or neglect.

. The secretary shall consider the following when determining whether to issue a certificate of parental improvement:

.. Documentation of any founded finding of child abuse or neglect and the underlying documentation the entity that issued the finding relied upon to make that finding;

.. Findings from any civil adjudication proceeding as defined in RCW 43.43.830;

.. Referral history alleging child abuse or neglect against the requestor;

.. The length of time that has elapsed since the founded finding of child abuse or neglect;

.. Whether a court made a finding that the requestor's child was dependent pursuant to chapter 13.34 RCW, the length of time elapsed since that dependency proceeding was dismissed, and the outcome of the dependency proceeding, including whether the child was returned to the requestor's home;

.. Any documentation submitted by the requestor indicating whether the requestor successfully addressed the circumstances that led to the founded finding of physical abuse or negligent treatment or maltreatment including, but not limited to: A declaration by the requestor signed under penalty of perjury; recent assessments or evaluations of the requestor; and completion or progress toward completion of recommended court-ordered treatment, services, or programs;

.. Any pending criminal or civil actions against the requestor;

.. Background checks as authorized under RCW 10.97.050, 43.43.833, and 43.43.834, and the federal bureau of investigation;

.. Personal and professional references submitted by the requestor from employers, professionals, and agencies familiar with the requestor who can address the requestor's current character;

.. Any education, volunteer work, employment history, or community involvement of the requestor identified by the requestor; and

.. Any additional information the secretary deems relevant.

. However, in deciding whether to grant a request for a certificate of parental improvement under subsection (5) of this section, the secretary must accept the underlying founded finding as valid and may not review the merits of that founded finding.

. The department shall enact rules to implement the process identified in this section.

. Governmental entities, and their officers, agents, employees, and volunteers are not liable in tort for any of their acts or omissions in issuing certificates of parental improvement including, but not limited to, any determination to issue the certificate, or any later act of an individual who received a certificate.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1645-S2.SL.pdf?cite=2020%20c%20270%20§%201[2020 c 270 § 1]; ]

== 74.13.730 - Certificates of parental improvement—Administrative review. (Effective January 1, 2021.)
. A person who applies for a certificate of parental improvement pursuant to RCW 74.13.720 has the right to seek review of the secretary's denial of this certificate request as provided in this section.

. The written notice provided by the department denying a request for a certificate of parental improvement must be sent by mail to the requestor's last known address and include at least the following information in plain language:

.. The reason or reasons for the secretary's denial of a certificate of parental improvement request following a founded finding of physical abuse or negligent treatment or maltreatment; and

.. That the requestor has a right to challenge the secretary's decision not to issue a certificate of parental improvement, including a description of the process for requesting a review of the secretary's decision to deny a request for a certificate of parental improvement.

. Within forty-five calendar days after the department has placed a notice in the mail to the address on the request notifying the requestor that the secretary is denying the request for a certificate of parental improvement pursuant to RCW 74.13.720, the requestor may request that the secretary review this determination. The request for review must be made in writing.

. If a requestor does not request a review as provided in this section, the requestor may not further challenge the secretary's decision not to issue a certificate of parental improvement following a founded finding of physical abuse or negligent treatment or maltreatment.

. Upon receipt of a written request for review, the secretary shall review and, if appropriate, may change the decision and issue a certificate of parental improvement. The secretary may designate the appropriate staff to conduct this review. The review must be completed within thirty days after receiving the written request for review. Upon completion of this review, the department shall notify the requestor in writing of the secretary's determination.

. If the secretary does not alter the decision not to issue a certificate of parental improvement following a child abuse or neglect finding, the requestor may request an adjudicative hearing to contest this decision. The adjudicative proceeding is governed by the administrative procedure act, chapter 34.05 RCW, and this section. The request for an adjudicative proceeding must be filed within forty-five calendar days of the date that the department placed the agency review determination in the mail to the address on the request. If a timely request for an adjudicative proceeding is not made as provided in this section, the requestor may not further challenge the secretary's decision and has no right to review by the secretary, an adjudicative hearing, or judicial review of the determination not to issue a certificate of parental improvement.

. Reviews and hearings conducted under this section are confidential and are not open to the public. Information about reports, reviews, and hearings may be disclosed only in accordance with federal and state laws pertaining to child welfare records and child protective services reports.

. The secretary shall establish procedures for reviewing requests for certificates of parental improvement and requests to alter the decision to deny a request for a certificate of parental improvement by administrative rule, including by emergency rule making if necessary. The secretary may adopt additional rules to implement this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1645-S2.SL.pdf?cite=2020%20c%20270%20§%202[2020 c 270 § 2]; ]

== 74.13.802 - Child welfare housing assistance pilot program. (Expires June 30, 2022.)
. Beginning July 1, 2020, the department shall establish a child welfare housing assistance pilot program, which provides housing vouchers, rental assistance, navigation, and other support services to eligible families.

.. The department shall operate or contract for the operation of the child welfare housing assistance pilot program under subsection (3) of this section in one county west of the crest of the Cascade mountain range and one county east of the crest of the Cascade mountain range.

.. The child welfare housing assistance pilot program is intended to shorten the time that children remain in out-of-home care.

. A parent with a child who is dependent pursuant to chapter 13.34 RCW and whose primary remaining barrier to reunification is the lack of appropriate housing is eligible for the child welfare housing assistance pilot program.

. The department shall contract with an outside entity or entities to operate the child welfare housing assistance pilot program. If no outside entity or entities are available to operate the program or specific parts of the program, the department may operate the program or the specific parts that are not operated by an outside entity.

. Families may be referred to the child welfare housing assistance pilot program by a caseworker, an attorney, a guardian ad litem as defined in chapter 13.34 RCW, a parent ally as defined in RCW 2.70.060, an office of public defense social worker, or the court.

. The department shall consult with a stakeholder group that must include, but is not limited to, the following:

.. Parent allies;

.. Parent attorneys and social workers managed by the office of public defense parent representation program;

.. The department of commerce;

.. Housing experts;

.. Community-based organizations;

.. Advocates; and

.. Behavioral health providers.

. The stakeholder group established in subsection (5) of this section shall begin meeting after July 28, 2019, and assist the department in design of the child welfare housing assistance pilot program in areas including, but not limited to:

.. Equitable racial, geographic, ethnic, and gender distribution of program support;

.. Eligibility criteria;

.. Creating a definition of homeless for purposes of eligibility for the program; and

.. Options for program design that include outside entities operating the entire program or specific parts of the program.

. By December 1, 2021, the department shall report outcomes for the child welfare housing assistance pilot program to the oversight board for children, youth, and families established pursuant to RCW 43.216.015. The report must include racial, geographic, ethnic, and gender distribution of program support.

. The child welfare housing assistance pilot program established in this section is subject to the availability of funds appropriated for this purpose.

. This section expires June 30, 2022.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2525-S.SL.pdf?cite=2020%20c%2033%20§%207[2020 c 33 § 7]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5718-S2.SL.pdf?cite=2019%20c%20328%20§%201[2019 c 328 § 1]; ]

== 74.13.901 - Construction—Chapter applicable to state registered domestic partnerships—2009 c 521.
For the purposes of this chapter, the terms spouse, marriage, marital, husband, wife, widow, widower, next of kin, and family shall be interpreted as applying equally to state registered domestic partnerships or individuals in state registered domestic partnerships as well as to marital relationships and married persons, and references to dissolution of marriage shall apply equally to state registered domestic partnerships that have been terminated, dissolved, or invalidated, to the extent that such interpretation does not conflict with federal law. Where necessary to implement chapter 521, Laws of 2009, gender-specific terms such as husband and wife used in any statute, rule, or other law shall be construed to be gender neutral, and applicable to individuals in state registered domestic partnerships. Nothing in chapter 521, Laws of 2009 shall be construed as creating or requiring the creation of any medical assistance program, as that term is defined in RCW 74.09.010, for state registered domestic partners that is analogous to federal medical assistance programs extended to married persons.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%20177[2009 c 521 § 177]; ]

== 74.13.902 - Construction—Religious or nonprofit organizations.
Nothing contained in chapter 3, Laws of 2012 shall be construed to alter or affect existing law regarding the manner in which a religious or nonprofit organization may be licensed to and provide adoption, foster care, or other child-placing services under this chapter or chapter 74.15 or 26.33 RCW.

[ 2012 c 3 § 15 (Referendum Measure No. 74, approved November 6, 2012); ]

== 74.13.903 - Construction—Prevention services.
Nothing in this chapter may be construed to limit the department's authority to offer or provide prevention services or primary prevention services as defined in chapter 13.34 RCW and this chapter, respectively.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1900.SL.pdf?cite=2019%20c%20172%20§%2018[2019 c 172 § 18]; ]

