= 74.20 - Support of dependent children.
:toc:

== 74.20.010 - Purpose—Legislative intent—Chapter to be liberally construed.
It is the responsibility of the state of Washington through the state department of social and health services to conserve the expenditure of public assistance funds, whenever possible, in order that such funds shall not be expended if there are private funds available or which can be made available by judicial process or otherwise to partially or completely meet the financial needs of the children of this state. The failure of parents to provide adequate financial support and care for their children is a major cause of financial dependency and a contributing cause of social delinquency.

The purpose of this chapter is to provide the state of Washington, through the department of social and health services, a more effective and efficient way to effect the support of dependent children by the person or persons who, under the law, are primarily responsible for such support and to lighten the heavy burden of the taxpayer, who in many instances is paying toward the support of dependent children while those persons primarily responsible are avoiding their obligations. It is the intention of the legislature that the powers delegated to the said department in this chapter be liberally construed to the end that persons legally responsible for the care and support of children within the state be required to assume their legal obligations in order to reduce the financial cost to the state of Washington in providing public assistance funds for the care of children. It is the intention of the legislature that the department provide sufficient staff to carry out the purposes of this chapter, chapter 74.20A RCW, the abandonment and nonsupport statutes, and any applicable federal support enforcement statute administered by the department. It is also the intent of the legislature that the staff responsible for support enforcement be encouraged to conduct their support enforcement duties with fairness, courtesy, and the highest professional standards.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c171.pdf?cite=1979%20ex.s.%20c%20171%20§%2024[1979 ex.s. c 171 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20364[1979 c 141 § 364]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c206.pdf?cite=1963%20c%20206%20§%201[1963 c 206 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c322.pdf?cite=1959%20c%20322%20§%202[1959 c 322 § 2]; ]

== 74.20.021 - Definitions.
See RCW 74.20A.020.

[ ]

== 74.20.040 - Duty of department to enforce child support—Requests for support enforcement services—Schedule of fees—Waiver—Rules.
. Whenever the department receives an application for public assistance on behalf of a child, the department shall take appropriate action under the provisions of this chapter, chapter 74.20A RCW, or other appropriate statutes of this state to establish or enforce support obligations against the parent or other persons owing a duty to pay support moneys.

. The secretary may accept a request for support enforcement services on behalf of persons who are not recipients of public assistance and may take appropriate action to establish or enforce support obligations against the parent or other persons owing a duty to pay moneys. The secretary may condition requests accepted under this subsection upon the payment of a fee as required by subsection (6) of this section or through regulation issued by the secretary. The secretary may establish[,] by regulation, reasonable standards and qualifications for support enforcement services provided to persons who are not currently receiving public assistance.

. The secretary may accept requests for support enforcement services from child support enforcement agencies in other states operating child support programs under Title IV-D of the social security act or from foreign countries, and may take appropriate action to establish and enforce support obligations, or to enforce subpoenas, information requests, orders for genetic testing, and collection actions issued by the other agency against the parent or other person owing a duty to pay support moneys, the parent or other person's employer, or any other person or entity properly subject to child support collection or information-gathering processes. The request shall contain and be accompanied by such information and documentation as the secretary may by rule require, and be signed by an authorized representative of the agency. The secretary may adopt rules setting forth the duration and nature of services provided under this subsection.

. The department may take action to establish, enforce, and collect a support obligation, including performing related services, under this chapter and chapter 74.20A RCW, or through the attorney general or prosecuting attorney for action under chapter 26.09, 26.18, 26.20, 26.21A, 26.26A, or 26.26B RCW or other appropriate statutes or the common law of this state.

. Whenever a support order is filed with the Washington state support registry under chapter 26.23 RCW, the department may take appropriate action under the provisions of this chapter, chapter 26.23 or 74.20A RCW, or other appropriate law of this state to establish or enforce the support obligations contained in that order against the responsible parent or other persons owing a duty to pay support moneys.

. [Empty]
.. Effective October 1, 2019, the secretary shall impose an annual fee of thirty-five dollars for each case in which support enforcement services are furnished where:

... The person entitled to receive support has never received assistance under the temporary assistance for needy families program, the aid for dependent families and children program, or a tribal temporary assistance for needy families program; and

... The state has collected at least five hundred fifty dollars of support.

.. The annual fee shall be retained by the state from support collected on behalf of the person entitled to receive support, but not from the first five hundred fifty dollars of support.

.. The secretary may, on showing of necessity, waive or defer any such fee or cost.

. Fees, due and owing, may be retained from support payments directly or collected as delinquent support moneys utilizing any of the remedies in this chapter, chapter 74.20A or 26.21A RCW, or any other remedy at law or equity available to the department or any agencies with whom it has a cooperative or contractual arrangement to establish, enforce, or collect support moneys or support obligations.

. The secretary may waive the fee, or any portion thereof, as a part of a compromise of disputed claims or may grant partial or total charge off of said fee if the secretary finds there are no available, practical, or lawful means by which said fee may be collected or to facilitate payment of the amount of delinquent support moneys or fees owed.

. The secretary shall adopt rules conforming to federal laws, including but not limited to complying with section 7310 of the federal deficit reduction act of 2005, 42 U.S.C. Sec. 654, and rules and regulations required to be observed in maintaining the state child support enforcement program required under Title IV-D of the federal social security act. The adoption of these rules shall be calculated to promote the cost-effective use of the agency's resources and not otherwise cause the agency to divert its resources from its essential functions.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1916-S.SL.pdf?cite=2019%20c%20275%20§%204[2019 c 275 § 4]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5333-S.SL.pdf?cite=2019%20c%2046%20§%205046[2019 c 46 § 5046]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2828-S.SL.pdf?cite=2012%201st%20sp.s.%20c%204%20§%201[2012 1st sp.s. c 4 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5921-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2042%20§%209[2011 1st sp.s. c 42 § 9]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5244-S.SL.pdf?cite=2007%20c%20143%20§%205[2007 c 143 § 5]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3901.SL.pdf?cite=1997%20c%2058%20§%20891[1997 c 58 § 891]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c360.pdf?cite=1989%20c%20360%20§%2012[1989 c 360 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c276.pdf?cite=1985%20c%20276%20§%201[1985 c 276 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c260.pdf?cite=1984%20c%20260%20§%2029[1984 c 260 § 29]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c201.pdf?cite=1982%20c%20201%20§%2020[1982 c 201 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c183.pdf?cite=1973%201st%20ex.s.%20c%20183%20§%201[1973 1st ex.s. c 183 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c213.pdf?cite=1971%20ex.s.%20c%20213%20§%201[1971 ex.s. c 213 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c206.pdf?cite=1963%20c%20206%20§%203[1963 c 206 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c322.pdf?cite=1959%20c%20322%20§%205[1959 c 322 § 5]; ]

== 74.20.045 - Employment status—Self-employed individuals—Enforcement.
The office of support enforcement shall, as a matter of policy, use all available remedies for the enforcement of support obligations where the obligor is a self-employed individual. The office of support enforcement shall not discriminate in favor of certain obligors based upon employment status.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2798-S2.SL.pdf?cite=1994%20c%20299%20§%2016[1994 c 299 § 16]; ]

== 74.20.055 - Designated agency under federal law—Role of prosecuting attorneys.
The department of social and health services office of support enforcement is the designated agency in Washington state to administer the child support program under Title IV-D of the federal social security act and is responsible for providing necessary and mandated support enforcement services and ensuring that such services are available statewide. It is the intent of the legislature to enhance the total child support program in this state by granting the office of support enforcement administrative powers and flexibility. If the exercise of this authority is used to supplant or replace the role of the prosecuting attorneys for reasons other than economy or federal compliance, the Washington association of prosecuting attorneys shall report to the committees on judiciary of the senate and house of representatives.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c276.pdf?cite=1985%20c%20276%20§%2017[1985 c 276 § 17]; ]

== 74.20.057 - Adjudicative proceedings—Role of department.
When the department appears or participates in an adjudicative proceeding under chapter 26.23 or 74.20A RCW it shall:

. Act in furtherance of the state's financial interest in the matter;

. Act in the best interests of the children of the state;

. Facilitate the resolution of the controversy; and

. Make independent recommendations to ensure the integrity and proper application of the law and process.

In the proceedings the department does not act on behalf or as an agent or representative of an individual.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2488-S.SL.pdf?cite=1994%20c%20230%20§%2018[1994 c 230 § 18]; ]

== 74.20.060 - Cooperation by person having custody of child—Penalty.
Any person having the care, custody or control of any dependent child or children who shall fail or refuse to cooperate with the department of social and health services, any prosecuting attorney or the attorney general in the course of administration of provisions of this chapter shall be guilty of a misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20365[1979 c 141 § 365]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c322.pdf?cite=1959%20c%20322%20§%207[1959 c 322 § 7]; ]

== 74.20.065 - Wrongful deprivation of custody—Legal custodian excused from support payments.
If the legal custodian has been wrongfully deprived of physical custody, the department is authorized to excuse the custodian from support payments for a child or children receiving or on whose behalf public assistance was provided under chapter 74.12 RCW, or for a child or children on behalf of whom the department is providing nonassistance support enforcement services.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5369-S.SL.pdf?cite=2002%20c%20199%20§%204[2002 c 199 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c41.pdf?cite=1983%201st%20ex.s.%20c%2041%20§%2031[1983 1st ex.s. c 41 § 31]; ]

== 74.20.101 - Payment of support moneys to state support registry—Notice—Effects of noncompliance.
. A responsible parent shall make all support payments through the office of support enforcement or the Washington state support registry if:

.. The parent's support order contains a provision directing the parent to make support payments through the office of support enforcement or the Washington state support registry; or

.. If the parent has received written notice from the office of support enforcement under RCW 26.23.110, 74.20A.040, or 74.20A.055 that all future support payments must be made through the office of support enforcement or the Washington state support registry.

. A responsible parent who has been ordered or notified to make support payments to the office of support enforcement or the Washington state support registry shall not receive credit for payments which are not paid to the office of support enforcement or the Washington state support registry unless:

.. The department determines that the granting of credit would not prejudice the rights of the residential parent or other person or agency entitled to receive the support payments and circumstances of an equitable nature exist; or

.. A court, after a hearing at which all interested parties were given an opportunity to be heard, on equitable principles, orders that credit be given.

. The rights of the payee under an order for support shall not be prejudiced if the department grants credit under subsection (2)(a) of this section. If the department determines that credit should be granted pursuant to subsection (2) of this section, the department shall mail notice of its decision to the last known address of the payee, together with information about the procedure to contest the determination.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c360.pdf?cite=1989%20c%20360%20§%207[1989 c 360 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c435.pdf?cite=1987%20c%20435%20§%2030[1987 c 435 § 30]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c171.pdf?cite=1979%20ex.s.%20c%20171%20§%2013[1979 ex.s. c 171 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c183.pdf?cite=1973%201st%20ex.s.%20c%20183%20§%202[1973 1st ex.s. c 183 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c173.pdf?cite=1969%20ex.s.%20c%20173%20§%2016[1969 ex.s. c 173 § 16]; ]

== 74.20.160 - Department may disclose information to internal revenue department.
Notwithstanding the provisions of RCW 74.04.060, upon approval of the department of health, education and welfare of the federal government, the department of social and health services may disclose to and keep the internal revenue department of the treasury of the United States advised of the names of all persons who are under legal obligation to support any dependent child or children and who are not doing so, to the end that the internal revenue department may have available to it the names of such persons for review in connection with income tax returns and claims of dependencies made by persons filing income tax returns.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20366[1979 c 141 § 366]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c206.pdf?cite=1963%20c%20206%20§%205[1963 c 206 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c322.pdf?cite=1959%20c%20322%20§%2017[1959 c 322 § 17]; ]

== 74.20.210 - Attorney general may act under Uniform Reciprocal Enforcement of Support Act pursuant to agreement with prosecuting attorney.
The prosecuting attorney of any county except a county with a population of one million or more may enter into an agreement with the attorney general whereby the duty to initiate petitions for support authorized under the provisions of *chapter 26.21 RCW as it is now or hereafter amended (**Uniform Reciprocal Enforcement of Support Act) in cases where the petitioner has applied for or is receiving public assistance on behalf of a dependent child or children shall become the duty of the attorney general. Any such agreement may also provide that the attorney general has the duty to represent the petitioner in intercounty proceedings within the state initiated by the attorney general which involve a petition received from another county. Upon the execution of such agreement, the attorney general shall be empowered to exercise any and all powers of the prosecuting attorney in connection with said petitions.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1201-S.SL.pdf?cite=1991%20c%20363%20§%20150[1991 c 363 § 150]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c173.pdf?cite=1969%20ex.s.%20c%20173%20§%2014[1969 ex.s. c 173 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c206.pdf?cite=1963%20c%20206%20§%206[1963 c 206 § 6]; ]

== 74.20.220 - Powers of department through the attorney general or prosecuting attorney.
In order to carry out its responsibilities imposed under this chapter and as required by federal law, the state department of social and health services, through the attorney general or prosecuting attorney, is hereby authorized to:

. Initiate an action in superior court to obtain a support order or obtain other relief related to support for a dependent child on whose behalf the department is providing public assistance or support enforcement services under RCW 74.20.040, or to enforce a superior court order.

. Appear as a party in dissolution, child support, parentage, maintenance suits, or other proceedings, for the purpose of representing the financial interest and actions of the state of Washington therein.

. Petition the court for modification of a superior court order when the office of support enforcement is providing support enforcement services under RCW 74.20.040.

. When the attorney general or prosecuting attorney appears in, defends, or initiates actions to establish, modify, or enforce child support obligations he or she represents the state, the best interests of the child relating to parentage, and the best interests of the children of the state, but does not represent the interests of any other individual.

. If public assistance has been applied for or granted on behalf of a child of parents who are divorced or legally separated, the attorney general or prosecuting attorney may apply to the superior court in such action for an order directing either parent or both to show cause:

.. Why an order of support for the child should not be entered, or

.. Why the amount of support previously ordered should not be increased, or

.. Why the parent should not be held in contempt for his or her failure to comply with any order of support previously entered.

. Initiate any civil proceedings deemed necessary by the department to secure reimbursement from the parent or parents of minor dependent children for all moneys expended by the state in providing assistance or services to said children.

. Nothing in this section limits the authority of the attorney general or prosecuting attorney to use any and all civil and criminal remedies to enforce, establish, or modify child support obligations whether or not the custodial parent receives public assistance.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5120-S2.SL.pdf?cite=1991%20c%20367%20§%2044[1991 c 367 § 44]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20367[1979 c 141 § 367]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c154.pdf?cite=1973%201st%20ex.s.%20c%20154%20§%20112[1973 1st ex.s. c 154 § 112]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c173.pdf?cite=1969%20ex.s.%20c%20173%20§%2015[1969 ex.s. c 173 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c206.pdf?cite=1963%20c%20206%20§%207[1963 c 206 § 7]; ]

== 74.20.225 - Subpoena authority—Enforcement.
In carrying out the provisions of this chapter or chapters 26.18, 26.23, 26.26A, 26.26B, and 74.20A RCW, the secretary and other duly authorized officers of the department may subpoena witnesses, take testimony, and compel the production of such papers, books, records, and documents as they may deem relevant to the performance of their duties. The division of child support may enforce subpoenas issued under this power according to RCW 74.20A.350.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5333-S.SL.pdf?cite=2019%20c%2046%20§%205047[2019 c 46 § 5047]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3901.SL.pdf?cite=1997%20c%2058%20§%20898[1997 c 58 § 898]; ]

== 74.20.230 - Petition for support order by married parent with minor children who are receiving public assistance.
Any married parent with minor children, natural or legally adopted children who is receiving public assistance may apply to the superior court of the county in which such parent resides or in which the spouse may be found for an order upon such spouse, if such spouse is the natural or adoptive mother or father of such children, to provide for such spouse's support and the support of such spouse's minor children by filing in such county a petition setting forth the facts and circumstances upon which such spouse relies for such order. If it appears to the satisfaction of the court that such parent is without funds to employ counsel, the state department of social and health services through the attorney general may file such petition on behalf of such parent. If satisfied that a just cause exists, the court shall direct that a citation issue to the other spouse requiring such spouse to appear at a time set by the court to show cause why an order of support should not be entered in the matter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c154.pdf?cite=1973%201st%20ex.s.%20c%20154%20§%20113[1973 1st ex.s. c 154 § 113]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c206.pdf?cite=1963%20c%20206%20§%208[1963 c 206 § 8]; ]

== 74.20.240 - Petition for support order by married parent with minor children who are receiving public assistance—Order—Powers of court.
. After the hearing of the petition for an order of support the court shall make an order granting or denying it and fixing, if allowed, the terms and amount of the support. (2) The court has the same power to compel the attendance of witnesses and the production of testimony as in actions and suits, to make such decree or orders as are equitable in view of the circumstances of both parties and to punish violations thereof as other contempts are punished.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c206.pdf?cite=1963%20c%20206%20§%209[1963 c 206 § 9]; ]

== 74.20.250 - Petition for support order by married parent with minor children who are receiving public assistance—Waiver of filing fees.
The court may, upon satisfactory showing that the petitioner is without funds to pay the filing fee, order that the petition and other papers be filed without payment of the fee.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c206.pdf?cite=1963%20c%20206%20§%2010[1963 c 206 § 10]; ]

== 74.20.260 - Financial statements by parent whose absence is basis of application for public assistance.
Any parent in the state whose absence is the basis upon which an application is filed for public assistance on behalf of a child shall be required to complete a statement, under oath, of his or her current monthly income, his or her total income over the past twelve months, the number of dependents for whom he or she is providing support, the amount he or she is contributing regularly toward the support of all children for whom application for such assistance is made, his or her current monthly living expenses, and such other information as is pertinent to determining his or her ability to support his or her children. Such statement shall be provided upon demand made by the state department of social and health services or attorney general, and if assistance based upon such application is granted on behalf of such child, additional statements shall be filed annually thereafter with the state department of social and health services until such time as the child is no longer receiving such assistance. Failure to comply with this section shall constitute a misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20214[2013 c 23 § 214]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20368[1979 c 141 § 368]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c206.pdf?cite=1963%20c%20206%20§%2011[1963 c 206 § 11]; ]

== 74.20.280 - Central unit for information and administration—Cooperation enjoined—Availability of records.
The department is authorized and directed to establish a central unit to serve as a registry for the receipt of information, for answering interstate inquiries concerning the parents of dependent children, to coordinate and supervise departmental activities in relation to such parents, to assure effective cooperation with law enforcement agencies, and to perform other functions authorized by state and federal support enforcement and child custody statutes and regulations.

To effectuate the purposes of this section, the secretary may request from state, county and local agencies all information and assistance as authorized by this chapter. Upon the request of the department of social and health services, all state, county and city agencies, officers and employees shall cooperate in the location of the parents of a dependent child and shall supply the department with all information relative to the location, income and property of such parents, notwithstanding any provision of law making such information confidential.

Any records established pursuant to the provisions of this section shall be available only to the attorney general, prosecuting attorneys, courts having jurisdiction in support and/or abandonment proceedings or actions, or other authorized agencies or persons for use consistent with the intent of state and federal support enforcement and child custody statutes and regulations.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c41.pdf?cite=1983%201st%20ex.s.%20c%2041%20§%2015[1983 1st ex.s. c 41 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20370[1979 c 141 § 370]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c206.pdf?cite=1963%20c%20206%20§%2013[1963 c 206 § 13]; ]

== 74.20.300 - Department exempt from fees relating to paternity or support.
No filing or recording fees, court fees, or fees for making copies of documents shall be required from the state department of social and health services by any county clerk, county auditor, or other county officer for the filing of any actions or documents necessary to establish paternity or enforce or collect support moneys.

Filing fees shall also not be required of any prosecuting attorney or the attorney general for action to establish paternity or enforce or collect support moneys.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c171.pdf?cite=1979%20ex.s.%20c%20171%20§%201[1979 ex.s. c 171 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c183.pdf?cite=1973%201st%20ex.s.%20c%20183%20§%203[1973 1st ex.s. c 183 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c206.pdf?cite=1963%20c%20206%20§%2015[1963 c 206 § 15]; ]

== 74.20.310 - Guardian ad litem in actions brought to determine parent and child relationship—Notice.
. The provisions of RCW 26.26A.485 requiring appointment of a guardian ad litem to represent the child in an action brought to determine the parent and child relationship do not apply to actions brought under chapter 26.26A or 26.26B RCW if:

.. The action is brought by the attorney general on behalf of the department of social and health services and the child; or

.. The action is brought by any prosecuting attorney on behalf of the state and the child when referral has been made to the prosecuting attorney by the department of social and health services requesting such action.

. On the issue of parentage, the attorney general or prosecuting attorney functions as the child's guardian ad litem provided the interests of the state and the child are not in conflict.

. The court, on its own motion or on motion of a party, may appoint a guardian ad litem when necessary.

. The summons shall contain a notice to the parents that pursuant to RCW 26.26A.485 the parents have a right to move the court for a guardian ad litem for the child other than the prosecuting attorney or the attorney general subject to subsection (2) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5333-S.SL.pdf?cite=2019%20c%2046%20§%205048[2019 c 46 § 5048]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2346-S2.SL.pdf?cite=2002%20c%20302%20§%20705[2002 c 302 § 705]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5120-S2.SL.pdf?cite=1991%20c%20367%20§%2045[1991 c 367 § 45]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c171.pdf?cite=1979%20ex.s.%20c%20171%20§%2015[1979 ex.s. c 171 § 15]; ]

== 74.20.320 - Custodian to remit support moneys when department has support obligation—Noncompliance.
Whenever a custodian of children, or other person, receives support moneys paid to them which moneys are paid in whole or in part in satisfaction of a support obligation which has been assigned to the department pursuant to Title IV-A of the federal social security act as amended by the personal responsibility and work opportunity reconciliation act of 1996 or RCW 74.20.330 or to which the department is owed a debt pursuant to RCW 74.20A.030, the moneys shall be remitted to the department within eight days of receipt by the custodian or other person. If not so remitted the custodian or other person shall be indebted to the department as a support debt in an amount equal to the amount of the support money received and not remitted.

By not paying over the moneys to the department, a custodial parent or other person is deemed, without the necessity of signing any document, to have made an irrevocable assignment to the department of any support delinquency owed which is not already assigned to the department or to any support delinquency which may accrue in the future in an amount equal to the amount of support money retained. The department may utilize the collection procedures in chapter 74.20A RCW to collect the assigned delinquency to effect recoupment and satisfaction of the debt incurred by reason of the failure of the custodial parent or other person to remit. The department is also authorized to make a set-off to effect satisfaction of the debt by deduction from support moneys in its possession or in the possession of any clerk of the court or other forwarding agent which are paid to the custodial parent or other person for the satisfaction of any support delinquency. Nothing in this section authorizes the department to make set-off as to current support paid during the month for which the payment is due and owing.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3901.SL.pdf?cite=1997%20c%2058%20§%20935[1997 c 58 § 935]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c171.pdf?cite=1979%20ex.s.%20c%20171%20§%2017[1979 ex.s. c 171 § 17]; ]

== 74.20.330 - Payment of public assistance as assignment of rights to support.
. Whenever public assistance is paid under a state program funded under Title IV-A of the federal social security act as amended by the personal responsibility and work opportunity reconciliation act of 1996, and the federal deficit reduction act of 2005, each applicant or recipient is deemed to have made assignment to the department of any rights to a support obligation from any other person the applicant or recipient may have in his or her own behalf or in behalf of any other family member for whom the applicant or recipient is applying for or receiving public assistance, including any unpaid support obligation or support debt which has accrued at the time the assignment is made.

. Payment of public assistance under a state-funded program, or a program funded under Title IV-A, IV-E, or XIX of the federal social security act as amended by the personal responsibility and work opportunity reconciliation act of 1996 shall:

.. Operate as an assignment by operation of law; and

.. Constitute an authorization to the department to provide the assistance recipient with support enforcement services.

. Effective October 1, 2008, whenever public assistance is paid under a state program funded under Title IV-A of the federal social security act as amended by the personal responsibility and work opportunity reconciliation act of 1996, and the federal deficit reduction act of 2005, a member of the family is deemed to have made an assignment to the state any right the family member may have, or on behalf of the family member receiving such assistance, to support from any other person, not exceeding the total amount of assistance paid to the family, which accrues during the period that the family receives assistance under the program.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2828-S.SL.pdf?cite=2012%201st%20sp.s.%20c%204%20§%202[2012 1st sp.s. c 4 § 2]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5921-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2042%20§%2010[2011 1st sp.s. c 42 § 10]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5244-S.SL.pdf?cite=2007%20c%20143%20§%206[2007 c 143 § 6]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2579.SL.pdf?cite=2000%20c%2086%20§%206[2000 c 86 § 6]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3901.SL.pdf?cite=1997%20c%2058%20§%20936[1997 c 58 § 936]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c360.pdf?cite=1989%20c%20360%20§%2013[1989 c 360 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c275.pdf?cite=1988%20c%20275%20§%2019[1988 c 275 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c276.pdf?cite=1985%20c%20276%20§%203[1985 c 276 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c171.pdf?cite=1979%20ex.s.%20c%20171%20§%2022[1979 ex.s. c 171 § 22]; ]

== 74.20.340 - Employees' case workload standards.
The department shall develop workload standards for each employee classification involved in support enforcement activities for each category of support enforcement cases.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6219.SL.pdf?cite=1998%20c%20245%20§%20150[1998 c 245 § 150]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c171.pdf?cite=1979%20ex.s.%20c%20171%20§%2025[1979 ex.s. c 171 § 25]; ]

== 74.20.350 - Costs and attorneys' fees.
In order to facilitate and ensure compliance with Title IV-D of the federal social security act, now existing or hereafter amended, wherein the state is required to undertake to establish parentage of such children as are born out of wedlock, the secretary of social and health services may pay the reasonable and proper fees of attorneys admitted to practice before the courts of this state, who are engaged in private practice for the purpose of maintaining actions under chapter 26.26A or 26.26B RCW on behalf of such children, to the end that parent and child relationships be determined and financial support obligations be established by superior court order. The secretary or the secretary's designee shall make the determination in each case as to which cases shall be referred for representation by such private attorneys. The secretary may advance, pay, or reimburse for payment of, such reasonable costs as may be attendant to an action under chapter 26.26A or 26.26B RCW. The representation by a private attorney shall be only on behalf of the subject child, the custodial natural parent, and the child's personal representative or guardian ad litem, and shall not in any manner be, or be construed to be, in representation of the department of social and health services or the state of Washington, such representation being restricted to that provided pursuant to chapters 43.10 and 36.27 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5333-S.SL.pdf?cite=2019%20c%2046%20§%205049[2019 c 46 § 5049]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c171.pdf?cite=1979%20ex.s.%20c%20171%20§%2019[1979 ex.s. c 171 § 19]; ]

== 74.20.360 - Orders for genetic testing.
. The division of child support may issue an order for genetic testing when providing services under this chapter and Title IV-D of the federal social security act if genetic testing:

.. Is appropriate in an action under chapter 26.26A RCW, the uniform parentage act;

.. Is appropriate in an action to establish support under RCW 74.20A.056; or

.. Would assist the parties or the division of child support in determining whether it is appropriate to proceed with an action to establish or disestablish parentage.

. The order for genetic testing shall be served on the alleged genetic parent or parents and the legal parent by personal service or by any form of mail requiring a return receipt.

. Within twenty days of the date of service of an order for genetic testing, any party required to appear for genetic testing, the child, or a guardian on the child's behalf, may petition in superior court under chapter 26.26A RCW to bar or postpone genetic testing.

. The order for genetic testing shall contain:

.. An explanation of the right to proceed in superior court under subsection (3) of this section;

.. Notice that if no one proceeds under subsection (3) of this section, the agency issuing the order will schedule genetic testing and will notify the parties of the time and place of testing by regular mail;

.. Notice that the parties must keep the agency issuing the order for genetic testing informed of their residence address and that mailing a notice of time and place for genetic testing to the last known address of the parties by regular mail constitutes valid service of the notice of time and place;

.. Notice that the order for genetic testing may be enforced through:

... Public assistance grant reduction for noncooperation, pursuant to agency rule, if the child and custodian are receiving public assistance;

... Termination of support enforcement services under Title IV-D of the federal social security act if the child and custodian are not receiving public assistance;

... A referral to superior court for an appropriate action under chapter 26.26A RCW; or

... A referral to superior court for remedial sanctions under RCW 7.21.060.

. The department may advance the costs of genetic testing under this section.

. If an action is pending under chapter 26.26A RCW, a judgment for reimbursement of the cost of genetic testing may be awarded under RCW 26.26A.330.

. If no action is pending in superior court, the department may impose an obligation to reimburse costs of genetic testing according to rules adopted by the department to implement RCW 74.20A.056.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5333-S.SL.pdf?cite=2019%20c%2046%20§%205050[2019 c 46 § 5050]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2346-S2.SL.pdf?cite=2002%20c%20302%20§%20706[2002 c 302 § 706]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3901.SL.pdf?cite=1997%20c%2058%20§%20901[1997 c 58 § 901]; ]

== 74.20.901 - Construction—Chapter applicable to state registered domestic partnerships—2009 c 521.
For the purposes of this chapter, the terms spouse, marriage, marital, husband, wife, widow, widower, next of kin, and family shall be interpreted as applying equally to state registered domestic partnerships or individuals in state registered domestic partnerships as well as to marital relationships and married persons, and references to dissolution of marriage shall apply equally to state registered domestic partnerships that have been terminated, dissolved, or invalidated, to the extent that such interpretation does not conflict with federal law. Where necessary to implement chapter 521, Laws of 2009, gender-specific terms such as husband and wife used in any statute, rule, or other law shall be construed to be gender neutral, and applicable to individuals in state registered domestic partnerships.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%20179[2009 c 521 § 179]; ]

