= 74.25 - Job opportunities and basic skills training program.
:toc:

== 74.25.040 - Volunteer work—Child care or other work—Training.
. Recipients of temporary assistance for needy families who are employed or participating in a work activity under *section 312 of this act may volunteer or work in a licensed child care facility. Licensed child care facilities participating in this effort shall provide care for the recipient's children and provide for the development of positive child care skills.

. The department shall train two hundred fifty recipients of temporary assistance for needy families to become family child care providers or child care center teachers. The department shall offer the training in rural and urban communities. The department shall adopt rules to implement the child care training program in this section.

. Recipients trained under this section shall provide child care services to clients of the department for two years following the completion of their child care training.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1089-S.SL.pdf?cite=1997%20c%2059%20§%2030[1997 c 59 § 30]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3901.SL.pdf?cite=1997%20c%2058%20§%20405[1997 c 58 § 405]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2798-S2.SL.pdf?cite=1994%20c%20299%20§%208[1994 c 299 § 8]; ]

