= 74.39 - Long-term care service options.
:toc:

== 74.39.001 - Finding.
The legislature finds that:

Washington's chronically functionally disabled population is growing at a rapid pace. This growth, along with economic and social changes and the coming age wave, presents opportunities for the development of long-term care community services networks and enhanced volunteer participation in those networks, and creates a need for different approaches to currently fragmented long-term care programs. The legislature further recognizes that persons with functional disabilities should receive long-term care services that encourage individual dignity, autonomy, and development of their fullest human potential.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c427.pdf?cite=1989%20c%20427%20§%201[1989 c 427 § 1]; ]

== 74.39.005 - Purpose.
The purpose of this chapter is to:

. Establish a balanced range of health, social, and supportive services that deliver long-term care services to persons with chronic functional disabilities of all ages;

. Ensure that functional ability shall be the determining factor in defining long-term care service needs and that these needs will be determined by a uniform system for comprehensively assessing functional disability;

. Ensure that services are provided in the most independent living situation consistent with individual needs;

. Ensure that long-term care service options shall be developed and made available that enable persons with functional disabilities to continue to live in their homes or other community residential facilities while in the care of their families or other volunteer support persons;

. Ensure that long-term care services are coordinated in a way that minimizes administrative cost, eliminates unnecessarily complex organization, minimizes program and service duplication, and maximizes the use of financial resources in directly meeting the needs of persons with functional limitations;

. Develop a systematic plan for the coordination, planning, budgeting, and administration of long-term care services now fragmented between the division of developmental disabilities, division of mental health, aging and adult services administration, division of children and family services, division of vocational rehabilitation, division of health, bureau of alcohol and substance abuse, and the department of health;

. Encourage the development of a statewide long-term care case management system that effectively coordinates the plan of care and services provided to eligible clients;

. Ensure that individuals and organizations affected by or interested in long-term care programs have an opportunity to participate in identification of needs and priorities, policy development, planning, and development, implementation, and monitoring of state supported long-term care programs;

. Support educational institutions in Washington state to assist in the procurement of federal support for expanded research and training in long-term care; and

. Facilitate the development of a coordinated system of long-term care education that is clearly articulated between all levels of higher education and reflective of both in-home care needs and institutional care needs of persons with functional disabilities.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1551-S.SL.pdf?cite=2020%20c%2076%20§%2021[2020 c 76 § 21]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1908-S2.SL.pdf?cite=1995%201st%20sp.s.%20c%2018%20§%2010[1995 1st sp.s. c 18 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c427.pdf?cite=1989%20c%20427%20§%202[1989 c 427 § 2]; ]

== 74.39.007 - Definitions.
The definitions in this section apply throughout RCW 74.39.007, 74.39.050, 74.39.060, 74.39.070, 43.190.060, and section 1, chapter 336, Laws of 1999 unless the context clearly requires otherwise.

. "Self-directed care" means the process in which an adult person, who is prevented by a functional disability from performing a manual function related to health care that an individual would otherwise perform for himself or herself, chooses to direct and supervise a paid personal aide to perform those tasks.

. "Personal aide" means an individual, working privately or as an individual provider under contract or agreement with the department of social and health services, who acts at the direction of an adult person with a functional disability living in his or her own home and provides that person with health care services that a person without a functional disability can perform.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1880-S.SL.pdf?cite=1999%20c%20336%20§%202[1999 c 336 § 2]; ]

== 74.39.010 - Option—Flexibility—Title XIX of the federal social security act.
A valuable option available to Washington state to achieve the goals of RCW 74.39.001 and 74.39.005 is the flexibility in personal care and other long-term care services encouraged by the federal government under Title XIX of the federal social security act. These services include options to expand community-based long-term care services, such as adult family homes, congregate care facilities, respite, chore services, hospice, and case management.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c427.pdf?cite=1989%20c%20427%20§%203[1989 c 427 § 3]; ]

== 74.39.020 - Opportunities—Increase of federal funds—Title XIX of the federal social security act.
Title XIX of the federal social security act offers valuable opportunities to increase federal funds available to provide community-based long-term care services to functionally disabled persons in their homes, and in noninstitutional residential facilities, such as adult family homes and congregate care facilities.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c427.pdf?cite=1989%20c%20427%20§%209[1989 c 427 § 9]; ]

== 74.39.030 - Community options program entry system—Waiver—Respite services.
The department shall request an amendment to its community options program entry system waiver under section 1905(c) of the federal social security act to include respite services as a service available under the waiver.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c427.pdf?cite=1989%20c%20427%20§%2011[1989 c 427 § 11]; ]

== 74.39.041 - Community residential options—Nursing facility eligible clients.
. To the extent of available funds and subject to any conditions placed on appropriations for this purpose, the department may provide one or more home and community-based waiver programs in accordance with section 1915(c) of the federal social security act for Washington residents who have a gross income in excess of three hundred percent of the federal supplemental security income benefit level. The waiver services provided in accordance with this section may differ from, and shall operate with a separate limit or limits on total enrollment than, those provided for persons who are categorically needy as defined in Title XIX of the federal social security act. The department shall adopt rules to establish eligibility criteria, applicable income standards, and the specific waiver services to be provided. Total annual enrollment levels and the services to be provided shall be as specified in the waiver agreement or agreements with the federal government, subject to any conditions on appropriations for this purpose.

. If a nursing facility resident becomes eligible for home and community-based waiver service alternatives to nursing facility care, but chooses to continue to reside in a nursing facility, the department must allow that choice. However, if the resident is a medicaid recipient, the resident must require a nursing facility level of care.

. If a recipient of home and community-based waiver services may continue to receive home and community-based waiver services, despite an otherwise disqualifying level of income, but chooses to seek admission to a nursing facility, the department must allow that choice. However, if the resident is a medicaid recipient, the resident must require a nursing facility level of care.

. The department will fully disclose to all individuals eligible for waiver services under this section the services available in different long-term care settings.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1341-S.SL.pdf?cite=2001%20c%20269%20§%202[2001 c 269 § 2]; ]

== 74.39.050 - Individuals with functional disabilities—Self-directed care.
. An adult person with a functional disability living in his or her own home may direct and supervise a paid personal aide in the performance of a health care task.

. The following requirements shall guide the provision of self-directed care under chapter 336, Laws of 1999:

.. Health care tasks are those medical, nursing, or home health services that enable the person to maintain independence, personal hygiene, and safety in his or her own home, and that are services that a person without a functional disability would customarily and personally perform without the assistance of a licensed health care provider.

.. The individual who chooses to self-direct a health care task is responsible for initiating self-direction by informing the health care professional who has ordered the treatment which involves that task of the individual's intent to perform that task through self-direction.

.. When state funds are used to pay for self-directed tasks, a description of those tasks will be included in the client's comprehensive assessment, and subject to review with each annual reassessment.

.. When a licensed health care provider orders treatment involving a health care task to be performed through self-directed care, the responsibility to ascertain that the patient understands the treatment and will be able to follow through on the self-directed care task is the same as it would be for a patient who performs the health care task for himself or herself, and the licensed health care provider incurs no additional liability when ordering a health care task which is to be performed through self-directed care.

.. The role of the personal aide in self-directed care is limited to performing the physical aspect of health care tasks under the direction of the person for whom the tasks are being done. This shall not affect the ability of a personal aide to provide other home care services, such as personal care or homemaker services, which enable the client to remain at home.

.. The responsibility to initiate self-directed health care tasks, to possess the necessary knowledge and training for those tasks, and to exercise judgment regarding the manner of their performance rests and remains with the person who has chosen to self-direct those tasks, including the decision to employ and dismiss a personal aide.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1880-S.SL.pdf?cite=1999%20c%20336%20§%203[1999 c 336 § 3]; ]

== 74.39.060 - Personal aide providers—Registration.
Any individual who, for compensation, serves as a personal aide provider under contract or agreement with the department of social and health services, to a person who self-directs his or her own care in his or her own home, shall register with the department of social and health services.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1880-S.SL.pdf?cite=1999%20c%20336%20§%204[1999 c 336 § 4]; ]

== 74.39.070 - Personal aide—Qualification exemptions.
A personal aide, in the performance of a health care task, who is directed and supervised by a person with a functional disability in his or her own home, is exempt from any legal requirement to qualify and be credentialed by the department of health as a health care provider under Title 18 RCW to the extent of the responsibilities provided and health care tasks performed under chapter 336, Laws of 1999.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1880-S.SL.pdf?cite=1999%20c%20336%20§%208[1999 c 336 § 8]; ]

