= 74.36 - Funding for community programs for the aging.
:toc:

== 74.36.100 - Department to participate in and administer Federal Older Americans Act of 1965.
The department of social and health services is authorized to take advantage of and participate in the Federal Older Americans Act of 1965 (Public Law 89-73, 89th Congress, 79 Stat. 220) and to accept, administer and disburse any federal funds that may be available under said act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c18.pdf?cite=1970%20ex.s.%20c%2018%20§%2027[1970 ex.s. c 18 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c33.pdf?cite=1967%20ex.s.%20c%2033%20§%201[1967 ex.s. c 33 § 1]; ]

== 74.36.110 - Community programs and projects for the aging—Allotments for—Purpose.
The secretary of the department of social and health services or his or her designee is authorized to allot for such purposes all or a portion of whatever state funds the legislature appropriates or are otherwise made available for the purpose of matching local funds dedicated to community programs and projects for the aging. The purpose of RCW 74.36.110 through 74.36.130 is to stimulate and assist local communities to obtain federal funds made available under the federal older Americans act of 1965 as amended.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20222[2013 c 23 § 222]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c169.pdf?cite=1971%20ex.s.%20c%20169%20§%2010[1971 ex.s. c 169 § 10]; ]

== 74.36.120 - Community programs and projects for the aging—Standards for eligibility and approval—Informal hearing on denial of approval.
. The secretary or his or her designee shall adopt and set forth standards for determining the eligibility and approval of community projects and priorities therefor, and shall have final authority to approve or deny such projects and funding requested under RCW 74.36.110 through 74.36.130.

. Only community project proposals submitted by local public agencies, by private nonprofit agencies or organizations, or by public or other nonprofit institutions of higher education, shall be eligible for approval.

. Any community project applicant whose application for approval is denied will be afforded an opportunity for an informal hearing before the secretary or his or her designee, but the administrative procedure act, chapter 34.05 RCW, shall not apply.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20223[2013 c 23 § 223]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c169.pdf?cite=1971%20ex.s.%20c%20169%20§%2011[1971 ex.s. c 169 § 11]; ]

== 74.36.130 - Community programs and projects for the aging—State funding, limitations—Payments, type.
. State funds made available under RCW 74.36.110 through 74.36.130 for any project shall not exceed fifty per centum of the nonfederal share of the costs. To the extent that federal law permits, and the secretary or his or her designee deems appropriate, the local community share and/or the state share may be in the form of cash or in-kind resources.

. Payments made under RCW 74.36.110 through 74.36.130 may be made in advance or by way of reimbursement, and in such installments and on such conditions as the secretary or his or her designee may determine, including provisions for adequate accounting systems, reasonable record retention periods, and financial audits.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20224[2013 c 23 § 224]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c169.pdf?cite=1971%20ex.s.%20c%20169%20§%2012[1971 ex.s. c 169 § 12]; ]

