= 74.38 - Senior citizens services act.
:toc:

== 74.38.010 - Legislative recognition—Public policy.
The legislature recognizes the need for the development and expansion of alternative services and forms of care for senior citizens. Such services should be designed to restore individuals to, or maintain them at, the level of independent living they are capable of attaining. These alternative services and forms of care should be designed to both complement the present forms of institutional care and create a system whereby appropriate services can be rendered according to the care needs of an individual. The provision of service should continue until the client is able to function independently, moves to an institution, moves from the state, dies, or withdraws from the program.

Therefore, it shall be the policy of this state to develop, expand, or maintain those programs which provide an alternative to institutional care when that form of care is premature, unnecessary, or inappropriate.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c321.pdf?cite=1977%20ex.s.%20c%20321%20§%201[1977 ex.s. c 321 § 1]; 1975-'76 2nd ex.s. c 131 § 1; ]

== 74.38.020 - Definitions.
As used in this chapter, the following words and phrases shall have the following meaning unless the content clearly requires otherwise:

. "Area agency" means an agency, other than a state agency, designated by the department to carry out programs or services approved by the department in a designated geographical area of the state.

. "Area plan" means the document submitted annually by an area agency to the department for approval which sets forth (a) goals and measurable objectives, (b) review of past expenditures and accounting of revenue for the previous year, (c) estimated revenue and expenditures for the ensuing year, and (d) the planning, coordination, administration, social services, and evaluation activities to be undertaken to carry out the purposes of the Older Americans Act of 1965 (42 U.S.C. Sec. 3024 et seq.), as now or hereafter amended.

. "Department" means the department of social and health services.

. "Office" shall mean the office on aging which is the organizational unit within the department responsible for coordinating and administering aging problems.

. "Eligible persons" means senior citizens who are:

.. Sixty-five years of age or more; or

.. Sixty years of age or more and are either (i) nonemployed, or (ii) employed for twenty hours per week or less; and

.. In need of services to enable them to remain in their customary homes because of physical, mental, or other debilitating impairments.

. "Low income" means initial resources or subsequent income at or below forty percent of the state median income as promulgated by the secretary of the United States department of health, education and welfare for Title XX of the Social Security Act, or, in the alternative, a level determined by the department and approved by the legislature.

. "Income" shall have the same meaning as in chapter 74.04 RCW, as now or hereafter amended; except, that money received from RCW 74.38.060 shall be excluded from this definition.

. "Resource" shall have the same meaning as in chapter 74.04 RCW, as now or hereafter amended.

. "Need" shall have the same meaning as in chapter 74.04 RCW, as now or hereafter amended.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c9.pdf?cite=1989%201st%20ex.s.%20c%209%20§%20817[1989 1st ex.s. c 9 § 817]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c321.pdf?cite=1977%20ex.s.%20c%20321%20§%202[1977 ex.s. c 321 § 2]; 1975-'76 2nd ex.s. c 131 § 2; ]

== 74.38.030 - Administration of community-based services program—Area plans—Annual state plan—Determination of low-income eligible persons.
. The program of community-based services authorized under this chapter shall be administered by the department. Such services may be provided by the department or through purchase of service contracts, vendor payments or direct client grants.

The department shall, under stipend or grant programs provided under RCW 74.38.060, utilize, to the maximum staffing level possible, eligible persons in its administration, supervision, and operation.

. The department shall be responsible for planning, coordination, monitoring and evaluation of services provided under this chapter but shall avoid duplication of services.

. The department may designate area agencies in cities of not less than twenty thousand population or in regional areas within the state. These agencies shall submit area plans, as required by the department. For area plans prepared for submission in 2009, and thereafter, the area agencies may include the findings and recommendations of area-wide planning initiatives that they may undertake with appropriate local and regional partners regarding the changing age demographics of their area and the implications of this demographic change for public policies and public services. They shall also submit, in the manner prescribed by the department, such other program or fiscal data as may be required.

. The department shall develop an annual state plan pursuant to the Older Americans Act of 1965, as now or hereafter amended. This plan shall include, but not be limited to:

.. Area agencies' programs and services approved by the department;

.. Other programs and services authorized by the department; and

.. Coordination of all programs and services.

. The department shall establish rules and regulations for the determination of low-income eligible persons. Such determination shall be related to need based on the initial resources and subsequent income of the person entering into a program or service. This determination shall not prevent the eligible person from utilizing a program or service provided by the department or area agency. However, if the determination is that such eligible person is nonlow income, the provision of RCW 74.38.050 shall be applied as of the date of such determination.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2668-S2.SL.pdf?cite=2008%20c%20146%20§%205[2008 c 146 § 5]; 1975-'76 2nd ex.s. c 131 § 3; ]

== 74.38.040 - Scope and extent of community based services program.
The community based services for low-income eligible persons provided by the department or the respective area agencies may include:

. Access services designed to provide identification of eligible persons, assessment of individual needs, reference to the appropriate service, and follow-up service where required. These services shall include information and referral, outreach, transportation, and counseling;

. Day care offered on a regular, recurrent basis. General nursing, rehabilitation, personal care, nutritional services, social casework, mental health as provided pursuant to chapter 71.24 RCW, and/or limited transportation services may be made available within this program;

. In-home care for persons, including basic health care; performance of various household tasks and other necessary chores, or, a combination of these services;

. Counseling on death for the terminally ill and care and attendance at the time of death; except, that this is not to include reimbursement for the use of life-sustaining mechanisms;

. Health services which will identify health needs and which are designed to avoid institutionalization; assist in securing admission to medical institutions or other health related facilities when required; and, assist in obtaining health services from public or private agencies or providers of health services. These services shall include health screening and evaluation, in-home services, health education, and such health appliances which will further the independence and well-being of the person;

. The provision of low-cost, nutritionally sound meals in central locations or in the person's home in the instance of incapacity. Also, supportive services may be provided in nutritional education, shopping assistance, diet counseling, and other services to sustain the nutritional well-being of these persons;

. The provisions of services to maintain a person's home in a state of adequate repair, insofar as is possible, for their safety and comfort. These services shall be limited, but may include housing counseling, minor repair and maintenance, and moving assistance when such repair will not attain standards of health and safety, as determined by the department;

. Civil legal services, as limited by RCW 2.50.100, for counseling and representation in the areas of housing, consumer protection, public entitlements, property, and related fields of law;

. Long-term care ombuds programs for residents of all long-term care facilities.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20225[2013 c 23 § 225]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c290.pdf?cite=1983%20c%20290%20§%2014[1983 c 290 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c321.pdf?cite=1977%20ex.s.%20c%20321%20§%203[1977 ex.s. c 321 § 3]; 1975-'76 2nd ex.s. c 131 § 4; ]

== 74.38.050 - Availability of services for persons other than those of low income—Utilization of volunteers and public assistance recipients—Private agencies—Well-adult clinics—Fee schedule, exceptions.
The services provided in RCW 74.38.040 may be provided to nonlow-income eligible persons: PROVIDED, That the department and the area agencies on aging shall utilize volunteer workers and public assistant recipients to the maximum extent possible to provide the services provided in RCW 74.38.040: PROVIDED, FURTHER, That the department and the area agencies shall utilize the bid procedure pursuant to chapter 43.19 RCW for providing such services to low-income and nonlow-income persons whenever the services to be provided are available through private agencies at a cost savings to the department. The department shall establish a fee schedule based on the ability to pay and graduated to full recovery of the cost of the service provided; except, that nutritional services, health screening, services under the long-term care ombuds program under chapter 43.190 RCW, and access services provided in RCW 74.38.040 shall not be based on need and no fee shall be charged; except further, notwithstanding any other provision of this chapter, that well-adult clinic services may be provided in lieu of health screening services if such clinics use the fee schedule established by this section.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20226[2013 c 23 § 226]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c290.pdf?cite=1983%20c%20290%20§%2015[1983 c 290 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c147.pdf?cite=1979%20ex.s.%20c%20147%20§%201[1979 ex.s. c 147 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c321.pdf?cite=1977%20ex.s.%20c%20321%20§%204[1977 ex.s. c 321 § 4]; 1975-'76 2nd ex.s. c 131 § 5; ]

== 74.38.060 - Expansion of federal programs authorized.
The department may expand the foster grandparent, senior companion and retired senior volunteer programs funded under the Federal Volunteer Agency (ACTION) (P.L. 93-113 Title II), or its successor agency, which provide senior citizens with volunteer stipends, out-of-pocket expenses, or wages to perform services in the community.

[ 1975-'76 2nd ex.s. c 131 § 6; ]

== 74.38.061 - Expansion of federal programs authorized.
The department may expand the foster grandparent, senior companion, and retired senior volunteer programs funded under the Federal Volunteer Agency (ACTION) (P.L. 93-113 Title II), or its successor agency, which provide senior citizens with volunteer stipends, out-of-pocket expenses, or wages to perform services in the community.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c321.pdf?cite=1977%20ex.s.%20c%20321%20§%205[1977 ex.s. c 321 § 5]; ]

== 74.38.070 - Reduced utility rates for low-income senior citizens and other low-income citizens.
Notwithstanding any other provision of law, any county, city, town, public utility district or other municipal corporation, or quasi municipal corporation providing utility services may provide such services at reduced rates for low-income senior citizens or other low-income citizens: PROVIDED, That, for the purposes of this section, "low-income senior citizen" or "other low-income citizen" shall be defined by appropriate ordinance or resolution adopted by the governing body of the county, city, town, public utility district or other municipal corporation, or quasi municipal corporation providing the utility services. Any reduction in rates granted in whatever manner to low-income senior citizens or other low-income citizens in one part of a service area shall be uniformly extended to low-income senior citizens or other low-income citizens in all other parts of the service area.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6416.SL.pdf?cite=2002%20c%20270%20§%201[2002 c 270 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6560-S.SL.pdf?cite=1998%20c%20300%20§%208[1998 c 300 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c164.pdf?cite=1990%20c%20164%20§%201[1990 c 164 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c44.pdf?cite=1988%20c%2044%20§%201[1988 c 44 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c160.pdf?cite=1980%20c%20160%20§%201[1980 c 160 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c116.pdf?cite=1979%20c%20116%20§%201[1979 c 116 § 1]; ]

== 74.38.900 - Short title.
Sections 1 through 6 of this act shall be known and may be cited as the "Senior Citizens Services Act".

[ 1975-'76 2nd ex.s. c 131 § 7; ]

