= 74.31 - Traumatic brain injuries.
:toc:

== 74.31.005 - Findings—Intent.
The center for disease control estimates that at least five million three hundred thousand Americans, approximately two percent of the United States population, currently have a long-term or lifelong need for help to perform activities of daily living as a result of a traumatic brain injury. Each year approximately one million four hundred thousand people in this country, including children, sustain traumatic brain injuries as a result of a variety of causes including falls, motor vehicle injuries, being struck by an object, or as a result of an assault and other violent crimes, including domestic violence. Additionally, there are significant numbers of veterans who sustain traumatic brain injuries as a result of their service in the military.

Prevention and the provision of appropriate supports and services in response to traumatic brain injury are consistent with the governor's executive order No. 10-01, "Implementing Health Reform the Washington Way," which recognizes protection of public health and the improvement of health status as essential responsibilities of the public health system.

Traumatic brain injury can cause a wide range of functional changes affecting thinking, sensation, language, or emotions. It can also cause epilepsy and increase the risk for conditions such as Alzheimer's disease, Parkinson's disease, and other brain disorders that become more prevalent with age. The impact of a traumatic brain injury on the individual and family can be devastating.

The legislature recognizes that current programs and services are not funded or designed to address the diverse needs of this population. It is the intent of the legislature to develop a comprehensive plan to help individuals with traumatic brain injuries meet their needs. The legislature also recognizes the efforts of many in the private sector who are providing services and assistance to individuals with traumatic brain injuries. The legislature intends to bring together those in both the public and private sectors with expertise in this area to address the needs of this growing population.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1614-S.SL.pdf?cite=2011%20c%20143%20§%201[2011 c 143 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2055-S2.SL.pdf?cite=2007%20c%20356%20§%201[2007 c 356 § 1]; ]

== 74.31.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Department" means the department of social and health services.

. "Department of health" means the Washington state department of health created pursuant to RCW 43.70.020.

. "Secretary" means the secretary of social and health services.

. "Traumatic brain injury" means injury to the brain caused by physical trauma resulting from, but not limited to, incidents involving motor vehicles, sporting events, falls, and physical assaults. Documentation of traumatic brain injury shall be based on adequate medical history, neurological examination, mental status testing, or neuropsychological evaluation. A traumatic brain injury shall be of sufficient severity to result in impairments in one or more of the following areas: Cognition; language memory; attention; reasoning; abstract thinking; judgment; problem solving; sensory, perceptual, and motor abilities; psychosocial behavior; physical functions; or information processing. The term does not apply to brain injuries that are congenital or degenerative, or to brain injuries induced by birth trauma.

. "Traumatic brain injury account" means the account established under RCW 74.31.060.

. "Council" means the Washington traumatic brain injury strategic partnership advisory council created under RCW 74.31.020.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2055-S2.SL.pdf?cite=2007%20c%20356%20§%202[2007 c 356 § 2]; ]

== 74.31.020 - Washington traumatic brain injury strategic partnership advisory council—Members—Expenses—Appointment—Duties.
. The Washington traumatic brain injury strategic partnership advisory council is established as an advisory council to the governor, the legislature, and the secretary of the department of social and health services.

. The council shall be composed of:

.. The following members who shall be appointed by the governor:

... A representative from a Native American tribe located in Washington state;

... Two representatives from a nonprofit organization serving individuals with traumatic brain injury;

... An individual with expertise in working with children with traumatic brain injuries;

... A physician who has experience working with individuals with traumatic brain injuries;

.. A neuropsychologist who has experience working with persons with traumatic brain injuries;

.. A social worker or clinical psychologist who has experience in working with persons who have sustained traumatic brain injuries;

.. A rehabilitation specialist, such as a speech pathologist, vocational rehabilitation counselor, occupational therapist, or physical therapist who has experience working with persons with traumatic brain injuries;

.. Two persons who are individuals with a traumatic brain injury;

... Two persons who are family members of individuals with traumatic brain injuries; and

.. Two members of the public who have experience with issues related to the causes of traumatic brain injuries; and

.. The following agency members:

... The secretary or the secretary's designee, and representatives from the following: The division of behavioral health and recovery services, the aging and disability services administration, and the division of vocational rehabilitation;

... The secretary of health or the secretary's designee;

... The secretary of corrections or the secretary's designee;

... The secretary of children, youth, and families or the secretary's designee;

.. A representative of the department of commerce with expertise in housing;

.. A representative from the Washington state department of veterans affairs;

.. A representative from the national guard; and

.. The executive director of the Washington protection and advocacy system or the executive director's designee.

. Councilmembers shall not be compensated for serving on the council, but may be reimbursed for all reasonable expenses related to costs incurred in participating in meetings for the council.

. No member may serve more than two consecutive terms.

. The appointed members of the council shall, to the extent possible, represent rural and urban areas of the state.

. A chairperson shall be elected every two years by majority vote from among the councilmembers. The chairperson shall act as the presiding officer of the council.

. The duties of the council include:

.. Collaborating with the department to develop and revise as needed a comprehensive statewide plan to address the needs of individuals with traumatic brain injuries;

.. Providing recommendations to the department on criteria to be used to select programs facilitating support groups for individuals with traumatic brain injuries and their families under RCW 74.31.050;

.. By January 15, 2013, and every two years thereafter, developing a report in collaboration with the department and submitting it to the legislature and the governor on the following:

... Identifying the activities of the council in the implementation of the comprehensive statewide plan;

... Recommendations for the revisions to the comprehensive statewide plan;

... Recommendations for using the traumatic brain injury account established under RCW 74.31.060 to form strategic partnerships and to foster the development of services and supports for individuals impacted by traumatic brain injuries; and

... Recommendations for a council staffing plan for council support under RCW 74.31.030.

. The council may utilize the advice or services of a nationally recognized expert, or other individuals as the council deems appropriate, to assist the council in carrying out its duties under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5127-S.SL.pdf?cite=2019%20c%20181%20§%203[2019 c 181 § 3]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6287.SL.pdf?cite=2018%20c%2058%20§%2055[2018 c 58 § 55]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1614-S.SL.pdf?cite=2011%20c%20143%20§%202[2011 c 143 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2055-S2.SL.pdf?cite=2007%20c%20356%20§%203[2007 c 356 § 3]; ]

== 74.31.030 - Staff support—Department powers and duties—Comprehensive plan.
. In response to council recommendations developed pursuant to RCW 74.31.020, the department shall include in the comprehensive statewide plan a staffing plan for providing adequate support for council activities for positions funded by the traumatic brain injury account established in RCW 74.31.060 and designate at least one staff person who shall be responsible for the following:

.. Coordinating policies, programs, and services for individuals with traumatic brain injuries; and

.. Providing staff support to the council created in RCW 74.31.020.

. The department shall provide data and information to the council established under RCW 74.31.020 that is requested by the council and is in the possession or control of the department.

. The department shall implement, within funds appropriated for this specific purpose, the comprehensive statewide plan to address the needs of individuals impacted by traumatic brain injuries, including the use of public-private partnerships and a public awareness campaign. The comprehensive plan should be created in collaboration with the council and should consider the following:

.. Building provider capacity and provider training;

.. Improving the coordination of services;

.. The feasibility of establishing agreements with private sector agencies or tribal governments to develop services for individuals with traumatic brain injuries; and

.. Other areas the council deems appropriate.

. The department shall:

.. Assure that information and referral services are provided to individuals with traumatic brain injuries. The referral services may be funded from the traumatic brain injury account established under RCW 74.31.060;

.. Encourage and facilitate the following:

... Collaboration among state agencies that provide services to individuals with traumatic brain injuries;

... Collaboration among organizations and entities that provide services to individuals with traumatic brain injuries; and

... Community participation in program implementation; and

.. Have the authority to accept, expend, or retain any gifts, bequests, contributions, or grants from private persons or private and public agencies to carry out the purpose of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1614-S.SL.pdf?cite=2011%20c%20143%20§%203[2011 c 143 § 3]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6444-S.SL.pdf?cite=2010%201st%20sp.s.%20c%2037%20§%20943[2010 1st sp.s. c 37 § 943]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2055-S2.SL.pdf?cite=2007%20c%20356%20§%204[2007 c 356 § 4]; ]

== 74.31.040 - Public awareness campaign.
In collaboration with the council, the department shall conduct a public awareness campaign that utilizes funding from the traumatic brain injury account to leverage a private advertising campaign to persuade Washington residents to be aware and concerned about the issues facing individuals with traumatic brain injuries through all forms of media including television, radio, and print.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1614-S.SL.pdf?cite=2011%20c%20143%20§%204[2011 c 143 § 4]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2055-S2.SL.pdf?cite=2007%20c%20356%20§%205[2007 c 356 § 5]; ]

== 74.31.050 - Support group programs—Funding—Recommendations.
. The department shall provide funding from the traumatic brain injury account established by RCW 74.31.060 to programs that facilitate support groups to individuals with traumatic brain injuries and their families.

. The department shall use a request for proposal process to select the programs to receive funding. The council shall provide recommendations to the department on the criteria to be used in selecting the programs.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1614-S.SL.pdf?cite=2011%20c%20143%20§%205[2011 c 143 § 5]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2055-S2.SL.pdf?cite=2007%20c%20356%20§%206[2007 c 356 § 6]; ]

== 74.31.060 - Traumatic brain injury account.
The traumatic brain injury account is created in the state treasury. The fee imposed under RCW 46.63.110(7)(c) must be deposited into the account. Moneys in the account may be spent only after appropriation, and may be used only to support the activities in the statewide traumatic brain injury comprehensive plan, to provide a public awareness campaign and services relating to traumatic brain injury under RCW 74.31.040 and 74.31.050, for information and referral services, and for costs of required department staff who are providing support for the council under RCW 74.31.020 and 74.31.030. The secretary of the department of social and health services has the authority to administer the funds. The department must make every effort to disburse the incremental revenue that is the result of the fee increased under RCW 46.63.110(7)(c) in a diverse manner to include rural areas of the state.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5127-S.SL.pdf?cite=2019%20c%20181%20§%202[2019 c 181 § 2]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1614-S.SL.pdf?cite=2011%20c%20143%20§%206[2011 c 143 § 6]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6444-S.SL.pdf?cite=2010%201st%20sp.s.%20c%2037%20§%20944[2010 1st sp.s. c 37 § 944]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2055-S2.SL.pdf?cite=2007%20c%20356%20§%207[2007 c 356 § 7]; ]

== 74.31.070 - Statewide response to traumatic brain injuries suffered by domestic violence survivors—Recommendations—Educational handout—Website.
. The department, in consultation with the council and at least one representative of a community-based domestic violence program and one medical professional with experience treating survivors of domestic violence, shall develop recommendations to improve the statewide response to traumatic brain injuries suffered by domestic violence survivors. In developing recommendations, the department may consider the creation of an educational handout, to be updated on a periodic basis, regarding traumatic brain injury to be provided to victims of domestic violence. The handout may include the information and screening tool described in subsection (2) of this section.

. [Empty]
.. The department, in consultation with the council, shall establish and recommend or develop content for a statewide website for victims of domestic violence to include:

... An explanation of the potential for domestic abuse to lead to traumatic brain injury;

... Information on recognizing cognitive, behavioral, and physical symptoms of traumatic brain injury as well as potential impacts to a person's emotional well-being and mental health;

... A self-screening tool for traumatic brain injury; and

... Recommendations for persons with traumatic brain injury to help address or cope with the injury.

.. The department must update the website created under this subsection on a periodic basis.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1532-S.SL.pdf?cite=2019%20c%20110%20§%201[2019 c 110 § 1]; ]

