= 74.39A - Long-term care services options—Expansion.
:toc:

== 74.39A.005 - Findings.
The legislature finds that the aging of the population and advanced medical technology have resulted in a growing number of persons who require assistance. The primary resource for long-term care continues to be family and friends. However, these traditional caregivers are increasingly employed outside the home. There is a growing demand for improvement and expansion of home and community-based long-term care services to support and complement the services provided by these informal caregivers.

The legislature further finds that the public interest would best be served by a broad array of long-term care services that support persons who need such services at home or in the community whenever practicable and that promote individual autonomy, dignity, and choice.

The legislature finds that as other long-term care options become more available, the relative need for nursing home beds is likely to decline. The legislature recognizes, however, that nursing home care will continue to be a critical part of the state's long-term care options, and that such services should promote individual dignity, autonomy, and a homelike environment.

The legislature finds that many recipients of in-home services are vulnerable and their health and well-being are dependent on their caregivers. The quality, skills, and knowledge of their caregivers are often the key to good care. The legislature finds that the need for well-trained caregivers is growing as the state's population ages and clients' needs increase. The legislature intends that current training standards be enhanced.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6502-S.SL.pdf?cite=2000%20c%20121%20§%209[2000 c 121 § 9]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2098-S.SL.pdf?cite=1993%20c%20508%20§%201[1993 c 508 § 1]; ]

== 74.39A.007 - Purpose and intent.
It is the legislature's intent that:

. Long-term care services administered by the department of social and health services include a balanced array of health, social, and supportive services that promote individual choice, dignity, and the highest practicable level of independence;

. Home and community-based services be developed, expanded, or maintained in order to meet the needs of consumers and to maximize effective use of limited resources;

. Long-term care services be responsive and appropriate to individual need and also cost-effective for the state;

. Nursing home care is provided in such a manner and in such an environment as will promote maintenance or enhancement of the quality of life of each resident and timely discharge to a less restrictive care setting when appropriate; and

. State health planning for nursing home bed supply take into account increased availability of other home and community-based service options.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2098-S.SL.pdf?cite=1993%20c%20508%20§%202[1993 c 508 § 2]; ]

== 74.39A.009 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Adult family home" means a home licensed under chapter 70.128 RCW.

. "Adult residential care" means services provided by an assisted living facility that is licensed under chapter 18.20 RCW and that has a contract with the department under RCW 74.39A.020 to provide personal care services.

. "Assisted living facility" means a facility licensed under chapter 18.20 RCW.

. "Assisted living services" means services provided by an assisted living facility that has a contract with the department under RCW 74.39A.010 to provide personal care services, intermittent nursing services, and medication administration services; and the facility provides these services to residents who are living in private apartment-like units.

. "Community residential service business" means a business that:

.. Is certified by the department of social and health services to provide to individuals who have a developmental disability as defined in RCW 71A.10.020(5):

... Group home services;

... Group training home services;

... Supported living services; or

... Voluntary placement services provided in a licensed staff residential facility for children;

.. Has a contract with the developmental disabilities administration to provide the services identified in (a) of this subsection; and

.. All of the business's long-term care workers are subject to statutory or regulatory training requirements that are required to provide the services identified in (a) of this subsection.

. "Consumer" or "client" means a person who is receiving or has applied for services under this chapter, including a person who is receiving services from an individual provider.

. "Consumer directed employer" is a private entity that contracts with the department to be the legal employer of individual providers for purposes of performing administrative functions. The consumer directed employer is patterned after the agency with choice model, recognized by the federal centers for medicare and medicaid services for financial management in consumer directed programs. The entity's responsibilities are described in RCW 74.39A.515 and throughout this chapter and include: (a) Coordination with the consumer, who is the individual provider's managing employer; (b) withholding, filing, and paying income and employment taxes, including workers' compensation premiums and unemployment taxes, for individual providers; (c) verifying an individual provider's qualifications; and (d) providing other administrative and employment-related supports. The consumer directed employer is a social service agency and its employees are mandated reporters as defined in RCW 74.34.020.

. "Core competencies" means basic training topics, including but not limited to, communication skills, worker self-care, problem solving, maintaining dignity, consumer directed care, cultural sensitivity, body mechanics, fall prevention, skin and body care, long-term care worker roles and boundaries, supporting activities of daily living, and food preparation and handling.

. "Cost-effective care" means care provided in a setting of an individual's choice that is necessary to promote the most appropriate level of physical, mental, and psychosocial well-being consistent with client choice, in an environment that is appropriate to the care and safety needs of the individual, and such care cannot be provided at a lower cost in any other setting. But this in no way precludes an individual from choosing a different residential setting to achieve his or her desired quality of life.

. "Department" means the department of social and health services.

. "Developmental disability" has the same meaning as defined in RCW 71A.10.020.

. "Direct care worker" means a paid caregiver who provides direct, hands-on personal care services to persons with disabilities or the elderly requiring long-term care.

. "Enhanced adult residential care" means services provided by an assisted living facility that is licensed under chapter 18.20 RCW and that has a contract with the department under RCW 74.39A.010 to provide personal care services, intermittent nursing services, and medication administration services.

. "Facility" means an adult family home, an assisted living facility, a nursing home, an enhanced services facility licensed under chapter 70.97 RCW, or a facility certified to provide medicare or medicaid services in nursing facilities or intermediate care facilities for individuals with intellectual disabilities under 42 C.F.R. Part 483.

. "Home and community-based services" means services provided in adult family homes, in-home services, and other services administered or provided by contract by the department directly or through contract with area agencies on aging or similar services provided by facilities and agencies licensed or certified by the department.

. "Home care aide" means a long-term care worker who is certified as a home care aide by the department of health under chapter 18.88B RCW.

. "Individual provider" is defined according to RCW 74.39A.240.

. "Legal employer" means the consumer directed employer, which along with the consumer, coemploys individual providers. The legal employer is responsible for setting wages and benefits for individual providers and must comply with applicable laws including, but not limited to, workers compensation and unemployment insurance laws.

. "Long-term care" means care and supports delivered indefinitely, intermittently, or over a sustained time to persons of any age who are functionally disabled due to chronic mental or physical illness, disease, chemical dependency, or a medical condition that is permanent, not curable, or is long-lasting and severely limits their mental or physical capacity for self-care. The use of this definition is not intended to expand the scope of services, care, or assistance provided by any individuals, groups, residential care settings, or professions unless otherwise required by law.

. [Empty]
.. "Long-term care workers" include all persons who provide paid, hands-on personal care services for the elderly or persons with disabilities, including but not limited to individual providers of home care services, direct care workers employed by home care agencies or a consumer directed employer, providers of home care services to persons with developmental disabilities under Title 71A RCW, all direct care workers in state-licensed assisted living facilities, enhanced services facilities, and adult family homes, respite care providers, direct care workers employed by community residential service businesses, and any other direct care worker providing home or community-based services to the elderly or persons with functional disabilities or developmental disabilities.

.. "Long-term care workers" do not include: (i) Persons employed by the following facilities or agencies: Nursing homes licensed under chapter 18.51 RCW, hospitals or other acute care settings, residential habilitation centers under chapter 71A.20 RCW, facilities certified under 42 C.F.R., Part 483, hospice agencies subject to chapter 70.127 RCW, adult day care centers, and adult day health care centers; or (ii) persons who are not paid by the state or by a private agency or facility licensed or certified by the state to provide personal care services.

. "Managing employer" means a consumer who coemploys one or more individual providers and whose responsibilities include (a) choosing potential individual providers and referring them to the consumer directed employer; (b) overseeing the day-to-day management and scheduling of the individual provider's tasks consistent with the plan of care; and (c) dismissing the individual provider when desired.

. "Nursing home" or "nursing facility" means a facility licensed under chapter 18.51 RCW or certified as a medicaid nursing facility under 42 C.F.R. Part 483, or both.

. "Person who is functionally disabled" means a person who because of a recognized chronic physical or mental condition or disease, including chemical dependency or developmental disability, is dependent upon others for direct care, support, supervision, or monitoring to perform activities of daily living. "Activities of daily living," in this context, means self-care abilities related to personal care such as bathing, eating, using the toilet, dressing, and transfer. Instrumental activities of daily living such as cooking, shopping, house cleaning, doing laundry, working, and managing personal finances may also be considered when assessing a person's functional abilities [ability] to perform activities in the home and the community.

. "Personal care services" means physical or verbal assistance with activities of daily living and instrumental activities of daily living provided because of a person's functional disability.

. "Population specific competencies" means basic training topics unique to the care needs of the population the long-term care worker is serving, including but not limited to, mental health, dementia, developmental disabilities, young adults with physical disabilities, and older adults.

. "Qualified instructor" means a registered nurse or other person with specific knowledge, training, and work experience in the provision of direct, hands-on personal care and other assistance services to the elderly or persons with disabilities requiring long-term care.

. "Secretary" means the secretary of social and health services.

. "Training partnership" means a joint partnership or trust that includes the office of the governor and the exclusive bargaining representative of individual providers under RCW 74.39A.270 with the capacity to provide training, peer mentoring, and workforce development, or other services to individual providers.

. "Tribally licensed assisted living facility" means an assisted living facility licensed by a federally recognized Indian tribe in which a facility provides services similar to services provided by assisted living facilities licensed under chapter 18.20 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6199-S.SL.pdf?cite=2018%20c%20278%20§%202[2018 c 278 § 2]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2314-S.SL.pdf?cite=2012%20c%20164%20§%20202[2012 c 164 § 202]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2056-S.SL.pdf?cite=2012%20c%2010%20§%2063[2012 c 10 § 63]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6180-S.SL.pdf?cite=2009%20c%20580%20§%201[2009 c 580 § 1]; 2009 c 2 § 2 (Initiative Measure No. 1029, approved November 4, 2008); http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2284-S2.SL.pdf?cite=2007%20c%20361%20§%202[2007 c 361 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6225-S.SL.pdf?cite=2004%20c%20142%20§%2014[2004 c 142 § 14]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1850-S2.SL.pdf?cite=1997%20c%20392%20§%20103[1997 c 392 § 103]; ]

== 74.39A.010 - Assisted living services and enhanced adult residential care—Contracts—Rules.
. To the extent of available funding, the department of social and health services may contract with licensed assisted living facilities under chapter 18.20 RCW and tribally licensed assisted living facilities for assisted living services and enhanced adult residential care. The department shall develop rules for facilities that contract with the department for assisted living services or enhanced adult residential care to establish:

.. Facility service standards consistent with the principles in RCW 74.39A.051 and consistent with chapter 70.129 RCW;

.. Standards for resident living areas consistent with RCW 74.39A.030;

.. Training requirements for providers and their staff.

. The department's rules shall provide that services in assisted living and enhanced adult residential care:

.. Recognize individual needs, privacy, and autonomy;

.. Include, but not be limited to, personal care, nursing services, medication administration, and supportive services that promote independence and self-sufficiency;

.. Are of sufficient scope to assure that each resident who chooses to remain in the assisted living or enhanced adult residential care may do so, to the extent that the care provided continues to be cost-effective and safe and promote the most appropriate level of physical, mental, and psychosocial well-being consistent with client choice;

.. Are directed first to those persons most likely, in the absence of enhanced adult residential care or assisted living services, to need hospital, nursing facility, or other out-of-home placement; and

.. Are provided in compliance with applicable facility and professional licensing laws and rules.

. When a facility contracts with the department for assisted living services or enhanced adult residential care, only services and facility standards that are provided to or in behalf of the assisted living services or enhanced adult residential care client shall be subject to the department's rules.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2314-S.SL.pdf?cite=2012%20c%20164%20§%20706[2012 c 164 § 706]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2056-S.SL.pdf?cite=2012%20c%2010%20§%2064[2012 c 10 § 64]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1908-S2.SL.pdf?cite=1995%201st%20sp.s.%20c%2018%20§%2014[1995 1st sp.s. c 18 § 14]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2098-S.SL.pdf?cite=1993%20c%20508%20§%203[1993 c 508 § 3]; ]

== 74.39A.020 - Adult residential care—Contracts—Rules.
. To the extent of available funding, the department of social and health services may contract for adult residential care.

. The department shall, by rule, develop terms and conditions for facilities that contract with the department for adult residential care to establish:

.. Facility service standards consistent with the principles in RCW 74.39A.051 and consistent with chapter 70.129 RCW; and

.. Training requirements for providers and their staff.

. The department shall, by rule, provide that services in adult residential care facilities:

.. Recognize individual needs, privacy, and autonomy;

.. Include personal care and other services that promote independence and self-sufficiency and aging in place;

.. Are directed first to those persons most likely, in the absence of adult residential care services, to need hospital, nursing facility, or other out-of-home placement; and

.. Are provided in compliance with applicable facility and professional licensing laws and rules.

. When a facility contracts with the department for adult residential care, only services and facility standards that are provided to or in behalf of the adult residential care client shall be subject to the adult residential care rules.

. To the extent of available funding, the department may also contract under this section with a tribally licensed assisted living facility for the provision of services of the same nature as the services provided by adult residential care facilities. The provisions of subsections (2)(a) and (b) and (3)(a) through (d) of this section apply to such a contract.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2314-S.SL.pdf?cite=2012%20c%20164%20§%20707[2012 c 164 § 707]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2056-S.SL.pdf?cite=2012%20c%2010%20§%2065[2012 c 10 § 65]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6225-S.SL.pdf?cite=2004%20c%20142%20§%2015[2004 c 142 § 15]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1908-S2.SL.pdf?cite=1995%201st%20sp.s.%20c%2018%20§%2015[1995 1st sp.s. c 18 § 15]; ]

== 74.39A.030 - Expansion of home and community services—Payment rates.
. To the extent of available funding, the department shall expand cost-effective options for home and community services for consumers for whom the state participates in the cost of their care.

. In expanding home and community services, the department shall take full advantage of federal funding available under Title XVIII and Title XIX of the federal social security act, including home health, adult day care, waiver options, and state plan services and expand the availability of in-home services and residential services, including services in adult family homes, assisted living facilities, and enhanced services facilities.

. [Empty]
.. The department shall by rule establish payment rates for home and community services that support the provision of cost-effective care. Beginning July 1, 2019, the department shall adopt a data-driven medicaid payment methodology as specified in RCW 74.39A.032 for contracted assisted living, adult residential care, and enhanced adult residential care. In the event of any conflict between any such rule and a collective bargaining agreement entered into under RCW 74.39A.270 and 74.39A.300, the collective bargaining agreement prevails.

.. The department may authorize an enhanced adult residential care rate for nursing homes that temporarily or permanently convert their bed use under chapter 70.38 RCW for the purposes of providing assisted living, enhanced adult residential care, or adult residential care, when the department determines that payment of an enhanced rate is cost-effective and necessary to foster expansion of these contracted services. As an incentive for nursing homes to permanently convert a portion of their nursing home bed capacity for the purposes of providing assisted living, enhanced adult residential care, or adult residential care, including but not limited to serving individuals with behavioral health treatment needs, the department may authorize a supplemental add-on to the residential care rate.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1394-S2.SL.pdf?cite=2019%20c%20324%20§%2011[2019 c 324 § 11]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6199-S.SL.pdf?cite=2018%20c%20278%20§%206[2018 c 278 § 6]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2515-S.SL.pdf?cite=2018%20c%20225%20§%202[2018 c 225 § 2]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2056-S.SL.pdf?cite=2012%20c%2010%20§%2066[2012 c 10 § 66]; 2002 c 3 § 10 (Initiative Measure No. 775, approved November 6, 2001); http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1908-S2.SL.pdf?cite=1995%201st%20sp.s.%20c%2018%20§%202[1995 1st sp.s. c 18 § 2]; ]

== 74.39A.032 - Medicaid payment methodology for certain contracted assisted living facilities—Established by rule—Required components.
. The department shall establish in rule a new medicaid payment system for contracted assisted living, adult residential care, and enhanced adult residential care. Beginning July 1, 2019, payments for these contracts must be based on the new methodology which must be phased-in to full implementation according to funding made available by the legislature for this purpose. The new payment system must have these components: Client care, operations, and room and board.

. Client care is the labor component of the system and must include variables to recognize the time and intensity of client care and services, staff wages, and associated fringe benefits. The wage variable in the client care component must be adjusted according to service areas based on labor costs.

.. The time variable is used to weight the client care payment to client acuity and must be scaled according to the classification levels utilized in the department's assessment tool. The initial system shall establish a variable for time using the residential care time study conducted in 2001 and the department's corresponding estimate of the average staff hours per client by job position.

.. The wage variable shall include recognition of staff positions needed to perform the functions required by contract, including nursing services. Data used to establish the wage variable must be adjusted so that no baseline wage is below the state minimum in effect at the time of implementation. The wage variable is a blended wage based on the federal bureau of labor statistics wage data and the distribution of time according to staff position. Blended wages are established for each county and then counties are arrayed from highest to lowest. Service areas are established and the median blended wage in each service area becomes the wage variable for all the assigned counties in that service area. The system must have no less than two service areas, one of which shall be a high labor cost service area and shall include counties at or above the ninety-fifth percentile in the array of blended wages.

.. The fringe benefit variable recognizes employee benefits and payroll taxes. The factor to calculate the percentage of fringe benefits shall be established using the statewide nursing facility cost ratio of benefits and payroll taxes to in-house wages.

. The operations component must recognize costs that are allowable under federal medicaid rules for the federal matching percentage. The operations component is calculated at ninety percent or greater of the statewide median nursing facility costs associated with the following:

.. Supplies;

.. Nonlabor administrative expenses;

.. Staff education and in-service training; and

.. Operational overhead including licenses, insurance, and business and occupational [occupation] taxes.

. The room and board component recognizes costs that do not qualify for federal financial participation under medicaid rules by compensating providers for the medicaid client's share of raw food and shelter costs including expenses related to the physical plant such as property taxes, property and liability insurance, debt service, and major capital repairs. The room and board component is subject to the department's and the Washington state health care authority's rules related to client financial responsibility.

. Subsections (2) and (3) of this section establish the rate for medicaid covered services. Subsection (4) of this section establishes the rate for nonmedicaid covered services.

. The rates paid on July 1, 2019, shall be based on data from the 2016 calendar year, except for the time variable under subsection (2)(a) of this section. The client care and operations components must be rebased in even-numbered years. Beginning with rates paid on July 1, 2020, wages, benefits and taxes, and operations costs shall be rebased using 2018 data.

. Beginning July 1, 2020, the room and board component shall be updated annually subject to the department's and the Washington state health care authority's rules related to client financial responsibility.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2515-S.SL.pdf?cite=2018%20c%20225%20§%203[2018 c 225 § 3]; ]

== 74.39A.035 - Expansion of nutrition services through the meals on wheels program.
. Subject to the availability of amounts appropriated for this specific purpose, the department of social and health services must develop a program to expand nutrition services through the meals on wheels program.

.. At least sixty-five percent of the moneys may be distributed according to formulae to existing providers of meals on wheels programs to expand the number of people served.

.. Up to twenty-five percent of the moneys may be distributed by a competitive grant process to expand the meals on wheels program into areas not presently being served.

.. Up to five percent of the moneys may be used by the department administration, monitoring of the grants, and providing technical assistance to existing and new meals on wheels providers.

. The department must develop criteria for awarding grants under subsection (1)(b) of this section. The criteria must include, but is not limited to:

.. Expanding service in areas with the greatest need to assist low-income homebound seniors who are unable to prepare food for themselves and lack a caregiver that prepares meals;

.. Expanding services in areas where senior citizens have limited access to community support services and facilities; and

.. Geographic diversity within the state and between rural and urban areas.

. None of the grant moneys awarded under subsection (1)(b) of this section may be used to supplant existing funds the provider receives for the meals on wheels program.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5736.SL.pdf?cite=2017%20c%20287%20§%202[2017 c 287 § 2]; ]

== 74.39A.040 - Department assessment of and assistance to hospital patients in need of long-term care.
The department shall work in partnership with hospitals in assisting patients and their families to find long-term care services of their choice. The department shall not delay hospital discharges but shall assist and support the activities of hospital discharge planners. The department also shall coordinate with home health and hospice agencies whenever appropriate. The role of the department is to assist the hospital and to assist patients and their families in making informed choices by providing information regarding home and community options to individuals who are hospitalized and likely to need long-term care.

. To the extent of available funds, the department shall assess individuals who:

.. Are medicaid clients, medicaid applicants, or eligible for both medicare and medicaid; and

.. Apply or are likely to apply for admission to a nursing facility.

. For individuals who are reasonably expected to become medicaid recipients within one hundred eighty days of admission to a nursing facility, the department shall, to the extent of available funds, offer an assessment and information regarding appropriate in-home and community services.

. When the department finds, based on assessment, that the individual prefers and could live appropriately and cost-effectively at home or in some other community-based setting, the department shall:

.. Advise the individual that an in-home or other community service is appropriate;

.. Develop, with the individual or the individual's representative, a comprehensive community service plan;

.. Inform the individual regarding the availability of services that could meet the applicant's needs as set forth in the community service plan and explain the cost to the applicant of the available in-home and community services relative to nursing facility care; and

.. Discuss and evaluate the need for ongoing involvement with the individual or the individual's representative.

. When the department finds, based on assessment, that the individual prefers and needs nursing facility care, the department shall:

.. Advise the individual that nursing facility care is appropriate and inform the individual of the available nursing facility vacancies;

.. If appropriate, advise the individual that the stay in the nursing facility may be short term; and

.. Describe the role of the department in providing nursing facility case management.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1908-S2.SL.pdf?cite=1995%201st%20sp.s.%20c%2018%20§%206[1995 1st sp.s. c 18 § 6]; ]

== 74.39A.051 - Quality improvement principles.
The department's system of quality improvement for long-term care services shall use the following principles, consistent with applicable federal laws and regulations:

. The system shall be client-centered and promote privacy, independence, dignity, choice, and a home or home-like environment for consumers consistent with chapter 392, Laws of 1997.

. The goal of the system is continuous quality improvement with the focus on consumer satisfaction and outcomes for consumers. This includes that when conducting licensing or contract inspections, the department shall interview an appropriate percentage of residents, family members, resident case managers, and advocates in addition to interviewing providers and staff.

. Providers should be supported in their efforts to improve quality and address identified problems initially through training, consultation, technical assistance, and case management.

. The emphasis should be on problem prevention both in monitoring and in screening potential providers of service.

. Monitoring should be outcome based and responsive to consumer complaints and based on a clear set of health, quality of care, and safety standards that are easily understandable and have been made available to providers, residents, and other interested parties.

. Prompt and specific enforcement remedies shall also be implemented without delay, pursuant to RCW 70.97.110, 71A.12.300, 74.39A.080, or 70.128.160, or chapter 18.51 or 74.42 RCW, for providers found to have delivered care or failed to deliver care resulting in problems that are serious, recurring, or uncorrected, or that create a hazard that is causing or likely to cause death or serious harm to one or more residents. These enforcement remedies may also include, when appropriate, reasonable conditions on a contract or license. In the selection of remedies, the safety, health, and well-being of residents shall be of paramount importance.

. Background checks of long-term care workers must be conducted as provided in RCW 74.39A.056.

. Except as provided in RCW 74.39A.074 and 74.39A.076, individual providers and home care agency providers must satisfactorily complete department-approved orientation, basic training, and continuing education within the time period specified by the department in rule. The department shall adopt rules to implement this section. The department shall deny payment to a consumer directed employer or a home care agency for services provided by employees who have not completed the training requirements within the time limit specified by department rules. The department shall deny payment to any individual providers who provide services under a contract with the department if they have been notified that they are no longer permitted to work because they have not completed the training requirements within the time period required by department rules.

. Under existing funds the department shall establish internally a quality improvement standards committee to monitor the development of standards and to suggest modifications.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6199-S.SL.pdf?cite=2018%20c%20278%20§%207[2018 c 278 § 7]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2314-S.SL.pdf?cite=2012%20c%20164%20§%20701[2012 c 164 § 701]; 2012 c 1 § 106 (Initiative Measure No. 1163, approved November 8, 2011); ]

== 74.39A.056 - Background checks on long-term care workers. (Effective until January 1, 2021.)
. [Empty]
.. All long-term care workers shall be screened through state and federal background checks in a uniform and timely manner to verify that they do not have a history that would disqualify them from working with vulnerable persons. The department must process background checks for long-term care workers and make the information available to employers, prospective employers, and others as authorized by law.

.. [Empty]
... Except as provided in (b)(ii) of this subsection, for long-term care workers hired on or after January 7, 2012, the background checks required under this section shall include checking against the federal bureau of investigation fingerprint identification records system and against the national sex offenders registry or their successor programs. The department shall require these long-term care workers to submit fingerprints for the purpose of investigating conviction records through both the Washington state patrol and the federal bureau of investigation. The department shall not pass on the cost of these criminal background checks to the workers or their employers.

... This subsection does not apply to long-term care workers employed by community residential service businesses until January 1, 2016.

.. The department shall share state and federal background check results with the department of health in accordance with RCW 18.88B.080.

.. Background check screening required under this section and department rules is not required for an employee of a consumer directed employer if all of the following circumstances apply:

... The individual has an individual provider contract with the department;

... The last background check on the contracted individual provider is still valid under department rules and did not disqualify the individual from providing personal care services;

... Employment by the consumer directed employer is the only reason a new background check would be required; and

... The department's background check results have been shared with the consumer directed employer.

. No provider, or its staff, or long-term care worker, or prospective provider or long-term care worker, with a stipulated finding of fact, conclusion of law, an agreed order, or finding of fact, conclusion of law, or final order issued by a disciplining authority or a court of law or entered into a state registry with a final substantiated finding of abuse, neglect, exploitation, or abandonment of a minor or a vulnerable adult as defined in chapter 74.34 RCW shall be employed in the care of and have unsupervised access to vulnerable adults.

. The department shall establish, by rule, a state registry which contains identifying information about long-term care workers identified under this chapter who have final substantiated findings of abuse, neglect, financial exploitation, or abandonment of a vulnerable adult as defined in RCW 74.34.020. The rule must include disclosure, disposition of findings, notification, findings of fact, appeal rights, and fair hearing requirements. The department shall disclose, upon request, final substantiated findings of abuse, neglect, financial exploitation, or abandonment to any person so requesting this information. This information must also be shared with the department of health to advance the purposes of chapter 18.88B RCW.

. The department shall adopt rules to implement this section.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6199-S.SL.pdf?cite=2018%20c%20278%20§%208[2018 c 278 § 8]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2314-S.SL.pdf?cite=2012%20c%20164%20§%20503[2012 c 164 § 503]; 2012 c 1 § 101 (Initiative Measure No. 1163, approved November 8, 2011); ]

== 74.39A.060 - Toll-free telephone number for complaints—Investigation and referral—Rules—Discrimination or retaliation prohibited.
. The aging and long-term support administration of the department shall establish and maintain a toll-free telephone number for receiving complaints regarding facilities and community residential services businesses as defined in this chapter.

. Each facility shall post in a place and manner clearly visible to residents and visitors the department's toll-free complaint telephone number and the toll-free number and program description of the long-term care ombuds as required by RCW 43.190.050.

. The aging and long-term support administration shall investigate complaints it receives about facilities and community residential services businesses unless the department determines that: (a) The complaint is intended to willfully harass the provider or the provider's employee; or (b) there is no reasonable basis for investigation; or (c) corrective action has been taken as determined by the ombuds or the department.

. The aging and long-term support administration shall refer complaints to appropriate state agencies, law enforcement agencies, the attorney general, the long-term care ombuds, or other entities if the department lacks authority to investigate or if its investigation reveals that a follow-up referral to one or more of these entities is appropriate.

. The department shall adopt rules that include the following complaint investigation protocols:

.. Upon receipt of a complaint, the department shall make a preliminary review of the complaint, assess the severity of the complaint, and assign an appropriate response time. Complaints involving imminent danger to the health, safety, or well-being of a resident must be responded to within two days. When appropriate, the department shall make an on-site investigation within a reasonable time after receipt of the complaint or otherwise ensure that complaints are responded to.

.. The complainant must be: Promptly contacted by the department, unless anonymous or unavailable despite several attempts by the department, and informed of the right to discuss the alleged violations with the inspector and to provide other information the complainant believes will assist the inspector; informed of the department's course of action; and informed of the right to receive a written copy of the investigation report.

.. In conducting the investigation, the department shall interview the complainant, unless anonymous, and shall use its best efforts to interview the vulnerable adult or adults allegedly harmed, and, consistent with the protection of the vulnerable adult shall interview facility staff, any available independent sources of relevant information, including if appropriate the family members of the vulnerable adult.

.. Substantiated complaints involving harm to a resident, if an applicable law or rule has been violated, shall be subject to one or more of the actions provided in RCW 74.39A.080 or 70.128.160. Whenever appropriate, the department shall also give consultation and technical assistance to the provider.

.. After a department finding of a violation for which a stop placement has been imposed, the department shall make an on-site revisit of the provider within fifteen working days from the request for revisit, to ensure correction of the violation. For violations that are serious or recurring or uncorrected following a previous citation, and create actual or threatened harm to one or more residents' well-being, including violations of residents' rights, the department shall make an on-site revisit as soon as appropriate to ensure correction of the violation. Verification of correction of all other violations may be made by either a department on-site revisit or by written or photographic documentation found by the department to be credible. This subsection does not prevent the department from enforcing license or contract suspensions or revocations. Nothing in this subsection shall interfere with or diminish the department's authority and duty to ensure that the provider adequately cares for residents, including to make departmental on-site revisits as needed to ensure that the provider protects residents and to enforce compliance with this chapter.

.. Substantiated complaints of neglect, abuse, exploitation, or abandonment of residents, or suspected criminal violations, shall also be referred by the department to the appropriate law enforcement agencies, the attorney general, and appropriate professional disciplining authority.

. The department may provide the substance of the complaint to the licensee or contractor before the completion of the investigation by the department unless such disclosure would reveal the identity of a complainant, witness, or resident who chooses to remain anonymous. Neither the substance of the complaint provided to the licensee or contractor nor any copy of the complaint or related report published, released, or made otherwise available shall disclose, or reasonably lead to the disclosure of, the name, title, or identity of any complainant, or other person mentioned in the complaint, except that the name of the provider and the name or names of any officer, employee, or agent of the department conducting the investigation shall be disclosed after the investigation has been closed and the complaint has been substantiated. The department may disclose the identity of the complainant if such disclosure is requested in writing by the complainant. Nothing in this subsection shall be construed to interfere with the obligation of the long-term care ombuds program or department staff to monitor the department's licensing, contract, and complaint investigation files for long-term care facilities.

. The resident has the right to be free of interference, coercion, discrimination, and reprisal from a facility in exercising his or her rights, including the right to voice grievances about treatment furnished or not furnished. A facility that provides long-term care services shall not discriminate or retaliate in any manner against a resident, employee, or any other person on the basis or for the reason that such resident or any other person made a complaint to the department, the attorney general, law enforcement agencies, or the long-term care ombuds, provided information, or otherwise cooperated with the investigation of such a complaint. Any attempt to discharge a resident against the resident's wishes, or any type of retaliatory treatment of a resident by whom or upon whose behalf a complaint substantiated by the department has been made to the department, the attorney general, law enforcement agencies, or the long-term care ombuds, within one year of the filing of the complaint, raises a rebuttable presumption that such action was in retaliation for the filing of the complaint. "Retaliatory treatment" means, but is not limited to, monitoring a resident's phone, mail, or visits; involuntary seclusion or isolation; transferring a resident to a different room unless requested or based upon legitimate management reasons; withholding or threatening to withhold food or treatment unless authorized by a terminally ill resident or his or her representative pursuant to law; or persistently delaying responses to a resident's request for service or assistance. A facility that provides long-term care services shall not willfully interfere with the performance of official duties by a long-term care ombuds. The department shall sanction and may impose a civil penalty of not more than three thousand dollars for a violation of this subsection.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6199-S.SL.pdf?cite=2018%20c%20278%20§%209[2018 c 278 § 9]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20227[2013 c 23 § 227]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2041-S.SL.pdf?cite=2001%20c%20193%20§%201[2001 c 193 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1620-S.SL.pdf?cite=1999%20c%20176%20§%2034[1999 c 176 § 34]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1850-S2.SL.pdf?cite=1997%20c%20392%20§%20210[1997 c 392 § 210]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1908-S2.SL.pdf?cite=1995%201st%20sp.s.%20c%2018%20§%2013[1995 1st sp.s. c 18 § 13]; ]

== 74.39A.070 - Rules for qualifications and training requirements—Requirement that contractors comply with federal and state regulations.
. The department shall, by rule, establish reasonable minimum qualifications and training requirements to assure that assisted living service, enhanced adult residential care service, and adult residential care providers with whom the department contracts are capable of providing services consistent with this chapter. The rules shall apply only to residential capacity for which the state contracts.

. The department shall not contract for assisted living, enhanced adult residential care, or adult residential care services with a provider if the department finds that the provider or any partner, officer, director, managerial employee, or owner of five percent or more of the provider has a history of significant noncompliance with federal or state regulations, rules, or laws in providing care or services to vulnerable adults or to children.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1908-S2.SL.pdf?cite=1995%201st%20sp.s.%20c%2018%20§%2016[1995 1st sp.s. c 18 § 16]; ]

== 74.39A.074 - Training requirements for long-term care workers.
. [Empty]
.. Except for long-term care workers exempt from certification under RCW 18.88B.041(1)(a), all persons hired as long-term care workers must meet the minimum training requirements in this section within one hundred twenty calendar days after the date of being hired.

.. Except as provided in RCW 74.39A.076, the minimum training requirement is seventy-five hours of entry-level training approved by the department. A long-term care worker must successfully complete five of these seventy-five hours before being eligible to provide care.

.. Training required by (d) of this subsection applies toward the training required under RCW 18.20.270 or 70.128.230 or any statutory or regulatory training requirements for long-term care workers employed by community residential service businesses.

.. The seventy-five hours of entry-level training required shall be as follows:

... Before a long-term care worker is eligible to provide care, he or she must complete:

(A) Two hours of orientation training regarding his or her role as caregiver and the applicable terms of employment; and

(B) Three hours of safety training, including basic safety precautions, emergency procedures, and infection control; and

... Seventy hours of long-term care basic training, including training related to:

(A) Core competencies; and

(B) Population specific competencies, including identification of individuals with potential hearing loss and how to seek assistance if hearing loss is suspected.

. Only training curriculum approved by the department may be used to fulfill the training requirements specified in this section. The department shall only approve training curriculum that:

.. Has been developed with input from consumer and worker representatives; and

.. Requires comprehensive instruction by qualified instructors on the competencies and training topics in this section.

. Individual providers under RCW 74.39A.270 shall be compensated for training time required by this section.

. The department shall adopt rules to implement this section.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5177.SL.pdf?cite=2017%20c%20216%20§%201[2017 c 216 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2314-S.SL.pdf?cite=2012%20c%20164%20§%20401[2012 c 164 § 401]; 2012 c 1 § 107 (Initiative Measure No. 1163, approved November 8, 2011); ]

== 74.39A.076 - Training requirements for individual providers caring for family members.
. Beginning January 7, 2012, except for long-term care workers exempt from certification under RCW 18.88B.041(1)(a):

.. A biological, step, or adoptive parent who is the individual provider only for the person's developmentally disabled son or daughter must receive twelve hours of training relevant to the needs of adults with developmental disabilities within the first one hundred twenty days after becoming an individual provider.

.. A spouse or registered domestic partner who is a long-term care worker only for a spouse or domestic partner, pursuant to the long-term services and supports trust program established in chapter 50B.04 RCW, must receive fifteen hours of basic training, and at least six hours of additional focused training based on the care-receiving spouse's or partner's needs, within the first one hundred twenty days after becoming a long-term care worker.

.. A person working as an individual provider who (i) provides respite care services only for individuals with developmental disabilities receiving services under Title 71A RCW or only for individuals who receive services under this chapter, and (ii) works three hundred hours or less in any calendar year, must complete fourteen hours of training within the first one hundred twenty days after becoming an individual provider. Five of the fourteen hours must be completed before becoming eligible to provide care, including two hours of orientation training regarding the caregiving role and terms of employment and three hours of safety training. The training partnership identified in RCW 74.39A.360 must offer at least twelve of the fourteen hours online, and five of those online hours must be individually selected from elective courses.

.. Individual providers identified in (d)(i) or (ii) of this subsection must complete thirty-five hours of training within the first one hundred twenty days after becoming an individual provider. Five of the thirty-five hours must be completed before becoming eligible to provide care. Two of these five hours shall be devoted to an orientation training regarding an individual provider's role as caregiver and the applicable terms of employment, and three hours shall be devoted to safety training, including basic safety precautions, emergency procedures, and infection control. Individual providers subject to this requirement include:

... An individual provider caring only for the individual provider's biological, step, or adoptive child or parent unless covered by (a) of this subsection; and

... A person working as an individual provider who provides twenty hours or less of care for one person in any calendar month.

. In computing the time periods in this section, the first day is the date of hire.

. Only training curriculum approved by the department may be used to fulfill the training requirements specified in this section. The department shall only approve training curriculum that:

.. Has been developed with input from consumer and worker representatives; and

.. Requires comprehensive instruction by qualified instructors.

. The department shall adopt rules to implement this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1087-S2.SL.pdf?cite=2019%20c%20363%20§%2019[2019 c 363 § 19]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2435.SL.pdf?cite=2018%20c%20220%20§%201[2018 c 220 § 1]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1322.SL.pdf?cite=2017%20c%20267%20§%201[2017 c 267 § 1]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1531.SL.pdf?cite=2015%20c%20152%20§%202[2015 c 152 § 2]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6387-S.SL.pdf?cite=2014%20c%20139%20§%207[2014 c 139 § 7]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2314-S.SL.pdf?cite=2012%20c%20164%20§%20402[2012 c 164 § 402]; 2012 c 1 § 108 (Initiative Measure No. 1163, approved November 8, 2011); ]

== 74.39A.078 - Rules for the approval of curricula for facility-based caregivers serving persons with behavioral health needs and geriatric behavioral health workers—Curricula requirements.
The department shall adopt rules to establish minimum competencies and standards for the approval of curricula for facility-based caregivers serving persons with behavioral health needs and geriatric behavioral health workers. The curricula must include at least thirty hours of training specific to the diagnosis, care, and crisis management of residents with a mental health disorder, traumatic brain injury, or dementia. The curricula must be outcome-based, and the effectiveness measured by demonstrated competency in the core specialty areas through the use of a competency test.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1548-S.SL.pdf?cite=2017%20c%20200%20§%201[2017 c 200 § 1]; ]

== 74.39A.080 - Department authority to take actions in response to noncompliance or violations.
. The department is authorized to take one or more of the actions listed in subsection (2) of this section in any case in which the department finds that a provider of assisted living services, adult residential care services, or enhanced adult residential care services has:

.. Failed or refused to comply with the requirements of this chapter or the rules adopted under this chapter;

.. Operated without a license or under a revoked license;

.. Knowingly, or with reason to know, made a false statement of material fact on his or her application for license or any data attached thereto, or in any matter under investigation by the department; or

.. Willfully prevented or interfered with any inspection or investigation by the department.

. When authorized by subsection (1) of this section, the department may take one or more of the following actions:

.. Refuse to issue a contract;

.. Impose reasonable conditions on a contract, such as correction within a specified time, training, and limits on the type of clients the provider may admit or serve;

.. Impose civil penalties of not more than one hundred dollars per day per violation;

.. Suspend, revoke, or refuse to renew a contract; or

.. Suspend admissions to the facility by imposing stop placement on contracted services.

. When the department orders stop placement, the facility shall not admit any person admitted by contract until the stop placement order is terminated. The department may approve readmission of a resident to the facility from a hospital or nursing home during the stop placement. The department shall terminate the stop placement when: (a) The violations necessitating the stop placement have been corrected; and (b) the provider exhibits the capacity to maintain correction of the violations previously found deficient. However, if upon the revisit the department finds new violations that the department reasonably believes will result in a new stop placement, the previous stop placement shall remain in effect until the new stop placement is imposed.

After a department finding of a violation for which a stop placement has been imposed, the department shall make an on-site revisit of the provider within fifteen working days from the request for revisit, to ensure correction of the violation. For violations that are serious or recurring or uncorrected following a previous citation, and create actual or threatened harm to one or more residents' well-being, including violations of residents' rights, the department shall make an on-site revisit as soon as appropriate to ensure correction of the violation. Verification of correction of all other violations may be made by either a department on-site revisit or by written or photographic documentation found by the department to be credible. This subsection does not prevent the department from enforcing license suspensions or revocations. Nothing in this subsection shall interfere with or diminish the department's authority and duty to ensure that the provider adequately cares for residents, including to make departmental on-site revisits as needed to ensure that the provider protects residents, and to enforce compliance with this chapter.

. Chapter 34.05 RCW applies to department actions under this section, except that orders of the department imposing contracts suspension, stop placement, or conditions for continuation of a contract are effective immediately upon notice and shall continue pending any hearing.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2041-S.SL.pdf?cite=2001%20c%20193%20§%203[2001 c 193 § 3]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2172.SL.pdf?cite=1996%20c%20193%20§%201[1996 c 193 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1908-S2.SL.pdf?cite=1995%201st%20sp.s.%20c%2018%20§%2017[1995 1st sp.s. c 18 § 17]; ]

== 74.39A.086 - Enforcement actions against persons not certified as home care aides and their employers—Rule-making authority.
. The department shall take appropriate enforcement action related to the contract of a consumer directed employer or a licensed or certified private agency or facility that provides long-term care services and knowingly employs a long-term care worker who is not a certified home care aide as required under chapter 18.88B RCW or, if exempted from certification under RCW 18.88B.041, who has not completed his or her required training under RCW 74.39A.074.

. The department shall deny payment to individual providers who provided services under a contract with the department if they have been notified that they are no longer permitted to work because they:

.. Were not certified as home care aides as required under chapter 18.88B RCW; or

.. Had not completed the training required under RCW 74.39A.074.

. The department may terminate the contract of any individual provider under contract with the department who:

.. Is not certified as a home care aide as required under chapter 18.88B RCW; or

.. Has not completed the training required under RCW 74.39A.074.

. Chapter 34.05 RCW shall govern actions by the department under this section.

. The department shall adopt rules to implement this section.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6199-S.SL.pdf?cite=2018%20c%20278%20§%2010[2018 c 278 § 10]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2314-S.SL.pdf?cite=2012%20c%20164%20§%20602[2012 c 164 § 602]; 2012 c 1 § 109 (Initiative Measure No. 1163, approved November 8, 2011); ]

== 74.39A.090 - Discharge planning—Contracts for case management services and reassessment and reauthorization—Assessment of case management roles and quality of in-home care services—Plan of care model language.
. Discharge planning, as directed in this section, is intended for residents and patients identified for discharge to long-term services under RCW 70.41.320, 74.39A.040, or 74.42.058. The purpose of discharge planning is to protect residents and patients from the financial incentives inherent in keeping residents or patients in a more expensive higher level of care and shall focus on care options that are in the best interest of the patient or resident.

. The department shall, consistent with the intent of this section, contract with area agencies on aging:

.. To provide case management services to consumers receiving home and community services in their own home; and

.. To reassess and reauthorize home and community services in home or in other settings for consumers:

... Who have been initially authorized by the department to receive home and community services; and

... Who, at the time of reassessment and reauthorization, are receiving home and community services in their own home.

. In the event that an area agency on aging is unwilling to enter into or satisfactorily fulfill a contract or an individual consumer's need for case management services will be met through an alternative delivery system, the department is authorized to:

.. Obtain the services through competitive bid; and

.. Provide the services directly until a qualified contractor can be found.

. [Empty]
.. The department shall include, in its oversight and monitoring of area agency on aging performance, assessment of case management roles undertaken by area agencies on aging in this section. The scope of oversight and monitoring includes, but is not limited to, assessing the degree and quality of the case management performed by area agency on aging staff for elderly and persons with disabilities in the community.

.. The department shall incorporate the expected outcomes and criteria to measure the performance of service coordination organizations into contracts with area agencies on aging as provided in chapter 70.320 RCW.

. Area agencies on aging shall assess the quality of the in-home care services provided to consumers who are receiving services under programs authorized through the medicaid state plan, medicaid waiver authorities, or similar state-funded in-home care programs through an individual provider or home care agency. Quality indicators may include, but are not limited to, home care consumers satisfaction surveys, how quickly home care consumers are linked with home care workers, and whether the plan of care under RCW 74.39A.095 has been honored by the agency or the individual provider.

. The department shall develop model language for the plan of care established in RCW 74.39A.095. The plan of care shall be in clear language, and written at a reading level that will ensure the ability of consumers to understand the rights and responsibilities expressed in the plan of care.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6199-S.SL.pdf?cite=2018%20c%20278%20§%2011[2018 c 278 § 11]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1519-S.SL.pdf?cite=2013%20c%20320%20§%2010[2013 c 320 § 10]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5732-S.SL.pdf?cite=2004%20c%20141%20§%203[2004 c 141 § 3]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1546-S2.SL.pdf?cite=1999%20c%20175%20§%202[1999 c 175 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1908-S2.SL.pdf?cite=1995%201st%20sp.s.%20c%2018%20§%2038[1995 1st sp.s. c 18 § 38]; ]

== 74.39A.095 - Case management services—Duties of the area agencies on aging—Consumers' plans of care—Notification to consumer directed employer.
. In carrying out case management responsibilities established under RCW 74.39A.090 for consumers who are receiving services under programs authorized through the medicaid state plan, medicaid waiver authorities, or similar state-funded in-home care programs, to the extent of available funding, each area agency on aging shall:

.. Work with each client to develop a plan of care under this section that identifies and ensures coordination of health and long-term care services and supports. In developing the plan, the area agency on aging shall use and modify as needed any comprehensive plan of care developed by the department as provided in RCW 74.39A.040;

.. Monitor the implementation of the consumer's plan of care to verify that it adequately meets the needs of the consumer through activities such as home visits, telephone contacts, and responses to information received by the area agency on aging indicating that a consumer may be experiencing problems relating to his or her home care;

.. Reassess and reauthorize services;

.. Explain to the consumer that consumers have the right to waive case management services offered by the area agency on aging, except consumers may not waive the area agency on aging's reassessment or reauthorization of services, or verification that services are being provided in accordance with the plan of care; and

.. Document the waiver of any case management services by the consumer.

. Each consumer has the right to direct and participate in the development of their plan of care to the maximum extent practicable, and to be provided with the time and support necessary to facilitate that participation.

. As authorized by the consumer, a copy of the plan of care may be distributed to: (a) The consumer's individual provider contracted with the department; (b) the entity contracted with the department to provide personal care services; and (c) other relevant providers with whom the consumer has frequent contact.

. If an individual provider is employed by a consumer directed employer, the department or area agency on aging must notify the consumer directed employer if:

.. There is reason to believe that an individual provider or prospective individual provider is not delivering or will not be able to deliver the services identified in the consumer's plan of care; or

.. The individual provider's performance is jeopardizing the health, safety, or well-being of a consumer receiving services under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6199-S.SL.pdf?cite=2018%20c%20278%20§%2012[2018 c 278 § 12]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6453-S.SL.pdf?cite=2014%20c%2040%20§%201[2014 c 40 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2314-S.SL.pdf?cite=2012%20c%20164%20§%20507[2012 c 164 § 507]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1548-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2031%20§%2014[2011 1st sp.s. c 31 § 14]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1371-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2021%20§%205[2011 1st sp.s. c 21 § 5]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6180-S.SL.pdf?cite=2009%20c%20580%20§%208[2009 c 580 § 8]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5732-S.SL.pdf?cite=2004%20c%20141%20§%201[2004 c 141 § 1]; 2002 c 3 § 11 (Initiative Measure No. 775, approved November 6, 2001); http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2637-S2.SL.pdf?cite=2000%20c%2087%20§%205[2000 c 87 § 5]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1546-S2.SL.pdf?cite=1999%20c%20175%20§%203[1999 c 175 § 3]; ]

== 74.39A.100 - Chore services—Legislative finding, intent.
The legislature finds that it is desirable to provide a coordinated and comprehensive program of in-home services for certain citizens in order that such persons may remain in their own homes, obtain employment if possible, and maintain a closer contact with the community. Such a program will seek to prevent mental and psychological deterioration which our citizens might otherwise experience. The legislature intends that the services will be provided in a fashion which promotes independent living.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c137.pdf?cite=1980%20c%20137%20§%201[1980 c 137 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c51.pdf?cite=1973%201st%20ex.s.%20c%2051%20§%201[1973 1st ex.s. c 51 § 1]; ]

== 74.39A.110 - Chore services—Legislative policy and intent regarding available funds—Levels of service.
It is the intent of the legislature that chore services be provided to eligible persons within the limits of funds appropriated for that purpose. Therefore, the department shall provide services only to those persons identified as at risk of being placed in a long-term care facility in the absence of such services. The department shall not provide chore services to any individual who is eligible for, and whose needs can be met by another community service administered by the department. Chore services shall be provided to the extent necessary to maintain a safe and healthful living environment. It is the policy of the state to encourage the development of volunteer chore services in local communities as a means of meeting chore care service needs and directing financial resources. In determining eligibility for chore services, the department shall consider the following:

. The kind of services needed;

. The degree of service need, and the extent to which an individual is dependent upon such services to remain in his or her home or return to his or her home;

. The availability of personal or community resources which may be utilized to meet the individual's need; and

. Such other factors as the department considers necessary to insure service is provided only to those persons whose chore service needs cannot be met by relatives, friends, nonprofit organizations, other persons, or by other programs or resources.

In determining the level of services to be provided under this chapter, the client shall be assessed using an instrument designed by the department to determine the level of functional disability, the need for service and the person's risk of long-term care facility placement.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1908-S2.SL.pdf?cite=1995%201st%20sp.s.%20c%2018%20§%2036[1995 1st sp.s. c 18 § 36]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c427.pdf?cite=1989%20c%20427%20§%205[1989 c 427 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981ex1c6.pdf?cite=1981%201st%20ex.s.%20c%206%20§%2016[1981 1st ex.s. c 6 § 16]; ]

== 74.39A.120 - Chore services—Expenditure limitation—Priorities—Rule on patient resource limit.
. The department shall establish a monthly dollar lid for each region on chore services expenditures within the legislative appropriation. Priority for services shall be given to the following situations:

.. People who were receiving chore personal care services as of June 30, 1995;

.. People for whom chore personal care services are necessary to return to the community from a nursing home;

.. People for whom chore personal care services are necessary to prevent unnecessary nursing home placement; and

.. People for whom chore personal care services are necessary as a protective measure based on referrals resulting from an adult protective services investigation.

. The department shall require a client to participate in the cost of chore services as a necessary precondition to receiving chore services paid for by the state. The client shall retain an amount equal to one hundred percent of the federal poverty level, adjusted for household size, for maintenance needs. The department shall consider the remaining income as the client participation amount for chore services except for those persons whose participation is established under *RCW 74.08.570.

. The department shall establish, by rule, the maximum amount of resources a person may retain and be eligible for chore services.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1908-S2.SL.pdf?cite=1995%201st%20sp.s.%20c%2018%20§%2037[1995 1st sp.s. c 18 § 37]; ]

== 74.39A.130 - Chore services—Department to develop program.
. The department is authorized to develop a program to provide for chore services under this chapter.

. The department may provide assistance in the recruiting of providers of the services enumerated in RCW 74.39A.120 and seek to assure the timely provision of services in emergency situations.

. The department shall assure that all providers of the chore services under this chapter are compensated for the delivery of the services on a prompt and regular basis.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1908-S2.SL.pdf?cite=1995%201st%20sp.s.%20c%2018%20§%2040[1995 1st sp.s. c 18 § 40]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c427.pdf?cite=1989%20c%20427%20§%206[1989 c 427 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c3.pdf?cite=1983%20c%203%20§%20189[1983 c 3 § 189]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c137.pdf?cite=1980%20c%20137%20§%202[1980 c 137 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c51.pdf?cite=1973%201st%20ex.s.%20c%2051%20§%203[1973 1st ex.s. c 51 § 3]; ]

== 74.39A.140 - Chore services—Employment of public assistance recipients.
In developing the program set forth in *RCW 74.08.550, the department shall, to the extent possible, and consistent with federal law, enlist the services of persons receiving grants under the provisions of chapter 74.08 RCW and chapter 74.12 RCW to carry out the services enumerated under **RCW 74.08.541. To this end, the department shall establish appropriate rules and regulations designed to determine eligibility for employment under this section, as well as regulations designed to notify persons receiving such grants of eligibility for such employment. The department shall further establish a system of compensation to persons employed under the provisions of this section which provides that any grants they receive under chapter 74.08 RCW or chapter 74.12 RCW shall be diminished by such percentage of the compensation received under this section as the department shall establish by rules and regulations.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c3.pdf?cite=1983%20c%203%20§%20190[1983 c 3 § 190]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c51.pdf?cite=1973%201st%20ex.s.%20c%2051%20§%204[1973 1st ex.s. c 51 § 4]; ]

== 74.39A.150 - Chore services for persons with disabilities—Eligibility.
. An otherwise eligible disabled person shall not be deemed ineligible for chore services under this chapter if the person's gross income from employment, adjusted downward by the cost of the chore services to be provided and the disabled person's work expenses, does not exceed the maximum eligibility standard established by the department for such chore services. The department shall establish a methodology for client participation that allows such disabled persons to be employed.

. If a disabled person arranges for chore services through an individual provider arrangement, the client's contribution shall be counted as first dollar toward the total amount owed to the provider for chore services rendered.

. As used in this section:

.. "Gross income" means total earned wages, commissions, salary, and any bonus;

.. "Work expenses" includes:

... Payroll deductions required by law or as a condition of employment, in amounts actually withheld;

... The necessary cost of transportation to and from the place of employment by the most economical means, except rental cars; and

... Expenses of employment necessary for continued employment, such as tools, materials, union dues, transportation to service customers if not furnished by the employer, and uniforms and clothing needed on the job and not suitable for wear away from the job;

.. "Employment" means any work activity for which a recipient receives monetary compensation;

.. " Disabled" means:

... Permanently and totally disabled as defined by the department and as such definition is approved by the federal social security administration for federal matching funds;

... Eighteen years of age or older;

... A resident of the state of Washington; and

... Willing to submit to such examinations as are deemed necessary by the department to establish the extent and nature of the disability.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1908-S2.SL.pdf?cite=1995%201st%20sp.s.%20c%2018%20§%2041[1995 1st sp.s. c 18 § 41]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c427.pdf?cite=1989%20c%20427%20§%207[1989 c 427 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c137.pdf?cite=1980%20c%20137%20§%203[1980 c 137 § 3]; ]

== 74.39A.155 - Support for persons at risk of institutional placement.
Within funds appropriated for this purpose, the department shall provide additional support for residents in community settings who exhibit challenging behaviors that put them at risk for institutional placement. The residents must be receiving services under programs authorized through the medicaid state plan, medicaid waiver authorities, or similar state-funded in-home care programs, and must have been evaluated under the individual comprehensive assessment reporting and evaluation process.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6199-S.SL.pdf?cite=2018%20c%20278%20§%2014[2018 c 278 § 14]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2668-S2.SL.pdf?cite=2008%20c%20146%20§%208[2008 c 146 § 8]; ]

== 74.39A.160 - Transfer of assets—Penalties.
. A person who receives an asset from an applicant for or recipient of long-term care services for less than fair market value shall be subject to a civil fine payable to the department if:

.. The applicant for or recipient of long-term care services transferred the asset for the purpose of qualifying for state or federal coverage for long-term care services and the person who received the asset was aware, or should have been aware, of this purpose;

.. Such transfer establishes a period of ineligibility for such service under state or federal laws or regulations; and

.. The department provides coverage for such services during the period of ineligibility because the failure to provide such coverage would result in an undue hardship for the applicant or recipient.

. The civil fine imposed under this section shall be imposed in a judicial proceeding initiated by the department and shall equal (a) up to one hundred fifty percent of the amount the department expends for the care of the applicant or recipient during the period of ineligibility attributable to the amount transferred to the person subject to the civil fine plus (b) the department's court costs and legal fees.

. Transfers subject to a civil fine under this section shall be considered null and void and a fraudulent conveyance as to the department. The department shall have the right to petition a court to set aside such transfers and require all assets transferred returned to the applicant or recipient.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1908-S2.SL.pdf?cite=1995%201st%20sp.s.%20c%2018%20§%2055[1995 1st sp.s. c 18 § 55]; ]

== 74.39A.170 - Recovery of payments—Transfer of assets rules for eligibility—Disclosure of estate recovery costs, terms, and conditions.
. All payments made in state-funded long-term care shall be recoverable as if they were medical assistance payments subject to recovery under 42 U.S.C. Sec. 1396p and chapter 43.20B RCW, but without regard to the recipient's age.

. In determining eligibility for state-funded long-term care services programs, the department shall impose the same rules with respect to the transfer of assets for less than fair market value as are imposed under 42 U.S.C. 1396p with respect to nursing home and home and community services.

. It is the responsibility of the department to fully disclose in advance verbally and in writing, in easy to understand language, the terms and conditions of estate recovery to all persons offered long-term care services subject to recovery of payments.

. In disclosing estate recovery costs to potential clients, and to family members at the consent of the client, the department shall provide a written description of the community service options.

. The department of social and health services shall develop an implementation plan for notifying the client or his or her legal representative at least quarterly of the types of services used and the cost of those services (debt) that will be charged against the estate. The estate planning implementation plan shall be submitted by December 12, 1999, to the appropriate standing committees of the house of representatives and the senate, and to the joint legislative and executive task force on long-term care.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1116-S2.SL.pdf?cite=1999%20c%20354%20§%201[1999 c 354 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1908-S2.SL.pdf?cite=1995%201st%20sp.s.%20c%2018%20§%2056[1995 1st sp.s. c 18 § 56]; ]

== 74.39A.180 - Authority to pay for probate actions and collection of bad debts.
Notwithstanding any other provision of law:

. In order to facilitate and ensure compliance with the federal social security act, Title XIX, as now existing or hereafter amended, later enactment to be adopted by reference by the director by rule, and other state laws mandating recovery of assets from estates of persons receiving long-term care services, the secretary of the department, with the approval of the office of the attorney general, may pay the reasonable and proper fees of attorneys admitted to practice before courts of this state, and associated professionals such as guardians, who are engaged in probate practice for the purpose of maintaining actions under Title 11 RCW, to the end that assets are not wasted, but are rather collected and preserved, and used for the care of the client or the reimbursement of the department pursuant to this chapter or chapter 43.20B RCW.

. The department may hire such other agencies and professionals on a contingency basis or otherwise as are necessary and cost-effective to collect bad debts owed to the department for long-term care services.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1908-S2.SL.pdf?cite=1995%201st%20sp.s.%20c%2018%20§%2057[1995 1st sp.s. c 18 § 57]; ]

== 74.39A.200 - Training curricula, materials—In public domain—Exceptions.
All training curricula and material, except competency testing material, developed by or for the department and used in part or in whole for the purpose of improving provider and caregiver knowledge and skill are in the public domain unless otherwise protected by copyright law and are subject to disclosure under chapter 42.56 RCW. Any training curricula and material developed by a private entity through a contract with the department are also considered part of the public domain and shall be shared subject to copyright restrictions. Any proprietary curricula and material developed by a private entity for the purposes of training staff in facilities licensed under chapter 18.20 or 70.128 RCW or individual providers and home care agency providers under this chapter and approved for training by the department are not part of the public domain.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1133-S.SL.pdf?cite=2005%20c%20274%20§%20355[2005 c 274 § 355]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6502-S.SL.pdf?cite=2000%20c%20121%20§%2011[2000 c 121 § 11]; ]

== 74.39A.210 - Disclosure of employee information—Employer immunity—Rebuttable presumption.
An employer providing home and community services, including facilities licensed under chapters 18.51, 18.20, 70.97, and 70.128 RCW, an employer of a program operating under RCW 71A.12.040(10), a consumer directed employer, or an in-home services agency employer licensed under chapter 70.127 RCW, who discloses information about a former or current employee to a prospective home and community services employer, nursing home employer, consumer directed employer, or in-home services agency employer, is presumed to be acting in good faith and is immune from civil and criminal liability for such disclosure or its consequences if the disclosed information relates to: (1) The employee's ability to perform his or her job; (2) the diligence, skill, or reliability with which the employee carried out the duties of his or her job; or (3) any illegal or wrongful act committed by the employee when related to his or her ability to care for a vulnerable adult. For purposes of this section, the presumption of good faith may only be rebutted upon a showing by clear and convincing evidence that the information disclosed by the employer was knowingly false or made with reckless disregard for the truth of the information disclosed. If the employee successfully rebuts the presumption of good faith standard in a court of competent jurisdiction, as the prevailing party, the employee shall be entitled to recover reasonable attorneys' fees against the employer. Nothing in this section shall affect or limit any other state, federal, or constitutional right otherwise available.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6199-S.SL.pdf?cite=2018%20c%20278%20§%2015[2018 c 278 § 15]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1320-S.SL.pdf?cite=2001%20c%20319%20§%2013[2001 c 319 § 13]; ]

== 74.39A.240 - Definitions.
The definitions in this section apply throughout RCW 74.39A.030, 74.39A.095, * 74.39A.220 through 74.39A.300, and 41.56.026 unless the context clearly requires otherwise.

. "Consumer" means a person to whom an individual provider provides any such services.

. "Department" means the department of social and health services.

. "Individual provider" means a person, including a personal aide, who, under an individual provider contract with the department or as an employee of a consumer directed employer, provides personal care or respite care services to persons who are functionally disabled or otherwise eligible under programs authorized and funded by the medicaid state plan, medicaid waiver programs[,] chapter 71A.12 RCW, RCW 74.13.270, or similar state-funded in-home care programs.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6199-S.SL.pdf?cite=2018%20c%20278%20§%2016[2018 c 278 § 16]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1371-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2021%20§%207[2011 1st sp.s. c 21 § 7]; 2002 c 3 § 3 (Initiative Measure No. 775, approved November 6, 2001); ]

== 74.39A.250 - Individual provider referral registry—Consumer directed employer duties—Department duties.
. If a consumer directed employer employs individual providers, the consumer directed employer shall:

.. Provide assistance to consumers and prospective consumers in finding individual providers and prospective individual providers through the operation of a referral registry of individual providers and prospective individual providers.

.. Before placing an individual provider or prospective individual provider on the referral registry, determine that the individual provider or prospective individual provider:

... Has met the minimum requirements for training under RCW 74.39A.051 and 74.39A.074;

... Has satisfactorily completed a background check within the prior twelve months; and

... Is not listed on any state or federal registry described in RCW 74.39A.056 or on other registries maintained by the department.

.. Remove from the referral registry any individual provider or prospective individual provider who does not meet the qualifications set forth in this subsection (1) or whose employment as an individual provider has been terminated based on good cause.

.. Provide routine, emergency, and respite referrals of individual providers and prospective individual providers to consumers and prospective consumers who are authorized to receive long-term in-home care services through an individual provider.

.. Not allow an individual provider to provide services to a consumer without the consumer's consent.

. The department shall perform the activities under subsection (1) of this section if the department has not transitioned the responsibilities under this section to a consumer directed employer.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6199-S.SL.pdf?cite=2018%20c%20278%20§%2017[2018 c 278 § 17]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2314-S.SL.pdf?cite=2012%20c%20164%20§%20708[2012 c 164 § 708]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1371-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2021%20§%208[2011 1st sp.s. c 21 § 8]; 2002 c 3 § 4 (Initiative Measure No. 775, approved November 6, 2001); ]

== 74.39A.261 - Background checks on individual providers—Department duties.
If the department contracts with individual providers, the department must perform background checks for individual providers and prospective individual providers under RCW 74.39A.056.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6199-S.SL.pdf?cite=2018%20c%20278%20§%2018[2018 c 278 § 18]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2314-S.SL.pdf?cite=2012%20c%20164%20§%20502[2012 c 164 § 502]; 2012 c 1 § 102 (Initiative Measure No. 1163, approved November 8, 2011); ]

== 74.39A.270 - Individual providers contracted with the department—Collective bargaining—Circumstances in which individual providers are considered public employees—Exceptions—Limitations.
The following provisions apply only to individual providers who are contracted with the department to provide personal care or respite care services:

. Solely for the purposes of collective bargaining and as expressly limited under subsections (2) and (3) of this section, the governor is the public employer, as defined in chapter 41.56 RCW, of individual providers, who, solely for the purposes of collective bargaining, are public employees as defined in chapter 41.56 RCW. To accommodate the role of the state as payor for the community-based services provided under this chapter and to ensure coordination with state employee collective bargaining under chapter 41.80 RCW and the coordination necessary to implement RCW 74.39A.300, the public employer shall be represented for bargaining purposes by the governor or the governor's designee appointed under chapter 41.80 RCW. The department shall solicit input from the developmental disabilities council, the governor's committee on disability issues and employment, the state council on aging, and other consumer advocacy organizations to obtain informed input from consumers on their interests, including impacts on consumer choice, for all issues proposed for collective bargaining under subsections (5) and (7) of this section.

. Chapter 41.56 RCW governs the collective bargaining relationship between the governor and individual providers, except as otherwise expressly provided in this chapter and except as follows:

.. The only unit appropriate for the purpose of collective bargaining under RCW 41.56.060 is a statewide unit of all individual providers;

.. The showing of interest required to request an election under RCW 41.56.060 is ten percent of the unit, and any intervener seeking to appear on the ballot must make the same showing of interest;

.. The mediation and interest arbitration provisions of RCW 41.56.430 through 41.56.470 and 41.56.480 apply, except that:

... With respect to commencement of negotiations between the governor and the bargaining representative of individual providers, negotiations shall be commenced by May 1st of any year prior to the year in which an existing collective bargaining agreement expires; and

... The decision of the arbitrator is not binding on the legislature and, if the legislature does not approve the request for funds necessary to implement the compensation and fringe benefit provisions of the arbitrated collective bargaining agreement, is not binding on the authority or the state;

.. Individual providers do not have the right to strike; and

.. Individual providers who are related to, or family members of, consumers or prospective consumers are not, for that reason, exempt from this chapter or chapter 41.56 RCW.

. Individual providers who are public employees solely for the purposes of collective bargaining under subsection (1) of this section are not, for that reason, employees of the state, its political subdivisions, or an area agency on aging for any purpose. Chapter 41.56 RCW applies only to the governance of the collective bargaining relationship between the employer and individual providers as provided in subsections (1) and (2) of this section.

. Consumers and prospective consumers retain the right to select, hire, supervise the work of, and terminate any individual provider providing services to them. Consumers may elect to receive long-term in-home care services from individual providers who are not referred to them by the department or a department contractor.

. Except as expressly limited in this section and RCW 74.39A.300, the wages, hours, and working conditions of individual providers are determined solely through collective bargaining as provided in this chapter. Except as described in RCW 74.39A.525, no agency or department of the state may establish policies or rules governing the wages or hours of individual providers.

. Nothing in this section modifies:

.. The department's authority to deny individual provider contracts to individuals who will not be able to meet the needs of a consumer or to terminate contracts of individual providers who are not adequately meeting the needs of a particular consumer; or

.. The consumer's right to: (i) Assign hours to one or more individual providers consistent with the rules adopted under this chapter and his or her plan of care; and (ii) select, hire, terminate, supervise the work of, and determine the conditions of employment for each individual provider providing services to the consumer under this chapter.

. At the request of the exclusive bargaining representative, the governor or the governor's designee appointed under chapter 41.80 RCW shall engage in collective bargaining, as defined in RCW 41.56.030(4), with the exclusive bargaining representative over the following subjects:

.. Employer contributions to the training partnership for the costs of: (i) Meeting all training and peer mentoring requirements under this chapter; and (ii) other training intended to promote the career development of individual providers; and

.. How the department's core responsibility affects hours of work for individual providers; this subsection shall not be interpreted to require collective bargaining over an individual consumer's plan of care.

. The state, the department, the area agencies on aging, or their contractors under this chapter may not be held vicariously or jointly liable for the action or inaction of any individual provider or prospective individual provider, whether or not that individual provider or prospective individual provider was included on the referral registry or referred to a consumer or prospective consumer. The existence of a collective bargaining agreement, the placement of an individual provider on the referral registry, or the development or approval of a plan of care for a consumer who chooses to use the services of an individual provider and the provision of case management services to that consumer, by the department or an area agency on aging, does not constitute a special relationship with the consumer.

. Nothing in this section affects the state's responsibility with respect to unemployment insurance for individual providers. However, individual providers are not to be considered, as a result of the state assuming this responsibility, employees of the state.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6199-S.SL.pdf?cite=2018%20c%20278%20§%2019[2018 c 278 § 19]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5976.SL.pdf?cite=2017%203rd%20sp.s.%20c%2024%20§%201[2017 3rd sp.s. c 24 § 1]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1725-S2.SL.pdf?cite=2016%20sp.s.%20c%2030%20§%201[2016 sp.s. c 30 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1371-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2021%20§%2010[2011 1st sp.s. c 21 § 10]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2284-S2.SL.pdf?cite=2007%20c%20361%20§%207[2007 c 361 § 7]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1916-S.SL.pdf?cite=2007%20c%20278%20§%203[2007 c 278 § 3]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2475-S.SL.pdf?cite=2006%20c%20106%20§%201[2006 c 106 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2933-S.SL.pdf?cite=2004%20c%203%20§%201[2004 c 3 § 1]; 2002 c 3 § 6 (Initiative Measure No. 775, approved November 6, 2001); ]

== 74.39A.275 - Individual provider overtime—Annual expenditure reports to legislature and joint legislative-executive overtime oversight task force.
In order to monitor quality of care and safety of consumers, employment conditions of individual providers, and compliance with the provisions of payment of hours in excess of forty hours each workweek for any single individual provider, the department must provide annual expenditure reports to the legislative fiscal committees and joint legislative-executive overtime oversight task force created under RCW 74.39A.525. The report must contain the following information:

. The number of individual providers receiving payment for more than forty hours in a workweek, specifying how many of those individual providers were eligible for those hours due to meeting the conditions of RCW 74.39A.525.

. The number of hours paid and the amount paid for hours in excess of forty hours in a workweek, specifying how many of those hours and payments were for individual providers eligible for those hours and payments due to meeting the conditions of RCW 74.39A.525 (1) or (2).

. In reporting the information required in subsections (1) and (2) of this section, the department must provide total amounts, averages, and a display of the distribution of the amounts.

. The information required must be provided by department region and county of client, department program, and must be specified for individual providers by the number of clients they serve.

. Any personally identifiable information of consumers and individual providers used to develop this report is confidential under RCW 43.17.410 and exempt from public disclosure, inspection, or copying in accordance with chapter 42.56RCW. However, information may be released in aggregate form, with any personally identifiable information redacted, for the purpose of statistical analysis and oversight of agency performance and actions.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6199-S.SL.pdf?cite=2018%20c%20278%20§%2021[2018 c 278 § 21]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1725-S2.SL.pdf?cite=2016%20sp.s.%20c%2030%20§%203[2016 sp.s. c 30 § 3]; ]

== 74.39A.300 - Funding process—Department-contracted individual providers.
If the department contracts with any individual providers for personal care services, funding will be determined in accordance with the following process:

. Upon meeting the requirements of subsection (2) of this section, the governor must submit, as a part of the proposed biennial or supplemental operating budget submitted to the legislature under RCW 43.88.030, a request for funds necessary to administer in-home care programs under this chapter and to implement the compensation and fringe benefits provisions of a collective bargaining agreement entered into under RCW 74.39A.270 or for legislation necessary to implement such agreement.

. A request for funds necessary to implement the compensation and fringe benefits provisions of a collective bargaining agreement entered into under RCW 74.39A.270 shall not be submitted by the governor to the legislature unless such request:

.. Has been submitted to the director of financial management by October 1st prior to the legislative session at which the request is to be considered; and

.. Has been certified by the director of financial management as being feasible financially for the state or reflects the binding decision of an arbitrator reached under RCW 74.39A.270(2)(c).

. The legislature must approve or reject the submission of the request for funds as a whole. If the legislature rejects or fails to act on the submission, any such agreement will be reopened solely for the purpose of renegotiating the funds necessary to implement the agreement.

. When any increase in individual provider wages or benefits is negotiated or agreed to, no increase in wages or benefits negotiated or agreed to under this chapter will take effect unless and until, before its implementation, the department has determined that the increase is consistent with federal law and federal financial participation in the provision of services under Title XIX of the federal social security act.

. The governor shall periodically consult with the joint committee on employment relations established by RCW 41.80.010 regarding appropriations necessary to implement the compensation and fringe benefits provisions of any collective bargaining agreement and, upon completion of negotiations, advise the committee on the elements of the agreement and on any legislation necessary to implement such agreement.

. After the expiration date of any collective bargaining agreement entered into under RCW 74.39A.270, all of the terms and conditions specified in any such agreement remain in effect until the effective date of a subsequent agreement, not to exceed one year from the expiration date stated in the agreement, except as provided in RCW 74.39A.270.

. If, after the compensation and benefit provisions of an agreement are approved by the legislature, a significant revenue shortfall occurs resulting in reduced appropriations, as declared by proclamation of the governor or by resolution of the legislature, both parties shall immediately enter into collective bargaining for a mutually agreed upon modification of the agreement.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6199-S.SL.pdf?cite=2018%20c%20278%20§%2022[2018 c 278 § 22]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2933-S.SL.pdf?cite=2004%20c%203%20§%202[2004 c 3 § 2]; 2002 c 3 § 9 (Initiative Measure No. 775, approved November 6, 2001); ]

== 74.39A.310 - Contract for individual home care services providers—Cost of change in wages and benefits funded or increase in labor rates.
. The department shall convert and distribute any change in the total amount of wages and benefits negotiated and funded in the contract for individual providers of home care services pursuant to RCW 74.39A.270 and 74.39A.300 or labor rates established under RCW 74.39A.530 into a per-quarter-hour amount. This must be accomplished in each odd-numbered year within sixty days after adjournment sine die of the legislative session.

. The per-quarter-hour amount shall be added to or subtracted from the statewide home care agency vendor rate and any increase shall be used exclusively for improving the wages and benefits of home care agency workers who provide direct care, and for paying any resulting change in required employer contributions or premiums.

. When determining the per-quarter-hour amount, the department must include:

.. The changes to wages, benefits, and compensation negotiated and funded each biennium, including but not limited to:

... Wages;

... Benefit pay, such as vacation, sick, and holiday pay;

... Mileage;

... Contributions to a training partnership;

.. Contributions to the health benefit trust; and

.. Contributions to the defined contribution retirement trust; and

.. The change in the average costs experienced by medicaid contracted home care agencies, as determined by the department in its sole discretion, of employer contributions or premiums required by law including, but not limited to:

... Federal insurance contributions act;

... Federal unemployment tax act;

... State unemployment tax authority;

... State paid family medical leave act; and

.. State workers' compensation system; and

.. An adjustment, as determined by the department in its sole discretion, for cost of compensation for work time that may not be billed as service hours, such as travel time, that must be paid to direct service workers under wage and hour laws and any related employer tax contributions or premiums.

. The portion of the vendor rate calculated for health care benefits, including but not limited to medical, dental, and vision benefits, may only be used for health benefits for home care agency workers who provide direct care.

. When establishing the per-quarter-hour amount, the department must prevent duplicate accounting for the same cost.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2380.SL.pdf?cite=2020%20c%20336%20§%201[2020 c 336 § 1]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6199-S.SL.pdf?cite=2018%20c%20278%20§%2023[2018 c 278 § 23]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2284-S2.SL.pdf?cite=2007%20c%20361%20§%208[2007 c 361 § 8]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2333-S.SL.pdf?cite=2006%20c%209%20§%201[2006 c 9 § 1]; ]

== 74.39A.320 - Establishment of capital add-on rate—Determination of medicaid occupancy percentage.
. To the extent funds are appropriated for this purpose, the department shall establish a capital add-on rate, not less than the July 1, 2005, capital add-on rate established by the department, for those assisted living facilities contracting with the department that have a medicaid occupancy percentage of sixty percent or greater.

. Effective for July 1, 2006, and for each July 1st rate-setting period thereafter, the department shall determine the facility's medicaid occupancy percentage using the last six months' medicaid resident days from the preceding calendar year divided by the product of all its licensed assisted living facility beds irrespective of use, times calendar days for the six-month period. For the purposes of this section, medicaid resident days include those clients who are enrolled in a medicaid managed long-term care program, including but not limited to the program for all inclusive care and the medicaid integration project.

. The medicaid occupancy percentage established beginning on July 1, 2006, and for each July 1st thereafter, shall be used to determine whether an assisted living facility qualifies for the capital add-on rate under this section. Those facilities that qualify for the capital add-on rate shall receive the capital add-on rate throughout the applicable fiscal year.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2056-S.SL.pdf?cite=2012%20c%2010%20§%2067[2012 c 10 § 67]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2925-S.SL.pdf?cite=2006%20c%20260%20§%201[2006 c 260 § 1]; ]

== 74.39A.326 - In-home personal care or respite services to family members—Department not authorized to pay—Exceptions—Enforcement—Rules.
. [Empty]
.. Except as provided under (b) of this subsection, the department shall not pay a home care agency licensed under chapter 70.127 RCW for in-home personal care or respite services provided under this chapter, Title 71A RCW, or chapter 74.39 RCW if the care is provided to a client by a family member of the client. To the extent permitted under federal law, the provisions of this subsection shall not apply if the family member providing care is older than the client.

.. The department may, on a case-by-case basis based on the client's health and safety, make exceptions to (a) of this subsection to authorize payment or to provide for payment during a transition period of up to three months. Within available funds, the restrictions under (a) of this subsection do not apply when the care is provided to: (i) A client who is an enrolled member of a federally recognized Indian tribe; or (ii) a client who resides in the household of an enrolled member of a federally recognized Indian tribe.

. The department shall take appropriate enforcement action against a home care agency found to have charged the state for hours of service for which the department is not authorized to pay under this section, including requiring recoupment of any payment made for those hours and, under criteria adopted by the department by rule, terminating the contract of an agency that violates a recoupment requirement.

. For purposes of this section:

.. "Client" means a person who has been deemed eligible by the department to receive in-home personal care or respite services.

.. "Family member" shall be liberally construed to include, but not be limited to, a parent, child, sibling, aunt, uncle, cousin, grandparent, grandchild, grandniece, or grandnephew, or such relatives when related by marriage.

. The department shall adopt rules to implement this section. The rules shall not result in affecting the amount, duration, or scope of the personal care or respite services benefit to which a client may be entitled pursuant to RCW 74.09.520 or Title XIX of the federal social security act.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5867.SL.pdf?cite=2017%203rd%20sp.s.%20c%2034%20§%203[2017 3rd sp.s. c 34 § 3]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2361-S.SL.pdf?cite=2009%20c%20571%20§%201[2009 c 571 § 1]; ]

== 74.39A.331 - Peer mentoring.
Long-term care workers shall be offered on-the-job training or peer mentorship for at least one hour per week in the first ninety days of work from a long-term care worker who has completed at least twelve hours of mentor training and is mentoring no more than ten other workers at any given time. This requirement applies to long-term care workers who begin work on or after July 1, 2012, except that it does not apply to long-term care workers employed by community residential service businesses until January 1, 2016.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2314-S.SL.pdf?cite=2012%20c%20164%20§%20403[2012 c 164 § 403]; 2012 c 1 § 111 (Initiative Measure No. 1163, approved November 8, 2011); ]

== 74.39A.341 - Continuing education requirements for long-term care workers.
. All long-term care workers shall complete twelve hours of continuing education training in advanced training topics each year. This requirement applies beginning July 1, 2012.

. Completion of continuing education as required in this section is a prerequisite to maintaining home care aide certification under chapter 18.88B RCW.

. Unless voluntarily certified as a home care aide under chapter 18.88B RCW, subsection (1) of this section does not apply to:

.. An individual provider caring only for his or her biological, step, or adoptive child;

.. Registered nurses and licensed practical nurses licensed under chapter 18.79 RCW;

.. Before January 1, 2016, a long-term care worker employed by a community residential service business;

.. A person working as an individual provider who provides twenty hours or less of care for one person in any calendar month; or

.. A person working as an individual provider who only provides respite services and works less than three hundred hours in any calendar year.

. Only training curriculum approved by the department may be used to fulfill the training requirements specified in this section. The department shall only approve training curriculum that:

.. Has been developed with input from consumer and worker representatives; and

.. Requires comprehensive instruction by qualified instructors.

. Individual providers under RCW 74.39A.270 shall be compensated for training time required by this section.

. The department of health shall adopt rules to implement subsection (1) of this section.

. The department shall adopt rules to implement subsection (2) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1531.SL.pdf?cite=2015%20c%20152%20§%203[2015 c 152 § 3]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6387-S.SL.pdf?cite=2014%20c%20139%20§%208[2014 c 139 § 8]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1629-S.SL.pdf?cite=2013%20c%20259%20§%203[2013 c 259 § 3]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2314-S.SL.pdf?cite=2012%20c%20164%20§%20405[2012 c 164 § 405]; 2012 c 1 § 112 (Initiative Measure No. 1163, approved November 8, 2011); ]

== 74.39A.351 - Advanced training.
. The department shall offer, directly or through contract, training opportunities sufficient for a long-term care worker to accumulate seventy hours of training within a reasonable time period. For individual providers represented by an exclusive bargaining representative, the training opportunities shall be offered through the training partnership established under RCW 74.39A.360.

. Training topics offered under this section shall include, but are not limited to: Client rights; personal care; mental illness; dementia; developmental disabilities; depression; medication assistance; advanced communication skills; positive client behavior support; developing or improving client-centered activities; dealing with wandering or aggressive client behaviors; medical conditions; nurse delegation core training; peer mentor training; and advocacy for quality care training.

. The department may not require long-term care workers to obtain the training described in this section.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6199-S.SL.pdf?cite=2018%20c%20278%20§%2024[2018 c 278 § 24]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2314-S.SL.pdf?cite=2012%20c%20164%20§%20404[2012 c 164 § 404]; 2012 c 1 § 113 (Initiative Measure No. 1163, approved November 8, 2011); ]

== 74.39A.360 - Training partnership.
. If the department has any contracts for personal care services with any individual providers represented by an exclusive bargaining representative:

.. All training and peer mentoring required under this chapter shall be provided by a training partnership;

.. Contributions to the partnership shall be made under a collective bargaining agreement negotiated under this chapter;

.. The training partnership shall provide reports as required by the department verifying that all individual providers have complied with all training requirements; and

.. The exclusive bargaining representative shall designate the training partnership.

. When individual providers are employed by a consumer directed employer, funding for training shall be included in the labor rate component paid to the consumer directed employer as determined and funded under RCW 74.39A.530.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6199-S.SL.pdf?cite=2018%20c%20278%20§%2025[2018 c 278 § 25]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2284-S2.SL.pdf?cite=2007%20c%20361%20§%206[2007 c 361 § 6]; ]

== 74.39A.370 - Addressing long-term care complaint workload.
Subject to funding provided for this specific purpose, the department of social and health services shall use additional investigative resources to address a significant growth in the long-term care complaint workload. The department shall use the resulting licensor resources to meet current statutory requirements and timelines. "Complaints," as used in this section, include both complaints about provider practice, under chapters 70.128, 18.20, 18.51, and 74.42 RCW, and complaints about individuals alleged to have abused, neglected, abandoned, or exploited residents or clients, under chapter 74.34 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1277-S.SL.pdf?cite=2011%201st%20sp.s.%20c%203%20§%20501[2011 1st sp.s. c 3 § 501]; ]

== 74.39A.380 - Internal quality review and accountability program for residential care services—Quality assurance panel—Report.
. Subject to funding provided for this specific purpose, the department of social and health services shall develop for phased-in implementation a statewide internal quality review and accountability program for residential care services. The program must be designed to enable the department to improve the accountability of staff and the consistent application of investigative activities across all long-term care settings, and must allow the systematic monitoring and evaluation of long-term care licensing and certification. The program must be designed to improve and standardize investigative outcomes for the vulnerable individuals at risk of abuse and neglect, and coordinate outcomes across the department to prevent perpetrators from changing settings and continuing to work with vulnerable adults.

. The department shall convene a quality assurance panel to review problems in the quality of care in adult family homes and to reduce incidents of abuse, neglect, abandonment, and financial exploitation. The state's long-term care ombuds shall chair the panel and identify appropriate stakeholders to participate. The panel must consider inspection, investigation, public complaint, and enforcement issues that relate to adult family homes. The panel must also focus on oversight issues to address de minimis violations, processes for handling unresolved citations, and better ways to oversee new providers. The panel shall meet at least quarterly, and provide a report with recommendations to the governor's office, the senate health and long-term care committee, and the house of representatives health and wellness committee by December 1, 2012.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20228[2013 c 23 § 228]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1277-S.SL.pdf?cite=2011%201st%20sp.s.%20c%203%20§%20502[2011 1st sp.s. c 3 § 502]; ]

== 74.39A.390 - Personal care services—Glove access.
. The legislature finds and declares that universal precautions are important health and safety protections for home care clients and workers who provide direct care for those clients. The use of personal protective equipment such as gloves is an established component of universal precautions and a key tool to protect against exposure to blood-borne pathogens such as hepatitis B virus, hepatitis C virus, and human immunodeficiency virus. Most medicaid clients are eligible to receive gloves through their medicaid benefit, yet the majority of clients are not aware of or do not use this benefit and as a result do not have gloves available in the home for individual providers to use. The legislature intends to improve the availability and usage of gloves by individual providers as part of universal precautions by ensuring that medicaid clients access gloves through their medicaid benefit.

. For medicaid clients, the department shall coordinate with the health care authority to assist clients receiving personal care services in accessing gloves as part of their health benefit for individual providers to use in the course of providing tasks where universal precautions are warranted. The assistance by the department and the health care authority must be designed to facilitate clients being able to access gloves on a monthly basis in a cost-effective and easy to access manner and must be consistent with requirements to receive federal matching funds under medicaid.

. In cases where clients are not eligible to receive such gloves under medicaid, the department shall work with the health care authority to develop a methodology to ensure clients have access to gloves on a monthly basis in a cost-effective and easy to access manner.

. The department shall submit a brief report with data on utilization of gloves by clients who are served by individual providers to the health care committees of the legislature by December 1, 2015.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2310-S.SL.pdf?cite=2014%20c%2070%20§%201[2014 c 70 § 1]; ]

== 74.39A.400 - Personal care services—Community first choice option.
. The department of social and health services shall refinance medicaid personal care services under the community first choice option. Beginning July 1, 2014, the department shall seek stakeholder input on program and system design prior to the submission of a proposal to the center for medicaid and medicare [centers for medicare and medicaid] services. The community first choice option shall be designed in such a way to meet the federal minimum maintenance of effort requirements and all service requirements as specified in federal rule. Optional services may also be included in the benefit package. In the first full year of implementation, the increase in per capita cost of services directly resulting from meeting the federal requirements of the community first choice option, as well as the cost of new optional services, shall not exceed a three percent increase over the per capita costs of personal care services in the fiscal year prior to full implementation of the community first choice option. The three percent limit on new expenditures shall not apply to cost increases that are not the result of implementing the community first choice option, including case load growth, case mix changes, inflation, vendor rate changes, expenditures necessary to meet state and federal law requirements, and any adjustments made pursuant to collective bargaining. The community first choice option must be fully implemented no later than August 30, 2015.

. The department shall use general fund—state savings from the refinance in this section to offset additional caseload, per capita cost increases, and staff resources necessary to implement the community first choice option. Any remaining general fund—state savings from the refinance shall be reserved for potential investments in home and community-based services for individuals with developmental disabilities or individuals with long-term care needs, including investments recommended by the joint legislative executive committee on aging and disability and the development and implementation council that the department must convene prior to submitting the proposed community first choice option to the centers for medicare and medicaid services. At a minimum, the final report to the legislature from the joint legislative executive committee on aging and disability must explore the cost and benefit of rate enhancements for providers of long-term services and supports, restoration of hours for in-home clients, additional investment in the family caregiver support program, and additional investment in the individual and family services program or other medicaid services to support individuals with developmental disabilities.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2746-S.SL.pdf?cite=2014%20c%20166%20§%202[2014 c 166 § 2]; ]

== 74.39A.500 - Consumer directed employer program—Establishment—Structure—Vendor qualifications—Transition—Department duties.
. The department may establish and implement a consumer directed employer program to provide personal care, respite care, and similar services to individuals with functional impairments under programs authorized through the medicaid state plan or medicaid waiver authorities and similar state-funded in-home care programs.

.. The consumer directed employer program is a consumer directed program and must be operated in a manner consistent with federal medicaid requirements. The consumer directed employer is the legal employer of individual providers for administrative purposes.

.. Under the consumer directed employer program, the consumer is the managing employer of individual providers and retains the primary right to select, dismiss, assign hours, and supervise the work of one or more individual providers, as long as the consumer's actions are consistent with the consumer's plan of care, this chapter, and state and federal law.

. The department shall endeavor to select and contract with one consumer directed employer to be a medicaid provider that will coemploy individual providers. The department shall make every effort to select a single qualified vendor. In the event it is not possible to contract with a single vendor, the department is authorized to contract with up to two vendors. The department's activities to identify, select, and contract with a consumer directed employer are exempt from the requirements of chapter 39.26 RCW.

.. When contracting with a consumer directed employer, the department should seek to contract with a vendor that demonstrates:

... A strong commitment to consumer choice, self-direction, and maximizing consumer autonomy and control over daily decisions; and

... A commitment to recruiting and retaining a high quality and diverse workforce and working with a broad coalition of stakeholders in an effort to understand the changing needs of the workforce and consumer needs and preferences.

.. Additional factors the department should consider in selecting a vendor include, but are not limited to, the vendor's:

... Ability to provide maximum support to consumers to focus on directing their own services through a model that recognizes that the provision of employer responsibility and human resource administration support is integral to successful self-directed home care programs;

... Commitment to engage and work closely with consumers in design, implementation, and ongoing operations through an advisory board, focus group, or other methods as approved by the department;

... Focus on workforce retention and creating incentives for qualified and trained providers to meet the growing needs of state long-term care consumers;

... Ability to meet the state's interest in preventing or mitigating disruptions to consumer services;

.. Ability to deliver high quality training, health care, and retirement, which may include participation in existing trusts that deliver those benefits;

.. Ability to comply with the terms and conditions of employment of individual providers at the time of the transition;

.. Commitment to involving its home care workforce in decision making;

.. Vision for including and enhancing home care workers as a valued member of the consumer's care team, as desired and authorized by the consumer and reflected in the consumer's plan of care; and

... Ability to build and adapt technology tools that can enhance efficiency and provide better quality of services.

.. In order to be qualified as a consumer directed employer, an entity must meet the requirements in: (i) Its contract with the department; (ii) the medicaid state plan; (iii) rules adopted under this chapter, if any; and (iv) this section.

.. Any qualified and willing individual may apply to become an employee of a consumer directed employer and may work as an individual provider when selected by a consumer.

.. A consumer directed employer that holds a contract with the department to provide medicaid services through the employment of individual providers is deemed to be a certified medicaid provider.

.. A consumer directed employer is not a home care agency under chapter 70.127 RCW.

.. A consumer directed employer that also provides home care services under chapter 70.127 RCW must demonstrate to the department's satisfaction that it operates the programs under separate business units, and that its business structures, policies, and procedures will prevent any conflicts of interest.

. If the department selects and contracts with a consumer directed employer, the department shall determine when to terminate the department's contracts with individual providers.

.. Until the department determines the transition to the consumer directed employer program is complete, the state shall continue to administer the individual provider program for the remaining contracted individual providers and to act as the public employer solely for the purpose of collective bargaining under RCW 74.39A.270 for those directly contracted individual providers.

.. Once the department determines that the transition to the consumer directed employer is complete, the department may no longer contract with individual providers, unless there are not any contracted consumer directed employers available.

. The department shall convene a stakeholder group to make recommendations to the legislature on the establishment of a separate licensure or certification category for a consumer directed employer. The stakeholder group shall make their recommendations by October 1, 2018.

. The department of labor and industries shall initially place individual providers employed by a consumer directed employer in the classification for the home care services and home care referral registry. After the department determines that the transition to the consumer directed employer program is complete, the department of labor and industries may, if necessary, adjust the classification and rate in accordance with chapter 51.16 RCW.

. After the date on which the department enters into a contract with the consumer directed employer and determines the transition to the consumer directed employer program is complete, biennial funding in the next ensuing biennium for case management and social work shall be reduced by no more than: Two million nine hundred eight thousand dollars for area agencies on aging; one million three hundred sixty-one thousand dollars for home and community services; and one million two hundred eighty-nine thousand dollars for developmental disabilities.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6199-S.SL.pdf?cite=2018%20c%20278%20§%203[2018 c 278 § 3]; ]

== 74.39A.505 - Consumer directed employer program—Rule-making authority—2018 c 278.
The department may adopt any rules as it deems necessary to implement the provisions of chapter 278, Laws of 2018.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6199-S.SL.pdf?cite=2018%20c%20278%20§%204[2018 c 278 § 4]; ]

== 74.39A.510 - Consumer directed employer program—Limitations.
. Nothing in chapter 278, Laws of 2018 modifies the department's:

.. Authority to establish a plan of care for each consumer, including establishing the number of hours in a week a consumer may assign to any one provider consistent with RCW 74.39A.525;

.. Core responsibility to manage long-term in-home care services under this chapter, including determination of the level of care that each consumer is eligible to receive;

.. Obligation to comply with the federal medicaid laws and regulations, the state medicaid plan, or any waiver granted by the federal department of health and human services; and to ensure federal financial participation in the provision of services.

. Nothing in chapter 278, Laws of 2018 modifies the legislature's right to make programmatic modifications to the delivery of state services under this title, including eligibility standards for consumers, standards for individual providers, and the nature of services provided.

. Nothing in this chapter shall cause individuals who were hired as long-term care workers prior to January 7, 2012, to lose their exemption from certification requirements under RCW 18.88B.041 solely because they became employees of a consumer directed employer.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6199-S.SL.pdf?cite=2018%20c%20278%20§%205[2018 c 278 § 5]; ]

== 74.39A.515 - Duties of consumer directed employers that employ individual providers—Duties of area agencies on aging with respect to individual providers contracted with the department—Rule making.
. If a consumer directed employer employs individual providers, then the consumer directed employer shall:

.. Verify that each individual provider has met any training requirements established under this chapter and rules adopted under this chapter;

.. Conduct background checks on individual providers as required under this chapter, RCW 43.43.830 through 43.43.842, 43.20A.710, and the rules adopted by the department; or verify that a background check has been conducted for each individual provider and that the background check is still valid in accordance with department rules;

.. Implement an electronic visit verification system that complies with federal requirements, or in the absence of an electronic visit verification system, monitor a statistically valid sample of individual provider's claims to the receipt of services by the consumer;

.. Monitor individual provider compliance with employment requirements;

.. As authorized and determined by the consumer, provide a copy of the consumer's plan of care to the individual provider who has been selected by the consumer;

.. Verify the individual provider is able and willing to carry out his or her responsibilities under the plan of care;

.. Take into account information provided by the consumer or the consumer's case manager about the consumer's specific needs;

.. Discontinue the individual provider's assignment to a consumer when the consumer directed employer has reason to believe, or the department or area agency on aging has reported, that the health, safety, or well-being of a consumer is in imminent jeopardy due to the performance of the individual provider;

.. Reject a request by a consumer to assign a specific person as his or her individual provider, if the consumer directed employer has reason to believe that the individual will be unable to appropriately meet the care needs of the consumer; and

.. Establish a dispute resolution process for consumers who wish to dispute decisions made under (h) and (i) of this subsection.

. If any individual providers are contracted with the department to provide services under this chapter, the area agency on aging case management responsibilities shall include:

.. Verifying that each individual provider has met all training requirements under this chapter and department rules;

.. Conducting background checks on individual providers as required under this chapter, RCW 43.43.830 through 43.43.842, 43.20A.710, and department rules; or verifying that background checks have been conducted for each individual provider and that the background check is still valid in accordance with department rules;

.. Monitoring that the individual provider is providing services as outlined in the consumer's plan of care;

.. Attaching the consumer's plan of care to the contract with the individual provider;

.. Verifying with the individual provider that he or she is able and willing to carry out his or her responsibilities under the plan of care;

.. Terminating the contract between the department and the individual provider if the department or area agency on aging finds that an individual provider's inadequate performance or inability to deliver quality care is jeopardizing the health, safety, or well-being of a consumer receiving service under this section;

.. Summarily suspending the contract pending a fair hearing, if there is reason to believe the health, safety, or well-being of a consumer is in imminent jeopardy; and

.. Rejecting a request by a consumer receiving services under this section to have a family member or other person serve as his or her individual provider if the case manager has reason to believe that the family member or other person will be unable to appropriately meet the care needs of the consumer.

. The consumer may request a fair hearing under chapter 34.05 RCW to contest a planned action of the case manager under subsection (2)(g) and (h) of this section.

. The department may adopt rules to implement this section.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6199-S.SL.pdf?cite=2018%20c%20278%20§%2013[2018 c 278 § 13]; ]

== 74.39A.520 - Individual providers employed by a consumer directed employer—Consumer's right to select, schedule, supervise, or dismiss individual providers.
The following provisions apply only if individual providers are employed by a consumer directed employer:

. Consumers and prospective consumers have the right to select, schedule, supervise the work of, and dismiss any individual provider providing services to them consistent with the consumer's plan of care.

. Nothing in this section modifies:

.. The consumer directed employer's authority to:

... Refuse to employ an individual provider who may not be able to meet the needs of a particular consumer;

... Assign an individual provider who has been dismissed by a consumer to a different consumer who has selected the individual provider;

... Provide information to a consumer about an individual provider's work history as an employee of the consumer directed employer; or

... Terminate the provider's employment when the individual is not meeting the needs of the consumer.

.. The consumer's right to:

... Assign hours to one or more individual providers consistent with this chapter, the rules adopted under this chapter, and his or her plan of care; or

... Dismiss an individual provider.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6199-S.SL.pdf?cite=2018%20c%20278%20§%2020[2018 c 278 § 20]; ]

== 74.39A.525 - Overtime criteria—Department-contracted individual providers—Individual providers employed by a consumer directed employer—Rule making—Expenditure reports—Joint legislative-executive overtime oversight task force.
. Except as authorized by subsection (3) or (4) of this section or otherwise required by law, the department may not permit a client to use a single department-contracted individual provider for more than forty hours in one workweek.

. A consumer directed employer that employs individual providers:

.. Must permit a client to use a single individual provider more than forty hours in a workweek if required by rules adopted under subsection (3) of this section;

.. May permit an individual provider to work additional hours in accordance with subsection (4) of this section; and

.. May permit an individual provider to work more than forty hours per workweek.

. The department shall adopt rules describing criteria under which a consumer may be permitted to use a single individual provider for more than forty hours per week. At a minimum, the criteria shall limit the state's exposure to exceeding the expenditure limits established in this section, require consumers to use good faith efforts to locate additional providers, address travel time from worksite to worksite, and address the following needs of consumers:

.. Emergencies that could pose a health and safety risk for consumers; and

.. Circumstances that could increase the risk of institutionalization without the use of overtime.

. An individual provider may be authorized to work more than forty hours in a workweek:

.. If the department established a permanent workweek limit between forty and one-quarter hours and sixty-five hours for an individual provider, based upon work performed by the individual provider in January 2016, as modified by an appeal, if any; or

.. For required training under RCW 74.39A.074, 74.39A.076, and 74.39A.341, and for required travel time between clients.

. The cost of overtime incurred under subsections (2)(a) and (b) and (4) of this section shall be included in a consumer directed employer labor rate determined in accordance with RCW 74.39A.530. The following overtime costs shall not be included in the labor rate under RCW 74.39A.530:

.. Costs incurred under subsection (2)(c) of this section;

.. Costs incurred by an employee of a consumer directed employer for services provided to an individual who is not a consumer;

.. Costs for services not authorized under this chapter; and

.. Overtime costs incurred because an employee of a consumer directed employer performed work:

... For both a consumer and an individual who is not a consumer; or

... Worked as both an individual provider and as an employee of the licensed home care agency affiliated with the consumer directed employer.

. Expenditures for hours in excess of forty hours each workweek under subsections (1) and (2) of this section shall not exceed eight and one-fourth percent of the total actual authorized personal care hours for the fiscal year as projected by the caseload forecast council.

. The caseload forecast council may adopt a temporary adjustment to the eight and one-fourth percent of the total average in-home personal care hours projection for that fiscal year, up to a maximum of ten percent, if it finds a higher percentage of overtime hours is necessitated by a shortage of individual providers to provide adequate client care, taking into consideration factors including the criteria in subsection (1) of this section and rules adopted by the department. If the council elects to temporarily increase the limit, it may do so only upon a majority vote of the council.

. The department shall prepare expenditure reports beginning September 1, 2018, and on September 1st every year thereafter. The report shall include the results of the department's monitoring of authorizations and costs of hours in excess of forty hours each workweek. If the department determines that the annual expenditures will exceed the limitation established in subsection (3) of this section, the department shall take those actions necessary to ensure compliance with the limitation.

. The expenditure reports must be submitted to the legislative fiscal committees and the joint legislative-executive overtime oversight task force. The joint legislative-executive overtime oversight task force members are as follows:

.. Two members from each of the two largest caucuses of the senate, appointed by the respective caucus leaders.

.. Two members from each of the two largest caucuses of the house of representatives, appointed by the speaker of the house of representatives.

.. The governor shall appoint members representing the department of social and health services and the office of financial management.

.. The governor shall appoint two members representing individual providers and two members representing consumers receiving personal care or respite care services from an individual provider.

. The task force shall meet when the department determines that it is projected to or is exceeding the expenditure limits established in subsection (6) of this section but may meet more frequently as desired by the task force. The task force shall choose cochairs, one from among the legislative members and one from among the executive branch members.

. The department may take appropriate corrective action, up to and including termination of an individual provider's contract, when the individual provider works more than his or her workweek limit in any given workweek.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6199-S.SL.pdf?cite=2018%20c%20278%20§%2026[2018 c 278 § 26]; ]

== 74.39A.530 - Consumer directed employer program—Labor and administrative rates—Rate-setting board—Funding process.
If the department contracts with a consumer directed employer:

. In addition to overtime and compensable travel time set forth in RCW 74.39A.525, the initial labor rates shall be paid as described in the most recent collective bargaining agreement between the governor and the service employees international union 775, plus the hourly roll-up costs of any additional legally required benefits or labor costs, until subsequent rates can be established in accordance with this section.

. A fourteen person rate-setting board is established to evaluate and propose changes in the rates paid to the consumer directed employer.

.. The following four members shall be voting members:

... One representative from the governor's office;

... One representative from the department;

... One representative from the consumer directed employer; and

... One designee from the exclusive bargaining representative of individual providers or, in the absence of an exclusive bargaining representative, a designee from the consumer directed employer workforce chosen by the employees of the consumer directed employer.

.. The following nine members of the board shall be nonvoting advisory members:

... Four legislators, one member from each caucus of the house of representatives and the senate;

... One representative from the state council on aging, appointed by the governor;

... One representative of an organization representing people with intellectual or developmental disabilities appointed by the governor;

... One representative of an organization representing people with physical disabilities appointed by the governor;

.. One representative from the licensed home care agency industry chosen by the state's largest association of home care agencies that primarily serves state-funded clients; and

.. One home care worker chosen by the state's largest organization of home care workers.

.. The governor's appointments shall be made by April 1st in even-numbered years.

. Beginning in the year following the establishment of the initial rate under subsection (1) of this section, and in every even-numbered year thereafter, the rate-setting board shall attempt to determine a proposed labor rate, including a specific amount for health benefits by considering the factors listed in RCW 41.56.465(5). In addition, the rate-setting board shall attempt to determine an administrative rate for the consumer directed employer.

. At the commencement of the board's rate-setting activities, the four voting members must first attempt to select a fifth voting member, who will chair the rate-setting panel and will cast a tie-breaking vote if the four voting members identified in subsection (2) of this section are unable to reach an agreement on the labor rate.

.. On the first occasion that the four voting members fail to select a tie-breaking member by a majority vote, the fifth member will be selected as follows:

... The panel member representing the governor's office shall request a list of five qualified arbitrators from the federal mediation and conciliation service.

... If a majority of the voting members of the panel cannot agree on the selection of a neutral arbitrator from the list, the representative from the consumer directed employer will strike a name from the list first. The representative from the governor's office shall then strike a name from the list, the designee from the exclusive bargaining representative or, in the absence of an exclusive bargaining representative, the designee from the consumer directed employer workforce shall strike a name from the list, and finally the representative from the department shall strike a name from the list.

... The name of the arbitrator remaining after the final strike shall be the fifth member of the panel.

... If that person is not willing or available to be the fifth panel member, the second to last person remaining on the list shall be asked to be the fifth panel member. If the second to last person is not willing or available, the third to last person shall be asked to be the fifth member. This process of selecting an arbitrator shall be continued until a fifth member of the panel is appointed.

.. On the next occasion that the four voting members fail to select a fifth tie-breaking member by a majority vote, the fifth member will be selected using the method described in (a) of this subsection except that the order of panel members striking names from the list, described in (a)(ii) of this subsection, shall be reversed.

.. On each successive occasion that the four voting members fail to select a fifth tie-breaking member by a majority vote, the order of panel members striking names from the list will continue to alternate between the order described in (a)(ii) and (b) of this subsection.

. If an agreement on a proposed labor rate, an administrative rate, or both, is not reached by a majority of the voting members of the rate-setting board prior to July 1st, then:

.. The labor rate shall be determined by the vote of the fifth member, who was selected in accordance with subsections (2) and (4) of this section; and

.. The administrative rate shall be determined by the department.

. After the rates have been determined in accordance with subsections (3) through (5) of this section, they shall be submitted to the director of the office of financial management by October 1st prior to the legislative session during which the requests are to be considered for review. If the director of the office of financial management certifies them as being feasible financially for the state, the governor shall include a request for funds necessary to implement the proposed rates as part of the governor's budget document submitted under RCW 43.88.030 and 43.88.060. The legislature shall approve or reject the request for funds as a whole.

. If the legislature rejects the request under subsection (5) of this section, the matter shall return to the rate-setting board established under this section for further consideration. Until the legislature approves a request for funds under this section, the current labor rate shall stay in effect.

. The labor rate approved by the legislature shall be an hourly rate paid to the consumer directed employer. The labor rate shall be used exclusively for paying the wages, associated taxes, and benefits of individual providers. The consumer directed employer shall have full discretion to set wages and benefits for individual providers, except as provided in: (a) Subsection (9) of this section; (b) any specific legislative appropriation requirement; or (c) a collective bargaining agreement, if applicable.

. The labor rate shall include a specific hourly amount that the consumer directed employer may use only for health benefits for individual providers.

. For the purpose of this section:

.. "Labor rate" is defined as that portion of the consumer directed employer's hourly rate that is to be used by the consumer directed employer to compensate its workers, including wages, benefits, and any associated taxes.

.. "Administrative rate" is defined as that portion of the consumer directed employer's hourly rate that is to be used by the consumer directed employer to perform its administrative duties.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6199-S.SL.pdf?cite=2018%20c%20278%20§%2027[2018 c 278 § 27]; ]

== 74.39A.800 - Changes to agreements—Performance of duties.
. If any provision of chapter 1, Laws of 2012 triggers changes to an agreement reached under RCW 74.39A.300, the changes must go into effect immediately without need for legislative approval.

. The requirements contained in RCW 74.39A.300 and chapter 1, Laws of 2012 constitute ministerial, mandatory, and nondiscretionary duties. Failure to fully perform such duties constitutes a violation of chapter 1, Laws of 2012. Any person may bring an action to require the governor or other responsible persons to perform such duties. Such action may be brought in the superior court, at the petitioner's option, for (a) Thurston county, or (b) the county of the petitioner's residence or principal place of business, or such action may be filed directly with the supreme court, which is hereby given original jurisdiction over such action.

[ 2012 c 1 § 304 (Initiative Measure No. 1163, approved November 8, 2011); ]

== 74.39A.900 - Section captions—1993 c 508.
Section captions as used in this act constitute no part of the law.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2098-S.SL.pdf?cite=1993%20c%20508%20§%2010[1993 c 508 § 10]; ]

== 74.39A.901 - Conflict with federal requirements.
If any part of this chapter or a collective bargaining agreement under this chapter is found by a court of competent jurisdiction to be in conflict with federal requirements that are a prescribed condition to the allocation of federal funds to the state, the conflicting part of this chapter or the agreement is inoperative solely to the extent of the conflict and with respect to the agencies directly affected, and this finding does not affect the operation of the remainder of this chapter or the agreement in its application to the agencies concerned. The rules under this chapter shall meet federal requirements that are a necessary condition to the receipt of federal funds by the state.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2933-S.SL.pdf?cite=2004%20c%203%20§%205[2004 c 3 § 5]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2098-S.SL.pdf?cite=1993%20c%20508%20§%2011[1993 c 508 § 11]; ]

== 74.39A.903 - Effective date—1993 c 508.
This act is necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and shall take effect immediately [May 18, 1993].

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2098-S.SL.pdf?cite=1993%20c%20508%20§%2013[1993 c 508 § 13]; ]

