= 74.48 - Skilled nursing facility safety net assessments.
:toc:

== 74.48.005 - Purpose—Findings—Intent.
. It is the intent of the legislature to encourage maximization of financial resources eligible and available for medicaid services by establishing the skilled nursing facility safety net trust fund to receive skilled nursing facility safety net assessments to use in securing federal matching funds under federally prescribed programs available through the state medicaid plan.

. The purpose of this chapter is to provide for a safety net assessment on certain Washington skilled nursing facilities, which will be used solely to support payments to skilled nursing facilities for medicaid services.

. The legislature finds that:

.. Washington skilled nursing facilities have proposed a skilled nursing facility safety net assessment to generate additional state and federal funding for the medicaid program, which will be used in part to restore recent reductions in skilled nursing facility reimbursement rates and provide for an increase in medicaid reimbursement rates; and

.. The skilled nursing facility safety net assessment and skilled nursing facility safety net trust fund created in this chapter allows the state to generate additional federal financial participation for the medicaid program and provides for increased reimbursement to skilled nursing facilities.

. In adopting this chapter, it is the intent of the legislature:

.. To impose a skilled nursing facility safety net assessment to be used solely for the purposes specified in this chapter;

.. That funds generated by the assessment, including matching federal financial participation, shall not be used for purposes other than as specified in this chapter;

.. That the total amount assessed not exceed the amount needed, in combination with all other available funds, to support the reimbursement rates and other payments authorized by this chapter, including payments under RCW 74.48.030; and

.. To condition the assessment and use of the resulting funds on receiving federal approval for receipt of additional federal financial participation.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5581-S.SL.pdf?cite=2011%201st%20sp.s.%20c%207%20§%2012[2011 1st sp.s. c 7 § 12]; ]

== 74.48.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Certain high volume medicaid nursing facilities" means the fewest number of facilities necessary with the highest number of medicaid days or total patient days annually to meet the statistical redistribution test at 42 C.F.R. Sec. 433.68(e)(2).

. "Continuing care retirement community" means a facility that provides a continuum of services by one operational entity or related organization providing independent living services, or *boarding home or assisted living services under chapter 18.20 RCW, and skilled nursing services under chapter 18.51 RCW in a single contiguous campus. The number of licensed nursing home beds must be sixty percent or less of the total number of beds available in the entire continuing care retirement community. For purposes of this subsection "contiguous" means land adjoining or touching other property held by the same or related organization including land divided by a public road.

. "Deductions from revenue" means reductions from gross revenue resulting from an inability to collect payment of charges. Such reductions include bad debt, contractual adjustments, policy discounts and adjustments, and other such revenue deductions.

. "Department" means the department of social and health services.

. "Fund" means the skilled nursing facility safety net trust fund.

. "Hospital based" means a nursing facility that is physically part of, or contiguous to, a hospital. For purposes of this subsection "contiguous" has the same meaning as in subsection (2) of this section.

. "Medicare patient day" means a patient day for medicare beneficiaries on a medicare part A stay, medicare hospice stay, and a patient day for persons who have opted for managed care coverage using their medicare benefit.

. "Medicare upper payment limit" means the limitation established by federal regulations, 42 C.F.R. Sec. 447.272, that disallows federal matching funds when state medicaid agencies pay certain classes of nursing facilities an aggregate amount for services that would exceed the amount that would be paid for the same services furnished by that class of nursing facilities under medicare payment principles.

. "Net resident service revenue" means gross revenue from services to nursing facility residents less deductions from revenue. Net resident service revenue does not include other operating revenue or nonoperating revenue.

. "Nonexempt nursing facility" means a nursing facility that is not exempt from the skilled nursing facility safety net assessment.

. "Nonoperating revenue" means income from activities not relating directly to the day-to-day operations of an organization. Nonoperating revenue includes such items as gains on disposal of a facility's assets, dividends, and interest from security investments, gifts, grants, and endowments.

. "Nursing facility," "facility," or "skilled nursing facility" has the same meaning as "nursing home" as defined in RCW 18.51.010.

. "Other operating revenue" means income from nonresident care services to residents, as well as sales and activities to persons other than residents. It is derived in the course of operating the facility such as providing personal laundry service for residents or from other sources such as meals provided to persons other than residents, personal telephones, gift shops, and vending machines.

. "Related organization" means an entity which is under common ownership and/or control with, or has control of, or is controlled by, the contractor, as defined under chapter 74.46 RCW.

.. "Common ownership" exists when an entity is the beneficial owner of five percent or more ownership interest in the contractor, as defined under chapter 74.46 RCW and any other entity.

.. "Control" exists where an entity has the power, directly or indirectly, significantly to influence or direct the actions or policies of an organization or institution, whether or not it is legally enforceable and however it is exercisable or exercised.

. "Resident day" means a calendar day of care provided to a nursing facility resident, excluding medicare patient days. Resident days include the day of admission and exclude the day of discharge. An admission and discharge on the same day count as one day of care. Resident days include nursing facility hospice days and exclude bedhold days for all residents.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5581-S.SL.pdf?cite=2011%201st%20sp.s.%20c%207%20§%2013[2011 1st sp.s. c 7 § 13]; ]

== 74.48.020 - Skilled nursing facility safety net trust fund.
. There is established in the state treasury the skilled nursing facility safety net trust fund. The purpose and use of the fund shall be to receive and disburse funds, together with accrued interest, in accordance with this chapter. Moneys in the fund, including interest earned, shall not be used or disbursed for any purposes other than those specified in this chapter. Any amounts expended from the fund that are later recouped by the department on audit or otherwise shall be returned to the fund.

. The skilled nursing facility safety net trust fund must be a separate and continuing fund, and no money in the fund reverts to the state general fund at any time. All assessments, interest, and penalties collected by the department under RCW 74.48.030, 74.48.040, and 74.48.080 shall be deposited into the fund.

. Any money received under RCW 74.48.030, 74.48.040, and 74.48.080 must be deposited in the state treasury for credit to the skilled nursing facility safety net trust fund, and must be expended, to the extent authorized by federal law, to obtain federal financial participation in the medicaid program and to maintain and enhance nursing facility rates in a manner set forth in subsection (4) of this section.

. Disbursements from the fund may be made only as follows:

.. As an immediate pass-through or rate add-on to reimburse the medicaid share of the skilled nursing facility safety net assessment as a medicaid allowable cost;

.. To make medicaid payments for nursing facility services in accordance with chapter 74.46 RCW and pursuant to this chapter;

.. To refund erroneous or excessive payments made by skilled nursing facilities pursuant to this chapter;

.. To administer the provisions of this chapter the department may expend an amount not to exceed one-half of one percent of the money received from the assessment, and must not exceed the amount authorized for expenditure by the legislature for administrative expenses in a fiscal year;

.. To repay the federal government for any excess payments made to skilled nursing facilities from the fund if the assessments or payment increases set forth in this chapter are deemed out of compliance with federal statutes and regulations and all appeals have been exhausted. In such a case, the department may require skilled nursing facilities receiving excess payments to refund the payments in question to the fund. The state in turn shall return funds to the federal government in the same proportion as the original financing. If a skilled nursing facility is unable to refund payments, the state shall either develop a payment plan or deduct moneys from future medicaid payments, or both; and

.. To increase nursing facility payments to fund covered services to medicaid beneficiaries within medicare upper limits.

. Any positive balance in the fund at the end of a fiscal year shall be applied to reduce the assessment amount for the subsequent fiscal year in accordance with RCW 74.48.040(1)(c)(i).

. Upon termination of the assessment, any amounts remaining in the fund shall be refunded to skilled nursing facilities, pro rata according to the amount paid by the facility, subject to limitations of federal law.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5581-S.SL.pdf?cite=2011%201st%20sp.s.%20c%207%20§%2014[2011 1st sp.s. c 7 § 14]; ]

== 74.48.030 - Assessments.
. In accordance with the redistribution method set forth in 42 C.F.R. Sec. 433.68(e)(1) and (2), the department shall seek a waiver of the broad-based and uniform provider assessment requirements of federal law to exclude certain nursing facilities from the skilled nursing facility safety net assessment and to permit certain high volume medicaid nursing facilities or facilities with a high number of total annual resident days to pay the skilled nursing facility safety net assessment at a lesser amount per nonmedicare patient day.

. The skilled nursing facility safety net assessment shall, at no time, be greater than the maximum percentage of the nursing facility industry reported net patient service revenues allowed under federal law or regulation.

. All skilled nursing facility safety net assessments collected pursuant to this section by the department shall be transmitted to the state treasurer who shall credit all such amounts to the skilled nursing facility safety net trust fund.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5581-S.SL.pdf?cite=2011%201st%20sp.s.%20c%207%20§%2015[2011 1st sp.s. c 7 § 15]; ]

== 74.48.040 - Administration and collection.
. The department, in cooperation with the office of financial management, shall develop rules for determining the amount to be assessed to individual skilled nursing facilities, notifying individual skilled nursing facilities of the assessed amount, and collecting the amounts due. Such rule making shall specifically include provision for:

.. Payment of the skilled nursing facility safety net assessment;

.. Interest on delinquent assessments;

.. Adjustment of the assessment amounts as follows:

... The assessment amounts under RCW 74.48.030 may be adjusted as follows:

(A) If sufficient other appropriated funds for skilled nursing facilities, are available to support the nursing facility reimbursement rates as authorized in the biennial appropriations act and other uses and payments permitted by RCW 74.48.020 and 74.48.030 without utilizing the full assessment authorized under RCW 74.48.030, the department shall reduce the amount of the assessment to the minimum level necessary to support those reimbursement rates and other uses and payments.

(B) So long as none of the conditions set forth in RCW 74.48.060(2) have occurred, if the department's forecasts indicate that the assessment amounts under RCW 74.48.030, together with all other appropriated funds, are not sufficient to support the skilled nursing facility reimbursement rates authorized in the biennial appropriations act and other uses and payments authorized under RCW 74.48.020 and 74.48.030, the department shall increase the assessment rates to the amount necessary to support those reimbursement rates and other payments to the maximum amount allowable under federal law.

(C) Any positive balance remaining in the fund at the end of the fiscal year shall be applied to reduce the assessment amount for the subsequent fiscal year.

... Beginning July 1, 2012, any adjustment to the assessment amounts pursuant to this subsection, and the data supporting such adjustment, including but not limited to relevant data listed in subsection (2) of this section, must be submitted to the Washington health care association, and aging services of Washington, for review and comment at least sixty calendar days prior to implementation of such adjusted assessment amounts. Any review and comment provided by the Washington health care association, and aging services of Washington, shall not limit the ability of either association or its members to challenge an adjustment or other action by the department that is not made in accordance with this chapter.

. By November 30th of each year, the department shall provide the following data to the office of financial management, the chair of the fiscal committee of the senate and the house of representatives, the Washington health care association, and aging services of Washington:

.. The fund balance; and

.. The amount of assessment paid by each skilled nursing facility.

. Assessments shall be assessed from July 1, 2011.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5581-S.SL.pdf?cite=2011%201st%20sp.s.%20c%207%20§%2016[2011 1st sp.s. c 7 § 16]; ]

== 74.48.050 - Exceptions.
. Subject to subsection (4) of this section the department shall exempt the following nursing facility providers from the skilled nursing facility safety net assessment subject to federal approval under 42 C.F.R. Sec. 433.68(e)(2):

.. Continuing care retirement communities;

.. Nursing facilities with thirty-five or fewer licensed beds;

.. State, tribal, and county operated nursing facilities; and

.. Any nursing facility operated by a public hospital district and nursing facilities that are hospital-based.

. The department shall lower the skilled nursing facility safety net assessment for either certain high volume medicaid nursing facilities or certain facilities with high resident volumes to meet the redistributive tests of 42 C.F.R. Sec. 433.68(e)(2).

. The department shall lower the skilled nursing facility safety net assessment for any skilled nursing facility with a licensed bed capacity in excess of two hundred three beds to the same level described in subsection (2) of this section.

. To the extent necessary to obtain federal approval under 42 C.F.R. Sec. 433.68(e)(2), the exemptions prescribed in subsections (1), (2), and (3) of this section may be amended by the department.

. The per resident day assessment rate shall be the same amount for each affected facility except as prescribed in subsections (1), (2), and (3) of this section.

. The department shall notify the nursing facility operators of any skilled nursing facilities that would be exempted from the skilled nursing facility safety net assessment pursuant to the waiver request submitted to the United States department of health and human services under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5581-S.SL.pdf?cite=2011%201st%20sp.s.%20c%207%20§%2017[2011 1st sp.s. c 7 § 17]; ]

== 74.48.060 - Conditions.
. If the centers for medicare and medicaid services fail to approve any state plan amendments or waiver requests that are necessary in order to implement the applicable sections of this chapter then the assessment authorized in RCW 74.48.040 shall cease to be imposed.

. Nothing in subsection (1) of this section prohibits the department from working cooperatively with the centers for medicare and medicaid services to secure approval of any needed state plan amendments or waiver requests. As provided in RCW 74.48.030 and 74.48.050, the department shall adjust any submitted state plan amendments or waiver requests as necessary to achieve approval.

. If this chapter does not take effect or ceases to be imposed, any moneys remaining in the fund shall be refunded to skilled nursing facilities in proportion to the amounts paid by such facilities.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5581-S.SL.pdf?cite=2011%201st%20sp.s.%20c%207%20§%2018[2011 1st sp.s. c 7 § 18]; ]

== 74.48.070 - Assessment part of operating overhead.
The incidence and burden of assessments imposed under this chapter shall be on skilled nursing facilities and the expense associated with the assessments shall constitute a part of the operating overhead of the facilities. Skilled nursing facilities shall not itemize the safety net assessment on billings to residents or third-party payers.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5581-S.SL.pdf?cite=2011%201st%20sp.s.%20c%207%20§%2019[2011 1st sp.s. c 7 § 19]; ]

== 74.48.080 - Enforcement.
If a nursing facility fails to make timely payment of the safety net assessment, the department may seek a remedy provided by law, including, but not limited to:

. Withholding any medical assistance reimbursement payments until such time as the assessment amount is recovered;

. Suspension or revocation of the nursing facility license; or

. Imposition of a civil fine up to one thousand dollars per day for each delinquent payment, not to exceed the amount of the assessment.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5581-S.SL.pdf?cite=2011%201st%20sp.s.%20c%207%20§%2020[2011 1st sp.s. c 7 § 20]; ]

== 74.48.090 - Quality incentive payments.
. The department and the department of health, in consultation with the Washington state health care association, and aging services of Washington, shall design a system of skilled nursing facility quality incentive payments. The design of the system shall be submitted to the relevant policy and fiscal committees of the legislature by January 1, 2013. For the 2011-2013 fiscal biennial budget period, the department shall not implement a system of skilled nursing facility quality incentive payments designed pursuant to this section. The system shall be based upon the following principles:

.. Evidence-based treatment and processes shall be used to improve health care outcomes for skilled nursing facility residents;

.. Effective purchasing strategies to improve the quality of health care services should involve the use of common quality improvement measures, while recognizing that some measures may not be appropriate for application to facilities with high bariatric, behaviorally challenged, or rehabilitation populations;

.. Quality measures chosen for the system should be consistent with the standards that have been developed by national quality improvement organizations, such as the national quality forum, the federal centers for medicare and medicaid services, or the federal agency for healthcare research and quality. New reporting burdens to skilled nursing facilities should be minimized by giving priority to measures skilled nursing facilities that are currently required to report to governmental agencies, such as the nursing home compare measures collected by the federal centers for medicare and medicaid services;

.. Benchmarks for each quality improvement measure should be set at levels that are feasible for skilled nursing facilities to achieve, yet represent real improvements in quality and performance for a majority of skilled nursing facilities in Washington state; and

.. Skilled nursing facilities performance and incentive payments should be designed in a manner such that all facilities in Washington are able to receive the incentive payments if performance is at or above the benchmark score set in the system established under this section.

. Pursuant to an appropriation by the legislature, for state fiscal year 2014 and each fiscal year thereafter, assessments may be increased to support an additional one percent increase in skilled nursing facility reimbursement rates for facilities that meet the quality incentive benchmarks established under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2127-S.SL.pdf?cite=2012%202nd%20sp.s.%20c%207%20§%20921[2012 2nd sp.s. c 7 § 921]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5581-S.SL.pdf?cite=2011%201st%20sp.s.%20c%207%20§%2021[2011 1st sp.s. c 7 § 21]; ]

== 74.48.900 - Severability—2011 1st sp.s. c 7.
Except as provided in RCW 74.48.060, if any provision of this act or its application to any person or circumstance is held invalid, the remainder of the act or the application of the provision to other persons or circumstances is not affected.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5581-S.SL.pdf?cite=2011%201st%20sp.s.%20c%207%20§%2024[2011 1st sp.s. c 7 § 24]; ]

== 74.48.901 - Effective date—2011 1st sp.s. c 7.
This act is necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and takes effect July 1, 2011.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5581-S.SL.pdf?cite=2011%201st%20sp.s.%20c%207%20§%2026[2011 1st sp.s. c 7 § 26]; ]

