= 74.66 - Medicaid fraud false claims act.
:toc:

== 74.66.005 - Short title.
This chapter may be known and cited as the medicaid fraud false claims act.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5978-S.SL.pdf?cite=2012%20c%20241%20§%20214[2012 c 241 § 214]; ]

== 74.66.010 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter:

. [Empty]
.. "Claim" means any request or demand made for a medicaid payment under chapter 74.09 RCW or other applicable law, whether under a contract or otherwise, for money or property and whether or not a government entity has title to the money or property, that:

... Is presented to an officer, employee, or agent of a government entity; or

... Is made to a contractor, grantee, or other recipient, if the money or property is to be spent or used on the government entity's behalf or to advance a government entity program or interest, and the government entity:

(A) Provides or has provided any portion of the money or property requested or demanded; or

(B) Will reimburse such contractor, grantee, or other recipient for any portion of the money or property which is requested or demanded.

.. A "claim" does not include requests or demands for money or property that the government entity has paid to an individual as compensation for employment or as an income subsidy with no restrictions on that individual's use of the money or property.

. "Custodian" means the custodian, or any deputy custodian, designated by the attorney general.

. "Documentary material" includes the original or any copy of any book, record, report, memorandum, paper, communication, tabulation, chart, or other document, or data compilations stored in or accessible through computer or other information retrieval systems, together with instructions and all other materials necessary to use or interpret the data compilations, and any product of discovery.

. "False claims act investigation" means any inquiry conducted by any false claims act investigator for the purpose of ascertaining whether any person is or has been engaged in any violation of this chapter.

. "False claims act investigator" means any attorney or investigator employed by the state attorney general who is charged with the duty of enforcing or carrying into effect any provision of this chapter, or any officer or employee of the state of Washington acting under the direction and supervision of the attorney or investigator in connection with an investigation pursuant to this chapter.

. "Government entity" means all Washington state agencies that administer medicaid-funded programs under this title.

. [Empty]
.. "Knowing" and "knowingly" mean that a person, with respect to information:

... Has actual knowledge of the information;

... Acts in deliberate ignorance of the truth or falsity of the information; or

... Acts in reckless disregard of the truth or falsity of the information.

.. "Knowing" and "knowingly" do not require proof of specific intent to defraud.

. "Material" means having a natural tendency to influence, or be capable of influencing, the payment or receipt of money or property.

. "Obligation" means an established duty, whether or not fixed, arising from an express or implied contractual, grantor-grantee, or licensor-licensee relationship, from a fee-based or similar relationship, from statute or rule, or from the retention of any overpayment.

. "Official use" means any use that is consistent with the law, and the rules and policies of the attorney general, including use in connection with: Internal attorney general memoranda and reports; communications between the attorney general and a federal, state, or local government agency, or a contractor of a federal, state, or local government agency, undertaken in furtherance of an investigation or prosecution of a case; interviews of any qui tam relator or other witness; oral examinations; depositions; preparation for and response to civil discovery requests; introduction into the record of a case or proceeding; applications, motions, memoranda, and briefs submitted to a court or other tribunal; and communications with attorney general investigators, auditors, consultants and experts, the counsel of other parties, and arbitrators or mediators, concerning an investigation, case, or proceeding.

. "Person" means any natural person, partnership, corporation, association, or other legal entity, including any local or political subdivision of a state.

. "Product of discovery" includes:

.. The original or duplicate of any deposition, interrogatory, document, thing, result of the inspection of land or other property, examination, or admission, which is obtained by any method of discovery in any judicial or administrative proceeding of an adversarial nature;

.. Any digest, analysis, selection, compilation, or derivation of any item listed in (a) of this subsection; and

.. Any index or other manner of access to any item listed in (a) of this subsection.

. "Qui tam action" is an action brought by a person under RCW 74.66.050.

. "Qui tam relator" or "relator" is a person who brings an action under RCW 74.66.050.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1388-S.SL.pdf?cite=2018%20c%20201%20§%207023[2018 c 201 § 7023]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5978-S.SL.pdf?cite=2012%20c%20241%20§%20201[2012 c 241 § 201]; ]

== 74.66.020 - Civil penalty—False or fraudulent claims.
. Subject to subsections (2) and (4) of this section, a person is liable to the government entity for a civil penalty of not less than the greater of ten thousand nine hundred fifty-seven dollars or the minimum inflation adjusted penalty amount imposed as provided by 31 U.S.C. Sec. 3729(a) and not more than the greater of twenty-one thousand nine hundred sixteen dollars or the maximum inflation adjusted penalty amount imposed as provided by 31 U.S.C. Sec. 3729(a), plus three times the amount of damages which the government entity sustains because of the act of that person, if the person:

.. Knowingly presents, or causes to be presented, a false or fraudulent claim for payment or approval;

.. Knowingly makes, uses, or causes to be made or used, a false record or statement material to a false or fraudulent claim;

.. Conspires to commit one or more of the violations in this subsection (1);

.. Has possession, custody, or control of property or money used, or to be used, by the government entity and knowingly delivers, or causes to be delivered, less than all of that money or property;

.. Is authorized to make or deliver a document certifying receipt of property used, or to be used, by the government entity and, intending to defraud the government entity, makes or delivers the receipt without completely knowing that the information on the receipt is true;

.. Knowingly buys, or receives as a pledge of an obligation or debt, public property from an officer or employee of the government entity who lawfully may not sell or pledge property; or

.. Knowingly makes, uses, or causes to be made or used a false record or statement material to an obligation to pay or transmit money or property to the government entity, or knowingly conceals or knowingly and improperly avoids or decreases an obligation to pay or transmit money or property to the government entity.

. The court may assess not less than two times the amount of damages which the government entity sustains because of the act of a person, if the court finds that:

.. The person committing the violation of subsection (1) of this section furnished the Washington state attorney general with all information known to him or her about the violation within thirty days after the date on which he or she first obtained the information;

.. The person fully cooperated with any investigation by the attorney general of the violation; and

.. At the time the person furnished the attorney general with the information about the violation, no criminal prosecution, civil action, or administrative action had commenced under this title with respect to the violation, and the person did not have actual knowledge of the existence of an investigation into the violation.

. A person violating this section is liable to the attorney general for the costs of a civil action brought to recover any such penalty or damages.

. For the purposes of determining whether an insurer has a duty to provide a defense or indemnification for an insured and if coverage may be denied if the terms of the policy exclude coverage for intentional acts, a violation of subsection (1) of this section is an intentional act.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6053.SL.pdf?cite=2018%20c%2063%20§%202[2018 c 63 § 2]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5978-S.SL.pdf?cite=2012%20c%20241%20§%20202[2012 c 241 § 202]; ]

== 74.66.030 - Public records exemption.
Any information furnished pursuant to this chapter is exempt from disclosure under the public records act, chapter 42.56 RCW, until final disposition and all court-ordered seals are lifted.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5978-S.SL.pdf?cite=2012%20c%20241%20§%20203[2012 c 241 § 203]; ]

== 74.66.040 - Attorney general—Investigation—Civil action.
The attorney general must diligently investigate a violation under RCW 74.66.020. If the attorney general finds that a person has violated or is violating RCW 74.66.020, the attorney general may bring a civil action under this section against the person.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5978-S.SL.pdf?cite=2012%20c%20241%20§%20204[2012 c 241 § 204]; ]

== 74.66.050 - Qui tam action—Relator rights and duties.
. A person may bring a civil action for a violation of RCW 74.66.020 for the person and for the government entity. The action may be known as a qui tam action and the person bringing the action as a qui tam relator. The action must be brought in the name of the government entity. The action may be dismissed only if the court , and the attorney general give written consent to the dismissal and their reason for consenting.

. A relator filing an action under this chapter must serve a copy of the complaint and written disclosure of substantially all material evidence and information the person possesses on the attorney general in electronic format. The relator must file the complaint in camera. The complaint must remain under seal for at least sixty days, and may not be served on the defendant until the court so orders. The attorney general may elect to intervene and proceed with the action within sixty days after it receives both the complaint and the material evidence and information.

. The attorney general may, for good cause shown, move the court for extensions of the time during which the complaint remains under seal under subsection (2) of this section. The motions may be supported by affidavits or other submissions in camera. The defendant may not be required to respond to any complaint filed under this section until twenty days after the complaint is unsealed and served upon the defendant.

. If the attorney general does not proceed with the action prior to the expiration of the sixty-day period or any extensions obtained under subsection (3) of this section, then the relator has the right to conduct the action.

. When a person brings an action under this section, no person other than the attorney general may intervene or bring a related action based on the facts underlying the pending action.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5978-S.SL.pdf?cite=2012%20c%20241%20§%20205[2012 c 241 § 205]; ]

== 74.66.060 - Qui tam action—Attorney general authority.
. If the attorney general proceeds with the qui tam action, the attorney general shall have the primary responsibility for prosecuting the action, and is not bound by an act of the relator. The relator has the right to continue as a party to the action, subject to the limitations set forth in subsection (2) of this section.

. [Empty]
.. The attorney general may move to dismiss the qui tam action notwithstanding the objections of the relator if the relator has been notified by the attorney general of the filing of the motion and the court has provided the relator with an opportunity for a hearing on the motion.

.. The attorney general may settle the action with the defendant notwithstanding the objections of the relator if the court determines, after a hearing, that the proposed settlement is fair, adequate, and reasonable under all the circumstances. Upon a showing of good cause, the hearing may be held in camera.

.. Upon a showing by the attorney general that unrestricted participation during the course of the litigation by the relator would interfere with or unduly delay the attorney general's prosecution of the case, or would be repetitious, irrelevant, or for purposes of harassment, the court may, in its discretion, impose limitations on the relator's participation, such as:

... Limiting the number of witnesses the relator may call;

... Limiting the length of the testimony of the witnesses;

... Limiting the relator's cross-examination of witnesses; or

... Otherwise limiting the participation by the relator in the litigation.

.. Upon a showing by the defendant that unrestricted participation during the course of the litigation by the relator would be for purposes of harassment or would cause the defendant undue burden or unnecessary expense, the court may limit the participation by the relator in the litigation.

. If the attorney general elects not to proceed with the qui tam action, the relator has the right to conduct the action. If the attorney general so requests, the relator must serve on the attorney general copies of all pleadings filed in the action and shall supply copies of all deposition transcripts, at the attorney general's expense. When the relator proceeds with the action, the court, without limiting the status and rights of the relator, may nevertheless permit the attorney general to intervene at a later date upon a showing of good cause.

. Whether or not the attorney general proceeds with the qui tam action, upon a showing by the attorney general that certain actions of discovery by the relator would interfere with the attorney general's investigation or prosecution of a criminal or civil matter arising out of the same facts, the court may stay such discovery for a period of not more than sixty days. The showing must be conducted in camera. The court may extend the sixty-day period upon a further showing in camera that the attorney general has pursued the criminal or civil investigation or proceedings with reasonable diligence and any proposed discovery in the civil action will interfere with the ongoing criminal or civil investigation or proceedings.

. Notwithstanding RCW 74.66.050, the attorney general may elect to pursue its claim through any alternate remedy available to the state, including any administrative proceeding to determine a civil money penalty. If any alternate remedy is pursued in another proceeding, the relator has the same rights in the proceeding as the relator would have had if the action had continued under this section. Any finding of fact or conclusion of law made in the other proceeding that has become final is conclusive on all parties to an action under this section. For purposes of this subsection, a finding or conclusion is final if it has been finally determined on appeal to the appropriate court of the state of Washington, if all time for filing the appeal with respect to the finding or conclusion has expired, or if the finding or conclusion is not subject to judicial review.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5978-S.SL.pdf?cite=2012%20c%20241%20§%20206[2012 c 241 § 206]; ]

== 74.66.070 - Qui tam action—Award—Proceeds of action or settlement of claim.
. [Empty]
.. Subject to (b) of this subsection, if the attorney general proceeds with a qui tam action, the relator must receive at least fifteen percent but not more than twenty-five percent of the proceeds of the action or settlement of the claim, depending upon the extent to which the relator substantially contributed to the prosecution of the action.

.. Where the action is one which the court finds to be based primarily on disclosures of specific information, other than information provided by the relator, relating to allegations or transactions in a criminal, civil, or administrative hearing, in a legislative or administrative report, hearing, audit, or investigation, or from the news media, the court may award an amount it considers appropriate, but in no case more than ten percent of the proceeds, taking into account the significance of the information and the role of the relator in advancing the case to litigation.

.. Any payment to a relator under (a) or (b) of this subsection must be made from the proceeds. The relator must also receive an amount for reasonable expenses which the court finds to have been necessarily incurred, plus reasonable attorneys' fees and costs. All expenses, fees, and costs must be awarded against the defendant.

. If the attorney general does not proceed with a qui tam action, the relator shall receive an amount which the court decides is reasonable for collecting the civil penalty and damages. The amount may not be less than twenty-five percent and not more than thirty percent of the proceeds of the action or settlement and must be paid out of the proceeds. The relator must also receive an amount for reasonable expenses, which the court finds to have been necessarily incurred, plus reasonable attorneys' fees and costs. All expenses, fees, and costs must be awarded against the defendant.

. Whether or not the attorney general proceeds with the qui tam action, if the court finds that the action was brought by a person who planned and initiated the violation of RCW 74.66.020 upon which the action was brought, then the court may, to the extent the court considers appropriate, reduce the share of the proceeds of the action which the person would otherwise receive under subsection (1) or (2) of this section, taking into account the role of that person in advancing the case to litigation and any relevant circumstances pertaining to the violation. If the person bringing the action is convicted of criminal conduct arising from his or her role in the violation of RCW 74.66.020, that person must be dismissed from the civil action and may not receive any share of the proceeds of the action. The dismissal may not prejudice the right of the state to continue the action, represented by the attorney general.

. If the attorney general does not proceed with the qui tam action and the relator conducts the action, the court may award to the defendant reasonable attorneys' fees and expenses if the defendant prevails in the action and the court finds that the claim of the relator was clearly frivolous, clearly vexatious, or brought primarily for purposes of harassment.

. Any funds recovered that remain after calculation and distribution under subsections (1) through (3) of this section must be deposited into the medicaid fraud penalty account established in RCW 74.09.215.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5978-S.SL.pdf?cite=2012%20c%20241%20§%20207[2012 c 241 § 207]; ]

== 74.66.080 - Qui tam action—Restrictions—Dismissal.
. In no event may a person bring a qui tam action which is based upon allegations or transactions which are the subject of a civil suit or an administrative civil money penalty proceeding in which the state is already a party.

. [Empty]
.. The court must dismiss an action or claim under this section, unless opposed by the attorney general, if substantially the same allegations or transactions as alleged in the action or claim were publicly disclosed:

... In a state criminal, civil, or administrative hearing in which the attorney general or other governmental [government] entity is a party;

... In a legislative report, or other state report, hearing, audit, or investigation; or

... By the news media;

unless the action is brought by the attorney general or the relator is an original source of the information.

.. For purposes of this section, "original source" means an individual who either (i) prior to a public disclosure under (a) of this subsection, has voluntarily disclosed to the attorney general the information on which allegations or transactions in a claim are based, or (ii) has knowledge that is independent of, and materially adds to, the publicly disclosed allegations or transactions, and who has voluntarily provided the information to the attorney general before filing an action under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5978-S.SL.pdf?cite=2012%20c%20241%20§%20208[2012 c 241 § 208]; ]

== 74.66.090 - Whistleblower relief.
. Any employee, contractor, or agent is entitled to all relief necessary to make that employee, contractor, or agent whole, if that employee, contractor, or agent , is discharged, demoted, suspended, threatened, harassed, or in any other manner discriminated against in the terms and conditions of employment because of lawful acts done by the employee, contractor, agent, or associated others in furtherance of an action under this chapter or other efforts to stop one or more violations of this chapter.

. Relief under subsection (1) of this section must include reinstatement with the same seniority status that employee, contractor, or agent would have had but for the discrimination, two times the amount of back pay, interest on the back pay, and compensation for any special damages sustained as a result of the discrimination, including litigation costs and reasonable attorneys' fees, and any and all relief available under RCW 49.60.030(2). An action under this subsection may be brought in the appropriate superior court of the state of Washington for the relief provided in this subsection.

. A civil action under this section may not be brought more than three years after the date when the retaliation occurred.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5978-S.SL.pdf?cite=2012%20c%20241%20§%20209[2012 c 241 § 209]; ]

== 74.66.100 - Procedure for civil actions.
. A subpoena requiring the attendance of a witness at a trial or hearing conducted under RCW 74.66.040 or 74.66.050 may be served at any place in the state of Washington.

. A civil action under RCW 74.66.040 or 74.66.050 may be brought at any time, without limitation after the date on which the violation of RCW 74.66.020 is committed.

. If the attorney general elects to intervene and proceed with a qui tam action, the attorney general may file its own complaint or amend the complaint of a relator to clarify or add detail to the claims in which the attorney general is intervening and to add any additional claims with respect to which the attorney general contends it is entitled to relief.

. In any action brought under RCW 74.66.040 or 74.66.050, the attorney general is required to prove all essential elements of the cause of action, including damages, by a preponderance of the evidence.

. Notwithstanding any other provision of law or the rules for superior court, a final judgment rendered in favor of the government entity in any criminal proceeding charging fraud or false statements, whether upon a verdict after trial or upon a plea of guilty or nolo contendere, estops the defendant from denying the essential elements of the offense in any action which involves the same transaction as in the criminal proceeding and which is brought under RCW 74.66.040 or 74.66.050.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5978-S.SL.pdf?cite=2012%20c%20241%20§%20210[2012 c 241 § 210]; ]

== 74.66.110 - Jurisdiction—Seal on action.
. Any action under RCW 74.66.040 or 74.66.050 may be brought in the superior court in any county in which the defendant or, in the case of multiple defendants, any one defendant can be found, resides, transacts business, or in which any act proscribed by RCW 74.66.020 occurred. The appropriate court must issue a summons as required by the superior court civil rules and service must occur at any place within the state of Washington.

. The superior courts have jurisdiction over any action brought under the laws of any city or county for the recovery of funds paid by a government entity if the action arises from the same transaction or occurrence as an action brought under RCW 74.66.040 or 74.66.050.

. With respect to any local government that is named as a coplaintiff with the state in an action brought under RCW 74.66.050, a seal on the action ordered by the court under RCW 74.66.050 does not preclude the attorney general or the person bringing the action from serving the complaint, any other pleadings, or the written disclosure of substantially all material evidence and information possessed by the person bringing the action on the law enforcement authorities that are authorized under the law of the local government to investigate and prosecute the action on behalf of the local government, except that the seal applies to the law enforcement authorities so served to the same extent as the seal applies to other parties in the action.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5978-S.SL.pdf?cite=2012%20c%20241%20§%20211[2012 c 241 § 211]; ]

== 74.66.120 - Civil investigative demands.
. [Empty]
.. Whenever the attorney general, or a designee, for purposes of this section, has reason to believe that any person may be in possession, custody, or control of any documentary material or information relevant to a false claims act investigation, the attorney general, or a designee, may, before commencing a civil proceeding under RCW 74.66.040 or making an election under RCW 74.66.050, issue in writing and serve upon the person , a civil investigative demand requiring the person:

... To produce the documentary material for inspection and copying;

... To answer in writing written interrogatories with respect to the documentary material or information;

... To give oral testimony concerning the documentary material or information; or

... To furnish any combination of such material, answers, or testimony.

.. The attorney general may delegate the authority to issue civil investigative demands under this subsection (1). Whenever a civil investigative demand is an express demand for any product of discovery, the attorney general, the deputy attorney general, or an assistant attorney general must serve, in any manner authorized by this section, a copy of the demand upon the person from whom the discovery was obtained and must notify the person to whom the demand is issued of the date on which the copy was served. Any information obtained by the attorney general or a designee of the attorney general under this section may be shared with any qui tam relator if the attorney general or designee determines it is necessary as part of any false claims act investigation.

. [Empty]
.. Each civil investigative demand issued under subsection (1) of this section must state the nature of the conduct constituting the alleged violation of this chapter which is under investigation, and the applicable provision of law alleged to be violated.

.. If the demand is for the production of documentary material, the demand must:

... Describe each class of documentary material to be produced with such definiteness and certainty as to permit the material to be fairly identified;

... Prescribe a return date for each class which will provide a reasonable period of time within which the material so demanded may be assembled and made available for inspection and copying; and

... Identify the false claims act investigator to whom such material must be made available.

.. If the demand is for answers to written interrogatories, the demand must:

... Set forth with specificity the written interrogatories to be answered;

... Prescribe dates at which time answers to written interrogatories must be submitted; and

... Identify the false claims law investigator to whom such answers must be submitted.

.. If the demand is for the giving of oral testimony, the demand must:

... Prescribe a date, time, and place at which oral testimony must be commenced;

... Identify a false claims act investigator who must conduct the examination and the custodian to whom the transcript of the examination must be submitted;

... Specify that the attendance and testimony are necessary to the conduct of the investigation;

... Notify the person receiving the demand of the right to be accompanied by an attorney and any other representative; and

.. Describe the general purpose for which the demand is being issued and the general nature of the testimony, including the primary areas of inquiry, which will be taken pursuant to the demand.

.. Any civil investigative demand issued under this section which is an express demand for any product of discovery is not due until thirty days after a copy of the demand has been served upon the person from whom the discovery was obtained.

.. The date prescribed for the commencement of oral testimony pursuant to a civil investigative demand issued under this section may not be sooner than six days after the date on which demand is received, unless the attorney general or an assistant attorney general designated by the attorney general determines that exceptional circumstances are present which warrant the commencement of the testimony sooner.

.. The attorney general may not authorize the issuance under this section of more than one civil investigative demand for oral testimony by the same person unless the person requests otherwise or unless the attorney general, after investigation, notifies that person in writing that an additional demand for oral testimony is necessary.

. A civil investigative demand issued under subsection (1) or (2) of this section may not require the production of any documentary material, the submission of any answers to written interrogatories, or the giving of any oral testimony if the material, answers, or testimony would be protected from disclosure under:

.. The standards applicable to subpoenas or subpoenas duces tecum issued by a court to aid in a special inquiry investigation; or

.. The standards applicable to discovery requests under the superior court civil rules, to the extent that the application of these standards to any demand is appropriate and consistent with the provisions and purposes of this section.

. Any demand which is an express demand for any product of discovery supersedes any inconsistent order, rule, or provision of law, other than this section, preventing or restraining disclosure of the product of discovery to any person. Disclosure of any product of discovery pursuant to any express demand does not constitute a waiver of any right or privilege which the person making such disclosure may be entitled to invoke to resist discovery of trial preparation materials.

. Any civil investigative demand issued under this section may be served by a false claims act investigator, or by a commissioned law enforcement official, at any place within the state of Washington.

. Service of any civil investigative demand issued under (a) of this subsection or of any petition filed under subsection (25) of this section may be made upon a partnership, corporation, association, or other legal entity by:

.. Delivering an executed copy of the demand or petition to any partner, executive officer, managing agent, or general agent of the partnership, corporation, association, or entity, or to any agent authorized by appointment or by law to receive service of process on behalf of such partnership, corporation, association, or entity;

.. Delivering an executed copy of the demand or petition to the principal office or place of business of the partnership, corporation, association, or entity; or

.. Depositing an executed copy of the demand or petition in the United States mail by registered or certified mail, with a return receipt requested, addressed to such partnership, corporation, association, or entity at its principal office or place of business.

. Service of any demand or petition may be made upon any natural person by:

.. Delivering an executed copy of the demand or petition to the person; or

.. Depositing an executed copy of the demand or petition in the United States mail by registered or certified mail, with a return receipt requested, addressed to the person at the person's residence or principal office or place of business.

. A verified return by the individual serving any civil investigative demand issued under subsection (1) or (2) of this section or any petition filed under subsection (25) of this section setting forth the manner of the service constitutes proof of the service. In the case of service by registered or certified mail, the return must be accompanied by the return post office receipt of delivery of the demand.

. [Empty]
.. The production of documentary material in response to a civil investigative demand served under this section must be made under a sworn certificate, in the form as the demand designates, by:

... In the case of a natural person, the person to whom the demand is directed; or

... In the case of a person other than a natural person, a person having knowledge of the facts and circumstances relating to the production and authorized to act on behalf of the person.

.. The certificate must state that all of the documentary material required by the demand and in the possession, custody, or control of the person to whom the demand is directed has been produced and made available to the false claims act investigator identified in the demand.

. Any person upon whom any civil investigative demand for the production of documentary material has been served under this section shall make such material available for inspection and copying to the false claims act investigator identified in the demand at the principal place of business of the person, or at another place as the false claims act investigator and the person thereafter may agree and prescribe in writing, or as the court may direct under subsection (25) of this section. The material must be made available on the return date specified in the demand, or on a later date as the false claims act investigator may prescribe in writing. The person may, upon written agreement between the person and the false claims act investigator, substitute copies for originals of all or any part of the material.

. [Empty]
.. Each interrogatory in a civil investigative demand served under this section must be answered separately and fully in writing under oath and must be submitted under a sworn certificate, in the form as the demand designates, by:

... In the case of a natural person, the person to whom the demand is directed; or

... In the case of a person other than a natural person, the person or persons responsible for answering each interrogatory.

.. If any interrogatory is objected to, the reasons for the objection must be stated in the certificate instead of an answer. The certificate must state that all information required by the demand and in the possession, custody, control, or knowledge of the person to whom the demand is directed has been submitted. To the extent that any information is not furnished, the information must be identified and reasons set forth with particularity regarding the reasons why the information was not furnished.

. The examination of any person pursuant to a civil investigative demand for oral testimony served under this section must be taken before an officer authorized to administer oaths and affirmations by the laws of the state of Washington or of the place where the examination is held. The officer before whom the testimony is to be taken must put the witness on oath or affirmation and must, personally or by someone acting under the direction of the officer and in the officer's presence, record the testimony of the witness. The testimony must be recorded and must be transcribed. When the testimony is fully transcribed, the officer before whom the testimony is taken shall promptly transmit a copy of the transcript of the testimony to the custodian. This subsection does not preclude the taking of testimony by any means authorized by, and in a manner consistent with, the superior court civil rules.

. The false claims act investigator conducting the examination shall exclude from the place where the examination is held all persons except the person giving the testimony, the attorney for and any other representative of the person giving the testimony, the attorney general, any person who may be agreed upon by the attorney for the government and the person giving the testimony, the officer before whom the testimony is to be taken, and any stenographer taking the testimony.

. The oral testimony of any person taken pursuant to a civil investigative demand served under this section must be taken in the county within which such person resides, is found, or transacts business, or in another place as may be agreed upon by the false claims act investigator conducting the examination and the person.

. When the testimony is fully transcribed, the false claims act investigator or the officer before whom the testimony is taken must afford the witness, who may be accompanied by counsel, a reasonable opportunity to examine and read the transcript, unless the examination and reading are waived by the witness. Any changes in form or substance which the witness desires to make must be entered and identified upon the transcript by the officer or the false claims act investigator, with a statement of the reasons given by the witness for making the changes. The transcript must then be signed by the witness, unless the witness in writing waives the signing, is ill, cannot be found, or refuses to sign. If the transcript is not signed by the witness within thirty days after being afforded a reasonable opportunity to examine it, the officer or the false claims act investigator must sign it and state on the record the fact of the waiver, illness, absence of the witness, or the refusal to sign, together with the reasons given.

. The officer before whom the testimony is taken must certify on the transcript that the witness was sworn by the officer and that the transcript is a true record of the testimony given by the witness, and the officer or false claims act investigator must promptly deliver the transcript, or send the transcript by registered or certified mail, to the custodian.

. Upon payment of reasonable charges therefor, the false claims act investigator must furnish a copy of the transcript to the witness only, except that the attorney general, the deputy attorney general, or an assistant attorney general may, for good cause, limit the witness to inspection of the official transcript of the witness' testimony.

. [Empty]
.. Any person compelled to appear for oral testimony under a civil investigative demand issued under subsection (1) or (2) of this section may be accompanied, represented, and advised by counsel. Counsel may advise the person, in confidence, with respect to any question asked of the person. The person or counsel may object on the record to any question, in whole or in part, and must briefly state for the record the reason for the objection. An objection may be made, received, and entered upon the record when it is claimed that the person is entitled to refuse to answer the question on the grounds of any constitutional or other legal right or privilege, including the privilege against self-incrimination. The person may not otherwise object to or refuse to answer any question, and may not directly or through counsel otherwise interrupt the oral examination. If the person refuses to answer any question, a special injury proceeding petition may be filed in the superior court under subsection (25) of this section for an order compelling the person to answer the question.

.. If the person refuses to answer any question on the grounds of the privilege against self-incrimination, the testimony of the person may be compelled in accordance with the provisions of the superior court civil rules.

. Any person appearing for oral testimony under a civil investigative demand issued under subsection (1) or (2) of this section is entitled to the same fees and allowances which are paid to witnesses in the superior courts.

. The attorney general must designate a false claims act investigator to serve as custodian of documentary material, answers to interrogatories, and transcripts of oral testimony received under this section, and must designate such additional false claims act investigators as the attorney general determines from time to time to be necessary to serve as deputies to the custodian.

. [Empty]
.. A false claims act investigator who receives any documentary material, answers to interrogatories, or transcripts of oral testimony under this section must transmit them to the custodian. The custodian shall take physical possession of the material, answers, or transcripts and is responsible for the use made of them and for the return of documentary material under subsection (23) of this section.

.. The custodian may cause the preparation of the copies of the documentary material, answers to interrogatories, or transcripts of oral testimony as may be required for official use by any false claims act investigator, or employee of the attorney general. The material, answers, and transcripts may be used by any authorized false claims act investigator or other officer or employee in connection with the taking of oral testimony under this section.

.. [Empty]
... Except as otherwise provided in this subsection (21), no documentary material, answers to interrogatories, or transcripts of oral testimony, or copies thereof, while in the possession of the custodian, may be available for examination by any individual other than a false claims act investigator or other officer or employee of the attorney general authorized under (b) of this subsection.

... The prohibition in (c)(i) of this subsection on the availability of material, answers, or transcripts does not apply if consent is given by the person who produced the material, answers, or transcripts, or, in the case of any product of discovery produced pursuant to an express demand for the material, consent is given by the person from whom the discovery was obtained. Nothing in this subsection [(21)](c)(ii) is intended to prevent disclosure to the legislature, including any committee or subcommittee for use by such an agency in furtherance of its statutory responsibilities.

.. While in the possession of the custodian and under the reasonable terms and conditions as the attorney general shall prescribe:

... Documentary material and answers to interrogatories must be available for examination by the person who produced the material or answers, or by a representative of that person authorized by that person to examine the material and answers; and

... Transcripts of oral testimony must be available for examination by the person who produced the testimony, or by a representative of that person authorized by that person to examine the transcripts.

. Whenever any official has been designated to appear before any court, special inquiry judge, or state administrative judge in any case or proceeding, the custodian of any documentary material, answers to interrogatories, or transcripts of oral testimony received under this section may deliver to the official the material, answers, or transcripts for official use in connection with any case or proceeding as the official determines to be required. Upon the completion of such a case or proceeding, the official must return to the custodian any material, answers, or transcripts so delivered which have not passed into the control of any court, grand jury, or agency through introduction into the record of such a case or proceeding.

. If any documentary material has been produced by any person in the course of any false claims act investigation pursuant to a civil investigative demand under this section, and:

.. Any case or proceeding before the court or special inquiry judge arising out of the investigation, or any proceeding before any administrative judge involving the material, has been completed; or

.. No case or proceeding in which the material may be used has been commenced within a reasonable time after completion of the examination and analysis of all documentary material and other information assembled in the course of the investigation:

Then, the custodian shall, upon written request of the person who produced the material, return to the person the material, other than copies furnished to the false claims act investigator under subsection (10) of this section or made for the attorney general under subsection (21)(b) of this section, which has not passed into the control of any court, grand jury, or agency through introduction into the record of the case or proceeding.

. [Empty]
.. In the event of the death, disability, or separation from service of the attorney general of the custodian of any documentary material, answers to interrogatories, or transcripts of oral testimony produced pursuant to civil investigative demand under this section, or in the event of the official relief of the custodian from responsibility for the custody and control of the material, answers, or transcripts, the attorney general must promptly:

... Designate another false claims act investigator to serve as custodian of the material, answers, or transcripts; and

... Transmit in writing to the person who produced the material, answers, or testimony notice of the identity and address of the successor so designated.

.. Any person who is designated to be a successor under this subsection (24) has, with regard to the material, answers, or transcripts, the same duties and responsibilities as were imposed by this section upon that person's predecessor in office, except that the successor may not be held responsible for any default or dereliction which occurred before that designation.

. Whenever any person fails to comply with any civil investigative demand issued under subsection (1) or (2) of this section, or whenever satisfactory copying or reproduction of any material requested in the demand cannot be done and the person refuses to surrender the material, the attorney general may file, in any superior court of the state of Washington for any county in which the person resides, is found, or transacts business, and serve upon the person a petition for an order of the court for the enforcement of the civil investigative demand.

. [Empty]
.. Any person who has received a civil investigative demand issued under subsection (1) or (2) of this section may file, in the superior court of the state of Washington for the county within which the person resides, is found, or transacts business, and serve upon the false claims act investigator identified in the demand a petition for an order of the court to modify or set aside the demand. In the case of a petition addressed to an express demand for any product of discovery, a petition to modify or set aside the demand may be brought only in the district court of the United States for the judicial district in which the proceeding in which the discovery was obtained is or was last pending. Any petition filed under this subsection (26)(a) must be filed:

... Within thirty days after the date of service of the civil investigative demand, or at any time before the return date specified in the demand, whichever date is earlier; or

... Within a longer period as may be prescribed in writing by any false claims act investigator identified in the demand.

.. The petition must specify each ground upon which the petitioner relies in seeking relief under (a) of this subsection, and may be based upon any failure of the demand to comply with the provisions of this section or upon any constitutional or other legal right or privilege of the person. During the pendency of the petition in the court, the court may stay, as it deems proper, the running of the time allowed for compliance with the demand, in whole or in part, except that the person filing the petition shall comply with any portions of the demand not sought to be modified or set aside.

. [Empty]
.. In the case of any civil investigative demand issued under subsection (1) or (2) of this section which is an express demand for any product of discovery, the person from whom the discovery was obtained may file, in the superior court of the state of Washington for the county in which the proceeding in which the discovery was obtained is or was last pending, and serve upon any false claims act investigator identified in the demand and upon the recipient of the demand , a petition for an order of the court to modify or set aside those portions of the demand requiring production of any product of discovery. Any petition under this subsection (27)(a) must be filed:

... Within twenty days after the date of service of the civil investigative demand, or at any time before the return date specified in the demand, whichever date is earlier; or

... Within a longer period as may be prescribed in writing by any false claims act investigator identified in the demand.

.. The petition must specify each ground upon which the petitioner relies in seeking relief under (a) of this subsection, and may be based upon any failure of the portions of the demand from which relief is sought to comply with the provisions of this section, or upon any constitutional or other legal right or privilege of the petitioner. During the pendency of the petition, the court may stay, as it deems proper, compliance with the demand and the running of the time allowed for compliance with the demand.

. At any time during which any custodian is in custody or control of any documentary material or answers to interrogatories produced, or transcripts of oral testimony given, by any person in compliance with any civil investigative demand issued under subsection (1) or (2) of this section, the person , and in the case of an express demand for any product of discovery, the person from whom the discovery was obtained , may file, in the superior court of the state of Washington for the county within which the office of the custodian is situated, and serve upon the custodian , a petition for an order of the court to require the performance by the custodian of any duty imposed upon the custodian by this section.

. Whenever any petition is filed in any superior court of the state of Washington under this section, the court has jurisdiction to hear and determine the matter so presented, and to enter an order or orders as may be required to carry out the provisions of this section. Any final order so entered is subject to appeal under the rules of appellate procedure. Any disobedience of any final order entered under this section by any court must be punished as a contempt of the court.

. The superior court civil rules apply to any petition under this section, to the extent that the rules are not inconsistent with the provisions of this section.

. Any documentary material, answers to written interrogatories, or oral testimony provided under any civil investigative demand issued under subsection (1) or (2) of this section are exempt from disclosure under the public records act, chapter 42.56 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5978-S.SL.pdf?cite=2012%20c%20241%20§%20212[2012 c 241 § 212]; ]

== 74.66.130 - Reporting.
Beginning November 15, 2012, and annually thereafter, the attorney general in consultation with the health care authority must report results of implementing the medicaid fraud false claims act. This report must include:

. The number of attorneys assigned to qui tam initiated actions;

. The number of cases brought by qui tam actions and indicate how many cases are brought by the attorney general and how many by the qui tam relator without attorney general participation;

. The results of any actions brought under subsection (2) of this section, delineated by cases brought by the attorney general and cases brought by the qui tam relator without attorney general participation;

. The amount of recoveries attributable to the medicaid false claims; and

. Information on the costs, attorneys' fees, and any other expenses incurred by defendants in investigating and defending against qui tam actions, to the extent this information is provided to the attorney general or health care authority.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5978-S.SL.pdf?cite=2012%20c%20241%20§%20213[2012 c 241 § 213]; ]

