= 31.35 - Agricultural lenders—Loan guaranty program.
:toc:

== 31.35.010 - Findings—Intent.
The legislature finds and declares that nondepository agricultural lenders can enhance their access to working capital for the purpose of financing agricultural borrowers by using the United States farmers home administration loan guaranty program. The farmers home administration loan guaranty program provides financing to agricultural borrowers needing working capital and longer term financing for the purchase of real estate, agricultural production expenses, debt refinancing, equipment, and the purchase of other fixed assets. Loans can be made to agricultural borrowers by nondepository lenders and guaranteed by the farmers home administration only if the state provides an ongoing opportunity for examination of such entities to confirm good lending practices and solvency.

It is the intent of the legislature to empower the director of financial institutions to examine nondepository agricultural lenders for the purpose of allowing such lenders to qualify for participation in the farmers home administration loan guaranty program.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20251[1994 c 92 § 251]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c134.pdf?cite=1990%20c%20134%20§%201[1990 c 134 § 1]; ]

== 31.35.020 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Agricultural lender" means a Washington corporation incorporated under Title 23B or 24 RCW and qualified as such under this chapter and the jurisdiction of the federal government agency sponsoring the loan guaranty program.

. "Director" means the director of financial institutions.

. "Loan guaranty program" means the farmers home administration loan guaranty program, or any other government program for which the agricultural lender is eligible and which has as its function the provision, facilitation, or financing of agricultural business operations.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20252[1994 c 92 § 252]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c134.pdf?cite=1990%20c%20134%20§%202[1990 c 134 § 2]; ]

== 31.35.030 - Administration—Rules—Duties of director.
. The director shall administer this chapter. The director may issue orders and adopt rules that, in the opinion of the director, are necessary to execute, enforce, and effectuate the purposes of this chapter. Rules to enforce the provisions of this chapter shall be adopted under the administrative procedure act, chapter 34.05 RCW.

. An application filed with the director under this chapter shall be in such form and contain such information as required by the director by rule and be consistent with the requirements of the loan guaranty program.

. After the director is satisfied that the applicant has satisfied all the conditions necessary for approval, the director shall issue a license to the applicant authorizing it to be an agricultural lender under this chapter.

. Any change of control of an agricultural lender shall be subject to the approval of the director. Such approval shall be subject to the same criteria as the criteria for approval of the original license. For purposes of this subsection, "change of control" means directly or indirectly, alone or in concert with others, to own, control, or hold the power to vote ten percent or more of the outstanding voting stock of an agricultural lender or the power to elect or control the election of a majority of the board of directors of an agricultural lender.

. The director may deny, suspend, or revoke a license if the agricultural lender violates any provision of this chapter or any rules promulgated pursuant to this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20253[1994 c 92 § 253]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c134.pdf?cite=1990%20c%20134%20§%203[1990 c 134 § 3]; ]

== 31.35.040 - Participation by agricultural lender—Powers and privileges.
. An agricultural lender may participate in a loan guaranty program. If an agricultural lender participates in a loan guaranty program, the agricultural lender shall comply with the requirements of that program.

. An agricultural lender may be incorporated under either the Washington business corporation act, Title 23B RCW, or the Washington nonprofit corporation act, Title 24 RCW. In addition to the powers and privileges provided to an agricultural lender by this chapter, an agricultural lender has all the powers and privileges conferred by its incorporating statute that are not inconsistent with or limited by this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c134.pdf?cite=1990%20c%20134%20§%204[1990 c 134 § 4]; ]

== 31.35.050 - Costs of supervision—Fees.
. The director is authorized to charge a fee for the estimated direct and indirect costs for examination and supervision by the director of an agricultural lender or a subsidiary of an agricultural lender. Excess examiner time shall be billed at a reasonable rate established by rule.

. All such fees shall be deposited in the financial services regulation fund and administered consistent with the provisions of RCW 43.320.110.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1211.SL.pdf?cite=2001%20c%20177%20§%207[2001 c 177 § 7]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20254[1994 c 92 § 254]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c134.pdf?cite=1990%20c%20134%20§%205[1990 c 134 § 5]; ]

== 31.35.060 - Responsibility of agricultural lender—Recordkeeping—Loan loss reserve.
. An agricultural lender shall keep books, accounts, and other records in such form and manner as required by the director. These records shall be kept at such place and shall be preserved for such length of time as specified by the director by rule.

. Not more than ninety days after the close of each calendar year, or within a period specified by the director, an agricultural lender shall file with the director a report containing the following:

.. Financial statements, including the balance sheet, the statement of income or loss, the statement of changes in capital accounts, and the statement of changes in financial position; and

.. Other information that the director may require.

. Each agricultural lender shall provide for a loan loss reserve sufficient to cover projected loan losses that are not guaranteed by the United States government or any agency thereof.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20255[1994 c 92 § 255]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c134.pdf?cite=1990%20c%20134%20§%206[1990 c 134 § 6]; ]

== 31.35.070 - Examination of agricultural lender.
. The director shall visit each agricultural lender at least every twenty-four months for the purpose of assuring that the agricultural lender remains in compliance with and qualified for the loan guaranty program.

.. The director may accept timely audited financial statements and other timely reports the director determines to be relevant and accurate as part of a full and complete examination of the agricultural lender. The director shall make an independent review of loans guaranteed by the loan guaranty program.

.. The agricultural lender shall be exempt from examination under this subsection if it terminates its activities under the loan guaranty program and no loans guaranteed by the loan guaranty program remain on the books. This exemption becomes effective upon notification to the director. The director shall confirm termination of activities under the loan guaranty program with the appropriate federal agency.

.. All examination reports and all information obtained by the director and the director's staff in conducting examinations of an agricultural lender are confidential to the same extent bank examinations are confidential under *RCW 30.04.075.

.. All examination reports may be shared with other state or federal agencies consistent with **chapter 30.04 RCW.

. A director, officer, or employee of an agricultural lender or of a subsidiary of an agricultural lender being examined by the director or a person having custody of any of the books, accounts, or records of the agricultural lender or of the subsidiary shall facilitate the examination so far as it is in his or her power to do so.

. If in the opinion of the director it is necessary in the examination of an agricultural lender or of a subsidiary of an agricultural lender, the director may retain any certified public accountant, attorney, appraiser, or other person to assist the director. The agricultural lender being examined shall pay the fees of a person retained by the director under this subsection.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20256[1994 c 92 § 256]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c134.pdf?cite=1990%20c%20134%20§%207[1990 c 134 § 7]; ]

== 31.35.080 - Enforcement—Responsibility of director—Penalty.
. The director shall adopt rules to enforce the intent and purposes of this chapter. Such rules shall include, but not be limited to, the following:

.. Disclosure of conflicts of interest;

.. Prohibition of false statements made to the director on any form required by the director or during any examination; or

.. Prevention of fraud and undue influence within an agricultural lender.

. A violation of any provision of this chapter or any rule of the director adopted under this chapter by an agent, employee, officer, or director of the agricultural lender shall be punishable by a fine, established by the director, not to exceed one hundred dollars for each offense. Each day's continuance of the violation shall be a separate and distinct offense. All fines shall be credited to the financial services regulation fund.

. The director may issue and serve upon an agricultural lender a notice of charges if, in the opinion of the director, the agricultural lender is violating or has violated the law, rule, or any condition imposed in writing by the director or any written agreement made by the director.

.. The notice shall contain a statement of the facts constituting the alleged violation or practice and shall fix a time and place at which a hearing will be held to determine whether an order to cease and desist should issue against the agricultural lender. The hearing shall be set not earlier than ten days nor later than thirty days after service of the notice unless a later date is set by the director at the request of the agricultural lender.

Unless the agricultural lender appears at the hearing by a duly authorized representative, it shall be deemed to have consented to the issuance of the cease and desist order. In the event of consent or if, upon the record made at the hearing, the director finds that any violation or practice specified in the notice of charges has been established, the director may issue and serve upon the agricultural lender an order to cease and desist from the violation or practice. The order may require the agricultural lender and its directors, officers, employees, and agents to cease and desist from the violation or practice and may require the agricultural lender to take affirmative action to correct the conditions resulting from the violation or practice.

.. A cease and desist order shall become effective at the expiration of ten days after the service of the order upon the agricultural lender concerned, except that a cease and desist order issued upon consent shall become effective at the time specified in the order and shall remain effective as provided in the order unless it is stayed, modified, terminated, or set aside by action of the director or a reviewing court.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1211.SL.pdf?cite=2001%20c%20177%20§%208[2001 c 177 § 8]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20257[1994 c 92 § 257]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c134.pdf?cite=1990%20c%20134%20§%208[1990 c 134 § 8]; ]

== 31.35.090 - Enforcement—Court order.
If, in the opinion of the director, an agricultural lender violates or there is reasonable cause to believe that an agricultural lender is about to violate any provision of this chapter or any rule adopted under this chapter, the director may bring an action in the appropriate court to enjoin the violation or to enforce compliance. Upon a proper showing, a restraining order, or preliminary or permanent injunction, shall be granted, and a receiver or a conservator may be appointed for the agricultural lender or the agricultural lender's assets.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20258[1994 c 92 § 258]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c134.pdf?cite=1990%20c%20134%20§%209[1990 c 134 § 9]; ]

== 31.35.100 - Notice—Investments not insured.
All agricultural lenders shall notify their members at the time of membership and annually thereafter that their investment in the agricultural lender, although regulated by the director, is not insured, guaranteed, or protected by any federal or state agency.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20259[1994 c 92 § 259]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c134.pdf?cite=1990%20c%20134%20§%2010[1990 c 134 § 10]; ]

== 31.35.105 - Application of RCW  31.24.230.
RCW 31.24.230 (2) through (4) supersede any contrary provision of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6168-S.SL.pdf?cite=2006%20c%2087%20§%2028[2006 c 87 § 28]; ]

== 31.35.900 - Severability—Administrative review—1990 c 134.
If any provision of this act or its application to any person or circumstance is held invalid or, if in the written opinion of the farmers home administration, is contrary to the intent and purposes of the loan guaranty program, the director shall not enforce such provision, but the remainder of the act or the application of the provision to other persons or circumstances shall not be affected.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20260[1994 c 92 § 260]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c134.pdf?cite=1990%20c%20134%20§%2011[1990 c 134 § 11]; ]

