= 31.40 - Federally guaranteed small business loans.
:toc:

== 31.40.010 - Intent.
The legislature finds and declares that small and moderate-size companies can enhance their access to working capital and to capital for acquiring and equipping commercial and industrial facilities by using the United States small business administration national small business loan program known as the 7(a) loan guaranty program. The 7(a) loan guaranty program provides financing to small firms needing working capital and longer term financing for equipment and other fixed assets. Such loans can be made to small businesses by nondepository lenders and guaranteed by the small business administration only if the state provides for the ongoing regulation and examination of such entities.

It is the intent of the legislature that the director of financial institutions [license], regulate, and subject to ongoing examination, nondepository lenders for the purpose of allowing such lenders to participate in the small business administration's 7(a) loan guaranty program.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20261[1994 c 92 § 261]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c212.pdf?cite=1989%20c%20212%20§%201[1989 c 212 § 1]; ]

== 31.40.020 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Licensee" means a Washington corporation licensed under the terms of this chapter.

. "Director" means the director of financial institutions.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20262[1994 c 92 § 262]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c212.pdf?cite=1989%20c%20212%20§%202[1989 c 212 § 2]; ]

== 31.40.030 - Director—Powers and duties.
. The director shall administer this chapter. The director may issue orders and adopt rules that, in the opinion of the director, are necessary to execute, enforce, and effectuate the purposes of this chapter. Rules to enforce the provisions of this chapter shall be adopted under the administrative procedure act, chapter 34.05 RCW.

. Whenever the director issues an order or a license under this chapter, the director may impose conditions that are necessary, in the opinion of the director, to carry out the purposes of this chapter.

. An application filed with the director under this chapter shall be in such a form and contain such information as the director may require.

. Any change of control of a licensee shall be subject to the approval of the director. Such approval shall be subject to the same criteria as the criteria for approval of the original license. For purposes of this subsection, "change of control" means directly or indirectly, alone or in concert with others, to own, control, or hold the power to vote ten percent or more of the outstanding voting stock of a licensee or the power to elect or control the election of a majority of the board of directors of the licensee.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20263[1994 c 92 § 263]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c212.pdf?cite=1989%20c%20212%20§%203[1989 c 212 § 3]; ]

== 31.40.040 - Licensee—Powers and duties.
. A licensee may participate in the 7(a) loan guaranty program of the small business administration pursuant to section 7(a) of the federal small business investment act of 1958, 15 U.S.C. Sec. 636(a), or any other government program for which the licensee is eligible and which has as its function the provision or facilitation of financing or management assistance to business firms. If a licensee participates in a program referred to in this section, the licensee shall comply with the requirements of that program.

. A licensee may be incorporated under either the Washington business corporation act or the Washington nonprofit corporation act. In addition to the powers and privileges provided to a licensee by this chapter, a licensee has all the powers and privileges conferred by its incorporating statute which are not inconsistent with or limited by this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c212.pdf?cite=1989%20c%20212%20§%204[1989 c 212 § 4]; ]

== 31.40.050 - License approval.
After a review of information regarding the directors, officers, and controlling persons of the applicant for a license, a review of the applicant's business plan, including at least three years of detailed financial projections and other relevant information, and a review of such additional information as is considered relevant by the director, the director shall approve an application for a license if, and only if, the director determines that:

. The applicant is capitalized in an amount that is not less than five hundred thousand dollars and that such sum is adequate for the applicant to transact business as a nondepository 7(a) lender and that in evaluating the capital position of the applicant the director may consider and include the net worth of any corporate shareholder of the applicant corporation if the shareholder guarantees the liabilities of the applicant: PROVIDED, That such corporate shareholder be subject to the reporting requirements of RCW 31.40.080;

. Each director, officer, and controlling person of the applicant is of good character and sound financial standing; that the directors and officers of the applicant are competent to perform their functions with respect to the applicant; and that the directors and officers of the applicant are collectively adequate to manage the business of the applicant as a nondepository 7(a) lender;

. The business plan of the applicant will be honestly and efficiently conducted in accordance with the intent and purposes of this chapter; and

. The proposed activity possesses a reasonable prospect for success.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20264[1994 c 92 § 264]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c212.pdf?cite=1989%20c%20212%20§%205[1989 c 212 § 5]; ]

== 31.40.060 - Prohibited loans—Exception.
. Either by itself or in concert with a director, officer, principal shareholder, or affiliate, or with another licensee, a licensee shall not hold control of a business firm to which it has made a loan under section 7(a) of the federal small business investment act of 1958, 15 U.S.C. Sec. 636(a), except that, to the extent necessary to protect the licensee's interest as creditor of the business firm, a licensee that provides financing assistance to a business firm may acquire and hold control of that business firm. Unless the director approves a longer period, a licensee holding control of a business firm under this section shall divest itself of the interest which constitutes holding control as soon as practicable or within five years after acquiring that interest, whichever is sooner.

. For the purposes of subsection (1) of this section, "hold control" means alone or in concert with others:

.. Ownership, directly or indirectly, of record or beneficially, of voting securities greater than:

... For a business firm with outstanding voting securities held by fewer than fifty shareholders, forty percent of the outstanding voting securities;

... For a business firm with outstanding voting securities held by fifty or more shareholders, twenty-five percent of the outstanding voting securities;

.. Being able to elect or control the election of a majority of the board of directors.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20265[1994 c 92 § 265]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c212.pdf?cite=1989%20c%20212%20§%206[1989 c 212 § 6]; ]

== 31.40.070 - Fees.
. The director is authorized to charge a fee for the estimated direct and indirect costs of the following:

.. An application for a license and the investigation thereof;

.. An application for approval to acquire control of a licensee and the investigation thereof;

.. An application for approval for a licensee to merge with another corporation, an application for approval for a licensee to purchase all or substantially all of the business of another person, or an application for approval for a licensee to sell all or substantially all of its business or of the business of any of its offices to another licensee and the investigation thereof;

.. An annual license;

.. An examination by the director of a licensee or a subsidiary of a licensee. Excess examiner time shall be billed at a reasonable rate established by rule.

. A fee for filing an application with the director shall be paid at the time the application is filed with the director.

. All such fees shall be deposited in the financial services regulation fund and administered consistent with the provisions of RCW 43.320.110.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1211.SL.pdf?cite=2001%20c%20177%20§%209[2001 c 177 § 9]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20266[1994 c 92 § 266]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c212.pdf?cite=1989%20c%20212%20§%207[1989 c 212 § 7]; ]

== 31.40.080 - Records—Reports—Loan loss reserve.
. A licensee shall keep books, accounts, and other records in such a form and manner as the director may require. These records shall be kept at such a place and shall be preserved for such a length of time as the director may specify.

. Not more than ninety days after the close of each calendar year or within a period specified by the director, a licensee shall file with the director a report containing the following:

.. Financial statements, including the balance sheet, the statement of income or loss, the statement of changes in capital accounts and the statement of changes in financial position; and

.. Other information that the director may require.

. Each licensee shall provide for a loan loss reserve sufficient to cover projected loan losses which are not guaranteed by the United States government or any agency thereof.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20267[1994 c 92 § 267]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c212.pdf?cite=1989%20c%20212%20§%208[1989 c 212 § 8]; ]

== 31.40.090 - Examination of licensees.
. The director shall examine each licensee not less than once every twenty-four months.

. The director may with or without notice and at any time during regular business hours examine a licensee or a subsidiary of a licensee.

. A director, officer, or employee of a licensee or of a subsidiary of a licensee being examined by the director or a person having custody of any of the books, accounts, or records of the licensee or of the subsidiary shall otherwise facilitate the examination so far as it is in his or her power to do so.

. If in the director's opinion it is necessary in the examination of a licensee, or of a subsidiary of a licensee, the director may retain any certified public accountant, attorney, appraiser, or other person to assist the director. The licensee being examined shall pay the fees of a person retained by the director under this subsection.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6168-S.SL.pdf?cite=2006%20c%2087%20§%2030[2006 c 87 § 30]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20268[1994 c 92 § 268]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c212.pdf?cite=1989%20c%20212%20§%209[1989 c 212 § 9]; ]

== 31.40.100 - Application denial.
If the director denies an application, the director shall provide the applicant with a written statement explaining the basis for the denial.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20269[1994 c 92 § 269]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c212.pdf?cite=1989%20c%20212%20§%2010[1989 c 212 § 10]; ]

== 31.40.110 - Rules—Penalties.
. The director shall adopt rules to enforce the intent and purposes of this chapter. Such rules shall include, but need not be limited to, the following:

.. Disclosure of conflicts of interest;

.. Prohibition of false statements made to the director on any form required by the director or during any examination requested by the director; or

.. Prevention of fraud and undue influence by a licensee.

. A violation of any provision of this chapter or any rule of the director adopted under this chapter by an agent, employee, officer, or director of the licensee shall be punishable by a fine, established by the director, not to exceed one hundred dollars for each offense. Each day's continuance of the violation shall be a separate and distinct offense. Each such fine shall be credited to the financial services regulation fund.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1211.SL.pdf?cite=2001%20c%20177%20§%2010[2001 c 177 § 10]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20270[1994 c 92 § 270]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c212.pdf?cite=1989%20c%20212%20§%2011[1989 c 212 § 11]; ]

== 31.40.120 - Injunction.
If, in the opinion of the director, a person violates or there is reasonable cause to believe that a person is about to violate any provision of this chapter or any rule adopted under this chapter, the director may bring an action in the appropriate court to enjoin the violation or to enforce compliance. Upon a proper showing, a restraining order, preliminary or permanent injunction, shall be granted, and a receiver or a conservator may be appointed for the defendant or the defendant's assets.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20271[1994 c 92 § 271]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c212.pdf?cite=1989%20c%20212%20§%2012[1989 c 212 § 12]; ]

== 31.40.130 - Penalty—License impairment.
The director may deny, suspend, or revoke a license if the applicant or holder violates any provision of this chapter or any rules promulgated pursuant to this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20272[1994 c 92 § 272]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c212.pdf?cite=1989%20c%20212%20§%2013[1989 c 212 § 13]; ]

== 31.40.135 - Application of RCW  31.24.230.
RCW 31.24.230 (1), (3), and (4) supersede any contrary provision of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6168-S.SL.pdf?cite=2006%20c%2087%20§%2029[2006 c 87 § 29]; ]

== 31.40.900 - Severability—1989 c 212.
If any provision of this act or its application to any person or circumstance is held invalid or, if in the written opinion of the small business administration, is contrary to the intent and purposes of the 7(a) loan guaranty program, the director shall not enforce such provision but the remainder of the act or the application of the provision to other persons or circumstances shall not be affected.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20273[1994 c 92 § 273]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c212.pdf?cite=1989%20c%20212%20§%2016[1989 c 212 § 16]; ]

