= 76.09 - Forest practices.
:toc:

== 76.09.010 - Legislative finding and declaration.
. The legislature hereby finds and declares that the forestland resources are among the most valuable of all resources in the state; that a viable forest products industry is of prime importance to the state's economy; that it is in the public interest for public and private commercial forestlands to be managed consistent with sound policies of natural resource protection; that coincident with maintenance of a viable forest products industry, it is important to afford protection to forest soils, fisheries, wildlife, water quantity and quality, air quality, recreation, and scenic beauty.

. The legislature further finds and declares it to be in the public interest of this state to create and maintain through the adoption of this chapter a comprehensive statewide system of laws and forest practices rules which will achieve the following purposes and policies:

.. Afford protection to, promote, foster and encourage timber growth, and require such minimum reforestation of commercial tree species on forestlands as will reasonably utilize the timber growing capacity of the soil following current timber harvest;

.. Afford protection to forest soils and public resources by utilizing all reasonable methods of technology in conducting forest practices;

.. Recognize both the public and private interest in the profitable growing and harvesting of timber;

.. Promote efficiency by permitting maximum operating freedom consistent with the other purposes and policies stated herein;

.. Provide for regulation of forest practices so as to avoid unnecessary duplication in such rules;

.. Provide for interagency input and intergovernmental and tribal coordination and cooperation;

.. Achieve compliance with all applicable requirements of federal and state law with respect to nonpoint sources of water pollution from forest practices;

.. To consider reasonable land use planning goals and concepts contained in local comprehensive plans and zoning regulations;

.. Foster cooperation among managers of public resources, forestland owners, Indian tribes and the citizens of the state; 

.. Develop a watershed analysis system that addresses the cumulative effect of forest practices on, at a minimum, the public resources of fish, water, and public capital improvements of the state and its political subdivisions; and

.. Assist forestland owners in accessing market capital and financing for the ecosystem services provided to the public as a result of the protection of public resources.

. The legislature further finds and declares that it is also in the public interest of the state to encourage forestland owners to undertake corrective and remedial action to reduce the impact of mass earth movements and fluvial processes.

. The legislature further finds and declares that it is in the public interest that the applicants for state forest practices permits should assist in paying for the cost of review and permitting necessary for the environmental protection of these resources.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2541-S.SL.pdf?cite=2010%20c%20188%20§%203[2010 c 188 § 3]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2091-S.SL.pdf?cite=1999%20sp.s.%20c%204%20§%20901[1999 sp.s. c 4 § 901]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5981-S.SL.pdf?cite=1993%20c%20443%20§%201[1993 c 443 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c95.pdf?cite=1987%20c%2095%20§%201[1987 c 95 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c137.pdf?cite=1974%20ex.s.%20c%20137%20§%201[1974 ex.s. c 137 § 1]; ]

== 76.09.020 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Adaptive management" means reliance on scientific methods to test the results of actions taken so that the management and related policy can be changed promptly and appropriately.

. "Appeals board" means the pollution control hearings board created by RCW 43.21B.010.

. "Application" means the application required pursuant to RCW 76.09.050.

. "Aquatic resources" includes water quality, salmon, other species of the vertebrate classes Cephalaspidomorphi and Osteichthyes identified in the forests and fish report, the Columbia torrent salamander (Rhyacotriton kezeri), the Cascade torrent salamander (Rhyacotriton cascadae), the Olympic torrent salamander (Rhyacotriton olympian), the Dunn's salamander (Plethodon dunni), the Van Dyke's salamander (Plethodon vandyke), the tailed frog (Ascaphus truei), and their respective habitats.

. "Board" means the forest practices board created in RCW 76.09.030.

. "Commissioner" means the commissioner of public lands.

. "Contiguous" means land adjoining or touching by common corner or otherwise. Land having common ownership divided by a road or other right-of-way shall be considered contiguous.

. "Conversion to a use other than commercial timber operation" means a bona fide conversion to an active use which is incompatible with timber growing and as may be defined by forest practices rules.

. "Date of receipt" has the same meaning as defined in RCW 43.21B.001.

. "Department" means the department of natural resources.

. "Ecosystem services" means the benefits that the public enjoys as a result of natural processes and biological diversity.

. "Ecosystem services market" means a system in which providers of ecosystem services can access financing or market capital to protect, restore, and maintain ecological values, including the full spectrum of regulatory, quasiregulatory, and voluntary markets.

. "Fill" means the placement of earth material or aggregate for road or landing construction or other similar activities.

. "Fish passage barrier" means any artificial instream structure that impedes the free passage of fish.

. "Forestland" means all land which is capable of supporting a merchantable stand of timber and is not being actively used for a use which is incompatible with timber growing. Forestland does not include agricultural land that is or was enrolled in the conservation reserve enhancement program by contract if such agricultural land was historically used for agricultural purposes and the landowner intends to continue to use the land for agricultural purposes in the future. As it applies to the operation of the road maintenance and abandonment plan element of the forest practices rules on small forestland owners, the term "forestland" excludes:

.. Residential home sites, which may include up to five acres; and

.. Cropfields, orchards, vineyards, pastures, feedlots, fish pens, and the land on which appurtenances necessary to the production, preparation, or sale of crops, fruit, dairy products, fish, and livestock exist.

. "Forestland owner" means any person in actual control of forestland, whether such control is based either on legal or equitable title, or on any other interest entitling the holder to sell or otherwise dispose of any or all of the timber on such land in any manner. However, any lessee or other person in possession of forestland without legal or equitable title to such land shall be excluded from the definition of "forestland owner" unless such lessee or other person has the right to sell or otherwise dispose of any or all of the timber located on such forestland.

. "Forest practice" means any activity conducted on or directly pertaining to forestland and relating to growing, harvesting, or processing timber, including but not limited to:

.. Road and trail construction, including forest practices hydraulic projects that include water crossing structures, and associated activities and maintenance;

.. Harvesting, final and intermediate;

.. Precommercial thinning;

.. Reforestation;

.. Fertilization;

.. Prevention and suppression of diseases and insects;

.. Salvage of trees; and

.. Brush control.

"Forest practice" shall not include preparatory work such as tree marking, surveying and road flagging, and removal or harvesting of incidental vegetation from forestlands such as berries, ferns, greenery, mistletoe, herbs, mushrooms, and other products which cannot normally be expected to result in damage to forest soils, timber, or public resources.

. "Forest practices hydraulic project" means a hydraulic project, as defined under RCW 77.55.011, that requires a forest practices application or notification under this chapter.

. "Forest practices rules" means any rules adopted pursuant to RCW 76.09.040.

. "Forest road," as it applies to the operation of the road maintenance and abandonment plan element of the forest practices rules on small forestland owners, means a road or road segment that crosses land that meets the definition of forestland, but excludes residential access roads.

. "Forest trees" does not include hardwood trees cultivated by agricultural methods in growing cycles shorter than fifteen years if the trees were planted on land that was not in forest use immediately before the trees were planted and before the land was prepared for planting the trees. "Forest trees" includes Christmas trees, but does not include Christmas trees that are cultivated by agricultural methods, as that term is defined in RCW 84.33.035.

. "Forests and fish report" means the forests and fish report to the board dated April 29, 1999.

. "Operator" means any person engaging in forest practices except an employee with wages as his or her sole compensation.

. "Person" means any individual, partnership, private, public, or municipal corporation, county, the department or other state or local governmental entity, or association of individuals of whatever nature.

. "Public resources" means water, fish and wildlife, and in addition shall mean capital improvements of the state or its political subdivisions.

. "Small forestland owner" has the same meaning as defined in RCW 76.09.450.

. "Timber" means forest trees, standing or down, of a commercial species, including Christmas trees. However, "timber" does not include Christmas trees that are cultivated by agricultural methods, as that term is defined in RCW 84.33.035.

. "Timber owner" means any person having all or any part of the legal interest in timber. Where such timber is subject to a contract of sale, "timber owner" shall mean the contract purchaser.

. "Unconfined channel migration zone" means the area within which the active channel of an unconfined stream is prone to move and where the movement would result in a potential near-term loss of riparian forest adjacent to the stream. Sizeable islands with productive timber may exist within the zone.

. "Unconfined stream" means generally fifth order or larger waters that experience abrupt shifts in channel location, creating a complex floodplain characterized by extensive gravel bars, disturbance species of vegetation of variable age, numerous side channels, wall-based channels, oxbow lakes, and wetland complexes. Many of these streams have dikes and levees that may temporarily or permanently restrict channel movement.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6406-S.SL.pdf?cite=2012%201st%20sp.s.%20c%201%20§%20212[2012 1st sp.s. c 1 § 212]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2935-S.SL.pdf?cite=2010%20c%20210%20§%2019[2010 c 210 § 19]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2541-S.SL.pdf?cite=2010%20c%20188%20§%206[2010 c 188 § 6]; prior:  2009 c 354 § 5; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5401-S.SL.pdf?cite=2009%20c%20246%20§%204[2009 c 246 § 4]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1095-S2.SL.pdf?cite=2003%20c%20311%20§%203[2003 c 311 § 3]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6241-S.SL.pdf?cite=2002%20c%2017%20§%201[2002 c 17 § 1]; prior:  2001 c 102 § 1; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5108.SL.pdf?cite=2001%20c%2097%20§%202[2001 c 97 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2091-S.SL.pdf?cite=1999%20sp.s.%20c%204%20§%20301[1999 sp.s. c 4 § 301]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c137.pdf?cite=1974%20ex.s.%20c%20137%20§%202[1974 ex.s. c 137 § 2]; ]

== 76.09.030 - Forest practices board—Created—Membership—Terms—Vacancies—Meetings—Compensation, travel expenses—Staff.
. There is hereby created the forest practices board of the state of Washington as an agency of state government consisting of members as follows:

.. The commissioner of public lands or the commissioner's designee;

.. The director of the department of commerce or the director's designee;

.. The director of the department of agriculture or the director's designee;

.. The director of the department of ecology or the director's designee;

.. The director of the department of fish and wildlife or the director's designee;

.. An elected member of a county legislative authority appointed by the governor. However, the county member's service on the board shall be conditioned on the member's continued service as an elected county official;

.. One member representing a timber products union, appointed by the governor from a list of three names submitted by a timber labor coalition affiliated with a statewide labor organization that represents a majority of the timber product unions in the state; and

.. Six members of the general public appointed by the governor, one of whom shall be a small forestland owner who actively manages his or her land, and one of whom shall be an independent logging contractor.

. The members of the initial board appointed by the governor shall be appointed so that the term of one member shall expire December 31, 1975, the term of one member shall expire December 31, 1976, the term of one member shall expire December 31, 1977, the terms of two members shall expire December 31, 1978, and the terms of two members shall expire December 31, 1979. Thereafter, each member shall be appointed for a term of four years. Vacancies on the board shall be filled in the same manner as the original appointments. Each member of the board shall continue in office until his or her successor is appointed and qualified. The commissioner of public lands or the commissioner's designee shall be the chair of the board.

. The board shall meet at such times and places as shall be designated by the chair or upon the written request of the majority of the board. The principal office of the board shall be at the state capital.

. Members of the board, except public employees and elected officials, shall be compensated in accordance with RCW 43.03.250. Each member shall be entitled to reimbursement for travel expenses incurred in the performance of their duties as provided in RCW 43.03.050 and 43.03.060.

. The board may employ such clerical help and staff pursuant to chapter 41.06 RCW as is necessary to carry out its duties.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6406-S.SL.pdf?cite=2012%201st%20sp.s.%20c%201%20§%20211[2012 1st sp.s. c 1 § 211]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2893-S.SL.pdf?cite=2008%20c%2046%20§%201[2008 c 46 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5172.SL.pdf?cite=2003%20c%2039%20§%2032[2003 c 39 § 32]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2091-S.SL.pdf?cite=1999%20sp.s.%20c%204%20§%201001[1999 sp.s. c 4 § 1001]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1014.SL.pdf?cite=1995%20c%20399%20§%20207[1995 c 399 § 207]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1751.SL.pdf?cite=1993%20c%20257%20§%201[1993 c 257 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c330.pdf?cite=1987%20c%20330%20§%201301[1987 c 330 § 1301]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c466.pdf?cite=1985%20c%20466%20§%2070[1985 c 466 § 70]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c287.pdf?cite=1984%20c%20287%20§%20108[1984 c 287 § 108]; 1975-'76 2nd ex.s. c 34 § 173; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c200.pdf?cite=1975%201st%20ex.s.%20c%20200%20§%201[1975 1st ex.s. c 200 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c137.pdf?cite=1974%20ex.s.%20c%20137%20§%203[1974 ex.s. c 137 § 3]; ]

== 76.09.040 - Forest practices rules—Adoption—Review of proposed rules—Hearings—Fish protection standards—Program for the acquisition of riparian open space.
. [Empty]
.. Where necessary to accomplish the purposes and policies stated in RCW 76.09.010, and to implement the provisions of this chapter, the board shall adopt forest practices rules pursuant to chapter 34.05 RCW and in accordance with the procedures enumerated in this section that:

... Establish minimum standards for forest practices;

... Provide procedures for the voluntary development of resource management plans which may be adopted as an alternative to the minimum standards in (a)(i) of this subsection if the plan is consistent with the purposes and policies stated in RCW 76.09.010 and the plan meets or exceeds the objectives of the minimum standards;

... Set forth necessary administrative provisions;

... Establish procedures for the collection and administration of forest practice fees as set forth by this chapter; and

.. Allow for the development of watershed analyses.

.. Forest practices rules pertaining to water quality protection shall be adopted by the board after reaching agreement with the director of the department of ecology or the director's designee on the board with respect to these rules. All other forest practices rules shall be adopted by the board.

.. Forest practices rules shall be administered and enforced by either the department or the local governmental entity as provided in this chapter. Such rules shall be adopted and administered so as to give consideration to all purposes and policies set forth in RCW 76.09.010.

. [Empty]
.. The board shall prepare proposed forest practices rules consistent with this section and chapter 34.05 RCW. In addition to any forest practices rules relating to water quality protection proposed by the board, the department of ecology may submit to the board proposed forest practices rules relating to water quality protection.

.. [Empty]
... The board shall hold one or more hearings on the proposed rules pursuant to chapter 34.05 RCW. Any county representative may propose specific forest practices rules relating to problems existing within the county at the hearings.

... The board may adopt and the department of ecology may approve such proposals if they find the proposals are consistent with the purposes and policies of this chapter.

. [Empty]
.. The board shall incorporate into the forest practices rules those fish protection standards in the rules adopted under chapter 77.55 RCW, as the rules existed on July 10, 2012, that are applicable to activities regulated under the forest practices rules. If fish protection standards are incorporated by reference, the board shall minimize administrative processes by utilizing the exception from the administrative procedures controlling significant legislative rules under RCW 34.05.328(5)(b)(iii) for the incorporation of rules adopted by other state agencies.

.. Thereafter, the board shall incorporate into the forest practices rules any changes to those fish protection standards in the rules adopted under chapter 77.55 RCW that are: (i) Adopted consistent with RCW 77.55.361; and (ii) applicable to activities regulated under the forest practices rules. If fish protection standards are incorporated by reference, the board shall minimize administrative processes by utilizing the exception from the administrative procedures controlling significant legislative rules under RCW 34.05.328(5)(b)(iii) for the incorporation of rules adopted by other state agencies.

.. The board shall establish and maintain technical guidance in the forest practices board manual, as provided under WAC 222-12-090 as it existed on July 10, 2012, to assist with implementation of the standards incorporated into the forest practices rules under this section. The guidance must include best management practices and standard techniques to ensure fish protection.

.. The board must complete the requirements of (a) of this subsection and establish initial technical guidance under (c) of this subsection by December 31, 2013.

. [Empty]
.. The board shall establish by rule a program for the acquisition of riparian open space and critical habitat for threatened or endangered species as designated by the board. Acquisition must be a conservation easement. Lands eligible for acquisition are forestlands within unconfined channel migration zones or forestlands containing critical habitat for threatened or endangered species as designated by the board. Once acquired, these lands may be held and managed by the department, transferred to another state agency, transferred to an appropriate local government agency, or transferred to a private nonprofit nature conservancy corporation, as defined in RCW 64.04.130, in fee or transfer of management obligation. The board shall adopt rules governing the acquisition by the state or donation to the state of such interest in lands including the right of refusal if the lands are subject to unacceptable liabilities. The rules shall include definitions of qualifying lands, priorities for acquisition, and provide for the opportunity to transfer such lands with limited warranties and with a description of boundaries that does not require full surveys where the cost of securing the surveys would be unreasonable in relation to the value of the lands conveyed. The rules shall provide for the management of the lands for ecological protection or fisheries enhancement. For the purposes of conservation easements entered into under this section, the following apply:

... For conveyances of a conservation easement in which the landowner conveys an interest in the trees only, the compensation must include the timber value component, as determined by the cruised volume of any timber located within the channel migration zone or critical habitat for threatened or endangered species as designated by the board, multiplied by the appropriate quality code stumpage value for timber of the same species shown on the appropriate table used for timber harvest excise tax purposes under RCW 84.33.091;

... For conveyances of a conservation easement in which the landowner conveys interests in both land and trees, the compensation must include the timber value component in (a)(i) of this subsection plus such portion of the land value component as determined just and equitable by the department. The land value component must be the acreage of qualifying channel migration zone or critical habitat for threatened or endangered species as determined by the board, to be conveyed, multiplied by the average per acre value of all commercial forestland in western Washington or the average for eastern Washington, whichever average is applicable to the qualifying lands. The department must determine the western and eastern Washington averages based on the land value tables established by RCW 84.33.140 and revised annually by the department of revenue.

.. Subject to appropriations sufficient to cover the cost of such an acquisition program and the related costs of administering the program, the department must establish a conservation easement in land that an owner tenders for purchase; provided that such lands have been taxed as forestlands and are located within an unconfined channel migration zone or contain critical habitat for threatened or endangered species as designated by the board. Lands acquired under this section shall become riparian or habitat open space. These acquisitions shall not be deemed to trigger the compensating tax of chapters 84.33 and 84.34 RCW.

.. Instead of offering to sell interests in qualifying lands, owners may elect to donate the interests to the state.

.. Any acquired interest in qualifying lands by the state under this section shall be managed as riparian open space or critical habitat.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6406-S.SL.pdf?cite=2012%201st%20sp.s.%20c%201%20§%20203[2012 1st sp.s. c 1 § 203]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2541-S.SL.pdf?cite=2010%20c%20188%20§%204[2010 c 188 § 4]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5401-S.SL.pdf?cite=2009%20c%20246%20§%201[2009 c 246 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2399-S.SL.pdf?cite=2000%20c%2011%20§%203[2000 c 11 § 3]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2091-S.SL.pdf?cite=1999%20sp.s.%20c%204%20§%20701[1999 sp.s. c 4 § 701]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5714-S.SL.pdf?cite=1997%20c%20173%20§%201[1997 c 173 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2590.SL.pdf?cite=1994%20c%20264%20§%2048[1994 c 264 § 48]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5981-S.SL.pdf?cite=1993%20c%20443%20§%202[1993 c 443 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c36.pdf?cite=1988%20c%2036%20§%2046[1988 c 36 § 46]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c95.pdf?cite=1987%20c%2095%20§%208[1987 c 95 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c137.pdf?cite=1974%20ex.s.%20c%20137%20§%204[1974 ex.s. c 137 § 4]; ]

== 76.09.050 - Rules establishing classes of forest practices—Applications for classes of forest practices—Approval or disapproval—Notifications—Procedures—Appeals—Waiver.
. The board shall establish by rule which forest practices shall be included within each of the following classes:

Class I: Minimal or specific forest practices that have no direct potential for damaging a public resource and that may be conducted without submitting an application or a notification except that when the regulating authority is transferred to a local governmental entity, those Class I forest practices that involve timber harvesting or road construction within "urban growth areas," designated pursuant to chapter 36.70A RCW, are processed as Class IV forest practices, but are not subject to environmental review under chapter 43.21C RCW;

Class II: Forest practices which have a less than ordinary potential for damaging a public resource that may be conducted without submitting an application and may begin five calendar days, or such lesser time as the department may determine, after written notification by the operator, in the manner, content, and form as prescribed by the department, is received by the department. However, the work may not begin until all forest practice fees required under RCW 76.09.065 have been received by the department. Class II shall not include forest practices:

.. On forestlands that are being converted to another use;

.. Within "shorelines of the state" as defined in RCW 90.58.030;

.. Excluded from Class II by the board; or

.. Including timber harvesting or road construction within "urban growth areas," designated pursuant to chapter 36.70A RCW, which are Class IV;

Class III: Forest practices other than those contained in Class I, II, or IV. A Class III application must be approved or disapproved by the department according to the following timelines; however, the applicant may not begin work on the forest practice until all forest practice fees required under RCW 76.09.065 have been received by the department:

.. Within thirty calendar days from the date the department receives the application if the application is not subject to concurrence review by the department of fish and wildlife under RCW 76.09.490; and

.. Within thirty days of the completion of the concurrence review by the department of fish and wildlife if the application is subject to concurrence review by the department of fish and wildlife under RCW 76.09.490;

Class IV: Forest practices other than those contained in Class I or II:

.. On forestlands that are being converted to another use;

.. On lands which, pursuant to RCW 76.09.070 as now or hereafter amended, are not to be reforested because of the likelihood of future conversion to urban development;

.. That involve timber harvesting or road construction on forestlands that are contained within "urban growth areas," designated pursuant to chapter 36.70A RCW, except where the forestland owner provides:

... A written statement of intent signed by the forestland owner not to convert to a use other than commercial forest product operations for ten years, accompanied by either a written forest management plan acceptable to the department or documentation that the land is enrolled under the provisions of chapter 84.33 or 84.34 RCW; or

... A conversion option harvest plan approved by the local governmental entity and submitted to the department as part of the application; and/or

.. Which have a potential for a substantial impact on the environment and therefore require an evaluation by the department as to whether or not a detailed statement must be prepared pursuant to the state environmental policy act, chapter 43.21C RCW. Such evaluation shall be made within the timelines established in RCW 43.21C.037; however, nothing herein shall be construed to prevent any local or regional governmental entity from determining that a detailed statement must be prepared for an action pursuant to a Class IV forest practice taken by that governmental entity concerning the land on which forest practices will be conducted. Unless the application is subject to concurrence review by the department of fish and wildlife under RCW 76.09.490, a Class IV application must be approved or disapproved by the department within thirty calendar days from the date the department receives the application. If a Class IV application is subject to concurrence review by the department of fish and wildlife under RCW 76.09.490, then the application must be approved or disapproved by the department within thirty calendar days from the completion of the concurrence review by the department of fish and wildlife. However, the department may extend the timelines applicable to the approval or disapproval of the application an additional thirty calendar days if the department determines that a detailed statement must be made, unless the commissioner of public lands, through the promulgation of a formal order, determines that the process cannot be completed within such a period. However, the applicant may not begin work on that forest practice until all forest practice fees required under RCW 76.09.065 have been received by the department.

Forest practices under Classes I, II, and III are exempt from the requirements for preparation of a detailed statement under the state environmental policy act.

. Except for those forest practices being regulated by local governmental entities as provided elsewhere in this chapter, no Class II, Class III, or Class IV forest practice shall be commenced or continued after January 1, 1975, unless the department has received a notification with regard to a Class II forest practice or approved an application with regard to a Class III or Class IV forest practice containing all information required by RCW 76.09.060 as now or hereafter amended. However, in the event forest practices regulations necessary for the scheduled implementation of this chapter and RCW 90.48.420 have not been adopted in time to meet such schedules, the department shall have the authority to regulate forest practices and approve applications on such terms and conditions consistent with this chapter and RCW 90.48.420 and the purposes and policies of RCW 76.09.010 until applicable forest practices regulations are in effect.

. Except for those forest practices being regulated by local governmental entities as provided elsewhere in this chapter, if a notification or application is delivered in person to the department by the operator or the operator's agent, the department shall immediately provide a dated receipt thereof. In all other cases, the department shall immediately mail a dated receipt to the operator.

. Except for those forest practices being regulated by local governmental entities as provided elsewhere in this chapter, forest practices shall be conducted in accordance with the forest practices regulations, orders and directives as authorized by this chapter or the forest practices regulations, and the terms and conditions of any approved applications.

. Except for those forest practices being regulated by local governmental entities as provided elsewhere in this chapter, the department of natural resources shall notify the applicant in writing of either its approval of the application or its disapproval of the application and the specific manner in which the application fails to comply with the provisions of this section or with the forest practices regulations. Except as provided otherwise in this section, if the department fails to either approve or disapprove an application or any portion thereof within the applicable time limit, the application shall be deemed approved and the operation may be commenced: PROVIDED, That this provision shall not apply to applications which are neither approved nor disapproved pursuant to the provisions of subsection (7) of this section: PROVIDED, FURTHER, That if seasonal field conditions prevent the department from being able to properly evaluate the application, the department may issue an approval conditional upon further review within sixty days. Upon receipt of any notification or any satisfactorily completed application the department shall in any event no later than two business days after such receipt transmit a copy to the departments of ecology and fish and wildlife, and to the county, city, or town in whose jurisdiction the forest practice is to be commenced. Any comments by such agencies shall be directed to the department of natural resources.

. For those forest practices regulated by the board and the department, if the county, city, or town believes that an application is inconsistent with this chapter, the forest practices regulations, or any local authority consistent with RCW 76.09.240 as now or hereafter amended, it may so notify the department and the applicant, specifying its objections.

. For those forest practices regulated by the board and the department, the department shall not approve portions of applications to which a county, city, or town objects if:

.. The department receives written notice from the county, city, or town of such objections within fourteen business days from the time of transmittal of the application to the county, city, or town, or one day before the department acts on the application, whichever is later; and

.. The objections relate to forestlands that are being converted to another use.

The department shall either disapprove those portions of such application or appeal the county, city, or town objections to the appeals board. If the objections related to (b) of this subsection are based on local authority consistent with RCW 76.09.240 as now or hereafter amended, the department shall disapprove the application until such time as the county, city, or town consents to its approval or such disapproval is reversed on appeal. The applicant shall be a party to all department appeals of county, city, or town objections. Unless the county, city, or town either consents or has waived its rights under this subsection, the department shall not approve portions of an application affecting such lands until the minimum time for county, city, or town objections has expired.

. For those forest practices regulated by the board and the department, in addition to any rights under the above paragraph, the county, city, or town may appeal any department approval of an application with respect to any lands within its jurisdiction. The appeals board may suspend the department's approval in whole or in part pending such appeal where there exists potential for immediate and material damage to a public resource.

. For those forest practices regulated by the board and the department, appeals under this section shall be made to the appeals board in the manner and time provided in RCW 76.09.205. In such appeals there shall be no presumption of correctness of either the county, city, or town or the department position.

. For those forest practices regulated by the board and the department, the department shall, within four business days notify the county, city, or town of all notifications, approvals, and disapprovals of an application affecting lands within the county, city, or town, except to the extent the county, city, or town has waived its right to such notice.

. For those forest practices regulated by the board and the department, a county, city, or town may waive in whole or in part its rights under this section, and may withdraw or modify any such waiver, at any time by written notice to the department.

. Notwithstanding subsections (2) through (5) of this section, forest practices applications or notifications are not required for exotic insect and disease control operations conducted in accordance with RCW 76.09.060(8) where eradication can reasonably be expected.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6406-S.SL.pdf?cite=2012%201st%20sp.s.%20c%201%20§%20205[2012 1st sp.s. c 1 § 205]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1582.SL.pdf?cite=2011%20c%20207%20§%201[2011 c 207 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2935-S.SL.pdf?cite=2010%20c%20210%20§%2020[2010 c 210 § 20]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1346-S2.SL.pdf?cite=2005%20c%20146%20§%201003[2005 c 146 § 1003]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5144-S.SL.pdf?cite=2003%20c%20314%20§%204[2003 c 314 § 4]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2399.SL.pdf?cite=2002%20c%20121%20§%201[2002 c 121 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5714-S.SL.pdf?cite=1997%20c%20173%20§%202[1997 c 173 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2590.SL.pdf?cite=1994%20c%20264%20§%2049[1994 c 264 § 49]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5981-S.SL.pdf?cite=1993%20c%20443%20§%203[1993 c 443 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990ex1c17.pdf?cite=1990%201st%20ex.s.%20c%2017%20§%2061[1990 1st ex.s. c 17 § 61]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c36.pdf?cite=1988%20c%2036%20§%2047[1988 c 36 § 47]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c95.pdf?cite=1987%20c%2095%20§%209[1987 c 95 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c200.pdf?cite=1975%201st%20ex.s.%20c%20200%20§%202[1975 1st ex.s. c 200 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c137.pdf?cite=1974%20ex.s.%20c%20137%20§%205[1974 ex.s. c 137 § 5]; ]

== 76.09.055 - Findings—Emergency rule making authorized.
. The legislature finds that the levels of fish stocks throughout much of the state require immediate action to be taken to help these fish runs where possible. The legislature also recognizes that federal and state agencies, tribes, county representatives, and private timberland owners have spent considerable effort and time to develop the forests and fish report. Given the agreement of the parties, the legislature believes that the immediate adoption of emergency rules is appropriate in this particular instance. These rules can implement many provisions of the forests and fish report to protect the economic well-being of the state, and to minimize the risk to the state and landowners to legal challenges. This authority is not designed to set any precedents for the forest practices board in future rule making or set any precedents for other rule-making bodies of the state.

. The forest practices board is authorized to adopt emergency rules amending the forest practices rules with respect to the protection of aquatic resources, in accordance with RCW 34.05.350, except: (a)(i) That the rules adopted under this section may remain in effect until permanent rules are adopted, or until June 30, 2001, whichever is sooner; (ii) that the rules adopted under RCW 76.09.420(5) must remain in effect until permanent rules are adopted; (b) notice of the proposed rules must be published in the Washington State Register as provided in RCW 34.05.320; (c) at least one public hearing must be conducted with an opportunity to provide oral and written comments; and (d) a rule-making file must be maintained as required by RCW 34.05.370. In adopting emergency rules consistent with this section, the board is not required to prepare a small business economic impact statement under chapter 19.85 RCW, prepare a statement indicating whether the rules constitute a significant legislative rule under RCW 34.05.328, prepare a significant legislative rule analysis under RCW 34.05.328, or follow the procedural requirements of the state environmental policy act, chapter 43.21C RCW. Except as provided in RCW 76.09.420, the forest practices board may only adopt recommendations contained in the forests and fish report as emergency rules under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1095-S2.SL.pdf?cite=2003%20c%20311%20§%205[2003 c 311 § 5]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2399-S.SL.pdf?cite=2000%20c%2011%20§%204[2000 c 11 § 4]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2091-S.SL.pdf?cite=1999%20sp.s.%20c%204%20§%20201[1999 sp.s. c 4 § 201]; ]

== 76.09.060 - Form and contents of notification and application—Reforestation requirements—Conversion of forestland to other use—New applications—Approval—Emergencies.
. The department shall prescribe the form and contents of the notification and application. The forest practices rules shall specify by whom and under what conditions the notification and application shall be signed or otherwise certified as acceptable. Activities conducted by the department or a contractor under the direction of the department under the provisions of RCW 76.04.660, shall be exempt from the landowner signature requirement on any forest practices application required to be filed. The application or notification shall be delivered in person to the department, sent by first-class mail to the department or electronically filed in a form defined by the department. The form for electronic filing shall be readily convertible to a paper copy, which shall be available to the public pursuant to chapter 42.56 RCW. The information required may include, but is not limited to:

.. Name and address of the forestland owner, timber owner, and operator;

.. Description of the proposed forest practice or practices to be conducted;

.. Legal description and tax parcel identification numbers of the land on which the forest practices are to be conducted;

.. Planimetric and topographic maps showing location and size of all lakes and streams and other public waters in and immediately adjacent to the operating area and showing all existing and proposed roads and major tractor roads;

.. Description of the silvicultural, harvesting, or other forest practice methods to be used, including the type of equipment to be used and materials to be applied;

.. For an application or notification submitted on or after July 10, 2012, that includes a forest practices hydraulic project, plans and specifications for the forest practices hydraulic project to ensure the proper protection of fish life;

.. Proposed plan for reforestation and for any revegetation necessary to reduce erosion potential from roadsides and yarding roads, as required by the forest practices rules;

.. Soil, geological, and hydrological data with respect to forest practices;

.. The expected dates of commencement and completion of all forest practices specified in the application;

.. Provisions for continuing maintenance of roads and other construction or other measures necessary to afford protection to public resources;

.. An affirmation that the statements contained in the notification or application are true; and

.. All necessary application or notification fees.

. Long range plans may be submitted to the department for review and consultation.

. The application for a forest practice or the notification of a forest practice is subject to the reforestation requirement of RCW 76.09.070.

.. If the application states that any land will be or is intended to be converted:

... The reforestation requirements of this chapter and of the forest practices rules shall not apply if the land is in fact converted unless applicable alternatives or limitations are provided in forest practices rules issued under RCW 76.09.070;

... Completion of such forest practice operations shall be deemed conversion of the lands to another use for purposes of chapters 84.33 and 84.34 RCW unless the conversion is to a use permitted under a current use tax agreement permitted under chapter 84.34 RCW;

... The forest practices described in the application are subject to applicable county, city, town, and regional governmental authority permitted under RCW 76.09.240 as well as the forest practices rules.

.. Except as provided elsewhere in this section, if the landowner harvests without an approved application or notification or the landowner does not state that any land covered by the application or notification will be or is intended to be converted, and the department or the county, city, town, or regional governmental entity becomes aware of conversion activities to a use other than commercial timber operations, as that term is defined in RCW 76.09.020, then the department shall send to the department of ecology and the appropriate county, city, town, and regional governmental entities the following documents:

... A notice of a conversion to nonforestry use;

... A copy of the applicable forest practices application or notification, if any; and

... Copies of any applicable outstanding final orders or decisions issued by the department related to the forest practices application or notification.

.. Failure to comply with the reforestation requirements contained in any final order or decision shall constitute a removal of designation under the provisions of RCW 84.33.140, and a change of use under the provisions of RCW 84.34.080, and, if applicable, shall subject such lands to the payments and/or penalties resulting from such removals or changes.

.. Conversion to a use other than commercial forest product operations within six years after approval of the forest practices application or notification without the consent of the county, city, or town shall constitute a violation of each of the county, municipal city, town, and regional authorities to which the forest practice operations would have been subject if the application had stated an intent to convert.

.. Land that is the subject of a notice of conversion to a nonforestry use produced by the department and sent to the department of ecology and a local government under this subsection is subject to the development prohibition and conditions provided in RCW 76.09.460.

.. Landowners who have not stated an intent to convert the land covered by an application or notification and who decide to convert the land to a nonforestry use within six years of receiving an approved application or notification must do so in a manner consistent with RCW 76.09.470.

.. The application or notification must include a statement requiring an acknowledgment by the forestland owner of his or her intent with respect to conversion and acknowledging that he or she is familiar with the effects of this subsection.

. Whenever an approved application authorizes a forest practice which, because of soil condition, proximity to a water course or other unusual factor, has a potential for causing material damage to a public resource, as determined by the department, the applicant shall, when requested on the approved application, notify the department two days before the commencement of actual operations.

. Before the operator commences any forest practice in a manner or to an extent significantly different from that described in a previously approved application or notification, there shall be submitted to the department a new application or notification form in the manner set forth in this section.

. [Empty]
.. Except as provided in RCW 76.09.350(4), the notification to or the approval given by the department to an application to conduct a forest practice shall be effective for a term of three years from the date of approval or notification.

.. A notification or application may be renewed for an additional three-year term by the filing and approval of a notification or application, as applicable, prior to the expiration of the original application or notification. A renewal application or notification is subject to the forest practices rules in effect at the time the renewal application or notification is filed. Nothing in this section precludes the applicant from applying for a new application or notification after the renewal period has lapsed.

.. At the option of the applicant, an application or notification may be submitted to cover a single forest practice or a number of forest practices within reasonable geographic or political boundaries as specified by the department. An application or notification that covers more than one forest practice may have an effective term of more than three years.

.. The board shall adopt rules that establish standards and procedures for approving an application or notification that has an effective term of more than three years. Such rules shall include extended time periods for application or notification approval or disapproval. The department may require the applicant to provide advance notice before commencing operations on an approved application or notification.

. Notwithstanding any other provision of this section, no prior application or notification shall be required for any emergency forest practice necessitated by fire, flood, windstorm, earthquake, or other emergency as defined by the board, but the operator shall submit an application or notification, whichever is applicable, to the department within forty-eight hours after commencement of such practice or as required by local regulations.

. Forest practices applications or notifications are not required for forest practices conducted to control exotic forest insect or disease outbreaks, when conducted by or under the direction of the department of agriculture in carrying out an order of the governor or director of the department of agriculture to implement pest control measures as authorized under chapter 17.24 RCW, and are not required when conducted by or under the direction of the department in carrying out emergency measures under a forest health emergency declaration by the commissioner of public lands as provided in RCW 76.06.130.

.. For the purposes of this subsection, exotic forest insect or disease has the same meaning as defined in RCW 76.06.020.

.. In order to minimize adverse impacts to public resources, control measures must be based on integrated pest management, as defined in RCW 17.15.010, and must follow forest practices rules relating to road construction and maintenance, timber harvest, and forest chemicals, to the extent possible without compromising control objectives.

.. Agencies conducting or directing control efforts must provide advance notice to the appropriate regulatory staff of the department of the operations that would be subject to exemption from forest practices application or notification requirements.

.. When the appropriate regulatory staff of the department are notified under (c) of this subsection, they must consult with the landowner, interested agencies, and affected tribes, and assist the notifying agencies in the development of integrated pest management plans that comply with forest practices rules as required under (b) of this subsection.

.. Nothing under this subsection relieves agencies conducting or directing control efforts from requirements of the federal clean water act as administered by the department of ecology under RCW 90.48.260.

.. Forestlands where trees have been cut as part of an exotic forest insect or disease control effort under this subsection are subject to reforestation requirements under RCW 76.09.070.

.. The exemption from obtaining approved forest practices applications or notifications does not apply to forest practices conducted after the governor, the director of the department of agriculture, or the commissioner of public lands have declared that an emergency no longer exists because control objectives have been met, that there is no longer an imminent threat, or that there is no longer a good likelihood of control.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6406-S.SL.pdf?cite=2012%201st%20sp.s.%20c%201%20§%20206[2012 1st sp.s. c 1 § 206]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6141-S.SL.pdf?cite=2007%20c%20480%20§%2011[2007 c 480 § 11]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5883-S2.SL.pdf?cite=2007%20c%20106%20§%201[2007 c 106 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1133-S.SL.pdf?cite=2005%20c%20274%20§%20357[2005 c 274 § 357]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5144-S.SL.pdf?cite=2003%20c%20314%20§%205[2003 c 314 § 5]; prior:  1997 c 290 § 3; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5714-S.SL.pdf?cite=1997%20c%20173%20§%203[1997 c 173 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5981-S.SL.pdf?cite=1993%20c%20443%20§%204[1993 c 443 § 4]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2330-S.SL.pdf?cite=1992%20c%2052%20§%2022[1992 c 52 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990ex1c17.pdf?cite=1990%201st%20ex.s.%20c%2017%20§%2062[1990 1st ex.s. c 17 § 62]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c200.pdf?cite=1975%201st%20ex.s.%20c%20200%20§%203[1975 1st ex.s. c 200 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c137.pdf?cite=1974%20ex.s.%20c%20137%20§%206[1974 ex.s. c 137 § 6]; ]

== 76.09.063 - Forest practices permit—Habitat incentives agreement.
When a private landowner is applying for a forest practices permit under this chapter and that landowner has entered into a habitat incentives agreement with the department and the department of fish and wildlife as provided in *RCW 77.55.300, the department shall comply with the terms of that agreement when evaluating the permit application.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5172.SL.pdf?cite=2003%20c%2039%20§%2033[2003 c 39 § 33]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5327-S.SL.pdf?cite=1997%20c%20425%20§%205[1997 c 425 § 5]; ]

== 76.09.065 - Fee for applications and notifications related to the commercial harvest of timber—Forest practices application account—Creation—Applications submitted to a local governmental entity.
. An applicant shall pay an application fee, if applicable, at the time an application or notification is submitted to the department or to the local governmental entity as provided in this chapter.

. [Empty]
.. If RCW 77.55.361, 76.09.490, 76.09.040, and 76.09.060 are not enacted into law by June 30, 2012, then the fee for applications and notifications submitted to the department shall be fifty dollars for class II, III, and IV forest practices applications or notifications relating to the commercial harvest of timber. However, the fee shall be five hundred dollars for class IV forest practices applications on lands being converted to other uses or on lands which are not to be reforested because of the likelihood of future conversion to urban development or on lands that are contained within "urban growth areas," designated pursuant to chapter 36.70A RCW, except the fee shall be fifty dollars on those lands where the forestland owner provides:

... A written statement of intent signed by the forestland owner not to convert to a use other than commercial forest product operations for ten years, accompanied by either a written forest management plan acceptable to the department or documentation that the land is enrolled under the provisions of chapter 84.33 RCW; or

... A conversion option harvest plan approved by the local governmental entity and submitted to the department as part of the forest practices application.

.. [Empty]
... If RCW 77.55.361, 76.09.490, 76.09.040, and 76.09.060 are enacted into law by June 30, 2012, then:

(A) The fee for applications and notifications relating to the commercial harvest of timber submitted to the department shall be one hundred dollars for class II applications and notifications, class III applications, and class IV forest practices that have a potential for a substantial impact on the environment and therefore require an evaluation by the department as to whether or not a detailed statement must be prepared pursuant to the state environmental policy act, chapter 43.21C RCW, when the application or notification is submitted by a landowner who satisfies the definition of small forestland owner provided in RCW 76.09.450 and the application or notification applies to a single contiguous ownership consisting of one or more parcels;

(B) The fee for applications and notifications relating to the commercial harvest of timber submitted to the department shall be one hundred fifty dollars for class II applications and notifications, class III applications, and class IV forest practices that have a potential for a substantial impact on the environment and therefore require an evaluation by the department as to whether or not a detailed statement must be prepared pursuant to the state environmental policy act, chapter 43.21C RCW, when the application or notification is submitted by a landowner who does not satisfy the criteria for a reduced application fee as provided in (b)(i)(A) of this subsection (2); and

(C) The fee shall be one thousand five hundred dollars for class IV forest practices applications on lands being converted to other uses or on lands that are not to be reforested because of the likelihood of future conversion to urban development or on lands that are contained within urban growth areas, designated pursuant to chapter 36.70A RCW, except the fee shall be the same as for a class III forest practices application where the forestland owner provides:

(I) A written statement of intent signed by the forestland owner not to convert to a use other than commercial forest product operations for ten years, accompanied by either a written forest management plan acceptable to the department or documentation that the land is enrolled under the provisions of chapter 84.33 RCW; or

(II) A conversion option harvest plan approved by the local governmental entity and submitted to the department as part of the forest practices application.

... If the board has not incorporated fish protection standards adopted under chapter 77.55 RCW into the forest practices rules and approved technical guidance as required under RCW 76.09.040 by December 31, 2013, the fee for applications and notifications submitted to the department shall be as provided under (a) of this subsection until the rules are adopted and technical guidance approved.

. The forest practices application account is created in the state treasury. Moneys in the account may be spent only after appropriation. All money collected from fees under subsection (2) of this section shall be deposited in the forest practices application account for the purposes of implementing this chapter, chapter 76.13 RCW, and Title 222 WAC.

. For applications submitted to a local governmental entity as provided in this chapter, the fee shall be determined, collected, and retained by the local governmental entity.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6406-S.SL.pdf?cite=2012%201st%20sp.s.%20c%201%20§%20209[2012 1st sp.s. c 1 § 209]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2399-S.SL.pdf?cite=2000%20c%2011%20§%205[2000 c 11 § 5]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5714-S.SL.pdf?cite=1997%20c%20173%20§%204[1997 c 173 § 4]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5981-S.SL.pdf?cite=1993%20c%20443%20§%205[1993 c 443 § 5]; ]

== 76.09.067 - Application for forest practices—Owner of perpetual timber rights.
Notwithstanding any other provision of this chapter to the contrary, for the purposes of RCW 76.09.050(1) and 76.09.060, where timber rights have been transferred by deed to a perpetual owner who is different from the forestland owner, the owner of perpetual timber rights may sign the forest practices application or notification. The forest practices application is not complete until the holder of perpetual timber rights has submitted evidence to the department that the signed forest practices application or notification has been received by the forestland owner.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5883-S2.SL.pdf?cite=2007%20c%20106%20§%205[2007 c 106 § 5]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6669-S.SL.pdf?cite=1998%20c%20100%20§%201[1998 c 100 § 1]; ]

== 76.09.070 - Reforestation—Requirements—Procedures—Notification on sale or transfer.
. After the completion of a logging operation, satisfactory reforestation, as defined by the rules and regulations promulgated by the board, shall be completed within three years. However:

.. A longer period may be authorized if seed or seedlings are not available;

.. A period of up to five years may be allowed where a natural regeneration plan is approved by the department; and 

.. The department may identify low-productivity lands on which it may allow for a period of up to ten years for natural regeneration.

. [Empty]
.. Upon the completion of a reforestation operation a report on such operation shall be filed with the department of natural resources.

.. Within twelve months of receipt of such a report the department shall inspect the reforestation operation, and shall determine either that the reforestation operation has been properly completed or that further reforestation and inspection is necessary.

. Satisfactory reforestation is the obligation of the owner of the land as defined by forest practices regulations, except the owner of perpetual rights to cut timber owned separately from the land is responsible for satisfactory reforestation. The reforestation obligation shall become the obligation of a new owner if the land or perpetual timber rights are sold or otherwise transferred.

. [Empty]
.. Prior to the sale or transfer of land or perpetual timber rights subject to a reforestation obligation or to a notice of conversion to a nonforestry use issued under RCW 76.09.060, the seller shall notify the buyer of the existence and nature of the obligation and the buyer shall sign a notice indicating the buyer's knowledge of all obligations.

.. The notice shall be on a form prepared by the department and shall be sent to the department by the seller at the time of sale or transfer of the land or perpetual timber rights.

.. If the seller fails to notify the buyer about the reforestation obligation or the notice of conversion to a nonforestry use, the seller shall pay the buyer's costs related to reforestation or mitigation under RCW 76.09.470, including all legal costs which include reasonable attorneys' fees, incurred by the buyer in enforcing the reforestation obligation or mitigation requirements against the seller.

.. Failure by the seller to send the required notice to the department at the time of sale shall be prima facie evidence, in an action by the buyer against the seller for costs related to reforestation or mitigation, that the seller did not notify the buyer of the reforestation obligation or potential mitigation requirements prior to sale.

. The forest practices regulations may provide alternatives to or limitations on the applicability of reforestation requirements with respect to forestlands being converted in whole or in part to another use which is compatible with timber growing. The forest practices regulations may identify classifications and/or areas of forestland that have the likelihood of future conversion to urban development within a ten year period. The reforestation requirements may be modified or eliminated on such lands. However, such identification and/or such conversion to urban development must be consistent with any local or regional land use plans or ordinances.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5883-S2.SL.pdf?cite=2007%20c%20106%20§%204[2007 c 106 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c95.pdf?cite=1987%20c%2095%20§%2010[1987 c 95 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c173.pdf?cite=1982%20c%20173%20§%201[1982 c 173 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c200.pdf?cite=1975%201st%20ex.s.%20c%20200%20§%204[1975 1st ex.s. c 200 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c137.pdf?cite=1974%20ex.s.%20c%20137%20§%207[1974 ex.s. c 137 § 7]; ]

== 76.09.080 - Stop work orders—Grounds—Contents—Procedure—Appeals.
. The department shall have the authority to serve upon an operator a stop work order which shall be a final order of the department if:

.. There is any violation of the provisions of this chapter or the forest practices regulations; or

.. There is a deviation from the approved application; or

.. Immediate action is necessary to prevent continuation of or to avoid material damage to a public resource.

. The stop work order shall set forth:

.. The specific nature, extent, and time of the violation, deviation, damage, or potential damage;

.. An order to stop all work connected with the violation, deviation, damage, or potential damage;

.. The specific course of action needed to correct such violation or deviation or to prevent damage and to correct and/or compensate for damage to public resources which has resulted from any violation, unauthorized deviation, or willful or negligent disregard for potential damage to a public resource; and/or those courses of action necessary to prevent continuing damage to public resources where the damage is resulting from the forest practice activities but has not resulted from any violation, unauthorized deviation, or negligence; and

.. The right of the operator to a hearing before the appeals board.

The department shall immediately file a copy of such order with the appeals board and mail a copy thereof to the timber owner and forestland owner at the addresses shown on the application. The operator, timber owner, or forestland owner may commence an appeal to the appeals board within thirty days from the date of receipt of the order by the operator. If such appeal is commenced, a hearing shall be held not more than twenty days after copies of the notice of appeal were filed with the appeals board. Such proceeding shall be an adjudicative proceeding within the meaning of chapter 34.05 RCW, the administrative procedure act. The operator shall comply with the order of the department immediately upon being served, but the appeals board if requested shall have authority to continue or discontinue in whole or in part the order of the department under such conditions as it may impose pending the outcome of the proceeding.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2935-S.SL.pdf?cite=2010%20c%20210%20§%2021[2010 c 210 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c175.pdf?cite=1989%20c%20175%20§%20163[1989 c 175 § 163]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c200.pdf?cite=1975%201st%20ex.s.%20c%20200%20§%205[1975 1st ex.s. c 200 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c137.pdf?cite=1974%20ex.s.%20c%20137%20§%208[1974 ex.s. c 137 § 8]; ]

== 76.09.090 - Notice of failure to comply—Contents—Procedures—Appeals—Hearing—Final order—Limitations on actions.
If a violation, a deviation, material damage or potential for material damage to a public resource has occurred and the department determines that a stop work order is unnecessary, then the department shall issue and serve upon the operator or land owner a notice, which shall clearly set forth:

. [Empty]
.. The specific nature, extent, and time of failure to comply with the approved application; or identifying the damage or potential damage; and/or

.. The relevant provisions of this chapter or of the forest practice regulations relating thereto;

. The right of the operator or land owner to a hearing before the department; and

. The specific course of action ordered by the department to be followed by the operator to correct such failure to comply and to prevent, correct and/or compensate for material damage to public resources which resulted from any violation, unauthorized deviation, or wilful or negligent disregard for potential damage to a public resource; and/or those courses of action necessary to prevent continuing damage to public resources where the damage is resulting from the forest practice activities but has not resulted from any violation, unauthorized deviation, or negligence.

The department shall mail a copy thereof to the forestland owner and the timber owner at the addresses shown on the application, showing the date of service upon the operator. Such notice to comply shall become a final order of the department: PROVIDED, That no direct appeal to the appeals board will be allowed from such final order. Such operator shall undertake the course of action so ordered by the department unless, within fifteen days after the date of service of such notice to comply, the operator, forestland owner, or timber owner, shall request the department in writing to schedule a hearing. If so requested, the department shall schedule a hearing on a date not more than twenty days after receiving such request. Within ten days after such hearing, the department shall issue a final order either withdrawing its notice to comply or clearly setting forth the specific course of action to be followed by such operator. Such operator shall undertake the course of action so ordered by the department unless within thirty days after the date of receipt of such final order, the operator, forestland owner, or timber owner appeals such final order to the appeals board.

No person shall be under any obligation under this section to prevent, correct, or compensate for any damage to public resources which occurs more than one year after the date of completion of the forest practices operations involved exclusive of reforestation, unless such forest practices were not conducted in accordance with forest practices rules and regulations: PROVIDED, That this provision shall not relieve the forestland owner from any obligation to comply with forest practices rules and regulations pertaining to providing continuing road maintenance. No action to recover damages shall be taken under this section more than two years after the date the damage involved occurs.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2935-S.SL.pdf?cite=2010%20c%20210%20§%2022[2010 c 210 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c200.pdf?cite=1975%201st%20ex.s.%20c%20200%20§%206[1975 1st ex.s. c 200 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c137.pdf?cite=1974%20ex.s.%20c%20137%20§%209[1974 ex.s. c 137 § 9]; ]

== 76.09.100 - Failure to comply with water quality protection—Department of ecology authorized to petition appeals board—Action on petition.
If the department of ecology determines that a person has failed to comply with the forest practices regulations relating to water quality protection, and that the department of natural resources has not issued a stop work order or notice to comply, the department of ecology shall inform the department thereof. If the department of natural resources fails to take authorized enforcement action within twenty-four hours under RCW 76.09.080, 76.09.090, 76.09.120, or 76.09.130, the department of ecology may petition to the chair of the appeals board, who shall, within forty-eight hours, either deny the petition or direct the department of natural resources to immediately issue a stop work order or notice to comply, or to impose a penalty. No civil or criminal penalties shall be imposed for past actions or omissions if such actions or omissions were conducted pursuant to an approval or directive of the department of natural resources.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20220[2013 c 23 § 220]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c200.pdf?cite=1975%201st%20ex.s.%20c%20200%20§%207[1975 1st ex.s. c 200 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c137.pdf?cite=1974%20ex.s.%20c%20137%20§%2010[1974 ex.s. c 137 § 10]; ]

== 76.09.110 - Final orders or final decisions binding upon all parties.
Unless declared invalid on appeal, a final order of the department or a final decision of the appeals board shall be binding upon all parties.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c137.pdf?cite=1974%20ex.s.%20c%20137%20§%2011[1974 ex.s. c 137 § 11]; ]

== 76.09.120 - Failure of owner to take required course of action—Notice of cost—Department authorized to complete course of action—Liability of owner for costs—Lien.
If an operator fails to undertake and complete any course of action with respect to a forest practice, as required by a final order of the department or a final decision of the appeals board or any court pursuant to RCW 76.09.080 and 76.09.090, the department may determine the cost thereof and give written notice of such cost to the operator, the timber owner and the owner of the forestland upon or in connection with which such forest practice was being conducted. If such operator, timber owner, or forestland owner fails within thirty days after such notice is given to undertake such course of action, or having undertaken such course of action fails to complete it within a reasonable time, the department may expend any funds available to undertake and complete such course of action and such operator, timber owner, and forestland owner shall be jointly and severally liable for the actual, direct cost thereof, but in no case more than the amount set forth in the notice from the department. If not paid within sixty days after the department completes such course of action and notifies such forestland owner in writing of the amount due, such amount shall become a lien on such forestland and the department may collect such amount in the same manner provided in chapter 60.04 RCW for mechanics' liens.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c137.pdf?cite=1974%20ex.s.%20c%20137%20§%2012[1974 ex.s. c 137 § 12]; ]

== 76.09.130 - Failure to obey stop work order—Departmental action authorized—Liability of owner or operator for costs.
When the operator has failed to obey a stop work order issued under the provisions of RCW 76.09.080 the department may take immediate action to prevent continuation of or avoid material damage to public resources. If a final order or decision fixes liability with the operator, timber owner, or forestland owner, they shall be jointly and severally liable for such emergency costs which may be collected in the manner provided for in RCW 76.09.120.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c137.pdf?cite=1974%20ex.s.%20c%20137%20§%2013[1974 ex.s. c 137 § 13]; ]

== 76.09.140 - Enforcement.
. The department of natural resources may take any necessary action to enforce any final order or final decision, and may disapprove any forest practices application or notification submitted by any person who has failed to comply with a final order or final decision or has failed to pay any civil penalties as provided in RCW 76.09.170, for up to one year from the issuance of a notice of intent to disapprove notifications and applications under this section or until the violator pays all outstanding civil penalties and complies with all validly issued and outstanding notices to comply and stop work orders, whichever is longer. For purposes of chapter 482, Laws of 1993, the terms "final order" and "final decision" shall mean the same as set forth in RCW 76.09.080, 76.09.090, and 76.09.110. The department shall provide written notice of its intent to disapprove an application or notification under this subsection. The department shall forward copies of its notice of intent to disapprove to any affected landowner. The disapproval period shall run from thirty days following the date of actual notice or when all administrative and judicial appellate processes, if any, have been exhausted. Any person provided the notice may seek review from the appeals board by filing a request for review within thirty days of the date of the notice of intent. While the notice of intent to disapprove is in effect, the violator may not serve as a person in charge of, be employed by, manage, or otherwise participate to any degree in forest practices.

. On request of the department, the attorney general may take action necessary to enforce this chapter, including, but not limited to: Seeking penalties, interest, costs, and attorneys' fees; enforcing final orders or decisions; and seeking civil injunctions, show cause orders, or contempt orders.

. A county may bring injunctive, declaratory, or other actions for enforcement for forest practice activities within its jurisdiction in the superior court as provided by law against the department, the forestland owner, timber owner or operator to enforce the forest practices rules or any final order of the department, or the appeals board. No civil or criminal penalties shall be imposed for past actions or omissions if such actions or omissions were conducted pursuant to an approval or directive of the department. Injunctions, declaratory actions, or other actions for enforcement under this subsection may not be commenced unless the department fails to take appropriate action after ten days written notice to the department by the county of a violation of the forest practices rules or final orders of the department or the appeals board.

. [Empty]
.. The department may require financial assurance prior to the conduct of any further forest practices from an operator or landowner who within the preceding three-year period has:

... Operated without an approved forest practices application, other than an unintentional operation in connection with an approved application outside the approved boundary of such an application;

... Continued to operate in breach of, or failed to comply with, the terms of an effective stop work order or notice to comply; or

... Failed to pay any civil or criminal penalty.

.. The department may deny any application for failure to submit financial assurances as required.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2399-S.SL.pdf?cite=2000%20c%2011%20§%206[2000 c 11 § 6]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2091-S.SL.pdf?cite=1999%20sp.s.%20c%204%20§%20801[1999 sp.s. c 4 § 801]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5688-S.SL.pdf?cite=1993%20c%20482%20§%201[1993 c 482 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c200.pdf?cite=1975%201st%20ex.s.%20c%20200%20§%208[1975 1st ex.s. c 200 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c137.pdf?cite=1974%20ex.s.%20c%20137%20§%2014[1974 ex.s. c 137 § 14]; ]

== 76.09.150 - Inspection—Right of entry.
. The department shall make inspections of forestlands, before, during, and after the conducting of forest practices as necessary for the purpose of ensuring compliance with this chapter, the forest practices rules, including forest practices rules incorporated under RCW 76.09.040(3), and to ensure that no material damage occurs to the natural resources of this state as a result of forest practices.

. Any duly authorized representative of the department shall have the right to enter upon forestland at any reasonable time to enforce the provisions of this chapter and the forest practices rules.

. The department or the department of ecology may apply for an administrative inspection warrant to either Thurston county superior court, or the superior court in the county in which the property is located. An administrative inspection warrant may be issued where:

.. The department has attempted an inspection of forestlands under this chapter to ensure compliance with this chapter and the forest practices rules or to ensure that no potential or actual material damage occurs to the natural resources of this state, and access to all or part of the forestlands has been actually or constructively denied; or

.. The department has reasonable cause to believe that a violation of this chapter or of rules adopted under this chapter is occurring or has occurred.

. In connection with any watershed analysis, any review of a pending application by an identification team appointed by the department, any compliance studies, any effectiveness monitoring, or other research that has been agreed to by a landowner, the department may invite representatives of other agencies, tribes, and interest groups to accompany a department representative and, at the landowner's election, the landowner, on any such inspections. Reasonable efforts shall be made by the department to notify the landowner of the persons being invited onto the property and the purposes for which they are being invited.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6406-S.SL.pdf?cite=2012%201st%20sp.s.%20c%201%20§%20207[2012 1st sp.s. c 1 § 207]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2399-S.SL.pdf?cite=2000%20c%2011%20§%207[2000 c 11 § 7]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2091-S.SL.pdf?cite=1999%20sp.s.%20c%204%20§%20802[1999 sp.s. c 4 § 802]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c137.pdf?cite=1974%20ex.s.%20c%20137%20§%2015[1974 ex.s. c 137 § 15]; ]

== 76.09.160 - Right of entry by department of ecology.
Any duly authorized representative of the department of ecology shall have the right to enter upon forestland at any reasonable time to administer the provisions of this chapter and RCW 90.48.420.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c137.pdf?cite=1974%20ex.s.%20c%20137%20§%2016[1974 ex.s. c 137 § 16]; ]

== 76.09.170 - Violations—Conversion to nontimber operation—Penalties—Remission or mitigation—Appeals—Lien.
. Every person who violates any provision of RCW 76.09.010 through 76.09.280 or of the forest practices rules, or who converts forestland to a use other than commercial timber operation within three years after completion of the forest practice without the consent of the county, city, or town, shall be subject to a penalty in an amount of not more than ten thousand dollars for every such violation. Each and every such violation shall be a separate and distinct offense. In case of a failure to comply with a stop work order, every day's continuance shall be a separate and distinct violation. Every person who through an act of commission or omission procures, aids or abets in the violation shall be considered to have violated the provisions of this section and shall be subject to the penalty in this section. No penalty shall be imposed under this section upon any governmental official, an employee of any governmental department, agency, or entity, or a member of any board or advisory committee created by this chapter for any act or omission in his or her duties in the administration of this chapter or of any rule adopted under this chapter.

. The department shall develop and recommend to the board a penalty schedule to determine the amount to be imposed under this section. The board shall adopt by rule, pursuant to chapter 34.05 RCW, such penalty schedule to be effective no later than January 1, 1994. The schedule shall be developed in consideration of the following:

.. Previous violation history;

.. Severity of the impact on public resources;

.. Whether the violation of this chapter or its rules was intentional;

.. Cooperation with the department;

.. Repairability of the adverse effect from the violation; and

.. The extent to which a penalty to be imposed on a forestland owner for a forest practice violation committed by another should be reduced because the owner was unaware of the violation and has not received substantial economic benefits from the violation.

. The penalty in this section shall be imposed by a notice in writing, either by certified mail with return receipt requested or by personal service, to the person incurring the same from the department describing the violation with reasonable particularity. Within fifteen days after the notice is received, the person incurring the penalty may apply in writing to the department for the remission or mitigation of such penalty. Upon receipt of the application, that department may remit or mitigate the penalty upon whatever terms that department in its discretion deems proper, provided the department deems such remission or mitigation to be in the best interests of carrying out the purposes of this chapter. The department shall have authority to ascertain the facts regarding all such applications in such reasonable manner and under such rule as it may deem proper.

. Any person incurring a penalty under this section may appeal the penalty to the appeals board. Such appeals shall be filed within thirty days after the date of receipt of the penalty unless an application for remission or mitigation is made to the department. When such an application for remission or mitigation is made, such appeals shall be filed within thirty days of receipt of notice from the department setting forth the disposition of the application for remission or mitigation.

. The penalty imposed under this section shall become due and payable thirty days after receipt of a notice imposing the same unless application for remission or mitigation is made or an appeal is filed. When such an application for remission or mitigation is made, any penalty incurred under this section shall become due and payable thirty days after receipt of notice setting forth the disposition of such application unless an appeal is filed from such disposition. Whenever an appeal of the penalty incurred is filed, the penalty shall become due and payable only upon completion of all administrative and judicial review proceedings and the issuance of a final decision confirming the penalty in whole or in part.

. If the amount of any penalty is not paid to the department within thirty days after it becomes due and payable, the attorney general, upon the request of the department, shall bring an action in the name of the state of Washington in the superior court of Thurston county or of any county in which such violator may do business, to recover such penalty, interest, costs, and attorneys' fees. In all such actions the procedure and rules of evidence shall be the same as an ordinary civil action except as otherwise provided in this chapter. In addition to or as an alternative to seeking enforcement of penalties in superior court, the department may bring an action in district court as provided in Title 3 RCW, to collect penalties, interest, costs, and attorneys' fees.

. Penalties imposed under this section for violations associated with a conversion to a use other than commercial timber operation shall be a lien upon the real property of the person assessed the penalty and the department may collect such amount in the same manner provided in chapter 60.04 RCW for mechanics' liens.

. Any person incurring a penalty imposed under this section is also responsible for the payment of all costs and attorneys' fees incurred in connection with the penalty and interest accruing on the unpaid penalty amount.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2935-S.SL.pdf?cite=2010%20c%20210%20§%2023[2010 c 210 § 23]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2091-S.SL.pdf?cite=1999%20sp.s.%20c%204%20§%20803[1999 sp.s. c 4 § 803]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5688-S.SL.pdf?cite=1993%20c%20482%20§%202[1993 c 482 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c200.pdf?cite=1975%201st%20ex.s.%20c%20200%20§%209[1975 1st ex.s. c 200 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c137.pdf?cite=1974%20ex.s.%20c%20137%20§%2017[1974 ex.s. c 137 § 17]; ]

== 76.09.180 - Disposition of moneys received as penalties, reimbursement for damages.
All penalties received or recovered by state agency action for violations as prescribed in RCW 76.09.170 shall be deposited in the state general fund. All such penalties recovered as a result of local government action shall be deposited in the local government general fund. Any funds recovered as reimbursement for damages pursuant to RCW 76.09.080 and 76.09.090 shall be transferred to that agency with jurisdiction over the public resource damaged, including but not limited to political subdivisions, the department of fish and wildlife, the department of ecology, the department of natural resources, or any other department that may be so designated: PROVIDED, That nothing herein shall be construed to affect the provisions of RCW 90.48.142.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2590.SL.pdf?cite=1994%20c%20264%20§%2050[1994 c 264 § 50]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c36.pdf?cite=1988%20c%2036%20§%2048[1988 c 36 § 48]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c137.pdf?cite=1974%20ex.s.%20c%20137%20§%2018[1974 ex.s. c 137 § 18]; ]

== 76.09.190 - Additional penalty, gross misdemeanor.
In addition to the penalties imposed pursuant to RCW 76.09.170, any person who conducts any forest practice or knowingly aids or abets another in conducting any forest practice in violation of any provisions of RCW 76.09.010 through 76.09.280 or 90.48.420, or of the regulations implementing RCW 76.09.010 through 76.09.280 or 90.48.420, shall be guilty of a gross misdemeanor and upon conviction thereof shall be punished by a fine of not less than one hundred dollars nor more than one thousand dollars, or by imprisonment for up to three hundred sixty-four days or by both fine and imprisonment for each separate violation. Each day upon which such violation occurs shall constitute a separate violation.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5168-S.SL.pdf?cite=2011%20c%2096%20§%2055[2011 c 96 § 55]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c137.pdf?cite=1974%20ex.s.%20c%20137%20§%2019[1974 ex.s. c 137 § 19]; ]

== 76.09.205 - Appeals board review.
A person aggrieved by the approval or disapproval of an application to conduct a forest practice or the approval or disapproval of any landscape plan or permit or watershed analysis may seek review from the appeals board by filing a request for the same within thirty days from the date of receipt of the decision. Concurrently with the filing of any request for review with the appeals board as provided in this section, the requestor must file a copy of his or her request with the department and the attorney general. The attorney general may intervene to protect the public interest and ensure that the provisions of this chapter are complied with.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2935-S.SL.pdf?cite=2010%20c%20210%20§%2024[2010 c 210 § 24]; ]

== 76.09.240 - Forest practices—County, city, or town to regulate—When—Adoption of development regulations—Enforcement—Technical assistance—Exceptions and limitations—Verification that land not subject to a notice of conversion to nonforestry uses—Reporting of information to the department of revenue.
. [Empty]
.. Counties planning under RCW 36.70A.040 with a population greater than one hundred thousand, and the cities and towns within those counties, where more than a total of twenty-five Class IV forest practices applications, as defined in RCW 76.09.050(1) Class IV (a) through (d), have been filed with the department between January 1, 2003, and December 31, 2005, shall adopt and enforce ordinances or regulations as provided in subsection (2) of this section for the following:

... Forest practices classified as Class I, II, III, and IV that are within urban growth areas designated under RCW 36.70A.110, except for forest practices on ownerships of contiguous forestland equal to or greater than twenty acres where the forestland owner provides, to the department and the county, city, or town, a written statement of intent, signed by the forestland owner, not to convert to a use other than growing commercial timber for ten years. This statement must be accompanied by either:

(A) A written forest management plan acceptable to the department; or

(B) Documentation that the land is enrolled as forestland of long-term commercial significance under the provisions of chapter 84.33 RCW; and

... Forest practices classified as Class IV, outside urban growth areas designated under RCW 36.70A.110, involving either timber harvest or road construction, or both on:

(A) Forestlands that are being converted to another use; or

(B) Lands which, under RCW 76.09.070, are not to be reforested because of the likelihood of future conversion to urban development;

.. Counties planning under RCW 36.70A.040, and the cities and towns within those counties, not included in (a) of this subsection, may adopt and enforce ordinances or regulations as provided in (a) of this subsection; and

.. Counties not planning under RCW 36.70A.040, and the cities and towns within those counties, may adopt and enforce ordinances or regulations as provided in subsection (2) of this section for forest practices classified as Class IV involving either timber harvest or road construction, or both on:

... Forestlands that are being converted to another use; or

... Lands which, under RCW 76.09.070, are not to be reforested because of the likelihood of future conversion to urban development.

. Before a county, city, or town may regulate forest practices under subsection (1) of this section, it shall ensure that its critical areas and development regulations are in compliance with RCW 36.70A.130 and, if applicable, RCW 36.70A.215. The county, city, or town shall notify the department and the department of ecology in writing sixty days prior to adoption of the development regulations required in this section. The transfer of jurisdiction shall not occur until the county, city, or town has notified the department, the department of revenue, and the department of ecology in writing of the effective date of the regulations. Ordinances and regulations adopted under subsection (1) of this section and this subsection must be consistent with or supplement development regulations that protect critical areas pursuant to RCW 36.70A.060, and shall at a minimum include:

.. Provisions that require appropriate approvals for all phases of the conversion of forestlands, including land clearing and grading; and

.. Procedures for the collection and administration of permit and recording fees.

. Activities regulated by counties, cities, or towns as provided in subsections (1) and (2) of this section shall be administered and enforced by those counties, cities, or towns. The department shall not regulate these activities under this chapter.

. The board shall continue to adopt rules and the department shall continue to administer and enforce those rules in each county, city, or town for all forest practices as provided in this chapter until such a time as the county, city, or town has updated its development regulations as required by RCW 36.70A.130 and, if applicable, RCW 36.70A.215, and has adopted ordinances or regulations under subsections (1) and (2) of this section. However, counties, cities, and towns that have adopted ordinances or regulations regarding forest practices prior to July 22, 2011, are not required to readopt their ordinances or regulations in order to satisfy the requirements of this section except as necessary to ensure consistency with Class IV forest practices as defined in RCW 76.09.050.

. Upon request, the department shall provide technical assistance to all counties, cities, and towns while they are in the process of adopting the regulations required by this section, and after the regulations become effective.

. For those forest practices over which the board and the department maintain regulatory authority no county, city, municipality, or other local or regional governmental entity shall adopt or enforce any law, ordinance, or regulation pertaining to forest practices, except that to the extent otherwise permitted by law, such entities may exercise any:

.. Land use planning or zoning authority: PROVIDED, That exercise of such authority may regulate forest practices only where the application submitted under RCW 76.09.060 as now or hereafter amended indicates that the lands are being converted to a use other than commercial forest product production: PROVIDED, That no permit system solely for forest practices shall be allowed; that any additional or more stringent regulations shall not be inconsistent with the forest practices regulations enacted under this chapter; and such local regulations shall not unreasonably prevent timber harvesting;

.. Taxing powers;

.. Regulatory authority with respect to public health; and

.. Authority granted by chapter 90.58 RCW, the "Shoreline Management Act of 1971."

. All counties and cities adopting or enforcing regulations or ordinances under this section shall include in the regulation or ordinance a requirement that a verification accompany every permit issued for forestland by that county or city associated with the conversion to a use other than commercial timber operation, as that term is defined in RCW 76.09.020, that verifies that the land in question is not or has not been subject to a notice of conversion to nonforestry uses under RCW 76.09.060 during the six-year period prior to the submission of a permit application.

. To improve the administration of the forest excise tax created in chapter 84.33 RCW, a county, city, or town that regulates forest practices under this section shall report permit information to the department of revenue for all approved forest practices permits. The permit information shall be reported to the department of revenue no later than sixty days after the date the permit was approved and shall be in a form and manner agreed to by the county, city, or town and the department of revenue. Permit information includes the landowner's legal name, address, telephone number, and parcel number.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1582.SL.pdf?cite=2011%20c%20207%20§%202[2011 c 207 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6481.SL.pdf?cite=2010%20c%20219%20§%201[2010 c 219 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1409-S.SL.pdf?cite=2007%20c%20236%20§%201[2007 c 236 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5883-S2.SL.pdf?cite=2007%20c%20106%20§%206[2007 c 106 § 6]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2399.SL.pdf?cite=2002%20c%20121%20§%202[2002 c 121 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5714-S.SL.pdf?cite=1997%20c%20173%20§%205[1997 c 173 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c200.pdf?cite=1975%201st%20ex.s.%20c%20200%20§%2011[1975 1st ex.s. c 200 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c137.pdf?cite=1974%20ex.s.%20c%20137%20§%2024[1974 ex.s. c 137 § 24]; ]

== 76.09.250 - Policy for continuing program of orientation and training.
The board shall establish a policy for a continuing program of orientation and training to be conducted by the department with relation to forest practices and the regulation thereof pursuant to RCW 76.09.010 through 76.09.280.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c137.pdf?cite=1974%20ex.s.%20c%20137%20§%2025[1974 ex.s. c 137 § 25]; ]

== 76.09.260 - Department to represent state's interest—Cooperation with other public agencies—Grants and gifts.
The department shall represent the state's interest in matters pertaining to forestry and forest practices, including federal matters, and may consult with and cooperate with the federal government and other states, as well as other public agencies, in the study and enhancement of forestry and forest practices. The department is authorized to accept, receive, disburse, and administer grants or other funds or gifts from any source, including private individuals or agencies, the federal government, and other public agencies for the purposes of carrying out the provisions of this chapter.

Nothing in this chapter shall modify the designation of the department of ecology as the agency representing the state for all purposes of the Federal Water Pollution Control Act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c137.pdf?cite=1974%20ex.s.%20c%20137%20§%2026[1974 ex.s. c 137 § 26]; ]

== 76.09.270 - Annual determination of state's research needs—Recommendations.
The department, along with other affected agencies and institutions, shall annually determine the state's needs for research in forest practices and the impact of such practices on public resources and shall recommend needed projects to the governor and the legislature.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c137.pdf?cite=1974%20ex.s.%20c%20137%20§%2027[1974 ex.s. c 137 § 27]; ]

== 76.09.280 - Removal of log and debris jams from streams.
Forestland owners shall permit reasonable access requested by appropriate agencies for removal from streambeds abutting their property of log and debris jams accumulated from upstream ownerships. Any owner of logs in such jams in claiming or removing them shall be required to remove all unmerchantable material from the streambed in accordance with the forest practices regulations. Any material removed from streambeds must also be removed in compliance with all applicable laws administered by other agencies.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c137.pdf?cite=1974%20ex.s.%20c%20137%20§%2028[1974 ex.s. c 137 § 28]; ]

== 76.09.290 - Inspection of lands—Reforestation.
The department shall inspect, or cause to be inspected, deforested lands of the state and ascertain if the lands are valuable chiefly for agriculture, timber growing, or other purposes, with a view to reforestation.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c100.pdf?cite=1986%20c%20100%20§%2049[1986 c 100 § 49]; ]

== 76.09.300 - Mass earth movements and fluvial processes—Program to correct hazardous conditions on sites associated with roads and railroad grades—Hazard-reduction plans.
. Mass earth movements and fluvial processes can endanger public resources and public safety. In some cases, action can be taken which has a probability of reducing the danger to public resources and public safety. In other cases it may be best to take no action. In order to determine where and what, if any, actions should be taken on forestlands, the department shall develop a program to correct hazardous conditions on identified sites associated with roads and railroad grades constructed on private and public forestlands prior to January 1, 1987. The first priority treatment shall be accorded to those roads and railroad grades constructed before the effective date of the forest practices act of 1974.

. This program shall be designed to accomplish the purposes and policies set forth in RCW 76.09.010. For each geographic area studied, the department shall produce a hazard-reduction plan which shall consist of the following elements:

.. Identification of sites where the department determines that earth movements or fluvial processes pose a significant danger to public resources or public safety: PROVIDED, That no liability shall attach to the state of Washington or the department for failure to identify such sites;

.. Recommendations for the implementation of any appropriate hazard-reduction measures on the identified sites, which minimize interference with natural processes and disturbance to the environment;

.. Analysis of the costs and benefits of each of the hazard-reduction alternatives, including a no-action alternative.

. In developing these plans, it is intended that the department utilize appropriate scientific expertise including a geomorphologist, a forest hydrologist, and a forest engineer.

. In developing these plans, the department shall consult with affected tribes, landowners, governmental agencies, and interested parties.

. Unless requested by a forestland owner under RCW 76.09.320, the department shall study geographic areas for participation in the program only to the extent that funds have been appropriated for cost sharing of hazard-reduction measures under RCW 76.09.320.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c95.pdf?cite=1987%20c%2095%20§%202[1987 c 95 § 2]; ]

== 76.09.305 - Advisory committee to review hazard-reduction plans authorized—Compensation, travel expenses.
The forest practices board may, upon request of the department or at its own discretion, appoint an advisory committee consisting of not more than five members qualified by appropriate experience and training to review and comment upon such draft hazard reduction plans prepared by the department as the department submits for review.

If an advisory committee is established, and within ninety days following distribution of a draft plan, the advisory committee shall prepare a written report on each hazard reduction plan submitted to it. The report, which shall be kept on file by the department, shall address each of those elements described in RCW 76.09.300(2).

Final authority for each plan is vested in the department, and advisory committee comments and decisions shall be advisory only. The exercise by advisory committee members of their authority to review and comment shall not imply or create any liability on their part. Advisory committee members shall be compensated as provided for in RCW 43.03.250 and shall receive reimbursement for travel expenses as provided by RCW 43.03.050 and 43.03.060.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c95.pdf?cite=1987%20c%2095%20§%203[1987 c 95 § 3]; ]

== 76.09.310 - Hazard-reduction program—Notice to landowners within areas selected for review—Proposed plans—Objections to plan, procedure—Final plans—Appeal.
. The department shall send a notice to all forestland owners, both public and private, within the geographic area selected for review, stating that the department intends to study the area as part of the hazard-reduction program.

. The department shall prepare a proposed plan for each geographic area studied. The department shall provide the proposed plan to affected landowners, Indian tribes, interested parties, and to the advisory committee, if established pursuant to RCW 76.09.305.

. Any aggrieved landowners, agencies, tribes, and other persons who object to any or all of the proposed hazard-reduction plan may, within thirty days of issuance of the plan, request the department in writing to schedule a conference. If so requested, the department shall schedule a conference on a date not more than thirty days after receiving such request.

. Within ten days after such a conference, the department shall either amend the proposed plan or respond in writing indicating why the objections were not incorporated into the plan.

. Within one hundred twenty days following the issuance of the proposed plan as provided in subsection (2) of this section, the department shall distribute a final hazard-reduction plan designating those sites for which hazard-reduction measures are recommended and those sites where no action is recommended. For each hazard-reduction measure recommended, a description of the work and cost estimate shall be provided.

. Any aggrieved landowners, agencies, tribes, and other persons are entitled to appeal the final hazard-reduction plan to the appeals board if, within thirty days of the issuance of the final plan, the party transmits a notice of appeal to the appeals board and to the department.

. A landowner's failure to object to the recommendations or to appeal the final hazard-reduction plan shall not be deemed an admission that the hazard-reduction recommendations are appropriate.

. The department shall provide a copy of the final hazard-reduction plan to the department of ecology and to each affected county.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2935-S.SL.pdf?cite=2010%20c%20210%20§%2025[2010 c 210 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c95.pdf?cite=1987%20c%2095%20§%204[1987 c 95 § 4]; ]

== 76.09.315 - Implementation of hazard-reduction measures—Election—Notice and application for cost-sharing funds—Inspection—Letter of compliance—Limitations on liability.
. When a forestland owner elects to implement the recommended hazard-reduction measures, the landowner shall notify the department and apply for cost-sharing funds. Upon completion, the department shall inspect the remedial measures undertaken by the forestland owner. If, in the department's opinion, the remedial measures have been properly implemented, the department shall promptly transmit a letter to the landowner stating that the landowner has complied with the hazard-reduction measures.

. Forestland owners, public and private, of hazard-reduction sites reviewed by the department and who have complied with the department's recommendations for sites which require action shall not be liable for any personal injuries or property damage, occurring on or off the property reviewed, arising from mass earth movements or fluvial processes associated with the hazard-reduction site reviewed. The limitation on liability contained in this subsection shall also cover personal injuries or property damage arising from mass earth movements or fluvial processes which are associated with those areas disturbed by activities required to acquire site access and to execute the plan when such activities are approved as part of a hazard-reduction plan. Notwithstanding the foregoing provisions of this subsection, a landowner may be liable when the landowner had actual knowledge of a dangerous artificial latent condition on the property that was not disclosed to the department.

. The exercise by the department of its authority, duties, and responsibilities provided for developing and implementing the hazard-reduction program and plans shall not imply or create any liability in the state of Washington or the department except that the department may be liable if the department is negligent in making a final hazard-reduction plan or in approving the implementation of specific hazard-reduction measures.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c95.pdf?cite=1987%20c%2095%20§%205[1987 c 95 § 5]; ]

== 76.09.320 - Implementation of hazard-reduction program—Cost sharing by department—Limitations.
. Subject to the availability of appropriated funds, the department shall pay fifty percent of the cost of implementing the hazard-reduction program, except as provided in subsection (2) of this section.

. In the event department funds described in subsection (1) of this section are not available for all or a portion of a forestland owner's property, the landowner may request application of the hazard-reduction program to the owner's lands, provided the landowner funds one hundred percent of the cost of implementation of the department's recommended actions on his or her property.

. No cost-sharing funds may be made available for sites where the department determines that the hazardous condition results from a violation of then-prevailing standards as established by statute or rule.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20231[2013 c 23 § 231]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c95.pdf?cite=1987%20c%2095%20§%206[1987 c 95 § 6]; ]

== 76.09.330 - Legislative findings—Liability from naturally falling trees required to be left standing.
The legislature hereby finds and declares that riparian ecosystems on forestlands in addition to containing valuable timber resources, provide benefits for wildlife, fish, and water quality. The legislature further finds and declares that leaving riparian areas unharvested and leaving snags and green trees for large woody debris recruitment for streams and rivers provides public benefits including but not limited to benefits for threatened and endangered salmonids, other fish, amphibians, wildlife, and water quality enhancement. The legislature further finds and declares that leaving upland areas unharvested for wildlife and leaving snags and green trees for future snag recruitment provides benefits for wildlife. Forestland owners may be required to leave trees standing in riparian and upland areas to benefit public resources. It is recognized that these trees may blow down or fall into streams and that organic debris may be allowed to remain in streams. This is beneficial to riparian dependent and other wildlife species. Further, it is recognized that trees may blow down, fall onto, or otherwise cause damage or injury to public improvements, private property, and persons. Notwithstanding any statutory provision, rule, or common law doctrine to the contrary, the landowner, the department, and the state of Washington shall not be held liable for any injury or damages resulting from these actions, including but not limited to wildfire, erosion, flooding, personal injury, property damage, damage to public improvements, and other injury or damages of any kind or character resulting from the trees being left.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2091-S.SL.pdf?cite=1999%20sp.s.%20c%204%20§%20602[1999 sp.s. c 4 § 602]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2330-S.SL.pdf?cite=1992%20c%2052%20§%205[1992 c 52 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c95.pdf?cite=1987%20c%2095%20§%207[1987 c 95 § 7]; ]

== 76.09.340 - Certain forest practices exempt from rules and policies under this chapter.
Forest practices consistent with a habitat conservation plan approved prior to March 25, 1996, by the secretary of the interior or commerce under 16 U.S.C. Sec. 1531 et seq., and the endangered species act of 1973 as amended, are exempt from rules and policies under this chapter, provided the proposed forest practices indicated in the application are in compliance with the plan, and provided this exemption applies only to rules and policies adopted primarily for the protection of one or more species, including unlisted species, covered by the plan. Such forest practices are deemed not to have the potential for a substantial impact on the environment but may be found to have the potential for a substantial impact on the environment due to other reasons under RCW 76.09.050.

Nothing in this section is intended to limit the board's rule-making authority under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2444-S.SL.pdf?cite=1996%20c%20136%20§%201[1996 c 136 § 1]; ]

== 76.09.350 - Long-term multispecies landscape management plans—Pilot projects, selection—Plan approval, elements—Notice of agreement recorded—Memorandums of agreements—Report, evaluation.
The legislature recognizes the importance of providing the greatest diversity of habitats, particularly riparian, wetland, and old growth habitats, and of assuring the greatest diversity of species within those habitats for the survival and reproduction of enough individuals to maintain the native wildlife of Washington forestlands. The legislature also recognizes the importance of long-term habitat productivity for natural and wild fish, for the protection of hatchery water supplies, and for the protection of water quality and quantity to meet the needs of people, fish, and wildlife. The legislature recognizes the importance of maintaining and enhancing fish and wildlife habitats capable of sustaining the commercial and noncommercial uses of fish and wildlife. The legislature further recognizes the importance of the continued growth and development of the state's forest products industry which has a vital stake in the long-term productivity of both the public and private forestland base.

The development of a landscape planning system would help achieve these goals. Landowners and resource managers should be provided incentives to voluntarily develop long-term multispecies landscape management plans that will provide protection to public resources. Because landscape planning represents a departure from the use of standard baseline rules and may result in unintended consequences to both the affected habitats and to a landowner's economic interests, the legislature desires to establish up to seven experimental pilot programs to gain experience with landscape planning that may prove useful in fashioning legislation of a more general application.

. Until December 31, 2000, the department in cooperation with the department of fish and wildlife, and the department of ecology when relating to water quality protection, is granted authority to select not more than seven pilot projects for the purpose of developing individual landowner multispecies landscape management plans.

.. Pilot project participants must be selected by the department in cooperation with the department of fish and wildlife, and the department of ecology when relating to water quality protection, no later than October 1, 1997.

.. The number and the location of the pilot projects are to be determined by the department in cooperation with the department of fish and wildlife, and the department of ecology when relating to water quality protection, and should be selected on the basis of risk to the habitat and species, variety and importance of species and habitats in the planning area, geographic distribution, surrounding ownership, other ongoing landscape and watershed planning activities in the area, potential benefits to water quantity and quality, financial and staffing capabilities of participants, and other factors that will contribute to the creation of landowner multispecies landscape planning efforts.

.. Each pilot project shall have a landscape management plan with the following elements:

... An identification of public resources selected for coverage under the plan and measurable objectives for the protection of the selected public resources;

... A termination date of not later than 2050;

... A general description of the planning area including its geographic location, physical and biological features, habitats, and species known to be present;

... An identification of the existing forest practices rules that will not apply during the term of the plan;

.. Proposed habitat management strategies or prescriptions;

.. A projection of the habitat conditions likely to result from the implementation of the specified management strategies or prescriptions;

.. An assessment of habitat requirements and the current habitat conditions of representative species included in the plan;

.. An assessment of potential or likely impacts to representative species resulting from the prescribed forest practices;

... A description of the anticipated benefits to those species or other species as a result of plan implementation;

.. A monitoring plan;

.. Reporting requirements including a schedule for review of the plan's performance in meeting its objectives;

.. Conditions under which a plan may be modified, including a procedure for adaptive management;

.. Conditions under which a plan may be terminated;

.. A procedure for adaptive management that evaluates the effectiveness of the plan to meet its measurable public resources objectives, reflects changes in the best available science, and provides changes to its habitat management strategies, prescriptions, and hydraulic project standards to the extent agreed to in the plan and in a timely manner and schedule;

.. A description of how the plan relates to publicly available plans of adjacent federal, state, tribal, and private timberland owners; and

.. A statement of whether the landowner intends to apply for approval of the plan under applicable federal law.

. Until December 31, 2000, the department, in agreement with the department of fish and wildlife, and the department of ecology when the landowner elects to cover water quality in the plan, shall approve a landscape management plan and enter into a binding implementation agreement with the landowner when such departments find, based upon the best scientific data available, that:

.. The plan contains all of the elements required under this section including measurable public resource objectives;

.. The plan is expected to be effective in meeting those objectives;

.. The landowner has sufficient financial resources to implement the management strategies or prescriptions to be implemented by the landowner under the plan;

.. The plan will:

... Provide better protection than current state law for the public resources selected for coverage under the plan considered in the aggregate; and

... Compared to conditions that could result from compliance with current state law:

(A) Not result in poorer habitat conditions over the life of the plan for any species selected for coverage that is listed as threatened or endangered under federal or state law, or that has been identified as a candidate for such listing, at the time the plan is approved; and

(B) Measurably improve habitat conditions for species selected for special consideration under the plan;

.. The plan shall include watershed analysis or provide for a level of protection that meets or exceeds the protection that would be provided by watershed analysis, if the landowner selects fish or water quality as a public resource to be covered under the plan. Any alternative process to watershed analysis would be subject to timely peer review;

.. The planning process provides for a public participation process during the development of the plan, which shall be developed by the department in cooperation with the landowner.

The management plans must be submitted to the department and the department of fish and wildlife, and the department of ecology when the landowner elects to cover water quality in the plan, no later than March 1, 2000. The department shall provide an opportunity for public comment on the proposed plan. The comment period shall not be less than forty-five days. The department shall approve or reject plans within one hundred twenty days of submittal by the landowner of a final plan. The decision by the department, in agreement with the department of fish and wildlife, and the department of ecology when the landowner has elected to cover water quality in the plan, to approve or disapprove the management plan is subject to the environmental review process of chapter 43.21C RCW, provided that any public comment period provided for under chapter 43.21C RCW shall run concurrently with the public comment period provided in this subsection (2).

. After a landscape management plan is adopted:

.. Forest practices consistent with the plan need not comply with:

... The specific forest practices rules identified in the plan; and

... Any forest practice rules and policies adopted after the approval of the plan to the extent that the rules:

(A) Have been adopted primarily for the protection of a public resource selected for coverage under the plan; or

(B) Provide for procedural or administrative obligations inconsistent with or in addition to those provided for in the plan with respect to those public resources; and

.. If the landowner has selected fish as one of the public resources to be covered under the plan, the plan shall serve as the hydraulic project approval for the life of the plan, in compliance with *RCW 77.55.100.

. The department is authorized to issue a single landscape level permit valid for the life of the plan to a landowner who has an approved landscape management plan and who has requested a landscape permit from the department. Landowners receiving a landscape level permit shall meet annually with the department and the department of fish and wildlife, and the department of ecology where water quality has been selected as a public resource to be covered under the plan, to review the specific forest practices activities planned for the next twelve months and to determine whether such activities are in compliance with the plan. The departments will consult with the affected Indian tribes and other interested parties who have expressed an interest in connection with the review. The landowner is to provide ten calendar days' notice to the department prior to the commencement of any forest practices authorized under a landscape level permit. The landscape level permit will not impose additional conditions relating to the public resources selected for coverage under the plan beyond those agreed to in the plan. For the purposes of chapter 43.21C RCW, forest practices conducted in compliance with an approved plan are deemed not to have the potential for a substantial impact on the environment as to any public resource selected for coverage under the plan.

. Except as otherwise provided in a plan, the agreement implementing the landscape management plan is an agreement that runs with the property covered by the approved landscape management plan and the department shall record notice of the plan in the real property records of the counties in which the affected properties are located. Prior to its termination, no plan shall permit forestland covered by its terms to be withdrawn from such coverage, whether by sale, exchange, or other means, nor to be converted to nonforestry uses except to the extent that such withdrawal or conversion would not measurably impair the achievement of the plan's stated public resource objectives. If a participant transfers all or part of its interest in the property, the terms of the plan still apply to the new landowner for the plan's stated duration unless the plan is terminated under its terms or unless the plan specifies the conditions under which the terms of the plan do not apply to the new landowner.

. The departments of natural resources, fish and wildlife, and ecology shall seek to develop memorandums of agreements with federal agencies and affected Indian tribes relating to tribal issues in the landscape management plans. The departments shall solicit input from affected Indian tribes in connection with the selection, review, and approval of any landscape management plan. If any recommendation is received from an affected Indian tribe and is not adopted by the departments, the departments shall provide a written explanation of their reasons for not adopting the recommendation.

. The department is directed to report to the forest practices board annually through the year 2000, but no later than December 31st of each year, on the status of each pilot project. The department is directed to provide to the forest practices board, no later than December 31, 2000, an evaluation of the pilot projects including a determination if a permanent landscape planning process should be established along with a discussion of what legislative and rule modifications are necessary.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5172.SL.pdf?cite=2003%20c%2039%20§%2034[2003 c 39 § 34]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1985-S.SL.pdf?cite=1997%20c%20290%20§%201[1997 c 290 § 1]; ]

== 76.09.360 - Single multiyear permit.
The department together with the department of fish and wildlife, and the department of ecology relating to water quality protection, shall develop a suitable process to permit landowners to secure all permits required for the conduct of forest practices in a single multiyear permit to be jointly issued by the departments and the departments shall report their findings to the legislature not later than December 31, 2000.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1985-S.SL.pdf?cite=1997%20c%20290%20§%202[1997 c 290 § 2]; ]

== 76.09.368 - Intent—Small forestland owners—Alternate plan processes/alternate harvest restrictions—Report to the legislature.
The legislature intends that small forestland owners have access to alternate plan processes or alternate harvest restrictions, or both if necessary, that meet the public resource protection standard set forth in RCW 76.09.370(3), but which also lowers the overall cost of regulation to small forestland owners including, but not limited to, timber value forgone, layout costs, and operating costs. The forest practices board shall consult with the small forestland owner office advisory committee in developing these alternate approaches. By July 1, 2003, the forest practices board shall provide the legislature with a written report that describes the board's progress in developing alternate plan processes or alternate harvest restrictions, or both if necessary, that meet legislative intent.

As used in this section, "small forestland owner" has the same meaning as defined in RCW 76.13.120(2).

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2311-S2.SL.pdf?cite=2002%20c%20120%20§%204[2002 c 120 § 4]; ]

== 76.09.370 - Findings—Forests and fish report—Adoption of rules.
. The legislature finds that the process that produced the forests and fish report was instigated by the forest practices board, the report is the product of considerable negotiations between several diverse interest groups, and the report has the support of key federal agencies. When adopting permanent rules under this section, the forest practices board is strongly encouraged to follow the recommendations of the forests and fish report, but may include other alternatives for protection of aquatic resources. If the forest practices board chooses to adopt rules under this section that are not consistent with the recommendations contained in the forests and fish report, the board must notify the appropriate legislative committees of the proposed deviations, the reasons for the proposed deviations, and whether the parties to the forests and fish report still support the agreement. The board shall defer final adoption of such rules for sixty days of the legislative session to allow for the opportunity for additional public involvement and legislative oversight.

. The forest practices board shall follow the regular rules adoption process contained in the administrative procedure act, chapter 34.05 RCW, when adopting permanent rules pertaining to forest practices and the protection of aquatic resources except as limited by subsection (1) of this section. The permanent rules must accomplish the policies stated in RCW 76.09.010 without jeopardizing the economic viability of the forest products industry.

. The rules adopted under this section should be as specific as reasonably possible while also allowing an applicant to propose alternate plans in response to site-specific physical features. Alternate plans should provide protection to public resources at least equal in overall effectiveness by alternate means.

. Rule making under subsection (2) of this section shall be completed by June 30, 2001.

. The board should consider coordinating any environmental review process under chapter 43.21C RCW relating to the adoption of rules under subsection (2) of this section with any review of a related proposal under the national environmental policy act (42 U.S.C. Sec. 4321, et seq.).

. After the board has adopted permanent rules under subsection (2) of this section, changes to those rules and any new rules covering aquatic resources may be adopted by the board but only if the changes or new rules are consistent with recommendations resulting from the scientifically based adaptive management process established by a rule of the board. Any new rules or changes under this subsection need not be based upon the recommendations of the adaptive management process if: (a) The board is required to adopt or modify rules by the final order of any court having jurisdiction thereof; or (b) future state legislation directs the board to adopt or modify the rules.

. In adopting permanent rules, the board shall incorporate the scientific-based adaptive management process described in the forests and fish report which will be used to determine the effectiveness of the new forest practices rules in aiding the state's salmon recovery effort. The purpose of an adaptive management process is to make adjustments as quickly as possible to forest practices that are not achieving the resource objectives. The adaptive management process shall incorporate the best available science and information, include protocols and standards, regular monitoring, a scientific and peer review process, and provide recommendations to the board on proposed changes to forest practices rules to meet timber industry viability and salmon recovery.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2091-S.SL.pdf?cite=1999%20sp.s.%20c%204%20§%20204[1999 sp.s. c 4 § 204]; ]

== 76.09.390 - Sale of land or timber rights with continuing obligations—Notice—Failure to notify—Exemption.
. Except as provided in subsection (2) of this section, prior to the sale or transfer of land or perpetual timber rights subject to continuing forestland obligations under the forest practices rules adopted under RCW 76.09.370, as specifically identified in the forests and fish report the seller shall notify the buyer of the existence and nature of such a continuing obligation and the buyer shall sign a notice of continuing forestland obligation indicating the buyer's knowledge thereof. The notice shall be on a form prepared by the department and shall be sent to the department by the seller at the time of sale or transfer of the land or perpetual timber rights and retained by the department. If the seller fails to notify the buyer about the continuing forestland obligation, the seller shall pay the buyer's costs related to such continuing forestland obligation, including all legal costs and reasonable attorneys' fees, incurred by the buyer in enforcing the continuing forestland obligation against the seller. Failure by the seller to send the required notice to the department at the time of sale shall be prima facie evidence, in an action by the buyer against the seller for costs related to the continuing forestland obligation, that the seller did not notify the buyer of the continuing forestland obligation prior to sale.

. Subsection (1) of this section does not apply to checklist road maintenance and abandonment plans created by RCW 76.09.420.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1095-S2.SL.pdf?cite=2003%20c%20311%20§%206[2003 c 311 § 6]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2091-S.SL.pdf?cite=1999%20sp.s.%20c%204%20§%20707[1999 sp.s. c 4 § 707]; ]

== 76.09.405 - Forest and fish support account—Created.
The forest and fish support account is hereby created in the state treasury. Receipts from appropriations, the surcharge imposed under RCW 82.04.261, and other sources must be deposited into the account. Expenditures from the account shall be used for activities pursuant to the state's implementation of the forests and fish report as defined in this chapter and related activities including, but not limited to, adaptive management, monitoring, and participation grants to tribes, state and local agencies, and not-for-profit public interest organizations. Expenditures from the account may be made only after appropriation by the legislature. During the 2019-2021 fiscal biennium, the legislature may appropriate moneys from the account for activities to implement this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1109-S.SL.pdf?cite=2019%20c%20415%20§%20982[2019 c 415 § 982]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1381-S.SL.pdf?cite=2007%20c%2054%20§%203[2007 c 54 § 3]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1513-S.SL.pdf?cite=2007%20c%2048%20§%201[2007 c 48 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6874-S.SL.pdf?cite=2006%20c%20300%20§%203[2006 c 300 § 3]; ]

== 76.09.410 - Road maintenance and abandonment plans—Fish passage barriers.
. The state may not require a small forestland owner to invest in upgrades, replacements, or other engineering of a forest road, and any fish passage barriers that are a part of the road, that do not threaten public resources or create a barrier to the passage of fish.

. Participation in the forests and fish agreement provides a benefit to both the landowner in terms of federal assurances, and the public in terms of aquatic habitat preservation and water quality enhancement; therefore, if conditions do threaten public resources or create a fish passage barrier, the road maintenance and abandonment planning process may not require a small forestland owner to take a positive action that will result in high cost without a significant portion of that cost being shared by the public.

. Some fish passage barriers are more of a threat to public resources than others; therefore, no small forestland owner should be required to repair a fish passage barrier until higher priority fish passage barriers on other lands in the watershed have been repaired.

. If an existing fish passage barrier on land owned by a small forestland owner was installed under an approved forest practices application or notification, and hydraulics approval, and that fish passage barrier becomes a high priority for fish passage based on the watershed ranking in *RCW 76.13.150, one hundred percent public funding shall be provided.

. The preparation of a road maintenance and abandonment plan can require technical expertise that may require large expenditures before the time that the landowner plans to conduct any revenue-generating operations on his or her land; therefore, small forestland owners should be allowed to complete a simplified road maintenance and abandonment plan checklist, that does not require professional engineering or forestry expertise to complete, and that does not need to be submitted until the time that the landowner submits a forest practices application or notification for final or intermediate harvesting, or for salvage of trees. Chapter 311, Laws of 2003 is intended to provide an alternate way for small forestland owners to comply with the road maintenance and abandonment plan goals identified in the forest practices rules.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1095-S2.SL.pdf?cite=2003%20c%20311%20§%202[2003 c 311 § 2]; ]

== 76.09.420 - Road maintenance and abandonment plans—Rules—Checklist—Report to the legislature—Emergency rules.
. The board must amend the forest practices rules relating to road maintenance and abandonment plans that exist on May 14, 2003, to reflect the following:

.. A forestland owner who owns a total of eighty acres or less of forestland in Washington is not required to submit a road maintenance and abandonment plan for any block of forestland that is twenty contiguous acres or less in area;

.. A landowner who satisfies the definition of a small forestland owner, but who does not qualify under (a) of this subsection, is only required to submit a checklist road maintenance and abandonment plan with the abbreviated content requirements provided for in subsection (3) of this section, and is not required to comply with annual reporting and review requirements; and

.. Existing forest roads must be maintained only to the extent necessary to prevent damage to public resources.

. The department must provide a landowner who is either exempted from submitting a road maintenance and abandonment plan under subsection (1)(a) of this section, or who qualifies for a checklist road maintenance and abandonment plan under subsection (1)(b) of this section, with an educational brochure outlining road maintenance standards and requirements. In addition, the department must develop a series of nonmandatory educational workshops on the rules associated with road construction and maintenance.

. [Empty]
.. A landowner who qualifies for a checklist road maintenance and abandonment plan under subsection (1)(b) of this section is only required to submit a checklist, designed by the department in consultation with the small forestland owner office advisory committee created in RCW 76.13.110, that confirms that the landowner is applying the checklist criteria to forest roads covered or affected by a forest practices application or notification. When developing the checklist road maintenance and abandonment plan, the department shall ensure that the checklist does not exceed current state law. Nothing in this subsection increases or adds to small forestland owners' duties or responsibilities under any other section of the forest practices rules or any other state law or rule.

.. A landowner who qualifies for the checklist road maintenance and abandonment plan is not required to submit the checklist before the time that he or she submits a forest practices application or notification for final or intermediate harvesting, or for salvage of trees. The department may encourage and accept checklists prior to the time that they are due.

. The department must monitor the extent of the checklist road maintenance and abandonment plan approach and report its findings to the appropriate committees of the legislature by December 31, 2008, and December 31, 2013.

. The board shall adopt emergency rules under RCW 34.05.090 by October 31, 2003, to implement this section. The emergency rules shall remain in effect until permanent rules can be adopted. The forest practices rules that relate to road maintenance and abandonment plans shall remain in effect as they existed on May 14, 2003, until emergency rules have been adopted under this section.

. This section is only intended to relate to the board's duties as they relate to the road maintenance and abandonment plan element of the forests and fish report. Nothing in this section alters any forestland owner's duties and responsibilities under any other section of the forest practices rules, or any other state law or rule.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1095-S2.SL.pdf?cite=2003%20c%20311%20§%204[2003 c 311 § 4]; ]

== 76.09.430 - Application to RCW  76.13.150.
RCW 76.13.150 applies to road maintenance and abandonment plans under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1095-S2.SL.pdf?cite=2003%20c%20311%20§%208[2003 c 311 § 8]; ]

== 76.09.440 - Small forestland owner—Fish passage barriers.
The department shall not disapprove a forest practices application filed by a small forestland owner on the basis that fish passage barriers have not been removed or replaced if the small forestland owner filing the application has committed to participate in the program established in RCW 76.13.150 for all fish passage barriers existing on the block of forestland covered by the forest practices application, and the fish passage barriers existing on the block of forestland covered by the forest practices application are lower on the funding order list established for the program than the current projects that are capable of being funded by the program.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1095-S2.SL.pdf?cite=2003%20c%20311%20§%209[2003 c 311 § 9]; ]

== 76.09.450 - Small forestland owner—Defined.
For the purposes of this chapter and RCW 76.13.150 and 77.12.755, "small forestland owner" means an owner of forestland who, at the time of submission of required documentation to the department, has harvested from his or her own lands in this state no more than an average timber volume of two million board feet per year during the three years prior to submitting documentation to the department and who certifies that he or she does not expect to harvest from his or her own lands in the state more than an average timber volume of two million board feet per year during the ten years following the submission of documentation to the department. However, any landowner who exceeded the two million board feet annual average timber harvest threshold from their land in the three years prior to submitting documentation to the department, or who expects to exceed the threshold during any of the following ten years, shall still be deemed a "small forestland owner" if he or she establishes to the department's reasonable satisfaction that the harvest limits were, or will be, exceeded in order to raise funds to pay estate taxes or for an equally compelling and unexpected obligation, such as for a court-ordered judgment or for extraordinary medical expenses.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1095-S2.SL.pdf?cite=2003%20c%20311%20§%2011[2003 c 311 § 11]; ]

== 76.09.460 - Notice of conversion to nonforestry use—Denial of permits or approvals by the county, city, town, or regional governmental entity—Enforcement.
If a county, city, town, or regional governmental entity receives a notice of conversion to nonforestry use by the department under RCW 76.09.060, then the county, city, town, or regional governmental entity must deny all applications for permits or approvals, including building permits and subdivision approvals, relating to nonforestry uses of the land that is the subject of the notification. The prohibition created by this section must be enforced by the county, city, town, or regional governmental entity:

. For a period of six years from the approval date of the applicable forest practices application or notification or the date that the department was made aware of the harvest activities; or

. Until the following activities are completed for the land that is the subject of the notice of conversion to a nonforestry use:

.. Full compliance with chapter 43.21C RCW, if applicable;

.. The department has notified the county, city, town, or regional governmental entity that the landowner has resolved any outstanding final orders or decisions issued by the department; and

.. A determination is made by the county, city, town, or regional governmental entity as to whether or not the condition of the land in question is in full compliance with local ordinances and regulations. If full compliance is not found, a mitigation plan to address violations of local ordinances or regulations must be required for the parcel in question by the county, city, town, or regional governmental entity. Required mitigation plans must be prepared by the landowner and approved by the county, city, town, or regional governmental entity. Once approved, the mitigation plan must be implemented by the landowner. Mitigation measures that may be required include, but are not limited to, revegetation requirements to plant and maintain trees of sufficient maturity and appropriate species composition to restore critical area and buffer function or to be in compliance with applicable local government regulations.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5883-S2.SL.pdf?cite=2007%20c%20106%20§%202[2007 c 106 § 2]; ]

== 76.09.470 - Conversion of land to nonforestry use—Action required of landowner—Action required of county, city, town, or regional governmental entity.
. If a landowner who did not state an intent to convert his or her land to a nonforestry use decides to convert his or her land to a nonforestry use within six years of receiving an approved forest practices application or notification under this chapter, the landowner must:

.. Stop all forest practices activities on the parcels subject to the proposed land use conversion to a nonforestry use;

.. Contact the department of ecology and the applicable county, city, town, or regional governmental entity to begin the permitting process; and

.. Notify the department, withdraw any applicable applications or notifications, and submit a new application for the conversion. The fee for a new application for conversion under this subsection (1)(c) is the difference between the applicable fee for the new application under RCW 76.09.065 and the fee previously paid for the original application or notification, which must be deposited in the forest practices application account created in RCW 76.09.065.

. Upon being contacted by a landowner under this section, the county, city, town, or regional governmental entity must:

.. Notify the department and request from the department the status of any applicable forest practices applications, notifications, or final orders or decisions; and

.. Complete the following activities:

... Require that the landowner be in full compliance with chapter 43.21C RCW, if applicable;

... Receive notification from the department that the landowner has resolved any outstanding final orders or decisions issued by the department; and

... Make a determination as to whether or not the condition of the land in question is in full compliance with local ordinances and regulations. If full compliance is not found, a mitigation plan to address violations of local ordinances or regulations must be required for the parcel in question by the county, city, town, or regional governmental entity. Required mitigation plans must be prepared by the landowner and approved by the county, city, town, or regional governmental entity. Once approved, the mitigation plan must be implemented by the landowner. Mitigation measures that may be required include, but are not limited to, revegetation requirements to plant and maintain trees of sufficient maturity and appropriate species composition to restore critical area and buffer function or to be in compliance with applicable local government regulations.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6406-S.SL.pdf?cite=2012%201st%20sp.s.%20c%201%20§%20210[2012 1st sp.s. c 1 § 210]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5883-S2.SL.pdf?cite=2007%20c%20106%20§%203[2007 c 106 § 3]; ]

== 76.09.480 - Identification of projects that mitigate infrastructure and noninfrastructure development.
The department and, when appropriate, the small forestland owner office established in RCW 76.13.110 must assist in identifying potential projects that can be used for the mitigation of infrastructure and noninfrastructure development, as those terms are defined in RCW 90.74.010, as provided in RCW 90.74.040.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2238-S2.SL.pdf?cite=2012%20c%2062%20§%208[2012 c 62 § 8]; ]

== 76.09.490 - Forest practices hydraulic project—Department may request information/technical assistance from the department of fish and wildlife—Concurrence review process.
. The department may request information and technical assistance from the department of fish and wildlife regarding any forest practices hydraulic project regulated under this chapter.

. A concurrence review process is established for certain forest practices hydraulic projects, as follow[s]:

.. After receiving an application under RCW 76.09.050 that includes a forest practices hydraulic project involving one or more water crossing structures meeting the criteria of (b) of this subsection, the department shall provide all necessary information provided by the applicant to the department of fish and wildlife for concurrence review consistent with RCW 77.55.361(3). The required information must be transmitted by the department to the department of fish and wildlife as soon as practicable following the receipt of a complete application.

.. The concurrence review process applies only to:

... Culvert installation or replacement, and repair at or below the bankfull width, as that term is defined in WAC 222-16-010 on July 10, 2012, in fish bearing rivers and streams that exceed five percent gradient;

... Bridge construction or replacement, and repair at or below the bankfull width, of fish bearing unconfined streams; or

... Fill within the flood level - 100 year, as that term is defined in WAC 222-16-010, as it existed on July 10, 2012, of fish bearing unconfined streams.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6406-S.SL.pdf?cite=2012%201st%20sp.s.%20c%201%20§%20202[2012 1st sp.s. c 1 § 202]; ]

== 76.09.900 - Short title.
Sections 1 through 28 of this 1974 act shall be known and may be cited as the "Forest Practices Act of 1974".

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c137.pdf?cite=1974%20ex.s.%20c%20137%20§%2029[1974 ex.s. c 137 § 29]; ]

== 76.09.905 - Air pollution laws not modified.
Nothing in RCW 76.09.010 through 76.09.280 or 90.48.420 shall modify chapter 70A.15 RCW or any other provision of law relating to the control of air pollution.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1192.SL.pdf?cite=2021%20c%2065%20§%2080[2021 c 65 § 80]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c137.pdf?cite=1974%20ex.s.%20c%20137%20§%2031[1974 ex.s. c 137 § 31]; ]

== 76.09.910 - Shoreline management act, hydraulics act, other statutes and ordinances not modified—Exceptions.
Nothing in RCW 76.09.010 through 76.09.280 as now or hereafter amended shall modify any requirements to comply with the Shoreline Management Act of 1971 except as limited by RCW 76.09.240 as now or hereafter amended, or the hydraulics act (*RCW 77.55.100), other state statutes in effect on January 1, 1975, and any local ordinances not inconsistent with RCW 76.09.240 as now or hereafter amended.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5172.SL.pdf?cite=2003%20c%2039%20§%2035[2003 c 39 § 35]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c200.pdf?cite=1975%201st%20ex.s.%20c%20200%20§%2012[1975 1st ex.s. c 200 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c137.pdf?cite=1974%20ex.s.%20c%20137%20§%2032[1974 ex.s. c 137 § 32]; ]

== 76.09.915 - Repeal and savings.
. The following acts or parts of acts are each repealed:

.. Section 2, chapter 193, Laws of 1945, section 1, chapter 218, Laws of 1947, section 1, chapter 44, Laws of 1953, section 1, chapter 79, Laws of 1957, section 10, chapter 207, Laws of 1971 ex. sess. and RCW 76.08.010;

.. Section 1, chapter 193, Laws of 1945 and RCW 76.08.020;

.. Section 3, chapter 193, Laws of 1945, section 2, chapter 218, Laws of 1947, section 1, chapter 115, Laws of 1955 and RCW 76.08.030;

.. Section 4, chapter 193, Laws of 1945, section 3, chapter 218, Laws of 1947, section 2, chapter 79, Laws of 1957 and RCW 76.08.040;

.. Section 5, chapter 193, Laws of 1945, section 4, chapter 218, Laws of 1947, section 3, chapter 79, Laws of 1957, section 11, chapter 207, Laws of 1971 ex. sess. and RCW 76.08.050;

.. Section 6, chapter 193, Laws of 1945, section 5, chapter 218, Laws of 1947, section 2, chapter 44, Laws of 1953, section 12, chapter 207, Laws of 1971 ex. sess. and RCW 76.08.060;

.. Section 7, chapter 193, Laws of 1945 and RCW 76.08.070;

.. Section 8, chapter 193, Laws of 1945, section 6, chapter 218, Laws of 1947, section 3, chapter 44, Laws of 1953, section 2, chapter 115, Laws of 1955, section 1, chapter 40, Laws of 1961 and RCW 76.08.080; and

.. Section 9, chapter 193, Laws of 1945, section 4, chapter 44, Laws of 1953 and RCW 76.08.090.

. Notwithstanding the foregoing repealer, obligations under such sections or permits issued thereunder and in effect on January 1, 1975, shall continue in full force and effect, and no liability thereunder, civil or criminal, shall be in any way modified.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c137.pdf?cite=1974%20ex.s.%20c%20137%20§%2034[1974 ex.s. c 137 § 34]; ]

== 76.09.920 - Application for extension of prior permits.
Permits issued by the department under the provisions of RCW 76.08.030 during 1974 shall be effective until April 1, 1975 if an application has been submitted under the provisions of RCW 76.09.050 prior to January 1, 1975.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c137.pdf?cite=1974%20ex.s.%20c%20137%20§%2035[1974 ex.s. c 137 § 35]; ]

== 76.09.925 - Effective dates—1974 ex.s. c 137.
RCW 76.09.030, 76.09.040, 76.09.050, 76.09.060, 76.09.200, 90.48.420, and 76.09.935 are necessary for the immediate preservation of the public peace, health and safety, the support of the state government and its existing public institutions, and shall take effect immediately. RCW 76.09.010, 76.09.020, 76.09.070, 76.09.080, 76.09.090, 76.09.100, 76.09.110, 76.09.120, 76.09.130, 76.09.140, 76.09.150, 76.09.160, 76.09.170, 76.09.180, 76.09.190, * 76.09.210, * 76.09.220, * 76.09.230, 76.09.240, 76.09.250, 76.09.260, 76.09.270, 76.09.280, 76.09.900, 76.09.905, 76.09.910, 76.09.930, 76.09.915, and 76.09.920 shall take effect January 1, 1975.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c137.pdf?cite=1974%20ex.s.%20c%20137%20§%2037[1974 ex.s. c 137 § 37]; ]

== 76.09.935 - Severability—1974 ex.s. c 137.
If any provision of this 1974 act or its application to any person or circumstance is held invalid, the remainder of the act or the application of the provisions to other persons or circumstances shall not be affected.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c137.pdf?cite=1974%20ex.s.%20c%20137%20§%2036[1974 ex.s. c 137 § 36]; ]

