= 76.06 - Forest insect and disease control.
:toc:

== 76.06.010 - Forest insects and tree diseases are public nuisance.
The legislature finds and declares that:

. Forest insects and forest tree diseases which threaten the permanent timber production of the forested areas of the state of Washington are a public nuisance.

. Exotic forest insects or diseases, even in small numbers, can constitute serious threats to native forests. Native tree species may lack natural immunity. There are often no natural control agents such as diseases, predators, or parasites to limit populations of exotic forest insects or diseases. Exotic forest insects or diseases can also outcompete, displace, or destroy habitat of native species. It is in the public interest to identify, control, and eradicate outbreaks of exotic forest insects or diseases that threaten the diversity, abundance, and survivability of native forest trees and the environment.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5144-S.SL.pdf?cite=2003%20c%20314%20§%201[2003 c 314 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c233.pdf?cite=1951%20c%20233%20§%201[1951 c 233 § 1]; ]

== 76.06.020 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Agent" means the recognized legal representative, representatives, agent, or agents for any owner.

. "Commissioner" means the commissioner of public lands.

. "Department" means the department of natural resources.

. "Disturbance agent" means those forces that damage or kill significant numbers of forest trees, such as insects, diseases, windstorms, ice storms, and fires.

. "Exotic" means not native to forestlands in Washington state.

. "Forest health" means, for the purposes of this chapter, the condition of a forest being sound in ecological function, sustainable, resilient, and resistant to insects, diseases, fire, and other disturbance, and having the capacity to meet landowner objectives.

. "Forest health emergency" means the introduction of, or an outbreak of, an exotic forest insect or disease that poses an imminent danger of damage to the environment by threatening the survivability of native tree species.

. "Forest insect or disease" means a living stage of an insect, other invertebrate animal, or disease-causing organism or agent that can directly or indirectly injure or cause disease or damage in trees, or parts of trees, or in processed or manufactured wood, or other products of trees.

. "Forestland" means any land on which there are sufficient numbers and distribution of trees and associated species to, in the judgment of the department, contribute to the spread of forest insect or forest disease outbreaks that could be detrimental to forest health.

. "Integrated pest management" means a strategy that uses various combinations of pest control methods, including biological, cultural, and chemical methods, in a compatible manner to achieve satisfactory control and ensure favorable economic and environmental consequences.

. "Native" means having populated Washington's forested lands prior to European settlement.

. "Outbreak" means a rapidly expanding population of insects or diseases with potential to spread.

. "Owner" means and includes persons or their agents.

. "Person" means any individual, partnership, private, public, or municipal corporation, county, federal, state, or local governmental agency, tribes, or association of individuals of whatever nature.

. "Timberland" means any land on which there is a sufficient number of trees, standing or down, to constitute, in the judgment of the department, a forest insect or forest disease breeding ground of a nature to constitute a menace, injurious and dangerous to permanent forest growth in the district under consideration.

. "Uncharacteristic" means ecologically atypical for a forest or vegetation type or plant association and refers to fire, insect, or disease events that are not within a natural range of variability.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6141-S.SL.pdf?cite=2007%20c%20480%20§%202[2007 c 480 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5144-S.SL.pdf?cite=2003%20c%20314%20§%202[2003 c 314 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2399-S.SL.pdf?cite=2000%20c%2011%20§%202[2000 c 11 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c128.pdf?cite=1988%20c%20128%20§%2015[1988 c 128 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c233.pdf?cite=1951%20c%20233%20§%202[1951 c 233 § 2]; ]

== 76.06.030 - Administration—Comprehensive forest health program—Limited liability.
. This chapter shall be administered by the department.

. The department has the lead role in developing a comprehensive forest health program to achieve the goals of chapter 480, Laws of 2007. Within available funding, the department shall:

.. Develop, gather, and disseminate information on forest health conditions, monitor forest health conditions and changes over time, and coordinate and enter agreements with interested and affected parties;

.. Coordinate with universities, university extension services, federal and state agencies, private, public, and tribal forestland owners, consulting foresters, and forest managers to monitor forest fuel buildup, forest insect and disease outbreaks, and wind and ice storm events; and

.. Coordinate with universities, university extension services, and state and federal agencies to provide education and technical assistance to private, public, and tribal forestland owners on silvicultural and forest management science, techniques, and technology to maintain forests in conditions that are resilient and resistant to disturbance agents.

. The department may implement a technical committee to advise on subjects and procedures for monitoring forest health conditions and program activities.

. The department may coordinate, support, and assist in establishing cooperative forest health projects to address outbreaks of insects or diseases. Priority for assistance authorized under this section shall be given to areas under forest health hazard warnings and areas where forest health decline has resulted in increased risk to public safety from fire.

. The state and its officers and employees are not liable for damages to a person or their property to the extent that liability is asserted to arise from providing or failing to provide assistance under chapter 480, Laws of 2007.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6141-S.SL.pdf?cite=2007%20c%20480%20§%203[2007 c 480 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c128.pdf?cite=1988%20c%20128%20§%2016[1988 c 128 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c233.pdf?cite=1951%20c%20233%20§%203[1951 c 233 § 3]; ]

== 76.06.040 - Maintenance of forestlands in healthy condition.
Landowners and managers are encouraged to maintain their forestlands in a healthy condition in order to meet their individual ownership objectives, protect public resources as defined in chapter 76.09 RCW, and avoid contributing to forest insect or disease outbreaks or increasing the risk of uncharacteristic fire.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6141-S.SL.pdf?cite=2007%20c%20480%20§%204[2007 c 480 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c233.pdf?cite=1951%20c%20233%20§%204[1951 c 233 § 4]; ]

== 76.06.130 - Exotic forest insect or disease control—Department's authority and duties—Declaration of forest health emergency.
The department is authorized to contribute resources and expertise to assist the department of agriculture in control or eradication efforts authorized under chapter 17.24 RCW in order to protect forestlands of the state.

If either the department of agriculture has not taken action under chapter 17.24 RCW or the commissioner finds that additional efforts are required to control or prevent an outbreak of an exotic forest insect or disease which has not become so habituated that it can no longer be eradicated and that poses an imminent danger of damage to the forested environment by threatening the diversity, abundance, and survivability of native tree species, or both, the commissioner may declare a forest health emergency.

Upon declaration of a forest health emergency, the department must delineate the area at risk and determine the most appropriate integrated pest management methods to control the outbreak, in consultation with other interested agencies, affected tribes, and affected forestland owners. The department must notify affected forestland owners of its intent to conduct control operations.

Upon declaration of a forest health emergency by the commissioner, the department is authorized to enter into agreements with forestland owners, companies, individuals, tribal entities, and federal, state, and local agencies to accomplish control of exotic forest insects or diseases on any affected forestlands using such funds as have been, or may be, made available.

The department must proceed with the control of the exotic forest insects or diseases on affected nonfederal and nontribal forestlands with or without the cooperation of the owner. The department may reimburse cooperating forestland owners and agencies for actual cost of equipment, labor, and materials utilized in cooperative exotic forest insect or disease control projects, as agreed to by the department.

A forest health emergency no longer exists when the department finds that the exotic forest insect or disease has been controlled or eradicated, that the imminent threat no longer exists, or that there is no longer good likelihood of effective control.

Nothing under this chapter diminishes the authority and responsibility of the department of agriculture under chapter 17.24 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5144-S.SL.pdf?cite=2003%20c%20314%20§%203[2003 c 314 § 3]; ]

== 76.06.140 - Forest health problems—Findings.
The legislature finds as follows:

. Washington faces serious forest health problems, primarily in eastern Washington, where forests are overcrowded or trees lack sufficient resilience to insects, diseases, wind, ice storms, and fire. The causes of and contributions to these conditions include fire suppression, past timber harvesting and silvicultural practices, altered species composition and stand structure, and the amplified risks that occur when the urban interface penetrates forestland.

. There is a private and public interest in addressing uncharacteristic outbreaks of native, naturalized, and nonnative insects and diseases, and reducing the risk of significant loss due to ice storms, windstorms, and uncharacteristic fire. The public interest is in protecting forest productivity on forests managed for commodity production; restoring and maintaining forest ecosystem vitality and natural forest processes and functions; reducing the cost of fire suppression and the resulting public expenditures; protecting, restoring, and enhancing fish and wildlife habitat, including the habitat of threatened or endangered species; and protecting drinking water supplies and water quality.

. Well managed forests are the first line of defense in reducing the likelihood of uncharacteristic fire, insect, and disease events, and supporting conservation and restoration of desired plants and animals. Active management of forests, consistent with landowner objectives and the protection of public resources, is the most economical and effective way to promote forest health and protect communities. Fire, native insects, and diseases perform important ecological functions when their occurrence does not present a material threat to long-term forest productivity and increase the likelihood of uncharacteristic fire.

. Forest health problems may exist on forestland regardless of ownership, and the state should pursue collaboration with the federal government to address common health deficiencies.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6141-S.SL.pdf?cite=2007%20c%20480%20§%201[2007 c 480 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6144-S2.SL.pdf?cite=2004%20c%20218%20§%201[2004 c 218 § 1]; ]

== 76.06.150 - Forest health—Commissioner of public lands designated as state's lead—Report to legislature.
. The commissioner of public lands is designated as the state of Washington's lead for all forest health issues.

. The commissioner of public lands shall strive to promote communications between the state and the federal government regarding forestland management decisions that potentially affect the health of forests in Washington and will allow the state to have an influence on the management of federally owned land in Washington. Such government-to-government cooperation is vital if the condition of the state's public and private forestlands are to be protected. These activities may include, when deemed by the commissioner to be in the best interest of the state:

.. Representing the state's interest before all appropriate local, state, and federal agencies;

.. Assuming the lead state role for developing formal comments on federal forest management plans that may have an impact on the health of forests in Washington; 

.. Pursuing in an expedited manner any available and appropriate cooperative agreements, including cooperating agency status designation, with the United States forest service and the United States bureau of land management that allow for meaningful participation in any federal land management plans that could affect the department's strategic plan for healthy forests and effective fire prevention and suppression, including the pursuit of any options available for giving effect to the cooperative philosophy contained within the national environmental policy act of 1969 (42 U.S.C. Sec. 4331); and

.. Pursuing agreements with federal agencies in the service of forest biomass energy partnerships and cooperatives authorized under RCW 43.30.835 through 43.30.840.

. The commissioner of public lands shall report to the chairs of the appropriate standing committees of the legislature every year on progress under this section, including the identification, if deemed appropriate by the commissioner, of any needed statutory changes, policy issues, or funding needs.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2165.SL.pdf?cite=2009%20c%20163%20§%205[2009 c 163 § 5]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6144-S2.SL.pdf?cite=2004%20c%20218%20§%202[2004 c 218 § 2]; ]

== 76.06.160 - Forest health issues—Tiered system.
Forest health issues shall be addressed by a tiered system.

. The first tier is intended to maintain forest health and protect forests from disturbance agents through the voluntary efforts of landowners. Tier 1 is the desired status. Consistent with landowner objectives and the protection of public resources, forests should be managed in ways that create, restore, or maintain healthy forest ecosystems so that disturbance agents occur or exist at nonepidemic levels. To the extent of available funding, information and technical assistance will be made available to forestland owners so they can plan for and implement necessary forest health maintenance and restoration activities.

. The second tier is intended to manage the development of threats to forest health, or address existing threats to forest health, due to disturbance agents. Actions by landowners to address such threats to forest health are voluntary except as required under chapter 76.04 RCW to reduce the danger of the spread of fire. Actions suggested to reduce threats to forest health are specified in forest health hazard warnings issued by the commissioner of public lands under RCW 76.06.180. Within available funding, site-specific information, technical assistance, and project coordination services shall be offered as determined appropriate by the department.

. The third tier is intended to address significant threats to forest health due to disturbance agents that have spread to multiple forest ownerships or increased forest fuel that is likely to further the spread of fire. Actions required to reduce significant threats to forest health are specified in forest health hazard orders issued by the commissioner of public lands under RCW 76.06.180(5). Within available funding, site-specific information, technical assistance, and project coordination services shall be offered as determined appropriate by the department. Landowners who are provided notice of a forest health hazard order under RCW 76.06.180(5) and fail to take the action required under such order may be subject to increased liability for the spread of fire as described in RCW 76.04.495 and 76.04.660. However, a private landowner need not take actions required under the third tier, and may not be held liable for the failure to take such actions, where the disturbance agents on the private landowner's land spread from state or federal lands or where the presence of disturbance agents on state or federal lands would limit the effectiveness of actions required on the private landowner's land under the third tier.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6141-S.SL.pdf?cite=2007%20c%20480%20§%205[2007 c 480 § 5]; ]

== 76.06.170 - Forest health technical advisory committee.
. The commissioner of public lands may appoint a forest health technical advisory committee when the commissioner determines that forestlands in any area of the state appear to be threatened by a forest health condition of such a nature, extent, or timing that action to reduce the threat may be necessary.

.. The committee shall consist of one scientist chosen for expertise in forest ecology, one scientist chosen for expertise in aquatic ecology, one scientist chosen for expertise in wildlife biology, two scientists chosen for expertise relative to the attendant risk, one specialist in wildfire protection, one specialist in fuels management, one forester with extensive silvicultural experience in the affected forest type, and a chairperson who shall represent the commissioner. The departments of fish and wildlife, ecology, and natural resources shall provide technical assistance to the committee in the areas of fish and wildlife, water quality, and forest practices, but shall not be members of the committee. The director of forest health protection of region 6 of the United States department of agriculture forest service or their named designee shall be invited to be an ex officio member of the committee. In the event the area affected contains substantial acreage of tribal or federally owned lands, representatives of the affected agencies and tribes shall be invited to participate in the proceedings of the committee.

.. The commissioner may disband the committee when he or she deems appropriate.

. The committee shall evaluate the threat to forest health and make a timely report to the commissioner on its nature, extent, and location.

.. In its deliberations, the committee shall consider the need for action to reduce the threat and alternative methods of achieving the desired results, including the environmental risks associated with the alternatives and the risks associated with taking no action.

.. The committee shall also recommend potential approaches to achieve the desired results for forestland ownerships of fewer than ten acres and for forests owned for scientific, study, recreational, or other uses not compatible with active management.

.. The committee shall recommend to the commissioner whether a forest health hazard warning or forest health hazard order is warranted based on the factors in RCW 76.06.180(2) or when otherwise determined by the committee to be warranted.

.. When the commissioner issues a forest health hazard warning or forest health hazard order, the committee shall monitor the progress and results of activities to address the hazard, and periodically report its findings to the commissioner.

. The exercise by forest health technical advisory committee members of their authority under this section shall not imply or create any liability on their part. Advisory committee members shall be compensated as provided in RCW 43.03.250 and shall receive reimbursement for travel expenses as provided by RCW 43.03.050 and 43.03.060. Costs associated with the committee may be paid from the general fund appropriation made available to the department of natural resources for fire suppression.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6141-S.SL.pdf?cite=2007%20c%20480%20§%206[2007 c 480 § 6]; ]

== 76.06.180 - Forest health hazard warning—Forest health hazard order—Notice—Appeal.
. Prior to issuing a forest health hazard warning or forest health hazard order, the commissioner shall consider the findings and recommendations of the forest health technical advisory committee and shall consult with county government officials, forestland owners and forestland managers, consulting foresters, and other interested parties to gather information on the threat, opportunities or constraints on treatment options, and other information they may provide. The commissioner, or a designee, shall conduct a public hearing in a county within the geographical area being considered.

. The commissioner of public lands may issue a forest health hazard warning when he or she deems such action is necessary to manage the development of a threat to forest health or address an existing threat to forest health. A decision to issue a forest health hazard warning may be based on existing forest stand conditions and:

.. The presence of an uncharacteristic insect or disease outbreak that has or is likely to (i) spread to multiple forest ownerships and cause extensive damage to forests; or (ii) significantly increase forest fuel that is likely to further the spread of uncharacteristic fire;

.. When, due to extensive physical damage from wind or ice storm or other cause, there are (i) insect populations building up to large scale levels; or (ii) significantly increased forest fuels that are likely to further the spread of uncharacteristic fire; or

.. When otherwise determined by the commissioner to be appropriate.

. The commissioner of public lands may issue a forest health hazard order when he or she deems such action is necessary to address a significant threat to forest health. A decision to issue a forest health hazard order may be based on existing forest stand conditions and:

.. The presence of an uncharacteristic insect or disease outbreak that has (i) spread to multiple forest ownerships and has caused and is likely to continue to cause extensive damage to forests; or (ii) significantly increased forest fuels that are likely to further the spread of uncharacteristic fire;

.. When, due to extensive physical damage from wind or ice storm or other cause (i) insect populations are causing extensive damage to forests; or (ii) significantly increased forest fuels are likely to further the spread of uncharacteristic fire;

.. Insufficient landowner action under a forest health hazard warning; or

.. When otherwise determined by the commissioner to be appropriate.

. A forest health hazard warning or forest health hazard order shall be issued by use of a commissioner's order. General notice of the commissioner's order shall be published in a newspaper of general circulation in each county within the area covered by the order and on the department's web site. The order shall specify the boundaries of the area affected, including federal and tribal lands, the forest stand conditions that would make a parcel subject to the provisions of the order, and the actions landowners or land managers should take to reduce the hazard. If the forest health hazard warning or order relates to land managed by the department, the warning or order may also contain provisions for the department's utilization of any forest biomass pursuant to chapter 79.150 RCW.

. Written notice of a forest health hazard warning or forest health hazard order shall be provided to forestland owners of specifically affected property.

.. The notice shall set forth:

... The reasons for the action;

... The boundaries of the area affected, including federal and tribal lands;

... Suggested actions that should be taken by the forestland owner under a forest health hazard warning or the actions that must be taken by a forestland owner under a forest health hazard order;

... The time within which such actions should or must be taken;

.. How to obtain information or technical assistance on forest health conditions and treatment options;

.. The right to request mitigation under subsection (6) of this section and appeal under subsection (7) of this section;

.. These requirements are advisory only for federal and tribal lands.

.. The notice shall be served by personal service or by mail to the latest recorded real property owner, as shown by the records of the county recording officer as defined in RCW 65.08.060. Service by mail is effective on the date of mailing. Proof of service shall be by affidavit or declaration under penalty of perjury.

. Forestland owners who have been issued a forest health hazard order under subsection (5) of this section may apply to the department for the remission or mitigation of such order. The application shall be made to the department within fifteen days after notice of the order has been served. Upon receipt of the application, the department may remit or mitigate the order upon whatever terms the department in its discretion deems proper, provided the department deems the remission or mitigation to be in the best interests of carrying out the purposes of this chapter. The department may ascertain the facts regarding all such applications in such reasonable manner and under such rule as it deems proper.

. Forestland owners who have been issued a forest health hazard order under subsection (5) of this section may appeal the order to the pollution control hearings board.

The appeal shall be filed within thirty days after notice of the order has been served, unless application for mitigation has been made to the department. When such an application for mitigation is made, such appeal shall be filed within thirty days after notice of the disposition of the application for mitigation has been served as provided in RCW 43.21B.230.

. A forest health hazard order issued under subsection (5) of this section is effective thirty days after date of service unless application for remission or mitigation is made or an appeal is filed. When an application for remission or mitigation is made, the order is effective thirty days after notice setting forth the disposition of the application is served unless an appeal is filed from such disposition. Whenever an appeal of the order is filed, the order shall become effective only upon completion of all administrative and judicial review proceedings and the issuance of a final decision confirming the order in whole or in part.

. Upon written request, the department may certify as adequate a forest health management plan developed by a forestland owner, before or in response to a forest health hazard warning or forest health hazard order, if the plan is likely to achieve the desired result and the terms of the plan are being diligently followed by the forestland owner. The certification of adequacy shall be determined by the department in its sole discretion, and be provided to the requestor in writing.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2935-S.SL.pdf?cite=2010%20c%20210%20§%2018[2010 c 210 § 18]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2481-S2.SL.pdf?cite=2010%20c%20126%20§%208[2010 c 126 § 8]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6141-S.SL.pdf?cite=2007%20c%20480%20§%207[2007 c 480 § 7]; ]

== 76.06.190 - Chapter 480, Laws of 2007 subject to the provisions of chapter  76.09 RCW.
Nothing in chapter 480, Laws of 2007 shall exempt actions specified under the authority of chapter 480, Laws of 2007 from the application of the provisions of chapter 76.09 RCW and rules adopted thereunder which govern forest practices.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6141-S.SL.pdf?cite=2007%20c%20480%20§%209[2007 c 480 § 9]; ]

== 76.06.200 - Forest health assessment and treatment framework.
. The department must establish a forest health assessment and treatment framework designed to proactively and systematically address the forest health issues facing the state. Specifically, the framework must endeavor to achieve an initial goal of assessing and treating one million acres of land by 2033.

. The department must utilize the framework to assess and treat acreage in an incremental fashion each biennium. The framework consists of three elements: Assessment; treatment; and progress review and reporting.

.. Assessment. Each biennium, the department must identify and assess two hundred thousand acres of fire prone lands and communities that are in need of forest health treatment, including the use of prescribed fire or mechanical treatment, such as thinning.

... The scope of the assessment must include lands protected by the department as well as lands outside of the department's fire protection responsibilities that could pose a high risk to department protected lands during a fire.

... The assessment must identify areas in need of treatment, the type or types of treatment recommended, data and planning needs to carry out recommended treatment, and the estimated cost of recommended treatment.

.. Treatment. Each biennium, the department must review previously completed assessments and prioritize and conduct as many identified treatments as possible using appropriations provided for that specific purpose.

.. Progress review and reporting. By December 1st of each even-numbered year, the department must provide the appropriate committees of the legislature and the office of financial management with:

... A request for appropriations designed to implement the framework in the following biennium, including assessment work and conducting treatments identified in previously completed assessments;

... A prioritized list and brief summary of treatments planned to be conducted under the framework with the requested appropriations, including relevant information from the assessment; and

... A list and brief summary of treatments carried out under the framework in the preceding biennium, including total funding available, costs for completed treatment, and treatment outcomes. The summary must include any barriers to framework implementation and legislative or administrative recommendations to address those barriers.

. In developing and implementing the framework, the department must:

.. Utilize and build on the forest health strategic planning initiated under section 308(11), chapter 36, Laws of 2016 sp. sess., to the maximum extent practicable, to promote the efficient use of resources;

.. Prioritize, to the maximum extent practicable consistent with this section, forest health treatments that are strategically planned to serve the dual benefits of forest health maximization while providing geographically planned tools for wildfire response; and

.. Establish a forest health advisory committee to assist in developing and implementing the framework. The committee may: (i) Include representation from large and small forestland owners, wildland fire response organizations, milling and log transportation industries, forest collaboratives that may exist in the affected areas, highly affected communities and community preparedness organizations, conservation groups, and other interested parties deemed appropriate by the commissioner; and (ii) consult with relevant local, state, and federal agencies, and tribes.

. In implementing subsection (3)(b) of this section, the department shall attempt to locate and design forest health treatments in such a way as to provide wildfire response personnel with strategically located treated areas to assist with managing fire response. These areas must attempt to maximize the firefighting benefits of natural and artificial geographic features and be located in areas that prioritize the protection of commercially managed lands from fires originating on public land.

. The department must establish and implement the forest health assessment and treatment framework within the appropriations specifically provided for this purpose.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1784-S2.SL.pdf?cite=2019%20c%20305%20§%201[2019 c 305 § 1]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5546-S2.SL.pdf?cite=2017%20c%2095%20§%201[2017 c 95 § 1]; ]

== 76.06.900 - Severability.
If any part of this chapter or requirements imposed upon landowners pursuant to this chapter are found to conflict with requirements of other statutes or rules, the conflicting part of this chapter or requirements imposed pursuant to this chapter shall be inoperative solely to the extent of the conflict. The finding or determination shall not affect the operation of the remainder of this chapter or such requirements.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6141-S.SL.pdf?cite=2007%20c%20480%20§%2010[2007 c 480 § 10]; ]

