= 76.15 - Community and urban forestry.
:toc:

== 76.15.005 - Finding.
. Trees and other woody vegetation are a necessary and important part of community and urban environments. Community and urban forests have many values and uses including conserving energy, reducing air and water pollution and soil erosion, contributing to property values, attracting business, reducing glare and noise, providing aesthetic and historical values, providing wood products, and affording comfort and protection for humans and wildlife.

. As urban and community areas in Washington state grow, the need to plan for and protect community and urban forests increases. Cities and communities benefit from assistance in developing and maintaining community and urban forestry programs that also address future growth.

. Assistance and encouragement in establishment, retention, and enhancement of these forests and trees by local governments, citizens, organizations, and professionals are in the interest of the state based on the contributions these forests make in preserving and enhancing the quality of life of Washington's municipalities and counties while providing opportunities for economic development.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5264.SL.pdf?cite=1991%20c%20179%20§%201[1991 c 179 § 1]; ]

== 76.15.007 - Purpose.
The purpose of this chapter is to:

. Encourage planting and maintenance and management of trees in the state's municipalities and counties and maximize the potential of tree and vegetative cover in improving the quality of the environment.

. Encourage the coordination of state and local agency activities and maximize citizen participation in the development and implementation of community and urban forestry-related programs.

. Foster healthy economic activity for the state's community and urban forestry-related businesses through cooperative and supportive contracts with the private business sector.

. Facilitate the creation of employment opportunities related to community and urban forestry activities including opportunities for inner city youth to learn teamwork, resource conservation, environmental appreciation, and job skills.

. Provide meaningful voluntary opportunities for the state's citizens and organizations interested in community and urban forestry activities.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5264.SL.pdf?cite=1991%20c%20179%20§%202[1991 c 179 § 2]; ]

== 76.15.010 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Community and urban forest" is that land in and around human settlements ranging from small communities to metropolitan areas, occupied or potentially occupied by trees and associated vegetation. Community and urban forestland may be planted or unplanted, used or unused, and includes public and private lands, lands along transportation and utility corridors, and forested watershed lands within populated areas.

. "Community and urban forest assessment" has the same meaning as defined in RCW 35.105.010.

. "Community and urban forest inventory" has the same meaning as defined in RCW 35.105.010.

. "Community and urban forestry" means the planning, establishment, protection, care, and management of trees and associated plants individually, in small groups, or under forest conditions within municipalities and counties.

. "Department" means the department of natural resources.

. "Municipality" means a city, town, port district, public school district, community college district, irrigation district, weed control district, park district, or other political subdivision of the state.

. "Person" means an individual, partnership, private or public municipal corporation, Indian tribe, state entity, county or local governmental entity, or association of individuals of whatever nature.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2844-S2.SL.pdf?cite=2008%20c%20299%20§%2023[2008 c 299 § 23]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2399-S.SL.pdf?cite=2000%20c%2011%20§%2015[2000 c 11 § 15]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5264.SL.pdf?cite=1991%20c%20179%20§%203[1991 c 179 § 3]; ]

== 76.15.020 - Authority.
. The department may establish and maintain a program in community and urban forestry to accomplish the purpose stated in RCW 76.15.007. The department may assist municipalities and counties in establishing and maintaining community and urban forestry programs and encourage persons to engage in appropriate and improved tree management and care.

. The department may advise, encourage, and assist municipalities, counties, and other public and private entities in the development and coordination of policies, programs, and activities for the promotion of community and urban forestry.

. The department may appoint a committee or council, in addition to the technical advisory committee created in RCW 76.15.080 to advise the department in establishing and carrying out a program in community and urban forestry.

. The department may assist municipal and county tree maintenance programs by making surplus equipment available on loan where feasible for community and urban forestry programs and cooperative projects.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2844-S2.SL.pdf?cite=2008%20c%20299%20§%203[2008 c 299 § 3]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5264.SL.pdf?cite=1991%20c%20179%20§%204[1991 c 179 § 4]; ]

== 76.15.030 - Funding sources—Fees—Contracts.
The department may:

. Receive and disburse any and all moneys contributed, allotted, or paid by the United States under authority of any act of congress for the purposes of this chapter.

. Receive such gifts, grants, bequests, and endowments and donations of labor, material, seedlings, and equipment from public or private sources as may be made for the purpose of carrying out the provisions of this chapter, and may spend the gifts, grants, bequests, endowments, and donations as well as other moneys from public or private sources.

. Charge fees for attendance at workshops and conferences, and for various publications and other materials that the department may prepare.

. Enter into agreements and contracts with persons having community and urban forestry-related responsibilities.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5264.SL.pdf?cite=1991%20c%20179%20§%205[1991 c 179 § 5]; ]

== 76.15.040 - Primary duty, department's—Cooperation.
The department shall assume the primary responsibility of carrying out this chapter and shall cooperate with other private and public, state and federal persons, any agency of another state, the United States, any agency of the United States, or any agency or province of Canada.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5264.SL.pdf?cite=1991%20c%20179%20§%206[1991 c 179 § 6]; ]

== 76.15.050 - Agreements for urban tree planting.
The department may enter into agreements with one or more nonprofit organizations whose primary purpose is urban tree planting. The agreements shall be to further public education about and support for urban tree planting, and for obtaining voluntary activities by the local community organizations in tree planting programs. The agreements shall ensure that such programs are consistent with the purposes of the community and urban forestry program under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5159-S.SL.pdf?cite=1993%20c%20204%20§%2010[1993 c 204 § 10]; ]

== 76.15.060 - Urban tree planting to be encouraged.
The department shall encourage urban planting of tree varieties that are site-appropriate and provide the best combination of energy and water conservation, fire safety and other safety, wildlife habitat, and aesthetic value. The department may provide technical assistance in developing programs in tree planting for energy conservation in areas of the state where such programs are most cost-effective.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5159-S.SL.pdf?cite=1993%20c%20204%20§%2011[1993 c 204 § 11]; ]

== 76.15.070 - Prioritized statewide inventory of community and urban forests—Community and urban forest assessment—Criteria and implementation plan.
. [Empty]
.. The department may, in collaboration with educational institutions, municipalities, corporations, the technical advisory committee created in RCW 76.15.080, state and national service organizations, and environmental organizations, conduct a prioritized statewide inventory of community and urban forests.

.. For purposes of efficiency, existing data and current inventory technologies must be utilized in the development of the inventory. Statewide data must be maintained and periodically updated by the department and made available to every municipality in the state.

.. The criteria established for the statewide community and urban forest inventory must support the planning needs of local governments.

.. The criteria for the statewide community and urban forest inventory may include but not be limited to: Tree size, species, location, site appropriateness, condition and health, contribution to canopy cover and volume, available planting spaces, and ecosystem, economic, social, and monetary value.

.. In developing the statewide community and urban forest inventory, the department shall strive to enable Washington cities' urban forest managers to access carbon markets by working to ensure the inventory developed under this section is compatible with existing and developing urban forest reporting protocols designed to facilitate access to those carbon markets.

. The department may, in collaboration with a statewide organization representing urban and community forestry programs, and with the evergreen communities partnership task force established in RCW 35.105.110, conduct a community and urban forest assessment and develop recommendations to the appropriate committees of the legislature to improve community and urban forestry in Washington.

. The inventory and assessment in this section must be capable of supporting the adoption and implementation of evergreen community management plans and ordinances described in RCW 35.105.050.

. The department may, in collaboration with municipalities, the technical advisory committee created in RCW 76.15.080, and a statewide organization representing urban and community forestry programs, develop an implementation plan for the inventory and assessment of the community and urban forests in Washington.

. [Empty]
.. The criteria and implementation plan for the statewide community and urban forest inventory and assessment required under this section must be completed by December 1, 2008. Upon the completion of the criteria and implementation plan's development, the department shall report the final product to the appropriate committees of the legislature.

.. An initial inventory and assessment, consisting of the community and urban forests of the willing municipalities located in one county located east of the crest of the Cascade mountains and the willing municipalities located in one county located west of the crest of the Cascade mountains must be completed by June 1, 2010.

. The requirements of this section are subject to the availability of amounts appropriated for the specific purposes of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2844-S2.SL.pdf?cite=2008%20c%20299%20§%204[2008 c 299 § 4]; ]

== 76.15.080 - Technical advisory committee.
. The commissioner of public lands shall appoint a technical advisory committee to provide advice to the department during the development of the criteria and implementation plan for the statewide community and urban forest inventory and assessment required under RCW 76.15.070.

. The technical advisory committee must include, but not be limited to, representatives from the following groups: Arborists; municipal foresters; educators; consultants; researchers; public works and utilities professionals; information technology specialists; and other affiliated professionals.

. The technical advisory committee members shall serve without compensation. Advisory committee members who are not state employees may receive reimbursement for travel expenses as provided by RCW 43.03.050 and 43.03.060. Costs associated with the technical advisory committee may be paid from the general fund appropriation made available to the department for community and urban forestry.

. The technical advisory committee created in this section must be disbanded by the commissioner upon the completion of the criteria and implementation plan for the statewide community and urban forest inventory and assessment required under RCW 76.15.070.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2844-S2.SL.pdf?cite=2008%20c%20299%20§%205[2008 c 299 § 5]; ]

== 76.15.090 - Evergreen community designation—Department's duties.
The department shall manage the application and evaluation of candidates for evergreen community designation under RCW 35.105.030, and forward its recommendations to the *department of community, trade, and economic development.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2844-S2.SL.pdf?cite=2008%20c%20299%20§%208[2008 c 299 § 8]; ]

