= 76.48 - Specialized forest products.
:toc:

== 76.48.011 - Declaration of public interest.
. It is in the public interest of this state to protect an important natural resource and to provide protection to the landowners of the state of Washington from the theft of specialized forest products.

. To satisfy this public interest, this chapter is intended to:

.. Provide law enforcement with reasonable tools;

.. Reasonably protect landowners from theft;

.. Ensure that requirements are not unduly burdensome to those harvesting, transporting, possessing, and purchasing specialized forest products;

.. Craft requirements that are clear and readily understandable; and

.. Establish requirements that are able to be administered and enforced consistently statewide.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1038-S.SL.pdf?cite=2009%20c%20245%20§%202[2009 c 245 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c47.pdf?cite=1967%20ex.s.%20c%2047%20§%202[1967 ex.s. c 47 § 2]; ]

== 76.48.021 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Artistic cedar product" means a product made from the wood of a cedar tree, including western red cedar, that is not included in the definition of "cedar products" and has been carved, turned, or otherwise manipulated to more than an insignificant degree with the objective intent to be an artistic expression and that would be or is recognized by the applicable local market as having an economic value greater than the value of the raw materials used. Examples of artistic cedar products include, but are not limited to:

.. Chainsaw carvings;

.. Hand carvings;

.. Decorative bowls and boxes.

. "Authorization" means a properly completed preprinted form authorizing the transportation or possession of Christmas trees prepared consistent with RCW 76.48.041.

. "Bill of lading" means a written or printed itemized list or statement of particulars pertinent to the transportation or possession of a specialized forest product prepared consistent with RCW 76.48.041.

. "Cascara bark" means the bark of a Cascara tree.

. [Empty]
.. "Cedar products" means the following if made from the wood of a cedar tree, including western red cedar:

... Shake and shingle bolts;

... Fence posts and fence rails;

... Logs not covered by a valid approved forest practices application or notification under chapter 76.09 RCW; and

... Other pieces measuring fifteen inches or longer.

.. "Cedar products" does not include those materials identified in the definition of "processed cedar products" or "artistic cedar products."

. "Christmas trees" means any evergreen trees including fir, pine, spruce, cedar, and other coniferous species commonly known as Christmas trees. The definition of Christmas trees includes trees with or without the roots intact and the tops of the trees. The definition of Christmas trees does not include trees without limbs or branches.

. "Cut or picked evergreen foliage" means evergreen boughs, huckleberry foliage, salal, fern, Oregon grape, rhododendron, mosses, bear grass, and other cut or picked evergreen products. "Cut or picked evergreen foliage" does not include cones, berries, any foliage that does not remain green year-round, seeds, or any plant listed on the state noxious weed list under RCW 17.10.080.

. "Department" means the department of natural resources.

. "First specialized forest products buyer" means the first person that receives any specialized forest products after they leave the harvest site.

. "Harvest" means to separate, by cutting, prying, picking, peeling, breaking, pulling, splitting, or otherwise removing, a specialized forest product. "Harvest" includes both removing a specialized forest product from its original physical connection with the land and collecting a specialized forest product that has been previously separated from the land.

. "Harvest site" means each location where one or more persons are engaged in harvesting specialized forest products close enough to each other that communication can be conducted with an investigating law enforcement officer in a normal conversational tone.

. "Huckleberry" means the following species of edible berries, if they are not nursery grown: Big huckleberry (Vaccinium membranaceum), Cascade blueberry (Vaccinium deliciosum), evergreen huckleberry (Vaccinium ovatum), red huckleberry (Vaccinium parvifolium), globe huckleberry (Vaccinium globulare), oval-leaf huckleberry (Vaccinium ovalifolium), Alaska huckleberry (Vaccinium alaskaense), dwarf huckleberry (Vaccinium caespitosum), western huckleberry (Vaccinium occidentale), bog blueberry (Vaccinium uliginosum), dwarf bilberry (Vaccinium myrtillus), and grouse whortleberry (Vaccinium scoparium).

. "Landowner" means, with regard to real property, the private owner, the state of Washington or any political subdivision, the federal government, or a person who by deed, contract, or lease has authority to harvest and sell the specialized forest products of the property. "Landowner" does not include the purchaser or successful high bidder at a public or private timber sale.

. "Native ornamental trees and shrubs" means any trees or shrubs which are not nursery grown and which have been removed from the ground with the roots intact.

. "Permittee" means a person who is authorized by a permit issued consistent with this chapter to harvest, possess, and transport specialized forest products or to sell huckleberries.

. "Permittor" means the landowner of the land from where specialized forest products were, or are planned to be, harvested under a permit issued consistent with this chapter.

. "Person" includes the plural and all corporations, foreign or domestic, copartnerships, firms, and associations of persons.

. "Processed cedar products" means products made from the wood of a cedar tree, including western red cedar, that have undergone more than an insignificant degree of value-added processing and are not included in the definition of "cedar products." Examples of processed cedar products include, but are not limited to:

.. Shakes;

.. Shingles;

.. Hop poles;

.. Pickets; and

.. Stakes.

. "Sales invoice" means a written or printed itemized list or statement of particulars pertinent to the transportation or possession of a specialized forest product prepared consistent with RCW 76.48.041.

. "Secondary specialized forest products buyer" means any person who receives any specialized forest products after the transaction with the first specialized forest products buyer.

. "Specialized forest products" means the following:

.. Specialty wood;

.. More than five Christmas trees;

.. More than five native ornamental trees and shrubs;

.. More than twenty pounds of cut or picked evergreen foliage;

.. More than five pounds of Cascara bark; and

.. More than five United States gallons of wild edible mushrooms.

. "Specialized forest products permit" or "permit" means a printed document and all attachments completed in compliance with the requirements of this chapter and includes both validated permits and verifiable permits.

. "Specialty wood" means:

.. A cedar product; or

.. Englemann spruce, Sitka spruce, big leaf maple, or western red alder that:

... Is in logs, chunks, slabs, stumps, or burls; 

... Is capable of being cut into a segment that is without knots in a portion of the surface area at least nineteen inches long and seven and a [one-] quarter inches wide when measured from the outer surface toward the center; 

... Measures:

(A) Nineteen inches or longer;

(B) Greater than one and three-quarter inches thick; and

(C) Seven and one-quarter inches or greater in width; and

... Is being harvested or transported from areas not associated with the concurrent logging of timber stands:

(A) Under a forest practices application approval or notification received by the department under chapter 76.09 RCW; or

(B) Under a contract or permit issued by an agency of the United States government.

. "Specialty wood processor" means any person who purchases, takes, or retains possession of specialty wood for later sale in the same or modified form following removal and delivery from the land where harvested.

. "Transportation" means the physical conveyance of specialized forest products outside or off of a harvest site by any means.

. "True copy" means a replica of a specialized forest products permit reproduced as provided in RCW 76.48.051.

. "Validated permit" means a permit that is validated as required under this chapter prior to the harvest, transportation, or possession of specialized forest products.

. "Verifiable permit" means a permit that contains the required information allowing a law enforcement officer to verify the validity of the information contained on the permit but that does not require validation prior to the harvest, transportation, or possession of specialized forest products.

. "Wild edible mushrooms" means edible mushrooms not cultivated or propagated by domestic means.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1038-S.SL.pdf?cite=2009%20c%20245%20§%203[2009 c 245 § 3]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2779-S.SL.pdf?cite=2008%20c%20191%20§%209[2008 c 191 § 9]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1909-S.SL.pdf?cite=2007%20c%20392%20§%203[2007 c 392 § 3]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1406-S.SL.pdf?cite=2005%20c%20401%20§%201[2005 c 401 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2399-S.SL.pdf?cite=2000%20c%2011%20§%2018[2000 c 11 § 18]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5011.SL.pdf?cite=1995%20c%20366%20§%201[1995 c 366 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2865-S.SL.pdf?cite=1992%20c%20184%20§%201[1992 c 184 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c94.pdf?cite=1979%20ex.s.%20c%2094%20§%201[1979 ex.s. c 94 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c147.pdf?cite=1977%20ex.s.%20c%20147%20§%201[1977 ex.s. c 147 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c47.pdf?cite=1967%20ex.s.%20c%2047%20§%203[1967 ex.s. c 47 § 3]; ]

== 76.48.031 - Specialized forest products permits—Required—Inspection.
. Except as provided in RCW 76.48.211, a completed specialized forest products permit issued under this chapter is required prior to engaging in the following activities:

.. Harvesting any specialized forest products from any lands, including his or her own land.

.. Possessing or transporting any specialized forest products, unless the person has in his or her possession either of the following in lieu of a permit:

... A true copy of the permit;

... If the person is transporting the specialized forest product from a location other than the harvest site or is a first or secondary specialized forest products buyer, a sales invoice, bill of lading, or, for the possession and transportation of Christmas trees only, an authorization if a copy of the authorization has been filed prior to the harvest of the Christmas trees with the sheriff's office for the county in which the Christmas trees are to be harvested;

... A bill of lading or documentation issued in or by another state, a Canadian province, or the federal government indicating the true origin of the specialized forest products as being outside of Washington; or

... If the products were harvested within the operational area defined by a valid forest practices application or notification under chapter 76.09 RCW, a sequentially numbered load ticket generated by the landowner or the landowner's agent that includes, at a minimum, all information required on a bill of lading and the forest practices application number.

.. Selling, or offering for sale, any amount of raw or unprocessed huckleberries, regardless if the huckleberries were harvested with the consent of the landowner, unless the possessor of the huckleberries being offered for sale is able to show that the huckleberries originated on land owned by the United States forest service and displays a valid permit from the United States forest service that lawfully entitles the possessor to harvest the huckleberries in question.

. [Empty]
.. Unless otherwise designated by the permittor as provided in this subsection, a permit or true copy must be readily available for inspection at each harvest site.

.. An individual permit or true copy must be carried and made readily available for inspection by each individual permittee at a harvest site if the permittor designated an individual permit or true copy as an additional condition or limitation specified on the permit under RCW 76.48.081.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1038-S.SL.pdf?cite=2009%20c%20245%20§%204[2009 c 245 § 4]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2779-S.SL.pdf?cite=2008%20c%20191%20§%203[2008 c 191 § 3]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1406-S.SL.pdf?cite=2005%20c%20401%20§%203[2005 c 401 § 3]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5011.SL.pdf?cite=1995%20c%20366%20§%205[1995 c 366 § 5]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2865-S.SL.pdf?cite=1992%20c%20184%20§%202[1992 c 184 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c94.pdf?cite=1979%20ex.s.%20c%2094%20§%205[1979 ex.s. c 94 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c147.pdf?cite=1977%20ex.s.%20c%20147%20§%205[1977 ex.s. c 147 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c47.pdf?cite=1967%20ex.s.%20c%2047%20§%207[1967 ex.s. c 47 § 7]; ]

== 76.48.041 - Contents of authorization, sales invoice, or bill of lading.
An authorization, sales invoice, or bill of lading must specify the following in order to satisfy the requirements of this chapter:

. The date of the product's transportation.

. The amount and type of specialized forest products being transported.

. The name and address of the person receiving the specialized forest products.

. The name and address of the first or secondary specialized forest products buyer, specialty wood processor, or other person from where the specialized forest products are being transported.

. The name of the driver transporting the specialized forest products.

. The license plate number of the vehicle transporting the specialized forest product.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1038-S.SL.pdf?cite=2009%20c%20245%20§%205[2009 c 245 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c94.pdf?cite=1979%20ex.s.%20c%2094%20§%207[1979 ex.s. c 94 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c47.pdf?cite=1967%20ex.s.%20c%2047%20§%209[1967 ex.s. c 47 § 9]; ]

== 76.48.051 - Specialized forest products permit—True copy.
. A true copy of a specialized forest products permit is valid if:

.. The copy is reproduced by a copy machine capable of effectively reproducing the permit information required under RCW 76.48.081; and

.. [Empty]
... The permittee has provided an original signature in the space provided on the face of the copy.

... An actual signature of the permittor is also required for a true copy to be valid if the permittor indicates on the space provided for signatures on the original permit that the actual signature of the permittor is required for the validation of any copies.

. A true copy is effective until the expiration date of the underlying permit unless an earlier date is provided by the signatories to the copy.

. Either signatory to a permit may condition the use of the true copy for only harvesting, only possessing, only transporting, or a combination of harvesting, possessing, and transporting the associated specialized forest products by indicating the limitations of the true copy on the permit or the copy.

. Any permittee issuing a true copy must record and retain for one year the following information:

.. The date the true copy is issued;

.. The license plate number and make and model of the vehicle to be used with the true copy;

.. The name and address of the person receiving the true copy;

.. The unique number assigned to a valid state identification document issued to the person; and

.. The expiration date of the true copy.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1038-S.SL.pdf?cite=2009%20c%20245%20§%206[2009 c 245 § 6]; ]

== 76.48.061 - Permit requirements.
. [Empty]
.. Except for the sale of huckleberries, the permit requirements of RCW 76.48.031 may be satisfied with either a validated permit or a verifiable permit. The decision to use a validated or verifiable permit must be made and agreed upon jointly by the permittee and the permittor.

.. For the sale of huckleberries, only a validated permit satisfies the requirements of RCW 76.48.031.

. [Empty]
.. Forms for both validated permits and verifiable permits must be provided by the department and be made available in reasonable quantities through county sheriff offices and other locations deemed appropriate by the department.

.. In designing the forms, the department shall ensure that:

... All mandatory requirements of this chapter are satisfied;

... The type of permit is clearly marked on the form;

... Each permit is separately numbered and the issuance of the permits are by unique numbers; and

... The form is designed in a manner allowing a permittor to require his or her signature on all true copies as provided in RCW 76.48.051.

. Permit forms must be completed in triplicate for each property and in each county in which specialized forest products are proposed to be harvested or huckleberries sold.

. [Empty]
.. Within five business days after the signature of the permittor on the form for a verifiable permit, as required in RCW 76.48.081, the original permit form must be provided by the permittee to the sheriff of the county in which the specialized forest products are to be harvested. The permittee may provide the permit form in a manner convenient to the permittee and the sheriff's office, including in-person presentation or by mail. If mailed, the permit form must be postmarked within the time window established under this subsection.

.. Upon full completion, as provided in RCW 76.48.081, the permit form for a validated permit must, except for permits to sell huckleberries, be mailed or presented for validation to the sheriff of the county in which the specialized forest products are to be harvested. Validated permits relating to the sale of huckleberries may be validated by the sheriff of any county in the state.

. Two copies of the permit must be retained by the permittee, of which one copy must be given or mailed to the permittor by the permittee. The original permit must be retained in the office of the county sheriff for the purposes of verifying the permit, if necessary.

. All permits expire no later than the end of the calendar year in which they are issued.

. Permits provided under this section are subject to any other conditions or limitations that the permittor may specify.

. Before a permit form is accepted or validated by a sheriff, sufficient personal identification may be required to reasonably identify the person mailing or presenting the permit form. The sheriff may conduct other investigations as deemed necessary to determine the validity of the information alleged on the form.

. In the event a single land ownership is situated in two or more counties, a permit form must be completed, as provided in this section, for the portions of the ownership situated in each county.

. Permits that are validated by or provided to a sheriff's office under this section must be maintained by that office for a length of time determined by the appropriate records retention schedule.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1038-S.SL.pdf?cite=2009%20c%20245%20§%207[2009 c 245 § 7]; ]

== 76.48.071 - Validation of forms for verifiable permits and validated permits.
. Forms for a verifiable permit become valid for the purposes of RCW 76.48.031 upon the completion of all information required by RCW 76.48.081.

. Forms for a validated permit become valid for the purposes of RCW 76.48.031 upon the validation of the form by the appropriate county sheriff.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1038-S.SL.pdf?cite=2009%20c%20245%20§%208[2009 c 245 § 8]; ]

== 76.48.081 - Specialized forest products permits—Expiration—Specifications.
. A specialized forest products permit form may not be validated or accepted for verification by a sheriff unless the permit satisfies the requirements of this section.

. A properly completed permit form shall include:

.. The date of its execution and expiration;

.. The name, address, up to three telephone numbers, and signature of the permittee and permittor;

.. The type of specialized forest products to be harvested or transported;

.. The approximate amount or volume of specialized forest products to be harvested or transported;

.. [Empty]
... For validated permits only, the parcel number or the legal description of the property from which the specialized forest products are to be harvested or transported;

... For verifiable permits only:

(A) The parcel number for where the harvesting is to occur, unless the owner of the parcel actually lives at the parcel and the parcel's boundaries comprise an area one acre in size or smaller;

(B) The address of the property where the harvesting is to occur if the owner of the property lives at the parcel and the parcel's boundaries comprise an area less than one acre;

(C) The name of the county where the harvesting is to occur; and

(D) An accurate report or statement from the county assessor of the county where the specialized forest products are to be harvested that provides clear evidence that the permittor named on the verifiable permit is the owner of the parcel named on the permit;

.. A description by local landmarks of where the harvesting is to occur, or from where the specialized forest products are to be transported;

.. For specialty wood, a copy of a map or aerial photograph, with defined permitted boundaries, included as an attachment to the permit;

.. [Empty]
.. For validated permits, a copy of a valid picture identification of the permittee on the copy of the permit form that is presented to the sheriff; and

... For verifiable permits, the unique number assigned to a valid state identification document for both the permittee and permittor; and

... The details of any other condition or limitation which the permittor may specify.

. For permits intended to satisfy the requirements of RCW 76.48.031 relating to the sale of huckleberries, the permit:

.. Must, in addition to the requirements of subsection (2) of this section, also contain information relating to where the huckleberries were, or plan to be, harvested, and the approximate amount of huckleberries that are going to be offered for sale; and

.. Must include a statement designed to inform the possessor that permission from the landowner is still required prior to the harvesting of huckleberries.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1038-S.SL.pdf?cite=2009%20c%20245%20§%209[2009 c 245 § 9]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2779-S.SL.pdf?cite=2008%20c%20191%20§%202[2008 c 191 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1406-S.SL.pdf?cite=2005%20c%20401%20§%202[2005 c 401 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5011.SL.pdf?cite=1995%20c%20366%20§%204[1995 c 366 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c94.pdf?cite=1979%20ex.s.%20c%2094%20§%204[1979 ex.s. c 94 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c147.pdf?cite=1977%20ex.s.%20c%20147%20§%204[1977 ex.s. c 147 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c47.pdf?cite=1967%20ex.s.%20c%2047%20§%206[1967 ex.s. c 47 § 6]; ]

== 76.48.091 - Acceptance and validation of permits—Authorized agents.
. County sheriffs may contract with other entities to serve as authorized agents to accept and validate permits under RCW 76.48.061. Entities that a county sheriff may contract with include the department, the United States forest service, the bureau of land management, local police departments, and other entities as decided upon by the county sheriffs' departments.

. An entity that contracts with a county sheriff to serve as an authorized agent under this section may make reasonable efforts to verify the information provided on the permit form such as the legal description or parcel number of the area where harvesting is to occur.

. All processes and requirements applicable to county sheriffs under RCW 76.48.061 also apply to entities contracted under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1038-S.SL.pdf?cite=2009%20c%20245%20§%2010[2009 c 245 § 10]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5011.SL.pdf?cite=1995%20c%20366%20§%2015[1995 c 366 § 15]; ]

== 76.48.101 - Possession of specialized forest products by first or secondary buyer—Display of documentation—Specialty wood processors.
. It is unlawful for any first or secondary specialized forest products buyer, or for any other person, to purchase, take possession of, or retain specialized forest products subsequent to the harvesting and prior to the retail sale of the products unless the supplier of the product displays:

.. An apparently valid permit required by RCW 76.48.031;

.. A true copy of an apparently valid permit; or

.. When applicable:

... A bill of lading, authorization, sales invoice, or a government-issued documentation, prepared consistent with RCW 76.48.031 indicating the true origin of the specialized forest products as being outside of Washington;

... If the products were harvested within the operational area defined by a valid forest practices application or notification under chapter 76.09 RCW, a sequentially numbered load ticket generated by the landowner or the landowner's agent that includes, at a minimum, all information required on a bill of lading and the forest practices application number; or

... A statement claiming the products offered for sale are otherwise exempt from the permit requirements of this chapter under RCW 76.48.211.

. In addition to the requirements of RCW 76.48.111, specialty wood processors are required to ensure that a bill of lading, authorization, or sales invoice accompanies all specialty wood upon the receipt of the specialty wood into or the shipping of the specialty wood out of the property of the specialty wood processor.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1038-S.SL.pdf?cite=2009%20c%20245%20§%2011[2009 c 245 § 11]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1406-S.SL.pdf?cite=2005%20c%20401%20§%207[2005 c 401 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c94.pdf?cite=1979%20ex.s.%20c%2094%20§%209[1979 ex.s. c 94 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c147.pdf?cite=1977%20ex.s.%20c%20147%20§%2011[1977 ex.s. c 147 § 11]; ]

== 76.48.111 - Specialized forest products buyers and huckleberry buyers—Required records.
. [Empty]
.. First and secondary specialized forest products buyers and huckleberry buyers are required to record:

... If the person is a first specialized forest product buyer, the permit number or, if applicable, a sequentially numbered load ticket generated by the landowner or the landowner's agent that includes, at a minimum, all information required on a bill of lading and the forest practices application or notification number if the seller claims the specialized forest product in question is exempt from the permit requirements of this chapter, as provided in RCW 76.48.211, due to its harvest within the operational area defined by a valid forest practices application or notification under chapter 76.09 RCW;

... Whether or not the products were accompanied by a bill of lading, authorization, or sales invoice;

... The type of specialized forest product purchased, and, if applicable, an indication that huckleberries were purchased;

... The name of the seller;

.. The amount of specialized forest product or huckleberries purchased;

.. The date of delivery;

.. The name of the person driving the vehicle in which the specialized forest products were transported to the buyer, as confirmed by a visual inspection of the applicable driver's license, unless the buyer has previously recorded the driver's information in an accessible record; and

.. Except for transactions involving Christmas trees, the license plate number of the vehicle in which the specialized forest products were transported to the buyer.

.. First and secondary specialized forest products buyers shall keep a record of this information, along with any accompanying bill of lading, sales invoice, or authorization, for a period of one year from the date of purchase and must make the records available for inspection upon demand by enforcement officials authorized under RCW 76.48.181 to enforce this chapter.

.. In lieu of a permit number or forest practices identification and load ticket number, the buyer may, when applicable, note that the seller claims that the products offered for sale are exempt from the permit requirements of this chapter under RCW 76.48.211, or were lawfully transported into Washington from out of state. All other information required by this section must be recorded.

. This section does not apply to buyers of specialized forest products at the retail sales level.

. Records of buyers of specialized forest products and huckleberries collected under this section may be made available to colleges and universities for the purpose of research.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1038-S.SL.pdf?cite=2009%20c%20245%20§%2012[2009 c 245 § 12]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2779-S.SL.pdf?cite=2008%20c%20191%20§%204[2008 c 191 § 4]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1406-S.SL.pdf?cite=2005%20c%20401%20§%206[2005 c 401 § 6]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2399-S.SL.pdf?cite=2000%20c%2011%20§%2019[2000 c 11 § 19]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5011.SL.pdf?cite=1995%20c%20366%20§%2014[1995 c 366 § 14]; ]

== 76.48.121 - Display of business license.
Every first or secondary specialized forest products buyer purchasing specialty wood and every specialty wood processor must prominently display the business license issued under RCW 19.02.070 and endorsed with the respective licenses or registrations or a copy of the business license at each location where the buyer or processor receives specialty wood if the first or secondary specialized forest products buyer or specialty wood processor is required to possess a license incorporated into the business licensing system created in chapter 19.02 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1568-S.SL.pdf?cite=2013%20c%20144%20§%2049[2013 c 144 § 49]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2017-S.SL.pdf?cite=2011%20c%20298%20§%2034[2011 c 298 § 34]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1038-S.SL.pdf?cite=2009%20c%20245%20§%2013[2009 c 245 § 13]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1406-S.SL.pdf?cite=2005%20c%20401%20§%209[2005 c 401 § 9]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5011.SL.pdf?cite=1995%20c%20366%20§%209[1995 c 366 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c94.pdf?cite=1979%20ex.s.%20c%2094%20§%2011[1979 ex.s. c 94 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c147.pdf?cite=1977%20ex.s.%20c%20147%20§%2013[1977 ex.s. c 147 § 13]; ]

== 76.48.131 - Unlawful acts.
It is unlawful for any person to:

. Sell or attempt to sell huckleberries, or harvest, possess, or transport specialized forest products in violation of RCW 76.48.031;

. Engage in activities or phases of harvesting specialized forest products not authorized by a permit under this chapter;

. Harvest specialized forest products in any lesser quantities than those specified in RCW 76.48.031 without first obtaining permission from the landowner or the landowner's authorized agent or representative; or

. Harvest huckleberries in any amount using a rake, mechanical device, or any other method that damages the huckleberry bush.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1038-S.SL.pdf?cite=2009%20c%20245%20§%2014[2009 c 245 § 14]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1909-S.SL.pdf?cite=2007%20c%20392%20§%204[2007 c 392 § 4]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5011.SL.pdf?cite=1995%20c%20366%20§%202[1995 c 366 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c94.pdf?cite=1979%20ex.s.%20c%2094%20§%202[1979 ex.s. c 94 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c147.pdf?cite=1977%20ex.s.%20c%20147%20§%202[1977 ex.s. c 147 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c47.pdf?cite=1967%20ex.s.%20c%2047%20§%204[1967 ex.s. c 47 § 4]; ]

== 76.48.141 - False, fraudulent, forged, or stolen specialized forest products permit, sales invoice, bill of lading, etc.—Penalty.
. It is unlawful for any person, upon official inquiry, investigation, or other authorized proceedings, to:

.. Offer as genuine any paper, document, or other instrument in writing purporting to be a specialized forest products permit, true copy of a permit, authorization, sales invoice, bill of lading, or other document required under this chapter; or

.. To make any representation of authority to possess or conduct harvesting or transporting of specialized forest products, or to conduct the sale of huckleberries, with knowledge that the representation of authority is in any manner false, fraudulent, forged, or stolen.

. It is unlawful for any person to produce a document for a first or secondary specialized forest products buyer purporting to be a true and genuine permit when delivering or attempting to deliver a specialized forest product with knowledge that the document is in any manner false, fraudulent, forged, or stolen.

. Any person who knowingly or intentionally violates this section is guilty of a class C felony punishable by imprisonment in a state correctional institution for a maximum term fixed by the court of not more than five years or by a fine of not more than five thousand dollars, or by both imprisonment and fine.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1038-S.SL.pdf?cite=2009%20c%20245%20§%2015[2009 c 245 § 15]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2779-S.SL.pdf?cite=2008%20c%20191%20§%207[2008 c 191 § 7]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20373[2003 c 53 § 373]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5011.SL.pdf?cite=1995%20c%20366%20§%2012[1995 c 366 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c94.pdf?cite=1979%20ex.s.%20c%2094%20§%2014[1979 ex.s. c 94 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c147.pdf?cite=1977%20ex.s.%20c%20147%20§%209[1977 ex.s. c 147 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c47.pdf?cite=1967%20ex.s.%20c%2047%20§%2013[1967 ex.s. c 47 § 13]; ]

== 76.48.151 - Penalties—Affirmative defense.
. Except as provided in RCW 76.48.141, a person who violates a provision of this chapter is guilty of a gross misdemeanor punishable by a fine of not more than one thousand dollars, imprisonment in the county jail for up to three hundred sixty-four days, or by both a fine and imprisonment.

. In any prosecution for a violation of this chapter's requirements to obtain or possess a specialized forest products permit, true copy, bill of lading, authorization, or sales invoice, it is an affirmative defense, if established by the defendant by a preponderance of the evidence, that:

.. The specialized forest products were harvested from the defendant's own land; or

.. The specialized forest products were harvested with the permission of the landowner.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5168-S.SL.pdf?cite=2011%20c%2096%20§%2056[2011 c 96 § 56]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1038-S.SL.pdf?cite=2009%20c%20245%20§%2016[2009 c 245 § 16]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1909-S.SL.pdf?cite=2007%20c%20392%20§%201[2007 c 392 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5011.SL.pdf?cite=1995%20c%20366%20§%2013[1995 c 366 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c147.pdf?cite=1977%20ex.s.%20c%20147%20§%2010[1977 ex.s. c 147 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c47.pdf?cite=1967%20ex.s.%20c%2047%20§%2014[1967 ex.s. c 47 § 14]; ]

== 76.48.161 - Multiple convictions for violating RCW  76.48.141 or  76.48.151—Suspension of privileges to obtain a specialized forest products permit.
. The court presiding over the conviction of any person for a violation of RCW 76.48.141 or 76.48.151 who has been convicted of violating either RCW 76.48.141 or 76.48.151 at least two other times shall order up to a three-year suspension of that person's privilege to obtain a specialized forest products permit under this chapter.

. If a court issues a suspension under this section after a conviction involving the misuse of a permit with a specified permittor, the legislature requests that the court notify the permittor listed on the permit of the suspension.

. Nothing in this section limits the ability of a court to order the suspension of any privileges related to specialized forest products as a condition of probation regardless of whether the person has any past convictions.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1038-S.SL.pdf?cite=2009%20c%20245%20§%2017[2009 c 245 § 17]; ]

== 76.48.171 - Disposition of fines.
All fines collected for violations of this chapter shall be paid into the general fund of the county treasury of the county in which the violation occurred and distributed equally among the district courts in the county, the county sheriff's office, and the state treasurer. The portion of the revenue provided to the state treasurer must be distributed to the specialized forest products outreach and education account created in RCW 76.48.251.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1038-S.SL.pdf?cite=2009%20c%20245%20§%2018[2009 c 245 § 18]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1406-S.SL.pdf?cite=2005%20c%20401%20§%2012[2005 c 401 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c147.pdf?cite=1977%20ex.s.%20c%20147%20§%2015[1977 ex.s. c 147 § 15]; ]

== 76.48.181 - Agencies responsible for enforcement of chapter.
. Primary enforcement responsibility of this chapter belongs with county sheriffs. However, other entities that may enforce this chapter include:

.. The department;

.. The Washington state patrol;

.. County or municipal police forces;

.. Authorized personnel of the United States forest service; and

.. Authorized personnel of the department of fish and wildlife. 

. The legislature encourages county sheriffs' offices to enter into interlocal agreements with these other agencies in order to receive additional assistance with their enforcement responsibilities.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1038-S.SL.pdf?cite=2009%20c%20245%20§%2019[2009 c 245 § 19]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5011.SL.pdf?cite=1995%20c%20366%20§%203[1995 c 366 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2590.SL.pdf?cite=1994%20c%20264%20§%2051[1994 c 264 § 51]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c36.pdf?cite=1988%20c%2036%20§%2049[1988 c 36 § 49]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c94.pdf?cite=1979%20ex.s.%20c%2094%20§%203[1979 ex.s. c 94 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c147.pdf?cite=1977%20ex.s.%20c%20147%20§%203[1977 ex.s. c 147 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c47.pdf?cite=1967%20ex.s.%20c%2047%20§%205[1967 ex.s. c 47 § 5]; ]

== 76.48.191 - Detention of specialized forest products and documentation.
. A law enforcement officer may take into custody and detain for a reasonable time any specialized forest products, authorizations, sales invoices, bills of lading, other documents, and vehicles in which the specialized forest products were transported if, under official inquiry, investigation, or other authorized proceeding regarding specialized forest products not covered by a valid permit or other acceptable document as provided in this chapter, the inspecting law enforcement officer has probable cause to believe that the specialized forest products were obtained in violation of this chapter until the true origin of the specialized forest products can be determined.

. A law enforcement officer may retain a specialized forest products permit, true copy of a permit, authorization, sales invoice, bill of lading, or other document required under this chapter if the officer reasonably suspects that the document is forged in violation of RCW 76.48.141, fraudulent, or stolen, until the authenticity of the document can be verified.

. [Empty]
.. If no arrest is made at the conclusion of the official inquiry, investigation, or other authorized proceeding for a violation of this chapter or another state law, all materials detained under this section must be returned to the person or persons from whom the materials were taken.

.. [Empty]
... If an arrest does follow the inquiry, investigation, or authorized proceeding, and the law enforcement officer has probable cause to believe that a person is selling or attempting to sell huckleberries, or is harvesting, in possession of, or transporting specialized forest products in violation of this chapter, any specialized forest products or huckleberries found at the time of arrest may be seized.

... If the specialized forest product triggering the arrest is specialty wood, the law enforcement officer may also seize any equipment, vehicles, tools, or paperwork associated with the arrest.

.. Materials seized under this chapter are subject to the provisions of RCW 76.48.201.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1038-S.SL.pdf?cite=2009%20c%20245%20§%2020[2009 c 245 § 20]; ]

== 76.48.201 - Protection of items seized under RCW  76.48.191—Disposition of items.
. [Empty]
.. Reasonable protection must be provided for any equipment, vehicles, tools, paperwork, huckleberries, or specialized forest products seized under RCW 76.48.191 during the period of adjudication unless the court before which the arrested person is ordered to appear orders the disposal of any or all of the seized materials.

.. Given the perishable nature of huckleberries and specialized forest products, the seizing agency may sell the product at fair market value and retain all proceeds until a final disposition of the case has been reached.

. Upon any disposition of the case by the court, the court shall:

.. Make a reasonable effort to return all materials seized under RCW 76.48.191 to its lawful owner or owners; or

.. Order the disposal of or return of any or all materials seized under this section, including tools, vehicles, equipment, paperwork, or specialized forest products.

. If the court orders the disposal of seized materials, it may:

.. Pay the proceeds of any sale of seized specialized forest products or huckleberries, less any reasonable expenses of the sale, to the lawful owner; or

.. Pay the proceeds of any sale of seized tools, equipment, or vehicles, less any reasonable expenses of the sale or, if applicable, towards any outstanding court costs, and then to the lawful owner or owners.

. If, for any reason, the proceeds of any sale of materials seized under this section cannot be provided to the lawful owner, the proceeds of the sale, less reasonable expenses relating to the sale, shall be paid to the treasurer of the county in which the violation occurred for deposit into the county general fund and for distribution equally among the district courts in the county, the county sheriff's office, and the state treasurer. The portion of the revenue provided to the state treasurer must be distributed to the specialized forest products outreach and education account created in RCW 76.48.251.

. The owner or owners of materials seized under RCW 76.48.191 must be offered an opportunity to appeal an order for the disposal of the seized materials.

. The return of materials seized under RCW 76.48.191, or the payment of the proceeds of any sale of products seized to the owner, shall not preclude the court from imposing any fine or penalty upon the violator for the violation of the provisions of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1038-S.SL.pdf?cite=2009%20c%20245%20§%2021[2009 c 245 § 21]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2779-S.SL.pdf?cite=2008%20c%20191%20§%206[2008 c 191 § 6]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1406-S.SL.pdf?cite=2005%20c%20401%20§%2011[2005 c 401 § 11]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5011.SL.pdf?cite=1995%20c%20366%20§%2011[1995 c 366 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c94.pdf?cite=1979%20ex.s.%20c%2094%20§%2013[1979 ex.s. c 94 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c147.pdf?cite=1977%20ex.s.%20c%20147%20§%208[1977 ex.s. c 147 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c47.pdf?cite=1967%20ex.s.%20c%2047%20§%2012[1967 ex.s. c 47 § 12]; ]

== 76.48.211 - Exemptions.
Except as otherwise conditioned, this chapter does not apply to:

. Nursery grown products.

. The following products when harvested within the operational areas as defined by a valid forest practices application or notification under chapter 76.09 RCW, and when the person harvesting is able to provide a sequentially numbered load ticket provided by the landowner or the landowner's agent that includes, at a minimum, all information required on a bill of lading and the forest practices application or notification number, or under a contract or permit issued by an agency of the United States government:

.. Logs;

.. Speciality wood;

.. Cut or picked evergreen foliage;

.. Poles;

.. Pilings; or

.. Other major forest products from which substantially all of the limbs and branches have been removed.

. Noncommercial harvest, transportation, or possession by the landowner, the landowner's agent, representative, or lessee of specialized forest products originating from property belonging to the landowner.

. Harvest, transportation, or possession of specialized forest products by:

.. A governmental entity or the entity's agent for the purposes of clearing or maintaining the governmental entity's right-of-way or easement; or

.. A public or regulated utility or the utility's agent for the purpose of clearing or maintaining the utility's right-of-way or easement.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1038-S.SL.pdf?cite=2009%20c%20245%20§%2022[2009 c 245 § 22]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1406-S.SL.pdf?cite=2005%20c%20401%20§%2010[2005 c 401 § 10]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5011.SL.pdf?cite=1995%20c%20366%20§%2010[1995 c 366 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c94.pdf?cite=1979%20ex.s.%20c%2094%20§%2012[1979 ex.s. c 94 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c147.pdf?cite=1977%20ex.s.%20c%20147%20§%207[1977 ex.s. c 147 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c47.pdf?cite=1967%20ex.s.%20c%2047%20§%2011[1967 ex.s. c 47 § 11]; ]

== 76.48.221 - Effect of RCW  76.48.031 with respect to huckleberries.
. Nothing in RCW 76.48.031 creates a requirement that a specialized forest products permit is required for an individual to harvest, possess, or transport huckleberries.

. Compliance with RCW 76.48.031 allows an individual to sell, or offer for sale, raw or unprocessed huckleberries. Possession of a specialized forest products permit does not create a right or privilege to harvest huckleberries. Huckleberries may be harvested only with the permission of the landowner and under the terms and conditions established between the landowner and the harvester.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1038-S.SL.pdf?cite=2009%20c%20245%20§%2023[2009 c 245 § 23]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2779-S.SL.pdf?cite=2008%20c%20191%20§%201[2008 c 191 § 1]; ]

== 76.48.231 - Department to develop educational material.
. Subject to the availability of funds in the specialized forest products outreach and education account established under RCW 76.48.251, the department shall develop educational material, including printed information, for law enforcement, forestland owners, and specialized forest products permittees, buyers, and processors specific to this chapter.

. The department is encouraged to foster partnerships with federal agencies, other state agencies, universities, local governments, and private interests in order to minimize educational and outreach expenses.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1038-S.SL.pdf?cite=2009%20c%20245%20§%2024[2009 c 245 § 24]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1406-S.SL.pdf?cite=2005%20c%20401%20§%2013[2005 c 401 § 13]; ]

== 76.48.241 - Assistance and training for minority groups.
. Minority groups have long been participants in the specialized forest products and huckleberry harvesting industry. The legislature encourages agencies serving minority communities, community-based organizations, refugee centers, social service agencies, agencies and organizations with expertise in the specialized forest products and huckleberry harvesting industries, and other interested groups to work cooperatively to accomplish the following purposes:

.. To provide assistance and make referrals on translation services and to assist in translating educational materials, laws, and rules regarding specialized forest products and huckleberries;

.. To hold clinics to teach techniques for effective picking; and

.. To work with both minority and nonminority permittees in order to protect resources and foster understanding between minority and nonminority permittees.

. To the extent practicable within their existing resources, the department, the state commission on Asian Pacific American affairs created in RCW 43.117.030, and the state commission on Hispanic affairs created in RCW 43.115.020 are encouraged to coordinate efforts under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1038-S.SL.pdf?cite=2009%20c%20245%20§%2025[2009 c 245 § 25]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2779-S.SL.pdf?cite=2008%20c%20191%20§%208[2008 c 191 § 8]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5011.SL.pdf?cite=1995%20c%20366%20§%2017[1995 c 366 § 17]; ]

== 76.48.251 - Specialized forest products outreach and education account.
The specialized forest products outreach and education account is created in the custody of the state treasurer. All receipts from RCW 76.48.171 and 76.48.201, any legislative appropriations, private donations, or any other private or public source directed to the account must be deposited in the account. Expenditures from the account may only be used by the department for funding activities under RCW 76.48.231 and 76.48.241. Only the commissioner of public lands or the commissioner's designee may authorize expenditures from the account. The account is subject to the allotment procedures under chapter 43.88 RCW, but an appropriation is not required for expenditures.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1038-S.SL.pdf?cite=2009%20c%20245%20§%2026[2009 c 245 § 26]; ]

== 76.48.907 - Saving—1967 ex.s. c 47.
This chapter is not intended to repeal, supersede, or modify any provision of existing law.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1038-S.SL.pdf?cite=2009%20c%20245%20§%2028[2009 c 245 § 28]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c47.pdf?cite=1967%20ex.s.%20c%2047%20§%2016[1967 ex.s. c 47 § 16]; ]

