= 1.40 - State medal of merit.
:toc:

== 1.40.010 - State medal of merit established.
There is established a decoration of the state medal of merit with accompanying ribbons and appurtenances for award by the governor, in the name of the state, to any person who has been distinguished by exceptionally meritorious conduct in performing outstanding services to the people and state of Washington, upon the nomination of the governor's state medal of merit committee.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c92.pdf?cite=1986%20c%2092%20§%201[1986 c 92 § 1]; ]

== 1.40.020 - Nominating committee created—Composition—Meeting—Rules.
There is created the state medal of merit committee for nominating candidates for the award of the state medal of merit. The committee membership consists of the governor, president of the senate, speaker of the house of representatives, and the chief justice of the supreme court, or their designees. The secretary of state shall serve as a nonvoting ex officio member, and shall serve as secretary to the committee. The committee shall meet annually to consider candidates for nomination. The committee shall adopt rules establishing the qualifications for the state medal of merit, the protocol governing the decoration, and the appurtenances necessary to the implementation of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c92.pdf?cite=1986%20c%2092%20§%202[1986 c 92 § 2]; ]

== 1.40.030 - Delegation of authority to make award.
The governor may delegate the awarding of the state medal of merit to the president of the senate, speaker of the house of representatives, or the chief justice of the supreme court.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c92.pdf?cite=1986%20c%2092%20§%203[1986 c 92 § 3]; ]

== 1.40.040 - Posthumous award.
The state medal of merit may be awarded posthumously to be presented to such representative of the deceased as may be deemed appropriate by the governor or the designees specified in RCW 1.40.030.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c92.pdf?cite=1986%20c%2092%20§%204[1986 c 92 § 4]; ]

== 1.40.050 - Certain persons prohibited from receiving award.
The state medal of merit shall not be awarded to any elected official while in office or to any candidate for an elected office.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c92.pdf?cite=1986%20c%2092%20§%205[1986 c 92 § 5]; ]

== 1.40.060 - Appearance of medal—Inscription.
The decoration of the state medal of merit shall be of bronze and shall consist of the seal of the state of Washington, surrounded by a raised laurel wreath and suspended from a ring attached by a dark green ribbon. The reverse of the decoration within the raised laurel wreath shall be inscribed with the words: "For exceptionally meritorious conduct in performing outstanding services to the people and state of Washington."

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c92.pdf?cite=1986%20c%2092%20§%206[1986 c 92 § 6]; ]

