= 1.70 - Uniform electronic legal material act.
:toc:

== 1.70.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Electronic" means relating to technology having electrical, digital, magnetic, wireless, optical, electromagnetic, or similar capabilities.

. "Legal material" means, whether or not in effect:

.. The Washington state Constitution;

.. The session laws of the state of Washington;

.. The Revised Code of Washington;

.. A state agency rule that has or had the effect of law;

.. The Washington State Register; or

.. The Washington Administrative Code.

. "Official publisher" means:

.. For the Washington state Constitution, the secretary of state;

.. For session laws of the state of Washington, the statute law committee;

.. For the Revised Code of Washington, the statute law committee;

.. For a rule published in the Washington State Register, the statute law committee;

.. For a rule not published in the Washington State Register, the state agency adopting the rule;

.. For the Washington State Register, the statute law committee; or

.. For the Washington Administrative Code, the statute law committee.

. "Publish" means to display, present, or release to the public, or cause to be displayed, presented, or released to the public, by the official publisher.

. "Record" means information that is inscribed on a tangible medium or that is stored in an electronic or other medium and is retrievable in perceivable form.

. "State" means a state of the United States, the District of Columbia, Puerto Rico, the United States Virgin Islands, or any territory or insular possession subject to the jurisdiction of the United States.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5039.SL.pdf?cite=2017%20c%20106%20§%202[2017 c 106 § 2]; ]

== 1.70.020 - Applicability.
. Except as provided in subsection (2) of this section, this chapter applies to all legal material in an electronic record that is designated as official under RCW 1.70.030 and first published electronically on or after January 1, 2018.

. This chapter applies to issues of the Washington State Register in an official electronic record that were first published on or after May 7, 2008.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5039.SL.pdf?cite=2017%20c%20106%20§%203[2017 c 106 § 3]; ]

== 1.70.030 - Legal material in official electronic record.
. If an official publisher publishes legal material only in an electronic record, the publisher shall:

.. Designate the electronic record as official; and

.. Comply with RCW 1.70.040, 1.70.060, and 1.70.070.

. An official publisher that publishes legal material in an electronic record and also publishes the material in a record other than an electronic record may designate the electronic record as official if the publisher complies with RCW 1.70.040, 1.70.060, and 1.70.070.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5039.SL.pdf?cite=2017%20c%20106%20§%204[2017 c 106 § 4]; ]

== 1.70.040 - Authentication of official electronic record.
An official publisher of legal material in an electronic record that is designated as official under RCW 1.70.030 shall authenticate the record. To authenticate an electronic record, the publisher shall provide a method for a user to determine that the record received by the user from the publisher is unaltered from the official record published by the publisher.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5039.SL.pdf?cite=2017%20c%20106%20§%205[2017 c 106 § 5]; ]

== 1.70.050 - Effect of authentication.
. Legal material in an electronic record that is authenticated under RCW 1.70.040 is presumed to be an accurate copy of the legal material.

. If another state has adopted a law substantially similar to this chapter, legal material in an electronic record that is designated as official and authenticated by the official publisher in that state is presumed to be an accurate copy of the legal material.

. A party contesting the authentication of legal material in an electronic record authenticated under RCW 1.70.040 has the burden of proving by a preponderance of the evidence that the record is not authentic.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5039.SL.pdf?cite=2017%20c%20106%20§%206[2017 c 106 § 6]; ]

== 1.70.060 - Preservation and security of legal material in official electronic record.
. An official publisher of legal material in an electronic record that is or was designated as official under RCW 1.70.030 shall provide for the preservation and security of the record in an electronic form or a form that is not electronic.

. If legal material is preserved under subsection (1) of this section in an electronic record, the official publisher shall:

.. Ensure the integrity of the record;

.. Provide for backup and disaster recovery of the record; and

.. Ensure the continuing usability of the material.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5039.SL.pdf?cite=2017%20c%20106%20§%207[2017 c 106 § 7]; ]

== 1.70.070 - Public access to legal material in official electronic record.
An official publisher of legal material in an electronic record that is required to be preserved under RCW 1.70.060 shall ensure that the material is reasonably available for use by the public on a permanent basis.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5039.SL.pdf?cite=2017%20c%20106%20§%208[2017 c 106 § 8]; ]

== 1.70.080 - Standards.
In implementing this chapter, an official publisher of legal material in an electronic record shall consider:

. Standards and practices of other jurisdictions;

. The most recent standards regarding authentication of, preservation and security of, and public access to, legal material in an electronic record and other electronic records, as promulgated by national standard-setting bodies;

. The needs of users of legal material in an electronic record;

. The views of governmental officials and entities and other interested persons; and

. To the extent practicable, methods and technologies for the authentication of, preservation and security of, and public access to, legal material which are compatible with the methods and technologies used by other official publishers in this state and in other states that have adopted a law substantially similar to this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5039.SL.pdf?cite=2017%20c%20106%20§%209[2017 c 106 § 9]; ]

== 1.70.090 - Courts excluded.
This chapter does not apply to any court or agency of the judicial branch.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5039.SL.pdf?cite=2017%20c%20106%20§%2012[2017 c 106 § 12]; ]

== 1.70.900 - Short title.
This chapter may be known and cited as the uniform electronic legal material act.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5039.SL.pdf?cite=2017%20c%20106%20§%201[2017 c 106 § 1]; ]

== 1.70.901 - Uniformity of application and construction.
In applying and construing this uniform act, consideration must be given to the need to promote uniformity of the law with respect to its subject matter among states that enact it.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5039.SL.pdf?cite=2017%20c%20106%20§%2010[2017 c 106 § 10]; ]

== 1.70.902 - Relation to electronic signatures in global and national commerce act.
This chapter modifies, limits, and supersedes the electronic signatures in global and national commerce act, 15 U.S.C. Sec. 7001 et seq., but does not modify, limit, or supersede Section 101(c) of that act, 15 U.S.C. Sec. 7001(c), or authorize electronic delivery of any of the notices described in Section 103(b) of that act, 15 U.S.C. Sec. 7003(b).

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5039.SL.pdf?cite=2017%20c%20106%20§%2011[2017 c 106 § 11]; ]

== 1.70.903 - Effective date—2017 c 106.
This act takes effect January 1, 2018.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5039.SL.pdf?cite=2017%20c%20106%20§%2013[2017 c 106 § 13]; ]

