= 1.80 - Uniform electronic transactions act.
:toc:

== 1.80.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Agreement" means the bargain of the parties in fact, as found in their language or inferred from other circumstances and from rules, regulations, and procedures given the effect of agreements under laws otherwise applicable to a particular transaction.

. "Automated transaction" means a transaction conducted or performed, in whole or in part, by electronic means or electronic records, in which the acts or records of one or both parties are not reviewed by an individual in the ordinary course in forming a contract, performing under an existing contract, or fulfilling an obligation required by the transaction.

. "Blockchain" means a cryptographically secured, chronological, and decentralized consensus ledger or consensus database maintained via internet, peer-to-peer network, or other similar interaction.

. "Computer program" means a set of statements or instructions to be used directly or indirectly in an information processing system in order to bring about a certain result.

. "Contract" means the total legal obligation resulting from the parties' agreement as affected by this chapter and other applicable law.

. "Distributed ledger technology" means any distributed ledger protocol and supporting infrastructure, including blockchain, that uses a distributed, decentralized, shared, and replicated ledger.

. "Electronic" means relating to technology having electrical, digital, magnetic, wireless, optical, electromagnetic, or similar capabilities, including without limitation blockchain and distributed ledger technology.

. "Electronic agent" means a computer program or an electronic or other automated means used independently to initiate an action or respond to electronic records or performances in whole or in part, without review or action by an individual.

. "Electronic record" means a record created, generated, sent, communicated, received, or stored by electronic means.

. "Electronic signature" means an electronic sound, symbol, or process attached to or logically associated with a record and executed or adopted by a person with the intent to sign the record.

. "Governmental agency" means an executive, legislative, or judicial agency, department, board, commission, authority, institution, or instrumentality of the federal government or of a state or of a county, municipality, or other political subdivision of a state.

. "Information" means data, text, images, sounds, codes, computer programs, software, databases, or the like.

. "Information processing system" means an electronic system for creating, generating, sending, receiving, storing, displaying, or processing information.

. "Person" means an individual, corporation, business trust, estate, trust, partnership, limited liability company, association, joint venture, governmental agency, public corporation, or any other legal or commercial entity.

. "Record" means information that is inscribed on a tangible medium or that is stored in an electronic or other medium and is retrievable in perceivable form.

. "Security procedure" means a procedure employed for the purpose of verifying that an electronic signature, record, or performance is that of a specific person or for detecting changes or errors in the information in an electronic record. The term includes a procedure that requires the use of algorithms or other codes, identifying words or numbers, encryption, or callback or other acknowledgment procedures.

. "State" means a state of the United States, the District of Columbia, Puerto Rico, the United States Virgin Islands, or any territory or insular possession subject to the jurisdiction of the United States. The term includes an Indian tribe or band, or Alaskan native village, which is recognized by federal law or formally acknowledged by a state.

. "Transaction" means an action or set of actions occurring between two or more persons relating to the conduct of business, commercial, or governmental affairs.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%202[2020 c 57 § 2]; ]

== 1.80.020 - Scope.
. Except as otherwise provided in subsection (2) of this section, this chapter applies to electronic records and electronic signatures relating to a transaction.

. This chapter does not apply to a transaction to the extent it is governed by:

.. A law governing the creation and execution of wills, codicils, or testamentary trusts; and

.. Title 62A RCW other than RCW 62A.1-306 and chapters 62A.2 and 62A.2A RCW.

. This chapter applies to an electronic record or electronic signature otherwise excluded from the application of this chapter under subsection (2) of this section to the extent it is governed by a law other than those specified in subsection (2) of this section.

. A transaction subject to this chapter is also subject to other applicable substantive law.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%203[2020 c 57 § 3]; ]

== 1.80.030 - Prospective application.
This chapter applies to any electronic record or electronic signature created, generated, sent, communicated, received, or stored on or after June 11, 2020.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%204[2020 c 57 § 4]; ]

== 1.80.040 - Use of electronic records and electronic signatures—Variation by agreement.
. This chapter does not require a record or signature to be created, generated, sent, communicated, received, stored, or otherwise processed or used by electronic means or in electronic form.

. This chapter applies only to transactions between parties each of which has agreed to conduct transactions by electronic means. Whether the parties agree to conduct a transaction by electronic means is determined from the context and surrounding circumstances, including the parties' conduct.

. A party that agrees to conduct a transaction by electronic means may refuse to conduct other transactions by electronic means. The right granted by this subsection may not be waived by agreement.

. Except as otherwise provided in this chapter, the effect of any of its provisions may be varied by agreement. The presence in certain provisions of this chapter of the words "unless otherwise agreed," or words of similar import, does not imply that the effect of other provisions may not be varied by agreement.

. Whether an electronic record or electronic signature has legal consequences is determined by this chapter and other applicable law.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%205[2020 c 57 § 5]; ]

== 1.80.050 - Construction and application.
This chapter must be construed and applied:

. To facilitate electronic transactions consistent with other applicable law;

. To be consistent with reasonable practices concerning electronic transactions and with the continued expansion of those practices; and

. To effectuate its general purpose to make uniform the law with respect to the subject of this chapter among states enacting it.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%206[2020 c 57 § 6]; ]

== 1.80.060 - Legal recognition of electronic records, electronic signatures, and electronic contracts.
. A record or signature may not be denied legal effect or enforceability solely because it is in electronic form.

. A contract may not be denied legal effect or enforceability solely because an electronic record was used in its formation.

. If a law requires a record to be in writing, an electronic record satisfies the law.

. If a law requires a signature, an electronic signature satisfies the law.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%207[2020 c 57 § 7]; ]

== 1.80.070 - Provision of information in writing—Presentation of records.
. If parties have agreed to conduct a transaction by electronic means and a law requires a person to provide, send, or deliver information in writing to another person, the requirement is satisfied if the information is provided, sent, or delivered, as the case may be, in an electronic record capable of retention by the recipient at the time of receipt. An electronic record is not capable of retention by the recipient if the sender or its information processing system inhibits the ability of the recipient to print or store the electronic record.

. If a law other than this chapter requires a record (a) to be posted or displayed in a certain manner, (b) to be sent, communicated, or transmitted by a specified method, or (c) to contain information that is formatted in a certain manner, the following rules apply:

... The record must be posted or displayed in the manner specified in the other law.

... Except as otherwise provided in subsection (4)(b) of this section, the record must be sent, communicated, or transmitted by the method specified in the other law.

... The record must contain the information formatted in the manner specified in the other law.

. If a sender inhibits the ability of a recipient to store or print an electronic record, the electronic record is not enforceable against the recipient.

. The requirements of this section may not be varied by agreement, but:

.. To the extent a law other than this chapter requires information to be provided, sent, or delivered in writing but permits that requirement to be varied by agreement, the requirement under subsection (1) of this section that the information be in the form of an electronic record capable of retention may also be varied by agreement; and

.. A requirement under a law other than this chapter to send, communicate, or transmit a record by regular United States mail may be varied by agreement to the extent permitted by the other law.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%208[2020 c 57 § 8]; ]

== 1.80.080 - Attribution and effect of electronic record and electronic signature.
. An electronic record or electronic signature is attributable to a person if it was the act of the person. The act of the person may be shown in any manner, including a showing of the efficacy of any security procedure applied to determine the person to which the electronic record or electronic signature was attributable.

. The effect of an electronic record or electronic signature attributed to a person under subsection (1) of this section is determined from the context and surrounding circumstances at the time of its creation, execution, or adoption, including the parties' agreement, if any, and otherwise as provided by law.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%209[2020 c 57 § 9]; ]

== 1.80.090 - Effect of change or error.
If a change or error in an electronic record occurs in a transmission between parties to a transaction, the following rules apply:

. If the parties have agreed to use a security procedure to detect changes or errors and one party has conformed to the procedure, but the other party has not, and the nonconforming party would have detected the change or error had that party also conformed, the conforming party may avoid the effect of the changed or erroneous electronic record.

. In an automated transaction involving an individual, the individual may avoid the effect of an electronic record that resulted from an error made by the individual in dealing with the electronic agent of another person if the electronic agent did not provide an opportunity for the prevention or correction of the error and, at the time the individual learns of the error, the individual:

.. Promptly notifies the other person of the error and that the individual did not intend to be bound by the electronic record received by the other person;

.. Takes reasonable steps, including steps that conform to the other person's reasonable instructions, to return to the other person or, if instructed by the other person, to destroy the consideration received, if any, as a result of the erroneous electronic record; and

.. Has not used or received any benefit or value from the consideration, if any, received from the other person.

. If neither subsection (1) of this section nor subsection (2) of this section applies, the change or error has the effect provided by other law, including the law of mistake, and the parties' contract, if any.

. Subsections (2) and (3) of this section may not be varied by agreement.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2010[2020 c 57 § 10]; ]

== 1.80.100 - Notarization, acknowledgment, verification, or under oath.
If a law requires a signature or record to be notarized, acknowledged, verified, or made under oath, the requirement is satisfied if the electronic signature of the person authorized to perform those acts, together with all other information required to be included by other applicable law, is attached to or logically associated with the signature or record.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2011[2020 c 57 § 11]; ]

== 1.80.110 - Retention of electronic records—Originals.
. If a law requires that a record be retained, the requirement is satisfied by retaining an electronic record of the information in the record which:

.. Accurately reflects the information set forth in the record after it was first generated in its final form as an electronic record or otherwise; and

.. Remains accessible for later reference.

. A requirement to retain a record in accordance with subsection (1) of this section does not apply to any information the sole purpose of which is to enable the record to be sent, communicated, or received.

. A person may satisfy subsection (1) of this section by using the services of another person if the requirements of that subsection are satisfied.

. If a law requires a record to be presented or retained in its original form, or provides consequences if the record is not presented or retained in its original form, that law is satisfied by an electronic record retained in accordance with subsection (1) of this section.

. If a law requires retention of a check, that requirement is satisfied by retention of an electronic record of the information on the front and back of the check in accordance with subsection (1) of this section.

. A record retained as an electronic record in accordance with subsection (1) of this section satisfies a law requiring a person to retain a record for evidentiary, audit, or like purposes, unless a law enacted after June 11, 2020, specifically prohibits the use of an electronic record for the specified purpose.

. This section does not preclude a governmental agency of this state from specifying additional requirements for the retention of a record subject to the agency's jurisdiction.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2012[2020 c 57 § 12]; ]

== 1.80.120 - Admissibility in evidence.
In a proceeding, evidence of a record or signature may not be excluded solely because it is in electronic form.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2013[2020 c 57 § 13]; ]

== 1.80.130 - Automated transaction.
In an automated transaction, the following rules apply:

. A contract may be formed by the interaction of electronic agents of the parties, even if no individual was aware of or reviewed the electronic agents' actions or the resulting terms and agreements.

. A contract may be formed by the interaction of an electronic agent and an individual, acting on the individual's own behalf or for another person, including by an interaction in which the individual performs actions that the individual is free to refuse to perform and which the individual knows or has reason to know will cause the electronic agent to complete the transaction or performance.

. The terms of the contract are determined by the substantive law applicable to it.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2014[2020 c 57 § 14]; ]

== 1.80.140 - Time and place of sending and receipt.
. Unless otherwise agreed between the sender and the recipient, an electronic record is sent when it:

.. Is addressed properly or otherwise directed properly to an information processing system that the recipient has designated or uses for the purpose of receiving electronic records or information of the type sent and from which the recipient is able to retrieve the electronic record;

.. Is in a form capable of being processed by that system; and

.. Enters an information processing system outside the control of the sender or of a person that sent the electronic record on behalf of the sender or enters a region of the information processing system designated or used by the recipient which is under the control of the recipient.

. Unless otherwise agreed between a sender and the recipient, an electronic record is received when:

.. It enters an information processing system that the recipient has designated or uses for the purpose of receiving electronic records or information of the type sent and from which the recipient is able to retrieve the electronic record; and

.. It is in a form capable of being processed by that system.

. Subsection (2) of this section applies even if the place the information processing system is located is different from the place the electronic record is deemed to be received under subsection (4) of this section.

. Unless otherwise expressly provided in the electronic record or agreed between the sender and the recipient, an electronic record is deemed to be sent from the sender's place of business and to be received at the recipient's place of business. For purposes of this subsection, the following rules apply:

.. If the sender or recipient has more than one place of business, the place of business of that person is the place having the closest relationship to the underlying transaction.

.. If the sender or the recipient does not have a place of business, the place of business is the sender's or recipient's residence, as the case may be.

. An electronic record is received under subsection (2) of this section even if no individual is aware of its receipt.

. Receipt of an electronic acknowledgment from an information processing system described in subsection (2) of this section establishes that a record was received but, by itself, does not establish that the content sent corresponds to the content received.

. If a person is aware that an electronic record purportedly sent under subsection (1) of this section, or purportedly received under subsection (2) of this section, was not actually sent or received, the legal effect of the sending or receipt is determined by other applicable law. Except to the extent permitted by the other law, the requirements of this subsection may not be varied by agreement.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2015[2020 c 57 § 15]; ]

== 1.80.150 - Transferable records.
. In this section, "transferable record" means an electronic record that:

.. Would be a note under chapter 62A.3 RCW or a document under chapter 62A.7 RCW if the electronic record were in writing; and

.. The issuer of the electronic record expressly has agreed is a transferable record.

. A person has control of a transferable record if a system employed for evidencing the transfer of interests in the transferable record reliably establishes that person as the person to which the transferable record was issued or transferred.

. A system satisfies subsection (2) of this section, and a person is deemed to have control of a transferable record, if the transferable record is created, stored, and assigned in such a manner that:

.. A single authoritative copy of the transferable record exists which is unique, identifiable, and, except as otherwise provided in (d), (e), and (f) of this subsection, unalterable;

.. The authoritative copy identifies the person asserting control as:

... The person to which the transferable record was issued; or

... If the authoritative copy indicates that the transferable record has been transferred, the person to which the transferable record was most recently transferred;

.. The authoritative copy is communicated to and maintained by the person asserting control or its designated custodian;

.. Copies or revisions that add or change an identified assignee of the authoritative copy can be made only with the consent of the person asserting control;

.. Each copy of the authoritative copy and any copy of a copy is readily identifiable as a copy that is not the authoritative copy; and

.. Any revision of the authoritative copy is readily identifiable as authorized or unauthorized.

. Except as otherwise agreed, a person having control of a transferable record is the holder, as defined in RCW 62A.1-201(b)(21), of the transferable record and has the same rights and defenses as a holder of an equivalent record or writing under the uniform commercial code including, if the applicable statutory requirements under RCW 62A.3-302(a), 62A.7-501, or 62A.9A-330 are satisfied, the rights and defenses of a holder in due course, a holder to which a negotiable document of title has been duly negotiated, or a purchaser, respectively. Delivery, possession, and endorsement are not required to obtain or exercise any of the rights under this subsection.

. Except as otherwise agreed, an obligor under a transferable record has the same rights and defenses as an equivalent obligor under equivalent records or writings under the uniform commercial code.

. If requested by a person against which enforcement is sought, the person seeking to enforce the transferable record shall provide reasonable proof that the person is in control of the transferable record. Proof may include access to the authoritative copy of the transferable record and related business records sufficient to review the terms of the transferable record and to establish the identity of the person having control of the transferable record.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2016[2020 c 57 § 16]; ]

== 1.80.160 - Creation and retention of electronic records and conversion of written records by governmental agencies.
Each governmental agency of this state shall determine whether, and the extent to which, a governmental agency will create and retain electronic records and convert written records to electronic records.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2017[2020 c 57 § 17]; ]

== 1.80.170 - Acceptance and distribution of electronic records by governmental agencies.
. Except as otherwise provided in RCW 1.80.110(6), each governmental agency of this state shall determine whether, and the extent to which, a governmental agency will send and accept electronic records and electronic signatures to and from other persons and otherwise create, generate, communicate, store, process, use, and rely upon electronic records and electronic signatures.

. To the extent that a governmental agency uses electronic records and electronic signatures under subsection (1) of this section, the governmental agency, giving due consideration to security, may specify:

.. The manner and format in which the electronic records must be created, generated, sent, communicated, received, and stored and the systems established for those purposes;

.. If electronic records must be signed by electronic means, the type of electronic signature required, the manner and format in which the electronic signature must be affixed to the electronic record, and the identity of, or criteria that must be met by, any third party used by a person filing a document to facilitate the process;

.. Control processes and procedures as appropriate to ensure adequate preservation, disposition, integrity, security, confidentiality, and auditability of electronic records; and

.. Any other required attributes for electronic records which are specified for corresponding nonelectronic records or reasonably necessary under the circumstances.

. Except as otherwise provided in RCW 1.80.110(6), this chapter does not require a governmental agency of this state to use or permit the use of electronic records or electronic signatures.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2018[2020 c 57 § 18]; ]

== 1.80.180 - Consistency and interoperability.
The governmental agency of this state which adopts standards pursuant to RCW 1.80.170 may encourage and promote consistency and interoperability with similar requirements adopted by other governmental agencies of this and other states and the federal government and nongovernmental persons interacting with governmental agencies of this state. If appropriate, those standards may specify differing levels of standards from which governmental agencies of this state may choose in implementing the most appropriate standard for a particular application.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2019[2020 c 57 § 19]; ]

== 1.80.190 - Relation to electronic signatures in global and national commerce act.
This chapter modifies, limits, and supersedes the electronic signatures in global and national commerce act, 15 U.S.C. Sec. 7001 et seq., but does not modify, limit, or supersede section 101(c) of that act, 15 U.S.C. Sec. 7001(c), or authorize electronic delivery of any of the notices described in section 103(b) of that act, 15 U.S.C. Sec. 7003(b).

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2020[2020 c 57 § 20]; ]

== 1.80.900 - Short title.
This chapter may be known and cited as the uniform electronic transactions act.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%201[2020 c 57 § 1]; ]

