= 11.90 - Uniform adult guardianship and protective proceedings jurisdiction act.
:toc:

== 11.90.010 - Short title.
This chapter may be cited as the uniform adult guardianship and protective proceedings jurisdiction act.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1261-S.SL.pdf?cite=2009%20c%2081%20§%201[2009 c 81 § 1]; ]

== 11.90.020 - Definitions. (Effective until January 1, 2022.)
In this chapter:

. "Adult" means an individual who has attained eighteen years of age.

. "Guardian of the estate" means a person appointed by the court to administer the property of an adult, and includes a conservator appointed by the court in another state.

. "Guardian of the person" or "guardian" means a person appointed by the court to make decisions regarding the person of an adult.

. "Guardianship order" means an order appointing a guardian of the person or guardian of the estate.

. "Guardianship proceeding" means a judicial proceeding in which an order for the appointment of a guardian of the person or guardian of the estate is sought or has been issued.

. "Incapacitated person" means an adult for whom a guardian of the person or guardian of the estate has been appointed.

. "Party" means the respondent, petitioner, guardian of the person or guardian of the estate, or any other person allowed by the court to participate in a guardianship or protective proceeding.

. "Person," except in the term incapacitated person or protected person, means an individual, corporation, business trust, estate, trust, partnership, limited liability company, association, joint venture, public corporation, government or governmental subdivision, agency, or instrumentality, or any other legal or commercial entity.

. "Protected person" means an adult for whom a protective order has been issued.

. "Protective order" means an order appointing a guardian of the estate or other order related to management of an adult's property, including an order issued by a court in another state appointing a conservator.

. "Protective proceeding" means a judicial proceeding in which a protective order is sought or has been issued.

. "Record" means information that is inscribed on a tangible medium or that is stored in an electronic or other medium and is retrievable in perceivable form.

. "Respondent" means an adult for whom a protective order or the appointment of a guardian of the person is sought.

. "State" means a state of the United States, the District of Columbia, Puerto Rico, the United States Virgin Islands, a federally recognized Indian tribe, or any territory or insular possession subject to the jurisdiction of the United States.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1261-S.SL.pdf?cite=2009%20c%2081%20§%202[2009 c 81 § 2]; ]

== 11.90.030 - Foreign country treatment.
A court of this state may treat a foreign country as if it were a state for the purpose of applying this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1261-S.SL.pdf?cite=2009%20c%2081%20§%203[2009 c 81 § 3]; ]

== 11.90.040 - Communications with out-of-state courts.
. A court of this state may communicate with a court in another state concerning a proceeding arising under this chapter. The court may allow the parties to participate in the communication. Except as otherwise provided in subsection (2) of this section, the court shall make a record of the communication. The record may be limited to the fact that the communication occurred.

. Courts may communicate concerning schedules, calendars, court records, and other administrative matters without making a record.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1261-S.SL.pdf?cite=2009%20c%2081%20§%204[2009 c 81 § 4]; ]

== 11.90.050 - Requests between in-state and out-of-state courts.
. In a guardianship or protective proceeding in this state, a court of this state may request the appropriate court of another state to do any of the following:

.. Hold an evidentiary hearing;

.. Order a person in that state to produce evidence or give testimony pursuant to procedures of that state;

.. Order that an evaluation or assessment be made of the respondent;

.. Order any appropriate investigation of a person involved in a proceeding;

.. Forward to the court of this state a certified copy of the transcript or other record of a hearing under (a) of this subsection or any other proceeding, any evidence otherwise produced under (b) of this subsection, and any evaluation or assessment prepared in compliance with an order under (c) or (d) of this subsection;

.. Issue any order necessary to assure the appearance in the proceeding of a person whose presence is necessary for the court to make a determination, including the respondent or the incapacitated or protected person;

.. Issue an order authorizing the release of medical, financial, criminal, or other relevant information in that state, including protected health information as defined in 45 C.F.R. Sec. 164.504.

. If a court of another state in which a guardianship or protective proceeding is pending requests assistance of the kind provided in subsection (1) of this section, a court of this state has jurisdiction for the limited purpose of granting the request or making reasonable efforts to comply with the request.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1261-S.SL.pdf?cite=2009%20c%2081%20§%205[2009 c 81 § 5]; ]

== 11.90.060 - Testimony and documentary evidence from another state.
. In a guardianship or protective proceeding, in addition to other procedures that may be available, testimony of a witness who is located in another state may be offered by deposition or other means allowable in this state for testimony taken in another state. The court on its own motion may order that the testimony of a witness be taken in another state and may prescribe the manner in which and the terms upon which the testimony is to be taken.

. In a guardianship or protective proceeding, a court in this state may permit a witness located in another state to be deposed or to testify by telephone or audiovisual or other electronic means. A court of this state shall cooperate with the court of the other state in designating an appropriate location for the deposition or testimony.

. Documentary evidence transmitted from another state to a court of this state by technological means that do not produce an original writing may not be excluded from evidence on an objection based on the best evidence rule.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1261-S.SL.pdf?cite=2009%20c%2081%20§%206[2009 c 81 § 6]; ]

== 11.90.200 - Definitions.
. In this chapter:

.. "Emergency" means a circumstance that likely will result in substantial harm to a respondent's health, safety, or welfare, and for which the appointment of a guardian is necessary because no other person has authority and is willing to act on the respondent's behalf.

.. "Home state" means the state in which the respondent was physically present, including any period of temporary absence, for at least six consecutive months immediately before the filing of a petition for a protective order or the appointment of a guardian; or if none, the state in which the respondent was physically present, including any period of temporary absence, for at least six consecutive months ending within the six months prior to the filing of the petition.

.. "Significant-connection state" means a state, other than the home state, with which a respondent has a significant connection other than mere physical presence and in which substantial evidence concerning the respondent is available.

. In determining under RCW 11.90.220 and 11.90.400(5) whether a respondent has a significant connection with a particular state, the court shall consider:

.. The location of the respondent's family and other persons required to be notified of the guardianship or protective proceeding;

.. The length of time the respondent at any time was physically present in the state and the duration of any absence;

.. The location of the respondent's property; and

.. The extent to which the respondent has ties to the state such as voting registration, state or local tax return filing, vehicle registration, driver's license, social relationship, and receipt of services.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1261-S.SL.pdf?cite=2009%20c%2081%20§%207[2009 c 81 § 7]; ]

== 11.90.210 - Exclusive jurisdictional basis. (Effective until January 1, 2022.)
This chapter provides the exclusive jurisdictional basis for a court of this state to appoint a guardian or issue a protective order for an adult under *chapters 11.88 and 11.92 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1261-S.SL.pdf?cite=2009%20c%2081%20§%208[2009 c 81 § 8]; ]

== 11.90.220 - Appointing a guardian or issuing a protective order.
A court of this state has jurisdiction to appoint a guardian or issue a protective order for a respondent if:

. This state is the respondent's home state;

. On the date the petition is filed, this state is a significant-connection state and:

.. The respondent does not have a home state or a court of the respondent's home state has declined to exercise jurisdiction because this state is a more appropriate forum; or

.. The respondent has a home state, a petition for an appointment or order is not pending in a court of that state or another significant-connection state, and, before the court makes the appointment or issues the order:

... A petition for an appointment or order is not filed in the respondent's home state;

... An objection to the court's jurisdiction is not filed by a person required to be notified of the proceeding; and

... The court in this state concludes that it is an appropriate forum under the factors set forth in RCW 11.90.250;

. This state does not have jurisdiction under either subsection (1) or (2) of this section, the respondent's home state and all significant-connection states have declined to exercise jurisdiction because this state is the more appropriate forum, and jurisdiction in this state is consistent with the constitutions of this state and the United States; or

. The requirements for special jurisdiction under RCW 11.90.230 are met.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1261-S.SL.pdf?cite=2009%20c%2081%20§%209[2009 c 81 § 9]; ]

== 11.90.230 - Special jurisdiction. (Effective until January 1, 2022.)
. A court of this state lacking jurisdiction under RCW 11.90.220 has special jurisdiction to do any of the following:

.. In an emergency, process a petition under *RCW 11.88.090 for appointment of a guardian for a respondent who is physically present in this state, for a term not exceeding ninety days;

.. Issue a protective order with respect to a respondent's real or tangible personal property located in this state if a petition for appointment of a guardian or a conservator for the respondent is pending or has been approved in another state;

.. Appoint a guardian of the person or guardian of the estate for an incapacitated or protected person for whom a provisional order to transfer the proceeding from another state has been issued under procedures similar to RCW 11.90.400.

. If a petition for the appointment of a guardian in an emergency is brought in this state and this state was not the respondent's home state on the date the petition was filed, the court shall dismiss the proceeding at the request of the court of the home state, if any, whether dismissal is requested before or after the emergency appointment.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1261-S.SL.pdf?cite=2009%20c%2081%20§%2010[2009 c 81 § 10]; ]

== 11.90.240 - Exclusive jurisdiction for court appointing a guardian or issuing a protective order.
Except as otherwise provided in RCW 11.90.230, a court that has appointed a guardian or issued a protective order consistent with this chapter has exclusive and continuing jurisdiction over the proceeding until it is terminated by the court or the appointment or order expires by its own terms.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1261-S.SL.pdf?cite=2009%20c%2081%20§%2011[2009 c 81 § 11]; ]

== 11.90.250 - In-state court declining jurisdiction. (Effective until January 1, 2022.)
. A court of this state having jurisdiction under RCW 11.90.220 to appoint a guardian or issue a protective order may decline to exercise its jurisdiction if it determines at any time that a court of another state is a more appropriate forum.

. If a court of this state declines to exercise its jurisdiction under subsection (1) of this section, it shall either dismiss or stay the proceeding. The court may impose any condition the court considers just and proper, including the condition that a petition for the appointment of a guardian or issuance of a protective order be filed promptly in another state.

. In determining whether it is an appropriate forum, the court shall consider all relevant factors, including:

.. Any expressed preference of the respondent;

.. Whether abuse, neglect, or exploitation of the respondent has occurred or is likely to occur and which state could best protect the respondent from the abuse, neglect, or exploitation;

.. The length of time the respondent was physically present in or was a legal resident of this or another state;

.. The distance of the respondent from the court in each state;

.. The financial circumstances of the respondent's estate;

.. The nature and location of the evidence;

.. The ability of the court in each state to decide the issue expeditiously and the procedures necessary to present evidence;

.. The familiarity of the court of each state with the facts and issues in the proceeding; and

.. If an appointment were made, the court's ability to monitor the conduct of the guardian of the person or guardian of the estate.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1261-S.SL.pdf?cite=2009%20c%2081%20§%2012[2009 c 81 § 12]; ]

== 11.90.260 - Jurisdiction required by unjustifiable conduct.
. If at any time a court of this state determines that it acquired jurisdiction to appoint a guardian or issue a protective order because of unjustifiable conduct, the court may:

.. Decline to exercise jurisdiction;

.. Exercise jurisdiction for the limited purpose of fashioning an appropriate remedy to ensure the health, safety, and welfare of the respondent or the protection of the respondent's property or prevent a repetition of the unjustifiable conduct, including staying the proceeding until a petition for the appointment of a guardian or issuance of a protective order is filed in a court of another state having jurisdiction; or

.. Continue to exercise jurisdiction after considering:

... The extent to which the respondent and all persons required to be notified of the proceedings have acquiesced in the exercise of the court's jurisdiction;

... Whether it is a more appropriate forum than the court of any other state under the factors set forth in RCW 11.90.250(3); and

... Whether the court of any other state would have jurisdiction under factual circumstances in substantial conformity with the jurisdictional standards of RCW 11.90.220.

. If a court of this state determines that it acquired jurisdiction to appoint a guardian or issue a protective order because a party seeking to invoke its jurisdiction engaged in unjustifiable conduct, it may assess against that party necessary and reasonable expenses, including attorneys' fees, investigative fees, court costs, communication expenses, witness fees and expenses, and travel expenses. The court may not assess fees, costs, or expenses of any kind against this state or a governmental subdivision, agency, or instrumentality of this state unless authorized by law other than this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1261-S.SL.pdf?cite=2009%20c%2081%20§%2013[2009 c 81 § 13]; ]

== 11.90.270 - Notice of petition requirements when not respondent's home state on filing date.
If a petition for the appointment of a guardian or issuance of a protective order is brought in this state and this state was not the respondent's home state on the date the petition was filed, in addition to complying with the notice requirements of this state, notice of the petition must be given to those persons who would be entitled to notice of the petition if a proceeding were brought in the respondent's home state. The notice must be given in the same manner as notice is required to be given in this state.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1261-S.SL.pdf?cite=2009%20c%2081%20§%2014[2009 c 81 § 14]; ]

== 11.90.280 - Rules when guardian appointment or protective order petition is filed in Washington and another state.
Except for a petition for the appointment of a guardian in an emergency or issuance of a protective order limited to property located in this state under RCW 11.90.230(1) (a) or (b), if a petition for the appointment of a guardian or issuance of a protective order is filed in this state and in another state and neither petition has been dismissed or withdrawn, the following rules apply:

. If the court in this state has jurisdiction under RCW 11.90.220, it may proceed with the case unless a court in another state acquires jurisdiction under provisions similar to RCW 11.90.220 before the appointment or issuance of the order.

. If the court in this state does not have jurisdiction under RCW 11.90.220, whether at the time the petition is filed or at any time before the appointment or issuance of the order, the court shall stay the proceeding and communicate with the court in the other state. If the court in the other state has jurisdiction, the court in this state shall dismiss the petition unless the court in the other state determines that the court in this state is a more appropriate forum.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1261-S.SL.pdf?cite=2009%20c%2081%20§%2015[2009 c 81 § 15]; ]

== 11.90.400 - Procedure for transfer of guardianship to an out-of-state court. (Effective until January 1, 2022.)
. A guardian of the person or guardian of the estate appointed in this state may petition the court to transfer the guardianship to another state.

. Notice of a petition under subsection (1) of this section must be given to the persons that would be entitled to notice of a petition in this state for the appointment of a guardian of the person or guardian of the estate.

. On the court's own motion or on request of the guardian of the person or guardian of the estate, the incapacitated or protected person, or other person required to be notified of the petition, the court shall hold a hearing on a petition filed pursuant to subsection (1) of this section.

. The court shall issue an order provisionally granting a petition to transfer a guardianship and shall direct the guardian of the person or guardian of the estate to petition for guardianship in the other state if the court is satisfied that the guardianship will be accepted by the court in the other state and the court finds that:

.. The incapacitated person is physically present in or is reasonably expected to move permanently to the other state;

.. An objection to the transfer has not been made or, if an objection has been made, the objector has not established that the transfer would be contrary to the interests of the incapacitated person; and

.. Plans for care and services for the incapacitated person in the other state are reasonable and sufficient.

. The court shall issue a provisional order granting a petition to transfer a guardianship of the estate and shall direct the guardian of the estate to petition for guardianship of the estate or conservatorship in the other state if the court is satisfied that the guardianship of the estate will be accepted by the court of the other state and the court finds that:

.. The protected person is physically present in or is reasonably expected to move permanently to the other state, or the protected person has a significant connection to the other state considering the factors in RCW 11.90.200(2);

.. An objection to the transfer has not been made or, if an objection has been made, the objector has not established that the transfer would be contrary to the interests of the protected person; and

.. Adequate arrangements will be made for management of the protected person's property.

. The court shall issue a final order confirming the transfer and terminating the guardianship of the person or guardianship of the estate upon its receipt of:

.. A provisional order accepting the proceeding from the court to which the proceeding is to be transferred which is issued under provisions similar to RCW 11.90.410; and

.. The documents required to terminate a guardianship of the person or guardianship of the estate in this state.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1261-S.SL.pdf?cite=2009%20c%2081%20§%2016[2009 c 81 § 16]; ]

== 11.90.410 - Procedures for transfer of guardianship or conservatorship to Washington. (Effective until January 1, 2022.)
. To confirm transfer of a guardianship or conservatorship transferred to this state under provisions similar to RCW 11.90.400, the guardian or conservator must petition the court in this state to accept the guardianship or conservatorship. The petition must include a certified copy of the other state's provisional order of transfer.

. Notice of a petition under subsection (1) of this section must be given to those persons that would be entitled to notice if the petition were a petition for the appointment of a guardian or issuance of a protective order in both the transferring state and this state. The notice must be given in the same manner as notice is required to be given in this state.

. On the court's own motion or on request of the guardian or conservator, the incapacitated or protected person, or other person required to be notified of the proceeding, the court shall hold a hearing on a petition filed pursuant to subsection (1) of this section.

. The court shall issue an order provisionally granting a petition filed under subsection (1) of this section unless:

.. An objection is made and the objector establishes that transfer of the proceeding would be contrary to the interests of the incapacitated or protected person; or

.. The guardian or conservator is ineligible for appointment in this state.

. The court shall issue a final order accepting the proceeding and appointing the guardian or conservator as guardian of the person or guardian of the estate in this state upon its receipt from the court from which the proceeding is being transferred of a final order issued under provisions similar to RCW 11.90.400 transferring the proceeding to this state.

. Not later than ninety days after issuance of a final order accepting transfer of a guardianship or conservatorship, the court shall determine whether the guardianship of the person or guardianship of the estate needs to be modified to conform to the law of this state.

. In granting a petition under this section, the court shall recognize a guardianship or conservatorship order from the other state, including the determination of the incapacitated or protected person's incapacity and the appointment of the guardian or conservator.

. The denial by a court of this state of a petition to accept a guardianship or conservatorship transferred from another state does not affect the ability of the guardian or conservator to seek appointment as guardian or guardian of the estate in this state if the court has jurisdiction to make an appointment other than by reason of the provisional order of transfer.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1261-S.SL.pdf?cite=2009%20c%2081%20§%2017[2009 c 81 § 17]; ]

== 11.90.420 - Registering out-of-state guardianship.
If a guardian has been appointed in another state and a petition for the appointment of a guardian is not pending in this state, the guardian appointed in the other state, after giving notice to the appointing court of an intent to register, may register the guardianship order in this state by filing as a foreign judgment in a court, in any appropriate county of this state, certified copies of the order and letters of office.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1261-S.SL.pdf?cite=2009%20c%2081%20§%2018[2009 c 81 § 18]; ]

== 11.90.430 - Registering an out-of-state protective order.
If a guardian of the estate or conservator has been appointed in another state and a petition for a protective order is not pending in this state, the guardian of the estate or conservator appointed in the other state, after giving notice to the appointing court of an intent to register, may register the protective order in this state by filing as a foreign judgment in a court of this state, in any county in which property belonging to the protected person is located, certified copies of the order and letters of office and of any bond.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1261-S.SL.pdf?cite=2009%20c%2081%20§%2019[2009 c 81 § 19]; ]

== 11.90.440 - Enforcement of guardianship or protective order from another state.
. Upon registration of a guardianship or protective order from another state, the guardian or conservator may exercise in this state all powers authorized in the order of appointment except as prohibited under the laws of this state, including maintaining actions and proceedings in this state and, if the guardian or conservator is not a resident of this state, subject to any conditions imposed upon nonresident parties.

. A court of this state may grant any relief available under this chapter and other law of this state to enforce a registered order.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1261-S.SL.pdf?cite=2009%20c%2081%20§%2020[2009 c 81 § 20]; ]

== 11.90.450 - Uniformity.
In applying and construing this uniform act, consideration must be given to the need to promote uniformity of the law with respect to its subject matter among states that enact it.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1261-S.SL.pdf?cite=2009%20c%2081%20§%2021[2009 c 81 § 21]; ]

== 11.90.460 - Application of the federal electronic signatures in global and national commerce act.
This chapter modifies, limits, and supersedes the federal electronic signatures in global and national commerce act, 15 U.S.C. Sec. 7001, et seq., but does not modify, limit, or supersede section 101(c) of that act, 15 U.S.C. 7001(c), or authorize electronic delivery of any of the notices described in section 103(b) of that act, 15 U.S.C. Sec. 7003(b).

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1261-S.SL.pdf?cite=2009%20c%2081%20§%2022[2009 c 81 § 22]; ]

== 11.90.470 - Application.
. This chapter applies to guardianship and protective proceedings filed on or after January 1, 2010.

. RCW 11.90.010 through 11.90.060 and 11.90.400 through 11.90.460 apply to proceedings filed before January 1, 2010, regardless of whether a guardianship or protective order has been issued.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1261-S.SL.pdf?cite=2009%20c%2081%20§%2023[2009 c 81 § 23]; ]

