= 11.48 - Personal representatives—General provisions—Actions by and against.
:toc:

== 11.48.010 - General powers and duties.
It shall be the duty of every personal representative to settle the estate, including the administration of any nonprobate assets within control of the personal representative under RCW 11.18.200, in his or her hands as rapidly and as quickly as possible, without sacrifice to the probate or nonprobate estate. The personal representative shall collect all debts due the deceased and pay all debts as hereinafter provided. The personal representative shall be authorized in his or her own name to maintain and prosecute such actions as pertain to the management and settlement of the estate, and may institute suit to collect any debts due the estate or to recover any property, real or personal, or for trespass of any kind or character.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2270-S.SL.pdf?cite=1994%20c%20221%20§%2030[1994 c 221 § 30]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.48.010[1965 c 145 § 11.48.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20147[1917 c 156 § 147]; RRS § 1517; prior: Code 1881 § 1528; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20291%20§%20141[1854 p 291 § 141]; ]

== 11.48.020 - Right to possession and management of estate.
Every personal representative shall, after having qualified, by giving bond as hereinbefore provided, have a right to the immediate possession of all the real as well as personal estate of the deceased, and may receive the rents and profits of the real estate until the estate shall be settled or delivered over, by order of the court, to the heirs or devisees, and shall keep in tenantable repair all houses, buildings and fixtures thereon, which are under his or her control.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202030[2010 c 8 § 2030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.48.020[1965 c 145 § 11.48.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%2094[1917 c 156 § 94]; RRS § 1464; prior: Code 1881 § 1444; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1860%20p%20189%20§%20132[1860 p 189 § 132]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20278%20§%2065[1854 p 278 § 65]; ]

== 11.48.025 - Continuation of decedent's business.
Upon a showing of advantage to the estate the court may authorize a personal representative to continue any business of the decedent, other than the business of a partnership of which the decedent was a member: PROVIDED, That if decedent left a nonintervention will or a will specifically authorizing a personal representative to continue any business of decedent, and his or her estate is solvent, or a will providing that the personal representative liquidate any business of decedent, this section shall not apply.

The order shall specify:

. The extent of the authority of the personal representative to incur liabilities;

. The period of time during which he or she may operate the business;

. Any additional provisions or restrictions which the court may, at its discretion, include.

Any interested person may for good cause require the personal representative to show cause why the authority granted him or her should not be limited or terminated. The order to show cause shall set forth the manner of service thereof and the time and place of hearing thereon.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202031[2010 c 8 § 2031]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.48.025[1965 c 145 § 11.48.025]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c98.pdf?cite=1955%20c%2098%20§%201[1955 c 98 § 1]; ]

== 11.48.030 - Chargeable with whole estate.
Every personal representative shall be chargeable in his or her accounts with the whole estate of the deceased which may come into his or her possession. He or she shall not be responsible for loss or decrease or destruction of any of the property or effects of the estate, without his or her fault.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202032[2010 c 8 § 2032]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.48.030[1965 c 145 § 11.48.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20155[1917 c 156 § 155]; RRS § 1525; prior: Code 1881 § 1538; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1860%20p%20210%20§%20241[1860 p 210 § 241]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20295%20§%20161[1854 p 295 § 161]; ]

== 11.48.040 - Not chargeable on special promise to pay decedent's debts unless in writing.
No personal representative shall be chargeable upon any special promise to answer damages, or to pay the debts of the testator or intestate out of his or her own estate, unless the agreement for that purpose, or some memorandum or note thereof, is in writing and signed by such personal representative, or by some other person by him or her thereunto specially authorized.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202033[2010 c 8 § 2033]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.48.040[1965 c 145 § 11.48.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20154[1917 c 156 § 154]; RRS § 1524; prior: Code 1881 § 1537; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20295%20§%20160[1854 p 295 § 160]; ]

== 11.48.050 - Allowance of necessary expenses.
He or she shall be allowed all necessary expenses in the care, management, and settlement of the estate.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202034[2010 c 8 § 2034]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.48.050[1965 c 145 § 11.48.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20156[1917 c 156 § 156]; RRS § 1526; prior: Code 1881 § 1541; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20295%20§%20164[1854 p 295 § 164]; ]

== 11.48.060 - May recover for embezzled or alienated property of decedent.
If any person, before the granting of letters testamentary or of administration, shall embezzle or alienate any of the moneys, goods, chattels, or effects of any deceased person, he or she shall stand chargeable, and be liable to the personal representative of the estate, in the value of the property so embezzled or alienated, together with any damage occasioned thereby, to be recovered for the benefit of the estate.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202035[2010 c 8 § 2035]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.48.060[1965 c 145 § 11.48.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20101[1917 c 156 § 101]; RRS § 1471; prior: Code 1881 § 1455; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20278%20§%2067[1854 p 278 § 67]; ]

== 11.48.070 - Concealed or embezzled property—Proceedings for discovery.
The court shall have authority to bring before it any person or persons suspected of having in his or her possession or having concealed, embezzled, conveyed, or disposed of any of the property of the estate of decedents or incompetents subject to administration under this title, or who has in his or her possession or within his or her knowledge any conveyances, bonds, contracts, or other writings which contain evidence of or may tend to establish the right, title, interest, or claim of the deceased in and to any property. If such person be not in the county in which the letters were granted, he or she may be cited and examined either before the court of the county where found or before the court issuing the order of citation, and if he or she be found innocent of the charges he or she shall be entitled to recover costs of the estate, which costs shall be fees and mileage of witnesses, statutory attorney's fees, and such per diem and mileage for the person so charged as allowed to witnesses in civil proceedings. Such party may be brought before the court by means of citation such as the court may choose to issue, and if he or she refuses to answer such interrogatories as may be put to him or her touching such matters, the court may commit him or her to the county jail, there to remain until he or she shall be willing to make such answers.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202036[2010 c 8 § 2036]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.48.070[1965 c 145 § 11.48.070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20102[1917 c 156 § 102]; RRS § 1472; prior: 1891 p 385 §§ 22, 23; Code 1881 §§ 1456, 1457; 1854 p 278 §§ 68, 69; ]

== 11.48.080 - Uncollectible debts—Liability—Purchase of claims by personal representative.
No personal representative shall be accountable for any debts due the estate, if it shall appear that they remain uncollected without his or her fault. No personal representative shall purchase any claim against the estate he or she represents, but the personal representative may make application to the court for permission to purchase certain claims, and if it appears to the court to be for the benefit of the estate that such purchase shall be made, the court may make an order allowing such claims and directing that the same may be purchased by the personal representative under such terms as the court shall order, and such claims shall thereafter be paid as are other claims, but the personal representative shall not profit thereby.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202037[2010 c 8 § 2037]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.48.080[1965 c 145 § 11.48.080]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20157[1917 c 156 § 157]; RRS § 1527; prior: Code 1881 § 1540; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20295%20§%20163[1854 p 295 § 163]; ]

== 11.48.090 - Actions for recovery of property and on contract.
Actions for the recovery of any property or for the possession thereof, and all actions founded upon contracts, may be maintained by and against personal representatives in all cases in which the same might have been maintained by and against their respective testators or intestates.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.48.090[1965 c 145 § 11.48.090]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20148[1917 c 156 § 148]; RRS § 1518; prior: Code 1881 § 1529; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1860%20p%20206%20§%20222[1860 p 206 § 222]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20291%20§%20142[1854 p 291 § 142]; ]

== 11.48.120 - Action on bond of previous personal representative.
Any personal representative may in his or her own name, for the benefit of all persons interested in the estate, as defined in RCW 11.96A.030(6) relative to a decedent's estate, maintain actions on the bond of a former personal representative of the same estate.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%204002[2021 c 140 § 4002]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202038[2010 c 8 § 2038]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.48.120[1965 c 145 § 11.48.120]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20151[1917 c 156 § 151]; RRS § 1521; prior: Code 1881 § 1532; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20291%20§%20145[1854 p 291 § 145]; ]

== 11.48.130 - Compromise of claims.
The court may authorize the personal representative, without the necessary nonintervention powers, to compromise and compound any claim owing the estate. Unless the court has restricted the power to compromise or compound claims owing to the estate and except as provided in RCW 11.68.090, a personal representative with nonintervention powers may compromise and compound a claim owing the estate without the intervention of the court.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%204003[2021 c 140 § 4003]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5110-S.SL.pdf?cite=1997%20c%20252%20§%2058[1997 c 252 § 58]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.48.130[1965 c 145 § 11.48.130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20152[1917 c 156 § 152]; RRS § 1522; prior: Code 1881 § 1533; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20291%20§%20146[1854 p 291 § 146]; ]

== 11.48.140 - Recovery of decedent's fraudulent conveyances.
When there shall be a deficiency of assets in the hands of a personal representative, and when the deceased shall in his or her lifetime have conveyed any real estate, or any rights, or interest therein, with intent to defraud his or her creditors or to avoid any right, duty, or debt of any person, or shall have so conveyed such estate, which deeds or conveyances by law are void as against creditors, the personal representative may, and it shall be his or her duty to, commence and prosecute to final judgment any proper action for the recovery of the same, and may recover for the benefit of the creditors all such real estate so fraudulently conveyed, and may also, for the benefit of the creditors, sue and recover all goods, chattels, rights, and credits which may have been so fraudulently conveyed by the deceased in his or her lifetime, whatever may have been the manner of such fraudulent conveyance.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202039[2010 c 8 § 2039]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.48.140[1965 c 145 § 11.48.140]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20153[1917 c 156 § 153]; prior: Code 1881 § 1534; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20291%20§%20147[1854 p 291 § 147]; ]

== 11.48.150 - Several personal representatives considered as one.
In an action against several personal representatives, they shall all be considered as one person representing their testator or intestate, and judgment may be given and execution issued against all of them who are defendants in the action.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.48.150[1965 c 145 § 11.48.150]; Code 1881 § 719; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20146%20§%20723[1877 p 146 § 723]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20165%20§%20660[1869 p 165 § 660]; RRS § 968; ]

== 11.48.160 - Default judgment not evidence of assets—Exception.
When a judgment is given against a personal representative for want of answer, such judgment is not to be deemed evidence of assets in his or her hands, unless it appear that the complaint alleged assets and that the notice was served upon him or her.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202040[2010 c 8 § 2040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.48.160[1965 c 145 § 11.48.160]; Code 1881 § 720; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20146%20§%20724[1877 p 146 § 724]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20166%20§%20661[1869 p 166 § 661]; RRS § 969; ]

== 11.48.180 - Liability of executor de son tort.
No person is liable to an action as executor of his or her own wrong for having taken, received, or interfered with the property of a deceased person, but is responsible to the personal representatives of such deceased person for the value of all property so taken or received, and for all injury caused by his or her interference with the estate of the deceased.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202041[2010 c 8 § 2041]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.48.180[1965 c 145 § 11.48.180]; Code 1881 § 722; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20146%20§%20726[1877 p 146 § 726]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20166%20§%20663[1869 p 166 § 663]; RRS § 971; ]

== 11.48.190 - Executor of executor may not sue for estate of first testator.
An executor of an executor has no authority as such to commence or maintain an action or proceeding relating to the estate of the testator of the first executor, or to take any charge or control thereof.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.48.190[1965 c 145 § 11.48.190]; Code 1881 § 723; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20147%20§%20727[1877 p 147 § 727]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20166%20§%20664[1869 p 166 § 664]; RRS § 972; ]

== 11.48.200 - Arrest and attachment, when, authorized.
In an action against a personal representative as such, the remedies of arrest and attachment shall not be allowed on account of the acts of his or her testator or intestate, but for his or her own acts as such personal representative, such remedies shall be allowed for the same causes in the manner and with like effect as in actions at law generally.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202042[2010 c 8 § 2042]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.48.200[1965 c 145 § 11.48.200]; Code 1881 § 724; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20147%20§%20729[1877 p 147 § 729]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20167%20§%20666[1869 p 167 § 666]; RRS § 973; ]

== 11.48.210 - Compensation—Attorney's fees.
If testator by will makes provision for the compensation of his or her personal representative, that shall be taken as his or her full compensation unless he or she files in the court a written instrument renouncing all claim for the compensation provided by the will before qualifying as personal representative. The personal representative, when no compensation is provided in the will, or when he or she renounces all claim to the compensation provided in the will, shall be allowed such compensation for his or her services as the court shall deem just and reasonable. Additional compensation may be allowed for his or her services as attorney and for other services not required of a personal representative. An attorney performing services for the estate at the instance of the personal representative shall have such compensation therefor out of the estate as the court shall deem just and reasonable. Such compensation may be allowed at the final account; but at any time during administration a personal representative or his or her attorney may apply to the court for an allowance upon the compensation of the personal representative and upon attorney's fees. If the court finds that the personal representative has failed to discharge his or her duties as such in any respect, it may deny him or her any compensation whatsoever or may reduce the compensation which would otherwise be allowed.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202043[2010 c 8 § 2043]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.48.210[1965 c 145 § 11.48.210]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20158[1917 c 156 § 158]; RRS § 1528; prior: Code 1881 § 1541; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20295%20§%20164[1854 p 295 § 164]; ]

