= 11.24 - Will contests.
:toc:

== 11.24.010 - Contest of probate or rejection—Limitation of action—Issues.
If any person interested in any will shall appear within four months immediately following the probate or rejection thereof, and by petition to the court having jurisdiction contest the validity of said will, or appear to have the will proven which has been rejected, he or she shall file a petition containing his or her objections and exceptions to said will, or to the rejection thereof. Issues respecting the competency of the deceased to make a last will and testament, or respecting the execution by a deceased of the last will and testament under restraint or undue influence or fraudulent representations, or for any other cause affecting the validity of the will or a part of it, shall be tried and determined by the court.

For the purpose of tolling the four-month limitations period, a contest is deemed commenced when a petition is filed with the court and not when served upon the personal representative. The petitioner shall personally serve the personal representative within ninety days after the date of filing the petition. If, following filing, service is not so made, the action is deemed to not have been commenced for purposes of tolling the statute of limitations.

If no person files and serves a petition within the time under this section, the probate or rejection of such will shall be binding and final.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2236.SL.pdf?cite=2007%20c%20475%20§%204[2007 c 475 § 4]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2270-S.SL.pdf?cite=1994%20c%20221%20§%2021[1994 c 221 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971c7.pdf?cite=1971%20c%207%20§%201[1971 c 7 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c168.pdf?cite=1967%20c%20168%20§%206[1967 c 168 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.24.010[1965 c 145 § 11.24.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%2015[1917 c 156 § 15]; RRS § 1385; prior:  1891 p 382 § 8; Code 1881 § 1360; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20213%20§%2096[1863 p 213 § 96]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1860%20p%20176%20§%2063[1860 p 176 § 63]; ]

== 11.24.020 - Filing of will contest petition—Notice.
Upon the filing of the petition referred to in RCW 11.24.010, notice shall be given as provided in RCW 11.96A.100 to the executors who have taken upon themselves the execution of the will, or to the administrators with the will annexed, to all legatees named in the will or to their guardians if any of them are minors, or their personal representatives if any of them are dead, and to all persons interested in the matter, as defined in *RCW 11.96A.030(5).

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6597-S.SL.pdf?cite=2006%20c%20360%20§%209[2006 c 360 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.24.020[1965 c 145 § 11.24.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%2016[1917 c 156 § 16]; RRS § 1386; prior:  1891 p 382 § 9; Code 1881 § 1361; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20214%20§%2097[1863 p 214 § 97]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1860%20p%20176%20§%2064[1860 p 176 § 64]; ]

== 11.24.030 - Burden of proof.
In any such contest proceedings the previous order of the court probating, or refusing to probate, such will shall be prima facie evidence of the legality of such will, if probated, or its illegality, if rejected, and the burden of proving the illegality of such will, if probated, or the legality of such will, if rejected by the court, shall rest upon the person contesting such probation or rejection of the will.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.24.030[1965 c 145 § 11.24.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%2017[1917 c 156 § 17]; RRS § 1387; ]

== 11.24.040 - Revocation of probate.
If, upon the trial of said issue, it shall be decided that the will or a part of it is for any reason invalid, or that it is not sufficiently proved to have been the last will of the testator, the will or part and probate thereof shall be annulled and revoked and to that extent the powers of the personal representative shall cease, but the personal representative shall not be liable for any act done in good faith previous to such annulling or revoking.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2270-S.SL.pdf?cite=1994%20c%20221%20§%2022[1994 c 221 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.24.040[1965 c 145 § 11.24.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%2018[1917 c 156 § 18]; RRS § 1388; prior: Code 1881 § 1364; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20214%20§%20100[1863 p 214 § 100]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1860%20p%20177%20§%2067[1860 p 177 § 67]; ]

== 11.24.050 - Costs.
If the probate be revoked or the will annulled, assessment of costs shall be in the discretion of the court. If the will be sustained, the court may assess the costs against the contestant, including, unless it appears that the contestant acted with probable cause and in good faith, such reasonable attorney's fees as the court may deem proper.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.24.050[1965 c 145 § 11.24.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%2019[1917 c 156 § 19]; RRS § 1389; prior: Code 1881 § 1366; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1860%20p%20177%20§%2069[1860 p 177 § 69]; ]

