= 11.98B - Uniform directed trust act.
:toc:

== 11.98B.005 - Short title.
This chapter may be known and cited as the uniform directed trust act.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6029-S.SL.pdf?cite=2020%20c%20303%20§%201[2020 c 303 § 1]; ]

== 11.98B.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Breach of trust" includes a violation by a trust director or trustee of a duty imposed on that director or trustee by the terms of the trust, this chapter, or law of this state other than this chapter pertaining to trusts.

. "Directed trust" means a trust for which the terms of the trust grant a power of direction.

. "Directed trustee" means a trustee that is subject to a trust director's power of direction.

. "Person" means an individual, estate, business or nonprofit entity, public corporation, government or governmental subdivision, agency, or instrumentality, or other legal entity.

. "Power of direction" means a power over a trust granted to a person by the terms of the trust to the extent the power is exercisable while the person is not serving as a trustee. The term includes a power over the investment, management, or distribution of trust property or other matters of trust administration. The term excludes the powers described in RCW 11.98B.030(2).

. "Settlor" means a person, including a testator, that creates, or contributes property to, a trust. If more than one person creates or contributes property to a trust, each person is a settlor of the portion of the trust property attributable to that person's contribution except to the extent another person has the power to revoke or withdraw that portion.

. "State" means a state of the United States, the District of Columbia, Puerto Rico, the United States Virgin Islands, or any other territory or possession subject to the jurisdiction of the United States.

. "Terms of a trust" means:

.. Except as otherwise provided in (b) of this subsection, the manifestation of the settlor's intent regarding a trust's provisions as:

... Expressed in the trust instrument; or

... Established by other evidence that would be admissible in a judicial proceeding; or

.. The trust's provisions as established, determined, or amended by:

... A trustee or trust director in accordance with applicable law;

... Court order; or

... A nonjudicial settlement agreement under chapter 11.96A RCW.

. "Trust director" means a person that is granted a power of direction by the terms of a trust to the extent the power is exercisable while the person is not serving as a trustee. The person is a trust director whether or not the terms of the trust refer to the person as a trust director and whether or not the person is a beneficiary or settlor of the trust.

. "Trustee" includes an original, additional, and successor trustee, and a cotrustee.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6029-S.SL.pdf?cite=2020%20c%20303%20§%202[2020 c 303 § 2]; ]

== 11.98B.020 - Applicability—Principal place of administration.
. This chapter applies to a trust, whenever created, that has its principal place of administration in this state, subject to the following rules:

.. If the trust was created before January 1, 2021, this chapter applies only to a decision or action occurring on or after January 1, 2021.

.. If the principal place of administration of the trust is changed to this state on or after January 1, 2021, this chapter applies only to a decision or action occurring on or after the date of the change.

. Without precluding other means to establish a sufficient connection with the designated jurisdiction in a directed trust, terms of the trust which designate the principal place of administration of the trust are valid and controlling if:

.. A trustee's principal place of business is located in or a trustee is a resident of the designated jurisdiction;

.. A trust director's principal place of business is located in or a trust director is a resident of the designated jurisdiction; or

.. All or part of the administration occurs in the designated jurisdiction.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6029-S.SL.pdf?cite=2020%20c%20303%20§%203[2020 c 303 § 3]; ]

== 11.98B.030 - Applicability—Exclusions—Power of appointment.
. In this section, "power of appointment" means a power that enables a person acting in a nonfiduciary capacity to designate a recipient of an ownership interest in or another power of appointment over trust property.

. This chapter does not apply to a:

.. Power of appointment;

.. Power to appoint or remove a trustee or trust director;

.. Power of a settlor over a trust to the extent the settlor has a power to revoke the trust;

.. Power of a beneficiary over a trust to the extent the exercise or nonexercise of the power affects the beneficial interest of:

... The beneficiary; or

... Another beneficiary represented by the beneficiary with respect to the exercise or nonexercise of the power; or

.. Power over a trust if:

... The terms of the trust provide that the power is held in a nonfiduciary capacity; and

... The power must be held in a nonfiduciary capacity to achieve the settlor's tax objectives under the federal internal revenue code of 1986, as amended, as of January 1, 2021.

. Unless the terms of a trust provide otherwise, a power granted to a person to designate a recipient of an ownership interest in or power of appointment over trust property which is exercisable while the person is not serving as a trustee is a power of appointment and not a power of direction.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6029-S.SL.pdf?cite=2020%20c%20303%20§%205[2020 c 303 § 5]; ]

== 11.98B.040 - Common law and principles of equity supplement.
The common law and principles of equity supplement this chapter, except to the extent modified by this chapter or law of this state other than this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6029-S.SL.pdf?cite=2020%20c%20303%20§%204[2020 c 303 § 4]; ]

== 11.98B.050 - Trust director—Power of direction.
. Subject to RCW 11.98B.060, the terms of a trust may grant a power of direction to a trust director.

. Unless the terms of a trust provide otherwise:

.. A trust director may exercise any further power appropriate to the exercise or nonexercise of a power of direction granted to the director under subsection (1) of this section; and

.. Trust directors with joint powers must act by majority decision.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6029-S.SL.pdf?cite=2020%20c%20303%20§%206[2020 c 303 § 6]; ]

== 11.98B.060 - Trust director—Power of direction—Limitations.
A trust director is subject to the same rules as a trustee in a like position and under similar circumstances in the exercise or nonexercise of a power of direction or further power under RCW 11.98B.050(2)(a) regarding:

. A payback provision in the terms of a trust necessary to comply with the reimbursement requirements of medicaid law in section 1917 of the social security act, 42 U.S.C. Sec. 1396p(d)(4)(A), as amended, as of January 1, 2021; and

. A charitable interest in the trust.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6029-S.SL.pdf?cite=2020%20c%20303%20§%207[2020 c 303 § 7]; ]

== 11.98B.070 - Trust director—Duties and liability.
. Subject to subsection (2) of this section, with respect to a power of direction or further power under RCW 11.98B.050(2)(a):

.. A trust director has the same fiduciary duty and liability in the exercise or nonexercise of the power:

... If the power is held individually, as a sole trustee in a like position and under similar circumstances; or

... If the power is held jointly with a trustee or another trust director, as a cotrustee in a like position and under similar circumstances; and

.. The terms of the trust may vary the director's duty or liability to the same extent the terms of the trust could vary the duty or liability of a trustee in a like position and under similar circumstances.

. Unless the terms of a trust provide otherwise, if a trust director is licensed, certified, or otherwise authorized or permitted by law other than this chapter to provide health care in the ordinary course of the director's business or practice of a profession, to the extent the director acts in that capacity, the director has no duty or liability under this chapter.

. The terms of a trust may impose a duty or liability on a trust director in addition to the duties and liabilities under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6029-S.SL.pdf?cite=2020%20c%20303%20§%208[2020 c 303 § 8]; ]

== 11.98B.080 - Directed trustee—Duties and liability.
. Subject to subsection (2) of this section, a directed trustee shall take reasonable action to comply with a trust director's exercise or nonexercise of a power of direction or further power under RCW 11.98B.050(2)(a), and the trustee is not liable for the action.

. A directed trustee must not comply with a trust director's exercise or nonexercise of a power of direction or further power under RCW 11.98B.050(2)(a) to the extent that by complying the trustee would engage in willful misconduct.

. An exercise of a power of direction under which a trust director may release a trustee or another trust director from liability for breach of trust is not effective if:

.. The breach involved the trustee's or other director's willful misconduct;

.. The release was induced by improper conduct of the trustee or other director in procuring the release; or

.. At the time of the release, the director did not know the material facts relating to the breach.

. A directed trustee that has reasonable doubt about its duty under this section may petition the superior court for instructions in the county where venue lies for the trust under RCW 11.96A.050.

. The terms of a trust may impose a duty or liability on a directed trustee in addition to the duties and liabilities under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6029-S.SL.pdf?cite=2020%20c%20303%20§%209[2020 c 303 § 9]; ]

== 11.98B.090 - Duty to provide information to trust director or trustee.
. Subject to RCW 11.98B.100, a trustee shall provide information to a trust director to the extent the information is reasonably related both to:

.. The powers or duties of the trustee; and

.. The powers or duties of the director.

. Subject to RCW 11.98B.100, a trust director shall provide information to a trustee or another trust director to the extent the information is reasonably related both to:

.. The powers or duties of the director; and

.. The powers or duties of the trustee or other director.

. A trustee that acts in reliance on information provided by a trust director is not liable for a breach of trust to the extent the breach resulted from the reliance, unless by so acting the trustee engages in willful misconduct.

. A trust director that acts in reliance on information provided by a trustee or another trust director is not liable for a breach of trust to the extent the breach resulted from the reliance, unless by so acting the trust director engages in willful misconduct.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6029-S.SL.pdf?cite=2020%20c%20303%20§%2010[2020 c 303 § 10]; ]

== 11.98B.100 - No duty to monitor, inform, or advise trust director or trustee.
. Unless the terms of a trust provide otherwise:

.. A trustee does not have a duty to:

... Monitor a trust director; or

... Inform or give advice to a settlor, beneficiary, trustee, or trust director concerning an instance in which the trustee might have acted differently than the director; and

.. By taking an action described in (a) of this subsection, a trustee does not assume the duty excluded by (a) of this subsection.

. Unless the terms of a trust provide otherwise:

.. A trust director does not have a duty to:

... Monitor a trustee or another trust director; or

... Inform or give advice to a settlor, beneficiary, trustee, or another trust director concerning an instance in which the director might have acted differently than a trustee or another trust director; and

.. By taking an action described in (a) of this subsection, a trust director does not assume the duty excluded by (a) of this subsection.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6029-S.SL.pdf?cite=2020%20c%20303%20§%2011[2020 c 303 § 11]; ]

== 11.98B.110 - Application to cotrustee.
The terms of a trust may relieve a cotrustee from duty and liability with respect to another cotrustee's exercise or nonexercise of a power of the other cotrustee to the same extent that in a directed trust a directed trustee is relieved from duty and liability with respect to a trust director's power of direction under RCW 11.98B.080 through 11.98B.100.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6029-S.SL.pdf?cite=2020%20c%20303%20§%2012[2020 c 303 § 12]; ]

== 11.98B.120 - Trust director—Action against—Limitation.
. An action against a trust director for breach of trust must be commenced within the same limitation period under RCW 11.96A.070 as for an action for breach of trust against a trustee in a like position and under similar circumstances.

. A report or accounting has the same effect on the limitation period for an action against a trust director for breach of trust that the report or accounting would have under RCW 11.96A.070 in an action for breach of trust against a trustee in a like position and under similar circumstances.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6029-S.SL.pdf?cite=2020%20c%20303%20§%2013[2020 c 303 § 13]; ]

== 11.98B.130 - Trust director—Action against—Defenses.
In an action against a trust director for breach of trust, the director may assert the same defenses a trustee in a like position and under similar circumstances could assert in an action for breach of trust against the trustee.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6029-S.SL.pdf?cite=2020%20c%20303%20§%2014[2020 c 303 § 14]; ]

== 11.98B.140 - Trust director—Personal jurisdiction.
. By accepting appointment as a trust director of a trust subject to this chapter, the director submits to personal jurisdiction of the courts of this state regarding any matter related to a power or duty of the director.

. This section does not preclude other methods of obtaining jurisdiction over a trust director.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6029-S.SL.pdf?cite=2020%20c%20303%20§%2015[2020 c 303 § 15]; ]

== 11.98B.150 - Trust director—Rules applicable to trustees apply.
Unless the terms of a trust provide otherwise, the rules applicable to a trustee apply to a trust director regarding the following matters:

. Acceptance;

. Giving of bond to secure performance;

. Reasonable compensation;

. Resignation;

. Removal; and

. Vacancy and appointment of successor.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6029-S.SL.pdf?cite=2020%20c%20303%20§%2016[2020 c 303 § 16]; ]

== 11.98B.900 - Uniformity of application and construction.
In applying and construing this uniform act, consideration must be given to the need to promote uniformity of the law with respect to its subject matter among states that enact it.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6029-S.SL.pdf?cite=2020%20c%20303%20§%2017[2020 c 303 § 17]; ]

== 11.98B.901 - Relation to electronic signatures in global and national commerce act.
This chapter modifies, limits, or supersedes the electronic signatures in global and national commerce act, 15 U.S.C. Sec. 7001 et seq., but does not modify, limit, or supersede section 101(c) of that act (15 U.S.C. Sec. 7001(c)) or authorize electronic delivery of any of the notices described in section 103(b) of that act (15 U.S.C. Sec. 7003(b)).

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6029-S.SL.pdf?cite=2020%20c%20303%20§%2018[2020 c 303 § 18]; ]

== 11.98B.902 - Effective date—2020 c 303.
This act takes effect January 1, 2021.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6029-S.SL.pdf?cite=2020%20c%20303%20§%2020[2020 c 303 § 20]; ]

