= 11.86 - Disclaimer of interests.
:toc:

== 11.86.011 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Beneficiary" means the person entitled, but for the person's disclaimer, to take an interest.

. "Creator of the interest" means a person who establishes, declares, or otherwise creates an interest.

. [Empty]
.. "Date of the transfer" means:

... For an inter vivos transfer, the date of the creation of the interest; or

... For a transfer upon the death of the creator of the interest, the date of the death of the creator.

.. A joint tenancy interest of a deceased joint tenant is deemed to be transferred at the death of the joint tenant rather than at the creation of the joint tenancy.

. "Disclaimant" means a beneficiary who executes a disclaimer on his or her own behalf or a person who executes a disclaimer on behalf of a beneficiary.

. "Disclaimer" means any writing which declines, refuses, renounces, or disclaims any interest that would otherwise be taken by a beneficiary.

. "Interest" includes the whole of any property, real or personal, legal or equitable, or any fractional part, share, or particular portion or specific assets thereof, any vested or contingent interest in any such property, any power to appoint, consume, apply, or expend property, or any other right, power, privilege, or immunity relating to property. "Interest" includes, but is not limited to, an interest created in any of the following manners:

.. By intestate succession;

.. Under a will;

.. Under a trust;

.. By succession to a disclaimed interest;

.. By virtue of an election to take against a will;

.. By creation of a power of appointment;

.. By exercise or nonexercise of a power of appointment;

.. By an inter vivos gift, whether outright or in trust;

.. By surviving the death of a depositor of a trust or P.O.D. account within the meaning of *RCW 30.22.040;

.. Under an insurance or annuity contract;

.. By surviving the death of another joint tenant;

.. Under an employee benefit plan;

.. Under an individual retirement account, annuity, or bond;

.. Under a community property agreement;

.. By surviving the death of a transferor of a transfer on death deed; or

.. Any other interest created by any testamentary or inter vivos instrument or by operation of law.

. "Person" means an individual, corporation, government, governmental subdivision or agency, business trust, estate, trust, partnership, association, or other entity.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1117-S.SL.pdf?cite=2014%20c%2058%20§%2022[2014 c 58 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c34.pdf?cite=1989%20c%2034%20§%201[1989 c 34 § 1]; ]

== 11.86.021 - Disclaimer of interest authorized. (Effective until January 1, 2022.)
. A beneficiary may disclaim an interest in whole or in part, or with reference to specific parts, shares or assets, in the manner provided in RCW 11.86.031.

. Likewise, a beneficiary may so disclaim through an agent or attorney so authorized by written instrument.

. A personal representative, guardian, attorney-in-fact if authorized under a durable power of attorney under chapter 11.125 RCW, or other legal representative of the estate of a minor, incompetent, or deceased beneficiary, may so disclaim on behalf of the beneficiary, with or without court order, if:

.. The legal representative deems the disclaimer to be in the best interests of those interested in the estate of the beneficiary and of those who take the disclaimed interest because of the disclaimer, and not detrimental to the best interests of the beneficiary; and

.. In the case of a guardian, no order has been issued under *RCW 11.92.140 determining that the disclaimer is not in the best interests of the beneficiary.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20402[2016 c 209 § 402]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c34.pdf?cite=1989%20c%2034%20§%202[1989 c 34 § 2]; ]

== 11.86.031 - Contents of disclaimer—Time and filing requirements—Fee.
. The disclaimer must:

.. Be in writing;

.. Be signed by the disclaimant;

.. Identify the interest to be disclaimed; and

.. State the disclaimer and the extent thereof.

. The disclaimer must be delivered or mailed as provided in subsection (3) of this section at any time after the creation of the interest, but in all events by nine months after the latest of:

.. The date the beneficiary attains the age of twenty-one years;

.. The date of the transfer;

.. The date that the beneficiary is finally ascertained and the beneficiary's interest is indefeasibly vested; or

.. December 17, 2010, if the date of the transfer is the date of the death of the creator of the interest and the creator dies after December 31, 2009, and before December 18, 2010.

. The disclaimer shall be mailed by first-class mail, or otherwise delivered, to the creator of the interest, the creator's legal representative, or the holder of the legal title to the property to which the interest relates or, if the creator is dead and there is no legal representative or holder of legal title, to the person having possession of the property.

. If the date of the transfer is the date of the death of the creator of the interest, a copy of the disclaimer may be filed with the clerk of the probate court in which the estate of the creator is, or has been, administered, or, if no probate administration has been commenced, then with the clerk of the court of any county provided by law as the place for probate administration of such person, where it shall be indexed under the name of the decedent in the probate index upon the payment of a fee established under *RCW 36.18.016.

. The disclaimer of an interest in real property may be recorded, but shall constitute notice to all persons only from and after the date of recording. If recorded, a copy of the disclaimer shall be recorded in the office of the auditor in the county or counties where the real property is situated.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5849.SL.pdf?cite=2011%20c%20113%20§%203[2011 c 113 § 3]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1692-S.SL.pdf?cite=1995%20c%20292%20§%204[1995 c 292 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c34.pdf?cite=1989%20c%2034%20§%203[1989 c 34 § 3]; ]

== 11.86.041 - Disposition of disclaimed interest.
. Unless the instrument creating an interest directs to the contrary, the interest disclaimed shall pass as if the beneficiary had died immediately prior to the date of the transfer of the interest. The disclaimer shall relate back to this date for all purposes.

. Unless the beneficiary provides otherwise in the disclaimer, in addition to the interests disclaimed, the beneficiary shall also be deemed to have disclaimed the minimum of all interests in the disclaimed property necessary to make the disclaimer a qualified disclaimer for purposes of section 2518 of the Internal Revenue Code.

. Any future interest taking effect in possession or enjoyment after termination of the interest disclaimed takes effect as if the beneficiary had died prior to the date of the beneficiary's final ascertainment as a beneficiary and the indefeasible vesting of the interest.

. The disclaimer is binding upon the beneficiary and all persons claiming through or under the beneficiary.

. Unless the instrument creating the interest directs to the contrary, a beneficiary whose interest in a devise or bequest under a will has been disclaimed shall be deemed to have died for purposes of RCW 11.12.110.

. In the case of a disclaimer of property over which the disclaimant has any power to direct the beneficial enjoyment of the disclaimed property, the disclaimant shall also be deemed to have disclaimed any power to direct the beneficial enjoyment of the disclaimed property, unless the power is limited by an ascertainable standard relating to the health, education, support, or maintenance of any person as described in section 2041 or 2514 of the Internal Revenue Code and applicable regulations adopted under those sections. This subsection applies unless the disclaimer specifically provides otherwise. This subsection shall not be deemed to otherwise prevent such a disclaimant from acting as trustee or personal representative over disclaimed property.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5197-S.SL.pdf?cite=1999%20c%2043%20§%201[1999 c 43 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5110-S.SL.pdf?cite=1997%20c%20252%20§%2073[1997 c 252 § 73]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1063.SL.pdf?cite=1991%20c%207%20§%201[1991 c 7 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c34.pdf?cite=1989%20c%2034%20§%204[1989 c 34 § 4]; ]

== 11.86.051 - When disclaimer barred—Exception.
. A beneficiary may not disclaim an interest if:

.. The beneficiary has accepted the interest or a benefit thereunder;

.. The beneficiary has assigned, conveyed, encumbered, pledged, or otherwise transferred the interest, or has contracted therefor;

.. The interest has been sold or otherwise disposed of pursuant to judicial process; or

.. The beneficiary has waived the right to disclaim in writing. The written waiver of the right to disclaim also is binding upon all persons claiming through or under the beneficiary.

. Notwithstanding the provisions of subsection (1)(a) through (c) of this section, a beneficiary's receipt of a benefit from property shall not necessarily bar such beneficiary's disclaimer of an interest in the same property when, prior to the date of the transfer of the interest to be disclaimed, the beneficiary already owned an interest in such property in joint tenancy, as community property, or otherwise. Any such receipt, in the absence of clear and convincing evidence to the contrary, shall be presumed to be an enjoyment or use of the interest the beneficiary already owned, and only after such interest and any benefit from such interest have been exhausted, shall the beneficiary be deemed to have received or accepted any part of the interest to be disclaimed.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6138.SL.pdf?cite=2000%20c%2024%20§%201[2000 c 24 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c34.pdf?cite=1989%20c%2034%20§%205[1989 c 34 § 5]; ]

== 11.86.061 - Effect of spendthrift or similar restriction.
A beneficiary may disclaim under this chapter notwithstanding any limitation on the interest of the beneficiary in the nature of a spendthrift provision or similar restriction.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c34.pdf?cite=1989%20c%2034%20§%206[1989 c 34 § 6]; ]

== 11.86.071 - Liability for distribution—Effect of disclaimer.
No legal representative of a creator of the interest, holder of legal title to property an interest in which is disclaimed, or person having possession of the property shall be liable for any otherwise proper distribution or other disposition made without actual knowledge of the disclaimer, or in reliance upon the disclaimer and without actual knowledge that the disclaimer is barred as provided in RCW 11.86.051.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c34.pdf?cite=1989%20c%2034%20§%207[1989 c 34 § 7]; ]

== 11.86.080 - Rights under other statutes or rules not abridged.
This chapter shall not abridge the right of any person, apart from this chapter, under any existing or future statute or rule of law, to disclaim any interest or to assign, convey, release, renounce or otherwise dispose of any interest.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c148.pdf?cite=1973%20c%20148%20§%209[1973 c 148 § 9]; ]

== 11.86.090 - Interests existing on June 7, 1973.
Any interest which exists on June 7, 1973 but which has not then become indefeasibly vested, or the taker of which has not then become finally ascertained, or of the existence of the transfer of which the beneficiary lacks knowledge, may be disclaimed after June 7, 1973 in the manner provided in RCW 11.86.031. However, for the purposes of RCW 11.86.031(2), the date on which the beneficiary first knows of the existence of the transfer shall be deemed to be the date of the transfer.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c34.pdf?cite=1989%20c%2034%20§%208[1989 c 34 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c148.pdf?cite=1973%20c%20148%20§%2010[1973 c 148 § 10]; ]

