= 11.95A - Uniform powers of appointment act.
:toc:

== 11.95A.001 - Short title. (Effective January 1, 2022.)
This chapter may be known and cited as the uniform powers of appointment act.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203101[2021 c 140 § 3101]; ]

== 11.95A.010 - Definitions. (Effective January 1, 2022.)
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Appointee" means a person to which a powerholder makes an appointment of appointive property.

. "Appointive property" means the property or property interest subject to a power of appointment.

. "Blanket-exercise clause" means a clause in an instrument which exercises a power of appointment and is not a specific-exercise clause. The term includes a clause that:

.. Expressly uses the words "any power" in exercising any power of appointment the powerholder has;

.. Expressly uses the words "any property" in appointing any property over which the powerholder has a power of appointment; or

.. Disposes of all property subject to disposition by the powerholder.

. "Donor" means a person that creates a power of appointment.

. "Exclusionary power of appointment" means a power of appointment exercisable in favor of any one or more of the permissible appointees to the exclusion of the other permissible appointees.

. "General power of appointment" means a power of appointment exercisable in favor of the powerholder, the powerholder's estate, a creditor of the powerholder, or a creditor of the powerholder's estate.

. "Gift-in-default clause" means a clause identifying a taker in default of appointment.

. "Impermissible appointee" means a person that is not a permissible appointee.

. "Instrument" means a record.

. "Nongeneral power of appointment" means a power of appointment that is not a general power of appointment.

. "Permissible appointee" means a person in whose favor a powerholder may exercise a power of appointment.

. "Person" means an individual, estate, trust, business or nonprofit entity, public corporation, government or governmental subdivision, agency, or instrumentality, or other legal entity.

. "Power of appointment" means a power that enables a powerholder acting in a nonfiduciary capacity to designate a recipient of an ownership interest in or another power of appointment over the appointive property. The term does not include a power of attorney.

. "Powerholder" means a person in which a donor creates a power of appointment.

. "Presently exercisable power of appointment" means a power of appointment exercisable by the powerholder at the relevant time. The term:

.. Includes a power of appointment not exercisable until the occurrence of a specified event, the satisfaction of an ascertainable standard, or the passage of a specified time only after:

... The occurrence of the specified event;

... The satisfaction of the ascertainable standard; or

... The passage of the specified time; and

.. Does not include a power exercisable only at the powerholder's death.

. "Specific-exercise clause" means a clause in an instrument which specifically refers to and exercises a particular power of appointment.

. "Taker in default of appointment" means a person that takes all or part of the appointive property to the extent the powerholder does not effectively exercise the power of appointment.

. "Terms of the instrument" means the manifestation of the intent of the maker of the instrument regarding the instrument's provisions as expressed in the instrument or as may be established by other evidence that would be admissible in a legal proceeding.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203102[2021 c 140 § 3102]; ]

== 11.95A.020 - Governing law. (Effective January 1, 2022.)
Unless the terms of the instrument creating a power of appointment manifest a contrary intent:

. The creation, revocation, or amendment of the power is governed by the law of the donor's domicile at the time the action is taken; and

. The exercise, release, lapse, or disclaimer of the power, or the revocation or amendment of the exercise, release, lapse, or disclaimer of the power, is governed by the law of the powerholder's domicile at the time the action is taken.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203103[2021 c 140 § 3103]; ]

== 11.95A.030 - Common law and principles of equity supplement. (Effective January 1, 2022.)
The common law and principles of equity supplement this chapter, except to the extent modified by this chapter or law of this state other than this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203104[2021 c 140 § 3104]; ]

== 11.95A.100 - Creation of power of appointment. (Effective January 1, 2022.)
. A power of appointment is created only if:

.. The instrument creating the power:

... Is valid under applicable law; and

... Except as otherwise provided in subsection (2) of this section, transfers the appointive property; and

.. The terms of the instrument creating the power manifest the donor's intent to create in a powerholder a power of appointment over the appointive property exercisable in favor of a permissible appointee.

. Subsection (1)(a)(ii) of this section does not apply to the creation of a power of appointment by the exercise of a power of appointment.

. A power of appointment may not be created in a deceased individual.

. Subject to an applicable rule against perpetuities, a power of appointment may be created in an unborn or unascertained powerholder.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203201[2021 c 140 § 3201]; ]

== 11.95A.110 - Power not transferable. (Effective January 1, 2022.)
A powerholder may not transfer a power of appointment. If a powerholder dies without exercising or releasing a power, the power lapses.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203202[2021 c 140 § 3202]; ]

== 11.95A.120 - Presumption of unlimited authority. (Effective January 1, 2022.)
Subject to RCW 11.95A.140 and 11.95A.350 through 11.95A.375, and unless the terms of the instrument creating a power of appointment manifest a contrary intent, the power is:

. Presently exercisable;

. Exclusionary; and

. Except as otherwise provided in RCW 11.95A.130, general.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203203[2021 c 140 § 3203]; ]

== 11.95A.130 - Presumption of unlimited authority—Exception. (Effective January 1, 2022.)
Unless the terms of the instrument creating a power of appointment manifest a contrary intent, the power is nongeneral if:

. The power is exercisable only at the powerholder's death; and

. The permissible appointees of the power are a defined and limited class that does not include the powerholder's estate, the powerholder's creditors, or the creditors of the powerholder's estate.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203204[2021 c 140 § 3204]; ]

== 11.95A.140 - Rules of classification. (Effective January 1, 2022.)
. In this section, "adverse party" means a person with a substantial beneficial interest in property which would be affected adversely by a powerholder's exercise or nonexercise of a power of appointment in favor of the powerholder, the powerholder's estate, a creditor of the powerholder, or a creditor of the powerholder's estate.

. If a powerholder may exercise a power of appointment only with the consent or joinder of an adverse party, the power is nongeneral.

. If the permissible appointees of a power of appointment are not defined and limited, the power is exclusionary.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203205[2021 c 140 § 3205]; ]

== 11.95A.150 - Power to revoke or amend. (Effective January 1, 2022.)
A donor may revoke or amend a power of appointment only to the extent that:

. The instrument creating the power is revocable by the donor; or

. The donor reserves a power of revocation or amendment in the instrument creating the power of appointment.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203206[2021 c 140 § 3206]; ]

== 11.95A.200 - Requisites for exercise of power of appointment. (Effective January 1, 2022.)
A power of appointment is exercised only:

. If the instrument exercising the power is valid under applicable law;

. If the terms of the instrument exercising the power:

.. Manifest the powerholder's intent to exercise the power; and

.. Subject to RCW 11.95A.230, satisfy the requirements of exercise, if any, imposed by the donor; and

. To the extent the appointment is a permissible exercise of the power.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203301[2021 c 140 § 3301]; ]

== 11.95A.210 - Intent to exercise—Determining intent from residuary clause. (Effective January 1, 2022.)
. In this section:

.. "Residuary clause" does not include a residuary clause containing a blanket-exercise clause or a specific-exercise clause.

.. "Will" includes a codicil and a testamentary instrument that revises another will.

. A residuary clause in a powerholder's will, or a comparable clause in the powerholder's revocable trust, manifests the powerholder's intent to exercise a power of appointment only if:

.. The terms of the instrument containing the residuary clause do not manifest a contrary intent;

.. The power is a general power exercisable in favor of the powerholder's estate;

.. There is no gift-in-default clause or the clause is ineffective; and

.. The powerholder did not release the power.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203302[2021 c 140 § 3302]; ]

== 11.95A.220 - Intent to exercise—After-acquired power. (Effective January 1, 2022.)
Unless the terms of the instrument exercising a power of appointment manifest a contrary intent:

. Except as otherwise provided in subsection (2) of this section, a blanket-exercise clause extends to a power acquired by the powerholder after executing the instrument containing the clause; and

. If the powerholder is also the donor of the power, the clause does not extend to the power unless there is no gift-in-default clause or the gift-in-default clause is ineffective.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203303[2021 c 140 § 3303]; ]

== 11.95A.230 - Substantial compliance with donor-imposed formal requirement. (Effective January 1, 2022.)
A powerholder's substantial compliance with a formal requirement of appointment imposed by the donor, including a requirement that the instrument exercising the power of appointment make reference or specific reference to the power, is sufficient if:

. The powerholder knows of and intends to exercise the power; and

. The powerholder's manner of attempted exercise of the power does not impair a material purpose of the donor in imposing the requirement.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203304[2021 c 140 § 3304]; ]

== 11.95A.240 - Permissible appointment. (Effective January 1, 2022.)
. A powerholder of a general power of appointment that permits appointment to the powerholder or the powerholder's estate may make any appointment, including an appointment in trust or creating a new power of appointment, that the powerholder could make in disposing of the powerholder's own property.

. A powerholder of a general power of appointment that permits appointment only to the creditors of the powerholder or of the powerholder's estate may appoint only to those creditors.

. Unless the terms of the instrument creating a power of appointment manifest a contrary intent, the powerholder of a nongeneral power may:

.. Make an appointment in any form, including an appointment in trust, in favor of a permissible appointee;

.. Create a general power in a permissible appointee;

.. Create a nongeneral power in any person to appoint to one or more of the permissible appointees of the original nongeneral power; or

.. Create a nongeneral power in a permissible appointee to appoint to one or more persons if the permissible appointees of the new nongeneral power include the permissible appointees of the original nongeneral power.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203305[2021 c 140 § 3305]; ]

== 11.95A.250 - Appointment to deceased appointee or permissible appointee's descendant. (Effective January 1, 2022.)
. Subject to RCW 11.12.110 and 11.12.120, an appointment to a deceased appointee is ineffective.

. Unless the terms of the instrument creating a power of appointment manifest a contrary intent, a powerholder of a nongeneral power may exercise the power in favor of, or create a new power of appointment in, a descendant of a deceased permissible appointee whether or not the descendant is described by the donor as a permissible appointee.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203306[2021 c 140 § 3306]; ]

== 11.95A.260 - Impermissible appointment. (Effective January 1, 2022.)
. Except as otherwise provided in RCW 11.95A.250, an exercise of a power of appointment in favor of an impermissible appointee is ineffective.

. An exercise of a power of appointment in favor of a permissible appointee is ineffective to the extent the appointment is a fraud on the power.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203307[2021 c 140 § 3307]; ]

== 11.95A.270 - Selective allocation doctrine. (Effective January 1, 2022.)
If a powerholder exercises a power of appointment in a disposition that also disposes of property the powerholder owns, the owned property and the appointive property must be allocated in the permissible manner that best carries out the powerholder's intent.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203308[2021 c 140 § 3308]; ]

== 11.95A.280 - Capture doctrine—Disposition of ineffectively appointed property under general power. (Effective January 1, 2022.)
To the extent a powerholder of a general power of appointment, other than a power to withdraw property from, revoke, or amend a trust, makes an ineffective appointment:

. The gift-in-default clause controls the disposition of the ineffectively appointed property; or

. If there is no gift-in-default clause or to the extent the clause is ineffective, the ineffectively appointed property:

.. Passes to:

... The powerholder if the powerholder is a permissible appointee and living; or

... If the powerholder is an impermissible appointee or deceased, the powerholder's estate if the estate is a permissible appointee; or

.. If there is no taker under (a) of this subsection, passes under a reversionary interest to the donor or the donor's transferee or successor in interest.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203309[2021 c 140 § 3309]; ]

== 11.95A.290 - Disposition of unappointed property—Released  or unexercised general power. (Effective January 1, 2022.)
To the extent a powerholder releases or fails to exercise a general power of appointment other than a power to withdraw property from, revoke, or amend a trust:

. The gift-in-default clause controls the disposition of the unappointed property; or

. If there is no gift-in-default clause or to the extent the clause is ineffective:

.. Except as otherwise provided in (b) of this subsection, the unappointed property passes to:

... The powerholder if the powerholder is a permissible appointee and living; or

... If the powerholder is an impermissible appointee or deceased, the powerholder's estate if the estate is a permissible appointee; or

.. To the extent the powerholder released the power, or if there is no taker under (a) of this subsection, the unappointed property passes under a reversionary interest to the donor or the donor's transferee or successor in interest.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203310[2021 c 140 § 3310]; ]

== 11.95A.300 - Disposition of unappointed property—Released or unexercised nongeneral power. (Effective January 1, 2022.)
To the extent a powerholder releases, ineffectively exercises, or fails to exercise a nongeneral power of appointment:

. The gift-in-default clause controls the disposition of the unappointed property; or

. If there is no gift-in-default clause or to the extent the clause is ineffective, the unappointed property:

.. Passes to the permissible appointees if:

... The permissible appointees are defined and limited; and

... The terms of the instrument creating the power do not manifest a contrary intent; or

.. If there is no taker under (a) of this subsection, passes under a reversionary interest to the donor or the donor's transferee or successor in interest.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203311[2021 c 140 § 3311]; ]

== 11.95A.310 - Disposition of unappointed property—Partial appointment to taker in default. (Effective January 1, 2022.)
Unless the terms of the instrument creating or exercising a power of appointment manifest a contrary intent, if the powerholder makes a valid partial appointment to a taker in default of appointment, the taker in default of appointment may share fully in unappointed property.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203312[2021 c 140 § 3312]; ]

== 11.95A.320 - Appointment to taker in default. (Effective January 1, 2022.)
If a powerholder makes an appointment to a taker in default of appointment and the appointee would have taken the property in the same manner and with the same conditions under a gift-in-default clause had the property not been appointed, the power of appointment is deemed not to have been exercised and the appointee takes under the clause.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203313[2021 c 140 § 3313]; ]

== 11.95A.330 - Powerholder's authority to revoke or amend exercise. (Effective January 1, 2022.)
A powerholder may revoke or amend an exercise of a power of appointment only to the extent that:

. The powerholder reserves a power of revocation or amendment in the instrument exercising the power of appointment and, if the power is nongeneral, the terms of the instrument creating the power of appointment do not prohibit the reservation; or

. The terms of the instrument creating the power of appointment provide that the exercise is revocable or amendable.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203314[2021 c 140 § 3314]; ]

== 11.95A.340 - Notice of exercise of testamentary power. (Effective January 1, 2022.)
Unless the person holding property subject to a testamentary power of appointment has within six months after the holder's death received written notice that the powerholder's last will has been admitted to probate or an adjudication of testacy has been entered with respect to the powerholder's last will in some jurisdiction, the person may, until the time the notice is received, transfer the property subject to appointment on the basis that the power has not been effectively exercised.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203315[2021 c 140 § 3315]; ]

== 11.95A.350 - Exercise of power in favor of holder—Limitations. (Effective January 1, 2022.)
If the standard governing the exercise of a lifetime or a testamentary power of appointment does not clearly indicate that a broader or more restrictive power of appointment is intended, the holder of the power of appointment may exercise it in his or her favor only for his or her health, education, support, or maintenance as described in section 2041 or 2514 of the Internal Revenue Code and the applicable regulations adopted under the section.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5066-S.SL.pdf?cite=1993%20c%20339%20§%207[1993 c 339 § 7]; ]

== 11.95A.355 - Exercise of power in favor of holder—Disregard of provision conferring absolute or similar power—Power of removal. (Effective January 1, 2022.)
If the holder of a lifetime or testamentary power of appointment may exercise the power in his or her own favor only for his or her health, education, support, or maintenance as described in section 2041 or 2514 of the Internal Revenue Code and the applicable regulations adopted under that section, then a provision of the instrument creating the power of appointment that purports to confer "absolute," "sole," "complete," "conclusive," or a similar discretion shall be disregarded in the exercise of that power in favor of the holder, and that power may then only be exercised reasonably and in accordance with the ascertainable standards set forth in RCW 11.95A.350 and this section. A person who has the right to remove or replace a trustee does not possess nor may the person be deemed to possess, by virtue of having that right, the power of the trustee who is subject to removal or to replacement.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203606[2021 c 140 § 3606]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5066-S.SL.pdf?cite=1993%20c%20339%20§%208[1993 c 339 § 8]; ]

== 11.95A.360 - Exercise of power in favor of holder—Income under marital deduction—Spousal power of appointment. (Effective January 1, 2022.)
Notwithstanding any provision of RCW 11.95A.350 through 11.95A.375 seemingly to the contrary, RCW 11.95A.350 through 11.95A.375 do not limit or restrict the distribution of income of a trust that qualifies or that otherwise could have qualified for the marital deduction under section 2056 or 2523 of the Internal Revenue Code, those Internal Revenue Code sections requiring that all income be distributed to the spouse of the decedent or of the trustor at least annually, whether or not an election was in fact made under section 2056(b)(7) or 2523(f) of the Internal Revenue Code. Further, RCW 11.95A.350 through 11.95A.375 do not limit or restrict the power of a spouse of the trustor or the spouse of the decedent to exercise a power of appointment described in section 2056(b)(5) or 2523(e) of the Internal Revenue Code with respect to that portion of the trust that could otherwise qualify for the marital deduction under either of those Internal Revenue Code sections.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203607[2021 c 140 § 3607]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5066-S.SL.pdf?cite=1993%20c%20339%20§%209[1993 c 339 § 9]; ]

== 11.95A.365 - Exercise of power in favor of holder—Inference of law. (Effective January 1, 2022.)
RCW 11.95A.350 through 11.95A.375 do not raise an inference that the law of this state prior to July 25, 1993, was different than contained in RCW 11.95A.350 through 11.95A.375.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203608[2021 c 140 § 3608]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5066-S.SL.pdf?cite=1993%20c%20339%20§%2010[1993 c 339 § 10]; ]

== 11.95A.370 - Exercise of power in favor of holder—Applicability. (Effective January 1, 2022.)
. [Empty]
.. RCW 11.95A.350 and 11.95A.355 respectively apply to a power of appointment created:

... Under a will, codicil, trust agreement, or declaration of trust, deed, power of attorney, or other instrument executed after July 25, 1993, unless the terms of the instrument refer specifically to RCW 11.95A.350 or 11.95A.355 respectively and provide expressly to the contrary; or

... Under a testamentary trust, trust agreement, or declaration of trust executed before July 25, 1993, unless:

(A) The trust is revoked, or amended to provide otherwise, and the terms of any amendment specifically refer to RCW 11.95A.350 or 11.95A.355, respectively, and provide expressly to the contrary;

(B) All parties in interest, as defined in RCW 11.98.240(3), elect affirmatively, in the manner prescribed in RCW 11.98.240(4), not to be subject to the application of this subsection. The election must be made by the later of September 1, 2000, or three years after the date on which the trust becomes irrevocable; or

(C) A person entitled to judicial proceedings for a declaration of rights or legal relations under RCW 11.96A.080 obtains a judicial determination that the application of this subsection (1)(a)(ii) to the trust is inconsistent with the provisions or purposes of the will or trust.

.. Notwithstanding (a) of this subsection, for the purposes of this section a codicil to a will, an amendment to a trust, or an amendment to another instrument that created the power of appointment in question shall not be deemed to cause that instrument to be executed after July 25, 1993, unless the codicil or amendment clearly shows an intent to have RCW 11.95A.350 or 11.95A.355 apply.

. Notwithstanding subsection (1) of this section, RCW 11.95A.350 through 11.95A.375 shall apply to a power of appointment created under a will, codicil, trust agreement, or declaration of trust, deed, power of attorney, or other instrument executed prior to July 25, 1993, if the person who created the power of appointment had on July 25, 1993, the power to revoke, amend, or modify the instrument creating the power of appointment, unless:

.. The terms of the instrument specifically refer to RCW 11.95A.350 or 11.95A.355 respectively and provide expressly to the contrary; or

.. The person creating the power of appointment was not competent, on July 25, 1993, to revoke, amend, or modify the instrument creating the power of appointment and did not regain his or her competence to revoke, amend, or modify the instrument creating the power of appointment on or before his or her death or before the time at which the instrument could no longer be revoked, amended, or modified by the person.

. For purposes of this section, a reference in an instrument to:

.. RCW 11.95.100 is a reference to RCW 11.95A.350; and

.. RCW 11.95.110 is a reference to RCW 11.95A.355.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203609[2021 c 140 § 3609]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20617[1999 c 42 § 617]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5110-S.SL.pdf?cite=1997%20c%20252%20§%2074[1997 c 252 § 74]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5066-S.SL.pdf?cite=1993%20c%20339%20§%2011[1993 c 339 § 11]; ]

== 11.95A.375 - Exercise of power in favor of holder—Cause of action. (Effective January 1, 2022.)
RCW 11.95A.350 through 11.95A.370 neither create a new cause of action nor impair an existing cause of action that, in either case, relates to a power that was exercised before July 25, 1993. RCW 11.95A.350 through 11.95A.370 neither create a new cause of action nor impair an existing cause of action that in either case relates to a power proscribed, limited, or qualified under RCW 11.95A.350 through 11.95A.370.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203610[2021 c 140 § 3610]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5066-S.SL.pdf?cite=1993%20c%20339%20§%2012[1993 c 339 § 12]; ]

== 11.95A.400 - Disclaimer. (Effective January 1, 2022.)
As provided by chapter 11.86 RCW:

. A powerholder may disclaim all or part of a power of appointment.

. A permissible appointee, appointee, or taker in default of appointment may disclaim all or part of an interest in appointive property.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203401[2021 c 140 § 3401]; ]

== 11.95A.410 - Authority to release. (Effective January 1, 2022.)
A powerholder may release a power of appointment, in whole or in part, except to the extent the terms of the instrument creating the power prevent the release.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203402[2021 c 140 § 3402]; ]

== 11.95A.420 - Method of release. (Effective January 1, 2022.)
A powerholder of a releasable power of appointment may release the power in whole or in part:

. By substantial compliance with a method provided in the terms of the instrument creating the power; or

. If the terms of the instrument creating the power do not provide a method or the method provided in the terms of the instrument is not expressly made exclusive, by a record manifesting the powerholder's intent by clear and convincing evidence.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203403[2021 c 140 § 3403]; ]

== 11.95A.430 - Revocation or amendment of release. (Effective January 1, 2022.)
A powerholder may revoke or amend a release of a power of appointment only to the extent that:

. The instrument of release is revocable by the powerholder; or

. The powerholder reserves a power of revocation or amendment in the instrument of release.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203404[2021 c 140 § 3404]; ]

== 11.95A.440 - Power to contract—Presently exercisable power of appointment. (Effective January 1, 2022.)
A powerholder of a presently exercisable power of appointment may contract:

. Not to exercise the power; or

. To exercise the power if the contract when made does not confer a benefit on an impermissible appointee.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203405[2021 c 140 § 3405]; ]

== 11.95A.450 - Power to contract—Power of appointment not presently exercisable. (Effective January 1, 2022.)
A powerholder of a power of appointment that is not presently exercisable may contract to exercise or not to exercise the power only if the powerholder:

. Is also the donor of the power; and

. Has reserved the power in a revocable trust.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203406[2021 c 140 § 3406]; ]

== 11.95A.460 - Remedy for breach of contract to appoint or not to appoint. (Effective January 1, 2022.)
The remedy for a powerholder's breach of a contract to appoint or not to appoint appointive property is limited to damages payable out of the appointive property or, if appropriate, specific performance of the contract.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203407[2021 c 140 § 3407]; ]

== 11.95A.500 - Creditor claims—General power created by powerholder. (Effective January 1, 2022.)
. In this section, "power of appointment created by the powerholder" includes a power of appointment created in a transfer by another person to the extent the powerholder contributed value to the transfer.

. Appointive property subject to a general power of appointment created by the powerholder is subject to a claim of a creditor of the powerholder or of the powerholder's estate to the extent provided in chapter 19.40 RCW.

. Subject to subsection (2) of this section, appointive property subject to a general power of appointment created by the powerholder is not subject to a claim of a creditor of the powerholder or the powerholder's estate to the extent the powerholder irrevocably appointed the property in favor of a person other than the powerholder or the powerholder's estate.

. Subject to subsections (2) and (3) of this section, and notwithstanding the presence of a spendthrift provision or whether the claim arose before or after the creation of the power of appointment, appointive property subject to a general power of appointment created by the powerholder is subject to a claim of a creditor of:

.. The powerholder, to the same extent as if the powerholder owned the appointive property, if the power is presently exercisable; and

.. The powerholder's estate, to the extent the estate is insufficient to satisfy the claim and subject to the right of a decedent to direct the source from which liabilities are paid, if the power is exercisable at the powerholder's death.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203501[2021 c 140 § 3501]; ]

== 11.95A.510 - Creditor claims—General power not created by powerholder. (Effective January 1, 2022.)
. Except as otherwise provided in subsection (2) of this section, appointive property subject to a general power of appointment created by a person other than the powerholder is subject to a claim of a creditor of:

.. The powerholder, to the extent the powerholder's property is insufficient, if the power is presently exercisable; and

.. The powerholder's estate, to the extent the estate is insufficient, subject to the right of a decedent to direct the source from which liabilities are paid.

. Subject to RCW 11.95A.530(3), a power of appointment created by a person other than the powerholder which is subject to an ascertainable standard relating to an individual's health, education, support, or maintenance within the meaning of 26 U.S.C. Sec. 2041(b)(1)(A) or 26 U.S.C. Sec. 2514(c)(1), on January 1, 2022, is treated for purposes of RCW 11.95A.500 through 11.95A.530 as a nongeneral power.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203502[2021 c 140 § 3502]; ]

== 11.95A.520 - Power to withdraw. (Effective January 1, 2022.)
. For purposes of RCW 11.95A.500 through 11.95A.530, and except as otherwise provided in subsection (2) of this section, a power to withdraw property from a trust is treated, during the time the power may be exercised, as a presently exercisable general power of appointment to the extent of the property subject to the power to withdraw.

. On the lapse, release, or waiver of a power to withdraw property from a trust, the power is treated as a presently exercisable general power of appointment only to the extent the value of the property affected by the lapse, release, or waiver exceeds the greater of the amount specified in 26 U.S.C. Sec. 2041(b)(2) and 26 U.S.C. Sec. 2514(e) or the amount specified in 26 U.S.C. Sec. 2503(b), on January 1, 2022.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203503[2021 c 140 § 3503]; ]

== 11.95A.530 - Creditor claims—Nongeneral power. (Effective January 1, 2022.)
. Except as otherwise provided in subsections (2) and (3) of this section, appointive property subject to a nongeneral power of appointment is exempt from a claim of a creditor of the powerholder or the powerholder's estate.

. Appointive property subject to a nongeneral power of appointment is subject to a claim of a creditor of the powerholder or the powerholder's estate to the extent that the powerholder owned the property and, reserving the nongeneral power, transferred the property in violation of chapter 19.40 RCW.

. If the initial gift in default of appointment is to the powerholder or the powerholder's estate, a nongeneral power of appointment is treated for purposes of this section and RCW 11.95A.500 through 11.95A.520 as a general power.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203504[2021 c 140 § 3504]; ]

== 11.95A.900 - Uniformity of application and construction. (Effective January 1, 2022.)
In applying and construing this uniform act, consideration must be given to the need to promote uniformity of the law with respect to its subject matter among states that enact it.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203601[2021 c 140 § 3601]; ]

== 11.95A.901 - Relation to electronic signatures in global and national commerce act. (Effective January 1, 2022.)
This chapter modifies, limits, or supersedes the electronic signatures in global and national commerce act, 15 U.S.C. Sec. 7001 et seq., but does not modify, limit, or supersede section 101(c) of that act, 15 U.S.C. Sec. 7001(c), or authorize electronic delivery of any of the notices described in section 103(b) of that act, 15 U.S.C. Sec. 7003(b).

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203602[2021 c 140 § 3602]; ]

== 11.95A.902 - Application—Existing relationships. (Effective January 1, 2022.)
. Except as otherwise provided in this chapter, on and after January 1, 2022:

.. This chapter applies to a power of appointment created before, on, or after January 1, 2022;

.. This chapter applies to a judicial proceeding concerning a power of appointment commenced on or after January 1, 2022;

.. This chapter applies to a judicial proceeding concerning a power of appointment commenced before January 1, 2022, unless the court finds that application of a particular provision of this chapter would interfere substantially with the effective conduct of the judicial proceeding or prejudice a right of a party, in which case the particular provision of this chapter does not apply and the superseded law applies;

.. A rule of construction or presumption provided in this chapter applies to an instrument executed before January 1, 2022, unless there is a clear indication of a contrary intent in the terms of the instrument; and

.. Except as otherwise provided in (a) through (d) of this subsection, an action done before January 1, 2022, is not affected by this chapter.

. If a right is acquired, extinguished, or barred on the expiration of a prescribed period that commenced under law of this state other than this chapter before January 1, 2022, the law continues to apply to the right.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203603[2021 c 140 § 3603]; ]

== 11.95A.903 - Effective date—2021 c 140 §§ 3101-3614.
Sections 3101 through 3614 of this act take effect January 1, 2022.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%203616[2021 c 140 § 3616]; ]

