= 11.05A - Uniform simultaneous death act.
:toc:

== 11.05A.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Co-owners with right of survivorship" includes joint tenants, tenants by the entireties, and other co-owners of property or accounts held under circumstances that entitle one or more to the whole of the property or account on the death of the other or others.

. "Governing instrument" means a deed, will, trust, insurance or annuity policy, account with pay on death designation, pension, profit-sharing, retirement, or similar benefit plan, instrument creating or exercising a power of appointment or a power of attorney, or a dispositive, appointive, or nominative instrument of any similar type.

. "Payor" means a trustee, insurer, business entity, employer, government, governmental agency, subdivision, or instrumentality, or any other person authorized or obligated by law or a governing instrument to make payments.

. "POD" means pay on death.

. "TOD" means transfer on death.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2236.SL.pdf?cite=2007%20c%20475%20§%207[2007 c 475 § 7]; ]

== 11.05A.020 - Minimum survival requirement—Probate code.
Except as provided in RCW 11.05A.060 and except for the purposes of the uniform TOD security registration act, if the title to property, the devolution of property, the right to elect an interest in property, or the right to exempt property, homestead, or family allowance depends upon an individual's survivorship of the death of another individual, an individual who is not established by clear and convincing evidence to have survived the other individual by one hundred twenty hours is deemed to have predeceased the other individual. This section does not apply if its application would result in a taking of intestate estate by the state.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2236.SL.pdf?cite=2007%20c%20475%20§%208[2007 c 475 § 8]; ]

== 11.05A.030 - Minimum survival requirement—Governing instruments.
Except as provided in RCW 11.05A.060 and except for a security registered in beneficiary form (TOD) under the Uniform TOD Security Registration Act, for purposes of a provision of a governing instrument that relates to an individual surviving an event, including the death of another individual, an individual who is not established by clear and convincing evidence to have survived the event by one hundred twenty hours is deemed to have predeceased the event.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2236.SL.pdf?cite=2007%20c%20475%20§%209[2007 c 475 § 9]; ]

== 11.05A.040 - Minimum survival requirement—Co-owners.
Except as provided in RCW 11.05A.060, if (1) it is not established by clear and convincing evidence that one of two co-owners with right of survivorship survived the other co-owner by one hundred twenty hours, one-half of the property passes as if one had survived by one hundred twenty hours and one-half as if the other had survived by one hundred twenty hours, and (2) there are more than two co-owners and it is not established by clear and convincing evidence that at least one of them survived the others by one hundred twenty hours, the property passes in the proportion that one bears to the whole number of co-owners.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2236.SL.pdf?cite=2007%20c%20475%20§%2010[2007 c 475 § 10]; ]

== 11.05A.050 - Evidence of death or status.
In addition to the rules of evidence in courts of general jurisdiction, the following rules relating to a determination of death and status apply:

. Death occurs when an individual is determined to be dead by the attending physician, county coroner, or county medical officer.

. A certified or authenticated copy of a death certificate purporting to be issued by an official or agency of the place where the death purportedly occurred is prima facie evidence of the fact, place, date, and time of death and the identity of the decedent.

. A certified or authenticated copy of any record or report of a governmental agency, domestic or foreign, that an individual is missing, detained, dead, or alive is prima facie evidence of the status and of the dates, circumstances, and places disclosed by the record or report.

. In the absence of prima facie evidence of death under subsection (2) or (3) of this section, the fact of death may be established by clear and convincing evidence, including circumstantial evidence.

. An individual whose death is not established under this section who is absent for a continuous period of seven years, during which he or she has not been heard from, and whose absence is not satisfactorily explained after diligent search or inquiry, is presumed to be dead. His or her death is presumed to have occurred at the end of the period unless there is sufficient evidence for determining that death occurred earlier.

. In the absence of evidence disputing the time of death stipulated on a document described in subsection (2) or (3) of this section, a document described in subsection (2) or (3) of this section that stipulates a time of death one hundred twenty hours or more after the time of death of another individual, however the time of death of the other individual is determined, establishes by clear and convincing evidence that the individual survived the other individual by one hundred twenty hours.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2236.SL.pdf?cite=2007%20c%20475%20§%2011[2007 c 475 § 11]; ]

== 11.05A.060 - Exceptions.
This chapter does not apply if:

. The governing instrument contains language dealing explicitly with simultaneous deaths or deaths in a common disaster and that language is operable under the facts of the case;

. The governing instrument expressly indicates that an individual is not required to survive an event, including the death of another individual, by any specified period or expressly requires the individual to survive the event for a stated period;

. The imposition of a one hundred twenty-hour requirement of survival would cause a nonvested property interest or a power of appointment to be invalid under RCW 11.98.130 through 11.98.160; or

. The application of this chapter to multiple governing instruments would result in an unintended failure or duplication of a disposition.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2236.SL.pdf?cite=2007%20c%20475%20§%2012[2007 c 475 § 12]; ]

== 11.05A.070 - Liability.
. Protection of Payors and Other Third Parties.

.. A payor or other third party is not liable for having made a payment or transferred an item of property or any other benefit to a person designated in a governing instrument who, under this chapter, is not entitled to the payment or item of property, or for having taken any other action in good faith reliance on the person's apparent entitlement under the terms of the governing instrument, before the payor or other third party received written notice of a claimed lack of entitlement under this chapter. A payor or other third party is liable for a payment made or other action taken after the payor or other third party received written notice of a claimed lack of entitlement under this chapter.

.. Written notice of a claimed lack of entitlement under (a) of this subsection must be mailed to the payor's or other third party's main office or home by registered or certified mail, return receipt requested, or served upon the payor or other third party in the same manner as a summons in a civil action. Upon receipt of written notice of a claimed lack of entitlement under this chapter, a payor or other third party may pay any amount owed or transfer or deposit any item of property held by it to or with the court having jurisdiction of the probate proceedings relating to the decedent's estate, or if no proceedings have been commenced, to or with the court having jurisdiction of probate proceedings relating to decedents' estates located in the county of the decedent's residence. The court shall hold the funds or item of property and, upon its determination under this chapter, shall order disbursement in accordance with the determination. Payments, transfers, or deposits made to or with the court discharge the payor or other third party from all claims for the value of amounts paid to or items of property transferred to or deposited with the court.

. Protection of Bona Fide Purchasers—Personal Liability of Recipient.

.. A person who purchases property for value and without notice, or who receives a payment or other item of property in partial or full satisfaction of a legally enforceable obligation, is neither obligated under this chapter to return the payment, item of property, or benefit nor liable under this chapter for the amount of the payment or the value of the item of property or benefit. But a person who, not for value, receives a payment, item of property, or any other benefit to which the person is not entitled under this chapter is obligated to return the payment, item of property, or benefit, or is personally liable for the amount of the payment or the value of the item of property or benefit, to the person who is entitled to it under this chapter.

.. If this chapter or any part of this chapter is preempted by federal law with respect to a payment, an item of property, or any other benefit covered by this chapter, a person who, not for value, receives the payment, item of property, or any other benefit to which the person is not entitled under this chapter is obligated to return the payment, item of property, or benefit, or is personally liable for the amount of the payment or the value of the item of property or benefit, to the person who would have been entitled to it were this chapter or part of this chapter not preempted.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2236.SL.pdf?cite=2007%20c%20475%20§%2013[2007 c 475 § 13]; ]

== 11.05A.900 - Application—Construction.
This chapter shall be applied and construed to effectuate its general purpose to make uniform the law with respect to the subject of this chapter among states enacting it.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2236.SL.pdf?cite=2007%20c%20475%20§%2014[2007 c 475 § 14]; ]

== 11.05A.901 - Short title.
This chapter may be cited as the uniform simultaneous death act.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2236.SL.pdf?cite=2007%20c%20475%20§%2015[2007 c 475 § 15]; ]

== 11.05A.904 - Application.
On July 22, 2007:

. An act done before July 22, 2007, in any proceeding and any accrued right is not impaired by this chapter. If a right is acquired, extinguished, or barred upon the expiration of a prescribed period of time that has commenced to run by the provisions of any statute before July 22, 2007, the provisions remain in force with respect to that right; and

. Any rule of construction or presumption provided in this chapter applies to instruments executed and multiple-party accounts opened before July 22, 2007, unless there is a clear indication of a contrary intent.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2236.SL.pdf?cite=2007%20c%20475%20§%2018[2007 c 475 § 18]; ]

