= 11.99 - Construction.
:toc:

== 11.99.010 - Effective date of title.
This title shall take effect and be in force on and after the first day of July, 1967; except that sections 11.44.055, 11.44.065, 11.44.070 and 11.44.080 shall take effect on July 1, 1965, and the repeal of the following acts or parts of acts as listed in section 11.99.015 shall also take effect on July 1, 1965, to wit: In subsection (10), section 1444, Code of 1881; in subsection (47), section 95, chapter 156, Laws of 1917; in subsection (48), section 1, chapter 23, Laws of 1919; in subsection (64), section 1, chapter 112, Laws of 1929; in subsection (66), section 123, chapter 180, Laws of 1935; in subsection (71), section 8, chapter 202, Laws of 1939; and in subsection (111), section 83.16.040, chapter 15, Laws of 1961. Except as above provided the procedures herein prescribed shall govern all proceedings in probate brought after the effective date of the title and, also, all further procedure and proceedings in probate then pending, except to the extent that in the opinion of the court their application in particular proceedings or part thereof would not be feasible or would work injustice, in which event the former procedure shall apply.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.99.010[1965 c 145 § 11.99.010]; ]

== 11.99.013 - Headings not part of law.
Title headings, chapter headings, and section or subsection headings, as used in this title do not constitute any part of the law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.99.013[1965 c 145 § 11.99.013]; ]

== 11.99.015 - Repeal.
See 1965 c 145 s 11.99.015.

[ ]

== 11.99.020 - Savings clause—Rights not affected.
No act done in any proceeding commenced before this title takes effect and no accrued right shall be impaired by its provisions. When a right is acquired, extinguished or barred upon the expiration of a prescribed period of time which has commenced to run by the provisions of any statute in force before this title takes effect, such provisions shall remain in force and be deemed a part of this code with respect to such right.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.99.020[1965 c 145 § 11.99.020]; ]

