= 11.12 - Wills.
:toc:

== 11.12.010 - Who may make a will.
Any person of sound mind who has attained the age of eighteen years may, by last will, devise all his or her estate, both real and personal.

All wills executed subsequent to September 16, 1940, and which meet the requirements of this section are hereby validated and shall have all the force and effect of wills executed subsequent to the taking effect of this section.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c17.pdf?cite=1970%20ex.s.%20c%2017%20§%203[1970 ex.s. c 17 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.12.010[1965 c 145 § 11.12.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c193.pdf?cite=1943%20c%20193%20§%201[1943 c 193 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%2024[1917 c 156 § 24]; Rem. Supp. 1943 § 1394; prior: Code 1881 § 1318; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20207%20§%2051[1863 p 207 § 51]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1860%20p%20169%20§%2018[1860 p 169 § 18]; ]

== 11.12.020 - Requisites of wills—Foreign wills.
. Every will shall be in writing signed by the testator or by some other person under the testator's direction in the testator's presence, and shall be attested by two or more competent witnesses, by subscribing their names to the will, or by signing an affidavit that complies with RCW 11.20.020(2), while in the presence of the testator and at the testator's direction or request: PROVIDED, That a last will and testament, executed in the mode prescribed by the law of the place where executed or of the testator's domicile, either at the time of the will's execution or at the time of the testator's death, shall be deemed to be legally executed, and shall be of the same force and effect as if executed in the mode prescribed by the laws of this state.

. This section shall be applied to all wills, whenever executed, including those subject to pending probate proceedings.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c79.pdf?cite=1990%20c%2079%20§%201[1990 c 79 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.12.020[1965 c 145 § 11.12.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c21.pdf?cite=1929%20c%2021%20§%201[1929 c 21 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%2025[1917 c 156 § 25]; RRS § 1395; prior: Code 1881 § 1319; 1863 p 207 §§ 53, 54; 1860 p 170 §§ 20, 21. FORMER PART OF SECTION; re nuncupative wills, now codified as RCW  11.12.025; ]

== 11.12.025 - Nuncupative wills.
Nothing contained in this chapter shall prevent any member of the armed forces of the United States or person employed on a vessel of the United States merchant marine from disposing of his wages or personal property, or prevent any person competent to make a will from disposing of his or her personal property of the value of not to exceed one thousand dollars, by nuncupative will if the same be proved by two witnesses who were present at the making thereof, and it be proven that the testator, at the time of pronouncing the same, did bid some person present to bear witness that such was his will, or to that effect, and that such nuncupative will was made at the time of the last sickness of the testator, but no proof of any nuncupative will shall be received unless it be offered within six months after the speaking of the testamentary words, nor unless the words or the substance thereof be first committed to writing, and in all cases a citation be issued to the widow and/or heirs at law of the deceased that they may contest the will, and no real estate shall be devised by a nuncupative will.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.12.025[1965 c 145 § 11.12.025]; ]

== 11.12.030 - Signature of testator at his or her direction—Signature by mark.
Every person who shall sign the testator's or testatrix's name to any will by his or her direction shall subscribe his or her own name to such will and state that he or she subscribed the testator's name at his or her request: PROVIDED, That such signing and statement shall not be required if the testator shall evidence the approval of the signature so made at his or her request by making his or her mark on the will.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202011[2010 c 8 § 2011]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.12.030[1965 c 145 § 11.12.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1927c91.pdf?cite=1927%20c%2091%20§%201[1927 c 91 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%2027[1917 c 156 § 27]; RRS § 1397; prior: Code 1881 § 1320; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20207%20§%2054[1863 p 207 § 54]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1860%20p%20170%20§%2021[1860 p 170 § 21]; ]

== 11.12.040 - Revocation of will—How effected—Effect on codicils.
. A will, or any part thereof, can be revoked:

.. By a subsequent will that revokes, or partially revokes, the prior will expressly or by inconsistency; or

.. By being burnt, torn, canceled, obliterated, or destroyed, with the intent and for the purpose of revoking the same, by the testator or by another person in the presence and by the direction of the testator. If such act is done by any person other than the testator, the direction of the testator and the facts of such injury or destruction must be proved by two witnesses.

. Revocation of a will in its entirety revokes its codicils, unless revocation of a codicil would be contrary to the testator's intent.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2270-S.SL.pdf?cite=1994%20c%20221%20§%2012[1994 c 221 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.12.040[1965 c 145 § 11.12.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%2028[1917 c 156 § 28]; RRS § 1398; prior: Code 1881 § 1321; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20207%20§%2055[1863 p 207 § 55]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1860%20p%20170%20§%2022[1860 p 170 § 22]; ]

== 11.12.051 - Dissolution, invalidation, or termination of marriage or domestic partnership.
. If, after making a will, the testator's marriage or domestic partnership is dissolved, invalidated, or terminated, all provisions in the will in favor of or granting any interest or power to the testator's former spouse or former domestic partner are revoked, unless the will expressly provides otherwise. Provisions affected by this section must be interpreted, and property affected passes, as if the former spouse or former domestic partner failed to survive the testator, having died at the time of entry of the decree of dissolution or declaration of invalidity. Provisions revoked by this section are revived by the testator's remarriage to the former spouse or reregistration of the domestic partnership with the former domestic partner. Revocation of certain nonprobate transfers is provided under RCW 11.07.010.

. This section is remedial in nature and applies to decrees of dissolution and declarations of invalidity entered before, on, or after January 1, 1995.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3104-S2.SL.pdf?cite=2008%20c%206%20§%20910[2008 c 6 § 910]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2270-S.SL.pdf?cite=1994%20c%20221%20§%2011[1994 c 221 § 11]; ]

== 11.12.060 - Agreement to convey does not revoke.
A bond, covenant, or agreement made for a valuable consideration by a testator to convey any property, devised or bequeathed in any last will previously made, shall not be deemed a revocation of such previous devise or bequest, but such property shall pass by the devise or bequest, subject to the same remedies on such bond, covenant, or agreement, for specific performance or otherwise, against devisees or legatees, as might be had by law against the heirs of the testator or his or her next of kin, if the same had descended to him or her.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202012[2010 c 8 § 2012]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.12.060[1965 c 145 § 11.12.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%2030[1917 c 156 § 30]; RRS § 1400; prior: Code 1881 § 1323; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20208%20§%2058[1863 p 208 § 58]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1860%20p%20170%20§%2025[1860 p 170 § 25]; ]

== 11.12.070 - Devise or bequeathal of property subject to encumbrance.
When any real or personal property subject to a mortgage is specifically devised, the devisee shall take such property so devised subject to such mortgage unless the will provides that such mortgage be otherwise paid. The term "mortgage" as used in this section shall not include a pledge of personal property.

A charge or encumbrance upon any real or personal estate for the purpose of securing the payment of money, or the performance of any covenant or agreement, shall not be deemed a revocation of any will relating to the same estate, previously executed. The devises and legacies therein contained shall pass and take effect, subject to such charge or encumbrance.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.12.070[1965 c 145 § 11.12.070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c205.pdf?cite=1955%20c%20205%20§%202[1955 c 205 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%2031[1917 c 156 § 31]; RRS § 1401; prior: Code 1881 § 1324; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1860%20p%20170%20§%2026[1860 p 170 § 26]; ]

== 11.12.080 - Revocation of later will or codicil—Effect—Evidence.
. If, after making any will, the testator shall execute a later will that wholly revokes the former will, the destruction, cancellation, or revocation of the later will shall not revive the former will, unless it was the testator's intention to revive it.

. Revocation of a codicil shall revive a prior will or part of a prior will that the codicil would have revoked had it remained in effect at the death of the testator, unless it was the testator's intention not to revive the prior will or part.

. Evidence that revival was or was not intended includes, in addition to a writing by which the later will or codicil is revoked, the circumstances of the revocation or contemporary or subsequent declarations of the testator.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2270-S.SL.pdf?cite=1994%20c%20221%20§%2013[1994 c 221 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.12.080[1965 c 145 § 11.12.080]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%2035[1917 c 156 § 35]; RRS § 1405; prior: Code 1881 § 1328; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20208%20§%2063[1863 p 208 § 63]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1860%20p%20171%20§%2030[1860 p 171 § 30]; ]

== 11.12.091 - Omitted child.
. If a will fails to name or provide for a child of the decedent who is born or adopted by the decedent after the will's execution and who survives the decedent, referred to in this section as an "omitted child," the child must receive a portion of the decedent's estate as provided in subsection (3) of this section, unless it appears either from the will or from other clear and convincing evidence that the failure was intentional.

. In determining whether an omitted child has been named or provided for, the following rules apply:

.. A child identified in a will by name is considered named whether identified as a child or in any other manner.

.. A reference in a will to a class described as the children, descendants, or issue of the decedent who are born after the execution of the will, or words of similar import, constitutes a naming of a person who falls within the class. A reference to another class, such as a decedent's heirs or family, does not constitute such a naming.

.. A nominal interest in an estate does not constitute a provision for a child receiving the interest.

. The omitted child must receive an amount equal in value to that which the child would have received under RCW 11.04.015 if the decedent had died intestate, unless the court determines on the basis of clear and convincing evidence that a smaller share, including no share at all, is more in keeping with the decedent's intent. In making the determination, the court may consider, among other things, the various elements of the decedent's dispositive scheme, provisions for the omitted child outside the decedent's will, provisions for the decedent's other children under the will and otherwise, and provisions for the omitted child's other parent under the will and otherwise.

. In satisfying a share provided by this section, the bequests made by the will abate as provided in chapter 11.10 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2270-S.SL.pdf?cite=1994%20c%20221%20§%209[1994 c 221 § 9]; ]

== 11.12.095 - Omitted spouse or omitted domestic partner.
. If a will fails to name or provide for a spouse or domestic partner of the decedent whom the decedent marries or enters into a domestic partnership after the will's execution and who survives the decedent, referred to in this section as an "omitted spouse" or "omitted domestic partner," the spouse or domestic partner must receive a portion of the decedent's estate as provided in subsection (3) of this section, unless it appears either from the will or from other clear and convincing evidence that the failure was intentional.

. In determining whether an omitted spouse or omitted domestic partner has been named or provided for, the following rules apply:

.. A spouse or domestic partner identified in a will by name is considered named whether identified as a spouse or domestic partner or in any other manner.

.. A reference in a will to the decedent's future spouse or spouses or future domestic partner or partners, or words of similar import, constitutes a naming of a spouse or domestic partner whom the decedent later marries or with whom the decedent enters into a domestic partnership. A reference to another class such as the decedent's heirs or family does not constitute a naming of a spouse or domestic partner who falls within the class.

.. A nominal interest in an estate does not constitute a provision for a spouse or domestic partner receiving the interest.

. The omitted spouse or omitted domestic partner must receive an amount equal in value to that which the spouse or domestic partner would have received under RCW 11.04.015 if the decedent had died intestate, unless the court determines on the basis of clear and convincing evidence that a smaller share, including no share at all, is more in keeping with the decedent's intent. In making the determination the court may consider, among other things, the spouse's or domestic partner's property interests under applicable community property or quasi-community property laws, the various elements of the decedent's dispositive scheme, and a marriage settlement or settlement in a domestic partnership or other provision and provisions for the omitted spouse or omitted domestic partner outside the decedent's will.

. In satisfying a share provided by this section, the bequests made by the will abate as provided in chapter 11.10 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3104-S2.SL.pdf?cite=2008%20c%206%20§%20911[2008 c 6 § 911]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2270-S.SL.pdf?cite=1994%20c%20221%20§%2010[1994 c 221 § 10]; ]

== 11.12.110 - Death of grandparent's issue before grantor.
Unless otherwise provided, when any property shall be given under a will, or under a trust of which the decedent is a grantor and which by its terms becomes irrevocable upon or before the grantor's death, to any issue of a grandparent of the decedent and that issue dies before the decedent, or dies before that issue's interest is no longer subject to a contingency, leaving descendants who survive the decedent, those descendants shall take that property as the predeceased issue would have done if the predeceased issue had survived the decedent. If those descendants are all in the same degree of kinship to the predeceased issue they shall take equally or, if of unequal degree, then those of more remote degree shall take by representation with respect to the predeceased issue.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1125.SL.pdf?cite=2005%20c%2097%20§%202[2005 c 97 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2270-S.SL.pdf?cite=1994%20c%20221%20§%2014[1994 c 221 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.12.110[1965 c 145 § 11.12.110]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c44.pdf?cite=1947%20c%2044%20§%201[1947 c 44 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%2034[1917 c 156 § 34]; Rem. Supp. 1947 § 1404; prior: Code 1881 § 1327; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20208%20§%2062[1863 p 208 § 62]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1860%20p%20171%20§%2029[1860 p 171 § 29]; ]

== 11.12.120 - Lapsed gift—Procedure and proof.
. If a will makes a gift to a person on the condition that the person survive the testator and the person does not survive the testator, then, unless otherwise provided, the gift lapses and falls into the residue of the estate to be distributed under the residuary clause of the will, if any, but otherwise according to the laws of descent and distribution.

. If the will gives the residue to two or more persons, the share of a person who does not survive the testator passes, unless otherwise provided, and subject to RCW 11.12.110, to the other person or persons receiving the residue, in proportion to the interest of each in the remaining part of the residue.

. The personal representative of the testator, a person who would be affected by the lapse or distribution of a gift under this section, or a guardian ad litem or other representative appointed to represent the interests of a person so affected may petition the court for a determination under this section, and the petition must be heard under the procedures of chapter 11.96A RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20604[1999 c 42 § 604]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2270-S.SL.pdf?cite=1994%20c%20221%20§%2015[1994 c 221 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c117.pdf?cite=1974%20ex.s.%20c%20117%20§%2051[1974 ex.s. c 117 § 51]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.12.120[1965 c 145 § 11.12.120]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c151.pdf?cite=1937%20c%20151%20§%201[1937 c 151 § 1]; RRS § 1404-1; ]

== 11.12.160 - Interested witness—Effect on will.
. An interested witness to a will is one who would receive a gift under the will.

. A will or any of its provisions is not invalid because it is signed by an interested witness. Unless there are at least two other subscribing witnesses to the will who are not interested witnesses, the fact that the will makes a gift to a subscribing witness creates a rebuttable presumption that the witness procured the gift by duress, menace, fraud, or undue influence.

. If the presumption established under subsection (2) of this section applies and the interested witness fails to rebut it, the interested witness shall take so much of the gift as does not exceed the share of the estate that would be distributed to the witness if the will were not established.

. The presumption established under subsection (2) of this section has no effect other than that stated in subsection (3) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2270-S.SL.pdf?cite=1994%20c%20221%20§%2016[1994 c 221 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.12.160[1965 c 145 § 11.12.160]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%2038[1917 c 156 § 38]; RRS § 1408; prior: Code 1881 § 1331; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20209%20§%2067[1863 p 209 § 67]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1860%20p%20171%20§%2034[1860 p 171 § 34]; ]

== 11.12.170 - Devise of land, what passes.
Every devise of land in any will shall be construed to convey all the estate of the devisor therein which he or she could lawfully devise, unless it shall clearly appear by the will that he or she intended to convey a less estate.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202013[2010 c 8 § 2013]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.12.170[1965 c 145 § 11.12.170]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%2039[1917 c 156 § 39]; RRS § 1409; prior: Code 1881 § 1332; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20209%20§%2069[1863 p 209 § 69]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1860%20p%20172%20§%2036[1860 p 172 § 36]; ]

== 11.12.180 - Rule in Shelley's Case abolished—Future distribution or interest to heirs.
The Rule in Shelley's Case is abolished as a rule of law and as a rule of construction. If an applicable statute or a governing instrument calls for a future distribution to or creates a future interest in a designated individual's "heirs," "heirs at law," "next of kin," "relatives," or "family," or language of similar import, the property passes to those persons, including the state under chapter 11.08 RCW, that would succeed to the designated individual's estate under chapter 11.04 RCW. The property must pass to those persons as if the designated individual had died when the distribution or transfer of the future interest was to take effect in possession or enjoyment. For purposes of this section and RCW 11.12.185, the designated individual's surviving spouse or surviving domestic partner is deemed to be an heir, regardless of whether the surviving spouse or surviving domestic partner has remarried or entered into a subsequent domestic partnership.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3104-S2.SL.pdf?cite=2008%20c%206%20§%20912[2008 c 6 § 912]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2270-S.SL.pdf?cite=1994%20c%20221%20§%2017[1994 c 221 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.12.180[1965 c 145 § 11.12.180]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%2040[1917 c 156 § 40]; RRS § 1410; prior: Code 1881 § 1333; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20210%20§%2070[1863 p 210 § 70]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1860%20p%20172%20§%2037[1860 p 172 § 37]; ]

== 11.12.185 - Doctrine of Worthier Title abolished—Exception.
The Doctrine of Worthier Title is abolished as a rule of law and as a rule of construction. However, the Doctrine of Worthier Title is preserved as a rule of construction if:

. A grantor has established in inter vivos trust of real property;

. The grantor has expressly reserved a reversion to himself or herself; and

. The words "heirs" or "heirs at law" are used by the grantor to describe the quality of the grantor's title in the reversion as an estate in fee simple in the event that the property reverts to the grantor.

In all other cases, language in a governing instrument describing the beneficiaries of a donative disposition as the transferor's "heirs," "heirs at law," "next of kin," "distributees," "relatives," or "family," or language of similar import, does not create or presumptively create a reversionary interest in the transferor.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2270-S.SL.pdf?cite=1994%20c%20221%20§%2018[1994 c 221 § 18]; ]

== 11.12.190 - Will to operate on after-acquired property.
Any estate, right or interest in property acquired by the testator after the making of his or her will may pass thereby and in like manner as if title thereto was vested in him or her at the time of making the will, unless the contrary manifestly appears by the will to have been the intention of the testator.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202014[2010 c 8 § 2014]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.12.190[1965 c 145 § 11.12.190]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%2041[1917 c 156 § 41]; RRS § 1411; prior: Code 1881 § 1334; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20210%20§%2071[1863 p 210 § 71]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1860%20p%20172%20§%2038[1860 p 172 § 38]; ]

== 11.12.220 - No interest on devise unless will so provides.
No interest shall be allowed or calculated on any devise contained in any will unless such will expressly provides for such interest.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.12.220[1965 c 145 § 11.12.220]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%2026[1917 c 156 § 26]; RRS § 1396; ]

== 11.12.230 - Intent of testator controlling.
All courts and others concerned in the execution of last wills shall have due regard to the direction of the will, and the true intent and meaning of the testator, in all matters brought before them.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.12.230[1965 c 145 § 11.12.230]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%2045[1917 c 156 § 45]; RRS § 1415; prior: Code 1881 § 1338; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20210%20§%2075[1863 p 210 § 75]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1860%20p%20172%20§%2042[1860 p 172 § 42]; ]

== 11.12.250 - Gift to trust.
A gift may be made by a will to a trustee of a trust executed by any trustor or testator (including a funded or unfunded life insurance trust, although the trustor has reserved any or all rights of ownership of the insurance contracts) if (1) the trust is identified in the testator's will and (2) its terms are evidenced either (a) in a written instrument other than a will, executed by the trustor prior to or concurrently with the execution of the testator's will or (b) in the will of a person who has predeceased the testator, regardless of when executed. The existence, size, or character of the corpus of the trust is immaterial to the validity of the gift. Such gift shall not be invalid because the trust is amendable or revocable, or both, or because the trust was amended after the execution of the testator's will or after the testator's death. Unless the will provides otherwise, the property so given shall not be deemed to be held under a testamentary trust of the testator but shall become a part of the trust to which it is given to be administered and disposed of in accordance with the terms of the instrument establishing the trust, including any amendments, made prior to the death of the testator, and regardless of whether made before or after the execution of the will. Unless the will provides otherwise, an express revocation of the trust prior to the testator's death invalidates the gift. Any termination of the trust other than by express revocation does not invalidate the gift. For purposes of this section, the term "gift" includes the exercise of any testamentary power of appointment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c23.pdf?cite=1985%20c%2023%20§%202[1985 c 23 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c149.pdf?cite=1984%20c%20149%20§%205[1984 c 149 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.12.250[1965 c 145 § 11.12.250]; prior:  1959 c 116 § 1; ]

== 11.12.255 - Incorporation by reference.
A will may incorporate by reference any writing in existence when the will is executed if the will itself manifests the testator's intent to incorporate the writing and describes the writing sufficiently to permit its identification. In the case of any inconsistency between the writing and the will, the will controls.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c23.pdf?cite=1985%20c%2023%20§%203[1985 c 23 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c149.pdf?cite=1984%20c%20149%20§%206[1984 c 149 § 6]; ]

== 11.12.260 - Separate writing may direct disposition of tangible personal property—Requirements.
. A will or a trust of which the decedent is a grantor and which by its terms becomes irrevocable upon or before the grantor's death may refer to a writing that directs disposition of tangible personal property not otherwise specifically disposed of by the will or trust other than property used primarily in trade or business. Such a writing shall not be effective unless: (a) An unrevoked will or trust refers to the writing, (b) the writing is either in the handwriting of, or signed by, the testator or grantor, and (c) the writing describes the items and the recipients of the property with reasonable certainty.

. The writing may be written or signed before or after the execution of the will or trust and need not have significance apart from its effect upon the dispositions of property made by the will or trust. A writing that meets the requirements of this section shall be given effect as if it were actually contained in the will or trust itself, except that if any person designated to receive property in the writing dies before the testator or grantor, the property shall pass as further directed in the writing and in the absence of any further directions, the disposition shall lapse and, in the case of a will, RCW 11.12.110 shall not apply to such lapse.

. The testator or grantor may make subsequent handwritten or signed changes to any writing. If there is an inconsistent disposition of tangible personal property as between writings, the most recent writing controls.

. As used in this section "tangible personal property" means articles of personal or household use or ornament, for example, furniture, furnishings, automobiles, boats, airplanes, and jewelry, as well as precious metals in any tangible form, for example, bullion or coins. The term includes articles even if held for investment purposes and encompasses tangible property that is not real property. The term does not include mobile homes or intangible property, for example, money that is normal currency or normal legal tender, evidences of indebtedness, bank accounts or other monetary deposits, documents of title, or securities.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2236.SL.pdf?cite=2007%20c%20475%20§%203[2007 c 475 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c23.pdf?cite=1985%20c%2023%20§%204[1985 c 23 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c149.pdf?cite=1984%20c%20149%20§%207[1984 c 149 § 7]; ]

== 11.12.265 - Filing of original will with court before death of testator.
Any person who has custody or control of any original will and who has not received knowledge of the death of the testator may deliver the will for filing under seal to any court having jurisdiction. The testator may withdraw the original will so filed upon proper identification. Any other person, including an attorney-in-fact or guardian of the testator, may withdraw the original will so filed only upon court order after showing of good cause. Upon request and presentation of a certified copy of the testator's death certificate, the clerk shall unseal the file. This section does not preclude filing a will not under seal and does not alter any duty of a person having knowledge of the testator's death to file the will.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6121.SL.pdf?cite=2004%20c%2072%20§%201[2004 c 72 § 1]; ]

