= 11.97 - Effect of trust instrument.
:toc:

== 11.97.010 - Power of trustor—Trust provisions control. (Effective until January 1, 2022.)
The trustor of a trust may by the provisions of the trust relieve the trustee from any or all of the duties, restrictions, and liabilities which would otherwise be imposed by chapters 11.95, 11.98, 11.100, and 11.104A RCW and RCW 11.106.020, or may alter or deny any or all of the privileges and powers conferred by those provisions; or may add duties, restrictions, liabilities, privileges, or powers to those imposed or granted by those provisions. If any specific provision of those chapters is in conflict with the provisions of a trust, the provisions of the trust control whether or not specific reference is made in the trust to any of those chapters, except as provided in RCW 6.32.250, 11.96A.190, 19.36.020, 11.98.002, 11.98.200 through 11.98.240, 11.98.072(1), 11.95.100 through 11.95.150, and chapter 11.103 RCW. In no event may a trustee be relieved of the duty to act in good faith and with honest judgment. Notwithstanding the breadth of discretion granted to a trustee in the terms of the trust, including the use of such terms as "absolute," "sole," or "uncontrolled," the trustee must exercise a discretionary power in good faith and in accordance with the terms and purposes of the trust and the interests of the beneficiaries.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5344.SL.pdf?cite=2013%20c%20272%20§%207[2013 c 272 § 7]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1051-S.SL.pdf?cite=2011%20c%20327%20§%2012[2011 c 327 § 12]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1351.SL.pdf?cite=2003%20c%20254%20§%204[2003 c 254 § 4]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5066-S.SL.pdf?cite=1993%20c%20339%20§%201[1993 c 339 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c30.pdf?cite=1985%20c%2030%20§%2038[1985 c 30 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c149.pdf?cite=1984%20c%20149%20§%2064[1984 c 149 § 64]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c124.pdf?cite=1959%20c%20124%20§%202[1959 c 124 § 2]; ]

== 11.97.020 - Trust term interpretation and property disposition—Rules of construction.
The rules of construction that apply in this state to the interpretation of a will and disposition of property by will also apply as appropriate to the interpretation of the terms of a trust and the disposition of the trust property.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1051-S.SL.pdf?cite=2011%20c%20327%20§%2013[2011 c 327 § 13]; ]

== 11.97.900 - Application of chapter. (Effective until January 1, 2022.)
This chapter applies to the provisions of chapters 11.95, 11.98, 11.100, and 11.104A RCW and to RCW 11.106.020.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1351.SL.pdf?cite=2003%20c%20254%20§%205[2003 c 254 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c30.pdf?cite=1985%20c%2030%20§%2039[1985 c 30 § 39]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c149.pdf?cite=1984%20c%20149%20§%2065[1984 c 149 § 65]; ]

