= 11.10 - Abatement of assets.
:toc:

== 11.10.010 - Abatement—Generally.
. Except as provided in subsection (2) of this section, property of a decedent abates, without preference as between real and personal property, in the following order:

.. Intestate property;

.. Residuary gifts;

.. General gifts;

.. Specific gifts.

For purposes of abatement a demonstrative gift, defined as a general gift charged on any specific property or fund, is deemed a specific gift to the extent of the value of the property or fund on which it is charged, and a general gift to the extent of a failure or insufficiency of that property or fund. Abatement within each classification is in proportion to the amounts of property each of the beneficiaries would have received if full distribution of the property had been made in accordance with the terms of the will.

. If the will expresses an order of abatement, or if the testamentary plan or the express or implied purpose of the devise would be defeated by the order of abatement stated in subsection (1) of this section, a gift abates as may be found necessary to give effect to the intention of the testator.

. If the subject of a preferred gift is sold, diminished, or exhausted incident to administration, not including satisfaction of debts or liabilities according to their community or separate status under RCW 11.10.030, abatement must be achieved by appropriate adjustments in, or contribution from, other interests in the remaining assets.

. To the extent that the whole of the community property is subject to abatement, the shares of the decedent and of the surviving spouse or surviving domestic partner in the community property abate equally.

. If required under RCW 11.10.040, nonprobate assets must abate with those disposed of under the will and passing by intestacy.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3104-S2.SL.pdf?cite=2008%20c%206%20§%20908[2008 c 6 § 908]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2270-S.SL.pdf?cite=1994%20c%20221%20§%205[1994 c 221 § 5]; ]

== 11.10.020 - Gift from mixed separate and community property.
To the extent that a gift is to be satisfied out of a source that consists of both separate and community property, unless otherwise indicated in the will it is presumed to be a gift from separate and community property in proportion to their relative value in the property or fund from which the gift is to be satisfied.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2270-S.SL.pdf?cite=1994%20c%20221%20§%206[1994 c 221 § 6]; ]

== 11.10.030 - Allocation of separate and community assets.
. A community debt or liability is charged against the entire community property, with the surviving spouse's or surviving domestic partner's half and the decedent spouse's or decedent domestic partner's half charged equally.

. A separate debt or liability is charged first against separate property, and if that is insufficient against the balance of decedent's half of community property remaining after community debts and liabilities are satisfied.

. A community debt or liability that is also the separate debt or liability of the decedent is charged first against the whole of the community property and then against the decedent's separate property.

. An expense of administration is charged against the separate property and the decedent's half of the community property in proportion to the relative value of the property, unless a different charging of expenses is shown to be appropriate under the circumstances including against the surviving spouse's or surviving domestic partner's share of the community property.

. Property of a similar type, community or separate, is appropriated in accordance with the abatement priorities of RCW 11.10.010.

. Property that is primarily chargeable for a debt or liability is exhausted, in accordance with the abatement priorities of RCW 11.10.010, before resort is had, also in accordance with RCW 11.10.010, to property that is secondarily chargeable.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3104-S2.SL.pdf?cite=2008%20c%206%20§%20931[2008 c 6 § 931]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2270-S.SL.pdf?cite=1994%20c%20221%20§%207[1994 c 221 § 7]; ]

== 11.10.040 - Nonprobate assets.
. If abatement is necessary among takers of a nonprobate asset, the court shall adopt the abatement order and limitations set out in RCW 11.10.010, 11.10.020, and 11.10.030, assigning categories in accordance with subsection (2) of this section.

. A nonprobate transfer must be categorized for purposes of abatement, within the list of priorities set out in RCW 11.10.010(1), as follows:

.. All nonprobate forms of transfer under which an identifiable nonprobate asset passes to a beneficiary or beneficiaries on the event of the decedent's death, such as, but not limited to, joint tenancies and payable-on-death accounts, are categorized as specific bequests.

.. With respect to all other interests passing under nonprobate forms of transfer, each must be categorized in the manner that is most closely comparable to the nature of the transfer of that interest.

. If and to the extent that a nonprobate asset is subject to the same obligations as are assets disposed of under the decedent's will, the nonprobate assets abate ratably with the probate assets, within the categories set out in subsection (2) of this section.

. If the nonprobate instrument of transfer or the decedent's will expresses a different order of abatement, or if the decedent's overall dispositive plan or the express or implied purpose of the transfer would be defeated by the order of abatement stated in subsections (1) through (3) of this section, the nonprobate assets abate as may be found necessary to give effect to the intention of the decedent.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2270-S.SL.pdf?cite=1994%20c%20221%20§%208[1994 c 221 § 8]; ]

== 11.10.900 - Application of chapter.
This chapter applies in all instances in which no other abatement scheme is expressly provided.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2270-S.SL.pdf?cite=1994%20c%20221%20§%204[1994 c 221 § 4]; ]

