= 11.02 - General provisions.
:toc:

== 11.02.001 - Section headings in Title 11 RCW not part of law.
Section headings, as found in Title 11 RCW, do not constitute any part of the law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c30.pdf?cite=1985%20c%2030%20§%203[1985 c 30 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c149.pdf?cite=1984%20c%20149%20§%20179[1984 c 149 § 179]; ]

== 11.02.005 - Definitions and use of terms. (Effective until January 1, 2022.)
When used in this title, unless otherwise required from the context:

. "Administrator" means a personal representative of the estate of a decedent and the term may be used in lieu of "personal representative" wherever required by context.

. "Codicil" means a will that modifies or partially revokes an existing earlier will. A codicil need not refer to or be attached to the earlier will.

. "Degree of kinship" means the degree of kinship as computed according to the rules of the civil law; that is, by counting upward from the intestate to the nearest common ancestor and then downward to the relative, the degree of kinship being the sum of these two counts.

. "Executor" means a personal representative of the estate of a decedent appointed by will and the term may be used in lieu of "personal representative" wherever required by context.

. "Guardian" or "limited guardian" means a personal representative of the person or estate of an incompetent or disabled person as defined in *RCW 11.88.010 and the term may be used in lieu of "personal representative" wherever required by context.

. "Heirs" denotes those persons, including the surviving spouse or surviving domestic partner, who are entitled under the statutes of intestate succession to the real and personal property of a decedent on the decedent's death intestate.

. "Internal revenue code" means the United States internal revenue code of 1986, as amended or renumbered as of January 1, 2001.

. "Issue" means all the lineal descendants of an individual. An adopted individual is a lineal descendant of each of his or her adoptive parents and of all individuals with regard to which each adoptive parent is a lineal descendant. A child conceived prior to the death of a parent but born after the death of the deceased parent is considered to be the surviving issue of the deceased parent for purposes of this title.

. "Net estate" refers to the real and personal property of a decedent exclusive of homestead rights, exempt property, the family allowance and enforceable claims against, and debts of, the deceased or the estate.

. "Nonprobate asset" means those rights and interests of a person having beneficial ownership of an asset that pass on the person's death under a written instrument or arrangement other than the person's will. "Nonprobate asset" includes, but is not limited to, a right or interest passing under a joint tenancy with right of survivorship, joint bank account with right of survivorship, transfer on death deed, payable on death or trust bank account, transfer on death security or security account, deed or conveyance if possession has been postponed until the death of the person, trust of which the person is grantor and that becomes effective or irrevocable only upon the person's death, community property agreement, individual retirement account or bond, or note or other contract the payment or performance of which is affected by the death of the person. "Nonprobate asset" does not include: A payable-on-death provision of a life insurance policy, annuity, or other similar contract, or of an employee benefit plan; a right or interest passing by descent and distribution under chapter 11.04 RCW; a right or interest if, before death, the person has irrevocably transferred the right or interest, the person has waived the power to transfer it or, in the case of contractual arrangement, the person has waived the unilateral right to rescind or modify the arrangement; or a right or interest held by the person solely in a fiduciary capacity. For the definition of "nonprobate asset" relating to revocation of a provision for a former spouse upon dissolution of marriage or declaration of invalidity of marriage, RCW 11.07.010(5) applies. For the definition of "nonprobate asset" relating to testamentary disposition of nonprobate assets, see RCW 11.11.010(7).

. "Personal representative" includes executor, administrator, special administrator, and guardian or limited guardian and special representative.

. "Real estate" includes, except as otherwise specifically provided herein, all lands, tenements, and hereditaments, and all rights thereto, and all interest therein possessed and claimed in fee simple, or for the life of a third person.

. "Representation" refers to a method of determining distribution in which the takers are in unequal degrees of kinship with respect to a decedent, and is accomplished as follows: After first determining who, of those entitled to share in the estate, are in the nearest degree of kinship, the estate is divided into equal shares, the number of shares being the sum of the number of persons who survive the decedent who are in the nearest degree of kinship and the number of persons in the same degree of kinship who died before the decedent but who left issue surviving the decedent; each share of a deceased person in the nearest degree must be divided among those of the deceased person's issue who survive the decedent and have no ancestor then living who is in the line of relationship between them and the decedent, those more remote in degree taking together the share which their ancestor would have taken had he or she survived the decedent.

. References to "section 2033A" of the internal revenue code in wills, trust agreements, powers of appointment, beneficiary designations, and other instruments governed by or subject to this title are deemed to refer to the comparable or corresponding provisions of section 2057 of the internal revenue code, as added by section 6006(b) of the internal revenue service restructuring act of 1998 (H.R. 2676, P.L. 105-206); and references to the section 2033A "exclusion" are deemed to mean the section 2057 deduction.

. "Settlor" has the same meaning as provided for "trustor" in this section.

. "Special administrator" means a personal representative of the estate of a decedent appointed for limited purposes and the term may be used in lieu of "personal representative" wherever required by context.

. "Surviving spouse" or "surviving domestic partner" does not include an individual whose marriage to or state registered domestic partnership with the decedent has been terminated, dissolved, or invalidated unless, by virtue of a subsequent marriage or state registered domestic partnership, he or she is married to or in a domestic partnership with the decedent at the time of death. A decree of separation that does not terminate the status of spouses or domestic partners is not a dissolution or invalidation for purposes of this subsection.

. "Trustee" means an original, added, or successor trustee and includes the state, or any agency thereof, when it is acting as the trustee of a trust to which chapter 11.98 RCW applies.

. "Trustor" means a person, including a testator, who creates, or contributes property to, a trust.

. "Will" means an instrument validly executed as required by RCW 11.12.020.

Words that import the singular number may also be applied to the plural of persons and things.

Words importing the masculine gender only may be extended to females also.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2368.SL.pdf?cite=2018%20c%2022%20§%206[2018 c 22 § 6]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1117-S.SL.pdf?cite=2014%20c%2058%20§%2018[2014 c 58 § 18]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1051-S.SL.pdf?cite=2011%20c%20327%20§%201[2011 c 327 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3104-S2.SL.pdf?cite=2008%20c%206%20§%20901[2008 c 6 § 901]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2236.SL.pdf?cite=2007%20c%20475%20§%201[2007 c 475 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1125.SL.pdf?cite=2005%20c%2097%20§%201[2005 c 97 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1361.SL.pdf?cite=2001%20c%20320%20§%201[2001 c 320 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6140.SL.pdf?cite=2000%20c%20130%20§%201[2000 c 130 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1623-S.SL.pdf?cite=1999%20c%20358%20§%2020[1999 c 358 § 20]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6181-S.SL.pdf?cite=1998%20c%20292%20§%20117[1998 c 292 § 117]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5110-S.SL.pdf?cite=1997%20c%20252%20§%201[1997 c 252 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2270-S.SL.pdf?cite=1994%20c%20221%20§%201[1994 c 221 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1075.SL.pdf?cite=1993%20c%2073%20§%201[1993 c 73 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c30.pdf?cite=1985%20c%2030%20§%204[1985 c 30 § 4]; prior:  1984 c 149 § 4; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c80.pdf?cite=1977%20ex.s.%20c%2080%20§%2014[1977 ex.s. c 80 § 14]; 1975-'76 2nd ex.s. c 42 § 23; 1965 c 145 § 11.02.005. Former RCW sections: Subd. (3), RCW  11.04.110; subd. (4), RCW  11.04.010; subd. (5), RCW  11.04.100; subd. (6), RCW  11.04.280; subd. (7), RCW  11.04.010; subd. (8) and (9), RCW  11.12.240; subd. (14) and (15), RCW  11.02.040; ]

== 11.02.070 - Community property—Disposition—Probate administration of.
Except as provided in RCW 41.04.273 and 11.84.025, upon the death of a decedent, a one-half share of the community property shall be confirmed to the surviving spouse or surviving domestic partner, and the other one-half share shall be subject to testamentary disposition by the decedent, or shall descend as provided in chapter 11.04 RCW. The whole of the community property shall be subject to probate administration for all purposes of this title, including the payment of obligations and debts of the community, the award in lieu of homestead, the allowance for family support, and any other matter for which the community property would be responsible or liable if the decedent were living.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3104-S2.SL.pdf?cite=2008%20c%206%20§%20902[2008 c 6 § 902]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6181-S.SL.pdf?cite=1998%20c%20292%20§%20504[1998 c 292 § 504]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c168.pdf?cite=1967%20c%20168%20§%201[1967 c 168 § 1]; ]

== 11.02.080 - Application and construction of act as to wills, proceedings, guardians, accrued rights, and pre-executed instruments—Severability—Effective date—1974 ex.s. c 117.
On and after October 1, 1974:

. The provisions of chapter 117, Laws of 1974 ex. sess. shall apply to any wills of decedents dying thereafter;

. The provisions of chapter 117, Laws of 1974 ex. sess. shall apply to any proceedings in court then pending or thereafter commenced regardless of the time of the death of decedent except to the extent that in the opinion of the court the former procedure should be made applicable in a particular case in the interest of justice or because of infeasibility of application of the procedure of chapter 117, Laws of 1974 ex. sess.;

. Every personal representative including a person administering an estate of a minor or incompetent holding an appointment on October 1, 1974, continues to hold the appointment, has the powers conferred by chapter 117, Laws of 1974 ex. sess. and is subject to the duties imposed with respect to any act occurring or done thereafter;

. An act done before October 1, 1974 in any proceeding and any accrued right is not impaired by chapter 117, Laws of 1974 ex. sess. If a right is acquired, extinguished, or barred upon the expiration of a prescribed period of time which has commenced to run by the provisions of any statute before October 1, 1974, the provisions shall remain in force with respect to that right;

. Any rule of construction or presumption provided in chapter 117, Laws of 1974 ex. sess. applies to instruments executed before October 1, 1974 unless there is a clear indication of a contrary intent.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c117.pdf?cite=1974%20ex.s.%20c%20117%20§%201[1974 ex.s. c 117 § 1]; ]

== 11.02.091 - Written instrument—Limit on characterization as testamentary.
. An otherwise effective written instrument of transfer may not be deemed testamentary solely because of a provision for a nonprobate transfer at death in the instrument.

. "Provision for a nonprobate transfer at death" as used in subsection (1) of this section includes, but is not limited to, a written provision that:

.. Money or another benefit up to that time due to, controlled, or owned by a decedent before death must be paid after the decedent's death to a person whom the decedent designates either in the instrument or a separate writing, including a will, executed at any time;

.. Money or another benefit due or to become due under the instrument ceases to be payable in the event of the death of the promisee or the promisor before payment or demand; or

.. Property, controlled by or owned by the decedent before death, that is the subject of the instrument passes to a person the decedent designates either in the instrument or in a separate writing, including a will, executed at any time.

. "Otherwise effective written instrument of transfer" as used in subsection (1) of this section means: An insurance policy; a contract of employment; a bond; a mortgage; a promissory note; a certified or uncertified security; an account agreement; a compensation plan; a pension plan; an individual retirement plan; an employee benefit plan; a joint tenancy; a community property agreement; a trust; a conveyance; a deed of gift; a contract; or another written instrument of a similar nature that would be effective if it did not contain provision for a nonprobate transfer at death.

. This section only eliminates a requirement that instruments of transfer comply with formalities for executing wills under chapter 11.12 RCW. This section does not make a written instrument effective as a contract, gift, conveyance, deed, or trust that would not otherwise be effective as such for reasons other than failure to comply with chapter 11.12 RCW.

. This section does not limit the rights of a creditor under other laws of this state.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1078.SL.pdf?cite=1993%20c%20291%20§%202[1993 c 291 § 2]; ]

== 11.02.100 - Transfer of shares of record—Dividends.
Shares of record in the name of a spouse or domestic partner may be transferred by such person, such person's agent or attorney, without the signature of such person's spouse or domestic partner. All dividends payable upon any shares of a corporation standing in the name of a spouse or domestic partner, shall be paid to such spouse or domestic partner, such person's agent or attorney, in the same manner as if such person were unmarried or not in a state registered domestic partnership, and it shall not be necessary for the other spouse or domestic partner to join in a receipt therefor; and any proxy or power given by a spouse or domestic partner, touching any shares of any corporation standing in such person's name, shall be valid and binding without the signature of the other spouse or other domestic partner.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3104-S2.SL.pdf?cite=2008%20c%206%20§%20903[2008 c 6 § 903]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c180.pdf?cite=1990%20c%20180%20§%207[1990 c 180 § 7]; ]

== 11.02.110 - Transfer of shares or securities—Presumption of joint tenancy.
Whenever shares or other securities issued by domestic or foreign corporations are or have been issued or transferred to two or more persons in joint tenancy form on the books or records of the corporation, it is presumed in favor of the corporation, its registrar and its transfer agent that the shares or other securities are owned by such persons in joint tenancy and not otherwise. A domestic or foreign corporation or its registrar or transfer agent is not liable for transferring or causing to be transferred on the books of the corporation to or pursuant to the direction of the surviving joint tenant or tenants any share or shares or other securities theretofore issued by the corporation to two or more persons in joint tenancy form on the books or records of the corporation, unless the transfer was made with actual knowledge by the corporation or by its registrar or transfer agent of the existence of any understanding, agreement, condition, or evidence that the shares or securities were held other than in joint tenancy, or of the invalidity of the joint tenancy or a breach of trust by the joint tenants.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c180.pdf?cite=1990%20c%20180%20§%208[1990 c 180 § 8]; ]

== 11.02.120 - Transfer of shares—Liability.
Neither a domestic or foreign corporation or its registrar or transfer agent shall be liable for transferring or causing to be transferred on the books of the corporation to or pursuant to the direction of the surviving spouse or the surviving domestic partner any share or shares or other securities theretofore issued by the corporation to the deceased or surviving spouse or both, or to the deceased or surviving domestic partner or both, if the corporation or its registrar or transfer agent shall be provided with the following:

. A copy of an agreement which shall have been entered into between the spouses or between the domestic partners pursuant to RCW 26.16.120 and certified by the auditor of the county in this state in whose office the same shall have been recorded;

. A certified copy of the death certificate of the deceased spouse or deceased domestic partner;

. An affidavit of the surviving spouse or surviving domestic partner that:

.. The shares or other securities constituted community property of the spouses or the domestic partners at date of death of the deceased spouse or deceased domestic partner and their disposition is controlled by the community property agreement;

.. No proceedings have been instituted to contest or set aside or cancel the agreement; and that

.. The claims of creditors have been paid or provided for.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3104-S2.SL.pdf?cite=2008%20c%206%20§%20904[2008 c 6 § 904]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c180.pdf?cite=1990%20c%20180%20§%209[1990 c 180 § 9]; ]

== 11.02.130 - Safe deposit repository—Lease provision ineffective to create joint tenancy or transfer at one lessee's death.
A provision in a lease of a safety deposit repository to the effect that two or more persons have access to the repository, or that purports to create a joint tenancy in the repository or in the contents of the repository, or that purports to vest ownership of the contents of the repository in the surviving lessee, is ineffective to create joint ownership of the contents of the repository or to transfer ownership at death of one of the lessees to the survivor. Ownership of the contents of the repository and devolution of title to those contents is determined according to rules of law without regard to the lease provisions.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1078.SL.pdf?cite=1993%20c%20291%20§%203[1993 c 291 § 3]; ]

== 11.02.900 - Short title—Washington trust act of 1984.
Chapter 149, Laws of 1984, as amended and reenacted in chapters 8, 9, 10, 11, 23, 30, and 31, Laws of 1985 shall be known as the Washington trust act of 1984.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c30.pdf?cite=1985%20c%2030%20§%202[1985 c 30 § 2]; ]

== 11.02.901 - Application—1985 c 30—Application of 1984 c 149 as amended and reenacted in 1985.
. Nothing in chapter 8, 9, 10, 11, 23, 30, or 31, Laws of 1985 shall invalidate or nullify:

.. Any instrument or property relationship that is executed and irrevocable as of the April 10, 1985; or

.. Any action undertaken in a proceeding where the action was commenced before April 10, 1985, as long as the instrument, property relationship, or action complies with chapter 149, Laws of 1984.

. Except as specifically provided otherwise in chapter 149, Laws of 1984 as amended and reenacted in 1985, chapter 149, Laws of 1984 as amended and reenacted in 1985 shall apply to all instruments, property relationships, and proceedings existing on January 1, 1985.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c30.pdf?cite=1985%20c%2030%20§%20139[1985 c 30 § 139]; ]

== 11.02.902 - Purpose—1985 c 30.
The purpose of this act is to make technical corrections to chapter 149, Laws of 1984, and to ensure that the changes made in that chapter meet the constitutional requirements of Article II, section 19 of the state Constitution.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c30.pdf?cite=1985%20c%2030%20§%201[1985 c 30 § 1]; ]

== 11.02.903 - Severability—1985 c 30.
If any provision of this act or its application to any person or circumstance is held invalid, the remainder of the act or the application of the provision to other persons or circumstances is not affected.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c30.pdf?cite=1985%20c%2030%20§%20144[1985 c 30 § 144]; ]

