= 11.96A - Trust and estate dispute resolution.
:toc:

== 11.96A.010 - Purpose.
The overall purpose of this chapter is to set forth generally applicable statutory provisions for the resolution of disputes and other matters involving trusts and estates in a single chapter under Title 11 RCW. The provisions are intended to provide nonjudicial methods for the resolution of matters, such as mediation, arbitration, and agreement. The [This] chapter also provides for judicial resolution of disputes if other methods are unsuccessful.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20102[1999 c 42 § 102]; ]

== 11.96A.020 - General power of courts—Intent—Plenary power of the court.
. It is the intent of the legislature that the courts shall have full and ample power and authority under this title to administer and settle:

.. All matters concerning the estates and assets of incapacitated, missing, and deceased persons, including matters involving nonprobate assets and powers of attorney, in accordance with this title; and

.. All trusts and trust matters.

. If this title should in any case or under any circumstance be inapplicable, insufficient, or doubtful with reference to the administration and settlement of the matters listed in subsection (1) of this section, the court nevertheless has full power and authority to proceed with such administration and settlement in any manner and way that to the court seems right and proper, all to the end that the matters be expeditiously administered and settled by the court.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20103[1999 c 42 § 103]; ]

== 11.96A.030 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Citation" or "cite" and other similar terms, when required of a person interested in the estate or trust or a party to a petition, means to give notice as required under RCW 11.96A.100. "Citation" or "cite" and other similar terms, when required of the court, means to order, as authorized under RCW 11.96A.020 and 11.96A.060, and as authorized by law.

. "Matter" includes any issue, question, or dispute involving:

.. The determination of any class of creditors, devisees, legatees, heirs, next of kin, or other persons interested in an estate, trust, nonprobate asset, or with respect to any other asset or property interest passing at death;

.. The direction of a personal representative or trustee to do or to abstain from doing any act in a fiduciary capacity;

.. The determination of any question arising in the administration of an estate or trust, or with respect to any nonprobate asset, or with respect to any other asset or property interest passing at death, that may include, without limitation, questions relating to: (i) The construction of wills, trusts, community property agreements, and other writings; (ii) a change of personal representative or trustee; (iii) a change of the situs of a trust; (iv) an accounting from a personal representative or trustee; (v) the determination of fees for a personal representative or trustee; or (vi) the powers and duties of a statutory trust director or directed trustee of a directed trust under chapter 11.98B RCW;

.. The grant to a personal representative or trustee of any necessary or desirable power not otherwise granted in the governing instrument or given by law;

.. An action or proceeding under chapter 11.84 RCW;

.. The amendment, reformation, or conformation of a will or a trust instrument to comply with statutes and regulations of the United States internal revenue service in order to achieve qualification for deductions, elections, and other tax requirements, including the qualification of any gift thereunder for the benefit of a surviving spouse who is not a citizen of the United States for the estate tax marital deduction permitted by federal law, including the addition of mandatory governing instrument requirements for a qualified domestic trust under section 2056A of the internal revenue code, the qualification of any gift thereunder as a qualified conservation easement as permitted by federal law, or the qualification of any gift for the charitable estate tax deduction permitted by federal law, including the addition of mandatory governing instrument requirements for a charitable remainder trust;

.. With respect to any nonprobate asset, or with respect to any other asset or property interest passing at death, including joint tenancy property, property subject to a community property agreement, or assets subject to a pay on death or transfer on death designation:

... The ascertaining of any class of creditors or others for purposes of chapter 11.18 or 11.42 RCW;

... The ordering of a qualified person, the notice agent, or resident agent, as those terms are defined in chapter 11.42 RCW, or any combination of them, to do or abstain from doing any particular act with respect to a nonprobate asset;

... The ordering of a custodian of any of the decedent's records relating to a nonprobate asset to do or abstain from doing any particular act with respect to those records;

... The determination of any question arising in the administration under chapter 11.18 or 11.42 RCW of a nonprobate asset;

.. The determination of any questions relating to the abatement, rights of creditors, or other matter relating to the administration, settlement, or final disposition of a nonprobate asset under this title;

.. The resolution of any matter referencing this chapter, including a determination of any questions relating to the ownership or distribution of an individual retirement account on the death of the spouse of the account holder as contemplated by RCW 6.15.020(6);

.. The resolution of any other matter that could affect the nonprobate asset;

.. With respect to any custodianship under a uniform transfers to minors act, the determination of any issues subject to court determination under chapter 11.114 RCW; and

.. The reformation of a will or trust to correct a mistake under RCW 11.96A.125.

. "Nonprobate assets" has the meaning given in RCW 11.02.005.

. "Notice agent" has the meanings given in RCW 11.42.010.

. "Party" or "parties" means any person who has a legal or equitable interest in, or who holds a power or a claim with respect to, the subject of a matter. Each of the terms "party" or "parties" must be construed liberally in its context to fulfill the purposes of the procedural rules contained in this chapter as supplemented by the court rules and to promote justice, without creating new substantive rights that do not otherwise exist under the laws of this state or principles of equity, and may include without limitation the following:

.. With respect to any property held subject to a revocable trust:

... Each trustee of the property subject to the trust; and

... Each trustor who transferred the property;

.. With respect to any property held subject to an irrevocable trust:

... Each trustee of the trust holding the property;

... Each qualified beneficiary, as defined in RCW 11.98.002, of the property subject to the trust and any other beneficiary whose interest is protected under the constitutional principles of due process; and

... Each holder of a power relating to the property;

.. With respect to any testate property:

... Each personal representative appointed to execute the will governing that property;

... Each devisee or legatee of that testate property;

... Each holder of a power relating to the testate property following the testator's death; and

... Each creditor whose claim has been established by allowance or judgment;

.. With respect to any intestate property:

... Each personal representative appointed to administer that property;

... Each heir of the decedent who owned that property;

... Each holder of a power relating to the intestate property following the owner's death; and

... Each creditor whose claim has been established by allowance or judgment;

.. With respect to any nonprobate asset, or with respect to any other asset or property interest passing at death, including joint tenancy property, property subject to a community property agreement, or assets subject to a pay on death or transfer on death designation:

... Each custodian of the property;

... Each transferee and beneficiary of the property; and

... Each qualified person, the notice agent, or resident agent, as those terms are defined in chapter 11.42 RCW;

.. With respect to any custodial property subject to a uniform transfers to minors act:

... Each custodian of the custodial property;

... The minor, as defined in RCW 11.114.010, for whose benefit the custodian holds the custodial property; and

... Each other person who holds a power under chapter 11.114 RCW to act on behalf of the minor;

.. With respect to any community property, each spouse;

.. With respect to a matter relating to the powers and duties of a trust director or a directed trustee, or both:

.. Each trust director with an interest in the matter;

... Each directed trustee;

... Each beneficiary, holder of a power, or other person whose interest or power is affected by the matter and is protected under the constitutional principles of due process;

... Each creditor whose claim has been allowed but has not been paid;

.. The attorney general to the extent that the attorney general is a necessary and proper party under RCW 11.110.120 and corresponding common law;

.. Each person who claims a legal right, title, or interest in property being subjected to probate or trust administration, nonprobate assets, other property passing at death, or custodial property, including without limitation the resolution of rights and duties under RCW 11.18.200 and questions relating to legal ownership or abatement; and

.. When necessary, a party's representative or representatives, which may include without limitation guardians; custodians; guardians ad litem; special representatives; virtual representatives; attorneys in fact; fiduciaries; and notice agents, resident agents, and qualified persons, as those terms are defined in chapter 11.42 RCW.

. "Persons interested in the estate, trust, nonprobate asset, other property passing at death, or custodial property" means all persons legally or beneficially interested in the estate, trust, nonprobate asset, other property passing at death, or custodial property; all persons holding powers with respect to the trust, estate, nonprobate asset, other property passing at death, or custodial property; the attorney general in the case of any charitable trust where the attorney general would be a necessary party to judicial proceedings concerning the trust; all fiduciaries of the estate, trust, nonprobate asset, or other property passing at death; and all custodians of custodial property.

. "Trustee" means any acting and qualified trustee of the trust.

. "Virtual representative" and other similar terms refer to a person who virtually represents another under RCW 11.96A.120 or other applicable law.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%204018[2021 c 140 § 4018]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5302.SL.pdf?cite=2015%20c%20115%20§%201[2015 c 115 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1051-S.SL.pdf?cite=2011%20c%20327%20§%205[2011 c 327 § 5]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1103-S.SL.pdf?cite=2009%20c%20525%20§%2020[2009 c 525 § 20]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3104-S2.SL.pdf?cite=2008%20c%206%20§%20927[2008 c 6 § 927]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6597-S.SL.pdf?cite=2006%20c%20360%20§%2010[2006 c 360 § 10]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6484.SL.pdf?cite=2002%20c%2066%20§%202[2002 c 66 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20104[1999 c 42 § 104]; ]

== 11.96A.040 - Original jurisdiction in probate and trust matters—Powers of court.
. The superior court of every county has original subject matter jurisdiction over the probate of wills and the administration of estates of incapacitated, missing, and deceased individuals in all instances, including without limitation:

.. When a resident of the state dies;

.. When a nonresident of the state dies in the state; or

.. When a nonresident of the state dies outside the state.

. The superior court of every county has original subject matter jurisdiction over trusts and all matters relating to trusts.

. The superior courts may: Probate or refuse to probate wills, appoint personal representatives, administer and settle the affairs and the estates of incapacitated, missing, or deceased individuals including but not limited to decedents' nonprobate assets; administer and settle matters that relate to nonprobate assets and arise under chapter 11.18 or 11.42 RCW; administer and settle all matters relating to trusts; administer and settle matters that relate to powers of attorney; award processes and cause to come before them all persons whom the courts deem it necessary to examine; order and cause to be issued all such writs and any other orders as are proper or necessary; and do all other things proper or incident to the exercise of jurisdiction under this section.

. The subject matter jurisdiction of the superior court applies without regard to venue. A proceeding or action by or before a superior court is not defective or invalid because of the selected venue if the court has jurisdiction of the subject matter of the action.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1135-S.SL.pdf?cite=2001%20c%20203%20§%209[2001 c 203 § 9]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20201[1999 c 42 § 201]; ]

== 11.96A.050 - Venue in proceedings involving probate or trust matters. (Effective until January 1, 2022.)
. Venue for proceedings pertaining to trusts is:

.. For testamentary trusts established under wills probated in the state of Washington, in the superior court of the county where the probate of the will is being administered or was completed or, in the alternative, the superior court of the county where any qualified beneficiary of the trust as defined in RCW 11.98.002 resides, the county where any trustee resides or has a place of business, or the county where any real property that is an asset of the trust is located; and

.. For all other trusts, in the superior court of the county where any qualified beneficiary of the trust as defined in RCW 11.98.002 resides, the county where any trustee resides or has a place of business, or the county where any real property that is an asset of the trust is located. If no county has venue for proceedings pertaining to a trust under the preceding sentence, then in any county.

. A party to a proceeding pertaining to a trust may request that venue be changed. If the request is made within four months of the giving of the first notice of a proceeding pertaining to the trust, except for good cause shown, venue must be moved to the county with the strongest connection to the trust as determined by the court, considering such factors as the residence of a qualified beneficiary of the trust as defined in RCW 11.98.002, the residence or place of business of a trustee, and the location of any real property that is an asset of the trust.

. Venue for proceedings subject to *chapter 11.88 or 11.92 RCW must be determined under the provisions of those chapters.

. Venue for proceedings pertaining to the probate of wills, the administration and disposition of a decedent's property, including nonprobate assets, and any other matter not identified in subsection (1), (2), or (3) of this section, must be in any county in the state of Washington that the petitioner selects. A party to a proceeding may request that venue be changed if the request is made within four months of the mailing of the notice of appointment and pendency of probate required by RCW 11.28.237, and except for good cause shown, venue must be moved as follows:

.. If the decedent was a resident of the state of Washington at the time of death, to the county of the decedent's residence; or

.. If the decedent was not a resident of the state of Washington at the time of death, to any of the following:

... Any county in which any part of the probate estate might be;

... If there are no probate assets, any county where any nonprobate asset might be; or

... The county in which the decedent died.

. Once letters testamentary or of administration have been granted in the state of Washington, all orders, settlements, trials, and other proceedings under this title must be had or made in the county in which such letters have been granted unless venue is moved as provided in subsection (4) of this section.

. Venue for proceedings pertaining to powers of attorney must be in the superior court of the county of the principal's residence, except for good cause shown.

. If venue is moved, an action taken before venue is changed is not invalid because of the venue.

. Any request to change venue that is made more than four months after the commencement of the action may be granted in the discretion of the court.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5344.SL.pdf?cite=2013%20c%20272%20§%203[2013 c 272 § 3]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1051-S.SL.pdf?cite=2011%20c%20327%20§%206[2011 c 327 § 6]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1135-S.SL.pdf?cite=2001%20c%20203%20§%2010[2001 c 203 § 10]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20202[1999 c 42 § 202]; ]

== 11.96A.060 - Exercise of powers—Orders, writs, process, etc.
The court may make, issue, and cause to be filed or served, any and all manner and kinds of orders, judgments, citations, notices, summons, and other writs and processes that might be considered proper or necessary in the exercise of the jurisdiction or powers given or intended to be given by this title.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20203[1999 c 42 § 203]; ]

== 11.96A.070 - Statutes of limitation.
. [Empty]
.. A beneficiary of an express trust may not commence a proceeding against a trustee for breach of trust more than three years after the date a report was delivered in the manner provided in RCW 11.96A.110 to the beneficiary or to a representative of the beneficiary if the report adequately disclosed the existence of a potential claim for breach of trust and informed the beneficiary of the time allowed for commencing a proceeding.

.. A report adequately discloses the existence of a potential claim for breach of trust if it provides sufficient information so that the beneficiary or representative knows or should have known of the potential claim. A report that includes all of the items described in this subsection [(1)](b) that are relevant for the reporting period is presumed to have provided such sufficient information regarding the existence of potential claims for breach of trust for such period:

... A statement of receipts and disbursements of principal and income that have occurred during the accounting period;

... A statement of the assets and liabilities of the trust and their values at the beginning and end of the period;

... The trustee's compensation for the period;

... The agents hired by the trustee, their relationship to the trustee, if any, and their compensation, for the period;

.. Disclosure of any pledge, mortgage, option, or lease of trust property, or other agreement affecting trust property binding for a period of five years or more that was granted or entered into during the accounting period;

.. Disclosure of all transactions during the period that are equivalent to one of the types of transactions described in RCW 11.98.078 or otherwise could have been affected by a conflict between the trustee's fiduciary and personal interests;

.. A statement that the recipient of the account information may petition the superior court pursuant to chapter 11.106 RCW to obtain review of the statement and of acts of the trustee disclosed in the statement; and

.. A statement that claims against the trustee for breach of trust may not be made after the expiration of three years from the date the trustee delivers the report in the manner provided in RCW 11.96A.110.

.. If (a) of this subsection does not apply, a judicial proceeding by a beneficiary against a trustee for breach of trust must be commenced within three years after the first to occur of:

... The removal, resignation, or death of the trustee;

... The termination of the beneficiary's interest in the trust; or

... The termination of the trust.

.. For purposes of this section, "express trust" does not include resulting trusts, constructive trusts, business trusts in which certificates of beneficial interest are issued to the beneficiary, investment trusts, voting trusts, trusts in the nature of mortgages or pledges, liquidation trusts, or trusts for the sole purpose of paying dividends, interest, interest coupons, salaries, wages, pensions, or profits, trusts created in deposits in any financial institution under *chapter 30.22 RCW, unless any such trust that is created in writing specifically incorporates this chapter in whole or in part.

. Except as provided in RCW 11.96A.250 with respect to special representatives, an action against a personal representative for alleged breach of fiduciary duty by an heir, legatee, or other interested party must be brought before discharge of the personal representative.

. The legislature hereby confirms the long-standing public policy of promoting the prompt and efficient resolution of matters involving trusts and estates. To further implement this policy, the legislature adopts the following statutory provisions in order to:

.. Encourage and facilitate the participation of qualified individuals as special representatives;

.. Serve the public's interest in having a prompt and efficient resolution of matters involving trusts or estates; and

.. Promote complete and final resolution of proceedings involving trusts and estates.

... Actions against a special representative must be brought before the earlier of:

(A) Three years from the discharge of the special representative as provided in RCW 11.96A.250; or

(B) The entry of an order by a court of competent jurisdiction under RCW 11.96A.240 approving the written agreement executed by all interested parties in accord with the provisions of RCW 11.96A.220.

... If a legal action is commenced against the special representative after the expiration of the period during which claims may be brought against the special representative as provided in (c)(i) of this subsection, alleging property damage, property loss, or other civil liability caused by or resulting from an alleged act or omission of the special representative arising out of or by reason of the special representative's duties or actions as special representative, the special representative must be indemnified: (A) From the assets held in the trust or comprising the estate involved in the dispute; and (B) by the persons bringing the legal action, for all expenses, attorneys' fees, judgments, settlements, decrees, or amounts due and owing or paid in satisfaction of or incurred in the defense of the legal action. To the extent possible, indemnification must be made first by the persons bringing the legal action, second from that portion of the trust or estate that is held for the benefit of, or has been distributed or applied to, the persons bringing the legal action, and third from the other assets held in the trust or comprising the estate involved in the dispute.

. The tolling provisions of RCW 4.16.190 apply to this chapter except that the running of a statute of limitations under subsection (1) or (2) of this section, or any other applicable statute of limitations for any matter that is the subject of dispute under this chapter, is not tolled as to an individual who had a guardian ad litem, limited or general guardian of the estate, or a special representative to represent the person during the probate or dispute resolution proceeding.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5344.SL.pdf?cite=2013%20c%20272%20§%204[2013 c 272 § 4]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1051-S.SL.pdf?cite=2011%20c%20327%20§%207[2011 c 327 § 7]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20204[1999 c 42 § 204]; ]

== 11.96A.080 - Persons entitled to judicial proceedings for declaration of rights or legal relations. (Effective until January 1, 2022.)
. Subject to the provisions of RCW 11.96A.260 through 11.96A.320, any party may have a judicial proceeding for the declaration of rights or legal relations with respect to any matter, as defined by RCW 11.96A.030; the resolution of any other case or controversy that arises under the Revised Code of Washington and references judicial proceedings under this title; or the determination of the persons entitled to notice under RCW 11.96A.110 or 11.96A.120.

. The provisions of this chapter apply to disputes arising in connection with estates of incapacitated persons unless otherwise covered by *chapters 11.88 and 11.92 RCW. The provisions of this chapter shall not supersede, but shall supplement, any otherwise applicable provisions and procedures contained in this title, including without limitation those contained in chapter 11.20, 11.24, 11.28, 11.40, 11.42, or 11.56 RCW. The provisions of this chapter shall not apply to actions for wrongful death under chapter 4.20 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20301[1999 c 42 § 301]; ]

== 11.96A.090 - Judicial proceedings.
. A judicial proceeding under this title is a special proceeding under the civil rules of court. The provisions of this title governing such actions control over any inconsistent provision of the civil rules.

. A judicial proceeding under this title must be commenced as a new action.

. Once commenced, the action may be consolidated with an existing proceeding upon the motion of a party for good cause shown, or by the court on its own motion.

. The procedural rules of court apply to judicial proceedings under this title only to the extent that they are consistent with this title, unless otherwise provided by statute or ordered by the court under RCW 11.96A.020 or 11.96A.050, or other applicable rules of court.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5135-S.SL.pdf?cite=2013%20c%20246%20§%202[2013 c 246 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20302[1999 c 42 § 302]; ]

== 11.96A.100 - Procedural rules.
Unless rules of court require or this title provides otherwise, or unless a court orders otherwise:

. A judicial proceeding under RCW 11.96A.090 is to be commenced by filing a petition with the court;

. A summons must be served in accordance with this chapter and, where not inconsistent with these rules, the procedural rules of court, however, if the proceeding is commenced as an action incidental to an existing judicial proceeding relating to the same trust or estate or nonprobate asset, notice must be provided by summons only with respect to those parties who were not already parties to the existing judicial proceedings;

. The summons need only contain the following language or substantially similar language:

SUPERIOR COURT OF WASHINGTONFOR (. . .) COUNTYIN RE . . . . . .)   ) No. . . . ) Summons )  

SUPERIOR COURT OF WASHINGTON

FOR (. . .) COUNTY

IN RE . . . . . .

)

 

 

 

)

 

No. . . .

 

)

 

Summons

 

)

 

 

TO THE RESPONDENT OR OTHER INTERESTED PARTY: A petition has been filed in the superior court of Washington for (. . .) County. Petitioner's claim is stated in the petition, a copy of which is served upon you with this summons.

In order to defend against or to object to the petition, you must answer the petition by stating your defense or objections in writing, and by serving your answer upon the person signing this summons not later than five days before the date of the hearing on the petition. Your failure to answer within this time limit might result in a default judgment being entered against you without further notice. A default judgment grants the petitioner all that the petitioner seeks under the petition because you have not filed an answer.

If you wish to seek the advice of a lawyer, you should do so promptly so that your written answer, if any, may be served on time.

This summons is issued under RCW 11.96A.100(3).

(Signed) . . . . . . . . . . . .

Print or Type Name

Dated: . . . . . .

Telephone Number: . . . . . .

. Subject to other applicable statutes and court rules, the clerk of each of the superior courts shall fix the time for any hearing on a matter on application by a party, and no order of the court shall be required to fix the time or to approve the form or content of the notice of a hearing;

. The answer to the petition and any counterclaims or cross-claims must be served on the parties or the parties' virtual representatives and filed with the court at least five days before the date of the hearing, and all replies to the counterclaims and cross-claims must be served on the parties or the parties' virtual representatives and filed with the court at least two days before the date of the hearing;

. Proceedings under this chapter are subject to the mediation and arbitration provisions of this chapter. Except as specifically provided in RCW 11.96A.310, the provisions of chapter 7.06 RCW do not apply;

. Testimony of witnesses may be by affidavit;

. Unless requested otherwise by a party in a petition or answer, the initial hearing must be a hearing on the merits to resolve all issues of fact and all issues of law;

. Any party may move the court for an order relating to a procedural matter, including discovery, and for summary judgment, in the original petition, answer, response, or reply, or in a separate motion, or at any other time; and

. If the initial hearing is not a hearing on the merits or does not result in a resolution of all issues of fact and all issues of law, the court may enter any order it deems appropriate, which order may (a) resolve such issues as it deems proper, (b) determine the scope of discovery, and (c) set a schedule for further proceedings for the prompt resolution of the matter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5052-S.SL.pdf?cite=2001%20c%2014%20§%201[2001 c 14 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20303[1999 c 42 § 303]; ]

== 11.96A.110 - Notice in judicial proceedings under this title requiring notice.
. Subject to RCW 11.96A.160, in all judicial proceedings under this title that require notice, the notice must be personally served on or mailed to all parties or the parties' legal or virtual representatives and to any other persons to whom notice may be required under applicable law at least twenty days before the hearing on the petition unless a different period is provided by statute or ordered by the court. The date of service shall be determined under the rules of civil procedure. Notwithstanding the foregoing, notice that is provided in an electronic transmission and electronically transmitted complies with this section if the party receiving notice has previously consented in a record delivered to the party giving notice to receiving notice by electronic transmission. Consent to receive notice by electronic transmission may be revoked at any time by a record delivered to the party giving notice. Consent is deemed revoked if the party giving notice is unable to electronically transmit two consecutive notices given in accordance with the consent.

. Proof of the service, mailing, or electronic delivery required in this section must be made by affidavit or declaration filed at or before the hearing.

. For the purposes of this title, the terms "electronic transmission" and "electronically transmitted" have the same meaning as set forth in RCW 23B.01.400.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%204019[2021 c 140 § 4019]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1051-S.SL.pdf?cite=2011%20c%20327%20§%208[2011 c 327 § 8]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20304[1999 c 42 § 304]; ]

== 11.96A.115 - Discovery.
In all matters governed by this title, discovery shall be permitted only in the following matters:

. A judicial proceeding that places one or more specific issues in controversy that has been commenced under RCW 11.96A.100, in which case discovery shall be conducted in accordance with the superior court civil rules and applicable local rules; or

. A matter in which the court orders that discovery be permitted on a showing of good cause, in which case discovery shall be conducted in accordance with the superior court civil rules and applicable local rules unless otherwise limited by the order of the court.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6597-S.SL.pdf?cite=2006%20c%20360%20§%2011[2006 c 360 § 11]; ]

== 11.96A.120 - Application of doctrine of virtual representation. (Effective until January 1, 2022.)
. Notice to a person who may represent and bind another person under this section has the same effect as if notice were given directly to the other person.

. The consent of a person who may represent and bind another person under this section is binding on the person represented unless the person represented objects to the representation before the consent would otherwise have become effective.

. The following limitations on the ability to serve as a virtual representative apply:

.. A trustor may not represent and bind a beneficiary under this section with respect to the termination and modification of an irrevocable trust; and

.. Representation of an incapacitated trustor with respect to his or her powers over a trust is subject to the provisions of RCW 11.103.030, and chapters 11.96A, *11.88, and * 11.92 RCW.

. To the extent there is no conflict of interest between the representative and the person represented or among those being represented with respect to the particular question or dispute:

.. A guardian may represent and bind the estate that the guardian controls, subject to chapters 11.96A, *11.88, and * 11.92 RCW;

.. A guardian of the person may represent and bind the incapacitated person if a guardian of the incapacitated person's estate has not been appointed;

.. An agent having authority to act with respect to the particular question or dispute may represent and bind the principal;

.. A trustee may represent and bind the beneficiaries of the trust;

.. A personal representative of a decedent's estate may represent and bind persons interested in the estate; and

.. A parent may represent and bind the parent's minor or unborn child or children if a guardian for the child or children has not been appointed.

. Unless otherwise represented, a minor, incapacitated, or unborn individual, or a person whose identity or location is unknown and not reasonably ascertainable, may be represented by and bound by another having a substantially identical interest with respect to the particular question or dispute, but only to the extent there is no conflict of interest between the representative and the person represented with regard to the particular question or dispute.

. Where an interest has been given to persons who comprise a certain class upon the happening of a certain event, the living persons who would constitute the class as of the date the representation is to be determined may virtually represent all other members of the class as of that date, but only to the extent that there is no conflict of interest between the representative and the person(s) represented with regard to the particular question or dispute.

. Where an interest has been given to a living person, and the same interest, or a share in it, is to pass to the surviving spouse or surviving domestic partner or to persons who are, or might be, the heirs, issue, or other kindred of that living person or the distributees of the estate of that living person upon the happening of a future event, that living person may virtually represent the surviving spouse or surviving domestic partner, heirs, issue, or other kindred of the person, and the distributees of the estate of the person, but only to the extent that there is no conflict of interest between the representative and the person(s) represented with regard to the particular question or dispute.

. Except as otherwise provided in subsection (7) of this section, where an interest has been given to a person or a class of persons, or both, upon the happening of any future event, and the same interest or a share of the interest is to pass to another person or class of persons, or both, upon the happening of an additional future event, the living person or persons who would take the interest upon the happening of the first event may virtually represent the persons and classes of persons who might take on the happening of the additional future event, but only to the extent that there is no conflict of interest between the representative and the person(s) represented with regard to the particular question or dispute.

. To the extent there is no conflict of interest between the holder of the power of appointment and the persons represented with respect to the particular question or dispute, the holder of a lifetime or testamentary power of appointment may virtually represent and bind persons who are permissible appointees or takers in default (but only to the extent that they are permissible appointees in the case of a limited power of appointment) under the power, and who are not permissible distributees as defined in RCW 11.98.002.

. The attorney general may virtually represent and bind a charitable organization if:

.. The charitable organization is not a qualified beneficiary as defined in RCW 11.98.002 specified in the trust instrument or acting as trustee; or

.. The charitable organization is a qualified beneficiary, but is not a permissible distributee, as those terms are defined in RCW 11.98.002, and its beneficial interest in the trust is subject to change by the trustor or by a person designated by the trustor.

. An action taken by the court is conclusive and binding upon each person receiving actual or constructive notice or who is otherwise represented under this section.

. This section is intended to adopt the common law concept of virtual representation. This section supplements the common law relating to the doctrine of virtual representation and may not be construed as limiting the application of that common law doctrine.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5344.SL.pdf?cite=2013%20c%20272%20§%205[2013 c 272 § 5]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1051-S.SL.pdf?cite=2011%20c%20327%20§%209[2011 c 327 § 9]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3104-S2.SL.pdf?cite=2008%20c%206%20§%20928[2008 c 6 § 928]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1135-S.SL.pdf?cite=2001%20c%20203%20§%2011[2001 c 203 § 11]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20305[1999 c 42 § 305]; ]

== 11.96A.125 - Mistake of fact or law in terms of will or trust—Judicial and nonjudicial reform.
The terms of a will or trust, even if unambiguous, may be reformed by judicial proceedings under this chapter to conform the terms to the intention of the testator or trustor if it is proved by clear, cogent, and convincing evidence that both the intent of the testator or trustor and the terms of the will or trust were affected by a mistake of fact or law, whether in expression or inducement. This does not limit the ability to reform the will or trust using the binding nonjudicial procedures of RCW 11.96A.220.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5344.SL.pdf?cite=2013%20c%20272%20§%206[2013 c 272 § 6]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1051-S.SL.pdf?cite=2011%20c%20327%20§%2011[2011 c 327 § 11]; ]

== 11.96A.127 - Charitable dispositions by will or trust.
. Except as otherwise provided in subsection (2) of this section, with respect to any charitable disposition made in a will or trust, if a particular charitable purpose becomes unlawful, impracticable, impossible to achieve, or wasteful:

.. The disposition does not fail, in whole or in part;

.. The subject property does not revert to the alternative, residuary, or intestate heirs of the estate or, in the case of a trust, the trustor or the trustor's successors in interest; and

.. The court may modify or terminate the trust by directing that the property be applied or distributed, in whole or in part, in a manner consistent with the testator's or trustor's charitable purposes.

. A provision in the terms of a will or charitable trust that would result in distribution of the property to a noncharitable beneficiary prevails over the power of the court under subsection (1) of this section to modify or terminate the will provision or trust only if, when the provision takes effect:

.. The property is to revert to the trustor and the trustor is still living; or

.. Fewer than twenty-one years have elapsed since the following:

... In the case of a charitable disposition in trust, the date of the trust's creation or the date the trust became irrevocable; or

... In the case of a charitable disposition in a will, the death of the testator, in the case of a charitable disposition in a will.

. For purposes of this title, a charitable purpose is one for the relief of poverty, the advancement of education or religion, the promotion of health, governmental or municipal purposes, or other purposes the achievement of which is beneficial to a community.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1051-S.SL.pdf?cite=2011%20c%20327%20§%2010[2011 c 327 § 10]; ]

== 11.96A.130 - Special notice. (Effective until January 1, 2022.)
Nothing in this chapter eliminates the requirement to give notice to a person who has requested special notice under RCW 11.28.240 or * 11.92.150.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20306[1999 c 42 § 306]; ]

== 11.96A.140 - Waiver of notice.
Notwithstanding any other provision of this title, notice of a hearing does not need to be given to a legally competent person who has waived in writing notice of the hearing in person or by attorney, or who has appeared at the hearing without objecting to the lack of proper notice or personal jurisdiction. The waiver of notice may apply either to a specific hearing or to any and all hearings and proceedings to be held, in which event the waiver of notice is of continuing effect unless subsequently revoked by the filing of a written notice of revocation of the waiver and the mailing of a copy of the notice of revocation of the waiver to the other parties. Unless notice of a hearing is required to be given by publication, if all persons entitled to notice of the hearing waive the notice or appear at the hearing without objecting to the lack of proper notice or personal jurisdiction, the court may hear the matter immediately. A guardian of the estate or a guardian ad litem may make the waivers on behalf of the incapacitated person, and a trustee may make the waivers on behalf of any competent or incapacitated beneficiary of the trust. A consul or other representative of a foreign government, whose appearance has been entered as provided by law on behalf of any person residing in a foreign country, may make the waiver of notice on behalf of the person.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20307[1999 c 42 § 307]; ]

== 11.96A.150 - Costs—Attorneys' fees. (Effective until January 1, 2022.)
. Either the superior court or any court on an appeal may, in its discretion, order costs, including reasonable attorneys' fees, to be awarded to any party: (a) From any party to the proceedings; (b) from the assets of the estate or trust involved in the proceedings; or (c) from any nonprobate asset that is the subject of the proceedings. The court may order the costs, including reasonable attorneys' fees, to be paid in such amount and in such manner as the court determines to be equitable. In exercising its discretion under this section, the court may consider any and all factors that it deems to be relevant and appropriate, which factors may but need not include whether the litigation benefits the estate or trust involved.

. This section applies to all proceedings governed by this title, including but not limited to proceedings involving trusts, decedent's estates and properties, and guardianship matters. This section shall not be construed as being limited by any other specific statutory provision providing for the payment of costs, including RCW 11.68.070 and 11.24.050, unless such statute specifically provides otherwise. This section shall apply to matters involving guardians and guardians ad litem and shall not be limited or controlled by the provisions of *RCW 11.88.090(10).

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2236.SL.pdf?cite=2007%20c%20475%20§%205[2007 c 475 § 5]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20308[1999 c 42 § 308]; ]

== 11.96A.160 - Appointment of guardian ad litem.
. The court, upon its own motion or upon request of one or more of the parties, at any stage of a judicial proceeding or at any time in a nonjudicial resolution procedure, may appoint a guardian ad litem to represent the interests of a minor, incapacitated, unborn, or unascertained person, person whose identity or address is unknown, or a designated class of persons who are not ascertained or are not in being. If not precluded by a conflict of interest, a guardian ad litem may be appointed to represent several persons or interests.

. The court-appointed guardian ad litem supersedes the special representative if so provided in the court order.

. The court may appoint the guardian ad litem at an ex parte hearing, or the court may order a hearing as provided in RCW 11.96A.090 with notice as provided in this section and RCW 11.96A.110.

. The guardian ad litem is entitled to reasonable compensation for services. Such compensation is to be paid from the principal of the estate or trust whose beneficiaries are represented.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20309[1999 c 42 § 309]; ]

== 11.96A.170 - Trial by jury.
If a party is entitled to a trial by jury and a jury is demanded, and the issues are not sufficiently made up by the written pleadings on file, the court, on due notice, shall settle and frame the issues to be tried. If a jury is not demanded, the court shall try the issues, and sign and file its findings and decision in writing, as provided for in civil actions.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20310[1999 c 42 § 310]; ]

== 11.96A.180 - Execution on judgments.
Judgment on the issues, as well as for costs, may be entered and enforced by execution or otherwise by the court as in civil actions.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20311[1999 c 42 § 311]; ]

== 11.96A.190 - Execution upon trust income or vested remainder—Permitted, when.
Nothing in RCW 6.32.250 shall forbid execution upon the income of any trust created by a person other than the judgment debtor for debt arising through the furnishing of the necessities of life to the beneficiary of such trust; or as to such income forbid the enforcement of any order of the superior court requiring the payment of support for the children under the age of eighteen of any beneficiary; or forbid the enforcement of any order of the superior court subjecting the vested remainder of any such trust upon its expiration to execution for the debts of the remainderman.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20312[1999 c 42 § 312]; ]

== 11.96A.200 - Appellate review.
An interested party may seek appellate review of a final order, judgment, or decree of the court respecting a judicial proceeding under this title. The review must be done in the manner and way provided by law for appeals in civil actions.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20313[1999 c 42 § 313]; ]

== 11.96A.210 - Purpose.
The purpose of RCW 11.96A.220 through 11.96A.250 is to provide a binding nonjudicial procedure to resolve matters through written agreements among the parties interested in the estate or trust. The procedure is supplemental to, and may not derogate from, any other proceeding or provision authorized by statute or the common law.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20401[1999 c 42 § 401]; ]

== 11.96A.220 - Binding agreement. (Effective until January 1, 2022.)
RCW 11.96A.210 through 11.96A.250 shall be applicable to the resolution of any matter, as defined by RCW 11.96A.030, other than matters subject to *chapter 11.88 or 11.92 RCW, or a trust for a minor or other incapacitated person created at its inception by the judgment or decree of a court unless the judgment or decree provides that RCW 11.96A.210 through 11.96A.250 shall be applicable. If all parties agree to a resolution of any such matter, then the agreement shall be evidenced by a written agreement signed by all parties. Subject to the provisions of RCW 11.96A.240, the written agreement shall be binding and conclusive on all persons interested in the estate, trust, nonprobate asset, other property passing at death, or custodial property. The agreement shall identify the subject matter of the dispute and the parties. If the agreement or a memorandum of the agreement is to be filed with the court under RCW 11.96A.230, the agreement may, but need not, include provisions specifically addressing jurisdiction, governing law, the waiver of notice of the filing as provided in RCW 11.96A.230, and the discharge of any special representative who has acted with respect to the agreement.

If a party who virtually represents another under RCW 11.96A.120 signs the agreement, then the party's signature constitutes the signature of all persons whom the party virtually represents, and all the virtually represented persons shall be bound by the agreement.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%204020[2021 c 140 § 4020]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20402[1999 c 42 § 402]; ]

== 11.96A.230 - Entry of agreement with court—Effect.
. Any party, or a party's legal representative, may file the written agreement or a memorandum summarizing the written agreement with the court having jurisdiction over the estate or trust. The agreement or a memorandum of its terms may be filed within thirty days of the agreement's execution by all parties only with the written consent of the special representative. The agreement or a memorandum of its terms may be filed after a special representative has commenced a proceeding under RCW 11.96A.240 only after the court has determined that the special representative has adequately represented and protected the parties represented. Failure to complete any action authorized or required under this subsection does not cause the written agreement to be ineffective and the agreement is nonetheless binding and conclusive on all persons interested in the estate or trust.

. On filing the agreement or memorandum, the agreement will be deemed approved by the court and is equivalent to a final court order binding on all persons interested in the estate, trust, nonprobate asset, other property passing at death, or custodial property.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%204022[2021 c 140 § 4022]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5052-S.SL.pdf?cite=2001%20c%2014%20§%202[2001 c 14 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20403[1999 c 42 § 403]; ]

== 11.96A.240 - Judicial approval of agreement.
Within thirty days of execution of the agreement by all parties, the special representative may note a hearing for presentation of the written agreement to a court of competent jurisdiction. The special representative shall provide notice of the time and date of the hearing to each party to the agreement whose address is known, unless such notice has been waived. Proof of mailing or delivery of the notice must be filed with the court. At such hearing the court shall review the agreement on behalf of the parties represented by the special representative. The court shall determine whether or not the interests of the represented parties have been adequately represented and protected, and an order declaring the court's determination shall be entered. If the court determines that such interests have not been adequately represented and protected, the agreement shall be declared of no effect.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20404[1999 c 42 § 404]; ]

== 11.96A.250 - Special representative.
. [Empty]
.. Any party or the parent of a minor or unborn party may petition the court for the appointment of a special representative to represent a party: (i) Who is a minor; (ii) who is incapacitated without an appointed guardian of his or her estate; (iii) who is yet unborn or unascertained; or (iv) whose identity or address is unknown. The petition may be heard by the court without notice.

.. In appointing the special representative the court shall give due consideration and deference to any nomination(s) made in the petition, the special skills required in the representation, and the need for a representative who will act independently and prudently. The nomination of a person as special representative by the petitioner and the person's willingness to serve as special representative are not grounds by themselves for finding a lack of independence, however, the court may consider any interests that the nominating party may have in the estate or trust in making the determination.

.. The special representative may enter into a binding agreement on behalf of the person or beneficiary. The special representative may be appointed for more than one person or class of persons if the interests of such persons or class are not in conflict. The petition must be verified. The petition and order appointing the special representative may be in the following form:

CAPTIONPETITION FOR APPOINTMENTOF CASEOF SPECIAL REPRESENTATIVE UNDER RCW 11.96A.250

CAPTION

PETITION FOR APPOINTMENT

OF CASE

OF SPECIAL REPRESENTATIVE

 

UNDER RCW 11.96A.250

The undersigned petitioner petitions the court for the appointment of a special representative in accordance with RCW 11.96A.250 and shows the court as follows:

1. Petitioner. Petitioner . . . [is the qualified and presently acting (personal representative) (trustee) of the above (estate) (trust) having been named (personal representative) (trustee) under (describe will and reference probate order or describe trust instrument)] or [is the (describe relationship of the petitioner to the party to be represented or to the matter at issue)].

2. Matter. A question concerning . . . has arisen as to (describe issue, for example: Related to interpretation, construction, administration, distribution). The issue is a matter as defined in RCW 11.96A.030 and is appropriate for determination under RCW 11.96A.210 through 11.96A.250.

3. Party/Parties to be Represented. This matter involves (include description of asset(s) and related beneficiaries and/or interested parties). Resolution of this matter will require the involvement of . . . . . . (name of person or class of persons), who is/are (minors), (incapacitated and without an appointed guardian), (unborn or unascertained) (whose identity or address is unknown).

4. Special Representative. The nominated special representative . . . is a lawyer licensed to practice before the courts of this state or an individual with special skill or training in the administration of estates or trusts. The nominated special representative does not have an interest in the matter and is not related to any person interested in the matter. The nominated special representative is willing to serve. The petitioner has no reason to believe that the nominated special representative will not act in an independent and prudent manner and in the best interests of the represented parties. (It is recommended that the petitioner also include information specifying the particular skills of the nominated special representative that relate to the matter in issue.)

5. Resolution. Petitioner desires to achieve a resolution of the questions that have arisen in this matter. Petitioner believes that proceeding in accordance with the procedures permitted under RCW 11.96A.210 through 11.96A.250 would be in the best interests of the parties, including the party requiring a special representative.

6. Request of Court. Petitioner requests that . . . . . . an attorney licensed to practice in the State of Washington,

(OR)

. . . . an individual with special skill or training in the administration of estates or trusts

be appointed special representative for . . . (describe party or parties being represented), who is/are (minors), (incapacitated and without an appointed guardian), (unborn or unascertained) (whose identity or address is unknown), as provided under RCW 11.96A.250.

DATED this . . . day of . . . . ., . . . .

. . . . . . . . . . . . . . .

(Petitioner)

VERIFICATION

I certify under penalty of perjury under the laws of the state of Washington that the foregoing is true and correct.

DATED . . . . . ., . . . . (year), at . . . . . ., Washington.

. . . . . . . . . . . . . . .

(Petitioner or other person

having knowledge)

CAPTIONPETITION FOR APPOINTMENTOF CASEOF SPECIAL REPRESENTATIVE UNDER RCW 11.96A.250

CAPTION

PETITION FOR APPOINTMENT

OF CASE

OF SPECIAL REPRESENTATIVE

 

UNDER RCW 11.96A.250

THIS MATTER having come on for hearing before this Court on Petition for Appointment of Special Representative filed herein, and it appearing that it would be in the best interests of the parties related to the matter described in the Petition to appoint a special representative to address the issues that have arisen in the matter and the Court finding that the facts stated in the Petition are true, now, therefore,

IT IS ORDERED that . . . is appointed under RCW 11.96A.250 as special representative (describe party or parties being represented) who is/are (minors), (incapacitated and without an appointed guardian), (unborn or unascertained) (whose identity or address is unknown), to represent their respective interests in the matter as provided in RCW 11.96A.250. The special representative shall be discharged of responsibility with respect to the matter as provided in RCW 11.96A.250. The special representative is discharged of responsibility with respect to the matter at such time as a written agreement is executed resolving the present issues, all as provided in that statute, or if an agreement is not reached within six months from entry of this Order, the special representative appointed under this Order is discharged of responsibility, subject to subsequent reappointment under RCW 11.96A.250.

DONE IN OPEN COURT this . . . day of . . . . ., . . . .

. . . . . . . . . . . . . . .

JUDGE/COURT COMMISSIONER

. Upon appointment by the court, the special representative must file a certification made under penalty of perjury in accordance with chapter 5.50 RCW that he or she (a) is not interested in the matter; (b) is not related to any person interested in the matter; (c) is willing to serve; and (d) will act independently, prudently, and in the best interests of the represented parties.

. The special representative must be a lawyer licensed to practice before the courts of this state or an individual with special skill or training in the administration of estates or trusts. The special representative may not have an interest in the matter, and may not be related to a person interested in the matter. The special representative is entitled to reasonable compensation for services that must be paid from the principal of an asset involved in the matter.

. The special representative is discharged from any responsibility and will have no further duties with respect to the matter or with respect to any party, on the earlier of: (a) The expiration of six months from the date the special representative was appointed unless the order appointing the special representative provides otherwise, or (b) the execution of the written agreement by all parties or their virtual representatives. Any action against a special representative must be brought within the time limits provided by RCW 11.96A.070(3)(c)(i).

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5017-S.SL.pdf?cite=2019%20c%20232%20§%2012[2019 c 232 § 12]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5344.SL.pdf?cite=2013%20c%20272%20§%2021[2013 c 272 § 21]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5052-S.SL.pdf?cite=2001%20c%2014%20§%203[2001 c 14 § 3]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20405[1999 c 42 § 405]; ]

== 11.96A.260 - Findings—Intent.
The legislature finds that it is in the interest of the citizens of the state of Washington to encourage the prompt and early resolution of disputes in trust, estate, and nonprobate matters. The legislature endorses the use of dispute resolution procedures by means other than litigation. The legislature also finds that the former chapter providing for the nonjudicial resolution of trust, estate, and nonprobate disputes, *chapter 11.96 RCW, has resulted in the successful resolution of thousands of disputes since 1984. The nonjudicial procedure has resulted in substantial savings of public funds by removing those disputes from the court system. Enhancement of the statutory framework supporting the nonjudicial process in *chapter 11.96 RCW would be beneficial and would foster even greater use of nonjudicial dispute methods to resolve trust, estate, and nonprobate disputes. The legislature further finds that it would be beneficial to allow parties to disputes involving trusts, estates, and nonprobate assets to have access to a process for required mediation followed by arbitration using mediators and arbitrators experienced in trust, estate, and nonprobate matters. Finally, the legislature also believes it would be beneficial to parties with disputes in trusts, estates, and nonprobate matters to clarify and streamline the statutory framework governing the procedures governing these cases in the court system.

Therefore, the legislature adopts RCW 11.96A.270 through 11.96A.320, that enhance *chapter 11.96 RCW and allow required mediation and arbitration in disputes involving trusts, estates, and nonprobate matters that are brought to the courts. RCW 11.96A.270 through 11.96A.320 also set forth specific civil procedures for handling trust and estate disputes in the court system. It is intended that the adoption of RCW 11.96A.270 through 11.96A.320 will encourage and direct all parties in trust, estate, and nonprobate matter disputes, and the court system, to provide for expeditious, complete, and final decisions to be made in disputed trust, estate, and nonprobate matters.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20501[1999 c 42 § 501]; ]

== 11.96A.270 - Intent—Parties can agree otherwise.
The intent of RCW 11.96A.260 through 11.96A.320 is to provide for the efficient settlement of disputes in trust, estate, and nonprobate matters through mediation and arbitration by providing any party the right to proceed first with mediation and then arbitration before formal judicial procedures may be utilized. Accordingly, any of the requirements or rights under RCW 11.96A.260 through 11.96A.320 are subject to any contrary agreement between the parties or the parties' virtual representatives.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20502[1999 c 42 § 502]; ]

== 11.96A.280 - Scope.
A party may cause the matter to be presented for mediation and then arbitration, as provided under RCW 11.96A.260 through 11.96A.320. If a party causes the matter to be presented for resolution under RCW 11.96A.260 through 11.96A.320, then judicial resolution of the matter, as provided in RCW 11.96A.060 or by any other civil action, is available only by complying with the mediation and arbitration provisions of RCW 11.96A.260 through 11.96A.320.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20503[1999 c 42 § 503]; ]

== 11.96A.290 - Superior court—Venue.
As used in RCW 11.96A.260 through 11.96A.320, "superior court" means: (1) Before the commencement of any legal proceedings, the appropriate superior court with respect to the matter as provided in RCW 11.96A.040; and (2) if legal proceedings have been commenced with respect to the matter, the superior court in which the proceedings are pending.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20504[1999 c 42 § 504]; ]

== 11.96A.300 - Mediation procedure.
. Notice of mediation. A party may cause the matter to be subject to mediation by service of written notice of mediation on all parties or the parties' virtual representatives as follows:

.. If no hearing has been set. If no hearing on the matter has been set, by serving notice in substantially the following form before any petition setting a hearing on the matter is filed with the court:

NOTICE OF MEDIATION UNDER RCW 11.96A.300

To: (Parties)

Notice is hereby given that the following matter shall be resolved by mediation under RCW 11.96A.300:

(State nature of matter)

This matter must be resolved using the mediation procedures of RCW 11.96A.300 unless a petition objecting to mediation is filed with the superior court within twenty days of service of this notice. If a petition objecting to mediation is not filed within the twenty-day period, RCW 11.96A.300(4) requires you to furnish to all other parties or their virtual representatives a list of acceptable mediators within thirty days of your receipt of this notice.

(Optional: Our list of acceptable mediators is as follows:)

DATED: . . . . . .

. . . .

(Party or party's legal representative)

.. If a hearing has been set. If a hearing on the matter has been set, by filing and serving notice in substantially the following form at least three days prior to the hearing that has been set on the matter:

NOTICE OF MEDIATION UNDER RCW 11.96A.300

To: (Parties)

Notice is hereby given that the following matter shall be resolved by mediation under RCW 11.96A.300:

(State nature of matter)

This matter must be resolved using the mediation procedures of RCW 11.96A.300 unless the court determines at the hearing set for . . . o'clock on . . . . . , (identify place of already set hearing), that mediation shall not apply pursuant to RCW 11.96A.300(3). If the court determines that mediation shall not apply, the court may decide the matter at the hearing, require arbitration, or direct other judicial proceedings.

(Optional: Our list of acceptable mediators is as follows:)

DATED: . . . . . .

. . . .

(Party or party's legal representative)

. Procedure when notice of mediation served before a hearing is set. The following provisions apply when notice of mediation is served before a hearing on the matter is set:

.. The written notice required in subsection (1)(a) of this section may be served at any time without leave of the court.

.. Any party may object to a notice of mediation under subsection (1)(a) of this section by filing a petition with the superior court and serving the petition on all parties or the parties' virtual representatives. The party objecting to notice of mediation under subsection (1)(a) of this section must file and serve the petition objecting to mediation no later than twenty days after receipt of the written notice of mediation. The petition may include a request for determination of matters subject to judicial resolution under RCW 11.96A.080 through 11.96A.200, and may also request that the matters in issue be decided at the hearing.

.. The hearing on the petition objecting to mediation must be heard no later than twenty days after the filing of that petition.

.. The party objecting to mediation must give notice of the hearing to all other parties at least ten days before the hearing and must include a copy of the petition.

At the hearing, the court shall order that mediation proceed except for good cause shown. Such order shall not be subject to appeal or revision. If the court determines that the matter should not be subject to mediation, the court shall dispose of the matter by: (i) Deciding the matter at that hearing, but only if the petition objecting to mediation contains a request for that relief, (ii) requiring arbitration, or (iii) directing other judicial proceedings.

. Procedure when notice of mediation served after hearing set. If the written notice of mediation required in subsection (1)(b) of this section is timely filed and served by a party and another party objects to mediation, by petition or orally at the hearing, the court shall order that mediation proceed except for good cause shown. Such order shall not be subject to appeal or revision. If the court determines that the matter should not be subject to mediation, the court shall dispose of the matter by: (a) Deciding the matter at that hearing, (b) requiring arbitration, or (c) directing other judicial proceedings.

. Selection of mediator; mediator qualifications.

.. If a petition objecting to mediation is not filed as provided in subsection (3) of this section, or if a court determines that mediation shall apply, each party shall, within thirty days of receipt of the initial notice or within twenty days after the court determination, whichever is later, furnish all other parties or the parties' virtual representatives a list of qualified and acceptable mediators. If the parties cannot agree on a mediator within ten days after the list is required to be furnished, a party may petition the court to appoint a mediator. All parties may submit a list of qualified and acceptable mediators to the court no later than the date on which the hearing on the petition is to be held. At the hearing the court shall select a qualified mediator from lists of acceptable mediators provided by the parties.

.. A qualified mediator must be: (i) An attorney licensed to practice before the courts of this state having at least five years of experience in estate and trust matters, (ii) an individual, who may be an attorney, with special skill or training in the administration of trusts and estates, or (iii) an individual, who may be an attorney, with special skill or training as a mediator. The mediator may not have an interest in an affected estate, trust, or nonprobate asset, and may not be related to a party.

. Date for mediation. Upon designation of a mediator by the parties or court appointment of a mediator, the mediator and the parties or the parties' virtual representatives shall establish a date for the mediation. If a date cannot be agreed upon within ten days of the designation or appointment of the mediator, a party may petition the court to set a date for the mediation session.

. Duration of mediation. The mediation must last at least three hours unless the matter is earlier resolved.

. Mediation agreement. A resolution of the matter that is the subject of the mediation must be evidenced by a nonjudicial dispute resolution agreement under RCW 11.96A.220.

. Costs of mediation. Costs of the mediation, including reasonable compensation for the mediator's services, shall be borne equally by the parties. The details of those costs and fees, including the compensation of the mediator, must be set forth in a mediation agreement between the mediator and all parties to the matter. Each party shall bear its own costs and expenses, including legal fees and witness expenses, in connection with the mediation proceeding: (a) Except as may occur otherwise as provided in RCW 11.96A.320, or (b) unless the matter is not resolved by mediation and the arbitrator or court finally resolving the matter directs otherwise.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5052-S.SL.pdf?cite=2001%20c%2014%20§%204[2001 c 14 § 4]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20505[1999 c 42 § 505]; ]

== 11.96A.310 - Arbitration procedure.
. When arbitration available. Arbitration under RCW 11.96A.260 through 11.96A.320 is available only if:

.. A party has first petitioned for mediation under RCW 11.96A.300 and such mediation has been concluded;

.. The court has determined that mediation under RCW 11.96A.300 is not required and has not ordered that the matter be disposed of in some other manner;

.. All of the parties or the parties' virtual representatives have agreed not to use the mediation procedures of RCW 11.96A.300; or

.. The court has ordered that the matter must be submitted to arbitration.

. Commencement of arbitration. Arbitration must be commenced as follows:

.. If the matter is not settled through mediation under RCW 11.96A.300, or the court orders that mediation is not required, a party may commence arbitration by serving written notice of arbitration on all other parties or the parties' virtual representatives. The notice must be served no later than twenty days after the later of the conclusion of the mediation procedure, if any, or twenty days after entry of the order providing that mediation is not required. If arbitration is ordered by the court under RCW 11.96A.300(3), arbitration must proceed in accordance with the order.

.. If the parties or the parties' virtual representatives agree that mediation does not apply and have not agreed to another procedure for resolving the matter, a party may commence arbitration without leave of the court by serving written notice of arbitration on all other parties or the parties' virtual representatives at any time before or at the initial judicial hearing on the matter. After the initial judicial hearing on the matter, the written notice required in subsection (1) of this section may only be served with leave of the court.

Any notice required by this section must be in substantially the following form:

NOTICE OF ARBITRATION UNDER RCW 11.96A.310

To: (Parties)

Notice is hereby given that the following matter must be resolved by arbitration under RCW 11.96A.310:

(State nature of matter)

The matter must be resolved using the arbitration procedures of RCW 11.96A.310 unless a petition objecting to arbitration is filed with the superior court within twenty days of receipt of this notice. If a petition objecting to arbitration is not filed within the twenty-day period, RCW 11.96A.310 requires you to furnish to all other parties or the parties' virtual representatives a list of acceptable arbitrators within thirty days of your receipt of this notice.

(Optional: Our list of acceptable arbitrators is as follows:)

DATED: . . . . . .

. . . .

(Party or party's legal representative)

. Objection to arbitration. A party may object to arbitration by filing a petition with the superior court and serving the petition on all parties or the parties' virtual representatives. The objection to arbitration may be filed at any time unless a written notice of arbitration has been served, in which case the objection to arbitration must be filed and served no later than twenty days after receipt of the written notice of arbitration. The hearing on the objection to arbitration must be heard no later than twenty days after the filing of that petition. The party objecting to arbitration must give notice of the hearing to all parties at least ten days before the hearing and shall include a copy of the petition. At the hearing, the court shall order that arbitration proceed except for good cause shown. Such order shall not be subject to appeal or revision. If the court determines that the matter should not be subject to arbitration, the court shall dispose of the matter by: (a) Deciding the matter at that hearing, but only if the petition objecting to arbitration contains a request for such relief; or (b) directing other judicial proceedings.

. Selection of arbitrator; qualifications of arbitrator.

.. If a petition objecting to arbitration is not filed as provided in subsection (3) of this section, or if a court determines that arbitration must apply, each party shall, within thirty days of receipt of the initial notice or within twenty days after the court determination, whichever is later, furnish all other parties or the parties' virtual representatives a list of acceptable arbitrators. If the parties cannot agree on an arbitrator within ten days after the list is required to be furnished, a party may petition the court to appoint an arbitrator. All parties may submit a list of qualified and acceptable arbitrators to the court no later than the date on which the hearing on the petition is to be held. At the hearing the court shall select a qualified arbitrator from lists of acceptable arbitrators provided by the parties.

.. A qualified arbitrator must be an attorney licensed to practice before the courts of this state having at least five years of experience in trust or estate matters or five years of experience in litigation or other formal dispute resolution involving trusts or estates, or an individual, who may be an attorney, with special skill or training with respect to the matter. The arbitrator may be the same person selected and used as a mediator under the mediation procedures of RCW 11.96A.300.

. Arbitration rules. Arbitration must be under *chapter 7.06 RCW, mandatory arbitration of civil actions, as follows:

.. Chapter 7.06 RCW, the superior court mandatory arbitration rules adopted by the supreme court, and any local rules for mandatory arbitration adopted by the superior court apply to this title. If the superior court has not adopted chapter 7.06 RCW, then the local rules for mandatory arbitration applicable in King county apply, except all the duties of the director of arbitration must be performed by the presiding judge of the superior court.

.. If a party has already filed a petition with the court with respect to the matter that will be the subject of the arbitration proceedings, then all other parties to the arbitration proceedings who have not yet filed a reply thereto must file a reply with the arbitrator within ten days of the date on which the arbitrator is selected or appointed.

.. The arbitration provisions of this subsection apply to all matters in dispute. The dollar limits and restrictions to monetary damages of RCW 7.06.020 do not apply to arbitrations under this subsection. To the extent any provision in this title is inconsistent with chapter 7.06 RCW or the rules referenced in (a) of this subsection, the provisions of this title control.

.. The compensation of the arbitrator must be set by written agreement between the parties and the arbitrator. The arbitrator must be compensated at the arbitrator's stated rate of compensation for acting as an arbitrator of disputes in trusts, estates, and nonprobate matters unless the parties or the parties' virtual representatives agree otherwise.

.. Unless directed otherwise by the arbitrator in accord with subsection (6) of this section or RCW 11.96A.320, or unless the matter is not resolved by arbitration and the court finally resolving the matter directs otherwise:

... Costs of the arbitration, including compensation for the arbitrator's services, must be borne equally by the parties participating in the arbitration, with the details of those costs and fees to be set forth in an arbitration agreement between the arbitrator and all parties to the matter; and

... A party shall bear its own costs and expenses, including legal fees and witness expenses, in connection with the arbitration proceeding.

.. The arbitrator and the parties shall execute a written agreement setting forth the terms of the arbitration and the process to be followed. This agreement must also contain the fee agreement provided in (d) of this subsection. A dispute as to this agreement must be resolved by the director of arbitration.

.. The rules of evidence and discovery applicable to civil causes of action before the superior court as defined in RCW 11.96A.290 apply, unless the parties have agreed otherwise or the arbitrator rules otherwise.

. Costs of arbitration. The arbitrator may order costs, including reasonable attorneys' fees and expert witness fees, to be paid by any party to the proceedings as justice may require.

. Decision of arbitrator. The arbitrator shall issue a final decision in writing within thirty days of the conclusion of the final arbitration hearing. Promptly after the issuance of the decision, the arbitrator shall serve each of the parties to the proceedings with a copy of the written arbitration decision. Proof of service shall be filed with the court. Service shall be made in conformity with CR 5(b) of the rules for superior court.

. Arbitration decision may be filed with the court. The arbitrator or any party to the arbitration may file the arbitrator's decision with the clerk of the superior court at any time after its issuance. Notice of such filing shall be promptly given to each party to the arbitration proceedings.

. Appeal. (a) The final decision of the arbitrator may be appealed by filing a notice of appeal with the superior court requesting a trial de novo on all issues of law and fact. The notice of appeal must be filed within thirty days after the date on which the decision was served on the party filing the notice of appeal. A trial de novo shall then be held, including a right to jury, if demanded.

.. If an appeal is not filed within the time provided in (a) of this subsection, the arbitration decision is conclusive and binding on all parties. If the arbitrator's decision has been filed with the clerk of the superior court, a judgment shall be entered and may be presented to the court by any party on ten days' prior notice. The judgment when entered shall have the same force and effect as judgments in civil actions.

. Costs on appeal of arbitration decision. The prevailing party in any such de novo superior court decision after an arbitration result must be awarded costs, including expert witness fees and attorneys' fees, in connection with the judicial resolution of the matter. Such costs shall be charged against the nonprevailing parties in such amount and in such manner as the court determines to be equitable. The provisions of this subsection take precedence over the provisions of RCW 11.96A.150 or any other similar provision.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5052-S.SL.pdf?cite=2001%20c%2014%20§%205[2001 c 14 § 5]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20506[1999 c 42 § 506]; ]

== 11.96A.320 - Petition for order compelling compliance.
If a party does not comply with any procedure of RCW 11.96A.260 through 11.96A.310, the other party or parties may petition the superior court for an order compelling compliance. A party obtaining an order compelling compliance is entitled to reimbursement of costs and attorneys' fees incurred in connection with: The petition and any other actions taken after the issuance of the order to compel compliance with the order, unless the court at the hearing on the petition determines otherwise for good cause shown. Reimbursement must be from the party or parties whose failure to comply was the basis for the petition.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20507[1999 c 42 § 507]; ]

== 11.96A.900 - Short title.
This chapter may be known and cited as the trust and estate dispute resolution act or "TEDRA."

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20101[1999 c 42 § 101]; ]

== 11.96A.902 - Effective date—1999 c 42.
This act takes effect January 1, 2000.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20703[1999 c 42 § 703]; ]

