= 11.76 - Settlement of estates.
:toc:

== 11.76.010 - Report of personal representative—Contents—Interim reports.
Not less frequently than annually from the date of qualification, unless a final report has theretofore been rendered, the personal representative shall make, verify by his or her oath, and file with the clerk of the court a report of the affairs of the estate. Such report shall contain a statement of the claims filed and allowed and all those rejected, and if it be necessary to sell, mortgage, lease, or exchange any property for the purpose of paying debts or settling any obligations against the estate or expenses of administration or allowance to the family, he or she may in such report set out the facts showing such necessity and ask for such sale, mortgage, lease, or exchange; such report shall likewise state the amount of property, real and personal, which has come into his or her hands, and give a detailed statement of all sums collected by him or her, and of all sums paid out, and it shall state such other things and matters as may be proper or necessary to give the court full information regarding any transactions by him or her done or which should be done. Such personal representative may at any time, however, make, verify, and file any reports which in his or her judgment would be proper or which the court may order to be made.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202061[2010 c 8 § 2061]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.76.010[1965 c 145 § 11.76.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20159[1917 c 156 § 159]; RRS § 1529; prior: Code 1881 § 1544; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20296%20§%20167[1854 p 296 § 167]; ]

== 11.76.020 - Notice of hearing—Settlement of report.
It shall not be necessary for the personal representative to give any notice of the hearing of any report prior to the final report, except as in RCW 11.28.240 provided, but the court may require notice of the hearing of any such report.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.76.020[1965 c 145 § 11.76.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20160[1917 c 156 § 160]; RRS § 1530; ]

== 11.76.030 - Final report and petition for distribution—Contents.
When the estate shall be ready to be closed, such personal representative shall make, verify, and file with the court his or her final report and petition for distribution. Such final report and petition shall, among other things, show that the estate is ready to be settled and shall show any moneys collected since the previous report, and any property which may have come into the hands of the personal representative since his or her previous report, and debts paid, and generally the condition of the estate at that time. It shall likewise set out the names and addresses, as nearly as may be, of all the legatees and devisees in the event there shall have been a will, and the names and addresses, as nearly as may be, of all the heirs who may be entitled to share in such estate, and shall give a particular description of all the property of the estate remaining undisposed of, and shall set out such other matters as may tend to inform the court of the condition of the estate, and it may ask the court for a settlement of the estate and distribution of property and the discharge of the personal representative. If the personal representative has been discharged without having legally closed the estate, without having legally obtained an adjudication as to the heirs, or without having legally procured a decree of distribution or final settlement the court may in its discretion upon petition of any person interested, cause all such steps to be taken in such estate as were omitted or defective.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202062[2010 c 8 § 2062]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.76.030[1965 c 145 § 11.76.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20161[1917 c 156 § 161]; RRS § 1531; prior:  1891 c 155 § 34; Code 1881 § 1556; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20305%20§%20251[1873 p 305 § 251]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20297%20§%20178[1854 p 297 § 178]; ]

== 11.76.040 - Time and place of hearing—Notice.
When such final report and petition for distribution, or either, has been filed, the court, or the clerk of the court, shall fix a day for hearing it which must be at least twenty days subsequent to the day of the publication as hereinafter provided. Notice of the time and place fixed for the hearing shall be given by the personal representative by publishing a notice thereof in a legal newspaper published in the county for one publication at least twenty days preceding the time fixed for the hearing. It shall state in substance that a final report and petition for distribution have, or either thereof has, been filed with the clerk of the court and that the court is asked to settle such report, distribute the property to the heirs or persons entitled thereto, and discharge the personal representative, and it shall give the time and place fixed for the hearing of such final report and petition and shall be signed by the personal representative or the clerk of the court.

Whenever a final report and petition for distribution, or either, shall have been filed in the estate of a decedent and a day fixed for the hearing of the same, the personal representative of such estate shall, not less than twenty days before the hearing, cause to be mailed a copy of the notice of the time and place fixed for hearing to each heir, legatee, devisee and distributee whose name and address are known to him or her, and proof of such mailing shall be made by affidavit and filed at or before the hearing.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202063[2010 c 8 § 2063]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c70.pdf?cite=1969%20c%2070%20§%203[1969 c 70 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.76.040[1965 c 145 § 11.76.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c205.pdf?cite=1955%20c%20205%20§%2013[1955 c 205 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c31.pdf?cite=1919%20c%2031%20§%201[1919 c 31 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20162[1917 c 156 § 162]; RRS § 1532. FORMER PART OF SECTION: re Notice of appointment as personal representative, now codified as RCW  11.28.237; ]

== 11.76.050 - Hearing on final report—Decree of distribution.
Upon the date fixed for the hearing of such final report and petition for distribution, or either thereof, or any day to which such hearing may have been adjourned by the court, if the court be satisfied that the notice of the time and place of hearing has been given as provided herein, it may proceed to the hearing aforesaid. Any person interested may file objections to the said report and petition for distribution, or may appear at the time and place fixed for the hearing thereof and present his or her objections thereto. The court may take such testimony as to it appears proper or necessary to determine whether the estate is ready to be settled, and whether the transactions of the personal representative should be approved, and to determine who are the legatees or heirs or persons entitled to have the property distributed to them, and the court shall, if it approves such report, and finds the estate ready to be closed, cause to be entered a decree approving such report, find and adjudge the persons entitled to the remainder of the estate, and that all debts have been paid, and by such decree shall distribute the real and personal property to those entitled to the same. Upon the production of receipts from the beneficiaries or distributees for their portions of the estate, the court shall, if satisfied with the correctness thereof, adjudge the estate closed and discharge the personal representative.

The court may, upon such final hearing, partition among the persons entitled thereto, the estate held in common and undivided, and designate and distribute their respective shares; or assign the whole or any part of said estate to one or more of the persons entitled to share therein. The person or persons to whom said estate is assigned shall pay or secure to the other parties interested in said estate their just proportion of the value thereof as determined by the court from the appraisement, or from any other evidence which the court may require.

If it shall appear to the court at or prior to any final hearing that the estate cannot be fairly divided, then the whole or any part of said estate may be sold or mortgaged in the manner provided by law for the sale or mortgaging of property by personal representatives and the proceeds thereof distributed to the persons entitled thereto as provided in the final decree.

The court shall have the authority to make partition, distribution and settlement of all estates in any manner which to the court seems right and proper, to the end that such estates may be administered and distributed to the persons entitled thereto. No estate shall be partitioned, nor sale thereof made where partition is impracticable except upon a hearing before the court and the court shall fix the values of the several pieces or parcels to be partitioned at the time of making such order of partition or sale; and may order the property sold and the proceeds distributed, or may order partition and distribute the several pieces or parcels, subject to such charges or burdens as shall be proper and equitable.

The provisions of this section shall be concurrent with and not in derogation of other statutes as to partition of property or sale.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202064[2010 c 8 § 2064]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.76.050[1965 c 145 § 11.76.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c93.pdf?cite=1921%20c%2093%20§%201[1921 c 93 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20163[1917 c 156 § 163]; RRS § 1533; prior: Code 1881 § 1557; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20297%20§%20179[1854 p 297 § 179]; ]

== 11.76.060 - Continuance to cite in sureties on bond when account incorrect.
If, at any hearing upon any report of any personal representative, it shall appear to the court before which said proceeding is pending that said personal representative has not fully accounted to the beneficiaries of his or her trust and that said report should not be approved as rendered, the court may continue said hearing to a day certain and may cite the surety upon the bond of said personal representative to appear upon the date fixed in said citation and show cause why the account should not be disapproved and judgment entered for any deficiency against said personal representative and the surety upon his or her bond. Said citation shall be personally served upon said surety in the manner provided by law for the service of summons in civil actions and shall be served not less than twenty days previous to said hearing. At said hearing any interested party, including the surety so cited, shall have the right to introduce any evidence which shall be material to the matter before the court. If, at said hearing, the report of said personal representative shall not be approved and the court shall find that said personal representative is indebted to the beneficiary of his or her trust in any amount, the court may thereupon enter final judgment against said personal representative and the surety upon his or her bond, which judgment shall be enforceable in the same manner and to the same extent as judgments in ordinary civil actions.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202065[2010 c 8 § 2065]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.76.060[1965 c 145 § 11.76.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c28.pdf?cite=1937%20c%2028%20§%201[1937 c 28 § 1]; RRS § 1590-1; ]

== 11.76.070 - Attorney's fees to contestant of erroneous account or report.
If, in any probate or guardianship proceeding, any personal representative shall fail or neglect to report to the court concerning his or her trust and any beneficiary or other interested party shall be reasonably required to employ legal counsel to institute legal proceedings to compel an accounting, or if an erroneous account or report shall be rendered by any personal representative and any beneficiary of said trust or other interested party shall be reasonably required to employ legal counsel to resist said account or report as rendered, and upon a hearing an accounting shall be ordered, or the account as rendered shall not be approved, and the said personal representative shall be charged with further liability, the court before which said proceeding is pending may, in its discretion, in addition to statutory costs, enter judgment for reasonable attorney's fees in favor of the person or persons instituting said proceedings and against said personal representative, and in the event that the surety or sureties upon the bond of said personal representative be made a party to said proceeding, then jointly against said surety and said personal representative, which judgment shall be enforced in the same manner and to the same extent as judgments in ordinary civil actions.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202066[2010 c 8 § 2066]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.76.070[1965 c 145 § 11.76.070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c28.pdf?cite=1937%20c%2028%20§%202[1937 c 28 § 2]; RRS § 1590-2; ]

== 11.76.080 - Representation of incapacitated person by guardian ad litem or limited guardian—Exception. (Effective until January 1, 2022.)
If there be any alleged incapacitated person as defined in *RCW 11.88.010 interested in the estate who has no legally appointed guardian or limited guardian, the court:

. At any stage of the proceeding in its discretion and for such purpose or purposes as it shall indicate, may appoint; and

. For hearings held under RCW 11.54.010, 11.68.041, 11.68.100, and 11.76.050 or for entry of an order adjudicating testacy or intestacy and heirship when no personal representative is appointed to administer the estate of the decedent, shall appoint some disinterested person as guardian ad litem to represent the allegedly incapacitated person with reference to any petition, proceeding report, or adjudication of testacy or intestacy without the appointment of a personal representative to administer the estate of decedent in which the alleged incapacitated person may have an interest, who, on behalf of the alleged incapacitated person, may contest the same as any other person interested might contest it, and who shall be allowed by the court reasonable compensation for his or her services: PROVIDED, HOWEVER, That where a surviving spouse or surviving domestic partner is the sole beneficiary under the terms of a will, the court may grant a motion by the personal representative to waive the appointment of a guardian ad litem for a person who is the minor child of the surviving spouse or surviving domestic partner and the decedent and who is incapacitated solely for the reason of his or her being under eighteen years of age.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3104-S2.SL.pdf?cite=2008%20c%206%20§%20806[2008 c 6 § 806]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5110-S.SL.pdf?cite=1997%20c%20252%20§%2071[1997 c 252 § 71]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c80.pdf?cite=1977%20ex.s.%20c%2080%20§%2015[1977 ex.s. c 80 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c117.pdf?cite=1974%20ex.s.%20c%20117%20§%2045[1974 ex.s. c 117 § 45]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971c28.pdf?cite=1971%20c%2028%20§%201[1971 c 28 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c70.pdf?cite=1969%20c%2070%20§%204[1969 c 70 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.76.080[1965 c 145 § 11.76.080]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20164[1917 c 156 § 164]; RRS § 1534; prior: Code 1881 § 1558; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20297%20§%20180[1854 p 297 § 180]; ]

== 11.76.095 - Distribution of estates to minors.
When a decree of distribution is made by the court in administration upon a decedent's estate or when distribution is made by a personal representative under a nonintervention will and distribution is ordered under such decree or authorized under such nonintervention will to a person under the age of eighteen years, it shall be required that:

. The money be deposited in a bank or trust company or be invested in an account in an insured financial institution for the benefit of the minor subject to withdrawal only upon the order of the court in the original probate proceeding, or upon said minor's attaining the age of eighteen years and furnishing proof thereof satisfactory to the depositary;

. A general guardian shall be appointed and qualify and the money or property be paid or delivered to such guardian prior to the discharge of the personal representative in the original probate proceeding; or

. A custodian be selected and the money or property be transferred to the custodian subject to chapter 11.114 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5110-S.SL.pdf?cite=1997%20c%20252%20§%2072[1997 c 252 § 72]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1088-S.SL.pdf?cite=1991%20c%20193%20§%2028[1991 c 193 § 28]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c29.pdf?cite=1988%20c%2029%20§%205[1988 c 29 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c117.pdf?cite=1974%20ex.s.%20c%20117%20§%2012[1974 ex.s. c 117 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971c28.pdf?cite=1971%20c%2028%20§%203[1971 c 28 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.76.095[1965 c 145 § 11.76.095]; ]

== 11.76.100 - Receipts for expenses from personal representative.
In rendering his or her accounts or reports the personal representative shall produce receipts or canceled checks for the expenses and charges which he or she shall have paid, which receipts shall be filed and remain in court until the probate has been completed and the personal representative has been discharged; however, he or she may be allowed any item of expenditure, not exceeding twenty dollars, for which no receipt is produced, if such item be supported by his or her own oath, but such allowances without receipts shall not exceed the sum of three hundred dollars in any one estate.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202067[2010 c 8 § 2067]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c363.pdf?cite=1987%20c%20363%20§%202[1987 c 363 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.76.100[1965 c 145 § 11.76.100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20170[1917 c 156 § 170]; RRS § 1540; prior: Code 1881 § 1553; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20297%20§%20176[1854 p 297 § 176]; ]

== 11.76.110 - Order of payment of debts.
After payment of costs of administration the debts of the estate shall be paid in the following order:

. Funeral expenses in such amount as the court shall order.

. Expenses of the last sickness, in such amount as the court shall order.

. Wages due for labor performed within sixty days immediately preceding the death of decedent.

. Debts having preference by the laws of the United States.

. Taxes, or any debts or dues owing to the state.

. Judgments rendered against the deceased in his or her lifetime which are liens upon real estate on which executions might have been issued at the time of his or her death, and debts secured by mortgages in the order of their priority.

. All other demands against the estate.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202068[2010 c 8 § 2068]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.76.110[1965 c 145 § 11.76.110]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20171[1917 c 156 § 171]; RRS § 1541; prior: Code 1881 § 1562; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1860%20p%20213%20§%20264[1860 p 213 § 264]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20298%20§%20184[1854 p 298 § 184]; ]

== 11.76.120 - Limitation on preference to mortgage or judgment.
The preference given in RCW 11.76.110 to a mortgage or judgment shall only extend to the proceeds of the property subject to the lien of such mortgage or judgment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.76.120[1965 c 145 § 11.76.120]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20172[1917 c 156 § 172]; RRS § 1542; prior:  1897 c 22 § 1; Code 1881 § 1653; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20298%20§%20185[1854 p 298 § 185]; ]

== 11.76.130 - Expense of monument.
Personal representatives of the estate of any deceased person are hereby authorized to expend a reasonable amount out of the estate of the decedent to erect a monument or tombstone suitable to mark the grave or crypt of the said decedent, and the expense thereof shall be paid as the funeral expenses are paid.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.76.130[1965 c 145 § 11.76.130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20175[1917 c 156 § 175]; RRS § 1545; prior: Code 1881 § 1555; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1875%20p%20127%20§%201[1875 p 127 § 1]; ]

== 11.76.150 - Payment of claims where estate insufficient.
If the estate shall be insufficient to pay the debts of any class, each creditor shall be paid in proportion to his or her claim, and no other creditor of any lower class shall receive any payment until all those of the preceding class shall have been fully paid.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202069[2010 c 8 § 2069]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.76.150[1965 c 145 § 11.76.150]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20174[1917 c 156 § 174]; RRS § 1544; prior: Code 1881 § 1564; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20298%20§%20186[1854 p 298 § 186]; ]

== 11.76.160 - Liability of personal representative.
Whenever a decree shall have been made by the court for the payment of creditors, the personal representative shall be personally liable to each creditor for his or her claim or the dividend thereon, except when his or her inability to make the payment thereof from the property of the estate shall result without fault upon his or her part. The personal representative shall likewise be liable on his or her bond to each creditor.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202070[2010 c 8 § 2070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.76.160[1965 c 145 § 11.76.160]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20176[1917 c 156 § 176]; RRS § 1546; prior:  1891 c 155 § 35; Code 1881 § 1568; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20299%20§%20190[1854 p 299 § 190]; ]

== 11.76.170 - Action on claim not acted on—Contribution.
If, after the accounts of the personal representative have been settled and the property distributed, it shall appear that there is a creditor or creditors whose claim or claims have been duly filed and not paid or disallowed, the said claim or claims shall not be a lien upon any of the property distributed, but the said creditor or creditors shall have a cause of action against the personal representative and his or her bond, for such an amount as such creditor or creditors would have been entitled to receive had the said claim been duly allowed and paid, and shall also have a cause of action against the distributees and creditors for a contribution from them in proportion to the amount which they have received. If the personal representative or his or her sureties be required to make any payment in this section provided for, he or she or they shall have a right of action against said distributees and creditors to compel them to contribute their just share.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202071[2010 c 8 § 2071]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.76.170[1965 c 145 § 11.76.170]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20177[1917 c 156 § 177]; RRS § 1547; prior: Code 1881 § 1569; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1860%20p%20214%20§%20271[1860 p 214 § 271]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20299%20§%20191[1854 p 299 § 191]; ]

== 11.76.180 - Order maturing claim not due.
If there be any claim not due the court may in its discretion, after hearing upon such notice as may be determined by it, mature such claim and direct that the same be paid in the due course of the administration.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.76.180[1965 c 145 § 11.76.180]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20178[1917 c 156 § 178]; RRS § 1548; prior: Code 1881 § 1567; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20298%20§%20189[1854 p 298 § 189]; ]

== 11.76.190 - Procedure on contingent and disputed claim.
If there be any contingent or disputed claim against the estate, the amount thereof, or such part thereof as the holder would be entitled to, if the claim were established or absolute, shall be paid into the court, where it shall remain to be paid over to the party when he or she shall become entitled thereto; or if he or she fails to establish his or her claim, to be paid over or distributed as the circumstances of the case may require.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202072[2010 c 8 § 2072]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.76.190[1965 c 145 § 11.76.190]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20179[1917 c 156 § 179]; RRS § 1549; prior: Code 1881 § 1567; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20298%20§%20189[1854 p 298 § 189]; ]

== 11.76.200 - Agent for absentee distributee.
When any estate has been or is about to be distributed by decree of the court as provided in this chapter, to any person who has not been located, the court shall appoint an agent for the purpose of representing the interests of such person and of taking possession and charge of said estate for the benefit of such absentee person: PROVIDED, That no public official may be appointed as agent under this section.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.76.200[1965 c 145 § 11.76.200]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955ex1c7.pdf?cite=1955%20ex.s.%20c%207%20§%201[1955 ex.s. c 7 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20165[1917 c 156 § 165]; RRS § 1535; ]

== 11.76.210 - Agent's bond.
Such agent shall make, subscribe and file an oath for the faithful performance of his or her duties, and shall give a bond to the state, to be approved by the court, conditioned faithfully to manage and account for such estate, before he or she shall be authorized to receive any property of said estate.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202073[2010 c 8 § 2073]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.76.210[1965 c 145 § 11.76.210]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955ex1c7.pdf?cite=1955%20ex.s.%20c%207%20§%202[1955 ex.s. c 7 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20166[1917 c 156 § 166]; RRS § 1536; ]

== 11.76.220 - Sale of unclaimed estate—Remittance of proceeds to department of revenue.
If the estate remains in the hands of the agent unclaimed for three years, any property not in the form of cash shall be sold under order of the court, and all funds, after deducting a reasonable sum for expenses and services of the agent, to be fixed by the court, shall be paid into the county treasury. The county treasurer shall issue triplicate receipts therefor, one of which shall be filed with the county auditor, one with the court, and one with the department of revenue. If the funds remain in the county treasury unclaimed for a period of four years and ninety days, the county treasurer shall forthwith remit them to the department of revenue for deposit in the state treasury in the fund in which escheats and forfeitures are by law required to be deposited.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c278.pdf?cite=1975%201st%20ex.s.%20c%20278%20§%2010[1975 1st ex.s. c 278 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.76.220[1965 c 145 § 11.76.220]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955ex1c7.pdf?cite=1955%20ex.s.%20c%207%20§%204[1955 ex.s. c 7 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20167[1917 c 156 § 167]; RRS § 1537; ]

== 11.76.230 - Liability of agent.
The agent shall be liable on his or her bond for the care and preservation of the estate while in his or her hands, and for the payment of the funds to the county treasury, and may be sued thereon by any person interested including the state.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202074[2010 c 8 § 2074]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.76.230[1965 c 145 § 11.76.230]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955ex1c7.pdf?cite=1955%20ex.s.%20c%207%20§%205[1955 ex.s. c 7 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20168[1917 c 156 § 168]; RRS § 1538; ]

== 11.76.240 - Claimant to proceeds of sale.
During the time the estate is held by the agent, or within four years after it is delivered to the county treasury, claim may be made thereto only by the absentee person or his or her legal representative, excepting that if it clearly appears that such person died prior to the decedent in whose estate distribution was made to him or her, but leaving lineal descendants surviving, such lineal descendants may claim. If any claim to the estate is made during the period specified above, the claimant shall forthwith notify the department of revenue in writing of such claim. The court, being first satisfied as to the right of such person to the estate, and after the filing of a clearance from the department of revenue, shall order the agent, or the county treasurer, as the case may be, to forthwith deliver the estate, or the proceeds thereof, if sold, to such person.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202075[2010 c 8 § 2075]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c278.pdf?cite=1975%201st%20ex.s.%20c%20278%20§%2011[1975 1st ex.s. c 278 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.76.240[1965 c 145 § 11.76.240]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955ex1c7.pdf?cite=1955%20ex.s.%20c%207%20§%206[1955 ex.s. c 7 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20169[1917 c 156 § 169]; RRS § 1539; ]

== 11.76.243 - Heirs may institute probate proceedings if no claimant appears.
If no person appears to claim the estate within four years after it is delivered to the county treasury, as provided by RCW 11.76.240, any heirs of the absentee person may institute probate proceedings on the estate of such absentee within ninety days thereafter. The fact that no claim has been made to the estate by the absentee person during the specified time shall be deemed prima facie proof of the death of such person for the purpose of issuing letters of administration in his or her estate. In the event letters of administration are issued within the period provided above, the county treasurer shall make payment of the funds held by him or her to the administrator upon being furnished a certified copy of the letters of administration.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202076[2010 c 8 § 2076]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.76.243[1965 c 145 § 11.76.243]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955ex1c7.pdf?cite=1955%20ex.s.%20c%207%20§%207[1955 ex.s. c 7 § 7]; ]

== 11.76.245 - Procedure when claim made after time limitation.
After any time limitation prescribed in RCW 11.76.220, 11.76.240 or 11.76.243, the absentee claimant may, at any time, if the assets of the estate have not been claimed under the provisions of RCW 11.76.240 and 11.76.243, notify the department of revenue of his or her claim to the estate, and file in the court which had jurisdiction of the original probate a petition claiming the assets of the estate. The department of revenue may appear in answer to such petition. Upon proof being made to the probate court that the claimant is entitled to the estate assets, the court shall render its judgment to that effect and the assets shall be paid to the claimant without interest, upon appropriation made by the legislature.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202077[2010 c 8 § 2077]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c278.pdf?cite=1975%201st%20ex.s.%20c%20278%20§%2012[1975 1st ex.s. c 278 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.76.245[1965 c 145 § 11.76.245]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955ex1c7.pdf?cite=1955%20ex.s.%20c%207%20§%208[1955 ex.s. c 7 § 8]; ]

== 11.76.247 - When court retains jurisdiction after entry of decree of distribution.
After the entry of the decree of distribution in the probate proceedings the court shall retain jurisdiction for the purpose of carrying out the provisions of RCW 11.76.200, 11.76.210, 11.76.220, 11.76.230, 11.76.240, 11.76.243 and 11.76.245.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.76.247[1965 c 145 § 11.76.247]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955ex1c7.pdf?cite=1955%20ex.s.%20c%207%20§%203[1955 ex.s. c 7 § 3]; ]

== 11.76.250 - Letters after final settlement.
A final settlement of the estate shall not prevent a subsequent issuance of letters of administration, should other property of the estate be discovered, or if it should become necessary and proper from any cause that letters should be again issued.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.76.250[1965 c 145 § 11.76.250]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20180[1917 c 156 § 180]; RRS § 1550; prior: Code 1881 § 1603; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20304%20§%20224[1854 p 304 § 224]; ]

