= 11.08 - Escheats.
:toc:

== 11.08.101 - Property of deceased inmates of state institutions—Disposition after two years.
Where, upon the expiration of two years after the death of any inmate of any state institution, there remains in the custody of the superintendent of such institution, money or property belonging to said deceased inmate, the superintendent shall forward such money to the state treasurer for deposit in the general fund of the state, and shall report such transfer and any remaining property to the department of corrections, which department shall cause the sale of such property and proceeds thereof shall be forwarded to the state treasurer for deposit in the general fund.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c136.pdf?cite=1981%20c%20136%20§%2058[1981 c 136 § 58]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%2010[1979 c 141 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.08.101[1965 c 145 § 11.08.101]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c138.pdf?cite=1951%20c%20138%20§%201[1951 c 138 § 1]; prior:  1923 c 113 § 1; RRS § 1363-1; ]

== 11.08.111 - Property of deceased inmates of state institutions—Disposition within two years.
Prior to the expiration of the two-year period provided for in RCW 11.08.101, the superintendent may transfer such money or property in his or her possession, upon request and satisfactory proof submitted to him or her, to the following designated persons:

. To the personal representative of the estate of such deceased inmate; or

. To the successor or successors defined in RCW 11.62.005, where such money and property does not exceed the amount specified in RCW 6.13.030, and the successor or successors shall have furnished proof of death and an affidavit made by said successor or successors meeting the requirements of RCW 11.62.010; or

. In the case of money, to the person who may have deposited such money with the superintendent for the use of the decedent, where the sum involved does not exceed one thousand dollars; or

. To the department of social and health services, when there are moneys due and owing from such deceased person's estate for the cost of his or her care and maintenance at a state institution: PROVIDED, That transfer of such money or property may be made to the person first qualifying under this section and such transfer shall exonerate the superintendent from further responsibility relative to such money or property: AND PROVIDED FURTHER, That upon satisfactory showing the funeral expenses of such decedent are unpaid, the superintendent may pay up to one thousand dollars from said deceased inmate's funds on said obligation.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202006[2010 c 8 § 2006]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c225.pdf?cite=1990%20c%20225%20§%202[1990 c 225 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c76.pdf?cite=1973%201st%20ex.s.%20c%2076%20§%201[1973 1st ex.s. c 76 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.08.111[1965 c 145 § 11.08.111]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c240.pdf?cite=1959%20c%20240%20§%201[1959 c 240 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c138.pdf?cite=1951%20c%20138%20§%202[1951 c 138 § 2]; ]

== 11.08.120 - Property of deceased inmates of state institutions—Sale—Disposition of proceeds.
The property, other than money, of such deceased inmate remaining in the custody of a superintendent of a state institution after the expiration of the above two-year period may be forwarded to the department of corrections at its request and may be appraised and sold at public auction to the highest bidder in the manner and form as provided for public sales of personal property, and all moneys realized upon such sale, after deducting the expenses thereof, shall be paid into the general fund of the state treasury.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c136.pdf?cite=1981%20c%20136%20§%2059[1981 c 136 § 59]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%2011[1979 c 141 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.08.120[1965 c 145 § 11.08.120]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c138.pdf?cite=1951%20c%20138%20§%203[1951 c 138 § 3]; prior:  1923 c 113 § 2; RRS § 1363-2; ]

== 11.08.140 - Escheat for want of heirs.
Whenever any person dies, whether a resident of this state or not, leaving property subject to the jurisdiction of this state and without being survived by any person entitled to the same under the laws of this state, such property shall be designated escheat property and shall be subject to the provisions of RCW 11.08.140 through 11.08.280.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.08.140[1965 c 145 § 11.08.140]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c254.pdf?cite=1955%20c%20254%20§%202[1955 c 254 § 2]; ]

== 11.08.150 - Title to property vests in state at death of owner.
Title to escheat property, which shall include any intangible personalty, shall vest in the state at the death of the owner thereof.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.08.150[1965 c 145 § 11.08.150]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c254.pdf?cite=1955%20c%20254%20§%203[1955 c 254 § 3]; ]

== 11.08.160 - Department of revenue—Jurisdiction—Duties.
The department of revenue of this state shall have supervision of and jurisdiction over escheat property and may institute and prosecute any proceedings, including any proceeding under chapter 11.62 RCW, deemed necessary or proper in the handling of such property, and it shall be the duty of the department of revenue to protect and conserve escheat property for the benefit of the permanent common school fund of the state until such property or the proceeds thereof have been forwarded to the state treasurer or the department of natural resources as hereinafter provided.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c128.pdf?cite=1988%20c%20128%20§%201[1988 c 128 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c64.pdf?cite=1988%20c%2064%20§%2023[1988 c 64 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c278.pdf?cite=1975%201st%20ex.s.%20c%20278%20§%201[1975 1st ex.s. c 278 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.08.160[1965 c 145 § 11.08.160]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c254.pdf?cite=1955%20c%20254%20§%204[1955 c 254 § 4]; ]

== 11.08.170 - Probate of escheat property—Notice to department of revenue.
Escheat property may be probated under the provisions of the probate laws of this state. Whenever such probate proceedings are instituted, whether by special administration or otherwise, the petitioner shall promptly notify the department of revenue in writing thereof on forms furnished by the department of revenue to the county clerks. Thereafter, the department of revenue shall be served with written notice at least twenty days prior to any hearing on proceedings involving the valuation or sale of property, on any petition for the allowance of fees, and on all interim reports, final accounts or petitions for the determination of heirship. Like notice shall be given of the presentation of any claims to the court for allowance. Failure to furnish such notice shall be deemed jurisdictional and any order of the court entered without such notice shall be void. The department of revenue may waive the provisions of this section in its discretion. The department shall be deemed to have waived its right to administer in such probate proceedings under RCW 11.28.120(5) unless application for appointment of the director or the director's designee is made within forty days immediately following receipt of notice of institution of proceedings.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2270-S.SL.pdf?cite=1994%20c%20221%20§%203[1994 c 221 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c225.pdf?cite=1990%20c%20225%20§%201[1990 c 225 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c278.pdf?cite=1975%201st%20ex.s.%20c%20278%20§%202[1975 1st ex.s. c 278 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.08.170[1965 c 145 § 11.08.170]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c254.pdf?cite=1955%20c%20254%20§%205[1955 c 254 § 5]; ]

== 11.08.180 - Department of revenue to be furnished copies of documents and pleadings.
The department of revenue may demand copies of any papers, documents, or pleadings involving the escheat property or the probate thereof deemed by it to be necessary for the enforcement of RCW 11.08.140 through 11.08.280 and it shall be the duty of the administrator or his or her attorney to furnish such copies to the department.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202007[2010 c 8 § 2007]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c278.pdf?cite=1975%201st%20ex.s.%20c%20278%20§%203[1975 1st ex.s. c 278 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.08.180[1965 c 145 § 11.08.180]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c254.pdf?cite=1955%20c%20254%20§%206[1955 c 254 § 6]; ]

== 11.08.185 - Escheat property—Records of department of revenue—Public record information.
All records of the department of revenue relating to escheated property or property about to escheat shall be a public record and shall be made available by the department of revenue for public inspection. Without limitation, the records to be made public shall include all available information regarding possible heirs, descriptions and amounts of property escheated or about to escheat, and any information which might serve to identify the proper heirs.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c25.pdf?cite=1973%20c%2025%20§%201[1973 c 25 § 1]; ]

== 11.08.200 - Liability for use of escheated property.
If any person shall take possession of escheat property without proper authorization to do so, and shall have the use thereof for a period exceeding sixty days, he or she shall be liable to the state for the reasonable value of such use, payment of which may be enforced by the department of revenue or by the administrator of the estate.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202008[2010 c 8 § 2008]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c278.pdf?cite=1975%201st%20ex.s.%20c%20278%20§%204[1975 1st ex.s. c 278 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.08.200[1965 c 145 § 11.08.200]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c254.pdf?cite=1955%20c%20254%20§%208[1955 c 254 § 8]; ]

== 11.08.205 - Lease, sublease, or rental of escheated real property—Authorized—Expenses—Distribution of proceeds.
. The department of natural resources shall have the authority to lease real property from the administrator of an estate being probated under the escheat provisions, RCW 11.08.140 to 11.08.280.

. The department of natural resources shall have the authority to sublease or rent the real property, it has leased under subsection (1) of this section, during the period that the real property is under the authority of the court appointed administrator.

. Any moneys gained by the department of natural resources from leases or rentals shall be credited to an escheat reserve account bearing the name of the estate.

. The department of natural resources shall have the authority to expend moneys to preserve and maintain the real property during the probate period.

. Any expenses by the department of natural resources in preserving or maintaining the real property may be paid as follows:

.. First, the expenses shall be charged to the escheat reserve account bearing the name of the estate; and

.. Second, if the expenses exceed the escheat reserve account, then the expenses shall be paid as follows:

... If the land is distributed to the state by the administrator, the expenses shall be paid out of the sale price of the land as later sold by the department of natural resources, or shall be paid out of the general fund if the land is held for use by the state; or

... If the land is distributed to the heirs by the administrator, the expenses shall be borne by the estate.

. Upon the final distribution of the real property, the escheat reserve account shall be closed out as follows:

.. If the real property is distributed to the state, the balance of the account shall be paid into the permanent common school fund of the state; or

.. If the real property is distributed to the heirs, the balance of the account shall be paid to the estate.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c249.pdf?cite=1969%20ex.s.%20c%20249%20§%201[1969 ex.s. c 249 § 1]; ]

== 11.08.210 - Allowance of claims, expenses, partial fees—Sale of property—Decree of distribution.
If at the expiration of four months from the date of the first publication of notice to creditors no heirs have appeared and established their claim to the estate, the court may enter an interim order allowing claims, expenses, and partial fees. If at the expiration of ten months from the date of issuance of letters testamentary or of administration no heirs have appeared and established their claim to the estate, all personal property not in the form of cash shall be sold under order of the court. Personal property found by the court to be worthless shall be ordered abandoned. Real property shall not be sold for the satisfaction of liens thereon, or for the payment of the debts of decedent or expenses of administration until the proceeds of the personal property are first exhausted. The court shall then enter a decree allowing any additional fees and charges deemed proper and distributing the balance of the cash on hand, together with any real property, to the state. Remittance of cash on hand shall be made to the department of revenue which shall make proper records thereof and forthwith forward such funds to the state treasurer for deposit in the permanent common school fund of the state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c209.pdf?cite=1979%20ex.s.%20c%20209%20§%2019[1979 ex.s. c 209 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c278.pdf?cite=1975%201st%20ex.s.%20c%20278%20§%205[1975 1st ex.s. c 278 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.08.210[1965 c 145 § 11.08.210]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c254.pdf?cite=1955%20c%20254%20§%209[1955 c 254 § 9]; ]

== 11.08.220 - Certified copies of decree—Department of natural resources duties.
The department of revenue shall be furnished two certified copies of the decree of the court distributing any real property to the state, one of which shall be forwarded to the department of natural resources which shall thereupon assume supervision of and jurisdiction over such real property and thereafter handle it the same as state common school lands. The administrator shall also file a certified copy of the decree with the auditor of any county in which the escheated real property is situated.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c128.pdf?cite=1988%20c%20128%20§%202[1988 c 128 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c278.pdf?cite=1975%201st%20ex.s.%20c%20278%20§%206[1975 1st ex.s. c 278 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.08.220[1965 c 145 § 11.08.220]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c125.pdf?cite=1957%20c%20125%20§%201[1957 c 125 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c254.pdf?cite=1955%20c%20254%20§%2010[1955 c 254 § 10]; ]

== 11.08.230 - Appearance and claim of heirs—Notices to department of revenue.
Upon the appearance of heirs and the establishment of their claim to the satisfaction of the court prior to entry of the decree of distribution to the estate, the provisions of RCW 11.08.140 through 11.08.280 shall not further apply, except for purposes of appeal: PROVIDED, That the department of revenue shall be promptly given written notice of such appearance by the claimants and furnished copies of all papers or documents on which such claim of heirship is based. Any documents in a foreign language shall be accompanied by translations made by a properly qualified translator, certified by him or her to be true and correct translations of the original documents. The administrator or his or her attorney shall also furnish the department of revenue with any other available information bearing on the validity of the claim.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202009[2010 c 8 § 2009]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c278.pdf?cite=1975%201st%20ex.s.%20c%20278%20§%207[1975 1st ex.s. c 278 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.08.230[1965 c 145 § 11.08.230]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c254.pdf?cite=1955%20c%20254%20§%2011[1955 c 254 § 11]; ]

== 11.08.240 - Limitation on filing claim.
Any claimant to escheated funds or real property shall have seven years from the date of issuance of letters testamentary or of administration within which to file his or her claim. Such claim shall be filed with the court having original jurisdiction of the estate, and a copy thereof served upon the department of revenue, together with twenty days notice of the hearing thereon.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202010[2010 c 8 § 2010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c278.pdf?cite=1975%201st%20ex.s.%20c%20278%20§%208[1975 1st ex.s. c 278 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.08.240[1965 c 145 § 11.08.240]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c254.pdf?cite=1955%20c%20254%20§%2012[1955 c 254 § 12]; ]

== 11.08.250 - Order of court on establishment of claim—Parklands—Appraisal.
Upon establishment of the claim to the satisfaction of the court, it shall order payment to the claimant of any escheated funds and delivery of any escheated land, or the proceeds thereof, if sold. If, however, the escheated property shall have been transferred to the state parks and recreation commission or local jurisdiction for park purposes, the court shall order payment to the claimant for the fair market value of the property at the time of transfer, excluding the value of physical improvements to the property while managed by a state agency or local jurisdiction. The value shall be established by independent appraisal obtained by the department of revenue.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5255-S.SL.pdf?cite=1993%20c%2049%20§%202[1993 c 49 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.08.250[1965 c 145 § 11.08.250]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c254.pdf?cite=1955%20c%20254%20§%2013[1955 c 254 § 13]; ]

== 11.08.260 - Payment of escheated funds to claimant.
In the event the order of the court requires the payment of escheated funds or the proceeds of the sale of escheated real property or the appraised value of escheated property transferred for park purposes, a certified copy of such order shall be served upon the department of revenue which shall thereupon take any steps necessary to effect payment to the claimant out of the general fund of the state.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5255-S.SL.pdf?cite=1993%20c%2049%20§%203[1993 c 49 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c278.pdf?cite=1975%201st%20ex.s.%20c%20278%20§%209[1975 1st ex.s. c 278 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.08.260[1965 c 145 § 11.08.260]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c254.pdf?cite=1955%20c%20254%20§%2014[1955 c 254 § 14]; ]

== 11.08.270 - Conveyance of escheated property to claimant.
In the event the order of the court requires the delivery of real property to the claimant, a certified copy of such order shall be served upon the department of natural resources which shall thereupon make proper certification to the office of the governor for issuance of a quitclaim deed for the property to the claimant.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c128.pdf?cite=1988%20c%20128%20§%203[1988 c 128 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.08.270[1965 c 145 § 11.08.270]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c254.pdf?cite=1955%20c%20254%20§%2015[1955 c 254 § 15]; ]

== 11.08.280 - Limitation when claimant is minor or incompetent not under guardianship.
The claims of any persons to escheated funds or real property which are not filed within seven years as specified above are forever barred, excepting as to those persons who are minors or who are legally incompetent and not under guardianship, in which event the claim may be filed within seven years after their disability is removed.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.08.280[1965 c 145 § 11.08.280]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c254.pdf?cite=1955%20c%20254%20§%2016[1955 c 254 § 16]; ]

== 11.08.290 - Deposit of cash received by personal representative of escheat estate.
All cash received by the personal representative of an escheat estate shall be immediately deposited at interest for the benefit of the estate in a federally insured time or savings deposit or share account, except that the personal representative may maintain an amount not to exceed two hundred fifty dollars in a checking account. This arrangement may be changed by appropriate court order.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c209.pdf?cite=1979%20ex.s.%20c%20209%20§%2018[1979 ex.s. c 209 § 18]; ]

== 11.08.300 - Transfer of property to department of revenue.
Escheat property may be transferred to the department of revenue under the provisions of RCW 11.62.005 through 11.62.020. The department of revenue shall furnish proof of death and an affidavit made by the department which meets the requirements of RCW 11.62.010 to any person who is indebted to or has possession of any personal property belonging to the decedent or to the decedent and his or her surviving spouse or surviving domestic partner as a community, which debt or personal property is an asset which is subject to probate. Upon receipt of such proof of death and affidavit, the person shall pay the indebtedness or deliver the personal property, or as much of either as is claimed, to the department of revenue pursuant to RCW 11.62.010.

The department of revenue shall file a copy of its affidavit made pursuant to chapter 11.62 RCW with the clerk of the court where any probate administration of the decedent has been commenced, or, if no probate administration has been commenced, then with the clerk of the court of any county provided by law as a place for probate administration of the estate of such person. The affidavit shall be indexed under the name of the decedent in the probate index upon payment of a fee of two dollars. Any claimant to escheated funds shall have seven years from the filing of the affidavit by the department of revenue within which to file the claim. The claim shall be filed with the clerk of the court where the affidavit of the department of revenue was filed, and a copy served upon the department of revenue, together with twenty days notice of a hearing to be held thereon, and the provisions of RCW 11.08.250 through 11.08.280 shall apply.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3104-S2.SL.pdf?cite=2008%20c%206%20§%20907[2008 c 6 § 907]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c225.pdf?cite=1990%20c%20225%20§%203[1990 c 225 § 3]; ]

