= 11.40 - Claims against estate.
:toc:

== 11.40.010 - Claims—Presentation—Other notice not affected.
A person having a claim against the decedent may not maintain an action on the claim unless a personal representative has been appointed and the claimant has presented the claim as set forth in this chapter. However, this chapter does not affect the notice under RCW 82.32.240 or the ability to maintain an action against a notice agent under chapter 11.42 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5110-S.SL.pdf?cite=1997%20c%20252%20§%207[1997 c 252 § 7]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1908-S2.SL.pdf?cite=1995%201st%20sp.s.%20c%2018%20§%2058[1995 1st sp.s. c 18 § 58]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2270-S.SL.pdf?cite=1994%20c%20221%20§%2025[1994 c 221 § 25]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1060.SL.pdf?cite=1991%20c%205%20§%201[1991 c 5 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c333.pdf?cite=1989%20c%20333%20§%201[1989 c 333 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c117.pdf?cite=1974%20ex.s.%20c%20117%20§%2033[1974 ex.s. c 117 § 33]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c168.pdf?cite=1967%20c%20168%20§%207[1967 c 168 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.40.010[1965 c 145 § 11.40.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c142.pdf?cite=1923%20c%20142%20§%203[1923 c 142 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20107[1917 c 156 § 107]; RRS § 1477; prior: Code 1881 § 1465; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1860%20p%20195%20§%20157[1860 p 195 § 157]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20280%20§%2078[1854 p 280 § 78]; ]

== 11.40.020 - Notice to creditors—Manner—Filings—Publication.
. Subject to subsection (2) of this section, a personal representative may give notice to the creditors of the decedent, in substantially the form set forth in RCW 11.40.030, announcing the personal representative's appointment and requiring that persons having claims against the decedent present their claims within the time specified in RCW 11.40.051 or be forever barred as to claims against the decedent's probate and nonprobate assets. If notice is given:

.. The personal representative shall file the notice with the court;

.. The personal representative shall cause the notice to be published once each week for three successive weeks in a legal newspaper in the county in which the estate is being administered;

.. The personal representative may, at any time during the probate proceeding, give actual notice to creditors who become known to the personal representative by serving the notice on the creditor or mailing the notice to the creditor at the creditor's last known address, by regular first-class mail, postage prepaid; and

.. The personal representative shall also mail a copy of the notice, including the decedent's social security number, to the state of Washington department of social and health services office of financial recovery.

The personal representative shall file with the court proof by affidavit of the giving and publication of the notice.

. If the decedent was a resident of the state of Washington at the time of death and probate proceedings are commenced in a county other than the county of the decedent's residence, then instead of the requirements under subsection (1)(a) and (b) of this section, the personal representative shall cause the notice to creditors in substantially the form set forth in RCW 11.40.030 to be published once each week for three successive weeks in a legal newspaper in the county of the decedent's residence and shall file the notice with the superior court of the county in which the probate proceedings were commenced.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1125.SL.pdf?cite=2005%20c%2097%20§%204[2005 c 97 § 4]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20601[1999 c 42 § 601]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5110-S.SL.pdf?cite=1997%20c%20252%20§%208[1997 c 252 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c117.pdf?cite=1974%20ex.s.%20c%20117%20§%2034[1974 ex.s. c 117 § 34]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.40.020[1965 c 145 § 11.40.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20108[1917 c 156 § 108]; RRS § 1478; prior:  1883 p 29 § 1; Code 1881 § 1468; ]

== 11.40.030 - Notice to creditors—Form.
Notice under RCW 11.40.020 must contain the following elements in substantially the following form:

CAPTION)No.OF CASE)PROBATE NOTICE TO )CREDITORS. . . .)RCW 11.40.030

CAPTION

)

No.

OF CASE

)

PROBATE NOTICE TO

 

)

CREDITORS

. . . .

)

RCW 11.40.030

The personal representative named below has been appointed as personal representative of this estate. Any person having a claim against the decedent must, before the time the claim would be barred by any otherwise applicable statute of limitations, present the claim in the manner as provided in RCW 11.40.070 by serving on or mailing to the personal representative or the personal representative's attorney at the address stated below a copy of the claim and filing the original of the claim with the court in which the probate proceedings were commenced. The claim must be presented within the later of: (1) Thirty days after the personal representative served or mailed the notice to the creditor as provided under RCW 11.40.020(1)(c); or (2) four months after the date of first publication of the notice. If the claim is not presented within this time frame, the claim is forever barred, except as otherwise provided in RCW 11.40.051 and 11.40.060. This bar is effective as to claims against both the decedent's probate and nonprobate assets.

Date of First

Publication:

Personal Representative:

Attorney for the Personal Representative:

Address for Mailing or Service:

Court of probate proceedings and cause number:

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1125.SL.pdf?cite=2005%20c%2097%20§%205[2005 c 97 § 5]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5110-S.SL.pdf?cite=1997%20c%20252%20§%209[1997 c 252 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c333.pdf?cite=1989%20c%20333%20§%207[1989 c 333 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c234.pdf?cite=1977%20ex.s.%20c%20234%20§%208[1977 ex.s. c 234 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c117.pdf?cite=1974%20ex.s.%20c%20117%20§%2035[1974 ex.s. c 117 § 35]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.40.030[1965 c 145 § 11.40.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c43.pdf?cite=1963%20c%2043%20§%201[1963 c 43 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20109[1917 c 156 § 109]; RRS § 1479; prior: Code 1881 § 1469; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20285%20§%20156[1873 p 285 § 156]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20281%20§%2082[1854 p 281 § 82]; ]

== 11.40.040 - "Reasonably ascertainable" creditor—Definition—Reasonable diligence—Presumptions—Petition for order.
. For purposes of RCW 11.40.051, a "reasonably ascertainable" creditor of the decedent is one that the personal representative would discover upon exercise of reasonable diligence. The personal representative is deemed to have exercised reasonable diligence upon conducting a reasonable review of the decedent's correspondence, including correspondence received after the date of death, and financial records, including personal financial statements, loan documents, checkbooks, bank statements, and income tax returns, that are in the possession of or reasonably available to the personal representative.

. If the personal representative conducts the review, the personal representative is presumed to have exercised reasonable diligence to ascertain creditors of the decedent and any creditor not ascertained in the review is presumed not reasonably ascertainable within the meaning of RCW 11.40.051. These presumptions may be rebutted only by clear, cogent, and convincing evidence.

. The personal representative may evidence the review and resulting presumption by filing with the court an affidavit regarding the facts referred to in this section. The personal representative may petition the court for an order declaring that the personal representative has made a review and that any creditors not known to the personal representative are not reasonably ascertainable. The petition must be filed under RCW 11.96A.080 and the notice specified under RCW 11.96A.110 must also be given by publication.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20607[1999 c 42 § 607]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5110-S.SL.pdf?cite=1997%20c%20252%20§%2010[1997 c 252 § 10]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2270-S.SL.pdf?cite=1994%20c%20221%20§%2028[1994 c 221 § 28]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c117.pdf?cite=1974%20ex.s.%20c%20117%20§%2036[1974 ex.s. c 117 § 36]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.40.040[1965 c 145 § 11.40.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20110[1917 c 156 § 110]; RRS § 1480; prior: Code 1881 § 1470; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20281%20§%2083[1854 p 281 § 83]; ]

== 11.40.051 - Claims against decedent—Time limits.
. Whether or not notice is provided under RCW 11.40.020, a person having a claim against the decedent is forever barred from making a claim or commencing an action against the decedent, if the claim or action is not already barred by an otherwise applicable statute of limitations, unless the creditor presents the claim in the manner provided in RCW 11.40.070 within the following time limitations:

.. If the personal representative provided notice under RCW 11.40.020 and the creditor was given actual notice as provided in RCW 11.40.020(1)(c), the creditor must present the claim within the later of: (i) Thirty days after the personal representative's service or mailing of notice to the creditor; and (ii) four months after the date of first publication of the notice;

.. If the personal representative provided notice under RCW 11.40.020 and the creditor was not given actual notice as provided in RCW 11.40.020(1)(c):

... If the creditor was not reasonably ascertainable, as defined in RCW 11.40.040, the creditor must present the claim within four months after the date of first publication of notice;

... If the creditor was reasonably ascertainable, as defined in RCW 11.40.040, the creditor must present the claim within twenty-four months after the decedent's date of death; and

.. If notice was not provided under this chapter or chapter 11.42 RCW, the creditor must present the claim within twenty-four months after the decedent's date of death.

. An otherwise applicable statute of limitations applies without regard to the tolling provisions of RCW 4.16.190.

. This bar is effective as to claims against both the decedent's probate and nonprobate assets.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1125.SL.pdf?cite=2005%20c%2097%20§%206[2005 c 97 § 6]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5110-S.SL.pdf?cite=1997%20c%20252%20§%2011[1997 c 252 § 11]; ]

== 11.40.060 - Claims involving liability or casualty insurance—Limitations—Exceptions to time limits.
The time limitations for presenting claims under this chapter do not accrue to the benefit of any liability or casualty insurer. Claims against the decedent or the decedent's marital community that can be fully satisfied by applicable insurance coverage or proceeds need not be presented within the time limitation of RCW 11.40.051, but the amount of recovery cannot exceed the amount of the insurance. The claims may at any time be presented as provided in RCW 11.40.070, subject to the otherwise relevant statutes of limitations, and do not constitute a cloud, lien, or encumbrance upon the title to the decedent's probate or nonprobate assets nor delay or prevent the conclusion of probate proceedings or the transfer or distribution of assets of the estate. This section does not serve to extend any otherwise relevant statutes of limitations.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5110-S.SL.pdf?cite=1997%20c%20252%20§%2012[1997 c 252 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c117.pdf?cite=1974%20ex.s.%20c%20117%20§%2037[1974 ex.s. c 117 § 37]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.40.060[1965 c 145 § 11.40.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20112[1917 c 156 § 112]; RRS § 1482; prior: Code 1881 § 1472; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20285%20§%20159[1873 p 285 § 159]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20166%20§%20665[1869 p 166 § 665]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20281%20§%2084[1854 p 281 § 84]; ]

== 11.40.070 - Claims—Form—Manner of presentation—Waiver of defects.
. The claimant, the claimant's attorney, or the claimant's agent shall sign the claim and include in the claim the following information:

.. The name and address of the claimant;

.. The name, address, if different from that of the claimant, and nature of authority of an agent signing the claim on behalf of the claimant;

.. A statement of the facts or circumstances constituting the basis of the claim;

.. The amount of the claim; and

.. If the claim is secured, unliquidated, contingent, or not yet due, the nature of the security, the nature of the uncertainty, or the date when it will become due.

Failure to describe correctly the information in (c), (d), or (e) of this subsection, if the failure is not substantially misleading, does not invalidate the claim.

. A claim does not need to be supported by affidavit.

. A claim must be presented within the time limits set forth in RCW 11.40.051 by: (a) Serving on or mailing to, by regular first-class mail, the personal representative or the personal representative's attorney a copy of the signed claim; and (b) filing the original of the signed claim with the court in which probate proceedings were commenced. A claim is deemed presented upon the later of the date of postmark or service on the personal representative, or the personal representative's attorney, and filing with the court.

. Notwithstanding any other provision of this chapter, if a claimant makes a written demand for payment within the time limits set forth in RCW 11.40.051, the personal representative may waive formal defects and elect to treat the demand as a claim properly filed under this chapter if: (a) The claim was due; (b) the amount paid is the amount of indebtedness over and above all payments and offsets; (c) the estate is solvent; and (d) the payment is made in good faith. Nothing in this chapter limits application of the doctrines of waiver, estoppel, or detrimental claims or any other equitable principle.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1125.SL.pdf?cite=2005%20c%2097%20§%207[2005 c 97 § 7]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5110-S.SL.pdf?cite=1997%20c%20252%20§%2013[1997 c 252 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.40.070[1965 c 145 § 11.40.070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20113[1917 c 156 § 113]; RRS § 1483; prior: Code 1881 § 1473; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20281%20§%2085[1854 p 281 § 85]; ]

== 11.40.080 - Claims—Duty to allow or reject—Notice of petition to allow—Attorneys' fees.
. The personal representative shall allow or reject all claims presented in the manner provided in RCW 11.40.070. The personal representative may allow or reject a claim in whole or in part.

. If the personal representative has not allowed or rejected a claim within the later of four months from the date of first publication of the notice to creditors or thirty days from presentation of the claim, the claimant may serve written notice on the personal representative that the claimant will petition the court to have the claim allowed. If the personal representative fails to notify the claimant of the allowance or rejection of the claim within twenty days after the personal representative's receipt of the claimant's notice, the claimant may petition the court for a hearing to determine whether the claim should be allowed or rejected, in whole or in part. If the court substantially allows the claim, the court may allow the petitioner reasonable attorneys' fees chargeable against the estate.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5110-S.SL.pdf?cite=1997%20c%20252%20§%2014[1997 c 252 § 14]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2270-S.SL.pdf?cite=1994%20c%20221%20§%2029[1994 c 221 § 29]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c64.pdf?cite=1988%20c%2064%20§%2022[1988 c 64 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.40.080[1965 c 145 § 11.40.080]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20114[1917 c 156 § 114]; RRS § 1484; prior: Code 1881 § 1474; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20281%20§%2086[1854 p 281 § 86]; ]

== 11.40.090 - Allowance of claims—Notice—Automatic allowance—Petition for extension—Ranking of claims—Barred claims.
. If the personal representative allows a claim, the personal representative shall notify the claimant of the allowance by personal service or regular first-class mail to the address stated on the claim.

. A claim that on its face does not exceed one thousand dollars presented in the manner provided in RCW 11.40.070 must be deemed allowed and may not thereafter be rejected unless the personal representative has notified the claimant of rejection of the claim within the later of six months from the date of first publication of the notice to creditors and two months from the personal representative's receipt of the claim. The personal representative may petition for an order extending the period for automatic allowance of the claims.

. Allowed claims must be ranked among the acknowledged debts of the estate to be paid expeditiously in the course of administration.

. A claim may not be allowed if it is barred by a statute of limitations.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5110-S.SL.pdf?cite=1997%20c%20252%20§%2015[1997 c 252 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.40.090[1965 c 145 § 11.40.090]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20115[1917 c 156 § 115]; RRS § 1485; prior: Code 1881 § 1475; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20281%20§%2087[1854 p 281 § 87]; ]

== 11.40.100 - Rejection of claim—Time limits—Notice—Compromise of claim.
. If the personal representative rejects a claim, in whole or in part, the claimant must bring suit against the personal representative within thirty days after notification of rejection or the claim is forever barred. The personal representative shall notify the claimant of the rejection and file an affidavit with the court showing the notification and the date of the notification. The personal representative shall notify the claimant of the rejection by personal service or certified mail addressed to the claimant or the claimant's agent, if applicable, at the address stated in the claim. The date of service or of the postmark is the date of notification. The notification must advise the claimant that the claimant must bring suit in the proper court against the personal representative within thirty days after notification of rejection or the claim will be forever barred.

. The personal representative may, before or after rejection of any claim, compromise the claim, whether due or not, absolute or contingent, liquidated, or unliquidated, if it appears to the personal representative that the compromise is in the best interests of the estate.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5110-S.SL.pdf?cite=1997%20c%20252%20§%2016[1997 c 252 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c117.pdf?cite=1974%20ex.s.%20c%20117%20§%2047[1974 ex.s. c 117 § 47]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.40.100[1965 c 145 § 11.40.100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20116[1917 c 156 § 116]; RRS § 1486; prior: Code 1881 § 1476; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20281%20§%2088[1854 p 281 § 88]; ]

== 11.40.110 - Action pending at decedent's death—Personal representative as defendant.
If an action is pending against the decedent at the time of the decedent's death, the plaintiff shall, within four months after appointment of the personal representative, serve on the personal representative a petition to have the personal representative substituted as defendant in the action. Upon hearing on the petition, the personal representative shall be substituted, unless, at or before the hearing, the claim of the plaintiff, together with costs, is allowed.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5110-S.SL.pdf?cite=1997%20c%20252%20§%2017[1997 c 252 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c117.pdf?cite=1974%20ex.s.%20c%20117%20§%2038[1974 ex.s. c 117 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.40.110[1965 c 145 § 11.40.110]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20117[1917 c 156 § 117]; RRS § 1487; prior: Code 1881 § 1477; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20282%20§%2089[1854 p 282 § 89]; ]

== 11.40.120 - Effect of judgment against personal representative.
The effect of any judgment rendered against a personal representative shall be only to establish the amount of the judgment as an allowed claim.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5110-S.SL.pdf?cite=1997%20c%20252%20§%2018[1997 c 252 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.40.120[1965 c 145 § 11.40.120]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20118[1917 c 156 § 118]; RRS § 1488; prior: Code 1881 § 1478; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20282%20§%2090[1854 p 282 § 90]; ]

== 11.40.130 - Judgment against decedent—Execution barred upon decedent's death—Presentation—Sale of property.
If a judgment was entered against the decedent during the decedent's lifetime, an execution may not issue on the judgment after the death of the decedent. The judgment must be presented in the manner provided in RCW 11.40.070, but if the judgment is a lien on any property of the decedent, the property may be sold for the satisfaction of the judgment and the officer making the sale shall account to the personal representative for any surplus.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5110-S.SL.pdf?cite=1997%20c%20252%20§%2019[1997 c 252 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.40.130[1965 c 145 § 11.40.130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20119[1917 c 156 § 119]; RRS § 1489; prior: Code 1881 § 1479; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20292%20§%2091[1854 p 292 § 91]; ]

== 11.40.135 - Secured claim—Creditor's right.
If a creditor's claim is secured by any property of the decedent, this chapter does not affect the right of a creditor to realize on the creditor's security, whether or not the creditor presented the claim in the manner provided in RCW 11.40.070.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5110-S.SL.pdf?cite=1997%20c%20252%20§%2020[1997 c 252 § 20]; ]

== 11.40.140 - Claim of personal representative—Presentation and petition—Filing.
If the personal representative has a claim against the decedent, the personal representative must present the claim in the manner provided in RCW 11.40.070, and the allowance or rejection of the claim shall be addressed, resolved, and settled under the procedures provided under chapter 11.96A RCW. This section applies whether or not the personal representative is acting under nonintervention powers.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5132.SL.pdf?cite=2021%20c%20140%20§%204001[2021 c 140 § 4001]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20608[1999 c 42 § 608]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5110-S.SL.pdf?cite=1997%20c%20252%20§%2021[1997 c 252 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.40.140[1965 c 145 § 11.40.140]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20120[1917 c 156 § 120]; RRS § 1490; prior: Code 1881 § 1482; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20283%20§%2094[1854 p 283 § 94]; ]

== 11.40.150 - Notice to creditors when personal representative resigns, dies, or is removed—Limit tolled by vacancy.
. If a personal representative has given notice under RCW 11.40.020 and then resigns, dies, or is removed, the successor personal representative shall:

.. Publish notice of the vacancy and succession for two successive weeks in the legal newspaper in which notice was published under RCW 11.40.020 if the vacancy occurred within twenty-four months after the decedent's date of death; and

.. Provide actual notice of the vacancy and succession to a creditor if: (i) The creditor filed a claim and the claim had not been accepted or rejected by the prior personal representative; or (ii) the creditor's claim was rejected and the vacancy occurred within thirty days after rejection of the claim.

. The time between the resignation, death, or removal and first publication of the vacancy and succession or, in the case of actual notice, the mailing of the notice of vacancy and succession must be added to the time within which a claim must be presented or a suit on a rejected claim must be filed. This section does not extend the twenty-four month self-executing bar under RCW 11.40.051.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5110-S.SL.pdf?cite=1997%20c%20252%20§%2022[1997 c 252 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.40.150[1965 c 145 § 11.40.150]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c26.pdf?cite=1939%20c%2026%20§%201[1939 c 26 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20121[1917 c 156 § 121]; RRS § 1491; prior:  1891 c 155 § 28; Code 1881 § 1485; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20288%20§%20172[1873 p 288 § 172]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1867%20p%20106%20§%203[1867 p 106 § 3]; ]

== 11.40.160 - Personal representative as successor to notice agent—Notice not affected—Presumptions—Duties.
If a notice agent had commenced nonprobate notice to creditors under chapter 11.42 RCW, the appointment of the personal representative does not affect the filing and publication of notice to creditors and does not affect actual notice to creditors given by the notice agent. The personal representative is presumed to have adopted or ratified all acts of the notice agent unless, within thirty days of appointment, the personal representative provides notice of rejection or nullification to the affected claimant or claimants by personal service or certified mail addressed to the claimant or claimant's agent, if applicable, at the address stated on the claim. The personal representative shall also provide notice under RCW 11.42.150.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5110-S.SL.pdf?cite=1997%20c%20252%20§%2023[1997 c 252 § 23]; ]

== 11.40.900 - Construction—Chapter applicable to state registered domestic partnerships—2009 c 521.
For the purposes of this chapter, the terms spouse, marriage, marital, husband, wife, widow, widower, next of kin, and family shall be interpreted as applying equally to state registered domestic partnerships or individuals in state registered domestic partnerships as well as to marital relationships and married persons, and references to dissolution of marriage shall apply equally to state registered domestic partnerships that have been terminated, dissolved, or invalidated, to the extent that such interpretation does not conflict with federal law. Where necessary to implement chapter 521, Laws of 2009, gender-specific terms such as husband and wife used in any statute, rule, or other law shall be construed to be gender neutral, and applicable to individuals in state registered domestic partnerships.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%2031[2009 c 521 § 31]; ]

