= 11.44 - Inventory and appraisement.
:toc:

== 11.44.015 - Inventory and appraisement—Filing—Copy distribution.
. Within three months after appointment, unless a longer time shall be granted by the court, every personal representative shall make and verify by affidavit a true inventory and appraisement of all of the property of the estate passing under the will or by laws of intestacy and which shall have come to the personal representative's possession or knowledge, including a statement of all encumbrances, liens, or other secured charges against any item. The personal representative shall determine the fair net value, as of the date of the decedent's death, of each item contained in the inventory after deducting the encumbrances, liens, and other secured charges on the item. Such property shall be classified as follows:

.. Real property, by legal description;

.. Stocks and bonds;

.. Mortgages, notes, and other written evidences of debt;

.. Bank accounts and money;

.. Furniture and household goods;

.. All other personal property accurately identified, including the decedent's proportionate share in any partnership, but no inventory of the partnership property shall be required of the personal representative.

. The inventory and appraisement may, but need not be, filed in the probate cause, but upon receipt of a written request for a copy of the inventory and appraisement from any heir, legatee, devisee, unpaid creditor who has filed a claim, or beneficiary of a nonprobate asset from whom contribution is sought under RCW 11.18.200, or from the department of revenue, the personal representative shall furnish to the person, within ten days of receipt of a request, a true and correct copy of the inventory and appraisement.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5110-S.SL.pdf?cite=1997%20c%20252%20§%2041[1997 c 252 § 41]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c168.pdf?cite=1967%20c%20168%20§%209[1967 c 168 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.44.015[1965 c 145 § 11.44.015]; ]

== 11.44.025 - Additional inventory and appraisement—Copy distribution.
Whenever any property of the estate not mentioned in the inventory and appraisement comes to the knowledge of a personal representative, the personal representative shall cause the property to be inventoried and appraised and shall make and verify by affidavit a true inventory and appraisement of the property within thirty days after the discovery thereof, unless a longer time shall be granted by the court, and shall provide a copy of the inventory and appraisement to every person who has properly requested a copy of the inventory and appraisement under RCW 11.44.015(2).

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5110-S.SL.pdf?cite=1997%20c%20252%20§%2042[1997 c 252 § 42]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c117.pdf?cite=1974%20ex.s.%20c%20117%20§%2048[1974 ex.s. c 117 § 48]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.44.025[1965 c 145 § 11.44.025]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%20100[1917 c 156 § 100]; RCW  11.44.060; RRS § 1470; prior: Code 1881 § 1453; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20281%20§%20138[1873 p 281 § 138]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20277%20§%2064[1854 p 277 § 64]; ]

== 11.44.035 - Inventory and appraisement may be contradicted or avoided.
In an action against the personal representative where the administration of the estate, or any part thereof, is put in issue and the inventory and appraisement of the estate by the personal representative is given in evidence, the same may be contradicted or avoided by evidence. Any party in interest in the estate may challenge the inventory and appraisement at any stage of the probate proceedings.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5110-S.SL.pdf?cite=1997%20c%20252%20§%2043[1997 c 252 § 43]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.44.035[1965 c 145 § 11.44.035]; Code 1881 § 721; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20146%20§%20725[1877 p 146 § 725]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20166%20§%20662[1869 p 166 § 662]; RCW  11.48.170; RRS § 970; ]

== 11.44.050 - Inventory and appraisement—Failure to return or provide copy—Revocation of letters.
If any personal representative shall neglect or refuse to make the inventory and appraisement within the period prescribed, or within such further time as the court may allow, or to provide a copy as provided under RCW 11.44.015, 11.44.025, or 11.44.035, the court may revoke the letters testamentary or of administration; and the personal representative shall be liable on his or her bond to any party interested for the injury sustained by the estate through his or her neglect.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5110-S.SL.pdf?cite=1997%20c%20252%20§%2044[1997 c 252 § 44]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.44.050[1965 c 145 § 11.44.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%2099[1917 c 156 § 99]; RRS § 1469; prior: Code 1881 § 1457; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20281%20§%20138[1873 p 281 § 138]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20278%20§%2069[1854 p 278 § 69]; ]

== 11.44.070 - Persons assisting in appraisement—Compensation—Refund.
The personal representative may employ a qualified and disinterested person to assist in ascertaining the fair market value as of the date of the decedent's death of any asset the value of which may be subject to reasonable doubt. Different persons may be employed to appraise different kinds of assets included in the estate. The amount of the fee to be paid to any persons assisting the personal representative in any appraisement shall be determined by the personal representative: PROVIDED HOWEVER, That the reasonableness of any such compensation shall, at the time of hearing on any final account as provided in chapter 11.76 RCW or on a request or petition under RCW 11.68.100 or 11.68.110, be reviewed by the court in accordance with the provisions of RCW 11.68.100, and if the court determines the compensation to be unreasonable, a personal representative may be ordered to make appropriate refund.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5110-S.SL.pdf?cite=1997%20c%20252%20§%2045[1997 c 252 § 45]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c117.pdf?cite=1974%20ex.s.%20c%20117%20§%2050[1974 ex.s. c 117 § 50]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c168.pdf?cite=1967%20c%20168%20§%2010[1967 c 168 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.44.070[1965 c 145 § 11.44.070]; ]

== 11.44.085 - Claims against personal representative included.
The naming or the appointment of any person as personal representative shall not operate as a discharge from any just claim which the testator or intestate had against the personal representative, but the claim shall be included in the inventory and appraisement and the personal representative shall be liable to the same extent as the personal representative would have been had he or she not been appointed personal representative.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5110-S.SL.pdf?cite=1997%20c%20252%20§%2046[1997 c 252 § 46]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.44.085[1965 c 145 § 11.44.085]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%2097[1917 c 156 § 97]; RCW  11.44.030; RRS § 1467; prior: Code 1881 § 1449; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1860%20p%2063%20§%205[1860 p 63 § 5]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20277%20§%2060[1854 p 277 § 60]; ]

== 11.44.090 - Discharge of debt—Specific bequest and inclusion in inventory and appraisement.
The discharge or bequest in a will of any debt or demand of the testator against any executor named in the testator's will or against any person shall not be valid against the creditors of the deceased, but shall be construed as a specific bequest of such debt or demand, and the amount thereof shall be included in the inventory and appraisement, and shall, if necessary, be applied in payment of the testator's debts; if not necessary for that purpose, it shall be paid in the same manner and proportions as other specific legacies.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5110-S.SL.pdf?cite=1997%20c%20252%20§%2047[1997 c 252 § 47]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c145.pdf?cite=1965%20c%20145%20§%2011.44.090[1965 c 145 § 11.44.090]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c156.pdf?cite=1917%20c%20156%20§%2098[1917 c 156 § 98]; RCW  11.44.040; RRS § 1468; prior: Code 1881 § 1450; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20277%20§%2061[1854 p 277 § 61]; ]

