= 11.102 - Common trust funds.
:toc:

== 11.102.010 - Funds authorized—Investment—Rules and regulations—"Affiliated" defined.
Any bank or trust company qualified to act as fiduciary in this state, or in any other state if affiliated with a bank or trust company qualified to act as fiduciary in this state, may establish common trust funds for the purpose of furnishing investments to itself and its affiliated or related bank or trust company as fiduciary, or to itself and its affiliated or related bank or trust company, and others, as cofiduciaries; and may, as such fiduciary or cofiduciary, invest funds which it lawfully holds for investment in interests in such common trust funds, if such investment is not prohibited by the instrument, judgment, decree, or order creating such fiduciary relationship, and if, in the case of cofiduciaries, the bank or trust company procures the consent of its cofiduciary or cofiduciaries to such investment: PROVIDED, That any bank or trust company qualified to act as fiduciary in the state of its charter, which is not a member of the federal reserve system, shall, in the operation of such common trust fund, comply with the rules and regulations as made from time to time by the director of financial institutions in the state where chartered and in Washington the director is hereby authorized and empowered to make such rules and regulations as he or she may deem necessary and proper in the premises.

"Affiliated" as used in this section means two or more banks or trust companies:

. In which twenty-five percent or more of their voting shares, excluding shares owned by the United States or by any company wholly owned by the United States, are directly or indirectly owned or controlled by a holding company; or

. In which the election of a majority of the directors is controlled in any manner by a holding company.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%201[1994 c 92 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c30.pdf?cite=1985%20c%2030%20§%2079[1985 c 30 § 79]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c105.pdf?cite=1979%20c%20105%20§%201[1979 c 105 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.28.010[1955 c 33 § 30.28.010]; prior:  1943 c 55 § 1; Rem. Supp. 1943 § 3388; ]

== 11.102.020 - Accounting.
Unless ordered by a court of competent jurisdiction the bank or trust company operating such common trust funds is not required to render a court accounting with regard to such funds; but it may, by application to the superior court, secure approval of such an accounting on such conditions as the court may establish.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c30.pdf?cite=1985%20c%2030%20§%2080[1985 c 30 § 80]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.28.020[1955 c 33 § 30.28.020]; prior:  1943 c 55 § 2; Rem. Supp. 1943 § 3388-1; ]

== 11.102.030 - Applicability of chapter.
This chapter shall apply to fiduciary relationships in existence on June 11, 1943, or thereafter established.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c30.pdf?cite=1985%20c%2030%20§%2081[1985 c 30 § 81]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.28.030[1955 c 33 § 30.28.030]; prior:  1943 c 55 § 7; Rem. Supp. 1943 § 3388-6; ]

== 11.102.040 - Interpretation of chapter.
This chapter shall be so interpreted and construed to effectuate its general purpose to make uniform the laws of those states which enact it.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c30.pdf?cite=1985%20c%2030%20§%2082[1985 c 30 § 82]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.28.040[1955 c 33 § 30.28.040]; prior:  1943 c 55 § 3; Rem. Supp. 1943 § 3388-2; ]

== 11.102.050 - Short title.
This chapter may be cited as the uniform common trust fund act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c30.pdf?cite=1985%20c%2030%20§%2083[1985 c 30 § 83]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.28.050[1955 c 33 § 30.28.050]; prior:  1943 c 55 § 4; Rem. Supp. 1943 § 3388-3; ]

