= 11.120 - Uniform fiduciary access to digital assets act.
:toc:

== 11.120.010 - Short title—2016 c 140.
This act may be known and cited as the revised uniform fiduciary access to digital assets act.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5029-S.SL.pdf?cite=2016%20c%20140%20§%201[2016 c 140 § 1]; ]

== 11.120.020 - Definitions.
In this chapter:

. "Account" means an arrangement under a terms-of-service agreement in which a custodian carries, maintains, processes, receives, or stores a digital asset of the user or provides goods or services to the user.

. "Agent" means an attorney-in-fact granted authority under a durable or nondurable power of attorney.

. "Carries" means engages in the transmission of an electronic communication.

. "Catalogue of electronic communications" means information that identifies each person with which a user has had an electronic communication, the time and date of the communication, and the electronic address of the person.

. "Content of an electronic communication" means information concerning the substance or meaning of the communication which:

.. Has been sent or received by a user;

.. Is in electronic storage by a custodian providing an electronic communication service to the public or is carried or maintained by a custodian providing a remote computing service to the public; and

.. Is not readily accessible to the public.

. "Court" means the superior court of each county.

. "Custodian" means a person that carries, maintains, processes, receives, or stores a digital asset of a user.

. "Designated recipient" means a person chosen by a user using an online tool to administer digital assets of the user.

. "Digital asset" means an electronic record in which an individual has a right or interest. The term does not include an underlying asset or liability unless the asset or liability is itself an electronic record.

. "Electronic" means relating to technology having electrical, digital, magnetic, wireless, optical, electromagnetic, or similar capabilities.

. "Electronic communication" has the meaning set forth in 18 U.S.C. Sec. 2510(12), as it existed on June 9, 2016.

. "Electronic communication service" means a custodian that provides to a user the ability to send or receive an electronic communication.

. "Fiduciary" means an original, additional, or successor personal representative, guardian, agent, or trustee.

. "Guardian" means a person appointed by a court to manage the estate or person, or both, of a living individual. The term includes a limited guardian or certified professional guardian.

. "Incapacitated person" means an individual for whom a guardian has been appointed.

. "Information" means data, text, images, videos, sounds, codes, computer programs, software, databases, or the like.

. "Online tool" means an electronic service provided by a custodian that allows the user, in an agreement distinct from the terms-of-service agreement between the custodian and user, to provide directions for disclosure or nondisclosure of digital assets to a third person.

. "Person" means an individual, estate, business or nonprofit entity, public corporation, government or governmental subdivision, agency, or instrumentality, or other legal entity.

. "Personal representative" means an executor, administrator, special administrator, or person that performs substantially the same function under law of this state other than this chapter.

. "Power of attorney" means a record that grants an agent authority to act in the place of a principal.

. "Principal" means an individual who grants authority to an agent in a power of attorney.

. "Record" means information that is inscribed on a tangible medium or that is stored in an electronic or other medium and is retrievable in perceivable form.

. "Remote computing service" means a custodian that provides to a user computer processing services or the storage of digital assets by means of an electronic communications system, as defined in 18 U.S.C. Sec. 2510(14), as it existed on June 9, 2016.

. "Terms-of-service agreement" means an agreement that controls the relationship between a user and a custodian.

. "Trustee" means a fiduciary with legal title to property under an agreement or declaration that creates a beneficial interest in another. The term includes a successor trustee.

. "User" means a person that has an account with a custodian.

. "Will" includes a codicil, testamentary instrument that only appoints an executor, and instrument that revokes or revises a testamentary instrument.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5029-S.SL.pdf?cite=2016%20c%20140%20§%202[2016 c 140 § 2]; ]

== 11.120.030 - Applicability.
. This chapter applies to:

.. A fiduciary acting under a will or power of attorney executed before, on, or after June 9, 2016;

.. A personal representative acting for a decedent who died before, on, or after June 9, 2016;

.. A guardian acting for an incapacitated person appointed before, on, or after June 9, 2016;

.. A trustee acting under a trust created before, on, or after June 9, 2016; and

.. A custodian if the user resides in this state or resided in this state at the time of the user's death.

. This chapter does not apply to a digital asset of an employer used by an employee in the ordinary course of the employer's business.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5029-S.SL.pdf?cite=2016%20c%20140%20§%203[2016 c 140 § 3]; ]

== 11.120.040 - User direction for disclosure of digital assets.
. A user may use an online tool to direct the custodian to disclose to a designated recipient or not to disclose some or all of the user's digital assets, including the content of electronic communications. If the online tool allows the user to modify or delete a direction at all times, a direction regarding disclosure using an online tool overrides a contrary direction by the user in a will, trust, power of attorney, or other record.

. If a user has not used an online tool to give direction under subsection (1) of this section or if the custodian has not provided an online tool, the user may allow or prohibit in a will, trust, power of attorney, or other record, disclosure to a fiduciary of some or all of the user's digital assets, including the content of electronic communications sent or received by the user.

. A user's direction under subsection (1) or (2) of this section overrides a contrary provision in a terms-of-service agreement that does not require the user to act affirmatively and distinctly from the user's assent to the terms-of-service agreement.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5029-S.SL.pdf?cite=2016%20c%20140%20§%204[2016 c 140 § 4]; ]

== 11.120.050 - Terms-of-service agreement.
. This chapter does not change or impair a right of a custodian or a user under a terms-of-service agreement to access and use digital assets of the user.

. This chapter does not give a fiduciary or a designated recipient any new or expanded rights other than those held by the user for whom, or for whose estate, the fiduciary or designated recipient acts or represents.

. A fiduciary's or designated recipient's access to digital assets may be modified or eliminated by a user, by federal law, or by a terms-of-service agreement if the user has not provided direction under RCW 11.120.040.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5029-S.SL.pdf?cite=2016%20c%20140%20§%205[2016 c 140 § 5]; ]

== 11.120.060 - Procedure for disclosing digital assets.
. When disclosing digital assets of a user under this chapter, the custodian may at its sole discretion:

.. Grant a fiduciary or designated recipient full access to the user's account;

.. Grant a fiduciary or designated recipient partial access to the user's account sufficient to perform the tasks with which the fiduciary or designated recipient is charged; or

.. Provide a fiduciary or designated recipient a copy in a record of any digital asset that, on the date the custodian received the request for disclosure, the user could have accessed if the user were alive and had full capacity and access to the account.

. A custodian may assess a reasonable administrative charge for the cost of disclosing digital assets under this chapter.

. A custodian need not disclose under this chapter a digital asset deleted by a user.

. If a user directs or a fiduciary or designated recipient requests a custodian to disclose under this chapter some, but not all, of the user's digital assets, the custodian need not disclose the assets if segregation of the assets would impose an undue burden on the custodian. If the custodian believes the direction or request imposes an undue burden, the custodian or the fiduciary or designated recipient may seek an order from the court to disclose:

.. A subset limited by date of the user's digital assets;

.. All of the user's digital assets to the fiduciary or designated recipient;

.. None of the user's digital assets; or

.. All of the user's digital assets to the court for review in camera.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5029-S.SL.pdf?cite=2016%20c%20140%20§%206[2016 c 140 § 6]; ]

== 11.120.070 - Disclosure of content of electronic communications of deceased user.
If a deceased user consented to or a court directs disclosure of the contents of electronic communications of the user, the custodian shall disclose to the personal representative of the estate of the user the content of an electronic communication sent or received by the user if the personal representative gives the custodian:

. A written request for disclosure in physical or electronic form;

. A certified copy of the death certificate of the user;

. A certified copy of the letter of appointment of the representative, or a small estate affidavit or court order;

. Unless the user provided direction using an online tool, a copy of the user's will, trust, power of attorney, or other record evidencing the user's consent to disclosure of the content of electronic communications; and

. If requested by the custodian:

.. A number, user name, address, or other unique subscriber or account identifier assigned by the custodian to identify the user's account;

.. Evidence linking the account to the user; or

.. A finding by the court that:

... The user had a specific account with the custodian, identifiable by the information specified in (a) of this subsection;

... Disclosure of the content of electronic communications of the user would not violate 18 U.S.C. Sec. 2701 et seq. and 47 U.S.C. Sec. 222, existing on June 9, 2016, or other applicable law;

... Unless the user provided direction using an online tool, the user consented to disclosure of the content of electronic communications; or

... Disclosure of the content of electronic communications of the user is reasonably necessary for administration of the estate.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5029-S.SL.pdf?cite=2016%20c%20140%20§%207[2016 c 140 § 7]; ]

== 11.120.080 - Disclosure of other digital assets of deceased user.
Unless the user prohibited disclosure of digital assets or the court directs otherwise, a custodian shall disclose to the personal representative of the estate of a deceased user a catalogue of electronic communications sent or received by the user and digital assets, other than the content of electronic communications of the user, if the representative gives the custodian:

. A written request for disclosure in physical or electronic form;

. A certified copy of the death certificate of the user;

. A certified copy of the letter of appointment of the representative, or a small estate affidavit or court order; and

. If requested by the custodian:

.. A number, user name, or address, or other unique subscriber or account identifier assigned by the custodian to identify the user's account;

.. Evidence linking the account to the user;

.. An affidavit stating that disclosure of the user's digital assets is reasonably necessary for administration of the estate; or

.. A finding by the court that:

... The user had a specific account with the custodian, identifiable by the information specified in (a) of this subsection; or

... Disclosure of the user's digital assets is reasonably necessary for administration of the estate.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5029-S.SL.pdf?cite=2016%20c%20140%20§%208[2016 c 140 § 8]; ]

== 11.120.090 - Disclosure of content of electronic communications of principal.
To the extent a power of attorney expressly grants an agent authority over the content of electronic communications sent or received by the principal and unless directed otherwise by the principal or the court, a custodian shall disclose to the agent the content if the agent gives the custodian:

. A written request for disclosure in physical or electronic form;

. An original or copy of the power of attorney expressly granting the agent authority over the content of electronic communications of the principal;

. A certification by the agent, under penalty of perjury, that the power of attorney is in effect; and

. If requested by the custodian:

.. A number, user name, address, or other unique subscriber or account identifier assigned by the custodian to identify the principal's account; or

.. Evidence linking the account to the principal.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5029-S.SL.pdf?cite=2016%20c%20140%20§%209[2016 c 140 § 9]; ]

== 11.120.100 - Disclosure of other digital assets of principal.
Unless otherwise ordered by the court, directed by the principal, or provided by a power of attorney, a custodian shall disclose to an agent with specific authority over digital assets or general authority to act on behalf of a principal a catalogue of electronic communications sent or received by the principal and digital assets, other than the content of electronic communications of the principal, if the agent gives the custodian:

. A written request for disclosure in physical or electronic form;

. An original or a copy of the power of attorney that gives the agent specific authority over digital assets or general authority to act on behalf of the principal;

. A certification by the agent, under penalty of perjury, that the power of attorney is in effect; and

. If requested by the custodian:

.. A number, user name, address, or other unique subscriber or account identifier assigned by the custodian to identify the principal's account; or

.. Evidence linking the account to the principal.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5029-S.SL.pdf?cite=2016%20c%20140%20§%2010[2016 c 140 § 10]; ]

== 11.120.110 - Disclosure of digital assets held in trust when trustee is original user.
Unless otherwise ordered by the court or provided in a trust, a custodian shall disclose to a trustee that is an original user of an account any digital asset of that account held in trust, including a catalogue of electronic communications of the trustee and the content of electronic communications.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5029-S.SL.pdf?cite=2016%20c%20140%20§%2011[2016 c 140 § 11]; ]

== 11.120.120 - Disclosure of content of electronic communications held in trust when trustee not original user.
Unless otherwise ordered by the court, directed by the user, or provided in a trust, a custodian shall disclose to a trustee that is not an original user of an account the content of an electronic communication sent or received by an original or successor user and carried, maintained, processed, received, or stored by the custodian in the account of the trust if the trustee gives the custodian:

. A written request for disclosure in physical or electronic form;

. A certified copy of the trust instrument, or a certification of the trust under RCW 11.98.075, that includes consent to disclosure of the content of electronic communications to the trustee;

. A certification by the trustee, under penalty of perjury, that the trust exists and the trustee is a currently acting trustee of the trust; and

. If requested by the custodian:

.. A number, user name, address, or other unique subscriber or account identifier assigned by the custodian to identify the trust's account; or

.. Evidence linking the account to the trust.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5029-S.SL.pdf?cite=2016%20c%20140%20§%2012[2016 c 140 § 12]; ]

== 11.120.130 - Disclosure of other digital assets held in trust when trustee not original user.
Unless otherwise ordered by the court, directed by the user, or provided in a trust, a custodian shall disclose, to a trustee that is not an original user of an account, a catalogue of electronic communications sent or received by an original or successor user and stored, carried, or maintained by the custodian in an account of the trust and any digital assets, other than the content of electronic communications in which the trust has a right or interest, if the trustee gives the custodian:

. A written request for disclosure in physical or electronic form;

. A certified copy of the trust instrument or a certification of the trust under RCW 11.98.075;

. A certification by the trustee, under penalty of perjury, that the trust exists and the trustee is a currently acting trustee of the trust; and

. If requested by the custodian:

.. A number, user name, address, or other unique subscriber or account identifier assigned by the custodian to identify the trust's account; or

.. Evidence linking the account to the trust.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5029-S.SL.pdf?cite=2016%20c%20140%20§%2013[2016 c 140 § 13]; ]

== 11.120.140 - Disclosure of digital assets to guardian of incapacitated person. (Effective until January 1, 2022.)
. Unless otherwise ordered by the court, a guardian appointed due to a finding of incapacity under *RCW 11.88.010(1) has the right to access an incapacitated person's digital assets other than the content of electronic communications.

. Unless otherwise ordered by the court or directed by the user, a custodian shall disclose to a guardian the catalogue of electronic communications sent or received by an incapacitated person and any digital assets, other than the content of electronic communications, if the guardian gives the custodian:

.. A written request for disclosure in physical or electronic form;

.. Certified copies of letters of guardianship and the court order appointing the guardian; and

.. If requested by the custodian:

... A number, user name, address, or other unique subscriber or account identifier assigned by the custodian to identify the account of the person; or

... Evidence linking the account to the incapacitated person.

. A guardian may request a custodian of the incapacitated person's digital assets to suspend or terminate an account of the incapacitated person for good cause. A request made under this section must be accompanied by certified copies of letters of guardianship and the court order appointing the guardian.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5029-S.SL.pdf?cite=2016%20c%20140%20§%2014[2016 c 140 § 14]; ]

== 11.120.150 - Fiduciary duty and authority.
. The legal duties imposed on a fiduciary charged with managing tangible property apply to the management of digital assets, including:

.. The duty of care;

.. The duty of loyalty; and

.. The duty of confidentiality.

. A fiduciary's or designated recipient's authority with respect to a digital asset of a user:

.. Except as otherwise provided in RCW 11.120.040, is subject to the applicable terms-of-service agreement;

.. Is subject to other applicable law, including copyright law;

.. In the case of a fiduciary, is limited by the scope of the fiduciary's duties; and

.. May not be used to impersonate the user.

. A fiduciary with authority over the property of a decedent, incapacitated person, principal, or settlor has the right to access any digital asset in which the decedent, incapacitated person, principal, or settlor had a right or interest and that is not held by a custodian or subject to a terms-of-service agreement.

. A fiduciary acting within the scope of the fiduciary's duties is an authorized user of the property of the decedent, incapacitated person, principal, or settlor for the purpose of applicable computer fraud and unauthorized computer access laws.

. A fiduciary with authority over the tangible, personal property of a decedent, incapacitated person, principal, or settlor:

.. Has the right to access the property and any digital asset stored in it; and

.. Is an authorized user for the purpose of computer fraud and unauthorized computer access laws.

. A custodian may disclose information in an account to a fiduciary of the user when the information is required to terminate an account used to access digital assets licensed to the user.

. A fiduciary of a user may request a custodian to terminate the user's account. A request for termination must be in writing, in either physical or electronic form, and accompanied by:

.. If the user is deceased, a certified copy of the death certificate of the user;

.. A certified copy of the letter of appointment of the representative or a small estate affidavit or court order, court order, power of attorney, or trust giving the fiduciary authority over the account; and

.. If requested by the custodian:

... A number, user name, address, or other unique subscriber or account identifier assigned by the custodian to identify the user's account;

... Evidence linking the account to the user; or

... A finding by the court that the user had a specific account with the custodian, identifiable by the information specified in (c)(i) of this subsection.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5029-S.SL.pdf?cite=2016%20c%20140%20§%2015[2016 c 140 § 15]; ]

== 11.120.160 - Custodian compliance and immunity.
. Not later than sixty days after receipt of the information required under RCW 11.120.070 through 11.120.150, a custodian shall comply with a request under this chapter from a fiduciary or designated recipient to disclose digital assets or terminate an account. If the custodian fails to comply, the fiduciary or designated recipient may apply to the court for an order directing compliance.

. An order under subsection (1) of this section directing compliance must contain a finding that compliance is not in violation of 18 U.S.C. Sec. 2702, as it existed on June 9, 2016.

. A custodian may notify the user that a request for disclosure or to terminate an account was made under this chapter.

. A custodian may deny a request under this chapter from a fiduciary or designated recipient for disclosure of digital assets or to terminate an account if the custodian is aware of any lawful access to the account following the receipt of the fiduciary's request.

. This section does not limit a custodian's ability to obtain or require a fiduciary or designated recipient requesting disclosure or termination under this chapter to obtain a court order which:

.. Specifies that an account belongs to the incapacitated person, trustor, decedent, or principal;

.. Specifies that there is sufficient consent from the incapacitated person, trustor, decedent, or principal to support the requested disclosure; and

.. Contains a finding required by law other than this chapter.

. A custodian and its officers, employees, and agents are immune from liability for an act or omission done in good faith in compliance with this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5029-S.SL.pdf?cite=2016%20c%20140%20§%2016[2016 c 140 § 16]; ]

== 11.120.900 - Uniformity of application and construction.
 In applying and construing this chapter, consideration must be given to the need to promote uniformity of the law with respect to its subject matter among states that enact it.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5029-S.SL.pdf?cite=2016%20c%20140%20§%2017[2016 c 140 § 17]; ]

== 11.120.901 - Relation to electronic signatures in global and national commerce act.
This chapter modifies, limits, or supersedes the electronic signatures in global and national commerce act, 15 U.S.C. Sec. 7001 et seq., but does not modify, limit, or supersede 15 U.S.C. Sec. 7001(c) or authorize electronic delivery of any of the notices described in 15 U.S.C. Sec. 7003(b).

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5029-S.SL.pdf?cite=2016%20c%20140%20§%2018[2016 c 140 § 18]; ]

