= 11.125 - Uniform power of attorney act.
:toc:

== 11.125.010 - Short title—2016 c 209.
Chapter 209, Laws of 2016 may be known and cited as the uniform power of attorney act.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20101[2016 c 209 § 101]; ]

== 11.125.020 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Agent" means a person granted authority to act for a principal under a power of attorney, whether denominated an agent, attorney-in-fact, or otherwise. The term includes an original agent, coagent, successor agent, and a person to which an agent's authority is delegated.

. "Durable," with respect to a power of attorney, means not terminated by the principal's incapacity.

. "Electronic" means relating to technology having electrical, digital, magnetic, wireless, optical, electromagnetic, or similar capabilities.

. "Good faith" means honesty in fact.

. "Incapacity" means inability of an individual to manage property, business, personal, or health care affairs because the individual:

.. Has an impairment in the ability to receive and evaluate information or make or communicate decisions even with the use of technological assistance; or

.. Is:

... An absentee, as defined in chapter 11.80 RCW; or

... Outside the United States and unable to return.

. "Person" means an individual, corporation, business trust, estate, trust, partnership, limited liability company, association, joint venture, public corporation, government or governmental subdivision, agency, or instrumentality, or any other legal or commercial entity.

. "Power of attorney" means a writing that uses the term "power of attorney" and grants authority to an agent to act in the place of the principal.

. "Presently exercisable general power of appointment," with respect to property or a property interest subject to a power of appointment, means power exercisable at the time in question to vest absolute ownership in the principal individually, the principal's estate, the principal's creditors, or the creditors of the principal's estate. The term includes a power of appointment not exercisable until the occurrence of a specified event, the satisfaction of an ascertainable standard, or the passage of a specified period only after the occurrence of the specified event, the satisfaction of the ascertainable standard, or the passage of the specified period. The term does not include a power exercisable in a fiduciary capacity or only by will.

. "Principal" means an individual who grants authority to an agent in a power of attorney.

. "Property" means anything that may be the subject of ownership, whether real or personal, legal or equitable, tangible or intangible, or any interest or right therein.

. "State" means a state of the United States, the District of Columbia, Puerto Rico, the United States Virgin Islands, or any territory or insular possession subject to the jurisdiction of the United States.

. "Stocks, bonds, and financial instruments" means stocks, bonds, mutual funds, and all other types of securities and financial instruments, whether held directly, indirectly, or in any other manner. The term shall also include but not be limited to commodity futures contracts, call or put options on stocks or stock indexes, derivatives, and margin accounts.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20102[2016 c 209 § 102]; ]

== 11.125.030 - Application—Exceptions.
. This chapter applies to all powers of attorney except:

.. A power to the extent it is coupled with an interest in the subject of the power, including a power given to or for the benefit of a creditor in connection with a credit transaction;

.. A proxy or other delegation to exercise voting rights or management rights with respect to an entity; and

.. A power created on a form prescribed by a government or governmental subdivision, agency, or instrumentality for a governmental purpose.

. Notwithstanding subsection (1) of this section, RCW 11.125.170 shall not apply to a power to make health care decisions under RCW 11.125.400 and 11.125.410, nor shall it apply to the power to nominate a guardian for a minor child under RCW 11.125.410.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20103[2016 c 209 § 103]; ]

== 11.125.040 - Power of attorney—Termination.
The authority conferred under a power of attorney created prior to January 1, 2017, and also for a power of attorney created on or after January 1, 2017, terminates upon the incapacity of the principal unless the writing contains the words "This power of attorney shall not be affected by disability of the principal," or "This power of attorney shall become effective upon the disability of the principal," or similar words showing the intent of the principal that the authority conferred shall be exercisable notwithstanding the principal's incapacity.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20104[2016 c 209 § 104]; ]

== 11.125.050 - Power of attorney—Requirements.
. A power of attorney must be signed and dated by the principal, and the signature must be either acknowledged before a notary public or other individual authorized by law to take acknowledgments, or attested by two or more competent witnesses who are neither home care providers for the principal nor care providers at an adult family home or long-term care facility in which the principal resides, and who are unrelated to the principal or agent by blood, marriage, or state registered domestic partnership, by subscribing their names to the power of attorney, while in the presence of the principal and at the principal's direction or request.

. A power of attorney shall be considered signed in accordance with this section if, in the case of a principal who is physically unable to sign his or her name, the principal makes a mark in accordance with RCW 11.12.030, or in the case of a principal who is physically unable to make a mark, the power of attorney is executed in accordance with RCW 64.08.100.

. A signature on a power of attorney is presumed to be genuine if the principal acknowledges the signature before a notary public or other individual authorized by law to take acknowledgments.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20105[2016 c 209 § 105]; ]

== 11.125.060 - Power of attorney—Validity.
. A power of attorney executed in this state on or after January 1, 2017, is valid if its execution complies with RCW 11.125.050.

. A power of attorney executed in this state before January 1, 2017, is valid if its execution complied with the law of this state as it existed at the time of execution.

. A power of attorney executed other than in this state is valid in this state if, when the power of attorney was executed, the execution complied with:

.. The law of the jurisdiction that determines the meaning and effect of the power of attorney pursuant to RCW 11.125.070; or

.. The requirements for a military power of attorney pursuant to 10 U.S.C. Sec. 1044b, as amended.

. Except as otherwise provided by statute other than chapter 209, Laws of 2016, a photocopy or electronically transmitted copy of an original power of attorney has the same effect as the original.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20106[2016 c 209 § 106]; ]

== 11.125.070 - Power of attorney—Meaning and effect.
The meaning and effect of a power of attorney is determined by the law of the jurisdiction indicated in the power of attorney and, in the absence of an indication of jurisdiction, by the law of the jurisdiction in which the power of attorney was executed.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20107[2016 c 209 § 107]; ]

== 11.125.080 - Guardian of principal's estate or person. (Effective until January 1, 2022.)
. In a power of attorney, a principal may nominate a guardian of the principal's estate or guardian of the principal's person for consideration by the court if protective proceedings for the principal's estate or person are begun after the principal executes the power of attorney. Except for good cause shown or disqualification, the court shall make its appointment in accordance with the principal's most recent nomination.

. If, after a principal executes a power of attorney, a court appoints a guardian of the principal's estate or other fiduciary charged with the management of all of the principal's property, the power of attorney remains in effect subject to the provisions of RCW 11.130.335(1).

. If, after a principal executes a power of attorney, a court appoints a guardian of the principal's estate or other fiduciary charged with the management of some but not all of the principal's property, the power of attorney shall not terminate or be modified, except to the extent ordered by the court.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5604-S2.SL.pdf?cite=2019%20c%20437%20§%20316[2019 c 437 § 316]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20108[2016 c 209 § 108]; ]

== 11.125.090 - Power of attorney—When effective—Principal's personal representative for health care.
. A power of attorney is effective when executed unless the principal provides in the power of attorney that it becomes effective at a future date or upon the occurrence of a future event or contingency.

. If a power of attorney becomes effective upon the occurrence of a future event or contingency, the principal, in the power of attorney, may authorize one or more persons to determine in a writing that the event or contingency has occurred.

. If a power of attorney becomes effective upon the principal's incapacity and the principal has not authorized a person to determine whether the principal is incapacitated, or the person authorized is unable or unwilling to make the determination, the power of attorney becomes effective upon a determination in a writing by:

.. A physician or licensed psychologist, unrelated to the principal or agent by blood or marriage, who has personally examined the principal, that the principal is incapacitated within the meaning of RCW 11.125.020(5)(a); or

.. A judge or an appropriate governmental official that the principal is incapacitated within the meaning of RCW 11.125.020(5)(b).

. A person authorized by the principal in the power of attorney to determine that the principal is incapacitated may act as the principal's personal representative pursuant to the health insurance portability and accountability act, sections 1171 through 1179 of the social security act, 42 U.S.C. Sec. 1320d, as amended, and applicable regulations, to obtain access to the principal's health care information and communicate with the principal's health care provider.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20109[2016 c 209 § 109]; ]

== 11.125.100 - Power of attorney termination—Agent authority termination.
. A power of attorney terminates when:

.. The principal dies;

.. The principal becomes incapacitated, if the power of attorney is not durable;

.. The principal revokes the power of attorney;

.. The power of attorney provides that it terminates;

.. The purpose of the power of attorney is accomplished; or

.. The principal revokes the agent's authority or the agent dies, becomes incapacitated, or resigns, and the power of attorney does not provide for another agent to act under the power of attorney.

. An agent's authority terminates when:

.. The principal revokes the authority;

.. The agent dies, becomes incapacitated, or resigns;

.. An action is filed for the dissolution or annulment of the agent's marriage to the principal or for their legal separation, or an action is filed for dissolution or annulment of the agent's state registered domestic partnership with the principal or for their legal separation, unless the power of attorney otherwise provides; or

.. The power of attorney terminates.

. An agent's authority which has been terminated under subsection (2)(c) of this section shall be reinstated effective immediately in the event that such action is dismissed with the consent of both parties or the petition for dissolution, annulment, or legal separation is withdrawn.

. Unless the power of attorney otherwise provides, an agent's authority is exercisable until the authority terminates under subsection (2) of this section, notwithstanding a lapse of time since the execution of the power of attorney.

. Termination of an agent's authority or of a power of attorney is not effective as to the agent or another person that, without actual knowledge of the termination, acts in good faith under the power of attorney. An act so performed, unless otherwise invalid or unenforceable, binds the principal and the principal's successors in interest.

. Incapacity of the principal of a power of attorney that is not durable does not revoke or terminate the power of attorney as to an agent or other person that, without actual knowledge of the incapacity, acts in good faith under the power of attorney. An act so performed, unless otherwise invalid or unenforceable, binds the principal and the principal's successors in interest.

. The execution of a power of attorney does not revoke a power of attorney previously executed by the principal unless the subsequent power of attorney provides that the previous power of attorney is revoked or that all other powers of attorney are revoked.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20110[2016 c 209 § 110]; ]

== 11.125.110 - Coagents—Successor agents—Liability.
. A principal may designate in a power of attorney two or more persons to act as coagents. Unless the power of attorney otherwise provides, all coagents must exercise their authority jointly; provided, however, a coagent may delegate that coagent's authority to another coagent.

. A principal may designate one or more successor agents to act if an agent resigns, dies, becomes incapacitated, is not qualified to serve, or declines to serve. A principal may grant authority to designate one or more successor agents to an agent or other person designated by name, office, or function. Unless the power of attorney otherwise provides, a successor agent:

.. Has the same authority as that granted to the original agent; and

.. May not act until all predecessor agents have resigned, died, become incapacitated, are no longer qualified to serve, or have declined to serve.

. Except as otherwise provided in the power of attorney and subsection (4) of this section, an agent that does not participate in or conceal a breach of fiduciary duty committed by another agent, including a predecessor agent, is not liable for the actions of the other agent.

. An agent that has actual knowledge of a breach or imminent breach of fiduciary duty by another agent shall notify the principal and, if the principal is incapacitated, take any action reasonably appropriate in the circumstances to safeguard the principal's best interest. An agent that fails to notify the principal or take action as required by this subsection is liable for the reasonably foreseeable damages that could have been avoided if the agent had notified the principal or taken such action.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20111[2016 c 209 § 111]; ]

== 11.125.120 - Reimbursement of expenses for agents.
Unless the power of attorney otherwise provides, an agent is entitled to reimbursement of expenses reasonably incurred on behalf of the principal and to reasonable compensation.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20112[2016 c 209 § 112]; ]

== 11.125.130 - Accepting appointment as an agent.
Except as otherwise provided in the power of attorney, a person accepts appointment as an agent under a power of attorney by exercising authority or performing duties as an agent or by any other assertion or conduct indicating acceptance.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20113[2016 c 209 § 113]; ]

== 11.125.140 - Agents—Duties—Liability—Disclosures.
. Notwithstanding provisions in the power of attorney, an agent that has accepted appointment shall:

.. Act in accordance with the principal's reasonable expectations to the extent actually known by the agent and, otherwise, in the principal's best interest;

.. Act in good faith; and

.. Act only within the scope of authority granted in the power of attorney.

. Except as otherwise provided in the power of attorney, an agent that has accepted appointment shall:

.. Act loyally for the principal's benefit;

.. Act so as not to create a conflict of interest that impairs the agent's ability to act impartially in the principal's best interest;

.. Act with the care, competence, and diligence ordinarily exercised by agents in similar circumstances;

.. Keep a record of all receipts, disbursements, and transactions made on behalf of the principal;

.. Cooperate with a person that has authority to make health care decisions for the principal to carry out the principal's reasonable expectations to the extent actually known by the agent and, otherwise, act in the principal's best interest; and

.. Attempt to preserve the principal's estate plan, to the extent actually known by the agent, if preserving the plan is consistent with the principal's best interest based on all relevant factors, including:

... The value and nature of the principal's property;

... The principal's foreseeable obligations and need for maintenance;

... Minimization of taxes, including income, estate, inheritance, generation-skipping transfer, and gift taxes; and

... Eligibility for a benefit, a program, or assistance under a statute or rule.

. An agent that acts in good faith is not liable to any beneficiary of the principal's estate plan for failure to preserve the plan.

. An agent that acts with care, competence, and diligence for the best interest of the principal is not liable solely because the agent also benefits from the act or has an individual or conflicting interest in relation to the property or affairs of the principal.

. If an agent is selected by the principal because of special skills or expertise possessed by the agent or in reliance on the agent's representation that the agent has special skills or expertise, the special skills or expertise must be considered in determining whether the agent has acted with care, competence, and diligence under the circumstances.

. Absent a breach of duty to the principal, an agent is not liable if the value of the principal's property declines.

. An agent that engages another person on behalf of the principal is not liable for an act, error of judgment, or default of that person if the agent exercises care, competence, and diligence in selecting and monitoring the person, provided however that the agent shall not be relieved of liability for such person's discretionary acts, that, if done by the agent, would result in liability to the agent.

. Unless RCW 11.125.110(1) applies, an agent may only delegate authority to another person if expressly authorized to do so in the power of attorney and may delegate some, but not all, of the authority granted by the principal. An agent that exercises authority to delegate to another person the authority granted by the principal is not liable for an act, error of judgment, or default of that person if the agent exercises care, competence, and diligence in selecting and monitoring the person, provided however that the agent shall not be relieved of liability for such person's discretionary acts, that, if done by the agent, would result in liability to the agent.

. Except as otherwise provided in the power of attorney, an agent is not required to disclose receipts, disbursements, or transactions conducted on behalf of the principal unless ordered by a court or requested in writing by the principal, a guardian, a conservator, another fiduciary acting for the principal, a governmental agency having authority to protect the welfare of the principal, or, upon the death of the principal, by the personal representative or successor in interest of the principal's estate. Such request by a guardian, conservator, or another fiduciary acting for the principal must be limited to information reasonably related to that guardian, conservator, or fiduciary's duties. If so requested, within thirty days the agent shall comply with the request or provide a writing or other record substantiating why additional time is needed and shall comply with the request within an additional thirty days.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20114[2016 c 209 § 114]; ]

== 11.125.150 - Power of attorney provisions relieving agent liability—When allowed.
A provision in a power of attorney relieving an agent of liability for breach of duty is binding on the principal and the principal's successors in interest except to the extent the provision:

. Relieves the agent of liability for breach of duty committed dishonestly, with an improper motive, or with gross negligence to the purposes of the power of attorney or the best interest of the principal; or

. Was inserted as a result of an abuse of a confidential or fiduciary relationship with the principal.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20115[2016 c 209 § 115]; ]

== 11.125.160 - Court petition—Who may file—Reasons may file.
. Except as otherwise provided in the power of attorney, the following persons may bring a petition described in subsection (2) of this section:

.. The principal or the agent;

.. The spouse or state registered domestic partner of the principal;

.. The guardian of the estate or person of the principal;

.. Any other interested person, as long as the person demonstrates to the court's satisfaction that the person is interested in the welfare of the principal and has a good faith belief that the court's intervention is necessary, and that the principal is incapacitated at the time of filing the petition or otherwise unable to protect his or her own interests; and

.. A person asked to accept the power of attorney.

. A person designated in subsection (1) of this section may file a petition requesting the court to construe a power of attorney or grant any other appropriate relief, including but not limited to:

.. Determination of whether the power of attorney is in effect or has terminated;

.. Compelling the agent to submit the agent's accounts or report the agent's acts as agent to the principal, the spouse or state registered domestic partner of the principal, the guardian of the person or the estate of the principal, or to any other person required by the court in its discretion, if the agent has not timely complied with a request under RCW 11.125.140(9). However, a government agency having authority to protect the welfare of the principal may file a petition upon the agent's refusal or failure to submit an accounting upon written request and shall not be required to wait sixty days;

.. Ratification of past acts or approval of proposed acts of the agent;

.. Issuance of an order directing the agent to exercise or refrain from exercising authority in a power of attorney in a particular manner or for a particular purpose;

.. Modification of the authority of an agent under a power of attorney;

.. Removal of the agent on a determination by the court of both of the following:

... Determination that the agent has violated or is unfit to perform the fiduciary duties under the power of attorney; and

... Determination that the removal of the agent is in the best interest of the principal;

.. Approval of the resignation of the agent and approval of the final accountings of the resigning agent if submitted, subject to any orders the court determines are necessary to protect the principal's interests;

.. Confirmation of the authority of a successor agent to act under a power of attorney upon removal or resignation of the previous agent;

.. Compelling a third person to honor the authority of an agent, provided that a third person may not be compelled to honor the agent's authority if the principal could not compel the third person to act in the same circumstances;

.. Order the agent to furnish a bond in an amount the court determines to be appropriate.

. Any action commenced under this section shall be subject to the notice requirements of chapter 11.96A RCW.

. Upon motion by the principal, the court shall dismiss a petition filed under this section, unless the court finds that the principal lacks capacity to revoke the agent's authority or the power of attorney.

. Except as otherwise provided in RCW 11.125.200(3)(b), any action commenced under this section shall be subject to the provisions of RCW 11.96A.150.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20116[2016 c 209 § 116]; ]

== 11.125.170 - Chapter violations—Agent liability.
An agent that violates this chapter is liable to the principal or the principal's successors in interest for the amount required to restore the value of the principal's property to what it would have been had the violation not occurred.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20117[2016 c 209 § 117]; ]

== 11.125.180 - Agent resignation—Procedure.
Unless the power of attorney has been terminated in accordance with RCW 11.125.080, or the power of attorney provides a different method for an agent's resignation, an agent may resign by giving notice to the principal and, if the principal is incapacitated:

. To the conservator or guardian, if one has been appointed for the principal, and a coagent or successor agent, if designated; or

. If there is no person described in subsection (1) of this section:

.. To any person reasonably believed by the agent to have sufficient interest in the principal's welfare;

.. To a governmental agency having authority to protect the welfare of the principal; or

.. By filing notice with the county recorder's office in the county where the principal resides.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20118[2016 c 209 § 118]; ]

== 11.125.190 - Acknowledged power of attorney—When may rely upon—Certification or translation request.
. For purposes of this section and RCW 11.125.200, "acknowledged" means purportedly verified before a notary public or other individual authorized to take acknowledgments.

. A person that in good faith accepts an acknowledged power of attorney without actual knowledge that the signature is not genuine may rely upon the presumption under RCW 11.125.050 that the signature is genuine.

. A person that in good faith accepts an acknowledged power of attorney without actual knowledge that the power of attorney is void, invalid, or terminated, that the purported agent's authority is void, invalid, or terminated, or that the agent is exceeding or improperly exercising the agent's authority may rely upon the power of attorney as if the power of attorney were genuine, valid and still in effect, the agent's authority were genuine, valid and still in effect, and the agent had not exceeded and had properly exercised the authority.

. A person that is asked to accept an acknowledged power of attorney may request, and rely upon, without further investigation:

.. An agent's certification given under penalty of perjury meeting the requirements of subsection (5) of this section; and

.. An English translation of the power of attorney if the power of attorney contains, in whole or in part, language other than English.

. A certification presented pursuant to subsection (4) of this section or pursuant to RCW 11.125.200 shall state that:

.. The person presenting himself or herself as the agent and signing the affidavit or declaration is the person so named in the power of attorney;

.. If the agent is named in the power of attorney as a successor agent, the circumstances or conditions stated in the power of attorney that would cause that person to become the acting agent have occurred;

.. To the best of the agent's knowledge, the principal is still alive;

.. To the best of the agent's knowledge, at the time the power of attorney was signed, the principal was competent to execute the document and was not under undue influence to sign the document;

.. All events necessary to making the power of attorney effective have occurred;

.. The agent does not have actual knowledge of the revocation, termination, limitation, or modification of the power of attorney or of the agent's authority;

.. The agent does not have actual knowledge of the existence of other circumstances that would limit, modify, revoke, or terminate the power of attorney or the agent's authority to take the proposed action;

.. If the agent was married to or in a state registered domestic partnership with the principal at the time of execution of the power of attorney, then at the time of signing the affidavit or declaration, the marriage or state registered domestic partnership of the principal and the agent has not been dissolved or declared invalid, and no action is pending for the dissolution of the marriage or domestic partnership or for legal separation; and

.. The agent is acting in good faith pursuant to the authority given under the power of attorney.

. An English translation requested under this section must be provided at the principal's expense unless the request is made more than seven business days after the power of attorney is presented for acceptance.

. For purposes of this section and RCW 11.125.200, a person that conducts activities through employees is without actual knowledge of a fact relating to a power of attorney, a principal, or an agent if the employee conducting the transaction involving the power of attorney is without actual knowledge of the fact.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20119[2016 c 209 § 119]; ]

== 11.125.200 - Acknowledged power of attorney—Acceptance—Refusal to accept.
. Except as otherwise provided in subsection (2) of this section:

.. A person shall either accept an acknowledged power of attorney or request a certification or a translation no later than seven business days after presentation of the power of attorney for acceptance;

.. If a person requests a certification or a translation, the person shall accept the power of attorney no later than five business days after receipt of the certification or translation; and

.. A person may not require an additional or different form of power of attorney for authority granted in the power of attorney presented.

. A person is not required to accept an acknowledged power of attorney if:

.. The person is not otherwise required to engage in a transaction with the principal in the same circumstances;

.. Engaging in a transaction with the agent or the principal in the same circumstances would be inconsistent with federal law;

.. The person has actual knowledge of the termination of the agent's authority or of the power of attorney before exercise of the power;

.. A request for a certification or a translation is refused;

.. The person in good faith believes that the power is not valid or that the agent does not have the authority to perform the act requested, whether or not a certification or a translation has been requested or provided; or

.. The person makes, or has actual knowledge that another person has made, a report to the department of social and health services stating a good faith belief that the principal may be subject to physical or financial abuse, neglect, exploitation, or abandonment by the agent or a person acting for or with the agent.

. A person that refuses in violation of this section to accept an acknowledged power of attorney is subject to:

.. A court order mandating acceptance of the power of attorney; and

.. Liability for reasonable attorneys' fees and costs incurred in any action or proceeding that confirms the validity of the power of attorney or mandates acceptance of the power of attorney.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20120[2016 c 209 § 120]; ]

== 11.125.210 - Principles of law and equity—Supplemental to chapter.
Unless displaced by a provision of this chapter, the principles of law and equity supplement this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20121[2016 c 209 § 121]; ]

== 11.125.220 - Conflicting laws.
This chapter does not supersede any other law applicable to financial institutions or other entities, and the other law controls if inconsistent with this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20122[2016 c 209 § 122]; ]

== 11.125.230 - Remedies—Not exclusive.
The remedies under this chapter are not exclusive and do not abrogate any right or remedy under the law of this state other than this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20123[2016 c 209 § 123]; ]

== 11.125.240 - Agent—Authority over principal's property.
. An agent under a power of attorney may, subject to the requirements of RCW 11.125.140, and in particular RCW 11.125.140(2)(f), do the following on behalf of the principal or with the principal's property only if the power of attorney expressly grants the agent the authority and exercise of the authority is not otherwise prohibited by another agreement or instrument to which the authority or property is subject:

.. Create, amend, revoke, or terminate an inter vivos trust;

.. Make a gift;

.. Create or change rights of survivorship;

.. Create or change a beneficiary designation;

.. Delegate some but not all of the authority granted under the power of attorney, except as otherwise provided in RCW 11.125.110(1);

.. Waive the principal's right to be a beneficiary of a joint and survivor annuity, including a survivor benefit under a retirement plan;

.. Exercise fiduciary powers that the principal has authority to delegate;

.. Exercise any power of appointment in favor of anyone other than the principal;

.. Create, amend, or revoke a community property agreement;

.. Cause a trustee to make distributions of property held in trust under the same conditions that the principal could;

.. Make any other provisions for nonprobate transfer at death contained in nontestamentary instruments described in RCW 11.02.091;

.. Make health care decisions for the principal, or give informed consent to health care decisions on the principal's behalf.

. Notwithstanding the provisions of subsection (1)(a) of this section, an agent may, even in the absence of a specific grant of authority, make transfers of property to any trust that benefits the principal alone and does not have dispositive provisions that are different from those that would have governed the property had it not been transferred into such trust.

. Notwithstanding the provisions of subsection (1)(b) of this section, an agent may, even in the absence of a specific grant of authority, make any transfer of resources not prohibited under chapter 74.09 RCW when the transfer is for the purpose of qualifying the principal for medical assistance or the limited casualty program for the medically needy.

. Notwithstanding a grant of authority to do an act described in subsection (1) of this section, unless the power of attorney otherwise provides, an agent that is not an ancestor, spouse, state registered domestic partner, or descendant of the principal, may not exercise authority under a power of attorney to create in the agent, or in an individual to whom the agent owes a legal obligation of support, an interest in the principal's property, whether by gift, right of survivorship, beneficiary designation, disclaimer, or otherwise.

. Unless the power of attorney otherwise provides, a grant of authority to make a gift is subject to RCW 11.125.390.

. Subject to subsections (1) through (5) of this section, if the subjects over which authority is granted in a power of attorney are similar or overlap, the broadest authority controls.

. Authority granted in a power of attorney is exercisable with respect to property that the principal has when the power of attorney is executed or acquires later, whether or not the property is located in this state and whether or not the authority is exercised or the power of attorney is executed in this state.

. An act performed by an agent pursuant to a power of attorney has the same effect and inures to the benefit of and binds the principal and the principal's successors in interest as if the principal had performed the act.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20201[2016 c 209 § 201]; ]

== 11.125.250 - Agent—General authority—When created—When can be modified.
. Subject to the provisions of RCW 11.125.240, if a power of attorney grants to an agent authority to do all acts that a principal could do or contains words of similar effect, the agent has the general authority described in RCW 11.125.260 through 11.125.410.

. An agent has authority described in chapter 209, Laws of 2016 if the power of attorney refers to general authority with respect to the descriptive term for the subjects stated in RCW 11.125.270 through 11.125.410 or cites the section in which the authority is described.

. A reference in a power of attorney to general authority with respect to the descriptive term for a subject in RCW 11.125.270 through 11.125.410 or a citation to a section of RCW 11.125.270 through 11.125.410 incorporates the entire section as if it were set out in full in the power of attorney.

. A principal may modify authority incorporated by reference.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20202[2016 c 209 § 202]; ]

== 11.125.260 - Agent authority—General powers.
Except as otherwise provided in the power of attorney, by executing a power of attorney that incorporates by reference a subject described in RCW 11.125.270 through 11.125.410 or that grants to an agent authority to do all acts that a principal could do pursuant to RCW 11.125.250(1), a principal authorizes the agent, with respect to that subject, to:

. Demand, receive, and obtain by litigation or otherwise, declaratory or injunctive relief, money, or another thing of value to which the principal is, may become, or claims to be entitled, and conserve, invest, disburse, or use anything so received or obtained for the purposes intended;

. Contract in any manner with any person, on terms agreeable to the agent, to accomplish a purpose of a transaction and perform, rescind, cancel, terminate, reform, restate, release, or modify the contract or another contract made by or on behalf of the principal;

. Execute, acknowledge, seal, deliver, file, or record any instrument or communication the agent considers desirable to accomplish a purpose of a transaction, including creating at any time a schedule listing some or all of the principal's property and attaching it to the power of attorney;

. Initiate, participate in, submit to alternative dispute resolution, settle, oppose, or propose or accept a compromise with respect to a claim existing in favor of or against the principal or intervene in litigation relating to the claim;

. Seek on the principal's behalf the assistance of a court or other governmental agency to carry out an act authorized in the power of attorney;

. Engage, compensate, and discharge an attorney, accountant, investment manager, expert witness, or other advisor;

. Prepare, execute, and file a record, report, or other document to safeguard or promote the principal's interest under a statute or regulation;

. Communicate with any representative or employee of a government or governmental subdivision, agency, or instrumentality, on behalf of the principal;

. Access communications intended for, and communicate on behalf of the principal, whether by mail, electronic transmission, telephone, or other means; and

. Do any lawful act with respect to the subject and all property related to the subject.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20203[2016 c 209 § 203]; ]

== 11.125.270 - Agent authority—Real property.
Unless the power of attorney otherwise provides, language in a power of attorney granting general authority with respect to real property authorizes the agent to:

. Demand; buy; sublease; license; receive; accept as a gift or as security for an extension of credit; or otherwise acquire or reject an interest in real property or a right incident to real property;

. Sell; exchange; convey with or without reservations, covenants, representations, or warranties; quitclaim; release; surrender; retain title for security; encumber; partition; consent to partitioning; subject to an easement or covenant, common interest regime; subdivide; apply for zoning or other governmental permits; plat or consent to platting; develop; grant an option concerning; lease; sublease; license; contribute to an entity in exchange for an interest in that entity; or, subject to RCW 11.125.240, otherwise grant or dispose of an interest in real property or a right incident to real property;

. Pledge or mortgage an interest in real property or right incident to real property as security to borrow money or pay, renew, extend the time of payment of a debt of the principal or a debt guaranteed by the principal, or as security for a nonmonetary obligation;

. Release, assign, satisfy, or enforce by litigation or otherwise a mortgage, deed of trust, conditional sale contract, encumbrance, lien, or other claim to real property which exists or is asserted;

. Manage or conserve an interest in real property or a right incident to real property owned or claimed to be owned by the principal, including:

.. Insuring against liability or casualty or other loss;

.. Obtaining or regaining possession of or protecting the interest or right by litigation or otherwise;

.. Paying, assessing, compromising, or contesting taxes or assessments or applying for and receiving refunds in connection with them; and

.. Purchasing supplies, hiring assistance or labor, and making repairs or alterations to the real property;

. Use, develop, alter, replace, remove, erect, or install structures or other improvements upon real property in or incident to which the principal has, or claims to have, an interest or right;

. Participate in a reorganization with respect to real property or an entity that owns an interest in or right incident to real property and receive, and hold, and act with respect to stocks and bonds or other property received in a plan of reorganization, including:

.. Selling or otherwise disposing of them;

.. Exercising or selling an option, right of conversion, or similar right with respect to them; and

.. Exercising any voting rights in person or by proxy;

. Change the form of title of an interest in or right incident to real property; and

. Dedicate to public use, with or without consideration, easements or other real property in which the principal has, or claims to have, an interest.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20204[2016 c 209 § 204]; ]

== 11.125.280 - Agent authority—Tangible personal property.
Unless the power of attorney otherwise provides, language in a power of attorney granting general authority with respect to tangible personal property authorizes the agent to:

. Demand, buy, receive, accept as a gift or as security for an extension of credit, or otherwise acquire or reject ownership or possession of tangible personal property or an interest in tangible personal property;

. Sell; exchange; convey with or without covenants, representations, or warranties; quitclaim; release; surrender; create a security interest in; grant options concerning; lease; sublease; or, otherwise dispose of tangible personal property or an interest in tangible personal property;

. Grant a security interest in tangible personal property or an interest in tangible personal property as security to borrow money or pay, renew, or extend the time of payment of a debt of the principal or a debt guaranteed by the principal;

. Release, assign, satisfy, or enforce by litigation or otherwise, a security interest, lien, or other claim on behalf of the principal, with respect to tangible personal property or an interest in tangible personal property;

. Manage or conserve tangible personal property or an interest in tangible personal property on behalf of the principal, including:

.. Insuring against liability or casualty or other loss;

.. Obtaining or regaining possession of or protecting the property or interest, by litigation or otherwise;

.. Paying, assessing, compromising, or contesting taxes or assessments or applying for and receiving refunds in connection with taxes or assessments;

.. Moving the property from place to place;

.. Storing the property for hire or on a gratuitous bailment; and

.. Using and making repairs, alterations, or improvements to the property; and

. Change the form of title of an interest in tangible personal property.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20205[2016 c 209 § 205]; ]

== 11.125.290 - Agent authority—Stocks, bonds, and financial instruments.
Unless the power of attorney otherwise provides, language in a power of attorney granting general authority with respect to stocks, bonds, and financial instruments authorizes the agent to:

. Buy, sell, and exchange stocks, bonds, and financial instruments;

. Establish, continue, modify, or terminate an account with respect to stocks, bonds, and financial instruments;

. Pledge stocks, bonds, and financial instruments as security to borrow, pay, renew, or extend the time of payment of a debt of the principal;

. Receive certificates and other evidences of ownership with respect to stocks, bonds, and financial instruments;

. Exercise voting rights with respect to stocks, bonds, and financial instruments in person or by proxy, enter into voting trusts, and consent to limitations on the right to vote;

. Buy, sell, exchange, assign, settle, and exercise commodity futures contracts and call or put options on stocks or stock indexes traded on a regulated option exchange; and

. Establish, continue, modify, and terminate option accounts.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20206[2016 c 209 § 206]; ]

== 11.125.300 - Agent authority—Banks and financial institutions.
Except as otherwise expressly provided in chapter 209, Laws of 2016 and in chapter 30A.22 RCW, unless the power of attorney otherwise provides, language in a power of attorney granting general authority with respect to banks and other financial institutions authorizes the agent to:

. Continue, modify, and terminate an account or other banking arrangement made by or on behalf of the principal;

. Establish, modify, and terminate an account or other banking arrangement with a bank, trust company, savings and loan association, credit union, thrift company, brokerage firm, or other financial institution selected by the agent;

. Contract for services available from a financial institution, including renting a safe deposit box or space in a vault;

. Withdraw, by check, order, electronic funds transfer, or otherwise, money or property of the principal deposited with or left in the custody of a financial institution;

. Receive statements of account, vouchers, notices, and similar documents from a financial institution and act with respect to them;

. Enter a safe deposit box or vault and withdraw or add to the contents;

. Borrow money and pledge as security personal property of the principal necessary to borrow money or pay, renew, or extend the time of payment of a debt of the principal or a debt guaranteed by the principal;

. Make, assign, draw, endorse, discount, guarantee, and negotiate promissory notes, checks, drafts, and other negotiable or nonnegotiable paper of the principal or payable to the principal or the principal's order, transfer money, receive the cash or other proceeds of those transactions, and accept a draft drawn by a person upon the principal and pay it when due;

. Receive for the principal and act upon a sight draft, warehouse receipt, or other document of title whether tangible or electronic, or other negotiable or nonnegotiable instrument;

. Apply for, receive, and use letters of credit, credit and debit cards, electronic transaction authorizations, and traveler's checks from a financial institution and give an indemnity or other agreement in connection with letters of credit; and

. Consent to an extension of the time of payment with respect to commercial paper or a financial transaction with a financial institution.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20207[2016 c 209 § 207]; ]

== 11.125.310 - Agent authority—Operation of a business or entity.
Subject to the terms of a document or an agreement governing an entity or an entity ownership interest, and unless the power of attorney otherwise provides, language in a power of attorney granting general authority with respect to operation of an entity or business authorizes the agent to:

. Operate, buy, sell, enlarge, reduce, or terminate an ownership interest;

. Perform a duty or discharge a liability and exercise in person or by proxy a right, power, privilege, or option that the principal has, may have, or claims to have;

. Enforce the terms of an ownership agreement;

. Initiate, participate in, submit to alternative dispute resolution, settle, oppose, or propose or accept a compromise with respect to litigation to which the principal is a party because of an ownership interest;

. Exercise in person or by proxy, or enforce by litigation or otherwise, a right, power, privilege, or option the principal has or claims to have as the holder of stocks, bonds, and financial instruments;

. Initiate, participate in, submit to alternative dispute resolution, settle, oppose, or propose or accept a compromise with respect to litigation to which the principal is a party concerning stocks, bonds, and financial instruments;

. With respect to an entity or business owned solely by the principal:

.. Continue, modify, renegotiate, extend, and terminate a contract made by or on behalf of the principal with respect to the entity or business before execution of the power of attorney;

.. Determine:

... The location of its operation;

... The nature and extent of its business;

... The methods of manufacturing, selling, merchandising, financing, accounting, and advertising employed in its operation;

... The amount and types of insurance carried; and

.. The mode of engaging, compensating, and dealing with its employees and accountants, attorneys, or other advisors;

.. Change the name or form of organization under which the entity or business is operated and enter into an ownership agreement with other persons to take over all or part of the operation of the entity or business; and

.. Demand and receive money due or claimed by the principal or on the principal's behalf in the operation of the entity or business and control and disburse the money in the operation of the entity or business;

. Put additional capital into an entity or business in which the principal has an interest;

. Join in a plan of reorganization, consolidation, conversion, domestication, or merger of the entity or business;

. Sell or liquidate all or part of an entity or business;

. Establish through agreement or independent appraisal the value of an entity or business to which the principal is a party;

. Prepare, sign, file, and deliver reports, compilations of information, returns, or other papers with respect to an entity or business and make related payments; and

. Pay, compromise, or contest taxes, assessments, fines, or penalties and perform any other act to protect the principal from illegal or unnecessary taxation, assessments, fines, or penalties, with respect to an entity or business, including attempts to recover, in any manner permitted by law, money paid before or after the execution of the power of attorney.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20208[2016 c 209 § 208]; ]

== 11.125.320 - Agent authority—Insurance and annuities.
Unless the power of attorney otherwise provides, language in a power of attorney granting general authority with respect to insurance and annuities authorizes the agent to:

. Continue, pay the premium or make a contribution on, modify, exchange, sell, rescind, release, or terminate a contract procured by or on behalf of the principal which insures or provides an annuity to either the principal or another person, whether or not the principal is a beneficiary under the contract;

. Procure new, different, and additional contracts of insurance and annuities for the benefit of the principal and the principal's spouse, state registered domestic partner, children, and other dependents, and select the amount, type of insurance or annuity, and mode of payment;

. Pay the premium or make a contribution on, modify, exchange, rescind, release, or terminate a contract of insurance or annuity procured by the agent;

. Apply for and receive a loan secured by a contract of insurance or annuity;

. Surrender and receive the cash surrender value on a contract of insurance or annuity;

. Exercise an election;

. Exercise investment powers available under a contract of insurance or annuity;

. Change the manner of paying premiums on a contract of insurance or annuity;

. Change or convert the type of insurance or annuity with respect to which the principal has or claims to have authority described in this section;

. Apply for and procure a benefit or assistance under a statute or regulation to guarantee or pay premiums of a contract of insurance on the life of the principal;

. Collect, sell, assign, hypothecate, borrow against, or pledge the interest of the principal in a contract of insurance or annuity;

. Select the form and timing of the payment of proceeds from a contract of insurance or annuity; and

. Pay, from proceeds or otherwise, compromise or contest, and apply for refunds in connection with, a tax or assessment levied by a taxing authority with respect to a contract of insurance or annuity or its proceeds or liability accruing by reason of the tax or assessment.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20209[2016 c 209 § 209]; ]

== 11.125.330 - Agent authority—Estates, trusts, and other beneficial interests.
. In this section, "estates, trusts, and other beneficial interests" means a trust, probate estate, guardianship, conservatorship, escrow, or custodianship or a fund from which the principal is, may become, or claims to be, entitled to a share or payment.

. Unless the power of attorney otherwise provides, language in a power of attorney granting general authority with respect to estates, trusts, and other beneficial interests authorizes the agent to:

.. Accept, receive, receipt for, sell, assign, pledge, or exchange a share in or payment from the fund;

.. Demand or obtain money or another thing of value to which the principal is, may become, or claims to be, entitled by reason of the fund, by litigation or otherwise;

.. Exercise for the benefit of the principal a presently exercisable general power of appointment held by the principal;

.. Exercise for the benefit of the principal a presently exercisable limited power of appointment held by the principal;

.. Initiate, participate in, submit to alternative dispute resolution, settle, oppose, or propose or accept a compromise with respect to litigation to ascertain the meaning, validity, or effect of a deed, will, declaration of trust, or other instrument or transaction affecting the interest of the principal;

.. Initiate, participate in, submit to alternative dispute resolution, settle, oppose, or propose or accept a compromise with respect to litigation to remove, substitute, or surcharge a fiduciary, and any other matter as defined under RCW 11.96A.030;

.. Conserve, invest, disburse, or use anything received for an authorized purpose;

.. Transfer an interest of the principal in real property, stocks, bonds, and financial instruments, accounts with financial institutions or securities intermediaries, insurance, annuities, and other property to the trustee of a revocable trust created by the principal as settlor, subject to the limitations in RCW 11.125.240(1); and

.. Reject, renounce, disclaim, release, or consent to a reduction in or modification of a share in or payment from the fund.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20210[2016 c 209 § 210]; ]

== 11.125.340 - Agent authority—Claims and litigation.
Unless the power of attorney otherwise provides, language in a power of attorney granting general authority with respect to claims and litigation authorizes the agent, without the need for appointment of a guardian or guardian ad litem under Title 4 RCW, to:

. Assert and maintain before a court or administrative agency a claim, claim for relief, cause of action, counterclaim, offset, recoupment, or defense, including an action to recover property or other thing of value, recover damages sustained by the principal, eliminate or modify tax liability, or seek an injunction, specific performance, or other relief;

. Bring or defend an action to determine adverse claims or intervene or otherwise participate in litigation;

. Seek an attachment, garnishment, order of arrest, or other preliminary, provisional, or intermediate relief and use an available procedure to effect or satisfy a judgment, order, or decree;

. Make or accept a tender, offer of judgment, or admission of facts, submit a controversy on an agreed statement of facts, consent to examination, and bind the principal in litigation;

. Submit to alternative dispute resolution, settle, and propose or accept a compromise, subject to special proceeding rule 98.16W;

. Waive the issuance and service of process upon the principal, accept service of process, appear for the principal, designate persons upon which process directed to the principal may be served, execute, and file or deliver stipulations on the principal's behalf, verify pleadings, seek appellate review, procure and give surety and indemnity bonds, contract and pay for the preparation and printing of records and briefs, receive, execute, and file or deliver a consent, waiver, release, confession of judgment, satisfaction of judgment, notice, agreement, or other instrument in connection with the prosecution, settlement, or defense of a claim or litigation;

. Act for the principal with respect to bankruptcy or insolvency, whether voluntary or involuntary, concerning the principal or some other person, or with respect to a reorganization, receivership, or application for the appointment of a receiver or trustee which affects an interest of the principal in property or other thing of value;

. Pay a judgment, award, or order against the principal or a settlement made in connection with a claim or litigation; and

. Receive money or other thing of value paid in settlement of or as proceeds of a claim or litigation.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20211[2016 c 209 § 211]; ]

== 11.125.350 - Agent authority—Personal and family maintenance.
. Unless the power of attorney otherwise provides, language in a power of attorney granting general authority with respect to personal and family maintenance authorizes the agent to:

.. Perform the acts necessary to maintain the customary standard of living of the principal, the principal's spouse or state registered domestic partner, and the following individuals, whether living when the power of attorney is executed or later born:

... The principal's children;

... Other individuals legally entitled to be supported by the principal; and

... The individuals whom the principal has customarily supported or indicated the intent to support;

.. Make periodic payments of child support and other family maintenance required by a court or governmental agency or an agreement to which the principal is a party;

.. Provide living quarters for the individuals described in subsection (1) of this section by:

... Purchase, lease, or other contract; or

... Paying the operating costs, including interest, amortization payments, repairs, improvements, and taxes, for premises owned by the principal or occupied by those individuals;

.. Provide reasonable domestic help, usual vacations and travel expenses, and funds for shelter, clothing, food, appropriate education, including postsecondary and vocational education, and other current living costs for the individuals described in subsection (1) of this section;

.. Pay expenses for necessary health care and custodial care on behalf of the individuals described in subsection (1) of this section;

.. Act as the principal's personal representative pursuant to the health insurance portability and accountability act, sections 1171 through 1179 of the social security act, 42 U.S.C. Sec. 1320d, as amended, and applicable regulations, for the limited purpose of making decisions regarding the payment of costs and expenses arising from past, present, or future health care provided to the principal which was consented to by the principal or anyone authorized under the law of this state to consent to health care on behalf of the principal;

.. Continue any provision made by the principal for automobiles or other means of transportation, including registering, licensing, insuring, and replacing them, for the individuals described in subsection (1) of this section;

.. Maintain credit and debit accounts for the convenience of the individuals described in subsection (1) of this section and open new accounts; and

.. Continue payments incidental to the membership or affiliation of the principal in a religious institution, club, society, order, or other organization or to continue contributions to those organizations.

. Authority with respect to personal and family maintenance is neither dependent upon, nor limited by, authority that an agent may or may not have with respect to gifts under chapter 209, Laws of 2016.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20212[2016 c 209 § 212]; ]

== 11.125.360 - Agent authority—Government program and civil and military service benefits.
. In this section, "benefits from governmental programs or civil or military service" means any benefit, program or assistance provided under a statute or regulation including social security, medicare, and medicaid.

. Unless the power of attorney otherwise provides, language in a power of attorney granting general authority with respect to benefits from governmental programs or civil or military service authorizes the agent to:

.. Execute vouchers in the name of the principal for allowances and reimbursements payable by the United States or a foreign government or by a state or subdivision of a state to the principal, including allowances and reimbursements for transportation of the individuals described in RCW 11.125.350(1)(a), and for shipment of their household effects;

.. Take possession and order the removal and shipment of property of the principal from a post, warehouse, depot, dock, or other place of storage or safekeeping, either governmental or private, and execute and deliver a release, voucher, receipt, bill of lading, shipping ticket, certificate, or other instrument for that purpose;

.. Enroll in, apply for, select, reject, change, amend, or discontinue, on the principal's behalf, a benefit or program;

.. Prepare, file, and maintain a claim of the principal for a benefit or assistance, financial or otherwise, to which the principal may be entitled under a statute or regulation;

.. Initiate, participate in, submit to alternative dispute resolution, settle, oppose, or propose or accept a compromise with respect to litigation concerning any benefit or assistance the principal may be entitled to receive under a statute or regulation; and

.. Receive the financial proceeds of a claim described in (d) of this subsection and conserve, invest, disburse, or use for a lawful purpose anything so received.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20213[2016 c 209 § 213]; ]

== 11.125.370 - Agent authority—Retirement benefits and deferred compensation.
. In this section, "retirement plan" means a plan or account created by an employer, the principal, or another individual to provide retirement benefits or deferred compensation of which the principal is a participant, beneficiary, or owner, including but not limited to a plan or account under the following sections of the internal revenue code:

.. An individual retirement account under internal revenue code section 408, 26 U.S.C. Sec. 408, as amended;

.. A roth individual retirement account under internal revenue code section 408A, 26 U.S.C. Sec. 408A, as amended;

.. A deemed individual retirement account under internal revenue code section 408(q), 26 U.S.C. Sec. 408(q), as amended;

.. An annuity or mutual fund custodial account under internal revenue code section 403(b), 26 U.S.C. Sec. 403(b), as amended;

.. A pension, profit-sharing, stock bonus, or other retirement plan qualified under internal revenue code section 401(a), 26 U.S.C. Sec. 401(a), as amended;

.. A plan under internal revenue code section 457(b), 26 U.S.C. Sec. 457(b), as amended; and

.. A nonqualified deferred compensation plan under internal revenue code section 409A, 26 U.S.C. Sec. 409A, as amended.

. Unless the power of attorney otherwise provides, language in a power of attorney granting general authority with respect to retirement plans authorizes the agent to:

.. Select the form and timing of payments under a retirement plan and withdraw benefits from a plan;

.. Make a rollover, including a direct trustee-to-trustee rollover, of benefits from one retirement plan to another;

.. Establish a retirement plan in the principal's name;

.. Make contributions to a retirement plan;

.. Exercise investment powers available under a retirement plan; and

.. Borrow from, sell assets to, or purchase assets from a retirement plan.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20214[2016 c 209 § 214]; ]

== 11.125.380 - Agent authority—Taxes.
Unless the power of attorney otherwise provides, language in a power of attorney granting general authority with respect to taxes authorizes the agent to:

. Prepare, sign, and file federal, state, local, and foreign income, gift, payroll, property, federal insurance contributions act, and other tax returns, claims for refunds, requests for extension of time, petitions regarding tax matters, and any other tax-related documents, including receipts, offers, waivers, consents, including consents and agreements under internal revenue code section 2032A, 26 U.S.C. Sec. 2032A, as amended, closing agreements, and any power of attorney required by the internal revenue service or other taxing authority including, but not limited to, an internal revenue service form 2848 in favor of any third party with respect to a tax year upon which the statute of limitations has not run and the following twenty-five tax years;

. Pay taxes due, collect refunds, post bonds, receive confidential information, and contest deficiencies determined by the internal revenue service or other taxing authority;

. Exercise any election available to the principal under federal, state, local, or foreign tax law; and

. Act for the principal in all tax matters for all periods before the internal revenue service, or other taxing authority.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20215[2016 c 209 § 215]; ]

== 11.125.390 - Agent authority—Gifts.
. In this section, a gift "for the benefit of" a person includes but is not limited to a gift to a trust, an account under the uniform transfers to minors act of any jurisdiction, and a tuition savings account or prepaid tuition plan as defined under internal revenue code section 529, 26 U.S.C. Sec. 529, as amended. Notwithstanding the terms of RCW 11.125.240(1)(a), the power to make a gift pursuant to RCW 11.125.240(1)(b) shall include the power to create a trust, an account under the uniform transfers to minors act, or a tuition savings account or prepaid tuition plan as defined under internal revenue code section 529, 26 U.S.C. Sec. 529, as amended, into which a gift is to be made.

. Unless the power of attorney otherwise provides, language in a power of attorney granting general authority with respect to gifts authorizes the agent only to:

.. Make outright to, or for the benefit of, a person, a gift of any of the principal's property, including by the exercise of a presently exercisable general power of appointment held by the principal, in an amount per donee not to exceed the annual dollar limits of the federal gift tax exclusion under internal revenue code section 2503(b), 26 U.S.C. Sec. 2503(b), as amended, without regard to whether the federal gift tax exclusion applies to the gift, or if the principal's spouse agrees to consent to a split gift pursuant to internal revenue code section 2513, 26 U.S.C. Sec. 2513, as amended, in an amount per donee not to exceed twice the annual federal gift tax exclusion limit; and

.. Consent, pursuant to internal revenue code section 2513, 26 U.S.C. Sec. 2513, as amended, to the splitting of a gift made by the principal's spouse in an amount per donee not to exceed the aggregate annual gift tax exclusions for both spouses.

. An agent may make a gift outright to, or for the benefit of, a person of the principal's property only as the agent determines is consistent with the principal's objectives if actually known by the agent and, if unknown, as the agent determines is consistent with the principal's best interest based on all relevant factors, including but not limited to:

.. The value and nature of the principal's property;

.. The principal's foreseeable obligations and need for maintenance;

.. Minimization of taxes, including income, estate, inheritance, generation-skipping transfer, and gift taxes;

.. Eligibility for a benefit, a program, or assistance under a statute or rule; and

.. The principal's personal history of making or joining in making gifts.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20216[2016 c 209 § 216]; ]

== 11.125.400 - Agent authority—Health care. (Effective until January 1, 2022.)
Unless the power of attorney otherwise provides, where language in a power of attorney grants general authority with respect to health care matters:

. The agent shall be authorized to act as the principal's personal representative pursuant to the health insurance portability and accountability act, sections 1171 through 1179 of the social security act, 42 U.S.C. Sec. 1320d, as amended, and applicable regulations for all purposes thereunder, including but not limited to accessing and acquiring the principal's health care related information.

. The agent shall be authorized to provide informed consent for health care decisions on the principal's behalf. If a principal has appointed more than one agent with authority to make mental health treatment decisions in accordance with a directive under chapter 71.32 RCW, to the extent of any conflict, the most recently appointed agent shall be treated as the principal's agent for mental health treatment decisions unless provided otherwise in either appointment.

. Unless he or she is the spouse, state registered domestic partner, father or mother, or adult child or brother or sister of the principal, none of the following persons may act as the agent for the principal: Any of the principal's physicians, the physicians' employees, or the owners, administrators, or employees of the health care facility or long-term care facility as defined in RCW 43.190.020 where the principal resides or receives care. Except when the principal has consented in a mental health advance directive executed under chapter 71.32 RCW to inpatient admission or electroconvulsive therapy, this authorization is subject to the same limitations as those that apply to a guardian under *RCW 11.92.043(5) (a) through (c) and 11.92.190.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20217[2016 c 209 § 217]; ]

== 11.125.410 - Agent authority—Principal's minor children. (Effective until January 1, 2022.)
Unless the power of attorney otherwise provides, the following general provisions shall apply to any power of attorney making reference to the care of the principal's minor children:

. A parent or guardian, through a power of attorney, may authorize an agent to make health care decisions on behalf of one or more of his or her children, or children for whom he or she is the legal guardian, who are under the age of majority as defined in RCW 26.28.015, to be effective if the child has no other parent or legal representative readily available and authorized to give such consent.

. A principal may further nominate a guardian or guardians of the person, or of the estate or both, of a minor child, whether born at the time of making the durable power of attorney or afterwards, to continue during the disability of the principal, during the minority of the child or for any less time by including such a provision in his or her power of attorney.

. The authority of any guardian of the person of any minor child shall supersede the authority of a designated agent to make health care decisions for the minor only after such designated guardian has been appointed by the court.

. In the event a conflict between the provisions of a will nominating a testamentary guardian under the authority of *RCW 11.88.080 and the nomination of a guardian under the authority of this statute, the most recent designation shall control.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20218[2016 c 209 § 218]; ]

== 11.125.420 - Death with dignity act.
Notwithstanding any provision in chapter 209, Laws of 2016, or any provision in a power of attorney, no rights under Washington's death with dignity act, chapter 70.245 RCW, may be exercised through a power of attorney.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20219[2016 c 209 § 219]; ]

== 11.125.430 - Agent's certification form—Power of attorney and agent authority validity.
The following optional form may be used by an agent to certify facts concerning a power of attorney.

AGENT'S CERTIFICATION AS TO THE VALIDITY OF POWER OF ATTORNEYAND AGENT'S AUTHORITYState of _____ [County] of _____] I, (Name of Agent), [certify] under penalty of perjurythat (Name of Principal) granted me authority as an agent or successoragent in a power of attorney dated .I further [certify] that to my knowledge:(1) I am acting in good faith pursuant to the authority given under the power of attorney;(2) The principal is alive and has not terminated, revoked, limited, or modified the power of attorney or my authority to act under the power of attorney; nor has the power of attorney or my authority to act under the power of attorney been terminated, revoked, limited, or modified by any other circumstances;(3) When the power of attorney was signed, the principal was competent to execute it and was not under undue influence to sign;(4) All events necessary to making the power of attorney effective have occurred;(5) If I was married or a registered domestic partner of the principal when the power of attorney was executed, there has been no subsequent dissolution, annulment, or legal separation, and no action is pending for the dissolution of the marriage or domestic partnership or for legal separation;(6) If the power of attorney was drafted to become effective upon the happening of an event or contingency, the event or contingency has occurred;(7) If I was named as a successor agent, the prior agent is no longer able or willing to serve, or the conditions stated in the power of attorney that cause me to become the acting agent have occurred; and(8) ____________________(Insert other relevant statements)SIGNATURE AND ACKNOWLEDGMENT_____Agent's Signature_____Date_____Agent's Name Printed __________Agent's Address _____Agent's Telephone Number This document was acknowledged before me on _____,      (Date)by _____        (Name of Agent)_____Signature of Notary(Seal, if any)My commission expires: _____[This document prepared by:_____]

AGENT'S CERTIFICATION AS TO THE VALIDITY OF POWER OF ATTORNEY

AND AGENT'S AUTHORITY

State of _____

 

[County] of _____]

 

I, (Name of Agent), [certify] under penalty of perjury

that (Name of Principal) granted me authority as an agent or successor

agent in a power of attorney dated .

I further [certify] that to my knowledge:

. I am acting in good faith pursuant to the authority given under the power of attorney;

. The principal is alive and has not terminated, revoked, limited, or modified the power of attorney or my authority to act under the power of attorney; nor has the power of attorney or my authority to act under the power of attorney been terminated, revoked, limited, or modified by any other circumstances;

. When the power of attorney was signed, the principal was competent to execute it and was not under undue influence to sign;

. All events necessary to making the power of attorney effective have occurred;

. If I was married or a registered domestic partner of the principal when the power of attorney was executed, there has been no subsequent dissolution, annulment, or legal separation, and no action is pending for the dissolution of the marriage or domestic partnership or for legal separation;

. If the power of attorney was drafted to become effective upon the happening of an event or contingency, the event or contingency has occurred;

. If I was named as a successor agent, the prior agent is no longer able or willing to serve, or the conditions stated in the power of attorney that cause me to become the acting agent have occurred; and

. _____

_____

_____

_____

(Insert other relevant statements)

SIGNATURE AND ACKNOWLEDGMENT

_____

Agent's Signature

_____

Date

_____

Agent's Name Printed

 

_____

_____

Agent's Address

 

_____

Agent's Telephone Number

 

This document was acknowledged before me on _____,

 

     (Date)

by _____

        (Name of Agent)

_____

Signature of Notary

(Seal, if any)

My commission expires: _____

[This document prepared by:

_____]

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20301[2016 c 209 § 301]; ]

== 11.125.900 - Application—Uniformity—2016 c 209.
In applying and construing this uniform act, consideration must be given to the need to promote uniformity of the law with respect to its subject matter among the states that enact it.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20501[2016 c 209 § 501]; ]

== 11.125.901 - Federal law application—Federal electronic signatures in global and national commerce act—2016 c 209.
Chapter 209, Laws of 2016 modifies, limits, and supersedes the federal electronic signatures in global and national commerce act, 15 U.S.C. Sec. 7001 et seq., but does not modify, limit, or supersede section 101(c) of that act, 15 U.S.C. Sec. 7001(c), or authorize electronic delivery of any of the notices described in section 103(b) of that act, 15 U.S.C. Sec. 7003(b).

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20502[2016 c 209 § 502]; ]

== 11.125.902 - Application—Dates—2016 c 209.
Except as otherwise provided in chapter 209, Laws of 2016, on January 1, 2017:

. Chapter 209, Laws of 2016 applies to a power of attorney created before, on, or after January 1, 2017;

. Chapter 209, Laws of 2016 applies to a judicial proceeding concerning a power of attorney commenced on or after January 1, 2017;

. Chapter 209, Laws of 2016 applies to a judicial proceeding concerning a power of attorney commenced before January 1, 2017, unless the court finds that application of a provision of chapter 209, Laws of 2016 would substantially interfere with the effective conduct of the judicial proceeding or prejudice the rights of a party, in which case that provision does not apply and the superseded law applies; and

. An act done before January 1, 2017, is not affected by chapter 209, Laws of 2016.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20503[2016 c 209 § 503]; ]

== 11.125.903 - Effective date—2016 c 209.
This act takes effect January 1, 2017.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20506[2016 c 209 § 506]; ]

