= 11.106 - Trustees' accounting act.
:toc:

== 11.106.010 - Scope of chapter—Exceptions.
This chapter does not apply to resulting trusts, constructive trusts, business trusts where certificates of beneficial interest are issued to the beneficiaries, investment trusts, voting trusts, insurance trusts prior to the death of the insured, trusts in the nature of mortgages or pledges, liquidation trusts or trusts for the sole purpose of paying dividends, interest or interest coupons, salaries, wages or pensions; nor does this chapter apply to personal representatives.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5344.SL.pdf?cite=2013%20c%20272%20§%2025[2013 c 272 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c30.pdf?cite=1985%20c%2030%20§%2095[1985 c 30 § 95]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c149.pdf?cite=1984%20c%20149%20§%20128[1984 c 149 § 128]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.30.010[1955 c 33 § 30.30.010]; prior:  1951 c 226 § 10; ]

== 11.106.020 - Trustee's annual statement.
The trustee or trustees appointed by any will, deed, or agreement executed must mail or deliver at least annually to each permissible distributee, as defined in RCW 11.98.002, a written itemized statement of all current receipts and disbursements made by the trustee of the funds of the trust both principal and income, and upon the request of any such beneficiary must furnish the beneficiary an itemized statement of all property then held by that trustee, and may also file any such statement in the superior court of the county in which the trustee or one of the trustees resides.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5344.SL.pdf?cite=2013%20c%20272%20§%2026[2013 c 272 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c30.pdf?cite=1985%20c%2030%20§%2096[1985 c 30 § 96]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c149.pdf?cite=1984%20c%20149%20§%20129[1984 c 149 § 129]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.30.020[1955 c 33 § 30.30.020]; prior:  1951 c 226 § 2; ]

== 11.106.030 - Intermediate and final accounts—Contents—Filing.
In addition to the statement required by RCW 11.106.020 any such trustee or trustees whenever it or they so desire, may file in the superior court of the county in which the trustees or one of the trustees resides an intermediate account under oath showing:

. The period covered by the account;

. The total principal with which the trustee is chargeable according to the last preceding account or the inventory if there is no preceding account;

. An itemized statement of all principal funds received and disbursed during such period;

. An itemized statement of all income received and disbursed during such period, unless waived;

. The balance of such principal and income remaining at the close of such period and how invested;

. The names and addresses of all living beneficiaries, including contingent beneficiaries, of the trust, and a statement as to any such beneficiary known to be under legal disability;

. A description of any possible unborn or unascertained beneficiary and his or her interest in the trust fund.

After the time for termination of the trust has arrived, the trustee or trustees may also file a final account in similar manner.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%202092[2010 c 8 § 2092]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c30.pdf?cite=1985%20c%2030%20§%2097[1985 c 30 § 97]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c149.pdf?cite=1984%20c%20149%20§%20130[1984 c 149 § 130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.30.030[1955 c 33 § 30.30.030]; prior:  1951 c 226 § 3; ]

== 11.106.040 - Petition for statement of account.
At any time after the later of one year from the inception of the trust or one year after the day on which a report was last filed, any settlor or beneficiary of a trust may file a petition under RCW 11.96A.080 with the superior court in the county where the trustee or one of the trustees resides asking the court to direct the trustee or trustees to file in the court an account. At the hearing on such petition the court may order the trustee to file an account for good cause shown.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20627[1999 c 42 § 627]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c30.pdf?cite=1985%20c%2030%20§%2098[1985 c 30 § 98]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c149.pdf?cite=1984%20c%20149%20§%20131[1984 c 149 § 131]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.30.040[1955 c 33 § 30.30.040]; prior:  1951 c 226 § 4; ]

== 11.106.050 - Account filed—Return day—Notice.
When any account has been filed pursuant to RCW 11.106.030 or 11.106.040, the clerk of the court where filed shall fix a return day therefor as provided in RCW 11.96A.100(4) and issue a notice. The notice shall state the time and place for the return date, the name or names of the trustee or trustees who have filed the account, that the account has been filed, that the court is asked to settle the account, and that any objections or exceptions to the account must be filed with the clerk of the court on or before the return date. The notice shall be given as provided for notices under RCW 11.96A.110.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20628[1999 c 42 § 628]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c30.pdf?cite=1985%20c%2030%20§%2099[1985 c 30 § 99]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c149.pdf?cite=1984%20c%20149%20§%20132[1984 c 149 § 132]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.30.050[1955 c 33 § 30.30.050]; prior:  1951 c 226 § 5; ]

== 11.106.060 - Account filed—Objections—Appointment of guardians ad litem—Representatives.
Upon or before the return date any beneficiary of the trust may file the beneficiary's written objections or exceptions to the account filed or to any action of the trustee or trustees set forth in the account. The court shall appoint guardians ad litem as provided in RCW 11.96A.160 and the court may allow representatives to be appointed under RCW 11.96A.120 or 11.96A.250 to represent the persons listed in those sections.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20629[1999 c 42 § 629]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c30.pdf?cite=1985%20c%2030%20§%20100[1985 c 30 § 100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c149.pdf?cite=1984%20c%20149%20§%20133[1984 c 149 § 133]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c80.pdf?cite=1977%20ex.s.%20c%2080%20§%2031[1977 ex.s. c 80 § 31]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.30.060[1955 c 33 § 30.30.060]; prior:  1951 c 226 § 6; ]

== 11.106.070 - Court to determine accuracy, validity—Decree.
Upon the return date or at some later date fixed by the court if so requested by one or more of the parties, the court without the intervention of a jury and after hearing all the evidence submitted shall determine the correctness of the account and the validity and propriety of all actions of the trustee or trustees set forth in the account including the purchase, retention, and disposition of any of the property and funds of the trust, and shall render its decree either approving or disapproving the account or any part of it, and surcharging the trustee or trustees for all losses, if any, caused by negligent or wilful breaches of trust.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c30.pdf?cite=1985%20c%2030%20§%20101[1985 c 30 § 101]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c149.pdf?cite=1984%20c%20149%20§%20134[1984 c 149 § 134]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.30.070[1955 c 33 § 30.30.070]; prior:  1951 c 226 § 7; ]

== 11.106.080 - Effect of decree.
The decree rendered under RCW 11.106.070 shall be deemed final, conclusive, and binding upon all the parties interested including all incompetent, unborn, and unascertained beneficiaries of the trust subject only to the right of appeal under RCW 11.106.090.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c30.pdf?cite=1985%20c%2030%20§%20102[1985 c 30 § 102]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c149.pdf?cite=1984%20c%20149%20§%20135[1984 c 149 § 135]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.30.080[1955 c 33 § 30.30.080]; prior:  1951 c 226 § 8; ]

== 11.106.090 - Appeal from decree.
The decree rendered under RCW 11.106.070 shall be a final order from which any party in interest may appeal as in civil actions to the supreme court or the court of appeals of the state of Washington.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c30.pdf?cite=1985%20c%2030%20§%20103[1985 c 30 § 103]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c149.pdf?cite=1984%20c%20149%20§%20136[1984 c 149 § 136]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971c81.pdf?cite=1971%20c%2081%20§%2080[1971 c 81 § 80]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.30.090[1955 c 33 § 30.30.090]; prior:  1951 c 226 § 9; ]

== 11.106.100 - Waiver of accounting by beneficiary.
Any adult beneficiary entitled to an accounting under either RCW 11.106.020 or 11.106.030 may waive such an accounting by a separate instrument delivered to the trustee.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c30.pdf?cite=1985%20c%2030%20§%20104[1985 c 30 § 104]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c149.pdf?cite=1984%20c%20149%20§%20137[1984 c 149 § 137]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.30.100[1955 c 33 § 30.30.100]; prior:  1951 c 226 § 11; ]

== 11.106.110 - Modification under chapter  11.97 RCW—How constituted.
This chapter is declared to be of similar import to the uniform trustees' accounting act. Any modification under chapter 11.97 RCW, including waiver, of the requirements of this chapter in any will, deed, or agreement heretofore or hereafter executed shall be given effect whether the waiver refers to the uniform trustees' accounting act by name or other reference or to any other act of like or similar import.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c30.pdf?cite=1985%20c%2030%20§%20105[1985 c 30 § 105]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c149.pdf?cite=1984%20c%20149%20§%20138[1984 c 149 § 138]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.30.110[1955 c 33 § 30.30.110]; prior:  1951 c 226 § 12; ]

