= 10.93 - Washington mutual aid peace officers powers act.
:toc:

== 10.93.001 - Short title—Legislative intent—Construction.
. This chapter may be known and cited as the Washington mutual aid peace officer powers act of 1985.

. It is the intent of the legislature that current artificial barriers to mutual aid and cooperative enforcement of the laws among general authority local, state, and federal agencies be modified pursuant to this chapter.

. This chapter shall be liberally construed to effectuate the intent of the legislature to modify current restrictions upon the limited territorial and enforcement authority of general authority peace officers and to effectuate mutual aid among agencies.

. The modification of territorial and enforcement authority of the various categories of peace officers covered by this chapter shall not create a duty to act in extraterritorial situations beyond any duty which may otherwise be imposed by law or which may be imposed by the primary commissioning agency.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c89.pdf?cite=1985%20c%2089%20§%201[1985 c 89 § 1]; ]

== 10.93.020 - Definitions.
As used in this chapter, the following terms have the meanings indicated unless the context clearly requires otherwise.

. "General authority Washington law enforcement agency" means any agency, department, or division of a municipal corporation, political subdivision, or other unit of local government of this state, and any agency, department, or division of state government, having as its primary function the detection and apprehension of persons committing infractions or violating the traffic or criminal laws in general, as distinguished from a limited authority Washington law enforcement agency, and any other unit of government expressly designated by statute as a general authority Washington law enforcement agency. The Washington state patrol and the department of fish and wildlife are general authority Washington law enforcement agencies.

. "Limited authority Washington law enforcement agency" means any agency, political subdivision, or unit of local government of this state, and any agency, department, or division of state government, having as one of its functions the apprehension or detection of persons committing infractions or violating the traffic or criminal laws relating to limited subject areas, including but not limited to, the state departments of natural resources and social and health services, the state gambling commission, the state lottery commission, the state parks and recreation commission, the state utilities and transportation commission, the *state liquor control board, the office of the insurance commissioner, and the state department of corrections.

. "General authority Washington peace officer" means any full-time, fully compensated and elected, appointed, or employed officer of a general authority Washington law enforcement agency who is commissioned to enforce the criminal laws of the state of Washington generally.

. "Limited authority Washington peace officer" means any full-time, fully compensated officer of a limited authority Washington law enforcement agency empowered by that agency to detect or apprehend violators of the laws in some or all of the limited subject areas for which that agency is responsible. A limited authority Washington peace officer may be a specially commissioned Washington peace officer if otherwise qualified for such status under this chapter.

. "Specially commissioned Washington peace officer", for the purposes of this chapter, means any officer, whether part-time or full-time, compensated or not, commissioned by a general authority Washington law enforcement agency to enforce some or all of the criminal laws of the state of Washington, who does not qualify under this chapter as a general authority Washington peace officer for that commissioning agency, specifically including reserve peace officers, and specially commissioned full-time, fully compensated peace officers duly commissioned by the states of Oregon or Idaho or any such peace officer commissioned by a unit of local government of Oregon or Idaho. A reserve peace officer is an individual who is an officer of a Washington law enforcement agency who does not serve such agency on a full-time basis but who, when called by the agency into active service, is fully commissioned on the same basis as full-time peace officers to enforce the criminal laws of the state.

. "Federal peace officer" means any employee or agent of the United States government who has the authority to carry firearms and make warrantless arrests and whose duties involve the enforcement of criminal laws of the United States.

. "Agency with primary territorial jurisdiction" means a city or town police agency which has responsibility for police activity within its boundaries; or a county police or sheriff's department which has responsibility with regard to police activity in the unincorporated areas within the county boundaries; or a statutorily authorized port district police agency or four-year state college or university police agency which has responsibility for police activity within the statutorily authorized enforcement boundaries of the port district, state college, or university.

. "Primary commissioning agency" means (a) the employing agency in the case of a general authority Washington peace officer, a limited authority Washington peace officer, an Indian tribal peace officer, or a federal peace officer, and (b) the commissioning agency in the case of a specially commissioned Washington peace officer (i) who is performing functions within the course and scope of the special commission and (ii) who is not also a general authority Washington peace officer, a limited authority Washington peace officer, an Indian tribal peace officer, or a federal peace officer.

. "Primary function of an agency" means that function to which greater than fifty percent of the agency's resources are allocated.

. "Mutual law enforcement assistance" includes, but is not limited to, one or more law enforcement agencies aiding or assisting one or more other such agencies through loans or exchanges of personnel or of material resources, for law enforcement purposes.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6234-S.SL.pdf?cite=2006%20c%20284%20§%2016[2006 c 284 § 16]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6076-S.SL.pdf?cite=2002%20c%20128%20§%201[2002 c 128 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2590.SL.pdf?cite=1994%20c%20264%20§%203[1994 c 264 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c36.pdf?cite=1988%20c%2036%20§%205[1988 c 36 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c89.pdf?cite=1985%20c%2089%20§%202[1985 c 89 § 2]; ]

== 10.93.030 - Reporting use of authority under this chapter.
The circumstances surrounding any actual exercise of peace officer authority under this chapter shall be timely reported, after the fact, to the Washington law enforcement agency with primary territorial jurisdiction and shall be subject to any reasonable reporting procedure which may be established by such agency.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c89.pdf?cite=1985%20c%2089%20§%203[1985 c 89 § 3]; ]

== 10.93.040 - Liability for exercise of authority.
Any liability or claim of liability which arises out of the exercise or alleged exercise of authority by an officer acting within the course and scope of the officer's duties as a peace officer under this chapter is the responsibility of the primary commissioning agency unless the officer acts under the direction and control of another agency or unless the liability is otherwise allocated under a written agreement between the primary commissioning agency and another agency.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c89.pdf?cite=1985%20c%2089%20§%204[1985 c 89 § 4]; ]

== 10.93.050 - Supervisory control over peace officers.
All persons exercising peace officer powers under this chapter are subject to supervisory control of and limitations imposed by the primary commissioning agency, but the primary commissioning agency may, by agreement with another agency, temporarily delegate supervision over the peace officer to another agency.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c89.pdf?cite=1985%20c%2089%20§%205[1985 c 89 § 5]; ]

== 10.93.060 - Privileges and immunities applicable.
All of the privileges and immunities from liability, exemption from laws, ordinances, and rules, all pension, relief, disability, worker's compensation insurance, and other benefits which apply to the activity of officers, agents, or employees of any law enforcement agency when performing their respective functions within the territorial limits of their respective agencies shall apply to them and to their primary commissioning agencies to the same degree and extent while such persons are engaged in the performance of authorized functions and duties under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c89.pdf?cite=1985%20c%2089%20§%206[1985 c 89 § 6]; ]

== 10.93.070 - General authority peace officer—Powers of, circumstances.
In addition to any other powers vested by law, a general authority Washington peace officer who possesses a certificate of basic law enforcement training or a certificate of equivalency or has been exempted from the requirement therefor by the Washington state criminal justice training commission may enforce the traffic or criminal laws of this state throughout the territorial bounds of this state, under the following enumerated circumstances:

. Upon the prior written consent of the sheriff or chief of police in whose primary territorial jurisdiction the exercise of the powers occurs;

. In response to an emergency involving an immediate threat to human life or property;

. In response to a request for assistance pursuant to a mutual law enforcement assistance agreement with the agency of primary territorial jurisdiction or in response to the request of a peace officer with enforcement authority;

. When the officer is transporting a prisoner;

. When the officer is executing an arrest warrant or search warrant; or

. When the officer is in fresh pursuit, as defined in RCW 10.93.120.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c89.pdf?cite=1985%20c%2089%20§%207[1985 c 89 § 7]; ]

== 10.93.080 - Limited authority peace officer—No additional powers.
A limited authority Washington peace officer shall have no additional powers by virtue of this chapter but shall be limited to those powers already vested by law or hereafter created by separate enactment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c89.pdf?cite=1985%20c%2089%20§%208[1985 c 89 § 8]; ]

== 10.93.090 - Specially commissioned peace officer—Powers of, circumstances.
A specially commissioned Washington peace officer who has successfully completed a course of basic training prescribed or approved for such officers by the Washington state criminal justice training commission may exercise any authority which the special commission vests in the officer, throughout the territorial bounds of the state, outside of the officer's primary territorial jurisdiction under the following circumstances:

. The officer is in fresh pursuit, as defined in RCW 10.93.120; or

. The officer is acting pursuant to mutual law enforcement assistance agreement between the primary commissioning agency and the agency with primary territorial jurisdiction.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c89.pdf?cite=1985%20c%2089%20§%209[1985 c 89 § 9]; ]

== 10.93.100 - Federal peace officers—No additional powers.
Federal peace officers shall have no additional powers by virtue of this chapter but shall be limited to those powers already vested by law or hereafter created by separate enactment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c89.pdf?cite=1985%20c%2089%20§%2010[1985 c 89 § 10]; ]

== 10.93.110 - Attorney general—No additional powers.
The attorney general shall have no additional powers by virtue of this chapter but shall be limited to those powers already vested by law or hereafter created by separate enactment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c89.pdf?cite=1985%20c%2089%20§%2011[1985 c 89 § 11]; ]

== 10.93.120 - Fresh pursuit, arrest.
. Any peace officer who has authority under Washington law to make an arrest may proceed in fresh pursuit of a person (a) who is reasonably believed to have committed a violation of traffic or criminal laws, or (b) for whom such officer holds a warrant of arrest, and such peace officer shall have the authority to arrest and to hold such person in custody anywhere in the state.

. The term "fresh pursuit," as used in this chapter, includes, without limitation, fresh pursuit as defined by the common law. Fresh pursuit does not necessarily imply immediate pursuit, but pursuit without unreasonable delay.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c89.pdf?cite=1985%20c%2089%20§%2012[1985 c 89 § 12]; ]

== 10.93.130 - Contracting authority of law enforcement agencies.
Under the interlocal cooperation act, chapter 39.34 RCW, any law enforcement agency referred to by this chapter may contract with any other such agency and may also contract with any law enforcement agency of another state, or such state's political subdivision, to provide mutual law enforcement assistance. The agency with primary territorial jurisdiction may require that officers from participating agencies meet reasonable training or certification standards or other reasonable standards.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c89.pdf?cite=1985%20c%2089%20§%2013[1985 c 89 § 13]; ]

== 10.93.140 - State patrol, fish and wildlife exempted.
This chapter does not limit the scope of jurisdiction and authority of the Washington state patrol and the department of fish and wildlife as otherwise provided by law, and these agencies shall not be bound by the reporting requirements of RCW 10.93.030.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6076-S.SL.pdf?cite=2002%20c%20128%20§%202[2002 c 128 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c89.pdf?cite=1985%20c%2089%20§%2014[1985 c 89 § 14]; ]

== 10.93.150 - Law enforcement disciplinary actions—Potential impeachment list.
A disciplinary action or any other adverse personnel action may not be undertaken by a law enforcement agency against a peace officer solely because that officer's name has been placed on a list maintained by a prosecuting attorney's office of recurring witnesses for whom there is known potential impeachment information, or that the officer's name may otherwise be subject to disclosure pursuant to Brady v. Maryland, 373 U.S. 83 (1963). This section does not prohibit a law enforcement agency from taking disciplinary action or any other adverse personnel action against a peace officer based on the underlying acts or omissions for which that officer's name was placed on a prosecutor-maintained list, or may otherwise be subject to disclosure pursuant to Brady v. Maryland, 373 U.S. 83 (1963), if the actions taken by the law enforcement agency otherwise conform to the rules and procedures adopted by the law enforcement agency as determined through collective bargaining.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6188.SL.pdf?cite=2018%20c%20265%20§%202[2018 c 265 § 2]; ]

== 10.93.160 - Immigration and citizenship status—Law enforcement agency restrictions.
. The definitions contained in RCW 43.17.420 apply to this section.

. The legislature finds that it is not the primary purpose of state and local law enforcement agencies or school resource officers to enforce civil federal immigration law. The legislature further finds that the immigration status of an individual or an individual's presence in, entry, or reentry to, or employment in the United States alone, is not a matter for police action, and that United States federal immigration authority has primary jurisdiction for enforcement of the provisions of Title 8 U.S.C. dealing with illegal entry.

. School resource officers, when acting in their official capacity as a school resource officer, may not:

.. Inquire into or collect information about an individual's immigration or citizenship status, or place of birth; or

.. Provide information pursuant to notification requests from federal immigration authorities for the purposes of civil immigration enforcement, except as required by law.

. State and local law enforcement agencies may not:

.. Inquire into or collect information about an individual's immigration or citizenship status, or place of birth unless there is a connection between such information and an investigation into a violation of state or local criminal law; or

.. Provide information pursuant to notification requests from federal immigration authorities for the purposes of civil immigration enforcement, except as required by law.

. State and local law enforcement agencies may not provide nonpublicly available personal information about an individual, including individuals subject to community custody pursuant to RCW 9.94A.701 and 9.94A.702, to federal immigration authorities in a noncriminal matter, except as required by state or federal law.

. [Empty]
.. State and local law enforcement agencies may not give federal immigration authorities access to interview individuals about a noncriminal matter while they are in custody, except as required by state or federal law, a court order, or by (b) of this subsection.

.. Permission may be granted to a federal immigration authority to conduct an interview regarding federal immigration violations with a person who is in the custody of a state or local law enforcement agency if the person consents in writing to be interviewed. In order to obtain consent, agency staff shall provide the person with an oral explanation and a written consent form that explains the purpose of the interview, that the interview is voluntary, and that the person may decline to be interviewed or may choose to be interviewed only with the person's attorney present. The form must state explicitly that the person will not be punished or suffer retaliation for declining to be interviewed. The form must be available at least in English and Spanish and explained orally to a person who is unable to read the form, using, when necessary, an interpreter from the district communications center "language line" or other district resources.

. An individual may not be detained solely for the purpose of determining immigration status.

. An individual must not be taken into custody, or held in custody, solely for the purposes of determining immigration status or based solely on a civil immigration warrant, or an immigration hold request.

. [Empty]
.. To ensure compliance with all treaty obligations, including consular notification, and state and federal laws, on the commitment or detainment of any individual, state and local law enforcement agencies must explain in writing:

... The individual's right to refuse to disclose their nationality, citizenship, or immigration status; and

... That disclosure of their nationality, citizenship, or immigration status may result in civil or criminal immigration enforcement, including removal from the United States.

.. Nothing in this subsection allows for any violation of subsection (4) of this section.

. A state and local government or law enforcement agency may not deny services, benefits, privileges, or opportunities to individuals in custody, or under community custody pursuant to RCW 9.94A.701 and 9.94A.702, or in probation status, on the basis of the presence of an immigration detainer, hold, notification request, or civil immigration warrant, except as required by law or as necessary for classification or placement purposes for individuals in the physical custody of the department of corrections.

. No state or local law enforcement officer may enter into any contract, agreement, or arrangement, whether written or oral, that would grant federal civil immigration enforcement authority or powers to state and local law enforcement officers, including but not limited to agreements created under 8 U.S.C. Sec. 1357(g), also known as 287(g) agreements.

. [Empty]
.. No state agency or local government or law enforcement officer may enter into an immigration detention agreement. All immigration detention agreements must be terminated no later than one hundred eighty days after May 21, 2019, except as provided in (b) of this subsection.

.. Any immigration detention agreement in effect prior to January 1, 2019, and under which a payment was made between July 1, 2017, and December 31, 2018, may remain in effect until the date of completion or December 31, 2021, whichever is earlier.

. No state or local law enforcement agency or school resource officer may enter into or renew a contract for the provision of language services from federal immigration authorities, nor may any language services be accepted from such for free or otherwise.

. The department of corrections may not give federal immigration authorities access to interview individuals about federal immigration violations while they are in custody, except as required by state or federal law or by court order, unless such individuals consent to be interviewed in writing. Before agreeing to be interviewed, individuals must be advised that they will not be punished or suffer retaliation for declining to be interviewed.

. Subsections (3) through (6) of this section do not apply to individuals who are in the physical custody of the department of corrections.

. Nothing in this section prohibits the collection, use, or disclosure of information that is:

.. Required to comply with state or federal law; or

.. In response to a lawfully issued court order.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5497-S2.SL.pdf?cite=2019%20c%20440%20§%206[2019 c 440 § 6]; ]

== 10.93.900 - Effective date—1985 c 89.
This act shall take effect July 1, 1985.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c89.pdf?cite=1985%20c%2089%20§%2017[1985 c 89 § 17]; ]

