= 10.66 - Drug traffickers—Off-limits orders.
:toc:

== 10.66.005 - Findings.
The legislature finds that drug abuse is escalating at an alarming rate. New protections need to be established to address this drug crisis which is threatening every stratum of our society. Prohibiting known drug traffickers from frequenting areas for continuous drug activity is one means of addressing this pervasive problem.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c271.pdf?cite=1989%20c%20271%20§%20213[1989 c 271 § 213]; ]

== 10.66.010 - Definitions. (Effective until July 1, 2022.)
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter:

. "Applicant" means any person who owns, occupies, or has a substantial interest in property, or who is a neighbor to property which is adversely affected by drug trafficking, including:

.. A "family or household member" or "intimate partner" as defined by RCW 26.50.010, who has a possessory interest in a residence as an owner or tenant, at least as great as a known drug trafficker's interest;

.. An owner or lessor;

.. An owner, tenant, or resident who lives or works in a designated PADT area; or

.. A city or prosecuting attorney for any jurisdiction in this state where drug trafficking is occurring.

. "Drug" or "drugs" means a controlled substance as defined in chapter 69.50 RCW or an "imitation controlled substance" as defined in RCW 69.52.020.

. "Known drug trafficker" means any person who has been convicted of a drug offense in this state, another state, or federal court who subsequently has been arrested for a drug offense in this state. For purposes of this definition, "drug offense" means a felony violation of chapter 69.50 or 69.52 RCW or equivalent law in another jurisdiction that involves the manufacture, distribution, or possession with intent to manufacture or distribute of a controlled substance or imitation controlled substance.

. "Off-limits orders" means an order issued by a superior or district court in the state of Washington that enjoins known drug traffickers from entering or remaining in a designated PADT area.

. "Protected against drug trafficking area" or "PADT area" means any specifically described area, public or private, contained in an off-limits order. The perimeters of a PADT area shall be defined using street names and numbers and shall include all real property contained therein, where drug sales, possession of drugs, pedestrian or vehicular traffic attendant to drug activity, or other activity associated with drug offenses confirms a pattern associated with drug trafficking. The area may include the full width of streets, alleys and sidewalks on the perimeter, common areas, planting strips, or parks and parking areas within the area described using the streets as boundaries.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2473-S.SL.pdf?cite=2020%20c%2029%20§%2011[2020 c 29 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c271.pdf?cite=1989%20c%20271%20§%20214[1989 c 271 § 214]; ]

== 10.66.020 - When order may be issued.
A court may enter an off-limits order enjoining a known drug trafficker who has been associated with drug trafficking in an area that the court finds to be a PADT area, from entering or remaining in a designated PADT area for up to one year. This relief may be ordered pursuant to applications for injunctive relief or as part of a criminal proceeding as follows:

. In a civil action, including an action brought under this chapter;

. In a nuisance abatement action pursuant to chapter 7.43 RCW;

. In an eviction action to exclude known drug traffickers or tenants who were evicted for allowing drug trafficking to occur on the premises which were the subject of the eviction action;

. As a condition of pretrial release of a known drug trafficker awaiting trial on drug charges. The order shall be in effect until the time of sentencing or dismissal of the criminal charges; or

. As a condition of sentencing of any known drug trafficker convicted of a drug offense. The order may include all periods of community placement or community supervision.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c271.pdf?cite=1989%20c%20271%20§%20215[1989 c 271 § 215]; ]

== 10.66.030 - Hearing—Summons.
Upon the filing of an application for an off-limits order under RCW 10.66.020 (1), (2), or (3), the court shall set a hearing fourteen days from the filing of the application, or as soon thereafter as the hearing can be scheduled. If the respondent has not already been served with a summons, the application shall be served on the respondent not less than five court days before the hearing. If timely service cannot be made, the court may set a new hearing date.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c271.pdf?cite=1989%20c%20271%20§%20216[1989 c 271 § 216]; ]

== 10.66.040 - Ex parte temporary order—Hearing—Notice.
Upon filing an application for an off-limits order under this chapter, an applicant may obtain an ex parte temporary off-limits order, with or without notice, only upon a showing that serious or irreparable harm will result to the applicant if the temporary off-limits order is not granted. An ex parte temporary off-limits order shall be effective for a fixed period not to exceed fourteen days, but the court may reissue the order upon a showing of good cause. A hearing on a one-year off-limits order, as provided in this chapter, shall be set for fourteen days from the issuance of the temporary order. The respondent shall be personally served with a copy of the temporary off-limits order along with a copy of the application and notice of the date set for the full hearing. At the hearing, if the court finds that respondent is a known drug trafficker who has engaged in drug trafficking in a particular area, and that the area is associated with a pattern of drug activities, the court shall issue a one-year off-limits order prohibiting the respondent from having any contact with the PADT area. At any time within three months before the expiration of the order, the applicant may apply for a renewal of the order by filing a new petition under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c271.pdf?cite=1989%20c%20271%20§%20217[1989 c 271 § 217]; ]

== 10.66.050 - Additional relief—PADT area.
In granting a temporary off-limits order or a one-year off-limits order, the court shall have discretion to grant additional relief as the court considers proper to achieve the purposes of this chapter. The PADT area defined in any off-limits order must be reasonably related to the area or areas impacted by the unlawful drug activity as described by the applicant in any civil action under RCW 10.66.020 (1), (2), or (3). The court in its discretion may allow a respondent, who is the subject of any order issued under RCW 10.66.020 as part of a civil or criminal proceeding, to enter an off-limits area or areas for health or employment reasons, subject to conditions prescribed by the court. Upon request, a certified copy of the order shall be provided to the applicant by the clerk of the court.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1142.SL.pdf?cite=1999%20c%20143%20§%2046[1999 c 143 § 46]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c271.pdf?cite=1989%20c%20271%20§%20218[1989 c 271 § 218]; ]

== 10.66.060 - Bond or security.
A temporary off-limits order or a one-year off-limits order may not issue under this chapter except upon the giving of a bond or security by the applicant. The court shall set the bond or security in the amount the court deems proper, but not less than one thousand dollars, for the payment of costs and damages that may be incurred by any party who is found to have been wrongfully restrained or enjoined. A bond or security shall not be required of the state of Washington, municipal corporations, or political subdivisions of the state of Washington.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c271.pdf?cite=1989%20c%20271%20§%20219[1989 c 271 § 219]; ]

== 10.66.070 - Appearance of party.
Nothing in this chapter shall preclude a party from appearing in person or by counsel.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c271.pdf?cite=1989%20c%20271%20§%20220[1989 c 271 § 220]; ]

== 10.66.080 - Notice of order to law enforcement agency.
A copy of an off-limits order granted under this chapter shall be forwarded by the court to the local law enforcement agency with jurisdiction over the PADT area specified in the order on or before the next judicial day following issuance of the order. Upon receipt of the order, the law enforcement agency shall promptly enter it into an appropriate law enforcement information system.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c271.pdf?cite=1989%20c%20271%20§%20221[1989 c 271 § 221]; ]

== 10.66.090 - Penalties.
. A person who willfully disobeys an off-limits order issued under this chapter is guilty of a gross misdemeanor.

. A person is guilty of a class C felony punishable according to chapter 9A.20 RCW if the person willfully disobeys an off-limits order in violation of the terms of the order and also either:

.. Enters or remains in a PADT area that is within one thousand feet of any school; or

.. Is convicted of a second or subsequent violation of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%2093[2003 c 53 § 93]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c271.pdf?cite=1989%20c%20271%20§%20223[1989 c 271 § 223]; ]

== 10.66.100 - Additional penalties.
Any person who willfully disobeys an off-limits order issued under this chapter shall be subject to criminal penalties as provided in this chapter and may also be found in contempt of court and subject to penalties under chapter 7.21 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1142.SL.pdf?cite=1999%20c%20143%20§%2047[1999 c 143 § 47]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c271.pdf?cite=1989%20c%20271%20§%20222[1989 c 271 § 222]; ]

== 10.66.110 - Jurisdiction.
The superior courts shall have jurisdiction of all civil actions and all felony criminal proceedings brought under this chapter. Courts of limited jurisdiction shall have jurisdiction of all misdemeanor and gross misdemeanor criminal actions brought under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c271.pdf?cite=1989%20c%20271%20§%20224[1989 c 271 § 224]; ]

== 10.66.120 - Venue.
For the purposes of this chapter, an action may be brought in any county in which any element of the alleged drug trafficking activities occurred.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c271.pdf?cite=1989%20c%20271%20§%20225[1989 c 271 § 225]; ]

== 10.66.130 - Modification of order—Notice to law enforcement agency.
Upon application, notice to all parties, and a hearing, the court may modify the terms of an off-limits order. When an order is terminated, modified, or amended before its expiration date, the clerk of the court shall forward, on or before the next judicial day, a true copy of the amended order to the law enforcement agency specified in the order. Upon receipt of an order, the law enforcement agency shall promptly enter it into an appropriate law enforcement information system.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c271.pdf?cite=1989%20c%20271%20§%20226[1989 c 271 § 226]; ]

