= 10.98 - Criminal justice information act.
:toc:

== 10.98.010 - Purpose.
The purpose of this chapter is to provide a system of reporting and disseminating felony criminal justice information that provides: (1) Timely and accurate criminal histories for filing and sentencing under the sentencing reform act of 1981, (2) identification and tracking of felons, and (3) data for statewide planning and forecasting of the felon population.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c17.pdf?cite=1984%20c%2017%20§%201[1984 c 17 § 1]; ]

== 10.98.020 - Short title.
This chapter may be known and cited as the criminal justice information act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c17.pdf?cite=1984%20c%2017%20§%202[1984 c 17 § 2]; ]

== 10.98.030 - Source of conviction histories.
The Washington state patrol identification, child abuse, and criminal history section as established in *RCW 43.43.700 shall be the primary source of felony conviction histories for filings, plea agreements, and sentencing on felony cases.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1142.SL.pdf?cite=1999%20c%20143%20§%2050[1999 c 143 § 50]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c17.pdf?cite=1984%20c%2017%20§%203[1984 c 17 § 3]; ]

== 10.98.040 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Arrest and fingerprint form" means the reporting form prescribed by the *identification, child abuse, and criminal history section to initiate compiling arrest and identification information.

. "Chief law enforcement officer" includes the sheriff or director of public safety of a county, the chief of police of a city or town, and chief officers of other law enforcement agencies operating within the state.

. "Department" means the department of corrections.

. "Disposition" means the conclusion of a criminal proceeding at any stage it occurs in the criminal justice system. Disposition includes but is not limited to temporary or permanent outcomes such as charges dropped by police, charges not filed by the prosecuting attorney, deferred prosecution, defendant absconded, charges filed by the prosecuting attorney pending court findings such as not guilty, dismissed, guilty, or guilty—case appealed to higher court.

. "Disposition report" means the reporting form prescribed by the *identification, child abuse, and criminal history section to report the legal procedures taken after completing an arrest and fingerprint form. The disposition report shall include but not be limited to the following types of information:

.. The type of disposition;

.. The statutory citation for the arrests;

.. The sentence structure if the defendant was convicted of a felony;

.. The state identification number; and

.. Identification information and other information that is prescribed by the *identification, child abuse, and criminal history section.

. "Fingerprints" means the fingerprints taken from arrested or charged persons under the procedures prescribed by the Washington state patrol *identification, child abuse, and criminal history section.

. "Prosecuting attorney" means the public or private attorney prosecuting a criminal case.

. "Section" refers to the Washington state patrol *section on identification, child abuse, and criminal history.

. "Sentence structure" means itemizing the components of the felony sentence. The sentence structure shall include but not be limited to the total or partial confinement sentenced, and whether the sentence is prison or jail, community supervision, fines, restitution, or community restitution.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6627.SL.pdf?cite=2002%20c%20175%20§%2018[2002 c 175 § 18]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1142.SL.pdf?cite=1999%20c%20143%20§%2051[1999 c 143 § 51]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c201.pdf?cite=1985%20c%20201%20§%201[1985 c 201 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c17.pdf?cite=1984%20c%2017%20§%204[1984 c 17 § 4]; ]

== 10.98.050 - Officials' duties.
. It is the duty of the chief law enforcement officer or the local director of corrections to transmit within seventy-two hours from the time of arrest to the section fingerprints together with other identifying data as may be prescribed by the section, and statutory violations of any person lawfully arrested, fingerprinted, and photographed under RCW 43.43.735. The disposition report shall be transmitted to the prosecuting attorney, county clerk, or appropriate court of limited jurisdiction, whichever is responsible for transmitting the report to the section under RCW 10.98.010.

. At the preliminary hearing or the arraignment of a felony case, the judge shall ensure that the felony defendants have been fingerprinted and an arrest and fingerprint form transmitted to the section. In cases where fingerprints have not been taken, the judge shall order the chief law enforcement officer of the jurisdiction or the local director of corrections, or, in the case of a juvenile, the juvenile court administrator to initiate an arrest and fingerprint form and transmit it to the section. The disposition report shall be transmitted to the prosecuting attorney.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5573-S.SL.pdf?cite=1999%20c%2049%20§%202[1999 c 49 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c6.pdf?cite=1989%20c%206%20§%201[1989 c 6 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c450.pdf?cite=1987%20c%20450%20§%206[1987 c 450 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c201.pdf?cite=1985%20c%20201%20§%202[1985 c 201 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c17.pdf?cite=1984%20c%2017%20§%205[1984 c 17 § 5]; ]

== 10.98.060 - Arrest and fingerprint form.
The arrest and fingerprint form shall include but not be limited to the following:

. Unique numbers associated with the arrest charges. The unique numbering system may be controlled by the local law enforcement agency, however the section shall approve of the numbering system and maintain a current catalog of approved local numbering systems. The purpose of the unique numbering system is to allow tracking of arrest charges through disposition;

. An organization code;

. Date of arrest;

. Local identification number;

. The prescribed fingerprints;

. Individual identification information and other information prescribed by the section.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c17.pdf?cite=1984%20c%2017%20§%206[1984 c 17 § 6]; ]

== 10.98.070 - National crime information center interstate identification index.
The section shall be the sole recipient of arrest and fingerprint forms described in RCW 10.98.060, fingerprint forms described in RCW 43.43.760, and disposition reports for forwarding to the federal bureau of investigation as required for participation in the national crime information center interstate identification index. The section shall comply with national crime information center interstate identification index regulations to maintain availability of out-of-state criminal history information.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c17.pdf?cite=1984%20c%2017%20§%207[1984 c 17 § 7]; ]

== 10.98.080 - State identification number, furnishing of.
The section shall promptly furnish a state identification number to the originating agency and to the prosecuting attorney who received a copy of the arrest and fingerprint form. In the case of juvenile felony-like adjudications, the section shall furnish, upon request, the state identification number to the juvenile information section of the administrative office of the courts.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1668.SL.pdf?cite=2005%20c%20282%20§%2023[2005 c 282 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c201.pdf?cite=1985%20c%20201%20§%203[1985 c 201 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c17.pdf?cite=1984%20c%2017%20§%208[1984 c 17 § 8]; ]

== 10.98.090 - Disposition forms—Coding.
. In all cases where an arrest and fingerprint form is transmitted to the section, the originating agency shall code the form indicating which agency is initially responsible for reporting the disposition to the section. Coding shall include but not be limited to the prosecuting attorney, superior court, district court, municipal court, or the originating agency.

. In the case of a superior court or felony disposition, the county clerk or prosecuting attorney shall promptly transmit the completed disposition information to the section. In a county where the judicial information system or other secure method of electronic transfer of information has been implemented between the court and the section, the county clerk shall electronically provide the disposition information. In the case of a felony conviction in a county without the judicial information system or other secure method of electronic transfer of information between the court and the section, the prosecuting attorney shall attach a copy of the judgment and sentence form to the disposition form transmitted to the section. In the case of a lower court disposition, the district or municipal court administrator shall either promptly transmit the completed disposition form or, in a county where the judicial information system or other secure method of electronic transfer of information has been implemented between the court and the section, electronically provide the disposition information to the section. For all other dispositions the originating agency shall promptly transmit the completed disposition form to the section.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6535-S.SL.pdf?cite=1998%20c%20197%20§%201[1998 c 197 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c201.pdf?cite=1985%20c%20201%20§%204[1985 c 201 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c17.pdf?cite=1984%20c%2017%20§%209[1984 c 17 § 9]; ]

== 10.98.100 - Compliance audit.
The section shall administer a compliance audit at least once annually for each prosecuting attorney, district and municipal court, and originating agency to ensure that all disposition reports have been received and added to the criminal history record information described in RCW 43.43.705. The section shall identify criminal history record information for which no disposition report has been received and has been outstanding for one year or longer since the date of arrest. Each open arrest shall be researched for a final disposition by section staff or the criminal justice agency shall be furnished a list of outstanding disposition reports for criminal history record information of persons who were arrested or against whom charges were filed by that agency. Each criminal justice agency shall provide the section with a current disposition report or status within sixty days of receipt of notification of open arrest. Cases pending prosecution shall be considered outstanding dispositions in the compliance audit. The results of compliance audits shall be published annually and distributed to legislative committees dealing with criminal justice issues, the office of financial management, and criminal justice agencies and associations.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5466.SL.pdf?cite=2013%20c%2062%20§%201[2013 c 62 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1668.SL.pdf?cite=2005%20c%20282%20§%2024[2005 c 282 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c201.pdf?cite=1985%20c%20201%20§%205[1985 c 201 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c17.pdf?cite=1984%20c%2017%20§%2010[1984 c 17 § 10]; ]

== 10.98.110 - Tracking felony cases.
. The department shall maintain records to track felony cases for convicted felons sentenced either to a term of confinement exceeding one year or ordered under the supervision of the department and felony cases under the jurisdiction of the department pursuant to interstate compact agreements.

. Tracking shall begin at the time the department receives a judgment and sentence form from a prosecuting attorney and shall include the collection and updating of felons' criminal records from the time of sentencing through discharge.

. The department of corrections shall collect information for tracking felons from its offices and from information provided by county clerks, the Washington state patrol *identification, child abuse, and criminal history section, the office of financial management, and any other public or private agency that provides services to help individuals complete their felony sentences.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1142.SL.pdf?cite=1999%20c%20143%20§%2052[1999 c 143 § 52]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1578-S.SL.pdf?cite=1993%20c%2031%20§%201[1993 c 31 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c462.pdf?cite=1987%20c%20462%20§%202[1987 c 462 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c17.pdf?cite=1984%20c%2017%20§%2011[1984 c 17 § 11]; ]

== 10.98.130 - Local jail reports.
Local jails shall report to the office of financial management and that office shall transmit to the department the information on all persons convicted of felonies or incarcerated for noncompliance with a felony sentence who are admitted or released from the jails and shall promptly respond to requests of the department for such data. Information transmitted shall include but not be limited to the state identification number, whether the reason for admission to jail was a felony conviction or noncompliance with a felony sentence, and the dates of the admission and release.

The office of financial management may contract with a state or local governmental agency, or combination thereof, or a private organization for the information collection and transmittal under this section.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c152.pdf?cite=1988%20c%20152%20§%201[1988 c 152 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c462.pdf?cite=1987%20c%20462%20§%203[1987 c 462 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c17.pdf?cite=1984%20c%2017%20§%2013[1984 c 17 § 13]; ]

== 10.98.140 - Criminal justice forecasting—Sentencing records.
. The section, the department, and the office of financial management shall be the primary sources of information for criminal justice forecasting. The information maintained by these agencies shall be complete, accurate, and sufficiently timely to support state criminal justice forecasting.

. The caseload forecast council shall keep records on all sentencings above or below the standard range defined by chapter 9.94A RCW. As a minimum, the records shall include the name of the offender, the crimes for which the offender was sentenced, the name and county of the sentencing judge, and the deviation from the standard range. Such records shall be made available to public officials upon request.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5891-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2040%20§%2032[2011 1st sp.s. c 40 § 32]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c462.pdf?cite=1987%20c%20462%20§%204[1987 c 462 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c201.pdf?cite=1985%20c%20201%20§%206[1985 c 201 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c17.pdf?cite=1984%20c%2017%20§%2014[1984 c 17 § 14]; ]

== 10.98.150 - Status reports on felons.
The section and the department shall provide prompt responses to the requests of law enforcement agencies and jails regarding the status of suspected or convicted felons. Dissemination of individual identities, criminal histories, or the whereabouts of a suspected or convicted felon shall be in accordance with chapter 10.97 RCW, the Washington state criminal records privacy act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c17.pdf?cite=1984%20c%2017%20§%2015[1984 c 17 § 15]; ]

== 10.98.160 - Procedures, development considerations—Washington integrated justice information board, review and recommendations.
In the development and modification of the procedures, definitions, and reporting capabilities of the section, the department, the office of financial management, and the responsible agencies and persons shall consider the needs of other criminal justice agencies such as the administrative office of the courts, local law enforcement agencies, local jails, the indeterminate sentence review board, the clemency board, prosecuting attorneys, and affected state agencies such as the office of financial management and legislative committees dealing with criminal justice issues. The Washington integrated justice information board shall review and provide recommendations to state justice agencies and the courts for development and modification of the statewide justice information network.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5891-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2040%20§%2033[2011 1st sp.s. c 40 § 33]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1668.SL.pdf?cite=2005%20c%20282%20§%2025[2005 c 282 § 25]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1605-S.SL.pdf?cite=2003%20c%20104%20§%202[2003 c 104 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1142.SL.pdf?cite=1999%20c%20143%20§%2053[1999 c 143 § 53]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c462.pdf?cite=1987%20c%20462%20§%205[1987 c 462 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c17.pdf?cite=1984%20c%2017%20§%2016[1984 c 17 § 16]; ]

