= 10.37 - Accusations and their requisites.
:toc:

== 10.37.010 - Pleadings required in criminal proceedings.
No pleading other than an indictment, information or complaint shall be required on the part of the state in any criminal proceedings in any court of the state, and when such pleading is in the manner and form as provided by law the defendant shall be required to plead thereto as prescribed by law without any further action or proceedings of any kind on the part of the state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c150.pdf?cite=1925%20ex.s.%20c%20150%20§%203[1925 ex.s. c 150 § 3]; RRS § 2050-1. FORMER PARTS OF SECTION:   1927 c 103 § 1; Code 1881 § 764; RRS § 2023, now codified as RCW  10.37.015.   1909 c 87 § 1; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c117.pdf?cite=1891%20c%20117%20§%201[1891 c 117 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c100.pdf?cite=1890%20p%20100%20§%201[1890 p 100 § 1]; RRS § 2024, now codified as RCW  10.37.026. (iii)  1891 c 28 § 19; Code 1881 § 1003; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20224%20§%20186[1873 p 224 § 186]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20240%20§%20181[1869 p 240 § 181]; RRS § 2054, now codified as RCW  10.37.025; ]

== 10.37.015 - Charge by information or indictment—Exceptions.
. No person shall be held to answer in any court for an alleged crime or offense, unless upon an information filed by the prosecuting attorney, or upon an indictment by a grand jury, except in cases of misdemeanor or gross misdemeanor before a district or municipal judge, or before a court martial, except as provided in subsection (2) of this section.

. Violations of RCW 46.20.342(1)(c)(iv) may be required by the prosecuting attorney to be referred to his or her office for consideration of filing an information or for entry into a precharge diversion program.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5195-S.SL.pdf?cite=2011%20c%2046%20§%201[2011 c 46 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c202.pdf?cite=1987%20c%20202%20§%20167[1987 c 202 § 167]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1927c103.pdf?cite=1927%20c%20103%20§%201[1927 c 103 § 1]; Code 1881 § 764; RRS § 2023; ]

== 10.37.040 - Indictment—Form.
The indictment may be substantially in the following form:

State of Washingtonv.A.  . . . . . B.  . . . . .Superior Court ofthe State ofWashington for theCounty of. . . .A. B. is accused by the grand jury of the . . . . . . . . . ., by this indictment, of the crime of [here insert the name of the crime, if it have one, such as treason, murder, arson, manslaughter, or the like; or if it be a crime having no general name, such as libel, assault and battery, and the like, insert a brief description of it as given by law], committed as follows:The said A. B. on the . . . . day of . . . . . ., (year) . . . ., in the county of . . . . . ., aforesaid, [here set forth the act charged as a crime.]Dated at . . . . . ., in the county aforesaid, the . . . . day of . . . . . ., A.D. (year) . . . . (Signed) C. D., Prosecuting Attorney.(Indorsed) A true bill.  (Signed) E. F., Foreperson of the Grand Jury.

State of Washington

v.



A.  . . . . . B.  . . . . .















Superior Court of

the State of

Washington for the

County of

. . . .

A. B. is accused by the grand jury of the . . . . . . . . . ., by this indictment, of the crime of [here insert the name of the crime, if it have one, such as treason, murder, arson, manslaughter, or the like; or if it be a crime having no general name, such as libel, assault and battery, and the like, insert a brief description of it as given by law], committed as follows:

The said A. B. on the . . . . day of . . . . . ., (year) . . . ., in the county of . . . . . ., aforesaid, [here set forth the act charged as a crime.]

Dated at . . . . . ., in the county aforesaid, the . . . . day of . . . . . ., A.D. (year) . . . .

 

(Signed) C. D., Prosecuting Attorney.

(Indorsed) A true bill.

 

 

(Signed) E. F., Foreperson of the Grand Jury.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2359-S.SL.pdf?cite=2016%20c%20202%20§%205[2016 c 202 § 5]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%201036[2010 c 8 § 1036]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c28.pdf?cite=1891%20c%2028%20§%2021[1891 c 28 § 21]; Code 1881 § 1005; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20225%20§%20188[1873 p 225 § 188]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20240%20§%20183[1869 p 240 § 183]; RRS § 2056; ]

== 10.37.050 - Indictment or information—Sufficiency.
The indictment or information is sufficient if it can be understood therefrom—

. That it is entitled in a court having authority to receive it;

. That it was found by a grand jury or prosecuting attorney of the county in which the court was held;

. That the defendant is named, or if his or her name cannot be discovered, that he or she is described by a fictitious name or by reference to a unique genetic sequence of deoxyribonucleic acid, with the statement that his or her real name is unknown;

. That the crime was committed within the jurisdiction of the court, except where, as provided by law, the act, though done without the county in which the court is held, is triable therein;

. That the crime was committed at some time previous to the finding of the indictment or filing of the information, and within the time limited by law for the commencement of an action therefor;

. That the act or omission charged as the crime is clearly and distinctly set forth in ordinary and concise language, without repetition, and in such a manner as to enable a person of common understanding to know what is intended;

. The act or omission charged as the crime is stated with such a degree of certainty as to enable the court to pronounce judgment upon a conviction according to the right of the case.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%201037[2010 c 8 § 1037]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2491-S.SL.pdf?cite=2000%20c%2092%20§%203[2000 c 92 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c28.pdf?cite=1891%20c%2028%20§%2029[1891 c 28 § 29]; Code 1881 § 1014; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20226%20§%20197[1873 p 226 § 197]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20242%20§%20192[1869 p 242 § 192]; RRS § 2065. FORMER PARTS OF SECTION:   1891 c 28 § 20; Code 1881 § 1004; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20224%20§%20187[1873 p 224 § 187]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20240%20§%20182[1869 p 240 § 182]; RRS § 2055, now codified as RCW  10.37.052.   1891 c 28 § 22; Code 1881 § 1006; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20225%20§%20189[1873 p 225 § 189]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20112%20§%2061[1854 p 112 § 61]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20241%20§%20184[1869 p 241 § 184]; RRS § 2057, now codified as RCW  10.37.054. (iii)  1891 c 28 § 30; Code 1881 § 1015; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20227%20§%20198[1873 p 227 § 198]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20242%20§%20193[1869 p 242 § 193]; RRS § 2066, now codified as RCW  10.37.056; ]

== 10.37.052 - Indictment or information—Requisites.
The indictment or information must contain—

. The title of the action, specifying the name of the court to which the indictment or information is presented and the names of the parties;

. A statement of the acts constituting the offense, in ordinary and concise language, without repetition, and in such manner as to enable a person of common understanding to know what is intended.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c28.pdf?cite=1891%20c%2028%20§%2020[1891 c 28 § 20]; Code 1881 § 1004; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20224%20§%20187[1873 p 224 § 187]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20240%20§%20182[1869 p 240 § 182]; RRS § 2055; ]

== 10.37.054 - Indictment or information—Certainty.
The indictment or information must be direct and certain as it regards:

. The party charged;

. The crime charged; and

. The particular circumstances of the crime charged, when they are necessary to constitute a complete crime.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c28.pdf?cite=1891%20c%2028%20§%2022[1891 c 28 § 22]; Code 1881 § 1006; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20225%20§%20189[1873 p 225 § 189]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20241%20§%20184[1869 p 241 § 184]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20112%20§%2061[1854 p 112 § 61]; RRS § 2057; ]

== 10.37.056 - Indictment or information—Certain defects or imperfections deemed immaterial.
No indictment or information is insufficient, nor can the trial, judgment or other proceedings thereon be affected, by reason of any of the following matters, which were formerly deemed defects or imperfections:

. For want of an allegation of the time or place of any material fact, when the time and place have been once stated;

. For the omission of any of the following allegations, namely: "With force and arms," "contrary to the form of the statute or the statutes," or "against the peace and dignity of the state;"

. For the omission to allege that the grand jury was impaneled, sworn, or charged;

. For any surplusage or repugnant allegation or for any repetition, when there is sufficient matter alleged to indicate clearly the offense and the person charged; nor

. For any other matter which was formerly deemed a defect or imperfection, but which does not tend to the prejudice of the substantial rights of the defendant upon the merits.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c28.pdf?cite=1891%20c%2028%20§%2030[1891 c 28 § 30]; Code 1881 § 1015; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20227%20§%20198[1873 p 227 § 198]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20242%20§%20193[1869 p 242 § 193]; RRS § 2066; ]

== 10.37.060 - Indictment or information—Separation into counts—Consolidation.
When there are several charges against any person, or persons, for the same act or transaction, or for two or more acts or transactions connected together, or for two or more acts or transactions of the same class of crimes or offenses, which may be properly joined, instead of having several indictments or informations the whole may be joined in one indictment, or information, in separate counts; and, if two or more indictments are found, or two or more informations filed, in such cases, the court may order such indictments or informations to be consolidated.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c109.pdf?cite=1925%20ex.s.%20c%20109%20§%201[1925 ex.s. c 109 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c28.pdf?cite=1891%20c%2028%20§%2024[1891 c 28 § 24]; Code 1881 § 1008; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20225%20§%20191[1873 p 225 § 191]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20241%20§%20186[1869 p 241 § 186]; RRS § 2059; ]

== 10.37.070 - Animals—Description of.
When the crime involves the taking of or injury to an animal the indictment or information is sufficiently certain in that respect if it describes the animal by the common name of its class.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c28.pdf?cite=1891%20c%2028%20§%2026[1891 c 28 § 26]; Code 1881 § 1011; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20226%20§%20194[1873 p 226 § 194]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20241%20§%20189[1869 p 241 § 189]; RRS § 2062; ]

== 10.37.080 - Forgery—Description of instrument.
When an instrument which is the subject of an indictment or information for forgery has been destroyed or withheld by the act or procurement of the defendant, and the fact of the destruction or withholding is alleged in the indictment or information, and established on the trial, the misdescription of the instrument is immaterial.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c28.pdf?cite=1891%20c%2028%20§%2035[1891 c 28 § 35]; Code 1881 § 1020; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20227%20§%20203[1873 p 227 § 203]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20113%20§%2068[1854 p 113 § 68]; RRS § 2071; ]

== 10.37.090 - Injury to person or intention concerning.
When the crime involves the commission of, or an attempt to commit a private injury, and is described with sufficient certainty in other respects to identify the act, an erroneous allegation as to the person injured or intended to be injured is not material.

[ Code 1881 § 1010; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20226%20§%20193[1873 p 226 § 193]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20241%20§%20188[1869 p 241 § 188]; RRS § 2061; ]

== 10.37.100 - Judgment, how pleaded.
In pleading a judgment or other determination of or proceeding before a court or officer of special jurisdiction, it is not necessary to state in the indictment or information the facts conferring jurisdiction; but the judgment, determination or proceeding may be stated to have been duly given or made. The facts conferring jurisdiction, however, must be established on the trial.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c28.pdf?cite=1891%20c%2028%20§%2032[1891 c 28 § 32]; Code 1881 § 1017; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20227%20§%20200[1873 p 227 § 200]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20242%20§%20195[1869 p 242 § 195]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20112%20§%2065[1854 p 112 § 65]; RRS § 2068; ]

== 10.37.110 - Larceny or embezzlement—Specification.
In an indictment or information for larceny or embezzlement of money, bank notes, certificates of stock, or valuable securities, or for a conspiracy to cheat or defraud a person of any such property, it is sufficient to allege the larceny or embezzlement, or the conspiracy to cheat and defraud, to be of money, bank notes, certificates of stock, or valuable securities, without specifying the coin, number, denomination or kind thereof.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c28.pdf?cite=1891%20c%2028%20§%2038[1891 c 28 § 38]; Code 1881 § 1023; RRS § 2074; ]

== 10.37.130 - Obscene literature—Description.
An indictment or information for exhibiting, publishing, passing, selling, or offering to sell, or having in possession with such intent, any lewd or obscene book, pamphlet, picture, print, card, paper, or writing, need not set forth any portion of the language used or figures shown upon such book, pamphlet, picture, print, card, paper, or writing, but it is sufficient to state generally the fact of the lewdness or obscenity thereof.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c28.pdf?cite=1891%20c%2028%20§%2039[1891 c 28 § 39]; Code 1881 § 1024; RRS § 2075; ]

== 10.37.140 - Perjury—Subornation of perjury—Description of matter.
In an indictment or information for perjury, or subornation of perjury, it is sufficient to set forth the substance of the controversy or matter in respect to which the crime was committed, and in what court or before whom the oath alleged to be false was taken, and that the court or person before whom it was taken had authority to administer it, with proper allegations of the falsity of the matter on which the perjury is assigned; but the indictment or information need not set forth the pleadings, record or proceedings with which the oath is connected, nor the commission or authority of the court or person before whom the perjury was committed.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c28.pdf?cite=1891%20c%2028%20§%2036[1891 c 28 § 36]; Code 1881 § 1021; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20228%20§%20204[1873 p 228 § 204]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20243%20§%20199[1869 p 243 § 199]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20112%20§%2067[1854 p 112 § 67]; RRS § 2072; ]

== 10.37.150 - Presumptions of law need not be stated.
Neither presumptions of law nor matters of which judicial notice is taken need be stated in an indictment or information.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c28.pdf?cite=1891%20c%2028%20§%2031[1891 c 28 § 31]; Code 1881 § 1016; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20227%20§%20199[1873 p 227 § 199]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20242%20§%20194[1869 p 242 § 194]; RRS § 2067; ]

== 10.37.160 - Statute—Exact words need not be used.
Words used in a statute to define a crime need not be strictly pursued in the indictment or information, but other words conveying the same meaning may be used.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c28.pdf?cite=1891%20c%2028%20§%2028[1891 c 28 § 28]; Code 1881 § 1013; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20226%20§%20196[1873 p 226 § 196]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20241%20§%20191[1869 p 241 § 191]; RRS § 2064; ]

== 10.37.170 - Statute, private—Description.
In pleading a private statute, or right derived therefrom, it is sufficient to refer, in the indictment or information, to the statute by its title and the day of its passage, and the court must thereupon take judicial notice thereof.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c28.pdf?cite=1891%20c%2028%20§%2033[1891 c 28 § 33]; Code 1881 § 1018; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20227%20§%20201[1873 p 227 § 201]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20243%20§%20196[1869 p 243 § 196]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20112%20§%2066[1854 p 112 § 66]; RRS § 2069; ]

== 10.37.190 - Words and phrases—How used.
The words used in an indictment or information must be construed in their usual acceptation, in common language, except words and phrases defined by law, which are to be construed according to their legal meaning.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c28.pdf?cite=1891%20c%2028%20§%2027[1891 c 28 § 27]; Code 1881 § 1012; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20227%20§%20195[1873 p 227 § 195]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20241%20§%20190[1869 p 241 § 190]; RRS § 2063; ]

