= 10.46 - Superior court trial.
:toc:

== 10.46.020 - Trial docket.
The clerk shall, in preparing the docket of criminal cases, enumerate the indictments and informations pending according to the date of their filing, specifying opposite to the title of each action whether it be for a felony or misdemeanor, and whether the defendant be in custody or on bail; and shall, in like manner, enter therein all indictments and informations on which issues of fact are joined, all cases brought to the court on change of venue from other counties, and all cases pending upon appeal from inferior courts.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c28.pdf?cite=1891%20c%2028%20§%2065[1891 c 28 § 65]; Code 1881 § 1044; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20231%20§%20222[1873 p 231 § 222]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20115%20§%2086[1854 p 115 § 86]; RRS § 2134; ]

== 10.46.060 - True name inserted in proceedings.
When a defendant is designated in the indictment or information by a fictitious or erroneous name, and in any stage of the proceedings his or her true name is discovered, it may be inserted in the subsequent proceedings, referring to the fact of his or her being indicted or informed against by the name mentioned in the indictment or information.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%201044[2010 c 8 § 1044]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c28.pdf?cite=1891%20c%2028%20§%2023[1891 c 28 § 23]; Code 1881 § 1007; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20225%20§%20190[1873 p 225 § 190]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20241%20§%20185[1869 p 241 § 185]; RRS § 2058; ]

== 10.46.070 - Conduct of trial—Generally.
The court shall decide all questions of law which shall arise in the course of the trial, and the trial shall be conducted in the same manner as in civil actions.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c28.pdf?cite=1891%20c%2028%20§%2070[1891 c 28 § 70]; Code 1881 § 1088; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20237%20§%20249[1873 p 237 § 249]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20119%20§%20111[1854 p 119 § 111]; RRS § 2158. FORMER PART OF SECTION: 1891 c 28 § 66, part; Code 1881 § 1078; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20236%20§%20239[1873 p 236 § 239]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20118%20§%20101[1854 p 118 § 101]; RRS § 2137, part, now codified as RCW  10.49.020; ]

== 10.46.080 - Continuances.
A continuance may be granted in any case on the ground of the absence of evidence on the motion of the defendant supported by affidavit showing the materiality of the evidence expected to be obtained, and that due diligence has been used to procure it; and also the name and place of residence of the witness or witnesses; and the substance of the evidence expected to be obtained, and if the prosecuting attorney admit that such evidence would be given, and that it be considered as actually given on the trial or offered and overruled as improper the continuance shall not be granted.

[ Code 1881 § 1077; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20206%20§%207[1877 p 206 § 7]; RRS § 2135; ]

== 10.46.085 - Continuances not permitted in certain cases.
When a defendant is charged with a crime which constitutes a violation of RCW 9A.64.020 or chapter 9.68, 9.68A, or 9A.44 RCW, and the alleged victim of the crime is a person under the age of eighteen years, neither the defendant nor the prosecuting attorney may agree to extend the originally scheduled trial date unless the court within its discretion finds that there are substantial and compelling reasons for a continuance of the trial date and that the benefit of the postponement outweighs the detriment to the victim. The court may consider the testimony of lay witnesses and of expert witnesses, if available, regarding the impact of the continuance on the victim.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c332.pdf?cite=1989%20c%20332%20§%207[1989 c 332 § 7]; ]

== 10.46.110 - Discharging defendant to give evidence.
When two or more persons are included in one prosecution, the court may, at any time before the defendant has gone into his or her defense, direct any defendant to be discharged, that he or she may be a witness for the state. A defendant may also, when there is not sufficient evidence to put him or her on his or her defense, at any time before the evidence is closed, be discharged by the court, for the purpose of giving evidence for a codefendant. The order of discharge is a bar to another prosecution for the same offense.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%201045[2010 c 8 § 1045]; Code 1881 § 1092; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20237%20§%20253[1873 p 237 § 253]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20120%20§%20117[1854 p 120 § 117]; RRS § 2162; ]

== 10.46.190 - Liability of convicted person for costs—Jury fee.
Every person convicted of a crime or held to bail to keep the peace may be liable to all the costs of the proceedings against him or her, including, when tried by a jury in the superior court or before a committing magistrate, a jury fee as provided for in civil actions for which judgment shall be rendered and collected. The court shall not order a defendant to pay costs, as described in RCW 10.01.160, if the court finds that the person at the time of sentencing is indigent as defined in RCW 10.101.010(3) (a) through (c). The jury fee, when collected for a case tried by the superior court, shall be paid to the clerk and applied as the jury fee in civil cases is applied.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1783-S2.SL.pdf?cite=2018%20c%20269%20§%209[2018 c 269 § 9]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5454-S2.SL.pdf?cite=2005%20c%20457%20§%2012[2005 c 457 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c248.pdf?cite=1977%20ex.s.%20c%20248%20§%201[1977 ex.s. c 248 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c53.pdf?cite=1977%20ex.s.%20c%2053%20§%201[1977 ex.s. c 53 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c304.pdf?cite=1961%20c%20304%20§%208[1961 c 304 § 8]; Code 1881 § 2105; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20418%20§%203[1869 p 418 § 3]; RRS § 2227; ]

== 10.46.200 - Costs allowed to acquitted or discharged defendant.
No prisoner or person under recognizance who shall be acquitted by verdict or discharged because no indictment is found against him or her, or for want of prosecution, shall be liable for any costs or fees of any officer or for any charge of subsistence while he or she was in custody, but in every such case the fees of the defendant's witnesses, and of the officers for services rendered at the request of the defendant; and charges for subsistence of the defendant while in custody shall be taxed and paid as other costs and charges in such cases.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%201046[2010 c 8 § 1046]; Code 1881 § 1168; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20207%20§%2010[1877 p 207 § 10]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20129%20§%20177[1854 p 129 § 177]; RRS § 2236; ]

== 10.46.210 - Taxation of costs on acquittal or discharge—Generally—Frivolous complaints.
When any person shall be brought before a court or other committing magistrate of any county, city or town in this state, having jurisdiction of the alleged offense, charged with the commission of a crime or misdemeanor, and such complaint upon examination shall appear to be unfounded, no costs shall be payable by such acquitted party, but the same shall be chargeable to the county, city or town for or in which the said complaint is triable, but if the court or other magistrate trying said charge, shall decide the complaint was frivolous or malicious, the judgment or verdict shall also designate who is the complainant, and may adjudge that said complainant pay the costs. In such cases a judgment shall thereupon be entered for the costs against said complainant, who shall stand committed until such costs be paid or discharged by due process of law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c202.pdf?cite=1987%20c%20202%20§%20168[1987 c 202 § 168]; Code 1881 § 2103; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20418%20§%201[1869 p 418 § 1]; RRS § 2225; ]

== 10.46.220 - Cost bills in felony cases—Certification.
In all convictions for felony, whether capital or punishable by imprisonment in the penitentiary, the clerk of the superior court shall forthwith, after sentence, tax the costs in the case. The cost bill shall be made out in triplicate, and be examined by the prosecuting attorney of the county in which the trial was had. After which the judge of the superior court shall allow and approve such bill or so much thereof, as is allowable by law. The clerk of the superior court shall thereupon, under his or her hand, and under the seal of the court, certify said triplicate cost bills, and shall file one with the papers of cause, and shall transmit one to the administrator for the courts and one to the county auditor of the county in which said felony was committed.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%201047[2010 c 8 § 1047]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c129.pdf?cite=1979%20c%20129%20§%201[1979 c 129 § 1]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1883%20p%2035%20§%201[1883 p 35 § 1]; Code 1881 § 2106; RRS § 2228; ]

== 10.46.230 - Cost bills in felony cases—Payment.
Upon the receipt of the cost bill, as provided for in the preceding section, the county auditor shall draw warrants for the amounts due each person, as certified in said cost bill, which warrants shall be paid as other county warrants are paid. On receipt of the certified copy of said cost bill, the administrator for the courts shall examine and audit said bill and allow the payment by the state of statutorily required witness fees in cases where conviction of a felony is obtained and the defendant is sentenced to pay a fine or is given a prison sentence even if the sentence is deferred or suspended. Payment shall be allowed by the administrator for the courts in such cases even when the conviction is subsequently reversed or if a new trial is granted.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c129.pdf?cite=1979%20c%20129%20§%202[1979 c 129 § 2]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1883%20p%2035%20§%201[1883 p 35 § 1]; Code 1881 § 2107; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20250%20§%20316[1873 p 250 § 316]; RRS § 2229; ]

