= 10.10 - Criminal appeals from district courts.
:toc:

== 10.10.010 - Court rules.
Every person convicted before a district judge of any offense may appeal from the judgment as provided by court rules.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c202.pdf?cite=1987%20c%20202%20§%20156[1987 c 202 § 156]; 1891 c 29 § 6, part; RRS § 1919, part; Code 1881 § 1898, part; 1877 p 203 § 7, part; 1873 p 384 § 196, part; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20261%20§%20177[1854 p 261 § 177]; ]

== 10.10.060 - Appeal—Costs—Default.
The appellant in a criminal action shall not be required to advance any fees in claiming his or her appeal nor in prosecuting the same; but if convicted in the appellate court, or if sentenced for failing to prosecute his or her appeal, he or she may be required as a part of the sentence to pay the costs of the prosecution. If the appellant shall fail to enter and prosecute his or her appeal he or she shall be defaulted of his or her recognizance, if any was taken, and the superior court may award sentence against him or her for the offense whereof he or she was convicted in like manner as if he or she had been convicted thereof in that court; and if he or she be not then in custody process may be issued to bring him or her into court to receive sentence.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%201008[2010 c 8 § 1008]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c29.pdf?cite=1891%20c%2029%20§%207[1891 c 29 § 7]; RRS § 1920; Code 1881 § 1900; 1873 p 384 § 198, part; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20261%20§%20179[1854 p 261 § 179]; ]

