= 10.99 - Domestic violence—Official response.
:toc:

== 10.99.010 - Purpose—Intent.
The purpose of this chapter is to recognize the importance of domestic violence as a serious crime against society and to assure the victim of domestic violence the maximum protection from abuse which the law and those who enforce the law can provide. The legislature finds that the existing criminal statutes are adequate to provide protection for victims of domestic violence. However, previous societal attitudes have been reflected in policies and practices of law enforcement agencies and prosecutors which have resulted in differing treatment of crimes occurring between cohabitants and of the same crimes occurring between strangers. Only recently has public perception of the serious consequences of domestic violence to society and to the victims led to the recognition of the necessity for early intervention by law enforcement agencies. It is the intent of the legislature that the official response to cases of domestic violence shall stress the enforcement of the laws to protect the victim and shall communicate the attitude that violent behavior is not excused or tolerated. Furthermore, it is the intent of the legislature that criminal laws be enforced without regard to whether the persons involved are or were married, cohabiting, or involved in a relationship.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c105.pdf?cite=1979%20ex.s.%20c%20105%20§%201[1979 ex.s. c 105 § 1]; ]

== 10.99.020 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Agency" means a general authority Washington law enforcement agency as defined in RCW 10.93.020.

. "Association" means the Washington association of sheriffs and police chiefs.

. "Dating relationship" has the same meaning as in RCW 26.50.010.

. "Domestic violence" includes but is not limited to any of the following crimes when committed either by (a) one family or household member against another family or household member, or (b) one intimate partner against another intimate partner:

... Assault in the first degree (RCW 9A.36.011);

... Assault in the second degree (RCW 9A.36.021);

... Assault in the third degree (RCW 9A.36.031);

... Assault in the fourth degree (RCW 9A.36.041);

.. Drive-by shooting (RCW 9A.36.045);

.. Reckless endangerment (RCW 9A.36.050);

.. Coercion (RCW 9A.36.070);

.. Burglary in the first degree (RCW 9A.52.020);

... Burglary in the second degree (RCW 9A.52.030);

.. Criminal trespass in the first degree (RCW 9A.52.070);

.. Criminal trespass in the second degree (RCW 9A.52.080);

.. Malicious mischief in the first degree (RCW 9A.48.070);

.. Malicious mischief in the second degree (RCW 9A.48.080);

.. Malicious mischief in the third degree (RCW 9A.48.090);

.. Kidnapping in the first degree (RCW 9A.40.020);

.. Kidnapping in the second degree (RCW 9A.40.030);

.. Unlawful imprisonment (RCW 9A.40.040);

.. Violation of the provisions of a restraining order, no-contact order, or protection order restraining or enjoining the person or restraining the person from going onto the grounds of or entering a residence, workplace, school, or day care, or prohibiting the person from knowingly coming within, or knowingly remaining within, a specified distance of a location (RCW 10.99.040, 10.99.050, 26.09.300, * 26.10.220, 26.26B.050, 26.44.063, 26.44.150, 26.50.060, 26.50.070, 26.50.130, 26.52.070, or 74.34.145);

.. Rape in the first degree (RCW 9A.44.040);

.. Rape in the second degree (RCW 9A.44.050);

.. Residential burglary (RCW 9A.52.025);

.. Stalking (RCW 9A.46.110); and

.. Interference with the reporting of domestic violence (RCW 9A.36.150).

. "Electronic monitoring" means the same as in RCW 9.94A.030.

. "Employee" means any person currently employed with an agency.

. "Family or household members" means the same as in RCW 26.50.010.

. "Intimate partners" means the same as in RCW 26.50.010.

. "Sworn employee" means a general authority Washington peace officer as defined in RCW 10.93.020, any person appointed under RCW 35.21.333, and any person appointed or elected to carry out the duties of the sheriff under chapter 36.28 RCW.

. "Victim" means a family or household member or an intimate partner who has been subjected to domestic violence.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5149-S2.SL.pdf?cite=2020%20c%20296%20§%205[2020 c 296 § 5]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1517-S2.SL.pdf?cite=2019%20c%20263%20§%20203[2019 c 263 § 203]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5333-S.SL.pdf?cite=2019%20c%2046%20§%205014[2019 c 46 § 5014]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6161-S.SL.pdf?cite=2004%20c%2018%20§%202[2004 c 18 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6400-S2.SL.pdf?cite=2000%20c%20119%20§%205[2000 c 119 § 5]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3900-S3.SL.pdf?cite=1997%20c%20338%20§%2053[1997 c 338 § 53]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2472.SL.pdf?cite=1996%20c%20248%20§%205[1996 c 248 § 5]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5219-S.SL.pdf?cite=1995%20c%20246%20§%2021[1995 c 246 § 21]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2392.SL.pdf?cite=1994%20c%20121%20§%204[1994 c 121 § 4]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1884-S.SL.pdf?cite=1991%20c%20301%20§%203[1991 c 301 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c257.pdf?cite=1986%20c%20257%20§%208[1986 c 257 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c263.pdf?cite=1984%20c%20263%20§%2020[1984 c 263 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c105.pdf?cite=1979%20ex.s.%20c%20105%20§%202[1979 ex.s. c 105 § 2]; ]

== 10.99.030 - Law enforcement officers—Training, powers, duties—Domestic violence reports (as amended by 2019 c 110).
. All training relating to the handling of domestic violence complaints by law enforcement officers shall stress enforcement of criminal laws in domestic situations, availability of community resources, and protection of the victim. Law enforcement agencies and community organizations with expertise in the issue of domestic violence shall cooperate in all aspects of such training.

. The criminal justice training commission shall implement by January 1, 1997, a course of instruction for the training of law enforcement officers in Washington in the handling of domestic violence complaints. The basic law enforcement curriculum of the criminal justice training commission shall include at least twenty hours of basic training instruction on the law enforcement response to domestic violence. The course of instruction, the learning and performance objectives, and the standards for the training shall be developed by the commission and focus on enforcing the criminal laws, safety of the victim, and holding the perpetrator accountable for the violence. The curriculum shall include training on the extent and prevalence of domestic violence, the importance of criminal justice intervention, techniques for responding to incidents that minimize the likelihood of officer injury and that promote victim safety, investigation and interviewing skills, evidence gathering and report writing, assistance to and services for victims and children, understanding the risks of traumatic brain injury posed by domestic violence, verification and enforcement of court orders, liability, and any additional provisions that are necessary to carry out the intention of this subsection.

. The criminal justice training commission shall develop and update annually an in-service training program to familiarize law enforcement officers with the domestic violence laws. The program shall include techniques for handling incidents of domestic violence that minimize the likelihood of injury to the officer and that promote the safety of all parties. The commission shall make the training program available to all law enforcement agencies in the state.

. Development of the training in subsections (2) and (3) of this section shall be conducted in conjunction with agencies having a primary responsibility for serving victims of domestic violence with emergency shelter and other services, and representatives to the statewide organization providing training and education to these organizations and to the general public.

. The primary duty of peace officers, when responding to a domestic violence situation, is to enforce the laws allegedly violated and to protect the complaining party.

. [Empty]
.. When a peace officer responds to a domestic violence call and has probable cause to believe that a crime has been committed, the peace officer shall exercise arrest powers with reference to the criteria in RCW 10.31.100. The officer shall notify the victim of the victim's right to initiate a criminal proceeding in all cases where the officer has not exercised arrest powers or decided to initiate criminal proceedings by citation or otherwise. The parties in such cases shall also be advised of the importance of preserving evidence.

.. A peace officer responding to a domestic violence call shall take a complete offense report including the officer's disposition of the case.

. When a peace officer responds to a domestic violence call((,)):

.. The officer shall advise victims of all reasonable means to prevent further abuse, including advising each person of the availability of a shelter or other services in the community, and giving each person immediate notice of the legal rights and remedies available. The notice shall include handing each person a copy of the following statement:

"IF YOU ARE THE VICTIM OF DOMESTIC VIOLENCE, you can ask the city or county prosecuting attorney to file a criminal complaint. You also have the right to file a petition in superior, district, or municipal court requesting an order for protection from domestic abuse which could include any of the following: (a) An order restraining your abuser from further acts of abuse; (b) an order directing your abuser to leave your household; (c) an order preventing your abuser from entering your residence, school, business, or place of employment; (d) an order awarding you or the other parent custody of or visitation with your minor child or children; and (e) an order restraining your abuser from molesting or interfering with minor children in your custody. The forms you need to obtain a protection order are available in any municipal, district, or superior court.

Information about shelters and alternatives to domestic violence is available from a statewide twenty-four-hour toll-free hotline at (include appropriate phone number). The battered women's shelter and other resources in your area are . . . . . (include local information)"; and

.. The officer is encouraged to inform victims that information on traumatic brain injury can be found on the statewide web site developed under RCW 74.31.070.

. The peace officer may offer, arrange, or facilitate transportation for the victim to a hospital for treatment of injuries or to a place of safety or shelter.

. The law enforcement agency shall forward the offense report to the appropriate prosecutor within ten days of making such report if there is probable cause to believe that an offense has been committed, unless the case is under active investigation. Upon receiving the offense report, the prosecuting agency may, in its discretion, choose not to file the information as a domestic violence offense, if the offense was committed against a sibling, parent, stepparent, or grandparent.

. Each law enforcement agency shall make as soon as practicable a written record and shall maintain records of all incidents of domestic violence reported to it.

. Records kept pursuant to subsections (6) and (10) of this section shall be made identifiable by means of a departmental code for domestic violence.

. Commencing January 1, 1994, records of incidents of domestic violence shall be submitted, in accordance with procedures described in this subsection, to the Washington association of sheriffs and police chiefs by all law enforcement agencies. The Washington criminal justice training commission shall amend its contract for collection of statewide crime data with the Washington association of sheriffs and police chiefs:

.. To include a table, in the annual report of crime in Washington produced by the Washington association of sheriffs and police chiefs pursuant to the contract, showing the total number of actual offenses and the number and percent of the offenses that are domestic violence incidents for the following crimes: (i) Criminal homicide, with subtotals for murder and nonnegligent homicide and manslaughter by negligence; (ii) forcible rape, with subtotals for rape by force and attempted forcible rape; (iii) robbery, with subtotals for firearm, knife or cutting instrument, or other dangerous weapon, and strongarm robbery; (iv) assault, with subtotals for firearm, knife or cutting instrument, other dangerous weapon, hands, feet, aggravated, and other nonaggravated assaults; (v) burglary, with subtotals for forcible entry, nonforcible unlawful entry, and attempted forcible entry; (vi) larceny theft, except motor vehicle theft; (vii) motor vehicle theft, with subtotals for autos, trucks and buses, and other vehicles; (viii) arson; and (ix) violations of the provisions of a protection order or no-contact order restraining the person from going onto the grounds of or entering a residence, workplace, school, or day care, provided that specific appropriations are subsequently made for the collection and compilation of data regarding violations of protection orders or no-contact orders;

.. To require that the table shall continue to be prepared and contained in the annual report of crime in Washington until that time as comparable or more detailed information about domestic violence incidents is available through the Washington state incident based reporting system and the information is prepared and contained in the annual report of crime in Washington; and

.. To require that, in consultation with interested persons, the Washington association of sheriffs and police chiefs prepare and disseminate procedures to all law enforcement agencies in the state as to how the agencies shall code and report domestic violence incidents to the Washington association of sheriffs and police chiefs.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1532-S.SL.pdf?cite=2019%20c%20110%20§%202[2019 c 110 § 2]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2906-S.SL.pdf?cite=2016%20c%20136%20§%205[2016 c 136 § 5]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2472.SL.pdf?cite=1996%20c%20248%20§%206[1996 c 248 § 6]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5219-S.SL.pdf?cite=1995%20c%20246%20§%2022[1995 c 246 § 22]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5360-S.SL.pdf?cite=1993%20c%20350%20§%203[1993 c 350 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c263.pdf?cite=1984%20c%20263%20§%2021[1984 c 263 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c145.pdf?cite=1981%20c%20145%20§%205[1981 c 145 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c105.pdf?cite=1979%20ex.s.%20c%20105%20§%203[1979 ex.s. c 105 § 3]; ]

== 10.99.033 - Law enforcement officers—Training—Criminal justice training commission.
. All training relating to the handling of domestic violence complaints by law enforcement officers must stress enforcement of criminal laws in domestic situations, availability of community resources, and protection of the victim. Law enforcement agencies and community organizations with expertise in the issue of domestic violence shall cooperate in all aspects of such training.

. The criminal justice training commission shall implement by July 28, 2019, a course of instruction for the training of law enforcement officers in Washington in the handling of domestic violence complaints. The basic law enforcement curriculum of the criminal justice training commission must include at least twenty hours of basic training instruction on the law enforcement response to domestic violence. The course of instruction, the learning and performance objectives, and the standards for the training must be developed by the commission and focus on enforcing the criminal laws, safety of the victim, and holding the perpetrator accountable for the violence. The curriculum must include training on the extent and prevalence of domestic violence, the importance of criminal justice intervention, techniques for responding to incidents that minimize the likelihood of officer injury and that promote victim safety, investigation and interviewing skills, evidence gathering and report writing, assistance to and services for victims and children, verification and enforcement of court orders, liability, and any additional provisions that are necessary to carry out the intention of this subsection.

. The criminal justice training commission shall develop and update annually an in-service training program to familiarize law enforcement officers with domestic violence laws. The program must include techniques for handling incidents of domestic violence that minimize the likelihood of injury to the officer and that promote the safety of all parties. The commission shall make the training program available to all law enforcement agencies in the state.

. Development of the training in subsections (2) and (3) of this section must be conducted in conjunction with agencies having a primary responsibility for serving victims of domestic violence with emergency shelter and other services, and representatives to the statewide organization providing training and education to these organizations and to the general public.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1225-S.SL.pdf?cite=2019%20c%20367%20§%202[2019 c 367 § 2]; ]

== 10.99.035 - Law enforcement agencies—Domestic violence records.
. A law enforcement agency shall forward the offense report regarding any incident of domestic violence to the appropriate prosecutor within ten days of making such report if there is probable cause to believe that an offense has been committed, unless the case is under active investigation. Upon receiving the offense report, the prosecuting agency may, in its discretion, choose not to file the information as a domestic violence offense, if the offense was committed against a sibling, parent, stepparent, or grandparent.

. Each law enforcement agency shall make as soon as practicable a written record and shall maintain records of all incidents of domestic violence reported to it.

. Records kept pursuant to RCW 10.99.030 and this section must be made identifiable by means of a departmental code for domestic violence.

. Commencing on July 28, 2019, records of incidents of domestic violence must be submitted, in accordance with procedures described in this subsection, to the Washington association of sheriffs and police chiefs by all law enforcement agencies. The criminal justice training commission shall amend its contract for collection of statewide crime data with the Washington association of sheriffs and police chiefs:

.. To include a table, in the annual report of crime in Washington produced by the Washington association of sheriffs and police chiefs pursuant to the contract, showing the total number of actual offenses and the number and percent of the offenses that are domestic violence incidents for the following crimes: (i) Criminal homicide, with subtotals for murder and nonnegligent homicide and manslaughter by negligence; (ii) forcible rape, with subtotals for rape by force and attempted forcible rape; (iii) robbery, with subtotals for firearm, knife or cutting instrument, or other dangerous weapon, and strongarm robbery; (iv) assault, with subtotals for firearm, knife or cutting instrument, other dangerous weapon, hands, feet, aggravated, and other nonaggravated assaults; (v) burglary, with subtotals for forcible entry, nonforcible unlawful entry, and attempted forcible entry; (vi) larceny theft, except motor vehicle theft; (vii) motor vehicle theft, with subtotals for autos, trucks and buses, and other vehicles; (viii) arson; and (ix) violations of the provisions of a protection order or no-contact order restraining the person from going onto the grounds of or entering a residence, workplace, school, or day care, provided that specific appropriations are subsequently made for the collection and compilation of data regarding violations of protection orders or no-contact orders;

.. To require that the table shall continue to be prepared and contained in the annual report of crime in Washington until that time as comparable or more detailed information about domestic violence incidents is available through the Washington state incident-based reporting system and the information is prepared and contained in the annual report of crime in Washington; and

.. To require that, in consultation with interested persons, the Washington association of sheriffs and police chiefs prepare and disseminate procedures to all law enforcement agencies in the state as to how the agencies shall code and report domestic violence incidents to the Washington association of sheriffs and police chiefs.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1225-S.SL.pdf?cite=2019%20c%20367%20§%203[2019 c 367 § 3]; ]

== 10.99.040 - Duties of court—No-contact order.
. Because of the serious nature of domestic violence, the court in domestic violence actions:

.. Shall not dismiss any charge or delay disposition because of concurrent dissolution or other civil proceedings;

.. Shall not require proof that either party is seeking a dissolution of marriage prior to instigation of criminal proceedings;

.. Shall waive any requirement that the victim's location be disclosed to any person, other than the attorney of a criminal defendant, upon a showing that there is a possibility of further violence: PROVIDED, That the court may order a criminal defense attorney not to disclose to his or her client the victim's location; and

.. Shall identify by any reasonable means on docket sheets those criminal actions arising from acts of domestic violence.

. [Empty]
.. Because of the likelihood of repeated violence directed at those who have been victims of domestic violence in the past, when any person charged with or arrested for a crime involving domestic violence is released from custody before arraignment or trial on bail or personal recognizance, the court authorizing the release may prohibit that person from having any contact with the victim. The jurisdiction authorizing the release shall determine whether that person should be prohibited from having any contact with the victim. If there is no outstanding restraining or protective order prohibiting that person from having contact with the victim, the court authorizing release may issue, by telephone, a no-contact order prohibiting the person charged or arrested from having contact with the victim or from knowingly coming within, or knowingly remaining within, a specified distance of a location.

.. In issuing the order, the court shall consider the provisions of RCW 9.41.800, and shall order the defendant to surrender, and prohibit the person from possessing, all firearms, dangerous weapons, and any concealed pistol license as required in RCW 9.41.800.

.. The no-contact order shall also be issued in writing as soon as possible, and shall state that it may be extended as provided in subsection (3) of this section. By January 1, 2011, the administrative office of the courts shall develop a pattern form for all no-contact orders issued under this chapter. A no-contact order issued under this chapter must substantially comply with the pattern form developed by the administrative office of the courts.

. [Empty]
.. At the time of arraignment the court shall determine whether a no-contact order shall be issued or extended. So long as the court finds probable cause, the court may issue or extend a no-contact order even if the defendant fails to appear at arraignment. The no-contact order shall terminate if the defendant is acquitted or the charges are dismissed.

.. In issuing the order, the court shall consider all information documented in the incident report concerning the person's possession of and access to firearms and whether law enforcement took temporary custody of firearms at the time of the arrest. The court may as a condition of release prohibit the defendant from possessing or accessing firearms and order the defendant to immediately surrender all firearms and any concealed pistol license to a law enforcement agency upon release.

.. If a no-contact order is issued or extended, the court may also include in the conditions of release a requirement that the defendant submit to electronic monitoring as defined in RCW 9.94A.030. If electronic monitoring is ordered, the court shall specify who shall provide the monitoring services, and the terms under which the monitoring shall be performed. Upon conviction, the court may require as a condition of the sentence that the defendant reimburse the providing agency for the costs of the electronic monitoring.

. [Empty]
.. Willful violation of a court order issued under subsection (2), (3), or (7) of this section is punishable under RCW 26.50.110.

.. The written order releasing the person charged or arrested shall contain the court's directives and shall bear the legend: "Violation of this order is a criminal offense under chapter 26.50 RCW and will subject a violator to arrest; any assault, drive-by shooting, or reckless endangerment that is a violation of this order is a felony. You can be arrested even if any person protected by the order invites or allows you to violate the order's prohibitions. You have the sole responsibility to avoid or refrain from violating the order's provisions. Only the court can change the order."

.. A certified copy of the order shall be provided to the victim.

. If a no-contact order has been issued prior to charging, that order shall expire at arraignment or within seventy-two hours if charges are not filed.

. Whenever a no-contact order is issued, modified, or terminated under subsection (2) or (3) of this section, the clerk of the court shall forward a copy of the order on or before the next judicial day to the appropriate law enforcement agency specified in the order. Upon receipt of the copy of the order the law enforcement agency shall enter the order for one year or until the expiration date specified on the order into any computer-based criminal intelligence information system available in this state used by law enforcement agencies to list outstanding warrants. Entry into the computer-based criminal intelligence information system constitutes notice to all law enforcement agencies of the existence of the order. The order is fully enforceable in any jurisdiction in the state. Upon receipt of notice that an order has been terminated under subsection (3) of this section, the law enforcement agency shall remove the order from the computer-based criminal intelligence information system.

. All courts shall develop policies and procedures by January 1, 2011, to grant victims a process to modify or rescind a no-contact order issued under this chapter. The administrative office of the courts shall develop a model policy to assist the courts in implementing the requirements of this subsection.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1225-S.SL.pdf?cite=2019%20c%20367%20§%204[2019 c 367 § 4]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1943.SL.pdf?cite=2015%20c%20287%20§%209[2015 c 287 § 9]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2363-S.SL.pdf?cite=2012%20c%20223%20§%203[2012 c 223 § 3]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2777-S.SL.pdf?cite=2010%20c%20274%20§%20309[2010 c 274 § 309]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6400-S2.SL.pdf?cite=2000%20c%20119%20§%2018[2000 c 119 § 18]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3900-S3.SL.pdf?cite=1997%20c%20338%20§%2054[1997 c 338 § 54]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2472.SL.pdf?cite=1996%20c%20248%20§%207[1996 c 248 § 7]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5219-S.SL.pdf?cite=1995%20c%20246%20§%2023[1995 c 246 § 23]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=1994%20sp.s.%20c%207%20§%20449[1994 sp.s. c 7 § 449]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6103.SL.pdf?cite=1992%20c%2086%20§%202[1992 c 86 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1884-S.SL.pdf?cite=1991%20c%20301%20§%204[1991 c 301 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c303.pdf?cite=1985%20c%20303%20§%2010[1985 c 303 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c263.pdf?cite=1984%20c%20263%20§%2022[1984 c 263 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c232.pdf?cite=1983%20c%20232%20§%207[1983 c 232 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c145.pdf?cite=1981%20c%20145%20§%206[1981 c 145 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c105.pdf?cite=1979%20ex.s.%20c%20105%20§%204[1979 ex.s. c 105 § 4]; ]

== 10.99.045 - Appearances by defendant—Defendant's history—No-contact order.
. A defendant arrested for an offense involving domestic violence as defined by RCW 10.99.020 shall be required to appear in person before a magistrate within one judicial day after the arrest.

. A defendant who is charged by citation, complaint, or information with an offense involving domestic violence as defined by RCW 10.99.020 and not arrested shall appear in court for arraignment in person as soon as practicable, but in no event later than fourteen days after the next day on which court is in session following the issuance of the citation or the filing of the complaint or information.

. [Empty]
.. At the time of the appearances provided in subsection (1) or (2) of this section, the court shall determine the necessity of imposing a no-contact order or other conditions of pretrial release according to the procedures established by court rule for a preliminary appearance or an arraignment. The court may include in the order any conditions authorized under RCW 9.41.800 and 10.99.040.

.. For the purposes of (a) of this subsection, the prosecutor shall provide for the court's review:

... The defendant's criminal history, if any, that occurred in Washington or any other state;

... If available, the defendant's criminal history that occurred in any tribal jurisdiction; and

... The defendant's individual order history.

.. For the purposes of (b) of this subsection, criminal history includes all previous convictions and orders of deferred prosecution, as reported through the judicial information system or otherwise available to the court or prosecutor, current to within the period specified in (d) of this subsection before the date of the appearance.

.. The periods applicable to previous convictions and orders of deferred prosecution are:

... One working day, in the case of previous actions of courts that fully participate in the state judicial information system; and

... Seven calendar days, in the case of previous actions of courts that do not fully participate in the judicial information system. For the purposes of this subsection, "fully participate" means regularly providing records to and receiving records from the system by electronic means on a daily basis.

. Appearances required pursuant to this section are mandatory and cannot be waived.

. The no-contact order shall be issued and entered with the appropriate law enforcement agency pursuant to the procedures outlined in RCW 10.99.040 (2) and (6).

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2777-S.SL.pdf?cite=2010%20c%20274%20§%20301[2010 c 274 § 301]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6400-S2.SL.pdf?cite=2000%20c%20119%20§%2019[2000 c 119 § 19]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6258-S.SL.pdf?cite=1998%20c%2055%20§%202[1998 c 55 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=1994%20sp.s.%20c%207%20§%20450[1994 sp.s. c 7 § 450]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c263.pdf?cite=1984%20c%20263%20§%2023[1984 c 263 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c232.pdf?cite=1983%20c%20232%20§%208[1983 c 232 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c145.pdf?cite=1981%20c%20145%20§%207[1981 c 145 § 7]; ]

== 10.99.050 - Victim contact—Restriction, prohibition—Violation, penalties—Written order—Procedures—Notice of change.
. When a defendant is found guilty of a crime and a condition of the sentence restricts the defendant's ability to have contact with the victim, such condition shall be recorded and a written certified copy of that order shall be provided to the victim.

. [Empty]
.. Willful violation of a court order issued under this section is punishable under RCW 26.50.110.

.. The written order shall contain the court's directives and shall bear the legend: Violation of this order is a criminal offense under chapter 26.50 RCW and will subject a violator to arrest; any assault, drive-by shooting, or reckless endangerment that is a violation of this order is a felony.

.. An order issued pursuant to this section in conjunction with a misdemeanor or gross misdemeanor sentence or juvenile disposition remains in effect for a fixed period of time determined by the court, which may not exceed five years from the date of sentencing or disposition.

.. An order issued pursuant to this section in conjunction with a felony sentence or juvenile disposition remains in effect for a fixed period of time determined by the court, which may not exceed the adult maximum sentence established in RCW 9A.20.021.

. Whenever an order prohibiting contact is issued pursuant to this section, the clerk of the court shall forward a copy of the order on or before the next judicial day to the appropriate law enforcement agency specified in the order. Upon receipt of the copy of the order the law enforcement agency shall enter the order for one year or until the expiration date specified on the order into any computer-based criminal intelligence information system available in this state used by law enforcement agencies to list outstanding warrants. Entry into the computer-based criminal intelligence information system constitutes notice to all law enforcement agencies of the existence of the order. The order is fully enforceable in any jurisdiction in the state.

. If an order prohibiting contact issued pursuant to this section is modified or terminated, the clerk of the court shall notify the law enforcement agency specified in the order on or before the next judicial day. Upon receipt of notice that an order has been terminated, the law enforcement agency shall remove the order from any computer-based criminal intelligence system.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1517-S2.SL.pdf?cite=2019%20c%20263%20§%20303[2019 c 263 § 303]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6400-S2.SL.pdf?cite=2000%20c%20119%20§%2020[2000 c 119 § 20]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3900-S3.SL.pdf?cite=1997%20c%20338%20§%2055[1997 c 338 § 55]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2472.SL.pdf?cite=1996%20c%20248%20§%208[1996 c 248 § 8]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1884-S.SL.pdf?cite=1991%20c%20301%20§%205[1991 c 301 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c303.pdf?cite=1985%20c%20303%20§%2012[1985 c 303 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c263.pdf?cite=1984%20c%20263%20§%2024[1984 c 263 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c105.pdf?cite=1979%20ex.s.%20c%20105%20§%205[1979 ex.s. c 105 § 5]; ]

== 10.99.055 - Enforcement of orders.
A peace officer in this state shall enforce an order issued by any court in this state restricting a defendant's ability to have contact with a victim by arresting and taking the defendant into custody, pending release on bail, personal recognizance, or court order, when the officer has probable cause to believe that the defendant has violated the terms of that order.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c263.pdf?cite=1984%20c%20263%20§%2025[1984 c 263 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c232.pdf?cite=1983%20c%20232%20§%209[1983 c 232 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c145.pdf?cite=1981%20c%20145%20§%208[1981 c 145 § 8]; ]

== 10.99.060 - Prosecutor's notice to victim—Description of available procedures.
The public attorney responsible for making the decision whether or not to prosecute shall advise the victim of that decision within five days, and, prior to making that decision shall advise the victim, upon the victim's request, of the status of the case. Notification to the victim that charges will not be filed shall include a description of the procedures available to the victim in that jurisdiction to initiate a criminal proceeding.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c105.pdf?cite=1979%20ex.s.%20c%20105%20§%206[1979 ex.s. c 105 § 6]; ]

== 10.99.070 - Liability of peace officers.
A peace officer shall not be held liable in any civil action for an arrest based on probable cause, enforcement in good faith of a court order, or any other action or omission in good faith under this chapter arising from an alleged incident of domestic violence brought by any party to the incident.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c105.pdf?cite=1979%20ex.s.%20c%20105%20§%207[1979 ex.s. c 105 § 7]; ]

== 10.99.080 - Penalty assessment (as amended by 2015 c 265).
. All superior courts, and courts organized under Title 3 or 35 RCW, may impose a penalty assessment not to exceed one hundred dollars on any ((person))adult offender convicted of a crime involving domestic violence. The assessment shall be in addition to, and shall not supersede, any other penalty, restitution, fines, or costs provided by law.

. Revenue from the assessment shall be used solely for the purposes of establishing and funding domestic violence advocacy and domestic violence prevention and prosecution programs in the city or county of the court imposing the assessment. Revenue from the assessment shall not be used for indigent criminal defense. If the city or county does not have domestic violence advocacy or domestic violence prevention and prosecution programs, cities and counties may use the revenue collected from the assessment to contract with recognized community-based domestic violence program providers.

. The assessment imposed under this section shall not be subject to any state or local remittance requirements under chapter 3.46, 3.50, 3.62, 7.68, 10.82, or 35.20 RCW.

. For the purposes of this section, "convicted" includes a plea of guilty, a finding of guilt regardless of whether the imposition of the sentence is deferred or any part of the penalty is suspended, or the levying of a fine. For the purposes of this section, "domestic violence" has the same meaning as that term is defined under RCW 10.99.020 and includes violations of equivalent local ordinances.

. When determining whether to impose a penalty assessment under this section, judges are encouraged to solicit input from the victim or representatives for the victim in assessing the ability of the convicted offender to pay the penalty, including information regarding current financial obligations, family circumstances, and ongoing restitution.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5564-S2.SL.pdf?cite=2015%20c%20265%20§%2024[2015 c 265 § 24]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6384-S.SL.pdf?cite=2004%20c%2015%20§%202[2004 c 15 § 2]; ]

== 10.99.090 - Policy adoption and implementation.
. By December 1, 2004, the association shall develop a written model policy on domestic violence committed or allegedly committed by sworn employees of agencies. In developing the policy, the association shall convene a work group consisting of representatives from the following entities and professions:

.. Statewide organizations representing state and local enforcement officers;

.. A statewide organization providing training and education for agencies having the primary responsibility of serving victims of domestic violence with emergency shelter and other services; and

.. Any other organization or profession the association determines to be appropriate.

. Members of the work group shall serve without compensation.

. The model policy shall provide due process for employees and, at a minimum, meet the following standards:

.. Provide prehire screening procedures reasonably calculated to disclose whether an applicant for a sworn employee position:

... Has committed or, based on credible sources, has been accused of committing an act of domestic violence;

... Is currently being investigated for an allegation of child abuse or neglect or has previously been investigated for founded allegations of child abuse or neglect; or

... Is currently or has previously been subject to any order under RCW 26.44.063, this chapter, chapter 10.14 or 26.50 RCW, or any equivalent order issued by another state or tribal court;

.. Provide for the mandatory, immediate response to acts or allegations of domestic violence committed or allegedly committed by a sworn employee of an agency;

.. Provide to a sworn employee, upon the request of the sworn employee or when the sworn employee has been alleged to have committed an act of domestic violence, information on programs under RCW 26.50.150;

.. Provide for the mandatory, immediate reporting by employees when an employee becomes aware of an allegation of domestic violence committed or allegedly committed by a sworn employee of the agency employing the sworn employee;

.. Provide procedures to address reporting by an employee who is the victim of domestic violence committed or allegedly committed by a sworn employee of an agency;

.. Provide for the mandatory, immediate self-reporting by a sworn employee to his or her employing agency when an agency in any jurisdiction has responded to a domestic violence call in which the sworn employee committed or allegedly committed an act of domestic violence;

.. Provide for the mandatory, immediate self-reporting by a sworn employee to his or her employing agency if the employee is currently being investigated for an allegation of child abuse or neglect or has previously been investigated for founded allegations of child abuse or neglect, or is currently or has previously been subject to any order under RCW 26.44.063, this chapter, chapter 10.14 or 26.50 RCW, or any equivalent order issued by another state or tribal court;

.. Provide for the performance of prompt separate and impartial administrative and criminal investigations of acts or allegations of domestic violence committed or allegedly committed by a sworn employee of an agency;

.. Provide for appropriate action to be taken during an administrative or criminal investigation of acts or allegations of domestic violence committed or allegedly committed by a sworn employee of an agency. The policy shall provide procedures to address, in a manner consistent with applicable law and the agency's ability to maintain public safety within its jurisdiction, whether to relieve the sworn employee of agency-issued weapons and other agency-issued property and whether to suspend the sworn employee's power of arrest or other police powers pending resolution of any investigation;

.. Provide for prompt and appropriate discipline or sanctions when, after an agency investigation, it is determined that a sworn employee has committed an act of domestic violence;

.. Provide that, when there has been an allegation of domestic violence committed or allegedly committed by a sworn employee, the agency immediately make available to the alleged victim the following information:

... The agency's written policy on domestic violence committed or allegedly committed by sworn employees;

... Information, including but not limited to contact information, about public and private nonprofit domestic violence advocates and services; and

... Information regarding relevant confidentiality policies related to the victim's information;

.. Provide procedures for the timely response, consistent with chapters 42.56 and 10.97 RCW, to an alleged victim's inquiries into the status of the administrative investigation and the procedures the agency will follow in an investigation of domestic violence committed or allegedly committed by a sworn employee;

.. Provide procedures requiring an agency to immediately notify the employing agency of a sworn employee when the notifying agency becomes aware of acts or allegations of domestic violence committed or allegedly committed by the sworn employee within the jurisdiction of the notifying agency; and

.. Provide procedures for agencies to access and share domestic violence training within their jurisdiction and with other jurisdictions.

. By June 1, 2005, every agency shall adopt and implement a written policy on domestic violence committed or allegedly committed by sworn employees of the agency that meet the minimum standards specified in this section. In lieu of developing its own policy, the agency may adopt the model policy developed by the association under this section. In developing its own policy, or before adopting the model policy, the agency shall consult public and private nonprofit domestic violence advocates and any other organizations and professions the agency finds appropriate.

. [Empty]
.. Except as provided in this section, not later than June 30, 2006, every sworn employee of an agency shall be trained by the agency on the agency's policy required under this section.

.. Sworn employees hired by an agency on or after March 1, 2006, shall, within six months of beginning employment, be trained by the agency on the agency's policy required under this section. 

. [Empty]
.. By June 1, 2005, every agency shall provide a copy of its policy developed under this section to the association and shall provide a statement notifying the association of whether the agency has complied with the training required under this section. The copy and statement shall be provided in electronic format unless the agency is unable to do so. The agency shall provide the association with any revisions to the policy upon adoption.

.. The association shall maintain a copy of each agency's policy and shall provide to the governor and legislature not later than January 1, 2006, a list of those agencies that have not developed and submitted policies and those agencies that have not stated their compliance with the training required under this section.

.. The association shall, upon request and within its resources, provide technical assistance to agencies in developing their policies.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1133-S.SL.pdf?cite=2005%20c%20274%20§%20209[2005 c 274 § 209]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6161-S.SL.pdf?cite=2004%20c%2018%20§%203[2004 c 18 § 3]; ]

== 10.99.100 - Sentencing—Factors—Defendant's criminal history.
. In sentencing for a crime of domestic violence as defined in this chapter, courts of limited jurisdiction shall consider, among other factors, whether:

.. The defendant suffered a continuing pattern of coercion, control, or abuse by the victim of the offense and the offense is a response to that coercion, control, or abuse;

.. The offense was part of an ongoing pattern of psychological, physical, or sexual abuse of a victim or multiple victims manifested by multiple incidents over a prolonged period of time; and

.. The offense occurred within sight or sound of the victim's or the offender's minor children under the age of eighteen years.

. [Empty]
.. In sentencing for a crime of domestic violence as defined in this chapter, the prosecutor shall provide for the court's review:

... The defendant's criminal history, if any, that occurred in Washington or any other state;

... If available, the defendant's prior criminal history that occurred in any tribal jurisdiction; and

... The defendant's individual order history.

.. For the purposes of (a) of this subsection, criminal history includes all previous convictions and orders of deferred prosecution, as reported through the judicial information system or otherwise available to the court or prosecutor, current to within the period specified in (c) of this subsection before the date of sentencing.

.. The periods applicable to previous convictions and orders of deferred prosecution are: 

... One working day, in the case of previous actions of courts that fully participate in the state judicial information system; and

... Seven calendar days, in the case of previous actions of courts that do not fully participate in the judicial information system. For the purposes of this subsection, "fully participate" means regularly providing records to and receiving records from the system by electronic means on a daily basis.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2777-S.SL.pdf?cite=2010%20c%20274%20§%20404[2010 c 274 § 404]; ]

== 10.99.800 - Domestic violence risk assessment work group—Report to legislature. (Expires June 30, 2021.)
. The Washington domestic violence risk assessment work group is established to study how and when risk assessment can best be used to improve the response to domestic violence offenders and victims and find effective strategies to reduce domestic violence homicides, serious injuries, and recidivism that are a result of domestic violence incidents in Washington state.

. [Empty]
.. The Washington state gender and justice commission, in collaboration with the Washington state coalition against domestic violence and the Washington State University criminal justice program, shall coordinate the work group and provide staff support.

.. The work group must include a representative from each of the following organizations:

... The Washington state gender and justice commission;

... The department of corrections;

... The department of social and health services;

... The Washington association of sheriffs and police chiefs;

.. The superior court judges' association;

.. The district and municipal court judges' association;

.. The Washington state association of counties;

.. The Washington association of prosecuting attorneys;

... The Washington defender association;

.. The Washington association of criminal defense lawyers;

.. The Washington state association of cities;

.. The Washington state coalition against domestic violence;

.. The Washington state office of civil legal aid; and

.. The family law section of the Washington state bar association.

.. The work group must additionally include representation from:

... Treatment providers;

... City law enforcement;

... County law enforcement;

... Court administrators; and

.. Domestic violence victims or family members of a victim.

. [Empty]
.. For its initial report in 2018, the work group shall research, review, and make recommendations on the following:

... How to best develop and use risk assessment in domestic violence response utilizing available research and Washington state data;

... Providing effective strategies for incorporating risk assessment in domestic violence response to reduce deaths, serious injuries, and recidivism due to domestic violence;

... Promoting access to domestic violence risk assessment for advocates, police, prosecutors, corrections, and courts to improve domestic violence response;

... Whether or how risk assessment could be used as an alternative to mandatory arrest in domestic violence;

.. Whether or how risk assessment could be used in bail determinations in domestic violence cases, and in civil protection order hearings;

.. Whether or how offender risk, needs, and responsivity could be used in determining eligibility for diversion, sentencing alternatives, and treatment options;

.. Whether or how victim risk, needs, and responsivity could be used in improving domestic violence response;

.. Whether or how risk assessment can improve prosecution and encourage prosecutors to aggressively enforce domestic violence laws; and

... Encouraging private sector collaboration.

.. The work group shall compile its findings and recommendations into an initial report and provide its report to the appropriate committees of the legislature and governor by June 30, 2018.

. [Empty]
.. For its report in 2019, the work group shall:

... Research, review, and make recommendations on whether laws mandating arrest in cases of domestic violence should be amended and whether alternative arrest statutes should incorporate domestic violence risk assessment in domestic violence response to improve the response to domestic violence, and what training for law enforcement would be needed to implement an alternative to mandatory arrest;

... Research, review, and make recommendations on how prior recommendations of the work group should be implemented in order to promote effective strategies to reduce domestic violence in Washington state;

... Monitor, evaluate, and provide recommendations on the development and use of the risk assessment tool under RCW 9.94A.502; and

... Provide recommendations on other items deemed appropriate by the work group.

.. The work group shall compile its findings and recommendations into a final report and provide its report to the appropriate committees of the legislature and governor by June 30, 2020.

. The work group must operate within existing funds.

. This section expires June 30, 2021.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1517-S2.SL.pdf?cite=2019%20c%20263%20§%20803[2019 c 263 § 803]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1163-S2.SL.pdf?cite=2017%20c%20272%20§%208[2017 c 272 § 8]; ]

== 10.99.801 - Domestic violence perpetrator treatment work group—Report to legislature. (Expires June 30, 2021.)
. The administrative office of the courts shall, through the Washington state gender and justice commission of the supreme court, convene a work group to address the issue of domestic violence perpetrator treatment and the role of certified perpetrator treatment programs in holding domestic violence perpetrators accountable.

. The work group must include a representative for each of the following organizations or interests: Superior court judges, district court judges, municipal court judges, court probation officers, prosecuting attorneys, defense attorneys, civil legal aid attorneys, domestic violence victim advocates, domestic violence perpetrator treatment providers, the department of social and health services, the department of corrections, the Washington state institute for public policy, and the University of Washington evidence based practice institute. At least two domestic violence perpetrator treatment providers must be represented as members of the work group.

. [Empty]
.. For its initial report in 2018, the work group shall: (i) Review laws, regulations, and court and agency practices pertaining to domestic violence perpetrator treatment used in civil and criminal contexts, including criminal domestic violence felony and misdemeanor offenses, family law, child welfare, and protection orders; (ii) consider the development of a universal diagnostic evaluation tool to be used by treatment providers and the department of corrections to assess the treatment needs of domestic violence perpetrators; and (iii) develop recommendations on changes to existing laws, regulations, and court and agency practices to improve victim safety, decrease recidivism, advance treatment outcomes, and increase the courts' confidence in domestic violence perpetrator treatment.

.. The work group shall report its recommendations to the affected entities and the appropriate committees of the legislature no later than June 30, 2018.

. [Empty]
.. For its report in 2019, the work group shall:

... Provide guidance and additional recommendations with respect to how prior recommendations of the work group should be implemented for the purpose of promoting effective strategies to reduce domestic violence in Washington state;

... Monitor, evaluate, and provide recommendations for the implementation of the newly established domestic violence treatment administrative codes;

... Monitor, evaluate, and provide recommendations on the implementation and supervision of domestic violence sentencing alternatives in different counties to promote consistency; and

... Provide recommendations on other items deemed appropriate by the work group.

.. The work group shall report its recommendations to the affected entities and the appropriate committees of the legislature no later than June 30, 2020.

. The work group must operate within existing funds.

. This section expires June 30, 2021.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1517-S2.SL.pdf?cite=2019%20c%20263%20§%20802[2019 c 263 § 802]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1163-S2.SL.pdf?cite=2017%20c%20272%20§%207[2017 c 272 § 7]; ]

== 10.99.901 - Construction—Chapter applicable to state registered domestic partnerships—2009 c 521.
For the purposes of this chapter, the terms spouse, marriage, marital, husband, wife, widow, widower, next of kin, and family shall be interpreted as applying equally to state registered domestic partnerships or individuals in state registered domestic partnerships as well as to marital relationships and married persons, and references to dissolution of marriage shall apply equally to state registered domestic partnerships that have been terminated, dissolved, or invalidated, to the extent that such interpretation does not conflict with federal law. Where necessary to implement chapter 521, Laws of 2009, gender-specific terms such as husband and wife used in any statute, rule, or other law shall be construed to be gender neutral, and applicable to individuals in state registered domestic partnerships.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%2029[2009 c 521 § 29]; ]

