= 10.58 - Evidence.
:toc:

== 10.58.010 - Rules—Generally.
The rules of evidence in civil actions, so far as practicable, shall be applied to criminal prosecutions.

[ Code 1881 § 1071; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20234%20§%20233[1873 p 234 § 233]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20117%20§%2097[1854 p 117 § 97]; RRS § 2152; ]

== 10.58.020 - Presumption of innocence—Conviction of lowest degree, when.
Every person charged with the commission of a crime shall be presumed innocent until the contrary is proved by competent evidence beyond a reasonable doubt; and when an offense has been proved against him or her, and there exists a reasonable doubt as to which of two or more degrees he or she is guilty, he or she shall be convicted only of the lowest.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%201053[2010 c 8 § 1053]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%2056[1909 c 249 § 56]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c28.pdf?cite=1891%20c%2028%20§%2091[1891 c 28 § 91]; Code 1881 § 767; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%2076%20§%203[1854 p 76 § 3]; RRS § 2308; ]

== 10.58.030 - Confession as evidence.
The confession of a defendant made under inducement, with all the circumstances, may be given as evidence against him or her, except when made under the influence of fear produced by threats; but a confession made under inducement is not sufficient to warrant a conviction without corroborating testimony.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%201054[2010 c 8 § 1054]; Code 1881 § 1070; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20234%20§%20232[1873 p 234 § 232]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20117%20§%2096[1854 p 117 § 96]; RRS § 2151; ]

== 10.58.035 - Statement of defendant—Admissibility.
. In criminal and juvenile offense proceedings where independent proof of the corpus delicti is absent, and the alleged victim of the crime is dead or incompetent to testify, a lawfully obtained and otherwise admissible confession, admission, or other statement of the defendant shall be admissible into evidence if there is substantial independent evidence that would tend to establish the trustworthiness of the confession, admission, or other statement of the defendant.

. In determining whether there is substantial independent evidence that the confession, admission, or other statement of the defendant is trustworthy, the court shall consider, but is not limited to:

.. Whether there is any evidence corroborating or contradicting the facts set out in the statement, including the elements of the offense;

.. The character of the witness reporting the statement and the number of witnesses to the statement;

.. Whether a record of the statement was made and the timing of the making of the record in relation to the making of the statement; and/or

.. The relationship between the witness and the defendant.

. Where the court finds that the confession, admission, or other statement of the defendant is sufficiently trustworthy to be admitted, the court shall issue a written order setting forth the rationale for admission.

. Nothing in this section may be construed to prevent the defendant from arguing to the jury or judge in a bench trial that the statement is not trustworthy or that the evidence is otherwise insufficient to convict.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1427.SL.pdf?cite=2003%20c%20179%20§%201[2003 c 179 § 1]; ]

== 10.58.038 - Polygraph examinations—Victims of alleged sex offenses.
A law enforcement officer, prosecuting attorney, or other government official may not ask or require a victim of an alleged sex offense to submit to a polygraph examination or other truth telling device as a condition for proceeding with the investigation of the offense. The refusal of a victim to submit to a polygraph examination or other truth telling device shall not by itself prevent the investigation, charging, or prosecution of the offense. For the purposes of this section, "sex offense" is any offense under chapter 9A.44 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1520.SL.pdf?cite=2007%20c%20202%20§%201[2007 c 202 § 1]; ]

== 10.58.040 - Intent to defraud.
Whenever an intent to defraud shall be made an element of an offense, it shall be sufficient if an intent appears to defraud any person, association or body politic or corporate whatsoever.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%2040[1909 c 249 § 40]; RRS § 2292; ]

== 10.58.060 - Ownership—Proof of.
In the prosecution of any offense committed upon, or in relation to, or in any way affecting any real estate, or any offense committed in stealing, embezzling, destroying, injuring, or fraudulently receiving or concealing any money, goods, or other personal estate, it shall be sufficient, and shall not be deemed a variance, if it be proved on trial that at the time when such offense was committed, either the actual or constructive possession, or the general or special property in the whole, or any part of such real or personal estate, was in the person or community alleged in the indictment or other accusation to be the owner thereof.

[ Code 1881 § 963; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%2099%20§%20133[1854 p 99 § 133]; RRS § 2156; ]

== 10.58.080 - View of place of crime permissible.
The court may order a view by any jury impaneled to try a criminal case.

[ Code 1881 § 1090; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20237%20§%20251[1873 p 237 § 251]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20120%20§%20115[1854 p 120 § 115]; RRS § 2160; ]

== 10.58.090 - Sex offenses—Admissibility.
. In a criminal action in which the defendant is accused of a sex offense, evidence of the defendant's commission of another sex offense or sex offenses is admissible, notwithstanding Evidence Rule 404(b), if the evidence is not inadmissible pursuant to Evidence Rule 403.

. In a case in which the state intends to offer evidence under this rule, the attorney for the state shall disclose the evidence to the defendant, including statements of witnesses or a summary of the substance of any testimony that is expected to be offered, at least fifteen days before the scheduled date of trial or at such later time as the court may allow for good cause.

. This section shall not be construed to limit the admission or consideration of evidence under any other evidence rule.

. For purposes of this section, "sex offense" means:

.. Any offense defined as a sex offense by RCW 9.94A.030;

.. Any violation under RCW 9A.44.096 (sexual misconduct with a minor in the second degree); and

.. Any violation under RCW 9.68A.090 (communication with a minor for immoral purposes).

. For purposes of this section, uncharged conduct is included in the definition of "sex offense."

. When evaluating whether evidence of the defendant's commission of another sexual offense or offenses should be excluded pursuant to Evidence Rule 403, the trial judge shall consider the following factors:

.. The similarity of the prior acts to the acts charged;

.. The closeness in time of the prior acts to the acts charged;

.. The frequency of the prior acts;

.. The presence or lack of intervening circumstances;

.. The necessity of the evidence beyond the testimonies already offered at trial;

.. Whether the prior act was a criminal conviction;

.. Whether the probative value is substantially outweighed by the danger of unfair prejudice, confusion of the issues, or misleading the jury, or by considerations of undue delay, waste of time, or needless presentation of cumulative evidence; and

.. Other facts and circumstances.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6933-S.SL.pdf?cite=2008%20c%2090%20§%202[2008 c 90 § 2]; ]

