= 10.34 - Fugitives of this state.
:toc:

== 10.34.010 - Officer may arrest defendant in any county.
If any person against whom a warrant may be issued for an alleged offense, committed in any county, shall either before or after the issuing of such warrant, escape from, or be out of the county, the sheriff or other officer to whom such warrant may be directed, may pursue and apprehend the party charged, in any county in this state, and for that purpose may command aid, and exercise the same authority as in his or her own county.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%201033[2010 c 8 § 1033]; Code 1881 § 1922; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20394%20§%20220[1873 p 394 § 220]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20107%20§%2028[1854 p 107 § 28]; RRS § 1950; ]

== 10.34.020 - Escape—Retaking prisoner—Authority.
If a person arrested escape or be rescued, the person from whose custody he or she made his or her escape, or was rescued, may immediately pursue and retake him or her at any time, and within any place in the state. To retake the person escaping or rescued, the person pursuing has the same power to command assistance as given in cases of arrest.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%201034[2010 c 8 § 1034]; Code 1881 § 1032; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20229%20§%20212[1873 p 229 § 212]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20114%20§%2076[1854 p 114 § 76]; RRS § 2085; ]

== 10.34.030 - Escape—Retaking in foreign state—Extradition agents.
The governor may appoint agents to make a demand upon the executive authority of any state or territory for the surrender of any fugitive from justice, or any other person charged with a felony or any other crime in this state. Whenever an application shall be made to the governor for the appointment of an agent he or she may require the official submitting the same to provide whatever information is necessary prior to approval of the application.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%201035[2010 c 8 § 1035]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5975.SL.pdf?cite=1993%20c%20442%20§%201[1993 c 442 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c91.pdf?cite=1967%20c%2091%20§%202[1967 c 91 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c28.pdf?cite=1891%20c%2028%20§%2098[1891 c 28 § 98]; Code 1881 § 971; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20217%20§%20157[1873 p 217 § 157]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20102%20§%205[1854 p 102 § 5]; RRS § 2241; ]

