= 10.05 - Deferred prosecution—Courts of limited jurisdiction.
:toc:

== 10.05.010 - Petition—Eligibility.
. In a court of limited jurisdiction a person charged with a misdemeanor or gross misdemeanor may petition the court to be considered for a deferred prosecution program. The petition shall be filed with the court at least seven days before the date set for trial but, upon a written motion and affidavit establishing good cause for the delay and failure to comply with this section, the court may waive this requirement subject to the defendant's reimbursement to the court of the witness fees and expenses due for subpoenaed witnesses who have appeared on the date set for trial.

. A person charged with a traffic infraction, misdemeanor, or gross misdemeanor under Title 46 RCW, or a misdemeanor or gross misdemeanor domestic violence offense, shall not be eligible for a deferred prosecution program unless the court makes specific findings pursuant to RCW 10.05.020. A person may not participate in a deferred prosecution program for a traffic infraction, misdemeanor, or gross misdemeanor under Title 46 RCW if he or she has participated in a deferred prosecution program for a prior traffic infraction, misdemeanor, or gross misdemeanor under Title 46 RCW, and a person may not participate in a deferred prosecution program for a misdemeanor or gross misdemeanor domestic violence offense if he or she has participated in a deferred prosecution program for a prior domestic violence offense. Separate offenses committed more than seven days apart may not be consolidated in a single program.

. A person charged with a misdemeanor or a gross misdemeanor under chapter 9A.42 RCW shall not be eligible for a deferred prosecution program unless the court makes specific findings pursuant to RCW 10.05.020. Such person shall not be eligible for a deferred prosecution program more than once.

. A person is not eligible for a deferred prosecution program if the misdemeanor or gross misdemeanor domestic violence offense was originally charged as a felony offense in superior court.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1517-S2.SL.pdf?cite=2019%20c%20263%20§%20701[2019 c 263 § 701]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3254-S2.SL.pdf?cite=2008%20c%20282%20§%2015[2008 c 282 § 15]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2382-S.SL.pdf?cite=2002%20c%20219%20§%206[2002 c 219 § 6]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3089-S2.SL.pdf?cite=1998%20c%20208%20§%201[1998 c 208 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c352.pdf?cite=1985%20c%20352%20§%204[1985 c 352 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982ex1c47.pdf?cite=1982%201st%20ex.s.%20c%2047%20§%2026[1982 1st ex.s. c 47 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c244.pdf?cite=1975%201st%20ex.s.%20c%20244%20§%201[1975 1st ex.s. c 244 § 1]; ]

== 10.05.015 - Statement of availability.
At the time of arraignment a person charged with a violation of RCW 46.61.502 or 46.61.504 or a misdemeanor or gross misdemeanor domestic violence offense may be given a statement by the court that explains the availability, operation, and effects of the deferred prosecution program.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1517-S2.SL.pdf?cite=2019%20c%20263%20§%20702[2019 c 263 § 702]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c352.pdf?cite=1985%20c%20352%20§%205[1985 c 352 § 5]; ]

== 10.05.020 - Requirements of petition—Rights of petitioner—Court findings. (Effective until July 1, 2022.)
. Except as provided in subsection (2) of this section, the petitioner shall allege under oath in the petition that the wrongful conduct charged is the result of or caused by substance use disorders or mental problems or domestic violence behavior problems for which the person is in need of treatment and unless treated the probability of future recurrence is great, along with a statement that the person agrees to pay the cost of a diagnosis and treatment of the alleged problem or problems if financially able to do so. The petition shall also contain a case history and written assessment prepared by an approved substance use disorder treatment program as designated in chapter 71.24 RCW if the petition alleges a substance use disorder, by an approved mental health center if the petition alleges a mental problem, or by a state-certified domestic violence treatment provider pursuant to chapter 26.50 RCW if the petition alleges a domestic violence behavior problem.

. In the case of a petitioner charged with a misdemeanor or gross misdemeanor under chapter 9A.42 RCW, the petitioner shall allege under oath in the petition that the petitioner is the natural or adoptive parent of the alleged victim; that the wrongful conduct charged is the result of parenting problems for which the petitioner is in need of services; that the petitioner is in need of child welfare services under chapter 74.13 RCW to improve his or her parenting skills in order to better provide his or her child or children with the basic necessities of life; that the petitioner wants to correct his or her conduct to reduce the likelihood of harm to his or her minor children; that in the absence of child welfare services the petitioner may be unable to reduce the likelihood of harm to his or her minor children; and that the petitioner has cooperated with the department of social and health services to develop a plan to receive appropriate child welfare services; along with a statement that the person agrees to pay the cost of the services if he or she is financially able to do so. The petition shall also contain a case history and a written service plan from the department of social and health services.

. Before entry of an order deferring prosecution, a petitioner shall be advised of his or her rights as an accused and execute, as a condition of receiving treatment, a statement that contains: (a) An acknowledgment of his or her rights; (b) an acknowledgment and waiver of the right to testify, the right to a speedy trial, the right to call witnesses to testify, the right to present evidence in his or her defense, and the right to a jury trial; (c) a stipulation to the admissibility and sufficiency of the facts contained in the written police report; and (d) an acknowledgment that the statement will be entered and used to support a finding of guilty if the court finds cause to revoke the order granting deferred prosecution. The petitioner shall also be advised that he or she may, if he or she proceeds to trial and is found guilty, be allowed to seek suspension of some or all of the fines and incarceration that may be ordered upon the condition that he or she seek treatment and, further, that he or she may seek treatment from public and private agencies at any time without regard to whether or not he or she is found guilty of the offense charged. He or she shall also be advised that the court will not accept a petition for deferred prosecution from a person who: (i) Sincerely believes that he or she is innocent of the charges; (ii) sincerely believes that he or she does not, in fact, suffer from alcoholism, drug addiction, mental problems, or domestic violence behavior problems; or (iii) in the case of a petitioner charged under chapter 9A.42 RCW, sincerely believes that he or she does not need child welfare services.

. Before entering an order deferring prosecution, the court shall make specific findings that: (a) The petitioner has stipulated to the admissibility and sufficiency of the facts as contained in the written police report; (b) the petitioner has acknowledged the admissibility of the stipulated facts in any criminal hearing on the underlying offense or offenses held subsequent to revocation of the order granting deferred prosecution; (c) the petitioner has acknowledged and waived the right to testify, the right to a speedy trial, the right to call witnesses to testify, the right to present evidence in his or her defense, and the right to a jury trial; and (d) the petitioner's statements were made knowingly and voluntarily. Such findings shall be included in the order granting deferred prosecution.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1517-S2.SL.pdf?cite=2019%20c%20263%20§%20703[2019 c 263 § 703]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1713-S3.SL.pdf?cite=2016%20sp.s.%20c%2029%20§%20525[2016 sp.s. c 29 § 525]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2742-S2.SL.pdf?cite=2010%20c%20269%20§%209[2010 c 269 § 9]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3254-S2.SL.pdf?cite=2008%20c%20282%20§%2016[2008 c 282 § 16]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2382-S.SL.pdf?cite=2002%20c%20219%20§%207[2002 c 219 § 7]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6181.SL.pdf?cite=1996%20c%2024%20§%201[1996 c 24 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c352.pdf?cite=1985%20c%20352%20§%206[1985 c 352 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c244.pdf?cite=1975%201st%20ex.s.%20c%20244%20§%202[1975 1st ex.s. c 244 § 2]; ]

== 10.05.030 - Arraignment continued—Treatment referral. (Effective until July 1, 2022.)
The arraigning judge upon consideration of the petition and with the concurrence of the prosecuting attorney may continue the arraignment and refer such person for a diagnostic investigation and evaluation to:

. An approved substance use disorder treatment program as designated in chapter 71.24 RCW if the petition alleges a substance use disorder;

. An approved mental health center if the petition alleges a mental problem;

. The department of social and health services if the petition is brought under RCW 10.05.020(2); or

. An approved state-certified domestic violence treatment provider pursuant to chapter 26.50 RCW if the petition alleges a domestic violence behavior problem.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1517-S2.SL.pdf?cite=2019%20c%20263%20§%20704[2019 c 263 § 704]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1713-S3.SL.pdf?cite=2016%20sp.s.%20c%2029%20§%20526[2016 sp.s. c 29 § 526]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2382-S.SL.pdf?cite=2002%20c%20219%20§%208[2002 c 219 § 8]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1142.SL.pdf?cite=1999%20c%20143%20§%2042[1999 c 143 § 42]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c244.pdf?cite=1975%201st%20ex.s.%20c%20244%20§%203[1975 1st ex.s. c 244 § 3]; ]

== 10.05.040 - Investigation and examination.
The program to which such person is referred, or the department of social and health services if the petition is brought under RCW 10.05.020(2), shall conduct an investigation and examination to determine:

. Whether the person suffers from the problem described;

. Whether the problem is such that if not treated, or if no child welfare services are provided, there is a probability that similar misconduct will occur in the future;

. Whether extensive and long term treatment is required;

. Whether effective treatment or child welfare services for the person's problem are available; and

. Whether the person is amenable to treatment or willing to cooperate with child welfare services.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1388-S.SL.pdf?cite=2018%20c%20201%20§%209005[2018 c 201 § 9005]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2382-S.SL.pdf?cite=2002%20c%20219%20§%209[2002 c 219 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c352.pdf?cite=1985%20c%20352%20§%207[1985 c 352 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c244.pdf?cite=1975%201st%20ex.s.%20c%20244%20§%204[1975 1st ex.s. c 244 § 4]; ]

== 10.05.050 - Report to court—Recommended treatment plan—Commitment to provide treatment.
. The program, or the department of social and health services if the petition is brought under RCW 10.05.020(2), shall make a written report to the court stating its findings and recommendations after the examination required by RCW 10.05.040. If its findings and recommendations support treatment or the implementation of a child welfare service plan, it shall also recommend a treatment or service plan setting out:

.. The type;

.. Nature;

.. Length;

.. A treatment or service time schedule; and

.. Approximate cost of the treatment or child welfare services.

. In the case of a child welfare service plan, the plan shall be designed in a manner so that a parent who successfully completes the plan will not be likely to withhold the basic necessities of life from his or her child.

. The report with the treatment or service plan shall be filed with the court and a copy given to the petitioner and petitioner's counsel. A copy of the treatment or service plan shall be given to the prosecutor by petitioner's counsel at the request of the prosecutor. The evaluation facility, or the department of social and health services if the petition is brought under RCW 10.05.020(2), making the written report shall append to the report a commitment by the treatment program or the department of social and health services that it will provide the treatment or child welfare services in accordance with this chapter. The facility or the service provider shall agree to provide the court with a statement every three months for the first year and every six months for the second year regarding (a) the petitioner's cooperation with the treatment or child welfare service plan proposed and (b) the petitioner's progress or failure in treatment or child welfare services. These statements shall be made as a declaration by the person who is personally responsible for providing the treatment or services.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1388-S.SL.pdf?cite=2018%20c%20201%20§%209006[2018 c 201 § 9006]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2382-S.SL.pdf?cite=2002%20c%20219%20§%2010[2002 c 219 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c352.pdf?cite=1985%20c%20352%20§%208[1985 c 352 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c244.pdf?cite=1975%201st%20ex.s.%20c%20244%20§%205[1975 1st ex.s. c 244 § 5]; ]

== 10.05.055 - Child welfare services.
Child welfare services provided under chapter 74.13 RCW pursuant to a deferred prosecution ordered under RCW 10.05.060 may not be construed to prohibit the department from providing services or undertaking proceedings pursuant to chapter 13.34 or 26.44 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2382-S.SL.pdf?cite=2002%20c%20219%20§%2012[2002 c 219 § 12]; ]

== 10.05.060 - Procedure upon approval of plan.
If the report recommends treatment, the court shall examine the treatment plan. If it approves the plan and the petitioner agrees to comply with its terms and conditions and agrees to pay the cost thereof, if able to do so, or arrange for the treatment, an entry shall be made upon the person's court docket showing that the person has been accepted for deferred prosecution. A copy of the treatment plan shall be filed with the court. If the charge be one that an abstract of the docket showing the charge, the date of the violation for which the charge was made, and the date of petitioner's acceptance is required to be sent to the department of licensing, an abstract shall be sent, and the department of licensing shall make an entry of the charge and of the petitioner's acceptance for deferred prosecution on the department's driving record of the petitioner. The entry is not a conviction for purposes of Title 46 RCW. Upon receipt of the abstract of the docket, the department shall issue the petitioner a probationary license in accordance with RCW 46.20.355, and the petitioner's driver's license shall be on probationary status for five years from the date of the violation that gave rise to the charge. The department shall maintain the record for ten years from date of entry of the order granting deferred prosecution.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1257.SL.pdf?cite=2009%20c%20135%20§%201[2009 c 135 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6047-S.SL.pdf?cite=1994%20c%20275%20§%2017[1994 c 275 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c250.pdf?cite=1990%20c%20250%20§%2013[1990 c 250 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c352.pdf?cite=1985%20c%20352%20§%209[1985 c 352 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c158.pdf?cite=1979%20c%20158%20§%204[1979 c 158 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c244.pdf?cite=1975%201st%20ex.s.%20c%20244%20§%206[1975 1st ex.s. c 244 § 6]; ]

== 10.05.070 - Arraignment when treatment rejected.
When treatment is either not recommended or not approved by the judge, or the petitioner declines to accept the treatment plan, the petitioner shall be arraigned on the charge.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c352.pdf?cite=1985%20c%20352%20§%2010[1985 c 352 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c244.pdf?cite=1975%201st%20ex.s.%20c%20244%20§%207[1975 1st ex.s. c 244 § 7]; ]

== 10.05.080 - Evidence, uses and admissibility.
If the petition is not approved or is withdrawn before approval, evidence pertaining to or resulting from the petition and/or investigation is inadmissible in any trial on the charges, but shall be available for use after a conviction in determining a sentence.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c352.pdf?cite=1985%20c%20352%20§%2011[1985 c 352 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c244.pdf?cite=1975%201st%20ex.s.%20c%20244%20§%208[1975 1st ex.s. c 244 § 8]; ]

== 10.05.090 - Procedure upon breach of treatment plan.
If a petitioner, who has been accepted for a deferred prosecution, fails or neglects to carry out and fulfill any term or condition of the petitioner's treatment plan or any term or condition imposed in connection with the installation of an interlock or other device under RCW 46.20.720, the facility, center, institution, or agency administering the treatment or the entity administering the use of the device, shall immediately report such breach to the court, the prosecutor, and the petitioner or petitioner's attorney of record, together with its recommendation. The court upon receiving such a report shall hold a hearing to determine whether the petitioner should be removed from the deferred prosecution program. At the hearing, evidence shall be taken of the petitioner's alleged failure to comply with the treatment plan or device installation and the petitioner shall have the right to present evidence on his or her own behalf. The court shall either order that the petitioner continue on the treatment plan or be removed from deferred prosecution. If removed from deferred prosecution, the court shall enter judgment pursuant to RCW 10.05.020 and, if the charge for which the deferred prosecution was granted was a misdemeanor or gross misdemeanor under Title 46 RCW, shall notify the department of licensing of the removal and entry of judgment.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2742-S2.SL.pdf?cite=2010%20c%20269%20§%2010[2010 c 269 § 10]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3254-S2.SL.pdf?cite=2008%20c%20282%20§%2017[2008 c 282 § 17]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1940.SL.pdf?cite=1997%20c%20229%20§%201[1997 c 229 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6047-S.SL.pdf?cite=1994%20c%20275%20§%2018[1994 c 275 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c352.pdf?cite=1985%20c%20352%20§%2012[1985 c 352 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c244.pdf?cite=1975%201st%20ex.s.%20c%20244%20§%209[1975 1st ex.s. c 244 § 9]; ]

== 10.05.100 - Conviction of similar offense.
If a petitioner is subsequently convicted of a similar offense that was committed while the petitioner was in a deferred prosecution program, upon notice the court shall remove the petitioner's docket from the deferred prosecution file and the court shall enter judgment pursuant to RCW 10.05.020.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3089-S2.SL.pdf?cite=1998%20c%20208%20§%202[1998 c 208 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c352.pdf?cite=1985%20c%20352%20§%2013[1985 c 352 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c244.pdf?cite=1975%201st%20ex.s.%20c%20244%20§%2010[1975 1st ex.s. c 244 § 10]; ]

== 10.05.110 - Trial delay not grounds for dismissal.
Delay in bringing a case to trial caused by a petitioner requesting deferred prosecution as provided for in this chapter shall not be grounds for dismissal.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c352.pdf?cite=1985%20c%20352%20§%2014[1985 c 352 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c244.pdf?cite=1975%201st%20ex.s.%20c%20244%20§%2011[1975 1st ex.s. c 244 § 11]; ]

== 10.05.120 - Dismissal of charges.
. Three years after receiving proof of successful completion of the two-year treatment program, and following proof to the court that the petitioner has complied with the conditions imposed by the court following successful completion of the two-year treatment program, but not before five years following entry of the order of deferred prosecution pursuant to a petition brought under RCW 10.05.020(1), the court shall dismiss the charges pending against the petitioner.

. When a deferred prosecution is ordered pursuant to a petition brought under RCW 10.05.020(2) and the court has received proof that the petitioner has successfully completed the child welfare service plan, or the plan has been terminated because the alleged victim has reached his or her majority and there are no other minor children in the home, the court shall dismiss the charges pending against the petitioner: PROVIDED, That in any case where the petitioner's parental rights have been terminated with regard to the alleged victim due to abuse or neglect that occurred during the pendency of the deferred prosecution, the termination shall be per se evidence that the petitioner did not successfully complete the child welfare service plan.

. When a deferred prosecution is ordered for a petition brought under RCW 10.05.020(1) involving a domestic violence behavior problem and the court has received proof that the petitioner has successfully completed the domestic violence treatment plan, the court shall dismiss the charges pending against the petitioner.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1517-S2.SL.pdf?cite=2019%20c%20263%20§%20705[2019 c 263 § 705]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5396-S.SL.pdf?cite=2003%20c%20220%20§%201[2003 c 220 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2382-S.SL.pdf?cite=2002%20c%20219%20§%2014[2002 c 219 § 14]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3089-S2.SL.pdf?cite=1998%20c%20208%20§%203[1998 c 208 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6047-S.SL.pdf?cite=1994%20c%20275%20§%2019[1994 c 275 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c352.pdf?cite=1985%20c%20352%20§%2015[1985 c 352 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c165.pdf?cite=1983%20c%20165%20§%2045[1983 c 165 § 45]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c244.pdf?cite=1975%201st%20ex.s.%20c%20244%20§%2012[1975 1st ex.s. c 244 § 12]; ]

== 10.05.130 - Services provided for indigent defendants.
Funds shall be appropriated from the fines and forfeitures of the court to provide investigation, examination, report and treatment plan for any indigent person who is unable to pay the cost of any program of treatment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c244.pdf?cite=1975%201st%20ex.s.%20c%20244%20§%2013[1975 1st ex.s. c 244 § 13]; ]

== 10.05.140 - Conditions of granting.
. As a condition of granting a deferred prosecution petition, the court shall order that the petitioner shall not operate a motor vehicle upon the public highways without a valid operator's license and proof of liability insurance. The amount of liability insurance shall be established by the court at not less than that established by RCW 46.29.490. As a condition of granting a deferred prosecution petition on any alcohol-dependency based case, the court shall also order the installation of an ignition interlock under RCW 46.20.720. The required periods of use of the interlock shall be not less than the periods provided for in RCW 46.20.720. As a condition of granting a deferred prosecution petition, the court may order the petitioner to make restitution and to pay costs as defined in RCW 10.01.160. To help ensure continued sobriety and reduce the likelihood of reoffense, the court may order reasonable conditions during the period of the deferred prosecution including, but not limited to, attendance at self-help recovery support groups for alcoholism or drugs, complete abstinence from alcohol and all nonprescribed mind-altering drugs, periodic urinalysis or breath analysis, and maintaining law-abiding behavior. The court may terminate the deferred prosecution program upon violation of the deferred prosecution order.

. As a condition of granting a deferred prosecution petition for a case involving a domestic violence behavior problem:

.. The court shall order the petitioner not to possess firearms and order the petitioner to surrender firearms under RCW 9.41.800; and

.. The court may order the petitioner to make restitution and to pay costs as defined in RCW 10.01.160. In addition, to help ensure continued sobriety and reduce the likelihood of reoffense in co-occurring domestic violence and substance abuse or mental health cases, the court may order reasonable conditions during the period of the deferred prosecution including, but not limited to, attendance at self-help recovery support groups for alcoholism or drugs, complete abstinence from alcohol and all nonprescribed mind-altering drugs, periodic urinalysis or breath analysis, and maintaining law-abiding behavior. The court may terminate the deferred prosecution program upon violation of the deferred prosecution order.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1517-S2.SL.pdf?cite=2019%20c%20263%20§%20706[2019 c 263 § 706]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2700-S.SL.pdf?cite=2016%20c%20203%20§%2011[2016 c 203 § 11]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5912-S2.SL.pdf?cite=2013%202nd%20sp.s.%20c%2035%20§%2021[2013 2nd sp.s. c 35 § 21]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1789-S2.SL.pdf?cite=2011%20c%20293%20§%208[2011 c 293 § 8]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2660-S.SL.pdf?cite=2004%20c%2095%20§%201[2004 c 95 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5396-S.SL.pdf?cite=2003%20c%20220%20§%202[2003 c 220 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5399-S.SL.pdf?cite=1999%20c%20331%20§%204[1999 c 331 § 4]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1940.SL.pdf?cite=1997%20c%20229%20§%202[1997 c 229 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1189-S.SL.pdf?cite=1991%20c%20247%20§%201[1991 c 247 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c352.pdf?cite=1985%20c%20352%20§%2016[1985 c 352 § 16]; ]

== 10.05.150 - Alcoholism program requirements.
A deferred prosecution program for alcoholism shall be for a two-year period and shall include, but not be limited to, the following requirements:

. Total abstinence from alcohol and all other nonprescribed mind-altering drugs;

. Participation in an intensive inpatient or intensive outpatient program in a state-approved substance use disorder treatment program;

. Participation in a minimum of two meetings per week of an alcoholism self-help recovery support group, as determined by the assessing agency, for the duration of the treatment program;

. Participation in an alcoholism self-help recovery support group, as determined by the assessing agency, from the date of court approval of the plan to entry into intensive treatment;

. Not less than weekly approved outpatient counseling, group or individual, for a minimum of six months following the intensive phase of treatment;

. Not less than monthly outpatient contact, group or individual, for the remainder of the two-year deferred prosecution period;

. The decision to include the use of prescribed drugs, including disulfiram, as a condition of treatment shall be reserved to the treating facility and the petitioner's physician;

. All treatment within the purview of this section shall occur within or be approved by a state-approved substance use disorder treatment program as described in *chapter 70.96A RCW;

. Signature of the petitioner agreeing to the terms and conditions of the treatment program.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1713-S3.SL.pdf?cite=2016%20sp.s.%20c%2029%20§%20527[2016 sp.s. c 29 § 527]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1142.SL.pdf?cite=1999%20c%20143%20§%2043[1999 c 143 § 43]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c352.pdf?cite=1985%20c%20352%20§%2017[1985 c 352 § 17]; ]

== 10.05.155 - Deferred prosecution program for domestic violence behavior—Requirements.
A deferred prosecution program for domestic violence behavior, or domestic violence co-occurring with substance abuse or mental health, must include, but is not limited to, the following requirements:

. Completion of a risk assessment;

. Participation in the level of treatment recommended by the program as outlined in the current treatment plan;

. Compliance with the contract for treatment;

. Participation in any ancillary or co-occurring treatments that are determined to be necessary for the successful completion of the domestic violence intervention treatment including, but not limited to, mental health or substance use treatment;

. Domestic violence intervention treatment within the purview of this section to be completed with a state-certified domestic violence intervention treatment program;

. Signature of the petitioner agreeing to the terms and conditions of the treatment program;

. Proof of compliance with any active order to surrender weapons issued in this program or related civil protection orders or no-contact orders.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1517-S2.SL.pdf?cite=2019%20c%20263%20§%20708[2019 c 263 § 708]; ]

== 10.05.160 - Appeal of deferred prosecution order.
The prosecutor may appeal an order granting deferred prosecution on any or all of the following grounds:

. Prior deferred prosecution has been granted to the defendant;

. For a present petition alleging a domestic violence behavior problem, a prior stipulated order of continuance has been granted to the defendant;

. Failure of the court to obtain proof of insurance or a treatment plan conforming to the requirements of this chapter;

. Failure of the court to comply with the requirements of RCW 10.05.100;

. Failure of the evaluation facility to provide the information required in RCW 10.05.040 and 10.05.050, if the defendant has been referred to the facility for treatment. If an appeal on such basis is successful, the trial court may consider the use of another treatment program;

. Failure of the court to order the installation of an ignition interlock or other device under RCW 10.05.140.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1517-S2.SL.pdf?cite=2019%20c%20263%20§%20707[2019 c 263 § 707]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2742-S2.SL.pdf?cite=2010%20c%20269%20§%2011[2010 c 269 § 11]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3254-S2.SL.pdf?cite=2008%20c%20282%20§%2019[2008 c 282 § 19]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1142.SL.pdf?cite=1999%20c%20143%20§%2044[1999 c 143 § 44]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3089-S2.SL.pdf?cite=1998%20c%20208%20§%204[1998 c 208 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c352.pdf?cite=1985%20c%20352%20§%2018[1985 c 352 § 18]; ]

== 10.05.170 - Supervision as condition—Levy of assessment.
As a condition of granting deferred prosecution, the court may order supervision of the petitioner during the period of deferral and may levy a monthly assessment upon the petitioner as provided in RCW 10.64.120. In a jurisdiction with a probation department, the court may appoint the probation department to supervise the petitioner. In a jurisdiction without a probation department, the court may appoint an appropriate person or agency to supervise the petitioner. A supervisor appointed under this section shall be required to do at least the following:

. If the charge for which deferral is granted relates to operation of a motor vehicle, at least once every six months request from the department of licensing an abstract of the petitioner's driving record; and

. At least once every month make contact with the petitioner or with any agency to which the petitioner has been directed for treatment as a part of the deferral.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1189-S.SL.pdf?cite=1991%20c%20247%20§%202[1991 c 247 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c352.pdf?cite=1985%20c%20352%20§%2019[1985 c 352 § 19]; ]

== 10.05.180 - Failure to register vehicle, aircraft, or vessel—Deferral program—Exception—Fines.
. Any county may set up a deferral program for persons who receive a citation for failing to register a vehicle, aircraft, or vessel under RCW 46.16A.030, 47.68.255, or 88.02.400. Under the deferral program:

.. If the person has received a criminal citation for failure to register a vehicle under RCW 46.16A.030, an aircraft under RCW 47.68.255, or a vessel under RCW 88.02.400, the defendant may petition the court for a deferred prosecution conditioned upon the defendant completing the criteria in (b) of this subsection within ninety days of the court granting the deferral.

.. To be eligible for a deferred prosecution under (a) of this subsection, the court shall dismiss the charge if the court receives satisfactory proof within ninety days that the person:

... Has paid a five hundred dollar fine;

... Has a valid Washington state driver's license; and

... Has registered the vehicle, aircraft, or vessel that was the subject of the citation.

.. Before entering an order deferring prosecution, the court shall make specific findings that: (i) The petitioner has stipulated to the admissibility and sufficiency of the facts as contained in the written police report; (ii) the petitioner has acknowledged the admissibility of the stipulated facts in any criminal hearing on the underlying offense or offenses held subsequent to revocation of the order granting deferred prosecution; (iii) the petitioner has acknowledged and waived the right to testify, the right to a speedy trial, the right to call witnesses to testify, the right to present evidence in his or her defense, and the right to a jury trial; and (iv) the petitioner's statements were made knowingly and voluntarily. Such findings shall be included in the order granting deferred prosecution.

.. If the defendant successfully completes the conditions required under the deferred prosecution, the court shall dismiss the charges pending against the defendant.

.. If the court finds that the defendant has not successfully completed the conditions required under the deferred prosecution, the court shall remove the defendant from deferred prosecution and enter a judgment.

. The deferral program described in this section does not apply to persons who have received a previous conviction or deferral for failing to register a vehicle under RCW 46.16A.030, an aircraft under RCW 47.68.255, or a vessel under RCW 88.02.400.

. Fines generated pursuant to the deferral program established in subsection (1) of this section shall be used by the county for the purpose of enforcement and prosecution of registration requirements under RCW 46.16A.030, 47.68.250, or 88.02.550.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5362-S.SL.pdf?cite=2019%20c%20459%20§%202[2019 c 459 § 2]; ]

== 10.05.190 - Deferred finding program—Failure to register vehicle, aircraft, or vessel.
Any county may set up a deferred finding program for persons who receive a citation for failing to register a vehicle under RCW 46.16A.030, an aircraft under RCW 47.68.255, or a vessel under RCW 88.02.400. Upon receipt of proof satisfactory to the prosecuting attorney's office with jurisdiction over the offense, which shall include payment of a five hundred dollar fine, that the person cited has a valid Washington state driver's license, and that the person cited has registered the vehicle, aircraft, or vessel that was the subject of the citation in Washington state, the citation must be dismissed. If receipt of proof does not occur within ninety days of the citation, the prosecuting attorney must seek the full penalty available for the citation. Fines generated pursuant to this program shall be used by the county for the purpose of enforcement and prosecution of registration requirements under RCW 46.16A.030, 47.68.255, or 88.02.400. This section applies to persons who have never received a previous citation or participated in a program of deferred finding for failing to register a vehicle under RCW 46.16A.030, an aircraft under RCW 47.68.255, or a vessel under RCW 88.02.400.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=2019%20c%20423%20§%20202[2019 c 423 § 202]; ]

