= 10.43 - Former acquittal or conviction.
:toc:

== 10.43.020 - Offense embraces lower degree and included offenses.
When the defendant has been convicted or acquitted upon an indictment or information of an offense consisting of different degrees, the conviction or acquittal shall be a bar to another indictment or information for the offense charged in the former, or for any lower degree of that offense, or for an offense necessarily included therein.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c28.pdf?cite=1891%20c%2028%20§%2074[1891 c 28 § 74]; Code 1881 § 1096; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20238%20§%20257[1873 p 238 § 257]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20120%20§%20121[1854 p 120 § 121]; RRS § 2166; ]

== 10.43.030 - Conviction or acquittal in other county.
Whenever, upon the trial of any person for a crime, it shall appear that the defendant has already been acquitted or convicted upon the merits, of the same crime, in a court having jurisdiction of such offense in another county of this state, such former acquittal or conviction is a sufficient defense.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%2020[1909 c 249 § 20]; RRS § 2272; ]

== 10.43.040 - Foreign conviction or acquittal.
Whenever, upon the trial of any person for a crime, it appears that the offense was committed in another state or country, under such circumstances that the courts of this state had jurisdiction thereof, and that the defendant has already been acquitted or convicted upon the merits, in a judicial proceeding conducted under the criminal laws of such state or country, founded upon the act or omission with respect to which he or she is upon trial, such former acquittal or conviction is a sufficient defense. Nothing in this section affects or prevents a prosecution in a court of this state of any person who has received administrative or nonjudicial punishment, civilian or military, in another state or country based upon the same act or omission.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%201042[2010 c 8 § 1042]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1067.SL.pdf?cite=1999%20c%20141%20§%201[1999 c 141 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%2019[1909 c 249 § 19]; RRS § 2271; ]

== 10.43.050 - Acquittal, when a bar.
No order of dismissal or directed verdict of not guilty on the ground of a variance between the indictment or information and the proof, or on the ground of any defect in such indictment or information, shall bar another prosecution for the same offense. Whenever a defendant shall be acquitted or convicted upon an indictment or information charging a crime consisting of different degrees, he or she cannot be proceeded against or tried for the same crime in another degree, nor for an attempt to commit such crime, or any degree thereof.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%201043[2010 c 8 § 1043]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%2064[1909 c 249 § 64]; Code 1881 § 769; RRS § 2316; ]

