= 10.85 - Rewards.
:toc:

== 10.85.030 - Rewards by counties, cities, towns, port commissions authorized.
The legislative authority of any county in the state, a port commission, or the governing body of a city or town, when in its opinion the public good requires it, is hereby authorized to offer and pay a suitable reward to any person or persons for information leading to:

.. The arrest of a specified person or persons convicted of or charged with any criminal offense; or

.. The arrest and conviction of a person or persons committing a specified criminal offense.

In the event of crimes against county, port district, city, or town property, including but not limited to road signs, vehicles, buildings, or any other type of county, port district, city, or town property, the legislative authority of any county, a port commission, or the governing body of a city or town may offer and pay a suitable reward to any person or persons who shall furnish information leading to the arrest and conviction of any person of any offense against this county, port district, city, or town property, including but not limited to those offenses set forth in RCW 9A.48.070 through 9A.48.090, whether or not the offense is a felony, gross misdemeanor, or misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c185.pdf?cite=1986%20c%20185%20§%201[1986 c 185 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c211.pdf?cite=1981%20c%20211%20§%201[1981 c 211 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c53.pdf?cite=1979%20ex.s.%20c%2053%20§%201[1979 ex.s. c 53 § 1]; 1975-'76 2nd ex.s. c 25 § 1; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1886%20p%20124%20§%201[1886 p 124 § 1]; RRS § 2249; ]

== 10.85.040 - Conflicting claims.
When more than one claimant applies for the payment of any reward, offered by any county legislative authority, board of commissioners of a port district, or city or town governing body, the county legislative authority, board of commissioners of a port district, or city or town governing body shall determine to whom the same shall be paid, and if to more than one person, in what proportion to each; and their determination shall be final and conclusive.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c185.pdf?cite=1986%20c%20185%20§%202[1986 c 185 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c53.pdf?cite=1979%20ex.s.%20c%2053%20§%202[1979 ex.s. c 53 § 2]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1886%20p%20124%20§%203[1886 p 124 § 3]; RRS § 2251; ]

== 10.85.050 - Payment of rewards.
Whenever any reward has been offered by any county legislative authority, board of commissioners of a port district, or city or town governing body in the state under RCW 10.85.030, the person or persons providing the information shall be entitled to the reward, and the county legislative authority, board of commissioners of a port district, or city or town governing body which has offered the reward is authorized to draw a warrant or warrants out of any money in the county, port district, or city or town treasury, as appropriate, not otherwise appropriated.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c185.pdf?cite=1986%20c%20185%20§%203[1986 c 185 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c53.pdf?cite=1979%20ex.s.%20c%2053%20§%203[1979 ex.s. c 53 § 3]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1886%20p%20124%20§%202[1886 p 124 § 2]; RRS § 2250; ]

