= 10.70 - Commitments.
:toc:

== 10.70.010 - Commitment until fine and costs are paid.
When the defendant is adjudged to pay a fine and costs, the court shall order him or her to be committed to the custody of the sheriff until the fine and costs are paid or secured as provided by law.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%201058[2010 c 8 § 1058]; Code 1881 § 1119; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20242%20§%20277[1873 p 242 § 277]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20123%20§%20141[1854 p 123 § 141]; RRS § 2200; ]

== 10.70.020 - Mittimus upon sentence to imprisonment.
When any person shall be sentenced to be imprisoned in the penitentiary or county jail, the clerk of the court shall, as soon as may be, make out and deliver to the sheriff of the county, or his or her deputy, a transcript from the minutes of the court of such conviction and sentence, duly certified by such clerk, which shall be sufficient authority for such sheriff to execute the sentence, who shall execute it accordingly.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%201059[2010 c 8 § 1059]; Code 1881 § 1126; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20243%20§%20284[1873 p 243 § 284]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20124%20§%20148[1854 p 124 § 148]; RRS § 2207; ]

