= 10.91 - Uniform rendition of accused persons act.
:toc:

== 10.91.010 - Arrest and return of released person charged in another state—Violation of release conditions—Request—Documents—Warrant—Investigation.
. If a person who has been charged with crime in another state and released from custody prior to final judgment, including the final disposition of any appeal, is alleged to have violated the terms and conditions of his or her release, and is present in this state, a designated agent of the court, judge, or magistrate which authorized the release may request the issuance of a warrant for the arrest of the person and an order authorizing his or her return to the demanding court, judge, or magistrate. Before the warrant is issued, the designated agent must file with a judicial officer of this state the following documents:

.. An affidavit stating the name and whereabouts of the person whose removal is sought, the crime with which the person was charged, the time and place of the crime charged, and the status of the proceedings against him or her;

.. A certified copy of the order or other document specifying the terms and conditions under which the person was released from custody; and

.. A certified copy of an order of the demanding court, judge, or magistrate stating the manner in which the terms and the conditions of the release have been violated and designating the affiant its agent for seeking removal of the person.

. Upon initially determining that the affiant is a designated agent of the demanding court, judge, or magistrate, and that there is a probable cause for believing that the person whose removal is sought has violated the terms or conditions of his or her release, the judicial officer shall issue a warrant to a law enforcement officer of this state for the person's arrest.

. The judicial officer shall notify the prosecuting attorney of his or her action and shall direct him or her to investigate the case to ascertain the validity of the affidavits and documents required by subsection (1) of this section and the identity and authority of the affiant.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%201089[2010 c 8 § 1089]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c17.pdf?cite=1971%20ex.s.%20c%2017%20§%202[1971 ex.s. c 17 § 2]; ]

== 10.91.020 - Preliminary hearing—Waiver—Conditions of release.
. The person whose removal is sought shall be brought before the judicial officer without unnecessary delay upon arrest pursuant to the warrant; whereupon the judicial officer shall set a time and place for hearing, and shall advise the person of his or her right to have the assistance of counsel, to confront the witnesses against him or her, and to produce evidence in his or her own behalf at the hearing.

. The person whose removal is sought may at this time in writing waive the hearing and agree to be returned to the demanding court, judge, or magistrate. If a waiver is executed, the judicial officer shall issue an order pursuant to RCW 10.91.030.

. The judicial officer may impose conditions of release authorized by the laws of this state which will reasonably assure the appearance at the hearing of the person whose removal is sought.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%201090[2010 c 8 § 1090]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c17.pdf?cite=1971%20ex.s.%20c%2017%20§%203[1971 ex.s. c 17 § 3]; ]

== 10.91.030 - Preliminary hearing—Investigation report—Findings—Order authorizing return.
The prosecuting attorney shall appear at the hearing and report to the judicial officer the results of his or her investigation. If the judicial officer finds that the affiant is a designated agent of the demanding court, judge, or magistrate and that the person whose removal is sought was released from custody by the demanding court, judge, or magistrate, and that the person has violated the terms or conditions of his or her release, the judicial officer shall issue an order authorizing the return of the person to the custody of the demanding court, judge, or magistrate forthwith.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%201091[2010 c 8 § 1091]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c17.pdf?cite=1971%20ex.s.%20c%2017%20§%204[1971 ex.s. c 17 § 4]; ]

== 10.91.040 - "Judicial officer of this state," "judicial officer" defined.
For the purpose of this chapter "judicial officer of this state" and "judicial officer" mean a judge of the superior or district court.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c202.pdf?cite=1987%20c%20202%20§%20170[1987 c 202 § 170]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c17.pdf?cite=1971%20ex.s.%20c%2017%20§%205[1971 ex.s. c 17 § 5]; ]

== 10.91.050 - Costs.
The costs of the procedures required by this chapter shall be borne by the demanding state, except when the designated agent is not a public official. In any case when the designated agent is not a public official, he or she shall bear the cost of such procedures.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%201092[2010 c 8 § 1092]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c17.pdf?cite=1971%20ex.s.%20c%2017%20§%209[1971 ex.s. c 17 § 9]; ]

== 10.91.910 - Construction—1971 ex.s. c 17.
This chapter shall be so construed as to effectuate its general purpose to make uniform the law of those states which enact it.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c17.pdf?cite=1971%20ex.s.%20c%2017%20§%207[1971 ex.s. c 17 § 7]; ]

== 10.91.920 - Short title.
This chapter may be cited as the "Uniform Rendition of Accused Persons Act."

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c17.pdf?cite=1971%20ex.s.%20c%2017%20§%208[1971 ex.s. c 17 § 8]; ]

