= 10.118 - Law enforcement—Use of force—Data collection.
:toc:

== 10.118.010 - Findings.
The legislature finds that law enforcement transparency and accountability are vital in maintaining public trust. Data collection is one essential tool to allow the public, law enforcement, and policymakers to analyze the effectiveness of existing police practices, determine which policies and training work and do not work, and avoid unintended consequences by supporting policy decisions with clear and relevant data.

The legislature finds that creating a statewide data collection program that creates a publicly accessible database to track metrics will help to promote openness, transparency, and accountability, build stronger police-community relations, improve trust and confidence in policing services, evaluate specific areas of concern such as biased policing and excessive force, and ultimately improve the quality of policing services.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5259-S2.SL.pdf?cite=2021%20c%20326%20§%201[2021 c 326 § 1]; ]

== 10.118.020 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Contractor" means the institution of higher education contracted with the office of the attorney general to implement the statewide use of force data program as provided in this chapter.

. "Great bodily harm" has the same meaning as in RCW 9A.04.110.

. "Institution of higher education" has the same meaning as in RCW 28B.92.030.

. "Law enforcement agency" or "agency" means any general authority Washington law enforcement agency and limited authority Washington law enforcement agency as those terms are defined in RCW 10.93.020.

. "Substantial bodily harm" has the same meaning as in RCW 9A.04.110.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5259-S2.SL.pdf?cite=2021%20c%20326%20§%202[2021 c 326 § 2]; ]

== 10.118.030 - Use of force—Reporting requirements.
. Each law enforcement agency in the state is required to report each incident where a law enforcement officer employed by the agency used force and:

.. A fatality occurred in connection with the use of force;

.. Great bodily harm occurred in connection with the use of force;

.. Substantial bodily harm occurred in connection with the use of force; or

.. A law enforcement officer:

... Discharged a firearm at or in the direction of a person;

... Pointed a firearm at a person;

... Used a chokehold or vascular neck restraint;

... Used an electronic control weapon including, but not limited to, a taser, against a person;

.. Used oleoresin capsicum spray against a person;

.. Discharged a less lethal shotgun or other impact munitions at or in the direction of a person;

.. Struck a person using an impact weapon or instrument including, but not limited to, a club, baton, or flashlight;

.. Used any part of their body to physically strike a person including, but not limited to, punching, kicking, slapping, or using closed fists or feet;

... Used a vehicle to intentionally strike a person or vehicle; or

.. Deployed a canine by releasing it from the physical control of the law enforcement officer or had under the law enforcement officer's control a canine that bites a person.

. Each report required in subsection (1) of this section must include the following information:

.. The date and time of the incident;

.. The location of the incident;

.. The agency or agencies employing the law enforcement officers;

.. The type of force used by the law enforcement officer;

.. The type of injury to the person against whom force was used, if any;

.. The type of injury to the law enforcement officer, if any;

.. Whether the person against whom force was used was armed or unarmed;

.. Whether the person against whom force was used was believed to be armed;

.. The type of weapon the person against whom force was used was armed with, if any;

.. The age, gender, race, and ethnicity of the person against whom force was used, if known;

.. The tribal affiliation of the person against whom force was used, if applicable and known;

.. Whether the person against whom force was used exhibited any signs associated with a potential mental health condition or use of a controlled substance or alcohol based on the observation of the law enforcement officer;

.. The name, age, gender, race, and ethnicity of the law enforcement officer, if known;

.. The law enforcement officer's years of service;

.. The reason for the initial contact between the person against whom force was used and the law enforcement officer;

.. Whether any minors were present at the scene of the incident, if known;

.. The entity conducting the independent investigation of the incident, if applicable;

.. Whether dashboard or body worn camera footage was recorded for an incident;

.. The number of officers who were present when force was used; and

.. The number of suspects who were present when force was used.

. Each law enforcement agency must also report any additional incidents and data required by the statewide use of force data program developed in section 3, chapter 326, Laws of 2021.

. All law enforcement agencies shall submit the reports required by this section in accordance with the requirements of the statewide use of force data program no later than three months after the office of the attorney general determines that the system procured in RCW 10.118.040 can accept law enforcement agency reports. Reports must be made in the format and time frame established in the statewide use of force data program.

. A law enforcement agency has satisfied its reporting obligations pursuant to chapter 326, Laws of 2021 by submitting the reports and data required under this section. The contractor shall provide technical assistance to any law enforcement agency in gathering, compiling, and submitting the required reports and data for each incident.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5259-S2.SL.pdf?cite=2021%20c%20326%20§%204[2021 c 326 § 4]; ]

== 10.118.040 - Competitive procurement.
. Subject to the availability of amounts appropriated for this specific purpose, the office of the attorney general must engage in a competitive procurement to contract with an institution of higher education to implement the statewide use of force data program. The primary purpose of the contract is to develop a system for law enforcement agencies to report, collect, and publish the use of force data reports required in RCW 10.118.030.

. The request for proposal or other procurement method should encourage collaboration with other public and private institutions, businesses, and organizations with significant expertise and experience in collecting, tracking, and reporting data on law enforcement interactions with the public.

. Members and representatives of entities participating in the advisory group established in section 3, chapter 326, Laws of 2021 may not participate or bid in the competitive procurement.

. The advisory group, or designated members of the group, may participate in the procurement process through the development of the request for proposal and the review and evaluation of responsive bidders.

. The contract must require the successful bidder to provide appropriate training to its staff and subcontractor staff, including training on racial equity issues.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5259-S2.SL.pdf?cite=2021%20c%20326%20§%205[2021 c 326 § 5]; ]

