= 10.122 - Uniform electronic recordation of custodial interrogations act.
:toc:

== 10.122.010 - Short title. (Effective January 1, 2022.)
This chapter may be known and cited as the uniform electronic recordation of custodial interrogations act.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1223-S.SL.pdf?cite=2021%20c%20329%20§%201[2021 c 329 § 1]; ]

== 10.122.020 - Definitions. (Effective January 1, 2022.)
In this chapter:

. "Custodial interrogation" means express questioning or other actions or words by a law enforcement officer which are reasonably likely to elicit an incriminating response from an individual and occurs when reasonable individuals in the same circumstances would consider themselves in custody.

. "Electronic recording" means an audio recording or audio and video recording that accurately records a custodial interrogation. "Record electronically" and "recorded electronically" have a corresponding meaning.

. "Law enforcement agency" means a general authority Washington law enforcement agency or limited authority Washington law enforcement agency as those terms are defined in RCW 10.93.020.

. "Law enforcement officer" means a general authority Washington peace officer or limited authority Washington peace officer as those terms are defined in RCW 10.93.020.

. "Person" means an individual, corporation, business trust, statutory trust, estate, trust, partnership, limited liability company, association, joint venture, public corporation, or government; governmental subdivision, agency, or instrumentality; or any other legal or commercial entity.

. "Place of detention" means a fixed location under the control of a law enforcement agency where individuals are questioned about alleged crimes or status offenses. The term includes a jail, police or sheriff's station, holding cell, correctional or detention facility, police vehicle, and[,] in the case of juveniles, schools.

. "State" means a state of the United States, the District of Columbia, Puerto Rico, the United States Virgin Islands, or any territory or insular possession subject to the jurisdiction of the United States.

. "Statement" means a communication whether oral, written, electronic, or nonverbal.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1223-S.SL.pdf?cite=2021%20c%20329%20§%202[2021 c 329 § 2]; ]

== 10.122.030 - Electronic recording requirement. (Effective January 1, 2022.)
. Except as otherwise provided by RCW 10.122.050 through 10.122.100, a custodial interrogation, including the giving of any required warning, advice of the rights of the individual being questioned, and the waiver of any rights by the individual, must be recorded electronically in its entirety if the interrogation subject is a juvenile or if the interrogation relates to a felony crime. A custodial interrogation at a jail, police or sheriff's station, holding cell, or correctional or detention facility must be recorded by audio and video means. A custodial interrogation at any other place of detention must be recorded by audio means at minimum.

. If a law enforcement officer conducts a custodial interrogation to which subsection (1) of this section applies without electronically recording it in its entirety, the officer shall prepare a written or electronic report explaining the reason for not complying with this section and summarizing the custodial interrogation process and the individual's statements.

. A law enforcement officer shall prepare the report required by subsection (2) of this section as soon as practicable after completing the interrogation.

. As soon as practicable, a law enforcement officer conducting a custodial interrogation outside a place of detention shall prepare a written or electronic report explaining the decision to interrogate outside a place of detention and summarizing the custodial interrogation process and the individual's statements made outside a place of detention.

. This section does not apply to a spontaneous statement made outside the course of a custodial interrogation or a statement made in response to a question asked routinely during the processing of the arrest of an individual.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1223-S.SL.pdf?cite=2021%20c%20329%20§%203[2021 c 329 § 3]; ]

== 10.122.040 - Consent not required—Notice. (Effective January 1, 2022.)
Notwithstanding RCW 9.73.030 and 9.73.090, a law enforcement officer conducting a custodial interrogation is not required to obtain consent to electronic recording from the individual being interrogated, but must inform the individual that an electronic recording is being made of the interrogation. This chapter does not permit a law enforcement officer or a law enforcement agency to record a private communication between an individual and the individual's lawyer.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1223-S.SL.pdf?cite=2021%20c%20329%20§%204[2021 c 329 § 4]; ]

== 10.122.050 - Exception for exigent circumstances. (Effective January 1, 2022.)
A custodial interrogation to which RCW 10.122.030 otherwise applies need not be recorded electronically if recording is not feasible because of exigent circumstances. The law enforcement officer conducting the interrogation shall record electronically an explanation of the exigent circumstances before conducting the interrogation, if feasible, or as soon as practicable after the interrogation is completed.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1223-S.SL.pdf?cite=2021%20c%20329%20§%205[2021 c 329 § 5]; ]

== 10.122.060 - Exception for individual's refusal to be recorded electronically. (Effective January 1, 2022.)
. A custodial interrogation to which RCW 10.122.030 otherwise applies need not be recorded electronically if the individual to be interrogated indicates that the individual will not participate in the interrogation if it is recorded electronically. If feasible, the agreement to participate without recording must be recorded electronically.

. If, during a custodial interrogation to which RCW 10.122.030 otherwise applies, the individual being interrogated indicates that the individual will not participate in further interrogation unless electronic recording ceases, the remainder of the custodial interrogation need not be recorded electronically. If feasible, the individual's agreement to participate without further recording must be recorded electronically.

. A law enforcement officer, with intent to avoid the requirement of electronic recording in RCW 10.122.030, may not encourage an individual to request that a recording not be made.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1223-S.SL.pdf?cite=2021%20c%20329%20§%206[2021 c 329 § 6]; ]

== 10.122.070 - Exception for interrogation conducted by other jurisdiction. (Effective January 1, 2022.)
If a custodial interrogation occurs in another state in compliance with that state's law or is conducted by a federal law enforcement agency in compliance with federal law, the interrogation need not be recorded electronically unless the interrogation is conducted with intent to avoid the requirement of electronic recording in RCW 10.122.030.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1223-S.SL.pdf?cite=2021%20c%20329%20§%207[2021 c 329 § 7]; ]

== 10.122.080 - Exception based on belief recording not required. (Effective January 1, 2022.)
. A custodial interrogation to which RCW 10.122.030 otherwise applies need not be recorded electronically if the interrogation occurs when no law enforcement officer conducting the interrogation has knowledge of facts and circumstances that would lead an officer reasonably to believe that the individual being interrogated may have committed an act for which RCW 10.122.030 requires that a custodial interrogation be recorded electronically.

. If, during a custodial interrogation under subsection (1) of this section, the individual being interrogated reveals facts and circumstances giving a law enforcement officer conducting the interrogation reason to believe that an act has been committed for which RCW 10.122.030 requires that a custodial interrogation be recorded electronically, continued custodial interrogation concerning that act must be recorded electronically, if feasible.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1223-S.SL.pdf?cite=2021%20c%20329%20§%208[2021 c 329 § 8]; ]

== 10.122.090 - Exception for safety of individual or protection of identity. (Effective January 1, 2022.)
A custodial interrogation to which RCW 10.122.030 otherwise applies need not be recorded electronically if a law enforcement officer conducting the interrogation or the officer's superior reasonably believes that electronic recording would disclose the identity of a confidential informant or jeopardize the safety of an officer, the individual being interrogated, or another individual. If feasible and consistent with the safety of a confidential informant, an explanation of the basis for the belief that electronic recording would disclose the informant's identity must be recorded electronically at the time of the interrogation. If contemporaneous recording of the basis for the belief is not feasible, the recording must be made as soon as practicable after the interrogation is completed.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1223-S.SL.pdf?cite=2021%20c%20329%20§%209[2021 c 329 § 9]; ]

== 10.122.100 - Exception for equipment malfunction. (Effective January 1, 2022.)
. All or part of a custodial interrogation to which RCW 10.122.030 otherwise applies need not be recorded electronically to the extent that recording is not feasible because the available electronic recording equipment fails, despite reasonable maintenance of the equipment, and timely repair or replacement is not feasible.

. If both audio and video recording of a custodial interrogation are otherwise required by RCW 10.122.030, recording may be by audio alone if a technical problem in the video recording equipment prevents video recording, despite reasonable maintenance of the equipment, and timely repair or replacement is not feasible.

. If both audio and video recording of a custodial interrogation are otherwise required by RCW 10.122.030, recording may be by video alone if a technical problem in the audio recording equipment prevents audio recording, despite reasonable maintenance of the equipment, and timely repair or replacement is not feasible.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1223-S.SL.pdf?cite=2021%20c%20329%20§%2010[2021 c 329 § 10]; ]

== 10.122.110 - Burden of persuasion. (Effective January 1, 2022.)
If the prosecution relies on an exception in RCW 10.122.050 through 10.122.100 to justify a failure to record electronically a custodial interrogation, the prosecution must prove by a preponderance of the evidence that the exception applies.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1223-S.SL.pdf?cite=2021%20c%20329%20§%2011[2021 c 329 § 11]; ]

== 10.122.120 - Notice of intent to introduce unrecorded statement. (Effective January 1, 2022.)
If the prosecution intends to introduce in its case in chief a statement made during a custodial interrogation to which RCW 10.122.030 applies which was not recorded electronically, the prosecution, not later than the time specified by the local rules governing discovery, shall serve the defendant with written notice of that intent and of any exception on which the prosecution intends to rely.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1223-S.SL.pdf?cite=2021%20c%20329%20§%2012[2021 c 329 § 12]; ]

== 10.122.130 - Procedural remedies. (Effective January 1, 2022.)
. Unless the court finds that an exception in RCW 10.122.050 through 10.122.100 applies, the court shall consider the failure to record electronically all or part of a custodial interrogation to which RCW 10.122.030 applies in determining whether a statement made during the interrogation is admissible, including whether it was voluntarily made.

. If the court admits into evidence a statement made during a custodial interrogation that was not recorded electronically in compliance with RCW 10.122.030, the court shall afford the defendant the opportunity to present to the jury the fact that the statement was not recorded electronically in compliance with RCW 10.122.030.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1223-S.SL.pdf?cite=2021%20c%20329%20§%2013[2021 c 329 § 13]; ]

== 10.122.140 - Handling and preserving electronic recording. (Effective January 1, 2022.)
Each law enforcement agency in this state shall establish and enforce procedures to ensure that the electronic recording of all or part of a custodial interrogation is identified, accessible, and preserved throughout the length of any resulting sentence, including any period of community custody extending through final discharge.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1223-S.SL.pdf?cite=2021%20c%20329%20§%2014[2021 c 329 § 14]; ]

== 10.122.150 - Policies and procedures relating to electronic recording. (Effective January 1, 2022.)
. Each law enforcement agency that is a governmental entity of this state shall adopt and enforce policies and procedures to implement this chapter.

. The policies and procedures adopted under subsection (1) of this section must address the following topics:

.. How an electronic recording of a custodial interrogation must be made;

.. The collection and review of electronic recordings, or the absence thereof, by supervisors in each law enforcement agency;

.. The assignment of supervisory responsibilities and a chain of command to promote internal accountability;

.. A process for explaining noncompliance with procedures and imposing administrative sanctions for a failure to comply that is not justified;

.. A supervisory system expressly imposing on individuals in specific positions a duty to ensure adequate staffing, education, training, and material resources to implement this chapter; and

.. A process for preserving the chain of custody of an electronic recording.

. The policies and procedures adopted under subsection (2)(a) of this section for video recording must contain standards for the angle, focus, and field of vision of a recording device which reasonably promote accurate recording of a custodial interrogation at a place of detention and reliable assessment of its accuracy and completeness.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1223-S.SL.pdf?cite=2021%20c%20329%20§%2015[2021 c 329 § 15]; ]

== 10.122.160 - Limitation of liability. (Effective January 1, 2022.)
. A law enforcement agency that is a governmental entity in this state which has implemented procedures reasonably designed to enforce the rules adopted pursuant to RCW 10.122.150 and ensure compliance with this chapter is not subject to civil liability for damages arising from a violation of this chapter.

. This chapter does not create a right of action against a law enforcement officer.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1223-S.SL.pdf?cite=2021%20c%20329%20§%2016[2021 c 329 § 16]; ]

== 10.122.170 - Self-authentication. (Effective January 1, 2022.)
. In any pretrial or posttrial proceeding, an electronic recording of a custodial interrogation is self-authenticating if it is accompanied by a certificate of authenticity sworn under oath or affirmation by an appropriate law enforcement officer.

. This chapter does not limit the right of an individual to challenge the authenticity of an electronic recording of a custodial interrogation under law of this state other than this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1223-S.SL.pdf?cite=2021%20c%20329%20§%2017[2021 c 329 § 17]; ]

== 10.122.180 - No right to electronic recording or transcript. (Effective January 1, 2022.)
. This chapter does not create a right of an individual to require a custodial interrogation to be recorded electronically.

. This chapter does not require preparation of a transcript of an electronic recording of a custodial interrogation.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1223-S.SL.pdf?cite=2021%20c%20329%20§%2018[2021 c 329 § 18]; ]

== 10.122.190 - Application—Construction—2021 c 329. (Effective January 1, 2022.)
In applying and construing this uniform act, consideration must be given to the need to promote uniformity of the law with respect to its subject matter among states that enact it.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1223-S.SL.pdf?cite=2021%20c%20329%20§%2019[2021 c 329 § 19]; ]

== 10.122.200 - Relation to electronic signatures in global and national commerce act. (Effective January 1, 2022.)
This chapter modifies, limits, and supersedes the electronic signatures in global and national commerce act, 15 U.S.C. Sec. 7001 et seq., but does not modify, limit, or supersede section 101(c) of that act, 15 U.S.C. Sec. 7001(c), or authorize electronic delivery of any of the notices described in section 103(b) of that act, 15 U.S.C. Sec. 7003(b).

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1223-S.SL.pdf?cite=2021%20c%20329%20§%2020[2021 c 329 § 20]; ]

== 10.122.900 - Effective date—2021 c 329.
Sections 1 through 20 of this act take effect January 1, 2022.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1223-S.SL.pdf?cite=2021%20c%20329%20§%2024[2021 c 329 § 24]; ]

