= 35.13A - Water or sewer districts—Assumption of jurisdiction.
:toc:

== 35.13A.010 - Definitions.
Whenever used in this chapter, the following words shall have the following meanings:

. The words "district," "water district," and "sewer district" shall mean a "water-sewer district" as that term is used in Title 57 RCW.

. The word "city" shall mean a city or town of any class and shall also include any code city as defined in chapter 35A.01 RCW.

. The word "indebtedness" shall include general obligation, revenue, and special indebtedness and temporary, emergency, and interim loans.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6119-S.SL.pdf?cite=1998%20c%20326%20§%201[1998 c 326 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c95.pdf?cite=1971%20ex.s.%20c%2095%20§%201[1971 ex.s. c 95 § 1]; ]

== 35.13A.020 - Assumption authorized—Disposition of properties and rights—Outstanding indebtedness—Management and control.
. Whenever all of the territory of a district is included within the corporate boundaries of a city, the city legislative body may adopt a resolution or ordinance to assume jurisdiction over all of the district.

. Upon the assumption, all real and personal property, franchises, rights, assets, taxes levied but not collected for the district for other than indebtedness, water, sewer, and drainage facilities, and all other facilities and equipment of the district shall become the property of the city subject to all financial, statutory, or contractual obligations of the district for the security or performance of which the property may have been pledged. The city, in addition to its other powers, shall have the power to manage, control, maintain, and operate the property, facilities and equipment and to fix and collect service and other charges from owners and occupants of properties so served by the city, subject, however, to any outstanding indebtedness, bonded or otherwise, of the district payable from taxes, assessments, or revenues of any kind or nature and to any other contractual obligations of the district.

. The city may by resolution or ordinance of its legislative body, assume the obligation of paying such district indebtedness and of levying and of collecting or causing to be collected the district taxes, assessments, and utility rates and charges of any kind or nature to pay and secure the payment of the indebtedness, according to all of the terms, conditions and covenants incident to the indebtedness, and shall assume and perform all other outstanding contractual obligation of the district in accordance with all of their terms, conditions, and covenants. An assumption shall not be deemed to impair the obligation of any indebtedness or other contractual obligation. During the period until the outstanding indebtedness of the district has been discharged, the territory of the district and the owners and occupants of property therein, shall continue to be liable for its and their proportionate share of the indebtedness, including any outstanding assessments levied within any local improvement district or utility local improvement district thereof. The city shall assume the obligation of causing the payment of the district's indebtedness, collecting the district's taxes, assessments, and charges, and observing and performing the other district contractual obligations. The legislative body of the city shall act as the officers of the district for the purpose of certifying the amount of any property tax to be levied and collected therein, and causing service and other charges and assessments to be collected from the property or owners or occupants thereof, enforcing the collection and performing all other acts necessary to ensure performance of the district's contractual obligations in the same manner and by the same means as if the territory of the district had not been included within the boundaries of a city.

When a city assumes the obligation of paying the outstanding indebtedness, and if property taxes or assessments have been levied and service and other charges have accrued for this purpose but have not been collected by the district prior to the assumption, the same when collected shall belong and be paid to the city and be used by the city so far as necessary for payment of the indebtedness of the district existing and unpaid on the date the city assumes the indebtedness. Any funds received by the city which have been collected for the purpose of paying any bonded or other indebtedness of the district, shall be used for the purpose for which they were collected and for no other purpose. Any outstanding indebtedness shall be paid as provided in the terms, conditions, and covenants of the indebtedness. All funds of the district on deposit with the county treasurer at the time of title transfer shall be used by the city solely for the benefit of the assumed utility and shall not be transferred to or used for the benefit of the city's general fund.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1264.SL.pdf?cite=1999%20c%20153%20§%2028[1999 c 153 § 28]; 2010 c 102 § 6; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6119-S.SL.pdf?cite=1998%20c%20326%20§%202[1998 c 326 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c95.pdf?cite=1971%20ex.s.%20c%2095%20§%202[1971 ex.s. c 95 § 2]; ]

== 35.13A.030 - Assumption of control if sixty percent or more of area or valuation within city.
Whenever a portion of a district equal to at least sixty percent of the area or sixty percent of the assessed valuation of the real property lying within such district, is included within the corporate boundaries of a city, the city may assume by ordinance the full and complete management and control of that portion of the entire district not included within another city, whereupon the provisions of RCW 35.13A.020 shall be operative; or the city may proceed directly under the provisions of RCW 35.13A.050.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1264.SL.pdf?cite=1999%20c%20153%20§%2029[1999 c 153 § 29]; 2010 c 102 § 7; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c95.pdf?cite=1971%20ex.s.%20c%2095%20§%203[1971 ex.s. c 95 § 3]; ]

== 35.13A.040 - Assumption of control if less than sixty percent of area or valuation within city.
Whenever the portion of a district included within the corporate boundaries of a city is less than sixty percent of the area of the district and less than sixty percent of the assessed valuation of the real property within the district, the city may elect to proceed under the provisions of RCW 35.13A.050.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1264.SL.pdf?cite=1999%20c%20153%20§%2030[1999 c 153 § 30]; 2010 c 102 § 8; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c95.pdf?cite=1971%20ex.s.%20c%2095%20§%204[1971 ex.s. c 95 § 4]; ]

== 35.13A.050 - Territory containing facilities within or without city—Duties of city or district—Rates and charges—Assumption of responsibility—Outstanding indebtedness—Properties and rights.
When electing under RCW 35.13A.030 or 35.13A.040 to proceed under this section, the city may assume, by ordinance, jurisdiction of the district's responsibilities, property, facilities and equipment within the corporate limits of the city: PROVIDED, That if on the effective date of such an ordinance the territory of the district included within the city contains any facilities serving or designed to serve any portion of the district outside the corporate limits of the city or if the territory lying within the district and outside the city contains any facilities serving or designed to serve territory included within the city (which facilities are hereafter in this section called the "serving facilities"), the city or district shall for the economically useful life of any such serving facilities make available sufficient capacity therein to serve the sewage or water requirements of such territory, to the extent that such facilities were designed to serve such territory at a rate charged to the municipality being served which is reasonable to all parties.

In the event a city proceeds under this section, the district may elect upon a favorable vote of a majority of all voters within the district voting upon such propositions to require the city to assume responsibility for the operation and maintenance of the district's property, facilities and equipment throughout the entire district and to pay the city a charge for such operation and maintenance which is reasonable under all of the circumstances.

A city acquiring property, facilities and equipment under the provisions of this section shall acquire such property, facilities and equipment, and fix and collect service and other charges from owners and occupants of properties served by the city, subject, to any contractual obligations of the district which relate to the property, facilities, or equipment so acquired by the city or which are secured by taxes, assessments or revenues from the territory of the district included within the city. In such cases, the property included within the city and the owners and occupants thereof shall continue to be liable for payment of its and their proportionate share of any outstanding district indebtedness. The district and its officers shall continue to levy taxes and assessments on and to collect service and other charges from such property, or owners or occupants thereof, to enforce such collections, and to perform all other acts necessary to insure performance of the district's contractual obligations in the same manner and by the same means as if the territory of the district had not been included within the boundaries of a city.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c95.pdf?cite=1971%20ex.s.%20c%2095%20§%205[1971 ex.s. c 95 § 5]; ]

== 35.13A.060 - District in more than one city—Assumption of responsibilities—Duties of cities.
Whenever more than one city, in whole or in part, is included within a district, the city which has within its boundaries sixty percent or more of the area of the assessed valuation of the district (in this section referred to as the "principal city") may, with the approval of any other city containing part of such district, assume responsibility for operation and maintenance of the district's property, facilities and equipment within such other city and make and enforce such charges for operation, maintenance and retirement of indebtedness as may be reasonable under all the circumstances.

Any other city having less than sixty percent in area or assessed valuation of such district, within its boundaries may install facilities and create local improvement districts or otherwise finance the cost of installation of such facilities and if such facilities have been installed in accordance with reasonable standards fixed by the principal city, such other city may connect such facilities to the utility system of such district operated by the principal city upon providing for payment by the owners or occupants of properties served thereby, of such charges established by the principal city as may be reasonable under the circumstances.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1264.SL.pdf?cite=1999%20c%20153%20§%2031[1999 c 153 § 31]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c95.pdf?cite=1971%20ex.s.%20c%2095%20§%206[1971 ex.s. c 95 § 6]; ]

== 35.13A.070 - Contracts.
Notwithstanding any provision of this chapter to the contrary, one or more cities and one or more districts may, through their legislative authorities, authorize a contract with respect to the rights, powers, duties, and obligation of such cities, or districts with regard to the use and ownership of property, the providing of services, the maintenance and operation of facilities, allocation of cost, financing and construction of new facilities, application and use of assets, disposition of liabilities and debts, the performance of contractual obligations, and any other matters arising out of the inclusion, in whole or in part, of the district or districts within any city or cities, or the assumption by the city of jurisdiction of a district under *RCW 35.13A.110. The contract may provide for the furnishing of services by any party thereto and the use of city or district facilities or real estate for such purpose, and may also provide for the time during which such district or districts may continue to exercise any rights, privileges, powers, and functions provided by law for such district or districts as if the district or districts or portions thereof were not included within a city or were not subject to an assumption of jurisdiction under *RCW 35.13A.110, including but not by way of limitation, the right to promulgate rules and regulations, to levy and collect special assessments, rates, charges, service charges, and connection fees, to adopt and carry out the provisions of a comprehensive plan, and amendments thereto, for a system of improvements, and to issue general obligation bonds or revenue bonds in the manner provided by law. The contract may provide for the transfer to a city of district facilities, property, rights, and powers as provided in RCW 35.13A.030, 35.13A.050, and * 35.13A.110, whether or not sixty percent or any of the area or assessed valuation of real estate lying within the district or districts is included within such city. The contract may provide that any party thereto may authorize, issue, and sell revenue bonds to provide funds for new water or sewer improvements or to refund any water revenue, sewer revenue, or combined water and sewer revenue bonds outstanding of any city, or district which is a party to such contract if such refunding is deemed necessary, providing such refunding will not increase interest costs. The contract may provide that any party thereto may authorize and issue, in the manner provided by law, general obligation or revenue bonds of like amounts, terms, conditions, and covenants as the outstanding bonds of any other party to the contract, and such new bonds may be substituted or exchanged for such outstanding bonds. However, no such exchange or substitution shall be effected in such a manner as to impair the obligation or security of any such outstanding bonds.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5650.SL.pdf?cite=1997%20c%20426%20§%202[1997 c 426 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c95.pdf?cite=1971%20ex.s.%20c%2095%20§%207[1971 ex.s. c 95 § 7]; ]

== 35.13A.080 - Dissolution of water district or sewer district.
In any of the cases provided for in RCW 35.13A.020, 35.13A.030, 35.13A.050, and * 35.13A.110, and notwithstanding any other method of dissolution provided by law, dissolution proceedings may be initiated by either the city or the district, or both, when the legislative body of the city and the governing body of the district agree to, and petition for, dissolution of the district.

The petition for dissolution shall be signed by the chief administrative officer of the city and the district, upon authorization of the legislative body of the city and the governing body of the district, respectively and such petition shall be presented to the superior court of the county in which the city is situated.

If the petition is thus authorized by both the city and district, and title to the property, facilities, and equipment of the district has passed to the city pursuant to action taken under this chapter, all indebtedness and local improvement district or utility local improvement district assessments of the district have been discharged or assumed by and transferred to the city, and the petition contains a statement of the distribution of assets and liabilities mutually agreed upon by the city and the district and a copy of the agreement between such city and the district is attached thereto, a hearing shall not be required and the court shall, if the interests of all interested parties have been protected, enter an order dissolving the district.

In any of the cases provided for in RCW 35.13A.020, 35.13A.030, and * 35.13A.110, if the petition for an order of dissolution is signed on behalf of the city alone or the district alone, or there is no mutual agreement on the distribution of assets and liabilities, the superior court shall enter an order fixing a hearing date not less than sixty days from the day the petition is filed, and the clerk of the court of the county shall give notice of such hearing by publication in a newspaper of general circulation in the district once a week for three successive weeks and by posting in three public places in the district at least twenty-one days before the hearing. The notice shall set forth the filing of the petition, its purposes, and the date and place of hearing thereon.

After the hearing the court shall enter its order with respect to the dissolution of the district. If the court finds that such district should be dissolved and the functions performed by the city, the court shall provide for the transfer of assets and liabilities to the city. The court may provide for the dissolution of the district upon such conditions as the court may deem appropriate. A certified copy of the court order dissolving the district shall be filed with the county auditor. If the court does not dissolve the district, it shall state the reasons for declining to do so.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5650.SL.pdf?cite=1997%20c%20426%20§%203[1997 c 426 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c95.pdf?cite=1971%20ex.s.%20c%2095%20§%208[1971 ex.s. c 95 § 8]; ]

== 35.13A.090 - Employment and rights of district employees.
Whenever a city acquires all of the facilities of a district, pursuant to this chapter, such a city shall offer to employ every full time employee of the district who is engaged in the operation of such a district's facilities on the date on which such city acquires the district facilities. When a city acquires any portion of the facilities of such a district, such a city shall offer to employ full time employees of the district as of the date of the acquisition of the facilities of the district who are not longer needed by the district.

Whenever a city employs a person who was employed immediately prior thereto by the district, arrangements shall be made:

. For the retention of all sick leave standing to the employee's credit in the plan of such district.

. For a vacation with pay during the first year of employment equivalent to that to which he or she would have been entitled if he or she had remained in the employment of the district.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202011[2009 c 549 § 2011]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1264.SL.pdf?cite=1999%20c%20153%20§%2032[1999 c 153 § 32]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c95.pdf?cite=1971%20ex.s.%20c%2095%20§%209[1971 ex.s. c 95 § 9]; ]

== 35.13A.100 - Assumption of substandard water system—Limited immunity from liability.
A city assuming responsibility for a water system that is not in compliance with state or federal requirements for public drinking water systems, and its agents and employees, are immune from lawsuits or causes of action, based on noncompliance with state or federal requirements for public drinking water systems, which predate the date of assuming responsibility and continue after the date of assuming responsibility, provided that the city has submitted and is complying with a plan and schedule of improvements approved by the department of health. This immunity shall expire on the earlier of the date the plan of improvements is completed or four years from the date of assuming responsibility. This immunity does not apply to intentional injuries, fraud, or bad faith.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6428-S.SL.pdf?cite=1994%20c%20292%20§%205[1994 c 292 § 5]; ]

== 35.13A.111 - Assumption of water-sewer district with fewer than two hundred fifty customers.
The board of commissioners of a water-sewer district, with fewer than two hundred fifty customers on July 24, 2005, and the city council of a code city with a population greater than one hundred thousand on July 24, 2005, may provide for assumption by the city of the district in accordance with RCW 35.13A.020, except as provided herein, pursuant to the terms and conditions of a contract executed in accordance with RCW 35.13A.070. None of the territory of the water-sewer district need be included within the territory of the city. The contract and assumption shall be approved by resolution of the board of commissioners and ordinance of the city council. If the water-sewer district has no indebtedness or monetary obligations on the date of assumption, the city shall use any surplus funds only for water services delivered to and water facilities constructed in the former territory of the district, unless provided otherwise in the contract. In connection with the assumption, the water-sewer district or the city, or both, may provide for dissolution of the district pursuant to RCW 35.13A.080.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5268.SL.pdf?cite=2005%20c%2043%20§%201[2005 c 43 § 1]; ]

== 35.13A.115 - Assumption resolution or ordinance—Referendum.
. Except as provided otherwise by subsection (4) of this section, a resolution or ordinance adopted by the legislative body of a city to assume jurisdiction of all or part of a water-sewer district under this chapter is subject to a referendum. Any referendum petition to repeal the assumption resolution or ordinance must be filed with the county auditor within ten days of passage of the resolution or ordinance. Within ten days of the filing of a petition, the county auditor must confer with the petitioner concerning the form and style of the petition and issue a petition identification number. The ballot title must be prepared by the applicable city attorney in accordance with this section and RCW 29A.36.071, and the question posed to the voters must be written so that an affirmative answer to the question and a majority affirmative vote on the measure results in approval of the proposed assumption, and a negative answer to the question and a majority negative vote on the measure results in the assumption being barred. The petitioner must be notified of the identification number and ballot title within this ten-day period. After this notification, the petitioner has forty-five days in which to secure on petition forms the signatures of at least ten percent of the number of voters residing in the part of the water-sewer district subject to the assumption resolution or ordinance who voted in the most recent general election, and file the signed petitions with the county auditor. Each petition form must contain the ballot title and full text of the measure to be referred. The county auditor must verify the sufficiency of the signatures on the petitions.

. If sufficient valid signatures on the petitions are properly submitted, the county auditor must submit the referendum measure to the registered voters residing in the part of the water-sewer district subject to the assumption resolution or ordinance in a general or special election no later than one hundred twenty days after the signed petition has been filed with the county auditor. Elections must be conducted in accordance with general election law, and the cost of the election must be borne by the city seeking approval to assume jurisdiction of all or part of the water-sewer district.

. When a referendum petition is filed with the county auditor, the assumption resolution or ordinance sought to be referred to the voters, and any proceedings before a boundary review board under chapter 36.93 RCW, are suspended from taking effect. Such suspension terminates when: (a) There is a final determination of insufficiency or untimeliness of the referendum petition; or (b) the assumption resolution or ordinance so referred is approved by the voters at a referendum election.

. If a city legislative authority assumes jurisdiction of all or part of a water-sewer district through a contract with a water-sewer district, or through an interlocal agreement with a water-sewer district under chapter 39.34 RCW, the provisions of this section do not apply.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5048-S.SL.pdf?cite=2015%20c%20172%20§%201[2015 c 172 § 1]; ]

== 35.13A.120 - Assumption resolution or ordinance—Effective date.
A resolution or ordinance adopted by a city in accordance with this chapter to assume jurisdiction of all or part of a district may not take effect until ninety or more days after its adoption.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5048-S.SL.pdf?cite=2015%20c%20172%20§%202[2015 c 172 § 2]; ]

