= 35.23 - Second-class cities.
:toc:

== 35.23.010 - Rights, powers, and privileges—Exchange of park purpose property.
Every city of the second class shall be entitled "City of . . . . . ." (naming it), and by such name shall have perpetual succession; may sue and be sued in all courts and in all proceedings; shall have and use a common seal which it may alter at pleasure; may acquire, hold, lease, use and enjoy property of every kind and control and dispose of it for the common benefit; and, upon making a finding that any property acquired for park purposes is not useful for such purposes and that an exchange thereof for other property to be dedicated for park purposes is in the public interest, may, with the consent of the dedicator or donor, his or her heirs, successors or assigns, exchange such property for other property to be dedicated for park purposes and make, execute and deliver proper conveyances to effect the exchange. In any case where owing to death or lapse of time there is neither donor, heir, successor, nor assigns to give consent to the exchange, then this consent may be executed by the grantee. Title to property so conveyed by the city shall vest in the grantee free and clear of any trust in favor of the public arising out of any prior dedication for park purposes.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202048[2009 c 549 § 2048]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.23.010[1965 c 7 § 35.23.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c190.pdf?cite=1953%20c%20190%20§%201[1953 c 190 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c241.pdf?cite=1907%20c%20241%20§%201[1907 c 241 § 1]; RRS § 9006; ]

== 35.23.021 - City officers enumerated—Compensation—Appointment and removal.
The government of a second-class city shall be vested in a mayor, a city council of seven members, a city attorney, a clerk, a treasurer, all elective; and a chief of police, municipal judge, city engineer, street superintendent, health officer and such other appointive officers as may be provided for by ordinance: PROVIDED, That the council may enact an ordinance providing for the appointment of the city clerk, city attorney, and treasurer by the mayor, which appointment shall be subject to confirmation by a majority vote of the city council. Such ordinance shall be enacted and become effective not later than thirty days prior to the first day allowed for filing declarations of candidacy for such offices when such offices are subject to an approaching city primary election. Elective incumbent city clerks, city attorneys, and city treasurers shall serve for the remainder of their unexpired term notwithstanding any appointment made pursuant to this section and RCW 35.23.051. If a free public library and reading room is established, five library trustees shall be appointed. The city council by ordinance shall prescribe the duties and fix the compensation of all officers and employees: PROVIDED, That the provisions of any such ordinance shall not be inconsistent with any statute: PROVIDED FURTHER, That where the city council finds that the appointment of a full time city engineer is unnecessary, it may in lieu of such appointment, by resolution provide for the performance of necessary engineering services on either a part time, temporary or periodic basis by a qualified engineering firm, pursuant to any reasonable contract.

The mayor shall appoint and at his or her pleasure may remove all appointive officers except as otherwise provided herein: PROVIDED, That municipal judges shall be removed only upon conviction of misconduct or malfeasance in office, or because of physical or mental disability rendering the judge incapable of performing the duties of his or her office. Every appointment or removal must be in writing signed by the mayor and filed with the city clerk.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2035[1994 c 81 § 35]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5112.SL.pdf?cite=1993%20c%2047%20§%201[1993 c 47 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c3.pdf?cite=1987%20c%203%20§%209[1987 c 3 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c116.pdf?cite=1969%20c%20116%20§%201[1969 c 116 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c116.pdf?cite=1965%20ex.s.%20c%20116%20§%209[1965 ex.s. c 116 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.24.020[1965 c 7 § 35.24.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c81.pdf?cite=1961%20c%2081%20§%201[1961 c 81 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c365.pdf?cite=1955%20c%20365%20§%202[1955 c 365 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c55.pdf?cite=1955%20c%2055%20§%205[1955 c 55 § 5]; prior:   1915 c 184 § 2; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c156.pdf?cite=1891%20c%20156%20§%204[1891 c 156 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c179.pdf?cite=1890%20p%20179%20§%20105[1890 p 179 § 105]; RRS § 9115.  1929 c 182 § 1, part; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1927c159.pdf?cite=1927%20c%20159%20§%201[1927 c 159 § 1]; 1915 c 184 § 3, part; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c57.pdf?cite=1893%20c%2057%20§%201[1893 c 57 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c156.pdf?cite=1891%20c%20156%20§%201[1891 c 156 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c179.pdf?cite=1890%20p%20179%20§%20106[1890 p 179 § 106]; RRS § 9116, part. (iii)  1915 c 184 § 28; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c196.pdf?cite=1890%20p%20196%20§%20137[1890 p 196 § 137]; RRS § 9142; ]

== 35.23.031 - Eligibility to hold elective office.
No person is eligible to hold an elective office in a second-class city unless the person is a resident and registered voter in the city.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5336-S.SL.pdf?cite=1997%20c%20361%20§%207[1997 c 361 § 7]; ]

== 35.23.051 - Elections—Terms of office—Positions and wards.
General municipal elections in second-class cities shall be held biennially in the odd-numbered years and shall be subject to general election law.

The terms of office of the mayor, city attorney, clerk, and treasurer shall be four years and until their successors are elected and qualified and assume office in accordance with RCW 29A.60.280: PROVIDED, That if the offices of city attorney, clerk, and treasurer are made appointive, the city attorney, clerk, and treasurer shall not be appointed for a definite term: PROVIDED FURTHER, That the term of the elected treasurer shall not commence in the same biennium in which the term of the mayor commences, nor in which the terms of the city attorney and clerk commence if they are elected.

Council positions shall be numbered in each second-class city so that council position seven has a two-year term of office and council positions one through six shall each have four-year terms of office. Each councilmember shall remain in office until a successor is elected and qualified and assumes office in accordance with RCW 29A.60.280.

In its discretion the council of a second-class city may divide the city by ordinance, into a convenient number of wards, not exceeding six, fix the boundaries of the wards, and change the ward boundaries from time to time and as provided in RCW 29A.76.010. No change in the boundaries of any ward shall be made within one hundred twenty days next before the date of a general municipal election, nor within twenty months after the wards have been established or altered unless pursuant to RCW 29A.92.040 or 29A.92.110. However, if a boundary change results in one ward being represented by more councilmembers than the number to which it is entitled, those having the shortest unexpired terms shall be assigned by the council to wards where there is a vacancy, and the councilmembers so assigned shall be deemed to be residents of the wards to which they are assigned for purposes of determining whether those positions are vacant.

Whenever such city is so divided into wards, the city council shall designate by ordinance the number of councilmembers to be elected from each ward, apportioning the same in proportion to the population of the wards. Thereafter the councilmembers so designated shall be elected by the voters resident in such ward, or by general vote of the whole city as may be designated in such ordinance. Council position seven shall not be associated with a ward and the person elected to that position may reside anywhere in the city and voters throughout the city may vote at a primary to nominate candidates for position seven, when a primary is necessary, and at a general election to elect the person to council position seven. Additional territory that is added to the city shall, by act of the council, be annexed to contiguous wards without affecting the right to redistrict at the expiration of twenty months after last previous division. The removal of a councilmember from the ward for which he or she was elected shall create a vacancy in such office.

Wards shall be redrawn as provided in chapter 29A.76 RCW. Wards shall be used as follows: (1) Only a resident of the ward may be a candidate for, or hold office as, a councilmember of the ward; and (2) only voters of the ward may vote at a primary to nominate candidates for a councilmember of the ward. Voters of the entire city may vote at the general election to elect a councilmember of a ward, unless the city had prior to January 1, 1994, limited the voting in the general election for any or all council positions to only voters residing within the ward associated with the council positions. If a city had so limited the voting in the general election to only voters residing within the ward, then the city shall be authorized to continue to do so. The elections for the remaining council position or council positions that are not associated with a ward shall be conducted as if the wards did not exist.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5266-S.SL.pdf?cite=2019%20c%20454%20§%205[2019 c 454 § 5]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1806-S.SL.pdf?cite=2015%20c%2053%20§%2039[2015 c 53 § 39]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5336-S.SL.pdf?cite=1997%20c%20361%20§%2013[1997 c 361 § 13]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1015.SL.pdf?cite=1995%20c%20134%20§%208[1995 c 134 § 8]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2278-S.SL.pdf?cite=1994%20c%20223%20§%2017[1994 c 223 § 17]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2036[1994 c 81 § 36]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c126.pdf?cite=1979%20ex.s.%20c%20126%20§%2022[1979 ex.s. c 126 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c116.pdf?cite=1969%20c%20116%20§%202[1969 c 116 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.24.050[1965 c 7 § 35.24.050]; prior:  1963 c 200 § 15; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c86.pdf?cite=1959%20c%2086%20§%204[1959 c 86 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c365.pdf?cite=1955%20c%20365%20§%203[1955 c 365 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c55.pdf?cite=1955%20c%2055%20§%206[1955 c 55 § 6]; prior:  1929 c 182 § 1, part; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1927c159.pdf?cite=1927%20c%20159%20§%201[1927 c 159 § 1]; 1915 c 184 § 3, part; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c57.pdf?cite=1893%20c%2057%20§%201[1893 c 57 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c156.pdf?cite=1891%20c%20156%20§%201[1891 c 156 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c179.pdf?cite=1890%20p%20179%20§%20106[1890 p 179 § 106]; RRS § 9116, part.   1941 c 108 § 1; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c87.pdf?cite=1939%20c%2087%20§%201[1939 c 87 § 1]; Rem. Supp. 1941 § 9116-1; ]

== 35.23.081 - Oath and bond of officers.
In a city of the second class, the treasurer, city attorney, clerk, chief of police, and such other officers as the council may require shall each, before entering upon the duties of office, take an oath of office and execute and file with the clerk an official bond in such penal sum as the council shall determine, conditioned for the faithful performance of his or her duties and otherwise conditioned as may be provided by ordinance. The oath of office shall be filed with the county auditor.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2037[1994 c 81 § 37]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c3.pdf?cite=1987%20c%203%20§%2010[1987 c 3 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c167.pdf?cite=1986%20c%20167%20§%2018[1986 c 167 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.24.080[1965 c 7 § 35.24.080]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c184.pdf?cite=1915%20c%20184%20§%205[1915 c 184 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c70.pdf?cite=1893%20c%2070%20§%201[1893 c 70 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c179.pdf?cite=1890%20p%20179%20§%20107[1890 p 179 § 107]; RRS § 9118; ]

== 35.23.091 - Compensation of officers—Expenses—Nonstate pensions.
The mayor and the members of the city council may be reimbursed for actual expenses incurred in the discharge of their official duties, upon presentation of a claim therefor, after allowance and approval thereof, by resolution of the city council; and each city councilmember may be paid for attending council meetings an amount which shall be fixed by ordinance and may be revised from time to time by ordinance, but any increase or reduction in the compensation attaching to an office shall not be applicable to the term then being served by the incumbent.

The city attorney, clerk and treasurer, if elective, shall severally receive at stated times a compensation to be fixed by ordinance by the city council.

The mayor and other officers shall receive such compensation as may be fixed by the city council at the time the estimates are made as provided by law.

Any city that provides a pension for any of its employees under a plan not administered by the state must notify the state auditor of the existence of the plan at the time of an audit of the city by the auditor. No city may establish a pension plan for its employees that is not administered by the state, except that any defined contribution plan in existence as of January 1, 1990, is deemed to have been authorized. No city that provides a defined contribution plan for its employees as authorized by this section may make any material changes in the terms or conditions of the plan after June 7, 1990.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c212.pdf?cite=1990%20c%20212%20§%201[1990 c 212 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c87.pdf?cite=1973%201st%20ex.s.%20c%2087%20§%201[1973 1st ex.s. c 87 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c270.pdf?cite=1969%20ex.s.%20c%20270%20§%208[1969 ex.s. c 270 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c105.pdf?cite=1965%20c%20105%20§%201[1965 c 105 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.24.090[1965 c 7 § 35.24.090]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c89.pdf?cite=1961%20c%2089%20§%207[1961 c 89 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c115.pdf?cite=1941%20c%20115%20§%201[1941 c 115 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c184.pdf?cite=1915%20c%20184%20§%207[1915 c 184 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c70.pdf?cite=1893%20c%2070%20§%202[1893 c 70 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c180.pdf?cite=1890%20p%20180%20§%20109[1890 p 180 § 109]; Rem. Supp. 1941 § 9120; ]

== 35.23.101 - Vacancies.
. The council of a second-class city may declare a council position vacant if the councilmember is absent for three consecutive regular meetings without permission of the council. 

. A vacancy in an elective office shall occur and shall be filled as provided in chapter 42.12 RCW. An incumbent councilmember is eligible to be appointed to fill a vacancy in the office of mayor.

Vacancies in offices other than that of mayor or city councilmember shall be filled by appointment of the mayor.

. If there is a temporary vacancy in an appointive office due to illness, absence from the city or other temporary inability to act, the mayor may appoint a temporary appointee to exercise the duties of the office until the temporary disability of the incumbent is removed.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1391.SL.pdf?cite=2008%20c%2050%20§%201[2008 c 50 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1015.SL.pdf?cite=1995%20c%20134%20§%209[1995 c 134 § 9]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2278-S.SL.pdf?cite=1994%20c%20223%20§%2019[1994 c 223 § 19]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2038[1994 c 81 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.24.100[1965 c 7 § 35.24.100]; prior:   1919 c 113 § 1; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c184.pdf?cite=1915%20c%20184%20§%206[1915 c 184 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c180.pdf?cite=1890%20p%20180%20§%20108[1890 p 180 § 108]; RRS § 9119.  1907 c 228 § 5, part; RRS § 9203, part; ]

== 35.23.111 - City attorney—Duties.
The city attorney shall advise the city authorities and officers in all legal matters pertaining to the business of the city and shall approve all ordinances as to form. He or she shall represent the city in all actions brought by or against the city or against city officials in their official capacity. He or she shall perform such other duties as the city council by ordinance may direct.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202049[2009 c 549 § 2049]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.24.110[1965 c 7 § 35.24.110]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c184.pdf?cite=1915%20c%20184%20§%2026[1915 c 184 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c70.pdf?cite=1893%20c%2070%20§%2011[1893 c 70 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c192.pdf?cite=1890%20p%20192%20§%20132[1890 p 192 § 132]; RRS § 9140; ]

== 35.23.121 - City clerk—Duties—Deputies.
The city clerk shall keep a full and true record of every act and proceeding of the city council and keep such books, accounts and make such reports as may be required by the state auditor. The city clerk shall record all ordinances, annexing thereto his or her certificate giving the number and title of the ordinance, stating that the ordinance was published and posted according to law and that the record is a true and correct copy thereof. The record copy with the clerk's certificate shall be prima facie evidence of the contents of the ordinance and of its passage and publication and shall be admissible as such evidence in any court or proceeding.

The city clerk shall be custodian of the seal of the city and shall have authority to acknowledge the execution of all instruments by the city which require acknowledgment.

The city clerk may appoint a deputy for whose acts he or she and his or her bondspersons shall be responsible, and he or she and his or her deputy shall have authority to take all necessary affidavits to claims against the city and certify them without charge.

The city clerk shall perform such other duties as may be required by statute or ordinance.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5063.SL.pdf?cite=2007%20c%20218%20§%2075[2007 c 218 § 75]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1889.SL.pdf?cite=1995%20c%20301%20§%2036[1995 c 301 § 36]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.24.120[1965 c 7 § 35.24.120]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c184.pdf?cite=1915%20c%20184%20§%2025[1915 c 184 § 25]; RRS § 9139; ]

== 35.23.131 - City treasurer—Duties.
The city treasurer shall receive and safely keep all money which comes into his or her hands as treasurer, for all of which he or she shall execute triplicate receipts, one to be filed with the city clerk. He or she shall receive all money due the city and disburse it on warrants issued by the clerk countersigned by the mayor, and not otherwise. He or she shall make monthly settlements with the city clerk at which time he or she shall deliver to the clerk the duplicate receipts for all money received and all canceled warrants as evidence of money paid.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202050[2009 c 549 § 2050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.24.130[1965 c 7 § 35.24.130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c184.pdf?cite=1915%20c%20184%20§%2024[1915 c 184 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c70.pdf?cite=1893%20c%2070%20§%208[1893 c 70 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c192.pdf?cite=1890%20p%20192%20§%20132[1890 p 192 § 132]; RRS § 9138; ]

== 35.23.134 - Association of sheriffs and police chiefs.
See chapter 36.28A RCW.

[ ]

== 35.23.141 - Duty of officers collecting moneys.
Every officer collecting or receiving any money belonging to or for the use of the city shall settle with the clerk and immediately pay it into the treasury on the order of the clerk to be credited to the fund to which it belongs.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.24.140[1965 c 7 § 35.24.140]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c184.pdf?cite=1915%20c%20184%20§%2030[1915 c 184 § 30]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c197.pdf?cite=1890%20p%20197%20§%20139[1890 p 197 § 139]; RRS § 9144; ]

== 35.23.142 - Combination of offices of treasurer with clerk—Authorized.
The city council of any city of the second class is authorized to provide by ordinance that the office of treasurer shall be combined with that of clerk, or that the office of clerk shall be combined with that of treasurer: PROVIDED, That such ordinance shall not be voted upon until the next regular meeting after its introduction.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2039[1994 c 81 § 39]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c116.pdf?cite=1969%20c%20116%20§%203[1969 c 116 § 3]; ]

== 35.23.144 - Combination of offices of treasurer with clerk—Powers of clerk.
In the event that the office of treasurer is combined with the office of clerk so as to become the office of clerk-treasurer, the clerk shall exercise all the powers vested in and perform all the duties required to be performed by the treasurer, and in cases where the law requires the treasurer to sign or execute any papers or documents, it shall not be necessary for the clerk to sign as treasurer, but shall be sufficient if he or she signs as clerk.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202051[2009 c 549 § 2051]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c116.pdf?cite=1969%20c%20116%20§%204[1969 c 116 § 4]; ]

== 35.23.146 - Combination of offices of treasurer with clerk—Powers of treasurer.
In the event that the office of clerk is combined with the office of treasurer so as to become the office of treasurer-clerk, the treasurer shall exercise all the powers vested in and perform all the duties required to be performed by the clerk.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c116.pdf?cite=1969%20c%20116%20§%205[1969 c 116 § 5]; ]

== 35.23.148 - Combination of offices of treasurer with clerk—Ordinance—Termination of combined offices.
The ordinance provided for combining said offices shall provide the date when the combination shall become effective, which date shall not be less than three months from the date when the ordinance becomes effective; and on and after said date the office of treasurer or clerk, as the case may be, shall be abolished. Any city which as herein provided, combined the office of treasurer with that of clerk or the office of clerk with that of treasurer may terminate such combination by ordinance, fixing the time when the combination shall cease and thereafter the duties of the offices shall be performed by separate officials: PROVIDED, That if the office of treasurer was combined with that of clerk, or an elective office of clerk was combined with the office of treasurer, the mayor shall appoint a treasurer and clerk who shall serve until the next regular municipal general election when a treasurer and clerk shall be elected for the term as provided by law unless such city has enacted an ordinance in accordance with *RCW 35.24.020.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c116.pdf?cite=1969%20c%20116%20§%206[1969 c 116 § 6]; ]

== 35.23.161 - Chief of police and police department.
The department of police in a city of the second class shall be under the direction and control of the chief of police subject to the direction of the mayor. Any police officer may pursue and arrest violators of city ordinances beyond the city limits.

Every citizen shall lend the police chief aid, when required, for the arrest of offenders and maintenance of public order. With the concurrence of the mayor, the police chief may appoint additional police officers to serve for one day only under orders of the chief in the preservation of public order.

The police chief shall have the same authority as that conferred upon sheriffs for the suppression of any riot, public tumult, disturbance of the peace, or resistance against the laws or the public authorities in the lawful exercise of their functions and shall be entitled to the same protection.

The police chief shall perform such other services as may be required by statute or ordinances of the city.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2040[1994 c 81 § 40]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c3.pdf?cite=1987%20c%203%20§%2011[1987 c 3 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c316.pdf?cite=1977%20ex.s.%20c%20316%20§%2022[1977 ex.s. c 316 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.24.160[1965 c 7 § 35.24.160]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c184.pdf?cite=1915%20c%20184%20§%2027[1915 c 184 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c70.pdf?cite=1893%20c%2070%20§%2012[1893 c 70 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c195.pdf?cite=1890%20p%20195%20§%20136[1890 p 195 § 136]; RRS § 9141; ]

== 35.23.170 - Park commissioners.
Councils of second-class cities and towns may provide by ordinance, for a board of park commissioners, not to exceed seven in number, to be appointed by the mayor, with the consent of the city council, from citizens of recognized fitness for such position. No commissioner shall receive any compensation. The first commissioners shall determine by lot whose term of office shall expire each year, and a new commissioner shall be appointed annually to serve for a term of years corresponding in number to the number of commissioners in order that one term shall expire each year. Such board of park commissioners shall have only such powers and authority with respect to the management, supervision, and control of parks and recreational facilities and programs as are granted to it by the council.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2016[1994 c 81 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c76.pdf?cite=1973%20c%2076%20§%201[1973 c 76 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.23.170[1965 c 7 § 35.23.170]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c86.pdf?cite=1953%20c%2086%20§%201[1953 c 86 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c121.pdf?cite=1925%20ex.s.%20c%20121%20§%201[1925 ex.s. c 121 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c228.pdf?cite=1907%20c%20228%20§%202[1907 c 228 § 2]; RRS § 9200; ]

== 35.23.181 - City council—Oath—Meetings.
The city council and mayor shall meet in January next succeeding the date of each general municipal election, and shall take the oath of office, and shall hold regular meetings at least once during each month but not to exceed one regular meeting in each week, at such times as may be fixed by ordinance.

Special meetings may be called by the mayor by written notice as provided in RCW 42.30.080. No ordinances shall be passed or contract let or entered into, or bill for the payment of money allowed at any special meeting.

All meetings of the city council shall be held at such place as may be designated by the city council. All final actions on resolutions and ordinances must take place within the corporate limits of the city. All meetings of the city council must be public.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5052-S.SL.pdf?cite=1993%20c%20199%20§%202[1993 c 199 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.24.180[1965 c 7 § 35.24.180]; 1915 c 184 § 10, part; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c70.pdf?cite=1893%20c%2070%20§%203[1893 c 70 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c181.pdf?cite=1890%20p%20181%20§%20113[1890 p 181 § 113]; RRS § 9123, part; ]

== 35.23.191 - City council—Mayor pro tempore.
The members of the city council, at their first meeting each calendar year and thereafter whenever a vacancy occurs in the office of mayor pro tempore, shall elect from among their number a mayor pro tempore, who shall hold office at the pleasure of the council and in case of the absence of the mayor, perform the duties of mayor except that he or she shall not have the power to appoint or remove any officer or to veto any ordinance. 

The mayor and the mayor pro tempore shall have power to administer oaths and affirmations, take affidavits and certify them. The mayor or the mayor pro tempore when acting as mayor, shall sign all conveyances made by the city and all instruments which require the seal of the city.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1391.SL.pdf?cite=2008%20c%2050%20§%202[2008 c 50 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2041[1994 c 81 § 41]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c101.pdf?cite=1969%20c%20101%20§%203[1969 c 101 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.24.190[1965 c 7 § 35.24.190]; 1915 c 184 § 10, part; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c70.pdf?cite=1893%20c%2070%20§%203[1893 c 70 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c181.pdf?cite=1890%20p%20181%20§%20113[1890 p 181 § 113]; RRS § 9123, part.   1915 c 184 § 23; RRS § 9137; ]

== 35.23.201 - City council—Meetings—Journal.
All meetings of the council shall be presided over by the mayor, or, in the mayor's absence, by the mayor pro tempore. The mayor shall have a vote only in the case of a tie in the votes of the councilmembers. If the clerk is absent from a council meeting, the mayor or mayor pro tempore shall appoint one of the members of the council as clerk pro tempore. The appointment of a councilmember as mayor pro tempore or clerk pro tempore shall not in any way abridge the councilmember's right to vote upon all questions coming before the council.

The clerk shall keep a correct journal of all proceedings and at the desire of any member the ayes and noes shall be taken on any question and entered in the journal.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2042[1994 c 81 § 42]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c107.pdf?cite=1965%20c%20107%20§%201[1965 c 107 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.24.200[1965 c 7 § 35.24.200]; 1915 c 184 § 13, part; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c182.pdf?cite=1890%20p%20182%20§%20115[1890 p 182 § 115]; RRS § 9126, part.  1915 c 184 § 11, part; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c156.pdf?cite=1891%20c%20156%20§%202[1891 c 156 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c182.pdf?cite=1890%20p%20182%20§%20114[1890 p 182 § 114]; RRS § 9124, part; ]

== 35.23.211 - Ordinances—Style—Requisites—Veto.
The enacting clause of all ordinances in a second-class city shall be as follows: "The city council of the city of . . . . . . do ordain as follows:"

No ordinance shall contain more than one subject and that must be clearly expressed in its title.

No ordinance or any section thereof shall be revised or amended unless the new ordinance sets forth the revised ordinance or the amended section at full length.

No ordinance and no resolution or order shall have any validity or effect unless passed by the votes of at least four councilmembers.

No ordinance shall take effect until five days after the date of its publication unless otherwise provided in this title.

Every ordinance which passes the council in order to become valid must be presented to the mayor; if the mayor approves it, the mayor shall sign it, but if not, the mayor shall return it with written objections to the council and the council shall cause the mayor's objections to be entered at large upon the journal and proceed to a reconsideration thereof. If upon reconsideration five members of the council voting upon a call of yeas and nays favor its passage, the ordinance shall become valid notwithstanding the mayor's veto. If the mayor fails for ten days to either approve or veto an ordinance, it shall become valid without the approval of the mayor.

Every ordinance shall be signed by the mayor and attested by the clerk.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2043[1994 c 81 § 43]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.24.210[1965 c 7 § 35.24.210]; 1915 c 184 § 11, part; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c156.pdf?cite=1891%20c%20156%20§%202[1891 c 156 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c182.pdf?cite=1890%20p%20182%20§%20114[1890 p 182 § 114]; RRS § 9124, part.  1915 c 184 § 12, part; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c70.pdf?cite=1893%20c%2070%20§%204[1893 c 70 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c182.pdf?cite=1890%20p%20182%20§%20116[1890 p 182 § 116]; RRS § 9125, part. (iii) 1915 c 184 § 18, part; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c186.pdf?cite=1890%20p%20186%20§%20118[1890 p 186 § 118]; RRS § 9132, part; ]

== 35.23.221 - Ordinances—Publication—Summary—Public notice of hearings and meeting agendas.
Promptly after adoption, the text of each ordinance or a summary of the content of each ordinance shall be published at least once in the city's official newspaper.

For purposes of this section, a summary shall mean a brief description which succinctly describes the main points of the ordinance. Publication of the title of an ordinance authorizing the issuance of bonds, notes, or other evidences of indebtedness shall constitute publication of a summary of that ordinance. When the city publishes a summary, the publication shall include a statement that the full text of the ordinance will be mailed upon request.

An inadvertent mistake or omission in publishing the text or a summary of the content of an ordinance shall not render the ordinance invalid.

In addition to the requirement that a city publish the text or a summary of the content of each adopted ordinance, every city shall establish a procedure for notifying the public of upcoming hearings and the preliminary agenda for the forthcoming council meeting. Such procedure may include, but not be limited to, written notification to the city's official newspaper, publication of a notice in the official newspaper, posting of upcoming council meeting agendas, or such other processes as the city determines will satisfy the intent of this requirement.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6025.SL.pdf?cite=1994%20c%20273%20§%2010[1994 c 273 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c168.pdf?cite=1988%20c%20168%20§%204[1988 c 168 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c400.pdf?cite=1987%20c%20400%20§%201[1987 c 400 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c469.pdf?cite=1985%20c%20469%20§%2025[1985 c 469 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.24.220[1965 c 7 § 35.24.220]; 1915 c 184 § 18, part; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c186.pdf?cite=1890%20p%20186%20§%20118[1890 p 186 § 118]; RRS § 9132, part.  1915 c 184 § 12, part; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c70.pdf?cite=1893%20c%2070%20§%204[1893 c 70 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c182.pdf?cite=1890%20p%20182%20§%20116[1890 p 182 § 116]; RRS § 9125, part; ]

== 35.23.251 - Ordinances granting franchises—Requisites.
No ordinance or resolution granting any franchise for any purpose shall be passed by the city council on the day of its introduction, nor for five days thereafter, nor at any other than a regular meeting nor without first being submitted to the city attorney.

No franchise or valuable privilege shall be granted unless by the vote of at least five members of the city council.

The city council may require a bond in a reasonable amount for any person or corporation obtaining a franchise from the city conditioned for the faithful performance of the conditions and terms of the franchise and providing a recovery on the bond in case of failure to perform the terms and conditions of franchise.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.24.250[1965 c 7 § 35.24.250]; 1915 c 184 § 12, part; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c70.pdf?cite=1893%20c%2070%20§%204[1893 c 70 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c182.pdf?cite=1890%20p%20182%20§%20116[1890 p 182 § 116]; RRS § 9125, part.  1907 c 228 § 1, part; RRS § 9199, part; ]

== 35.23.261 - Audit and allowance of demands against city.
All demands against the city shall be presented to and audited by the city council in accordance with such regulations as it may by ordinance prescribe; and upon the allowance of a demand, the clerk shall draw a warrant upon the treasurer for it, which warrant shall be countersigned by the mayor and shall specify for what purpose it is drawn and out of which fund it is to be paid.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.24.260[1965 c 7 § 35.24.260]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c184.pdf?cite=1915%20c%20184%20§%2019[1915 c 184 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c186.pdf?cite=1890%20p%20186%20§%20119[1890 p 186 § 119]; RRS § 9133; ]

== 35.23.270 - City council—Quorum—Rules—Journal, etc.
A majority of the councilmembers shall constitute a quorum for the transaction of business. A less number may compel the attendance of absent members and may adjourn from time to time. The council shall determine its rules of proceedings. The council may punish their members for disorderly conduct and upon written charges entered upon the journal therefor, may, after trial, expel a member by two-thirds vote of all the members elected. All orders of the city council shall be entered upon the journal of its proceedings, which journal shall be signed by the officer who presided at the meeting. The journal shall be kept by the clerk under the council's direction.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2017[1994 c 81 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.23.270[1965 c 7 § 35.23.270]; 1907 c 241 § 28, part; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c148.pdf?cite=1890%20p%20148%20§%2037[1890 p 148 § 37]; RRS § 9033, part.   1907 c 241 § 59; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c159.pdf?cite=1890%20p%20159%20§%2049[1890 p 159 § 49]; RRS § 9062; ]

== 35.23.290 - City council—Entry of ayes and noes on journal.
At any time, at the request of any two members the ayes and noes on any question may be taken and entered upon the journal and they must be so taken and entered upon the passage of all ordinances appropriating money, imposing taxes, abolishing licenses, increasing or lessening the amount to be paid for licenses.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.23.290[1965 c 7 § 35.23.290]; 1907 c 241 § 28, part; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c148.pdf?cite=1890%20p%20148%20§%2037[1890 p 148 § 37]; RRS § 9033, part.   1907 c 241 § 60; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c159.pdf?cite=1890%20p%20159%20§%2050[1890 p 159 § 50]; RRS § 9063; ]

== 35.23.311 - Eminent domain.
Whenever it shall become necessary for the city to take or damage private property for the purpose of establishing, laying out, extending and widening streets and other public highways and places within the city, or for the purpose of securing rights-of-way for drains, sewers and aqueducts, and for the purpose of widening, straightening or diverting the channels of streams and the improvement of waterfronts, or any other public purpose, and the city council cannot agree with the owner thereof as to the price to be paid, the city council may proceed to acquire, take or damage the same in the manner provided by chapter 8.12 RCW or by chapter 8.20 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.24.310[1965 c 7 § 35.24.310]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c184.pdf?cite=1915%20c%20184%20§%2022[1915 c 184 § 22]; RRS § 9136; ]

== 35.23.325 - Payment of claims and obligations by warrant or check.
A second-class city, by ordinance, may adopt a policy for the payment of claims or other obligations of the city, which are payable out of solvent funds, electing to pay such obligations by warrant or by check. However, when the applicable fund is not solvent at the time payment is ordered, a warrant shall be issued. When checks are to be used, the legislative body shall designate the qualified public depositary, upon which such checks are to be drawn, and the officers authorized or required to sign such checks. Wherever a reference is made to warrants in this title, such term shall include checks where authorized by this section.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/3056.SL.pdf?cite=2006%20c%2041%20§%201[2006 c 41 § 1]; ]

== 35.23.330 - Limitation on allowance of claims, warrants, etc.
No claim shall be allowed against the city by the city council, nor shall the city council order any warrants to be drawn except at a general meeting of the council. The council shall never allow, make valid, or recognize any demand against the city which was not a valid claim against it when the obligation was created, nor authorize to be paid any demand which without such action would be invalid or which is then barred by the statute of limitations, or for which the city was never liable, and any such action shall be void.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.23.330[1965 c 7 § 35.23.330]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c241.pdf?cite=1907%20c%20241%20§%2035[1907 c 241 § 35]; RRS § 9042.  1907 c 241 § 72, part; RRS § 9075, part; ]

== 35.23.331 - Nuisances.
Every act or thing done or being within the limits of a second-class city which is declared by law or by ordinance to be a nuisance shall be a nuisance and shall be so considered in all actions and proceedings. All remedies given by law for the prevention and abatement of nuisances shall apply thereto.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2046[1994 c 81 § 46]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.24.330[1965 c 7 § 35.24.330]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c184.pdf?cite=1915%20c%20184%20§%2021[1915 c 184 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c187.pdf?cite=1890%20p%20187%20§%20123[1890 p 187 § 123]; RRS § 9135; ]

== 35.23.351 - Application of RCW  35.23.352 to certain agreements relating to water pollution control, solid waste handling facilities.
RCW 35.23.352 does not apply to the selection of persons or entities to construct or develop water pollution control facilities or to provide water pollution control services under RCW 70A.140.040 or the selection of persons or entities to construct or develop solid waste handling facilities or to provide solid waste handling services under RCW 35.21.156.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201013[2020 c 20 § 1013]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c399.pdf?cite=1989%20c%20399%20§%205[1989 c 399 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c244.pdf?cite=1986%20c%20244%20§%2010[1986 c 244 § 10]; ]

== 35.23.352 - Public works—Contracts—Bids—Small works roster—Purchasing requirements, recycled or reused materials or products.
. Any second-class city or any town may construct any public works, as defined in RCW 39.04.010, by contract or day labor without calling for bids therefor whenever the estimated cost of the work or improvement, including cost of materials, supplies and equipment will not exceed the sum of one hundred sixteen thousand one hundred fifty-five dollars if more than one craft or trade is involved with the public works, or seventy-five thousand five hundred dollars if a single craft or trade is involved with the public works or the public works project is street signalization or street lighting. A public works project means a complete project. The restrictions in this subsection do not permit the division of the project into units of work or classes of work to avoid the restriction on work that may be performed by day labor on a single project.

Whenever the cost of the public work or improvement, including materials, supplies and equipment, will exceed these figures, the same shall be done by contract. All such contracts shall be let at public bidding upon publication of notice calling for sealed bids upon the work. The notice shall be published in the official newspaper, or a newspaper of general circulation most likely to bring responsive bids, at least thirteen days prior to the last date upon which bids will be received. The notice shall generally state the nature of the work to be done that plans and specifications therefor shall then be on file in the city or town hall for public inspections, and require that bids be sealed and filed with the council or commission within the time specified therein. Each bid shall be accompanied by a bid proposal deposit in the form of a cashier's check, postal money order, or surety bond to the council or commission for a sum of not less than five percent of the amount of the bid, and no bid shall be considered unless accompanied by such bid proposal deposit. The council or commission of the city or town shall let the contract to the lowest responsible bidder or shall have power by resolution to reject any or all bids and to make further calls for bids in the same manner as the original call.

When the contract is let then all bid proposal deposits shall be returned to the bidders except that of the successful bidder which shall be retained until a contract is entered into and a bond to perform the work furnished, with surety satisfactory to the council or commission, in accordance with RCW 39.08.030. If the bidder fails to enter into the contract in accordance with his or her bid and furnish a bond within ten days from the date at which he or she is notified that he or she is the successful bidder, the check or postal money order and the amount thereof shall be forfeited to the council or commission or the council or commission shall recover the amount of the surety bond. A low bidder who claims error and fails to enter into a contract is prohibited from bidding on the same project if a second or subsequent call for bids is made for the project.

If no bid is received on the first call the council or commission may readvertise and make a second call, or may enter into a contract without any further call or may purchase the supplies, material or equipment and perform the work or improvement by day labor.

. For the purposes of this section, "lowest responsible bidder" means a bid that meets the criteria under RCW 39.04.350 and has the lowest bid; provided, that if the city issues a written finding that the lowest bidder has delivered a project to the city within the last three years which was late, over budget, or did not meet specifications, and the city does not find in writing that such bidder has shown how they would improve performance to be likely to meet project specifications then the city may choose the second lowest bidder whose bid is within five percent of the lowest bid and meets the same criteria as the lowest bidder.

. The allocation of public works projects to be performed by city or town employees shall not be subject to a collective bargaining agreement.

. In lieu of the procedures of subsection (1) of this section, a second-class city or a town may let contracts using the small works roster process provided in RCW 39.04.155.

Whenever possible, the city or town shall invite at least one proposal from a certified minority or woman contractor who shall otherwise qualify under this section.

. The form required by RCW 43.09.205 shall be to account and record costs of public works in excess of five thousand dollars that are not let by contract.

. The cost of a separate public works project shall be the costs of the materials, equipment, supplies, and labor on that construction project.

. Any purchase of supplies, material, or equipment, except for public work or improvement, where the cost thereof exceeds seven thousand five hundred dollars shall be made upon call for bids.

. Bids shall be called annually and at a time and in the manner prescribed by ordinance for the publication in a newspaper of general circulation in the city or town of all notices or newspaper publications required by law. The contract shall be awarded to the lowest responsible bidder.

. For advertisement and formal sealed bidding to be dispensed with as to purchases with an estimated value of fifteen thousand dollars or less, the council or commission must authorize by resolution, use of the uniform procedure provided in RCW 39.04.190.

. The city or town legislative authority may waive the competitive bidding requirements of this section pursuant to RCW 39.04.280 if an exemption contained within that section applies to the purchase or public work.

. This section does not apply to performance-based contracts, as defined in RCW 39.35A.020(4), that are negotiated under chapter 39.35A RCW.

. Nothing in this section shall prohibit any second-class city or any town from allowing for preferential purchase of products made from recycled materials or products that may be recycled or reused.

. [Empty]
.. Any second-class city or any town may procure public works with a unit priced contract under this section for the purpose of completing anticipated types of work based on hourly rates or unit pricing for one or more categories of work or trades.

.. For the purposes of this section, "unit priced contract" means a competitively bid contract in which public works are anticipated on a recurring basis to meet the business or operational needs of the city or town, under which the contractor agrees to a fixed period indefinite quantity delivery of work, at a defined unit price for each category of work.

.. Unit priced contracts must be executed for an initial contract term not to exceed three years, with the city or town having the option of extending or renewing the unit priced contract for one additional year.

.. Invitations for unit price bids shall include, for purposes of the bid evaluation, estimated quantities of the anticipated types of work or trades, and specify how the city or town will issue or release work assignments, work orders, or task authorizations pursuant to a unit priced contract for projects, tasks, or other work based on the hourly rates or unit prices bid by the contractor. Contracts must be awarded to the lowest responsible bidder as per RCW 39.04.010. Whenever possible, the city or town must invite at least one proposal from a certified minority or woman contractor who otherwise qualifies under this section.

.. Unit price contractors shall pay prevailing wages for all work that would otherwise be subject to the requirements of chapter 39.12 RCW. Prevailing wages for all work performed pursuant to each work order must be the prevailing wage rates in effect at the beginning date for each contract year. Unit priced contracts must have prevailing wage rates updated annually. Intents and affidavits for prevailing wages paid must be submitted annually for all work completed within the previous twelve-month period of the unit priced contract.

. Any second-class city or town that awards a project to a bidder under the criteria described in subsection (2) of this section must make an annual report to the department of commerce that includes the total number of bids awarded to certified minority or women contractors and describing how notice was provided to potential certified minority or women contractors.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5418-S.SL.pdf?cite=2019%20c%20434%20§%201[2019 c 434 § 1]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6143-S.SL.pdf?cite=2018%20c%2074%20§%202[2018 c 74 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1847-S.SL.pdf?cite=2009%20c%20229%20§%204[2009 c 229 § 4]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2527.SL.pdf?cite=2002%20c%2094%20§%202[2002 c 94 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6347-S.SL.pdf?cite=2000%20c%20138%20§%20204[2000 c 138 § 204]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2077-S.SL.pdf?cite=1998%20c%20278%20§%203[1998 c 278 § 3]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5757-S2.SL.pdf?cite=1996%20c%2018%20§%202[1996 c 18 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6025.SL.pdf?cite=1994%20c%20273%20§%209[1994 c 273 § 9]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2018[1994 c 81 § 18]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5048-S.SL.pdf?cite=1993%20c%20198%20§%2010[1993 c 198 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%2056[1989 c 431 § 56]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c168.pdf?cite=1988%20c%20168%20§%203[1988 c 168 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c120.pdf?cite=1987%20c%20120%20§%202[1987 c 120 § 2]; prior:  1985 c 469 § 24; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c219.pdf?cite=1985%20c%20219%20§%202[1985 c 219 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c169.pdf?cite=1985%20c%20169%20§%207[1985 c 169 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c89.pdf?cite=1979%20ex.s.%20c%2089%20§%202[1979 ex.s. c 89 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c41.pdf?cite=1977%20ex.s.%20c%2041%20§%201[1977 ex.s. c 41 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c74.pdf?cite=1974%20ex.s.%20c%2074%20§%202[1974 ex.s. c 74 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c114.pdf?cite=1965%20c%20114%20§%201[1965 c 114 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.23.352[1965 c 7 § 35.23.352]; prior:  1957 c 121 § 1; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c211.pdf?cite=1951%20c%20211%20§%201[1951 c 211 § 1]; prior:   1907 c 241 § 52; RRS § 9055.   1915 c 184 § 31; RRS § 9145. (iii)  1947 c 151 § 1; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c209.pdf?cite=1890%20p%20209%20§%20166[1890 p 209 § 166]; Rem. Supp. 1947 § 9185; ]

== 35.23.371 - Taxation—Street poll tax.
A second-class city may impose upon and collect from every inhabitant of the city over the age of eighteen years an annual street poll tax not exceeding two dollars and no other road poll tax shall be collected within the limits of the city.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2047[1994 c 81 § 47]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c154.pdf?cite=1973%201st%20ex.s.%20c%20154%20§%2051[1973 1st ex.s. c 154 § 51]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c292.pdf?cite=1971%20ex.s.%20c%20292%20§%2061[1971 ex.s. c 292 § 61]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.24.370[1965 c 7 § 35.24.370]; 1905 c 75 § 1, part; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c201.pdf?cite=1890%20p%20201%20§%20154[1890 p 201 § 154]; RRS § 9210, part; ]

== 35.23.380 - Exclusive franchises prohibited.
No exclusive franchise or privilege shall be granted for the use of any street, alley, highway, or public place or any part thereof.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.23.380[1965 c 7 § 35.23.380]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c241.pdf?cite=1907%20c%20241%20§%2032[1907 c 241 § 32]; RRS § 9039; ]

== 35.23.410 - Leasing of street ends on waterfront.
The city council may lease for business purposes portions of the ends of streets terminating in the waterfront or navigable waters of the city with the written consent of all the property owners whose properties abut upon the portion proposed to be leased. The lease may be made for any period not exceeding fifteen years but must provide that at intervals of every five years during the term, the rental to be paid by the lessee shall be readjusted between him or her and the city by mutual agreement, or if they cannot agree by a board of arbitration, one to be chosen by the city, one by the lessee and the third by the other two, their decision to be final. The vote of two-thirds of all the councilmembers elected is necessary to authorize such a lease.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202052[2009 c 549 § 2052]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.23.410[1965 c 7 § 35.23.410]; 1907 c 241 § 67, part; RRS § 9070, part; ]

== 35.23.420 - Notice of lease to be published before execution.
No lease of a portion of the end of a street terminating in the waterfront or navigable waters of the city shall be made until a notice describing the portion of the street proposed to be leased, to whom and for what purpose leased and the proposed rental to be paid has been published by the city clerk in the official newspaper at least fifteen days prior to the execution of the lease.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.23.420[1965 c 7 § 35.23.420]; 1907 c 241 § 67, part; RRS § 9070, part; ]

== 35.23.430 - Railroads in streets to be assessed for street improvement.
If an improvement is made upon a street occupied by a street railway or any railroad enjoying a franchise on the street, the city council shall assess against the railroad its just proportion of making the improvement which shall be not less than the expense of improving the space between the rails of the railroad and for a distance of one foot on each side. The assessment against the railroad shall be made on the rolls of the improvement district the same as against other property in the district and shall be a lien on that portion of the railroad within the district from the time of the equalization of the roll. The lien may be foreclosed by a civil action in superior court and the same period of redemption from any sale on foreclosure shall be allowed as is allowed in cases of sale of real estate upon execution.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.23.430[1965 c 7 § 35.23.430]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c241.pdf?cite=1907%20c%20241%20§%2065[1907 c 241 § 65]; RRS § 9068; ]

== 35.23.440 - Specific powers enumerated.
The city council of each second-class city shall have power and authority:

. Ordinances: To make and pass all ordinances, orders, and resolutions not repugnant to the Constitution of the United States or the state of Washington, or the provisions of this title, necessary for the municipal government and management of the affairs of the city, for the execution of the powers vested in said body corporate, and for the carrying into effect of the provisions of this title.

. License of shows: To fix and collect a license tax, for the purposes of revenue and regulation, on theatres, melodeons, balls, concerts, dances, theatrical, circus, or other performances, and all performances where an admission fee is charged, or which may be held in any house or place where wines or liquors are sold to the participators; also all shows, billiard tables, pool tables, bowling alleys, exhibitions, or amusements.

. Hotels, etc., licenses: To fix and collect a license tax for the purposes of revenue and regulation on and to regulate all taverns, hotels, restaurants, banks, brokers, manufactories, livery stables, express companies and persons engaged in transmitting letters or packages, railroad, stage, and steamboat companies or owners, whose principal place of business is in such city, or who have an agency therein.

. Peddlers', etc., licenses: To license, for the purposes of revenue and regulation, tax, prohibit, suppress, and regulate all raffles, hawkers, peddlers, pawnbrokers, refreshment or coffee stands, booths, or sheds; and to regulate as authorized by state law all tippling houses, dram shops, saloons, bars, and barrooms.

. Dance houses: To prohibit or suppress, or to license and regulate all dance houses, fandango houses, or any exhibition or show of any animal or animals.

. License vehicles: To license for the purposes of revenue and regulation, and to tax hackney coaches, cabs, omnibuses, drays, market wagons, and all other vehicles used for hire, and to regulate their stands, and to fix the rates to be charged for the transportation of persons, baggage, and property.

. Hotel runners: To license or suppress runners for steamboats, taverns, or hotels.

. License generally: To fix and collect a license tax for the purposes of revenue and regulation, upon all occupations and trades, and all and every kind of business authorized by law not heretofore specified. However, on any business, trade, or calling not provided by law to be licensed for state and county purposes, the amount of license shall be fixed at the discretion of the city council, as they may deem the interests and good order of the city may require. A city may not require a business to be licensed based solely upon registration under or compliance with the streamlined sales and use tax agreement.

. Riots: To prevent and restrain any riot or riotous assemblages, disturbance of the peace, or disorderly conduct in any place, house, or street in the city.

. Nuisances: To declare what shall be deemed nuisances; to prevent, remove, and abate nuisances at the expense of the parties creating, causing, or committing or maintaining the same, and to levy a special assessment on the land or premises whereon the nuisance is situated to defray the cost or to reimburse the city for the cost of abating the same.

. Stock pound: To establish, maintain, and regulate a common pound for estrays, and to appoint a poundkeeper, who shall be paid out of the fines and fees imposed and collected of the owners of any animals impounded, and from no other source; to prevent and regulate the running at large of any and all domestic animals within the city limits or any parts thereof, and to regulate or prevent the keeping of such animals within any part of the city.

. Control of certain trades: To control and regulate slaughterhouses, washhouses, laundries, tanneries, forges, and offensive trades, and to provide for their exclusion or removal from the city limits, or from any part thereof.

. Street cleaning: To provide, by regulation, for the prevention and summary removal of all filth and garbage in streets, sloughs, alleys, back yards, or public grounds of such city, or elsewhere therein.

. Gambling, etc.: To prohibit and suppress all gaming and all gambling or disorderly houses, and houses of ill fame, and all immoral and indecent amusements, exhibitions, and shows.

. Markets: To establish and regulate markets and market places.

. Speed of railroad cars: To fix and regulate the speed at which any railroad cars, streetcars, automobiles, or other vehicles may run within the city limits, or any portion thereof.

. City commons: To provide for and regulate the commons of the city.

. Fast driving: To regulate or prohibit fast driving or riding in any portion of the city.

. Combustibles: To regulate or prohibit the loading or storage of gunpowder and combustible or explosive materials in the city, or transporting the same through its streets or over its waters.

. Property: To have, purchase, hold, use, and enjoy property of every name or kind whatsoever, and to sell, lease, transfer, mortgage, convey, control, or improve the same; to build, erect, or construct houses, buildings, or structures of any kind needful for the use or purposes of such city.

. Fire department: To establish, continue, regulate, and maintain a fire department for such city, to change or reorganize the same, and to disband any company or companies of the said department; also, to discontinue and disband said fire department, and to create, organize, establish, and maintain a paid fire department for such city.

. Water supply: To adopt, enter into, and carry out means for securing a supply of water for the use of such city or its inhabitants, or for irrigation purposes therein.

. Overflow of water: To prevent the overflow of the city or to secure its drainage, and to assess the cost thereof to the property benefited.

. House numbers: To provide for the numbering of houses.

. Health board: To establish a board of health; to prevent the introduction and spread of disease; to establish a city infirmary and to provide for the indigent sick; and to provide and enforce regulations for the protection of health, cleanliness, peace, and good order of the city; to establish and maintain hospitals within or without the city limits; to control and regulate interments and to prohibit them within the city limits.

. Harbors and wharves: To build, alter, improve, keep in repair, and control the waterfront; to erect, regulate, and repair wharves, and to fix the rate of wharfage and transit of wharf, and levy dues upon vessels and commodities; and to provide for the regulation of berths, landing, stationing, and removing steamboats, sail vessels, rafts, barges, and all other watercraft; to fix the rate of speed at which steamboats and other steam watercraft may run along the waterfront of the city; to build bridges so as not to interfere with navigation; to provide for the removal of obstructions to the navigation of any channel or watercourses or channels.

. License of steamers: To license steamers, boats, and vessels used in any watercourse in the city, and to fix and collect a license tax thereon.

. Ferry licenses: To license ferries and toll bridges under the law regulating the granting of such license.

. Penalty for violation of ordinances: To provide that violations of ordinances with the punishment for any offense not exceeding a fine of five thousand dollars or imprisonment for up to three hundred sixty-four days, or both fine and imprisonment, but the punishment for any criminal ordinance shall be the same as the punishment provided in state law for the same crime. Alternatively, such a city may provide that a violation of an ordinance constitutes a civil violation subject to monetary penalties or to determine and impose fines for forfeitures and penalties, but no act which is a state crime may be made a civil violation. A violation of an order, regulation, or ordinance relating to traffic including parking, standing, stopping, and pedestrian offenses is a traffic infraction, except that violation of an order, regulation, or ordinance equivalent to those provisions of Title 46 RCW set forth in RCW 46.63.020 remains a misdemeanor.

. Police department: To create and establish a city police; to prescribe their duties and their compensation; and to provide for the regulation and government of the same.

. Examine official accounts: To examine, either in open session or by committee, the accounts or doings of all officers or other persons having the care, management, or disposition of moneys, property, or business of the city.

. Contracts: To make all appropriations, contracts, or agreements for the use or benefit of the city and in the city's name.

. Streets and sidewalks: To provide by ordinance for the opening, laying out, altering, extending, repairing, grading, paving, planking, graveling, macadamizing, or otherwise improving of public streets, avenues, and other public ways, or any portion of any thereof; and for the construction, regulation, and repair of sidewalks and other street improvements, all at the expense of the property to be benefited thereby, without any recourse, in any event, upon the city for any portion of the expense of such work, or any delinquency of the property holders or owners, and to provide for the forced sale thereof for such purposes; to establish a uniform grade for streets, avenues, sidewalks, and squares, and to enforce the observance thereof.

. Waterways: To clear, cleanse, alter, straighten, widen, fill up, or close any waterway, drain, or sewer, or any watercourse in such city when not declared by law to be navigable, and to assess the expense thereof, in whole or in part, to the property specially benefited.

. Sewerage: To adopt, provide for, establish, and maintain a general system of sewerage, draining, or both, and the regulation thereof; to provide funds by local assessments on the property benefited for the purpose aforesaid and to determine the manner, terms, and place of connection with main or central lines of pipes, sewers, or drains established, and compel compliance with and conformity to such general system of sewerage or drainage, or both, and the regulations of said council thereto relating, by the infliction of suitable penalties and forfeitures against persons and property, or either, for nonconformity to, or failure to comply with the provisions of such system and regulations or either.

. Buildings and parks: To provide for all public buildings, public parks, or squares, necessary or proper for the use of the city.

. Franchises: To permit the use of the streets for railroad or other public service purposes.

. Payment of judgments: To order paid any final judgment against such city, but none of its lands or property of any kind or nature, taxes, revenue, franchise, or rights, or interest, shall be attached, levied upon, or sold in or under any process whatsoever.

. Weighing of fuel: To regulate the sale of coal and wood in such city, and may appoint a measurer of wood and weigher of coal for the city, and define his or her duties, and may prescribe his or her term of office, and the fees he or she shall receive for his or her services: PROVIDED, That such fees shall in all cases be paid by the parties requiring such service.

. Hospitals, etc.: To erect and establish hospitals and pesthouses and to control and regulate the same.

. Waterworks: To provide for the erection, purchase, or otherwise acquiring of waterworks within or without the corporate limits of the city to supply such city and its inhabitants with water, and to regulate and control the use and price of the water so supplied.

. City lights: To provide for lighting the streets and all public places of the city and for furnishing the inhabitants of the city with gas, electric, or other light, and for the ownership, purchase or acquisition, construction, or maintenance of such works as may be necessary or convenient therefor: PROVIDED, That no purchase of any such water plant or light plant shall be made without first submitting the question of such purchase to the electors of the city.

. Parks: To acquire by purchase or otherwise land for public parks, within or without the limits of the city, and to improve the same.

. Bridges: To construct and keep in repair bridges, and to regulate the use thereof.

. Power of eminent domain: In the name of and for the use and benefit of the city, to exercise the right of eminent domain, and to condemn lands and property for the purposes of streets, alleys, parks, public grounds, waterworks, or for any other municipal purpose and to acquire by purchase or otherwise such lands and property as may be deemed necessary for any of the corporate uses provided for by this title, as the interests of the city may from time to time require.

. To provide for the assessment of taxes: To provide for the assessment, levying, and collecting of taxes on real and personal property for the corporate uses and purposes of the city and to provide for the payment of the debts and expenses of the corporation.

. Local improvements: To provide for making local improvements, and to levy and collect special assessments on the property benefited thereby and for paying the same or any portion thereof; to determine what work shall be done or improvements made, at the expense, in whole or in part, of the adjoining, contiguous, or proximate property, and to provide for the manner of making and collecting assessments therefor.

. Cemeteries: To regulate the burial of the dead and to establish and regulate cemeteries, within or without the corporate limits, and to acquire lands therefor by purchase or otherwise.

. Fire limits: To establish fire limits with proper regulations and to make all needful regulations for the erection and maintenance of buildings or other structures within the corporate limits as safety of persons or property may require, and to cause all such buildings and places as may from any cause be in a dangerous state to be put in a safe condition; to regulate the manner in which stone, brick, and other buildings, party walls, and partition fences shall be constructed and maintained.

. Safety and sanitary measures: To require the owners of public halls, theaters, hotels, and other buildings to provide suitable means of exit and proper fire escapes; to provide for the cleaning and purification of watercourses and canals and for the draining and filling up of ponds on private property within its limits when the same shall be offensive to the senses or dangerous to the health, and to charge the expense thereof to the property specially benefited, and to regulate and control and provide for the prevention and punishment of the defilement or pollution of all streams running in or through its corporate limits and a distance of five miles beyond its corporate limits, and of any stream or lake from which the water supply of the city is or may be taken and for a distance of five miles beyond its source of supply, and to make all quarantine and other regulations as may be necessary for the preservation of the public health and to remove all persons afflicted with any contagious disease to some suitable place to be provided for that purpose.

. To regulate liquor traffic: To regulate the selling or giving away of intoxicating, spirituous, malt, vinous, mixed, or fermented liquors as authorized by the general laws of the state.

. To establish streets on tidelands: To project or extend or establish streets over and across any tidelands within the limits of such city.

. To provide for the general welfare.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5168-S.SL.pdf?cite=2011%20c%2096%20§%2026[2011 c 96 § 26]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202053[2009 c 549 § 2053]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3126-S.SL.pdf?cite=2008%20c%20129%20§%202[2008 c 129 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2019[1994 c 81 § 19]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1544-S.SL.pdf?cite=1993%20c%2083%20§%205[1993 c 83 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c278.pdf?cite=1986%20c%20278%20§%204[1986 c 278 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c258.pdf?cite=1984%20c%20258%20§%20803[1984 c 258 § 803]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c189.pdf?cite=1984%20c%20189%20§%205[1984 c 189 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c136.pdf?cite=1979%20ex.s.%20c%20136%20§%2028[1979 ex.s. c 136 § 28]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c316.pdf?cite=1977%20ex.s.%20c%20316%20§%2021[1977 ex.s. c 316 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c116.pdf?cite=1965%20ex.s.%20c%20116%20§%207[1965 ex.s. c 116 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.23.440[1965 c 7 § 35.23.440]; prior:  1907 c 241 § 29; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c148.pdf?cite=1890%20p%20148%20§%2038[1890 p 148 § 38]; RRS § 9034; ]

== 35.23.442 - City and town license fees and taxes on financial institutions.
See chapter 82.14A RCW.

[ ]

== 35.23.443 - City license fees or taxes on certain business activities to be at a single uniform rate.
See RCW 35.21.710.

[ ]

== 35.23.444 - Nonpolluting power generation by individual—Exemption from regulation—Authorization to contract with utility.
See chapter 80.58 RCW.

[ ]

== 35.23.445 - Hydroelectric resources—Separate legal authority—Creation by irrigation districts and cities, towns, or public utility districts.
See RCW 87.03.825 through 87.03.840.

[ ]

== 35.23.452 - Additional powers—Acquisition, control, and disposition of property.
The city council of such city shall have power to purchase, lease, or otherwise acquire real estate and personal property necessary or proper for municipal purposes and to control, lease, sublease, convey or otherwise dispose of the same; to acquire and plat land for cemeteries and parks and provide for the regulation thereof, including but not limited to the right to lease any waterfront and other lands adjacent thereto owned by it for manufacturing, commercial or other business purposes; including but not limited to the right to lease for wharf, dock and other purposes of navigation and commerce such portions of its streets which bound upon or terminate in its waterfront or the navigable waters of such city, subject, however, to the written consent of the lessees of a majority of the square feet frontage of the harbor area abutting on any street proposed to be so leased. No lease of streets or waterfront shall be for longer than ten years and the rental therefor shall be fixed by the city council. Every such lease shall contain a clause that at intervals of every five years during the term thereof the rental to be paid by the lessee shall be readjusted between the lessee and the city by mutual agreement, or in default of such mutual agreement that the rental shall be fixed by arbitrators to be appointed one by the city council, one by the lessee and the third by the two thus appointed. No such lease shall be made until the city council has first caused notice thereof to be published in the official newspaper of such city at least fifteen days and in one issue thereof each week prior to the making of such lease, which notice shall describe the portion of the street proposed to be leased, to whom, for what purpose, and the rental to be charged therefor. The city may improve part of such waterfront or street extensions by building inclines, wharves, gridirons and other accommodations for shipping, commerce and navigation and may charge and collect for service and use thereof reasonable rates and tolls.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.24.300[1965 c 7 § 35.24.300]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c155.pdf?cite=1963%20c%20155%20§%201[1963 c 155 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c184.pdf?cite=1915%20c%20184%20§%2015[1915 c 184 § 15]; RRS § 9128; ]

== 35.23.454 - Additional powers—Parking meter revenue for revenue bonds.
All second-class cities and towns are authorized to use parking meter revenue as a base for obtaining revenue bonds for use in improvement of streets, roads, alleys, and such other related public works.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2044[1994 c 81 § 44]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.24.305[1965 c 7 § 35.24.305]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c166.pdf?cite=1957%20c%20166%20§%201[1957 c 166 § 1]; ]

== 35.23.455 - Additional powers—Construction and operation of boat harbors, marinas, docks, etc.
The legislative body of any second-class city or town which contains, or abuts upon, any bay, lake, sound, river or other navigable waters, may construct, operate and maintain any boat harbor, marina, dock or other public improvement, for the purposes of commerce, recreation or navigation.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2020[1994 c 81 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c154.pdf?cite=1965%20c%20154%20§%201[1965 c 154 § 1]; ]

== 35.23.456 - Additional powers—Ambulances and first aid equipment.
A second-class city, where commercial ambulance service is not readily available, shall have the power:

. To authorize the operation of municipally-owned ambulances which may serve the city and may serve for emergencies surrounding rural areas;

. To authorize the operation of other municipally-owned first aid equipment which may serve the city and surrounding rural areas;

. To contract with the county or with another municipality for emergency use of city-owned ambulances or other first aid equipment: PROVIDED, That the county or other municipality shall contribute at least the cost of maintenance and operation of the equipment attributable to its use thereof; and

. To provide that such ambulance service may be used to transport persons in need of emergency hospital care to hospitals beyond the city limits.

The council may, in its discretion, make a charge for the service authorized by this section: PROVIDED, That such ambulance service shall not enter into competition or competitive bidding where private ambulance service is available.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2045[1994 c 81 § 45]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.24.306[1965 c 7 § 35.24.306]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c131.pdf?cite=1963%20c%20131%20§%201[1963 c 131 § 1]; ]

== 35.23.457 - Conveyance or lease of space above real property or structures or improvements.
See RCW 35.22.302.

[ ]

== 35.23.460 - Employees' group insurance—False arrest insurance.
Subject to chapter 48.62 RCW, any second-class city or town may contract with an insurance company authorized to do business in this state to provide group insurance for its employees including group false arrest insurance for its law enforcement personnel, and pursuant thereto may use a portion of its revenues to pay an employer's portion of the premium for such insurance, and may make deductions from the payrolls of employees for the amount of the employees' contribution and may apply the amount deducted in payment of the employees' portion of the premium.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2021[1994 c 81 § 21]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1907-S.SL.pdf?cite=1991%20sp.s.%20c%2030%20§%2019[1991 sp.s. c 30 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.23.460[1965 c 7 § 35.23.460]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c127.pdf?cite=1963%20c%20127%20§%201[1963 c 127 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c162.pdf?cite=1947%20c%20162%20§%201[1947 c 162 § 1]; RRS § 9592-160; ]

== 35.23.470 - Publicity fund.
Every city of the second class may create a publicity fund to be used exclusively for exploiting and advertising the general advantages and opportunities of the city and its vicinity. After providing by ordinance for a publicity fund the city council may use therefor an annual amount not exceeding sixty-two and one-half cents per thousand dollars of assessed valuation of the taxable property in the city.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2022[1994 c 81 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c195.pdf?cite=1973%201st%20ex.s.%20c%20195%20§%2016[1973 1st ex.s. c 195 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.23.470[1965 c 7 § 35.23.470]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c57.pdf?cite=1913%20c%2057%20§%201[1913 c 57 § 1]; RRS § 9035; ]

== 35.23.480 - Publicity board.
The publicity board administering the publicity fund shall consist of three members nominated by a recognized commercial organization in the city, then appointed by the mayor and confirmed by at least a two-thirds vote of the city council. The commercial organization must be incorporated, must be representative and public, devoted exclusively to the work usually devolving upon such organizations and have not less than two hundred bona fide dues-paying members; if more than one organization in the city meets the qualifications, the oldest one shall be designated to make the nominations.

Members of the publicity board must be resident property owners and voters in the city and after their appointment and confirmation must qualify by taking the oath of office and filing a bond with the city in the sum of one thousand dollars conditioned upon the faithful performance of their duties. They shall be appointed in December and their terms shall be for one year commencing on the second Monday in January after their appointment and until their successors are appointed and qualified. Any member of the board may be removed by the mayor at the request of the organization which nominated the members after a majority vote of the entire membership of the organization favoring the removal, taken at a regular meeting.

Members of the publicity board shall serve without remuneration.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.23.480[1965 c 7 § 35.23.480]; 1913 c 57 § 2, part; RRS § 9036, part; ]

== 35.23.490 - Limitations on use of publicity fund.
All expenditures shall be made under direction of the board of publicity. No part of the publicity fund shall ever be paid to any newspaper, magazine, or periodical published within the city or county in which the city is situated, for advertising, or write-ups or for any other service or purpose and no part of the fund shall be expended for the purpose of making exhibits at any fair, exposition or the like.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.23.490[1965 c 7 § 35.23.490]; 1913 c 57 § 2, part; RRS § 9036, part; ]

== 35.23.505 - Local improvement guaranty fund—Investment in city's own guaranteed bonds.
The city treasurer of any second-class city, by and with the consent of the city council or finance committee of the city council, may invest any portion of its local improvement guaranty fund in the city's own guaranteed local improvement bonds in an amount not to exceed ten percent of the total issue of bonds in any one local improvement district: PROVIDED, That no such investment shall be made in an amount which will affect the ability of the local improvement guaranty fund to meet its obligations as they accrue, and that if all the bonds have the same maturity, the bonds having the highest numbers shall be purchased.

The interest received shall be credited to the local improvement guaranty fund.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2048[1994 c 81 § 48]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.24.400[1965 c 7 § 35.24.400]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c145.pdf?cite=1941%20c%20145%20§%202[1941 c 145 § 2]; RRS § 9138-2; ]

== 35.23.515 - Utilities—City may contract for service or construct own facilities.
The city council of every city of the second class may contract for supplying the city with water, light, power, and heat for municipal purposes; and within or without the city may acquire, construct, repair, and manage pumps, aqueducts, reservoirs, plants, or other works necessary or proper for irrigation purposes or for supplying water, light, power, or heat or any by-product thereof for the use of the city and any person within the city and dispose of any excess of its supply to any person without the city.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2049[1994 c 81 § 49]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.24.410[1965 c 7 § 35.24.410]; 1917 c 124 § 1, part; 1915 c 184 § 16, part; RRS § 9129, part; ]

== 35.23.525 - Utilities—Method of acquisition—Bonds.
To pay the original cost of water, light, power, or heat systems, every city of the second class may issue:

. General bonds to be retired by general tax levies against all the property within the city limits then existing or as they may thereafter be extended; or

. Utility bonds under the general authority given to all cities for the acquisition or construction of public utilities.

Extensions to plants may be made either

. By general bond issue,

. By general tax levies, or

. By creating local improvement districts in accordance with statutes governing their establishment.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2050[1994 c 81 § 50]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.24.420[1965 c 7 § 35.24.420]; 1917 c 124 § 1, part; 1915 c 184 § 16, part; RRS § 9129, part; ]

== 35.23.535 - Utilities—Maintenance and operation—Rates.
No taxes shall be imposed for maintenance and operating charges of city owned water, light, power, or heating works or systems.

Rates shall be fixed by ordinance for supplying water, light, power, or heat for commercial, domestic, or irrigation purposes sufficient to pay for all operating and maintenance charges. If the rates in force produce a greater amount than is necessary to meet operating and maintenance charges, the rates may be reduced or the excess income may be transferred to the city's current expense fund.

Complete separate accounts for municipal utilities must be kept under the system and on forms prescribed by the state auditor.

The term "maintenance and operating charges," as used in this section includes all necessary repairs, replacement, interest on any debts incurred in acquiring, constructing, repairing and operating plants and departments and all depreciation charges. This term shall also include an annual charge equal to four percent on the cost of the plant or system, as determined by the state auditor to be paid into the current expense fund, except that where utility bonds have been or may hereafter be issued and are unpaid no payment shall be required into the current expense fund until such bonds are paid.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1889.SL.pdf?cite=1995%20c%20301%20§%2037[1995 c 301 § 37]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.24.430[1965 c 7 § 35.24.430]; 1917 c 124 § 1, part; 1915 c 184 § 16, part; RRS § 9129, part; ]

== 35.23.545 - Procedure to attack consolidation or annexation of territory.
Proceedings attacking the validity of the consolidation of a city of the second class or the annexation of territory to a city of the second class shall be by quo warranto only, instituted by the prosecuting attorney of the county in which the city is located or by a person interested in the proceedings whose interest must clearly be shown. The quo warranto proceedings must be commenced within one year after the consolidation or annexation proceedings complained of and no error, irregularity, or defect of any kind shall be the basis for invalidating a consolidation or annexation after one year.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2051[1994 c 81 § 51]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.24.440[1965 c 7 § 35.24.440]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c153.pdf?cite=1923%20c%20153%20§%201[1923 c 153 § 1]; RRS § 8913-1; ]

== 35.23.555 - Criminal code repeals by city operating municipal court—Agreement covering costs of handling resulting criminal cases—Arbitration.
A city of the second class operating a municipal court may not repeal in its entirety that portion of its municipal code defining crimes or repeal a provision of its municipal code which defines a crime equivalent to an offense listed in RCW 46.63.020 unless the municipality has reached an agreement with the appropriate county under chapter 39.34 RCW under which the county is to be paid a reasonable amount for costs associated with prosecution, adjudication, and sentencing in criminal cases filed in district court as a result of the repeal. The agreement shall include provisions for periodic review and renewal of the terms of the agreement. If the municipality and the county are unable to agree on the terms for renewal of the agreement, they shall be deemed to have entered into an agreement to submit the issue to arbitration under chapter 7.04A RCW. Pending conclusion of the arbitration proceeding, the terms of the agreement shall remain in effect. The municipality and the county have the same rights and are subject to the same duties as other parties who have agreed to submit to arbitration under chapter 7.04A RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1054-S.SL.pdf?cite=2005%20c%20433%20§%2039[2005 c 433 § 39]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2052[1994 c 81 § 52]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c258.pdf?cite=1984%20c%20258%20§%20206[1984 c 258 § 206]; ]

== 35.23.560 - Waterworks—Construction by city or by district assessments.
All cities and towns within the state, other than cities of the first class, which are empowered to construct waterworks for irrigation and domestic purposes, may do so either by the entire city or by assessment districts as the mayor and council may determine.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.23.560[1965 c 7 § 35.23.560]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1901c117.pdf?cite=1901%20c%20117%20§%201[1901 c 117 § 1]; RRS § 9526; ]

== 35.23.570 - Waterworks—Plans—Special assessments.
Before letting any contract for the construction of any waterworks for irrigation and domestic purposes, the mayor and council shall by ordinance or resolution adopt the plans therefor and shall fix and establish the assessment district, if the same is to be constructed at the expense of the district, and such cities and towns are authorized to charge the expense of such waterworks for irrigation and domestic purposes to all the property included within such district which is contiguous or proximate to any streets in which any main pipe or lateral pipe of such waterworks for irrigation and domestic purposes, is to be placed, and to levy special assessments upon such property to pay therefor, which assessment shall be levied in accordance with the last general assessment of the property within said district for city purposes.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2023[1994 c 81 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.23.570[1965 c 7 § 35.23.570]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1901c117.pdf?cite=1901%20c%20117%20§%202[1901 c 117 § 2]; RRS § 9527; ]

== 35.23.580 - Waterworks—Procedure—Bonds.
For the purpose of providing for, constructing and maintaining such waterworks for irrigation and domestic purposes and issuing bonds to pay therefor, such cities and towns may proceed in all ways in accordance with, and apply all the provisions of, law relating to local improvement assessments.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.23.580[1965 c 7 § 35.23.580]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1901c117.pdf?cite=1901%20c%20117%20§%203[1901 c 117 § 3]; RRS § 9528; ]

== 35.23.680 - Cities of ten thousand or more may frame charter without changing classification.
See chapter 35.22 RCW.

[ ]

== 35.23.705 - Purchase of electric power and energy from joint operating agency.
A city of the second class may contract to purchase from a joint operating agency electric power and energy required for its present or future requirements. For projects the output of which is limited to qualified alternative energy resources as defined by RCW 19.29A.090(3), the contract may include the purchase of capability of the projects to produce electricity in addition to the actual output of the projects. The contract may provide that the city must make the payments required by the contract whether or not a project is completed, operable, or operating and notwithstanding the suspension, interruption, interference, reduction, or curtailment of the output of a project or the power and energy contracted for. The contract may also provide that payments under the contract are not subject to reduction, whether by offset or otherwise, and shall not be conditioned upon the performance or nonperformance of the joint operating agency or a city, town, or public utility district under the contract or other instrument.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1854-S.SL.pdf?cite=2003%20c%20138%20§%205[2003 c 138 § 5]; ]

== 35.23.800 - Code city retaining former second-class city plan—Elective officers.
In a city initially classified as a second-class city prior to January 1, 1993, that retained its second-class city plan of government when the city reorganized as a noncharter code city, the elective officers shall consist of a mayor, twelve councilmembers, a city clerk, and a city treasurer.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2024[1994 c 81 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c3.pdf?cite=1987%20c%203%20§%206[1987 c 3 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.23.020[1965 c 7 § 35.23.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c83.pdf?cite=1949%20c%2083%20§%201[1949 c 83 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c241.pdf?cite=1907%20c%20241%20§%202[1907 c 241 § 2]; RRS § 9007; ]

== 35.23.805 - Code city retaining former second-class city plan—Elections—Terms of office.
In a city initially classified as a second-class city prior to January 1, 1993, that retained its second-class city plan of government when the city reorganized as a noncharter code city, the terms of office of mayor, city clerk, city treasurer and councilmembers shall be four years, and until their successors are elected and qualified and assume office in accordance with RCW 29A.60.280, but not more than six councilmembers normally shall be elected in any one year to fill a full term.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1806-S.SL.pdf?cite=2015%20c%2053%20§%2040[2015 c 53 § 40]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2025[1994 c 81 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c3.pdf?cite=1987%20c%203%20§%207[1987 c 3 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c126.pdf?cite=1979%20ex.s.%20c%20126%20§%2021[1979 ex.s. c 126 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.23.040[1965 c 7 § 35.23.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c200.pdf?cite=1963%20c%20200%20§%2014[1963 c 200 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c86.pdf?cite=1959%20c%2086%20§%203[1959 c 86 § 3]; prior:   1951 c 71 § 1; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c120.pdf?cite=1909%20c%20120%20§%204[1909 c 120 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c241.pdf?cite=1907%20c%20241%20§%203[1907 c 241 § 3]; RRS § 9008.   1951 c 71 § 1; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c241.pdf?cite=1907%20c%20241%20§%204[1907 c 241 § 4]; RRS § 9009; ]

== 35.23.810 - Code city retaining former second-class city plan—Mayor—General duties.
In a city initially classified as a second-class city prior to January 1, 1993, that retained its second-class city plan of government when the city reorganized as a noncharter code city, the mayor shall be the chief executive officer of the city and shall:

. Have general supervision over the several departments of the city government and over all its interests;

. Preside over the city council when present;

. Once in three months, submit a general statement of the condition of the various departments and recommend to the city council such measures as the mayor deems expedient for the public health or improvement of the city, its finances or government; and

. Countersign all warrants and licenses, deeds, leases and contracts requiring signature issued under and by authority of the city.

If there is a vacancy in the office of mayor or the mayor is absent from the city, or is unable from any cause to discharge the duties of the office, the president of the council shall act as mayor, exercise all the powers and be subject to all the duties of the mayor.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2026[1994 c 81 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.23.080[1965 c 7 § 35.23.080]; 1907 c 241 § 16, part; RRS § 9021, part.  1907 c 241 § 17, part; RRS § 9022, part; ]

== 35.23.815 - Code city retaining former second-class city plan—Appointive officers.
In a city initially classified as a second-class city prior to January 1, 1993, that retained its second-class city plan of government when the city reorganized as a noncharter code city, the appointive officers shall be a chief of police, city attorney, health officer, and street commissioner; the council may also create by ordinance the offices of superintendent of irrigation, city engineer, harbor master, pound keeper, city jailer, chief of the fire department, and any other offices necessary to discharge the functions of the city and for whose election or appointment no other provision is made. If a paid fire department is established therein a chief engineer and one or more assistant engineers may be appointed. If a free library and reading room is established therein five library trustees shall be appointed. The council by ordinance shall prescribe the duties of the officers and fix their compensation subject to the provisions of any statutes pertaining thereto.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2027[1994 c 81 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.23.120[1965 c 7 § 35.23.120]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c83.pdf?cite=1949%20c%2083%20§%202[1949 c 83 § 2]; Rem. Supp. 1949 § 9007A; ]

== 35.23.820 - Code city retaining former second-class city plan—Health officer.
In a city initially classified as a second-class city prior to January 1, 1993, that retained its second-class city plan of government when the city reorganized as a noncharter code city, the council shall create the office of city health officer, prescribe the duties and qualifications of this office and fix the compensation for the office.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2028[1994 c 81 § 28]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.23.150[1965 c 7 § 35.23.150]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c241.pdf?cite=1907%20c%20241%20§%2064[1907 c 241 § 64]; RRS § 9067; ]

== 35.23.825 - Code city retaining former second-class city plan—Street commissioner.
In a city initially classified as a second-class city prior to January 1, 1993, that retained its second-class city plan of government when the city reorganized as a noncharter code city, the street commissioner shall be under the direction of the mayor and city council shall have control of the streets and public places of the city and shall perform such duties as the city council may prescribe.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2029[1994 c 81 § 29]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.23.160[1965 c 7 § 35.23.160]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c241.pdf?cite=1907%20c%20241%20§%2023[1907 c 241 § 23]; RRS § 9028; ]

== 35.23.830 - Code city retaining former second-class city plan—Appointment of officers—Confirmation.
In a city initially classified as a second-class city prior to January 1, 1993, that retained its second-class city plan of government when the city reorganized as a noncharter code city, the mayor shall appoint all the appointive officers of the city subject to confirmation by the city council. If the council refuses to confirm any nomination of the mayor, the mayor shall nominate another person for that office within ten days thereafter, and may continue to so nominate until a nominee is confirmed. If the mayor fails to make another nomination for the same office within ten days after the rejection of a nominee, the city council shall elect a suitable person to fill the office during the term. The affirmative vote of not less than seven councilmembers is necessary to confirm any nomination made by the mayor.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2030[1994 c 81 § 30]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.23.180[1965 c 7 § 35.23.180]; 1907 c 241 § 8, part; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c145.pdf?cite=1890%20p%20145%20§%2025[1890 p 145 § 25]; RRS § 9013, part; ]

== 35.23.835 - Code city retaining former second-class city plan—Oath and bond of officers.
Before entering upon official duties and within ten days after receiving notice of being elected or appointed to city office, every officer of a city initially classified as a second-class city prior to January 1, 1993, that retained its second-class city plan of government when the city reorganized as a noncharter code city shall qualify by taking the oath of office and by filing such bond duly approved as may be required. The oath of office shall be filed with the county auditor. If no notice of election or appointment was received, the officer must qualify on or before the date fixed for the assumption of the duties of the office. The city council shall fix the amount of all official bonds and may designate what officers shall be required to give bonds in addition to those required to do so by statute.

All official bonds shall be approved by the city council and when so approved shall be filed with the city clerk except the city clerk's which shall be filed with the mayor. No city officer shall be eligible as a surety upon any bond running to the city as obligee.

The city council may require a new or additional bond of any officer whenever it deems it expedient.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2031[1994 c 81 § 31]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c3.pdf?cite=1987%20c%203%20§%208[1987 c 3 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c167.pdf?cite=1986%20c%20167%20§%2017[1986 c 167 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.23.190[1965 c 7 § 35.23.190]; 1907 c 241 § 10, part; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c145.pdf?cite=1890%20p%20145%20§%2029[1890 p 145 § 29]; RRS § 9015, part.   1907 c 241 § 11; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c145.pdf?cite=1890%20p%20145%20§%2029[1890 p 145 § 29]; RRS § 9016; ]

== 35.23.840 - Code city retaining former second-class city plan—City council—How constituted.
In a city initially classified as a second-class city prior to January 1, 1993, that retained its second-class city plan of government when the city reorganized as a noncharter code city, the mayor and twelve councilmembers shall constitute the city council. At the first council meeting in each calendar year, the city council shall elect one of their own body to serve as president of the council.

The mayor shall preside at all meetings at which the mayor is present. In the absence of the mayor, the president of the council shall preside. In the absence of both the mayor and the president of the council, the council may elect a president pro tempore from its own body. The president pro tempore shall have all the powers of the president of the council during the session of the council at which the president pro tempore is presiding.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2032[1994 c 81 § 32]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.23.250[1965 c 7 § 35.23.250]; 1907 c 241 § 17, part; RRS § 9022, part.   1907 c 247 § 27; RRS § 9032. (iii) 1907 c 241 § 28, part; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c148.pdf?cite=1890%20p%20148%20§%2037[1890 p 148 § 37]; RRS § 9033, part; ]

== 35.23.845 - Code city retaining former second-class city plan—City council—Presiding officer—Voting rights.
In a city initially classified as a second-class city prior to January 1, 1993, that retained its second-class city plan of government when the city reorganized as a noncharter code city, the mayor shall have a vote only in the case of a tie in the votes of the councilmembers. The president of the council while presiding or the president pro tempore shall have the right to vote upon all questions coming before the council.

A majority of all the members elected shall be necessary to pass any ordinance appropriating for any purpose the sum of five hundred dollars or upwards or any ordinance imposing any assessment, tax, or license or in any wise increasing or diminishing the city revenue.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2033[1994 c 81 § 33]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.23.280[1965 c 7 § 35.23.280]; 1907 c 241 § 28, part; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c148.pdf?cite=1890%20p%20148%20§%2037[1890 p 148 § 37]; RRS § 9033, part.   1907 c 241 § 61; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c159.pdf?cite=1890%20p%20159%20§%2051[1890 p 159 § 51]; RRS § 9064; ]

== 35.23.850 - Code city retaining former second-class city plan—Wards—Division of city into.
In any city initially classified as a second-class city prior to January 1, 1993, that retained its second-class city plan of government when the city reorganized as a noncharter code city, the city council may divide the city into wards, not exceeding six in all, or change the boundaries of existing wards at any time less than one hundred twenty days before a municipal general election. Unless the city is dividing into wards or changing the boundaries of existing wards under RCW 29A.92.040 or 29A.92.110, no change in the boundaries of wards shall affect the term of any councilmember, and councilmembers shall serve out their terms in the wards of their residences at the time of their elections. However, if these boundary changes result in one ward being represented by more councilmembers than the number to which it is entitled, those having the shortest unexpired terms shall be assigned by the council to wards where there is a vacancy, and the councilmembers so assigned shall be deemed to be residents of the wards to which they are assigned for purposes of determining whether those positions are vacant.

If the city is dividing into wards or changing the boundaries of existing wards under RCW 29A.92.040 or 29A.92.110, all council positions are subject to election at the next regular election.

The representation of each ward in the city council shall be in proportion to the population as nearly as is practicable.

Wards shall be redrawn as provided in chapter 29A.76 RCW. Wards shall be used as follows: (1) Only a resident of the ward may be a candidate for, or hold office as, a councilmember of the ward; and (2) only voters of the ward may vote at a primary to nominate candidates for a councilmember of the ward. Voters of the entire city may vote at the general election to elect a councilmember of a ward, unless the city had prior to January 1, 1994, limited the voting in the general election for any or all council positions to only voters residing within the ward associated with the council positions. If a city had so limited the voting in the general election to only voters residing within the ward, then the city shall be authorized to continue to do so. The elections for the remaining council position or council positions that are not associated with a ward shall be conducted as if the wards did not exist.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5266-S.SL.pdf?cite=2019%20c%20454%20§%206[2019 c 454 § 6]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1806-S.SL.pdf?cite=2015%20c%2053%20§%2041[2015 c 53 § 41]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1015.SL.pdf?cite=1995%20c%20134%20§%2010[1995 c 134 § 10]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2278-S.SL.pdf?cite=1994%20c%20223%20§%2016[1994 c 223 § 16]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2034[1994 c 81 § 34]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.23.530[1965 c 7 § 35.23.530]; prior:  1907 c 241 § 14; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c147.pdf?cite=1890%20p%20147%20§%2035[1890 p 147 § 35]; RRS § 9019; ]

== 35.23.860 - Telecommunications services and facilities authorized—Requirements.
. A second-class city may construct, purchase, acquire, develop, finance, lease, license, provide, contract for, interconnect, alter, improve, repair, operate, and maintain telecommunications services or telecommunications facilities for the purpose of furnishing the second-class city and its inhabitants with telecommunications services. The second-class city has full authority to regulate and control the use, distribution, and price of the services.

. [Empty]
.. Before providing telecommunications services pursuant to subsection (1) of this section, a second-class city must examine and report to its governing body and to the state broadband office the following about the area to be served by the second-class city:

... An assessment of the current availability of broadband infrastructure and its adequacy to provide high-speed internet access and other advanced telecommunications services to end users;

... The location of where retail telecommunications services will be provided;

... Evidence relating to the unserved nature of the community in which retail telecommunications services will be provided;

... Expected costs of providing retail telecommunications services to customers to be served by the second-class city;

.. Evidence that proposed telecommunications infrastructure will be capable of scaling to greater download and upload speeds to meet state broadband goals under RCW 43.330.536;

.. Sources of funding for the project that will supplement any grant or loan awards; and

.. A strategic plan to maintain long-term operation of the infrastructure, and the expected installation charges and monthly costs for end users.

.. The state broadband office must post a review of the proposed project on its website.

. For purposes of this section:

.. "Telecommunications" has the same meaning as defined in RCW 80.04.010.

.. "Unserved" means an area of Washington in which households and businesses lack access to broadband service at a minimum 100 megabits per second download speed and at a minimum 20 megabits per second upload speed.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1336-S.SL.pdf?cite=2021%20c%20294%20§%206[2021 c 294 § 6]; ]

