= 35.89 - Water redemption bonds.
:toc:

== 35.89.010 - Authority to issue water redemption bonds.
If a public water system has been constructed within any local improvement district of any city or town for the construction of which bonds of the local improvement district were issued and are outstanding and unpaid, and if the city or town has taken over the system or is operating it as a public utility or has incorporated it into or connected it with any system operated by city or town as a public utility, from the operation of which such city or town derives a revenue, the city or town may by resolution of its council authorize the issue of bonds to an amount not exceeding the amount of the local improvement bonds issued for the construction of the water system then outstanding and unpaid with interest due and unpaid, and may redeem the outstanding local improvement bonds by exchanging therefor an equal amount at par of the bonds authorized by this chapter. The new bonds shall be called water redemption bonds.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.89.010[1965 c 7 § 35.89.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c85.pdf?cite=1929%20c%2085%20§%201[1929 c 85 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c52.pdf?cite=1923%20c%2052%20§%201[1923 c 52 § 1]; RRS § 9154-1.  1923 c 52 § 2, part; RRS § 9154-2, part; ]

== 35.89.020 - Bonds—Terms—Execution—Rights of owner.
. Water redemption bonds shall be in denominations of not more than one thousand nor less than one hundred dollars each, and shall bear interest at a rate or rates as authorized by the city or town council, payable semiannually, and shall bear a serial number and shall be signed by the mayor of the city or town and shall be otherwise executed in such manner and payable at such time and place not exceeding twenty years after the date of issue as the city or town council shall determine and such bonds shall be payable only out of the special fund created by authority of this chapter and shall be a valid claim of the owner thereof only against that fund and the fixed portion or amount of the revenues of the water system pledged to the fund, and shall not constitute an indebtedness of the city or town. Such bonds may be in any form, including bearer bonds or registered bonds as provided in RCW 39.46.030.

. Notwithstanding subsection (1) of this section, such bonds may be issued and sold in accordance with chapter 39.46 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c167.pdf?cite=1983%20c%20167%20§%2066[1983 c 167 § 66]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c56.pdf?cite=1970%20ex.s.%20c%2056%20§%2046[1970 ex.s. c 56 § 46]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c232.pdf?cite=1969%20ex.s.%20c%20232%20§%2023[1969 ex.s. c 232 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.89.020[1965 c 7 § 35.89.020]; 1923 c 52 § 2, part; RRS § 9154-2, part; ]

== 35.89.030 - Bonds exchange—Subrogation.
Water redemption bonds issued under the authority of this chapter shall only be sold or disposed of in exchange for an equal amount in par value of principal and interest of the local improvement district bonds issued for the construction of water systems taken over and operated by the city or town, or incorporated into or connected with a water system operated by it.

Upon the exchange of the water redemption bonds authorized by this chapter for local improvement district bonds the city or town shall be subrogated to all the rights of the owners and holders of such local improvement district bonds against the property of the local improvement district and against any person or corporation liable thereon.

Any money derived by the city or town from the sale or enforcement of such local improvement district bonds shall be paid into the city's water redemption fund.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.89.030[1965 c 7 § 35.89.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c52.pdf?cite=1923%20c%2052%20§%203[1923 c 52 § 3]; RRS § 9154-3; ]

== 35.89.040 - Water redemption fund—Creation.
The city or town council before issuing water redemption bonds shall by ordinance establish a fund for the payment of the bonds at maturity and of interest thereon as it matures to be designated the water redemption fund.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.89.040[1965 c 7 § 35.89.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c52.pdf?cite=1923%20c%2052%20§%204[1923 c 52 § 4]; RRS § 9154-4; ]

== 35.89.050 - Water redemption fund—Sources.
Every city and town shall have power to regulate and control the use and price of water supplied through a water system taken over from a local improvement district.

It shall establish such rates and charges for the water as shall be sufficient after providing for the operation and maintenance of the system to provide for the payment of the water redemption bonds at maturity and of interest thereon as it matures, and such portion shall be included in and collected as a part of the charges made by such city or town for water supplied through such water system and such portion shall be paid into the water redemption fund.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.89.050[1965 c 7 § 35.89.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c52.pdf?cite=1923%20c%2052%20§%205[1923 c 52 § 5]; RRS § 9154-5; ]

== 35.89.060 - Water redemption fund—Trust fund.
All moneys paid into or collected for the water redemption fund shall be used for the payment of principal and interest of the water redemption bonds issued under the authority of this chapter and no part thereof while any of said bonds are outstanding and unpaid, shall be diverted to any other fund or use: PROVIDED, That when both principal and interest on all water redemption bonds issued and outstanding have been paid, any unexpended balance remaining in the fund may be transferred to the general fund or such other fund as the city or town council may direct.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.89.060[1965 c 7 § 35.89.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c52.pdf?cite=1923%20c%2052%20§%208[1923 c 52 § 8]; RRS § 9154-8; ]

== 35.89.070 - Payment of interest on bonds.
The treasurer of such city or town shall pay the interest on the water redemption bonds authorized by this chapter out of the money in the water redemption fund.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.89.070[1965 c 7 § 35.89.070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c52.pdf?cite=1923%20c%2052%20§%206[1923 c 52 § 6]; RRS § 9154-6; ]

== 35.89.080 - Payment of principal of bonds.
Whenever there is sufficient money in the water redemption fund, over and above the amount that will be required to pay the interest on the bonds up to the time of maturity of the next interest payment, to pay the principal of one or more bonds, the city or town treasurer shall call in and pay such bonds. The bonds shall be called and paid in their numerical order, and the call shall be made by publication in the official newspaper of the city or town. The call shall state the total amount and the serial number or numbers of the bonds called and that they will be paid on the date when the next semiannual payment of interest will be due, and that interest on the bonds called will cease from such date.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.89.080[1965 c 7 § 35.89.080]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c52.pdf?cite=1923%20c%2052%20§%207[1923 c 52 § 7]; RRS § 9154-7; ]

== 35.89.090 - Violations—Penalties—Personal liability.
Every ordinance, resolution, order, or action of the council, board, or officer of any city or town, and every warrant or other instrument made, issued, passed or done in violation of the provisions of this chapter shall be void.

Every officer, agent, employee, or member of the council of the city or town, and every person or corporation who shall knowingly commit any violation of the provisions of this chapter or knowingly aid in such violation, shall be liable to the city or town for all money transferred, diverted or paid out in violation thereof and such liability shall attach to and be enforceable against the official bond, if any, of such official agent, employee, or member of the council.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.89.090[1965 c 7 § 35.89.090]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c52.pdf?cite=1923%20c%2052%20§%209[1923 c 52 § 9]; RRS § 9154-9; ]

== 35.89.100 - Water systems—What included.
The term "water system" as used in this chapter shall include and be applicable to all reservoirs, storage and clarifying tanks, conduits, mains, laterals, pipes, hydrants and other equipment used or constructed for the purpose of supplying water for public or domestic use, and shall include not only water systems constructed by local improvement districts, but also any system with which the same may be incorporated or connected.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.89.100[1965 c 7 § 35.89.100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c52.pdf?cite=1923%20c%2052%20§%2010[1923 c 52 § 10]; RRS § 9154-10; ]

