= 35.07 - Disincorporation.
:toc:

== 35.07.001 - Actions subject to review by boundary review board.
Actions taken under chapter 35.07 RCW may be subject to potential review by a boundary review board under chapter 36.93 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c84.pdf?cite=1989%20c%2084%20§%2026[1989 c 84 § 26]; ]

== 35.07.010 - Authority for disincorporation.
Cities and towns may disincorporate.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2010[1994 c 81 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.07.010[1965 c 7 § 35.07.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1897c69.pdf?cite=1897%20c%2069%20§%201[1897 c 69 § 1]; RRS § 8914; ]

== 35.07.020 - Petition—Requisites.
The petition for disincorporation must be signed by a majority of the registered voters thereof and filed with the city or town council.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.07.020[1965 c 7 § 35.07.020]; 1897 c 69 § 2, part; RRS § 8915, part; ]

== 35.07.040 - Calling election—Receiver.
The council shall cause an election to be called upon the proposition of disincorporation. If the city or town has any indebtedness or outstanding liabilities, it shall order the election of a receiver at the same time.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5336-S.SL.pdf?cite=1997%20c%20361%20§%204[1997 c 361 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.07.040[1965 c 7 § 35.07.040]; 1897 c 69 § 2, part; RRS § 8915, part; ]

== 35.07.050 - Notice of election.
Notice of such election shall be given.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1806-S.SL.pdf?cite=2015%20c%2053%20§%2021[2015 c 53 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.07.050[1965 c 7 § 35.07.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1897c69.pdf?cite=1897%20c%2069%20§%203[1897 c 69 § 3]; RRS § 8916; ]

== 35.07.060 - Ballots.
The ballots for the election shall be printed at the expense of the municipality and there shall be printed thereon the words "for dissolution" in one line and the words "against dissolution" in another line and in other and separate lines, the names of each of the lawfully nominated candidates for receiver. In all other respects the ballots shall be in conformity with the law regulating elections in such cities and towns.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.07.060[1965 c 7 § 35.07.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1897c69.pdf?cite=1897%20c%2069%20§%204[1897 c 69 § 4]; RRS § 8917; ]

== 35.07.070 - Conduct of election.
The election shall be conducted as other elections are required by law to be conducted in the city or town except as in this chapter otherwise provided.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.07.070[1965 c 7 § 35.07.070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1897c69.pdf?cite=1897%20c%2069%20§%205[1897 c 69 § 5]; RRS § 8918; ]

== 35.07.080 - Canvass of returns.
The result of the election, together with the ballots cast, shall be certified by the canvassing authority to the council which shall meet within one week thereafter and shall declare the result which shall be made a matter of record in the journal of the council proceedings. If the vote "For dissolution" be a majority of the registered voters of such city or town voting at such election, such corporation shall be deemed dissolved.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.07.080[1965 c 7 § 35.07.080]; 1933 c 128 § 1, part; 1897 c 69 § 6, part; Rem. Supp. §8919, part; ]

== 35.07.090 - Effect of disincorporation—Powers—Officers.
Upon disincorporation of a city or town, its powers and privileges as such, are surrendered to the state and it is absolved from any further duty to the state or its own inhabitants and all the offices appertaining thereto shall cease to exist immediately upon the entry of the result: PROVIDED, That if a receiver is required, the officers shall continue in the exercise of all their powers until a receiver has qualified as such, and thereupon shall surrender to him or her all property, money, vouchers, records and books of the city or town including those in any manner pertaining to its business.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202001[2009 c 549 § 2001]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.07.090[1965 c 7 § 35.07.090]; 1933 c 128 § 1, part; 1897 c 69 § 6, part; RRS § 8919, part; ]

== 35.07.100 - Effect of disincorporation—Existing contracts.
Disincorporation shall not impair the obligation of any contract. If any franchise lawfully granted has not expired at the time of disincorporation, the disincorporation does not impair any right thereunder and does not imply any authority to interfere therewith to any greater extent than the city or town might have, if it had remained incorporated.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.07.100[1965 c 7 § 35.07.100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1897c69.pdf?cite=1897%20c%2069%20§%2018[1897 c 69 § 18]; RRS § 8931; ]

== 35.07.110 - Effect of disincorporation—Streets.
Upon disincorporation of a city or town, its streets and highways pass to the control of the state and shall remain public highways until closed in pursuance of law; and the territory embraced therein shall be made into a new road district or annexed to adjoining districts as may be ordered by the board of county commissioners of the county embracing such city or town.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.07.110[1965 c 7 § 35.07.110]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1897c69.pdf?cite=1897%20c%2069%20§%2017[1897 c 69 § 17]; RRS § 8930; ]

== 35.07.120 - Receiver—Qualification—Bond.
The receiver must qualify within ten days after he or she has been declared elected, by filing with the county auditor a bond equal in penalty to the audited indebtedness and the established liabilities of the city or town with sureties approved by the board of county commissioners, or if the board is not in session, by the judge of the superior court of the county. The bond shall run to the state and shall be conditioned for the faithful performance of his or her duties as receiver and the prompt payment in the order of their priority of all lawful claims finally established as the funds come into his or her hands to discharge them. The bond shall be filed with the county auditor and shall be a public record and shall be for the benefit of every person who may be injured by the receiver's failure to discharge his or her duty.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202002[2009 c 549 § 2002]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.07.120[1965 c 7 § 35.07.120]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1897c69.pdf?cite=1897%20c%2069%20§%207[1897 c 69 § 7]; RRS § 8920; ]

== 35.07.130 - Elected receiver—Failure to qualify—Court to appoint.
If the person elected receiver fails to qualify as such within the prescribed time, the council shall file in the superior court of the county a petition setting forth the fact of the election, its result and the failure of the person elected receiver to qualify within the prescribed time and praying for the appointment of another person as receiver. Notice of the filing of the petition and of the time fixed for hearing thereon must be served upon the person elected receiver at least three days before the time fixed for the hearing. If he or she cannot be found within the county, no notice need be served, and the court may proceed with full jurisdiction to determine the matter upon the hearing. Unless good cause to the contrary is shown, the court shall appoint some suitable person to act as receiver, who shall qualify as required by RCW 35.07.120 within ten days from the date of his or her appointment.

If the council fails to procure the appointment of a receiver, any person qualified to vote in the city or town may file such a petition and make such application.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202003[2009 c 549 § 2003]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.07.130[1965 c 7 § 35.07.130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1897c69.pdf?cite=1897%20c%2069%20§%208[1897 c 69 § 8]; RRS § 8921; ]

== 35.07.140 - No receiver elected though indebtedness exists—Procedure.
If no receiver is elected upon the supposition that no indebtedness existed and it transpires that the municipality does have indebtedness or an outstanding liability, any interested person may file a petition in the superior court asking for the appointment of a receiver, and unless the indebtedness or liability is discharged, the court shall appoint some suitable person to act as receiver who shall qualify as required of any other receiver hereunder, within ten days from the date of his or her appointment.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202004[2009 c 549 § 2004]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.07.140[1965 c 7 § 35.07.140]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1897c69.pdf?cite=1897%20c%2069%20§%2015[1897 c 69 § 15]; RRS § 8928; ]

== 35.07.150 - Duties of receiver—Claims—Priority.
The receiver, upon qualifying, shall take possession of all the property, money, vouchers, records and books of the former municipality including those in any manner pertaining to its business and proceed to wind up its affairs. He or she shall have authority to pay:

. All outstanding warrants and bonds in the order of their maturity with due regard to the fund on which they are properly a charge;

. All lawful claims against the corporation which have been audited and allowed by the council;

. All lawful claims which may be presented to him or her within the time limited by law for the presentation of such claims, but no claim shall be allowed or paid which is not presented within six months from the date of the disincorporation election;

. All claims that by final adjudication may come to be established as lawful claims against the corporation.

As between warrants, bonds and other claims, their priority shall be determined with regard to the fund on which they are properly a charge.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202005[2009 c 549 § 2005]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.07.150[1965 c 7 § 35.07.150]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1897c69.pdf?cite=1897%20c%2069%20§%209[1897 c 69 § 9]; RRS § 8922; ]

== 35.07.160 - Receiver may sue and be sued.
The receiver shall have the right to sue and be sued in all cases necessary or proper for the purpose of winding up the affairs of the former city or town and shall be subject to suit in all cases wherein the city or town might have been sued, subject to the limitations provided in this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.07.160[1965 c 7 § 35.07.160]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1897c69.pdf?cite=1897%20c%2069%20§%2012[1897 c 69 § 12]; RRS § 8925; ]

== 35.07.170 - Receiver—Power to sell property.
The receiver shall be authorized to sell at public auction after such public notice as the sheriff is required to give of like property sold on execution, all the property of the former municipality except such as is necessary for his or her use in winding up its affairs, and excepting also such as has been dedicated to public use.

Personal property shall be sold for cash.

Real property may be sold for all cash, or for one-half cash and the remainder in deferred payments, the last payment not to be later than one year from date of sale. Title shall not pass until all deferred payments have been fully paid.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202006[2009 c 549 § 2006]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.07.170[1965 c 7 § 35.07.170]; 1897 c 69 § 10, part; RRS § 8923; ]

== 35.07.180 - Receiver—Power to levy taxes.
In the same manner and to the same extent as the proper authorities of the former city or town could have done had it not been disincorporated, the receiver shall be authorized to levy taxes on all taxable property, to receive the taxes when collected and to apply them together with the proceeds arising from sales to the extinguishment of the obligations of the former city or town.

After all the lawful claims against the former city or town have been paid excepting bonds not yet due, no levy greater than fifty cents per thousand dollars of assessed value shall be made; nor shall the levy be greater than sufficient to meet the accruing interest until the bonds mature.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c195.pdf?cite=1973%201st%20ex.s.%20c%20195%20§%2011[1973 1st ex.s. c 195 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.07.180[1965 c 7 § 35.07.180]; 1897 c 69 § 10, part; RRS § 8923, part; ]

== 35.07.190 - Receiver's compensation.
The receiver shall be entitled to deduct from any funds coming into his or her hands a commission of six percent on the first thousand dollars, five percent on the second thousand and four percent on any amount over two thousand dollars as his or her full compensation exclusive of necessary traveling expenses and necessary disbursements, but not exclusive of attorney's fees.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202007[2009 c 549 § 2007]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.07.190[1965 c 7 § 35.07.190]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1897c69.pdf?cite=1897%20c%2069%20§%2011[1897 c 69 § 11]; RRS § 8924; ]

== 35.07.200 - Receiver—Removal for cause.
The receiver shall proceed to wind up the affairs of the corporation with diligence and for negligence or misconduct in the discharge of his or her duties may be removed by the superior court upon a proper showing made by a taxpayer of the former city or town or by an unsatisfied creditor thereof.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202008[2009 c 549 § 2008]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.07.200[1965 c 7 § 35.07.200]; 1897 c 69 § 13, part; RRS § 8926, part; ]

== 35.07.210 - Receiver—Successive appointments.
In the case of removal, death, or resignation of a receiver, the court may appoint a new receiver to take charge of the affairs of the former city or town.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.07.210[1965 c 7 § 35.07.210]; 1897 c 69 § 13, part; RRS § 8926, part; ]

== 35.07.220 - Receiver—Final account and discharge.
Upon the final payment of all lawful demands against the former city or town, the receiver shall file a final account, together with all vouchers, with the clerk of the superior court. Any funds remaining in his or her hands shall be paid to the county treasurer for the use of the school district in which the former city or town was situated; and thereupon the receivership shall be at an end.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202009[2009 c 549 § 2009]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.07.220[1965 c 7 § 35.07.220]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1897c69.pdf?cite=1897%20c%2069%20§%2014[1897 c 69 § 14]; RRS § 8927; ]

== 35.07.225 - Applicability of general receivership law.
The provisions of Title 7 RCW generally applicable to receivers and receiverships do not apply to receivers elected or appointed under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6189-S.SL.pdf?cite=2004%20c%20165%20§%2043[2004 c 165 § 43]; ]

== 35.07.230 - Involuntary dissolution of towns—Authorized.
If any town fails for two successive years to hold its regular municipal election, or if the officers elected at the regular election of any town fail for two successive years to qualify and the government of the town ceases to function by reason thereof, the state auditor may petition the superior court of the county for an order, dissolving the town. In addition to stating the facts which would justify the entry of such an order, the petition shall set forth a detailed statement of the assets and liabilities of the town insofar as they can be ascertained.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1889.SL.pdf?cite=1995%20c%20301%20§%2034[1995 c 301 § 34]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.07.230[1965 c 7 § 35.07.230]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c76.pdf?cite=1925%20ex.s.%20c%2076%20§%201[1925 ex.s. c 76 § 1]; RRS § 8931-1; ]

== 35.07.240 - Involuntary dissolution of towns—Notice of hearing.
Upon the filing of a petition for the involuntary dissolution of a town, the superior court shall enter an order fixing the time for hearing thereon at a date not less than thirty days from date of filing. The state auditor shall give notice of the hearing by publication in a newspaper of general circulation in the county, once a week for three successive weeks, and by posting in three public places in the town, stating therein the purpose of the petition and the date and place of hearing thereon.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c469.pdf?cite=1985%20c%20469%20§%2018[1985 c 469 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.07.240[1965 c 7 § 35.07.240]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c76.pdf?cite=1925%20ex.s.%20c%2076%20§%202[1925 ex.s. c 76 § 2]; RRS § 8931-2; ]

== 35.07.250 - Involuntary dissolution of towns—Hearing.
Any person owning property in or qualified to vote in the town may appear at the hearing and file written objections to the granting of the petition. If the court finds that the town has failed for two successive years to hold its regular municipal election or that its officers elected at a regular election have failed to qualify for two successive years thereby causing the government of the town to cease to function, it shall enter an order for disincorporation of the town.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.07.250[1965 c 7 § 35.07.250]; 1925 ex.s. c 76 § 3, part; RRS § 8931-3, part; ]

== 35.07.260 - Involuntary dissolution of towns—Alternative forms of order.
. If the court finds that the town has no indebtedness and no assets, the order of dissolution shall be effective forthwith.

. If the court finds that the town has assets, but no indebtedness or liabilities, it shall order a sale of the assets other than cash by the sheriff in the manner provided by law for the sale of property on execution. The proceeds of the sale together with any money on hand in the treasury of the town, after deducting the costs of the proceeding and sale, shall be paid into the county treasury and placed to the credit of the school district in which the town is located.

. If the court finds that the town has indebtedness or liabilities and assets other than cash, it shall order the sale of the assets as provided in subsection (2) hereof and that the proceeds thereof and the cash on hand shall be applied to the payment of the indebtedness and liabilities.

. If the court finds that the town has indebtedness or liabilities, but no assets or that the assets are insufficient to pay the indebtedness and liabilities, it shall order the board of county commissioners to levy from year to year a tax on the taxable property within the boundaries of the former town until the indebtedness and liabilities are paid. All taxes delinquent at the date of dissolution when collected shall be applied to the payment of the indebtedness and liabilities. Any balance remaining from the collection of delinquent taxes and taxes levied under order of the court, after payment of the indebtedness and liabilities shall be placed to the credit of the school district in which the town is located.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.07.260[1965 c 7 § 35.07.260]; 1925 ex.s. c 76 § 3, part; RRS § 8931-3, part; ]

