= 35.49 - Local improvements—Collection of assessments.
:toc:

== 35.49.010 - Collection by city treasurer—Notices.
All assessments for local improvements in local improvement districts shall be collected by the city treasurer and shall be kept in a separate fund to be known as "local improvement fund, district No. . . . ." and shall be used for no other purpose than the redemption of warrants drawn upon and bonds issued against the fund to provide payment for the cost and expense of the improvement.

All assessments for local improvements in a utility local improvement district shall be collected by the city treasurer, shall be paid into the appropriate revenue bond fund, and shall be used for no other purpose than the redemption of revenue bonds issued to provide funds for the cost and expense of the improvement.

As soon as the assessment roll has been placed in the hands of the city or town treasurer for collection, he or she shall publish a notice in the official newspaper of the city or town once a week for two consecutive weeks, that the roll is in his or her hands for collection and that all or any portion of the assessment may be paid within thirty days from the date of the first publication of the notice without penalty, interest or costs.

Within fifteen days of the first newspaper publication, the city or town treasurer shall notify each owner or reputed owner whose name appears on the assessment roll, at the address shown on the tax rolls of the county treasurer for each item of property described on the list, of the nature of the assessment, of the amount of his or her real property subject to such assessment, of the total amount of assessment due, and of the time during which such assessment may be paid without penalty, interest, or costs.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202085[2009 c 549 § 2085]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c137.pdf?cite=1972%20ex.s.%20c%20137%20§%201[1972 ex.s. c 137 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c258.pdf?cite=1969%20ex.s.%20c%20258%20§%2013[1969 ex.s. c 258 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c52.pdf?cite=1967%20c%2052%20§%2013[1967 c 52 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.49.010[1965 c 7 § 35.49.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c98.pdf?cite=1911%20c%2098%20§%2028[1911 c 98 § 28]; RRS § 9380.  1911 c 98 § 50, part; RRS § 9403, part; ]

== 35.49.020 - Installments—Number—Due date.
In all cases where bonds are issued to pay the cost and expense of a local improvement, the ordinance levying the assessments shall provide that the sum charged against any lot, tract, and parcel of land or other property, or any portion thereof, may be paid during the thirty day period allowed for the payment of assessments without penalty or interest and that thereafter the sum remaining unpaid may be paid in equal annual principal installments or in equal annual installments of principal and interest. The number of installments shall be less by two than the number of years which the bonds issued to pay for the improvement are to run. The estimated interest rate may be stated in the ordinance confirming the assessment roll. Where payment is required in equal annual principal installments, interest on the whole amount unpaid at the rate fixed by the ordinance authorizing the issuance and sale of the bonds shall be due on the due date of the first installment of principal and each year thereafter on the due date of each installment of principal: PROVIDED, That the legislative authority of any city or town having made a bond issue payable on or before twenty-two years after the date of issue may provide by ordinance that all assessments and portions of assessments unpaid after the thirty day period allowed for payment of assessments without penalty or interest may be paid in ten equal installments beginning with the eleventh year and ending with the twentieth year from the expiration of said thirty day period, together with interest on the unpaid installments at the rate fixed by such ordinance, and that in each year after the said thirty day period, to and including the tenth year thereafter, one installment of interest on the principal sum of the assessment at the rate so fixed shall be paid and collected, and that beginning with the eleventh year after the thirty day period one installment of the principal, together with the interest due thereon, and on all installments thereafter to become due shall be paid and collected.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c96.pdf?cite=1982%20c%2096%20§%201[1982 c 96 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c323.pdf?cite=1981%20c%20323%20§%205[1981 c 323 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c258.pdf?cite=1969%20ex.s.%20c%20258%20§%2014[1969 ex.s. c 258 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.49.020[1965 c 7 § 35.49.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c117.pdf?cite=1925%20ex.s.%20c%20117%20§%201[1925 ex.s. c 117 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c168.pdf?cite=1915%20c%20168%20§%205[1915 c 168 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c98.pdf?cite=1911%20c%2098%20§%2049[1911 c 98 § 49]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1899c124.pdf?cite=1899%20c%20124%20§%204[1899 c 124 § 4]; RRS § 9402; ]

== 35.49.030 - Ordinance to prescribe time of payment—Interest—Penalties.
Every city and town shall prescribe by ordinance within what time assessments or installments thereof shall be paid, and shall provide for the payment and collection of interest thereon at a rate as shall be fixed by the legislative body of the city or town. Assessments or installments thereof, when delinquent, in addition to such interest, shall bear such penalty not less than five percent as shall be by general ordinance prescribed.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c116.pdf?cite=1971%20ex.s.%20c%20116%20§%205[1971 ex.s. c 116 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c258.pdf?cite=1969%20ex.s.%20c%20258%20§%2015[1969 ex.s. c 258 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.49.030[1965 c 7 § 35.49.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c353.pdf?cite=1955%20c%20353%20§%203[1955 c 353 § 3]; prior: 1927 c 275 § 1, part; 1921 c 92 § 1, part; 1911 c 98 § 24, part; RRS § 9376, part; ]

== 35.49.040 - Payment without interest or penalty.
The owner of any lot, tract, or parcel of land or other property charged with local improvement assessment may redeem it from all or any portion thereof by paying to the city or town treasurer all or any portion thereof without interest within thirty days after the first publication by the treasurer of notice that the assessment roll is in his or her hands for collection.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202086[2009 c 549 § 2086]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.49.040[1965 c 7 § 35.49.040]; 1911 c 98 § 50, part; RRS § 9403, part; ]

== 35.49.050 - Prepayment of installments subsequently due.
The owner of any lot, tract, or parcel of land or other property charged with a local improvement assessment may redeem it from all liability for the unpaid amount of the assessment at any time after the thirty day period allowed for payment of assessments without penalty or interest by paying the entire installments of the assessment remaining unpaid to the city or town treasurer with interest thereon to the date of maturity of the installment next falling due.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.49.050[1965 c 7 § 35.49.050]; 1911 c 98 § 50, part; RRS § 9403, part; ]

== 35.49.060 - Payment by city or town.
On or before the fifteenth day of August of each year, the city or town treasurer shall certify to the city or town council a detailed statement showing:

. The proceedings authorizing and confirming any local improvement assessments or utility local improvement assessments affecting city or town property,

. The lots, tracts, or parcels of lands of the city or town so assessed,

. The several assessments against each,

. The interest, penalties, and charges thereon,

. The penalties and charges which will accrue upon the assessments to the date of payment, and

. The total of all such assessments, interest, penalty, and charges.

The longest outstanding liens shall be paid first, but if the money in the "city (or town) property assessments redemption fund" is insufficient at any time to discharge all such liens against the lands of the city or town upon a given assessment roll, the city or town treasurer may pay such portion thereof as may be possible from the funds available.

If deemed necessary, the city or town council may transfer money from the general fund to the redemption fund as a loan to be repaid when the money is available for repayment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c52.pdf?cite=1967%20c%2052%20§%2014[1967 c 52 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.49.060[1965 c 7 § 35.49.060]; 1929 c 183 § 2, part; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c130.pdf?cite=1909%20c%20130%20§%202[1909 c 130 § 2]; RRS § 9345, part; ]

== 35.49.070 - Payment by county.
Upon the confirmation of the assessment roll for a local improvement district or utility local improvement district, the city or town treasurer shall certify and forward to the board of county commissioners a statement of all the lots, tracts, or parcels of land held or owned by the county assessed thereon, separately describing each lot, tract, or parcel, with the amount of the assessment charged against it.

The board of county commissioners shall cause the amount of such local assessments to be paid to the city or town as other claims against the county are paid.

If title to any property thus described was acquired by the county through foreclosure of general tax liens, the county shall:

. Pay the assessment from the proceeds of the sale of the property; or

. Sell the property subject to the lien of the assessment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c52.pdf?cite=1967%20c%2052%20§%2015[1967 c 52 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.49.070[1965 c 7 § 35.49.070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c139.pdf?cite=1929%20c%20139%20§%201[1929 c 139 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1905c29.pdf?cite=1905%20c%2029%20§%203[1905 c 29 § 3]; RRS § 9342; ]

== 35.49.080 - Payment by metropolitan park district.
Upon the confirmation of the assessment roll for a local improvement district or utility local improvement district, the city treasurer shall certify and forward to the board of park commissioners of any metropolitan park district in which the city is located, a statement of all the lots, tracts, and parcels of land or other property held or owned by the district, assessed thereon, separately describing each lot, tract, or parcel with the amount of the assessment charged against it.

The board of park commissioners shall cause the amount of the local assessments to be paid as other claims against the metropolitan park district are paid.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c52.pdf?cite=1967%20c%2052%20§%2016[1967 c 52 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.49.080[1965 c 7 § 35.49.080]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c204.pdf?cite=1929%20c%20204%20§%203[1929 c 204 § 3]; RRS § 9343-3; ]

== 35.49.090 - Payment by joint owner.
If any assessment for a local improvement, or an installment thereof, or judgment for either of them is paid, or a certificate of sale for either of them is redeemed by a joint owner of any of the property so assessed, he or she may, after demand and refusal, recover from his or her co-owners, by an action brought in superior court, the respective portions of the payment which each co-owner should bear. He or she shall have a lien upon the undivided interests of his or her co-owners from the date of the payment made by him or her and in the action shall recover interest at ten percent from the date of payment by him or her and the costs of the action in addition to the principal sum due him or her.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202087[2009 c 549 § 2087]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.49.090[1965 c 7 § 35.49.090]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c98.pdf?cite=1911%20c%2098%20§%2062[1911 c 98 § 62]; RRS § 9415; ]

== 35.49.100 - Payment in error—Remedy.
If, through error or inadvertence, a person pays any assessment for a local improvement or an installment thereof upon the lands of another, he or she may, after demand and refusal, recover from the owner of such lands, by an action in the superior court, the amount so paid and the costs of the action.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202088[2009 c 549 § 2088]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.49.100[1965 c 7 § 35.49.100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c98.pdf?cite=1911%20c%2098%20§%2065[1911 c 98 § 65]; RRS § 9418; ]

== 35.49.110 - Record of payment.
If the amount of any assessment for a local improvement with interest, penalty, costs, and charges accrued thereon is paid to the treasurer before sale of the property in foreclosure of the lien thereon, the city or town treasurer shall mark it paid upon the assessment roll with the date of payment thereof.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.49.110[1965 c 7 § 35.49.110]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1927c275.pdf?cite=1927%20c%20275%20§%202[1927 c 275 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c98.pdf?cite=1911%20c%2098%20§%2030[1911 c 98 § 30]; RRS § 9382; ]

== 35.49.130 - Tax liens—City may protect assessment lien at foreclosure sale.
If any property situated in a local improvement district or utility local improvement district created by a city or town is offered for sale for general taxes by the county treasurer, the city or town shall have power to protect the lien or liens of any local improvement assessments outstanding against the whole or portion of such property by purchase at the treasurer's foreclosure sale.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5098.SL.pdf?cite=1995%20c%2038%20§%202[1995 c 38 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5372-S2.SL.pdf?cite=1994%20c%20301%20§%204[1994 c 301 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.49.130[1965 c 7 § 35.49.130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c98.pdf?cite=1911%20c%2098%20§%2063[1911 c 98 § 63]; RRS § 9416.  1929 c 143 § 1, part; 1925 ex.s. c 170 § 1, part; 1911 c 98 § 40, part; RRS § 9393, part; ]

== 35.49.140 - Tax liens—Payment by city after taking property on foreclosure of local assessments.
If a city or town has bid in any property on sale for local improvement assessments, it may satisfy the lien of any outstanding general taxes upon the property by payment of the face of such taxes and costs, without penalty or interest, but this shall not apply where certificates of delinquency against the property have been issued to private persons.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.49.140[1965 c 7 § 35.49.140]; 1929 c 143 § 1, part; 1925 ex.s. c 170 § 1, part; 1911 c 98 § 40, part; RRS § 9393, part; ]

== 35.49.150 - Tax title property—City may acquire from county before resale.
If property is struck off to or bid in by a county at a sale for general taxes, and is subject to local improvement assessments in any city or town, or has been taken over by the city or town on the foreclosure of local improvement assessments, the city or town may acquire the property from the county at any time before resale and receive a deed therefor upon paying the face of such taxes and costs, without penalty or interest.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.49.150[1965 c 7 § 35.49.150]; 1929 c 143 § 1, part; 1925 ex.s. c 170 § 1, part; 1911 c 98 § 40, part; RRS § 9393, part; ]

== 35.49.160 - Tax title property—Disposition of proceeds upon resale.
Whenever property struck off to or bid in by a county at a sale for general taxes is subsequently sold by the county, the proceeds of the sale must be applied as follows:

. First, to reimburse the county for the costs of foreclosure and sale as defined in RCW 36.35.110;

. Any remaining proceeds must next be applied to pay any amounts deferred under chapter 84.37 or 84.38 RCW on the property, including accrued interest, and outstanding at the time the county acquired the property by tax deed;

. Any remaining proceeds must next be applied to discharge in full the lien or liens for general taxes for which the property was sold;

. Any remaining proceeds must be paid to the city or town to discharge all local improvement assessment liens against the property; and

. Any surplus proceeds must be distributed among the proper county funds.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1421.SL.pdf?cite=2013%20c%20221%20§%201[2013 c 221 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.49.160[1965 c 7 § 35.49.160]; 1929 c 143 § 1, part; 1925 ex.s. c 170 § 1, part; 1911 c 98 § 40, part; RRS § 9393, part; ]

== 35.49.170 - Acquisition of property by state or political subdivisions which is subject to unpaid assessments and delinquencies.
See RCW 79.44.190.

[ ]

