= 35.37 - Fiscal—Cities under twenty thousand and cities other than first class—Bonds.
:toc:

== 35.37.010 - Accounting—Funds.
Every city and town having less than twenty thousand inhabitants shall maintain a current expense fund out of which it must pay current expenses. It shall also maintain an "indebtedness fund," and if it has outstanding general indebtedness bonds, it must maintain a sinking fund therefor. If it maintains waterworks, lighting plant, cemetery, or other public works or institutions from which rent or other revenue is derived it must maintain a separate fund for each utility or institution. All moneys collected by such cities and towns from licenses shall be credited to the current expense fund.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.37.010[1965 c 7 § 35.37.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1897c84.pdf?cite=1897%20c%2084%20§%201[1897 c 84 § 1]; RRS § 5635.   1897 c 84 § 2; RRS § 5636. (iii)  1897 c 84 § 9; RRS § 5643. (iv) 1897 c 84 § 10, part; RRS § 5644, part; ]

== 35.37.020 - Accounting—Surplus and deficit in utility accounts.
Any deficit for operation and maintenance of utilities and institutions owned and controlled by cities and towns having less than twenty thousand inhabitants, over and above the revenue therefrom, shall be paid out of the current expense fund. Any surplus in the waterworks fund, lighting fund, *cemetery fund, or other like funds at the end of the fiscal year shall be paid into the current expense fund except such part as the council by a finding entered into the record of the proceedings may conclude to be necessary for the purpose of:

. Extending or repairing the particular utility or institution; or

. Paying interest or principal of any indebtedness incurred in the construction or purchase of the particular utility or institution; or

. Creating or adding to a sinking fund for the payment of any indebtedness incurred in the construction or purchase of the particular utility or institution.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.37.020[1965 c 7 § 35.37.020]; 1897 c 84 § 10, part; RRS § 5644, part; ]

== 35.37.027 - Validation of preexisting obligations by former city.
All elections for the validation of any debt created by any city or town which has since become consolidated with any other city or town shall be by ballot, and the vote shall be taken in the new consolidated city as constituted at the time of the election.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.37.027[1965 c 7 § 35.37.027]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1897c84.pdf?cite=1897%20c%2084%20§%2012[1897 c 84 § 12]; RRS § 5646; ]

== 35.37.030 - Applicability of chapter.
The provisions of the remainder of this chapter shall not be applied to cities of the first class nor to borrowing money and issuing bonds by any city or town for the purpose of supplying it with water, artificial light, or sewers if the works for supplying the water, artificial light, or sewers are to be owned and controlled by the city or town.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.37.030[1965 c 7 § 35.37.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c128.pdf?cite=1891%20c%20128%20§%2010[1891 c 128 § 10]; RRS § 9548.   1891 c 128 § 11; RRS § 9549; ]

== 35.37.040 - Authority to contract debts—Limits.
Every city and town, may, without a vote of the people, contract indebtedness or borrow money for strictly municipal purposes on the credit of the city or town and issue negotiable bonds therefor in an amount which when added to its existing nonvoter approved indebtedness will not exceed the amount of indebtedness authorized by chapter 39.36 RCW, as now or hereafter amended, to be incurred without the assent of the voters.

When bonds are issued under this section the ordinance providing therefor shall contain a statement showing the value of the taxable property in the city or town, as the term "value of the taxable property" is defined in RCW 39.36.015, together with the amount of the existing nonvoter approved and total indebtedness of the city or town, which indebtedness shall include the amount for which such bonds are issued.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c186.pdf?cite=1984%20c%20186%20§%2015[1984 c 186 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c42.pdf?cite=1970%20ex.s.%20c%2042%20§%2012[1970 ex.s. c 42 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.37.040[1965 c 7 § 35.37.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c128.pdf?cite=1891%20c%20128%20§%201[1891 c 128 § 1]; RRS § 9538.  1891 c 128 § 6, part; RRS § 9544, part; ]

== 35.37.050 - Excess indebtedness—Authority to contract.
Every city and town may, when authorized by the voters of the city or town pursuant to Article VIII, section 6 of the state Constitution at an election held pursuant to RCW 39.36.050, contract indebtedness or borrow money for strictly municipal purposes on the credit of the city or town and issue negotiable bonds therefor in an amount which when added to its existing indebtedness will exceed the amount of indebtedness authorized by chapter 39.36 RCW, as now or hereafter amended, to be incurred without the assent of the voters but will not exceed the amounts of indebtedness authorized by chapter 39.36 RCW, as now or hereafter amended, to be incurred with the assent of the voters.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c186.pdf?cite=1984%20c%20186%20§%2016[1984 c 186 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.37.050[1965 c 7 § 35.37.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c128.pdf?cite=1891%20c%20128%20§%202[1891 c 128 § 2]; RRS § 9539.  1891 c 128 § 4, part; RRS § 9542, part; ]

== 35.37.090 - General indebtedness bonds—Issuance and sale.
All general indebtedness bonds shall be issued and sold in accordance with chapter 39.46 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c186.pdf?cite=1984%20c%20186%20§%2017[1984 c 186 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c167.pdf?cite=1983%20c%20167%20§%2036[1983 c 167 § 36]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.37.090[1965 c 7 § 35.37.090]; 1891 c 128 § 5, part; RRS § 9543, part.  1891 c 128 § 6, part; RRS § 9544, part; ]

== 35.37.110 - General indebtedness bonds—Taxation to pay.
So long as any general indebtedness bonds are outstanding an amount sufficient to pay the interest upon them as it accrues shall be included in each annual levy for municipal purposes and a sufficient amount shall be included in each annual levy for payment of principal so that all bonds may be paid serially as they mature.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.37.110[1965 c 7 § 35.37.110]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c128.pdf?cite=1891%20c%20128%20§%208[1891 c 128 § 8]; RRS § 9546; ]

== 35.37.120 - General indebtedness bonds—Taxation—Failure to levy—Remedy.
If the council of any city or town which has issued general indebtedness bonds fails to make any levy necessary to make principal or interest payments due on the bonds, the owner of any bond or interest payment which has been presented to the treasurer and payment thereof refused because of the failure to make a levy may file the bond together with any unpaid coupons with the county auditor, taking his or her receipt therefor.

The county auditor shall register bonds so filed, and the county legislative authority at its next session at which it levies the annual county tax shall add to the city's or town's levy a sum sufficient to realize the amount of principal and interest past due and to become due prior to the next annual levy to be collected and held by the county treasurer and paid out only upon warrants drawn by the county auditor as the payments mature in favor of the owner of the bond as shown by the auditor's register. Similar levies shall be made in each succeeding year until the bonds and any coupons or interest payments are fully satisfied.

This remedy is alternative and in addition to any other remedy which the owner of such a bond or coupon may have.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202074[2009 c 549 § 2074]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c167.pdf?cite=1983%20c%20167%20§%2038[1983 c 167 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.37.120[1965 c 7 § 35.37.120]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c128.pdf?cite=1891%20c%20128%20§%209[1891 c 128 § 9]; RRS § 9547; ]

