= 35.97 - Heating systems.
:toc:

== 35.97.010 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Biomass energy system" means a system that provides for the production or collection of organic materials such as wood and agricultural residues and municipal solid waste that are primarily organic materials and the conversion or use of that material for the production of heat or substitute fuels through several processes including, but not limited to, burning, pyrolysis, or anaerobic digestion.

. "Cogeneration" means the sequential generation of two or more forms of energy from a common fuel or energy source.

. "Cogeneration facility" means any machinery, equipment, structure, process, or property or any part thereof, installed or acquired for the primary purpose of cogeneration by a person or corporation.

. "Geothermal heat" means the natural thermal energy of the earth.

. "Waste heat" means the thermal energy which otherwise would be released to the environment from an industrial process, electric generation, or other process.

. "Heat" means thermal energy.

. "Heat source" includes but is not limited to (a) any integral part of a heat production or heat rejection system of an industrial facility, cogeneration facility, or electric power generation facility, (b) geothermal well or spring, (c) biomass energy system, (d) solar collection facility, and (e) hydrothermal resource or heat extraction process.

. "Municipality" means a county, city, town, irrigation district which distributes electricity, water-sewer district, port district, or metropolitan municipal corporation.

. "Heating facilities or heating systems" means all real and personal property, or interests therein, necessary or useful for: (a) The acquisition, production, or extraction of heat; (b) the storage of heat; (c) the distribution of heat from its source to the place of utilization; (d) the extraction of heat at the place of utilization from the medium by which the heat is distributed; (e) the distribution of heat at the place of utilization; and (f) the conservation of heat.

. "Hydrothermal resource" means the thermal energy available in wastewater, sewage effluent, wells, or other water sources, natural or man-made.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1264.SL.pdf?cite=1999%20c%20153%20§%2041[1999 c 153 § 41]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c522.pdf?cite=1987%20c%20522%20§%204[1987 c 522 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c216.pdf?cite=1983%20c%20216%20§%202[1983 c 216 § 2]; ]

== 35.97.020 - Heating systems authorized.
. Counties, cities, towns, irrigation districts which distribute electricity, sewer districts, water districts, port districts, and metropolitan municipal corporations are authorized pursuant to this chapter to establish heating systems and supply heating services from Washington's heat sources.

. Nothing in this chapter authorizes any municipality to generate, transmit, distribute, or sell electricity.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c11.pdf?cite=1989%20c%2011%20§%207[1989 c 11 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c522.pdf?cite=1987%20c%20522%20§%203[1987 c 522 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c216.pdf?cite=1983%20c%20216%20§%201[1983 c 216 § 1]; ]

== 35.97.030 - Heating systems—General powers of municipalities.
A municipality may construct, purchase, acquire, add to, extend, maintain, and operate a system of heating facilities, within or without its limits, for the purpose of supplying its inhabitants and other persons with heat, with full power to regulate and control the use, distribution, and price of supplying heat, and to enter into agreements for the maintenance and operation of heating facilities under terms and conditions determined by the legislative authority of the municipality. The provision of heat and heating facilities and the establishment and operation of heating systems by a municipality under this chapter are hereby declared to be a public use and a public and strictly municipal purpose. However, nothing in this chapter shall be construed to restrain or limit the authority of any individual, partnership, corporation, or private utility from establishing and operating heating systems.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c216.pdf?cite=1983%20c%20216%20§%203[1983 c 216 § 3]; ]

== 35.97.040 - Heating systems—Specific powers of municipalities.
In addition to the general powers under RCW 35.97.030, and not by way of limitation, municipalities have the following specific powers:

. The usual powers of a corporation, to be exercised for public purposes;

. To acquire by purchase, gift, or condemnation property or interests in property within and without the municipality, necessary for the construction and operation of heating systems, including additions and extensions of heating systems. No municipality may acquire any heat source by condemnation. To the extent judged economically feasible by the municipality, public property and rights-of-way shall be utilized in lieu of private property acquired by condemnation. The municipality shall determine in cooperation with existing users that addition of district heating facilities to any public property or rights-of-way shall not be a hazard or interference with existing uses or, if so, that the cost for any relocation of facilities of existing users shall be a cost and expense of installing the heating facility;

. To acquire, install, add to, maintain, and operate heating facilities at a heat source or to serve particular consumers of heat, whether such facilities are located on property owned by the municipality, by the consumer of heat, or otherwise;

. To sell, lease, or otherwise dispose of heating facilities;

. To contract for the operation of heating facilities;

. To apply and qualify for and receive any private or federal grants, loans, or other funds available for carrying out the objects of the municipality under this chapter;

. Full and exclusive authority to sell and regulate and control the use, distribution, rates, service, charges, and price of all heat supplied by the municipality and to carry out any other powers and duties under this chapter free from the jurisdiction and control of the utilities and transportation commission;

. To utilize fuels other than the heat sources described in RCW 35.97.020 on a standby basis, to meet start-up and emergency requirements, to meet peak demands, or to supplement those heat sources as necessary to provide a reliable and economically feasible supply of heat;

. To the extent permitted by the state Constitution, to make loans for the purpose of enabling suppliers or consumers of heat to finance heating facilities;

. To enter into cooperative agreements providing for the acquisition, construction, ownership, financing, use, control, and regulation of heating systems and heating facilities by more than one municipality or by one or more municipalities on behalf of other municipalities.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c216.pdf?cite=1983%20c%20216%20§%204[1983 c 216 § 4]; ]

== 35.97.050 - Heating systems—Authorized by legislative authority of municipality—Competitive bidding.
If the legislative authority of a municipality deems it advisable that the municipality purchase, acquire, or construct a heating system, or make any additions or extensions to a heating system, the legislative authority shall so provide by an ordinance or a resolution specifying and adopting the system or plan proposed, declaring the estimated cost thereof, as near as may be, and specifying the method of financing and source of funds. Any construction, alteration, or improvement of a heating system by any municipality shall be in compliance with the appropriate competitive bidding requirements in Titles 35, 36, 53, 57, or 87 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1264.SL.pdf?cite=1999%20c%20153%20§%2042[1999 c 153 § 42]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%201603[1996 c 230 § 1603]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c216.pdf?cite=1983%20c%20216%20§%205[1983 c 216 § 5]; ]

== 35.97.060 - Municipality may impose rates and charges—Classification of customers.
A municipality may impose rates, charges, or rentals for heat, service, and facilities provided to customers of the system if the rates charged are uniform for the same class of customers or service. In classifying customers served or service furnished, the legislative authority may consider: The difference in cost of service to the various customers; location of the various customers within or without the municipality; the difference in cost of maintenance, operation, repair, and replacement of the various parts of the system; the different character of the service furnished various customers; the quantity and quality of the heat furnished; the time heat is used; the demand on the system; capital contributions made to the system including, but not limited to, assessments or the amount of capital facilities provided for use by the customer; and any other matters which present a reasonable difference as a ground for distinction.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c216.pdf?cite=1983%20c%20216%20§%206[1983 c 216 § 6]; ]

== 35.97.070 - Municipality may shut off heat for nonpayment—Late payment charges authorized.
If prompt payment of a heating rate, charge, or rental is not made, a municipality after reasonable notice may shut off the heating supply to the building, place, or premises to which the municipality supplied the heating. A municipality may also make an additional charge for late payment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c216.pdf?cite=1983%20c%20216%20§%207[1983 c 216 § 7]; ]

== 35.97.080 - Connection charges authorized.
A municipality may charge property owners seeking to connect to the heating system, as a condition to granting the right to connect and in addition to the cost of the connection, such reasonable connection charge as the legislative authority determines to be proper in order that the property owners bear their pro rata share of the cost of the system. Potential customers shall not be compelled to subscribe or connect to the heating system. The cost of connection to the system shall include the cost of acquisition and installation of heating facilities necessary or useful for the connection, including any heating facilities located or installed on the property being served. Connection charges may, in the discretion of the municipality, be made payable in installments over a period of not more than thirty years or the estimated life of the facilities installed, whichever is less. Installments, if any, shall bear interest and penalties at such rates and be payable at such times and in such manner as the legislative authority of the municipality may provide.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c216.pdf?cite=1983%20c%20216%20§%208[1983 c 216 § 8]; ]

== 35.97.090 - Local improvement district—Assessments—Bonds and warrants.
For the purpose of paying all or a portion of the cost of heating facilities, a municipality may form local improvement districts or utility local improvement districts, foreclose on, levy, and collect assessments, reassessments, and supplemental assessments; and issue local improvement district bonds and warrants in the manner provided by law for cities or towns.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c216.pdf?cite=1983%20c%20216%20§%209[1983 c 216 § 9]; ]

== 35.97.100 - Special funds authorized.
For the purpose of providing funds for defraying all or a portion of the costs of planning, purchase, leasing, condemnation, or other acquisition, construction, reconstruction, development, improvement, extension, repair, maintenance, or operation of a heating system, and the implementation of the powers in RCW 35.97.030 and 35.97.040, a municipality may authorize, by ordinance or resolution, the creation of a special fund or funds into which the municipality shall be obligated to set aside and pay all or any designated proportion or amount of any or all revenues derived from the heating system, including any utility local improvement district assessments, any grants received to pay the cost of the heating system, and any municipal license fees specified in the ordinance or resolution creating such special fund.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c216.pdf?cite=1983%20c%20216%20§%2010[1983 c 216 § 10]; ]

== 35.97.110 - Revenue bonds—Form, terms, etc.
If the legislative authority of a municipality deems it advisable to finance all or a portion of the costs of planning, purchase, leasing, condemnation, or other acquisition, construction, reconstruction, development, improvement, and extension of a heating system, or for the implementation of the powers in RCW 35.97.030 and 35.97.040, or for working capital, interest during construction and for a period of up to one year thereafter, debt service and other reserves, and the costs of issuing revenue obligations, a municipality may issue revenue bonds against the special fund or fund created from revenues or assessments. The revenue bonds so issued may be issued in one or more series and shall be dated, shall bear interest at such rate or rates, and shall mature at such time or times as may be determined by the legislative authority of the municipality, and may be made redeemable before maturity at such price or prices and under such terms and conditions as may be fixed by the legislative authority of the municipality prior to the issuance of the bonds. The legislative authority of the municipality shall determine the form of the bonds, including any interest coupons to be attached thereto, and shall fix the denomination or denominations of the bonds and the place or places of payment of principal and interest. If an officer whose signature or a facsimile of whose signature appears on any bonds or coupons ceases to be such officer before the delivery of the bonds, the signature shall for all purposes have the same effect as if the officer had remained in office until the delivery. The bonds may be issued in coupon or in registered form or both, and provisions may be made for the registration of any coupon bonds as to the principal alone and also as to both principal and interest and for the reconversion into coupon bonds of any bonds registered as to both principal and interest. Bonds may be sold at public or private sale for such price and bearing interest at such fixed or variable rate as may be determined by the legislative authority of the municipality.

The principal of and interest on any revenue bonds shall be secured by a pledge of the revenues and receipts derived from the heating system, including any amounts pledged to be paid into a special fund under RCW 35.97.100, and may be secured by a mortgage covering all or any part of the system, including any enlargements of and additions to such system thereafter made. The revenue bonds shall state upon their face that they are payable from a special fund, naming it and the ordinance creating it, and that they do not constitute a general indebtedness of the municipality. The ordinance or resolution under which the bonds are authorized to be issued and any such mortgage may contain agreements and provisions respecting the maintenance of the system, the fixing and collection of rates and charges, the creation and maintenance of special funds from such revenues, the rights and remedies available in the event of default, and other matters improving the marketability of the revenue bonds, all as the legislative authority of the municipality deems advisable. Any revenue bonds issued under this chapter may be secured by a trust agreement by and between the municipality and a corporate trustee, which may be any trust company or bank having the powers of a trust company within the state. Any such trust agreement or ordinance or resolution providing for the issuance of such bonds may contain such provisions for protecting and enforcing the rights and remedies of the bond owners as may be reasonable and proper and not in violation of law. Any such trust agreement may set forth the rights and remedies of the bond owners and of the trustee and may restrict the individual right of action by bond owners as is customary in trust agreements or trust indentures.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c216.pdf?cite=1983%20c%20216%20§%2011[1983 c 216 § 11]; ]

== 35.97.120 - Revenue warrants.
Revenue warrants may be issued and such warrants and interest thereon may be payable out of the special fund or refunded through the proceeds of the sale of refunding revenue warrants or revenue bonds. Every revenue warrant and the interest thereon issued against the special fund is a valid claim of the owner thereof only as against that fund and the amount of revenue pledged to the fund, and does not constitute an indebtedness of the authorized municipality. Every revenue warrant shall state on its face that it is payable from a special fund, naming it and the ordinance or resolution creating it.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c216.pdf?cite=1983%20c%20216%20§%2012[1983 c 216 § 12]; ]

== 35.97.130 - Revenue bonds and warrants—Holder may enforce.
If a municipality fails to set aside and pay into the special fund created for the payment of revenue bonds and warrants the amount which it has obligated itself in the ordinance or resolution creating the fund to set aside and pay therein, the holder of any bond or warrant issued against the bond may bring suit against the municipality to compel it to do so.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c216.pdf?cite=1983%20c%20216%20§%2013[1983 c 216 § 13]; ]

