= 35.82 - Housing authorities law.
:toc:

== 35.82.010 - Finding and declaration of necessity.
It is hereby declared: (1) That there exist in the state insanitary or unsafe dwelling accommodations and that persons of low income are forced to reside in such insanitary or unsafe accommodations; that within the state there is a shortage of safe or sanitary dwelling accommodations available at rents which persons of low income can afford and that such persons are forced to occupy overcrowded and congested dwelling accommodations; that the aforesaid conditions cause an increase in and spread of disease and crime and constitute a menace to the health, safety, morals and welfare of the residents of the state and impair economic values; that these conditions necessitate excessive and disproportionate expenditures of public funds for crime prevention and punishment, public health and safety, fire and accident protection, and other public services and facilities; (2) that these areas in the state cannot be cleared, nor can the shortage of safe and sanitary dwellings for persons of low income be relieved, through the operation of private enterprise, and that the construction of housing projects for persons of low income (as herein defined) would therefore not be competitive with private enterprise; (3) that the clearance, replanning and reconstruction of the areas in which insanitary or unsafe housing conditions exist and the providing of safe and sanitary dwelling accommodations for persons of low income are public uses and purposes for which public money may be spent and private property acquired and are governmental functions of state concern; (4) that it is in the public interest that work on projects for such purposes be commenced as soon as possible in order to relieve unemployment which now (1939) constitutes an emergency; and the necessity in the public interest for the provisions hereinafter enacted, is hereby declared as a matter of legislative determination.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.82.010[1965 c 7 § 35.82.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c23.pdf?cite=1939%20c%2023%20§%202[1939 c 23 § 2]; RRS § 6889-2; ]

== 35.82.020 - Definitions.
The following terms, wherever used or referred to in this chapter, shall have the following respective meanings, unless a different meaning clearly appears from the context:

. "Authority" or "housing authority" shall mean any of the public corporations created by RCW 35.82.030.

. "City" shall mean any city, town, or code city. "County" shall mean any county in the state. "The city" shall mean the particular city for which a particular housing authority is created. "The county" shall mean the particular county for which a particular housing authority is created.

. "Governing body" shall mean, in the case of a city, the city council or the commission and in the case of a county, the county legislative authority.

. "Mayor" shall mean the mayor of the city or the officer thereof charged with the duties customarily imposed on the mayor or executive head of the city.

. "Clerk" shall mean the clerk of the city or the clerk of the county legislative authority, as the case may be, or the officer charged with the duties customarily imposed on such clerk.

. "Area of operation": (a) In the case of a housing authority of a city, shall include such city and the area within five miles from the territorial boundaries thereof: PROVIDED, That the area of operation of a housing authority of any city shall not include any area which lies within the territorial boundaries of some other city, as herein defined; (b) in the case of a housing authority of a county, shall include all of the county except that portion which lies within the territorial boundaries of any city as herein defined.

. "Federal government" shall include the United States of America, the United States housing authority or any other agency or instrumentality, corporate or otherwise, of the United States of America.

. "Slum" shall mean any area where dwellings predominate which, by reason of dilapidation, overcrowding, lack of ventilation, light or sanitary facilities, or any combination of these factors, are detrimental to safety, health and morals.

. "Housing project" shall mean any work or undertaking: (a) To demolish, clear or remove buildings from any slum area; such work or undertaking may embrace the adaptation of such area to public purposes, including parks or other recreational or community purposes; or (b) to provide decent, safe and sanitary urban or rural dwellings, apartments, mobile home parks, or other living accommodations for persons of low income; such work or undertaking may include the rehabilitation of dwellings owned by persons of low income, and also may include buildings, land, equipment, facilities and other real or personal property for necessary, convenient or desirable appurtenances, streets, sewers, water service, parks, site preparation, gardening, administrative, community, health, recreational, welfare or other purposes; or (c) without limitation by implication, to provide decent, safe, and sanitary urban and rural dwellings, apartments, mobile home parks, or other living accommodations for senior citizens; such work or undertaking may include buildings, land, equipment, facilities, and other real or personal property for necessary, convenient, or desirable appurtenances, streets, sewers, water service, parks, site preparation, gardening, administrative, community, health, recreational, welfare, or other purposes; or (d) to accomplish a combination of the foregoing. The term "housing project" also may be applied to the planning of the buildings and improvements, the acquisition of property, the demolition of existing structures, the construction, reconstruction, alteration and repair of the improvements and all other work in connection therewith.

. "Persons of low income" shall mean persons or families who lack the amount of income which is necessary (as determined by the authority undertaking the housing project) to enable them, without financial assistance, to live in decent, safe and sanitary dwellings, without overcrowding.

. "Bonds" shall mean any bonds, notes, interim certificates, debentures, or other obligations issued by the authority pursuant to this chapter.

. "Real property" shall include all lands, including improvements and fixtures thereon, and property of any nature appurtenant thereto, or used in connection therewith, and every estate, interest and right, legal or equitable, therein, including terms for years and liens by way of judgment, mortgage or otherwise and the indebtedness secured by such liens.

. "Obligee of the authority" or "obligee" shall include any bondholder, trustee or trustees for any bondholders, or lessor demising to the authority property used in connection with a housing project, or any assignee or assignees of such lessor's interest or any part thereof, and the federal government when it is a party to any contract with the authority.

. "Mortgage loan" shall mean an interest bearing obligation secured by a mortgage.

. "Mortgage" shall mean a mortgage deed, deed of trust or other instrument securing a mortgage loan and constituting a lien on real property held in fee simple, or on a leasehold under a lease having a remaining term at the time the mortgage is acquired of not less than the term for repayment of the mortgage loan secured by the mortgage, improved or to be improved by a housing project.

. "Senior citizen" means a person age sixty-two or older who is determined by the authority to be poor or infirm but who is otherwise in some manner able to provide the authority with revenue which (together with all other available moneys, revenues, income, and receipts of the authority, from whatever sources derived) will be sufficient: (a) To pay, as the same become due, the principal and interest on bonds of the authority; (b) to meet the cost of, and to provide for, maintaining and operating projects (including the cost of insurance) and administrative expenses of the authority; and (c) to create (by not less than the six years immediately succeeding the issuance of any bonds) a reserve sufficient to meet the principal and interest payments which will be due on the bonds in any one year thereafter and to maintain such reserve.

. "Commercial space" shall mean space which, because of its proximity to public streets, sidewalks, or other thoroughfares, is well suited for commercial or office use. Commercial space includes but is not limited to office as well as retail space.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c363.pdf?cite=1989%20c%20363%20§%201[1989 c 363 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c225.pdf?cite=1983%20c%20225%20§%201[1983 c 225 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c187.pdf?cite=1979%20ex.s.%20c%20187%20§%201[1979 ex.s. c 187 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c274.pdf?cite=1977%20ex.s.%20c%20274%20§%201[1977 ex.s. c 274 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.82.020[1965 c 7 § 35.82.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c23.pdf?cite=1939%20c%2023%20§%203[1939 c 23 § 3]; RRS § 6889-3; ]

== 35.82.030 - Creation of housing authorities.
In each city (as herein defined) and in each county of the state there is hereby created a public body corporate and politic to be known as the "Housing Authority" of the city or county: PROVIDED, HOWEVER, That such authority shall not transact any business or exercise its powers hereunder until or unless the governing body of the city or the county, as the case may be, by proper resolution shall declare at any time hereafter that there is need for an authority to function in such city or county. The determination as to whether or not there is such need for an authority to function (1) may be made by the governing body on its own motion or (2) shall be made by the governing body upon the filing of a petition signed by twenty-five residents of the city or county, as the case may be, asserting that there is need for an authority to function in such city or county and requesting that the governing body so declare.

The governing body shall adopt a resolution declaring that there is need for a housing authority in the city or county, as the case may be, if it shall find (1) that insanitary or unsafe inhabited dwelling accommodations exist in such city or county; (2) that there is a shortage of safe or sanitary dwelling accommodations in such city or county available to persons of low income at rentals they can afford; or (3) that there is a shortage of safe or sanitary dwellings, apartments, mobile home parks, or other living accommodations available for senior citizens. In determining whether dwelling accommodations are unsafe or insanitary said governing body may take into consideration the degree of overcrowding, the percentage of land coverage, the light, air, space and access available to the inhabitants of such dwelling accommodations, the size and arrangement of the rooms, the sanitary facilities, and the extent to which conditions exist in such buildings which endanger life or property by fire or other causes.

In any suit, action or proceeding involving the validity or enforcement of or relating to any contract of the authority, the authority shall be conclusively deemed to have become established and authorized to transact business and exercise its powers hereunder upon proof of the adoption of a resolution by the governing body declaring the need for the authority. Such resolution or resolutions shall be deemed sufficient if it declares that there is such need for an authority and finds in substantially the foregoing terms (no further detail being necessary) that either or both of the above enumerated conditions exist in the city or county, as the case may be. A copy of such resolution duly certified by the clerk shall be admissible in evidence in any suit, action or proceeding.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c187.pdf?cite=1979%20ex.s.%20c%20187%20§%202[1979 ex.s. c 187 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.82.030[1965 c 7 § 35.82.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c23.pdf?cite=1939%20c%2023%20§%204[1939 c 23 § 4]; RRS § 6889-4; ]

== 35.82.040 - Appointment, qualifications, and tenure of commissioners.
Except as provided in RCW 35.82.045, when the governing body of a city adopts a resolution declaring that there is a need for a housing authority, it shall promptly notify the mayor of such adoption. Upon receiving such notice, the mayor shall appoint five persons as commissioners of the authority created for the city. When the governing body of a county adopts a resolution declaring that there is a need for a housing authority, it shall appoint five persons as commissioners of the authority created for the county. The commissioners who are first appointed shall be designated to serve for terms of one, two, three, four and five years, respectively, from the date of their appointment, but thereafter commissioners shall be appointed for a term of office of five years except that all vacancies shall be filled for the unexpired term. No commissioner of an authority may be an officer or employee of the city or county for which the authority is created, unless the commissioner is an employee of a separately elected county official other than the county governing body in a county with a population of less than one hundred seventy-five thousand as of the 1990 federal census, and the total government employment in that county exceeds forty percent of total employment. A commissioner shall hold office until a successor has been appointed and has qualified, unless sooner removed according to this chapter. A certificate of the appointment or reappointment of any commissioner shall be filed with the clerk and such certificate shall be conclusive evidence of the due and proper appointment of such commissioner. A commissioner shall receive no compensation for his or her services for the authority, in any capacity, but he or she shall be entitled to the necessary expenses, including traveling expenses, incurred in the discharge of his or her duties.

The powers of each authority shall be vested in the commissioners thereof in office from time to time. Except as provided in RCW 35.82.045, three commissioners shall constitute a quorum of the authority for the purpose of conducting its business and exercising its powers and for all other purposes. Action may be taken by the authority upon a vote of a majority of the commissioners present, unless in any case the bylaws of the authority shall require a larger number. The mayor (or in the case of an authority for a county, the governing body of the county) shall designate which of the commissioners appointed shall be the first chair of the commission and he or she shall serve in the capacity of chair until the expiration of his or her term of office as commissioner. When the office of the chair of the authority becomes vacant, the authority shall select a chair from among its commissioners. An authority shall select from among its commissioners a vice chair, and it may employ a secretary (who shall be executive director), technical experts and such other officers, agents and employees, permanent and temporary, as it may require, and shall determine their qualifications, duties and compensation. For such legal services as it may require, an authority may call upon the chief law officer of the city or the county or may employ its own counsel and legal staff. An authority may delegate to one or more of its agents or employees such powers or duties as it may deem proper.

If federal law requires that the membership of the board of commissioners of a local authority contains one member who is directly assisted by the authority, the board may by resolution temporarily or permanently increase its size to six members. The board may determine the length of the term of the position filled by a directly assisted member. A person appointed to such a position may serve in that position only as long as he or she is directly assisted by the authority.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5156.SL.pdf?cite=1999%20c%2077%20§%201[1999 c 77 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2459-S.SL.pdf?cite=1998%20c%20140%20§%201[1998 c 140 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1725.SL.pdf?cite=1995%20c%20293%20§%201[1995 c 293 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.82.040[1965 c 7 § 35.82.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c23.pdf?cite=1939%20c%2023%20§%205[1939 c 23 § 5]; RRS § 6889-5; ]

== 35.82.045 - Cities with a population of four hundred thousand or more—Appointment of additional commissioners—Appointment, compensation of commissioners—Organization of authority.
. After June 11, 1998, the governing body of a city with a population of four hundred thousand or more, that has created a housing authority under RCW 35.82.040, shall adopt a resolution to expand the number of commissioners on the housing authority from five to seven. Upon receiving the notice, the mayor, with approval of the city council, shall appoint additional persons as commissioners of the authority created for the city.

. In appointing commissioners, the mayor shall consider persons that represent the community, provided that two commissioners shall consist of tenants that reside in a housing project that is owned by the housing authority.

. After June 11, 1998, all commissioners shall be appointed to serve four-year terms, except that all vacancies shall be filled for the remainder of the unexpired term. A commissioner of an authority may not be an officer or employee of the city for which the authority is created. A commissioner shall hold office until a successor has been appointed and has qualified, unless sooner removed according to this chapter.

. A commissioner may be reappointed only after review and approval by the city council.

. A certificate of the appointment or reappointment of any commissioner shall be filed with the clerk and the certificate is conclusive evidence of the due and proper appointment of the commissioner.

. A commissioner shall receive no compensation for his or her services for the authority, in any capacity, but he or she is entitled to the necessary expenses, including traveling expenses, incurred in the discharge of his or her duties.

. The powers of each authority vest in the commissioners of the authority in office from time to time. Four commissioners shall constitute a quorum of the authority for the purpose of conducting its business and exercising its powers and for all other purposes. Action may be taken by the authority upon a vote of a majority of the commissioners present, unless in any case the bylaws of the authority shall require a larger number.

. The mayor, with consent of the city council, shall designate which of the commissioners appointed shall be the first chair of the commission and he or she shall serve in the capacity of chair until the expiration of his or her term of office as commissioner. When the office of the chair of the authority becomes vacant, the authority shall select a chair from among its commissioners. An authority shall select from among its commissioners a vice chair, and the authority may employ a secretary, who shall be executive director, technical experts and such other officers, agents, and employees, permanent and temporary, as the authority requires, and shall determine their qualifications, duties, and compensation.

. For such legal services as it may require, an authority may call upon the chief law officer of the city or may employ its own counsel and legal staff. An authority may delegate to one or more of its agents or employees such powers or duties as it may deem proper.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2459-S.SL.pdf?cite=1998%20c%20140%20§%202[1998 c 140 § 2]; ]

== 35.82.050 - Conflicts of interest for commissioners, employees, and appointees.
. No commissioner, employee, or appointee to any decision-making body for the housing authority shall own or hold an interest in any contract or property or engage in any business, transaction, or professional or personal activity, that would:

.. Be, or appear to be, in conflict with the commissioner's, employee's, or appointee's official duties to any decision-making body for the housing authority duties relating to the housing authority served by or subject to the authority of such commissioner, employee, or appointee to any decision-making body for the housing authority;

.. Secure, or appear to secure, unwarranted privileges or advantages for such commissioner, employee, or appointee to any decision-making body for the housing authority, or others; or

.. Prejudice, or appear to prejudice, such commissioner's, employee's, or appointee's to any decision-making body for the housing authority independence of judgment in exercise of his or her official duties relating to the housing authority served by or subject to the authority of the commissioner, employee, or appointee to any decision-making body for the housing authority.

. No commissioner, employee, or appointee to any decision-making body for the housing authority shall act in an official capacity in any manner in which such commissioner, employee, or appointee to any decision-making body of the housing authority has a direct or indirect financial or personal involvement.

. No commissioner, employee, or appointee to any decision-making body for the housing authority shall use his or her public office or employment to secure financial gain to such commissioner, employee, or appointee to any decision-making body for the housing authority.

. If any commissioner or employee of an authority or any appointee to any decision-making body for the housing authority owns or controls an interest direct or indirect in any property included or planned to be included in any housing project, he or she immediately shall disclose the same in writing to the authority and such disclosure shall be entered upon the minutes of the authority. Failure to disclose such interest shall constitute misconduct in office. Upon such disclosure such commissioner, employee, or appointee to any decision-making body for the housing authority shall not participate in any action by the authority affecting such property.

. No provision of this section shall preclude a tenant of the public housing authority from serving as a commissioner, employee, or appointee to any decision-making body of the housing authority. No provision of this section shall preclude a tenant of the public housing authority who is serving as a commissioner, employee, or appointee to any decision-making body of the housing authority from voting on any issue or decision, or participating in any action by the authority, unless a conflict of interest, as set forth in subsections (1) through (4) of this section, exists as to that particular tenant and the particular property or interest at issue before, or subject to action by the housing authority.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202124[2009 c 549 § 2124]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2459-S.SL.pdf?cite=1998%20c%20140%20§%203[1998 c 140 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.82.050[1965 c 7 § 35.82.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c23.pdf?cite=1939%20c%2023%20§%206[1939 c 23 § 6]; RRS § 6889-6; ]

== 35.82.060 - Removal of commissioners.
For inefficiency or neglect of duty or misconduct in office, a commissioner of an authority may be removed by the mayor (or in the case of an authority for a county, by the governing body of said county), but a commissioner shall be removed only after he or she shall have been given a copy of the charges at least ten days prior to the hearing thereon and had an opportunity to be heard in person or by counsel. In the event of the removal of any commissioner, a record of the proceedings, together with the charges and findings thereon, shall be filed in the office of the clerk.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202125[2009 c 549 § 2125]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.82.060[1965 c 7 § 35.82.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c23.pdf?cite=1939%20c%2023%20§%207[1939 c 23 § 7]; RRS § 6889-7; ]

== 35.82.070 - Powers of authority.
An authority shall constitute a public body corporate and politic, exercising public and essential governmental functions, and having all the powers necessary or convenient to carry out and effectuate the purposes and provisions of this chapter, including the following powers in addition to others herein granted:

. To sue and be sued; to have a seal and to alter the same at pleasure; to have perpetual succession; to make and execute contracts and other instruments, including but not limited to partnership agreements and joint venture agreements, necessary or convenient to the exercise of the powers of the authority; to participate in the organization or the operation of a nonprofit corporation which has as one of its purposes to provide or assist in the provision of housing for persons of low income; and to make and from time to time amend and repeal bylaws, rules and regulations, not inconsistent with this chapter, to carry into effect the powers and purposes of the authority.

. Within its area of operation: To prepare, carry out, acquire, lease and operate housing projects; to provide for the construction, reconstruction, improvement, alteration or repair of any housing project or any part thereof; to agree to rent or sell dwellings forming part of the projects to or for persons of low income. Where an agreement or option is made to sell a dwelling to a person of low income, the authority may convey the dwelling to the person upon fulfillment of the agreement irrespective of whether the person is at the time of the conveyance a person of low income. Leases, options, agreements, or conveyances may include such covenants as the authority deems appropriate to assure the achievement of the objectives of this chapter.

. To acquire, lease, rent, sell, or otherwise dispose of any commercial space located in buildings or structures containing a housing project or projects.

. To arrange or contract for the furnishing by any person or agency, public or private, of services, privileges, works, or facilities for, or in connection with, a housing project or the occupants thereof; and (notwithstanding anything to the contrary contained in this chapter or in any other provision of law) to include in any contract let in connection with a project, stipulations requiring that the contractor and any subcontractors comply with requirements as to minimum wages and maximum hours of labor, and comply with any conditions which the federal government may have attached to its financial aid of the project.

. To lease or rent any dwellings, houses, accommodations, lands, buildings, structures or facilities embraced in any housing project and (subject to the limitations contained in this chapter) to establish and revise the rents or charges therefor; to own or manage buildings containing a housing project or projects as well as commercial space or other dwelling units that do not constitute a housing project as that term is defined in this chapter. However, notwithstanding the provisions under subsection (1) of this section, dwelling units made available or sold to persons of low income, together with functionally related and subordinate facilities, shall occupy at least fifty percent of the interior space in the total development owned by the authority or at least fifty percent of the total number of units in the development owned by the authority, whichever produces the greater number of units for persons of low income, and for mobile home parks, the mobile home lots made available to persons of low income shall be at least fifty percent of the total number of mobile home lots in the park owned by the authority; to own, hold, and improve real or personal property; to purchase, lease, obtain options upon, acquire by gift, grant, bequest, devise, or otherwise including financial assistance and other aid from the state or any public body, person or corporation, any real or personal property or any interest therein; to acquire by the exercise of the power of eminent domain any real property; to sell, lease, exchange, transfer, assign, pledge, or dispose of any real or personal property or any interest therein; to sell, lease, exchange, transfer, or dispose of any real or personal property or interest therein at less than fair market value to a governmental entity for any purpose when such action assists the housing authority in carrying out its powers and purposes under this chapter, to a low-income person or family for the purpose of providing housing for that person or family, or to a nonprofit corporation provided the nonprofit corporation agrees to sell the property to a low-income person or family or to use the property for the provision of housing for persons of low income for at least twenty years; to insure or provide for the insurance of any real or personal property or operations of the authority against any risks or hazards; to procure or agree to the procurement of insurance or guarantees from the federal government of the payment of any bonds or parts thereof issued by an authority, including the power to pay premiums on any such insurance.

. To invest any funds held in reserves or sinking funds, or any funds not required for immediate disbursement, in property or securities in which savings banks may legally invest funds subject to their control; to purchase its bonds at a price not more than the principal amount thereof and accrued interest, all bonds so purchased to be canceled.

. Within its area of operation: To investigate into living, dwelling and housing conditions and into the means and methods of improving such conditions; to determine where slum areas exist or where there is a shortage of decent, safe and sanitary dwelling accommodations for persons of low income; to make studies and recommendations relating to the problem of clearing, replanning and reconstructing of slum areas, and the problem of providing dwelling accommodations for persons of low income, and to cooperate with the city, the county, the state or any political subdivision thereof in action taken in connection with such problems; and to engage in research, studies and experimentation on the subject of housing.

. Acting through one or more commissioners or other person or persons designated by the authority: To conduct examinations and investigations and to hear testimony and take proof under oath at public or private hearings on any matter material for its information; to administer oaths, issue subpoenas requiring the attendance of witnesses or the production of books and papers and to issue commissions for the examination of witnesses who are outside of the state or unable to attend before the authority, or excused from attendance; to make available to appropriate agencies (including those charged with the duty of abating or requiring the correction of nuisances or like conditions, or of demolishing unsafe or insanitary structures within its area of operation) its findings and recommendations with regard to any building or property where conditions exist which are dangerous to the public health, morals, safety or welfare.

. To initiate eviction proceedings against any tenant as provided by law. Activity occurring in any housing authority unit that constitutes a violation of chapter 69.41, 69.50 or 69.52 RCW shall constitute a nuisance for the purpose of RCW 59.12.030(5).

. To exercise all or any part or combination of powers herein granted.

No provisions of law with respect to the acquisition, operation or disposition of property by other public bodies shall be applicable to an authority unless the legislature shall specifically so state.

. To agree (notwithstanding the limitation contained in RCW 35.82.210) to make such payments in lieu of taxes as the authority finds consistent with the achievement of the purposes of this chapter.

. Upon the request of a county or city, to exercise any powers of a community renewal agency under chapter 35.81 RCW or a public corporation, commission, or authority under chapter 35.21 RCW.

. To exercise the powers granted in this chapter within the boundaries of any city, town, or county not included in the area in which such housing authority is originally authorized to function: PROVIDED, HOWEVER, The governing or legislative body of such city, town, or county, as the case may be, adopts a resolution declaring that there is a need for the authority to function in such territory.

. To administer contracts for assistance payments to persons of low income in accordance with section 8 of the United States Housing Act of 1937, as amended by Title II, section 201 of the Housing and Community Development Act of 1974, P.L. 93-383.

. To sell at public or private sale, with or without public bidding, for fair market value, any mortgage or other obligation held by the authority.

. To the extent permitted under its contract with the holders of bonds, notes, and other obligations of the authority, to consent to any modification with respect to rate of interest, time and payment of any installment of principal or interest security, or any other term of any contract, mortgage, mortgage loan, mortgage loan commitment, contract or agreement of any kind to which the authority is a party.

. To make, purchase, participate in, invest in, take assignments of, or otherwise acquire loans to persons of low income to enable them to acquire, construct, reconstruct, rehabilitate, improve, lease, or refinance their dwellings, and to take such security therefor as is deemed necessary and prudent by the authority.

. To make, purchase, participate in, invest in, take assignments of, or otherwise acquire loans for the acquisition, construction, reconstruction, rehabilitation, improvement, leasing, or refinancing of land, buildings, or developments for housing for persons of low income. For purposes of this subsection, development shall include either land or buildings or both.

.. Any development financed under this subsection shall be subject to an agreement that for at least twenty years the dwelling units made available to persons of low income together with functionally related and subordinate facilities shall occupy at least fifty percent of the interior space in the total development or at least fifty percent of the total number of units in the development, whichever produces the greater number of units for persons of low income. For mobile home parks, the mobile home lots made available to persons of low income shall be at least fifty percent of the total number of mobile home lots in the park. During the term of the agreement, the owner shall use its best efforts in good faith to maintain the dwelling units or mobile home lots required to be made available to persons of low income at rents affordable to persons of low income. The twenty-year requirement under this subsection (18)(a) shall not apply when an authority finances the development by nonprofit corporations or governmental units of dwellings or mobile home lots intended for sale to persons of low and moderate income, and shall not apply to construction or other short-term financing provided to nonprofit corporations or governmental units when the financing has a repayment term of one year or less.

.. In addition, if the development is owned by a for-profit entity, the dwelling units or mobile home lots required to be made available to persons of low income shall be rented to persons whose incomes do not exceed fifty percent of the area median income, adjusted for household size, and shall have unit or lot rents that do not exceed fifteen percent of area median income, adjusted for household size, unless rent subsidies are provided to make them affordable to persons of low income.

For purposes of this subsection (18)(b), if the development is owned directly or through a partnership by a governmental entity or a nonprofit organization, which nonprofit organization is itself not controlled by a for-profit entity or affiliated with any for-profit entity that a nonprofit organization itself does not control, it shall not be treated as being owned by a for-profit entity when the governmental entity or nonprofit organization exercises legal control of the ownership entity and in addition, (i) the dwelling units or mobile home lots required to be made available to persons of low income are rented to persons whose incomes do not exceed sixty percent of the area median income, adjusted for household size, and (ii) the development is subject to an agreement that transfers ownership to the governmental entity or nonprofit organization or extends an irrevocable right of first refusal to purchase the development under a formula for setting the acquisition price that is specified in the agreement.

.. Commercial space in any building financed under this subsection that exceeds four stories in height shall not constitute more than twenty percent of the interior area of the building. Before financing any development under this subsection the authority shall make a written finding that financing is important for project feasibility or necessary to enable the authority to carry out its powers and purposes under this chapter.

. To contract with a public authority or corporation, created by a county, city, or town under RCW 35.21.730 through 35.21.755, to act as the developer for new housing projects or improvement of existing housing projects.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2357-S.SL.pdf?cite=2002%20c%20218%20§%2022[2002 c 218 § 22]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5584.SL.pdf?cite=1993%20c%20478%20§%2017[1993 c 478 § 17]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1740.SL.pdf?cite=1991%20c%20167%20§%201[1991 c 167 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c363.pdf?cite=1989%20c%20363%20§%202[1989 c 363 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c386.pdf?cite=1985%20c%20386%20§%201[1985 c 386 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c225.pdf?cite=1983%20c%20225%20§%202[1983 c 225 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c274.pdf?cite=1977%20ex.s.%20c%20274%20§%202[1977 ex.s. c 274 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.82.070[1965 c 7 § 35.82.070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c43.pdf?cite=1945%20c%2043%20§%201[1945 c 43 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c23.pdf?cite=1939%20c%2023%20§%208[1939 c 23 § 8]; Rem. Supp. 1945 § 6889-8; ]

== 35.82.076 - Small works roster.
A housing authority may establish and use a small works roster for awarding contracts under RCW 39.04.155.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6347-S.SL.pdf?cite=2000%20c%20138%20§%20205[2000 c 138 § 205]; ]

== 35.82.080 - Operation not for profit.
It is hereby declared to be the policy of this state that each housing authority shall manage and operate its housing projects in an efficient manner so as to enable it to fix the rentals for low-income dwelling accommodations at the lowest possible rates consistent with its providing decent, safe and sanitary dwelling accommodations, and that no housing authority shall construct or operate any such project for profit, or as a source of revenue to the city or the county. To this end, an authority shall fix the rentals for rental units for persons of low income in projects owned or leased by the authority at no higher rates than it shall find to be necessary in order to produce revenues which (together with all other available moneys, revenues, income and receipts of the authority from whatever sources derived) will be sufficient (1) to pay, as the same become due, the principal and interest on the bonds or other obligations of the authority issued or incurred to finance the projects; (2) to meet the cost of, and to provide for, maintaining and operating the projects (including the cost of any insurance) and the administrative expenses of the authority; and (3) to create (during not less than the six years immediately succeeding its issuance of any such bonds) a reserve sufficient to meet the largest principal and interest payments which will be due on such bonds in any one year thereafter and to maintain such reserve. Nothing contained in this section shall be construed to limit an authority's power to rent commercial space located in buildings containing housing projects or non low-income units owned, acquired, financed, or constructed under *RCW 35.82.070(5), (16), or (17) at profitable rates and to use any profit realized from such rentals in carrying into effect the powers and purposes provided to housing authorities under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c363.pdf?cite=1989%20c%20363%20§%203[1989 c 363 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c225.pdf?cite=1983%20c%20225%20§%203[1983 c 225 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c274.pdf?cite=1977%20ex.s.%20c%20274%20§%203[1977 ex.s. c 274 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.82.080[1965 c 7 § 35.82.080]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c23.pdf?cite=1939%20c%2023%20§%209[1939 c 23 § 9]; RRS § 6889-9; ]

== 35.82.090 - Rentals and tenant selection.
In the operation and management of rental units which are rented to persons of low income in any housing project an authority shall at all times observe the following duties with respect to rentals and tenant selection: (1) It may rent or lease the dwelling accommodations therein to persons of low income and at rentals within the financial reach of such persons of low income; (2) it may rent or lease to a low-income tenant dwelling accommodations consisting of the number of rooms (but no greater number) which it deems necessary to provide safe and sanitary accommodations to the proposed occupants thereof, without overcrowding; and (3) it shall not accept any person as a low income tenant in any housing project designated for persons of low income if the person or persons who would occupy the dwelling accommodations have an annual net income in excess of five times the annual rental of the quarters to be furnished such person or persons, except that in the case of families with three or more minor dependents, such ratio shall not exceed six to one; in computing the rental for this purpose of selecting tenants, there shall be included in the rental the average annual cost (as determined by the authority) to occupants of heat, water, electricity, gas, cooking range and other necessary services or facilities, whether or not the charge for such services and facilities is in fact included in the rental. This income limitation does not apply to housing projects designated for senior citizens.

Nothing contained in this section or RCW 35.82.080 shall be construed as limiting the power of an authority to vest in an obligee the right, in the event of a default by the authority, to take possession of a housing project or cause the appointment of a receiver thereof, free from all the restrictions imposed by this section or RCW 35.82.080.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c363.pdf?cite=1989%20c%20363%20§%204[1989 c 363 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c187.pdf?cite=1979%20ex.s.%20c%20187%20§%203[1979 ex.s. c 187 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c274.pdf?cite=1977%20ex.s.%20c%20274%20§%204[1977 ex.s. c 274 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.82.090[1965 c 7 § 35.82.090]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c23.pdf?cite=1939%20c%2023%20§%2010[1939 c 23 § 10]; RRS § 6889-10; ]

== 35.82.100 - Cooperation between authorities.
Any two or more authorities may join or cooperate with one another in the exercise of any or all of the powers conferred hereby for the purpose of financing, planning, undertaking, constructing or operating a housing project or projects located within the area of operation of any one or more of said authorities.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.82.100[1965 c 7 § 35.82.100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c23.pdf?cite=1939%20c%2023%20§%2011[1939 c 23 § 11]; RRS § 6889-11; ]

== 35.82.110 - Eminent domain.
An authority shall have the right to acquire by the exercise of the power of eminent domain any real property which it may deem necessary for its purposes under this chapter after the adoption by it of a resolution declaring that the acquisition of the real property described therein is necessary for such purposes. An authority may exercise the power of eminent domain in the same manner and under the same procedure as now is or may be hereafter provided by law in the case of other corporations authorized by the laws of the state to exercise the right of eminent domain; or it may exercise the power of eminent domain in the manner now or which may be hereafter provided by any other applicable statutory provisions for the exercise of the power of eminent domain. Property already devoted to a public use may be acquired in like manner: PROVIDED, That no real property belonging to the city, the county, the state or any political subdivision thereof may be acquired without its consent.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.82.110[1965 c 7 § 35.82.110]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c23.pdf?cite=1939%20c%2023%20§%2012[1939 c 23 § 12]; RRS § 6889-12; ]

== 35.82.120 - Planning, zoning and building laws.
All housing projects of an authority shall be subject to the planning, zoning, sanitary and building laws, ordinances and regulations applicable to the locality in which the housing project is situated. In the planning and location of any housing project, an authority shall take into consideration the relationship of the project to any larger plan or long-range program for the development of the area in which the housing authority functions.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.82.120[1965 c 7 § 35.82.120]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c23.pdf?cite=1939%20c%2023%20§%2013[1939 c 23 § 13]; RRS § 6889-13; ]

== 35.82.130 - Bonds.
An authority shall have power to issue bonds from time to time in its discretion, for any of its corporate purposes. An authority shall also have power to issue refunding bonds for the purpose of paying or retiring bonds previously issued by it. An authority may issue such types of bonds as it may determine, including (without limiting the generality of the foregoing) bonds on which the principal and interest are payable: (1) Exclusively from the income and revenues of the housing project financed with the proceeds of such bonds; (2) exclusively from the income and revenues of certain designated housing projects whether or not they are financed in whole or in part with the proceeds of such bonds; or (3) from all or part of its revenues or assets generally. Any such bonds may be additionally secured by a pledge of any grant or contributions from the federal government or other source, or a pledge of any income or revenues of the authority, or a mortgage of any housing project, projects or other property of the authority. Any pledge made by the authority shall be valid and binding from the time when the pledge is made; the revenues, moneys, or property so pledged and thereafter received by the authority shall immediately be subject to the lien of the pledge without any physical delivery thereof or further act, and the lien of any such pledge shall be valid and binding as against all parties having claims of any kind in tort, contract, or otherwise against the authority, irrespective or whether the parties have notice thereof. 

Neither the commissioners of an authority nor any person executing the bonds shall be liable personally on the bonds by reason of the issuance thereof. The bonds and other obligations of an authority (and such bonds and obligations shall so state on their face) shall not be a debt of the city, the county, the state or any political subdivision thereof and neither the city or the county, nor the state or any political subdivision thereof shall be liable thereon, nor in any event shall such bonds or obligations be payable out of any funds or properties other than those of the authority. The bonds shall not constitute an indebtedness within the meaning of any constitutional or statutory debt limitation or restriction. Bonds of an authority are declared to be issued for an essential public and governmental purpose and to be public instrumentalities and, together with interest thereon and income therefrom, shall be exempt from taxes. Nothing in this section shall prevent an authority from issuing bonds the interest on which is included in gross income of the owners thereof for income tax purposes.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1725.SL.pdf?cite=1995%20c%20293%20§%202[1995 c 293 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1740.SL.pdf?cite=1991%20c%20167%20§%202[1991 c 167 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c274.pdf?cite=1977%20ex.s.%20c%20274%20§%205[1977 ex.s. c 274 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.82.130[1965 c 7 § 35.82.130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c23.pdf?cite=1939%20c%2023%20§%2014[1939 c 23 § 14]; RRS § 6889-14; ]

== 35.82.140 - Form and sale of bonds.
. Bonds of an authority shall be authorized by its resolution and may be issued in one or more series and shall bear such date or dates, mature at such time or times, bear interest at such rate or rates, be in such denomination or denominations, be in such form, either coupon or registered as provided in RCW 39.46.030, carry such conversion or registration privileges, have such rank or priority, be executed in such manner, be payable in such medium of payment, at such place or places, and be subject to such terms of redemption (with or without premium) as such resolution, its trust indenture or mortgage may provide.

The bonds may be sold at public or private sale.

In case any of the commissioners or officers of the authority whose signatures appear on any bond or any coupons shall cease to be such commissioners or officers before the delivery of such bonds, such signatures shall, nevertheless, be valid and sufficient for all purposes, the same as if they had remained in office until such delivery. Any provision of any law to the contrary notwithstanding, any bonds issued pursuant to this chapter shall be fully negotiable.

In any suit, action or proceedings involving the validity or enforceability of any bond of an authority or the security therefor, any such bond reciting in substance that it has been issued by the authority to aid in financing a housing project to provide dwelling accommodations for persons of low income shall be conclusively deemed to have been issued for a housing project of such character and said project shall be conclusively deemed to have been planned, located and constructed in accordance with the purposes and provisions of this chapter.

. Notwithstanding subsection (1) of this section, such bonds may be issued and sold in accordance with chapter 39.46 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c167.pdf?cite=1983%20c%20167%20§%2065[1983 c 167 § 65]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c274.pdf?cite=1977%20ex.s.%20c%20274%20§%206[1977 ex.s. c 274 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c56.pdf?cite=1970%20ex.s.%20c%2056%20§%2045[1970 ex.s. c 56 § 45]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c232.pdf?cite=1969%20ex.s.%20c%20232%20§%2022[1969 ex.s. c 232 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.82.140[1965 c 7 § 35.82.140]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c23.pdf?cite=1939%20c%2023%20§%2015[1939 c 23 § 15]; RRS § 6889-15; ]

== 35.82.150 - Provisions of bonds, trust indentures, and mortgages.
In connection with the issuance of bonds or the incurring of obligations under leases and in order to secure the payment of such bonds or obligations, an authority, in addition to its other powers, shall have power:

. To pledge all or any part of its gross or net rents, fees, revenues, or assets, including mortgage loans and obligations securing the same, to which its right then exists or may thereafter come into existence.

. To mortgage all or any part of its real or personal property, then owned or thereafter acquired.

. To covenant against pledging all or any part of its rents, fees and revenues, or against mortgaging all or any part of its real or personal property, to which its right or title then exists or may thereafter come into existence or against permitting or suffering any lien on such revenues or property; to covenant with respect to limitations on its right to sell, lease or otherwise dispose of any housing project or any part thereof; and to covenant as to what other, or additional debts or obligations may be incurred by it.

. To covenant as to the bonds to be issued and as to the issuance of such bonds in escrow or otherwise, and as to the use and disposition of the proceeds thereof; to provide for the replacement of lost, destroyed or mutilated bonds; to covenant against extending the time for the payment of its bonds or interest thereon; and to redeem the bonds, and to covenant for their redemption and to provide the terms and conditions thereof.

. To covenant (subject to the limitations contained in this chapter) as to the rents and fees to be charged in the operation of a housing project or projects, the amount to be raised each year or other period of time by rents, fees and other revenues, and as to the use and disposition to be made thereof; to create or to authorize the creation of special funds for moneys held for construction or operating costs, debt service, reserves, or other purposes, and to covenant as to the use and disposition of the moneys held in such funds.

. To prescribe the procedure, if any, by which the terms of any contract with bondholders may be amended or abrogated, the amount of bonds the holders of which must consent thereto and the manner in which such consent may be given.

. To covenant as to use of any or all of its real or personal property; and to covenant as to the maintenance of its real and personal property, the replacement thereof, the insurance to be carried thereon and the use and disposition of insurance moneys.

. To covenant as to the rights, liabilities, powers and duties arising upon the breach by it of any covenant, condition, or obligation; and to covenant and prescribe as to events of default and terms and conditions upon which any or all of its bonds or obligations shall become or may be declared due before maturity, and as to the terms and conditions upon which such declaration and its consequences may be waived.

. To vest in a trustee or trustees or the holders of bonds or any proportion of them the right to enforce the payment of the bonds or any covenants securing or relating to the bonds; to vest in a trustee or trustees the right, in the event of a default by said authority, to take possession and use, operate and manage any housing project or part thereof, and to collect the rents and revenues arising therefrom and to dispose of such moneys in accordance with the agreement of the authority with said trustee; to provide for the powers and duties of a trustee or trustees and to limit the liabilities thereof; and to provide the terms and conditions upon which the trustee or trustees or the holders of bonds or any proportion of them may enforce any covenant or rights securing or relating to the bonds.

. To covenant as to the use and disposition of the gross income from mortgages owned by the authority and payment of principal of the mortgages.

. To exercise all or any part or combination of the powers herein granted; to make covenants other than and in addition to the covenants herein expressly authorized, of like or different character; to make such covenants and to do any and all such acts and things as may be necessary or convenient or desirable in order to secure its bonds, or, in the absolute discretion of said authority, as will tend to make the bonds more marketable notwithstanding that such covenants, acts or things may not be enumerated herein.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c274.pdf?cite=1977%20ex.s.%20c%20274%20§%207[1977 ex.s. c 274 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.82.150[1965 c 7 § 35.82.150]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c23.pdf?cite=1939%20c%2023%20§%2016[1939 c 23 § 16]; RRS § 6889-16; ]

== 35.82.160 - Certification by attorney general.
Any authority may submit to the attorney general of the state any bonds to be issued hereunder after all proceedings for the issuance of such bonds have been taken. Upon the submission of such proceedings to the attorney general, it shall be the duty of the attorney general to examine into and pass upon the validity of such bonds and the regularity of all proceedings in connection therewith. If such proceedings conform to the provisions of this chapter and are otherwise regular in form and if such bonds when delivered and paid for will constitute binding and legal obligations of the authority enforceable according to the terms thereof, the attorney general shall certify in substance upon the back of each of said bonds that it is issued in accordance with the Constitution and laws of the state of Washington.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.82.160[1965 c 7 § 35.82.160]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c23.pdf?cite=1939%20c%2023%20§%2017[1939 c 23 § 17]; RRS § 6889-17; ]

== 35.82.170 - Remedies of an obligee of authority.
An obligee of an authority shall have the right in addition to all other rights which may be conferred on such obligee, subject only to any contractual restrictions binding upon such obligee:

. By mandamus, suit, action or proceeding at law or in equity to compel said authority and the commissioners, officers, agents or employees thereof to perform each and every term, provision and covenant contained in any contract of said authority with or for the benefit of such obligee, and to require the carrying out of any or all such covenants and agreements of said authority and the fulfillment of all duties imposed upon said authority by this chapter.

. By suit, action or proceeding in equity, to enjoin any acts or things which may be unlawful, or the violation of any of the rights of such obligee of said authority.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.82.170[1965 c 7 § 35.82.170]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c23.pdf?cite=1939%20c%2023%20§%2018[1939 c 23 § 18]; RRS § 6889-18; ]

== 35.82.180 - Additional remedies conferable by authority.
An authority shall have power by its resolution, trust indenture, mortgage, lease or other contract to confer upon any obligee holding or representing a specified amount in bonds, or holding a lease, the right (in addition to all rights that may otherwise be conferred), upon the happening of an event of default as defined in such resolution or instrument, by suit, action or proceeding in any court of competent jurisdiction:

. To cause possession of any housing project or any part thereof to be surrendered to any such obligee.

. To obtain the appointment of a receiver of any housing project of said authority or any part thereof and of the rents and profits therefrom. If such receiver be appointed, he or she may enter and take possession of such housing project or any part thereof and operate and maintain same, and collect and receive all fees, rents, revenues, or other charges thereafter arising therefrom, and shall keep such moneys in a separate account or accounts and apply the same in accordance with the obligations of said authority as the court shall direct.

. To require said authority and the commissioners thereof to account as if it and they were the trustees of an express trust.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202126[2009 c 549 § 2126]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.82.180[1965 c 7 § 35.82.180]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c23.pdf?cite=1939%20c%2023%20§%2019[1939 c 23 § 19]; RRS § 6889-19; ]

== 35.82.190 - Exemption of property from execution sale.
All real property of an authority shall be exempt from levy and sale by virtue of an execution, and no execution or other judicial process shall issue against the same nor shall any judgment against an authority be a charge or lien upon its real property: PROVIDED, HOWEVER, That the provisions of this section shall not apply to or limit the right of obligees to foreclose or otherwise enforce any mortgage of an authority or the right of obligees to pursue any remedies for the enforcement of any pledge or lien given by an authority on its rents, fees or revenues.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.82.190[1965 c 7 § 35.82.190]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c23.pdf?cite=1939%20c%2023%20§%2020[1939 c 23 § 20]; RRS § 6889-20; ]

== 35.82.200 - Aid from federal government—Provisions applicable to authorities.
. In addition to the powers conferred upon an authority by other provisions of this chapter, an authority is empowered to borrow money or accept contributions, grants or other financial assistance from the federal government for or in aid of any housing project within its area of operation, to take over or lease or manage any housing project or undertaking constructed or owned by the federal government, and to these ends, to comply with such conditions and enter into such mortgages, trust indentures, leases or agreements as may be necessary, convenient or desirable. It is the purpose and intent of this chapter to authorize every authority to do any and all things necessary or desirable to secure the financial aid or cooperation of the federal government in the undertaking, construction, maintenance or operation of any housing project by such authority.

. All housing authorities shall be subject to the provisions of chapter 39.10 RCW except where alternative requirements or procedures of federal law or federal regulation are authorized.

. The requirements of chapter 39.12 RCW regarding prevailing wages shall apply to housing authority public works except where specifically preempted by federal law or federal regulation.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1690.SL.pdf?cite=2010%201st%20sp.s.%20c%2021%20§%204[2010 1st sp.s. c 21 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.82.200[1965 c 7 § 35.82.200]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c23.pdf?cite=1939%20c%2023%20§%2021[1939 c 23 § 21]; RRS § 6889-21; ]

== 35.82.210 - Tax exemption and payments in lieu of taxes—Definitions.
. The property of an authority is declared to be public property used for essential public and governmental purposes and such property and an authority shall be exempt from all taxes and special assessments of the city, the county, the state or any political subdivision thereof: PROVIDED, HOWEVER, That in lieu of such taxes an authority may agree to make payments to the city or the county or any such political subdivision for improvements, services and facilities furnished by such city, county or political subdivision for the benefit of a housing project, but in no event shall such payments exceed the amount last levied as the annual tax of such city, county or political subdivision upon the property included in said project prior to the time of its acquisition by the authority.

. For the sole purpose of the exemption from tax under this section:

.. "Authority," in addition to the meaning in RCW 35.82.020, also means tribal housing authorities and intertribal housing authorities.

.. "Intertribal housing authority" means a housing authority created by a consortium of tribal governments to operate and administer housing programs for persons of low income or senior citizens for and on behalf of such tribes.

.. "Tribal government" means the governing body of a federally recognized Indian tribe.

.. "Tribal housing authority" means the tribal government or an agency or branch of the tribal government that operates and administers housing programs for persons of low income or senior citizens.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2109-S2.SL.pdf?cite=2000%20c%20187%20§%202[2000 c 187 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.82.210[1965 c 7 § 35.82.210]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c23.pdf?cite=1939%20c%2023%20§%2022[1939 c 23 § 22]; RRS § 6889-22; ]

== 35.82.220 - Housing bonds legal investments and security.
Notwithstanding any restrictions on investments contained in any laws of this state, the state and all public officers, municipal corporations, political subdivisions, and public bodies, all banks, bankers, trust companies, savings banks and institutions, building and loan associations, savings and loan associations, investment companies and other persons carrying on a banking business, all insurance companies, insurance associations and other persons carrying on an insurance business, and all executors, administrators, guardians, trustees and other fiduciaries may legally invest any sinking funds, moneys or other funds belonging to them or within their control in any bonds or other obligations issued by a housing authority pursuant to the housing authorities law of this state or issued by any public housing authority or agency in the United States, and such bonds and other obligations shall be authorized security for all public deposits; it being the purpose of this chapter to authorize any persons, firms, corporations, associations, political subdivisions, bodies and officers, public or private, to use any funds owned or controlled by them, including (but not limited to) sinking, insurance, investment, retirement, compensation, pension and trust funds, and funds held on deposit, for the purchase of any such bonds or other obligations: PROVIDED, HOWEVER, That nothing contained in this chapter shall be construed as relieving any person, firm or corporation from any duty of exercising reasonable care in selecting securities.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c274.pdf?cite=1977%20ex.s.%20c%20274%20§%208[1977 ex.s. c 274 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.82.220[1965 c 7 § 35.82.220]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c23.pdf?cite=1939%20c%2023%20§%2023[1939 c 23 § 23]; RRS § 6889-23; ]

== 35.82.230 - Reports.
At least once a year, an authority shall file with the clerk a report of its activities for the preceding year, and shall make recommendations with reference to such additional legislation or other action as it deems necessary in order to carry out the purposes of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.82.230[1965 c 7 § 35.82.230]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c23.pdf?cite=1939%20c%2023%20§%2024[1939 c 23 § 24]; RRS § 6889-24; ]

== 35.82.240 - Rural housing projects.
Housing authorities created for counties are specifically empowered and authorized to borrow money, accept grants and exercise their other powers to provide housing for farmers of low income as herein defined. In providing such housing, such housing authorities shall not be subject to the tenant selection limitations provided in RCW 35.82.090(3). In connection with such projects, such housing authorities may enter into such leases or purchase agreements, accept such conveyances and rent or sell dwellings forming part of such projects to or for farmers of low income, as such housing authority deems necessary in order to assure the achievement of the objectives of this chapter. Such leases, agreements or conveyances may include such covenants as the housing authority deems appropriate regarding such dwellings and the tracts of land described in any such instrument, which covenants shall be deemed to run with the land where the housing authority deems it necessary and the parties to such instrument so stipulate. Nothing contained in this section shall be construed as limiting any other powers of any housing authority.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.82.240[1965 c 7 § 35.82.240]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c69.pdf?cite=1941%20c%2069%20§%201[1941 c 69 § 1]; Rem. Supp. 1941 § 6889-23a; ]

== 35.82.250 - Housing applications by farmers.
The owner of any farm operated, or worked upon, by farmers of low income in need of safe and sanitary housing may file an application with a housing authority of a county requesting that it provide for a safe and sanitary dwelling or dwellings for occupancy by such farmers of low income. Such applications shall be received and examined by housing authorities in connection with the formulation of projects or programs to provide housing for farmers of low income.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.82.250[1965 c 7 § 35.82.250]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c69.pdf?cite=1941%20c%2069%20§%202[1941 c 69 § 2]; Rem. Supp. 1941 § 6889-23b; ]

== 35.82.260 - Farmers of low income.
"Farmers of low income" shall mean persons or families who at the time of their admission to occupancy in a dwelling of a housing authority: (1) live under unsafe or insanitary housing conditions; (2) derive their principal income from operating or working upon a farm; and (3) had an aggregate average annual net income for the three years preceding their admission that was less than the amount determined by the housing authority to be necessary, within its area of operation, to enable them, without financial assistance, to obtain decent, safe and sanitary housing without overcrowding.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.82.260[1965 c 7 § 35.82.260]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c69.pdf?cite=1941%20c%2069%20§%203[1941 c 69 § 3]; Rem. Supp. 1941 § 6889-23c; ]

== 35.82.270 - Powers are additional.
The powers conferred by RCW 35.82.240 through 35.82.270 shall be in addition and supplemental to the powers conferred by any other law, and nothing contained herein shall be construed as limiting any other powers of any housing authority.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.82.270[1965 c 7 § 35.82.270]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c69.pdf?cite=1941%20c%2069%20§%204[1941 c 69 § 4]; Rem. Supp. 1941 § 6889-23d; ]

== 35.82.280 - Supplemental projects.
Except as limited by this section, an authority shall have the same powers with respect to supplemental projects as hereinafter in this section defined as are now or hereafter granted to it under this chapter with respect to housing projects.

No funds shall be expended by an authority for a supplemental project except by resolution adopted on notice at a public hearing as provided by *chapter 42.32 RCW, supported by formal findings of fact incorporated therein, establishing that:

. Low-income housing needs within the area of operation of the authority are being or will be adequately met by existing programs; and

. A surplus of funds will exist after meeting such low-income housing needs.

Expenditures for supplemental projects shall be limited to those funds determined to be surplus.

"Supplemental project" for the purposes of this chapter shall mean any work or undertaking to provide buildings, land, equipment, facilities, and other real or personal property for recreational, group home, halfway house or other community purposes which by resolution of the housing authority is determined to be necessary for the welfare of the community within its area of operation and to fully accomplish the purposes of this chapter. Such project need not be in conjunction with the clearing of a slum area under subsection (9)(a) of RCW 35.82.020 or with the providing of low-income housing under subsection (9)(b) of RCW 35.82.020.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c300.pdf?cite=1971%20ex.s.%20c%20300%20§%202[1971 ex.s. c 300 § 2]; ]

== 35.82.285 - Group homes or halfway houses for released juveniles or developmentally disabled.
Housing authorities created under this chapter may establish and operate group homes or halfway houses to serve juveniles released from state juvenile or correctional institutions, or to serve the developmentally disabled as defined in *RCW 71A.10.020(2). Authorities may contract for the operation of facilities so established, with qualified nonprofit organizations as agent of the authority. Authorities may provide support or supportive services in facilities serving juveniles, the developmentally disabled or other persons under a disability, and the frail elderly, whether or not they are operated by the authority.

Action under this section shall be taken by the authority only after a public hearing as provided by chapter 42.30 RCW. In exercising this power the authority shall not be empowered to acquire property by eminent domain, and the facilities established shall comply with all zoning, building, fire, and health regulations and procedures applicable in the locality.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1740.SL.pdf?cite=1991%20c%20167%20§%203[1991 c 167 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c198.pdf?cite=1973%201st%20ex.s.%20c%20198%20§%202[1973 1st ex.s. c 198 § 2]; ]

== 35.82.300 - Joint housing authorities—Creation authorized—Contents of ordinances creating—Powers.
This section applies to all cities and counties.

. Joint housing authorities are hereby authorized when the legislative authorities of one or more counties and the legislative authorities of any city or cities within any of those counties or in another county or counties have authorized such joint housing authority by ordinance.

. The ordinances enacted by the legislative authorities creating the joint housing authority shall prescribe the number of commissioners, the method for their appointment and length of their terms, the election of officers, and the method for removal of commissioners.

. The ordinances enacted by the legislative authorities creating the joint housing authority shall prescribe the allocation of all costs of the joint housing authority and any other matters necessary for the operation of the joint housing authority.

. A joint housing authority shall have all the powers as prescribed by this chapter for any housing authority. The area of operation of a joint housing authority shall be the combined areas, defined by RCW 35.82.020(6), of the housing authorities created in each city and county authorizing the joint housing authority.

. The provisions of RCW 35.82.040 and 35.82.060 shall not apply to a joint housing authority created pursuant to this section.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5594.SL.pdf?cite=2002%20c%20258%20§%201[2002 c 258 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c25.pdf?cite=1980%20c%2025%20§%201[1980 c 25 § 1]; ]

== 35.82.310 - Joint housing authorities—Dissolution.
[(1)] A joint housing authority may be dissolved pursuant to substantially identical resolutions or ordinances of the legislative authority of each of the counties or cities that previously authorized that joint housing authority. These resolutions or ordinances may authorize the execution of an agreement among the counties, cities, and the joint housing authority that provides for the timing, distribution of assets, obligations and liabilities, and other matters deemed necessary or appropriate by the legislative authorities.

. Each resolution or ordinance dissolving a joint housing authority shall provide for the following:

.. Activation or reactivation of a housing authority or joint housing authority by each of the cities and counties that previously authorized the joint housing authority and any additional cities or counties that are then to be added. This activation or reactivation takes effect upon the dissolution of the joint housing authority or at an earlier time provided in the resolutions or ordinances dissolving the joint housing authority; and

.. Distribution of all assets, obligations, and liabilities of the joint housing authority to the housing authorities activated or reactivated under (a) of this subsection. Distribution of assets, obligations, and liabilities may be based on any, or a combination of any of, the following considerations:

... The population within the boundaries of each of the housing authorities activated or reactivated under (a) of this subsection;

... The number of housing units owned by the joint housing authority within the boundaries of each of the housing authorities activated or reactivated under (a) of this subsection;

... The number of low-income residents within the boundaries of each of the housing authorities activated or reactivated under (a) of this subsection;

... The effect of the proposed distribution on the viability of the housing authorities activated or reactivated under (a) of this subsection; or

.. Any other reasonable criteria to determine the distribution of assets, obligations, and liabilities.

. Each activated or reactivated housing authority shall be responsible for debt service on bonds or other obligations issued or incurred to finance the acquisition, construction, or improvement of the projects, properties, and other assets that have been distributed to them under the dissolution. However, if an outstanding bond issue is secured in whole or in part by the general revenues of the joint housing authority being dissolved, each housing authority activated or reactivated under subsection (2)(a) of this section shall remain jointly and severally liable for retirement of debt service through repayment of those outstanding bonds and other obligations of the joint housing authority until paid or defeased, from general revenues of each of the activated or reactivated housing authorities, and from any other revenues and accounts that had been expressly pledged by the joint housing authority to the payment of those bonds or other obligations. As used in this subsection, "general revenues" means all revenues of a housing authority from any source, but only to the extent that those revenues are available to pay debt service on bonds or other obligations and are not then or thereafter pledged or restricted by law, regulation, contract, covenant, resolution, deed of trust, or otherwise, solely to another particular purpose.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2418-S2.SL.pdf?cite=2006%20c%20349%20§%2012[2006 c 349 § 12]; ]

== 35.82.320 - Deactivation of housing authority—Procedure.
A housing authority created under this chapter and activated by a resolution by the governing body of a city, town, or county may be deactivated by a resolution by the city, town, or county. The findings listed in RCW 35.82.030 to activate the housing authority shall be considered prior to deactivating the housing authority. For the sole purposes of winding up the affairs of a deactivated housing authority, the governing body of the city, town, or county may exercise any power granted to a housing authority under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c275.pdf?cite=1987%20c%20275%20§%201[1987 c 275 § 1]; ]

== 35.82.325 - Deactivation of housing authority—Distribution of assets.
The assets of an authority in the process of deactivation shall be applied and distributed as follows:

. All liabilities and obligations of the authority shall be paid, satisfied, and discharged, or adequate provision shall be made therefor;

. Assets held by the authority upon condition requiring return, transfer, or conveyance, which condition occurs by reason of the deactivation shall be returned, transferred, or conveyed in accordance with such requirements;

. Assets received and held by the authority subject to limitations permitting their use only for activities purposes contained in RCW 35.82.070, but not held upon a condition requiring return, transfer, or conveyance by reason of the deactivation, shall be transferred or conveyed to the governing body of the city, town, or county and used to engage in activities contained in RCW 35.82.070;

. Other assets, if any, shall be returned to the governing body of the city, town, or county for uses allowed under state law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c275.pdf?cite=1987%20c%20275%20§%202[1987 c 275 § 2]; ]

== 35.82.330 - Chapter not applicable to certain transfers of property.
This chapter does not apply to transfers of property under *sections 1 and 2 of this act.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2759-S.SL.pdf?cite=2006%20c%2035%20§%208[2006 c 35 § 8]; ]

== 35.82.340 - Previously incarcerated individuals—Rental policies that are not unduly burdensome encouraged.
The legislature recognizes that stable, habitable, and supportive housing is a critical factor that increases a previously incarcerated individual's access to treatment and services as well as the likelihood of success in the community. Housing authorities are therefore encouraged to formulate rental policies that are not unduly burdensome to previously incarcerated individuals attempting to reenter the community, particularly when the individual's family may already reside in government subsidized housing.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6157-S.SL.pdf?cite=2007%20c%20483%20§%20603[2007 c 483 § 603]; ]

== 35.82.900 - Short title.
This chapter shall be known and may be cited as the "Housing Authorities Law."

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.82.900[1965 c 7 § 35.82.900]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c23.pdf?cite=1939%20c%2023%20§%201[1939 c 23 § 1]; ]

== 35.82.910 - Chapter controlling.
Insofar as the provisions of this chapter are inconsistent with the provisions of any other law, the provisions of this chapter shall be controlling.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.82.910[1965 c 7 § 35.82.910]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c23.pdf?cite=1939%20c%2023%20§%2026[1939 c 23 § 26]; ]

