= 35.47 - Local improvements—Procedure for cancellation of nonguaranteed bonds.
:toc:

== 35.47.010 - Distribution of moneys in local improvement funds to holders of bonds and warrants—Notice—Time limitation—Abandonment and transfer to general fund.
Any city or town having any outstanding and unpaid local improvement bonds or warrants issued in connection with a local improvement therein to which the local guaranty fund law is not applicable and that have been delinquent for more than fifteen years, by ordinance, may direct that the money, if any, remaining in a given local improvement fund for which no real property is held in trust shall be distributed by the city or town on a pro rata basis, without any reference to numerical order, to the holders of outstanding bonds or warrants for each such fund, excluding the accrued interest thereon. If the outstanding bonds or warrants are not presented for payment within one year after the last date of publication of notice provided for herein, the money being held in the local improvement fund of a city or town shall be deemed abandoned, and shall be transferred to the city or town general fund: PROVIDED, That the city or town shall publish a notice once each week for two successive weeks in the official newspaper of the city or town in which it is indicated that L.I.D. bonds for . . . . . . L.I.D. improvement Nos. . . . . to . . . . inclusive must be presented to the city or town for payment not later than one year from this date or the money being held in the local improvement fund of the city or town shall be transferred to the city or town general fund.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c469.pdf?cite=1985%20c%20469%20§%2031[1985 c 469 § 31]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c6.pdf?cite=1965%20ex.s.%20c%206%20§%201[1965 ex.s. c 6 § 1]; ]

== 35.47.020 - Declaration of obsolescence and cancellation upon distribution of moneys, untimely presentment, or lack of money in local improvement fund.
After the city or town having said bonds or warrants referred to in RCW 35.47.010 has distributed the money in a local improvement district fund in accordance with RCW 35.47.010, or such bonds or warrants are not presented for payment within one year after the last date of publication of notice provided for in RCW 35.47.010, such city or town may, by ordinance, declare such bonds and warrants, without any reference to numerical order, to be obsolete, cancel the same, and terminate all accounting thereon, and clear such bonds and warrants off their records including any unguaranteed bonds or warrants outstanding against districts in which there remains no money in the given local improvement fund.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c6.pdf?cite=1965%20ex.s.%20c%206%20§%202[1965 ex.s. c 6 § 2]; ]

== 35.47.030 - Cancellation procedure where no money in local improvement fund.
If the bonds or warrants outstanding against a district are unguaranteed and if there remains no money in the appropriate local improvement fund to pay them, and if no real property is held in trust for the fund, the city or town shall give notice in the same manner as provided in RCW 35.47.010, stating that L.I.D. . . . . . . (bonds or warrants) for . . . . . . L.I.D. improvement Nos. . . . . to . . . . inclusive will be canceled as provided in RCW 35.47.020, unless such bonds or warrants are presented to the city or town within one year from the date of last publication of the notice, together with good cause shown as to why such cancellation should not take place. If such bonds or warrants are not presented, with good cause shown, within one year after the last date of publication of such notice, they may be canceled as provided in RCW 35.47.020.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c6.pdf?cite=1965%20ex.s.%20c%206%20§%203[1965 ex.s. c 6 § 3]; ]

== 35.47.040 - Action under RCW  35.47.010 through  35.47.030 unaffected by chapter  35.48 RCW or other law.
Nothing in chapter 35.48 RCW or other existing law to the contrary shall preclude the action authorized herein.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c6.pdf?cite=1965%20ex.s.%20c%206%20§%204[1965 ex.s. c 6 § 4]; ]

