= 35.17 - Commission form of government.
:toc:

== 35.17.010 - Definition of commission form.
The commission form of city government means a city government in which the legislative powers and duties are exercised by a commission of three, consisting of a mayor, a commissioner of finance and accounting, and a commissioner of streets and public improvements, and in which the executive and administrative powers and duties are distributed among the three departments as follows:

. Department of public safety of which the mayor shall be the superintendent;

. Department of finance and accounting of which the commissioner of finance and accounting shall be the superintendent;

. Department of streets and public improvements of which the commissioner of streets and public improvement shall be the superintendent.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.010[1965 c 7 § 35.17.010]; 1911 c 116 § 11, part; RRS § 9100, part.  1943 c 25 § 3, part; 1911 c 116 § 12, part; Rem. Supp. 1943 § 9101, part; ]

== 35.17.020 - Elections—Terms of commissioners—Vacancies.
. All regular elections in cities organized under the statutory commission form of government shall be held quadrennially in the odd-numbered years on the dates provided in RCW 29A.04.330. However, after commissioners are elected at the next general election occurring in 1995 or 1997, regular elections in cities organized under a statutory commission form of government shall be held biennially at municipal general elections.

. The commissioners shall be nominated and elected at large. Their terms shall be for four years and until their successors are elected and qualified and assume office in accordance with RCW 29A.60.280. However, at the next regular election of a city organized under a statutory commission form of government, the terms of office of commissioners shall occur with the person who is elected as a commissioner receiving the least number of votes being elected to a two-year term of office and the other two persons who are elected being elected to four-year terms of office. Thereafter, commissioners shall be elected to four-year terms of office.

. Vacancies on a commission shall occur and shall be filled as provided in chapter 42.12 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=2013%20c%2011%20§%2087[2013 c 11 § 87]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2278-S.SL.pdf?cite=1994%20c%20223%20§%2010[1994 c 223 § 10]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2369.SL.pdf?cite=1994%20c%20119%20§%201[1994 c 119 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c126.pdf?cite=1979%20ex.s.%20c%20126%20§%2017[1979 ex.s. c 126 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.020[1965 c 7 § 35.17.020]; prior:  1963 c 200 § 12; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c86.pdf?cite=1959%20c%2086%20§%202[1959 c 86 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c55.pdf?cite=1955%20c%2055%20§%209[1955 c 55 § 9]; prior:   1911 c 116 § 5; RRS § 9094.  1943 c 25 § 1, part; 1911 c 116 § 3, part; Rem. Supp. 1943 § 9092, part; ]

== 35.17.030 - Laws applicable.
Cities organized under the commission form have all the powers of cities of the second class and shall be governed by the statutes applicable to cities of that class to the extent to which they are appropriate and not in conflict with provisions specifically applicable to cities organized under the commission form.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.030[1965 c 7 § 35.17.030]; 1911 c 116 § 11, part; RRS § 9100, part.  1911 c 116 § 4, part; RRS § 9093, part; ]

== 35.17.035 - Second-class cities, parking meter revenue for revenue bonds.
See RCW 35.23.454.

[ ]

== 35.17.040 - Offices.
The commission shall have and maintain an office at the city hall, or such other place as the city may provide.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.040[1965 c 7 § 35.17.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c309.pdf?cite=1955%20c%20309%20§%203[1955 c 309 § 3]; prior: 1943 c 25 § 4, part; 1911 c 116 § 14, part; Rem. Supp. 1943 § 9103, part; ]

== 35.17.050 - Meetings.
Regular meetings of the commission shall be held on the second Monday after the election of the commissioners and thereafter at least once each week on a day to be fixed by ordinance. Special meetings may be called by the mayor or two commissioners. All meetings of the commission shall be open to the public.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.050[1965 c 7 § 35.17.050]; 1911 c 116 § 15, part; RRS § 9104, part; ]

== 35.17.060 - President.
The mayor shall be president of the commission. He or she shall preside at its meetings when present and shall oversee all departments and recommend to the commission, action on all matters requiring attention in any department.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202014[2009 c 549 § 2014]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.060[1965 c 7 § 35.17.060]; 1911 c 116 § 15, part; RRS § 9104, part; ]

== 35.17.070 - Vice president.
The commissioner of finance and accounting shall be vice president of the commission. In the absence or inability of the mayor, he or she shall perform the duties of president.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202015[2009 c 549 § 2015]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.070[1965 c 7 § 35.17.070]; 1911 c 116 § 15, part; RRS § 9104, part; ]

== 35.17.080 - Employees of commission.
The commission shall appoint by a majority vote a city clerk and such other officers and employees as the commission may by ordinance provide. Any officer or employee appointed by the commission may be discharged at any time by vote of a majority of the members of the commission. Any commissioner may perform any duties pertaining to his or her department but without additional compensation therefor.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202016[2009 c 549 § 2016]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.080[1965 c 7 § 35.17.080]; 1943 c 25 § 3, part; 1911 c 116 § 12, part; Rem. Supp. 1943 § 9101, part; ]

== 35.17.090 - Distribution of powers—Assignment of duties.
The commission by ordinance shall determine what powers and duties are to be performed in each department, shall prescribe the powers and duties of the various officers and employees and make such rules and regulations for the efficient and economical conduct of the business of the city as it may deem necessary and proper. The commission may assign particular officers and employees to one or more departments and may require an officer or employee to perform duties in two or more departments.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.090[1965 c 7 § 35.17.090]; 1911 c 116 § 11, part; RRS § 9100, part; ]

== 35.17.100 - Bonds of commissioners and employees.
Every member of the city commission, before qualifying, shall give a good and sufficient bond to the city in a sum equivalent to five times the amount of his or her annual salary, conditioned for the faithful performance of the duties of his or her office. The bonds must be approved by a judge of the superior court for the county in which the city is located and filed with the clerk thereof. The commission, by resolution, may require any of its appointees to give bond to be fixed and approved by the commission and filed with the mayor.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5063.SL.pdf?cite=2007%20c%20218%20§%2065[2007 c 218 § 65]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.100[1965 c 7 § 35.17.100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c116.pdf?cite=1911%20c%20116%20§%206[1911 c 116 § 6]; RRS § 9095; ]

== 35.17.105 - Clerk may take acknowledgments.
The clerk or deputy clerk of any city having a commission form of government shall, without charge, take acknowledgments and administer oaths required by law on all claims and demands against the city.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.105[1965 c 7 § 35.17.105]; ]

== 35.17.108 - Salaries of mayor and commissioners.
The annual salaries of the mayor and the commissioners of any city operating under a commission form of government shall be as fixed by charter or ordinance of said city. The power and authority conferred by this section shall be construed as in addition and supplemental to powers or authority conferred by any other law, and nothing contained herein shall be construed as limiting any other powers or authority of any such city.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c100.pdf?cite=1967%20c%20100%20§%201[1967 c 100 § 1]; ]

== 35.17.120 - Officers and employees—Salaries and wages.
All appointive officers and employees shall receive such compensation as the commission shall fix by ordinance, payable monthly or at such shorter periods as the commission may determine.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.120[1965 c 7 § 35.17.120]; 1943 c 25 § 4, part; 1911 c 116 § 14, part; Rem. Supp. 1943 § 9103, part; ]

== 35.17.130 - Officers and employees—Creation—Removal—Changes in compensation.
The commission shall have power from time to time to create, fill and discontinue offices and employments other than those herein prescribed, according to their judgment of the needs of the city; and may, by majority vote of all the members, remove any such officer or employees, except as otherwise provided for in this chapter; and may by resolution, or otherwise, prescribe, limit or change the compensation of such officers or employees.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.130[1965 c 7 § 35.17.130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c116.pdf?cite=1911%20c%20116%20§%2013[1911 c 116 § 13]; RRS § 9102; ]

== 35.17.150 - Officers and employees—Passes, free services prohibited, exceptions—Penalty.
No officer or employee, elected or appointed, shall receive from any enterprise operating under a public franchise any frank, free ticket, or free service or receive any service upon terms more favorable than are granted to the public generally: PROVIDED, That the provisions of this section shall not apply to free transportation furnished to police officers and firefighters in uniform nor to free service to city officials provided for in the franchise itself.

Any violation of the provisions of this section shall be a misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202017[2009 c 549 § 2017]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.150[1965 c 7 § 35.17.150]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c268.pdf?cite=1961%20c%20268%20§%2011[1961 c 268 § 11]; prior: 1911 c 116 § 17, part; RRS § 9106, part; ]

== 35.17.170 - Financial statements—Monthly—Annual.
The commission shall each month print in pamphlet form a detailed itemized statement of all receipts and expenses of the city and a summary of its proceedings during the preceding month and furnish copies thereof to the state library, the city library, the newspapers of the city, and to persons who apply therefor at the office of the city clerk. At the end of each year the commission shall cause a complete examination of all the books and accounts of the city to be made by competent accountants and shall publish the result of such examination to be made in the manner above provided for publication of statements of monthly expenditures.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.170[1965 c 7 § 35.17.170]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c116.pdf?cite=1911%20c%20116%20§%2018[1911 c 116 § 18]; RRS § 9107; ]

== 35.17.180 - Legislative power—How exercised.
Each member of the commission shall have the right to vote on all questions coming before the commission. Two members of the commission shall constitute a quorum and the affirmative vote of at least two members shall be necessary to adopt any motion, resolution, ordinance, or course of action.

Every measure shall be reduced to writing and read before the vote is taken and upon every vote the yeas and nays shall be called and recorded.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.180[1965 c 7 § 35.17.180]; 1911 c 116 § 10, part; RRS § 9099, part; ]

== 35.17.190 - Legislative ordinances and resolutions.
Every resolution and ordinance adopted by the commission shall be signed by the mayor or by two members of the commission and filed and recorded within five days of its passage. The mayor shall have no veto power.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.190[1965 c 7 § 35.17.190]; 1911 c 116 § 10, part; RRS § 9099, part; ]

== 35.17.200 - Legislative—Appropriations of money.
No money shall be appropriated except by ordinance and every such ordinance complete in the form in which it is finally passed shall remain on file with the city clerk for public inspection at least one week before final passage.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.200[1965 c 7 § 35.17.200]; 1911 c 116 § 16, part; RRS § 9105, part; ]

== 35.17.210 - Legislative—Street improvements.
Every ordinance or resolution ordering any street improvement or sewer complete in the form in which it is finally passed shall remain on file with the city clerk for public inspection at least one week before final passage.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.210[1965 c 7 § 35.17.210]; 1911 c 116 § 16, part; RRS § 9105, part; ]

== 35.17.220 - Legislative—Franchises—Referendum.
No franchise or right to occupy or use the streets, highways, bridges or other public places shall be granted, renewed, or extended except by ordinance and every such ordinance complete in the form in which it is finally passed shall remain on file with the city clerk for at least one week before final passage and if the franchise or grant is for interurban or street railways, gas or waterworks, electric light or power plants, heating plants, telegraph or telephone systems or other public service utilities, the ordinance must be submitted to a vote of the people at a general or special election and approved by a majority of those voting thereon.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.220[1965 c 7 § 35.17.220]; 1911 c 116 § 16, part; RRS § 9105, part; ]

== 35.17.230 - Legislative—Ordinances—Time of going into effect.
Ordinances shall not go into effect before thirty days from the time of final passage and are subject to referendum during the interim except:

. Ordinances initiated by petition;

. Ordinances necessary for immediate preservation of public peace, health, and safety which contain a statement of urgency and are passed by unanimous vote of all the commissioners;

. Ordinances providing for local improvement districts.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.230[1965 c 7 § 35.17.230]; 1911 c 116 § 22, part; RRS § 9111, part.  1911 c 116 § 21, part; RRS § 9110, part; ]

== 35.17.240 - Legislative—Referendum—Filing suspends ordinance.
Upon the filing of a referendum petition praying therefor, the commission shall reconsider an ordinance subject to referendum and upon reconsideration shall defeat it in its entirety or shall submit it to a vote of the people. The operation of an ordinance so protested against shall be suspended until the referendum petition is finally found insufficient or until the ordinance protested against has received a majority of the votes cast thereon at the election.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.240[1965 c 7 § 35.17.240]; 1911 c 116 § 22, part; RRS § 9111, part; ]

== 35.17.250 - Legislative—Referendum—Petitions and conduct of elections.
All provisions applicable to the character, form, and number of signatures required for an initiative petition, to the examination and certification thereof, and to the submission to the vote of the people of the ordinance proposed thereby, shall apply to a referendum petition and to the ordinance sought to be defeated thereby.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.250[1965 c 7 § 35.17.250]; 1911 c 116 § 22, part; RRS § 9111, part; ]

== 35.17.260 - Legislative—Ordinances by initiative petition.
Ordinances may be initiated by petition of registered voters of the city filed with the commission. If the petition accompanying the proposed ordinance is signed by the registered voters in the city equal in number to twenty-five percent of the votes cast for all candidates for mayor at the last preceding city election, and if it contains a request that, unless passed by the commission, the ordinance be submitted to a vote of the registered voters of the city, the commission shall either:

. Pass the proposed ordinance without alteration within twenty days after the county auditor's certificate of sufficiency has been received by the commission; or

. Immediately after the county auditor's certificate of sufficiency for the petition is received, cause to be called a special election to be held on the next election date, as provided in RCW 29A.04.330, provided that the resolution deadline for that election has not passed, for submission of the proposed ordinance without alteration, to a vote of the people unless a general election will occur within ninety days, in which event submission must be made on the general election ballot.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1919-S.SL.pdf?cite=2015%20c%20146%20§%205[2015 c 146 § 5]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1806-S.SL.pdf?cite=2015%20c%2053%20§%2029[2015 c 53 § 29]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2140-S.SL.pdf?cite=1996%20c%20286%20§%204[1996 c 286 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.260[1965 c 7 § 35.17.260]; 1911 c 116 § 21, part; RRS § 9110, part; ]

== 35.17.270 - Legislative—Initiative petition—Submission procedures.
The petitioner preparing an initiative petition for submission to the commission shall follow the procedures established in RCW 35.21.005.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2140-S.SL.pdf?cite=1996%20c%20286%20§%205[1996 c 286 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.270[1965 c 7 § 35.17.270]; 1911 c 116 § 21, part; RRS § 9110, part.  1911 c 116 § 20, part; RRS § 9109, part. (iii)  1911 c 116 § 24; RRS § 9113; ]

== 35.17.280 - Legislative—Initiative petition—Checking by clerk.
Within ten days from the filing of a petition submitting a proposed ordinance the city clerk shall ascertain and append to the petition his or her certificate stating whether or not it is signed by a sufficient number of registered voters, using the registration records and returns of the preceding municipal election for his or her sources of information, and the commission shall allow him or her extra help for that purpose, if necessary. If the signatures are found by the clerk to be insufficient the petition may be amended in that respect within ten days from the date of the certificate. Within ten days after submission of the amended petition the clerk shall make an examination thereof and append his or her certificate thereto in the same manner as before. If the second certificate shall also show the number of signatures to be insufficient, the petition shall be returned to the person filing it.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202018[2009 c 549 § 2018]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.280[1965 c 7 § 35.17.280]; 1911 c 116 § 20, part; RRS § 9109, part.  1911 c 116 § 21, part; RRS § 9110, part; ]

== 35.17.290 - Legislative—Initiative petition—Appeal to court.
If the clerk finds the petition insufficient or if the commission refuses either to pass an initiative ordinance or order an election thereon, any taxpayer may commence an action in the superior court against the city and procure a decree ordering an election to be held in the city for the purpose of voting upon the proposed ordinance if the court finds the petition to be sufficient.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.290[1965 c 7 § 35.17.290]; 1911 c 116 § 20, part; RRS § 9109, part.  1911 c 116 § 21, part; RRS § 9110, part; ]

== 35.17.300 - Legislative—Initiative—Conduct of election.
Publication of notice, the election, the canvass of the returns and declaration of the results, shall be conducted in all respects as are other city elections. Any number of proposed ordinances may be voted on at the same election, but there shall not be more than one special election for that purpose during any one six-month period.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.300[1965 c 7 § 35.17.300]; 1911 c 116 § 20, part; RRS § 9109, part.  1911 c 116 § 21, part; RRS § 9110, part; ]

== 35.17.310 - Legislative—Initiative—Notice of election.
The city clerk shall cause any ordinance or proposition required to be submitted to the voters at an election to be published once in each of the daily newspapers in the city not less than five nor more than twenty days before the election, or if no daily newspaper is published in the city, publication shall be made in each of the weekly newspapers published therein. This publication shall be in addition to the notice required in RCW 29A.52.355.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1806-S.SL.pdf?cite=2015%20c%2053%20§%2030[2015 c 53 § 30]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.310[1965 c 7 § 35.17.310]; 1911 c 116 § 21, part; RRS § 9110, part; ]

== 35.17.330 - Legislative—Initiative—Effective date—Record.
If the number of votes cast thereon favor the proposed ordinance, it shall become effective immediately and shall be made a part of the record of ordinances of the city.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.330[1965 c 7 § 35.17.330]; 1911 c 116 § 21, part; RRS § 9110, part; ]

== 35.17.340 - Legislative—Initiative—Repeal or amendment.
Upon the adoption of an ordinance initiated by petition, the city clerk shall write on the margin of the record thereof "ordinance by petition No. . . . .," or "ordinance by vote of the people," and it cannot be repealed or amended except by a vote of the people.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.340[1965 c 7 § 35.17.340]; 1911 c 116 § 21, part; RRS § 9110, part; ]

== 35.17.350 - Legislative—Initiative—Repeal or amendment—Method.
The commission may by means of an ordinance submit a proposition for the repeal or amendment of an ordinance, initiated by petition, by submitting it to a vote of the people at any general election and if a majority of the votes cast upon the proposition favor it, the ordinance shall be repealed or amended accordingly.

A proposition of repeal or amendment must be published before the election thereon as is an ordinance initiated by petition when submitted to election.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.350[1965 c 7 § 35.17.350]; 1911 c 116 § 21, part; RRS § 9110, part; ]

== 35.17.360 - Legislative—Initiative—Repeal or amendment—Record.
Upon the adoption of a proposition to repeal or amend an ordinance initiated by petition, the city clerk shall write upon the margin of the record of the ordinance "repealed (or amended) by ordinance No. . . . .," or "repealed (or amended) by vote of the people."

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.360[1965 c 7 § 35.17.360]; 1911 c 116 § 21, part; RRS § 9110, part; ]

== 35.17.370 - Organization on commission form—Eligibility—Census.
Any city having a population of two thousand and less than thirty thousand may organize as a city under the commission form of government. The requisite population shall be determined by the last preceding state or federal census or the council may cause a census to be taken by one or more suitable persons, in which the full name of each person in the city shall be plainly written, the names alphabetically arranged and regularly numbered in a complete series, verified before an officer authorized to administer oaths and filed with the city clerk.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.370[1965 c 7 § 35.17.370]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1927c210.pdf?cite=1927%20c%20210%20§%201[1927 c 210 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c116.pdf?cite=1911%20c%20116%20§%201[1911 c 116 § 1]; RRS § 9090; ]

== 35.17.380 - Organization—Petition.
Upon petition of electors in any city equal in number to twenty-five percent of the votes cast for all candidates for mayor at the last preceding city election therein, the mayor by proclamation shall cause to be submitted the question of organizing the city under the commission form of government at a special election at a time specified therein and within sixty days after the filing of the petition. If the plan is not adopted at the special election called, it shall not be resubmitted to the voters of the city for adoption within two years thereafter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.380[1965 c 7 § 35.17.380]; 1911 c 116 § 2, part; RRS § 9091, part; ]

== 35.17.390 - Organization—Ballots.
The proposition on the ballot shall be: "Shall the proposition to organize the city of (name of city) under the commission form of government be adopted?" followed by the words: "For organization as a city under commission form" and "against organization as a city under commission form." The election shall be conducted, the vote canvassed, and the result declared in the same manner as provided by law in respect to other city elections. If a majority of the votes cast are in favor thereof the city shall proceed to elect a mayor and two commissioners.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.390[1965 c 7 § 35.17.390]; 1911 c 116 § 2, part; RRS § 9091, part; ]

== 35.17.400 - Organization—Election of officers—Term.
The first election of commissioners shall be held at the next special election that occurs at least sixty days after the election results are certified where the proposition to organize under the commission form was approved by city voters, and the commission first elected shall commence to serve as soon as they have been elected and have qualified and shall continue to serve until their successors have been elected and qualified and have assumed office in accordance with RCW 29A.60.280. The date of the second election for commissioners shall be in accordance with RCW 29A.04.330 such that the term of the first commissioners will be as near as possible to, but not in excess of, four years calculated from the first day in January in the year after the year in which the first commissioners were elected.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1806-S.SL.pdf?cite=2015%20c%2053%20§%2031[2015 c 53 § 31]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2278-S.SL.pdf?cite=1994%20c%20223%20§%2011[1994 c 223 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c126.pdf?cite=1979%20ex.s.%20c%20126%20§%2018[1979 ex.s. c 126 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.400[1965 c 7 § 35.17.400]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c200.pdf?cite=1963%20c%20200%20§%2013[1963 c 200 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c55.pdf?cite=1955%20c%2055%20§%2010[1955 c 55 § 10]; prior: 1943 c 25 § 1, part; 1911 c 116 § 3, part; Rem. Supp. 1943 § 9092, part; ]

== 35.17.410 - Organization—Effect on ordinances—Boundaries—Property.
All bylaws, ordinances and resolutions in force when a city organizes under the commission form shall remain in force until amended or repealed.

The boundaries of a city reorganized under the commission form shall not be changed thereby.

All rights and property vested in the city before reorganization under the commission form shall vest in the city as reorganized and no right or liability either in favor of or against it, existing at the time and no suit or prosecution shall be affected by the change.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.410[1965 c 7 § 35.17.410]; 1911 c 116 § 4, part; RRS § 9093, part; ]

== 35.17.420 - Organization—Revision of appropriations.
If, at the beginning of the term of office of the first commission elected in a city organized under the commission form, the appropriations for the expenditures of the city for the current fiscal year have been made, the commission, by ordinance, may revise them.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.420[1965 c 7 § 35.17.420]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c116.pdf?cite=1911%20c%20116%20§%2019[1911 c 116 § 19]; RRS § 9108; ]

== 35.17.430 - Abandonment of commission form.
Any city which has operated under the commission form for more than six years may again reorganize as a noncommission city without changing its classification unless it desires to do so.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c47.pdf?cite=1965%20ex.s.%20c%2047%20§%203[1965 ex.s. c 47 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.430[1965 c 7 § 35.17.430]; 1911 c 116 § 23, part; RRS § 9112, part; ]

== 35.17.440 - Abandonment—Method.
Upon the filing of a petition praying therefor, signed by not less than twenty-five percent of the registered voters resident in the city, a special election shall be called at which the following proposition only shall be submitted: "Shall the city of (name of city) abandon its organization as a city under the commission form and become a city under the general laws governing cities of like population?"

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.440[1965 c 7 § 35.17.440]; 1911 c 116 § 23, part; RRS § 9112, part; ]

== 35.17.450 - Abandonment—Conduct of election—Canvass.
The sufficiency of the petition for the abandonment of the commission form of city government shall be determined, the election ordered and conducted, the returns canvassed and the results declared as required by the provisions applicable to the proceedings for the enactment of an ordinance by initiative petition to the extent to which they are appropriate.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.450[1965 c 7 § 35.17.450]; 1911 c 116 § 23, part; RRS § 9112, part; ]

== 35.17.460 - Abandonment—Effect.
If a majority of the votes cast upon the proposition of abandoning the commission form of city government favor the proposition, the city shall be reorganized under general laws immediately upon the first election of city officers, which shall be held on the date of the next general city election of cities of its class. The change in form of government shall not affect the property, rights, or liabilities of the city.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.17.460[1965 c 7 § 35.17.460]; 1911 c 116 § 23, part; RRS § 9112, part; ]

