= 35.31 - Accident claims and funds.
:toc:

== 35.31.020 - Charter cities—Manner of filing.
The provisions of chapter 35.31 RCW shall be applied notwithstanding any provisions to the contrary in any charter of any city permitted by law to have a charter; however, charter provisions not inconsistent herewith shall continue to apply. All claims for damages against a charter city shall be filed in the manner set forth in chapter 4.96 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1218.SL.pdf?cite=1993%20c%20449%20§%207[1993 c 449 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c164.pdf?cite=1967%20c%20164%20§%2012[1967 c 164 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.31.020[1965 c 7 § 35.31.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c224.pdf?cite=1957%20c%20224%20§%203[1957 c 224 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c96.pdf?cite=1917%20c%2096%20§%201[1917 c 96 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c148.pdf?cite=1915%20c%20148%20§%201[1915 c 148 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c83.pdf?cite=1909%20c%2083%20§%202[1909 c 83 § 2]; RRS § 9479; ]

== 35.31.040 - Noncharter cities and towns—Manner of filing—Report.
All claims for damages against noncharter cities and towns shall be filed in the manner set forth in chapter 4.96 RCW.

No ordinance or resolution shall be passed allowing such claim or any part thereof, or appropriating any money or other property to pay or satisfy the same or any part thereof, until the claim has first been referred to the proper department or committee, nor until such department or committee has made its report to the council thereon pursuant to such reference.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1218.SL.pdf?cite=1993%20c%20449%20§%208[1993 c 449 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c74.pdf?cite=1989%20c%2074%20§%201[1989 c 74 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c164.pdf?cite=1967%20c%20164%20§%2013[1967 c 164 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.31.040[1965 c 7 § 35.31.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c224.pdf?cite=1957%20c%20224%20§%204[1957 c 224 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c148.pdf?cite=1915%20c%20148%20§%202[1915 c 148 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c167.pdf?cite=1909%20c%20167%20§%201[1909 c 167 § 1]; RRS § 9481; ]

== 35.31.050 - Accident fund—Warrants for judgments.
Every city of the second class and town may create an accident fund upon which the clerk shall draw warrants for the full amount of any judgment including interest and costs against the city or town on account of personal injuries suffered by any person as shown by a transcript of the judgment duly certified to the clerk. The warrants shall be issued in denominations not less than one hundred dollars nor more than five hundred dollars; they shall draw interest at the rate of six percent per annum, shall be numbered consecutively and be paid in the order of their issue.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2055[1994 c 81 § 55]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.31.050[1965 c 7 § 35.31.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c128.pdf?cite=1909%20c%20128%20§%201[1909 c 128 § 1]; RRS § 9482.   1909 c 128 § 2; RRS § 9483. (iii)  1909 c 128 § 5; RRS § 9486; ]

== 35.31.060 - Tax levy for fund.
The city or town council after the drawing of warrants against the accident fund shall estimate the amount necessary to pay the warrants with accrued interest thereon, and shall levy a tax sufficient to pay that amount not exceeding seventy-five cents per thousand dollars of assessed value. If a single levy of seventy-five cents per thousand dollars of assessed value is not sufficient, an annual levy of seventy-five cents per thousand dollars of assessed value shall be made until the warrants and interest are fully paid.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c195.pdf?cite=1973%201st%20ex.s.%20c%20195%20§%2019[1973 1st ex.s. c 195 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.31.060[1965 c 7 § 35.31.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c128.pdf?cite=1909%20c%20128%20§%203[1909 c 128 § 3]; RRS § 9484; ]

== 35.31.070 - Surplus to current expense fund.
If there is no judgment outstanding against the city or town for personal injuries the money remaining in the accident fund after the payment of the warrants drawn on that fund and interest in full shall be transferred to the current expense fund.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.31.070[1965 c 7 § 35.31.070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c128.pdf?cite=1909%20c%20128%20§%204[1909 c 128 § 4]; RRS § 9485; ]

