= 35.64 - Zoos and aquariums.
:toc:

== 35.64.010 - Contracts for management and operation—Terms—Public hearing.
. If the legislative authority of a city with a population over one hundred fifty thousand that is not in a metropolitan park district contracts with one or more nonprofit corporations or other public organizations for the overall management and operation of a zoo, an aquarium, or both, that contract shall be subject to this section. No such contract for the overall management and operation of zoo or aquarium facilities by a nonprofit corporation or other public organization shall have an initial term or any renewal term longer than twenty years, but may be renewed by the legislative authority of the city upon the expiration of an initial term or any renewal term.

. Before approving each initial and any renewal contract with a nonprofit corporation or other public organization for the overall management and operation of any facilities, the city legislative authority shall hold a public hearing on the proposed management and operation by the nonprofit corporation or other public organization. At least thirty days prior to the hearing, a public notice setting forth the date, time, and place of the hearing must be published at least once in a local newspaper of general circulation. Notice of the hearing shall also be mailed or otherwise delivered to all who would be entitled to notice of a special meeting of the city legislative authority under RCW 42.30.080. The notice shall identify the facilities involved and the nonprofit corporation or other public organization proposed for management and operation under the contract with the city. The terms and conditions under which the city proposes to contract with the nonprofit corporation or other public organization for management and operation shall be available upon request from and after the date of publication of the hearing notice and at the hearing, but after the public hearing the city legislative authority may amend the proposed terms and conditions at open public meetings.

. As part of the management and operation contract, the legislative authority of the city may authorize the managing and operating entity to grant to any nonprofit corporation or public or private organization franchises or concessions that further the public use and enjoyment of the zoo or aquarium, as the case may be, and may authorize the managing and operating entity to contract with any public or private organization for any specific services as are routinely so procured by the city.

. Notwithstanding any provision in the charter of the city so contracting for the overall management and operation of a zoo or an aquarium, or any other provision of law, the nonprofit corporation or other public organization with responsibility for overall management or operation of any such facilities pursuant to a contract under this section may, in carrying out that responsibility under such contract, manage, supervise, and control those employees of the city employed in connection with the zoo or aquarium and may hire, fire, and otherwise discipline those employees. Notwithstanding any provision in the charter of the city so contracting for the overall management and operation of a zoo or an aquarium, or any other provision of law, the civil service system of any such city shall provide for the nonprofit corporation or other public organization to manage, supervise, control, hire, fire, and otherwise discipline those employees of the city employed in connection with the zoo or aquarium.

. As part of the management and operation contract, the legislative authority of the city shall provide for oversight of the managing and operating entity to ensure public accountability of the entity and its performance in a manner consistent with the contract.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6858.SL.pdf?cite=2000%20c%20206%20§%201[2000 c 206 § 1]; ]

== 35.64.020 - Construction—Collective bargaining agreement not affected.
Nothing in this chapter shall be construed to affect any terms, conditions, or practices contained in a collective bargaining agreement in effect on June 8, 2000.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6858.SL.pdf?cite=2000%20c%20206%20§%202[2000 c 206 § 2]; ]

