= 35.69 - Sidewalks—Construction, reconstruction in first and second-class cities.
:toc:

== 35.69.010 - Definitions.
The term "street" as used herein includes boulevard, avenue, street, alley, way, lane, square or place.

The term "city" includes any city of the first or second class or any other city of equal population working under a special charter.

The term "sidewalk" includes any and all pedestrian structures or forms of improvement for pedestrians included in the space between the street margin, as defined by a curb or the edge of the traveled road surface, and the line where the public right-of-way meets the abutting property.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6093-S.SL.pdf?cite=1996%20c%2019%20§%202[1996 c 19 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2061[1994 c 81 § 61]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.69.010[1965 c 7 § 35.69.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1927c203.pdf?cite=1927%20c%20203%20§%201[1927 c 203 § 1]; RRS § 9332-1; ]

== 35.69.020 - Resolution of necessity—Liability of abutting property—Reconstruction.
. Whenever a portion, not longer than one block in length, of any street in any city is not improved by the construction of a sidewalk thereon, or the sidewalk thereon has become unfit or unsafe for purposes of public travel, and such street adjacent to both ends of said portion is so improved and in good repair, and the city council of such city by resolution finds that the improvement of such portion of such street by the construction or reconstruction of a sidewalk thereon is necessary for the public safety and convenience, the duty, burden, and expense of constructing or reconstructing such sidewalk shall devolve upon the property directly abutting upon such portion except as provided in subsections (2) and (3) of this section.

. An abutting property shall not be charged with any costs of construction or reconstruction under this chapter, or under chapter 35.68 or 35.70 RCW, in excess of fifty percent of the valuation of such abutting property, exclusive of improvements thereon, according to the valuation last placed upon it for purposes of general taxation.

. An abutting property shall not be charged with any costs of reconstruction under this chapter, or under chapter 35.68 or 35.70 RCW, if the reconstruction is required to correct deterioration of or damage to the sidewalk that is the direct result of actions by the city or its agents or to correct deterioration of or damage to the sidewalk that is the direct result of the failure of the city to enforce its ordinances. 

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6093-S.SL.pdf?cite=1996%20c%2019%20§%203[1996 c 19 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.69.020[1965 c 7 § 35.69.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1927c203.pdf?cite=1927%20c%20203%20§%202[1927 c 203 § 2]; RRS § 9332-2; ]

== 35.69.030 - Notice to owners—Service—Contents—Assessment—Collection.
Whenever the city council of any such city has adopted such resolution it shall cause a notice to be served on the owner of the property directly abutting on such portion of such street, instructing him or her to construct or reconstruct a sidewalk on such portion in accordance with the plans and specifications which shall be attached to such notice. The notice shall be deemed sufficiently served if delivered in person to the owner or if left at the home of such owner with a person of suitable age and discretion then resident therein, or with an agent of such owner, authorized to collect rentals on such property, or, if the owner is a nonresident of the state of Washington, by mailing a copy to his or her last known address, or if he or she is unknown or if his or her address is unknown, then by posting a copy in a conspicuous place at such portion of the street where the improvement is to be made. The notice shall specify a reasonable time within which such construction or reconstruction shall be made, and shall state that in case the owner fails to make the same within such time, the city will proceed to make it through the officer or department thereof charged with the inspection of sidewalks and that such officer or department will report to the city council, at a subsequent date, to be definitely stated in the notice, an assessment roll showing the lot or parcel of land directly abutting on such portion of the street so improved, the cost of the improvement, and the name of the owner, if known, and that the city council at the time stated in the notice or at the time or times to which the same may be adjourned, will hear any and all protests against the proposed assessment. Upon the expiration of the time fixed within which the owner is required to construct or reconstruct such sidewalk, if the owner has failed to perform such work, the city may proceed to perform it, and the officer or department of the city performing the work shall, within the time fixed in the notice, report to the city council an assessment roll showing the lot or parcel of land directly abutting on that portion of the street so improved, the cost of the work, and the name of the owner, if known. The city council shall, at the time in such notice designated, or at an adjourned time or times, assess the cost of such improvement against said property and shall fix the time and manner for payment thereof, which said assessment shall become a lien upon said property and shall be collected in the manner as is provided by law for collection of local improvements assessments under this title.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202118[2009 c 549 § 2118]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.69.030[1965 c 7 § 35.69.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1927c203.pdf?cite=1927%20c%20203%20§%203[1927 c 203 § 3]; RRS § 9332-3; ]

== 35.69.040 - Abutting property defined.
For the purposes of this chapter all property having a frontage upon the sides or margins of any street shall be deemed to be abutting property, and such property shall be chargeable, as provided herein, for all costs of construction or reconstruction or any form of sidewalk improvement between the margin of said street and the roadway lying in front of and adjacent to said property.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.69.040[1965 c 7 § 35.69.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1927c203.pdf?cite=1927%20c%20203%20§%204[1927 c 203 § 4]; RRS § 9332-4; ]

== 35.69.050 - Construction of chapter.
Nothing in this chapter shall be construed to limit or repeal any existing powers of cities with reference to the construction or reconstruction of sidewalks or the improvement or maintenance of streets, but the power and authority herein granted is to be exercised concurrent with or in extension of powers and authority now existing. The legislative authority of any city before exercising the powers and authority herein granted shall, by proper ordinance, provide for the application and enforcement of the same within the limitations herein specified.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.69.050[1965 c 7 § 35.69.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1927c203.pdf?cite=1927%20c%20203%20§%205[1927 c 203 § 5]; RRS § 9332-5; ]

