= 35.71 - Pedestrian malls.
:toc:

== 35.71.010 - Definitions.
As used in this chapter, the following terms shall have the meaning herein given to each of them:

"City" means any city or town.

"Chief executive" means the mayor in a mayor-council or commission city and city manager in a council-manager city.

"Corporate authority" means the legislative body of any city.

"Project" means a pedestrian mall project.

"Right-of-way" means that area of land dedicated for public use or secured by the public for purposes of ingress and egress to abutting property and other public purposes.

"Mall" means an area of land, part of which may be surfaced, landscaped, and used entirely for pedestrian movements, except with respect to governmental functions, utilities, and loading and unloading of goods.

"Mall organization" means a group of property owners, lessors, or lessees in an area that has been organized to consider the establishment, maintenance, and operation of a mall in a given area and persons owning or having any legal or equitable interest in the real property affected by the establishment of the mall.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.71.010[1965 c 7 § 35.71.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c111.pdf?cite=1961%20c%20111%20§%201[1961 c 111 § 1]; ]

== 35.71.020 - Establishment declared public purpose—Authority to establish—General powers.
The establishment of pedestrian malls is declared to be for a public purpose. Any corporate authority, by ordinance, may establish and regulate any street right-of-way as a mall, may prohibit, in whole or in part, vehicular traffic on a mall, and may provide for the acquisition of any interest in the right-of-way necessary to its establishment, and may provide for the determination of legal damages, if any, to abutting property.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.71.020[1965 c 7 § 35.71.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c111.pdf?cite=1961%20c%20111%20§%202[1961 c 111 § 2]; ]

== 35.71.030 - Resolution of intention—Traffic limitation—Property owner's right of ingress and egress.
When the corporate authority determines that the public interest, safety, and convenience is best served by the establishment of a mall and that vehicular traffic will not be unduly inconvenienced thereby, it may adopt a resolution declaring its intention to do so, and announcing the intended extent of traffic limitation. Any corporate authority is authorized to limit the utilization of any right-of-way, except for utilities and governmental functions, provided adequate alternative routes for vehicular movement, and the loading and unloading of goods are established or are available. The abutting property owner's right of ingress and egress shall be considered to have been satisfied whenever the corporate authority has planned and constructed, or there is available, an alternate route, alleyway, and service driveway.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.71.030[1965 c 7 § 35.71.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c111.pdf?cite=1961%20c%20111%20§%203[1961 c 111 § 3]; ]

== 35.71.040 - Plan—Alternate vehicle routes—Off-street parking—Hearing, notice.
Before a mall is established, a plan shall be formulated consistent with the city's comprehensive plan, including at least the area of the right-of-way between two intersecting streets and showing alternate routes outside the mall area upon which any vehicles excluded from using the mall may be accommodated; it may include a provision for on and off-street parking. After the plans have been prepared, the corporate authority shall hold a public hearing thereon, giving notice of time and place at least two weeks in advance of the hearing in a newspaper of general circulation in the city and as required by *chapter 42.32 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.71.040[1965 c 7 § 35.71.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c111.pdf?cite=1961%20c%20111%20§%204[1961 c 111 § 4]; ]

== 35.71.050 - Real estate appraisers—Report.
The corporate authority is authorized to engage duly qualified real estate appraisers, for the purpose of determining the value, or legal damages, if any, to any person, owning or having any legal or equitable interest in any real property who contends that he or she would suffer damage if a projected mall were established; in connection therewith the city shall take into account any increment in value that may result from the establishment of the mall. The appraisers shall submit their findings in writing to the chief executive of the city.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202122[2009 c 549 § 2122]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.71.050[1965 c 7 § 35.71.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c111.pdf?cite=1961%20c%20111%20§%205[1961 c 111 § 5]; ]

== 35.71.060 - Financing methods.
The corporate authority may finance the establishment of a mall, including, but not limited to, right-of-way improvements, traffic control devices, and off-street parking facilities in the vicinity of the mall, by one or more of the following methods or by a combination of any two or more of them:

. By creating local improvement districts under the laws applicable thereto in Title 35 RCW.

. By issuing revenue bonds pursuant to chapter 35.41 RCW, *RCW 35.24.305, chapter 35.92 RCW, RCW 35.81.100, and by such other statutes that may authorize such bonds.

. By issuing general obligation bonds pursuant to chapter 39.52 RCW, RCW 35.81.115, and by such other statutes and applicable provisions of the state Constitution that may authorize such bonds.

. By use of gifts and donations.

. General fund and other available moneys: PROVIDED, That if any general fund moneys are expended for a mall, provision may be made for repayment thereof to the general fund from money received from the financing of the mall.

The corporate authority may include within the cost of any mall project the expense of moving utilities, or any facility located within a right-of-way.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.71.060[1965 c 7 § 35.71.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c111.pdf?cite=1961%20c%20111%20§%206[1961 c 111 § 6]; ]

== 35.71.070 - Waivers and quitclaim deeds—Rights in right-of-way.
The corporate authority may formulate, solicit, finance and acquire, purchase, or negotiate the acquisition of waivers and the execution of quitclaim deeds by persons owning or having any legal or equitable interest in the real property affected by the establishment of a mall, conveying the necessary rights to the city to prohibit through vehicular traffic and otherwise limit vehicular access to, and from, such right-of-way: PROVIDED, That the execution of such waivers and quitclaim deeds shall not operate to extinguish the rights of the abutting owner, lessor, or lessee in the right-of-way, not included in such waiver or quitclaim deed.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.71.070[1965 c 7 § 35.71.070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c111.pdf?cite=1961%20c%20111%20§%207[1961 c 111 § 7]; ]

== 35.71.080 - Vacating, replatting right-of-way for mall purposes.
The corporate authority, as an alternate to the preceding methods, may find that the right-of-way no longer is needed as a right-of-way. When persons owning or having any legal or equitable interest in the real property affected by a proposed mall, present a petition to the corporate authority for vacating the right-of-way pursuant to chapter 35.79 RCW, or the corporate authority initiates by resolution such a vacation proceeding, a right-of-way may be vacated and replatted for mall purposes, and closed to vehicular traffic except as provided in RCW 35.71.030, consistent with the subdivision standards allowed by Title 58 RCW, and chapter 35.63 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.71.080[1965 c 7 § 35.71.080]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c111.pdf?cite=1961%20c%20111%20§%208[1961 c 111 § 8]; ]

== 35.71.090 - "Mall organization"—Powers in general—Directors—Officers.
The corporate authority may cause an organization of persons to be known as a "Mall organization" interested in creating a mall in a given area to be formed to provide for consultative assistance to the city with respect to the establishment and administration of a mall. This organization may elect a board of directors of not less than three nor more than twelve members. The board shall elect a president, a vice president, and a secretary from its membership.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.71.090[1965 c 7 § 35.71.090]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c111.pdf?cite=1961%20c%20111%20§%209[1961 c 111 § 9]; ]

== 35.71.100 - Special assessment.
After the establishment of the mall, the corporate authority may levy a special assessment on the real property within the area specially benefited by the improvement. Such special levy, if any, shall be for operation and maintenance of the mall and appurtenances thereto, which may not exceed one percent of the aggregate actual valuation of the real property (including twenty-five percent of the actual valuation of the improvements thereon) according to the valuation last placed upon it for purposes of general taxation: PROVIDED, That if a mall organization board of directors exists as authorized by RCW 35.71.090, the corporate authority may entertain a recommendation from this organization with respect to such a levy by the corporate authority.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.71.100[1965 c 7 § 35.71.100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c111.pdf?cite=1961%20c%20111%20§%2010[1961 c 111 § 10]; ]

== 35.71.110 - Claims for damages.
Following the public hearing on the ordinance to establish a mall any person owning or having any legal or equitable interest in property which might be affected by reason of the establishment of the proposed mall or the board of directors of a mall organization shall, within twenty days of such hearing, file with the city clerk a statement describing the real property as to which the claim is made, the nature of the claimant's interest therein, the nature of the alleged damage thereto and the amount of damages claimed. After the receipt thereof, the corporate authority may negotiate with the affected parties concerning them or deny them.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.71.110[1965 c 7 § 35.71.110]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c111.pdf?cite=1961%20c%20111%20§%2011[1961 c 111 § 11]; ]

== 35.71.120 - Contracts with mall organization for administration—Conflicting charter provisions.
If the corporate authority desires to have the mall administered by a mall organization rather than by one of its departments, the corporate authority may execute a contract with such an organization for the administration of the mall upon mutually satisfactory terms and conditions: PROVIDED, That if any provision of a city charter conflicts with this section, such provision of the city charter shall prevail.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.71.120[1965 c 7 § 35.71.120]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c111.pdf?cite=1961%20c%20111%20§%2012[1961 c 111 § 12]; ]

== 35.71.130 - Election to discontinue mall—Ordinance—Outstanding obligations—Restoration to former status.
The board of directors of a mall organization may call for an election, after the mall has been in operation for two years, at which the voting shall be by secret ballot, on the question: "Shall the mall be continued in operation?" If sixty percent of the membership of the organization vote to discontinue the mall, the results of the election shall be submitted to the corporate authority. The corporate authority may initiate proceedings by ordinance for the discontinuation of the mall, allocate the proportionate amount of the outstanding obligations of the mall to the abutting property of the mall or property specially benefited if a local improvement district is established, subject to the provisions of any applicable statutes and bond ordinances, resolutions, or agreements, and thereafter, at a time set by the corporate authority, the mall may be restored to its former right-of-way status.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.71.130[1965 c 7 § 35.71.130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c111.pdf?cite=1961%20c%20111%20§%2013[1961 c 111 § 13]; ]

== 35.71.910 - Chapter controls inconsistent laws.
Insofar as the provisions of this chapter are inconsistent with a provision of any other law, the provisions of this chapter shall be controlling.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.71.910[1965 c 7 § 35.71.910]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c111.pdf?cite=1961%20c%20111%20§%2015[1961 c 111 § 15]; ]

