= 35.51 - Local improvements—Classification of property—Reserve funds.
:toc:

== 35.51.010 - Definitions.
The definitions set forth in this section apply throughout this chapter.

. "Local improvement district" means any local improvement district, local utility district, or any other similar special assessment district.

. "Municipality" means any city, town, county, metropolitan municipal corporation, or any other municipal corporation or quasi-municipal corporation of the state of Washington authorized to order local improvements, to establish local improvement districts, and to levy special assessments on property specially benefited thereby to pay the expense of the improvements.

. "Permissible floor area" means the maximum total floor area, at grade and above and below grade, of a building or other structure that may lawfully be developed on a property.

. "Private land use restriction" means any restriction on the use of property imposed by agreement and enforceable by a court of law and that the legislative authority of a municipality determines is useful in measuring special benefits to a property from an improvement. Such restrictions include but are not limited to easements, covenants, and equitable servitudes that are not mere personal obligations.

. "Public land use restriction" means any restriction on the use of property imposed by federal, state, or local laws, regulations, ordinances, or resolutions. Such restrictions include but are not limited to local zoning ordinances and historic preservation statutes.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c397.pdf?cite=1985%20c%20397%20§%205[1985 c 397 § 5]; ]

== 35.51.020 - Joint planning, construction, and operation of improvements.
A municipality may contract with any other municipality, with a public corporation, or with the state of Washington, for the following purposes:

. To have the acquisition or construction of the whole or any part of an improvement performed by another municipality, by a public corporation, or by the state of Washington;

. To pay, from assessments on property within a local improvement district or from the proceeds of local improvement district bonds, notes or warrants, the whole or any part of the expense of an improvement ordered, constructed, acquired, or owned by another municipality or a public corporation; or

. To integrate the planning, financing, construction, acquisition, management, or operation, or any combination thereof, of the improvements of one municipality or a public corporation with the planning, financing, construction, acquisition, management, or operation, or any combination thereof, of the improvements of another municipality or public corporation on such terms and conditions as may be mutually agreed upon including, but not limited to, the allocation of the costs of the improvements and the allocation of planning, financing, construction, management, operation, or other responsibilities.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c242.pdf?cite=1987%20c%20242%20§%205[1987 c 242 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c397.pdf?cite=1985%20c%20397%20§%206[1985 c 397 § 6]; ]

== 35.51.030 - Alternative or additional method of assessment—Classification of property.
. As an alternative or in addition to other methods of ascertaining assessments for local improvements, the legislative authority of a municipality may develop and apply a system of classification of properties based upon some or all of the public land use restrictions or private land use restrictions to which such property may be put at the time the assessment roll is confirmed.

. The legislative authority of a municipality may classify property into office, retail, residential, public, or any other classifications the legislative authority finds reasonable, and may levy special assessments upon different classes of property at different rates, but in no case may a special assessment exceed the special benefit to a particular property. A municipality also may exempt certain classes of property from assessment if the legislative authority of the municipality determines that properties within such classes will not specially benefit from the improvement.

. For each property within a classification, the legislative authority of the municipality may determine the special assessment after consideration of any or all of the following:

.. Square footage of the property;

.. Permissible floor area;

.. Distance from or proximity of access to the local improvement;

.. Private land use restrictions and public land use restrictions;

.. Existing facilities on the property at the time the assessment roll is confirmed; and

.. Any other factor the legislative authority finds to be a reasonable measure of the special benefits to the properties being assessed.

. If after the assessment roll is confirmed, the legislative authority of a municipality finds that the lawful uses of any assessed property have changed and that the property no longer falls within its original classification, the legislative authority may, in its discretion, reclassify and reassess such property whether or not the bonds issued to pay any part of such costs remain outstanding. If such reassessment reduces the total outstanding assessments within the local improvement district, the legislative authority shall either reassess all other properties upward in an aggregate amount equal to such reduction, or shall pledge additional money, including money in a reserve fund, to the payment of principal of and interest on such bonds in an amount equal to such reduction.

. When the legislative authority of a municipality determines that it will use the alternative or additional method of assessment authorized by this section, it may select and describe the method or methods of assessment in the ordinance ordering a local improvement and creating a local improvement district if such method or methods of assessment have been described in the notice of hearing required under RCW 35.43.150. If the method or methods of assessment are so selected and described in the ordinance ordering a local improvement and creating a local improvement district, the action and decision of the legislative authority as to such method or methods of assessment shall be final and conclusive, and no lawsuit whatsoever may be maintained challenging such method or methods of assessment unless that lawsuit is served and filed no later than thirty days after the date of passage of the ordinance ordering the improvement, and creating the district or, when applicable, no later than thirty days after the expiration of the thirty-day protest period provided in RCW 35.43.180.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c397.pdf?cite=1985%20c%20397%20§%207[1985 c 397 § 7]; ]

== 35.51.040 - Reserve fund authorized—Use.
For the purpose of securing the payment of the principal of and interest on an issue of local improvement bonds, notes, warrants, or other short-term obligations, the legislative authority of a municipality may create a reserve fund in an amount not exceeding fifteen percent of the principal amount of the bonds, notes, or warrants issued. The cost of a reserve fund may be included in the cost and expense of any local improvement for assessment against the property in the local improvement district to pay the cost, or any part thereof. The reserve fund may be provided for from the proceeds of the bonds, notes, warrants, or other short-term obligations, from special assessment payments, or from any other money legally available therefor. The legislative authority of a municipality shall provide that after payment of administrative costs a sum in proportion to the ratio between the part of the original assessment against a given lot, tract, or parcel of land in a local improvement district assessed to create a reserve fund, if any, and the total original amount of such assessment, plus a proportionate share of any interest accrued in the reserve fund, shall be credited and applied, respectively, to any nondelinquent portion of the principal of that assessment and any nondelinquent installment interest on that assessment paid by a property owner, but in no event may the principal amount of bonds outstanding exceed the principal amount of assessments outstanding. Whether the payment is made during the thirty-day prepayment period referred to in RCW 35.49.010 and 35.49.020 or thereafter and whenever all or part of a remaining nondelinquent assessment or any nondelinquent installment payment of principal and interest is paid, the reserve fund balance shall be reduced accordingly as each such sum is thus credited and applied to a nondelinquent principal payment and a nondelinquent interest payment. Each payment of a nondelinquent assessment or any nondelinquent installment payment of principal and interest shall be reduced by the amount of the credit. The balance of a reserve fund remaining after payment in full and retirement of all local improvement bonds, notes, warrants, or other short-term obligations secured by such fund shall be transferred to the municipality's guaranty fund.

Where, before July 26, 1987, a municipality established a reserve fund under this section that did not provide for a credit or reimbursement of the money remaining in the reserve fund to the owners of the lots, tracts, or parcels of property subject to the assessments, the balance in the reserve fund shall be distributed, after payment in full and retirement of all local improvement district bonds and other obligations secured by the reserve fund, to those owners of the lots, tracts, or parcels of property subject to the assessments at the time the final installment or assessment payment on the lot, tract, or parcel was made. No owner is eligible to receive reimbursement for a lot, tract, or parcel if a lien on an unpaid assessment, or an installment thereon, that was imposed on such property remains in effect at the time the reimbursement is made or was foreclosed on the property. The amount to be distributed to the owners of each lot, tract, or parcel that is eligible for reimbursement shall be equal to the balance in the reserve fund, multiplied by the assessment imposed on the lot, tract, or parcel, divided by the total of all the assessments on the lots, tracts, or parcels eligible for reimbursement.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c340.pdf?cite=1987%20c%20340%20§%201[1987 c 340 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c397.pdf?cite=1985%20c%20397%20§%208[1985 c 397 § 8]; ]

== 35.51.050 - Loan agreements—Assessments may be pledged.
Assessments for local improvements in a local improvement district created by a municipality may be pledged and applied when collected to the payment of its obligations under a loan agreement entered into under chapter 39.69 RCW to pay costs of improvements in such a local improvement district.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5650.SL.pdf?cite=1997%20c%20426%20§%204[1997 c 426 § 4]; ]

== 35.51.900 - Authority supplemental—1985 c 397.
The authority granted by sections 1 through 8 of this act is supplemental and in addition to the authority granted by Title 35 RCW and to any other authority granted to cities, towns, or municipal corporations to levy special assessments.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c397.pdf?cite=1985%20c%20397%20§%2012[1985 c 397 § 12]; ]

== 35.51.9001 - Authority supplemental—1997 c 426.
The authority granted by RCW 35.51.050 is supplemental and in addition to the authority granted by Title 35 RCW and to any other authority granted to cities, towns, or municipal corporations to levy, pledge, and apply special assessments.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5650.SL.pdf?cite=1997%20c%20426%20§%205[1997 c 426 § 5]; ]

