= 35.86A - Off-street parking—Parking commissions.
:toc:

== 35.86A.010 - Declaration.
It is hereby determined and declared:

. The free circulation of traffic of all kinds through our cities is necessary to the health, safety and general welfare of the public, whether residing in, traveling to or through the cities of this state;

. The most efficient use of the street and highway system requires availability of strategically located parking for vehicles in localities where large numbers of persons congregate;

. An expanding suburban population has increased demands for further concentration of uses in central metropolitan areas, necessitating an increasing investment in streets and highways;

. On-street parking is now inadequate, and becomes increasingly an inefficient and uneconomical method for temporary storage of vehicles in commercial, industrial and high-density residential areas, causing such immediate adverse consequences as the following, among others:

.. Serious traffic congestion from on-street parking, which interferes with use of streets for travel, disrupts public surface transportation at peak hours, impedes rapid and effective fighting of fires and disposition of police forces, slows emergency vehicles, and inflicts hardship upon persons with disabilities and others dependent upon private vehicles for transportation;

.. On-street parking absorbs right-of-way useful and usable for travel;

.. On-street parking reduces the space available for truck and passenger loading for the abutting properties, hinders ready access, and impedes cleaning of streets;

.. Inability to temporarily store automobiles has discouraged the public from travel to and within our cities, from congregating at public events, and from using public facilities;

. Insufficient off-street parking has had long-range results, as the following, among others:

.. Metropolitan street and highway systems have lost efficiency and the free circulation of traffic and persons has been impaired;

.. The growth and development of metropolitan areas has been retarded;

.. Business, industry, and housing has become unnecessarily and uneconomically dispersed;

.. Limited and valuable land area is under used.

All of which cause loss of payrolls, business and productivity, and property values, with resulting impairment of the public health, safety and welfare, the utility of our streets and highways, and tax revenues;

. Establishment of public off-street parking facilities will promote the public health, safety, convenience, and welfare, by:

.. Expediting the movement of the public, and of goods in metropolitan areas, alleviating traffic congestion, and preserving the large investment in streets and highways;

.. Permitting a greater use of public facilities, congregation of the public, and more intensive development of private property within the community;

. Establishment of public off-street parking is a necessary ancillary to and extension of an efficient street and highway system in metropolitan areas, as much so as a station or terminal is to a railroad or urban transit line;

. Public off-street parking facilities, open to the public and owned by a city or town, are and remain a public use and a public function, irrespective of whether:

.. Parking fees are charged to users;

.. The management or operation of one or more parking facilities is conducted by a public agency, or under contract or lease by private enterprise; or

.. A portion of the facilities is used for commercial, store or automobile accessory purposes;

. Public parking facilities under the control of a parking commission are appropriately treated differently from other parking facilities of a city.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2390.SL.pdf?cite=2020%20c%20274%20§%2013[2020 c 274 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c204.pdf?cite=1969%20ex.s.%20c%20204%20§%201[1969 ex.s. c 204 § 1]; ]

== 35.86A.020 - Authority of cities of first and second class to establish parking facilities through parking commissions.
Cities of the first and second class are authorized and empowered to establish and maintain public off-street parking facilities through a parking commission; the use of property and property rights for such purpose is declared to be a public use; and parking facilities under the control of such parking commission shall be governed by the provisions of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2064[1994 c 81 § 64]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c204.pdf?cite=1969%20ex.s.%20c%20204%20§%202[1969 ex.s. c 204 § 2]; ]

== 35.86A.030 - Definitions.
. "Parking facilities" means lots, garages, parking terminals, buildings and structures and accommodations for parking of motor vehicles off the street or highway, open to public use, with or without charge.

. "Parking commission" shall mean the department or agency created by the legislative authority of the municipality as hereinafter provided.

. "City council" shall mean the city council or legislative authority of the municipality.

. "Mayor" shall mean the chief executive officer of the municipality.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c204.pdf?cite=1969%20ex.s.%20c%20204%20§%203[1969 ex.s. c 204 § 3]; ]

== 35.86A.040 - Ownership, control, and use of parking facilities.
Parking facilities established pursuant to this chapter shall be owned by the city, under the control of the parking commission (unless relinquished), and for the use of the public. The provisions of chapter 35.86 RCW as now or hereafter amended shall not apply to such parking facilities or other facilities under parking commission control.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c204.pdf?cite=1969%20ex.s.%20c%20204%20§%204[1969 ex.s. c 204 § 4]; ]

== 35.86A.050 - Parking commission—Creation authorized—Purpose—Membership—Terms—Vacancies—Expenses.
Any city of the first or second class may by ordinance create a parking commission for the purpose of establishing and operating off-street parking facilities.

Such parking commission shall consist of five members appointed by the mayor and confirmed by the city council, who shall serve without compensation but may be reimbursed for necessary expenses. One member of the parking commission shall be selected from among persons actively engaged in the private parking industry, if available.

Three of those first appointed shall be designated to serve for one, two, and three years respectively, and two shall be designated to serve four years. The terms for all subsequently appointed members shall be four years. In event of any vacancy, the mayor, subject to confirmation of the city council, shall make appointments to fill the unexpired portion of the term.

A member may be reappointed, and shall hold office until his or her successor has been appointed and has qualified. Members may be removed by the mayor upon consent of the city council.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2244.SL.pdf?cite=1994%20c%2081%20§%2065[1994 c 81 § 65]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c204.pdf?cite=1969%20ex.s.%20c%20204%20§%205[1969 ex.s. c 204 § 5]; ]

== 35.86A.060 - Parking commission—Chair—Rules—Resolutions.
The parking commission shall select from its members a chair, and may establish its own rules, regulations and procedures not inconsistent with this chapter. No resolution shall be adopted by the parking commission except upon the concurrence of at least three members.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202128[2009 c 549 § 2128]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c204.pdf?cite=1969%20ex.s.%20c%20204%20§%206[1969 ex.s. c 204 § 6]; ]

== 35.86A.070 - Powers and authority of parking commission.
The parking commission is authorized and empowered, in the name of the municipality by resolution to:

. Own and acquire property and property rights by purchase, gift, devise, or lease for the construction, maintenance, or operation of off-street parking facilities, or for effectuating the purpose of this chapter; and accept grants-in-aid, including compliance with conditions attached thereto;

. Construct, maintain, and operate off-street parking facilities located on land dedicated for park or civic center purposes, or on other municipally-owned land where the primary purpose of such off-street parking facility is to provide parking for persons who use such park or civic center facilities, and undertake research, and prepare plans incidental thereto subject to applicable statutes and charter provisions for municipal purchases, expenditures, and improvements; and in addition may own other off-street parking facilities and operate them in accordance with RCW 35.86A.120: PROVIDED, That the provisions of chapter 35.86 RCW as now or hereafter amended shall not apply to such construction, operation or maintenance;

. Establish and collect parking fees, require that receipts be provided for parking fees, make exemption for persons with disabilities, lease space for commercial, store, advertising or automobile accessory purposes, and regulate prices and service charges, for use of and within and the aerial space over parking facilities under its control;

. Subject to applicable city civil service provisions, provide for the appointment, removal and control of officers and employees, and prescribe their duties and compensation, and to control all equipment and property under the commission's jurisdiction;

. Contract with private persons and organizations for the management and/or operation of parking facilities under its control, and services related thereto, including leasing of such facilities or portions thereof;

. Cause construction of parking facilities as a condition of an operating agreement or lease, derived through competitive bidding, or in the manner authorized by chapter 35.42 RCW;

. Execute and accept instruments, including deeds, necessary or convenient for the carrying on of its business; acquire rights to develop parking facilities over or under city property; and to contract to operate and manage parking facilities under the jurisdiction of other city departments or divisions and of other public bodies;

. Determine the need for and recommend to the city council:

.. The establishment of local improvement districts to pay the cost of parking facilities or any part thereof;

.. The issuance of bonds or other financing by the city for construction of parking facilities;

.. The acquisition of property and property rights by condemnation from the public, or in street areas;

. Transfer its control of property to the city and liquidate its affairs, so long as such transfer does not contravene any covenant or agreement made with the holders of bonds or other creditors; and

. Require payment of the excise tax hereinafter provided.

Parking fees for parking facilities under the control of the parking commission shall be maintained commensurate with and neither higher nor lower than prevailing rates for parking charged by commercial operators in the general area.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2390.SL.pdf?cite=2020%20c%20274%20§%2014[2020 c 274 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c127.pdf?cite=1980%20c%20127%20§%201[1980 c 127 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c221.pdf?cite=1975%201st%20ex.s.%20c%20221%20§%203[1975 1st ex.s. c 221 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c204.pdf?cite=1969%20ex.s.%20c%20204%20§%207[1969 ex.s. c 204 § 7]; ]

== 35.86A.080 - New off-street parking facilities—Powers of parking commission and city council.
. Whenever the parking commission intends to construct new off-street parking facilities it shall:

.. Prepare plans for such proposed development, which shall meet the approval of the planning commission, other appropriate city planning agency, or city council;

.. Prepare a report to the city council stating the proposed method of financing and property acquisition;

.. Specify the property rights, if any, to be secured from the public or of property devoted to public use; the uses of streets necessary therefor, or realignment or vacation of streets and alleys; the relocation of street utilities; and any street area to be occupied or closed during construction.

. In the event the proposed parking facility shall require:

.. Creation of a local improvement district;

.. Issuance of bonds, allocation or appropriation of municipal revenues from other sources, or guarantees of or use of the credit of the municipality;

.. Exercise of the power of eminent domain; or

.. Use of, or vacation, realignment of streets and alleys, or relocation of municipal utilities.

One or more public hearings shall be held thereon before the city council, or an assigned committee thereof, which shall report its recommendations to be approved, revised, or rejected by the city council. Such hearings may be consolidated with any required hearings for street vacations, or creation of a local improvement district. Pursuant to such hearing, the city council may:

. Create a local improvement district to finance all or part of the parking facility, in accordance with Title 35 RCW, as now existing or hereinafter amended: PROVIDED, HOWEVER, That assessments against property within the district may be measured per lot, per square foot, by property valuation, or any other method as fairly reflects the special benefits derived therefrom, and credit in calculating the assessment may be allowed for property rights or services performed;

. Provide for issuance of revenue bonds payable from revenues of the proposed parking facility, from other off-street parking facilities, on-street meter collections, or allocations of other sources of funds; issue general obligation bonds; make reimbursable or nonrefundable appropriations from the general fund, or reserves; and/or guarantee bonds issued or otherwise pledge the city's credit, all in such combination, and under such terms and conditions as the city council shall specify;

. Authorize acquisition of the necessary property and property rights by eminent domain proceedings, in the manner authorized by law for cities in Title 8 RCW: PROVIDED, That the city council shall first determine that the proposed parking facility will promote the circulation of traffic or the more convenient or efficient use by the public of streets or public facilities in the immediate area than would exist if the proposed parking facility were not provided, or that the parking facility otherwise enhances the public health, safety and welfare; and

. Authorize and execute the necessary transfer or control of property rights; vacate or realign streets and alleys or permit uses within the same; and direct relocation of street utilities.

In event none of the four above powers need be exercised, the city council's approval of construction plans shall be deemed full authority to construct and complete the parking facility.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c204.pdf?cite=1969%20ex.s.%20c%20204%20§%208[1969 ex.s. c 204 § 8]; ]

== 35.86A.090 - Powers of cities.
The city may:

. Transfer control of off-street parking facilities under other departments to the parking commission under such conditions as deemed appropriate;

. Issue revenue bonds pursuant to chapter 35.41 RCW, and RCW * 35.24.305, and 35.81.100 as now or hereafter amended, and such other statutes as may authorize such bonds for parking facilities authorized herein;

. Issue general obligation bonds pursuant to chapters 39.44, 39.52 RCW, and RCW 35.81.115 as now or hereafter amended, and such other statutes and applicable provisions of the state Constitution that may authorize such bonds for parking facilities authorized herein;

. Appropriate funds for the parking commission; and

. Enact such ordinances as may be necessary to carry out the provisions of this chapter, notwithstanding any charter provisions to the contrary.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c204.pdf?cite=1969%20ex.s.%20c%20204%20§%209[1969 ex.s. c 204 § 9]; ]

== 35.86A.100 - Disposition of revenues—Expenditure procedure.
All revenues received shall be paid to the municipal treasurer for the credit of the general fund, or such other funds as may be provided by ordinance.

Expenditures of the parking commission shall be made in accordance with the budget adopted by the municipality pursuant to chapter 35.32A RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c204.pdf?cite=1969%20ex.s.%20c%20204%20§%2010[1969 ex.s. c 204 § 10]; ]

== 35.86A.110 - Excise tax to reimburse taxing authorities for loss of property tax revenue.
Such cities shall pay to the county treasurer an annual excise tax equal to the amount which would be paid upon real property devoted to the purpose of off-street parking, were it in private ownership. This section shall apply to parking facilities acquired and/or operated under this chapter. The proceeds of such excise tax shall be allocated by the county treasurer to the various taxing authorities in which such property is situated, in the same manner as though the property were in private ownership.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c204.pdf?cite=1969%20ex.s.%20c%20204%20§%2011[1969 ex.s. c 204 § 11]; ]

== 35.86A.120 - Operation of parking facilities—Bid requirements and procedure.
Except for off-street parking facilities situated on real property leased or rented to a city and not used for park and civic center parking, cities may operate off-street parking facilities with city forces. Leased or rented off-street parking facilities shall be operated by responsible, experienced private operators of such facilities. The call for bids shall specify the terms and conditions under which the facility will be leased for private operation. The call for bids shall specify the time and place at which the bids will be received and the time and when the same will be opened, and such call shall be advertised once a week for two successive weeks before the time fixed for the filing of bids in a newspaper of general circulation in the city. If no bid is received for the operation of such an off-street parking facility, or if the bids received are not satisfactory, the legislative body of the city may reject such bids and shall readvertise the facility for lease. In the event that no bids or no satisfactory bids shall have been received following the second advertising, the city may negotiate with a private operator for the operation of the facility without competitive bidding. In the event the city shall be unable to negotiate for satisfactory private operation within a reasonable time, the city may operate the facility for a period not to exceed three years, at which time it shall readvertise as provided above in this section.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c127.pdf?cite=1980%20c%20127%20§%202[1980 c 127 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c221.pdf?cite=1975%201st%20ex.s.%20c%20221%20§%204[1975 1st ex.s. c 221 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c204.pdf?cite=1969%20ex.s.%20c%20204%20§%2012[1969 ex.s. c 204 § 12]; ]

