= 35.85 - Viaducts, elevated roadways, tunnels and subways.
:toc:

== 35.85.010 - Authority to construct viaducts, bridges, elevated roadways, etc.
Any city of the first class shall have power to provide for the construction, maintenance and operation upon public streets and upon the extensions and connections thereof over intervening tidelands to and across any harbor reserves, waterways, canals, rivers, natural watercourses and other channels, any bridges, drawbridges, viaducts, elevated roadways and tunnels or any combination thereof together with all necessary approaches thereto, with or without street railway tracks thereon or therein, and to make any and all necessary cuts, fills, or other construction, upon, in, or along such streets and approaches as a part of any such improvement, and to order any and all work to be done which shall be necessary to complete any such improvement. The word "approaches" as used in this section shall include any arterial highway or highways or streets connecting with any such bridge, drawbridge, viaduct, elevated roadway or tunnel, or combination thereof, which are necessary to give convenient access thereto or therefrom from any portion of the improvement district which may be specially benefited by such improvement and which is liable to assessment for such improvement.

Whenever it is desired to pay the whole or any portion of the cost and expense of any such improvement by special assessments, the council or other legislative body of such city shall in the ordinance ordering such improvement fix and establish the boundaries of the improvement district, the property within which is to bear such assessment, which district shall include as near as may be, all the property specially benefited by such improvement.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.85.010[1965 c 7 § 35.85.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c103.pdf?cite=1911%20c%20103%20§%201[1911 c 103 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909ex1c14.pdf?cite=1909%20ex.s.%20c%2014%20§%201[1909 ex.s. c 14 § 1]; RRS § 9001; ]

== 35.85.020 - Assessment district—Resolution—Hearing—Ordinance ordering improvement.
Any such improvement may be initiated by the city council, or other legislative body, by a resolution, declaring its intention to order such improvement, which resolution shall set forth the nature and territorial extent of such proposed improvement, shall specify and describe the boundaries of the proposed improvement district and notify all persons who may desire to object thereto to appear and present such objections at a meeting of the council specified in such resolution and directing the board of public works, or other proper board, officer, or authority of the city, to submit to such council at or prior to the date fixed for such hearing the estimated cost and expense of the improvement, and a statement of the proportionate amount thereof which should be borne by the property within the proposed improvement district, and a statement of the aggregate assessed valuation of the real property exclusive of improvements, within said district, according to the valuation last placed upon it for purposes of general taxation. Such resolution shall be published in at least two consecutive issues of the official newspaper of the city, the date of the first publication to be at least thirty days prior to the date fixed by the resolution for hearing before the council.

Upon such hearing, or upon any adjournment thereof, the council shall have power to amend, change, extend, or contract the boundaries of the proposed improvement district as specified in the resolution, and to consider and determine all matters in relation to the proposed improvement, and, upon the conclusion of the hearing, or any adjournment thereof, shall have power by ordinance to order the improvement to be made and to adopt, fix and establish the boundaries of the improvement district. The action of such council in ordering such improvement, or in abandoning it, and in fixing and establishing the boundaries of the improvement district shall be final and conclusive. Any such ordinance may be passed upon majority vote of the council or other legislative body of the city.

Such ordinance may provide for the construction of the improvement in sections, the letting of separate contracts for each such section, and, in case the same is made in sections, separate assessment rolls to defray the cost and expense of any such section of such improvement may be prepared, and the amounts thereon appearing as finally determined, may be levied and assessed against real property within the improvement district. The provisions of law, charter and ordinance of any such city, relating to supplemental assessments, reassessments and omitted property shall be applicable to any improvement authorized in this chapter.

The city council, or other legislative body of such city, shall by general ordinance, make provision for hearing any objections in writing, to any assessment roll for such improvement, filed with the city clerk or comptroller at a prior date to the hearing thereon. Any right of appeal to the superior court provided by law to be taken from any local improvement assessment levied and assessed by any such city, may be exercised, within the time and in the manner therein provided, by any person so objecting to any assessment levied and assessed for any improvement authorized in this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.85.020[1965 c 7 § 35.85.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c103.pdf?cite=1911%20c%20103%20§%202[1911 c 103 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909ex1c14.pdf?cite=1909%20ex.s.%20c%2014%20§%202[1909 ex.s. c 14 § 2]; RRS § 9002; ]

== 35.85.030 - Limit of assessment—Lien—Priority.
The city council may prescribe by general ordinance, the mode and manner in which the charge upon property in such local improvement district shall be assessed and determined for the purpose of paying the cost and expense of establishing and constructing such improvement: PROVIDED, That no assessment shall be levied on any such district, the aggregate of which is a greater sum than twenty-five percent of the assessed value of all the real property in such district according to the last equalized assessment thereof for general taxation: PROVIDED FURTHER, That there shall be, in all cases, an opportunity for a hearing upon objections to the assessment roll by the parties affected thereby, before the council as a board of equalization, which hearing shall be after publication of a reasonable notice thereof, such notice to be published in such manner and for such time as may be prescribed by ordinance. At such hearing, or at legal adjournments thereof, such changes may be made in the assessment roll as the city council may find necessary to make the same just and equitable. Railroad rights-of-way shall be assessed for such benefits as shall inure or accrue to the owners, lessees, or operators of the same, resulting or to result from the construction and maintenance of any such improvement, whether such rights-of-way lie within the limits of any street or highway or not; such assessment to lie against the franchise rights when such right-of-way is within such street or highway.

When the assessment roll has been finally confirmed by the city council, the charges therein made shall be and become a lien against the property or franchise therein described, paramount to all other liens (except liens for assessments and taxes) upon the property assessed from the time the assessment roll shall be placed in the hands of the collector.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.85.030[1965 c 7 § 35.85.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909ex1c14.pdf?cite=1909%20ex.s.%20c%2014%20§%203[1909 ex.s. c 14 § 3]; RRS § 9003; ]

== 35.85.040 - Operation by city—Leases—Use of income.
As a part of the original construction of any improvement herein authorized, or afterward as an alteration or renewal thereof, any such city, notwithstanding any charter provision to the contrary, may, at its own cost, construct, maintain and operate street railway tracks in the roadway thereof, and may provide electric power for the propulsion of cars, and may lease the use of such tracks and power for the operation of streetcars or interurban railways; or such city may authorize any operator of the street or interurban railways to construct and furnish such street railway tracks and electric power and use the same for street or interurban purposes, under lease or franchise ordinance: PROVIDED, That no such lease or franchise shall be exclusive, but shall at all times reserve the right to the city to permit other lines of street or interurban railway to use such street railway tracks in common with any preceding lessee or grantee, upon equal terms. The rate of lease or use of such street railway tracks for streets or interurban cars shall be as fixed by the legislative authority of the city, but shall not be less than one mill for each passenger carried, or ten cents for each freight car moved over such improvement. The income from such charges, rental and leasing shall be used wholly for the maintenance, repair and betterment of said improvement and the extinguishment of any debt incurred by the city in constructing it.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.85.040[1965 c 7 § 35.85.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909ex1c14.pdf?cite=1909%20ex.s.%20c%2014%20§%204[1909 ex.s. c 14 § 4]; RRS § 9004; ]

== 35.85.050 - Authority to construct tunnels and subways.
Any city of the first class shall have power to provide for the construction, maintenance and operation within such city of tunnels, subways, or both, with or without roadways, sidewalks, street railway tracks or any combination thereof therein, together with all necessary approaches thereto; and to order any and all work to be done which shall be necessary to complete any such improvement. The word "approaches," as used in this section, shall include any arterial highway or highways or streets connecting with any such tunnel or subway which may be necessary to give convenient access thereto or therefrom from any portion of the improvement district which may be specially benefited by such improvement, and which is liable to assessment for such improvement.

Whenever it is desired to pay the whole or any portion of the cost and expense of any such improvement by special assessments, the council or other legislative body of such city shall, in the ordinance ordering such improvement, fix and establish the boundaries of the improvement district, the property in which is to bear such assessment, which district shall include as near as may be all the property specially benefited by such improvement.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.85.050[1965 c 7 § 35.85.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c168.pdf?cite=1925%20ex.s.%20c%20168%20§%201[1925 ex.s. c 168 § 1]; RRS § 9005-1; ]

== 35.85.060 - Procedure.
Any such improvement may be initiated and assessments therefor determined and levied as prescribed in RCW 35.85.020 to 35.85.040, inclusive.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.85.060[1965 c 7 § 35.85.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c168.pdf?cite=1925%20ex.s.%20c%20168%20§%202[1925 ex.s. c 168 § 2]; RRS § 9005-2; ]

== 35.85.070 - Assessments—Bonds.
Any assessments so levied shall be collected, and bonds may be issued for the payment of the whole or any part of the cost of such improvement, in the manner now or hereafter provided for the collection of assessments and the issuance of bonds for other local improvements.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.85.070[1965 c 7 § 35.85.070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c168.pdf?cite=1925%20ex.s.%20c%20168%20§%203[1925 ex.s. c 168 § 3]; RRS § 9005-3; ]

== 35.85.080 - Construction of chapter.
The provisions and remedies provided by this chapter are cumulative of existing provisions and remedies, and nothing herein contained shall be held to repeal any provision of the existing law or of any charter of any city upon the subject matter thereof, but such existing law or charter provision shall continue in full force and effect, and it shall be optional with the city authorities to proceed under either such existing law, charter provision or this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.85.080[1965 c 7 § 35.85.080]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909ex1c14.pdf?cite=1909%20ex.s.%20c%2014%20§%205[1909 ex.s. c 14 § 5]; RRS § 9005.   1925 ex.s. c 168 § 4; RRS § 9005-4; ]

