= 35.76 - Streets—Budget and accounting.
:toc:

== 35.76.010 - Declaration of purpose—Budget and accounting by functional categories.
Records of city street expenditures are generally inadequate to meet the needs of cities for planning and administration of their street programs and the needs of the legislature in providing for city street financing. It is the intent of the legislature that each city and town shall budget and thereafter maintain records and accounts for all street expenditures by functional categories in a manner consistent with its size, administrative capabilities, and the amounts of money expended by it for street purposes.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.76.010[1965 c 7 § 35.76.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c115.pdf?cite=1963%20c%20115%20§%201[1963 c 115 § 1]; ]

== 35.76.020 - Cost accounting and reporting—Cities over eight thousand.
The state auditor shall formulate, prescribe, and install a system of cost accounting and reporting for each city having a population of more than eight thousand, according to the last official census, which will correctly show all street expenditures by functional categories. The system shall also provide for reporting all revenues available for street purposes from whatever source including local improvement district assessments and state and federal aid.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1889.SL.pdf?cite=1995%20c%20301%20§%2048[1995 c 301 § 48]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.76.020[1965 c 7 § 35.76.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c115.pdf?cite=1963%20c%20115%20§%202[1963 c 115 § 2]; ]

== 35.76.030 - Cost accounting and reporting—Cities of eight thousand or less.
Consistent with the intent of this chapter as stated in RCW 35.76.010, the state auditor, from and after July 1, 1965, is authorized and directed to prescribe accounting and reporting procedures for street expenditures for cities and towns having a population of eight thousand or less, according to the last official census.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1889.SL.pdf?cite=1995%20c%20301%20§%2049[1995 c 301 § 49]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.76.030[1965 c 7 § 35.76.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c115.pdf?cite=1963%20c%20115%20§%203[1963 c 115 § 3]; ]

== 35.76.040 - Manual of instructions.
The state auditor, after consultation with the association of Washington cities and the planning division of the state department of transportation shall prepare and distribute to the cities and towns a manual of instructions governing accounting and reporting procedures for all street expenditures.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%2021[1984 c 7 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.76.040[1965 c 7 § 35.76.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c115.pdf?cite=1963%20c%20115%20§%204[1963 c 115 § 4]; ]

== 35.76.050 - Cost-audit examination and report.
The state auditor shall annually make a cost-audit examination of street records for each city and town and make a written report thereon to the legislative body of each city and town. The expense of the examination shall be paid out of that portion of the motor vehicle fund allocated to the cities and towns and withheld for use by the state department of transportation under the terms of RCW 46.68.110(1).

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1889.SL.pdf?cite=1995%20c%20301%20§%2050[1995 c 301 § 50]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%2022[1984 c 7 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.76.050[1965 c 7 § 35.76.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c115.pdf?cite=1963%20c%20115%20§%205[1963 c 115 § 5]; ]

== 35.76.060 - Budgets.
Expenditures for city and town streets shall be budgeted by each city and town according to the same functional categories prescribed by the state auditor for purposes of accounting and reporting as provided in RCW 35.76.020 and 35.76.030. 

In the preparation of city and town budgets, including the preparation and filing of budget estimates, adoption of preliminary budgets and adoption of final budgets, all expenditures for street purposes shall be designated by such functional categories only.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.76.060[1965 c 7 § 35.76.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c115.pdf?cite=1963%20c%20115%20§%206[1963 c 115 § 6]; ]

