= 35.62 - Name—Change of.
:toc:

== 35.62.010 - Authority for.
Any city or town may change its name in accordance with the procedure provided in this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.62.010[1965 c 7 § 35.62.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c146.pdf?cite=1925%20ex.s.%20c%20146%20§%201[1925 ex.s. c 146 § 1]; RRS § 8891-1; ]

== 35.62.021 - Election—Petition or resolution.
The question of whether the name of a city or town shall be changed shall be presented to the voters of the city or town upon either: (1) The adoption of a resolution by the city or town council proposing a specific name change; or (2) the submission of a petition proposing a specific name change that has been signed by voters of the city or town equal in number to at least ten percent of the total number of voters of the city or town who voted at the last municipal general election. However, for any newly incorporated city or town that has not had city officials elected at a normal general municipal election, the election that is used as the base for determining the number of required signatures shall be the election at which the initial elected officials were elected.

The election on changing the name of the city or town shall be held at the next general election occurring sixty or more days after the resolution was adopted, or the resolution [petition] was submitted that has been certified by the county auditor as having sufficient valid signatures.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c193.pdf?cite=1990%20c%20193%20§%201[1990 c 193 § 1]; ]

== 35.62.031 - Ballot—One name proposed.
Where only one new name has been proposed by petition or resolution such question shall be in substantially the following form:

"Shall the name of the city (or town) of    (insert name)    be changed to the city (or town) of    (insert the proposed new name)   ?

Yes . . .

No . . ."

If a majority of the votes cast favor the name change, the city or town shall have its name changed effective thirty days after the certification of the election results.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c193.pdf?cite=1990%20c%20193%20§%202[1990 c 193 § 2]; ]

== 35.62.041 - Ballot—More than one name proposed—Votes necessary.
Where more than one name is proposed by either petition or resolution, the question shall be separated into two separate parts and shall be in substantially the following form:

"Shall the name of the city (or town) of    (insert name)    be changed?

Yes . . .

No . . ."

"If a name change is approved, which of the following should be the new name?

   (insert name)   

   (insert name)   

Vote for one."

Voters may select a name change whether or not they vote in favor of changing the name of the city or town. If a majority of the votes cast on the first proposition favor changing the name, the name that receives at least a majority of the total number of votes cast for an alternative name shall become the new name of the city or town effective thirty days after the certification of the election results.

If no alternative name receives a simple majority vote, then an election shall be held at the next November special election date, at which voters shall be given the option of choosing which of the two alternative names that received the most votes shall become the new name of the city or town. This ballot proposition shall be worded substantially as follows:

"Which of the following names shall become the new name of the city (or town) of    (insert name)   ?

   (insert name)   

   (insert name)   

Vote for one."

The name that receives the majority vote shall become the new name of the city or town effective thirty days after the certification of the election results.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c193.pdf?cite=1990%20c%20193%20§%203[1990 c 193 § 3]; ]

== 35.62.060 - Results—Certification.
Whenever any city or town has changed its name, the clerk shall certify the new name to the secretary of state prior to the date when the change takes effect.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.62.060[1965 c 7 § 35.62.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c146.pdf?cite=1925%20ex.s.%20c%20146%20§%206[1925 ex.s. c 146 § 6]; RRS § 8891-6; ]

