= 35.58 - Metropolitan municipal corporations.
:toc:

== 35.58.010 - Declaration of policy and purpose.
It is hereby declared to be the public policy of the state of Washington to provide for the people of the populous metropolitan areas in the state the means of obtaining essential services not adequately provided by existing agencies of local government. The growth of urban population and the movement of people into suburban areas has created problems of water pollution abatement, garbage disposal, water supply, transportation, planning, parks and parkways which extend beyond the boundaries of cities, counties and special districts. For reasons of topography, location and movement of population, and land conditions and development, one or more of these problems cannot be adequately met by the individual cities, counties and districts of many metropolitan areas.

It is the purpose of this chapter to enable cities and counties to act jointly to meet these common problems in order that the proper growth and development of the metropolitan areas of the state may be assured and the health and welfare of the people residing therein may be secured.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c70.pdf?cite=1974%20ex.s.%20c%2070%20§%201[1974 ex.s. c 70 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.010[1965 c 7 § 35.58.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%201[1957 c 213 § 1]; ]

== 35.58.020 - Definitions.
The definitions set forth in this section apply throughout this chapter.

. "Authorized metropolitan function" means a metropolitan function which a metropolitan municipal corporation shall have been authorized to perform in the manner provided in this chapter.

. "Central city" means the city with the largest population in a metropolitan area.

. "Central county" means the county containing the city with the largest population in a metropolitan area.

. "City" means an incorporated city or town.

. "City council" means the legislative body of any city or town.

. "City-owned transit system" means a system of public transportation owned or operated, including contracts for the services of a publicly owned or operated system of transportation, by a city that is not located within the boundaries of a metropolitan municipal corporation, county transportation authority, or public transportation benefit area.

. "Component city" means an incorporated city or town within a metropolitan area.

. "Component county" means a county, all or part of which is included within a metropolitan area.

. "Metropolitan area" means the area contained within the boundaries of a metropolitan municipal corporation, or within the boundaries of an area proposed to be organized as such a corporation.

. "Metropolitan council" means the legislative body of a metropolitan municipal corporation, or the legislative body of a county which has by ordinance or resolution assumed the rights, powers, functions, and obligations of a metropolitan municipal corporation pursuant to the provisions of chapter 36.56 RCW.

. "Metropolitan function" means any of the functions of government named in RCW 35.58.050.

. "Metropolitan municipal corporation" means a municipal corporation of the state of Washington created pursuant to this chapter, or a county which has by ordinance or resolution assumed the rights, powers, functions, and obligations of a metropolitan municipal corporation pursuant to the provisions of chapter 36.56 RCW.

. "Metropolitan public transportation" or "metropolitan transportation" for the purposes of this chapter means the transportation of packages, passengers, and their incidental baggage by means other than by chartered bus, sightseeing bus, or any other motor vehicle not on an individual fare-paying basis, together with the necessary passenger terminals and parking facilities or other properties necessary for passenger and vehicular access to and from such people-moving systems: PROVIDED, That nothing in this chapter shall be construed to prohibit a metropolitan municipal corporation from leasing its buses to private certified carriers; to prohibit a metropolitan municipal corporation from providing school bus service for the transportation of pupils; or to prohibit a metropolitan municipal corporation from chartering an electric streetcar on rails which it operates entirely within a city.

. "Pollution" has the meaning given in RCW 90.48.020.

. "Population" means the number of residents as shown by the figures released for the most recent official state, federal, or county census, or population determination made under the direction of the office of financial management.

. "Proof of payment" means evidence of fare prepayment authorized by a metropolitan municipal corporation or a city-owned transit system for the use of buses or other modes of public transportation.

. "Special district" means any municipal corporation of the state of Washington other than a city, county, or metropolitan municipal corporation.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2480-S.SL.pdf?cite=2008%20c%20123%20§%205[2008 c 123 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c103.pdf?cite=1982%20c%20103%20§%201[1982 c 103 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c151.pdf?cite=1979%20c%20151%20§%2028[1979 c 151 § 28]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c277.pdf?cite=1977%20ex.s.%20c%20277%20§%2012[1977 ex.s. c 277 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c84.pdf?cite=1974%20ex.s.%20c%2084%20§%201[1974 ex.s. c 84 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c70.pdf?cite=1974%20ex.s.%20c%2070%20§%202[1974 ex.s. c 70 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c303.pdf?cite=1971%20ex.s.%20c%20303%20§%202[1971 ex.s. c 303 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.020[1965 c 7 § 35.58.020]; prior:  1957 c 213 § 2; ]

== 35.58.030 - Corporations authorized—Limitation on boundaries.
Any area of the state containing two or more cities, at least one of which is of ten thousand or more population, may organize as a metropolitan municipal corporation for the performance of certain functions, as provided in this chapter. The boundaries of a metropolitan municipal corporation may not be expanded to include territory located in a county other than a component county except as a result of the consolidation of two or more contiguous metropolitan municipal corporations.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1140-S.SL.pdf?cite=1993%20c%20240%20§%201[1993 c 240 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.030[1965 c 7 § 35.58.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%203[1957 c 213 § 3]; ]

== 35.58.040 - Territory which must be included or excluded—Boundaries.
At the time of its formation no metropolitan municipal corporation shall include only a part of any city, and every city shall be either wholly included or wholly excluded from the boundaries of such corporation. If subsequent to the formation of a metropolitan municipal corporation a part only of any city shall be included within the boundaries of a metropolitan municipal corporation such part shall be deemed to be "unincorporated" for the purpose of selecting a member of the metropolitan council pursuant to *RCW 35.58.120(3) and such city shall neither select nor participate in the selection of a member on the metropolitan council pursuant to RCW 35.58.120.

Any metropolitan municipal corporation now existing within a county with a population of one million or more shall, upon May 21, 1971, have the same boundaries as those of the respective central county of such metropolitan corporation. The boundaries of such metropolitan corporation may not be enlarged or diminished after such date by annexation as provided in chapter 35.58 RCW and any purported annexation of territory shall be deemed void. Any contiguous metropolitan municipal corporations may be consolidated into a single metropolitan municipal corporation upon such terms, for the purpose of performing such metropolitan function or functions, and to be effective at such time as may be approved by resolutions of the respective metropolitan councils. In the event of such consolidation the component city with the largest population shall be the central city of such consolidated metropolitan municipal corporation and the component county with the largest population shall be the central county of such consolidated metropolitan municipal corporation.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1140-S.SL.pdf?cite=1993%20c%20240%20§%202[1993 c 240 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1201-S.SL.pdf?cite=1991%20c%20363%20§%2039[1991 c 363 § 39]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c303.pdf?cite=1971%20ex.s.%20c%20303%20§%203[1971 ex.s. c 303 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c105.pdf?cite=1967%20c%20105%20§%201[1967 c 105 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.040[1965 c 7 § 35.58.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%204[1957 c 213 § 4]; ]

== 35.58.050 - Functions authorized.
A metropolitan municipal corporation shall have the power to perform any one or more of the following functions, when authorized in the manner provided in this chapter:

. Metropolitan water pollution abatement.

. Metropolitan water supply.

. Metropolitan public transportation.

. Metropolitan garbage disposal.

. Metropolitan parks and parkways.

. Metropolitan comprehensive planning.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c70.pdf?cite=1974%20ex.s.%20c%2070%20§%203[1974 ex.s. c 70 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.050[1965 c 7 § 35.58.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%205[1957 c 213 § 5]; ]

== 35.58.060 - Unauthorized functions to be performed under other law.
All functions of local government which are not authorized as provided in this chapter to be performed by a metropolitan municipal corporation, shall continue to be performed by the counties, cities and special districts within the metropolitan area as provided by law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.060[1965 c 7 § 35.58.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%206[1957 c 213 § 6]; ]

== 35.58.070 - Resolution, petition for election—Requirements, procedure.
A metropolitan municipal corporation may be created by vote of the qualified electors residing in a metropolitan area in the manner provided in this chapter. An election to authorize the creation of a metropolitan municipal corporation may be called pursuant to resolution or petition in the following manner:

. A resolution or concurring resolutions calling for such an election may be adopted by either:

.. The city council of a central city; or

.. The city councils of two or more component cities other than a central city; or

.. The board of commissioners of a central county.

A certified copy of such resolution or certified copies of such concurring resolutions shall be transmitted to the board of commissioners of the central county.

. A petition calling for such an election shall be signed by at least four percent of the qualified voters residing within the metropolitan area and shall be filed with the auditor of the central county.

Any resolution or petition calling for such an election shall describe the boundaries of the proposed metropolitan area, name the metropolitan function or functions which the metropolitan municipal corporation shall be authorized to perform initially and state that the formation of the metropolitan municipal corporation will be conducive to the welfare and benefit of the persons and property within the metropolitan area. After the filing of a first sufficient petition or resolution with such county auditor or board of county commissioners respectively, action by such auditor or board shall be deferred on any subsequent petition or resolution until after the election has been held pursuant to such first petition or resolution.

Upon receipt of such a petition, the auditor shall examine the same and certify to the sufficiency of the signatures thereon. For the purpose of examining the signatures on such petition, the auditor shall be permitted access to the voter registration books of each component county and each component city. No person may withdraw his or her name from a petition after it has been filed with the auditor. Within thirty days following the receipt of such petition, the auditor shall transmit the same to the board of commissioners of the central county, together with his or her certificate as to the sufficiency thereof.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202097[2009 c 549 § 2097]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.070[1965 c 7 § 35.58.070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%207[1957 c 213 § 7]; ]

== 35.58.080 - Hearings on petition, resolution—Inclusion, exclusion of territory—Boundaries—Calling election.
Upon receipt of a duly certified petition or a valid resolution calling for an election on the formation of a metropolitan municipal corporation, the board of commissioners of the central county shall fix a date for a public hearing thereon which shall be not more than sixty nor less than forty days following the receipt of such resolution or petition. Notice of such hearing shall be published once a week for at least four consecutive weeks in one or more newspapers of general circulation within the metropolitan area. The notice shall contain a description of the boundaries of the proposed metropolitan area, shall name the initial metropolitan function or functions and shall state the time and place of the hearing and the fact that any changes in the boundaries of the metropolitan area will be considered at such time and place. At such hearing or any continuation thereof, any interested person may appear and be heard on all matters relating to the effect of the formation of the proposed municipal metropolitan corporation. The commissioners may make such changes in the boundaries of the metropolitan area as they shall deem reasonable and proper, but may not delete any portion of the proposed area which will create an island of included or excluded lands, may not delete a portion of any city, and may not delete any portion of the proposed area which is contributing or may reasonably be expected to contribute to the pollution of any water course or body of water in the proposed area when the petition or resolution names metropolitan water pollution abatement as a function to be performed by the proposed metropolitan municipal corporation. If the commissioners shall determine that any additional territory should be included in the metropolitan area, a second hearing shall be held and notice given in the same manner as for the original hearing. The commissioners may adjourn the hearing on the formation of a metropolitan municipal corporation from time to time not exceeding thirty days in all. At the next regular meeting following the conclusion of such hearing the commissioners shall adopt a resolution fixing the boundaries of the proposed metropolitan municipal corporation, declaring that the formation of the proposed metropolitan municipal corporation will be conducive to the welfare and benefit of the persons and property therein and providing for the calling of a special election on the formation of the metropolitan municipal corporation to be held not more than one hundred twenty days nor less than sixty days following the adoption of such resolution.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c70.pdf?cite=1974%20ex.s.%20c%2070%20§%204[1974 ex.s. c 70 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.080[1965 c 7 § 35.58.080]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%208[1957 c 213 § 8]; ]

== 35.58.090 - Election procedure to form corporation and levy tax—Qualified voters—Establishment of corporation—First meeting of council.
The election on the formation of the metropolitan municipal corporation shall be conducted by the auditor of the central county in accordance with the general election laws of the state and the results thereof shall be canvassed by the county canvassing board of the central county, which shall certify the result of the election to the county legislative authority of the central county, and shall cause a certified copy of such canvass to be filed in the office of the secretary of state. Notice of the election shall be published in one or more newspapers of general circulation in each component county in the manner provided in the general election laws. No person shall be entitled to vote at such election unless that person is a qualified voter under the laws of the state in effect at the time of such election and has resided within the metropolitan area for at least thirty days preceding the date of the election. The ballot proposition shall be in substantially the following form:

"FORMATION OF METROPOLITAN

MUNICIPAL CORPORATION

Shall a metropolitan municipal corporation be established for the area described in a resolution of the county legislative authority of . . . . . . county adopted on the . . . . day of . . . . . ., (year) . . . ., to perform the metropolitan functions of . . . . . . (here insert the title of each of the functions to be authorized as set forth in the petition or initial resolution).

 YES . . . .□ NO . . . .□"

 

YES . . . .

□

 

NO . . . .

□"

If a majority of the persons voting on the proposition residing within the central city shall vote in favor thereof and a majority of the persons voting on the proposition residing in the metropolitan area outside of the central city shall vote in favor thereof, the metropolitan municipal corporation shall thereupon be established and the county legislative authority of the central county shall adopt a resolution setting a time and place for the first meeting of the metropolitan council which shall be held not later than sixty days after the date of such election. A copy of such resolution shall be transmitted to the legislative body of each component city and county and of each special district which shall be affected by the particular metropolitan functions authorized.

At the same election there shall be submitted to the voters residing within the metropolitan area, for their approval or rejection, a proposition authorizing the metropolitan municipal corporation, if formed, to levy at the earliest time permitted by law on all taxable property located within the metropolitan municipal corporation a general tax, for one year, of twenty-five cents per thousand dollars of assessed value in excess of any constitutional or statutory limitation for authorized purposes of the metropolitan municipal corporation. The proposition shall be expressed on the ballots in substantially the following form:

"ONE YEAR TWENTY-FIVE CENTS

PER THOUSAND DOLLARS OF

ASSESSED VALUE LEVY

Shall the metropolitan municipal corporation, if formed, levy a general tax of twenty-five cents per thousand dollars of assessed value for one year upon all the taxable property within said corporation in excess of the constitutional and/or statutory tax limits for authorized purposes of the corporation?

 YES . . . .□ NO . . . .□"

 

YES . . . .

□

 

NO . . . .

□"

Such proposition to be effective must be approved by a majority of at least three-fifths of the persons voting on the proposition to levy such tax, with a forty percent validation requirement, in the manner set forth in Article VII, section 2(a) of the Constitution of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2359-S.SL.pdf?cite=2016%20c%20202%20§%2027[2016 c 202 § 27]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1140-S.SL.pdf?cite=1993%20c%20240%20§%203[1993 c 240 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c195.pdf?cite=1973%201st%20ex.s.%20c%20195%20§%2023[1973 1st ex.s. c 195 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.090[1965 c 7 § 35.58.090]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%209[1957 c 213 § 9]; ]

== 35.58.100 - Additional functions—Authorized by election.
A metropolitan municipal corporation may be authorized to perform one or more metropolitan functions in addition to those which it has previously been authorized to perform, with the approval of the voters at an election, in the manner provided in this section.

An election to authorize a metropolitan municipal corporation to perform one or more additional metropolitan functions may be called pursuant to a resolution or a petition in the following manner:

. A resolution calling for such an election may be adopted by:

.. The city council of the central city; or

.. The city councils of at least one-half in number of the component cities other than the central city; or

.. The board of commissioners of the central county. Such resolution shall be transmitted to the metropolitan council.

. A petition calling for such an election shall be signed by at least four percent of the registered voters residing within the metropolitan area and shall be filed with the auditor of the central county.

Any resolution or petition calling for such an election shall name the additional metropolitan functions which the metropolitan municipal corporation shall be authorized to perform.

Upon receipt of such a petition, the auditor shall examine the signatures thereon and certify to the sufficiency thereof. For the purpose of examining the signatures on such petition, the auditor shall be permitted access to all voter registration books of any component county and of all component cities. No person may withdraw his or her name from a petition after it has been filed with the auditor. Within thirty days following the receipt of such petition, the auditor shall transmit the same to the metropolitan council, together with his or her certificate as to the sufficiency of signatures thereon.

Upon receipt of a valid resolution or duly certified petition calling for an election on the authorization of the performance of one or more additional metropolitan functions, the metropolitan council shall cause to be called a special election to be held not more than one hundred and twenty days nor less than sixty days following such receipt. Such special election shall be conducted and canvassed as provided in this chapter for an election on the question of forming a metropolitan municipal corporation. The ballot proposition shall be in substantially the following form:

"Shall the . . . . . . metropolitan municipal corporation be authorized to perform the additional metropolitan functions of . . . . . . (here insert the title of each of the additional functions to be authorized as set forth in the petition or resolution)?

 YES . . . .□ NO . . . .□"

 

YES . . . .

□

 

NO . . . .

□"

If a majority of the persons voting on the proposition shall vote in favor thereof, the metropolitan municipal corporation shall be authorized to perform such additional metropolitan function or functions.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202098[2009 c 549 § 2098]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c105.pdf?cite=1967%20c%20105%20§%202[1967 c 105 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.100[1965 c 7 § 35.58.100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2010[1957 c 213 § 10]; ]

== 35.58.110 - Additional functions—Authorized without election.
A metropolitan municipal corporation may be authorized to perform one or more metropolitan functions in addition to those which it previously has been authorized to perform, without an election, in the manner provided in this section. A resolution providing for the performance of such additional metropolitan function or functions shall be adopted by the metropolitan council. A copy of such resolution shall be transmitted by registered mail to the legislative body of each component city and county. If, within ninety days after the date of such mailing, a concurring resolution is adopted by the legislative body of each component county, of each component city of the first class, and of at least two-thirds of all other component cities, and such concurring resolutions are transmitted to the metropolitan council, such council shall by resolution declare that the metropolitan municipal corporation has been authorized to perform such additional metropolitan function or functions. A copy of such resolution shall be transmitted by registered mail to the legislative body of each component city and county and of each special district which will be affected by the particular additional metropolitan function authorized.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.110[1965 c 7 § 35.58.110]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2011[1957 c 213 § 11]; ]

== 35.58.112 - Recommended comprehensive plan for performance of additional function—Study and preparation.
The metropolitan council of a metropolitan municipal corporation upon the affirmative vote of two-thirds of the members of such council may make planning, engineering, legal, financial and feasibility studies preliminary to or incident to the preparation of a recommended comprehensive plan for any metropolitan function, and may prepare such a recommended comprehensive plan before the metropolitan municipal corporation has been authorized to perform such function. The studies and plan may cover territory within and without the metropolitan municipal corporation. A recommended comprehensive plan prepared pursuant to this section for any metropolitan function may not be adopted by the metropolitan council unless the metropolitan municipal corporation shall have been authorized to perform such function.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c105.pdf?cite=1967%20c%20105%20§%207[1967 c 105 § 7]; ]

== 35.58.114 - Recommended comprehensive plan for performance of additional function—Resolution for special election to authorize additional function—Contents—Hearings—Election procedure.
Whenever a recommended comprehensive plan for the performance of any additional metropolitan function shall have been prepared and the metropolitan council shall have found the plan to be feasible the council may by resolution call a special election to authorize the performance of such additional function without the filing of the petitions or resolutions provided for in RCW 35.58.100.

If the metropolitan council shall determine that the performance of such function requires enlargement of the metropolitan area, such resolution shall contain a description of the boundaries of the proposed metropolitan area and may be adopted only after a public hearing thereon before the council. Notice of such hearing shall be published once a week for at least two consecutive weeks in one or more newspapers of general circulation within the proposed metropolitan area. The notice shall contain a description of the boundaries of the proposed metropolitan area, shall name the additional function or functions to be performed and shall state the time and place of the hearing and the fact that any changes in the boundaries of the proposed metropolitan area will be considered at such time and place. At such hearing any interested person may appear and be heard. The council may make such changes in the proposed metropolitan area as they shall deem reasonable and proper, but may not delete any portion of the existing metropolitan area and may not delete any portion of the proposed additional area which will create an island of included or excluded lands. If the council shall determine that the proposed additional area should be further enlarged, a second hearing shall be held and notice given in the same manner as for the original hearing. The council may adjourn the hearing or hearings from time to time.

Following the conclusion of such hearing or hearings the council may adopt a resolution fixing the boundaries of the proposed metropolitan area and calling a special election on the performance of such additional function. If the metropolitan municipal corporation is then authorized to perform the function of metropolitan sewage disposal the council may provide in such resolution that local governmental agencies collecting sewage from areas outside the metropolitan area as same is constituted on the date of adoption of such resolution will not thereafter be required to discharge such sewage into the metropolitan sewer system or to secure approval of local construction plans from the metropolitan municipal corporation unless such local agency shall first have entered into a contract with the metropolitan municipal corporation for the disposal of such sewage. The metropolitan council may also provide in such resolution that the authorization to perform such additional function be effective only if the voters at such election also authorize the issuance of any general obligation bonds required to carry out the recommended comprehensive plan.

The resolution calling such election shall fix the form of the ballot proposition and the same may vary from that specified in RCW 35.58.100. If the metropolitan council shall find that the issuance of general obligation bonds is necessary to perform such additional function and to carry out such recommended comprehensive plan then the ballot proposition shall set forth the principal amount of such bonds and the maximum maturity thereof and the proposition shall be so worded that the voters may by a single yes or no vote authorize the performance of the designated function in the area described in the resolution and the issuance of such general obligation bonds.

The persons voting at such election shall be all of the qualified voters who have resided within the boundaries of the proposed metropolitan area for at least thirty days preceding the date of the election. The election shall be conducted and canvassed as provided in RCW 35.58.090.

If the resolution calling such election does not require the approval of general obligation bonds as a condition of the performance of such additional function and if a majority of the persons voting on the ballot proposition residing within the existing metropolitan municipal corporation shall vote in favor thereof and a majority of the persons residing within the area proposed to be added to the existing metropolitan municipal corporation shall vote in favor thereof the boundaries described in the resolution calling the election shall become the boundaries of the metropolitan municipal corporation and the metropolitan municipal corporation shall be authorized to perform the additional function described in the proposition.

If the resolution calling such election shall require the authorization of general obligation bonds as a condition of the performance of such additional function, then to be effective the ballot proposition must be approved as provided in the preceding paragraph and must also be approved by at least three-fifths of the persons voting thereon and the number of persons voting on such proposition must constitute not less than forty percent of the total number of votes cast within such area at the last preceding state general election.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c105.pdf?cite=1967%20c%20105%20§%208[1967 c 105 § 8]; ]

== 35.58.116 - Proposition for issuance of general obligation bonds or levy of general tax—Submission at same election or special election.
The metropolitan council may at the same election called to authorize the performance of an additional function or at a special election called by the council after it has been authorized to perform any metropolitan function submit a proposition for the issuance of general obligation bonds for capital purposes as provided in RCW 35.58.450 or a proposition for the levy of a general tax for any authorized purpose for one year in such total dollar amount as the metropolitan council may determine and specify in such proposition. Any such proposition to be effective must be assented to by at least three-fifths of the persons voting thereon and the number of persons voting on such proposition shall constitute not less than forty percent of the total number of votes cast within the metropolitan area at the last preceding state general election. Any such proposition shall only be effective if the performance of the additional function shall be authorized at such election or shall have been authorized prior thereto.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c105.pdf?cite=1967%20c%20105%20§%209[1967 c 105 § 9]; ]

== 35.58.120 - Metropolitan council—Composition.
Unless the rights, powers, functions, and obligations of a metropolitan municipal corporation have been assumed by a county as provided in chapter 36.56 RCW, a metropolitan municipal corporation shall be governed by a metropolitan council composed of elected officials of the component counties and component cities, and possibly other persons, as determined by agreement of each of the component counties and the component cities equal in number to at least twenty-five percent of the total number of component cities that have at least seventy-five percent of the combined component city populations. The agreement shall remain in effect until altered in the same manner as the initial composition is determined.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1140-S.SL.pdf?cite=1993%20c%20240%20§%204[1993 c 240 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c92.pdf?cite=1983%20c%2092%20§%201[1983 c 92 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c190.pdf?cite=1981%20c%20190%20§%203[1981 c 190 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c70.pdf?cite=1974%20ex.s.%20c%2070%20§%205[1974 ex.s. c 70 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c303.pdf?cite=1971%20ex.s.%20c%20303%20§%205[1971 ex.s. c 303 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c135.pdf?cite=1969%20ex.s.%20c%20135%20§%201[1969 ex.s. c 135 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c105.pdf?cite=1967%20c%20105%20§%203[1967 c 105 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.120[1965 c 7 § 35.58.120]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2012[1957 c 213 § 12]; ]

== 35.58.130 - Metropolitan council—Organization, chair, procedures.
At the first meeting of the metropolitan council following the formation of a metropolitan municipal corporation, the mayor of the central city shall serve as temporary chair. As its first official act the council shall elect a chair. The chair shall be a voting member of the council and shall preside at all meetings. In the event of his or her absence or inability to act the council shall select one of its members to act as chair pro tempore. A majority of all members of the council shall constitute a quorum for the transaction of business. A smaller number of councilmembers than a quorum may adjourn from time to time and may compel the attendance of absent members in such manner and under such penalties as the council may provide. The council shall determine its own rules and order of business, shall provide by resolution for the manner and time of holding all regular and special meetings and shall keep a journal of its proceedings which shall be a public record. Every legislative act of the council of a general or permanent nature shall be by resolution.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202099[2009 c 549 § 2099]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.130[1965 c 7 § 35.58.130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2013[1957 c 213 § 13]; ]

== 35.58.140 - Metropolitan council—Terms.
Each member of a metropolitan council except those selected under the provisions of RCW 35.58.120, shall hold office at the pleasure of the body which selected him or her. Each member, who shall hold office ex officio, may not hold office after he or she ceases to hold the position of elected county executive, mayor, commissioner, or councilmember. The chair shall hold office until the second Tuesday in July of each even-numbered year and may, if reelected, serve more than one term. Each member shall hold office until his or her successor has been selected as provided in this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202100[2009 c 549 § 2100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c303.pdf?cite=1971%20ex.s.%20c%20303%20§%206[1971 ex.s. c 303 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c135.pdf?cite=1969%20ex.s.%20c%20135%20§%202[1969 ex.s. c 135 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c105.pdf?cite=1967%20c%20105%20§%204[1967 c 105 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.140[1965 c 7 § 35.58.140]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2014[1957 c 213 § 14]; ]

== 35.58.150 - Metropolitan council—Vacancies.
A vacancy in the office of a member of the metropolitan council shall be filled in the same manner as provided for the original selection. The meeting of mayors to fill a vacancy of the member selected under the provisions of RCW 35.58.120 or of special district representatives to fill a vacancy of a member selected under RCW 35.58.120 shall be held at such time and place as shall be designated by the chair of the metropolitan council after ten days' written notice mailed to the mayors of each of the cities specified in RCW 35.58.120 or to the representatives of the special purpose districts specified in RCW 35.58.120, whichever is applicable.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202101[2009 c 549 § 2101]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c44.pdf?cite=1984%20c%2044%20§%201[1984 c 44 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c105.pdf?cite=1967%20c%20105%20§%205[1967 c 105 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.150[1965 c 7 § 35.58.150]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2015[1957 c 213 § 15]; ]

== 35.58.160 - Metropolitan council—Compensation—Waiver of compensation.
The chair and committee chairs of the metropolitan council except elected public officials serving on a full-time salaried basis may receive such compensation as the other members of the metropolitan council shall provide. Members of the council other than the chair and committee chairs shall receive compensation of fifty dollars per day or portion thereof for attendance at metropolitan council or committee meetings, or for performing other services on behalf of the metropolitan municipal corporation, but not exceeding a total of four thousand eight hundred dollars in any year, in addition to any compensation which they may receive as officers of component cities or counties: PROVIDED, That elected public officers serving in such capacities on a full-time basis shall not receive compensation for attendance at metropolitan, council, or committee meetings, or otherwise performing services on behalf of the metropolitan municipal corporation: PROVIDED FURTHER, That committee chairs shall not receive compensation in any one year greater than one-third of the compensation authorized for the county commissioners or county councilmembers of the central county.

Any member of the council may waive all or any portion of his or her compensation payable under this section as to any month or months during his or her term of office, by a written waiver filed with the council as provided in this section. The waiver, to be effective, must be filed any time after the member's selection and prior to the date on which the compensation would otherwise be paid. The waiver shall specify the month or period of months for which it is made.

All members of the council shall be reimbursed for expenses actually incurred by them in the conduct of official business for the metropolitan municipal corporation.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202102[2009 c 549 § 2102]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c330.pdf?cite=1985%20c%20330%20§%201[1985 c 330 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c84.pdf?cite=1974%20ex.s.%20c%2084%20§%202[1974 ex.s. c 84 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.160[1965 c 7 § 35.58.160]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2016[1957 c 213 § 16]; ]

== 35.58.170 - Corporation name and seal.
The name of a metropolitan municipal corporation shall be established by its metropolitan council. Each metropolitan municipal corporation shall adopt a corporate seal containing the name of the corporation and the date of its formation.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.170[1965 c 7 § 35.58.170]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2017[1957 c 213 § 17]; ]

== 35.58.180 - General powers of corporation.
In addition to the powers specifically granted by this chapter a metropolitan municipal corporation shall have all powers which are necessary to carry out the purposes of the metropolitan municipal corporation and to perform authorized metropolitan functions. A metropolitan municipal corporation may contract with the United States or any agency thereof, any state or agency thereof, any other metropolitan municipal corporation, any county, city, special district, or governmental agency and any private person, firm or corporation for the purpose of receiving gifts or grants or securing loans or advances for preliminary planning and feasibility studies, or for the design, construction or operation of metropolitan facilities and a metropolitan municipal corporation may contract with any governmental agency or with any private person, firm or corporation for the use by either contracting party of all or any part of the facilities, structures, lands, interests in lands, air rights over lands and rights-of-way of all kinds which are owned, leased or held by the other party and for the purpose of planning, constructing or operating any facility or performing any service which the metropolitan municipal corporation may be authorized to operate or perform, on such terms as may be agreed upon by the contracting parties: PROVIDED, That before any contract for the lease or operation of any metropolitan public transportation facilities shall be let to any private person, firm or corporation, a general schedule of rental rates for bus equipment with or without drivers shall be publicly posted applicable to all private certificated carriers, and for other facilities competitive bids shall first be called upon such notice, bidder qualifications and bid conditions as the metropolitan council shall determine.

A metropolitan municipal corporation may sue and be sued in its corporate capacity in all courts and in all proceedings.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c84.pdf?cite=1974%20ex.s.%20c%2084%20§%203[1974 ex.s. c 84 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c105.pdf?cite=1967%20c%20105%20§%206[1967 c 105 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.180[1965 c 7 § 35.58.180]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2018[1957 c 213 § 18]; ]

== 35.58.190 - Performance of function or functions—Commencement date.
The metropolitan council shall provide by resolution the effective date on which the metropolitan municipal corporation will commence to perform any one or more of the metropolitan functions which it shall have been authorized to perform.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.190[1965 c 7 § 35.58.190]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2019[1957 c 213 § 19]; ]

== 35.58.200 - Powers relative to water pollution abatement.
If a metropolitan municipal corporation shall be authorized to perform the function of metropolitan water pollution abatement, it shall have the following powers in addition to the general powers granted by this chapter:

. To prepare a comprehensive water pollution abatement plan including provisions for waterborne pollutant removal, water quality improvement, sewage disposal, and stormwater drainage for the metropolitan area.

. To acquire by purchase, condemnation, gift, or grant and to lease, construct, add to, improve, replace, repair, maintain, operate and regulate the use of metropolitan facilities for water pollution abatement, including but not limited to, removal of waterborne pollutants, water quality improvement, sewage disposal and stormwater drainage within or without the metropolitan area, including but not limited to trunk, interceptor and outfall sewers, whether used to carry sanitary waste, stormwater, or combined storm and sanitary sewage, lift and pumping stations, pipelines, drains, sewage treatment plants, flow control structures together with all lands, property rights, equipment and accessories necessary for such facilities. Sewer facilities which are owned by a county, city, or special district may be acquired or used by the metropolitan municipal corporation only with the consent of the legislative body of the county, city, or special districts owning such facilities. Counties, cities, and special districts are hereby authorized to convey or lease such facilities to metropolitan municipal corporations or to contract for their joint use on such terms as may be fixed by agreement between the legislative body of such county, city, or special district and the metropolitan council, without submitting the matter to the voters of such county, city, or district.

. To require counties, cities, special districts and other political subdivisions to discharge sewage collected by such entities from any portion of the metropolitan area which can drain by gravity flow into such metropolitan facilities as may be provided to serve such areas when the metropolitan council shall declare by resolution that the health, safety, or welfare of the people within the metropolitan area requires such action.

. To fix rates and charges for the use of metropolitan water pollution abatement facilities, and to expend the moneys so collected for authorized water pollution abatement activities.

. To establish minimum standards for the construction of local water pollution abatement facilities and to approve plans for construction of such facilities by component counties or cities or by special districts, which are connected to the facilities of the metropolitan municipal corporation. No such county, city, or special district shall construct such facilities without first securing such approval.

. To acquire by purchase, condemnation, gift, or grant, to lease, construct, add to, improve, replace, repair, maintain, operate and regulate the use of facilities for the local collection of sewage or stormwater in portions of the metropolitan area not contained within any city or special district operating local public sewer facilities and, with the consent of the legislative body of any such city or special district, to exercise such powers within such city or special district and for such purpose to have all the powers conferred by law upon such city or special district with respect to such local collection facilities: PROVIDED, That such consent shall not be required if the department of ecology certifies that a water pollution problem exists within any such city or special district and notifies the city or special district to correct such problem and corrective construction of necessary local collection facilities shall not have been commenced within one year after notification. All costs of such local collection facilities shall be paid for by the area served thereby.

. To participate fully in federal and state programs under the federal water pollution control act (86 Stat. 816 et seq., 33 U.S.C. 1251 et seq.) and to take all actions necessary to secure to itself or its component agencies the benefits of that act and to meet the requirements of that act, including but not limited to the following:

.. authority to develop and implement such plans as may be appropriate or necessary under the act.

.. authority to require by appropriate regulations that its component agencies comply with all effluent treatment and limitation requirements, standards of performance requirements, pretreatment requirements, a user charge and industrial cost recovery system conforming to federal regulation, and all conditions of national permit discharge elimination system permits issued to the metropolitan municipal corporation or its component agencies. Adoption of such regulations and compliance therewith shall not constitute a breach of any sewage disposal contract between a metropolitan municipal corporation and its component agencies nor a defense to an action for the performance of all terms and conditions of such contracts not inconsistent with such regulations and such contracts, as modified by such regulations, shall be in all respects valid and enforceable.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975c36.pdf?cite=1975%20c%2036%20§%201[1975 c 36 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c70.pdf?cite=1974%20ex.s.%20c%2070%20§%206[1974 ex.s. c 70 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c303.pdf?cite=1971%20ex.s.%20c%20303%20§%207[1971 ex.s. c 303 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.200[1965 c 7 § 35.58.200]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2020[1957 c 213 § 20]; ]

== 35.58.210 - Metropolitan water pollution abatement advisory committee.
If a metropolitan municipal corporation shall be authorized to perform the function of metropolitan water pollution abatement, the metropolitan council shall, prior to the effective date of the assumption of such function, cause a metropolitan water pollution abatement advisory committee to be formed by notifying the legislative body of each component city and county which operates a sewer system to appoint one person to serve on such advisory committee and the board of commissioners of each water-sewer district which operates a sewer system, any portion of which lies within the metropolitan area, to appoint one person to serve on such committee. The metropolitan water pollution abatement advisory committee shall meet at the time and place provided in the notice and elect a chair. The members of such committee shall serve at the pleasure of the appointing bodies and shall receive no compensation other than reimbursement for expenses actually incurred in the performance of their duties. The function of such advisory committee shall be to advise the metropolitan council in matters relating to the performance of the water pollution abatement function.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1074.SL.pdf?cite=2011%20c%20124%20§%201[2011 c 124 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202103[2009 c 549 § 2103]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1264.SL.pdf?cite=1999%20c%20153%20§%2033[1999 c 153 § 33]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c70.pdf?cite=1974%20ex.s.%20c%2070%20§%207[1974 ex.s. c 70 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.210[1965 c 7 § 35.58.210]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2021[1957 c 213 § 21]; ]

== 35.58.215 - Powers relative to systems of sewerage.
A metropolitan municipal corporation authorized to perform water pollution abatement may exercise all the powers relating to systems of sewerage authorized by RCW 36.94.010, 36.94.020, and 36.94.140 for counties.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5838-S.SL.pdf?cite=1997%20c%20447%20§%2013[1997 c 447 § 13]; ]

== 35.58.220 - Powers relative to water supply.
If a metropolitan municipal corporation shall be authorized to perform the function of metropolitan water supply, it shall have the following powers in addition to the general powers granted by this chapter:

. To prepare a comprehensive plan for the development of sources of water supply, trunk supply mains and water treatment and storage facilities for the metropolitan area.

. To acquire by purchase, condemnation, gift or grant and to lease, construct, add to, improve, replace, repair, maintain, operate and regulate the use of metropolitan facilities for water supply within or without the metropolitan area, including buildings, structures, water sheds, wells, springs, dams, settling basins, intakes, treatment plants, trunk supply mains and pumping stations, together with all lands, property, equipment and accessories necessary to enable the metropolitan municipal corporation to obtain and develop sources of water supply, treat and store water and deliver water through trunk supply mains. Water supply facilities which are owned by a city or special district may be acquired or used by the metropolitan municipal corporation only with the consent of the legislative body of the city or special district owning such facilities. Cities and special districts are hereby authorized to convey or lease such facilities to metropolitan municipal corporations or to contract for their joint use on such terms as may be fixed by agreement between the legislative body of such city or special district and the metropolitan council, without submitting the matter to the voters of such city or special district.

. To fix rates and charges for water supplied by the metropolitan municipal corporation.

. To acquire by purchase, condemnation, gift or grant and to lease, construct, add to, improve, replace, repair, maintain, operate and regulate the use of facilities for the local distribution of water in portions of the metropolitan area not contained within any city, or water-sewer district that operates a water system, and, with the consent of the legislative body of any city or the water-sewer district, to exercise such powers within such city or water-sewer district and for such purpose to have all the powers conferred by law upon such city or water-sewer district with respect to such local distribution facilities. All costs of such local distribution facilities shall be paid for by the area served thereby.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1264.SL.pdf?cite=1999%20c%20153%20§%2034[1999 c 153 § 34]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.220[1965 c 7 § 35.58.220]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2022[1957 c 213 § 22]; ]

== 35.58.230 - Metropolitan water advisory committee.
If a metropolitan municipal corporation shall be authorized to perform the function of metropolitan water supply, the metropolitan council shall, prior to the effective date of the assumption of such function, cause a metropolitan water advisory committee to be formed by notifying the legislative body of each component city which operates a water system to appoint one person to serve on such advisory committee and the board of commissioners of each water-sewer district that operates a water system, any portion of which lies within the metropolitan area, to appoint one person to serve on such committee who shall be a water-sewer district commissioner. The metropolitan water advisory committee shall meet at the time and place provided in the notice and elect a chair. The members of such committee shall serve at the pleasure of the appointing bodies and shall receive no compensation other than reimbursement for expenses actually incurred in the performance of their duties. The function of such advisory committee shall be to advise the metropolitan council with respect to matters relating to the performance of the water supply function.

The requirement to create a metropolitan water advisory committee shall not apply to a county that has assumed the rights, powers, functions, and obligations of the metropolitan municipal corporation under chapter 36.56 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202104[2009 c 549 § 2104]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1264.SL.pdf?cite=1999%20c%20153%20§%2035[1999 c 153 § 35]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1140-S.SL.pdf?cite=1993%20c%20240%20§%205[1993 c 240 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.230[1965 c 7 § 35.58.230]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2023[1957 c 213 § 23]; ]

== 35.58.240 - Powers relative to transportation.
If a metropolitan municipal corporation shall be authorized to perform the function of metropolitan transportation, it shall have the following powers in addition to the general powers granted by this chapter:

. To prepare, adopt, and carry out a general comprehensive plan for public transportation service which will best serve the residents of the metropolitan area and to amend said plan from time to time to meet changed conditions and requirements.

. To acquire by purchase, condemnation, gift, or grant and to lease, construct, add to, improve, replace, repair, maintain, operate, and regulate the use of metropolitan transportation facilities and properties within or without the metropolitan area, including systems of surface, underground, or overhead railways, tramways, buses, or any other means of local transportation except taxis, and including escalators, moving sidewalks, or other people-moving systems, passenger terminal and parking facilities and properties, and such other facilities and properties as may be necessary for passenger and vehicular access to and from such people-moving systems, terminal and parking facilities and properties, together with all lands, rights-of-way, property, equipment, and accessories necessary for such systems and facilities. Public transportation facilities and properties which are owned by any city may be acquired or used by the metropolitan municipal corporation only with the consent of the city council of the city owning such facilities. Cities are hereby authorized to convey or lease such facilities to metropolitan corporations or to contract for their joint use on such terms as may be fixed by agreement between the city council of such city and the metropolitan council, without submitting the matter to the voters of such city.

. To fix rates, tolls, fares, and charges for the use of such facilities and to establish various routes and classes of service. Fares or charges may be adjusted or eliminated for any distinguishable class of users including, but not limited to, senior citizens, persons with disabilities, and students. Classes of service and fares will be maintained in the several parts of the metropolitan area at such levels as will provide, insofar as reasonably practicable, that the portion of any annual transit operating deficit of the metropolitan municipal corporation attributable to the operation of all routes, taken as a whole, which are located within the central city is approximately in proportion to the portion of total taxes collected by or on behalf of the metropolitan municipal corporation for transit purposes within the central city, and that the portion of such annual transit operating deficit attributable to the operation of all routes, taken as a whole, which are located outside the central city, is approximately in proportion to the portion of such taxes collected outside the central city.

In the event any metropolitan municipal corporation shall extend its metropolitan transportation function to any area or service already offered by any company holding a certificate of public convenience and necessity from the Washington utilities and transportation commission under RCW 81.68.040, it shall by purchase or condemnation acquire at the fair market value, from the person holding the existing certificate for providing the services, that portion of the operating authority and equipment representing the services within the area of public operation.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2390.SL.pdf?cite=2020%20c%20274%20§%2011[2020 c 274 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c25.pdf?cite=1981%20c%2025%20§%201[1981 c 25 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c303.pdf?cite=1971%20ex.s.%20c%20303%20§%208[1971 ex.s. c 303 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c105.pdf?cite=1967%20c%20105%20§%2011[1967 c 105 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.240[1965 c 7 § 35.58.240]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2024[1957 c 213 § 24]; ]

== 35.58.245 - Public transportation function—Authorization by election required—Procedure.
Notwithstanding any other provision of chapter 35.58 RCW a metropolitan municipal corporation may perform the function of metropolitan public transportation only if the performance of such function is authorized by election. The metropolitan council may call such election and certify the ballot proposition. The election shall be conducted and canvassed as provided in RCW 35.58.090 and the municipality shall be authorized to perform the function of metropolitan public transportation if a majority of the persons voting on the proposition shall vote in favor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c303.pdf?cite=1971%20ex.s.%20c%20303%20§%201[1971 ex.s. c 303 § 1]; ]

== 35.58.250 - Other local public passenger transportation service prohibited—Agreements—Purchase—Condemnation.
Except in accordance with an agreement made as provided herein, upon the effective date on which the metropolitan municipal corporation commences to perform the metropolitan transportation function, no person or private corporation shall operate a local public passenger transportation service within the metropolitan area with the exception of taxis, buses owned or operated by a school district or private school, and buses owned or operated by any corporation or organization solely for the purposes of the corporation or organization and for the use of which no fee or fare is charged.

An agreement may be entered into between the metropolitan municipal corporation and any person or corporation legally operating a local public passenger transportation service wholly within or partly within and partly without the metropolitan area and on said effective date under which such person or corporation may continue to operate such service or any part thereof for such time and upon such terms and conditions as provided in such agreement. Where any such local public passenger transportation service will be required to cease to operate within the metropolitan area, the commission may agree with the owner of such service to purchase the assets used in providing such service, or if no agreement can be reached, the commission shall condemn such assets in the manner provided herein for the condemnation of other properties.

Wherever a privately owned public carrier operates wholly or partly within a metropolitan municipal corporation, the Washington utilities and transportation commission shall continue to exercise jurisdiction over such operation as provided by law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.250[1965 c 7 § 35.58.250]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2025[1957 c 213 § 25]; ]

== 35.58.260 - Transportation function—Acquisition of city system.
If a metropolitan municipal corporation shall be authorized to perform the metropolitan transportation function, it shall, upon the effective date of the assumption of such power, have and exercise all rights with respect to the construction, acquisition, maintenance, operation, extension, alteration, repair, control and management of passenger transportation which any component city shall have been previously empowered to exercise and, except as provided in RCW 35.21.925 and 36.73.180, such powers shall not thereafter be exercised by such component cities without the consent of the metropolitan municipal corporation: PROVIDED, That any city owning and operating a public transportation system on such effective date may continue to operate such system within such city until such system shall have been acquired by the metropolitan municipal corporation and a metropolitan municipal corporation may not acquire such system without the consent of the city council of such city.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2179-S.SL.pdf?cite=2010%20c%20251%20§%207[2010 c 251 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.260[1965 c 7 § 35.58.260]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2026[1957 c 213 § 26]; ]

== 35.58.262 - Transportation function—Fuel purchasing strategies—Reports.
. In performing the metropolitan transportation function, metropolitan municipal corporations and counties that have assumed the rights, powers, functions, and obligations of metropolitan municipal corporations under chapter 36.56 RCW may explore and implement strategies designed to reduce the overall cost of fuel and mitigate the impact of market fluctuations and pressure on both short-term and long-term fuel costs. These strategies may include, but are not limited to, futures contracts, hedging, swap transactions, option contracts, costless collars, and long-term storage.

. Metropolitan municipal corporations and counties that have assumed the rights, powers, functions, and obligations of metropolitan municipal corporations under chapter 36.56 RCW that choose to implement the strategies authorized in this section must submit periodic reports to the transportation committees of the legislature on the status of any such implemented strategies. Each report must include a description of each contract established to mitigate fuel costs, the amounts of fuel covered by the contracts, the cost mitigation results, and any related recommendations. The first report must be submitted within one year of implementation.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2746-S.SL.pdf?cite=2008%20c%20126%20§%202[2008 c 126 § 2]; ]

== 35.58.263 - Transportation function—Fuel purchasing strategies—Liability immunity.
If metropolitan municipal corporations and counties that have assumed the rights, powers, functions, and obligations of metropolitan municipal corporations under chapter 36.56 RCW choose to implement the strategies authorized in RCW 35.58.262, the state is not liable for any financial losses that may be incurred as the result of participating in such strategies.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2746-S.SL.pdf?cite=2008%20c%20126%20§%203[2008 c 126 § 3]; ]

== 35.58.265 - Acquisition of existing transportation system—Assumption of labor contracts—Transfer of employees—Preservation of employee benefits—Collective bargaining.
If a metropolitan municipal corporation shall perform the metropolitan transportation function and shall acquire any existing transportation system, it shall assume and observe all existing labor contracts relating to such system and, to the extent necessary for operation of facilities, all of the employees of such acquired transportation system whose duties are necessary to operate efficiently the facilities acquired shall be appointed to comparable positions to those which they held at the time of such transfer, and no employee or retired or pensioned employee of such systems shall be placed in any worse position with respect to pension seniority, wages, sick leave, vacation or other benefits that he or she enjoyed as an employee of such system prior to such acquisition. The metropolitan municipal corporation shall engage in collective bargaining with the duly appointed representatives of any employee labor organization having existing contracts with the acquired transportation system and may enter into labor contracts with such employee labor organization.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202105[2009 c 549 § 2105]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c91.pdf?cite=1965%20c%2091%20§%201[1965 c 91 § 1]; ]

== 35.58.268 - Public transportation employees—Payroll deduction for political action committees.
Any public official authorized to disburse funds in payment of salaries and wages of public transportation employees may, upon written request of the employee, deduct from the salary or wages of the employee, contributions for payment of voluntary deductions for political action committees sponsored by labor or employee organizations with public transportation employees as members. For the purposes of this section, "public transportation employees" means employees of a public transportation system specified in RCW 35.58.272 who are covered by a collective bargaining agreement.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c204.pdf?cite=1985%20c%20204%20§%201[1985 c 204 § 1]; ]

== 35.58.270 - Metropolitan transit commission.
. If a metropolitan municipal corporation shall be authorized to perform the function of metropolitan transportation with a commission form of management, a metropolitan transit commission shall be formed prior to the effective date of the assumption of such function. Except as provided in this section, the metropolitan transit commission shall exercise all powers of the metropolitan municipal corporation with respect to metropolitan transportation facilities, including but not limited to the power to construct, acquire, maintain, operate, extend, alter, repair, control and manage a local public transportation system within and without the metropolitan area, to establish new passenger transportation services and to alter, curtail, or abolish any services as the commission may deem desirable and to fix tolls and fares.

. The comprehensive plan for public transportation service and any amendments thereof shall be adopted by the metropolitan council and the metropolitan transit commission shall provide transportation facilities and service consistent with such plan. The metropolitan transit commission shall authorize expenditures for transportation purposes within the budget adopted by the metropolitan council. Tolls and fares may be fixed or altered by the commission only after approval thereof by the metropolitan council. Bonds of the metropolitan municipal corporation for public transportation purposes shall be issued by the metropolitan council as provided in this chapter.

. The metropolitan transit commission shall consist of seven members. Six of such members shall be appointed by the metropolitan council and the seventh member shall be the chair of the metropolitan council who shall be ex officio the chair of the metropolitan transit commission. Three of the six appointed members of the commission shall be residents of the central city and three shall be residents of the metropolitan area outside of the central city. The three central city members of the first metropolitan transit commission shall be selected from the existing transit commission of the central city, if there be a transit commission in such city. The terms of first appointees shall be for one, two, three, four, five and six years, respectively. Thereafter, commissioners shall serve for a term of four years. Compensation of transit commissioners shall be determined by the metropolitan council.

. There is one nonvoting member of the metropolitan transit commission. The nonvoting member is recommended by the labor organization representing the public transportation employees within the local public transportation system. If the public transportation employees are represented by more than one labor organization, all such labor organizations shall select the nonvoting member by majority vote. The nonvoting member is appointed for a term of four years. The nonvoting member shall comply with all governing bylaws and policies of the commission. The chair or cochairs of the commission shall exclude the nonvoting member from attending any executive session held for the purpose of discussing negotiations with labor organizations. The chair or cochairs may exclude the nonvoting member from attending any other executive session.

. The requirement to create a metropolitan transit commission shall not apply to a county that has assumed the rights, powers, functions, and obligations of the metropolitan municipal corporation under chapter 36.56 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2986-S.SL.pdf?cite=2010%20c%20278%20§%201[2010 c 278 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202106[2009 c 549 § 2106]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1140-S.SL.pdf?cite=1993%20c%20240%20§%206[1993 c 240 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c105.pdf?cite=1967%20c%20105%20§%2012[1967 c 105 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.270[1965 c 7 § 35.58.270]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2027[1957 c 213 § 27]; ]

== 35.58.271 - Public transportation in municipalities—Financing.
See chapter 35.95 RCW.

[ ]

== 35.58.2711 - Local sales and use taxes for financing public transportation systems.
See RCW 82.14.045 through 82.14.060.

[ ]

== 35.58.2712 - Public transportation feasibility study—Advanced financial support payments.
Any municipality, as defined in RCW 35.95.020, may be eligible to receive a one-time advanced financial support payment to perform a feasibility study to determine the need for public transportation to serve its residents. This payment shall be governed by the following conditions:

. The payment shall precede any advanced financial support payment to develop a plan pursuant to RCW 36.57A.150;

. The amount of such payment shall be commensurate with the number of residents in and the size of the land area of such municipality and the number and size of school districts in such municipality and shall not exceed one hundred ten thousand dollars; and

. Repayment of an advanced financial support payment shall be made to the general fund by the municipality within two years after the date such advanced payment was received. The study shall be completed within one year after the date such advanced payment was received. The study and its recommendations shall then be presented to the legislative authority of the municipality. Within six months of its receipt of the study and its recommendations, the legislative authority shall pass a resolution adopting or rejecting all or part of the study. A copy of the resolution shall be transmitted to the state agency administering this section. Such repayment shall be waived within two years of the date such advanced payment was received if the legislative authority or the voters in such municipality do not elect to levy and collect taxes to support public transportation in their area. Such repayment shall not be waived in the event any of the provisions of this subsection are not followed;

. The feasibility study shall give consideration to consolidating or coordinating all or any portion of the K-12 pupil transportation system within the proposed boundaries of the municipality. Any school district lying wholly or in part within the proposed boundaries shall fully cooperate in the study unless the school board shall pass a resolution to the contrary setting forth the reasons therefor. A copy of the resolution shall be forwarded to the secretary of the department of transportation for inclusion in the municipality's application file.

The department of transportation shall provide technical assistance in the preparation of feasibility studies, and shall adopt reasonable rules and regulations to carry out the provisions of this section.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c59.pdf?cite=1979%20c%2059%20§%201[1979 c 59 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c44.pdf?cite=1977%20ex.s.%20c%2044%20§%206[1977 ex.s. c 44 § 6]; ]

== 35.58.272 - Public transportation systems—Definitions.
"Municipality" as used in *RCW 35.58.272 through 35.58.279, as now or hereafter amended, and in RCW 36.57.080, 36.57.100, 36.57.110, 35.58.2721, 35.58.2794, and chapter 36.57A RCW, means any metropolitan municipal corporation which shall have been authorized to perform the function of metropolitan public transportation; any county performing the public transportation function as authorized by RCW 36.57.100 and 36.57.110 or which has established a county transportation authority pursuant to chapter 36.57 RCW; any public transportation benefit area established pursuant to chapter 36.57A RCW; and any city, which is not located within the boundaries of a metropolitan municipal corporation unless provided otherwise in RCW 35.21.925 and 36.73.180, county transportation authority, or public transportation benefit area, and which owns, operates or contracts for the services of a publicly owned or operated system of transportation: PROVIDED, That the term "municipality" shall mean in respect to any county performing the public transportation function pursuant to RCW 36.57.100 and 36.57.110 only that portion of the unincorporated area lying wholly within such unincorporated transportation benefit area.

"Motor vehicle" as used in *RCW 35.58.272 through 35.58.279, as now or hereafter amended, shall have the same meaning as in RCW 82.44.010.

"County auditor" shall mean the county auditor of any county or any person designated to perform the duties of a county auditor pursuant to RCW 82.44.140.

"Person" shall mean any individual, corporation, firm, association or other form of business association.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2179-S.SL.pdf?cite=2010%20c%20251%20§%208[2010 c 251 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c270.pdf?cite=1975%201st%20ex.s.%20c%20270%20§%201[1975 1st ex.s. c 270 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c255.pdf?cite=1969%20ex.s.%20c%20255%20§%207[1969 ex.s. c 255 § 7]; ]

== 35.58.2721 - Public transportation systems—Authority of municipalities to acquire, operate, etc.—Indebtedness—Bond issues.
. In addition to any other authority now provided by law, and subject only to constitutional limitations, the governing body of any municipality shall be authorized to acquire, construct, operate, and maintain a public transportation system and additions and betterments thereto, and to issue general obligation bonds for public mass transportation capital purposes including but not limited to replacement of equipment: PROVIDED, That the general indebtedness incurred under this section when considered together with all the other outstanding general indebtedness of the municipality shall not exceed the amounts of indebtedness authorized by chapter 39.36 RCW and chapter 35.58 RCW, as now or hereafter amended, to be incurred without and with the assent of the voters. Such bonds may be in any form, including bearer bonds or registered bonds as provided in RCW 39.46.030.

Any municipality is authorized to pledge for the payment or security of the principal of and interest on any bonds issued for authorized public transportation purposes all or any portion of any taxes authorized to be levied by the issuer, including, but not limited to, the local sales and use tax authorized pursuant to RCW 82.14.045, as now or hereafter amended. No motor vehicle excise taxes under *RCW 35.58.273 may be pledged for bonds.

. Notwithstanding subsection (1) of this section, such bonds may be issued and sold in accordance with chapter 39.46 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c42.pdf?cite=1990%20c%2042%20§%20315[1990 c 42 § 315]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c167.pdf?cite=1983%20c%20167%20§%2046[1983 c 167 § 46]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c175.pdf?cite=1979%20ex.s.%20c%20175%20§%201[1979 ex.s. c 175 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c270.pdf?cite=1975%201st%20ex.s.%20c%20270%20§%207[1975 1st ex.s. c 270 § 7]; ]

== 35.58.2794 - Public transportation systems—Research, testing, development, etc., of systems—Powers to comply with federal laws.
Any city, county, public transportation benefit area authority, county transportation authority, or metropolitan municipal corporation operating a public transportation system shall be authorized to conduct, contract for, participate in and support research, demonstration, testing and development of public transportation systems, equipment and use incentives and shall have all powers necessary to comply with any criteria, standards, and regulations which may be adopted under the urban mass transportation act (78 Stat. 302 et seq., 49 U.S.C. 1601 et seq.) and to take all actions necessary to meet the requirements of that act. Any county in which a county transportation authority or public transportation benefit area shall have been established and any metropolitan municipal corporation which shall have been authorized to perform the function of metropolitan public transportation shall have, in addition to such powers, the authority to prepare, adopt and carry out a comprehensive transit plan and to make such other plans and studies and to perform such programs as the governing body of the county authority public transportation benefit area authority or metropolitan municipal corporation shall deem necessary to implement and comply with said federal act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c270.pdf?cite=1975%201st%20ex.s.%20c%20270%20§%208[1975 1st ex.s. c 270 § 8]; ]

== 35.58.2795 - Public transportation systems—Six-year transit plans.
By September 1st of each year, the legislative authority of each municipality, as defined in RCW 35.58.272, and each regional transit authority shall prepare a six-year transit development plan for that calendar year and the ensuing five years. The program shall be consistent with the comprehensive plans adopted by counties, cities, and towns, pursuant to chapter 35.63, 35A.63, or 36.70 RCW, the inherent authority of a first-class city or charter county derived from its charter, or chapter 36.70A RCW. The program shall contain information as to how the municipality intends to meet state and local long-range priorities for public transportation, capital improvements, significant operating changes planned for the system, and how the municipality intends to fund program needs. The six-year plan for each municipality and regional transit authority shall specifically set forth those projects of regional significance for inclusion in the transportation improvement program within that region. Each municipality and regional transit authority shall file the six-year program with the state department of transportation, the transportation improvement board, and cities, counties, and regional planning councils within which the municipality is located.

In developing its program, the municipality and the regional transit authority shall consider those policy recommendations affecting public transportation contained in the state transportation policy plan approved by the state transportation commission and, where appropriate, adopted by the legislature. The municipality shall conduct one or more public hearings while developing its program and for each annual update.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1967-S.SL.pdf?cite=2011%20c%20371%20§%201[2011 c 371 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1928-S.SL.pdf?cite=1994%20c%20158%20§%206[1994 c 158 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990ex1c17.pdf?cite=1990%201st%20ex.s.%20c%2017%20§%2060[1990 1st ex.s. c 17 § 60]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c396.pdf?cite=1989%20c%20396%20§%201[1989 c 396 § 1]; ]

== 35.58.2796 - Public transportation systems—Annual reports by department.
. [Empty]
.. The department of transportation shall develop an annual report summarizing the status of public transportation systems in the state for the previous calendar year. By December 1st of each year, the report must be made available to the transportation committees of the legislature and to each municipality, as defined in RCW 35.58.272, and to individual members of the municipality's legislative authority.

.. To assist the department with preparation of the report, each municipality shall file a system report by September 1st of each year with the state department of transportation identifying its public transportation services for the previous calendar year and its objectives for improving the efficiency and effectiveness of those services. The system report shall address those items required for each public transportation system in the department's report.

.. The department report shall describe individual public transportation systems, including contracted transportation services and dial-a-ride services, and include a statewide summary of public transportation issues and data. The descriptions shall include the following elements and such other elements as the department deems appropriate after consultation with the municipalities and the transportation committees of the legislature:

... Equipment and facilities, including vehicle replacement standards;

... Services and service standards;

... Revenues, expenses, and ending balances, by fund source;

... Policy issues and system improvement objectives, including community participation in development of those objectives and how those objectives address statewide transportation priorities;

.. Operating indicators applied to public transportation services, revenues, and expenses. Operating indicators shall include operating cost per passenger trip, operating cost per revenue vehicle service hour, passenger trips per revenue service hour, passenger trips per vehicle service mile, vehicle service hours per employee, and farebox revenue as a percent of operating costs.

.. To the extent that information is available, the department report must include descriptive information on any other modes of public transportation, the impact of public transportation on transportation system performance, and how public transportation helps the state meet the transportation system policy goals described in RCW 47.04.280.

. [Empty]
.. The department of transportation shall develop an annual report summarizing the status of public transportation system coordination in and between counties with a population of seven hundred thousand or more that border Puget Sound for the previous calendar year. By December 1st of each year, the report must be made available to the transportation committees of the legislature and to each municipality, as defined in RCW 35.58.272, located in a county with a population of seven hundred thousand or more that borders Puget Sound and to individual members of the municipality's legislative authority.

.. To assist the department with preparation of the report required under this subsection, each municipality, as defined in RCW 35.58.272, located in a county with a population of seven hundred thousand or more that borders Puget Sound shall file a report by September 1st of each year with the department identifying its coordination efforts in the previous calendar year with other municipalities, as defined in RCW 35.58.272, located in counties with a population of seven hundred thousand or more that border Puget Sound in the following areas:

... Integrating marketing efforts;

... Aligning fare structures;

... Integrating service planning;

... Coordinating long-range planning, including capital projects planning and implementation;

.. Integrating other administrative functions and internal business processes as appropriate; and

.. Integrating certain customer-focused tools and initiatives.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1842-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%2011%20§%202[2015 3rd sp.s. c 11 § 2]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1967-S.SL.pdf?cite=2011%20c%20371%20§%202[2011 c 371 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5513.SL.pdf?cite=2005%20c%20319%20§%20101[2005 c 319 § 101]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c396.pdf?cite=1989%20c%20396%20§%202[1989 c 396 § 2]; ]

== 35.58.280 - Powers relative to garbage disposal.
If a metropolitan municipal corporation shall be authorized to perform the function of metropolitan garbage disposal, it shall have the following powers in addition to the general powers granted by this chapter:

. To prepare a comprehensive garbage disposal plan for the metropolitan area.

. To acquire by purchase, condemnation, gift, or grant and to lease, construct, add to, improve, replace, repair, maintain, operate and regulate the use of metropolitan facilities for garbage disposal within or without the metropolitan area, including garbage disposal sites, central collection station sites, structures, machinery and equipment for the operation of central collection stations and for the hauling and disposal of garbage by any means, together with all lands, property, equipment and accessories necessary for such facilities. Garbage disposal facilities which are owned by a city or county may be acquired or used by the metropolitan municipal corporation only with the consent of the legislative body of the city or county owning such facilities. Cities and counties are hereby authorized to convey or lease such facilities to metropolitan municipal corporations or to contract for their joint use on such terms as may be fixed by agreement between the legislative body of such city or county and the metropolitan council, without submitting the matter to the voters of such city or county.

. To fix rates and charges for the use of metropolitan garbage disposal facilities.

. With the consent of any component city, to acquire by purchase, condemnation, gift or grant and to lease, construct, add to, improve, replace, repair, maintain, operate and regulate the use of facilities for the local collection of garbage within such city, and for such purpose to have all the powers conferred by law upon such city with respect to such local collection facilities. Nothing herein contained shall be deemed to authorize the local collection of garbage except in component cities. All costs of such local collection facilities shall be paid for by the area served thereby.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.280[1965 c 7 § 35.58.280]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2028[1957 c 213 § 28]; ]

== 35.58.290 - Powers relative to parks and parkways.
If a metropolitan municipal corporation shall be authorized to perform the function of metropolitan parks and parkways, it shall have the following powers in addition to the general powers granted by this chapter:

. To prepare a comprehensive plan of metropolitan parks and parkways.

. To acquire by purchase, condemnation, gift or grant, to lease, construct, add to, improve, develop, replace, repair, maintain, operate and regulate the use of metropolitan parks and parkways, together with all lands, rights-of-way, property, equipment and accessories necessary therefor. A park or parkway shall be considered to be a metropolitan facility if the metropolitan council shall by resolution find it to be of use and benefit to all or a major portion of the residents of the metropolitan area. Parks or parkways which are owned by a component city or county may be acquired or used by the metropolitan municipal corporation only with the consent of the legislative body of such city or county. Cities and counties are hereby authorized to convey or lease such facilities to metropolitan municipal corporations or to contract for their joint use on such terms as may be fixed by agreement between the legislative bodies of such city or county and the metropolitan council, without submitting the matter to the voters of such city or county. If parks or parkways which have been acquired or used as metropolitan facilities shall no longer be used for park purposes by the metropolitan municipal corporation, such facilities shall revert to the component city or county which formerly owned them.

. To fix fees and charges for the use of metropolitan park and parkway facilities.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.290[1965 c 7 § 35.58.290]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2029[1957 c 213 § 29]; ]

== 35.58.300 - Metropolitan park board.
If a metropolitan municipal corporation shall be authorized to perform the function of metropolitan parks and parkways, a metropolitan park board shall be formed prior to the effective date of the assumption of such function. Except as provided in this section, the metropolitan park board shall exercise all powers of the metropolitan municipal corporation with respect to metropolitan park and parkway facilities.

The metropolitan park board shall authorize expenditures for park and parkway purposes within the budget adopted by the metropolitan council. Bonds of the metropolitan municipal corporation for park and parkway purposes shall be issued by the metropolitan council as provided in this chapter.

The metropolitan park board shall consist of five members appointed by the metropolitan council at least two of whom shall be residents of the central city. The terms of first appointees shall be for one, two, three, four and five years, respectively. Thereafter members shall serve for a term of four years. Compensation of park board members shall be determined by the metropolitan council.

The requirement to create a metropolitan park board shall not apply to a county that has assumed the rights, powers, functions, and obligations of the metropolitan municipal corporation under chapter 36.56 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1140-S.SL.pdf?cite=1993%20c%20240%20§%207[1993 c 240 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.300[1965 c 7 § 35.58.300]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2030[1957 c 213 § 30]; ]

== 35.58.310 - Powers relative to planning.
If a metropolitan municipal corporation shall be authorized to perform the function of metropolitan comprehensive planning, it shall have the following powers in addition to the general powers granted by this chapter:

. To prepare a recommended comprehensive land use and capital facilities plan for the metropolitan area.

. To review proposed zoning ordinances and resolutions or comprehensive plans of component cities and counties and make recommendations thereon. Such proposed zoning ordinances and resolutions or comprehensive plans must be submitted to the metropolitan council prior to adoption and may not be adopted until reviewed and returned by the metropolitan council. The metropolitan council shall cause such ordinances, resolutions and plans to be reviewed by the planning staff of the metropolitan municipal corporation and return such ordinances, resolutions and plans, together with their findings and recommendations thereon within sixty days following their submission.

. To provide planning services for component cities and counties upon request and upon payment therefor by the cities or counties receiving such service.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.310[1965 c 7 § 35.58.310]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2031[1957 c 213 § 31]; ]

== 35.58.320 - Eminent domain.
A metropolitan municipal corporation shall have power to acquire by purchase and condemnation all lands and property rights, both within and without the metropolitan area, which are necessary for its purposes. Such right of eminent domain shall be exercised by the metropolitan council in the same manner and by the same procedure as is or may be provided by law for cities, except insofar as such laws may be inconsistent with the provisions of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1140-S.SL.pdf?cite=1993%20c%20240%20§%208[1993 c 240 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.320[1965 c 7 § 35.58.320]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2032[1957 c 213 § 32]; ]

== 35.58.330 - Powers may be exercised with relation to public rights-of-way without franchise—Conditions.
A metropolitan municipal corporation shall have power to construct or maintain metropolitan facilities in, along, on, under, over, or through public streets, bridges, viaducts, and other public rights-of-way without first obtaining a franchise from the county or city having jurisdiction over the same: PROVIDED, That such facilities shall be constructed and maintained in accordance with the ordinances and resolutions of such city or county relating to construction, installation and maintenance of similar facilities in such public properties.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.330[1965 c 7 § 35.58.330]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2033[1957 c 213 § 33]; ]

== 35.58.340 - Disposition of unneeded property.
Except as otherwise provided herein, a metropolitan municipal corporation may sell, or otherwise dispose of any real or personal property acquired in connection with any authorized metropolitan function and which is no longer required for the purposes of the metropolitan municipal corporation in the same manner as provided for cities. When the metropolitan council determines that a metropolitan facility or any part thereof which has been acquired from a component city or county without compensation is no longer required for metropolitan purposes, but is required as a local facility by the city or county from which it was acquired, the metropolitan council shall by resolution transfer it to such city or county.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1140-S.SL.pdf?cite=1993%20c%20240%20§%209[1993 c 240 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.340[1965 c 7 § 35.58.340]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2034[1957 c 213 § 34]; ]

== 35.58.350 - Powers and functions of metropolitan municipal corporation—Where vested—Powers of metropolitan council.
All the powers and functions of a metropolitan municipal corporation shall be vested in the metropolitan council unless expressly vested in specific officers, boards, or commissions by this chapter, or vested in the county legislative authority of a county that has assumed the rights, powers, functions, and obligations of a metropolitan municipal corporation as provided in chapter 36.56 RCW. Without limitation of the foregoing authority, or of other powers given it by this chapter, the metropolitan council shall have the following powers:

. To establish offices, departments, boards and commissions in addition to those provided by this chapter which are necessary to carry out the purposes of the metropolitan municipal corporation, and to prescribe the functions, powers and duties thereof.

. To appoint or provide for the appointment of, and to remove or to provide for the removal of, all officers and employees of the metropolitan municipal corporation except those whose appointment or removal is otherwise provided by this chapter.

. To fix the salaries, wages and other compensation of all officers and employees of the metropolitan municipal corporation unless the same shall be otherwise fixed in this chapter.

. To employ such engineering, legal, financial, or other specialized personnel as may be necessary to accomplish the purposes of the metropolitan municipal corporation.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1140-S.SL.pdf?cite=1993%20c%20240%20§%2010[1993 c 240 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.350[1965 c 7 § 35.58.350]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2035[1957 c 213 § 35]; ]

== 35.58.360 - Rules and regulations—Penalties—Enforcement.
A metropolitan municipal corporation shall have power to adopt by resolution such rules and regulations as shall be necessary or proper to enable it to carry out authorized metropolitan functions and may provide penalties for the violation thereof. Actions to impose or enforce such penalties may be brought in the superior court of the state of Washington in and for the central county.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.360[1965 c 7 § 35.58.360]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2036[1957 c 213 § 36]; ]

== 35.58.370 - Merit system.
The metropolitan council shall establish and provide for the operation and maintenance of a personnel merit system for the employment, classification, promotion, demotion, suspension, transfer, layoff and discharge of its appointive officers and employees solely on the basis of merit and fitness without regard to political influence or affiliation. The person appointed or body created for the purpose of administering such personnel system shall have power to make, amend and repeal rules and regulations as are deemed necessary for such merit system. Such rules and regulations shall provide:

. That the person to be discharged or demoted must be presented with the reasons for such discharge or demotion specifically stated; and

. That he or she shall be allowed a reasonable time in which to reply thereto in writing and that he or she be given a hearing thereon within a reasonable time.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202107[2009 c 549 § 2107]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.370[1965 c 7 § 35.58.370]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2037[1957 c 213 § 37]; ]

== 35.58.380 - Retention of existing personnel.
A metropolitan municipal corporation shall offer to employ every person who on the date such corporation acquires a metropolitan facility is employed in the operation of such facility by a component city or county or by a special district.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.380[1965 c 7 § 35.58.380]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2038[1957 c 213 § 38]; ]

== 35.58.390 - Prior employees pension rights preserved.
Where a metropolitan municipal corporation employs a person employed immediately prior thereto by a component city or county, or by a special district, such employee shall be deemed to remain an employee of such city, county, or special district for the purposes of any pension plan of such city, county, or special district, and shall continue to be entitled to all rights and benefits thereunder as if he or she had remained as an employee of the city, county, or special district, until the metropolitan municipal corporation has provided a pension plan and such employee has elected, in writing, to participate therein.

Until such election, the metropolitan municipal corporation shall deduct from the remuneration of such employee the amount which such employee is or may be required to pay in accordance with the provisions of the plan of such city, county, or special district and the metropolitan municipal corporation shall pay to the city, county, or special district any amounts required to be paid under the provisions of such plan by employer or employee.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202108[2009 c 549 § 2108]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.390[1965 c 7 § 35.58.390]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2039[1957 c 213 § 39]; ]

== 35.58.400 - Prior employees sick leave and vacation rights preserved.
Where a metropolitan municipal corporation employs a person employed immediately prior thereto by a component city or county or by a special district, the employee shall be deemed to remain an employee of such city, county, or special district for the purposes of any sick leave credit plan of the component city, county, or special district until the metropolitan municipal corporation has established a sick leave credit plan for its employees, whereupon the metropolitan municipal corporation shall place to the credit of the employee the sick leave credits standing to his or her credit in the plan of such city, county, or special district.

Where a metropolitan municipal corporation employs a person theretofore employed by a component city, county, or by a special district, the metropolitan municipal corporation shall, during the first year of his or her employment by the metropolitan municipal corporation, provide for such employee a vacation with pay equivalent to that which he or she would have been entitled if he or she had remained in the employment of the city, county, or special district.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202109[2009 c 549 § 2109]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.400[1965 c 7 § 35.58.400]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2040[1957 c 213 § 40]; ]

== 35.58.410 - Budget—Expenditures—Revenue estimates—Requirements for a county assuming the powers of a metropolitan municipal corporation.
. On or before the third Monday in June of each year, each metropolitan municipal corporation shall adopt a budget for the following calendar year. Such budget shall include a separate section for each authorized metropolitan function. Expenditures shall be segregated as to operation and maintenance expenses and capital and betterment outlays. Administrative and other expense general to the corporation shall be allocated between the authorized metropolitan functions. The budget shall contain an estimate of all revenues to be collected during the following budget year, including any surplus funds remaining unexpended from the preceding year. The metropolitan council shall not be required to confine capital or betterment expenditures made from bond proceeds or emergency expenditures to items provided in the budget. The affirmative vote of three-fourths of all members of the metropolitan council shall be required to authorize emergency expenditures.

. Subsection (1) of this section shall not apply to a county that has assumed the rights, powers, functions, and obligations of a metropolitan municipal corporation under chapter 36.56 RCW. This subsection (2) shall apply only to each county that has assumed the rights, powers, functions, and obligations of a metropolitan municipal corporation under chapter 36.56 RCW.

Each county that has assumed the rights, powers, functions, and obligations of a metropolitan municipal corporation under chapter 36.56 RCW shall, on or before the third Monday in June of each year, prepare an estimate of all revenues to be collected during the following calendar year, including any surplus funds remaining unexpended from the preceding year for each authorized metropolitan function.

By June 30 of each year, the county shall adopt the rate for sewage disposal that will be charged to component cities and water-sewer districts during the following budget year.

As long as any general obligation indebtedness remains outstanding that was issued by the metropolitan municipal corporation prior to the assumption by the county, the county shall continue to impose the taxes authorized by RCW 82.14.045 and * 35.58.273(4) at the maximum rates and on all of the taxable events authorized by law. If, despite the continued imposition of those taxes, the estimate of revenues made on or before the third Monday in June shows that estimated revenues will be insufficient to make all debt service payments falling due in the following calendar year on all general obligation indebtedness issued by the metropolitan municipal corporation prior to the assumption by the county of the rights, powers, functions, and obligations of the metropolitan municipal corporation, the remaining amount required to make the debt service payments shall be designated as "supplemental income" and shall be obtained from component cities and component counties as provided under RCW 35.58.420.

The county shall prepare and adopt a budget each year in accordance with applicable general law or county charter. If supplemental income has been designated under this subsection, the supplemental income shall be reflected in the budget that is adopted. If during the budget year the actual tax revenues from the taxes imposed under the authority of RCW 82.14.045 and * 35.58.273(4) exceed the estimates upon which the supplemental income was based, the difference shall be refunded to the component cities and component counties in proportion to their payments promptly after the end of the budget year. A county that has assumed the rights, powers, functions, and obligations of a metropolitan municipal corporation under chapter 36.56 RCW shall not be required to confine capital or betterment expenditures for authorized metropolitan functions from bond proceeds or emergency expenditures to items provided in the budget.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1264.SL.pdf?cite=1999%20c%20153%20§%2036[1999 c 153 § 36]; 1998 c 321 § 26 (Referendum Bill No. 49, approved November 3, 1998); http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1140-S.SL.pdf?cite=1993%20c%20240%20§%2011[1993 c 240 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.410[1965 c 7 § 35.58.410]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2041[1957 c 213 § 41]; ]

== 35.58.420 - Supplemental income payments by component city and county.
Each component city shall pay such proportion of the supplemental income of the metropolitan municipal corporation as the assessed valuation of property within its limits bears to the total assessed valuation of taxable property within the metropolitan area. Each component county shall pay such proportion of such supplemental income as the assessed valuation of the property within the unincorporated area of such county lying within the metropolitan area bears to the total assessed valuation of taxable property within the metropolitan area. In making such determination, the metropolitan council shall use the last available assessed valuations. The metropolitan council shall certify to each component city and county, prior to the fourth Monday in June of each year, the share of the supplemental income to be paid by such component city or county for the next calendar year. The latter shall then include such amount in its budget for the ensuing calendar year, and during such year shall pay to the metropolitan municipal corporation, in equal quarterly installments, the amount of its supplemental income share from whatever sources may be available to it.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.420[1965 c 7 § 35.58.420]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2042[1957 c 213 § 42]; ]

== 35.58.430 - Funds—Disbursements—Treasurer—Expenses—Election expenses.
The treasurer of each component county shall create a separate fund into which shall be paid all money collected from taxes levied by the metropolitan municipal corporation on property in such county and such money shall be forwarded quarterly by the treasurer of each such county to the treasurer of the central county as directed by the metropolitan council. The treasurer of the central county shall act as the treasurer of the metropolitan municipal corporation and shall establish and maintain such funds as may be authorized by the metropolitan council. Money shall be disbursed from such funds upon warrants drawn by the auditor of the central county as authorized by the metropolitan council. The central county shall be reimbursed by the metropolitan municipal corporation for services rendered by the treasurer and auditor of the central county in connection with the receipt and disbursement of such funds. The expense of all special elections held pursuant to this chapter shall be paid by the metropolitan municipal corporation.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.430[1965 c 7 § 35.58.430]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2043[1957 c 213 § 43]; ]

== 35.58.450 - General obligation bonds—Issuance, sale, form, term, election, payment.
Notwithstanding the limitations of chapter 39.36 RCW and any other statutory limitations otherwise applicable and limiting municipal debt, a metropolitan municipal corporation shall have the power to contract indebtedness and issue general obligation bonds and to pledge the full faith and credit of the corporation to the payment thereof, for any authorized capital purpose of the metropolitan municipal corporation, not to exceed an amount, together with any outstanding nonvoter approved general indebtedness, equal to three-fourths of one percent of the value of the taxable property within the metropolitan municipal corporation, as the term "value of the taxable property" is defined in RCW 39.36.015. A metropolitan municipal corporation may additionally contract indebtedness and issue general obligation bonds, for any authorized capital purpose of a metropolitan municipal corporation, together with any other outstanding general indebtedness, not to exceed an amount equal to five percent of the value of the taxable property within the corporation, as the term "value of the taxable property" is defined in RCW 39.36.015, when a proposition authorizing the indebtedness has been approved by three-fifths of the persons voting on said proposition at said election at which such election the total number of persons voting on such bond proposition shall constitute not less than forty percent of the total number of voters voting within the area of said metropolitan municipal corporation at the last preceding state general election. Such general obligation bonds may be authorized in any total amount in one or more propositions and the amount of such authorization may exceed the amount of bonds which could then lawfully be issued. Such bonds may be issued in one or more series from time to time out of such authorization. The elections shall be held pursuant to RCW 39.36.050.

Whenever the voters of a metropolitan municipal corporation have, pursuant to RCW 84.52.056, approved excess property tax levies to retire such bond issues, both the principal of and interest on such general obligation bonds may be made payable from annual tax levies to be made upon all the taxable property within the metropolitan municipal corporation in excess of the constitutional and/or statutory tax limit. The principal of and interest on any general obligation bond may be made payable from any other taxes or any special assessments which the metropolitan municipal corporation may be authorized to levy or from any otherwise unpledged revenue which may be derived from the ownership or operation of properties or facilities incident to the performance of the authorized function for which such bonds are issued or may be made payable from any combination of the foregoing sources. The metropolitan council may include in the principal amount of such bond issue an amount for engineering, architectural, planning, financial, legal, urban design and other services incident to acquisition or construction solely for authorized capital purposes.

General obligation bonds shall be issued and sold by the metropolitan council as provided in chapter 39.46 RCW and shall mature in not to exceed forty years from the date of issue.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1140-S.SL.pdf?cite=1993%20c%20240%20§%2013[1993 c 240 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c186.pdf?cite=1984%20c%20186%20§%2018[1984 c 186 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c167.pdf?cite=1983%20c%20167%20§%2047[1983 c 167 § 47]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c195.pdf?cite=1973%201st%20ex.s.%20c%20195%20§%2024[1973 1st ex.s. c 195 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c303.pdf?cite=1971%20ex.s.%20c%20303%20§%209[1971 ex.s. c 303 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c56.pdf?cite=1970%20ex.s.%20c%2056%20§%2038[1970 ex.s. c 56 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c42.pdf?cite=1970%20ex.s.%20c%2042%20§%2013[1970 ex.s. c 42 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c11.pdf?cite=1970%20ex.s.%20c%2011%20§%201[1970 ex.s. c 11 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c255.pdf?cite=1969%20ex.s.%20c%20255%20§%2017[1969 ex.s. c 255 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c232.pdf?cite=1969%20ex.s.%20c%20232%20§%2016[1969 ex.s. c 232 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c105.pdf?cite=1967%20c%20105%20§%2013[1967 c 105 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.450[1965 c 7 § 35.58.450]; prior:  1957 c 213 § 45; ]

== 35.58.460 - Revenue bonds—Issuance, sale, form, term, payment, reserves, actions.
. A metropolitan municipal corporation may issue revenue bonds to provide funds to carry out its authorized metropolitan water pollution abatement, water supply, garbage disposal or transportation purposes, without submitting the matter to the voters of the metropolitan municipal corporation. The metropolitan council shall create a special fund or funds for the sole purpose of paying the principal of and interest on the bonds of each such issue, into which fund or funds the metropolitan council may obligate the metropolitan municipal corporation to pay such amounts of the gross revenue of the particular utility constructed, acquired, improved, added to, or repaired out of the proceeds of sale of such bonds, as the metropolitan council shall determine and may obligate the metropolitan municipal corporation to pay such amounts out of otherwise unpledged revenue which may be derived from the ownership, use or operation of properties or facilities owned, used or operated incident to the performance of the authorized function for which such bonds are issued or out of otherwise unpledged fees, tolls, charges, tariffs, fares, rentals, special taxes or other sources of payment lawfully authorized for such purpose, as the metropolitan council shall determine. The principal of, and interest on, such bonds shall be payable only out of such special fund or funds, and the owners of such bonds shall have a lien and charge against the gross revenue of such utility or any other revenue, fees, tolls, charges, tariffs, fares, special taxes or other authorized sources pledged to the payment of such bonds.

Such revenue bonds and the interest thereon issued against such fund or funds shall be a valid claim of the owners thereof only as against such fund or funds and the revenue pledged therefor, and shall not constitute a general indebtedness of the metropolitan municipal corporation.

Each such revenue bond shall state upon its face that it is payable from such special fund or funds, and all revenue bonds issued under this chapter shall be negotiable securities within the provisions of the law of this state. Such revenue bonds may be registered either as to principal only or as to principal and interest as provided in RCW 39.46.030, or may be bearer bonds; shall be in such denominations as the metropolitan council shall deem proper; shall be payable at such time or times and at such places as shall be determined by the metropolitan council; shall bear interest at such rate or rates as shall be determined by the metropolitan council; shall be signed by the chair and attested by the secretary of the metropolitan council, any of which signatures may be facsimile signatures, and the seal of the metropolitan municipal corporation shall be impressed or imprinted thereon; any attached interest coupons shall be signed by the facsimile signatures of said officials.

Such revenue bonds shall be sold in such manner, at such price and at such rate or rates of interest as the metropolitan council shall deem to be for the best interests of the metropolitan municipal corporation, either at public or private sale.

The metropolitan council may at the time of the issuance of such revenue bonds make such covenants with the owners of said bonds as it may deem necessary to secure and guarantee the payment of the principal thereof and the interest thereon, including but not being limited to covenants to set aside adequate reserves to secure or guarantee the payment of such principal and interest, to maintain rates sufficient to pay such principal and interest and to maintain adequate coverage over debt service, to appoint a trustee or trustees for the bond owners to safeguard the expenditure of the proceeds of sale of such bonds and to fix the powers and duties of such trustee or trustees and to make such other covenants as the metropolitan council may deem necessary to accomplish the most advantageous sale of such bonds. The metropolitan council may also provide that revenue bonds payable out of the same source may later be issued on a parity with revenue bonds being issued and sold.

The metropolitan council may include in the principal amount of any such revenue bond issue an amount to establish necessary reserves, an amount for working capital and an amount necessary for interest during the period of construction of any such metropolitan facilities plus six months. The metropolitan council may, if it deems it to the best interest of the metropolitan municipal corporation, provide in any contract for the construction or acquisition of any metropolitan facilities or additions or improvements thereto or replacements or extensions thereof that payment therefor shall be made only in such revenue bonds at the par value thereof.

If the metropolitan municipal corporation shall fail to carry out or perform any of its obligations or covenants made in the authorization, issuance and sale of such bonds, the owner of any such bond may bring action against the metropolitan municipal corporation and compel the performance of any or all of such covenants.

. Notwithstanding subsection (1) of this section, such bonds may be issued and sold in accordance with chapter 39.46 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202110[2009 c 549 § 2110]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1140-S.SL.pdf?cite=1993%20c%20240%20§%2014[1993 c 240 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c167.pdf?cite=1983%20c%20167%20§%2048[1983 c 167 § 48]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c70.pdf?cite=1974%20ex.s.%20c%2070%20§%208[1974 ex.s. c 70 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c56.pdf?cite=1970%20ex.s.%20c%2056%20§%2039[1970 ex.s. c 56 § 39]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c11.pdf?cite=1970%20ex.s.%20c%2011%20§%202[1970 ex.s. c 11 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c255.pdf?cite=1969%20ex.s.%20c%20255%20§%2018[1969 ex.s. c 255 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c232.pdf?cite=1969%20ex.s.%20c%20232%20§%2017[1969 ex.s. c 232 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c105.pdf?cite=1967%20c%20105%20§%2014[1967 c 105 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.460[1965 c 7 § 35.58.460]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2046[1957 c 213 § 46]; ]

== 35.58.470 - Funding, refunding bonds.
The metropolitan council may, by resolution, without submitting the matter to the voters of the metropolitan municipal corporation, provide for the issuance of funding or refunding general obligation bonds to refund any outstanding general obligation bonds or any part thereof at maturity, or before maturity if they are by their terms or by other agreement subject to prior redemption, with the right in the metropolitan council to combine various series and issues of the outstanding bonds by a single issue of funding or refunding bonds, and to issue refunding bonds to pay any redemption premium payable on the outstanding bonds being refunded. The funding or refunding general obligation bonds shall, except as specifically provided in this section, be issued in accordance with the provisions of this chapter with respect to general obligation bonds.

The metropolitan council may, by resolution, without submitting the matter to the voters of the metropolitan municipal corporation, provide for the issuance of funding or refunding revenue bonds to refund any outstanding revenue bonds or any part thereof at maturity, or before maturity if they are by their terms or by agreement subject to prior redemption, with the right in the metropolitan council to combine various series and issues of the outstanding bonds by a single issue of refunding bonds, and to issue refunding bonds to pay any redemption premium payable on the outstanding bonds being refunded. The funding or refunding revenue bonds shall be payable only out of a special fund created out of the gross revenue of the particular utility, and shall be a valid claim only as against such special fund and the amount of the revenue of the utility pledged to the fund. The funding or refunding revenue bonds shall, except as specifically provided in this section, be issued in accordance with the provisions of this chapter with respect to revenue bonds.

The metropolitan council may exchange the funding or refunding bonds at par for the bonds which are being funded or refunded, or it may sell them in such manner, at such price and at such rate or rates of interest as it deems for the best interest of the metropolitan municipal corporation.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c56.pdf?cite=1970%20ex.s.%20c%2056%20§%2040[1970 ex.s. c 56 § 40]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c232.pdf?cite=1969%20ex.s.%20c%20232%20§%2018[1969 ex.s. c 232 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.470[1965 c 7 § 35.58.470]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2047[1957 c 213 § 47]; ]

== 35.58.480 - Borrowing money from component city or county.
A metropolitan municipal corporation shall have the power when authorized by a majority of all members of the metropolitan council to borrow money from any component city or county and such cities or counties are hereby authorized to make such loans or advances on such terms as may be mutually agreed upon by the legislative bodies of the metropolitan municipal corporation and any such component city or county to provide funds to carry out the purposes of the metropolitan municipal corporation.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.480[1965 c 7 § 35.58.480]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2048[1957 c 213 § 48]; ]

== 35.58.490 - Interest bearing warrants.
A metropolitan council shall have the power to authorize the issuance of interest bearing warrants on such terms and conditions as the metropolitan council shall provide and to repay the interest bearing warrants with any moneys legally authorized for such purposes, including tax receipts where appropriate.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1140-S.SL.pdf?cite=1993%20c%20240%20§%2015[1993 c 240 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.490[1965 c 7 § 35.58.490]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2049[1957 c 213 § 49]; ]

== 35.58.500 - Local improvement districts—Utility local improvement districts.
The metropolitan municipal corporation shall have the power to levy special assessments payable over a period of not exceeding twenty years on all property within the metropolitan area specially benefited by any improvement, on the basis of special benefits conferred, to pay in whole, or in part, the damages or costs of any such improvement, and for such purpose may establish local improvement districts and enlarged local improvement districts, issue local improvement warrants and bonds to be repaid by the collection of local improvement assessments and generally to exercise with respect to any improvements which it may be authorized to construct or acquire the same powers as may now or hereafter be conferred by law upon cities. Such local improvement districts shall be created and such special assessments levied and collected and local improvement warrants and bonds issued and sold in the same manner as shall now or hereafter be provided by law for cities. The duties imposed upon the city treasurer under such acts shall be imposed upon the treasurer of the county in which such local improvement district shall be located.

A metropolitan municipal corporation may provide that special benefit assessments levied in any local improvement district may be paid into such revenue bond redemption fund or funds as may be designated by the metropolitan council to secure the payment of revenue bonds issued to provide funds to pay the cost of improvements for which such assessments were levied. If local improvement district assessments shall be levied for payment into a revenue bond fund, the local improvement district created therefor shall be designated a utility local improvement district. A metropolitan municipal corporation that creates a utility local improvement district shall conform with the laws relating to utility local improvement districts created by a city.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1140-S.SL.pdf?cite=1993%20c%20240%20§%2016[1993 c 240 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.500[1965 c 7 § 35.58.500]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2050[1957 c 213 § 50]; ]

== 35.58.510 - Obligations of corporation are legal investments and security for public deposits.
All banks, trust companies, bankers, savings banks, and institutions, building and loan associations, savings and loan associations, investment companies and other persons carrying on a banking or investment business, all insurance companies, insurance associations, and other persons carrying on an insurance business, and all executors, administrators, curators, trustees and other fiduciaries, may legally invest any sinking funds, moneys, or other funds belonging to them or within their control in any bonds or other obligations issued by a metropolitan municipal corporation pursuant to this chapter. Such bonds and other obligations shall be authorized security for all public deposits. It is the purpose of this section to authorize any persons, political subdivisions and officers, public or private, to use any funds owned or controlled by them for the purchase of any such bonds or other obligations. Nothing contained in this section with regard to legal investments shall be construed as relieving any person of any duty of exercising reasonable care in selecting securities.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.510[1965 c 7 § 35.58.510]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2051[1957 c 213 § 51]; ]

== 35.58.520 - Investment of corporate funds.
A metropolitan municipal corporation shall have the power to invest its funds held in reserves or sinking funds or any such funds which are not required for immediate disbursement, in any investments in which a city is authorized to invest, as provided in RCW 35.39.030.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1140-S.SL.pdf?cite=1993%20c%20240%20§%2017[1993 c 240 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.520[1965 c 7 § 35.58.520]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2052[1957 c 213 § 52]; ]

== 35.58.530 - Annexation—Requirements, procedure.
Territory located within a component county that is annexed to a component city after the establishment of a metropolitan municipal corporation shall by such act be annexed to the metropolitan municipal corporation. Territory within a metropolitan municipal corporation may be annexed to a city which is not within such metropolitan municipal corporation in the manner provided by law and in such event either (1) such city may be annexed to such metropolitan municipal corporation by ordinance of the legislative body of the city concurred in by resolution of the metropolitan council, or (2) if such city shall not be so annexed such territory shall remain within the metropolitan municipal corporation unless such city shall by resolution of its legislative body request the withdrawal of such territory subject to any outstanding indebtedness of the metropolitan corporation and the metropolitan council shall by resolution consent to such withdrawal.

Any territory located within a component county that is contiguous to a metropolitan municipal corporation and lying wholly within an incorporated city or town may be annexed to such metropolitan municipal corporation by ordinance of the legislative body of such city or town requesting such annexation concurred in by resolution of the metropolitan council.

Any other territory located within a component county that is adjacent to a metropolitan municipal corporation may be annexed thereto by vote of the qualified electors residing in the territory to be annexed, in the manner provided in this chapter. An election to annex such territory may be called pursuant to a petition or resolution in the following manner:

. A petition calling for such an election shall be signed by at least four percent of the qualified voters residing within the territory to be annexed and shall be filed with the auditor of the central county.

. A resolution calling for such an election may be adopted by the metropolitan council.

Any resolution or petition calling for such an election shall describe the boundaries of the territory to be annexed, and state that the annexation of such territory to the metropolitan municipal corporation will be conducive to the welfare and benefit of the persons or property within the metropolitan municipal corporation and within the territory proposed to be annexed.

Upon receipt of such a petition, the auditor shall examine the same and certify to the sufficiency of the signatures thereon. Within thirty days following the receipt of such petition, the auditor shall transmit the same to the metropolitan council, together with his or her certificate as to the sufficiency thereof.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%202111[2009 c 549 § 2111]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1140-S.SL.pdf?cite=1993%20c%20240%20§%2018[1993 c 240 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c135.pdf?cite=1969%20ex.s.%20c%20135%20§%203[1969 ex.s. c 135 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c105.pdf?cite=1967%20c%20105%20§%2015[1967 c 105 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.530[1965 c 7 § 35.58.530]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2053[1957 c 213 § 53]; ]

== 35.58.540 - Annexation—Hearings—Inclusion, exclusion of territory—Boundaries—Calling election.
Upon receipt of a duly certified petition calling for an election on the annexation of territory to a metropolitan municipal corporation, or if the metropolitan council shall determine without a petition being filed, that an election on the annexation of any adjacent territory shall be held, the metropolitan council shall fix a date for a public hearing thereon which shall be not more than sixty nor less than forty days following the receipt of such petition or adoption of such resolution. Notice of such hearing shall be published once a week for at least four consecutive weeks in one or more newspapers of general circulation within the territory proposed to be annexed. The notice shall contain a description of the boundaries of the territory proposed to be annexed and shall state the time and place of the hearing thereon and the fact that any changes in the boundaries of such territory will be considered at such time and place. At such hearing or any continuation thereof, any interested person may appear and be heard on all matters relating to the proposed annexation. The metropolitan council may make such changes in the boundaries of the territory proposed to be annexed as it shall deem reasonable and proper, but may not delete any portion of the proposed area which will create an island of included or excluded lands and may not delete a portion of any city. If the metropolitan council shall determine that any additional territory should be included in the territory to be annexed, a second hearing shall be held and notice given in the same manner as for the original hearing. The metropolitan council may adjourn the hearing on the proposed annexation from time to time not exceeding thirty days in all. At the next regular meeting following the conclusion of such hearing, the metropolitan council shall, if it finds that the annexation of such territory will be conducive to the welfare and benefit of the persons and property therein and the welfare and benefit of the persons and property within the metropolitan municipal corporation, adopt a resolution fixing the boundaries of the territory to be annexed and causing to be called a special election on such annexation to be held not more than one hundred twenty days nor less than sixty days following the adoption of such resolution.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.540[1965 c 7 § 35.58.540]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2054[1957 c 213 § 54]; ]

== 35.58.550 - Annexation—Election—Favorable vote.
An election on the annexation of territory to a metropolitan municipal corporation shall be conducted and canvassed in the same manner as provided for the conduct of an election on the formation of a metropolitan municipal corporation except that notice of such election shall be published in one or more newspapers of general circulation in the territory proposed to be annexed and the ballot proposition shall be in substantially the following form:

ANNEXATION TO (here insert name of

metropolitan municipal corporation).

"Shall the territory described in a resolution of the metropolitan council of (here insert name of metropolitan municipal corporation) adopted on the . . . . . . . . . ., 19. . ., be annexed to such incorporation?

 YES . . . .□ NO . . . .□"

 

YES . . . .

□

 

NO . . . .

□"

If a majority of those voting on such proposition vote in favor thereof, the territory shall thereupon be annexed to the metropolitan municipal corporation.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.550[1965 c 7 § 35.58.550]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2055[1957 c 213 § 55]; ]

== 35.58.560 - Taxes—Counties or cities not to impose on certain operations—Credits or offsets against state taxes—Refund of motor vehicle fuel taxes paid.
No county or city shall have the right to impose a tax upon the gross revenues derived by a metropolitan municipal corporation from the operation of a metropolitan sewage disposal, water supply, garbage disposal or public transportation system.

A metropolitan municipal corporation may credit or offset against the amount of any tax which is levied by the state during any calendar year upon the gross revenues derived by such metropolitan municipal corporation from the performance of any authorized function, the amount of any expenditures made from such gross revenues by such metropolitan municipal corporation during the same calendar year or any year prior to May 21, 1971 in planning for or performing the function of metropolitan public transportation and including interest on any moneys advanced for such purpose from other funds and to the extent of such credit a metropolitan municipal corporation may expend such revenues for such purposes.

A metropolitan municipal corporation authorized to perform the function of metropolitan public transportation and engaged in the operation of an urban passenger transportation system shall receive a refund of the amount of the motor vehicle fuel tax levied by the state and paid on each gallon of motor vehicle fuel used, whether such vehicle fuel tax has been paid either directly to the vendor from whom the motor vehicle fuel was purchased or indirectly by adding the amount of such tax to the price of such fuel: PROVIDED, That no refunds authorized by this section shall be granted on fuel used by any urban transportation vehicle on any trip where any portion of said trip is more than six road miles beyond the corporate limits of the metropolitan municipal corporation in which said trip originated.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c303.pdf?cite=1971%20ex.s.%20c%20303%20§%2010[1971 ex.s. c 303 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c105.pdf?cite=1967%20c%20105%20§%2016[1967 c 105 § 16]; ]

== 35.58.570 - Sewage facilities—Capacity charge.
. A metropolitan municipal corporation that is engaged in the transmission, treatment, and disposal of sewage may impose a capacity charge on users of the metropolitan municipal corporation's sewage facilities when the user connects, reconnects, or establishes a new service to sewer facilities of a city, county, or special district that discharges into the metropolitan facilities. The capacity charge shall be based upon the cost of the sewage facilities' excess capacity that is necessary to provide sewerage treatment for new users to the system.

. The capacity charge is a monthly charge reviewed and approved annually by the metropolitan council. A metropolitan municipal corporation may charge property owners seeking to connect to the sewage facilities of the metropolitan municipal corporation as a condition to granting the right to so connect, in addition to the cost of such connection, such reasonable capacity charge as the legislative body of the metropolitan municipal corporation shall determine proper in order that such property owners shall bear their equitable share of the cost of such system. The equitable share may include interest charges applied from the date of construction of the sewage facilities until the connection, or for a period not to exceed ten years, at a rate commensurate with the rate of interest applicable to the metropolitan municipal corporation at the time of construction or major rehabilitation of the sewage facilities, or at the time of installation of the sewer lines to which the property owner is seeking to connect but not to exceed ten percent per year: PROVIDED, That the aggregate amount of interest shall not exceed the equitable share of the cost of the sewage facilities allocated to such property owners. Capacity charges collected shall be considered revenue of the sewage facilities.

. The council of the metropolitan municipal corporation shall enforce the collection of the capacity charge in the same manner provided for the collection, enforcement, and payment of rates and charges for water-sewer districts provided in RCW 57.08.081. At least thirty days before commencement of an action to foreclose a lien for a capacity charge, the metropolitan municipal corporation shall send written notice of delinquency in payment of the capacity charge to any first mortgage or deed of trust holder of record at the address of record.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2528-S.SL.pdf?cite=2000%20c%20161%20§%201[2000 c 161 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%201602[1996 c 230 § 1602]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c389.pdf?cite=1989%20c%20389%20§%201[1989 c 389 § 1]; ]

== 35.58.580 - Public transportation fares—Proof of payment—Civil infractions.
. Persons traveling on public transportation operated by a metropolitan municipal corporation or a city-owned transit system shall pay the fare established by the metropolitan municipal corporation or the city-owned transit system and shall produce proof of payment in accordance with the terms of use established by the metropolitan municipal corporation or the city-owned transit system. Such persons shall produce proof of payment when requested by a person designated to monitor fare payment. The required manner of producing proof of payment specified in the terms of use established by the metropolitan municipal corporation or the city-owned transit system may include, but is not limited to, requiring a person using an electronic fare payment card to validate the card by presenting the card to an electronic card reader before or upon entering a public transportation vehicle or a restricted fare paid area.

. The following constitute civil infractions punishable according to the schedule of fines and penalties established by a metropolitan municipal corporation or a city-owned transit system under RCW 35.58.585:

.. Failure to pay the required fare, except when a metropolitan municipal corporation or a city-owned transit system under RCW 35.58.585 fails to meet the requirements of subsection (3) of this section;

.. Failure to produce proof of payment in the manner required by the terms of use established by the metropolitan municipal corporation or the city-owned transit system including, but not limited to, the failure to produce a validated fare payment card when requested to do so by a person designated to monitor fare payment; and

.. Failure to depart the bus or other mode of public transportation when requested to do so by a person designated to monitor fare payment.

. If fare payment is required before entering a transit vehicle, as defined in RCW 9.91.025(2)(b), or before entering a fare paid area in a transit facility, as defined in RCW 9.91.025(2)(a), signage must be conspicuously posted at the place of boarding or within ten feet of the nearest entrance to a transit facility that clearly indicates: (a) The locations where tickets or fare media may be purchased; and (b) that a person using an electronic fare payment card must present the card to an electronic card reader before entering a transit vehicle or before entering a restricted fare paid area.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2252-S.SL.pdf?cite=2012%20c%2068%20§%201[2012 c 68 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2480-S.SL.pdf?cite=2008%20c%20123%20§%201[2008 c 123 § 1]; ]

== 35.58.585 - Public transportation fares—Schedule of fines and penalties—Who may monitor fare payment—Administration of citations.
. Both a metropolitan municipal corporation and a city-owned transit system may establish, by resolution, a schedule of fines and penalties for civil infractions established in RCW 35.58.580. Fines established shall not exceed those imposed for class 1 infractions under RCW 7.80.120.

. [Empty]
.. Both a metropolitan municipal corporation and a city-owned transit system may designate persons to monitor fare payment who are equivalent to, and are authorized to exercise all the powers of, an enforcement officer as defined in RCW 7.80.040. Both a metropolitan municipal corporation and a city-owned transit system may employ personnel to either monitor fare payment or contract for such services, or both.

.. In addition to the specific powers granted to enforcement officers under RCW 7.80.050 and 7.80.060, persons designated to monitor fare payment may also take the following actions:

... Request proof of payment from passengers;

... Request personal identification from a passenger who does not produce proof of payment when requested;

... Issue a citation for a civil infraction established in RCW 35.58.580 conforming to the requirements established in RCW 7.80.070, except that the form for the notice of civil infraction must be approved by the administrative office of the courts and must not include vehicle information; and

... Request that a passenger leave the bus or other mode of public transportation when the passenger has not produced proof of payment after being asked to do so by a person designated to monitor fare payment.

. Both a metropolitan municipal corporation and a city-owned transit system shall keep records of citations in the manner prescribed by RCW 7.80.150. All civil infractions established by this section and RCW 35.58.580 and 35.58.590 shall be heard and determined by a district court as provided in RCW 7.80.010 (1) and (4).

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2427-S.SL.pdf?cite=2016%20c%2095%20§%2010[2016 c 95 § 10]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2480-S.SL.pdf?cite=2008%20c%20123%20§%202[2008 c 123 § 2]; ]

== 35.58.590 - Public transportation fares—Powers of law enforcement authorities.
RCW 35.58.580 and 35.58.585 do not prevent law enforcement authorities from prosecuting for theft, trespass, or other charges by any individual who:

. Fails to pay the required fare on more than one occasion within a twelve-month period;

. Fails to timely select one of the options for responding to the notice of civil infraction after receiving a statement of the options for responding to the notice of infraction and the procedures necessary to exercise these options; or

. Fails to depart the bus or other mode of public transportation when requested to do so by a person designated to monitor fare payment.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2480-S.SL.pdf?cite=2008%20c%20123%20§%203[2008 c 123 § 3]; ]

== 35.58.595 - Public transportation fares—Powers and authority are supplemental to other laws.
The powers and authority conferred by RCW 35.58.580 through 35.58.590 shall be construed as in addition and supplemental to powers or authority conferred by any other law, and nothing contained therein shall be construed as limiting any other powers or authority of any public agency.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2480-S.SL.pdf?cite=2008%20c%20123%20§%204[2008 c 123 § 4]; ]

== 35.58.600 - Collaboration with local coordinating coalitions to advance transportation services for persons with special transportation needs.
A municipality, as defined in RCW 35.58.272, and each regional transit authority shall work collaboratively with the appropriate local coordinating coalition or coalitions as described under *RCW 47.06B.070 to advance the coordination of and maximize efficiencies in transportation services provided to persons with special transportation needs as defined in *RCW 47.06B.012.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2072-S.SL.pdf?cite=2009%20c%20515%20§%2013[2009 c 515 § 13]; ]

== 35.58.610 - Supplemental transportation improvements.
If the legislative authority of a city provides or contracts for supplemental transportation improvements, as described in RCW 35.21.925 or under chapter 36.73 RCW, a metropolitan municipal corporation serving the city or border jurisdictions shall coordinate its services with the supplemental transportation improvements to maximize efficiencies in public transportation services within and across service boundaries.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2179-S.SL.pdf?cite=2010%20c%20251%20§%204[2010 c 251 § 4]; ]

== 35.58.900 - Liberal construction.
The rule of strict construction shall have no application to this chapter, but the same shall be liberally construed in all respects in order to carry out the purposes and objects for which this chapter is intended.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.58.900[1965 c 7 § 35.58.900]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c213.pdf?cite=1957%20c%20213%20§%2056[1957 c 213 § 56]; ]

== 35.58.911 - Prior proceedings validated, ratified, approved and confirmed.
All proceedings which have been taken prior to the date *this 1967 amendatory act takes effect for the purpose of financing or aiding in the financing of any work, undertaking or project by any metropolitan municipal corporation, including all proceedings for the authorization and issuance of bonds and for the sale, execution, and delivery thereof, are hereby validated, ratified, approved, and confirmed, notwithstanding any lack of power (other than constitutional) of such metropolitan municipal corporation or the governing body or officers thereof, to authorize and issue such bonds, or to sell, execute, or deliver the same and notwithstanding any defects or irregularities (other than constitutional) in such proceedings.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c105.pdf?cite=1967%20c%20105%20§%2017[1967 c 105 § 17]; ]

