= 35.102 - Municipal business and occupation tax.
:toc:

== 35.102.010 - Findings—Intent.
The legislature finds that businesses in Washington are concerned about the potential for multiple taxation that arises due to the various city business and occupation taxes and are concerned about the lack of uniformity among city jurisdictions. The current system has a negative impact on Washington's business climate. The legislature further finds that local business and occupation tax revenue provides a sizable portion of city revenue that is used for essential services. The legislature recognizes that local government services contribute to a healthy business climate.

The legislature intends to provide for a more uniform system of city business and occupation taxes that eliminates multiple taxation, while allowing for some continued local control and flexibility to cities.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2030.SL.pdf?cite=2003%20c%2079%20§%201[2003 c 79 § 1]; ]

== 35.102.020 - Limited scope—Utility businesses.
Chapter 79, Laws of 2003 does not apply to taxes on any service that historically or traditionally has been taxed as a utility business for municipal tax purposes, such as:

. A light and power business or a natural gas distribution business, as defined in RCW 82.16.010;

. A telephone business, as defined in RCW 82.16.010;

. Cable television services;

. Sewer or water services;

. Drainage services;

. Solid waste services; or

. Steam services.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5089-S.SL.pdf?cite=2007%20c%206%20§%201021[2007 c 6 § 1021]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2030.SL.pdf?cite=2003%20c%2079%20§%202[2003 c 79 § 2]; ]

== 35.102.030 - Definitions.
The definitions in this section apply throughout chapter 79, Laws of 2003, unless the context clearly requires otherwise.

. "Business" has the same meaning as given in chapter 82.04 RCW.

. "City" means a city, town, or code city.

. "Business and occupation tax" or "gross receipts tax" means a tax imposed on or measured by the value of products, the gross income of the business, or the gross proceeds of sales, as the case may be, and that is the legal liability of the business.

. "Value of products" has the same meaning as given in chapter 82.04 RCW.

. "Gross income of the business" has the same meaning as given in chapter 82.04 RCW.

. "Gross proceeds of sales" has the same meaning as given in chapter 82.04 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2030.SL.pdf?cite=2003%20c%2079%20§%203[2003 c 79 § 3]; ]

== 35.102.040 - Model ordinance—Mandatory provisions.
. [Empty]
.. The cities, working through the association of Washington cities, shall form a model ordinance development committee made up of a representative sampling of cities that as of July 27, 2003, impose a business and occupation tax. This committee shall work through the association of Washington cities to adopt a model ordinance on municipal gross receipts business and occupation tax. The model ordinance and subsequent amendments shall be adopted using a process that includes opportunity for substantial input from business stakeholders and other members of the public. Input shall be solicited from statewide business associations and from local chambers of commerce and downtown business associations in cities that levy a business and occupation tax.

.. The department of commerce shall contract to post the model ordinance on an internet web site and to make paper copies available for inspection upon request. The department of revenue and the department of licensing shall post copies of or links to the model ordinance on their internet web sites. Additionally, a city that imposes a business and occupation tax must make copies of its ordinance available for inspection and copying as provided in chapter 42.56 RCW.

.. The definitions and tax classifications in the model ordinance may not be amended more frequently than once every four years, however the model ordinance may be amended at any time to comply with changes in state law. Any amendment to a mandatory provision of the model ordinance must be adopted with the same effective date by all cities.

. A city that imposes a business and occupation tax must adopt the mandatory provisions of the model ordinance. The following provisions are mandatory:

.. A system of credits that meets the requirements of RCW 35.102.060 and a form for such use;

.. A uniform, minimum small business tax threshold of at least the equivalent of twenty thousand dollars in gross income annually. A city may elect to deviate from this requirement by creating a higher threshold or exemption but it shall not deviate lower than the level required in this subsection. If a city has a small business threshold or exemption in excess of that provided in this subsection as of January 1, 2003, and chooses to deviate below the threshold or exemption level that was in place as of January 1, 2003, the city must notify all businesses licensed to do business within the city at least one hundred twenty days prior to the potential implementation of a lower threshold or exemption amount;

.. Tax reporting frequencies that meet the requirements of RCW 35.102.070;

.. Penalty and interest provisions that meet the requirements of RCW 35.102.080 and 35.102.090;

.. Claim periods that meet the requirements of RCW 35.102.100;

.. Refund provisions that meet the requirements of RCW 35.102.110; and

.. Definitions, which at a minimum, must include the definitions enumerated in RCW 35.102.030 and 35.102.120. The definitions in chapter 82.04 RCW shall be used as the baseline for all definitions in the model ordinance, and any deviation in the model ordinance from these definitions must be described by a comment in the model ordinance.

. Except for the deduction required by RCW 35.102.160 and the system of credits developed to address multiple taxation under subsection (2)(a) of this section, a city may adopt its own provisions for tax exemptions, tax credits, and tax deductions.

. Any city that adopts an ordinance that deviates from the nonmandatory provisions of the model ordinance shall make a description of such differences available to the public, in written and electronic form.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2658-S2.SL.pdf?cite=2010%20c%20271%20§%20706[2010 c 271 § 706]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6671-S.SL.pdf?cite=2006%20c%20301%20§%207[2006 c 301 § 7]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1133-S.SL.pdf?cite=2005%20c%20274%20§%20266[2005 c 274 § 266]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2030.SL.pdf?cite=2003%20c%2079%20§%204[2003 c 79 § 4]; ]

== 35.102.050 - Nexus required.
A city may not impose a business and occupation tax on a person unless that person has nexus with the city. For the purposes of this section, the term "nexus" means business activities conducted by a person sufficient to subject that person to the taxing jurisdiction of a city under the standards established for interstate commerce under the commerce clause of the United States Constitution. Mere registration under or compliance with the streamlined sales and use tax agreement does not constitute nexus for the purposes of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3126-S.SL.pdf?cite=2008%20c%20129%20§%204[2008 c 129 § 4]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2030.SL.pdf?cite=2003%20c%2079%20§%205[2003 c 79 § 5]; ]

== 35.102.060 - Multiple taxation—Credit system.
. A city that imposes a business and occupation tax shall provide for a system of credits to avoid multiple taxation as follows:

.. Persons who engage in business activities that are within the purview of more than one classification of the tax shall be taxable under each applicable classification.

.. Notwithstanding anything to the contrary in this section, if imposition of the tax would place an undue burden upon interstate commerce or violate constitutional requirements, a taxpayer shall be allowed a credit only to the extent necessary to preserve the validity of the tax.

.. Persons taxable under the retailing or wholesaling classification with respect to selling products in a city shall be allowed a credit against those taxes for any eligible gross receipts taxes paid by the person (i) with respect to the manufacturing of the products sold in the city, and (ii) with respect to the extracting of the products, or the ingredients used in the products, sold in the city. The amount of the credit shall not exceed the tax liability arising with respect to the sale of those products.

.. Persons taxable under the manufacturing classification with respect to manufacturing products in a city shall be allowed a credit against that tax for any eligible gross receipts tax paid by the person with respect to extracting the ingredients of the products manufactured in the city and with respect to manufacturing the products other than in the city. The amount of the credit shall not exceed the tax liability arising with respect to the manufacturing of those products.

.. Persons taxable under the retailing or wholesaling classification with respect to selling products in a city shall be allowed a credit against those taxes for any eligible gross receipts taxes paid by the person with respect to the printing, or the printing and publishing, of the products sold within the city. The amount of the credit shall not exceed the tax liability arising with respect to the sale of those products.

. The model ordinance shall be drafted to address the issue of multiple taxation for those tax classifications that are in addition to those enumerated in subsection (1)(c) through (e) of this section. The objective of any such provisions shall be to eliminate multiple taxation of the same income by two or more cities.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2030.SL.pdf?cite=2003%20c%2079%20§%206[2003 c 79 § 6]; ]

== 35.102.070 - Reporting frequency.
A city that imposes a business and occupation tax must allow reporting and payment of tax on a monthly, quarterly, or annual basis. The frequency for any particular person may be assigned at the discretion of the city, except that monthly reporting may be assigned only if it can be demonstrated that the taxpayer is remitting excise tax to the state on a monthly basis. For persons assigned a monthly frequency, payment is due within the same time period provided for monthly taxpayers under RCW 82.32.045. For persons assigned a quarterly or annual frequency, payment is due within the same time period as provided for quarterly or annual frequency under RCW 82.32.045. Until December 31, 2020, for persons assigned annual frequency, payment is due on or before the last day of the month next succeeding the end of the period covered by the return. Beginning January 1, 2021, and thereafter, for persons assigned annual frequency, payment is due within the same time period as provided for annual frequency under RCW 82.32.045.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1059-S2.SL.pdf?cite=2019%20c%2063%20§%203[2019 c 63 § 3]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2030.SL.pdf?cite=2003%20c%2079%20§%207[2003 c 79 § 7]; ]

== 35.102.080 - Computation of interest.
. A city that imposes a business and occupation tax shall compute interest charged a taxpayer on an underpaid tax or penalty in accordance with RCW 82.32.050.

. A city that imposes a business and occupation tax shall compute interest paid on refunds or credits of amounts paid or other recovery allowed a taxpayer in accordance with RCW 82.32.060.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2030.SL.pdf?cite=2003%20c%2079%20§%208[2003 c 79 § 8]; ]

== 35.102.090 - Penalties.
A city that imposes a business and occupation tax shall provide for the imposition of penalties in accordance with chapter 82.32 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2030.SL.pdf?cite=2003%20c%2079%20§%209[2003 c 79 § 9]; ]

== 35.102.100 - Claim period.
The provisions relating to the time period allowed for an assessment or correction of an assessment for additional taxes, penalties, or interest shall be in accordance with chapter 82.32 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2030.SL.pdf?cite=2003%20c%2079%20§%2010[2003 c 79 § 10]; ]

== 35.102.110 - Refund period.
The provisions relating to the time period allowed for a refund of taxes paid shall be in accordance with chapter 82.32 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2030.SL.pdf?cite=2003%20c%2079%20§%2011[2003 c 79 § 11]; ]

== 35.102.120 - Definitions—Tax classifications.
. In addition to the definitions in RCW 35.102.030, the following terms and phrases must be defined in the model ordinance under RCW 35.102.040, and such definitions shall include any specific requirements as noted in this subsection:

.. Eligible gross receipts tax.

.. Extracting.

.. Manufacturing. Software development may not be defined as a manufacturing activity.

.. Retailing.

.. Retail sale.

.. Services. The term "services" excludes retail or wholesale services.

.. Wholesale sale.

.. Wholesaling.

.. To manufacture.

.. Commercial and industrial use.

.. Engaging in business.

.. Person.

. Any tax classifications in addition to those enumerated in subsection (1) of this section that are included in the model ordinance must be uniform among all cities.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2030.SL.pdf?cite=2003%20c%2079%20§%2012[2003 c 79 § 12]; ]

== 35.102.130 - Allocation and apportionment of income.
A city that imposes a business and occupation tax must provide for the allocation and apportionment of a person's gross income, other than persons subject to the provisions of chapter 82.14A RCW, as follows:

. Gross income derived from all activities other than those taxed as service or royalties must be allocated to the location where the activity takes place.

.. In the case of sales of tangible personal property, the activity takes place where delivery to the buyer occurs.

.. [Empty]
... In the case of sales of digital products, the activity takes place where delivery to the buyer occurs. The delivery of digital products will be deemed to occur at:

(A) The seller's place of business if the purchaser receives the digital product at the seller's place of business;

(B) If not received at the seller's place of business, the location where the purchaser or the purchaser's donee, designated as such by the purchaser, receives the digital product, including the location indicated by instructions for delivery to the purchaser or donee, known to the seller;

(C) If the location where the purchaser or the purchaser's donee receives the digital product is not known, the purchaser's address maintained in the ordinary course of the seller's business when use of this address does not constitute bad faith;

(D) If no address for the purchaser is maintained in the ordinary course of the seller's business, the purchaser's address obtained during the consummation of the sale, including the address of a purchaser's payment instrument, if no other address is available, when use of this address does not constitute bad faith; and

(E) If no address for the purchaser is obtained during the consummation of the sale, the address where the digital good or digital code is first made available for transmission by the seller or the address from which the digital automated service or service described in RCW 82.04.050 (2)(g) or (6)(c) was provided, disregarding for these purposes any location that merely provided the digital transfer of the product sold.

... If none of the methods in (b)(i) of this subsection (1) for determining where the delivery of digital products occurs are available after a good faith effort by the taxpayer to apply the methods provided in (b)(i)(A) through (E) of this subsection (1), then the city and the taxpayer may mutually agree to employ any other method to effectuate an equitable allocation of income from the sale of digital products. The taxpayer will be responsible for petitioning the city to use an alternative method under this subsection (1)(b)(ii). The city may employ an alternative method for allocating the income from the sale of digital products if the methods provided in (b)(i)(A) through (E) of this subsection (1) are not available and the taxpayer and the city are unable to mutually agree on an alternative method to effectuate an equitable allocation of income from the sale of digital products.

... For purposes of this subsection (1)(b), the following definitions apply:

(A) "Digital automated services," "digital codes," and "digital goods" have the same meaning as in RCW 82.04.192;

(B) "Digital products" means digital goods, digital codes, digital automated services, and the services described in RCW 82.04.050 (2)(g) and (6)(c); and

(C) "Receive" has the same meaning as in RCW 82.32.730.

.. If a business activity allocated under this subsection (1) takes place in more than one city and all cities impose a gross receipts tax, a credit must be allowed as provided in RCW 35.102.060; if not all of the cities impose a gross receipts tax, the affected cities must allow another credit or allocation system as they and the taxpayer agree.

. Gross income derived as royalties from the granting of intangible rights must be allocated to the commercial domicile of the taxpayer.

. Gross income derived from activities taxed as services shall be apportioned to a city by multiplying apportionable income by a fraction, the numerator of which is the payroll factor plus the service-income factor and the denominator of which is two.

.. The payroll factor is a fraction, the numerator of which is the total amount paid in the city during the tax period by the taxpayer for compensation and the denominator of which is the total compensation paid everywhere during the tax period. Compensation is paid in the city if:

... The individual is primarily assigned within the city;

... The individual is not primarily assigned to any place of business for the tax period and the employee performs fifty percent or more of his or her service for the tax period in the city; or

... The individual is not primarily assigned to any place of business for the tax period, the individual does not perform fifty percent or more of his or her service in any city, and the employee resides in the city.

.. The service income factor is a fraction, the numerator of which is the total service income of the taxpayer in the city during the tax period, and the denominator of which is the total service income of the taxpayer everywhere during the tax period. Service income is in the city if the customer location is in the city.

.. Gross income of the business from engaging in an apportionable activity must be excluded from the denominator of the service income factor if, in respect to such activity, at least some of the activity is performed in the city, and the gross income is attributable under (b) of this subsection (3) to a city or unincorporated area of a county within the United States or to a foreign country in which the taxpayer is not taxable. For purposes of this subsection (3)(c), "not taxable" means that the taxpayer is not subject to a business activities tax by that city or county within the United States or by that foreign country, except that a taxpayer is taxable in a city or county within the United States or in a foreign country in which it would be deemed to have a substantial nexus with the city or county within the United States or with the foreign country under the standards in RCW 35.102.050 regardless of whether that city or county within the United States or that foreign country imposes such a tax.

.. If the allocation and apportionment provisions of this subsection (3) do not fairly represent the extent of the taxpayer's business activity in the city, the taxpayer may petition for or the tax administrator may require, in respect to all or any part of the taxpayer's business activity, if reasonable:

... Separate accounting;

... The exclusion of any one or more of the factors;

... The inclusion of one or more additional factors that will fairly represent the taxpayer's business activity in the city; or

... The employment of any other method to effectuate an equitable allocation and apportionment of the taxpayer's income.

.. The party petitioning for, or the tax administrator requiring, the use of any method to effectuate an equitable allocation and apportionment of the taxpayer's income pursuant to subsection (d) of this subsection (3) must prove by a preponderance of the evidence:

... That the allocation and apportionment provisions of this subsection (3) do not fairly represent the extent of the taxpayer's business activity in the city; and

... That the alternative to such provisions is reasonable.

The same burden of proof shall apply whether the taxpayer is petitioning for, or the tax administrator is requiring, the use of an alternative, reasonable method to effectuate an equitable allocation and apportionment of the taxpayer's income.

.. If the tax administrator requires any method to effectuate an equitable allocation and apportionment of the taxpayer's income, the tax administrator cannot impose any civil or criminal penalty with reference to the tax due that is attributable to the taxpayer's reasonable reliance solely on the allocation and apportionment provisions of this subsection (3).

.. A taxpayer that has received written permission from the tax administrator to use a reasonable method to effectuate an equitable allocation and apportionment of the taxpayer's income shall not have that permission revoked with respect to transactions and activities that have already occurred unless there has been a material change in, or a material misrepresentation of, the facts provided by the taxpayer upon which the tax administrator reasonably relied in approving a reasonable alternative method.

. The definitions in this subsection apply throughout this section.

.. "Apportionable income" means the gross income of the business taxable under the service classifications of a city's gross receipts tax, including income received from activities outside the city if the income would be taxable under the service classification if received from activities within the city, less any exemptions or deductions available.

.. "Business activities tax" means a tax measured by the amount of, or economic results of, business activity conducted in a city or county within the United States or within a foreign country. The term includes taxes measured in whole or in part on net income or gross income or receipts. "Business activities tax" does not include a sales tax, use tax, or a similar transaction tax, imposed on the sale or acquisition of goods or services, whether or not denominated a gross receipts tax or a tax imposed on the privilege of doing business.

.. "Compensation" means wages, salaries, commissions, and any other form of remuneration paid to individuals for personal services that are or would be included in the individual's gross income under the federal internal revenue code.

.. "Customer" means a person or entity to whom the taxpayer makes a sale or renders services or from whom the taxpayer otherwise receives gross income of the business.

.. "Individual" means any individual who, under the usual common law rules applicable in determining the employer-employee relationship, has the status of an employee of that taxpayer.

.. "Customer location" means the following:

... For a customer not engaged in business, if the service requires the customer to be physically present, where the service is performed.

... For a customer not engaged in business, if the service does not require the customer to be physically present:

(A) The customer's residence; or

(B) If the customer's residence is not known, the customer's billing/mailing address.

... For a customer engaged in business:

(A) Where the services are ordered from;

(B) At the customer's billing/mailing address if the location from which the services are ordered is not known; or

(C) At the customer's commercial domicile if none of the above are known.

.. "Primarily assigned" means the business location of the taxpayer where the individual performs his or her duties.

.. "Service-taxable income" or "service income" means gross income of the business subject to tax under either the service or royalty classification.

.. "Tax period" means the calendar year during which tax liability is accrued. If taxes are reported by a taxpayer on a basis more frequent than once per year, taxpayers shall calculate the factors for the previous calendar year for reporting in the current calendar year and correct the reporting for the previous year when the factors are calculated for that year, but not later than the end of the first quarter of the following year.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1403-S.SL.pdf?cite=2019%20c%20101%20§%201[2019 c 101 § 1]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5358-S.SL.pdf?cite=2017%20c%20323%20§%20511[2017 c 323 § 511]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2620-S.SL.pdf?cite=2010%20c%20111%20§%20305[2010 c 111 § 305]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2030.SL.pdf?cite=2003%20c%2079%20§%2013[2003 c 79 § 13]; ]

== 35.102.1301 - Municipal business and occupation tax—Study of potential net fiscal impacts.
. The department of revenue shall conduct a study of the net fiscal impacts of chapter 79, Laws of 2003, with particular emphasis on the revenue impacts of the apportionment and allocation method contained in RCW 35.102.130 and any revenue impact resulting from the increased uniformity and consistency provided through the model ordinance. In conducting the study, the department shall use, and regularly consult with, a committee composed of an equal representation from interested business representatives and from a representative sampling of cities imposing business and occupation taxes. The department shall report the final results of the study to the governor and the fiscal committees of the legislature by November 30, 2005. In addition, the department shall provide progress reports to the governor and the fiscal committees of the legislature on November 30, 2003, and November 30, 2004. As part of its report, the department shall examine and recommend options to address any adverse revenue impacts to local jurisdictions.

. For the purposes of this section, "net fiscal impacts" means accounting for the potential of both positive and negative fiscal impacts on local jurisdictions that may result from chapter 79, Laws of 2003.

. It is the intent of the legislature through this study to provide accurate fiscal impact analysis and recommended options to alleviate revenue impacts from chapter 79, Laws of 2003 so as to allow local jurisdictions to anticipate and appropriately address any potential adverse revenue impacts from chapter 79, Laws of 2003.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2030.SL.pdf?cite=2003%20c%2079%20§%2015[2003 c 79 § 15]; ]

== 35.102.140 - Municipal business and occupation tax—Implementation by cities—Contingent authority.
Cities imposing business and occupation taxes must comply with all requirements of RCW 35.102.020 through 35.102.130 by December 31, 2004. A city that has not complied with the requirements of RCW 35.102.020 through 35.102.130 by December 31, 2004, may not impose a tax that is imposed by a city on the privilege of engaging in business activities. Cities imposing business and occupation taxes after December 31, 2004, must comply with RCW 35.102.020 through 35.102.130.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2030.SL.pdf?cite=2003%20c%2079%20§%2014[2003 c 79 § 14]; ]

== 35.102.145 - Municipal business and occupation tax—Confidentiality, privilege, and disclosure.
A city that imposes a business and occupation tax may by ordinance provide that return or tax information is confidential, privileged, and subject to disclosure in the manner provided by RCW 82.32.330.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1597-S2.SL.pdf?cite=2010%20c%20106%20§%20101[2010 c 106 § 101]; ]

== 35.102.150 - Allocation of income—Printing and publishing activities.
Notwithstanding RCW 35.102.130, a city that imposes a business and occupation tax must allocate a person's gross income from the activities of printing, and of publishing newspapers, periodicals, or magazines, to the principal place in this state from which the taxpayer's business is directed or managed. As used in this section, the activities of printing, and of publishing newspapers, periodicals, or magazines are those activities to which the tax rates in RCW * 82.04.260(13) and 82.04.280(1)(a) apply.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5167-S.SL.pdf?cite=2011%20c%20174%20§%20201[2011 c 174 § 201]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6143-S.SL.pdf?cite=2010%201st%20sp.s.%20c%2023%20§%20519[2010 1st sp.s. c 23 § 519]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2122.SL.pdf?cite=2009%20c%20461%20§%204[2009 c 461 § 4]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2033-S.SL.pdf?cite=2006%20c%20272%20§%201[2006 c 272 § 1]; ]

== 35.102.160 - Professional employer organizations—Tax deduction.
. A city that imposes its business and occupation tax on professional employer services performed by a professional employer organization, regardless of the tax classification applicable to such services, shall provide a deduction identical to the deduction in RCW 82.04.540(2).

. For the purposes of this section, "professional employer organization" and "professional employer services" have the same meanings as in RCW 82.04.540.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6671-S.SL.pdf?cite=2006%20c%20301%20§%206[2006 c 301 § 6]; ]

