= 35.105 - Urban forest management.
:toc:

== 35.105.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Community and urban forest assessment" means an analysis of the community and urban forest inventory to: Establish the scope and scale of forest-related benefits and services; determine the economic valuation of such benefits, highlight trends, and issues of concern; identify high priority areas to be addressed; outline strategies for addressing the critical issues and urban landscapes; and identify opportunities for retaining trees, expanding forest canopy, and planting additional trees to sustain Washington's urban and community forests.

. "Community and urban forest inventory" means a management tool designed to gauge the condition, management status, health, and diversity of a community and urban forest. An inventory may evaluate individual trees or groups of trees or canopy cover within community and urban forests, and will be periodically updated by the department of natural resources.

. "Department" means the department of commerce.

. "Evergreen community ordinances" means ordinances adopted by the legislative body of a city, town, or county that relate to urban forests and are consistent with this chapter.

. "Evergreen community" means a city, town, or county designated as such under RCW 35.105.030.

. "Management plan" means an evergreen community urban forest management plan developed pursuant to this chapter.

. "Public facilities" has the same meaning as defined in RCW 36.70A.030.

. "Public forest" means urban forests owned by the state, city, town, county, or other public entity within or adjacent to the urban growth areas.

. "Reforestation" means establishing and maintaining trees and urban forest canopy in plantable spaces such as street rights-of-way, transportation corridors, interchanges and highways, riparian areas, unstable slopes, shorelines, public lands, and property of willing private landowners.

. "Tree canopy" means the layer of leaves, branches, and stems of trees that cover the ground when viewed from above and that can be measured as a percentage of a land area shaded by trees.

. "Urban forest" has the same definition as provided for the term "community and urban forest" in RCW 76.15.010.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2242.SL.pdf?cite=2009%20c%20565%20§%2021[2009 c 565 § 21]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2844-S2.SL.pdf?cite=2008%20c%20299%20§%202[2008 c 299 § 2]; ]

== 35.105.020 - Coordination with department of natural resources.
The department shall, in the implementation of this chapter, coordinate with the department of natural resources. Additionally, in the development of the model evergreen community urban forest management plans and ordinances required by RCW 35.105.050, the department shall utilize the technical expertise of the department of natural resources regarding arboriculture, tree selection, and maintenance.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2844-S2.SL.pdf?cite=2008%20c%20299%20§%206[2008 c 299 § 6]; ]

== 35.105.030 - Evergreen community recognition program.
. The department, with the advice of the evergreen communities partnership task force created in RCW 35.105.110, shall develop the criteria for an evergreen community recognition program whereby the state can recognize cities, towns, and counties, to be designated as an evergreen community, who are developing excellent urban forest management programs that include community and urban forestry inventories, assessments, plans, ordinances, maintenance programs, partnerships, and community involvement.

. [Empty]
.. Designation as an evergreen community must include no fewer than two graduated steps.

.. The first graduated step of designation as an evergreen community includes satisfaction of the following requirements:

... The development and implementation of a tree board or tree department;

... The development of a tree care ordinance;

... The implementation of a community forestry program with an annual budget of at least two dollars for every city resident;

... Official recognition of arbor day; and

.. The completion of an updated community and urban forest inventory for the city, town, or county or the formal adoption of an inventory developed for the city, town, or county by the department of natural resources pursuant to RCW 76.15.070.

.. The second graduated step of designation as an evergreen community includes the adoption of evergreen community management plans and ordinances that exceed the minimum standards in the model evergreen community management plans and ordinances adopted by the department under RCW 35.105.050.

.. The department may require additional graduated steps and establish the minimum requirements for each recognized step.

. The department shall develop gateway signage and logos for an evergreen community.

. The department shall, unless the duty is assumed by the governor, recognize, certify, and designate cities, towns, and counties satisfying the criteria developed under this section as an evergreen community.

. Applications for evergreen community status must be submitted to and evaluated by the department of natural resources.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2844-S2.SL.pdf?cite=2008%20c%20299%20§%207[2008 c 299 § 7]; ]

== 35.105.040 - Evergreen community grant and competitive awards program.
. The department shall, subject to the availability of amounts appropriated for this specific purpose, coordinate with the department of natural resources in the development and implementation of a needs-based evergreen community grant and competitive awards program to provide financial assistance to cities, towns, and counties for the development, adoption, or implementation of evergreen community management plans or ordinances developed under RCW 35.105.090.

. The grant program authorized in this section shall address both the goals of rewarding innovation by a successful evergreen community and of providing resources and assistance to the applicants with the greatest financial need.

. The department may only provide grants to cities, towns, or counties under this chapter that:

.. Are recognized as an evergreen community consistent with RCW 35.105.030, or are applying for funds that would aid them in their pursuit of evergreen community recognition; and

.. Have developed, or are developing urban forest management partnerships with local not-for-profit organizations.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2844-S2.SL.pdf?cite=2008%20c%20299%20§%209[2008 c 299 § 9]; ]

== 35.105.050 - Development of model evergreen community management plans and ordinances.
. To the extent that funds are appropriated for this specific purpose, the department shall develop model evergreen community management plans and ordinances pursuant to RCW 35.105.070 and 35.105.080 with measurable goals and timelines to guide plan and ordinance adoption or development consistent with RCW 35.105.090.

. Model plans and ordinances developed under this section must:

.. Recognize ecoregional differences in the state;

.. Provide flexibility for the diversity of urban character and relative differences in density and zoning found in Washington's cities, towns, and counties;

.. Provide an urban forestland owner inventorying his or her own property with the ability to access existing inventories, technology, and other technical assistance available through the department of natural resources;

.. Recognize and provide for vegetation management practices and programs that prevent vegetation from interfering with or damaging utilities, public facilities, and solar panels or buildings specifically designed to optimize passive solar energy; and

.. Provide for vegetation management practices and programs that reflect and are consistent with the priorities and goals of the growth management act, chapter 36.70A RCW.

. All model plans and ordinances developed by the department must be developed in conjunction with the evergreen communities partnership task force created in RCW 35.105.110.

. After the development of model evergreen community plans and ordinances under this section, the department shall, in conjunction with the department of natural resources, distribute and provide outreach regarding the model plans and ordinances and associated best management practices to cities, towns, and counties to aid the cities, towns, and counties in obtaining evergreen community recognition under RCW 35.105.030.

. By December 1, 2010, the department shall, at a minimum, develop the model evergreen community plans and ordinances required under this section for areas of the state where the department of natural resources has completed community and urban forest inventories pursuant to RCW 76.15.070.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2844-S2.SL.pdf?cite=2008%20c%20299%20§%2010[2008 c 299 § 10]; ]

== 35.105.060 - Report to the legislature.
. The department shall deliver a report to the appropriate committees of the legislature following the development of the model evergreen community management plans and ordinances under RCW 35.105.050 recommending any next steps and additional incentives to increase voluntary participation by cities, towns, and counties in the evergreen community recognition program established in RCW 35.105.030.

. By the fifteenth day of each consecutive December leading up to the adoption of the model evergreen community plans and ordinances, the department shall deliver a report to the appropriate committees of the legislature outlining progress made towards the development and implementation of the model plans and ordinances.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2844-S2.SL.pdf?cite=2008%20c%20299%20§%2011[2008 c 299 § 11]; ]

== 35.105.070 - Model evergreen community management plans—Elements to consider.
In the development of model evergreen community management plans under RCW 35.105.050, the department shall consider including, but not be limited to, the following elements:

. Inventory and assessment of the jurisdiction's urban and community forests utilized as a dynamic management tool to set goals, implement programs, and monitor outcomes that may be adjusted over time;

. Canopy cover goals;

. Reforestation and tree canopy expansion goals within the city's, town's, and county's boundaries;

. Restoration of public forests;

. Achieving forest stand and diversity goals;

. Maximizing vegetated stormwater management with trees and other vegetation that reduces runoff, increases soil infiltration, and reduces stormwater pollution;

. Environmental health goals specific to air quality, habitat for wildlife, and energy conservation;

. Vegetation management practices and programs to prevent vegetation from interfering with or damaging utilities and public facilities;

. Prioritizing planting sites;

. Standards for tree selection, siting, planting, and pruning;

. Scheduling maintenance and stewardship for new and established trees;

. Staff and volunteer training requirements emphasizing appropriate expertise and professionalism;

. Guidelines for protecting existing trees from construction-related damage and damage related to preserving territorial views;

. Integrating disease and pest management;

. Wood waste utilization;

. Community outreach, participation, education programs, and partnerships with nongovernment organizations;

. Time frames for achieving plan goals, objectives, and tasks;

. Monitoring and measuring progress toward those benchmarks and goals;

. Consistency with the urban wildland interface codes developed by the state building code council;

. Emphasizing landscape and revegetation plans in residential and commercial development areas where tree retention objectives are challenging to achieve; and

. Maximizing building heating and cooling energy efficiency through appropriate siting of trees for summer shading, passive solar heating in winter, and for wind breaks.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2844-S2.SL.pdf?cite=2008%20c%20299%20§%2012[2008 c 299 § 12]; ]

== 35.105.080 - Model evergreen community ordinances—Elements to consider.
The department shall, in the development of model evergreen community ordinances under RCW 35.105.050, consider including, but not be limited to, the following policy elements:

. Tree canopy cover, density, and spacing;

. Tree conservation and retention;

. Vegetated stormwater runoff management using native trees and appropriate nonnative, nonnaturalized vegetation;

. Clearing, grading, protection of soils, reductions in soil compaction, and use of appropriate soils with low runoff potential and high infiltration rates;

. Appropriate tree siting and maintenance for vegetation management practices and programs to prevent vegetation from interfering with or damaging utilities and public facilities;

. Native species and nonnative, nonnaturalized species diversity selection to reduce disease and pests in urban forests;

. Tree maintenance;

. Street tree installation and maintenance;

. Tree and vegetation buffers for riparian areas, critical areas, transportation and utility corridors, and commercial and residential areas;

. Tree assessments for new construction permitting;

. Recommended forest conditions for different land use types;

. Variances for hardship and safety;

. Variances to avoid conflicts with renewable solar energy infrastructure, passive solar building design, and locally grown produce; and

. Permits and appeals.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2844-S2.SL.pdf?cite=2008%20c%20299%20§%2013[2008 c 299 § 13]; ]

== 35.105.090 - Evergreen community management plans and ordinances—Local jurisdictions may adopt.
. A city, town, or county may adopt evergreen community management plans and ordinances, including enforcement mechanisms and civil penalties for violations of its evergreen community ordinances.

. Evergreen community ordinances adopted under this section may not prohibit or conflict with vegetation management practices and programs undertaken to prevent vegetation from interfering with or damaging utilities and public facilities.

. Management plans developed by cities, towns, or counties must be based on urban forest inventories for the city, town, or county covered by the management plan. The city, town, or county developing the management plan may produce independent inventories themselves or rely solely on inventories developed, commissioned, or approved by the department of natural resources under chapter 76.15 RCW.

. Cities, towns, or counties may establish a local evergreen community advisory board or utilize existing citizen boards focused on municipal tree issues to achieve appropriate expert and stakeholder participation in the adoption and development of inventories, assessments, ordinances, and plans consistent with this chapter.

. A city, town, or county shall invite the expert advice of utilities serving within its jurisdiction for the purpose of developing and adopting appropriate plans for vegetation management practices and programs to prevent vegetation from interfering with or damaging utilities and public facilities.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2844-S2.SL.pdf?cite=2008%20c%20299%20§%2014[2008 c 299 § 14]; ]

== 35.105.100 - Submission and review of management plans and evergreen community ordinances.
. A city, town, or county seeking evergreen community recognition under RCW 35.105.030 shall submit its management plans and evergreen community ordinances to the department for review and comment at least sixty days prior to its planned implementation date.

. The department shall, together with the department of natural resources, review any evergreen community ordinances or management plans submitted. When reviewing ordinances or plans under this section, the department shall focus its review on the plan's consistency with this chapter and the model evergreen community management plans and ordinances adopted under RCW 35.105.050. When the following entities submit evergreen community ordinances and management plans for review, they must be considered by the department, together with the department of natural resources, the department of fish and wildlife, and the Puget Sound partnership: A county adjacent to Puget Sound or any city located within any of those counties. The reviewing departments may provide written comments on both plans and ordinances.

. Together with the department of natural resources, the department may offer technical assistance in the development of evergreen community ordinances and management plans.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2844-S2.SL.pdf?cite=2008%20c%20299%20§%2016[2008 c 299 § 16]; ]

== 35.105.110 - Evergreen communities partnership task force.
. The director of the department shall assemble and convene the evergreen communities partnership task force of no more than twenty-five individuals to aid and advise the department in the administration of this chapter.

. At the discretion of the department, the task force may be disbanded once the urban and community forests assessments conducted by the department of natural resources under RCW 76.15.070 and the model evergreen community management plans and ordinances developed under RCW 35.105.050 are completed.

. Representatives of the department of natural resources and the department of ecology shall participate in the task force.

. The department shall invite individuals representing the following entities to serve on the task force:

.. A statewide council representing urban and community forestry programs authorized under RCW 76.15.020;

.. A conservation organization with expertise in Puget Sound stormwater management;

.. At least two cities, one from a city east and one from a city west of the crest of the Cascade mountains;

.. At least two counties, one from a county east and one from a county west of the crest of the Cascade mountains;

.. Two land development professionals or representative associations representing development professionals affected by tree retention ordinances and stormwater management policies;

.. A national conservation organization with a network of chapter volunteers working to conserve habitat for birds and wildlife;

.. A land trust conservation organization facilitating urban forest management partnerships;

.. A national conservation organization with expertise in backyard, schoolyard, and community wildlife habitat development;

.. A public works professional;

.. A private utility;

.. A national forestland trust exclusively dedicated to sustaining America's vast and vital private forests and safeguarding their many public benefits;

.. Professionals with expertise in local land use planning, housing, or infrastructure; and

.. The timber industry.

. The department is encouraged to recruit task force members who are able to represent two or more of the stakeholder groups listed in subsection (4) of this section.

. In assembling the task force, the department shall strive to achieve representation from as many of the state's major ecoregions as possible.

. Each member of the task force shall serve without compensation. Task force members that are not state employees may be reimbursed for travel expenses as authorized in RCW 43.03.050 and 43.03.060.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2844-S2.SL.pdf?cite=2008%20c%20299%20§%2017[2008 c 299 § 17]; ]

== 35.105.120 - Limitations of chapter.
Nothing in this chapter may be construed to:

. Conflict or supersede with any requirements, duties, or objectives placed on local governments under chapter 36.70A RCW with specific emphasis on allowing cities and unincorporated urban growth areas to achieve their desired residential densities in a manner and character consistent with RCW 36.70A.110; or

. Apply to lands designated under chapters 76.09, 79.70, 79.71, 84.33, and 84.34 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2844-S2.SL.pdf?cite=2008%20c%20299%20§%2018[2008 c 299 § 18]; ]

