= 35.106 - Crime-free rental housing.
:toc:

== 35.106.005 - Finding—Intent.
The legislature finds that local governments, landlords, and tenants working together to provide crime-free rental housing is beneficial to the public health, safety, and welfare. The legislature is also concerned about activities and provisions that serve to bar a person with a criminal history from obtaining viable housing regardless of other factors that may indicate rental stability, such as employment, rental references, or time in the community with no further criminal activity. It is therefore the intent of chapter 132, Laws of 2010 to provide certain requirements that a local government must follow in adopting a crime-free rental housing program.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5742-S.SL.pdf?cite=2010%20c%20132%20§%201[2010 c 132 § 1]; ]

== 35.106.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Crime-free rental housing program" means a crime prevention program designed to reduce crime, drugs, and gangs on rental housing premises under the supervision of the local police department or a crime prevention officer. The program may include, but is not limited to: Property management and crime prevention training classes; crime prevention through environmental design surveys; and community awareness training.

. "Criminal activity" means a criminal act defined by statute or ordinance that threatens the health, safety, or welfare of the tenants, owner, guests, occupants, or property manager.

. "Local government" means any city, code city, town, or county.

. "Premises" has the same meaning as in RCW 59.18.030.

. "Rental housing" means any tenancy subject to chapter 59.12, 59.18, or 59.20 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5742-S.SL.pdf?cite=2010%20c%20132%20§%202[2010 c 132 § 2]; ]

== 35.106.020 - Crime-free rental housing program.
. [Empty]
.. Except as provided in (b) of this subsection, a local government may adopt and implement a crime-free rental housing program within its jurisdiction in accordance with this chapter.

.. A crime-free rental housing program adopted and implemented by a county is applicable only to unincorporated areas of the county.

. Except as provided in subsection (3) of this section, a crime-free rental housing program must be voluntary.

. [Empty]
.. A local government may require a landlord to participate in a crime-free rental housing program upon exceeding a reasonable threshold of instances of criminal activity on the premises if the landlord has not made a good faith effort to deter the criminal activity.

.. A good faith effort may include, but is not limited to:

... Service of notice on the tenant to comply or quit as allowed by law or the commencement of an unlawful detainer action against the tenant; and

... Attendance and completion of a landlord training program approved by the local government.

. [Empty]
.. As a prerequisite to subsection (3) of this section, upon the occurrence of criminal activity on the premises, the local police department must send a notice to the landlord setting forth the following:

... The date and location of the occurrence;

... The nature of the occurrence; and

... The name of the person who engaged in the occurrence.

.. Notice is deemed properly delivered when it is either served upon the landlord or a property manager of the rental property, or is delivered by first-class mail to the last known address of the landlord.

. This section does not prevent a local government from charging a fee for participation in a crime-free rental housing program.

. This section does not affect a local government's authority to enforce existing law in regard to rental housing, except in regard to a crime-free rental housing program.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5742-S.SL.pdf?cite=2010%20c%20132%20§%203[2010 c 132 § 3]; ]

== 35.106.030 - Program—No prohibition against hiring or renting to person based on criminal history.
A crime-free rental housing program may not prohibit a landlord from hiring or renting to a person solely because of the person's criminal history.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5742-S.SL.pdf?cite=2010%20c%20132%20§%204[2010 c 132 § 4]; ]

== 35.106.100 - Chapter supersedes and preempts local laws—Application of RCW  35.106.020 to local laws.
. Except as provided in subsection (2) of this section, this chapter supersedes and preempts all rules, regulations, codes, statutes, or ordinances of all local governments regarding the same subject matter. The state preemption created in this section applies to all rules, regulations, codes, statutes, and ordinances pertaining to crime-free rental housing programs at any time.

. RCW 35.106.020 does not apply to rules, regulations, codes, statutes, or ordinances adopted by local governments prior to July 1, 2010, except as required by an order issued by a court of competent jurisdiction pursuant to litigation regarding the rules, regulations, codes, statutes, or ordinances.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5742-S.SL.pdf?cite=2010%20c%20132%20§%205[2010 c 132 § 5]; ]

