= 90.54 - Water resources act of 1971.
:toc:

== 90.54.005 - Findings—Objectives—2002 c 329.
The legislature recognizes the critical importance of providing and securing sufficient water to meet the needs of people, farms, and fish. The legislature finds that an effective way to meet the water needs of people, farms, and fish is through strategies developed and implemented at the local watershed level. The objectives of these strategies are to supply water in sufficient quantities to satisfy the following three water resource objectives:

. Providing sufficient water for residential, commercial, and industrial needs;

. Providing sufficient water for productive fish populations; and

. Providing sufficient water for productive agriculture.

The legislature affirms its intent to provide continued support for watershed strategies and provides the tools in chapter 329, Laws of 2002 to assist local watersheds in meeting these objectives.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2993.SL.pdf?cite=2002%20c%20329%20§%201[2002 c 329 § 1]; ]

== 90.54.010 - Purpose.
. The legislature finds that:

.. Proper utilization of the water resources of this state is necessary to the promotion of public health and the economic well-being of the state and the preservation of its natural resources and aesthetic values. Although water is a renewable resource, its supply and availability are becoming increasingly limited, particularly during summer and fall months and dry years when demand is greatest. Growth and prosperity have significantly increased the competition for this limited resource. Adequate water supplies are essential to meet the needs of the state's growing population and economy. At the same time instream resources and values must be preserved and protected so that future generations can continue to enjoy them.

.. All citizens of Washington share an interest in the proper stewardship of our invaluable water resources. To ensure that available water supplies are managed to best meet both instream and offstream needs, a comprehensive planning process is essential. The people of the state have the unique opportunity to work together to plan and manage our water. Through a comprehensive planning process that includes the state, Indian tribes, local governments, and interested parties, it is possible to make better use of available water supplies and achieve better management of water resources. Through comprehensive planning, conflicts among water users and interests can be reduced or resolved. It is in the best interests of the state that comprehensive water resource planning be given a high priority so that water resources and associated values can be utilized and enjoyed today and protected for tomorrow.

.. Diverse hydrologic, climatic, cultural, and socioeconomic conditions exist throughout the regions of the state. Water resource issues vary significantly across regions. Comprehensive water resource planning is best accomplished through a regional planning process sensitive to the unique characteristics and issues of each region.

.. Comprehensive water resource planning must provide interested parties adequate opportunity to participate. Water resource issues are best addressed through cooperation and coordination among the state, Indian tribes, local governments, and interested parties.

.. The long-term needs of the state require ongoing assessment of water availability, use, and demand. A thorough inventory of available resources is essential to water resource management. Current state water resource data and data management is inadequate to meet changing needs and respond to competing water demands. Therefore, a state water resource data program is needed to support an effective water resource management program. Efforts should be made to coordinate and consolidate into one resource data system all relevant information developed by the department of ecology and other agencies relating to the use, protection, and management of the state's water resources.

. It is the purpose of this chapter to set forth fundamentals of water resource policy for the state to insure that waters of the state are protected and fully utilized for the greatest benefit to the people of the state of Washington and, in relation thereto, to provide direction to the department of ecology, other state agencies and officials, and local government in carrying out water and related resources programs. It is the intent of the legislature to work closely with the executive branch, Indian tribes, local government, and interested parties to ensure that water resources of the state are wisely managed.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c295.pdf?cite=1990%20c%20295%20§%201[1990 c 295 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c225.pdf?cite=1971%20ex.s.%20c%20225%20§%201[1971 ex.s. c 225 § 1]; ]

== 90.54.020 - General declaration of fundamentals for utilization and management of waters of the state.
Utilization and management of the waters of the state shall be guided by the following general declaration of fundamentals:

. Uses of water for domestic, stock watering, industrial, commercial, agricultural, irrigation, hydroelectric power production, mining, fish and wildlife maintenance and enhancement, recreational, and thermal power production purposes, and preservation of environmental and aesthetic values, and all other uses compatible with the enjoyment of the public waters of the state, are declared to be beneficial.

. Allocation of waters among potential uses and users shall be based generally on the securing of the maximum net benefits for the people of the state. Maximum net benefits shall constitute total benefits less costs including opportunities lost.

. The quality of the natural environment shall be protected and, where possible, enhanced as follows:

.. Perennial rivers and streams of the state shall be retained with base flows necessary to provide for preservation of wildlife, fish, scenic, aesthetic and other environmental values, and navigational values. Lakes and ponds shall be retained substantially in their natural condition. Withdrawals of water which would conflict therewith shall be authorized only in those situations where it is clear that overriding considerations of the public interest will be served.

.. Waters of the state shall be of high quality. Regardless of the quality of the waters of the state, all wastes and other materials and substances proposed for entry into said waters shall be provided with all known, available, and reasonable methods of treatment prior to entry. Notwithstanding that standards of quality established for the waters of the state would not be violated, wastes and other materials and substances shall not be allowed to enter such waters which will reduce the existing quality thereof, except in those situations where it is clear that overriding considerations of the public interest will be served. Technology-based effluent limitations or standards for discharges for municipal water treatment plants located on the Chehalis, Columbia, Cowlitz, Lewis, or Skagit river shall be adjusted to reflect credit for substances removed from the plant intake water if:

... The municipality demonstrates that the intake water is drawn from the same body of water into which the discharge is made; and

... The municipality demonstrates that no violation of receiving water quality standards or appreciable environmental degradation will result.

. The development of multipurpose water storage facilities shall be a high priority for programs of water allocation, planning, management, and efficiency. The department, other state agencies, local governments, and planning units formed under *section 107 or 108 of this act shall evaluate the potential for the development of new storage projects and the benefits and effects of storage in reducing damage to stream banks and property, increasing the use of land, providing water for municipal, industrial, agricultural, power generation, and other beneficial uses, and improving streamflow regimes for fisheries and other instream uses.

. Adequate and safe supplies of water shall be preserved and protected in potable condition to satisfy human domestic needs.

. Multiple-purpose impoundment structures are to be preferred over single-purpose structures. Due regard shall be given to means and methods for protection of fishery resources in the planning for and construction of water impoundment structures and other artificial obstructions.

. Federal, state, and local governments, individuals, corporations, groups and other entities shall be encouraged to carry out practices of conservation as they relate to the use of the waters of the state. In addition to traditional development approaches, improved water use efficiency, conservation, and use of reclaimed water shall be emphasized in the management of the state's water resources and in some cases will be a potential new source of water with which to meet future needs throughout the state. Use of reclaimed water shall be encouraged through state and local planning and programs with incentives for state financial assistance recognizing programs and plans that encourage the use of conservation and reclaimed water use, and state agencies shall continue to review and reduce regulatory barriers and streamline permitting for the use of reclaimed water where appropriate.

. Development of water supply systems, whether publicly or privately owned, which provide water to the public generally in regional areas within the state shall be encouraged. Development of water supply systems for multiple domestic use which will not serve the public generally shall be discouraged where water supplies are available from water systems serving the public.

. Full recognition shall be given in the administration of water allocation and use programs to the natural interrelationships of surface and groundwaters.

. Expressions of the public interest will be sought at all stages of water planning and allocation discussions.

. Water management programs, including but not limited to, water quality, flood control, drainage, erosion control and storm runoff are deemed to be in the public interest.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6117-S2.SL.pdf?cite=2007%20c%20445%20§%208[2007 c 445 § 8]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2054-S2.SL.pdf?cite=1997%20c%20442%20§%20201[1997 c 442 § 201]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c348.pdf?cite=1989%20c%20348%20§%201[1989 c 348 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c399.pdf?cite=1987%20c%20399%20§%202[1987 c 399 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c225.pdf?cite=1971%20ex.s.%20c%20225%20§%202[1971 ex.s. c 225 § 2]; ]

== 90.54.030 - Water and related resources—Department to be advised—Water resources data program.
For the purpose of ensuring that the department is fully advised in relation to the performance of the water resources program provided in RCW 90.54.040, the department is directed to become informed with regard to all phases of water and related resources of the state. To accomplish this objective the department shall:

. Develop a comprehensive water resource data program that provides the information necessary for effective planning and management on a regional and statewide basis. The data program shall include an information management plan describing the data requirements for effective water resource planning, and a system for collecting and providing access to water resource data on a regional and statewide basis;

. Collect, organize and catalog existing information and studies available to it from all sources, both public and private, pertaining to water and related resources of the state;

. Develop such additional data and studies pertaining to water and related resources as are necessary to accomplish the objectives of this chapter; and

. Develop alternate courses of action to solve existing and foreseeable problems of water and related resources and include therein, to the extent feasible, the economic and social consequences of each such course, and the impact on the natural environment.

All the foregoing shall be included in a "water resources information system" established and maintained by the department. The department shall develop a system of cataloging, storing and retrieving the information and studies of the information system so that they may be made readily available to and effectively used not only by the department but by the public generally.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5029.SL.pdf?cite=1997%20c%2032%20§%201[1997 c 32 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c295.pdf?cite=1990%20c%20295%20§%202[1990 c 295 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c47.pdf?cite=1988%20c%2047%20§%204[1988 c 47 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c225.pdf?cite=1971%20ex.s.%20c%20225%20§%203[1971 ex.s. c 225 § 3]; ]

== 90.54.035 - State funding of water resource programs—Priorities.
. State funding of water resource, supply, and quality related capital programs, both current and future, shall, to the maximum extent possible within state or federal legal requirements, be directed to assist in the resolution of current conflicts and implementation of regional water resource plans with priority given to current needs over new requirements.

. Consistent with RCW 90.54.180, priority shall be given, to the maximum extent possible within state or federal legal requirements, to those water conservation projects funded by the state that will result in the greatest net water savings.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2026-S.SL.pdf?cite=1991%20c%20347%20§%203[1991 c 347 § 3]; ]

== 90.54.040 - Comprehensive state water resources program—Modifying existing and adopting new regulations and statutes.
. The department, through the adoption of appropriate rules, is directed, as a matter of high priority to insure that the waters of the state are utilized for the best interests of the people, to develop and implement in accordance with the policies of this chapter a comprehensive state water resources program which will provide a process for making decisions on future water resource allocation and use. The department may develop the program in segments so that immediate attention may be given to waters of a given physioeconomic region of the state or to specific critical problems of water allocation and use.

. In relation to the management and regulatory programs relating to water resources vested in it, the department is further directed to modify existing regulations and adopt new regulations, when needed and possible, to insure that existing regulatory programs are in accord with the water resource policy of this chapter and the program established in subsection (1) of this section. 

. The department is directed to review all statutes relating to water resources which it is responsible for implementing. When any of the same appear to the department to be ambiguous, unclear, unworkable, unnecessary, or otherwise deficient, it shall make recommendations to the legislature including appropriate proposals for statutory modifications or additions. Whenever it appears that the policies of any such statutes are in conflict with the policies of this chapter, and the department is unable to fully perform as provided in subsection (2) of this section, the department is directed to submit statutory modifications to the legislature which, if enacted, would allow the department to carry out such statutes in harmony with this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5029.SL.pdf?cite=1997%20c%2032%20§%202[1997 c 32 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c47.pdf?cite=1988%20c%2047%20§%205[1988 c 47 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c225.pdf?cite=1971%20ex.s.%20c%20225%20§%204[1971 ex.s. c 225 § 4]; ]

== 90.54.045 - Water resource planning—Pilot process—Report to the legislature.
. In the development and implementation of the comprehensive state water resources program required in RCW 90.54.040(1), the process described therein shall involve participation of appropriate state agencies, Indian tribes, local governments, and interested parties, and shall be applied on a regional basis pursuant to subsection (2) of this section.

. Prior to July 1, 1991, the department, with advice from appropriate state agencies, Indian tribes, local government, and interested parties, shall identify regions and establish regional boundaries for water resource planning and shall designate two regions in which the process shall be initiated on a pilot basis. One region shall encompass an area within the Puget Sound basin in which critical water resource issues exist. A concurrent pilot process may encompass a region east of the Cascade mountains.

. The department shall report to the chairs of the appropriate legislative committees prior to July 1st each year summarizing the progress of the pilot process in the two regions. The pilot process in each region shall be completed and shall produce a regional water plan by December 31, 1993.

. Appropriate state agencies, Indian tribes, local governments, and interested parties in regions not selected for the pilot program are strongly encouraged to commence water resource planning within their regions.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2026-S.SL.pdf?cite=1991%20c%20347%20§%204[1991 c 347 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c295.pdf?cite=1990%20c%20295%20§%203[1990 c 295 § 3]; ]

== 90.54.050 - Setting aside or withdrawing waters—Rules—Consultation with legislative committees—Public hearing, notice—Review.
In conjunction with the programs provided for in RCW 90.54.040(1), whenever it appears necessary to the director in carrying out the policy of this chapter, the department may by rule adopted pursuant to chapter 34.05 RCW:

. Reserve and set aside waters for beneficial utilization in the future, and

. When sufficient information and data are lacking to allow for the making of sound decisions, withdraw various waters of the state from additional appropriations until such data and information are available. Before proposing the adoption of rules to withdraw waters of the state from additional appropriation, the department shall consult with the standing committees of the house of representatives and the senate having jurisdiction over water resource management issues.

Prior to the adoption of a rule under this section, the department shall conduct a public hearing in each county in which waters relating to the rule are located. The public hearing shall be preceded by a notice placed in a newspaper of general circulation published within each of said counties. Rules adopted hereunder shall be subject to review in accordance with the provisions of RCW 34.05.240.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1110-S.SL.pdf?cite=1997%20c%20439%20§%202[1997 c 439 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5029.SL.pdf?cite=1997%20c%2032%20§%203[1997 c 32 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c47.pdf?cite=1988%20c%2047%20§%207[1988 c 47 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c225.pdf?cite=1971%20ex.s.%20c%20225%20§%205[1971 ex.s. c 225 § 5]; ]

== 90.54.060 - Department to seek involvement of other persons and entities, means—Assistance grants.
To insure that all of the various persons and entities having an interest in the water resources of the state and the programs of the chapter are provided with a full opportunity for involvement not only with the development of the program but the implementation by the department under this chapter, the following directions are given:

. The department shall make reasonable efforts to inform the people of the state about the state's water and related resources and their management. The department in the performance of the responsibilities provided in this chapter shall not only invite but actively encourage participation by all persons and private groups and entities showing an interest in water resources programs of this chapter.

. The department shall similarly invite and encourage participation by all agencies of federal, state and local government, including counties, municipal and public corporations, having interests or responsibilities relating to water resources. Said state and local agencies are directed to fully participate to insure that their interests are considered by the department. The department shall, when funds are made available to it for such purposes, provide assistance grants to said state and local agencies for the purposes of financing activities directed to be performed by them under this subsection.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c225.pdf?cite=1971%20ex.s.%20c%20225%20§%206[1971 ex.s. c 225 § 6]; ]

== 90.54.080 - State to vigorously represent its interests before federal agencies, interstate agencies.
The state shall vigorously represent its interest before water resource regulation, management, development, and use agencies of the United States, including among others the federal power commission, environmental protection agency, army corps of engineers, department of the interior, department of agriculture and the atomic energy commission, and of interstate agencies with regard to planning, licensing, relicensing, permit proposals, and proposed construction, development and utilization plans. Where federal or interstate agency plans, activities, or procedures conflict with state water policies, all reasonable steps available shall be taken by the state to preserve the integrity of this state's policies.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c225.pdf?cite=1971%20ex.s.%20c%20225%20§%208[1971 ex.s. c 225 § 8]; ]

== 90.54.090 - State, local governments, municipal corporations to comply with chapter.
All agencies of state and local government, including counties and municipal and public corporations, shall, whenever possible, carry out powers vested in them in manners which are consistent with the provisions of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c505.pdf?cite=1987%20c%20505%20§%2082[1987 c 505 § 82]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977c75.pdf?cite=1977%20c%2075%20§%2095[1977 c 75 § 95]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c225.pdf?cite=1971%20ex.s.%20c%20225%20§%2010[1971 ex.s. c 225 § 10]; ]

== 90.54.100 - Department to evaluate needs for projects and alternative methods of financing.
The department of ecology shall as a matter of high priority evaluate the needs for water resource development projects and the alternative methods of financing of the same by public and private agencies, including financing by federal, state and local governments and combinations thereof. Such evaluations shall be broadly based and be included as a part of the comprehensive state water resources program relating to uses and management as defined in RCW 90.54.030.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5029.SL.pdf?cite=1997%20c%2032%20§%205[1997 c 32 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c225.pdf?cite=1971%20ex.s.%20c%20225%20§%2011[1971 ex.s. c 225 § 11]; ]

== 90.54.110 - Authority to secure and obtain benefits, including grants.
The department of ecology is authorized to obtain the benefits including acceptance of grants, of any program of the federal government or any other source to carry out the provisions of this chapter and is empowered to take such actions as are necessary and appropriate to secure such benefits.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c225.pdf?cite=1971%20ex.s.%20c%20225%20§%2012[1971 ex.s. c 225 § 12]; ]

== 90.54.120 - "Department," "utilize," and "utilization" defined.
For the purposes of this chapter, unless the context is clearly to the contrary, the following definitions shall be used:

. "Department" means department of ecology.

. "Utilize" or "utilization" shall not only mean use of water for such long recognized consumptive or nonconsumptive beneficial purposes as domestic, stock watering, industrial, commercial, agricultural, irrigation, hydroelectric power production, thermal power production, mining, recreational, maintenance of wildlife and fish life purposes, but includes the retention of water in lakes and streams for the protection of environmental, scenic, aesthetic and related purposes, upon which economic values have not been placed historically and are difficult to quantify.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c225.pdf?cite=1971%20ex.s.%20c%20225%20§%2013[1971 ex.s. c 225 § 13]; ]

== 90.54.130 - Land use management policy modifications—Advisory recommendations.
The department of ecology may recommend land use management policy modifications it finds appropriate for the further protection of ground and surface water resources in this state. Such advisory recommendations may be made to other state regulatory agencies, local governments, water systems, and other appropriate bodies.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c253.pdf?cite=1984%20c%20253%20§%204[1984 c 253 § 4]; ]

== 90.54.140 - Protection of groundwater aquifers if sole drinking water source.
The legislature hereby declares that the protection of groundwater aquifers which are the sole drinking water source for a given jurisdiction shall be of the uppermost priority of the state department of ecology, department of social and health services, and all local government agencies with jurisdiction over such areas. In administration of programs related to the disposal of wastes and other practices which may impact such water quality, the department of ecology, department of social and health services, and such affected local agencies shall explore all possible measures for the protection of the aquifer, including any appropriate incentives, penalties, or other measures designed to bring about practices which provide for the least impact on the quality of the groundwater.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c253.pdf?cite=1984%20c%20253%20§%205[1984 c 253 § 5]; ]

== 90.54.150 - Water supply projects—Cooperation with other agencies—Scope of participation.
When feasible, the department of ecology shall cooperate with the United States and other public entities, including Indian tribes, in the planning, development, and operation of comprehensive water supply projects designed primarily to resolve controversies and conflicts over water use by increasing water quantity and improving water quality within a stream or river system, or other bodies of water, as well as to enhance opportunities for both instream and diversionary water uses within the system, and, in relation thereto, the department may:

. Participate with the federal government and other public entities in the planning, development, operation, and management of various phases of water projects hereafter authorized by congress;

. Provide rights to the use of public waters under the state's surface and ground water codes for these projects when the waters are available for allocation; and

. Provide financial assistance through grants and loans for projects when moneys are made available to the department for this assistance by other provisions of this code.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c216.pdf?cite=1979%20ex.s.%20c%20216%20§%209[1979 ex.s. c 216 § 9]; ]

== 90.54.160 - Department to report on dam safety.
The department of ecology shall report to the legislature on the last working day of December of 1984, 1985, and 1986, and thereafter as deemed appropriate by the department, on dam facilities that exhibit safety deficiencies sufficient to pose a significant threat to the safety of life and property. The report shall identify the owner or owners of such facilities, detail the owner's ability and attitude towards correcting such deficiencies, and provide an estimate of the cost of correcting the deficiencies if a study has been completed.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c83.pdf?cite=1984%20c%2083%20§%201[1984 c 83 § 1]; ]

== 90.54.170 - Electric generation facility—Evaluation of application to appropriate water.
In addition to other requirements of this chapter, when the proposed water resource development project involves a new water supply combined with an electric generation facility where such electricity generated may be sold to an entity authorized by law to distribute electricity, the department shall evaluate and utilize, in connection with any application to appropriate water pursuant to the water code, chapter 90.03 RCW, sufficient information furnished by the project applicant regarding the need for the project, alternative means of serving the purposes of the project, the cumulative effects of the project and similar projects that are built, under construction or permitted in the relevant river basin or basins, the impact, if any, on flood control plans and an estimate of the impact, if any, of the sale of the project's electricity on the rates of utility customers of the Bonneville power administration. Such information shall be furnished at the project applicant's own cost and expense.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c444.pdf?cite=1985%20c%20444%20§%206[1985 c 444 § 6]; ]

== 90.54.180 - Water use efficiency and conservation programs and practices.
Consistent with the fundamentals of water resource policy set forth in this chapter, state and local governments, individuals, corporations, groups and other entities shall be encouraged to carry out water use efficiency and conservation programs and practices consistent with the following:

. Water efficiency and conservation programs should utilize an appropriate mix of economic incentives, cost share programs, regulatory programs, and technical and public information efforts. Programs which encourage voluntary participation are preferred.

. Increased water use efficiency and reclaimed water should receive consideration as a potential source of water in state and local water resource planning processes. In determining the cost-effectiveness of alternative water sources, consideration should be given to the benefits of conservation, wastewater recycling, and impoundment of waters. Where reclaimed water is a feasible replacement source of water, it shall be used by state agencies and state facilities for nonpotable water uses in lieu of the use of potable water. For purposes of this requirement, feasible replacement source means (a) the reclaimed water is of adequate quality and quantity for the proposed use; (b) the proposed use is approved by the departments of ecology and health; (c) the reclaimed water can be reliably supplied by a local public agency or public water system; and (d) the cost of the reclaimed water is reasonable relative to the costs of conservation or other potentially available supplies of potable water, after taking into account all costs and benefits, including environmental costs and benefits.

. In determining the cost-effectiveness of alternative water sources, full consideration should be given to the benefits of storage which can reduce the damage to stream banks and property, increase the utilization of land, provide water for municipal, industrial, agricultural, and other beneficial uses, provide for the generation of electric power from renewable resources, and improve streamflow regimes for fishery and other instream uses.

. Entities receiving state financial assistance for construction of water source expansion or acquisition of new sources shall develop, and implement if cost-effective, a water use efficiency and conservation element of a water supply plan pursuant to RCW 43.20.230(1).

. State programs to improve water use efficiency should focus on those areas of the state in which water is overappropriated; areas that experience diminished streamflows or aquifer levels; regional areas that the governor has identified as high priority for investments in improved water quality and quantity, including the Spokane river, the Columbia river basin, and the Puget Sound; areas most likely to be affected by global warming; and areas where projected water needs, including those for instream flows, exceed available supplies.

. Existing and future generations of citizens of the state of Washington should be made aware of the importance of the state's water resources and the need for wise and efficient use and development of this vital resource. In order to increase this awareness, state agencies should integrate public information programs on increasing water use efficiency into existing public information efforts. This effort shall be coordinated with other levels of government, including local governments and Indian tribes.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6117-S2.SL.pdf?cite=2007%20c%20445%20§%209[2007 c 445 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c348.pdf?cite=1989%20c%20348%20§%205[1989 c 348 § 5]; ]

== 90.54.191 - Streamflow restoration a priority.
The department shall prioritize the expenditure of funds and other resources for programs related to streamflow restoration in watersheds where the exercise of inchoate water rights may have a larger effect on streamflows and other water uses.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1338-S2.SL.pdf?cite=2003%201st%20sp.s.%20c%205%20§%2010[2003 1st sp.s. c 5 § 10]; ]

== 90.54.210 - Department shall act on water rights applications that rely on reservations of water established in WAC 173-518-080 or 173-545-090.
. The department shall act on all water rights applications that rely on the reservations of water established in WAC 173-518-080 or 173-545-090, as those provisions existed on March 31, 2016. The legislature declares that the reservations of water established in WAC 173-518-080 and 173-545-090, as those provisions existed on March 31, 2016, are consistent with legislative intent and are specifically authorized to be maintained and implemented by the department.

. This section does not affect the department's authority to lawfully adopt, amend, or repeal any rule, including WAC 173-518-080 or 173-545-090.

. This section may not be construed to prejudice any reservation of water not referenced in this section.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6513-S.SL.pdf?cite=2016%20c%20117%20§%201[2016 c 117 § 1]; ]

== 90.54.800 - Policy guidelines.
Future development of hydropower and protection of river-related resources shall be guided by policies and programs which:

. Create opportunities for balanced development of cost-effective and environmentally sound hydropower projects by a range of development interests;

. Protect significant values associated with the state's rivers, including fish and wildlife populations and habitats, water quality and quantity, unique physical and botanical features, archeological sites, and scenic and recreational resources;

. Protect the interests of the citizens of the state regarding river-related economic development, municipal water supply, supply of electric energy, flood control, recreational opportunity, and environmental integrity;

. Fully utilize the state's authority in the federal hydropower licensing process.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c159.pdf?cite=1989%20c%20159%20§%203[1989 c 159 § 3]; ]

== 90.54.900 - Certain rights, authority, not to be affected by chapter.
Nothing in this chapter shall affect any existing water rights, riparian, appropriative, or otherwise; nor shall it affect existing rights relating to the operation of any hydroelectric or water storage reservoir or related facility; nor shall it affect any exploratory work, construction or operation of a thermal power plant by an electric utility in accordance with the provisions of chapter 80.50 RCW. Nothing in this chapter shall enlarge or reduce the department of ecology's authority to regulate the surface use of waters of this state or structures on the underlying beds, tidelands or shorelands.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c225.pdf?cite=1971%20ex.s.%20c%20225%20§%209[1971 ex.s. c 225 § 9]; ]

== 90.54.910 - Short title.
This chapter shall be known and may be cited as the "Water Resources Act of 1971".

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c225.pdf?cite=1971%20ex.s.%20c%20225%20§%2014[1971 ex.s. c 225 § 14]; ]

== 90.54.920 - Rights not impaired.
. Nothing in this act shall affect or operate to impair any existing water rights.

. Nothing in this act shall be used to prevent future storage options, recognizing that storage may be necessary as a method of conserving water to meet both instream and out-of-stream needs.

. Nothing in this act shall infringe upon the rate-making prerogatives of any public water purveyor.

. Nothing in this act shall preclude the joint select committee on water resource policy from reviewing any subject matter contained herein for any future modifications.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c348.pdf?cite=1989%20c%20348%20§%203[1989 c 348 § 3]; ]

