= 90.74 - Aquatic resources mitigation.
:toc:

== 90.74.005 - Findings—Intent.
. The legislature finds that:

.. The state lacks a clear policy relating to the mitigation of wetlands and aquatic habitat for infrastructure development;

.. Regulatory agencies have generally required project proponents to use compensatory mitigation only at the site of the project's impacts and to mitigate narrowly for the habitat or biological functions impacted by a project;

.. This practice of considering traditional on-site, in-kind mitigation may provide fewer environmental benefits when compared to innovative mitigation proposals that provide benefits in advance of a project's planned impacts and that restore functions or habitat other than those impacted at a project site;

.. Regulatory decisions on development proposals that attempt to incorporate innovative mitigation measures take an unreasonably long period of time and are subject to a great deal of uncertainty and additional expenses; and

.. Greater environmental benefits may be achievable through compensatory environmental mitigation when the collective mitigation investments of project proponents is paired with the structure of successful state programs that are referenced in statute and are designed to enhance and preserve aquatic and riparian functions when there is a clear linkage between the environmental impacts and the goals of the state program. Programs such as the forestry riparian easement program, the family forest fish passage program, and the riparian open space program created pursuant to RCW 76.09.040 may have a logical and physical nexus with many underlying projects, especially road projects, and are proven to create a sustained benefit in the aquatic environment.

. The legislature therefore declares that it is the policy of the state to authorize innovative mitigation measures by requiring state regulatory agencies to consider mitigation proposals for projects that are timed, designed, and located in a manner to provide equal or better biological functions and values compared to traditional on-site, in-kind mitigation proposals.

. It is the intent of the legislature to authorize local governments to accommodate the goals of this chapter. It is not the intent of the legislature to: (a) Restrict the ability of a project proponent to pursue project specific mitigation; or (b) create any new authority for regulating wetlands or aquatic habitat beyond what is specifically provided for in this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2238-S2.SL.pdf?cite=2012%20c%2062%20§%202[2012 c 62 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5273-S.SL.pdf?cite=1997%20c%20424%20§%201[1997 c 424 § 1]; ]

== 90.74.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Compensatory mitigation" means the restoration, creation, enhancement, or preservation of uplands, wetlands, or other aquatic resources for the purposes of compensating for unavoidable adverse impacts that remain after all appropriate and practicable avoidance and minimization has been achieved. "Compensatory mitigation" includes mitigation that:

.. Occurs at the same time as, or in advance of, a project's planned environmental impacts;

.. Is located in a site either on, near, or distant from the project's impacts; and

.. Provides either the same or different biological functions and values as the functions and values impacted by the project.

. "Family forest fish passage program" means the program administered by the recreation and conservation office created pursuant to RCW 76.09.410 that provides public cost assistance to small forestland owners associated with the road maintenance and abandonment processes.

. "Forestry riparian easement program" means the program established in RCW 76.13.120.

. "Infrastructure development" means an action that is critical for the maintenance or expansion of an existing infrastructure feature such as a highway, rail line, airport, marine terminal, utility corridor, harbor area, or hydroelectric facility and is consistent with an approved land use planning process. This planning process may include the growth management act, chapter 36.70A RCW, or the shoreline management act, chapter 90.58 RCW, in areas covered by those chapters.

. "Mitigation" means sequentially avoiding impacts, minimizing impacts, or compensating for remaining unavoidable impacts.

. "Mitigation plan" means a document or set of documents developed through joint discussions between a project proponent and environmental regulatory agencies that describe the unavoidable wetland or aquatic resource impacts of a proposed infrastructure development or noninfrastructure development and the proposed compensatory mitigation for those impacts.

. "Noninfrastructure development" means a development project that requires the completion of compensatory mitigation that does not meet the definition of "infrastructure development" and is consistent with an approved land use planning process. This planning process may include the growth management act, chapter 36.70A RCW, or the shoreline management act, chapter 90.58 RCW, in areas covered by those chapters.

. "Project proponent" means a public or private entity responsible for preparing a mitigation plan.

. "Riparian open space program" means the program created pursuant to RCW 76.09.040.

. "Watershed" means an area identified as a state of Washington water resource inventory area under WAC 173-500-040 as it exists on June 7, 2012.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2238-S2.SL.pdf?cite=2012%20c%2062%20§%203[2012 c 62 § 3]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5273-S.SL.pdf?cite=1997%20c%20424%20§%202[1997 c 424 § 2]; ]

== 90.74.020 - Mitigation plans.
. Project proponents may use a mitigation plan to propose compensatory mitigation within a watershed. A mitigation plan shall:

.. Contain provisions that guarantee the long-term viability of the created, restored, enhanced, or preserved habitat, including assurances for protecting any essential biological functions and values defined in the mitigation plan;

.. Contain provisions for long-term monitoring of any created, restored, or enhanced mitigation site; and

.. Be consistent with the local comprehensive land use plan and any other applicable planning process in effect for the development area, such as an adopted subbasin or watershed plan.

. [Empty]
.. The departments of ecology and fish and wildlife may not limit the scope of options in a mitigation plan to areas on or near the project site, or to habitat types of the same type as contained on the project site. The departments of ecology and fish and wildlife shall fully review and give due consideration to compensatory mitigation proposals that improve the overall biological functions and values of the watershed or bay and accommodate the mitigation needs of the infrastructure development or noninfrastructure development, including proposals or portions of proposals that are explored or developed in RCW 90.74.040.

.. The departments of ecology and fish and wildlife are not required to grant approval to a mitigation plan that the departments find does not provide equal or better biological functions and values within the watershed or bay.

. When making a permit or other regulatory decision under the guidance of this chapter, the departments of ecology and fish and wildlife shall consider whether the mitigation plan provides equal or better biological functions and values, compared to the existing conditions, for the target resources or species identified in the mitigation plan. This consideration shall be based upon the following factors:

.. The relative value of the mitigation for the target resources, in terms of the quality and quantity of biological functions and values provided;

.. The compatibility of the proposal with the intent of broader resource management and habitat management objectives and plans, such as existing resource management plans, watershed plans, critical areas ordinances, the forestry riparian easement program, the riparian open space program, the family forest fish passage program, and shoreline master programs;

.. The ability of the mitigation to address scarce functions or values within a watershed;

.. The benefits of the proposal to broader watershed landscape, including the benefits of connecting various habitat units or providing population-limiting habitats or functions for target species;

.. The benefits of early implementation of habitat mitigation for projects that provide compensatory mitigation in advance of the project's planned impacts; and

.. The significance of any negative impacts to nontarget species or resources.

. A mitigation plan may be approved through a memorandum of agreement between the project proponent and either the department of ecology or the department of fish and wildlife, or both.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2238-S2.SL.pdf?cite=2012%20c%2062%20§%204[2012 c 62 § 4]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5273-S.SL.pdf?cite=1997%20c%20424%20§%203[1997 c 424 § 3]; ]

== 90.74.030 - Regulatory decisions, guidance—Multiple requests for review of mitigation plans.
. In making regulatory decisions relating to wetland or aquatic resource mitigation, the departments of ecology and fish and wildlife shall, at the request of the project proponent, follow the guidance of this chapter.

. If the department of ecology or the department of fish and wildlife receives multiple requests for review of mitigation plans, each department may schedule its review of these proposals to conform to available budgetary resources.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2238-S2.SL.pdf?cite=2012%20c%2062%20§%207[2012 c 62 § 7]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5273-S.SL.pdf?cite=1997%20c%20424%20§%204[1997 c 424 § 4]; ]

== 90.74.040 - Developing new programs/using existing programs to mitigate for environmental impacts—Departments authorized to seek funds.
. [Empty]
.. To the degree that resources are deemed available by the affected departments, the department of ecology and the department of fish and wildlife shall allow, when appropriate, programs that are related to environmental mitigation, or explore the potential of developing new programs, to utilize the forestry riparian easement program, the riparian open space program, or the family forest fish passage program to mitigate for environmental impacts from projects conducted in the state where compatible with existing regulations. The use of these programs may not be additive to existing compensatory mitigation requirements.

.. In implementing this subsection, the department of natural resources may be used as a resource, consistent with RCW 76.09.480, to assist in identifying potential projects that can be used for the mitigation of infrastructure and noninfrastructure development.

. The department of ecology and the department of fish and wildlife are authorized to seek federal or private funds and in-kind contributions to implement this section. The scope of effort in implementing this section may be defined by the success of the department of ecology and the department of fish and wildlife in securing specific funding.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2238-S2.SL.pdf?cite=2012%20c%2062%20§%205[2012 c 62 § 5]; ]

