= 90.88 - Aquatic rehabilitation zones.
:toc:

== 90.88.005 - Findings—Intent.
. The legislature finds that Hood Canal is a precious aquatic resource of our state. The legislature finds that Hood Canal is a rich source of recreation, fishing, aquaculture, and aesthetic enjoyment for the citizens of this state. The legislature also finds that Hood Canal has great cultural significance for the tribes in the Hood Canal area. The legislature therefore recognizes Hood Canal's substantial environmental, cultural, economic, recreational, and aesthetic importance in this state.

. The legislature finds that Hood Canal is a marine water of the state at significant risk. The legislature finds that Hood Canal has a "dead zone" related to low-dissolved oxygen concentrations, a condition that has recurred for many years. The legislature also finds that this problem and various contributors to the problem were documented in the May 2004 Preliminary Assessment and Corrective Action Plan published by the state agency known as the Puget Sound action team and the Hood Canal coordinating council.

. The legislature further finds that significant research, monitoring, and study efforts are currently occurring regarding Hood Canal's low-dissolved oxygen concentrations. The legislature also finds numerous public, private, and community organizations are working to provide public education and identify potential solutions. The legislature recognizes that, while some information and research is now available and some potential solutions have been identified, more research and analysis is needed to fully develop a program to address Hood Canal's low-dissolved oxygen concentrations.

. The legislature finds a need exists for the state to take action to address Hood Canal's low-dissolved oxygen concentrations. The legislature also finds establishing an aquatic rehabilitation zone for Hood Canal will serve as a statutory framework for future regulations and programs directed at recovery of this important aquatic resource.

. The legislature therefore intends to establish an aquatic rehabilitation zone for Hood Canal as the framework to address Hood Canal's low-dissolved oxygen concentrations. The legislature also intends to incorporate provisions in the new statutory chapter creating the designation as solutions are identified regarding this problem.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5372-S.SL.pdf?cite=2007%20c%20341%20§%2050[2007 c 341 § 50]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2081-S.SL.pdf?cite=2005%20c%20478%20§%201[2005 c 478 § 1]; ]

== 90.88.010 - Designation by the legislature—Zone one established.
. Aquatic rehabilitation zones may be designated by the legislature for areas whose surrounding marine water bodies pose serious environmental or public health concerns.

. Aquatic rehabilitation zone one is established. Aquatic rehabilitation zone one includes all watersheds that drain to Hood Canal south of a line projected from Tala Point in Jefferson county to Foulweather Bluff in Kitsap county.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2081-S.SL.pdf?cite=2005%20c%20478%20§%202[2005 c 478 § 2]; ]

== 90.88.020 - Hood Canal rehabilitation program—State lead agency—Local management board.
. The development of a program for rehabilitation of Hood Canal is authorized in Jefferson, Kitsap, and Mason counties within the aquatic rehabilitation zone one.

. The Puget Sound partnership, created in RCW 90.71.210, is designated as the state lead agency for the rehabilitation program authorized in this section.

. The Hood Canal coordinating council is designated as the local management board for the rehabilitation program authorized in this section.

. The Puget Sound partnership and the Hood Canal coordinating council must each approve and must comanage projects under the rehabilitation program authorized in this section.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5372-S.SL.pdf?cite=2007%20c%20341%20§%2051[2007 c 341 § 51]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2097-S.SL.pdf?cite=2005%20c%20479%20§%202[2005 c 479 § 2]; ]

== 90.88.030 - Aquatic zone one—Roles of Hood Canal coordinating council and Puget Sound partnership—Participation of governments and nonprofit organizations—Project funding, priorities, and criteria—Reports.
. The Hood Canal coordinating council shall serve as the local management board for aquatic rehabilitation zone one. The local management board shall coordinate local government efforts with respect to the program authorized according to RCW 90.88.020. In the Hood Canal area, the Hood Canal coordinating council also shall:

.. Serve as the lead entity and the regional recovery organization for the purposes of chapter 77.85 RCW for Hood Canal summer chum; and

.. Assist in coordinating activities under chapter 90.82 RCW.

. When developing and implementing the program authorized in RCW 90.88.020 and when establishing funding criteria according to subsection (7) of this section, the Puget Sound partnership, created in RCW 90.71.210, and the local management board shall solicit participation by federal, tribal, state, and local agencies and universities and nonprofit organizations with expertise in areas related to program activities. The local management board may include state and federal agency representatives, or additional persons, as nonvoting management board members or may receive technical assistance and advice from them in other venues. The local management board also may appoint technical advisory committees as needed.

. The local management board and the Puget Sound partnership shall participate in the development of the program authorized under RCW 90.88.020.

. The local management board and its participating local and tribal governments shall assess concepts for a regional governance structure and shall submit a report regarding the findings and recommendations to the appropriate committees of the legislature by December 1, 2007.

. Any of the local management board's participating counties and tribes, any federal, tribal, state, or local agencies, or any universities or nonprofit organizations may continue individual efforts and activities for rehabilitation of Hood Canal. Nothing in this section limits the authority of units of local government to enter into interlocal agreements under chapter 39.34 RCW or any other provision of law.

. The local management board may not exercise authority over land or water within the individual counties or otherwise preempt the authority of any units of local government.

. The local management board and the Puget Sound partnership each may receive and disburse funding for projects, studies, and activities related to Hood Canal's low-dissolved oxygen concentrations. The Puget Sound partnership and the local management board shall jointly coordinate a process to prioritize projects, studies, and activities for which the Puget Sound partnership receives state funding specifically allocated for Hood Canal corrective actions to implement this section. The local management board and the Puget Sound partnership shall establish criteria for funding these projects, studies, and activities based upon their likely value in addressing and resolving Hood Canal's low-dissolved oxygen concentrations. Final approval for projects under this section requires the consent of both the Puget Sound partnership and the local management board. Projects under this section must be comanaged by the Puget Sound partnership and the local management board. Nothing in this section prohibits any federal, tribal, state, or local agencies, universities, or nonprofit organizations from receiving funding for specific projects that may assist in the rehabilitation of Hood Canal.

. The local management board may hire and fire staff, including an executive director, enter into contracts, accept grants and other moneys, disburse funds, make recommendations to local governments about potential regulations and the development of programs and incentives upon request, pay all necessary expenses, and choose a fiduciary agent.

. The local management board shall report its progress on a quarterly basis to the legislative bodies of the participating counties and tribes and the participating state agencies. The local management board also shall submit an annual report describing its efforts and successes in implementing the program established according to RCW 90.88.020 to the appropriate committees of the legislature.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5372-S.SL.pdf?cite=2007%20c%20341%20§%2052[2007 c 341 § 52]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2097-S.SL.pdf?cite=2005%20c%20479%20§%203[2005 c 479 § 3]; ]

== 90.88.040 - Forest practices—Nonapplicability of chapter.
This chapter does not apply to forest practices regulated under chapter 76.09 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2081-S.SL.pdf?cite=2005%20c%20478%20§%203[2005 c 478 § 3]; ]

== 90.88.050 - Scope of chapter.
This chapter does not alter, diminish, or expand the jurisdictional authorities in other statutes or affect the application of other statutory requirements or programs that do not specifically refer to aquatic rehabilitation zones.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2081-S.SL.pdf?cite=2005%20c%20478%20§%204[2005 c 478 § 4]; ]

== 90.88.900 - Effective date—2005 c 478.
This act is necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and takes effect immediately [May 16, 2005].

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2081-S.SL.pdf?cite=2005%20c%20478%20§%206[2005 c 478 § 6]; ]

== 90.88.901 - Regulatory authority not conferred.
Nothing in chapter 479, Laws of 2005 provides any regulatory authority to the Puget Sound partnership, created in RCW 90.71.210, or the Hood Canal coordinating council.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5372-S.SL.pdf?cite=2007%20c%20341%20§%2053[2007 c 341 § 53]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2097-S.SL.pdf?cite=2005%20c%20479%20§%205[2005 c 479 § 5]; ]

== 90.88.902 - Activities subject to appropriations.
The activities of the Puget Sound partnership, created in RCW 90.71.210, and the Hood Canal coordinating council required by chapter 479, Laws of 2005 are subject to the availability of amounts appropriated for this specific purpose.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5372-S.SL.pdf?cite=2007%20c%20341%20§%2054[2007 c 341 § 54]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2097-S.SL.pdf?cite=2005%20c%20479%20§%206[2005 c 479 § 6]; ]

== 90.88.903 - Effective date—2005 c 479.
This act is necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and takes effect immediately [May 16, 2005].

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2097-S.SL.pdf?cite=2005%20c%20479%20§%208[2005 c 479 § 8]; ]

