= 90.86 - Joint legislative committee on water supply during drought.
:toc:

== 90.86.010 - Joint legislative committee on water supply during drought.
The joint legislative committee on water supply during drought is created.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2166.SL.pdf?cite=2005%20c%2060%20§%201[2005 c 60 § 1]; ]

== 90.86.020 - Membership.
The committee shall consist of four senators and four representatives who shall be selected biennially as follows:

. The president of the senate shall appoint four members from the senate to serve on the committee, including the chair of the committee responsible for water resource issues. Two members from each major political party must be appointed.

. The speaker of the house of representatives shall appoint four members from the house of representatives to serve on the committee, including the chair of the committee responsible for water resource issues. Two members from each major political party must be appointed.

. The committee shall elect a chair and a vice chair. The chair shall be a member of the house of representatives in even-numbered years and a member of the senate in odd-numbered years.

. The presiding officer of the appropriate legislative chamber shall fill any vacancies occurring on the committee by appointment from the same political party as the departing member.

. Members shall serve until their successors are appointed as provided in this section, or until they are no longer members of the legislature, whichever is sooner.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2166.SL.pdf?cite=2005%20c%2060%20§%202[2005 c 60 § 2]; ]

== 90.86.030 - Meetings—Requests for information—Reports from department of ecology—Recommendations to the legislature.
. The joint legislative committee on water supply during drought shall convene from time to time at the call of the chair when a drought conditions order under RCW 43.83B.405 is in effect, or when the chair determines, in consultation with the department of ecology, that it is likely that such an order will be issued within the next year.

. The committee may request and review information relating to water supply conditions in the state, and economic, environmental, and other impacts relating to decreased water supply being experienced or anticipated. The governor's executive water emergency committee, the department of ecology, and other state agencies with water management or related responsibilities shall cooperate in responding to requests from the committee.

. During drought conditions in which an order issued under RCW 43.83B.405 is in effect, the department of ecology shall provide to the committee no less than monthly a report describing drought response activities of the department and other state and federal agencies participating on the water supply availability committee. The report shall include information regarding applications for, and approvals and denials of emergency water withdrawals and temporary changes or transfers of, water rights under RCW 43.83B.410.

. The committee from time to time shall make recommendations to the senate and house of representatives on budgetary and legislative actions that will improve the state's drought response programs and planning.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2617-S2.SL.pdf?cite=2010%201st%20sp.s.%20c%207%20§%20122[2010 1st sp.s. c 7 § 122]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2166.SL.pdf?cite=2005%20c%2060%20§%203[2005 c 60 § 3]; ]

== 90.86.900 - Effective date—2005 c 60.
This act is necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and takes effect immediately [April 14, 2005].

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2166.SL.pdf?cite=2005%20c%2060%20§%205[2005 c 60 § 5]; ]

