= 90.92 - Pilot local water management program.
:toc:

== 90.92.010 - Findings. (Expires June 30, 2021.)
The legislature finds that participants in the Walla Walla watershed pilot program have demonstrated exceptional cooperation in developing and implementing an innovative water management concept that enhances flexibility in water use since convening in 2009. The legislature further finds that the existing authorities and structure of the pilot program must evolve to meet the growing water resource demands in the Walla Walla watershed and to protect and enhance ecological functions. As the next step in the process, the legislature intends to extend the Walla Walla pilot program through June 30, 2021, to allow the pilot to perform internal and external evaluations, build upon previous pilot program efforts, continue Walla Walla river flow enhancement technical work, and restructure this chapter to develop a thirty-year integrated water resource management strategic plan. The legislature continues to recognize the significant contribution of former state representative William Grant's leadership in the creation of a Walla Walla pilot design to authorize local water management activity.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5352-S2.SL.pdf?cite=2019%20c%2078%20§%201[2019 c 78 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1580-S2.SL.pdf?cite=2009%20c%20183%20§%201[2009 c 183 § 1]; ]

== 90.92.020 - Definitions. (Expires June 30, 2021.)
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Basin" means the WRIA where the planning area is located.

. "Board" means a water management board created under this chapter.

. "Department" means the department of ecology.

. "Director" means the director of the department of ecology.

. "Initiating entities" means the county boards of commissioners within the planning area, the city council of the largest Washington city in the planning area, the largest water user in the planning area, and all affected federally recognized tribes within the planning area.

. "Instream flow" means a minimum flow under chapter 90.03 or 90.22 RCW or a base flow under chapter 90.54 RCW that has been set by rule.

. "Local water management program" means the water banking mechanism, any local water plans authorized by the board, and any other activities authorized by RCW 90.92.050.

. "Local water plan" means a voluntary water management plan developed by local water rights holders within the planning area to manage their water use in a manner that enhances streamflows in exchange for greater flexibility in exercising the water rights.

. "Planning area" means the entirety or a subsection of a single or multiple WRIA as identified in the creation of a board under this chapter.

. "Trust water right" means any water right acquired by the state under chapter 90.42 RCW for management in the state's [trust] water rights program.

. "Watershed plan" means a plan adopted under chapter 90.82 RCW.

. "WRIA" means a water resource inventory area established in chapter 173-500 WAC as it existed on January 1, 1997.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1580-S2.SL.pdf?cite=2009%20c%20183%20§%202[2009 c 183 § 2]; ]

== 90.92.030 - Establishing a water management board. (Expires June 30, 2021.)
. Initiating entities may collectively petition the department in order to establish a water management board.

. The department, in consultation with the initiating entities, may create a board if:

.. The initiating entities demonstrate to the department that the following criteria are satisfied:

... Community support for the development of a local watershed management plan, including the affected federally recognized tribes, local governments, and general community support;

... There is commitment on the part of the initiating entities and the affected community to enhance streamflows for fish; and

... An adequate monitoring network is in place, as determined by the department;

.. The department determines the following:

... An instream flow rule for the WRIA or WRIAs in the planning area has been adopted since 1998;

... The planning area is located within one of the sixteen fish-critical basins designated by the department in its March 2003 "Washington Water Acquisition Program" report and demonstrates a significant history of severely impaired flows; and

... The watershed planning unit has completed a watershed implementation plan adopted under chapter 90.82 RCW and salmon recovery implementation plan adopted under chapter 77.85 RCW.

. The department, in determining whether to create a board, must give strong consideration to basins that have completed a judicial proceeding to adjudicate water rights under chapter 90.03 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1580-S2.SL.pdf?cite=2009%20c%20183%20§%203[2009 c 183 § 3]; ]

== 90.92.040 - Composition of board—Members' terms—Policy advisory group—Conflicts of interest. (Expires June 30, 2021.)
. [Empty]
.. Each board must be composed of the following members:

... All affected federally recognized tribes within the planning area will be invited to participate and may appoint one member each;

... The following entities must each appoint one member:

(A) Each county board of commissioners within the planning area;

(B) The city council of the largest Washington city in the planning area; and

(C) The board of directors of the entity or the person who uses the greatest quantity of water in the planning area;

... The conservation districts' board of supervisors in the planning area must jointly appoint one member; and

... The members under (a)(i) through (iii) of this subsection must appoint the remaining three members of the board. These three members must be residents of the planning area. One member must be a planning area water rights holder. One member must represent environmental interests in the planning area. One member must be a citizen at large.

.. If for any reason one of the required governments or entities to be represented on the board declines to participate, the remaining board members may invite another local government within the planning area to join the board.

. Each member of the board serves a two-year term and may be reappointed for an additional term. Members may continue to serve on the board until a new appointment is made.

. The board must create a policy advisory group and a water resource panel.

.. For the policy advisory group, the board must invite participation from the department and the department of fish and wildlife, other affected state agencies, and other interests as appropriate. The board may also appoint members from local government agencies, academia, watershed and salmon recovery entities, businesses, and agricultural and environmental organizations as the board deems appropriate.

.. The policy advisory group must assist and advise the board in coordinating and developing water resource-related programs, planning, and activities within the planning area, including the coordination of efforts with all jurisdictions of the planning area and development of the board's strategic actions.

.. For the water resource panel, the board must appoint members to the water resource panel who have expertise and understanding regarding surface water and groundwater monitoring and hydrological analysis, irrigation management and engineering, water rights, and fisheries habitat and economic development. The board must invite participation from the department and the department of fish and wildlife.

.. The water resource panel must provide technical assistance for the development of the local water plans and provide advice to the board on the criteria for establishment of local water plans and the approval, denial, or modification of the local water plans.

. A board member, employee, or contractor may not engage in any act that is in conflict with the proper discharge of their official duties. Such conflicts of interest include, but are not limited to, holding a financial interest in a matter before the board.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1580-S2.SL.pdf?cite=2009%20c%20183%20§%204[2009 c 183 § 4]; ]

== 90.92.050 - Board's authorities, duties, and responsibilities. (Expires June 30, 2021.)
. The board has the following authority, duties, and responsibilities:

.. Assume the duties, responsibilities, and all current activities of the watershed planning unit and the initiating governments authorized in RCW 90.82.040;

.. Develop strategic actions for the planning area by building on the watershed plan;

.. Adopt and revise criteria, guidance, and processes to effectuate the purpose of this chapter;

.. Administer the local water plan process;

.. Oversee local water plan implementation;

.. Manage banked water as authorized under this chapter;

.. Acquire water rights by donation, purchase, or lease;

.. Participate in local, state, tribal, federal, and multistate basin water planning initiatives and programs; and

.. Enter into agreements with water rights holders to not divert water that becomes available as a result of local water plans, water banking activities, or other programs and projects endorsed by the board and the department.

. During the transition period of July 1, 2019, to June 30, 2021, the board shall:

.. Participate with the department to complete, by June 30, 2020, a performance audit conducted by the state auditor's office within existing resources, and a financial audit funded with existing department resources, to evaluate the Walla Walla pilot program since 2008 and to incorporate audit findings and recommendations into a thirty-year integrated water resource management strategy;

.. Continue working with the department, the Confederated Tribes of the Umatilla Indian Reservation, and other participants to advance the Walla Walla basin flow enhancement study and its recommendation, including any necessary environmental reviews for near-term actions;

.. Collaborate with the department in the development of a thirty-year integrated water resource management strategic plan, including a draft and final programmatic environmental impact statement, and explore interstate agreements to maximize integrated water resource management;

.. By November 1, 2020, jointly develop with the department a report to the legislature recommending the scope and scale of an integrated water resource management strategic plan, including a funding approach and organization structure, to achieve the desired outcome of improved and sustainable flows for fish, adequate water supplies for agriculture, municipal, and domestic water users, and improved habitat and floodplain functionality in the Walla Walla watershed; and

.. Coordinate with the department's office of Columbia river to request funding to complete tasks required during the transition period.

. The board may acquire, purchase, hold, lease, manage, occupy, and sell real and personal property, including water rights, or any interest in water rights, enter into and perform all necessary contracts, appoint and employ necessary agents and employees, including an executive director and fix their compensation, employ contractors including contracts for professional services, and do all lawful acts required and expedient to carry out the purposes of this chapter.

. The board constitutes an independently funded entity, and may provide for its own funding as determined by the board. The board may solicit and accept grants, loans, and donations and may adopt fees for services it provides. The board may not impose taxes or acquire property, including water rights, by the exercise of eminent domain. The board may distribute available funds as grants or loans to local water plans or other water initiatives and projects that will further the goals of the board.

. The ability of the board to fully meet its duties under this chapter is dependent on the level of funding available to the board. If sufficient funding is not available to the board to carry out its duties, the board may, in consultation with the department, establish a plan that determines and sets priorities for implementation of the board's duties.

. The board, and its members and staff, acting in their official capacities, are immune from liability and are not subject to any cause of action or claim for damages arising from acts or omissions engaged in under this chapter.

. Upon the creation of the board, and for the duration of the board, the existing planning unit for the planning area, established under RCW 90.82.040, is dissolved and all assets, funds, files, planning documents, pending plans and grant applications, and other current activities of the planning unit are transferred to the board.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5352-S2.SL.pdf?cite=2019%20c%2078%20§%202[2019 c 78 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1580-S2.SL.pdf?cite=2009%20c%20183%20§%205[2009 c 183 § 5]; ]

== 90.92.060 - Report to the legislature. (Expires June 30, 2021.)
The board, in collaboration with the department, must provide a written report to the legislature by November 1, 2020, as described in RCW 90.92.050.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5352-S2.SL.pdf?cite=2019%20c%2078%20§%203[2019 c 78 § 3]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1580-S2.SL.pdf?cite=2009%20c%20183%20§%206[2009 c 183 § 6]; ]

== 90.92.070 - Water banking. (Expires June 30, 2021.)
. The board may establish a mechanism to bank water for the holders of water rights within the planning area to voluntarily deposit them on a temporary or permanent basis.

. The board has the following authority regarding banked water in the planning area:

.. The board may accept a surface water right or a groundwater right on a permanent or temporary basis under terms and conditions agreed upon by the water rights holder and the board.

.. On a temporary or permanent basis, the board may accept a water right, or portion thereof, that will be made available under local water plans for streamflow enhancement under the terms of the local water plan, as provided in this chapter.

.. Except as provided in (d) of this subsection, the board must accept a water right temporarily banked for instream flow without conducting a review of the extent and validity of the water right. Such a water right may not thereafter be authorized for any other purposes. A banked water right that has not been tentatively determined as to its extent and validity is not entitled to be protected from impairment by another water right.

.. The board may manage a water right that has been banked as mitigation for impairment to instream flows and other existing water rights. However, the water right may only be available for mitigation to the extent the department determines the water right is valid and use of the water right for mitigation will not cause detriment or injury to existing water rights.

. [Empty]
.. A water right banked on a temporary basis remains in the ownership of the water rights holder and not the state of Washington or the board.

.. A water right banked on a permanent basis must be transferred to the state of Washington as a trust water right consistent with RCW 90.42.080.

. A water right or portion of a water right banked under this chapter is not subject to loss by forfeiture under RCW 90.14.130 through 90.14.200. When a temporary water right is withdrawn from banking, the time period that the water right was banked may not be calculated as time water was not used for purposes of RCW 90.14.160, 90.14.170, and 90.14.180.

. When a temporarily deposited water right is withdrawn from banking, the time period that the water right was banked may not be included in the five years of prior water use for purposes of applications to add acreage or purposes of water use under RCW 90.03.380(1).

. Nothing in this chapter forecloses or diminishes the rights of any person to apply to the department to transfer a water right to the state trust water rights program under the authority of chapter 90.42 RCW or to apply for a change of a water right to the department or to a water conservancy board authorized under chapter 90.80 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1580-S2.SL.pdf?cite=2009%20c%20183%20§%207[2009 c 183 § 7]; ]

== 90.92.080 - Local water plan—Board to adopt guidelines and criteria for filing, review, and approval—Annual reports—Term. (Expires June 30, 2021.)
. The board shall adopt guidelines and criteria for filing, review, and approval of a local water plan. The board shall also develop a dispute resolution process that provides for water users, the board, and the department to resolve disputes regarding the implementation and enforcement of a local water plan.

. A water user or group of water users within the planning area, organized as provided in guidelines adopted by the board, may submit a proposed local water plan to the board.

. A local water plan must include:

.. A determination by the board of the baseline water use for all water rights involved in the local water plan, based on the guidelines adopted by the board, and in consultation with the water resource panel. The baseline documents regarding water use that are submitted by the water users may not be used by the department to determine the validity of the water rights in any future administrative or regulatory actions;

.. A clearly defined set of practices that provide for flexibility of water use as defined in subsection (4) of this section;

.. An estimate of the amount of water that would remain instream either long term or during critical flow periods for fish;

.. Performance measures and options for achieving reductions in total water use from baseline;

.. Performance measures for tracking improved streamflows either long term or during critical flow periods for fish; and

.. Measurement, tracking, and monitoring measures and procedures that ensure the implementation and enforcement of the measures for flexibility of water use, enhancement of the streamflows, and other elements, terms, and conditions in the local water plan.

. The local water plan may have elements and provide rights to the use and application of water that are not otherwise authorized in the water rights, including:

.. The ability to use the quantity of water defined as baseline in RCW 90.92.120(1)(a) on new or additional places of use, from new or additional points of diversion or withdrawal, and at different times of the year;

.. The ability to change or add a source of water supply including the use of groundwater to supplement surface water rights and the ability to implement the conjunctive use of the groundwater and surface water; and

.. The storage of water and infiltration of the water to the groundwater to supplement shallow groundwater withdrawals or for the purpose of replenishing the aquifer.

. To participate in a local water plan, water rights holders must: (a) Agree to allow a portion or all of their baseline water use to remain instream, as specified in the approved local water plan; (b) have existing operable water conveyance infrastructure in place and available for use; (c) agree that any water made available for streamflow enhancement may not be diverted from the water source and used during the term of the local water plan, but instead must be deposited into the water bank or, upon request by the water rights holder, transferred to the trust water rights program consistent with chapter 90.42 RCW; (d) measure and monitor their water use, streamflows upstream and downstream of the boundaries of the plan, and groundwater levels within the boundaries of the plan; and (e) commit to staying in the program consistent with criteria established by the board.

. Unless agreed upon by the water rights holder, nothing in this chapter diminishes or changes existing water rights.

. The water users must submit annual reports to the department and the board regarding contract performance, consistent with the guidelines adopted by the board.

. A local water plan may be effective for a term of one to ten years.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1580-S2.SL.pdf?cite=2009%20c%20183%20§%208[2009 c 183 § 8]; ]

== 90.92.090 - Local water plan—Public notice period—Other requirements. (Expires June 30, 2021.)
. The board must provide a thirty-day public notice period for the proposal for a local water plan and accept comments from all interested persons during that period.

. To become effective, the local water plan must be approved by both the board and the department. A proposed local water plan must not be approved if the board and the department determine the local water plan will not substantially enhance instream flow conditions.

. The approved local water plan must be signed by the executive director of the board, by the director, and by all water users participating in the local water plan. The local water plan is a contract among the board, the department, and the water users in which all parties agree to abide by all terms and conditions of the local water plan.

. If an approved local water plan is not in compliance with its terms and conditions, the board shall, consistent with the dispute resolution process adopted by the board, seek compliance. If the board revokes a local water plan due to noncompliance, the water users in the local water plan must thereafter exercise the water rights only as the water rights were authorized and conditioned prior to the approval of the local water plan, and all rights and duties that were terms in the local water plan lapse and are not valid or enforceable.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1580-S2.SL.pdf?cite=2009%20c%20183%20§%209[2009 c 183 § 9]; ]

== 90.92.100 - Appeal—Review of a claim of impairment. (Expires June 30, 2021.)
. Any person not party to the local water plan and aggrieved by the director's decision may appeal the decision to the pollution control hearings board as provided under RCW 43.21B.230.

. A water rights holder who believes the holder's water right has been impaired by any action under this chapter may request that the department review the impairment claim. If the department determines that some action under this chapter is impairing existing rights, the department, the board, and the water users must amend the local water plan to eliminate the impairment. Any decision of the department to alter or not alter a local water plan is appealable to the pollution control hearings board under RCW 43.21B.230.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1580-S2.SL.pdf?cite=2009%20c%20183%20§%2010[2009 c 183 § 10]; ]

== 90.92.110 - Local water plan—Expiration—Making elements of the local water plan permanent. (Expires June 30, 2021.)
. A local water plan expires by its terms, by withdrawal of one or more water users to the local water plan, or upon agreement by all parties to the contact [contract]. Upon the expiration of a local water plan that has been operating for five or more years, the water users may request that the board and the department make the elements of the local water plan, including water deposited to the water bank for placement in the trust water rights program, permanent authorizations and conditions for use of the water rights.

. The request under subsection (1) of this section must be evaluated based on whether:

.. The determination of the baseline water use adequately analyzed the extent and validity of the donated water right; and

.. [Empty]
... Whether there is injury or detriment to other existing water rights; or

... The written approval obtained from the holder of an impaired water right is continued or renewed.

. If the board and the department approve the request under subsection (1) of this section, the department shall issue superseding water rights consistent with the management and uses of the water under the local water plan. That portion of the water rights deposited in the water bank for placement in the trust water rights program must be made permanent and transferred in accordance with chapter 90.42 RCW.

. If the local water plan expires and the water management and uses under the local water plan are not granted approval to be permanent, the water users in the local water plan must thereafter exercise the water rights only as the water rights were authorized and conditioned prior to the local water plan, and all rights and duties that were terms in the local water plan lapse and are not valid or enforceable.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1580-S2.SL.pdf?cite=2009%20c%20183%20§%2011[2009 c 183 § 11]; ]

== 90.92.120 - Local water plan—Status of water rights. (Expires June 30, 2021.)
. The water rights in the local water plan as authorized for the uses described in RCW 90.92.080(4) are:

.. Not subject to either the approval of the department under RCW 90.03.380 through 90.03.390, 90.44.100, and 90.44.105, or a tentative determination of the validity and extent of the water rights;

.. Not subject to loss by forfeiture under RCW 90.14.130 through 90.14.200 during the period of time from when the local water plan is approved to the expiration or nullification of the local water plan as provided in RCW 90.92.110; and

.. Not to be exercised in a manner that would result in injury or detriment to other existing water rights unless express written approval is obtained from the holder of the impaired water right. To allow impacts to existing instream flow rights, the board and the department must agree that the flow benefits provided by a local water plan outweigh the impacts on existing instream flow rights.

. The years during the period of time when the local water plan is operational may not be considered or calculated as a period of time that the water was not applied to use for purposes of RCW 90.14.130 through 90.14.200. Further, the years during this period of time may not be considered or calculated as a period of time that the water was not applied to use and for purposes of future applications to change the water right for additional purposes or acreage under RCW 90.03.380.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1580-S2.SL.pdf?cite=2009%20c%20183%20§%2012[2009 c 183 § 12]; ]

== 90.92.130 - Location of pilot program. (Expires June 30, 2021.)
The local water management program authorized by this chapter must be piloted in WRIA 32, as defined in chapter 173-500 WAC as it existed on January 1, 1997.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1580-S2.SL.pdf?cite=2009%20c%20183%20§%2013[2009 c 183 § 13]; ]

