= 90.94 - Streamflow restoration.
:toc:

== 90.94.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Department" means the department of ecology.

. "Lead agency" has the same meaning as defined in RCW 90.82.060.

. "Water resource inventory area" or "WRIA" means a water resource inventory area established in chapter 173-500 WAC as it existed on January 19, 2018.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=2018%20c%201%20§%20201[2018 c 1 § 201]; ]

== 90.94.020 - Authorization for new domestic groundwater withdrawals exempt from permitting with a potential impact on a closed water body and potential impairment to an instream flow—Requirements—Fees—Adoption of rules.
. Unless requirements are otherwise specified in the applicable rules adopted under this chapter or under chapter 90.22 or 90.54 RCW, potential impacts on a closed water body and potential impairment to an instream flow are authorized for new domestic groundwater withdrawals exempt from permitting under RCW 90.44.050 through compliance with the requirements established in this section.

. In the following water resource inventory areas with instream flow rules adopted by the department under chapters 90.22 and 90.54 RCW that do not explicitly regulate permit-exempt groundwater withdrawals and that have completed a watershed plan adopted under chapter 90.82 RCW, the department shall work with the initiating governments and the planning units described in chapter 90.82 RCW to review existing watershed plans to identify the potential impacts of exempt well use, identify evidence-based conservation measures, and identify projects to improve watershed health: 1 (Nooksack); 11 (Nisqually); 22 (Lower Chehalis); 23 (Upper Chehalis); 49 (Okanogan); 55 (Little Spokane); and 59 (Colville).

. In the water resource inventory areas listed in subsection (2) of this section, the lead agency shall invite a representative from each federally recognized Indian tribe that has a usual and accustomed harvest area within the water resource inventory area to participate as part of the planning unit.

. [Empty]
.. In collaboration with the planning unit, the initiating governments must update the watershed plan to include recommendations for projects and actions that will measure, protect, and enhance instream resources and improve watershed functions that support the recovery of threatened and endangered salmonids. Watershed plan recommendations may include, but are not limited to, acquiring senior water rights, water conservation, water reuse, stream gaging, groundwater monitoring, and developing natural and constructed infrastructure, which includes, but is not limited to, such projects as floodplain restoration, off-channel storage, and aquifer recharge. Qualifying projects must be specifically designed to enhance streamflows and not result in negative impacts to ecological functions or critical habitat.

.. At a minimum, the watershed plan must include those actions that the planning units determine to be necessary to offset potential impacts to instream flows associated with permit-exempt domestic water use. The highest priority recommendations must include replacing the quantity of consumptive water use during the same time as the impact and in the same basin or tributary. Lower priority projects include projects not in the same basin or tributary and projects that replace consumptive water supply impacts only during critical flow periods. The watershed plan may include projects that protect or improve instream resources without replacing the consumptive quantity of water where such projects are in addition to those actions that the planning unit determines to be necessary to offset potential consumptive impacts to instream flows associated with permit-exempt domestic water use.

.. Prior to adoption of the updated watershed plan, the department must determine that actions identified in the watershed plan, after accounting for new projected uses of water over the subsequent twenty years, will result in a net ecological benefit to instream resources within the water resource inventory area.

.. The watershed plan may include:

... Recommendations for modification to fees established under this subsection;

... Standards for water use quantities that are less than authorized under RCW 90.44.050 or more or less than authorized under subsection (5) of this section for withdrawals exempt from permitting;

... Specific conservation requirements for new water users to be adopted by local or state permitting authorities; or

... Other approaches to manage water resources for a water resource inventory area or a portion thereof.

.. Any modification to fees collected under subsection (5) of this section or standards for water use quantities that are less than authorized under RCW 90.44.050 or more or less than authorized under subsection (5) of this section for withdrawals exempt from permitting may not be applied unless authorized by rules adopted under this chapter or under chapter 90.54 RCW.

. Until an updated watershed plan is approved and rules are adopted under this chapter or chapter 90.54 RCW, a city or county issuing a building permit under RCW 19.27.097(1)(c), or approving a subdivision under chapter 58.17 RCW in a watershed listed in subsection (2) of this section must:

.. Record relevant restrictions or limitations associated with water supply with the property title;

.. Collect applicable fees, as described under this section;

.. Record the number of building permits issued under chapter 19.27 RCW or subdivision approvals issued under chapter 58.17 RCW subject to the provisions of this section;

.. Annually transmit to the department three hundred fifty dollars of each fee collected under this subsection;

.. Annually transmit an accounting of building permits and subdivision approvals subject to the provisions of this section to the department;

.. Until rules have been adopted that specify otherwise, require the following measures for each new domestic use that relies on a withdrawal exempt from permitting under RCW 90.44.050:

... An applicant shall pay a fee of five hundred dollars to the permitting authority;

... An applicant may obtain approval for a withdrawal exempt from permitting under RCW 90.44.050 for domestic use only, with a maximum annual average withdrawal of three thousand gallons per day per connection.

. Rules adopted under this chapter or under chapter 90.54 RCW may:

.. Rely on watershed plan recommendations and procedures established in this section to authorize new withdrawals exempt from permitting under RCW 90.44.050 that would potentially impact a closed water body or a minimum flow or level;

.. Rely on projects identified in the watershed plan to offset consumptive water use; and

.. Include updates to fees based on the planning unit's determination of the costs for offsetting consumptive water use.

. [Empty]
.. If a watershed plan that meets the requirements of this section is not adopted in water resource inventory area 1 (Nooksack) by February 1, 2019, the department must adopt rules for that water resource inventory area that meet the requirements of this section by August 1, 2020.

.. If a watershed plan that meets the requirements of this section is not adopted in water resource inventory area 11 (Nisqually) by February 1, 2019, the department must adopt rules for that water resource inventory area that meet the requirements of this section by August 1, 2020.

.. The department must adopt rules that meet the requirements of this section for any of the following water resource inventory areas that do not adopt a watershed plan that meets the requirements of this section by February 1, 2021: 22 (Lower Chehalis); 23 (Upper Chehalis); 49 (Okanogan); 55 (Little Spokane); and 59 (Colville).

. This section only applies to new domestic groundwater withdrawals exempt from permitting under RCW 90.44.050 in the following water resource inventory areas with instream flow rules adopted under chapters 90.22 and 90.54 RCW that do not explicitly regulate permit-exempt groundwater withdrawals: 1 (Nooksack); 11 (Nisqually); 22 (Lower Chehalis); 23 (Upper Chehalis); 49 (Okanogan); 55 (Little Spokane); and 59 (Colville) and does not restrict the withdrawal of groundwater for other uses that are exempt from permitting under RCW 90.44.050.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=2018%20c%201%20§%20202[2018 c 1 § 202]; ]

== 90.94.030 - Authorization for new domestic groundwater withdrawals exempt from permitting with a potential impact on a closed water body and potential impairment to an instream flow—Requirements—Watershed restoration and enhancement committees—Watershed restoration and enhancement plan—Fees—Adoption of rules—Application of section.
. Unless requirements are otherwise specified in the applicable rules adopted under this chapter or chapter 90.22 or 90.54 RCW, potential impacts on a closed water body and potential impairment to an instream flow are authorized for new domestic groundwater withdrawals exempt from permitting under RCW 90.44.050 through compliance with the requirements established in this section.

. [Empty]
.. In the following water resource inventory areas with instream flow rules adopted by the department under chapters 90.22 and 90.54 RCW that do not explicitly regulate permit-exempt groundwater withdrawals and that have either not adopted a watershed plan, or adopted a partial watershed plan, under chapter 90.82 RCW, the department shall establish watershed restoration and enhancement committees in the following water resource inventory areas: 7 (Snohomish); 8 (Cedar-Sammamish); 9 (Duwamish-Green); 10 (Puyallup-White); 12 (Chambers-Clover); 13 (Deschutes); 14 (Kennedy-Goldsborough); and 15 (Kitsap).

.. The department shall chair the watershed restoration and enhancement committee and invite the following entities to participate:

... A representative from each federally recognized Indian tribe that has reservation land within the water resource inventory area;

... A representative from each federally recognized Indian tribe that has a usual and accustomed harvest area within the water resource inventory area;

... A representative from the department of fish and wildlife, appointed by the director of the department of fish and wildlife;

... A representative designated by each county within the water resource inventory area;

.. A representative designated by each city within the water resource inventory area;

.. A representative designated by the largest irrigation district within the water resource inventory area;

.. A representative designated by the largest publicly owned water purveyor providing water within the water resource inventory area that is not a municipality;

.. A representative designated by a local organization representing the residential construction industry within the water resource inventory area;

... A representative designated by a local organization representing environmental interests within the water resource inventory area; and

.. A representative designated by a local organization representing agricultural interests within the water resource inventory area.

. By June 30, 2021, the department shall prepare and adopt a watershed restoration and enhancement plan for each watershed listed under subsection (2)(a) of this section, in collaboration with the watershed restoration and enhancement committee. Except as described in (h) of this subsection, all members of a watershed restoration and enhancement committee must approve the plan prior to adoption.

.. The watershed restoration and enhancement plan should include recommendations for projects and actions that will measure, protect, and enhance instream resources and improve watershed functions that support the recovery of threatened and endangered salmonids. Plan recommendations may include, but are not limited to, acquiring senior water rights, water conservation, water reuse, stream gaging, groundwater monitoring, and developing natural and constructed infrastructure, which includes but is not limited to such projects as floodplain restoration, off-channel storage, and aquifer recharge. Qualifying projects must be specifically designed to enhance streamflows and not result in negative impacts to ecological functions or critical habitat.

.. At a minimum, the plan must include those actions that the committee determines to be necessary to offset potential impacts to instream flows associated with permit-exempt domestic water use. The highest priority recommendations must include replacing the quantity of consumptive water use during the same time as the impact and in the same basin or tributary. Lower priority projects include projects not in the same basin or tributary and projects that replace consumptive water supply impacts only during critical flow periods. The plan may include projects that protect or improve instream resources without replacing the consumptive quantity of water where such projects are in addition to those actions that the committee determines to be necessary to offset potential consumptive impacts to instream flows associated with permit-exempt domestic water use.

.. Prior to adoption of the watershed restoration and enhancement plan, the department must determine that actions identified in the plan, after accounting for new projected uses of water over the subsequent twenty years, will result in a net ecological benefit to instream resources within the water resource inventory area.

.. The watershed restoration and enhancement plan must include an evaluation or estimation of the cost of offsetting new domestic water uses over the subsequent twenty years, including withdrawals exempt from permitting under RCW 90.44.050.

.. The watershed restoration and enhancement plan must include estimates of the cumulative consumptive water use impacts over the subsequent twenty years, including withdrawals exempt from permitting under RCW 90.44.050.

.. The watershed restoration and enhancement plan may include:

... Recommendations for modification to fees established under this subsection;

... Standards for water use quantities that are less than authorized under RCW 90.44.050 or more or less than authorized under subsection (4) of this section for withdrawals exempt from permitting;

... Specific conservation requirements for new water users to be adopted by local or state permitting authorities; or

... Other approaches to manage water resources for a water resource inventory area or a portion thereof.

.. After adoption of a watershed restoration and enhancement plan, the department shall evaluate the plan recommendations and initiate rule making, if necessary, to incorporate recommendations into rules adopted under this chapter or under chapter 90.22 or 90.54 RCW. Any modification to fees collected under subsection (4) of this section or standards for water use quantities that are less than authorized under RCW 90.44.050 or more or less than authorized under subsection (4) of this section for withdrawals exempt from permitting may not be applied unless authorized by rules adopted under this chapter or under chapter 90.54 RCW.

.. If the watershed restoration and enhancement committee fails to approve a plan by June 30, 2021, the director of the department shall submit the final draft plan to the salmon recovery funding board established under RCW 77.85.110 and request that the salmon recovery funding board provide a technical review and provide recommendations to the director to amend the final draft plan, if necessary, so that actions identified in the plan, after accounting for new projected uses of water over the subsequent twenty years, will result in a net ecological benefit to instream resources within the water resource inventory area. The director of the department shall consider the recommendations and may amend the plan without committee approval prior to adoption. After plan adoption, the director of the department shall initiate rule making within six months to incorporate recommendations into rules adopted under this chapter or under chapter 90.22 or 90.54 RCW, and shall adopt amended rules within two years of initiation of rule making.

. [Empty]
.. Until a watershed restoration and enhancement plan is approved and rules are adopted under subsection (3) of this section, a city or county issuing a building permit under RCW 19.27.097(1)(d), or approving a subdivision under chapter 58.17 RCW in a watershed listed in subsection (2)(a) of this section must:

... Record relevant restrictions or limitations associated with water supply with the property title;

... Collect applicable fees, as described under this section;

... Record the number of building permits issued under chapter 19.27 RCW or subdivision approvals issued under chapter 58.17 RCW subject to the provisions of this section;

... Annually transmit to the department three hundred fifty dollars of each fee collected under this subsection;

.. Annually transmit an accounting of building permits and subdivision approvals subject to the provisions of this section to the department;

.. Until rules have been adopted that specify otherwise, require the following measures for each new domestic use that relies on a withdrawal exempt from permitting under RCW 90.44.050:

(A) An applicant shall pay a fee of five hundred dollars to the permitting authority;

(B) Except as provided in (b) of this subsection, an applicant may obtain approval for a withdrawal exempt from permitting under RCW 90.44.050 for domestic use only, with a maximum annual average withdrawal of nine hundred fifty gallons per day per connection; and

(C) An applicant shall manage stormwater runoff on-site to the extent practicable by maximizing infiltration, including using low-impact development techniques, or pursuant to stormwater management requirements adopted by the local permitting authority, if locally adopted requirements are more stringent.

.. Upon the issuance of a drought emergency order under RCW 43.83B.405, the department may curtail withdrawal of groundwater exempt from permitting under RCW 90.44.050 and approved under this subsection (4) to no more than three hundred fifty gallons per day per connection for indoor use only. Notwithstanding the limitation to no more than three hundred fifty gallons per day per connection for indoor use only, an applicant may use groundwater exempt from permitting to maintain a fire control buffer during a drought emergency order.

. Rules adopted under this chapter or chapter 90.54 RCW may:

.. Rely on watershed restoration and enhancement plan recommendations and procedures established in this section to authorize new withdrawals exempt from permitting under RCW 90.44.050 that would potentially impact a closed water body or a minimum flow or level;

.. Rely on projects identified in the watershed restoration and enhancement plan to offset consumptive water use; and

.. Include updates to fees based on the watershed restoration and enhancement committee's determination of the costs for offsetting consumptive water use.

. This section only applies to new domestic groundwater withdrawals exempt from permitting under RCW 90.44.050 in the following water resource inventory areas with instream flow rules adopted under chapters 90.22 and 90.54 RCW that do not explicitly regulate permit-exempt groundwater withdrawals: 7 (Snohomish); 8 (Cedar-Sammamish); 9 (Duwamish-Green); 10 (Puyallup-White); 12 (Chambers-Clover); 13 (Deschutes); 14 (Kennedy-Goldsborough); and 15 (Kitsap) and does not restrict the withdrawal of groundwater for other uses that are exempt from permitting under RCW 90.44.050.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=2018%20c%201%20§%20203[2018 c 1 § 203]; ]

== 90.94.040 - Pilot projects to measure water use from all new groundwater withdrawals for domestic purposes exempt from permitting—Areas—Report to the legislature.
. The department shall initiate two pilot projects to measure water use from all new groundwater withdrawals for domestic purposes exempt from permitting under RCW 90.44.050 in the areas described in this section. The pilot projects must be conducted to determine the overall feasibility of measuring water use for all new groundwater withdrawals. The department must purchase and provide meters to be used in the pilot projects. The pilot projects must be conducted in the area under the Dungeness water rule, chapter 173-518 WAC, within water resource inventory area 18 and the area in which the Kittitas county water bank program operates within water resource inventory area 39.

. At a minimum, the pilot project must address the following:

.. Initial and ongoing costs, including costs to local government and the department;

.. Technical, practical, and legal considerations that must be addressed;

.. The costs and benefits of a water use measurement program relying on individual meters versus a water management program that estimates permit-exempt groundwater withdrawals; and

.. Measures to protect the privacy of individual property owners and ensure accurate data collection.

. The department shall report on the pilot project results in the report to the legislature submitted under RCW 90.94.050. The department shall include recommendations to the legislature, including estimated program costs for expanding the pilot projects to other basins.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=2018%20c%201%20§%20204[2018 c 1 § 204]; ]

== 90.94.050 - Report to the legislature—Elements.
The department shall submit a report to the legislature by December 31, 2020, and December 31, 2027, in compliance with RCW 43.01.036, that includes the following elements:

. Progress in completing and adopting watershed plans under RCW 90.94.020 and watershed restoration and enhancement plans under RCW 90.94.030;

. A description of program projects and expenditures;

. An assessment of the streamflow restoration and enhancement benefits from program projects;

. A listing of other efforts or actions taken associated with streamflow restoration and enhancement, projects to benefit instream resources, and other directly related watershed improvements conducted in coordination with the restoration and enhancement planning process;

. The total number of new withdrawals exempt from permitting under RCW 90.44.050 authorized in each water resource inventory area under provisions of RCW 90.94.020 and 90.94.030, and estimates of consumptive water use impacts associated with the new withdrawals; and

. A description of potential or planned projects, including projected costs and anticipated streamflow, water supply, and watershed health benefits.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=2018%20c%201%20§%20205[2018 c 1 § 205]; ]

== 90.94.060 - Watershed restoration and enhancement account.
. The watershed restoration and enhancement account is created in the custody of the state treasurer. All receipts from fees paid pursuant to RCW 90.94.020 and 90.94.030 must be deposited into the account. The account may also receive those moneys as may be appropriated by the legislature for the purpose of funding restoration and enhancement projects as identified in RCW 90.94.020 and 90.94.030. Expenditures from the account may be used only for the costs of administering chapter 1, Laws of 2018, including implementing watershed planning projects under RCW 90.94.020 and watershed restoration and enhancement projects under RCW 90.94.030, and collecting data and completing studies necessary to develop, implement, and evaluate watershed restoration and enhancement projects under chapter 1, Laws of 2018. Only the director or the director's designee may authorize expenditures from the account. The account is subject to allotment procedures under chapter 43.88 RCW, but an appropriation is not required for expenditures.

. Fee revenues collected under RCW 90.94.020 and 90.94.030 must be used exclusively within the water resource inventory area in which the fee originated. The restriction in this subsection does not apply to moneys in the watershed restoration and enhancement account that do not originate from fees collected under RCW 90.94.020 and 90.94.030.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=2018%20c%201%20§%20206[2018 c 1 § 206]; ]

== 90.94.070 - Watershed restoration and enhancement taxable bond account.
. The watershed restoration and enhancement taxable bond account is created in the custody of the state treasurer. All receipts from direct appropriations from the legislature or moneys directed to the account from any other source must be deposited in the account. The account is intended to fund projects using taxable bonds. Expenditures from the account may be used only as provided for in this section. Only the director or the director's designee may authorize expenditures from the account. The account is subject to allotment procedures under chapter 43.88 RCW, but an appropriation is not required for expenditures.

. Expenditures from the watershed restoration and enhancement taxable bond account may be used to assess, plan, and develop projects that include acquiring senior water rights, water conservation, water reuse, stream gaging, groundwater monitoring, and developing natural and constructed infrastructure, which includes, but is not limited to, projects such as floodplain restoration, off-channel storage, and aquifer recharge, or other actions designed to provide access to new water supplies with priority given to projects in watersheds developing plans as directed by RCW 90.94.020 and 90.94.030 and watersheds participating in the pilot project in RCW 90.94.040.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=2018%20c%201%20§%20207[2018 c 1 § 207]; ]

== 90.94.080 - Watershed restoration and enhancement bond account.
. The watershed restoration and enhancement bond account is created in the custody of the state treasurer. All receipts from direct appropriations from the legislature or moneys directed to the account from any other source must be deposited in the account. The account is intended to fund projects using tax exempt bonds. Expenditures from the account may be used only as provided for in this section. Only the director or the director's designee may authorize expenditures from the account. The account is subject to allotment procedures under chapter 43.88 RCW, but an appropriation is not required for expenditures.

. Expenditures from the watershed restoration and enhancement bond account may be used to assess, plan, and develop projects that include acquiring senior water rights, water conservation, water reuse, stream gaging, groundwater monitoring, and developing natural and constructed infrastructure, which includes, but is not limited to, projects such as floodplain restoration, off-channel storage, and aquifer recharge, or other actions designed to provide access to new water supplies with priority given to projects in watersheds developing plans as directed by RCW 90.94.020 and 90.94.030 and watersheds participating in the pilot project in RCW 90.94.040.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=2018%20c%201%20§%20208[2018 c 1 § 208]; ]

== 90.94.090 - Joint legislative task force on water resource mitigation—Water resource mitigation pilot projects. (Expires January 1, 2029.)
. A joint legislative task force on water resource mitigation is established to review the treatment of surface water and groundwater appropriations as they relate to instream flows and fish habitat, to develop and recommend a mitigation sequencing process and scoring system to address such appropriations, and to review the Washington supreme court decision in Foster v. Department of Ecology, 184 Wn.2d 465, 362 P.3d 959 (2015).

. The task force must consist of the following members:

.. Two members from each of the two largest caucuses of the senate, appointed by the president of the senate;

.. Two members from each of the two largest caucuses of the house of representatives, appointed by the speaker of the house of representatives;

.. A representative from the department, appointed by the director of the department;

.. A representative from the department of fish and wildlife, appointed by the director of the department of fish and wildlife;

.. A representative from the department of agriculture, appointed by the director of the department of agriculture;

.. One representative from each of the following groups, appointed by the consensus of the cochairs of the task force:

... An organization representing the farming industry in Washington;

... An organization representing Washington cities;

... Two representatives from an environmental advocacy organization or organizations;

... An organization representing municipal water purveyors;

.. An organization representing business interests;

.. Representatives of two federally recognized Indian tribes, one invited by recommendation of the Northwest Indian fisheries commission, and one invited by recommendation of the Columbia river intertribal fish commission.

. If a member has not been designated for a position set forth in subsection (2) of this section, that position may not be counted for purposes of determining a quorum.

. One cochair of the task force must be a member of the majority caucus of one chamber of the legislature, and one cochair must be a member of the minority caucus of the other chamber of the legislature, as those caucuses existed as of January 19, 2018.

. The first meeting of the task force must occur by June 30, 2018.

. Staff support for the task force must be provided by the office of program research and senate committee services. The department and the department of fish and wildlife shall cooperate with the task force and provide information as the cochairs reasonably request.

. Within existing appropriations, the expenses of the operations of the task force, including the expenses associated with the task force's meetings, must be paid jointly and in equal amounts by the senate and the house of representatives. Task force expenditures are subject to approval by the house executive rules committee and the senate facility and operations committee. Legislative members of the task force are reimbursed for travel expenses in accordance with RCW 44.04.120. Nonlegislative members are not entitled to be reimbursed for travel expenses if they are elected officials or are participating on behalf of an employer, governmental entity, or other organization. Any reimbursement for other nonlegislative members is subject to chapter 43.03 RCW.

. [Empty]
.. By November 15, 2019, and November 15, 2022, the joint legislative task force must make recommendations to the legislature in compliance with RCW 43.01.036.

.. Recommendations of the joint legislative task force must be made by a sixty percent majority of the appointed members of the task force. The representatives of the departments of fish and wildlife, ecology, and agriculture are not eligible to vote on the recommendations. Minority recommendations that achieve the support of at least five of the appointed voting members of the task force may also be submitted to the legislature.

. The department shall issue permit decisions for up to five water resource mitigation pilot projects. It is the intent of the legislature to use the pilot projects to inform the legislative task force process while also enabling the processing of water right applications that address water supply needs. The department is authorized to issue permits in reliance upon water resource mitigation of impacts to instream flows and closed surface water bodies under the following mitigation sequence:

.. Avoiding impacts by: (i) Complying with mitigation required by adopted rules that set forth minimum flows, levels, or closures; or (ii) making the water diversion or withdrawal subject to the applicable minimum flows or levels; or

.. Where avoidance of impacts is not reasonably attainable, minimizing impacts by providing permanent new or existing trust water rights or through other types of replacement water supply resulting in no net annual increase in the quantity of water diverted or withdrawn from the stream or surface water body and no net detrimental impacts to fish and related aquatic resources; or

.. Where avoidance and minimization are not reasonably attainable, compensating for impacts by providing net ecological benefits to fish and related aquatic resources in the water resource inventory area through in-kind or out-of-kind mitigation or a combination thereof, that improves the function and productivity of affected fish populations and related aquatic habitat. Out-of-kind mitigation may include instream or out-of-stream measures that improve or enhance existing water quality, riparian habitat, or other instream functions and values for which minimum instream flows or closures were established in that watershed.

. The department must monitor the implementation of the pilot projects, including all mitigation associated with each pilot project, approved under this section at least annually through December 31, 2028.

. The pilot projects eligible for processing under this section, based on criteria as of January 19, 2018, include:

.. A city operating a group A water system in Kitsap county and water resource inventory area 15, with a population between 13,000 and 14,000;

.. A city operating a group A water system in Pierce county and water resource inventory area 10, with a population between 9,500 and 10,500;

.. A city operating a group A water system in Thurston county and water resource inventory area 11, with a population between 8,500 and 9,500;

.. A nonprofit mutual water system operating a group A water system in Pierce county and water resource inventory area 12, with between 10,500 and 11,500 service connections; and

.. An irrigation district located in Whatcom county and water resource inventory area 1, solely for the purpose of processing changes of water rights from surface water to groundwater, and implementing flow augmentation to benefit instream flows.

. Water right applicants eligible to be processed under this pilot project authority must elect to be included in the pilot project review by notifying the department by July 1, 2018. Once an applicant notifies the department of its intent to be processed under this pilot project authority, subsection (9) of this section applies to final decisions issued by the department, even if such a final decision is issued after the expiration of this section.

. By November 15, 2018, the department must furnish the task force with information on conceptual mitigation plans for each water resource mitigation pilot project application. By November 15, 2019, and November 15, 2022, the department must provide the task force with an update on the mitigation plans based on additional information developed after November 15, 2018.

. To ensure that the processing of pilot project applications can inform the task force process in a timely manner, the department must expedite processing of applications for water resource mitigation pilot projects. The applicant for each pilot project must reimburse the department for the department's costs of processing the applicant's application.

. The water resource mitigation pilot project authority granted to the department does not affect or modify any other procedural requirements of chapter 90.03, 90.44, or 90.54 RCW that apply to the processing of such applications.

. The joint legislative task force expires December 31, 2022. During the period from November 16, 2019, through December 31, 2022, the work of the task force is limited to:

.. A review of any additional information that may be developed after November 15, 2019, as a result of the pilot projects established under subsection (9) of this section; and

.. An update of the task force's November 15, 2019, recommendations.

. This section expires January 1, 2029.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1080-S.SL.pdf?cite=2021%20c%20332%20§%207024[2021 c 332 § 7024]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1102-S.SL.pdf?cite=2019%20c%20413%20§%207035[2019 c 413 § 7035]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=2018%20c%201%20§%20301[2018 c 1 § 301]; ]

== 90.94.900 - Effective date—2018 c 1.
This act is necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and takes effect immediately [January 19, 2018].

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=2018%20c%201%20§%20307[2018 c 1 § 307]; ]

