= 90.90 - Columbia river basin water supply.
:toc:

== 90.90.005 - Finding.
. The legislature finds that a key priority of water resource management in the Columbia river basin is the development of new water supplies that includes storage and conservation in order to meet the economic and community development needs of people and the instream flow needs of fish.

. The legislature therefore declares that a Columbia river basin water supply development program is needed, and directs the department of ecology to aggressively pursue the development of water supplies to benefit both instream and out-of-stream uses.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2860-S2.SL.pdf?cite=2006%20c%206%20§%201[2006 c 6 § 1]; ]

== 90.90.010 - Columbia river basin water supply development account—Use for storage facilities and access to water supplies—Evaluation—Public comment—Use of net water savings—Water service contracts.
. The Columbia river basin water supply development account is created in the state treasury. The account may receive direct appropriations from the legislature, receipts of any funds pursuant to RCW 90.90.020 and 90.90.030, or funds from any other sources. The account is intended to fund projects using tax exempt bonds.

. [Empty]
.. Expenditures from the Columbia river basin water supply development account may be used to assess, plan, and develop new storage, improve or alter operations of existing storage facilities, implement conservation projects, develop pump exchanges, or any other actions designed to provide access to new water supplies within the Columbia river basin for both instream and out-of-stream uses. Except for the development of new storage projects and pump exchanges, there shall be no expenditures from this account for water acquisition or transfers from one water resource inventory area to another without specific legislative authority. For purposes of this chapter, "pump exchanges" means water supply development projects that exchange water from one source to another or relocate an existing diversion downstream, with resulting instream benefit.

.. Two-thirds of the funds placed in the account shall be used to support the development of new storage facilities and pump exchanges; the remaining one-third shall be used for the other purposes listed in this section.

. [Empty]
.. Funds may not be expended from this account for the construction of a new storage facility until the department of ecology evaluates the following:

... Water uses to be served by the facility;

... The quantity of water necessary to meet those uses;

... The benefits and costs to the state of meeting those uses, including short-term and long-term economic, cultural, and environmental effects; and

... Alternative means of supplying water to meet those uses, including the costs of those alternatives and an analysis of the extent to which long-term water supply needs can be met using these alternatives.

.. The department of ecology may rely on studies and information developed through compliance with other state and federal permit requirements and other sources. The department shall compile its findings and conclusions, and provide a summary of the information it reviewed.

.. Before finalizing its evaluation under the provisions of this section, the department of ecology shall make the preliminary evaluation available to the public. Public comment may be made to the department within thirty days of the date the preliminary evaluation is made public.

. Net water savings achieved through conservation measures funded by the account shall be placed in trust in proportion to the state funding provided to implement a project.

. Net water savings achieved through conservation measures funded by the account developed within the boundaries of the federal Columbia river reclamation project and directed to the Odessa subarea to reduce the use of groundwater for existing irrigation is exempt from the provisions of subsection (4) of this section.

. The department of ecology may enter into water service contracts with applicants receiving water from the program to recover all or a portion of the cost of developing the water supply. Costs recovered under water service contracts does not include staff time expended by the department on developing the water supply. With the applicant's concurrence, the department may receive power revenue generated by the water supply developed by the department through water service contracts. The department may deny an application if the applicant does not enter into a water service contract. Revenue collected from water service contracts must be deposited into the Columbia river basin water supply revenue recovery account created in RCW 90.90.100. The department may adopt rules describing the methodology as to how charges will be established and direct costs recovered for water supply developed under the Columbia river basin water supply program. Water service contracts with federal agencies under RCW 90.42.150 are not required to be established by rule.

. Moneys in the Columbia river basin water supply development account created in this section may be spent only after appropriation.

. Interest earned by deposits in the account will be retained in the account.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1803-S2.SL.pdf?cite=2011%20c%2083%20§%201[2011 c 83 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2860-S2.SL.pdf?cite=2006%20c%206%20§%202[2006 c 6 § 2]; ]

== 90.90.020 - Allocation and development of water supplies.
. [Empty]
.. Water supplies secured through the development of new storage facilities made possible with funding from the Columbia river basin water supply development account, the Columbia river basin taxable bond water supply development account, and the Columbia river basin water supply revenue recovery account shall be allocated as follows:

... Two-thirds of active storage shall be available for appropriation for out-of-stream uses; and

... One-third of active storage shall be available to augment instream flows and shall be managed by the department of ecology. The timing of releases of this water shall be determined by the department of ecology, in cooperation with the department of fish and wildlife and fisheries comanagers, to maximize benefits to salmon and steelhead populations.

.. Water available for appropriation under (a)(i) of this subsection but not yet appropriated shall be temporarily available to augment instream flows to the extent that it does not impair existing water rights.

. Water developed under the provisions of this section to offset out-of-stream uses and for instream flows is deemed adequate mitigation for the issuance of new water rights provided for in subsection (1)(a) of this section and satisfies all consultation requirements under state law related to the issuance of new water rights.

. The department of ecology shall focus its efforts to develop water supplies for the Columbia river basin on the following needs:

.. Alternatives to groundwater for agricultural users in the Odessa subarea aquifer;

.. Sources of water supply for pending water right applications;

.. A new uninterruptible supply of water for the holders of interruptible water rights on the Columbia river mainstem that are subject to instream flows or other mitigation conditions to protect streamflows; and

.. New municipal, domestic, industrial, and irrigation water needs within the Columbia river basin.

. The one-third/two-thirds allocation of water resources between instream and out-of-stream uses established in this section does not apply to applications for changes or transfers of existing water rights in the Columbia river basin.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1803-S2.SL.pdf?cite=2011%20c%2083%20§%204[2011 c 83 § 4]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2860-S2.SL.pdf?cite=2006%20c%206%20§%203[2006 c 6 § 3]; ]

== 90.90.030 - Voluntary regional agreements—Scope and application—Definitions. (Expires June 30, 2024.)
. The department of ecology may enter into voluntary regional agreements for the purpose of providing new water for out-of-stream use, streamlining the application process, and protecting instream flow.

. Such agreements shall ensure that:

.. For water rights issued from the Columbia river mainstem, there is no negative impact on Columbia river mainstem instream flows in the months of July and August as a result of the new appropriations issued under the agreement;

.. For water rights issued from the lower Snake river mainstem, there is no negative impact on Snake river mainstem instream flows from April through August as a result of the new appropriations issued under the agreement; and

.. Efforts are made to harmonize such agreements with watershed plans adopted under the authority of chapter 90.82 RCW that are applicable to the area covered by the agreement.

. The protection of instream flow as set forth in subsection (2) of this section is adequate for purposes of mitigating instream flow impacts resulting from any appropriations for out-of-stream use made under a voluntary regional agreement, and the only applicable consultation provisions under state law regarding instream flow impacts shall be those set forth in subsection (4) of this section.

. Before executing a voluntary agreement under this section, the department of ecology shall:

.. Provide a sixty-day period for consultation with county legislative authorities and watershed planning groups with jurisdiction over the area where the water rights included in the agreement are located, the department of fish and wildlife, and affected tribal governments, and federal agencies. The department of fish and wildlife shall provide written comments within that time period. The consultation process for voluntary regional agreements developed under the provisions of this section is deemed adequate for the issuance of new water rights provided for in this section and satisfies all consultation requirements under state law related to the issuance of new water rights; and

.. Provide a thirty-day public review and comment period for a draft agreement, and publish a summary of any public comments received. The thirty-day review period shall not begin until after the department of ecology has concluded its consultation under (a) of this subsection and the comments that have been received by the department are made available to the public.

. The provisions of subsection (4) of this section satisfy all applicable consultation requirements under state law.

. The provisions of this section and any voluntary regional agreements developed under such provisions may not be relied upon by the department of ecology as a precedent, standard, or model that must be followed in any other voluntary regional agreements.

. Nothing in this section may be interpreted or administered in a manner that precludes the processing of water right applications under chapter 90.03 or 90.44 RCW that are not included in a voluntary regional agreement.

. Nothing in this section may be interpreted or administered in a manner that impairs or diminishes a valid water right or a habitat conservation plan approved for purposes of compliance with the federal endangered species act.

. If the department of ecology executes a voluntary agreement under this section that includes water rights appropriated from the lower Snake river mainstem, the department shall develop aggregate data in accordance with the provisions of RCW 90.90.050 for the lower Snake river mainstem.

. Any agreement entered into under this section shall remain in full force and effect through the term of the agreement regardless of the expiration of this section.

. The definitions in this subsection apply to this section and RCW 90.90.050, and may only be used for purposes of implementing these sections.

.. "Columbia river mainstem" means all water in the Columbia river within the ordinary high water mark of the main channel of the Columbia river between the border of the United States and Canada and the Bonneville dam, and all groundwater within one mile of the high water mark.

.. "Lower Snake river mainstem" means all water in the lower Snake river within the ordinary high water mark of the main channel of the lower Snake river from the head of Ice Harbor pool to the confluence of the Snake and Columbia rivers, and all groundwater within one mile of the high water mark.

. This section expires June 30, 2024.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6125.SL.pdf?cite=2018%20c%2072%20§%201[2018 c 72 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2212-S.SL.pdf?cite=2012%20c%20161%20§%201[2012 c 161 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2860-S2.SL.pdf?cite=2006%20c%206%20§%204[2006 c 6 § 4]; ]

== 90.90.040 - Columbia river water supply inventory—Long-term water supply and demand forecast.
. To support the development of new water supplies in the Columbia river and to protect instream flow, the department of ecology shall work with all interested parties, including interested county legislative authorities and watershed planning groups in the Columbia river basin, and affected tribal governments, to develop a Columbia river water supply inventory and a long-term water supply and demand forecast. The inventory must include:

.. A list of conservation projects that have been implemented under this chapter and the amount of water conservation they have achieved; and

.. A list of potential water supply and storage projects in the Columbia river basin, including estimates of:

... Cost per acre-foot;

... Benefit to fish and other instream needs;

... Benefit to out-of-stream needs; and

... Environmental and cultural impacts.

. The department of ecology shall complete the first Columbia river water supply inventory by November 15, 2006, and shall update the inventory annually thereafter.

. The department of ecology shall complete the first Columbia river long-term water supply and demand forecast by November 15, 2006, and shall update the report every five years thereafter.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1803-S2.SL.pdf?cite=2011%20c%2083%20§%206[2011 c 83 § 6]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2860-S2.SL.pdf?cite=2006%20c%206%20§%205[2006 c 6 § 5]; ]

== 90.90.050 - Columbia river mainstem water resources information system.
. In order to better understand current water use and instream flows in the Columbia river mainstem, the department of ecology shall establish and maintain a Columbia river mainstem water resources information system that provides the information necessary for effective mainstem water resource planning and management.

. To accomplish the objective in subsection (1) of this section, the department of ecology shall use information compiled by existing local watershed planning groups, federal agencies, the Bonneville power administration, irrigation districts, conservation districts in the basin, and other available sources. The information shall include:

.. The total aggregate quantity of water rights issued under state permits and certificates and filed under state claims on the Columbia river mainstem and for groundwater within one mile of the mainstem; and

.. The total aggregate volume of current water use under these rights as metered and reported by water users under current law.

. The department of ecology shall publish the aggregate data on the department's web site no later than June 30, 2009, and shall periodically update the data.

. For purposes of this section, the definition of Columbia river mainstem in RCW 90.90.030(11) shall apply and the use of the definition is solely limited to the purpose of collecting data to meet the information requirements of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6125.SL.pdf?cite=2018%20c%2072%20§%202[2018 c 72 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2860-S2.SL.pdf?cite=2006%20c%206%20§%206[2006 c 6 § 6]; ]

== 90.90.060 - Additional releases of water from Lake Roosevelt.
. In 2006, the legislature enacted chapter 6, Laws of 2006, an act relating to water resource management in the Columbia river basin. In its enactment, the legislature established that a key priority of water resource management in the Columbia river basin is the development of new water supplies to meet economic and community development needs concurrent with instream flow needs.

. Consistent with this intent, the governor and the legislature are in agreement with the Confederated Tribes of the Colville Reservation and the Spokane Tribe of Indians to support additional releases of water from Lake Roosevelt. Because the sovereign and proprietary interests of these tribal governments are directly affected by water levels in Lake Roosevelt, the state intends to share a portion of the benefits derived from Lake Roosevelt water releases and to mitigate for any impacts such releases may have upon the tribes.

. These new releases of Lake Roosevelt water of approximately eighty-two thousand five hundred acre feet of water, increasing to no more than one hundred thirty-two thousand five hundred acre feet of water in drought years, will bolster the state economy and will meet the following critical needs: New surface water supplies for farmers to replace the use of diminishing groundwater in the Odessa aquifer; new water supplies for municipalities with pending water right applications; enhanced certainty for agricultural water users with water rights that are interruptible during times of drought; and water to increase flows in the river when salmon need it most.

. Nothing in chapter 82, Laws of 2008 expands, impairs, or otherwise affects the existing status and sovereignty of the tribal governments involved in Lake Roosevelt water releases pursuant to this section and RCW 90.90.070.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6874-S2.SL.pdf?cite=2008%20c%2082%20§%201[2008 c 82 § 1]; ]

== 90.90.070 - Columbia river water delivery account—Creation—Distribution.
. The Columbia river water delivery account is created in the state treasury. Moneys in the account may be spent only after appropriation. The account consists of all moneys transferred or appropriated to the account by law. The legislature may appropriate moneys in the account:

.. For distributions for purposes of RCW 90.90.060 as provided in this section; and

.. To the department of ecology for other purposes relating to implementation of RCW 90.90.060 and 90.90.080.

. On July 1, 2008, and each July 1st thereafter for the duration of the agreements described in RCW 90.90.060, the state treasurer shall transfer moneys from the general fund into the Columbia river water delivery account in the amounts described in subsection (3) of this section.

. Subject to appropriations, on July 1, 2008, and each July 1st thereafter, the state treasurer shall distribute moneys from the Columbia river water delivery account as follows:

.. To the Confederated Tribes of the Colville Reservation, on July 1, 2008, the sum of three million seven hundred seventy-five thousand dollars; and on July 1, 2009, the sum of three million six hundred twenty-five thousand dollars. Each July 1st thereafter for the duration of the agreement, the treasurer shall distribute an amount equal to the previous year's distribution adjusted for inflation. The inflation adjustment shall be computed using the percentage change on the implicit price deflator for personal consumption expenditures for the United States for the previous calendar year, as compiled by the bureau of economic analysis of the United States department of commerce and reported in the most recent quarterly publication of the economic and revenue forecast council or successor agency.

.. To the Spokane Tribe of Indians, on July 1, 2008, the sum of two million two hundred fifty thousand dollars. Each July 1st thereafter for the duration of the agreement, the treasurer shall distribute an amount equal to the previous year's distribution adjusted for inflation. The inflation adjustment shall be computed using the percentage change in the consumer price index for the Washington state Seattle-Tacoma-Bremerton consolidated metropolitan statistical area for the previous calendar year as compiled by the bureau of labor statistics, United States department of labor, and reported in the most recent quarterly publication of the economic and revenue forecast council or successor agency.

. The state treasurer may not distribute moneys from the Columbia river water delivery account to a tribe pursuant to this section unless the director of ecology has certified in writing to the state treasurer and the legislature that the agreement with the tribes is still in effect.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6874-S2.SL.pdf?cite=2008%20c%2082%20§%202[2008 c 82 § 2]; ]

== 90.90.080 - Impacts of water release—Department of ecology's duties.
. Because the potential impacts of water releases under agreements reached under this chapter on affected counties are unknown, the department of ecology shall, by November 15, 2009:

.. Conduct an assessment of the potential impacts, including recommendations for mitigation, and report to [the] appropriate committees of the legislature; and

.. Establish a process for identifying and reporting on future impacts on the affected counties, and for making recommendations for mitigation.

. Within the framework of Columbia river basin water resources management under this chapter, the department of ecology shall:

.. Provide technical assistance to help affected counties identify and develop competitive project applications to benefit both instream and out-of-stream uses;

.. Assist affected counties in exploring options to ensure water resources are available for their current and future needs. Such options include pursuing a memorandum of understanding with the affected counties that is consistent with RCW 90.90.005 to effectuate the purposes of this section. The memorandum of understanding shall be available for public comment for a period of thirty days before being signed by the department; and

.. Consider regional equity when making funding decisions on water supply applications.

. As used in this section, "affected counties" means those counties east of the crest of the Cascade mountains with an international border, or those counties east of the crest of the Cascade mountains that border both a county with an international border and a county with four hundred thousand or more residents.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6874-S2.SL.pdf?cite=2008%20c%2082%20§%203[2008 c 82 § 3]; ]

== 90.90.090 - Columbia river basin taxable bond water supply development account—Water service contracts.
. The Columbia river basin taxable bond water supply development account is created in the state treasury. All receipts from direct appropriations from the legislature, moneys directed to the account pursuant to RCW 90.90.020 and 90.90.030, or moneys directed to the account from any other sources must be deposited in the account. Moneys in the account may be spent only after appropriation. The account is intended to fund projects using taxable bonds. Expenditures from the account may be used only as provided in this section.

. [Empty]
.. Expenditures from the Columbia river basin taxable bond water supply development account may be used to assess, plan, and develop new storage, improve or alter operations of existing storage facilities, implement conservation projects, develop pump exchanges, or any other actions designed to provide access to new water supplies within the Columbia river basin for both instream and out-of-stream uses. Except for the development of new storage projects and pump exchanges, there may be no expenditures from the account for water acquisition or transfers from one water resource inventory area to another without specific legislative authority. For the purposes of this section, the term "pump exchanges" means water supply development projects that exchange water from one source to another or relocate an existing diversion downstream, with resulting instream benefit.

.. Two-thirds of the moneys placed in the account must be used to support the development of new storage facilities and pump exchanges; the remaining one-third of the moneys must be used for the other purposes listed in this section.

. [Empty]
.. Funds may not be expended from the account for the construction of a new storage facility until the department of ecology evaluates the following:

... Water uses to be served by the facility;

... The quantity of water necessary to meet those uses;

... The benefits and costs to the state of meeting those uses, including short-term and long-term economic, cultural, and environmental effects; and

... Alternative means of supplying water to meet those uses, including the costs of those alternatives and an analysis of the extent to which long-term water supply needs can be met using these alternatives.

.. The department of ecology may rely on studies and information developed through compliance with other state and federal permit requirements and other sources. The department shall compile its findings and conclusions, and provide a summary of the information it reviewed.

.. Before finalizing its evaluation under the provisions of this section, the department of ecology shall make the preliminary evaluation available to the public. Public comment may be made to the department within thirty days of the date the preliminary evaluation is made public.

. Net water savings achieved through conservation measures funded by the account shall be placed in trust in proportion to the state funding provided to implement a project.

. Net water savings achieved through conservation measures funded by the account developed within the boundaries of the federal Columbia river reclamation project and directed to the Odessa subarea to reduce the use of groundwater for existing irrigation is exempt from the provisions of subsection (4) of this section.

. The department of ecology may enter into water service contracts with applicants receiving water from the program to recover all or a portion of the cost of developing the water supply. Costs recovered under water service contracts does not include staff time expended by the department on developing the water supply. With the applicant's concurrence, the department may receive power revenue generated by the water supply developed by the department through water service contracts. The department may deny an application if the applicant does not enter into a water service contract. Revenue collected from water service contracts must be deposited into the Columbia river basin water supply revenue recovery account created in RCW 90.90.100. The department may adopt rules describing the methodology as to how charges will be established and direct costs recovered for water supply developed under the Columbia river basin water supply program. Water service contracts with federal agencies under RCW 90.42.150 are not required to be established by rule.

. Interest earned by deposits in the account will be retained in the account.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1803-S2.SL.pdf?cite=2011%20c%2083%20§%202[2011 c 83 § 2]; ]

== 90.90.100 - Columbia river basin water supply revenue recovery account—Water service contracts.
. The Columbia river basin water supply revenue recovery account is created in the state treasury. All receipts from direct appropriations from the legislature, moneys directed to the account pursuant to RCW 90.90.020 and 90.90.030, revenue from water service contracts described in this chapter, or moneys directed into the account from any other sources must be deposited in the account. Moneys in the account may be spent only after appropriation. Expenditures from the account may be used only as provided in this section.

. [Empty]
.. Expenditures from the Columbia river basin water supply revenue recovery account may be used to assess, plan, and develop new storage, improve or alter operations of existing storage facilities, implement conservation projects, develop pump exchanges, or any other actions designed to provide access to new water supplies within the Columbia river basin for both instream and out-of-stream uses. Except for the development of new storage projects and pump exchanges, there may be no expenditures from the account for water acquisition or transfers from one water resource inventory area to another without specific legislative authority. For the purposes of this section, the term "pump exchanges" means water supply development projects that exchange water from one source to another or relocate an existing diversion downstream, with resulting instream benefit.

.. Two-thirds of the moneys placed in the account must be used to support the development of new storage facilities and pump exchanges; the remaining one-third of the moneys must be used for the other purposes listed in this section.

. [Empty]
.. Funds may not be expended from the account for the construction of a new storage facility until the department of ecology evaluates the following:

... Water uses to be served by the facility;

... The quantity of water necessary to meet those uses;

... The benefits and costs to the state of meeting those uses, including short-term and long-term economic, cultural, and environmental effects; and

... Alternative means of supplying water to meet those uses, including the costs of those alternatives and an analysis of the extent to which long-term water supply needs can be met using these alternatives.

.. The department of ecology may rely on studies and information developed through compliance with other state and federal permit requirements and other sources. The department shall compile its findings and conclusions, and provide a summary of the information it reviewed.

.. Before finalizing its evaluation under the provisions of this section, the department of ecology shall make the preliminary evaluation available to the public. Public comment may be made to the department within thirty days of the date the preliminary evaluation is made public.

. Net water savings achieved through conservation measures funded by the account shall be placed in trust in proportion to the state funding provided to implement a project.

. Net water savings achieved through conservation measures funded by the account developed within the boundaries of the federal Columbia river reclamation project and directed to the Odessa subarea to reduce the use of groundwater for existing irrigation is exempt from the provisions of subsection (4) of this section.

. The department of ecology may enter into water service contracts with applicants receiving water from the program to recover all or a portion of the cost of developing the water supply. Costs recovered under water service contracts does not include staff time expended by the department on developing the water supply. With the applicant's concurrence, the department may receive power revenue generated by the water supply developed by the department through water service contracts. The department may deny an application if the applicant does not enter into a water service contract. Revenue collected from water service contracts must be deposited into the Columbia river basin water supply revenue recovery account created in this section. The department may adopt rules describing the methodology as to how charges will be established and direct costs recovered for water supply developed under the Columbia river basin water supply program. Water service contracts with federal agencies under RCW 90.42.150 are not required to be established by rule.

. Interest earned by deposits in the account will be retained in the account.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1803-S2.SL.pdf?cite=2011%20c%2083%20§%203[2011 c 83 § 3]; ]

== 90.90.110 - Use of certain water made available through reoperation of Sullivan lake.
Two-thirds of the water made available through reoperation of Sullivan lake funded from the Columbia river basin water supply development account created in RCW 90.90.010 must be used to supply or offset out-of-stream uses described in RCW 90.90.020(3) in Douglas, Ferry, Lincoln, Okanogan, Pend Oreille, and Stevens counties. At least one-half of this quantity must be made available for municipal, domestic, and industrial uses.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1803-S2.SL.pdf?cite=2011%20c%2083%20§%205[2011 c 83 § 5]; ]

== 90.90.900 - Effective date—2006 c 6.
This act takes effect July 1, 2006.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2860-S2.SL.pdf?cite=2006%20c%206%20§%2010[2006 c 6 § 10]; ]

