= 51.14 - Self-insurers.
:toc:

== 51.14.010 - Duty to secure payment of compensation—Options.
Every employer under this title shall secure the payment of compensation under this title by:

. Insuring and keeping insured the payment of such benefits with the state fund; or

. Qualifying as a self-insurer under this title.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c289.pdf?cite=1971%20ex.s.%20c%20289%20§%2026[1971 ex.s. c 289 § 26]; ]

== 51.14.020 - Qualification.
. An employer may qualify as a self-insurer by establishing to the director's satisfaction that he or she has sufficient financial ability to make certain the prompt payment of all compensation under this title and all assessments which may become due from such employer. Each application for certification as a self-insurer submitted by an employer shall be accompanied by payment of a fee of one hundred fifty dollars or such larger sum as the director shall find necessary for the administrative costs of evaluation of the applicant's qualifications. Any employer who has formerly been certified as a self-insurer and thereafter ceases to be so certified may not apply for certification within three years of ceasing to have been so certified.

. [Empty]
.. A self-insurer may be required by the director to supplement existing financial ability by depositing in an escrow account in a depository designated by the director, money and/or corporate or governmental securities approved by the director, or a surety bond written by any company admitted to transact surety business in this state, or provide an irrevocable letter of credit issued by a federally or state chartered commercial banking institution authorized to conduct business in the state of Washington filed with the department. The money, securities, bond, or letter of credit shall be in an amount reasonably sufficient in the director's discretion to insure payment of reasonably foreseeable compensation and assessments but not less than the employer's normal expected annual claim liabilities and in no event less than one hundred thousand dollars. In arriving at the amount of money, securities, bond, or letter of credit required under this subsection, the director shall take into consideration the financial ability of the employer to pay compensation and assessments and his or her probable continuity of operation. However, a letter of credit shall be acceptable only if the self-insurer has a net worth of not less than five hundred million dollars as evidenced in an annual financial statement prepared by a qualified, independent auditor using generally accepted accounting principles. The money, securities, bond, or letter of credit so deposited shall be held by the director solely for the payment of compensation by the self-insurer and his or her assessments. In the event of default the self-insurer loses all right and title to, any interest in, and any right to control the surety. The amount of surety may be increased or decreased from time to time by the director. The income from any securities deposited may be distributed currently to the self-insurer.

.. The letter of credit option authorized in (a) of this subsection shall not apply to self-insurers authorized under RCW 51.14.150 or to self-insurers who are counties, cities, or municipal corporations.

. Securities or money deposited by an employer pursuant to subsection (2) of this section shall be returned to him or her upon his or her written request provided the employer files the bond required by such subsection.

. If the employer seeking to qualify as a self-insurer has previously insured with the state fund, the director shall require the employer to make up his or her proper share of any deficit or insufficiency in the state fund as a condition to certification as a self-insurer.

. A self-insurer may reinsure a portion of his or her liability under this title with any reinsurer authorized to transact such reinsurance in this state: PROVIDED, That the reinsurer may not participate in the administration of the responsibilities of the self-insurer under this title. Such reinsurance may not exceed eighty percent of the liabilities under this title.

. For purposes of the application of this section, the department may adopt separate rules establishing the security requirements applicable to units of local government. In setting such requirements, the department shall take into consideration the ability of the governmental unit to meet its self-insured obligations, such as but not limited to source of funds, permanency, and right of default.

. The director shall adopt rules to carry out the purposes of this section including, but not limited to, rules respecting the terms and conditions of letters of credit and the establishment of the appropriate level of net worth of the self-insurer to qualify for use of the letter of credit. Only letters of credit issued in strict compliance with the rules shall be deemed acceptable.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5668.SL.pdf?cite=1995%20c%2031%20§%201[1995 c 31 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c209.pdf?cite=1990%20c%20209%20§%201[1990 c 209 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c57.pdf?cite=1986%20c%2057%20§%201[1986 c 57 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c323.pdf?cite=1977%20ex.s.%20c%20323%20§%209[1977 ex.s. c 323 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c43.pdf?cite=1972%20ex.s.%20c%2043%20§%2016[1972 ex.s. c 43 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c289.pdf?cite=1971%20ex.s.%20c%20289%20§%2027[1971 ex.s. c 289 § 27]; ]

== 51.14.030 - Certification of employer as self-insurer.
The director may issue a certification that an employer is qualified as a self-insurer when such employer meets the following requirements:

. He or she has fulfilled the requirements of RCW 51.14.020.

. He or she has submitted to the department a payroll report for the preceding consecutive twelve-month period.

. He or she has submitted to the department a sworn itemized statement accompanied by an independent audit of the employer's books demonstrating to the director's satisfaction that the employer has sufficient liquid assets to meet his or her estimated liabilities as a self-insurer.

. He or she has demonstrated to the department the existence of the safety organization maintained by him or her within his or her establishment that indicates a record of accident prevention.

. He or she has submitted to the department a description of the administrative organization to be maintained by him or her to manage industrial insurance matters including:

.. The reporting of injuries;

.. The authorization of medical care;

.. The payment of compensation;

.. The handling of claims for compensation;

.. The name and location of each business location of the employer; and

.. The qualifications of the personnel of the employer to perform this service.

. He or she has demonstrated to the department the ability and commitment to submit electronically the claims [data] required by RCW 51.14.110.

Such certification shall remain in effect until withdrawn by the director or surrendered by the employer with the approval of the director. An employer's qualification as a self-insurer shall become effective on the date of certification or any date specified in the certificate after the date of certification.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1310-S.SL.pdf?cite=2005%20c%20145%20§%203[2005 c 145 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c323.pdf?cite=1977%20ex.s.%20c%20323%20§%2010[1977 ex.s. c 323 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c289.pdf?cite=1971%20ex.s.%20c%20289%20§%2028[1971 ex.s. c 289 § 28]; ]

== 51.14.040 - Surety liability—Termination.
. The surety on a bond filed by a self-insurer pursuant to this title may terminate its liability thereon by giving the director written notice stating when, not less than thirty days thereafter, such termination shall be effective.

. In case of such termination, the surety shall remain liable, in accordance with the terms of the bond, with respect to future compensation for injuries to employees of the self-insurer occurring prior to the termination of the surety's liability.

. If the bond is terminated for any reason other than the employer's terminating his or her status as a self-insurer, the employer shall, prior to the date of termination of the surety's liability, otherwise comply with the requirements of this title.

. The liability of a surety on any bond filed pursuant to this section shall be released and extinguished and the bond returned to the employer or surety provided either such liability is secured by another bond filed, or money or securities deposited as required by this title.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%2014003[2010 c 8 § 14003]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c289.pdf?cite=1971%20ex.s.%20c%20289%20§%2029[1971 ex.s. c 289 § 29]; ]

== 51.14.050 - Termination of status—Notice—Financial requirements.
. Any employer may at any time terminate his or her status as a self-insurer by giving the director written notice stating when, not less than thirty days thereafter, such termination shall be effective, provided such termination shall not be effective until the employer either shall have ceased to be an employer or shall have filed with the director for state industrial insurance coverage under this title.

. An employer who ceases to be a self-insurer, and who so files with the director, must maintain money, securities, or surety bonds deemed sufficient in the director's discretion to cover the entire liability of such employer for injuries or occupational diseases to his or her employees which occurred during the period of self-insurance: PROVIDED, That the director may agree for the medical aid and accident funds to assume the obligation of such claims, in whole or in part, and shall adjust the employer's premium rate to provide for the payment of such obligations on behalf of the employer.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%2014004[2010 c 8 § 14004]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c289.pdf?cite=1971%20ex.s.%20c%20289%20§%2030[1971 ex.s. c 289 § 30]; ]

== 51.14.060 - Default by self-insurer—Authority of director—Liability for reimbursement.
. The director may, in cases of default upon any obligation under this title by the self-insurer, after ten days notice by certified mail to the defaulting self-insurer of the intention to do so, bring suit upon such bond or collect the interest and principal of any of the securities as they may become due or sell the securities or any of them as may be required or apply the money deposited, all in order to pay compensation and discharge the obligations of the defaulting self-insurer under this title.

. The director shall be authorized to fulfill the defaulting self-insured employer's obligations under this title from the defaulting self-insured employer's deposit or from other funds provided under this title for the satisfaction of claims against the defaulting self-insured employer. The defaulting self-insured employer is liable to and shall reimburse the director for the amounts necessary to fulfill the obligations of the defaulting self-insured employer that are in excess of the amounts received by the director from any bond filed, or securities or money deposited, by the defaulting self-insured employer pursuant to chapter 51.14 RCW. The amounts to be reimbursed shall include all amounts paid or payable as compensation under this title together with administrative costs, including attorneys' fees, and shall be considered taxes due the state of Washington.

. The department shall transfer the balance of any defaulted self-insured employer's deposit as required by RCW 51.14.020 into the insolvency trust fund when the following have occurred:

.. All claims against the defaulted self-insured employer are closed; and

.. The self-insured employer has been in default for ten years.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/3061.SL.pdf?cite=2010%20c%20213%20§%202[2010 c 213 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c57.pdf?cite=1986%20c%2057%20§%202[1986 c 57 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c289.pdf?cite=1971%20ex.s.%20c%20289%20§%2031[1971 ex.s. c 289 § 31]; ]

== 51.14.070 - Payments upon default.
Whenever compensation due under this title is not paid because of an uncorrected default of a self-insurer, such compensation shall be paid from the medical aid and accidents funds, and any moneys obtained by the director from the bonds or other security provided under RCW 51.14.020 shall be deposited to the appropriate fund for the payment of compensation and administrative costs, including attorneys' fees.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c57.pdf?cite=1986%20c%2057%20§%203[1986 c 57 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c289.pdf?cite=1971%20ex.s.%20c%20289%20§%2036[1971 ex.s. c 289 § 36]; ]

== 51.14.073 - Default lien.
. In all cases of probate, insolvency, assignment for the benefit of creditors, or bankruptcy, the claim of the state for the amounts necessary to fulfill the obligations of a defaulting self-insured employer together with administrative costs and attorneys' fees is a lien prior to all other liens or claims and on a parity with prior tax liens and the mere existence of a default by a self-insured employer is sufficient to create the lien without any prior or subsequent action by the state. All administrators, receivers, and assignees for the benefit of creditors shall notify the director of such administration, receivership, or assignment within thirty days of their appointment or qualification.

. Separate and apart and in addition to the lien established by this section, the department may issue an assessment, as provided for in RCW 51.48.120, for the amount necessary to fulfill the defaulting self-insured employer's obligations, including all amounts paid and payable as compensation under this title and administrative costs, including attorneys' fees.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c57.pdf?cite=1986%20c%2057%20§%204[1986 c 57 § 4]; ]

== 51.14.077 - Self-insurers' insolvency trust—Assessments—Rules.
. A self-insurers' insolvency trust is established to provide for the unsecured benefits paid to the injured workers of self-insured employers under this title for insolvent or defaulting self-insured employers and for the department's associated administrative costs, including attorneys' fees. The self-insurers' insolvency trust shall be funded by an insolvency assessment which shall be levied on a post-insolvency basis and after the defaulting self-insured employer's security deposit, assets, and reinsurance, if any, have been exhausted. Insolvency assessments shall be imposed on all self-insured employers, except school districts, cities, and counties. The manner of imposing and collecting assessments to the insolvency fund shall be set forth in rules adopted by the department to ensure that self-insured employers pay into the fund in proportion to their claim costs. The department's rules shall provide that self-insured employers who have surrendered their certification shall be assessed for a period of not more than three calendar years following the termination date of their certification.

. The director shall adopt rules to carry out the purposes of this section, including but not limited to:

.. Governing the formation of the self-insurers' insolvency trust for the purpose of this chapter;

.. Governing the organization and operation of the self-insurers' insolvency trust to assure compliance with the requirements of this chapter;

.. Requiring adequate accountability of the collection and disbursement of funds in the self-insurers' insolvency trust; and

.. Any other provisions necessary to carry out the requirements of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c57.pdf?cite=1986%20c%2057%20§%206[1986 c 57 § 6]; ]

== 51.14.080 - Withdrawal of certification—Grounds.
Certification of a self-insurer shall be withdrawn by the director upon one or more of the following grounds:

. The employer no longer meets the requirements of a self-insurer; or

. The self-insurer's deposit is insufficient; or

. The self-insurer intentionally or repeatedly induces employees to fail to report injuries, induces claimants to treat injuries in the course of employment as off-the-job injuries, persuades claimants to accept less than the compensation due, or unreasonably makes it necessary for claimants to resort to proceedings against the employer to obtain compensation; or

. The self-insurer habitually fails to comply with rules and regulations of the director regarding reports or other requirements necessary to carry out the purposes of this title; or

. The self-insurer habitually engages in a practice of arbitrarily or unreasonably refusing employment to applicants for employment or discharging employees because of nondisabling bodily conditions; or

. The self-insurer fails to pay an insolvency assessment under the procedures established pursuant to RCW 51.14.077.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c57.pdf?cite=1986%20c%2057%20§%207[1986 c 57 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c289.pdf?cite=1971%20ex.s.%20c%20289%20§%2032[1971 ex.s. c 289 § 32]; ]

== 51.14.090 - Withdrawal of certification, corrective action upon employees' petition.
. Upon the petition of any employee or union or association having a substantial number of employees in the employ of the self-insurer the director or the director's designee may, in the director or designee's sole discretion, hold a hearing to determine whether or not there are grounds for the withdrawal of certification of a self-insurer or for corrective action by the department.

. The director shall serve upon the self-insurer and upon any employee or union or association having a substantial number of employees in the employ of said self-insurer, personally or by certified mail, a notice of intention to withdraw, or not to withdraw, certification of the self-insurer, which notice shall describe the nature and location or locations of the plants or operations involved; and the specific nature of the reasons for the decision. Similar notice shall be provided for decisions regarding corrective actions. The corrective action notice shall also include a directive to the self-insurer specifying the program deficiencies to be eliminated.

. If the decision is to withdraw certification, it shall include: The period of time within which the ground or grounds therefor existed or arose; and the date, not less than ninety days after the self-insurer's receipt of the notice, when the certification will be withdrawn.

. An appeal of any action taken by the director under this section may be taken by the self-insurer, or by any employee or union or association having a substantial number of employees in the employ of the self-insurer. Proceedings on the appeal shall be as prescribed in this title. Appeal by a self-insurer of notice of intention to withdraw certification or to take corrective action shall not act as a stay of the withdrawal or corrective action, unless the board or court, for good cause shown, orders otherwise.

. The director may adopt rules to carry out the purposes of this section.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6222.SL.pdf?cite=1996%20c%2058%20§%201[1996 c 58 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c21.pdf?cite=1983%20c%2021%20§%201[1983 c 21 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c289.pdf?cite=1971%20ex.s.%20c%20289%20§%2033[1971 ex.s. c 289 § 33]; ]

== 51.14.095 - Corrective action—Appeal.
. The director shall take corrective action against a self-insured employer if the director determines that:

.. The employer is not following proper industrial insurance claims procedures;

.. The employer's accident prevention program is inadequate; or

.. Any condition described in RCW 51.14.080 (1) through (5) exists.

. Corrective actions may be taken upon the director's initiative or in response to a petition filed under RCW 51.14.090. Corrective actions which may be taken by the director shall include:

.. Probationary certification for a period of time determined by the director;

.. Mandatory training for employers in areas including claims management, safety procedures, and administrative reporting requirements; and

.. Monitoring of the activities of the employer to determine progress towards compliance.

The director shall adopt rules defining the corrective actions which may be taken in response to a given condition.

Corrective actions shall be limited to those described in (a), (b), and (c) of this subsection.

. Upon the termination of the corrective action, the director shall review the employer's program for compliance with state statutes and regulations. A written report regarding the employer's compliance shall be provided to the employer and to any party to a petition filed under RCW 51.14.090. If the director determines that compliance has been attained, no further action shall be taken. If compliance has not been attained, the director may take additional corrective action as defined in this section, or proceed toward decertification as described in RCW 51.14.080.

. An employer may appeal any action taken by the director under this section. Proceedings during the appeal shall be as prescribed in this title. An appeal by a self-insurer shall not act as a stay of the corrective action, unless the board or court, for good cause shown, orders otherwise.

. This section shall not be construed to limit the responsibilities or authority of the department under RCW 51.14.080 or 51.14.090.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c21.pdf?cite=1983%20c%2021%20§%202[1983 c 21 § 2]; ]

== 51.14.100 - Notice of compliance to be posted—Penalty.
. Every employer subject to the provisions of this title shall post and keep posted in a conspicuous place or places in and about his or her place or places of business a reasonable number of typewritten or printed notices of compliance substantially identical to a form prescribed by the director, stating that such employer is subject to the provisions of this title. Such notice shall advise whether the employer is self-insured or has insured with the department, and shall designate a person or persons on the premises to whom report of injury shall be made.

. Any employer who has failed to open an account with the department or qualify as a self-insurer shall not post or permit to be posted on or about his or her place of business or premises any notice of compliance with this title and any wilful violation of this subsection by any officer or supervisory employee of an employer shall be a misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%2014005[2010 c 8 § 14005]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c289.pdf?cite=1971%20ex.s.%20c%20289%20§%2034[1971 ex.s. c 289 § 34]; ]

== 51.14.110 - Employer's duty to maintain records, furnish information—Electronic reporting system—Requirement and penalties—Confidentiality of claims data—Rules.
. Every self-insurer shall maintain a record of all payments of compensation made under this title. The self-insurer shall furnish to the director all information the self-insurer has in its possession as to any disputed claim, upon forms approved by the director.

. [Empty]
.. The department shall establish an electronic reporting system for the submission to the department of specified self-insurance claims data to more effectively monitor the performance of self-insurers and to obtain claims information in an efficient manner.

.. Self-insurers shall submit claims data electronically in the format and frequency prescribed by the department.

.. Electronic submittal to the department of specified claims data is required to maintain self-insurance certification. The department shall establish an escalating schedule of penalties for noncompliance with this requirement, up to and including withdrawal of self-insurance certification.

.. Claims data reported to the department electronically by individual self-insurers are confidential in accordance with RCW 51.16.070 and 51.28.070. The department may publish, for statistical purposes, aggregated claims data that contain no personal identifiers.

. The department shall adopt rules to administer this section.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1310-S.SL.pdf?cite=2005%20c%20145%20§%202[2005 c 145 § 2]; 2005 c 145 § 1; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c289.pdf?cite=1971%20ex.s.%20c%20289%20§%2035[1971 ex.s. c 289 § 35]; ]

== 51.14.120 - Copy of claim file—Notice of protest or appeal—Medical report.
. The self-insurer shall provide, when authorized under RCW 51.28.070, a copy of the employee's claim file at no cost within fifteen days of receipt of a request by the employee or the employee's representative, and shall provide the physician performing an examination with all relevant medical records from the worker's claim file, but only to the extent required of the department under RCW 51.36.070. If the self-insured employer determines that release of the claim file to an unrepresented worker in whole or in part, may not be in the worker's best interests, the employer must submit a request for denial with an explanation along with a copy of that portion of the claim file not previously provided within twenty days after the request from the worker. In the case of second or subsequent requests, a reasonable charge for copying may be made. The self-insurer shall provide the entire contents of the claim file unless the request is for only a particular portion of the file. Any new material added to the claim file after the initial request shall be provided under the same terms and conditions as the initial request.

. The self-insurer shall transmit notice to the department of any protest or appeal by an employee relating to the administration of an industrial injury or occupational disease claim under this chapter within five working days of receipt. The date that the protest or appeal is received by the self-insurer shall be deemed to be the date the protest is received by the department for the purpose of RCW 51.52.050.

. The self-insurer shall submit a medical report with the request for closure of a claim under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5205-S.SL.pdf?cite=2001%20c%20152%20§%201[2001 c 152 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5515-S.SL.pdf?cite=1993%20c%20122%20§%202[1993 c 122 § 2]; ]

== 51.14.130 - Request for claim resolution—Time.
The self-insurer shall request allowance or denial of a claim within sixty days from the date that the claim is filed. If the self-insurer fails to act within sixty days, the department shall promptly intervene and adjudicate the claim.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5515-S.SL.pdf?cite=1993%20c%20122%20§%203[1993 c 122 § 3]; ]

== 51.14.140 - Violations of disclosure or request for resolution—Order by director.
Failure of a self-insurer to comply with RCW 51.14.120 and 51.14.130 shall subject the self-insurer to a penalty under RCW 51.48.080, which shall accrue for the benefit of the employee. The director shall issue an order conforming with RCW 51.52.050 determining whether a violation has occurred within thirty days of a request by an employee.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5515-S.SL.pdf?cite=1993%20c%20122%20§%204[1993 c 122 § 4]; ]

== 51.14.150 - School districts, ESDs, public hospital districts, or hospitals as self-insurers—Authorized—Organization—Qualifications.
. For the purposes of this section, "hospital" means a hospital as defined in *RCW 70.41.020(2) or a psychiatric hospital regulated under chapter 71.12 RCW, but does not include beds utilized by a comprehensive cancer center for cancer research.

. [Empty]
.. Any two or more employers which are school districts or educational service districts, or (b) any two or more employers which are public hospital districts or hospitals, and are owned or operated by a state agency or municipal corporation of this state, or (c) any two or more employers which are hospitals, no one of which is owned or operated by a state agency or municipal corporation of this state, may enter into agreements to form self-insurance groups for the purposes of this chapter.

. No more than one group may be formed under subsection (2)(b) of this section and no more than one group may be formed under subsection (2)(c) of this section.

. The self-insurance groups shall be organized and operated under rules promulgated by the director under RCW 51.14.160. Such a self-insurance group shall be deemed an employer for the purposes of this chapter, and may qualify as a self-insurer if it meets all the other requirements of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5211.SL.pdf?cite=1997%20c%2035%20§%201[1997 c 35 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1351.SL.pdf?cite=1993%20c%20158%20§%201[1993 c 158 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c174.pdf?cite=1983%20c%20174%20§%202[1983 c 174 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c191.pdf?cite=1982%20c%20191%20§%207[1982 c 191 § 7]; ]

== 51.14.160 - School districts, ESDs, or hospitals as self-insurers—Rules—Scope.
The director shall promulgate rules to carry out the purposes of RCW 51.14.150:

. Governing the formation of self-insurance groups for the purposes of this chapter;

. Governing the organization and operation of the groups to assure their compliance with the requirements of this chapter;

. Requiring adequate monetary reserves, determined under accepted actuarial practices, to be maintained by each group to assure financial solvency of the group; and

. Requiring each group to carry adequate reinsurance.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c174.pdf?cite=1983%20c%20174%20§%203[1983 c 174 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c191.pdf?cite=1982%20c%20191%20§%208[1982 c 191 § 8]; ]

== 51.14.170 - Administration of claims—Third-party administrators.
. Self-insured employers may elect to have their claims administered by a third party or they may elect to self-administer their claims. Third-party administrators given the responsibility of administering the claims of workers by an employer shall be licensed by the department. All employer claims administrators given the responsibility of administering the claims of workers shall maintain certification established by the department.

. The department shall adopt rules to administer this section. The rules for licensing third-party administrators must:

.. Incorporate the department's rules for self-insurers in effect as of March 2020;

.. Include criteria for determining appropriate penalties for violation of their responsibilities and duties, including managing claims, engaging in the department's management of claims, coordinating proper employment of injured workers during the pendency of the worker's claim, making requests of the department in individual cases, or participating in appeals involving a worker's benefits in a way that furthers the purpose of this title;

.. Consider recognized and approved claim processing practices within the industrial insurance industry, and the industrial insurance laws and rules of this state;

.. Consider similar licensure rules under the insurance laws and rules of this state; and

.. Include requirements for maintaining a license, and any penalties for violation of those licensing requirements.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2409-S.SL.pdf?cite=2020%20c%20277%20§%208[2020 c 277 § 8]; ]

== 51.14.300 - Ombuds office created—Appointment—Open and competitive contracting.
The office of the ombuds for workers of industrial insurance self-insured employers is created. The ombuds shall be appointed by the governor and report directly to the director of the department. The office of the ombuds may be openly and competitively contracted by the governor in accordance with chapter 39.26 RCW but shall not be physically housed within the industrial insurance division.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20105[2013 c 23 § 105]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5053-S.SL.pdf?cite=2007%20c%20281%20§%201[2007 c 281 § 1]; ]

== 51.14.310 - Ombuds—Term of office—Removal—Vacancies.
The person appointed ombuds shall hold office for a term of six years and shall continue to hold office until reappointed or until his or her successor is appointed. The governor may remove the ombuds only for neglect of duty, misconduct, or inability to perform duties. Any vacancy shall be filled by similar appointment for the remainder of the unexpired term.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20106[2013 c 23 § 106]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5053-S.SL.pdf?cite=2007%20c%20281%20§%202[2007 c 281 § 2]; ]

== 51.14.320 - Ombuds—Training or experience qualifications.
Any ombuds appointed under this chapter shall have training or experience, or both, in the following areas:

. Washington state industrial insurance including self-insurance programs;

. The Washington state legal system;

. Dispute or problem resolution techniques, including investigation, mediation, and negotiation.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20107[2013 c 23 § 107]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5053-S.SL.pdf?cite=2007%20c%20281%20§%203[2007 c 281 § 3]; ]

== 51.14.330 - Ombuds office—Staffing level.
During the first two years after the office of the ombuds is created, the staffing level shall be no more than four persons, including the ombuds and any administrative staff. Thereafter, the staffing levels shall be determined based upon the office of the ombuds's workload and whether any additional locations are needed.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20108[2013 c 23 § 108]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5053-S.SL.pdf?cite=2007%20c%20281%20§%204[2007 c 281 § 4]; ]

== 51.14.340 - Ombuds office—Powers and duties.
The office of the ombuds shall have the following powers and duties:

. To act as an advocate for injured workers of self-insured employers;

. To offer and provide information on industrial insurance as appropriate to workers of self-insured employers;

. To identify, investigate, and facilitate resolution of industrial insurance complaints from workers of self-insured employers;

. To maintain a statewide toll-free telephone number for the receipt of complaints and inquiries; and

. To refer complaints to the department when appropriate.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20109[2013 c 23 § 109]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5053-S.SL.pdf?cite=2007%20c%20281%20§%205[2007 c 281 § 5]; ]

== 51.14.350 - Ombuds office—Referral procedures—Department response to referred complaints.
. The office of the ombuds shall develop referral procedures for complaints by workers of self-insured employers. The department shall act as quickly as possible on any complaint referred to them by the office of the ombuds.

. The department shall respond to any complaint against a self-insured employer referred to it by the office of the ombuds and shall forward the office of the ombuds a summary of the results of the investigation and action proposed or taken.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20110[2013 c 23 § 110]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5053-S.SL.pdf?cite=2007%20c%20281%20§%206[2007 c 281 § 6]; ]

== 51.14.360 - Ombuds liability—Discriminatory, disciplinary, or retaliatory actions—Communications privileged and confidential—Testimony.
. No ombuds is liable for good faith performance of responsibilities under this chapter.

. No discriminatory, disciplinary, or retaliatory action may be taken against any employee of a self-insured employer for any communication made, or information given or disclosed, to assist the ombuds in carrying out its duties and responsibilities, unless the same was done maliciously. This subsection is not intended to infringe on the rights of the employer to supervise, discipline, or terminate an employee for other reasons.

. All communications by the ombuds, if reasonably related to the requirements of his or her responsibilities under this chapter and done in good faith, are privileged and confidential, and this shall serve as a defense to any action in libel or slander.

. Representatives of the office of the ombuds are exempt from being required to testify as to any privileged or confidential matters except as the court may deem necessary to enforce this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20111[2013 c 23 § 111]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5053-S.SL.pdf?cite=2007%20c%20281%20§%207[2007 c 281 § 7]; ]

== 51.14.370 - Confidentiality of ombuds records and files—Disclosure prohibited—Exception.
All records and files of the ombuds relating to any complaint or investigation made pursuant to carrying out its duties and the identities of complainants, witnesses, or injured workers shall remain confidential unless disclosure is authorized by the complainant or injured worker or his or her guardian or legal representative. No disclosures may be made outside the office of the ombuds without the consent of any named witness or complainant unless the disclosure is made without the identity of any of these individuals being disclosed.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20112[2013 c 23 § 112]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5053-S.SL.pdf?cite=2007%20c%20281%20§%208[2007 c 281 § 8]; ]

== 51.14.380 - Explaining ombuds program—Posters and brochures.
The ombuds shall integrate into existing posters and brochures information explaining the ombuds program. Both the posters and the brochures shall contain the ombuds's toll-free telephone number. Every self-insured employer must place a poster in an area where all workers have access to it. The self-insured employer must provide a brochure to all injured workers at the time the employer is notified of the worker's injury.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20113[2013 c 23 § 113]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5053-S.SL.pdf?cite=2007%20c%20281%20§%209[2007 c 281 § 9]; ]

== 51.14.390 - Ombuds office—Funding.
. To provide start-up funding for the office of the ombuds, the department shall impose a one-time assessment on all self-insurers. The amount of the assessment shall be determined by the department and shall not exceed the amount needed to pay the start-up costs.

. Ongoing funding for the office of the ombuds shall be obtained as part of an annual administrative assessment of self-insurers under RCW 51.44.150. This assessment shall be proportionately based on the number of claims for each self-insurer during the past year.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20114[2013 c 23 § 114]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5053-S.SL.pdf?cite=2007%20c%20281%20§%2010[2007 c 281 § 10]; ]

== 51.14.400 - Ombuds—Annual report to governor.
. The ombuds shall provide the governor with an annual report that includes the following:

.. A description of the issues addressed during the past year and a very brief description of case scenarios in a form that does not compromise confidentiality;

.. An accounting of the monitoring activities by the ombuds; and

.. An identification of the deficiencies in the industrial insurance system related to self-insurers, if any, and recommendations for remedial action in policy or practice.

. The first annual report shall be due on or before October 1, 2008. Subsequent reports shall be due on or before October 1st.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20115[2013 c 23 § 115]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5053-S.SL.pdf?cite=2007%20c%20281%20§%2012[2007 c 281 § 12]; ]

