= 51.98 - Construction.
:toc:

== 51.98.010 - Continuation of existing law.
The provisions of this title insofar as they are substantially the same as statutory provisions repealed by this chapter, and relating to the same subject matter, shall be construed as restatements and continuations, and not as new enactments.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c23.pdf?cite=1961%20c%2023%20§%2051.98.010[1961 c 23 § 51.98.010]; ]

== 51.98.020 - Title, chapter, section headings not part of law.
Title headings, chapter headings, and section or subsection headings, as used in this title do not constitute any part of the law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c23.pdf?cite=1961%20c%2023%20§%2051.98.020[1961 c 23 § 51.98.020]; ]

== 51.98.030 - Invalidity of part of title not to affect remainder.
If any provision of this title, or its application to any person or circumstance is held invalid, the remainder of the title, or the application of the provision to other persons or circumstances is not affected: PROVIDED, That nothing in this section shall affect or invalidate any of the provisions of RCW 51.04.090.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c23.pdf?cite=1961%20c%2023%20§%2051.98.030[1961 c 23 § 51.98.030]; ]

== 51.98.040 - Repeals and saving.
See 1961 c 23 s 51.98.040.

[ ]

== 51.98.050 - Emergency—1961 c 23.
This act is necessary for the immediate preservation of the public peace, health and safety, the support of the state government and its existing public institutions, and shall take effect immediately.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c23.pdf?cite=1961%20c%2023%20§%2051.98.050[1961 c 23 § 51.98.050]; ]

== 51.98.060 - Effective dates—1971 ex.s. c 289.
The provisions of this 1971 amendatory act are necessary for the immediate preservation of the public peace, health and safety, the support of the state government and its existing public institutions, and shall take effect on July 1, 1971: PROVIDED, That RCW 51.08.070 as amended by section 1 of this 1971 amendatory act, RCW 51.12.010 as amended in section 2 of this 1971 amendatory act, RCW 51.12.020 as amended in section 3 of this 1971 amendatory act and RCW 51.16.110 as amended in section 4 of this 1971 amendatory act shall take effect and become operative without any further action of the legislature on January 1, 1972.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c289.pdf?cite=1971%20ex.s.%20c%20289%20§%2090[1971 ex.s. c 289 § 90]; ]

== 51.98.070 - Severability—1971 ex.s. c 289.
If any provision of this 1971 amendatory act, or its application to any person or circumstance is held invalid, the remainder of the act, or the application of the provision to other persons or circumstances is not affected: PROVIDED, That nothing in this section shall affect or invalidate any of the provisions of RCW 51.04.090.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c289.pdf?cite=1971%20ex.s.%20c%20289%20§%2091[1971 ex.s. c 289 § 91]; ]

