= 78.06 - Mining claims—Survey reports.
:toc:

== 78.06.010 - Definitions.
Words or terms used herein have the following meanings:

. "Geological surveys" means surveys on the ground for mineral deposits by the proper application of the principles and techniques of the science of geology as they relate to the search for and discovery of mineral deposits.

. "Geochemical surveys" means surveys on the ground for mineral deposits by the proper application of the principles and techniques of the science of chemistry as they relate to the search for and discovery of mineral deposits.

. "Geophysical surveys" means surveys on the ground for mineral deposits through the employment of generally recognized equipment and methods for measuring physical differences between rock types or discontinuities in geological formations.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c119.pdf?cite=1959%20c%20119%20§%201[1959 c 119 § 1]; ]

== 78.06.020 - Duplicate survey reports to be filed with county auditor—Contents.
All reports of geological, geophysical, or geochemical surveys on mining claims which may be filed with the auditor of any county in this state pursuant to United States Public Law 85-876 or amendments or revisions thereto shall be so filed in duplicate, and shall set forth fully:

. The location of the survey performed in relation to the point of discovery and boundaries of the claim.

. The nature, extent, and cost of the survey.

. The date the survey was commenced and the date completed.

. The basic findings therefrom.

. The name, address, and professional background of the person or persons performing or conducting the survey.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c119.pdf?cite=1959%20c%20119%20§%202[1959 c 119 § 2]; ]

== 78.06.030 - Auditor to forward survey reports to department of natural resources.
All county auditors receiving for filing duplicate copies of geological, geochemical, and geophysical survey reports on mining claims shall forward, monthly, one copy of each report received to the department of natural resources.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c127.pdf?cite=1988%20c%20127%20§%2031[1988 c 127 § 31]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c119.pdf?cite=1959%20c%20119%20§%203[1959 c 119 § 3]; ]

