= 78.56 - Metals mining and milling operations.
:toc:

== 78.56.010 - Intent.
It is in the best interests of the citizens of the state of Washington to insure the highest degree of environmental protection while allowing the proper development and use of its natural resources, including its mineral resources. Metals mining can have significant positive and adverse impacts on the state and on local communities. The purpose of this chapter is to assure that metals mineral mining or milling operations are designed, constructed, and operated in a manner that promotes both economic opportunities and environmental and public health safeguards for the citizens of the state. It is the intent of the legislature to create a regulatory framework which yields, to the greatest extent possible, a metals mining industry that is compatible with these policies.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2521-S.SL.pdf?cite=1994%20c%20232%20§%201[1994 c 232 § 1]; ]

== 78.56.020 - Definitions.
The definitions set forth in this section apply throughout this chapter.

. "Metals mining and milling operation" means a mining operation extracting from the earth precious or base metal ore and processing the ore by treatment or concentration in a milling facility. It also refers to an expansion of an existing operation or any new metals mining operation if the expansion or new mining operation is likely to result in a significant, adverse environmental impact pursuant to the provisions of chapter 43.21C RCW. The extraction of dolomite, sand, gravel, aggregate, limestone, magnesite, silica rock, and zeolite or other nonmetallic minerals; and placer mining; and the smelting of aluminum are not metals mining and milling operations regulated under this chapter.

. "Milling" means the process of grinding or crushing ore and extracting the base or precious metal by chemical solution, electro winning, or flotation processes.

. "Heap leach extraction process" means the process of extracting base or precious metal ore by percolating solutions through ore in an open system and includes reprocessing of previously milled ore. The heap leach extraction process does not include leaching in a vat or tank.

. "In situ extraction" means the process of dissolving base or precious metals from their natural place in the geological setting and retrieving the solutions from which metals can be recovered.

. "Regulated substances" means any materials regulated under a waste discharge permit pursuant to the requirements of chapter 90.48 RCW and/or a permit issued pursuant to chapter 70A.15 RCW.

. "To mitigate" means: (a) To avoid the adverse impact altogether by not taking a certain action or parts of an action; (b) to minimize adverse impacts by limiting the degree or magnitude of the action and its implementation, by using appropriate technology or by taking affirmative steps to avoid or reduce impacts; (c) to rectify adverse impacts by repairing, rehabilitating, or restoring the affected environment; (d) to reduce or eliminate adverse impacts over time by preservation and maintenance operations during the life of the action; (e) to compensate for the impact by replacing, enhancing, or providing substitute resources or environments; or (f) to monitor the adverse impact and take appropriate corrective measures.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1192.SL.pdf?cite=2021%20c%2065%20§%2084[2021 c 65 § 84]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2521-S.SL.pdf?cite=1994%20c%20232%20§%202[1994 c 232 § 2]; ]

== 78.56.030 - Operations subject to this chapter and other requirements.
Metals mining and milling operations are subject to the requirements of this chapter in addition to the requirements established in other statutes and rules.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2521-S.SL.pdf?cite=1994%20c%20232%20§%203[1994 c 232 § 3]; ]

== 78.56.040 - Disclosures required with state environmental policy act checklist—Public inspection of information.
The department of ecology shall require each applicant submitting a checklist pursuant to chapter 43.21C RCW for a metals mining and milling operation to disclose the ownership and each controlling interest in the proposed operation. The applicant shall also disclose all other mining operations within the United States which the applicant operates or in which the applicant has an ownership or controlling interest. In addition, the applicant shall disclose and may enumerate and describe the circumstances of: (1) Any past or present bankruptcies involving the ownerships and their subsidiaries, (2) any abandonment of sites regulated by the model toxics control act, chapter 70A.305 RCW, or other similar state remedial cleanup programs, or the federal comprehensive environmental response, compensation, and liability act, 42 U.S.C. Sec. 9601 et seq., as amended, (3) any penalties in excess of ten thousand dollars assessed for violations of the provisions of 33 U.S.C. Sec. 1251 et seq. or 42 U.S.C. Sec. 7401 et seq., and (4) any previous forfeitures of financial assurance due to noncompliance with reclamation or remediation requirements. This information shall be available for public inspection and copying at the department of ecology. Ownership or control of less than ten percent of the stock of a corporation shall not by itself constitute ownership or a controlling interest under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1192.SL.pdf?cite=2021%20c%2065%20§%2085[2021 c 65 § 85]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2521-S.SL.pdf?cite=1994%20c%20232%20§%204[1994 c 232 § 4]; ]

== 78.56.050 - Environmental impact statement required—Mitigation measures to be part of permit requirements—Department of ecology to cooperate with affected local governments.
. An environmental impact statement must be prepared for any proposed metals mining and milling operation. The department of ecology shall be the lead agency in coordinating the environmental review process under chapter 43.21C RCW and in preparing the environmental impact statement, except for uranium and thorium operations regulated under Title 70 RCW.

. As part of the environmental review of metals mining and milling operations regulated under this chapter, the applicant shall provide baseline data adequate to document the premining conditions at the proposed site of the metals mining and milling operation. The baseline data shall contain information on the elements of the natural environment identified in rules adopted pursuant to chapter 43.21C RCW.

. The department of ecology, after consultation with the department of fish and wildlife, shall incorporate measures to mitigate significant probable adverse impacts to fish and wildlife as part of the department of ecology's permit requirements for the proposed operation.

. In conducting the environmental review and preparing the environmental impact statement, the department of ecology shall cooperate with all affected local governments to the fullest extent practicable.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2521-S.SL.pdf?cite=1994%20c%20232%20§%205[1994 c 232 § 5]; ]

== 78.56.060 - Metals mining coordinator to be appointed—Duties.
The department of ecology will appoint a metals mining coordinator. The coordinator will maintain current information on the status of any metals mining and milling operation regulated under this chapter from the preparation of the environmental impact statement through the permitting, construction, operation, and reclamation phases of the project or until the proposal is no longer active. The coordinator shall also maintain current information on postclosure activities. The coordinator will act as a contact person for the applicant, the operator, and interested members of the public. The coordinator may also assist agencies with coordination of their inspection and monitoring responsibilities.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2521-S.SL.pdf?cite=1994%20c%20232%20§%206[1994 c 232 § 6]; ]

== 78.56.070 - Quarterly inspections by responsible state agencies required—Cross-training and coordination of inspections encouraged.
. State agencies with the responsibility for inspecting metals mining and milling operations regulated under this chapter shall conduct such inspections at least quarterly: PROVIDED, That the inspections are not prevented by inclement weather conditions.

. The legislature encourages state agencies with inspection responsibilities for metals mining and milling operations regulated under this chapter to explore opportunities for cross-training of inspectors among state agencies and programs. This cross-training would be for the purpose of meeting the inspection responsibilities of these agencies in a more efficient and cost-effective manner. If doing so would be more efficient and cost-effective, state agency inspectors are also encouraged to coordinate inspections with federal and local government inspectors as well as with one another.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2521-S.SL.pdf?cite=1994%20c%20232%20§%207[1994 c 232 § 7]; ]

== 78.56.080 - Estimate of costs by department of ecology and department of natural resources—Fee on operations to be established by department of ecology.
. [Empty]
.. As part of its normal budget development process and in consultation with the metals mining industry, the department of ecology shall estimate the costs required for the department to meet its obligations for the additional inspections of metals mining and milling operations required by chapter 232, Laws of 1994. The department shall also estimate the cost of employing the metals mining coordinator established in RCW 78.56.060.

.. As part of its normal budget development process and in consultation with the metals mining industry, the department of natural resources shall estimate the costs required for the department to meet its obligations for the additional inspections of metals mining and milling operations required by chapter 232, Laws of 1994.

. Based on the cost estimates generated by the department of ecology and the department of natural resources, the department of ecology shall establish the amount of a fee to be paid by each active metals mining and milling operation regulated under this chapter. The fee shall be established at a level to fully recover the direct and indirect costs of the agency responsibilities identified in subsection (1) of this section. The amount of the fee for each operation shall be proportional to the number of visits required per site. Each applicant for a metals mining and milling operation shall also be assessed the fee based on the same criterion. The department of ecology may adjust the fees established in this subsection if unanticipated activity in the industry increases or decreases the amount of funding necessary to meet agencies' inspection responsibilities.

. The department of ecology shall collect the fees established in subsection (2) of this section. All moneys from these fees shall be deposited into the general fund.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6581-S.SL.pdf?cite=2012%20c%20198%20§%2015[2012 c 198 § 15]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5669.SL.pdf?cite=1997%20c%20170%20§%201[1997 c 170 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2521-S.SL.pdf?cite=1994%20c%20232%20§%208[1994 c 232 § 8]; ]

== 78.56.090 - Initial waste discharge permits for tailings facilities—Siting criteria—Primary screening process—Technical site investigation—Site selection report.
. In the processing of an application for an initial waste discharge permit for a tailings facility pursuant to the requirements of chapter 90.48 RCW, the department of ecology shall consider site-specific criteria in determining a preferred location of tailings facilities of metals mining and milling operations and incorporate the requirements of all known available and reasonable methods in order to maintain the highest possible standards to insure the purity of all waters of the state in accordance with the public policy identified by RCW 90.48.010.

In implementing the siting criteria, the department shall take into account the objectives of the proponent's application relating to mining and milling operations. These objectives shall consist of, but not be limited to (a) operational feasibility, (b) compatibility with optimum tailings placement methods, (c) adequate volume capacity, (d) availability of construction materials, and (e) an optimized embankment volume.

. To meet the mandate of subsection (1) of this section, siting of tailings facilities shall be accomplished through a two-stage process that consists of a primary alternatives screening phase, and a secondary technical site investigation phase.

. The primary screening phase will consist of, but not be limited to, siting criteria based on considerations as to location as follows:

.. Proximity to the one hundred year floodplain, as indicated in the most recent federal emergency management agency maps;

.. Proximity to surface and ground water;

.. Topographic setting;

.. Identifiable adverse geologic conditions, such as landslides and active faults; and

.. Visibility impacts of the public generally and residents more particularly.

. The department of ecology, through the primary screening process, shall reduce the available tailings facility sites to one or more feasible locations whereupon a technical site investigation phase shall be conducted by the department for the purpose of verifying the adequacy of the remaining potential sites. The technical site investigations phase shall consist of, but not be limited to, the following:

.. Soil characteristics;

.. Hydrologic characteristics;

.. A local and structural geology evaluation, including seismic conditions and related geotechnical investigations;

.. A surface water control analysis; and

.. A slope stability analysis.

. Upon completion of the two phase evaluation process set forth in this section, the department of ecology shall issue a site selection report on the preferred location. This report shall address the above criteria as well as analyze the feasibility of reclamation and stabilization of the tailings facility. The siting report may recommend mitigation or engineering factors to address siting concerns. The report shall be developed in conjunction with the preparation of and contained in an environmental impact statement prepared pursuant to chapter 43.21C RCW. The report may be utilized by the department of ecology for the purpose of providing information related to the suitability of the site and for ruling on an application for a waste discharge permit.

. The department of ecology may, at its discretion, require the applicant to provide the information required in either phase one or phase two as described in subsections (3) and (4) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2521-S.SL.pdf?cite=1994%20c%20232%20§%209[1994 c 232 § 9]; ]

== 78.56.100 - Waste discharge permits for metals mining and milling operations tailing facilities—Pollution control standards—Waste rock management plan—Citizen observation and verification of water samples—Voluntary reduction plan—Application of this section.
. In order to receive a waste discharge permit from the department of ecology pursuant to the requirements of chapter 90.48 RCW or in order to operate a metals mining and milling tailing facility, an applicant proposing a metals mining and milling operation regulated under this chapter must meet the following additional requirements:

.. Any tailings facility shall be designed and operated to prevent the release of pollution and must meet the following standards:

... Operators shall apply all known available and reasonable technology to limit the concentration of potentially toxic materials in the tailings facility to assure the protection of wildlife and human health;

... The tailings facility shall have a containment system that includes an engineered liner system, leak detection and leak collection elements, and a seepage collection impoundment to assure that a leak of any regulated substance under chapter 90.48 RCW will be detected before escaping from the containment system. The design and management of the facility must ensure that any leaks from the tailings facility are detected in a manner which allows for remediation pursuant to chapter 90.48 RCW. The applicant shall prepare a detailed engineering report setting forth the facility design and construction. The applicant shall submit the report to the department of ecology for its review and approval of a design as determined by the department. Natural conditions, such as depth to groundwater or net rainfall, shall be taken into account in the facility design, but not in lieu of the protection required by the engineered liner system;

... The toxicity of mine or mill tailings and the potential for long-term release of regulated substances from mine or mill tailings shall be reduced to the greatest extent practicable through stabilization, removal, or reuse of the substances; and

... The closure of the tailings facility shall provide for isolation or containment of potentially toxic materials and shall be designed to prevent future release of regulated substances contained in the impoundment;

.. The applicant must develop a waste rock management plan approved by the department of ecology and the department of natural resources which emphasizes pollution prevention. At a minimum, the plan must contain the following elements:

... An accurate identification of the acid generating properties of the waste rock;

... A strategy for encapsulating potentially toxic material from the environment, when appropriate, in order to prevent the release of heavy metals and acidic drainage; and

... A plan for reclaiming and closing waste rock sites which minimizes infiltration of precipitation and runoff into the waste rock and which is designed to prevent future releases of regulated substances contained within the waste rock;

.. If an interested citizen or citizen group so requests of the department of ecology, the metals mining and milling operator or applicant shall work with the department of ecology and the interested party to make arrangements for citizen observation and verification in the taking of required water samples. While it is the intent of this subsection to provide for citizen observation and verification of water sampling activities, it is not the intent of this subsection to require additional water sampling and analysis on the part of the mining and milling operation or the department. The citizen observation and verification program shall be incorporated into the applicant's, operator's, or department's normal sampling regimen and shall occur at least once every six months. There is no duty of care on the part of the state or its employees to any person who participates in the citizen observation and verification of water sampling under chapter 232, Laws of 1994 and the state and its employees shall be immune from any civil lawsuit based on any injuries to or claims made by any person as a result of that person's participation in such observation and verification of water sampling activities. The metals mining and milling operator or applicant shall not be liable for any injuries to or claims made by any person which result from that person coming onto the property of the metals mining and milling operator or applicant as an observer pursuant to chapter 232, Laws of 1994. The results from these and all other relevant water sampling activities shall be kept on file with the relevant county and shall be available for public inspection during normal working hours; and

.. An operator or applicant for a metals mining and milling operation must complete a voluntary reduction plan in accordance with RCW 70A.214.110.

. Only those tailings facilities constructed after April 1, 1994, must meet the requirement established in subsection (1)(a) of this section. Only those waste rock holdings constructed after April 1, 1994, must meet the requirement established in subsection (1)(b) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1192.SL.pdf?cite=2021%20c%2065%20§%2086[2021 c 65 § 86]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2521-S.SL.pdf?cite=1994%20c%20232%20§%2010[1994 c 232 § 10]; ]

== 78.56.110 - Performance security required—Conditions—Department of ecology authority to adopt requirements—Liability under performance security.
. The department of ecology shall not issue necessary permits to an applicant for a metals mining and milling operation until the applicant has deposited with the department of ecology a performance security which is acceptable to the department of ecology based on the requirements of subsection (2) of this section. This performance security may be:

.. Bank letters of credit;

.. A cash deposit;

.. Negotiable securities;

.. An assignment of a savings account;

.. A savings certificate in a Washington bank; or

.. A corporate surety bond executed in favor of the department of ecology by a corporation authorized to do business in the state of Washington under Title 48 RCW.

The department of ecology may, for any reason, refuse any performance security not deemed adequate.

. The performance security shall be conditioned on the faithful performance of the applicant or operator in meeting the following obligations:

.. Compliance with the environmental protection laws of the state of Washington administered by the department of ecology, or permit conditions administered by the department of ecology, associated with the construction, operation, and closure pertaining to metals mining and milling operations, and with the related environmental protection ordinances and permit conditions established by local government when requested by local government;

.. Reclamation of metals mining and milling operations that do not meet the threshold of surface mining as defined by RCW 78.44.031(17);

.. Postclosure environmental monitoring as determined by the department of ecology; and

.. Provision of sufficient funding as determined by the department of ecology for cleanup of potential problems revealed during or after closure.

. The department of ecology may, if it deems appropriate, adopt rules for determining the amount of the performance security, requirements for the performance security, requirements for the issuer of the performance security, and any other requirements necessary for the implementation of this section.

. The department of ecology may increase or decrease the amount of the performance security at any time to compensate for any alteration in the operation that affects meeting the obligations in subsection (2) of this section. At a minimum, the department shall review the adequacy of the performance security every two years.

. Liability under the performance security shall be maintained until the obligations in subsection (2) of this section are met to the satisfaction of the department of ecology. Liability under the performance security may be released only upon written notification by the department of ecology.

. Any interest or appreciation on the performance security shall be held by the department of ecology until the obligations in subsection (2) of this section have been met to the satisfaction of the department of ecology. At such time, the interest shall be remitted to the applicant or operator. However, if the applicant or operator fails to comply with the obligations of subsection (2) of this section, the interest or appreciation may be used by the department of ecology to comply with the obligations.

. Only one agency may require a performance security to satisfy the deposit requirements of RCW 78.44.087, and only one agency may require a performance security to satisfy the deposit requirements of this section. However, a single performance security, when acceptable to both the department of ecology and the department of natural resources, may be utilized by both agencies to satisfy the requirements of this section and RCW 78.44.087.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5662-S.SL.pdf?cite=1995%20c%20223%20§%201[1995 c 223 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2521-S.SL.pdf?cite=1994%20c%20232%20§%2011[1994 c 232 § 11]; ]

== 78.56.120 - Remediation or mitigation by department of ecology—Order to submit performance security.
The department of ecology may, with staff, equipment, and material under its control, or by contract with others, remediate or mitigate any impact of a metals mining and milling operation when it finds that the operator or permit holder has failed to comply with relevant statutes, rules, or permits, and the operator or permit holder has failed to take adequate or timely action to rectify these impacts.

If the department intends to remediate or mitigate such impacts, the department shall issue an order to submit performance security requiring the permit holder or surety to submit to the department the amount of moneys posted pursuant to RCW 78.56.110. If the amount specified in the order to submit performance security is not paid within twenty days after issuance of the notice, the attorney general upon request of the department shall bring an action on behalf of the state in a superior court to recover the amount specified and associated legal fees.

The department may proceed at any time after issuing the order to submit performance security to remediate or mitigate adverse impacts.

The department shall keep a record of all expenses incurred in carrying out any remediation or mitigation activities authorized under this section, including:

. Remediation or mitigation;

. A reasonable charge for the services performed by the state's personnel and the state's equipment and materials utilized; and

. Administrative and legal expenses related to remediation or mitigation.

The department shall refund to the surety or permit holder all amounts received in excess of the amount of expenses incurred. If the amount received is less than the expenses incurred, the attorney general, upon request of the department of ecology, may bring an action against the permit holder on behalf of the state in the superior court to recover the remaining costs listed in this section.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5662-S.SL.pdf?cite=1995%20c%20223%20§%202[1995 c 223 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2521-S.SL.pdf?cite=1994%20c%20232%20§%2012[1994 c 232 § 12]; ]

== 78.56.130 - Legislative finding—Impact analysis required for large-scale operations—Impact fees by county legislative authority—Application of this section—Application of chapter  82.02 RCW.
. The legislature finds that the construction and operation of large-scale metals mining and milling facilities may create new job opportunities and enhance local tax revenues. However, the legislature also finds that such operations may also result in new demands on public facilities owned and operated by local government entities, such as public streets and roads; publicly owned parks, open space, and recreation facilities; school facilities; and fire protection facilities in jurisdictions that are not part of a fire district. It is important for these economic impacts to be identified as part of any proposal for a large-scale metals mining and milling operation. It is then appropriate for the county legislative authority to balance expected revenues, including revenues derived from taxes paid by the owner of such an operation, and costs associated with the operation to determine to what degree any new costs require mitigation by the metals mining applicant.

. An applicant for a large-scale metals mining and milling operation regulated under this chapter must submit to the relevant county legislative authority an impact analysis describing the economic impact of the proposed mining operation on local governmental units. For the purposes of this section, a metals mining operation is large-scale if, in the construction or operation of the mine and the associated milling facility, the applicant and contractors at the site employ more than thirty-five persons during any consecutive six-month period. The relevant county is the county in which the mine and mill are to be sited, unless the economic impacts to local governmental units are projected to substantially affect more than one county. In that case, the impact plan must be submitted to the legislative authority of all affected counties. Local governmental units include counties, cities, towns, school districts, and special purpose districts.

. The economic impact analysis shall include at least the following information:

.. A timetable for development of the mining operation, including the opening date of the operation and the estimated closing date;

.. The estimated number of persons coming into the impacted area as a result of the development of the mining operation;

.. An estimate of the increased capital and operating costs to local governmental units for providing services necessary as a result of the development of the mining operation; and

.. An estimate of the increased tax or other revenues accruing to local governmental units as a result of development of the mining and milling operation.

. The county legislative authority of a county planning under chapter 36.70A RCW may assess impact fees under chapter 82.02 RCW to address economic impacts associated with development of the mining operation. The county legislative authority shall hold at least one public hearing on the economic impact analysis and any proposed mitigation measures.

. The county legislative authority of a county which is not planning under chapter 36.70A RCW may negotiate with the applicant on a strategy to address economic impacts associated with development of the mining operation. The county legislative authority shall hold at least one public hearing on the economic impact analysis and any proposed mitigation measures.

. The county legislative authority must approve or disapprove the impact analysis and any associated proposals from the applicant to address economic impacts to local governmental units resulting from development of the mining operation. If the applicant does not submit an adequate impact analysis to the relevant county legislative authority or if the county legislative authority does not find the applicant's proposals to be acceptable because of their failure to adequately mitigate adverse economic impacts, the county legislative authority shall refuse to issue any permits under its jurisdiction necessary for the construction or operation of the mine and associated mill.

. The requirements established in this section apply to metals mining operations under construction or constructed after April 1, 1994.

. The provisions of chapter 82.02 RCW shall apply to new mining and milling operations.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2521-S.SL.pdf?cite=1994%20c%20232%20§%2013[1994 c 232 § 13]; ]

== 78.56.140 - Citizen action suits.
. Except as provided in subsections (2) and (5) of this section, any aggrieved person may commence a civil action on his or her own behalf:

.. Against any person, including any state agency or local government agency, who is alleged to be in violation of a law, rule, order, or permit pertaining to metals mining and milling operations regulated under chapter 232, Laws of 1994;

.. Against a state agency if there is alleged a failure of the agency to perform any nondiscretionary act or duty under state laws pertaining to metals mining and milling operations; or

.. Against any person who constructs a metals mining and milling operation without the permits and authorizations required by state law.

The superior courts shall have jurisdiction to enforce metals mining laws, rules, orders, and permit conditions, or to order the state to perform such act or duty, as the case may be. In addition to injunctive relief, a superior court may award a civil penalty when deemed appropriate in an amount not to exceed ten thousand dollars per violation per day, payable to the state of Washington.

. No action may be commenced:

.. Under subsection (1)(a) of this section:

... Prior to sixty days after the plaintiff has given notice of the alleged violation to the state, and to any alleged violator of a metals mining and milling law, rule, order, or permit condition; or

... If the state has commenced and is diligently prosecuting a civil action in a court of the state or of the United States or is diligently pursuing authorized administrative enforcement action to require compliance with the law, rule, order, or permit. To preclude a civil action, the enforcement action must contain specific, aggressive, and enforceable timelines for compliance and must provide for public notice of and reasonable opportunity for public comment on the enforcement action. In any such court action, any aggrieved person may intervene as a matter of right; or

.. Under subsection (1)(b) of this section prior to sixty days after the plaintiff has given notice of such action to the state.

. [Empty]
.. Any action respecting a violation of a law, rule, order, or permit condition pertaining to metals mining and milling operations may be brought in the judicial district in which such operation is located or proposed.

.. In such action under this section, the state, if not a party, may intervene as a matter of right.

. The court, in issuing any final order in any action brought pursuant to subsection (1) of this section, may award costs of litigation, including reasonable attorney and expert witness fees, to any prevailing party, wherever the court determines such award is appropriate. The court may, if a temporary restraining order or preliminary injunction is sought, require the filing of a bond or equivalent security in accordance with the rules of civil procedure.

. A civil action to enforce compliance with a law, rule, order, or permit may not be brought under this section if any other statute, or the common law, provides authority for the plaintiff to bring a civil action and, in such action, obtain the same relief, as authorized under this section, for enforcement of such law, rule, order, or permit. Nothing in this section restricts any right which any person, or class of persons, may have under any statute or common law to seek any relief, including relief against the state or a state agency.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2521-S.SL.pdf?cite=1994%20c%20232%20§%2014[1994 c 232 § 14]; ]

== 78.56.150 - Application of requirements to milling facilities not adjacent to mining operation.
A milling facility which is not adjacent to or in the vicinity of the metals mining operation producing the ore to be milled and which processes precious or base metal ore by treatment or concentration is subject to the provisions of RCW 78.56.010 through 78.56.090, 78.56.100(1) (a), (c), and (d), 78.56.110 through 78.56.140, 70A.15.4520, and 70A.300.470 and chapters 70A.15, 70A.300, 90.03, and 90.48 RCW and all other applicable laws. The smelting of aluminum does not constitute a metals milling operation under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1192.SL.pdf?cite=2021%20c%2065%20§%2087[2021 c 65 § 87]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2521-S.SL.pdf?cite=1994%20c%20232%20§%2015[1994 c 232 § 15]; ]

== 78.56.160 - Moratorium on use of heap leach extraction process—Joint review by department of ecology and department of natural resources—Permanent prohibition of in situ extraction.
. Until June 30, 1996, there shall be a moratorium on metals mining and milling operations using the heap leach extraction process. The department of natural resources and the department of ecology shall jointly review the existing laws and regulations pertaining to the heap leach extraction process for their adequacy in safeguarding the environment.

. Metals mining using the process of in situ extraction is permanently prohibited in the state of Washington.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6219.SL.pdf?cite=1998%20c%20245%20§%20161[1998 c 245 § 161]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2521-S.SL.pdf?cite=1994%20c%20232%20§%2016[1994 c 232 § 16]; ]

== 78.56.901 - Effective date—1994 c 232 §§ 1-5, 9-17, and 23-29.
This act is necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and, with the exception of sections 6 through 8 and 18 through 22 of this act, shall take effect immediately [April 1, 1994].

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2521-S.SL.pdf?cite=1994%20c%20232%20§%2030[1994 c 232 § 30]; ]

== 78.56.902 - Effective date—1994 c 232 §§ 6-8 and 18-22.
Sections 6 through 8 and 18 through 22 of this act shall take effect July 1, 1995.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2521-S.SL.pdf?cite=1994%20c%20232%20§%2031[1994 c 232 § 31]; ]

