= 18.35 - Hearing and speech services.
:toc:

== 18.35.005 - Regulation of health care professions—Criteria.
See chapter 18.120 RCW.

[ ]

== 18.35.008 - Intent.
It is the intent of this chapter to protect the public health, safety, and welfare; to protect the public from being misled by incompetent, unethical, and unauthorized persons; and to assure the availability of hearing and speech services of high quality to persons in need of such services.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2309-S.SL.pdf?cite=1996%20c%20200%20§%201[1996 c 200 § 1]; ]

== 18.35.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Assistive listening device or system" means an amplification system that is specifically designed to improve the signal to noise ratio for the listener, reduce interference from noise in the background, and enhance hearing levels at a distance by picking up sound from as close to source as possible and sending it directly to the ear of the listener, excluding hearing instruments as defined in this chapter.

. "Audiology" means the application of principles, methods, and procedures related to hearing and the disorders of hearing and to related language and speech disorders, whether of organic or nonorganic origin, peripheral or central, that impede the normal process of human communication including, but not limited to, disorders of auditory sensitivity, acuity, function, processing, or vestibular function, the application of aural habilitation, rehabilitation, and appropriate devices including fitting and dispensing of hearing instruments, and cerumen management to treat such disorders.

. "Board" means the board of hearing and speech.

. "Department" means the department of health.

. "Direct supervision" means the supervising speech-language pathologist, hearing aid specialist, or audiologist is on-site and in view during the procedures or tasks. The board shall develop rules outlining the procedures or tasks allowable under direct supervision.

. "Establishment" means any permanent site housing a person engaging in the practice of fitting and dispensing of hearing instruments by a hearing aid specialist or audiologist; where the client can have personal contact and counsel during the firm's business hours; where business is conducted; and the address of which is given to the state for the purpose of bonding.

. "Facility" means any permanent site housing a person engaging in the practice of speech-language pathology and/or audiology, excluding the sale, lease, or rental of hearing instruments.

. "Fitting and dispensing of hearing instruments" means the sale, lease, or rental or attempted sale, lease, or rental of hearing instruments together with the selection and modification of hearing instruments and the administration of nondiagnostic tests as specified by RCW 18.35.110 and the use of procedures essential to the performance of these functions; and includes recommending specific hearing instrument systems, specific hearing instruments, or specific hearing instrument characteristics, the taking of impressions for ear molds for these purposes, the use of nondiagnostic procedures and equipment to verify the appropriateness of the hearing instrument fitting, and hearing instrument orientation. The fitting and dispensing of hearing instruments as defined by this chapter may be equally provided by a licensed hearing aid specialist or licensed audiologist.

. "Good standing" means a licensed hearing aid specialist, licensed audiologist, licensed speech-language pathologist, or certified speech-language pathology assistant whose license or certification has not been subject to sanctions pursuant to chapter 18.130 RCW or sanctions by other states, territories, or the District of Columbia in the last two years.

. "Hearing aid specialist" means a person who is licensed to engage in the practice of fitting and dispensing of hearing instruments and meets the qualifications of this chapter.

. "Hearing health care professional" means an audiologist or hearing aid specialist licensed under this chapter or a physician specializing in diseases of the ear licensed under chapter 18.71 RCW.

. "Hearing instrument" means any wearable prosthetic instrument or device designed for or represented as aiding, improving, compensating for, or correcting defective human hearing and any parts, attachments, or accessories of such an instrument or device, excluding batteries and cords, ear molds, and assistive listening devices.

. "Indirect supervision" means the procedures or tasks are performed under the speech-language pathologist, the hearing aid specialist, or the audiologist's overall direction and control, but the speech-language pathologist, hearing aid specialist, or audiologist's presence is not required during the performance of the procedures or tasks. The board shall develop rules outlining the procedures or tasks allowable under indirect supervision.

. "Interim permit holder" means a person who holds the permit created under RCW 18.35.060 and who practices under the supervision of a licensed hearing aid specialist, licensed speech-language pathologist, or licensed audiologist.

. "Licensed audiologist" means a person who is licensed by the department to engage in the practice of audiology and meets the qualifications in this chapter.

. "Licensed speech-language pathologist" means a person who is licensed by the department to engage in the practice of speech-language pathology and meets the qualifications of this chapter.

. "Secretary" means the secretary of health.

. "Speech-language pathology" means the application of principles, methods, and procedures related to the development and disorders, whether of organic or nonorganic origin, that impede oral, pharyngeal, or laryngeal sensorimotor competencies and the normal process of human communication including, but not limited to, disorders and related disorders of speech, articulation, fluency, voice, verbal and written language, auditory comprehension, cognition/communication, and the application of augmentative communication treatment and devices for treatment of such disorders.

. "Speech-language pathology assistant" means a person who is certified by the department to provide speech-language pathology services under the direction and supervision of a licensed speech-language pathologist or speech-language pathologist certified as an educational staff associate by the superintendent of public instruction, and meets all of the requirements of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2108.SL.pdf?cite=2014%20c%20189%20§%202[2014 c 189 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5601-S.SL.pdf?cite=2009%20c%20301%20§%202[2009 c 301 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5358.SL.pdf?cite=2005%20c%2045%20§%201[2005 c 45 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2589-S.SL.pdf?cite=2002%20c%20310%20§%201[2002 c 310 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1998%20c%20142%20§%201[1998 c 142 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2309-S.SL.pdf?cite=1996%20c%20200%20§%202[1996 c 200 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1500-S.SL.pdf?cite=1993%20c%20313%20§%201[1993 c 313 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2080[1991 c 3 § 80]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c39.pdf?cite=1983%20c%2039%20§%201[1983 c 39 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c158.pdf?cite=1979%20c%20158%20§%2038[1979 c 158 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c106.pdf?cite=1973%201st%20ex.s.%20c%20106%20§%201[1973 1st ex.s. c 106 § 1]; ]

== 18.35.020 - Hearing instruments—Dispensing—License, certificate, permit required.
. No person shall engage in the fitting and dispensing of hearing instruments or imply or represent that he or she is engaged in the fitting and dispensing of hearing instruments unless he or she is a licensed hearing aid specialist, or a licensed audiologist or holds an interim permit issued by the department as provided in this chapter and is an owner or employee of an establishment that is bonded as provided by RCW 18.35.240. The owner or manager of an establishment that dispenses hearing instruments is responsible under this chapter for all transactions made in the establishment name or conducted on its premises by agents or persons employed by the establishment engaged in fitting and dispensing of hearing instruments. Every establishment that fits and dispenses shall have in its employ at least one licensed hearing aid specialist or licensed audiologist at all times, and shall annually submit proof that all testing equipment at that establishment that is required by the board to be calibrated has been properly calibrated.

. Effective January 1, 2003, no person shall engage in the practice of audiology or imply or represent that he or she is engaged in the practice of audiology unless he or she is a licensed audiologist or holds an audiology interim permit issued by the department as provided in this chapter. Audiologists who are certified as educational staff associates by the Washington professional educator standards board are excluded unless they elect to become licensed under this chapter. However, a person certified by the state board of education as an educational staff associate who practices outside the school setting must be a licensed audiologist.

. Effective January 1, 2003, no person shall engage in the practice of speech-language pathology or imply or represent that he or she is engaged in the practice of speech-language pathology unless he or she is a licensed speech-language pathologist or holds a speech-language pathology interim permit issued by the department as provided in this chapter. Speech-language pathologists who are certified as educational staff associates by the state board of education are excluded unless they elect to become licensed under this chapter. However, a person certified by the state board of education as an educational staff associate who practices outside the school setting must be a licensed speech-language pathologist.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2108.SL.pdf?cite=2014%20c%20189%20§%203[2014 c 189 § 3]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/3098-S2.SL.pdf?cite=2006%20c%20263%20§%20801[2006 c 263 § 801]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5358.SL.pdf?cite=2005%20c%2045%20§%202[2005 c 45 § 2]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2589-S.SL.pdf?cite=2002%20c%20310%20§%202[2002 c 310 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1998%20c%20142%20§%202[1998 c 142 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2309-S.SL.pdf?cite=1996%20c%20200%20§%203[1996 c 200 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c198.pdf?cite=1989%20c%20198%20§%201[1989 c 198 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c39.pdf?cite=1983%20c%2039%20§%202[1983 c 39 § 2]; 1973 1st ex.s c 106 § 2; ]

== 18.35.030 - Receipt required—Contents.
Any person who engages in fitting and dispensing of hearing instruments shall provide to each person who enters into an agreement to purchase a hearing instrument a receipt at the time of the agreement containing the following information:

. The seller's name, signature, license, or permit number, address, and phone number of his or her regular place of business;

. A description of the instrument furnished, including make, model, circuit options, and the term "used" or "reconditioned" if applicable;

. A disclosure of the cost of all services including but not limited to the cost of testing and fitting, the actual cost of the hearing instrument furnished, the cost of ear molds if any, and the terms of the sale. These costs, including the cost of ear molds, shall be known as the total purchase price. The receipt shall also contain a statement of the purchaser's recision rights under this chapter and an acknowledgment that the purchaser has read and understands these rights. Upon request, the purchaser shall also be supplied with a signed and dated copy of any hearing evaluation performed by the seller.

. At the time of delivery of the hearing instrument, the purchaser shall also be furnished with the serial number of the hearing instrument supplied.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2589-S.SL.pdf?cite=2002%20c%20310%20§%203[2002 c 310 § 3]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2309-S.SL.pdf?cite=1996%20c%20200%20§%204[1996 c 200 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c39.pdf?cite=1983%20c%2039%20§%203[1983 c 39 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c106.pdf?cite=1973%201st%20ex.s.%20c%20106%20§%203[1973 1st ex.s. c 106 § 3]; ]

== 18.35.040 - Applicants—Generally.
. An applicant for licensure as a hearing aid specialist must have the following minimum qualifications and shall pay a fee determined by the secretary as provided in RCW 43.70.250. An applicant shall be issued a license under the provisions of this chapter if the applicant has not committed unprofessional conduct as specified by chapter 18.130 RCW, and:

.. [Empty]
... Satisfactorily completes the hearing aid specialist examination required by this chapter; and

... Satisfactorily completes:

(A) A minimum of a two-year degree program in hearing aid specialist instruction. The program must be approved by the board;

(B) A two-year or four-year degree in a field of study approved by the board from an accredited institution, a nine-month board-approved certificate program offered by a board-approved hearing aid specialist program, and the practical examination approved by the board. The practical examination must be given at least quarterly, as determined by the board. The department may hire licensed industry experts approved by the board to proctor the examination; or

.. Holds a current, unsuspended, unrevoked license from another jurisdiction if the standards for licensing in such other jurisdiction are substantially equivalent to those prevailing in this state as provided in (a) of this subsection; or

.. [Empty]
... Holds a current, unsuspended, unrevoked license from another jurisdiction, has been actively practicing as a licensed hearing aid specialist in another jurisdiction for at least forty-eight of the last sixty months, and submits proof of completion of advance certification from either the international hearing society or the national board for certification in hearing instrument sciences; and

... Satisfactorily completes the hearing aid specialist examination required by this chapter or a substantially equivalent examination approved by the board.

The applicant must present proof of qualifications to the board in the manner and on forms prescribed by the secretary.

. [Empty]
.. An applicant for licensure as a speech-language pathologist or audiologist must have the following minimum qualifications:

... Has not committed unprofessional conduct as specified by the uniform disciplinary act;

... Has a master's degree or the equivalent, or a doctorate degree or the equivalent, from a program at a board-approved institution of higher learning, which includes completion of a supervised clinical practicum experience as defined by rules adopted by the board; and

... Has completed postgraduate professional work experience approved by the board.

.. All qualified applicants must satisfactorily complete the speech-language pathology or audiology examinations required by this chapter.

.. The applicant must present proof of qualifications to the board in the manner and on forms prescribed by the secretary.

. An applicant for certification as a speech-language pathology assistant shall pay a fee determined by the secretary as provided in RCW 43.70.250 and must have the following minimum qualifications:

.. An associate of arts or sciences degree, or a certificate of proficiency, from a speech-language pathology assistant program from an institution of higher education that is approved by the board, as is evidenced by the following:

... Transcripts showing forty-five quarter hours or thirty semester hours of speech-language pathology coursework; and

... Transcripts showing forty-five quarter hours or thirty semester hours of general education credit; or

.. A bachelor of arts or bachelor of sciences degree, as evidenced by transcripts, from a speech, language, and hearing program from an institution of higher education that is approved by the board.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1551-S.SL.pdf?cite=2020%20c%2076%20§%2017[2020 c 76 § 17]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2108.SL.pdf?cite=2014%20c%20189%20§%204[2014 c 189 § 4]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5601-S.SL.pdf?cite=2009%20c%20301%20§%203[2009 c 301 § 3]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1379.SL.pdf?cite=2007%20c%20271%20§%201[2007 c 271 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2589-S.SL.pdf?cite=2002%20c%20310%20§%204[2002 c 310 § 4]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1998%20c%20142%20§%203[1998 c 142 § 3]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2309-S.SL.pdf?cite=1996%20c%20200%20§%205[1996 c 200 § 5]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2081[1991 c 3 § 81]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c198.pdf?cite=1989%20c%20198%20§%202[1989 c 198 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%2030[1985 c 7 § 30]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c39.pdf?cite=1983%20c%2039%20§%204[1983 c 39 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c30.pdf?cite=1975%201st%20ex.s.%20c%2030%20§%2036[1975 1st ex.s. c 30 § 36]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c106.pdf?cite=1973%201st%20ex.s.%20c%20106%20§%204[1973 1st ex.s. c 106 § 4]; ]

== 18.35.050 - Examination—Required—When offered—Review.
Except as otherwise provided in this chapter an applicant for license shall appear at a time and place and before such persons as the department may designate to be examined by written or practical tests, or both. Examinations in hearing aid specialist, speech-language pathology, and audiology shall be held within the state at least once a year. The examinations shall be reviewed annually by the board and the department, and revised as necessary. The examinations shall include appropriate subject matter to ensure the competence of the applicant. Nationally recognized examinations in the fields of fitting and dispensing of hearing instruments, speech-language pathology, and audiology may be used to determine if applicants are qualified for licensure. An applicant who fails an examination may apply for reexamination upon payment of a reexamination fee. The hearing aid specialist reexamination fee for hearing aid specialists and audiologists shall be set by the secretary under RCW 43.70.250.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2108.SL.pdf?cite=2014%20c%20189%20§%205[2014 c 189 § 5]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2589-S.SL.pdf?cite=2002%20c%20310%20§%205[2002 c 310 § 5]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2309-S.SL.pdf?cite=1996%20c%20200%20§%206[1996 c 200 § 6]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1500-S.SL.pdf?cite=1993%20c%20313%20§%202[1993 c 313 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c198.pdf?cite=1989%20c%20198%20§%203[1989 c 198 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c39.pdf?cite=1983%20c%2039%20§%205[1983 c 39 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c106.pdf?cite=1973%201st%20ex.s.%20c%20106%20§%205[1973 1st ex.s. c 106 § 5]; ]

== 18.35.060 - Interim permit—Issuance.
The department, upon approval by the board, shall issue an interim permit authorizing an applicant for speech-language pathologist licensure or audiologist licensure who, except for the postgraduate professional experience and the examination requirements, meets the academic and practicum requirements of RCW 18.35.040(2) to practice under supervision. The interim permit is valid for a period of one year from date of issuance. The board shall determine conditions for the interim permit.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5358.SL.pdf?cite=2005%20c%2045%20§%203[2005 c 45 § 3]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2589-S.SL.pdf?cite=2002%20c%20310%20§%206[2002 c 310 § 6]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1998%20c%20142%20§%204[1998 c 142 § 4]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5445-S.SL.pdf?cite=1997%20c%20275%20§%203[1997 c 275 § 3]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2309-S.SL.pdf?cite=1996%20c%20200%20§%207[1996 c 200 § 7]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2019[1996 c 191 § 19]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1500-S.SL.pdf?cite=1993%20c%20313%20§%203[1993 c 313 § 3]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2082[1991 c 3 § 82]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%2031[1985 c 7 § 31]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c39.pdf?cite=1983%20c%2039%20§%206[1983 c 39 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c30.pdf?cite=1975%201st%20ex.s.%20c%2030%20§%2037[1975 1st ex.s. c 30 § 37]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c106.pdf?cite=1973%201st%20ex.s.%20c%20106%20§%206[1973 1st ex.s. c 106 § 6]; ]

== 18.35.070 - Examination—Contents—Tests.
The hearing aid specialist written or practical examination, or both, provided in RCW 18.35.050 shall consist of:

. Tests of knowledge in the following areas as they pertain to the fitting of hearing instruments:

.. Basic physics of sound;

.. The human hearing mechanism, including the science of hearing and the causes and rehabilitation of abnormal hearing and hearing disorders; and

.. Structure and function of hearing instruments.

. Tests of proficiency in the following areas as they pertain to the fitting of hearing instruments:

.. Pure tone audiometry, including air conduction testing and bone conduction testing;

.. Live voice or recorded voice speech audiometry, including speech reception threshold testing and speech discrimination testing;

.. Effective masking;

.. Recording and evaluation of audiograms and speech audiometry to determine hearing instrument candidacy;

.. Selection and adaptation of hearing instruments and testing of hearing instruments; and

.. Taking ear mold impressions.

. Evidence of knowledge regarding the medical and rehabilitation facilities for children and adults that are available in the area served.

. Evidence of knowledge of grounds for revocation or suspension of license under the provisions of this chapter.

. Any other tests as the board may by rule establish.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2108.SL.pdf?cite=2014%20c%20189%20§%206[2014 c 189 § 6]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2309-S.SL.pdf?cite=1996%20c%20200%20§%208[1996 c 200 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c106.pdf?cite=1973%201st%20ex.s.%20c%20106%20§%207[1973 1st ex.s. c 106 § 7]; ]

== 18.35.080 - License—Generally.
. The department shall license each qualified applicant who satisfactorily completes the required examinations for his or her profession and complies with administrative procedures and administrative requirements established pursuant to RCW 43.70.250 and 43.70.280.

. The board shall waive the requirements of RCW 18.35.040 and 18.35.050 and grant an audiology license to a person who on January 1, 2003, holds a current audiology certificate issued by the department.

. The board shall waive the requirements of RCW 18.35.040 and 18.35.050 and grant a speech-language pathology license to a person who on January 1, 2003, holds a current speech-language pathology certificate issued by the department.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2589-S.SL.pdf?cite=2002%20c%20310%20§%207[2002 c 310 § 7]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5445-S.SL.pdf?cite=1997%20c%20275%20§%204[1997 c 275 § 4]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2309-S.SL.pdf?cite=1996%20c%20200%20§%209[1996 c 200 § 9]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2020[1996 c 191 § 20]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2083[1991 c 3 § 83]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c198.pdf?cite=1989%20c%20198%20§%204[1989 c 198 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%2032[1985 c 7 § 32]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c30.pdf?cite=1975%201st%20ex.s.%20c%2030%20§%2038[1975 1st ex.s. c 30 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c106.pdf?cite=1973%201st%20ex.s.%20c%20106%20§%208[1973 1st ex.s. c 106 § 8]; ]

== 18.35.085 - Credentialing by endorsement.
An applicant holding a credential in another state, territory, or the District of Columbia may be credentialed to practice in this state without examination if the board determines that the other state's credentialing standards are substantially equivalent to the standards in this state.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2309-S.SL.pdf?cite=1996%20c%20200%20§%2010[1996 c 200 § 10]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1960-S.SL.pdf?cite=1991%20c%20332%20§%2031[1991 c 332 § 31]; ]

== 18.35.090 - Compliance with administrative procedures, requirements—Display of license—Continuing education, competency standards.
Each person who engages in practice under this chapter shall comply with administrative procedures and administrative requirements established under RCW 43.70.250 and 43.70.280 and shall keep the license or interim permit conspicuously posted in the place of business at all times. The secretary may establish mandatory continuing education requirements and/or continued competency standards to be met by licensees or interim permit holders as a condition for license or interim permit renewal.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2589-S.SL.pdf?cite=2002%20c%20310%20§%208[2002 c 310 § 8]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1998%20c%20142%20§%205[1998 c 142 § 5]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5445-S.SL.pdf?cite=1997%20c%20275%20§%205[1997 c 275 § 5]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2309-S.SL.pdf?cite=1996%20c%20200%20§%2011[1996 c 200 § 11]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2021[1996 c 191 § 21]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2084[1991 c 3 § 84]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c198.pdf?cite=1989%20c%20198%20§%205[1989 c 198 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%2033[1985 c 7 § 33]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c39.pdf?cite=1983%20c%2039%20§%207[1983 c 39 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c106.pdf?cite=1973%201st%20ex.s.%20c%20106%20§%209[1973 1st ex.s. c 106 § 9]; ]

== 18.35.095 - Licensure or certification—Inactive status.
. A hearing aid specialist licensed under this chapter and not actively practicing may be placed on inactive status by the department at the written request of the licensee. The board shall define by rule the conditions for inactive status licensure. In addition to the requirements of RCW 43.24.086, the licensing fee for a licensee on inactive status shall be directly related to the costs of administering an inactive license by the department. A hearing aid specialist on inactive status may be voluntarily placed on active status by notifying the department in writing, paying the remainder of the licensing fee for the licensing year, and complying with subsection (2) of this section.

. Hearing aid specialist inactive licensees applying for active licensure shall comply with the following: A licensee who has not fitted or dispensed hearing instruments for more than five years from the expiration of the licensee's full fee license shall retake the practical or the written, or both, hearing aid specialist examinations required under this chapter and other requirements as determined by the board. Persons who have inactive status in this state but who are actively licensed and in good standing in any other state shall not be required to take the hearing aid specialist practical examination, but must submit an affidavit attesting to their knowledge of the current Washington Administrative Code rules and Revised Code of Washington statutes pertaining to the fitting and dispensing of hearing instruments.

. A speech-language pathologist or audiologist licensed under this chapter, or a speech-language pathology assistant certified under this chapter, and not actively practicing either speech-language pathology or audiology may be placed on inactive status by the department at the written request of the license or certification holder. The board shall define by rule the conditions for inactive status licensure or certification. In addition to the requirements of RCW 43.24.086, the fee for a license or certification on inactive status shall be directly related to the cost of administering an inactive license or certification by the department. A person on inactive status may be voluntarily placed on active status by notifying the department in writing, paying the remainder of the fee for the year, and complying with subsection (4) of this section.

. Speech-language pathologist, speech-language pathology assistant, or audiologist inactive license or certification holders applying for active licensure or certification shall comply with requirements set forth by the board, which may include completion of continuing competency requirements and taking an examination.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2108.SL.pdf?cite=2014%20c%20189%20§%207[2014 c 189 § 7]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5601-S.SL.pdf?cite=2009%20c%20301%20§%204[2009 c 301 § 4]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2589-S.SL.pdf?cite=2002%20c%20310%20§%209[2002 c 310 § 9]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2309-S.SL.pdf?cite=1996%20c%20200%20§%2012[1996 c 200 § 12]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1500-S.SL.pdf?cite=1993%20c%20313%20§%2012[1993 c 313 § 12]; ]

== 18.35.100 - Place of business.
. Every hearing aid specialist, audiologist, speech-language pathologist, or interim permit holder, who is regulated under this chapter, shall notify the department in writing of the regular address of the place or places in the state of Washington where the person practices or intends to practice more than twenty consecutive business days and of any change thereof within ten days of such change. Failure to notify the department in writing shall be grounds for suspension or revocation of the license or interim permit.

. The department shall keep a record of the places of business of persons who hold licenses or interim permits.

. Any notice required to be given by the department to a person who holds a license or interim permit may be given by mailing it to the address of the last establishment or facility of which the person has notified the department, except that notice to a licensee or interim permit holder of proceedings to deny, suspend, or revoke the license or interim permit shall be by certified or registered mail or by means authorized for service of process.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2108.SL.pdf?cite=2014%20c%20189%20§%208[2014 c 189 § 8]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2589-S.SL.pdf?cite=2002%20c%20310%20§%2010[2002 c 310 § 10]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1998%20c%20142%20§%206[1998 c 142 § 6]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2309-S.SL.pdf?cite=1996%20c%20200%20§%2013[1996 c 200 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c39.pdf?cite=1983%20c%2039%20§%208[1983 c 39 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c106.pdf?cite=1973%201st%20ex.s.%20c%20106%20§%2010[1973 1st ex.s. c 106 § 10]; ]

== 18.35.105 - Records—Contents.
Each licensee and interim permit holder under this chapter shall keep records of all services rendered for a minimum of three years. These records shall contain the names and addresses of all persons to whom services were provided. Hearing aid specialists, audiologists, and interim permit holders shall also record the date the hearing instrument warranty expires, a description of the services and the dates the services were provided, and copies of any contracts and receipts. All records, as required pursuant to this chapter or by rule, shall be owned by the establishment or facility and shall remain with the establishment or facility in the event the licensee changes employment. If a contract between the establishment or facility and the licensee provides that the records are to remain with the licensee, copies of such records shall be provided to the establishment or facility.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2108.SL.pdf?cite=2014%20c%20189%20§%209[2014 c 189 § 9]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2589-S.SL.pdf?cite=2002%20c%20310%20§%2011[2002 c 310 § 11]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1998%20c%20142%20§%207[1998 c 142 § 7]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2309-S.SL.pdf?cite=1996%20c%20200%20§%2014[1996 c 200 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c198.pdf?cite=1989%20c%20198%20§%206[1989 c 198 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c39.pdf?cite=1983%20c%2039%20§%2016[1983 c 39 § 16]; ]

== 18.35.110 - Disciplinary action—Grounds.
In addition to causes specified under RCW 18.130.170 and 18.130.180, any person licensed or holding an interim permit under this chapter may be subject to disciplinary action by the board for any of the following causes:

. For unethical conduct in dispensing hearing instruments. Unethical conduct shall include, but not be limited to:

.. Using or causing or promoting the use of, in any advertising matter, promotional literature, testimonial, guarantee, warranty, label, brand, insignia, or any other representation, however disseminated or published, which is false, misleading or deceptive;

.. Failing or refusing to honor or to perform as represented any representation, promise, agreement, or warranty in connection with the promotion, sale, dispensing, or fitting of the hearing instrument;

.. Advertising a particular model, type, or kind of hearing instrument for sale which purchasers or prospective purchasers responding to the advertisement cannot purchase or are dissuaded from purchasing and where it is established that the purpose of the advertisement is to obtain prospects for the sale of a different model, type, or kind than that advertised;

.. Falsifying hearing test or evaluation results;

.. [Empty]
... Whenever any of the following conditions are found or should have been found to exist either from observations by the licensee or interim permit holder or on the basis of information furnished by the prospective hearing instrument user prior to fitting and dispensing a hearing instrument to any such prospective hearing instrument user, failing to advise that prospective hearing instrument user in writing that the user should first consult a licensed physician specializing in diseases of the ear or if no such licensed physician is available in the community then to any duly licensed physician:

(A) Visible congenital or traumatic deformity of the ear, including perforation of the eardrum;

(B) History of, or active drainage from the ear within the previous ninety days;

(C) History of sudden or rapidly progressive hearing loss within the previous ninety days;

(D) Acute or chronic dizziness;

(E) Any unilateral hearing loss;

(F) Significant air-bone gap when generally acceptable standards have been established as defined by the food and drug administration;

(G) Visible evidence of significant cerumen accumulation or a foreign body in the ear canal;

(H) Pain or discomfort in the ear; or

(I) Any other conditions that the board may by rule establish. It is a violation of this subsection for any licensee or that licensee's employees and putative agents upon making such required referral for medical opinion to in any manner whatsoever disparage or discourage a prospective hearing instrument user from seeking such medical opinion prior to the fitting and dispensing of a hearing instrument. No such referral for medical opinion need be made by any licensed hearing aid specialist, licensed audiologist, or interim permit holder in the instance of replacement only of a hearing instrument which has been lost or damaged beyond repair within twelve months of the date of purchase. The licensed hearing aid specialist, licensed audiologist, or interim permit holder or their employees or putative agents shall obtain a signed statement from the hearing instrument user documenting the waiver of medical clearance and the waiver shall inform the prospective user that signing the waiver is not in the user's best health interest: PROVIDED, That the licensed hearing aid specialist, licensed audiologist, or interim permit holder shall maintain a copy of either the physician's statement showing that the prospective hearing instrument user has had a medical evaluation within the previous six months or the statement waiving medical evaluation, for a period of three years after the purchaser's receipt of a hearing instrument. Nothing in this section required to be performed by a licensee or interim permit holder shall mean that the licensee or interim permit holder is engaged in the diagnosis of illness or the practice of medicine or any other activity prohibited under the laws of this state;

... Fitting and dispensing a hearing instrument to any person under eighteen years of age who has not been examined and cleared for hearing instrument use within the previous six months by a physician specializing in otolaryngology except in the case of replacement instruments or except in the case of the parents or guardian of such person refusing, for good cause, to seek medical opinion: PROVIDED, That should the parents or guardian of such person refuse, for good cause, to seek medical opinion, the licensed hearing aid specialist or licensed audiologist shall obtain from such parents or guardian a certificate to that effect in a form as prescribed by the department;

... Fitting and dispensing a hearing instrument to any person under eighteen years of age who has not been examined by an audiologist who holds at least a master's degree in audiology for recommendations during the previous six months, without first advising such person or his or her parents or guardian in writing that he or she should first consult an audiologist who holds at least a master's degree in audiology, except in cases of hearing instruments replaced within twelve months of their purchase;

.. Representing that the services or advice of a person licensed to practice medicine and surgery under chapter 18.71 RCW or osteopathic medicine and surgery under chapter 18.57 RCW or of a clinical audiologist will be used or made available in the selection, fitting, adjustment, maintenance, or repair of hearing instruments when that is not true, or using the word "doctor," "clinic," or other like words, abbreviations, or symbols which tend to connote a medical or osteopathic medicine and surgery profession when such use is not accurate;

.. Permitting another to use his or her license or interim permit;

.. Stating or implying that the use of any hearing instrument will restore normal hearing, preserve hearing, prevent or retard progression of a hearing impairment, or any other false, misleading, or medically or audiologically unsupportable claim regarding the efficiency of a hearing instrument;

.. Representing or implying that a hearing instrument is or will be "custom-made," "made to order," "prescription made," or in any other sense specially fabricated for an individual when that is not the case; or

.. Directly or indirectly offering, giving, permitting, or causing to be given, money or anything of value to any person who advised another in a professional capacity as an inducement to influence that person, or to have that person influence others to purchase or contract to purchase any product sold or offered for sale by the hearing aid specialist, audiologist, or interim permit holder, or to influence any person to refrain from dealing in the products of competitors.

. Engaging in any unfair or deceptive practice or unfair method of competition in trade within the meaning of RCW 19.86.020.

. Aiding or abetting any violation of the rebating laws as stated in chapter 19.68 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2108.SL.pdf?cite=2014%20c%20189%20§%2010[2014 c 189 § 10]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2589-S.SL.pdf?cite=2002%20c%20310%20§%2012[2002 c 310 § 12]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1998%20c%20142%20§%208[1998 c 142 § 8]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2309-S.SL.pdf?cite=1996%20c%20200%20§%2015[1996 c 200 § 15]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1627.SL.pdf?cite=1996%20c%20178%20§%201[1996 c 178 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1500-S.SL.pdf?cite=1993%20c%20313%20§%204[1993 c 313 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c150.pdf?cite=1987%20c%20150%20§%2022[1987 c 150 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c39.pdf?cite=1983%20c%2039%20§%209[1983 c 39 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c106.pdf?cite=1973%201st%20ex.s.%20c%20106%20§%2011[1973 1st ex.s. c 106 § 11]; ]

== 18.35.120 - Disciplinary action—Additional grounds.
A licensee or interim permit holder under this chapter may also be subject to disciplinary action if the licensee or interim permit holder:

. Is found guilty in any court of any crime involving forgery, embezzlement, obtaining money under false pretenses, larceny, extortion, or conspiracy to defraud and ten years have not elapsed since the date of the conviction; or

. Has a judgment entered against him or her in any civil action involving forgery, embezzlement, obtaining money under false pretenses, larceny, extortion, or conspiracy to defraud and five years have not elapsed since the date of the entry of the final judgment in the action, but a license shall not be issued unless the judgment debt has been discharged; or

. Has a judgment entered against him or her under chapter 19.86 RCW and two years have not elapsed since the entry of the final judgment; but a license shall not be issued unless there has been full compliance with the terms of such judgment, if any. The judgment shall not be grounds for denial, suspension, nonrenewal, or revocation of a license unless the judgment arises out of and is based on acts of the applicant, licensee, or employee of the licensee; or

. Commits unprofessional conduct as defined in RCW 18.130.180 of the uniform disciplinary act.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2589-S.SL.pdf?cite=2002%20c%20310%20§%2013[2002 c 310 § 13]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1998%20c%20142%20§%209[1998 c 142 § 9]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2309-S.SL.pdf?cite=1996%20c%20200%20§%2017[1996 c 200 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c39.pdf?cite=1983%20c%2039%20§%2010[1983 c 39 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c106.pdf?cite=1973%201st%20ex.s.%20c%20106%20§%2012[1973 1st ex.s. c 106 § 12]; ]

== 18.35.140 - Powers and duties of department.
The powers and duties of the department, in addition to the powers and duties provided under other sections of this chapter, are as follows:

. To provide space necessary to carry out the examination set forth in RCW 18.35.070 of applicants for hearing aid specialist licenses or audiology licenses.

. To authorize all disbursements necessary to carry out the provisions of this chapter.

. To require the periodic examination of testing equipment, as defined by the board, and to carry out the periodic inspection of facilities or establishments of persons who are licensed under this chapter, as reasonably required within the discretion of the department.

. To appoint advisory committees as necessary.

. To keep a record of proceedings under this chapter and a register of all persons licensed or holding interim permits under this chapter. The register shall show the name of every living licensee or interim permit holder for hearing aid specialist, every living licensee or interim permit holder for speech-language pathology, and every living licensee or interim permit holder for audiology, with his or her last known place of residence and the date and number of his or her license or interim permit.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2108.SL.pdf?cite=2014%20c%20189%20§%2011[2014 c 189 § 11]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2589-S.SL.pdf?cite=2002%20c%20310%20§%2014[2002 c 310 § 14]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1998%20c%20142%20§%2010[1998 c 142 § 10]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2309-S.SL.pdf?cite=1996%20c%20200%20§%2018[1996 c 200 § 18]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1500-S.SL.pdf?cite=1993%20c%20313%20§%205[1993 c 313 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c39.pdf?cite=1983%20c%2039%20§%2011[1983 c 39 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c106.pdf?cite=1973%201st%20ex.s.%20c%20106%20§%2014[1973 1st ex.s. c 106 § 14]; ]

== 18.35.150 - Board of hearing and speech—Created—Membership—Qualifications—Terms—Vacancies—Meetings—Compensation—Travel expenses.
. There is created hereby the board of hearing and speech to govern the three separate professions: Hearing aid specialist, audiology, and speech-language pathology. The board shall consist of eleven members to be appointed by the governor.

. Members of the board shall be residents of this state. Three members shall represent the public and shall have an interest in the rights of consumers of health services, and shall not be or have been a member of, or married to a member of, another licensing board, a licensee of a health occupation board, an employee of a health facility, nor derive his or her primary livelihood from the provision of health services at any level of responsibility. Two members shall be hearing aid specialists who are licensed under this chapter, have at least five years of experience in the practice of hearing instrument fitting and dispensing, and must be actively engaged in fitting and dispensing within two years of appointment. Two members of the board shall be audiologists licensed under this chapter who have at least five years of experience in the practice of audiology and must be actively engaged in practice within two years of appointment. Two members of the board shall be speech-language pathologists licensed under this chapter who have at least five years of experience in the practice of speech-language pathology and must be actively engaged in practice within two years of appointment. One advisory nonvoting member shall be a speech-language pathology assistant certified in Washington. One advisory nonvoting member shall be a medical physician licensed in the state of Washington.

. The term of office of a member is three years. Of the initial appointments, one hearing aid specialist, one speech-language pathologist, one audiologist, and one consumer shall be appointed for a term of two years, and one hearing aid specialist, one speech-language pathologist, one audiologist, and two consumers shall be appointed for a term of three years. Thereafter, all appointments shall be made for expired terms. No member shall be appointed to serve more than two consecutive terms. A member shall continue to serve until a successor has been appointed. The governor shall either reappoint the member or appoint a successor to assume the member's duties at the expiration of his or her predecessor's term. A vacancy in the office of a member shall be filled by appointment for the unexpired term.

. The chair shall rotate annually among the hearing aid specialists, speech-language pathologists, audiologists, and public members serving on the board. In the absence of the chair, the board shall appoint an interim chair. In event of a tie vote, the issue shall be brought to a second vote and the chair shall refrain from voting.

. The board shall meet at least once each year, at a place, day and hour determined by the board, unless otherwise directed by a majority of board members. The board shall also meet at such other times and places as are requested by the department or by three members of the board. A quorum is a majority of the board. A hearing aid specialist, speech-language pathologist, and audiologist must be represented. Meetings of the board shall be open and public, except the board may hold executive sessions to the extent permitted by chapter 42.30 RCW.

. Members of the board shall be compensated in accordance with RCW 43.03.240 and shall be reimbursed for their travel expenses in accordance with RCW 43.03.050 and 43.03.060.

. The governor may remove a member of the board for cause at the recommendation of a majority of the board.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2108.SL.pdf?cite=2014%20c%20189%20§%2012[2014 c 189 § 12]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5601-S.SL.pdf?cite=2009%20c%20301%20§%205[2009 c 301 § 5]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2589-S.SL.pdf?cite=2002%20c%20310%20§%2015[2002 c 310 § 15]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2309-S.SL.pdf?cite=1996%20c%20200%20§%2019[1996 c 200 § 19]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1500-S.SL.pdf?cite=1993%20c%20313%20§%206[1993 c 313 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c198.pdf?cite=1989%20c%20198%20§%207[1989 c 198 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c287.pdf?cite=1984%20c%20287%20§%2033[1984 c 287 § 33]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c39.pdf?cite=1983%20c%2039%20§%2012[1983 c 39 § 12]; 1975-'76 2nd ex.s. c 34 § 35; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c106.pdf?cite=1973%201st%20ex.s.%20c%20106%20§%2015[1973 1st ex.s. c 106 § 15]; ]

== 18.35.161 - Board—Powers and duties.
The board shall have the following powers and duties:

. To establish by rule such minimum standards and procedures in the fitting and dispensing of hearing instruments as deemed appropriate and in the public interest;

. To adopt any other rules necessary to implement this chapter and which are not inconsistent with it;

. To develop, approve, and administer or supervise the administration of examinations to applicants for licensure under this chapter;

. To require a licensee or interim permit holder to make restitution to any individual injured by a violation of this chapter or chapter 18.130 RCW, the uniform disciplinary act. The authority to require restitution does not limit the board's authority to take other action deemed appropriate and provided for in this chapter or chapter 18.130 RCW;

. To pass upon the qualifications of applicants for licensure or interim permits and to certify to the secretary;

. To recommend requirements for continuing education and continuing competency requirements as a prerequisite to renewing a license or certification under this chapter;

. To keep an official record of all its proceedings. The record is evidence of all proceedings of the board that are set forth in this record;

. To adopt rules, if the board finds it appropriate, in response to questions put to it by professional health associations, hearing aid specialists, audiologists, speech-language pathologists, interim permit holders, and consumers in this state; and

. To adopt rules relating to standards of care relating to hearing aid specialists or audiologists, including the dispensing of hearing instruments, and relating to speech-language pathologists, including dispensing of communication devices.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2108.SL.pdf?cite=2014%20c%20189%20§%2013[2014 c 189 § 13]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6297.SL.pdf?cite=2010%20c%2065%20§%204[2010 c 65 § 4]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2589-S.SL.pdf?cite=2002%20c%20310%20§%2016[2002 c 310 § 16]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1998%20c%20142%20§%2011[1998 c 142 § 11]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2309-S.SL.pdf?cite=1996%20c%20200%20§%2020[1996 c 200 § 20]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1500-S.SL.pdf?cite=1993%20c%20313%20§%207[1993 c 313 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c150.pdf?cite=1987%20c%20150%20§%2023[1987 c 150 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c39.pdf?cite=1983%20c%2039%20§%2013[1983 c 39 § 13]; ]

== 18.35.162 - Unprofessional conduct.
Violation of the standards adopted by rule under RCW 18.35.161 is unprofessional conduct under this chapter and chapter 18.130 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2309-S.SL.pdf?cite=1996%20c%20200%20§%2021[1996 c 200 § 21]; ]

== 18.35.172 - Application of uniform disciplinary act.
The uniform disciplinary act, chapter 18.130 RCW, governs unlicensed practice, the issuance and denial of licenses and interim permits, and the discipline of licensees and permit holders under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2589-S.SL.pdf?cite=2002%20c%20310%20§%2017[2002 c 310 § 17]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1998%20c%20142%20§%2012[1998 c 142 § 12]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2309-S.SL.pdf?cite=1996%20c%20200%20§%2022[1996 c 200 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c150.pdf?cite=1987%20c%20150%20§%2021[1987 c 150 § 21]; ]

== 18.35.175 - Unlawful sales practices.
It is unlawful to fit or dispense a hearing instrument to a resident of this state if the attempted sale or purchase is offered or made by telephone or mail order and there is no face-to-face contact to test or otherwise determine the needs of the prospective purchaser. This section does not apply to the sale of hearing instruments by wholesalers to licensees under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2589-S.SL.pdf?cite=2002%20c%20310%20§%2018[2002 c 310 § 18]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2309-S.SL.pdf?cite=1996%20c%20200%20§%2023[1996 c 200 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c39.pdf?cite=1983%20c%2039%20§%2021[1983 c 39 § 21]; ]

== 18.35.180 - Application of Consumer Protection Act and False Advertising Act.
Acts and practices in the course of trade in the promoting, advertising, selling, fitting, and dispensing of hearing instruments shall be subject to the provisions of chapter 19.86 RCW (Consumer Protection Act) and RCW 9.04.050 (False Advertising Act) and any violation of the provisions of this chapter shall constitute violation of RCW 19.86.020.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2309-S.SL.pdf?cite=1996%20c%20200%20§%2024[1996 c 200 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c106.pdf?cite=1973%201st%20ex.s.%20c%20106%20§%2018[1973 1st ex.s. c 106 § 18]; ]

== 18.35.185 - Rescission of transaction—Requirements—Notice.
. In addition to any other rights and remedies a purchaser may have, the purchaser of a hearing instrument shall have the right to rescind the transaction for other than the licensed hearing aid specialist, licensed audiologist, or interim permit holder's breach if:

.. The purchaser, for reasonable cause, returns the hearing instrument or holds it at the licensed hearing aid specialist, licensed audiologist, or interim permit holder's disposal, if the hearing instrument is in its original condition less normal wear and tear. "Reasonable cause" shall be defined by the board but shall not include a mere change of mind on the part of the purchaser or a change of mind related to cosmetic concerns of the purchaser about wearing a hearing instrument; and

.. The purchaser sends notice of the cancellation by certified mail, return receipt requested, to the establishment employing the licensed hearing aid specialist, licensed audiologist, or interim permit holder at the time the hearing instrument was originally purchased, and the notice is posted not later than thirty days following the date of delivery, but the purchaser and the licensed hearing aid specialist, licensed audiologist, or interim permit holder may extend the deadline for posting of the notice of rescission by mutual, written agreement. In the event the hearing instrument develops a problem which qualifies as a reasonable cause for recision or which prevents the purchaser from evaluating the hearing instrument, and the purchaser notifies the establishment employing the licensed hearing aid specialist, licensed audiologist, or interim permit holder of the problem during the thirty days following the date of delivery and documents such notification, the deadline for posting the notice of rescission shall be extended by an equal number of days as those between the date of the notification of the problem to the date of notification of availability for redeliveries. Where the hearing instrument is returned to the licensed hearing aid specialist, licensed audiologist, or interim permit holder for any inspection for modification or repair, and the licensed hearing aid specialist, licensed audiologist, or interim permit holder has notified the purchaser that the hearing instrument is available for redelivery, and where the purchaser has not responded by either taking possession of the hearing instrument or instructing the licensed hearing aid specialist, licensed audiologist, or interim permit holder to forward it to the purchaser, then the deadline for giving notice of the recision shall extend no more than seven working days after this notice of availability.

. If the transaction is rescinded under this section or as otherwise provided by law and the hearing instrument is returned to the licensed hearing aid specialist, licensed audiologist, or interim permit holder, the licensed hearing aid specialist, licensed audiologist, or interim permit holder shall refund to the purchaser any payments or deposits for that hearing instrument. However, the licensed hearing aid specialist, licensed audiologist, or interim permit holder may retain, for each hearing instrument, fifteen percent of the total purchase price or one hundred twenty-five dollars, whichever is less. After December 31, 1996, the recision amount shall be determined by the board. The licensed hearing aid specialist, licensed audiologist, or interim permit holder shall also return any goods traded in contemplation of the sale, less any costs incurred by the licensed hearing aid specialist, licensed audiologist, or interim permit holder in making those goods ready for resale. The refund shall be made within ten business days after the rescission. The buyer shall incur no additional liability for such rescission.

. For the purposes of this section, the purchaser shall have recourse against the bond held by the establishment entering into a purchase agreement with the buyer, as provided by RCW 18.35.240.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2108.SL.pdf?cite=2014%20c%20189%20§%2014[2014 c 189 § 14]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2589-S.SL.pdf?cite=2002%20c%20310%20§%2019[2002 c 310 § 19]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1998%20c%20142%20§%2013[1998 c 142 § 13]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2309-S.SL.pdf?cite=1996%20c%20200%20§%2025[1996 c 200 § 25]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1500-S.SL.pdf?cite=1993%20c%20313%20§%209[1993 c 313 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c198.pdf?cite=1989%20c%20198%20§%2012[1989 c 198 § 12]; ]

== 18.35.190 - Valid license prerequisite to suits.
In addition to remedies otherwise provided by law, in any action brought by or on behalf of a person required to be licensed or to hold an interim permit under this chapter, or by any assignee or transferee, it shall be necessary to allege and prove that the licensee or interim permit holder at the time of the transaction held a valid license or interim permit as required by this chapter, and that such license or interim permit has not been suspended or revoked pursuant to RCW 18.35.110, 18.35.120, or 18.130.160.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2589-S.SL.pdf?cite=2002%20c%20310%20§%2020[2002 c 310 § 20]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1998%20c%20142%20§%2014[1998 c 142 § 14]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2309-S.SL.pdf?cite=1996%20c%20200%20§%2026[1996 c 200 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c198.pdf?cite=1989%20c%20198%20§%208[1989 c 198 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c150.pdf?cite=1987%20c%20150%20§%2024[1987 c 150 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c39.pdf?cite=1983%20c%2039%20§%2014[1983 c 39 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c106.pdf?cite=1973%201st%20ex.s.%20c%20106%20§%2019[1973 1st ex.s. c 106 § 19]; ]

== 18.35.195 - Exemptions.
. This chapter shall not apply to military or federal government employees.

. This chapter does not prohibit or regulate:

.. Fitting or dispensing by students enrolled in a board-approved program who are directly supervised by a licensed hearing aid specialist, a licensed audiologist under the provisions of this chapter, or an instructor at a two-year hearing aid specialist degree program that is approved by the board;

.. Hearing aid specialists, speech-language pathologists, or audiologists of other states, territories, or countries, or the District of Columbia while appearing as clinicians of bona fide educational seminars sponsored by speech-language pathology, audiology, hearing aid specialist, medical, or other healing art professional associations so long as such activities do not go beyond the scope of practice defined by this chapter; and

.. The practice of audiology or speech-language pathology by persons certified by the Washington professional educator standards board as educational staff associates, except for those persons electing to be licensed under this chapter. However, a person certified by the board as an educational staff associate who practices outside the school setting must be a licensed audiologist or licensed speech-language pathologist.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2108.SL.pdf?cite=2014%20c%20189%20§%2015[2014 c 189 § 15]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/3098-S2.SL.pdf?cite=2006%20c%20263%20§%20802[2006 c 263 § 802]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5358.SL.pdf?cite=2005%20c%2045%20§%204[2005 c 45 § 4]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2589-S.SL.pdf?cite=2002%20c%20310%20§%2021[2002 c 310 § 21]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1998%20c%20142%20§%2015[1998 c 142 § 15]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2309-S.SL.pdf?cite=1996%20c%20200%20§%2027[1996 c 200 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c39.pdf?cite=1983%20c%2039%20§%2022[1983 c 39 § 22]; ]

== 18.35.200 - Other laws unaffected.
The provisions of this chapter shall not exclude the application of any other law to persons or circumstances covered under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c106.pdf?cite=1973%201st%20ex.s.%20c%20106%20§%2020[1973 1st ex.s. c 106 § 20]; ]

== 18.35.205 - Chapter exclusive.
The legislature finds that the public health, safety, and welfare would best be protected by uniform regulation of hearing aid specialists, speech-language pathologists, speech-language pathology assistants, audiologists, and interim permit holders throughout the state. Therefore, the provisions of this chapter relating to the licensing of hearing aid specialists, speech-language pathologists, and audiologists, the certification of speech-language pathology assistants, and regulation of interim permit holders and their respective establishments or facilities is exclusive. No political subdivision of the state of Washington within whose jurisdiction a hearing aid specialist, audiologist, or speech-language pathologist establishment or facility is located may require any registrations, bonds, licenses, certificates, or interim permits of the establishment or facility or its employees or charge any fee for the same or similar purposes: PROVIDED, HOWEVER, That nothing herein shall limit or abridge the authority of any political subdivision to levy and collect a general and nondiscriminatory license fee levied on all businesses, or to levy a tax based upon the gross business conducted by any firm within the political subdivision.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2108.SL.pdf?cite=2014%20c%20189%20§%2016[2014 c 189 § 16]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5601-S.SL.pdf?cite=2009%20c%20301%20§%206[2009 c 301 § 6]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2589-S.SL.pdf?cite=2002%20c%20310%20§%2022[2002 c 310 § 22]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1998%20c%20142%20§%2016[1998 c 142 § 16]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2309-S.SL.pdf?cite=1996%20c%20200%20§%2028[1996 c 200 § 28]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c39.pdf?cite=1983%20c%2039%20§%2024[1983 c 39 § 24]; ]

== 18.35.220 - Violations—Cease and desist orders—Notice—Injunctions.
. If the board determines following notice and hearing, or following notice if no hearing was timely requested, that a person has:

.. Violated any provisions of this chapter or chapter 18.130 RCW; or

.. Violated any lawful order, or rule of the board

an order may be issued by the board requiring the person to cease and desist from the unlawful practice. The board shall then take affirmative action as is necessary to carry out the purposes of this chapter.

. If the board makes a written finding of fact that the public interest will be irreparably harmed by delay in issuing an order, a temporary cease and desist order may be issued. Prior to issuing a temporary cease and desist order, the board, whenever possible, shall give notice by telephone or otherwise of the proposal to issue a temporary cease and desist order to the person to whom the order would be directed. Every temporary cease and desist order shall include in its terms a provision that upon request a hearing will be held to determine whether the order becomes permanent.

. The department, with or without prior administrative proceedings, may bring an action in the superior court to enjoin the acts or practices and to enforce compliance with this chapter, or rule or order under this chapter. Upon proper showing, injunctive relief or temporary restraining orders shall be granted and a receiver or conservator may be appointed. The department shall not be required to post a bond in any court proceedings.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1500-S.SL.pdf?cite=1993%20c%20313%20§%2010[1993 c 313 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c150.pdf?cite=1987%20c%20150%20§%2025[1987 c 150 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c39.pdf?cite=1983%20c%2039%20§%2017[1983 c 39 § 17]; ]

== 18.35.230 - Violations—Registered agent—Service.
. Each licensee or interim permit holder shall name a registered agent to accept service of process for any violation of this chapter or rule adopted under this chapter.

. The registered agent may be released at the expiration of one year after the license or interim permit issued under this chapter has expired or been revoked.

. Failure to name a registered agent for service of process for violations of this chapter or rules adopted under this chapter may be grounds for disciplinary action.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2589-S.SL.pdf?cite=2002%20c%20310%20§%2023[2002 c 310 § 23]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1998%20c%20142%20§%2017[1998 c 142 § 17]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2309-S.SL.pdf?cite=1996%20c%20200%20§%2029[1996 c 200 § 29]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c198.pdf?cite=1989%20c%20198%20§%209[1989 c 198 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c39.pdf?cite=1983%20c%2039%20§%2019[1983 c 39 § 19]; ]

== 18.35.240 - Violations—Surety bond or security in lieu of surety bonds.
. Every individual engaged in the fitting and dispensing of hearing instruments shall be covered by a surety bond of ten thousand dollars or more, for the benefit of any person injured or damaged as a result of any violation by the licensee or permit holder, or their employees or agents, of any of the provisions of this chapter or rules adopted by the secretary.

. In lieu of the surety bond required by this section, the licensee or permit holder may deposit cash or other negotiable security in a banking institution as defined in *chapter 30.04 RCW or a credit union as defined in chapter 31.12 RCW. All obligations and remedies relating to surety bonds shall apply to deposits and security filed in lieu of surety bonds.

. If a cash deposit or other negotiable security is filed, the licensee or permit holder shall maintain such cash or other negotiable security for one year after discontinuing the fitting and dispensing of hearing instruments.

. Each invoice for the purchase of a hearing instrument provided to a customer must clearly display on the first page the bond number covering the licensee or interim permit holder responsible for fitting/dispensing the hearing instrument.

. All licensed hearing aid specialists, licensed audiologists, and permit holders must verify compliance with the requirement to hold a surety bond or cash or other negotiable security by submitting a signed declaration of compliance upon annual renewal of their license or permit. Up to twenty-five percent of the credential holders may be randomly audited for surety bond compliance after the credential is renewed. It is the credential holder's responsibility to submit a copy of the original surety bond or bonds, or documentation that cash or other negotiable security is held in a banking institution during the time period being audited. Failure to comply with the audit documentation request or failure to supply acceptable documentation within thirty days may result in disciplinary action.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2108.SL.pdf?cite=2014%20c%20189%20§%2017[2014 c 189 § 17]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2589-S.SL.pdf?cite=2002%20c%20310%20§%2024[2002 c 310 § 24]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2452.SL.pdf?cite=2000%20c%2093%20§%202[2000 c 93 § 2]; 2000 c 93 § 1; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1998%20c%20142%20§%2018[1998 c 142 § 18]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2309-S.SL.pdf?cite=1996%20c%20200%20§%2030[1996 c 200 § 30]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1500-S.SL.pdf?cite=1993%20c%20313%20§%2011[1993 c 313 § 11]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2085[1991 c 3 § 85]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c198.pdf?cite=1989%20c%20198%20§%2010[1989 c 198 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c39.pdf?cite=1983%20c%2039%20§%2018[1983 c 39 § 18]; ]

== 18.35.250 - Violations—Remedies—Actions on bond or security.
. In addition to any other legal remedies, an action may be brought in any court of competent jurisdiction upon the bond, cash deposit, or security in lieu of a surety bond required by this chapter, by any person having a claim against a licensee or interim permit holder, agent, or employee for any violation of this chapter or any rule adopted under this chapter. The aggregate liability of the surety, cash deposit, or other negotiable security to all claimants shall in no event exceed the sum of the bond. Claims shall be satisfied in the order of judgment rendered.

. An action upon the bond, cash deposit, or other negotiable security shall be commenced by serving and filing a complaint.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2589-S.SL.pdf?cite=2002%20c%20310%20§%2025[2002 c 310 § 25]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2452.SL.pdf?cite=2000%20c%2093%20§%204[2000 c 93 § 4]; 2000 c 93 § 3; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1998%20c%20142%20§%2019[1998 c 142 § 19]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2309-S.SL.pdf?cite=1996%20c%20200%20§%2031[1996 c 200 § 31]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2086[1991 c 3 § 86]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c198.pdf?cite=1989%20c%20198%20§%2011[1989 c 198 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c39.pdf?cite=1983%20c%2039%20§%2020[1983 c 39 § 20]; ]

== 18.35.260 - Misrepresentation of credentials.
. A person who is not a licensed hearing aid specialist may not represent himself or herself as being so licensed and may not use in connection with his or her name the words "licensed hearing instrument fitter/dispenser," "hearing instrument specialist," or "hearing aid fitter/dispenser," or a variation, synonym, word, sign, number, insignia, coinage, or whatever expresses, employs, or implies these terms, names, or functions of a licensed hearing aid specialist.

. A person who is not a licensed speech-language pathologist may not represent himself or herself as being so licensed and may not use in connection with his or her name the words including "licensed speech-language pathologist" or a variation, synonym, word, sign, number, insignia, coinage, or whatever expresses, employs, or implies these terms, names, or functions as a licensed speech-language pathologist.

. A person who is not a certified speech-language pathology assistant may not represent himself or herself as being so certified and may not use in connection with his or her name the words including "certified speech-language pathology assistant" or a variation, synonym, word, sign, number, insignia, coinage, or whatever expresses, employs, or implies these terms, names, or functions as a certified speech-language pathology assistant.

. A person who is not a licensed audiologist may not represent himself or herself as being so licensed and may not use in connection with his or her name the words "licensed audiologist" or a variation, synonym, letter, word, sign, number, insignia, coinage, or whatever expresses, employs, or implies these terms, names, or functions of a licensed audiologist.

. Nothing in this chapter prohibits a person credentialed in this state under another act from engaging in the practice for which he or she is credentialed.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2108.SL.pdf?cite=2014%20c%20189%20§%2018[2014 c 189 § 18]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5601-S.SL.pdf?cite=2009%20c%20301%20§%207[2009 c 301 § 7]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2589-S.SL.pdf?cite=2002%20c%20310%20§%2026[2002 c 310 § 26]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1998%20c%20142%20§%2020[1998 c 142 § 20]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2309-S.SL.pdf?cite=1996%20c%20200%20§%2016[1996 c 200 § 16]; ]

== 18.35.270 - Assistant ratios—Data collection.
Recognizing the trend in utilization of speech-language pathologist assistants and audiologist assistants across practice settings, the board of hearing and speech shall, on an ongoing basis, collect data on: The number of assistants in specific practice settings; supervisor to speech-language pathologist assistant or audiologist assistant ratios; and the level of education and training of speech-language pathologist assistants and audiologist assistants.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2309-S.SL.pdf?cite=1996%20c%20200%20§%2035[1996 c 200 § 35]; ]

== 18.35.280 - Delegation to assistive personnel—Supervisor duties.
Speech-language pathologists are responsible for patient care given by assistive personnel under their supervision. A speech-language pathologist may delegate to assistive personnel selected acts, tasks, or procedures that fall within the scope of speech-language pathology practice but do not exceed the education or training of the assistive personnel.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5601-S.SL.pdf?cite=2009%20c%20301%20§%209[2009 c 301 § 9]; ]

== 18.35.290 - Delegation to assistive personnel—Assistant duties.
A speech-language pathology assistant may only perform procedures or tasks delegated by the speech-language pathologist and must follow the individualized education program or treatment plan. Speech-language pathology assistants may not perform procedures or tasks that require diagnosis, evaluation, or clinical interpretation.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5601-S.SL.pdf?cite=2009%20c%20301%20§%2010[2009 c 301 § 10]; ]

== 18.35.300 - No requirement to contract with speech-language pathology assistant.
Nothing in this chapter may be construed to require that a health carrier defined in RCW 48.43.005 contract with a person certified as a speech-language pathology assistant under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5601-S.SL.pdf?cite=2009%20c%20301%20§%2012[2009 c 301 § 12]; ]

== 18.35.310 - Hearing instruments—Notice—Rules.
. Any person who engages in fitting and dispensing of hearing instruments shall:

.. Prior to initial fitting and purchase, notify a person seeking to purchase a hearing instrument, both orally and in writing, about the uses, benefits, and limitations of current hearing assistive technologies, as defined by the department of health in rule.

.. Provide to each person who enters into an agreement to purchase a hearing instrument a receipt, which must be signed by the purchaser at the time of the purchase, containing language that verifies that prior to initial fitting and purchase the consumer was informed, both orally and in writing, about the uses, benefits, and limitations of current hearing assistive technologies, as defined by the department of health in rule.

. The department may adopt rules to create a standard receipt form that persons required to provide notice under this section may provide to purchasers, as required in subsection (1)(a) of this section.

. A person required to provide written notice in subsection (1) of this section may produce written materials, use materials produced by hearing instrument manufacturers or others, or use the materials created by the office of the deaf and hard of hearing, as required in RCW 43.20A.675.

. This section may not be construed to create a private right of action or claim against any person engaging in the fitting and dispensing of hearing instruments.

. The department must adopt rules necessary to implement this section. The department may consider a number of factors in defining current hearing assistive technologies, but must consider whether hearing assistive technologies are compatible with assistive listening systems that are compliant with the Americans with disabilities act.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5210.SL.pdf?cite=2019%20c%20183%20§%202[2019 c 183 § 2]; ]

== 18.35.903 - Construction—Chapter applicable to state registered domestic partnerships—2009 c 521.
For the purposes of this chapter, the terms spouse, marriage, marital, husband, wife, widow, widower, next of kin, and family shall be interpreted as applying equally to state registered domestic partnerships or individuals in state registered domestic partnerships as well as to marital relationships and married persons, and references to dissolution of marriage shall apply equally to state registered domestic partnerships that have been terminated, dissolved, or invalidated, to the extent that such interpretation does not conflict with federal law. Where necessary to implement chapter 521, Laws of 2009, gender-specific terms such as husband and wife used in any statute, rule, or other law shall be construed to be gender neutral, and applicable to individuals in state registered domestic partnerships.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%2046[2009 c 521 § 46]; ]

