= 18.55 - Ocularists.
:toc:

== 18.55.007 - License required.
No person may practice or represent himself or herself as an ocularist without first having a valid license to do so.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c150.pdf?cite=1987%20c%20150%20§%2040[1987 c 150 § 40]; ]

== 18.55.010 - Licensing—Exemptions—Limitations.
. Nothing in this chapter shall:

.. Be construed to limit or restrict a duly licensed physician or employees working under the personal supervision of a duly licensed physician from the practices enumerated in this chapter;

.. Be construed to prohibit an unlicensed person from performing mechanical work upon inert matter in an ocularist's office or laboratory;

.. Be construed to authorize or permit a licensee under this chapter to hold himself or herself out as being able to, or to offer to, or to undertake to attempt, by any manner of means, to examine or exercise eyes, or diagnose, treat, correct, relieve, operate, or prescribe for disease or any visual deficiency.

. Each practitioner duly licensed pursuant to chapters 18.53, 18.57, and 18.71 RCW shall have all the rights and privileges which may accrue under this chapter to ocularists licensed under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c101.pdf?cite=1980%20c%20101%20§%201[1980 c 101 § 1]; ]

== 18.55.015 - Intent.
The legislature finds it necessary to regulate the practice of ocularist to protect the public health, safety, and welfare. The legislature intends that only individuals who meet and maintain minimum standards of competence and conduct may provide service to the public.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5632-S.SL.pdf?cite=1991%20c%20180%20§%201[1991 c 180 § 1]; ]

== 18.55.020 - Definitions.
The terms defined in this section shall have the meaning ascribed to them wherever appearing in this chapter, unless a different meaning is specifically used to such term in such statute.

. "Department" means the department of health.

. "Secretary" means the secretary of health.

. "Ocularist" means a person licensed under this chapter.

. "Apprentice" means a person designated an apprentice in the records of the secretary to receive from a licensed ocularist training and direct supervision in the work of an ocularist.

. "Stock-eye" means an ocular stock prosthesis that has not been originally manufactured or altered by the ocularist or service provider selling or fitting, or both, said prosthesis to a patient or customer. "Altered" means either taking away or adding materials, or colorization, or otherwise changing the prosthesis' appearance, function, or fit in the socket or on the implant of the patient or customer.

. "Modified stock-eye" means a stock-eye that has been altered in some manner by the ocularist or service provider selling or fitting, or both, said prosthesis to a patient or customer. "Altered" is as defined in subsection (5) of this section. A modified stock-eye cannot be defined as either a "custom" or "impression-fitted" eye or prosthesis by adding material that incorporates an impression-surface of the patient or customer socket or implant surfaces.

. "Custom-eye" means an original, newly manufactured eye or prosthesis that has been specifically crafted by an ocularist or authorized service provider for the patient or customer to whom it is sold or provided. The "custom-eye" may be either an impression-fitted eye (an impression of the socket or implant surfaces) or an empirical/wax pattern-fitted method eye, or a combination of either, as delineated in the ocularist examination.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20504[1994 sp.s. c 9 § 504]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5632-S.SL.pdf?cite=1991%20c%20180%20§%202[1991 c 180 § 2]; 1991 c 3 § 142; 1991 sp.s. c 11 § 2; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c101.pdf?cite=1980%20c%20101%20§%202[1980 c 101 § 2]; ]

== 18.55.030 - Licenses—Renewal.
The secretary shall determine administrative procedures, administrative requirements, and fees for licenses and renewals as provided in RCW 43.70.250 and 43.70.280.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2031[1996 c 191 § 31]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20143[1991 c 3 § 143]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c101.pdf?cite=1980%20c%20101%20§%203[1980 c 101 § 3]; ]

== 18.55.040 - License applicants—Qualifications—Examination.
No applicant shall be licensed under this chapter until the applicant complies with administrative procedures, administrative requirements, and fees determined by the secretary according to RCW 43.70.250 and 43.70.280. Qualifications must require that the applicant:

. Is eighteen years or more of age;

. Has graduated from high school or has received a high school equivalency certificate as provided in RCW 28B.50.536;

. Is of good moral character; and

. [Empty]
.. Had at least ten thousand hours of apprenticeship training under the direct supervision of a licensed ocularist; or

.. Successfully completed a prescribed course in ocularist training programs approved by the secretary; or

.. Has had at least ten thousand hours of apprenticeship training under the direct supervision of a practicing ocularist, or has the equivalent experience as a practicing ocularist, or any combination of training and supervision, not in the state of Washington; and

. Successfully passes an examination conducted or approved by the secretary.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1686-S.SL.pdf?cite=2013%20c%2039%20§%202[2013 c 39 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2032[1996 c 191 § 32]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5632-S.SL.pdf?cite=1991%20c%20180%20§%204[1991 c 180 § 4]; 1991 c 3 § 144; 1991 sp.s. c 11 § 2; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%2053[1985 c 7 § 53]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c101.pdf?cite=1980%20c%20101%20§%204[1980 c 101 § 4]; ]

== 18.55.043 - Licensing requirements—Military training or experience.
An applicant with military training or experience satisfies the training or experience requirements of this chapter unless the secretary determines that the military training or experience is not substantially equivalent to the standards of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5307-S.SL.pdf?cite=2011%20c%2032%20§%203[2011 c 32 § 3]; ]

== 18.55.045 - Examination.
The secretary may approve an examination prepared or administered by a private testing agency or association of licensing authorities. The examination shall determine if the applicant has a thorough knowledge of the principles governing the practice of an ocularist.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5632-S.SL.pdf?cite=1991%20c%20180%20§%205[1991 c 180 § 5]; ]

== 18.55.050 - Licenses or registrations—Renewal.
Every individual licensed or registered under this chapter shall comply with administrative procedures, administrative requirements, and fees determined by the secretary, as provided by RCW 43.70.250 and 43.70.280 to renew his or her license.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2033[1996 c 191 § 33]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5632-S.SL.pdf?cite=1991%20c%20180%20§%206[1991 c 180 § 6]; 1991 c 3 § 145; 1991 sp.s. c 11 § 2; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%2054[1985 c 7 § 54]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c101.pdf?cite=1980%20c%20101%20§%207[1980 c 101 § 7]; ]

== 18.55.060 - Apprentices.
. A person wishing to work as an apprentice ocularist shall submit to the secretary the registration fee and completed application form signed by the applicant and the licensed ocularist who shall be responsible for the acts of the apprentice in the performance of his or her work in the apprenticeship program.

. Apprentices shall complete their ten thousand hours of apprenticeship within eight years and shall not work longer as an apprentice unless the secretary determines, after a hearing, that the apprentice was prevented by causes beyond his or her control from completing the apprenticeship and becoming a licensee hereunder in eight years.

. No licensee under this chapter may have more than two apprentices in training at one time.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5632-S.SL.pdf?cite=1991%20c%20180%20§%207[1991 c 180 § 7]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20146[1991 c 3 § 146]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c101.pdf?cite=1980%20c%20101%20§%205[1980 c 101 § 5]; ]

== 18.55.066 - Application of uniform disciplinary act.
The uniform disciplinary act, chapter 18.130 RCW, governs unlicensed practice, the issuance and denial of licenses, and the discipline of licensees under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c150.pdf?cite=1987%20c%20150%20§%2039[1987 c 150 § 39]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c259.pdf?cite=1986%20c%20259%20§%2089[1986 c 259 § 89]; ]

== 18.55.075 - Scope of practice.
An ocularist designs, fabricates, and fits ocular prosthetic appliances. An ocularist is authorized to perform the necessary procedures to provide an ocular prosthetic service for the patient in the ocularist's office or laboratory on referral of a physician. A referral is not required for the replacement of an ocular prosthetic appliance. The ocularist is authorized to make judgment on the needed care, replacement, and use of an ocular prosthetic appliance. The ocularist is authorized to design, fabricate, and fit human prosthetics in the following categories:

. Stock and custom prosthetic eyes;

. Stock and custom therapeutic scleral shells;

. Stock and custom therapeutic painted iris shells;

. External orbital and facial prosthetics; and

. Ocular conformers: PROVIDED, That nothing herein shall be construed to allow the fitting or fabricating of contact lenses.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5632-S.SL.pdf?cite=1991%20c%20180%20§%203[1991 c 180 § 3]; ]

== 18.55.085 - Unprofessional conduct.
An ocularist or authorized service provider shall explain to patients or customers exactly which type of prosthesis or service they are receiving or purchasing. Failure to do so, or misrepresentation of said services, constitutes unprofessional conduct under this chapter and chapter 18.130 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5632-S.SL.pdf?cite=1991%20c%20180%20§%209[1991 c 180 § 9]; ]

== 18.55.095 - Authority of secretary.
In addition to any other authority provided by law, the secretary may:

. Adopt rules in accordance with chapter 34.05 RCW necessary to implement this chapter;

. Establish forms necessary to administer this chapter;

. Issue a license to any applicant who has met the education, training, and examination requirements for licensure and deny a license to applicants who do not meet the minimum qualifications for licensure. Proceedings concerning the denial of licenses based on unprofessional conduct or impaired practice shall be governed by the uniform disciplinary act, chapter 18.130 RCW;

. Employ clerical, administrative, and investigative staff as needed to implement and administer this chapter and hire individuals, including those licensed under this chapter, to serve as examiners or consultants as necessary to implement and administer this chapter;

. Maintain the official departmental record of all applicants and licensees;

. Determine the minimum education and experience requirements for licensure, including but not limited to approval of educational programs;

. Prepare and administer or approve the preparation and administration of examinations for licensure; and

. Establish and implement by rule a continuing competency program.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5632-S.SL.pdf?cite=1991%20c%20180%20§%208[1991 c 180 § 8]; ]

== 18.55.105 - Out-of-state applicants.
An applicant holding a credential in another state may be credentialed to practice in this state without examination if the secretary determines that the other state's credentialing standards are substantially equivalent to the standards in this state.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5632-S.SL.pdf?cite=1991%20c%20180%20§%2012[1991 c 180 § 12]; ]

