= 18.79 - Nursing care.
:toc:

== 18.79.010 - Purpose.
It is the purpose of the nursing care quality assurance commission to regulate the competency and quality of professional health care providers under its jurisdiction by establishing, monitoring, and enforcing qualifications for licensing, consistent standards of practice, continuing competency mechanisms, and discipline. Rules, policies, and procedures developed by the commission must promote the delivery of quality health care to the residents of the state of Washington.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20401[1994 sp.s. c 9 § 401]; ]

== 18.79.020 - Definitions.
Unless a different meaning is plainly required by the context, the definitions set forth in this section apply throughout this chapter.

. "Commission" means the Washington state nursing care quality assurance commission.

. "Department" means the department of health.

. "Secretary" means the secretary of health or the secretary's designee.

. "Diagnosis," in the context of nursing practice, means the identification of, and discrimination between, the person's physical and psychosocial signs and symptoms that are essential to effective execution and management of the nursing care regimen.

. "Diploma" means written official verification of completion of an approved nursing education program.

. "Nurse" or "nursing," unless otherwise specified as a practical nurse or practical nursing, means a registered nurse or registered nursing.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20402[1994 sp.s. c 9 § 402]; ]

== 18.79.030 - Licenses required—Titles.
. It is unlawful for a person to practice or to offer to practice as a registered nurse in this state unless that person has been licensed under this chapter. A person who holds a license to practice as a registered nurse in this state may use the titles "registered nurse" and "nurse" and the abbreviation "R.N." No other person may assume those titles or use the abbreviation or any other words, letters, signs, or figures to indicate that the person using them is a registered nurse.

. It is unlawful for a person to practice or to offer to practice as an advanced registered nurse practitioner or as a nurse practitioner in this state unless that person has been licensed under this chapter. A person who holds a license to practice as an advanced registered nurse practitioner in this state may use the titles "advanced registered nurse practitioner," "nurse practitioner," and "nurse" and the abbreviations "A.R.N.P." and "N.P." No other person may assume those titles or use those abbreviations or any other words, letters, signs, or figures to indicate that the person using them is an advanced registered nurse practitioner or nurse practitioner.

. It is unlawful for a person to practice or to offer to practice as a licensed practical nurse in this state unless that person has been licensed under this chapter. A person who holds a license to practice as a licensed practical nurse in this state may use the titles "licensed practical nurse" and "nurse" and the abbreviation "L.P.N." No other person may assume those titles or use that abbreviation or any other words, letters, signs, or figures to indicate that the person using them is a licensed practical nurse.

. Nothing in this section shall prohibit a person listed as a Christian Science nurse in the Christian Science Journal published by the Christian Science Publishing Society, Boston, Massachusetts, from using the title "Christian Science nurse," so long as such person does not hold himself or herself out as a registered nurse, advanced registered nurse practitioner, nurse practitioner, or licensed practical nurse, unless otherwise authorized by law to do so.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5976-S.SL.pdf?cite=1997%20c%20177%20§%201[1997 c 177 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20403[1994 sp.s. c 9 § 403]; ]

== 18.79.040 - "Registered nursing practice" defined—Exceptions. (Effective until July 1, 2022.)
. "Registered nursing practice" means the performance of acts requiring substantial specialized knowledge, judgment, and skill based on the principles of the biological, physiological, behavioral, and sociological sciences in either:

.. The observation, assessment, diagnosis, care or counsel, and health teaching of individuals with illnesses, injuries, or disabilities, or in the maintenance of health or prevention of illness of others;

.. The performance of such additional acts requiring education and training and that are recognized by the medical and nursing professions as proper and recognized by the commission to be performed by registered nurses licensed under this chapter and that are authorized by the commission through its rules;

.. The administration, supervision, delegation, and evaluation of nursing practice. However, nothing in this subsection affects the authority of a hospital, hospital district, in-home service agency, community-based care setting, medical clinic, or office, concerning its administration and supervision;

.. The teaching of nursing;

.. The executing of medical regimen as prescribed by a licensed physician and surgeon, dentist, osteopathic physician and surgeon, podiatric physician and surgeon, physician assistant, osteopathic physician assistant, or advanced registered nurse practitioner, or as directed by a licensed midwife within his or her scope of practice.

. Nothing in this section prohibits a person from practicing a profession for which a license has been issued under the laws of this state or specifically authorized by any other law of the state of Washington.

. This section does not prohibit (a) the nursing care of the sick, without compensation, by an unlicensed person who does not hold himself or herself out to be a registered nurse, (b) the practice of licensed practical nursing by a licensed practical nurse, or (c) the practice of a nursing assistant, providing delegated nursing tasks under chapter 18.88A RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2186.SL.pdf?cite=2012%20c%2013%20§%201[2012 c 13 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1753.SL.pdf?cite=2003%20c%20140%20§%201[2003 c 140 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1908-S2.SL.pdf?cite=1995%201st%20sp.s.%20c%2018%20§%2050[1995 1st sp.s. c 18 § 50]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20404[1994 sp.s. c 9 § 404]; ]

== 18.79.050 - "Advanced registered nursing practice" defined—Exceptions.
"Advanced registered nursing practice" means the performance of the acts of a registered nurse and the performance of an expanded role in providing health care services as recognized by the medical and nursing professions, the scope of which is defined by rule by the commission. Upon approval by the commission, an advanced registered nurse practitioner may prescribe legend drugs and controlled substances contained in Schedule V of the Uniform Controlled Substances Act, chapter 69.50 RCW, and Schedules II through IV subject to RCW 18.79.240(1) (r) or (s).

Nothing in this section prohibits a person from practicing a profession for which a license has been issued under the laws of this state or specifically authorized by any other law of the state of Washington.

This section does not prohibit (1) the nursing care of the sick, without compensation, by an unlicensed person who does not hold himself or herself out to be an advanced registered nurse practitioner, or (2) the practice of registered nursing by a licensed registered nurse or the practice of licensed practical nursing by a licensed practical nurse.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5805-S.SL.pdf?cite=2000%20c%2064%20§%202[2000 c 64 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20405[1994 sp.s. c 9 § 405]; ]

== 18.79.060 - "Licensed practical nursing practice" defined—Exceptions. (Effective until July 1, 2022.)
"Licensed practical nursing practice" means the performance of services requiring the knowledge, skill, and judgment necessary for carrying out selected aspects of the designated nursing regimen under the direction and supervision of a licensed physician and surgeon, dentist, osteopathic physician and surgeon, physician assistant, osteopathic physician assistant, podiatric physician and surgeon, advanced registered nurse practitioner, registered nurse, or midwife.

Nothing in this section prohibits a person from practicing a profession for which a license has been issued under the laws of this state or specifically authorized by any other law of the state of Washington.

This section does not prohibit the nursing care of the sick, without compensation, by an unlicensed person who does not hold himself or herself out to be a licensed practical nurse.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2186.SL.pdf?cite=2012%20c%2013%20§%202[2012 c 13 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20406[1994 sp.s. c 9 § 406]; ]

== 18.79.070 - Commission established—Membership—Qualifications.
. The state nursing care quality assurance commission is established, consisting of fifteen members to be appointed by the governor to four-year terms. The governor shall consider nursing members who are recommended for appointment by the appropriate professional associations in the state. No person may serve as a member of the commission for more than two consecutive full terms.

. There must be seven registered nurse members, two advanced registered nurse practitioner members, three licensed practical nurse members, and three public members on the commission. Each member of the commission must be a citizen of the United States and a resident of this state.

. [Empty]
.. Registered nurse members of the commission must:

... Be licensed as registered nurses under this chapter; and

... Have had at least three years' experience in the active practice of nursing and have been engaged in that practice within two years of appointment.

.. In addition:

... At least one member must be on the faculty at a four-year university nursing program;

... At least one member must be on the faculty at a two-year community college nursing program;

... At least two members must be staff nurses providing direct patient care; and

... At least one member must be a nurse manager or a nurse executive.

. Advanced registered nurse practitioner members of the commission must:

.. Be licensed as advanced registered nurse practitioners under this chapter; and

.. Have had at least three years' experience in the active practice of advanced registered nursing and have been engaged in that practice within two years of appointment.

. Licensed practical nurse members of the commission must:

.. Be licensed as licensed practical nurses under this chapter; and

.. Have had at least three years' actual experience as a licensed practical nurse and have been engaged in practice as a practical nurse within two years of appointment.

. Public members of the commission may not be a member of any other health care licensing board or commission, or have a fiduciary obligation to a facility rendering health services regulated by the commission, or have a material or financial interest in the rendering of health services regulated by the commission.

In appointing the initial members of the commission, it is the intent of the legislature that, to the extent possible, the governor appoint the existing members of the board of nursing and the board of practical nursing repealed under chapter 9, Laws of 1994 sp. sess. The governor may appoint initial members of the commission to staggered terms of from one to four years. Thereafter, all members shall be appointed to full four-year terms. Members of the commission hold office until their successors are appointed.

When the secretary appoints pro tem members, reasonable efforts shall be made to ensure that at least one pro tem member is a registered nurse who is currently practicing and, in addition to meeting other minimum qualifications, has graduated from an associate or baccalaureate nursing program within three years of appointment.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1075-S.SL.pdf?cite=2005%20c%2017%20§%201[2005 c 17 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20407[1994 sp.s. c 9 § 407]; ]

== 18.79.080 - Commission—Order of removal—Vacancy.
The governor may remove a member of the commission for neglect of duty, misconduct, malfeasance or misfeasance in office, or for incompetency or unprofessional conduct as defined in chapter 18.130 RCW. Whenever the governor is satisfied that a member of the commission has been guilty of neglect of duty, misconduct, malfeasance or misfeasance in office, or of incompetency or unprofessional conduct, the governor shall file with the secretary of state a statement of the causes for and the order of removal from office, and the secretary shall forthwith send a certified copy of the statement of causes and order of removal to the last known post office address of the member. If a vacancy occurs on the commission, the governor shall appoint a replacement member to fill the remainder of the unexpired term.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20408[1994 sp.s. c 9 § 408]; ]

== 18.79.090 - Commission—Compensation.
Each commission member shall be compensated in accordance with RCW 43.03.265 and shall be paid travel expenses when away from home in accordance with RCW 43.03.050 and 43.03.060.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1863.SL.pdf?cite=1999%20c%20366%20§%205[1999 c 366 § 5]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20409[1994 sp.s. c 9 § 409]; ]

== 18.79.100 - Commission—Officers—Meetings.
The commission shall annually elect officers from among its members. The commission shall meet at least quarterly at times and places it designates. It shall hold such other meetings during the year as may be deemed necessary to transact its business. A majority of the commission members appointed and serving constitutes a quorum at a meeting. All meetings of the commission must be open and public, except that the commission may hold executive sessions to the extent permitted by chapter 42.30 RCW.

Carrying a motion or resolution, adopting a rule, or passing a measure requires the affirmative vote of a majority of a quorum of the commission. The commission may appoint panels consisting of at least three members. A quorum for transaction of any business by a panel is a minimum of three members. A majority vote of a quorum of the panel is required to transact business delegated to it by the commission.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20410[1994 sp.s. c 9 § 410]; ]

== 18.79.110 - Commission—Duties and powers—Rules—Successor to boards.
. The commission shall keep a record of all of its proceedings and make such reports to the governor as may be required. The commission shall define by rules what constitutes specialized and advanced levels of nursing practice as recognized by the medical and nursing profession. The commission may adopt rules or issue advisory opinions in response to questions put to it by professional health associations, nursing practitioners, and consumers in this state concerning the authority of various categories of nursing practitioners to perform particular acts.

. The commission shall approve curricula and shall establish criteria for minimum standards for schools preparing persons for licensing as registered nurses, advanced registered nurse practitioners, and licensed practical nurses under this chapter. The commission shall approve such schools of nursing as meet the requirements of this chapter and the commission, and the commission shall approve establishment of basic nursing education programs and shall establish criteria as to the need for and the size of a program and the type of program and the geographical location. The commission shall establish criteria for proof of reasonable currency of knowledge and skill as a basis for safe practice after three years' inactive or lapsed status. The commission shall establish criteria for licensing by endorsement. The commission shall determine examination requirements for applicants for licensing as registered nurses, advanced registered nurse practitioners, and licensed practical nurses under this chapter, and shall certify to the secretary for licensing duly qualified applicants.

. The commission shall adopt rules on continuing competency. The rules must include exemptions from the continuing competency requirements for registered nurses seeking advanced nursing degrees. Nothing in this subsection prohibits the commission from providing additional exemptions for any person credentialed under this chapter who is enrolled in an advanced education program.

. The commission shall adopt such rules under chapter 34.05 RCW as are necessary to fulfill the purposes of this chapter.

. The commission is the successor in interest of the board of nursing and the board of practical nursing. All contracts, undertakings, agreements, rules, regulations, decisions, orders, and policies of the former board of nursing or the board of practical nursing continue in full force and effect under the commission until the commission amends or rescinds those rules, regulations, decisions, orders, or policies.

. The members of the commission are immune from suit in an action, civil or criminal, based on its disciplinary proceedings or other official acts performed in good faith as members of the commission.

. Whenever the workload of the commission requires, the commission may request that the secretary appoint pro tempore members of the commission. When serving, pro tempore members of the commission have all of the powers, duties, and immunities, and are entitled to all of the emoluments, including travel expenses, of regularly appointed members of the commission.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5092.SL.pdf?cite=2013%20c%20229%20§%201[2013 c 229 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20411[1994 sp.s. c 9 § 411]; ]

== 18.79.120 - Application of Uniform Disciplinary Act.
The Uniform Disciplinary Act, chapter 18.130 RCW, governs unlicensed practice, the issuance and denial of licenses, and the discipline of licensees under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20412[1994 sp.s. c 9 § 412]; ]

== 18.79.140 - Executive director—Qualifications.
The executive director must be a graduate of an approved nursing education program and of a college or university, with a masters' degree, and currently licensed as a registered nurse under this chapter; have a minimum of eight years' experience in nursing in any combination of administration and nursing education; and have been actively engaged in the practice of registered nursing or nursing education within two years immediately before the time of appointment.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20414[1994 sp.s. c 9 § 414]; ]

== 18.79.150 - Schools and programs—Requirements—Approval.
An institution desiring to conduct a school of registered nursing or a school or program of practical nursing, or both, shall apply to the commission and submit evidence satisfactory to the commission that:

. It is prepared to carry out the curriculum approved by the commission for basic registered nursing or practical nursing, or both; and

. It is prepared to meet other standards established by law and by the commission.

The commission shall make, or cause to be made, such surveys of the schools and programs, and of institutions and agencies to be used by the schools and programs, as it determines are necessary. If in the opinion of the commission, the requirements for an approved school of registered nursing or a school or program of practical nursing, or both, are met, the commission shall approve the school or program.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20415[1994 sp.s. c 9 § 415]; ]

== 18.79.160 - Applicants—Required documentation—Criteria—Rules.
. An applicant for a license to practice as a registered nurse shall submit to the commission:

.. An attested written application on a department form;

.. An official transcript demonstrating graduation and successful completion of an approved program of nursing; and

.. Any other official records specified by the commission.

. An applicant for a license to practice as an advanced registered nurse practitioner shall submit to the commission:

.. An attested written application on a department form;

.. An official transcript demonstrating graduation and successful completion of an advanced registered nurse practitioner program meeting criteria established by the commission; and

.. Any other official records specified by the commission.

. An applicant for a license to practice as a licensed practical nurse shall submit to the commission:

.. An attested written application on a department form;

.. Written official evidence that the applicant is over the age of eighteen;

.. An official transcript demonstrating graduation and successful completion of an approved practical nursing program, or its equivalent; and

.. Any other official records specified by the commission.

. At the time of submission of the application, the applicant for a license to practice as a registered nurse, advanced registered nurse practitioner, or licensed practical nurse must not be in violation of chapter 18.130 RCW or this chapter.

. The commission shall establish by rule the criteria for evaluating the education of all applicants.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6554-S.SL.pdf?cite=2004%20c%20262%20§%206[2004 c 262 § 6]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20416[1994 sp.s. c 9 § 416]; ]

== 18.79.170 - Examination—Rules.
An applicant for a license to practice as a registered nurse, advanced registered nurse practitioner, or licensed practical nurse must pass an examination in subjects determined by the commission. The examination may be supplemented by an oral or practical examination. The commission shall establish by rule the requirements for applicants who have failed the examination to qualify for reexamination.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20417[1994 sp.s. c 9 § 417]; ]

== 18.79.180 - Interim permits—License—Expiration upon failure.
When authorized by the commission, the department shall issue an interim permit authorizing the applicant to practice registered nursing, advanced registered nursing, or licensed practical nursing, as appropriate, from the time of verification of the completion of the school or training program until notification of the results of the examination. Upon the applicant passing the examination, and if all other requirements established by the commission for licensing are met, the department shall issue the applicant a license to practice registered nursing, advanced registered nursing, or licensed practical nursing, as appropriate. If the applicant fails the examination, the interim permit expires upon notification to the applicant, and is not renewable. The holder of an interim permit is subject to chapter 18.130 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20418[1994 sp.s. c 9 § 418]; ]

== 18.79.190 - Reciprocity—Foreign programs—Examination.
Upon approval of the application by the commission, the department shall issue a license by endorsement without examination to practice as a registered nurse or as a licensed practical nurse to a person who is licensed as a registered nurse or licensed practical nurse under the laws of another state, territory, or possession of the United States, and who meets all other qualifications for licensing.

An applicant who has graduated from a school or program of nursing outside the United States and is licensed as a registered nurse or licensed practical nurse, or their equivalents, outside the United States must meet all qualifications required by this chapter and pass examinations as determined by the commission.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20419[1994 sp.s. c 9 § 419]; ]

== 18.79.200 - License procedures, requirements, fees.
An applicant for a license to practice as a registered nurse, advanced registered nurse practitioner, or licensed practical nurse shall comply with administrative procedures, administrative requirements, and fees as determined under RCW 43.70.250 and 43.70.280.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2062[1996 c 191 § 62]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20420[1994 sp.s. c 9 § 420]; ]

== 18.79.202 - License fee surcharge—Use of proceeds—Nursing resource center account—Report to the legislature—Review—Rules.
. In addition to the licensing fee for registered nurses and licensed practical nurses licensed under this chapter, the department shall impose an additional surcharge of five dollars per year on all initial licenses and renewal licenses for registered nurses and licensed practical nurses issued under this chapter. Advanced registered nurse practitioners are only required to pay the surcharge on their registered nurse licenses.

. The department, in consultation with the commission and the workforce training and education coordinating board, shall use the proceeds from the surcharge imposed under subsection (1) of this section to provide grants to a central nursing resource center. The grants may be awarded only to a not-for-profit central nursing resource center that is comprised of and led by nurses. The central nursing resource center will demonstrate coordination with relevant nursing constituents including professional nursing organizations, groups representing nursing educators, staff nurses, nurse managers or executives, and labor organizations representing nurses. The central nursing resource center shall have as its mission to contribute to the health and wellness of Washington state residents by ensuring that there is an adequate nursing workforce to meet the current and future health care needs of the citizens of the state of Washington. The grants may be used to fund the following activities of the central nursing resource center:

.. Maintain information on the current and projected supply and demand of nurses through the collection and analysis of data regarding the nursing workforce, including but not limited to education level, race and ethnicity, employment settings, nursing positions, reasons for leaving the nursing profession, and those leaving Washington state to practice elsewhere. This data collection and analysis must complement other state activities to produce data on the nursing workforce and the central nursing resource center shall work collaboratively with other entities in the data collection to ensure coordination and avoid duplication of efforts;

.. Monitor and validate trends in the applicant pool for programs in nursing. The central nursing resource center must work with nursing leaders to identify approaches to address issues arising related to the trends identified, and collect information on other states' approaches to addressing these issues;

.. Facilitate partnerships between the nursing community and other health care providers, licensing authority, business and industry, consumers, legislators, and educators to achieve policy consensus, promote diversity within the profession, and enhance nursing career mobility and nursing leadership development;

.. Evaluate the effectiveness of nursing education and articulation among programs to increase access to nursing education and enhance career mobility, especially for populations that are underrepresented in the nursing profession;

.. Provide consultation, technical assistance, data, and information related to Washington state and national nursing resources;

.. Promote strategies to enhance patient safety and quality patient care including encouraging a safe and healthy workplace environment for nurses; and

.. Educate the public including students in K-12 about opportunities and careers in nursing.

. The nursing resource center account is created in the custody of the state treasurer. All receipts from the surcharge in subsection (1) of this section must be deposited in the account. Expenditures from the account may be used only for grants to an organization to conduct the specific activities listed in subsection (2) of this section and to compensate the department for the reasonable costs associated with the collection and distribution of the surcharge and the administration of the grant provided for in subsection (2) of this section. No money from this account may be used by the recipient towards administrative costs of the central nursing resource center not associated with the specific activities listed in subsection (2) of this section. No money from this account may be used by the recipient toward lobbying. Only the secretary or the secretary's designee may authorize expenditures from the account. The account is subject to allotment procedures under chapter 43.88 RCW, but an appropriation is not required for expenditures. Grants will be awarded on an annual basis and funds will be distributed quarterly. The first distribution after awarding the first grant shall be made no later than six months after July 24, 2005. The central nursing resource center shall report to the department on meeting the grant objectives annually.

. The central nursing resource center shall submit a report of all progress, collaboration with other organizations and government entities, and activities conducted by the center to the relevant committees of the legislature by November 30, 2011. The department shall conduct a review of the program to collect funds to support the activities of a nursing resource center and make recommendations on the effectiveness of the program and whether it should continue. The review shall be paid for with funds from the nursing resource center account. The review must be completed by June 30, 2012.

. The department may adopt rules as necessary to implement chapter 268, Laws of 2005.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5599-S.SL.pdf?cite=2005%20c%20268%20§%204[2005 c 268 § 4]; ]

== 18.79.210 - License renewal—Procedures, requirements, fees.
A license issued under this chapter must be renewed, except as provided in this chapter. The licensee shall comply with administrative procedures, administrative requirements, and fees as determined under RCW 43.70.250 and 43.70.280.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2063[1996 c 191 § 63]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20421[1994 sp.s. c 9 § 421]; ]

== 18.79.230 - Temporary retirement—Renewal—Fee—Qualification.
A person licensed under this chapter who desires to retire temporarily from registered nursing practice, advanced registered nursing practice, or licensed practical nursing practice in this state shall send a written notice to the secretary.

Upon receipt of the notice the department shall place the name of the person on inactive status. While remaining on this status the person shall not practice in this state any form of nursing provided for in this chapter. When the person desires to resume practice, the person shall apply to the commission for renewal of the license and pay a renewal fee to the state treasurer. Persons on inactive status for three years or more must provide evidence of knowledge and skill of current practice as required by the commission or as provided in this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20423[1994 sp.s. c 9 § 423]; ]

== 18.79.240 - Construction. (Effective until July 1, 2022.)
. In the context of the definition of registered nursing practice and advanced registered nursing practice, this chapter shall not be construed as:

.. Prohibiting the incidental care of the sick by domestic servants or persons primarily employed as housekeepers, so long as they do not practice registered nursing within the meaning of this chapter;

.. Preventing a person from the domestic administration of family remedies or the furnishing of nursing assistance in case of emergency;

.. Prohibiting the practice of nursing by students enrolled in approved schools as may be incidental to their course of study or prohibiting the students from working as nursing technicians;

.. Prohibiting auxiliary services provided by persons carrying out duties necessary for the support of nursing services, including those duties that involve minor nursing services for persons performed in hospitals, nursing homes, or elsewhere under the direction of licensed physicians or the supervision of licensed registered nurses;

.. Prohibiting the practice of nursing in this state by a legally qualified nurse of another state or territory whose engagement requires him or her to accompany and care for a patient temporarily residing in this state during the period of one such engagement, not to exceed six months in length, if the person does not represent or hold himself or herself out as a registered nurse licensed to practice in this state;

.. Prohibiting nursing or care of the sick, with or without compensation, when done in connection with the practice of the religious tenets of a church by adherents of the church so long as they do not engage in the practice of nursing as defined in this chapter;

.. Prohibiting the practice of a legally qualified nurse of another state who is employed by the United States government or a bureau, division, or agency thereof, while in the discharge of his or her official duties;

.. Permitting the measurement of the powers or range of human vision, or the determination of the accommodation and refractive state of the human eye or the scope of its functions in general, or the fitting or adaptation of lenses for the aid thereof;

.. Permitting the prescribing or directing the use of, or using, an optical device in connection with ocular exercises, visual training, vision training, or orthoptics;

.. Permitting the prescribing of contact lenses for, or the fitting and adaptation of contact lenses to, the human eye;

.. Prohibiting the performance of routine visual screening;

.. Permitting the practice of dentistry or dental hygiene as defined in chapters 18.32 and 18.29 RCW, respectively;

.. Permitting the practice of chiropractic as defined in chapter 18.25 RCW including the adjustment or manipulation of the articulation of the spine;

.. Permitting the practice of podiatric medicine and surgery as defined in chapter 18.22 RCW;

.. Permitting the performance of major surgery, except such minor surgery as the commission may have specifically authorized by rule adopted in accordance with chapter 34.05 RCW;

.. Permitting the prescribing of controlled substances as defined in Schedule I of the Uniform Controlled Substances Act, chapter 69.50 RCW;

.. Prohibiting the determination and pronouncement of death;

.. Prohibiting advanced registered nurse practitioners, approved by the commission as certified registered nurse anesthetists from selecting, ordering, or administering controlled substances as defined in Schedules II through IV of the Uniform Controlled Substances Act, chapter 69.50 RCW, consistent with their commission-recognized scope of practice; subject to facility-specific protocols, and subject to a request for certified registered nurse anesthetist anesthesia services issued by a physician licensed under chapter 18.71 RCW, an osteopathic physician and surgeon licensed under chapter 18.57 RCW, a dentist licensed under chapter 18.32 RCW, or a podiatric physician and surgeon licensed under chapter 18.22 RCW; the authority to select, order, or administer Schedule II through IV controlled substances being limited to those drugs that are to be directly administered to patients who require anesthesia for diagnostic, operative, obstetrical, or therapeutic procedures in a hospital, clinic, ambulatory surgical facility, or the office of a practitioner licensed under chapter 18.71, 18.22, 18.36, 18.36A, 18.57, 18.57A, or 18.32 RCW; "select" meaning the decision-making process of choosing a drug, dosage, route, and time of administration; and "order" meaning the process of directing licensed individuals pursuant to their statutory authority to directly administer a drug or to dispense, deliver, or distribute a drug for the purpose of direct administration to a patient, under instructions of the certified registered nurse anesthetist. "Protocol" means a statement regarding practice and documentation concerning such items as categories of patients, categories of medications, or categories of procedures rather than detailed case-specific formulas for the practice of nurse anesthesia;

.. Prohibiting advanced registered nurse practitioners from ordering or prescribing controlled substances as defined in Schedules II through IV of the Uniform Controlled Substances Act, chapter 69.50 RCW, if and to the extent that doing so is permitted by their scope of practice;

.. Prohibiting the practice of registered nursing or advanced registered nursing by a student enrolled in an approved school if:

... The student performs services without compensation or expectation of compensation as part of a volunteer activity;

... The student is under the direct supervision of a registered nurse or advanced registered nurse practitioner licensed under this chapter, a pharmacist licensed under chapter 18.64 RCW, an osteopathic physician and surgeon licensed under chapter 18.57 RCW, or a physician licensed under chapter 18.71 RCW;

... The services the student performs are within the scope of practice of: (A) The nursing profession for which the student is receiving training; and (B) the person supervising the student;

... The school in which the student is enrolled verifies the student has demonstrated competency through his or her education and training to perform the services; and

.. The student provides proof of current malpractice insurance to the volunteer activity organizer prior to performing any services.

. In the context of the definition of licensed practical nursing practice, this chapter shall not be construed as:

.. Prohibiting the incidental care of the sick by domestic servants or persons primarily employed as housekeepers, so long as they do not practice practical nursing within the meaning of this chapter;

.. Preventing a person from the domestic administration of family remedies or the furnishing of nursing assistance in case of emergency;

.. Prohibiting the practice of practical nursing by students enrolled in approved schools as may be incidental to their course of study or prohibiting the students from working as nursing assistants;

.. Prohibiting auxiliary services provided by persons carrying out duties necessary for the support of nursing services, including those duties that involve minor nursing services for persons performed in hospitals, nursing homes, or elsewhere under the direction of licensed physicians or the supervision of licensed registered nurses;

.. Prohibiting or preventing the practice of nursing in this state by a legally qualified nurse of another state or territory whose engagement requires him or her to accompany and care for a patient temporarily residing in this state during the period of one such engagement, not to exceed six months in length, if the person does not represent or hold himself or herself out as a licensed practical nurse licensed to practice in this state;

.. Prohibiting nursing or care of the sick, with or without compensation, when done in connection with the practice of the religious tenets of a church by adherents of the church so long as they do not engage in licensed practical nurse practice as defined in this chapter;

.. Prohibiting the practice of a legally qualified nurse of another state who is employed by the United States government or any bureau, division, or agency thereof, while in the discharge of his or her official duties.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1726.SL.pdf?cite=2019%20c%20270%20§%204[2019 c 270 § 4]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1479.SL.pdf?cite=2005%20c%2028%20§%201[2005 c 28 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5829-S.SL.pdf?cite=2003%20c%20258%20§%206[2003 c 258 § 6]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5805-S.SL.pdf?cite=2000%20c%2064%20§%203[2000 c 64 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20424[1994 sp.s. c 9 § 424]; ]

== 18.79.250 - Advanced registered nurse practitioner—Activities allowed.
An advanced registered nurse practitioner under his or her license may perform for compensation nursing care, as that term is usually understood, of the ill, injured, or infirm, and in the course thereof, she or he may do the following things that shall not be done by a person not so licensed, except as provided in RCW 18.79.260 and 18.79.270:

. Perform specialized and advanced levels of nursing as recognized jointly by the medical and nursing professions, as defined by the commission;

. Prescribe legend drugs and Schedule V controlled substances, as defined in the Uniform Controlled Substances Act, chapter 69.50 RCW, and Schedules II through IV subject to RCW 18.79.240(1) (r) or (s) within the scope of practice defined by the commission;

. Perform all acts provided in RCW 18.79.260;

. Hold herself or himself out to the public or designate herself or himself as an advanced registered nurse practitioner or as a nurse practitioner.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5805-S.SL.pdf?cite=2000%20c%2064%20§%204[2000 c 64 § 4]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20425[1994 sp.s. c 9 § 425]; ]

== 18.79.256 - Advanced registered nurse practitioner—Scope of practice—Document attestation.
An advanced registered nurse practitioner may sign and attest to any certificates, cards, forms, or other required documentation that a physician may sign, so long as it is within the advanced registered nurse practitioner's scope of practice.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1259.SL.pdf?cite=2015%20c%20104%20§%201[2015 c 104 § 1]; ]

== 18.79.260 - Registered nurse—Activities allowed—Delegation of tasks. (Effective until July 1, 2022.)
. A registered nurse under his or her license may perform for compensation nursing care, as that term is usually understood, to individuals with illnesses, injuries, or disabilities.

. A registered nurse may, at or under the general direction of a licensed physician and surgeon, dentist, osteopathic physician and surgeon, naturopathic physician, optometrist, podiatric physician and surgeon, physician assistant, osteopathic physician assistant, advanced registered nurse practitioner, or midwife acting within the scope of his or her license, administer medications, treatments, tests, and inoculations, whether or not the severing or penetrating of tissues is involved and whether or not a degree of independent judgment and skill is required. Such direction must be for acts which are within the scope of registered nursing practice.

. A registered nurse may delegate tasks of nursing care to other individuals where the registered nurse determines that it is in the best interest of the patient.

.. The delegating nurse shall:

... Determine the competency of the individual to perform the tasks;

... Evaluate the appropriateness of the delegation;

... Supervise the actions of the person performing the delegated task; and

... Delegate only those tasks that are within the registered nurse's scope of practice.

.. A registered nurse, working for a home health or hospice agency regulated under chapter 70.127 RCW, may delegate the application, instillation, or insertion of medications to a registered or certified nursing assistant under a plan of care.

.. Except as authorized in (b) or (e) of this subsection, a registered nurse may not delegate the administration of medications. Except as authorized in (e) of this subsection, a registered nurse may not delegate acts requiring substantial skill, and may not delegate piercing or severing of tissues. Acts that require nursing judgment shall not be delegated.

.. No person may coerce a nurse into compromising patient safety by requiring the nurse to delegate if the nurse determines that it is inappropriate to do so. Nurses shall not be subject to any employer reprisal or disciplinary action by the nursing care quality assurance commission for refusing to delegate tasks or refusing to provide the required training for delegation if the nurse determines delegation may compromise patient safety.

.. For delegation in community-based care settings or in-home care settings, a registered nurse may delegate nursing care tasks only to registered or certified nursing assistants or home care aides certified under chapter 18.88B RCW. Simple care tasks such as blood pressure monitoring, personal care service, diabetic insulin device set up, verbal verification of insulin dosage for sight-impaired individuals, or other tasks as defined by the nursing care quality assurance commission are exempted from this requirement.

... "Community-based care settings" includes: Community residential programs for people with developmental disabilities, certified by the department of social and health services under chapter 71A.12 RCW; adult family homes licensed under chapter 70.128 RCW; and assisted living facilities licensed under chapter 18.20 RCW. Community-based care settings do not include acute care or skilled nursing facilities.

... "In-home care settings" include an individual's place of temporary or permanent residence, but does not include acute care or skilled nursing facilities, and does not include community-based care settings as defined in (e)(i) of this subsection.

... Delegation of nursing care tasks in community-based care settings and in-home care settings is only allowed for individuals who have a stable and predictable condition. "Stable and predictable condition" means a situation in which the individual's clinical and behavioral status is known and does not require the frequent presence and evaluation of a registered nurse.

... The determination of the appropriateness of delegation of a nursing task is at the discretion of the registered nurse. Other than delegation of the administration of insulin by injection for the purpose of caring for individuals with diabetes, the administration of medications by injection, sterile procedures, and central line maintenance may never be delegated.

.. When delegating insulin injections under this section, the registered nurse delegator must instruct the individual regarding proper injection procedures and the use of insulin, demonstrate proper injection procedures, and must supervise and evaluate the individual performing the delegated task weekly during the first four weeks of delegation of insulin injections. If the registered nurse delegator determines that the individual is competent to perform the injection properly and safely, supervision and evaluation shall occur at least every ninety days thereafter.

..(A) The registered nurse shall verify that the nursing assistant or home care aide, as the case may be, has completed the required core nurse delegation training required in chapter 18.88A or 18.88B RCW prior to authorizing delegation.

(B) Before commencing any specific nursing tasks authorized to be delegated in this section, a home care aide must be certified pursuant to chapter 18.88B RCW and must comply with RCW 18.88B.070.

.. The nurse is accountable for his or her own individual actions in the delegation process. Nurses acting within the protocols of their delegation authority are immune from liability for any action performed in the course of their delegation duties.

.. Nursing task delegation protocols are not intended to regulate the settings in which delegation may occur, but are intended to ensure that nursing care services have a consistent standard of practice upon which the public and the profession may rely, and to safeguard the authority of the nurse to make independent professional decisions regarding the delegation of a task.

.. The nursing care quality assurance commission may adopt rules to implement this section.

. Only a person licensed as a registered nurse may instruct nurses in technical subjects pertaining to nursing.

. Only a person licensed as a registered nurse may hold herself or himself out to the public or designate herself or himself as a registered nurse.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2314-S.SL.pdf?cite=2012%20c%20164%20§%20407[2012 c 164 § 407]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2186.SL.pdf?cite=2012%20c%2013%20§%203[2012 c 13 § 3]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2056-S.SL.pdf?cite=2012%20c%2010%20§%2037[2012 c 10 § 37]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1397-S.SL.pdf?cite=2009%20c%20203%20§%201[2009 c 203 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2668-S2.SL.pdf?cite=2008%20c%20146%20§%2011[2008 c 146 § 11]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1753.SL.pdf?cite=2003%20c%20140%20§%202[2003 c 140 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1218-S.SL.pdf?cite=2000%20c%2095%20§%203[2000 c 95 § 3]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1908-S2.SL.pdf?cite=1995%201st%20sp.s.%20c%2018%20§%2051[1995 1st sp.s. c 18 § 51]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1809-S.SL.pdf?cite=1995%20c%20295%20§%201[1995 c 295 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20426[1994 sp.s. c 9 § 426]; ]

== 18.79.270 - Licensed practical nurse—Activities allowed. (Effective until July 1, 2022.)
A licensed practical nurse under his or her license may perform nursing care, as that term is usually understood, of the ill, injured, or infirm, and in the course thereof may, under the direction of a licensed physician and surgeon, osteopathic physician and surgeon, dentist, naturopathic physician, podiatric physician and surgeon, physician assistant, osteopathic physician assistant, advanced registered nurse practitioner, or midwife acting under the scope of his or her license, or at the direction and under the supervision of a registered nurse, administer drugs, medications, treatments, tests, injections, and inoculations, whether or not the piercing of tissues is involved and whether or not a degree of independent judgment and skill is required, when selected to do so by one of the licensed practitioners designated in this section, or by a registered nurse who need not be physically present; if the order given is reduced to writing within a reasonable time and made a part of the patient's record. Such direction must be for acts within the scope of licensed practical nurse practice.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2186.SL.pdf?cite=2012%20c%2013%20§%204[2012 c 13 § 4]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1809-S.SL.pdf?cite=1995%20c%20295%20§%202[1995 c 295 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20427[1994 sp.s. c 9 § 427]; ]

== 18.79.280 - Medication, tests, treatments allowed.
It is not a violation of chapter 18.71 RCW or of chapter 18.57 RCW for a registered nurse, at or under the general direction of a licensed physician and surgeon, or osteopathic physician and surgeon, to administer prescribed drugs, injections, inoculations, tests, or treatment whether or not the piercing of tissues is involved.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20428[1994 sp.s. c 9 § 428]; ]

== 18.79.290 - Catheterization of students—Rules.
. In accordance with rules adopted by the commission, public school districts and private schools that offer classes for any of grades kindergarten through twelve may provide for clean, intermittent bladder catheterization of students or assisted self-catheterization of students who are in the custody of the school district or private school at the time. After consultation with staff of the superintendent of public instruction, the commission shall adopt rules in accordance with chapter 34.05 RCW, that provide for the following and such other matters as the commission deems necessary to the proper implementation of this section:

.. A requirement for a written, current, and unexpired request from a parent, legal guardian, or other person having legal control over the student that the school district or private school provide for the catheterization of the student;

.. A requirement for a written, current, and unexpired request from a physician licensed under chapter 18.71 or 18.57 RCW, that catheterization of the student be provided for during the hours when school is in session or the hours when the student is under the supervision of school officials;

.. A requirement for written, current, and unexpired instructions from an advanced registered nurse practitioner or a registered nurse licensed under this chapter regarding catheterization that include (i) a designation of the school district or private school employee or employees who may provide for the catheterization, and (ii) a description of the nature and extent of any required supervision; and

.. The nature and extent of acceptable training that shall (i) be provided by a physician, advanced registered nurse practitioner, or registered nurse licensed under chapter 18.71 or 18.57 RCW, or this chapter, and (ii) be required of school district or private school employees who provide for the catheterization of a student under this section, except that a licensed practical nurse licensed under this chapter is exempt from training.

. This section does not require school districts to provide intermittent bladder catheterization of students.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20429[1994 sp.s. c 9 § 429]; ]

== 18.79.300 - Department—Rules for administration.
The department, subject to chapter 34.05 RCW, the Washington Administrative Procedure Act, may adopt such reasonable rules as may be necessary to carry out the duties imposed upon it in the administration of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20430[1994 sp.s. c 9 § 430]; ]

== 18.79.310 - Rules, regulations, decisions of previous boards—Effect.
As of July 1, 1994, all rules, regulations, decisions, and orders of the board of nursing under *chapter 18.88 RCW or the board of practical nursing under *chapter 18.78 RCW continue to be in effect under the commission, until the commission acts to modify the rules, regulations, decisions, or orders.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20431[1994 sp.s. c 9 § 431]; ]

== 18.79.330 - Finding.
The legislature finds a need to provide additional work-related opportunities for nursing students. Nursing students enrolled in bachelor of science programs or associate degree programs, working within the limits of their education, gain valuable judgment and knowledge through expanded work opportunities.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5829-S.SL.pdf?cite=2003%20c%20258%20§%201[2003 c 258 § 1]; ]

== 18.79.340 - Nursing technicians.
. "Nursing technician" means a nursing student employed in a hospital licensed under chapter 70.41 RCW, a clinic, or a nursing home licensed under chapter 18.51 RCW, who:

.. Is currently enrolled in good standing in a nursing program approved by the commission and has not graduated; or

.. Is a graduate of a nursing program approved by the commission who graduated:

... Within the past thirty days; or

... Within the past sixty days and has received a determination from the secretary that there is good cause to continue the registration period, as defined by the secretary in rule.

. No person may practice or represent oneself as a nursing technician by use of any title or description of services without being registered under this chapter, unless otherwise exempted by this chapter.

. The commission may adopt rules to implement chapter 258, Laws of 2003.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6237-S.SL.pdf?cite=2012%20c%20153%20§%2013[2012 c 153 § 13]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5829-S.SL.pdf?cite=2003%20c%20258%20§%202[2003 c 258 § 2]; ]

== 18.79.350 - Nursing technicians—Nursing functions.
. Nursing technicians are authorized to perform specific nursing functions within the limits of their education, up to their skill and knowledge, but they may not:

.. Administer chemotherapy, blood or blood products, intravenous medications, or scheduled drugs, or carry out procedures on central lines;

.. Assume ongoing responsibility for assessments, planning, implementation, or evaluation of the care of patients;

.. Function independently, act as a supervisor, or delegate tasks to licensed practical nurses, nursing assistants, or unlicensed personnel; or

.. Perform or attempt to perform nursing techniques or procedures for which the nursing technician lacks the appropriate knowledge, experience, and education.

. Nursing technicians may function only under the direct supervision of a registered nurse who agrees to act as supervisor and is immediately available to the nursing technician. The supervising registered nurse must have an unrestricted license with at least two years of clinical practice in the setting where the nursing technician works.

. Nursing technicians may only perform specific nursing functions based upon and limited to their education and when they have demonstrated the ability and been verified to safely perform these functions by the nursing program in which the nurse technician is enrolled. The nursing program providing verification is immune from liability for any nursing function performed or not performed by the nursing technician.

. Nursing technicians are responsible and accountable for their specific nursing functions.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5829-S.SL.pdf?cite=2003%20c%20258%20§%203[2003 c 258 § 3]; ]

== 18.79.360 - Applications for registration as a nursing technician—Fee.
. Applications for registration must be submitted on forms provided by the secretary. The secretary may require any information and documentation that reasonably relates to the need to determine whether the applicant meets the criteria for registration provided for in chapter 18.130 RCW. Each applicant shall pay a fee determined by the secretary under RCW 43.70.250. The fee must accompany the application.

. An applicant for registration as a nursing technician shall submit:

.. A signed statement from the applicant's nursing program verifying enrollment in, or graduation from, the nursing program; and

.. A signed statement from the applicant's employer certifying that the employer understands the role of the nursing technician and agrees to meet the requirements of subsection (4) of this section.

. The secretary shall issue a registration to an applicant who has met the requirements for registration or deny a registration to an applicant who does not meet the requirements, except that proceedings concerning the denial of registration based on unprofessional conduct or impairment are governed by the uniform disciplinary act, chapter 18.130 RCW.

. The employer:

.. Shall not require the nursing technician to work beyond his or her education and training;

.. Shall verify that the nursing technician continues to qualify as a nursing technician as described in RCW 18.79.340;

.. Shall advise the department and nursing program of any practice-related action taken against the nursing technician;

.. Shall maintain documentation of the specific nursing functions the nursing technician is authorized to perform; and

.. Shall provide training regarding the provisions of chapter 258, Laws of 2003, including procedures for filing a complaint with the department of health or the department of social and health services concerning violations of chapter 258, Laws of 2003, to all nursing technicians and registered nurses who shall supervise nursing technicians and document the training and make it available for any inspection or survey.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5829-S.SL.pdf?cite=2003%20c%20258%20§%204[2003 c 258 § 4]; ]

== 18.79.370 - Nursing technicians—Registration renewal.
The secretary shall establish by rule the procedural requirements and fees for renewal of the registration. Failure to renew invalidates the registration and all privileges granted by the registration. For renewal of registration, a nursing technician must attest that he or she continues to qualify as a nursing technician as described in RCW 18.79.340.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5829-S.SL.pdf?cite=2003%20c%20258%20§%205[2003 c 258 § 5]; ]

== 18.79.390 - Secretary and commission relationship.
. The secretary shall employ an executive director that is:

.. Hired by and serves at the pleasure of the commission;

.. Exempt from the provisions of the civil service law, chapter 41.06 RCW and whose salary is established by the commission in accordance with RCW 43.03.028; and

.. Responsible for performing all administrative duties of the commission, including preparing an annual budget, and any other duties as delegated to the executive director by the commission.

. Consistent with the budgeting and accounting act, the commission is responsible for proposing its own biennial budget which the secretary must submit to the office of financial management.

. Prior to adopting credentialing fees under RCW 43.70.250, the secretary shall collaborate with the commission to determine the appropriate fees necessary to support the activities of the commission.

. Prior to the secretary exercising the secretary's authority to adopt uniform rules and guidelines, or any other actions that might impact the licensing or disciplinary authority of the commission, the secretary shall first meet with the commission to determine how those rules or guidelines, or changes to rules or guidelines, might impact the commission's ability to effectively carry out its statutory duties. If the commission, in consultation with the secretary, determines that the proposed rules or guidelines, or changes to existing rules or guidelines, will negatively impact the commission's ability to effectively carry out its statutory duties, then the individual commission shall collaborate with the secretary to develop alternative solutions to mitigate the impacts. If an alternative solution cannot be reached, the parties may resolve the dispute through a mediator as set forth in subsection (6) of this section.

. The commission shall negotiate with the secretary to develop performance-based expectations, including identification of key performance measures. The performance expectations should focus on consistent, timely regulation of health care professionals.

. In the event there is a disagreement between the commission and the secretary, that is unable to be resolved through negotiation, a representative of both parties shall agree on the designation of a third party to mediate the dispute.

. The secretary shall employ staff that are hired and managed by the executive director provided that nothing contained in this section may be construed to alter any existing collective bargaining unit or the provisions of any existing collective bargaining agreement.

. By December 31, 2013, the commission must present a report with recommendations to the governor and the legislature regarding:

.. Evidence-based practices and research-based practices used by boards of nursing when conducting licensing, educational, disciplinary, and financial activities and the use of such practices by the commission; and

.. A comparison of the commission's licensing, education, disciplinary, and financial outcomes with those of other boards of nursing using a national database.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1518-S2.SL.pdf?cite=2013%20c%2081%20§%205[2013 c 81 § 5]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1048-S.SL.pdf?cite=2011%20c%2060%20§%208[2011 c 60 § 8]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1103-S4.SL.pdf?cite=2008%20c%20134%20§%2030[2008 c 134 § 30]; ]

== 18.79.400 - Pain management rules—Criteria for new rules.
. By June 30, 2011, the commission shall adopt new rules on chronic, noncancer pain management that contain the following elements:

.. [Empty]
... Dosing criteria, including:

(A) A dosage amount that must not be exceeded unless an advanced registered nurse practitioner or certified registered nurse anesthetist first consults with a practitioner specializing in pain management; and

(B) Exigent or special circumstances under which the dosage amount may be exceeded without consultation with a practitioner specializing in pain management.

... The rules regarding consultation with a practitioner specializing in pain management must, to the extent practicable, take into account:

(A) Circumstances under which repeated consultations would not be necessary or appropriate for a patient undergoing a stable, ongoing course of treatment for pain management;

(B) Minimum training and experience that is sufficient to exempt an advanced registered nurse practitioner or certified registered nurse anesthetist from the specialty consultation requirement;

(C) Methods for enhancing the availability of consultations;

(D) Allowing the efficient use of resources; and

(E) Minimizing the burden on practitioners and patients;

.. Guidance on when to seek specialty consultation and ways in which electronic specialty consultations may be sought;

.. Guidance on tracking clinical progress by using assessment tools focusing on pain interference, physical function, and overall risk for poor outcome; and

.. Guidance on tracking the use of opioids, particularly in the emergency department.

. The commission shall consult with the agency medical directors' group, the department of health, the University of Washington, and the largest professional associations for advanced registered nurse practitioners and certified registered nurse anesthetists in the state.

. The rules adopted under this section do not apply:

.. To the provision of palliative, hospice, or other end-of-life care; or

.. To the management of acute pain caused by an injury or a surgical procedure.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2876-S.SL.pdf?cite=2010%20c%20209%20§%207[2010 c 209 § 7]; ]

== 18.79.410 - Commission—Information to legislature.
In addition to the authority provided in RCW 42.52.804, the commission, its members, or staff as directed by the commission, may communicate, present information requested, volunteer information, testify before legislative committees, and educate the legislature, as the commission may from time to time see fit.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1518-S2.SL.pdf?cite=2013%20c%2081%20§%206[2013 c 81 § 6]; ]

== 18.79.420 - Down syndrome—Parent information.
A nurse who provides a parent with a positive prenatal or postnatal diagnosis of Down syndrome shall provide the parent with the information prepared by the department under RCW 43.70.738 at the time the nurse provides the parent with the Down syndrome diagnosis.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2403.SL.pdf?cite=2016%20c%2070%20§%207[2016 c 70 § 7]; ]

== 18.79.800 - Opioid drug prescribing rules—Adoption.
. By January 1, 2019, the commission must adopt rules establishing requirements for prescribing opioid drugs. The rules may contain exemptions based on education, training, amount of opioids prescribed, patient panel, and practice environment.

. In developing the rules, the commission must consider the agency medical directors' group and centers for disease control guidelines, and may consult with the department of health, the University of Washington, and the largest professional associations for advanced registered nurse practitioners and certified registered nurse anesthetists in the state.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1427-S.SL.pdf?cite=2017%20c%20297%20§%208[2017 c 297 § 8]; ]

== 18.79.810 - Opioid drugs—Right to refuse.
By January 1, 2020, the commission must adopt or amend its rules to require advanced registered nurse practitioners who prescribe opioids to inform patients of their right to refuse an opioid prescription or order for any reason. If a patient indicates a desire to not receive an opioid, the advanced registered nurse practitioner must document the patient's request and avoid prescribing or ordering opioids, unless the request is revoked by the patient.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5380-S.SL.pdf?cite=2019%20c%20314%20§%2010[2019 c 314 § 10]; ]

== 18.79.900 - Severability—1994 sp.s. c 9.
If any provision of this act or its application to any person or circumstance is held invalid, the remainder of the act or the application of the provision to other persons or circumstances is not affected.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20904[1994 sp.s. c 9 § 904]; ]

== 18.79.901 - Headings and captions not law—1994 sp.s. c 9.
Headings and captions used in this act constitute no part of the law.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20905[1994 sp.s. c 9 § 905]; ]

== 18.79.902 - Effective date—1994 sp.s. c 9.
This act takes effect July 1, 1994.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20906[1994 sp.s. c 9 § 906]; ]

