= 18.32 - Dentistry.
:toc:

== 18.32.002 - Findings—Purpose.
The legislature finds that the health and well-being of the people of this state are of paramount importance.

The legislature further finds that the conduct of members of the dental profession licensed to practice dentistry in this state plays a vital role in preserving the health and well-being of the people of the state.

The legislature further finds that requiring continuing dental education for all licensed dentists in the state is an important component of providing high quality dentistry for the people of this state.

The legislature further finds that there is no effective means of handling disciplinary proceedings against members of the dental profession licensed in this state when such proceedings are necessary for the protection of the public health.

Therefore, the legislature declares its intention to exercise the police power of the state to protect the public health, to promote the welfare of the state, and to provide a commission to act as a disciplinary and regulatory body for the members of the dental profession licensed to practice dentistry in this state.

It is the purpose of the commission established in RCW 18.32.0351 to regulate the competency and quality of professional health care providers under its jurisdiction by establishing, monitoring, and enforcing qualifications for licensure, continuing education, consistent standards of practice, continuing competency mechanisms, and discipline. Rules, policies, and procedures developed by the commission must promote the delivery of quality health care to the residents of the state.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1699.SL.pdf?cite=1999%20c%20364%20§%201[1999 c 364 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20201[1994 sp.s. c 9 § 201]; ]

== 18.32.005 - Regulation of health care professions—Criteria.
See chapter 18.120 RCW.

[ ]

== 18.32.010 - Words defined.
Words used in the singular in this chapter may also be applied to the plural of the persons and things; words importing the plural may be applied to the singular; words importing the masculine gender may be extended to females also; the term "commission" used in this chapter shall mean the Washington state dental quality assurance commission; and the term "secretary" shall mean the secretary of health of the state of Washington.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20202[1994 sp.s. c 9 § 202]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2058[1991 c 3 § 58]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c112.pdf?cite=1935%20c%20112%20§%201[1935 c 112 § 1]; RRS § 10031-1; ]

== 18.32.020 - Practice of dentistry defined.
A person practices dentistry, within the meaning of this chapter, who (1) represents himself or herself as being able to diagnose, treat, remove stains and concretions from teeth, operate or prescribe for any disease, pain, injury, deficiency, deformity, or physical condition of the human teeth, alveolar process, gums, or jaw, or (2) offers or undertakes by any means or methods to diagnose, treat, remove stains or concretions from teeth, operate or prescribe for any disease, pain, injury, deficiency, deformity, or physical condition of the same, or take impressions of the teeth or jaw, or (3) owns, maintains, or operates an office for the practice of dentistry, or (4) engages in any of the practices included in the curricula of recognized and approved dental schools or colleges, or (5) professes to the public by any method to furnish, supply, construct, reproduce, or repair any prosthetic denture, bridge, appliance, or other structure to be worn in the human mouth.

The fact that a person uses any dental degree, or designation, or any card, device, directory, poster, sign, or other media whereby he or she represents himself or herself to be a dentist, shall be prima facie evidence that such person is engaged in the practice of dentistry.

X-ray diagnosis as to the method of dental practice in which the diagnosis and examination is made of the normal and abnormal structures, parts, or functions of the human teeth, the alveolar process, maxilla, mandible or soft tissues adjacent thereto, is hereby declared to be the practice of dentistry. Any person other than a regularly licensed physician or surgeon who makes any diagnosis or interpretation or explanation, or attempts to diagnose or to make any interpretation or explanation of the registered shadow or shadows of any part of the human teeth, alveolar process, maxilla, mandible or soft tissues adjacent thereto by the use of X-ray is declared to be engaged in the practice of dentistry, medicine, or surgery.

The practice of dentistry includes the performance of any dental or oral and maxillofacial surgery. "Oral and maxillofacial surgery" means the specialty of dentistry that includes the diagnosis and surgical and adjunctive treatment of diseases, injuries, and defects of the hard and soft tissues of the oral and maxillofacial region.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20477[2011 c 336 § 477]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2689-S.SL.pdf?cite=1996%20c%20259%20§%201[1996 c 259 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c98.pdf?cite=1957%20c%2098%20§%201[1957 c 98 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c52.pdf?cite=1957%20c%2052%20§%2020[1957 c 52 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c112.pdf?cite=1935%20c%20112%20§%206[1935 c 112 § 6]; RRS § 10031-6.   1943 c 240 § 1; Rem. Supp. 1943 § 10031-6a; ]

== 18.32.030 - Exemptions from chapter.
The following practices, acts, and operations are excepted from the operation of the provisions of this chapter:

. The rendering of dental relief in emergency cases in the practice of his or her profession by a physician or surgeon, licensed as such and registered under the laws of this state, unless the physician or surgeon undertakes to or does reproduce lost parts of the human teeth in the mouth or to restore or to replace in the human mouth lost or missing teeth;

. The practice of dentistry in the discharge of official duties by dentists in the United States federal services on federal reservations, including but not limited to the armed services, coast guard, public health service, veterans' bureau, or bureau of Indian affairs;

. Dental schools or colleges approved under RCW 18.32.040, and the practice of dentistry by students in accredited dental schools or colleges approved by the commission, when acting under the direction and supervision of Washington state-licensed dental school faculty;

. The practice of dentistry by licensed dentists of other states or countries while appearing as clinicians at meetings of the Washington state dental association, or component parts thereof, or at meetings sanctioned by them, or other groups approved by the commission;

. The use of roentgen and other rays for making radiographs or similar records of dental or oral tissues, under the supervision of a licensed dentist or physician;

. The making, repairing, altering, or supplying of artificial restorations, substitutions, appliances, or materials for the correction of disease, loss, deformity, malposition, dislocation, fracture, injury to the jaws, teeth, lips, gums, cheeks, palate, or associated tissues or parts; providing the same are made, repaired, altered, or supplied pursuant to the written instructions and order of a licensed dentist which may be accompanied by casts, models, or impressions furnished by the dentist, and the prescriptions shall be retained and filed for a period of not less than three years and shall be available to and subject to the examination of the secretary or the secretary's authorized representatives;

. The removal of deposits and stains from the surfaces of the teeth, the application of topical preventative or prophylactic agents, and the polishing and smoothing of restorations, when performed or prescribed by a dental hygienist licensed under the laws of this state;

. A qualified and licensed physician and surgeon or osteopathic physician and surgeon extracting teeth or performing oral surgery pursuant to the scope of practice under chapter 18.71 or 18.57 RCW;

. The performing of dental operations or services by registered dental assistants and licensed expanded function dental auxiliaries holding a credential issued under chapter 18.260 RCW when performed under the supervision of a licensed dentist, or by other persons not licensed under this chapter if the person is licensed pursuant to chapter 18.29, 18.57, 18.71, or 18.79 RCW as it applies to registered nurses and advanced registered nurse practitioners, each while acting within the scope of the person's permitted practice under the person's license: PROVIDED HOWEVER, That such persons shall in no event perform the following dental operations or services unless permitted to be performed by the person under this chapter or chapters 18.29, 18.57, 18.71, 18.79 as it applies to registered nurses and advanced registered nurse practitioners, and 18.260 RCW:

.. Any removal of or addition to the hard or soft tissue of the oral cavity;

.. Any diagnosis of or prescription for treatment of disease, pain, deformity, deficiency, injury, or physical condition of the human teeth or jaws, or adjacent structure;

.. Any administration of general or injected local anaesthetic of any nature in connection with a dental operation, including intravenous sedation;

.. Any oral prophylaxis;

.. The taking of any impressions of the teeth or jaw or the relationships of the teeth or jaws, for the purpose of fabricating any intra-oral restoration, appliance, or prosthesis;

. The performing of dental services described in RCW 18.350.040 by dental anesthesia assistants certified under chapter 18.350 RCW when working under the supervision and direction of an oral and maxillofacial surgeon or dental anesthesiologist; and

. The performance of dental health aide therapist services to the extent authorized under chapter 70.350 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5079-S.SL.pdf?cite=2017%20c%205%20§%205[2017 c 5 § 5]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5620-S2.SL.pdf?cite=2012%20c%2023%20§%207[2012 c 23 § 7]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1099-S.SL.pdf?cite=2007%20c%20269%20§%2015[2007 c 269 § 15]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1721-S.SL.pdf?cite=2003%20c%20282%20§%201[2003 c 282 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20203[1994 sp.s. c 9 § 203]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2059[1991 c 3 § 59]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c202.pdf?cite=1989%20c%20202%20§%2013[1989 c 202 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c158.pdf?cite=1979%20c%20158%20§%2035[1979 c 158 § 35]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c236.pdf?cite=1971%20ex.s.%20c%20236%20§%201[1971 ex.s. c 236 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c47.pdf?cite=1969%20c%2047%20§%207[1969 c 47 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c52.pdf?cite=1957%20c%2052%20§%2021[1957 c 52 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c93.pdf?cite=1953%20c%2093%20§%201[1953 c 93 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c130.pdf?cite=1951%20c%20130%20§%201[1951 c 130 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c92.pdf?cite=1941%20c%2092%20§%203[1941 c 92 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c112.pdf?cite=1935%20c%20112%20§%2025[1935 c 112 § 25]; Rem. Supp. 1941 § 10031-25; prior:  1923 c 16 § 23.   1935 c 112 § 6; RRS § 10031-6; prior:  1923 c 16 § 1; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1901c152.pdf?cite=1901%20c%20152%20§%205[1901 c 152 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c55.pdf?cite=1893%20c%2055%20§%2011[1893 c 55 § 11]; ]

== 18.32.0351 - Commission established—Membership.
The Washington state dental quality assurance commission is established, consisting of sixteen members each appointed by the governor to a four-year term. No member may serve more than two consecutive full terms. In appointing the initial members of the commission, it is the intent of the legislature that, to the extent possible, members of the previous boards and committees regulating these professions be appointed to the commission. Members of the commission hold office until their successors are appointed. The governor may appoint members of the initial commission to staggered terms of from one to four years. Thereafter, all members shall be appointed to full four-year terms. Twelve members of the commission must be dentists, two members must be expanded function dental auxiliaries licensed under chapter 18.260 RCW, and two members must be public members.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1099-S.SL.pdf?cite=2007%20c%20269%20§%2016[2007 c 269 § 16]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20204[1994 sp.s. c 9 § 204]; ]

== 18.32.0353 - Commission—Removal of member—Order of removal—Vacancy.
The governor may remove a member of the commission for neglect of duty, misconduct, or malfeasance or misfeasance in office. Whenever the governor is satisfied that a member of the commission has been guilty of neglect of duty, misconduct, or malfeasance or misfeasance in office, the governor shall file with the secretary of state a statement of the causes for and the order of removal from office, and the secretary shall forthwith send a certified copy of the order of removal and statement of causes by certified mail to the last known post office address of the member. If a vacancy occurs on the commission, the governor shall appoint a replacement to fill the remainder of the unexpired term.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20205[1994 sp.s. c 9 § 205]; ]

== 18.32.0355 - Commission—Qualifications of members.
Members must be citizens of the United States and residents of this state. Dentist members must be licensed dentists in the active practice of dentistry for a period of five years before appointment. Of the twelve dentists appointed to the commission, at least four must reside and engage in the active practice of dentistry east of the summit of the Cascade mountain range. Public members of the commission may not be a member of any other health care licensing board or commission, or have a fiduciary obligation to a facility rendering health services regulated by the commission, or have a material or financial interest in the rendering of health services regulated by the commission.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20206[1994 sp.s. c 9 § 206]; ]

== 18.32.0357 - Commission—Duties and powers—Attorney general to advise, represent.
The commission shall elect officers each year. Meetings of the commission are open to the public, except the commission may hold executive sessions to the extent permitted by chapter 42.30 RCW. The secretary of health shall furnish such secretarial, clerical, and other assistance as the commission may require.

A majority of the commission members appointed and serving constitutes a quorum for the transaction of commission business. The affirmative vote of a majority of a quorum of the commission is required to carry a motion or resolution, to adopt a rule, or to pass a measure.

The commission may appoint members of panels consisting of not less than three members. A quorum for transaction of any business shall be a minimum of three members. A majority vote of a quorum of the panel is required to transact business delegated to it by the commission.

The members of the commission are immune from suit in an action, civil or criminal, based upon its disciplinary proceedings or other official acts performed in good faith as members of the commission.

The commission may, whenever the workload of the commission requires, request that the secretary appoint pro tempore members. While serving as members pro tempore persons have all the powers, duties, and immunities, and are entitled to the emoluments, including travel expenses, of the commission.

The commission shall prepare or determine the nature of the examinations for applicants to practice dentistry.

The commission shall establish continuing dental education requirements.

The attorney general shall advise the commission and represent it in all legal proceedings.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1699.SL.pdf?cite=1999%20c%20364%20§%202[1999 c 364 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20207[1994 sp.s. c 9 § 207]; ]

== 18.32.0358 - Commission successor to other boards.
The commission is the successor in interest of the board of dental examiners and the dental disciplinary board. All contracts, undertakings, agreements, rules, regulations, and policies continue in full force and effect on July 1, 1994, unless otherwise repealed or rejected by chapter 9, Laws of 1994 sp. sess. or by the commission.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20226[1994 sp.s. c 9 § 226]; ]

== 18.32.0361 - Compensation of commission members.
Each member of the commission shall be compensated in accordance with RCW 43.03.265. Members shall be reimbursed for travel expenses incurred in the actual performance of their duties, as provided in RCW 43.03.050 and 43.03.060. Commission members shall be compensated and reimbursed for their activities in developing or administering a multistate licensing examination, as provided in this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1863.SL.pdf?cite=1999%20c%20366%20§%203[1999 c 366 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20208[1994 sp.s. c 9 § 208]; ]

== 18.32.0363 - Examinations—Contracts for administration—Multistate.
The commission may contract with competent persons on a temporary basis to assist in developing or administering examinations for licensure.

The commission may enter into compacts and agreements with other states and with organizations formed by several states, for the purpose of conducting multistate licensing examinations. The commission may enter into the compacts and agreements even though they would result in the examination of a candidate for a license in this state by an examiner or examiners from another state or states, and even though the compacts and agreements would result in the examination of a candidate or candidates for a license in another state or states by an examiner or examiners from this state.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20209[1994 sp.s. c 9 § 209]; ]

== 18.32.0365 - Rules.
The commission may adopt rules in accordance with chapter 34.05 RCW to implement this chapter and chapter 18.130 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20210[1994 sp.s. c 9 § 210]; ]

== 18.32.039 - Application of uniform disciplinary act.
The uniform disciplinary act, chapter 18.130 RCW, governs unlicensed practice, the issuance and denial of licenses, and the discipline of licensees under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c150.pdf?cite=1987%20c%20150%20§%2017[1987 c 150 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c259.pdf?cite=1986%20c%20259%20§%2034[1986 c 259 § 34]; ]

== 18.32.040 - Requirements for licensure.
The commission shall require that every applicant for a license to practice dentistry shall:

. Present satisfactory evidence of graduation from a dental college, school, or dental department of an institution approved by the commission;

. Submit, for the files of the commission, a recent picture duly identified and attested; and

. [Empty]
.. Pass an examination prepared or approved by and administered under the direction of the commission. The dentistry licensing examination shall consist of practical and written tests upon such subjects and of such scope as the commission determines. The commission shall set the standards for passing the examination. The secretary shall keep on file the examination papers and records of examination for at least one year. This file shall be open for inspection by the applicant or the applicant's agent unless the disclosure will compromise the examination process as determined by the commission or is exempted from disclosure under chapter 42.56 RCW.

.. The commission may accept, in lieu of all or part of the written examination required in (a) of this subsection, a certificate granted by a national or regional testing organization approved by the commission.

.. The commission shall accept, in lieu of the practical examination required in (a) of this subsection, proof that an applicant has satisfactorily completed a general practice residency, pediatric residency, or advanced education in general dentistry residency program in Washington state accredited by the commission on dental accreditation of the American dental association, of at least one year's duration, in a residency program that serves predominantly low-income patients.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1411-S.SL.pdf?cite=2017%20c%20100%20§%201[2017 c 100 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1689-S.SL.pdf?cite=2005%20c%20454%20§%202[2005 c 454 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1133-S.SL.pdf?cite=2005%20c%20274%20§%20222[2005 c 274 § 222]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20211[1994 sp.s. c 9 § 211]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2061[1991 c 3 § 61]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c202.pdf?cite=1989%20c%20202%20§%2016[1989 c 202 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c38.pdf?cite=1979%20c%2038%20§%202[1979 c 38 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c112.pdf?cite=1935%20c%20112%20§%205[1935 c 112 § 5]; RRS § 10031-5; prior: 1923 c 16 §§ 4, 5; ]

== 18.32.050 - Compensation and reimbursement for administering examination.
Commission members shall be compensated and reimbursed pursuant to this section for their activities in administering a multi-state licensing examination pursuant to the commission's compact or agreement with another state or states or with organizations formed by several states.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5308-S.SL.pdf?cite=1995%20c%20198%20§%202[1995 c 198 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20212[1994 sp.s. c 9 § 212]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c287.pdf?cite=1984%20c%20287%20§%2030[1984 c 287 § 30]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c38.pdf?cite=1979%20c%2038%20§%203[1979 c 38 § 3]; 1975-'76 2nd ex.s. c 34 § 34; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c188.pdf?cite=1967%20c%20188%20§%202[1967 c 188 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c52.pdf?cite=1957%20c%2052%20§%2023[1957 c 52 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c93.pdf?cite=1953%20c%2093%20§%203[1953 c 93 § 3]; 1935 c 112 § 11, part; RRS § 10031-11, part; ]

== 18.32.091 - License required.
No person, unless previously licensed to practice dentistry in this state, shall begin the practice of dentistry in this state without first applying to, and obtaining a license.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5322-S.SL.pdf?cite=2017%20c%20320%20§%205[2017 c 320 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c150.pdf?cite=1987%20c%20150%20§%2018[1987 c 150 § 18]; ]

== 18.32.100 - Applications.
The applicant for a dentistry license shall file an application on a form furnished by the secretary, stating the applicant's name, age, place of residence, the name of the school or schools attended by the applicant, the period of such attendance, the date of the applicant's graduation, whether the applicant has ever been the subject of any disciplinary action related to the practice of dentistry, and shall include a statement of all of the applicant's dental activities. This shall include any other information deemed necessary by the commission.

The application shall be signed by the applicant and shall be accompanied by proof of the applicant's school attendance and graduation.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5810-S.SL.pdf?cite=2015%20c%2072%20§%208[2015 c 72 § 8]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20213[1994 sp.s. c 9 § 213]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2062[1991 c 3 § 62]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c202.pdf?cite=1989%20c%20202%20§%2018[1989 c 202 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c52.pdf?cite=1957%20c%2052%20§%2028[1957 c 52 § 28]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c93.pdf?cite=1953%20c%2093%20§%204[1953 c 93 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c130.pdf?cite=1951%20c%20130%20§%202[1951 c 130 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c92.pdf?cite=1941%20c%2092%20§%202[1941 c 92 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c112.pdf?cite=1935%20c%20112%20§%204[1935 c 112 § 4]; Rem. Supp. 1941 § 10031-4, part; 1923 c 16 §§ 2, 3, 6, 7; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1901c152.pdf?cite=1901%20c%20152%20§%201[1901 c 152 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c55.pdf?cite=1893%20c%2055%20§%204[1893 c 55 § 4]; ]

== 18.32.110 - Application fee.
Each applicant shall pay a fee determined by the secretary as provided in RCW 43.70.250 and 43.70.280.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2014[1996 c 191 § 14]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2063[1991 c 3 § 63]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c202.pdf?cite=1989%20c%20202%20§%2019[1989 c 202 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%2023[1985 c 7 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c30.pdf?cite=1975%201st%20ex.s.%20c%2030%20§%2027[1975 1st ex.s. c 30 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c49.pdf?cite=1969%20c%2049%20§%201[1969 c 49 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c52.pdf?cite=1957%20c%2052%20§%2029[1957 c 52 § 29]; 1941 c 92 § 2, part; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c112.pdf?cite=1935%20c%20112%20§%204[1935 c 112 § 4]; Rem. Supp. 1941 § 10031-4, part; ]

== 18.32.160 - Licenses—Who shall sign.
All licenses issued by the secretary on behalf of the commission shall be signed by the secretary or chairperson and secretary of the commission.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20215[1994 sp.s. c 9 § 215]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2065[1991 c 3 § 65]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c202.pdf?cite=1989%20c%20202%20§%2021[1989 c 202 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c130.pdf?cite=1951%20c%20130%20§%203[1951 c 130 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c112.pdf?cite=1935%20c%20112%20§%2017[1935 c 112 § 17]; RRS § 10031-17; ]

== 18.32.170 - Duplicate licenses—Fee.
A fee determined by the secretary as provided in RCW 43.70.250 and 43.70.280 shall be charged for every duplicate license issued by the secretary.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2015[1996 c 191 § 15]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2066[1991 c 3 § 66]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%2025[1985 c 7 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c30.pdf?cite=1975%201st%20ex.s.%20c%2030%20§%2029[1975 1st ex.s. c 30 § 29]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c52.pdf?cite=1957%20c%2052%20§%2025[1957 c 52 § 25]; 1935 c 112 § 11, part; RRS § 10031-11, part; ]

== 18.32.180 - License renewal.
Every person licensed to practice dentistry in this state shall renew his or her license and comply with administrative procedures, administrative requirements, continuing education requirements, and fees as provided in RCW 43.70.250 and 43.70.280. The commission, in its sole discretion, may permit the applicant to be licensed without examination, and with or without conditions, if it is satisfied that the applicant meets all the requirements for licensure in this state and is competent to engage in the practice of dentistry.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1699.SL.pdf?cite=1999%20c%20364%20§%203[1999 c 364 § 3]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2016[1996 c 191 § 16]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20216[1994 sp.s. c 9 § 216]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2067[1991 c 3 § 67]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c202.pdf?cite=1989%20c%20202%20§%2022[1989 c 202 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%2026[1985 c 7 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c30.pdf?cite=1975%201st%20ex.s.%20c%2030%20§%2030[1975 1st ex.s. c 30 § 30]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c49.pdf?cite=1969%20c%2049%20§%203[1969 c 49 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c130.pdf?cite=1951%20c%20130%20§%204[1951 c 130 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c112.pdf?cite=1935%20c%20112%20§%2024[1935 c 112 § 24]; RRS § 10031-24; ]

== 18.32.185 - Inactive license status.
The commission may adopt rules under this section authorizing an inactive license status.

. An individual licensed under chapter 18.32 RCW may place his or her license on inactive status. The holder of an inactive license must not practice dentistry in this state without first activating the license.

. The inactive renewal fee must be established by the secretary under RCW 43.70.250. Failure to renew an inactive license shall result in cancellation of the inactive license in the same manner as an active license.

. An inactive license may be placed in an active status upon compliance with rules established by the commission.

. Provisions relating to disciplinary action against a person with a license are applicable to a person with an inactive license, except that when disciplinary proceedings against a person with an inactive license have been initiated, the license will remain inactive until the proceedings have been completed.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2126.SL.pdf?cite=1996%20c%20187%20§%201[1996 c 187 § 1]; ]

== 18.32.190 - Licenses display—Notification of address.
Every person who engages in the practice of dentistry in this state shall cause his or her license to be, at all times, displayed in a conspicuous place, in his or her office wherein he or she shall practice such profession, and shall further, whenever requested, exhibit such license to any of the members of the commission, or its authorized agent, and to the secretary or his or her authorized agent. Every licensee shall notify the secretary of the address or addresses, and of every change thereof, where the licensee shall engage in the practice of dentistry.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20217[1994 sp.s. c 9 § 217]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2068[1991 c 3 § 68]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c277.pdf?cite=1981%20c%20277%20§%207[1981 c 277 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c112.pdf?cite=1935%20c%20112%20§%207[1935 c 112 § 7]; RRS § 10031-7; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c16.pdf?cite=1923%20c%2016%20§%2015[1923 c 16 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c55.pdf?cite=1893%20c%2055%20§%205[1893 c 55 § 5]; ]

== 18.32.195 - University of Washington dental school faculty and residents—Licenses.
The commission may, without examination, issue a license to persons who possess the qualifications set forth in this section.

. The commission may, upon written request of the dean of the school of dentistry of the University of Washington, issue a license to practice dentistry in this state to persons who have been licensed or otherwise authorized to practice dentistry in another state or country and who have been accepted for employment by the school of dentistry as faculty members. For purposes of this subsection, this means teaching members of the faculty of the school of dentistry of the University of Washington. Such license shall permit the holder thereof to practice dentistry within the confines of the university facilities for a period of one year while he or she is so employed as a faculty member by the school of dentistry of the University of Washington. It shall terminate whenever the holder ceases to be a faculty member. Such license shall permit the holder thereof to practice dentistry only in connection with his or her duties in employment with the school of dentistry of the University of Washington. This limitation shall be stated on the license.

. The commission may, upon written request of the dean of the school of dentistry of the University of Washington or the director of a postdoctoral dental residency program approved by the commission, issue a limited license to practice dentistry in this state to university postdoctoral students or residents in dental education or to postdoctoral residents in a dental residency program approved by the commission. Prior to July 1, 2010, a dental residency program must be accredited by the commission on dental accreditation, or be in the process of obtaining such accreditation, in order to be approved by the commission. On or after July 1, 2010, the dental residency program must be accredited by the commission on dental accreditation in order to be approved by the commission. The license shall permit the resident dentist to provide dental care only in connection with his or her duties as a university postdoctoral dental student or resident or a postdoctoral resident in a program approved by the commission.

. The commission may condition the granting of a license under this section with terms the commission deems appropriate. All persons licensed under this section shall be subject to the jurisdiction of the commission to the same extent as other members of the dental profession, in accordance with this chapter, and in addition the licensee may be disciplined by the commission after a hearing has been held in accordance with the provisions set forth in this chapter, and determination by the commission that such licensee has violated any of the restrictions set forth in this section.

. Persons applying for licensure pursuant to this section shall pay the application fee determined by the secretary and, in the event the license applied for is issued, a license fee at the rate provided for licenses generally. After review by the commission, licenses issued under this section may be renewed annually if the licensee continues to be employed as a faculty member of the school of dentistry of the University of Washington, or is a university postdoctoral student or resident in dental education, or a postdoctoral resident in a dental residency program approved by the commission, and otherwise meets the requirements of the provisions and conditions deemed appropriate by the commission. Any person who obtains a license pursuant to this section may, without an additional application fee, apply for licensure under this chapter, in which case the applicant shall be subject to examination and the other requirements of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1740-S.SL.pdf?cite=2009%20c%20327%20§%201[2009 c 327 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1689-S.SL.pdf?cite=2005%20c%20454%20§%201[2005 c 454 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1612.SL.pdf?cite=2005%20c%20164%20§%201[2005 c 164 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20218[1994 sp.s. c 9 § 218]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2555-S.SL.pdf?cite=1992%20c%2059%20§%201[1992 c 59 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2069[1991 c 3 § 69]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c111.pdf?cite=1985%20c%20111%20§%201[1985 c 111 § 1]; ]

== 18.32.215 - Licensure without examination—Licensed in another state.
. An applicant holding a valid license and currently engaged in practice in another state may be granted a license without examination required by this chapter, on the payment of any required fees, if the applicant:

.. Is a graduate of a dental college, school, or dental department of an institution approved by the commission under RCW 18.32.040(1); or

.. [Empty]
... Has practiced in another state for at least four years; and

... Has completed a one-year postdoctoral residency approved by the commission. The residency may have been completed outside Washington.

. The commission may also require the applicant to: (a) File with the commission documentation certifying the applicant is licensed to practice in another state; and (b) provide information as the commission deems necessary pertaining to the conditions and criteria of the Uniform Disciplinary Act, chapter 18.130 RCW, and to demonstrate to the commission a knowledge of Washington law pertaining to the practice of dentistry.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2881-S.SL.pdf?cite=2008%20c%20147%20§%201[2008 c 147 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5966-S.SL.pdf?cite=2003%20c%2057%20§%202[2003 c 57 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20219[1994 sp.s. c 9 § 219]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c202.pdf?cite=1989%20c%20202%20§%2030[1989 c 202 § 30]; ]

== 18.32.220 - Certificate available for dentists going out-of-state.
Anyone who is a licensed dentist in the state of Washington who desires to change residence to another state or territory, shall, upon application to the secretary and payment of a fee as determined by the secretary under RCW 43.70.250 and 43.70.280, receive a certificate over the signature of the secretary or his or her designee, which shall attest to the facts mentioned in this section, and giving the date upon which the dentist was licensed.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2017[1996 c 191 § 17]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2070[1991 c 3 § 70]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c202.pdf?cite=1989%20c%20202%20§%2023[1989 c 202 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c112.pdf?cite=1935%20c%20112%20§%2014[1935 c 112 § 14]; RRS § 10031-14. FORMER PART OF SECTION:  1935 c 112 § 15; RRS § 10031-15, now codified as RCW  18.32.225; ]

== 18.32.222 - Commission report—Foreign-trained dentists—Licensure.
By November 15, 2009, the commission shall report to the governor and the legislature with recommendations for appropriate standards for issuing a license to a foreign-trained dentist. The recommendations shall consider the balance between maintaining assurances that Washington's dental professionals are well-qualified and planning for an adequate supply of dentists to meet the future needs of Washington's diverse urban and rural communities. In addition to considering the use of standards established by accreditation organizations, the recommendations shall consider other options to reduce barriers to licensure.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2881-S.SL.pdf?cite=2008%20c%20147%20§%202[2008 c 147 § 2]; ]

== 18.32.226 - Community-based sealant programs in schools.
. For low-income, rural, and other at-risk populations and in coordination with local public health jurisdictions and local oral health coalitions, a dental assistant working as of April 19, 2001, under the supervision of a licensed dentist may apply sealants and fluoride varnishes under the general supervision of a dentist in community-based sealant programs carried out in schools without attending the department's school sealant endorsement program.

. For low-income, rural, and other at-risk populations and in coordination with local public health jurisdictions and local oral health coalitions, dental assistants who are school sealant endorsed under RCW 43.70.650 may apply sealants and fluoride varnishes under the general supervision of a dentist in community-based sealant programs carried out in schools.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6020-S.SL.pdf?cite=2001%20c%2093%20§%204[2001 c 93 § 4]; ]

== 18.32.390 - Penalty—General.
Any person who violates any of the provisions of the chapter for which no specific penalty has been provided herein, shall be subject to prosecution before any court of competent jurisdiction, and shall, upon conviction, be guilty of a gross misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c259.pdf?cite=1986%20c%20259%20§%2038[1986 c 259 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c112.pdf?cite=1935%20c%20112%20§%2016[1935 c 112 § 16]; RRS § 10031-16; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1901c152.pdf?cite=1901%20c%20152%20§%204[1901 c 152 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c55.pdf?cite=1893%20c%2055%20§%208[1893 c 55 § 8]; ]

== 18.32.530 - "Unprofessional conduct."
In addition to those acts defined in chapter 18.130 RCW, the term "unprofessional conduct" as used in RCW 18.32.530 through 18.32.755 includes gross, willful, or continued overcharging for professional services.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c202.pdf?cite=1989%20c%20202%20§%2026[1989 c 202 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c259.pdf?cite=1986%20c%20259%20§%2041[1986 c 259 § 41]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c5.pdf?cite=1977%20ex.s.%20c%205%20§%203[1977 ex.s. c 5 § 3]; ]

== 18.32.533 - Unprofessional conduct—Abrogation of copayment provisions.
It is unprofessional conduct under this chapter and chapter 18.130 RCW for a dentist to abrogate the copayment provisions of a contract by accepting the payment received from a third party payer as full payment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c202.pdf?cite=1985%20c%20202%20§%201[1985 c 202 § 1]; ]

== 18.32.534 - Impaired dentist program—Content—License surcharge.
. To implement an impaired dentist program as authorized by RCW 18.130.175, the commission shall enter into a contract with a voluntary substance abuse monitoring program. The impaired dentist program may include any or all of the following:

.. Contracting with providers of treatment programs;

.. Receiving and evaluating reports of suspected impairment from any source;

.. Intervening in cases of verified impairment;

.. Referring impaired dentists to treatment programs;

.. Monitoring the treatment and rehabilitation of impaired dentists including those ordered by the commission;

.. Providing education, prevention of impairment, posttreatment monitoring, and support of rehabilitated impaired dentists; and

.. Performing other related activities as determined by the commission.

. A contract entered into under subsection (1) of this section shall be financed by a surcharge of up to fifty dollars on each license issuance or renewal to be collected by the department of health from every dentist licensed under chapter 18.32 RCW. These moneys shall be placed in the health professions account to be used solely for the implementation of the impaired dentist program.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1534.SL.pdf?cite=2013%20c%20129%20§%201[2013 c 129 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1838-S.SL.pdf?cite=1999%20c%20179%20§%201[1999 c 179 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20220[1994 sp.s. c 9 § 220]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2072[1991 c 3 § 72]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c125.pdf?cite=1989%20c%20125%20§%201[1989 c 125 § 1]; ]

== 18.32.640 - Rules—Administration of sedation and general anesthesia.
. The commission may adopt such rules as it deems necessary to carry out this chapter.

. The commission may adopt rules governing administration of sedation and general anesthesia by persons licensed under this chapter, including necessary training, education, equipment, and the issuance of any permits, certificates, or registration as required.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20221[1994 sp.s. c 9 § 221]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c217.pdf?cite=1988%20c%20217%20§%201[1988 c 217 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c259.pdf?cite=1986%20c%20259%20§%2042[1986 c 259 § 42]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c5.pdf?cite=1977%20ex.s.%20c%205%20§%2014[1977 ex.s. c 5 § 14]; ]

== 18.32.655 - Commission—Supervision of records—Rules.
The commission shall:

. Require licensed dentists to keep and maintain a copy of each laboratory referral instruction, describing detailed services rendered, for a period to be determined by the commission but not more than three years, and may require the production of all such records for examination by the commission or its authorized representatives; and

. Adopt reasonable rules requiring licensed dentists to make, maintain, and produce for examination by the commission or its authorized representatives such other records as may be reasonable and proper in the performance of its duties and enforcing the provisions of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20222[1994 sp.s. c 9 § 222]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c259.pdf?cite=1986%20c%20259%20§%2035[1986 c 259 § 35]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c93.pdf?cite=1953%20c%2093%20§%208[1953 c 93 § 8]; ]

== 18.32.665 - Advertising—False—Credit terms.
It shall be unlawful for any person, firm, or corporation to publish, directly or indirectly, or circulate any fraudulent, false, or misleading statements within the state of Washington as to the skill or method of practice of any person or operator; or in any way to advertise in print any matter with a view of deceiving the public, or in any way that will tend to deceive or defraud the public; or to claim superiority over neighboring dental practitioners; or to publish reports of cases or certificates of same in any public advertising media; or to advertise as using any anesthetic, drug, formula, medicine, which is either falsely advertised or misnamed; or to employ "capper" or "steerers" to obtain patronage; and any person committing any offense against any of the provisions of this section shall, upon conviction, be subjected to such penalties as are provided in this chapter: PROVIDED, That any person licensed under this chapter may announce credit, terms of credit or installment payments that may be made at periodical intervals to apply on account of any dental service rendered. The commission may adopt such rules as are necessary to carry out the intent of this section.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20223[1994 sp.s. c 9 § 223]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c259.pdf?cite=1986%20c%20259%20§%2036[1986 c 259 § 36]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c112.pdf?cite=1935%20c%20112%20§%2020[1935 c 112 § 20]; RRS § 10031-20; ]

== 18.32.675 - Practice or solicitation by corporations prohibited—Penalty.
. No corporation shall practice dentistry or shall solicit through itself, or its agent, officers, employees, directors or trustees, dental patronage for any dentists or dental surgeon employed by any corporation: PROVIDED, That nothing contained in this chapter shall prohibit a corporation from employing a dentist or dentists to render dental services to its employees: PROVIDED, FURTHER, That such dental services shall be rendered at no cost or charge to the employees; nor shall it apply to corporations or associations in which the dental services were originated and are being conducted upon a purely charitable basis for the worthy poor.

. Nothing in this chapter precludes a person or entity not licensed by the commission from:

.. Ownership or leasehold of any assets used by a dental practice, including real property, furnishings, equipment, instruments, materials, supplies, and inventory, excluding dental records of patients;

.. [Empty]
... Employing or contracting for the services of personnel other than licensed dentists, licensed dental hygienists, licensed expanded function dental auxiliaries, certified dental anesthesia assistants, and registered dental assistants;

... Contracting for the services of a licensed dentist or employing or contracting for the services of licensed dental hygienists, licensed expanded function dental auxiliaries, certified dental anesthesia assistants, and registered dental assistants if the entity is a health service contractor that is licensed under chapter 48.44 RCW and is organized as a nonprofit integrated care delivery system, if all of the following conditions are met:

(A) The arrangement between the parties meets the personal services and management contracts safe harbor requirements as provided by 42 C.F.R. Sec. 1001.952(d); and

(B) The arrangement between the parties meets either of the following safe harbors:

(I) The managed care organization safe harbor requirements as provided by 42 C.F.R. Sec. 1001.952(t); or

(II) The space rental safe harbor requirements as provided by 42 C.F.R. Sec. 1001.952(b) and the equipment rental safe harbor requirements as provided by 42 C.F.R. Sec. 1001.952(c);

.. Providing business support and management services to a dental practice, including as a sole provider of such services; and

.. Receiving fees for the services in (a) through (c) of this subsection provided to a dental practice calculated as agreed to by the dental practice owner or owners.

. Nothing in this chapter shall prohibit a health carrier as defined in RCW 48.43.005, while acting in its capacity as a health carrier and in no other capacity, from entering into provider contracts or provider compensation agreements, as defined in RCW 48.43.730, with a dentist or dental practice.

. Any corporation violating this section is guilty of a gross misdemeanor, and each day that this chapter is violated shall be considered a separate offense.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2229-S.SL.pdf?cite=2018%20c%20210%20§%201[2018 c 210 § 1]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5322-S.SL.pdf?cite=2017%20c%20320%20§%202[2017 c 320 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20124[2003 c 53 § 124]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c112.pdf?cite=1935%20c%20112%20§%2019[1935 c 112 § 19]; RRS § 10031-19; ]

== 18.32.677 - Interference with licensee's independent clinical judgment.
. A person that is not licensed under this chapter or an entity that is not a professional entity practices dentistry in violation of this chapter, and subject to enforcement under RCW 18.130.190, if the person or entity interferes with a licensed dentist's independent clinical judgment by:

.. Limiting or imposing requirements on the length of time a dentist spends with a patient or performing dental services, or otherwise placing conditions on the number of patients a dentist must treat in a certain period of time or the number of certain types of procedures a dentist must complete in a certain time period;

.. Limiting or imposing requirements on the decision of a dentist regarding a course or alternative course of treatment for a patient or the manner in which a course of treatment is carried out by the dentist;

.. Limiting or imposing requirements on the manner in which a dentist uses dental equipment or materials for the provision of dental treatment;

.. Limiting or imposing requirements on the use of a laboratory or the materials, supplies, instruments, or equipment deemed reasonably necessary by a dentist to provide diagnoses and treatment consistent with the standard of care;

.. Limiting or imposing requirements for the professional training deemed reasonably necessary by a dentist to properly serve the dentist's patients;

.. Limiting or imposing requirements on the referrals by a dentist to another licensed dentist specialist or any other practitioner the dentist determines is necessary;

.. Interfering with a dentist's right to access patient records at any time;

.. Interfering with a dentist's decision to refund any payment made by a patient for dental services performed by the dentist;

.. Limiting or imposing requirements on the advertising of a dental practice if it would result in a violation of this chapter or *RCW 18.130.020(12)(b) by the dental practice; or

.. Limiting or imposing requirements on communications with a dentist's patients.

. For the purpose of this section, "dentist" means a dentist licensed under this chapter.

. Violations of this section shall be enforced pursuant to RCW 18.130.190, including the authority to issue subpoenas pursuant to RCW 18.130.050(4). Communication of complaints or information to a state agency pursuant to RCW 4.24.500 through 4.24.520 are covered by those provisions.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5322-S.SL.pdf?cite=2017%20c%20320%20§%203[2017 c 320 § 3]; ]

== 18.32.683 - Patient abandonment.
. The attending dentist, without reasonable cause, must not neglect, ignore, abandon, or refuse to complete the current procedure for a patient. If the dentist chooses to withdraw responsibility for a patient of record, the dentist shall:

.. Advise the patient that termination of treatment is contemplated and that another dentist should be sought to complete the current procedure and for future care; and

.. Advise the patient that the dentist will remain reasonably available under the circumstances for up to fifteen days from the date of such notice to render emergency care related to that current procedure.

. If a dentist provides dental services as an employee or contractor of another dentist or an entity authorized to render dental services pursuant to chapter 18.100, 25.05, or 25.15 RCW or to operate a dental office pursuant to RCW 18.32.675(1), the other dentist or entity shall be responsible for the continuing treatment of patients and a dentist who ceases to be an employee or contractor of such other dentist or entity is not deemed to have abandoned any patient, and is not obligated to advise any patient as provided in this section, with respect to which the continuing treatment responsibility is retained by the other dentist or entity. If an entity is responsible for the continuing treatment of patients, any licensed dentist who is the owner of the entity is considered the attending dentist responsible for ensuring compliance by the entity with this section.

. A dental practice owner who is discontinuing a dental practice or moving a dental practice to a new location must comply with the requirements of subsection (1) of this section, or must make reasonable arrangements for the transfer of the patient records of active patients of the dental practice, or copies of the records, to a licensed dentist or professional entity, or at the written request of any patient, transfer of the patient's records, or copies of the records, to the patient. An unlicensed person or entity shall not intentionally prevent a dental practice owner from complying with this subsection.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5322-S.SL.pdf?cite=2017%20c%20320%20§%204[2017 c 320 § 4]; ]

== 18.32.685 - Prescriptions—Filled by druggists.
Registered pharmacists of this state may fill prescriptions of legally licensed dentists of this state for any drug necessary in the practice of dentistry.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c112.pdf?cite=1935%20c%20112%20§%2026[1935 c 112 § 26]; RRS § 10031-26; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c16.pdf?cite=1923%20c%2016%20§%2024[1923 c 16 § 24]; ]

== 18.32.695 - Identification of new dental prostheses.
Every complete upper and lower denture and removable dental prosthesis fabricated by a dentist licensed under this chapter, or fabricated pursuant to the dentist's work order or under the dentist's direction or supervision, shall be marked with the name of the patient for whom the prosthesis is intended. The markings shall be done during fabrication and shall be permanent, legible, and cosmetically acceptable. The exact location of the markings and the methods used to apply or implant them shall be determined by the dentist or dental laboratory fabricating the prosthesis. If, in the professional judgment of the dentist or dental laboratory, this identification is not practical, identification shall be provided as follows:

. The initials of the patient may be shown alone, if use of the name of the patient is impracticable; or

. The identification marks may be omitted in their entirety if none of the forms of identification specified in subsection (1) of this section is practicable or clinically safe.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c252.pdf?cite=1987%20c%20252%20§%201[1987 c 252 § 1]; ]

== 18.32.705 - Identification of previously fabricated prostheses.
Any removable prosthesis in existence before July 26, 1987, that was not marked in accordance with RCW 18.32.695 at the time of its fabrication, shall be so marked at the time of any subsequent rebasing.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c252.pdf?cite=1987%20c%20252%20§%202[1987 c 252 § 2]; ]

== 18.32.715 - Identification of dental prostheses—Violation.
Failure of any dentist to comply with RCW 18.32.695 and 18.32.705 is a violation for which the dentist may be subject to proceedings if the dentist is charged with the violation within two years of initial insertion of the dental prosthetic device.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c252.pdf?cite=1987%20c%20252%20§%204[1987 c 252 § 4]; ]

== 18.32.725 - Sanitary regulations.
It shall be the duty of every person engaged in the practice of dentistry or who shall own, operate, or manage any dental office to keep said office and dental equipment in a thoroughly clean and sanitary condition.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c112.pdf?cite=1935%20c%20112%20§%2027[1935 c 112 § 27]; RRS § 10031-27; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c16.pdf?cite=1923%20c%2016%20§%2025[1923 c 16 § 25]; ]

== 18.32.735 - Unlawful practice—Hygienists—Penalty.
Any licensed dentist who shall permit any dental hygienist operating under his or her supervision to perform any operation required to be performed by a dentist under the provisions of this chapter shall be guilty of a misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20478[2011 c 336 § 478]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c112.pdf?cite=1935%20c%20112%20§%2028[1935 c 112 § 28]; RRS § 10031-28; ]

== 18.32.745 - Unlawful practice—Employing unlicensed dentist—Penalty.
. No manager, proprietor, partnership, or association owning, operating, or controlling any room, office, or dental parlors, where dental work is done, provided, or contracted for, shall employ or retain any unlicensed person or dentist as an operator; nor shall fail, within ten days after demand made by the secretary of health or the commission in writing sent by certified mail, addressed to any such manager, proprietor, partnership, or association at the room, office, or dental parlor, to furnish the secretary of health or the commission with the names and addresses of all persons practicing or assisting in the practice of dentistry in his or her place of business or under his or her control, together with a sworn statement showing by what license or authority the persons are practicing dentistry.

. The sworn statement shall not be used as evidence in any subsequent court proceedings, except in a prosecution for perjury connected with its execution.

. Any violation of this section is improper, unprofessional, and dishonorable conduct, and grounds for injunction proceedings as provided by this chapter.

. [Empty]
.. Except as provided in (b) of this subsection, a violation of this section is also a gross misdemeanor.

.. The failure to furnish the information as may be requested in accordance with this section is a misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20125[2003 c 53 § 125]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20224[1994 sp.s. c 9 § 224]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2073[1991 c 3 § 73]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c5.pdf?cite=1977%20ex.s.%20c%205%20§%2031[1977 ex.s. c 5 § 31]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c52.pdf?cite=1957%20c%2052%20§%2038[1957 c 52 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c93.pdf?cite=1953%20c%2093%20§%207[1953 c 93 § 7]; 1937 c 45 § 1, part; 1935 c 112 § 18, part; RRS § 10031-18, part; ]

== 18.32.755 - Advertising—Names used—Penalty.
. Any advertisement or announcement for dental services must include for each office location advertised the names of all persons practicing dentistry at that office location.

. Any violation of this section is improper, unprofessional, and dishonorable conduct, and grounds for injunction proceedings as provided by RCW 18.130.190(4).

. A violation of this section is also a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20126[2003 c 53 § 126]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20225[1994 sp.s. c 9 § 225]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c259.pdf?cite=1986%20c%20259%20§%2037[1986 c 259 § 37]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c52.pdf?cite=1957%20c%2052%20§%2039[1957 c 52 § 39]; 1937 c 45 § 1, part; 1935 c 112 § 18, part; RRS § 10031-18, part; ]

== 18.32.765 - Pilot project—Commission—Authority over budget.
. The commission may conduct a pilot project to evaluate the effect of granting the commission additional authority over budget development, spending, and staffing. If the commission intends to conduct a pilot project, it must provide a notice in writing to the secretary by June 1, 2008. If the commission chooses to conduct a pilot project, the pilot project shall begin on July 1, 2008, and conclude on June 30, 2013.

. The pilot project shall include the following provisions:

.. That the secretary shall employ an executive director that is:

... Hired by and serves at the pleasure of the commission;

... Exempt from the provisions of the civil service law, chapter 41.06 RCW and whose salary is established by the commission in accordance with RCW 43.03.028; and

... Responsible for performing all administrative duties of the commission, including preparing an annual budget, and any other duties as delegated to the executive director by the commission;

.. Consistent with the budgeting and accounting act:

... With regard to budget for the remainder of the 2007-2009 biennium, the commission has authority to spend the remaining funds allocated with respect to its professions, dentists licensed under this chapter and expanded function dental auxiliaries and dental assistants regulated under chapter 18.260 RCW; and

... Beginning with the 2009-2011 biennium, the commission is responsible for proposing its own biennial budget which the secretary must submit to the office of financial management;

.. That, prior to adopting credentialing fees under RCW 43.70.250, the secretary shall collaborate with the commission to determine the appropriate fees necessary to support the activities of the commission;

.. That, prior to the secretary exercising the secretary's authority to adopt uniform rules and guidelines, or any other actions that might impact the licensing or disciplinary authority of the commission, the secretary shall first meet with the commission to determine how those rules or guidelines, or changes to rules or guidelines, might impact the commission's ability to effectively carry out its statutory duties. If the commission, in consultation with the secretary, determines that the proposed rules or guidelines, or changes to existing rules or guidelines, will negatively impact the commission's ability to effectively carry out its statutory duties, then the individual commission shall collaborate with the secretary to develop alternative solutions to mitigate the impacts. If an alternative solution cannot be reached, the parties may resolve the dispute through a mediator as set forth in (f) of this subsection;

.. That the commission shall negotiate with the secretary to develop performance-based expectations, including identification of key performance measures. The performance expectations should focus on consistent, timely regulation of health care professionals; and

.. That in the event there is a disagreement between the commission and the secretary, that is unable to be resolved through negotiation, a representative of both parties shall agree on the designation of a third party to mediate the dispute.

. By December 15, 2013, the secretary, the commission, and the other commissions conducting similar pilot projects under RCW 18.71.430, 18.79.390, and * 18.25.210, shall report to the governor and the legislature on the results of the pilot project. The report shall:

.. Compare the effectiveness of licensing and disciplinary activities of each commission during the pilot project with the licensing and disciplinary activities of the commission prior to the pilot project and the disciplinary activities of other disciplining authorities during the same time period as the pilot project;

.. Compare the efficiency of each commission with respect to the timeliness and personnel resources during the pilot project to the efficiency of the commission prior to the pilot project and the efficiency of other disciplining authorities during the same period as the pilot project;

.. Compare the budgetary activity of each commission during the pilot project to the budgetary activity of the commission prior to the pilot project and to the budgetary activity of other disciplining authorities during the same period as the pilot project;

.. Evaluate each commission's regulatory activities, including timelines, consistency of decision making, and performance levels in comparison to other disciplining authorities; and

.. Review summaries of national research and data regarding regulatory effectiveness and patient safety.

. The secretary shall employ staff that are hired and managed by the executive director provided that nothing contained in this section may be construed to alter any existing collective bargaining unit or the provisions of any existing collective bargaining agreement.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1048-S.SL.pdf?cite=2011%20c%2060%20§%206[2011 c 60 § 6]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1103-S4.SL.pdf?cite=2008%20c%20134%20§%2032[2008 c 134 § 32]; ]

== 18.32.775 - Disciplinary proceedings—Cost and fee recovery.
. In any disciplinary case pertaining to a dentist where there is a contested hearing, if the commission or its hearing panel makes the finding requisite for, and imposes upon the dentist, a disciplinary sanction or fine under RCW 18.130.160, unless it determines to waive the assessment of a hearing fee, it shall assess against the licensee a partial recovery of the state's hearing expenses as follows:

.. The partial recovery hearing fee must be:

... An amount equal to six thousand dollars for each full hearing day in the proceeding and one-half of that amount for any partial hearing day; and

... A partial recovery of investigative and hearing preparation expenses in an amount as found to be reasonable reimbursement under the circumstances but no more than ten thousand dollars;

.. Substantiation of investigative and hearing preparation expenses for purposes of (a) of this subsection may be by affidavit or declaration descriptive of efforts expended, which are reviewable in the hearing as would be a cost bill;

.. The commission or its hearing panel may waive the partial recovery hearing fee if it determines the assessment of the fee (i) would create substantial undue hardship for the dentist, or (ii) in all the circumstances of the case, including the nature of the charges alleged, it would be manifestly unjust to assess the fee. Consideration of the waiver must be applied for and considered during the hearing itself. This may be in advance of the decision related to RCW 18.130.160.

. If the dentist seeks judicial review of the disciplinary action and there was a partial recovery hearing fee assessed, then unless the license holder achieves a substantial element of relief, the reviewing trial court or appellate court shall further impose a partial cost recovery fee in the amount of twenty-five thousand dollars at the superior court level, twenty-five thousand dollars at the court of appeals level, and twenty-five thousand dollars at the supreme court level. Application for waiver may be made to the court at each level and must be considered by the court under the standards stated in subsection (1)(c) of this section.

. In any disciplinary case pertaining to a dentist where the case is resolved by agreement prior to completion of a contested hearing, the commission shall assess against the dentist a partial recovery of investigative and hearing preparation expenses in an amount as found to be reasonable reimbursement in the circumstances but no more than ten thousand dollars, unless it determines to waive this fee under the standards stated in subsection (1)(c) of this section.

. In any stipulated informal disposition of allegations pertaining to a dentist as contemplated under RCW 18.130.172, the potential dollar limit of reimbursement of investigative and processing costs may not exceed two thousand dollars per allegation.

. Should the dentist fail to pay any agreed reimbursement or ordered cost recovery under the statute, the commission may seek collection of the amount in the same manner as enforcement of a fine under RCW 18.130.165.

. All fee recoveries and reimbursements under this statute must be deposited to the health professions account for the portion of it allocated to the commission. The fee recoveries shall be fully credited in reduction of actual or projected expenditures used to determine dentist license renewal fees.

. The authority of the commission under this section is in addition to all of its authorities under RCW 18.130.160, elsewhere in chapter 18.130 RCW, or in this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2009%20c%20177%20§%201[2009 c 177 § 1]; ]

== 18.32.785 - Pain management rules—Criteria for new rules.
. By June 30, 2011, the commission shall adopt new rules on chronic, noncancer pain management that contain the following elements:

.. [Empty]
... Dosing criteria, including:

(A) A dosage amount that must not be exceeded unless a dentist first consults with a practitioner specializing in pain management; and

(B) Exigent or special circumstances under which the dosage amount may be exceeded without consultation with a practitioner specializing in pain management.

... The rules regarding consultation with a practitioner specializing in pain management must, to the extent practicable, take into account:

(A) Circumstances under which repeated consultations would not be necessary or appropriate for a patient undergoing a stable, ongoing course of treatment for pain management;

(B) Minimum training and experience that is sufficient to exempt a dentist from the specialty consultation requirement;

(C) Methods for enhancing the availability of consultations;

(D) Allowing the efficient use of resources; and

(E) Minimizing the burden on practitioners and patients;

.. Guidance on when to seek specialty consultation and ways in which electronic specialty consultations may be sought;

.. Guidance on tracking clinical progress by using assessment tools focusing on pain interference, physical function, and overall risk for poor outcome; and

.. Guidance on tracking the use of opioids.

. The commission shall consult with the agency medical directors' group, the department of health, the University of Washington, and the largest professional association of dentists in the state.

. The rules adopted under this section do not apply:

.. To the provision of palliative, hospice, or other end-of-life care; or

.. To the management of acute pain caused by an injury or a surgical procedure.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2876-S.SL.pdf?cite=2010%20c%20209%20§%202[2010 c 209 § 2]; ]

== 18.32.800 - Opioid drug prescribing rules—Adoption.
. By January 1, 2019, the commission must adopt rules establishing requirements for prescribing opioid drugs. The rules may contain exemptions based on education, training, amount of opioids prescribed, patient panel, and practice environment.

. In developing the rules, the commission must consider the agency medical directors' group and centers for disease control guidelines, and may consult with the department of health, the University of Washington, and the largest professional association of dentists in the state.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1427-S.SL.pdf?cite=2017%20c%20297%20§%203[2017 c 297 § 3]; ]

== 18.32.810 - Opioid drugs—Right to refuse.
By January 1, 2020, the commission must adopt or amend its rules to require dentists who prescribe opioids to inform patients of their right to refuse an opioid prescription or order for any reason. If a patient indicates a desire to not receive an opioid, the dentist must document the patient's request and avoid prescribing or ordering opioids, unless the request is revoked by the patient.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5380-S.SL.pdf?cite=2019%20c%20314%20§%204[2019 c 314 § 4]; ]

