= 18.92 - Veterinary medicine, surgery, and dentistry.
:toc:

== 18.92.010 - Veterinary practice defined.
Any person shall be regarded as practicing veterinary medicine, surgery and dentistry within the meaning of this chapter who shall, within this state, (1) by advertisement, or by any notice, sign, or other indication, or by a statement written, printed or oral, in public or private, made, done, or procured by himself or herself, or any other, at his or her request, for him or her, represent, claim, announce, make known or pretend his or her ability or willingness to diagnose or prognose or treat diseases, deformities, defects, wounds, or injuries of animals; (2) or who shall so advertise, make known, represent or claim his or her ability and willingness to prescribe or administer any drug, medicine, treatment, method or practice, or to perform any operation, manipulation, or apply any apparatus or appliance for cure, amelioration, correction or reduction or modification of any animal disease, deformity, defect, wound or injury, for hire, fee, compensation, or reward, promised, offered, expected, received, or accepted directly or indirectly; (3) or who shall within this state diagnose or prognose any animal diseases, deformities, defects, wounds or injuries, for hire, fee, reward, or compensation promised, offered, expected, received, or accepted directly or indirectly; (4) or who shall within this state prescribe or administer any drug, medicine, treatment, method or practice, or perform any operation, or manipulation, or apply any apparatus or appliance for the cure, amelioration, alleviation, correction, or modification of any animal disease, deformity, defect, wound, or injury, for hire, fee, compensation, or reward, promised, offered, expected, received or accepted directly or indirectly; (5) or who performs any manual procedure for the diagnosis of pregnancy, sterility, or infertility upon livestock; (6) or who implants any electronic device for the purpose of establishing or maintaining positive identification of animals.

The opening of an office or place of business for the practice of veterinary medicine, the use of a sign, card, device or advertisement as a practitioner of veterinary medicine or as a person skilled in such practice shall be prima facie evidence of engaging in the practice of veterinary medicine, surgery and dentistry.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1144-S.SL.pdf?cite=1995%20c%20317%20§%201[1995 c 317 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c92.pdf?cite=1959%20c%2092%20§%201[1959 c 92 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c71.pdf?cite=1941%20c%2071%20§%201[1941 c 71 § 1]; Rem. Supp. 1941 § 10040-1; 1907 c 124 § 1. FORMER PART OF SECTION:  1941 c 71 § 21; Rem. Supp. 1941 § 10040-21, now codified as RCW  18.92.015; ]

== 18.92.012 - Authority to dispense legend drugs prescribed by other veterinarians.
A veterinarian licensed under this chapter may dispense veterinary legend drugs prescribed by other veterinarians licensed under this chapter, so long as, during any year, the total drugs so dispensed do not constitute more than five percent of the total dosage units of legend drugs the veterinarian dispenses and the veterinarian maintains records of his or her dispensing activities consistent with the requirements of chapters 18.64, 69.04, 69.41, and 69.50 RCW. For purposes of this section, a "veterinary legend drug" is a legend drug, as defined in chapter 69.41 RCW, which is either: (1) Restricted to use by licensed veterinarians by any law or regulation of the federal government, or (2) designated by rule by the pharmacy quality assurance commission as being a legend drug that one licensed veterinarian may dispense for another licensed veterinarian under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1609.SL.pdf?cite=2013%20c%2019%20§%2041[2013 c 19 § 41]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5381-S.SL.pdf?cite=1991%20c%2047%20§%201[1991 c 47 § 1]; ]

== 18.92.013 - Dispensing of drugs by registered or licensed personnel.
. A veterinarian legally prescribing drugs may delegate to a registered veterinary medication clerk, while under the veterinarian's direct supervision, certain nondiscretionary functions defined by the board and used in the preparing of legend and nonlegend drugs (except controlled substances as defined in or under chapter 69.50 RCW) associated with the practice of veterinary medicine. A veterinarian legally prescribing drugs may delegate to a licensed veterinary technician, while under the veterinarian's indirect supervision, certain nondiscretionary functions defined by the board and used in the preparing of legend drugs, nonlegend drugs, and controlled substances associated with the practice of veterinary medicine. Upon final approval of the packaged prescription following a direct physical inspection of the packaged prescription for proper formulation, packaging, and labeling by the veterinarian, the veterinarian may delegate the delivery of the prescription to a registered veterinary medication clerk or licensed veterinary technician, while under the veterinarian's indirect supervision. Dispensing of drugs by veterinarians, licensed veterinary technicians, and registered veterinary medication clerks shall meet the applicable requirements of chapters 18.64, 69.40, 69.41, and 69.50 RCW and is subject to inspection by the pharmacy quality assurance commission investigators.

. A licensed veterinary technician may administer legend drugs under chapter 69.41 RCW and controlled substances under chapter 69.50 RCW under indirect supervision of a veterinarian.

. For the purposes of this section:

.. "Direct supervision" means the veterinarian is on the premises and is quickly and easily available; and

.. "Indirect supervision" means the veterinarian is not on the premises but has given written or oral instructions for the delegated task.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1609.SL.pdf?cite=2013%20c%2019%20§%2042[2013 c 19 § 42]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1271-S.SL.pdf?cite=2009%20c%20136%20§%201[2009 c 136 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1331.SL.pdf?cite=2007%20c%20235%20§%205[2007 c 235 § 5]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2452.SL.pdf?cite=2000%20c%2093%20§%208[2000 c 93 § 8]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1266-S.SL.pdf?cite=1993%20c%2078%20§%202[1993 c 78 § 2]; ]

== 18.92.015 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Board" means the Washington state veterinary board of governors.

. "Department" means the department of health.

. "Secretary" means the secretary of the department of health.

. "Veterinary medication clerk" means a person who has satisfactorily completed a board-approved training program developed in consultation with the pharmacy quality assurance commission and designed to prepare persons to perform certain nondiscretionary functions defined by the board and used in the dispensing of legend and nonlegend drugs (except controlled substances as defined in or under chapter 69.50 RCW) associated with the practice of veterinary medicine.

. "Veterinary technician" means a person who is licensed by the board upon meeting the requirements of RCW 18.92.128.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1609.SL.pdf?cite=2013%20c%2019%20§%2043[2013 c 19 § 43]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1331.SL.pdf?cite=2007%20c%20235%20§%201[2007 c 235 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2452.SL.pdf?cite=2000%20c%2093%20§%209[2000 c 93 § 9]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1266-S.SL.pdf?cite=1993%20c%2078%20§%201[1993 c 78 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1960-S.SL.pdf?cite=1991%20c%20332%20§%2040[1991 c 332 § 40]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20238[1991 c 3 § 238]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c102.pdf?cite=1983%20c%20102%20§%201[1983 c 102 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c158.pdf?cite=1979%20c%20158%20§%2071[1979 c 158 § 71]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c44.pdf?cite=1974%20ex.s.%20c%2044%20§%201[1974 ex.s. c 44 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c50.pdf?cite=1967%20ex.s.%20c%2050%20§%201[1967 ex.s. c 50 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c92.pdf?cite=1959%20c%2092%20§%202[1959 c 92 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c71.pdf?cite=1941%20c%2071%20§%2021[1941 c 71 § 21]; Rem. Supp. 1941 § 10040-21; ]

== 18.92.021 - Veterinary board of governors—Appointment, qualifications, terms, officers—Quorum.
. There is created a Washington state veterinary board of governors consisting of seven members, five of whom shall be licensed veterinarians, one of whom shall be a licensed veterinary technician trained in both large and small animal medicine, and one of whom shall be a lay member.

. [Empty]
.. The licensed members shall be appointed by the governor. At the time of their appointment the licensed members of the board must be actual residents of the state in active practice as licensed practitioners of veterinary medicine, surgery, and dentistry, or employed as a licensed veterinary technician, as applicable, and must be citizens of the United States. Not more than one licensed veterinary member shall be from the same congressional district. The board shall not be deemed to be unlawfully constituted and a member of the board shall not be deemed ineligible to serve the remainder of the member's unexpired term on the board solely by reason of the establishment of new or revised boundaries for congressional districts.

.. The terms of the first licensed members of the board shall be as follows: One member for five, four, three, two, and one years respectively. Thereafter the terms shall be for five years and until their successors are appointed and qualified.

.. The lay member shall be appointed by the governor for a five year term and until the lay member's successor is appointed.

.. A member may be appointed to serve a second term, if that term does not run consecutively.

.. Vacancies in the board shall be filled by the governor, the appointee to hold office for the remainder of the unexpired term.

. The licensed veterinary technician member is a nonvoting member with respect to board decisions related to the discipline of a veterinarian involving standard of care.

. Officers of the board shall be a chair and a secretary-treasurer to be chosen by the members of the board from among its members.

. Four members of the board shall constitute a quorum at meetings of the board.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1331.SL.pdf?cite=2007%20c%20235%20§%203[2007 c 235 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c2.pdf?cite=1983%20c%202%20§%202[1983 c 2 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982ex1c30.pdf?cite=1982%201st%20ex.s.%20c%2030%20§%205[1982 1st ex.s. c 30 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c134.pdf?cite=1982%20c%20134%20§%201[1982 c 134 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c31.pdf?cite=1979%20ex.s.%20c%2031%20§%201[1979 ex.s. c 31 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c50.pdf?cite=1967%20ex.s.%20c%2050%20§%202[1967 ex.s. c 50 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c92.pdf?cite=1959%20c%2092%20§%203[1959 c 92 § 3]; ]

== 18.92.030 - General duties of board.
. The board shall develop and administer, or approve, or both, a licensure examination in the subjects determined by the board to be essential to the practice of veterinary medicine, surgery, and dentistry. The board may approve an examination prepared or administered by a private testing agency or association of licensing authorities.

. The board, under chapter 34.05 RCW, may adopt rules necessary to carry out the purposes of this chapter, including:

.. Standards for the performance of the duties and responsibilities of veterinary technicians and veterinary medication clerks and fixing minimum standards of continuing education for veterinary technicians. The rules shall be adopted in the interest of good veterinary health care delivery to the consuming public and shall not prevent veterinary technicians from inoculating an animal; and

.. Standards prescribing requirements for veterinary medical facilities and fixing minimum standards of continuing veterinary medical education.

. The department is the board's official office of record.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1331.SL.pdf?cite=2007%20c%20235%20§%204[2007 c 235 § 4]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2452.SL.pdf?cite=2000%20c%2093%20§%2010[2000 c 93 § 10]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5308-S.SL.pdf?cite=1995%20c%20198%20§%2013[1995 c 198 § 13]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1266-S.SL.pdf?cite=1993%20c%2078%20§%203[1993 c 78 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c259.pdf?cite=1986%20c%20259%20§%20140[1986 c 259 § 140]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c102.pdf?cite=1983%20c%20102%20§%202[1983 c 102 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c134.pdf?cite=1982%20c%20134%20§%202[1982 c 134 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c67.pdf?cite=1981%20c%2067%20§%2023[1981 c 67 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c44.pdf?cite=1974%20ex.s.%20c%2044%20§%202[1974 ex.s. c 44 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c50.pdf?cite=1967%20ex.s.%20c%2050%20§%203[1967 ex.s. c 50 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c157.pdf?cite=1961%20c%20157%20§%202[1961 c 157 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c92.pdf?cite=1959%20c%2092%20§%204[1959 c 92 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c71.pdf?cite=1941%20c%2071%20§%204[1941 c 71 § 4]; Rem. Supp. 1941 § 10040-4. FORMER PART OF SECTION:  1941 c 71 § 9; Rem. Supp. 1941 § 10040-9 now codified as RCW  18.92.035; ]

== 18.92.035 - Board to certify successful examinees.
The board shall certify to the secretary the names of all applicants who have successfully passed an examination and are entitled to a license to practice veterinary medicine, surgery and dentistry. The secretary shall thereupon issue a license to practice veterinary medicine, surgery and dentistry to such applicant.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20239[1991 c 3 § 239]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c71.pdf?cite=1941%20c%2071%20§%209[1941 c 71 § 9]; Rem. Supp. 1941 § 10040-9; ]

== 18.92.040 - Compensation and travel expenses of board members.
Each member of the board shall be compensated in accordance with *RCW 43.70.250 and shall be reimbursed for travel expenses in accordance with RCW 43.03.050 and 43.03.060. No expense may be incurred by members of the board except in connection with board meetings without prior approval of the secretary.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20240[1991 c 3 § 240]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c287.pdf?cite=1984%20c%20287%20§%2051[1984 c 287 § 51]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c102.pdf?cite=1983%20c%20102%20§%204[1983 c 102 § 4]; 1975-'76 2nd ex.s. c 34 § 53; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c44.pdf?cite=1974%20ex.s.%20c%2044%20§%203[1974 ex.s. c 44 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c50.pdf?cite=1967%20ex.s.%20c%2050%20§%204[1967 ex.s. c 50 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c92.pdf?cite=1959%20c%2092%20§%205[1959 c 92 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c71.pdf?cite=1941%20c%2071%20§%205[1941 c 71 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c79.pdf?cite=1913%20c%2079%20§%202[1913 c 79 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c124.pdf?cite=1907%20c%20124%20§%2013[1907 c 124 § 13]; Rem. Supp. 1941 § 10040-5; ]

== 18.92.046 - Application of uniform disciplinary act.
The uniform disciplinary act, chapter 18.130 RCW, governs unlicensed practice, the issuance and denial of licenses, and the discipline of licensees under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c150.pdf?cite=1987%20c%20150%20§%2058[1987 c 150 § 58]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c259.pdf?cite=1986%20c%20259%20§%20139[1986 c 259 § 139]; ]

== 18.92.047 - Impaired veterinarian program—Content—License surcharge.
. To implement an impaired veterinarian program as authorized by RCW 18.130.175, the veterinary board of governors shall enter into a contract with a voluntary substance abuse monitoring program. The impaired veterinarian program may include any or all of the following:

.. Contracting with providers of treatment programs;

.. Receiving and evaluating reports of suspected impairment from any source;

.. Intervening in cases of verified impairment;

.. Referring impaired veterinarians to treatment programs;

.. Monitoring the treatment and rehabilitation of impaired veterinarians including those ordered by the board;

.. Providing education, prevention of impairment, posttreatment monitoring, and support of rehabilitated impaired veterinarians; and

.. Performing other related activities as determined by the board.

. A contract entered into under subsection (1) of this section shall be financed by a surcharge of twenty-five dollars on each license issuance or renewal of a new license to be collected by the department of health from every veterinarian licensed under chapter 18.92 RCW. These moneys shall be placed in the health professions account to be used solely for the implementation of the impaired veterinarian program.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2432.SL.pdf?cite=2016%20c%2042%20§%203[2016 c 42 § 3]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20241[1991 c 3 § 241]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c125.pdf?cite=1989%20c%20125%20§%202[1989 c 125 § 2]; ]

== 18.92.051 - Compliance with chapter required.
It is a violation of RCW 18.130.190 for any person to practice the profession of veterinary medicine, surgery, or dentistry in this state, who has not complied with the provisions of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c150.pdf?cite=1987%20c%20150%20§%2059[1987 c 150 § 59]; ]

== 18.92.060 - Licensing exemptions.
Nothing in this chapter applies to:

. Commissioned veterinarians in the United States military services or veterinarians employed by Washington state and federal agencies while performing official duties;

. A person practicing veterinary medicine upon his or her own animal;

. A person advising with respect to or performing the castrating and dehorning of cattle, castrating and docking of sheep, castrating of swine, caponizing of poultry, or artificial insemination of animals;

. [Empty]
.. A person who is a regularly enrolled student in a veterinary school or training course approved under RCW 18.92.015 and performing duties or actions assigned by his or her instructors or working under the direct supervision of a licensed veterinarian during a school vacation period or (b) a person performing assigned duties under the supervision of a veterinarian within the established framework of an internship program recognized by the board;

. A veterinarian regularly licensed in another state consulting with a licensed veterinarian in this state;

. A veterinary technician or veterinary medication clerk acting under the supervision and control of a licensed veterinarian. The practice of a veterinary technician or veterinary medication clerk is limited to the performance of services which are authorized by the board;

. An owner being assisted in practice by his or her employees when employed in the conduct of the owner's business;

. An owner being assisted in practice by some other person gratuitously;

. The implanting in their own animals of any electronic device for identifying animals by established humane societies and animal control organizations that provide appropriate training, as determined by the veterinary board of governors, and/or direct or indirect supervision by a licensed veterinarian;

. The implanting of any electronic device by a public fish and wildlife agency for the identification of fish or wildlife.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2452.SL.pdf?cite=2000%20c%2093%20§%2011[2000 c 93 § 11]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1144-S.SL.pdf?cite=1995%20c%20317%20§%202[1995 c 317 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1266-S.SL.pdf?cite=1993%20c%2078%20§%204[1993 c 78 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c44.pdf?cite=1974%20ex.s.%20c%2044%20§%204[1974 ex.s. c 44 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c50.pdf?cite=1967%20ex.s.%20c%2050%20§%205[1967 ex.s. c 50 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c92.pdf?cite=1959%20c%2092%20§%2013[1959 c 92 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c71.pdf?cite=1941%20c%2071%20§%2020[1941 c 71 § 20]; Rem. Supp. 1941 § 10040-20; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c124.pdf?cite=1907%20c%20124%20§%2015[1907 c 124 § 15]; ]

== 18.92.070 - Applications—Procedure—Qualifications—Eligibility to take examination.
No person, unless registered or licensed to practice veterinary medicine, surgery, and dentistry in this state at the time this chapter shall become operative, shall begin the practice of veterinary medicine, surgery and dentistry without first applying for and obtaining a license for such purpose from the secretary. In order to procure a license to practice veterinary medicine, surgery, and dentistry in the state of Washington, the applicant for such license shall file his or her application at least sixty days prior to date of examination upon a form furnished by the secretary of health, which, in addition to the fee provided by this chapter, shall be accompanied by satisfactory evidence that he or she is at least eighteen years of age and of good moral character, and by official transcripts or other evidence of graduation from a veterinary college satisfactory to and approved by the board. Said application shall be signed by the applicant and sworn to by him or her before some person authorized to administer oaths. When such application and the accompanying evidence are found satisfactory, the secretary shall notify the applicant to appear before the board for the next examination. In addition, applicants shall be subject to grounds for denial or issuance of a conditional license under chapter 18.130 RCW.

Nothing in this chapter shall preclude the board from permitting a person who has completed a portion of his or her educational program as determined by the board, in a veterinary college recognized by the board, to take the examination or any part thereof prior to satisfying the requirements for application for a license: PROVIDED HOWEVER, That no license shall be issued to such applicant until such requirements are satisfied.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20242[1991 c 3 § 242]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c259.pdf?cite=1986%20c%20259%20§%20141[1986 c 259 § 141]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c134.pdf?cite=1982%20c%20134%20§%203[1982 c 134 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c158.pdf?cite=1979%20c%20158%20§%2072[1979 c 158 § 72]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c44.pdf?cite=1974%20ex.s.%20c%2044%20§%205[1974 ex.s. c 44 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c292.pdf?cite=1971%20ex.s.%20c%20292%20§%2028[1971 ex.s. c 292 § 28]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c71.pdf?cite=1941%20c%2071%20§%206[1941 c 71 § 6]; Rem. Supp. 1941 § 10040-6; ]

== 18.92.100 - Examinations—Time of—Subjects—Manner.
Examinations for license to practice veterinary medicine, surgery and dentistry shall be held at least once each year at such times and places as the secretary may authorize and direct. The examination shall be on subjects that are ordinarily included in the curricula of veterinary colleges. All examinees shall be tested by written examination, supplemented by such oral interviews and practical demonstrations as the board deems necessary.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5308-S.SL.pdf?cite=1995%20c%20198%20§%2014[1995 c 198 § 14]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20243[1991 c 3 § 243]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c50.pdf?cite=1967%20ex.s.%20c%2050%20§%206[1967 ex.s. c 50 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c92.pdf?cite=1959%20c%2092%20§%207[1959 c 92 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c71.pdf?cite=1941%20c%2071%20§%207[1941 c 71 § 7]; Rem. Supp. 1941 § 10040-7; ]

== 18.92.115 - Reexamination—Fee.
Any applicant who shall fail to secure the required grade in his or her first examination may take the next regular veterinary examination. The fee for reexamination shall be determined by the secretary as provided in RCW 43.70.250.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20499[2011 c 336 § 499]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20244[1991 c 3 § 244]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%2071[1985 c 7 § 71]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c30.pdf?cite=1975%201st%20ex.s.%20c%2030%20§%2082[1975 1st ex.s. c 30 § 82]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c50.pdf?cite=1967%20ex.s.%20c%2050%20§%207[1967 ex.s. c 50 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c92.pdf?cite=1959%20c%2092%20§%208[1959 c 92 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c71.pdf?cite=1941%20c%2071%20§%2010[1941 c 71 § 10]; Rem. Supp. 1941 § 10040-10; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c124.pdf?cite=1907%20c%20124%20§%2017[1907 c 124 § 17]; ]

== 18.92.120 - License—Temporary certificates, restrictions.
Any person who shall make application for examination, as provided by RCW 18.92.070, and who has not previously failed to pass the veterinary examination, and whose application is found satisfactory by the secretary, may be given a temporary certificate to practice veterinary medicine, surgery and dentistry valid only until the results of the next examination for licenses are available. In addition, applicants shall be subject to the grounds for denial or issuance of a conditional license under chapter 18.130 RCW. No more than one temporary certificate may be issued to any applicant. Such permittee shall be employed by a licensed veterinary practitioner or by the state of Washington.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20245[1991 c 3 § 245]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c259.pdf?cite=1986%20c%20259%20§%20142[1986 c 259 § 142]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c50.pdf?cite=1967%20ex.s.%20c%2050%20§%208[1967 ex.s. c 50 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c92.pdf?cite=1959%20c%2092%20§%209[1959 c 92 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c71.pdf?cite=1941%20c%2071%20§%2011[1941 c 71 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c124.pdf?cite=1907%20c%20124%20§%2011[1907 c 124 § 11]; Rem. Supp. 1941 § 10040-11; ]

== 18.92.125 - Veterinary technicians or veterinary medication clerks.
No veterinarian who uses the services of a veterinary technician or veterinary medication clerk shall be considered as aiding and abetting any unlicensed person to practice veterinary medicine. A veterinarian retains professional and personal responsibility for any act which constitutes the practice of veterinary medicine as defined in this chapter when performed by a veterinary technician or veterinary medication clerk in his or her employ.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2452.SL.pdf?cite=2000%20c%2093%20§%2012[2000 c 93 § 12]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1266-S.SL.pdf?cite=1993%20c%2078%20§%205[1993 c 78 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c259.pdf?cite=1986%20c%20259%20§%20143[1986 c 259 § 143]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c102.pdf?cite=1983%20c%20102%20§%205[1983 c 102 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c44.pdf?cite=1974%20ex.s.%20c%2044%20§%206[1974 ex.s. c 44 § 6]; ]

== 18.92.128 - Veterinary technician license.
The board shall issue a veterinary technician license to an individual who has:

. Successfully completed required examinations administered or approved by the board; and

. Successfully completed a posthigh school course approved by the board in the care and treatment of animals.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6745.SL.pdf?cite=2010%20c%20123%20§%202[2010 c 123 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6745.SL.pdf?cite=2010%20c%20123%20§%201[2010 c 123 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1331.SL.pdf?cite=2007%20c%20235%20§%202[2007 c 235 § 2]; ]

== 18.92.130 - License—Reciprocity with other states—Fee.
Any person who has been lawfully licensed to practice veterinary medicine, surgery, and dentistry in another state or territory which has and maintains a standard for the practice of veterinary medicine, surgery and dentistry which is substantially the same as that maintained in this state, and who has been lawfully and continuously engaged in the practice of veterinary medicine, surgery and dentistry for two years or more immediately before filing his or her application to practice in this state and who shall submit to the secretary a duly attested certificate from the examining board of the state or territory in which he or she is registered, certifying to the fact of his or her registration and of his or her being a person of good moral character and of professional attainments, may upon the payment of the fee as provided herein, be granted a license to practice veterinary medicine, surgery and dentistry in this state, without being required to take an examination: PROVIDED, HOWEVER, That no license shall be issued to any applicant, unless the state or territory from which such certificate has been granted to such applicant shall have extended a like privilege to engage in the practice of veterinary medicine, surgery and dentistry within its own borders to veterinarians heretofore and hereafter licensed by this state, and removing to such other state: AND PROVIDED FURTHER, That the secretary of health shall have power to enter into reciprocal relations with other states whose requirements are substantially the same as those provided herein. The board shall make recommendations to the secretary upon all requests for reciprocity.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20246[1991 c 3 § 246]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c92.pdf?cite=1959%20c%2092%20§%2010[1959 c 92 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c71.pdf?cite=1941%20c%2071%20§%2012[1941 c 71 § 12]; Rem. Supp. 1941 § 10040-12; ]

== 18.92.135 - License to practice specialized veterinary medicine.
. The department may issue a license to practice specialized veterinary medicine in this state to a veterinarian who:

.. Submits an application on a form provided by the secretary for a license in a specialty area recognized by the board by rule;

.. Holds a current certification as a diplomate of a national specialty board or college recognized by the board by rule in the specialty area for which application is submitted;

.. Is not subject to license investigation, suspension, revocation, or other disciplinary action in any state, United States territory, or province of Canada;

.. Has successfully completed an examination established by the board regarding this state's laws and rules regulating the practice of veterinary medicine; and

.. Provides other information and verification required by the board.

. A veterinarian licensed to practice specialized veterinary medicine shall not practice outside his or her licensed specialty unless he or she meets licensing requirements established for practicing veterinary medicine, surgery, and dentistry under RCW 18.92.070 and 18.92.100.

. The board shall determine by rule the limits of the practice of veterinary medicine, surgery, and dentistry represented by a license to practice specialized veterinary medicine.

. The board may deny, revoke, suspend, or modify a license to practice specialized veterinary medicine if the national specialty board or college certifying the licensee denies, revokes, suspends, modifies, withdraws, or otherwise limits the certification or if the certification expires.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1960-S.SL.pdf?cite=1991%20c%20332%20§%2041[1991 c 332 § 41]; ]

== 18.92.140 - License—Procedures, requirements, fees.
Each person now qualified to practice veterinary medicine, surgery, and dentistry, licensed as a veterinary technician, or registered as a veterinary medication clerk in this state or who becomes licensed or registered to engage in practice shall comply with administrative procedures, administrative requirements, and fees determined as provided in RCW 43.70.250 and 43.70.280.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1331.SL.pdf?cite=2007%20c%20235%20§%206[2007 c 235 § 6]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2452.SL.pdf?cite=2000%20c%2093%20§%2013[2000 c 93 § 13]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2079[1996 c 191 § 79]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1266-S.SL.pdf?cite=1993%20c%2078%20§%206[1993 c 78 § 6]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20247[1991 c 3 § 247]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%2072[1985 c 7 § 72]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c102.pdf?cite=1983%20c%20102%20§%206[1983 c 102 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c71.pdf?cite=1941%20c%2071%20§%2016[1941 c 71 § 16]; Rem. Supp. 1941 § 10040-16. FORMER PARTS OF SECTION:   1941 c 71 § 17; Rem. Supp. 1941 § 10040-17, now codified as RCW  18.92.142.  1941 c 71 § 19, part; Rem. Supp. 1941 § 10040-19, part, now codified as RCW  18.92.145; ]

== 18.92.145 - License, certificates of registration, permit, examination, and renewal fees.
Administrative procedures, administrative requirements, and fees shall be established as provided in RCW 43.70.250 and 43.70.280 for the issuance, renewal, or administration of the following licenses, certificates of registration, permits, duplicate licenses, renewals, or examination:

. For a license to practice veterinary medicine, surgery, and dentistry issued upon an examination given by the examining board;

. For a license to practice veterinary medicine, surgery, and dentistry issued upon the basis of a license issued in another state;

. For a license as a veterinary technician;

. For a certificate of registration as a veterinary medication clerk;

. For a temporary permit to practice veterinary medicine, surgery, and dentistry. The temporary permit fee shall be accompanied by the full amount of the examination fee; and

. For a license to practice specialized veterinary medicine.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1331.SL.pdf?cite=2007%20c%20235%20§%207[2007 c 235 § 7]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2452.SL.pdf?cite=2000%20c%2093%20§%2014[2000 c 93 § 14]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2080[1996 c 191 § 80]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1266-S.SL.pdf?cite=1993%20c%2078%20§%207[1993 c 78 § 7]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1960-S.SL.pdf?cite=1991%20c%20332%20§%2042[1991 c 332 § 42]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20248[1991 c 3 § 248]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%2073[1985 c 7 § 73]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c102.pdf?cite=1983%20c%20102%20§%207[1983 c 102 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c30.pdf?cite=1975%201st%20ex.s.%20c%2030%20§%2084[1975 1st ex.s. c 30 § 84]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c266.pdf?cite=1971%20ex.s.%20c%20266%20§%2020[1971 ex.s. c 266 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c50.pdf?cite=1967%20ex.s.%20c%2050%20§%209[1967 ex.s. c 50 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c92.pdf?cite=1959%20c%2092%20§%2012[1959 c 92 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c71.pdf?cite=1941%20c%2071%20§%2019[1941 c 71 § 19]; Rem. Supp. 1941 § 10040-19; 1907 c 124 §§ 9, 10; ]

== 18.92.150 - License—Display.
Every person holding a license under the provisions of this chapter shall conspicuously display it in his or her principal place of business, together with the annual renewal license certificate.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20500[2011 c 336 § 500]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c71.pdf?cite=1941%20c%2071%20§%2018[1941 c 71 § 18]; Rem. Supp. 1941 § 10040-18; ]

== 18.92.230 - Use of another's license or diploma a felony.
Any person filing or attempting to file, as his or her own, the diploma or license of another is guilty of forgery under RCW 9A.60.020.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20139[2003 c 53 § 139]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c71.pdf?cite=1941%20c%2071%20§%2023[1941 c 71 § 23]; Rem. Supp. 1941 § 10040-23; ]

== 18.92.240 - Violations generally—Penalty.
Violation of any of the provisions of this chapter, or of any rule or regulation made pursuant thereto, shall constitute a misdemeanor and punishable by fine of not less than fifty dollars.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c71.pdf?cite=1941%20c%2071%20§%2024[1941 c 71 § 24]; Rem. Supp. 1941 § 10040-24; ]

== 18.92.250 - Intent—Veterinary services—Low-income households.
The legislature recognizes that low-income households may not receive needed veterinary services for household pets. It is the intent of the legislature to allow qualified animal control agencies and humane societies to provide veterinary services to low-income members of our communities. It is not the intent of the legislature to allow these agencies to provide veterinary services to the public at large.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5004-S.SL.pdf?cite=2019%20c%20142%20§%201[2019 c 142 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2002%20c%20157%20§%201[2002 c 157 § 1]; ]

== 18.92.260 - Animal care societies/nonprofit humane societies—Low-income households—License required—Rule-making authority—Uniform disciplinary act—Registration—Fees.
. [Empty]
.. Subject to the limitations in this section, animal care and control agencies as defined in RCW 16.52.011 and nonprofit humane societies, that have qualified under section 501(c)(3) of the internal revenue code may provide veterinary services to animals owned by qualified low-income households. A veterinarian or veterinary technician acting within his or her scope of practice must perform the veterinary services. For purposes of this section, "low-income household" means the same as in RCW 43.185A.010.

.. Animal control agencies and nonprofit humane societies, receiving any animals on an emergency basis, may provide emergency care where there is an unexpected, serious occurrence or situation that urgently requires prompt action in order to prevent an animal's death or permanent injury of the animal.

.. Animal control agencies and nonprofit humane societies may provide veterinary care for sick animals up to thirty days postadoption.

.. Any local ordinance addressing the needs under this section that was approved by the voters and is in effect on July 1, 2003, remains in effect.

. Veterinarians, veterinary technicians, and veterinary medication clerks employed at these facilities must be licensed under this chapter. No officer, director, supervisor, or any other individual associated with an animal care or control agency or nonprofit humane society owning and operating a veterinary medical facility may impose any terms or conditions of employment or direct or attempt to direct an employed veterinarian in any way that interferes with the free exercise of the veterinarian's professional judgment or infringes upon the utilization of his or her professional skills.

. Veterinarians, veterinary technicians, veterinary medication clerks, and animal control agencies and humane societies acting under this section shall, for purposes of providing the veterinary services, meet the requirements established under this chapter and are subject to the rules adopted by the veterinary board of governors in the same fashion as any licensed veterinarian or veterinary medical facility in the state.

. The Washington state veterinary board of governors shall adopt rules to:

.. Establish registration and registration renewal requirements;

.. Govern the purchase and use of drugs for the veterinary services authorized under this section;

.. Establish annual reporting requirements that demonstrate the animal care and control facilities and nonprofit humane societies are serving only low-income households as defined in RCW 43.185A.010; and

.. Ensure that agencies and societies are in compliance with this section.

. The veterinary medical service authority granted by registration under this section may be denied, suspended, revoked, or conditioned by a determination of the board of governors for any act of noncompliance with this chapter. The uniform disciplinary act, chapter 18.130 RCW, governs unregistered operation, the issuance and denial of registrations, and the discipline of registrants under this section.

. No animal control agency or humane society may operate under this chapter without registering with the department. An application for registration shall be made upon forms provided by the department and shall include the information the department reasonably requires, as provided by RCW 43.70.280. The department shall establish registration and renewal fees as provided by RCW 43.70.250. A registration fee shall accompany each application for registration or renewal.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5004-S.SL.pdf?cite=2019%20c%20142%20§%202[2019 c 142 § 2]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2002%20c%20157%20§%202[2002 c 157 § 2]; ]

== 18.92.270 - Higher education facilities—Dogs and cats used for research—Adoption.
. A higher education facility that receives public money, including tax exempt status, or a facility that provides research in collaboration with a higher education facility, that utilizes dogs or cats for scientific, educational, or research purposes, upon conclusion of a dog or cat's use for scientific, educational, or research purposes shall:

.. Have the facility's attending veterinarian or designee assess the health of the dog or cat and determine if the dog or cat is suitable for adoption, consistent with guidelines promulgated by the American veterinary medical association; and

.. Make reasonable efforts to offer the dog or cat for adoption, when the dog or cat is deemed suitable for adoption, through the facility's own adoption program or through an animal care and control agency or an animal rescue group as defined in RCW 82.04.040. A facility that offers dogs or cats for adoption to an animal care and control agency or an animal rescue group under this section may enter into an agreement to facilitate adoptions.

. Nothing in this section shall:

.. Create a duty upon an animal care and control agency or an animal rescue group to accept a dog or cat offered for adoption by a research facility; or

.. Prohibit a facility from completing scientific research or educational use prior to making a suitability for adoption determination.

. A research facility that provides a dog or cat for adoption pursuant to this section is immune from any civil liability for acts or omissions relating to the adoption of a dog or cat pursuant to subsection (1) of this section, other than acts constituting willful or wanton misconduct.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5212-S.SL.pdf?cite=2019%20c%20184%20§%201[2019 c 184 § 1]; ]

== 18.92.280 - Suicide prevention training program—Required education.
. The board, in consultation with the University of Washington's forefront suicide prevention center of excellence and affected professional associations, shall develop a suicide prevention training program for veterinarians and veterinary technicians by June 30, 2022. The program must:

.. Recognize that veterinarians treat animal patients and have limited interaction with animal patient owners;

.. Focus on mental health and well-being;

.. Include general content on suicide risk, prevention, and resourcing, and specific content on imminent harm by lethal means; and

.. Be three hours in length.

. Beginning July 1, 2022, all veterinarians and veterinary technicians shall complete the training program developed by the board. The training must be completed during the first full continuing education reporting period after July 1, 2022, or during the first full continuing education reporting period after initial licensure, whichever is later. The board may exempt any veterinarian or veterinary technician who completed training substantially equivalent to the training developed under subsection (1) of this section in the three years prior to July 1, 2022.

. The hours spent completing training under this section count toward meeting any applicable continuing education requirements for veterinarians and veterinary technicians.

. Nothing in this section may be interpreted to expand or limit the scope of practice of a veterinarian or veterinary technician.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2411-S.SL.pdf?cite=2020%20c%20229%20§%202[2020 c 229 § 2]; ]

