= 18.52C - Nursing pools.
:toc:

== 18.52C.010 - Legislative intent.
The legislature intends to protect the public's right to high quality health care by assuring that nursing pools employ, procure or refer competent and qualified health care or long-term care personnel, and that such personnel are provided to health care facilities, agencies, or individuals in a way to meet the needs of residents and patients.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1850-S2.SL.pdf?cite=1997%20c%20392%20§%20526[1997 c 392 § 526]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c243.pdf?cite=1988%20c%20243%20§%201[1988 c 243 § 1]; ]

== 18.52C.020 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Adult family home" means a residential home licensed pursuant to chapter 70.128 RCW.

. "Health care facility" means a nursing home, hospital, hospice care facility, home health care agency, hospice agency, assisted living facility, group home, or other entity for the delivery of health care or long-term care services, including chore services provided under chapter 74.39A RCW.

. "Nursing home" means any nursing home facility licensed pursuant to chapter 18.52 RCW.

. "Nursing pool" means any person engaged in the business of providing, procuring, or referring health care or long-term care personnel for temporary employment in health care facilities, such as licensed nurses or practical nurses, nursing assistants, and chore service providers. "Nursing pool" does not include an individual who only engages in providing his or her own services.

. "Person" includes an individual, firm, corporation, partnership, or association.

. "Secretary" means the secretary of the department of health.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2056-S.SL.pdf?cite=2012%20c%2010%20§%2036[2012 c 10 § 36]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1320-S.SL.pdf?cite=2001%20c%20319%20§%203[2001 c 319 § 3]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1850-S2.SL.pdf?cite=1997%20c%20392%20§%20527[1997 c 392 § 527]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20130[1991 c 3 § 130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c243.pdf?cite=1988%20c%20243%20§%202[1988 c 243 § 2]; ]

== 18.52C.030 - Registration required.
A person who operates a nursing pool shall register the pool with the secretary. Each separate location of the business of a nursing pool shall have a separate registration.

The secretary shall establish administrative procedures, administrative requirements, and fees as provided in RCW 43.70.250 and 43.70.280.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2028[1996 c 191 § 28]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20131[1991 c 3 § 131]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c243.pdf?cite=1988%20c%20243%20§%203[1988 c 243 § 3]; ]

== 18.52C.040 - Duties of nursing pool—Application of uniform disciplinary act—Criminal background checks.
. The nursing pool shall document that each temporary employee or referred independent contractor provided or referred to health care facilities currently meets the applicable minimum state credentialing requirements.

. The nursing pool shall not require, as a condition of employment or referral, that employees or independent contractors of the nursing pool recruit new employees or independent contractors for the nursing pool from among the permanent employees of the health care facility to which the nursing pool employee or independent contractor has been assigned or referred.

. The nursing pool shall carry professional and general liability insurance to insure against any loss or damage occurring, whether professional or otherwise, as the result of the negligence of its employees, agents or independent contractors for acts committed in the course of their employment with the nursing pool: PROVIDED, That a nursing pool that only refers self-employed, independent contractors to health care facilities shall carry professional and general liability insurance to cover its own liability as a nursing pool which refers self-employed, independent contractors to health care facilities: AND PROVIDED FURTHER, That it shall require, as a condition of referral, that self-employed, independent contractors carry professional and general liability insurance to insure against loss or damage resulting from their own acts committed in the course of their own employment by a health care facility.

. The uniform disciplinary act, chapter 18.130 RCW, shall govern the issuance and denial of registration and the discipline of persons registered under this chapter. The secretary shall be the disciplinary authority under this chapter.

. The nursing pool shall conduct a criminal background check on all employees and independent contractors as required under RCW 43.43.842 prior to employment or referral of the employee or independent contractor.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1850-S2.SL.pdf?cite=1997%20c%20392%20§%20528[1997 c 392 § 528]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20132[1991 c 3 § 132]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c243.pdf?cite=1988%20c%20243%20§%204[1988 c 243 § 4]; ]

== 18.52C.050 - Registration prerequisite to state reimbursement.
No state agency shall allow reimbursement for the use of temporary health care personnel from nursing pools that are not registered pursuant to this chapter: PROVIDED, That individuals directly retained by a health care facility without intermediaries may be reimbursed.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c243.pdf?cite=1988%20c%20243%20§%205[1988 c 243 § 5]; ]

