= 18.54 - Optometry board.
:toc:

== 18.54.010 - Definitions.
Unless the context clearly indicates otherwise, the terms used in this chapter take their meanings as follows:

. "Board" means the optometry board;

. "License" means a certificate or permit to practice optometry as provided in *RCW 18.53.020 as amended from time to time;

. "Members" means members of the optometry board.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c25.pdf?cite=1963%20c%2025%20§%201[1963 c 25 § 1]; ]

== 18.54.020 - Examining committee reconstituted as optometry board.
The examining committee, heretofore created pursuant to RCW 43.24.060, is reorganized and reconstituted as the optometry board.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c25.pdf?cite=1963%20c%2025%20§%202[1963 c 25 § 2]; ]

== 18.54.030 - Composition—Appointments—Qualifications—Terms—Vacancies.
The initial composition of the optometry board includes the three members of the examining committee for optometry plus two more optometrists to be appointed by the governor.

The governor must make all appointments to the optometry board. Only optometrists who are citizens of the United States, residents of this state, having been licensed to practice and practicing optometry in this state for a period of at least four years immediately preceding the effective date of appointment, and who have no connection with any school or college embracing the teaching of optometry or with any optical supply business may be appointed.

The governor may set the terms of office of the initial board at his or her discretion, to establish the following perpetual succession: The terms of the initial board include one position for one year, two for two years, and two for three years; and upon the expiration of the terms of the initial board, all appointments are for three years.

In addition to the members specified in this section, the governor shall appoint a consumer member of the board, who shall serve for a term of three years.

In the event that a vacancy occurs on the board in the middle of an appointee's term, the governor must appoint a successor for the unexpired portion of the term only.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20489[2011 c 336 § 489]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c279.pdf?cite=1984%20c%20279%20§%2054[1984 c 279 § 54]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c25.pdf?cite=1963%20c%2025%20§%203[1963 c 25 § 3]; ]

== 18.54.040 - Officers.
The board must elect a chair and secretary from its members, to serve for a term of one year or until their successors are elected and qualified.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20490[2011 c 336 § 490]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c25.pdf?cite=1963%20c%2025%20§%204[1963 c 25 § 4]; ]

== 18.54.050 - Meetings.
The board must meet at least once yearly or more frequently upon call of the chair or the secretary of health at such times and places as the chair or the secretary of health may designate by giving three days' notice or as otherwise required by RCW 42.30.075.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20491[2011 c 336 § 491]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20139[1991 c 3 § 139]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c175.pdf?cite=1989%20c%20175%20§%2065[1989 c 175 § 65]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c158.pdf?cite=1979%20c%20158%20§%2048[1979 c 158 § 48]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c69.pdf?cite=1975%201st%20ex.s.%20c%2069%20§%209[1975 1st ex.s. c 69 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c25.pdf?cite=1963%20c%2025%20§%205[1963 c 25 § 5]; ]

== 18.54.060 - Quorum.
Three members constitute a quorum for the transaction of business of the board.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c25.pdf?cite=1963%20c%2025%20§%206[1963 c 25 § 6]; ]

== 18.54.070 - Powers and duties—Examinations—Rules.
The board has the following powers and duties:

. To develop and administer, or approve, or both, a licensure examination. The board may approve an examination prepared or administered by a private testing agency or association of licensing authorities.

. The board shall adopt rules and regulations to promote safety, protection and the welfare of the public, to carry out the purposes of this chapter, to aid the board in the performance of its powers and duties, and to govern the practice of optometry.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5308-S.SL.pdf?cite=1995%20c%20198%20§%207[1995 c 198 § 7]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20140[1991 c 3 § 140]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c259.pdf?cite=1986%20c%20259%20§%2084[1986 c 259 § 84]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c158.pdf?cite=1979%20c%20158%20§%2049[1979 c 158 § 49]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c69.pdf?cite=1975%201st%20ex.s.%20c%2069%20§%2010[1975 1st ex.s. c 69 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c25.pdf?cite=1963%20c%2025%20§%207[1963 c 25 § 7]; ]

== 18.54.076 - Application of uniform disciplinary act.
The uniform disciplinary act, chapter 18.130 RCW, governs unlicensed practice, the issuance and denial of licenses, and the discipline of licensees under this chapter and chapter 18.53 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c150.pdf?cite=1987%20c%20150%20§%2037[1987 c 150 § 37]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c259.pdf?cite=1986%20c%20259%20§%2079[1986 c 259 § 79]; ]

== 18.54.090 - Administrative procedures—Minimum fees.
The board is an administrative agency of the state of Washington, and the provisions of the administrative procedure act, chapter 34.05 RCW as amended from time to time, govern the conduct and proceedings of the board. Nothing in this chapter shall be construed to give the board the power to set or recommend a minimum schedule of fees to be charged by licensed optometrist.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c25.pdf?cite=1963%20c%2025%20§%209[1963 c 25 § 9]; ]

== 18.54.130 - Compensation and travel expenses of members.
Members of the board are entitled to receive their travel expenses in accordance with RCW 43.03.050 and 43.03.060. Each member of the board will also be compensated in accordance with RCW 43.03.240.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c287.pdf?cite=1984%20c%20287%20§%2041[1984 c 287 § 41]; 1975-'76 2nd ex.s. c 34 § 39; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c188.pdf?cite=1967%20c%20188%20§%203[1967 c 188 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c25.pdf?cite=1963%20c%2025%20§%2013[1963 c 25 § 13]; ]

== 18.54.140 - Board may draw from health professions account.
Notwithstanding any other provisions of law, rule or regulation, the board may draw from the health professions account on vouchers approved by the secretary of health, so much money as is necessary to carry into effect, to administer, and to enforce the provisions of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20141[1991 c 3 § 141]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c168.pdf?cite=1983%20c%20168%20§%209[1983 c 168 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c158.pdf?cite=1979%20c%20158%20§%2050[1979 c 158 § 50]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c69.pdf?cite=1975%201st%20ex.s.%20c%2069%20§%2012[1975 1st ex.s. c 69 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c25.pdf?cite=1963%20c%2025%20§%2014[1963 c 25 § 14]; ]

== 18.54.150 - Devolution of powers relating to revocation of certificates.
All powers previously vested in the director of licenses under the provisions of RCW 18.53.100 are vested in the optometry board.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c25.pdf?cite=1963%20c%2025%20§%2015[1963 c 25 § 15]; ]

== 18.54.900 - Short title.
This act may be known and cited as the "optometry board act."

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c25.pdf?cite=1963%20c%2025%20§%2016[1963 c 25 § 16]; ]

== 18.54.920 - RCW  43.24.060 and  43.24.120 not applicable to optometry.
The provisions of RCW 43.24.060 and 43.24.120 are not applicable to the licensing and regulation of the practice of optometry.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2200.SL.pdf?cite=1999%20c%20240%20§%206[1999 c 240 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c25.pdf?cite=1963%20c%2025%20§%2018[1963 c 25 § 18]; ]

