= 18.36A - Naturopathy.
:toc:

== 18.36A.010 - Intent.
The legislature finds that it is necessary to regulate the practice of naturopaths in order to protect the public health, safety, and welfare. It is the legislature's intent that only individuals who meet and maintain minimum standards of competence and conduct may provide service to the public.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c447.pdf?cite=1987%20c%20447%20§%201[1987 c 447 § 1]; ]

== 18.36A.020 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Board" means the board of naturopathy created in RCW 18.36A.150.

. "Colon hydrotherapist" means a person certified under this chapter to perform colon hydrotherapy pursuant to an affiliation with one or more naturopaths.

. "Colon hydrotherapy" means the performance of enemas or colonic irrigation.

. "Common diagnostic procedures" means the use of venipuncture consistent with the practice of naturopathic medicine, commonly used diagnostic modalities consistent with naturopathic practice, health history taking, physical examination, radiography, examination of body orifices excluding endoscopy, laboratory medicine, and obtaining samples of human tissues, but excluding incision or excision beyond that which is authorized as a minor office procedure.

. "Department" means the department of health.

. "Educational program" means an accredited program preparing persons for the practice of naturopathic medicine.

. "Homeopathy" means a system of medicine based on the use of infinitesimal doses of medicines capable of producing symptoms similar to those of the disease treated, as listed in the homeopathic pharmacopeia of the United States.

. "Hygiene and immunization" means the use of such preventative techniques as personal hygiene, asepsis, public health, and immunizations, to the extent allowed by rule.

. "Manual manipulation" or "mechanotherapy" means manipulation of a part or the whole of the body by hand or by mechanical means.

. "Minor office procedures" means care and procedures incident thereto of superficial lacerations, lesions, and abrasions, and the removal of foreign bodies located in superficial structures, not to include the eye; and the use of antiseptics and topical or local anesthetics in connection therewith. "Minor office procedures" also includes intramuscular, intravenous, subcutaneous, and intradermal injections of substances consistent with the practice of naturopathic medicine and in accordance with rules established by the secretary.

. "Naturopath" means an individual licensed under this chapter.

. "Naturopathic medicines" means vitamins; minerals; botanical medicines; homeopathic medicines; hormones; and those legend drugs and controlled substances consistent with naturopathic medical practice in accordance with rules established by the board. Controlled substances are limited to codeine and testosterone products that are contained in Schedules III, IV, and V in chapter 69.50 RCW.

. "Nutrition and food science" means the prevention and treatment of disease or other human conditions through the use of foods, water, herbs, roots, bark, or natural food elements.

. "Physical modalities" means use of physical, chemical, electrical, and other modalities that do not exceed those used as of July 22, 2011, in minor office procedures or common diagnostic procedures, including but not limited to heat, cold, air, light, water in any of its forms, sound, massage, and therapeutic exercise.

. "Radiography" means the ordering, but not the interpretation, of radiographic diagnostic and other imaging studies and the taking and interpretation of standard radiographs.

. "Secretary" means the secretary of health or the secretary's designee.

. "Suggestion" means techniques including but not limited to counseling, biofeedback, and hypnosis.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5124.SL.pdf?cite=2021%20c%20179%20§%202l[2021 c 179 § 2l]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1181.SL.pdf?cite=2011%20c%2041%20§%203[2011 c 41 § 3]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5152-S.SL.pdf?cite=2011%20c%2040%20§%201[2011 c 40 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1546.SL.pdf?cite=2005%20c%20158%20§%201[2005 c 158 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2087[1991 c 3 § 87]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c447.pdf?cite=1987%20c%20447%20§%204[1987 c 447 § 4]; ]

== 18.36A.030 - License required.
. No person may practice naturopathy or represent himself or herself as a naturopath without first applying for and receiving a license from the secretary to practice naturopathy.

. A person represents himself or herself as a naturopath when that person adopts or uses any title or any description of services that incorporates one or more of the following terms or designations: Naturopath, naturopathy, naturopathic, naturopathic physician, ND, or doctor of naturopathic medicine.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1181.SL.pdf?cite=2011%20c%2041%20§%204[2011 c 41 § 4]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2088[1991 c 3 § 88]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c447.pdf?cite=1987%20c%20447%20§%202[1987 c 447 § 2]; ]

== 18.36A.040 - Scope of practice.
Naturopathic medicine is the practice by naturopaths of the art and science of the diagnosis, prevention, and treatment of disorders of the body by stimulation or support, or both, of the natural processes of the human body. A naturopath is responsible and accountable to the consumer for the quality of naturopathic care rendered.

The practice of naturopathic medicine includes manual manipulation (mechanotherapy), the prescription, administration, dispensing, and use, except for the treatment of malignancies, of nutrition and food science, physical modalities, minor office procedures, homeopathy, naturopathic medicines, hygiene and immunization, contraceptive devices, common diagnostic procedures, and suggestion; however, nothing in this chapter shall prohibit consultation and treatment of a patient in concert with a practitioner licensed under chapter 18.57 or 18.71 RCW. No person licensed under this chapter may employ the term "chiropractic" to describe any services provided by a naturopath under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5152-S.SL.pdf?cite=2011%20c%2040%20§%202[2011 c 40 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1546.SL.pdf?cite=2005%20c%20158%20§%202[2005 c 158 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2089[1991 c 3 § 89]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c246.pdf?cite=1988%20c%20246%20§%201[1988 c 246 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c447.pdf?cite=1987%20c%20447%20§%203[1987 c 447 § 3]; ]

== 18.36A.050 - Application of chapter—Exemptions.
Nothing in this chapter shall be construed to prohibit or restrict:

. The practice of a profession by individuals who are licensed, certified, or registered under other laws of this state who are performing services within their authorized scope of practice;

. The practice of naturopathic medicine by an individual employed by the government of the United States while the individual is engaged in the performance of duties prescribed for him or her by the laws and regulations of the United States;

. The practice of naturopathic medicine by students enrolled in a school approved by the secretary. The performance of services shall be pursuant to a course of instruction or assignments from an instructor and under the supervision of the instructor. The instructor shall be a naturopath licensed pursuant to this chapter; or

. The practice of oriental medicine or oriental herbology, or the rendering of other dietary or nutritional advice.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2090[1991 c 3 § 90]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c447.pdf?cite=1987%20c%20447%20§%205[1987 c 447 § 5]; ]

== 18.36A.060 - Powers of secretary—Application of uniform disciplinary act.
In addition to any other authority provided by law, the secretary may:

. Set all license and certificate, examination, and renewal fees in accordance with RCW 43.70.250;

. Establish forms and procedures necessary to administer this chapter;

. Issue a license or certificate to any applicant who has met the education, training, and examination requirements for licensure or certification and deny a license or certification to applicants who do not meet the minimum qualifications for licensure or certification; except that denial of licenses or certificates based on unprofessional conduct or impaired practice shall be governed by the uniform disciplinary act, chapter 18.130 RCW;

. Hire clerical, administrative, and investigative staff as needed to implement and administer this chapter and to hire individuals, including those licensed under this chapter, to serve as examiners or consultants as necessary to implement and administer this chapter;

. Maintain the official department record of all applicants, licensees, and certified persons; and

. Conduct a hearing on an appeal of a denial of a license or certificate based on the applicant's failure to meet the minimum qualifications for licensure or certification. The hearing shall be conducted pursuant to chapter 34.05 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5124.SL.pdf?cite=2021%20c%20179%20§%203[2021 c 179 § 3]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1181.SL.pdf?cite=2011%20c%2041%20§%205[2011 c 41 § 5]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2091[1991 c 3 § 91]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c447.pdf?cite=1987%20c%20447%20§%206[1987 c 447 § 6]; ]

== 18.36A.080 - Civil immunity.
The secretary, members of the board, or individuals acting on their behalf, are immune from suit in any civil action based on any act performed in the course of their duties.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1181.SL.pdf?cite=2011%20c%2041%20§%206[2011 c 41 § 6]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2093[1991 c 3 § 93]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c447.pdf?cite=1987%20c%20447%20§%208[1987 c 447 § 8]; ]

== 18.36A.090 - Requirements for licensure.
The department shall issue a license to any applicant who meets the following requirements:

. Successful completion of an educational program approved by the board, the minimum standard of which shall be the successful completion of a doctorate degree program in naturopathy which includes a minimum of two hundred postgraduate hours in the study of mechanotherapy from an approved educational program, or successful completion of equivalent alternate training that meets the criteria established by the board. The requirement for two hundred postgraduate hours in the study of mechanotherapy shall expire June 30, 1989;

. Successful completion of any equivalent experience requirement established by the board;

. Successful completion of an examination administered or approved by the board;

. Good moral character; and

. Not having engaged in unprofessional conduct or being unable to practice with reasonable skill and safety as a result of a physical or mental impairment.

The board shall establish what constitutes adequate proof of meeting the above requirements. Any person holding a valid license to practice drugless therapeutics under chapter 18.36 RCW upon January 1, 1988, shall be deemed licensed pursuant to this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1181.SL.pdf?cite=2011%20c%2041%20§%207[2011 c 41 § 7]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2094[1991 c 3 § 94]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c447.pdf?cite=1987%20c%20447%20§%209[1987 c 447 § 9]; ]

== 18.36A.095 - Colon hydrotherapist certification requirements.
. Beginning July 1, 2022, the secretary shall issue a certification as a colon hydrotherapist to any applicant who:

.. Has completed education and training requirements established by the board. At a minimum, education and training requirements must address proper technique, the use of appropriate equipment, and safety and consent procedures; and

.. Has successfully passed an examination approved by the board.

. The board may recognize certification or accreditation by a professional organization as satisfying any of the requirements in subsection (1) of this section if the organization's standards are substantially equivalent to or more stringent than those established under subsection (1) of this section.

. A colon hydrotherapist may not practice colon hydrotherapy unless the colon hydrotherapist has established an affiliation with one or more naturopaths licensed under this chapter. A colon hydrotherapist must submit the names of all naturopaths with which the colon hydrotherapist is affiliated to the board on a schedule established by the board. A colon hydrotherapist may practice in a location other than the office of a naturopath. A colon hydrotherapist may only perform colon hydrotherapy on patients who have been referred to the colon hydrotherapist by a naturopath with whom the colon hydrotherapist is affiliated and only according to the plan of care delegated from the naturopath to the colon hydrotherapist.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5124.SL.pdf?cite=2021%20c%20179%20§%201[2021 c 179 § 1]; ]

== 18.36A.100 - Standards for approval of educational programs.
. The board shall establish by rule the standards for approval of educational programs and alternate training and may contract with individuals or organizations having expertise in the profession and/or in education to report to the board the information necessary for the board to evaluate the educational programs. The standards for approval shall be based on the minimal competencies necessary for safe practice. The standards and procedures for approval shall apply equally to educational programs and equivalent alternate training within the United States and those in foreign jurisdictions.

. Each educational program requesting approval shall pay all administrative costs for the educational program evaluation, including, but not limited to, costs for site evaluation.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1181.SL.pdf?cite=2011%20c%2041%20§%208[2011 c 41 § 8]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2095[1991 c 3 § 95]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c447.pdf?cite=1987%20c%20447%20§%2010[1987 c 447 § 10]; ]

== 18.36A.110 - Examination for licensure.
. The date and location of the examination shall be established by the board. Applicants who have been found to meet the education and experience requirements for licensure shall be scheduled for the next examination following the filing of the application. The board shall establish by rule the examination application deadline.

. The examination shall contain subjects appropriate to the standards of competency and scope of practice.

. The board shall establish by rule the requirements for a reexamination if the applicant has failed the examination.

. The board may approve an examination prepared or administered, or both, by a private testing agency or association of licensing boards.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1181.SL.pdf?cite=2011%20c%2041%20§%209[2011 c 41 § 9]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2096[1991 c 3 § 96]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c447.pdf?cite=1987%20c%20447%20§%2011[1987 c 447 § 11]; ]

== 18.36A.120 - License standards for applicants from other jurisdictions—Reciprocity.
The board shall establish by rule the standards for licensure of applicants licensed in another jurisdiction. However, the standards for reciprocity of licensure shall not be less than required for licensure in the state of Washington.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1181.SL.pdf?cite=2011%20c%2041%20§%2010[2011 c 41 § 10]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2097[1991 c 3 § 97]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c447.pdf?cite=1987%20c%20447%20§%2012[1987 c 447 § 12]; ]

== 18.36A.130 - Compliance with secretary's determinations.
Applicants shall comply with administrative procedures, administrative requirements, and fees determined by the secretary as provided in RCW 43.70.250 and 43.70.280.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2022[1996 c 191 § 22]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2098[1991 c 3 § 98]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c447.pdf?cite=1987%20c%20447%20§%2013[1987 c 447 § 13]; ]

== 18.36A.140 - Fee for renewal, late renewal.
The secretary shall establish the administrative procedures, administrative requirements, and fees for renewal and late renewal of licenses and certificates as provided in RCW 43.70.250 and 43.70.280.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5124.SL.pdf?cite=2021%20c%20179%20§%204[2021 c 179 § 4]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2023[1996 c 191 § 23]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2099[1991 c 3 § 99]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c447.pdf?cite=1987%20c%20447%20§%2014[1987 c 447 § 14]; ]

== 18.36A.150 - Board of naturopathy.
. There is created the board of naturopathy consisting of seven members appointed by the governor to four-year terms. Five members of the board shall be persons licensed under this chapter and two shall be members of the public. No member may serve more than two consecutive full terms. Members hold office until their successors are appointed. The governor may appoint the initial members of the board to staggered terms from one to four years. Thereafter, all members shall be appointed to full four-year terms.

. The public members of the board may not be a member of any other health care licensing board or commission, have a fiduciary obligation to a facility rendering services regulated under this chapter, or have a material or financial interest in the rendering of services regulated under this chapter.

. The board shall elect officers each year. The board shall meet at least twice each year and may hold additional meetings as called by the chair. Meetings of the board are open to the public, except that the board may hold executive sessions to the extent permitted by chapter 42.30 RCW. The department shall provide secretarial, clerical, and other assistance as required by the board.

. Each member of the board shall be compensated in accordance with RCW 43.03.240. Members shall be reimbursed for travel expenses incurred in the actual performance of their duties, as provided in RCW 43.03.050 and 43.03.060.

. A majority of the board members appointed and serving constitutes a quorum for the transaction of board business. The affirmative vote of a majority of a quorum of the board is required to carry a motion or resolution, to adopt a rule, or to pass a measure.

. The board may appoint members to panels of at least three members. A quorum for transaction of any business by a panel is a minimum of three members. A majority vote of a quorum of the panel is required to transact business delegated to it by the board.

. The board may adopt such rules as are consistent with this chapter as may be deemed necessary and proper to carry out the purposes of this chapter.

. The governor may remove a member of the board for neglect of duty, misconduct, or malfeasance or misfeasance in office. Whenever the governor is satisfied that a member of the board has been guilty of neglect of duty, misconduct, or malfeasance or misfeasance in office, he or she shall file with the secretary of state a statement of the cause for and the order of removal from office, and the secretary shall immediately send a certified copy of the order of removal and statement of causes by certified mail to the last known post office address of the member. If a vacancy occurs on the board, the governor shall appoint a replacement to fill the remainder of the unexpired term.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1181.SL.pdf?cite=2011%20c%2041%20§%201[2011 c 41 § 1]; ]

== 18.36A.160 - Board of naturopathy—Duties.
. In addition to any other authority provided by law, the board shall:

.. Adopt rules, in accordance with chapter 34.05 RCW, necessary to implement this chapter;

.. Determine the minimum education and experience requirements for licensure in conformance with RCW 18.36A.090, including, but not limited to, approval of educational programs;

.. Determine the minimum education and training requirements for certification as a colon hydrotherapist under RCW 18.36A.095, including identifying any certification or accreditation organizations that satisfy certification requirements;

.. Establish standards for the affiliation relationship between a colon hydrotherapist and a naturopath, including standards for communicating a plan of care for a patient, transferring a patient to a higher level of care, and providing general, off-site supervision;

.. Prepare and administer, or approve the preparation and administration of, examinations for licensure or certification;

.. Establish by rule the procedures for an appeal of examination failure;

.. Determine whether alternative methods of training are equivalent to formal education, and establish forms, procedures, and criteria for evaluation of an applicant's equivalent alternative training to determine the applicant's eligibility to take the examination; and

.. Adopt rules implementing a continuing competency program.

. The uniform disciplinary act, chapter 18.130 RCW, governs unlicensed and uncertified practice, the issuance and denial of licenses and certifications, and the discipline of licensees and certified persons under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5124.SL.pdf?cite=2021%20c%20179%20§%205[2021 c 179 § 5]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1181.SL.pdf?cite=2011%20c%2041%20§%202[2011 c 41 § 2]; ]

== 18.36A.900 - Effective date—1987 c 447 §§ 1-14.
Sections 1 through 14 of this act shall take effect January 1, 1988.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c447.pdf?cite=1987%20c%20447%20§%2020[1987 c 447 § 20]; ]

