= 18.06 - Acupuncture and Eastern medicine.
:toc:

== 18.06.010 - Definitions.
The following terms in this chapter shall have the meanings set forth in this section unless the context clearly indicates otherwise:

. "Acupuncture" or "Eastern medicine" means a health care service utilizing acupuncture or Eastern medicine diagnosis and treatment to promote health and treat organic or functional disorders and includes the following:

.. Acupuncture, including the use of acupuncture needles or lancets to directly and indirectly stimulate acupuncture points and meridians;

.. Use of electrical, mechanical, or magnetic devices to stimulate acupuncture points and meridians;

.. Moxibustion;

.. Acupressure;

.. Cupping;

.. Dermal friction technique;

.. Infra-red;

.. Sonopuncture;

.. Laserpuncture;

.. Point injection therapy, as defined in rule by the department. Point injection therapy includes injection of substances, limited to saline, sterile water, herbs, minerals, vitamins in liquid form, and homeopathic and nutritional substances, consistent with the practice of acupuncture or Eastern medicine. Point injection therapy does not include injection of controlled substances contained in Schedules I through V of the uniform controlled substances act, chapter 69.50 RCW or steroids as defined in RCW 69.41.300;

.. Dietary advice and health education based on acupuncture or Eastern medical theory, including the recommendation and sale of herbs, vitamins, minerals, and dietary and nutritional supplements;

.. Breathing, relaxation, and Eastern exercise techniques;

.. Qi gong;

.. Eastern massage and Tui na, which is a method of Eastern bodywork, characterized by the kneading, pressing, rolling, shaking, and stretching of the body and does not include spinal manipulation; and

.. Superficial heat and cold therapies.

. "Acupuncturist" or "acupuncture and Eastern medicine practitioner" means a person licensed under this chapter.

. "Department" means the department of health.

. "Secretary" means the secretary of health or the secretary's designee.

Nothing in this chapter requires individuals to be licensed as an acupuncturist or Eastern medicine practitioner in order to provide the techniques and services in subsection (1)(k) through (o) of this section or to sell herbal products.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1865-S.SL.pdf?cite=2019%20c%20308%20§%202[2019 c 308 § 2]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2448-S.SL.pdf?cite=2016%20c%2097%20§%201[2016 c 97 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6280-S.SL.pdf?cite=2010%20c%20286%20§%202[2010 c 286 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1398-S.SL.pdf?cite=1995%20c%20323%20§%204[1995 c 323 § 4]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1392-S.SL.pdf?cite=1992%20c%20110%20§%201[1992 c 110 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%204[1991 c 3 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c326.pdf?cite=1985%20c%20326%20§%201[1985 c 326 § 1]; ]

== 18.06.020 - Practice without license unlawful.
. No one may hold themselves out to the public as an acupuncturist, licensed acupuncturist, acupuncture and Eastern medicine practitioner, or any derivative thereof which is intended to or is likely to lead the public to believe such a person is an acupuncturist, licensed acupuncturist[,] or acupuncture and Eastern medicine practitioner, unless licensed as provided for in this chapter.

. A person may not practice acupuncture or Eastern medicine if the person is not licensed under this chapter.

. No one may use any configuration of letters after their name (including L.Ac., EAMP, or AEMP) which indicates a degree or formal training in acupuncture or Eastern medicine unless licensed as provided for in this chapter.

. The secretary may by rule proscribe or regulate advertising and other forms of patient solicitation which are likely to mislead or deceive the public as to whether someone is licensed under this chapter.

. A person licensed under this chapter may use the title acupuncture and Eastern medicine practitioner and may use the letters AEMP indicating such license. However, nothing in this section prohibits or limits in any way a practitioner licensed under this chapter from alternatively holding himself or herself out as an acupuncturist, licensed acupuncturist, or East Asian medicine practitioner or from using the letters L.Ac. or EAMP after his or her name.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1865-S.SL.pdf?cite=2019%20c%20308%20§%203[2019 c 308 § 3]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6280-S.SL.pdf?cite=2010%20c%20286%20§%203[2010 c 286 § 3]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1398-S.SL.pdf?cite=1995%20c%20323%20§%205[1995 c 323 § 5]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%205[1991 c 3 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c326.pdf?cite=1985%20c%20326%20§%202[1985 c 326 § 2]; ]

== 18.06.045 - Exemptions from chapter.
Nothing in this chapter shall be construed to prohibit or restrict:

. The practice by an individual credentialed under the laws of this state and performing services within such individual's authorized scope of practice;

. The practice by an individual employed by the government of the United States while engaged in the performance of duties prescribed by the laws of the United States;

. The practice by a person who is a regular student in an educational program approved by the secretary, and whose performance of services is pursuant to a regular course of instruction or assignments from an instructor and under the general supervision of the instructor;

. The practice of acupuncture or Eastern medicine by any person credentialed to perform acupuncture or Eastern medicine in any other jurisdiction where such person is doing so in the course of regular instruction of a school of acupuncture, Eastern medicine, traditional Chinese medicine, or medical traditions from Japan, Korea, or other East Asian countries, approved by the secretary or in an educational seminar by a professional organization of acupuncture or Eastern medicine, provided that in the latter case, the practice is supervised directly by a person licensed under this chapter or licensed under any other healing art whose scope of practice is acupuncture and Eastern medicine.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1865-S.SL.pdf?cite=2019%20c%20308%20§%204[2019 c 308 § 4]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6280-S.SL.pdf?cite=2010%20c%20286%20§%204[2010 c 286 § 4]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1398-S.SL.pdf?cite=1995%20c%20323%20§%206[1995 c 323 § 6]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1392-S.SL.pdf?cite=1992%20c%20110%20§%202[1992 c 110 § 2]; ]

== 18.06.050 - Applications for licensure—Qualifications.
Any person seeking to be licensed shall present to the secretary:

. A written application on a form or forms provided by the secretary setting forth under affidavit such information as the secretary may require; and

. Proof that the candidate has:

.. Successfully completed a course, approved by the secretary, of didactic training in basic sciences and acupuncture and Eastern medicine over a minimum period of two academic years. The training shall include such subjects as anatomy, physiology, microbiology, biochemistry, pathology, hygiene, and a survey of western clinical sciences. The basic science classes must be equivalent to those offered at the collegiate level. However, if the applicant is a licensed chiropractor under chapter 18.25 RCW or a naturopath licensed under chapter 18.36A RCW, the requirements of this subsection relating to basic sciences may be reduced by up to one year depending upon the extent of the candidate's qualifications as determined under rules adopted by the secretary;

.. Successfully completed five hundred hours of clinical training in acupuncture or Eastern medicine that is approved by the secretary.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1865-S.SL.pdf?cite=2019%20c%20308%20§%205[2019 c 308 § 5]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6280-S.SL.pdf?cite=2010%20c%20286%20§%205[2010 c 286 § 5]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6554-S.SL.pdf?cite=2004%20c%20262%20§%202[2004 c 262 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%207[1991 c 3 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c447.pdf?cite=1987%20c%20447%20§%2015[1987 c 447 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c326.pdf?cite=1985%20c%20326%20§%205[1985 c 326 § 5]; ]

== 18.06.060 - Approval of educational programs.
The department shall consider for approval any school or program that meets the requirements outlined in this chapter and provides the training required under RCW 18.06.050. Clinical and didactic training may be approved as separate programs or as a joint program. The process for approval shall be established by the secretary by rule.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1865-S.SL.pdf?cite=2019%20c%20308%20§%206[2019 c 308 § 6]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%208[1991 c 3 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c326.pdf?cite=1985%20c%20326%20§%206[1985 c 326 § 6]; ]

== 18.06.080 - Authority of secretary—Examination—Contents—Immunity.
. The secretary is hereby authorized and empowered to execute the provisions of this chapter and shall offer examinations in order to become a licensed acupuncturist or acupuncture and Eastern medicine practitioner at least twice a year at such times and places as the secretary may select. The examination shall be a written examination and may include a practical examination.

. The secretary shall approve a licensure examination in the subjects that the secretary determines are within the scope of and commensurate with the work performed by an acupuncturist or acupuncture and Eastern medicine practitioner and shall include but not necessarily be limited to anatomy, physiology, microbiology, biochemistry, pathology, hygiene, acupuncture, and Eastern medicine. All application papers shall be deposited with the secretary and there retained for at least one year, when they may be destroyed.

. If the examination is successfully passed, the secretary shall confer on such candidate the title of acupuncturist or acupuncture and Eastern medicine practitioner.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1865-S.SL.pdf?cite=2019%20c%20308%20§%207[2019 c 308 § 7]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6280-S.SL.pdf?cite=2010%20c%20286%20§%206[2010 c 286 § 6]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5995.SL.pdf?cite=2009%20c%20560%20§%202[2009 c 560 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1398-S.SL.pdf?cite=1995%20c%20323%20§%207[1995 c 323 § 7]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20502[1994 sp.s. c 9 § 502]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1392-S.SL.pdf?cite=1992%20c%20110%20§%203[1992 c 110 § 3]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2010[1991 c 3 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c326.pdf?cite=1985%20c%20326%20§%208[1985 c 326 § 8]; ]

== 18.06.090 - Fluency in English required.
Before licensure, each applicant shall demonstrate sufficient fluency in reading, speaking, and understanding the English language to enable the applicant to communicate with other health care providers and patients concerning health care problems and treatment.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1398-S.SL.pdf?cite=1995%20c%20323%20§%208[1995 c 323 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c326.pdf?cite=1985%20c%20326%20§%209[1985 c 326 § 9]; ]

== 18.06.100 - Investigation of applicant's background.
Each applicant shall, as part of his or her application, furnish written consent to an investigation of his or her personal background, professional training, and experience by the department or any person acting on its behalf.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c326.pdf?cite=1985%20c%20326%20§%2010[1985 c 326 § 10]; ]

== 18.06.110 - Application of Uniform Disciplinary Act.
The Uniform Disciplinary Act, chapter 18.130 RCW, governs uncertified practice, the issuance and denial of licenses, and the disciplining of license holders under this chapter. The secretary shall be the disciplining authority under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1398-S.SL.pdf?cite=1995%20c%20323%20§%209[1995 c 323 § 9]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2011[1991 c 3 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c150.pdf?cite=1987%20c%20150%20§%209[1987 c 150 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c326.pdf?cite=1985%20c%20326%20§%2011[1985 c 326 § 11]; ]

== 18.06.120 - Compliance with administrative procedures—Fees.
. Every person licensed under this chapter shall comply with the administrative procedures and administrative requirements for registration and renewal set by the secretary under RCW 43.70.250 and 43.70.280.

. All fees collected under this section and *RCW 18.06.070 shall be credited to the health professions account as required under RCW 43.70.320.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6280-S.SL.pdf?cite=2010%20c%20286%20§%207[2010 c 286 § 7]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%203[1996 c 191 § 3]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1398-S.SL.pdf?cite=1995%20c%20323%20§%2010[1995 c 323 § 10]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1392-S.SL.pdf?cite=1992%20c%20110%20§%204[1992 c 110 § 4]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2012[1991 c 3 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c326.pdf?cite=1985%20c%20326%20§%2012[1985 c 326 § 12]; ]

== 18.06.130 - Patient information form—Penalty.
. The secretary shall develop a form to be used by a person licensed under this chapter to inform the patient of the scope of practice and qualifications of an acupuncturist or acupuncture and Eastern medicine practitioner. All license holders shall bring the form to the attention of the patients in whatever manner the secretary, by rule, provides.

. A person violating this section is guilty of a misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1865-S.SL.pdf?cite=2019%20c%20308%20§%208[2019 c 308 § 8]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6280-S.SL.pdf?cite=2010%20c%20286%20§%208[2010 c 286 § 8]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20121[2003 c 53 § 121]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1398-S.SL.pdf?cite=1995%20c%20323%20§%2011[1995 c 323 § 11]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2013[1991 c 3 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c326.pdf?cite=1985%20c%20326%20§%2013[1985 c 326 § 13]; ]

== 18.06.140 - Consultation with other health care practitioners—Patient waiver—Emergencies—Penalty. (Effective until July 1, 2022.)
. When a person licensed under this chapter sees patients with potentially serious disorders such as cardiac conditions, acute abdominal symptoms, and such other conditions, the practitioner shall immediately request a consultation or recent written diagnosis from a primary health care provider licensed under chapter 18.71, 18.57, 18.57A, 18.36A, or 18.71A RCW or RCW 18.79.050. In the event that the patient with the disorder refuses to authorize such consultation or provide a recent diagnosis from such primary health care provider, acupuncture or Eastern medicine treatments may only be continued after the patient signs a written waiver acknowledging the risks associated with the failure to pursue treatment from a primary health care provider. The waiver must also include: (a) An explanation of an acupuncturist's or acupuncture and Eastern medicine practitioner's scope of practice, including the services and techniques acupuncturists or acupuncture and Eastern medicine practitioners are authorized to provide and (b) a statement that the services and techniques that an acupuncturist or acupuncture and Eastern medicine practitioner is authorized to provide will not resolve the patient's underlying potentially serious disorder. The requirements of the waiver shall be established by the secretary in rule.

. In an emergency, a person licensed under this chapter shall: (a) Initiate the emergency medical system by calling 911; (b) request an ambulance; and (c) provide patient support until emergency response arrives.

. A person violating this section is guilty of a misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1865-S.SL.pdf?cite=2019%20c%20308%20§%209[2019 c 308 § 9]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1045-S.SL.pdf?cite=2015%20c%2060%20§%202[2015 c 60 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6280-S.SL.pdf?cite=2010%20c%20286%20§%209[2010 c 286 § 9]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20122[2003 c 53 § 122]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1398-S.SL.pdf?cite=1995%20c%20323%20§%2012[1995 c 323 § 12]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2014[1991 c 3 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c326.pdf?cite=1985%20c%20326%20§%2014[1985 c 326 § 14]; ]

== 18.06.160 - Adoption of rules.
The secretary shall adopt rules in the manner provided by chapter 34.05 RCW as are necessary to carry out the purposes of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2015[1991 c 3 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c326.pdf?cite=1985%20c%20326%20§%2016[1985 c 326 § 16]; ]

== 18.06.190 - Licensing by endorsement.
The secretary may license a person without examination if such person is credentialed as an acupuncturist or acupuncture and Eastern medicine practitioner, or equivalent, in another jurisdiction if, in the secretary's judgment, the requirements of that jurisdiction are equivalent to or greater than those of Washington state.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1865-S.SL.pdf?cite=2019%20c%20308%20§%2010[2019 c 308 § 10]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6280-S.SL.pdf?cite=2010%20c%20286%20§%2010[2010 c 286 § 10]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1398-S.SL.pdf?cite=1995%20c%20323%20§%2013[1995 c 323 § 13]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2018[1991 c 3 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c326.pdf?cite=1985%20c%20326%20§%2019[1985 c 326 § 19]; ]

== 18.06.200 - Health care insurance benefits not mandatory.
Nothing in this chapter may be construed to require that individual or group policies or contracts of an insurance carrier, health care service contractor, or health maintenance organization provide benefits or coverage for services and supplies provided by a person licensed under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1398-S.SL.pdf?cite=1995%20c%20323%20§%2014[1995 c 323 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c326.pdf?cite=1985%20c%20326%20§%2020[1985 c 326 § 20]; ]

== 18.06.210 - Prescription of drugs and practice of medicine not authorized.
This chapter shall not be construed as permitting the administration or prescription of drugs or in any way infringing upon the practice of medicine and surgery as defined in chapter 18.71 or 18.57 RCW, except as authorized in this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c326.pdf?cite=1985%20c%20326%20§%2021[1985 c 326 § 21]; ]

== 18.06.220 - Acupuncture and Eastern medicine advisory committee.
The Washington state acupuncture and Eastern medicine advisory committee is established.

. The committee consists of five members, each of whom must be a resident of the state of Washington. Four committee members must be acupuncturists or acupuncture and Eastern medicine practitioners licensed under this chapter who have not less than five years' experience in the practice of acupuncture and Eastern medicine and who have been actively engaged in practice within two years of appointment. The fifth committee member must be appointed from the public at large and must have an interest in the rights of consumers of health services.

. The secretary shall appoint the committee members. Committee members serve at the pleasure of the secretary. The secretary may appoint members of the initial committee to staggered terms of one to three years, and thereafter all terms are for three years. No member may serve more than two consecutive full terms.

. The committee shall meet as necessary, but no less often than once per year. The committee shall elect a chair and a vice chair. A majority of the members currently serving constitutes a quorum.

. The committee shall advise and make recommendations to the secretary on standards for the practice of acupuncture and Eastern medicine.

. Committee members must be compensated in accordance with RCW 43.03.240, including travel expenses in carrying out his or her authorized duties in accordance with RCW 43.03.050 and 43.03.060.

. Committee members are immune from suit in an action, civil or criminal, based on the department's disciplinary proceedings or other official acts performed in good faith.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1865-S.SL.pdf?cite=2019%20c%20308%20§%2011[2019 c 308 § 11]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1045-S.SL.pdf?cite=2015%20c%2060%20§%201[2015 c 60 § 1]; ]

== 18.06.230 - Point injection therapy services—Education and training.
. Prior to providing point injection therapy services, an acupuncturist or acupuncture and Eastern medicine practitioner must obtain the education and training necessary to provide the service.

. Any acupuncturist or acupuncture and Eastern medicine practitioner performing point injection therapy prior to June 9, 2016, must be able to demonstrate, upon request of the department of health, successful completion of education and training in point injection therapy.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1865-S.SL.pdf?cite=2019%20c%20308%20§%2012[2019 c 308 § 12]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2448-S.SL.pdf?cite=2016%20c%2097%20§%204[2016 c 97 § 4]; ]

== 18.06.240 - Continuing education.
The department shall adopt a rule requiring completion of continuing education for acupuncturists as a condition of license renewal.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1865-S.SL.pdf?cite=2019%20c%20308%20§%2013[2019 c 308 § 13]; ]

