= 18.71A - Physician assistants.
:toc:

== 18.71A.010 - Definitions. (Effective until July 1, 2021.)
The definitions set forth in this section apply throughout this chapter.

. "Commission" means the Washington medical commission.

. "Department" means the department of health.

. "Physician assistant" means a person who is licensed by the commission to practice medicine to a limited extent only under the supervision of a physician as defined in chapter 18.71 RCW and who is academically and clinically prepared to provide health care services and perform diagnostic, therapeutic, preventative, and health maintenance services.

. "Practice medicine" has the meaning defined in RCW 18.71.011.

. "Secretary" means the secretary of health or the secretary's designee.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5764.SL.pdf?cite=2019%20c%2055%20§%205[2019 c 55 § 5]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20318[1994 sp.s. c 9 § 318]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c196.pdf?cite=1990%20c%20196%20§%201[1990 c 196 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c113.pdf?cite=1988%20c%20113%20§%201[1988 c 113 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c190.pdf?cite=1975%201st%20ex.s.%20c%20190%20§%201[1975 1st ex.s. c 190 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c30.pdf?cite=1971%20ex.s.%20c%2030%20§%201[1971 ex.s. c 30 § 1]; ]

== 18.71A.020 - Rules fixing qualifications and restricting practice—Applications—Discipline—Payment of funds. (Effective until July 1, 2021.)
. The commission shall adopt rules fixing the qualifications and the educational and training requirements for licensure as a physician assistant or for those enrolled in any physician assistant training program. The requirements shall include completion of an accredited physician assistant training program approved by the commission and within one year successfully take and pass an examination approved by the commission, if the examination tests subjects substantially equivalent to the curriculum of an accredited physician assistant training program. An interim permit may be granted by the department of health for one year provided the applicant meets all other requirements. Physician assistants licensed by the board of medical examiners, or the commission as of July 1, 1999, shall continue to be licensed.

. [Empty]
.. The commission shall adopt rules governing the extent to which:

... Physician assistant students may practice medicine during training; and

... Physician assistants may practice after successful completion of a physician assistant training course.

.. Such rules shall provide:

... That the practice of a physician assistant shall be limited to the performance of those services for which he or she is trained; and

... That each physician assistant shall practice medicine only under the supervision and control of a physician licensed in this state, but such supervision and control shall not be construed to necessarily require the personal presence of the supervising physician or physicians at the place where services are rendered.

. Applicants for licensure shall file an application with the commission on a form prepared by the secretary with the approval of the commission, detailing the education, training, and experience of the physician assistant and such other information as the commission may require. The application shall be accompanied by a fee determined by the secretary as provided in RCW 43.70.250 and 43.70.280. A surcharge of fifty dollars per year shall be charged on each license renewal or issuance of a new license to be collected by the department and deposited into the impaired physician account for physician assistant participation in the impaired physician program. Each applicant shall furnish proof satisfactory to the commission of the following:

.. That the applicant has completed an accredited physician assistant program approved by the commission and is eligible to take the examination approved by the commission;

.. That the applicant is of good moral character; and

.. That the applicant is physically and mentally capable of practicing medicine as a physician assistant with reasonable skill and safety. The commission may require an applicant to submit to such examination or examinations as it deems necessary to determine an applicant's physical or mental capability, or both, to safely practice as a physician assistant.

. [Empty]
.. The commission may approve, deny, or take other disciplinary action upon the application for license as provided in the Uniform Disciplinary Act, chapter 18.130 RCW.

.. The license shall be renewed as determined under RCW 43.70.250 and 43.70.280. The commission shall request licensees to submit information about their current professional practice at the time of license renewal and licensees must provide the information requested. This information may include practice setting, medical specialty, or other relevant data determined by the commission.

.. The commission may authorize the use of alternative supervisors who are licensed either under chapter 18.57 or 18.71 RCW.

. All funds in the impaired physician account shall be paid to the contract entity within sixty days of deposit.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5764.SL.pdf?cite=2019%20c%2055%20§%206[2019 c 55 § 6]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1485-S2.SL.pdf?cite=2015%20c%20252%20§%209[2015 c 252 § 9]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5480.SL.pdf?cite=2011%20c%20178%20§%202[2011 c 178 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1765-S.SL.pdf?cite=2009%20c%2098%20§%202[2009 c 98 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5702.SL.pdf?cite=1999%20c%20127%20§%201[1999 c 127 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1618-S2.SL.pdf?cite=1998%20c%20132%20§%2014[1998 c 132 § 14]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2057[1996 c 191 § 57]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20319[1994 sp.s. c 9 § 319]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1253-S.SL.pdf?cite=1993%20c%2028%20§%205[1993 c 28 § 5]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6070.SL.pdf?cite=1992%20c%2028%20§%202[1992 c 28 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c196.pdf?cite=1990%20c%20196%20§%202[1990 c 196 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c30.pdf?cite=1971%20ex.s.%20c%2030%20§%202[1971 ex.s. c 30 § 2]; ]

== 18.71A.023 - Practice requirements—Military training or experience.
An applicant with military training or experience satisfies the training or experience requirements of this chapter unless the commission determines that the military training or experience is not substantially equivalent to the standards of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5307-S.SL.pdf?cite=2011%20c%2032%20§%206[2011 c 32 § 6]; ]

== 18.71A.025 - Application of uniform disciplinary act. (Effective until July 1, 2021.)
The uniform disciplinary act, chapter 18.130 RCW, governs the issuance and denial of licenses and the discipline of licensees under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c259.pdf?cite=1986%20c%20259%20§%20106[1986 c 259 § 106]; ]

== 18.71A.030 - Limitations on practice—Scope of practice. (Effective until July 1, 2021.)
. A physician assistant may practice medicine in this state only with the approval of the delegation agreement by the commission and only to the extent permitted by the commission. A physician assistant who has received a license but who has not received commission approval of the delegation agreement under RCW 18.71A.040 may not practice. A physician assistant shall be subject to discipline under chapter 18.130 RCW.

. Physician assistants may provide services that they are competent to perform based on their education, training, and experience and that are consistent with their commission-approved delegation agreement. The supervising physician and the physician assistant shall determine which procedures may be performed and the degree of supervision under which the procedure is performed. Physician assistants may practice in any area of medicine or surgery as long as the practice is not beyond the supervising physician's own scope of expertise and practice.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6445-S.SL.pdf?cite=2016%20c%20155%20§%2023[2016 c 155 § 23]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1737-S.SL.pdf?cite=2013%20c%20203%20§%206[2013 c 203 § 6]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20320[1994 sp.s. c 9 § 320]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1253-S.SL.pdf?cite=1993%20c%2028%20§%206[1993 c 28 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c196.pdf?cite=1990%20c%20196%20§%203[1990 c 196 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c30.pdf?cite=1971%20ex.s.%20c%2030%20§%203[1971 ex.s. c 30 § 3]; ]

== 18.71A.035 - Limitation on practice—Remote sites. (Effective until July 1, 2021.)
. No licensee may be utilized in a remote site without approval by the commission or its designee. A "remote site" is defined as a setting physically separate from the sponsoring or supervising physician's primary place for meeting patients or a setting where the physician is present less than twenty-five percent of the practice time of the licensee.

. [Empty]
.. Approval by the commission or its designee may be granted to utilize a licensee in a remote site if:

... There is a demonstrated need for the utilization;

... Adequate provision for timely communication between the primary or alternate physician and the licensee exists;

... The responsible sponsoring or supervising physician spends at least ten percent of the practice time of the licensee in the remote site unless the sponsoring physician demonstrates that adequate supervision is being maintained by an alternate method such as telecommunication.

.. The names of the sponsoring or supervising physician and the licensee must be prominently displayed at the entrance to the clinic or in the reception area.

. No physician assistant holding an interim permit may be utilized in a remote site setting.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1737-S.SL.pdf?cite=2013%20c%20203%20§%202[2013 c 203 § 2]; ]

== 18.71A.040 - Commission approval required—Application—Fee—Discipline. (Effective until July 1, 2021.)
. No physician assistant practicing in this state shall be employed or supervised by a physician or physician group without the approval of the commission.

. Prior to commencing practice, a physician assistant licensed in this state shall apply to the commission for permission to be employed or supervised by a physician or physician group. The delegation agreement shall be jointly submitted by the physician or physician group and physician assistant. Administrative procedures, administrative requirements, and fees shall be established as provided in RCW 43.70.250 and 43.70.280. The delegation agreement shall delineate the manner and extent to which the physician assistant would practice and be supervised. Whenever a physician assistant is practicing in a manner inconsistent with the approved delegation agreement, the commission may take disciplinary action under chapter 18.130 RCW.

. A physician may enter into delegation agreements with five physician assistants, but may petition the commission for a waiver of this limit. However, no physician may have under his or her supervision: (a) More than three physician assistants who are working in remote sites; or (b) more physician assistants than the physician can adequately supervise.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1737-S.SL.pdf?cite=2013%20c%20203%20§%207[2013 c 203 § 7]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2058[1996 c 191 § 58]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2040[1996 c 191 § 40]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20321[1994 sp.s. c 9 § 321]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1253-S.SL.pdf?cite=1993%20c%2028%20§%207[1993 c 28 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c196.pdf?cite=1990%20c%20196%20§%204[1990 c 196 § 4]; prior:  1986 c 259 § 113; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%2061[1985 c 7 § 61]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c30.pdf?cite=1975%201st%20ex.s.%20c%2030%20§%2064[1975 1st ex.s. c 30 § 64]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c190.pdf?cite=1975%201st%20ex.s.%20c%20190%20§%202[1975 1st ex.s. c 190 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c30.pdf?cite=1971%20ex.s.%20c%2030%20§%204[1971 ex.s. c 30 § 4]; ]

== 18.71A.045 - Eligibility of foreign medical school graduates.
Foreign medical school graduates shall not be eligible for licensing as physician assistants after July 1, 1989.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20322[1994 sp.s. c 9 § 322]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c113.pdf?cite=1988%20c%20113%20§%202[1988 c 113 § 2]; ]

== 18.71A.050 - Physician's liability, responsibility. (Effective until July 1, 2021.)
No physician who supervises a licensed physician assistant in accordance with and within the terms of any permission granted by the commission is considered as aiding and abetting an unlicensed person to practice medicine. The supervising physician and physician assistant shall retain professional and personal responsibility for any act which constitutes the practice of medicine as defined in RCW 18.71.011 when performed by the physician assistant.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20323[1994 sp.s. c 9 § 323]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1253-S.SL.pdf?cite=1993%20c%2028%20§%208[1993 c 28 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c196.pdf?cite=1990%20c%20196%20§%205[1990 c 196 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c259.pdf?cite=1986%20c%20259%20§%20114[1986 c 259 § 114]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c30.pdf?cite=1971%20ex.s.%20c%2030%20§%205[1971 ex.s. c 30 § 5]; ]

== 18.71A.060 - Limitations on health care services.
No health care services may be performed under this chapter in any of the following areas:

. The measurement of the powers or range of human vision, or the determination of the accommodation and refractive state of the human eye or the scope of its functions in general, or the fitting or adaptation of lenses or frames for the aid thereof.

. The prescribing or directing the use of, or using, any optical device in connection with ocular exercises, visual training, vision training, or orthoptics.

. The prescribing of contact lenses for, or the fitting or adaptation of contact lenses to, the human eye.

. Nothing in this section shall preclude the performance of routine visual screening.

. The practice of dentistry or dental hygiene as defined in chapters 18.32 and 18.29 RCW respectively. The exemptions set forth in RCW 18.32.030 (1) and (8), shall not apply to a physician assistant.

. The practice of chiropractic as defined in chapter 18.25 RCW including the adjustment or manipulation of the articulations of the spine.

. The practice of podiatric medicine and surgery as defined in chapter 18.22 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20324[1994 sp.s. c 9 § 324]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c196.pdf?cite=1990%20c%20196%20§%206[1990 c 196 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c77.pdf?cite=1973%20c%2077%20§%2021[1973 c 77 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c30.pdf?cite=1971%20ex.s.%20c%2030%20§%206[1971 ex.s. c 30 § 6]; ]

== 18.71A.085 - Acupuncture.
Any physician assistant acupuncturist currently licensed by the commission may continue to perform acupuncture under the physician assistant license as long as he or she maintains licensure as a physician assistant.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20325[1994 sp.s. c 9 § 325]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c196.pdf?cite=1990%20c%20196%20§%2010[1990 c 196 § 10]; ]

== 18.71A.090 - Signing and attesting to required documentation. (Effective until July 1, 2021.)
A physician assistant may sign and attest to any certificates, cards, forms, or other required documentation that the physician assistant's supervising physician or physician group may sign, provided that it is within the physician assistant's scope of practice and is consistent with the terms of the physician assistant's practice arrangement plan as required by this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1966.SL.pdf?cite=2007%20c%20264%20§%203[2007 c 264 § 3]; ]

== 18.71A.100 - Pain management rules—Criteria for new rules.
. By June 30, 2011, the commission shall adopt new rules on chronic, noncancer pain management that contain the following elements:

.. [Empty]
... Dosing criteria, including:

(A) A dosage amount that must not be exceeded unless a physician assistant first consults with a practitioner specializing in pain management; and

(B) Exigent or special circumstances under which the dosage amount may be exceeded without consultation with a practitioner specializing in pain management.

... The rules regarding consultation with a practitioner specializing in pain management must, to the extent practicable, take into account:

(A) Circumstances under which repeated consultations would not be necessary or appropriate for a patient undergoing a stable, ongoing course of treatment for pain management;

(B) Minimum training and experience that is sufficient to exempt a physician assistant from the specialty consultation requirement;

(C) Methods for enhancing the availability of consultations;

(D) Allowing the efficient use of resources; and

(E) Minimizing the burden on practitioners and patients;

.. Guidance on when to seek specialty consultation and ways in which electronic specialty consultations may be sought;

.. Guidance on tracking clinical progress by using assessment tools focusing on pain interference, physical function, and overall risk for poor outcome; and

.. Guidance on tracking the use of opioids, particularly in the emergency department.

. The commission shall consult with the agency medical directors' group, the department of health, the University of Washington, and the largest professional association of physician assistants in the state.

. The rules adopted under this section do not apply:

.. To the provision of palliative, hospice, or other end-of-life care; or

.. To the management of acute pain caused by an injury or a surgical procedure.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2876-S.SL.pdf?cite=2010%20c%20209%20§%206[2010 c 209 § 6]; ]

== 18.71A.110 - Down syndrome—Parent information.
A physician assistant who provides a parent with a positive prenatal or postnatal diagnosis of Down syndrome shall provide the parent with the information prepared by the department under RCW 43.70.738 at the time the physician assistant provides the parent with the Down syndrome diagnosis.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2403.SL.pdf?cite=2016%20c%2070%20§%206[2016 c 70 § 6]; ]

== 18.71A.120 - Practice agreement—Elements—Amendment—Disciplinary action. (Effective July 1, 2021.)
. Prior to commencing practice, a physician assistant licensed in Washington state must enter into a practice agreement with a physician or group of physicians, at least one of whom must be working in a supervisory capacity.

.. Entering into a practice agreement is voluntary for the physician assistant and the supervising physician. A physician may not be compelled to participate in a practice agreement as a condition of employment.

.. Prior to entering into the practice agreement, the physician, physicians, or their designee must verify the physician assistant's credentials.

.. The protections of RCW 43.70.075 apply to any physician who reports to the commission acts of retaliation or reprisal for declining to sign a practice agreement.

.. The practice agreement must be maintained by the physician assistant's employer or at his or her place of work and must be made available to the commission upon request.

.. The commission shall develop a model practice agreement.

.. The commission shall establish administrative procedures, administrative requirements, and fees as provided in RCW 43.70.250 and 43.70.280.

. A practice agreement must include all of the following:

.. The duties and responsibilities of the physician assistant, the supervising physician, and alternate physicians. The practice agreement must describe supervision requirements for specified procedures or areas of practice. The practice agreement may only include acts, tasks, or functions that the physician assistant and supervising physician or alternate physicians are qualified to perform by education, training, or experience and that are within the scope of expertise and clinical practice of both the physician assistant and the supervising physician or alternate physicians, unless otherwise authorized by law, rule, or the commission;

.. A process between the physician assistant and supervising physician or alternate physicians for communication, availability, and decision making when providing medical treatment to a patient or in the event of an acute health care crisis not previously covered by the practice agreement, such as a flu pandemic or other unforeseen emergency. Communications may occur in person, electronically, by telephone, or by an alternate method;

.. If there is only one physician party to the practice agreement, a protocol for designating an alternate physician for consultation in situations in which the physician is not available;

.. The signature of the physician assistant and the signature or signatures of the supervising physician. A practice agreement may be signed electronically using a method for electronic signatures approved by the commission; and

.. A termination provision. A physician assistant or physician may terminate the practice agreement as it applies to a single supervising physician without terminating the agreement with respect to the remaining participating physicians. If the termination results in no supervising physician being designated on the agreement, a new supervising physician must be designated for the agreement to be valid.

... Except as provided in (e)(ii) of this subsection, the physician assistant or supervising physician must provide written notice at least thirty days prior to the termination.

... The physician assistant or supervising physician may terminate the practice agreement immediately due to good faith concerns regarding unprofessional conduct or failure to practice medicine while exercising reasonable skill and safety.

. A practice agreement may be amended for any reason, such as to add or remove supervising physicians or alternate physicians or to amend the duties and responsibilities of the physician assistant.

. Whenever a physician assistant is practicing in a manner inconsistent with the practice agreement, the commission may take disciplinary action under chapter 18.130 RCW.

. Whenever a physician is subject to disciplinary action under chapter 18.130 RCW related to the practice of a physician assistant, the case must be referred to the appropriate disciplining authority.

. A physician assistant or physician may participate in more than one practice agreement if he or she is reasonably able to fulfill the duties and responsibilities in each agreement.

. A physician may supervise no more than ten physician assistants. A physician may petition the commission for a waiver of this limit. The commission shall automatically grant a waiver to any physician who possesses, on July 1, 2021, a valid waiver to supervise more than ten physician assistants. A physician granted a waiver under this subsection may not supervise more physician assistants than the physician is able to adequately supervise.

. A physician assistant must file with the commission in a form acceptable to the commission:

.. Each practice agreement into which the physician assistant enters under this section;

.. Any amendments to the practice agreement; and

.. Notice if the practice agreement is terminated.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2378-S.SL.pdf?cite=2020%20c%2080%20§%206[2020 c 80 § 6]; ]

== 18.71A.130 - Education and outreach campaign. (Effective July 1, 2021, until August 1, 2023.)
. The commission shall conduct an education and outreach campaign to make license holders, health carriers, and the public aware of the provisions of chapter 80, Laws of 2020.

. This section expires August 1, 2023.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2378-S.SL.pdf?cite=2020%20c%2080%20§%209[2020 c 80 § 9]; ]

== 18.71A.140 - Licenses issued under chapter  18.57A RCW. (Effective July 1, 2021.)
. On or after July 1, 2021, no new licenses may be issued under *chapter 18.57A RCW. The commission shall license physician assistants licensed under *chapter 18.57A RCW prior to July 1, 2021, as physician assistants under this chapter when they renew their licenses.

. The board of osteopathic medicine and surgery remains the disciplining authority under chapter 18.130 RCW for conduct occurring while a physician assistant is licensed under *chapter 18.57A RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2378-S.SL.pdf?cite=2020%20c%2080%20§%2010[2020 c 80 § 10]; ]

== 18.71A.150 - Rules—Chapter 80, Laws of 2020.
The commission and the board of osteopathic medicine and surgery shall adopt any rules necessary to implement chapter 80, Laws of 2020.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2378-S.SL.pdf?cite=2020%20c%2080%20§%2011[2020 c 80 § 11]; ]

== 18.71A.800 - Opioid drug prescribing rules—Adoption.
. By January 1, 2019, the commission must adopt rules establishing requirements for prescribing opioid drugs. The rules may contain exemptions based on education, training, amount of opioids prescribed, patient panel, and practice environment.

. In developing the rules, the commission must consider the agency medical directors' group and centers for disease control guidelines, and may consult with the department of health, the University of Washington, and the largest professional association of physician assistants in the state.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1427-S.SL.pdf?cite=2017%20c%20297%20§%207[2017 c 297 § 7]; ]

== 18.71A.810 - Opioid drugs—Right to refuse.
By January 1, 2020, the commission must adopt or amend its rules to require physician assistants who prescribe opioids to inform patients of their right to refuse an opioid prescription or order for any reason. If a patient indicates a desire to not receive an opioid, the physician assistant must document the patient's request and avoid prescribing or ordering opioids, unless the request is revoked by the patient.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5380-S.SL.pdf?cite=2019%20c%20314%20§%209[2019 c 314 § 9]; ]

