= 18.84 - Radiologic technologists.
:toc:

== 18.84.010 - Legislative intent—Insurance coverage not required.
It is the intent and purpose of this chapter to protect the public by the certification and registration of practitioners of radiological technology. By promoting high standards of professional performance, by requiring professional accountability, and by credentialing those persons who seek to provide radiological technology under the title of radiologic technologists, and by regulating all persons utilizing ionizing radiation on human beings this chapter identifies those practitioners who have achieved a particular level of competency. Nothing in this chapter shall be construed to require that individual or group policies or contracts of an insurance carrier, health care service contractor, or health maintenance organization provide benefits or coverage for services and supplies provided by a person certified under this chapter.

The legislature finds and declares that this chapter conforms to the guidelines, terms, and definitions for the credentialing of health or health-related professions specified under chapter 18.120 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6439-S.SL.pdf?cite=2008%20c%20246%20§%201[2008 c 246 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2037.SL.pdf?cite=1991%20c%20222%20§%201[1991 c 222 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c412.pdf?cite=1987%20c%20412%20§%201[1987 c 412 § 1]; ]

== 18.84.020 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Approved cardiovascular invasive specialist program" or "approved radiologist assistant program" means a school approved by the secretary. The secretary may recognize other organizations that establish standards for radiologist assistant programs or cardiovascular invasive specialist programs and designate schools that meet the organization's standards as approved.

. "Approved school of radiologic technology" means a school of radiologic technology, cardiovascular invasive specialist program, or radiologist assistant program approved by the secretary or a school found to maintain the equivalent of such a course of study as determined by the department. Such school may be operated by a medical or educational institution, and for the purpose of providing any requisite clinical experience, shall be affiliated with one or more general hospitals.

. "Cardiac or vascular catheterization" means all anatomic or physiological studies of intervention in which the heart, coronary arteries, or vascular system are entered via a systemic vein or artery using a catheter that is manipulated under fluoroscopic visualization.

. "Department" means the department of health.

. "Licensed practitioner" means any licensed health care practitioner performing services within the person's authorized scope of practice.

. "Radiologic technologist" means an individual certified under this chapter, other than a licensed practitioner, who practices radiologic technology as a:

.. Diagnostic radiologic technologist, who is a person who actually handles X-ray equipment in the process of applying radiation on a human being for diagnostic purposes at the direction of a licensed practitioner, this includes parenteral procedures related to radiologic technology when performed under the direct supervision of a physician licensed under chapter 18.71 or 18.57 RCW; 

.. Therapeutic radiologic technologist, who is a person who uses radiation-generating equipment for therapeutic purposes on human subjects at the direction of a licensed practitioner, this includes parenteral procedures related to radiologic technology when performed under the direct supervision of a physician licensed under chapter 18.71 or 18.57 RCW; 

.. Nuclear medicine technologist, who is a person who prepares radiopharmaceuticals and administers them to human beings for diagnostic and therapeutic purposes and who performs in vivo and in vitro detection and measurement of radioactivity for medical purposes at the direction of a licensed practitioner;

.. Radiologist assistant, who is an advanced-level certified diagnostic radiologic technologist who assists radiologists by performing advanced diagnostic imaging procedures as determined by rule under levels of supervision defined by the secretary, this includes but is not limited to enteral and parenteral procedures when performed under the direction of the supervising radiologist, and that these procedures may include injecting diagnostic agents to sites other than intravenous, performing diagnostic aspirations and localizations, and assisting radiologists with other invasive procedures; or

.. Cardiovascular invasive specialist, who is a person who assists in cardiac or vascular catheterization procedures under the personal supervision of a physician licensed under chapter 18.71 or 18.57 RCW. This includes parenteral procedures related to cardiac or vascular catheterization including, but not limited to, parenteral procedures involving arteries and veins.

. "Radiologic technology" means the use of ionizing radiation upon a human being for diagnostic or therapeutic purposes.

. "Radiologist" means a physician certified by the American board of radiology or the American osteopathic board of radiology.

. "Registered X-ray technician" means a person who is registered with the department, and who applies ionizing radiation at the direction of a licensed practitioner and who does not perform parenteral procedures.

. "Secretary" means the secretary of health.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2430-S.SL.pdf?cite=2010%20c%2092%20§%201[2010 c 92 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6439-S.SL.pdf?cite=2008%20c%20246%20§%202[2008 c 246 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2452.SL.pdf?cite=2000%20c%2093%20§%2042[2000 c 93 § 42]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20505[1994 sp.s. c 9 § 505]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2037.SL.pdf?cite=1991%20c%20222%20§%202[1991 c 222 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20204[1991 c 3 § 204]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c412.pdf?cite=1987%20c%20412%20§%203[1987 c 412 § 3]; ]

== 18.84.030 - Registration or certificate required.
No person may practice radiologic technology without being registered or certified under this chapter, unless that person is a licensed practitioner as defined in *RCW 18.84.020(3). A person represents himself or herself to the public as a certified radiologic technologist when that person adopts or uses a title or description of services that incorporates one or more of the following items or designations:

. Certified radiologic technologist or CRT, for persons so certified under this chapter;

. Certified radiologic therapy technologist, CRTT, or CRT, for persons certified in the therapeutic field;

. Certified radiologic diagnostic technologist, CRDT, or CRT, for persons certified in the diagnostic field; 

. Certified nuclear medicine technologist, CNMT, or CRT, for persons certified as nuclear medicine technologists; or

. Certified radiologist assistant or CRA for persons certified as radiologist assistants.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6439-S.SL.pdf?cite=2008%20c%20246%20§%203[2008 c 246 § 3]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2037.SL.pdf?cite=1991%20c%20222%20§%203[1991 c 222 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c412.pdf?cite=1987%20c%20412%20§%202[1987 c 412 § 2]; ]

== 18.84.040 - Powers of secretary—Application of uniform disciplinary act.
. In addition to any other authority provided by law, the secretary may:

.. Adopt rules, in accordance with chapter 34.05 RCW, necessary to implement this chapter;

.. Set all registration, certification, and renewal fees in accordance with RCW 43.70.250;

.. Establish forms and procedures necessary to administer this chapter;

.. Evaluate and designate those schools from which graduation will be accepted as proof of an applicant's eligibility to receive a certificate;

.. Determine whether alternative methods of training are equivalent to formal education, and to establish forms, procedures, and criteria for evaluation of an applicant's alternative training to determine the applicant's eligibility to receive a certificate;

.. Issue a certificate to any applicant who has met the education, training, examination, and conduct requirements for certification; and

.. Issue a registration to an applicant who meets the requirement for a registration.

. The secretary may hire clerical, administrative, and investigative staff as needed to implement this chapter.

. The uniform disciplinary act, chapter 18.130 RCW, governs the issuance and denial of registrations and certifications, unregistered and uncertified practice, and the discipline of registrants and certificants under this chapter. The secretary is the disciplining authority under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5995.SL.pdf?cite=2009%20c%20560%20§%2017[2009 c 560 § 17]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6439-S.SL.pdf?cite=2008%20c%20246%20§%204[2008 c 246 § 4]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20506[1994 sp.s. c 9 § 506]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2037.SL.pdf?cite=1991%20c%20222%20§%2011[1991 c 222 § 11]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20205[1991 c 3 § 205]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c412.pdf?cite=1987%20c%20412%20§%205[1987 c 412 § 5]; ]

== 18.84.050 - Record of proceedings.
The secretary shall keep an official record of all proceedings, a part of which record shall consist of a register of all applicants for certification under this chapter, with the result of each application.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20206[1991 c 3 § 206]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c412.pdf?cite=1987%20c%20412%20§%206[1987 c 412 § 6]; ]

== 18.84.070 - Secretary immune from liability.
The secretary or individuals acting on his or her behalf are immune from suit in any civil action based on any certification or disciplinary proceedings or other official acts performed in the course of their duties.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5995.SL.pdf?cite=2009%20c%20560%20§%2018[2009 c 560 § 18]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20507[1994 sp.s. c 9 § 507]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20208[1991 c 3 § 208]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c412.pdf?cite=1987%20c%20412%20§%208[1987 c 412 § 8]; ]

== 18.84.080 - Certification—Qualifications.
. The secretary shall issue a certificate to any applicant who demonstrates to the secretary's satisfaction, that the following requirements have been met to practice as:

.. A diagnostic radiologic technologist, therapeutic radiologic technologist, or nuclear medicine technologist:

... Graduation from an approved school or successful completion of alternate training that meets the criteria established by the secretary;

... Satisfactory completion of a radiologic technologist examination approved by the secretary; and

... Good moral character; 

.. A radiologist assistant:

... Satisfactory completion of an approved radiologist assistant program;

... Satisfactory completion of a radiologist assistant examination approved by the secretary; and

... Good moral character; or

.. A cardiovascular invasive specialist:

... Satisfactory completion of a cardiovascular invasive specialist program or alternate training approved by the secretary. The secretary may only approve a cardiovascular invasive specialist program that includes training in the following subjects: Cardiovascular anatomy and physiology, pharmacology, radiation physics and safety, radiation imaging and positioning, medical recordkeeping, and multicultural health as required by RCW 43.70.615(3);

... Satisfactory completion of a cardiovascular invasive specialist examination approved by the secretary. For purposes of this subsection (1)(c)(ii), the secretary may approve an examination administered by a national credentialing organization for cardiovascular invasive specialists; and

... Good moral character.

. Applicants shall be subject to the grounds for denial or issuance of a conditional license under chapter 18.130 RCW.

. The secretary shall establish by rule what constitutes adequate proof of meeting the requirements for certification and for designation of certification in a particular field of radiologic technology.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2430-S.SL.pdf?cite=2010%20c%2092%20§%202[2010 c 92 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6439-S.SL.pdf?cite=2008%20c%20246%20§%205[2008 c 246 § 5]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20209[1991 c 3 § 209]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c412.pdf?cite=1987%20c%20412%20§%209[1987 c 412 § 9]; ]

== 18.84.085 - Certification—Cardiovascular invasive specialists.
. Until July 1, 2012, the secretary shall, in addition to certificates issued under RCW 18.84.080, issue a cardiovascular invasive specialist certificate to any person who:

.. Has held a health care credential in good standing issued by the department for at least five years; and

.. Has at least five years, with at least one thousand hours per year, of prior experience in cardiac or vascular catheterization during the period of time the person held the health care credential under (a) of this subsection.

. A person certified as a cardiovascular invasive specialist under this section is subject to the same renewal requirements as all other certified cardiovascular invasive specialists, but shall not be subject to the education and examination requirements, unless he or she allows his or her certification to expire without renewal for more than one year. If the person allows his or her certification to expire without renewal for more than one year, he or she must meet the same education and examination requirements as all other certified cardiovascular invasive specialists before being issued a new certification.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2430-S.SL.pdf?cite=2010%20c%2092%20§%203[2010 c 92 § 3]; ]

== 18.84.090 - Certification—Approval of schools and training.
The secretary shall establish by rule the standards and procedures for approval of schools and alternate training, and may contract with individuals or organizations having expertise in the profession or in education to assist in evaluating those applying for approval. The standards and procedures set shall apply equally to schools and training within the United States and those in foreign jurisdictions.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20508[1994 sp.s. c 9 § 508]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20210[1991 c 3 § 210]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c412.pdf?cite=1987%20c%20412%20§%2010[1987 c 412 § 10]; ]

== 18.84.095 - Certification—Military training or experience.
An applicant with military training or experience satisfies the training or experience requirements of this chapter unless the secretary determines that the military training or experience is not substantially equivalent to the standards of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5307-S.SL.pdf?cite=2011%20c%2032%20§%209[2011 c 32 § 9]; ]

== 18.84.100 - Certification—Application form—Fee.
Applications for certification must be submitted on forms provided by the secretary. The secretary may require any information and documentation that reasonably relates to the determination of whether the applicant meets the requirements for certification provided for in this chapter and chapter 18.130 RCW. Each applicant shall comply with administrative procedures, administrative requirements, and fees determined by the secretary as provided in RCW 43.70.250 and 43.70.280.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2071[1996 c 191 § 71]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20211[1991 c 3 § 211]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c412.pdf?cite=1987%20c%20412%20§%2011[1987 c 412 § 11]; ]

== 18.84.110 - Renewal of certificates.
The secretary shall establish the administrative procedures, administrative requirements, and fees for renewal of certificates as provided in RCW 43.70.250 and 43.70.280.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2072[1996 c 191 § 72]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20509[1994 sp.s. c 9 § 509]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20212[1991 c 3 § 212]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c412.pdf?cite=1987%20c%20412%20§%2012[1987 c 412 § 12]; ]

== 18.84.120 - Registration—Fee—Requirements.
The secretary may issue a registration to an applicant who submits, on forms provided by the department, the applicant's name, the address, occupational title, name and location of business where applicant performs his or her services, and other information as determined by the secretary, including information necessary to determine whether there are grounds for denial of registration under this chapter or chapter 18.130 RCW. Each applicant shall pay a fee as determined by the secretary as provided in RCW 43.70.250 and 43.70.280. The secretary shall establish the administrative procedures, administrative requirements, and fees for registration and for renewal of registrations as provided in RCW 43.70.250 and 43.70.280.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2073[1996 c 191 § 73]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2037.SL.pdf?cite=1991%20c%20222%20§%204[1991 c 222 § 4]; ]

== 18.84.123 - Application, certification, and renewal fees.
In accordance with RCW 43.135.055, the department may establish application, certification, and renewal fees as necessary to recover the cost of implementing chapter 246, Laws of 2008.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3381.SL.pdf?cite=2008%20c%20285%20§%2014[2008 c 285 § 14]; ]

== 18.84.130 - Educational material.
The secretary may provide educational materials and training to registered X-ray technicians, certified radiologic technologists, licensed practitioners and the public concerning, but not limited to, health risks associated with ionizing radiation, proper radiographic techniques, and X-ray equipment maintenance. The secretary may charge fees to recover the cost of providing educational materials and training.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2037.SL.pdf?cite=1991%20c%20222%20§%205[1991 c 222 § 5]; ]

== 18.84.140 - Application of chapter—Exemption for authorized scope of practice.
Nothing in this chapter may be construed to prohibit or restrict the practice of a profession by a person who is either registered, certified, licensed, or similarly regulated under the laws of this state who is performing services within the person's authorized scope of practice.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2037.SL.pdf?cite=1991%20c%20222%20§%206[1991 c 222 § 6]; ]

== 18.84.150 - Application of chapter—Exemption for dentists.
This chapter does not apply to practitioners licensed under chapter 18.32 RCW or unlicensed persons supervised by persons licensed under chapter 18.32 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2037.SL.pdf?cite=1991%20c%20222%20§%207[1991 c 222 § 7]; ]

== 18.84.160 - Application of chapter—Exemption for chiropractors.
This chapter does not apply to practitioners licensed under chapter 18.25 RCW or unlicensed persons supervised by persons licensed under chapter 18.25 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2037.SL.pdf?cite=1991%20c%20222%20§%208[1991 c 222 § 8]; ]

== 18.84.170 - Registration deadline.
Persons required to register under this chapter must be registered by January 1, 1992.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2037.SL.pdf?cite=1991%20c%20222%20§%2010[1991 c 222 § 10]; ]

== 18.84.180 - Unprofessional conduct.
It is unprofessional conduct under chapter 18.130 RCW for any person registered or certified under this chapter to interpret images, make diagnoses, prescribe medications or therapies, or perform other procedures that may be prohibited by rule.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6439-S.SL.pdf?cite=2008%20c%20246%20§%206[2008 c 246 § 6]; ]

== 18.84.800 - Construction—Student practice.
Nothing in this chapter may be construed to prohibit or restrict practice by a regularly enrolled student in a cardiovascular invasive specialist program approved by the secretary whose practice is pursuant to a regular course of instruction or assignments. Persons practicing under this section must be clearly identified as students.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2430-S.SL.pdf?cite=2010%20c%2092%20§%204[2010 c 92 § 4]; ]

== 18.84.901 - Effective date—1987 c 412.
This act shall take effect October 1, 1987.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c412.pdf?cite=1987%20c%20412%20§%2017[1987 c 412 § 17]; ]

== 18.84.903 - Effective date—1991 c 222.
This act is necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and shall take effect July 1, 1991.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2037.SL.pdf?cite=1991%20c%20222%20§%2014[1991 c 222 § 14]; ]

