= 18.19 - Counselors.
:toc:

== 18.19.010 - Legislative findings—Insurance benefits not mandated.
The qualifications and practices of counselors in this state are virtually unknown to potential clients. Beyond the regulated practices of psychiatry and psychology, there are a considerable variety of disciplines, theories, and techniques employed by other counselors under a number of differing titles. The legislature recognizes the right of all counselors to practice their skills freely, consistent with the requirements of the public health and safety, as well as the right of individuals to choose which counselors best suit their needs and purposes. This chapter shall not be construed to require or prohibit that individual or group policies or contracts of an insurance carrier, health care service contractor, or health maintenance organization provide benefits or coverage for services and supplies provided by a person registered under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5877-S.SL.pdf?cite=2001%20c%20251%20§%2017[2001 c 251 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c512.pdf?cite=1987%20c%20512%20§%201[1987 c 512 § 1]; ]

== 18.19.020 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Agency" means (a) an agency or facility operated, licensed, or certified by the state of Washington; (b) a federally recognized Indian tribe located within the state; or (c) a county.

. "Agency affiliated counselor" means a person registered under this chapter who is engaged in counseling and employed by an agency. "Agency affiliated counselor" includes juvenile probation counselors who are employees of the juvenile court under RCW 13.04.035 and 13.04.040 and juvenile court employees providing functional family therapy, aggression replacement training, or other evidence-based programs approved by the department of children, youth, and families.

. "Certified adviser" means a person certified under this chapter who is engaged in private practice counseling to the extent authorized in RCW 18.19.200.

. "Certified counselor" means a person certified under this chapter who is engaged in private practice counseling to the extent authorized in RCW 18.19.200.

. "Client" means an individual who receives or participates in counseling or group counseling.

. "Counseling" means employing any therapeutic techniques, including but not limited to social work, mental health counseling, marriage and family therapy, and hypnotherapy, for a fee that offer, assist or attempt to assist an individual or individuals in the amelioration or adjustment of mental, emotional, or behavioral problems, and includes therapeutic techniques to achieve sensitivity and awareness of self and others and the development of human potential. For the purposes of this chapter, nothing may be construed to imply that the practice of hypnotherapy is necessarily limited to counseling.

. "Counselor" means an individual, practitioner, therapist, or analyst who engages in the practice of counseling to the public for a fee, including for the purposes of this chapter, hypnotherapists.

. "Department" means the department of health.

. "Hypnotherapist" means a person registered under this chapter who is practicing hypnosis as a modality.

. "Private practice counseling" means the practice of counseling by a certified counselor or certified adviser as specified in RCW 18.19.200.

. "Psychotherapy" means the practice of counseling using diagnosis of mental disorders according to the fourth edition of the diagnostic and statistical manual of mental disorders, published in 1994, and the development of treatment plans for counseling based on diagnosis of mental disorders in accordance with established practice standards.

. "Secretary" means the secretary of the department or the secretary's designee.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5955-S.SL.pdf?cite=2019%20c%20470%20§%203[2019 c 470 § 3]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1939.SL.pdf?cite=2011%20c%2086%20§%201[2011 c 86 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6884-S.SL.pdf?cite=2010%201st%20sp.s.%20c%2020%20§%201[2010 1st sp.s. c 20 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2674-S2.SL.pdf?cite=2008%20c%20135%20§%201[2008 c 135 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5877-S.SL.pdf?cite=2001%20c%20251%20§%2018[2001 c 251 § 18]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2019[1991 c 3 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c512.pdf?cite=1987%20c%20512%20§%203[1987 c 512 § 3]; ]

== 18.19.030 - Registration required—Counselors.
A person may not, as a part of his or her position as an employee of a state agency, practice counseling without being registered to practice as an agency affiliated counselor by the department under this chapter unless exempt under RCW 18.19.040.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2674-S2.SL.pdf?cite=2008%20c%20135%20§%202[2008 c 135 § 2]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5877-S.SL.pdf?cite=2001%20c%20251%20§%2019[2001 c 251 § 19]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2020[1991 c 3 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c512.pdf?cite=1987%20c%20512%20§%202[1987 c 512 § 2]; ]

== 18.19.031 - Registered counselor credentials—Limitation on issuance.
The department of health may not issue any new registered counselor credentials after July 1, 2009.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2674-S2.SL.pdf?cite=2008%20c%20135%20§%2022[2008 c 135 § 22]; ]

== 18.19.035 - Registration required—Hypnotherapists.
A person may not, for a fee or as a part of his or her position as an employee of a state agency, practice hypnotherapy without being registered to practice as a hypnotherapist by the department under this chapter unless exempt under RCW 18.19.040.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2674-S2.SL.pdf?cite=2008%20c%20135%20§%203[2008 c 135 § 3]; ]

== 18.19.040 - Exemptions.
Nothing in this chapter may be construed to prohibit or restrict:

. The practice of a profession by a person who is either registered, certified, licensed, or similarly regulated under the laws of this state and who is performing services within the person's authorized scope of practice, including any attorney admitted to practice law in this state when providing counseling incidental to and in the course of providing legal counsel;

. The practice of counseling by an employee or trainee of any federal agency, or the practice of counseling by a student of a college or university, if the employee, trainee, or student is practicing solely under the supervision of and accountable to the agency, college, or university, through which he or she performs such functions as part of his or her position for no additional fee other than ordinary compensation;

. The practice of counseling by a person for no compensation;

. The practice of counseling by persons offering services for public and private nonprofit organizations or charities not primarily engaged in counseling for a fee when approved by the organizations or agencies for whom they render their services;

. Evaluation, consultation, planning, policy-making, research, or related services conducted by social scientists for private corporations or public agencies;

. The practice of counseling by a person under the auspices of a religious denomination, church, or organization, or the practice of religion itself;

. The practice of counseling by peer counselors who use their own experience to encourage and support people with similar conditions or activities related to the training of peer counselors; and

. Counselors who reside outside Washington state from providing up to ten days per quarter of training or workshops in the state, as long as they do not hold themselves out to be registered or certified in Washington state.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2674-S2.SL.pdf?cite=2008%20c%20135%20§%205[2008 c 135 § 5]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5877-S.SL.pdf?cite=2001%20c%20251%20§%2020[2001 c 251 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c512.pdf?cite=1987%20c%20512%20§%204[1987 c 512 § 4]; ]

== 18.19.050 - Powers of secretary—Application of uniform disciplinary act—Public education program.
. In addition to any other authority provided by law, the secretary has the following authority:

.. To adopt rules, in accordance with chapter 34.05 RCW, necessary to implement this chapter;

.. To set all registration, certification, and renewal fees in accordance with RCW 43.70.250 and to collect and deposit all such fees in the health professions account established under RCW 43.70.320;

.. To establish forms and procedures necessary to administer this chapter;

.. To hire clerical, administrative, and investigative staff as needed to implement this chapter;

.. To issue a registration or certification to any applicant who has met the requirements for registration or certification; and

.. To establish education equivalency, examination, supervisory, consultation, and continuing education requirements for certified counselors and certified advisers.

. The uniform disciplinary act, chapter 18.130 RCW, governs the issuance and denial of registrations and certifications and the discipline of registrants under this chapter. The secretary shall be the disciplining authority under this chapter. 

. The department shall publish and disseminate information to educate the public about the responsibilities of counselors, the types of counselors, and the rights and responsibilities of clients established under this chapter. The secretary may assess an additional fee for each application and renewal to fund public education efforts under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2674-S2.SL.pdf?cite=2008%20c%20135%20§%206[2008 c 135 § 6]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5877-S.SL.pdf?cite=2001%20c%20251%20§%2021[2001 c 251 § 21]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2021[1991 c 3 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c512.pdf?cite=1987%20c%20512%20§%205[1987 c 512 § 5]; ]

== 18.19.060 - Information disclosure to clients.
Certified counselors and certified advisers shall provide clients at the commencement of any program of treatment with accurate disclosure information concerning their practice, in accordance with guidelines developed by the department, that will inform clients of the purposes of and resources available under this chapter, including the right of clients to refuse treatment, the responsibility of clients for choosing the provider and treatment modality which best suits their needs, and the extent of confidentiality provided by this chapter, the department, another agency, or other jurisdiction. The disclosure statement must inform the client of the certified counselor's or certified adviser's consultation arrangement or supervisory agreement as defined in rules adopted by the secretary. The disclosure information provided by the certified counselor or certified adviser, the receipt of which shall be acknowledged in writing by the certified counselor or certified adviser and the client, shall include any relevant education and training, the therapeutic orientation of the practice, the proposed course of treatment where known, any financial requirements, referral resources, and such other information as the department may require by rule. The disclosure information shall also include a statement that the certification of an individual under this chapter does not include a recognition of any practice standards, nor necessarily imply the effectiveness of any treatment. Certified counselors and certified advisers must also disclose that they are not credentialed to diagnose mental disorders or to conduct psychotherapy as defined by the secretary by rule. The client is not liable for any fees or charges for services rendered prior to receipt of the disclosure statement.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2674-S2.SL.pdf?cite=2008%20c%20135%20§%207[2008 c 135 § 7]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5877-S.SL.pdf?cite=2001%20c%20251%20§%2022[2001 c 251 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c512.pdf?cite=1987%20c%20512%20§%206[1987 c 512 § 6]; ]

== 18.19.080 - Official records.
The secretary shall keep an official record of all proceedings, a part of which record shall consist of a register of all applicants for registration under this chapter, with the result of each application.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5877-S.SL.pdf?cite=2001%20c%20251%20§%2023[2001 c 251 § 23]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2023[1991 c 3 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c512.pdf?cite=1987%20c%20512%20§%208[1987 c 512 § 8]; ]

== 18.19.090 - Application for credentials—Contents—Form—Requirements.
. Application for agency affiliated counselor, certified counselor, certified adviser, or hypnotherapist must be made on forms approved by the secretary. The secretary may require information necessary to determine whether applicants meet the qualifications for the credential and whether there are any grounds for denial of the credential, or for issuance of a conditional credential, under this chapter or chapter 18.130 RCW. The application for agency affiliated counselor, certified counselor, or certified adviser must include a description of the applicant's orientation, discipline, theory, or technique. Each applicant shall pay a fee determined by the secretary as provided in RCW 43.70.250, which shall accompany the application.

. Applicants for agency affiliated counselor must provide satisfactory documentation that they are employed by an agency or have an offer of employment from an agency.

. At the time of application for initial certification, applicants for certified counselor prior to July 1, 2010, are required to:

.. Have been registered for no less than five years at the time of application for an initial certification;

.. Have held a valid, active registration that is in good standing and be in compliance with any disciplinary process and orders at the time of application for an initial certification;

.. Show evidence of having completed coursework in risk assessment, ethics, appropriate screening and referral, and Washington state law and other subjects identified by the secretary;

.. Pass an examination in risk assessment, ethics, appropriate screening and referral, and Washington state law, and other subjects as determined by the secretary; and

.. Have a written consultation agreement with a credential holder who meets the qualifications established by the secretary.

. Unless eligible for certification under subsection (3) of this section, applicants for certified counselor or certified adviser are required to:

.. [Empty]
... Have a bachelor's degree in a counseling-related field, if applying for certified counselor; or

... Have an associate degree in a counseling-related field and a supervised internship, if applying for certified adviser;

.. Pass an examination in risk assessment, ethics, appropriate screening and referral, and Washington state law, and other subjects as determined by the secretary; and

.. Have a written supervisory agreement with a supervisor who meets the qualifications established by the secretary.

. Each applicant shall include payment of the fee determined by the secretary as provided in RCW 43.70.250.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2674-S2.SL.pdf?cite=2008%20c%20135%20§%208[2008 c 135 § 8]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2024[1991 c 3 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c512.pdf?cite=1987%20c%20512%20§%209[1987 c 512 § 9]; ]

== 18.19.095 - Agency affiliated counselor practicing as peer counselor—No automatic denial of applicant with past conviction for certain offenses—Conditions.
The department may not automatically deny an applicant for registration under this chapter for a position as an agency affiliated counselor practicing as a peer counselor in an agency or facility based on a conviction history consisting of convictions for simple assault, assault in the fourth degree, prostitution, theft in the third degree, theft in the second degree, or forgery, the same offenses as they may be renamed, or substantially equivalent offenses committed in other states or jurisdictions if:

. At least one year has passed between the applicant's most recent conviction for an offense set forth in this section and the date of application for employment;

. The offense was committed as a result of the person's substance use or untreated mental health symptoms; and

. The applicant is at least one year in recovery from a substance use disorder, whether through abstinence or stability on medication-assisted therapy, or in recovery from mental health challenges.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1907-S2.SL.pdf?cite=2019%20c%20446%20§%2045[2019 c 446 § 45]; ]

== 18.19.100 - Renewal of credentials.
The secretary shall establish administrative procedures, administrative requirements, continuing education, and fees for renewal of credentials as provided in RCW 43.70.250 and 43.70.280. When establishing continuing education requirements for agency affiliated counselors, the secretary shall consult with the appropriate state agency director responsible for licensing, certifying, or operating the relevant agency practice setting.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2674-S2.SL.pdf?cite=2008%20c%20135%20§%2010[2008 c 135 § 10]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%205[1996 c 191 § 5]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2025[1991 c 3 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c512.pdf?cite=1987%20c%20512%20§%2010[1987 c 512 § 10]; ]

== 18.19.180 - Confidential communications.
An individual registered under this chapter shall not disclose the written acknowledgment of the disclosure statement pursuant to RCW 18.19.060 nor any information acquired from persons consulting the individual in a professional capacity when that information was necessary to enable the individual to render professional services to those persons except:

. With the written consent of that person or, in the case of death or disability, the person's personal representative, other person authorized to sue, or the beneficiary of an insurance policy on the person's life, health, or physical condition;

. That a person registered under this chapter is not required to treat as confidential a communication that reveals the contemplation or commission of a crime or harmful act;

. If the person is a minor, and the information acquired by the person registered under this chapter indicates that the minor was the victim or subject of a crime, the person registered may testify fully upon any examination, trial, or other proceeding in which the commission of the crime is the subject of the inquiry;

. If the person waives the privilege by bringing charges against the person registered under this chapter;

. In response to a subpoena from a court of law or the secretary. The secretary may subpoena only records related to a complaint or report under chapter 18.130 RCW; or

. As required under chapter 26.44 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5877-S.SL.pdf?cite=2001%20c%20251%20§%2024[2001 c 251 § 24]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2033[1991 c 3 § 33]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c512.pdf?cite=1987%20c%20512%20§%2011[1987 c 512 § 11]; ]

== 18.19.190 - Other professions not affected.
This chapter shall not be construed as permitting the administration or prescription of drugs or in any way infringing upon the practice of medicine and surgery as defined in chapter 18.71 RCW, or in any way infringing upon the practice of psychology as defined in chapter 18.83 RCW, or restricting the scope of the practice of counseling for those registered under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5877-S.SL.pdf?cite=2001%20c%20251%20§%2025[2001 c 251 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c512.pdf?cite=1987%20c%20512%20§%2018[1987 c 512 § 18]; ]

== 18.19.200 - Scope of practice—Certified counselors and certified advisers.
The scope of practice of certified counselors and certified advisers consists exclusively of the following:

. Appropriate screening of the client's level of functional impairment using the global assessment of functioning as described in the fourth edition of the diagnostic and statistical manual of mental disorders, published in 1994. Recognition of a mental or physical disorder or a global assessment of functioning score of sixty or less requires that the certified counselor or certified adviser refer the client to a physician, osteopathic physician, psychiatric registered nurse practitioner, or licensed mental health practitioner, as defined by the secretary, for diagnosis and treatment;

. Certified counselors and certified advisers may counsel and guide a client in adjusting to life situations, developing new skills, and making desired changes, in accordance with the theories and techniques of a specific counseling method and established practice standards, if the client has a global assessment of functioning score greater than sixty;

. Certified counselors may counsel and guide a client in adjusting to life situations, developing new skills, and making desired changes if the client has a global assessment of functioning score of sixty or less if:

.. The client has been referred to the certified counselor by a physician, osteopathic physician, psychiatric registered nurse practitioner, or licensed mental health practitioner, as defined by the secretary, and care is provided as part of a plan of treatment developed by the referring practitioner who is actively treating the client. The certified counselor must adhere to any conditions related to the certified counselor's role as specified in the plan of care; or

.. The certified counselor referred the client to seek diagnosis and treatment from a physician, osteopathic physician, psychiatric registered nurse practitioner, or licensed mental health practitioner, as defined by the secretary, and the client refused, in writing, to seek treatment from the other provider. The certified counselor may provide services to the client consistent with a treatment plan developed by the certified counselor and the consultant or supervisor with whom the certified counselor has a written consultation or supervisory agreement. A certified counselor shall not be a sole treatment provider for a client with a global assessment of functioning score of less than fifty.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2674-S2.SL.pdf?cite=2008%20c%20135%20§%204[2008 c 135 § 4]; ]

== 18.19.210 - Agency affiliated counselors—Employment status—Duty to notify department.
. [Empty]
.. An applicant for registration as an agency affiliated counselor who applies to the department within thirty days of employment by an agency may work as an agency affiliated counselor while the application is processed. The applicant must provide required documentation within reasonable time limits established by the department, and if the applicant does not do so, the applicant must stop working.

.. The applicant may not provide unsupervised counseling prior to completion of a criminal background check performed by either the employer or the secretary. For purposes of this subsection, "unsupervised" means the supervisor is not physically present at the location where the counseling occurs.

. Agency affiliated counselors shall notify the department if they are either no longer employed by the agency identified on their application or are now employed with another agency, or both. Agency affiliated counselors may not engage in the practice of counseling unless they are currently affiliated with an agency.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1907-S2.SL.pdf?cite=2019%20c%20446%20§%2047[2019 c 446 § 47]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5732-S2.SL.pdf?cite=2013%20c%20338%20§%206[2013 c 338 § 6]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2674-S2.SL.pdf?cite=2008%20c%20135%20§%209[2008 c 135 § 9]; ]

== 18.19.220 - Certified counselors and hypnotherapist advisory committee.
The Washington state-certified counselors and hypnotherapist advisory committee is established.

. The committee is comprised of seven members. Two committee members must be certified counselors or certified advisers. Two committee members must be hypnotherapists. Three committee members must be consumers and represent the public at large and may not hold any mental health care provider license, certification, or registration.

. Two committee members must be appointed for a term of one year, two committee members must be appointed for a term of two years, and three committee members must be appointed for a term of three years. Subsequent committee members must be appointed for terms of three years. A person may not serve as a committee member for more than two consecutive terms.

. [Empty]
.. Each committee member must be a resident of the state of Washington.

.. A committee member may not hold an office in a professional association for their profession.

.. Advisory committee members may not be employed by the state of Washington.

.. Each professional committee member must have been actively engaged in their profession for five years immediately preceding appointment.

.. The consumer committee members must represent the general public and be unaffiliated directly or indirectly with the professions credentialed under this chapter.

. The secretary shall appoint the committee members.

. Committee members are immune from suit in an action, civil or criminal, based on the department's disciplinary proceedings or other official acts performed in good faith.

. Committee members must be compensated in accordance with RCW 43.03.240, including travel expenses in carrying out his or her authorized duties in accordance with RCW 43.03.050 and 43.03.060.

. The committee shall elect a chair and vice chair.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2674-S2.SL.pdf?cite=2008%20c%20135%20§%2019[2008 c 135 § 19]; ]

== 18.19.900 - Short title.
This chapter shall be known as the omnibus credentialing act for counselors.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c512.pdf?cite=1987%20c%20512%20§%2020[1987 c 512 § 20]; ]

== 18.19.902 - Registered counselor credential abolished.
To practice counseling, all registered counselors must obtain another health profession credential by July 1, 2010. The registered counselor credential is abolished July 1, 2010.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2674-S2.SL.pdf?cite=2008%20c%20135%20§%2020[2008 c 135 § 20]; ]

