= 18.59 - Occupational therapy.
:toc:

== 18.59.010 - Purpose.
In order to safeguard the public health, safety, and welfare; to protect the public from being mislead by incompetent, unethical, and unauthorized persons; to assure the highest degree of professional conduct on the part of occupational therapists and occupational therapy assistants; and to assure the availability of occupational therapy services of high quality to persons in need of such services, it is the purpose of this chapter to provide for the regulation of persons offering occupational therapy services to the public.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c9.pdf?cite=1984%20c%209%20§%202[1984 c 9 § 2]; ]

== 18.59.020 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Board" means the board of occupational therapy practice.

. "Department" means the department of health.

. "Occupational therapist" means a person licensed to practice occupational therapy under this chapter.

. "Occupational therapy" is the scientifically based use of purposeful activity with individuals who are limited by physical injury or illness, psychosocial dysfunction, developmental or learning disabilities, or the aging process in order to maximize independence, prevent disability, and maintain health. The practice encompasses evaluation, treatment, and consultation. Specific occupational therapy services include but are not limited to: Using specifically designed activities and exercises to enhance neurodevelopmental, cognitive, perceptual motor, sensory integrative, and psychomotor functioning; administering and interpreting tests such as manual muscle and sensory integration; teaching daily living skills; developing prevocational skills and play and avocational capabilities; designing, fabricating, or applying selected orthotic and prosthetic devices or selected adaptive equipment; wound care management as provided in RCW 18.59.170; and adapting environments for persons with disabilities. These services are provided individually, in groups, or through social systems.

. "Occupational therapy aide" means a person who is trained to perform specific occupational therapy techniques under professional supervision as defined by the board but who does not perform activities that require advanced training in the sciences or practices involved in the profession of occupational therapy.

. "Occupational therapy assistant" means a person licensed to assist in the practice of occupational therapy under the supervision or with the regular consultation of an occupational therapist.

. "Occupational therapy practitioner" means a person who is credentialed as an occupational therapist or occupational therapy assistant.

. "Person" means any individual, partnership, unincorporated organization, or corporate body, except that only an individual may be licensed under this chapter.

. "Secretary" means the secretary of health.

. "Sharp debridement" means the removal of loose or loosely adherent devitalized tissue with the use of tweezers, scissors, or scalpel, without any type of anesthesia other than topical anesthetics. "Sharp debridement" does not mean surgical debridement.

. "Wound care management" means a part of occupational therapy treatment that facilitates healing, prevents edema, infection, and excessive scar formation, and minimizes wound complications. Treatment may include: Assessment of wound healing status; patient education; selection and application of dressings; cleansing of the wound and surrounding areas; application of topical medications, as provided under RCW 18.59.160; use of physical agent modalities; application of pressure garments and nonweight-bearing orthotic devices, excluding high-temperature custom foot orthotics made from a mold; sharp debridement of devitalized tissue; debridement of devitalized tissue with other agents; and adapting activities of daily living to promote independence during wound healing.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5018-S.SL.pdf?cite=2011%20c%2088%20§%201[2011 c 88 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1113-S.SL.pdf?cite=1999%20c%20333%20§%201[1999 c 333 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20153[1991 c 3 § 153]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c9.pdf?cite=1984%20c%209%20§%203[1984 c 9 § 3]; ]

== 18.59.031 - License required.
No person may practice or represent himself or herself as an occupational therapy practitioner without first having a valid license to do so.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1113-S.SL.pdf?cite=1999%20c%20333%20§%202[1999 c 333 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c150.pdf?cite=1987%20c%20150%20§%2044[1987 c 150 § 44]; ]

== 18.59.040 - Activities not regulated by chapter—Limited permits.
This chapter shall not be construed as preventing or restricting the practice, services, or activities of:

. A person licensed in this state under any other law from engaging in the profession or occupation for which the person is licensed;

. A person employed as an occupational therapist or occupational therapy assistant by the government of the United States, if the person provides occupational therapy solely under the directions or control of the organization by which the person is employed;

. A person pursuing a course of study leading to a degree or certificate in occupational therapy in an accredited or approved educational program if the activities and services constitute a part of a supervised course of study, if the person is designated by a title which clearly indicated the person's status as a student or trainee;

. A person fulfilling the supervised fieldwork experience requirements of RCW 18.59.050, if the activities and services constitute a part of the experience necessary to meet the requirements of RCW 18.59.050;

. A person performing occupational therapy services in the state, if the services are performed for no more than ninety working days and if:

.. The person is licensed under the laws of another state which has licensure requirements at least as stringent as the requirements of this chapter, as determined by the board; or

.. The person has met commonly accepted standards for the practice of occupational therapy as specifically defined by the board;

. A person employed by or supervised by an occupational therapist as an occupational therapy aide;

. A person with a limited permit. A limited permit may be granted to persons who have completed the education and experience requirements of this chapter, or education and experience requirements which the board deems equivalent to those specified as requirements for licensure. The limited permit allows the applicant to practice in association with an occupational therapist. The limited permit is valid until the results of the next examination have been made public. One extension of this permit may be granted if the applicant has failed the examination, but during this period the person shall be under the direct supervision of an occupational therapist;

. Any persons who teach daily living skills, develop prevocational skills, and play and avocational capabilities, or adapt equipment or environments for individuals with disabilities, or who do specific activities to enhance cognitive, perceptual motor, sensory integrative and psychomotor skills, but who do not hold themselves out to the public by any title, initials, or description of services as being engaged in the practice of occupational therapy; or

. Any person who designs, fabricates, or applies orthotic or prosthetic devices which are prescribed by a health care professional authorized by the laws of the state of Washington to prescribe the device or to direct the design, fabrication or application of the device.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2390.SL.pdf?cite=2020%20c%20274%20§%202[2020 c 274 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c296.pdf?cite=1985%20c%20296%20§%201[1985 c 296 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c9.pdf?cite=1984%20c%209%20§%205[1984 c 9 § 5]; ]

== 18.59.050 - Licenses—Application—Requirements—Waiver.
. An applicant applying for a license as an occupational therapist or as an occupational therapy assistant shall file a written application on forms provided by the department showing to the satisfaction of the board that the applicant meets the requirements specified in this subsection.

.. The applicant shall be of good moral character.

.. The applicant shall present evidence satisfactory to the board of having successfully completed the academic requirements of an educational program in occupational therapy recognized by the board, with concentration in biological or physical science, psychology, sociology, and with education in selected manual skills.

... For an occupational therapist, such a program shall be nationally accredited and approved by rules of the board.

... For an occupational therapy assistant, such a program shall be nationally accredited and approved by rules of the board.

.. The applicant shall submit to the board evidence of having successfully completed a period of supervised fieldwork experience at a recognized educational institution or a training program approved by the educational institution at which the applicant met the academic requirements.

... For an occupational therapist, a minimum of six months of supervised fieldwork experience is required.

... For an occupational therapy assistant, a minimum of two months of supervised fieldwork experience is required.

.. An applicant for licensure as an occupational therapist or as an occupational therapy assistant shall pass an examination as provided in RCW 18.59.060.

. The board may waive the educational requirements specified under subsection (1)(b)(ii) of this section for an occupational therapy assistant who has met the experience and any other requirements established by the board. Upon successful completion of the examination required of the occupational therapist, the individual shall be granted a license.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c9.pdf?cite=1984%20c%209%20§%206[1984 c 9 § 6]; ]

== 18.59.060 - Examinations.
. A person applying for licensure shall demonstrate eligibility in accordance with RCW 18.59.050 and shall apply for examination upon a form and in such a manner as the department prescribes. The application shall be accompanied by the fee prescribed by RCW 18.59.110, which fee shall not be refunded. A person who fails an examination may apply for reexamination. The application shall be accompanied by the prescribed fee.

. An applicant for licensure under this chapter shall be given a written examination to test the applicant's knowledge of the basic and clinical sciences relating to occupational therapy and occupational therapy theory and practice, including the applicant's professional skills of occupational therapy techniques and methods, and such other subjects as the board deems useful to determine the applicant's fitness to practice. The board shall approve the examination and establish standards for acceptable performance.

. Applicants for licensure shall be examined at a time and place and under such supervision as the board may determine. The examination shall be given at least twice each year at such places as the board determines, and the board shall give reasonable public notice of the examinations in accordance with its rules at least sixty days prior to the administration of the examination.

. Applicants may obtain their examination scores and may review their papers in accordance with such rules as the board establishes.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c9.pdf?cite=1984%20c%209%20§%207[1984 c 9 § 7]; ]

== 18.59.070 - Waiver of examination and licensing requirements—Applicants licensed in other states or territories.
. The board shall waive the examination and grant a license to a person engaged in the profession of an occupational therapist or an occupational therapy assistant on June 7, 1984, if the board determines that the person meets commonly accepted standards for the profession, as established by rule of the board. The board may waive the examination, education, or experience requirements and grant a license to any person meeting the standards adopted by the board under this section after June 7, 1984, if the board considers the requirements for licensure in this chapter as having been met.

. The board may grant a license to any applicant who presents proof of current licensure as an occupational therapist or occupational therapy assistant in another state, the District of Columbia, or a territory of the United States, which requires standards for licensure considered by the board to be equivalent to the requirements for licensure under this chapter.

. The board shall waive the education and experience requirements for licensure in RCW 18.59.050(1) (c) and (d) for applicants for licensure who present evidence to the board that they have been engaged in the practice of occupational therapy for the three years immediately prior to June 7, 1984. The proof of actual practice shall be presented to the board in such a manner as the board prescribes by rule. To obtain the waiver, an applicant shall file an application for examination no later than six months from June 7, 1984. An applicant who has filed for examination under this subsection shall be excluded from the licensure requirement until the date the results of the examination are made public, and may conduct the appropriate activities under *RCW 18.59.030.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c9.pdf?cite=1984%20c%209%20§%208[1984 c 9 § 8]; ]

== 18.59.080 - License issuance—Posting required.
The secretary shall issue a license to a person who meets the licensing requirements of this chapter upon payment of the prescribed license fee. The license shall be posted in a conspicuous location at the person's work site.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20154[1991 c 3 § 154]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c9.pdf?cite=1984%20c%209%20§%209[1984 c 9 § 9]; ]

== 18.59.090 - Renewal of licenses—Reinstatement of suspended or revoked licenses—Inactive status.
. Licenses under this chapter shall be renewed at the time and in the manner determined by the secretary and with the payment of a renewal fee. The board shall establish requirements for license renewal which provide evidence of continued competency. The secretary may provide for the late renewal of a license upon the payment of a late fee in accordance with its rules which may include additional continuing education or examination requirements.

. A suspended license is subject to expiration and may be renewed as provided in this section, but the renewal does not entitle the licensee, while the license remains suspended and until it is reinstated, to engage in the licensed activity, or in any other conduct or activity in violation of the order or judgment by which the license was suspended. If a license revoked on disciplinary grounds is reinstated, the licensee, as a condition of reinstatement, shall pay the renewal fee and any applicable late fee.

. Any occupational therapist or occupational therapy assistant licensed under this chapter not practicing occupational therapy or providing services may place his or her license in an inactive status. The secretary may prescribe requirements for maintaining an inactive status and converting from an inactive or active status.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20155[1991 c 3 § 155]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c13.pdf?cite=1990%20c%2013%20§%201[1990 c 13 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c9.pdf?cite=1984%20c%209%20§%2010[1984 c 9 § 10]; ]

== 18.59.100 - Duty to refer medical cases.
An occupational therapist shall, after evaluating a patient and if the case is a medical one, refer the case to a physician for appropriate medical direction if such direction is lacking. Treatment by an occupational therapist of such a medical case may take place only upon the referral of a physician, osteopathic physician, podiatric physician and surgeon, naturopath, chiropractor, physician assistant, psychologist, optometrist, or advanced registered nurse practitioner licensed to practice in this state.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1010-S.SL.pdf?cite=2015%20c%2010%20§%201[2015 c 10 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1113-S.SL.pdf?cite=1999%20c%20333%20§%203[1999 c 333 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c259.pdf?cite=1986%20c%20259%20§%20101[1986 c 259 § 101]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c9.pdf?cite=1984%20c%209%20§%2011[1984 c 9 § 11]; ]

== 18.59.110 - Applications—Licenses—Limited permits.
Administrative procedures, administrative requirements, and fees shall be established as provided in RCW 43.70.250 and 43.70.280 for applications, initial and renewal licenses, and limited permits.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2041[1996 c 191 § 41]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20156[1991 c 3 § 156]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%2058[1985 c 7 § 58]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c9.pdf?cite=1984%20c%209%20§%2012[1984 c 9 § 12]; ]

== 18.59.120 - Board of occupational therapy practice established—Members—Terms—Meetings—Compensation.
. There is established a board of occupational therapy practice. The board shall consist of five members appointed by the governor, who may consider the persons who are recommended for appointment by occupational therapy associations of the state. The members of the board shall be residents of the state. Four of the members shall have been engaged in rendering services to the public, teaching, or research in occupational therapy for at least five years immediately preceding their appointment. Three of these four board members shall be occupational therapists who shall at all times be holders of licenses for the practice of occupational therapy in the state, except for the initial members of the board, all of whom shall fulfill the requirements for licensure under this chapter. At least one member of the board shall be an occupational therapy assistant licensed to assist in the practice of occupational therapy, except for the initial member appointed to this position, who shall fulfill the requirements for licensure as a occupational therapy assistant under this chapter. The remaining member of the board shall be a member of the public with an interest in the rights of consumers of health services.

. The governor shall, within sixty days after June 7, 1984, appoint one member for a term of one year, two members for a term of two years, and two members for a term of three years.  Appointments made thereafter shall be for three-year terms, but no person shall be appointed to serve more than two consecutive full terms. Terms shall begin on the first day of the calendar year and end on the last day of the calendar year or until successors are appointed, except for the initial appointed members, who shall serve through the last calendar day of the year in which they are appointed before commencing the terms prescribed by this section. The governor shall make appointments for vacancies in unexpired terms within ninety days after the vacancies occur.

. The board shall meet during the first month of each calendar year to select a chair and for other purposes. At least one additional meeting shall be held before the end of each calendar year. Further meetings may be convened at the call of the chair or the written request of any two board members. A majority of members of the board constitutes a quorum for all purposes. All meetings of the board shall be open to the public, except that the board may hold closed sessions to prepare, approve, grade, or administer examinations or, upon request of an applicant who fails an examination, to prepare a response indicating the reasons for the applicant's failure.

. Members of the board shall receive compensation in the amount of fifty dollars for each day's attendance at proper meetings of the committee.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20492[2011 c 336 § 492]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c9.pdf?cite=1984%20c%209%20§%2013[1984 c 9 § 13]; ]

== 18.59.130 - Board—Powers and duties—Rules.
. The board shall administer, coordinate, and enforce this chapter, evaluate qualifications under this chapter, and provide for supervision of examinations of applicants for licensure under this chapter.

. The board may adopt such rules as it deems necessary in the administration of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c259.pdf?cite=1986%20c%20259%20§%20102[1986 c 259 § 102]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c9.pdf?cite=1984%20c%209%20§%2014[1984 c 9 § 14]; ]

== 18.59.141 - Application of uniform disciplinary act.
The uniform disciplinary act, chapter 18.130 RCW, governs unlicensed practice, the issuance and denial of licenses, and the discipline of licensees under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c150.pdf?cite=1987%20c%20150%20§%2043[1987 c 150 § 43]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c259.pdf?cite=1986%20c%20259%20§%20100[1986 c 259 § 100]; ]

== 18.59.150 - Board—Staff.
The secretary shall provide such administrative and investigative staff as are necessary for the board to carry out its duties under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20157[1991 c 3 § 157]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c9.pdf?cite=1984%20c%209%20§%2015[1984 c 9 § 15]; ]

== 18.59.160 - Purchase, storage, and administration of medications—Restrictions—Liability.
An occupational therapist licensed under this chapter may purchase, store, and administer topical and transdermal medications such as hydrocortisone, dexamethasone, fluocinonide, topical anesthetics, lidocaine, magnesium sulfate, and other similar medications for the practice of occupational therapy as prescribed by a health care provider with prescribing authority as authorized in RCW 18.59.100. Administration of medication must be documented in the patient's medical record. Some medications may be applied by the use of iontophoresis and phonophoresis. An occupational therapist may not purchase, store, or administer controlled substances. A pharmacist who dispenses such drugs to a licensed occupational therapist is not liable for any adverse reactions caused by any method of use by the occupational therapist. Application of a topical medication to a wound is subject to RCW 18.59.170.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5018-S.SL.pdf?cite=2011%20c%2088%20§%202[2011 c 88 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1041-S.SL.pdf?cite=2009%20c%2068%20§%201[2009 c 68 § 1]; ]

== 18.59.170 - Scope of practice—Wound care management.
. [Empty]
.. An occupational therapist licensed under this chapter may provide wound care management only:

... In the course of occupational therapy treatment to return patients to functional performance in their everyday occupations under the referral and direction of a physician or other authorized health care provider listed in RCW 18.59.100 in accordance with their scope of practice. The referring provider must evaluate the patient prior to referral to an occupational therapist for wound care; and

... After filing an affidavit under subsection (2)(b) of this section.

.. An occupational therapist may not delegate wound care management, including any form of debridement.

. [Empty]
.. Debridement is not an entry-level skill and requires specialized training, which must include: Indications and contraindications for the use of debridement; appropriate selection and use of clean and sterile techniques; selection of appropriate tools, such as scissors, forceps, or scalpel; identification of viable and devitalized tissues; and conditions which require referral back to the referring provider. Training must be provided through continuing education, mentoring, cotreatment, and observation. Consultation with the referring provider is required if the wound exposes anatomical structures underlying the skin, such as tendon, muscle, or bone, or if there is an obvious worsening of the condition, or signs of infection.

.. [Empty]
... Occupational therapists may perform wound care management upon showing evidence of adequate education and training by submitting an affidavit to the board attesting to their education and training as follows:

(A) For occupational therapists performing any part of wound care management, except sharp debridement with a scalpel, a minimum of fifteen hours of mentored training in a clinical setting is required to be documented in the affidavit. Mentored training includes observation, cotreatment, and supervised treatment by a licensed occupational therapist who is authorized to perform wound care management under this section or a health care provider who is authorized to perform wound care management in his or her scope of practice. Fifteen hours mentored training in a clinical setting must include a case mix similar to the occupational therapist's expected practice;

(B) For occupational therapists performing sharp debridement with a scalpel, a minimum of two thousand hours in clinical practice and an additional minimum of fifteen hours of mentored sharp debridement training in the use of a scalpel in a clinical setting is required to be documented in the affidavit. Mentored training includes observation, cotreatment, and supervised treatment by a licensed occupational therapist who is authorized to perform sharp debridement with a scalpel under this section or a health care provider who is authorized to perform wound care management, including sharp debridement with a scalpel, in his or her scope of practice. Both the two thousand hours in clinical practice and the fifteen hours of mentored training in a clinical setting must include a case mix similar to the occupational therapist's expected practice.

... Certification as a certified hand therapist by the hand therapy certification commission or as a wound care specialist by the national alliance of wound care or equivalent organization approved by the board is sufficient to meet the requirements of (b)(i) of this subsection.

.. The board shall develop an affidavit form for the purposes of (b) of this subsection.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5018-S.SL.pdf?cite=2011%20c%2088%20§%203[2011 c 88 § 3]; ]

== 18.59.900 - Short title.
This chapter shall be known and may be cited as the occupational therapy practice act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c9.pdf?cite=1984%20c%209%20§%201[1984 c 9 § 1]; ]

