= 18.29 - Dental hygienists.
:toc:

== 18.29.003 - Regulation of health care professions—Criteria.
See chapter 18.120 RCW.

[ ]

== 18.29.005 - "Surfaces of the teeth" defined.
The term "surfaces of the teeth" as used in this chapter means the portions of the crown and root surface to which there is no periodontal membrane attached.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c47.pdf?cite=1969%20c%2047%20§%206[1969 c 47 § 6]; ]

== 18.29.011 - License required.
No person may practice as a dental hygienist in this state without having a license as such and, after the first year, an unexpired license renewal certificate.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c150.pdf?cite=1987%20c%20150%20§%2016[1987 c 150 § 16]; ]

== 18.29.021 - Requirements for licensing.
. The department shall issue a license to any applicant who, as determined by the secretary:

.. Has successfully completed an educational program approved by the secretary. This educational program shall include coursework encompassing the subject areas within the scope of the license to practice dental hygiene in the state of Washington;

.. Has successfully completed an examination administered or approved by the dental hygiene examining committee; and

.. Has not engaged in unprofessional conduct or is not unable to practice with reasonable skill and safety as a result of a physical or mental impairment.

. Applications for licensure must comply with administrative procedures, administrative requirements, and fees established according to RCW 43.70.250 and 43.70.280.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2010[1996 c 191 § 10]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5308-S.SL.pdf?cite=1995%20c%20198%20§%204[1995 c 198 § 4]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2046[1991 c 3 § 46]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c202.pdf?cite=1989%20c%20202%20§%201[1989 c 202 § 1]; ]

== 18.29.045 - Licensure by endorsement.
An applicant holding a valid license and currently engaged in practice in another state may be granted a license without examination required by this chapter, on the payment of any required fees, if the secretary in consultation with the advisory committee determines that the other state's licensing standards are substantively equivalent to the standards in this state: PROVIDED, That the secretary in consultation with the advisory committee may require the applicant to: (1) File with the secretary documentation certifying the applicant is licensed to practice in another state; and (2) provide information as the secretary deems necessary pertaining to the conditions and criteria of the uniform disciplinary act, chapter 18.130 RCW and to demonstrate to the secretary a knowledge of Washington law pertaining to the practice of dental hygiene.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2047[1991 c 3 § 47]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c202.pdf?cite=1989%20c%20202%20§%2029[1989 c 202 § 29]; ]

== 18.29.050 - Scope of licensee's functions—Employment—Supervision.
Any person licensed as a dental hygienist in this state may remove deposits and stains from the surfaces of the teeth, may apply topical preventive or prophylactic agents, may polish and smooth restorations, may perform root planing and soft-tissue curettage, and may perform other dental operations and services delegated to them by a licensed dentist. Any person licensed as a dental hygienist in this state may apply topical anesthetic agents under the general supervision, as defined in RCW 18.260.010, of a dentist: PROVIDED HOWEVER, That licensed dental hygienists shall in no event perform the following dental operations or services:

. Any surgical removal of tissue of the oral cavity;

. Any prescription of drugs or medications requiring the written order or prescription of a licensed dentist or physician, except that a hygienist may place antimicrobials pursuant to the order of a licensed dentist and under the dentist's required supervision;

. Any diagnosis for treatment or treatment planning; or

. The taking of any impression of the teeth or jaw, or the relationships of the teeth or jaws, for the purpose of fabricating any intra-oral restoration, appliance, or prosthesis, except that a dental hygienist may take an impression for any purpose that is either allowed:

.. For a dental assistant registered under chapter 18.260 RCW; or

.. As a delegated duty for dental hygienists pursuant to rules adopted by the dental quality assurance commission.

Such licensed dental hygienists may perform dental operations and services only under the supervision of a licensed dentist, and under such supervision may be employed by hospitals, boards of education of public or private schools, county boards, boards of health, or public or charitable institutions, or in dental offices.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5606.SL.pdf?cite=2015%20c%20120%20§%201[2015 c 120 § 1]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1330.SL.pdf?cite=2013%20c%2087%20§%201[2013 c 87 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5327-S.SL.pdf?cite=2003%20c%20257%20§%201[2003 c 257 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5322-S.SL.pdf?cite=1997%20c%2037%20§%201[1997 c 37 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c235.pdf?cite=1971%20ex.s.%20c%20235%20§%201[1971 ex.s. c 235 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c47.pdf?cite=1969%20c%2047%20§%204[1969 c 47 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c16.pdf?cite=1923%20c%2016%20§%2027[1923 c 16 § 27]; RRS § 10030-27; ]

== 18.29.053 - Expanded function dental auxiliary services—Supervision.
A person who holds a license under this chapter and who has met the requirements under RCW 18.260.050 and has been issued a license to practice as an expanded function dental auxiliary may perform those expanded function dental auxiliary services identified in RCW 18.260.070 under the specified supervision of a supervising dentist.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1099-S.SL.pdf?cite=2007%20c%20269%20§%2014[2007 c 269 § 14]; ]

== 18.29.056 - Employment by health care facilities authorized—Limitations—Requirements for services performed in senior centers.
. [Empty]
.. Subject to RCW 18.29.230 and (e) of this subsection, dental hygienists licensed under this chapter with two years' practical clinical experience with a licensed dentist within the preceding five years may be employed, retained, or contracted by health care facilities and senior centers to perform authorized dental hygiene operations and services without dental supervision.

.. Subject to RCW 18.29.230 and (e) of this subsection, dental hygienists licensed under this chapter with two years' practical clinical experience with a licensed dentist within the preceding five years may perform authorized dental hygiene operations and services without dental supervision under a lease agreement with a health care facility or senior center.

.. Dental hygienists performing operations and services under (a) or (b) of this subsection are limited to removal of deposits and stains from the surfaces of the teeth, application of topical preventive or prophylactic agents, application of topical anesthetic agents, polishing and smoothing restorations, and performance of root planing and soft-tissue curettage, but shall not perform injections of anesthetic agents, administration of nitrous oxide, or diagnosis for dental treatment.

.. The performance of dental hygiene operations and services in health care facilities shall be limited to patients, students, and residents of the facilities.

.. A dental hygienist employed, retained, or contracted to perform services under this section or otherwise performing services under a lease agreement under this section in a senior center must, before providing services:

... Enter into a written practice arrangement plan, approved by the department, with a dentist licensed in this state, under which the dentist will provide off-site supervision of the dental services provided. This agreement does not create an obligation for the dentist to accept referrals of patients receiving services under the program; and

... Obtain information from the patient's primary health care provider about any health conditions of the patient that would be relevant to the provision of preventive dental care. The information may be obtained by the dental hygienist's direct contact with the provider or through a written document from the provider that the patient presents to the dental hygienist.

.. For dental planning and dental treatment, dental hygienists shall refer patients to licensed dentists.

. For the purposes of this section:

.. "Health care facilities" are limited to hospitals; nursing homes; home health agencies; group homes serving the elderly, individuals with disabilities, and juveniles; state-operated institutions under the jurisdiction of the department of social and health services or the department of corrections; and federal, state, and local public health facilities, state or federally funded community and migrant health centers, and tribal clinics.

.. "Senior center" means a multipurpose community facility operated and maintained by a nonprofit organization or local government for the organization and provision of a combination of some of the following: Health, social, nutritional, educational services, and recreational activities for persons sixty years of age or older.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1554.SL.pdf?cite=2019%20c%20111%20§%201[2019 c 111 § 1]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1330.SL.pdf?cite=2013%20c%2087%20§%202[2013 c 87 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1309-S.SL.pdf?cite=2009%20c%20321%20§%201[2009 c 321 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1298-S.SL.pdf?cite=2007%20c%20270%20§%201[2007 c 270 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5322-S.SL.pdf?cite=1997%20c%2037%20§%202[1997 c 37 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c279.pdf?cite=1984%20c%20279%20§%2063[1984 c 279 § 63]; ]

== 18.29.058 - Delegated acts—Homebound patients.
. [Empty]
.. Any person licensed in this state as a dental hygienist with two years of practical clinical experience within the preceding five years may perform delegated acts specified in (b) of this subsection on a homebound patient under the general supervision of a dentist licensed under chapter 18.32 RCW if the patient has first been examined by the supervising dentist within a time frame deemed appropriate by the supervising dentist.

.. The acts that may be performed under (a) of this subsection are limited to the acts, specified in rule by the dental quality assurance commission, that a dental hygienist is authorized to perform under the general supervision of a dentist.

. Prior to performing acts under this section, the dental hygienist shall:

.. Obtain information from the patient's primary health care provider about any health conditions of the patient that would be relevant to the provision of preventive dental care. The dental hygienist shall review and discuss any changes in health condition with the supervising dentist prior to treatment;

.. Discuss appropriateness of care with the supervising dentist; and

.. Obtain written consent from the supervising dentist.

. For purposes of this section:

.. "General supervision" has the same meaning as in RCW 18.260.010; and

.. "Homebound patient" means a patient incapable of travel due to age or disability.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1330.SL.pdf?cite=2013%20c%2087%20§%203[2013 c 87 § 3]; ]

== 18.29.060 - License issuance—Display.
Upon passing an examination and meeting the requirements as provided in RCW 18.29.021, the secretary of health shall issue to the successful applicant a license as dental hygienist. The license shall be displayed in a conspicuous place in the operation room where such licensee shall practice.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2048[1991 c 3 § 48]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c202.pdf?cite=1989%20c%20202%20§%2012[1989 c 202 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%2021[1985 c 7 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c277.pdf?cite=1981%20c%20277%20§%204[1981 c 277 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c158.pdf?cite=1979%20c%20158%20§%2032[1979 c 158 § 32]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c16.pdf?cite=1923%20c%2016%20§%2031[1923 c 16 § 31]; RRS § 10030-31; ]

== 18.29.071 - Renewals.
The secretary shall establish the administrative procedures, administrative requirements, and fees for renewal of licenses as provided in this chapter and in RCW 43.70.250 and 43.70.280.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2011[1996 c 191 § 11]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2049[1991 c 3 § 49]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c202.pdf?cite=1989%20c%20202%20§%202[1989 c 202 § 2]; ]

== 18.29.076 - Application of uniform disciplinary act.
The uniform disciplinary act, chapter 18.130 RCW, governs unlicensed practice, the issuance and denial of licenses, and the discipline of licensees under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c150.pdf?cite=1987%20c%20150%20§%2015[1987 c 150 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c259.pdf?cite=1986%20c%20259%20§%2031[1986 c 259 § 31]; ]

== 18.29.100 - Violations—Penalty—Prosecutions.
Any person who shall violate any provision of this chapter shall be guilty of a misdemeanor. It shall be the duty of the prosecuting attorney of each county to prosecute all cases involving a violation of this chapter arising within his or her county. The attorney general may assist in such prosecutions and shall appear at all hearings when requested to do so by the secretary of health.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2050[1991 c 3 § 50]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c158.pdf?cite=1979%20c%20158%20§%2034[1979 c 158 § 34]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c16.pdf?cite=1923%20c%2016%20§%2036[1923 c 16 § 36]; RRS § 10030-36; ]

== 18.29.110 - Dental hygiene examining committee—Generally.
There shall be a dental hygiene examining committee consisting of four practicing dental hygienists and one public member appointed by the secretary, to be known as the Washington dental hygiene examining committee. Each dental hygiene member shall be licensed and have been actively practicing dental hygiene for a period of not less than five years immediately before appointment and shall not be connected with any dental hygiene school. The public member shall not be connected with any dental hygiene program or engaged in any practice or business related to dental hygiene. Members of the committee shall be appointed by the secretary to prepare and conduct examinations for dental hygiene licensure. Members shall be appointed to serve for terms of three years from October 1 of the year in which they are appointed. Terms of the members shall be staggered. Each member shall hold office for the term of his or her appointment and until his or her successor is appointed and qualified. Any member of the committee may be removed by the secretary for neglect of duty, misconduct, malfeasance, or misfeasance in office, after being given a written statement of the charges against him or her and sufficient opportunity to be heard thereon. Members of the committee shall be compensated in accordance with RCW 43.03.240 and shall be reimbursed for travel expenses in accordance with RCW 43.03.050 and 43.03.060.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1554.SL.pdf?cite=2019%20c%20111%20§%202[2019 c 111 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2051[1991 c 3 § 51]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c202.pdf?cite=1989%20c%20202%20§%203[1989 c 202 § 3]; ]

== 18.29.120 - Examinations—Secretary's authority—Consultation with examining authority.
The secretary in consultation with the Washington dental hygiene examining committee shall:

. Adopt rules in accordance with chapter 34.05 RCW necessary to prepare and conduct examinations for dental hygiene licensure;

. Require an applicant for licensure to pass an examination consisting of written and practical tests upon such subjects and of such scope as the committee determines;

. Set the standards for passage of the examination;

. Administer at least two examinations each calendar year. Additional examinations may be given as necessary; and

. Establish by rule the procedures for an appeal of an examination failure.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5308-S.SL.pdf?cite=1995%20c%20198%20§%205[1995 c 198 § 5]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2052[1991 c 3 § 52]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c202.pdf?cite=1989%20c%20202%20§%204[1989 c 202 § 4]; ]

== 18.29.130 - Secretary's authority—Generally—Continuing education.
In addition to any other authority provided by law, the secretary may:

. Adopt rules in accordance with chapter 34.05 RCW necessary to implement this chapter;

. Establish forms necessary to administer this chapter;

. Issue a license to any applicant who has met the education and examination requirements for licensure and deny a license to applicants who do not meet the minimum qualifications for licensure. Proceedings concerning the denial of licenses based on unprofessional conduct or impaired practice shall be governed by the uniform disciplinary act, chapter 18.130 RCW;

. Employ clerical, administrative, and investigative staff as needed to implement and administer this chapter and hire individuals, including those licensed under this chapter, to serve as examiners or consultants as necessary to implement and administer this chapter;

. Maintain the official departmental record of all applicants and licensees;

. Establish, by rule, the minimum education requirements for licensure, including but not limited to approval of educational programs; and

. Establish and implement by rule a continuing education program.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2053[1991 c 3 § 53]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c202.pdf?cite=1989%20c%20202%20§%205[1989 c 202 § 5]; ]

== 18.29.140 - Approval of educational programs.
The secretary shall establish by rule the standards and procedures for approval of educational programs and may contract with individuals or organizations having expertise in the profession or in education to report to the secretary information necessary for the secretary to evaluate the educational programs. The secretary may establish a fee for educational program evaluation. The fee shall be set to defray the administrative costs for evaluating the educational program, including, but not limited to, costs for site evaluation.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2054[1991 c 3 § 54]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c202.pdf?cite=1989%20c%20202%20§%206[1989 c 202 § 6]; ]

== 18.29.150 - Examinations.
. The secretary shall establish the date and location of the examination. Applicants who meet the education requirements for licensure shall be scheduled for the next examination following the filing of the application. The secretary shall establish by rule the examination application deadline.

. The examination shall contain subjects appropriate to the scope of practice and on laws in the state of Washington regulating dental hygiene practice.

. The committee shall establish by rule the requirements for a reexamination if the applicant has failed the examination.

. The committee may approve an examination prepared or administered by a private testing agency or association of licensing authorities.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2055[1991 c 3 § 55]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c202.pdf?cite=1989%20c%20202%20§%207[1989 c 202 § 7]; ]

== 18.29.160 - Immunity.
The secretary, members of the committee, and individuals acting on their behalf are immune from suit in any action, civil or criminal, based on any acts performed in the course of their duties.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2056[1991 c 3 § 56]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c202.pdf?cite=1989%20c%20202%20§%208[1989 c 202 § 8]; ]

== 18.29.170 - Committee meetings—Quorum—Effect of vacancy.
The committee shall meet at least once a year and at such times as may be necessary for the transaction of business.

A majority of the committee shall constitute a quorum.

A vacancy in the committee membership shall not impair the right of the remaining members of the committee to exercise any power or to perform any duty of the committee, so long as the power is exercised or the duty performed by a quorum of the committee.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c202.pdf?cite=1989%20c%20202%20§%209[1989 c 202 § 9]; ]

== 18.29.180 - Exemptions from chapter.
The following practices, acts, and operations are excepted from the operation of this chapter:

. The practice of dental hygiene in the discharge of official duties by dental hygienists in the United States armed services, coast guard, public health services, veterans' bureau, or bureau of Indian affairs;

. Dental hygiene programs approved by the secretary and the practice of dental hygiene by students in dental hygiene programs approved by the secretary, when acting under the direction and supervision of persons licensed under chapter 18.29 or 18.32 RCW acting as instructors;

. The practice of dental hygiene by students in accredited dental hygiene educational programs when acting under the direction and supervision of instructors licensed under chapter 18.29 or 18.32 RCW; and

. The performance of dental health aide therapist services to the extent authorized under chapter 70.350 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5079-S.SL.pdf?cite=2017%20c%205%20§%204[2017 c 5 § 4]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6554-S.SL.pdf?cite=2004%20c%20262%20§%204[2004 c 262 § 4]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%2057[1991 c 3 § 57]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c202.pdf?cite=1989%20c%20202%20§%2010[1989 c 202 § 10]; ]

== 18.29.190 - Initial limited license.
. The department shall issue an initial limited license without the examination required by this chapter to any applicant who, as determined by the secretary:

.. Holds a valid license in another state or Canadian province that allows a substantively equivalent scope of practice in subsection (3)(a) through (j) of this section;

.. Is currently engaged in active practice in another state or Canadian province. For the purposes of this section, "active practice" means five hundred sixty hours of practice in the preceding twenty-four months;

.. Files with the secretary documentation certifying that the applicant:

... Has graduated from an accredited dental hygiene school approved by the secretary;

... Has successfully completed the dental hygiene national board examination; and

... Is licensed to practice in another state or Canadian province;

.. Provides information as the secretary deems necessary pertaining to the conditions and criteria of the uniform disciplinary act, chapter 18.130 RCW;

.. Demonstrates to the secretary a knowledge of Washington state law pertaining to the practice of dental hygiene, including the administration of legend drugs;

.. Pays any required fees; and

.. Meets requirements for AIDS education.

. The term of the initial limited license issued under this section is eighteen months and it is renewable upon:

.. Demonstration of successful passage of a substantively equivalent dental hygiene patient evaluation/prophylaxis examination;

.. Demonstration of successful passage of a substantively equivalent local anesthesia examination;

.. Demonstration of didactic and clinical competency in the administration of nitrous oxide analgesia; and

.. Demonstration of successful passage of an educational program on the administration of local anesthesia and nitrous oxide analgesia.

. A person practicing with an initial limited license granted under this section has the authority to perform hygiene procedures that are limited to:

.. Oral inspection and measuring of periodontal pockets;

.. Patient education in oral hygiene;

.. Taking intra-oral and extra-oral radiographs;

.. Applying topical preventive or prophylactic agents;

.. Polishing and smoothing restorations;

.. Oral prophylaxis and removal of deposits and stains from the surface of the teeth;

.. Recording health histories;

.. Taking and recording blood pressure and vital signs;

.. Performing subgingival and supragingival scaling; and

.. Performing root planing.

. [Empty]
.. A person practicing with an initial limited license granted under this section may not perform the following dental hygiene procedures unless authorized in (b) or (c) of this subsection:

... Give injections of local anesthetic;

... Place restorations into the cavity prepared by a licensed dentist and afterwards carve, contour, and adjust contacts and occlusion of the restoration;

... Soft tissue curettage; or

... Administer nitrous oxide/oxygen analgesia.

.. A person licensed in another state or Canadian province who can demonstrate substantively equivalent licensing standards in the administration of local anesthetic may receive a temporary endorsement to administer local anesthesia. For purposes of the renewed limited license, this endorsement demonstrates the successful passage of the local anesthesia examination.

.. A person licensed in another state or Canadian province who can demonstrate substantively equivalent licensing standards in restorative procedures may receive a temporary endorsement for restorative procedures.

.. A person licensed in another state or Canadian province who can demonstrate substantively equivalent licensing standards in administering nitrous oxide analgesia may receive a temporary endorsement to administer nitrous oxide analgesia.

. [Empty]
.. A person practicing with a renewed limited license granted under this section may:

... Perform hygiene procedures as provided under subsection (3) of this section;

... Give injections of local anesthetic;

... Perform soft tissue curettage; and

... Administer nitrous oxide/oxygen analgesia.

.. A person practicing with a renewed limited license granted under this section may not place restorations into the cavity prepared by a licensed dentist and afterwards carve, contour, and adjust contacts and occlusion of the restoration.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1554.SL.pdf?cite=2019%20c%20111%20§%203[2019 c 111 § 3]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5606.SL.pdf?cite=2015%20c%20120%20§%202[2015 c 120 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6418.SL.pdf?cite=2006%20c%2066%20§%201[2006 c 66 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6554-S.SL.pdf?cite=2004%20c%20262%20§%203[2004 c 262 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1801-S.SL.pdf?cite=1993%20c%20323%20§%202[1993 c 323 § 2]; ]

== 18.29.210 - Rules.
The secretary in consultation with the dental hygiene examining committee shall develop rules and definitions to implement this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1801-S.SL.pdf?cite=1993%20c%20323%20§%204[1993 c 323 § 4]; ]

== 18.29.220 - Community-based sealant programs in schools.
For low-income, rural, and other at-risk populations and in coordination with local public health jurisdictions and local oral health coalitions, a dental hygienist licensed in this state may assess for and apply sealants and apply fluoride, and may remove deposits and stains from the surfaces of teeth in community-based sealant programs carried out in schools:

. Without attending the department's school sealant endorsement program if the dental hygienist was licensed as of April 19, 2001; or

. If the dental hygienist is school sealant endorsed under RCW 43.70.650.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1554.SL.pdf?cite=2019%20c%20111%20§%204[2019 c 111 § 4]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1309-S.SL.pdf?cite=2009%20c%20321%20§%202[2009 c 321 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1298-S.SL.pdf?cite=2007%20c%20270%20§%202[2007 c 270 § 2]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6020-S.SL.pdf?cite=2001%20c%2093%20§%203[2001 c 93 § 3]; ]

== 18.29.230 - Services at senior centers and community-based sealant programs—Dental hygienist duties.
A dental hygienist participating in a program under RCW 18.29.056 that involves providing services at senior centers, as defined in RCW 18.29.056, or under RCW 18.29.220 that involves removing deposits and stains from the surfaces of teeth in a community-based sealant program must:

. Provide the patient or, if the patient is a minor, the parent or legal guardian of the patient, if reasonably available, with written information that includes at least the following:

.. A notice that the treatment being given under the program is not a comprehensive oral health care service, but is provided as a preventive service only; and

.. A recommendation that the patient should be examined by a licensed dentist for comprehensive oral health care services; and

. Assist the patient in obtaining a referral for further dental planning and treatment, including providing a written description of methods and sources by which a patient may obtain a referral, if needed, to a dentist, and a list of licensed dentists in the community. Written information should be provided to the parent on the potential needs of the patient.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1298-S.SL.pdf?cite=2007%20c%20270%20§%203[2007 c 270 § 3]; ]

== 18.29.900 - Construction—1923 c 16.
Words used in this chapter importing the singular number may also be applied to the plural of persons and things. Words importing the plural may be applied to the singular, and words importing the masculine gender may be extended to females also.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c16.pdf?cite=1923%20c%2016%20§%2037[1923 c 16 § 37]; ]

