= 18.57A - Osteopathic physician assistants.
:toc:

== 18.57A.010 - Definitions. (Effective until July 1, 2022.)
. "Osteopathic physician's assistant" means a person who has satisfactorily completed a board-approved training program designed to prepare persons to practice osteopathic medicine to a limited extent;

. "Board" means the board of osteopathic medicine and surgery; and

. "Practice medicine" shall have the meaning defined in RCW 18.57.001.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c117.pdf?cite=1979%20c%20117%20§%2017[1979 c 117 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c30.pdf?cite=1971%20ex.s.%20c%2030%20§%207[1971 ex.s. c 30 § 7]; ]

== 18.57A.020 - Rules fixing qualifications and restricting practice—Interim permit—Applications—Discipline—Information about current professional practice. (Effective until July 1, 2022.)
. The board shall adopt rules fixing the qualifications and the educational and training requirements for licensure as an osteopathic physician assistant or for those enrolled in any physician assistant training program. The requirements shall include completion of an accredited physician assistant training program approved by the board and within one year successfully take and pass an examination approved by the board, providing such examination tests subjects substantially equivalent to the curriculum of an accredited physician assistant training program. An interim permit may be granted by the department of health for one year provided the applicant meets all other requirements. Physician assistants licensed by the board of osteopathic medicine as of July 1, 1999, shall continue to be licensed.

. [Empty]
.. The board shall adopt rules governing the extent to which:

... Physician assistant students may practice medicine during training; and

... Physician assistants may practice after successful completion of a training course.

.. Such rules shall provide:

... That the practice of an osteopathic physician assistant shall be limited to the performance of those services for which he or she is trained; and

... That each osteopathic physician assistant shall practice osteopathic medicine only under the supervision and control of an osteopathic physician licensed in this state, but such supervision and control shall not be construed to necessarily require the personal presence of the supervising physicians at the place where services are rendered. The board may authorize the use of alternative supervisors who are licensed either under chapter 18.57 or 18.71 RCW.

. Applicants for licensure shall file an application with the board on a form prepared by the secretary with the approval of the board, detailing the education, training, and experience of the physician assistant and such other information as the board may require. The application shall be accompanied by a fee determined by the secretary as provided in RCW 43.70.250 and 43.70.280. A surcharge of fifty dollars per year shall be charged on each license renewal or issuance of a new license to be collected by the department of health and placed in the health professions account for physician assistant participation in an impaired practitioner program. Each applicant shall furnish proof satisfactory to the board of the following:

.. That the applicant has completed an accredited physician assistant program approved by the board and is eligible to take the examination approved by the board;

.. That the applicant is of good moral character; and

.. That the applicant is physically and mentally capable of practicing osteopathic medicine as an osteopathic physician assistant with reasonable skill and safety. The board may require any applicant to submit to such examination or examinations as it deems necessary to determine an applicant's physical and/or mental capability to safely practice as an osteopathic physician assistant.

. The board may approve, deny, or take other disciplinary action upon the application for a license as provided in the uniform disciplinary act, chapter 18.130 RCW. The license shall be renewed as determined under RCW 43.70.250 and 43.70.280.

. The board must request licensees to submit information about their current professional practice at the time of license renewal and licensees must provide the information requested. This information may include practice setting, medical specialty, board certification, or other relevant data determined by the board.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2432.SL.pdf?cite=2016%20c%2042%20§%202[2016 c 42 § 2]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1485-S2.SL.pdf?cite=2015%20c%20252%20§%2011[2015 c 252 § 11]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5702.SL.pdf?cite=1999%20c%20127%20§%202[1999 c 127 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1618-S2.SL.pdf?cite=1998%20c%20132%20§%2013[1998 c 132 § 13]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2039[1996 c 191 § 39]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1253-S.SL.pdf?cite=1993%20c%2028%20§%201[1993 c 28 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6070.SL.pdf?cite=1992%20c%2028%20§%201[1992 c 28 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c30.pdf?cite=1971%20ex.s.%20c%2030%20§%208[1971 ex.s. c 30 § 8]; ]

== 18.57A.023 - Practice requirements—Military training and experience. (Effective until July 1, 2022.)
An applicant with military training or experience satisfies the training and experience requirements of this chapter unless the board determines that the military training or experience is not substantially equivalent to the standards of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5307-S.SL.pdf?cite=2011%20c%2032%20§%204[2011 c 32 § 4]; ]

== 18.57A.025 - Application of uniform disciplinary act. (Effective until July 1, 2022.)
The uniform disciplinary act, chapter 18.130 RCW, governs the approval or disapproval of applications and the discipline of persons authorized to practice under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c259.pdf?cite=1986%20c%20259%20§%2093[1986 c 259 § 93]; ]

== 18.57A.030 - Limitations on practice—Scope of practice. (Effective until July 1, 2022.)
. An osteopathic physician assistant as defined in this chapter may practice osteopathic medicine in this state only with the approval of the delegation agreement by the board and only to the extent permitted by the board. An osteopathic physician assistant who has received a license but who has not received board approval of the delegation agreement under RCW 18.57A.040 may not practice. An osteopathic physician assistant shall be subject to discipline by the board under the provisions of chapter 18.130 RCW.

. Osteopathic physician assistants may provide services that they are competent to perform based on their education, training, and experience and that are consistent with their board-approved delegation agreement. The supervising physician and the physician assistant shall determine which procedures may be performed and the degree of supervision under which the procedure is performed. Physician assistants may practice in any area of medicine or surgery so long as the practice is not beyond the supervising physician's own scope of expertise and practice.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6445-S.SL.pdf?cite=2016%20c%20155%20§%2024[2016 c 155 § 24]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1737-S.SL.pdf?cite=2013%20c%20203%20§%203[2013 c 203 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1253-S.SL.pdf?cite=1993%20c%2028%20§%202[1993 c 28 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c259.pdf?cite=1986%20c%20259%20§%2095[1986 c 259 § 95]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c30.pdf?cite=1971%20ex.s.%20c%2030%20§%209[1971 ex.s. c 30 § 9]; ]

== 18.57A.035 - Limitation on practice—Remote sites. (Effective until July 1, 2022.)
. No licensee may be utilized in a remote site without approval by the board or its designee. A "remote site" is defined as a setting physically separate from the sponsoring or supervising physician's primary place for meeting patients or a setting where the physician is present less than twenty-five percent of the practice time of the licensee.

. [Empty]
.. Approval by the commission or its designee may be granted to utilize a licensee in a remote site if:

... There is a demonstrated need for the utilization;

... Adequate provision for timely communication between the primary or alternate physician and the licensee exists;

... The responsible sponsoring or supervising physician spends at least ten percent of the practice time of the licensee in the remote site unless the sponsoring physician demonstrates that adequate supervision is being maintained by an alternate method such as telecommunication.

.. The names of the sponsoring or supervising physician and the licensee must be prominently displayed at the entrance to the clinic or in the reception area.

. No physician assistant holding an interim permit may be utilized in a remote site setting.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1737-S.SL.pdf?cite=2013%20c%20203%20§%201[2013 c 203 § 1]; ]

== 18.57A.040 - Practice arrangements. (Effective until July 1, 2022.)
. No osteopathic physician assistant practicing in this state shall be employed or supervised by an osteopathic physician or physician group without the approval of the board.

. Prior to commencing practice, an osteopathic physician assistant licensed in this state shall apply to the board for permission to be employed or supervised by an osteopathic physician or physician group. The delegation agreement shall be jointly submitted by the osteopathic physician or physician group and osteopathic physician assistant. The secretary may charge a fee as provided in RCW 43.70.250 to recover the cost for the plan review. The delegation agreement shall delineate the manner and extent to which the physician assistant would practice and be supervised. Whenever an osteopathic physician assistant is practicing in a manner inconsistent with the approved delegation agreement, the board may take disciplinary action under chapter 18.130 RCW.

. An osteopathic physician may enter into delegation agreements with five physician assistants, but may petition the board for a waiver of this limit. However, no osteopathic physician may have under his or her supervision: (a) More than three physician assistants who are working in remote sites; or (b) more physician assistants than the osteopathic physician can adequately supervise.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1737-S.SL.pdf?cite=2013%20c%20203%20§%204[2013 c 203 § 4]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1253-S.SL.pdf?cite=1993%20c%2028%20§%203[1993 c 28 § 3]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20152[1991 c 3 § 152]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c259.pdf?cite=1986%20c%20259%20§%2096[1986 c 259 § 96]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%2057[1985 c 7 § 57]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c30.pdf?cite=1975%201st%20ex.s.%20c%2030%20§%2060[1975 1st ex.s. c 30 § 60]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c30.pdf?cite=1971%20ex.s.%20c%2030%20§%2010[1971 ex.s. c 30 § 10]; ]

== 18.57A.050 - Osteopathic physician's liability, responsibility. (Effective until July 1, 2022.)
No osteopathic physician who supervises a licensed osteopathic physician assistant in accordance with and within the terms of any permission granted by the board shall be considered as aiding and abetting an unlicensed person to practice osteopathic medicine within the meaning of RCW 18.57.001: PROVIDED, HOWEVER, That the supervising osteopathic physician and the osteopathic physician assistant shall retain professional and personal responsibility for any act which constitutes the practice of osteopathic medicine as defined in RCW 18.57.001 when performed by the physician assistant.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1253-S.SL.pdf?cite=1993%20c%2028%20§%204[1993 c 28 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c259.pdf?cite=1986%20c%20259%20§%2097[1986 c 259 § 97]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c30.pdf?cite=1971%20ex.s.%20c%2030%20§%2011[1971 ex.s. c 30 § 11]; ]

== 18.57A.060 - Limitations on health care services. (Effective until July 1, 2022.)
No health care services may be performed under this chapter in any of the following areas:

. The measurement of the powers or range of human vision, or the determination of the accommodation and refractive state of the human eye or the scope of its functions in general, or the fitting or adaptation of lenses or frames for the aid thereof.

. The prescribing or directing the use of, or using, any optical device in connection with ocular exercises, visual training, vision training or orthoptics.

. The prescribing of contact lenses for, or the fitting or adaptation of contact lenses to, the human eye.

. Nothing in this section shall preclude the performance of routine visual screening.

. The practice of dentistry or dental hygiene as defined in chapter 18.32 and 18.29 RCW respectively. The exemptions set forth in RCW 18.32.030, paragraphs (1) and (8), shall not apply to a physician's assistant.

. The practice of chiropractic as defined in chapter 18.25 RCW including the adjustment or manipulation of the articulations of the spine.

. The practice of podiatric medicine and surgery as defined in chapter 18.22 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2400.SL.pdf?cite=2000%20c%20171%20§%2021[2000 c 171 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c77.pdf?cite=1973%20c%2077%20§%2020[1973 c 77 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c30.pdf?cite=1971%20ex.s.%20c%2030%20§%2012[1971 ex.s. c 30 § 12]; ]

== 18.57A.070 - Physician assistant acupuncturist—Licensure. (Effective until July 1, 2022.)
Any physician assistant acupuncturist currently licensed as a physician assistant may continue to perform acupuncture under the physician assistant license as long as he or she maintains licensure as a physician assistant.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2452.SL.pdf?cite=2000%20c%2093%20§%2041[2000 c 93 § 41]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c233.pdf?cite=1977%20ex.s.%20c%20233%20§%201[1977 ex.s. c 233 § 1]; ]

== 18.57A.080 - Signing and attesting to required documentation. (Effective until July 1, 2022.)
An osteopathic physician assistant may sign and attest to any certificates, cards, forms, or other required documentation that the osteopathic physician assistant's supervising osteopathic physician or osteopathic physician group may sign, provided that it is within the osteopathic physician assistant's scope of practice and is consistent with the terms of the osteopathic physician assistant's delegation agreement as required by this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1737-S.SL.pdf?cite=2013%20c%20203%20§%205[2013 c 203 § 5]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1966.SL.pdf?cite=2007%20c%20264%20§%202[2007 c 264 § 2]; ]

== 18.57A.090 - Pain management rules—Repeal—Adoption of new rules. (Effective until July 1, 2022.)
. By June 30, 2011, the board shall repeal its rules on pain management, WAC 246-854-120 through 246-854-150.

. By June 30, 2011, the board shall adopt new rules on chronic, noncancer pain management that contain the following elements:

.. [Empty]
... Dosing criteria, including:

(A) A dosage amount that must not be exceeded unless an osteopathic physician's assistant first consults with a practitioner specializing in pain management; and

(B) Exigent or special circumstances under which the dosage amount may be exceeded without consultation with a practitioner specializing in pain management.

... The rules regarding consultation with a practitioner specializing in pain management must, to the extent practicable, take into account:

(A) Circumstances under which repeated consultations would not be necessary or appropriate for a patient undergoing a stable, ongoing course of treatment for pain management;

(B) Minimum training and experience that is sufficient to exempt an osteopathic physician's assistant from the specialty consultation requirement;

(C) Methods for enhancing the availability of consultations;

(D) Allowing the efficient use of resources; and

(E) Minimizing the burden on practitioners and patients;

.. Guidance on when to seek specialty consultation and ways in which electronic specialty consultations may be sought;

.. Guidance on tracking clinical progress by using assessment tools focusing on pain interference, physical function, and overall risk for poor outcome; and

.. Guidance on tracking the use of opioids, particularly in the emergency department.

. The board shall consult with the agency medical directors' group, the department of health, the University of Washington, and the largest association of osteopathic physician's assistants in the state.

. The rules adopted under this section do not apply:

.. To the provision of palliative, hospice, or other end-of-life care; or

.. To the management of acute pain caused by an injury or a surgical procedure.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2876-S.SL.pdf?cite=2010%20c%20209%20§%204[2010 c 209 § 4]; ]

== 18.57A.100 - Down syndrome—Parent information. (Effective until July 1, 2022.)
An osteopathic physician's assistant who provides a parent with a positive prenatal or postnatal diagnosis of Down syndrome shall provide the parent with the information prepared by the department under RCW 43.70.738 at the time the osteopathic physician's assistant provides the parent with the Down syndrome diagnosis.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2403.SL.pdf?cite=2016%20c%2070%20§%204[2016 c 70 § 4]; ]

== 18.57A.800 - Opioid drug prescribing rules—Adoption. (Effective until July 1, 2022.)
. By January 1, 2019, the board must adopt rules establishing requirements for prescribing opioid drugs. The rules may contain exemptions based on education, training, amount of opioids prescribed, patient panel, and practice environment.

. In developing the rules, the board must consider the agency medical directors' group and centers for disease control guidelines, and may consult with the department of health, the University of Washington, and the largest professional association of osteopathic physician assistants in the state.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1427-S.SL.pdf?cite=2017%20c%20297%20§%205[2017 c 297 § 5]; ]

== 18.57A.810 - Opioid drugs—Right to refuse. (Effective until July 1, 2022.)
By January 1, 2020, the board must adopt or amend its rules to require osteopathic physicians' assistants who prescribe opioids to inform patients of their right to refuse an opioid prescription or order for any reason. If a patient indicates a desire to not receive an opioid, the osteopathic physician's assistant must document the patient's request and avoid prescribing or ordering opioids, unless the request is revoked by the patient.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5380-S.SL.pdf?cite=2019%20c%20314%20§%206[2019 c 314 § 6]; ]

