= 18.89 - Respiratory care practitioners.
:toc:

== 18.89.010 - Legislative findings—Insurance coverage not mandated.
The legislature finds that in order to safeguard life, health, and to promote public welfare, a person practicing or offering to practice respiratory care as a respiratory care practitioner in this state shall be required to submit evidence that he or she is qualified to practice, and shall be licensed as provided. The settings for these services may include, health facilities licensed in this state, clinics, home care, home health agencies, physicians' offices, and public or community health services. Nothing in this chapter shall be construed to require that individual or group policies or contracts of an insurance carrier, health care service contractor, or health maintenance organization provide benefits or coverage for services and supplies provided by a person certified under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1536-S.SL.pdf?cite=1997%20c%20334%20§%201[1997 c 334 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c415.pdf?cite=1987%20c%20415%20§%201[1987 c 415 § 1]; ]

== 18.89.015 - Unlawful practice, when.
After July 1, 1998, it shall be unlawful for a person to practice or to offer to practice as a respiratory care practitioner in this state or to use a title, sign, or device to indicate that such a person is practicing as a respiratory care practitioner unless the person has been duly licensed and registered under the provisions of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1536-S.SL.pdf?cite=1997%20c%20334%20§%202[1997 c 334 § 2]; ]

== 18.89.020 - Definitions. (Effective until July 1, 2022.)
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Department" means the department of health.

. "Health care practitioner" means:

.. A physician licensed under chapter 18.71 RCW;

.. An osteopathic physician or surgeon licensed under chapter 18.57 RCW; or

.. Acting within the scope of their respective licensure, a podiatric physician and surgeon licensed under chapter 18.22 RCW, an advanced registered nurse practitioner licensed under chapter 18.79 RCW, a naturopath licensed under chapter 18.36A RCW, a physician assistant licensed under chapter 18.71A RCW, or an osteopathic physician assistant licensed under chapter 18.57A RCW.

. "Respiratory care practitioner" means an individual licensed under this chapter.

. "Secretary" means the secretary of health or the secretary's designee.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1640.SL.pdf?cite=2011%20c%20235%20§%201[2011 c 235 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1536-S.SL.pdf?cite=1997%20c%20334%20§%203[1997 c 334 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20511[1994 sp.s. c 9 § 511]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20227[1991 c 3 § 227]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c415.pdf?cite=1987%20c%20415%20§%202[1987 c 415 § 2]; ]

== 18.89.030 - Respiratory care practitioner—What constitutes.
A respiratory care practitioner is a person who adopts or uses any title or any description of services which incorporates one or more of the following terms or designations: (1) RT, (2) RCP, (3) respiratory care practitioner, (4) respiratory therapist, (5) respiratory technician, (6) inhalation therapist, or (7) any other words, abbreviation, or insignia indicating that he or she is a respiratory care practitioner.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c415.pdf?cite=1987%20c%20415%20§%204[1987 c 415 § 4]; ]

== 18.89.040 - Scope of practice.
. A respiratory care practitioner licensed under this chapter is employed in the treatment, management, diagnostic testing, rehabilitation, and care of patients with deficiencies and abnormalities which affect the cardiopulmonary system and associated aspects of other systems, and is under the direct order and under the qualified medical direction of a health care practitioner. The practice of respiratory care includes:

.. The use and administration of prescribed medical gases, exclusive of general anesthesia;

.. The use of air and oxygen administering apparatus;

.. The use of humidification and aerosols;

.. The administration, to the extent of training, as determined by the secretary, of prescribed pharmacologic agents related to respiratory care;

.. The use of mechanical ventilatory, hyperbaric, and physiological support;

.. Postural drainage, chest percussion, and vibration;

.. Bronchopulmonary hygiene;

.. Cardiopulmonary resuscitation as it pertains to advanced cardiac life support or pediatric advanced life support guidelines;

.. The maintenance of natural and artificial airways and insertion, without cutting tissues, of artificial airways, as prescribed by a health care practitioner;

.. Diagnostic and monitoring techniques such as the collection and measurement of cardiorespiratory specimens, volumes, pressures, and flows;

.. The insertion of devices to draw, analyze, infuse, or monitor pressure in arterial, capillary, or venous blood as prescribed by a health care practitioner; and

.. Diagnostic monitoring of and therapeutic interventions for desaturation, ventilatory patterns, and related sleep abnormalities to aid the health care practitioner in diagnosis. This subsection does not prohibit any person from performing sleep monitoring tasks as set forth in this subsection under the supervision or direction of a licensed health care provider.

. Nothing in this chapter prohibits or restricts:

.. The practice of a profession by individuals who are licensed under other laws of this state who are performing services within their authorized scope of practice, that may overlap the services provided by respiratory care practitioners;

.. The practice of respiratory care by an individual employed by the government of the United States while the individual is engaged in the performance of duties prescribed for him or her by the laws and rules of the United States;

.. The practice of respiratory care by a person pursuing a supervised course of study leading to a degree or certificate in respiratory care as a part of an accredited and approved educational program, if the person is designated by a title that clearly indicates his or her status as a student or trainee and limited to the extent of demonstrated proficiency of completed curriculum, and under direct supervision;

.. The use of the title "respiratory care practitioner" by registered nurses authorized under chapter 18.79 RCW; or

.. The practice without compensation of respiratory care of a family member.

Nothing in this chapter shall be construed to require that individual or group policies or contracts of an insurance carrier, health care service contractor, or health maintenance organization provide benefits or coverage for services and supplies provided by a person licensed under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1640.SL.pdf?cite=2011%20c%20235%20§%202[2011 c 235 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5262.SL.pdf?cite=1999%20c%2084%20§%201[1999 c 84 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1536-S.SL.pdf?cite=1997%20c%20334%20§%204[1997 c 334 § 4]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20716[1994 sp.s. c 9 § 716]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c415.pdf?cite=1987%20c%20415%20§%205[1987 c 415 § 5]; ]

== 18.89.050 - Powers of secretary—Ad hoc advisers—Application of Uniform Disciplinary Act.
. In addition to any other authority provided by law, the secretary may:

.. Adopt rules, in accordance with chapter 34.05 RCW, necessary to implement this chapter;

.. Set all license, examination, and renewal fees in accordance with RCW 43.70.250;

.. Establish forms and procedures necessary to administer this chapter;

.. Issue a license to any applicant who has met the education, training, and examination requirements for licensure;

.. Hire clerical, administrative, and investigative staff as needed to implement this chapter and hire individuals licensed under this chapter to serve as examiners for any practical examinations;

.. Approve those schools from which graduation will be accepted as proof of an applicant's eligibility to take the licensure examination, specifically requiring that applicants must have completed an accredited respiratory program with two-year curriculum;

.. Prepare, grade, and administer, or determine the nature of, and supervise the grading and administration of, examinations for applicants for licensure;

.. Determine whether alternative methods of training are equivalent to formal education and establish forms, procedures, and criteria for evaluation of an applicant's alternative training to determine the applicant's eligibility to take the examination;

.. Determine which states have legal credentialing requirements equivalent to those of this state and issue licenses to individuals legally credentialed in those states without examination;

.. Define and approve any experience requirement for licensure; and

.. Appoint members of the profession to serve in an ad hoc advisory capacity to the secretary in carrying out this chapter. The members will serve for designated times and provide advice on matters specifically identified and requested by the secretary. The members shall be compensated in accordance with RCW 43.03.220 and reimbursed for travel expenses under RCW 43.03.040 and 43.03.060.

. The provisions of chapter 18.130 RCW shall govern the issuance and denial of licenses, unlicensed practice, and the disciplining of persons licensed under this chapter. The secretary shall be the disciplining authority under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6554-S.SL.pdf?cite=2004%20c%20262%20§%2013[2004 c 262 § 13]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1536-S.SL.pdf?cite=1997%20c%20334%20§%205[1997 c 334 § 5]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20512[1994 sp.s. c 9 § 512]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20228[1991 c 3 § 228]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c415.pdf?cite=1987%20c%20415%20§%206[1987 c 415 § 6]; ]

== 18.89.060 - Record of proceedings.
The secretary shall keep an official record of all proceedings, a part of which record shall consist of a register of all applicants for licensure under this chapter, with the result of each application.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1536-S.SL.pdf?cite=1997%20c%20334%20§%206[1997 c 334 § 6]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20229[1991 c 3 § 229]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c415.pdf?cite=1987%20c%20415%20§%207[1987 c 415 § 7]; ]

== 18.89.080 - Secretary and ad hoc committee immune from liability.
The secretary, ad hoc committee members, or individuals acting on their behalf are immune from suit in any civil action based on any licensure or disciplinary proceedings, or other official acts performed in the course of their duties.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1536-S.SL.pdf?cite=1997%20c%20334%20§%207[1997 c 334 § 7]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20513[1994 sp.s. c 9 § 513]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20231[1991 c 3 § 231]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c415.pdf?cite=1987%20c%20415%20§%209[1987 c 415 § 9]; ]

== 18.89.090 - Licensure—Qualifications.
. The secretary shall issue a license to any applicant who demonstrates to the secretary's satisfaction that the following requirements have been met:

.. Graduation from a school approved by the secretary or successful completion of alternate training which meets the criteria established by the secretary;

.. Successful completion of an examination administered or approved by the secretary;

.. Successful completion of any experience requirement established by the secretary;

.. Good moral character.

In addition, applicants shall be subject to the grounds for denial or issuance of a conditional license under chapter 18.130 RCW.

. A person who meets the qualifications to be admitted to the examination for licensure as a respiratory care practitioner may practice as a respiratory care practitioner under the supervision of a respiratory care practitioner licensed under this chapter between the date of filing an application for licensure and the announcement of the results of the next succeeding examination for licensure if that person applies for and takes the first examination for which he or she is eligible.

. A person certified as a respiratory care practitioner in good standing on July 1, 1998, who applies within one year of July 1, 1998, may be licensed without having completed the two-year curriculum set forth in RCW 18.89.050(1)(f), and without having to retake an examination under subsection (1)(b) of this section.

. The secretary shall establish by rule what constitutes adequate proof of meeting the criteria.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1536-S.SL.pdf?cite=1997%20c%20334%20§%208[1997 c 334 § 8]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20232[1991 c 3 § 232]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c415.pdf?cite=1987%20c%20415%20§%2010[1987 c 415 § 10]; ]

== 18.89.095 - Licensure—Qualifications—Military training or experience.
An applicant with military training or experience satisfies the training or experience requirements of this chapter unless the secretary determines that the military training or experience is not substantially equivalent to the standards of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5307-S.SL.pdf?cite=2011%20c%2032%20§%2011[2011 c 32 § 11]; ]

== 18.89.100 - Certification—Competency requirements.
The secretary shall approve only those persons who have achieved the minimum level of competency as defined by the secretary. The secretary shall establish by rule the standards and procedures for approval of alternate training and shall have the authority to contract with individuals or organizations having expertise in the profession, or in education, to assist in evaluating those applying for approval. The standards and procedures set shall apply equally to schools and training within the United States and those in foreign jurisdictions.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20233[1991 c 3 § 233]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c415.pdf?cite=1987%20c%20415%20§%2011[1987 c 415 § 11]; ]

== 18.89.110 - Licensure—Examination.
. The date and location of the examination shall be established by the secretary. Applicants who have been found by the secretary to meet the other requirements for licensure shall be scheduled for the next examination following the filing of the application. However, the applicant shall not be scheduled for any examination taking place sooner than sixty days after the application is filed.

. The secretary shall examine each applicant, by means determined most effective, on subjects appropriate to the scope of practice. Such examinations shall be limited to the purpose of determining whether the applicant possesses the minimum skill and knowledge necessary to practice competently, and shall meet generally accepted standards of fairness and validity for licensure examinations.

. All examinations shall be conducted by the secretary, and all grading of the examinations shall be under fair and wholly impartial methods.

. Any applicant who fails to make the required grade in the first examination is entitled to take up to three subsequent examinations, upon compliance with administrative procedures, administrative requirements, and fees determined by the secretary under RCW 43.70.250 and 43.70.280 and such remedial education as is deemed necessary.

. Applicants who meet the educational criteria as established by the national board for respiratory care to sit for the national board for respiratory care's advanced practitioner exams, or who have been issued the registered respiratory therapist credential by the national board for respiratory care, shall be considered to have met the educational criteria of this chapter, provided the criteria and credential continue to be recognized by the secretary as equal to or greater than the licensure standards in Washington. Applicants must have verification submitted directly from the national board for respiratory care to the department.

. The secretary may approve an examination prepared and administered by a private testing agency or association of credentialing boards for use by an applicant in meeting the licensure requirement.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6554-S.SL.pdf?cite=2004%20c%20262%20§%2014[2004 c 262 § 14]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1536-S.SL.pdf?cite=1997%20c%20334%20§%209[1997 c 334 § 9]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2076[1996 c 191 § 76]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20234[1991 c 3 § 234]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c415.pdf?cite=1987%20c%20415%20§%2012[1987 c 415 § 12]; ]

== 18.89.120 - Licensure—Application form—Fee.
Applications for licensure shall be submitted on forms provided by the secretary. The secretary may require any information and documentation which reasonably relates to the need to determine whether the applicant meets the criteria for licensure provided in this chapter and chapter 18.130 RCW. All applicants shall comply with administrative procedures, administrative requirements, and fees determined by the secretary under RCW 43.70.250 and 43.70.280.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1536-S.SL.pdf?cite=1997%20c%20334%20§%2010[1997 c 334 § 10]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2077[1996 c 191 § 77]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20235[1991 c 3 § 235]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c415.pdf?cite=1987%20c%20415%20§%2013[1987 c 415 § 13]; ]

== 18.89.140 - Renewal of licenses—Continuing education.
Licenses shall be renewed according to administrative procedures, administrative requirements, continuing education requirements, and fees determined by the secretary under RCW 43.70.250 and 43.70.280. A minimum of thirty hours of continuing education approved by the secretary must be completed every two years to meet the continuing education requirements under this section.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2452.SL.pdf?cite=2000%20c%2093%20§%2043[2000 c 93 § 43]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1536-S.SL.pdf?cite=1997%20c%20334%20§%2011[1997 c 334 § 11]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2078[1996 c 191 § 78]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20237[1991 c 3 § 237]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c415.pdf?cite=1987%20c%20415%20§%2015[1987 c 415 § 15]; ]

== 18.89.150 - Reciprocity.
An applicant holding a license in another state may be licensed to practice in this state without examination if the secretary determines that the other state's licensing standards are substantially equivalent to the standards in this state.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1536-S.SL.pdf?cite=1997%20c%20334%20§%2012[1997 c 334 § 12]; ]

