= 18.76 - Poison information centers.
:toc:

== 18.76.010 - Purpose.
The legislature finds that accidental and purposeful exposure to drugs, poisons, and toxic substances continues to be a severe health problem in the state of Washington. It further finds that a significant reduction in the consequences of such accidental exposures has occurred as a result of the services provided by poison information centers.

The purpose of this chapter is to reduce morbidity and mortality associated with overdose and poisoning incidents by providing emergency telephone assistance and treatment referral to victims of such incidents, by providing immediate treatment information to health care professionals, and public education and prevention programs. Further, the purpose is to improve utilization of drugs by providing information to health professionals relating to appropriate therapeutic drug use.

The legislature recognizes that enhanced cooperation between the emergency medical system and poison control centers will aid in responding to emergencies resulting from exposure to drugs, poisons, and toxic substances, and that, by providing telephone assistance to individuals with possible exposure to these substances, the need for emergency room and professional office visits will be reduced. As a result the cost of health care to those who may have exposures to drugs, poisons, and toxic substances will be avoided and appropriate treatment will be assured.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5239-S2.SL.pdf?cite=1993%20c%20343%20§%201[1993 c 343 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c214.pdf?cite=1987%20c%20214%20§%2016[1987 c 214 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c178.pdf?cite=1980%20c%20178%20§%201[1980 c 178 § 1]; ]

== 18.76.020 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter:

. "Department" means the department of health.

. "Poison information center medical director" means a person who: (a) Is licensed to practice medicine and surgery under chapter 18.71 RCW or osteopathic medicine and surgery under chapter 18.57 RCW; (b) is certified by the secretary under standards adopted under RCW 18.76.050; and (c) provides services enumerated under RCW 18.76.030, and is responsible for supervision of poison information specialists.

. "Poison information specialist" means a person who provides services enumerated under RCW 18.76.030 under the supervision of a poison information center medical director and is certified by the secretary under standards adopted under RCW 18.76.050.

. "Secretary" means the secretary of health.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1627.SL.pdf?cite=1996%20c%20178%20§%207[1996 c 178 § 7]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20184[1991 c 3 § 184]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c214.pdf?cite=1987%20c%20214%20§%2019[1987 c 214 § 19]; ]

== 18.76.030 - Poison information center—Statewide program.
The department shall, in a manner consistent with this chapter, provide support for the statewide program of poison and drug information services. These services shall, no later than June 30, 1993, be centralized in and coordinated by a single nonprofit center to be located in a place determined by the secretary. The services of this center shall be:

. Twenty-four hour emergency telephone management and treatment referral of victims of poisoning and overdose incidents, to include determining whether treatment can be accomplished at the scene of the incident or transport to an emergency treatment or other facility is required, and carrying out telephone follow-up to assure that adequate care is provided;

. Providing information to health professionals involved in management of poisoning and overdose victims;

. Coordination and development of community education programs designed to inform the public and members of the health professions of poison prevention and treatment methods and to improve awareness of poisoning and overdose problems, occupational risks, and environmental exposures; and

. Coordination of outreach units whose primary functions shall be to inform the public about poison problems and prevention methods, how to utilize the poison center, and other toxicology issues.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5239-S2.SL.pdf?cite=1993%20c%20343%20§%202[1993 c 343 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c214.pdf?cite=1987%20c%20214%20§%2017[1987 c 214 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c178.pdf?cite=1980%20c%20178%20§%202[1980 c 178 § 2]; ]

== 18.76.041 - Consulting with other poison programs.
The department shall establish a system for consulting with other state and local agency programs concerned with poisons and poisonings, incidents involving exposures to potentially poisonous substances, and other toxicological matters to develop the most coordinated and consistent response to such situations as is reasonably possible.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5239-S2.SL.pdf?cite=1993%20c%20343%20§%203[1993 c 343 § 3]; ]

== 18.76.050 - Rules and standards.
The secretary with the advice of the emergency medical services and trauma care steering committee established under *RCW 18.73.050 shall adopt rules, under chapter 34.05 RCW, prescribing:

. Standards for the operation of a poison information center;

. Standards and procedures for certification, recertification and decertification of poison center medical directors and poison information specialists; and

. Standards and procedures for reciprocity with other states or national certifying agencies.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c269.pdf?cite=1990%20c%20269%20§%2021[1990 c 269 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c214.pdf?cite=1987%20c%20214%20§%2020[1987 c 214 § 20]; ]

== 18.76.060 - Poison center medical director—Poison information specialist—Certification required.
. A person may not act as a poison center medical director or perform the duties of poison information specialists of a poison information center without being certified by the secretary under this chapter.

. Notwithstanding subsection (1) of this section, if a poison center medical director terminates certification or is decertified, that poison center medical director's authority may be delegated by the department to any other person licensed to practice medicine and surgery under chapter 18.71 RCW or osteopathic medicine and surgery under chapter 18.57 RCW for a period of thirty days, or until a new poison center medical director is certified, whichever comes first.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1627.SL.pdf?cite=1996%20c%20178%20§%208[1996 c 178 § 8]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5239-S2.SL.pdf?cite=1993%20c%20343%20§%204[1993 c 343 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c214.pdf?cite=1987%20c%20214%20§%2021[1987 c 214 § 21]; ]

== 18.76.070 - Immunity from liability.
. No act done or omitted in good faith while performing duties as a poison center medical director or poison information specialist of a poison information center shall impose any liability on the poison center, its officers, the poison center medical director, the poison information specialist, or other employees.

. This section:

.. Applies only to acts or omissions committed or omitted in the performance of duties which are within the area of responsibility and expertise of the poison center medical director or poison information specialist.

.. Does not relieve the poison center or any person from any duty imposed by law for the designation or training of a person certified under this chapter.

.. Does not apply to any act or omission which constitutes gross negligence or wilful or wanton conduct.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c214.pdf?cite=1987%20c%20214%20§%2022[1987 c 214 § 22]; ]

== 18.76.080 - Department to defend personnel.
The department shall defend any poison center medical director or poison information specialist for any act or omission subject to RCW 18.76.070.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c214.pdf?cite=1987%20c%20214%20§%2023[1987 c 214 § 23]; ]

== 18.76.090 - Use of gifts and grants.
The center may receive gifts, grants, and endowments from public or private sources that may be made from time to time, in trust or otherwise, for the use and benefit of the purposes of the center and spend gifts, grants, or endowments or any income from the public or private sources according to their terms.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5239-S2.SL.pdf?cite=1993%20c%20343%20§%205[1993 c 343 § 5]; ]

== 18.76.110 - Certificate suspension—Noncompliance with support order—Reissuance.
The department shall immediately suspend the certification of a poison center medical director or a poison information specialist who has been certified pursuant to RCW 74.20A.320 by the department of social and health services as a person who is not in compliance with a support order or a *residential or visitation order. If the person has continued to meet all other requirements for certification during the suspension, reissuance of the certification shall be automatic upon the department's receipt of a release issued by the department of social and health services stating that the person is in compliance with the order.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3901.SL.pdf?cite=1997%20c%2058%20§%20825[1997 c 58 § 825]; ]

