= 18.83 - Psychologists.
:toc:

== 18.83.010 - Definitions.
When used in this chapter:

. The "practice of psychology" means the observation, evaluation, interpretation, and modification of human behavior by the application of psychological principles, methods, and procedures for the purposes of preventing or eliminating symptomatic or maladaptive behavior and promoting mental and behavioral health. It includes, but is not limited to, providing the following services to individuals, families, groups, organizations, and the public, whether or not payment is received for services rendered:

.. Psychological measurement, assessment, and evaluation by means of psychological, neuropsychological, and psychoeducational testing;

.. Diagnosis and treatment of mental, emotional, and behavioral disorders, and psychological aspects of illness, injury, and disability; and

.. Counseling and guidance, psychotherapeutic techniques, remediation, health promotion, and consultation within the context of established psychological principles and theories.

This definition does not include the teaching of principles of psychology for accredited educational institutions, or the conduct of research in problems of human or animal behavior.

Nothing in this definition shall be construed as permitting the administration or prescribing of drugs or in any way infringing upon the practice of medicine and surgery as defined in chapter 18.71 RCW.

. "Secretary" means the secretary of health.

. "Board" means the examining board of psychology.

. "Department" means the department of health.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=1994%20c%2035%20§%201[1994 c 35 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20193[1991 c 3 § 193]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c279.pdf?cite=1984%20c%20279%20§%2075[1984 c 279 § 75]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c158.pdf?cite=1979%20c%20158%20§%2067[1979 c 158 § 67]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c70.pdf?cite=1965%20c%2070%20§%201[1965 c 70 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c305.pdf?cite=1955%20c%20305%20§%201[1955 c 305 § 1]; ]

== 18.83.020 - License required—Use of "psychology" or similar terms.
. To safeguard the people of the state of Washington from the dangers of unqualified and improper practice of psychology, it is unlawful for any person to whom this chapter applies to represent himself or herself to be a psychologist without first obtaining a license as provided in this chapter.

. A person represents himself or herself to be a psychologist when the person adopts or uses any title or any description of services which incorporates one or more of the following terms: "psychology," "psychological," "psychologist," or any term of like import.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c27.pdf?cite=1986%20c%2027%20§%201[1986 c 27 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c70.pdf?cite=1965%20c%2070%20§%202[1965 c 70 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c305.pdf?cite=1955%20c%20305%20§%202[1955 c 305 § 2]; ]

== 18.83.035 - Examining board—Composition—Terms—Chairperson.
There is created the examining board of psychology which shall examine the qualifications of applicants for licensing. The board shall consist of seven psychologists and two public members, all appointed by the governor. The public members shall not be and have never been psychologists or in training to be psychologists; they may not have any household member who is a psychologist or in training to be a psychologist; they may not participate or ever have participated in a commercial or professional field related to psychology, nor have a household member who has so participated; and they may not have had within two years before appointment a substantial financial interest in a person regulated by the board. Each psychologist member of the board shall be a citizen of the United States who has actively practiced psychology in the state of Washington for at least three years immediately preceding appointment and who is licensed under this chapter. Board members shall be appointed for a term of five years, except that the terms of the existing appointees shall be adjusted by the governor so that no more than two members' terms expire each year with all subsequent appointments for a five-year term. Upon the death, resignation, or removal of a member, the governor shall appoint a successor to serve for the unexpired term. The board shall elect one of its members to serve as chairperson.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c226.pdf?cite=1989%20c%20226%20§%201[1989 c 226 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c27.pdf?cite=1986%20c%2027%20§%202[1986 c 27 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c279.pdf?cite=1984%20c%20279%20§%2076[1984 c 279 § 76]; ]

== 18.83.045 - Examining board—Generally.
The board shall meet at least once each year and at such other times as the board deems appropriate to properly discharge its duties. All meetings shall be held in Olympia, Washington, or such other places as may be designated by the secretary. Five members of the board shall constitute a quorum, except that oral examinations may be conducted with only three psychologist members.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20195[1991 c 3 § 195]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c279.pdf?cite=1984%20c%20279%20§%2077[1984 c 279 § 77]; ]

== 18.83.050 - Examining board—Powers and duties.
. The board shall adopt such rules as it deems necessary to carry out its functions.

. The board shall examine the qualifications of applicants for licensing under this chapter, to determine which applicants are eligible for licensing under this chapter and shall forward to the secretary the names of applicants so eligible.

. The board shall administer examinations to qualified applicants on at least an annual basis. The board shall determine the subject matter and scope of the examination, except as provided in RCW 18.83.170. The board may allow applicants to take the examination upon the granting of their doctoral degree before completion of their internship for supervised experience.

. The board shall keep a complete record of its own proceedings, of the questions given in examinations, of the names and qualifications of all applicants, and the names and addresses of all licensed psychologists. The examination paper of such applicant shall be kept on file for a period of at least one year after examination.

. The board shall, by rule, adopt a code of ethics for psychologists which is designed to protect the public interest.

. The board may require that persons licensed under this chapter as psychologists obtain and maintain professional liability insurance in amounts determined by the board to be practicable and reasonably available.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6554-S.SL.pdf?cite=2004%20c%20262%20§%208[2004 c 262 § 8]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=1994%20c%2035%20§%202[1994 c 35 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20196[1991 c 3 § 196]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c27.pdf?cite=1986%20c%2027%20§%203[1986 c 27 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c279.pdf?cite=1984%20c%20279%20§%2078[1984 c 279 § 78]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c70.pdf?cite=1965%20c%2070%20§%205[1965 c 70 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c305.pdf?cite=1955%20c%20305%20§%205[1955 c 305 § 5]; ]

== 18.83.051 - Examining board—Compensation and travel expenses.
Each member of the board shall be compensated in accordance with RCW 43.03.240 and in addition thereto shall be reimbursed for travel expenses incurred in carrying out the duties of the board in accordance with RCW 43.03.050 and 43.03.060.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c287.pdf?cite=1984%20c%20287%20§%2048[1984 c 287 § 48]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c168.pdf?cite=1983%20c%20168%20§%2010[1983 c 168 § 10]; 1975-'76 2nd ex.s. c 34 § 48; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c199.pdf?cite=1969%20ex.s.%20c%20199%20§%2019[1969 ex.s. c 199 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c70.pdf?cite=1965%20c%2070%20§%2021[1965 c 70 § 21]; ]

== 18.83.054 - Application of uniform disciplinary act.
. The uniform disciplinary act, chapter 18.130 RCW, governs unlicensed practice, the issuance and denial of licenses, and the discipline of licensees under this chapter, except that the term "unlicensed practice" shall be defined by RCW 18.83.180 rather than RCW 18.130.020.

. A person who holds a license under this chapter is subject to the uniform disciplinary act, chapter 18.130 RCW, at all times the license is maintained.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1734.SL.pdf?cite=1999%20c%2066%20§%201[1999 c 66 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c150.pdf?cite=1987%20c%20150%20§%2051[1987 c 150 § 51]; ]

== 18.83.060 - Application, examination—Fees.
Administrative procedures, administrative requirements, and fees for applications and examinations shall be established as provided in RCW 43.70.250 and 43.70.280.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2064[1996 c 191 § 64]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20197[1991 c 3 § 197]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c279.pdf?cite=1984%20c%20279%20§%2079[1984 c 279 § 79]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c30.pdf?cite=1975%201st%20ex.s.%20c%2030%20§%2072[1975 1st ex.s. c 30 § 72]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c70.pdf?cite=1965%20c%2070%20§%206[1965 c 70 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c305.pdf?cite=1955%20c%20305%20§%206[1955 c 305 § 6]; ]

== 18.83.070 - Applicants—Qualifications—Examination.
An applicant for a license as "psychologist" must submit proof to the board that:

. The applicant is of good moral character.

. The applicant holds a doctoral degree from a regionally accredited institution, obtained from an integrated program of graduate study in psychology as defined by rules of the board.

. The applicant has had no fewer than two years of supervised experience. The board shall adopt rules defining the circumstances under which supervised experience shall qualify the candidate for licensure.

. The applicant has passed the examination or examinations required by the board.

Any person holding a valid license to practice psychology in the state of Washington on June 7, 1984, shall be considered licensed under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6554-S.SL.pdf?cite=2004%20c%20262%20§%209[2004 c 262 § 9]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5308-S.SL.pdf?cite=1995%20c%20198%20§%2011[1995 c 198 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c279.pdf?cite=1984%20c%20279%20§%2080[1984 c 279 § 80]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c70.pdf?cite=1965%20c%2070%20§%207[1965 c 70 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c305.pdf?cite=1955%20c%20305%20§%207[1955 c 305 § 7]; ]

== 18.83.072 - Examinations.
. Examination of applicants shall be held in Olympia, Washington, or at such other place as designated by the secretary, at least annually at such times as the board may determine.

. Any applicant who fails to make a passing grade on the examination may be allowed to retake the examination. Any applicant who fails the examination a second time must obtain special permission from the board to take the examination again.

. The board may approve an examination prepared or administered by a private testing agency or association of licensing authorities.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6554-S.SL.pdf?cite=2004%20c%20262%20§%2010[2004 c 262 § 10]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2065[1996 c 191 § 65]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5308-S.SL.pdf?cite=1995%20c%20198%20§%2012[1995 c 198 § 12]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20198[1991 c 3 § 198]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c279.pdf?cite=1984%20c%20279%20§%2081[1984 c 279 § 81]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c266.pdf?cite=1971%20ex.s.%20c%20266%20§%2015[1971 ex.s. c 266 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c70.pdf?cite=1965%20c%2070%20§%2020[1965 c 70 § 20]; ]

== 18.83.080 - Licenses—Issuance—Display.
The board shall forward to the secretary the name of each applicant entitled to a license under this chapter. The secretary shall promptly issue to such applicant a license authorizing such applicant to use the title "psychologist". Each licensed psychologist shall keep his or her license displayed in a conspicuous place in his or her principal place of business.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2066[1996 c 191 § 66]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20199[1991 c 3 § 199]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c27.pdf?cite=1986%20c%2027%20§%204[1986 c 27 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c70.pdf?cite=1965%20c%2070%20§%208[1965 c 70 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c305.pdf?cite=1955%20c%20305%20§%208[1955 c 305 § 8]; ]

== 18.83.082 - Temporary permit.
A person, not licensed in this state, who wishes to perform practices under the provisions of this chapter for a period not to exceed ninety days within a calendar year, must petition the board for a temporary permit to perform such practices. If the person is licensed or certified in another state deemed by the board to have standards equivalent to this chapter, or if the person is a member of a professional organization and holds a certificate deemed by the board to meet standards equivalent to this chapter, a permit may be issued. No fee shall be charged for such temporary permit.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6554-S.SL.pdf?cite=2004%20c%20262%20§%2011[2004 c 262 § 11]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2067[1996 c 191 § 67]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c279.pdf?cite=1984%20c%20279%20§%2082[1984 c 279 § 82]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c30.pdf?cite=1975%201st%20ex.s.%20c%2030%20§%2073[1975 1st ex.s. c 30 § 73]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c70.pdf?cite=1965%20c%2070%20§%2023[1965 c 70 § 23]; ]

== 18.83.090 - Continuing education requirements—Human trafficking information—License renewal.
. The board shall establish rules governing mandatory continuing education requirements which shall be met by any psychologist applying for a license renewal.

. The office of crime victims advocacy shall supply the board with information on methods of recognizing victims of human trafficking, what services are available for these victims, and where to report potential trafficking situations. The information supplied must be culturally sensitive and must include information relating to minor victims. The board shall disseminate this information to licensees by: Providing the information on the board's website; including the information in newsletters; holding trainings at meetings attended by organization members; or through another distribution method determined by the board. The board shall report to the office of crime victims advocacy on the method or methods it uses to distribute information under this subsection.

. Administrative procedures, administrative requirements, and fees for renewal and reissue of licenses shall be established as provided in RCW 43.70.250 and 43.70.280.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5850-S2.SL.pdf?cite=2009%20c%20492%20§%206[2009 c 492 § 6]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2068[1996 c 191 § 68]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20200[1991 c 3 § 200]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c279.pdf?cite=1984%20c%20279%20§%2083[1984 c 279 § 83]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977c58.pdf?cite=1977%20c%2058%20§%201[1977 c 58 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c30.pdf?cite=1975%201st%20ex.s.%20c%2030%20§%2074[1975 1st ex.s. c 30 § 74]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c266.pdf?cite=1971%20ex.s.%20c%20266%20§%2016[1971 ex.s. c 266 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c70.pdf?cite=1965%20c%2070%20§%209[1965 c 70 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c305.pdf?cite=1955%20c%20305%20§%209[1955 c 305 § 9]; ]

== 18.83.105 - Certificates of qualification.
The board may issue certificates of qualification with appropriate title to applicants who meet all the licensing requirements except the possession of the degree of Doctor of Philosophy or its equivalent in psychology from an accredited educational institution. These certificates of qualification certify that the holder has been examined by the board and is deemed competent to perform certain functions within the practice of psychology under the periodic direct supervision of a psychologist licensed by the board. Such functions will be specified on the certificate issued by the board. Such applicant shall comply with administrative procedures, administrative requirements, and fees determined under RCW 43.70.250 and 43.70.280. Upon petition by a holder the board of examiners may grant authority to function without immediate supervision.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2069[1996 c 191 § 69]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20201[1991 c 3 § 201]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%2067[1985 c 7 § 67]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c30.pdf?cite=1975%201st%20ex.s.%20c%2030%20§%2075[1975 1st ex.s. c 30 § 75]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c70.pdf?cite=1965%20c%2070%20§%2022[1965 c 70 § 22]; ]

== 18.83.110 - Privileged communications.
Confidential communications between a client and a psychologist shall be privileged against compulsory disclosure to the same extent and subject to the same conditions as confidential communications between attorney and client, but this exception is subject to the limitations under RCW 71.05.217 (6) and (7).

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5720-S2.SL.pdf?cite=2020%20c%20302%20§%20116[2020 c 302 § 116]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1713-S3.SL.pdf?cite=2016%20sp.s.%20c%2029%20§%20414[2016 sp.s. c 29 § 414]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5763-S2.SL.pdf?cite=2005%20c%20504%20§%20706[2005 c 504 § 706]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c271.pdf?cite=1989%20c%20271%20§%20303[1989 c 271 § 303]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c439.pdf?cite=1987%20c%20439%20§%2012[1987 c 439 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c70.pdf?cite=1965%20c%2070%20§%2011[1965 c 70 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c305.pdf?cite=1955%20c%20305%20§%2011[1955 c 305 § 11]; ]

== 18.83.115 - Duty to disclose information to client.
. Psychologists licensed under this chapter shall provide clients at the commencement of any program of treatment with accurate disclosure information concerning their practice, in accordance with guidelines developed by the board, which will inform clients of the purposes of and resources available under this chapter, including the right of clients to refuse treatment, the responsibility of clients for choosing the provider and treatment modality which best suits their needs, and the extent of confidentiality provided by this chapter. The disclosure information provided by the psychologist, the receipt of which shall be acknowledged in writing by the psychologist and client, shall include any relevant education and training, the therapeutic orientation of the practice, the proposed course of treatment where known, any financial requirements, and such other information as the board may require by rule.

. In inpatient settings, the health facility shall provide clients with the disclosure statement at the commencement of any program of treatment, and shall post the statement in a conspicuous location accessible to the client.

. The board shall provide for modification of the guidelines as appropriate in cases where the client has been referred by the court, a state agency, or other governmental body to a particular provider for specified evaluation or treatment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c27.pdf?cite=1986%20c%2027%20§%209[1986 c 27 § 9]; ]

== 18.83.121 - Unprofessional conduct.
In addition to those acts defined in chapter 18.130 RCW, the board may take disciplinary action under RCW 18.130.160 for the following reasons:

. Failing to maintain the confidentiality of information under RCW 18.83.110;

. Violating the ethical code developed by the board under RCW 18.83.050;

. Failing to inform prospective research subjects or their authorized representatives of the possible serious effects of participation in research; and failing to undertake reasonable efforts to remove possible harmful effects of participation;

. Practicing in an area of psychology for which the person is clearly untrained or incompetent;

. Failing to exercise appropriate supervision over persons who practice under the supervision of a psychologist;

. Using fraud or deceit in the procurement of the psychology license, or knowingly assisting another in the procurement of such a license through fraud or deceit;

. Failing to maintain professional liability insurance when required by the board;

. Violating any state statute or administrative rule specifically governing the practice of psychology; or

. Gross, wilful, or continued overcharging for professional services.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c150.pdf?cite=1987%20c%20150%20§%2052[1987 c 150 § 52]; ]

== 18.83.135 - Examining board—Powers and duties.
In addition to the authority prescribed under RCW 18.130.050, the board shall have the following authority:

. To maintain records of all activities, and to publish and distribute to all psychologists at least once each year abstracts of significant activities of the board;

. To obtain the written consent of the complaining client or patient or their legal representative, or of any person who may be affected by the complaint, in order to obtain information which otherwise might be confidential or privileged; and

. To apply the provisions of the uniform disciplinary act, chapter 18.130 RCW, to all persons licensed as psychologists under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2452.SL.pdf?cite=2000%20c%2093%20§%207[2000 c 93 § 7]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1734.SL.pdf?cite=1999%20c%2066%20§%202[1999 c 66 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=1994%20c%2035%20§%204[1994 c 35 § 4]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2358.SL.pdf?cite=1992%20c%2012%20§%201[1992 c 12 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c150.pdf?cite=1987%20c%20150%20§%2053[1987 c 150 § 53]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c279.pdf?cite=1984%20c%20279%20§%2086[1984 c 279 § 86]; ]

== 18.83.155 - Examining board—Notice of disciplinary action.
The board shall report to appropriate national and state organizations which represent the profession of psychology any disciplinary action.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=1994%20c%2035%20§%205[1994 c 35 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c150.pdf?cite=1987%20c%20150%20§%2054[1987 c 150 § 54]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c279.pdf?cite=1984%20c%20279%20§%2089[1984 c 279 § 89]; ]

== 18.83.170 - License without oral examination—Reciprocity program.
. Upon compliance with administrative procedures, administrative requirements, and fees determined under RCW 43.70.250 and 43.70.280, the board may grant a license, without oral examination, to any applicant who has not previously failed any examination held by the board of psychology of the state of Washington and furnishes evidence satisfactory to the board that the applicant:

.. Holds a doctoral degree with primary emphasis on psychology from an accredited college or university; and

.. [Empty]
... Is licensed or certified to practice psychology in another state or country in which the requirements for such licensing or certification are, in the judgment of the board, essentially equivalent to those required by this chapter and the rules and regulations of the board. Such individuals must have been licensed or certified in another state for a period of at least two years; or

... Is a diplomate in good standing of the American Board of Examiners in Professional Psychology; or

... Is a member of a professional organization and holds a certificate deemed by the board to meet standards equivalent to this chapter.

. [Empty]
.. [Empty]
... The department shall establish a reciprocity program for applicants for licensure as a psychologist in Washington.

... The reciprocity program applies to applicants for a license as a psychologist who:

(A) Hold or have held within the past twelve months a credential in good standing from another state or territory of the United States which has a scope of practice that is substantially equivalent to or greater than the scope of practice for licensed psychologists as established under this chapter; and

(B) Have no disciplinary record or disqualifying criminal history.

.. The department shall issue a probationary license to an applicant who meets the requirements of (a)(ii) of this subsection. The department must determine what deficiencies, if any, exist between the education and experience requirements of the other state's credential and, after consideration of the experience and capabilities of the applicant, determine whether it is appropriate to require the applicant to complete additional education or experience requirements to maintain the probationary license and, within a reasonable time period, transition to a full license. A person who holds a probationary license may only practice as a psychologist in a licensed or certified service provider, as defined in *RCW 71.24.025. The department may place a reasonable time limit on a probationary license and may, if appropriate, require the applicant to pass a jurisprudential examination.

.. The department must maintain and publish a list of credentials in other states and territories that the department has determined to have a scope of practice that is substantially equivalent to or greater than the scope of practice for licensed psychologists as established under this chapter. The department shall prioritize identifying and publishing the department's determination for the five states or territories that have historically had the most applicants for reciprocity under subsection (1) of this section with a scope of practice that is substantially equivalent to or greater than the scope of practice for licensed psychologists as established under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5054.SL.pdf?cite=2019%20c%20351%20§%201[2019 c 351 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6554-S.SL.pdf?cite=2004%20c%20262%20§%2012[2004 c 262 § 12]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2070[1996 c 191 § 70]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20202[1991 c 3 § 202]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c279.pdf?cite=1984%20c%20279%20§%2092[1984 c 279 § 92]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c30.pdf?cite=1975%201st%20ex.s.%20c%2030%20§%2076[1975 1st ex.s. c 30 § 76]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c70.pdf?cite=1965%20c%2070%20§%2017[1965 c 70 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c305.pdf?cite=1955%20c%20305%20§%2017[1955 c 305 § 17]; ]

== 18.83.180 - Penalties.
It shall be a gross misdemeanor and unlicensed practice for any person to:

. Use in connection with his or her name any designation tending to imply that he or she is a licensed psychologist unless duly licensed under or specifically excluded from the provisions of this chapter;

. Practice as a licensed psychologist during the time his or her license issued under the provisions of this chapter is suspended or revoked.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c150.pdf?cite=1987%20c%20150%20§%2055[1987 c 150 § 55]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c70.pdf?cite=1965%20c%2070%20§%2018[1965 c 70 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c305.pdf?cite=1955%20c%20305%20§%2018[1955 c 305 § 18]; ]

== 18.83.190 - Injunction.
If any person represents himself or herself to be a psychologist, unless the person is exempt from the provisions of this chapter, without possessing a valid license, certificated qualification, or a temporary permit to do so, or if he or she violates any of the provisions of this chapter, any prosecuting attorney, the secretary, or any citizen of the same county may maintain an action in the name of the state to enjoin such person from representing himself or herself as a psychologist. The injunction shall not relieve the person from criminal prosecution, but the remedy by injunction shall be in addition to the liability of such offender to criminal prosecution and to suspension or revocation of his or her license.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20203[1991 c 3 § 203]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c27.pdf?cite=1986%20c%2027%20§%208[1986 c 27 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c70.pdf?cite=1965%20c%2070%20§%2024[1965 c 70 § 24]; ]

== 18.83.200 - Exemptions.
This chapter shall not apply to:

. Any person teaching, lecturing, consulting, or engaging in research in psychology but only insofar as such activities are performed as a part of or are dependent upon a position in a college or university in the state of Washington.

. Any person who holds a valid school psychologist credential from the Washington professional educator standards board but only when such a person is practicing psychology in the course of his or her employment.

. Any person employed by a local, state, or federal government agency whose psychologists must qualify for employment under federal or state certification or civil service regulations; but only at those times when that person is carrying out the functions of his or her employment.

. Any person who must qualify under the employment requirements of a business or industry and who is employed by a business or industry which is not engaged in offering psychological services to the public, but only when such person is carrying out the functions of his or her employment: PROVIDED, That no person exempt from licensing under this subsection shall engage in the clinical practice of psychology.

. Any person who is a student of psychology, psychological intern, or resident in psychology preparing for the profession of psychology under supervision in a training institution or facilities and who is designated by the title such as "psychological trainee," "psychology student," which thereby indicates his or her training status.

. Any person who has received a doctoral degree from an accredited institution of higher learning with an adequate major in sociology or social psychology as determined by the board and who has passed comprehensive examinations in the field of social psychology as part of the requirements for the doctoral degree. Such persons may use the title "social psychologist" provided that they file a statement of their education with the board.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/3098-S2.SL.pdf?cite=2006%20c%20263%20§%20803[2006 c 263 § 803]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c27.pdf?cite=1986%20c%2027%20§%2010[1986 c 27 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c70.pdf?cite=1965%20c%2070%20§%2019[1965 c 70 § 19]; ]

== 18.83.210 - Certain counseling or guidance not prohibited.
Nothing in this chapter shall be construed as prohibiting any individual from offering counseling or guidance provided that such individuals do not hold themselves forth as psychologists.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c70.pdf?cite=1965%20c%2070%20§%2025[1965 c 70 § 25]; ]

== 18.83.220 - Supervised experience hours—Reduction for certified chemical dependency professionals.
The department shall reduce the total number of supervised experience hours required under RCW 18.83.070 by three months for any applicant for a license under this chapter who has practiced as a certified chemical dependency professional for three years in the previous ten years.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1768-S.SL.pdf?cite=2019%20c%20444%20§%2027[2019 c 444 § 27]; ]

