= 18.53 - Optometry.
:toc:

== 18.53.005 - Legislative finding and declaration.
The legislature finds and declares that the practice of optometry is a learned profession and affects the health, welfare and safety of the people of this state, and should be regulated in the public interest and limited to qualified persons licensed and authorized to practice under the provisions of chapters 18.53 and 18.54 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c58.pdf?cite=1981%20c%2058%20§%201[1981 c 58 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c69.pdf?cite=1975%201st%20ex.s.%20c%2069%20§%201[1975 1st ex.s. c 69 § 1]; ]

== 18.53.010 - Definition—Scope of practice.
. The practice of optometry is defined as the examination of the human eye, the examination and ascertaining any defects of the human vision system and the analysis of the process of vision. The practice of optometry may include, but not necessarily be limited to, the following:

.. The employment of any objective or subjective means or method, including the use of drugs, for diagnostic and therapeutic purposes by those licensed under this chapter and who meet the requirements of subsections (2) and (3) of this section, and the use of any diagnostic instruments or devices for the examination or analysis of the human vision system, the measurement of the powers or range of human vision, or the determination of the refractive powers of the human eye or its functions in general; and

.. The prescription and fitting of lenses, prisms, therapeutic or refractive contact lenses and the adaption or adjustment of frames and lenses used in connection therewith; and

.. The prescription and provision of visual therapy, therapeutic aids, and other optical devices; and

.. The ascertainment of the perceptive, neural, muscular, or pathological condition of the visual system; and

.. The adaptation of prosthetic eyes.

. [Empty]
.. Those persons using topical drugs for diagnostic purposes in the practice of optometry shall have a minimum of sixty hours of didactic and clinical instruction in general and ocular pharmacology as applied to optometry, as established by the board, and certification from an institution of higher learning, accredited by those agencies recognized by the United States office of education or the council on postsecondary accreditation to qualify for certification by the optometry board of Washington to use drugs for diagnostic purposes.

.. Those persons using or prescribing topical drugs for therapeutic purposes in the practice of optometry must be certified under (a) of this subsection, and must have an additional minimum of seventy-five hours of didactic and clinical instruction as established by the board, and certification from an institution of higher learning, accredited by those agencies recognized by the United States office of education or the council on postsecondary accreditation to qualify for certification by the optometry board of Washington to use drugs for therapeutic purposes.

.. Those persons using or prescribing drugs administered orally for diagnostic or therapeutic purposes in the practice of optometry shall be certified under (b) of this subsection, and shall have an additional minimum of sixteen hours of didactic and eight hours of supervised clinical instruction as established by the board, and certification from an institution of higher learning, accredited by those agencies recognized by the United States office of education or the council on postsecondary accreditation to qualify for certification by the optometry board of Washington to administer, dispense, or prescribe oral drugs for diagnostic or therapeutic purposes.

.. Those persons administering epinephrine by injection for treatment of anaphylactic shock in the practice of optometry must be certified under (b) of this subsection and must have an additional minimum of four hours of didactic and supervised clinical instruction, as established by the board, and certification from an institution of higher learning, accredited by those agencies recognized by the United States office of education or the council on postsecondary accreditation to qualify for certification by the optometry board to administer epinephrine by injection.

.. Such course or courses shall be the fiscal responsibility of the participating and attending optometrist.

.. [Empty]
... All persons receiving their initial license under this chapter on or after January 1, 2007, must be certified under (a), (b), (c), and (d) of this subsection.

... All persons licensed under this chapter on or after January 1, 2009, must be certified under (a) and (b) of this subsection.

... All persons licensed under this chapter on or after January 1, 2011, must be certified under (a), (b), (c), and (d) of this subsection.

. The board shall establish a list of topical drugs for diagnostic and treatment purposes limited to the practice of optometry, and no person licensed pursuant to this chapter shall prescribe, dispense, purchase, possess, or administer drugs except as authorized and to the extent permitted by the board.

. The board must establish a list of oral Schedule III through V controlled substances and any oral legend drugs, with the approval of and after consultation with the pharmacy quality assurance commission. The board may include Schedule II hydrocodone combination products consistent with subsection (6) of this section. No person licensed under this chapter may use, prescribe, dispense, purchase, possess, or administer these drugs except as authorized and to the extent permitted by the board. No optometrist may use, prescribe, dispense, or administer oral corticosteroids.

.. The board, with the approval of and in consultation with the pharmacy quality assurance commission, must establish, by rule, specific guidelines for the prescription and administration of drugs by optometrists, so that licensed optometrists and persons filling their prescriptions have a clear understanding of which drugs and which dosages or forms are included in the authority granted by this section.

.. An optometrist may not:

... Prescribe, dispense, or administer a controlled substance for more than seven days in treating a particular patient for a single trauma, episode, or condition or for pain associated with or related to the trauma, episode, or condition; or

... Prescribe an oral drug within ninety days following ophthalmic surgery unless the optometrist consults with the treating ophthalmologist.

.. If treatment exceeding the limitation in (b)(i) of this subsection is indicated, the patient must be referred to a physician licensed under chapter 18.71 RCW.

.. The prescription or administration of drugs as authorized in this section is specifically limited to those drugs appropriate to treatment of diseases or conditions of the human eye and the adnexa that are within the scope of practice of optometry. The prescription or administration of drugs for any other purpose is not authorized by this section.

. The board shall develop a means of identification and verification of optometrists certified to use therapeutic drugs for the purpose of issuing prescriptions as authorized by this section.

. Nothing in this chapter may be construed to authorize the use, prescription, dispensing, purchase, possession, or administration of any Schedule I or II controlled substance, except Schedule II hydrocodone combination products. The provisions of this subsection must be strictly construed.

. With the exception of the administration of epinephrine by injection for the treatment of anaphylactic shock, no injections or infusions may be administered by an optometrist.

. Nothing in this chapter may be construed to authorize optometrists to perform ophthalmic surgery. Ophthalmic surgery is defined as any invasive procedure in which human tissue is cut, ablated, or otherwise penetrated by incision, injection, laser, ultrasound, or other means, in order to: Treat human eye diseases; alter or correct refractive error; or alter or enhance cosmetic appearance. Nothing in this chapter limits an optometrist's ability to use diagnostic instruments utilizing laser or ultrasound technology. Ophthalmic surgery, as defined in this subsection, does not include removal of superficial ocular foreign bodies, epilation of misaligned eyelashes, placement of punctal or lacrimal plugs, diagnostic dilation and irrigation of the lacrimal system, orthokeratology, prescription and fitting of contact lenses with the purpose of altering refractive error, or other similar procedures within the scope of practice of optometry.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5293-S.SL.pdf?cite=2015%20c%20113%20§%201[2015 c 113 § 1]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1609.SL.pdf?cite=2013%20c%2019%20§%202[2013 c 19 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5535-S.SL.pdf?cite=2006%20c%20232%20§%201[2006 c 232 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5226-S.SL.pdf?cite=2003%20c%20142%20§%201[2003 c 142 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c36.pdf?cite=1989%20c%2036%20§%201[1989 c 36 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c58.pdf?cite=1981%20c%2058%20§%202[1981 c 58 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c69.pdf?cite=1975%201st%20ex.s.%20c%2069%20§%202[1975 1st ex.s. c 69 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c144.pdf?cite=1919%20c%20144%20§%201[1919 c 144 § 1]; RRS § 10147; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c235.pdf?cite=1909%20c%20235%20§%201[1909 c 235 § 1]; ]

== 18.53.021 - License required.
It is a violation of RCW 18.130.190 for any person to practice optometry in this state without first obtaining a license from the secretary of health.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20133[1991 c 3 § 133]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c150.pdf?cite=1987%20c%20150%20§%2038[1987 c 150 § 38]; ]

== 18.53.030 - Temporary permit—When issued.
The board may at its discretion, issue a permit to practice optometry during the interim between examinations, to any person who has filed an application for examination which has been accepted by the board as admitting the applicant to the next examination. Such permit shall be valid only until the date of the next examination and shall not be issued sooner than thirty days following any regular examination, and no permit shall be issued to any person who has failed before the board, nor where a certificate has been revoked.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c259.pdf?cite=1986%20c%20259%20§%2080[1986 c 259 § 80]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c144.pdf?cite=1919%20c%20144%20§%208[1919 c 144 § 8]; RRS § 10153; ]

== 18.53.035 - Credentialing by endorsement.
An applicant holding a credential in another state may be credentialed to practice in this state without examination if the board determines that the other state's credentialing standards are substantially equivalent to the standards in this state.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1960-S.SL.pdf?cite=1991%20c%20332%20§%2030[1991 c 332 § 30]; ]

== 18.53.040 - Exemptions—Exceptions—Limitation.
Nothing in this chapter shall be construed to pertain in any manner to the practice of any regularly qualified oculist or physician, who is regularly licensed to practice medicine in the state of Washington, or to any person who is regularly licensed to practice as a dispensing optician in the state of Washington, nor to any person who in the regular course of trade, sells or offers for sale, spectacles or eyeglasses as regular merchandise without pretense of adapting them to the eyes of the purchaser, and not in evasion of this chapter: PROVIDED, That any such regularly qualified oculist or physician or other person shall be subject to the provisions of RCW 18.53.140 (9) through (14), in connection with the performance of any function coming within the definition of the practice of optometry as defined in this chapter: PROVIDED FURTHER, HOWEVER, That in no way shall this section be construed to permit a dispensing optician to practice optometry as defined in chapter 69, Laws of 1975 1st ex. sess.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2400.SL.pdf?cite=2000%20c%20171%20§%2019[2000 c 171 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c69.pdf?cite=1975%201st%20ex.s.%20c%2069%20§%2015[1975 1st ex.s. c 69 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c155.pdf?cite=1937%20c%20155%20§%203[1937 c 155 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c144.pdf?cite=1919%20c%20144%20§%2015[1919 c 144 § 15]; Rem. Supp. 1937 § 10159; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c235.pdf?cite=1909%20c%20235%20§%2013[1909 c 235 § 13]; ]

== 18.53.050 - License renewal.
Every licensed optometrist shall renew his or her license by complying with administrative procedures, administrative requirements, and fees determined according to RCW 43.70.250 and 43.70.280.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2029[1996 c 191 § 29]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20134[1991 c 3 § 134]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%2051[1985 c 7 § 51]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c168.pdf?cite=1983%20c%20168%20§%208[1983 c 168 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c277.pdf?cite=1981%20c%20277%20§%208[1981 c 277 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c30.pdf?cite=1975%201st%20ex.s.%20c%2030%20§%2056[1975 1st ex.s. c 30 § 56]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c266.pdf?cite=1971%20ex.s.%20c%20266%20§%2010[1971 ex.s. c 266 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c275.pdf?cite=1955%20c%20275%20§%201[1955 c 275 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c144.pdf?cite=1919%20c%20144%20§%2013[1919 c 144 § 13]; RRS § 10158; ]

== 18.53.060 - License applicants—Eligibility—Qualifications—Examinations—Exception.
From and after January 1, 1940, in order to be eligible for examination for registration, a person shall be a citizen of the United States of America, who shall have a preliminary education of or equal to four years in a state accredited high school and has completed a full attendance course in a regularly chartered school of optometry maintaining a standard which is deemed sufficient and satisfactory by the optometry board, who is a person of good moral character, who has a visual acuity in at least one eye, of a standard known as 20/40 under correction: PROVIDED, That from and after January 1, 1975, in order to be eligible for examination for a license, a person shall have the following qualifications:

. Be a graduate of a state accredited high school or its equivalent;

. Have a diploma or other certificate of completion from an accredited college of optometry or school of optometry, maintaining a standard which is deemed sufficient and satisfactory by the optometry board, conferring its degree of doctor of optometry or its equivalent, maintaining a course of four scholastic years in addition to preprofessional college-level studies, and teaching substantially all of the following subjects: General anatomy, anatomy of the eyes, physiology, physics, chemistry, pharmacology, biology, bacteriology, general pathology, ocular pathology, ocular neurology, ocular myology, psychology, physiological optics, optometrical mechanics, clinical optometry, visual field charting and orthoptics, general laws of optics and refraction and use of the ophthalmoscope, retinoscope and other clinical instruments necessary in the practice of optometry; and

. Be of good moral character.

Such person shall file an application for an examination and license with said board at any time thirty days prior to the time fixed for such examination, or at a later date if approved by the board, and such application must be on forms approved by the board, and properly attested, and if found to be in accordance with the provisions of this chapter shall entitle the applicant upon payment of the proper fee, to take the examination prescribed by the board. Such examination shall not be out of keeping with the established teachings and adopted textbooks of the recognized schools of optometry, and shall be confined to such subjects and practices as are recognized as essential to the practice of optometry. All candidates without discrimination, who shall successfully pass the prescribed examination, shall be registered by the board and shall, upon payment of the proper fee, be issued a license. Any license to practice optometry in this state issued by the secretary, and which shall be in full force and effect at the time of passage of chapter 69, Laws of 1975 1st ex. sess., shall be continued.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5308-S.SL.pdf?cite=1995%20c%20198%20§%206[1995 c 198 § 6]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20135[1991 c 3 § 135]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c69.pdf?cite=1975%201st%20ex.s.%20c%2069%20§%204[1975 1st ex.s. c 69 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c155.pdf?cite=1937%20c%20155%20§%201[1937 c 155 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c144.pdf?cite=1919%20c%20144%20§%205[1919 c 144 § 5]; Rem. Supp. 1937 § 10150; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c235.pdf?cite=1909%20c%20235%20§%207[1909 c 235 § 7]; ]

== 18.53.070 - Licensing—Procedures, requirements, fees.
Administrative procedures, administrative requirements, and fees for issuing a license shall be determined as provided in RCW 43.70.250 and 43.70.280.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2030[1996 c 191 § 30]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20136[1991 c 3 § 136]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%2052[1985 c 7 § 52]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c260.pdf?cite=1981%20c%20260%20§%205[1981 c 260 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c69.pdf?cite=1975%201st%20ex.s.%20c%2069%20§%205[1975 1st ex.s. c 69 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c30.pdf?cite=1975%201st%20ex.s.%20c%2030%20§%2057[1975 1st ex.s. c 30 § 57]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c144.pdf?cite=1919%20c%20144%20§%209[1919 c 144 § 9]; RRS § 10151; prior:  1909 c 235 § 7; ]

== 18.53.100 - Disciplinary action—Grounds.
The following constitutes grounds for disciplinary action under chapter 18.130 RCW:

. Any form of fraud or deceit used in securing a license; or

. Any unprofessional conduct, of a nature likely to deceive or defraud the public; or

. The employing either directly or indirectly of any person or persons commonly known as "cappers" or "steerers" to obtain business; or

. To employ any person to solicit from house to house, or to personally solicit from house to house; or

. Advertisement in any way in which untruthful, improbable or impossible statements are made regarding treatments, cures or values; or

. The use of the term "eye specialist" in connection with the name of such optometrist; or

. Inability to demonstrate, in a manner satisfactory to the secretary or the board of optometry, their practical ability to perform any function set forth in RCW 18.53.010 which they utilize in their practice.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20137[1991 c 3 § 137]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c259.pdf?cite=1986%20c%20259%20§%2081[1986 c 259 § 81]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c69.pdf?cite=1975%201st%20ex.s.%20c%2069%20§%206[1975 1st ex.s. c 69 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c144.pdf?cite=1919%20c%20144%20§%2011[1919 c 144 § 11]; RRS § 10156; 1909 c 235 §§ 11, 12; ]

== 18.53.101 - Application of uniform disciplinary act.
The uniform disciplinary act, chapter 18.130 RCW, governs unlicensed practice, the issuance and denial of licenses, and the discipline of licensees under this chapter and chapter 18.54 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c150.pdf?cite=1987%20c%20150%20§%2036[1987 c 150 § 36]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c259.pdf?cite=1986%20c%20259%20§%2078[1986 c 259 § 78]; ]

== 18.53.140 - Unlawful acts.
It shall be unlawful for any person:

. To sell or barter, or offer to sell or barter any license issued by the secretary; or

. To purchase or procure by barter any license with the intent to use the same as evidence of the holder's qualification to practice optometry; or

. To alter with fraudulent intent in any material regard such license; or

. To use or attempt to use any such license which has been purchased, fraudulently issued, counterfeited or materially altered as a valid license; or

. To practice optometry under a false or assumed name, or as a representative or agent of any person, firm or corporation with which the licensee has no connection: PROVIDED, Nothing in this chapter nor in the optometry law shall make it unlawful for any lawfully licensed optometrist or association of lawfully licensed optometrists to practice optometry under the name of any lawfully licensed optometrist who may transfer by inheritance or otherwise the right to use such name; or

. To practice optometry in this state either for him or herself or any other individual, corporation, partnership, group, public or private entity, or any member of the licensed healing arts without having at the time of so doing a valid license issued by the secretary of health; or

. To in any manner barter or give away as premiums either on his or her own account or as agent or representative for any other purpose, firm or corporation, any eyeglasses, spectacles, lenses or frames; or

. To use drugs in the practice of optometry, except as authorized under RCW 18.53.010; or

. To use advertising whether printed, radio, display, or of any other nature, which is misleading or inaccurate in any material particular, nor shall any such person in any way misrepresent any goods or services (including but without limitation, its use, trademark, grade, quality, size, origin, substance, character, nature, finish, material, content, or preparation) or credit terms, values, policies, services, or the nature or form of the business conducted; or

. To advertise the "free examination of eyes," "free consultation," "consultation without obligation," "free advice," or any words or phrases of similar import which convey the impression to the public that eyes are examined free or of a character tending to deceive or mislead the public, or in the nature of "bait advertising;" or

. To use an advertisement of a frame or mounting which is not truthful in describing the frame or mounting and all its component parts. Or advertise a frame or mounting at a price, unless it shall be depicted in the advertisement without lenses inserted, and in addition the advertisement must contain a statement immediately following, or adjacent to the advertised price, that the price is for frame or mounting only, and does not include lenses, eye examination and professional services, which statement shall appear in type as large as that used for the price, or advertise lenses or complete glasses, viz.: frame or mounting with lenses included, at a price either alone or in conjunction with professional services; or

. To use advertising, whether printed, radio, display, or of any other nature, which inaccurately lays claim to a policy or continuing practice of generally underselling competitors; or

. To use advertising, whether printed, radio, display or of any other nature which refers inaccurately in any material particular to any competitors or their goods, prices, values, credit terms, policies or services; or

. To use advertising whether printed, radio, display, or of any other nature, which states any definite amount of money as "down payment" and any definite amount of money as a subsequent payment, be it daily, weekly, monthly, or at the end of any period of time.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5226-S.SL.pdf?cite=2003%20c%20142%20§%202[2003 c 142 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20138[1991 c 3 § 138]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c36.pdf?cite=1989%20c%2036%20§%202[1989 c 36 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c259.pdf?cite=1986%20c%20259%20§%2082[1986 c 259 § 82]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c58.pdf?cite=1981%20c%2058%20§%203[1981 c 58 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c158.pdf?cite=1979%20c%20158%20§%2047[1979 c 158 § 47]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c69.pdf?cite=1975%201st%20ex.s.%20c%2069%20§%207[1975 1st ex.s. c 69 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c78.pdf?cite=1945%20c%2078%20§%201[1945 c 78 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c134.pdf?cite=1935%20c%20134%20§%201[1935 c 134 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c144.pdf?cite=1919%20c%20144%20§%207[1919 c 144 § 7]; Rem. Supp. 1945 § 10152. Cf.  1909 c 235 § 5; ]

== 18.53.145 - Unlawful advertising of indemnity benefits.
It shall be unlawful for any licensee subject to the provisions of chapter 18.53 RCW to advertise to the effect that benefits in the form of indemnity will accrue to subscribers of health care service contracts for services performed by the licensee for a subscriber when the licensee is neither a health care service contractor nor a participant. A violation of this section shall be punishable as provided in RCW 18.53.140(10).

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c143.pdf?cite=1969%20c%20143%20§%202[1969 c 143 § 2]; ]

== 18.53.150 - Violations generally—Penalty.
Any person violating this chapter is guilty of a misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c259.pdf?cite=1986%20c%20259%20§%2083[1986 c 259 § 83]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c144.pdf?cite=1919%20c%20144%20§%2022[1919 c 144 § 22]; RRS § 10163.  Prior:  1909 c 235 § 12; ]

== 18.53.160 - Public aid ocular services—Discrimination prohibited.
All agencies of the state and its subdivisions, and all commissions, clinics and boards administering relief, public assistance, public welfare assistance, social security, health insurance, or health service under the laws of this state, shall accept the services of licensed optometrists for any service covered by their licenses relating to any person receiving benefits from said agencies or subdivisions and shall pay for such services in the same way as practitioners of other professions may be paid for similar services. None of the said governmental agencies, or agents, officials or employees thereof, including the public schools, in the performance of their duties shall in any way show discrimination among licensed ocular practitioners.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c149.pdf?cite=1949%20c%20149%20§%201[1949 c 149 § 1]; Rem. Supp. 1949 § 9991a; ]

== 18.53.165 - Discrimination prohibited—Legislative finding and declaration.
The legislature finds and declares that the costs of health care to the people are rising disproportionately to other costs and that there is a paramount concern that the right of the people to obtain access to health care in all its facets is being impaired thereby. For this reason, the reliance on the mechanism of insurance, whether profit or nonprofit, is the only effective manner in which the large majority of the people can attain access to quality health care, and it is therefore declared to be in the public interest that health care insurance be regulated to assure that all the people have access to health care rendered by whatever means, and to the greatest extent possible. RCW 18.53.165 through 18.53.190 and 18.53.901, prohibiting discrimination against the legally recognized and licensed profession of optometrists, is necessary in the interest of the public health, welfare and safety.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c48.pdf?cite=1973%20c%2048%20§%201[1973 c 48 § 1]; ]

== 18.53.170 - Discrimination prohibited—Acceptance of services by state agencies and subdivisions.
Notwithstanding any other provision of law, the state and its political subdivisions shall accept the services of licensed optometrists for any service covered by their licenses with relation to any person receiving benefits, salaries, wages, or any other type of compensation from the state, its agencies or subdivisions.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c48.pdf?cite=1973%20c%2048%20§%202[1973 c 48 § 2]; ]

== 18.53.175 - Discrimination prohibited—State agencies and subdivisions—Officials and employees.
The state and its political subdivisions, and all officials, agents, employees, or representatives thereof, are prohibited from in any way discriminating against licensed optometrists in performing and receiving compensation for services covered by their licenses.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c48.pdf?cite=1973%20c%2048%20§%203[1973 c 48 § 3]; ]

== 18.53.180 - Discrimination prohibited—Agreements or contracts by state and subdivisions.
Notwithstanding any other provision of law, the state and its political subdivisions, and all officials, agents, employees, or representatives thereof, are prohibited from entering into any agreement or contract with any individual, group, association, or corporation which in any way, directly or indirectly, discriminates against licensed optometrists in performing and receiving compensation for services covered by their licenses.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c48.pdf?cite=1973%20c%2048%20§%204[1973 c 48 § 4]; ]

== 18.53.185 - Discrimination prohibited—Costs immaterial.
Notwithstanding any other provision of law, for the purpose of RCW 18.53.165 through 18.53.180 and 18.53.190 it is immaterial whether the cost of any policy, plan, agreement, or contract be deemed additional compensation for services, or otherwise.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c48.pdf?cite=1973%20c%2048%20§%205[1973 c 48 § 5]; ]

== 18.53.190 - Discrimination prohibited—Application of law.
RCW 18.53.165 through 18.53.185 shall apply to all agreements, renewals, or contracts issued on or after June 7, 1973.

Health care service contracts having a participant agreement with a majority of the licensed optometrists within its service area may provide benefits to persons or groups of persons through contracts which allow a subscriber to utilize on an equal participation basis the services of any participant provided in the contract, and such contracts shall not be discriminatory.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c69.pdf?cite=1975%201st%20ex.s.%20c%2069%20§%208[1975 1st ex.s. c 69 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c48.pdf?cite=1973%20c%2048%20§%206[1973 c 48 § 6]; ]

== 18.53.200 - Privileged communications.
The information and records of a licensed optometrist pertaining to a patient shall be privileged communications, the same as now or hereafter may exist in the relationship of physician and patient and shall not be released or subjected to disclosure without the consent of the patient or as otherwise required by law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c69.pdf?cite=1975%201st%20ex.s.%20c%2069%20§%2014[1975 1st ex.s. c 69 § 14]; ]

== 18.53.210 - Inactive license status.
The optometry board may adopt rules under this section authorizing an inactive license status.

. An individual licensed under this chapter may place his or her license on inactive status. The holder of an inactive license must not practice optometry in this state without first activating the license.

. The inactive renewal fee must be established by the secretary under RCW 43.70.250. Failure to renew an inactive license shall result in cancellation of the inactive license in the same manner as an active license.

. An inactive license may be placed in an active status upon compliance with rules established by the optometry board.

. Provisions relating to disciplinary action against a person with a license are applicable to a person with an inactive license, except that when disciplinary proceedings against a person with an inactive license have been initiated, the license will remain inactive until the proceedings have been completed.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5535-S.SL.pdf?cite=2006%20c%20232%20§%202[2006 c 232 § 2]; ]

== 18.53.900 - Short title—1919 c 144.
This act shall be known, and may be referred to as, "The Optometry Law".

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c144.pdf?cite=1919%20c%20144%20§%2020[1919 c 144 § 20]; ]

== 18.53.901 - Severability—1973 c 48.
If any provision of this 1973 act, or its application to any person or circumstance is held invalid, the remainder of the act, or the application of the provision to other persons or circumstances is not affected.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c48.pdf?cite=1973%20c%2048%20§%207[1973 c 48 § 7]; ]

== 18.53.920 - Repeal—1919 c 144.
All acts and parts of acts inconsistent with this act are hereby repealed.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c144.pdf?cite=1919%20c%20144%20§%2019[1919 c 144 § 19]; ]

