= 18.96 - Landscape architects.
:toc:

== 18.96.010 - Evidence of qualifications required.
In order to safeguard human health and property, and to promote the public welfare, any person in either public or private capacity practicing or offering to practice landscape architecture for hire shall be required to submit evidence that he or she is qualified so to practice and shall be licensed under the provisions of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5273-S.SL.pdf?cite=2009%20c%20370%20§%202[2009 c 370 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c158.pdf?cite=1969%20ex.s.%20c%20158%20§%201[1969 ex.s. c 158 § 1]; ]

== 18.96.020 - Use of titles, descriptions, and phrases—License or authorization required.
. It is unlawful for any person to practice or offer to practice in this state, landscape architecture, or to use in connection with his or her name or otherwise assume, use, or advertise any title or description including the phrases "landscape architect," "landscape architecture," "landscape architectural," or language tending to imply that he or she is a landscape architect, unless the person is licensed or authorized to practice in the state of Washington under this chapter.

. A person may use the title "intern landscape architect" after graduation from an accredited degree program in landscape architecture and working under the direct supervision of a licensed landscape architect.

. This section does not affect the use of the phrases "landscape architect," "landscape architecture," or "landscape architectural" where a person does not practice or offer to practice landscape architecture.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5273-S.SL.pdf?cite=2009%20c%20370%20§%203[2009 c 370 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c158.pdf?cite=1969%20ex.s.%20c%20158%20§%202[1969 ex.s. c 158 § 2]; ]

== 18.96.030 - Definitions.
The definitions in this section apply throughout this chapter, unless the context clearly requires otherwise.

. "Administration of the construction contract" means the periodic observation of materials and work to observe the general compliance with the construction contract documents, and does not include responsibility for supervising construction methods and processes, site conditions, equipment operations, personnel, or safety on the worksite.

. "Board" means the state board of licensure for landscape architects.

. "Certificate of licensure" means the certificate issued by the director to newly licensed landscape architects.

. "Department" means the department of licensing.

. "Design" means the conceiving, planning, delineation, siting, and arrangement of natural and built features. Where applied to the discussion of structures or utility systems, design does not include the act of engineering such features.

. "Director" means the director of licensing.

. "Engineer" means an individual who is registered as an engineer under chapter 18.43 RCW.

. "Engineering" means the "practice of engineering" as defined in RCW 18.43.020.

. "Landscape architect" means an individual who engages in the practice of landscape architecture.

. "Landscape architecture" means the rendering of professional services in connection with consultations, investigations, reconnaissance, research, planning, design, construction document preparation, construction administration, or teaching supervision in connection with the development of land areas where, and to the extent that, the dominant purpose of such services is the preservation, enhancement, or determination of proper land uses, natural land features, ground cover and planting, naturalistic and aesthetic values, the settings and approaches to structures or other improvements, or natural drainage and erosion control. This practice includes the location, design, and arrangement of such tangible objects as pools, walls, steps, trellises, canopies, and such features as are incidental and necessary to the purposes in this chapter. Landscape architecture involves the design and arrangement of land forms and the development of outdoor space including, but not limited to, the design of public parks, trails, playgrounds, cemeteries, home and school grounds, and the development of industrial and recreational sites.

. "Licensed" means holding a currently valid certificate of licensure issued by the director authorizing the practice of landscape architecture.

. "Person" means any individual, partnership, professional service corporation, corporation, joint stock association, joint venture, or any other entity authorized to do business in the state.

. "Practice of landscape architecture" means the rendering of services where landscape architectural education, training, experience, and the application of mathematical, physical, and social science principles are applied in consultation, evaluation, planning, design including, but not limited to, the preparation and filing of plans, drawings, specifications, and other contract documents, and administration of contracts relative to projects principally directed at the functional and aesthetic use and preservation of land.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5273-S.SL.pdf?cite=2009%20c%20370%20§%204[2009 c 370 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c158.pdf?cite=1979%20c%20158%20§%2073[1979 c 158 § 73]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c158.pdf?cite=1969%20ex.s.%20c%20158%20§%203[1969 ex.s. c 158 § 3]; ]

== 18.96.040 - Licensure board for landscape architects—Members—Qualifications.
. [Empty]
.. There is created a licensure board for landscape architects consisting of five members appointed by the governor.

.. Four members shall be licensed landscape architects who are residents of the state and have at least eight years' experience in the practice of landscape architecture as registered or licensed landscape architects in responsible charge of landscape architectural work or responsible charge of landscape architectural teaching. One member shall be a public member, who is not and has never been a registered or licensed landscape architect and who does not employ and is not employed by or professionally or financially associated with a landscape architect.

.. The term of each newly appointed member shall be six years.

. [Empty]
.. Every member of the board shall receive a certificate of appointment from the governor. On the expiration of the term of each member, the governor shall appoint a successor to serve for a term of six years or until the next successor has been appointed.

.. The governor may remove any member of the board for cause. Vacancies in the board for any reason shall be filled by appointment for the unexpired term.

. The board shall elect a chair, a vice chair, and a secretary. The secretary may delegate his or her authority to the executive director.

. Members of the board shall be compensated in accordance with RCW 43.03.240 and shall be reimbursed for travel expenses in accordance with RCW 43.03.050 and 43.03.060.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20501[2011 c 336 § 501]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5273-S.SL.pdf?cite=2009%20c%20370%20§%205[2009 c 370 § 5]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1643.SL.pdf?cite=1993%20c%2035%20§%201[1993 c 35 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c18.pdf?cite=1985%20c%2018%20§%201[1985 c 18 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c158.pdf?cite=1969%20ex.s.%20c%20158%20§%204[1969 ex.s. c 158 § 4]; ]

== 18.96.060 - Board—Adoption of rules—Executive director.
. The board may adopt such rules under chapter 34.05 RCW as are necessary for the proper performance of its duties under this chapter.

. The director may employ an executive director subject to approval of the board.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5273-S.SL.pdf?cite=2009%20c%20370%20§%206[2009 c 370 § 6]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20234[2002 c 86 § 234]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c158.pdf?cite=1969%20ex.s.%20c%20158%20§%206[1969 ex.s. c 158 § 6]; ]

== 18.96.070 - Qualifications of applicants.
This section establishes the minimum evidence satisfactory to the board that the applicant is qualified for licensure as a professional landscape architect.

. A certificate of licensure shall be granted by the director to all qualified applicants who are certified by the board as having passed the required examination and as having given satisfactory proof of completion of the required education and work experience.

. An applicant for licensure as a landscape architect shall be of a good moral character, at least eighteen years of age, and shall possess one of the following qualifications:

.. Have a professional landscape architectural degree from an institution of higher education accredited by the national landscape architecture accreditation board, or an equivalent degree in landscape architecture as determined by the board, and three years of practical landscape architectural work experience under the supervision of a registered or licensed landscape architect; or

.. Have a high school diploma or equivalent and eight years' practical landscape architectural work experience, which may include landscape design as a principal activity and postsecondary education approved by the board. At least six years of work experience must be under the direct supervision of a registered or licensed landscape architect. An applicant may receive up to two years of practical landscape architectural work experience for postsecondary education courses in landscape architecture, landscape architectural technology, or a related field, including courses in a community or technical college, if the courses are equivalent to education courses in an accredited landscape architectural degree program.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5273-S.SL.pdf?cite=2009%20c%20370%20§%207[2009 c 370 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c158.pdf?cite=1969%20ex.s.%20c%20158%20§%207[1969 ex.s. c 158 § 7]; ]

== 18.96.080 - Applications for licensure and examinations—Fees.
. Application for licensure shall be filed with the board as provided by rule.

. The application for examination shall be filed with the board as prescribed by rule.

. The application and examination fees shall be determined by the director under RCW 43.24.086.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5273-S.SL.pdf?cite=2009%20c%20370%20§%208[2009 c 370 § 8]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1643.SL.pdf?cite=1993%20c%2035%20§%202[1993 c 35 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%2074[1985 c 7 § 74]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c30.pdf?cite=1975%201st%20ex.s.%20c%2030%20§%2085[1975 1st ex.s. c 30 § 85]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c158.pdf?cite=1969%20ex.s.%20c%20158%20§%208[1969 ex.s. c 158 § 8]; ]

== 18.96.090 - Examinations.
. Examinations of landscape architects for certificates of licensure shall be held at least annually at such time and place as the board determines. 

. The board shall determine the content, scope, and grading process of the examination. The board may adopt an appropriate national examination and grading procedure.

. Applicants who fail to pass any section of the examination shall be permitted to retake the parts failed as prescribed by the board. If the entire examination is not successfully completed within five years, a retake of the entire examination is required.

. Applicants for licensure may begin taking the examination upon graduating from an accredited landscape architecture program if the applicant is employed under the supervision of a registered or licensed landscape architect.

. The director shall issue a certificate of licensure to qualified applicants as provided in RCW 18.96.150.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5273-S.SL.pdf?cite=2009%20c%20370%20§%209[2009 c 370 § 9]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1643.SL.pdf?cite=1993%20c%2035%20§%203[1993 c 35 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c18.pdf?cite=1985%20c%2018%20§%202[1985 c 18 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c158.pdf?cite=1969%20ex.s.%20c%20158%20§%209[1969 ex.s. c 158 § 9]; ]

== 18.96.100 - Reciprocity.
. The director may, upon receipt of the current licensure fee, grant a certificate of licensure to an applicant who is a licensed landscape architect in another state or territory of the United States, the District of Columbia, or another country, if that individual's qualifications and experience are determined by the board to be equivalent to the qualifications and experience required of a person licensed under RCW 18.96.070.

. A landscape architect licensed or registered in any other jurisdiction recognized by the board may offer to practice landscape architecture in this state if:

.. It is clearly and prominently stated in any such offer that the landscape architect is not licensed to practice landscape architecture in Washington state; and

.. Before practicing landscape architecture or signing a contract to provide landscape architectural services, the landscape architect obtains a certificate of licensure.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5273-S.SL.pdf?cite=2009%20c%20370%20§%2010[2009 c 370 § 10]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1643.SL.pdf?cite=1993%20c%2035%20§%204[1993 c 35 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%2075[1985 c 7 § 75]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c30.pdf?cite=1975%201st%20ex.s.%20c%2030%20§%2086[1975 1st ex.s. c 30 § 86]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c158.pdf?cite=1969%20ex.s.%20c%20158%20§%2010[1969 ex.s. c 158 § 10]; ]

== 18.96.110 - Renewals.
. The renewal dates and fees for certificates of licensure shall be set by the director in accordance with RCW 43.24.086. Licensees who fail to pay the renewal fee within thirty days of the due date shall pay all delinquent fees plus a penalty fee equal to one-third of the renewal fee. A licensee who fails to pay a renewal fee for a period of five years may be reinstated under such circumstances as the board determines.

. Any licensee in good standing may withdraw from the practice of landscape architecture by giving written notice to the director, and may within five years thereafter resume active practice upon payment of the then-current renewal fee. A licensee may be reinstated after a withdrawal of more than five years under such circumstances as the board determines.

. A licensed landscape architect must demonstrate continuing professional education activities since the landscape architect's last renewal or initial licensure, as the case may be; the board shall by rule describe the professional development activities required by the board. The board may decline to renew a license if the landscape architect's continuing professional education activities do not meet the standards in the board's rules. In the application of this subsection, the board shall strive to ensure that rules are consistent with the continuing professional education requirements in use by the national professional organizations representing landscape architects and in use by other cohort states. Cohort states are those other United States determined by the board to be comparable to Washington in natural factors and landscape architecture licensure.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5273-S.SL.pdf?cite=2009%20c%20370%20§%2011[2009 c 370 § 11]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1643.SL.pdf?cite=1993%20c%2035%20§%205[1993 c 35 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c18.pdf?cite=1985%20c%2018%20§%203[1985 c 18 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%2076[1985 c 7 § 76]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c30.pdf?cite=1975%201st%20ex.s.%20c%2030%20§%2087[1975 1st ex.s. c 30 § 87]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c158.pdf?cite=1969%20ex.s.%20c%20158%20§%2011[1969 ex.s. c 158 § 11]; ]

== 18.96.120 - Unprofessional conduct—Grounds for disciplinary action.
The board may impose any action in RCW 18.235.110 upon the following grounds:

. Offering to pay, paying, or accepting, either directly or indirectly, any substantial gift, bribe, or other consideration to influence the award of professional work;

. Being willfully untruthful or deceptive in any professional report, statement, or testimony;

. Having a financial interest in the bidding for or the performance of a contract to supply labor or materials for or to construct a project for which employed or retained as a landscape architect except with the consent of the client or employer after disclosure of such facts; or allowing an interest in any business to affect a decision regarding landscape architectural work for which retained, employed, or called upon to perform;

. Signing or permitting a seal to be affixed to any drawings or specifications that were not prepared or reviewed by the landscape architect or under the landscape architect's personal supervision by persons subject to the landscape architect's direction and control; or

. Willfully evading or trying to evade any law, ordinance, code, or regulation governing site or landscape construction.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5273-S.SL.pdf?cite=2009%20c%20370%20§%2012[2009 c 370 § 12]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20235[2002 c 86 § 235]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3901.SL.pdf?cite=1997%20c%2058%20§%20827[1997 c 58 § 827]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c158.pdf?cite=1969%20ex.s.%20c%20158%20§%2012[1969 ex.s. c 158 § 12]; ]

== 18.96.140 - Reissuance of lost or destroyed certificates.
A new certificate of licensure to replace any certificate lost or destroyed, or mutilated may be issued by the director, and a charge determined by the director as provided in RCW 43.24.086 shall be made for such issuance.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5273-S.SL.pdf?cite=2009%20c%20370%20§%2013[2009 c 370 § 13]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20236[2002 c 86 § 236]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%2077[1985 c 7 § 77]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c30.pdf?cite=1975%201st%20ex.s.%20c%2030%20§%2088[1975 1st ex.s. c 30 § 88]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c158.pdf?cite=1969%20ex.s.%20c%20158%20§%2014[1969 ex.s. c 158 § 14]; ]

== 18.96.150 - Certificates of licensure—Issuance—Contents—Seal.
. The director shall issue a certificate of licensure to any applicant who has, to the satisfaction of the board, met all the requirements for licensure upon payment of the licensure fee as provided in this chapter. All certificates of licensure shall show the full name of the licensee, have the license number, and shall be signed by the chair of the board and by the director. The issuance of a certificate of licensure by the director is prima facie evidence that the person named therein is entitled to all the rights and privileges of a licensed landscape architect.

. Each licensee shall obtain a seal of the design authorized by the board bearing the landscape architect's name, license number, the legend "Licensed Landscape Architect," and the name of this state. Drawings prepared by the licensee shall be sealed and signed by the licensee when filed with public authorities. It is unlawful to seal and sign a document after a licensee's certificate of licensure or authorization has expired, been revoked, or is suspended. A landscape architect shall not seal and sign technical submissions not prepared by the landscape architect or his or her regularly employed subordinates or individuals under his or her direct control, or if prepared by a landscape architect licensed in any jurisdiction recognized by the board, reviewed and accepted as the sealing landscape architect's own work; a landscape architect who signs or seals drawings or specifications that he or she has reviewed is responsible to the same extent as if prepared by that landscape architect.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5273-S.SL.pdf?cite=2009%20c%20370%20§%2014[2009 c 370 § 14]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1643.SL.pdf?cite=1993%20c%2035%20§%206[1993 c 35 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c158.pdf?cite=1969%20ex.s.%20c%20158%20§%2015[1969 ex.s. c 158 § 15]; ]

== 18.96.180 - Certificate of licensure suspension—Noncompliance with support order—Reissuance.
The board, through the director, shall immediately suspend the certificate of licensure to practice landscape architecture of a person who has been certified under RCW 74.20A.320 by the department of social and health services as a person who is not in compliance with a support order or a *residential or visitation order. If the person has continued to meet other requirements for reinstatement during the suspension, reissuance of the certificate shall be automatic upon the director's receipt of a release issued by the department of social and health services stating that the individual is in compliance with the order.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5273-S.SL.pdf?cite=2009%20c%20370%20§%2015[2009 c 370 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c158.pdf?cite=1969%20ex.s.%20c%20158%20§%2018[1969 ex.s. c 158 § 18]; ]

== 18.96.200 - Uniform regulation of business and professions act.
The uniform regulation of business and professions act, chapter 18.235 RCW, governs unlicensed practice, the issuance and denial of licenses, and the discipline of licensees under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20237[2002 c 86 § 237]; ]

== 18.96.210 - Landscape architects' license account.
The landscape architects' license account is created in the custody of the state treasurer. All receipts from fees under this chapter must be deposited into the account. Expenditures from the account may be used only for administrative and operating purposes under this chapter. Only the director or the director's designees may authorize expenditures from the account. The account is subject to allotment procedures under chapter 43.88 RCW, but an appropriation is not required for expenditures.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5273-S.SL.pdf?cite=2009%20c%20370%20§%2017[2009 c 370 § 17]; ]

== 18.96.220 - Application—Professions and activities not affected.
This chapter does not affect or prevent:

. The practice of architecture, land surveying, engineering, geology, or any recognized profession by persons not licensed as landscape architects;

. Drafters, clerks, project managers, superintendents, and other employees of landscape architects from acting under the instructions, control, or supervision of their employers;

. The construction, alteration, or supervision of sites by contractors or superintendents employed by contractors or the preparation of shop drawings in connection therewith;

. Owners or contractors under chapter 18.27 RCW from engaging persons who are not landscape architects to observe and supervise site construction of a project;

. Qualified professional biologists as referenced in chapter 36.70 RCW from providing services for natural site areas that also fall within the definition of the practice of landscape architecture without a violation of this chapter;

. The preparation of construction documents including planting plans, landscape materials, or other horticulture-related elements;

. Individuals from making plans, drawings, or specifications for any property owned by them and for their own personal use;

. The design of irrigation systems; and

. Landscape design on residential properties.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5273-S.SL.pdf?cite=2009%20c%20370%20§%2018[2009 c 370 § 18]; ]

== 18.96.230 - Military training or experience.
An applicant with military training or experience satisfies the training or experience requirements of this chapter unless the board determines that the military training or experience is not substantially equivalent to the standards of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1418.SL.pdf?cite=2011%20c%20351%20§%207[2011 c 351 § 7]; ]

== 18.96.901 - Construction—Chapter applicable to state registered domestic partnerships—2009 c 521.
For the purposes of this chapter, the terms spouse, marriage, marital, husband, wife, widow, widower, next of kin, and family shall be interpreted as applying equally to state registered domestic partnerships or individuals in state registered domestic partnerships as well as to marital relationships and married persons, and references to dissolution of marriage shall apply equally to state registered domestic partnerships that have been terminated, dissolved, or invalidated, to the extent that such interpretation does not conflict with federal law. Where necessary to implement chapter 521, Laws of 2009, gender-specific terms such as husband and wife used in any statute, rule, or other law shall be construed to be gender neutral, and applicable to individuals in state registered domestic partnerships.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%2048[2009 c 521 § 48]; ]

