= 18.73 - Emergency medical care and transportation services.
:toc:

== 18.73.010 - Legislative finding.
The legislature finds that a statewide program of emergency medical care is necessary to promote the health, safety, and welfare of the citizens of this state. The intent of the legislature is to assure minimum standards and training for first responders and emergency medical technicians, and minimum standards for ambulance services, ambulances, aid vehicles, aid services, and emergency medical equipment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c269.pdf?cite=1990%20c%20269%20§%2022[1990 c 269 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c104.pdf?cite=1988%20c%20104%20§%202[1988 c 104 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c214.pdf?cite=1987%20c%20214%20§%201[1987 c 214 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c208.pdf?cite=1973%201st%20ex.s.%20c%20208%20§%201[1973 1st ex.s. c 208 § 1]; ]

== 18.73.020 - Supersession of local regulation.
The legislature further declares its intention to supersede all ordinances, regulations, and requirements promulgated by counties, cities and other political subdivisions of the state of Washington, insofar as they may provide for the regulation of emergency medical care, first aid, and ambulance services which do not exceed the provisions of this chapter; except that (1) license fees established in this chapter shall supersede all license fees of counties, cities and other political subdivisions of this state; and, (2) nothing in this chapter shall alter the provisions of RCW 18.71.200, 18.71.210, and 18.71.220.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c259.pdf?cite=1986%20c%20259%20§%20118[1986 c 259 § 118]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c208.pdf?cite=1973%201st%20ex.s.%20c%20208%20§%202[1973 1st ex.s. c 208 § 2]; ]

== 18.73.030 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Advanced life support" means invasive emergency medical services requiring advanced medical treatment skills as defined by chapter 18.71 RCW.

. "Aid service" means an organization that operates one or more aid vehicles.

. "Aid vehicle" means a vehicle used to carry aid equipment and individuals trained in first aid or emergency medical procedure.

. "Ambulance" means a ground or air vehicle designed and used to transport the ill and injured and to provide personnel, facilities, and equipment to treat patients before and during transportation.

. "Ambulance service" means an organization that operates one or more ambulances.

. "Basic life support" means noninvasive emergency medical services requiring basic medical treatment skills as defined in this chapter.

. "Communications system" means a radio and landline network which provides rapid public access, coordinated central dispatching of services, and coordination of personnel, equipment, and facilities in an emergency medical services and trauma care system.

. "Council" means the local or regional emergency medical services and trauma care council as authorized under chapter 70.168 RCW.

. "Department" means the department of health.

. "Emergency medical service" means medical treatment and care which may be rendered at the scene of any medical emergency or while transporting any patient in an ambulance to an appropriate medical facility, including ambulance transportation between medical facilities.

. "Emergency medical services medical program director" means a person who is an approved medical program director as defined by RCW 18.71.205(4).

. "Emergency medical technician" means a person who is authorized by the secretary to render emergency medical care pursuant to RCW 18.73.081 or, under the responsible supervision and direction of an approved medical program director, to participate in an emergency services supervisory organization or a community assistance referral and education services program established under RCW 35.21.930 if the participation does not exceed the participant's training and certification.

. "Emergency services supervisory organization" means an entity that is authorized by the secretary to use certified emergency medical services personnel to provide medical evaluation or initial treatment, or both, to sick or injured people, while in the course of duties with the organization for on-site medical care prior to any necessary activation of emergency medical services. Emergency services supervisory organizations include law enforcement agencies, disaster management organizations, search and rescue operations, diversion centers, and businesses with organized industrial safety teams.

. "First responder" means a person who is authorized by the secretary to render emergency medical care as defined by RCW 18.73.081.

. "Patient care procedures" means written operating guidelines adopted by the regional emergency medical services and trauma care council, in consultation with the local emergency medical services and trauma care councils, emergency communication centers, and the emergency medical services medical program director, in accordance with statewide minimum standards. The patient care procedures shall identify the level of medical care personnel to be dispatched to an emergency scene, procedures for triage of patients, the level of trauma care facility to first receive the patient, and the name and location of other trauma care facilities to receive the patient should an interfacility transfer be necessary. Procedures on interfacility transfer of patients shall be consistent with the transfer procedures in chapter 70.170 RCW.

. "Prehospital patient care protocols" means the written procedure adopted by the emergency medical services medical program director which direct the out-of-hospital emergency care of the emergency patient which includes the trauma care patient. These procedures shall be based upon the assessment of the patient's medical needs and what treatment will be provided for emergency conditions. The protocols shall meet or exceed statewide minimum standards developed by the department in rule as authorized in chapter 70.168 RCW.

. "Secretary" means the secretary of the department of health.

. "Stretcher" means a cart designed to serve as a litter for the transportation of a patient in a prone or supine position as is commonly used in the ambulance industry, such as wheeled stretchers, portable stretchers, stair chairs, solid backboards, scoop stretchers, basket stretchers, or flexible stretchers. The term does not include personal mobility aids that recline at an angle or remain at a flat position, that are owned or leased for a period of at least one week by the individual using the equipment or the individual's guardian or representative, such as wheelchairs, personal gurneys, or banana carts.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1276-S.SL.pdf?cite=2021%20c%2069%20§%201[2021 c 69 § 1]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5591-S.SL.pdf?cite=2015%20c%2093%20§%205[2015 c 93 § 5]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2617-S2.SL.pdf?cite=2010%201st%20sp.s.%20c%207%20§%2025[2010 1st sp.s. c 7 § 25]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1237.SL.pdf?cite=2005%20c%20193%20§%202[2005 c 193 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2452.SL.pdf?cite=2000%20c%2093%20§%2016[2000 c 93 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c269.pdf?cite=1990%20c%20269%20§%2023[1990 c 269 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c104.pdf?cite=1988%20c%20104%20§%203[1988 c 104 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c214.pdf?cite=1987%20c%20214%20§%202[1987 c 214 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c112.pdf?cite=1983%20c%20112%20§%205[1983 c 112 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c261.pdf?cite=1979%20ex.s.%20c%20261%20§%201[1979 ex.s. c 261 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c208.pdf?cite=1973%201st%20ex.s.%20c%20208%20§%203[1973 1st ex.s. c 208 § 3]; ]

== 18.73.081 - Duties of secretary—Minimum requirements to be prescribed.
In addition to other duties prescribed by law, the secretary shall:

. Prescribe minimum requirements for:

.. Ambulance, air ambulance, and aid vehicles and equipment; 

.. Ambulance and aid services; and

.. Minimum emergency communication equipment;

. Adopt procedures for services that fail to perform in accordance with minimum requirements;

. Prescribe minimum standards for first responder and emergency medical technician training including:

.. Adoption of curriculum and period of certification;

.. Procedures for certification, recertification, decertification, or modification of certificates;

.. Adoption of requirements for ongoing training and evaluation, as approved by the county medical program director, to include appropriate evaluation for individual knowledge and skills. The first responder, emergency medical technician, or emergency medical services provider agency may elect a program of continuing education and a written and practical examination instead of meeting the ongoing training and evaluation requirements;

.. Procedures for reciprocity with other states or national certifying agencies;

.. Review and approval or disapproval of training programs; and

.. Adoption of standards for numbers and qualifications of instructional personnel required for first responder and emergency medical technician training programs;

. Prescribe minimum requirements for liability insurance to be carried by licensed services except that this requirement shall not apply to public bodies; and

. Certify emergency medical program directors.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1541-S.SL.pdf?cite=1993%20c%20254%20§%201[1993 c 254 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c269.pdf?cite=1990%20c%20269%20§%2024[1990 c 269 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c111.pdf?cite=1988%20c%20111%20§%201[1988 c 111 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c214.pdf?cite=1987%20c%20214%20§%207[1987 c 214 § 7]; ]

== 18.73.101 - Variance from requirements.
The secretary may grant a variance from a provision of this chapter and RCW 18.71.200 through 18.71.220 if no detriment to health and safety would result from the variance and compliance is expected to cause reduction or loss of existing emergency medical services. Variances may be granted for a period of no more than one year. A variance may be renewed by the secretary.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2617-S2.SL.pdf?cite=2010%201st%20sp.s.%20c%207%20§%2026[2010 1st sp.s. c 7 § 26]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2452.SL.pdf?cite=2000%20c%2093%20§%2017[2000 c 93 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c214.pdf?cite=1987%20c%20214%20§%209[1987 c 214 § 9]; ]

== 18.73.120 - Certificate of advanced first aid qualification.
The secretary shall recognize a current certificate of advanced first aid qualification for those who provide proof of advanced Red Cross training or its equivalent.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c261.pdf?cite=1979%20ex.s.%20c%20261%20§%2012[1979 ex.s. c 261 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c208.pdf?cite=1973%201st%20ex.s.%20c%20208%20§%2012[1973 1st ex.s. c 208 § 12]; ]

== 18.73.130 - Ambulance services and aid services—Licensing.
An ambulance service or aid service may not operate in the state of Washington without holding a license for such operation, issued by the secretary when such operation is consistent with the statewide and regional emergency medical services and trauma care plans established pursuant to chapter 70.168 RCW, indicating the general area to be served and the number of vehicles to be used, with the following exceptions:

. The United States government;

. Ambulance services providing service in other states when bringing patients into this state;

. Owners of businesses in which ambulance or aid vehicles are used exclusively on company property but occasionally in emergencies may transport patients to hospitals not on company property;

. Operators of vehicles pressed into service for transportation of patients in emergencies when licensed ambulances are not available or cannot meet overwhelming demand; and

. Emergency services supervisory organizations, as defined in RCW 18.73.030(13). All entities that employ certified emergency medical services personnel must ensure that such personnel work under the medical oversight and protocols of a medical program director and within their scope of practice, are able to meet certification training requirements, and are provided with necessary medical equipment to provide care at their level of certification.

The license shall be valid for a period of two years and shall be renewed on request provided the holder has consistently complied with the regulations of the department and the department of licensing and provided also that the needs of the area served have been met satisfactorily. The license shall not be transferable and may be revoked if the service is found in violation of rules adopted by the department.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1276-S.SL.pdf?cite=2021%20c%2069%20§%202[2021 c 69 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2452.SL.pdf?cite=2000%20c%2093%20§%2018[2000 c 93 § 18]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6033.SL.pdf?cite=1992%20c%20128%20§%202[1992 c 128 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c269.pdf?cite=1990%20c%20269%20§%2025[1990 c 269 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c214.pdf?cite=1987%20c%20214%20§%2010[1987 c 214 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c261.pdf?cite=1979%20ex.s.%20c%20261%20§%2013[1979 ex.s. c 261 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c158.pdf?cite=1979%20c%20158%20§%2061[1979 c 158 § 61]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c208.pdf?cite=1973%201st%20ex.s.%20c%20208%20§%2013[1973 1st ex.s. c 208 § 13]; ]

== 18.73.140 - Ambulance and aid vehicles—Licenses.
The secretary shall issue an ambulance or aid vehicle license for each vehicle so designated. The license shall be for a period of two years and may be reissued on expiration if the vehicle and its equipment meet requirements in force at the time of expiration of the license period. The license may be revoked if the ambulance or aid vehicle is found to be operating in violation of the regulations promulgated by the department or without required equipment. The license shall be terminated automatically if the vehicle is sold or transferred to the control of any organization not currently licensed as an ambulance or aid vehicle service. The license number shall be prominently displayed on each vehicle.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2452.SL.pdf?cite=2000%20c%2093%20§%2019[2000 c 93 § 19]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6033.SL.pdf?cite=1992%20c%20128%20§%203[1992 c 128 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c214.pdf?cite=1987%20c%20214%20§%2011[1987 c 214 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c261.pdf?cite=1979%20ex.s.%20c%20261%20§%2014[1979 ex.s. c 261 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c208.pdf?cite=1973%201st%20ex.s.%20c%20208%20§%2014[1973 1st ex.s. c 208 § 14]; ]

== 18.73.145 - Ambulance and aid vehicles—Self-inspection program.
The secretary shall adopt a self-inspection program to assure compliance with minimum standards for vehicles and for medical equipment and personnel on all licensed vehicles. The self-inspection shall coincide with the vehicle licensing cycle and shall be recorded on forms provided by the department. The department may perform an on-site inspection of any licensed service or vehicles as needed.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c214.pdf?cite=1987%20c%20214%20§%2013[1987 c 214 § 13]; ]

== 18.73.150 - Ambulance personnel requirements.
. [Empty]
.. Any ambulance operated as such shall operate with sufficient personnel for adequate patient care, at least one of whom shall be an emergency medical technician under standards promulgated by the secretary. The emergency medical technician shall have responsibility for its operation and for the care of patients both before they are placed aboard the vehicle and during transit. If there are two or more emergency medical technicians operating the ambulance, a nondriving medical technician shall be in command of the vehicle. The emergency medical technician in command of the vehicle shall be in the patient compartment and in attendance to the patient.

.. Except as provided in subsection (2) of this section, the driver of the ambulance shall have at least a certificate of advance first aid qualification recognized by the secretary pursuant to RCW 18.73.120 unless there are at least two certified emergency medical technicians in attendance of the patient, in which case the driver shall not be required to have such certificate.

. With approval from the department, an ambulance service established by volunteer or municipal corporations, or by an association made up entirely of two or more municipalities, in a rural area with insufficient personnel may use a driver without any medical or first aid training so long as the driver is at least eighteen years old, successfully passes a background check issued or approved by the department, possesses a valid driver's license with no restrictions, is accompanied by a nondriving emergency medical technician while operating the ambulance during a response or transport of a patient, and only provides medical care to patients to the level that they are trained.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5198.SL.pdf?cite=2021%20c%2017%20§%201[2021 c 17 § 1]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5751-S.SL.pdf?cite=2017%20c%2070%20§%201[2017 c 70 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6033.SL.pdf?cite=1992%20c%20128%20§%204[1992 c 128 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c261.pdf?cite=1979%20ex.s.%20c%20261%20§%2015[1979 ex.s. c 261 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c208.pdf?cite=1973%201st%20ex.s.%20c%20208%20§%2015[1973 1st ex.s. c 208 § 15]; ]

== 18.73.155 - Requirements—Military training or experience.
An applicant with military training or experience satisfies the training or experience requirements of this chapter unless the secretary determines that the military training or experience is not substantially equivalent to the standards of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5307-S.SL.pdf?cite=2011%20c%2032%20§%207[2011 c 32 § 7]; ]

== 18.73.170 - Aid vehicles—Personnel—Use.
The aid vehicle shall be operated in accordance with standards promulgated by the secretary, by at least one person holding a certificate recognized under RCW 18.73.120.

The aid vehicle may be used for transportation of patients only when it is impossible or impractical to obtain an ambulance or when a wait for arrival of an ambulance would place the life of the patient in jeopardy. If so used, the vehicle shall be under the command of a person holding a certificate recognized pursuant to RCW 18.73.081 other than the driver.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c214.pdf?cite=1987%20c%20214%20§%2012[1987 c 214 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c261.pdf?cite=1979%20ex.s.%20c%20261%20§%2017[1979 ex.s. c 261 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c208.pdf?cite=1973%201st%20ex.s.%20c%20208%20§%2017[1973 1st ex.s. c 208 § 17]; ]

== 18.73.180 - Other transportation vehicles.
Other vehicles not herein defined by this chapter shall not be used for transportation of patients who must be carried on a stretcher or who may require medical attention en route, except that such transportation may be used when:

. A disaster creates a situation that cannot be served by licensed ambulances; or

. The use of a stretcher is necessary because an individual's personal mobility aid cannot be adequately secured in the nonambulance vehicle and the individual has written authorization from his or her physician that it is safe to transfer the individual from a personal mobility aid to a stretcher.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1837-S.SL.pdf?cite=2007%20c%20305%20§%201[2007 c 305 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c214.pdf?cite=1987%20c%20214%20§%2014[1987 c 214 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c261.pdf?cite=1979%20ex.s.%20c%20261%20§%2018[1979 ex.s. c 261 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c208.pdf?cite=1973%201st%20ex.s.%20c%20208%20§%2018[1973 1st ex.s. c 208 § 18]; ]

== 18.73.190 - Violations—Penalties.
Any person who violates any of the provisions of this chapter and for which a penalty is not provided shall be deemed guilty of a misdemeanor and upon conviction thereof, shall be fined in any sum not exceeding one hundred dollars for each day of the violation, or may be imprisoned in the county jail not exceeding six months.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c214.pdf?cite=1987%20c%20214%20§%2015[1987 c 214 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c208.pdf?cite=1973%201st%20ex.s.%20c%20208%20§%2019[1973 1st ex.s. c 208 § 19]; ]

== 18.73.200 - Administrative procedure act applicable.
The administrative procedure act, chapter 34.05 RCW, shall wherever applicable govern the rights, remedies, and procedures respecting the administration of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c208.pdf?cite=1973%201st%20ex.s.%20c%20208%20§%2021[1973 1st ex.s. c 208 § 21]; ]

== 18.73.240 - Application of uniform disciplinary act.
The uniform disciplinary act, chapter 18.130 RCW, shall govern the issuance and denial of credentials, unauthorized practice, and the discipline of persons credentialed under this chapter. The secretary shall act as the disciplinary authority under this chapter. Disciplinary action shall be initiated against a person credentialed under this chapter in a manner consistent with the responsibilities and duties of the medical program director under whom such person is responsible.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6033.SL.pdf?cite=1992%20c%20128%20§%205[1992 c 128 § 5]; ]

== 18.73.250 - Epinephrine—Availability—Administration.
. All of the state's ambulance and aid services shall make epinephrine available to their emergency medical technicians in their emergency care supplies. The emergency medical technician may administer epinephrine.

. Nothing in this section authorizes the administration of epinephrine by a first responder.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5708-S.SL.pdf?cite=2005%20c%20463%20§%201[2005 c 463 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1317.SL.pdf?cite=2001%20c%2024%20§%201[2001 c 24 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1992-S.SL.pdf?cite=1999%20c%20337%20§%204[1999 c 337 § 4]; ]

== 18.73.260 - Guidelines.
. The department of health shall convene a stakeholder group including the department of social and health services, the department of transportation, and local special needs transportation providers who shall assist in the development of guidelines for the safe transport of individuals who rely on stretchers and personal mobility devices.

. The department of health shall prepare guidelines for the public and vehicle operators relating to:

.. Appropriate situations in which vehicles other than ambulances may be used to transport individuals who rely upon personal mobility aids in the normal course of their lives; and

.. Methods for properly securing personal mobility aids on vehicles other than ambulances and determining if they are adequately secured.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1837-S.SL.pdf?cite=2007%20c%20305%20§%202[2007 c 305 § 2]; ]

== 18.73.270 - Disclosure of information by emergency medical personnel—Violent injuries—Immunity.
. Except when treatment is provided in a hospital licensed under chapter 70.41 RCW, a *physician's trained emergency medical service intermediate life support technician and paramedic, emergency medical technician, or first responder who renders treatment to a patient for (a) a bullet wound, gunshot wound, powder burn, or other injury arising from or caused by the discharge of a firearm; (b) an injury caused by a knife, an ice pick, or any other sharp or pointed instrument which federal, state, or local law enforcement authorities reasonably believe to have been intentionally inflicted upon a person; (c) a blunt force injury that federal, state, or local law enforcement authorities reasonably believe resulted from a criminal act; or (d) injuries sustained in an automobile collision, shall disclose without the patient's authorization, upon a request from a federal, state, or local law enforcement authority as defined in **RCW 70.02.010(3), the following information, if known:

... The name of the patient;

... The patient's residence;

... The patient's sex;

... The patient's age;

.. The patient's condition or extent and location of injuries as determined by the *physician's trained emergency medical service intermediate life support technician and paramedic, emergency medical technician, or first responder;

.. Whether the patient was conscious when contacted;

.. Whether the patient appears to have consumed alcohol or appears to be under the influence of alcohol or drugs;

.. The name or names of the *physician's trained emergency medical service intermediate life support technician and paramedic, emergency medical technician, or first responder who provided treatment to the patient; and

... The name of the facility to which the patient is being transported for additional treatment.

. A *physician's trained emergency medical service intermediate life support technician and paramedic, emergency medical technician, first responder, or other individual who discloses information pursuant to this section is immune from civil or criminal liability or professional licensure action for the disclosure, provided that the *physician's trained emergency medical service intermediate life support technician and paramedic, emergency medical technician, first responder, or other individual acted in good faith and without gross negligence or willful or wanton misconduct.

. The obligation to provide information pursuant to this section is secondary to patient care needs. Information must be provided as soon as reasonably possible taking into consideration a patient's emergency care needs.

. For purposes of this section, "a *physician's trained emergency medical service intermediate life support technician and paramedic" has the same meaning as in RCW 18.71.200.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5056-S.SL.pdf?cite=2009%20c%20359%20§%201[2009 c 359 § 1]; ]

== 18.73.280 - Ambulance service—Transport of patients to a nonmedical facility.
An ambulance service may transport patients to a nonmedical facility, such as a mental health facility or chemical dependency program as authorized in regional emergency medical services and trauma care plans under RCW 70.168.100.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1721-S.SL.pdf?cite=2015%20c%20157%20§%204[2015 c 157 § 4]; ]

== 18.73.910 - Effective dates—1973 1st ex.s. c 208.
The provisions of sections 1 through 8, inclusive, 11, 12, 20, 21, 22, and 23 of this 1973 act shall take effect on July 1, 1973. The provisions of sections 9, 10, and 13 through 19, inclusive, shall take effect on January 1, 1976.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c208.pdf?cite=1973%201st%20ex.s.%20c%20208%20§%2022[1973 1st ex.s. c 208 § 22]; ]

