= 18.110 - Art dealers—Artists.
:toc:

== 18.110.010 - Definitions.
As used in this chapter, the following terms have the meanings indicated unless the context clearly requires otherwise.

. "Art dealer" means a person, partnership, firm, association, or corporation, other than a public auctioneer, which undertakes to sell a work of fine art created by another.

. "Artist" means the creator of a work of fine art.

. "On consignment" means delivered to an art dealer for the purpose of sale or exhibition, or both, to the public by the art dealer other than at a public auction.

. "Work of fine art" means an original art work which is:

.. A visual rendition including a painting, drawing, sculpture, mosaic, or photograph;

.. A work of calligraphy;

.. A work of graphic art including an etching, lithograph, offset print, or silk screen;

.. A craft work in materials including clay, textile, fiber, wood, metal, plastic, or glass; or

.. A work in mixed media including a collage or a work consisting of any combination of works included in this subsection.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c33.pdf?cite=1981%20c%2033%20§%201[1981 c 33 § 1]; ]

== 18.110.020 - Rights—Duties—Liabilities.
If an art dealer accepts a work of fine art on a fee, commission, or other compensation basis, on consignment from the artist:

. The art dealer is, with respect to that work of fine art, the agent of the artist.

. The work of fine art is trust property and the art dealer is trustee for the benefit of the artist until the work of fine art is sold to a bona fide third party.

. The proceeds of the sale of the work of fine art are trust property and the art dealer is trustee for the benefit of the artist until the amount due the artist from the sale is paid. These trust funds shall be paid to the artist within thirty days of receipt by the art dealer unless the parties expressly agree otherwise in writing. If the sale of the work of fine art is on installment, the funds from the installment shall first be applied to pay any balance due the artist on the sale, unless the artist expressly agrees in writing that the proceeds on each installment shall be paid according to a percentage established by the consignment agreement.

. The art dealer is strictly liable for the loss of or damage to the work of fine art while it is in the art dealer's possession. For the purpose of this subsection the value of the work of fine art is the value established in a written agreement between the artist and art dealer prior to the loss or damage or, if no written agreement regarding the value of the work of fine art exists, the fair market value of the work of fine art.

A work of fine art which is trust property when initially accepted by the art dealer remains trust property notwithstanding the subsequent purchase of the work of fine art by the art dealer directly or indirectly for the art dealer's own account until the purchase price is paid in full to the artist. No property which is trust property under this section is subject to the claims, liens, or security interests of the creditors of the art dealer.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c33.pdf?cite=1981%20c%2033%20§%202[1981 c 33 § 2]; ]

== 18.110.030 - Contract required—Provisions.
. An art dealer may accept a work of fine art on a fee, commission, or other compensation basis, on consignment from the artist only if prior to or at the time of acceptance the art dealer enters into a written contract with the artist which states:

.. The value of the work of fine art;

.. The minimum price for the sale of the work of fine art; and

.. The fee, commission, or other compensation basis of the art dealer.

. An art dealer who accepts a work of fine art on a fee, commission, or other compensation basis, on consignment from the artist may use or display the work of fine art or a photograph of the work of fine art or permit the use or display of the work or photograph only if:

.. Notice is given to users or viewers that the work of fine art is the work of the artist; and

.. The artist gives prior written consent to the particular use or display.

. Any portion of a contract which waives any provision of this chapter is void.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c33.pdf?cite=1981%20c%2033%20§%203[1981 c 33 § 3]; ]

== 18.110.040 - Violations—Penalties—Attorney fees.
An art dealer violating RCW 18.110.030 is liable to the artist for fifty dollars plus actual damages, including incidental and consequential damages, sustained as a result of the violation. If an art dealer violates RCW 18.110.030, the artist's obligation for compensation to the art dealer is voidable. In an action under this section the court may, in its discretion, award the artist reasonable attorney's fees.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c33.pdf?cite=1981%20c%2033%20§%204[1981 c 33 § 4]; ]

== 18.110.900 - Application of chapter.
This chapter applies to any work of fine art accepted on consignment on or after July 26, 1981. If a work of fine art is accepted on consignment on or after July 26, 1981 under a contract made before that date, this section applies only to the extent that it does not conflict with the contract.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c33.pdf?cite=1981%20c%2033%20§%205[1981 c 33 § 5]; ]

