= 18.118 - Regulation of business professions.
:toc:

== 18.118.005 - Legislative findings—Intent.
The legislature recognizes the value of an analytical review, removed from the political process, of proposals for increased regulation of real estate and other business professions which the legislature already regulates, as well as of proposals for regulation of professions not currently regulated. The legislature further finds that policies and standards set out for regulation of the health professions in chapter 18.120 RCW have equal applicability to other professions. To further the goal of governmental regulation only as necessary to protect the public interest and to promote economic development through employment, the legislature expands the scope of chapter 18.120 RCW to apply to business professions. The legislature intends that the reviews of proposed business profession regulation be conducted by the department of licensing's policy and research rather than regulatory staff and that the reviews be conducted and recommendations made in an impartial manner. Further, the legislature intends that the department of licensing provide sufficient staffing to conduct the reviews.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c514.pdf?cite=1987%20c%20514%20§%203[1987 c 514 § 3]; ]

== 18.118.010 - Purpose—Intent.
. The purpose of this chapter is to establish guidelines for the regulation of the real estate profession and other business professions which may seek legislation to substantially increase their scope of practice or the level of regulation of the profession, and for the regulation of business professions not licensed or regulated on July 26, 1987: PROVIDED, That the provisions of this chapter are not intended and shall not be construed to: (a) Apply to any regulatory entity created prior to July 26, 1987, except as provided in this chapter; (b) affect the powers and responsibilities of the superintendent of public instruction or Washington professional educator standards board under RCW 28A.410.210 and 28A.410.010; (c) apply to or interfere in any way with the practice of religion or to any kind of treatment by prayer; (d) apply to any remedial or technical amendments to any statutes which licensed or regulated activity before July 26, 1987; and (e) apply to proposals relating solely to continuing education. The legislature believes that all individuals should be permitted to enter into a business profession unless there is an overwhelming need for the state to protect the interests of the public by restricting entry into the profession. Where such a need is identified, the regulation adopted by the state should be set at the least restrictive level consistent with the public interest to be protected.

. It is the intent of this chapter that no regulation shall be imposed upon any business profession except for the exclusive purpose of protecting the public interest. All bills introduced in the legislature to regulate a business profession for the first time should be reviewed according to the following criteria. A business profession should be regulated by the state only when:

.. Unregulated practice can clearly harm or endanger the health, safety, or welfare of the public, and the potential for the harm is easily recognizable and not remote or dependent upon tenuous argument;

.. The public needs and can reasonably be expected to benefit from an assurance of initial and continuing professional ability; and

.. The public cannot be effectively protected by other means in a more cost-beneficial manner.

. After evaluating the criteria in subsection (2) of this section and considering governmental and societal costs and benefits, if the legislature finds that it is necessary to regulate a business profession not previously regulated by law, the least restrictive alternative method of regulation should be implemented, consistent with the public interest and this section:

.. Where existing common law and statutory civil actions and criminal prohibitions are not sufficient to eradicate existing harm, the regulation should provide for stricter civil actions and criminal prosecutions;

.. Where a service is being performed for individuals involving a hazard to the public health, safety, or welfare, the regulation should impose inspection requirements and enable an appropriate state agency to enforce violations by injunctive relief in court, including, but not limited to, regulation of the business activity providing the service rather than the employees of the business;

.. Where the threat to the public health, safety, or economic well-being is relatively small as a result of the operation of the business profession, the regulation should implement a system of registration;

.. Where the consumer may have a substantial basis for relying on the services of a practitioner, the regulation should implement a system of certification; or

.. Where apparent that adequate regulation cannot be achieved by means other than licensing, the regulation should implement a system of licensing.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5732-S.SL.pdf?cite=2005%20c%20497%20§%20218[2005 c 497 § 218]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20553[1990 c 33 § 553]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c514.pdf?cite=1987%20c%20514%20§%204[1987 c 514 § 4]; ]

== 18.118.020 - Definitions.
The definitions contained in this section shall apply throughout this chapter unless the context clearly requires otherwise.

. "Applicant group" includes any business professional group or organization, any individual, or any other interested party which proposes that any business professional group not presently regulated be regulated or which proposes legislation to substantially increase the scope of practice or the level of regulation of the profession.

. "Business professions" means those business occupations or professions which are not health professions under chapter 18.120 RCW and includes, in addition to real estate brokers and salespersons under chapter 18.85 RCW, the following professions and occupations: Accountancy under chapter 18.04 RCW; architects under chapter 18.08 RCW; auctioneering under chapter 18.11 RCW; cosmetologists, barbers, and manicurists under chapter 18.16 RCW; contractors under chapter 18.27 RCW; debt adjusting under chapter 18.28 RCW; engineers and surveyors under chapter 18.43 RCW; escrow agents under chapter 18.44 RCW; landscape architects under chapter 18.96 RCW; water well construction under chapter 18.104 RCW; plumbers under chapter 18.106 RCW; and art dealers under chapter 18.110 RCW.

. "Certificate" and "certification" mean a voluntary process by which a statutory regulatory entity grants recognition to an individual who (a) has met certain prerequisite qualifications specified by that regulatory entity, and (b) may assume or use "certified" in the title or designation to perform prescribed professional tasks.

. "Grandfather clause" means a provision in a regulatory statute applicable to practitioners actively engaged in the regulated profession prior to the effective date of the regulatory statute which exempts the practitioners from meeting the prerequisite qualifications set forth in the regulatory statute to perform prescribed occupational tasks.

. "Inspection" means the periodic examination of practitioners by a state agency in order to ascertain whether the practitioners' occupation is being carried out in a fashion consistent with the public health, safety, and welfare.

. "Legislative committees of reference" means the standing legislative committees designated by the respective rules committees of the senate and house of representatives to consider proposed legislation to regulate business professions not previously regulated.

. "License", "licensing", and "licensure" mean permission to engage in a business profession which would otherwise be unlawful in the state in the absence of the permission. A license is granted to those individuals who meet prerequisite qualifications to perform prescribed professional tasks and for the use of a particular title.

. "Professional license" means an individual, nontransferable authorization to carry on an activity based on qualifications which include: (a) Graduation from an accredited or approved program, and (b) acceptable performance on a qualifying examination or series of examinations.

. "Practitioner" means an individual who (a) has achieved knowledge and skill by practice, and (b) is actively engaged in a specified business profession.

. "Public member" means an individual who is not, and never was, a member of the business profession being regulated or the spouse of a member, or an individual who does not have and never has had a material financial interest in either the rendering of the business professional service being regulated or an activity directly related to the profession being regulated.

. "Registration" means the formal notification which, prior to rendering services, a practitioner shall submit to a state agency setting forth the name and address of the practitioner; the location, nature and operation of the business activity to be practiced; and, if required by the regulatory entity, a description of the service to be provided.

. "Regulatory entity" means any board, commission, agency, division, or other unit or subunit of state government which regulates one or more professions, occupations, industries, businesses, or other endeavors in this state.

. "State agency" includes every state office, department, board, commission, regulatory entity, and agency of the state, and, where provided by law, programs and activities involving less than the full responsibility of a state agency.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c514.pdf?cite=1987%20c%20514%20§%205[1987 c 514 § 5]; ]

== 18.118.030 - Applicants for regulation—Information.
After July 26, 1987, if appropriate, applicant groups shall explain each of the following factors to the extent requested by the legislative committees of reference:

. A definition of the problem and why regulation is necessary:

.. The nature of the potential harm to the public if the business profession is not regulated, and the extent to which there is a threat to public health and safety;

.. The extent to which consumers need and will benefit from a method of regulation identifying competent practitioners, indicating typical employers, if any, of practitioners in the profession; and

.. The extent of autonomy a practitioner has, as indicated by:

... The extent to which the profession calls for independent judgment and the extent of skill or experience required in making the independent judgment; and

... The extent to which practitioners are supervised;

. The efforts made to address the problem:

.. Voluntary efforts, if any, by members of the profession to:

... Establish a code of ethics; or

... Help resolve disputes between practitioners and consumers; and

.. Recourse to and the extent of use of applicable law and whether it could be strengthened to control the problem;

. The alternatives considered:

.. Regulation of business employers or practitioners rather than employee practitioners;

.. Regulation of the program or service rather than the individual practitioners;

.. Registration of all practitioners;

.. Certification of all practitioners;

.. Other alternatives;

.. Why the use of the alternatives specified in this subsection would not be adequate to protect the public interest; and

.. Why licensing would serve to protect the public interest;

. The benefit to the public if regulation is granted:

.. The extent to which the incidence of specific problems present in the unregulated profession can reasonably be expected to be reduced by regulation;

.. Whether the public can identify qualified practitioners;

.. The extent to which the public can be confident that qualified practitioners are competent:

... Whether the proposed regulatory entity would be a board composed of members of the profession and public members, or a state agency, or both, and, if appropriate, their respective responsibilities in administering the system of registration, certification, or licensure, including the composition of the board and the number of public members, if any; the powers and duties of the board or state agency regarding examinations and for cause revocation, suspension, and nonrenewal of registrations, certificates, or licenses; the promulgation of rules and canons of ethics; the conduct of inspections; the receipt of complaints and disciplinary action taken against practitioners; and how fees would be levied and collected to cover the expenses of administering and operating the regulatory system;

... If there is a grandfather clause, whether such practitioners will be required to meet the prerequisite qualifications established by the regulatory entity at a later date;

... The nature of the standards proposed for registration, certification, or licensure as compared with the standards of other jurisdictions;

... Whether the regulatory entity would be authorized to enter into reciprocity agreements with other jurisdictions; and

.. The nature and duration of any training including, but not limited to, whether the training includes a substantial amount of supervised field experience; whether training programs exist in this state; if there will be an experience requirement; whether the experience must be acquired under a registered, certificated, or licensed practitioner; whether there are alternative routes of entry or methods of meeting the prerequisite qualifications; whether all applicants will be required to pass an examination; and, if an examination is required, by whom it will be developed and how the costs of development will be met;

.. Assurance of the public that practitioners have maintained their competence:

... Whether the registration, certification, or licensure will carry an expiration date; and

... Whether renewal will be based only upon payment of a fee, or whether renewal will involve reexamination, peer review, or other enforcement;

. The extent to which regulation might harm the public:

.. The extent to which regulation will restrict entry into the profession:

... Whether the proposed standards are more restrictive than necessary to insure safe and effective performance; and

... Whether the proposed legislation requires registered, certificated, or licensed practitioners in other jurisdictions who migrate to this state to qualify in the same manner as state applicants for registration, certification, and licensure when the other jurisdiction has substantially equivalent requirements for registration, certification, or licensure as those in this state; and

.. Whether there are similar professions to that of the applicant group which should be included in, or portions of the applicant group which should be excluded from, the proposed legislation;

. The maintenance of standards:

.. Whether effective quality assurance standards exist in the profession, such as legal requirements associated with specific programs that define or enforce standards, or a code of ethics; and

.. How the proposed legislation will assure quality:

... The extent to which a code of ethics, if any, will be adopted; and

... The grounds for suspension or revocation of registration, certification, or licensure;

. A description of the group proposed for regulation, including a list of associations, organizations, and other groups representing the practitioners in this state, an estimate of the number of practitioners in each group, and whether the groups represent different levels of practice; and

. The expected costs of regulation:

.. The impact registration, certification, or licensure will have on the costs of the services to the public; and

.. The cost to the state and to the general public of implementing the proposed legislation.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c514.pdf?cite=1987%20c%20514%20§%206[1987 c 514 § 6]; ]

== 18.118.040 - Applicants for regulation—Written report—Recommendation of department of licensing.
Applicant groups shall submit a written report explaining the factors enumerated in RCW 18.118.030 to the legislative committees of reference. Applicant groups, other than state agencies created prior to July 26, 1987, shall submit copies of their written report to the department of licensing for review and comment. The department of licensing shall make recommendations based on the report to the extent requested by the legislative committees.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c514.pdf?cite=1987%20c%20514%20§%207[1987 c 514 § 7]; ]

== 18.118.901 - Construction—Chapter applicable to state registered domestic partnerships—2009 c 521.
For the purposes of this chapter, the terms spouse, marriage, marital, husband, wife, widow, widower, next of kin, and family shall be interpreted as applying equally to state registered domestic partnerships or individuals in state registered domestic partnerships as well as to marital relationships and married persons, and references to dissolution of marriage shall apply equally to state registered domestic partnerships that have been terminated, dissolved, or invalidated, to the extent that such interpretation does not conflict with federal law. Where necessary to implement chapter 521, Laws of 2009, gender-specific terms such as husband and wife used in any statute, rule, or other law shall be construed to be gender neutral, and applicable to individuals in state registered domestic partnerships.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%2049[2009 c 521 § 49]; ]

