= 18.185 - Bail bond agents.
:toc:

== 18.185.005 - Declaration, intent, construction.
The legislature declares that the licensing of bail bond agents should be uniform throughout the state. Therefore, it is the intent of the legislature to preempt any local regulation of bail bond agents, including licensing fees, but not including local business license fees. Nothing in this chapter limits the discretion of the courts of this state to accept or reject a particular surety or recognizance bond in a particular case.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1870-S.SL.pdf?cite=1993%20c%20260%20§%201[1993 c 260 § 1]; ]

== 18.185.010 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Department" means the department of licensing.

. "Director" means the director of licensing.

. "Commission" means the criminal justice training commission.

. "Collateral or security" means property of any kind given as security to obtain a bail bond.

. "Bail bond agency" means a business that sells and issues corporate surety bail bonds or that provides security in the form of personal or real property to ensure the appearance of a criminal defendant before the courts of this state or the United States.

. "Qualified agent" means an owner, sole proprietor, partner, manager, officer, or chief operating officer of a corporation who meets the requirements set forth in this chapter for obtaining a bail bond agency license.

. "Bail bond agent" means a person who is employed by a bail bond agency and engages in the sale or issuance of bail bonds, but does not mean a clerical, secretarial, or other support person who does not participate in the sale or issuance of bail bonds.

. "Licensee" means a bail bond agency, a bail bond agent, a qualified agent, or a bail bond recovery agent.

. "Branch office" means any office physically separated from the principal place of business of the licensee from which the licensee or an employee or agent of the licensee conducts any activity meeting the criteria of a bail bond agency.

. "Bail bond recovery agent" means a person who is under contract with a bail bond agent to receive compensation, reward, or any other form of lawful consideration for locating, apprehending, and surrendering a fugitive criminal defendant for whom a bail bond has been posted. "Bail bond recovery agent" does not include a general authority Washington peace officer or a limited authority Washington peace officer.

. "Contract" means a written agreement between a bail bond agent or qualified agent and a bail bond recovery agent for the purpose of locating, apprehending, and surrendering a fugitive criminal defendant in exchange for lawful consideration.

. "Planned forced entry" means a premeditated forcible entry into a dwelling, building, or other structure without the occupant's knowledge or consent for the purpose of apprehending a fugitive criminal defendant subject to a bail bond. "Planned forced entry" does not include situations where, during an imminent or actual chase or pursuit of a fleeing fugitive criminal defendant, or during a casual or unintended encounter with the fugitive, the bail bond recovery agent forcibly enters into a dwelling, building, or other structure without advanced planning.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2313-S.SL.pdf?cite=2004%20c%20186%20§%202[2004 c 186 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2400.SL.pdf?cite=2000%20c%20171%20§%2040[2000 c 171 § 40]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6544.SL.pdf?cite=1996%20c%20242%20§%201[1996 c 242 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1870-S.SL.pdf?cite=1993%20c%20260%20§%202[1993 c 260 § 2]; ]

== 18.185.015 - Cost of administration—Fees.
Pursuant to RCW 43.24.086 and 43.135.055, the department may increase fees as necessary to defray the cost of administering *chapter 105, Laws of 2008 (Engrossed Substitute Senate Bill No. 6347).

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3381.SL.pdf?cite=2008%20c%20285%20§%2029[2008 c 285 § 29]; ]

== 18.185.020 - Agent license requirements.
An applicant must meet the following minimum requirements to obtain a bail bond agent license:

. Be at least eighteen years of age;

. Be a citizen or resident alien of the United States;

. Not have been convicted of a crime in any jurisdiction in the preceding ten years, if the director determines that the applicant's particular crime directly relates to a capacity to perform the duties of a bail bond agent and the director determines that the license should be withheld to protect the citizens of Washington state. If the director shall make a determination to withhold a license because of previous convictions, the determination shall be consistent with the restoration of employment rights act, chapter 9.96A RCW;

. Be employed by a bail bond agency or be licensed as a bail bond agency; and

. Pay the required fee.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1870-S.SL.pdf?cite=1993%20c%20260%20§%203[1993 c 260 § 3]; ]

== 18.185.030 - Agency license requirements.
. In addition to meeting the minimum requirements to obtain a license as a bail bond agent, a qualified agent must meet the following additional requirements to obtain a bail bond agency license:

.. Pass an examination determined by the director to measure the person's knowledge and competence in the bail bond agency business; or

.. Have had at least three years' experience as a manager, supervisor, or administrator in the bail bond business or a related field in Washington state as determined by the director. A year's experience means not less than two thousand hours of actual compensated work performed before the filing of an application. An applicant shall substantiate the experience by written certifications from previous employers. If the applicant is unable to supply written certifications from previous employers, applicants may offer written certifications from persons other than employers who, based on personal knowledge, can substantiate the employment; and

.. Pay any additional fees as established by the director.

. An agency license issued under this section may not be assigned or transferred without prior written approval of the director.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6437-S.SL.pdf?cite=2008%20c%20105%20§%201[2008 c 105 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1870-S.SL.pdf?cite=1993%20c%20260%20§%204[1993 c 260 § 4]; ]

== 18.185.040 - License applications.
. Applications for licenses required under this chapter shall be filed with the director on a form provided by the director. The director may require any information and documentation that reasonably relates to the need to determine whether the applicant meets the criteria, including fingerprints.

. Applicants for licensure or endorsement as a bail bond recovery agent must complete a records check through the Washington state patrol criminal identification system and through the federal bureau of investigation at the applicant's expense. Such record check shall include a fingerprint check using a Washington state patrol approved fingerprint card. The Washington state patrol shall forward the fingerprints of applicants to the federal bureau of investigation for a national criminal history records check. The director may accept proof of a recent national crime information center/III criminal background report or any national or interstate criminal background report in addition to fingerprints to accelerate the licensing and endorsement process. The director is authorized to periodically perform a background investigation of licensees to identify criminal convictions subsequent to the renewal of a license or endorsement.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2313-S.SL.pdf?cite=2004%20c%20186%20§%204[2004 c 186 § 4]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1870-S.SL.pdf?cite=1993%20c%20260%20§%205[1993 c 260 § 5]; ]

== 18.185.050 - License cards, certificates—Advertising—Notice of changes.
. The director shall issue a bail bond agent license card to each licensed bail bond agent. A bail bond agent shall carry the license card whenever he or she is performing the duties of a bail bond agent and shall exhibit the card upon request.

. The director shall issue a license certificate to each licensed bail bond agency.

.. Within seventy-two hours after receipt of the license certificate, the licensee shall post and display the certificate in a conspicuous place in the principal office of the licensee within the state.

.. It is unlawful for any person holding a license certificate to knowingly and willfully post the license certificate upon premises other than those described in the license certificate or to materially alter a license certificate.

.. Every advertisement by a licensee that solicits or advertises business shall contain the name of the licensee, the address of record, and the license number as they appear in the records of the director.

.. The licensee shall notify the director within thirty days of any change in the licensee's officers or directors or any material change in the information furnished or required to be furnished to the director.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1870-S.SL.pdf?cite=1993%20c%20260%20§%206[1993 c 260 § 6]; ]

== 18.185.056 - License suspension—Electronic benefit cards.
The director shall immediately suspend any license issued under this chapter if the director receives information that the license holder has not complied with RCW 74.08.580(2). If the license holder has otherwise remained eligible to be licensed, the director may reinstate the suspended license when the holder has complied with RCW 74.08.580(2).

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5921-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2042%20§%2018[2011 1st sp.s. c 42 § 18]; ]

== 18.185.057 - License suspension—Noncompliance with support order—Reissuance.
The director shall immediately suspend any license issued under this chapter if the holder has been certified pursuant to RCW 74.20A.320 by the department of social and health services as a person who is not in compliance with a support order or a *residential or visitation order. If the person has continued to meet all other requirements for reinstatement during the suspension, reissuance of the license shall be automatic upon the director's receipt of a release issued by the department of social and health services stating that the person is in compliance with the order.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3901.SL.pdf?cite=1997%20c%2058%20§%20840[1997 c 58 § 840]; ]

== 18.185.060 - Prelicensing training and continuing education requirements.
. The director shall adopt rules establishing prelicense training and testing requirements for bail bond agents, which shall include no less than four hours of classes. The director may establish, by rule, continuing education requirements for bail bond agents.

. The director or the director's designee, with the advice of law enforcement agencies and associations, the criminal justice training commission, prosecutors' associations, or such other entities as may be appropriate, shall consult with representatives of the bail bond industry and associations before adopting or amending the prelicensing training or continuing education requirements of this section.

. The director may appoint an advisory committee consisting of representatives from the bail bond industry and a consumer to assist in the development of rules to implement and administer this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6437-S.SL.pdf?cite=2008%20c%20105%20§%202[2008 c 105 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1870-S.SL.pdf?cite=1993%20c%20260%20§%207[1993 c 260 § 7]; ]

== 18.185.070 - Bond.
. No bail bond agency license may be issued under the provisions of this chapter unless the qualified agent files with the director a bond, executed by a surety company authorized to do business in this state, in the sum of ten thousand dollars conditioned to recover against the agency and its servants, officers, agents, and employees by reason of its violation of the provisions of RCW 18.185.100. The bond shall be made payable to the state of Washington, and anyone so injured by the agency or its servants, officers, agents, or employees may bring suit upon the bond in any county in which jurisdiction over the licensee may be obtained. The suit must be brought not later than two years after the failure to return property in accordance with RCW 18.185.100. If valid claims against the bond exceed the amount of the bond or deposit, each claimant shall be entitled only to a pro rata amount, based on the amount of the claim as it is valid against the bond, without regard to the date of filing of any claim or action.

. Every licensed bail bond agency must at all times maintain on file with the director the bond required by this section in full force and effect. Upon failure by a licensee to do so, the director shall suspend the licensee's license and shall not reinstate the license until this requirement is met.

. In lieu of posting a bond, a qualified agent may deposit in an interest-bearing account, ten thousand dollars.

. The director may waive the bond requirements of this section, in his or her discretion, pursuant to adopted rules.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1870-S.SL.pdf?cite=1993%20c%20260%20§%208[1993 c 260 § 8]; ]

== 18.185.080 - Relation of this chapter to local regulation, taxation.
. The provisions of this chapter relating to the licensing for regulatory purposes of bail bond agents and bail bond agencies are exclusive. No governmental subdivision of this state may enact any laws or rules licensing for regulatory purposes such persons, except as provided in subsections (2) and (3) of this section.

. This section shall not be construed to prevent a political subdivision of this state from levying a business fee, business and occupation tax, or other tax upon bail bond agencies if such fees or taxes are levied by the political subdivision on other types of businesses within its boundaries.

. This section shall not be construed to prevent this state or a political subdivision of this state from licensing for regulatory purposes bail bond agencies with respect to activities that are not regulated under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1870-S.SL.pdf?cite=1993%20c%20260%20§%209[1993 c 260 § 9]; ]

== 18.185.090 - Notice concerning agent's status—Forced entry—Discharge of firearm.
. A bail bond agency shall notify the director within thirty days after the death or termination of employment of any employee who is a licensed bail bond agent.

. A bail bond agency shall notify the director within seventy-two hours upon receipt of information affecting a licensed bail bond agent's continuing eligibility to hold a license under the provisions of this chapter.

. A bail bond agent or bail bond recovery agent shall notify the director within seventy-two hours upon receipt of information affecting the bail bond recovery agent's continuing eligibility to hold a bail bond recovery agent's license under the provisions of this chapter.

. A bail bond recovery agent shall notify the director within ten business days following a forced entry for the purpose of apprehending a fugitive criminal defendant, whether planned or unplanned. The notification under this subsection must include information required by rule of the director.

. A bail bond recovery agent shall notify the local law enforcement agency whenever the bail bond recovery agent discharges his or her firearm while on duty, other than on a supervised firearms range. The notification must be made within ten business days of the date the firearm is discharged.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6437-S.SL.pdf?cite=2008%20c%20105%20§%203[2008 c 105 § 3]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2313-S.SL.pdf?cite=2004%20c%20186%20§%207[2004 c 186 § 7]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1870-S.SL.pdf?cite=1993%20c%20260%20§%2010[1993 c 260 § 10]; ]

== 18.185.100 - Records—Finances—Disposition of security.
. Every qualified agent shall keep adequate records for three years of all collateral and security received, all trust accounts required by this section, and all bail bond transactions handled by the bail bond agency, as specified by rule. The records shall be open to inspection without notice by the director or authorized representatives of the director.

. Every qualified agent who receives collateral or security is a fiduciary of the property and shall keep adequate records for three years of the receipt, safekeeping, and disposition of the collateral or security. Every qualified agent shall maintain a trust account in a federally insured financial institution located in this state. All moneys, including cash, checks, money orders, wire transfers, and credit card sales drafts, received as collateral or security or otherwise held for a bail bond agency's client shall be deposited in the trust account not later than the third banking day following receipt of the funds or money. A qualified agent shall not in any way encumber the corpus of the trust account or commingle any other moneys with moneys properly maintained in the trust account. Each qualified agent required to maintain a trust account shall report annually under oath to the director the account number and balance of the trust account, and the name and address of the institution that holds the trust account, and shall report to the director within ten business days whenever the trust account is changed or relocated or a new trust account is opened.

. Whenever a bail bond is exonerated by the court, the qualified agent shall, within five business days after written notification of exoneration, return all collateral or security to the person entitled thereto.

. Records of contracts for fugitive apprehension must be retained by the bail bond agent and by the bail bond recovery agent for a period of three years.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2313-S.SL.pdf?cite=2004%20c%20186%20§%208[2004 c 186 § 8]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6544.SL.pdf?cite=1996%20c%20242%20§%203[1996 c 242 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1870-S.SL.pdf?cite=1993%20c%20260%20§%2011[1993 c 260 § 11]; ]

== 18.185.110 - Unprofessional conduct.
In addition to the unprofessional conduct described in RCW 18.235.130, the following conduct, acts, or conditions constitute unprofessional conduct:

. Violating any of the provisions of this chapter or the rules adopted under this chapter;

. Failing to meet the qualifications set forth in RCW 18.185.020, 18.185.030, and 18.185.250;

. Knowingly committing, or being a party to, any material fraud, misrepresentation, concealment, conspiracy, collusion, trick, scheme, or device whereby any other person lawfully relies upon the word, representation, or conduct of the licensee. However, this subsection (3) does not prevent a bail bond recovery agent from using any pretext to locate or apprehend a fugitive criminal defendant or gain any information regarding the fugitive;

. Assigning or transferring any license issued pursuant to the provisions of this chapter, except as provided in RCW 18.185.030 or 18.185.250;

. Conversion of any money or contract, deed, note, mortgage, or other evidence of title, to his or her own use or to the use of his or her principal or of any other person, when delivered to him or her in trust or on condition, in violation of the trust or before the happening of the condition; and failure to return any money or contract, deed, note, mortgage, or other evidence of title within thirty days after the owner is entitled to possession, and makes demand for possession, shall be prima facie evidence of conversion;

. Failing to keep records, maintain a trust account, or return collateral or security, as required by RCW 18.185.100;

. Any conduct in a bail bond transaction which demonstrates bad faith, dishonesty, or untrustworthiness; 

. Violation of an order to cease and desist that is issued by the director under chapter 18.235 RCW;

. Wearing, displaying, holding, or using badges not approved by the department;

. Making any statement that would reasonably cause another person to believe that the bail bond recovery agent is a sworn peace officer;

. Failing to carry a copy of the contract or to present a copy of the contract as required under RCW 18.185.270(1);

. Using the services of an unlicensed bail bond recovery agent or using the services of a bail bond recovery agent without issuing the proper contract;

. Misrepresenting or knowingly making a material misstatement or omission in the application for a license;

. Using the services of a person performing the functions of a bail bond recovery agent who has not been licensed by the department as required by this chapter; 

. Performing the functions of a bail bond recovery agent without being both (a) licensed under this chapter or supervised by a licensed bail bond recovery agent under RCW 18.185.290; and (b) under contract with a bail bond agent;

. Performing the functions of a bail bond recovery agent without exercising due care to protect the safety of persons other than the defendant and the property of persons other than the defendant; or

. Using a dog in the apprehension of a fugitive criminal defendant.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6437-S.SL.pdf?cite=2008%20c%20105%20§%204[2008 c 105 § 4]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1574-S.SL.pdf?cite=2007%20c%20256%20§%202[2007 c 256 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2313-S.SL.pdf?cite=2004%20c%20186%20§%209[2004 c 186 § 9]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20251[2002 c 86 § 251]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1870-S.SL.pdf?cite=1993%20c%20260%20§%2012[1993 c 260 § 12]; ]

== 18.185.115 - Unprofessional conduct—Certain contracts—General power of attorney—Presumption.
Entering into a contract, including a general power of attorney, that gives a bail bond agent full authority over a person's finances, assets, real property, or personal property creates a presumption of unprofessional conduct that may be overcome by a preponderance of the evidence presented to the department to the contrary. The department has the discretion to determine whether or not the bail bond agency or agent has overcome the presumption and if unprofessional conduct was committed.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1022.SL.pdf?cite=2016%20c%2073%20§%201[2016 c 73 § 1]; ]

== 18.185.120 - Director's powers.
In addition to those powers set forth in RCW 18.235.030, the director or the director's designee has the authority to order restitution to the person harmed by the licensee.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1574-S.SL.pdf?cite=2007%20c%20256%20§%203[2007 c 256 § 3]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20252[2002 c 86 § 252]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1870-S.SL.pdf?cite=1993%20c%20260%20§%2013[1993 c 260 § 13]; ]

== 18.185.130 - Complaints.
Any person may submit a written complaint to the department charging a license holder or applicant with unprofessional conduct and specifying the grounds for the charge. If the director determines that the complaint merits investigation, or if the director has reason to believe, without a formal complaint, that a license holder or applicant may have engaged in unprofessional conduct, the director shall investigate to determine if there has been unprofessional conduct. A person who files a complaint under this section in good faith is immune from suit in any civil action related to the filing or contents of the complaint.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1870-S.SL.pdf?cite=1993%20c%20260%20§%2014[1993 c 260 § 14]; ]

== 18.185.140 - Statement of charges—Notice.
When a statement of charges is issued against a license holder or applicant under RCW 18.235.050, notice of this action must be given to the owner or qualified agent of the employing bail bond agency.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20253[2002 c 86 § 253]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1870-S.SL.pdf?cite=1993%20c%20260%20§%2015[1993 c 260 § 15]; ]

== 18.185.170 - Unlicensed activity—Criminal penalties.
. Any person who performs the functions and duties of a bail bond agent in this state without being licensed in accordance with the provisions of this chapter, or any person presenting or attempting to use as his or her own the license of another, or any person who gives false or forged evidence of any kind to the director in obtaining a license, or any person who falsely impersonates any other licensee, or any person who attempts to use an expired or revoked license, or any person who violates any of the provisions of this chapter is guilty of a gross misdemeanor.

. A person is guilty of a gross misdemeanor if the person owns or operates a bail bond agency in this state without first obtaining a bail bond agency license.

. The owner or qualified agent of a bail bond agency is guilty of a gross misdemeanor if the owner or qualified agent employs any person to perform the duties of a bail bond agent without the employee having in the employee's possession a permanent bail bond agent license issued by the department.

. After December 31, 2005, a person is guilty of a gross misdemeanor if the person:

.. Performs the functions of a bail bond recovery agent without first obtaining a license from the department and entering into a contract with a bail bond agent as required by this chapter; or, in the case of a bail bond recovery agent from another state, the person performs the functions of a bail bond recovery agent without operating under the direct supervision of a licensed bail bond recovery agent as required by this chapter; or

.. Conducts a planned forced entry without first complying with the requirements of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2313-S.SL.pdf?cite=2004%20c%20186%20§%2013[2004 c 186 § 13]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20254[2002 c 86 § 254]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1870-S.SL.pdf?cite=1993%20c%20260%20§%2018[1993 c 260 § 18]; ]

== 18.185.200 - Application of Administrative Procedure Act.
The director, in implementing and administering the provisions of this chapter, shall act in accordance with the Administrative Procedure Act, chapter 34.05 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1870-S.SL.pdf?cite=1993%20c%20260%20§%2021[1993 c 260 § 21]; ]

== 18.185.210 - Application of Consumer Protection Act.
Failure to fulfill the fiduciary duties and other duties as prescribed in RCW 18.185.100 is not reasonable in relation to the development and preservation of business. A violation of RCW 18.185.100 is an unfair or deceptive act in trade or commerce for the purpose of applying the Consumer Protection Act, chapter 19.86 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1870-S.SL.pdf?cite=1993%20c%20260%20§%2022[1993 c 260 § 22]; ]

== 18.185.220 - Branch office—Qualified bail bond agent as manager.
A branch office may not operate under a business name other than the name of the principal bail bond agency and must have a qualified bail bond agent as manager of the office. The qualified agent shall comply with the provisions of RCW 18.185.100.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6544.SL.pdf?cite=1996%20c%20242%20§%202[1996 c 242 § 2]; ]

== 18.185.230 - License required for branch office.
If a licensee maintains a branch office, the licensee shall not operate that branch office until a branch office license has been received from the director. A bail bond agency may apply to the director for authority to establish one or more branch offices under the same name as the main office upon the payment of a fee as prescribed by the director by rule. The director shall issue a separate license for each branch office showing the location of each branch which shall be prominently displayed in the office for which it is issued. A corporation, partnership, or sole proprietorship shall not establish more than one principal office within this state.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6544.SL.pdf?cite=1996%20c%20242%20§%204[1996 c 242 § 4]; ]

== 18.185.240 - Uniform regulation of business and professions act.
The uniform regulation of business and professions act, chapter 18.235 RCW, governs unlicensed practice, the issuance and denial of licenses, and the discipline of licensees under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20255[2002 c 86 § 255]; ]

== 18.185.250 - Bail bond recovery agent license—Requirements.
An applicant must meet the following requirements to obtain a bail bond recovery agent license:

. Submit a fully completed application that includes proper identification on a form prescribed by the director;

. Pass an examination determined by the director to measure his or her knowledge and competence in the bail recovery business;

. Be at least twenty-one years old;

. Be a citizen or legal resident alien of the United States;

. Not have been convicted of a crime in any jurisdiction, if the director determines that the applicant's particular crime directly relates to a capacity to perform the duties of a bail bond recovery agent, and that the license should be withheld to protect the citizens of Washington state. The director shall make the director's determination to withhold a license because of previous convictions notwithstanding the restoration of employment rights act, chapter 9.96A RCW;

. Not have had certification as a peace officer revoked or denied under chapter 43.101 RCW, unless certification has subsequently been reinstated under RCW 43.101.115;

. Submit a receipt showing payment for a background check through the Washington state patrol and the federal bureau of investigation;

. Have a current firearms certificate issued by the commission if carrying a firearm in the performance of his or her duties as a bail bond recovery agent;

. [Empty]
.. Have a current license or equivalent permit to carry a concealed pistol;

.. A resident alien must provide a copy of his or her alien firearm license; and

. [Empty]
.. Pay the required nonrefundable fee for each application for a bail bond recovery agent license;

.. A bail bond agent or qualified agent who wishes to perform the duties of a bail bond recovery agent must first obtain a bail bond recovery agent endorsement to his or her bail bond agent or agency license in order to act as a bail bond recovery agent, and pay the required nonrefundable fee for each application for a bail bond recovery agent endorsement.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6437-S.SL.pdf?cite=2008%20c%20105%20§%205[2008 c 105 § 5]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2313-S.SL.pdf?cite=2004%20c%20186%20§%203[2004 c 186 § 3]; ]

== 18.185.260 - Bail bond recovery agents—Prelicense training/testing requirements—Continuing education requirements—Rules.
. The director shall adopt rules establishing prelicense training and testing requirements for bail bond recovery agents, which shall include no less than thirty-two hours of field operations classes. The director may establish, by rule, continuing education and recertification requirements for bail bond recovery agents.

. The director or the director's designee, with the advice of law enforcement agencies and associations, the criminal justice training commission, prosecutors' associations, or such other entities as may be appropriate, shall consult with representatives of the bail bond industry and associations before adopting or amending the prelicensing training, testing, and continuing education and recertification requirements of this section and shall establish minimum exam standards necessary for a bail bond recovery agent to qualify for licensure or endorsement.

. The standards must include, but are not limited to, the following:

.. A minimum level of education or experience appropriate for performing the duties of a bail bond recovery agent;

.. A minimum level of knowledge in relevant areas of criminal and civil law;

.. A minimum level of knowledge regarding the appropriate use of force and different degrees of the use of force; and

.. Adequate training of the use of firearms from the criminal justice training commission, from an instructor who has been trained or certified by the criminal justice training commission, or from another entity approved by the director.

. The legislature does not intend, and nothing in this chapter shall be construed to restrict or limit in any way the powers of bail bond agents as recognized in and derived from the United States supreme court case of Taylor v. Taintor, 16 Wall. 366 (1872).

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6437-S.SL.pdf?cite=2008%20c%20105%20§%206[2008 c 105 § 6]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2313-S.SL.pdf?cite=2004%20c%20186%20§%205[2004 c 186 § 5]; ]

== 18.185.270 - Bail bond agent/bail bond recovery agent—Each fugitive an individual contract—Format of contract.
. Each fugitive criminal defendant to be recovered will be treated as an individual contract between the bail bond agent and the bail bond recovery agent. A bail bond agent shall provide a bail bond recovery agent a copy of each individual contract. A bail bond recovery agent must carry, in addition to the license issued by the department, a copy of the contract and, if requested, must present a copy of the contract and the license to the fugitive criminal defendant, the owner or manager of the property in which the agent entered in order to locate or apprehend the fugitive, other residents, if any, of the residence in which the agent entered in order to locate or apprehend the fugitive, and to the local law enforcement agency or officer. If presenting a copy of the contract or the license at the time of the request would unduly interfere with the location or apprehension of the fugitive, the agent shall present the copy of the contract or the license within a reasonable period of time after the exigent circumstances expire.

. The director, or the director's designee, with the advice of the bail bond industry and associations, law enforcement agencies and associations, and prosecutors' associations shall develop a format for the contract. At a minimum, the contract must include the following:

.. The name, address, phone number, and license number of the bail bond agency or bail bond agent contracting with the bail bond recovery agent;

.. The name and license number of the bail bond recovery agent; and

.. The name, last known address, and phone number of the fugitive.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2313-S.SL.pdf?cite=2004%20c%20186%20§%206[2004 c 186 § 6]; ]

== 18.185.280 - Bail bond recovery agent, generally.
. A person may not perform the functions of a bail bond recovery agent unless the person is licensed by the department under this chapter.

. A bail bond agent may contract with a person to perform the functions of a bail bond recovery agent. Before contracting with the bail bond recovery agent, the bail bond agent must check the license issued by the department under this chapter. The requirements established by the department under this chapter do not prevent the bail bond agent from imposing additional requirements that the bail bond agent considers appropriate.

. A contract entered into under this chapter is authority for the person to perform the functions of a bail bond recovery agent as specifically authorized by the contract and in accordance with applicable law. A contract entered into by a bail bond agent with a bail bond recovery agent is not transferable by the bail bond recovery agent to another bail bond recovery agent.

. Whenever a person licensed by the department as a bail bond recovery agent is engaged in the performance of the person's duties as a bail bond recovery agent, the person must carry a copy of the license.

. A license or endorsement issued by the department under this chapter is valid from the date the license or endorsement is issued until its expiration date unless it is suspended or revoked by the department prior to its expiration date.

. Nothing in this chapter is meant to prevent a bail bond agent from contacting a fugitive criminal defendant for the purpose of requesting the surrender of the fugitive, or from accepting the voluntary surrender of the fugitive.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6437-S.SL.pdf?cite=2008%20c%20105%20§%207[2008 c 105 § 7]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2313-S.SL.pdf?cite=2004%20c%20186%20§%2010[2004 c 186 § 10]; ]

== 18.185.290 - Out-of-state bail bond recovery agent.
A bail bond recovery agent from another state who is not licensed under this chapter may not perform the functions of a bail bond recovery agent in this state unless the agent is working under the direct supervision of a licensed bail bond recovery agent.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2313-S.SL.pdf?cite=2004%20c%20186%20§%2011[2004 c 186 § 11]; ]

== 18.185.300 - Bail bond recovery agent—Planned forced entry—Requirements.
. Before a bail bond recovery agent may apprehend a person subject to a bail bond in a planned forced entry, the bail bond recovery agent must:

.. Have reasonable cause to believe that the defendant is inside the dwelling, building, or other structure where the planned forced entry is expected to occur; and

.. Notify an appropriate law enforcement agency in the local jurisdiction in which the apprehension is expected to occur. Notification must include, at a minimum: The name of the defendant; the address, or the approximate location if the address is undeterminable, of the dwelling, building, or other structure where the planned forced entry is expected to occur; the name of the bail bond recovery agent; the name of the contracting bail bond agent; and the alleged offense or conduct the defendant committed that resulted in the issuance of a bail bond.

. During the actual planned forced entry, a bail bond recovery agent:

.. Shall wear a shirt, vest, or other garment with the words "BAIL BOND RECOVERY AGENT," "BAIL ENFORCEMENT," or "BAIL ENFORCEMENT AGENT" displayed in at least two-inch-high reflective print letters across the front and back of the garment and in a contrasting color to that of the garment; and

.. May display a badge approved by the department with the words "BAIL BOND RECOVERY AGENT," "BAIL ENFORCEMENT," or "BAIL ENFORCEMENT AGENT" prominently displayed.

. Any law enforcement officer who assists in or is in attendance during a planned forced entry is immune from civil action for damages arising out of actions taken by the bail bond recovery agent or agents conducting the forced entry.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6437-S.SL.pdf?cite=2008%20c%20105%20§%208[2008 c 105 § 8]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2313-S.SL.pdf?cite=2004%20c%20186%20§%2012[2004 c 186 § 12]; ]

== 18.185.310 - Military training or experience.
An applicant with military training or experience satisfies the training or experience requirements of this chapter unless the director determines that the military training or experience is not substantially equivalent to the standards of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1418.SL.pdf?cite=2011%20c%20351%20§%2012[2011 c 351 § 12]; ]

== 18.185.901 - Effective date—1993 c 260.
This act is necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and shall take effect July 1, 1993.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1870-S.SL.pdf?cite=1993%20c%20260%20§%2025[1993 c 260 § 25]; ]

