= 18.138 - Dietitians and nutritionists.
:toc:

== 18.138.010 - Definitions.
. "Dietetics" is the integration and application of scientific principles of food, nutrition, biochemistry, physiology, management, and behavioral and social sciences in counseling people to achieve and maintain health. Unique functions of dietetics include, but are not limited to:

.. Assessing individual and community food practices and nutritional status using anthropometric, biochemical, clinical, dietary, and demographic data for clinical, research, and program planning purposes;

.. Establishing priorities, goals, and objectives that meet nutritional needs and are consistent with available resources and constraints;

.. Providing nutrition counseling and education as components of preventive, curative, and restorative health care;

.. Developing, implementing, managing, and evaluating nutrition care systems; and

.. Evaluating, making changes in, and maintaining appropriate standards of quality in food and nutrition care services.

. "General nutrition services" means the counseling and/or educating of groups or individuals in the selection of food to meet normal nutritional needs for health maintenance, which includes, but is not restricted to:

.. Assessing the nutritional needs of individuals and groups by planning, organizing, coordinating, and evaluating the nutrition components of community health care services;

.. Supervising, administering, or teaching normal nutrition in colleges, universities, clinics, group care homes, nursing homes, hospitals, private industry, and group meetings.

. "Certified dietitian" means any person certified to practice dietetics under this chapter.

. "Certified nutritionist" means any person certified to provide general nutrition services under this chapter.

. "Department" means the department of health.

. "Secretary" means the secretary of health or the secretary's designee.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20278[1991 c 3 § 278]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c277.pdf?cite=1988%20c%20277%20§%201[1988 c 277 § 1]; ]

== 18.138.020 - Certification required.
. No persons shall represent themselves as certified dietitians or certified nutritionists unless certified as provided for in this chapter.

. Persons represent themselves as certified dietitians or certified nutritionists when any title or any description of services is used which incorporates one or more of the following items or designations: "Certified dietitian," "certified dietician," "certified nutritionist," "D.," "C.D.," or "C.N."

. The secretary may by rule proscribe or regulate advertising and other forms of patient solicitation which are likely to mislead or deceive the public as to whether someone is certified under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20279[1991 c 3 § 279]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c277.pdf?cite=1988%20c%20277%20§%202[1988 c 277 § 2]; ]

== 18.138.030 - Qualifications for certification.
. An applicant applying for certification as a certified dietitian or certified nutritionist shall file a written application on a form or forms provided by the secretary setting forth under affidavit such information as the secretary may require, and proof that the candidate has met qualifications set forth below in subsection (2) or (3) of this section.

. Any person seeking certification as a "certified dietitian" shall meet the following qualifications:

.. Be eighteen years of age or older;

.. Has satisfactorily completed a major course of study in human nutrition, foods and nutrition, dietetics, or food systems management, and has received a baccalaureate or higher degree from a college or university accredited by the Western association of schools and colleges or a similar accreditation agency or colleges and universities approved by the secretary in rule;

.. Demonstrates evidence of having successfully completed a planned continuous preprofessional experience in dietetic practice of not less than nine hundred hours under the supervision of a certified dietitian or a registered dietitian or demonstrates completion of a coordinated undergraduate program in dietetics, both of which meet the training criteria established by the secretary;

.. Has satisfactorily completed an examination for dietitians administered by a public or private agency or institution recognized by the secretary as qualified to administer the examination; and

.. Has satisfactorily completed courses of continuing education as currently established by the secretary.

. An individual may be certified as a certified dietician if he or she provides evidence of meeting criteria for registration on June 9, 1988, by the commission on dietetic registration.

. Any person seeking certification as a "certified nutritionist" shall meet the following qualifications:

.. Possess the qualifications required to be a certified dietitian; or

.. Has received a master's degree or doctorate degree in one of the following subject areas: Human nutrition, nutrition education, foods and nutrition, or public health nutrition from a college or university accredited by the Western association of schools and colleges or a similar accrediting agency or colleges and universities approved by the secretary in rule.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20280[1991 c 3 § 280]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c277.pdf?cite=1988%20c%20277%20§%203[1988 c 277 § 3]; ]

== 18.138.040 - Certification—Application procedures, requirements, fees.
. If the applicant meets the qualifications as outlined in RCW 18.138.030(2), the secretary shall confer on such candidates the title certified dietitian.

. If the applicant meets the qualifications as outlined in RCW 18.138.030(4), the secretary shall confer on such candidates the title certified nutritionist.

. Applicants for certification as a certified dietitian or certified nutritionist shall comply with administrative procedures, administrative requirements, and fees determined by the secretary under RCW 43.70.250 and 43.70.280.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2084[1996 c 191 § 84]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20281[1991 c 3 § 281]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c277.pdf?cite=1988%20c%20277%20§%204[1988 c 277 § 4]; ]

== 18.138.050 - Certification without examination.
The secretary may certify a person applying for the title "certified dietitian" without examination if such person is licensed or certified as a dietitian in another jurisdiction and if, in the secretary's judgment, the requirements of that jurisdiction are equivalent to or greater than those of Washington state.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20282[1991 c 3 § 282]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c277.pdf?cite=1988%20c%20277%20§%206[1988 c 277 § 6]; ]

== 18.138.060 - Renewal of certification—Fee.
. Every person certified as a certified dietitian or certified nutritionist shall renew the certification according to administrative procedures, administrative requirements, and fees determined by the secretary as provided in RCW 43.70.250 and 43.70.280.

. All fees collected under this section shall be credited to the health professions account as required.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2085[1996 c 191 § 85]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20283[1991 c 3 § 283]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c277.pdf?cite=1988%20c%20277%20§%207[1988 c 277 § 7]; ]

== 18.138.070 - Authority of secretary.
In addition to any other authority provided by law, the secretary may:

. Adopt rules in accordance with chapter 34.05 RCW necessary to implement this chapter;

. Establish forms necessary to administer this chapter;

. Issue a certificate to an applicant who has met the requirements for certification and deny a certificate to an applicant who does not meet the minimum qualifications;

. Hire clerical, administrative, and investigative staff as needed to implement and administer this chapter and hire individuals, including those certified under this chapter, to serve as consultants as necessary to implement and administer this chapter;

. Maintain the official departmental record of all applicants and certificate holders;

. Conduct a hearing, pursuant to chapter 34.05 RCW, on an appeal of a denial of certification based on the applicant's failure to meet the minimum qualifications for certification;

. Investigate alleged violations of this chapter and consumer complaints involving the practice of persons representing themselves as certified dietitians or certified nutritionists;

. Issue subpoenas, statements of charges, statements of intent to deny certifications, and orders and delegate in writing to a designee the authority to issue subpoenas, statements of charges, and statements on intent to deny certifications;

. Conduct disciplinary proceedings, impose sanctions, and assess fines for violations of this chapter or any rules adopted under it in accordance with chapter 34.05 RCW;

. Set all certification, renewal, and late renewal fees in accordance with RCW 43.70.250; and

. Set certification expiration dates and renewal periods for all certifications under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1251-S.SL.pdf?cite=1999%20c%20151%20§%20301[1999 c 151 § 301]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20516[1994 sp.s. c 9 § 516]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20284[1991 c 3 § 284]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c277.pdf?cite=1988%20c%20277%20§%2010[1988 c 277 § 10]; ]

== 18.138.090 - Application of uniform disciplinary act.
The uniform disciplinary act, chapter 18.130 RCW, governs the issuance and denial of certificates, unauthorized practices, and the disciplining of certificate holders under this chapter. The secretary shall be the disciplining authority under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20286[1991 c 3 § 286]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c277.pdf?cite=1988%20c%20277%20§%205[1988 c 277 § 5]; ]

== 18.138.100 - Insurance coverage.
This chapter does not require or prohibit individual or group policies or contracts of an insurance carrier, health care service contractor, or health maintenance organization to provide benefits or coverage for services and supplies provided by a person certified under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c277.pdf?cite=1988%20c%20277%20§%209[1988 c 277 § 9]; ]

== 18.138.110 - Health food stores exempted.
Nothing in this chapter shall be construed to apply to owners, operators or employees of health food stores provided the owners, operators or employees do not represent themselves to be certified dietitians or certified nutritionists.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c277.pdf?cite=1988%20c%20277%20§%2011[1988 c 277 § 11]; ]

