= 18.155 - Sex offender treatment providers.
:toc:

== 18.155.010 - Findings—Construction.
The legislature finds that sex offender therapists who examine and treat sex offenders pursuant to the special sexual [sex] offender sentencing alternative under RCW 9.94A.670 and who may treat juvenile sex offenders pursuant to RCW 13.40.160, play a vital role in protecting the public from sex offenders who remain in the community following conviction. The legislature finds that the qualifications, practices, techniques, and effectiveness of sex offender treatment providers vary widely and that the court's ability to effectively determine the appropriateness of granting the sentencing alternative and monitoring the offender to ensure continued protection of the community is undermined by a lack of regulated practices. The legislature recognizes the right of sex offender therapists to practice, consistent with the paramount requirements of public safety. Public safety is best served by regulating sex offender therapists whose clients are being evaluated and being treated pursuant to RCW 9.94A.670 and 13.40.160. This chapter shall be construed to require only those sex offender therapists who examine and treat sex offenders pursuant to RCW 9.94A.670 and 13.40.160 to obtain a sexual [sex] offender treatment certification as provided in this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2400.SL.pdf?cite=2000%20c%20171%20§%2032[2000 c 171 § 32]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6223.SL.pdf?cite=2000%20c%2028%20§%2037[2000 c 28 § 37]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c3.pdf?cite=1990%20c%203%20§%20801[1990 c 3 § 801]; ]

== 18.155.020 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter:

. "Advisory committee" means the sex offender treatment providers advisory committee established under RCW 18.155.100.

. "Certified sex offender treatment provider" means an individual who is a licensed psychologist, licensed marriage and family therapist, licensed social worker, licensed mental health counselor, or psychiatrist as defined in RCW 71.05.020, who is certified to examine and treat sex offenders pursuant to chapters 9.94A and 13.40 RCW and sexually violent predators under chapter 71.09 RCW.

. "Certified affiliate sex offender treatment provider" means an individual who is a licensed psychologist, licensed marriage and family therapist, licensed social worker, licensed mental health counselor, or psychiatrist as defined in RCW 71.05.020, who is certified as an affiliate to examine and treat sex offenders pursuant to chapters 9.94A and 13.40 RCW and sexually violent predators under chapter 71.09 RCW under the supervision of a qualified supervisor.

. "Department" means the department of health.

. [Empty]
.. "Qualified supervisor" means:

... A person who meets the requirements for certification as a sex offender treatment provider;

... A person who meets a lifetime experience threshold of having provided at least two thousand hours of direct sex offender specific treatment and assessment services and who continues to maintain professional involvement in the field; or

... A person who meets a lifetime experience threshold of at least two years of full-time work in a state-run facility or state-run treatment program providing direct sex offender specific treatment and assessment services and who continues to maintain professional involvement in the field.

.. A qualified supervisor not credentialed by the department as a sex offender treatment provider must sign and submit to the department an attestation form provided by the department stating under penalty of perjury that the qualified supervisor has met the requisite education, training, or experience requirements and that the qualified supervisor is able to substantiate the qualified supervisor's claim to have met the requirements for education, training, or experience.

. "Secretary" means the secretary of health.

. "Sex offender treatment provider" or "affiliate sex offender treatment provider" means a person who counsels or treats sex offenders accused of or convicted of a sex offense as defined by RCW 9.94A.030.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6641-S.SL.pdf?cite=2020%20c%20266%20§%201[2020 c 266 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2849-S.SL.pdf?cite=2004%20c%2038%20§%203[2004 c 38 § 3]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6151-S.SL.pdf?cite=2001%202nd%20sp.s.%20c%2012%20§%20401[2001 2nd sp.s. c 12 § 401]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2400.SL.pdf?cite=2000%20c%20171%20§%2033[2000 c 171 § 33]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6223.SL.pdf?cite=2000%20c%2028%20§%2038[2000 c 28 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c3.pdf?cite=1990%20c%203%20§%20802[1990 c 3 § 802]; ]

== 18.155.030 - Certificate required.
. No person shall represent himself or herself as a certified sex offender treatment provider or certified affiliate sex offender treatment provider without first applying for and receiving a certificate pursuant to this chapter.

. Only a certified sex offender treatment provider, or certified affiliate sex offender treatment provider who has completed at least fifty percent of the required hours under the supervision of a qualified supervisor, may perform or provide the following services:

.. Treatment or evaluation of convicted level III sex offenders who are sentenced and ordered into treatment pursuant to chapter 9.94A RCW and adjudicated level III juvenile sex offenders who are ordered into treatment pursuant to chapter 13.40 RCW; or

.. Except as provided under subsection (3) of this section, treatment of sexually violent predators who are conditionally released to a less restrictive alternative pursuant to chapter 71.09 RCW.

. A certified sex offender treatment provider, or certified affiliate sex offender treatment provider who has completed at least fifty percent of the required hours under the supervision of a qualified supervisor, may not perform or provide treatment of sexually violent predators under subsection (2)(b) of this section if the treatment provider has been:

.. Convicted of a sex offense, as defined in RCW 9.94A.030;

.. Convicted in any other jurisdiction of an offense that under the laws of this state would be classified as a sex offense as defined in RCW 9.94A.030; or

.. Suspended or otherwise restricted from practicing any health care profession by competent authority in any state, federal, or foreign jurisdiction.

. Certified sex offender treatment providers and certified affiliate sex offender treatment providers may perform or provide the following service: Treatment or evaluation of convicted level I and level II sex offenders who are sentenced and ordered into treatment pursuant to chapter 9.94A RCW and adjudicated juvenile level I and level II sex offenders who are sentenced and ordered into treatment pursuant to chapter 13.40 RCW.

. Employees of state-run facilities or state-run treatment programs are not required to be a certified sex offender treatment provider or a certified affiliate sex offender treatment provider to do the work described in this section as part of their job duties if not pursuing certification under this chapter.

. Individuals credentialed by the department of health as a certified sex offender treatment provider or a certified affiliate sex offender treatment provider prior to June 11, 2020, are considered to have met the requirement of holding an underlying health license or credential described in RCW 18.155.020 (2) and (3), provided the underlying license or credential remains active and in good standing.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6641-S.SL.pdf?cite=2020%20c%20266%20§%202[2020 c 266 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2849-S.SL.pdf?cite=2004%20c%2038%20§%204[2004 c 38 § 4]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6151-S.SL.pdf?cite=2001%202nd%20sp.s.%20c%2012%20§%20402[2001 2nd sp.s. c 12 § 402]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2400.SL.pdf?cite=2000%20c%20171%20§%2034[2000 c 171 § 34]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6223.SL.pdf?cite=2000%20c%2028%20§%2039[2000 c 28 § 39]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c3.pdf?cite=1990%20c%203%20§%20803[1990 c 3 § 803]; ]

== 18.155.040 - Secretary—Authority.
In addition to any other authority provided by law, the secretary shall have the following authority:

. To set administrative procedures, administrative requirements, and fees in accordance with RCW 43.70.250, 43.70.280, and 71.09.360;

. To establish forms necessary to administer this chapter;

. To issue a certificate or an affiliate certificate to any applicant who has met the education, training, and examination requirements for certification or an affiliate certification and deny a certificate to applicants who do not meet the minimum qualifications for certification or affiliate certification. Proceedings concerning the denial of certificates based on unprofessional conduct or impaired practice shall be governed by the uniform disciplinary act, chapter 18.130 RCW;

. To hire clerical, administrative, and investigative staff as needed to implement and administer this chapter and to hire individuals including those certified under this chapter to serve as examiners or consultants as necessary to implement and administer this chapter;

. To maintain the official department record of all applicants and certifications;

. To conduct a hearing on an appeal of a denial of a certificate on the applicant's failure to meet the minimum qualifications for certification. The hearing shall be conducted pursuant to chapter 34.05 RCW;

. To issue subpoenas, statements of charges, statements of intent to deny certificates, and orders and to delegate in writing to a designee the authority to issue subpoenas, statements of charges, and statements of intent to deny certificates;

. To determine the minimum education, work experience, and training requirements for certification or affiliate certification, including but not limited to approval of educational programs;

. To prepare and administer or approve the preparation and administration of examinations for certification;

. To establish by rule the procedure for appeal of an examination failure;

. To adopt rules implementing a continuing competency program;

. To adopt rules in accordance with chapter 34.05 RCW as necessary to implement this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6641-S.SL.pdf?cite=2020%20c%20266%20§%207[2020 c 266 § 7]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2849-S.SL.pdf?cite=2004%20c%2038%20§%205[2004 c 38 § 5]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2086[1996 c 191 § 86]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c3.pdf?cite=1990%20c%203%20§%20804[1990 c 3 § 804]; ]

== 18.155.060 - Immunity.
The secretary, members of the committee, and individuals acting on their behalf are immune from suit in any action, civil or criminal, based on any acts performed in the course of their duties.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c3.pdf?cite=1990%20c%203%20§%20806[1990 c 3 § 806]; ]

== 18.155.070 - Certificate—Requirements.
The department shall issue a certificate to any applicant who meets the following requirements:

. Successful completion of an educational program approved by the secretary or successful completion of alternate training which meets the criteria of the secretary;

. Successful completion of any experience requirement established by the secretary;

. Successful completion of an examination administered or approved by the secretary;

. Not having engaged in unprofessional conduct or being unable to practice with reasonable skill and safety as a result of a physical or mental impairment;

. Not convicted of a sex offense, as defined in RCW 9.94A.030 or convicted in any other jurisdiction of an offense that under the laws of this state would be classified as a sex offense as defined in RCW 9.94A.030; and

. Other requirements as may be established by the secretary that impact the competence of the sex offender treatment provider.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2654-S.SL.pdf?cite=2006%20c%20134%20§%201[2006 c 134 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c3.pdf?cite=1990%20c%203%20§%20807[1990 c 3 § 807]; ]

== 18.155.075 - Affiliate certificate—Requirements.
. The department shall issue an affiliate certificate to any applicant who meets the following requirements:

.. Successful completion of an educational program approved by the secretary or successful completion of alternate training which meets the criteria of the secretary;

.. Successful completion of an examination administered or approved by the secretary;

.. Proof of supervision by a qualified supervisor;

.. Not having engaged in unprofessional conduct or being unable to practice with reasonable skill and safety as a result of a physical or mental impairment;

.. Not convicted of a sex offense, as defined in RCW 9.94A.030 or convicted in any other jurisdiction of an offense that under the laws of this state would be classified as a sex offense as defined in RCW 9.94A.030; and

.. Other requirements as may be established by the secretary that impact the competence of the sex offender treatment provider.

. Individuals credentialed by the department of health as a certified affiliate sex offender treatment provider prior to June 11, 2020, are considered to have met the requirement of holding an underlying health license or credential described in RCW 18.155.020(3), provided the underlying license or credential remains active and in good standing.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6641-S.SL.pdf?cite=2020%20c%20266%20§%203[2020 c 266 § 3]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2654-S.SL.pdf?cite=2006%20c%20134%20§%202[2006 c 134 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2849-S.SL.pdf?cite=2004%20c%2038%20§%206[2004 c 38 § 6]; ]

== 18.155.080 - Standards and procedures.
The secretary shall establish standards and procedures for approval of the following:

. Educational programs and alternate training, which must consider credit for experience obtained through work in a state-run facility or state-run treatment program in Washington or in another state or territory of the United States where the applicant demonstrates having provided at least two thousand hours of direct sex offender specific treatment and assessment services, or two years full-time experience working in a state-run facility or state-run treatment program providing direct sex offender specific treatment and assessment services, and continue to maintain professional involvement in the field;

. Examination procedures;

. [Empty]
.. Certifying applicants who have a comparable certification in another jurisdiction, who must be allowed to receive consideration of certification if:

... They hold or have held within the past thirty-six months a credential in good standing from another state or territory of the United States that the secretary, with advice from the advisory committee, deems to be substantially equivalent to sex offender treatment provider certification in Washington; or

... They meet a lifetime experience threshold of having provided at least two thousand hours of direct sex offender specific treatment and assessment services, or two years full-time experience working in a state-run facility or state-run treatment program providing direct sex offender specific treatment and assessment services, and continue to maintain professional involvement in the field;

.. Nothing in (a) of this subsection prohibits the secretary from requiring background checks as a condition of receiving a credential;

. Application method and forms;

. Requirements for renewals of certificates;

. Requirements of certified sex offender treatment providers and certified affiliate sex offender treatment providers who seek inactive status;

. Other rules, policies, administrative procedures, and administrative requirements as appropriate to carry out the purposes of this chapter.

. In construing the requirements of this section, the applicant may sign attestation forms under penalty of perjury indicating that the applicant has participated in the required training and that the applicant is able to substantiate the applicant's claim to have met the requirements for hours of training if such substantiation is requested. Substantiation may include letters of recommendation from experts in the field with personal knowledge of the applicant's qualifications and experience to treat sex offenders in the community.

. Employees of a state-run facility or state-run treatment program may obtain the necessary experience to qualify for this certification through their work and do not need to be certified as an affiliate sex offender treatment provider to obtain the necessary experience requirements upon demonstrating proof of supervision by a qualified supervisor.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6641-S.SL.pdf?cite=2020%20c%20266%20§%204[2020 c 266 § 4]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2849-S.SL.pdf?cite=2004%20c%2038%20§%207[2004 c 38 § 7]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2151-S.SL.pdf?cite=1996%20c%20191%20§%2087[1996 c 191 § 87]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c3.pdf?cite=1990%20c%203%20§%20808[1990 c 3 § 808]; ]

== 18.155.090 - Application of uniform disciplinary act.
The uniform disciplinary act, chapter 18.130 RCW, governs unauthorized practice, the issuance and denial of certificates, and the discipline of certified sex offender treatment providers and certified affiliate sex offender treatment providers under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2849-S.SL.pdf?cite=2004%20c%2038%20§%208[2004 c 38 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c3.pdf?cite=1990%20c%203%20§%20809[1990 c 3 § 809]; ]

== 18.155.100 - Sex offender treatment providers advisory committee—Appointment—Terms—Duties—Requirements.
. The sex offender treatment providers advisory committee is established to advise the secretary concerning the administration of this chapter.

. The secretary shall appoint the members of the advisory committee, which shall consist of the following persons:

.. One superior court judge;

.. Three sex offender treatment providers;

.. One mental health practitioner who specializes in treating victims of sexual assault;

.. One defense attorney with experience in representing persons charged with sexual offenses;

.. One representative from a statewide association representing prosecuting attorneys;

.. The secretary of the department of social and health services or the secretary's designee;

.. The secretary of the department of corrections or the secretary's designee; and

.. The secretary of the department of children, youth, and families or the secretary's designee.

. The advisory committee shall be a permanent body. The members shall serve staggered six-year terms, to be set by the secretary. No person other than the members representing the departments of social and health services, children, youth, and families, and corrections may serve more than two consecutive terms.

. The secretary may remove any member of the advisory committee for cause as specified by rule. In the case of a vacancy, the secretary shall appoint a person to serve for the remainder of the unexpired term.

. The advisory committee shall provide advice to the secretary concerning:

.. Certification procedures under this chapter and their implementation;

.. Standards maintained under RCW 18.155.080, and advice on individual applications for certification;

.. Issues pertaining to maintaining a healthy workforce of certified sex offender treatment providers to meet the needs of the state of Washington. In considering workforce issues, the advisory committee must evaluate options for reducing or eliminating some or all of the certification-related fees, including the feasibility of requiring that the cost of regulation of persons certified under this chapter be borne by the professions that are identified as eligible to be an underlying credential for certification; and

.. Recommendations for reform of regulatory or administrative practices of the department, the department of social and health services, or the department of corrections that are within the purview and expertise of the advisory committee. The advisory committee may submit recommendations requiring statutory reform to the office of the governor, the secretary of the senate, and the chief clerk of the house of representatives.

. Committee members shall be reimbursed for travel expenses in accordance with RCW 43.03.050 and 43.03.060.

. The advisory committee shall elect officers as deemed necessary to administer its duties. A simple majority of the advisory committee members currently serving shall constitute a quorum of the advisory committee.

. Members of the advisory committee shall be residents of the state of Washington.

. Members of the advisory committee who are sex offender treatment providers must have a minimum of five years of extensive work experience in treating sex offenders to qualify for appointment to the advisory committee. The sex offender treatment providers on the advisory committee must be certified under this chapter.

. The advisory committee shall meet at times as necessary to conduct advisory committee business.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6641-S.SL.pdf?cite=2020%20c%20266%20§%205[2020 c 266 § 5]; ]

