= 18.190 - Operation as limited liability company.
:toc:

== 18.190.010 - License—Requirements.
Any business or profession licensed under this title may operate as a limited liability company formed under chapter 25.15 RCW. Any such limited liability company must be licensed as a limited liability company in accordance with the otherwise applicable licensing provisions of this title. Any such limited liability company shall meet the following requirements:

. The principal purpose and business of the limited liability company shall be to furnish services to the public which are consistent with the applicable chapter under this title;

. At least one manager of the limited liability company shall be a person licensed under the applicable chapter under this title; and

. Each resident manager or member in charge of an office of the limited liability company in this state and each resident manager or member personally engaged within this state in the business or profession of the company shall be licensed under the applicable chapter under this title.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1235-S2.SL.pdf?cite=1994%20c%20211%20§%201403[1994 c 211 § 1403]; ]

