= 18.270 - Fire protection sprinkler fitting.
:toc:

== 18.270.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Certificate" means a certificate of competency granted by the director under the terms of this chapter, and is valid within the state and all political subdivisions, and meets all of the requirements for license or certification that may be applied by the political subdivisions.

. "Contractor" means any person, corporation, or other entity, licensed under chapter 18.160 RCW, which performs any work covered by the provisions of this chapter.

. "Director" means the state director of fire protection.

. "Fire protection sprinkler fitting" means installing, altering, and repairing sprinkler, standpipe, hose, or other hazard systems for fire protection purposes that are an assembly of piping or conduit beginning at the connection to the primary water supply within a building, sprinkler tank heaters, air lines, and all tanks and pumps attached thereto.

. "Journey-level sprinkler fitter" means any person who has been issued a certificate by the director as provided by this chapter.

. "NFPA 13-D" means the standard in use by the national fire protection association for the installation of fire protection sprinkler systems in one and two-family dwellings and manufactured homes whenever the provisions of this chapter are applied.

. "NFPA 13-R" means the standard in use by the national fire protection association for the installation of fire protection sprinkler systems in residential dwellings up to and including four stories in height whenever the provisions of this chapter are applied.

. "Person" means a natural person, including an owner, manager, partner, officer, employee, or occupant.

. "Residential sprinkler fitter" means anyone who has been issued a certificate by the director limited to installation, maintenance, and repair of the fire protection sprinkler system of residential occupancies as defined by NFPA 13-D and NFPA 13-R.

. "Trainee" means anyone who has been issued a training certificate by the director who is learning the fire protection sprinkler fitting trade under the direct supervision of a journey-level sprinkler fitter or residential sprinkler fitter.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1968-S.SL.pdf?cite=2007%20c%20435%20§%201[2007 c 435 § 1]; ]

== 18.270.020 - Certificate required—Penalties.
. No person may engage in the trade of fire protection sprinkler fitting without having a valid journey-level sprinkler fitter certificate, residential sprinkler fitter certificate, training certificate, or temporary certificate, with the exception of a certified plumber installing a residential fire protection sprinkler system connected to potable water requiring a plumbing certificate.

. No contractor may employ a person in violation of subsection (1) of this section to perform fire protection sprinkler fitting work.

. A person found by the director to have committed an infraction under this chapter shall be assessed a monetary penalty as set by rule.

. Each day in which a person engages in the trade of fire protection sprinkler fitting in violation of subsection (1) of this section or employs a person in violation of subsection (2) of this section is considered a separate infraction.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1968-S.SL.pdf?cite=2007%20c%20435%20§%203[2007 c 435 § 3]; ]

== 18.270.030 - Examination.
The director shall adopt a written examination to be administered to applicants for certificates.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1968-S.SL.pdf?cite=2007%20c%20435%20§%204[2007 c 435 § 4]; ]

== 18.270.040 - Application requirements—Certificate without examination.
. Every applicant for a certificate shall pay an examination fee and satisfactorily pass an examination as provided by rule.

. Every applicant for a certificate shall apply to the director on an application form provided by the director and pay the application fee as provided by rule.

. [Empty]
.. Every applicant for a journey-level sprinkler fitter certificate shall provide evidence to the director on a form provided by the director of at least eight thousand hours of trade-related fire protection sprinkler fitting experience.

.. Every applicant for a residential sprinkler fitter certificate shall provide evidence to the director on a form provided by the director of at least four thousand hours of trade-related fire protection sprinkler fitting or residential sprinkler fitting experience.

. Every applicant for a training certificate shall provide evidence to the director on a form provided by the director of trade-related employment by a contractor.

. [Empty]
.. The director shall grant a journey-level sprinkler fitter certificate without examination to any applicant who, during the ninety days following January 1, 2009, submits an application for such certification and evidence of his or her employment as a journey-level sprinkler fitter for a period of not less than eight thousand hours.

.. The director shall grant a residential sprinkler fitter certificate without examination to any applicant who, during the ninety days following January 1, 2009, submits an application for such certification and evidence of his or her employment as a journey-level sprinkler fitter or a residential sprinkler fitter for a period of not less than four thousand hours.

. The director may grant a certificate without examination to any applicant who is a journey-level sprinkler fitter or residential sprinkler fitter from a state whose requirements for certification are at least substantially equivalent to the requirements of this state, and which extends the same privileges of reciprocity to journey-level sprinkler fitters or residential sprinkler fitters from this state.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1968-S.SL.pdf?cite=2007%20c%20435%20§%205[2007 c 435 § 5]; ]

== 18.270.050 - Certificate expiration and renewal.
. A certificate expires on December 31st.

. The certificate shall be renewed every other year.

. Before the expiration date of the certificate, every applicant shall reapply to the director on an application form provided by the director and pay the application fee as provided by rule.

. If a certificate is not renewed before its expiration date, an applicant must:

.. Apply to the director on an application form provided by the director;

.. Pay an application fee to the director as provided by rule;

.. Pay an examination fee as provided by rule; and

.. Successfully pass the written examination required by this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1968-S.SL.pdf?cite=2007%20c%20435%20§%206[2007 c 435 § 6]; ]

== 18.270.060 - Fees—Deposit and use.
All receipts from fees and charges or from the money generated by the rules adopted under this chapter shall be deposited into the fire protection contractor license fund created in RCW 18.160.050 and used for the purposes authorized under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1968-S.SL.pdf?cite=2007%20c%20435%20§%207[2007 c 435 § 7]; ]

== 18.270.070 - Violations—Investigations.
An authorized representative of the director may investigate alleged violations of this chapter. Upon request of an authorized representative, a person performing fire protection sprinkler fitting or residential sprinkler fitting work must produce evidence of a certificate issued by the director in accordance with this chapter. Failure to produce such evidence is an infraction as provided by RCW 18.270.020.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1968-S.SL.pdf?cite=2007%20c%20435%20§%208[2007 c 435 § 8]; ]

== 18.270.080 - Appeals.
A person wishing to appeal a determination of infraction under this chapter must file an appeal within twenty days of the date of the notice of infraction in accordance with chapter 34.05 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1968-S.SL.pdf?cite=2007%20c%20435%20§%209[2007 c 435 § 9]; ]

== 18.270.090 - Suspension.
The director shall immediately suspend any certificate issued under this chapter if the holder has been certified pursuant to RCW 74.20A.320 by the department of social and health services as a person who is not in compliance with a support order. If the person has continued to meet all other requirements for certification during the suspension, reissuance of the certificate shall be automatic upon the director's receipt of a release issued by the department of social and health services stating that the person is in compliance with the order.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1968-S.SL.pdf?cite=2007%20c%20435%20§%2010[2007 c 435 § 10]; ]

== 18.270.900 - Administration of chapter.
. This chapter shall be administered by the director.

. The director may adopt rules necessary for the administration of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1968-S.SL.pdf?cite=2007%20c%20435%20§%202[2007 c 435 § 2]; ]

== 18.270.901 - Effective date—2007 c 435.
This act takes effect January 1, 2009.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1968-S.SL.pdf?cite=2007%20c%20435%20§%2012[2007 c 435 § 12]; ]

