= 18.215 - Surgical technologists.
:toc:

== 18.215.005 - Registration of surgical technologists.
The registration of surgical technologists is in the interest of the public health, safety, and welfare.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1864-S.SL.pdf?cite=1999%20c%20335%20§%201[1999 c 335 § 1]; ]

== 18.215.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Department" means the department of health.

. "Secretary" means the secretary of health or the secretary's designee.

. "Surgical technologist" means a person, regardless of title, who is supervised in the surgical setting under the delegation of authority of a health care practitioner acting within the scope of his or her license and under the laws of this state.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1864-S.SL.pdf?cite=1999%20c%20335%20§%202[1999 c 335 § 2]; ]

== 18.215.020 - Registration.
No person may represent oneself as a surgical technologist by use of any title or description without being registered by the department under the provisions of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1864-S.SL.pdf?cite=1999%20c%20335%20§%203[1999 c 335 § 3]; ]

== 18.215.030 - Construction—Limitation of chapter.
Nothing in this chapter may be construed to prohibit or restrict:

. The practice of an individual licensed, certified, or registered under the laws of this state and performing services within his or her authorized scope of practice;

. The practice by an individual employed by the government of the United States while engaged in the performance of duties prescribed by the laws of the United States;

. The practice by a person who is a regular student in an educational program approved by the secretary, and whose performance of services is pursuant to a regular course of instruction or assignments from an instructor and under the general supervision of the instructor.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1864-S.SL.pdf?cite=1999%20c%20335%20§%204[1999 c 335 § 4]; ]

== 18.215.040 - Secretary's authority.
In addition to any other authority provided by law, the secretary has the authority to:

. Adopt rules under chapter 34.05 RCW as required to implement this chapter;

. Establish all registration and renewal fees in accordance with RCW 43.70.250;

. Establish forms and procedures necessary to administer this chapter;

. Register an applicant or deny registration based upon unprofessional conduct or impairment governed by the uniform disciplinary act, chapter 18.130 RCW;

. Hire clerical, administrative, investigative, and other staff as needed to implement this chapter; and

. Maintain the official department record of all applicants and persons with registrations.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1864-S.SL.pdf?cite=1999%20c%20335%20§%205[1999 c 335 § 5]; ]

== 18.215.050 - Required applicant information.
An applicant shall identify the name and address of the applicant and other information required by the secretary necessary to establish whether there are grounds for denial of a registration or conditional registration under chapter 18.130 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1864-S.SL.pdf?cite=1999%20c%20335%20§%206[1999 c 335 § 6]; ]

== 18.215.060 - Registration of applicant—Fee.
The secretary shall register an applicant on forms provided by the secretary. Each applicant shall pay a fee determined by the secretary under RCW 43.70.250. The fee shall accompany the application.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1864-S.SL.pdf?cite=1999%20c%20335%20§%207[1999 c 335 § 7]; ]

== 18.215.070 - Renewal of registration—Requirements, fees established by rule.
The secretary shall establish by rule the procedural requirements and fees for renewal of registration. Failure to renew shall invalidate the registration and all privileges granted by the registration.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1864-S.SL.pdf?cite=1999%20c%20335%20§%208[1999 c 335 § 8]; ]

== 18.215.080 - Uniform disciplinary act—Application to chapter.
The uniform disciplinary act, chapter 18.130 RCW, governs unregistered practice, the issuance and denial of registration, and the discipline of persons registered under this chapter. The secretary shall be the disciplining authority under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1864-S.SL.pdf?cite=1999%20c%20335%20§%209[1999 c 335 § 9]; ]

== 18.215.090 - Registration requirements—Military training or experience.
An applicant with military training or experience satisfies the training or experience requirements of this chapter unless the secretary determines that the military training or experience is not substantially equivalent to the standards of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5307-S.SL.pdf?cite=2011%20c%2032%20§%2013[2011 c 32 § 13]; ]

