= 18.250 - Athletic trainers.
:toc:

== 18.250.005 - Purpose.
It is the purpose of this chapter to provide for the licensure of persons offering athletic training services to the public and to ensure standards of competence and professional conduct on the part of athletic trainers.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5503-S.SL.pdf?cite=2007%20c%20253%20§%201[2007 c 253 § 1]; ]

== 18.250.010 - Definitions. (Effective until July 1, 2022.)
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Athlete" means a person who participates in exercise, recreation, sport, or games requiring physical strength, range-of-motion, flexibility, body awareness and control, speed, stamina, or agility, and the exercise, recreation, sports, or games are of a type conducted in association with an educational institution or professional, amateur, or recreational sports club or organization.

. "Athletic injury" means an injury or condition sustained by an athlete that affects the person's participation or performance in exercise, recreation, sport, or games and the injury or condition is within the professional preparation and education of an athletic trainer.

. "Athletic trainer" means a person who is licensed under this chapter. An athletic trainer can practice athletic training through the consultation, referral, or guidelines of a licensed health care provider working within their scope of practice.

. [Empty]
.. "Athletic training" means the application of the following principles and methods as provided by a licensed athletic trainer:

... Risk management and prevention of athletic injuries through preactivity screening and evaluation, educational programs, physical conditioning and reconditioning programs, application of commercial products, use of protective equipment, promotion of healthy behaviors, and reduction of environmental risks;

... Recognition, evaluation, and assessment of athletic injuries by obtaining a history of the athletic injury, inspection and palpation of the injured part and associated structures, and performance of specific testing techniques related to stability and function to determine the extent of an injury;

... Immediate care of athletic injuries, including emergency medical situations through the application of first-aid and emergency procedures and techniques for nonlife-threatening or life-threatening athletic injuries;

... Treatment, rehabilitation, and reconditioning of athletic injuries through the application of physical agents and modalities, therapeutic activities and exercise, standard reassessment techniques and procedures, commercial products, and educational programs, in accordance with guidelines established with a licensed health care provider as provided in RCW 18.250.070;

.. Treatment, rehabilitation, and reconditioning of work-related injuries through the application of physical agents and modalities, therapeutic activities and exercise, standard reassessment techniques and procedures, commercial products, and educational programs, under the direct supervision of and in accordance with a plan of care for an individual worker established by a provider authorized to provide physical medicine and rehabilitation services for injured workers; and

.. Referral of an athlete to an appropriately licensed health care provider if the athletic injury requires further definitive care or the injury or condition is outside an athletic trainer's scope of practice, in accordance with RCW 18.250.070.

.. "Athletic training" does not include:

... The use of spinal adjustment or manipulative mobilization of the spine and its immediate articulations;

... Orthotic or prosthetic services with the exception of evaluation, measurement, fitting, and adjustment of temporary, prefabricated or direct-formed orthosis as defined in chapter 18.200 RCW;

... The practice of occupational therapy as defined in chapter 18.59 RCW;

... The practice of acupuncture and Eastern medicine as defined in chapter 18.06 RCW;

.. Any medical diagnosis; and

.. Prescribing legend drugs or controlled substances, or surgery.

. "Committee" means the athletic training advisory committee.

. "Department" means the department of health.

. "Licensed health care provider" means a physician, physician assistant, osteopathic physician, osteopathic physician assistant, advanced registered nurse practitioner, naturopath, physical therapist, chiropractor, dentist, massage therapist, acupuncturist, occupational therapist, or podiatric physician and surgeon.

. "Secretary" means the secretary of health or the secretary's designee.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1865-S.SL.pdf?cite=2019%20c%20308%20§%2019[2019 c 308 § 19]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2425-S.SL.pdf?cite=2016%20c%2041%20§%2022[2016 c 41 § 22]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2430-S.SL.pdf?cite=2014%20c%20194%20§%201[2014 c 194 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5503-S.SL.pdf?cite=2007%20c%20253%20§%202[2007 c 253 § 2]; ]

== 18.250.020 - Secretary's authority—Application of uniform disciplinary act.
. In addition to any other authority provided by law, the secretary may:

.. Adopt rules, in accordance with chapter 34.05 RCW, necessary to implement this chapter;

.. Establish all license, examination, and renewal fees in accordance with RCW 43.70.250;

.. Establish forms and procedures necessary to administer this chapter;

.. Establish administrative procedures, administrative requirements, and fees in accordance with RCW 43.70.250 and 43.70.280. All fees collected under this section must be credited to the health professions account as required under RCW 43.70.320;

.. Develop and administer, or approve, or both, examinations to applicants for a license under this chapter;

.. Establish continuing education requirements by rule;

.. Issue a license to any applicant who has met the education, training, and examination requirements for licensure and deny a license to applicants who do not meet the minimum qualifications for licensure. However, denial of licenses based on unprofessional conduct or impaired practice is governed by the uniform disciplinary act, chapter 18.130 RCW;

.. In consultation with the committee, approve examinations prepared or administered by private testing agencies or organizations for use by an applicant in meeting the licensing requirements under RCW 18.250.060;

.. Determine which states have credentialing requirements substantially equivalent to those of this state, and issue licenses to individuals credentialed in those states that have successfully fulfilled the requirements of RCW 18.250.080;

.. Hire clerical, administrative, and investigative staff as needed to implement and administer this chapter;

.. Maintain the official department record of all applicants and licensees; and

.. Establish requirements and procedures for an inactive license.

. The uniform disciplinary act, chapter 18.130 RCW, governs unlicensed practice, the issuance and denial of licenses, and the discipline of licensees under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2430-S.SL.pdf?cite=2014%20c%20194%20§%202[2014 c 194 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5503-S.SL.pdf?cite=2007%20c%20253%20§%203[2007 c 253 § 3]; ]

== 18.250.030 - Athletic training advisory committee.
. The athletic training advisory committee is formed to further the purposes of this chapter.

. The committee consists of five members. Four members of the committee must be athletic trainers licensed under this chapter and residing in this state, must have not less than five years' experience in the practice of athletic training, and must be actively engaged in practice within two years of appointment. The fifth member must be appointed from the public at large, and have an interest in the rights of consumers of health services.

. The committee may provide advice on matters specifically identified and requested by the secretary, such as applications for licenses.

. The committee may be requested by the secretary to approve an examination required for licensure under this chapter.

. The committee, at the request of the secretary, may recommend rules in accordance with the administrative procedure act, chapter 34.05 RCW, relating to standards for appropriateness of athletic training care.

. The committee must meet during the year as necessary to provide advice to the secretary. The committee may elect a chair and a vice chair. A majority of the members currently serving constitute a quorum.

. Each member of the committee must be reimbursed for travel expenses as authorized in RCW 43.03.050 and 43.03.060. In addition, members of the committee must be compensated in accordance with RCW 43.03.240 when engaged in the authorized business of the committee.

. The secretary, members of the committee, or individuals acting on their behalf are immune from suit in any action, civil or criminal, based on any credentialing or disciplinary proceedings or other official acts performed in the course of their duties.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5503-S.SL.pdf?cite=2007%20c%20253%20§%204[2007 c 253 § 4]; ]

== 18.250.040 - License required.
. It is unlawful for any person to practice or offer to practice as an athletic trainer, or to represent themselves or other persons to be legally able to provide services as an athletic trainer, unless the person is licensed under the provisions of this chapter.

. No person may use the title "athletic trainer," the letters "ATC" or "LAT," the terms "sports trainer," "team trainer," "trainer," or any other words, abbreviations, or insignia in connection with his or her name to indicate or imply, directly or indirectly, that he or she is an athletic trainer without being licensed in accordance with this chapter as an athletic trainer.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5688-S.SL.pdf?cite=2019%20c%20358%20§%201[2019 c 358 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5503-S.SL.pdf?cite=2007%20c%20253%20§%205[2007 c 253 § 5]; ]

== 18.250.050 - Limitations of chapter.
Nothing in this chapter may prohibit, restrict, or require licensure of:

. Any person licensed, certified, or registered in this state and performing services within the authorized scope of practice;

. The practice by an individual employed by the government of the United States as an athletic trainer while engaged in the performance of duties prescribed by the laws of the United States;

. Any person pursuing a supervised course of study in an accredited athletic training educational program, if the person is designated by a title that clearly indicates a student or trainee status;

. An athletic trainer from another state for purposes of continuing education, consulting, or performing athletic training services while accompanying his or her group, individual, or representatives into Washington state on a temporary basis for no more than ninety days in a calendar year;

. Any elementary, secondary, or postsecondary school teacher, educator, or coach who does not represent themselves to the public as an athletic trainer; or

. A personal or fitness trainer employed by an athletic club or fitness center and not representing themselves as an athletic trainer or performing the duties of an athletic trainer provided under RCW 18.250.010(4)(a) (ii) through (vi).

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5688-S.SL.pdf?cite=2019%20c%20358%20§%202[2019 c 358 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5503-S.SL.pdf?cite=2007%20c%20253%20§%206[2007 c 253 § 6]; ]

== 18.250.060 - Applicant requirements.
An applicant for an athletic trainer license must:

. Have received a bachelor's or advanced degree from an accredited four-year college or university that meets the academic standards of athletic training, accepted by the secretary, as advised by the committee;

. Have successfully completed an examination administered or approved by the secretary, in consultation with the committee; and

. Submit an application on forms prescribed by the secretary and pay the licensure fee required under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5503-S.SL.pdf?cite=2007%20c%20253%20§%207[2007 c 253 § 7]; ]

== 18.250.070 - Treatment, rehabilitation, and reconditioning—Referral to licensed health care provider.
. Except as necessary to provide emergency care of athletic injuries, an athletic trainer shall not provide treatment, rehabilitation, or reconditioning services to any person except as specified in guidelines established with a licensed health care provider who is licensed to perform the services provided in the guidelines.

. If there is no improvement in an athlete who has sustained an athletic injury within fifteen days of initiation of treatment, rehabilitation, or reconditioning, the athletic trainer must refer the athlete to a licensed health care provider that is appropriately licensed to assist the athlete.

. If an athletic injury requires treatment, rehabilitation, or reconditioning for more than forty-five days, the athletic trainer must consult with, or refer the athlete to a licensed health care provider. The athletic trainer shall document the action taken.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5503-S.SL.pdf?cite=2007%20c%20253%20§%208[2007 c 253 § 8]; ]

== 18.250.080 - Application procedures, requirements, and fees.
Each applicant and license holder must comply with administrative procedures, administrative requirements, and fees under RCW 43.70.250 and 43.70.280. The secretary shall furnish a license to any person who applies and who has qualified under the provisions of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5503-S.SL.pdf?cite=2007%20c%20253%20§%209[2007 c 253 § 9]; ]

== 18.250.090 - Practice setting not restricted.
Nothing in this chapter restricts the ability of athletic trainers to work in the practice setting of his or her choice.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5503-S.SL.pdf?cite=2007%20c%20253%20§%2010[2007 c 253 § 10]; ]

== 18.250.100 - Health carrier contract with athletic trainer not required.
Nothing in this chapter may be construed to require that a health carrier defined in RCW 48.43.005 contract with a person licensed as an athletic trainer under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5503-S.SL.pdf?cite=2007%20c%20253%20§%2011[2007 c 253 § 11]; ]

== 18.250.110 - Medications.
. An athletic trainer licensed under this chapter may purchase, store, and administer over-the-counter topical medications such as hydrocortisone, fluocinonide, topical anesthetics, silver sulfadiazine, lidocaine, magnesium sulfate, zinc oxide, and other similar medications, as prescribed by an authorized health care practitioner for the practice of athletic training.

.. An athletic trainer may not administer any medications to a student in a public school as defined in RCW 28A.150.010 or private schools governed by chapter 28A.195 RCW.

.. An athletic trainer may administer medications consistent with this section to a minor in a setting other than a school, if the minor's parent or guardian provides written consent.

. An athletic trainer licensed under this chapter who has completed an anaphylaxis training program in accordance with RCW 70.54.440 may administer an epinephrine autoinjector to any individual who the athletic trainer believes in good faith is experiencing anaphylaxis as authorized by RCW 70.54.440.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5688-S.SL.pdf?cite=2019%20c%20358%20§%203[2019 c 358 § 3]; ]

== 18.250.901 - Effective date—2007 c 253.
This act takes effect July 1, 2008.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5503-S.SL.pdf?cite=2007%20c%20253%20§%2016[2007 c 253 § 16]; ]

== 18.250.902 - Implementation—2007 c 253.
The secretary of health may take the necessary steps to ensure that this act is implemented on its effective date.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5503-S.SL.pdf?cite=2007%20c%20253%20§%2017[2007 c 253 § 17]; ]

