= 18.230 - Recreation therapy.
:toc:

== 18.230.005 - Finding.
The overriding mission of therapeutic recreation is the provision of purposeful intervention designed to help clients grow and to assist them to prevent or relieve problems through recreation and leisure. It is a systematic methodology through a progression of phases, including assessment, planning, implementation, and evaluation. It is not a limited or restricted concept of service carried out only within the constraints of institutional care, but is a client-centered model that reflects a concern for the total well-being of the client. Recreation therapy is cost-effective and can decrease the costs of health care services by reducing primary and secondary disabilities. In anticipation of the expansion in long-term care, physical and psychiatric rehabilitation, and services for people with disabilities, the legislature finds and declares that the registration of recreational therapists is in the interest of the public health and safety.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2315-S.SL.pdf?cite=2002%20c%20216%20§%201[2002 c 216 § 1]; ]

== 18.230.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Department" means the department of health.

. "Recreation therapy" means the use of recreational, and/or community activities to include leisure counseling and community integration as treatment intervention to improve functional leisure and community competence of persons with a physical, cognitive, emotional, behavioral, or social disability. The primary purpose of recreation therapy is the use of leisure and community integration activities to restore, remediate, or rehabilitate persons in order to improve functioning and independence, as well as reduce or eliminate the effects of illness or disability.

. "Recreational therapist" means a person registered under this chapter.

. "Registration" means the registration issued to a person under this chapter.

. "Secretary" means the secretary of health or the secretary's designee.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2315-S.SL.pdf?cite=2002%20c%20216%20§%202[2002 c 216 § 2]; ]

== 18.230.020 - Use of title—Registration required.
No person may practice or represent oneself as a registered recreational therapist by use of any title without being registered to practice by the department of health, unless otherwise exempted by this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2315-S.SL.pdf?cite=2002%20c%20216%20§%203[2002 c 216 § 3]; ]

== 18.230.030 - Limitation of chapter.
Nothing in this chapter may be construed to prohibit or restrict:

. The practice by an individual licensed, certified, or registered under the laws of this state and performing services within the authorized scope of practice;

. The practice by an individual employed by the government of the United States while engaged in the performance of duties prescribed by the laws of the United States;

. The practice by a person who is a regular student in an educational program approved by the secretary, and whose performance of services is pursuant to a regular course of instruction or assignments from an instructor and under the general supervision of the instructor.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2315-S.SL.pdf?cite=2002%20c%20216%20§%204[2002 c 216 § 4]; ]

== 18.230.040 - Secretary's authority.
In addition to any other authority provided by law, the secretary has the authority to:

. Adopt rules under chapter 34.05 RCW necessary to implement this chapter;

. Establish all registration and renewal fees in accordance with RCW 43.70.250;

. Establish forms and procedures necessary to administer this chapter;

. Register any applicants who have met the requirements for registration and to deny registration to applicants who do not meet the requirements of this chapter, except that proceedings concerning the denial of registration based upon unprofessional conduct or impairment is governed by the uniform disciplinary act, chapter 18.130 RCW;

. Hire clerical, administrative, investigative, and other staff as needed to implement this chapter; and

. Maintain the official department record of all applicants and persons registered under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2315-S.SL.pdf?cite=2002%20c%20216%20§%205[2002 c 216 § 5]; ]

== 18.230.050 - Official record.
The secretary must keep an official record of all proceedings. A part of the record shall consist of a register of all applicants for registration under this chapter and the results of each application.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2315-S.SL.pdf?cite=2002%20c%20216%20§%206[2002 c 216 § 6]; ]

== 18.230.060 - Registration—Grounds for denial.
. Applicants for registration under this chapter are subject to the grounds for denial of a registration under chapter 18.130 RCW.

. The secretary must issue a registration to an applicant who completes an application form that identifies the name and address of the applicant, the registration requested, and information required by the secretary necessary to establish whether there are grounds for denial of a registration.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2315-S.SL.pdf?cite=2002%20c%20216%20§%207[2002 c 216 § 7]; ]

== 18.230.070 - Registration—Required information—Fee.
Applications for registration must be submitted on forms provided by the secretary. The secretary may require any information and documentation that reasonably relates to the need to determine whether the applicant meets the criteria for registration provided for in this chapter and chapter 18.130 RCW. Each applicant must pay a fee determined by the secretary under RCW 43.70.250. The fee must accompany the application.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2315-S.SL.pdf?cite=2002%20c%20216%20§%208[2002 c 216 § 8]; ]

== 18.230.080 - Renewal of registration.
The secretary must establish by rule the procedural requirements and fees for renewal of a registration. Failure to renew invalidates the registration and all privileges granted by the registration.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2315-S.SL.pdf?cite=2002%20c%20216%20§%209[2002 c 216 § 9]; ]

== 18.230.090 - Uniform disciplinary act—Application to chapter.
The uniform disciplinary act, chapter 18.130 RCW, governs the issuance and denial of a registration, unauthorized practice, and the discipline of persons registered under this chapter. The secretary is the disciplining authority under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2315-S.SL.pdf?cite=2002%20c%20216%20§%2010[2002 c 216 § 10]; ]

== 18.230.901 - Effective date—2002 c 216.
This act takes effect July 1, 2003.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2315-S.SL.pdf?cite=2002%20c%20216%20§%2014[2002 c 216 § 14]; ]

