= 18.290 - Genetic counselors.
:toc:

== 18.290.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Advisory committee" means the advisory committee on genetic counseling established in *section 5 of this act.

. "Collaborative agreement" means a written document that memorializes a relationship between a genetic counselor and a physician licensed under chapter 18.71 RCW or an osteopathic physician licensed under chapter 18.57 RCW, who is board certified in medical genetics or who is board certified in a specialty relevant to the practice of the genetic counselor that authorizes a genetic counselor to perform the functions specified in subsection (5)(d) of this section as applied to the practice of genetic counseling.

. "Department" means the department of health.

. "Genetic counselor" means an individual who is licensed to engage in the practice of genetic counseling under this chapter.

. "Practice of genetic counseling" means a communication process, conducted by one or more appropriately trained individuals that includes:

.. Estimating the likelihood of occurrence or recurrence of a birth defect or of any potentially inherited or genetically influenced condition. This assessment may involve:

... Obtaining and analyzing a complete health history of the person and family;

... Reviewing pertinent medical records;

... Evaluating the risks from exposure to possible mutagens or teratogens; and

... Providing recommendations for genetic testing or other evaluations to diagnose a condition or determine the carrier status of one or more family members;

.. Helping the individual, family, or health care provider:

... Appreciate the medical and psychosocial implications of a disorder, including its features, variability, usual course, and management options;

... Learn how genetic factors contribute to the disorder and affect the chance for recurrence of the condition in other family members;

... Understand available options for coping with, preventing, or reducing the chance of occurrence or recurrence of a condition;

... Understand genetic or prenatal tests, coordinate testing for inherited disorders, and interpret complex genetic test results;

.. Facilitating an individual's or family's:

... Exploration of the perception of risk and burden associated with the disorder;

... Decision making regarding testing or medical interventions consistent with their beliefs, goals, needs, resources, and cultural, ethical, and moral views; and

... Adjustment and adaptation to the condition or their genetic risk by addressing needs for psychosocial and medical support; and

.. Pursuant to a collaborative agreement:

... Ordering genetic tests or other evaluations to diagnose a condition or determine the carrier status of one or more family members, including testing for inherited disorders; and

... Selecting the most appropriate, accurate, and cost-effective methods of diagnosis.

. "Secretary" means the secretary of health.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5608-S.SL.pdf?cite=2009%20c%20302%20§%201[2009 c 302 § 1]; ]

== 18.290.020 - Secretary—Authority.
In addition to any other authority, the secretary has the authority to:

. Adopt rules under chapter 34.05 RCW necessary to implement this chapter;

. Establish all licensing, examination, and renewal fees in accordance with RCW 43.70.110 and 43.70.250;

. Establish forms and procedures necessary to administer this chapter;

. Issue licenses to applicants who have met the education, training, and examination requirements for obtaining a license and to deny a license to applicants who do not meet the requirements;

. Hire clerical, administrative, investigative, and other staff as needed to implement this chapter to serve as examiners for any practical examinations;

. Determine minimum education requirements and evaluate and designate those educational programs from which graduation will be accepted as proof of eligibility to take a qualifying examination for applicants for obtaining a license;

. Establish practice parameters consistent with the practice of genetic counseling as defined in RCW 18.290.010 and considering developments in the field, with the advice and recommendations of the *advisory committee;

. Prepare, grade, and administer, or determine the nature of, and supervise the grading and administration of examinations for obtaining a license;

. Determine which states have licensing requirements equivalent to those of this state, and issue licenses to applicants licensed in those states without examination;

. Define and approve any experience requirement for licensing;

. Adopt rules implementing a continuing competency program;

. Maintain the official department record of all applicants and license holders; and

. Establish by rule the procedures for an appeal of an examination failure.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5608-S.SL.pdf?cite=2009%20c%20302%20§%202[2009 c 302 § 2]; ]

== 18.290.030 - Construction.
Nothing in this chapter shall be construed to prohibit or restrict:

. An individual who holds a credential issued by this state, other than as a genetic counselor, to engage in the practice of that occupation or profession without obtaining an additional credential from the state. The individual may not use the title genetic counselor unless licensed as such in this state;

. The practice of genetic counseling by a person who is employed by the government of the United States while engaged in the performance of duties prescribed by the laws of the United States;

. The practice of genetic counseling by a person who is a regular student in an educational program approved by the secretary, and whose performance of services is pursuant to a regular course of instruction or assignments from an instructor and under the general supervision of the instructor; or

. The practice of genetic counseling by a person who is practicing under the general supervision of a genetic counselor in a genetic counseling training site while gathering logbook cases for the purpose of meeting licensing requirements.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5608-S.SL.pdf?cite=2009%20c%20302%20§%203[2009 c 302 § 3]; ]

== 18.290.040 - Licensing requirements.
The secretary shall issue a license to any applicant who demonstrates to the satisfaction of the secretary that the applicant meets the following requirements:

. Graduation from a master's or doctorate program in genetic counseling or medical genetics approved by the secretary;

. Successful completion of any clinical experience requirements established by the secretary; and

. Successful completion of an examination administered or approved by the secretary.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5608-S.SL.pdf?cite=2009%20c%20302%20§%204[2009 c 302 § 4]; ]

== 18.290.050 - Examinations.
. The date and location of examinations must be established by the secretary. Applicants who have been found by the secretary to meet the other requirements for obtaining a license must be scheduled for the next examination following the filing of the application. The secretary shall establish by rule the examination application deadline.

. The secretary or the secretary's designees shall examine each applicant, by means determined most effective, on subjects appropriate to the scope of practice, as applicable. The examinations must be limited to the purpose of determining whether the applicant possesses the minimum skill and knowledge necessary to practice competently.

. The examination papers, all grading of the papers, and the grading of any practical work shall be preserved for a period of not less than one year after the secretary has made and published the decisions. All examinations must be conducted under fair and wholly impartial methods.

. Any applicant failing to make the required grade in the first examination may take up to two subsequent examinations as the applicant desires upon prepaying a fee determined by the secretary under RCW 43.70.250 for each subsequent examination. Upon failing four examinations, the secretary may invalidate the original application and require remedial education before the person may take future examinations.

. The secretary may approve an examination prepared or administered by a private organization that certifies and recertifies genetic counselors, or an association of licensing agencies, for use by an applicant in meeting the credentialing requirements.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5608-S.SL.pdf?cite=2009%20c%20302%20§%206[2009 c 302 § 6]; ]

== 18.290.060 - Applications for licensing.
Applications for licensing must be submitted on forms provided by the secretary. The secretary may require any information and documentation that reasonably relates to the need to determine whether the applicant meets the criteria for licensing provided for in this chapter and chapter 18.130 RCW. Each applicant shall pay a fee determined by the secretary under RCW 43.70.250. The fee must accompany the application.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5608-S.SL.pdf?cite=2009%20c%20302%20§%207[2009 c 302 § 7]; ]

== 18.290.070 - License renewals.
The secretary shall establish by rule the requirements and fees for renewal of a license. Failure to renew the license invalidates the license and all privileges granted by the license. If a license has lapsed for a period longer than three years, the person shall demonstrate competence to the satisfaction of the secretary by completing continuing competency requirements or meeting other standards determined by the secretary.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5608-S.SL.pdf?cite=2009%20c%20302%20§%208[2009 c 302 § 8]; ]

== 18.290.080 - Provisional licenses.
The secretary may grant a provisional license to a person who has met all of the requirements for obtaining a license except for the successful completion of an examination. A provisional license must be renewed annually. The secretary may grant a provisional license to a person up to four times. A provisional license holder may only practice genetic counseling under the supervision of either a licensed genetic counselor, a physician licensed under chapter 18.71 RCW, or osteopathic physician licensed under chapter 18.57 RCW, with a current certification in clinical genetics issued by an organization approved by the secretary.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5608-S.SL.pdf?cite=2009%20c%20302%20§%209[2009 c 302 § 9]; ]

== 18.290.090 - Reciprocity.
An applicant holding a license in another state may be licensed to practice in this state without examination if the secretary determines that the licensing standards of the other state are substantially equivalent to the licensing standards of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5608-S.SL.pdf?cite=2009%20c%20302%20§%2010[2009 c 302 § 10]; ]

== 18.290.100 - Prohibited practices.
. Except as provided in RCW 18.290.030, no person shall engage in the practice of genetic counseling unless he or she is licensed, or provisionally licensed, under this chapter.

. A person not licensed with the secretary to practice genetic counseling may not represent himself or herself as a "licensed genetic counselor or a genetic counselor."

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5608-S.SL.pdf?cite=2009%20c%20302%20§%2011[2009 c 302 § 11]; ]

== 18.290.110 - Application of uniform disciplinary act.
The uniform disciplinary act, chapter 18.130 RCW, governs unlicensed practice, the issuance and denial of a license, and the discipline of persons licensed under this chapter. The secretary shall be the disciplining authority under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5608-S.SL.pdf?cite=2009%20c%20302%20§%2012[2009 c 302 § 12]; ]

== 18.290.120 - Down syndrome—Parent information.
A genetic counselor who provides a parent with a positive prenatal or postnatal diagnosis of Down syndrome shall provide the parent with the information prepared by the department under RCW 43.70.738 at the time the genetic counselor provides the parent with the Down syndrome diagnosis.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2403.SL.pdf?cite=2016%20c%2070%20§%208[2016 c 70 § 8]; ]

== 18.290.900 - Effective date—2009 c 302.
This act takes effect August 1, 2010.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5608-S.SL.pdf?cite=2009%20c%20302%20§%2015[2009 c 302 § 15]; ]

== 18.290.901 - Implementation—2009 c 302.
The secretary of health may adopt such rules as authorized under RCW 18.290.020 to ensure that chapter 302, Laws of 2009 is implemented on its effective date.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5608-S.SL.pdf?cite=2009%20c%20302%20§%2016[2009 c 302 § 16]; ]

