= 18.210 - On-site wastewater treatment systems—Designer licensing.
:toc:

== 18.210.005 - Findings—Purpose—Prohibition.
. In order to safeguard life, health, and property and to promote the public welfare, the legislature finds that it is in the public interest to permit the limited practice of engineering by qualified individuals who are not registered as professional engineers under chapter 18.43 RCW. The increased complexity of on-site wastewater treatment systems, changes in treatment technology, and the need to protect groundwater and watershed areas make it essential that qualified professionals design the systems. Furthermore, the legislature finds that individuals who have been authorized by local health jurisdictions to design on-site wastewater treatment systems have performed these designs in the past. However, it is desirable to establish a statewide licensing program to create uniform application of design practices, standards for designs, individual qualifications, and consistent enforcement efforts applicable to all persons who design on-site wastewater treatment systems, including persons licensed to practice as professional engineers under chapter 18.43 RCW. It is further desirable to establish a certification program applicable to all persons who inspect or approve on-site wastewater treatment systems on behalf of a local health jurisdiction.

. It is unlawful for any individual to practice or offer to practice the design of on-site wastewater treatment systems unless licensed in accordance with this chapter or licensed as a professional engineer under chapter 18.43 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5821-S2.SL.pdf?cite=1999%20c%20263%20§%201[1999 c 263 § 1]; ]

== 18.210.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Board" means the board of registration for professional engineers and land surveyors as defined in chapter 18.43 RCW.

. "Certificate of competency" or "certificate" means a certificate issued to employees of local health jurisdictions indicating that the certificate holder has passed the licensing examination required under this chapter.

. "Designer" or "licensee" means an individual authorized under this chapter to perform design services for on-site wastewater treatment systems.

. "Director" means the executive director of the Washington state board of registration for professional engineers and land surveyors.

. "Engineer" means a professional engineer licensed under chapter 18.43 RCW.

. "License" means a license to design on-site wastewater treatment systems under this chapter.

. "Local health jurisdiction" or "jurisdictional health department" means an administrative agency created under chapter 70.05, 70.08, or 70.46 RCW, that administers the regulation and codes regarding on-site wastewater treatment systems.

. "On-site wastewater design" means the development of plans, details, specifications, instructions, or inspections by application of specialized knowledge in analysis of soils, on-site wastewater treatment systems, disposal methods, and technologies to create an integrated system of collection, transport, distribution, treatment, and disposal of on-site wastewater.

. "On-site wastewater treatment system" means an integrated system of components that: Convey, store, treat, and/or provide subsurface soil treatment and disposal of wastewater effluent on the property where it originates or on adjacent or other property and includes piping, treatment devices, other accessories, and soil underlying the disposal component of the initial and reserve areas, for on-site wastewater treatment under three thousand five hundred gallons per day when not connected to a public sewer system.

. "Practice of engineering" has the meaning set forth in RCW 18.43.020(8).

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1176.SL.pdf?cite=2019%20c%20442%20§%2015[2019 c 442 § 15]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1061-S.SL.pdf?cite=2011%20c%20256%20§%201[2011 c 256 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2617-S2.SL.pdf?cite=2010%201st%20sp.s.%20c%207%20§%2076[2010 1st sp.s. c 7 § 76]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5821-S2.SL.pdf?cite=1999%20c%20263%20§%202[1999 c 263 § 2]; ]

== 18.210.020 - Unprofessional conduct.
In addition to the unprofessional conduct described in RCW 18.235.130, the following conduct, acts, and conditions constitute unprofessional conduct:

. Practicing with a *practice permit or license issued under this chapter that is expired, suspended, or revoked;

. Being willfully untruthful or deceptive in any document, report, statement, testimony, or plan that pertains to the design or construction of an on-site wastewater treatment system;

. Submission of a design or as-built record to a local health jurisdiction, to the department of health, or to the department of ecology, that is knowingly based upon false, incorrect, misleading, or fabricated information; and

. Submission of any application for licensure or certification that contains false, fraudulent, or misleading information.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1061-S.SL.pdf?cite=2011%20c%20256%20§%202[2011 c 256 § 2]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20256[2002 c 86 § 256]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5821-S2.SL.pdf?cite=1999%20c%20263%20§%203[1999 c 263 § 3]; ]

== 18.210.030 - Support order—License suspension.
The board shall immediately suspend the license of a person who has been certified pursuant to RCW 74.20A.320 by the department of social and health services as a person who is not in compliance with a support order. If the person has continued to meet all other requirements for a license under this chapter during the suspension, reissuance of the license or certificate shall be automatic upon the department's receipt of a release issued by the department of social and health services stating that the licensee is in compliance with the child support order. The procedure in RCW 74.20A.320 is the exclusive administrative remedy for contesting the establishment of noncompliance with a child support order, and suspension of a license under this section, and satisfies the requirements of RCW 34.05.422.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1061-S.SL.pdf?cite=2011%20c%20256%20§%203[2011 c 256 § 3]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20257[2002 c 86 § 257]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5821-S2.SL.pdf?cite=1999%20c%20263%20§%204[1999 c 263 § 4]; ]

== 18.210.050 - Board's authority.
The board may:

. Employ administrative, clerical, and investigative staff as necessary to administer and enforce this chapter;

. Establish fees for applications, examinations, and renewals in accordance with chapter 18.43 RCW;

. Issue licenses to applicants who meet the requirements of this chapter; and

. Exercise rule-making authority to implement this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1176.SL.pdf?cite=2019%20c%20442%20§%2016[2019 c 442 § 16]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1061-S.SL.pdf?cite=2011%20c%20256%20§%204[2011 c 256 § 4]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2617-S2.SL.pdf?cite=2010%201st%20sp.s.%20c%207%20§%2077[2010 1st sp.s. c 7 § 77]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5821-S2.SL.pdf?cite=1999%20c%20263%20§%206[1999 c 263 § 6]; ]

== 18.210.060 - Board—Authority—Duties.
The board may:

. Adopt rules to implement this chapter including, but not limited to, evaluation of experience, examinations, and scope and standards of practice;

. Administer licensing examinations; and

. Review and approve or deny initial and renewal license applications.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2617-S2.SL.pdf?cite=2010%201st%20sp.s.%20c%207%20§%2078[2010 1st sp.s. c 7 § 78]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20258[2002 c 86 § 258]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5821-S2.SL.pdf?cite=1999%20c%20263%20§%207[1999 c 263 § 7]; ]

== 18.210.080 - Immunity.
The director, members of the board, and individuals acting on behalf of the director or the board are immune to liability in any civil action or criminal case based on any acts performed in the course of their duties under this chapter, except for acts displaying intentional or willful misconduct.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1061-S.SL.pdf?cite=2011%20c%20256%20§%205[2011 c 256 § 5]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5821-S2.SL.pdf?cite=1999%20c%20263%20§%209[1999 c 263 § 9]; ]

== 18.210.100 - Written examination—Minimum requirements.
All applicants for licensure under this chapter, except as provided in RCW 18.210.180, must pass a written examination administered by the board and must also meet the following minimum requirements:

. A high school diploma or equivalent; and

. A minimum of four years of experience, as approved by the board, showing increased responsibility for the design of on-site wastewater treatment systems. The experience should include site soil assessment, hydraulics, topographic delineations, use of specialized treatment processes and devices, microbiology, and construction practices. Completion of satisfactory college-level coursework or successful participation in a board-approved internship or mentoring program may be substituted for up to two years of the experience requirement.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1061-S.SL.pdf?cite=2011%20c%20256%20§%206[2011 c 256 § 6]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5821-S2.SL.pdf?cite=1999%20c%20263%20§%2011[1999 c 263 § 11]; ]

== 18.210.110 - Experience from outside state.
Experience in on-site design, inspection, and/or construction activities acquired outside the state of Washington may satisfy the experience requirements under this chapter. The board shall consider the experience according to the level of complexity of the design work and evidence that the experience shows increased responsibility over designs. The experience may be considered only to the extent that it can be independently verified by the board.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5821-S2.SL.pdf?cite=1999%20c%20263%20§%2012[1999 c 263 § 12]; ]

== 18.210.120 - Application for licensure—References—Fees.
. Application for licensure must be on forms prescribed by the board and furnished by the director. The application must contain statements, made under oath, demonstrating the applicant's education and work experience.

. Applicants shall provide not less than two verifications of experience. Verifications of experience may be provided by licensed professional engineers, licensed on-site wastewater treatment system designers, or state/local regulatory officials in the on-site wastewater treatment field who have direct knowledge of the applicant's qualifications to practice in accordance with this chapter and who can verify the applicant's work experience.

. The board , shall determine an application fee for licensure as an on-site wastewater treatment system designer. A nonrefundable application fee must accompany the application. The board shall ensure that the application fee includes the cost of the examination and the cost issuance of a license and certificate. A candidate who fails an examination may apply for reexamination. The board shall determine the fee for reexamination.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1176.SL.pdf?cite=2019%20c%20442%20§%2017[2019 c 442 § 17]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1061-S.SL.pdf?cite=2011%20c%20256%20§%207[2011 c 256 § 7]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5821-S2.SL.pdf?cite=1999%20c%20263%20§%2013[1999 c 263 § 13]; ]

== 18.210.130 - Issuance of license.
. The director shall issue a license to any applicant who meets the requirements of this chapter. The issuance of a license by the director is evidence that the person named is entitled to the rights and privileges of a licensed on-site wastewater treatment system designer as long as the license remains valid.

. Each person licensed under this chapter shall obtain an inking stamp, of a design authorized by the board, that contains the licensee's name and license number. Plans, specifications, and reports prepared by the registrant must be signed, dated, and stamped. Signature and stamping constitute certification by the licensee that a plan, specification, or report was prepared by or under the direct supervision of a licensee.

. Those persons who obtain a certificate of competency as provided in *chapter 70.118 RCW do not have the privileges granted to a license holder under this chapter and do not have authority to obtain and use a stamp as described in this section.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5821-S2.SL.pdf?cite=1999%20c%20263%20§%2014[1999 c 263 § 14]; ]

== 18.210.140 - Renewal—Renewal fee—Penalty fee.
. Licenses and certificates issued under this chapter are valid for a period of time as determined by the board and may be renewed under the conditions described in this chapter. An expired license or certificate is invalid and must be renewed. Any licensee or certificate holder who fails to pay the renewal fee within ninety days following the date of expiration shall be assessed a penalty fee as determined by the board and must pay the penalty fee and the base renewal fee before the license or certificate may be renewed.

. Any license issued under this chapter that is not renewed within two years of its date of expiration must be canceled. Following cancellation, a person seeking to renew must reapply as a new applicant under this chapter.

. The board shall determine the fee for applications and for renewals of licenses and certificates issued under this chapter. For determining renewal fees, the pool of licensees and certificate holders under this chapter must be combined with the licensees established in chapter 18.43 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1176.SL.pdf?cite=2019%20c%20442%20§%2018[2019 c 442 § 18]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1061-S.SL.pdf?cite=2011%20c%20256%20§%208[2011 c 256 § 8]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5821-S2.SL.pdf?cite=1999%20c%20263%20§%2015[1999 c 263 § 15]; ]

== 18.210.150 - Persons exempt from licensure.
A person engaged in any of the following activities is not required to be licensed in accordance with this chapter:

. A licensed professional engineer, as provided in chapter 18.43 RCW, if the professional engineer performs the design work in accordance with this chapter and rules adopted under this chapter; or

. An employee or a subordinate of a person licensed under chapter 18.43 RCW as a professional engineer, or a person licensed under this chapter if the work is performed under the direct supervision of the engineer or licensee and does not include final design decisions.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5821-S2.SL.pdf?cite=1999%20c%20263%20§%2016[1999 c 263 § 16]; ]

== 18.210.160 - Prohibited practices—Penalty.
On or after July 1, 2003, it is a gross misdemeanor for any person, not otherwise exempt from the requirements of this chapter, to: (1) Perform on-site wastewater treatment systems design services without a license; (2) purport to be qualified to perform those services without having been issued a license under this chapter; (3) attempt to use the license or seal of another; (4) attempt to use a revoked or suspended license; or (5) attempt to use false or fraudulent credentials. In addition, action may be taken under RCW 18.235.150.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1061-S.SL.pdf?cite=2011%20c%20256%20§%209[2011 c 256 § 9]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20259[2002 c 86 § 259]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5821-S2.SL.pdf?cite=1999%20c%20263%20§%2017[1999 c 263 § 17]; ]

== 18.210.170 - Professional development.
The board shall require licensees under this chapter to maintain continuing professional development. The board may require these licensees to demonstrate maintenance of knowledge and skills as a condition of license renewal, including peer review of work products and periodic reexamination.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1061-S.SL.pdf?cite=2011%20c%20256%20§%2010[2011 c 256 § 10]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5821-S2.SL.pdf?cite=1999%20c%20263%20§%2018[1999 c 263 § 18]; ]

== 18.210.180 - Foreign jurisdiction—License without examination.
Any person holding a license issued by a jurisdiction outside the state of Washington authorizing that person to perform design services for site soil assessment, hydraulics, topographic delineations, use of specialized treatment processes and devices, microbiology, and construction practices of on-site wastewater treatment systems may be granted a license without examination under this chapter, if:

. The education, experience, and/or examination forming the basis of the license is determined by the board to be equal to or greater than the conditions for the issuance of a license under this chapter; and

. The individual has paid the applicable fee and has submitted the necessary application form.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1061-S.SL.pdf?cite=2011%20c%20256%20§%2011[2011 c 256 § 11]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5821-S2.SL.pdf?cite=1999%20c%20263%20§%2019[1999 c 263 § 19]; ]

== 18.210.190 - Local health jurisdictions—Certificate of competency—Fee.
. Employees of local health jurisdictions who review, inspect, or approve the design and construction of on-site wastewater treatment systems shall obtain a certificate of competency by obtaining a passing score on the written examination administered for licensure under this chapter. Eligibility to apply for the certificate of competency is based upon a written request from the local health director or designee and payment of a fee established by the director. The certificate of competency is renewable upon payment of a fee established by the director. Certificate holders are also subject to the requirements of RCW 18.210.140(1).

. Issuance of the certificate of competency does not authorize the certificate holder to offer or provide on-site wastewater treatment system design services. However, nothing in this chapter limits or affects the ability of local health jurisdictions to perform on-site design services under their authority in chapter 70.05 RCW.

. Local health jurisdictions and the state department of health retain authority to:

.. Administer state and local regulations and codes for approval or disapproval of designs for on-site wastewater treatment systems;

.. Issue permits for construction;

.. Evaluate soils and site conditions for compliance with code requirements; and

.. Perform on-site wastewater treatment design work as authorized in state and local board of health rules.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1061-S.SL.pdf?cite=2011%20c%20256%20§%2012[2011 c 256 § 12]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5821-S2.SL.pdf?cite=1999%20c%20263%20§%2020[1999 c 263 § 20]; ]

== 18.210.200 - Account—Budget request—Fees.
. The board shall set fees at a level adequate to pay the costs of administering this chapter. All fees and fines collected under this chapter shall be paid into the professional engineers' account established under RCW 18.43.150. Moneys in the account may be spent only after appropriation and must be used to carry out all the purposes and provisions of this chapter and chapter 18.43 RCW, including the cost of administering this chapter.

. The director shall biennially prepare a budget request based on the anticipated cost of administering licensing and certification activities. The budget request shall include the estimated income from fees contained in this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1176.SL.pdf?cite=2019%20c%20442%20§%2022[2019 c 442 § 22]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5821-S2.SL.pdf?cite=1999%20c%20263%20§%2021[1999 c 263 § 21]; ]

== 18.210.220 - Uniform regulation of business and professions act.
The uniform regulation of business and professions act, chapter 18.235 RCW, governs unlicensed practice, the issuance and denial of licenses, and the discipline of licensees under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20260[2002 c 86 § 260]; ]

== 18.210.230 - Military training or experience.
An applicant with military training or experience satisfies the training or experience requirements of this chapter unless the director determines that the military training or experience is not substantially equivalent to the standards of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1418.SL.pdf?cite=2011%20c%20351%20§%2013[2011 c 351 § 13]; ]

