= 18.205 - Substance use disorder professionals.
:toc:

== 18.205.010 - Substance use disorder professional certification.
The legislature recognizes substance use disorder professionals as discrete health professionals. Substance use disorder professional certification serves the public interest.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1768-S.SL.pdf?cite=2019%20c%20444%20§%201[2019 c 444 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6550-S.SL.pdf?cite=1998%20c%20243%20§%201[1998 c 243 § 1]; ]

== 18.205.020 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Agency" means (a) a community behavioral health agency or facility operated, licensed, or certified by the state of Washington; (b) a federally recognized Indian tribe located within the state; (c) a county; (d) a federally qualified health center; or (e) a hospital.

. "Certification" means a voluntary process recognizing an individual who qualifies by examination and meets established educational prerequisites, and which protects the title of practice.

. "Co-occurring disorder specialist" means an individual possessing an enhancement that certifies the individual to provide substance use disorder counseling subject to the practice limitations under RCW 18.205.105.

. "Committee" means the substance use disorder professional certification advisory committee established under this chapter.

. "Core competencies of substance use disorder counseling" means competency in the nationally recognized knowledge, skills, and attitudes of professional practice, including assessment and diagnosis of substance use disorders, substance use disorder treatment planning and referral, patient and family education in the disease of substance use disorders, individual and group counseling, relapse prevention counseling, and case management, all oriented to assist individuals with substance use disorder in their recovery.

. "Counseling" means employing any therapeutic techniques including, but not limited to, social work, mental health counseling, marriage and family therapy, and hypnotherapy, for a fee, that offer, assist, or attempt to assist an individual or individuals in the amelioration or adjustment of mental, emotional, or behavioral problems, and includes therapeutic techniques to achieve sensitivity and awareness of self and others and the development of human potential. For the purposes of this chapter, nothing may be construed to imply that the practice of hypnotherapy is necessarily limited to counseling.

. "Department" means the department of health.

. "Health profession" means a profession providing health services regulated under the laws of this state.

. "Recovery" means a process of change through which individuals improve their health and wellness, live self-directed lives, and strive to reach their full potential. Recovery often involves achieving remission from active substance use disorder.

. "Secretary" means the secretary of health or the secretary's designee.

. "Substance use disorder counseling" means employing the core competencies of substance use disorder counseling to assist or attempt to assist individuals with substance use disorder in their recovery.

. "Substance use disorder professional" means an individual certified in substance use disorder counseling under this chapter.

. "Substance use disorder professional trainee" means an individual working toward the education and experience requirements for certification as a substance use disorder professional.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1768-S.SL.pdf?cite=2019%20c%20444%20§%202[2019 c 444 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2674-S2.SL.pdf?cite=2008%20c%20135%20§%2015[2008 c 135 § 15]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6550-S.SL.pdf?cite=1998%20c%20243%20§%202[1998 c 243 § 2]; ]

== 18.205.030 - Title or description of services.
No person may represent oneself as a certified substance use disorder professional, certified substance use disorder professional trainee, or co-occurring disorder specialist or use any title or description of services of a certified substance use disorder professional, certified substance use disorder professional trainee, or co-occurring disorder specialist without applying for certification, meeting the required qualifications, and being certified by the department of health, unless otherwise exempted by this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1768-S.SL.pdf?cite=2019%20c%20444%20§%203[2019 c 444 § 3]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2674-S2.SL.pdf?cite=2008%20c%20135%20§%2016[2008 c 135 § 16]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2400.SL.pdf?cite=2000%20c%20171%20§%2041[2000 c 171 § 41]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6550-S.SL.pdf?cite=1998%20c%20243%20§%203[1998 c 243 § 3]; ]

== 18.205.050 - Practice not prohibited or restricted by chapter.
Nothing in this chapter shall be construed to prohibit or restrict:

. The practice by an individual licensed, certified, or registered under the laws of this state and performing services within the authorized scope of practice;

. The practice by an individual employed by the government of the United States while engaged in the performance of duties prescribed by the laws of the United States;

. The practice by a person who is a regular student in an educational program approved by the secretary, and whose performance of services is pursuant to a regular course of instruction or assignments from an instructor and under the general supervision of the instructor.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6550-S.SL.pdf?cite=1998%20c%20243%20§%205[1998 c 243 § 5]; ]

== 18.205.060 - Authority of secretary.
In addition to any other authority provided by law, the secretary has the authority to:

. Adopt rules under chapter 34.05 RCW necessary to implement this chapter, in consultation with the committee;

. Establish all certification, examination, and renewal fees in accordance with RCW 43.70.250;

. Establish forms and procedures necessary to administer this chapter;

. Issue certificates to applicants who have met the education, training, and examination requirements for certification and to deny certification to applicants who do not meet the minimum qualifications, except that proceedings concerning the denial of certification based upon unprofessional conduct or impairment shall be governed by the uniform disciplinary act, chapter 18.130 RCW;

. Hire clerical, administrative, investigative, and other staff as needed to implement this chapter, and hire individuals certified under this chapter to serve as examiners for any practical examinations;

. Determine minimum education requirements and evaluate and designate those educational programs that will be accepted as proof of eligibility to take a qualifying examination for applicants for certification;

. Prepare, grade, and administer, or determine the nature of, and supervise the grading and administration of, examinations for applicants for certification;

. Determine whether alternative methods of training are equivalent to formal education, and establish forms, procedures, and criteria for evaluation of an applicant's alternative training to determine the applicant's eligibility to take any qualifying examination;

. Determine which states have credentialing requirements equivalent to those of this state, and issue certificates to individuals credentialed in those states without examinations;

. Define and approve any experience requirement for certification;

. Implement and administer a program for consumer education;

. Adopt rules implementing a continuing competency program;

. Maintain the official department record of all applicants and certificated individuals;

. Establish by rule the procedures for an appeal of an examination failure; and

. Establish disclosure requirements.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6550-S.SL.pdf?cite=1998%20c%20243%20§%206[1998 c 243 § 6]; ]

== 18.205.070 - Official record of proceedings.
The secretary shall keep an official record of all proceedings. A part of the record shall consist of a register of all applicants for certification under this chapter and the results of each application.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6550-S.SL.pdf?cite=1998%20c%20243%20§%207[1998 c 243 § 7]; ]

== 18.205.080 - Substance use disorder certification advisory committee—Composition—Terms.
. The secretary shall appoint a substance use disorder certification advisory committee to further the purposes of this chapter. The committee shall be composed of seven members, one member initially appointed for a term of one year, three for a term of two years, and three for a term of three years. Subsequent appointments shall be for terms of three years. No person may serve as a member of the committee for more than two consecutive terms. Members of the committee shall be residents of this state. The committee shall be composed of four certified substance use disorder professionals; one substance use disorder treatment program director; one physician licensed under chapter 18.71 or 18.57 RCW who is certified in addiction medicine or a licensed or certified mental health practitioner; and one member of the public who has received substance use disorder counseling.

. The secretary may remove any member of the committee for cause as specified by rule. In the case of a vacancy, the secretary shall appoint a person to serve for the remainder of the unexpired term.

. The committee shall meet at the times and places designated by the secretary and shall hold meetings during the year as necessary to provide advice to the director. The committee may elect a chair and a vice chair. A majority of the members currently serving shall constitute a quorum.

. Each member of the committee shall be reimbursed for travel expenses as authorized in RCW 43.03.050 and 43.03.060. In addition, members of the committee shall be compensated in accordance with RCW 43.03.240 when engaged in the authorized business of the committee.

. The director of the health care authority, or his or her designee, shall serve as an ex officio member of the committee.

. The secretary, members of the committee, or individuals acting on their behalf are immune from suit in any action, civil or criminal, based on any certification or disciplinary proceedings or other official acts performed in the course of their duties.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1768-S.SL.pdf?cite=2019%20c%20444%20§%204[2019 c 444 § 4]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1388-S.SL.pdf?cite=2018%20c%20201%20§%209007[2018 c 201 § 9007]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6550-S.SL.pdf?cite=1998%20c%20243%20§%208[1998 c 243 § 8]; ]

== 18.205.090 - Certification requirements.
. The secretary shall issue a certificate to any applicant who demonstrates to the secretary's satisfaction that the following requirements have been met:

.. Completion of:

... An educational program approved by the secretary;

... An apprenticeship program reviewed by the substance use disorder certification advisory committee, approved by the secretary, and registered and approved under chapter 49.04 RCW; or

... Alternate training that meets established criteria;

.. Successful completion of an approved examination, based on core competencies of substance use disorder counseling; and

.. Successful completion of an experience requirement that establishes fewer hours of experience for applicants with higher levels of relevant education. In meeting any experience requirement established under this subsection, the secretary may not require more than one thousand five hundred hours of experience in substance use disorder counseling for applicants who are licensed under chapter 18.83 RCW or under chapter 18.79 RCW as advanced registered nurse practitioners.

. The secretary shall establish by rule what constitutes adequate proof of meeting the criteria.

. Applicants are subject to the grounds for denial of a certificate or issuance of a conditional certificate under chapter 18.130 RCW.

. Certified substance use disorder professionals shall not be required to be registered under chapter 18.19 RCW or licensed under chapter 18.225 RCW.

. As of July 28, 2019, a person certified under this chapter holding the title of chemical dependency professional is considered to hold the title of substance use disorder professional until such time as the person's present certification expires or is renewed.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1311.SL.pdf?cite=2021%20c%20165%20§%202[2021 c 165 § 2]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1768-S.SL.pdf?cite=2019%20c%20444%20§%205[2019 c 444 § 5]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5877-S.SL.pdf?cite=2001%20c%20251%20§%2030[2001 c 251 § 30]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6550-S.SL.pdf?cite=1998%20c%20243%20§%209[1998 c 243 § 9]; ]

== 18.205.095 - Certification requirements—Trainees.
. The secretary shall issue a trainee certificate to any applicant who demonstrates to the satisfaction of the secretary that he or she is working toward the education and experience requirements in RCW 18.205.090.

. A trainee certified under this section shall submit to the secretary for approval a declaration, in accordance with rules adopted by the department, which shall be updated with the trainee's annual renewal, that he or she is actively pursuing the experience requirements under RCW 18.205.090 and is enrolled in:

.. An approved education program; or

.. An apprenticeship program reviewed by the substance use disorder certification advisory committee, approved by the secretary, and registered and approved under chapter 49.04 RCW.

. A trainee certified under this section may practice only under the supervision of a certified substance use disorder professional. The first 50 hours of any face-to-face client contact must be under direct observation. All remaining experience must be under supervision in accordance with rules adopted by the department.

. A certified substance use disorder professional trainee provides substance use disorder assessments, counseling, and case management with a state regulated agency and can provide clinical services to patients consistent with his or her education, training, and experience as approved by his or her supervisor.

. A trainee certification may only be renewed four times, unless the secretary finds that a waiver to allow additional renewals is justified due to barriers to testing or training resulting from a governor-declared emergency.

. Applicants are subject to denial of a certificate or issuance of a conditional certificate for the reasons set forth in chapter 18.130 RCW.

. A person certified under this chapter holding the title of chemical dependency professional trainee is considered to hold the title of substance use disorder professional trainee until such time as the person's present certification expires or is renewed.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1311.SL.pdf?cite=2021%20c%20165%20§%201[2021 c 165 § 1]; http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1063.SL.pdf?cite=2021%20c%2057%20§%201[2021 c 57 § 1]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1768-S.SL.pdf?cite=2019%20c%20444%20§%206[2019 c 444 § 6]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2674-S2.SL.pdf?cite=2008%20c%20135%20§%2018[2008 c 135 § 18]; ]

== 18.205.097 - Certification—Impermissible grounds for denial.
The department may not automatically deny an applicant for certification under this chapter for a position as a substance use disorder professional or substance use disorder professional trainee based on a conviction history consisting of convictions for simple assault, assault in the fourth degree, prostitution, theft in the third degree, theft in the second degree, or forgery, the same offenses as they may be renamed, or substantially equivalent offenses committed in other states or jurisdictions if:

. At least one year has passed between the applicant's most recent conviction for an offense set forth in this section and the date of application for employment;

. The offense was committed as a result of the person's substance use or untreated mental health symptoms; and

. The applicant is at least one year in recovery from a substance use disorder, whether through abstinence or stability on medication-assisted therapy, or in recovery from mental health challenges.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1768-S.SL.pdf?cite=2019%20c%20444%20§%2023[2019 c 444 § 23]; ]

== 18.205.100 - Educational programs and alternative training—Supervision—Standards and procedures—Established by rule.
The secretary may establish by rule the standards and procedures for approval of educational programs and alternative training. The requirements for who may provide approved supervision towards training must be the same for all applicants in the regular or alternative training pathways. The requirements for who may provide approved supervision towards training must allow approved supervision to be provided by a person who meets or exceeds the requirements of a certified substance use disorder professional in the state of Washington and who would be eligible to take the examination required for certification. The secretary may utilize or contract with individuals or organizations having expertise in the profession or in education to assist in the evaluations. The secretary shall establish by rule the standards and procedures for revocation of approval of educational programs. The standards and procedures set shall apply equally to educational programs and training in the United States and in foreign jurisdictions. The secretary may establish a fee for educational program evaluations.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1768-S.SL.pdf?cite=2019%20c%20444%20§%207[2019 c 444 § 7]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2400.SL.pdf?cite=2000%20c%20171%20§%2042[2000 c 171 § 42]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6550-S.SL.pdf?cite=1998%20c%20243%20§%2010[1998 c 243 § 10]; ]

== 18.205.102 - Education requirements—Secretary to define.
All education requirements established as defined by the secretary under RCW 18.205.100 credited by an approved education program for participants in the apprenticeship program for substance use disorder professionals must meet or exceed competency requirements established by the secretary.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1311.SL.pdf?cite=2021%20c%20165%20§%204[2021 c 165 § 4]; ]

== 18.205.105 - Co-occurring disorder specialist enhancement—Training standards.
. The department shall develop training standards for the creation of a co-occurring disorder specialist enhancement which may be added to the license or registration held by one of the following:

.. Psychologists licensed under chapter 18.83 RCW;

.. Independent clinical social workers licensed under chapter 18.225 RCW;

.. Marriage and family therapists licensed under chapter 18.225 RCW;

.. Mental health counselors licensed under chapter 18.225 RCW; and

.. An agency affiliated counselor under chapter 18.19 RCW with a master's degree or further advanced degree in counseling or one of the social sciences from an accredited college or university who has at least two years of experience, experience gained under the supervision of a mental health professional recognized by the department or attested to by the licensed behavioral health agency, in direct treatment of persons with mental illness or emotional disturbance.

. To obtain the co-occurring disorder specialist enhancement, the applicant must meet training standards and experience requirements. The training standards must be designed with consideration of the practices of the health professions listed in subsection (1) of this section and consisting of sixty hours of instruction consisting of (a) thirty hours in understanding the disease pattern of addiction and the pharmacology of alcohol and other drugs; and (b) thirty hours in understanding addiction placement, continuing care, and discharge criteria, including the American society of addiction medicine criteria; treatment planning specific to substance abuse; relapse prevention; and confidentiality issues specific to substance use disorder treatment.

. In developing the training standards, the department shall consult with the examining board of psychology established in chapter 18.83 RCW, the Washington state mental health counselors, marriage and family therapists, and social workers advisory committee established in chapter 18.225 RCW, the substance use disorder certification advisory committee established in chapter 18.205 RCW, and educational institutions in Washington state that train psychologists, marriage and family therapists, mental health counselors, independent clinical social workers, and substance use disorder professionals.

. The department shall approve educational programs that meet the training standards, and must not limit its approval to university-based courses.

. The secretary shall issue a co-occurring disorder specialist enhancement to any applicant who demonstrates to the secretary's satisfaction that the following requirements have been met:

.. Completion of the training standards;

.. Successful completion of an approved examination based on core competencies of substance use disorder counseling;

.. Successful completion of an experience requirement of:

... Eighty hours of supervised experience for an applicant listed under subsection (1) of this section with fewer than five years of experience; or

... Forty hours of supervised experience for an applicant listed under subsection (1) of this section with five or more years of experience; and

.. Payment of any fees that may be established by the department.

. An applicant for the co-occurring disorder specialist enhancement may receive supervised experience from any person who meets or exceeds the requirements of a certified substance use disorder professional in the state of Washington and who would be eligible to take the examination required for substance use disorder professional certification.

. A person who has obtained a co-occurring disorder specialist enhancement may provide substance use disorder counseling services which are equal in scope with those provided by substance use disorder professionals under this chapter, subject to the following limitations:

.. A co-occurring disorder specialist may only provide substance use disorder counseling services if the co-occurring disorder specialist is employed by:

... An agency that provides counseling services;

... A federally qualified health center; or

... A hospital;

.. Following an initial intake or assessment, a co-occurring disorder specialist may provide substance use disorder treatment only to clients diagnosed with a substance use disorder and a mental health disorder;

.. Prior to providing substance use disorder treatment to a client assessed to be in need of 2.1 or higher level of care according to American society of addiction medicine criteria, a co-occurring disorder specialist must make a reasonable effort to refer and connect the client to the appropriate care setting, as indicated by the client's American society of addiction medicine level of care; and

.. A co-occurring disorder specialist must comply with rules promulgated by the department under subsection (11) of this section.

. The secretary shall establish by rule what constitutes adequate proof of meeting the criteria.

. Applicants are subject to the grounds for denial of a certificate or issuance of a conditional certificate under chapter 18.130 RCW.

. The department may adopt a fee to defray the cost of regulatory activities related to the issuance of co-occurring disorder specialist enhancements and any related disciplinary activities.

. The department shall adopt rules regarding the role of co-occurring disorder specialists across the American society of addiction medicine continuum of care.

. Any increase in fees necessary to cover the cost of regulating co-occurring disorder professionals [specialists] who receive an enhancement under this section must be borne by persons licensed as psychologists under chapter 18.83 RCW, independent clinical social workers under chapter 18.225 RCW, marriage and family therapists under chapter 18.225 RCW, or mental health counselors under chapter 18.225 RCW. The cost of regulating co-occurring disorder specialists who receive an enhancement under this section may not be borne by substance use disorder professionals or substance use disorder professional trainees certified under this chapter and may not be included in the calculation of fees for substance use disorder professionals or substance use disorder professional trainees certified under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1768-S.SL.pdf?cite=2019%20c%20444%20§%2025[2019 c 444 § 25]; ]

== 18.205.107 - Co-occurring disorder specialist enhancement—Contracted educational program—Telephonic consultation service. (Expires July 1, 2025.)
. Beginning July 1, 2020, subject to the availability of amounts appropriated for this specific purpose, the department shall contract with an educational program to offer the training developed under RCW 18.205.105. The contracted educational program shall offer the training at a reduced cost to health care providers identified in RCW 18.205.105. The training must be (a) available online on an ongoing basis and (b) offered in person at least four times per calendar year.

. Beginning July 1, 2020, subject to the availability of amounts appropriated for this specific purpose, the department shall contract with an entity to provide a telephonic consultation service to assist health care providers who have been issued a substance use disorder professional certification pursuant to RCW 18.205.090 or a co-occurring disorder specialist enhancement under RCW 18.205.105 with the diagnosis and treatment of patients with co-occurring behavioral health disorders.

. The department shall identify supervisors who are trained and available to supervise persons seeking to meet the supervised experience requirements established under RCW 18.205.105.

. This section expires July 1, 2025.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1768-S.SL.pdf?cite=2019%20c%20444%20§%2026[2019 c 444 § 26]; ]

== 18.205.110 - Examination.
. The date and location of examinations shall be established by the secretary. Applicants who have been found by the secretary to meet the other requirements for certification shall be scheduled for the next examination following the filing of the application. The secretary shall establish by rule the examination application deadline.

. The secretary or the secretary's designees shall examine each applicant, by means determined most effective, on subjects appropriate to the scope of practice, as applicable. Such examinations shall be limited to the purpose of determining whether the applicant possesses the minimum skill and knowledge necessary to practice competently.

. The examination papers, all grading of the papers, and the grading of any practical work shall be preserved for a period of not less than one year after the secretary has made and published the decisions. All examinations shall be conducted under fair and wholly impartial methods.

. Any applicant failing to make the required grade in the first examination may take up to three subsequent examinations as the applicant desires upon prepaying a fee determined by the secretary under RCW 43.70.250 for each subsequent examination. Upon failing four examinations, the secretary may invalidate the original application and require such remedial education before the person may take future examinations.

. The secretary may approve an examination prepared or administered by a private testing agency or association of licensing agencies for use by an applicant in meeting the certification requirements.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6550-S.SL.pdf?cite=1998%20c%20243%20§%2011[1998 c 243 § 11]; ]

== 18.205.120 - Application for certification—Fee.
Applications for certification shall be submitted on forms provided by the secretary. The secretary may require any information and documentation that reasonably relates to the need to determine whether the applicant meets the criteria for certification provided for in this chapter and chapter 18.130 RCW. Each applicant shall pay a fee determined by the secretary under RCW 43.70.250. The fee shall accompany the application.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6550-S.SL.pdf?cite=1998%20c%20243%20§%2012[1998 c 243 § 12]; ]

== 18.205.130 - Waiver of examination—Certification of applicants—Intent.
. Within two years after July 1, 1999, the secretary shall waive the examination and certify a person who pays a fee and produces a valid chemical dependency counselor certificate of qualification from the department of social and health services.

. Within two years after July 1, 1999, the secretary shall waive the examination and certify applicants who are licensed under chapter 18.83 RCW or under chapter 18.79 RCW as advanced registered nurse practitioners who pay a fee, who document completion of courses substantially equivalent to those required of chemical dependency counselors working in programs approved under *chapter 70.96A RCW on July 1, 1999, and who provide evidence of one thousand five hundred hours of experience in chemical dependency counseling.

. It is the intent of the legislature that the credentialing of chemical dependency professionals be established solely by the department.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6550-S.SL.pdf?cite=1998%20c%20243%20§%2013[1998 c 243 § 13]; ]

== 18.205.140 - Applicant credentialed in another state—Certification without examination—Reciprocity program.
. An applicant holding a credential in another state may be certified to practice in this state without examination if the secretary determines that the other state's credentialing standards are substantially equivalent to the standards in this state.

. [Empty]
.. [Empty]
... The department shall establish a reciprocity program for applicants for certification as a chemical dependency professional in Washington.

... The reciprocity program applies to applicants for certification as a chemical dependency professional who:

(A) Hold or have held within the past twelve months a credential in good standing from another state or territory of the United States which has a scope of practice that is substantially equivalent to or greater than the scope of practice for certified chemical dependency professionals as established under this chapter; and

(B) Have no disciplinary record or disqualifying criminal history.

.. The department shall issue a probationary certificate to an applicant who meets the requirements of (a)(ii) of this subsection. The department must determine what deficiencies, if any, exist between the education and experience requirements of the other state's credential and, after consideration of the experience and capabilities of the applicant, determine whether it is appropriate to require the applicant to complete additional education or experience requirements to maintain the probationary certificate and, within a reasonable time period, transition to a full certificate. A person who holds a probationary certificate may only practice as a chemical dependency professional in a licensed or certified service provider, as defined in *RCW 71.24.025. The department may place a reasonable time limit on a probationary certificate and may, if appropriate, require the applicant to pass a jurisprudential examination.

.. The department must maintain and publish a list of credentials in other states and territories that the department has determined to have a scope of practice that is substantially equivalent to or greater than the scope of practice for certified chemical dependency professionals as established under this chapter. The department shall prioritize identifying and publishing the department's determination for the five states or territories that have historically had the most applicants for reciprocity under subsection (1) of this section with a scope of practice that is substantially equivalent to or greater than the scope of practice for certified chemical dependency professionals as established under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5054.SL.pdf?cite=2019%20c%20351%20§%202[2019 c 351 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6550-S.SL.pdf?cite=1998%20c%20243%20§%2014[1998 c 243 § 14]; ]

== 18.205.150 - Uniform disciplinary act.
The uniform disciplinary act, chapter 18.130 RCW, shall govern the issuance and denial of certificates, unauthorized practice, and the discipline of persons certified under this chapter. The secretary shall be the disciplining authority under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6550-S.SL.pdf?cite=1998%20c%20243%20§%2015[1998 c 243 § 15]; ]

== 18.205.160 - Co-occurring disorder specialist enhancement—Substance use disorder counseling services.
The department of health must amend its rules, including WAC 246-341-0515, to allow persons with a co-occurring disorder specialist enhancement under chapter 18.205 RCW to provide substance use disorder counseling services that are equal in scope with the scope and practice of a substance use disorder professional under chapter 18.205 RCW, subject to the practice limitations under RCW 18.205.105.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1768-S.SL.pdf?cite=2019%20c%20444%20§%2029[2019 c 444 § 29]; ]

== 18.205.170 - Co-occurring disorder specialist enhancement—Review, analysis, and report.
. The department, in collaboration with the behavioral health institute at the University of Washington, the research and data analysis division at the department of social and health services, and the division of behavioral health and recovery at the health care authority, must conduct a review and analysis regarding the effects of the co-occurring disorder specialist enhancement created by chapter 444, Laws of 2019 on increasing the number of providers qualified to provide substance use disorder services and improving outcomes for persons with a substance use disorder.

. The review and analysis shall assess:

.. The effects of the availability of the co-occurring disorder specialist enhancement on:

... Increasing the number of providers qualified to provide substance use disorder services; and

... Improving outcomes for persons with a substance use disorder;

.. The number of co-occurring disorder specialist enhancements that have been issued;

.. The settings in which co-occurring disorder specialists are working;

.. The geographic distribution of co-occurring disorder specialists;

.. Any change in the number of certified substance use disorder professionals and substance use disorder professional trainees;

.. Any change in the number of people receiving treatment at the appropriate level of care, including:

... The number of American society of addiction medicine assessments made by co-occurring disorder specialists;

... The assessed level of care for clients according to American society of addiction medicine criteria;

... Co-occurring mental health diagnoses for clients receiving services from a co-occurring disorder specialist;

... The number of referrals made by co-occurring disorder specialists, by American society of addiction medicine level; and

.. The number of successful placements made by co-occurring disorder specialists; and

.. Any other factors relevant to assessing the effects of the availability of the co-occurring disorder specialist enhancement on the behavioral health workforce and the provision of appropriate services to clients.

. The agencies listed in subsection (1) of this section must develop the tools necessary to conduct the review and analysis required by this section.

. By December 1, 2022, the department shall submit a preliminary report of the findings of its review and analysis and any recommendations for improving the qualifications for an enhancement or the practice of those who have been issued an enhancement, and a final report by December 1, 2024.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1768-S.SL.pdf?cite=2019%20c%20444%20§%2030[2019 c 444 § 30]; ]

== 18.205.900 - Effective dates—1998 c 243.
This act takes effect July 1, 1998, except for sections 3, 9, 13, and 14 of this act, which take effect July 1, 1999.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6550-S.SL.pdf?cite=1998%20c%20243%20§%2018[1998 c 243 § 18]; ]

