= 18.240 - Animal massage therapists.
:toc:

== 18.240.005 - Finding.
The certification of animal massage therapists is in the interest of the public health, safety, and welfare. While veterinarians and certain massage therapists may perform animal massage techniques, the legislature finds that meeting all of the requirements of those professions can be unnecessarily cumbersome for those individuals who would like to limit their practice only to animal massage.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2425-S.SL.pdf?cite=2016%20c%2041%20§%2019[2016 c 41 § 19]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5403-S.SL.pdf?cite=2007%20c%2070%20§%201[2007 c 70 § 1]; ]

== 18.240.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Board" means the veterinary board of governors established in chapter 18.92 RCW.

. "Certified animal massage therapist" means an individual who provides external manipulation or pressure of soft tissues by use of the hands, body, or device designed and limited to providing massage. Animal massage may include techniques such as stroking, percussions, compressions, friction, Swedish gymnastics or movements, gliding, kneading, range of motion or stretching, and fascial or connective tissue stretching, with or without the aid of superficial heat, cold, water, lubricants, or salts. Animal massage does not include: Diagnosis, prognosis, or all treatment of diseases, deformities, defects, wounds, or injuries of animals; attempts to adjust or manipulate any articulations of the animal's body or spine or mobilization of these articulations by the use of a thrusting force; acupuncture involving the use of needles; or mechanical therapies that are restricted to the field of veterinary medicine. Animal massage may be performed solely for purposes of patient well-being.

. "Department" means the department of health.

. "Secretary" means the secretary of health or the secretary's designee.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2425-S.SL.pdf?cite=2016%20c%2041%20§%2020[2016 c 41 § 20]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5403-S.SL.pdf?cite=2007%20c%2070%20§%202[2007 c 70 § 2]; ]

== 18.240.020 - Certification required.
No person may practice as a certified animal massage therapist in this state without having a certification issued by the secretary unless he or she is exempt under RCW 18.240.040.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2425-S.SL.pdf?cite=2016%20c%2041%20§%2021[2016 c 41 § 21]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5403-S.SL.pdf?cite=2007%20c%2070%20§%203[2007 c 70 § 3]; ]

== 18.240.030 - Certification requirements.
The secretary shall issue a certificate to any applicant who demonstrates that the following requirements have been met:

. Successful completion of a training program approved by the secretary that includes three hundred hours of instruction in general animal massage techniques, kinesiology, anatomy, physiology, behavior, first aid care, and handling techniques as follows:

.. For a certificate to practice animal massage on large animals, the three hundred hours of specialized instruction must be related to the performance of animal massage on large animals; and

.. For a certificate to practice animal massage on small animals, the three hundred hours of specialized instruction must be related to the performance of animal massage on small animals; and

. Successful completion of a competency evaluation, approved by the secretary, in either large animal massage or small animal massage, or both.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5403-S.SL.pdf?cite=2007%20c%2070%20§%204[2007 c 70 § 4]; ]

== 18.240.040 - Limitation of chapter.
Nothing in this chapter may be construed to prohibit or restrict:

. The practice of veterinary medicine by those who are in compliance with chapter 18.92 RCW;

. The practice of animal massage by those who are in compliance with chapter 18.108 RCW;

. The practice of animal massage therapy by a person who is a regular student in an educational program whose performance of services is pursuant to a regular course of instruction or assignments from an instructor and under the general supervision of the instructor; or

. The use of animal massage techniques by the owner of the animal who is the recipient of the services or by an employee of the owner or another person providing gratuitous assistance.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5403-S.SL.pdf?cite=2007%20c%2070%20§%205[2007 c 70 § 5]; ]

== 18.240.050 - Secretary's authority.
In addition to any other authority provided by law, the secretary has the authority to:

. Adopt rules under chapter 34.05 RCW as required to implement this chapter;

. Establish all certification and renewal fees in accordance with RCW 43.70.110 and 43.70.250;

. Establish forms and procedures necessary to administer this chapter;

. Certify an applicant or deny certification based upon unprofessional conduct or impairment governed by the uniform disciplinary act, chapter 18.130 RCW;

. Deny certification to applicants who do not meet the training, competency evaluation, and conduct requirements for certification;

. Hire clerical, administrative, investigative, and other staff as needed to implement this chapter;

. Maintain the official department record for all applicants and persons with certifications;

. Review coursework and training taken by an applicant in another state to determine whether it is substantially equivalent to that required under this chapter and determine whether additional coursework or training is needed before taking an examination for certification under RCW 18.240.060;

. Approve education and training programs; and

. Convene temporary work groups of individuals knowledgeable in the practice of animal massage to advise the secretary on appropriate standards of practice and credentialing, as necessary.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5403-S.SL.pdf?cite=2007%20c%2070%20§%206[2007 c 70 § 6]; ]

== 18.240.060 - Examinations.
. The date and location of examinations must be established by the secretary. Applicants who have been found by the secretary to meet the other requirements for obtaining a certificate must be scheduled for the next examination following the filing of the application. The secretary shall establish by rule the examination application deadline.

. The secretary shall examine each applicant, by means determined most effective, on subjects appropriate to the scope of practice, as applicable. The examinations must be limited to the purpose of determining whether the applicant possesses the minimum skill and knowledge necessary to practice competently.

. The examination papers, all grading of the papers, and the grading of any practical work must be preserved for a period of not less than one year after the secretary has made and published the decisions. All examinations must be conducted under fair and wholly impartial methods.

. Any applicant failing to make the required grade in the first examination may take up to three subsequent examinations as the applicant desires upon prepaying a fee determined by the secretary under RCW 43.70.250 for each subsequent examination. Upon failing four examinations, the secretary may invalidate the original application and require remedial education before the person may take future examinations.

. The secretary may approve an examination prepared or administered by a private testing agency or association of licensing agencies for use by an applicant in meeting the certification requirements.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5403-S.SL.pdf?cite=2007%20c%2070%20§%207[2007 c 70 § 7]; ]

== 18.240.070 - Applicant certification—Fees.
The secretary shall certify an applicant on forms provided by the secretary. Each applicant shall pay a fee determined by the secretary under RCW 43.70.250. The fee must accompany the application.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5403-S.SL.pdf?cite=2007%20c%2070%20§%208[2007 c 70 § 8]; ]

== 18.240.080 - Renewal of certification.
The secretary shall establish by rule the procedural requirements and fees for renewal of certification. Failure to renew invalidates the certification and all privileges granted by the certification.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5403-S.SL.pdf?cite=2007%20c%2070%20§%209[2007 c 70 § 9]; ]

== 18.240.090 - Application of uniform disciplinary act.
The uniform disciplinary act, chapter 18.130 RCW, governs the uncertified practice, the issuance and denial of certification, and the discipline of persons certified under this chapter. The secretary is the disciplining authority under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5403-S.SL.pdf?cite=2007%20c%2070%20§%2010[2007 c 70 § 10]; ]

