= 18.330 - Elder and vulnerable adult referral agency act.
:toc:

== 18.330.005 - Findings.
. The legislature finds that locating acceptable housing and appropriate care for vulnerable adults is an important aspect of providing an appropriate continuity of care for senior citizens.

. The legislature further finds that locating appropriate and quality housing alternatives sometimes depends on elder and vulnerable adult referral agencies attempting to assist with referral.

. The legislature further finds that vulnerable adult referral professionals should be required to meet certain minimum requirements to promote better integration of vulnerable adult housing choices.

. The legislature further finds that the requirement that elder and vulnerable adult referral agencies meet minimum standards of conduct is in the interest of public health, safety, and welfare.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1494-S.SL.pdf?cite=2011%20c%20357%20§%201[2011 c 357 § 1]; ]

== 18.330.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Care services" means any combination of services, including in-home care, private duty care, or private duty nursing designed for or with the goal of allowing vulnerable adults to receive care and related services at home or in a home-like setting. Care service providers must include home health agencies and in-home service agencies licensed under chapter 70.127 RCW.

. "Client" means an elder person or a vulnerable adult, or his or her representative if any, seeking a referral or assistance with entering into an arrangement for supportive housing or care services in Washington state through an elder and vulnerable adult referral agency. For purposes of this chapter, the "client's representative" means the person authorized under RCW 7.70.065 or other laws to provide informed consent for an individual unable to do so. "Client" may also mean a person seeking a referral for supportive housing or care services on behalf of the elder person or vulnerable adult through an elder care referral service: PROVIDED, That such a person is a family member, relative, or domestic partner of the senior or vulnerable adult.

. "Elder and vulnerable adult referral agency" or "agency" means a business or person who receives a fee from or on behalf of a vulnerable adult seeking a referral to care services or supportive housing, or who receives a fee from a care services provider or supportive housing provider because of any referral provided to or on behalf of a vulnerable adult.

. "Fee" means anything of value. "Fee" includes money or other valuable consideration or services or the promise of money or other valuable consideration or services, received directly or indirectly by an elder and vulnerable adult referral agency.

. "Information" means the provision of general information by an agency to a person about the types of supportive housing or care services available in the area that may meet the needs of elderly or vulnerable adults without giving the person the names of specific providers of care services or supportive housing, or giving a provider the name of the person or vulnerable adult. Information also means the provision by an agency of the names of specific providers to a social worker, discharge planner, case manager, professional guardian, nurse, or other professional who is assisting a vulnerable adult locate supportive housing or care services, where the agency does not request or receive any fee.

. "Person" includes any individual, firm, corporation, partnership, association, company, society, manager, contractor, subcontractor, bureau, agency, organization, service, office, or an agent or any of their employees.

. "Provider" means any entity or person that both provides supportive housing or care services to a vulnerable adult for a fee and provides or is required to provide such housing or services under a state or local business license specific to such housing or services.

. "Referral" means the act of an agency giving a client the name or names of specific providers of care services or supportive housing that may meet the needs of the vulnerable adult identified in the intake form described in RCW 18.330.060, or the agency gives a provider the name of a client for the purposes of enabling the provider to contact the client regarding care services or supportive housing provided by that provider.

. "Supportive housing" means any type of housing that includes services for care needs and is designed for prospective residents who are vulnerable adults. Supportive housing includes, but is not limited to, nursing homes licensed under chapter 18.51 RCW, *boarding homes licensed under chapter 18.20 RCW, adult family homes licensed under chapter 70.128 RCW, and continuing care retirement communities under RCW 70.38.025.

. "Vulnerable adult" has the same meaning as in RCW 74.34.020.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1494-S.SL.pdf?cite=2011%20c%20357%20§%202[2011 c 357 § 2]; ]

== 18.330.020 - Agency duties.
. As of January 1, 2012, a business or person operating or maintaining an agency in this state is subject to the provisions of this chapter. An agency must maintain general and professional liability insurance to cover the acts and services of the agency. The combined liability insurance coverage required is one million dollars.

. The agency may not create an exclusive agreement between the agency and the client, or between the agency and a provider. The agency cannot provide referral services to a client where the only names given to the client are of providers in which the agency or its personnel or immediate family members have an ownership interest in those providers. An agreement entered into between an agency and a provider must allow either the provider or the agency to cancel the agreement with specific payment terms regarding pending fees or commissions outlined in the agreement.

. The marketing materials, informational brochures, and websites owned or operated by an agency, and concerning information or referral services for elderly or vulnerable adults, must include a clear identification of the agency.

. All owners, operators, and employees of an agency shall be considered mandated reporters under the vulnerable adults act, chapter 74.34 RCW. No agency may develop or enforce any policies or procedures that interfere with the reporting requirements of chapter 74.34 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1494-S.SL.pdf?cite=2011%20c%20357%20§%203[2011 c 357 § 3]; ]

== 18.330.030 - Exemptions.
Nothing in this chapter may be construed to prohibit, restrict, or apply to:

. Any home health or hospice agency while providing counseling to patients on placement options in the normal course of practice;

. Government entities providing information and assistance to vulnerable adults unless making a referral in which a fee is received from a client;

. Professional guardians providing services under authority of their guardianship appointment;

. Supportive housing or care services providers who make referrals to other supportive housing or care services providers where no monetary value is exchanged;

. Social workers, discharge planners, or other social services staff assisting a vulnerable adult to define supportive housing or care services providers in the course of their employment responsibilities if they do not receive any monetary value from a provider; or

. Any person to the extent that he or she provides information to another person.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1494-S.SL.pdf?cite=2011%20c%20357%20§%204[2011 c 357 § 4]; ]

== 18.330.040 - Referral records—Agreement records.
. Each agency shall keep records of all referrals rendered to or on behalf of clients. These records must contain:

.. The name of the vulnerable adult, and the address and phone number of the client or the client's representative, if any;

.. The kind of supportive housing or care services for which referral was sought;

.. The location of the care services or supportive housing referred to the client and probable duration, if known;

.. The monthly or unit cost of the supportive housing or care services, if known;

.. If applicable, the amount of the agency's fee to the client or to the provider;

.. If applicable, the dates and amounts of refund of the agency's fee, if any, and reason for such refund; and

.. A copy of the client's disclosure and intake forms described in RCW 18.330.050 and 18.330.060.

. Each agency shall also keep records of any contract or written agreement entered into with any provider for services rendered to or on behalf of a vulnerable adult, including any referrals to a provider. Any provision in a contract or written agreement not consistent with this chapter is void and unenforceable.

. The agency must maintain the records covered by this chapter for a period of six years. The agency's records identifying a client are considered "health care information" and the provisions of chapter 70.02 RCW apply but only to the extent that such information meets the definition of "health care information" under *RCW 70.02.010(7). The client must have access upon request to the agency's records concerning the client and covered by this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1494-S.SL.pdf?cite=2011%20c%20357%20§%205[2011 c 357 § 5]; ]

== 18.330.050 - Referrals—Disclosure statement.
. An agency must provide a disclosure statement to each client prior to making a referral. A disclosure statement is not required when the agency is only providing information to a person. The disclosure statement must be acknowledged by the client prior to the referral and the agency shall retain a copy of the disclosure statement and acknowledgment. Acknowledgment may be in the form of:

.. A signature of the client or legal representative on the exact disclosure statement;

.. An electronic signature that includes the date, time, internet provider address, and displays the exact disclosure statement document;

.. A faxed confirmation that includes the date, time, and fax number and displaying the exact disclosure statement document; or

.. In instances where a vulnerable adult chooses not to sign or otherwise provide acknowledgment of the disclosure statement, the referral professional or agency may satisfy the acknowledgment requirement of this subsection (1) by documenting the client's refusal to sign.

. The disclosure statement must be dated and must contain the following information:

.. The name, address, and telephone number of the agency;

.. The name of the client;

.. The amount of the fee to be received from the client, if any. Alternatively, if the fee is to be received from the provider, the method of computation of the fee and the time and method of payment. In addition, the agency shall disclose to the client the amount of fee to be received from the provider, if the client requests such information;

.. A clear description of the services provided by the agency in general, and to be provided specifically for the client;

.. A provision stating that the agency may not require or request clients to sign waivers of potential liability for losses of personal property or injury, or to sign waivers of any rights of the client established in state or federal law;

.. A provision stating that the agency works with both the client and the care services or supportive housing provider in the same transaction, and an explanation that the agency will need the client's authorization to obtain or disclose confidential health care information;

.. A statement indicating the frequency on which the agency regularly tours provider facilities, and that, at the time of referral, the agency will inform the client in writing or by electronic means if the agency has toured the referred supportive housing provider or providers, and if so, the most recent date that tour took place;

.. A provision stating that the client may, without cause, stop using the agency or switch to another agency without penalty or cancellation fee to the client;

.. An explanation of the agency's refund of fees policy, which must be consistent with RCW 18.330.090;

.. A statement that the client may file a complaint with the attorney general's office for violations of this chapter, including the name, address, and telephone number of the consumer protection division of that office; and

.. If the agency or its personnel who are directly involved in providing referrals to clients, including the personnel's immediate family members, have an ownership interest in the supportive housing or care services to which the client is given a referral, a provision stating that the agency or such personnel or their immediate family members have an ownership interest in the supportive housing or care services to which the client is given referral services, and, if such ownership interest exists, an explanation of that interest.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1494-S.SL.pdf?cite=2011%20c%20357%20§%206[2011 c 357 § 6]; ]

== 18.330.060 - Intake form.
. The agency shall use a standardized intake form for all clients prior to making a referral. The intake form must, at a minimum, contain the following information regarding the vulnerable adult:

.. Recent medical history, as relevant to the referral process;

.. Known medications and medication management needs;

.. Known medical diagnoses, health concerns, and the reasons the client is seeking supportive housing or care services;

.. Significant known behaviors or symptoms that may cause concern or require special care;

.. Mental illness, dementia, or developmental disability diagnosis, if any;

.. Assistance needed for daily living;

.. Particular cultural or language access needs and accommodations;

.. Activity preferences;

.. Sleeping habits of the vulnerable adult, if known;

.. Basic information about the financial situation of the vulnerable adult and the availability of any long-term care insurance or financial assistance, including medicaid, which may be helpful in defining supportive housing and care services options for the vulnerable adult;

.. Current living situation of the client;

.. Geographic location preferences; and

.. Preferences regarding other issues important to the client, such as food and daily routine.

. The agency shall obtain the intake information from the most available sources, such as from the client, the client's representative, or a health care professional, and shall allow the vulnerable adult to participate to the maximum extent possible.

. The agency may provide information to a person about the types of supportive housing or care services available in the area that may meet the needs of elderly or vulnerable adults without the need to complete an intake form or provide a disclosure statement, if the agency does not make a referral or request or receive any fee. In addition, the agency may provide the names of specific providers to a social worker, discharge planner, case manager, professional guardian, nurse, or other professional who is assisting a vulnerable adult locate supportive housing or care services, provided the agency does not request or receive any fee.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1494-S.SL.pdf?cite=2011%20c%20357%20§%207[2011 c 357 § 7]; ]

== 18.330.070 - How referral is made—Contact with providers—Search for violations—Uniform standard for enforcement status.
. The agency may choose to provide a referral for the client by either giving the client the name or names of specific providers who may meet the needs of the vulnerable adult identified in the intake form or by giving a provider or providers the name of the client after obtaining the authorization of the client or the client's representative.

. [Empty]
.. Prior to making a referral to a specific provider, the agency shall speak with a representative of the provider and obtain, at a minimum, the following general information, which must be dated and retained in the agency's records:

... The type of license held by the provider and license number;

... Whether the provider is authorized by license to provide care to individuals with a mental illness, dementia, or developmental disability;

... Sources of payment accepted, including whether medicaid is accepted;

... General level of medication management services provided;

.. General level and types of personal care services provided;

.. Particular cultural needs that may be accommodated;

.. Primary language spoken by care providers;

.. Activities typically provided;

... Behavioral problems or symptoms that can or cannot be met;

.. Food preferences and special diets that can be accommodated; and

.. Other special care or services available.

.. The agency shall update this information regarding the provider at least annually. To the extent practicable, referrals shall be made to providers who appear, in the best judgment of the agency, capable of meeting the vulnerable adult's identified needs.

. Prior to making a referral of a supportive housing provider, the agency shall conduct a search, and inform the client that a search was conducted, of the department of social and health service's website to see if the provider is in enforcement status for violation of its licensing regulations. Prior to making a referral of a care services provider, the agency shall conduct a search, and inform the client that a search was conducted, of the department of health's website to determine if the provider is in enforcement status for violation of its licensing regulations. The searches required by this subsection must be considered timely if done within thirty days before the referral. The information obtained by the agency from the searches must be disclosed in writing to the client if the referral includes that provider.

. By January 1, 2012, the department of social and health services and the department of health must convene a work group of stakeholders to collaboratively identify and implement a uniform standard for the information pertaining to the enforcement status of a provider that must be disclosed to the client under subsection (3) of this section. The uniform standard must clearly identify what elements of an enforcement action should be included under the disclosure requirements of subsection (3) of this section. Agencies will have no liability or responsibility for the accuracy, completeness, timeliness, or currency of information shared in the prescribed format and are immune from any cause of action rising from their reliance on, use of, or distribution of this information.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1494-S.SL.pdf?cite=2011%20c%20357%20§%208[2011 c 357 § 8]; ]

== 18.330.080 - Fees charged to providers.
Nothing in this chapter will limit, specify, or otherwise regulate the fees charged by an agency to a provider for a referral.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1494-S.SL.pdf?cite=2011%20c%20357%20§%209[2011 c 357 § 9]; ]

== 18.330.090 - Disclosure of fees and refund policies.
. The agency shall clearly disclose its fees and refund policies to clients and providers. If the agency receives a fee regarding a client who was provided referral services for supportive housing, and the vulnerable adult dies, is hospitalized, or is transferred to another supportive housing setting for more appropriate care within the first thirty days of admission, then the agency shall refund a portion of its fee to the person who paid it, whether that is the client or the supportive housing provider. The amount refunded must be a prorated portion of the agency's fees, based upon a per diem calculation for the days that the client resided or retained a bed in the supportive housing.

. A refund policy inconsistent with this section is void and unenforceable.

. This section does not limit the application of other remedies, including the consumer protection act, chapter 19.86 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1494-S.SL.pdf?cite=2011%20c%20357%20§%2010[2011 c 357 § 10]; ]

== 18.330.100 - Background checks—Disqualifying crimes and acts.
Any employee, owner, or operator of an agency that works with vulnerable adults must pass a criminal background check every twenty-four months and not have been convicted of any crime that is disqualifying under RCW 43.43.830 or 43.43.842, or been found by a court of law or disciplinary authority to have abused, neglected, financially exploited, or abandoned a minor or vulnerable adult.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1494-S.SL.pdf?cite=2011%20c%20357%20§%2011[2011 c 357 § 11]; ]

== 18.330.110 - Acceptance of fees—Compliance with chapter.
An agency may not charge or accept a fee or other consideration from a client, care services provider, or supportive housing provider unless the agency substantially complies with the terms of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1494-S.SL.pdf?cite=2011%20c%20357%20§%2012[2011 c 357 § 12]; ]

== 18.330.120 - Provisions exclusive—Local government licensing.
. The provisions of this chapter relating to the regulation of private elder and vulnerable adult referral agencies are exclusive.

. This chapter may not be construed to affect or reduce the authority of any political subdivision of the state of Washington to provide for the licensing of private elder and vulnerable adult referral agencies solely for revenue purposes.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1494-S.SL.pdf?cite=2011%20c%20357%20§%2013[2011 c 357 § 13]; ]

== 18.330.130 - When remuneration for referral not allowed.
In accordance with RCW 74.09.240, the agency may not solicit or receive any remuneration directly or indirectly, overtly or covertly, in cash or in kind, in return for referring an individual to a person for the furnishing or arranging for the furnishing of any item or service for which payment may be made in whole or in part under chapter 74.09 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1494-S.SL.pdf?cite=2011%20c%20357%20§%2014[2011 c 357 § 14]; ]

== 18.330.140 - Application of consumer protection act.
The legislature finds that the operation of an agency in violation of this chapter is a matter vitally affecting the public interest for the purpose of applying the consumer protection act, chapter 19.86 RCW. Such a violation is an unfair or deceptive act in trade or commerce and an unfair method of competition for the purpose of applying the consumer protection act, chapter 19.86 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1494-S.SL.pdf?cite=2011%20c%20357%20§%2015[2011 c 357 § 15]; ]

== 18.330.150 - Liability of agencies.
Agencies and their employees, owners, and officers will not be considered providers and will not be liable or responsible for the acts or omissions of a provider.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1494-S.SL.pdf?cite=2011%20c%20357%20§%2016[2011 c 357 § 16]; ]

== 18.330.800 - Work group—Licensure.
The department of licensing shall convene a work group of stakeholders to consider the feasibility of establishing licensure for elder and vulnerable adult referral agencies described in chapter 357, Laws of 2011. The work group will provide recommendations to the legislature by December 1, 2011.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1494-S.SL.pdf?cite=2011%20c%20357%20§%2017[2011 c 357 § 17]; ]

== 18.330.900 - Short title.
This chapter may be known and cited as the "elder and vulnerable adult referral agency act."

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1494-S.SL.pdf?cite=2011%20c%20357%20§%2018[2011 c 357 § 18]; ]

== 18.330.901 - Effective date—2011 c 357.
This act takes effect January 1, 2012.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1494-S.SL.pdf?cite=2011%20c%20357%20§%2020[2011 c 357 § 20]; ]

