= 18.320 - Social workers.
:toc:

== 18.320.005 - Findings—2011 c 89.
. The legislature finds that:

.. The practice of social work by persons in the public and private sectors improves the lives of many people throughout the state through the application of a broad spectrum of social sciences to enhance the quality of life and develop the full potential of each client;

.. The practice of social work is a complex discipline that, appropriately undertaken, can address client problems, needs, and concerns, with the goal that clients achieve the maximum possible enhancement of their quality of life and develop to their full potential. However, improper assessment of client problems and needs by unqualified persons can lead to client harm;

.. It is in the state's interest to take steps to safeguard state residents from misrepresentations about qualifications for practicing social work. Because such misrepresentations could lead to the improper practice of social work by unqualified persons, those who represent themselves as social workers should have a qualifying degree from an accredited and approved social work program.

. The legislature declares that chapter 89, Laws of 2011 to regulate social workers constitutes an exercise of the state's police power to protect and promote the health, safety, and welfare of the residents of the state in general. Accordingly, while chapter 89, Laws of 2011 is intended to protect the public generally, it does not create a duty owed by the state or its instrumentalities to any individual or entity.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5020-S.SL.pdf?cite=2011%20c%2089%20§%201[2011 c 89 § 1]; ]

== 18.320.010 - Representation as social worker.
. To address the goal of safeguarding Washington residents from the unqualified or improper practice of social work, a person may not represent himself or herself as a social worker unless qualified as a social worker as defined in this section.

. For purposes of this section, "social worker" means a person who meets one of the following qualifications:

.. Is licensed under RCW 18.225.090(1)(a) or 18.225.145(1)(a); or

.. Has graduated with at least a bachelor's degree from a social work educational program accredited by the council on social work education.

. A public agency or private entity doing business in Washington may not use the title of social worker, or a form of the title, for describing or designating volunteer or employment positions or within contracts for services, reference materials, manuals, or other documents, unless the volunteers or employees working in those positions are qualified as a social worker as defined in this section.

. This section does not apply to:

.. Persons employed in Washington on January 1, 2012, under the job title of social worker so long as the person continues to be employed by the same agency as on January 1, 2012;

.. Persons employed by the state of Washington on January 1, 2012, under the job title of social worker so long as the person continues to be employed by the state and who shall continue to have the same layoff, reversion, transfer, and promotional opportunities as were available to the employee on January 1, 2012;

.. Individuals employed by the government of the United States while engaged in the performance of duties prescribed by the laws of the United States; or

.. Persons providing services as an educational staff associate who are certified by the Washington professional educator standards board. However, this section applies to a certified educational staff associate providing services outside the school setting.

. As used in subsection (4) of this section, "agency" means any private employer or any agency of state government.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5020-S.SL.pdf?cite=2011%20c%2089%20§%202[2011 c 89 § 2]; ]

== 18.320.020 - Application of consumer protection act.
. The legislature finds that the practices covered by this chapter are matters vitally affecting the public interest for the purpose of applying the consumer protection act, chapter 19.86 RCW. A violation of this chapter is not reasonable in relation to the development and preservation of business and is an unfair or deceptive act in trade or commerce and an unfair method of competition for the purpose of applying the consumer protection act, chapter 19.86 RCW.

. Remedies available under chapter 19.86 RCW for a violation of this chapter do not affect any other remedy available under the law.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5020-S.SL.pdf?cite=2011%20c%2089%20§%203[2011 c 89 § 3]; ]

