= 18.370 - Tanning facilities.
:toc:

== 18.370.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Tanning facility" means any location, place, area, structure, or business that provides persons access to any ultraviolet tanning device for a fee.

. "Ultraviolet tanning device" means equipment that emits electromagnetic radiation with wavelengths in the air between two hundred and four hundred nanometers used for tanning of the skin including, but not limited to, a sunlamp, tanning booth, or tanning bed. An ultraviolet tanning device does not mean a phototherapy device which may be used by or under the direct supervision of a licensed physician who is trained in the use of phototherapy devices.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6065.SL.pdf?cite=2014%20c%2087%20§%201[2014 c 87 § 1]; ]

== 18.370.020 - Minors prohibited—Proof of age.
. Persons under eighteen years of age are prohibited from using an ultraviolet tanning device without a written prescription for ultraviolet radiation treatment from a physician licensed under chapter 18.57 or 18.71 RCW.

. Proof of age must be satisfied with a driver's license or other government-issued identification containing the date of birth and a photograph of the individual.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6065.SL.pdf?cite=2014%20c%2087%20§%202[2014 c 87 § 2]; ]

== 18.370.030 - Penalty.
The owner of a tanning facility that violates this chapter is liable for a civil penalty not to exceed two hundred fifty dollars per violation in addition to any other penalty established by law.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6065.SL.pdf?cite=2014%20c%2087%20§%203[2014 c 87 § 3]; ]

