= 18.400 - Professional licensure—Previous criminal convictions.
:toc:

== 18.400.010 - Findings—Intent. (Effective January 1, 2022.)
. The legislature finds that individuals with prior criminal convictions, upon completing the terms of one's sentence, have paid their debt to society, and should be given the opportunity to be regular and productive members of society by seeking gainful employment. Recognizing the perils recidivism poses to the individual, families, public safety, and general well-being, the legislature should prioritize that removal of these barriers which prevent these individuals from entering the workforce.

. It is the intent of the legislature to provide a reliable process for individuals with past criminal convictions to apply for a professional license, and to not be prevented from obtaining a professional license due to a prior criminal conviction which does not directly relate to the applicable profession, business, or trade.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1399.SL.pdf?cite=2021%20c%20194%20§%201[2021 c 194 § 1]; ]

== 18.400.020 - Preliminary application for a professional license with a criminal conviction. (Effective January 1, 2022.)
. An individual who has a criminal conviction may submit to the appropriate licensing authority a preliminary application for a professional license, government certification, or state recognition of the individual's personal qualifications for a determination as to whether the individual's criminal conviction would disqualify the individual from obtaining the occupational or professional license, government certification, or state recognition of the individual's personal qualifications from that licensing authority. The preliminary application may be submitted at any time, including prior to obtaining required education or paying any fee. Only licenses, certifications, or recognitions administered by the department of licensing or a board or commission with the support of the department of licensing are eligible for a determination under this section.

. The preliminary application may include additional information about the individual's current circumstances, including the time since the offense, completion of the criminal sentence, other evidence of rehabilitation, testimonials, employment history, and employment aspirations.

. Upon receipt of a preliminary application under subsection (2) of this section, the appropriate licensing authority shall make a determination of whether the individual's criminal conviction would disqualify the individual from obtaining a professional license, government certification, or state recognition of the individual's personal qualifications from that licensing authority.

. The licensing authority shall issue its determination in writing within two months after receiving a preliminary application under subsection (2) of this section. If the licensing authority determines that the individual's criminal conviction would disqualify the individual, the licensing authority will provide a determination that includes findings of fact and conclusions of law and may advise the individual of any action the individual may take to remedy the disqualification. If the licensing authority finds that the individual has been convicted of a subsequent criminal conviction, or that the individual has failed to disclose a conviction, the licensing authority may rescind a determination upon finding that the subsequent criminal conviction would be disqualifying under subsection (3) of this section.

. The individual may appeal the determination of the licensing authority. The appeal shall be in accordance with chapter 34.05 RCW.

. An individual whose preliminary application has been disqualified shall not file another preliminary application under this section with the same licensing authority within two years after the final decision on the previous preliminary application, except that if the individual has taken action to remedy the disqualification as advised by the licensing board. If such action has been taken, the individual may file another preliminary application under this section with the same licensing authority six months after the final decision on the previous preliminary application.

. A licensing authority shall not charge a fee to a person for any preliminary application filed pursuant to this section.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1399.SL.pdf?cite=2021%20c%20194%20§%202[2021 c 194 § 2]; ]

== 18.400.030 - Licensing authority disqualification determination. (Effective January 1, 2022.)
The appropriate licensing authority may disqualify an individual from obtaining a professional license, government certification, or state recognition if it determines the individual's conviction is related to the occupation or profession unless the individual has requested and received a certificate of restoration of opportunity under RCW 9.97.020.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1399.SL.pdf?cite=2021%20c%20194%20§%203[2021 c 194 § 3]; ]

== 18.400.900 - Effective date—2021 c 194.
This act takes effect January 1, 2022.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1399.SL.pdf?cite=2021%20c%20194%20§%204[2021 c 194 § 4]; ]

