= 5.24 - Uniform judicial notice of foreign laws act.
:toc:

== 5.24.010 - Judicial notice of Constitution and laws.
Every court of this state shall take judicial notice of the Constitution, common law, civil law, and statutes of every state, territory and other jurisdiction of the United States.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c82.pdf?cite=1941%20c%2082%20§%201[1941 c 82 § 1]; Rem. Supp. 1941 § 1278; ]

== 5.24.020 - Manner of obtaining information.
The court may inform itself of such laws in such manner as it may deem proper, and the court may call upon counsel to aid it in obtaining such information.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c82.pdf?cite=1941%20c%2082%20§%202[1941 c 82 § 2]; Rem. Supp. 1941 § 1279; ]

== 5.24.030 - Determination by court—Review.
The determination of such laws shall be made by the court and not by the jury and shall be reviewable.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c82.pdf?cite=1941%20c%2082%20§%203[1941 c 82 § 3]; Rem. Supp. 1941 § 1280; ]

== 5.24.040 - Necessity of pleading foreign laws.
This chapter shall not be construed to relieve any party of the duty of hereafter pleading such laws where required under the law and practice of this state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c331.pdf?cite=1981%20c%20331%20§%2014[1981 c 331 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c82.pdf?cite=1941%20c%2082%20§%204[1941 c 82 § 4]; Rem. Supp. 1941 § 1281; ]

== 5.24.050 - Jurisdictions excepted.
The law of any jurisdiction other than a state, territory or other jurisdiction of the United States shall be an issue for the court, but shall not be subject to the foregoing provisions concerning judicial notice.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c82.pdf?cite=1941%20c%2082%20§%205[1941 c 82 § 5]; Rem. Supp. 1941 § 1282; ]

== 5.24.060 - Construction of chapter.
This chapter shall be so interpreted and construed as to effectuate its general purpose to make uniform the law of those states which enact it.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c82.pdf?cite=1941%20c%2082%20§%206[1941 c 82 § 6]; Rem. Supp. 1941 § 1283; ]

== 5.24.070 - Short title.
This chapter may be cited as the "Uniform Judicial Notice of Foreign Laws Act."

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c82.pdf?cite=1941%20c%2082%20§%207[1941 c 82 § 7]; Rem. Supp. 1941 § 1284; ]

