= 5.48 - Proof—Replacement of lost records.
:toc:

== 5.48.010 - Substitution of copy authorized.
Whenever a pleading, process, return, verdict, bill of exceptions, order, entry, stipulation or other act, file or proceeding in any action or proceeding pending in any court of this state shall have been lost or destroyed by fire or otherwise, or is withheld by any person, such court may, upon the application of any party to such action or proceeding, order a copy or substantial copy thereof to be substituted.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c337.pdf?cite=1890%20p%20337%20§%201[1890 p 337 § 1]; RRS § 1270; ]

== 5.48.020 - Methods to replace lost court records.
Whenever the record required by law of the proceedings, judgment or decree in any action or other proceeding of any court in this state in which a final judgment has been rendered, or any part thereof, is lost or destroyed by fire or otherwise, such court may, upon the application of any party interested therein, grant an order authorizing such record or parts thereof to be supplied or replaced—

. by a certified copy of such original record, or part thereof, when the same can be obtained;

. by a duly certified copy of the record in the supreme court or court of appeals of such original record of any action or proceeding that may have been removed to the supreme court or court of appeals and remains recorded or filed in said courts;

. by the original pleadings, entries, papers and files in such action or proceeding when the same can be obtained;

. by an agreement in writing signed by all the parties to such action or proceeding, their representatives or attorneys, that a substituted copy of such original record is substantially correct.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971c81.pdf?cite=1971%20c%2081%20§%2025[1971 c 81 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c338.pdf?cite=1890%20p%20338%20§%202[1890 p 338 § 2]; RRS § 1271; ]

== 5.48.030 - Action to replace—Procedure.
Whenever the record required by law, or any part thereof, of the proceedings or judgment or decree in any action or other proceeding of any court in this state in which the final judgment has been rendered, is lost or destroyed by fire or otherwise, and such loss cannot be supplied or replaced as provided in RCW 5.48.020, any person or party interested therein may make a written application to the court to which said record belongs, setting forth the substance of the record so lost or destroyed, which application shall be verified in the manner provided for the verification of pleadings in a civil action, and thereupon summons shall issue and actual service, or service by publication, shall be made upon all persons interested in or affected by said original judgment or final entry in the manner provided by law for the commencement of civil actions, provided the parties may waive the issuing or service of summons and enter their appearance to such application; and upon the hearing of such application without further pleadings, if the court finds that such record has been lost or destroyed and that it is enabled by the evidence produced to find the substance or effect thereof material to the preservation of the rights of the parties thereto, it shall make an order allowing a record, which record shall recite the substance and effect of said lost or destroyed record, or part thereof, and the same shall thereupon be recorded in said court, and shall have the same effect as the original record would have if the same had not been lost or destroyed, so far as it concerns the rights of the parties so making the application, or persons or parties so served with summons, or entering their appearance, or persons claiming under them by a title acquired subsequently to the filing of the application.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c338.pdf?cite=1890%20p%20338%20§%203[1890 p 338 § 3]; RRS § 1272; ]

== 5.48.040 - Hearing on application—Evidence.
Upon the hearing of the application provided in RCW 5.48.030, the court may admit in evidence oral testimony and any complete or partial abstract of such record, docket entries or indices, and any other written evidence of the contents or effect of such records and published reports concerning such actions or proceedings, when the court is of opinion that such abstracts, writings and publications were fairly and honestly made before the loss of such records occurred.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c339.pdf?cite=1890%20p%20339%20§%204[1890 p 339 § 4]; RRS § 1273; ]

== 5.48.050 - Time for appeal extended.
Whenever a lost or destroyed judgment or order is one to which either party has a right to a proceeding in error or of appeal, the time intervening between the filing of the application mentioned in RCW 5.48.030 and the final order of the court thereon shall be excluded in computing the time within which such proceeding or appeal may be taken as provided by law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c339.pdf?cite=1890%20p%20339%20§%205[1890 p 339 § 5]; RRS § 1274; ]

== 5.48.051 - Costs to be taxed.
The costs to be taxed, upon an application to restore a lost or destroyed record, shall be the same as are provided for like service in civil actions, and may be adjudged against either or any party to such proceeding or application, or may, in the discretion of the court, be apportioned between such parties.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c339.pdf?cite=1890%20p%20339%20§%206[1890 p 339 § 6]; RRS § 1275; ]

== 5.48.060 - Replacement of lost or destroyed probate records.
In case of the loss or destruction by fire or otherwise of the records, or any part thereof, of any probate court or superior court having probate jurisdiction, the judge of any such court may proceed, upon its own motion, or upon application in writing of any party in interest, to restore the records, papers, and proceedings of either of said courts relating to the estates of deceased persons, including recorded wills, wills probated, or filed for probate in such courts, all marriage records and all other records and proceedings, and for the purpose of restoring said records, wills, papers, or proceedings, or any part thereof, may cause citations or other process to be issued to any and all parties to be designated by him or her, and may compel the attendance in court of any and all witnesses whose testimony may be necessary to the establishment of any such record or part thereof, and the production of any and all written or documentary evidence which may be by him or her deemed necessary in determining the true import and effect of the original records, will, paper, or other document belonging to the files of said courts; and may make such orders and decrees establishing such original record, will, paper, document or proceeding, or the substance thereof, as to him or her shall seem just and proper.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20138[2011 c 336 § 138]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c9.pdf?cite=1957%20c%209%20§%205[1957 c 9 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c340.pdf?cite=1890%20p%20340%20§%207[1890 p 340 § 7]; RRS § 1276; ]

== 5.48.070 - Costs—Payment of.
The costs incurred in the probate and superior courts in proceedings under RCW 5.48.051 and 5.48.060 shall be paid by the party or parties interested in such proceedings, or in whose behalf such proceedings are instituted.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c340.pdf?cite=1890%20p%20340%20§%208[1890 p 340 § 8]; RRS § 1277. FORMER PART OF SECTION:  1890 p 339 § 6; RRS § 1275, now codified as RCW  5.48.051; ]

