= 5.50 - Uniform unsworn declarations act.
:toc:

== 5.50.010 - Definitions.
In this chapter:

. "Law" includes a statute, judicial decision or order, rule of court, executive order, and administrative rule, regulation, or order.

. "Record" means information that is inscribed on a tangible medium or that is stored in an electronic or other medium and is retrievable in perceivable form.

. "Sign" means, with present intent to authenticate or adopt a record:

.. To execute or adopt a tangible symbol;

.. To attach to or logically associate with the record an electronic symbol, sound, or process;

.. To affix or place the declarant's signature as defined in RCW 9A.04.110 on the record;

.. To affix or logically associate the declarant's signature in the manner described in general rule 30 to the record if he or she is a licensed attorney; or

.. To affix or logically associate the declarant's full name, department or agency, and badge or personnel number to any record that is electronically submitted to a court, a prosecutor, or a magistrate from an electronic device that is owned, issued, or maintained by a criminal justice agency if the declarant is a law enforcement officer.

. "Sworn declaration" means a declaration in a signed record given under oath. The term includes a sworn statement, verification, certificate, and affidavit.

. "Unsworn declaration" means a declaration in a signed record not given under oath but given under penalty of perjury. The term includes an unsworn statement, verification, and certificate.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2022[2020 c 57 § 22]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5017-S.SL.pdf?cite=2019%20c%20232%20§%201[2019 c 232 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1345.SL.pdf?cite=2011%20c%2022%20§%202[2011 c 22 § 2]; ]

== 5.50.020 - Applicability.
This chapter applies to an unsworn declaration by a declarant who at the time of making the declaration is physically located within or outside the boundaries of the United States, whether or not the location is subject to the jurisdiction of the United States.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5017-S.SL.pdf?cite=2019%20c%20232%20§%202[2019 c 232 § 2]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1345.SL.pdf?cite=2011%20c%2022%20§%203[2011 c 22 § 3]; ]

== 5.50.030 - Validity of unsworn declaration—Exceptions.
. Except as otherwise provided in subsection (2) of this section, if a law of this state requires or permits use of a sworn declaration, an unsworn declaration meeting the requirements of this chapter has the same effect as a sworn declaration.

. This chapter does not apply to:

.. A deposition;

.. An oath of office;

.. An oath required to be given before a specified official other than a notary public; or

.. A declaration to be recorded pursuant to Title 64 or 65 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2023[2020 c 57 § 23]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1345.SL.pdf?cite=2011%20c%2022%20§%204[2011 c 22 § 4]; ]

== 5.50.040 - Medium required for presentation of unsworn declaration.
If a law of this state requires that a sworn declaration be presented in a particular medium, an unsworn declaration must be presented in that medium.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1345.SL.pdf?cite=2011%20c%2022%20§%205[2011 c 22 § 5]; ]

== 5.50.050 - Form.
An unsworn declaration under this chapter must be in substantially the following form:

I declare under penalty of perjury under the law of Washington that the foregoing is true and correct.

Signed on the . . . . day of . . . . . ., . . . .,

.. (month) (year)

at . . . . . . . . . . . . . . . . . . .

(city or other location, and state or country)

. . . . . . . . .

(printed name)

. . . . . . . . .

..

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5017-S.SL.pdf?cite=2019%20c%20232%20§%203[2019 c 232 § 3]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1345.SL.pdf?cite=2011%20c%2022%20§%206[2011 c 22 § 6]; ]

== 5.50.060 - Relation to electronic signatures in global and national commerce act.
This chapter modifies, limits, and supersedes the federal electronic signatures in global and national commerce act, 15 U.S.C. Sec. 7001, et seq., but does not modify, limit, or supersede section 101(c) of that act, 15 U.S.C. Sec. 7001(c), or authorize electronic delivery of any of the notices described in section 103(b) of that act, 15 U.S.C. Sec. 7003(b).

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1345.SL.pdf?cite=2011%20c%2022%20§%208[2011 c 22 § 8]; ]

== 5.50.900 - Short title.
This chapter may be cited as the uniform unsworn declarations act.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5017-S.SL.pdf?cite=2019%20c%20232%20§%204[2019 c 232 § 4]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1345.SL.pdf?cite=2011%20c%2022%20§%201[2011 c 22 § 1]; ]

== 5.50.901 - Uniformity of application and construction.
In applying and construing this uniform act and chapter, consideration must be given to the need to promote uniformity of the law with respect to its subject matter among states that enact it.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5017-S.SL.pdf?cite=2019%20c%20232%20§%205[2019 c 232 § 5]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1345.SL.pdf?cite=2011%20c%2022%20§%207[2011 c 22 § 7]; ]

