= 5.52 - Telegraphic communications.
:toc:

== 5.52.010 - Deemed communications in writing.
Contracts made by telegraph shall be deemed to be contracts in writing; and all communications sent by telegraph and signed by the person or persons sending the same, or by his, her, or their authority, shall be held and deemed to be communications in writing.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20139[2011 c 336 § 139]; Code 1881 § 2352; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1865%20p%2074%20§%2011[1865 p 74 § 11]; RRS § 11345; ]

== 5.52.020 - Notice by telegraph deemed actual notice.
Whenever any notice, information, or intelligence, written or otherwise, is required to be given, the same may be given by telegraph: PROVIDED, That the dispatch containing the same be delivered to the person entitled thereto, or to his or her agent or attorney. Notice by telegraph shall be deemed actual notice.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20140[2011 c 336 § 140]; Code 1881 § 2353; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1865%20p%2074%20§%2012[1865 p 74 § 12]; RRS § 11346; ]

== 5.52.030 - Instrument transmitted by telegraph—Effect.
Any power of attorney, or other instrument in writing, duly proved or acknowledged, and certified so as to be entitled to record may, together with the certificate of its proof or acknowledgment, be sent by telegraph, and telegraphic copy, or duplicate thereof, shall, prima facie, have the same force and effect, in all respects, and may be admitted to record and recorded in the same manner and with like effect as the original.

[ Code 1881 § 2354; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1865%20p%2074%20§%2013[1865 p 74 § 13]; RRS § 11347; ]

== 5.52.040 - Bills and notes drawn by telegraph—Effect.
Checks, due bills, promissory notes, bills of exchange and all orders or agreements for the payment or delivery of money, or other thing of value, may be made or drawn by telegraph, and when so made or drawn, shall have the same force and effect to charge the maker, drawer, indorser or acceptor thereof, and shall create the same rights and equities in favor of the payee, drawer [drawee], indorser [indorsee], acceptor, holder or bearer thereof, and shall be entitled to the same days of grace as if duly made or drawn and delivered in writing; but it shall not be lawful for any person other than the person or drawer thereof, to cause any such instrument to be sent by telegraph, so as to charge any person thereby, except as in RCW 5.52.050 otherwise provided. Whenever the genuineness or execution of any such instrument received by telegraph shall be denied on oath, by or on behalf of the person sought to be charged thereby, it shall be incumbent upon the party claiming under or alleging the same, to prove the existence and execution of the original writing from which the telegraph copy or duplicate was transmitted. The original message shall in all cases be preserved in the telegraph office from which the same is sent.

[ Code 1881 § 2355; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1865%20p%2074%20§%2014[1865 p 74 § 14]; RRS § 11348; ]

== 5.52.050 - Electronic copies as evidence.
Except as otherwise provided in this chapter, any instrument in writing, duly certified, under his or her hand and official seal, by a notary public, commissioner of deeds, or clerk of a court of record, to be genuine, within the personal knowledge of such officer, may, together with such certificate, be sent by telegraph or other electronic transmission and the telegraphic or other electronic transmission copy thereof shall, prima facie, only have the same force, effect and validity, in all respects whatsoever as the original, and the burden of proof shall rest with the party denying the genuineness, or due execution of the original.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1471.SL.pdf?cite=2006%20c%20198%20§%202[2006 c 198 § 2]; Code 1881 § 2356; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1865%20p%2075%20§%2015[1865 p 75 § 15]; RRS § 11349; ]

== 5.52.060 - Seal and revenue stamp, how described.
Whenever any document to be sent by telegraph bears a seal, either private or official, it shall not be necessary for the operator in sending the same, to telegraph a description of the seal, or any words or device thereon, but the same may be expressed in the telegraphic copy by the letters "L.S.," or by the word "seal," and whenever any document bears a revenue stamp, it shall be sufficient to express the same in the telegraphic copy, by the word "stamp," without any other or further description thereof.

[ Code 1881 § 2359; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1865%20p%2076%20§%2018[1865 p 76 § 18]; RRS § 11350; ]

== 5.52.070 - "Telegraphic copy" or "telegraphic duplicate" defined.
The term "telegraphic copy," or "telegraphic duplicate," whenever used in this chapter, shall be construed to mean any copy of a message, made or prepared for delivery at the office to which said message may have been sent by telegraph.

[ Code 1881 § 2362; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1865%20p%2077%20§%2021[1865 p 77 § 21]; RRS § 11351; ]

