= 5.56 - Witnesses—Compelling attendance.
:toc:

== 5.56.010 - When witnesses must attend—Fees and allowances.
Any person may be compelled to attend as a witness before any court of record, judge, commissioner, or referee, in any civil action or proceeding in this state. No such person shall be compelled to attend as a witness in any civil action or proceeding unless the fees be paid or tendered him or her which are allowed by law for one day's attendance as a witness and for traveling to and returning from the place where he or she is required to attend, together with any allowance for meals and lodging theretofore fixed as specified herein: PROVIDED, That such fees be demanded by any witness residing within the same county where such court of record, judge, commissioner, or referee is located, or within twenty miles of the place where such court is located, at the time of service of the subpoena: PROVIDED FURTHER, That a party desiring the attendance of a witness residing outside of the county in which such action or proceeding is pending, or more than twenty miles of the place where such court is located, shall apply ex parte to such court, or to the judge, commissioner, referee, or clerk thereof, who, if such application be granted and a subpoena issued, shall fix without notice an allowance for meals and lodging, if any to be allowed, together with necessary travel expenses, and the amounts so fixed shall be endorsed upon the subpoena and tendered to such witness at the time of the service of the subpoena: PROVIDED FURTHER, That the court shall fix and allow at or after trial such additional amounts for meals, lodging, and travel as it may deem reasonable for the attendance of such witness.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20141[2011 c 336 § 141]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c19.pdf?cite=1963%20c%2019%20§%201[1963 c 19 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c19.pdf?cite=1891%20c%2019%20§%202[1891 c 19 § 2]; Code 1881 § 393; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2087%20§%20395[1877 p 87 § 395]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20104%20§%20388[1869 p 104 § 388]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20156%20§%2069[1863 p 156 § 69]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20187%20§%20295[1854 p 187 § 295]; RRS § 1215; ]

== 5.56.050 - Person in court required to testify.
A person present in court or before a judicial officer, may be required to testify in the same manner as if he or she were in attendance upon a subpoena issued by such court or officer.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20142[2011 c 336 § 142]; Code 1881 § 397; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2088%20§%20399[1877 p 88 § 399]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20106%20§%20392[1869 p 106 § 392]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20188%20§%20299[1854 p 188 § 299]; RRS § 1219; ]

== 5.56.060 - Result of failure to attend.
If any person duly served with a subpoena and obliged to attend as a witness, shall fail to do so, without any reasonable excuse, he or she shall be liable to the aggrieved party for all damages occasioned by such failure, to be recovered in a civil action.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20143[2011 c 336 § 143]; Code 1881 § 398; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2088%20§%20400[1877 p 88 § 400]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20106%20§%20393[1869 p 106 § 393]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20188%20§%20300[1854 p 188 § 300]; RRS § 1220, part. FORMER PART OF SECTION: Code 1881 § 399; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2088%20§%20401[1877 p 88 § 401]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20106%20§%20394[1869 p 106 § 394]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20188%20§%20301[1854 p 188 § 301]; RRS § 1220, part, now codified as RCW  5.56.061; ]

== 5.56.061 - Failure to attend considered contempt of court.
A failure to attend as required by the subpoena, shall also be considered a contempt of court as provided in chapter 7.21 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c373.pdf?cite=1989%20c%20373%20§%208[1989 c 373 § 8]; Code 1881 § 399; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2088%20§%20401[1877 p 88 § 401]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20106%20§%20394[1869 p 106 § 394]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20188%20§%20301[1854 p 188 § 301]; RRS § 1220, part; ]

== 5.56.070 - Attachment of witness.
The court, judge, or other officer, in such case, may issue an attachment to bring such witness before them to answer for contempt, and also testify as witness in the cause in which he or she was subpoenaed.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c202.pdf?cite=1987%20c%20202%20§%20125[1987 c 202 § 125]; Code 1881 § 400; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2088%20§%20402[1877 p 88 § 402]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20106%20§%20395[1869 p 106 § 395]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20188%20§%20302[1854 p 188 § 302]; RRS § 1221; ]

== 5.56.080 - To whom attachment directed—Execution.
Such attachment may be directed to the sheriff or any deputy of any county in which the witness may be found, and shall be executed in the same manner as a warrant; and the fees of the officer for issuing and serving the same shall be paid by the person against whom the same was issued, unless he or she shows reasonable cause, to the satisfaction of the judge, for his or her omission to attend; in which case the party requiring such attachment shall pay all such costs.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c202.pdf?cite=1987%20c%20202%20§%20126[1987 c 202 § 126]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c19.pdf?cite=1891%20c%2019%20§%203[1891 c 19 § 3]; RRS § 1222; ]

== 5.56.090 - Testimony of prisoner, how obtained.
If the witness be a prisoner confined in a jail or prison within this state, an order for his or her examination in prison, upon deposition, or for his or her temporary removal and production before a court or officer, for the purpose of being orally examined, may be issued.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20144[2011 c 336 § 144]; Code 1881 § 401; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2088%20§%20403[1877 p 88 § 403]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20106%20§%20396[1869 p 106 § 396]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20189%20§%20303[1854 p 189 § 303]; RRS § 1223; ]

== 5.56.100 - Affidavit to procure order.
Such order can only be made upon affidavit, showing the nature of the action or proceeding, the testimony expected from the witness, and its materiality.

[ Code 1881 § 402; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2088%20§%20404[1877 p 88 § 404]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20106%20§%20397[1869 p 106 § 397]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20189%20§%20304[1854 p 189 § 304]; RRS § 1224; ]

