= 5.64 - Admissibility of certain gestures of apology, sympathy, fault, etc. in civil actions against health care providers.
:toc:

== 5.64.010 - Civil actions against health care providers—Admissibility of evidence of furnishing or offering to pay medical expenses—Admissibility of expressions of apology, sympathy, fault, etc.
. In any civil action against a health care provider for personal injuries which is based upon alleged professional negligence, or in any arbitration or mediation proceeding related to such civil action, evidence of furnishing or offering or promising to pay medical, hospital, or similar expenses occasioned by an injury is not admissible.

. [Empty]
.. In a civil action against a health care provider for personal injuries that is based upon alleged professional negligence, or in any arbitration or mediation proceeding related to such civil action, a statement, affirmation, gesture, or conduct identified in (b) of this subsection is not admissible as evidence if:

... It was conveyed by a health care provider to the injured person, or to a person specified in RCW 7.70.065 (1)(a) or (2)(a) within thirty days of the act or omission that is the basis for the allegation of professional negligence or within thirty days of the time the health care provider discovered the act or omission that is the basis for the allegation of professional negligence, whichever period expires later; and

... It relates to the discomfort, pain, suffering, injury, or death of the injured person as the result of the alleged professional negligence.

.. (a) of this subsection applies to:

... Any statement, affirmation, gesture, or conduct expressing apology, fault, sympathy, commiseration, condolence, compassion, or a general sense of benevolence; or

... Any statement or affirmation regarding remedial actions that may be taken to address the act or omission that is the basis for the allegation of negligence.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2292-S2.SL.pdf?cite=2006%20c%208%20§%20101[2006 c 8 § 101]; 1975-'76 2nd ex.s. c 56 § 3; ]

