= 5.66 - Admissibility of certain gestures expressing sympathy.
:toc:

== 5.66.010 - Admissibility of sympathetic gestures.
. The portion of statements, writings, or benevolent gestures expressing sympathy or a general sense of benevolence relating to the pain, suffering, or death of a person involved in an accident, and made to that person or to the family of that person, shall be inadmissible as evidence in a civil action. A statement of fault, however, which is part of, or in addition to, any of the above shall not be made inadmissible by this section.

. For purposes of this section:

.. "Accident" means an occurrence resulting in injury or death to one or more persons that is not the result of willful action by a party.

.. "Benevolent gestures" means actions that convey a sense of compassion or commiseration emanating from humane impulses.

.. "Family" means the spouse or the domestic partner, parent, grandparent, stepmother, stepfather, child, grandchild, brother, sister, half brother, half sister, adopted child of a parent, or spouse's or domestic partner's parents of an injured party.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3104-S2.SL.pdf?cite=2008%20c%206%20ยง%20403[2008 c 6 ยง 403]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6429.SL.pdf?cite=2002%20c%20334%20ยง%201[2002 c 334 ยง 1]; ]

