= 20.01 - Agricultural products—Commission merchants, dealers, brokers, buyers, agents.
:toc:

== 20.01.010 - Definitions.
As used in this title the terms defined in this section have the meanings indicated unless the context clearly requires otherwise.

. "Agent" means any person who, on behalf of any commission merchant, dealer, broker, or cash buyer, acts as liaison between a consignor and a principal, or receives, contracts for, or solicits any agricultural product from the consignor thereof or who negotiates the consignment or purchase of any agricultural product on behalf of any commission merchant, dealer, broker, or cash buyer and who transacts all or a portion of that business at any location other than at the principal place of business of his or her employer. With the exception of an agent for a commission merchant or dealer handling horticultural products, an agent may operate only in the name of one principal and only to the account of that principal.

. "Agricultural product" means any unprocessed horticultural, vermicultural and its by-products, viticultural, berry, poultry, poultry product, grain, bee, or other agricultural products. "Agricultural product" also includes (a) mint or mint oil processed by or for the producer thereof, hay and straw baled or prepared for market in any manner or form and livestock; and (b) agricultural seed, flower seed, vegetable seed, other crop seed, and seeds, as defined in chapter 15.49 RCW, however, any disputes regarding responsibilities for seed clean out are governed exclusively by contracts between the producers of the seed and conditioners or processors of the seed.

. "Broker" means any person other than a commission merchant, dealer, or cash buyer who negotiates the purchase or sale of any agricultural product, but no broker may handle the agricultural products involved or proceeds of the sale.

. "Cash buyer" means any person other than a commission merchant, dealer, or broker, who obtains from the consignor thereof for the purpose of resale or processing, title, possession, or control of any agricultural product or who contracts for the title, possession, or control of any agricultural product, or who buys or agrees to buy for resale any agricultural product by paying to the consignor at the time of obtaining possession or control of any agricultural product the full agreed price of the agricultural product, in coin or currency. However, a cashier's check, certified check, credit card, or bankdraft may be used for the payment. For the purposes of this subsection, "agricultural product," does not include hay, grain, straw, or livestock.

. "Certified weight" means any signed certified statement or memorandum of weight, measure or count issued by a licensed public weighmaster in accordance with the provisions of chapter 15.80 RCW.

. "Commission merchant" means any person who receives on consignment for sale or processing and sale from the consignor thereof any agricultural product for sale on commission on behalf of the consignor, or who accepts any farm product in trust from the consignor thereof for the purpose of resale, or who sells or offers for sale on commission any agricultural product, or who in any way handles for the account of or as an agent of the consignor thereof, any agricultural product.

. "Conditioner" means any person, firm, company, or other organization that receives seeds from a consignor for drying or cleaning.

. "Consignor" means any producer, person, or his or her agent who sells, ships, or delivers to any commission merchant, dealer, cash buyer, or agent, any agricultural product for processing, handling, sale, or resale.

. "Date of sale" means the date agricultural products are delivered to the person buying the products.

. "Dealer" means any person other than a cash buyer, as defined in subsection (4) of this section, who solicits, contracts for, or obtains from the consignor thereof for reselling or processing, title, possession, or control of any agricultural product, or who buys or agrees to buy any agricultural product from the consignor thereof for sale or processing and includes any person, other than one who acts solely as a producer, who retains title in an agricultural product and delivers it to a producer for further production or increase. For the purposes of this chapter, the term dealer includes any person who purchases livestock on behalf of and for the account of another, or who purchases cattle in another state or country and imports these cattle into this state for resale.

. "Director" means the director of agriculture or a duly authorized representative.

. "Fixed or established place of business" for the purpose of this chapter means any permanent warehouse, building, or structure, at which necessary and appropriate equipment and fixtures are maintained for properly handling those agricultural products generally dealt in, and at which supplies of the agricultural products being usually transported are stored, offered for sale, sold, delivered, and generally dealt with in quantities reasonably adequate for and usually carried for the requirements of such a business, and that is recognized as a permanent business at such place, and carried on as such in good faith and not for the purpose of evading this chapter, and where specifically designated personnel are available to handle transactions concerning those agricultural products generally dealt in, which personnel are available during designated and appropriate hours to that business, and shall not mean a residence, barn, garage, tent, temporary stand or other temporary quarters, any railway car, or permanent quarters occupied pursuant to any temporary arrangement.

. "Licensed public weighmaster" means any person, licensed under the provisions of chapter 15.80 RCW, who weighs, measures, or counts any commodity or thing and issues therefor a signed certified statement, ticket, or memorandum of weight, measure, or count upon which the purchase or sale of any commodity or upon which the basic charge of payment for services rendered is based.

. "Licensee" means any person or business licensed under this chapter as a commission merchant, dealer, limited dealer, broker, cash buyer, or agent.

. "Limited dealer" means any person who buys, agrees to buy, or pays for the production or increase of any agricultural product by paying to the consignor at the time of obtaining possession or control of any agricultural product the full agreed price of the agricultural product and who operates under the alternative bonding provision in RCW 20.01.211.

. "Person" means any natural person, firm, partnership, exchange, association, trustee, receiver, corporation, and any member, officer, or employee thereof or assignee for the benefit of creditors.

. "Pooling contract" means any written agreement whereby a consignor delivers a horticultural product to a commission merchant under terms whereby the commission merchant may commingle the consignor's horticultural products for sale with others similarly agreeing, which must include all of the following:

.. A delivery receipt for the consignor that indicates the variety of horticultural product delivered, the number of containers, or the weight and tare thereof;

.. Horticultural products received for handling and sale in the fresh market shall be accounted for to the consignor with individual pack-out records that shall include variety, grade, size, and date of delivery. Individual daily packing summaries shall be available within forty-eight hours after packing occurs. However, platform inspection shall be acceptable by mutual contract agreement on small deliveries to determine variety, grade, size, and date of delivery;

.. Terms under which the commission merchant may use his or her judgment in regard to the sale of the pooled horticultural product;

.. The charges to be paid by the consignor as filed with the state of Washington;

.. A provision that the consignor shall be paid for his or her pool contribution when the pool is in the process of being marketed in direct proportion, not less than eighty percent of his or her interest less expenses directly incurred, prior liens, and other advances on the grower's crop unless otherwise mutually agreed upon between grower and commission merchant.

. "Processor" means any person, firm, company, or other organization that purchases agricultural crops from a consignor and that cans, freezes, dries, dehydrates, cooks, presses, powders, or otherwise processes those crops in any manner whatsoever for eventual resale.

. "Producer" means any person engaged in the business of growing or producing any agricultural product, whether as the owner of the products, or producing the products for others holding the title thereof.

. "Proprietary seed" means any seed that is protected under the Federal Plant Variety Protection Act.

. "Retail merchant" means any person operating from a bona fide or established place of business selling agricultural products twelve months of each year.

. "Seed" means agricultural seed, flower seed, vegetable seed, other crop seed, and seeds, as defined in chapter 15.49 RCW.

. "Seed bailment contract" means any contract meeting the requirements of chapter 15.48 RCW.

. "Seed clean out" means the process of removing impurities from raw seed product.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20568[2011 c 336 § 568]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5374-S.SL.pdf?cite=2011%20c%20103%20§%2039[2011 c 103 § 39]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6339.SL.pdf?cite=2004%20c%20212%20§%201[2004 c 212 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1100-S.SL.pdf?cite=2003%20c%20395%20§%201[2003 c 395 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1142-S.SL.pdf?cite=1991%20c%20174%20§%201[1991 c 174 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c354.pdf?cite=1989%20c%20354%20§%2037[1989 c 354 § 37]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c178.pdf?cite=1986%20c%20178%20§%206[1986 c 178 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c412.pdf?cite=1985%20c%20412%20§%208[1985 c 412 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c305.pdf?cite=1983%20c%20305%20§%201[1983 c 305 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c194.pdf?cite=1982%20c%20194%20§%201[1982 c 194 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c296.pdf?cite=1981%20c%20296%20§%2030[1981 c 296 § 30]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c115.pdf?cite=1979%20ex.s.%20c%20115%20§%201[1979 ex.s. c 115 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c304.pdf?cite=1977%20ex.s.%20c%20304%20§%201[1977 ex.s. c 304 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c102.pdf?cite=1974%20ex.s.%20c%20102%20§%202[1974 ex.s. c 102 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c182.pdf?cite=1971%20ex.s.%20c%20182%20§%201[1971 ex.s. c 182 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c240.pdf?cite=1967%20c%20240%20§%2040[1967 c 240 § 40]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c232.pdf?cite=1963%20c%20232%20§%201[1963 c 232 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%201[1959 c 139 § 1]; ]

== 20.01.020 - Rules and regulations—Enforcement of chapter—Interference prohibited.
The director, but not his or her duly authorized representative, may adopt such rules and regulations as are necessary to carry out the purpose of this chapter. It shall be the duty of the director to enforce and carry out the provisions of this chapter, rules and regulations adopted hereunder. No person shall interfere with the director when he or she is performing or carrying out duties imposed on him or her by this chapter, rules and regulations adopted hereunder.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20569[2011 c 336 § 569]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%202[1959 c 139 § 2]; ]

== 20.01.030 - Exemptions.
This chapter does not apply to:

. Any cooperative marketing associations or federations incorporated under, or whose articles of incorporation and bylaws are equivalent to, the requirements of chapter 23.86 RCW, except as to that portion of the activities of the association or federation that involve the handling or dealing in the agricultural products of nonmembers of the organization: PROVIDED, That the associations or federations may purchase up to fifteen percent of their gross from nonmembers for the purpose of filling orders: PROVIDED FURTHER, That if the cooperative or association acts as a processor as defined in RCW 20.01.500(2) and markets the processed agricultural crops on behalf of the grower or its own behalf, the association or federation is subject to the provisions of RCW 20.01.500 through 20.01.560 and the license provision of this chapter excluding bonding provisions: PROVIDED FURTHER, That none of the foregoing exemptions in this subsection apply to any such cooperative or federation dealing in or handling grain in any manner, and not licensed under the provisions of chapter 22.09 RCW;

. Any person who sells exclusively his or her own agricultural products as the producer thereof;

. Any public livestock market operating under a bond required by law or a bond required by the United States to secure the performance of the public livestock market's obligation. However, any such market operating as a livestock dealer or order buyer, or both, is subject to all provisions of this chapter except for the payment of the license fee required in RCW 20.01.040;

. Any retail merchant having a bona fide fixed or permanent place of business in this state, but only for the retail merchant's retail business conducted at such fixed or established place of business;

. Any person buying farm products for his or her own use or consumption;

. Any warehouse operator or grain dealer licensed under the state grain warehouse act, chapter 22.09 RCW, with respect to his or her handling of any agricultural product as defined under that chapter;

. Any nursery dealer who is required to be licensed under the horticultural laws of the state with respect to his or her operations as such licensee;

. Any person licensed under the now existing dairy laws of the state with respect to his or her operations as such licensee;

. Any producer who purchases less than fifteen percent of his or her volume to complete orders;

. Any person, association, or corporation regulated under chapter 67.16 RCW and the rules adopted thereunder while performing acts regulated by that chapter and the rules adopted thereunder;

. Any domestic winery, as defined in RCW 66.04.010, licensed under Title 66 RCW, with respect to its transactions involving agricultural products used by the domestic winery in making wine;

. Any person licensed as a marijuana producer or processor under RCW 69.50.325 with respect to the operations under such license. The definitions in RCW 69.50.101 apply to this subsection (12).

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6505.SL.pdf?cite=2014%20c%20140%20§%2035[2014 c 140 § 35]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%2038[2013 c 23 § 38]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20570[2011 c 336 § 570]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5678-S.SL.pdf?cite=1993%20c%20104%20§%201[1993 c 104 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c354.pdf?cite=1989%20c%20354%20§%2038[1989 c 354 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c307.pdf?cite=1989%20c%20307%20§%2037[1989 c 307 § 37]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c254.pdf?cite=1988%20c%20254%20§%2010[1988 c 254 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c305.pdf?cite=1983%20c%20305%20§%202[1983 c 305 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c194.pdf?cite=1982%20c%20194%20§%202[1982 c 194 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c296.pdf?cite=1981%20c%20296%20§%2031[1981 c 296 § 31]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c115.pdf?cite=1979%20ex.s.%20c%20115%20§%202[1979 ex.s. c 115 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c304.pdf?cite=1977%20ex.s.%20c%20304%20§%202[1977 ex.s. c 304 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c7.pdf?cite=1975%201st%20ex.s.%20c%207%20§%2018[1975 1st ex.s. c 7 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c182.pdf?cite=1971%20ex.s.%20c%20182%20§%202[1971 ex.s. c 182 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c132.pdf?cite=1969%20ex.s.%20c%20132%20§%201[1969 ex.s. c 132 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c240.pdf?cite=1967%20c%20240%20§%2041[1967 c 240 § 41]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%203[1959 c 139 § 3]; ]

== 20.01.038 - License required of persons dealing in livestock, hay, grain, or straw.
Any person who deals in livestock, hay, grain or straw, other than the producer or grower thereof, shall license as a dealer or commission merchant and shall be subject to all the provisions of this chapter regulating such a licensee.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c232.pdf?cite=1963%20c%20232%20§%209[1963 c 232 § 9]; ]

== 20.01.040 - License—Generally.
No person may act as a commission merchant, dealer, broker, cash buyer, or agent without a license. Any person applying for such a license shall file an application with the director prior to conducting business pursuant to this chapter. No application shall be considered complete unless an effective bond or other acceptable form of security is also filed with the director, as provided under RCW 20.01.210, 20.01.211, or 20.01.212. Each license issued under this chapter shall require renewal on or before the renewal date prescribed by the director by rule. License fees shall be prorated where necessary to accommodate staggered renewals of a license or licenses. The application shall be accompanied by a license fee as prescribed by the director by rule.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5713-S.SL.pdf?cite=1991%20c%20109%20§%2016[1991 c 109 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c354.pdf?cite=1989%20c%20354%20§%2039[1989 c 354 § 39]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c393.pdf?cite=1987%20c%20393%20§%2013[1987 c 393 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c305.pdf?cite=1983%20c%20305%20§%203[1983 c 305 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c115.pdf?cite=1979%20ex.s.%20c%20115%20§%203[1979 ex.s. c 115 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c102.pdf?cite=1974%20ex.s.%20c%20102%20§%203[1974 ex.s. c 102 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c182.pdf?cite=1971%20ex.s.%20c%20182%20§%203[1971 ex.s. c 182 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%204[1959 c 139 § 4]; ]

== 20.01.050 - License renewals.
If an application for renewal of a commission merchant, dealer, broker or cash buyer license is not filed prior to the prescribed renewal date a penalty of twenty-five percent shall be assessed and added to the original fee and shall be paid by the applicant before the renewal license shall be issued.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5713-S.SL.pdf?cite=1991%20c%20109%20§%2017[1991 c 109 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%205[1959 c 139 § 5]; ]

== 20.01.060 - Licensee in one class may obtain license in another—Additional fee.
Any person licensed as a commission merchant, dealer, or broker, in the manner prescribed in this chapter, may apply for and secure a license in any or all of the remaining such classifications upon payment of an additional fee of twenty-five dollars for each such additional classification: PROVIDED, That the applicant's principal license shall be in that classification requiring the greatest license fee. Such applicant shall further comply with those parts of this chapter regulating the licensing of the other particular classifications involved.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c115.pdf?cite=1979%20ex.s.%20c%20115%20§%204[1979 ex.s. c 115 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c304.pdf?cite=1977%20ex.s.%20c%20304%20§%203[1977 ex.s. c 304 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c102.pdf?cite=1974%20ex.s.%20c%20102%20§%204[1974 ex.s. c 102 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c182.pdf?cite=1971%20ex.s.%20c%20182%20§%204[1971 ex.s. c 182 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%206[1959 c 139 § 6]; ]

== 20.01.070 - Application for license—Contents.
Application for a license shall be on a form prescribed by the director and shall state the full name of the person applying for such license and if the applicant is an individual, receiver, trustee, firm, exchange, partnership, association or corporation, the full name of each member of the firm or partnership, or the names of the officers of the exchange, association or corporation shall be given in the application. Such application shall further state the principal business address of the applicant in the state and elsewhere and the name or names of the person authorized to receive and accept service of summons and legal notices of all kinds for the applicant and any other necessary information prescribed by the director.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%207[1959 c 139 § 7]; ]

== 20.01.080 - Commission merchant's schedule of commissions and charges—Changes, posting.
Any person applying for a commission merchant's license shall include in his or her application a schedule of commissions, together with an itemized list of all charges for services to be rendered to a consignor and shall post a copy of such charges on his or her premises in a conspicuous place where it is clearly visible and available to consignors. In addition to the posting of the itemized list of charges, such list shall be distributed to each consignor along with each contract entered into between the consignor and the commission merchant. Such commissions and charges shall not be changed or varied for the license period except by written contract between the consignor or his or her agent and the licensee or thirty days after written notice to the director, and proper posting of such changes, as prescribed by the director, on the licensee's premises. Charges for services rendered and not listed on the schedule of commissions and charges filed with the director, or for increases in charges listed and filed which are directly caused by increases in labor rates or in cost of materials which occur after the signing of the contract by the grower, shall be rendered only on an actual cost to the licensee basis.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c254.pdf?cite=1988%20c%20254%20§%2016[1988 c 254 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c304.pdf?cite=1977%20ex.s.%20c%20304%20§%204[1977 ex.s. c 304 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c182.pdf?cite=1971%20ex.s.%20c%20182%20§%205[1971 ex.s. c 182 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%208[1959 c 139 § 8]; ]

== 20.01.086 - Waiver of reporting, accounting, and recordkeeping requirements prohibited.
Except where specifically provided in this chapter, the reporting, accounting, and recordkeeping requirements of this chapter, being matters of public interest, may not be waived by contract between the consignor and/or the commission merchant or dealer.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c304.pdf?cite=1977%20ex.s.%20c%20304%20§%205[1977 ex.s. c 304 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c102.pdf?cite=1974%20ex.s.%20c%20102%20§%208[1974 ex.s. c 102 § 8]; ]

== 20.01.090 - Agent to disclose principal licensee and his endorsement.
Any person applying for an agent's license shall include the name and address of the principal licensee represented or sought to be represented by such agent and the written endorsement or nomination of such principal licensee.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%209[1959 c 139 § 9]; ]

== 20.01.100 - Issuance of license—Expiration date—Fraudulent application grounds for refusal, revocation.
The director, upon his or her satisfaction that the applicant has met the requirements of this chapter and rules and regulations adopted hereunder, shall issue a license entitling the applicant to carry on the business described on the application. Such license shall expire on December 31st following the issuance of the license, provided that it has not been revoked or suspended prior thereto, by the director, after due notice and hearing. Fraud and misrepresentation in making an application for a license shall be cause for refusal to grant a license or revocation of license granted pursuant to a fraudulent application after due notice and hearing.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20571[2011 c 336 § 571]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2010[1959 c 139 § 10]; ]

== 20.01.110 - Publication of list of licensees and rules—Posting license.
The director may publish a list, as often as he or she deems necessary, of all persons licensed under this chapter together with all the necessary rules and regulations concerning the enforcement of this chapter. Each person licensed under the provisions of this chapter shall post his or her license or a copy thereof in his or her place or places of business in plain view of the public.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20572[2011 c 336 § 572]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2011[1959 c 139 § 11]; ]

== 20.01.120 - Vehicle license plates.
The licensee shall prominently display license plates issued by the director on the front and back of any vehicle used by the licensee to transport upon public highways unprocessed agricultural products which he or she has not produced as a producer of such agricultural products. If the licensee operates more than one vehicle to transport unprocessed agricultural products on public highways he or she shall apply to the director for license plates for each such additional vehicle. Such additional license plates shall be issued to the licensee at the actual cost to the department for such license plates and necessary handling charges. Such license plates are not transferable to any other person and may be used only on the licensee's vehicle or vehicles. The display of such license plates on the vehicle or vehicles of a person whose license has been revoked, or the failure to surrender such license plates forthwith to the department after such revocation, shall be deemed a violation of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20573[2011 c 336 § 573]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2012[1959 c 139 § 12]; ]

== 20.01.125 - Hay or straw—Certified vehicle tare and load weights—Violations.
Every dealer and commission merchant dealing in hay or straw shall obtain a certified vehicle tare weight and a certified vehicle gross weight for each load hauled and shall furnish the consignor with a copy of such certified weight ticket within seventy-two hours after taking delivery. It shall be a violation of this chapter for any licensee to transport hay or straw which has been purchased by weight without having obtained a certified weight ticket from the first licensed public weighmaster which would be encountered on the ordinary route to the destination where the hay or straw is to be unloaded. If agreed upon in writing between a dealer or commission merchant and a grower or consigner, a certified vehicle tare weight and certified vehicle gross weight may be obtained from a hay or straw processing facility with a scale approved by the director.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2923.SL.pdf?cite=2008%20c%2026%20§%201[2008 c 26 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c178.pdf?cite=1986%20c%20178%20§%207[1986 c 178 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c182.pdf?cite=1971%20ex.s.%20c%20182%20§%206[1971 ex.s. c 182 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c232.pdf?cite=1963%20c%20232%20§%208[1963 c 232 § 8]; ]

== 20.01.130 - Disposition of moneys.
All fees and other moneys received by the department under this chapter shall be paid to the director and used solely for the purpose of carrying out this chapter and the rules adopted under this chapter. All civil fines received by the courts as the result of notices of infractions issued by the director shall be paid to the director, less any mandatory court costs and assessments.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1100-S.SL.pdf?cite=2003%20c%20395%20§%202[2003 c 395 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5968-S.SL.pdf?cite=1993%20sp.s.%20c%2024%20§%20929[1993 sp.s. c 24 § 929]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c178.pdf?cite=1986%20c%20178%20§%208[1986 c 178 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c142.pdf?cite=1973%20c%20142%20§%201[1973 c 142 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c182.pdf?cite=1971%20ex.s.%20c%20182%20§%207[1971 ex.s. c 182 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2013[1959 c 139 § 13]; ]

== 20.01.140 - Change in organization of firm to be reported.
Any change in the organization of any firm, association, exchange, corporation, or partnership licensed under this chapter shall be reported to the director and the licensee's surety or sureties within thirty days.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1100-S.SL.pdf?cite=2003%20c%20395%20§%203[2003 c 395 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2014[1959 c 139 § 14]; ]

== 20.01.150 - Denial, suspension, revocation of licenses, probationary orders—Authority.
The director is authorized to deny, suspend, or revoke a license or issue conditional or probationary orders in the manner prescribed herein, in any case in which he or she finds that there has been a failure and/or refusal to comply with the requirements of this chapter, rules or regulations adopted hereunder.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20574[2011 c 336 § 574]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2015[1959 c 139 § 15]; ]

== 20.01.160 - Denial, suspension, revocation of licenses, probationary orders—Procedure.
In all proceedings for revocation, suspension, or denial of a license, or the issuance of a conditional or probationary order, the licensee or applicant shall be given an opportunity to be heard and may be represented by counsel. The director shall give the licensee or applicant twenty days' notice in writing and such notice shall specify the charges or reasons for the hearing for such revocation, suspension, denial or the issuance of a conditional or probationary order. The notice shall also state the date, time and place where such hearing is to be held. A copy of such notice shall be mailed to the licensee's surety. Such hearings shall be held in the city of Olympia, unless a different place is fixed by the director.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2016[1959 c 139 § 16]; ]

== 20.01.170 - Denial, suspension, revocation of licenses, probationary orders—Subpoenas, witnesses, testimony, fees.
The director may issue subpoenas to compel the attendance of witnesses, and/or the production of books or documents, anywhere in the state. The licensee or applicant shall have opportunity to make his or her defense, and may have such subpoenas issued as he or she desires. Subpoenas shall be served in the same manner as in civil cases in the superior court. Witnesses shall testify under oath which may be administered by the director. Testimony shall be recorded and may be taken by deposition under such rules as the director may prescribe. Witnesses, except complaining witnesses, shall be entitled to fees for attendance and travel, as provided for in chapter 2.40 RCW, as enacted or hereafter amended.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20575[2011 c 336 § 575]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c232.pdf?cite=1963%20c%20232%20§%202[1963 c 232 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2017[1959 c 139 § 17]; ]

== 20.01.180 - Denial, suspension, revocation of licenses, probationary orders—Findings and conclusions—Record.
The director shall hear and determine the charges, make findings and conclusions upon the evidence produced, and file them in his or her office, together with a record of all of the evidence, and serve upon the accused a copy of such findings and conclusions.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20576[2011 c 336 § 576]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2018[1959 c 139 § 18]; ]

== 20.01.190 - Denial, suspension, revocation of licenses, probationary orders—Final action in writing—Appeal to superior court.
The revocation, suspension or denial of a license, or the issuance of conditional or probationary orders, shall be in writing signed by the director, stating the grounds upon which such order is based and the aggrieved person shall have the right to appeal from such order within fifteen days after a copy thereof is served upon him or her, to the superior court of Thurston county or the county in which the hearing was held. A copy of such findings shall be mailed to the licensee's surety. In such appeal the entire record shall be certified by the director to the court, and the review on appeal shall be confined to the evidence adduced at the hearing before the director.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20577[2011 c 336 § 577]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2019[1959 c 139 § 19]; ]

== 20.01.200 - Denial, suspension, revocation of licenses, probationary orders—Appellate review.
Appellate review of the judgment of the superior court may be sought as provided in other civil cases.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c202.pdf?cite=1988%20c%20202%20§%2024[1988 c 202 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971c81.pdf?cite=1971%20c%2081%20§%2066[1971 c 81 § 66]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2020[1959 c 139 § 20]; ]

== 20.01.205 - License suspension—Noncompliance with support order—Reissuance.
The director shall immediately suspend the license or certificate of a person who has been certified pursuant to RCW 74.20A.320 by the department of social and health services as a person who is not in compliance with a support order. If the person has continued to meet all other requirements for reinstatement during the suspension, reissuance of the license or certificate shall be automatic upon the director's receipt of a release issued by the department of social and health services stating that the licensee is in compliance with the order.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5374-S.SL.pdf?cite=2011%20c%20103%20§%2022[2011 c 103 § 22]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3901.SL.pdf?cite=1997%20c%2058%20§%20855[1997 c 58 § 855]; ]

== 20.01.210 - Commission merchants, dealers—Bonds.
. Before the license is issued to any commission merchant or dealer, or both, the applicant shall execute and deliver to the director a surety bond executed by the applicant as principal and by a surety company qualified and authorized to do business in this state as surety. The bond shall be to the state for the benefit of qualified consignors of agricultural products in this state. All such sureties on a bond, as provided in this section, shall be released and discharged from all liability to the state accruing on such bond by giving notice to the principal and the director by certified mail. Upon receipt of such notice the director shall notify the surety and the principal of the effective date of termination which shall be thirty days from the receipt of such notice by the director, but this shall not relieve, release, or discharge the surety from any liability already accrued or which shall accrue before the expiration period provided for in this subsection.

. The bond for a commission merchant or dealer in hay, straw, or seed shall be not less than fifteen thousand dollars. The actual amount of such bond shall be determined by dividing the annual dollar volume of the licensee's net proceeds or net payments due consignors by twelve and increasing that amount to the next multiple of five thousand dollars. The bond for a new commission merchant or dealer in hay, straw, or seed shall be subject to increase at any time during the licensee's first year of operation based on the average of business volume for any three months. Except as provided in subsection (3) of this section, the bond shall be not less than ten thousand dollars for any other dealer.

. The bond for a commission merchant or dealer in livestock shall be not less than ten thousand dollars. The actual amount of such bond shall be determined in accordance with the formula set forth in the packers and stockyard act of 1921 (7 U.S.C. 181), except that a commission merchant or dealer in livestock shall increase the commission merchant's or dealer's bond by five thousand dollars for each agent the commission merchant or dealer has endorsed under RCW 20.01.090. A dealer who also acts as an order buyer for other persons who are also licensed and bonded under this chapter or under the packers and stockyards act (7 U.S.C. 181) may subtract that amount of business from the annual gross volume of purchases reported to the director in determining the amount of bond coverage that must be provided and maintained for the purposes of this chapter.

. The bond for a commission merchant handling agricultural products other than livestock, hay, straw, or seed shall not be less than ten thousand dollars. The bond for a dealer handling agricultural products other than livestock, hay, straw, or seed shall not be less than ten thousand dollars. The actual amount of such bond shall be determined by dividing the annual dollar volume of the licensee's net proceeds or net payments due consignors by fifty-two and increasing that amount to the next multiple of two thousand dollars. However, bonds above twenty-six thousand dollars shall be increased to the next multiple of five thousand dollars.

. When the annual dollar volume of any commission merchant or dealer reaches two million six hundred thousand dollars, the amount of the bond required above this level shall be on a basis of ten percent of the amount arrived at by applying the appropriate formula.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6339.SL.pdf?cite=2004%20c%20212%20§%202[2004 c 212 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5713-S.SL.pdf?cite=1991%20c%20109%20§%2018[1991 c 109 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c178.pdf?cite=1986%20c%20178%20§%209[1986 c 178 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c305.pdf?cite=1983%20c%20305%20§%204[1983 c 305 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c194.pdf?cite=1982%20c%20194%20§%203[1982 c 194 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c304.pdf?cite=1977%20ex.s.%20c%20304%20§%206[1977 ex.s. c 304 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c102.pdf?cite=1974%20ex.s.%20c%20102%20§%205[1974 ex.s. c 102 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c182.pdf?cite=1971%20ex.s.%20c%20182%20§%208[1971 ex.s. c 182 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c232.pdf?cite=1963%20c%20232%20§%205[1963 c 232 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2021[1959 c 139 § 21]; ]

== 20.01.211 - Alternative bonding provision for certain dealers.
. In lieu of the bonding provision required by RCW 20.01.210, any dealer who buys, agrees to buy, or pays for the production or increase of any agricultural product by paying to the consignor at the time of obtaining possession or control of any agricultural product the full agreed price of the agricultural product may file a bond in an amount equal to the dealer's maximum monthly purchases, divided by twelve, but the minimum bond under this section shall be no less than ten thousand dollars.

. Any dealer using the bonding provisions of this section shall file an affidavit with the director that sets forth the dealer's maximum monthly purchases from or payments to consignors. The affidavit shall be filed at the time of application and with each renewal.

. Any dealer bonded under this section who is found to be in violation of this chapter shall be required to comply with the bonding requirements of RCW 20.01.210 for a minimum of two years.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1100-S.SL.pdf?cite=2003%20c%20395%20§%204[2003 c 395 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c305.pdf?cite=1983%20c%20305%20§%205[1983 c 305 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c304.pdf?cite=1977%20ex.s.%20c%20304%20§%2016[1977 ex.s. c 304 § 16]; ]

== 20.01.212 - Livestock dealers bonded under federal law.
If an applicant for a commission merchant's and/or dealer's license is bonded as a livestock dealer or packer under the provisions of the packers and stockyards act of 1921 (7 U.S.C. 181), as amended, on June 13, 1963, and acts as a commission merchant, packer, and/or a dealer only in livestock as defined in said packers and stockyards act of 1921 (7 U.S.C. 181), the director may accept such bond in lieu of the bond required in RCW 20.01.210 as good and sufficient and issue the applicant a license limited solely to dealing in livestock. A dealer buying and selling livestock who has furnished a bond as required by the packers and stockyards administration to cover acting as order buyer as well as dealer may also act as an order buyer for others under the provisions of this chapter, and all persons who act as order buyers of livestock shall license under this chapter as a livestock dealer: PROVIDED, That the applicant shall furnish the director with a bond approved by the United States secretary of agriculture. Such bond shall be in a minimum amount of ten thousand dollars. It shall be a violation for the licensee to act as a commission merchant and/or dealer in any other agricultural commodity without first having notified the director and furnishing him or her with a bond as required under the provisions of RCW 20.01.210, and failure to furnish the director with such bond shall be cause for the immediate suspension of the licensee's license, and revocation subject to a hearing.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20578[2011 c 336 § 578]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5713-S.SL.pdf?cite=1991%20c%20109%20§%2019[1991 c 109 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c304.pdf?cite=1977%20ex.s.%20c%20304%20§%207[1977 ex.s. c 304 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c182.pdf?cite=1971%20ex.s.%20c%20182%20§%209[1971 ex.s. c 182 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c232.pdf?cite=1963%20c%20232%20§%206[1963 c 232 § 6]; ]

== 20.01.214 - Appeal from rejected bond claim.
Upon any bond claim being denied by the director the claimant must appeal such action to the superior court in the county where this claimant resides in this state or Thurston county, within sixty days after receipt of written notice of such rejection or such rejection shall become final and binding upon the claimant.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c182.pdf?cite=1971%20ex.s.%20c%20182%20§%2010[1971 ex.s. c 182 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c232.pdf?cite=1963%20c%20232%20§%207[1963 c 232 § 7]; ]

== 20.01.220 - Action on bond for fraud.
Any consignor of an agricultural product claiming to be injured by the fraud of any commission merchant and/or dealer or their agents may bring action upon said bond against principal, surety, and agent in any court of competent jurisdiction to recover the damages caused by such fraud. Any consignor undertaking such an action shall name the director as a party.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c178.pdf?cite=1986%20c%20178%20§%2010[1986 c 178 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c194.pdf?cite=1982%20c%20194%20§%204[1982 c 194 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2022[1959 c 139 § 22]; ]

== 20.01.230 - Action on bond for failure to comply with chapter.
The director or any consignor of an agricultural product may also bring action upon said bond against both principal and surety in any court of competent jurisdiction to recover the damages caused by any failure to comply with the provisions of this chapter or the rules adopted hereunder. Any consignor undertaking such an action shall name the director as a party.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c178.pdf?cite=1986%20c%20178%20§%2011[1986 c 178 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2023[1959 c 139 § 23]; ]

== 20.01.240 - Claims against commission merchant, dealer.
. Any consignor who believes he or she has a valid claim against the bond of a commission merchant or dealer shall file a claim with the director.

. In the case of a claim against the bond of a commission merchant or dealer in hay or straw, default occurs when the licensee fails to make payment within thirty days of the date the licensee took possession of the hay or straw or at a date agreed to by both the consignor and commission merchant or dealer in written contract. In the case of a claim against a limited dealer in hay or straw, default occurs when the licensee fails to make payment upon taking possession of the hay or straw.

. Upon the filing of a claim under this subsection against any commission merchant or dealer handling any agricultural product, the director may, after investigation, proceed to ascertain the names and addresses of all consignor creditors of such commission merchant and dealer, together with the amounts due and owing to them by such commission merchant and dealer, and shall request all such consignor creditors to file a verified statement of their respective claims with the director. Such request shall be addressed to each known consignor creditor at his or her last known address.

. For claims against a bond that have been filed by consignors prior to the sixty-day deadline established in RCW 20.01.250, the director shall investigate the claims and, within thirty days of verifying the claims, demand payment for the valid claims by the licensee's surety. The director shall distribute the proceeds of the valid bond claims to the claimants on a pro rata basis within the limits of the claims and the availability of the bond proceeds. If a claim is filed after the sixty-day deadline established in RCW 20.01.250, the director may investigate the claim and may demand payment for a valid claim. The director shall distribute the proceeds of any such payment made by the surety to the claimant on a first-to-file, first-to-be-paid basis within the limits of the claim and the availability of any bond proceeds remaining after the pro rata distribution. All distributions made by the director under this subsection are subject to RCW 20.01.260.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20579[2011 c 336 § 579]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1100-S.SL.pdf?cite=2003%20c%20395%20§%205[2003 c 395 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c178.pdf?cite=1986%20c%20178%20§%2012[1986 c 178 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2024[1959 c 139 § 24]; ]

== 20.01.250 - Failure of consignor to file claim, time limitation.
If a consignor creditor so addressed fails, refuses or neglects to file in the office of the director his or her verified claim as requested by the director within sixty days from the date of such request, the director shall thereupon be relieved of further duty or action hereunder on behalf of said consignor creditor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20580[2011 c 336 § 580]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2025[1959 c 139 § 25]; ]

== 20.01.260 - Director not liable if circumstances prevent ascertainment of creditors—Demand on bond.
Where by reason of the absence of records, or other circumstances making it impossible or unreasonable for the director to ascertain the names and addresses of all said consignor creditors, the director after exerting due diligence and making reasonable inquiry to secure said information from all reasonable and available sources, may make demand on said bond on the basis of information then in his or her possession, and thereafter shall not be liable or responsible for claims or the handling of claims which may subsequently appear or be discovered.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20581[2011 c 336 § 581]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2026[1959 c 139 § 26]; ]

== 20.01.270 - Demand on bond after claims ascertained—Power of director to settle, compromise.
Upon ascertaining all claims and statements in the manner herein set forth, the director may then make demand upon the bond on behalf of those claimants whose statements have been filed, and shall have the power to settle or compromise said claims with the surety company on the bond, and is empowered in such cases to execute and deliver a release and discharge of the bond involved.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2027[1959 c 139 § 27]; ]

== 20.01.280 - Action on bond after refusal to pay—New bond, failure to file.
Upon the refusal of the surety company to pay the demand the director may thereupon bring an action on the bond in behalf of said consignor creditors. Upon any action being commenced on said bond the director may require the filing of a new bond and immediately upon the recovery in any action on such bond such commission merchant and/or dealer shall file a new bond and upon failure to file the same within ten days in either case such failure shall constitute grounds for the suspension or revocation of his or her license.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20582[2011 c 336 § 582]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2028[1959 c 139 § 28]; ]

== 20.01.300 - Verified complaints of consignor—Investigations.
For the purpose of enforcing the provisions of this chapter the director is authorized to receive verified complaints from any consignor against any commission merchant, dealer, broker, cash buyer, or agent or any person, assuming or attempting to act as such, and upon receipt of such verified complaint shall have full authority to make any and all necessary investigations relative to the said complaint.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2030[1959 c 139 § 30]; ]

== 20.01.310 - Oaths, testimony, witnesses, subpoenas—Contempt proceedings—Records as evidence.
The director or his or her authorized agents are empowered to administer oaths of verification on said complaints. He or she shall have full authority to administer oaths and take testimony thereunder, to issue subpoenas in the manner prescribed in RCW 20.01.170 requiring attendance of witnesses before him or her, together with all books, memoranda, papers, and other documents, articles, or instruments; to compel the disclosure by such witnesses of all facts known to them relative to the matters under investigation, and all parties disobeying the orders or subpoenas of said director shall be guilty of contempt and shall be certified to the superior court of the state for punishment for such contempt. Copies of records, audits and reports of audits, inspection certificates, certified reports, findings, and all papers on file in the office of the director shall be prima facie evidence of the matters therein contained, and may be admitted into evidence in any hearing provided in this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20583[2011 c 336 § 583]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2031[1959 c 139 § 31]; ]

== 20.01.320 - Investigations, examinations, inspections—Search warrants—Subpoenas.
The director on his or her own motion or upon the verified complaint of any interested party may investigate, examine, or inspect (1) any transaction involving solicitation, receipt, sale, or attempted sale of agricultural products by any person or persons acting or assuming to act as a commission merchant, dealer, broker, cash buyer, or agent; (2) the failure to make proper and true account of sales and settlement thereof as required under this chapter or rules adopted under this chapter; (3) the intentional making of false statements as to conditions and quantity of any agricultural products received or in storage; (4) the intentional making of false statements as to market conditions; (5) the failure to make payment for products within the time required by this chapter; (6) any and all other injurious transactions. In furtherance of such an investigation, examination, or inspection, the director or an authorized representative may examine that portion of the ledgers, books, accounts, memoranda and other documents, agricultural products, scales, measures, and other articles and things used in connection with the business of the person relating to the transactions involved. For the purpose of the investigation the director shall at all times have free and unimpeded access to all buildings, yards, warehouses, storage, and transportation facilities or any other place where agricultural products are kept, stored, handled, or transported. If the director is denied access, the director may apply to any court of competent jurisdiction for a search warrant authorizing access to the premises and records. The court may upon the application issue the search warrant for the purposes requested. The director may also, for the purpose of the investigation, issue subpoenas to compel the attendance of witnesses, as provided in RCW 20.01.170, or the production of books or documents, anywhere in the state.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1100-S.SL.pdf?cite=2003%20c%20395%20§%206[2003 c 395 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2032[1959 c 139 § 32]; ]

== 20.01.330 - Denial, revocation, suspension, or condition of licenses, probationary orders—Grounds.
The director may refuse to grant a license or renew a license and may revoke or suspend a license or issue a conditional or probationary order if he or she is satisfied after a hearing, as herein provided, of the existence of any of the following facts, which are hereby declared to be a violation of this chapter:

. That fraudulent charges or returns have been made by the applicant, or licensee, for the handling, sale or storage of, or for rendering of any service in connection with the handling, sale or storage of any agricultural product.

. That the applicant, or licensee, has failed or refused to render a true account of sales, or to make a settlement thereon, or to pay for agricultural products received, within the time and in the manner required by this chapter.

. That the applicant, or licensee, has made any false statement as to the condition, quality, or quantity of agricultural products received, handled, sold, or stored by him or her.

. That the applicant, or licensee, directly or indirectly has purchased for his or her own account agricultural products received by him or her upon consignment without prior authority from the consignor together with the price fixed by consignor or without promptly notifying the consignor of such purchase. This shall not prevent any commission merchant from taking to account of sales, in order to close the day's business, miscellaneous lots or parcels of agricultural products remaining unsold, if such commission merchant shall forthwith enter such transaction on his or her account of sales.

. That the applicant, or licensee, has intentionally made any false or misleading statement as to the conditions of the market for any agricultural products.

. That the applicant, or licensee, has made fictitious sales or has been guilty of collusion to defraud the consignor.

. That a commission merchant to whom any consignment is made has reconsigned such consignment to another commission merchant and has received, collected, or charged by such means more than one commission for making the sale thereof, for the consignor, unless by written consent of such consignor.

. That the licensee was guilty of fraud or deception in the procurement of such license.

. That the licensee or applicant has failed or refused to file with the director a schedule of his or her charges for services in connection with agricultural products handled on account of or as an agent of another, or that the applicant, or licensee, has indulged in any unfair practice.

. That the licensee has rejected, without reasonable cause, or has failed or refused to accept, without reasonable cause, any agricultural product bought or contracted to be bought from a consignor by such licensee; or failed or refused, without reasonable cause, to furnish or provide boxes or other containers, or hauling, harvesting, or any other service contracted to be done by licensee in connection with the acceptance, harvesting, or other handling of said agricultural products bought or handled or contracted to be bought or handled; or has used any other device to avoid acceptance or unreasonably to defer acceptance of agricultural products bought or handled or contracted to be bought or handled.

. That the licensee has otherwise violated any provision of this chapter and/or rules and regulations adopted hereunder.

. That the licensee has knowingly employed an agent, as defined in this chapter, without causing said agent to comply with the licensing requirements of this chapter applicable to agents.

. That the applicant or licensee has, in the handling of any agricultural products, been guilty of fraud, deceit, or negligence.

. That the licensee has failed or refused, upon demand, to permit the director or his or her agents to make the investigations, examination, or audits, as provided in this chapter, or that the licensee has removed or sequestered any books, records, or papers necessary to any such investigations, examination, or audits, or has otherwise obstructed the same.

. That the licensee, without reasonable cause, has failed or refused to execute or carry out a lawful contract with a consignor.

. That the licensee has failed or refused to keep and maintain the records as required by this chapter and/or rules and regulations adopted hereunder.

. That the licensee has attempted payment by a check the licensee knows not to be backed by sufficient funds to cover such check.

. That the licensee has been guilty of fraud or deception in his or her dealings with purchasers including misrepresentation of goods as to grade, quality, weights, quantity, or any other essential fact in connection therewith.

. That the licensee has permitted a person to in fact operate his or her own separate business under cover of the licensee's license and bond.

. That a commission merchant or dealer has failed to furnish additional bond coverage within fifteen days of when it was requested in writing by the director.

. That the licensee has discriminated in the licensee's dealings with consignors on the basis of race, creed, color, national origin, sex, or the presence of any disability.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2390.SL.pdf?cite=2020%20c%20274%20§%203[2020 c 274 § 3]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20584[2011 c 336 § 584]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c354.pdf?cite=1989%20c%20354%20§%2040[1989 c 354 § 40]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c20.pdf?cite=1982%20c%2020%20§%201[1982 c 20 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c296.pdf?cite=1981%20c%20296%20§%2032[1981 c 296 § 32]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c304.pdf?cite=1977%20ex.s.%20c%20304%20§%208[1977 ex.s. c 304 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c182.pdf?cite=1971%20ex.s.%20c%20182%20§%2011[1971 ex.s. c 182 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2033[1959 c 139 § 33]; ]

== 20.01.340 - Denial, revocation, suspension of licenses, probationary orders—Previous violations as grounds.
Previous violation by the applicant or licensee, or by any person connected with him or her, of any of the provisions of this chapter and/or rules and regulations adopted hereunder, shall be good and sufficient ground for denial, suspension or revocation of a license, or the issuance of a conditional or probationary order.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20585[2011 c 336 § 585]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2034[1959 c 139 § 34]; ]

== 20.01.350 - Denial, revocation, suspension of licenses, probationary orders—Hearing, investigation—Findings required—Notices.
The director, after hearing or investigation, may refuse to grant a license or renewal thereof and may revoke or suspend any license or issue a conditional or probationary order, as the case may require, when he or she is satisfied that the licensee has executory or executed contracts for the purchase of agricultural products, or for the handling of agricultural products on consignment.

In such cases, if the director is satisfied that to permit the dealer or commission merchant to continue to purchase or to receive further shipments or deliveries of agricultural products would be likely to cause serious and irreparable loss to said consignor-creditors, or to consignors with whom the said dealer or commission merchant has said contracts, then the director within his or her discretion may thereupon and forthwith shorten the time herein provided for hearing upon an order to show cause why the license of said dealer or commission merchant should not be forthwith suspended, or revoked: PROVIDED, That the time of notice of said hearing, shall in no event be less than twenty-four hours, and the director shall, within that period, call a hearing at which the dealer or commission merchant proceeded against shall be ordered to show cause why the license should not be suspended, or revoked, or continued under such conditions and provisions, if any, as the director may consider just and proper and for the protection of the best interests of the producer-creditors involved. Said hearing, in the case of such emergency, may be called upon written notice, said notice to be served personally or by mail on the dealer or commission merchant involved, and may be held at the nearest office of the director or at such place as may be most convenient at the discretion of the director, for the attendance of all parties involved.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20586[2011 c 336 § 586]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2035[1959 c 139 § 35]; ]

== 20.01.360 - Order of revocation, suspension.
Any order revoking or suspending a license may, within the discretion of the director, be made conditional upon the settlement, adjustment or satisfaction of the consequence of the violation or violations as specified, and the operation of such an order may be deferred for such purpose. Any such order may contain provisions for modification or dismissal thereof upon presentation to the director of evidence that the matter of complaint has been settled, adjusted or withdrawn at any time before such order becomes final.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2036[1959 c 139 § 36]; ]

== 20.01.370 - Commission merchants—Recordkeeping.
Every commission merchant taking control of any agricultural products for sale as such commission merchant, shall promptly make and keep for a period of three years, beginning on the day the sale of the product is complete, a correct record showing in detail the following with reference to the handling, sale, or storage of such agricultural products:

. The name and address of the consignor.

. The date received.

. The quality and quantity delivered by the consignor, and where applicable the dockage, tare, grade, size, net weight, or quantity.

. An accounting of all sales, including dates, terms of sales, quality and quantity of agricultural products sold, and proof of payments received on behalf of the consignor.

. The terms of payment to the producer.

. An itemized statement of the charges to be paid by consignor in connection with the sale.

. The names and addresses of all purchasers if said commission merchant has any financial interest in the business of said purchasers, or if said purchasers have any financial interest in the business of said commission merchant, directly or indirectly, as holder of the other's corporate stock, as copartner, as lender or borrower of money to or from the other, or otherwise. Such interest shall be noted in said records following the name of any such purchaser.

. A lot number or other identifying mark for each consignment, which number or mark shall appear on all sales tags and other essential records needed to show what the agricultural products actually sold for.

. Any claim or claims which have been or may be filed by the commission merchant against any person for overcharges or for damages resulting from the injury or deterioration of such agricultural products by the act, neglect or failure of such person and such records shall be open to the inspection of the director and the consignor of agricultural products for whom such claim or claims are made.

Before a commission merchant may handle an agricultural product in a pooling arrangement or accounting, the consignor must have agreed in writing to allow the pooling.

Where a pooling arrangement is agreed to in writing between the consignor and commission merchant, the reporting requirements of subsections (4), (5), (6), and (8) of this section shall apply to the pool rather than to the individual consignor or consignment and the records of the pool shall be available for inspection by any consignor to that pool.

For individual accounting, the commission merchant shall transmit a copy of the record required by this section to the consignor on the same day the final remittance is made to the consignor as required by RCW 20.01.430. For a consignor who is participating in a pooling arrangement, the commission merchant shall, on the same day final remittance and accounting are made to the consignor as required by RCW 20.01.430, transmit to the consignor a summary of the records which are available for inspection by any consignor to that pool.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5713-S.SL.pdf?cite=1991%20c%20109%20§%2020[1991 c 109 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c354.pdf?cite=1989%20c%20354%20§%2041[1989 c 354 § 41]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c254.pdf?cite=1988%20c%20254%20§%2018[1988 c 254 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c115.pdf?cite=1979%20ex.s.%20c%20115%20§%205[1979 ex.s. c 115 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c304.pdf?cite=1977%20ex.s.%20c%20304%20§%209[1977 ex.s. c 304 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c102.pdf?cite=1974%20ex.s.%20c%20102%20§%206[1974 ex.s. c 102 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c232.pdf?cite=1963%20c%20232%20§%203[1963 c 232 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2037[1959 c 139 § 37]; ]

== 20.01.380 - Dealers, cash buyers, livestock dealers—Recordkeeping—Carrying identification and health documents.
Every dealer or cash buyer purchasing any agricultural products from the consignor thereof shall promptly make and keep for three years a correct record showing in detail the following:

. The name and address of the consignor.

. The date received.

. The terms of the sale.

. The quality and quantity delivered by the consignor, and where applicable the dockage, tare, grade, size, net weight, or quantity.

. An itemized statement of any charges paid by the dealer or cash buyer for the account of the consignor.

. The name and address of the purchaser: PROVIDED, That the name and address of the purchaser may be deleted from the record furnished to the consignor.

A copy of such record containing the above matters shall be forwarded to the consignor forthwith.

Livestock dealers must also maintain individual animal identification and disposition records as may be required by law, or rule adopted by the director.

Livestock dealers must carry animal identification and animal health documents as required by chapters 16.36 and 16.57 RCW and rules adopted by the director under those chapters.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5204.SL.pdf?cite=2007%20c%2071%20§%207[2007 c 71 § 7]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5713-S.SL.pdf?cite=1991%20c%20109%20§%2021[1991 c 109 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c354.pdf?cite=1989%20c%20354%20§%2042[1989 c 354 § 42]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c254.pdf?cite=1988%20c%20254%20§%2017[1988 c 254 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c296.pdf?cite=1981%20c%20296%20§%2033[1981 c 296 § 33]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c232.pdf?cite=1963%20c%20232%20§%204[1963 c 232 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2038[1959 c 139 § 38]; ]

== 20.01.385 - Failure to comply—Construction of transaction.
Whenever a commission merchant or dealer handling any agricultural products fails to carry out the provisions of RCW 20.01.370 as now or hereafter amended or RCW 20.01.380, whichever is applicable, it shall be prima facie evidence that the transaction involving the handling of any agricultural products between the consignor and the commission merchant or dealer was either a commission type transaction, or dealer transaction constituting an outright sale by the consignor, whichever is most favorable to the consignor. Such determination in favor of the consignor shall be based on the market price of the agricultural product in question at the time the complaint is filed against said commission merchant or dealer by the consignor: PROVIDED, That if the return to the consignor is determined most favorably on a commission basis, the total commission shall not exceed ten percent, and all other charges for handling the agricultural product in question shall be figured on the basis of the actual cost of said handling.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c304.pdf?cite=1977%20ex.s.%20c%20304%20§%2010[1977 ex.s. c 304 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c102.pdf?cite=1974%20ex.s.%20c%20102%20§%207[1974 ex.s. c 102 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c240.pdf?cite=1967%20c%20240%20§%2042[1967 c 240 § 42]; ]

== 20.01.390 - When dealer must pay for products delivered to him or her.
. Every dealer must pay for agricultural products, except livestock, delivered to him or her at the time and in the manner specified in the contract with the producer, but if no time is set by such contract, or at the time of said delivery, then within thirty days from the delivery or taking possession of such agricultural products.

. Every dealer must pay for livestock delivered to him or her at the time and in the manner specified in the contract, but if no time is set by such contract, or at the time of said delivery, then within seven days from the delivery or taking possession of such livestock. Where payment for livestock is made by mail, payment is timely if mailed within seven days of the date of sale.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20587[2011 c 336 § 587]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c20.pdf?cite=1982%20c%2020%20§%202[1982 c 20 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2039[1959 c 139 § 39]; ]

== 20.01.400 - Broker's memorandum of sale.
Every broker, upon negotiating the sale of agricultural products, shall issue to both buyer and seller a written memorandum of sale, showing price, date of delivery, quality, and other details concerned in the transaction. A copy of this memorandum shall be retained by the broker for a period of one year.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2040[1959 c 139 § 40]; ]

== 20.01.410 - Manifest of cargo—Bill of lading.
. A copy of a manifest of cargo, on a form prescribed by the director, shall be carried on any vehicle transporting agricultural products purchased by a dealer or cash buyer, or consigned to a commission merchant from the consignor thereof when prescribed by the director. A bill of lading may be carried in lieu of a manifest of cargo for an agricultural product other than hay or straw.

. Except as provided in subsection (3) of this section, the commission merchant, dealer, or cash buyer of agricultural products shall issue a copy of the manifest or bill of lading to the consignor of the agricultural products and the original shall be retained by the licensee for a period of three years during which time it shall be surrendered upon request to the director. The manifest of cargo is valid only when signed by the licensee or his or her agent and the consignor or his or her authorized representative of the agricultural products.

. The commission merchant or dealer of hay or straw shall issue a copy of a manifest to the consignor. The original copy shall be retained by the commission merchant or dealer for a period of three years during which time it shall be surrendered upon request to the director. The manifest of cargo is valid only when signed by the licensee or his or her agent and the consignor or his or her authorized representative of hay or straw.

. Manifest forms will be provided to licensees at the actual cost for the manifests plus necessary handling costs incurred by the department.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1100-S.SL.pdf?cite=2003%20c%20395%20§%207[2003 c 395 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c182.pdf?cite=1971%20ex.s.%20c%20182%20§%2012[1971 ex.s. c 182 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2041[1959 c 139 § 41]; ]

== 20.01.420 - Commission merchant's report of sale to consignor.
When requested by a consignor, a commission merchant shall promptly make available to the consignor or to the director all records of the ongoing sales of the consignor's agricultural products showing the amount sold, the selling price, and any other information required under RCW 20.01.370.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5713-S.SL.pdf?cite=1991%20c%20109%20§%2022[1991 c 109 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2042[1959 c 139 § 42]; ]

== 20.01.430 - Commission merchant's remittance to consignor.
Every commission merchant shall remit to the consignor of any agricultural product the full price for which such agricultural product was sold within thirty days of the date of sale, or in the case of livestock within seven days of the date of sale unless otherwise mutually agreed between grower and commission merchant. The remittance to the consignor shall include all collections, overcharges, and damages, less the agreed commission and other charges and advances, and a complete account of the sale. Where payment for livestock is made by mail, payment is timely if mailed within seven days of the date of sale unless otherwise specified in an agreement between the producer and the dealer in livestock.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c20.pdf?cite=1982%20c%2020%20§%203[1982 c 20 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c304.pdf?cite=1977%20ex.s.%20c%20304%20§%2011[1977 ex.s. c 304 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c102.pdf?cite=1974%20ex.s.%20c%20102%20§%209[1974 ex.s. c 102 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2043[1959 c 139 § 43]; ]

== 20.01.440 - Commission merchant's copy of records to be retained—Inspection—Department's certificate of condition, quality, etc.
Every commission merchant shall retain a copy of all records covering each transaction for a period of three years from the date thereof, which copy shall at all times be available for, and open to, the confidential inspection of the director and the consignor, or authorized representative of either. In the event of any dispute or disagreement between a consignor and a commission merchant arising at the time of delivery as to condition, quality, grade, pack, quantity, or weight of any lot, shipment, or consignment of agricultural products, the department shall furnish, upon the payment of a reasonable fee therefor by the requesting party, a certificate establishing the condition, quality, grade, pack, quantity, or weight of such lot, shipment, or consignment. Such certificate shall be prima facie evidence in all courts of this state as to the recitals thereof. The burden of proof shall be upon the commission merchant to prove the correctness of his or her accounting as to any transaction which may be questioned.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20588[2011 c 336 § 588]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5713-S.SL.pdf?cite=1991%20c%20109%20§%2023[1991 c 109 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2044[1959 c 139 § 44]; ]

== 20.01.450 - Claims against seller by dealer, cash buyer—Credit to dealer, cash buyer against consignor—Certificate of proof.
No claim may be made as against the seller of agricultural products by a dealer or cash buyer under this chapter, and no credit may be allowed to such dealer or cash buyer as against a consignor of agricultural products by reason of damage to, or loss, dumping, or disposal of agricultural products sold to said dealer or cash buyer, in any payment, accounting or settlement made by said dealer or cash buyer to said consignor, unless said dealer or cash buyer has secured and is in possession of a certificate, issued by an agricultural inspector, county health officer, director, a duly authorized officer of the state department of social and health services, or by some other official now or hereafter authorized by law, to the effect that the agricultural products involved have been damaged, dumped, destroyed or otherwise disposed of as unfit for the purpose intended. Such certificate will not be valid as proof of proper claim, credit or offset unless issued within twenty-four hours, or a reasonable time as prescribed by the director, of the receipt by the dealer or cash buyer of the agricultural products involved.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%2033[1979 c 141 § 33]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2045[1959 c 139 § 45]; ]

== 20.01.460 - Prohibited acts—Penalties.
. Any person who violates the provisions of this chapter or fails to comply with the rules adopted under this chapter is guilty of a gross misdemeanor, except as provided in subsections (2) through (4) of this section.

. Any commission merchant, dealer, or cash buyer, or any person assuming or attempting to act as a commission merchant, dealer, or cash buyer without a license is guilty of a class C felony who:

.. Imposes false charges for handling or services in connection with agricultural products.

.. Makes fictitious sales or is guilty of collusion to defraud the consignor.

.. Intentionally makes false statement or statements as to the grade, conditions, markings, quality, or quantity of goods shipped or packed in any manner.

.. With the intent to defraud the consignor, fails to comply with the requirements set forth under RCW * 20.01.010(10), 20.01.390, or 20.01.430.

. Any person who violates the provisions of RCW 20.01.040, 20.01.080, 20.01.120, 20.01.125, 20.01.410, or 20.01.610 has committed a civil infraction.

. Unlawful issuance of a check or draft may be prosecuted under RCW 9A.56.060.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1100-S.SL.pdf?cite=2003%20c%20395%20§%208[2003 c 395 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c354.pdf?cite=1989%20c%20354%20§%2043[1989 c 354 § 43]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c254.pdf?cite=1988%20c%20254%20§%2019[1988 c 254 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c178.pdf?cite=1986%20c%20178%20§%2013[1986 c 178 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c20.pdf?cite=1982%20c%2020%20§%204[1982 c 20 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2046[1959 c 139 § 46]; ]

== 20.01.465 - Time of sale requirement—Unlawful practice.
. In the preparation and use of written contracts, it is unlawful for a commission merchant to include in such contracts a requirement that a consignor give up all involvement in determining the time the consignor's agricultural products will be sold.

. Subsection (1) of this section does not apply to agricultural products consigned to a commission merchant under a written pooling agreement.

. Subsection (1) of this section does not apply to seeds consigned to a commission merchant.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6339.SL.pdf?cite=2004%20c%20212%20§%203[2004 c 212 § 3]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5713-S.SL.pdf?cite=1991%20c%20109%20§%2024[1991 c 109 § 24]; ]

== 20.01.470 - Action to enjoin violation of chapter.
The director may bring an action to enjoin the violation or the threatened violation of any provision of this chapter or of any order made pursuant to this chapter in the superior court in the county in which such violation occurs or is about to occur.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2047[1959 c 139 § 47]; ]

== 20.01.475 - Licensee under chapter—Prima facie evidence acting as licensee handling agricultural products.
It shall be prima facie evidence that a licensee licensed under the provisions of this chapter is acting as such in the handling of any agricultural product.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5374-S.SL.pdf?cite=2011%20c%20103%20§%2040[2011 c 103 § 40]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c182.pdf?cite=1971%20ex.s.%20c%20182%20§%2013[1971 ex.s. c 182 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c240.pdf?cite=1967%20c%20240%20§%2043[1967 c 240 § 43]; ]

== 20.01.480 - Violations resulting in improper or nonpayment—Charges.
When a violation has occurred which results in improper payment or nonpayment and a claim is made to the department and the payment is secured through the actions of the department, the charges made to the consignor for the action of the department in the matter will depend upon the delay of reporting after such improper payment or nonpayment would normally become obvious to the consignor as follows:

. When reported within thirty days, no charge.

. When reported thirty days to one hundred eighty days, five percent.

. When reported after one hundred eighty days, ten percent.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c304.pdf?cite=1977%20ex.s.%20c%20304%20§%2013[1977 ex.s. c 304 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c182.pdf?cite=1971%20ex.s.%20c%20182%20§%2014[1971 ex.s. c 182 § 14]; ]

== 20.01.482 - Civil infractions—Notice—Misdemeanors.
. The director shall have the authority to issue a notice of civil infraction if an infraction is committed in his or her presence or, if after investigation, the director has reasonable cause to believe an infraction has been committed.

. It is a misdemeanor for any person to refuse to properly identify himself or herself for the purpose of issuance of a notice of infraction.

. Any person willfully failing to respond to a notice of infraction is guilty of a misdemeanor regardless of the disposition of the notice of infraction.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1650-S.SL.pdf?cite=2006%20c%20270%20§%2010[2006 c 270 § 10]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2583.SL.pdf?cite=2004%20c%2043%20§%203[2004 c 43 § 3]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20161[2003 c 53 § 161]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c178.pdf?cite=1986%20c%20178%20§%201[1986 c 178 § 1]; ]

== 20.01.484 - Civil infractions—Response to notice.
. Any person who receives a notice of infraction shall respond to such notice as provided in this section within fifteen days of the date of the notice.

. Any employee or agent of a licensee under this chapter is fully authorized to accept a notice of infraction on behalf of the licensee. The director shall also furnish a copy of the notice of infraction to the licensee by certified mail within five days of issuance.

. If the person determined to have committed the infraction does not contest the determination, that person shall respond by completing the appropriate portion of the notice of infraction and submitting it, either by mail or in person, to the court specified on the notice. A check or money order in the amount of the penalty prescribed for the infraction must be submitted with the response. When a response, which does not contest the determination, is received, an appropriate order shall be entered into the courts record and a record of the response shall be furnished to the director.

. If a person determined to have committed the infraction wishes to contest the determination, that person shall respond by completing the portion of the notice of the infraction requesting a hearing and submitted either by mail or in person to the court specified in the notice. The court shall notify the person in writing of the time, place, and the date of the hearing which shall not be sooner than fifteen days from the date of the notice, except by agreement.

. If the person determined to have committed the infraction does not contest the determination, but wishes to explain mitigating circumstances surrounding the infraction, the person shall respond by completing the portion of the notice of infraction requesting a hearing for that purpose and submitting it either by mail or in person to the court specified in the notice. The court shall notify the person in writing of the time, place and date of the hearing.

. If a person issued a notice of infraction fails to respond to the notice of infraction or fails to appear at the hearing requested pursuant to this section, the court shall enter an appropriate order in assessing the monetary penalty prescribed in the schedule of penalties submitted to the court by the director and shall notify the director of the failure to respond to the notice of infraction or to appear at a requested hearing.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c178.pdf?cite=1986%20c%20178%20§%202[1986 c 178 § 2]; ]

== 20.01.486 - Civil infractions—Hearing to contest charge—Order—Appeal.
A hearing held for the purpose of contesting the determination that an infraction has been committed shall be held without jury. The court may consider the notice of infraction and any other written report submitted by the director. The person named in the notice may subpoena witnesses and has the right to present evidence and examine witnesses present in court. The burden of proof is upon the state to establish the commission of the infraction by preponderance of evidence.

After consideration of the evidence and argument, the court shall determine whether the infraction was committed. Where it is not established that the infraction was committed, an order dismissing the notice shall be entered in the court's record. When it is established that the infraction was committed, an appropriate order shall be entered in the court's record, a copy of which shall be furnished to the director. Appeal from the court's determination or order shall be to the superior court and must be appealed within ten days. The decision of the superior court is subject only to discretionary review pursuant to Rule 2.3 of the rules of appellate procedure.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c178.pdf?cite=1986%20c%20178%20§%203[1986 c 178 § 3]; ]

== 20.01.488 - Civil infractions—Informal hearing on mitigating circumstances—Order—No appeal.
A hearing held for the purpose of allowing a person to explain mitigating circumstances surrounding the commission of an infraction shall be an informal proceeding. The person named in the notice may not subpoena witnesses. The determination that the infraction has been committed may not be contested at a hearing held for the purpose of explaining circumstances. After the court has heard the explanation of the circumstances surrounding the commission of the infraction, an appropriate order shall be entered in the court's record. A copy of the order shall be furnished to the director. There may be no appeal from the court's determination or order.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c178.pdf?cite=1986%20c%20178%20§%204[1986 c 178 § 4]; ]

== 20.01.490 - Civil infractions—Monetary penalty—Failure to pay, misdemeanor.
. Any person found to have committed a civil infraction under this chapter shall be assessed a monetary penalty. No monetary penalty so assessed may exceed five thousand dollars. The director shall adopt a schedule of monetary penalties for each violation of this chapter classified as a civil infraction and shall submit the schedule to the proper courts. Whenever a monetary penalty is imposed by the court, the penalty is immediately due and payable. The court may, at its discretion, grant an extension of time, not to exceed thirty days, in which the penalty must be paid.

. Failure to pay any monetary penalties imposed under this chapter is a misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1100-S.SL.pdf?cite=2003%20c%20395%20§%209[2003 c 395 § 9]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20162[2003 c 53 § 162]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c178.pdf?cite=1986%20c%20178%20§%205[1986 c 178 § 5]; ]

== 20.01.500 - "Grower," "processor" defined—Application of exemption contained in RCW  20.01.030(1).
Notwithstanding any other provision of law, for the purposes of RCW 20.01.510 through 20.01.550 the term "grower" and the term "processor" shall have the meanings ascribed thereto by this section:

. "Grower" means any person, firm, company, or other organization that is engaged in the production of agricultural crops which must be planted, cultivated, and harvested within a twelve-month period.

. [Empty]
.. "Processor" means any person, firm, company, or other organization that purchases agricultural crops from a grower and who cans, freezes, dries, dehydrates, cooks, presses, powders, or otherwise processes such crops in any manner whatsoever for eventual resale.

.. The exemption provided for in RCW 20.01.030(1) shall not apply to a cooperative or association as defined therein, which acts as a processor defined herein, and markets such agricultural crops on behalf of the grower or on its own behalf.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c304.pdf?cite=1977%20ex.s.%20c%20304%20§%2014[1977 ex.s. c 304 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c182.pdf?cite=1971%20ex.s.%20c%20182%20§%2015[1971 ex.s. c 182 § 15]; ]

== 20.01.510 - Processor's form showing maximum processing capacity.
In order to carry out the purposes of this chapter, the director may require a processor to annually complete a form prescribed by the director, which, when completed, will show the maximum processing capacity of each plant operated by the processor in the state of Washington. Such completed form shall be returned to the director by a date prescribed by him or her.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20589[2011 c 336 § 589]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5374-S.SL.pdf?cite=2011%20c%20103%20§%2041[2011 c 103 § 41]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c182.pdf?cite=1971%20ex.s.%20c%20182%20§%2016[1971 ex.s. c 182 § 16]; ]

== 20.01.520 - Processor to have grower contracts and commitments on file.
By a date or dates prescribed prior to planting time by the director, the director, in order to carry out the purposes of this chapter, may require a processor to have filed with the director:

. A copy of each contract the processor has entered into with a grower for the purchase of acres of crops and/or quantity of crops to be harvested during the present or next growing season; and

. A notice of each oral commitment the processor has given to growers for the purchase of acres of crops and/or quantity of crops to be harvested during the present or next growing season, and such notice shall disclose the amount of acres and/or quantity to which the processor has committed himself or herself.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5374-S.SL.pdf?cite=2011%20c%20103%20§%2042[2011 c 103 § 42]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c182.pdf?cite=1971%20ex.s.%20c%20182%20§%2017[1971 ex.s. c 182 § 17]; ]

== 20.01.530 - Grower may file form showing crops processor is committed to purchase.
Any grower may file with the director on a form prescribed by him or her the acres of crops and/or quantity of crops to be harvested during the present or next growing season, which he or she understands a processor has orally committed himself or herself to purchase.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20591[2011 c 336 § 591]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c182.pdf?cite=1971%20ex.s.%20c%20182%20§%2018[1971 ex.s. c 182 § 18]; ]

== 20.01.540 - Committing to purchase more crops than plants can process—Violation.
Any processor who, from the information filed with the director, appears to or has committed himself or herself either orally or in writing to purchase more crops than his or her plants are capable of processing shall be in violation of this chapter and his or her dealer's license subject to denial, suspension, or revocation as provided for in RCW 20.01.330.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20592[2011 c 336 § 592]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c182.pdf?cite=1971%20ex.s.%20c%20182%20§%2019[1971 ex.s. c 182 § 19]; ]

== 20.01.550 - Discrimination by processor.
Any processor who discriminates between growers with whom he or she contracts as to price, conditions for production, harvesting, and delivery of crops which is not supportable by economic cost factors shall be in violation of this chapter and the director may subsequent to a hearing deny, suspend, or revoke such processor's license to act as a dealer.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20593[2011 c 336 § 593]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c304.pdf?cite=1977%20ex.s.%20c%20304%20§%2015[1977 ex.s. c 304 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c182.pdf?cite=1971%20ex.s.%20c%20182%20§%2020[1971 ex.s. c 182 § 20]; ]

== 20.01.560 - Effective date of RCW  20.01.500 through  20.01.550.
RCW 20.01.500 through 20.01.550 shall take effect beginning on September 1, 1972.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c182.pdf?cite=1971%20ex.s.%20c%20182%20§%2021[1971 ex.s. c 182 § 21]; ]

== 20.01.570 - Cash or other security in lieu of surety bond.
In lieu of the surety bond required under the provisions of this chapter, an applicant or licensee may file with the director a deposit consisting of cash or other security acceptable to the director. The director may adopt rules and regulations necessary for the administration of such security.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c142.pdf?cite=1973%20c%20142%20§%202[1973 c 142 § 2]; ]

== 20.01.610 - Authority to stop vehicle violating chapter—Failure to stop, civil infraction.
The director may establish points of inspection for vehicles transporting agricultural products on the public roads of this state. Vehicles transporting agricultural products on the public roads of this state are subject to inspection and must stop at any posted inspection point established by the director. The director or appointed officers may stop a vehicle transporting agricultural products upon the public roads of this state at a place other than an inspection point if there is reasonable cause to believe the carrier, seller, or buyer may be in violation of this chapter. Any operator of a vehicle failing or refusing to stop when directed to do so has committed a civil infraction.

The director and appointed officers shall work to ensure that vehicles carrying perishable agricultural products are detained no longer than is absolutely necessary for a prompt assessment of compliance with this chapter. If a vehicle carrying perishable agricultural products is found to be in violation of this chapter, the director or appointed officers shall promptly issue necessary notices of civil infraction, as provided in RCW 20.01.482 and 20.01.484, and shall allow the vehicle to continue toward its destination without further delay.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5204.SL.pdf?cite=2007%20c%2071%20§%206[2007 c 71 § 6]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1100-S.SL.pdf?cite=2003%20c%20395%20§%2010[2003 c 395 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c178.pdf?cite=1986%20c%20178%20§%2014[1986 c 178 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c305.pdf?cite=1983%20c%20305%20§%208[1983 c 305 § 8]; ]

== 20.01.900 - Chapter cumulative and nonexclusive.
The provisions of this chapter shall be cumulative and nonexclusive and shall not affect any other remedy.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2048[1959 c 139 § 48]; ]

== 20.01.920 - Effective date—1959 c 139.
The effective date of this chapter shall be January 1, 1960.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2050[1959 c 139 § 50]; ]

== 20.01.930 - Repealer.
Chapter 14, Laws of 1955 as amended by section 4, chapter 262, Laws of 1955, section 3, chapter 262, Laws of 1955, sections 1 and 2, chapter 262, Laws of 1955 and RCW 20.04.010 through 20.04.120, 20.08.010 through 20.08.110, 20.12.020 through 20.12.040, 20.16.010 through 20.16.040, 20.20.010 through 20.20.060, 20.24.010 through 20.24.070 and 20.98.010 through 20.98.060 are hereby repealed.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c139.pdf?cite=1959%20c%20139%20§%2051[1959 c 139 § 51]; ]

== 20.01.940 - Repealer—Savings—1979 ex.s. c 115.
Section 10, chapter 102, Laws of 1974 ex. sess., section 12, chapter 304, Laws of 1977 ex. sess. and RCW 20.01.445 are each repealed.

Such repeals shall not be construed as affecting any existing right acquired under the statutes repealed, nor as affecting any proceeding instituted thereunder, nor any rule, regulation, or order promulgated thereunder, nor any administrative action taken thereunder.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c115.pdf?cite=1979%20ex.s.%20c%20115%20§%206[1979 ex.s. c 115 § 6]; ]

