= 39.10 - Alternative public works contracting procedures.
:toc:

== 39.10.200 - Finding—Purpose—Intent.
The legislature finds that the traditional process of awarding public works contracts in lump sum to the lowest responsible bidder is a fair and objective method of selecting a contractor. However, under certain circumstances, alternative public works contracting procedures may best serve the public interest if such procedures are implemented in an open and fair process based on objective and equitable criteria. The purpose of this chapter is to authorize the use of certain supplemental alternative public works contracting procedures, to prescribe appropriate requirements to ensure that such contracting procedures serve the public interest, and to establish a process for evaluation of such contracting procedures. It is the intent of the legislature to establish that, unless otherwise specifically provided for in law, public bodies may use only those alternative public works contracting procedures specifically authorized in this chapter, subject to the requirements of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1690.SL.pdf?cite=2010%201st%20sp.s.%20c%2021%20§%202[2010 1st sp.s. c 21 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1506-S2.SL.pdf?cite=2007%20c%20494%20§%201[2007 c 494 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2607-S.SL.pdf?cite=1994%20c%20132%20§%201[1994 c 132 § 1]; ]

== 39.10.210 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Alternative public works contracting procedure" means the design-build, general contractor/construction manager, and job order contracting procedures authorized in RCW 39.10.300, 39.10.340, and 39.10.420, respectively.

. "Board" means the capital projects advisory review board.

. "Certified public body" means a public body certified to use design-build or general contractor/construction manager contracting procedures, or both, under RCW 39.10.270.

. "Committee," unless otherwise noted, means the project review committee.

. "Design-build procedure" means a contract between a public body and another party in which the party agrees to both design and build the facility, portion of the facility, or other item specified in the contract.

. "Disadvantaged business enterprise" means any business entity certified with the office of minority and women's business enterprises under chapter 39.19 RCW.

. "General contractor/construction manager" means a firm with which a public body has selected to provide services during the design phase and negotiated a maximum allowable construction cost to act as construction manager and general contractor during the construction phase.

. "Heavy civil construction project" means a civil engineering project, the predominant features of which are infrastructure improvements.

. "Job order contract" means a contract in which the contractor agrees to a fixed period, indefinite quantity delivery order contract which provides for the use of negotiated, definitive work orders for public works as defined in RCW 39.04.010.

. "Job order contractor" means a registered or licensed contractor awarded a job order contract.

. "Maximum allowable construction cost" means the maximum cost of the work to construct the project including a percentage for risk contingency, negotiated support services, and approved change orders.

. "Negotiated support services" means items a general contractor would normally manage or perform on a construction project including, but not limited to surveying, hoisting, safety enforcement, provision of toilet facilities, temporary heat, cleanup, and trash removal, and that are negotiated as part of the maximum allowable construction cost.

. "Percent fee" means the percentage amount to be earned by the general contractor/construction manager as overhead and profit.

. "Price-related factor" means an evaluation factor that impacts costs which may include, but is not limited to overhead and profit, lump sum or guaranteed maximum price for the entire or a portion of the project, operating costs, or other similar factors that may apply to the project.

. "Public body" means any general or special purpose government in the state of Washington, including but not limited to state agencies, institutions of higher education, counties, cities, towns, ports, school districts, and special purpose districts.

. "Public works project" means any work for a public body within the definition of "public work" in RCW 39.04.010.

. "Small business entity" means a small business as defined in RCW 39.26.010.

. "Total contract cost" means the fixed amount for the detailed specified general conditions work, the negotiated maximum allowable construction cost, and the percent fee on the negotiated maximum allowable construction cost.

. "Total project cost" means the cost of the project less financing and land acquisition costs.

. "Unit price book" means a book containing specific prices, based on generally accepted industry standards and information, where available, for various items of work to be performed by the job order contractor. The prices may include: All the costs of materials; labor; equipment; overhead, including bonding costs; and profit for performing the items of work. The unit prices for labor must be at the rates in effect at the time the individual work order is issued.

. "Work order" means an order issued for a definite scope of work to be performed pursuant to a job order contract.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1295-S.SL.pdf?cite=2019%20c%20212%20§%201[2019 c 212 § 1]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2208.SL.pdf?cite=2014%20c%2042%20§%201[2014 c 42 § 1]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1466-S.SL.pdf?cite=2013%20c%20222%20§%201[2013 c 222 § 1]; prior:  2010 1st sp.s. c 36 § 6014; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1506-S2.SL.pdf?cite=2007%20c%20494%20§%20101[2007 c 494 § 101]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5285-S.SL.pdf?cite=2005%20c%20469%20§%203[2005 c 469 § 3]; prior:  2003 c 352 § 1; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1788-S.SL.pdf?cite=2003%20c%20301%20§%202[2003 c 301 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2056-S.SL.pdf?cite=2003%20c%20300%20§%203[2003 c 300 § 3]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5060-S.SL.pdf?cite=2001%20c%20328%20§%201[2001 c 328 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1070.SL.pdf?cite=2000%20c%20209%20§%201[2000 c 209 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1425-S.SL.pdf?cite=1997%20c%20376%20§%201[1997 c 376 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2607-S.SL.pdf?cite=1994%20c%20132%20§%202[1994 c 132 § 2]; ]

== 39.10.220 - Board—Membership—Vacancies.
. The board is created in the department of enterprise services to provide an evaluation of public capital projects construction processes, including the impact of contracting methods on project outcomes, and to advise the legislature on policies related to public works delivery methods.

. Members of the board are appointed as follows:

.. Two representatives from construction general contracting; one representative from the architectural profession; one representative from the engineering profession; two representatives from construction specialty subcontracting; two representatives from construction trades labor organizations; one representative from the office of minority and women's business enterprises; one representative from a higher education institution; one representative from the department of enterprise services; one individual representing Washington cities; two representatives from private industry; and one representative of a domestic insurer authorized to write surety bonds for contractors in Washington state, each appointed by the governor. All appointed members must be knowledgeable about public works contracting procedures. If a vacancy occurs, the governor shall fill the vacancy for the unexpired term;

.. One member representing counties, selected by the Washington state association of counties;

.. One member representing public ports, selected by the Washington public ports association;

.. One member representing public hospital districts, selected by the association of Washington public hospital districts;

.. One member representing school districts, selected by the Washington state school directors' association; and

.. Two members of the house of representatives, one from each major caucus, appointed by the speaker of the house of representatives, and two members of the senate, one from each major caucus, appointed by the president of the senate. Legislative members are nonvoting.

. Members selected under subsection (2)(a) of this section shall serve for terms of four years, with the terms expiring on June 30th on the fourth year of the term.

. The board chair is selected from among the appointed members by the majority vote of the voting members.

. Legislative members of the board shall be reimbursed for travel expenses in accordance with RCW 44.04.120. Nonlegislative members of the board, project review committee members, and committee chairs shall be reimbursed for travel expenses as provided in RCW 43.03.050 and 43.03.060.

. Vacancies are filled in the same manner as appointed. Members of the board may be removed for malfeasance or misfeasance in office, upon specific written charges by the governor, under chapter 34.05 RCW.

. The board shall meet as often as necessary.

. Board members are expected to consistently attend board meetings. The chair of the board may ask the governor to remove any member who misses more than two meetings in any calendar year without cause.

. The department of enterprise services shall provide staff support as may be required for the proper discharge of the function of the board.

. The board may establish committees as it desires and may invite nonmembers of the board to serve as committee members.

. The board shall encourage participation from persons and entities not represented on the board.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1466-S.SL.pdf?cite=2013%20c%20222%20§%202[2013 c 222 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1506-S2.SL.pdf?cite=2007%20c%20494%20§%20102[2007 c 494 § 102]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1830-S.SL.pdf?cite=2005%20c%20377%20§%201[2005 c 377 § 1]; ]

== 39.10.230 - Board—Powers and duties.
The board has the following powers and duties:

. Develop and recommend to the legislature policies to further enhance the quality, efficiency, and accountability of capital construction projects through the use of traditional and alternative delivery methods in Washington, and make recommendations regarding expansion, continuation, elimination, or modification of the alternative public works contracting methods;

. Evaluate the use of existing contracting procedures and the potential future use of other alternative contracting procedures including competitive negotiation contracts;

. Submit recommendations to the appropriate committees of the legislature evaluating alternative contracting procedures that are not authorized under this chapter;

. Appoint members of committees; and

. Develop and administer questionnaires designed to provide quantitative and qualitative data on alternative public works contracting procedures on which evaluations are based.

The capital projects advisory review board is directed to review current statutes regarding life-cycle cost analysis and energy efficiency as related to the design-build procurement method performed under chapter 39.10 RCW. Capital projects advisory review board shall report to the appropriate committees of the legislature by December 31, 2013, with recommendations for statutory changes that promote energy efficiency and reduce the total cost to construct, operate and maintain public buildings. Recommendation must include provisions for postoccupancy validation of estimated energy efficiency measures, and operating and maintenance cost estimates. Life-cycle estimates of energy use must include estimates of energy consumptions for materials used in construction.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1466-S.SL.pdf?cite=2013%20c%20222%20§%203[2013 c 222 § 3]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1690.SL.pdf?cite=2010%201st%20sp.s.%20c%2021%20§%203[2010 1st sp.s. c 21 § 3]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1197.SL.pdf?cite=2009%20c%2075%20§%201[2009 c 75 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1506-S2.SL.pdf?cite=2007%20c%20494%20§%20103[2007 c 494 § 103]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1830-S.SL.pdf?cite=2005%20c%20377%20§%202[2005 c 377 § 2]; ]

== 39.10.240 - Project review committee—Creation—Members.
. The board shall establish a project review committee to review and approve public works projects using the design-build and general contractor/construction manager contracting procedures authorized in RCW 39.10.300 and 39.10.340 and to certify public bodies as provided in RCW 39.10.270.

. The board shall, by a majority vote of the board, appoint persons to the committee who are knowledgeable in the use of the design-build and general contractor/construction manager contracting procedures. Appointments must represent a balance among the industries and public owners on the board listed in RCW 39.10.220.

.. Each member of the committee shall be appointed for a term of three years. However, for initial appointments, the board shall stagger the appointment of committee members so that the first members are appointed to serve terms of one, two, or three years from the date of appointment. Appointees may be reappointed to serve more than one term.

.. The committee shall, by a majority vote, elect a chair and vice chair for the committee.

.. The committee chair may select a person or persons on a temporary basis as a nonvoting member if project specific expertise is needed to assist in a review.

. The chair of the committee, in consultation with the vice chair, may appoint one or more panels of at least six committee members to carry out the duties of the committee. Each panel shall have balanced representation of the private and public sector representatives serving on the committee.

. Any member of the committee directly or indirectly affiliated with a submittal before the committee must recuse himself or herself from the committee consideration of that submittal.

. Any person who sits on the committee or panel is not precluded from subsequently bidding on or participating in projects that have been reviewed by the committee.

. The committee shall meet as often as necessary to ensure that certification and approvals are completed in a timely manner.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1466-S.SL.pdf?cite=2013%20c%20222%20§%204[2013 c 222 § 4]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1506-S2.SL.pdf?cite=2007%20c%20494%20§%20104[2007 c 494 § 104]; ]

== 39.10.250 - Project review committee—Duties.
The committee shall:

. Certify, or renew certification for, public bodies to use design-build or general contractor/construction manager contracting procedures, or both;

. Review and approve the use of the design-build or general contractor/construction manager contracting procedures on a project by project basis for public bodies that are not certified under RCW 39.10.270;

. Review and approve not more than two design-build demonstration projects that include procurement of operations and maintenance services for a period longer than three years.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1295-S.SL.pdf?cite=2019%20c%20212%20§%202[2019 c 212 § 2]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1466-S.SL.pdf?cite=2013%20c%20222%20§%205[2013 c 222 § 5]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1197.SL.pdf?cite=2009%20c%2075%20§%202[2009 c 75 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1506-S2.SL.pdf?cite=2007%20c%20494%20§%20105[2007 c 494 § 105]; ]

== 39.10.260 - Project review committee—Meetings—Open and public.
. The committee shall hold regular public meetings to carry out its duties as described in RCW 39.10.250. Committee meetings are subject to chapter 42.30 RCW.

. The committee shall publish notice of its public meetings at least twenty days before the meeting in a legal newspaper circulated in the area where the public body seeking certification is located, or where each of the proposed projects under consideration will be constructed. All meeting notices must be posted on the committee's web site.

. The meeting notice must identify the public body that is seeking certification or project approval, and where applicable, a description of projects to be considered at the meeting. The notice must indicate when, where, and how the public may present comments regarding the committee's certification of a public body or approval of a project. Information submitted by a public body to be reviewed at the meeting shall be available on the committee's web site at the time the notice is published.

. The committee must allow for public comment on the appropriateness of certification of a public body or on the appropriateness of the use of the proposed contracting procedure and the qualifications of a public body to use the contracting procedure. The committee shall receive and record both written and oral comments at the public meeting.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1466-S.SL.pdf?cite=2013%20c%20222%20§%206[2013 c 222 § 6]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1506-S2.SL.pdf?cite=2007%20c%20494%20§%20106[2007 c 494 § 106]; ]

== 39.10.270 - Project review committee—Certification of public bodies.
. A public body may apply for certification to use the design-build or general contractor/construction manager contracting procedure, or both. Once certified, a public body may use the contracting procedure for which it is certified on individual projects without seeking committee approval for a period of three years. A public body seeking certification must submit to the committee an application in a format and manner as prescribed by the committee. The application must include a description of the public body's qualifications, its capital plan during the certification period, and its intended use of alternative contracting procedures.

. A public body seeking certification for the design-build procedure must demonstrate successful management of at least one design-build project within the previous five years. A public body seeking certification for the general contractor/construction manager procedure must demonstrate successful management of at least one general contractor/construction manager project within the previous five years.

. To certify a public body, the committee shall determine that the public body:

.. Has the necessary experience and qualifications to determine which projects are appropriate for using alternative contracting procedures;

.. Has the necessary experience and qualifications to carry out the alternative contracting procedure including, but not limited to: (i) Project delivery knowledge and experience; (ii) personnel with appropriate construction experience; (iii) a management plan and rationale for its alternative public works projects; (iv) demonstrated success in managing public works projects; (v) the ability to properly manage its capital facilities plan including, but not limited to, appropriate project planning and budgeting experience; and (vi) the ability to meet requirements of this chapter; and

.. Has resolved any audit findings on previous public works projects in a manner satisfactory to the committee.

. The committee shall make its determination at the public meeting during which an application for certification is reviewed. Public comments must be considered before a determination is made. Within ten business days of the public meeting, the committee shall provide a written determination to the public body, and make its determination available to the public on the committee's web site.

. The committee may revoke any public body's certification upon a finding, after a public hearing, that its use of design-build or general contractor/construction manager contracting procedures no longer serves the public interest.

. The committee may renew the certification of a public body for additional three-year periods. The public body must submit an application for recertification at least three months before the initial certification expires. The committee may accept late applications, if administratively feasible, to avoid expiration of certification on a case-by-case basis. The application shall include updated information on the public body's experience and current staffing with the procedure it is applying to renew, and any other information requested in advance by the committee. The committee must review the application for recertification at a meeting held before expiration of the applicant's initial certification period. A public body must reapply for certification under the process described in subsection (1) of this section once the period of recertification expires.

. Certified public bodies must submit project data information as required in RCW 39.10.320 and 39.10.350.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1295-S.SL.pdf?cite=2019%20c%20212%20§%203[2019 c 212 § 3]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2052.SL.pdf?cite=2017%20c%20211%20§%201[2017 c 211 § 1]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1466-S.SL.pdf?cite=2013%20c%20222%20§%207[2013 c 222 § 7]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1197.SL.pdf?cite=2009%20c%2075%20§%203[2009 c 75 § 3]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1506-S2.SL.pdf?cite=2007%20c%20494%20§%20107[2007 c 494 § 107]; ]

== 39.10.280 - Project review committee—Project approval process.
. A public body not certified under RCW 39.10.270 must apply for approval from the committee to use the design-build or general contractor/construction manager contracting procedure on a project. A public body seeking approval must submit to the committee an application in a format and manner as prescribed by the committee. The application must include a description of the public body's qualifications, a description of the project, the public body's intended use of alternative contracting procedures, and, if applicable, a declaration that the public body has elected to procure the project as a heavy civil construction project.

. To approve a proposed project, the committee shall determine that:

.. The alternative contracting procedure will provide a substantial fiscal benefit or the use of the traditional method of awarding contracts in lump sum to the low responsive bidder is not practical for meeting desired quality standards or delivery schedules;

.. The proposed project meets the requirements for using the alternative contracting procedure as described in RCW 39.10.300 or 39.10.340;

.. The public body has the necessary experience or qualified team to carry out the alternative contracting procedure including, but not limited to: (i) Project delivery knowledge and experience; (ii) sufficient personnel with construction experience to administer the contract; (iii) a written management plan that shows clear and logical lines of authority; (iv) the necessary and appropriate funding and time to properly manage the job and complete the project; (v) continuity of project management team, including personnel with experience managing projects of similar scope and size to the project being proposed; and (vi) necessary and appropriate construction budget;

.. For design-build projects, public body personnel or consultants are knowledgeable in the design-build process and are able to oversee and administer the contract; and

.. The public body has resolved any audit findings related to previous public works projects in a manner satisfactory to the committee.

. The committee shall, if practicable, make its determination at the public meeting during which a submittal is reviewed. Public comments must be considered before a determination is made.

. Within ten business days after the public meeting, the committee shall provide a written determination to the public body, and make its determination available to the public on the committee's web site. If the committee fails to make a written determination within ten business days of the public meeting, the request of the public body to use the alternative contracting procedure on the requested project shall be deemed approved.

. Failure of the committee to meet within sixty calendar days of a public body's application to use an alternative contracting procedure on a project shall be deemed an approval of the application.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2208.SL.pdf?cite=2014%20c%2042%20§%202[2014 c 42 § 2]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1466-S.SL.pdf?cite=2013%20c%20222%20§%208[2013 c 222 § 8]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1506-S2.SL.pdf?cite=2007%20c%20494%20§%20108[2007 c 494 § 108]; ]

== 39.10.290 - Appeal process.
Final determinations by the committee may be appealed to the board within seven days by the public body or by an interested party. A written notice of an appeal must be provided to the committee and, as applicable, to the public body. The board shall resolve an appeal within forty-five days of receipt of the appeal and shall send a written determination of its decision to the party making the appeal and to the appropriate public body, as applicable. The public body shall comply with the determination of the board.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1506-S2.SL.pdf?cite=2007%20c%20494%20§%20109[2007 c 494 § 109]; ]

== 39.10.300 - Design-build procedure—Uses.
. Subject to the requirements in RCW 39.10.250, 39.10.270, or 39.10.280, public bodies may utilize the design-build procedure, including progressive design-build, for public works projects in which the total project cost is over two million dollars and where:

.. The construction activities are highly specialized and a design-build approach is critical in developing the construction methodology; or

.. The projects selected provide opportunity for greater innovation or efficiencies between the designer and the builder; or

.. Significant savings in project delivery time would be realized.

. Subject to the process in RCW 39.10.270 or 39.10.280, public bodies may use the design-build procedure for parking garages, regardless of cost.

. The design-build procedure may be used for the construction or erection of portable facilities as defined in WAC 392-343-018, preengineered metal buildings, or not more than ten prefabricated modular buildings per installation site, regardless of cost and is not subject to approval by the committee.

. Except for utility projects and approved demonstration projects, the design-build procedure may not be used to procure operations and maintenance services for a period longer than three years. State agency projects that propose to use the design-build-operate-maintain procedure shall submit cost estimates for the construction portion of the project consistent with the office of financial management's capital budget requirements. Operations and maintenance costs must be shown separately and must not be included as part of the capital budget request.

. Subject to the process in RCW 39.10.280, a public body may seek committee approval for a design-build demonstration project that includes procurement of operations and maintenance services for a period longer than three years.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1295-S.SL.pdf?cite=2019%20c%20212%20§%204[2019 c 212 § 4]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1466-S.SL.pdf?cite=2013%20c%20222%20§%209[2013 c 222 § 9]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1197.SL.pdf?cite=2009%20c%2075%20§%204[2009 c 75 § 4]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1506-S2.SL.pdf?cite=2007%20c%20494%20§%20201[2007 c 494 § 201]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5520-S.SL.pdf?cite=2003%20c%20352%20§%202[2003 c 352 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2056-S.SL.pdf?cite=2003%20c%20300%20§%204[2003 c 300 § 4]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6597-S.SL.pdf?cite=2002%20c%2046%20§%201[2002 c 46 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5060-S.SL.pdf?cite=2001%20c%20328%20§%202[2001 c 328 § 2]; ]

== 39.10.320 - Design-build procedure—Project management and contracting requirements.
. A public body utilizing the design-build contracting procedure shall provide:

.. Reasonable budget contingencies totaling not less than five percent of the anticipated contract value;

.. Staff or consultants with expertise and prior experience in the management of comparable projects;

.. Contract documents that include alternative dispute resolution procedures to be attempted prior to the initiation of litigation;

.. Submission of project information, as required by the board;

.. Contract documents that require the contractor, subcontractors, and designers to submit project information required by the board; and

.. Contract documents that require the design builder to submit plans for inclusion of underutilized firms as subcontractors and suppliers including, but not limited to, the office of minority and women's business enterprises certified businesses, veteran certified businesses, and small businesses as allowed by law.

. A public body utilizing the design-build contracting procedure may provide incentive payments to contractors for early completion, cost savings, or other goals if such payments are identified in the request for proposals.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1295-S.SL.pdf?cite=2019%20c%20212%20§%205[2019 c 212 § 5]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1466-S.SL.pdf?cite=2013%20c%20222%20§%2010[2013 c 222 § 10]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1506-S2.SL.pdf?cite=2007%20c%20494%20§%20203[2007 c 494 § 203]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2607-S.SL.pdf?cite=1994%20c%20132%20§%207[1994 c 132 § 7]; ]

== 39.10.330 - Design-build contract award process.
. Contracts for design-build services shall be awarded through a competitive process using public solicitation of proposals for design-build services. The public body shall publish at least once in a legal newspaper of general circulation published in, or as near as possible to, that part of the county in which the public work will be done, a notice of its request for qualifications from proposers for design-build services, and the availability and location of the request for proposal documents. The request for qualifications documents shall include:

.. A description of the project including the estimated design-build contract value and the intended use of the project;

.. The reasons for using the design-build procedure;

.. A description of the qualifications to be required of the proposer;

.. A description of the process the public body will use to evaluate qualifications and finalists' proposals, including evaluation factors and the relative weight of factors and any specific forms to be used by the proposers;

... Evaluation factors for qualifications shall include technical qualifications, such as specialized experience and technical competence of the firms and the key design and construction personnel; capacity to perform; the proposer's past performance in utilization of the office of minority and women's business enterprises certified businesses, to the extent permitted by law; ability to provide a performance and payment bond for the project; and other appropriate factors. Evaluation factors may also include, but are not limited to, the proposer's past performance in utilization of small business entities. Cost or price-related factors are not permitted in the request for qualifications phase;

... Evaluation factors for finalists' proposals shall include the management plan to meet time and budget requirements and one or more price-related factors. Evaluation factors may also include, but not be limited to, the technical approach, design concept, and the outreach plan to include small business entities and disadvantaged business enterprises as subconsultants, subcontractors, and suppliers for the project;

.. Protest procedures including time limits for filing a protest, which in no event may limit the time to file a protest to fewer than four business days from the date the proposer was notified of the selection decision;

.. The proposed contract;

.. The honorarium to be paid to finalists submitting responsive proposals and who are not awarded a design-build contract;

.. The schedule for the procurement process and the project; and

.. Other information relevant to the project.

. The public body shall establish an evaluation committee to evaluate the responses to the request for qualifications based solely on the factors, weighting, and process identified in the request for qualifications and any addenda issued by the public body. Based on the evaluation committee's findings, the public body shall select not more than five responsive and responsible finalists to submit proposals. The public body may, in its sole discretion, reject all proposals and shall provide its reasons for rejection in writing to all proposers.

. The public body must notify all proposers of the finalists selected to move to the next phase of the selection process. The process may not proceed to the next phase until two business days after all proposers are notified of the committee's selection decision. At the request of a proposer not selected as a finalist, the public body must provide the requesting proposer with a scoring summary of the evaluation factors for its proposal. Proposers filing a protest on the selection of the finalists must file the protest in accordance with the published protest procedures. The selection process may not advance to the next phase of selection until two business days after the final protest decision is transmitted to the protestor.

. Upon selection of the finalists, the public body shall issue a request for proposals to the finalists. The request for proposal documents shall include:

.. Any specific forms to be used by the finalists; and

.. Submission of a summary of the finalist's accident prevention program and an overview of its implementation.

. The public body shall establish an evaluation committee to evaluate the proposals submitted by the finalists. The finalists' proposals shall be evaluated and scored based solely on the factors, weighting, and process identified in the request for qualifications, the request for proposals, and in any addenda published by the public body. Public bodies may request best and final proposals from finalists. The public body may initiate negotiations with the finalist submitting the highest scored proposal. If the public body is unable to execute a contract with the finalist submitting the highest scored proposal, negotiations with that finalist may be suspended or terminated and the public body may proceed to negotiate with the next highest scored finalist. Public bodies shall continue in accordance with this procedure until a contract agreement is reached or the selection process is terminated.

. The public body shall notify all finalists of the selection decision and make a selection summary of the final proposals available to all proposers within two business days of such notification. If the public body receives a timely written protest from a finalist firm, the public body may not execute a contract until two business days after the final protest decision is transmitted to the protestor. The protestor must submit its protest in accordance with the published protest procedures.

. The firm awarded the contract shall provide a performance and payment bond for the contracted amount.

. Any contract must require the firm awarded the contract to track and report to the public body its utilization of the office of minority and women's business enterprises certified businesses and veteran certified businesses.

. The public body shall provide appropriate honorarium payments to finalists submitting responsive proposals that are not awarded a design-build contract. Honorarium payments shall be sufficient to generate meaningful competition among potential proposers on design-build projects. In determining the amount of the honorarium, the public body shall recognize the level of effort required to meet the selection criteria.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1295-S.SL.pdf?cite=2019%20c%20212%20§%206[2019 c 212 § 6]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2555.SL.pdf?cite=2014%20c%2019%20§%201[2014 c 19 § 1]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1466-S.SL.pdf?cite=2013%20c%20222%20§%2011[2013 c 222 § 11]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1197.SL.pdf?cite=2009%20c%2075%20§%205[2009 c 75 § 5]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1506-S2.SL.pdf?cite=2007%20c%20494%20§%20204[2007 c 494 § 204]; ]

== 39.10.340 - General contractor/construction manager procedure—Uses.
Subject to the process in RCW 39.10.270 or 39.10.280, public bodies may utilize the general contractor/construction manager procedure for public works projects where at least one of the following is met:

. Implementation of the project involves complex scheduling, phasing, or coordination;

. The project involves construction at an occupied facility which must continue to operate during construction;

. The involvement of the general contractor/construction manager during the design stage is critical to the success of the project;

. The project encompasses a complex or technical work environment;

. The project requires specialized work on a building that has historic significance; or

. The project is, and the public body elects to procure the project as, a heavy civil construction project. However, no provision of this chapter pertaining to a heavy civil construction project applies unless the public body expressly elects to procure the project as a heavy civil construction project.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2208.SL.pdf?cite=2014%20c%2042%20§%203[2014 c 42 § 3]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1466-S.SL.pdf?cite=2013%20c%20222%20§%2012[2013 c 222 § 12]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1506-S2.SL.pdf?cite=2007%20c%20494%20§%20301[2007 c 494 § 301]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5520-S.SL.pdf?cite=2003%20c%20352%20§%203[2003 c 352 § 3]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2056-S.SL.pdf?cite=2003%20c%20300%20§%205[2003 c 300 § 5]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6597-S.SL.pdf?cite=2002%20c%2046%20§%202[2002 c 46 § 2]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5060-S.SL.pdf?cite=2001%20c%20328%20§%203[2001 c 328 § 3]; ]

== 39.10.350 - General contractor/construction manager procedure—Project management and contracting requirements.
. A public body using the general contractor/construction manager contracting procedure shall provide for:

.. The preparation of appropriate, complete, and coordinated design documents;

.. Confirmation that a constructability analysis of the design documents has been performed prior to solicitation of a subcontract bid package;

.. Reasonable budget contingencies totaling not less than five percent of the anticipated contract value;

.. To the extent appropriate, on-site architectural or engineering representatives during major construction or installation phases;

.. Employment of staff or consultants with expertise and prior experience in the management of comparable projects, critical path method schedule review and analysis, and the administration, pricing, and negotiation of change orders;

.. Contract documents that include alternative dispute resolution procedures to be attempted before the initiation of litigation;

.. Contract documents that: (i) Obligate the public owner to accept or reject a request for equitable adjustment, change order, or claim within a specified time period but no later than sixty calendar days after the receipt by the public body of related documentation; and (ii) provide that if the public owner does not respond in writing to a request for equitable adjustment, change order, or claim within the specified time period, the request is deemed denied;

.. Submission of project information, as required by the board; and

.. Contract documents that require the contractor, subcontractors, and designers to submit project information required by the board.

. A public body using the general contractor/construction manager contracting procedure may include an incentive clause for early completion, cost savings, or other performance goals if such incentives are identified in the request for proposals. No incentives granted may exceed five percent of the maximum allowable construction cost. No incentives may be paid from any contingency fund established for coordination of the construction documents or coordination of the work.

. If the construction is completed for less than the maximum allowable construction cost, any savings not otherwise negotiated as part of an incentive clause shall accrue to the public body. If the construction is completed for more than the maximum allowable construction cost, the additional cost is the responsibility of the general contractor/construction manager.

. If the public body and the general contractor/construction manager agree, in writing, on a price for additional work, the public body must issue a change order within thirty days of the written agreement. If the public body does not issue a change order within the thirty days, interest shall accrue on the dollar amount of the additional work satisfactorily completed until a change order is issued. The public body shall pay this interest at a rate of one percent per month.

. For a project procured as a heavy civil construction project, an independent audit, paid for by the public body, must be conducted to confirm the proper accrual of costs as outlined in the contract.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2208.SL.pdf?cite=2014%20c%2042%20§%204[2014 c 42 § 4]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1506-S2.SL.pdf?cite=2007%20c%20494%20§%20302[2007 c 494 § 302]; ]

== 39.10.360 - General contractor/construction manager procedure—Contract award process.
. Public bodies should select general contractor/construction managers early in the life of public works projects, and in most situations no later than the completion of schematic design.

. Contracts for the services of a general contractor/construction manager under this section shall be awarded through a competitive process requiring the public solicitation of proposals for general contractor/construction manager services. The public solicitation of proposals shall include:

.. A description of the project, including programmatic, performance, and technical requirements and specifications when available;

.. The reasons for using the general contractor/construction manager procedure including, if applicable, a clear statement that the public body is electing to procure the project as a heavy civil construction project, in which case the solicitation must additionally:

... Indicate the minimum percentage of the cost of the work to construct the project that will constitute the negotiated self-perform portion of the project;

... Indicate whether the public body will allow the price to be paid for the negotiated self-perform portion of the project to be deemed a cost of the work to which the general contractor/construction manager's percent fee applies; and

... Require proposals to indicate the proposer's fee for the negotiated self-perform portion of the project;

.. A description of the qualifications to be required of the firm, including submission of the firm's accident prevention program;

.. A description of the process the public body will use to evaluate qualifications and proposals, including evaluation factors, the relative weight of factors, and protest procedures including time limits for filing a protest, which in no event may limit the time to file a protest to fewer than four business days from the date the proposer was notified of the selection decision;

.. The form of the contract, including any contract for preconstruction services, to be awarded;

.. The estimated maximum allowable construction cost; and

.. The bid instructions to be used by the general contractor/construction manager finalists.

. [Empty]
.. Evaluation factors for selection of the general contractor/construction manager shall include, but not be limited to:

... Ability of the firm's professional personnel;

... The firm's past performance in negotiated and complex projects;

... The firm's ability to meet time and budget requirements;

... The scope of work the firm proposes to self-perform and its ability to perform that work;

.. The firm's proximity to the project location;

.. Recent, current, and projected workloads of the firm; and

.. The firm's approach to executing the project.

.. An agency may also consider the firm's outreach plan to include small business entities and disadvantaged business enterprises, and the firm's past performance in the utilization of such firms as an evaluation factor.

. A public body shall establish a committee to evaluate the proposals. After the committee has selected the most qualified finalists, at the time specified by the public body, these finalists shall submit final proposals, including sealed bids for the percent fee on the estimated maximum allowable construction cost and the fixed amount for the general conditions work specified in the request for proposal. The public body shall establish a time and place for the opening of sealed bids for the percent fee on the estimated maximum allowable construction cost and the fixed amount for the general conditions work specified in the request for proposal. At the time and place named, these bids must be publicly opened and read and the public body shall make all previous scoring available to the public. The public body shall select the firm submitting the highest scored final proposal using the evaluation factors and the relative weight of factors published in the public solicitation of proposals. A public body shall not evaluate or disqualify a proposal based on the terms of a collective bargaining agreement.

. The public body shall notify all finalists of the selection decision and make a selection summary of the final proposals available to all proposers within two business days of such notification. If the public body receives a timely written protest from a proposer, the public body may not execute a contract until two business days after the final protest decision is transmitted to the protestor. The protestor must submit its protest in accordance with the published protest procedures.

. Public bodies may contract with the selected firm to provide services during the design phase that may include life-cycle cost design considerations, value engineering, scheduling, cost estimating, constructability, alternative construction options for cost savings, and sequencing of work, and to act as the construction manager and general contractor during the construction phase.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2208.SL.pdf?cite=2014%20c%2042%20§%205[2014 c 42 § 5]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1466-S.SL.pdf?cite=2013%20c%20222%20§%2013[2013 c 222 § 13]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1197.SL.pdf?cite=2009%20c%2075%20§%206[2009 c 75 § 6]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1506-S2.SL.pdf?cite=2007%20c%20494%20§%20303[2007 c 494 § 303]; ]

== 39.10.370 - General contractor/construction manager procedure—Maximum allowable construction cost.
. The maximum allowable construction cost shall be used to establish a total contract cost for which the general contractor/construction manager shall provide a performance and payment bond. The maximum allowable construction cost shall be negotiated between the public body and the selected firm when the construction documents and specifications are at least ninety percent complete.

. Major bid packages may be bid in accordance with RCW 39.10.380 before agreement on the maximum allowable construction cost between the public body and the selected general contractor/construction manager. The general contractor/construction manager may issue an intent to award to the responsible bidder submitting the lowest responsive bid.

. The public body may, at its option, authorize the general contractor/construction manager to proceed with the bidding and award of bid packages and construction before receipt of complete project plans and specifications. Any contracts awarded under this subsection shall be incorporated in the negotiated maximum allowable construction cost.

. The total contract cost includes the fixed amount for the detailed specified general conditions work, the negotiated maximum allowable construction cost, the negotiated support services, and the percent fee on the negotiated maximum allowable construction cost. Negotiated support services may be included in the specified general conditions at the discretion of the public body.

. If the public body is unable to negotiate a satisfactory maximum allowable construction cost with the firm selected that the public body determines to be fair, reasonable, and within the available funds, negotiations with that firm shall be formally terminated and the public body shall negotiate with the next highest scored firm and continue until an agreement is reached or the process is terminated.

. If the maximum allowable construction cost varies more than fifteen percent from the bid estimated maximum allowable construction cost due to requested and approved changes in the scope by the public body, the percent fee shall be renegotiated.

. As part of the negotiation of the maximum allowable construction cost under subsection (1) of this section, on a project that the public body has elected to procure as a heavy civil construction project:

.. The general contractor/construction manager shall submit a proposed construction management and contracting plan, which must include, at a minimum:

... The scope of work and cost estimates for each bid package;

... A proposed price and scope of work for the negotiated self-perform portion of the project;

... The bases used by the general contractor/construction manager to develop all cost estimates, including the negotiated self-perform portion of the project; and

... The general contractor/construction manager's updated outreach plan to include small business entities, disadvantaged business entities, and any other disadvantaged or underutilized businesses as the public body may designate in the public solicitation of proposals, as subcontractors and suppliers for the project;

.. The public body and general contractor/construction manager may negotiate the scopes of work to be procured by bid and the price and scope of work for the negotiated self-perform portion of the project, if any;

.. The negotiated self-perform portion of the project must not exceed fifty percent of the cost of the work to construct the project;

.. Subject to the limitation of RCW 39.10.390(4), the public body may additionally negotiate with the general contractor/construction manager to determine on which scopes of work the general contractor/construction manager will be permitted to bid, if any;

.. The public body and general contractor/construction manager shall negotiate, to the public body's satisfaction, a fair and reasonable outreach plan;

.. If the public body is unable to negotiate to its reasonable satisfaction a component of this subsection (7), negotiations with the firm must be terminated and the public body shall negotiate with the next highest scored firm and continue until an agreement is reached or the process is terminated.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2208.SL.pdf?cite=2014%20c%2042%20§%206[2014 c 42 § 6]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1506-S2.SL.pdf?cite=2007%20c%20494%20§%20304[2007 c 494 § 304]; ]

== 39.10.380 - General contractor/construction manager procedure—Subcontract bidding procedure.
. All subcontract work and equipment and material purchases shall be competitively bid with public bid openings. Subcontract bid packages and equipment and materials purchases shall be awarded to the responsible bidder submitting the lowest responsive bid. In preparing subcontract bid packages, the general contractor/construction manager shall not be required to violate or waive terms of a collective bargaining agreement.

. All subcontract bid packages in which bidder eligibility was not determined in advance shall include the specific objective criteria that will be used by the general contractor/construction manager and the public body to evaluate bidder responsibility. If the lowest bidder submitting a responsive bid is determined by the general contractor/construction manager and the public body not to be responsible, the general contractor/construction manager and the public body must provide written documentation to that bidder explaining their intent to reject the bidder as not responsible and afford the bidder the opportunity to establish that it is a responsible bidder. Responsibility shall be determined in accordance with criteria listed in the bid documents. Protests concerning bidder responsibility determination by the general contractor/construction manager and the public body shall be in accordance with subsection (4) of this section.

. All subcontractors who bid work over three hundred thousand dollars shall post a bid bond. All subcontractors who are awarded a contract over three hundred thousand dollars shall provide a performance and payment bond for the contract amount. All other subcontractors shall provide a performance and payment bond if required by the general contractor/construction manager.

. If the general contractor/construction manager receives a written protest from a subcontractor bidder or an equipment or material supplier, the general contractor/construction manager shall not execute a contract for the subcontract bid package or equipment or material purchase order with anyone other than the protesting bidder without first providing at least two full business days' written notice to all bidders of the intent to execute a contract for the subcontract bid package. The protesting bidder must submit written notice of its protest no later than two full business days following the bid opening. Intermediate Saturdays, Sundays, and legal holidays are not counted.

. A low bidder who claims error and fails to enter into a contract is prohibited from bidding on the same project if a second or subsequent call for bids is made for the project.

. The general contractor/construction manager may negotiate with the lowest responsible and responsive bidder to negotiate an adjustment to the lowest bid or proposal price based upon agreed changes to the contract plans and specifications under the following conditions:

.. All responsive bids or proposal prices exceed the available funds;

.. The apparent low responsive bid or proposal does not exceed the available funds by the greater of one hundred twenty-five thousand dollars or two percent for projects valued over ten million dollars; and

.. The negotiated adjustment will bring the bid or proposal price within the amount of available funds.

. If the negotiation is unsuccessful, the subcontract work or equipment or material purchases must be rebid.

. The general contractor/construction manager must provide a written explanation if all bids are rejected.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1466-S.SL.pdf?cite=2013%20c%20222%20§%2014[2013 c 222 § 14]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1506-S2.SL.pdf?cite=2007%20c%20494%20§%20305[2007 c 494 § 305]; ]

== 39.10.385 - General contractor/construction manager procedure—Alternative subcontractor selection process.
As an alternative to the subcontractor selection process outlined in RCW 39.10.380, a general contractor/construction manager may, with the approval of the public body, select mechanical subcontractors, electrical subcontractors, or both, using the process outlined in this section. This alternative selection process may only be used when the anticipated value of the subcontract will exceed three million dollars. When using the alternative selection process, the general contractor/construction manager should select the subcontractor early in the life of the public works project.

. In order to use this alternative selection process, the general contractor/construction manager and the public body must determine that it is in the best interest of the public. In making this determination the general contractor/construction manager and the public body must:

.. Publish a notice of intent to use this alternative selection process in a legal newspaper published in or as near as possible to that part of the county where the public work will be constructed. Notice must be published at least fourteen calendar days before conducting a public hearing. The notice must include the date, time, and location of the hearing; a statement justifying the basis and need for the alternative selection process; how interested parties may, prior to the hearing, obtain the evaluation criteria and applicable weight given to each criteria that will be used for evaluation; and protest procedures including time limits for filing a protest, which may in no event, limit the time to file a protest to fewer than four business days from the date the proposer was notified of the selection decision;

.. Conduct a hearing and provide an opportunity for any interested party to submit written and verbal comments regarding the justification for using this selection process, the evaluation criteria, weights for each criteria, and protest procedures;

.. After the public hearing, consider the written and verbal comments received and determine if using this alternative selection process is in the best interests of the public; and

.. Issue a written final determination to all interested parties. All protests of the decision to use the alternative selection process must be in writing and submitted to the public body within seven calendar days of the final determination. Any modifications to the criteria, weights, and protest procedures based on comments received during the public hearing process must be included in the final determination.

. Contracts for the services of a subcontractor under this section must be awarded through a competitive process requiring a public solicitation of proposals. Notice of the public solicitation of proposals must be provided to the office of minority and women's business enterprises. The public solicitation of proposals must include:

.. A description of the project, including programmatic, performance, and technical requirements and specifications when available;

.. The reasons for using the alternative selection process;

.. A description of the minimum qualifications required of the firm;

.. A description of the process used to evaluate qualifications and proposals, including evaluation factors and the relative weight of factors;

.. Protest procedures;

.. The form of the contract, including any contract for preconstruction services, to be awarded;

.. The estimated maximum allowable subcontract cost; and

.. The bid instructions to be used by the finalists.

. Evaluation factors for selection of the subcontractor must include, but not be limited to:

.. Ability of the firm's professional personnel;

.. The firm's past performance on similar projects;

.. The firm's ability to meet time and budget requirements;

.. The scope of work the firm proposes to perform with its own forces and its ability to perform that work;

.. The firm's plan for outreach to minority and women-owned businesses;

.. The firm's proximity to the project location;

.. The firm's capacity to successfully complete the project;

.. The firm's approach to executing the project;

.. The firm's approach to safety on the project;

.. The firm's safety history; and

.. If the firm is selected as one of the most qualified finalists, the firm's fee and cost proposal.

. The general contractor/construction manager shall establish a committee to evaluate the proposals. At least one representative from the public body shall serve on the committee. Final proposals, including sealed bids for the percent fee on the estimated maximum allowable subcontract cost, and the fixed amount for the subcontract general conditions work specified in the request for proposal, will be requested from the most qualified firms.

. The general contractor/construction manager must notify all proposers of the most qualified firms that will move to the next phase of the selection process. The process may not proceed to the next phase until two business days after all proposers are notified of the committee's selection decision. At the request of a proposer, the general contractor/construction manager must provide the requesting proposer with a scoring summary of the evaluation factors for its proposal. Proposers filing a protest on the selection of the most qualified finalists must file the protest with the public body in accordance with the published protest procedures. The selection process may not advance to the next phase of selection until two business days after the final protest decision issued by the public body is transmitted to the protestor.

. The general contractor/construction manager and the public body shall select the firm submitting the highest scored final proposal using the evaluation factors and the relative weight of factors identified in the solicitation of proposals. The scoring of the nonprice factors must be made available at the opening of the fee and cost proposals. The general contractor/construction manager shall notify all proposers of the selection decision and make a selection summary of the final proposals, which shall be available to all proposers within two business days of such notification. The general contractor/construction manager may not evaluate or disqualify a proposal based on the terms of a collective bargaining agreement.

. If the public body receives a timely written protest from a "most qualified firm," the general contractor/construction manager may not execute a contract for the protested subcontract work until two business days after the final protest decision issued by the public body is transmitted to the protestor. The protestor must submit its protest in accordance with the published protest procedures.

. If the general contractor/construction manager is unable to negotiate a satisfactory maximum allowable subcontract cost with the firm selected deemed by public body and the general contractor/construction manager to be fair, reasonable, and within the available funds, negotiations with that firm must be formally terminated and the general contractor/construction manager may negotiate with the next highest scored firm until an agreement is reached or the process is terminated.

. With the approval of the public body, the general contractor/construction manager may contract with the selected firm to provide preconstruction services during the design phase that may include life-cycle cost design considerations, value engineering, scheduling, cost estimating, constructability, alternative construction options for cost savings, and sequencing of work; and to act as the mechanical or electrical subcontractor during the construction phase.

. The maximum allowable subcontract cost must be used to establish a total subcontract cost for purposes of a performance and payment bond. Total subcontract cost means the fixed amount for the detailed specified general conditions work, the negotiated maximum allowable subcontract cost, and the percent fee on the negotiated maximum allowable subcontract cost. Maximum allowable subcontract cost means the maximum cost to complete the work specified for the subcontract, including the estimated cost of work to be performed by the subcontractor's own forces, a percentage for risk contingency, negotiated support services, and approved change orders. The maximum allowable subcontract cost must be negotiated between the general contractor/construction manager and the selected firm when the construction documents and specifications are at least ninety percent complete. Final agreement on the maximum allowable subcontract cost is subject to the approval of the public body.

. If the work of the mechanical contractor or electrical contractor is completed for less than the maximum allowable subcontract cost, any savings not otherwise negotiated as part of an incentive clause becomes part of the risk contingency included in the general contractor/construction manager's maximum allowable construction cost. If the work of the mechanical contractor or the electrical contractor is completed for more than the maximum allowable subcontract cost, the additional cost is the responsibility of that subcontractor. An independent audit, paid for by the public body, must be conducted to confirm the proper accrual of costs as outlined in the contract.

. A mechanical or electrical contractor selected under this section may perform work with its own forces. In the event it elects to subcontract some of its work, it must select a subcontractor utilizing the procedure outlined in RCW 39.10.380.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1466-S.SL.pdf?cite=2013%20c%20222%20§%2015[2013 c 222 § 15]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6401.SL.pdf?cite=2010%20c%20163%20§%201[2010 c 163 § 1]; ]

== 39.10.390 - General contractor/construction manager procedure—Subcontract work.
. Except as provided in this section, bidding on subcontract work or for the supply of equipment or materials by the general contractor/construction manager or its subsidiaries is prohibited.

. The general contractor/construction manager, or its subsidiaries, may bid on subcontract work or for the supply of equipment or materials if:

.. The work within the subcontract bid package or equipment or materials is customarily performed or supplied by the general contractor/construction manager;

.. The bid opening is managed by the public body and is in compliance with RCW 39.10.380; and

.. Notification of the general contractor/construction manager's intention to bid is included in the public solicitation of bids for the bid package or for the equipment or materials.

. In no event may the general contractor/construction manager or its subsidiaries assign warranty responsibility or the terms of its contract or purchase order with vendors for equipment or material purchases to subcontract bid package bidders or subcontractors who have been awarded a contract. The value of subcontract work performed and equipment and materials supplied by the general contractor/construction manager may not exceed thirty percent of the negotiated maximum allowable construction cost, unless procured as a heavy civil construction project under this chapter. Negotiated support services performed by the general contractor/construction manager shall not be considered subcontract work for purposes of this subsection.

. Notwithstanding any contrary provision of this chapter, for a project that a public body has elected to procure as a heavy civil construction project under this chapter, at least thirty percent of the cost of the work to construct the project included in the negotiated maximum allowable construction cost must be procured through competitive sealed bidding in which bidding by the general contractor/construction manager or its subsidiaries is prohibited.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2208.SL.pdf?cite=2014%20c%2042%20§%207[2014 c 42 § 7]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1466-S.SL.pdf?cite=2013%20c%20222%20§%2016[2013 c 222 § 16]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1506-S2.SL.pdf?cite=2007%20c%20494%20§%20306[2007 c 494 § 306]; ]

== 39.10.400 - General contractor/construction manager procedure—Prebid determination of subcontractor eligibility.
. If determination of subcontractor eligibility prior to seeking bids is in the best interest of the project and critical to the successful completion of a subcontract bid package, the general contractor/construction manager and the public body may determine subcontractor eligibility to bid. The general contractor/construction manager and the public body must:

.. Conduct a hearing and provide an opportunity for any interested party to submit written and verbal comments regarding the justification for conducting bidder eligibility, the evaluation criteria, and weights for each criteria and subcriteria;

.. Publish a notice of intent to evaluate and determine bidder eligibility in a legal newspaper published in or as near as possible to that part of the county where the public work will be constructed at least fourteen calendar days before conducting a public hearing;

.. Ensure the public hearing notice includes the date, time, and location of the hearing, a statement justifying the basis and need for performing eligibility analysis before bid opening, and how interested parties may, at least five days before the hearing, obtain the specific eligibility criteria and applicable weights given to each criteria and subcriteria that will be used during evaluation;

.. After the public hearing, consider written and verbal comments received and determine if establishing bidder eligibility in advance of seeking bids is in the best interests of the project and critical to the successful completion of a subcontract bid package; and

.. Issue a written final determination to all interested parties. All protests of the decision to establish bidder eligibility before issuing a subcontractor bid package must be filed with the superior court within seven calendar days of the final determination. Any modifications to the eligibility criteria and weights shall be based on comments received during the public hearing process and shall be included in the final determination.

. Determinations of bidder eligibility shall be in accordance with the evaluation criteria and weights for each criteria established in the final determination and shall be provided to interested persons upon request. Any potential bidder determined not to meet eligibility criteria must be afforded one opportunity to establish its eligibility. Protests concerning bidder eligibility determinations shall be in accordance with subsection (1) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1466-S.SL.pdf?cite=2013%20c%20222%20§%2017[2013 c 222 § 17]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1506-S2.SL.pdf?cite=2007%20c%20494%20§%20307[2007 c 494 § 307]; ]

== 39.10.410 - General contractor/construction manager procedure—Subcontract agreements.
Subcontract agreements used by the general contractor/construction manager shall not:

. Delegate, restrict, or assign the general contractor/construction manager's implied duty not to hinder or delay the subcontractor. Nothing in this subsection (1) prohibits the general contractor/construction manager from requiring subcontractors not to hinder or delay the work of the general contractor/construction manager or other subcontractors and to hold subcontractors responsible for such damages;

. Delegate, restrict, or assign the general contractor/construction manager's authority to resolve subcontractor conflicts. The general contractor/construction manager may delegate or assign coordination of specific elements of the work, including: (a) The coordination of shop drawings among subcontractors; (b) the coordination among subcontractors in ceiling spaces and mechanical rooms; and (c) the coordination of a subcontractor's lower tier subcontractors. Nothing in this subsection prohibits the general contractor/construction manager from imposing a duty on its subcontractors to cooperate with the general contractor/construction manager and other subcontractors in the coordination of the work;

. Restrict the subcontractor's right to damages for changes to the construction schedule or work to the extent that the delay or disruption is caused by the general contractor/construction manager or entities acting for it. The general contractor/construction manager may require the subcontractor to provide notice that rescheduling or resequencing will result in delays or additional costs;

. Require the subcontractor to bear the cost of trade damage repair except to the extent the subcontractor is responsible for the damage. Nothing in this subsection (4) precludes the general contractor/construction manager from requiring the subcontractor to take reasonable steps to protect the subcontractor's work from trade damage; or

. Require the subcontractor to execute progress payment applications that waive claims for additional time or compensation or bond or retainage rights as a condition of receipt of progress payment, except to the extent the subcontractor has received or will receive payment. Nothing in this section precludes the general contractor/construction manager from requiring the subcontractor to provide notice of claims for additional time or compensation as a condition precedent to right of recovery or to execute a full and final release, including a waiver of bond and retainage rights, as a condition of final payment.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1506-S2.SL.pdf?cite=2007%20c%20494%20§%20308[2007 c 494 § 308]; ]

== 39.10.420 - Job order procedure—Public bodies may authorize and use.
. All public bodies of the state of Washington are authorized to award job order contracts and use the job order contracting procedure.

. [Empty]
.. The department of enterprise services may issue job order contract work orders for Washington state parks department projects and public hospital districts.

.. The department of enterprise services, the University of Washington, and Washington State University may issue job order contract work orders for the state regional universities and The Evergreen State College.

. Public bodies may use a job order contract for public works projects when a determination is made that the use of job order contracts will benefit the public by providing an effective means of reducing the total lead-time and cost for the construction of public works projects for repair and renovation required at public facilities through the use of unit price books and work orders by eliminating time-consuming, costly aspects of the traditional public works process, which require separate contracting actions for each small project.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1295-S.SL.pdf?cite=2019%20c%20212%20§%207[2019 c 212 § 7]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1395.SL.pdf?cite=2017%20c%20136%20§%201[2017 c 136 § 1]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2772.SL.pdf?cite=2016%20c%2052%20§%201[2016 c 52 § 1]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1466-S.SL.pdf?cite=2013%20c%20222%20§%2018[2013 c 222 § 18]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1768.SL.pdf?cite=2013%20c%20186%20§%201[2013 c 186 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2328.SL.pdf?cite=2012%20c%20102%20§%201[2012 c 102 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1197.SL.pdf?cite=2009%20c%2075%20§%207[2009 c 75 § 7]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1506-S2.SL.pdf?cite=2007%20c%20494%20§%20401[2007 c 494 § 401]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1788-S.SL.pdf?cite=2003%20c%20301%20§%201[2003 c 301 § 1]; ]

== 39.10.430 - Job order procedure—Contract award process.
. Job order contracts shall be awarded through a competitive process using public requests for proposals.

. The public body shall make an effort to solicit proposals from certified minority or certified woman-owned contractors to the extent permitted by the Washington state civil rights act, RCW 49.60.400.

. The public body shall publish, at least once in a statewide publication and legal newspaper of general circulation published in every county in which the public works project is anticipated, a request for proposals for job order contracts and the availability and location of the request for proposal documents. The public body shall ensure that the request for proposal documents at a minimum includes:

.. A detailed description of the scope of the job order contract including performance, technical requirements and specifications, functional and operational elements, minimum and maximum work order amounts, duration of the contract, and options to extend the job order contract;

.. The reasons for using job order contracts;

.. A description of the qualifications required of the proposer;

.. The identity of the specific unit price book to be used;

.. The minimum contracted amount committed to the selected job order contractor;

.. A description of the process the public body will use to evaluate qualifications and proposals, including evaluation factors and the relative weight of factors. The public body shall ensure that evaluation factors include, but are not limited to, proposal price and the ability of the proposer to perform the job order contract. In evaluating the ability of the proposer to perform the job order contract, the public body may consider: The ability of the professional personnel who will work on the job order contract; past performance on similar contracts; ability to meet time and budget requirements; past performance on approved subcontractor inclusion plans; ability to provide a performance and payment bond for the job order contract; recent, current, and projected workloads of the proposer; location; and the concept of the proposal;

.. The form of the contract to be awarded;

.. The method for pricing renewals of or extensions to the job order contract;

.. A notice that the proposals are subject to RCW 39.10.470; and

.. Other information relevant to the project.

. A public body shall establish a committee to evaluate the proposals. After the committee has selected the most qualified finalists, the finalists shall submit final proposals, including sealed bids based upon the identified unit price book. Such bids may be in the form of coefficient markups from listed price book costs. The public body shall award the contract to the firm submitting the highest scored final proposal using the evaluation factors and the relative weight of factors published in the public request for proposals and will notify the board of the award of the contract.

. The public body shall provide a protest period of at least ten business days following the day of the announcement of the apparent successful proposal to allow a protester to file a detailed statement of the grounds of the protest. The public body shall promptly make a determination on the merits of the protest and provide to all proposers a written decision of denial or acceptance of the protest. The public body shall not execute the contract until two business days following the public body's decision on the protest.

. The requirements of RCW 39.30.060 do not apply to requests for proposals for job order contracts.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1295-S.SL.pdf?cite=2019%20c%20212%20§%208[2019 c 212 § 8]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1506-S2.SL.pdf?cite=2007%20c%20494%20§%20402[2007 c 494 § 402]; ]

== 39.10.440 - Job order procedure—Contract requirements.
. The maximum total dollar amount that may be awarded under a job order contract is four million dollars per year for a maximum of three years. Any unused capacity from the previous year may be carried over for one year and added to the immediate following year's limit. The maximum annual volume including unused capacity shall not exceed the limit of two years. The maximum total dollar amount that may be awarded under a job order contract for the department of enterprise services, counties with a population of more than one million, and cities with a population of more than four hundred thousand is six million dollars per year for a maximum of three years. The maximum total dollar amounts are exclusive of Washington state sales and use tax.

. Job order contracts may be executed for an initial contract term of not to exceed two years, with the option of extending or renewing the job order contract for one year. All extensions or renewals must be priced as provided in the request for proposals. The extension or renewal must be mutually agreed to by the public body and the job order contractor.

. A public body may have no more than three job order contracts in effect at any one time, with the exception of the department of enterprise services, which may have six job order contracts in effect at any one time.

. At least ninety percent of work contained in a job order contract must be subcontracted to entities other than the job order contractor. The job order contractor must distribute contracts as equitably as possible among qualified and available subcontractors including certified minority and woman-owned subcontractors to the extent permitted by law as demonstrated on the subcontractor and supplier project submission, and shall limit subcontractor bonding requirements to the greatest extent possible.

. The job order contractor shall publish notification of intent to perform public works projects at the beginning of each contract year in a statewide publication and in a legal newspaper of general circulation in every county in which the public works projects are anticipated.

. Job order contractors shall pay prevailing wages for all work that would otherwise be subject to the requirements of chapter 39.12 RCW. Prevailing wages for all work performed pursuant to each work order must be the rates in effect at the time the individual work order is issued.

. If, in the initial contract term, the public body, at no fault of the job order contractor, fails to issue the minimum amount of work orders stated in the public request for proposals, the public body shall pay the contractor an amount equal to the difference between the minimum work order amount and the actual total of the work orders issued multiplied by an appropriate percentage for overhead and profit contained in the contract award coefficient for services as specified in the request for proposals. This is the contractor's sole remedy.

. All job order contracts awarded under this section must be signed before July 1, 2021; however the job order contract may be extended or renewed as provided for in this section.

. Public bodies may amend job order contracts awarded prior to July 1, 2007, in accordance with this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1295-S.SL.pdf?cite=2019%20c%20212%20§%209[2019 c 212 § 9]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5203.SL.pdf?cite=2015%20c%20173%20§%201[2015 c 173 § 1]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1466-S.SL.pdf?cite=2013%20c%20222%20§%2019[2013 c 222 § 19]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1506-S2.SL.pdf?cite=2007%20c%20494%20§%20403[2007 c 494 § 403]; ]

== 39.10.450 - Job order procedure—Work orders.
. The maximum dollar amount for a work order is five hundred thousand dollars, excluding Washington state sales and use tax.

. All work orders issued for the same project shall be treated as a single work order for purposes of the dollar limit on work orders.

. No more than twenty percent of the dollar value of a work order may consist of items of work not contained in the unit price book.

. Any new stand-alone permanent structure constructed under a work order shall not exceed three thousand gross square feet.

. A public body may issue no work orders under a job order contract until it has approved, in consultation with the office of minority and women's business enterprises or the equivalent local agency, a plan prepared by the job order contractor that equitably spreads certified women and minority business enterprise subcontracting opportunities, to the extent permitted by the Washington state civil rights act, RCW 49.60.400, among the various subcontract disciplines.

. For purposes of chapters 39.08, 39.12, 39.76, and 60.28 RCW, each work order issued shall be treated as a separate contract. The alternate filing provisions of RCW 39.12.040(2) apply to each work order that otherwise meets the eligibility requirements of RCW 39.12.040(2).

. The job order contract shall not be used for the procurement of architectural or engineering services not associated with specific work orders. Architectural and engineering services shall be procured in accordance with RCW 39.80.040.

. Any work order over three hundred fifty thousand dollars, excluding Washington state sales and use tax, and including over six hundred single trade hours shall utilize a state registered apprenticeship program for that single trade in accordance with RCW 39.04.320. Awarding entities may adjust this requirement for a specific work order for the following reasons:

.. The demonstrated lack of availability of apprentices in specific geographic areas;

.. A disproportionately high ratio of material costs to labor hours, which does not make feasible the required minimum levels of apprentice participation;

.. Participating contractors have demonstrated a good faith effort to comply with the requirements of RCW 39.04.300 and 39.04.310; or

.. Other criteria the awarding entity deems appropriate.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1295-S.SL.pdf?cite=2019%20c%20212%20§%2010[2019 c 212 § 10]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2328.SL.pdf?cite=2012%20c%20102%20§%202[2012 c 102 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1506-S2.SL.pdf?cite=2007%20c%20494%20§%20404[2007 c 494 § 404]; ]

== 39.10.460 - Job order procedure—Required information to board.
Each year, a public body shall provide to the board the following information for each job order contract for the period July 1st through June 30th:

. A list of work orders issued;

. The cost of each work order;

. A list of subcontractors hired under each work order;

. If requested by the board, a copy of the intent to pay prevailing wage and the affidavit of wages paid for each work order subcontract; and

. Any other information requested by the board.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2328.SL.pdf?cite=2012%20c%20102%20§%203[2012 c 102 § 3]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1506-S2.SL.pdf?cite=2007%20c%20494%20§%20405[2007 c 494 § 405]; ]

== 39.10.470 - Public inspection of certain records—Protection of trade secrets—Protection of documents submitted.
. Except as provided in subsections (2) and (3) of this section, all proceedings, records, contracts, and other public records relating to alternative public works transactions under this chapter shall be open to the inspection of any interested person, firm, or corporation in accordance with chapter 42.56 RCW.

. Trade secrets, as defined in RCW 19.108.010, or other proprietary information submitted by a bidder, offeror, or contractor in connection with an alternative public works transaction under this chapter shall not be subject to chapter 42.56 RCW if the bidder, offeror, or contractor specifically states in writing the reasons why protection is necessary, and identifies the data or materials to be protected.

. All documents related to a procurement under RCW 39.10.330 are exempt from disclosure until the notification of the highest scoring finalist is made in accordance with RCW 39.10.330(6) or the selection process is terminated, except as expressly required under RCW 39.10.330(3).

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1295-S.SL.pdf?cite=2019%20c%20212%20§%2011[2019 c 212 § 11]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2555.SL.pdf?cite=2014%20c%2019%20§%202[2014 c 19 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1133-S.SL.pdf?cite=2005%20c%20274%20§%20275[2005 c 274 § 275]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2607-S.SL.pdf?cite=1994%20c%20132%20§%2010[1994 c 132 § 10]; ]

== 39.10.480 - Construction of chapter—Waiver of other limits and requirements.
This chapter shall not be construed to affect or modify the existing statutory, regulatory, or charter powers of public bodies except to the extent that a procedure authorized by this chapter is adopted by a public body for a particular public works project. In that event, the normal contracting or procurement limits or requirements of a public body as imposed by statute, ordinance, resolution, or regulation shall be deemed waived or amended only to the extent necessary to accommodate such procedures for a particular public works project.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2607-S.SL.pdf?cite=1994%20c%20132%20§%209[1994 c 132 § 9]; ]

== 39.10.490 - Application of chapter.
The alternative public works contracting procedures authorized under this chapter are limited to public works contracts signed before July 1, 2021. Methods of public works contracting authorized under this chapter shall remain in full force and effect until completion of contracts signed before July 1, 2021.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1466-S.SL.pdf?cite=2013%20c%20222%20§%2020[2013 c 222 § 20]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1506-S2.SL.pdf?cite=2007%20c%20494%20§%20501[2007 c 494 § 501]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5060-S.SL.pdf?cite=2001%20c%20328%20§%205[2001 c 328 § 5]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1425-S.SL.pdf?cite=1997%20c%20376%20§%207[1997 c 376 § 7]; 1997 c 220 § 404 (Referendum Bill No. 48, approved June 17, 1997); http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2115.SL.pdf?cite=1995%203rd%20sp.s.%20c%201%20§%20305[1995 3rd sp.s. c 1 § 305]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2607-S.SL.pdf?cite=1994%20c%20132%20§%2012[1994 c 132 § 12]; ]

== 39.10.900 - Captions not law—1994 c 132.
Captions as used in this act do not constitute any part of law.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2607-S.SL.pdf?cite=1994%20c%20132%20§%2013[1994 c 132 § 13]; ]

== 39.10.901 - Severability—1994 c 132.
If any provision of this act or its application to any person or circumstance is held invalid, the remainder of the act or the application of the provision to other persons or circumstances is not affected.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2607-S.SL.pdf?cite=1994%20c%20132%20§%2014[1994 c 132 § 14]; ]

== 39.10.903 - Part headings and captions not law—2007 c 494.
Part headings and captions used in chapter 494, Laws of 2007 are not any part of the law.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1506-S2.SL.pdf?cite=2007%20c%20494%20§%20510[2007 c 494 § 510]; ]

== 39.10.904 - Effective dates—2007 c 494.
This act is necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and takes effect July 1, 2007, except for section 104 of this act, which takes effect immediately [May 15, 2007], and section 508 of this act, which takes effect June 30, 2007.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1506-S2.SL.pdf?cite=2007%20c%20494%20§%20512[2007 c 494 § 512]; ]

== 39.10.905 - Severability—2007 c 494.
If any provision of this act or its application to any person or circumstance is held invalid, the remainder of the act or the application of the provision to other persons or circumstances is not affected.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1506-S2.SL.pdf?cite=2007%20c%20494%20§%20513[2007 c 494 § 513]; ]

