= 39.34 - Interlocal cooperation act.
:toc:

== 39.34.010 - Declaration of purpose.
It is the purpose of this chapter to permit local governmental units to make the most efficient use of their powers by enabling them to cooperate with other localities on a basis of mutual advantage and thereby to provide services and facilities in a manner and pursuant to forms of governmental organization that will accord best with geographic, economic, population and other factors influencing the needs and development of local communities.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c239.pdf?cite=1967%20c%20239%20§%201[1967 c 239 § 1]; ]

== 39.34.020 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Public agency" means any agency, political subdivision, or unit of local government of this state including, but not limited to, municipal corporations, quasi municipal corporations, special purpose districts, and local service districts; any agency of the state government; any agency of the United States; any Indian tribe recognized as such by the federal government; and any political subdivision of another state.

. "State" means a state of the United States.

. "Watershed management partnership" means an interlocal cooperation agreement formed under the authority of RCW 39.34.200.

. "WRIA" has the definition in RCW 90.82.020.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5073.SL.pdf?cite=2003%20c%20327%20§%203[2003 c 327 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c33.pdf?cite=1985%20c%2033%20§%201[1985 c 33 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c36.pdf?cite=1979%20c%2036%20§%201[1979 c 36 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c283.pdf?cite=1977%20ex.s.%20c%20283%20§%2013[1977 ex.s. c 283 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c115.pdf?cite=1975%201st%20ex.s.%20c%20115%20§%201[1975 1st ex.s. c 115 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c34.pdf?cite=1973%20c%2034%20§%201[1973 c 34 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971c33.pdf?cite=1971%20c%2033%20§%201[1971 c 33 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c88.pdf?cite=1969%20c%2088%20§%201[1969 c 88 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c40.pdf?cite=1969%20c%2040%20§%201[1969 c 40 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c239.pdf?cite=1967%20c%20239%20§%203[1967 c 239 § 3]; ]

== 39.34.030 - Joint powers—Agreements for joint or cooperative action, requisites, effect on responsibilities of component agencies—Joint utilization of architectural or engineering services—Financing of joint projects.
. Any power or powers, privileges or authority exercised or capable of exercise by a public agency of this state may be exercised and enjoyed jointly with any other public agency of this state having the power or powers, privilege or authority, and jointly with any public agency of any other state or of the United States to the extent that laws of such other state or of the United States permit such joint exercise or enjoyment. Any agency of the state government when acting jointly with any public agency may exercise and enjoy all of the powers, privileges and authority conferred by this chapter upon a public agency.

. Any two or more public agencies may enter into agreements with one another for joint or cooperative action pursuant to the provisions of this chapter, except that any such joint or cooperative action by public agencies which are educational service districts and/or school districts shall comply with the provisions of RCW 28A.320.080. Appropriate action by ordinance, resolution or otherwise pursuant to law of the governing bodies of the participating public agencies shall be necessary before any such agreement may enter into force.

. Any such agreement shall specify the following:

.. Its duration;

.. The precise organization, composition and nature of any separate legal or administrative entity created thereby together with the powers delegated thereto, provided such entity may be legally created. Such entity may include a nonprofit corporation organized pursuant to chapter 24.03 or 24.06 RCW whose membership is limited solely to the participating public agencies or a partnership organized pursuant to chapter *25.04 or 25.05 RCW whose partners are limited solely to participating public agencies, or a limited liability company organized under chapter 25.15 RCW whose membership is limited solely to participating public agencies, and the funds of any such corporation, partnership, or limited liability company shall be subject to audit in the manner provided by law for the auditing of public funds;

.. Its purpose or purposes;

.. The manner of financing the joint or cooperative undertaking and of establishing and maintaining a budget therefor;

.. The permissible method or methods to be employed in accomplishing the partial or complete termination of the agreement and for disposing of property upon such partial or complete termination; and

.. Any other necessary and proper matters.

. In the event that the agreement does not establish a separate legal entity to conduct the joint or cooperative undertaking, the agreement shall contain, in addition to provisions specified in subsection (3)(a), (c), (d), (e), and (f) of this section, the following:

.. Provision for an administrator or a joint board responsible for administering the joint or cooperative undertaking. In the case of a joint board, public agencies that are party to the agreement shall be represented; and

.. The manner of acquiring, holding and disposing of real and personal property used in the joint or cooperative undertaking. Any joint board is authorized to establish a special fund with a state, county, city, or district treasurer servicing an involved public agency designated "Operating fund of . . . . . . joint board."

. No agreement made pursuant to this chapter relieves any public agency of any obligation or responsibility imposed upon it by law except that:

.. To the extent of actual and timely performance thereof by a joint board or other legal or administrative entity created by an agreement made pursuant to this chapter, the performance may be offered in satisfaction of the obligation or responsibility; and

.. With respect to one or more public agencies purchasing or otherwise contracting through a bid, proposal, or contract awarded by another public agency or by a group of public agencies, any obligation with respect to competitive bids or proposals that applies to the public agencies involved is satisfied if the public agency or group of public agencies that awarded the bid, proposal, or contract complied with its own statutory requirements and either (i) posted the bid or solicitation notice on a web site established and maintained by a public agency, purchasing cooperative, or similar service provider, for purposes of posting public notice of bid or proposal solicitations, or (ii) provided an access link on the state's web portal to the notice.

. [Empty]
.. Any two or more public agencies may enter into a contract providing for the joint utilization of architectural or engineering services if:

... The agency contracting with the architectural or engineering firm complies with the requirements for contracting for such services under chapter 39.80 RCW; and

... The services to be provided to the other agency or agencies are related to, and within the general scope of, the services the architectural or engineering firm was selected to perform.

.. Any agreement providing for the joint utilization of architectural or engineering services under this subsection must be executed for a scope of work specifically detailed in the agreement and must be entered into prior to commencement of procurement of such services under chapter 39.80 RCW.

. Financing of joint projects by agreement shall be as provided by law.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5958.SL.pdf?cite=2019%20c%2091%20§%201[2019 c 91 § 1]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5348-S.SL.pdf?cite=2015%20c%20232%20§%201[2015 c 232 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1264.SL.pdf?cite=2009%20c%20202%20§%206[2009 c 202 § 6]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2639-S.SL.pdf?cite=2008%20c%20198%20§%202[2008 c 198 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2615.SL.pdf?cite=2004%20c%20190%20§%201[2004 c 190 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2495-S.SL.pdf?cite=1992%20c%20161%20§%204[1992 c 161 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20568[1990 c 33 § 568]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c308.pdf?cite=1981%20c%20308%20§%202[1981 c 308 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c81.pdf?cite=1972%20ex.s.%20c%2081%20§%201[1972 ex.s. c 81 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c239.pdf?cite=1967%20c%20239%20§%204[1967 c 239 § 4]; ]

== 39.34.040 - Methods of filing agreements—Status of interstate agreements—Real party in interest—Actions.
Prior to its entry into force, an agreement made pursuant to this chapter shall be filed with the county auditor or, alternatively, listed by subject on a public agency's web site or other electronically retrievable public source. In the event that an agreement entered into pursuant to this chapter is between or among one or more public agencies of this state and one or more public agencies of another state or of the United States the agreement shall have the status of an interstate compact, but in any case or controversy involving performance or interpretation thereof or liability thereunder, the public agencies party thereto shall be real parties in interest and the state may maintain an action to recoup or otherwise make itself whole for any damages or liability which it may incur by reason of being joined as a party therein. Such action shall be maintainable against any public agency or agencies whose default, failure of performance, or other conduct caused or contributed to the incurring of damage or liability by the state.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2676.SL.pdf?cite=2006%20c%2032%20§%201[2006 c 32 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5046.SL.pdf?cite=1995%20c%2022%20§%201[1995 c 22 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2495-S.SL.pdf?cite=1992%20c%20161%20§%205[1992 c 161 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c239.pdf?cite=1967%20c%20239%20§%205[1967 c 239 § 5]; ]

== 39.34.050 - Duty to submit agreement to jurisdictional state officer or agency.
In the event that an agreement made pursuant to this chapter shall deal in whole or in part with the provision of services or facilities with regard to which an officer or agency of the state government has constitutional or statutory powers of control, the agreement shall, as a condition precedent to its entry into force, be submitted to the state officer or agency having such power of control. The agreement shall be approved or disapproved by the state officer or agency with regard to matters within his, her, or its jurisdiction within ninety days after receipt of the agreement. If a state officer or agency fails to act within the ninety-day time limit, the agreement shall be deemed approved by that state officer or agency.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2495-S.SL.pdf?cite=1992%20c%20161%20§%206[1992 c 161 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c239.pdf?cite=1967%20c%20239%20§%206[1967 c 239 § 6]; ]

== 39.34.055 - Public purchase agreements with public benefit nonprofit corporations.
The department of enterprise services may enter into an agreement with a public benefit nonprofit corporation to allow the public benefit nonprofit corporation to participate in state contracts for purchases administered by the department. Such agreement must comply with the requirements of RCW 39.34.030 through 39.34.050. For the purposes of this section "public benefit nonprofit corporation" means a public benefit nonprofit corporation as defined in RCW 24.03.005 that is receiving local, state, or federal funds either directly or through a public agency other than an Indian tribe or a political subdivision of another state.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5931-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2043%20§%20246[2011 1st sp.s. c 43 § 246]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2814.SL.pdf?cite=1994%20c%2098%20§%201[1994 c 98 § 1]; ]

== 39.34.060 - Participating agencies may appropriate funds and provide personnel, property, and services.
Any public agency entering into an agreement pursuant to this chapter may appropriate funds and may sell, lease, give, or otherwise supply property, personnel, and services to the administrative joint board or other legal or administrative entity created to operate the joint or cooperative undertaking.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2495-S.SL.pdf?cite=1992%20c%20161%20§%207[1992 c 161 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c239.pdf?cite=1967%20c%20239%20§%207[1967 c 239 § 7]; ]

== 39.34.070 - Authority of joint boards to receive loans or grants.
Any joint board created pursuant to the provisions of this chapter is hereby authorized to accept loans or grants of federal, state or private funds in order to accomplish the purposes of this chapter provided each of the participating public agencies is authorized by law to receive such funds.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c239.pdf?cite=1967%20c%20239%20§%208[1967 c 239 § 8]; ]

== 39.34.080 - Contracts to perform governmental activities which each contracting agency is authorized to perform.
Any one or more public agencies may contract with any one or more other public agencies to perform any governmental service, activity, or undertaking which each public agency entering into the contract is authorized by law to perform: PROVIDED, That such contract shall be authorized by the governing body of each party to the contract. Such contract shall set forth fully the purposes, powers, rights, objectives, and responsibilities of the contracting parties.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c239.pdf?cite=1967%20c%20239%20§%209[1967 c 239 § 9]; ]

== 39.34.085 - Agreements for operation of bus services.
In addition to the other powers granted by chapter 39.34 RCW, one or more cities or towns or a county, or any combination thereof, may enter into agreements with each other or with a public transportation agency of a contiguous state, or contiguous Canadian province, to allow a city or such other transportation agency to operate bus service for the transportation of the general public within the territorial boundaries of such city and/or county or to allow such city and/or county to operate such bus service within the jurisdiction of such other public agency when no such existing bus certificate of public convenience and necessity has been authorized by the Washington utilities and transportation commission: PROVIDED, HOWEVER, That such transportation may extend beyond the territorial boundaries of either party to the agreement if the agreement so provides, and if such service is not in conflict with existing bus service authorized by the Washington utilities and transportation commission. The provisions of this section shall be cumulative and nonexclusive and shall not affect any other right granted by this chapter or any other provision of law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977c46.pdf?cite=1977%20c%2046%20§%201[1977 c 46 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c139.pdf?cite=1969%20ex.s.%20c%20139%20§%201[1969 ex.s. c 139 § 1]; ]

== 39.34.090 - Agencies' contracting authority regarding electricity, utilities' powers, preserved.
Nothing in this chapter shall be construed to increase or decrease existing authority of any public agency of this state to enter into agreements or contracts with any other public agency of this state or of any other state or the United States with regard to the generation, transmission, or distribution of electricity or the existing powers of any private or public utilities.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c239.pdf?cite=1967%20c%20239%20§%2010[1967 c 239 § 10]; ]

== 39.34.100 - Powers conferred by chapter are supplemental.
The powers and authority conferred by this chapter shall be construed as in addition and supplemental to powers or authority conferred by any other law, and nothing contained herein shall be construed as limiting any other powers or authority of any public agency.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c239.pdf?cite=1967%20c%20239%20§%2011[1967 c 239 § 11]; ]

== 39.34.110 - Powers otherwise prohibited by Constitutions or federal laws.
No power, privilege, or other authority shall be exercised under this chapter where prohibited by the state Constitution or the Constitution or laws of the federal government.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c239.pdf?cite=1967%20c%20239%20§%2012[1967 c 239 § 12]; ]

== 39.34.130 - Transactions between state agencies—Charging of costs—Regulation by director of financial management.
Except as otherwise provided by law, the full costs of a state agency incurred in providing services or furnishing materials to or for another agency under chapter 39.34 RCW or any other statute shall be charged to the agency contracting for such services or materials and shall be repaid and credited to the fund or appropriation against which the expenditure originally was charged. Amounts representing a return of expenditures from an appropriation shall be considered as returned loans of services or of goods, supplies or other materials furnished, and may be expended as part of the original appropriation to which they belong without further or additional appropriation. Such interagency transactions shall be subject to regulation by the director of financial management, including but not limited to provisions for the determination of costs, prevention of interagency contract costs beyond those which are fully reimbursable, disclosure of reimbursements in the governor's budget and such other requirements and restrictions as will promote more economical and efficient operations of state agencies.

Except as otherwise provided by law, this section shall not apply to the furnishing of materials or services by one agency to another when other funds have been provided specifically for that purpose pursuant to law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c151.pdf?cite=1979%20c%20151%20§%2045[1979 c 151 § 45]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c61.pdf?cite=1969%20ex.s.%20c%2061%20§%201[1969 ex.s. c 61 § 1]; ]

== 39.34.140 - Transactions between state agencies—Procedures for payments through transfers upon accounts.
The director of financial management may establish procedures whereby some or all payments between state agencies may be made by transfers upon the accounts of the state treasurer in lieu of making such payments by warrant or check. Such procedures, when established, shall include provision for corresponding entries to be made in the accounts of the affected agencies.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c151.pdf?cite=1979%20c%20151%20§%2046[1979 c 151 § 46]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c61.pdf?cite=1969%20ex.s.%20c%2061%20§%202[1969 ex.s. c 61 § 2]; ]

== 39.34.150 - Transactions between state agencies—Advancements.
State agencies are authorized to advance funds to defray charges for materials to be furnished or services to be rendered by other state agencies. Such advances shall be made only upon the approval of the director of financial management, or his or her order made pursuant to an appropriate regulation requiring advances in certain cases. An advance shall be made from the fund or appropriation available for the procuring of such services or materials, to the state agency which is to perform the services or furnish the materials, in an amount no greater than the estimated charges therefor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20805[2011 c 336 § 805]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c151.pdf?cite=1979%20c%20151%20§%2047[1979 c 151 § 47]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c61.pdf?cite=1969%20ex.s.%20c%2061%20§%203[1969 ex.s. c 61 § 3]; ]

== 39.34.160 - Transactions between state agencies—Time limitation for expenditure of advance—Unexpended balance.
An advance made under RCW 39.34.130 through 39.34.150 from appropriated funds shall be available for expenditure for no longer than the period of the appropriation from which it was made. When the actual costs of materials and services have been finally determined, and in no event later than the lapsing of the appropriation, any unexpended balance of the advance shall be returned to the agency for credit to the fund or account from which it was made.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c61.pdf?cite=1969%20ex.s.%20c%2061%20§%204[1969 ex.s. c 61 § 4]; ]

== 39.34.170 - Transactions between state agencies—Powers and authority cumulative.
The powers and authority conferred by RCW 39.34.130 through 39.34.160 shall be construed as in addition and supplemental to powers or authority conferred by any other law, and not to limit any other powers or authority of any public agency expressly granted by any other statute.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c61.pdf?cite=1969%20ex.s.%20c%2061%20§%205[1969 ex.s. c 61 § 5]; ]

== 39.34.180 - Criminal justice responsibilities—Interlocal agreements—Termination.
. Each county, city, and town is responsible for the prosecution, adjudication, sentencing, and incarceration of misdemeanor and gross misdemeanor offenses committed by adults in their respective jurisdictions, and referred from their respective law enforcement agencies, whether filed under state law or city ordinance, and must carry out these responsibilities through the use of their own courts, staff, and facilities, or by entering into contracts or interlocal agreements under this chapter to provide these services. Nothing in this section is intended to alter the statutory responsibilities of each county for the prosecution, adjudication, sentencing, and incarceration for not more than one year of felony offenders, nor shall this section apply to any offense initially filed by the prosecuting attorney as a felony offense or an attempt to commit a felony offense.

. The following principles must be followed in negotiating interlocal agreements or contracts: Cities and counties must consider (a) anticipated costs of services; and (b) anticipated and potential revenues to fund the services, including fines and fees, criminal justice funding, and state-authorized sales tax funding levied for criminal justice purposes.

. If an agreement as to the levels of compensation within an interlocal agreement or contract for gross misdemeanor and misdemeanor services cannot be reached between a city and county, then either party may invoke binding arbitration on the compensation issued by notice to the other party. In the case of establishing initial compensation, the notice shall request arbitration within thirty days. In the case of nonrenewal of an existing contract or interlocal agreement, the notice must be given one hundred twenty days prior to the expiration of the existing contract or agreement and the existing contract or agreement remains in effect until a new agreement is reached or until an arbitration award on the matter of fees is made. The city and county each select one arbitrator, and the initial two arbitrators pick a third arbitrator.

. A city or county that wishes to terminate an agreement for the provision of court services must provide written notice of the intent to terminate the agreement in accordance with RCW 3.50.810 and 35.20.010.

. For cities or towns that have not adopted, in whole or in part, criminal code or ordinance provisions related to misdemeanor and gross misdemeanor crimes as defined by state law, this section shall have no application until July 1, 1998.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5472-S.SL.pdf?cite=2001%20c%2068%20§%204[2001 c 68 § 4]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6211-S.SL.pdf?cite=1996%20c%20308%20§%201[1996 c 308 § 1]; ]

== 39.34.190 - Watershed management plan projects—Use of water-related revenues.
. The legislative authority of a city or county and the governing body of any special purpose district enumerated in subsection (2) of this section may authorize up to ten percent of its water-related revenues to be expended in the implementation of watershed management plan projects or activities that are in addition to the county's, city's, or district's existing water-related services or activities. Such limitation on expenditures shall not apply to water-related revenues of a public utility district organized according to Title 54 RCW. Water-related revenues include rates, charges, and fees for the provision of services relating to water supply, treatment, distribution, and management generally, and those general revenues of the local government that are expended for water management purposes. A local government may not expend for this purpose any revenues that were authorized by voter approval for other specified purposes or that are specifically dedicated to the repayment of municipal bonds or other debt instruments.

. The following special purpose districts may exercise the authority provided by this section:

.. Water districts, sewer districts, and water-sewer districts organized under Title 57 RCW;

.. Public utility districts organized under Title 54 RCW;

.. Irrigation, reclamation, conservation, and similar districts organized under Titles 87 and 89 RCW;

.. Port districts organized under Title 53 RCW;

.. Diking, drainage, and similar districts organized under Title 85 RCW;

.. Flood control and similar districts organized under Title 86 RCW;

.. Lake or beach management districts organized under chapter 36.61 RCW;

.. Aquifer protection areas organized under chapter 36.36 RCW; and

.. Shellfish protection districts organized under chapter 90.72 RCW.

. The authority for expenditure of local government revenues provided by this section shall be applicable broadly to the implementation of watershed management plans addressing water supply, water transmission, water quality treatment or protection, or any other water-related purposes. Such plans include but are not limited to plans developed under the following authorities:

.. Watershed plans developed under chapter 90.82 RCW;

.. Salmon recovery plans developed under chapter 77.85 RCW;

.. Watershed management elements of comprehensive land use plans developed under the growth management act, chapter 36.70A RCW;

.. Watershed management elements of shoreline master programs developed under the shoreline management act, chapter 90.58 RCW;

.. Nonpoint pollution action plans developed under the Puget Sound water quality management planning authorities of chapter 90.71 RCW and chapter 400-12 WAC;

.. Other comprehensive management plans addressing watershed health at a WRIA level or sub-WRIA basin drainage level;

.. Coordinated water system plans under *chapter 70.116 RCW and similar regional plans for water supply; and

.. Any combination of the foregoing plans in an integrated watershed management plan.

. The authority provided by this section to expend revenues for watershed management plan implementation shall be construed broadly to include, but not be limited to:

.. The coordination and oversight of plan implementation, including funding a watershed management partnership for this purpose;

.. Technical support, monitoring, and data collection and analysis;

.. The design, development, construction, and operation of projects included in the plan; and

.. Conducting activities and programs included as elements in the plan.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3186-S2.SL.pdf?cite=2008%20c%20301%20§%2026[2008 c 301 § 26]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5073.SL.pdf?cite=2003%20c%20327%20§%202[2003 c 327 § 2]; ]

== 39.34.200 - Watershed management partnerships—Formation.
Any two or more public agencies may enter into agreements with one another to form a watershed management partnership for the purpose of implementing any portion or all elements of a watershed management plan, including the coordination and oversight of plan implementation. The plan may be any plan or plan element described in RCW 39.34.190(3). The watershed partnership agreement shall include the provisions required of all interlocal agreements under RCW 39.34.030(3). The agreement shall be filed pursuant to RCW 39.34.040 with the county auditor of each county lying within the geographical watershed area to be addressed by the partnership. The public agencies forming the partnership shall designate a treasurer for the deposit, accounting, and handling of the funds of the partnership. The treasurer shall be either a county treasurer or a city treasurer of a county or city participating in the agreement to form the partnership.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5073.SL.pdf?cite=2003%20c%20327%20§%204[2003 c 327 § 4]; ]

== 39.34.210 - Watershed management partnerships—Indebtedness—Bonds.
Where a watershed management partnership formed under the authority of RCW 39.34.200 establishes a separate legal entity to conduct the cooperating undertaking of the partnership, such legal entity is authorized for the purpose of carrying out such undertaking to contract indebtedness and to issue and sell general obligation bonds pursuant to and in the manner provided for general county bonds in chapters 36.67 and 39.46 RCW and other applicable statutes, and to issue revenue bonds pursuant to and in the manner provided for revenue bonds in chapter 36.67 RCW and other applicable statutes. The joint board established by the partnership agreement shall perform the functions referenced in chapter 36.67 RCW to be performed by the county legislative authority in the case of county bonds.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5073.SL.pdf?cite=2003%20c%20327%20§%206[2003 c 327 § 6]; ]

== 39.34.215 - Watershed management partnerships—Eminent domain authority.
. As limited in subsection (3) of this section, a watershed management partnership formed or qualified under the authority of RCW 39.34.200 and 39.34.210, including the separate legal entity established by such a partnership under RCW 39.34.030(3)(b) to conduct the cooperative undertaking of the partnership under the same statutory authority, may exercise the power of eminent domain as provided in chapter 8.12 RCW.

. The eminent domain authority granted under subsection (1) of this section may be exercised only for those utility purposes for which the watershed partnership was formed and is limited solely to providing water services to its customers.

. Subsection (1) of this section applies only to a watershed management partnership that:

.. Was formed or qualified before July 1, 2006, under the authority of RCW 39.34.200 and 39.34.210;

.. Is not engaged in planning or in implementing a plan for a water resource inventory area under the terms of chapter 90.82 RCW;

.. Is composed entirely of cities and water-sewer districts authorized to exercise the power of eminent domain in the manner provided by chapter 8.12 RCW; and

.. Is governed by a board of directors consisting entirely of elected officials from the cities and water-sewer districts that constitute the watershed management partnership.

. A watershed management partnership exercising authority under this section shall:

.. Comply with the notice requirements of RCW 8.25.290; and

.. Provide notice to the city, town, or county with jurisdiction over the subject property by certified mail thirty days prior to the partnership board authorizing condemnation.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5241.SL.pdf?cite=2011%20c%2097%20§%201[2011 c 97 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1332-S.SL.pdf?cite=2009%20c%20504%20§%201[2009 c 504 § 1]; ]

== 39.34.220 - Watershed management plans—Additional authority for implementation—Existing agreements not affected.
The amendments by chapter 327, Laws of 2003 to the interlocal cooperation act authorities are intended to provide additional authority to public agencies for the purposes of implementing watershed management plans, and do not affect any agreements among public agencies existing on July 27, 2003.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5073.SL.pdf?cite=2003%20c%20327%20§%207[2003 c 327 § 7]; ]

== 39.34.230 - Covered emergencies—Interlocal agreements for mutual aid and cooperation—Liability of state—Existing rights.
. During a covered emergency, the *department of community, trade, and economic development may enter into interlocal agreements under this chapter with one or more public agencies for the purposes of providing mutual aid and cooperation to any public agency affected by the cause of the emergency.

. All legal liability by a public agency and its employees for damage to property or injury or death to persons caused by acts done or attempted during, or while traveling to or from, a covered emergency, or in preparation for a covered emergency, pursuant to an interlocal agreement entered into under this section, or under the color of this section in a bona fide attempt to comply therewith, shall be the obligation of the state of Washington. Suits may be instituted and maintained against the state for the enforcement of such liability, or for the indemnification of any public agency or its employees for damage done to their private property, or for any judgment against them for acts done in good faith in compliance with this chapter: PROVIDED, That the foregoing shall not be construed to result in indemnification in any case of willful misconduct, gross negligence, or bad faith on the part of any public agency or any of a public agency's employees: PROVIDED, That should the United States or any agency thereof, in accordance with any federal statute, rule, or regulation, provide for the payment of damages to property and/or for death or injury as provided for in this section, then and in that event there shall be no liability or obligation whatsoever upon the part of the state of Washington for any such damage, death, or injury for which the United States government assumes liability.

. For purposes of this section, "covered emergency" means an emergency for which the governor has proclaimed a state of emergency under RCW 43.06.010, and for which the governor has authorized the *department of community, trade, and economic development to enter into interlocal agreements under this section.

. This section shall not affect the right of any person to receive benefits to which he or she would otherwise be entitled under the workers' compensation law, or under any pension or retirement law, nor the right of any such person to receive any benefits or compensation under any act of congress.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6950.SL.pdf?cite=2008%20c%20181%20§%20101[2008 c 181 § 101]; ]

== 39.34.900 - Short title.
This chapter may be cited as the "Interlocal Cooperation Act."

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c239.pdf?cite=1967%20c%20239%20§%202[1967 c 239 § 2]; ]

== 39.34.920 - Effective date—1967 c 239.
The effective date of this chapter is July 1, 1967.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c239.pdf?cite=1967%20c%20239%20§%2015[1967 c 239 § 15]; ]

