= 39.19 - Office of minority and women's business enterprises.
:toc:

== 39.19.010 - Intent.
The legislature finds that minority and women-owned businesses are significantly under-represented and have been denied equitable competitive opportunities in contracting. It is the intent of this chapter to mitigate societal discrimination and other factors in participating in public works and in providing goods and services and to delineate a policy that an increased level of participation by minority and women-owned and controlled businesses is desirable at all levels of state government. The purpose and intent of this chapter are to provide the maximum practicable opportunity for increased participation by minority and women-owned and controlled businesses in participating in public works and the process by which goods and services are procured by state agencies and educational institutions from the private sector.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c328.pdf?cite=1987%20c%20328%20§%201[1987 c 328 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c120.pdf?cite=1983%20c%20120%20§%201[1983 c 120 § 1]; ]

== 39.19.020 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Advisory committee" means the advisory committee on minority and women's business enterprises.

. "Broker" means a person that provides a bona fide service, such as professional, technical, consultant, brokerage, or managerial services and assistance in the procurement of essential personnel, facilities, equipment, materials, or supplies required for performance of a contract.

. "Contractor" means an individual or entity granted state certification and awarded either a direct contract with an agency or an indirect contract as a subcontractor to perform a service or provide goods.

. "Director" means the director of the office of minority and women's business enterprises.

. "Educational institutions" means the state universities, the regional universities, The Evergreen State College, and the community colleges.

. "Goals" means annual overall agency goals, expressed as a percentage of dollar volume, for participation by minority and women-owned and controlled businesses and shall not be construed as a minimum goal for any particular contract or for any particular geographical area. It is the intent of this chapter that such overall agency goals shall be achievable and shall be met on a contract-by-contract or class-of-contract basis.

. "Goods and/or services" includes professional services and all other goods and services.

. "Office" means the office of minority and women's business enterprises.

. "Person" includes one or more individuals, partnerships, associations, organizations, corporations, cooperatives, legal representatives, trustees and receivers, or any group of persons.

. "Procurement" means the purchase, lease, or rental of any goods or services.

. "Public works" means all work, construction, highway and ferry construction, alteration, repair, or improvement other than ordinary maintenance, which a state agency or educational institution is authorized or required by law to undertake.

. "State agency" includes the state of Washington and all agencies, departments, offices, divisions, boards, commissions, and correctional and other types of institutions.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5418-S.SL.pdf?cite=2019%20c%20434%20§%202[2019 c 434 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6572-S.SL.pdf?cite=1996%20c%2069%20§%204[1996 c 69 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c328.pdf?cite=1987%20c%20328%20§%202[1987 c 328 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c120.pdf?cite=1983%20c%20120%20§%202[1983 c 120 § 2]; ]

== 39.19.030 - Office of minority and women's business enterprises—Director—Powers and duties.
There is hereby created the office of minority and women's business enterprises. The governor shall appoint a director for the office, subject to confirmation by the senate. The director may employ a deputy director and a confidential secretary, both of which shall be exempt under chapter 41.06 RCW, and such staff as are necessary to carry out the purposes of this chapter.

The office shall consult with the minority and women's business enterprises advisory committee to:

. Develop, plan, and implement programs to provide an opportunity for participation by qualified minority and women-owned and controlled businesses in public works and the process by which goods and services are procured by state agencies and educational institutions from the private sector;

. Develop a comprehensive plan insuring that qualified minority and women-owned and controlled businesses are provided an opportunity to participate in public contracts for public works and goods and services;

. Identify barriers to equal participation by qualified minority and women-owned and controlled businesses in all state agency and educational institution contracts;

. Establish annual overall goals for participation by qualified minority and women-owned and controlled businesses for each state agency and educational institution to be administered on a contract-by-contract basis or on a class-of-contracts basis;

. Develop and maintain a central minority and women's business enterprise certification list for all state agencies and educational institutions. No business is entitled to certification under this chapter unless it meets the definition of small business concern as established by the office. All applications for certification under this chapter shall be sworn under oath;

. Develop, implement, and operate a system of monitoring compliance with this chapter;

. Adopt rules under chapter 34.05 RCW, the Administrative Procedure Act, governing: (a) Establishment of agency goals; (b) development and maintenance of a central minority and women's business enterprise certification program, including a definition of "small business concern" which shall be consistent with the small business requirements defined under section 3 of the Small Business Act, 15 U.S.C. Sec. 632, and its implementing regulations as guidance; (c) procedures for monitoring and enforcing compliance with goals, regulations, contract provisions, and this chapter; (d) utilization of standard clauses by state agencies and educational institutions, as specified in RCW 39.19.050; and (e) determination of an agency's or educational institution's goal attainment consistent with the limitations of RCW 39.19.075;

. Submit an annual report to the governor and the legislature outlining the progress in implementing this chapter;

. Investigate complaints of violations of this chapter with the assistance of the involved agency or educational institution; and

. Cooperate and act jointly or by division of labor with the United States or other states, and with political subdivisions of the state of Washington and their respective minority, socially and economically disadvantaged and women business enterprise programs to carry out the purposes of this chapter. However, the power which may be exercised by the office under this subsection permits investigation and imposition of sanctions only if the investigation relates to a possible violation of chapter 39.19 RCW, and not to violation of local ordinances, rules, regulations, however denominated, adopted by political subdivisions of the state.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6572-S.SL.pdf?cite=1996%20c%2069%20§%205[1996 c 69 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c175.pdf?cite=1989%20c%20175%20§%2085[1989 c 175 § 85]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c328.pdf?cite=1987%20c%20328%20§%203[1987 c 328 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c120.pdf?cite=1983%20c%20120%20§%203[1983 c 120 § 3]; ]

== 39.19.041 - Ad hoc advisory committees.
The director may establish ad hoc advisory committees, as necessary, to assist in the development of policies to carry out the purposes of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1107-S.SL.pdf?cite=1995%20c%20269%20§%201302[1995 c 269 § 1302]; ]

== 39.19.050 - Standard clauses required in requests for proposals, advertisements, and bids.
The rules adopted under RCW 39.19.030 shall include requirements for standard clauses in requests for proposals, advertisements, bids, or calls for bids, necessary to carry out the purposes of this chapter, which shall include notice of the statutory penalties under RCW 39.19.080 and 39.19.090 for noncompliance.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c120.pdf?cite=1983%20c%20120%20§%205[1983 c 120 § 5]; ]

== 39.19.060 - Compliance with public works and procurement goals—Plan to maximize opportunity for minority and women-owned businesses.
. Each state agency and educational institution shall comply with the annual goals established for that agency or institution under this chapter for public works and procuring goods or services. This chapter applies to all public works and procurement by state agencies and educational institutions, including all contracts and other procurement under chapters 28B.10, 39.04, 39.26, 43.19, and 47.28 RCW.

. Each state agency shall adopt a plan, developed in consultation with the director and the advisory committee, to ensure that minority and women-owned businesses are afforded the maximum practicable opportunity to directly and meaningfully participate in the execution of public contracts for public works and goods and services. The plan shall include specific measures the agency will undertake to increase the participation of certified minority and women-owned businesses.

. The office shall annually notify the governor, the state auditor, and the joint legislative audit and review committee of all agencies and educational institutions not in compliance with this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5418-S.SL.pdf?cite=2019%20c%20434%20§%203[2019 c 434 § 3]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2222-S2.SL.pdf?cite=1996%20c%20288%20§%2028[1996 c 288 § 28]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1493-S.SL.pdf?cite=1993%20c%20512%20§%209[1993 c 512 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c120.pdf?cite=1983%20c%20120%20§%206[1983 c 120 § 6]; ]

== 39.19.070 - Compliance with goals—Bidding procedures.
It is the intent of this chapter that the goals established under this chapter for participation by minority and women-owned and controlled businesses be achievable. If necessary to accomplish this intent, contracts may be awarded to the next lowest responsible bidder in turn, or all bids may be rejected and new bids obtained, if the lowest responsible bidder does not meet the goals established for a particular contract under this chapter. The dollar value of the total contract used for the calculation of the specific contract goal may be increased or decreased to reflect executed change orders. An apparent low-bidder must be in compliance with the contract provisions required under this chapter as a condition precedent to the granting of a notice of award by any state agency or educational institution.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2191-S.SL.pdf?cite=1994%20c%2015%20§%201[1994 c 15 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c328.pdf?cite=1987%20c%20328%20§%204[1987 c 328 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c120.pdf?cite=1983%20c%20120%20§%207[1983 c 120 § 7]; ]

== 39.19.075 - Compliance with goals—Valuation of goods or services.
For purposes of measuring an agency's or educational institution's goal attainment, any regulations adopted under RCW 39.19.030(7)(e) must provide that if a certified minority and women's business enterprise is a broker of goods or materials required under a contract, the contracting agency or educational institution may count only the dollar value of the fee or commission charged and not the value of goods or materials provided. The contracting agency or educational institution may, at its discretion, fix the dollar value of the fee or commission charged at either the actual dollar value of the fee or commission charged or at a standard percentage of the total value of the brokered goods, which percentage must reflect the fees or commissions generally paid to brokers for providing such services.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6572-S.SL.pdf?cite=1996%20c%2069%20§%206[1996 c 69 § 6]; ]

== 39.19.080 - Prohibited activities—Penalties.
. A person, firm, corporation, business, union, or other organization shall not:

.. Prevent or interfere with a contractor's or subcontractor's compliance with this chapter, or any rule adopted under this chapter;

.. Submit false or fraudulent information to the state concerning compliance with this chapter or any such rule;

.. Fraudulently obtain, retain, attempt to obtain or retain, or aid another in fraudulently obtaining or retaining or attempting to obtain or retain certification as a minority or women's business enterprise for the purpose of this chapter;

.. Knowingly make a false statement, whether by affidavit, verified statement, report, or other representation, to a state official or employee for the purpose of influencing the certification or denial of certification of any entity as a minority or women's business enterprise;

.. Knowingly obstruct, impede, or attempt to obstruct or impede any state official or employee who is investigating the qualification of a business entity that has requested certification as a minority or women's business enterprise;

.. Fraudulently obtain, attempt to obtain, or aid another person in fraudulently obtaining or attempting to obtain public moneys to which the person is not entitled under this chapter; or

.. Knowingly make false statements that any entity is or is not certified as a minority or women's business enterprise for purposes of obtaining a contract governed by this chapter.

. Any person or entity violating this chapter or any rule adopted under this chapter shall be subject to the penalties in RCW 39.19.090. Nothing in this section prevents the state agency or educational institution from pursuing such procedures or sanctions as are otherwise provided by statute, rule, or contract provision.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c328.pdf?cite=1987%20c%20328%20§%205[1987 c 328 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c120.pdf?cite=1983%20c%20120%20§%208[1983 c 120 § 8]; ]

== 39.19.090 - Compliance with chapter or contract—Remedies.
If a person, firm, corporation, or business does not comply with any provision of this chapter or with a contract requirement established under this chapter, the state may withhold payment, debar the contractor, suspend, or terminate the contract and subject the contractor to civil penalties of up to ten percent of the amount of the contract or up to five thousand dollars for each violation. The office shall adopt, by rule, criteria for the imposition of penalties under this section. Wilful repeated violations, exceeding a single violation, may disqualify the contractor from further participation in state contracts for a period of up to three years. An apparent low-bidder must be in compliance with the contract provisions required under this chapter as a condition precedent to the granting of a notice of award by any state agency or educational institution.

The office shall follow administrative procedures under chapter 34.05 RCW in determining a violation and imposing penalties under this chapter.

The procedures and sanctions in this section are not exclusive; nothing in this section prevents the state agency or educational institution administering the contracts from pursuing such procedures or sanctions as are otherwise provided by statute, rule, or contract provision.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c328.pdf?cite=1987%20c%20328%20§%206[1987 c 328 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c120.pdf?cite=1983%20c%20120%20§%209[1983 c 120 § 9]; ]

== 39.19.100 - Enforcement by attorney general—Injunctive relief.
The attorney general may bring an action in the name of the state against any person to restrain and prevent the doing of any act prohibited or declared to be unlawful in this chapter. The attorney general may, in the discretion of the court, recover the costs of the action including reasonable attorneys' fees and the costs of investigation.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c328.pdf?cite=1987%20c%20328%20§%2012[1987 c 328 § 12]; ]

== 39.19.110 - Enforcement by attorney general—Investigative powers.
. Whenever the attorney general believes that any person (a) may be in possession, custody, or control of any original or copy of any book, record, report, memorandum, paper, communication, tabulation, map, chart, photograph, mechanical transcription, or other tangible document or recording, wherever situated, that the attorney general believes to be relevant to the subject matter of an investigation, the attorney general may require such person to answer written interrogatories or give oral testimony regarding a possible violation of this chapter, or of any provision of a contract as required by this chapter, or (b) may have knowledge of any information that the attorney general believes relevant to the subject matter of such an investigation, the attorney general may, before instituting a civil proceeding thereon, execute in writing and cause to be served upon such a person, a civil investigative demand requiring the person to produce the documentary material and permit inspection and copying, to answer in writing written interrogatories, to give oral testimony, or any combination of demands pertaining to the documentary material or information. Documents and information obtained under this section shall not be admissible in criminal prosecutions.

. Each such demand shall:

.. State the statute, the alleged violation of which is under investigation, and the general subject matter of the investigation;

.. State with reasonable specificity what documentary material is required, if the demand is for the production of documentary material;

.. Prescribe a return date governed by the court rules within which the documentary material is to be produced, the answers to written interrogatories are to be made, or a date, time, and place at which oral testimony is to be taken; and

.. Identify the members of the attorney general's staff to whom such documentary material is to be made available for inspection and copying, to whom answers to written interrogatories are to be made, or who are to conduct the examination for oral testimony.

. No such demand may:

.. Contain any requirement that would be unreasonable or improper if contained in a subpoena duces tecum, a request for answers to written interrogatories, or a notice of deposition upon oral examination issued under the court rules of this state; or

.. Require the disclosure of any documentary material which would be privileged, or which for any other reason would not be required by a subpoena duces tecum issued by a court of this state.

. Service of any such demand may be made by:

.. Delivering a duly executed copy thereof to the person to be served, or, if that person is not a natural person, to any officer or managing agent of the person to be served;

.. Delivering a duly executed copy thereof to the principal place of business in this state of the person to be served; or

.. Mailing by registered or certified mail a duly executed copy thereof addressed to the person to be served at the principal place of business in this state, or, if that person has no place of business in this state, to the person's principal office or place of business.

. [Empty]
.. Documentary material demanded under this section shall be produced for inspection and copying during normal business hours at the principal office or place of business of the person served, or at such other times and places as may be agreed upon by the person served and the attorney general;

.. Written interrogatories in a demand served under this section shall be answered in the same manner as provided in the civil rules for superior court;

.. The oral testimony of any person obtained pursuant to a demand served under this section shall be taken in the same manner as provided in the civil rules for superior court for the taking of depositions. In the course of the deposition, the assistant attorney general conducting the examination may exclude all persons other than the person being examined, the person's counsel, and the officer before whom the testimony is to be taken from the place where the examination is held;

.. Any person compelled to appear pursuant to a demand for oral testimony under this section may be accompanied by counsel;

.. The oral testimony of any person obtained pursuant to a demand served under this section shall be taken in the county within which the person resides, is found, or transacts business, or in such other place as may be agreed upon between the person served and the attorney general.

. No documentary material, answers to written interrogatories, or transcripts of oral testimony produced pursuant to a demand, or copies thereof, may, unless otherwise ordered by a superior court for good cause shown, be produced for inspection or copying by, nor may the contents thereof be disclosed to, anyone other than an authorized employee or agent of the attorney general, without the consent of the person who produced such material, answered written interrogatories, or gave oral testimony: PROVIDED, That under such reasonable terms and conditions as the attorney general shall prescribe, the copies of such documentary material, answers to written interrogatories, or transcripts of oral testimony shall be available for inspection and copying by the person who produced the material, answered written interrogatories, or gave oral testimony, or any duly authorized representative of that person. The attorney general or any assistant attorney general may use such copies of documentary material, answers to written interrogatories, or transcripts of oral testimony as he or she determines necessary to enforce this chapter, including presentation before any court: PROVIDED FURTHER, That any such material, answers to written interrogatories, or transcripts of oral testimony that contain material designated by the declarant to be trade secrets shall not be presented except with the approval of the court in which the action is pending after adequate notice to the person furnishing the material, answers to written interrogatories, or oral testimony.

. At any time before the return date specified in the demand, or within twenty days after the demand has been served, whichever period is shorter, a petition to extend the return date for, or to modify or set aside a demand issued pursuant to subsection (1) of this section, stating good cause, may be filed in the superior court for Thurston county, or in any other county where the parties reside or are found. A petition, by the person on whom the demand is served, stating good cause, to require the attorney general or any person to perform any duty imposed by this section, and all other petitions in connection with a demand, may be filed in the superior court for Thurston county, or in the county where the parties reside. The court shall have jurisdiction to impose such sanctions as are provided for in the civil rules for superior court with respect to discovery motions.

. Whenever any person fails to comply with any civil investigative demand for documentary material, answers to written interrogatories, or oral testimony duly served upon that person under this section, or whenever satisfactory copying or reproduction of any such material cannot be done and the person refuses to surrender such material, the attorney general may file, in the trial court of general jurisdiction in the county in which the person resides, is found, or transacts business, and serve upon that person a petition for an order of the court for the enforcement of this section, except that if such person transacts business in more than one county, the petition shall be filed in the county in which the person maintains his or her principal place of business or in such other county as may be agreed upon by the parties to the petition. Whenever any petition is filed under this section in the trial court of general jurisdiction in any county, the court shall have jurisdiction to hear and determine the matter so presented and to enter such order or orders as may be required to carry into effect this section, and may impose such sanctions as are provided for in the civil rules for superior court with respect to discovery motions.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c328.pdf?cite=1987%20c%20328%20§%2013[1987 c 328 § 13]; ]

== 39.19.120 - Certification of business enterprises.
The office shall be the sole authority to perform certification of minority business enterprises, socially and economically disadvantaged business enterprises, and women's business enterprises throughout the state of Washington. Certification by the state office will allow these firms to participate in programs for these enterprises administered by the state of Washington, any city, town, county, special purpose district, public corporation created by the state, municipal corporation, or quasi-municipal corporation within the state of Washington.

This statewide certification process will prevent duplication of effort, achieve efficiency, and permit local jurisdictions to further develop, implement, and/or enhance comprehensive systems of monitoring and compliance for contracts issued by their agencies.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c328.pdf?cite=1987%20c%20328%20§%207[1987 c 328 § 7]; ]

== 39.19.140 - Implementation of statewide certification.
Implementation of statewide certification shall be effective January 1, 1988, following consultation by the office with appropriate state and local officials who currently administer similar certification programs. Any business having been certified under any of the programs identified pursuant to *RCW 39.19.130 as a minority and women's business enterprise shall be deemed certified by the office as of January 1, 1988.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c328.pdf?cite=1987%20c%20328%20§%209[1987 c 328 § 9]; ]

== 39.19.150 - Local government may petition for reconsideration of business certification.
. Any city, county, town, special purpose district, public corporation created by the state, municipal corporation, or quasi-municipal corporation having reason to believe that a particular minority and women's business enterprise should not have been certified under RCW 39.19.140 may petition the office for reconsideration. The basis for the petition may be one or more of the following:

.. The office's rules or regulations were improperly applied; or

.. Material facts relating to the minority and women's business enterprise's certification application to the office are untrue.

. The petitioner shall carry the burden of persuasion. The affected minority or women's business enterprise shall receive notice of the petition and an opportunity to respond.

. After reviewing the information presented in support of and in opposition to the petition, the office shall issue a written decision, granting or denying the petition. If the office grants the petition, it may revoke, suspend, or refuse to renew the certification or impose sanctions under this chapter as appropriate.

. The office's decision on a petition is administratively final and the rights of appeal set out in the office regulations shall apply. A certification shall remain in effect while a petition is pending.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c328.pdf?cite=1987%20c%20328%20§%2010[1987 c 328 § 10]; ]

== 39.19.160 - Local government responsible for monitoring compliance.
Any city, town, county, special purpose district, public corporation created by the state, municipal corporation, or quasi-municipal corporation within the state of Washington utilizing the certification by the office retains the responsibility for monitoring compliance with the programs under its jurisdiction. The office shall not be responsible for enforcement of local ordinances, rules, or regulations, however titled.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c328.pdf?cite=1987%20c%20328%20§%2011[1987 c 328 § 11]; ]

== 39.19.170 - Prequalification of minority and women-owned businesses—Waiver of performance bond.
. State agencies shall not require a performance bond for any public works project that does not exceed twenty-five thousand dollars awarded to a prequalified and certified minority or woman-owned business that has been prequalified as provided under subsection (2) of this section.

. A limited prequalification questionnaire shall be required assuring:

.. That the bidder has adequate financial resources or the ability to secure such resources;

.. That the bidder can meet the performance schedule;

.. That the bidder is experienced in the type of work to be performed; and

.. That all equipment to be used is adequate and functioning and that all equipment operators are qualified to operate such equipment.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1493-S.SL.pdf?cite=1993%20c%20512%20§%2010[1993 c 512 § 10]; ]

== 39.19.200 - Minority and women's business enterprises account—Created.
The minority and women's business enterprises account is created in the custody of the state treasurer. All receipts from RCW 39.19.210, 39.19.220, and 39.19.230 shall be deposited in the account. Expenditures from the account may be used only for the purposes defraying all or part of the costs of the office in administering this chapter. Only the director or the director's designee may authorize expenditures from the account. Moneys in the account may be spent only after appropriation.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1800.SL.pdf?cite=1993%20c%20195%20§%201[1993 c 195 § 1]; ]

== 39.19.210 - Businesses using the office—Fees.
The office may charge a reasonable fee or other appropriate charge, to be set by rule adopted by the office under chapter 34.05 RCW, to a business using the services of the office.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1800.SL.pdf?cite=1993%20c%20195%20§%202[1993 c 195 § 2]; ]

== 39.19.220 - Political subdivisions—Fees.
The office may charge to a political subdivision in this state a reasonable fee or other appropriate charge, to be set by rule adopted by the office under chapter 34.05 RCW, prorated on the relative benefit to the political subdivision, for the certification under this chapter of a business.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1800.SL.pdf?cite=1993%20c%20195%20§%203[1993 c 195 § 3]; ]

== 39.19.230 - State agencies and educational institutions—Fees.
The office may charge to a state agency and educational institutions, as both are defined in RCW 39.19.020, a reasonable fee or other appropriate charge, to be set by rule adopted by the office under chapter 34.05 RCW, based upon the state agency's or educational institution's expenditure level of funds subject to the office.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1800.SL.pdf?cite=1993%20c%20195%20§%204[1993 c 195 § 4]; ]

== 39.19.240 - Linked deposit program—Compilation of information—Notification regarding enterprises no longer certified—Monitoring loans.
. The office shall, in consultation with the state treasurer and the *department of community, trade, and economic development, compile information on minority and women's business enterprises that have received financial assistance through a qualified public depositary under the provisions of RCW 43.86A.060. The information shall include, but is not limited to:

.. Name of the qualified public depositary;

.. Geographic location of the minority or women's business enterprise;

.. Name of the minority or women's business enterprise;

.. Date of last certification by the office and certification number;

.. Type of business;

.. Amount and term of the loan to the minority or women's business enterprise; and

.. Other information the office deems necessary for the implementation of this section.

. The office shall notify the state treasurer of minority or women's business enterprises that are no longer certified under the provisions of this chapter. The written notification shall contain information regarding the reason for the decertification and information on financing provided to the minority or women's business enterprise under RCW 43.86A.060.

. The office shall, in consultation with the state treasurer and the *department of community, trade, and economic development, monitor the performance of loans made to minority and women-owned business enterprises under RCW 43.86A.060.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5782-S2.SL.pdf?cite=2005%20c%20302%20§%205[2005 c 302 § 5]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2456-S.SL.pdf?cite=2002%20c%20305%20§%202[2002 c 305 § 2]; ]

== 39.19.250 - Participation in contracts by qualified minority and women-owned and controlled businesses—Data—Contact people—Reports.
. For the purpose of annual reporting on progress required by *section 1 of this act, each state agency and educational institution shall submit data to the office and the office of minority and women's business enterprises on the participation by qualified minority and women-owned and controlled businesses in the agency's or institution's contracts and other related information requested by the director. The director of the office of minority and women's business enterprises shall determine the content and format of the data and the reporting schedule, which must be at least annually.

. The office must develop and maintain a list of contact people at each state agency and educational institution who are able to present to hearings of the appropriate committees of the legislature its progress in carrying out the purposes of chapter 39.19 RCW.

. The office must submit a report aggregating the data received from each state agency and educational institution to the legislature and the governor.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5418-S.SL.pdf?cite=2019%20c%20434%20§%204[2019 c 434 § 4]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1087.SL.pdf?cite=2009%20c%20348%20§%202[2009 c 348 § 2]; ]

== 39.19.910 - Effective date—Applicability—1983 c 120.
. This act is necessary for the immediate preservation of the public peace, health, and safety, the support of the state government and its existing public institutions, and shall take effect July 1, 1983.

. Contracts entered into before September 1, 1983, are not subject to this act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c120.pdf?cite=1983%20c%20120%20§%2021[1983 c 120 § 21]; ]

== 39.19.920 - Severability—Conflict with federal requirements—1983 c 120.
. If any provision of this act or its application to any person or circumstance is held invalid, the remainder of the act or the application of the provision to other persons or circumstances is not affected.

. If any part of this chapter is found to be in conflict with federal requirements which are a prescribed condition to the allocation of federal funds to the state the conflicting part of this chapter is hereby declared to be inoperative solely to the extent of the conflict and with respect to the agencies directly affected, and such finding or determination shall not affect the operation of the remainder of this chapter in its application to the agencies concerned. The rules under this chapter shall meet federal requirements which are a necessary condition to the receipt of federal funds by the state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c120.pdf?cite=1983%20c%20120%20§%2018[1983 c 120 § 18]; ]

