= 39.67 - Agreements between taxing districts.
:toc:

== 39.67.010 - Agreements contingent on property tax levy—Authorized.
Any agreement or contract between two taxing districts other than the state which is otherwise authorized by law may be made contingent upon a particular property tax levy rate of an identified taxing district other than the state where such rate affects the regular property tax rate of one of the parties to the contract and therefore affects the party's resources with which to perform under the contract. The governing body of every taxing district that could have its tax levy adversely affected by such a contract shall be notified about the contract.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c274.pdf?cite=1988%20c%20274%20§%202[1988 c 274 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c107.pdf?cite=1986%20c%20107%20§%201[1986 c 107 § 1]; ]

== 39.67.020 - Transfer of funds between taxing districts.
Any taxing district other than the state may transfer funds to another taxing district other than the state where the regular property tax levy rate of the second district may affect the regular property tax levy rate of the first district and where such transfer is part of an agreement whereby proration or reduction of property taxes is lessened or avoided. The governing body of every taxing district that could have its tax levy adversely affected by such an agreement shall be notified about the agreement.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c274.pdf?cite=1988%20c%20274%20§%203[1988 c 274 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c107.pdf?cite=1986%20c%20107%20§%202[1986 c 107 § 2]; ]

