= 39.62 - Uniform facsimile signature of public officials act.
:toc:

== 39.62.010 - Definitions.
As used in this chapter:

. "Public security" means a bond, note, certificate of indebtedness, or other obligation for the payment of money, issued by this state or by any of its departments, agencies, counties, cities, towns, municipal corporations, junior taxing districts, school districts, or other instrumentalities or by any of its political subdivisions.

. "Instrument of payment" means a check, draft, warrant, or order for the payment, delivery, or transfer of funds.

. "Authorized officer" means any official of this state or any of its departments, agencies, counties, cities, towns, municipal corporations, junior taxing districts, school districts, or other instrumentalities or any of its political subdivisions whose signature to a public security or instrument of payment is required or permitted.

. "Facsimile signature" means a reproduction by engraving, imprinting, stamping, or other means of the manual signature of an authorized officer.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c86.pdf?cite=1969%20c%2086%20§%201[1969 c 86 § 1]; ]

== 39.62.020 - Facsimile signature—Authorized—Legal effect.
Any authorized officer, after filing with the secretary of state his or her manual signature certified by him or her under oath, may execute or cause to be executed with a facsimile signature in lieu of his or her manual signature:

. Any public security: PROVIDED, That at least one signature required or permitted to be placed thereon shall be manually subscribed, and

. Any instrument of payment.

Upon compliance with this chapter by the authorized officer, his or her facsimile signature has the same legal effect as his or her manual signature.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20811[2011 c 336 § 811]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c86.pdf?cite=1969%20c%2086%20§%202[1969 c 86 § 2]; ]

== 39.62.030 - Facsimile seal—Authorized—Legal effect.
When the seal of this state or any of its departments, agencies, counties, cities, towns, municipal corporations, junior taxing districts, school districts, or other instrumentalities or of any of its political subdivisions is required in the execution of a public security or instrument of payment, the authorized officer may cause the seal to be printed, engraved, stamped or otherwise placed in facsimile thereon. The facsimile seal has the same legal effect as the impression of the seal.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c86.pdf?cite=1969%20c%2086%20§%203[1969 c 86 § 3]; ]

== 39.62.040 - Unauthorized use—Penalty.
Any person who with intent to defraud uses on a public security or an instrument of payment:

. A facsimile signature, or any reproduction of it, of any authorized officer, or

. Any facsimile seal, or any reproduction of it, of this state or any of its departments, agencies, counties, cities, towns, municipal corporations, junior taxing districts, school districts, or other instrumentalities or of any of its political subdivisions is guilty of a class B felony punishable according to chapter 9A.20 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20213[2003 c 53 § 213]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c86.pdf?cite=1969%20c%2086%20§%204[1969 c 86 § 4]; ]

== 39.62.900 - Construction—Uniformity.
This chapter shall be so construed as to effectuate its general purpose to make uniform the law of those states which enact it.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c86.pdf?cite=1969%20c%2086%20§%205[1969 c 86 § 5]; ]

== 39.62.910 - Short title.
This act may be cited as the uniform facsimile signature of public officials act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c86.pdf?cite=1969%20c%2086%20§%206[1969 c 86 § 6]; ]

