= 39.59 - Public funds—Authorized investments.
:toc:

== 39.59.010 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Bond" means any agreement which may or may not be represented by a physical instrument, including but not limited to bonds, notes, warrants, or certificates of indebtedness, that evidences an obligation under which the issuer agrees to pay a specified amount of money, with or without interest, at a designated time or times either to registered owners or bearers.

. "Local government" means any county, city, town, special purpose district, political subdivision, municipal corporation, or quasi-municipal corporation, including any public corporation, authority, or other instrumentality created by such an entity.

. "State" includes any state in the United States, other than the state of Washington.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6349.SL.pdf?cite=2016%20c%20152%20§%209[2016 c 152 § 9]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5024.SL.pdf?cite=2015%20c%20225%20§%2050[2015 c 225 § 50]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2352.SL.pdf?cite=2002%20c%20332%20§%2022[2002 c 332 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c281.pdf?cite=1988%20c%20281%20§%201[1988 c 281 § 1]; ]

== 39.59.020 - Authorized investments—Local government authority.
. Local governments in the state of Washington are authorized to invest their funds and money in their custody or possession, eligible for investment, in investments authorized by this chapter.

. Nothing in this section is intended to limit or otherwise restrict a local government from investing in additional authorized investments if that local government has specific authority to do so.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6349.SL.pdf?cite=2016%20c%20152%20§%2010[2016 c 152 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c281.pdf?cite=1988%20c%20281%20§%202[1988 c 281 § 2]; ]

== 39.59.040 - Authorized investments—Bonds, warrants, certificates, and other investments.
Any local government in the state of Washington may invest in:

. Bonds of the state of Washington and any local government in the state of Washington;

. General obligation bonds of a state and general obligation bonds of a local government of a state, which bonds have at the time of investment one of the three highest credit ratings of a nationally recognized rating agency;

. Subject to compliance with RCW 39.56.030, registered warrants of a local government in the same county as the government making the investment;

. Certificates, notes, or bonds of the United States, or other obligations of the United States or its agencies, or of any corporation wholly owned by the government of the United States; or United States dollar denominated bonds, notes, or other obligations that are issued or guaranteed by supranational institutions, provided that, at the time of investment, the institution has the United States government as its largest shareholder;

. Federal home loan bank notes and bonds, federal land bank bonds and federal national mortgage association notes, debentures and guaranteed certificates of participation, or the obligations of any other government sponsored corporation whose obligations are or may become eligible as collateral for advances to member banks as determined by the board of governors of the federal reserve system;

. Bankers' acceptances purchased on the secondary market;

. Commercial paper purchased in the secondary market, provided that any local government of the state of Washington that invests in such commercial paper must adhere to the investment policies and procedures adopted by the state investment board; and

. Corporate notes purchased on the secondary market, provided that any local government of the state of Washington that invests in such notes must adhere to the investment policies and procedures adopted by the state investment board.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6349.SL.pdf?cite=2016%20c%20152%20§%2011[2016 c 152 § 11]; ]

