= 39.06 - Public works—Registration, licensing, of contractors.
:toc:

== 39.06.010 - Contracts with unregistered or unlicensed contractors and with other violators prohibited.
No agency of the state or any of its political subdivisions may execute a contract:

. With any contractor who is not registered or licensed as may be required by the laws of this state other than contractors on highway projects who have been prequalified as required by RCW 47.28.070, with the department of transportation to perform highway construction, reconstruction, or maintenance; or

. For two years from the date that a violation is finally determined, with any person or entity who has been determined by the respective administering agency to have violated RCW 50.12.070(1)(b), 51.16.070(1)(b), or * 82.32.070(1)(b). During this two-year period, the person or entity may not be permitted to bid, or have a bid considered, on any public works contract.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1514.SL.pdf?cite=1997%20c%2054%20§%201[1997 c 54 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%2043[1984 c 7 § 43]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c70.pdf?cite=1967%20c%2070%20§%203[1967 c 70 § 3]; ]

== 39.06.020 - Verification of subcontractor responsibility criteria.
A public works contractor must verify responsibility criteria for each first tier subcontractor, and a subcontractor of any tier that hires other subcontractors must verify responsibility criteria for each of its subcontractors. Verification shall include that each subcontractor, at the time of subcontract execution, meets the responsibility criteria listed in RCW 39.04.350(1) and possesses an electrical contractor license, if required by chapter 19.28 RCW, or an elevator contractor license, if required by chapter 70.87 RCW. This verification requirement, as well as the responsibility criteria, must be included in every public works contract and subcontract of every tier.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2010-S.SL.pdf?cite=2007%20c%20133%20§%203[2007 c 133 § 3]; ]

