= 39.69 - Public loans to municipal corporations.
:toc:

== 39.69.010 - "Municipal corporation" defined.
As used in this chapter, "municipal corporation" includes counties, cities, towns, port districts, water-sewer districts, school districts, metropolitan park districts, or such other units of local government which are authorized to issue obligations.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1264.SL.pdf?cite=1999%20c%20153%20§%2053[1999 c 153 § 53]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c19.pdf?cite=1987%20c%2019%20§%201[1987 c 19 § 1]; ]

== 39.69.020 - Loan agreements.
Any municipal corporation may enter into a loan agreement containing the terms and conditions of a loan from an agency of the state of Washington or the United States of America and evidencing the obligation of the municipal corporation to repay that loan under the terms and conditions set forth in the loan agreement. A loan agreement may provide that the municipal corporation will repay the loan solely from revenues set aside into a special fund for repayment of that loan. In the case of a municipal corporation authorized to borrow money payable from taxes, and authorized to levy such taxes, the loan agreement may provide that repayment of the loan is a general obligation of the municipal corporation, or both a general obligation and an obligation payable from revenues set aside into a special fund.

The state or federal agency making the loan shall have such rights of recovery in the event of default in payment or other breach of the loan agreement as may be provided in the loan agreement or otherwise by law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c19.pdf?cite=1987%20c%2019%20§%202[1987 c 19 § 2]; ]

== 39.69.030 - Application of constitutional debt limitations.
Nothing in this chapter authorizes municipal corporations to incur indebtedness beyond constitutional indebtedness limitations.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c19.pdf?cite=1987%20c%2019%20§%203[1987 c 19 § 3]; ]

== 39.69.040 - Chapter supplemental.
The authority under this chapter is supplemental and in addition to the authority to issue obligations under any other provision of law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c19.pdf?cite=1987%20c%2019%20§%204[1987 c 19 § 4]; ]

