= 39.72 - Lost or destroyed evidence of indebtedness.
:toc:

== 39.72.010 - Local government indebtedness—Issuance of duplicate instrument—Written affidavit—Loss recovery.
. In case of the loss or destruction of a warrant for the payment of money, or any bond or other instrument or evidence of indebtedness, issued by a municipality, the municipality may issue or cause to be issued a duplicate in lieu thereof, bearing the same designation and for the same amount as the original. The duplicate instrument is subject in all other respects to the same provisions of law as the original instrument.

.. Before a duplicate instrument is issued in accordance with this section, the issuing officer shall require the person making application for issuance of the duplicate to file a written affidavit specifically alleging on oath:

... That the applicant is the proper owner, payee, or legal representative of the owner or payee of the original instrument;

... The date of issue, number, amount, and for what services, claim, or purpose the original instrument or series of instruments of which it is a part was issued;

... That the original instrument has been lost or destroyed; and

... That the original instrument has not been paid or has not been received by the applicant.

.. In the event that an original instrument and its duplicate instrument are both presented for payment as a result of forgery or fraud, the agency, department, or officer that issues a duplicate under this section is responsible for endeavoring to recover any losses suffered by the municipality.

. For purposes of this section, "municipality" means any county, city, town, district, or other political subdivision or municipal corporation of the state of Washington, or an agency, department, or officer of the municipality.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5767-S.SL.pdf?cite=2016%20sp.s.%20c%205%20§%202[2016 sp.s. c 5 § 2]; 1975-'76 2nd ex.s. c 77 § 1; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c61.pdf?cite=1965%20ex.s.%20c%2061%20§%204[1965 ex.s. c 61 § 4]; ]

== 39.72.020 - Local government indebtedness—Records to be kept—Cancellation of originals.
When a municipal corporation issues a duplicate instrument, as authorized in this chapter, the issuing officer of such municipal corporation shall keep a full and complete record of all warrants, bonds, or other instruments alleged to have been lost or destroyed, which were issued by such municipal corporation, and of the issue of any duplicate therefor; and upon the issuance of any duplicate such officer shall enter upon his or her books the cancellation of the original instrument and immediately notify the treasurer of the county, city or other municipal corporation, the state auditor, and all trustees and paying agencies authorized to redeem such instruments on behalf of the municipal corporation, of such cancellation. The treasurer shall keep a similar list of all warrants, bonds, or other instruments so canceled.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20813[2011 c 336 § 813]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c61.pdf?cite=1965%20ex.s.%20c%2061%20§%205[1965 ex.s. c 61 § 5]; ]

