= 39.86 - Private activity bond allocation.
:toc:

== 39.86.100 - Legislative findings and policy.
The federal internal revenue code of 1986, as amended imposes ceilings on the aggregate amount of certain types of bonds, including tax-exempt private activity bonds and other types, that may be issued during any calendar year by or on behalf of states and their political subdivisions. The code provides a formula for allocating the annual tax-exempt private activity bond ceiling among various issuers of private activity bonds for housing, student loans, exempt facilities, and redevelopment projects within a state, but permits each state to enact a different allocation method that is appropriate to that state's needs. In addition, congress might, from time to time, amend the code by authorizing state ceilings on additional types of bonds. The purpose of this chapter is to provide a flexible and efficient method of allocating the annual state ceiling in Washington in a manner that recognizes the need of the state and its political subdivisions to finance activities or projects that satisfy a substantial public purpose.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2753-S.SL.pdf?cite=2010%201st%20sp.s.%20c%206%20§%203[2010 1st sp.s. c 6 § 3]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5197.SL.pdf?cite=2001%20c%20330%20§%201[2001 c 330 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c297.pdf?cite=1987%20c%20297%20§%201[1987 c 297 § 1]; ]

== 39.86.110 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Agency" means the department of commerce.

. "Bond use category" means: (a) Any of the following categories of bonds which are subject to the annual state tax-exempt private activity bond ceiling: (i) Housing, (ii) student loans, (iii) small issue, (iv) exempt facility, (v) redevelopment, and (vi) remainder; and (b) any other categories of bonds described in the code for which there is a separate ceiling, with the exception of bonds designated solely for school district purposes.

. "Bonds" means bonds, notes, or other obligations of an issuer.

. "Carryforward" is an allocation or reallocation of the state ceiling which is carried from one calendar year to a later year, in accordance with the code.

. "Code" means the federal internal revenue code of 1986, as amended.

. "Director" means the director of the agency or the director's designee.

. "Exempt facility" means the bond use category which includes all bonds which are exempt facility bonds as described in the code, except those for qualified residential rental projects.

. "Firm and convincing evidence" means documentation that satisfies the director that the issuer is committed to the prompt financing of, and will issue bonds for, the project or program for which it requests an allocation from the state ceiling.

. "Housing" means the bond use category which includes: (a) Mortgage revenue bonds and mortgage credit certificates as described in the code; and (b) exempt facility bonds for qualified residential rental projects as described in the code.

. "Initial allocation" means the portion or dollar value of the annual state tax-exempt private activity bond ceiling which initially in each calendar year is allocated to a bond use category for the issuance of private activity bonds, in accordance with RCW 39.86.120.

. "Issuer" means the state, any agency or instrumentality of the state, any political subdivision, or any other entity authorized to issue bonds under state law.

. "Original allocation" means any allocation of bond authority by a mandatory formula in the code, except for the initial allocations of the annual state ceiling on tax-exempt private activity bonds.

. "Private activity bonds" means obligations that are private activity bonds as defined in the code or bonds for purposes described in section 1317(25) of the federal internal revenue code of 1986, as amended.

. "Program" means the activities for which housing bonds may be issued.

. "Redevelopment" means the bond use category which includes qualified redevelopment bonds as described in the code.

. "Remainder" means that portion of the annual state tax-exempt private activity bond ceiling remaining after initial allocations are made under RCW 39.86.120 for any other bond use category.

. "Small issue" means the bond use category which includes all industrial development bonds that constitute qualified small issue bonds, as described in the code.

. "State" means the state of Washington.

. "State ceiling" means the volume limitation for each calendar year on specific bond types, including tax-exempt private activity bonds and other bonds, as imposed by the code.

. "Student loans" means the bond use category which includes qualified student loan bonds as described in the code.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2753-S.SL.pdf?cite=2010%201st%20sp.s.%20c%206%20§%204[2010 1st sp.s. c 6 § 4]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2242.SL.pdf?cite=2009%20c%20565%20§%2023[2009 c 565 § 23]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1014.SL.pdf?cite=1995%20c%20399%20§%2057[1995 c 399 § 57]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c297.pdf?cite=1987%20c%20297%20§%202[1987 c 297 § 2]; ]

== 39.86.120 - Initial allocation.
. Except as provided in subsections (2) and (4) of this section, the initial allocation of the state ceiling shall be for each year as follows:

BOND USECATEGORY 2010 and THEREAFTERHousing 42.0%Small Issue 25.0%Exempt Facility 20.0%Student Loans 5.0%Public Utility 0.0%Remainder andRedevelopment 8.0%

BOND USE

CATEGORY

 

2010 and THEREAFTER

Housing

 

42.0%

Small Issue

 

25.0%

Exempt Facility

 

20.0%

Student Loans

 

5.0%

Public Utility

 

0.0%

Remainder and

Redevelopment

 

8.0%

. Initial allocations may be modified by the agency only to reflect an issuer's carryforward amount. Any reduction of the initial allocation shall be added to the remainder and be available for allocation or reallocation.

. The remainder shall be allocated by the agency among one or more issuers from any bond use category with regard to the criteria specified in RCW 39.86.130.

. Should any bond use category no longer be subject to the state ceiling due to federal or state provisions of law, the agency shall divide the amount of that initial allocation among the remaining categories as necessary or appropriate with regard to the criteria specified in RCW 39.86.130.

. [Empty]
.. Prior to July 1st of each calendar year, any available portion of an initial allocation may be allocated or reallocated only to an issuer within the same bond use category, except that the remainder category, or portions thereof, may be allocated at any time to any bond use category.

.. Beginning July 1st of each calendar year, the agency may allocate or reallocate any available portion of the state ceiling to any bond use category with regard to the criteria specified in RCW 39.86.130.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6342-S.SL.pdf?cite=2016%20sp.s.%20c%2018%20§%201[2016 sp.s. c 18 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2753-S.SL.pdf?cite=2010%201st%20sp.s.%20c%206%20§%206[2010 1st sp.s. c 6 § 6]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5197.SL.pdf?cite=2001%20c%20330%20§%202[2001 c 330 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c50.pdf?cite=1990%20c%2050%20§%201[1990 c 50 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c297.pdf?cite=1987%20c%20297%20§%203[1987 c 297 § 3]; ]

== 39.86.130 - Criteria.
. In granting an allocation, reallocation, or carryforward of the state ceiling as provided in this chapter, the agency shall consider existing state priorities and other such criteria, including but not limited to, the following criteria:

.. Need of issuers to issue bonds within a bond use category subject to a state ceiling;

.. Amount of the state ceiling available;

.. Public benefit and purpose to be satisfied, including economic development, educational opportunity, and public health, safety, or welfare;

.. Cost or availability of alternative methods of financing for the project or program; and

.. Certainty of using the allocation which is being requested.

. In determining whether to allocate an amount of the state ceiling to an issuer within any bond use category, the agency shall consider, but is not limited to, the following criteria for each of the bond use categories:

.. Housing: Criteria which comply with RCW 43.180.200.

.. Student loans: Criteria which comply with the applicable provisions of Title 28B RCW and rules adopted by the office of student financial assistance or applicable state agency dealing with student financial aid.

.. Small issue: Factors which may include:

... The number of employment opportunities the project is likely to create or retain in relation to the amount of the bond issuance;

... The level of unemployment existing in the geographic area likely to be affected by the project;

... A commitment to providing employment opportunities to low-income persons in cooperation with the employment security department;

... Geographic distribution of projects;

.. The number of persons who will benefit from the project;

.. Consistency with criteria identified in subsection (1) of this section; and

.. Order in which requests were received.

.. Exempt facility or redevelopment: Factors which may include:

... State issuance needs;

... Consistency with criteria identified in subsection (1) of this section;

... Order in which requests were received;

... The proportionate number of persons in relationship to the size of the community who will benefit from the project; and

.. The unique timing and issuance needs of large scale projects that may require allocations in more than one year.

.. Public utility: Factors which may include:

... Consistency with criteria identified in subsection (1) of this section; and

... Timing needs for issuance of bonds over a multi-year period.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5182-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2011%20§%20243[2011 1st sp.s. c 11 § 243]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2753-S.SL.pdf?cite=2010%201st%20sp.s.%20c%206%20§%207[2010 1st sp.s. c 6 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c297.pdf?cite=1987%20c%20297%20§%204[1987 c 297 § 4]; ]

== 39.86.140 - Procedure for obtaining state ceiling allocation.
. No issuer may receive an allocation of the state ceiling without a certificate of approval from the agency. The agency may not make an allocation of the state ceiling to an issuer formed or organized under the laws of another state.

. For each state ceiling allocation request, an issuer shall submit to the agency, no sooner than ninety days prior to the beginning of a calendar year for which an allocation of the state ceiling is being requested, a form identifying:

.. The amount of the allocation sought;

.. The bond use category from which the allocation sought would be made;

.. The project or program for which the allocation is requested;

.. The financing schedule for which the allocation is needed; and

.. Any other such information required by the agency, including information which corresponds to the allocation criteria of RCW 39.86.130.

. The agency may approve or deny an allocation for all or a portion of the issuer's request. Any denied request, however, shall remain on file with the agency for the remainder of the calendar year and shall be considered for receiving any allocation, reallocation, or carryforward of unused portions of the state ceiling during that period.

. After receiving an allocation request, the agency shall mail to the requesting issuer a written certificate of approval or notice of denial for an allocation amount, by a date no later than the latest of the following:

.. February 1st of the calendar year for which the request is made; or

.. Fifteen days from the date the agency receives an allocation request.

. [Empty]
.. For requests of the state ceiling of any calendar year, the following applies to all bond use categories except housing and student loans:

... Except for housing and student loans, any allocations granted prior to April 1st, for which bonds have not been issued by July 1st of the same calendar year, shall revert to the agency on July 1st of the same calendar year for reallocation unless an extension or carryforward is granted;

... Except for housing and student loans, any allocations granted on or after April 1st, for which bonds have not been issued by October 15th of the same calendar year, shall revert to the agency on October 15th of the same calendar year for reallocation unless an extension or carryforward is granted.

.. For each calendar year, any housing or student loan allocations, for which bonds have not been issued by December 15th of the same calendar year, shall revert to the agency on December 15th of the same calendar year for reallocation unless an extension or carryforward is granted.

.. In any calendar year for which no allocation for student loan bonds has been granted by February 1st of that year, the entire initial allocation for student loans may be reallocated to housing on February 1st of the same calendar year.

. An extension of the deadlines provided by subsection (5) of this section may be granted by the agency for the approved allocation amount or a portion thereof, based on:

.. Firm and convincing evidence that the bonds will be issued before the end of the calendar year if the extension is granted; and

.. Any other criteria the agency deems appropriate.

. If an issuer determines that bonds subject to the state ceiling will not be issued for the project or program for which an allocation was granted, the issuer shall promptly notify the agency in writing so that the allocation may be canceled and the amount may be available for reallocation.

. Bonds subject to the state ceiling may be issued only to finance the project or program for which a certificate of approval is granted.

. Within three business days of the date that bonds for which an allocation of the state ceiling is granted have been delivered to the original purchasers, the issuer shall mail to the agency a written notification of the bond issuance. In accordance with chapter 39.44 RCW, the issuer shall also complete bond issuance information on the form provided by the agency.

. If the total amount of bonds issued under the authority of a state ceiling for a project or program is less than the amount allocated, the remaining portion of the allocation shall revert to the agency for reallocation in accordance with the criteria in RCW 39.86.130. If the amount of bonds actually issued under the authority of a state ceiling is greater than the amount allocated, the entire allocation shall be disallowed.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6342-S.SL.pdf?cite=2016%20sp.s.%20c%2018%20§%202[2016 sp.s. c 18 § 2]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1761-S.SL.pdf?cite=2011%20c%20211%20§%203[2011 c 211 § 3]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2753-S.SL.pdf?cite=2010%201st%20sp.s.%20c%206%20§%208[2010 1st sp.s. c 6 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c297.pdf?cite=1987%20c%20297%20§%205[1987 c 297 § 5]; ]

== 39.86.150 - Reallocation process and carryforwards.
. Beginning July 1st of each calendar year, the agency may allocate or reallocate any portions of the annual state tax-exempt private activity bond ceiling for which no certificate of approval is in effect. Reallocations may also be made from the remainder category at any time during the year.

. Prior to the end of each calendar year, the agency shall allocate or reallocate any unused portions of the state ceiling among one or more issuers as carryforward, to be used within three years, in accordance with the code and relevant criteria described in RCW 39.86.130.

. Reallocations of state bond ceilings other than the annual tax-exempt private activity bond ceiling may be made by the agency in accordance with the code or as established in agency rule when not specified in the code.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2753-S.SL.pdf?cite=2010%201st%20sp.s.%20c%206%20§%209[2010 1st sp.s. c 6 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c297.pdf?cite=1987%20c%20297%20§%206[1987 c 297 § 6]; ]

== 39.86.155 - State bond ceiling allocation formula.
Original allocations or any reallocations of state bond ceilings other than the tax-exempt private activity bond ceiling must be determined by formula as provided in the code, or by department rule if no formula is provided in the code.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2753-S.SL.pdf?cite=2010%201st%20sp.s.%20c%206%20§%205[2010 1st sp.s. c 6 § 5]; ]

== 39.86.160 - Executive orders.
If federal legislation is enacted or federal regulations are promulgated which affect the state ceiling, when the legislature is not in session or is less than forty-five days from the constitutional end of session, the governor may establish by executive order an alternative system for the allocation of tax exempt bonds under the state ceiling, effective until the legislature acts. In allocating or reallocating under this section, the governor shall take into account the requirements of federal law, the policy choices expressed in state law, and the projected needs of issuers.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c297.pdf?cite=1987%20c%20297%20§%207[1987 c 297 § 7]; ]

== 39.86.170 - Fees.
A fee schedule shall be established by rule by the agency to assist in support of bond allocation activities. Fees shall reflect costs actually incurred or expected to be incurred by the agency in its bond allocation and bond users clearinghouse activities.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2753-S.SL.pdf?cite=2010%201st%20sp.s.%20c%206%20§%2010[2010 1st sp.s. c 6 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c297.pdf?cite=1987%20c%20297%20§%208[1987 c 297 § 8]; ]

== 39.86.180 - Code amendments.
In order to permit the full use of the authorized state ceiling under federal law, the agency may adopt rules approving any amendments made to the code after May 8, 1987.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c297.pdf?cite=1987%20c%20297%20§%209[1987 c 297 § 9]; ]

== 39.86.190 - Biennial reports.
Beginning in June 2018 and thereafter by June 30th of each even-numbered year, the agency shall submit a biennial report to the legislature summarizing usage of the bond allocation proceeds and any policy concerns for future bond allocations.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6342-S.SL.pdf?cite=2016%20sp.s.%20c%2018%20§%203[2016 sp.s. c 18 § 3]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2753-S.SL.pdf?cite=2010%201st%20sp.s.%20c%206%20§%2011[2010 1st sp.s. c 6 § 11]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2327-S.SL.pdf?cite=2009%20c%20518%20§%2019[2009 c 518 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c297.pdf?cite=1987%20c%20297%20§%2010[1987 c 297 § 10]; ]

== 39.86.905 - Captions.
As used in this chapter, captions constitute no part of the law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c297.pdf?cite=1987%20c%20297%20§%2015[1987 c 297 § 15]; ]

