= 39.106 - Joint municipal utility services.
:toc:

== 39.106.010 - Short title—Purpose—Intent—2011 c 258.
. Chapter 258, Laws of 2011 shall be known as the joint municipal utility services act.

. It is the purpose of chapter 258, Laws of 2011 to improve the ability of local government utilities to plan, finance, construct, acquire, maintain, operate, and provide facilities and utility services to the public, and to reduce costs and improve the benefits, efficiency, and quality of utility services.

. Chapter 258, Laws of 2011 is intended to facilitate joint municipal utility services and is not intended to expand the types of services provided by local governments or their utilities. Further, nothing in chapter 258, Laws of 2011 is intended to alter the regulatory powers of cities, counties, or other local governments or state agencies that exercise such powers. Further, nothing in chapter 258, Laws of 2011 may be construed to alter the underlying authority of the units of local government that enter into agreements under chapter 258, Laws of 2011 or to diminish in any way the authority of local governments to enter into agreements under chapter 39.34 RCW or other applicable law.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1332-S.SL.pdf?cite=2011%20c%20258%20§%201[2011 c 258 § 1]; ]

== 39.106.020 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Agreement" means a joint municipal utility services agreement, among members, that forms an authority, as more fully described in this chapter.

. "Authority" means a joint municipal utility services authority formed under this chapter.

. "Board of directors" or "board" means the board of directors of an authority.

. "Member" means a city, town, county, water-sewer district, public utility district, other special purpose district, municipal corporation, or other unit of local government of this or another state that provides utility services, and any Indian tribe recognized as such by the United States government, that is a party to an agreement forming an authority.

. "Utility services," for purposes of this chapter, means any or all of the following functions: The provision of retail or wholesale water supply and water conservation services; the provision of wastewater, sewage, or septage collection, handling, treatment, transmission, or disposal services; the provision of point and nonpoint water pollution monitoring programs; the provision for the generation, production, storage, distribution, use, or management of reclaimed water; and the management and handling of stormwater, surface water, drainage, and flood waters.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1332-S.SL.pdf?cite=2011%20c%20258%20§%202[2011 c 258 § 2]; ]

== 39.106.030 - Formation of authorities—Characteristics—Substantive powers.
. An authority may be formed by two or more members pursuant to this chapter by execution of a joint municipal utility services agreement that materially complies with the requirements of RCW 39.106.050. Except as otherwise provided in RCW 39.106.080, at the time of execution of an agreement each member must be providing the type of utility service or services that will be provided by the authority. The agreement must be approved by the legislative authority of each of the members. The agreement must be filed with the Washington state secretary of state, who must provide a certificate of filing with respect to any authority. An authority shall be deemed to have been formed as of the date of that filing. The formation and activities of an authority, and the admission or withdrawal of members, are not subject to review by any boundary review board. Any amendments to an agreement must be filed with the Washington state secretary of state, and will become effective on the date of filing.

. An authority is a municipal corporation. Subject to RCW 39.106.040(3), the provisions of a joint municipal utility services agreement, and any limitations imposed pursuant to RCW 39.106.050: (a) An authority may perform or provide any or all of the utility service or services that all of its members, other than tribal government members, perform or provide under applicable law; and (b) in performing or providing those utility services, an authority may exercise any or all of the powers described in RCW 39.106.040(1).

. An authority shall be entitled to all the immunities and exemptions that are available to local governmental entities under applicable law, including without limitation the provisions of chapter 4.96 RCW. Notwithstanding this subsection (3), if all of an authority's members are the same type of Washington local government entity, then the immunities and exemptions available to that type of entity shall govern.

. Nothing in this chapter shall diminish a member's powers in connection with its provision or management of utility services, or its taxing power with respect to those services, nor does this chapter diminish in any way the authority of local governments to enter into agreements under chapter 39.34 RCW or other applicable law.

. Nothing in this chapter shall impair or diminish a valid water right, including rights established under state law and rights established under federal law.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1332-S.SL.pdf?cite=2011%20c%20258%20§%203[2011 c 258 § 3]; ]

== 39.106.040 - Corporate powers of authorities.
. For the purpose of performing or providing utility services, and subject to subsection (3) of this section and RCW 39.106.050, an authority has and is entitled to exercise the following powers:

.. To sue and be sued, complain and defend, in its corporate name;

.. To have a corporate seal which may be altered at pleasure, and to use the same by causing it, or a facsimile thereof, to be impressed or affixed or in any other manner reproduced;

.. To purchase, take, receive, take by lease, condemn, receive by grant, or otherwise acquire, and to own, hold, improve, use, operate, maintain, add to, extend, and fully control the use of and otherwise deal in and with, real or personal property or property rights, including without limitation water and water rights, or other assets, or any interest therein, wherever situated;

.. To sell, convey, lease out, exchange, transfer, surplus, and otherwise dispose of all or any part of its property and assets;

.. To incur liabilities for any of its utility services purposes, to borrow money at such rates of interest as the authority may determine, to issue its bonds, notes, and other obligations, and to pledge any or all of its revenues to the repayment of bonds, notes, and other obligations;

.. To enter into contracts for any of its utility services purposes with any individual or entity, both public and private, and to enter into intergovernmental agreements with its members and with other public agencies;

.. To be eligible to apply for and to receive state, federal, and private grants, loans, and assistance that any of its members are eligible to receive in connection with the development, design, acquisition, construction, maintenance, and/or operation of facilities and programs for utility services;

.. To adopt and alter rules, policies, and guidelines, not inconsistent with this chapter or with other laws of this state, for the administration and regulation of the affairs and assets of the authority;

.. To obtain insurance, to self-insure, and to participate in pool insurance programs;

.. To indemnify any officer, director, employee, volunteer, or former officer, employee, or volunteer, or any member, for acts, errors, or omissions performed in the exercise of their duties in the manner approved by the board;

.. To employ such persons, as public employees, that the board determines are needed to carry out the authority's purposes and to fix wages, salaries, and benefits, and to establish any bond requirements for those employees;

.. To provide for and pay pensions and participate in pension plans and other benefit plans for any or all of its officers or employees, as public employees;

.. To determine and impose fees, rates, and charges for its utility services;

.. Subject to RCW 39.106.050(20), to have a lien for delinquent and unpaid rates and charges for retail connections and retail utility service to the public, together with recording fees and penalties (not exceeding eight percent) determined by the board, including interest (at a rate determined by the board) on such rates, charges, fees, and penalties, against the premises to which such service has been furnished or is available, which lien shall be superior to all other liens and encumbrances except general taxes and local and special assessments;

.. To make expenditures to promote and advertise its programs, educate its members, customers, and the general public, and provide and support conservation and other practices in connection with providing utility services;

.. With the consent of the member within whose geographic boundaries an authority is so acting, to compel all property owners within an area served by a wastewater collection system owned or operated by an authority to connect their private drain and sewer systems with that system, or to participate in and follow the requirements of an inspection and maintenance program for on-site systems, and to pay associated rates and charges, under such terms and conditions, and such penalties, as the board shall prescribe by resolution;

.. With the consent of the member within whose geographic or service area boundaries an authority is so acting, to create local improvement districts or utility local improvement districts, to impose and collect assessments and to issue bonds and notes, all consistent with the statutes governing local improvement districts or utility local improvement districts applicable to the member that has provided such consent. Notwithstanding this subsection (1)(q), the guaranty fund provisions of chapter 35.54 RCW shall not apply to a local improvement district created by an authority;

.. To receive contributions or other transfers of real and personal property and property rights, money, other assets, and franchise rights, wherever situated, from its members or from any other person;

.. To prepare and submit plans relating to utility services on behalf of itself or its members;

.. To terminate its operations, wind up its affairs, dissolve, and provide for the handling and distribution of its assets and liabilities in a manner consistent with the applicable agreement;

.. To transfer its assets, rights, obligations, and liabilities to a successor entity, including without limitation a successor authority or municipal corporation;

.. Subject to subsection (3) of this section, RCW 39.106.050, and applicable law, to have and exercise any other corporate powers capable of being exercised by any of its members in providing utility services.

. An authority, as a municipal corporation, is subject to the public records act (chapter 42.56 RCW), the open public meetings act (chapter 42.30 RCW), and the code of ethics for municipal officers (chapter 42.23 RCW), and an authority is subject to audit by the state auditor under chapter 43.09 RCW.

. In the exercise of its powers in connection with performing or providing utility services, an authority is subject to the following:

.. An authority has no power to levy taxes.

.. An authority has the power of eminent domain as necessary to perform or provide utility services, but only if all of its members, other than tribal government members, have powers of eminent domain. Further, an authority may exercise the power of eminent domain only pursuant to the provisions of Washington law, in the manner and subject to the statutory limitations applicable to one or more of its Washington local government members. If all of its members are the same type of Washington governmental entity, then the statute governing the exercise of eminent domain by that type of entity shall govern. An authority may not exercise the power of eminent domain with respect to property owned by a city, town, county, special purpose district, authority, or other unit of local government, but may acquire or use such property under mutually agreed upon terms and conditions.

.. An authority may pledge its revenues in connection with its obligations, and may acquire property or property rights through and subject to the terms of a conditional sales contract, a real estate contract, or a financing contract under chapter 39.94 RCW, or other federal or state financing program. However, an authority must not in any other manner mortgage or provide security interests in its real or personal property or property rights. As a local governmental entity without taxing power, an authority may not issue general obligation bonds. However, an authority may pledge its full faith and credit to the payment of amounts due pursuant to a financing contract under chapter 39.94 RCW or other federal or state financing program.

.. In order for an authority to provide a particular utility service in a geographical area, one or more of its members must have authority, under applicable law, to provide that utility service in that geographical area.

.. As a separate municipal corporation, an authority's obligations and liabilities are its own and are not obligations or liabilities of its members except to the extent and in the manner established under the provisions of an agreement or otherwise expressly provided by contract.

.. Upon its dissolution, after provision is made for an authority's liabilities, remaining assets must be distributed to a successor entity, or to one or more of the members, or to another public body of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1332-S.SL.pdf?cite=2011%20c%20258%20§%204[2011 c 258 § 4]; ]

== 39.106.050 - Elements of joint municipal utility services agreements.
A joint municipal utility services agreement that forms and governs an authority must include the elements described in this section, together with such other provisions an authority's members deem appropriate. However, the failure of an agreement to include each and every one of the elements described in this section shall not render the agreement invalid. An agreement must:

. Identify the members, together with conditions upon which additional members that are providing utility services may join the authority, the conditions upon which members may or must withdraw, including provisions for handling of relevant assets and liabilities upon a withdrawal, and the effect of boundary adjustments of the authority and boundary adjustments between or among members;

. State the name of the authority;

. Describe the utility services that the authority will provide;

. Specify how the number of directors of the authority's board will be determined, and how those directors will be appointed. Each director on the board of an authority must be an elected official of a member. Except as limited by an agreement, an authority's board may exercise the authority's powers;

. Describe how votes of the members represented on the authority's board are to be weighted, and set forth any limitations on the exercise of powers of the authority's board, which may include, by way of example, requirements that certain decisions be made by a supermajority of members represented on an authority's board, based on the number of members and/or some other factor or factors, and that certain decisions be ratified by the legislative authorities of the members;

. Describe how the agreement is to be amended;

. Describe how the authority's rules may be adopted and amended;

. Specify the circumstances under which the authority may be dissolved, and how it may terminate its operations, wind up its affairs, and provide for the handling, assumption, and/or distribution of its assets and liabilities;

. List any legally authorized substantive or corporate powers that the authority will not exercise;

. Specify under which personnel laws the authority will operate, which may be the personnel laws applicable to any one of its Washington local government members;

. Specify under which public works and procurement laws the authority will operate, which may be the public works and procurement laws applicable to any one of its Washington local government members;

. Consistent with RCW 39.106.040(3)(b), specify under which Washington eminent domain laws any condemnations by the authority will be subject;

. Specify how the treasurer of the authority will be appointed, which may be an officer or employee of the authority, the treasurer or chief finance officer of any Washington local government member, or the treasurer of any Washington county in which any member of the authority is located. However, if the total number of utility customers of all of the members of an authority does not exceed two thousand five hundred, the treasurer of an authority must be either the treasurer of any member or the treasurer of a county in which any member of the authority is located;

. Specify under which Washington state statute or statutes surplus property of the authority will be disposed;

. Describe how the authority's budgets will be prepared and adopted;

. Describe how any assets of members that are transferred to or managed by the authority will be accounted for;

. Generally describe the financial obligations of members to the authority;

. Describe how rates and charges imposed by the authority, if any, will be determined. An agreement may specify a specific Washington state statute applicable to one or all of its members for the purpose of governing rate-setting criteria applicable to retail customers, if any;

. Specify the Washington state statute or statutes under which bonds, notes, and other obligations of the authority will be issued for the purpose of performing or providing utility services, which must be a bond issuance statute applicable to one or more of its members other than a tribal member. If all of its members are the same type of Washington governmental entity, then a Washington state statute or statutes governing the issuance of bonds, notes, and other obligations issued by that type of entity shall govern;

. Specify under which Washington state statute or statutes any liens of an authority shall be exercised, which must be statutes applicable to the type or types of utility service for which the lien shall apply. Further, if all of its members are the same type of Washington governmental entity, then the statute or statutes governing that type of entity shall govern;

. Include any other provisions deemed necessary and appropriate by the members.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1332-S.SL.pdf?cite=2011%20c%20258%20§%205[2011 c 258 § 5]; ]

== 39.106.060 - Authority of members to assist authority and to transfer funds, property, and other assets.
For the purpose of assisting the authority in providing utility services, the members of an authority are authorized, with or without payment or other consideration and without submitting the matter to the electors of those members, to lease, convey, transfer, assign, or otherwise make available to an authority any money, real or personal property or property rights, other assets including licenses, water rights (subject to applicable law), other property (whether held by a member's utility or by a member's general government), or franchises or rights thereunder.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1332-S.SL.pdf?cite=2011%20c%20258%20§%206[2011 c 258 § 6]; ]

== 39.106.070 - Tax exemptions and preferences.
. As a municipal corporation, the property of an authority is exempt from taxation.

. An authority is entitled to all of the exemptions from or preferences with respect to taxes that are available to any or all of its members, other than a tribal member, in connection with the provision or management of utility services.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1332-S.SL.pdf?cite=2011%20c%20258%20§%207[2011 c 258 § 7]; ]

== 39.106.080 - Conversion of existing entities into authorities.
. Any intergovernmental entity formed under chapter 39.34 RCW or other applicable law may become a joint municipal utility services authority and be entitled to all the powers and privileges available under this chapter, if: (a) The public agencies that are parties to an existing interlocal agreement would otherwise be eligible to form an authority to provide the relevant utility services; (b) the public agencies that are parties to the existing interlocal agreement amend, restate, or replace that interlocal agreement so that it materially complies with the requirements of RCW 39.106.050; (c) the amended, restated, or replacement agreement is filed with the Washington state secretary of state consistent with RCW 39.106.030; and (d) the amended, restated, or replacement agreement expressly provides that all rights and obligations of the entity formerly existing under chapter 39.34 RCW or other applicable law shall thereafter be the obligations of the new authority created under this chapter. Upon compliance with those requirements, the new authority shall be a successor of the former intergovernmental entity for all purposes, and all rights and obligations of the former entity shall transfer to the new authority. Those obligations shall be treated as having been incurred, entered into, or issued by the new authority, and those obligations shall remain in full force and effect and shall continue to be enforceable in accordance with their terms.

. If an interlocal agreement under chapter 39.34 RCW or other applicable law relating to utility services includes among its original participants a city or county that does not itself provide or no longer provides utility services, that city or county may continue as a party to the amended, restated, or replacement agreement and shall be treated as a member for all purposes under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1332-S.SL.pdf?cite=2011%20c%20258%20§%208[2011 c 258 § 8]; ]

== 39.106.090 - Powers conferred by chapter are supplemental.
The powers and authority conferred by this chapter shall be construed as in addition and supplemental to powers or authority conferred by any other law, and nothing contained in this chapter shall be construed as limiting any other powers or authority of any member or any other entity formed under chapter 39.34 RCW or other applicable law.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1332-S.SL.pdf?cite=2011%20c%20258%20§%209[2011 c 258 § 9]; ]

