= 40.06 - State publications distribution center.
:toc:

== 40.06.010 - Definitions.
As used in this chapter:

. "Electronic repository" means a collection of publicly accessible electronic publications stored in a secure digital environment with redundant backup to preserve the collection.

. "Format" includes any media used in the publication of state information including electronic, print, audio, visual, and microfilm.

. "State agency" includes every state office, officer, department, division, bureau, board, commission and agency of the state, and, where applicable, all subdivisions of each.

. "State publication" means information published by state agencies, regardless of format, intended for distribution to state government or the public. Examples may include annual, biennial, and special reports required by law, state agency newsletters, periodicals, and magazines, and other informational material intended for general dissemination to state agencies, the public, or the legislature.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2155-S.SL.pdf?cite=2006%20c%20199%20§%203[2006 c 199 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c232.pdf?cite=1977%20ex.s.%20c%20232%20§%208[1977 ex.s. c 232 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c233.pdf?cite=1963%20c%20233%20§%201[1963 c 233 § 1]; ]

== 40.06.020 - Center created as division of state library—Depository library system—Rules.
There is hereby created as a division of the state library, and under the direction of the state librarian, a state publications distribution center. The center shall utilize the depository library system to permit citizens economical and convenient access to state publications, regardless of format. To this end the secretary of state shall make such rules as may be deemed necessary to carry out the provisions of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2155-S.SL.pdf?cite=2006%20c%20199%20§%204[2006 c 199 § 4]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2926-S.SL.pdf?cite=2002%20c%20342%20§%205[2002 c 342 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c232.pdf?cite=1977%20ex.s.%20c%20232%20§%209[1977 ex.s. c 232 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c233.pdf?cite=1963%20c%20233%20§%202[1963 c 233 § 2]; ]

== 40.06.030 - Deposits by state agencies—Exemptions.
. Every state agency shall promptly submit to the state library copies of published information that are state publications.

.. For state publications available only in print format, each state agency shall deposit, at a minimum, two copies of each of its publications with the state library. For the purposes of broad public access, state agencies may deposit additional copies with the state library for distribution to additional depository libraries.

.. For state publications available only in electronic format, each state agency shall deposit one copy of each of its publications with the state library.

.. For state publications available in both print and electronic format, each state agency shall deposit two print copies and one electronic copy of the publication with the state library.

. Annually, each state agency shall provide the state library with a listing of all its publications made available to state government and the public during the preceding year, including those published in electronic form. The secretary of state shall, by rule, establish the annual date by which state agencies must provide the list of its publications to the state library.

. In the interest of economy and efficiency, the state librarian may specifically or by general rule exempt a given state publication or class of publications from the requirements of this section in full or in part.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5931-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2043%20§%20304[2011 1st sp.s. c 43 § 304]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2155-S.SL.pdf?cite=2006%20c%20199%20§%205[2006 c 199 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c232.pdf?cite=1977%20ex.s.%20c%20232%20§%2010[1977 ex.s. c 232 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c233.pdf?cite=1963%20c%20233%20§%203[1963 c 233 § 3]; ]

== 40.06.040 - Interlibrary depository contracts—Repository of electronic publications.
. To provide economical public access to state publications, the center may enter into depository contracts with any free public library, The Evergreen State College, regional university, or state university library, or, if needed, the library of any privately incorporated college or university in this state. The requirements for eligibility to contract as a depository library shall be established by the secretary of state upon recommendations of the state librarian. The standards shall include and take into consideration the type of library, available housing and space for the publications, the number and qualifications of personnel, and availability for public use. The center may also contract with public, out-of-state libraries for the exchange of state and other publications on a reciprocal basis. Any state publication to be distributed to the public and the legislature shall be mailed at the lowest available postal rate.

. The office of the secretary of state through the state librarian shall preserve and make accessible state agency electronic publications deposited with the state library through an electronic repository.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2155-S.SL.pdf?cite=2006%20c%20199%20§%206[2006 c 199 § 6]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2926-S.SL.pdf?cite=2002%20c%20342%20§%206[2002 c 342 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c260.pdf?cite=1981%20c%20260%20§%208[1981 c 260 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c232.pdf?cite=1977%20ex.s.%20c%20232%20§%2011[1977 ex.s. c 232 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c169.pdf?cite=1977%20ex.s.%20c%20169%20§%2096[1977 ex.s. c 169 § 96]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c233.pdf?cite=1963%20c%20233%20§%204[1963 c 233 § 4]; ]

== 40.06.050 - Center to publish list of publications and other descriptive matter.
The center shall publish and distribute regularly a list of available state publications, and may publish and distribute such other descriptive matter as will facilitate the distribution of and access to state publications.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2155-S.SL.pdf?cite=2006%20c%20199%20§%207[2006 c 199 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c233.pdf?cite=1963%20c%20233%20§%205[1963 c 233 § 5]; ]

== 40.06.060 - Agencies to furnish lists to center.
Upon request by the center, issuing state agencies shall furnish the center with a complete list of its current state publications and a copy of its mailing and/or exchange lists.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c233.pdf?cite=1963%20c%20233%20§%206[1963 c 233 § 6]; ]

== 40.06.070 - Exemptions.
This chapter shall not apply to nor affect the duties concerning publications distributed by, or officers of:

. The state law library; and

. The statute law committee and the code reviser.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c3.pdf?cite=1983%20c%203%20§%2083[1983 c 3 § 83]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c233.pdf?cite=1963%20c%20233%20§%207[1963 c 233 § 7]; ]

== 40.06.900 - Effective date—1963 c 233.
The effective date of this chapter shall be July 1, 1963.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c233.pdf?cite=1963%20c%20233%20§%208[1963 c 233 § 8]; ]

