= 40.10 - Microfilming of records to provide continuity of civil government.
:toc:

== 40.10.010 - Essential records—Designation—List—Security and protection—Reproduction.
In order to provide for the continuity and preservation of civil government, each elected and appointed officer of the state shall designate those public documents which are essential records of his or her office and needed in an emergency and for the reestablishment of normal operations after any such emergency. A list of such records shall be forwarded to the state archivist on forms prescribed by the state archivist. This list shall be reviewed at least annually by the elected or appointed officer to insure its completeness. Any changes or revisions following this review shall be forwarded to the state archivist. Each such elected and appointed officer of state government shall insure that the security of essential records of his or her office is by the most economical means commensurate with adequate protection. Protection of essential records may be by vaulting, planned or natural dispersal of copies, or any other method approved by the state archivist. Reproductions of essential records may be by photo copy, magnetic tape, microfilm, or other method approved by the state archivist. Local government offices may coordinate the protection of their essential records with the state archivist as necessary to provide continuity of local government under emergency conditions.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20816[2011 c 336 § 816]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c36.pdf?cite=1982%20c%2036%20§%201[1982 c 36 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c54.pdf?cite=1973%20c%2054%20§%201[1973 c 54 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c241.pdf?cite=1963%20c%20241%20§%201[1963 c 241 § 1]; ]

== 40.10.020 - Essential records—Reproduction and storage—Coordination of protection program—Fees.
The state archivist is authorized to reproduce those documents designated as essential records by the several elected and appointed officials of the state and local government by microfilm or other miniature photographic process and to assist and cooperate in the storage and safeguarding of such reproductions in such place as is recommended by the state archivist with the advice of the *director of community, trade, and economic development. The state archivist shall coordinate the essential records protection program and shall carry out the provisions of the state emergency plan as they relate to the preservation of essential records. The state archivist is authorized to charge the several departments of the state and local government the actual cost incurred in reproducing, storing and safeguarding such documents: PROVIDED, That nothing herein shall authorize the destruction of the originals of such documents after reproduction thereof.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1014.SL.pdf?cite=1995%20c%20399%20§%2058[1995 c 399 § 58]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2045[1986 c 266 § 45]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%20106[1985 c 7 § 106]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c36.pdf?cite=1982%20c%2036%20§%202[1982 c 36 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c54.pdf?cite=1973%20c%2054%20§%202[1973 c 54 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c241.pdf?cite=1963%20c%20241%20§%202[1963 c 241 § 2]; ]

