= 40.26 - Biometric identifiers.
:toc:

== 40.26.010 - Finding.
The legislature finds that the collection and use of personal information has been a practice of virtually all state agencies and programs. Advances in technology have given rise to new forms of data, such as email and internet protocol (IP) addresses, which can be easily collected and stored along with traditional types of data such as names and dates of birth. One new form of personally identifiable information is biometric identifiers. The unique nature of this new type of personal data calls for additional guidance regarding its use by state agencies.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1717-S.SL.pdf?cite=2017%20c%20306%20§%201[2017 c 306 § 1]; ]

== 40.26.020 - Biometric identifiers—Notice and consent—Agencies—Use, storage, retention—Review—Definitions—Exceptions.
. Unless authorized by law, an agency may not collect, capture, purchase, or otherwise obtain a biometric identifier without first providing notice and obtaining the individual's consent, as follows:

.. The notice provided must clearly specify the purpose and use of the biometric identifier; and

.. The consent obtained must be specific to the terms of the notice, and must be recorded and maintained by the agency for the duration of the retention of the biometric identifier.

. Any biometric identifier obtained by an agency:

.. May not be sold;

.. May only be used consistent with the terms of the notice and consent obtained under subsection (1) of this section, or as authorized by law; and

.. May be shared, including with other state agencies or local governments, only:

... As needed to execute the purposes of the collection, consistent with the notice and consent obtained under subsection (1) of this section, or as authorized by law; or

... If such sharing is specified within the original consent.

. An agency that collects, purchases, or otherwise obtains biometric identifiers must:

.. Establish security policies that ensure the integrity and appropriate confidentiality of the biometric identifiers;

.. Address biometric identifiers in the agency's privacy policies;

.. Only retain biometric identifiers necessary to fulfill the original purpose and use, as specified in the notice and consent obtained under subsection (1) of this section, or as authorized by law;

.. Set record retention schedules tailored to the original purpose of the collection of biometric identifiers;

.. Otherwise minimize the review and retention of the biometric identifiers, consistent with state record retention requirements; and

.. Design a biometric policy to ensure that the agency is minimizing the collection of biometric identifiers to the fewest number necessary to accomplish the agency mission.

. The use and storage of biometric identifiers obtained by an agency must comply with all other applicable state and federal laws and regulations, including the health insurance portability and accountability act (HIPAA), the family educational rights and privacy act (FERPA), regulations regarding data breach notifications and individual privacy protections, and any policies or standards published by the office of the chief information officer.

. Biometric identifiers may not be disclosed under the public records act, chapter 42.56 RCW.

. Agency policies, regulations, guidance, and retention schedules regarding biometric identifiers must be reviewed annually to incorporate any new technology, as appropriate, and respond to citizen complaints.

. The definitions in this subsection apply throughout this section unless the context requires otherwise.

.. "Agency" means every state office, department, division, bureau, board, commission, or other state agency.

.. "Biometric identifier" means any information, regardless of how it is captured, converted, stored, or shared, based on an individual's retina or iris scan, fingerprint, voiceprint, DNA, or scan of hand or face geometry, except when such information is derived from:

... Writing samples, written signatures, photographs, human biological samples used for valid scientific testing or screening, demographic data, tattoo descriptions, or physical descriptions such as height, weight, hair color, or eye color;

... Donated organ tissues or parts, or blood or serum stored on behalf of recipients or potential recipients of living or cadaveric transplants and obtained or stored by a federally designated organ procurement agency;

... Information captured from a patient in a health care setting or information collected, used, or stored for health care treatment, payment, or operations under the federal health insurance portability and accountability act of 1996; or

... X-ray, roentgen process, computed tomography, magnetic resonance imaging (MRI), positron emission tomography (PET) scan, mammography, or other image or film of the human anatomy used to diagnose, develop a prognosis for, or treat an illness or other medical condition or to further validate scientific testing or screening.

. Subsection (1) of this section does not apply to general authority Washington law enforcement agencies, as defined under RCW 10.93.020.

. [Empty]
.. For purposes of the restrictions and obligations in subsection (1) of this section, "biometric identifier" does not include fingerprints or DNA for the following:

... Limited authority Washington law enforcement agencies, as defined under RCW 10.93.020;

... Agencies authorized by statute to confine a person involuntarily, or to petition for such confinement; and

... The attorney general's office when obtaining or using biometric identifiers is necessary for law enforcement, legal advice, or legal representation.

.. When an agency listed under (a) of this subsection has a need to collect, capture, purchase, or otherwise obtain a biometric identifier other than a fingerprint or DNA to fulfill a purpose authorized by law, for either an individual circumstance or a categorical circumstance, the requirements of subsection (1) of this section are waived upon such agency providing prompt written notice to the state's chief privacy officer and to the appropriate committees of the legislature, stating the type of biometric identifier at issue and the general circumstances requiring the waiver.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2213.SL.pdf?cite=2017%202nd%20sp.s.%20c%201%20§%201[2017 2nd sp.s. c 1 § 1]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1717-S.SL.pdf?cite=2017%20c%20306%20§%202[2017 c 306 § 2]; ]

