= 40.20 - Reproduced records for governments and business.
:toc:

== 40.20.010 - "Business" defined.
For the purpose of this chapter, the term "business" shall mean and include business, industry, profession, occupation and calling of every kind.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c223.pdf?cite=1949%20c%20223%20§%203[1949 c 223 § 3]; Rem. Supp. 1949 § 1257-6; ]

== 40.20.020 - Reproduction by film or photograph.
The head of any business or the head of any state, county or municipal department, commission, bureau or board may cause any or all records required or authorized by law to be made or kept by such official, department, commission, bureau, board, or business to be photographed, microphotographed, reproduced on film, or photocopied for all purposes of recording documents, plats, files or papers, or copying or reproducing such records. Such film or reproducing material shall be of permanent material and the device used to reproduce such records on such film or material shall be such as to accurately reproduce and perpetuate the original records in all details, and shall be approved for the intended purpose: PROVIDED, That the state archivist shall approve such material for state records use: PROVIDED, FURTHER, That the state auditor shall approve such material for use by local governmental subdivisions.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c32.pdf?cite=1981%20c%2032%20§%205[1981 c 32 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c95.pdf?cite=1973%20c%2095%20§%201[1973 c 95 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c223.pdf?cite=1949%20c%20223%20§%201[1949 c 223 § 1]; Rem. Supp. 1949 § 1257-4; ]

== 40.20.030 - Use as original.
Such photostatic copy, photograph, microphotograph or photographic film record, or copy of the original records shall be deemed to be an original record for all purposes, and shall be admissible in evidence in all courts or administrative agencies. A facsimile, exemplification or certified copy thereof shall, for all purposes recited herein, be deemed to be a transcript, exemplification or certified copy of the original.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c223.pdf?cite=1949%20c%20223%20§%202[1949 c 223 § 2]; Rem. Supp. 1949 § 1257-5; ]

