= 37.08 - Jurisdiction in special cases.
:toc:

== 37.08.200 - Rainier National Park.
Exclusive jurisdiction shall be, and the same is hereby ceded to the United States over and within all the territory that is now or may hereafter be included in that tract of land in the state of Washington, set aside for the purposes of a national park, and known as the Rainier National Park; saving, however, to the said state, the right to serve civil or criminal process within the limits of the aforesaid park, in suits or prosecutions for or on account of rights acquired, obligations incurred or crimes committed in said state, but outside of said park; and saving further to the said state the right to tax persons and corporations, their franchises and property on the lands included in said park: PROVIDED, HOWEVER, This jurisdiction shall not vest until the United States through the proper officer, notifies the governor of this state that they assume police or military jurisdiction over said park.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1901c92.pdf?cite=1901%20c%2092%20§%201[1901 c 92 § 1]; RRS § 8110; ]

== 37.08.210 - Olympic National Park.
Exclusive jurisdiction shall be, and the same is hereby ceded to the United States over and within all the territory that is now or hereafter included in that tract of land in the state of Washington, set aside for the purposes of a national park, and known as the Olympic National Park; saving, however, to the said state, the right to serve civil and criminal process within the limits of the aforesaid park, in suits or prosecutions for or on account of rights acquired, obligations incurred or crimes committed in said state, but outside of said park; and saving further to the said state the right to tax persons and corporations, their franchises and property on the lands included in said park: PROVIDED, HOWEVER, This jurisdiction shall not vest until the United States, through the proper officer, notifies the governor of this state that they assume police or military jurisdiction over said park: AND PROVIDED FURTHER, That full jurisdiction over a strip of land two hundred fifty feet wide, being one hundred twenty-five feet wide on each side of the now existing center line of primary state highway No. 9 together with existing pit sites and stockpile sites within said park shall be retained by the state of Washington.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c114.pdf?cite=1945%20c%20114%20§%201[1945 c 114 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c51.pdf?cite=1941%20c%2051%20§%201[1941 c 51 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c170.pdf?cite=1939%20c%20170%20§%201[1939 c 170 § 1]; Rem. Supp. 1945 § 8110-1; ]

== 37.08.220 - National forests, establishment, consolidation, extension of.
The legislature of the state of Washington hereby consents to the acquisition by the United States by purchase or gift of such lands in the state of Washington as in the opinion of the government of the United States may be needed for the establishment, consolidation and extension of national forests in this state under the provisions of the act of congress approved March 1, 1911, and entitled: "An act to enable any state to cooperate with any other state or states or with the United States for the protection of the watersheds of navigable streams and to appoint a commission for the acquisition of lands for the purpose of conserving the navigability of navigable rivers," as amended: PROVIDED, The state of Washington shall retain a concurrent jurisdiction with the United States in and over lands so acquired so far that civil processes in all cases, and such criminal processes as may issue under the authority of the state of Washington against any person charged with the commission of any crime without or within said jurisdiction, may be executed thereon in like manner as if this consent had not been granted: PROVIDED FURTHER, That before any acquirement of lands be made under the provisions of this section, such acquisition shall be approved by the department of natural resources: AND FURTHER PROVIDED, That the state of Washington shall retain concurrent jurisdiction to tax persons and corporations and their property and transaction on such lands so acquired.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c128.pdf?cite=1988%20c%20128%20§%208[1988 c 128 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c58.pdf?cite=1935%20c%2058%20§%201[1935 c 58 § 1]; RRS § 9663-23; ]

== 37.08.230 - Migratory bird preserves.
Consent of the state of Washington is given to the acquisition by the United States by purchase, gift, devise, or lease of such areas of land or water, or of land and water, in the state of Washington, as the United States may deem necessary for the establishment of migratory-bird reservations in accordance with the act of congress approved February 18, 1929, entitled "An Act to more effectively meet the obligations of the United States under the migratory bird treaty with Great Britain by lessening the dangers threatening migratory game birds from drainage and other causes by the acquisition of areas of land and of water to furnish in perpetuity reservations for the adequate protection of such birds; and authorizing appropriations for the establishment of such areas, their maintenance and improvement and for other purposes," reserving, however, to the state of Washington full and complete jurisdiction and authority over all such areas not incompatible with the administration, maintenance, protection, and control thereof by the United States under the terms of said act of congress.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c159.pdf?cite=1933%20c%20159%20§%201[1933 c 159 § 1]; no RRS; ]

== 37.08.240 - Lake Washington ship canal.
That in aid of the construction, maintenance and operation of a ship canal, by the United States of America, to connect the waters of Lakes Union and Washington, in King county, with Puget Sound, together with all necessary and convenient locks, landways, spillways, buildings, power plant and other proper appurtenances, there be and hereby is granted by this state to said United States the right to place, construct, maintain, and operate, such ship canal, landways, spillways, buildings, power plant and other proper appurtenances, upon, along, through and over any and all lands belonging to and waters of this state in said King county, within such limits as shall be defined by the plans and specifications for such improvement as the same shall be approved by the United States secretary of war, and the right to raise the waters of Salmon Bay and the right to lower the waters of Lake Washington, in prosecution of such improvement, and this state hereby releases the United States from all liability to damages to this state, its successors or assigns, that shall or might arise from such lowering or raising of waters, or otherwise from such improvement. But nothing in this section contained shall operate as an assumption of nor create any liability on the part of the state, for any damages which may result to any person, company or corporation.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1901c6.pdf?cite=1901%20c%206%20§%201[1901 c 6 § 1]; RRS § 8120; ]

== 37.08.250 - Additional right-of-way.
That a right-of-way of not exceeding five hundred feet in width is hereby granted to the United States of America through any lands or shorelands belonging to the state of Washington, or to the University of Washington, and lying in King county between Lakes Union and Washington, or in or adjoining either of them, the southern boundary of such right-of-way on the upland to be coincident with the southern boundary of the lands now occupied by the University of Washington adjacent to the present right-of-way of said canal; the width and definite location of such right-of-way before the same is taken possession of by said United States shall be plainly and completely platted and a plat thereof approved by the secretary of war of the United States filed with the department of natural resources: PROVIDED, That nothing in this section contained shall be construed to repeal or impair any right, interest, privilege or grant expressed or intended in the act of the legislature of the state of Washington approved February 8, 1901, entitled, "An Act relative to and in aid of the construction, maintenance and operation by the United States of America of a ship canal with proper locks and appurtenances to connect the waters of Lakes Union and Washington in King county with Puget Sound and declaring an emergency."

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c128.pdf?cite=1988%20c%20128%20§%209[1988 c 128 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c216.pdf?cite=1907%20c%20216%20§%201[1907 c 216 § 1]; RRS § 8121; ]

== 37.08.260 - Auburn general depot.
Concurrent jurisdiction shall be, and the same is hereby ceded to the United States over and within all the land comprising the Auburn General Depot area, being 570.08 acres, more or less, situate in King county, state of Washington; saving, however, to the state the right to serve civil and criminal process within the limits of the aforesaid area in suits or prosecutions for or on account of rights acquired, obligations incurred or crimes committed in said state, but outside of said area. The metes and bounds description of the land over which jurisdiction is ceded hereby is as follows:

A parcel of land in sections 24 and 25, Township 21 North, Range 4 East, Willamette Meridian, King County, as follows: Beginning at a point on the west line of the Northern Pacific Railway right-of-way which point is S 89˚16'55" W, 423.65 feet and N 2˚12'33" W, 20 feet from the southeast corner of section 25, thence S 89˚16'55" W, 1548.93 feet along the north right-of-way line of Ellingson Road to a point, thence N 0˚10'45" E, 1298.11 feet to a point, thence S 89˚31'28" W, 638.25 feet to the east right-of-way line of Greenhalgh Road, thence N 0˚08'47" E, 1351.31 feet along said east right-of-way line to its intersection with the north right-of-way line of Algona Road, thence S 89˚46'07" W, 1724.35 feet along said north right-of-way line to a point on the easterly right-of-way line of the Chicago, Milwaukee, St. Paul and Pacific Railroad, thence N 0˚04'38" W, 1223.74 feet along said right-of-way to a point of spiral curve, thence along a spiral curve whose central angle is 1˚36'14" and whose long chord bears N 0˚27'20" E, 158.51 feet, thence along a circular curve to the right, whose radius bears S 88˚28'24" E, 2822.01 feet, through a central angle of 21˚16'24" for a distance of 1047.78 feet to a point of spiral, thence along a spiral curve whose central angle is 1˚36'14", and whose long chord bears N 23˚51'42" E, 158.51 feet, thence N 24˚24'15" E, 3088.12 feet to a point of spiral curve, thence along a spiral whose central angle is 1˚35'51", and whose long chord bears N 23˚51'55" E, 161.51 feet to point of circular curve, thence along a circular curve, to the left, whose radius bears N 67˚11'36" W, 2908.01 feet, through a central angle of 20˚58'46" for a distance of 1064.80 feet, thence along a spiral curve to the left, whose central angle is 1˚35'51", and whose long chord bears N 0˚45'10" E, 161.51 feet, thence N 0˚13'47" E, 1148.81 feet to the centerline of the Chicago, Milwaukee, St. Paul and Pacific Railroad and Northern Pacific crossover track being a point in a curve, thence along centerline of said crossover track on a curve to the left in a southeasterly direction, from a radius which bears N 63˚36'26" E, 351.28 feet, through a central angle of 26˚50'13" for a distance of 164.54 feet, thence S 53˚13'47" E, 1840.78 feet along said centerline, thence along a curve to the right in a southeasterly direction, from a radius which bears S 36˚46'13" W, 386.60 feet, through a central angle of 10˚26'06" for a distance of 70.41 feet to the intersection of the westerly right-of-way line of county road No. 76, thence *S 2˚12'33" E, 6596.21 feet along the westerly right-of-way line of county road No. 76 to the East-West centerline of said section 25, thence N 89˚46'02" E, 60.04 feet to the westerly right-of-way line of the Northern Pacific Railway Company, thence S 2˚12'33" E, 2605.01 feet to point of beginning. The jurisdiction ceded hereby does not extend to any existing perimeter railroad or county road right-of-way.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c40.pdf?cite=1951%20c%2040%20§%201[1951 c 40 § 1]; ]

== 37.08.280 - Veterans hospitals.
Upon the filing of an appropriate notice thereof with the governor by the administrator of veterans affairs, an agency of the United States of America, pursuant to the provisions of section 302 of Public Law 93-82 (87 Stat. 195; 38 U.S.C. Sec. 5007), the governor is hereby authorized and directed to accept such legislative jurisdiction as is necessary to establish concurrent jurisdiction between the United States and the state of Washington to all land comprising the veterans hospital located at Vancouver in Clark county, Washington; the veterans administration hospital located at Walla Walla in Walla Walla county, Washington, and the veterans administration hospital located at American Lake in Pierce county, Washington. The acquisition of such concurrent jurisdiction shall become effective upon filing the documents signifying such acceptance in the office of the secretary of state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c142.pdf?cite=1975%201st%20ex.s.%20c%20142%20§%201[1975 1st ex.s. c 142 § 1]; ]

