= 47.02 - Department buildings.
:toc:

== 47.02.010 - Buildings on east capitol site authorized—Financing.
The department is authorized in accordance with the provisions of this chapter and RCW 79.24.500 through 79.24.600 to provide for the acquisition of land and the construction of buildings, laboratories, and facilities on the east capitol site for the use of the commission and the department and to finance payment thereof by bonds payable out of special funds from the proceeds of state excise taxes on motor vehicle fuels, or by gifts, bequests, or grants or by such additional funds as the legislature may provide.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%2083[1984 c 7 § 83]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c235.pdf?cite=1977%20ex.s.%20c%20235%20§%2014[1977 ex.s. c 235 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c167.pdf?cite=1965%20ex.s.%20c%20167%20§%201[1965 ex.s. c 167 § 1]; ]

== 47.02.120 - District 1 headquarters bonds—Issuance and sale.
For the purpose of providing funds for the acquisition of headquarters facilities for district 1 of the department of transportation and costs incidental thereto, together with all improvements and equipment required to make the facilities suitable for the department's use, there shall be issued and sold upon the request of the secretary of the department of transportation a total of fifteen million dollars of general obligation bonds of the state of Washington.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6800-S.SL.pdf?cite=2006%20c%20334%20§%2039[2006 c 334 § 39]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c293.pdf?cite=1990%20c%20293%20§%201[1990 c 293 § 1]; ]

== 47.02.130 - District 1 headquarters bonds—Uses of proceeds.
Authorized uses of proceeds from the sale of bonds authorized in RCW 47.02.120 through 47.02.190 include but are not limited to repayment to the motor vehicle fund for the initial financing of the headquarters facilities.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5615-S.SL.pdf?cite=1999%20c%2094%20§%2011[1999 c 94 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c293.pdf?cite=1990%20c%20293%20§%202[1990 c 293 § 2]; ]

== 47.02.140 - District 1 headquarters bonds—Duties of state finance committee.
Upon the request of the secretary of the department of transportation, the state finance committee shall supervise and provide for the issuance, sale, and retirement of the bonds authorized by RCW 47.02.120 through 47.02.190 in accordance with chapter 39.42 RCW. Bonds authorized by RCW 47.02.120 through 47.02.190 shall be sold in such manner, at such time or times, in such amounts, and at such price as the state finance committee shall determine. Except for the purpose of repaying the loan from the motor vehicle fund, no such bonds may be offered for sale without prior legislative appropriation of the net proceeds of the sale of the bonds.

The state finance committee shall consider the issuance of short-term obligations in lieu of long-term obligations for the purposes of more favorable interest rates, lower total interest costs, and increased marketability and for the purpose of retiring the bonds during the life of the project for which they were issued.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6800-S.SL.pdf?cite=2006%20c%20334%20§%2040[2006 c 334 § 40]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c293.pdf?cite=1990%20c%20293%20§%203[1990 c 293 § 3]; ]

== 47.02.150 - District 1 headquarters bonds—Proceeds, deposit and use.
The proceeds from the sale of bonds authorized by RCW 47.02.120 through 47.02.190 shall be available only for the purposes enumerated in RCW 47.02.120 and 47.02.130; for the payment of bond anticipation notes, if any; and for the payment of bond issuance costs, including the costs of underwriting. Proceeds shall be deposited in the motor vehicle fund.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5615-S.SL.pdf?cite=1999%20c%2094%20§%2012[1999 c 94 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c293.pdf?cite=1990%20c%20293%20§%204[1990 c 293 § 4]; ]

== 47.02.160 - District 1 headquarters bonds—Statement of general obligation—Pledge of excise taxes.
Bonds issued under the authority of RCW 47.02.120 through 47.02.190 must distinctly state that they are a general obligation of the state of Washington, must pledge the full faith and credit of the state to the payment of the principal thereof and the interest thereon, and must contain an unconditional promise to pay such principal and interest as the same becomes due. The principal and interest on the bonds must be first payable in the manner provided in RCW 47.02.120 through 47.02.190 from the proceeds of the state excise taxes on motor vehicle and special fuels imposed by chapter 82.38 RCW. Proceeds of such excise taxes are hereby pledged to the payment of any bonds and the interest thereon issued under the authority of RCW 47.02.120 through 47.02.190, and the legislature agrees to continue to impose these excise taxes on motor vehicle and special fuels in amounts sufficient to pay, when due, the principal and interest on all bonds issued under the authority of RCW 47.02.120 through 47.02.190.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1883-S.SL.pdf?cite=2013%20c%20225%20§%20611[2013 c 225 § 611]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1225.SL.pdf?cite=1995%20c%20274%20§%205[1995 c 274 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c293.pdf?cite=1990%20c%20293%20§%205[1990 c 293 § 5]; ]

== 47.02.170 - District 1 headquarters bonds—Repayment procedure—Designated funds.
Both principal and interest on the bonds issued for the purposes of RCW 47.02.120 through 47.02.190 shall be payable from the highway bond retirement fund. The state finance committee may provide that a special account be created in the fund to facilitate payment of the principal and interest. The state finance committee shall, on or before June 30th of each year, certify to the state treasurer the amount required for principal and interest on the bonds in accordance with the bond proceedings. The state treasurer shall withdraw revenues from the motor vehicle fund and deposit in the highway bond retirement fund, or a special account in the fund, such amounts, and at such times, as are required by the bond proceedings.

Any funds required for bond retirement or interest on the bonds authorized by RCW 47.02.120 through 47.02.190 shall be taken from that portion of the motor vehicle fund that results from the imposition of excise taxes on motor vehicle and special fuels and that is distributed to the state under RCW 46.68.130. Funds required shall never constitute a charge against any other allocations of motor vehicle fuel and special fuel tax revenues to the state, counties, cities, and towns unless the amount arising from excise taxes on motor vehicle and special fuels distributed to the state under RCW 46.68.130 proves insufficient to meet the requirements for bond retirement or interest on any such bonds.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c293.pdf?cite=1990%20c%20293%20§%206[1990 c 293 § 6]; ]

== 47.02.190 - District 1 headquarters bonds—Equal charges against certain revenues.
Bonds issued under the authority of RCW 47.02.120 through * 47.02.180 and this section and any other general obligation bonds of the state of Washington that have been or that may be authorized and that pledge motor vehicle and special fuels excise taxes for the payment of principal and interest thereon shall be an equal charge against the revenues from such motor vehicle and special fuels excise taxes.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c293.pdf?cite=1990%20c%20293%20§%208[1990 c 293 § 8]; ]

