= 47.17 - State highway routes.
:toc:

== 47.17.001 - Criteria for changes to system.
In considering whether to make additions, deletions, or other changes to the state highway system, the legislature shall be guided by the following criteria as contained in the Road Jurisdiction Committee Phase I report to the legislature dated January 1987:

. A rural highway route should be designated as a state highway if it meets any of the following criteria:

.. Is designated as part of the national system of interstate and defense highways (popularly called the interstate system); or

.. Is designated as part of the system of numbered United States routes; or

.. Contains an international border crossing that is open twelve or more hours each day.

. A rural highway route may be designated as a state highway if it is part of an integrated system of roads and:

.. Carries in excess of three hundred thousand tons annually and provides primary access to a rural port or intermodal freight terminal;

.. Provides a major cross-connection between existing state highways; 

.. Connects places exhibiting one or more of the following characteristics:

... A population center of one thousand or greater;

... An area or aggregation of areas having a population equivalency of one thousand or more, such as, but not limited to, recreation areas, military installations, and so forth;

... A county seat;

... A major commercial-industrial terminal in a rural area with a population equivalency of one thousand or greater; or

.. Is designated as a scenic and recreational highway.

. An urban highway route that meets any of the following criteria should be designated as part of the state highway system:

.. Is designated as part of the interstate system;

.. Is designated as part of the system of numbered United States routes;

.. Is an urban extension of a rural state highway into or through an urban area and is necessary to form an integrated system of state highways;

.. Is a principal arterial that is a connecting link between two state highways and serves regionally oriented through traffic in urbanized areas with a population of fifty thousand or greater, or is a spur that serves regionally oriented traffic in urbanized areas.

. The following guidelines are intended to be used as a basis for interpreting and applying the criteria to specific routes:

.. For any route wholly within one or more contiguous jurisdictions which would be proposed for transfer to the state highway system under these criteria, if local officials prefer, responsibility will remain at the local level.

.. State highway routes maintain continuity of the system by being composed of routes that join other state routes at both ends or to arterial routes in the states of Oregon and Idaho and the Province of British Columbia.

.. Public facilities may be considered to be served if they are within approximately two miles of a state highway.

.. Exceptions may be made to include:

... Rural spurs as state highways if they meet the criteria relative to serving population centers of one thousand or greater population or activity centers with population equivalencies or an aggregated population of one thousand or greater;

... Urban spurs as state highways that provide needed access to Washington state ferry terminals, state parks, major seaports, and trunk airports; and

... Urban connecting links as state highways that function as needed bypass routing of regionally oriented through traffic and benefit truck routing, capacity alternative, business congestion, and geometric deficiencies.

.. In urban and urbanized areas:

... Unless they are significant regional traffic generators, public facilities such as state hospitals, state correction centers, state universities, ferry terminals, and military bases do not constitute a criteria for establishment of a state highway; and

... There may be no more than one parallel nonaccess controlled facility in the same corridor as a freeway or limited access facility as designated by the metropolitan planning organization.

.. When there is a choice of two or more routes between population centers, the state route designation shall normally be based on the following considerations:

... The ability to handle higher traffic volumes;

... The higher ability to accommodate further development or expansion along the existing alignment;

... The most direct route and the lowest travel time;

... The route that serves traffic with the most interstate, statewide, and interregional significance;

.. The route that provides the optimal spacing between other state routes; and

.. The route that best serves the comprehensive plan for community development in those areas where such a plan has been developed and adopted.

.. A route designated in chapter 47.39 RCW as a scenic and recreational highway may be designated as a state highway in addition to a parallel state highway route.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2023-S.SL.pdf?cite=1993%20c%20430%20§%201[1993 c 430 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c233.pdf?cite=1990%20c%20233%20§%201[1990 c 233 § 1]; ]

== 47.17.005 - State route No. 2.
A state highway to be known as state route number 2 is established as follows:

Beginning at a junction with state route number 5 in Everett, thence easterly by way of Monroe, Stevens Pass, and Leavenworth to a junction with state route number 97 in the vicinity of Peshastin; also

From a junction with state route number 97 in the vicinity of Peshastin, thence easterly by way of Wenatchee, to a junction with state route number 97 in the vicinity of Orondo, thence easterly by way of Waterville, Wilbur, and Davenport to a junction with state route number 90 in the vicinity west of Spokane; also

Beginning at a junction with state route number 90 at Spokane, thence northerly to a junction with state route number 395 in the vicinity north of Spokane; also

From a junction with state route number 395 in the vicinity north of Spokane, thence northerly to a junction with state route number 20 at Newport; also

From a junction with state route number 20 at Newport, thence easterly to the Washington-Idaho boundary line.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1232.SL.pdf?cite=1997%20c%20155%20§%201[1997 c 155 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c199.pdf?cite=1987%20c%20199%20§%201[1987 c 199 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%202[1970 ex.s. c 51 § 2]; ]

== 47.17.010 - State route No. 3.
A state highway to be known as state route number 3 is established as follows:

Beginning at a junction with state route number 101 at Shelton, thence northeasterly to a junction with state route number 302 at Allyn; also

From that junction with state route number 302 at Allyn, thence northeasterly to a junction with state route number 106 in the vicinity of Belfair; also

From that junction with state route number 106 in the vicinity of Belfair, thence northeasterly by the most feasible route to Bremerton, thence northerly and easterly by the most feasible route in the vicinity of Poulsbo to a junction with state route number 104 in the vicinity of Port Gamble.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%203[1970 ex.s. c 51 § 3]; ]

== 47.17.015 - State route No. 4.
A state highway to be known as state route number 4 is established as follows:

Beginning at a junction with state route number 101 in the vicinity of a location known as Johnson's Landing, in Pacific county, thence southeasterly by the most feasible route by way of Kelso to a junction with state route number 5.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%204[1970 ex.s. c 51 § 4]; ]

== 47.17.020 - State route No. 5—Washington green highway.
A state highway to be known as state route number 5, and designated as a Washington green highway, is established as follows:

Beginning at the Washington-Oregon boundary line on the interstate bridge over the Columbia river at Vancouver, thence northerly by way of Kelso, Chehalis, Centralia, Olympia, Tacoma, Seattle, Everett and Mt. Vernon, thence northwesterly to the east of Lake Samish, thence northeasterly and northerly by way of Bellingham to the international boundary line in the vicinity of Blaine in Whatcom county.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1303-S2.SL.pdf?cite=2007%20c%20348%20§%20405[2007 c 348 § 405]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%205[1970 ex.s. c 51 § 5]; ]

== 47.17.025 - State route No. 6.
A state highway to be known as state route number 6 is established as follows:

Beginning at a junction with state route number 101 at Raymond, thence easterly by the most feasible route to a junction with state route number 5 at Chehalis.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%206[1970 ex.s. c 51 § 6]; ]

== 47.17.030 - State route No. 7.
A state highway to be known as state route number 7 is established as follows:

Beginning at a junction with state route number 12 in the vicinity of Morton, thence northerly to a junction with state route number 706 at Elbe; also

From that junction with state route number 706 at Elbe, thence northerly to a junction with state route number 5 at Tacoma.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%207[1970 ex.s. c 51 § 7]; ]

== 47.17.035 - State route No. 8.
A state highway to be known as state route number 8 is established as follows:

Beginning at a junction with state route number 12 in the vicinity of Elma, thence easterly to a junction with state route number 101 west of Olympia.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c199.pdf?cite=1987%20c%20199%20§%202[1987 c 199 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%208[1970 ex.s. c 51 § 8]; ]

== 47.17.040 - State route No. 9.
A state highway to be known as state route number 9 is established as follows:

Beginning at a junction with state route number 522 north of Woodinville, thence northerly by way of Snohomish, Arlington and Sedro Woolley to a junction with state route number 542, in the vicinity of Deming; also

Beginning at a junction with state route number 542, in the vicinity of Lawrence, thence northerly to the international boundary at Sumas.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%209[1970 ex.s. c 51 § 9]; ]

== 47.17.045 - State route No. 10.
A state highway to be known as state route number 10 is established as follows:

Beginning at a junction with state route number 970 at Teanaway junction thence easterly to a junction with state route number 97 west of Ellensburg.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c199.pdf?cite=1987%20c%20199%20§%203[1987 c 199 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975c63.pdf?cite=1975%20c%2063%20§%2014[1975 c 63 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c73.pdf?cite=1971%20ex.s.%20c%2073%20§%201[1971 ex.s. c 73 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2010[1970 ex.s. c 51 § 10]; ]

== 47.17.050 - State route No. 11.
A state highway to be known as state route number 11 is established as follows:

Beginning at a junction with state route number 5 in the vicinity of Burlington, thence northerly by way of Blanchard to a junction with state route number 5 at Bellingham.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c199.pdf?cite=1987%20c%20199%20§%204[1987 c 199 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2011[1970 ex.s. c 51 § 11]; ]

== 47.17.055 - State route No. 12.
A state highway to be known as state route number 12 is established as follows:

Beginning at a junction with state route number 101 at Aberdeen, thence easterly by way of Montesano and Elma to a junction with state route number 8 in the vicinity of Elma; also

From that junction with state route number 8 in the vicinity of Elma, thence southeasterly to a junction with state route number 5 in the vicinity north of Centralia; also

Beginning at a junction with state route number 5 in the vicinity south of Chehalis, thence easterly by way of Morton and White Pass to a junction with state route number 410 northwest of Yakima; also

From that junction with state route number 410 northwest of Yakima, thence southeasterly to a junction with state route number 82 at Yakima; also

Beginning at a junction with state route number 182 near Pasco, thence southeasterly by the most feasible route by way of Wallula to Walla Walla, thence northerly by way of Dayton to a junction with state route number 127 at Dodge; also

From that junction with state route number 127 in the vicinity of Dodge, thence easterly by the most feasible route by way of Pomeroy and Clarkston to the Washington-Idaho boundary line.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c177.pdf?cite=1985%20c%20177%20§%201[1985 c 177 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c180.pdf?cite=1983%20c%20180%20§%201[1983 c 180 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2012[1970 ex.s. c 51 § 12]; ]

== 47.17.060 - State route No. 14.
A state highway to be known as state route number 14 is established as follows:

Beginning at a junction with state route number 5 at Vancouver, thence easterly by way of Stevenson to a junction with state route number 97 in the vicinity of Maryhill; also

Beginning at a junction with state route number 97 in the vicinity of Maryhill, thence easterly along the north bank of the Columbia river to a junction with state route number 82 in the vicinity of Plymouth.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c177.pdf?cite=1985%20c%20177%20§%202[1985 c 177 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2013[1970 ex.s. c 51 § 13]; ]

== 47.17.065 - State route No. 16.
A state highway to be known as state route number 16 is established as follows:

Beginning at a junction with state route number 5 at Tacoma, thence northwesterly by way of the Tacoma Narrows Bridge to a junction with state route number 3 in the vicinity of Gorst.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c199.pdf?cite=1987%20c%20199%20§%205[1987 c 199 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c151.pdf?cite=1973%201st%20ex.s.%20c%20151%20§%201[1973 1st ex.s. c 151 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2014[1970 ex.s. c 51 § 14]; ]

== 47.17.070 - State route No. 17.
A state highway to be known as state route number 17 is established as follows:

Beginning at a junction with state route number 395 in the vicinity of Mesa, thence northwesterly by way of the vicinity of Moses Lake, and Soap Lake, to a junction with state route number 2 west of Coulee City; also

From a junction with state route number 2 in the vicinity west of Coulee City, thence northerly by way of the vicinity of Leahy, crossing the Columbia river in the vicinity of Bridgeport, thence northwesterly to a junction with state route number 97 east of Brewster.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c33.pdf?cite=1979%20ex.s.%20c%2033%20§%201[1979 ex.s. c 33 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2015[1970 ex.s. c 51 § 15]; ]

== 47.17.075 - State route No. 18.
A state highway to be known as state route number 18 is established as follows:

Beginning at a junction with state route number 99 in the vicinity of northeast Tacoma, thence northeasterly by way of Auburn to a junction with state route number 90 west of North Bend.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c199.pdf?cite=1987%20c%20199%20§%206[1987 c 199 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2016[1970 ex.s. c 51 § 16]; ]

== 47.17.077 - State route No. 19.
A state highway to be known as state route number 19 is established as follows:

Beginning at a junction with state route number 104, thence northerly to a junction with state route number 20 near Old Fort Townsend state park.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%201[1991 c 342 § 1]; ]

== 47.17.080 - State route No. 20.
A state highway to be known as state route number 20 is established as follows:

Beginning at a junction with state route number 101 in the vicinity of Discovery Bay, thence northeasterly via the most feasible route to Port Townsend; also

From the state ferry terminal at Port Townsend via the state ferry system northeasterly to the state ferry terminal at Keystone; also

From the Keystone ferry dock on Whidbey Island, thence northeasterly by the most feasible route by way of Deception Pass, Burlington, Sedro Woolley, Concrete, Newhalem, Winthrop, Twisp, Okanogan, Tonasket, Republic, Kettle Falls, Colville, and Tiger; thence southerly and southeasterly to a junction with state route number 2 at Newport.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2618-S.SL.pdf?cite=1994%20c%20209%20§%201[1994 c 209 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c151.pdf?cite=1973%201st%20ex.s.%20c%20151%20§%2013[1973 1st ex.s. c 151 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2017[1970 ex.s. c 51 § 17]; ]

== 47.17.081 - State route No. 20 north.
A state highway to be known as state route number 20 north is established as follows:

Beginning at a junction with state route number 20 in the vicinity southeast of Anacortes, thence northwesterly to the state ferry terminal at Anacortes; also

From the state ferry terminal at Anacortes via the state ferry system to the state ferry terminals at Lopez Island, Shaw Island, Orcas Island, and Friday Harbor.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2618-S.SL.pdf?cite=1994%20c%20209%20§%202[1994 c 209 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c151.pdf?cite=1973%201st%20ex.s.%20c%20151%20§%2017[1973 1st ex.s. c 151 § 17]; ]

== 47.17.085 - State route No. 21.
A state highway to be known as state route number 21 is established as follows:

Beginning at a junction with state route number 260 in Kahlotus, thence northerly by the most feasible route, crossing state route number 26, and continuing northerly to a junction with state route number 395 in the vicinity of Lind; also

Beginning at a junction with state route number 395 in the vicinity of Lind, thence northerly by the most feasible route by way of Odessa to a junction with state route number 2 in the vicinity west of Wilbur; also

Beginning at a junction with state route number 2 at Wilbur, thence northerly by the most feasible route to a junction with state route number 20 at Republic; also

Beginning at a junction with state route number 20 east of Republic, thence northeasterly by the most feasible route to the east of Curlew lake by way of Curlew to the international boundary line in the vicinity of Danville.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c79.pdf?cite=1983%20c%2079%20§%201[1983 c 79 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975c63.pdf?cite=1975%20c%2063%20§%201[1975 c 63 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2018[1970 ex.s. c 51 § 18]; ]

== 47.17.090 - State route No. 22.
A state highway to be known as state route number 22 is established as follows:

Beginning at a junction with state route number 82, thence southerly to a junction of state route number 97 in the vicinity of Toppenish; also

From a junction with state route number 97 at Toppenish, thence southeasterly by way of Mabton to a junction with state route number 82 at Prosser.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c199.pdf?cite=1987%20c%20199%20§%207[1987 c 199 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2019[1970 ex.s. c 51 § 19]; ]

== 47.17.095 - State route No. 23.
A state highway to be known as state route number 23 is established as follows:

Beginning at a junction with state route number 195 in the vicinity north of Colfax, thence northwesterly to a junction with state route number 90 at Sprague; also

From that junction with state route number 90 at Sprague, thence northwesterly to a junction with state route number 28 at Harrington.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c199.pdf?cite=1987%20c%20199%20§%208[1987 c 199 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2020[1970 ex.s. c 51 § 20]; ]

== 47.17.100 - State route No. 24.
A state highway to be known as state route number 24 is established as follows:

Beginning at a junction with state route number 82 at Yakima, thence easterly and northerly via Cold Creek and Vernita to a junction with state route number 26 in the vicinity of Othello.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2021[1970 ex.s. c 51 § 21]; ]

== 47.17.105 - State route No. 25.
A state highway to be known as state route number 25 is established as follows:

Beginning at a junction with state route number 2 at Davenport, thence northerly by the most feasible route to a junction with state route number 395 in the vicinity of Kettle Falls, thence northeasterly by the most feasible route to international boundary line.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2022[1970 ex.s. c 51 § 22]; ]

== 47.17.110 - State route No. 26.
A state highway to be known as state route number 26 is established as follows:

Beginning at a junction with state route number 90 in the vicinity of the east end of the Vantage bridge, thence southerly, parallel to the east bank of the Columbia river for a distance of approximately two and one-half miles, thence southeasterly to the vicinity of Othello, thence easterly to a junction with state route number 395, thence easterly by way of the vicinity of Washtucna and Dusty to a junction with state route number 195 in the vicinity of Colfax.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c33.pdf?cite=1979%20ex.s.%20c%2033%20§%202[1979 ex.s. c 33 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2023[1970 ex.s. c 51 § 23]; ]

== 47.17.115 - State route No. 27.
A state highway to be known as state route number 27 is established as follows:

Beginning at a junction with state route number 195 in the vicinity of Pullman, thence northerly to a junction with state route number 271 in the vicinity of Oakesdale; also

From a junction with state route number 271 at Oakesdale, thence northerly by way of Tekoa, Latah, Fairfield, and Rockford to a junction with state route number 290 in the vicinity of Millwood.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%202[1991 c 342 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c195.pdf?cite=1979%20ex.s.%20c%20195%20§%201[1979 ex.s. c 195 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975c63.pdf?cite=1975%20c%2063%20§%202[1975 c 63 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2024[1970 ex.s. c 51 § 24]; ]

== 47.17.120 - State route No. 28.
A state highway to be known as state route number 28 is established as follows:

Beginning at a junction with state route number 2 in the vicinity east of Wenatchee, thence southeasterly to a junction with state route number 281 at Quincy; also

From that junction with state route number 281 at Quincy, thence easterly by way of Ephrata and Odessa to a junction with state route number 2 at Davenport.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2025[1970 ex.s. c 51 § 25]; ]

== 47.17.130 - State route No. 31.
A state highway to be known as state route number 31 is established as follows:

Beginning at a junction with state route number 20 at Tiger, thence northerly by way of Metaline Falls to the international boundary.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c151.pdf?cite=1973%201st%20ex.s.%20c%20151%20§%2014[1973 1st ex.s. c 151 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2027[1970 ex.s. c 51 § 27]; ]

== 47.17.132 - State route No. 35.
A state highway to be known as state route number 35 is established as follows:

Beginning at the Washington-Oregon boundary line thence northerly to a junction with state route number 14 in the vicinity of White Salmon.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6800-S.SL.pdf?cite=2006%20c%20334%20§%2041[2006 c 334 § 41]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1316.SL.pdf?cite=1997%20c%20308%20§%201[1997 c 308 § 1]; ]

== 47.17.133 - State route No. 41.
A state highway to be known as state route number 41 is established as follows:

Beginning at a junction with state route number 2 in Newport, thence southerly along the Washington-Idaho boundary line to Fourth Street in Newport.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1232.SL.pdf?cite=1997%20c%20155%20§%202[1997 c 155 § 2]; ]

== 47.17.135 - State route No. 82—Washington green highway.
A state highway to be known as state route number 82, and designated as a Washington green highway, is established as follows:

Beginning at a junction with state route number 90 in the vicinity of Ellensburg, thence southerly and easterly by way of Yakima, Union Gap, Sunnyside, Prosser, Kiona, and Goose Gap west of Richland, thence southeasterly near Kennewick and southwesterly by way of the vicinity of Plymouth to a crossing of the Columbia river at the Washington-Oregon boundary line.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1303-S2.SL.pdf?cite=2007%20c%20348%20§%20406[2007 c 348 § 406]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c33.pdf?cite=1979%20ex.s.%20c%2033%20§%203[1979 ex.s. c 33 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2028[1970 ex.s. c 51 § 28]; ]

== 47.17.140 - State route No. 90—American Veterans Memorial Highway—Washington green highway.
A state highway to be known as state route number 90, and designated as the American Veterans Memorial Highway as well as a Washington green highway, is established as follows:

Beginning at a junction with state route number 5, thence, via the west approach to the Lake Washington bridge in Seattle, in an easterly direction by way of Mercer Island, North Bend, Snoqualmie pass, Ellensburg, Vantage, Moses Lake, Ritzville, Sprague and Spokane to the Washington-Idaho boundary line.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1303-S2.SL.pdf?cite=2007%20c%20348%20§%20407[2007 c 348 § 407]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5288-S.SL.pdf?cite=1991%20c%2056%20§%202[1991 c 56 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c73.pdf?cite=1971%20ex.s.%20c%2073%20§%202[1971 ex.s. c 73 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2029[1970 ex.s. c 51 § 29]; ]

== 47.17.145 - State route No. 92.
A state highway to be known as state route number 92 is established as follows:

Beginning at a junction with state route number 9 northeast of Everett, thence northeasterly by the most feasible route to Granite Falls.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2030[1970 ex.s. c 51 § 30]; ]

== 47.17.153 - State route No. 96.
A state highway to be known as state route number 96 is established as follows:

Beginning at a junction with state route number 5 in the vicinity south of Everett, thence easterly to a junction with state route number 9 in the vicinity of Ree's Corner.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%203[1991 c 342 § 3]; ]

== 47.17.155 - State route No. 97.
A state highway to be known as state route number 97 is established as follows:

Beginning at the Washington-Oregon boundary on the interstate bridge across the Columbia river at Biggs Rapids, thence in a northerly direction to the junction with state route number 14 in the vicinity of Maryhill, thence in a northerly direction by way of Goldendale, thence northeasterly by way of Satus Pass to a junction with state route number 22 at Toppenish, thence northwesterly south of the Yakima river to a junction with state route number 82 at Union Gap; also

Beginning at a junction with state route number 90 in the vicinity of Ellensburg, thence northeasterly by way of Swauk Pass to a junction with state route number 2 in the vicinity of Peshastin; also

Beginning at a junction with state route number 2 in the vicinity north of Orondo, thence northerly by way of the vicinities of Chelan, Pateros, Brewster, Okanogan, and Oroville to the international boundary line.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c199.pdf?cite=1987%20c%20199%20§%209[1987 c 199 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%20131[1984 c 7 § 131]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975c63.pdf?cite=1975%20c%2063%20§%203[1975 c 63 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c151.pdf?cite=1973%201st%20ex.s.%20c%20151%20§%202[1973 1st ex.s. c 151 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2032[1970 ex.s. c 51 § 32]; ]

== 47.17.157 - State route No. 97-alternate.
A state highway to be known as state route number 97-alternate is established as follows:

Beginning at a junction with state route number 2 in the vicinity of Olds, thence northerly by way of Entiat to a junction with state route number 97 in the vicinity east of Chelan.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c199.pdf?cite=1987%20c%20199%20§%2010[1987 c 199 § 10]; ]

== 47.17.160 - State route No. 99.
A state highway to be known as state route number 99 is established as follows:

Beginning at a junction with state route number 18 in the vicinity of Federal Way, thence northerly by way of Midway, to a junction with state route 518 in Tukwila; also

Beginning at a junction with state route number 599 in the vicinity of Tukwila, thence northerly by way of Seattle, Edmonds, and Lynnwood to a junction with state route number 5 in Everett: PROVIDED, That until state route number 509 is constructed and opened to traffic on an anticipated ultimate alignment from a junction with state route number 705 in Tacoma via the Port of Tacoma industrial area to a junction with state route number 18 in the vicinity of Federal Way that portion of state route number 99 between state route number 5 at Fife and state route number 18 in the vicinity of Federal Way shall remain on the state highway system.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5376.SL.pdf?cite=2004%20c%20205%20§%201[2004 c 205 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c33.pdf?cite=1979%20ex.s.%20c%2033%20§%204[1979 ex.s. c 33 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c73.pdf?cite=1971%20ex.s.%20c%2073%20§%203[1971 ex.s. c 73 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2033[1970 ex.s. c 51 § 33]; ]

== 47.17.163 - State route No. 100.
A state highway to be known as state route number 100 is established as follows:

Beginning at a junction with state route number 101 in Ilwaco, thence westerly and southerly to Fort Canby state park; also

Beginning at a junction with state route number 100 in Ilwaco, thence southerly to Fort Canby state park.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%204[1991 c 342 § 4]; ]

== 47.17.165 - State route No. 101.
A state highway to be known as state route number 101 is established as follows:

Beginning at the Oregon boundary on the interstate bridge at Point Ellis, thence northwesterly by way of Ilwaco to a junction with state route number 4 in the vicinity of a location known as Johnson's Landing in Pacific county; also

From that junction with state route number 4 in the vicinity of a location known as Johnson's Landing, in Pacific county, thence northerly by way of South Bend to a junction with state route number 6 at Raymond; also

From that junction with state route number 6 at Raymond, thence northerly by way of Cosmopolis to a junction with state route number 12 at Aberdeen; also

From that junction with state route number 12 at Aberdeen, thence westerly to Hoquiam, thence northwesterly by way of Lake Quinault to Forks, thence easterly by way of Port Angeles to the vicinity of Discovery Bay, thence southerly by way of Shelton to a junction with state route number 5 in the vicinity west of Olympia; also

Beginning at a junction with state route number 101 in the vicinity east of Ilwaco, thence northerly to a junction with state route number 101 in the vicinity northeast of Ilwaco.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c199.pdf?cite=1987%20c%20199%20§%2011[1987 c 199 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2034[1970 ex.s. c 51 § 34]; ]

== 47.17.168 - State route No. 102.
A state highway to be known as state route number 102 is established as follows:

Beginning at the Washington Corrections Center, thence northeasterly to a junction of state route number 101 north of Shelton.

Before award of any construction contract for improvements to state route number 102 under either program A or program C, the department of transportation shall secure a portion of the construction cost from Mason county.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c197.pdf?cite=1984%20c%20197%20§%201[1984 c 197 § 1]; ]

== 47.17.170 - State route No. 103.
A state highway to be known as state route number 103 is established as follows:

Beginning at a junction with state route number 101 at Seaview, thence northerly by way of Long Beach to Leadbetter Point state park.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%205[1991 c 342 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2035[1970 ex.s. c 51 § 35]; ]

== 47.17.175 - State route No. 104.
A state highway to be known as state route number 104 is established as follows:

Beginning at a junction with state route number 101 in the vicinity south of Discovery Bay, thence southeasterly to the vicinity of Shine on Hood Canal, thence crossing Hood Canal to a junction with state route number 3 in the vicinity of Port Gamble; also

From that junction with state route number 3 in the vicinity of Port Gamble, thence to Port Gamble, thence southerly and easterly to the state ferry terminal at Kingston; also

From the state ferry terminal at Kingston via the state ferry system easterly to the state ferry terminal at Edmonds; also

From the state ferry terminal at Edmonds, thence southeasterly to a junction with state route number 99 in the vicinity of the Snohomish-King county line; also

Beginning at a junction with state route number 99 in the vicinity of the Snohomish-King county line, thence southeasterly to a junction with state route number 522 in the vicinity of Lake Forest Park.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2618-S.SL.pdf?cite=1994%20c%20209%20§%203[1994 c 209 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2036[1970 ex.s. c 51 § 36]; ]

== 47.17.180 - State route No. 105.
A state highway to be known as state route number 105 is established as follows:

Beginning at a junction with state route number 101 at Raymond, thence westerly by way of Tokeland and North Cove to the shore of Grays Harbor north of Westport; also

Beginning at a junction with state route number 105 in the vicinity south of Westport, thence northeasterly to a junction with state route number 101 at Aberdeen.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c199.pdf?cite=1987%20c%20199%20§%2012[1987 c 199 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2037[1970 ex.s. c 51 § 37]; ]

== 47.17.185 - State route No. 106.
A state highway to be known as state route number 106 is established as follows:

Beginning at a junction with state route number 101 near the mouth of the Skokomish river, thence northeasterly along the southeast shore of Hood Canal to a junction with state route number 3 in the vicinity of Belfair.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2038[1970 ex.s. c 51 § 38]; ]

== 47.17.190 - State route No. 107.
A state highway to be known as state route number 107 is established as follows:

Beginning at a junction with state route number 101 north of Artic, thence northeasterly to a junction with state route number 12 at Montesano.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2039[1970 ex.s. c 51 § 39]; ]

== 47.17.195 - State route No. 108.
A state highway to be known as state route number 108 is established as follows:

Beginning at a junction with state route number 8 in the vicinity west of McCleary, thence northeasterly to a junction with state route number 101 south of Shelton.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c151.pdf?cite=1973%201st%20ex.s.%20c%20151%20§%203[1973 1st ex.s. c 151 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2040[1970 ex.s. c 51 § 40]; ]

== 47.17.200 - State route No. 109.
A state highway to be known as state route number 109 is established as follows:

Beginning at a junction with state route number 101 in Hoquiam, thence northwesterly by way of Ocean City, Copalis, Pacific Beach, and Moclips to a junction with state route number 101 in the vicinity of Queets; also a bypass beginning at a junction with state route number 101 in the vicinity of the north city limits of Hoquiam, thence southerly to a junction with state route number 109 in the vicinity of the west city limits of Hoquiam.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c180.pdf?cite=1983%20c%20180%20§%202[1983 c 180 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2041[1970 ex.s. c 51 § 41]; ]

== 47.17.212 - State route No. 110.
A state highway to be known as state route number 110 is established as follows:

Beginning at a junction with state route number 101 in the vicinity north of Forks, thence westerly to the Olympic national park boundary in the vicinity of La Push; also

Beginning at a junction with state route number 110 near the Quillayute river, thence westerly to the Olympic national park boundary in the vicinity of Moro.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%206[1991 c 342 § 6]; ]

== 47.17.215 - State route No. 112.
A state highway to be known as state route number 112 is established as follows:

Beginning at the easterly boundary of the Makah Indian Reservation, thence easterly by way of Clallam Bay and Pysht to a junction with state route number 101 in or near Port Angeles.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c73.pdf?cite=1971%20ex.s.%20c%2073%20§%205[1971 ex.s. c 73 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2044[1970 ex.s. c 51 § 44]; ]

== 47.17.216 - State route No. 113.
A state highway to be known as state route number 113 is established as follows:

Beginning at a junction with state route number 101 in the vicinity of Sappho, thence northerly to a junction with state route number 112 in the vicinity of the Pysht River.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%207[1991 c 342 § 7]; ]

== 47.17.217 - State route No. 115.
A state highway to be known as state route number 115 is established as follows:

Beginning at Ocean Shores thence in an easterly and northerly direction by the most feasible route to a junction with state route number 109 in the vicinity south of Ocean City.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c60.pdf?cite=1973%20c%2060%20§%201[1973 c 60 § 1]; ]

== 47.17.219 - State route No. 116.
A state highway to be known as state route number 116 is established as follows:

Beginning at a junction with state route number 19 in the vicinity of Irondale, thence easterly and northerly to Fort Flagler state park.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%208[1991 c 342 § 8]; ]

== 47.17.221 - State route No. 117.
A state highway to be known as state route number 117 is established as follows:

Beginning at a junction with state route number 101 in Port Angeles, thence northerly to the port of Port Angeles at Marine Drive.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%209[1991 c 342 § 9]; ]

== 47.17.223 - State route No. 119.
A state highway to be known as state route number 119 is established as follows:

Beginning at a junction with state route number 101 near Hoodsport, thence northwesterly to the Mount Rose development intersection.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2010[1991 c 342 § 10]; ]

== 47.17.225 - State route No. 121.
A state highway to be known as state route number 121 is established as follows:

Beginning at a junction with state route number 5 in the vicinity of Maytown, thence easterly, northerly, and westerly by way of Millersylvania state park to a junction with state route number 5 south of Tumwater.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2011[1991 c 342 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2046[1970 ex.s. c 51 § 46]; ]

== 47.17.227 - State route No. 122.
A state highway to be known as state route number 122 is established as follows:

Beginning at a junction with state route number 12 near Mayfield dam, thence northeasterly and southerly by way of Mayfield to a junction with state route number 12 in Mossyrock.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2012[1991 c 342 § 12]; ]

== 47.17.230 - State route No. 123.
A state highway to be known as state route number 123 is established as follows:

Beginning at a junction with state route number 12 in the vicinity west of White Pass, thence northerly to a junction with state route number 410 in the vicinity west of Chinook Pass.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2047[1970 ex.s. c 51 § 47]; ]

== 47.17.235 - State route No. 124.
A state highway to be known as state route number 124 is established as follows:

Beginning at a junction with state route number 12 in the vicinity of Burbank, thence northeasterly by the most feasible route to a point in the vicinity of Eureka, thence easterly by the most feasible route to a junction with state route number 125 in the vicinity of Prescott, thence easterly to a junction with state route number 12 in the vicinity northeast of Waitsburg.

That portion of state route number 124 lying between the junction with state route number 12 and the county road to Ice Harbor Dam to be known as "Ice Harbor Drive".

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c151.pdf?cite=1973%201st%20ex.s.%20c%20151%20§%204[1973 1st ex.s. c 151 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2048[1970 ex.s. c 51 § 48]; ]

== 47.17.240 - State route No. 125.
A state highway to be known as state route number 125 is established as follows:

Beginning at the Washington-Oregon boundary line south of Walla Walla, thence northerly to a junction with state route number 12 at Walla Walla; also

From a junction with state route number 12 at Walla Walla, thence northerly to a junction with state route number 124 at Prescott.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c33.pdf?cite=1979%20ex.s.%20c%2033%20§%205[1979 ex.s. c 33 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2049[1970 ex.s. c 51 § 49]; ]

== 47.17.250 - State route No. 127.
A state highway to be known as state route number 127 is established as follows:

Beginning at a junction with state route number 12 in the vicinity of Dodge, thence northerly to a junction with state route number 26 in the vicinity of Dusty.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c33.pdf?cite=1979%20ex.s.%20c%2033%20§%206[1979 ex.s. c 33 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2051[1970 ex.s. c 51 § 51]; ]

== 47.17.255 - State route No. 128.
A state highway to be known as state route number 128 is established as follows:

Beginning at a junction with state route number 12 in Clarkston, thence northeasterly and easterly by way of the Red Wolf crossing to the Idaho state line.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2013[1991 c 342 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c108.pdf?cite=1990%20c%20108%20§%201[1990 c 108 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2052[1970 ex.s. c 51 § 52]; ]

== 47.17.260 - State route No. 129.
A state highway to be known as state route number 129 is established as follows:

Beginning at the Washington-Oregon boundary line in Asotin county, thence northerly by the most feasible route by way of Asotin to a junction with state route number 12 at Clarkston.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2053[1970 ex.s. c 51 § 53]; ]

== 47.17.262 - State route No. 131.
A state highway to be known as state route number 131 is established as follows:

Beginning at the Gifford Pinchot national forest boundary south of Randle, thence northerly to a junction with state route number 12 in Randle.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2014[1991 c 342 § 14]; ]

== 47.17.275 - State route No. 141.
A state highway to be known as state route number 141 is established as follows:

Beginning at a wye junction with state route number 14, the west branch in the vicinity east of Underwood and the east branch in the vicinity of White Salmon, thence northerly to the boundary of the Gifford Pinchot National Forest.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2056[1970 ex.s. c 51 § 56]; ]

== 47.17.280 - State route No. 142.
A state highway to be known as state route number 142 is established as follows:

Beginning at a junction with state route number 14 in the vicinity of Lyle, thence northeasterly by way of Klickitat to a junction with state route number 97 in the vicinity of Goldendale.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2057[1970 ex.s. c 51 § 57]; ]

== 47.17.285 - State route No. 150.
A state highway to be known as state route number 150 is established as follows:

Beginning at Manson, thence southeasterly to the north of Lake Chelan to a junction with state route number 97-alternate at Chelan.

Also beginning at a junction with state route number 97-alternate at Chelan southerly to a junction with state route number 97 in the vicinity of Chelan Station.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c199.pdf?cite=1987%20c%20199%20§%2013[1987 c 199 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2058[1970 ex.s. c 51 § 58]; ]

== 47.17.295 - State route No. 153.
A state highway to be known as state route number 153 is established as follows:

Beginning at a junction with state route number 97 in the vicinity of Pateros, thence northerly and westerly by the most feasible route to a junction with state route number 20 in the vicinity south of Twisp.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2060[1970 ex.s. c 51 § 60]; ]

== 47.17.300 - State route No. 155.
A state highway to be known as state route number 155 is established as follows:

Beginning at a junction with state route number 2 in the vicinity north of Coulee City, thence northeasterly to the boundary of the federal reservation at the Grand Coulee dam; also

Beginning at the boundary of the federal reservation at the Grand Coulee dam, thence northwesterly by the most feasible route by way of Nespelem and Disautel to a junction with state route number 97 at Omak; also

Beginning at a junction with state route number 155 at Omak, thence northwesterly crossing the Okanogan river to a junction with state route number 215 at Omak.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975c63.pdf?cite=1975%20c%2063%20§%204[1975 c 63 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2061[1970 ex.s. c 51 § 61]; ]

== 47.17.305 - State route No. 160.
A state highway to be known as state route number 160 is established as follows:

Beginning at a junction with state route number 16 in the vicinity south of Port Orchard, thence easterly on Sedgwick Road to the Washington state ferry dock at Point Southworth; also

From the state ferry terminal at Point Southworth via the state ferry system easterly to the state ferry terminal at Vashon Heights; also

From the state ferry terminal at Vashon Heights easterly via the state ferry system to the state ferry terminal at Fauntleroy.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2618-S.SL.pdf?cite=1994%20c%20209%20§%204[1994 c 209 § 4]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2023-S.SL.pdf?cite=1993%20c%20430%20§%202[1993 c 430 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2062[1970 ex.s. c 51 § 62]; 1991 c 342 § 15; 1992 c 166 § 31; ]

== 47.17.310 - State route No. 161.
A state highway to be known as state route number 161 is established as follows:

Beginning at a junction with state route number 7 in the vicinity of La Grande, thence northeasterly via Eatonville to Puyallup, thence northerly to a junction with state route number 18.

That portion of state route 161 within King county shall be designated Enchanted Parkway.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c520.pdf?cite=1987%20c%20520%20§%201[1987 c 520 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c73.pdf?cite=1971%20ex.s.%20c%2073%20§%206[1971 ex.s. c 73 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2063[1970 ex.s. c 51 § 63]; ]

== 47.17.315 - State route No. 162.
A state highway to be known as state route number 162 is established as follows:

Beginning at a junction with state route number 410 at Sumner, thence southerly to Orting, thence northeasterly to a junction with state route number 165 in the vicinity south of Buckley.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975c63.pdf?cite=1975%20c%2063%20§%205[1975 c 63 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c73.pdf?cite=1971%20ex.s.%20c%2073%20§%207[1971 ex.s. c 73 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2064[1970 ex.s. c 51 § 64]; ]

== 47.17.317 - State route No. 163.
A state highway to be known as state route number 163 is established as follows:

Beginning at a junction with state route number 16 in Tacoma, thence northerly to the Point Defiance ferry terminal; also

From the state ferry terminal at Point Defiance via the state ferry system northerly to the state ferry terminal at Tahlequah.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2618-S.SL.pdf?cite=1994%20c%20209%20§%205[1994 c 209 § 5]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2016[1991 c 342 § 16]; ]

== 47.17.320 - State route No. 164.
A state highway to be known as state route number 164 is established as follows:

Beginning at a junction with state route number 18 in the vicinity of Auburn, thence southeasterly to a junction with state route number 410 at Enumclaw.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c199.pdf?cite=1987%20c%20199%20§%2014[1987 c 199 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2065[1970 ex.s. c 51 § 65]; ]

== 47.17.325 - State route No. 165.
A state highway to be known as state route number 165 is established as follows:

Beginning at the northwest entrance to Mt. Rainier National Park, thence northerly to a junction with state route number 410 at Buckley.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2066[1970 ex.s. c 51 § 66]; ]

== 47.17.328 - State route No. 166.
A state highway to be known as state route number 166 is established as follows:

Beginning at a junction with state route number 16 in the vicinity west of Port Orchard, thence northeasterly to the eastern Port Orchard city limits as they exist on June 10, 2010.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6510-S.SL.pdf?cite=2010%20c%2077%20§%202[2010 c 77 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2023-S.SL.pdf?cite=1993%20c%20430%20§%203[1993 c 430 § 3]; ]

== 47.17.330 - State route No. 167.
A state highway to be known as state route number 167 is established as follows:

Beginning at a junction with state route number 5 in the vicinity of Tacoma, thence easterly by way of the vicinity of Puyallup and Sumner, thence northerly by way of the vicinity of Auburn and Kent to a junction with state route number 900 in the vicinity of Renton.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2017[1991 c 342 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c33.pdf?cite=1979%20ex.s.%20c%2033%20§%208[1979 ex.s. c 33 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2067[1970 ex.s. c 51 § 67]; ]

== 47.17.335 - State route No. 168.
A state highway to be known as state route number 168 is established as follows:

Beginning at a junction with state route number 410 in the vicinity of the junction of the Greenwater and White rivers, thence easterly to a junction with state route number 410 in the vicinity north of Cliffdell.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2068[1970 ex.s. c 51 § 68]; ]

== 47.17.340 - State route No. 169.
A state highway to be known as state route number 169 is established as follows:

Beginning at a junction with state route number 164 at Enumclaw, thence northwesterly by way of Summit to a junction with state route number 900 in the vicinity of Renton.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c73.pdf?cite=1971%20ex.s.%20c%2073%20§%208[1971 ex.s. c 73 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2069[1970 ex.s. c 51 § 69]; ]

== 47.17.345 - State route No. 170.
A state highway to be known as state route number 170 is established as follows:

Beginning at a junction with state route number 17 west of Warden, thence easterly to Warden.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2070[1970 ex.s. c 51 § 70]; ]

== 47.17.350 - State route No. 171.
A state highway to be known as state route number 171 is established as follows:

Beginning at a junction with state route number 90 west of Moses Lake, thence northeasterly by way of Moses Lake to a junction with state route number 28 in the vicinity west of Odessa. Until such time as state route number 171 is actually constructed on the location adopted by the department, no existing county roads may be maintained or improved by the department as a temporary route of state route number 171.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%20132[1984 c 7 § 132]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2071[1970 ex.s. c 51 § 71]; ]

== 47.17.355 - State route No. 172.
A state highway to be known as state route number 172 is established as follows:

Beginning at a junction with state route number 2 in the vicinity of Waterville, thence northerly and easterly by the most feasible route by way of Mansfield to a junction with state route number 17 in the vicinity of Leahy.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2072[1970 ex.s. c 51 § 72]; ]

== 47.17.360 - State route No. 173.
A state highway to be known as state route number 173 is established as follows:

Beginning at a junction with state route number 17 at Bridgeport thence northwesterly on the south side of the Columbia river to a junction with state route number 97 in the vicinity of Brewster.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2073[1970 ex.s. c 51 § 73]; ]

== 47.17.365 - State route No. 174.
A state highway to be known as state route number 174 is established as follows:

Beginning at a junction with state route number 17 east of Bridgeport, thence easterly to the boundary of the federal reservation at Grand Coulee dam; also

Beginning at a junction with state route number 155 at Grand Coulee, thence southeasterly to a junction with state route number 21 in the vicinity north of Wilbur; also

A spur beginning at a junction with state route number 174 in the vicinity of the boundary of the federal reservation at the Grand Coulee dam and extending to Crown Point.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c199.pdf?cite=1987%20c%20199%20§%2015[1987 c 199 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2074[1970 ex.s. c 51 § 74]; ]

== 47.17.370 - State route No. 181.
A state highway to be known as state route number 181 is established as follows:

Beginning at a junction with state route number 516 in the vicinity of Kent, thence northerly to a junction with state route number 405 in the vicinity of Tukwila.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2018[1991 c 342 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c192.pdf?cite=1979%20ex.s.%20c%20192%20§%204[1979 ex.s. c 192 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c73.pdf?cite=1971%20ex.s.%20c%2073%20§%209[1971 ex.s. c 73 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2075[1970 ex.s. c 51 § 75]; ]

== 47.17.372 - State route No. 182.
A state highway to be known as state route number 182 is established as follows:

Beginning at a junction with state route number 82 in the vicinity of Goose Gap, thence easterly via Richland to a junction with state route number 395 in the vicinity of Pasco.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c33.pdf?cite=1979%20ex.s.%20c%2033%20§%209[1979 ex.s. c 33 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c73.pdf?cite=1971%20ex.s.%20c%2073%20§%2010[1971 ex.s. c 73 § 10]; ]

== 47.17.375 - State route No. 193.
A state highway to be known as state route number 193 is established as follows:

Beginning at a junction with state route number 128 in the vicinity of the Red Wolf crossing, thence westerly to the port of Wilma.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2019[1991 c 342 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c108.pdf?cite=1990%20c%20108%20§%202[1990 c 108 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%20133[1984 c 7 § 133]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2076[1970 ex.s. c 51 § 76]; ]

== 47.17.377 - State route No. 194.
A state highway to be known as state route number 194 is established as follows:

Beginning at the port of Almota, thence northerly and easterly to a junction with state route number 195 in the vicinity of Pullman.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2020[1991 c 342 § 20]; ]

== 47.17.380 - State route No. 195.
A state highway to be known as state route number 195 is established as follows:

Beginning at the Washington-Idaho boundary line southeast of Uniontown, thence northwesterly and northerly by way of the vicinity of Pullman, Colfax, and Rosalia to a junction with state route number 90 at Spokane.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c33.pdf?cite=1979%20ex.s.%20c%2033%20§%2010[1979 ex.s. c 33 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2077[1970 ex.s. c 51 § 77]; ]

== 47.17.382 - State route No. 197.
A state highway to be known as state route number 197 is established as follows:

Beginning at the Washington-Oregon boundary on the interstate bridge across the Columbia river in the vicinity of The Dalles, thence northerly to a junction with state route number 14.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c33.pdf?cite=1979%20ex.s.%20c%2033%20§%2011[1979 ex.s. c 33 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c151.pdf?cite=1973%201st%20ex.s.%20c%20151%20§%206[1973 1st ex.s. c 151 § 6]; ]

== 47.17.385 - State route No. 202.
A state highway to be known as state route number 202 is established as follows:

Beginning at a junction with state route number 522 near Bothell, thence southeasterly to a junction with state route number 90 in the vicinity of North Bend.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c199.pdf?cite=1987%20c%20199%20§%2016[1987 c 199 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2078[1970 ex.s. c 51 § 78]; ]

== 47.17.390 - State route No. 203.
A state highway to be known as state route number 203 is established as follows:

Beginning at a junction with state route number 202 at Fall City, thence northerly by the most feasible route by way of Duvall to a junction with state route number 2 at Monroe.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2079[1970 ex.s. c 51 § 79]; ]

== 47.17.395 - State route No. 204.
A state highway to be known as state route number 204 is established as follows:

Beginning at a junction with state route number 2 in the vicinity east of Everett, thence northeasterly to a junction with state route number 9.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c199.pdf?cite=1987%20c%20199%20§%2017[1987 c 199 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2080[1970 ex.s. c 51 § 80]; ]

== 47.17.400 - State route No. 205.
A state highway to be known as state route number 205 is established as follows:

Beginning at the Washington-Oregon boundary line in the vicinity east of Vancouver, thence northwesterly to a junction with state route number 5 in the vicinity of Salmon Creek, north of Vancouver.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2081[1970 ex.s. c 51 § 81]; ]

== 47.17.405 - State route No. 206.
A state highway to be known as state route number 206 is established as follows:

Beginning at a junction with state route number 2 in the vicinity north of Mead, thence northeasterly to the entrance to Mt. Spokane State Park.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c199.pdf?cite=1987%20c%20199%20§%2018[1987 c 199 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2082[1970 ex.s. c 51 § 82]; ]

== 47.17.410 - State route No. 207.
A state highway to be known as state route number 207 is established as follows:

Beginning at a junction with state route number 2 in the vicinity north of Winton, thence northerly to Lake Wenatchee state park.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2021[1991 c 342 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2083[1970 ex.s. c 51 § 83]; ]

== 47.17.416 - State route No. 211.
A state highway to be known as state route number 211 is established as follows:

Beginning at a junction with state route number 2 southwest of Newport, thence northerly by the most feasible route by way of Sacheen Lake to a junction with state route number 20 at Usk.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975c63.pdf?cite=1975%20c%2063%20§%2010[1975 c 63 § 10]; ]

== 47.17.417 - State route No. 213.
A state highway to be known as state route number 213 is established as follows:

Beginning at a junction with state route number 97 in the vicinity of Malott, thence northeasterly to a junction with state route number 20 southwest of Okanogan. Until such time as this route is actually constructed on the location adopted by the department, no county roads may be maintained or improved by the department as a temporary route.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%20134[1984 c 7 § 134]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c151.pdf?cite=1973%201st%20ex.s.%20c%20151%20§%2018[1973 1st ex.s. c 151 § 18]; ]

== 47.17.419 - State route No. 215.
A state highway to be known as state route number 215 is established as follows:

Beginning at a junction with state route number 20 in the vicinity of Okanogan, thence northeasterly on the west side of the Okanagan river to a junction with state route number 97 north of Omak.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c151.pdf?cite=1973%201st%20ex.s.%20c%20151%20§%2019[1973 1st ex.s. c 151 § 19]; ]

== 47.17.425 - State route No. 221.
A state highway to be known as state route number 221 is established as follows:

Beginning at a junction with state route number 14 in the vicinity of Patterson, thence northerly to a junction with state route number 22 in the vicinity of Prosser.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2086[1970 ex.s. c 51 § 86]; ]

== 47.17.430 - State route No. 223.
A state highway to be known as state route number 223 is established as follows:

Beginning at a junction with state route number 22 in the vicinity southeast of Toppenish, thence easterly to a junction with state route number 12 in the vicinity of Granger. The establishment of state route number 223 as defined in this section shall be effective July 1, 1965.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2087[1970 ex.s. c 51 § 87]; ]

== 47.17.435 - State route No. 224.
A state highway to be known as state route number 224 is established as follows:

Beginning at a junction with state route number 82 at Kiona, thence northeasterly to a junction with state route number 240 at Richland.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c199.pdf?cite=1987%20c%20199%20§%2019[1987 c 199 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2088[1970 ex.s. c 51 § 88]; ]

== 47.17.436 - State route No. 225.
A state highway to be known as state route number 225 is established as follows:

Beginning at a junction with state route number 224 in Kiona, thence northeasterly by way of Benton City to a junction with state route number 240 near Horn Rapids dam.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2022[1991 c 342 § 22]; ]

== 47.17.440 - State route No. 230.
A state highway to be known as state route number 230 is established as follows:

Beginning at a junction with state route number 90 in the vicinity of Ritzville, thence easterly by the most feasible route to a junction with state route number 23 in the vicinity of Ewan.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2089[1970 ex.s. c 51 § 89]; ]

== 47.17.445 - State route No. 231.
A state highway to be known as state route number 231 is established as follows:

Beginning at a junction with state route number 23 in the vicinity northwest of Sprague, thence northerly by way of Edwall to a junction with state route number 2 in the vicinity west of Reardan; also

Beginning at a junction with state route number 2 in the vicinity of Reardan, thence northerly by way of Long Lake across the Spokane river, thence northeasterly by way of Springdale to a junction with state route number 395 in the vicinity of Chewelah.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2090[1970 ex.s. c 51 § 90]; ]

== 47.17.455 - State route No. 240.
A state highway to be known as state route number 240 is established as follows:

Beginning at a junction with state route number 24 in the vicinity east of Cold Creek, thence southeasterly by the most feasible route across the Atomic Energy Commission Reservation to a junction with state route number 224 at Richland; also

From that junction with state route number 224 at Richland, thence southerly to a junction with state route number 182 at Richland; also

From a junction with state route number 182 at Richland southeasterly to a junction with state route number 395 at Kennewick. The secretary may enter into negotiations with appropriate federal agencies to secure right-of-way for the highway over and across the Atomic Energy Commission Reservation.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c177.pdf?cite=1985%20c%20177%20§%203[1985 c 177 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%20135[1984 c 7 § 135]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2092[1970 ex.s. c 51 § 92]; ]

== 47.17.460 - State route No. 241.
A state highway to be known as state route number 241 is established as follows:

Beginning at a junction with state route number 22 in Mabton, thence northerly and northeasterly by way of Sunnyside to a junction with state route number 24.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2023[1991 c 342 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c199.pdf?cite=1987%20c%20199%20§%2020[1987 c 199 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2093[1970 ex.s. c 51 § 93]; ]

== 47.17.465 - State route No. 243.
A state highway to be known as state route number 243 is established as follows:

Beginning at a junction with state route number 24 north of its crossing of the Columbia river, thence westerly and northerly by way of Arrowsmith and Beverly to a junction with state route number 26 south of the Columbia river bridge at Vantage.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2094[1970 ex.s. c 51 § 94]; ]

== 47.17.475 - State route No. 260.
A state highway to be known as state route number 260 is established as follows:

Beginning at a junction with state route number 17 west of Connell, thence easterly to a junction with state route number 395 in the vicinity of Connell, thence northeasterly by way of Kahlotus to a junction with state route number 26 at Washtucna.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2096[1970 ex.s. c 51 § 96]; ]

== 47.17.480 - State route No. 261.
A state highway to be known as state route number 261 is established as follows:

Beginning at a junction with state route number 12 at Delaney, thence northwesterly to a junction with state route number 260 in the vicinity of McAdam; also

Beginning at a junction with state route number 26 at Washtucna, thence northerly to a junction with state route number 90 at Ritzville.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c199.pdf?cite=1987%20c%20199%20§%2021[1987 c 199 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c73.pdf?cite=1971%20ex.s.%20c%2073%20§%2012[1971 ex.s. c 73 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2097[1970 ex.s. c 51 § 97]; ]

== 47.17.481 - State route No. 262.
A state highway to be known as state route number 262 is established as follows:

Beginning at a junction with state route number 26 east of Royal City, thence northerly and easterly to a junction with state route number 17 west of Warden.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2024[1991 c 342 § 24]; ]

== 47.17.482 - State route No. 263.
A state highway to be known as state route number 263 is established as follows:

Beginning at the port of Windust, thence easterly and northerly to a junction with state route number 260 in Kahlotus.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2025[1991 c 342 § 25]; ]

== 47.17.485 - State route No. 270.
A state highway to be known as state route number 270 is established as follows:

Beginning at a junction with state route number 195 at Pullman, thence easterly by the most feasible route to a point on the Washington-Idaho boundary line.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2098[1970 ex.s. c 51 § 98]; ]

== 47.17.490 - State route No. 271.
A state highway to be known as state route number 271 is established as follows:

Beginning at a junction with state route number 27 in the vicinity of Oakesdale, thence northwesterly to a junction with state route number 195 in the vicinity south of Rosalia.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%2099[1970 ex.s. c 51 § 99]; ]

== 47.17.495 - State route No. 272.
A state highway to be known as state route number 272 is established as follows:

Beginning at a junction with state route number 195 at Colfax, thence easterly to a junction with state route number 27 at Palouse; also

Beginning at a junction with state route number 27 at Palouse, thence northeasterly by the most feasible route to a point on the Washington-Idaho boundary line.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20100[1970 ex.s. c 51 § 100]; ]

== 47.17.500 - State route No. 274.
A state highway to be known as state route number 274 is established as follows:

Beginning at a junction with state route number 27 at Tekoa, thence easterly to the Washington-Idaho boundary line.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20101[1970 ex.s. c 51 § 101]; ]

== 47.17.503 - State route No. 278.
A state highway to be known as state route number 278 is established as follows:

Beginning at a junction with state route number 27 in Rockford, thence easterly and southerly to the Washington-Idaho boundary.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2026[1991 c 342 § 26]; ]

== 47.17.505 - State route No. 281.
A state highway to be known as state route number 281 is established as follows:

Beginning at a junction with state route number 90 in the vicinity of George, thence northerly to a junction with state route number 28 at Quincy; also

Beginning at a junction with state route number 281 at a point north of the above described junction on state route number 90, thence in a southeasterly direction to a junction with state route number 90 in the vicinity east of George, some 1.6 miles more or less, resulting in a wye connection between state route number 281 and state route number 90.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c73.pdf?cite=1971%20ex.s.%20c%2073%20§%2013[1971 ex.s. c 73 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20102[1970 ex.s. c 51 § 102]; ]

== 47.17.510 - State route No. 282.
A state highway to be known as state route number 282 is established as follows:

Beginning at a junction with state route number 28 in the vicinity of Ephrata, thence southeasterly to a junction with state route number 17 in the vicinity of Rocky Ford creek.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20103[1970 ex.s. c 51 § 103]; ]

== 47.17.515 - State route No. 283.
A state highway to be known as state route number 283 is established as follows:

Beginning at a junction with state route number 281 in the vicinity of Burke Junction, thence northeasterly by the most feasible route to a junction with state route number 28 in the vicinity west of Ephrata.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20104[1970 ex.s. c 51 § 104]; ]

== 47.17.517 - State route No. 285.
A state highway to be known as state route number 285 is established as follows:

Beginning at a junction with state route number 28 in East Wenatchee, thence westerly across the Columbia river and northwesterly to a junction with state route number 2 in Wenatchee.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2027[1991 c 342 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c224.pdf?cite=1977%20ex.s.%20c%20224%20§%201[1977 ex.s. c 224 § 1]; ]

== 47.17.520 - State route No. 290.
A state highway to be known as state route number 290 is established as follows:

Beginning at a junction with state route number 90 in Spokane, thence northeasterly by way of Millwood, Trentwood, and Newman Lake to the termination of Idaho state highway number 53 at the Washington-Idaho boundary line.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5356.SL.pdf?cite=2005%20c%2014%20§%201[2005 c 14 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c6.pdf?cite=1977%20ex.s.%20c%206%20§%201[1977 ex.s. c 6 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20105[1970 ex.s. c 51 § 105]; ]

== 47.17.525 - State route No. 291.
A state highway to be known as state route number 291 is established as follows:

Beginning at a junction with state route number 2 in Spokane, thence northwesterly along the north bank of the Spokane river to the vicinity of Tumtum; and thence southwesterly along the north shore of Long Lake to a junction with state route number 231 in the vicinity of the Little Falls Dam.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c180.pdf?cite=1983%20c%20180%20§%204[1983 c 180 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20106[1970 ex.s. c 51 § 106]; ]

== 47.17.530 - State route No. 292.
A state highway to be known as state route number 292 is established as follows:

Beginning at a junction with state route number 231 at Springdale, thence easterly to a junction with state route number 395 in the vicinity of Loon Lake.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20107[1970 ex.s. c 51 § 107]; ]

== 47.17.540 - State route No. 300.
A state highway to be known as state route number 300 is established as follows:

Beginning at the western boundary of the Belfair State Park, thence generally easterly to a junction with state route number 3 at Belfair.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20109[1970 ex.s. c 51 § 109]; ]

== 47.17.545 - State route No. 302.
A state highway to be known as state route number 302 is established as follows:

Beginning at a junction with state route number 3 in the vicinity of Allyn, thence easterly to a junction with state route number 16 in the vicinity of Purdy.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c199.pdf?cite=1987%20c%20199%20§%2022[1987 c 199 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20110[1970 ex.s. c 51 § 110]; ]

== 47.17.550 - State route No. 303.
A state highway to be known as state route number 303 is established as follows:

Beginning at a junction with state route number 304 at Bremerton, thence by way of the Warren Avenue bridge across the Port Washington Narrows northerly to a junction with state route number 3 in the vicinity north of Silverdale.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2028[1991 c 342 § 28]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c73.pdf?cite=1971%20ex.s.%20c%2073%20§%2014[1971 ex.s. c 73 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20111[1970 ex.s. c 51 § 111]; ]

== 47.17.556 - State route No. 304.
A state highway to be known as state route number 304 is established as follows:

Beginning at a junction with state route number 3 in Bremerton, thence easterly to the ferry terminal in Bremerton; also

From the state ferry terminal at Bremerton via the state ferry system easterly to the junction with state route number 519 at the state ferry terminal in Seattle.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2618-S.SL.pdf?cite=1994%20c%20209%20§%206[1994 c 209 § 6]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2023-S.SL.pdf?cite=1993%20c%20430%20§%204[1993 c 430 § 4]; ]

== 47.17.560 - State route No. 305.
A state highway to be known as state route number 305 is established as follows:

Beginning at the junction with state route number 519 at the state ferry terminal in Seattle, thence via the state ferry system northwesterly to the state ferry terminal at Bainbridge Island; also

From the state ferry terminal at Bainbridge Island, thence northerly by the most feasible route to the north end of Bainbridge Island, across Agate Pass, thence northwesterly by the most feasible route to a junction with state route number 3 in the vicinity north of Poulsbo.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2618-S.SL.pdf?cite=1994%20c%20209%20§%207[1994 c 209 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20113[1970 ex.s. c 51 § 113]; ]

== 47.17.566 - State route No. 307.
A state highway to be known as state route number 307 is established as follows:

Beginning at a junction with state route number 305 at Poulsbo, thence northeasterly to a junction with state route number 104 near Miller Lake.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2029[1991 c 342 § 29]; ]

== 47.17.567 - State route No. 308.
A state highway to be known as state route number 308 is established as follows:

Beginning at a junction with state route number 3, thence easterly to Keyport.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c199.pdf?cite=1987%20c%20199%20§%2023[1987 c 199 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c73.pdf?cite=1971%20ex.s.%20c%2073%20§%2015[1971 ex.s. c 73 § 15]; ]

== 47.17.569 - State route No. 310.
A state highway to be known as state route number 310 is established as follows:

Beginning at a junction with state route number 3 near Oyster Bay, thence easterly to a junction with state route number 304 in Bremerton.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2030[1991 c 342 § 30]; ]

== 47.17.571 - State route No. 339.
A state highway to be known as state route number 339 is established as follows:

Beginning at the junction of state route number 160 at the state ferry terminal at Vashon Heights, thence via the state ferry system northeasterly to the junction with state route number 519 at the state ferry terminal in Seattle.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2618-S.SL.pdf?cite=1994%20c%20209%20§%209[1994 c 209 § 9]; ]

== 47.17.575 - State route No. 395.
A state highway to be known as state route number 395 is established as follows:

Beginning at a junction with state route number 82 at Kennewick, northerly to a junction with state route number 182 at Pasco; also

From a junction with state route number 182 at Pasco, thence northeasterly by way of the vicinity of Mesa and Connell to a junction with state route number 90 at Ritzville; also

From a junction with state route number 2 in the vicinity north of Spokane, thence northerly by way of the vicinity of Colville and Kettle Falls to the international boundary line in the vicinity of Laurier.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c177.pdf?cite=1985%20c%20177%20§%204[1985 c 177 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c33.pdf?cite=1979%20ex.s.%20c%2033%20§%2013[1979 ex.s. c 33 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20116[1970 ex.s. c 51 § 116]; ]

== 47.17.577 - State route No. 397.
A state highway to be known as state route number 397 is established as follows:

Beginning at state route number 82 at exit 114, thence easterly, northwesterly, and northerly across the Columbia River, thence easterly and northerly to a junction with state route number 395 in Pasco.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1000.SL.pdf?cite=2009%20c%20184%20§%201[2009 c 184 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2023-S.SL.pdf?cite=1993%20c%20430%20§%205[1993 c 430 § 5]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2031[1991 c 342 § 31]; ]

== 47.17.580 - State route No. 401.
A state highway to be known as state route number 401 is established as follows:

Beginning at Point Ellice on state route number 101, thence easterly and northerly to a junction with state route number 4 in the vicinity north of Naselle.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20117[1970 ex.s. c 51 § 117]; ]

== 47.17.595 - State route No. 405.
A state highway to be known as state route number 405 is established as follows:

Beginning at a junction with state route number 5 in the vicinity south of Seattle, thence northeasterly to Renton, thence northerly east of Lake Washington to a junction with state route number 5 north of Seattle.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20120[1970 ex.s. c 51 § 120]; ]

== 47.17.605 - State route No. 409.
A state highway to be known as state route number 409 is established as follows:

Beginning at the South Ferry landing, as now located, or as it may be relocated, on the south side of Puget Island, thence generally northerly by the most feasible route to the Puget Island bridge, thence crossing said bridge to a junction with state route number 4 at the north approach of said bridge at the town of Cathlamet: PROVIDED, That the state of Washington shall not assume or pay any bond or bonds outstanding against said bridge, or interest on said bonds, but said bond or bonds, and interest thereon, shall remain the sole obligation of the obligors named on said bonds.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20122[1970 ex.s. c 51 § 122]; ]

== 47.17.610 - State route No. 410.
A state highway to be known as state route number 410 is established as follows:

Beginning at a junction with state route number 167 at Sumner, thence easterly by way of Buckley, Enumclaw, and Chinook Pass, to a junction with state route number 12 northwest of Yakima: PROVIDED, That until such time as state route number 167 is constructed and opened to traffic on an anticipated ultimate alignment from a junction with state route number 5 near Tacoma easterly to Sumner on the north side of the Puyallup river, the public highway between state route number 5 in Tacoma and state route number 161 in Sumner, on the south side of the Puyallup river, shall remain on the state highway system.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c199.pdf?cite=1987%20c%20199%20§%2024[1987 c 199 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c151.pdf?cite=1973%201st%20ex.s.%20c%20151%20§%208[1973 1st ex.s. c 151 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20123[1970 ex.s. c 51 § 123]; ]

== 47.17.615 - State route No. 411.
A state highway to be known as state route number 411 is established as follows:

Beginning at a junction with state route number 432 in Longview, thence northerly to a junction with state route number 5 at Castle Rock.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2032[1991 c 342 § 32]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20124[1970 ex.s. c 51 § 124]; ]

== 47.17.625 - State route No. 432.
A state highway to be known as state route number 432 is established as follows:

Beginning at a junction with state route number 4 in the vicinity west of Longview, thence southeasterly to a junction with state route number 5 south of Kelso.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2033[1991 c 342 § 33]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20126[1970 ex.s. c 51 § 126]; ]

== 47.17.630 - State route No. 433.
A state highway to be known as state route number 433 is established as follows:

Beginning at the Washington-Oregon boundary on the interstate bridge at Longview, thence northerly to a junction with state route number 432 in Longview.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2034[1991 c 342 § 34]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c199.pdf?cite=1987%20c%20199%20§%2025[1987 c 199 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20127[1970 ex.s. c 51 § 127]; ]

== 47.17.635 - State route No. 500.
A state highway to be known as state route number 500 is established as follows:

Beginning at a junction with state route number 5 at Vancouver, thence northeasterly to Orchards, thence southeasterly to a junction with state route number 14 at Camas.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20128[1970 ex.s. c 51 § 128]; ]

== 47.17.640 - State route No. 501—Erwin O. Rieger Memorial Highway.
A state highway to be known as state route number 501 is established as follows:

Beginning at a junction with state route number 5 at Vancouver, thence northerly by way of Lower River Road and an extension thereof to Ridgefield, thence easterly to a junction with state route number 5 in the vicinity south of La Center. That portion of state route number 501 from the northerly junction of N.W. Lower River Road to the Ridgefield city limits is designated "the Erwin O. Rieger Memorial Highway." The department may enter into an agreement with the Port of Vancouver, Clark county, or the United States Army Engineers, or any combination thereof, to obtain material dredged from the Columbia river and have it stockpiled at no expense to the state.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1946.SL.pdf?cite=1991%20c%2078%20§%201[1991 c 78 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%20136[1984 c 7 § 136]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20129[1970 ex.s. c 51 § 129]; ]

== 47.17.645 - State route No. 502.
A state highway to be known as state route number 502 is established as follows:

Beginning at a junction with state route number 5 in the vicinity north of Vancouver, thence easterly to a junction with state route number 503 at Battle Ground.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20130[1970 ex.s. c 51 § 130]; ]

== 47.17.650 - State route No. 503.
A state highway to be known as state route number 503 is established as follows:

Beginning at a junction with state route number 500 at Orchards, thence northerly to a junction with state route number 502 at Battle Ground, thence northerly to Amboy, thence northeasterly by way of Cougar to the Cowlitz-Skamania county line; also

Beginning at a junction with state route number 503 in the vicinity of Yale, thence westerly to a junction with state route number 5 in the vicinity of Woodland.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2035[1991 c 342 § 35]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975c63.pdf?cite=1975%20c%2063%20§%206[1975 c 63 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20131[1970 ex.s. c 51 § 131]; ]

== 47.17.655 - State route No. 504—Spirit Lake Memorial Highway.
A state highway to be known as state route number 504, hereby designated the Spirit Lake Memorial Highway, dedicated to the memory of those who lost their lives in the 1980 eruption of Mt. St. Helens, is established as follows:

Beginning at a junction with state route number 5 in the vicinity north of Castle Rock, thence easterly along the north shore of Silver Lake by way of Silverlake and Toutle, past a junction with state route number 505, thence by way of Kid Valley and St. Helens to the former Spirit Lake.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c82.pdf?cite=1982%20c%2082%20§%201[1982 c 82 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20132[1970 ex.s. c 51 § 132]; ]

== 47.17.660 - State route No. 505.
A state highway to be known as state route number 505 is established as follows:

Beginning in Winlock, thence via Toledo, easterly and southerly to a junction with state route number 504 in the vicinity north of Toutle.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2036[1991 c 342 § 36]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20133[1970 ex.s. c 51 § 133]; ]

== 47.17.665 - State route No. 506.
A state highway to be known as state route number 506 is established as follows:

Beginning at Ryderwood, thence by way of Vader northeasterly to a junction with state route number 5 west of Toledo.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20134[1970 ex.s. c 51 § 134]; ]

== 47.17.670 - State route No. 507.
A state highway to be known as state route number 507 is established as follows:

Beginning at a junction with state route number 5 in Centralia, thence northerly by the most feasible route by way of Bucoda to Tenino, thence northeasterly by way of Rainier, Yelm and McKenna to a junction with state route number 7 in the vicinity south of Tacoma.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20135[1970 ex.s. c 51 § 135]; ]

== 47.17.675 - State route No. 508.
A state highway to be known as state route number 508 is established as follows:

Beginning at a junction with state route number 5 south of Chehalis, thence easterly by way of Onalaska to a junction with state route number 7 at Morton.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20136[1970 ex.s. c 51 § 136]; ]

== 47.17.680 - State route No. 509.
A state highway to be known as state route number 509 is established as follows:

Beginning at a junction with state route number 705 at Tacoma, thence northeasterly to a junction with state route number 99 in the vicinity of Redondo; also

From a junction with state route number 516 at Des Moines, thence northerly to a junction with state route number 99 in Seattle.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2037[1991 c 342 § 37]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c33.pdf?cite=1979%20ex.s.%20c%2033%20§%2014[1979 ex.s. c 33 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20137[1970 ex.s. c 51 § 137]; ]

== 47.17.685 - State route No. 510.
A state highway to be known as state route number 510 is established as follows:

Beginning at a junction with state route number 5, thence southeasterly via St. Clair to a junction with state route number 507 at Yelm.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20138[1970 ex.s. c 51 § 138]; ]

== 47.17.690 - State route No. 512.
A state highway to be known as state route number 512 is established as follows:

Beginning at a junction with state route number 5 south of Tacoma, thence easterly to a junction with state route number 7 south of Tacoma, thence easterly to a junction with state route number 167 in the vicinity of Puyallup.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20139[1970 ex.s. c 51 § 139]; ]

== 47.17.695 - State route No. 513.
A state highway to be known as state route number 513 is established as follows:

Beginning at a junction with state route number 520 in Seattle, thence northerly and easterly to the vicinity of Sand Point.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2038[1991 c 342 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c73.pdf?cite=1971%20ex.s.%20c%2073%20§%2016[1971 ex.s. c 73 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20140[1970 ex.s. c 51 § 140]; ]

== 47.17.705 - State route No. 515.
A state highway to be known as state route number 515 is established as follows:

Beginning at a junction with state route number 516 in the vicinity east of Kent, thence northerly to a junction with state route number 900 in Renton.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20142[1970 ex.s. c 51 § 142]; ]

== 47.17.710 - State route No. 516.
A state highway to be known as state route number 516 is established as follows:

Beginning at a junction with state route number 509 in the vicinity south of Des Moines, thence southeasterly to a junction with state route number 5; also

From that junction with state route number 5, thence easterly to a junction with state route number 167 in Kent, thence easterly to a junction with state route number 169 south of Maple Valley.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20143[1970 ex.s. c 51 § 143]; ]

== 47.17.715 - State route No. 518.
A state highway to be known as state route number 518 is established as follows:

Beginning at a junction with state route number 509 near Sunnydale, thence easterly to a junction with state route number 5 in the vicinity of Seattle.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20144[1970 ex.s. c 51 § 144]; ]

== 47.17.717 - State route No. 519.
A state highway to be known as state route number 519 is established as follows:

Beginning at a junction with state route number 90 in Seattle, thence westerly, and northerly to the Washington state ferry terminal.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2039[1991 c 342 § 39]; ]

== 47.17.720 - State route No. 520.
A state highway to be known as state route number 520 is established as follows:

Beginning at a junction with state route number 5 in Seattle, thence easterly via the Evergreen Point bridge to a junction with state route number 202 in the vicinity of Redmond.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20145[1970 ex.s. c 51 § 145]; ]

== 47.17.725 - State route No. 522.
A state highway to be known as state route number 522 is established as follows:

Beginning at Seattle in King county, thence easterly by the most feasible route to the north of Lake Washington by way of Bothell to a junction with state route number 202 near Bothell; also

From that junction with state route number 202 near Bothell, thence northeasterly by the most feasible route to a junction with state route number 2 in the vicinity of Monroe.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20146[1970 ex.s. c 51 § 146]; ]

== 47.17.727 - State route No. 523.
A state highway to be known as state route number 523 is established as follows:

Beginning at a junction with state route number 99 and Northeast 145th Street in Seattle, thence easterly to a junction with state route number 522.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2040[1991 c 342 § 40]; ]

== 47.17.730 - State route No. 524.
A state highway to be known as state route number 524 is established as follows:

Beginning at a junction with state route number 104 at Edmonds, thence northeasterly to a junction with state route number 5 in the vicinity of Lynnwood, thence easterly to a junction with state route number 522 near Maltby.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2041[1991 c 342 § 41]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%20137[1984 c 7 § 137]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20147[1970 ex.s. c 51 § 147]; ]

== 47.17.735 - State route No. 525.
A state highway to be known as state route number 525 is established as follows:

Beginning at a junction with state route number 5 in the vicinity south of Everett, thence northwesterly to the state ferry terminal at Mukilteo; also

From the junction with state route number 526 at Mukilteo, thence southerly to a junction with state route number 525; also

From the state ferry terminal at Mukilteo via the state ferry system northerly to the state ferry terminal at Clinton; also

From the state ferry terminal at Clinton, thence northwesterly to a junction with state route number 20 in the vicinity east of Keystone.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6053-S.SL.pdf?cite=2001%20c%20130%20§%201[2001 c 130 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2618-S.SL.pdf?cite=1994%20c%20209%20§%208[1994 c 209 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c151.pdf?cite=1973%201st%20ex.s.%20c%20151%20§%2015[1973 1st ex.s. c 151 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20148[1970 ex.s. c 51 § 148]; ]

== 47.17.740 - State route No. 526.
A state highway to be known as state route number 526 is established as follows:

Beginning at a junction with state route number 525 at Mukilteo, thence easterly to a junction with state route number 5 in the vicinity of its junction with state route number 527.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20149[1970 ex.s. c 51 § 149]; ]

== 47.17.745 - State route No. 527.
A state highway to be known as state route number 527 is established as follows:

Beginning at a junction with state route number 405 in the vicinity of Bothell, thence northerly to a junction with state route number 5 in Everett.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1520.SL.pdf?cite=2011%20c%20201%20§%201[2011 c 201 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20150[1970 ex.s. c 51 § 150]; ]

== 47.17.750 - State route No. 528.
A state highway to be known as state route number 528 is established as follows:

Beginning at a junction with state route number 5 near Marysville, thence easterly to a junction with state route number 9. Until such time as state route number 528 from Marysville to a junction with state route number 9 is actually constructed on the location adopted by the department, no existing city streets or county roads may be maintained or improved by the department as a temporary route of state route number 528.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%20138[1984 c 7 § 138]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c73.pdf?cite=1971%20ex.s.%20c%2073%20§%2018[1971 ex.s. c 73 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20151[1970 ex.s. c 51 § 151]; ]

== 47.17.752 - State route No. 529.
A state highway to be known as state route number 529 is established as follows:

Beginning at a junction with state route number 5 in Everett, thence westerly and northerly through Everett to a junction with state route number 528 in Marysville.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2042[1991 c 342 § 42]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c73.pdf?cite=1971%20ex.s.%20c%2073%20§%2019[1971 ex.s. c 73 § 19]; ]

== 47.17.755 - State route No. 530.
A state highway to be known as state route number 530 is established as follows:

Beginning at a junction with state route number 5 in the vicinity west of Arlington, thence easterly and northerly by way of Darrington to a junction with state route number 20 in the vicinity of Rockport.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2043[1991 c 342 § 43]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c131.pdf?cite=1983%20c%20131%20§%201[1983 c 131 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c73.pdf?cite=1971%20ex.s.%20c%2073%20§%2020[1971 ex.s. c 73 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20152[1970 ex.s. c 51 § 152]; ]

== 47.17.757 - State route No. 531.
A state highway to be known as state route number 531 is established as follows:

Beginning at Wenberg state park, thence northerly and easterly to a junction with state route number 9 in the vicinity north of Marysville.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2044[1991 c 342 § 44]; ]

== 47.17.760 - State route No. 532.
A state highway to be known as state route number 532 is established as follows:

Beginning at a point on Camano Island known as McEacherns Corner, thence easterly over a bridge and by way of Stanwood to a junction with state route number 530 in the vicinity of Stanwood, thence easterly to a junction with state route number 5 in the vicinity east of Stanwood.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20153[1970 ex.s. c 51 § 153]; ]

== 47.17.765 - State route No. 534.
A state highway to be known as state route number 534 is established as follows:

Beginning at a junction with state route number 5 at Conway, thence southeasterly to a junction with state route number 9 at McMurray.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20154[1970 ex.s. c 51 § 154]; ]

== 47.17.770 - State route No. 536.
A state highway to be known as state route number 536 is established as follows:

Beginning at a junction with state route number 20 at Fredonia, thence easterly to a junction with state route number 5 at Mt. Vernon.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c151.pdf?cite=1973%201st%20ex.s.%20c%20151%20§%2016[1973 1st ex.s. c 151 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20155[1970 ex.s. c 51 § 155]; ]

== 47.17.780 - State route No. 538.
A state highway to be known as state route number 538 is established as follows:

Beginning at a junction with state route number 5 at Mt. Vernon, thence easterly to a junction with state route number 9.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20157[1970 ex.s. c 51 § 157]; ]

== 47.17.785 - State route No. 539.
A state highway to be known as state route number 539 is established as follows:

Beginning at a junction with state route number 5 at Bellingham, thence northerly to the international boundary in the vicinity east of Delta.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20158[1970 ex.s. c 51 § 158]; ]

== 47.17.795 - State route No. 542.
A state highway to be known as state route number 542 is established as follows:

Beginning at a junction with state route number 5 at Bellingham, thence easterly to a point in the vicinity of Austin Pass in Whatcom county.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20160[1970 ex.s. c 51 § 160]; ]

== 47.17.797 - State route No. 543.
A state highway to be known as state route number 543 is established as follows:

Beginning at a junction with state route number 5 in the vicinity of Blaine, thence northerly to the international boundary.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c73.pdf?cite=1971%20ex.s.%20c%2073%20§%2022[1971 ex.s. c 73 § 22]; ]

== 47.17.800 - State route No. 544.
A state highway to be known as state route number 544 is established as follows:

Beginning at a junction with state route number 539 in the vicinity of Wiser lake, thence northeasterly by way of Everson to a junction with state route number 9 in the vicinity of Nooksack.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20161[1970 ex.s. c 51 § 161]; ]

== 47.17.805 - State route No. 546.
A state highway to be known as state route number 546 is established as follows:

Beginning at a junction with state route number 539 approximately 2.7 miles south of the international boundary, thence easterly by way of Van Buren to a junction with state route number 9.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20162[1970 ex.s. c 51 § 162]; ]

== 47.17.806 - State route No. 547.
A state highway to be known as state route number 547 is established as follows:

Beginning at the junction of state route number 542 in the vicinity of Kendall, thence northwesterly to a junction with state route number 9 at Sumas.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c197.pdf?cite=1984%20c%20197%20§%202[1984 c 197 § 2]; ]

== 47.17.807 - State route No. 548.
A state highway to be known as state route number 548 is established as follows:

Beginning at a junction with state route number 5 in the vicinity north of Ferndale, thence westerly and northerly to a junction with state route number 5 in Blaine.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2045[1991 c 342 § 45]; ]

== 47.17.808 - State route No. 599.
A state highway to be known as state route number 599 is established as follows:

Beginning in the vicinity south of Seattle at a junction with state route number 5, thence in a northwesterly direction west of the Duwamish river to a junction with state route number 99 in the vicinity of South 118 street south of Seattle.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c73.pdf?cite=1971%20ex.s.%20c%2073%20§%2023[1971 ex.s. c 73 § 23]; ]

== 47.17.815 - State route No. 702.
A state highway to be known as state route number 702 is established as follows:

Beginning at a junction with state route number 507 at McKenna, thence easterly to a junction with state route number 7.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20164[1970 ex.s. c 51 § 164]; ]

== 47.17.818 - State route No. 704.
A state highway to be known as state route number 704 is established as follows: Beginning at a junction with state route number 5 in south Pierce county, thence easterly across Fort Lewis to a junction with state route number 7.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6140-S2.SL.pdf?cite=2002%20c%2056%20§%20304[2002 c 56 § 304]; ]

== 47.17.819 - State route No. 705.
A state highway to be known as state route number 705 is established as follows:

Beginning at a junction with state route number 5 in Tacoma, thence northerly to a junction with Schuster Parkway in the Tacoma central business district.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c33.pdf?cite=1979%20ex.s.%20c%2033%20§%2015[1979 ex.s. c 33 § 15]; ]

== 47.17.820 - State route No. 706—Road to Paradise.
A state highway to be known as state route number 706, designated the Road to Paradise, is established as follows:

Beginning at a junction with state route number 7 at Elbe, thence easterly to a southwest entrance to Mt. Rainier National Park.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c97.pdf?cite=1990%20c%2097%20§%201[1990 c 97 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20165[1970 ex.s. c 51 § 165]; ]

== 47.17.821 - State route No. 730.
A state highway to be known as state route number 730 is established as follows:

Beginning at the Washington-Oregon boundary line, thence northeasterly to a junction with state route number 12 south of Wallula.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c177.pdf?cite=1985%20c%20177%20§%205[1985 c 177 § 5]; ]

== 47.17.823 - State route No. 821.
A state highway to be known as state route number 821 is established as follows:

Beginning at a junction with state route number 82 in the vicinity north of Yakima, thence northerly to a junction with state route number 82 south of Ellensburg.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c151.pdf?cite=1973%201st%20ex.s.%20c%20151%20§%209[1973 1st ex.s. c 151 § 9]; ]

== 47.17.824 - State route No. 823.
A state highway to be known as state route number 823 is established as follows:

Beginning at the junction of state route number 82 in the vicinity of Selah northerly by way of Selah and easterly to a junction with state route number 821 in the vicinity of the firing center interchange.

Before award of any construction contract for improvements to state route number 823 under either program A or program C, the department of transportation shall secure a portion of the construction cost from the city of Selah or Yakima county, or both.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2046[1991 c 342 § 46]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c197.pdf?cite=1984%20c%20197%20§%203[1984 c 197 § 3]; ]

== 47.17.825 - State route No. 900.
A state highway to be known as state route number 900 is established as follows:

Beginning at a junction with state route number 5 in Seattle near the Duwamish River, thence southerly by way of Renton to a junction with state route number 90 in the vicinity of Issaquah.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2047[1991 c 342 § 47]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c33.pdf?cite=1979%20ex.s.%20c%2033%20§%2016[1979 ex.s. c 33 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20166[1970 ex.s. c 51 § 166]; ]

== 47.17.835 - State route No. 902.
A state highway to be known as state route number 902 is established as follows:

Beginning at a junction with state route number 90, thence northwesterly, northerly, northeasterly, and easterly, via the town of Medical Lake, to a junction with state route number 90 at a point approximately three miles northeast of Four Lakes.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2049[1991 c 342 § 49]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20168[1970 ex.s. c 51 § 168]; ]

== 47.17.840 - State route No. 903.
A state highway to be known as state route number 903 is established as follows:

Beginning at a junction with state route number 970 in the vicinity of Cle Elum, thence northwesterly by way of Cle Elum and Roslyn to the National Forest boundary in the vicinity of Lake Cle Elum.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975c63.pdf?cite=1975%20c%2063%20§%207[1975 c 63 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20169[1970 ex.s. c 51 § 169]; ]

== 47.17.845 - State route No. 904.
A state highway to be known as state route number 904 is established as follows:

Beginning at a junction with state route number 90 in the vicinity of Tyler, thence northeasterly via Cheney to a junction with state route number 90 in the vicinity of Four Lakes.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c73.pdf?cite=1971%20ex.s.%20c%2073%20§%2025[1971 ex.s. c 73 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20170[1970 ex.s. c 51 § 170]; ]

== 47.17.850 - State route No. 906.
A state highway to be known as state route number 906 is established as follows:

Beginning at a junction with state route number 90 at the West Summit interchange of Snoqualmie Pass, thence along the alignment of the state route number 90 as it existed on May 11, 1967, in a southeasterly direction to a junction with state route number 90 at the Hyak interchange.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5513.SL.pdf?cite=2005%20c%20319%20§%20129[2005 c 319 § 129]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%20139[1984 c 7 § 139]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c235.pdf?cite=1977%20ex.s.%20c%20235%20§%2016[1977 ex.s. c 235 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c73.pdf?cite=1971%20ex.s.%20c%2073%20§%2026[1971 ex.s. c 73 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20171[1970 ex.s. c 51 § 171]; ]

== 47.17.917 - State route No. 970.
A state highway to be known as state route number 970 is established as follows:

Beginning at a junction with state route number 90 in the vicinity of Cle Elum, thence northeasterly by way of Teanaway to a junction with state route number 97 in the vicinity of Virden.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975c63.pdf?cite=1975%20c%2063%20§%2012[1975 c 63 § 12]; ]

== 47.17.919 - State route No. 971.
A state highway to be known as state route number 971 is established as follows:

Beginning at a junction with state route number 97-alternate in the vicinity of Winesap, thence northerly to Lake Chelan state park, thence southeasterly to a junction with state route number 97-alternate west of Chelan.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2051[1991 c 342 § 51]; ]

== 47.17.960 - Local bridges—Department responsibility.
Although not part of the state highway system, the bridges designated in this section shall remain the continuing responsibility of the Washington state department of transportation. Continuing responsibility includes all structural maintenance, repair, and replacement of the substructure, superstructure, and roadway deck. Local agencies are responsible for snow and ice control, sweeping, striping, lane marking, and channelization.

State of Washington Inventory ofBridges and StructuresFacility (SWIBS) NumberS. Fork Skykomish River BridgeWN-002000487032Manette BridgeWN-303250032700Grays River Bridge (Rosburg)WN-403000064300Elochoman BridgeWN-407000023300

State of Washington Inventory of

Bridges and Structures

Facility

 

(SWIBS) Number

S. Fork Skykomish River Bridge

WN-002000487032

Manette Bridge

WN-303250032700

Grays River Bridge (Rosburg)

WN-403000064300

Elochoman Bridge

WN-407000023300

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2055[1991 c 342 § 55]; ]

== 47.17.990 - Construction—Refunds to counties composed of islands.
Nothing in this chapter precludes the refund of all vehicle license fees and motor vehicle fuel tax directly or indirectly paid by the residents of those counties composed entirely of islands and that have neither a fixed physical connection with the mainland nor any state highways on any of the islands of which they are composed, as authorized under RCW 46.68.080.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2618-S.SL.pdf?cite=1994%20c%20209%20§%2010[1994 c 209 § 10]; ]

