= 47.14 - Right-of-way donations.
:toc:

== 47.14.010 - Legislative finding, intent.
The legislature finds that in numerous areas throughout the state, rapid expansion of residential, commercial, industrial, and business activities is producing increased traffic levels. The legislature further finds that many property owners have exhibited a willingness to donate real property or property rights for transportation improvements to accommodate such increases in traffic. The legislature recognizes that the cost of right-of-way acquisition is often a significant, and even a prohibitive cost element in many transportation improvement projects.

The legislature seeks to encourage the voluntary donation of right-of-way to the state, counties, cities, and towns for transportation improvements recognizing that such donations can result in direct benefits to property owners, developers, and the community at large.

It is the intent of the legislature to further facilitate the department of transportation's authority under RCW 47.12.010, 47.24.030, and 47.52.050 to accept donations of right-of-way for state transportation purposes. The legislature further intends to facilitate the authority of a city, town, or county to accept donations of right-of-way for other transportation purposes.

The legislature therefore declares it to be in the best interest and welfare of the citizens of Washington for the state department of transportation, and for counties, cities, and towns to actively foster and encourage donations of right-of-way by willing donors in all areas where transportation improvements are to be made. In addition, and in lieu of monetary compensation for property needed for right-of-way purposes, the legislature seeks to provide incentives to potential donors such as are set forth in RCW 47.14.030 and 47.14.040.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c267.pdf?cite=1987%20c%20267%20§%201[1987 c 267 § 1]; ]

== 47.14.020 - Definitions.
The definitions set forth in this section apply throughout this chapter.

. "Right-of-way" means the area of land designated for transportation purposes.

. "Airspace" means the space above and below the gradeline of all highways, roads, and streets, and the area alongside the traveled way and within approved right-of-way lines.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c267.pdf?cite=1987%20c%20267%20§%202[1987 c 267 § 2]; ]

== 47.14.030 - Credit against transportation benefit district assessment.
The governing body of a transportation benefit district may give credit for all or any portion of any real property donation against an assessment, charge, or other required financial contribution for transportation improvements within a transportation benefit district established under RCW 36.73.020 or 35.21.225. The credit granted shall be available against any assessment, charge or other required financial contribution for any transportation purpose which utilizes the donated property.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c267.pdf?cite=1987%20c%20267%20§%203[1987 c 267 § 3]; ]

== 47.14.040 - Advertising signs on donated parcel.
The department or the county, city, or town to which the right-of-way is donated shall, upon request, grant the donor an airspace lease or a permit for the purpose of erecting or maintaining, or both, one or more signs advertising a business of the donor that is conducted on premises adjacent to the donated parcel unless the sign or signs would be detrimental to the safety and operation of the highway, road, or street. This provision applies to all highways, roads, and streets other than limited access highways and streets, where it applies only until the donated parcel becomes part of a completed operating facility. Except as provided in this section, any such sign shall conform to the requirements of all other applicable federal, state, and local laws and ordinances. The lease agreement or permit shall take into consideration applicable county and city zoning ordinances and may provide for compensation for removal of the sign in accordance with applicable federal, state, and local laws and ordinances. The lease agreement or permit shall specify the conditions for signage.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c267.pdf?cite=1987%20c%20267%20§%204[1987 c 267 § 4]; ]

== 47.14.050 - Department's duties.
The department shall:

. Give priority to the refinement and modification of right-of-way procedures and policies dealing with donation;

. Reduce or simplify paperwork requirements resulting from right-of-way procurement;

. Increase communication and education efforts as a means to solicit and encourage voluntary right-of-way donations;

. Enhance communication and coordination with local governments through agreements of understanding that address state acceptance of right-of-way donations secured under zoning, use permits, subdivision, and associated police power authority of local government.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6219.SL.pdf?cite=1998%20c%20245%20§%2096[1998 c 245 § 96]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c267.pdf?cite=1987%20c%20267%20§%205[1987 c 267 § 5]; ]

== 47.14.900 - Construction.
Nothing in this chapter may be construed to contravene the requirements of chapter 8.26 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c267.pdf?cite=1987%20c%20267%20§%206[1987 c 267 § 6]; ]

