= 47.29 - Transportation innovative partnerships.
:toc:

== 47.29.010 - Finding—Intent.
. The legislature finds that the public-private transportation initiatives act created under chapter 47.46 RCW has not met the needs and expectations of the public or private sectors for the development of transportation projects. The legislature intends to phase out chapter 47.46 RCW coincident with the completion of the Tacoma Narrows Bridge - SR 16 public-private partnership. From July 24, 2005, this chapter will provide a more desirable and effective approach to developing transportation projects in partnership with the private sector by applying lessons learned from other states and from this state's ten-year experience with chapter 47.46 RCW.

. It is the legislature's intent to achieve the following goals through the creation of this new approach to public-private partnerships:

.. To provide a well-defined mechanism to facilitate the collaboration between public and private entities in transportation;

.. To bring innovative thinking from the private sector and other states to bear on public projects within the state;

.. To provide greater flexibility in achieving the transportation projects; and

.. To allow for creative cost and risk sharing between the public and private partners.

. The legislature intends that the powers granted in this chapter to the commission or department are in addition to any powers granted under chapter 47.56 RCW.

. It is further the intent of the legislature that an expert review panel be established for each project developed under chapter 334, Laws of 2006. Expert review panels shall be responsible for reviewing selected proposals, analyzing and reviewing tentative agreements, and making recommendations to the governor and the transportation commission on the advisability of executing agreements under chapter 334, Laws of 2006.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6800-S.SL.pdf?cite=2006%20c%20334%20§%2048[2006 c 334 § 48]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1541-S.SL.pdf?cite=2005%20c%20317%20§%201[2005 c 317 § 1]; ]

== 47.29.020 - Definitions.
The definitions in this section apply throughout this chapter.

. "Authority" means the transportation commission.

. "Commission" means the transportation commission.

. "Department" means the department of transportation.

. "Eligible project" means any project eligible for development under RCW 47.29.050.

. "Eligible public works project" means only a project that meets the criteria of either RCW 47.29.060 (3) or (4).

. "Private sector partner" and "private partner" means a person, entity, or organization that is not the federal government, a state, or a political subdivision of a state.

. "Public funds" means all moneys derived from taxes, fees, charges, tolls, etc.

. "Public sector partner" and "public partner" means any federal or state unit of government, bistate transportation organization, or any other political subdivision of any state.

. "Transportation innovative partnership program" or "program" means the program as outlined in RCW 47.29.040.

. "Transportation project" means a project, whether capital or operating, where the state's primary purpose for the project is to preserve or facilitate the safe transport of people or goods via any mode of travel. However, this does not include projects that are primarily for recreational purposes, such as parks, hiking trails, off-road vehicle trails, etc.

. "Unit of government" means any department or agency of the federal government, any state or agency, office, or department of a state, any city, county, district, commission, authority, entity, port, or other public corporation organized and existing under statutory law or under a voter-approved charter or initiative, and any intergovernmental entity created under chapter 39.34 RCW or this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1541-S.SL.pdf?cite=2005%20c%20317%20§%202[2005 c 317 § 2]; ]

== 47.29.030 - Transportation commission powers and duties.
In addition to the powers it now possesses, the commission shall:

. Approve or review contracts or agreements authorized in this chapter;

. Adopt rules to carry out this chapter and govern the program, which at a minimum must address the following issues:

.. The types of projects allowed; however, all allowed projects must be included in the Washington transportation plan or identified by the authority as being a priority need for the state;

.. The types of contracts allowed, with consideration given to the best practices available;

.. The composition of the team responsible for the evaluation of proposals to include:

... Washington state department of transportation staff;

... An independent representative of a consulting or contracting field with no interests in the project that is prohibited from becoming a project manager for the project and bidding on any part of the project;

... An observer from the state auditor's office or the joint legislative audit and review committee;

... A person appointed by the commission, if the secretary of transportation is a cabinet member, or appointed by the governor if the secretary of transportation is not a cabinet member; and

.. A financial expert;

.. Minimum standards and criteria required of all proposals;

.. Procedures for the proper solicitation, acceptance, review, and evaluation of projects;

.. Criteria to be considered in the evaluation and selection of proposals that includes:

... Comparison with the department's internal ability to complete the project that documents the advantages of completing the project as a partnership versus solely as a public venture; and

... Factors such as, but not limited to: Priority, cost, risk sharing, scheduling, and management conditions;

.. The protection of confidential proprietary information while still meeting the need for public disclosure that is consistent with RCW 47.29.190;

.. Protection for local contractors to participate in subcontracting opportunities;

.. Specifying that maintenance issues must be resolved in a manner consistent with the personnel system reform act, chapter 41.80 RCW;

.. Specifying that provisions regarding patrolling and law enforcement on a public facility are subject to approval by the Washington state patrol;

. Adopt guidelines to address security and performance issues.

Preliminary rules and guidelines developed under this section must be submitted to the chairs and ranking members of both transportation committees by November 30, 2005, for review and comment. All final rules and guidelines must be submitted to the full legislature during the 2006 session for review.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1541-S.SL.pdf?cite=2005%20c%20317%20§%203[2005 c 317 § 3]; ]

== 47.29.040 - Purpose.
The Transportation Innovative Partnerships Act is created for the planning, acquisition, design, financing, management, development, construction, reconstruction, replacement, improvement, maintenance, preservation, repair, and operation of transportation projects. The goals of this chapter are to:

. Reduce the cost of transportation project delivery;

. Recover transportation investment costs;

. Develop an expedited project delivery process;

. Encourage business investment in public infrastructure;

. Use any fund source outside the state treasury, where financially advantageous and in the public interest;

. Maximize innovation;

. Develop partnerships between and among private entities and the public sector for the advancement of public purposes on mutually beneficial terms;

. Create synergies between and among public sector entities to develop projects that serve both transportation and other important public purposes; and

. Access specialized construction management and project management services and techniques available in the private sector.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1541-S.SL.pdf?cite=2005%20c%20317%20§%204[2005 c 317 § 4]; ]

== 47.29.050 - Eligible projects.
Projects eligible for development under this chapter include:

. Transportation projects, whether capital or operating, where the state's primary purpose for the project is to facilitate the safe transport of people or goods via any mode of travel. However, this does not include projects that are primarily for recreational purposes, such as parks, hiking trails, off-road vehicle trails, etc.; and

. Facilities, structures, operations, properties, vehicles, vessels, or the like that are developed concurrently with an eligible transportation project and that are capable of (a) providing revenues to support financing of an eligible transportation project, or (b) that are public projects that advance public purposes unrelated to transportation.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1541-S.SL.pdf?cite=2005%20c%20317%20§%205[2005 c 317 § 5]; ]

== 47.29.060 - Eligible financing.
. Subject to the limitations in this section, the department may, in connection with the evaluation of eligible projects, consider any financing mechanisms identified under subsections (3) through (5) of this section or any other lawful source, either integrated as part of a project proposal or as a separate, stand-alone proposal to finance a project. Financing may be considered for all or part of a proposed project. A project may be financed in whole or in part with:

.. The proceeds of grant anticipation revenue bonds authorized by 23 U.S.C. Sec. 122 and applicable state law. Legislative authorization and appropriation is required in order to use this source of financing;

.. Grants, loans, loan guarantees, lines of credit, revolving lines of credit, or other financing arrangements available under the Transportation Infrastructure Finance and Innovation Act under 23 U.S.C. Sec. 181 et seq., or any other applicable federal law;

.. Infrastructure loans or assistance from the state infrastructure bank established by RCW 82.44.195;

.. Federal, state, or local revenues, subject to appropriation by the applicable legislative authority;

.. User fees, tolls, fares, lease proceeds, rents, gross or net receipts from sales, proceeds from the sale of development rights, franchise fees, or any other lawful form of consideration. However, projects financed by tolls or equivalent funding sources must first be authorized by the legislature under RCW 47.56.820.

. As security for the payment of financing described in this section, the revenues from the project may be pledged, but no such pledge of revenues constitutes in any manner or to any extent a general obligation of the state. Any financing described in this section may be structured on a senior, parity, or subordinate basis to any other financing.

. For any transportation project developed under this chapter that is owned, leased, used, or operated by the state, as a public facility, if indebtedness is issued, it must be issued by the state treasurer for the transportation project.

. For other public projects defined in RCW 47.29.050(2) that are developed in conjunction with a transportation project, financing necessary to develop, construct, or operate the public project must be approved by the state finance committee or by the governing board of a public benefit corporation as provided in the federal Internal Revenue Code section 63-20;

. For projects that are developed in conjunction with a transportation project but are not themselves a public facility or public project, any lawful means of financing may be used.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1773-S2.SL.pdf?cite=2008%20c%20122%20§%2018[2008 c 122 § 18]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1541-S.SL.pdf?cite=2005%20c%20317%20§%206[2005 c 317 § 6]; ]

== 47.29.070 - Use of federal funds and similar revenues.
The department may accept from the United States or any of its agencies such funds as are available to this state or to any other unit of government for carrying out the purposes of this chapter, whether the funds are made available by grant, loan, or other financing arrangement. The department may enter into such agreements and other arrangements with the United States or any of its agencies as may be necessary, proper, and convenient for carrying out the purposes of this chapter, subject to RCW 47.29.080.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1541-S.SL.pdf?cite=2005%20c%20317%20§%207[2005 c 317 § 7]; ]

== 47.29.080 - Other sources of funds or property.
The department may accept from any source any grant, donation, gift, or other form of conveyance of land, money, other real or personal property, or other valuable thing made to the state of Washington, the department, or a local government for carrying out the purposes of this chapter.

Any eligible project may be financed in whole or in part by contribution of any funds or property made by any private entity or public sector partner that is a party to any agreement entered into under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1541-S.SL.pdf?cite=2005%20c%20317%20§%208[2005 c 317 § 8]; ]

== 47.29.090 - Project review, evaluation, and selection.
. Subject to subsection (2) of this section, the commission may:

.. Solicit concepts or proposals for eligible projects from private entities and units of government;

.. On or after January 1, 2007, accept unsolicited concepts or proposals for eligible projects from private entities and units of government, subject to RCW 47.29.170;

.. Direct the department to evaluate projects for inclusion in the transportation innovative partnerships program that are already programmed or identified for traditional development by the state;

.. Direct the department to evaluate the concepts or proposals received under this section; and

.. Select potential projects based on the concepts or proposals. The evaluation under this subsection must include consultation with any appropriate unit of government.

. Before undertaking any of the activities contained in subsection (1) of this section, the commission must have:

.. Completed the tolling feasibility study; and

.. Adopted rules specifying procedures for the proper solicitation, acceptance, review, and evaluation of projects, which procedures must include:

... A comparison with the department's internal ability to complete the project that documents the advantages of completing the project as a partnership versus solely as a public venture; and

... Factors such as priority, cost, risk sharing, scheduling, and management conditions.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1541-S.SL.pdf?cite=2005%20c%20317%20§%209[2005 c 317 § 9]; ]

== 47.29.100 - Administrative fee.
The department may charge a reasonable administrative fee for the evaluation of an unsolicited project proposal. The amount of the fee will be established in rules of the commission.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1541-S.SL.pdf?cite=2005%20c%20317%20§%2010[2005 c 317 § 10]; ]

== 47.29.110 - Funds for proposal evaluation and negotiation.
The department may spend, out of any funds identified for the purpose, such moneys as may be necessary for the evaluation of concepts or proposals for eligible projects and for negotiating agreements for eligible projects authorized by this chapter. The department may employ engineers, consultants, or other experts the department determines are needed for the purposes of doing the evaluation and negotiation. Expenses incurred by the department under this section before the issuance of transportation project bonds or other financing must be paid by the department and charged to the appropriate project. The department shall keep records and accounts showing each amount so charged.

Unless otherwise provided in the omnibus transportation budget the funds spent by the department under this section in connection with the project must be repaid from the proceeds of the bonds or other financing upon the sale of transportation project bonds or upon obtaining other financing for an eligible project, as allowed by law or contract.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1541-S.SL.pdf?cite=2005%20c%20317%20§%2011[2005 c 317 § 11]; ]

== 47.29.120 - Expert consultation.
The commission and department may consult with legal, financial, and other experts inside and outside the public sector in the evaluation, negotiation, and development of projects under this chapter, consistent with RCW 43.10.040 where applicable.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1541-S.SL.pdf?cite=2005%20c%20317%20§%2012[2005 c 317 § 12]; ]

== 47.29.130 - Contracted studies.
Notwithstanding any other provision of law, and in the absence of any direct federal funding or direction, the department may contract with a private developer of a selected project proposal to conduct environmental impact studies and engineering and technical studies.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1541-S.SL.pdf?cite=2005%20c%20317%20§%2013[2005 c 317 § 13]; ]

== 47.29.140 - Partnership agreements.
. The following provisions must be included in any agreement to which the state is a party:

.. For any project that proposes terms for stand-alone maintenance or asset management services for a public facility, those services must be provided in a manner consistent with any collective bargaining agreements, the personnel system reform act (chapter 41.80 RCW), and civil service laws that are in effect for the public facility;

.. Transportation projects that are selected for development under this chapter must be identified in the Washington transportation plan or be identified by the authority as being a priority need for the state;

.. If there is a tolling component to the project, then it must be specified that tolling technology used in the project must be consistent with tolling technology standards adopted by the department for transportation-related projects;

.. Provisions for bonding, financial guarantees, deposits, or the posting of other security to secure the payment of laborers, subcontractors, and suppliers who perform work or provide materials as part of the project;

.. All projects must be financed in a manner consistent with RCW 47.29.060. This chapter is null and void if this subsection or RCW 47.29.060 fails to become law or is held invalid by a court of final jurisdiction.

. Agreements between the state and private sector partners entered into under this section must specifically include the following contractual elements:

.. The point in the project at which public and private sector partners will enter the project and which partners will assume responsibility for specific project elements;

.. How the partners will share management of the risks of the project;

.. How the partners will share the costs of development of the project;

.. How the partners will allocate financial responsibility for cost overruns;

.. The penalties for nonperformance;

.. The incentives for performance;

.. The accounting and auditing standards to be used to evaluate work on the project;

.. For any project that reverts to public ownership, the responsibility for reconstruction or renovations that are required in order for a facility to meet all applicable government standards upon reversion of the facility to the state; and

.. Provisions for patrolling and law enforcement on transportation projects that are public facilities.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1541-S.SL.pdf?cite=2005%20c%20317%20§%2014[2005 c 317 § 14]; ]

== 47.29.150 - Public involvement and participation.
. Before final approval, agreements entered into under this chapter must include a process that provides for public involvement and participation with respect to the development of the projects. This plan must be submitted along with the proposed agreement, and both must be approved under RCW 47.29.160 before the state may enter a binding agreement.

. All workshops, forums, open houses, meetings, public hearings, or similar public gatherings must be administered and attended by representatives of the state and any other public entities that are party to an agreement authorized by this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1541-S.SL.pdf?cite=2005%20c%20317%20§%2015[2005 c 317 § 15]; ]

== 47.29.160 - Approval and execution.
. Before approving an agreement under subsection (2) of this section, the commission, with the technical assistance of the department, must:

.. Prepare a financial analysis that fully discloses all project costs, direct and indirect, including costs of any financing;

.. Publish notice and make available the contents of the agreement, with the exception of patent information, at least twenty days before the public hearing required in (c) of this subsection; and

.. Hold a public hearing on the proposed agreement, with proper notice provided at least twenty days before the hearing. The public hearing must be held within the boundaries of the county seat of the county containing the project.

. The commission must allow at least twenty days from the public hearing on the proposed agreement required under subsection (1)(c) of this section before approving and executing any agreements authorized under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1541-S.SL.pdf?cite=2005%20c%20317%20§%2016[2005 c 317 § 16]; ]

== 47.29.170 - Unsolicited proposals.
Before accepting any unsolicited project proposals, the commission must adopt rules to facilitate the acceptance, review, evaluation, and selection of unsolicited project proposals. These rules must include the following:

. Provisions that specify unsolicited proposals must meet predetermined criteria;

. Provisions governing procedures for the cessation of negotiations and consideration;

. Provisions outlining that unsolicited proposals are subject to a two-step process that begins with concept proposals and would only advance to the second step, which are fully detailed proposals, if the commission so directed;

. Provisions that require concept proposals to include at least the following information: Proposers' qualifications and experience; description of the proposed project and impact; proposed project financing; and known public benefits and opposition; and

. Provisions that specify the process to be followed if the commission is interested in the concept proposal, which must include provisions:

.. Requiring that information regarding the potential project would be published for a period of not less than thirty days, during which time entities could express interest in submitting a proposal;

.. Specifying that if letters of interest were received during the thirty days, then an additional sixty days for submission of the fully detailed proposal would be allowed; and

.. Procedures for what will happen if there are insufficient proposals submitted or if there are no letters of interest submitted in the appropriate time frame.

The commission may adopt other rules as necessary to avoid conflicts with existing laws, statutes, or contractual obligations of the state.

The commission may not accept or consider any unsolicited proposals before July 1, 2018.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5096.SL.pdf?cite=2017%20c%20313%20§%20711[2017 c 313 § 711]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1299-S.SL.pdf?cite=2015%201st%20sp.s.%20c%2010%20§%20704[2015 1st sp.s. c 10 § 704]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5024-S.SL.pdf?cite=2013%20c%20306%20§%20708[2013 c 306 § 708]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1175-S.SL.pdf?cite=2011%20c%20367%20§%20701[2011 c 367 § 701]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5352-S.SL.pdf?cite=2009%20c%20470%20§%20702[2009 c 470 § 702]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1094-S.SL.pdf?cite=2007%20c%20518%20§%20702[2007 c 518 § 702]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6241-S.SL.pdf?cite=2006%20c%20370%20§%20604[2006 c 370 § 604]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1541-S.SL.pdf?cite=2005%20c%20317%20§%2017[2005 c 317 § 17]; ]

== 47.29.180 - Advisory committees.
For projects with costs, including financing costs, of three hundred million dollars or greater, advisory committees are required.

. The commission must establish an advisory committee to advise with respect to eligible projects. An advisory committee must consist of not fewer than five and not more than nine members, as determined by the public partners. Members must be appointed by the commission, or for projects with joint public sector participation, in a manner agreed to by the commission and any participating unit of government. In making appointments to the committee, the commission shall consider persons or organizations offering a diversity of viewpoints on the project.

. An advisory committee shall review concepts or proposals for eligible projects and submit comments to the public sector partners.

. An advisory committee shall meet as necessary at times and places fixed by the department, but not less than twice per year. The state shall provide personnel services to assist the advisory committee within the limits of available funds. An advisory committee may adopt rules to govern its proceedings and may select officers.

. An advisory committee must be dissolved once the project has been fully constructed and debt issued to pay for the project has been fully retired.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1541-S.SL.pdf?cite=2005%20c%20317%20§%2018[2005 c 317 § 18]; ]

== 47.29.190 - Confidentiality.
A proposer shall identify those portions of a proposal that the proposer considers to be confidential, proprietary information, or trade secrets and provide any justification as to why these materials, upon request, should not be disclosed by the authority. Patent information will be covered until the patent expires. Other information such as originality of design or records of negotiation may only be protected under this section until an agreement is reached. Disclosure must occur before final agreement and execution of the contract. Projects under federal jurisdiction or using federal funds must conform to federal regulations under the Freedom of Information Act.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1541-S.SL.pdf?cite=2005%20c%20317%20§%2019[2005 c 317 § 19]; ]

== 47.29.200 - Prevailing wages.
If public funds are used to pay any costs of construction of a public facility that is part of an eligible project, chapter 39.12 RCW applies to the entire eligible public works project.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1541-S.SL.pdf?cite=2005%20c%20317%20§%2020[2005 c 317 § 20]; ]

== 47.29.210 - Government agreements.
The state may, either separately or in combination with any other public sector partner, enter into working agreements, coordination agreements, or similar implementation agreements, including the formation of bistate transportation organizations, to carry out the joint implementation of a transportation project selected under this chapter. The state may enter into agreements with other units of government or Canadian provinces for transborder transportation projects.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1541-S.SL.pdf?cite=2005%20c%20317%20§%2021[2005 c 317 § 21]; ]

== 47.29.220 - Eminent domain.
The state may exercise the power of eminent domain to acquire property, rights-of-way, or other rights in property for projects that are necessary to implement an eligible project developed under this chapter, regardless of whether the property will be owned in fee simple by the state.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1541-S.SL.pdf?cite=2005%20c%20317%20§%2022[2005 c 317 § 22]; ]

== 47.29.230 - Transportation innovative partnership account.
. The transportation innovative partnership account is established in the custody of the state treasurer separate and distinct from the state general fund. Interest earned by the transportation innovative partnership account must be credited to the account. The account is subject to allotment procedures under chapter 43.88 RCW.

. The following moneys must be deposited into the transportation innovative partnership account:

.. Proceeds from bonds or other financing instruments issued under RCW 47.29.250;

.. Revenues received from any transportation project developed under this chapter or developed under the general powers granted to the department; and

.. Any other moneys that are by donation, grant, contract, law, or other means transferred, allocated, or appropriated to the account.

. Moneys in the transportation innovative partnership account may only be expended upon evidence of approval by the Washington state legislature, either upon appropriation of supporting state funds or by other statutory direction.

. The state treasurer shall serve as a fiduciary for the purpose of carrying out this chapter and implementing all or portions of any transportation project financed under this chapter.

. Moneys in the transportation innovative partnership account that were derived from revenue subject to Article II, section 40 (Amendment 18) of the Washington state Constitution, may be used only for purposes authorized by that provision of the state Constitution.

. The state treasurer shall establish separate subaccounts within the transportation innovative partnership account for each transportation project that is initiated under this chapter or under the general powers granted to the department. Except as provided in subsection (5) of this section, the state may pledge moneys in the transportation innovative partnership account to secure revenue bonds or any other debt obligations relating to the project for which the account is established.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1541-S.SL.pdf?cite=2005%20c%20317%20§%2023[2005 c 317 § 23]; ]

== 47.29.240 - Use of account.
. The state may use moneys in the transportation innovative partnership subaccount to ensure the repayment of loan guarantees or extensions of credit made to or on behalf of private entities engaged in the planning, acquisition, financing, development, design, construction, reconstruction, replacement, improvement, maintenance, preservation, management, repair, or operation of any eligible project that is related to a subaccount established under this chapter.

. The lien of a pledge made under this section is subordinate to the lien of a pledge securing bonds payable from moneys in the motor vehicle fund established in RCW 46.68.070, or the transportation innovative partnership account established in RCW 47.29.230.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1541-S.SL.pdf?cite=2005%20c%20317%20§%2024[2005 c 317 § 24]; ]

== 47.29.250 - Issuing bonds and other obligations.
. In addition to any authority the commission or department has to issue and sell bonds and other similar obligations, this section establishes continuing authority for the issuance and sale of bonds and other similar obligations in a manner consistent with this section. To finance a project in whole or in part, the commission may request that the state treasurer issue revenue bonds on behalf of the public sector partner. The bonds must be secured by a pledge of, and a lien on, and be payable only from moneys in the transportation innovative partnership account established in RCW 47.29.230, and any other revenues specifically pledged to repayment of the bonds. Such a pledge by the public partner creates a lien that is valid and binding from the time the pledge is made. Revenue bonds issued under this section are not general obligations of the state or local government and are not secured by or payable from any funds or assets of the state other than the moneys and revenues specifically pledged to the repayment of such revenue bonds.

. Moneys received from the issuance of revenue bonds or other debt obligations, including any investment earnings thereon, may be spent:

.. For the purpose of financing the costs of the project for which the bonds are issued;

.. To pay the costs and other administrative expenses of the bonds;

.. To pay the costs of credit enhancement or to fund any reserves determined to be necessary or advantageous in connection with the revenue bonds; and

.. To reimburse the public sector partners for any costs related to carrying out the projects authorized under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1541-S.SL.pdf?cite=2005%20c%20317%20§%2025[2005 c 317 § 25]; ]

== 47.29.260 - Study and report.
The department shall conduct a study of:

. The contracting powers and project management authorities it currently possesses; those same powers and authorities authorized under this chapter; and those powers and authorities employed by other states or the private sector;

. Methods of encouraging competition for the development of transportation projects; and

. Any additional procedures that may be necessary or desirable for negotiating contracts in situations of a single qualified bidder, in either solicited or unsolicited proposals.

The department must submit its report, along with any recommended legislative changes, to the commission by November 1, 2005, and to the governor and the legislature for consideration in the 2006 legislative session.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1541-S.SL.pdf?cite=2005%20c%20317%20§%2026[2005 c 317 § 26]; ]

== 47.29.270 - Federal laws.
Notwithstanding any provision of this chapter, applicable federal laws, rules, and regulations govern in any situation that involves federal funds if the federal laws, rules, or regulations:

. Conflict with any provision of this chapter;

. Require procedures that are additional to or different from those provided in this chapter; or

. Require contract provisions not authorized in this chapter. If no federal funds are provided, state laws, rates, and rules will govern.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1541-S.SL.pdf?cite=2005%20c%20317%20§%2027[2005 c 317 § 27]; ]

== 47.29.280 - Expert review panel on proposed project agreements—Creation—Authority.
. The department shall establish an expert review panel to review, analyze, and make recommendations to the governor and the transportation commission on whether to approve, reject, or continue negotiations on a proposed project agreement under this chapter. The department shall provide staff to support the expert review panel, if requested by the panel. The expert review panel may utilize any of the consultants under contract for the department, and the expert review panel may contract for consulting expertise in specific areas as it deems necessary to ensure a thorough and critical review of any proposed project agreement.

. The governor shall appoint members of an expert review panel that have experience in large capital project delivery, public-private partnerships, public financing of infrastructure improvements, or other areas of expertise that will benefit the panel. The panel shall consist of no less than three, but no more than five members, as determined by the governor.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6800-S.SL.pdf?cite=2006%20c%20334%20§%2049[2006 c 334 § 49]; ]

== 47.29.290 - Expert review panel on proposed project agreements—Execution of agreements.
Upon receiving the recommendations of the expert review panel as provided in RCW 47.29.280, and upon consultation with the governor, the transportation commission shall either execute the proposed project agreement, reject the proposed project agreement, or continue further negotiations between the state and a private partner. The execution of any agreement or the rejection of any agreement shall constitute a final action for legal or administrative purposes.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6800-S.SL.pdf?cite=2006%20c%20334%20§%2050[2006 c 334 § 50]; ]

