= 47.39 - Scenic and recreational highway act of 1967.
:toc:

== 47.39.010 - System created—Standards.
There is hereby created a scenic and recreational highway system. Highways in this system shall be developed and maintained in accordance with general standards for state highways of comparable classification and usage.

Recognizing that the Transportation Equity Act for the 21st Century establishes a national "scenic byway" program that could benefit state and local roadways, the Washington state scenic byway designation program is revised to address state and local transportation routes. Byways in this program must be designated and maintained in accordance with the criteria developed by the department under this chapter. However, a highway so designated under RCW 47.39.069 does not become part of the scenic and recreational highway system unless approved by the legislature. Corridors within the scenic and recreational highway system that showcase the state's historic agricultural areas and promote the maintenance and enhancement of agricultural areas may be designated as agricultural scenic corridors.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6211-S.SL.pdf?cite=2010%20c%2014%20§%201[2010 c 14 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5273-S.SL.pdf?cite=1999%20c%20218%20§%201[1999 c 218 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c85.pdf?cite=1967%20ex.s.%20c%2085%20§%201[1967 ex.s. c 85 § 1]; ]

== 47.39.020 - Designation of portions of existing highways and ferry routes as part of system.
The following portions of highways are designated as part of the scenic and recreational highway system:

. State route number 2, beginning at the crossing of Woods creek at the east city limits of Monroe, thence in an easterly direction by way of Stevens pass to a junction with state route number 97 in the vicinity of Peshastin; also

Beginning at the junction with state route number 17, in the vicinity of Coulee City, thence easterly to the junction with state route number 155;

. State route number 3, beginning at a junction with state route number 101 in the vicinity of Shelton, thence northeasterly and northerly to a junction with state route number 104 in the vicinity of Port Gamble;

. State route number 4, beginning at the junction with state route number 101, thence easterly through Cathlamet to Coal Creek road, approximately .5 miles west of the Longview city limits;

. State route number 5, beginning at the junction with Starbird Road in Snohomish county, thence northerly to the junction with Bow Hill Road in Skagit county, to be designated as an agricultural scenic corridor with appropriate signage;

. State route number 6, beginning at the junction with state route number 101 in Raymond, thence easterly to the junction with state route number 5, in the vicinity of Chehalis;

. State route number 7, beginning at the junction with state route number 12 in Morton, thence northerly to the junction with state route number 507;

. State route number 8, beginning at a junction with state route number 12 in the vicinity of Elma, thence easterly to a junction with state route number 101 near Tumwater;

. State route number 9, beginning at the junction with state route number 530 in Arlington, thence northerly to the end of the route at the Canadian border;

. State route number 10, beginning at Teanaway junction, thence easterly to a junction with state route number 97 west of Ellensburg;

. State route number 11, beginning at the junction with state route number 5 in the vicinity of Burlington, thence in a northerly direction to the junction with state route number 5;

. State route number 12, beginning at a junction with a county road approximately 2.8 miles west of the crossing of the Wynoochee river which is approximately 1.2 miles west of Montesano, thence in an easterly direction to a junction with state route number 8 in the vicinity of Elma; also

Beginning at a junction with state route number 5, thence easterly by way of Morton, Randle, and Packwood to the junction with state route number 410, approximately 3.5 miles west of Naches; also

Beginning at the junction with state route number 124 in the vicinity of the Tri-Cities, thence easterly through Wallula and Touchet to a junction with a county road approximately 2.4 miles west of a junction with state route number 129 at Clarkston;

. State route number 14, beginning at the crossing of Gibbons creek approximately 0.9 miles east of Washougal, thence easterly along the north bank of the Columbia river to a point in the vicinity of Plymouth;

. State route number 17, beginning at a junction with state route number 395 in the vicinity of Mesa, thence northerly to the junction with state route number 97 in the vicinity of Brewster;

. State route number 19, the Chimacum-Beaver Valley road, beginning at the junction with state route number 104, thence northerly to the junction with state route number 20;

. State route number 20, beginning at the junction with state route number 101 to the ferry zone in Port Townsend; also

Beginning at the Keystone ferry slip on Whidbey Island, thence northerly and easterly to a junction with state route number 153 southeast of Twisp; also

Beginning at the junction of state route number 97 in the vicinity of Okanogan, thence westerly across the Okanogan river to the junction with state route number 215; also

Beginning at a junction with state route number 97 near Tonasket, thence easterly and southerly to a junction with state route number 2 at Newport;

. State route number 25, beginning at the Spokane river bridge, thence northerly through Cedonia, Gifford, Kettle Falls, and Northport, to the Canadian border;

. State route number 26, beginning at the Whitman county boundary line, thence easterly by way of the vicinities of La Crosse and Dusty to a junction with state route number 195 in the vicinity of Colfax;

. State route number 27, beginning at a junction with state route number 195 in the vicinity of Pullman, thence northerly by way of the vicinities of Palouse and Garfield to a junction with state route number 271 in the vicinity of Oakesdale; also

From a junction with state route number 271 at Oakesdale, thence northerly to the vicinity of Rockford;

. State route number 31, beginning at the junction with state route number 20 in Tiger, thence northerly to the Canadian border;

. State route number 82, beginning at the junction with state route number 395 south of the Tri-Cities area, thence southerly to the end of the route at the Oregon border;

. State route number 90, beginning at the junction with East Sunset Way in the vicinity east of Issaquah, thence easterly to Thorp road 9.0 miles west of Ellensburg;

. State route number 97, beginning at the Oregon border, in a northerly direction through Toppenish and Wapato to the junction with state route number 82 at Union Gap; also

Beginning at the junction with state route number 10, 2.5 miles north of Ellensburg, in a northerly direction to the junction with state route number 2, 4.0 miles east of Leavenworth; also

Beginning at the junction of state route number 153 in the vicinity south of Pateros, thence northerly by way of the vicinities of Brewster, Okanogan, Omak, Riverside, Tonasket, and Oroville to the international boundary line;

. State route number 97 alternate, beginning at the junction with state route number 2 in the vicinity of Monitor, thence northerly to the junction with state route number 97, approximately 5.0 miles north of Chelan;

. State route number 101, beginning at the Astoria-Megler bridge, thence north to Fowler street in Raymond; also

Beginning at a junction with state route number 109 in the vicinity of Queets, thence in a northerly, northeasterly, and easterly direction by way of Forks to the junction with state route number 5 in the vicinity of Olympia;

. State route number 104, beginning at a junction with state route number 101 in the vicinity south of Discovery bay, thence in a southeasterly direction to the Kingston ferry crossing;

. State route number 105, beginning at a junction with state route number 101 at Raymond, thence westerly and northerly by way of Tokeland and North Cove to the shore of Grays Harbor north of Westport; also

Beginning at a junction with state route number 105 in the vicinity south of Westport, thence northeasterly to a junction with state route number 101 at Aberdeen;

. State route number 109, beginning at a junction with state route number 101 in Hoquiam to a junction with state route number 101 in the vicinity of Queets;

. State route number 112, beginning at the easterly boundary of the Makah Indian reservation, thence in an easterly direction to the vicinity of Laird's corner on state route number 101;

. State route number 116, beginning at the junction with the Chimacum-Beaver Valley road, thence in an easterly direction to Fort Flagler State Park;

. State route number 119, beginning at the junction with state route number 101 at Hoodsport, thence northwesterly to the Mount Rose development intersection;

. State route number 122, Harmony road, between the junction with state route number 12 near Mayfield dam and the junction with state route number 12 in Mossyrock;

. State route number 123, beginning at the junction with state route number 12 in the vicinity of Morton, thence northerly to the junction with state route number 410;

. State route number 129, beginning at the Oregon border, thence northerly to the junction with state route number 12 in Clarkston;

. State route number 141, beginning at the junction with state route number 14 in Bingen, thence northerly to the end of the route at the Skamania county line;

. State route number 142, beginning at the junction with state route number 14 in Lyle, thence northeasterly to the junction with state route number 97, .5 miles from Goldendale;

. State route number 153, beginning at a junction with state route number 97 in the vicinity of Pateros, thence in a northerly direction to a junction with state route number 20 in the vicinity south of Twisp;

. State route number 155, beginning at a junction with state route number 2 in the vicinity north of Coulee City, thence northerly and westerly to the junction with state route number 215;

. State route number 194, beginning at the Port of Almota to the junction with state route number 195 in the vicinity of Pullman;

. State route number 195, beginning at the Washington-Idaho boundary line southeast of Uniontown, thence northwesterly and northerly by way of the vicinity of Colton, Pullman, Colfax, Steptoe, and Rosalia to the Whitman county boundary line;

. State route number 202, beginning at the junction with state route number 522, thence in an easterly direction to the junction with state route number 90 in the vicinity of North Bend;

. State route number 211, beginning at the junction with state route number 2, thence northerly to the junction with state route number 20 in the vicinity of Usk;

. State route number 215, beginning at the junction of state route number 20 in the vicinity of Okanogan, thence northeasterly on the west side of the Okanogan river to a junction with state route number 97 north of Omak;

. State route number 231, beginning at the junction with state route number 23, in the vicinity of Sprague, thence in a northerly direction to the junction with state route number 2, approximately 2.5 miles west of Reardan;

. State route number 261, beginning at the junction with state route number 12 in the vicinity of Delaney, thence northwesterly to the junction with state route number 260;

. State route number 262, beginning at the junction with state route number 26, thence northeasterly to the junction with state route number 17 between Moses Lake and Othello;

. State route number 271, beginning at a junction with state route number 27 in the vicinity of Oakesdale, thence northwesterly to a junction with state route number 195 in the vicinity south of Rosalia;

. State route number 272, beginning at the junction with state route number 195 in Colfax, thence easterly to the Idaho state line, approximately 1.5 miles east of Palouse;

. State route number 278, beginning at a junction with state route number 27, thence easterly via Rockford to the Idaho state line;

. State route number 305, beginning at the Winslow ferry dock to the junction with state route number 3 approximately 1.0 mile north of Poulsbo;

. State route number 395, beginning at the north end of the crossing of Mill creek in the vicinity of Colville, thence in a northwesterly direction to a junction with state route number 20 at the west end of the crossing over the Columbia river at Kettle Falls;

. State route number 401, beginning at a junction with state route number 101 at Point Ellice, thence easterly and northerly to a junction with state route number 4 in the vicinity north of Naselle;

. State route number 410, beginning at the intersection with Farman street in Enumclaw, thence in an easterly direction to the junction with state route number 12, approximately 3.5 miles west of Naches;

. State route number 501, beginning at the junction with state route number 5 in the vicinity of Vancouver, thence northwesterly on the New Lower River road around Vancouver Lake;

. State route number 503, beginning at the junction with state route number 500, thence northerly by way of Battle Ground and Yale to the junction with state route number 5 in the vicinity of Woodland;

. State route number 504, beginning at a junction with state route number 5 at Castle Rock, to the end of the route on Johnston Ridge, approximately milepost 52;

. State route number 505, beginning at the junction with state route number 504, thence northwesterly by way of Toledo to the junction with state route number 5;

. State route number 508, beginning at the junction with state route number 5, thence in an easterly direction to the junction with state route number 7 in Morton;

. State route number 525, beginning at the ferry toll booth on Whidbey Island to a junction with state route number 20 east of the Keystone ferry slip;

. State route number 542, beginning at the junction with state route number 5, thence easterly to the vicinity of Austin pass in Whatcom county;

. State route number 547, beginning at the junction with state route number 542 in Kendall, thence northwesterly to the junction with state route number 9 in the vicinity of the Canadian border;

. State route number 706, beginning at the junction with state route number 7 in Elbe, in an easterly direction to the end of the route at Mt. Rainier National Park;

. State route number 821, beginning at a junction with state route number 82 at the Yakima firing center interchange, thence in a northerly direction to a junction with state route number 82 at the Thrall road interchange;

. State route number 971, Navarre Coulee road, between the junction with state route number 97 and the junction with South Lakeshore road;

. Beginning at the Anacortes ferry landing, the Washington state ferries Anacortes/San Juan Islands route, which includes stops at Lopez, Shaw, Orcas, and San Juan Islands; and the roads on San Juan and Orcas Islands as described in San Juan Island county council resolution number 7, adopted February 5, 2008;

. All Washington state ferry routes.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5030.SL.pdf?cite=2013%20c%20154%20§%202[2013 c 154 § 2]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1024-S.SL.pdf?cite=2011%20c%20123%20§%201[2011 c 123 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6211-S.SL.pdf?cite=2010%20c%2014%20§%202[2010 c 14 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5289.SL.pdf?cite=2009%20c%20277%20§%201[2009 c 277 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5937.SL.pdf?cite=2003%20c%2055%20§%201[2003 c 55 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2023-S.SL.pdf?cite=1993%20c%20430%20§%207[1993 c 430 § 7]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6078.SL.pdf?cite=1992%20c%2026%20§%202[1992 c 26 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5801.SL.pdf?cite=1991%20c%20342%20§%2054[1991 c 342 § 54]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c240.pdf?cite=1990%20c%20240%20§%203[1990 c 240 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975c63.pdf?cite=1975%20c%2063%20§%208[1975 c 63 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c151.pdf?cite=1973%201st%20ex.s.%20c%20151%20§%2010[1973 1st ex.s. c 151 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c73.pdf?cite=1971%20ex.s.%20c%2073%20§%2029[1971 ex.s. c 73 § 29]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c51.pdf?cite=1970%20ex.s.%20c%2051%20§%20177[1970 ex.s. c 51 § 177]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c281.pdf?cite=1969%20ex.s.%20c%20281%20§%206[1969 ex.s. c 281 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c85.pdf?cite=1967%20ex.s.%20c%2085%20§%202[1967 ex.s. c 85 § 2]; ]

== 47.39.030 - Development and maintenance of system by department of transportation and parks and recreation commission—Allocation of costs.
. The department shall pay from motor vehicle funds appropriated for construction of state highways, the following costs of developing and constructing scenic and recreational highways: (a) Acquisition of the right-of-way necessary for state highway purposes; (b) construction of the portion of the highway designed primarily for motor vehicle travel; (c) exit and entrance roadways providing access to scenic observation points; (d) safety rest areas; (e) roadside landscaping within the portion of the highway right-of-way acquired by the department for state highway purposes; (f) the uniform signs and markers designating the various features and facilities of the scenic and recreational highways; and (g) any additional costs of constructing and developing the scenic and recreational highways, including property acquisition adjacent to highways as authorized by RCW 47.12.250, for which the department shall receive reimbursement from the federal government or any other source.

. The parks and recreation commission shall pay the costs of developing and constructing the scenic and recreational highways not provided for in subsection (1) of this section from any funds appropriated for such purposes.

. The costs of maintaining the scenic and recreational highway system shall be allocated between the department and the parks and recreation commission in the same manner that costs of developing and constructing such highways are allocated in subsections (1) and (2) of this section.

. The city, town, county, regional transportation planning organization, federal agency, federally recognized tribe, or any other such party that nominates a roadway not located on a state-owned right-of-way for designation as a scenic byway shall bear all costs relating to the nomination and designation of the byway, such as costs for developing, maintaining, planning, designing, and constructing the scenic byway.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5273-S.SL.pdf?cite=1999%20c%20218%20§%202[1999 c 218 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%20207[1984 c 7 § 207]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c85.pdf?cite=1967%20ex.s.%20c%2085%20§%203[1967 ex.s. c 85 § 3]; ]

== 47.39.040 - Planning and design standards established by department of community, trade, and economic development.
The establishment of planning and design standards for items provided for in RCW 47.39.050 shall be coordinated by the *department of community, trade, and economic development. The department of transportation, parks and recreation commission, and any other departments or commissions whose interests are affected shall prepare, submit, and file with the *department of community, trade, and economic development standards relating to the scenic and recreational highway system. If varying planning and design standards are filed, the *department of community, trade, and economic development shall consult with the submitting agencies on the merits of the several proposals and, based upon such consultation, establish a set of standards. Pursuant to the planning and design standards so established, the department of transportation and the parks and recreation commission shall develop the highways and areas adjacent thereto to accomplish the purposes of this chapter, but the department shall retain exclusive authority over the highway right-of-way.

Responsibility for construction and maintenance is hereby established between the department and the parks and recreation commission with the department responsible for activities financed with funds provided for under RCW 47.39.030(1) and the parks and recreation commission responsible for activities financed from other sources of funds. By mutual consent, responsibility for development and/or maintenance may be transferred between the two agencies.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1014.SL.pdf?cite=1995%20c%20399%20§%20122[1995 c 399 § 122]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c6.pdf?cite=1985%20c%206%20§%2016[1985 c 6 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%20208[1984 c 7 § 208]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c85.pdf?cite=1967%20ex.s.%20c%2085%20§%204[1967 ex.s. c 85 § 4]; ]

== 47.39.050 - Planning and design standards—Facilities and factors considered.
Planning and design standards established for highways falling within the scenic and recreational highways system may include, but shall not be limited to, provision for the following:

. Hiking, bicycle, and bridle trails, including regulations for their use;

. Campsites and shelters;

. Boat launching sites;

. Access trails to lakes, rivers and streams, and easements along their shores;

. Safety rest areas;

. Historic and geologic interpretative facilities;

. Scenic observation facilities;

. Roadside landscaping, restoration and aesthetic enhancement;

. Specifically delineated highway corridors and means for the preservation of natural beauty, historic sites, or viewpoints;

. A uniform system of signs and markers designating the various features and facilities of the scenic and recreational highway systems.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c85.pdf?cite=1967%20ex.s.%20c%2085%20§%205[1967 ex.s. c 85 § 5]; ]

== 47.39.060 - Designation of system on maps or other descriptive material.
The department and the parks and recreation commission may include, where appropriate, on any maps, or in any relevant descriptive material they may prepare at state expense, references to those portions of highways designated in RCW 47.39.020, and may include those designated byways by appropriate color or code designation.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5273-S.SL.pdf?cite=1999%20c%20218%20§%203[1999 c 218 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%20209[1984 c 7 § 209]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c85.pdf?cite=1967%20ex.s.%20c%2085%20§%206[1967 ex.s. c 85 § 6]; ]

== 47.39.069 - Designation and removal criteria.
. The department, in consultation with the *department of community, trade, and economic development, the department of natural resources, the parks and recreation commission, affected cities, towns, and counties, federally recognized tribes, regional transportation planning organizations, Washington-based automobile clubs, statewide bicycling organizations, and other interested parties, shall develop by December 31, 1999, criteria for assessing scenic byways and heritage tour routes and an appropriate method of nomination and application for the designation and removal of the designation of the byways. Factors the department may take into consideration, but is not limited by, are: (a) Scenic quality of the byway; (b) natural aspects, such as geological formations, water bodies, vegetation, and wildlife; (c) historic elements; (d) cultural features such as the arts, crafts, music, customs, or traditions of a distinct group of people; (e) archaeological features; (f) recreational activities; (g) roadway safety including accommodations for bicycle and pedestrian travel, tour buses, and automobiles; (h) scenic byway and local and regional byway management plans; and (i) local public involvement and support for the byway.

. The criteria developed in subsection (1) of this section must not impose nor require regulation of privately owned lands or property rights.

. Any person may nominate a roadway, path, or trail for inclusion in the scenic byway program. The department shall assess nominations in accordance with the criteria developed under subsection (1) of this section. The department shall submit its recommendations for scenic byway and heritage tour route designations to the commission for its approval and official designation of the roadway, path, or trail as a scenic byway or a heritage tour route. All decisions made by the commission relating to scenic byway and heritage tour route designations are final.

. The department shall apply the criteria in subsection (1) of this section to state highways that are currently not a part of the designated scenic and recreational highway system. The department shall respond to local requests for route evaluation as defined in subsection (3) of this section.

. Once the commission has designated a roadway as a scenic byway, the department may submit an individual nomination to the federal highway administration for its consideration of whether the roadway qualifies to be designated as a national scenic byway or an All-American Roadway.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5273-S.SL.pdf?cite=1999%20c%20218%20§%204[1999 c 218 § 4]; ]

== 47.39.075 - Corridor management plan.
The department shall participate with local communities to develop a corridor management plan for a state highway nominated to be part of the scenic byway program. Local, regional, or other governmental bodies shall develop a corridor management plan for nominated routes that are under their jurisdiction.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5273-S.SL.pdf?cite=1999%20c%20218%20§%205[1999 c 218 § 5]; ]

== 47.39.080 - Funding priorities—Signage.
Recognizing that the Transportation Equity Act for the 21st Century establishes a national "Scenic Byways" grant program and a new apportionment program called "Transportation Enhancement Activities," the department of transportation shall place high priority on obtaining funds from those sources for further development of a scenic and recreational highways program, including enhancement projects on the designated scenic and recreational highway system. The department shall consider the use of the designated system by bicyclists and pedestrians in connection with nonmotorized routes in the state trail plan, and the state bicycle plan which are also eligible for TEA-21 funding. Appropriate signage may be used at intersections of nonmotorized and motorized systems to demonstrate the access, location, and the interconnectivity of various modes of travel for transportation and recreation. For the purposes of leveraging national scenic byway planning grant funds, the commission may designate eligible state highways as scenic byways on an interim basis.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5273-S.SL.pdf?cite=1999%20c%20218%20§%206[1999 c 218 § 6]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2023-S.SL.pdf?cite=1993%20c%20430%20§%208[1993 c 430 § 8]; ]

== 47.39.090 - Consultation with other agencies and parties—Identification of tourist routes.
In developing the scenic and recreational highways program, the department shall consult with the *department of community, trade, and economic development, the department of natural resources, the parks and recreation commission, affected cities, towns, and counties, regional transportation planning organizations, statewide bicycling organizations, and other interested parties. The scenic and recreational highways program may identify entire highway loops or similar tourist routes that could be developed to promote tourist activity and provide concurrent economic growth while protecting the scenic and recreational quality surrounding state highways.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1014.SL.pdf?cite=1995%20c%20399%20§%20123[1995 c 399 § 123]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2023-S.SL.pdf?cite=1993%20c%20430%20§%209[1993 c 430 § 9]; ]

== 47.39.100 - Removal of designation.
. The commission may remove the designation of a route if it no longer possesses the intrinsic qualities or fails to meet the criteria that supported its designation.

. The department shall determine whether a roadway designated as a national scenic byway or an All-American Roadway is being properly maintained in accordance with the roadway's byway management plan, including preserving the intrinsic qualities that originally supported the designation. When the department determines that the intrinsic qualities of a national scenic byway or All-American Roadway have not been maintained sufficiently to retain its designation, the department shall notify the party responsible for maintaining the designation of the finding and allow the party an opportunity, under federal regulations, for corrective action before formal removal of the designation of the roadway.

. Local, regional, or other governmental bodies may notify the commission of the removal of a designated route if they determine it no longer meets the designation criteria, or community support for the designation no longer exists, or it no longer possesses the intrinsic qualities that supported its original designation.

. State or local removal of a designated route will result in discontinued state support of the designated route and can include, but is not limited to, state matching assistance for grant applications, the removal of signs directly related to the byway, free promotional information in the state-owned safety rest areas, and inclusion in maps, brochures, and electronic media.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5273-S.SL.pdf?cite=1999%20c%20218%20§%207[1999 c 218 § 7]; ]

== 47.39.900 - Short title.
RCW 47.39.010 through 47.39.910 shall constitute a new chapter in Title 47 RCW and shall be known and may be cited as the "Scenic and Recreational Highway Act of 1967."

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c85.pdf?cite=1967%20ex.s.%20c%2085%20§%207[1967 ex.s. c 85 § 7]; ]

== 47.39.910 - Severability—1967 ex.s. c 85.
If any provision of this act, or its application to any person or circumstance is held invalid, the remainder of the act, or the application of the provision to other persons or circumstances is not affected.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c85.pdf?cite=1967%20ex.s.%20c%2085%20§%208[1967 ex.s. c 85 § 8]; ]

