= 47.68 - Aeronautics.
:toc:

== 47.68.010 - Statement of policy.
It is hereby declared that the purpose of this chapter is to further the public interest and aeronautical progress by providing for the protection and promotion of safety in aeronautics; by cooperating in effecting uniformity of the laws and regulations relating to the development and regulation of aeronautics in the several states consistent with federal aeronautics laws and regulations; by granting to a state agency such powers and imposing upon it such duties that the state may properly perform its functions relative to aeronautics and effectively exercise its jurisdiction over persons and property within such jurisdiction, assist in the development of a statewide system of airports, cooperate with and assist the municipalities of this state and others engaged in aeronautics, and encourage and develop aeronautics; by establishing only such regulations as are essential in order that persons engaged in aeronautics of every character may so engage with the least possible restriction, consistent with the safety and the rights of others; and by providing for cooperation with the federal authorities in the development of a national system of civil aviation and for coordination of the aeronautical activities of those authorities and the authorities of this state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c165.pdf?cite=1947%20c%20165%20§%202[1947 c 165 § 2]; Rem. Supp. 1947 § 10964-82; ]

== 47.68.015 - Change of meaning, certain terms.
Unless the language specifically indicates otherwise, or unless the context plainly requires a different interpretation:

Wherever in any provision in the Revised Code of Washington the term "Washington state aeronautics commission", "the state aeronautics commission", "the aeronautics commission of the state", "the aeronautics commission", or "the commission" (when referring to the Washington state aeronautics commission) is used, it shall mean the department of transportation created in RCW 47.01.031.

Wherever in any provision in the Revised Code of Washington the term "state director of aeronautics", "director of aeronautics", or "director" (when referring to the state director of aeronautics) is used, it shall mean the secretary of transportation whose office is created in RCW 47.01.041.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c151.pdf?cite=1977%20ex.s.%20c%20151%20§%2022[1977 ex.s. c 151 § 22]; ]

== 47.68.020 - Definitions.
As used in this chapter, unless the context clearly indicates otherwise:

. "Aeronautics" means the science and art of flight and including but not limited to transportation by aircraft; the operation, construction, repair, or maintenance of aircraft, aircraft power plants and accessories, including the repair, packing, and maintenance of parachutes; the design, establishment, construction, extension, operation, improvement, repair, or maintenance of airports or air navigation facilities; and instruction in flying or ground subjects pertaining thereto.

. "Aircraft" means any contrivance now known, or hereafter invented, used or designed for navigation of or flight in the air.

. "Airport" means any area of land or water which is used, or intended for use, for the landing and take-off of aircraft, and any appurtenant areas which are used, or intended for use, for airport buildings or other airport facilities or right-of-way, together with all airport buildings and facilities located thereon.

. "Department" means the state department of transportation.

. "Secretary" means the state secretary of transportation.

. "State" or "this state" means the state of Washington.

. "Air navigation facility" means any facility, other than one owned or operated by the United States, used in, available for use in, or designed for use in aid of air navigation, including any structures, mechanisms, lights, beacons, markers, communicating systems, or other instrumentalities or devices used or useful as an aid, or constituting an advantage or convenience, to the safe taking-off, navigation, and landing of aircraft, or the safe and efficient operation or maintenance of an airport, and any combination of any or all of such facilities.

. "Operation of aircraft" or "operate aircraft" means the use, navigation, or piloting of aircraft in the airspace over this state or upon any airport within this state.

. "Airman or airwoman" means any individual who engages, as the person in command, or as pilot, mechanic, or member of the crew in the navigation of aircraft while under way, and any individual who is directly in charge of the inspection, maintenance, overhauling, or repair of aircraft engines, airframes, propellers, or appliances, and any individual who serves in the capacity of aircraft dispatcher or air-traffic control tower operator; but does not include any individual employed outside the United States, or any individual employed by a manufacturer of aircraft, aircraft engines, airframes, propellers, or appliances to perform duties as inspector or mechanic in connection therewith, or any individual performing inspection or mechanical duties in connection with aircraft owned or operated by the person.

. "Aeronautics instructor" means any individual who for hire or reward engages in giving instruction or offering to give instruction in flying or ground subjects pertaining to aeronautics, but excludes any instructor in a public school, university, or institution of higher learning duly accredited and approved for carrying on collegiate work, who instructs in flying or ground subjects pertaining to aeronautics, while in the performance of his or her duties at such school, university, or institution.

. "Air school" means any person who advertises, represents, or holds out as giving or offering to give instruction in flying or ground subjects pertaining to aeronautics whether for or without hire or reward; but excludes any public school, university, or institution of higher learning duly accredited and approved for carrying on collegiate work.

. "Person" means any individual, firm, partnership, corporation, company, association, joint stock association, or body politic; and includes any trustee, receiver, assignee, or other similar representative thereof.

. "Municipal" means pertaining to a municipality, and "municipality" means any county, city, town, authority, district, or other political subdivision or public corporation of this state.

. "Airport hazard" means any structure, object of natural growth, or use of land, which obstructs the airspace required for the flight of aircraft in landing or taking off at an airport or is otherwise hazardous to such landing or taking off.

. "State airway" means a route in the navigable airspace over and above the lands or waters of this state, designated by the department as a route suitable for air navigation.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5337-S.SL.pdf?cite=1993%20c%20208%20§%204[1993 c 208 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%20342[1984 c 7 § 342]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c165.pdf?cite=1947%20c%20165%20§%201[1947 c 165 § 1]; Rem. Supp. 1947 § 10964-81; ]

== 47.68.060 - Offices.
Suitable offices and office equipment shall be provided by the state for the aeronautics division of the department of transportation in a city in the state that it may designate, and the department may incur the necessary expense for office furniture, stationery, printing, incidental expenses, and other expenses necessary for the administration of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%20343[1984 c 7 § 343]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c165.pdf?cite=1947%20c%20165%20§%206[1947 c 165 § 6]; Rem. Supp. 1947 § 10964-86; ]

== 47.68.070 - General powers.
The department has general supervision over aeronautics within this state. It is empowered and directed to encourage, foster, and assist in the development of aeronautics in this state and to encourage the establishment of airports and air navigation facilities. It shall cooperate with and assist the federal government, the municipalities of this state, and other persons in the development of aeronautics, and shall seek to coordinate the aeronautical activities of these bodies and persons. Municipalities are authorized to cooperate with the department in the development of aeronautics and aeronautical facilities in this state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%20344[1984 c 7 § 344]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c165.pdf?cite=1947%20c%20165%20§%207[1947 c 165 § 7]; Rem. Supp. 1947 § 10964-87; ]

== 47.68.080 - Drafts of legislation, other duties.
The department may draft and recommend necessary legislation to advance the interests of the state in aeronautics, represent the state in aeronautical matters before federal agencies and other state agencies, and participate as party plaintiff or defendant or as intervener on behalf of the state or any municipality or citizen thereof in any controversy which involves the interest of the state in aeronautics.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%20345[1984 c 7 § 345]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c165.pdf?cite=1947%20c%20165%20§%208[1947 c 165 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c252.pdf?cite=1945%20c%20252%20§%205[1945 c 252 § 5]; Rem. Supp. 1947 § 10964-88; ]

== 47.68.090 - Aid to municipalities, Indian tribes, persons—Federal aid.
. The department of transportation may make available its engineering and other technical services, with or without charge, to any municipality or person desiring them in connection with the planning, acquisition, construction, improvement, maintenance, or operation of airports or air navigation facilities.

. [Empty]
.. The department may render financial assistance by grant or loan, or both, to the following entities out of appropriations made by the legislature for the following purposes:

... Any municipality or municipalities acting jointly in the planning, acquisition, construction, improvement, maintenance, or operation of an airport owned or controlled, or to be owned or controlled by such municipality or municipalities;

... Any Indian tribe recognized as such by the federal government or such tribes acting jointly in the planning, acquisition, construction, improvement, maintenance, or operation of an airport, owned or controlled, or to be owned or controlled by such tribe or tribes, and to be held available for the general use of the public; or

... Any person or persons acting jointly in the planning, acquisition, construction, improvement, maintenance, or operation of an airport, owned or controlled, or to be owned or controlled by such person or persons, and to be held available for the general use of the public.

.. Such financial assistance may be furnished in connection with federal or other financial aid for the same purposes: PROVIDED, That no grant or loan, or both, shall be in excess of seven hundred fifty thousand dollars for any one project: PROVIDED FURTHER, That no grant or loan, or both, shall be granted unless the municipality or municipalities acting jointly, the tribe or tribes acting jointly, or the person or persons acting jointly shall from their own funds match any funds made available by the department upon such ratio as the department may prescribe.

.. The department must establish, by rule, criteria for administering financial assistance to any entity.

. The department is authorized to act as agent of any municipality or municipalities acting jointly, any tribe or tribes acting jointly, or any person or persons acting jointly upon the request of such municipality or municipalities, tribe or tribes, or person or persons in accepting, receiving, receipting for, and disbursing federal moneys, and other moneys public or private, made available to finance, in whole or in part, the planning, acquisition, construction, improvement, maintenance, or operation of an airport or air navigation facility; and if requested by such municipality or municipalities, tribe or tribes, or person or persons, may act as its or their agent in contracting for and supervising such planning, acquisition, construction, improvement, maintenance, or operation; and all municipalities, tribes, and persons are authorized to designate the department as their agent for the foregoing purposes. The department, as principal on behalf of the state, and any municipality on its own behalf, may enter into any contracts, with each other or with the United States or with any person, which may be required in connection with a grant or loan of federal moneys for airport or air navigation facility purposes. All federal moneys accepted under this section shall be accepted and transferred or expended by the department upon such terms and conditions as are prescribed by the United States. All moneys received by the department pursuant to this section shall be deposited in the state treasury, and, unless otherwise prescribed by the authority from which such moneys were received, shall be kept in separate funds designated according to the purposes for which the moneys were made available, and held by the state in trust for such purposes. All such moneys are hereby appropriated for the purposes for which the same were made available, to be disbursed or expended in accordance with the terms and conditions upon which they were made available: PROVIDED, That any landing fee or charge imposed by any Indian tribe or tribes for the privilege of use of an airport facility planned, acquired, constructed, improved, maintained, or operated with financial assistance from the department pursuant to this section must apply equally to tribal and nontribal members: PROVIDED FURTHER, That in the event any municipality or municipalities, Indian tribe or tribes, or person or persons, or any distributor of aircraft fuel as defined by RCW 82.42.010 which operates in any airport facility which has received financial assistance pursuant to this section, fails to collect the aircraft fuel excise tax as specified in chapter 82.42 RCW, all funds or value of technical assistance given or paid to such municipality or municipalities, Indian tribe or tribes, or person or persons under the provisions of this section shall revert to the department, and shall be due and payable to the department immediately.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1018.SL.pdf?cite=2017%20c%2048%20§%202[2017 c 48 § 2]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5337-S.SL.pdf?cite=2011%20c%2051%20§%201[2011 c 51 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5352-S.SL.pdf?cite=2009%20c%20470%20§%20718[2009 c 470 § 718]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c67.pdf?cite=1980%20c%2067%20§%201[1980 c 67 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c161.pdf?cite=1975%201st%20ex.s.%20c%20161%20§%201[1975 1st ex.s. c 161 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c165.pdf?cite=1947%20c%20165%20§%209[1947 c 165 § 9]; Rem. Supp. 1947 § 10964-89; ]

== 47.68.100 - Acquisition and disposal of airports, facilities, etc.
The department is authorized on behalf of and in the name of the state, out of appropriations and other moneys made available for such purposes, to plan, establish, construct, enlarge, improve, maintain, equip, operate, regulate, protect, and police airports, air navigation facilities, and air markers and/or air marking systems, either within or without the state, including the construction, installation, equipment, maintenance, and operation at the airports of buildings and other facilities for the servicing of aircraft or for the comfort and accommodation of air travelers. For such purposes the department may by purchase, gift, devise, lease, condemnation, or otherwise, acquire property, real or personal, or any interest therein, including easements or land outside the boundaries of an airport or airport site, as are necessary to permit safe and efficient operation of the airports or to permit the removal, elimination, marking, or lighting of obstructions or airport hazards, or to prevent the establishment of airport hazards. In like manner the department may acquire existing airports and air navigation facilities. However, it shall not acquire or take over any airport or air navigation facility owned or controlled by a municipality of this or any other state without the consent of the municipality. The department may by sale, lease, or otherwise, dispose of any property, airport, air navigation facility, or portion thereof or interest therein. The disposal by sale, lease, or otherwise shall be in accordance with the laws of this state governing the disposition of other property of the state, except that in the case of disposals to any municipality or state government or the United States for aeronautical purposes incident thereto, the sale, lease, or other disposal may be effected in such manner and upon such terms as the department deems in the best interest of the state. The department may exercise any powers granted by this section jointly with any municipalities, agencies, or departments of the state government, with other states or their municipalities, or with the United States.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%20346[1984 c 7 § 346]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c165.pdf?cite=1947%20c%20165%20§%2010[1947 c 165 § 10]; Rem. Supp. 1947 § 10964-90; ]

== 47.68.110 - Zoning powers not interfered with.
Nothing contained in this chapter shall be construed to limit any right, power or authority of the state or a municipality to regulate airport hazards by zoning.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c165.pdf?cite=1947%20c%20165%20§%2011[1947 c 165 § 11]; Rem. Supp. 1947 § 10964-91; ]

== 47.68.120 - Condemnation, how exercised.
In the condemnation of property authorized by this chapter, the department shall proceed in the name of the state in the manner that property is acquired by the department for public uses.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%20347[1984 c 7 § 347]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c165.pdf?cite=1947%20c%20165%20§%2012[1947 c 165 § 12]; Rem. Supp. 1947 § 10964-92; ]

== 47.68.130 - Contracts or leases of facilities in operating airports.
In operating an airport or air navigation facility owned or controlled by the state, the department may enter into contracts, leases, and other arrangements for a term not exceeding twenty-five years with any persons. The department may grant the privilege of using or improving the airport or air navigation facility or any portion or facility thereof or space therein for commercial purposes, confer the privilege of supplying goods, commodities, things, services, or facilities at the airport or air navigation facility, or make available services to be furnished by the department or its agents at the airport or air navigation facility. In each case the department may establish the terms and conditions and fix the charges, rentals, or fees for the privileges or services, which shall be reasonable and uniform for the same class of privilege or service and shall be established with due regard to the property and improvements used and the cost of operation to the state. In no case shall the public be deprived of its rightful, equal, and uniform use of the airport, air navigation facility, or portion or facility thereof.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%20348[1984 c 7 § 348]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c165.pdf?cite=1947%20c%20165%20§%2013[1947 c 165 § 13]; Rem. Supp. 1947 § 10964-93; ]

== 47.68.140 - Lease of airports.
The department may by contract, lease, or other arrangement, upon a consideration fixed by it, grant to any qualified person for a term not to exceed twenty-five years the privilege of operating, as agent of the state or otherwise, any airport owned or controlled by the state: PROVIDED, That no such person shall be granted any authority to operate the airport other than as a public airport or to enter into any contracts, leases, or other arrangements in connection with the operation of the airport which the department might not have undertaken under RCW 47.68.130.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c3.pdf?cite=1983%20c%203%20§%20141[1983 c 3 § 141]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c165.pdf?cite=1947%20c%20165%20§%2014[1947 c 165 § 14]; Rem. Supp. 1947 § 10964-94; ]

== 47.68.150 - Lien for state's charges.
To enforce the payment of any charges for repairs to, improvements, storage, or care of any personal property made or furnished by the department or its agents in connection with the operation of an airport or air navigation facility owned or operated by the state, the state shall have liens on such property, which shall be enforceable by the department as provided by law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%20349[1984 c 7 § 349]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c165.pdf?cite=1947%20c%20165%20§%2015[1947 c 165 § 15]; Rem. Supp. 1947 § 10964-95; ]

== 47.68.160 - Acceptance of federal moneys.
The department is authorized to accept, receive, receipt for, disburse, and expend federal moneys, and other moneys public or private, made available to accomplish, in whole or in part, any of the purposes of this section. All federal moneys accepted under this section shall be accepted and expended by the department upon such terms and conditions as are prescribed by the United States. In accepting federal moneys under this section, the department shall have the same authority to enter into contracts on behalf of the state as is granted to the department under RCW 47.68.090 with respect to federal moneys accepted on behalf of municipalities. All moneys received by the department pursuant to this section shall be deposited in the state treasury, and, unless otherwise prescribed by the authority from which such moneys were received, shall be kept in separate funds designated according to the purposes for which the moneys were made available, and held by the state in trust for such purposes. All such moneys are hereby appropriated for the purpose of which the same were made available, to be disbursed or expended in accordance with the terms and conditions upon which they were made available.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c3.pdf?cite=1983%20c%203%20§%20142[1983 c 3 § 142]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c165.pdf?cite=1947%20c%20165%20§%2016[1947 c 165 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c252.pdf?cite=1945%20c%20252%20§%207[1945 c 252 § 7]; Rem. Supp. 1947 § 10964-96; ]

== 47.68.170 - State airways system.
The department may designate, design, and establish, expand, or modify a state airways system that will best serve the interest of the state. It may chart the airways system and arrange for publication and distribution of such maps, charts, notices, and bulletins relating to the airways as may be required in the public interest. The system shall be supplementary to and coordinated in design and operation with the federal airways system. It may include all types of air navigation facilities, whether publicly or privately owned, if the facilities conform to federal safety standards.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%20350[1984 c 7 § 350]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c165.pdf?cite=1947%20c%20165%20§%2017[1947 c 165 § 17]; Rem. Supp. 1947 § 10964-97; ]

== 47.68.180 - Execution of necessary contracts.
The department may enter into any contracts necessary to the execution of the powers granted it by this chapter. All contracts made by the department, either as the agent of the state or as the agent of any municipality, shall be made pursuant to the laws of the state governing the making of like contracts. Where the planning, acquisition, construction, improvement, maintenance, or operation of any airport or air navigation facility is financed wholly or partially with federal moneys, the department as agent of the state or of any municipality, may let contracts in the manner prescribed by the federal authorities acting under the laws of the United States and any rules or regulations made thereunder.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%20351[1984 c 7 § 351]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c165.pdf?cite=1947%20c%20165%20§%2018[1947 c 165 § 18]; Rem. Supp. 1947 § 10964-98; ]

== 47.68.185 - Establishment of procedures required by conditions of federal transfers of facilities.
The department is authorized to establish the necessary accounts or administrative procedures required by conditions attached to transfers of airport facilities from the federal government to the state of Washington.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%20352[1984 c 7 § 352]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c73.pdf?cite=1963%20c%2073%20§%201[1963 c 73 § 1]; ]

== 47.68.190 - Exclusive grants prohibited.
The department shall not grant any exclusive right for the use of any landing area or air navigation facility under its jurisdiction. This section shall not be construed to prevent the making of contracts, leases, and other arrangements pursuant to this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%20353[1984 c 7 § 353]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c165.pdf?cite=1947%20c%20165%20§%2019[1947 c 165 § 19]; Rem. Supp. 1947 § 10964-99; ]

== 47.68.200 - Exercise of powers, public and governmental purpose.
The acquisition of any lands or interest therein pursuant to this chapter, the planning, acquisition, establishment, construction, improvement, maintenance, equipment, and operation of airports and air navigation facilities, whether by the state separately or jointly with any municipality or municipalities, and the exercise of any other powers herein granted to the department are public and governmental functions, exercised for a public purpose, and matters of public necessity. All lands and other property and privileges acquired and used by or on behalf of the state in the manner and for the purposes enumerated in this chapter shall and are declared to be acquired and used for public and governmental purposes and as a matter of public necessity.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%20354[1984 c 7 § 354]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c165.pdf?cite=1947%20c%20165%20§%2020[1947 c 165 § 20]; Rem. Supp. 1947 § 10964-100; ]

== 47.68.210 - Rules—Standards.
The department of transportation may perform such acts, issue and amend such orders, make, promulgate, and amend such reasonable general rules, and procedures, and establish such minimum standards, consistent with the provisions of this chapter, as it shall deem necessary to perform its duties hereunder; all commensurate with and for the purpose of protecting and insuring the general public interest and safety, the safety of persons operating, using or traveling in aircraft or persons receiving instruction in flying or ground subjects pertaining to aeronautics, and the safety of persons and property on land or water, and developing and promoting aeronautics in this state. No rule of the department shall apply to airports or air navigation facilities owned or operated by the United States.

The department shall keep on file with the code reviser, and at the principal office of the department, a copy of all its rules for public inspection.

The department shall provide for the publication and general distribution of all its orders, rules, and procedures having general effect.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%20198[1982 c 35 § 198]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c165.pdf?cite=1947%20c%20165%20§%2021[1947 c 165 § 21]; Rem. Supp. 1947 § 10964-101; ]

== 47.68.220 - Operating aircraft recklessly or under influence of intoxicants or drugs.
It shall be unlawful for any person to operate an aircraft in the air, or on the ground or water, while under the influence of intoxicating liquor, narcotics, or other habit-forming drug, or to operate an aircraft in the air or on the ground or water, in a careless manner so as to endanger the life or property of another. In any proceeding charging careless or reckless operation of aircraft in violation of this section, the court in determining whether the operation was careless or reckless may consider the standards for safe operation of aircraft prescribed by federal statutes or regulations governing aeronautics.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c165.pdf?cite=1947%20c%20165%20§%2022[1947 c 165 § 22]; Rem. Supp. 1947 § 10964-102; ]

== 47.68.230 - Aircraft, airman, and airwoman certificates required.
It shall be unlawful for any person to operate or cause or authorize to be operated any civil aircraft within this state unless such aircraft has an appropriate effective certificate, permit, or license issued by the United States, if such certificate, permit, or license is required by the United States, and a current registration certificate issued by the secretary of transportation, if registration of the aircraft with the department of transportation is required by this chapter. It shall be unlawful for any person to engage in aeronautics as an airman or airwoman in the state unless the person has an appropriate effective airman or airwoman certificate, permit, rating, or license issued by the United States authorizing him or her to engage in the particular class of aeronautics in which he or she is engaged, if such certificate, permit, rating, or license is required by the United States.

Where a certificate, permit, rating, or license is required for an airman or airwoman by the United States, it shall be kept in his or her personal possession when he or she is operating within the state. Where a certificate, permit, or license is required by the United States or by this chapter for an aircraft, it shall be carried in the aircraft at all times while the aircraft is operating in the state and shall be conspicuously posted in the aircraft where it may be readily seen by passengers or inspectors. Such certificates shall be presented for inspection upon the demand of any peace officer, or any other officer of the state or of a municipality or member, official, or employee of the department of transportation authorized pursuant to this chapter to enforce the aeronautics laws, or any official, manager, or person in charge of any airport, or upon the reasonable request of any person.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5414-S.SL.pdf?cite=2005%20c%20341%20§%201[2005 c 341 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5337-S.SL.pdf?cite=1993%20c%20208%20§%205[1993 c 208 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c220.pdf?cite=1987%20c%20220%20§%201[1987 c 220 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c158.pdf?cite=1979%20c%20158%20§%20205[1979 c 158 § 205]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c68.pdf?cite=1967%20ex.s.%20c%2068%20§%202[1967 ex.s. c 68 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c9.pdf?cite=1967%20ex.s.%20c%209%20§%207[1967 ex.s. c 9 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c49.pdf?cite=1949%20c%2049%20§%2011[1949 c 49 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c165.pdf?cite=1947%20c%20165%20§%2023[1947 c 165 § 23]; Rem. Supp. 1949 § 10964-103; ]

== 47.68.235 - License or certificate suspension—Noncompliance with support order—Reissuance.
The department shall immediately suspend the license or certificate of a person who has been certified pursuant to RCW 74.20A.320 by the department of social and health services as a person who is not in compliance with a support order or a *residential or visitation order. If the person has continued to meet all other requirements for reinstatement during the suspension, reissuance of the license or certificate shall be automatic upon the department's receipt of a release issued by the department of social and health services stating that the licensee is in compliance with the order.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3901.SL.pdf?cite=1997%20c%2058%20§%20859[1997 c 58 § 859]; ]

== 47.68.240 - Penalties for violations.
. Except as provided in subsection (2) of this section, any person violating any of the provisions of this chapter, or any of the rules, regulations, or orders issued pursuant thereto, is guilty of a misdemeanor.

. [Empty]
.. Any person violating any of the provisions of RCW 47.68.220, 47.68.230, or 47.68.255 is guilty of a gross misdemeanor.

.. In addition to, or in lieu of, the penalties provided in this section, or as a condition to the suspension of a sentence which may be imposed pursuant thereto, for violations of RCW 47.68.220 and 47.68.230, the court in its discretion may prohibit the violator from operating an aircraft within the state for such period as it may determine but not to exceed one year. Violation of the duly imposed prohibition of the court may be treated as a separate offense under this section or as a contempt of court.

. In addition to the provisions of subsections (1) and (2) of this section, failure to register an aircraft, as required by this chapter is subject to a penalty of one hundred dollars if the aircraft registration is sixty days or more past due.

. The revenue from the penalty prescribed in subsection (3) of this section must be deposited into the aeronautics account under RCW 82.42.090.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2413-S.SL.pdf?cite=2016%20c%2020%20§%202[2016 c 20 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5414-S.SL.pdf?cite=2005%20c%20341%20§%202[2005 c 341 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6056.SL.pdf?cite=2003%20c%20375%20§%203[2003 c 375 § 3]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20265[2003 c 53 § 265]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6467-S.SL.pdf?cite=2000%20c%20229%20§%202[2000 c 229 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5706-S.SL.pdf?cite=1999%20c%20277%20§%205[1999 c 277 § 5]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1127-S.SL.pdf?cite=1993%20c%20238%20§%203[1993 c 238 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c202.pdf?cite=1987%20c%20202%20§%20216[1987 c 202 § 216]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c3.pdf?cite=1983%20c%203%20§%20145[1983 c 3 § 145]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c165.pdf?cite=1947%20c%20165%20§%2024[1947 c 165 § 24]; Rem. Supp. 1947 § 10964-104; ]

== 47.68.250 - Registration of aircraft. (Effective until July 1, 2021.)
. Every aircraft must be registered with the department for each calendar year in which the aircraft is operated or is based within this state. A fee of fifteen dollars is charged for each such registration and each annual renewal thereof.

. Possession of the appropriate effective federal certificate, permit, rating, or license relating to ownership and airworthiness of the aircraft, and payment of the excise tax imposed by Title 82 RCW for the privilege of using the aircraft within this state during the year for which the registration is sought, and payment of the registration fee required by this section are the only requisites for registration of an aircraft under this section.

. The registration fee imposed by this section is payable to and collected by the secretary. The fee for any calendar year must be paid during the month of January, and must be collected by the secretary at the time of the collection by him or her of the excise tax. If the secretary is satisfied that the requirements for registration of the aircraft have been met, he or she must issue to the owner of the aircraft a certificate of registration therefor. The secretary must pay to the state treasurer the registration fees collected under this section, which registration fees must be credited to the aeronautics account.

. It is not necessary for the registrant to provide the secretary with originals or copies of federal certificates, permits, ratings, or licenses. The secretary must issue certificates of registration, or such other evidences of registration or payment of fees as he or she may deem proper; and in connection therewith may prescribe requirements for the possession and exhibition of such certificates or other evidences.

. The provisions of this section do not apply to:

.. An aircraft owned by and used exclusively in the service of any government or any political subdivision thereof, including the government of the United States, any state, territory, or possession of the United States, or the District of Columbia, which is not engaged in carrying persons or property for commercial purposes;

.. An aircraft registered under the laws of a foreign country;

.. An aircraft that is owned by a nonresident if:

... The aircraft remains in this state or is based in this state, or both, for a period less than ninety days; or

... The aircraft is a large private airplane as defined in RCW 82.08.215 and remains in this state for a period of ninety days or longer, but only when:

(A) The airplane is in this state exclusively for the purpose of repairs, alterations, or reconstruction, including any flight testing related to the repairs, alterations, or reconstruction, or for the purpose of continual storage of not less than one full calendar year;

(B) An employee of the facility providing these services is on board the airplane during any flight testing; and

(C) Within ninety days of the date the airplane first arrived in this state during the calendar year, the nonresident files a written statement with the department indicating that the airplane is exempt from registration under this subsection (5)(c)(ii). The written statement must be filed in a form and manner prescribed by the department and must include such information as the department requires. The department may require additional periodic verification that the airplane remains exempt from registration under this subsection (5)(c)(ii) and that written statements conform with the provisions of chapter 5.50 RCW;

.. An aircraft engaged principally in commercial flying constituting an act of interstate or foreign commerce;

.. An aircraft owned by the commercial manufacturer thereof while being operated for test or experimental purposes, or for the purpose of training crews for purchasers of the aircraft;

.. An aircraft being held for sale, exchange, delivery, test, or demonstration purposes solely as stock in trade of an aircraft dealer licensed under Title 14 RCW; and

.. An aircraft based within the state that is in an unairworthy condition, is not operated within the registration period, and has obtained a written exemption issued by the secretary.

. The secretary must be notified within thirty days of any change in ownership of a registered aircraft. The notification must contain the N, NC, NR, NL, or NX number of the aircraft, the full name and address of the former owner, and the full name and address of the new owner. For failure to so notify the secretary, the registration of that aircraft may be canceled by the secretary, subject to reinstatement upon application and payment of a reinstatement fee of ten dollars by the new owner.

. A municipality or port district that owns, operates, or leases an airport, as defined in RCW 47.68.020, with the intent to operate, must require from an aircraft owner proof of aircraft registration as a condition of leasing or selling tiedown or hangar space for an aircraft. It is the responsibility of the lessee or purchaser to register the aircraft. Proof of registration must be provided according to the following schedule:

.. For the purchase of tiedown or hangar space, the municipality or port district must allow the purchaser thirty days from the date of the application for purchase to produce proof of aircraft registration.

.. For the lease of tiedown or hangar space that extends thirty days or more, the municipality or port district must allow the lessee thirty days to produce proof of aircraft registration from the date of the application for lease of tiedown or hangar space.

.. For the lease of tiedown or hangar space that extends less than thirty days, the municipality or port district must allow the lessee to produce proof of aircraft registration at any point prior to the final day of the lease.

. The airport must work with the aviation division to assist in its efforts to register aircraft by providing information about based aircraft on an annual basis as requested by the division.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5017-S.SL.pdf?cite=2019%20c%20232%20§%2023[2019 c 232 § 23]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5316.SL.pdf?cite=2017%203rd%20sp.s.%20c%2025%20§%2044[2017 3rd sp.s. c 25 § 44]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2413-S.SL.pdf?cite=2016%20c%2020%20§%203[2016 c 20 § 3]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5882-S.SL.pdf?cite=2013%202nd%20sp.s.%20c%2013%20§%201102[2013 2nd sp.s. c 13 § 1102]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6056.SL.pdf?cite=2003%20c%20375%20§%204[2003 c 375 § 4]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1562-S.SL.pdf?cite=1999%20c%20302%20§%202[1999 c 302 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6229-S.SL.pdf?cite=1998%20c%20188%20§%201[1998 c 188 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1190.SL.pdf?cite=1995%20c%20170%20§%203[1995 c 170 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5337-S.SL.pdf?cite=1993%20c%20208%20§%207[1993 c 208 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c220.pdf?cite=1987%20c%20220%20§%203[1987 c 220 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c158.pdf?cite=1979%20c%20158%20§%20206[1979 c 158 § 206]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c9.pdf?cite=1967%20ex.s.%20c%209%20§%208[1967 ex.s. c 9 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c150.pdf?cite=1955%20c%20150%20§%2011[1955 c 150 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c49.pdf?cite=1949%20c%2049%20§%2012[1949 c 49 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c165.pdf?cite=1947%20c%20165%20§%2025[1947 c 165 § 25]; Rem. Supp. 1949 § 10964-105; ]

== 47.68.255 - Evasive registration.
A person who is required to register an aircraft under this chapter and who registers an aircraft in another state or foreign country evading the Washington aircraft excise tax is guilty of a gross misdemeanor. For a second or subsequent offense, the person convicted is also subject to a fine equal to four times the amount of avoided taxes and fees, no part of which may be suspended, except as provided in RCW 10.05.180. Excise taxes owed and fines assessed must be deposited in the manner provided under RCW 46.16A.030(6).

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5362-S.SL.pdf?cite=2019%20c%20459%20§%204[2019 c 459 § 4]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=2019%20c%20423%20§%20204[2019 c 423 § 204]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201147[2010 c 161 § 1147]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20266[2003 c 53 § 266]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6467-S.SL.pdf?cite=2000%20c%20229%20§%203[2000 c 229 § 3]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5706-S.SL.pdf?cite=1999%20c%20277%20§%206[1999 c 277 § 6]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1967-S.SL.pdf?cite=1996%20c%20184%20§%203[1996 c 184 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1127-S.SL.pdf?cite=1993%20c%20238%20§%202[1993 c 238 § 2]; ]

== 47.68.280 - Investigations, hearings, etc.—Subpoenas—Compelling attendance.
The department or any officer or employee of the department designated by it has the power to hold investigations, inquiries, and hearings concerning matters covered by this chapter including accidents in aeronautics within this state. Hearings shall be open to the public and, except as hereinafter provided, shall be held upon such call or notice as the department deems advisable. The department and every officer or employee of the department designated by it to hold any inquiry, investigation, or hearing has the power to administer oaths and affirmations, certify to all official acts, issue subpoenas, and order the attendance of witnesses and the production of papers, books and documents. In case of the failure of a person to comply with a subpoena or order issued under the authority of this section, the department or its authorized representatives may invoke the aid of a competent court of general jurisdiction. The court may thereupon order the person to comply with the requirements of the subpoena or order or to give evidence touching the matter in question. Failure to obey the order of the court may be punished by the court as a contempt thereof.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%20356[1984 c 7 § 356]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c165.pdf?cite=1947%20c%20165%20§%2028[1947 c 165 § 28]; Rem. Supp. 1947 § 10964-108; ]

== 47.68.290 - Joint hearings—Cooperation.
The department may confer with or hold joint hearings with any agency of the United States in connection with any matter arising under this chapter or relating to the development of aeronautics.

The department may avail itself of the cooperation, services, records, and facilities of the agencies of the United States as fully as may be practicable in the administration and enforcement of this chapter, and shall furnish to the agencies of the United States such services, records, and facilities as are practicable.

The department shall report to the appropriate agency of the United States all accidents in aeronautics in this state of which it is informed, and shall in so far as is practicable preserve, protect, and prevent the removal of the component parts of any aircraft involved in an accident being investigated by it until the federal agency institutes an investigation.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%20357[1984 c 7 § 357]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c165.pdf?cite=1947%20c%20165%20§%2029[1947 c 165 § 29]; Rem. Supp. 1947 § 10964-109; ]

== 47.68.300 - State and municipal agencies to cooperate.
In carrying out this chapter the department may use the facilities and services of other agencies of the state and of the municipalities of the state to the utmost extent possible, and the agencies and municipalities are authorized and directed to make available their facilities and services.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%20358[1984 c 7 § 358]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c165.pdf?cite=1947%20c%20165%20§%2030[1947 c 165 § 30]; Rem. Supp. 1947 § 10964-110; ]

== 47.68.310 - Enforcement of aeronautics laws.
It is the duty of the secretary, the department, the officers and employees of the department, and every state and municipal officer charged with the enforcement of state and municipal laws to enforce and assist in the enforcement of this chapter and of all other laws of this state relating to aeronautics. The secretary and those officers or employees of the department designated by the secretary in writing are granted police powers solely for the enforcement of state aeronautics laws and the rules having the effect of law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%20359[1984 c 7 § 359]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c204.pdf?cite=1955%20c%20204%20§%201[1955 c 204 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c165.pdf?cite=1947%20c%20165%20§%2031[1947 c 165 § 31]; Rem. Supp. 1947 § 10964-111; ]

== 47.68.320 - Service of orders—Hearings—Review.
Every order of the department requiring performance of certain acts or compliance with certain requirements and any denial or revocation of an approval, certificate, or license shall set forth the reasons and shall state the acts to be done or requirements to be met before approval by the department will be given or the approval, license, or certificate granted or restored, or the order modified or changed. Orders issued by the department under this chapter shall be served upon the persons affected either by certified mail or in person. In every case where notice and opportunity for a hearing are required under this chapter, the order of the department shall, on not less than ten days notice, specify a time when and place where the person affected may be heard, or the time within which the person may request a hearing, and the order shall become effective upon the expiration of the time for exercising the opportunity for a hearing, unless a hearing is held or requested within the time provided, in which case the order shall be suspended until the department affirms, disaffirms, or modifies the order after a hearing has been held or default by the person has been affected. To the extent practicable, hearings on the orders shall be in the county where the affected person resides or does business. Any person aggrieved by an order of the department or by the grant, denial, or revocation of an approval, license, or certificate may have the action of the department reviewed by the courts of this state under chapter 34.05 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%20360[1984 c 7 § 360]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c165.pdf?cite=1947%20c%20165%20§%2032[1947 c 165 § 32]; Rem. Supp. 1947 § 10964-112; ]

== 47.68.330 - Exchange of data, reports of violations, etc.
The department is authorized to report to the appropriate federal agencies and agencies of other states all proceedings instituted charging violation of RCW 47.68.220 and 47.68.230 and all penalties, of which it has knowledge, imposed upon airmen or airwomen or the owners or operators of aircraft for violations of the law of this state relating to aeronautics or for violations of the rules, regulations, or orders of the department. The department is authorized to receive reports of penalties and other data from agencies of the federal government and other states and, when necessary, to enter into agreements with federal agencies and the agencies of other states governing the delivery, receipt, exchange, and use of reports and data. The department may make the reports and data of the federal agencies, the agencies of other states, and the courts of this state available, with or without request therefor, to any and all courts of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%2010023[2010 c 8 § 10023]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c3.pdf?cite=1983%20c%203%20§%20146[1983 c 3 § 146]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c165.pdf?cite=1947%20c%20165%20§%2033[1947 c 165 § 33]; Rem. Supp. 1947 § 10964-113; ]

== 47.68.340 - Hazardous structures and obstacles—Marking—Hearing to determine hazard.
A structure or obstacle that obstructs the air space above ground or water level, when determined by the department after a hearing to be a hazard or potential hazard to the safe flight of aircraft, shall be plainly marked, illuminated, painted, lighted, or designated in a manner to be approved in accordance with the general rules of the department so that the structure or obstacle will be clearly visible to airmen or airwomen. In determining which structures or obstacles constitute a safety hazard, or a hazard to flight, the department shall take into account those obstacles located at a river, lake, or canyon crossing, and in other low-altitude flight paths usually traveled by aircraft including, but not limited to, airport areas and runway departure and approach areas as defined by federal air regulations.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%2010024[2010 c 8 § 10024]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1866.SL.pdf?cite=1995%20c%20153%20§%202[1995 c 153 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%20361[1984 c 7 § 361]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c263.pdf?cite=1961%20c%20263%20§%202[1961 c 263 § 2]; ]

== 47.68.350 - Hazardous structures and obstacles—Reporting location—Subpoenas.
The secretary may require owners, operators, lessees, or others having the control or management of structures or obstacles over one hundred fifty feet above ground or water level and that are or may become a hazard to air flight to report the location of the existing or proposed structures or obstacles to the department. For that purpose the secretary may issue subpoenas and subpoenas duces tecum returnable within twenty days to the department. If a person refuses to obey the secretary's subpoena, the department may certify to the superior court all facts of the refusal. The court shall summarily hear evidence on the refusal, and, if the evidence warrants, punish the person refusing in the same manner and to the same extent as a contempt committed before the court.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%20362[1984 c 7 § 362]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c263.pdf?cite=1961%20c%20263%20§%203[1961 c 263 § 3]; ]

== 47.68.360 - Hazardous structures and obstacles—Exemption of structures required by federal law to be marked.
RCW 47.68.340 and 47.68.350 shall not apply to structures required to be marked by federal regulations.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c3.pdf?cite=1983%20c%203%20§%20147[1983 c 3 § 147]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c263.pdf?cite=1961%20c%20263%20§%204[1961 c 263 § 4]; ]

== 47.68.380 - Aerial search and rescue—Liability—Definition.
. The aviation division of the department is responsible for the conduct and management of all aerial search and rescue within the state. This includes search and rescue efforts involving aircraft and airships. The division is also responsible for search and rescue activities involving electronic emergency signaling devices such as emergency locater transmitters (ELT's) and emergency position indicating radio beacons (EPIRB's).

. An act or omission by any person registered with the aviation division of the department for the purpose of engaging in aerial search and rescue activities, while engaged in such activities, shall not impose any liability on the department or the person for civil damages resulting from the act or omission. However, the immunity provided under this subsection shall not apply to an act or omission that constitutes gross negligence or willful or wanton misconduct. For the purpose of this subsection, "aerial search and rescue activities" includes, but is not limited to, training and training-related activities, but does not include appropriate search and rescue activities conducted under the authority of RCW 38.52.400.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6324-S.SL.pdf?cite=2008%20c%2034%20§%201[2008 c 34 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1866.SL.pdf?cite=1995%20c%20153%20§%201[1995 c 153 § 1]; ]

== 47.68.390 - Airport capacity and facilities assessment.
. The aviation division of the department of transportation shall conduct a statewide airport capacity and facilities assessment. The assessment must include a statewide analysis of existing airport facilities, and passenger and air cargo transportation capacity, regarding both commercial aviation and general aviation; however, the primary focus of the assessment must be on commercial aviation. The assessment must at a minimum address the following issues:

.. Existing airport facilities, both commercial and general aviation, including air side, land side, and airport service facilities;

.. Existing air and airport capacity, including the number of annual passengers and air cargo operations;

.. Existing airport services, including fixed based operator services, fuel services, and ground services; and

.. Existing airspace capacity.

. The department shall consider existing information, technical analyses, and other research the department deems appropriate. The department may contract and consult with private independent professional and technical experts regarding the assessment.

. The department shall submit the assessment to the appropriate standing committees of the legislature, the governor, the transportation commission, and regional transportation planning organizations by July 1, 2006.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5121-S.SL.pdf?cite=2005%20c%20316%20§%201[2005 c 316 § 1]; ]

== 47.68.400 - Airport capacity and facilities market analysis.
. After submitting the assessment under RCW 47.68.390, the aviation division of the department of transportation shall conduct a statewide airport capacity and facilities market analysis. The analysis must include a statewide needs analysis of airport facilities, passenger and air cargo transportation capacity, and demand and forecast market needs over the next twenty-five years with a more detailed analysis of the Puget Sound, southwest Washington, Spokane, and Tri-Cities regions. The analysis must address the forecasted needs of both commercial aviation and general aviation; however, the primary focus of the analysis must be on commercial aviation. The analysis must at a minimum address the following issues:

.. A forecast of future airport facility needs based on passenger and air cargo operations and demand, airline planning, and a determination of aviation trends, demographic, geographic, and market factors that may affect future air travel demand;

.. A determination of when the state's existing commercial service airports will reach their capacity;

.. The factors that may affect future air travel and when capacity may be reached and in which location;

.. The role of the state, metropolitan planning organizations, regional transportation planning organizations, the federal aviation administration, and airport sponsors in addressing statewide airport facilities and capacity needs; and

.. Whether the state, metropolitan planning organizations, regional transportation planning organizations, the federal aviation administration, or airport sponsors have identified options for addressing long-range capacity needs at airports, or in regions, that will reach capacity before the year 2030.

. The department shall consider existing information, technical analyses, and other research the department deems appropriate. The department may contract and consult with private independent professional and technical experts regarding the analysis.

. The department shall submit the analysis to the appropriate standing committees of the legislature, the governor, the transportation commission, and regional transportation planning organizations by July 1, 2007.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5121-S.SL.pdf?cite=2005%20c%20316%20§%202[2005 c 316 § 2]; ]

