= 47.72 - Navigation canals.
:toc:

== 47.72.010 - Declaration of purpose.
The purposes of this chapter are to aid commerce and navigation, including the development of recreational facilities related thereto, and to otherwise promote the general welfare by the development of navigation canals within the boundaries of the state of Washington.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c123.pdf?cite=1965%20ex.s.%20c%20123%20§%201[1965 ex.s. c 123 § 1]; ]

== 47.72.050 - Powers and duties.
In its capacity as successor to the canal commission, the department of transportation may:

. Adopt rules and regulations necessary to carry out the purposes of this chapter.

. Make such investigations, surveys, and studies it deems necessary to determine the feasibility of the development of a navigation canal, or systems of navigation canals within the state of Washington.

. Construct, maintain, and/or operate any navigation canal, or navigation canal systems deemed feasible by the department of transportation.

. Acquire by gift, purchase, or condemnation from any person, municipal, public, or private corporation, or the state of Washington, or lease from the United States of America, any lands, rights-of-way, easements, or property rights in, over, or across lands or waters necessary for the construction, operation, or maintenance of any navigation canal, or navigation canal system. The acquisition of such rights is for a public use. The exercise of the right of eminent domain shall be in the manner provided by chapter 8.04 RCW, and all actions initiated thereunder shall be brought in the name of the department of transportation.

. Hold public hearings. Prior to a determination of feasibility for any proposed project, the department shall hold a public hearing so that members of the public may present their views thereon.

. Accept and expend moneys appropriated by the legislature or received from any public or private source, including the federal government, in carrying out the purposes of this chapter.

. Negotiate and cooperate with the United States of America for the purpose of inducing the United States to undertake the construction, operation, or maintenance of any navigation canal, or navigation canal system provided for in this chapter.

. As a local sponsor cooperate, contract, and otherwise fully participate on behalf of the state of Washington with the United States of America, in any study relating to a determination of feasibility of a navigation canal or navigation canal system, and in any project relating to the construction, operation, or maintenance of a navigation canal, or navigation canal system to be undertaken by the United States of America.

The authority granted herein includes, but is not limited to, contributing such moneys to the United States of America as may be required and appropriated for that purpose by the legislature and furnishing without cost to the United States of America all lands, easements, and rights-of-way, performing all necessary alterations to utilities arising from any project, and holding the United States of America free from any claims for damages arising out of the construction of any project.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c151.pdf?cite=1977%20ex.s.%20c%20151%20§%2075[1977 ex.s. c 151 § 75]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c123.pdf?cite=1965%20ex.s.%20c%20123%20§%205[1965 ex.s. c 123 § 5]; ]

== 47.72.060 - "Canal" defined.
For the purposes of this chapter, "canal" is defined as any waterway for navigation created by construction of reservoirs or construction of channels by excavation in dry ground, in streams, rivers or in tidal waters and any existing waterway incorporated into such a canal and including any appurtenant features necessary for operation and maintenance of the canal.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c123.pdf?cite=1965%20ex.s.%20c%20123%20§%206[1965 ex.s. c 123 § 6]; ]

