= 47.85 - Transportation project delivery and review.
:toc:

== 47.85.005 - Intent.
It is the intent of the legislature to achieve transportation regulatory reform that expedites the delivery of transportation projects through a streamlined approach to environmental decision making. The department of transportation should work cooperatively and proactively with state regulatory and natural resource agencies, public and private sector interests, and Indian tribes to avoid project delays. The department and state regulatory and natural resource agencies should continue to implement and improve upon the successful policies, guidance, tools, and procedures that were created as a result of transportation permit efficiency and accountability committee efforts. The department should expedite project delivery and routine maintenance activities through the use of programmatic agreements and permits where possible and seek new opportunities to eliminate duplicative processes.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5996-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%2017%20§%201[2015 3rd sp.s. c 17 § 1]; ]

== 47.85.010 - Legislative declaration.
The legislature recognizes the value that tribal governments provide in the review of transportation projects. The legislature expects the department to continue its efforts to provide consistent consultation and communication during the environmental review of proposed transportation projects.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5996-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%2017%20§%202[2015 3rd sp.s. c 17 § 2]; ]

== 47.85.020 - Multiagency permit program—Federal act compliance—Permit application guidance, quality control.
The department must streamline the permitting process by developing and maintaining positive relationships with the regulatory agencies and the Indian tribes. The department can reduce the time it takes to obtain permits by incorporating impact avoidance and minimization measures into project design and by developing complete permit applications. To streamline the permitting process, the department must:

. Implement a multiagency permit program, commensurate with program funding levels, consisting of appropriate regulatory agency staff with oversight and management from the department.

.. The multiagency permit program must provide early project coordination, expedited project review, project status updates, technical and regulatory guidance, and construction support to ensure compliance.

.. The multiagency permit program staff must assist department project teams with developing complete biological assessments and permit applications, provide suggestions for how the project can avoid and minimize impacts, and provide input regarding mitigation for unavoidable impacts;

. Establish, implement, and maintain programmatic agreements and permits with federal and state agencies to expedite the process of ensuring compliance with the endangered species act, section 106 of the national historic preservation act, hydraulic project approvals, the clean water act, and other federal acts as appropriate;

. Collaborate with permitting staff from the United States army corps of engineers, Seattle district, department of ecology, and department of fish and wildlife to develop, implement, and maintain complete permit application guidance. The guidance must identify the information that is required for agencies to consider a permit application complete; and

. Perform internal quality assurance and quality control to ensure that permit applications are complete before submitting them to the regulatory agencies.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5996-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%2017%20§%203[2015 3rd sp.s. c 17 § 3]; ]

== 47.85.030 - Finding—Environmental review and oversight.
The legislature finds that an essential component of streamlined permit decision making is the ability of the department to demonstrate the capacity to meet environmental responsibilities. Therefore, the legislature directs that:

. Qualified environmental staff within the department must supervise the development of all environmental documentation in accordance with the department's project delivery tools;

. The department must conduct special prebid meetings for projects that are environmentally complex. In addition, the department must review environmental requirements related to these projects during the preconstruction meeting held with the contractor who is awarded the bid;

. Environmental staff at the department, or consultant staff hired directly by the department, must conduct field inspections to ensure that project activities comply with permit conditions and environmental commitments. These inspectors:

.. Must notify the department's project engineer when compliance with permit conditions or environmental regulations are not being met; and

.. Must immediately notify the regulatory agencies with jurisdiction over the nonconforming work; and

. When a project is not complying with a permit or environmental regulation, the project engineer must immediately order the contractor to stop all nonconforming work and implement measures necessary to bring the project into compliance with permits and regulations.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5996-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%2017%20§%204[2015 3rd sp.s. c 17 § 4]; ]

== 47.85.040 - Environmental training and compliance.
The legislature expects the department to continue its efforts to improve training and compliance. The department must:

. Provide training in environmental procedures and permit requirements for those responsible for project delivery activities;

. Require wetland mitigation sites to be designed by qualified technical specialists that meet training requirements developed by the department in consultation with the department of ecology. Environmental mitigation site improvements must have oversight by environmental staff;

. Develop, implement, and maintain an environmental compliance data system to track permit conditions, environmental commitments, and violations;

. Continue to implement the environmental compliance assurance procedure to ensure that appropriate agencies are notified and that action is taken to remedy noncompliant work as soon as possible. When work occurs that does not comply with environmental permits or regulations, the project engineer must document the lessons learned to make other project teams within the department aware of the violation to prevent reoccurrence; and

. Provide an annual report summarizing violations of environmental permits and regulations to the department of ecology and the legislature on March 1st of each year for violations occurring during the preceding year.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5996-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%2017%20§%205[2015 3rd sp.s. c 17 § 5]; ]

== 47.85.050 - Finding—Local land use review procedures.
The legislature finds that local land use reviews under chapter 90.58 RCW need to be harmonized with the efficient accomplishment of necessary maintenance and improvement to state transportation facilities. Local land use review procedures are highly variable and pose distinct challenges for linear facility maintenance and improvement projects sponsored by the department. In particular, clearer procedures for local permitting under chapter 90.58 RCW are needed to meet the objectives of chapter 36.70A RCW regarding department facilities designated as essential public facilities.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5996-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%2017%20§%206[2015 3rd sp.s. c 17 § 6]; ]

== 47.85.100 - Construction—Judicial review.
Nothing in this chapter may be interpreted to create a private right of action or right of review. Judicial review of the department's environmental review is limited to that available under chapter 43.21C RCW or applicable federal law.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5996-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%2017%20§%207[2015 3rd sp.s. c 17 § 7]; ]

