= 47.82 - Amtrak.
:toc:

== 47.82.010 - Service improvement program.
The department, in conjunction with local jurisdictions, shall coordinate as appropriate with the designated metropolitan planning organizations to develop a program for improving Amtrak passenger rail service. The program may include:

. Determination of the appropriate level of Amtrak passenger rail service;

. Implementation of higher train speeds for Amtrak passenger rail service, where safety considerations permit;

. Recognition, in the state's long-range planning process, of potential higher speed intercity passenger rail service, while monitoring socioeconomic and technological conditions as indicators for higher speed systems; and

. Identification of existing intercity rail rights-of-way which may be used for public transportation corridors in the future.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c43.pdf?cite=1990%20c%2043%20§%2036[1990 c 43 § 36]; ]

== 47.82.020 - Depot upgrading.
The department shall, when feasible, assist local jurisdictions in upgrading Amtrak depots. Multimodal use of these facilities shall be encouraged.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c43.pdf?cite=1990%20c%2043%20§%2037[1990 c 43 § 37]; ]

== 47.82.030 - Service extension.
. The department, in conjunction with local jurisdictions, shall coordinate as appropriate with designated metropolitan and provincial transportation organizations to pursue resumption of Amtrak service from Seattle to Vancouver, British Columbia, via Everett, Mount Vernon, and Bellingham.

. The department, in conjunction with local jurisdictions, shall study potential Amtrak service on the following routes:

.. Daytime Spokane-Wenatchee-Everett-Seattle service;

.. Daytime Spokane-Tri-Cities-Vancouver-Portland service;

.. Tri-Cities-Yakima-Ellensburg-Seattle service, if the Stampede Pass route is reopened; and

.. More frequent Portland-Vancouver-Kelso-Centralia-Olympia-Tacoma-Seattle service or increments thereof.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c43.pdf?cite=1990%20c%2043%20§%2038[1990 c 43 § 38]; ]

== 47.82.040 - Coordination with other rail systems and common carriers.
The department, with other state and local agencies shall coordinate as appropriate with designated metropolitan planning organizations to provide public information with respect to common carrier passenger transportation. This information may include maps, routes, and schedules of passenger rail service, local transit agencies, air carriers, private ground transportation providers, and international, state, and local ferry services.

The state shall continue its cooperative relationship with Amtrak and Canadian passenger rail systems.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c43.pdf?cite=1990%20c%2043%20§%2039[1990 c 43 § 39]; ]

== 47.82.900 - Construction—Severability—Headings—1990 c 43.
See notes following RCW 81.100.010.

[ ]

