= 34.12 - Office of administrative hearings.
:toc:

== 34.12.010 - Office created—Conduct of hearings—Chief administrative law judge, appointment, term, qualifications, removal.
A state office of administrative hearings is hereby created. The office shall be independent of state administrative agencies and shall be responsible for impartial administration of administrative hearings in accordance with the legislative intent expressed by this chapter. Hearings shall be conducted with the greatest degree of informality consistent with fairness and the nature of the proceeding. The office shall be under the direction of a chief administrative law judge, appointed by the governor with the advice and consent of the senate, for a term of five years. The person appointed is required, as a condition of appointment, to be admitted to practice law in the state of Washington, and may be removed for cause.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c67.pdf?cite=1981%20c%2067%20§%201[1981 c 67 § 1]; ]

== 34.12.020 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Administrative law judge" means any person appointed by the chief administrative law judge to conduct or preside over hearings as provided in this chapter.

. "Hearing" means an adjudicative proceeding within the meaning of RCW 34.05.010(1) conducted by a state agency under RCW 34.05.413 through 34.05.476.

. "Office" means the office of administrative hearings.

. "State agency" means any state board, commission, department, or officer authorized by law to make rules or to conduct adjudicative proceedings, except those in the legislative or judicial branches, the growth management hearings board, the utilities and transportation commission, the pollution control hearings board, the shorelines hearings board, the forest practices appeals board, the *environmental hearings office, the board of industrial insurance appeals, the Washington personnel resources board, the public employment relations commission, and the board of tax appeals.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6214-S.SL.pdf?cite=2010%20c%20211%20§%2016[2010 c 211 § 16]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1268-S.SL.pdf?cite=2002%20c%20354%20§%20226[2002 c 354 § 226]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1722-S.SL.pdf?cite=1995%20c%20331%20§%201[1995 c 331 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6339-S.SL.pdf?cite=1994%20c%20257%20§%2022[1994 c 257 § 22]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2054-S.SL.pdf?cite=1993%20c%20281%20§%2016[1993 c 281 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c175.pdf?cite=1989%20c%20175%20§%2033[1989 c 175 § 33]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c189.pdf?cite=1982%20c%20189%20§%201[1982 c 189 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c67.pdf?cite=1981%20c%2067%20§%202[1981 c 67 § 2]; ]

== 34.12.030 - Administrative law judges—Appointment and contractual basis—Clerical personnel—Discipline and termination of administrative law judges—Civil service—Rules for operation of office.
. The chief administrative law judge shall appoint administrative law judges to fulfill the duties prescribed in this chapter. All administrative law judges shall have a demonstrated knowledge of administrative law and procedures. The chief administrative law judge may establish different levels of administrative law judge positions.

. The chief administrative law judge may also contract with qualified individuals to serve as administrative law judges for specified hearings. Such individuals shall be compensated for their services on a contractual basis for each hearing, in accordance with chapter 43.88 RCW. The chief administrative law judge may not contract with any individual who is at that time an employee of the state.

. The chief administrative law judge may appoint such clerical and other specialized or technical personnel as may be necessary to carry on the work of this chapter.

. Subject to any collective bargaining agreement, the administrative law judges appointed under subsection (1) of this section are subject to discipline and termination, for cause, by the chief administrative law judge. Upon written request by the person so disciplined or terminated, the chief administrative law judge shall forthwith put the reasons for such action in writing. The person affected has a right of review by the superior court of Thurston county on petition for reinstatement or other remedy filed within thirty days of receipt of such written reasons.

. All employees of the office except the chief administrative law judge and the administrative law judges are subject to chapter 41.06 RCW.

. Administrative law judges appointed under subsection (1) of this section have the right to collectively bargain under chapter 41.80 RCW, regardless of their exemption from chapter 41.06 RCW.

. The office may adopt rules for its own operation and in furtherance of this chapter in accordance with chapter 34.05 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2017-S.SL.pdf?cite=2020%20c%2077%20§%205[2020 c 77 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c67.pdf?cite=1981%20c%2067%20§%203[1981 c 67 § 3]; ]

== 34.12.034 - Retail internet service adequacy proceedings.
When requested by the public utility district commissioners, the chief administrative law judge shall assign an administrative law judge to conduct proceedings under RCW 54.16.420.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6034-S.SL.pdf?cite=2018%20c%20186%20§%202[2018 c 186 § 2]; ]

== 34.12.035 - State patrol disciplinary hearings.
The chief administrative law judge shall designate an administrative law judge to serve, as the need arises, as presiding officer in state patrol disciplinary hearings conducted under RCW 43.43.090.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c141.pdf?cite=1984%20c%20141%20§%206[1984 c 141 § 6]; ]

== 34.12.036 - Landlord-tenant proceedings.
When requested by the attorney general, the chief administrative law judge shall assign an administrative law judge to conduct proceedings under Title 59 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1461-S2.SL.pdf?cite=2007%20c%20431%20§%209[2007 c 431 § 9]; ]

== 34.12.037 - Human rights commission proceedings.
When requested by the state human rights commission, the chief administrative law judge shall assign an administrative law judge to conduct proceedings under chapter 49.60 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c185.pdf?cite=1985%20c%20185%20§%2029[1985 c 185 § 29]; ]

== 34.12.038 - Local government whistleblower proceedings.
When requested by a local government, the chief administrative law judge shall assign an administrative law judge to conduct proceedings under chapter 42.41 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6321-S.SL.pdf?cite=1992%20c%2044%20§%208[1992 c 44 § 8]; ]

== 34.12.039 - Local government whistleblower proceedings—Costs.
Costs for the services of the office of administrative hearings for the initial twenty-four hours of services on a hearing under chapter 42.41 RCW shall be billed to the local government administrative hearings account. Costs for services beyond the initial twenty-four hours of services shall be allocated to the parties by the administrative law judge, the proportion to be borne by each party at the discretion of the administrative law judge. The charges for these costs shall be billed to the affected local government that shall recover payment from any other party specified by the administrative law judge.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6321-S.SL.pdf?cite=1992%20c%2044%20§%209[1992 c 44 § 9]; ]

== 34.12.040 - Hearings conducted by administrative law judges—Criteria for assignment.
Except pursuant to RCW 43.70.740, whenever a state agency conducts a hearing which is not presided over by officials of the agency who are to render the final decision, the hearing shall be conducted by an administrative law judge assigned under this chapter. In assigning administrative law judges, the chief administrative law judge shall wherever practical (1) use personnel having expertise in the field or subject matter of the hearing, and (2) assign administrative law judges primarily to the hearings of particular agencies on a long-term basis.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1381-S.SL.pdf?cite=2013%20c%20109%20§%205[2013 c 109 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c67.pdf?cite=1981%20c%2067%20§%204[1981 c 67 § 4]; ]

== 34.12.050 - Administrative law judge—Motion of prejudice against—Request for assignment of.
. Any party to a hearing being conducted under the provisions of this chapter (including the state agency, whether or not it is nominally a party) may file with the chief administrative law judge a motion of prejudice, with supporting affidavit, against the administrative law judge assigned to preside at the hearing. The first such motion filed by any party shall be automatically granted.

. Any state agency may request from the chief administrative law judge the assignment of an administrative law judge for the purpose of conducting a rule-making or investigatory proceeding.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c67.pdf?cite=1981%20c%2067%20§%205[1981 c 67 § 5]; ]

== 34.12.060 - Initial decision or proposal for decision—Findings of fact and conclusions of law—Inapplicability to state patrol disciplinary hearings.
When an administrative law judge presides at a hearing under this chapter and a majority of the officials of the agency who are to render the final decision have not heard substantially all of the oral testimony and read all exhibits submitted by any party, it shall be the duty of such judge, or in the event of his or her unavailability or incapacity, of another judge appointed by the chief administrative law judge, to issue an initial decision or proposal for decision including findings of fact and conclusions of law in accordance with RCW 34.05.461 or 34.05.485. However, this section does not apply to a state patrol disciplinary hearing conducted under RCW 43.43.090.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20763[2011 c 336 § 763]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c175.pdf?cite=1989%20c%20175%20§%2034[1989 c 175 § 34]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c141.pdf?cite=1984%20c%20141%20§%207[1984 c 141 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c189.pdf?cite=1982%20c%20189%20§%202[1982 c 189 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c67.pdf?cite=1981%20c%2067%20§%206[1981 c 67 § 6]; ]

== 34.12.070 - Record of hearings.
The chief administrative law judge may establish a method of making a record of all hearings and may employ or contract in order to implement such method.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c67.pdf?cite=1981%20c%2067%20§%207[1981 c 67 § 7]; ]

== 34.12.080 - Procedural conduct of hearings—Rules.
All hearings shall be conducted in conformance with the Administrative Procedure Act, chapter 34.05 RCW. After consultation with affected agencies, the chief administrative law judge may promulgate rules governing the procedural conduct of the hearings. Such rules shall seek the maximum procedural uniformity in agency hearings consistent with demonstrable needs for individual agency variation.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c67.pdf?cite=1981%20c%2067%20§%208[1981 c 67 § 8]; ]

== 34.12.090 - Transfer of employees and equipment.
. All state employees who have exclusively or principally conducted or presided over hearings for state agencies prior to July 1, 1982, shall be transferred to the office.

. All state employees who have exclusively or principally served as support staff for those employees transferred under subsection (1) of this section shall be transferred to the office.

. All equipment or other tangible property in possession of state agencies, used or held exclusively or principally by personnel transferred under subsection (1) of this section shall be transferred to the office unless the office of financial management, in consultation with the head of the agency and the chief administrative law judge, determines that the equipment or property will be more efficiently used by the agency if such property is not transferred.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c67.pdf?cite=1981%20c%2067%20§%209[1981 c 67 § 9]; ]

== 34.12.100 - Salaries.
The chief administrative law judge shall be paid a salary fixed by the governor after recommendation of the director of financial management. Subject to any collective bargaining agreement, the salaries of administrative law judges appointed under the terms of this chapter shall be determined by the chief administrative law judge after recommendation of the director of financial management.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2017-S.SL.pdf?cite=2020%20c%2077%20§%206[2020 c 77 § 6]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5315-S2.SL.pdf?cite=2015%203rd%20sp.s.%20c%201%20§%20310[2015 3rd sp.s. c 1 § 310]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5931-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2043%20§%20469[2011 1st sp.s. c 43 § 469]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2617-S2.SL.pdf?cite=2010%201st%20sp.s.%20c%207%20§%203[2010 1st sp.s. c 7 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c155.pdf?cite=1986%20c%20155%20§%2010[1986 c 155 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c67.pdf?cite=1981%20c%2067%20§%2010[1981 c 67 § 10]; ]

== 34.12.110 - Application of chapter.
The creation of the office of administrative hearings and the transfer of duties and personnel under this chapter shall not affect the validity of any rule, action, decision, or proceeding held or promulgated by any state agency before July 1, 1982. This chapter applies to hearings occurring after July 1, 1982.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c67.pdf?cite=1981%20c%2067%20§%2011[1981 c 67 § 11]; ]

== 34.12.120 - Appointment of chief administrative law judge.
The governor shall appoint the chief administrative law judge.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c175.pdf?cite=1989%20c%20175%20§%2035[1989 c 175 § 35]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c67.pdf?cite=1981%20c%2067%20§%2012[1981 c 67 § 12]; ]

== 34.12.130 - Administrative hearings revolving fund—Created, purposes.
The administrative hearings revolving fund is hereby created in the state treasury for the purpose of centralized funding, accounting, and distribution of the actual costs of the services provided to agencies of the state government by the office of administrative hearings.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c189.pdf?cite=1982%20c%20189%20§%209[1982 c 189 § 9]; ]

== 34.12.140 - Transfers and payments into revolving fund—Limitation on employment security department payments—Allotment by director of financial management—Disbursements from fund by voucher.
The amounts to be disbursed from the administrative hearings revolving fund from time to time shall be transferred thereto by the state treasurer from funds appropriated to any and all agencies for administrative hearings expenses on a quarterly basis. Agencies operating in whole or in part from nonappropriated funds shall pay into the administrative hearings revolving fund such funds as will fully reimburse funds appropriated to the office of administrative hearings for any services provided activities financed by nonappropriated funds. The funds from the employment security department for the administrative hearings services provided by the office of administrative hearings shall not exceed that portion of the resources provided to the employment security department by the department of labor, employment and training administration, for such administrative hearings services. To satisfy department of labor funding requirements, the office of administrative hearings shall meet or exceed timeliness standards under federal regulations in the conduct of employment security department appeals.

The director of financial management shall allot all such funds to the office of administrative hearings for the operation of the office, pursuant to appropriation, in the same manner as appropriated funds are allocated to other agencies under chapter 43.88 RCW.

Disbursements from the administrative hearings revolving fund shall be pursuant to vouchers executed by the chief administrative law judge or his or her designee.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20764[2011 c 336 § 764]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c189.pdf?cite=1982%20c%20189%20§%2010[1982 c 189 § 10]; ]

== 34.12.150 - Accounting procedures.
The chief administrative law judge shall keep such records as are necessary to facilitate proper allocation of costs to funds and agencies served and the director of financial management shall prescribe appropriate accounting procedures to accurately allocate costs to funds and agencies served. Billings shall be adjusted in line with actual costs incurred at intervals not to exceed six months.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c189.pdf?cite=1982%20c%20189%20§%2011[1982 c 189 § 11]; ]

== 34.12.160 - Direct payments by agencies, when authorized.
In cases where there are unanticipated demands for services of the office of administrative hearings or where there are insufficient funds on hand or available for payment through the administrative hearings revolving fund or in other cases of necessity, the chief administrative law judge may request payment for services directly from agencies for whom the services are performed to the extent that revenues or other funds are available. Upon approval by the director of financial management, the agency shall make the requested payment. The payment may be made on either an advance or reimbursable basis as approved by the director of financial management.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c189.pdf?cite=1982%20c%20189%20§%2012[1982 c 189 § 12]; ]

