= 84.14 - New and rehabilitated multiple-unit dwellings in urban centers.
:toc:

== 84.14.005 - Findings.
The legislature finds:

. That in many of Washington's urban centers there is insufficient availability of desirable and convenient residential units, including affordable housing units, to meet the needs of a growing number of the public who would live in these urban centers if these desirable, convenient, attractive, affordable, and livable places to live were available;

. That the development of additional and desirable residential units, including affordable housing units, in these urban centers that will attract and maintain a significant increase in the number of permanent residents in these areas will help to alleviate the detrimental conditions and social liability that tend to exist in the absence of a viable mixed income residential population and will help to achieve the planning goals mandated by the growth management act under RCW 36.70A.020; and

. That planning solutions to solve the problems of urban sprawl often lack incentive and implementation techniques needed to encourage residential redevelopment in those urban centers lacking a sufficient variety of residential opportunities, and it is in the public interest and will benefit, provide, and promote the public health, safety, and welfare to stimulate new or enhanced residential opportunities, including affordable housing opportunities, within urban centers through a tax incentive as provided by this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1910-S2.SL.pdf?cite=2007%20c%20430%20§%201[2007 c 430 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5387-S2.SL.pdf?cite=1995%20c%20375%20§%201[1995 c 375 § 1]; ]

== 84.14.007 - Purpose.
It is the purpose of this chapter to encourage increased residential opportunities, including affordable housing opportunities, in cities that are required to plan or choose to plan under the growth management act within urban centers where the governing authority of the affected city has found there is insufficient housing opportunities, including affordable housing opportunities. It is further the purpose of this chapter to stimulate the construction of new multifamily housing and the rehabilitation of existing vacant and underutilized buildings for multifamily housing in urban centers having insufficient housing opportunities that will increase and improve residential opportunities, including affordable housing opportunities, within these urban centers. To achieve these purposes, this chapter provides for special valuations in residentially deficient urban centers for eligible improvements associated with multiunit housing, which includes affordable housing. It is an additional purpose of this chapter to allow unincorporated areas of rural counties that are within urban growth areas to stimulate housing opportunities and for certain counties to stimulate housing opportunities near college campuses to promote dense, transit-oriented, walkable college communities.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6330-S2.SL.pdf?cite=2014%20c%2096%20§%202[2014 c 96 § 2]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6277-S.SL.pdf?cite=2012%20c%20194%20§%201[2012 c 194 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1910-S2.SL.pdf?cite=2007%20c%20430%20§%202[2007 c 430 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5387-S2.SL.pdf?cite=1995%20c%20375%20§%202[1995 c 375 § 2]; ]

== 84.14.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Affordable housing" means residential housing that is rented by a person or household whose monthly housing costs, including utilities other than telephone, do not exceed thirty percent of the household's monthly income. For the purposes of housing intended for owner occupancy, "affordable housing" means residential housing that is within the means of low or moderate-income households.

. "Campus facilities master plan" means the area that is defined by the University of Washington as necessary for the future growth and development of its campus facilities for campuses authorized under RCW 28B.45.020.

. "City" means either (a) a city or town with a population of at least fifteen thousand, (b) the largest city or town, if there is no city or town with a population of at least fifteen thousand, located in a county planning under the growth management act, or (c) a city or town with a population of at least five thousand located in a county subject to the provisions of RCW 36.70A.215.

. "County" means a county with an unincorporated population of at least three hundred fifty thousand.

. "Governing authority" means the local legislative authority of a city or a county having jurisdiction over the property for which an exemption may be applied for under this chapter.

. "Growth management act" means chapter 36.70A RCW.

. "High cost area" means a county where the third quarter median house price for the previous year as reported by the Washington center for real estate research at Washington State University is equal to or greater than one hundred thirty percent of the statewide median house price published during the same time period.

. "Household" means a single person, family, or unrelated persons living together.

. "Low-income household" means a single person, family, or unrelated persons living together whose adjusted income is at or below eighty percent of the median family income adjusted for family size, for the county where the project is located, as reported by the United States department of housing and urban development. For cities located in high-cost areas, "low-income household" means a household that has an income at or below one hundred percent of the median family income adjusted for family size, for the county where the project is located.

. "Moderate-income household" means a single person, family, or unrelated persons living together whose adjusted income is more than eighty percent but is at or below one hundred fifteen percent of the median family income adjusted for family size, for the county where the project is located, as reported by the United States department of housing and urban development. For cities located in high-cost areas, "moderate-income household" means a household that has an income that is more than one hundred percent, but at or below one hundred fifty percent, of the median family income adjusted for family size, for the county where the project is located.

. "Multiple-unit housing" means a building having four or more dwelling units not designed or used as transient accommodations and not including hotels and motels. Multifamily units may result from new construction or rehabilitated or conversion of vacant, underutilized, or substandard buildings to multifamily housing.

. "Owner" means the property owner of record.

. "Permanent residential occupancy" means multiunit housing that provides either rental or owner occupancy on a nontransient basis. This includes owner-occupied or rental accommodation that is leased for a period of at least one month. This excludes hotels and motels that predominately offer rental accommodation on a daily or weekly basis.

. "Rehabilitation improvements" means modifications to existing structures, that are vacant for twelve months or longer, that are made to achieve a condition of substantial compliance with existing building codes or modification to existing occupied structures which increase the number of multifamily housing units.

. "Residential targeted area" means an area within an urban center or urban growth area that has been designated by the governing authority as a residential targeted area in accordance with this chapter. With respect to designations after July 1, 2007, "residential targeted area" may not include a campus facilities master plan.

. "Rural county" means a county with a population between fifty thousand and seventy-one thousand and bordering Puget Sound.

. "Substantial compliance" means compliance with local building or housing code requirements that are typically required for rehabilitation as opposed to new construction.

. "Urban center" means a compact identifiable district where urban residents may obtain a variety of products and services. An urban center must contain:

.. Several existing or previous, or both, business establishments that may include but are not limited to shops, offices, banks, restaurants, governmental agencies;

.. Adequate public facilities including streets, sidewalks, lighting, transit, domestic water, and sanitary sewer systems; and

.. A mixture of uses and activities that may include housing, recreation, and cultural activities in association with either commercial or office, or both, use.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1107.SL.pdf?cite=2017%20c%2052%20§%2016[2017 c 52 § 16]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6330-S2.SL.pdf?cite=2014%20c%2096%20§%203[2014 c 96 § 3]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6277-S.SL.pdf?cite=2012%20c%20194%20§%202[2012 c 194 § 2]; prior:  2007 c 430 § 3; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2164-S.SL.pdf?cite=2007%20c%20185%20§%201[2007 c 185 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2466-S.SL.pdf?cite=2002%20c%20146%20§%201[2002 c 146 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2505.SL.pdf?cite=2000%20c%20242%20§%201[2000 c 242 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6094.SL.pdf?cite=1997%20c%20429%20§%2040[1997 c 429 § 40]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5387-S2.SL.pdf?cite=1995%20c%20375%20§%203[1995 c 375 § 3]; ]

== 84.14.020 - Exemption—Duration—Valuation.
. [Empty]
.. The value of new housing construction, conversion, and rehabilitation improvements qualifying under this chapter is exempt from ad valorem property taxation, as follows:

... For properties for which applications for certificates of tax exemption eligibility are submitted under this chapter before July 22, 2007, the value is exempt for ten successive years beginning January 1 of the year immediately following the calendar year of issuance of the certificate; and

... For properties for which applications for certificates of tax exemption eligibility are submitted under this chapter on or after July 22, 2007, the value is exempt:

(A) For eight successive years beginning January 1st of the year immediately following the calendar year of issuance of the certificate; or

(B) For twelve successive years beginning January 1st of the year immediately following the calendar year of issuance of the certificate, if the property otherwise qualifies for the exemption under this chapter and meets the conditions in this subsection (1)(a)(ii)(B). For the property to qualify for the twelve-year exemption under this subsection, the applicant must commit to renting or selling at least twenty percent of the multifamily housing units as affordable housing units to low and moderate-income households, and the property must satisfy that commitment and any additional affordability and income eligibility conditions adopted by the local government under this chapter. In the case of projects intended exclusively for owner occupancy, the minimum requirement of this subsection (1)(a)(ii)(B) may be satisfied solely through housing affordable to moderate-income households.

.. The exemptions provided in (a)(i) and (ii) of this subsection do not include the value of land or nonhousing-related improvements not qualifying under this chapter.

.. For properties receiving an exemption as provided in (a)(ii)(B) of this subsection that are in compliance with existing contracts and where the certificate of tax exemption is set to expire after June 11, 2020, but before December 31, 2021, the exemption is extended until December 31, 2021, provided that the property must satisfy any eligibility criteria or limitations provided in this chapter as a condition to the existing exemption for a given property continue to be met. For all properties eligible to receive an extension pursuant to this subsection (1)(c), the city or county that issued the initial certificate of tax exemption, as required in RCW 84.14.090, must notify the county assessor and the applicant of the extension of the certificate of tax exemption.

. When a local government adopts guidelines pursuant to RCW 84.14.030(2) and includes conditions that must be satisfied with respect to individual dwelling units, rather than with respect to the multiple-unit housing as a whole or some minimum portion thereof, the exemption may, at the local government's discretion, be limited to the value of the qualifying improvements allocable to those dwelling units that meet the local guidelines.

. In the case of rehabilitation of existing buildings, the exemption does not include the value of improvements constructed prior to the submission of the application required under this chapter. The incentive provided by this chapter is in addition to any other incentives, tax credits, grants, or other incentives provided by law.

. This chapter does not apply to increases in assessed valuation made by the assessor on nonqualifying portions of building and value of land nor to increases made by lawful order of a county board of equalization, the department of revenue, or a county, to a class of property throughout the county or specific area of the county to achieve the uniformity of assessment or appraisal required by law.

. At the conclusion of the exemption period, the new or rehabilitated housing cost shall be considered as new construction for the purposes of chapter 84.55 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2950-S.SL.pdf?cite=2020%20c%20237%20§%202[2020 c 237 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1910-S2.SL.pdf?cite=2007%20c%20430%20§%204[2007 c 430 § 4]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2466-S.SL.pdf?cite=2002%20c%20146%20§%202[2002 c 146 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5746-S.SL.pdf?cite=1999%20c%20132%20§%201[1999 c 132 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5387-S2.SL.pdf?cite=1995%20c%20375%20§%205[1995 c 375 § 5]; ]

== 84.14.030 - Application—Requirements.
An owner of property making application under this chapter must meet the following requirements:

. The new or rehabilitated multiple-unit housing must be located in a residential targeted area as designated by the city or county;

. The multiple-unit housing must meet guidelines as adopted by the governing authority that may include height, density, public benefit features, number and size of proposed development, parking, income limits for occupancy, limits on rents or sale prices, and other adopted requirements indicated necessary by the city or county. The required amenities should be relative to the size of the project and tax benefit to be obtained;

. The new, converted, or rehabilitated multiple-unit housing must provide for a minimum of fifty percent of the space for permanent residential occupancy. In the case of existing occupied multifamily development, the multifamily housing must also provide for a minimum of four additional multifamily units. Existing multifamily vacant housing that has been vacant for twelve months or more does not have to provide additional multifamily units;

. New construction multifamily housing and rehabilitation improvements must be completed within three years from the date of approval of the application;

. Property proposed to be rehabilitated must fail to comply with one or more standards of the applicable state or local building or housing codes on or after July 23, 1995. If the property proposed to be rehabilitated is not vacant, an applicant must provide each existing tenant housing of comparable size, quality, and price and a reasonable opportunity to relocate; and

. The applicant must enter into a contract with the city or county approved by the governing authority, or an administrative official or commission authorized by the governing authority, under which the applicant has agreed to the implementation of the development on terms and conditions satisfactory to the governing authority.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6277-S.SL.pdf?cite=2012%20c%20194%20§%203[2012 c 194 § 3]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1910-S2.SL.pdf?cite=2007%20c%20430%20§%205[2007 c 430 § 5]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5713.SL.pdf?cite=2005%20c%2080%20§%201[2005 c 80 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6094.SL.pdf?cite=1997%20c%20429%20§%2042[1997 c 429 § 42]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5387-S2.SL.pdf?cite=1995%20c%20375%20§%206[1995 c 375 § 6]; ]

== 84.14.040 - Designation of residential targeted area—Criteria—Local designation—Hearing—Standards, guidelines.
. The following criteria must be met before an area may be designated as a residential targeted area:

.. The area must be within an urban center, as determined by the governing authority;

.. The area must lack, as determined by the governing authority, sufficient available, desirable, and convenient residential housing, including affordable housing, to meet the needs of the public who would be likely to live in the urban center, if the affordable, desirable, attractive, and livable places to live were available;

.. The providing of additional housing opportunity, including affordable housing, in the area, as determined by the governing authority, will assist in achieving one or more of the stated purposes of this chapter; and

.. If the residential targeted area is designated by a county, the area must be located in an unincorporated area of the county that is within an urban growth area under RCW 36.70A.110 and the area must be: (i) In a rural county, served by a sewer system and designated by a county prior to January 1, 2013; or (ii) in a county that includes a campus of an institution of higher education, as defined in RCW 28B.92.030, where at least one thousand two hundred students live on campus during the academic year.

. For the purpose of designating a residential targeted area or areas, the governing authority may adopt a resolution of intention to so designate an area as generally described in the resolution. The resolution must state the time and place of a hearing to be held by the governing authority to consider the designation of the area and may include such other information pertaining to the designation of the area as the governing authority determines to be appropriate to apprise the public of the action intended.

. The governing authority must give notice of a hearing held under this chapter by publication of the notice once each week for two consecutive weeks, not less than seven days, nor more than thirty days before the date of the hearing in a paper having a general circulation in the city or county where the proposed residential targeted area is located. The notice must state the time, date, place, and purpose of the hearing and generally identify the area proposed to be designated as a residential targeted area.

. Following the hearing, or a continuance of the hearing, the governing authority may designate all or a portion of the area described in the resolution of intent as a residential targeted area if it finds, in its sole discretion, that the criteria in subsections (1) through (3) of this section have been met.

. After designation of a residential targeted area, the governing authority must adopt and implement standards and guidelines to be utilized in considering applications and making the determinations required under RCW 84.14.060. The standards and guidelines must establish basic requirements for both new construction and rehabilitation, which must include:

.. Application process and procedures;

.. Requirements that address demolition of existing structures and site utilization; and

.. Building requirements that may include elements addressing parking, height, density, environmental impact, and compatibility with the existing surrounding property and such other amenities as will attract and keep permanent residents and that will properly enhance the livability of the residential targeted area in which they are to be located.

. The governing authority may adopt and implement, either as conditions to eight-year exemptions or as conditions to an extended exemption period under RCW 84.14.020(1)(a)(ii)(B), or both, more stringent income eligibility, rent, or sale price limits, including limits that apply to a higher percentage of units, than the minimum conditions for an extended exemption period under RCW 84.14.020(1)(a)(ii)(B). For any multiunit housing located in an unincorporated area of a county, a property owner seeking tax incentives under this chapter must commit to renting or selling at least twenty percent of the multifamily housing units as affordable housing units to low and moderate-income households. In the case of multiunit housing intended exclusively for owner occupancy, the minimum requirement of this subsection (6) may be satisfied solely through housing affordable to moderate-income households.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6330-S2.SL.pdf?cite=2014%20c%2096%20§%204[2014 c 96 § 4]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6277-S.SL.pdf?cite=2012%20c%20194%20§%204[2012 c 194 § 4]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1910-S2.SL.pdf?cite=2007%20c%20430%20§%206[2007 c 430 § 6]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5387-S2.SL.pdf?cite=1995%20c%20375%20§%207[1995 c 375 § 7]; ]

== 84.14.050 - Application—Procedures.
An owner of property seeking tax incentives under this chapter must complete the following procedures:

. In the case of rehabilitation or where demolition or new construction is required, the owner must secure from the governing authority or duly authorized representative, before commencement of rehabilitation improvements or new construction, verification of property noncompliance with applicable building and housing codes;

. In the case of new and rehabilitated multifamily housing, the owner must apply to the city or county on forms adopted by the governing authority. The application must contain the following:

.. Information setting forth the grounds supporting the requested exemption including information indicated on the application form or in the guidelines;

.. A description of the project and site plan, including the floor plan of units and other information requested;

.. A statement that the applicant is aware of the potential tax liability involved when the property ceases to be eligible for the incentive provided under this chapter;

. The applicant must verify the application by oath or affirmation; and

. The application must be accompanied by the application fee, if any, required under RCW 84.14.080. The governing authority may permit the applicant to revise an application before final action by the governing authority.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6277-S.SL.pdf?cite=2012%20c%20194%20§%205[2012 c 194 § 5]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1910-S2.SL.pdf?cite=2007%20c%20430%20§%207[2007 c 430 § 7]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5746-S.SL.pdf?cite=1999%20c%20132%20§%202[1999 c 132 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6094.SL.pdf?cite=1997%20c%20429%20§%2043[1997 c 429 § 43]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5387-S2.SL.pdf?cite=1995%20c%20375%20§%208[1995 c 375 § 8]; ]

== 84.14.060 - Approval—Required findings.
. The duly authorized administrative official or committee of the city or county may approve the application if it finds that:

.. A minimum of four new units are being constructed or in the case of occupied rehabilitation or conversion a minimum of four additional multifamily units are being developed;

.. If applicable, the proposed multiunit housing project meets the affordable housing requirements as described in RCW 84.14.020;

.. The proposed project is or will be, at the time of completion, in conformance with all local plans and regulations that apply at the time the application is approved;

.. The owner has complied with all standards and guidelines adopted by the city or county under this chapter; and

.. The site is located in a residential targeted area of an urban center or urban growth area that has been designated by the governing authority in accordance with procedures and guidelines indicated in RCW 84.14.040.

. An application may not be approved after July 1, 2007, if any part of the proposed project site is within a campus facilities master plan, except as provided in RCW 84.14.040(1)(d).

. An application may not be approved for a residential targeted area in a rural county on or after January 1, 2020.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6330-S2.SL.pdf?cite=2014%20c%2096%20§%205[2014 c 96 § 5]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6277-S.SL.pdf?cite=2012%20c%20194%20§%206[2012 c 194 § 6]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1910-S2.SL.pdf?cite=2007%20c%20430%20§%208[2007 c 430 § 8]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2164-S.SL.pdf?cite=2007%20c%20185%20§%202[2007 c 185 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5387-S2.SL.pdf?cite=1995%20c%20375%20§%209[1995 c 375 § 9]; ]

== 84.14.070 - Processing—Approval—Denial—Appeal.
. The governing authority or an administrative official or commission authorized by the governing authority must approve or deny an application filed under this chapter within ninety days after receipt of the application.

. If the application is approved, the city or county must issue the owner of the property a conditional certificate of acceptance of tax exemption. The certificate must contain a statement by a duly authorized administrative official of the governing authority that the property has complied with the required findings indicated in RCW 84.14.060.

. If the application is denied by the authorized administrative official or commission authorized by the governing authority, the deciding administrative official or commission must state in writing the reasons for denial and send the notice to the applicant at the applicant's last known address within ten days of the denial.

. Upon denial by a duly authorized administrative official or commission, an applicant may appeal the denial to the governing authority within thirty days after receipt of the denial. The appeal before the governing authority must be based upon the record made before the administrative official with the burden of proof on the applicant to show that there was no substantial evidence to support the administrative official's decision. The decision of the governing body in denying or approving the application is final.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6277-S.SL.pdf?cite=2012%20c%20194%20§%207[2012 c 194 § 7]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5387-S2.SL.pdf?cite=1995%20c%20375%20§%2010[1995 c 375 § 10]; ]

== 84.14.080 - Fees.
The governing authority may establish an application fee. This fee may not exceed an amount determined to be required to cover the cost to be incurred by the governing authority and the assessor in administering this chapter. The application fee must be paid at the time the application for limited exemption is filed. If the application is approved, the governing authority shall pay the application fee to the county assessor for deposit in the county current expense fund, after first deducting that portion of the fee attributable to its own administrative costs in processing the application. If the application is denied, the governing authority may retain that portion of the application fee attributable to its own administrative costs and refund the balance to the applicant.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5387-S2.SL.pdf?cite=1995%20c%20375%20§%2011[1995 c 375 § 11]; ]

== 84.14.090 - Filing requirements for owner upon completion—Determination by city or county—Notice of intention by city or county not to file—Extension of deadline—Appeal.
. Upon completion of rehabilitation or new construction for which an application for a limited tax exemption under this chapter has been approved and after issuance of the certificate of occupancy, the owner must file with the city or county the following:

.. A statement of the amount of rehabilitation or construction expenditures made with respect to each housing unit and the composite expenditures made in the rehabilitation or construction of the entire property;

.. A description of the work that has been completed and a statement that the rehabilitation improvements or new construction on the owner's property qualify the property for limited exemption under this chapter;

.. If applicable, a statement that the project meets the affordable housing requirements as described in RCW 84.14.020; and

.. A statement that the work has been completed within three years of the issuance of the conditional certificate of tax exemption.

. Within thirty days after receipt of the statements required under subsection (1) of this section, the authorized representative of the city or county must determine whether the work completed, and the affordability of the units, is consistent with the application and the contract approved by the city or county and is qualified for a limited tax exemption under this chapter. The city or county must also determine which specific improvements completed meet the requirements and required findings.

. If the rehabilitation, conversion, or construction is completed within three years of the date the application for a limited tax exemption is filed under this chapter, or within an authorized extension of this time limit, and the authorized representative of the city or county determines that improvements were constructed consistent with the application and other applicable requirements, including if applicable, affordable housing requirements, and the owner's property is qualified for a limited tax exemption under this chapter, the city or county must file the certificate of tax exemption with the county assessor within ten days of the expiration of the thirty-day period provided under subsection (2) of this section.

. The authorized representative of the city or county must notify the applicant that a certificate of tax exemption is not going to be filed if the authorized representative determines that:

.. The rehabilitation or new construction was not completed within three years of the application date, or within any authorized extension of the time limit;

.. The improvements were not constructed consistent with the application or other applicable requirements;

.. If applicable, the affordable housing requirements as described in RCW 84.14.020 were not met; or

.. The owner's property is otherwise not qualified for limited exemption under this chapter.

. If the authorized representative of the city or county finds that construction or rehabilitation of multiple-unit housing was not completed within the required time period due to circumstances beyond the control of the owner and that the owner has been acting and could reasonably be expected to act in good faith and with due diligence, the governing authority or the city or county official authorized by the governing authority may extend the deadline for completion of construction or rehabilitation for a period not to exceed twenty-four consecutive months.

. The governing authority may provide by ordinance for an appeal of a decision by the deciding officer or authority that an owner is not entitled to a certificate of tax exemption to the governing authority, a hearing examiner, or other city or county officer authorized by the governing authority to hear the appeal in accordance with such reasonable procedures and time periods as provided by ordinance of the governing authority. The owner may appeal a decision by the deciding officer or authority that is not subject to local appeal or a decision by the local appeal authority that the owner is not entitled to a certificate of tax exemption in superior court under RCW 34.05.510 through 34.05.598, if the appeal is filed within thirty days of notification by the city or county to the owner of the decision being challenged.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6277-S.SL.pdf?cite=2012%20c%20194%20§%208[2012 c 194 § 8]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1910-S2.SL.pdf?cite=2007%20c%20430%20§%209[2007 c 430 § 9]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5387-S2.SL.pdf?cite=1995%20c%20375%20§%2012[1995 c 375 § 12]; ]

== 84.14.100 - Report—Filing.
. Thirty days after the anniversary of the date of the certificate of tax exemption and each year for the tax exemption period, the owner of the rehabilitated or newly constructed property must file with a designated authorized representative of the city or county an annual report indicating the following:

.. A statement of occupancy and vacancy of the rehabilitated or newly constructed property during the twelve months ending with the anniversary date;

.. A certification by the owner that the property has not changed use and, if applicable, that the property has been in compliance with the affordable housing requirements as described in RCW 84.14.020 since the date of the certificate approved by the city or county;

.. A description of changes or improvements constructed after issuance of the certificate of tax exemption; and

.. Any additional information requested by the city or county in regards to the units receiving a tax exemption.

. All cities or counties, which issue certificates of tax exemption for multiunit housing that conform to the requirements of this chapter, must report annually by December 31st of each year, beginning in 2007, to the department of commerce. The report must include the following information:

.. The number of tax exemption certificates granted;

.. The total number and type of units produced or to be produced;

.. The number and type of units produced or to be produced meeting affordable housing requirements;

.. The actual development cost of each unit produced;

.. The total monthly rent or total sale amount of each unit produced;

.. The income of each renter household at the time of initial occupancy and the income of each initial purchaser of owner-occupied units at the time of purchase for each of the units receiving a tax exemption and a summary of these figures for the city or county; and

.. The value of the tax exemption for each project receiving a tax exemption and the total value of tax exemptions granted.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6277-S.SL.pdf?cite=2012%20c%20194%20§%209[2012 c 194 § 9]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1910-S2.SL.pdf?cite=2007%20c%20430%20§%2010[2007 c 430 § 10]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5387-S2.SL.pdf?cite=1995%20c%20375%20§%2013[1995 c 375 § 13]; ]

== 84.14.110 - Cancellation of exemption—Notice by owner of change in use—Additional tax—Penalty—Interest—Lien—Notice of cancellation—Appeal—Correction of tax rolls.
. If improvements have been exempted under this chapter, the improvements continue to be exempted for the applicable period under RCW 84.14.020, so long as they are not converted to another use and continue to satisfy all applicable conditions. If the owner intends to convert the multifamily development to another use, or if applicable, if the owner intends to discontinue compliance with the affordable housing requirements as described in RCW 84.14.020 or any other condition to exemption, the owner must notify the assessor within sixty days of the change in use or intended discontinuance. If, after a certificate of tax exemption has been filed with the county assessor, the authorized representative of the governing authority discovers that a portion of the property is changed or will be changed to a use that is other than residential or that housing or amenities no longer meet the requirements, including, if applicable, affordable housing requirements, as previously approved or agreed upon by contract between the city or county and the owner and that the multifamily housing, or a portion of the housing, no longer qualifies for the exemption, the tax exemption must be canceled and the following must occur:

.. Additional real property tax must be imposed upon the value of the nonqualifying improvements in the amount that would normally be imposed, plus a penalty must be imposed amounting to twenty percent. This additional tax is calculated based upon the difference between the property tax paid and the property tax that would have been paid if it had included the value of the nonqualifying improvements dated back to the date that the improvements were converted to a nonmultifamily use;

.. The tax must include interest upon the amounts of the additional tax at the same statutory rate charged on delinquent property taxes from the dates on which the additional tax could have been paid without penalty if the improvements had been assessed at a value without regard to this chapter; and

.. The additional tax owed together with interest and penalty must become a lien on the land and attach at the time the property or portion of the property is removed from multifamily use or the amenities no longer meet applicable requirements, and has priority to and must be fully paid and satisfied before a recognizance, mortgage, judgment, debt, obligation, or responsibility to or with which the land may become charged or liable. The lien may be foreclosed upon expiration of the same period after delinquency and in the same manner provided by law for foreclosure of liens for delinquent real property taxes. An additional tax unpaid on its due date is delinquent. From the date of delinquency until paid, interest must be charged at the same rate applied by law to delinquent ad valorem property taxes.

. Upon a determination that a tax exemption is to be canceled for a reason stated in this section, the governing authority or authorized representative must notify the record owner of the property as shown by the tax rolls by mail, return receipt requested, of the determination to cancel the exemption. The owner may appeal the determination to the governing authority or authorized representative, within thirty days by filing a notice of appeal with the clerk of the governing authority, which notice must specify the factual and legal basis on which the determination of cancellation is alleged to be erroneous. The governing authority or a hearing examiner or other official authorized by the governing authority may hear the appeal. At the hearing, all affected parties may be heard and all competent evidence received. After the hearing, the deciding body or officer must either affirm, modify, or repeal the decision of cancellation of exemption based on the evidence received. An aggrieved party may appeal the decision of the deciding body or officer to the superior court under RCW 34.05.510 through 34.05.598.

. Upon determination by the governing authority or authorized representative to terminate an exemption, the county officials having possession of the assessment and tax rolls must correct the rolls in the manner provided for omitted property under RCW 84.40.080. The county assessor must make such a valuation of the property and improvements as is necessary to permit the correction of the rolls. The value of the new housing construction, conversion, and rehabilitation improvements added to the rolls is considered as new construction for the purposes of chapter 84.55 RCW. The owner may appeal the valuation to the county board of equalization under chapter 84.48 RCW and according to the provisions of RCW 84.40.038. If there has been a failure to comply with this chapter, the property must be listed as an omitted assessment for assessment years beginning January 1 of the calendar year in which the noncompliance first occurred, but the listing as an omitted assessment may not be for a period more than three calendar years preceding the year in which the failure to comply was discovered.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6277-S.SL.pdf?cite=2012%20c%20194%20§%2010[2012 c 194 § 10]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1910-S2.SL.pdf?cite=2007%20c%20430%20§%2011[2007 c 430 § 11]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2466-S.SL.pdf?cite=2002%20c%20146%20§%203[2002 c 146 § 3]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1202-S.SL.pdf?cite=2001%20c%20185%20§%201[2001 c 185 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5387-S2.SL.pdf?cite=1995%20c%20375%20§%2014[1995 c 375 § 14]; ]

