= 84.25 - Targeted urban areas—Exemption.
:toc:

== 84.25.010 - Findings.
The legislature finds that:

. Many cities have planned under the growth management act, chapter 36.70A RCW, and designated and zoned lands for industrial and manufacturing use;

. The industrial and manufacturing industries provide family living wage jobs;

. In the current economic climate the creation of additional family living wage jobs is essential;

. It is critical that Washington state promote its continued strength in the fields of aerospace, technology, biomedical, and other industries that will provide family-wage job growth; and

. Planning for industrial and manufacturing use is inadequate to attract new industry and manufacturing and an incentive should be created to stimulate the development of new industrial and manufacturing uses in the existing inventory of lands zoned for industrial and manufacturing use in targeted urban areas through a tax incentive as provided by this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5761.SL.pdf?cite=2015%201st%20sp.s.%20c%209%20§%201[2015 1st sp.s. c 9 § 1]; ]

== 84.25.020 - Purpose.
It is the purpose of this chapter to encourage new manufacturing and industrial uses on undeveloped or underutilized lands zoned for industrial and manufacturing uses in targeted urban areas, thereby increasing employment opportunities for family living wage jobs. Cities that plan under the growth management act meeting the criteria of this chapter where the governing authority of the affected city has found there is insufficient family living wage jobs for its wage earning population may designate a portion of the city's industrial and manufacturing zoned and undeveloped land to receive an ad valorem tax exemption for the value of new construction of industrial/manufacturing facilities within the designated area.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5761.SL.pdf?cite=2015%201st%20sp.s.%20c%209%20§%202[2015 1st sp.s. c 9 § 2]; ]

== 84.25.030 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "City" means any city that: (a) Has a population of at least eighteen thousand; and (b) is north or east of the largest city in the county in which the city is located and such county has a population of at least seven hundred thousand, but less than eight hundred thousand.

. "Family living wage job" means a job with a wage that is sufficient for raising a family. A family living wage job must have an average wage of eighteen dollars an hour or more, working two thousand eighty hours per year on the subject site, as adjusted annually for inflation by the consumer price index. The family living wage may be increased by the local authority based on regional factors and wage conditions.

. "Governing authority" means the local legislative authority of a city having jurisdiction over the property for which an exemption may be applied for under this chapter.

. "Growth management act" means chapter 36.70A RCW.

. "Industrial/manufacturing facilities" means building improvements that are ten thousand square feet or larger, representing a minimum improvement valuation of eight hundred thousand dollars for uses categorized as "division D: manufacturing" by the United States department of labor in the occupation safety and health administration's standard industrial classification manual.

. "Lands zoned for industrial and manufacturing uses" means lands in a city zoned as of December 31, 2014, for an industrial or manufacturing use consistent with the city's comprehensive plan where the lands are designated for industry.

. "Owner" means the property owner of record.

. "Targeted area" means an area of undeveloped lands zoned for industrial and manufacturing uses in the city that is located within or contiguous to an innovation partnership zone, foreign trade zone, or EB-5 regional center, and designated for possible exemption under the provisions of this chapter.

. "Undeveloped or underutilized" means that there are no existing building improvements on the property or portions of the property targeted for new or expanded industrial or manufacturing uses.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5761.SL.pdf?cite=2015%201st%20sp.s.%20c%209%20§%203[2015 1st sp.s. c 9 § 3]; ]

== 84.25.040 - Exemption—New construction of industrial/manufacturing facilities.
. [Empty]
.. The value of new construction of industrial/manufacturing facilities qualifying under this chapter is exempt from property taxation under this title, as provided in this section. The value of new construction of industrial/manufacturing facilities is exempt from taxation for properties for which an application for a certificate of tax exemption is submitted under this chapter before December 31, 2022. The value is exempt under this section for ten successive years beginning January 1st of the year immediately following the calendar year of issuance of the certificate.

.. The exemption provided in this section does not include the value of land or nonindustrial/manufacturing-related improvements not qualifying under this chapter.

. The exemption provided in this section is in addition to any other exemptions, deferrals, credits, grants, or other tax incentives provided by law.

. This chapter does not apply to state levies or increases in assessed valuation made by the assessor on nonqualifying portions of buildings and value of land nor to increases made by lawful order of a county board of equalization, the department of revenue, or a county, to a class of property throughout the county or specific area of the county to achieve the uniformity of assessment or appraisal required by law.

. This exemption does not apply to any county property taxes unless the governing body of the county adopts a resolution and notifies the governing authority of its intent to allow the property to be exempted from county property taxes.

. At the conclusion of the exemption period, the new industrial/manufacturing facilities cost must be considered as new construction for the purposes of chapter 84.55 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5761.SL.pdf?cite=2015%201st%20sp.s.%20c%209%20§%204[2015 1st sp.s. c 9 § 4]; ]

== 84.25.050 - Application requirements for property owner.
An owner of property making application under this chapter must meet the following requirements:

. The new construction of industrial/manufacturing facilities must be located on land zoned for industrial and manufacturing uses, undeveloped or underutilized, and as provided in RCW 84.25.060, designated by the city as a targeted area;

. The new construction of industrial/manufacturing facilities must meet all construction and development regulations of the city;

. The new construction of industrial/manufacturing facilities must be completed within three years from the date of approval of the application; and

. The applicant must enter into a contract with the city approved by the governing authority, or an administrative official or commission authorized by the governing authority, under which the applicant has agreed to the implementation of the development on terms and conditions satisfactory to the governing authority.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5761.SL.pdf?cite=2015%201st%20sp.s.%20c%209%20§%205[2015 1st sp.s. c 9 § 5]; ]

== 84.25.060 - Targeted area designation requirements.
. The following criteria must be met before an area may be designated as a targeted area:

.. The area must be lands zoned for industrial and manufacturing uses; and

.. The city must have determined that the targeting of the area, as evaluated by the governing authority, will assist in the new construction of industrial/manufacturing facilities that will provide employment for family living wage jobs.

. For the purpose of designating a targeted area, the governing authority may adopt a resolution of intention to so designate an area as generally described in the resolution. The resolution must state the time and place of a hearing to be held by the governing authority to consider the designation of the area and may include such other information pertaining to the designation of the area as the governing authority determines to be appropriate to apprise the public of the action intended.

. The governing authority must give notice of a hearing held under this chapter by publication of the notice once each week for two consecutive weeks, not less than seven days, nor more than thirty days before the date of the hearing in a paper having a general circulation in the city where the proposed targeted area is located. The notice must state the time, date, place, and purpose of the hearing and generally identify the area proposed to be designated as a targeted area.

. Following the hearing or a continuance of the hearing, and subject to the limit on targeted areas, the governing authority may designate all or a portion of the area described in the resolution of intent as a targeted area if it finds, in its sole discretion, that the criteria in subsection (1) of this section have been met.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5761.SL.pdf?cite=2015%201st%20sp.s.%20c%209%20§%206[2015 1st sp.s. c 9 § 6]; ]

== 84.25.070 - Exemption application procedures.
An owner of property seeking an exemption under this chapter must complete the following procedures:

. The owner must apply to the city on forms adopted by the governing authority. The application must contain the following:

.. Information setting forth the grounds supporting the requested exemption including information indicated on the application form or in the guidelines;

.. A description of the project and site plan, and other information requested;

.. A statement of the expected number of new family living wage jobs to be created;

.. A statement that the applicant is aware of the potential tax liability involved when the property ceases to be eligible for the incentive provided under this chapter; and

.. A statement that the applicant would not have built in this location but for the availability of the tax exemption under this chapter;

. The applicant must verify the application by oath or affirmation; and

. The application must be accompanied by the application fee, if any, required under this chapter. The governing authority may permit the applicant to revise an application before final action by the governing authority.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5761.SL.pdf?cite=2015%201st%20sp.s.%20c%209%20§%207[2015 1st sp.s. c 9 § 7]; ]

== 84.25.080 - Application approval—City review requirements.
The duly authorized administrative official or committee of the city may approve the application if it finds that:

. A minimum of twenty-five new family living wage jobs will be created on the subject site as a result of new construction of manufacturing/industrial [industrial/manufacturing] facilities within one year of building occupancy;

. The proposed project is, or will be, at the time of completion, in conformance with all local plans and regulations that apply at the time the application is approved; and

. The criteria of this chapter have been satisfied.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5761.SL.pdf?cite=2015%201st%20sp.s.%20c%209%20§%208[2015 1st sp.s. c 9 § 8]; ]

== 84.25.090 - Application—City approval or denial—Appeals.
. The city governing authority or its authorized representative must approve or deny an application filed under this chapter within ninety days after receipt of the application.

. If the application is approved, the city must issue the owner of the property a conditional certificate of acceptance of tax exemption. The certificate must contain a statement by a duly authorized administrative official of the governing authority that the property has complied with the required criteria of this chapter.

. If the application is denied by the city, the city must state in writing the reasons for denial and send the notice to the applicant at the applicant's last known address within ten days of the denial.

. Upon denial by the city, an applicant may appeal the denial to the city's governing authority within thirty days after receipt of the denial. The appeal before the city's governing authority must be based upon the record made before the city with the burden of proof on the applicant to show that there was no substantial evidence to support the city's decision. The decision of the city in denying or approving the application is final.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5761.SL.pdf?cite=2015%201st%20sp.s.%20c%209%20§%209[2015 1st sp.s. c 9 § 9]; ]

== 84.25.100 - Application fee.
The governing authority may establish an application fee. This fee may not exceed an amount determined to be required to cover the cost to be incurred by the governing authority and the assessor in administering this chapter. The application fee must be paid at the time the application for limited exemption is filed. If the application is approved, the governing authority of the city must pay the application fee to the county assessor for deposit in the county current expense fund, after first deducting that portion of the fee attributable to its own administrative costs in processing the application. If the application is denied, the city's governing authority may retain that portion of the application fee attributable to its own administrative costs and refund the balance to the applicant.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5761.SL.pdf?cite=2015%201st%20sp.s.%20c%209%20§%2010[2015 1st sp.s. c 9 § 10]; ]

== 84.25.110 - Certificate of tax exemption—Requirements.
. Upon completion of the new construction of a manufacturing/industrial [industrial/manufacturing] facility for which an application for an exemption under this chapter has been approved and issued a certificate of occupancy, the owner must file with the city the following:

.. A description of the work that has been completed and a statement that the new construction on the owner's property qualify the property for a partial exemption under this chapter;

.. A statement of the new family living wage jobs to be offered as a result of the new construction of manufacturing/industrial [industrial/manufacturing] facilities; and

.. A statement that the work has been completed within three years of the issuance of the conditional certificate of tax exemption.

. Within thirty days after receipt of the statements required under subsection (1) of this section, the city must determine whether the work completed and the jobs to be offered are consistent with the application and the contract approved by the city and whether the application is qualified for a tax exemption under this chapter.

. If the criteria of this chapter have been satisfied and the owner's property is qualified for a tax exemption under this chapter, the city must file the certificate of tax exemption with the county assessor within ten days of the expiration of the thirty-day period provided under subsection (2) of this section.

. The city must notify the applicant that a certificate of tax exemption is denied if the city determines that:

.. The work was not completed within three years of the application date;

.. The work was not constructed consistent with the application or other applicable requirements;

.. The jobs to be offered are not consistent with the application and criteria of this chapter; or

.. The owner's property is otherwise not qualified for an exemption under this chapter.

. If the city finds that the work was not completed within the required time period due to circumstances beyond the control of the owner and that the owner has been acting and could reasonably be expected to act in good faith and with due diligence, the governing authority or the city official authorized by the governing authority may extend the deadline for completion of the work for a period not to exceed twenty-four consecutive months.

. The city's governing authority may enact an ordinance to provide a process for an owner to appeal a decision by the city that the owner is not entitled to a certificate of tax exemption to the city. The owner may appeal a decision by the city to deny a certificate of tax exemption in superior court under RCW 34.05.510 through 34.05.598, if the appeal is filed within thirty days of notification by the city to the owner of the exemption denial.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5761.SL.pdf?cite=2015%201st%20sp.s.%20c%209%20§%2011[2015 1st sp.s. c 9 § 11]; ]

== 84.25.120 - Annual report.
. Thirty days after the anniversary of the date of the certificate of tax exemption and each year for the tax exemption period, the owner of the new industrial/manufacturing facilities must file with a designated authorized representative of the city an annual report indicating the following:

.. A statement of the family living wage jobs at the facility as of the anniversary date;

.. A certification by the owner that the property has not changed use;

.. A description of changes or improvements constructed after issuance of the certificate of tax exemption; and

.. Any additional information requested by the city.

. A city that issues a certificate of tax exemption under this chapter must report annually by December 31st of each year, beginning in 2013, to the department of commerce. The report must include the following information:

.. The number of tax exemption certificates granted;

.. The total number and type of new manufacturing/industrial [industrial/manufacturing] facilities constructed;

.. The number of family living wage jobs resulting from the new manufacturing/industrial [industrial/manufacturing] facilities; and

.. The value of the tax exemption for each project receiving a tax exemption and the total value of tax exemptions granted.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5761.SL.pdf?cite=2015%201st%20sp.s.%20c%209%20§%2012[2015 1st sp.s. c 9 § 12]; ]

== 84.25.130 - Improvements.
. If the value of improvements have been exempted under this chapter, the improvements continue to be exempted for the applicable period under this chapter so long as they are not converted to another use and continue to satisfy all applicable conditions including, but not limited to, zoning, land use, building, and family-wage job creation.

. If an owner voluntarily opts to discontinue compliance with the requirements of this chapter, the owner must notify the assessor within sixty days of the change in use or intended discontinuance.

. If, after a certificate of tax exemption has been filed with the county assessor, the city discovers that a portion of the property is changed or will be changed to disqualify the owner for exemption eligibility under this chapter, the tax exemption must be canceled and the following occurs:

.. Additional real property tax must be imposed on the value of the nonqualifying improvements in the amount that would be imposed if an exemption had not been available under this chapter, plus a penalty equal to twenty percent of the additional value. This additional tax is calculated based upon the difference between the property tax paid and the property tax that would have been paid if it had included the value of the nonqualifying improvements dated back to the date that the improvements were converted to a nonqualifying use;

.. The tax must include interest upon the amounts of the additional tax at the same statutory rate charged on delinquent property taxes from the dates on which the additional tax could have been paid without penalty if the improvements had been assessed at a value without regard to this chapter; and

.. The additional tax owed together with interest and penalty becomes a lien on the property and attaches at the time the property or portion of the property is removed from the qualifying use under this chapter or the amenities no longer meet the applicable requirements for exemption under this chapter. A lien under this section has priority to, and must be fully paid and satisfied before, a recognizance, mortgage, judgment, debt, obligation, or responsibility to or with which the property may become charged or liable. The lien may be foreclosed upon expiration of the same period after delinquency and in the same manner provided by law for foreclosure of liens for delinquent real property taxes. An additional tax unpaid on its due date is delinquent. From the date of delinquency until paid, interest must be charged at the same rate applied by law to delinquent property taxes.

. Upon a determination that a tax exemption is to be terminated for a reason stated in this section, the city's governing authority must notify the record owner of the property as shown by the tax rolls by mail, return receipt requested, of the determination to terminate the exemption. The owner may appeal the determination to the city, within thirty days by filing a notice of appeal with the city, which notice must specify the factual and legal basis on which the determination of termination is alleged to be erroneous. At an appeal hearing, all affected parties may be heard and all competent evidence received. After the hearing, the deciding body or officer must either affirm, modify, or repeal the decision of termination of exemption based on the evidence received. An aggrieved party may appeal the decision of the deciding body or officer to the superior court as provided in RCW 34.05.510 through 34.05.598.

. Upon determination by the city to terminate an exemption, the county officials having possession of the assessment and tax rolls must correct the rolls in the manner provided for omitted property under RCW 84.40.080. The county assessor must make such a valuation of the property and improvements as is necessary to permit the correction of the rolls. The value of the new industrial/manufacturing facilities added to the rolls is considered new construction for the purposes of chapter 84.40 RCW. The owner may appeal the valuation to the county board of equalization as provided in chapter 84.40 RCW. If there has been a failure to comply with this chapter, the property must be listed as an omitted assessment for assessment years beginning January 1st of the calendar year in which the noncompliance first occurred, but the listing as an omitted assessment may not be for a period more than three calendar years preceding the year in which the failure to comply was discovered.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5761.SL.pdf?cite=2015%201st%20sp.s.%20c%209%20§%2013[2015 1st sp.s. c 9 § 13]; ]

== 84.25.140 - Application—2015 1st sp.s. c 9.
This act applies to taxes levied for collection in 2016 and thereafter.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5761.SL.pdf?cite=2015%201st%20sp.s.%20c%209%20§%2014[2015 1st sp.s. c 9 § 14]; ]

