= 84.41 - Revaluation of property.
:toc:

== 84.41.010 - Declaration of policy.
Recent comprehensive studies by the legislative council have disclosed gross inequality and nonuniformity in valuation of real property for tax purposes throughout the state. Serious nonuniformity in valuations exists both between similar property within the various taxing districts and between general levels of valuation of the various counties. Such nonuniformity results in inequality in taxation contrary to standards of fairness and uniformity required and established by the Constitution and is of such flagrant and widespread occurrence as to constitute a grave emergency adversely affecting state and local government and the welfare of all the people.

Traditional public policy of the state has vested large measure of control in matters of property valuation in county government, and the state hereby declares its purpose to continue such policy. However, present statutes and practices thereunder have failed to achieve the measure of uniformity required by the Constitution; the resultant widespread inequality and nonuniformity in valuation of property can and should no longer be tolerated. It thus becomes necessary to require general revaluation of property throughout the state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c15.pdf?cite=1961%20c%2015%20§%2084.41.010[1961 c 15 § 84.41.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c251.pdf?cite=1955%20c%20251%20§%201[1955 c 251 § 1]; ]

== 84.41.020 - Scope of chapter.
This chapter does not, and is not intended to affect procedures whereby taxes are imposed either for local or state purposes. This chapter concerns solely the administrative procedures by which the true and fair value in money of property is determined. The process of valuation, which is distinct and separate from the process of levying and imposing a tax, does not result either in the imposition of a tax or the determination of the amount of a tax. This chapter is intended to, and applies only to procedures and methods whereby the value of property is ascertained.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c15.pdf?cite=1961%20c%2015%20§%2084.41.020[1961 c 15 § 84.41.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c251.pdf?cite=1955%20c%20251%20§%202[1955 c 251 § 2]; ]

== 84.41.030 - Revaluation program to be on continuous basis—Revaluation schedule—Effect of other proceedings on valuation.
. Each county assessor must maintain an active and systematic program of revaluation on a continuous basis. All taxable real property within a county must be revalued annually, and all taxable real property within a county must be physically inspected at least once every six years. Each county assessor may disregard any program of revaluation, if requested by a property owner, and change, as appropriate, the valuation of real property upon the receipt of a notice of decision received under RCW 36.70B.130 or chapter 35.22, 35.63, 35A.63, or 36.70 RCW pertaining to the value of the real property.

. The department will provide advisory appraisals of industrial properties valued at twenty-five million dollars or more in real and personal property value when requested by the county assessor.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5275-S.SL.pdf?cite=2015%20c%2086%20§%20102[2015 c 86 § 102]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5368-S.SL.pdf?cite=2009%20c%20308%20§%201[2009 c 308 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2567.SL.pdf?cite=1996%20c%20254%20§%207[1996 c 254 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982ex1c46.pdf?cite=1982%201st%20ex.s.%20c%2046%20§%201[1982 1st ex.s. c 46 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c288.pdf?cite=1971%20ex.s.%20c%20288%20§%206[1971 ex.s. c 288 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c15.pdf?cite=1961%20c%2015%20§%2084.41.030[1961 c 15 § 84.41.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c251.pdf?cite=1955%20c%20251%20§%203[1955 c 251 § 3]; ]

== 84.41.041 - Physical inspection and valuation of taxable property required—Adjustments during intervals based on statistical data.
. Each county assessor must cause taxable real property to be physically inspected and valued at least once every six years in accordance with RCW 84.41.030, and in accordance with a plan filed with and approved by the department of revenue. Such revaluation plan must provide that all taxable real property within a county must be revalued and these newly determined values placed on the assessment rolls each year. Property must be valued at one hundred percent of its true and fair value and assessed on the same basis, in accordance with RCW 84.40.030, unless specifically provided otherwise by law. During the intervals between each physical inspection of real property, the valuation of such property must be adjusted to its current true and fair value, such adjustments to be made once each year and to be based upon appropriate statistical data.

. The assessor may require property owners to submit pertinent data respecting taxable property in their control including data respecting any sale or purchase of said property within the past five years, the cost and characteristics of any improvement on the property and other facts necessary for appraisal of the property.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5358-S.SL.pdf?cite=2017%20c%20323%20§%20507[2017 c 323 § 507]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5275-S.SL.pdf?cite=2015%20c%2086%20§%20103[2015 c 86 § 103]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5368-S.SL.pdf?cite=2009%20c%20308%20§%202[2009 c 308 § 2]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1467-S.SL.pdf?cite=2001%20c%20187%20§%2021[2001 c 187 § 21]; 1997 c 3 § 108 (Referendum Bill No. 47, approved November 4, 1997); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c319.pdf?cite=1987%20c%20319%20§%204[1987 c 319 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982ex1c46.pdf?cite=1982%201st%20ex.s.%20c%2046%20§%202[1982 1st ex.s. c 46 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c214.pdf?cite=1979%20ex.s.%20c%20214%20§%209[1979 ex.s. c 214 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c131.pdf?cite=1974%20ex.s.%20c%20131%20§%202[1974 ex.s. c 131 § 2]; ]

== 84.41.050 - Budget, levy, to provide funds.
Each county assessor in budgets hereafter submitted, shall make adequate provision to effect countywide revaluations as herein directed. The several boards of county commissioners in passing upon budgets submitted by the several assessors, shall authorize and levy amounts which in the judgment of the board will suffice to carry out the directions of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c15.pdf?cite=1961%20c%2015%20§%2084.41.050[1961 c 15 § 84.41.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c251.pdf?cite=1955%20c%20251%20§%205[1955 c 251 § 5]; ]

== 84.41.060 - Assistance by department of revenue at request of assessor.
Any county assessor may request special assistance from the department of revenue in the valuation of property which either (1) requires specialized knowledge not otherwise available to the assessor's staff, or (2) because of an inadequate staff, cannot be completed by the assessor within the time required by this chapter. After consideration of such request the department of revenue shall advise the assessor that such request is either approved or rejected in whole or in part. Upon approval of such request, the department of revenue may assist the assessor in the valuation of such property in such manner as the department of revenue, in its discretion, considers proper and adequate.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c278.pdf?cite=1975%201st%20ex.s.%20c%20278%20§%20197[1975 1st ex.s. c 278 § 197]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c15.pdf?cite=1961%20c%2015%20§%2084.41.060[1961 c 15 § 84.41.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c251.pdf?cite=1955%20c%20251%20§%206[1955 c 251 § 6]; ]

== 84.41.070 - Finding of unsatisfactory progress—Notice—Duty of county legislative authority.
If the department of revenue finds upon its own investigation, or upon a showing by others, that the revaluation program for any county is not proceeding for any reason as herein directed, the department of revenue shall advise both the county legislative authority and the county assessor of such finding. Within thirty days after receiving such advice, the county legislative authority, at regular or special session, either (1) shall authorize such expenditures as will enable the assessor to complete the revaluation program as herein directed, or (2) shall direct the assessor to request special assistance from the department of revenue for aid in effectuating the county's revaluation program.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5372-S2.SL.pdf?cite=1994%20c%20301%20§%2040[1994 c 301 § 40]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c278.pdf?cite=1975%201st%20ex.s.%20c%20278%20§%20198[1975 1st ex.s. c 278 § 198]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c15.pdf?cite=1961%20c%2015%20§%2084.41.070[1961 c 15 § 84.41.070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c251.pdf?cite=1955%20c%20251%20§%207[1955 c 251 § 7]; ]

== 84.41.080 - Contracts for special assistance.
Upon receiving a request from the county assessor, either upon his or her initiation or at the direction of the board of county commissioners, for special assistance in the county's revaluation program, the department of revenue may, before undertaking to render such special assistance, negotiate a contract with the board of county commissioners of the county concerned. Such contracts as are negotiated shall provide that the county will reimburse the state for fifty percent of the costs of such special assistance within three years of the date of expenditure of such costs. All such reimbursements shall be paid to the department of revenue for deposit to the state general fund. The department of revenue shall keep complete records of such contracts, including costs incurred, payments received, and services performed thereunder.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20365[2013 c 23 § 365]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c278.pdf?cite=1975%201st%20ex.s.%20c%20278%20§%20199[1975 1st ex.s. c 278 § 199]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c15.pdf?cite=1961%20c%2015%20§%2084.41.080[1961 c 15 § 84.41.080]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c251.pdf?cite=1955%20c%20251%20§%208[1955 c 251 § 8]; ]

== 84.41.090 - Department to establish statistical methods—Publication of rules, regulations, and guides—Compliance required.
The department of revenue shall by rule establish appropriate statistical methods for use by assessors in adjusting the valuation of property between physical inspections. The department of revenue shall make and publish such additional rules, regulations and guides which it determines are needed to supplement materials presently published by the department of revenue for the general guidance and assistance of county assessors. Each assessor is hereby directed and required to value property in accordance with the standards established by RCW 84.40.030 and in accordance with the applicable rules, regulations and valuation manuals published by the department of revenue.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982ex1c46.pdf?cite=1982%201st%20ex.s.%20c%2046%20§%203[1982 1st ex.s. c 46 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c278.pdf?cite=1975%201st%20ex.s.%20c%20278%20§%20200[1975 1st ex.s. c 278 § 200]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c15.pdf?cite=1961%20c%2015%20§%2084.41.090[1961 c 15 § 84.41.090]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c251.pdf?cite=1955%20c%20251%20§%209[1955 c 251 § 9]; ]

== 84.41.100 - Assessor may appoint deputies and engage expert appraisers.
See RCW 36.21.011.

[ ]

== 84.41.110 - Appraisers to act in advisory capacity.
Appraisers whose services may be obtained by contract or who may be assigned by the department of revenue to assist any county assessor shall act in an advisory capacity only, and valuations made by them shall not in any manner be binding upon the assessor, it being the intent herein that all valuations made pursuant to this chapter shall be made and entered by the assessor pursuant to law as directed herein.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c278.pdf?cite=1975%201st%20ex.s.%20c%20278%20§%20201[1975 1st ex.s. c 278 § 201]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c15.pdf?cite=1961%20c%2015%20§%2084.41.110[1961 c 15 § 84.41.110]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c251.pdf?cite=1955%20c%20251%20§%2011[1955 c 251 § 11]; ]

== 84.41.120 - Assessor to keep records—Orders of department of revenue, compliance enjoined, remedies.
Each county assessor shall keep such books and records as are required by the rules and regulations of the department of revenue and shall comply with any lawful order, rule, or regulation of the department of revenue.

Whenever it appears to the department of revenue that any assessor has failed to comply with any of the provisions of this chapter relating to his or her duties or the rules of the department of revenue made in pursuance thereof, the department of revenue, after a hearing on the facts, may issue an order directing such assessor to comply with such provisions of this chapter or rules of the department of revenue. Such order shall be mailed by registered mail to the assessor at the county courthouse. If, upon the expiration of fifteen days from the date such order is mailed, the assessor has not complied therewith or has not taken measures that will insure compliance within a reasonable time, the department of revenue may apply to a judge of the superior court or court commissioner of the county in which such assessor holds office, for an order returnable within five days from the date thereof to compel him or her to comply with such provisions of law or of the order of the department of revenue or to show cause why he or she should not be compelled so to do. Any order issued by the judge pursuant to such order to show cause shall be final. The remedy herein provided shall be cumulative and shall not exclude the department of revenue from exercising any powers or rights otherwise granted.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20366[2013 c 23 § 366]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c278.pdf?cite=1975%201st%20ex.s.%20c%20278%20§%20202[1975 1st ex.s. c 278 § 202]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c15.pdf?cite=1961%20c%2015%20§%2084.41.120[1961 c 15 § 84.41.120]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c251.pdf?cite=1955%20c%20251%20§%2012[1955 c 251 § 12]; ]

== 84.41.130 - Assessor's annual reports.
Each county assessor, before October 15th each year, shall prepare and submit to the department of revenue a detailed report of the progress made in the revaluation program in his or her county to the date of the report and be made a matter of public record. Such report shall be submitted upon forms supplied by the department of revenue and shall consist of such information as the department of revenue requires.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6219.SL.pdf?cite=1998%20c%20245%20§%20171[1998 c 245 § 171]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c278.pdf?cite=1975%201st%20ex.s.%20c%20278%20§%20203[1975 1st ex.s. c 278 § 203]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c15.pdf?cite=1961%20c%2015%20§%2084.41.130[1961 c 15 § 84.41.130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c251.pdf?cite=1955%20c%20251%20§%2013[1955 c 251 § 13]; ]

