= 84.55 - Limitations upon regular property taxes.
:toc:

== 84.55.005 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Inflation" means the percentage change in the implicit price deflator for personal consumption expenditures for the United States as published for the most recent twelve-month period by the bureau of economic analysis of the federal department of commerce by September 25th of the year before the taxes are payable;

. "Limit factor" means:

.. For taxing districts with a population of less than ten thousand in the calendar year prior to the assessment year, one hundred one percent;

.. For taxing districts for which a limit factor is authorized under RCW 84.55.0101, the lesser of the limit factor authorized under that section or one hundred one percent;

.. For all other districts, the lesser of one hundred one percent or one hundred percent plus inflation; and

. "Regular property taxes" has the meaning given it in RCW 84.04.140.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6333-S.SL.pdf?cite=2014%20c%2097%20§%20316[2014 c 97 § 316]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2416.SL.pdf?cite=2007%20sp.s.%20c%201%20§%201[2007 sp.s. c 1 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5028-S.SL.pdf?cite=1997%20c%20393%20§%2020[1997 c 393 § 20]; 1997 c 3 § 201 (Referendum Bill No. 47, approved November 4, 1997); http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5372-S2.SL.pdf?cite=1994%20c%20301%20§%2049[1994 c 301 § 49]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c62.pdf?cite=1983%201st%20ex.s.%20c%2062%20§%2011[1983 1st ex.s. c 62 § 11]; ]

== 84.55.010 - Limitations prescribed.
. Except as provided in this chapter, the levy for a taxing district in any year must be set so that the regular property taxes payable in the following year do not exceed the limit factor multiplied by the amount of regular property taxes lawfully levied for such district in the highest of the three most recent years in which such taxes were levied for such district plus an additional dollar amount calculated by multiplying the regular property tax levy rate of that district for the preceding year by the increase in assessed value in that district resulting from:

.. New construction;

.. Increases in assessed value due to construction of wind turbine, solar, biomass, and geothermal facilities, if such facilities generate electricity and the property is not included elsewhere under this section for purposes of providing an additional dollar amount. The property may be classified as real or personal property;

.. Improvements to property; and

.. Any increase in the assessed value of state-assessed property.

. The requirements of this section do not apply to:

.. State property taxes levied under RCW 84.52.065(1) for collection in calendar years 2019 through 2021; and

.. State property taxes levied under RCW 84.52.065(2) for collection in calendar years 2018 through 2021.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2242.SL.pdf?cite=2017%203rd%20sp.s.%20c%2013%20§%20302[2017 3rd sp.s. c 13 § 302]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1634-S.SL.pdf?cite=2014%20c%204%20§%201[2014 c 4 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6141-S.SL.pdf?cite=2006%20c%20184%20§%201[2006 c 184 § 1]; 1997 c 3 § 202 (Referendum Bill No. 47, approved November 4, 1997); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c218.pdf?cite=1979%20ex.s.%20c%20218%20§%202[1979 ex.s. c 218 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c67.pdf?cite=1973%201st%20ex.s.%20c%2067%20§%201[1973 1st ex.s. c 67 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c288.pdf?cite=1971%20ex.s.%20c%20288%20§%2020[1971 ex.s. c 288 § 20]; ]

== 84.55.0101 - Limit factor—Authorization for taxing district to use one hundred one percent or less—Ordinance or resolution.
Upon a finding of substantial need, the legislative authority of a taxing district other than the state may provide for the use of a limit factor under this chapter of one hundred one percent or less. In districts with legislative authorities of four members or less, two-thirds of the members must approve an ordinance or resolution under this section. In districts with more than four members, a majority plus one vote must approve an ordinance or resolution under this section. The new limit factor shall be effective for taxes collected in the following year only.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2416.SL.pdf?cite=2007%20sp.s.%20c%201%20§%202[2007 sp.s. c 1 § 2]; 1997 c 3 § 204 (Referendum Bill No. 47, approved November 4, 1997); ]

== 84.55.015 - Restoration of regular levy.
If a taxing district has not levied since 1985 and elects to restore a regular property tax levy subject to applicable statutory limitations then such first restored levy must be set so that the regular property tax payable does not exceed the amount which was last levied, plus an additional dollar amount calculated by multiplying the property tax rate which is proposed to be restored, or the maximum amount which could be lawfully levied in the year such a restored levy is proposed, by the increase in assessed value in the district since the last levy resulting from:

. New construction;

. Increases in assessed value due to construction of wind turbine, solar, biomass, and geothermal facilities, if such facilities generate electricity and the property is not included elsewhere under this section for purposes of providing an additional dollar amount. The property may be classified as real or personal property;

. Improvements to property; and

. Any increase in the assessed value of state-assessed property.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1634-S.SL.pdf?cite=2014%20c%204%20§%202[2014 c 4 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6141-S.SL.pdf?cite=2006%20c%20184%20§%202[2006 c 184 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5495-S.SL.pdf?cite=1999%20c%2096%20§%201[1999 c 96 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c218.pdf?cite=1979%20ex.s.%20c%20218%20§%204[1979 ex.s. c 218 § 4]; ]

== 84.55.020 - Limitation upon first levy for district created from consolidation.
Notwithstanding the limitation set forth in RCW 84.55.010, the first levy for a taxing district created from consolidation of similar taxing districts must be set so that the regular property taxes payable in the following year do not exceed the limit factor multiplied by the sum of the amount of regular property taxes lawfully levied for each component taxing district in the highest of the three most recent years in which such taxes were levied for such district plus the additional dollar amount calculated by multiplying the regular property tax rate of each component district for the preceding year by the increase in assessed value in each component district resulting from:

. New construction;

. Increases in assessed value due to construction of wind turbine, solar, biomass, and geothermal facilities, if such facilities generate electricity and the property is not included elsewhere under this section for purposes of providing an additional dollar amount. The property may be classified as real or personal property;

. Improvements to property; and

. Any increase in the assessed value of state-assessed property.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1634-S.SL.pdf?cite=2014%20c%204%20§%203[2014 c 4 § 3]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6141-S.SL.pdf?cite=2006%20c%20184%20§%203[2006 c 184 § 3]; 1997 c 3 § 203 (Referendum Bill No. 47, approved November 4, 1997); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c288.pdf?cite=1971%20ex.s.%20c%20288%20§%2021[1971 ex.s. c 288 § 21]; ]

== 84.55.030 - Limitation upon first levy following annexation.
For the first levy for a taxing district following annexation of additional property, the limitation set forth in RCW 84.55.010 must be increased by an amount equal to the aggregate assessed valuation of the newly annexed property as shown by the current completed and balanced tax rolls of the county or counties within which such property lies, multiplied by the dollar rate that would have been used by the annexing unit in the absence of such annexation, plus the additional dollar amount calculated by multiplying the regular property tax levy rate of that annexing taxing district for the preceding year by the increase in assessed value in the annexing district resulting from:

. New construction;

. Increases in assessed value due to construction of wind turbine, solar, biomass, and geothermal facilities, if such facilities generate electricity and the property is not included elsewhere under this section for purposes of providing an additional dollar amount. The property may be classified as real or personal property;

. Improvements to property; and

. Any increase in the assessed value of state-assessed property.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1634-S.SL.pdf?cite=2014%20c%204%20§%204[2014 c 4 § 4]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6141-S.SL.pdf?cite=2006%20c%20184%20§%204[2006 c 184 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c195.pdf?cite=1973%201st%20ex.s.%20c%20195%20§%20107[1973 1st ex.s. c 195 § 107]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c288.pdf?cite=1971%20ex.s.%20c%20288%20§%2022[1971 ex.s. c 288 § 22]; ]

== 84.55.035 - Inapplicability of limitation to newly-formed taxing district created other than by consolidation or annexation.
RCW 84.55.010 shall not apply to the first levy by or for a newly-formed taxing district created other than by consolidation or annexation.

This section shall be retroactive in effect and shall be deemed to validate any levy within its scope, even though the levy has been made prior to June 4, 1979.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c218.pdf?cite=1979%20ex.s.%20c%20218%20§%205[1979 ex.s. c 218 § 5]; ]

== 84.55.040 - Increase in statutory dollar rate limitation.
If by reason of the operation of RCW 84.52.043 and 84.52.050, as now or hereafter amended the statutory dollar rate limitation applicable to the levy by a taxing district has been increased over the statutory millage limitation applicable to such taxing district's levy in the preceding year, the limitation on the dollar rate amount of a levy provided for in this chapter shall be increased by multiplying the otherwise dollar limitation by a fraction, the numerator of which is the increased dollar limitation and the denominator of which is the dollar limitation for the prior year.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c195.pdf?cite=1973%201st%20ex.s.%20c%20195%20§%20108[1973 1st ex.s. c 195 § 108]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c195.pdf?cite=1973%201st%20ex.s.%20c%20195%20§%20151[1973 1st ex.s. c 195 § 151]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c288.pdf?cite=1971%20ex.s.%20c%20288%20§%2023[1971 ex.s. c 288 § 23]; ]

== 84.55.045 - Applicability of chapter to levy by port district for industrial development district purposes.
For purposes of applying the provisions of this chapter:

. A levy by or for a port district pursuant to *RCW 53.36.100 shall be treated in the same manner as a separate regular property tax levy made by or for a separate taxing district; and

. The first levy by or for a port district pursuant to *RCW 53.36.100 after April 1, 1982, shall not be subject to RCW 84.55.010.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982ex1c3.pdf?cite=1982%201st%20ex.s.%20c%203%20§%202[1982 1st ex.s. c 3 § 2]; ]

== 84.55.047 - Applicability of chapter to community revitalization financing increment areas.
Limitations on regular property taxes that are provided in this chapter shall continue in a taxing district whether or not an increment area exists within the taxing district as provided under chapter 39.89 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1418-S.SL.pdf?cite=2001%20c%20212%20§%2024[2001 c 212 § 24]; ]

== 84.55.050 - Election to authorize increase in regular property tax levy—Limited propositions—Procedure.
. Subject to any otherwise applicable statutory dollar rate limitations, regular property taxes may be levied by or for a taxing district in an amount exceeding the limitations provided for in this chapter if such levy is authorized by a proposition approved by a majority of the voters of the taxing district voting on the proposition at a general election held within the district or at a special election within the taxing district called by the district for the purpose of submitting such proposition to the voters. Any election held pursuant to this section shall be held not more than twelve months prior to the date on which the proposed levy is to be made, except as provided in subsection (2) of this section. The ballot of the proposition shall state the dollar rate proposed and shall clearly state the conditions, if any, which are applicable under subsection (4) of this section.

. [Empty]
.. Subject to statutory dollar limitations, a proposition placed before the voters under this section may authorize annual increases in levies for multiple consecutive years, up to six consecutive years, during which period each year's authorized maximum legal levy shall be used as the base upon which an increased levy limit for the succeeding year is computed, but the ballot proposition must state the dollar rate proposed only for the first year of the consecutive years and must state the limit factor, or a specified index to be used for determining a limit factor, such as the consumer price index, which need not be the same for all years, by which the regular tax levy for the district may be increased in each of the subsequent consecutive years. Elections for this purpose must be held at a primary or general election. The title of each ballot measure must state the limited purposes for which the proposed annual increases during the specified period of up to six consecutive years shall be used.

.. [Empty]
... Except as otherwise provided in this subsection (2)(b), funds raised by a levy under this subsection may not supplant existing funds used for the limited purpose specified in the ballot title. For purposes of this subsection, existing funds means the actual operating expenditures for the calendar year in which the ballot measure is approved by voters. Actual operating expenditures excludes lost federal funds, lost or expired state grants or loans, extraordinary events not likely to reoccur, changes in contract provisions beyond the control of the taxing district receiving the services, and major nonrecurring capital expenditures.

... The supplanting limitations in (b)(i) of this subsection do not apply to levies approved by the voters in calendar years 2009, 2010, and 2011, in any county with a population of one million five hundred thousand or more. This subsection (2)(b)(ii) only applies to levies approved by the voters after July 26, 2009.

... The supplanting limitations in (b)(i) of this subsection do not apply to levies approved by the voters in calendar year 2009 and thereafter in any county with a population less than one million five hundred thousand. This subsection (2)(b)(iii) only applies to levies approved by the voters after July 26, 2009.

. After a levy authorized pursuant to this section is made, the dollar amount of such levy may not be used for the purpose of computing the limitations for subsequent levies provided for in this chapter, unless the ballot proposition expressly states that the levy made under this section will be used for this purpose.

. If expressly stated, a proposition placed before the voters under subsection (1) or (2) of this section may:

.. Use the dollar amount of a levy under subsection (1) of this section, or the dollar amount of the final levy under subsection (2) of this section, for the purpose of computing the limitations for subsequent levies provided for in this chapter;

.. Limit the period for which the increased levy is to be made under (a) of this subsection;

.. Limit the purpose for which the increased levy is to be made under (a) of this subsection, but if the limited purpose includes making redemption payments on bonds;

... For the county in which the state capitol is located, the period for which the increased levies are made may not exceed twenty-five years; and

... For districts other than a district under (c)(i) of this subsection, the period for which the increased levies are made may not exceed nine years;

.. Set the levy or levies at a rate less than the maximum rate allowed for the district;

.. Provide that the exemption authorized by RCW 84.36.381 will apply to the levy of any additional regular property taxes authorized by voters; or

.. Include any combination of the conditions in this subsection.

. Except as otherwise expressly stated in an approved ballot measure under this section, subsequent levies shall be computed as if:

.. The proposition under this section had not been approved; and

.. The taxing district had made levies at the maximum rates which would otherwise have been allowed under this chapter during the years levies were made under the proposition.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2597-S.SL.pdf?cite=2018%20c%2046%20§%203[2018 c 46 § 3]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1344-S.SL.pdf?cite=2017%20c%20296%20§%202[2017 c 296 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5433-S2.SL.pdf?cite=2009%20c%20551%20§%203[2009 c 551 § 3]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6641.SL.pdf?cite=2008%20c%20319%20§%201[2008 c 319 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5498.SL.pdf?cite=2007%20c%20380%20§%202[2007 c 380 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5659-S.SL.pdf?cite=2003%201st%20sp.s.%20c%2024%20§%204[2003 1st sp.s. c 24 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c287.pdf?cite=1989%20c%20287%20§%201[1989 c 287 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c169.pdf?cite=1986%20c%20169%20§%201[1986 c 169 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c218.pdf?cite=1979%20ex.s.%20c%20218%20§%203[1979 ex.s. c 218 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c195.pdf?cite=1973%201st%20ex.s.%20c%20195%20§%20109[1973 1st ex.s. c 195 § 109]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c288.pdf?cite=1971%20ex.s.%20c%20288%20§%2024[1971 ex.s. c 288 § 24]; ]

== 84.55.060 - Rate rules—Educational program—Other necessary action.
The department of revenue shall adopt rules relating to the calculation of tax rates and the limitation in RCW 84.55.010, conduct an educational program on this subject, and take any other action necessary to insure compliance with the statutes and rules on this subject.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c218.pdf?cite=1979%20ex.s.%20c%20218%20§%206[1979 ex.s. c 218 § 6]; ]

== 84.55.070 - Inapplicability of chapter to levies for certain purposes.
The provisions of this chapter do not apply to a levy, including any state levy, or that portion of a levy, made by or for a taxing district:

. For the purpose of funding a property tax refund paid under the provisions of chapter 84.68 RCW;

. Under RCW 84.69.180; or

. Attributable to amounts of state taxes withheld under RCW 84.56.290 or the provisions of chapter 84.69 RCW, or otherwise attributable to state taxes lawfully owing by reason of adjustments made under RCW 84.48.080.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2242.SL.pdf?cite=2017%203rd%20sp.s.%20c%2013%20§%20308[2017 3rd sp.s. c 13 § 308]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1208-S2.SL.pdf?cite=2009%20c%20350%20§%2011[2009 c 350 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982ex1c28.pdf?cite=1982%201st%20ex.s.%20c%2028%20§%202[1982 1st ex.s. c 28 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c228.pdf?cite=1981%20c%20228%20§%203[1981 c 228 § 3]; ]

== 84.55.092 - Protection of future levy capacity.
. The regular property tax levy for each taxing district other than the state's levies may be set at the amount which would be allowed otherwise under this chapter if the regular property tax levy for the district for taxes due in prior years beginning with 1986 had been set at the full amount allowed under this chapter including any levy authorized under RCW 52.16.160 or 52.26.140(1)(c) that would have been imposed but for the limitation in RCW 52.18.065 or 52.26.240, applicable upon imposition of the benefit charge under chapter 52.18 or 52.26 RCW.

. The purpose of subsection (1) of this section is to remove the incentive for a taxing district to maintain its tax levy at the maximum level permitted under this chapter, and to protect the future levy capacity of a taxing district that reduces its tax levy below the level that it otherwise could impose under this chapter, by removing the adverse consequences to future levy capacities resulting from such levy reductions.

. Subsection (1) of this section does not apply to any portion of a city or town's regular property tax levy that has been reduced as part of the formation of a fire protection district under RCW 52.02.160.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2242.SL.pdf?cite=2017%203rd%20sp.s.%20c%2013%20§%20309[2017 3rd sp.s. c 13 § 309]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5628-S.SL.pdf?cite=2017%20c%20328%20§%203[2017 c 328 § 3]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1467-S.SL.pdf?cite=2017%20c%20196%20§%203[2017 c 196 § 3]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6285-S.SL.pdf?cite=1998%20c%2016%20§%203[1998 c 16 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c274.pdf?cite=1988%20c%20274%20§%204[1988 c 274 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c107.pdf?cite=1986%20c%20107%20§%203[1986 c 107 § 3]; ]

== 84.55.100 - Determination of limitations.
The property tax limitation contained in this chapter shall be determined by the county assessors of the respective counties in accordance with the provisions of this chapter: PROVIDED, That the limitation for any state levy shall be determined by the department of revenue and the limitation for any intercounty rural library district shall be determined by the library district in consultation with the respective county assessors.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c223.pdf?cite=1983%20c%20223%20§%201[1983 c 223 § 1]; ]

== 84.55.110 - Withdrawal of certain areas of a library district, metropolitan park district, fire protection district, or public hospital district—Calculation of taxes due.
Whenever a withdrawal occurs under RCW 27.12.355, 35.61.360, 52.04.056, or 70.44.235, restrictions under chapter 84.55 RCW on the taxes due for the library district, metropolitan park district, fire protection district, or public hospital district, and restrictions under chapter 84.55 RCW on the taxes due for the city or town if an entire city or town area is withdrawn from a library district or fire protection district, shall be calculated as if the withdrawn area had not been part of the library district, metropolitan park district, fire protection district, or public hospital district, and as if the library district or fire protection district had not been part of the city or town.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c138.pdf?cite=1987%20c%20138%20§%206[1987 c 138 § 6]; ]

== 84.55.120 - Public hearing—Taxing district's revenue sources—Adoption of tax increase by ordinance or resolution.
. A taxing district, other than the state, that collects regular levies must hold a public hearing on revenue sources for the district's following year's current expense budget. The hearing must include consideration of possible increases in property tax revenues and must be held prior to the time the taxing district levies the taxes or makes the request to have the taxes levied. The county legislative authority, or the taxing district's governing body if the district is a city, town, or other type of district, must hold the hearing. For purposes of this section, "current expense budget" means that budget which is primarily funded by taxes and charges and reflects the provision of ongoing services. It does not mean the capital, enterprise, or special assessment budgets of cities, towns, counties, or special purpose districts.

. If the taxing district is otherwise required to hold a public hearing on its proposed regular tax levy, a single public hearing may be held on this matter.

. [Empty]
.. Except as provided in (b) of this subsection (3), no increase in property tax revenue may be authorized by a taxing district, other than the state, except by adoption of a separate ordinance or resolution, pursuant to notice, specifically authorizing the increase in terms of both dollars and percentage. The ordinance or resolution may cover a period of up to two years, but the ordinance must specifically state for each year the dollar increase and percentage change in the levy from the previous year.

.. Exempt from the requirements of (a) of this subsection are increases in revenue resulting from the addition of:

... New construction;

... Increases in assessed value due to construction of wind turbine, solar, biomass, and geothermal facilities, if such facilities generate electricity and the property is not included elsewhere under this section for purposes of providing an additional dollar amount. The property may be classified as real or personal property;

... Improvements to property; and

... Any increase in the value of state-assessed property.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1634-S.SL.pdf?cite=2014%20c%204%20§%205[2014 c 4 § 5]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6141-S.SL.pdf?cite=2006%20c%20184%20§%206[2006 c 184 § 6]; 1997 c 3 § 209 (Referendum Bill No. 47, approved November 4, 1997); http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5443-S.SL.pdf?cite=1995%20c%20251%20§%201[1995 c 251 § 1]; ]

== 84.55.125 - Limitation adjustment for certain leasehold interests.
For taxes levied for collection in 2002, the limitation set forth in RCW 84.55.010 for a taxing district shall be increased by an amount equal to the aggregate assessed valuation of leasehold interests subject to tax by the district under RCW 84.40.410, multiplied by the regular property tax levy rate of that district for the preceding year.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1055.SL.pdf?cite=2001%20c%2026%20§%204[2001 c 26 § 4]; ]

== 84.55.130 - Inapplicability of limitation to certain multiyear levy periods by port districts.
. Except as provided in RCW 53.36.160(3), RCW 84.55.010 does not apply to a levy under RCW 53.36.160.

. For purposes of applying the provisions of this chapter, a levy by or for a port district under RCW 53.36.160(3) must be treated in the same manner as a separate regular property tax levy made by or for a separate taxing district.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1337-S.SL.pdf?cite=2015%20c%20135%20§%203[2015 c 135 § 3]; ]

== 84.55.135 - Property tax levies or special assessments on dissolved special purpose districts—When authorized.
. Except as provided in subsection (2) of this section, if a county dissolves a special purpose district under chapter 36.96 RCW, the county may impose a separate property tax levy or special assessment on the property lying within the former boundaries of the dissolved special purpose district beginning in the first calendar year following dissolution if:

.. The county assumes responsibility of the services previously provided by the special purpose district; and

.. The property tax levy or special assessment does not exceed any legally authorized property tax levy rate or special assessment for the dissolved special purpose district.

. If a county discontinues providing the services of a dissolved special purpose district for which the county imposed a separate property tax levy or special assessment as provided in subsection (1) of this section, the county must cease imposing that property tax levy or special assessment beginning in the first calendar year after the discontinuation of the provision of services by the county.

. For purposes of RCW 84.52.010 and 84.52.043, a property tax levy authorized by a county under this section is subject to the same provisions as the county's general property tax levy.

. The limitation in RCW 84.55.010 does not apply to the first property tax levy imposed under this section.

. For purposes of this section, "special assessment" means any special assessment, benefit assessment, or rates and charges imposed by a special purpose district.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2588-S.SL.pdf?cite=2020%20c%20179%20§%206[2020 c 179 § 6]; ]

