= 84.72 - Federal payments in lieu of taxes.
:toc:

== 84.72.010 - State treasurer authorized to receive in lieu payments—Department of revenue to apportion.
The state treasurer is hereby authorized and directed to receive any moneys that may be paid to the state by the United States or any agency thereof in lieu of ad valorem property taxes, and to transfer the same to the respective county treasurers in compliance with apportionments made by the state department of revenue; and the state treasurer shall immediately notify the department of revenue of the receipt of any such payment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c278.pdf?cite=1975%201st%20ex.s.%20c%20278%20§%20211[1975 1st ex.s. c 278 § 211]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c15.pdf?cite=1961%20c%2015%20§%2084.72.010[1961 c 15 § 84.72.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c199.pdf?cite=1941%20c%20199%20§%201[1941 c 199 § 1]; Rem. Supp. 1941 § 11337-15; ]

== 84.72.020 - Basis of apportionment.
Any such moneys so paid to the state treasurer shall be apportioned to the state and to the taxing districts thereof that would be entitled to share in the property taxes in lieu of which such payments are made in the same proportion that the state and such taxing units would have shared in such property taxes if the same had been levied. The basis of apportionment shall be the same as that of property taxes first collectible in the year in which such lieu payment is made: PROVIDED, That if any such lieu payment cannot be so apportioned the apportionment shall be made on such basis as the department of revenue shall deem equitable and proper.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c278.pdf?cite=1975%201st%20ex.s.%20c%20278%20§%20212[1975 1st ex.s. c 278 § 212]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c15.pdf?cite=1961%20c%2015%20§%2084.72.020[1961 c 15 § 84.72.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c199.pdf?cite=1941%20c%20199%20§%202[1941 c 199 § 2]; Rem. Supp. 1941 § 11337-16; ]

== 84.72.030 - Certification of apportionment to state treasurer—Distribution to county treasurers.
The department of revenue may indicate either the exact apportionment to taxing units or it may direct in general terms that county treasurers shall apportion any such lieu payment in the manner provided in RCW 84.72.020. In either event the department of revenue shall certify to the state treasurer the basis of apportionment and the state treasurer shall thereupon forthwith transmit any such lieu payment, together with a statement of the basis of apportionment, to the county treasurer in accordance with such certification.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c278.pdf?cite=1975%201st%20ex.s.%20c%20278%20§%20213[1975 1st ex.s. c 278 § 213]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c15.pdf?cite=1961%20c%2015%20§%2084.72.030[1961 c 15 § 84.72.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c199.pdf?cite=1941%20c%20199%20§%203[1941 c 199 § 3]; Rem. Supp. 1941 § 11337-17; ]

