= 84.98 - Construction.
:toc:

== 84.98.010 - Continuation of existing law.
The provisions of this title insofar as they are substantially the same as statutory provisions repealed by this chapter, and relating to the same subject matter, shall be construed as restatements and continuations, and not as new enactments.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c15.pdf?cite=1961%20c%2015%20§%2084.98.010[1961 c 15 § 84.98.010]; ]

== 84.98.020 - Title, chapter, section headings not part of law.
Title headings, chapter headings, and section or subsection headings, as used in this title, do not constitute any part of the law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c15.pdf?cite=1961%20c%2015%20§%2084.98.020[1961 c 15 § 84.98.020]; ]

== 84.98.030 - Invalidity of part of title not to affect remainder.
If any section, subdivision of a section, paragraph, sentence, clause or word of this title for any reason shall be adjudged invalid, such judgment shall not affect, impair or invalidate the remainder of this title but shall be confined in its operation to the section, subdivision of a section, paragraph, sentence, clause or word directly involved in the controversy in which such judgment shall have been rendered. If any tax imposed under this title shall be adjudged invalid as to any person, corporation, association or class of persons, corporations or associations included within the scope of the general language of this title such invalidity shall not affect the liability of any person, corporation, association or class of persons, corporations or associations as to which such tax has not been adjudged invalid. It is hereby expressly declared that had any section, subdivision of a section, paragraph, sentence, clause, word or any person, corporation, association or class of persons, corporations or associations as to which this title is declared invalid been eliminated from the title at the time the same was considered the title would have nevertheless been enacted with such portions eliminated.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c15.pdf?cite=1961%20c%2015%20s%2084.98.030[1961 c 15 s 84.98.030]; ]

== 84.98.040 - Repeals and saving.
See 1961 c 15 s 84.98.040.

[ ]

== 84.98.050 - Emergency—1961 c 15.
This act is necessary for the immediate preservation of the public peace, health and safety, the support of the state government and its existing public institutions, and shall take effect immediately.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c15.pdf?cite=1961%20c%2015%20§%2084.98.050[1961 c 15 § 84.98.050]; ]

