= 23.95 - Uniform business organizations code.
:toc:

== 23.95.100 - Short title.
This chapter may be known and cited as the uniform business organizations code—general provisions.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201101[2015 c 176 § 1101]; ]

== 23.95.105 - Definitions. (Effective until January 1, 2022.)
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise or as set forth in RCW 23.95.400 or 23.95.600.

. "Annual report" means the report required by RCW 23.95.255.

. "Business corporation" means a domestic business corporation incorporated under or subject to Title 23B RCW or a foreign business corporation.

. "Commercial registered agent" means a person listed under RCW 23.95.420.

. "Domestic," with respect to an entity, means governed as to its internal affairs by the law of this state.

. "Electronic transmission" means an electronic communication:

.. Not directly involving the physical transfer of a record in a tangible medium; and

.. That may be retained, retrieved, and reviewed by the sender and the recipient thereof, and that may be directly reproduced in a tangible medium by such a sender and recipient.

. "Entity" means:

.. A business corporation;

.. A nonprofit corporation;

.. A limited liability partnership;

.. A limited partnership;

.. A limited liability company;

.. A general cooperative association; or

.. A limited cooperative association.

. "Entity filing" means a record delivered to the secretary of state for filing pursuant to this chapter.

. "Execute," "executes," or "executed" means with present intent to authenticate or adopt a record:

.. To sign or adopt a tangible symbol;

.. To attach to or logically associate with the record an electronic symbol, sound, or process; or

.. With respect to a record to be filed with the secretary of state, in compliance with the standards for filing with the office of the secretary of state as prescribed by the secretary of state.

. "Filed record" means a record filed by the secretary of state pursuant to this chapter.

. "Foreign," with respect to an entity, means governed as to its internal affairs by the law of a jurisdiction other than this state.

. "General cooperative association" means a domestic general cooperative association formed under or subject to chapter 23.86 RCW.

. "Governor" means:

.. A director of a business corporation;

.. A director of a nonprofit corporation;

.. A partner of a limited liability partnership;

.. A general partner of a limited partnership;

.. A manager of a manager-managed limited liability company;

.. A member of a member-managed limited liability company;

.. A director of a general cooperative association;

.. A director of a limited cooperative association; or

.. Any other person under whose authority the powers of an entity are exercised and under whose direction the activities and affairs of the entity are managed pursuant to the organic law and organic rules of the entity.

. "Interest" means:

.. A share in a business corporation;

.. A membership in a nonprofit corporation;

.. A share in a nonprofit corporation formed under chapter 24.06 RCW;

.. A partnership interest in a limited liability partnership;

.. A partnership interest in a limited partnership;

.. A limited liability company interest;

.. A share or membership in a general cooperative association; or

.. A member's interest in a limited cooperative association.

. "Interest holder" means:

.. A shareholder of a business corporation;

.. A member of a nonprofit corporation;

.. A shareholder of a nonprofit corporation formed under chapter 24.06 RCW;

.. A partner of a limited liability partnership;

.. A general partner of a limited partnership;

.. A limited partner of a limited partnership;

.. A member of a limited liability company;

.. A shareholder or member of a general cooperative association; or

.. A member of a limited cooperative association.

. "Jurisdiction," when used to refer to a political entity, means the United States, a state, a foreign country, or a political subdivision of a foreign country.

. "Jurisdiction of formation" means the jurisdiction whose law includes the organic law of an entity.

. "Limited cooperative association" means a domestic limited cooperative association formed under or subject to chapter 23.100 RCW or a foreign limited cooperative association.

. "Limited liability company" means a domestic limited liability company formed under or subject to chapter 25.15 RCW or a foreign limited liability company.

. "Limited liability limited partnership" means a domestic limited liability limited partnership formed under or subject to chapter 25.10 RCW or a foreign limited liability limited partnership.

. "Limited liability partnership" means a domestic limited liability partnership registered under or subject to chapter 25.05 RCW or a foreign limited liability partnership.

. "Limited partnership" means a domestic limited partnership formed under or subject to chapter 25.10 RCW or a foreign limited partnership. "Limited partnership" includes a limited liability limited partnership.

. "Noncommercial registered agent" means a person that is not a commercial registered agent and is:

.. An individual or domestic or foreign entity that serves in this state as the registered agent of an entity;

.. An individual who holds the office or other position in an entity which is designated as the registered agent pursuant to RCW 23.95.415(1)(b)(ii); or

.. A government, governmental subdivision, agency, or instrumentality, or a separate legal entity comprised of two or more of these entities, that serves as the registered agent of an entity.

. "Nonprofit corporation" means a domestic nonprofit corporation incorporated under or subject to chapter 24.03 or 24.06 RCW or a foreign nonprofit corporation.

. "Nonregistered foreign entity" means a foreign entity that is not registered to do business in this state pursuant to a statement of registration filed by the secretary of state.

. "Organic law" means the law of an entity's jurisdiction of formation governing the internal affairs of the entity.

. "Organic rules" means the public organic record and private organic rules of an entity.

. "Person" means an individual, business corporation, nonprofit corporation, partnership, limited partnership, limited liability company, general cooperative association, limited cooperative association, unincorporated nonprofit association, statutory trust, business trust, common-law business trust, estate, trust, association, joint venture, public corporation, government or governmental subdivision, agency, or instrumentality, or any other legal or commercial entity.

. "Principal office" means the principal executive office of an entity, whether or not the office is located in this state.

. "Private organic rules" means the rules, whether or not in a record, that govern the internal affairs of an entity, are binding on all its interest holders, and are not part of its public organic record, if any. "Private organic rules" includes:

.. The bylaws of a business corporation and any agreement among shareholders pursuant to RCW 23B.07.320;

.. The bylaws of a nonprofit corporation;

.. The partnership agreement of a limited liability partnership;

.. The partnership agreement of a limited partnership;

.. The limited liability company agreement;

.. The bylaws of a general cooperative association; and

.. The bylaws of a limited cooperative association.

. "Proceeding" means civil suit and criminal, administrative, and investigatory action.

. "Property" means all property, whether real, personal, or mixed or tangible or intangible, or any right or interest therein.

. "Public organic record" means the record the filing of which by the secretary of state is required to form an entity and any amendment to or restatement of that record. The term includes:

.. The articles of incorporation of a business corporation;

.. The articles of incorporation of a nonprofit corporation;

.. The certificate of limited partnership of a limited partnership;

.. The certificate of formation of a limited liability company;

.. The articles of incorporation of a general cooperative association;

.. The articles of organization of a limited cooperative association; and

.. The document under the laws of another jurisdiction that is equivalent to a document listed in this subsection.

. "Receipt," as used in this chapter, means actual receipt. "Receive" has a corresponding meaning.

. "Record" means information that is inscribed on a tangible medium or that is stored in an electronic or other medium and is retrievable in perceivable form.

. "Registered agent" means an agent of an entity which is authorized to receive service of any process, notice, or demand required or permitted by law to be served on the entity. The term includes a commercial registered agent and a noncommercial registered agent.

. "Registered foreign entity" means a foreign entity that is registered to do business in this state pursuant to a certificate of registration filed by the secretary of state.

. "State" means a state of the United States, the District of Columbia, Puerto Rico, the United States Virgin Islands, or any territory or insular possession subject to the jurisdiction of the United States.

. "Tangible medium" means a writing, copy of a writing, facsimile, or a physical reproduction, each on paper or on other tangible material.

. "Transfer" includes:

.. An assignment;

.. A conveyance;

.. A sale;

.. A lease;

.. An encumbrance, including a mortgage or security interest;

.. A change of record owner of interest;

.. A gift; and

.. A transfer by operation of law.

. "Type of entity" means a generic form of entity:

.. Recognized at common law; or

.. Formed under an organic law, whether or not some entities formed under that law are subject to provisions of that law that create different categories of the form of entity.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2029[2020 c 57 § 29]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5002.SL.pdf?cite=2019%20c%2037%20§%201401[2019 c 37 § 1401]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201102[2015 c 176 § 1102]; ]

== 23.95.110 - Delivery of record.
. Except as otherwise provided in this chapter, permissible means of delivery of a record include delivery by hand, United States mail, private courier service, and electronic transmission.

. Records may be delivered to the secretary of state by electronic transmission as authorized by the secretary of state pursuant to RCW 23.95.115(2). The secretary of state may deliver a record to an entity by electronic transmission if the entity has designated an address, location, or system to which the record may be electronically transmitted.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201103[2015 c 176 § 1103]; ]

== 23.95.115 - Rules and procedures.
. The secretary of state has the power reasonably necessary to perform the duties required by this chapter, including adoption, amendment, or repeal of rules under chapter 34.05 RCW for the efficient administration of this chapter.

. The secretary of state may adopt rules to facilitate electronic filing. The rules will detail the circumstances under which the electronic filing of documents will be permitted, how the documents will be filed, and how the secretary of state will return filed documents. The rules may also impose additional requirements related to implementation of electronic filing processes, including but not limited to file formats, signature technologies, delivery, and the types of entities, records, or documents permitted.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201104[2015 c 176 § 1104]; ]

== 23.95.200 - Entity filing requirements.
. To be filed by the secretary of state pursuant to this chapter, an entity filing must be received by the secretary of state, comply with this chapter, and satisfy the following:

.. The entity filing must be required or permitted by Title 23, 23B, 24, or 25 RCW.

.. The entity filing must be delivered in a tangible medium unless and to the extent the secretary of state permits electronic delivery of entity filings pursuant to RCW 23.95.115(2).

.. The words in the entity filing must be in English, and numbers must be in Arabic or Roman numerals, but the name of the entity need not be in English if written in English letters or Arabic or Roman numerals.

.. The entity filing must be executed by or on behalf of a person authorized or required under this chapter or the entity's organic law to execute the filing.

.. The entity filing must state the name and capacity, if any, of each individual who executed it, on behalf of either the individual or the person authorized or required to execute the filing, but need not contain a seal, attestation, acknowledgment, or verification.

. When an entity filing is delivered to the secretary of state for filing, any fee required under this chapter and any fee, interest, or penalty required to be paid under this chapter or law other than this chapter must be paid in a manner permitted by the secretary of state or by that law.

. The secretary of state may require that an entity filing delivered in a tangible medium be accompanied by an identical or conformed copy.

. A record filed under this chapter may be executed by an individual acting in a valid representative capacity.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2030[2020 c 57 § 30]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201201[2015 c 176 § 1201]; ]

== 23.95.205 - Forms.
. The secretary of state may provide forms for entity filings required or permitted to be made by Title 23, 23B, 24, or 25 RCW, but, except as otherwise provided in subsection (2) of this section, their use is not required.

. The secretary of state may require that a cover sheet for an entity filing and an annual report be on forms prescribed by the secretary of state.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201202[2015 c 176 § 1202]; ]

== 23.95.210 - Effective date and time.
Except as otherwise provided in this chapter and subject to RCW 23.95.220(4), an entity filing is effective:

. On the date of filing and at the time specified in the entity filing as its effective time;

. Unless prohibited by the entity's organic law, at a specified delayed effective date and time, which may not be more than ninety days after the date of filing;

. If a delayed effective date is specified, but no time is specified, at 12:01 a.m. on the date specified; or

. If subsection (1), (2), or (3) of this section does not apply, on the date and at the time of its filing by the secretary of state as provided in RCW 23.95.225.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201203[2015 c 176 § 1203]; ]

== 23.95.215 - Withdrawal of filed record before effectiveness.
. Except as otherwise provided in this chapter, a filed record may be withdrawn before it takes effect by delivering to the secretary of state for filing a statement of withdrawal.

. A statement of withdrawal must:

.. Be executed by an individual acting in a valid representative capacity; and

.. Identify the filed record to be withdrawn.

. On filing by the secretary of state of a statement of withdrawal, the action or transaction evidenced by the original filed record shall not take effect.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201204[2015 c 176 § 1204]; ]

== 23.95.220 - Correcting filed record.
. An entity may correct a filed record if:

.. The filed record at the time of filing contained an inaccurate statement;

.. The filed record was defectively executed; or

.. The electronic transmission of the filed record to the secretary of state was defective.

. To correct a filed record, the entity must deliver to the secretary of state for filing a statement of correction.

. A statement of correction:

.. May not state a delayed effective date;

.. Must be executed by the individual correcting the filed record;

.. Must identify the filed record to be corrected;

.. Must specify the inaccuracy or defect to be corrected; and

.. Must correct the inaccuracy or defect.

. A statement of correction is effective as of the effective date of the filed record that it corrects except as to persons relying on the uncorrected filed record and adversely affected by the correction. As to those persons, the statement of correction is effective when filed.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201205[2015 c 176 § 1205]; ]

== 23.95.225 - Duty of secretary of state to file—Review of refusal to file.
. The secretary of state shall file an entity filing that satisfies this chapter. The duty of the secretary of state under this section is ministerial.

. The secretary of state shall record an entity filing on the date and at the time of its receipt. After filing an entity filing, the secretary of state shall deliver to the person that submitted the filing a copy of the filed record with an acknowledgment of the date and time of filing.

. If the secretary of state refuses to file an entity filing, the secretary of state not later than fifteen business days after the filing is received, shall:

.. Return the entity filing or notify the person that submitted the filing of the refusal; and

.. Provide a brief explanation in a record of the reason for the refusal.

. If the secretary of state refuses to file an entity filing, the person that submitted the entity filing may petition the superior court to compel its filing. The entity filing and the explanation of the secretary of state of the refusal to file must be attached to the petition. The court may decide the matter in a summary proceeding.

. The filing of or refusal to file an entity filing does not:

.. Affect the validity or invalidity of the entity filing in whole or in part;

.. Relate to the correctness or incorrectness of information contained in the entity filing; or

.. Create a presumption that the information contained in the filing is correct or incorrect.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201206[2015 c 176 § 1206]; ]

== 23.95.230 - Evidentiary effect of copy of filed record.
A certification from the secretary of state accompanying a copy of a filed record is conclusive evidence that the copy is an accurate representation of the original record on file with the secretary of state.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201207[2015 c 176 § 1207]; ]

== 23.95.235 - Certificate of existence or registration—Definitions.
. On request of any person, the secretary of state shall issue a certificate of existence for a domestic entity or a certificate of registration for a registered foreign entity.

. A certificate under subsection (1) of this section must state:

.. The domestic entity's name or the registered foreign entity's name used in this state;

.. In the case of a domestic entity:

... That its public organic record has been filed and has taken effect;

... The date the public organic record became effective;

... The period of the entity's duration if the records of the secretary of state reflect that the entity's period of duration is less than perpetual; and

... That the records of the secretary of state do not reflect that the entity has been dissolved;

.. In the case of a registered foreign entity:

... That it is registered to do business in this state;

... The date the foreign entity registered to do business in this state; and

... That the records of the secretary of state do not reflect that the foreign entity's registration to do business in the state has been terminated;

.. That all fees, interest, and penalties owed to this state by the domestic or foreign entity and collected through the secretary of state have been paid, if:

... Payment is reflected in the records of the secretary of state; and

... Nonpayment affects the existence or registration of the domestic or foreign entity;

.. That the most recent annual report required by RCW 23.95.255 has been delivered to the secretary of state for filing;

.. That a proceeding is not pending under RCW 23.95.610 as to a domestic entity or under RCW 23.95.550 as to a registered foreign entity; and

.. Other facts reflected in the records of the secretary of state pertaining to the domestic or foreign entity which the person requesting the certificate reasonably requests.

. Subject to any qualification stated in the certificate, a certificate issued by the secretary of state under subsection (1) of this section may be relied upon as conclusive evidence of the facts stated in the certificate, and that as of the date of its issuance: (a) In the case of a domestic entity, it is in existence and duly formed or incorporated, as applicable; and (b) in the case of a foreign entity, it is registered and authorized to do business in this state.

. The terms "doing business" and "transacting business," and their variants such as "do business" and "transact business," are used interchangeably, and each has the same meaning as the other when used in this title and in Titles 23B, 24, and 25 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5040.SL.pdf?cite=2017%20c%2031%20§%201[2017 c 31 § 1]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201208[2015 c 176 § 1208]; ]

== 23.95.240 - Execution of entity filing.
. Any person who executes a record the person knows is false in any material respect with the intent the record be an entity filing is guilty of a gross misdemeanor punishable under chapter 9A.20 RCW.

. A person that executes an entity filing as an agent or legal representative thereby affirms as a fact that the person is authorized to execute the entity filing.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201209[2015 c 176 § 1209]; ]

== 23.95.245 - Execution and filing pursuant to judicial order.
. If a person required by the entity's organic law to execute a record that is to be an entity filing or to make an entity filing does not do so, any other person that is aggrieved may petition the superior court to order:

.. The person to execute the record;

.. The person to make the entity filing; or

.. The secretary of state to file the entity filing unexecuted.

. If the petitioner under subsection (1) of this section is not the entity to which the entity filing pertains, the petitioner shall make the entity a party to the action.

. A filed record created under subsection (1)(c) of this section is effective without being executed.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201210[2015 c 176 § 1210]; ]

== 23.95.250 - Delivery by secretary of state.
Except as otherwise provided by RCW 23.95.450 or by law of this state other than this chapter, the secretary of state may deliver a record to a person by delivering it:

. In person to the person that submitted it for filing;

. To the address of the person's registered agent;

. To the principal office address of the person; or

. To another address the person provides to the secretary of state for delivery.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201211[2015 c 176 § 1211]; ]

== 23.95.255 - Initial or annual report for secretary of state. (Effective until January 1, 2022.)
. A domestic entity other than a limited liability partnership or nonprofit corporation shall, within one hundred twenty days of the date on which its public organic record became effective, deliver to the secretary of state for filing an initial report that states the information required under subsection (2) of this section.

. A domestic entity or registered foreign entity shall deliver to the secretary of state for filing an annual report that states:

.. The name of the entity and its jurisdiction of formation;

.. The name and street and mailing addresses of the entity's registered agent in this state;

.. The street and mailing addresses of the entity's principal office;

.. In the case of a registered foreign entity, the street and mailing address of the entity's principal office in the state or country under the laws of which it is incorporated;

.. The names of the entity's governors;

.. A brief description of the nature of the entity's business; and

.. The entity's unified business identifier number.

. Information in an initial or annual report must be current as of the date the report is executed by the entity.

. Annual reports must be delivered to the secretary of state on a date determined by the secretary of state and at such additional times as the entity elects.

. If an initial or annual report does not contain the information required by this section, the secretary of state promptly shall notify the reporting entity in a record and return the report for correction.

. If an initial or annual report contains the name or address of a registered agent that differs from the information shown in the records of the secretary of state immediately before the annual report becomes effective, the differing information in the initial or annual report is considered a statement of change under RCW 23.95.430.

. The secretary of state shall send to each domestic entity and registered foreign entity, not less than thirty or more than ninety days prior to the expiration date of the entity's annual renewal, a notice that the entity's annual report must be filed as required by this chapter and that any applicable annual renewal fee must be paid, and stating that if the entity fails to file its annual report or pay the annual renewal fee it will be administratively dissolved. The notice may be sent by postal or email as elected by the entity, addressed to its registered agent within the state, or to an electronic address designated by the entity in a record retained by the secretary of state. Failure of the secretary of state to provide any such notice does not relieve a domestic entity or registered foreign entity from its obligations to file the annual report required by this chapter or to pay any applicable annual renewal fee. The option to receive the notice provided under this section by email may be selected only when the secretary of state makes the option available.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5040.SL.pdf?cite=2017%20c%2031%20§%202[2017 c 31 § 2]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201212[2015 c 176 § 1212]; ]

== 23.95.260 - Fees.
. Except as provided in subsection (2) of this section, the secretary of state shall adopt rules in accordance with chapter 34.05 RCW setting:

.. Fees for:

... Filing entity filings;

... Furnishing copies or certified copies of any filed record under this chapter; and

... Furnishing a certificate of existence or registration of an entity, or any other certificate;

.. License or renewal fees authorized under Title 23, 23B, 24, or 25 RCW;

.. Penalty fees; and

.. Other miscellaneous charges. 

. There is no fee for:

.. A registered agent's consent to act as agent or statement of resignation;

.. Filing articles of dissolution;

.. Filing certificates of judicial dissolution;

.. Filing statements of withdrawal; and

.. Filing annual reports when submitted concurrently with the payment of annual license fees.

. The withdrawal under RCW 23.95.215 of a filed record before it is effective or the correction of a filed record under RCW 23.95.220 does not entitle the person on whose behalf the record was filed to a refund of the filing fee.

. The secretary of state shall establish the fee schedule authorized under this section in a manner that is consistent with the fee schedule applicable to the various entities that is in effect on January 1, 2016. The amounts of fees, charges, and penalties established under this section may be no greater than the amounts applicable to entity filings, penalties, and other charges in effect on January 1, 2016. Fees may be adjusted by rule only in an amount that does not exceed the average biennial increase in the cost of providing service. This must be determined in a biennial cost study performed by the secretary of state.

. All fees collected by the secretary of state shall be deposited with the state treasurer pursuant to law or deposited in the secretary of state's revolving fund as provided in RCW 43.07.130.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201213[2015 c 176 § 1213]; ]

== 23.95.265 - Waiver of penalty fees.
The secretary of state may, where exigent or mitigating circumstances are presented, waive penalty fees due from any entity previously in good standing which would otherwise be penalized or lose its active status. An entity desiring to seek relief under this section must, within fifteen days of discovery of the missed filing or lapse, notify the secretary of state as provided in rule. The notification must include the name and mailing address of the entity, the governor or other entity official to whom correspondence should be sent, and a statement under oath by a governor or other entity official, setting forth the nature of the missed filing or lapse, the circumstances giving rise to the missed filing or lapse, and the relief sought. If the secretary of state is satisfied that sufficient exigent or mitigating circumstances exist, that the entity has demonstrated good faith and a reasonable attempt to comply with the applicable statutes of this state, the secretary of state may issue an order allowing relief from the penalty. If the secretary of state determines the request does not comply with the requirements for relief, the secretary of state shall deny the relief and state the reasons for the denial. Any denial of relief by the secretary of state is not reviewable notwithstanding the provisions of chapter 34.05 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2031[2020 c 57 § 31]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201214[2015 c 176 § 1214]; ]

== 23.95.300 - Permitted names.
. The name of a domestic entity and the name under which a foreign entity may register to do business in this state , must be distinguishable on the records of the secretary of state from any:

.. Name of an existing domestic entity which at the time is not administratively dissolved;

.. Name of a foreign entity registered to do business in this state under Article 5 of this chapter;

.. Name reserved under RCW 23.95.310; or

.. Name registered under RCW 23.95.315.

. If an entity consents in a record to the use of its name and submits an undertaking in a form satisfactory to the secretary of state to change its name to a name that is distinguishable on the records of the secretary of state from any name in any category of names in subsection (1) of this section, the name of the consenting entity may be used by the person to which the consent was given.

. A name may not be considered distinguishable on the records of the secretary of state from the name of another entity by virtue of:

.. A variation in the words, phrases, or abbreviations indicating the type of entity, such as "corporation," "corp.," "incorporated," "Inc.," "company," "co.," "social purpose corporation," "SPC," "S.P.C.," "professional corporation," "PC," "P.C.," "professional service," "PS," "P.S.," "Limited," "Ltd.," "limited partnership," "LP," "L.P.," "limited liability partnership," "LLP," "L.L.P.," "registered limited liability partnership," "RLLP," "R.L.L.P.," "limited liability limited partnership," "LLLP," "L.L.L.P.," "registered limited liability limited partnership," "RLLLP," "R.L.L.L.P.," "limited liability company," "LLC," "L.L.C.," "professional limited liability company," "PLLC," or "P.L.L.C.";

.. The addition or deletion of an article or conjunction such as "the" or "and" from the same name;

.. Punctuation, capitalization, or special characters or symbols in the same name; or

.. Use of abbreviation or the plural form of a word in the same name.

. An entity name may not contain language stating or implying that the entity is organized for a purpose other than those permitted by the entity's public organic record.

. This chapter does not control the use of assumed business names or "trade names."

. An entity may use a name that is not distinguishable from a name described in subsection (1) of this section if the entity delivers to the secretary of state a certified copy of a final judgment of a court of competent jurisdiction establishing the right of the entity to use the name in this state.

. An entity may use the name, including the fictitious name, of another entity that is used in this state if the other entity is formed or authorized to transact business in this state and the proposed user entity:

.. Has merged with the other entity; or

.. Has been formed by reorganization of the other entity.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201301[2015 c 176 § 1301]; ]

== 23.95.305 - Name requirements for certain types of entities. (Effective until January 1, 2022.)
. [Empty]
.. The name of a business corporation:

...(A) Except in the case of a social purpose corporation, must contain the word "corporation," "incorporated," "company," or "limited," or the abbreviation "Corp.," "Inc.," "Co.," or "Ltd.," or words or abbreviations of similar import in another language; or

(B) In the case of a social purpose corporation, must contain the words "social purpose corporation" or the abbreviation "SPC" or "S.P.C."; and

... Must not contain any of the following words or phrases: "Bank," "banking," "banker," "trust," "cooperative," or any combination of the words "industrial" and "loan," or any combination of any two or more of the words "building," "savings," "loan," "home," "association," and "society," or any other words or phrases prohibited by any statute of this state.

.. The name of a professional service corporation must contain either the words "professional service" or "professional corporation" or the abbreviation "P.S." or "P.C." The name may also contain either the words "corporation," "incorporated," "company," or "limited," or the abbreviation "Corp.," "Inc.," "Co.," or "Ltd." The name of a professional service corporation organized to render dental services must contain the full names or surnames of all shareholders and no other word than "chartered" or the words "professional services" or the abbreviation "P.S." or "P.C."

. The name of a nonprofit corporation:

.. May include "club," "league," "association," "services," "committee," "fund," "society," "foundation," "guild," ". . . . . ., a nonprofit corporation," ". . . . . ., a nonprofit mutual corporation," or any name of like import;

.. Except for nonprofit corporations formed prior to January 1, 1969, must not include or end with "incorporated," "company," "corporation," "partnership," "limited partnership," or "Ltd.," or any abbreviation thereof; and

.. May only include the term "public benefit" or names of like import if the nonprofit corporation has been designated as a public benefit nonprofit corporation by the secretary of state in accordance with chapter 24.03 RCW.

. The name of a limited partnership may contain the name of any partner. The name of a partnership that is not a limited liability limited partnership must contain the words "limited partnership" or the abbreviation "LP" or "L.P." and may not contain the words "limited liability limited partnership" or the abbreviation "LLLP" or "L.L.L.P." If the limited partnership is a limited liability limited partnership, the name must contain the words "limited liability limited partnership" or the abbreviation "LLLP" or "L.L.L.P." and may not contain the abbreviation "LP" or "L.P."

. The name of a limited liability partnership must contain the words "limited liability partnership" or the abbreviation "LLP" or "L.L.P." If the name of a foreign limited liability partnership contains the words "registered limited liability partnership" or the abbreviation "R.L.L.P." or "RLLP," it may include those words or abbreviations in its foreign registration statement.

. [Empty]
.. The name of a limited liability company:

... Must contain the words "limited liability company," the words "limited liability" and abbreviation "Co.," or the abbreviation "L.L.C." or "LLC"; and

... May not contain any of the following words or phrases: "Cooperative," "partnership," "corporation," "incorporated," or the abbreviations "Corp.," "Ltd.," or "Inc.," or "LP," "L.P.," "LLP," "L.L.P.," "LLLP," "L.L.L.P," or any words or phrases prohibited by any statute of this state.

.. The name of a professional limited liability company must contain either the words "professional limited liability company," or the words "professional limited liability" and the abbreviation "Co.," or the abbreviation "P.L.L.C." or "PLLC," provided that the name of a professional limited liability company organized to render dental services must contain the full names or surnames of all members and no other word than "chartered" or the words "professional services" or the abbreviation "P.L.L.C." or "PLLC."

. The name of a cooperative association organized under chapter 23.86 RCW may contain the words "corporation," "incorporated," or "limited," or the abbreviation "Corp.," "Inc.," or "Ltd."

. The name of a limited cooperative association must contain the phrase "limited cooperative association" or "limited cooperative" or the abbreviation "L.C.A." or "LCA." "Limited" may be abbreviated as "Ltd." "Cooperative" may be abbreviated as "Co-op." or "Coop." "Association" may be abbreviated as "Assoc." or "Assn."

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5002.SL.pdf?cite=2019%20c%2037%20§%201402[2019 c 37 § 1402]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201302[2015 c 176 § 1302]; ]

== 23.95.310 - Reservation of name.
. A person may reserve the exclusive use of an entity name including the alternate name adopted pursuant to RCW 23.95.525 by delivering an application to the secretary of state for filing. The application must state the name and address of the applicant and the name to be reserved. If the secretary of state finds that the entity name is available, the secretary of state shall reserve the name for the applicant's exclusive use for one hundred eighty days.

. The owner of a reserved entity name may transfer the reservation to another person that is not an individual by delivering to the secretary of state an executed notice in a record of the transfer which states the name and address of the transferee.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201303[2015 c 176 § 1303]; ]

== 23.95.315 - Registration of name.
. A foreign entity not registered to do business in this state under Article 5 of this chapter may register its name, or an alternate name adopted pursuant to RCW 23.95.525, if the name is distinguishable on the records of the secretary of state from the names that are not available under RCW 23.95.300.

. To register its name or an alternate name adopted pursuant to RCW 23.95.525, a foreign entity must deliver to the secretary of state for filing an application stating the entity's name, the jurisdiction and date of its formation, and any alternate name adopted pursuant to RCW 23.95.525. The application must be accompanied by a certificate of existence, or a document of similar import, from the entity's jurisdiction of formation. If the secretary of state finds that the name applied for is available, the secretary of state shall register the name for the applicant's exclusive use.

. The registration of a name under this section is effective upon the effective date of the application and until the close of the calendar year in which the application for registration is filed.

. A foreign entity whose name registration is effective may renew the registration for successive one-year periods by delivering, not earlier than three months before the expiration of the registration, to the secretary of state for filing a renewal application that complies with this section. When filed, the renewal application renews the registration for the following calendar year.

. A foreign entity whose name registration is effective may register as a foreign entity under the registered name or consent in an executed record to the use of that name by another entity.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201304[2015 c 176 § 1304]; ]

== 23.95.400 - Definitions.
The definitions in this section apply throughout this section and RCW 23.95.405 through 23.95.460 unless the context clearly requires otherwise.

. "Registered agent filing" means:

.. The public organic record of a domestic entity;

.. An application of a domestic limited liability partnership; or

.. A registration statement filed pursuant to RCW 23.95.510.

. [(2)] "Represented entity" means:

.. A domestic entity; or

.. A registered foreign entity.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201401[2015 c 176 § 1401]; ]

== 23.95.405 - Entities required to designate and maintain registered agent.
The following shall designate and maintain a registered agent in this state:

. A domestic entity; and

. A registered foreign entity.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201402[2015 c 176 § 1402]; ]

== 23.95.410 - Addresses in filing.
If a provision of this chapter other than RCW 23.95.445(1)(d) requires that a record state an address, the record must state:

. A street address in this state; and

. A mailing address in this state, if different from the address described in subsection (1) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201403[2015 c 176 § 1403]; ]

== 23.95.415 - Designation of registered agent.
. A registered agent filing must be executed by the represented entity and state:

.. The name of the entity's commercial registered agent; or

.. If the entity does not have a commercial registered agent:

... The name and address of the entity's noncommercial registered agent; or

... The title of an office or other position with the entity, if service of process, notices, and demands are to be sent to whichever individual is holding that office or position, and the address to which process, notices, or demands are to be sent.

. A registered agent shall not be appointed without having given prior consent in a record to the appointment. The consent shall be delivered to the secretary of state in such form as the secretary of state may prescribe. The consent shall be filed with or as a part of the record first appointing a registered agent. In the event any individual or entity has been appointed registered agent without consent, that individual or entity may deliver to the secretary of state a notarized statement attesting to that fact, and the name shall immediately be removed from the records of the secretary of state.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201404[2015 c 176 § 1404]; ]

== 23.95.420 - Listing of commercial registered agent.
. A person may become listed as a commercial registered agent by delivering to the secretary of state for filing a commercial-registered-agent listing statement executed by the person which states:

.. The name of the individual or the name of the entity, type of entity, and jurisdiction of formation of the entity;

.. That the person is in the business of serving as a commercial registered agent in this state; and

.. The address of a place of business of the person in this state to which service of process, notices, and demands being served on or sent to entities represented by the person may be delivered.

. A commercial-registered-agent listing statement may include the information regarding acceptance by the agent of service of process, notices, and demands in a form other than a tangible medium as provided in RCW 23.95.450(5).

. If the name of a person delivering to the secretary of state for filing a commercial-registered-agent listing statement is not distinguishable on the records of the secretary of state from the name of another commercial registered agent listed under this section, the person shall adopt a fictitious name that is distinguishable and use that name in its statement and when it does business in this state as a commercial registered agent.

. The secretary of state shall note the filing of a commercial-registered-agent listing statement in the records maintained by the secretary of state for each entity represented by the agent at the time of the filing. The statement has the effect of amending the registered agent filing for each of those entities to:

.. Designate the person becoming listed as a commercial registered agent as the commercial registered agent of each of those entities; and

.. Delete the name and address of the former agent from the registered agent filing of each of those entities.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2032[2020 c 57 § 32]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201405[2015 c 176 § 1405]; ]

== 23.95.425 - Termination of listing of commercial registered agent.
. A commercial registered agent may terminate its listing as a commercial registered agent by delivering to the secretary of state for filing a commercial-registered-agent termination statement executed by the agent which states:

.. The name of the agent as listed under RCW 23.95.420; and

.. That the agent is no longer in the business of serving as a commercial registered agent in this state.

. A commercial-registered-agent termination statement takes effect at 12:01 a.m. on the 31st day after the day on which it is delivered to the secretary of state for filing.

. The commercial registered agent promptly shall furnish each entity represented by the agent notice in a record of the filing of the commercial-registered-agent termination statement.

. When a commercial-registered-agent termination statement takes effect, the commercial registered agent ceases to be the registered agent for each entity formerly represented by it. Until an entity formerly represented by a terminated commercial registered agent designates a new registered agent, service of process may be made on the entity pursuant to RCW 23.95.450. Termination of the listing of a commercial registered agent under this section does not affect any contractual rights a represented entity has against the agent or that the agent has against the entity.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201406[2015 c 176 § 1406]; ]

== 23.95.430 - Change of registered agent by entity.
. A represented entity may change its registered agent or other information on file under RCW 23.95.415(1) by delivering to the secretary of state for filing a statement of change executed by the entity which states:

.. The name of the entity; and

.. The information required under RCW 23.95.415(1).

. The interest holders or governors of a domestic entity need not approve the filing of:

.. A statement of change under this section; or

.. A similar filing changing the registered agent or registered office, if any, of the entity in any other jurisdiction.

. A statement of change under this section designating a new registered agent must be accompanied by the new registered agent's consent in a record, either on the statement or attached to it in a manner and form as the secretary of state may prescribe, to the appointment.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201407[2015 c 176 § 1407]; ]

== 23.95.435 - Change of name, address, type of entity, or jurisdiction of formation by noncommercial registered agent.
. If a noncommercial registered agent changes its name or its address in effect with respect to a represented entity under RCW 23.95.415(1), the agent shall deliver to the secretary of state for filing, with respect to each entity represented by the agent, a statement of change executed by the agent which states:

.. The name of the entity;

.. The name and address of the agent in effect with respect to the entity;

.. If the name of the agent has changed, the new name; and

.. If the address of the agent has changed, the new address.

. A noncommercial registered agent promptly shall furnish the represented entity with notice in a record of the delivery to the secretary of state for filing of a statement of change and the changes made in the statement.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201408[2015 c 176 § 1408]; ]

== 23.95.440 - Change of name, address, type of entity, or jurisdiction of formation by commercial registered agent.
. If a commercial registered agent changes its name, its address as listed under RCW 23.95.420(1), its type of entity, or its jurisdiction of formation, the agent shall deliver to the secretary of state for filing a statement of change executed by the agent which states:

.. The name of the agent as listed under RCW 23.95.420(1);

.. If the name of the agent has changed, the new name;

.. If the address of the agent has changed, the new address; and

.. If the agent is an entity:

... If the type of entity of the agent has changed, the new type of entity; and

... If the jurisdiction of formation of the agent has changed, the new jurisdiction of formation.

. The filing by the secretary of state of a statement of change under subsection (1) of this section is effective to change the information regarding the agent with respect to each entity represented by the agent.

. A commercial registered agent promptly shall furnish to each entity represented by it a notice in a record of the filing by the secretary of state of a statement of change relating to the name or address of the agent and the changes made in the statement.

. If a commercial registered agent changes its address without delivering for filing a statement of change as required by this section, the secretary of state may cancel the listing of the agent under RCW 23.95.420. A cancellation under this subsection has the same effect as a termination under RCW 23.95.425. Promptly after canceling the listing of an agent, the secretary of state shall serve notice in a record in the manner provided in RCW 23.95.450 (2) or (3) on:

.. Each entity represented by the agent, stating that the agent has ceased to be the registered agent for the entity and that, until the entity designates a new registered agent, service of process may be made on the entity as provided in RCW 23.95.450; and

.. The agent, stating that the listing of the agent has been canceled under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201409[2015 c 176 § 1409]; ]

== 23.95.445 - Resignation of registered agent.
. A registered agent may resign as agent for a represented entity by delivering to the secretary of state for filing a statement of resignation executed by the agent which states:

.. The name of the entity;

.. The name of the agent;

.. That the agent resigns from serving as registered agent for the entity; and

.. The address of the entity to which the agent will send the notice required by subsection (3) of this section.

. A statement of resignation takes effect on the earlier of:

.. The 31st day after the day on which it is filed by the secretary of state; or

.. The designation of a new registered agent for the represented entity.

. A registered agent promptly shall furnish to the represented entity notice in a record of the date on which a statement of resignation was filed.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201410[2015 c 176 § 1410]; ]

== 23.95.450 - Service of process, notice, or demand on entity.
. A represented entity may be served with any process, notice, or demand required or permitted by law by serving its registered agent.

. If a represented entity ceases to have a registered agent, or if its registered agent cannot with reasonable diligence be served, the entity may be served by registered or certified mail, return receipt requested, or by similar commercial delivery service, addressed to the entity at the entity's principal office. The address of the principal office must be as shown in the entity's most recent annual report filed by the secretary of state. Service is effected under this subsection on the earliest of:

.. The date the entity receives the mail or delivery by the commercial delivery service;

.. The date shown on the return receipt, if executed by the entity; or

.. Five days after its deposit with the United States postal service or commercial delivery service, if correctly addressed and with sufficient postage or payment.

. If process, notice, or demand cannot be served on an entity pursuant to subsection (1) or (2) of this section, service may be made by handing a copy to the individual in charge of any regular place of business or activity of the entity if the individual served is not a plaintiff in the action.

. The secretary of state shall be an agent of the entity for service of process if process, notice, or demand cannot be served on an entity pursuant to subsection (1), (2), or (3) of this section.

. Service of process, notice, or demand on a registered agent must be in a tangible medium, but service may be made on a commercial registered agent in other forms, and subject to such requirements, as the agent has stated in its listing under RCW 23.95.420 that it will accept.

. Service of process, notice, or demand may be made by other means under law other than this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2033[2020 c 57 § 33]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201411[2015 c 176 § 1411]; ]

== 23.95.455 - Duties of registered agent.
The only duties under this chapter of a registered agent that has complied with this chapter are:

. To forward to the represented entity at the address most recently supplied to the agent by the entity any process, notice, or demand pertaining to the entity which is served on or received by the agent;

. To provide the notices required by this chapter to the entity at the address most recently supplied to the agent by the entity;

. If the agent is a noncommercial registered agent, to keep current the information required by RCW 23.95.415(1) in the most recent registered agent filing for the entity; and

. If the agent is a commercial registered agent, to keep current the information listed for it under RCW 23.95.420(1).

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201412[2015 c 176 § 1412]; ]

== 23.95.460 - Jurisdiction and venue.
The designation or maintenance in this state of a registered agent does not by itself create the basis for personal jurisdiction over the represented entity in this state. The address of the agent does not determine venue in an action or a proceeding involving the entity.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201413[2015 c 176 § 1413]; ]

== 23.95.500 - Governing law.
. This chapter does not authorize this state to regulate the organization or internal affairs of a foreign entity registered to do business in this state, or govern the liability that a person has as an interest holder or governor for a debt, obligation, or other liability of the foreign entity.

. A foreign entity is not precluded from registering to do business in this state because of any difference between the law of the entity's jurisdiction of formation and the law of this state.

. Registration of a foreign entity to do business in this state does not authorize the foreign entity to engage in any activity or exercise any power that a domestic entity of the same type may not engage in or exercise in this state. Except as otherwise provided in this chapter or other applicable law of this state, a foreign entity is subject to the same duties, restrictions, penalties, and liabilities now or later imposed on a domestic entity of the same type.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201501[2015 c 176 § 1501]; ]

== 23.95.505 - Registration to do business in this state.
. A foreign entity may not do business in this state until it registers with the secretary of state under this chapter.

. A foreign entity doing business in this state may not maintain an action or proceeding in this state unless it is registered to do business in this state and has paid to this state all fees and penalties for the years, or parts thereof, during which it did business in this state without having registered.

. The successor to a foreign entity that transacted business in this state without a certificate of registration and the assignee of a cause of action arising out of that business may not maintain a proceeding based on that cause of action in any court in this state until the foreign entity, or its successor, obtains a certificate of registration.

. A court may stay a proceeding commenced by a foreign entity, its successor, or assignee until it determines whether the foreign entity, or its successor, requires a certificate of registration. If it so determines, the court may further stay the proceeding until the foreign entity, or its successor, obtains the certificate of registration.

. A foreign entity that transacts business in this state without a certificate of registration is liable to this state, for the years or parts thereof during which it transacted business in this state without a certificate of registration, in an amount equal to all fees which would have been imposed by this chapter upon the entity had it applied for and received a certificate of registration to transact business in this state and thereafter filed all reports required by this chapter, plus all penalties imposed by this chapter for failure to pay such fees.

. The failure of a foreign entity to register to do business in this state does not: (a) Impair the validity of a contract or act of the foreign entity; (b) impair the right of any other party to the contract to maintain any action, suit, or proceeding on the contract; or (c) preclude the foreign entity from defending an action or proceeding in this state.

. A limitation on the liability of an interest holder or governor of a foreign entity is not waived solely because the foreign entity does business in this state without registering.

. RCW 23.95.500 (1) and (2) applies even if a foreign entity fails to register under this Article 5.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201502[2015 c 176 § 1502]; ]

== 23.95.510 - Foreign registration statement.
. To register to do business in this state, a foreign entity must deliver a foreign registration statement to the secretary of state for filing. The statement must be executed by the entity and state:

.. The name of the foreign entity and, if the name does not comply with RCW 23.95.300, an alternate name adopted pursuant to RCW 23.95.525;

.. The type of entity and, if it is a foreign limited partnership, whether it is a foreign limited liability limited partnership;

.. The entity's jurisdiction of formation;

.. The street and mailing addresses of the entity's principal office and, if the law of the entity's jurisdiction of formation requires the entity to maintain an office in that jurisdiction, the street and mailing addresses of the office;

.. The information required by RCW 23.95.415(1);

.. The names and addresses of the entity's governors and, if the entity is a business corporation or nonprofit corporation, the names and addresses of its officers;

.. The date of the entity's formation and period of duration;

.. The nature of the entity's business or purposes to be conducted or promoted in this state; and

.. The date on which the entity first did, or intends to do, business in this state.

. The foreign entity shall deliver with the registration statement a certificate of existence, or a document of similar import, issued no more than sixty days before the date of submission of the registration statement and duly authenticated by the secretary of state or other official having custody of the entity's records in the entity's jurisdiction of formation.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201503[2015 c 176 § 1503]; ]

== 23.95.515 - Amendment of foreign registration statement.
A registered foreign entity shall promptly deliver to the secretary of state for filing an amendment to its foreign registration statement if there is a change in:

. The name of the entity;

. The type of entity, including, if it is a foreign limited partnership, whether the entity became or ceased to be a foreign limited liability limited partnership;

. The entity's jurisdiction of formation;

. An address required by RCW 23.95.510(1)(d); or

. The information required by RCW 23.95.415(1).

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201504[2015 c 176 § 1504]; ]

== 23.95.520 - Activities not constituting doing business.
. Activities of a foreign entity that do not constitute doing business in this state under this chapter include, but are not limited to:

.. Maintaining, defending, mediating, arbitrating, or settling an action or proceeding, or settling claims or disputes;

.. Carrying on any activity concerning its internal affairs, including holding meetings of its interest holders or governors;

.. Maintaining accounts in financial institutions;

.. Maintaining offices or agencies for the transfer, exchange, and registration of securities of the entity or maintaining trustees or depositories with respect to those securities;

.. Selling through independent contractors;

.. Soliciting or obtaining orders by any means if the orders require acceptance outside this state before they become binding contracts and where the contracts do not involve any local performance other than delivery and installation;

.. Creating or acquiring indebtedness, mortgages, or security interests in property;

.. Securing or collecting debts or enforcing mortgages or security interests in property securing the debts;

.. Conducting an isolated transaction that is completed within thirty days and that is not in the course of repeated transactions of a like nature;

.. Owning, without more, property;

.. Doing business in interstate commerce; and

.. Operating an approved branch campus of a foreign degree-granting institution in compliance with chapter 28B.90 RCW and in accordance with subsection (2) of this section.

. In addition to those acts that are specified in subsection (1) of this section, a foreign degree-granting institution that establishes an approved branch campus in the state under chapter 28B.90 RCW shall not be deemed to transact business in the state solely because it:

.. Owns and controls an incorporated branch campus in this state;

.. Pays the expenses of tuition or room and board charged by the incorporated branch campus for its students enrolled at the branch campus or contributes to the capital thereof; or

.. Provides personnel who furnish assistance and counsel to its students while in the state but who have no authority to enter into any transactions for or on behalf of the foreign degree-granting institution.

. A person does not do business in this state solely by being an interest holder or governor of a domestic entity or foreign entity that does business in this state.

. This section does not apply in determining the contacts or activities that may subject a foreign entity to service of process, taxation, or regulation under law of this state other than this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201505[2015 c 176 § 1505]; ]

== 23.95.525 - Noncomplying name of foreign entity.
. A foreign entity whose name does not comply with RCW 23.95.300 for an entity of its type may not register to do business in this state until it adopts, for the purpose of doing business in this state, an alternate name that complies with RCW 23.95.300. A registered foreign entity that registers under an alternate name under this subsection need not comply with chapter 19.80 RCW. After registering to do business in this state with an alternate name, a registered foreign entity shall do business in this state under:

.. The alternate name;

.. Its entity name, with the addition of its jurisdiction of formation clearly identified; or

.. An assumed or fictitious name the entity is authorized to use under chapter 19.80 RCW.

. If a registered foreign entity changes its name to one that does not comply with RCW 23.95.300, it may not do business in this state until it complies with subsection (1) of this section by amending its foreign registration statement to adopt an alternate name that complies with RCW 23.95.300.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201506[2015 c 176 § 1506]; ]

== 23.95.530 - Withdrawal of registration of registered foreign entity.
. A registered foreign entity may withdraw its registration by delivering a statement of withdrawal to the secretary of state for filing. The statement of withdrawal must be executed by the entity and state:

.. The name of the entity and its jurisdiction of formation;

.. That the entity is not doing business in this state and that it withdraws its registration to do business in this state;

.. That the entity revokes the authority of its registered agent to accept service on its behalf in this state; and

.. An address to which service of process may be made under subsection (3) of this section.

. For foreign corporations, the statement of withdrawal must be accompanied by a copy of a revenue clearance certificate issued pursuant to RCW 82.32.260.

. After the withdrawal of the registration of an entity, service of process in any action or proceeding based on a cause of action arising during the time the entity was registered to do business in this state may be made pursuant to RCW 23.95.450.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5040.SL.pdf?cite=2017%20c%2031%20§%203[2017 c 31 § 3]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201507[2015 c 176 § 1507]; ]

== 23.95.535 - Withdrawal deemed on conversion to domestic entity.
A registered foreign entity that converts to any type of domestic entity is deemed to have withdrawn its registration on the effective date of the conversion.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201508[2015 c 176 § 1508]; ]

== 23.95.540 - Withdrawal on dissolution or conversion.
. A registered foreign entity that has dissolved and completed winding up or has converted to a domestic or foreign person not subject to this chapter shall deliver a statement of withdrawal to the secretary of state for filing. The statement must be executed by the dissolved or converted entity and state:

.. In the case of a foreign entity that has completed winding up:

... Its name and jurisdiction of formation; and

... That the foreign entity surrenders its registration to do business in this state; and

.. In the case of a foreign entity that has converted to a domestic or foreign person not subject to chapter 176, Laws of 2015:

... The name of the converting foreign entity and its jurisdiction of formation;

... The type of person to which it has converted and its jurisdiction of formation;

... That it surrenders its registration to do business in this state and revokes the authority of its registered agent to accept service on its behalf; and

... A mailing address to which service of process may be made under subsection (2) of this section.

. After a withdrawal is effective under this section, service of process in any action or proceeding based on a cause of action arising during the time the foreign entity was registered to do business in this state may be made pursuant to RCW 23.95.450.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201509[2015 c 176 § 1509]; ]

== 23.95.545 - Transfer of registration.
. If a registered foreign entity merges into a nonregistered foreign entity or converts to a foreign entity required to register with the secretary of state to do business in this state, the foreign entity shall deliver to the secretary of state for filing an application for transfer of registration. The application must be executed by the surviving or converted entity and state:

.. The name of the registered foreign entity before the merger or conversion;

.. The type of entity it was before the merger or conversion;

.. The name of the applicant entity and, if the name does not comply with RCW 23.95.300, an alternate name adopted pursuant to RCW 23.95.525(1);

.. The type of entity of the applicant entity and its jurisdiction of formation; and

.. The following information regarding the applicant entity, if different than the information for the foreign entity before the merger or conversion:

... The street and mailing addresses of the principal office of the entity and, if the law of the entity's jurisdiction of formation requires it to maintain an office in that jurisdiction, the street and mailing addresses of that office; and

... The information required pursuant to RCW 23.95.415(1).

. When an application for transfer of registration takes effect, the registration of the registered foreign entity to do business in this state is transferred without interruption to the entity into which it has merged or to which it has been converted.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201510[2015 c 176 § 1510]; ]

== 23.95.550 - Termination of registration.
. The secretary of state may terminate the registration of a registered foreign entity in the manner provided in subsections (2) and (3) of this section if:

.. The entity does not pay any fee, interest, or penalty required to be paid to the secretary of state under this chapter or law of this state other than this chapter;

.. The entity does not deliver to the secretary of state for filing an annual report when it is due;

.. The entity does not have a registered agent as required by RCW 23.95.405;

.. The entity does not deliver to the secretary of state for filing a statement of change under RCW 23.95.430 if change occurs in the name or address of the entity's registered agent;

.. A governor, officer, or agent of the entity executed a document knowing it was false in any material respect with intent that the document be delivered to the secretary of state for filing; or

.. The secretary of state receives a duly authenticated certificate from the secretary of state or other official having custody of the entity's records in the entity's jurisdiction of formation stating that it has been dissolved or disappeared as the result of a merger.

. If the secretary of state determines that one or more grounds for termination exist under subsection (1) of this section, the secretary of state shall deliver a notice of the determination to the registered foreign entity's registered agent or, if the entity does not have a registered agent, to the entity's principal office. The notice must state the grounds for termination under subsection (1) of this section.

. If the entity does not cure each ground for termination stated in the notice within sixty days after the notice is effective, the secretary of state shall terminate the registration of the foreign entity by filing a statement of termination that recites the ground or grounds for termination and the effective date of termination and delivering a copy of the statement of termination to the foreign entity.

. The authority of a registered foreign entity to do business in this state ceases on the effective date of termination shown on the statement of termination.

. The termination of a foreign entity's registration does not terminate the authority of the registered agent of the foreign entity.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201511[2015 c 176 § 1511]; ]

== 23.95.555 - Action by attorney general.
The attorney general may maintain an action to enjoin a foreign entity from doing business in this state in violation of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201512[2015 c 176 § 1512]; ]

== 23.95.600 - Domestic entity—Definition.
For the purposes of this Article 6, the term "domestic entity" does not include a domestic limited liability partnership.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201601[2015 c 176 § 1601]; ]

== 23.95.605 - Grounds.
The secretary of state may commence a proceeding under RCW 23.95.610 to dissolve a domestic entity administratively if:

. The entity does not pay any fee, interest, or penalty required to be paid to the secretary of state when due;

. The entity does not deliver an annual report to the secretary of state not later than one hundred twenty days after it is due;

. The entity does not have a registered agent in this state for thirty consecutive days; or

. The entity's period of duration stated in its public organic record expired.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201602[2015 c 176 § 1602]; ]

== 23.95.610 - Procedure and effect.
. If the secretary of state determines that one or more grounds exist under RCW 23.95.605 for administratively dissolving a domestic entity, the secretary of state shall serve the entity pursuant to RCW 23.95.250 with notice in a record of the secretary of state's determination.

. If a domestic entity, not later than sixty days after service of the notice required by subsection (1) of this section, does not cure or demonstrate to the satisfaction of the secretary of state the nonexistence of each ground determined by the secretary of state, the secretary of state shall administratively dissolve the entity by executing a statement of administrative dissolution that recites the grounds for dissolution and the effective date of dissolution. The secretary of state shall file the statement and serve a copy on the entity pursuant to RCW 23.95.250.

. A domestic entity that is dissolved administratively continues its existence as an entity but may not carry on any activities except as necessary to wind up its activities and affairs and liquidate its assets in the manner provided in its organic law or to apply for reinstatement under RCW 23.95.615.

. The administrative dissolution of a domestic entity does not terminate the authority of its registered agent.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201603[2015 c 176 § 1603]; ]

== 23.95.615 - Reinstatement.
. A domestic entity that is dissolved administratively under RCW 23.95.610 may apply to the secretary of state for reinstatement not later than five years after the effective date of dissolution. The application must be executed by the entity and state:

.. The name of the entity and a statement that the name satisfies RCW 23.95.300; if the name does not satisfy RCW 23.95.300, the entity must deliver with its application an amendment to its public organic record changing its name;

.. The address of the principal office of the entity and the name and address of its registered agent;

.. The effective date of the entity's administrative dissolution; and

.. That the grounds for dissolution did not exist or have been cured.

. To be reinstated, an entity must pay the full amount of all annual license or renewal fees which would have been assessed during the period of administrative dissolution had the entity been in active status, plus a penalty fee established by the secretary of state by rule, and the license or renewal fee for the year of reinstatement.

. If the secretary of state determines that an application under subsection (1) of this section contains the information required by subsection (1) of this section, is satisfied that the information is correct, and determines that all payments required to be made to the secretary of state by subsection (2) of this section have been made, the secretary of state shall:

.. Cancel the statement of administrative dissolution and prepare a statement of reinstatement that states the secretary of state's determination and the effective date of reinstatement;

.. File the statement; and

.. Serve a copy of the statement on the entity.

. When reinstatement under this section is effective as provided in RCW 23.95.210:

.. It relates back to and takes effect as of the effective date of the administrative dissolution; and

.. The domestic entity resumes carrying on its activities and affairs as if the administrative dissolution had never occurred, except for the rights of a person arising out of an act or omission in reliance on the dissolution before the person knew or had reason to know of the reinstatement.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201604[2015 c 176 § 1604]; ]

== 23.95.620 - Judicial review of denial of reinstatement.
. If the secretary of state denies a domestic entity's application for reinstatement following administrative dissolution, the secretary of state shall serve the entity with a notice in a record that explains the reasons for denial.

. An entity may seek judicial review of denial of reinstatement in the superior court not later than thirty days after service of the notice of denial.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201605[2015 c 176 § 1605]; ]

== 23.95.625 - Entity name not distinguishable from name of governmental entity.
. Any county, city, town, district, or other political subdivision of the state, or the state of Washington or any department or agency of the state, may apply to the secretary of state for the administrative dissolution, or the termination of registration, of any entity using a name that is not distinguishable from the name of the applicant for dissolution. The application must state the precise legal name of the governmental entity and its date of formation and the applicant shall mail a copy to the entity's registered agent. If the name of the entity is not distinguishable from the name of the applicant, then, except as provided in subsection (4) of this section, the secretary of state shall commence proceedings for administrative dissolution under RCW 23.95.610 or termination of registration under RCW 23.95.550.

. A name may not be considered distinguishable by virtue of the items specified in RCW 23.95.300(3).

. [Empty]
.. The following are not distinguishable for purposes of this section:

... "City of Anytown" and "City of Anytown, Inc."; and

... "City of Anytown" and "Anytown City."

.. The following are distinguishable for purposes of this section:

... "City of Anytown" and "Anytown, Inc.";

... "City of Anytown" and "The Anytown Company"; and

... "City of Anytown" and "Anytown Cafe, Inc."

. If the entity that is the subject of the application was formed or registered before the formation of the applicant as a governmental entity, then this section applies only if the applicant for dissolution provides a certified copy of a final judgment of a court of competent jurisdiction determining that the applicant holds a superior property right to the name than does the entity.

. The duties of the secretary of state under this section are ministerial.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201606[2015 c 176 § 1606]; ]

== 23.95.700 - Reservation of power to amend or repeal.
The legislature has power to amend or repeal all or part of this chapter at any time, and all domestic and foreign entities subject to this chapter are governed by the amendment or repeal.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201701[2015 c 176 § 1701]; ]

== 23.95.705 - Supplemental principles of law.
Unless displaced by particular provisions of this chapter, the principles of law and equity supplement this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201702[2015 c 176 § 1702]; ]

== 23.95.710 - Relation to electronic signatures in global and national commerce act.
This chapter modifies, limits, and supersedes the electronic signatures in global and national commerce act, 15 U.S.C. Sec. 7001 et seq., but does not modify, limit, or supersede Sec. 101(c) of that act, 15 U.S.C. Sec. 7001(c), or authorize electronic delivery of any of the notices described in section 103(b) of that act, 15 U.S.C. Sec. 7003(b).

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201703[2015 c 176 § 1703]; ]

== 23.95.715 - Savings.
The repeal of a statute by chapter 176, Laws of 2015 does not affect:

. The operation of the statute or any action taken under it before its repeal;

. Any ratification, right, remedy, privilege, obligation, or liability acquired, accrued, or incurred under the statute before its repeal;

. Any violation of the statute or any penalty, forfeiture, or punishment incurred because of the violation before its repeal; or

. Any proceeding, reorganization, or dissolution commenced under the statute before its repeal, and the proceeding, reorganization, or dissolution may be completed in accordance with the statute as if it had not been repealed.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%201704[2015 c 176 § 1704]; ]

