= 23.86 - Cooperative associations.
:toc:

== 23.86.007 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Association" means any corporation subject to this chapter.

. "Member" or "members" includes a member or members of an association subject to this chapter without capital stock and a shareholder or shareholders of voting common stock in an association subject to this chapter with capital stock.

. "Articles of incorporation" means the original or restated articles of incorporation, articles of consolidation, or articles of association and all amendments including articles of merger. Corporations incorporated under this chapter with articles of association shall not be required to amend the title or references to the term "articles of association."

. "Director," "directors," or "board of directors" includes "trustee," "trustees," or "board of trustees" respectively. Corporations incorporated under this chapter with references in their articles of association or bylaws to "trustee," "trustees," or "board of trustees" shall not be required to amend the references.

. "Agricultural association" means an association that engages in any activity in connection with the marketing or selling of the agricultural products of its members, or with the harvesting, preserving, drying, processing, canning, packing, storing, handling, shipping, or utilization thereof, or the manufacturing or marketing of the by-products thereof; or in connection with the manufacturing, selling, or supplying to its members of machinery, equipment, or supplies, or in the financing of these activities. In the application of the definition of agricultural association, "agricultural products" includes horticultural, viticultural, forestry, dairy, livestock, poultry, bee, and farm products.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6492-S.SL.pdf?cite=1994%20c%20206%20§%201[1994 c 206 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c307.pdf?cite=1989%20c%20307%20§%203[1989 c 307 § 3]; ]

== 23.86.010 - Cooperative associations—Who may organize.
Any number of persons may associate themselves together as a cooperative association, society, company or exchange, with or without capital stock, for the transaction of any lawful business on the cooperative plan. For the purposes of this chapter the words "association," "company," "exchange," "society" or "union" shall be construed the same.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c307.pdf?cite=1989%20c%20307%20§%204[1989 c 307 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c19.pdf?cite=1913%20c%2019%20§%201[1913 c 19 § 1]; RRS § 3904; ]

== 23.86.020 - Business authorized.
An association created under this chapter, being for mutual welfare, the words "lawful business" shall extend to every kind of lawful effort for business, agricultural, dairy, mercantile, mining, manufacturing or mechanical business, on the cooperative plan.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c19.pdf?cite=1913%20c%2019%20§%207[1913 c 19 § 7]; RRS § 3910; ]

== 23.86.022 - Certificate of authority as insurance company—Filing of documents.
For those corporations that have a certificate of authority, are applying for, or intend to apply for a certificate of authority from the insurance commissioner as an insurance company under chapter 48.05 RCW, whenever under this chapter corporate documents are required to be filed with the secretary of state, the documents shall be filed with the insurance commissioner rather than the secretary of state.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1065-S2.SL.pdf?cite=1998%20c%2023%20§%204[1998 c 23 § 4]; ]

== 23.86.030 - Association name—Immunity from liability of association board members and officers.
. The name of any association subject to this chapter must comply with Article 3 of chapter 23.95 RCW.

. No corporation or association organized or doing business in this state shall be entitled to use the term "cooperative" as a part of its corporate or other business name or title, unless it: (a) Is subject to the provisions of this chapter or chapter 23.78, 23.100, or 31.12 RCW; (b) is subject to the provisions of chapter 24.06 RCW and operating on a cooperative basis; (c) is, on July 23, 1989, an organization lawfully using the term "cooperative" as part of its corporate or other business name or title; or (d) is a nonprofit corporation or association the voting members of which are corporations or associations operating on a cooperative basis. Any corporation or association violating the provisions of this section may be enjoined from doing business under such name at the instance of any member or any association subject to this chapter.

. A member of the board of directors or an officer of any association subject to this chapter shall have the same immunity from liability as is granted in RCW 4.24.264.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5002.SL.pdf?cite=2019%20c%2037%20§%201403[2019 c 37 § 1403]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%209103[2015 c 176 § 9103]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c307.pdf?cite=1989%20c%20307%20§%205[1989 c 307 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c212.pdf?cite=1987%20c%20212%20§%20706[1987 c 212 § 706]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c19.pdf?cite=1913%20c%2019%20§%2017[1913 c 19 § 17]; RRS § 3920; ]

== 23.86.035 - Powers.
Each association subject to this chapter shall have the following powers:

. To have perpetual succession by its corporate name unless a limited period of duration is stated in the articles of incorporation.

. To sue and be sued, complain, and defend in its corporate name.

. To have and use a corporate seal.

. To purchase, take, receive, lease, or otherwise acquire, own, hold, improve, use, and deal in and with real or personal property or any interest therein, wherever situated.

. To sell, convey, mortgage, pledge, lease, exchange, transfer, or otherwise dispose of all or any part of its property and assets.

. To purchase, take, receive, subscribe for, or otherwise acquire, own, hold, vote, use, employ, sell, mortgage, lend, pledge, or otherwise dispose of, use, and deal in and with shares or other interest in, or obligations of, other domestic or foreign corporations, associations, partnerships or individuals, or direct or indirect obligations of the United States or any other government, state, territory, governmental district or municipality, or any instrumentality thereof.

. To make contracts and incur liabilities, borrow money at rates of interest the association may determine, issue notes, bonds, certificates of indebtedness, and other obligations, receive funds from members and pay interest thereon, issue capital stock and certificates representing equity interests in assets, allocate earnings and losses at the times and in the manner the articles of incorporation or bylaws or other contract specify, create book credits, capital funds, and reserves, and secure obligations by mortgage or pledge of any of its property, franchises, and income.

. To lend money for corporate purposes, invest and reinvest funds, and take and hold real and personal property as security for the payment of funds loaned or invested.

. To conduct business, carry on operations, have offices, and exercise the powers granted by this chapter, within or without this state.

. To elect or appoint officers and agents of the corporation, define their duties, and fix their compensation.

. To make and alter bylaws, not inconsistent with its articles of incorporation or with the laws of this state, for the administration and regulation of the affairs of the association.

. To make donations for the public welfare or for charitable, scientific, or educational purposes, and in time of war to make donations in aid of war activities.

. To pay pensions and establish pension plans, pension trusts, profit-sharing plans, stock bonus plans, stock option plans, and other incentive plans for any or all of its directors, officers, and employees.

. To be a partner, member, associate, or manager of any partnership, joint venture, trust, or other enterprise.

. To cease corporate activities and surrender its corporate franchise.

. To have and exercise all powers necessary or convenient to effect its purposes.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c307.pdf?cite=1989%20c%20307%20§%206[1989 c 307 § 6]; ]

== 23.86.050 - Articles—Contents.
Every association formed under this chapter after July 23, 1989, shall prepare articles of incorporation in writing, which shall set forth:

. The name of the association.

. The purpose for which it was formed which may include the transaction of any lawful business for which associations may be incorporated under this chapter. It shall not be necessary to set forth in the articles of incorporation any of the corporate powers enumerated in this chapter.

. Its principal place of business.

. The term for which it is to exist which may be perpetual or for a stated number of years.

. If organized without capital stock, whether the property rights and interest of each member shall be equal or unequal; and if unequal, the articles shall set forth the general rules by which the property rights and interests of all members shall be determined and fixed. The association may admit new members who shall be entitled to share in the property of the association with old members in accordance with the general rules.

. If the association is to have capital stock:

.. The aggregate number of shares which the association shall have authority to issue; if shares are to consist of one class only, the par value of each share, or a statement that all shares are without par value; or, if shares are to be divided into classes, the number of shares of each class, and a statement of the par value of the shares of each class or that shares are to be without par value;

.. If the shares are to be divided into classes, the designation of each class and a statement of the preferences, limitations, and relative rights in respect to the shares of each class;

.. If the association is to issue the shares of any preferred or special class in series, the designation of each series and a statement of the variations in the relative rights and preferences between series fixed in the articles of incorporation, and a statement of any authority vested in the board of directors to establish series and fix and determine the variations in the relative rights and preferences between series; and

.. Any provision limiting or denying to members the preemptive right to acquire additional shares of the association.

. Provisions for distribution of assets on dissolution or final liquidation.

. Whether a dissenting member shall be limited to a return of less than the fair value of the member's equity interest in the association. A dissenting member may not be limited to a return of less than the consideration paid to or retained by the association for the equity interest unless the fair value is less than the consideration paid to or retained by the association.

. The address of its initial registered office, including street and number, and the name of its initial registered agent at the address.

. The number of directors constituting the initial board of directors and the names and addresses of the persons who are to serve as the initial directors.

. The name and address of each incorporator.

. Any provision, not inconsistent with law, which the incorporators elect to set forth in the articles of incorporation for the regulation of the internal affairs of the association, including provisions regarding:

.. Eliminating or limiting the personal liability of a director to the association or its members for monetary damages for conduct as a director: PROVIDED, That such provision shall not eliminate or limit the liability of a director for acts or omissions that involve intentional misconduct by a director or a knowing violation of law by a director, or for any transaction from which the director will personally receive a benefit in money, property, or services to which the director is not legally entitled. No such provision may eliminate or limit the liability of a director for any act or omission occurring before the date when such provision becomes effective; and

.. Any provision which under this chapter is required or permitted to be set forth in the bylaws.

Associations organized under this chapter before July 23, 1989, or under *chapter 24.32 RCW shall not be required to amend their articles of association or articles of incorporation to conform to this section unless the association is otherwise amending the articles of association or articles of incorporation.

The information specified in subsections (9) through (11) of this section may be deleted when filing amendments.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c307.pdf?cite=1989%20c%20307%20§%207[1989 c 307 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c212.pdf?cite=1987%20c%20212%20§%20704[1987 c 212 § 704]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%20171[1982 c 35 § 171]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c34.pdf?cite=1961%20c%2034%20§%201[1961 c 34 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c19.pdf?cite=1913%20c%2019%20§%202[1913 c 19 § 2]; RRS § 3905; ]

== 23.86.055 - Articles—Filing.
. The articles of incorporation shall be signed by the incorporators and delivered to the secretary of state for filing in accordance with Article 2 of chapter 23.95 RCW.

. Upon the filing of the articles of incorporation, the corporate existence shall begin, and the certificate of incorporation shall, except as against the state in a proceeding to cancel or revoke the certificate of incorporation, be conclusive evidence that all conditions precedent required to be performed by the incorporators have been complied with and that the corporation has been incorporated under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%209104[2015 c 176 § 9104]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c307.pdf?cite=1989%20c%20307%20§%208[1989 c 307 § 8]; ]

== 23.86.070 - Applicable fees, charges, and penalties.
Associations organized under or subject to this chapter are subject to the applicable fees, charges, and penalties established by the secretary of state under RCW 23.95.260 and 43.07.120.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%209105[2015 c 176 § 9105]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2576-S2.SL.pdf?cite=2010%201st%20sp.s.%20c%2029%20§%2010[2010 1st sp.s. c 29 § 10]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5492-S.SL.pdf?cite=1993%20c%20269%20§%201[1993 c 269 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=1991%20c%2072%20§%2015[1991 c 72 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c307.pdf?cite=1989%20c%20307%20§%209[1989 c 307 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%20173[1982 c 35 § 173]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c263.pdf?cite=1959%20c%20263%20§%202[1959 c 263 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c214.pdf?cite=1953%20c%20214%20§%201[1953 c 214 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c99.pdf?cite=1925%20ex.s.%20c%2099%20§%201[1925 ex.s. c 99 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c19.pdf?cite=1913%20c%2019%20§%204[1913 c 19 § 4]; RRS § 3907; ]

== 23.86.075 - Fees for services by secretary of state.
See RCW 43.07.120.

[ ]

== 23.86.080 - Directors—Election and appointment.
. Associations shall be managed by a board of not less than three directors (which may be referred to as "trustees"). The directors shall be elected by the members of the association at such time, in such manner, and for such term of office as the bylaws may prescribe, and shall hold office during the term for which they were elected and until their successors are elected and qualified.

. Except as provided in RCW 23.86.087, any vacancy occurring in the board of directors, and any directorship to be filled by reason of an increase in the number of directors, may be filled by the board of directors unless the articles of incorporation or the bylaws provide that a vacancy or directorship so created shall be filled in some other manner. A director elected or appointed to fill a vacancy shall be elected or appointed for the unexpired term of the predecessor in office.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5726.SL.pdf?cite=2003%20c%20252%20§%201[2003 c 252 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c307.pdf?cite=1989%20c%20307%20§%2010[1989 c 307 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c19.pdf?cite=1913%20c%2019%20§%205[1913 c 19 § 5]; RRS § 3908; ]

== 23.86.085 - Election of officers.
The directors shall elect a president and one or more vice presidents, who need not be directors. If the president and vice presidents are not members of the board of directors, the directors shall elect from their number a chair of the board of directors and one or more vice chairs. They shall also elect a secretary and treasurer, who need not be directors, and they may combine the two offices and designate the combined office as secretary-treasurer. The treasurer may be a bank or any depository, and as such shall not be considered an officer but a function of the board of directors. In such case, the secretary shall perform the usual accounting duties of the treasurer, except that the funds shall be deposited only as authorized by the board of directors.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20654[2011 c 336 § 654]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c307.pdf?cite=1989%20c%20307%20§%2011[1989 c 307 § 11]; ]

== 23.86.087 - Removal of officers or directors.
Any member may bring charges against an officer or director by filing charges in writing with the secretary of the association, together with a petition signed by ten percent of the members requesting the removal of the officer or director in question. The removal shall be voted upon at the next regular or special meeting of the association and, by a vote of a majority of the members voting, the association may remove the officer or director and fill the vacancy. The director or officer against whom such charges have been brought shall be informed in writing of the charges prior to the meeting and shall have an opportunity at the meeting to be heard in person or by counsel and to present witnesses. The person or persons bringing the charges shall have the same opportunity. If the bylaws provide for election of directors by districts, the petition for removal of a director must be signed by the number of members residing in the district from which the officer or director was elected as the articles of incorporation or bylaws specify and, in the absence of such specification, the petition must be signed by ten percent of the members residing in the district. The board of directors must call a special meeting of the members residing in that district to consider the removal of the director. By a vote of the majority of the members of the district voting, the association may remove the officer or director and fill the vacancy.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c307.pdf?cite=1989%20c%20307%20§%2012[1989 c 307 § 12]; ]

== 23.86.090 - Amendments to articles.
The articles of incorporation may be amended by a majority vote of the members voting thereon, at any regular meeting or at any special meeting called for that purpose, after notice of the proposed amendment has been given to all members entitled to vote thereon, in the manner provided by the bylaws: PROVIDED, That if the total vote upon the proposed amendment shall be less than twenty-five percent of the total membership of the association, the amendment shall not be approved. At the meeting, members may vote upon the proposed amendment in person, or by written proxy, or by mailed ballot. The power to amend shall include the power to extend the period of its duration for a further definite time or perpetually, and also include the power to increase or diminish the amount of capital stock and the number of shares: PROVIDED, The amount of the capital stock shall not be diminished below the amount of the paid-up capital stock at the time such amendment is adopted. After the adoption of an amendment to its articles of incorporation, the association shall cause a copy of such amendment adopted to be recorded in the office of the secretary of state as provided in RCW 24.06.195.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c307.pdf?cite=1989%20c%20307%20§%2023[1989 c 307 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%20174[1982 c 35 § 174]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c297.pdf?cite=1981%20c%20297%20§%2032[1981 c 297 § 32]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c34.pdf?cite=1961%20c%2034%20§%202[1961 c 34 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c19.pdf?cite=1913%20c%2019%20§%206[1913 c 19 § 6]; RRS § 3909; ]

== 23.86.095 - Registered agent.
Effective January 1, 1990, every association subject to this chapter shall have and maintain a registered agent in this state in accordance with the requirements set forth in Article 4 of chapter 23.95 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%209106[2015 c 176 § 9106]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c307.pdf?cite=1989%20c%20307%20§%2013[1989 c 307 § 13]; ]

== 23.86.100 - Bylaws.
Any association subject to this chapter may pass bylaws to govern itself in the carrying out of the provisions of this chapter which are not inconsistent with the provisions of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c307.pdf?cite=1989%20c%20307%20§%2024[1989 c 307 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c19.pdf?cite=1913%20c%2019%20§%2019[1913 c 19 § 19]; RRS § 3922; ]

== 23.86.105 - Member liability—Termination.
. Except for debts lawfully contracted between a member and the association, no member shall be liable for the debts of the association to an amount exceeding the sum remaining unpaid on his or her membership fee or subscription to capital stock.

. Membership may be terminated under provisions, rules, or regulations prescribed in the articles of incorporation or bylaws. In the absence thereof, the board of directors may prescribe such provisions, rules, and regulations.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c307.pdf?cite=1989%20c%20307%20§%2019[1989 c 307 § 19]; ]

== 23.86.115 - Voting.
. The right of a member to vote may be limited, enlarged, or denied to the extent specified in the articles of incorporation or bylaws. Unless so limited, enlarged, or denied, each member shall be entitled to one vote on each matter submitted to a vote of members. The bylaws may allow subscribers to vote as members if one-fifth of the subscription for the membership fee or capital stock has been paid.

. A member may vote in person or, unless the articles of incorporation or the bylaws otherwise provide, may vote by mail, by electronic transmission, or by proxy executed in writing by the member or by a duly authorized attorney-in-fact. No proxy shall be valid for more than 11 months from the date of its execution unless otherwise specified in the proxy. Votes by mail or by proxy shall be made by mail ballot or proxy form prepared and distributed by the association in accordance with procedures set forth in the articles of incorporation or bylaws. Persons voting by mail or by electronic transmission shall be deemed present for all purposes of quorum, count of votes, and percentage voting of total voting power.

. If the articles of incorporation or bylaws provide for more or less than one vote per member on any matter, every reference in this chapter to a majority or other proportion of members shall refer to such a majority or other proportion of votes entitled to be cast by members.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5347.SL.pdf?cite=2021%20c%20101%20§%201[2021 c 101 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c307.pdf?cite=1989%20c%20307%20§%2021[1989 c 307 § 21]; ]

== 23.86.125 - Voting—Quorum.
Except as otherwise provided in this chapter, the articles of incorporation or the bylaws may provide the number or percentage of votes that members are entitled to cast in person, by mail, or by proxy that shall constitute a quorum at meetings of members. In the absence of any provision in the articles of incorporation or bylaws, twenty-five percent of the total membership of the association shall constitute a quorum.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c307.pdf?cite=1989%20c%20307%20§%2022[1989 c 307 § 22]; ]

== 23.86.135 - Members right to dissent—Exception for members of a rural electric association.
. Except as provided in subsection (2) of this section, a member of an association shall have the right to dissent from any of the following association actions:

.. Any plan of merger or consolidation to which the association is a party;

.. Any plan of conversion of the association to an ordinary business corporation; or

.. Any sale or exchange of all or substantially all of the property and assets of the association not made in the usual and regular course of its business, including a sale in dissolution, but not including a sale pursuant to an order of a court having jurisdiction in the premises or a sale for cash on terms requiring that all or substantially all of the net proceeds of the sale be distributed to the members in accordance with their respective interests within one year from the date of sale.

. A member of a rural electric association is not entitled to dissent from a merger to which the association is a party if all members of the association have the right to continue their membership status in the surviving association on substantially similar terms.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6338-S.SL.pdf?cite=2016%20c%20228%20§%201[2016 c 228 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c307.pdf?cite=1989%20c%20307%20§%2030[1989 c 307 § 30]; ]

== 23.86.145 - Rights of dissenting members.
. Except as provided otherwise under this chapter, the rights and procedures set forth in chapter 23B.13 RCW shall apply to a member who elects to exercise the right of dissent.

. The articles of incorporation of an association subject to this chapter may provide that a dissenting member shall be limited to a return of less than the fair value of the member's equity interest in the association, but a dissenting member may not be limited to a return of less than the consideration paid to or retained by the association for the equity interest unless the fair value is less than the consideration paid to or retained by the association.

. Any member of an agricultural association who exercises the right to dissent from an association action described in RCW 23.86.135 shall be entitled to payment of the member's equity interest on the same time schedule that would have applied if membership in the association had been terminated.

. Subsection (3) of this section does not apply to agricultural associations that are involved in an action under subsection (3) of this section before June 9, 1994: (a) As to the associations that were involved in the particular action; (b) for three years after June 9, 1994.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6492-S.SL.pdf?cite=1994%20c%20206%20§%202[1994 c 206 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=1991%20c%2072%20§%2016[1991 c 72 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c307.pdf?cite=1989%20c%20307%20§%2031[1989 c 307 § 31]; ]

== 23.86.160 - Apportionment of earnings.
The directors may apportion the net earnings by paying dividends upon the paid-up capital stock at a rate not exceeding eight percent per annum. They may set aside reasonable reserves out of such net earnings for any association purpose. The directors may, however, distribute all or any portion of the net earnings to members in proportion to the business of each with the association and they may include nonmembers at a rate not exceeding that paid to members. The directors may distribute, on a patronage basis, such net earnings at different rates on different classes, kinds, or varieties of products handled. All dividends declared or other distributions made under this section may, in the discretion of the directors, be in the form of capital stock, capital or equity certificates, book credits, or capital funds of the association. All unclaimed dividends or distributions authorized under this chapter or funds payable on redeemed stock, equity certificates, book credits, or capital funds shall revert to the association at the discretion of the directors at any time after one year from the end of the fiscal year during which such distributions or redemptions have been declared.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c307.pdf?cite=1989%20c%20307%20§%2025[1989 c 307 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c37.pdf?cite=1947%20c%2037%20§%201[1947 c 37 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c99.pdf?cite=1943%20c%2099%20§%203[1943 c 99 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c19.pdf?cite=1913%20c%2019%20§%2013[1913 c 19 § 13]; Rem. Supp. 1947 § 3916; ]

== 23.86.170 - Distribution of dividends.
The profits or net earnings of such association shall be distributed to those entitled thereto at such time and in such manner not inconsistent with this chapter as its bylaws shall prescribe, which shall be as often as once a year.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c19.pdf?cite=1913%20c%2019%20§%2014[1913 c 19 § 14]; RRS § 3917; ]

== 23.86.191 - Indemnification of agents of any corporation authorized.
See RCW 23B.17.030.

[ ]

== 23.86.195 - Cooperative associations organized under other statutes—Reorganization under chapter.
Any cooperative association organized under any other statute may be reorganized under the provisions of this chapter by adopting and filing amendments to its articles of incorporation in accordance with the provisions of this chapter for amending articles of incorporation. The articles of incorporation as amended must conform to the requirements of this chapter, and shall state that the cooperative association accepts the benefits and will be bound by the provisions of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c307.pdf?cite=1989%20c%20307%20§%2026[1989 c 307 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c297.pdf?cite=1981%20c%20297%20§%2038[1981 c 297 § 38]; ]

== 23.86.200 - Definitions.
For the purposes of RCW 23.86.200 through 23.86.230 a "domestic" cooperative association or "domestic" corporation is one formed under the laws of this state, and an "ordinary business" corporation is one formed or which could be formed under Title 23B RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=1991%20c%2072%20§%2017[1991 c 72 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c221.pdf?cite=1971%20ex.s.%20c%20221%20§%201[1971 ex.s. c 221 § 1]; ]

== 23.86.210 - Conversion of cooperative association to domestic ordinary business corporation—Procedure.
. A cooperative association may be converted to a domestic ordinary business corporation pursuant to the following procedures:

.. The board of directors of the association shall, by affirmative vote of not less than two-thirds of all such directors, adopt a plan for such conversion setting forth:

... The reasons why such conversion is desirable and in the interests of the members of the association;

... The proposed contents of articles of conversion with respect to items (ii) through (ix) of subparagraph (c) below; and

... Such other information and matters as the board of directors may deem to be pertinent to the proposed plan.

.. After adoption by the board of directors, the plan for conversion shall be submitted for approval or rejection to the members of the association at any regular meetings or at any special meetings called for that purpose, after notice of the proposed conversion has been given to all members entitled to vote thereon, in the manner provided by the bylaws. The notice of the meeting shall be accompanied by a full copy of the proposed plan for conversion or by a summary of its provisions. At the meeting members may vote upon the proposed conversion in person, or by written proxy, or by mailed ballot. The affirmative vote of two-thirds of the members voting thereon shall be required for approval of the plan of conversion. If the total vote upon the proposed conversion shall be less than twenty-five percent of the total membership of the association, the conversion shall not be approved.

.. Upon approval by the members of the association, the articles of conversion shall be executed in duplicate by the association by one of its officers and shall set forth:

... The dates and vote by which the plan for conversion was adopted by the board of directors and members respectively;

... The corporate name of the converted organization. The name shall comply with requirements in Article 3 of chapter 23.95 RCW for names of business corporations formed under Title 23B RCW, and shall not contain the term "cooperative";

... The purpose or purposes for which the converted corporation is to exist;

... The duration of the converted corporation, which may be perpetual or for a stated term of years;

.. The capitalization of the converted corporation and the class or classes of shares of stock into which divided, together with the par value, if any, of such shares, in accordance with statutory requirements applicable to ordinary business corporations, and the basis upon which outstanding shares of the association are converted into shares of the converted corporation;

.. Any provision limiting or denying to shareholders the preemptive right to acquire additional shares of the converted corporation;

.. The address of the converted corporation's initial registered agent;

.. The names and addresses of the persons who are to serve as directors of the converted corporation until the first annual meeting of shareholders of the converted corporation or until their successors are elected and qualify;

... Any additional provisions, not inconsistent with law, provided for by the plan for conversion for the regulation of the internal affairs of the converted corporation, including any provision restricting the transfer of shares or which under Title 23B RCW is required or permitted to be set forth in bylaws.

.. The articles of conversion shall be delivered to the secretary of state for filing in accordance with Article 2 of chapter 23.95 RCW.

.. Upon delivering the articles of conversion to the secretary of state for filing, the converted corporation shall pay, and the secretary of state shall collect, the same filing and license fees as for filing articles of incorporation of a newly formed business corporation similarly capitalized.

. Upon filing by the secretary of state of the articles of conversion, the conversion of the cooperative association to an ordinary business corporation shall become effective as provided in RCW 23.95.210; the articles of conversion shall thereafter constitute and be treated in like manner as articles of incorporation; and the converted corporation shall be subject to all laws applicable to corporations formed under Title 23B RCW, and shall not thereafter be subject to laws applying only to cooperative associations. The converted corporation shall constitute and be deemed to constitute a continuation of the corporate substance of the cooperative association and the conversion shall in no way derogate from the rights of creditors of the former association.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%209107[2015 c 176 § 9107]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=1991%20c%2072%20§%2018[1991 c 72 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c307.pdf?cite=1989%20c%20307%20§%2027[1989 c 307 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%20175[1982 c 35 § 175]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c297.pdf?cite=1981%20c%20297%20§%2034[1981 c 297 § 34]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c221.pdf?cite=1971%20ex.s.%20c%20221%20§%202[1971 ex.s. c 221 § 2]; ]

== 23.86.220 - Merger of cooperative association with one or more cooperative associations or business corporations—Procedure.
. A cooperative association may merge with one or more domestic cooperative associations, or with one or more domestic ordinary business corporations, in accordance with the procedures and subject to the conditions set forth or referred to in this section.

. If the merger is into another domestic cooperative association, the board of directors of each of the associations shall approve by vote of not less than two-thirds of all the directors, a plan of merger setting forth:

.. The names of the associations proposing to merge;

.. The name of the association which is to be the surviving association in the merger;

.. The terms and conditions of the proposed merger;

.. The manner and basis of converting the shares of each merging association into shares or other securities or obligations of the surviving association;

.. A statement of any changes in the articles of incorporation of the surviving association to be effected by such merger; and

.. Such other provisions with respect to the proposed merger as are deemed necessary or desirable.

. Following approval by the boards of directors, the plan of merger shall be submitted to a vote of the members of each of the associations at any regular meeting or at any special meetings called for that purpose, after notice of the proposed merger has been given to all members entitled to vote thereon, in the manner provided in the bylaws. The notice of the meeting shall be in writing stating the purpose or purposes of the meeting and include or be accompanied by a copy or summary of the plan of merger. At the meeting members may vote upon the proposed merger in person, or by written proxy, or by mailed ballot. The affirmative vote of two-thirds of the members voting thereon, by each association, shall be required for approval of the plan of merger. If the total vote of either association upon the proposed merger shall be less than twenty-five percent of the total membership of such association, the merger shall not be approved.

. Upon approval by the members of the associations proposing to merge, articles of merger shall be executed in duplicate by each association by an officer of each association, and shall set forth:

.. The plan of merger;

.. As to each association, the number of members and, if there is capital stock, the number of shares outstanding; and

.. As to each association, the number of members who voted for and against such plan, respectively.

. The articles of merger shall be delivered to the secretary of state for filing in accordance with Article 2 of chapter 23.95 RCW.

. For filing articles of merger hereunder the secretary of state shall charge and collect the same fees as apply to filing of articles of merger of ordinary business corporations.

. If the plan of merger is for merger of the cooperative association into a domestic ordinary business corporation, the association shall follow the same procedures as hereinabove provided for merger of domestic cooperative associations and the ordinary business corporation shall follow the applicable procedures set forth in RCW 23B.07.050 and chapter 23B.11 RCW.

. At any time prior to filing of the articles of merger, the merger may be abandoned pursuant to provisions therefor, if any, set forth in the plan of merger.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%209108[2015 c 176 § 9108]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=1991%20c%2072%20§%2019[1991 c 72 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c307.pdf?cite=1989%20c%20307%20§%2028[1989 c 307 § 28]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%20176[1982 c 35 § 176]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c297.pdf?cite=1981%20c%20297%20§%2035[1981 c 297 § 35]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c221.pdf?cite=1971%20ex.s.%20c%20221%20§%203[1971 ex.s. c 221 § 3]; ]

== 23.86.230 - Merger of cooperative association with one or more cooperative associations or business corporations—Rights, powers, duties and liabilities of surviving entity—Articles.
. Upon issuance of the certificate of merger by the secretary of state, the merger of the cooperative association into another cooperative association or ordinary business corporation, as the case may be, shall be effected.

. When merger has been effected:

.. The several parties to the plan of merger shall be a single cooperative association or corporation, as the case may be, which shall be that cooperative association or corporation designated in the plan of merger as the survivor.

.. The separate existence of all parties to the plan of merger, except that of the surviving cooperative association or corporation, shall cease.

.. If the surviving entity is a cooperative association, it shall have all the rights, privileges, immunities and powers and shall be subject to all the duties and liabilities of a cooperative association organized under chapter 23.86 RCW. If the surviving entity is an ordinary business corporation, it shall have all the rights, privileges, immunities and powers and shall be subject to all the duties and liabilities of a corporation organized or existing under Title 23B RCW.

.. Such surviving cooperative association or corporation, as the case may be, shall thereupon and thereafter possess all the rights, privileges, immunities, and franchises, both public and private of each of the merging organizations, to the extent that such rights, privileges, immunities, and franchises are not inconsistent with the corporate nature of the surviving organization; and all property, real, personal and mixed, and all debts due on whatever account, including subscriptions to shares, and all other choses in action, and all and every other interest of or belonging to or due to each of the organizations so merged shall be taken and deemed to be transferred to and vested in such surviving cooperative association or corporation, as the case may be, without further act or deed; and the title to any real estate, or any interest therein, vested in any such merged cooperative association shall not revert or be in any way impaired by reason of such merger.

. The surviving cooperative association or corporation, as the case may be, shall, after the merger is effected, be responsible and liable for all the liabilities and obligations of each of the organizations so merged; and any claim existing or action or proceeding pending by or against any of such organizations may be prosecuted as if the merger had not taken place and the surviving cooperative association or corporation may be substituted in its place. Neither the right of creditors nor any liens upon the property of any cooperative association or corporation party to the merger shall be impaired by the merger.

. The articles of incorporation of the surviving cooperative association or of the surviving ordinary business corporation, as the case may be, shall be deemed to be amended to the extent, if any, that changes in such articles are stated in the plan of merger.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=1991%20c%2072%20§%2020[1991 c 72 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c307.pdf?cite=1989%20c%20307%20§%2029[1989 c 307 § 29]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c221.pdf?cite=1971%20ex.s.%20c%20221%20§%204[1971 ex.s. c 221 § 4]; ]

== 23.86.250 - Dissolution.
The members of any association may by the vote of two-thirds of the members voting thereon, at any regular meeting or at any special meeting called for that purpose, vote to dissolve said association after notice of the proposed dissolution has been given to all members entitled to vote thereon, in the manner provided by the bylaws, and thereupon such proceeding shall be had for the dissolution of said association as is provided by law for the dissolution of corporations organized under chapter 24.06 RCW: PROVIDED, That if the total vote upon the proposed dissolution shall be less than twenty-five percent of the total membership of the association, the dissolution shall not be approved. At the meeting, members may vote upon the proposed dissolution in person, or by written proxy, or by mailed ballot.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c297.pdf?cite=1981%20c%20297%20§%2036[1981 c 297 § 36]; ]

== 23.86.310 - Annual report.
Every association subject to this chapter shall deliver an annual report to the secretary of state in accordance with RCW 23.95.255.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%209109[2015 c 176 § 9109]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c307.pdf?cite=1989%20c%20307%20§%2015[1989 c 307 § 15]; ]

== 23.86.330 - Administrative dissolution.
The provisions of Article 6 of chapter 23.95 RCW relating to administrative dissolution by the secretary of state shall apply to every association subject to this chapter formed on or after July 23, 1989.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%209110[2015 c 176 § 9110]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=1991%20c%2072%20§%2021[1991 c 72 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c307.pdf?cite=1989%20c%20307%20§%2017[1989 c 307 § 17]; ]

== 23.86.350 - Application of RCW  24.06.100 and  24.06.105.
The provisions of RCW 24.06.100 and 24.06.105 shall apply to every association subject to this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c307.pdf?cite=1989%20c%20307%20§%2020[1989 c 307 § 20]; ]

== 23.86.360 - Application of Title 23B RCW.
The provisions of Title 23B RCW shall apply to the associations subject to this chapter, except where such provisions are in conflict with or inconsistent with the express provisions of this chapter. The terms "shareholder" or "shareholders" as used in Title 23B RCW, or in chapter 24.06 RCW as incorporated by reference herein, shall be deemed to refer to "member" or "members" as defined in this chapter. When the terms "share" or "shares" are used with reference to voting rights in Title 23B RCW, or in chapter 24.06 RCW as incorporated by reference herein, such terms shall be deemed to refer to the vote or votes entitled to be cast by a member or members.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=1991%20c%2072%20§%2023[1991 c 72 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c307.pdf?cite=1989%20c%20307%20§%2032[1989 c 307 § 32]; ]

== 23.86.370 - Application of Article 5 of chapter  23.95 RCW.
The provisions of Article 5 of chapter 23.95 RCW and RCW 24.06.367 and 24.06.369 shall apply to every foreign corporation which desires to conduct affairs in this state under the authority of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%209111[2015 c 176 § 9111]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c307.pdf?cite=1989%20c%20307%20§%2033[1989 c 307 § 33]; ]

== 23.86.400 - Locally regulated utilities—Attachments to poles.
. As used in this section:

.. "Attachment" means the affixation or installation of any wire, cable or other physical material capable of carrying electronic impulses or light waves for the carrying of intelligence for telecommunications or television, including, but not limited to cable, and any related device, apparatus, or auxiliary equipment upon any pole owned or controlled in whole or in part by one or more locally regulated utilities where the installation has been made with the necessary consent.

.. "Locally regulated utility" means an electric service cooperative organized under this chapter and not subject to rate or service regulation by the utilities and transportation commission.

.. "Nondiscriminatory" means that pole owners may not arbitrarily differentiate among or between similar classes of persons approved for attachments.

. All rates, terms, and conditions made, demanded or received by a locally regulated utility for attachments to its poles must be just, reasonable, nondiscriminatory and sufficient. A locally regulated utility shall levy attachment space rental rates that are uniform for the same class of service within the locally regulated utility service area.

. Nothing in this section shall be construed or is intended to confer upon the utilities and transportation commission any authority to exercise jurisdiction over locally regulated utilities.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6554-S.SL.pdf?cite=1996%20c%2032%20§%201[1996 c 32 § 1]; ]

== 23.86.410 - Tariff for irrigation pumping service—Authority for locally regulated utility to buy back electricity.
The board may approve a tariff for irrigation pumping service that allows the locally regulated utility to buy back electricity from customers to reduce electricity usage by those customers during the locally regulated utility's particular irrigation season.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1606.SL.pdf?cite=2001%20c%20122%20§%204[2001 c 122 § 4]; ]

== 23.86.420 - Conversion of domestic association to limited cooperative association—Procedure.
. Except as provided in subsection (2) of this section, a domestic association organized under this chapter may convert to a limited cooperative association pursuant to RCW 23.100.1302 through 23.100.1314.

. This section does not apply to a domestic association organized for the purpose of generating, purchasing, selling, marketing, transmitting, or distributing electric energy.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5002.SL.pdf?cite=2019%20c%2037%20§%201404[2019 c 37 § 1404]; ]

== 23.86.900 - Application—1989 c 307.
The provisions of this chapter relating to domestic cooperative associations shall apply to:

. All cooperative associations organized under this chapter; and

. All agricultural cooperative associations organized under *chapter 24.32 RCW. All such agricultural cooperatives are deemed to have been incorporated under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c307.pdf?cite=1989%20c%20307%20§%202[1989 c 307 § 2]; ]

