= 23.78 - Employee cooperative corporations.
:toc:

== 23.78.010 - Definitions.
For the purposes of this chapter, the terms defined in this section have the meanings given:

. "Employee cooperative" means a corporation that has elected to be governed by the provisions of this chapter.

. "Member" means a natural person who has been accepted for membership in, and owns a membership share issued by an employee cooperative.

. "Patronage" means the amount of work performed as a member of an employee cooperative, measured in accordance with the articles of incorporation and bylaws.

. "Written notice of allocation" means a written instrument which discloses to a member the stated dollar amount of the member's patronage allocation, and the terms for payment of that amount by the employee cooperative.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c457.pdf?cite=1987%20c%20457%20§%202[1987 c 457 § 2]; ]

== 23.78.020 - Election by corporation to be governed as an employee cooperative—Laws governing.
Any corporation organized under the laws of this state may elect to be governed as an employee cooperative under the provisions of this chapter, by so stating in its articles of incorporation, or articles of amendment filed in accordance with Title 23B RCW and Article 2 of chapter 23.95 RCW.

A corporation so electing shall be governed by all provisions of Title 23B RCW, except RCW 23B.07.050, 23B.13.020, and chapter 23B.11 RCW, and except as otherwise provided in this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%209101[2015 c 176 § 9101]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=1991%20c%2072%20§%209[1991 c 72 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c457.pdf?cite=1987%20c%20457%20§%203[1987 c 457 § 3]; ]

== 23.78.030 - Revocation of election.
An employee cooperative may revoke its election under this chapter by a vote of two-thirds of the members and through articles of amendment delivered to the secretary of state for filing in accordance with RCW 23B.01.200, 23B.10.060, and Article 2 of chapter 23.95 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%209102[2015 c 176 § 9102]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=1991%20c%2072%20§%2010[1991 c 72 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c457.pdf?cite=1987%20c%20457%20§%204[1987 c 457 § 4]; ]

== 23.78.040 - Corporate name.
An employee cooperative may include the word "cooperative" or "co-op" in its corporate name.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c457.pdf?cite=1987%20c%20457%20§%205[1987 c 457 § 5]; ]

== 23.78.050 - Members—Membership shares.
. The articles of incorporation or the bylaws shall establish qualifications and the method of acceptance and termination of members. No person may be accepted as a member unless employed by the employee cooperative on a full-time or part-time basis.

. An employee cooperative shall issue a class of voting stock designated as "membership shares." Each member shall own only one membership share, and only members may own these shares.

. Membership shares shall be issued for a fee as determined from time to time by the directors. RCW 23B.06.040 and 23B.06.200 do not apply to such membership shares.

Members of an employee cooperative shall have all the rights and responsibilities of stockholders of a corporation organized under Title 23B RCW, except as otherwise provided in this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=1991%20c%2072%20§%2011[1991 c 72 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c457.pdf?cite=1987%20c%20457%20§%206[1987 c 457 § 6]; ]

== 23.78.060 - Right to vote—Power to amend or repeal bylaws—Right to amend articles of incorporation.
. No capital stock other than membership shares shall be given voting power in an employee cooperative, except as otherwise provided in this chapter, or in the articles of incorporation.

. The power to amend or repeal bylaws of an employee cooperative shall be in the members only.

. Except as otherwise permitted by RCW 23B.10.040, no capital stock other than membership shares shall be permitted to vote on any amendment to the articles of incorporation.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=1991%20c%2072%20§%2012[1991 c 72 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c457.pdf?cite=1987%20c%20457%20§%207[1987 c 457 § 7]; ]

== 23.78.070 - Net earnings or losses—Apportionment, distribution, and payment.
. The net earnings or losses of an employee cooperative shall be apportioned and distributed at the times and in the manner as the articles of incorporation or bylaws shall specify. Net earnings declared as patronage allocations with respect to a period of time, and paid or credited to members, shall be apportioned among the members in accordance with the ratio which each member's patronage during the period involved bears to total patronage by all members during that period.

. The apportionment, distribution, and payment of net earnings required by subsection (1) of this section may be in cash, credits, written notices of allocation, or capital stock issued by the employee cooperative.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c457.pdf?cite=1987%20c%20457%20§%208[1987 c 457 § 8]; ]

== 23.78.080 - Internal capital accounts authorized—Redemptions—Assignment of portion of retained net earnings and net losses to collective reserve account authorized.
. Any employee cooperative may establish through its articles of incorporation or bylaws a system of internal capital accounts to reflect the book value and to determine the redemption price of membership shares, capital stock, and written notices of allocation.

. The articles of incorporation or bylaws of an employee cooperative may permit the periodic redemption of written notices of allocation and capital stock, and must provide for recall and redemption of the membership share upon termination of membership in the cooperative. No redemption shall be made if redemption would result in a violation of RCW 23B.06.400.

. The articles of incorporation or bylaws may provide for the employee cooperative to pay or credit interest on the balance in each member's internal capital account.

. The articles of incorporation or bylaws may authorize assignment of a portion of retained net earnings and net losses to a collective reserve account. Earnings assigned to the collective reserve account may be used for any and all corporate purposes as determined by the board of directors.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=1991%20c%2072%20§%2013[1991 c 72 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c457.pdf?cite=1987%20c%20457%20§%209[1987 c 457 § 9]; ]

== 23.78.090 - Internal capital account cooperatives.
. An internal capital account cooperative is an employee cooperative whose entire net book value is reflected in internal capital accounts, one for each member, and a collective reserve account, and in which no persons other than members own capital stock. In an internal capital account cooperative, each member shall have one and only one vote in any matter requiring voting by stockholders.

. An internal capital account cooperative shall credit the paid-in membership fee and additional paid-in capital of a member to the member's internal capital account, and shall also record the apportionment of retained net earnings or net losses to the members in accordance with patronage by appropriately crediting or debiting the internal capital accounts of members. The collective reserve account in an internal capital account cooperative shall reflect any paid-in capital, net losses, and retained net earnings not allocated to individual members.

. In an internal capital account cooperative, the balances in all the individual internal capital accounts and collective reserve account, if any, shall be adjusted at the end of each accounting period so that the sum of the balances is equal to the net book value of the employee cooperative.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c457.pdf?cite=1987%20c%20457%20§%2010[1987 c 457 § 10]; ]

== 23.78.100 - Provision for conversion of shares and accounts—Limitations upon merger.
. When any employee cooperative revokes its election in accordance with RCW 23.78.030, the articles of amendment shall provide for conversion of membership shares and internal capital accounts or their conversion to securities or other property in a manner consistent with Title 23B RCW.

. An employee cooperative that has not revoked its election under this chapter may not merge with another corporation other than an employee cooperative. Two or more employee cooperatives may merge in accordance with RCW 23B.01.200, 23B.07.050, and chapter 23B.11 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=1991%20c%2072%20§%2014[1991 c 72 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c457.pdf?cite=1987%20c%20457%20§%2011[1987 c 457 § 11]; ]

== 23.78.900 - Short title.
This chapter may be cited as the employee cooperative corporations act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c457.pdf?cite=1987%20c%20457%20§%201[1987 c 457 § 1]; ]

