= 16.30 - Dangerous wild animals.
:toc:

== 16.30.005 - Intent.
It is the intent of the state of Washington to protect the public against the serious health and safety risks that dangerous wild animals pose to the community.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1418.SL.pdf?cite=2007%20c%20238%20§%201[2007 c 238 § 1]; ]

== 16.30.010 - Definitions.
. "Animal control authority" means an entity acting alone or in concert with other local governmental units for enforcement of the animal control laws of the city, county, and state and the shelter and welfare of animals.

. "Potentially dangerous wild animal" means one of the following types of animals, whether bred in the wild or in captivity, and any or all hybrids thereof:

.. Class mammalia

... Order carnivora

(A) Family felidae, only lions, tigers, captive-bred cougars, jaguars, cheetahs, leopards, snow leopards, and clouded leopards;

(B) Family canidae, wolves, excluding wolf-hybrids;

(C) Family ursidae, all bears;

(D) Family hyaenidae, such as hyenas;

... Order perissodactyla, only rhinoceroses;

... Order primates, all nonhuman primate species;

... Order proboscidae, all elephants [elephant] species;

.. Class reptilia

... Order squamata

(A) Family atractaspidae, all species;

(B) Family colubridae, only dispholidus typus;

(C) Family elapidae, all species, such as cobras, mambas, kraits, coral snakes, and Australian tiger snakes;

(D) Family hydrophiidae, all species, such as sea snakes;

(E) Family varanidae, only water monitors and crocodile monitors;

(F) Family viperidae, all species, such as rattlesnakes, cottonmouths, bushmasters, puff adders, and gaboon vipers;

... Order crocodilia, all species, such as crocodiles, alligators, caimans, and gavials.

. "Person" means any individual, partnership, corporation, organization, trade or professional association, firm, limited liability company, joint venture, association, trust, estate, or any other legal entity, and any officer, member, shareholder, director, employee, agent, or representative thereof.

. "Possessor" means any person who owns, possesses, keeps, harbors, brings into the state, or has custody or control of a potentially dangerous wild animal.

. "Wildlife sanctuary" means a nonprofit organization, as described in RCW 84.36.800, that cares for animals defined as potentially dangerous and:

.. No activity that is not inherent to the animal's nature, natural conduct, or the animal in its natural habitat is conducted;

.. No commercial activity involving an animal occurs including, but not limited to, the sale of or trade in animals, animal parts, animal by-products, or animal offspring, or the sale of photographic opportunities involving an animal, or the use of an animal for any type of entertainment purpose;

.. No unescorted public visitations or direct contact between the public and an animal; or

.. No breeding of animals occurs in the facility.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1418.SL.pdf?cite=2007%20c%20238%20§%202[2007 c 238 § 2]; ]

== 16.30.020 - Exceptions.
. The provisions of this chapter do not apply to:

.. Institutions authorized by the Washington department of fish and wildlife to hold, possess, and propagate deleterious exotic wildlife pursuant to RCW 77.12.047;

.. Institutions accredited or certified by the American zoo and aquarium association or a facility with a current signed memorandum of participation with an association of zoos and aquariums species survival plan;

.. Duly incorporated nonprofit animal protection organizations, such as humane societies and shelters, housing an animal at the written request of the animal control authority or acting under the authority of this chapter;

.. Animal control authority, law enforcement officers, or county sheriffs acting under the authority of this chapter;

.. Veterinary hospitals or clinics;

.. A holder of a valid wildlife rehabilitation permit issued by the Washington department of fish and wildlife;

.. Any wildlife sanctuary as defined under RCW 16.30.010(5);

.. A research facility as defined by the animal welfare act, 7 U.S.C.A. 2131, as amended, for the species of animals for which they are registered. This includes but is not limited to universities, colleges, and laboratories holding a valid class R license under the animal welfare act;

.. Circuses, defined as incorporated, class C licensees under the animal welfare act, 7 U.S.C.A. 2131, as amended, that are temporarily in this state, and that offer performances by live animals, clowns, and acrobats for public entertainment;

.. A person temporarily transporting and displaying a potentially dangerous wild animal through the state if the transit time is not more than twenty-one days and the animal is at all times maintained within a confinement sufficient to prevent the animal from escaping;

.. Domesticated animals subject to this title or native wildlife subject to Title 77 RCW;

.. A person displaying animals at a fair approved by the Washington department of agriculture pursuant to chapter 15.76 or 36.37 RCW; and

.. A game farm meeting the requirements of WAC 232-12-027(1).

. This chapter does not require a city or county that does not have an animal control authority to create that office.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1418.SL.pdf?cite=2007%20c%20238%20§%203[2007 c 238 § 3]; ]

== 16.30.030 - Prohibited behavior.
. A person shall not own, possess, keep, harbor, bring into the state, or have custody or control of a potentially dangerous wild animal, except as provided in subsection (3) of this section.

. A person shall not breed a potentially dangerous wild animal.

. A person in legal possession of a potentially dangerous wild animal prior to July 22, 2007, and who is the legal possessor of the animal may keep possession of the animal for the remainder of the animal's life. The person must maintain veterinary records, acquisition papers for the animal, if available, or other documents or records that establish that the person possessed the animal prior to July 22, 2007, and present the paperwork to an animal control or law enforcement authority upon request. The person shall have the burden of proving that he or she possessed the animal prior to July 22, 2007.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1418.SL.pdf?cite=2007%20c%20238%20§%204[2007 c 238 § 4]; ]

== 16.30.040 - Confiscation—Duties of animal control authority or law enforcement officer.
. The animal control authority or a law enforcement officer may immediately confiscate a potentially dangerous wild animal if:

.. The animal control authority or law enforcement officer has probable cause to believe that the animal was acquired after July 22, 2007, in violation of RCW 16.30.030;

.. The animal poses a public safety or health risk;

.. The animal is in poor health and condition as a result of the possessor; or

.. The animal is being held in contravention of the [this] act.

. A potentially dangerous wild animal that is confiscated under this section may be returned to the possessor only if the animal control authority or law enforcement officer establishes that the possessor had possession of the animal prior to July 22, 2007, and the return does not pose a public safety or health risk.

. The animal control authority or law enforcement officer shall serve notice upon the possessor in person or by regular and certified mail, return receipt requested, notifying the possessor of the confiscation, that the possessor is responsible for payment of reasonable costs for caring and providing for the animal during the confiscation, and that the possessor must meet the requirements of subsection (2) of this section in order for the animal to be returned to the possessor.

. If a potentially dangerous wild animal confiscated under this section is not returned to the possessor, the animal control authority or law enforcement officer may release the animal to a facility such as a wildlife sanctuary or a facility exempted pursuant to RCW 16.30.020. If the animal control authority or law enforcement officer is unable to relocate the animal within a reasonable period of time, it may euthanize the animal.

. An animal control authority or law enforcement officer may euthanize a potentially dangerous wild animal under this section only if all known reasonable placement options, including relocation to a wildlife sanctuary, are unavailable.

. This section applies to animal confiscations on or after July 22, 2007.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1418.SL.pdf?cite=2007%20c%20238%20§%205[2007 c 238 § 5]; ]

== 16.30.050 - City or county ordinances.
A city or county may adopt an ordinance governing potentially dangerous wild animals that is more restrictive than this chapter. However, nothing in this chapter requires a city or county to adopt an ordinance to be in compliance with this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1418.SL.pdf?cite=2007%20c%20238%20§%206[2007 c 238 § 6]; ]

== 16.30.060 - Violations—Civil penalty.
A person who violates RCW 16.30.030 is liable for a civil penalty of not less than two hundred dollars and not more than two thousand dollars for each animal with respect to which there is a violation and for each day the violation continues.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1418.SL.pdf?cite=2007%20c%20238%20§%207[2007 c 238 § 7]; ]

== 16.30.070 - Enforcement of provisions.
. The animal control authority and its staff and agents, local law enforcement agents, and county sheriffs are authorized and empowered to enforce the provisions of this chapter.

. If a locality does not have a local animal control authority, the department of fish and wildlife shall enforce the provisions of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1418.SL.pdf?cite=2007%20c%20238%20§%208[2007 c 238 § 8]; ]

