= 16.49 - Custom slaughtering.
:toc:

== 16.49.005 - Intent.
This chapter is intended to safeguard the household user of uninspected and inspected meat products from possible harm due to adulterated, misbranded, or unfit meat or meat products or meat or meat products that have been prepared under insanitary conditions.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2377-S.SL.pdf?cite=2000%20c%2099%20§%201[2000 c 99 § 1]; ]

== 16.49.008 - Application.
. This chapter does not apply to the slaughter and preparation of one thousand or fewer pastured chickens in a calendar year by the agricultural producer of the chickens for the sale of whole raw chickens by the producer directly to the ultimate consumer at the producer's farm.

. For the purposes of this section, "chicken" means the species Gallus domesticus.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1754-S.SL.pdf?cite=2003%20c%20397%20§%201[2003 c 397 § 1]; ]

== 16.49.015 - Definitions.
For the purposes of this chapter:

. "Department" means the department of agriculture of the state of Washington.

. "Director" means the director of the department or the director's designee.

. "Custom farm slaughterer" means a person licensed to slaughter meat food animals for the owner of the animal through the use of a mobile unit.

. "Custom slaughtering establishment" means the facility operated by a person licensed to slaughter meat food animals for the owner of the animal at a fixed location.

. "Custom meat facility" means the facility operated by a person licensed to prepare uninspected meat for the owner of the uninspected meat. Operators of custom meat facilities may also sell prepackaged inspected meat to any person. This chapter does not prohibit the operator of a custom meat facility from being licensed to prepare at the facility and sell inspected meat to any person.

. "Inspected meat" means the carcasses or carcass parts of meat food animals which have been slaughtered and inspected at establishments subject to inspection under a federal meat inspection act.

. "Uninspected meat" means the carcasses or carcass parts of meat food animals that have been slaughtered by the owner of the animals, a custom farm slaughterer, or at a custom slaughtering establishment.

. "Household user" means the ultimate consumer, members of the consumer's household, and his or her nonpaying guests and employees.

. "Person" means any individual, partnership, association, and corporation.

. "Meat food animal" means cattle, swine, sheep, or goats.

. "Meat food bird" means a ratite, such as an ostrich, emu, or rhea.

. "Official establishment" means an establishment operated for the purpose of slaughtering meat food animals for sale or use as human food in compliance with the federal meat inspection act.

. "Prepared" means smoked, salted, rendered, boned, cut up, or otherwise processed.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2377-S.SL.pdf?cite=2000%20c%2099%20§%202[2000 c 99 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1151.SL.pdf?cite=1999%20c%20291%20§%2028[1999 c 291 § 28]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c77.pdf?cite=1987%20c%2077%20§%204[1987 c 77 § 4]; ]

== 16.49.025 - Rules.
The director shall enforce and carry out the provisions of this chapter and adopt rules necessary to carry out its purpose. The rules may include, but are not limited to:

. Requirements for construction, equipment, cleaning, sanitation, and sanitary practices to ensure sanitary operations;

. Requirements for identification or tagging of meat food animals slaughtered by licensees to maintain identification of the owner of the animal;

. Requirements for handling and storing inspected and uninspected meats and meat products;

. Requirements for labeling meat and meat products; and

. Requirements for slaughtering and processing of meat food birds by licensees.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2377-S.SL.pdf?cite=2000%20c%2099%20§%203[2000 c 99 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c77.pdf?cite=1987%20c%2077%20§%205[1987 c 77 § 5]; ]

== 16.49.035 - Custom slaughtering and custom meat licenses—Generally.
. It is unlawful for any person to operate as a custom farm slaughterer or to operate a custom slaughtering establishment or custom meat facility in the state without first obtaining a license from the director. Custom farm slaughterers must obtain a separate license for each mobile unit. Separate licenses are required for each custom slaughtering establishment and custom meat facility.

. Application for a license must be made on a form prescribed by the director and accompanied by a twenty-five dollar license fee. The application must include:

.. The full name and address of the applicant. If the applicant is a partnership or corporation, the application must include the full name and address of each partner or officer;

.. The physical location address of each establishment or facility to be licensed;

.. The name and address of a resident of this state authorized to accept legal notices for the applicant; and

.. Any other information prescribed by the director.

. If an application for renewal of a license and the license fee are not received by June 30th, the applicant must pay an additional fee of twenty-five dollars before the renewal license is issued.

. Initial issuance of a license requires a prelicense inspection by the director for compliance with this chapter and rules adopted under this chapter. A license shall only be issued after an applicant is found to be in substantial compliance with this chapter and rules adopted under this chapter.

. Licenses issued under this chapter expire June 30th of each year.

. Licenses issued under this chapter are not transferable.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2377-S.SL.pdf?cite=2000%20c%2099%20§%204[2000 c 99 § 4]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5713-S.SL.pdf?cite=1991%20c%20109%20§%204[1991 c 109 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c77.pdf?cite=1987%20c%2077%20§%201[1987 c 77 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c415.pdf?cite=1985%20c%20415%20§%205[1985 c 415 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c204.pdf?cite=1959%20c%20204%20§%2044[1959 c 204 § 44]; ]

== 16.49.045 - Inspections.
To determine compliance with this chapter and the rules adopted under this chapter, the director may inspect the mobile unit of any custom farm slaughterer and the premises of any custom slaughtering establishment or custom meat facility at any reasonable time.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2377-S.SL.pdf?cite=2000%20c%2099%20§%205[2000 c 99 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c77.pdf?cite=1987%20c%2077%20§%208[1987 c 77 § 8]; ]

== 16.49.055 - Custom meat facilities—Conditions for preparation of inspected and uninspected meat.
Inspected and uninspected meat may only be prepared by a custom meat facility under the following conditions:

. Inspected meat and meat products prepared from inspected meat must be kept separated from uninspected meat and meat products prepared from uninspected meat to prevent inspected meat from coming into contact with uninspected meat.

. Preparation of inspected meat and uninspected meat must be done at different times.

. Equipment used in preparing uninspected meat or products prepared from uninspected meat must be cleaned and sanitized before being used to prepare inspected meat.

. Uninspected meat may be prepared only for the use of the owner, who must be a household user.

. Uninspected meat and meat products prepared from uninspected meat must be clearly marked and labeled "not for sale".

. Packages of uninspected meat may not be stored in a retail counter.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2377-S.SL.pdf?cite=2000%20c%2099%20§%206[2000 c 99 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c77.pdf?cite=1987%20c%2077%20§%203[1987 c 77 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c415.pdf?cite=1985%20c%20415%20§%207[1985 c 415 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c98.pdf?cite=1971%20ex.s.%20c%2098%20§%203[1971 ex.s. c 98 § 3]; ]

== 16.49.065 - Licensed custom farm slaughterer—Transport of offal.
A licensed custom farm slaughterer may transport the offal of a meat food animal he or she has slaughtered for the owner, when it is transported as part of a slaughtering transaction and the offal is handled in a sanitary manner.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2377-S.SL.pdf?cite=2000%20c%2099%20§%207[2000 c 99 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c120.pdf?cite=1967%20ex.s.%20c%20120%20§%204[1967 ex.s. c 120 § 4]; ]

== 16.49.075 - Unlawful acts—Selling, trading, or giving away uninspected meat or meat products—Interfering with director's duties.
It is unlawful for any person to:

. Sell, trade, or give away uninspected meat or meat products; or

. Interfere with the director in the performance of his or her duties under this chapter or the rules adopted under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2377-S.SL.pdf?cite=2000%20c%2099%20§%208[2000 c 99 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c77.pdf?cite=1987%20c%2077%20§%209[1987 c 77 § 9]; ]

== 16.49.085 - Violations of chapter or rules—Investigation by director—Subpoenas.
The director may investigate any violation or possible violation of this chapter or any rule adopted under this chapter. To assist in such investigation, the director may issue subpoenas to compel the attendance of witnesses or to compel production of records or documents anywhere in the state.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2377-S.SL.pdf?cite=2000%20c%2099%20§%209[2000 c 99 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c77.pdf?cite=1987%20c%2077%20§%2010[1987 c 77 § 10]; ]

== 16.49.095 - Denial, suspension, revocation of license—Grounds—Request for hearing.
. The director may deny, suspend, or revoke any license required under this chapter if the director determines that an applicant or licensee has committed any of the following acts:

.. Refused, neglected, or failed to comply with the provisions of this chapter, the rules adopted under this chapter, or any lawful order of the director;

.. Refused, neglected, or failed to keep and maintain records required under this chapter or rules adopted under this chapter to make the records available to the director on request;

.. Refused the director access to any facilities or parts of the facilities for the purpose of carrying out the provisions of this chapter or rules adopted under this chapter; or

.. Refused, neglected, or failed to comply with any provisions of chapter 15.130 RCW or rules adopted under that chapter.

. Upon receipt of notice by the director to deny, suspend, or revoke a license, a person may request a hearing under chapter 34.05 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6318-S.SL.pdf?cite=2018%20c%20236%20§%20710[2018 c 236 § 710]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2377-S.SL.pdf?cite=2000%20c%2099%20§%2010[2000 c 99 § 10]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2523.SL.pdf?cite=1994%20c%20128%20§%201[1994 c 128 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c415.pdf?cite=1985%20c%20415%20§%2012[1985 c 415 § 12]; ]

== 16.49.105 - Noncompliance with chapter or rules—Civil penalty.
Any person who fails to comply with this chapter or the rules adopted under this chapter may be subject to a civil penalty in an amount of not more than one thousand dollars per violation per day. Each violation is a separate and distinct offense.

All moneys collected for civil penalties under this chapter shall be deposited in the state general fund.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2377-S.SL.pdf?cite=2000%20c%2099%20§%2011[2000 c 99 § 11]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2523.SL.pdf?cite=1994%20c%20128%20§%202[1994 c 128 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c415.pdf?cite=1985%20c%20415%20§%206[1985 c 415 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c204.pdf?cite=1959%20c%20204%20§%2051[1959 c 204 § 51]; ]

== 16.49.115 - Application of administrative procedure act.
Chapter 34.05 RCW governs the rights, remedies, and procedures respecting the administration of this chapter, including rule making, assessment of civil penalties, emergency actions, and license suspension, revocation, or denial.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2377-S.SL.pdf?cite=2000%20c%2099%20§%2012[2000 c 99 § 12]; ]

== 16.49.125 - Custom meat facilities—Sale of inspected meat—Ordinances may be more restrictive.
The provisions of this chapter relating to the sale of inspected meat in custom meat facilities do not supersede or restrict the authority of any county or any city to adopt ordinances that are more restrictive for the handling and sale of inspected meat than those provided in this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2377-S.SL.pdf?cite=2000%20c%2099%20§%2013[2000 c 99 § 13]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1151.SL.pdf?cite=1999%20c%20291%20§%2029[1999 c 291 § 29]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c77.pdf?cite=1987%20c%2077%20§%2011[1987 c 77 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c98.pdf?cite=1971%20ex.s.%20c%2098%20§%209[1971 ex.s. c 98 § 9]; ]

