= 16.50 - Humane slaughter of livestock.
:toc:

== 16.50.100 - Declaration of policy.
The legislature of the state of Washington finds that the use of humane methods in the slaughter of livestock prevents needless suffering; results in safer and better working conditions for persons engaged in the slaughtering industry; brings about improvement of products and economy in slaughtering operations; and produces other benefits for producers, processors and consumers which tend to expedite the orderly flow of livestock and their products. It is therefore declared to be the policy of the state of Washington to require that the slaughter of all livestock, and the handling of livestock in connection with slaughter, shall be carried out only by humane methods and to provide that methods of slaughter shall conform generally to those authorized by the Federal Humane Slaughter Act of 1958, and regulations thereunder.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c31.pdf?cite=1967%20c%2031%20§%201[1967 c 31 § 1]; ]

== 16.50.110 - Definitions.
For the purpose of this chapter:

. "Department" means the department of agriculture of the state of Washington.

. "Director" means the director of the department or his or her duly appointed representative.

. "Humane method" means either: (a) A method whereby the animal is rendered insensible to pain by mechanical, electrical, chemical, or other means that is rapid and effective, before being shackled, hoisted, thrown, cast, or cut; or (b) a method in accordance with the ritual requirements of any religious faith whereby the animal suffers loss of consciousness by anemia of the brain caused by the simultaneous and instantaneous severance of the carotid arteries with a sharp instrument.

. "Livestock" means cattle, calves, sheep, swine, horses, mules, and goats.

. "Packer" means any person engaged in the business of slaughtering livestock.

. "Person" means a natural person, individual, firm, partnership, corporation, company, society, and association and every officer, agent, or employee, thereof. This term shall import either the singular or plural, as the case may be.

. "Slaughterer" means any person engaged in the commercial or custom slaughtering of livestock, including custom farm slaughterers.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20421[2011 c 336 § 421]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c31.pdf?cite=1967%20c%2031%20§%202[1967 c 31 § 2]; ]

== 16.50.120 - Humane methods for bleeding or slaughtering livestock required.
No slaughterer or packer shall bleed or slaughter any livestock except by a humane method: PROVIDED, That the director may, by administrative order, exempt a person from compliance with this chapter for a period of not to exceed six months if he or she finds that an earlier compliance would cause such person undue hardship.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20422[2011 c 336 § 422]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c31.pdf?cite=1967%20c%2031%20§%203[1967 c 31 § 3]; ]

== 16.50.130 - Administration of chapter—Rules.
The director shall administer the provisions of this chapter. He or she shall adopt and may from time to time revise rules which shall conform substantially to the rules and regulations promulgated by the secretary of agriculture of the United States pursuant to the federal humane slaughter act of 1958, Public Law 85-765, 72 Stat. 862 and any amendments thereto. Such rules shall be adopted pursuant to the provisions of chapter 34.05 RCW as enacted or hereafter amended concerning the adoption of rules.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20423[2011 c 336 § 423]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c31.pdf?cite=1967%20c%2031%20§%204[1967 c 31 § 4]; ]

== 16.50.140 - Manually operated hammer, sledge or poleaxe—Declared inhumane.
The use of a manually operated hammer, sledge or poleaxe is declared to be an inhumane method of slaughter within the meaning of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c31.pdf?cite=1967%20c%2031%20§%205[1967 c 31 § 5]; ]

== 16.50.150 - Religious freedom—Ritual slaughter defined as humane.
Nothing in this chapter shall be construed to prohibit, abridge, or in any way hinder the religious freedom of any person or group. Notwithstanding any other provisions of this chapter, ritual slaughter and the handling or other preparation of livestock for ritual slaughter is defined as humane.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c31.pdf?cite=1967%20c%2031%20§%2010[1967 c 31 § 10]; ]

== 16.50.160 - Injunctions against violations.
The director may bring an action to enjoin the violation or threatened violation of any provision of this chapter or any rule adopted pursuant to this chapter in the superior court in the county in which such violation occurs or is about to occur, notwithstanding the existence of the other remedies at law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c31.pdf?cite=1967%20c%2031%20§%206[1967 c 31 § 6]; ]

== 16.50.170 - Penalty for violations.
Any person violating any provision of this chapter or of any rule adopted hereunder is guilty of a misdemeanor and subject to a fine of not more than two hundred fifty dollars or confinement in the county jail for not more than ninety days.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c31.pdf?cite=1967%20c%2031%20§%207[1967 c 31 § 7]; ]

