= 16.58 - Identification of cattle through licensing of certified feed lots.
:toc:

== 16.58.010 - Purpose.
The purpose of this chapter is to expedite the movement of cattle from producers to the point of slaughter without losing the ownership identity of such cattle, and further to provide for fair and economical methods of identification of cattle in such commercial feed lots.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c81.pdf?cite=1979%20c%2081%20§%201[1979 c 81 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c181.pdf?cite=1971%20ex.s.%20c%20181%20§%201[1971 ex.s. c 181 § 1]; ]

== 16.58.020 - Definitions.
For the purpose of this chapter:

. "Certified feed lot" means any place, establishment, or facility commonly known as a commercial feed lot, cattle feed lot, or the like, which complies with all of the requirements of this chapter, and any rules adopted under this chapter and which holds a valid license from the director.

. "Department" means the department of agriculture of the state of Washington.

. "Director" means the director of the department or his or her duly authorized representative.

. "Licensee" means any persons licensed under the provisions of this chapter.

. "Person" means a natural person, individual, firm, partnership, corporation, company, society, and association, and every officer, agent or employee thereof. This term shall import either the singular or the plural as the case may be.

. "Livestock inspection" or "inspection" means the examination of livestock or livestock hides for brands or any means of identifying livestock or livestock hides including the examination of documents providing evidence of ownership.

. "Change of ownership" means the transfer of ownership from one person to another by the sale of livestock. It does not mean: A change in partners within a partnership; a change in members within an association or a society; or the sale of stock within a corporation, company, or association.

. "Direct to slaughter" means the delivery of livestock to a slaughter plant within ten days of the sale of the cattle to the slaughter plant.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5891-S.SL.pdf?cite=2003%20c%20326%20§%2046[2003 c 326 § 46]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c181.pdf?cite=1971%20ex.s.%20c%20181%20§%202[1971 ex.s. c 181 § 2]; ]

== 16.58.030 - Rules—Interference with director proscribed.
The director may adopt those rules as are necessary to carry out the purpose of this chapter. No person shall interfere with the director when he or she is performing or carrying out any duties imposed upon the director by this chapter or rules adopted under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5891-S.SL.pdf?cite=2003%20c%20326%20§%2047[2003 c 326 § 47]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c181.pdf?cite=1971%20ex.s.%20c%20181%20§%203[1971 ex.s. c 181 § 3]; ]

== 16.58.040 - Certified feed lot license—Required—Application, contents.
Any person desiring to engage in the business of operating one or more certified feed lots shall obtain an annual license from the director for that purpose. The application for a license shall be on a form prescribed by the director and shall include the following:

. The number of certified feed lots the applicant intends to operate and their exact location and mailing address;

. The legal description of the land on which the certified feed lot will be situated;

. A complete description of the facilities used for feeding and handling of cattle at each certified feed lot;

. The estimated number of cattle which can be handled for feeding purposes at each certified feed lot; and

. Any other information necessary to carry out the purpose and provisions of this chapter and rules adopted under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5891-S.SL.pdf?cite=2003%20c%20326%20§%2048[2003 c 326 § 48]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c181.pdf?cite=1971%20ex.s.%20c%20181%20§%204[1971 ex.s. c 181 § 4]; ]

== 16.58.050 - Certified feed lot license—Fee—Issuance or renewal—Inspection prior to issuance of original license.
. The application for an annual license to engage in the business of operating one or more certified feed lots shall be accompanied by a license fee of nine hundred thirty-five dollars.

. Upon approval of the application by the director and compliance with the provisions of this chapter and rules adopted under this chapter, the applicant shall be issued a license or license renewal. The director shall conduct an inspection of all cattle and their corresponding ownership documents prior to issuing an original license. The inspection fee is the higher of the current inspection fee per head of cattle or time and mileage as set forth in RCW 16.57.220.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5959-S.SL.pdf?cite=2019%20c%2092%20§%207[2019 c 92 § 7]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5891-S.SL.pdf?cite=2003%20c%20326%20§%2049[2003 c 326 § 49]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2089-S.SL.pdf?cite=1997%20c%20356%20§%205[1997 c 356 § 5]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2089-S.SL.pdf?cite=1997%20c%20356%20§%204[1997 c 356 § 4]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6463-S.SL.pdf?cite=1994%20c%2046%20§%2023[1994 c 46 § 23]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6463-S.SL.pdf?cite=1994%20c%2046%20§%2014[1994 c 46 § 14]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5443-S.SL.pdf?cite=1993%20c%20354%20§%203[1993 c 354 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c81.pdf?cite=1979%20c%2081%20§%202[1979 c 81 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c181.pdf?cite=1971%20ex.s.%20c%20181%20§%205[1971 ex.s. c 181 § 5]; ]

== 16.58.060 - Certified feed lot license—Expiration—Late renewal.
Certified feed lot licenses expire on June 30th following the date of issuance. If a person fails, refuses, or neglects to apply for renewal of a license by June 30th, the person's license shall expire. To reinstate a license, the person shall be assessed a late fee of twenty-five dollars which shall be added to the regular license fee and shall be paid before the director may issue a license to the applicant.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5891-S.SL.pdf?cite=2003%20c%20326%20§%2050[2003 c 326 § 50]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5713-S.SL.pdf?cite=1991%20c%20109%20§%2010[1991 c 109 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c181.pdf?cite=1971%20ex.s.%20c%20181%20§%206[1971 ex.s. c 181 § 6]; ]

== 16.58.070 - Certified feed lot license—Denial, suspension, or revocation—Hearings.
The director is authorized to deny, suspend, or revoke a license in accordance with the provisions of chapter 34.05 RCW if he or she finds that there has been a failure to comply with any requirement of this chapter or rules adopted under this chapter. Hearings for the revocation, suspension, or denial of a license shall be subject to the provisions of chapter 34.05 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5891-S.SL.pdf?cite=2003%20c%20326%20§%2051[2003 c 326 § 51]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c175.pdf?cite=1989%20c%20175%20§%2054[1989 c 175 § 54]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c181.pdf?cite=1971%20ex.s.%20c%20181%20§%207[1971 ex.s. c 181 § 7]; ]

== 16.58.080 - Livestock inspection—Facilities required—Help to be furnished.
Every certified feed lot shall be equipped with a facility or a livestock pen, approved by the director as to location and construction within the feed lot so that necessary livestock inspection can be carried on in a proper, expeditious and safe manner. Each licensee shall furnish the director with sufficient help necessary to carry out inspections in the manner set forth above.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5891-S.SL.pdf?cite=2003%20c%20326%20§%2052[2003 c 326 § 52]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c181.pdf?cite=1971%20ex.s.%20c%20181%20§%208[1971 ex.s. c 181 § 8]; ]

== 16.58.095 - Inspection required for cattle not having inspection certificate.
All cattle entering or reentering a certified feed lot must be inspected upon entry, unless they are accompanied by an inspection certificate issued by the director, or any other agency authorized in any state or Canadian province by law to issue a certificate. Licensees shall report a discrepancy between cattle entering or reentering a certified feed lot and the inspection certificate accompanying the cattle to the nearest inspector immediately. A discrepancy may require an inspection of all the cattle entering or reentering the lot, except as may otherwise be provided by rule.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5891-S.SL.pdf?cite=2003%20c%20326%20§%2053[2003 c 326 § 53]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5713-S.SL.pdf?cite=1991%20c%20109%20§%2011[1991 c 109 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c81.pdf?cite=1979%20c%2081%20§%206[1979 c 81 § 6]; ]

== 16.58.100 - Audits—Purpose.
. The director shall conduct audits of the cattle received, fed, handled, and shipped by the licensee at each certified feed lot. These audits shall be for the purpose of determining if the cattle correlate with the inspection certificates issued in their behalf and that the certificate of assurance furnished the director by the licensee correlates with his or her assurance that inspected cattle were not commingled with uninspected cattle.

. The department shall conduct an audit to determine compliance with RCW 16.36.150 at the time of conducting audits under subsection (1) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1538-S.SL.pdf?cite=2011%20c%20204%20§%204[2011 c 204 § 4]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5891-S.SL.pdf?cite=2003%20c%20326%20§%2054[2003 c 326 § 54]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c81.pdf?cite=1979%20c%2081%20§%203[1979 c 81 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c181.pdf?cite=1971%20ex.s.%20c%20181%20§%2010[1971 ex.s. c 181 § 10]; ]

== 16.58.110 - Records—Contents—Examination.
All certified feed lots shall furnish the director with records as requested by the director on a monthly basis on all cattle entering or on feed in the certified feed lots and dispersed therefrom. These records must include a copy of each inspection certificate received and an itemized listing of all cattle entering and leaving the feed lot. All requested records shall be subject to examination by the director for the purpose of maintaining the integrity of the identity of all the cattle. The director may make the examinations only during regular business hours or any working shift except in an emergency to protect the interest of the owners of the cattle.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5891-S.SL.pdf?cite=2003%20c%20326%20§%2055[2003 c 326 § 55]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5713-S.SL.pdf?cite=1991%20c%20109%20§%2012[1991 c 109 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c181.pdf?cite=1971%20ex.s.%20c%20181%20§%2011[1971 ex.s. c 181 § 11]; ]

== 16.58.120 - Records required at each certified feed lot.
The licensee shall maintain sufficient records as required by the director at each certified feed lot, if said licensee operates more than one certified feed lot.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5713-S.SL.pdf?cite=1991%20c%20109%20§%2013[1991 c 109 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c181.pdf?cite=1971%20ex.s.%20c%20181%20§%2012[1971 ex.s. c 181 § 12]; ]

== 16.58.130 - Feed lots—Fee for each head of cattle handled—Failure to pay. (Effective until July 1, 2023.)
Each licensee shall pay to the director a fee of twenty-eight cents for each head of cattle handled through the licensee's feed lot. The licensee must pay a call out fee of twenty dollars to the department for each day and for each livestock inspector, certified veterinarian, or field livestock inspector who performs inspections at each certified feed lot. Payment of the fees shall be made by the licensee on a monthly basis. Failure to pay as required shall be grounds for suspension or revocation of a certified feed lot license. The director shall not renew a certified feed lot license if a licensee has failed to make prompt and timely payments.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5959-S.SL.pdf?cite=2019%20c%2092%20§%208[2019 c 92 § 8]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6376.SL.pdf?cite=2006%20c%20156%20§%202[2006 c 156 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5891-S.SL.pdf?cite=2003%20c%20326%20§%2056[2003 c 326 § 56]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2089-S.SL.pdf?cite=1997%20c%20356%20§%207[1997 c 356 § 7]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2089-S.SL.pdf?cite=1997%20c%20356%20§%206[1997 c 356 § 6]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6463-S.SL.pdf?cite=1994%20c%2046%20§%2024[1994 c 46 § 24]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6463-S.SL.pdf?cite=1994%20c%2046%20§%2015[1994 c 46 § 15]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5443-S.SL.pdf?cite=1993%20c%20354%20§%204[1993 c 354 § 4]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5713-S.SL.pdf?cite=1991%20c%20109%20§%2014[1991 c 109 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c81.pdf?cite=1979%20c%2081%20§%204[1979 c 81 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c181.pdf?cite=1971%20ex.s.%20c%20181%20§%2013[1971 ex.s. c 181 § 13]; ]

== 16.58.140 - Disposition of fees.
All fees provided for in this chapter shall be deposited in an account in the agricultural local fund and used for enforcing and carrying out the purpose and provisions of this chapter or chapter 16.57 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5891-S.SL.pdf?cite=2003%20c%20326%20§%2057[2003 c 326 § 57]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c81.pdf?cite=1979%20c%2081%20§%205[1979 c 81 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c181.pdf?cite=1971%20ex.s.%20c%20181%20§%2014[1971 ex.s. c 181 § 14]; ]

== 16.58.150 - Situations when no inspection required—Fee—Suspension of license—Hearing.
No inspection shall be required when cattle are moved or transferred from one certified feed lot to another when they are accompanied by satisfactory proof of ownership and there is no change of ownership or from a certified feed lot to a point within this state, or out of state where this state maintains inspection, for the purpose of immediate slaughter. Any change of ownership within a certified feed lot requires a livestock inspection unless the cattle are sent direct to slaughter. An inspection fee as provided for in RCW 16.57.220 is payable to the director by the seller of the cattle or through the licensee as an agent. Upon notice by the director to suspend a license under this section, a person may request a hearing under chapter 34.05 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5891-S.SL.pdf?cite=2003%20c%20326%20§%2058[2003 c 326 § 58]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c181.pdf?cite=1971%20ex.s.%20c%20181%20§%2015[1971 ex.s. c 181 § 15]; ]

== 16.58.160 - Suspension of license awaiting investigation—Hearing.
The director may, when a certified feed lot's conditions become such that the integrity of reports or records of the cattle in that feed lot becomes doubtful, immediately suspend the certified feed lot's license until such time as the director can conduct an investigation to verify the condition of reports or records.

Upon notice by the director to suspend a license under this section, a person may request a hearing under chapter 34.05 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5891-S.SL.pdf?cite=2003%20c%20326%20§%2059[2003 c 326 § 59]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5713-S.SL.pdf?cite=1991%20c%20109%20§%2015[1991 c 109 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c181.pdf?cite=1971%20ex.s.%20c%20181%20§%2016[1971 ex.s. c 181 § 16]; ]

== 16.58.170 - General penalties—Subsequent offenses.
. Except as provided in subsection (2) of this section, any person who violates the provisions of this chapter or any rule adopted under this chapter is guilty of a misdemeanor.

. A second or subsequent violation is a gross misdemeanor. Any offense committed more than five years after a previous conviction shall be considered a first offense.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5891-S.SL.pdf?cite=2003%20c%20326%20§%2060[2003 c 326 § 60]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20115[2003 c 53 § 115]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c181.pdf?cite=1971%20ex.s.%20c%20181%20§%2017[1971 ex.s. c 181 § 17]; ]

== 16.58.900 - Chapter as cumulative and nonexclusive.
The provisions of this chapter shall be cumulative and nonexclusive and shall not affect any other remedy.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c181.pdf?cite=1971%20ex.s.%20c%20181%20§%2018[1971 ex.s. c 181 § 18]; ]

