= 16.68 - Disposal of dead animals.
:toc:

== 16.68.010 - Definitions.
For the purposes of this chapter, unless clearly indicated otherwise by the context:

. "Carcass" means all parts, including viscera, of a dead meat food animal;

. "Dead animal" means the body of a meat food animal, or any part or portion thereof: PROVIDED, That the following dead animals are exempt from the provisions of this chapter:

.. Edible products from a licensed slaughtering establishment;

.. Edible products where the meat food animal was slaughtered under farm slaughter permit;

.. Edible products where the meat food animal was slaughtered by a bona fide farmer on his or her own ranch for his or her own consumption;

.. Hides from meat food animals that are properly identified as to ownership and brands;

. "Director" means the director of agriculture;

. "Independent collector" means any person who does not own a licensed rendering plant within the state of Washington but is properly equipped and licensed to transport dead animals or packing house refuse to a specified rendering plant.

. "Meat food animal" means cattle, horses, mules, asses, swine, sheep, and goats;

. "Person" means any individual, firm, corporation, partnership, or association;

. "Place of transfer" means an authorized reloading site for the direct transfer of dead animals or packing house refuse from the vehicle making original pickup to the line vehicle that will transport the dead animals or packing house refuse to a specified licensed rendering plant;

. "Rendering plant" means any place of business or location where dead animals or any part or portion thereof, or packing house refuse, are processed for the purpose of obtaining the hide, skin, grease residue, or any other by-product whatsoever;

. "Substation" means a properly equipped and authorized concentration site for the temporary storage of dead animals or packing house refuse pending final delivery to a licensed rendering plant.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20438[2011 c 336 § 438]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c100.pdf?cite=1949%20c%20100%20§%201[1949 c 100 § 1]; Rem. Supp. 1949 § 3142-1; ]

== 16.68.030 - Sale, gift, or conveyance prohibited—Exceptions.
It is unlawful for any person to sell, offer for sale, or give away a dead animal or convey the same along any public road or land not his or her own: PROVIDED, That dead animals may be sold or given away to and legally transported on highways by a person having an unrevoked, annual license to operate a rendering plant or by a person having an unrevoked, annual license to operate as an independent collector.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20439[2011 c 336 § 439]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c100.pdf?cite=1949%20c%20100%20§%203[1949 c 100 § 3]; Rem. Supp. 1949 § 3142-3; ]

== 16.68.040 - License required of rendering plants and independent collectors.
It is unlawful for any person to operate a rendering plant or act as an independent collector without first obtaining a license from the director.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c100.pdf?cite=1949%20c%20100%20§%204[1949 c 100 § 4]; Rem. Supp. 1949 § 3142-4; ]

== 16.68.050 - Rendering plant license fee.
Any person engaged in operating a rendering plant shall secure from the director an annual rendering plant license and pay an annual fee of one hundred dollars: PROVIDED, That no license shall be required to operate a rendering plant on the premises of a licensed slaughtering establishment maintaining state or federal meat inspection unless said rendering plant receives dead animals that have been transported on public highways.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c100.pdf?cite=1949%20c%20100%20§%205[1949 c 100 § 5]; Rem. Supp. 1949 § 3142-5; ]

== 16.68.060 - Independent collector license fee.
Any person engaged in the business of independent collector shall secure from the director an annual independent collector license and pay an annual fee of fifty dollars.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c100.pdf?cite=1949%20c%20100%20§%206[1949 c 100 § 6]; Rem. Supp. 1949 § 3142-6; ]

== 16.68.070 - Substation or places of transfer license fee.
Any rendering plant operator or independent collector that operates substations or places of transfer shall secure from the director an annual substation license or place of transfer license and pay an annual fee of twenty-five dollars for each substation or place of transfer.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c100.pdf?cite=1949%20c%20100%20§%207[1949 c 100 § 7]; Rem. Supp. 1949 § 3142-7; ]

== 16.68.080 - Expiration of license—Revocation.
Any license or permit issued under this chapter shall expire on the thirtieth day of June next subsequent to the date of issue, and may be sooner revoked by the director or his or her authorized representative for violations of this chapter. Any licensee or permittee under this chapter shall have the right to demand a hearing before the director before a revocation is made permanent.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20440[2011 c 336 § 440]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c100.pdf?cite=1949%20c%20100%20§%208[1949 c 100 § 8]; Rem. Supp. 1949 § 3142-8; ]

== 16.68.090 - Applications for license.
Any person applying for a license to operate a rendering plant and/or substation and/or place of transfer, or to act as an independent collector shall make application on forms furnished by the director. Said application shall give all information required by the director and shall be accompanied by the required license fee.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c100.pdf?cite=1949%20c%20100%20§%209[1949 c 100 § 9]; Rem. Supp. 1949 § 3142-9; ]

== 16.68.100 - Procedure upon application—Inspection of premises.
If the director finds that the locations, buildings, substations equipment, vehicles, places of transfer, or proposed method of operation do not fully comply with the requirements of this chapter, he or she shall notify the applicant by registered letter wherein the same fails to comply. If the applicant whose plant or operation failed to comply notifies the director within ten days from the receipt of the registered letter that he or she will discontinue operations, the fee accompanying the application will be returned to him or her; otherwise no part of the fee will be refunded. If the applicant whose plant failed to comply within a reasonable time, to be fixed by the director or his or her authorized representative, notifies the director that such defects are remedied, a second inspection shall be made. Not more than two inspections may be made on one application.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20441[2011 c 336 § 441]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c100.pdf?cite=1949%20c%20100%20§%2010[1949 c 100 § 10]; Rem. Supp. 1949 § 3142-10; ]

== 16.68.110 - Duty of licensees as to premises.
Every licensee under this chapter must comply with the following:

. All floors shall be constructed of concrete or other impervious material, shall be kept reasonably clean and in good repair. Floors shall slope at least one-fourth inch to the foot toward drains, and slope at least three-eighths inch to the foot as the drains are approached.

. Adequate sanitary drainage must be provided leading to approved grease traps and approved sewage disposal system. No point on the floor shall be over sixteen feet from a drain.

. Suitable disposal of paunch contents must be provided in accordance with sanitary regulations.

. Walls shall be of impervious material to a height not less than six feet from the floor with a tight union with the floor.

. Potable water supply shall be provided for human consumption, washing, and cleaning.

. Ample steam shall be provided for cleaning purposes.

. Approved toilet and dressing room facilities must be provided for employees.

. The building must be kept free from flies, rats, mice, and cockroaches.

. Premises must be kept neat and orderly and all buildings must be attractive in appearance.

. All rendering plants, substations, and places of transfer shall be so located, arranged, constructed, and maintained, and the operation so conducted at all times as to be consistent with public health and safety.

. Suitable facilities for the dipping, washing, and disinfecting of hides obtained from animals that died or were killed on account of an infectious or contagious disease, shall be provided.

. Two copies of building or remodeling plans shall be forwarded to the director for his or her approval before such building or remodeling is begun.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20442[2011 c 336 § 442]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c100.pdf?cite=1949%20c%20100%20§%2012[1949 c 100 § 12]; Rem. Supp. 1949 § 3142-12; ]

== 16.68.120 - Duty of licensees—Standards.
Every licensee under this chapter shall comply with the following:

. Dead animals shall be placed in containers or vehicles which are constructed of or lined with impervious material, and which do not permit the escape of any liquid, and which are covered in such a way that the contents shall not be openly exposed to insects.

. All vehicles and containers used for transporting dead animals shall be properly cleaned and disinfected before leaving the premises of a rendering plant, substation or place of transfer.

. After original loading, dead animals shall not be moved from the transporting container or vehicle upon a public highway or in any other place, except at a licensed rendering plant, licensed substation, or licensed place of transfer.

. No containers and vehicles used for transporting dead animals shall be used for the transporting of live animals except to a licensed rendering plant.

. All vehicles used to haul dead animals that have died of an infectious or contagious disease, shall proceed directly to the unloading point and shall not enter other premises until the vehicle has been properly cleaned and disinfected.

. The name of the rendering plant or independent collector shall be painted in letters at least four inches high on each side of every truck used for transporting dead animals.

. The skinning and dismembering of dead animals shall be done in the building where they are processed.

. Cooking vats or tanks shall be airtight except for proper escape for steam or vapor.

. Steam or vapor from cooking vats or tanks shall be so disposed of as not to be detrimental to public health or safety.

. Dead animals shall be processed within forty-eight hours after delivery to the rendering plant.

. No carcasses, parts thereof, or packing house refuse under process for marketing shall be permitted to come in contact with any part of the building or the equipment used in connection with the unloading, skinning, dismembering and grinding of carcasses or refuse as originally received at disposal plant.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c100.pdf?cite=1949%20c%20100%20§%2013[1949 c 100 § 13]; Rem. Supp. 1949 § 3142-13; ]

== 16.68.130 - Right of access to premises and records.
The director or his or her authorized agent, shall have free and uninterrupted access to all parts of premises that come under the provisions of this chapter, for the purpose of making inspections and the examination of records.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20443[2011 c 336 § 443]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c100.pdf?cite=1949%20c%20100%20§%2014[1949 c 100 § 14]; Rem. Supp. 1949 § 3142-14; ]

== 16.68.140 - Unlawful possession of horse meat—Exceptions.
It shall be unlawful for any person to transport, to sell, offer to sell, or have on his or her premises horse meat for other than human consumption unless said horse meat is decharacterized in a manner prescribed by the director: PROVIDED, That this provision shall not apply to carcasses slaughtered by a farmer for consumption on his or her own ranch or to carcasses in the possession of a person licensed under this chapter, or to canned horse meat meeting United States bureau of animal industry regulations.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20444[2011 c 336 § 444]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c100.pdf?cite=1949%20c%20100%20§%2015[1949 c 100 § 15]; Rem. Supp. 1949 § 3142-18; ]

== 16.68.150 - Feeding of carcasses to swine unlawful—Exception.
It shall be unlawful to feed carcasses of animals, or any part or portion thereof, to swine, unless said carcasses or portions thereof are cooked in a manner prescribed by the director.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c100.pdf?cite=1949%20c%20100%20§%2016[1949 c 100 § 16]; Rem. Supp. 1949 § 3142-20; ]

== 16.68.160 - Disposition of fees.
Funds collected for license fees and inspection fees shall be retained by the director to be used for the enforcement of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c100.pdf?cite=1949%20c%20100%20§%2011[1949 c 100 § 11]; Rem. Supp. 1949 § 3142-11; ]

== 16.68.170 - Rules and regulations.
The director is authorized and shall make and enforce such regulations as may be necessary to effectuate the provisions of this chapter. Such regulations shall be consistent with the provisions of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c100.pdf?cite=1949%20c%20100%20§%2017[1949 c 100 § 17]; Rem. Supp. 1949 § 3142-21; ]

== 16.68.180 - Penalty for violations.
The violation of any provision of this chapter shall be a misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c100.pdf?cite=1949%20c%20100%20§%2018[1949 c 100 § 18]; Rem. Supp. 1949 § 3142-22; ]

== 16.68.190 - Bait for trapping purposes—Exception.
Nothing in this chapter shall prohibit the department of fish and wildlife from using the carcasses of dead animals for trap bait in their regular trapping operations.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2590.SL.pdf?cite=1994%20c%20264%20§%206[1994 c 264 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c36.pdf?cite=1988%20c%2036%20§%207[1988 c 36 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c100.pdf?cite=1949%20c%20100%20§%2018A[1949 c 100 § 18A]; Rem. Supp. 1949 § 3142-23; ]

