= 16.70 - Control of pet animals infected with diseases communicable to humans.
:toc:

== 16.70.010 - Purpose.
The incidence of disease communicated to human beings by contact with pet animals has shown an increase in the past few years. The danger to human beings from such pets infected with disease communicable to humans has demonstrated the necessity for legislation to authorize the secretary of the department of health and the state board of health to take such action as is necessary to control the sale, importation, movement, transfer, or possession of such animals where it becomes necessary in order to protect the public health and welfare.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%202[1991 c 3 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971c72.pdf?cite=1971%20c%2072%20§%201[1971 c 72 § 1]; ]

== 16.70.020 - Definitions.
The following words or phrases as used in this chapter shall have the following meanings unless the context indicates otherwise:

. "Pet animals" means dogs (Canidae), cats (Felidae), monkeys and other similar primates, turtles, psittacine birds, skunks, or any other species of wild or domestic animals sold or retained for the purpose of being kept as a household pet.

. "Secretary" means the secretary of the department of health or his or her designee.

. "Department" means the department of health.

. "Board" means the Washington state board of health.

. "Person" means an individual, group of individuals, partnership, corporation, firm, or association.

. "Quarantine" means the placing and restraining of any pet animal or animals by direction of the secretary, either within a certain described and designated enclosure or area within this state, or the restraining of any such pet animal or animals from entering this state.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%203[1991 c 3 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971c72.pdf?cite=1971%20c%2072%20§%202[1971 c 72 § 2]; ]

== 16.70.030 - Emergency action authorized—Scope—Animals as public nuisance.
In the event of an emergency arising out of an outbreak of communicable disease caused by exposure to or contact with pet animals, the secretary is hereby authorized to take any reasonable action deemed necessary by him or her to protect the public health, including but not limited to the use of quarantine or the institution of any legal action authorized pursuant to Title 7 RCW and RCW 43.70.170, 43.70.180, and 43.70.190.

The secretary shall have authority to destroy any pet animal or animals which may reasonably be suspected of having a communicable disease dangerous to humans and such animal or animals are hereby declared to be a public nuisance.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20445[2011 c 336 § 445]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971c72.pdf?cite=1971%20c%2072%20§%203[1971 c 72 § 3]; ]

== 16.70.040 - Rules—Scope.
. The secretary, with the advice and concurrence of the director of the department of agriculture, shall be authorized to develop rules for proposed adoption by the board relating to the importation, movement, sale, transfer, or possession of pet animals as defined in RCW 16.70.020 which are reasonably necessary for the protection and welfare of the people of this state.

. The director of the department of agriculture shall also be authorized to adopt rules to allow administration of permits for those pet animals under subsection (1) of this section by the state veterinarian.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2132.SL.pdf?cite=1996%20c%20188%20§%205[1996 c 188 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971c72.pdf?cite=1971%20c%2072%20§%204[1971 c 72 § 4]; ]

== 16.70.050 - Violations—Penalty.
Any person violating or refusing or neglecting to obey the order or directive issued by the secretary pursuant to the authority granted under this action [act] or the rules and regulations promulgated by the board hereunder shall be guilty of a misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971c72.pdf?cite=1971%20c%2072%20§%205[1971 c 72 § 5]; ]

== 16.70.060 - Concurrent powers—Cooperation between officials.
The powers conferred on the secretary by this chapter shall be concurrent with the powers conferred on the director of the department of agriculture by chapter 16.36 RCW, and chapter 43.23 RCW, and the secretary and director shall cooperate in exercising their responsibilities in these areas.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971c72.pdf?cite=1971%20c%2072%20§%206[1971 c 72 § 6]; ]

