= 14.16 - Aircraft and airman regulations.
:toc:

== 14.16.010 - Definitions.
In this chapter "aircraft" means any contrivance now known or hereafter invented, used, or designed for navigation of or flight in the air, except a parachute or other contrivance designed for such navigation but used primarily as safety equipment. The term "airman" or "airwoman" means any individual (including the person in command and any pilot, mechanic, or member of the crew) who engages in the navigation of aircraft while under way and any individual who is in charge of the inspection, overhauling, or repairing of aircraft. "Operating aircraft" means performing the services of aircraft pilot. "Person" means any individual, proprietorship, partnership, corporation, or trust. "Downed aircraft rescue transmitter" means a transmitter of a type approved by the state department of transportation or the federal aviation administration with sufficient transmission power and reliability that it will be automatically activated upon the crash of an aircraft so as to transmit a signal on a preset frequency so that it will be effective to assist in the location of the downed aircraft. "Air school" means air school as defined in *RCW 47.68.020(11).

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%205006[2010 c 8 § 5006]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%208[1984 c 7 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c205.pdf?cite=1969%20ex.s.%20c%20205%20§%201[1969 ex.s. c 205 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c157.pdf?cite=1929%20c%20157%20§%201[1929 c 157 § 1]; RRS § 2722-1; ]

== 14.16.020 - Federal licensing of aircraft required.
The public safety requiring and the advantages of uniform regulation making it desirable in the interest of aeronautical progress that aircraft operating within this state should conform with respect to design, construction, and airworthiness to the standards prescribed by the United States government with respect to navigation of aircraft subject to its jurisdiction, it shall be unlawful for any person to navigate any aircraft within this state unless it is licensed and registered by the department of commerce of the United States in the manner prescribed by the lawful rules and regulations of the United States government then in force: PROVIDED, HOWEVER, That for the first thirty days after entrance into this state this section shall not apply to aircraft owned by a nonresident of this state other than aircraft carrying persons or property for hire, if such aircraft is licensed and registered and displays identification marks in compliance with the laws of the state, territory or foreign country of which its owner is a resident.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c157.pdf?cite=1929%20c%20157%20§%202[1929 c 157 § 2]; RRS § 2722-2; ]

== 14.16.030 - Federal licensing of airmen or airwomen.
The public safety requiring and the advantages of uniform regulation making it desirable in the interest of aeronautical progress that a person serving as an airman or airwoman within this state should have the qualifications necessary for obtaining and holding the class of license required by the United States government with respect to such an airman or airwoman subject to its jurisdiction, it shall be unlawful for any person to serve as an airman or airwoman within this state unless he or she has such a license: PROVIDED, HOWEVER, That for the first thirty days after entrance into this state this section shall not apply to nonresidents of this state operating aircraft within this state, other than aircraft carrying persons or property for hire, if such person shall have fully complied with the laws of the state, territory or foreign country of his or her residence respecting the licensing of airmen or airwomen.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%205007[2010 c 8 § 5007]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c157.pdf?cite=1929%20c%20157%20§%203[1929 c 157 § 3]; RRS § 2722-3; ]

== 14.16.040 - Possession of license.
The certificate of the license herein required shall be kept in the personal possession of the licensee when he or she is serving as an airman or airwoman within this state, and must be presented for inspection upon the demand of any passenger, any peace officer of this state, or any official, manager, or person in charge of any airport or landing field in this state upon which he or she shall land.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%205008[2010 c 8 § 5008]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c157.pdf?cite=1929%20c%20157%20§%204[1929 c 157 § 4]; RRS § 2722-4; ]

== 14.16.050 - Traffic rules.
The public safety requiring and the advantages of uniform regulation making it desirable in the interest of aeronautical progress that any person operating aircraft within this state should conform to the air traffic rules now or hereafter established by the secretary of commerce of the United States for the navigation of aircraft subject to the jurisdiction of the United States, it shall be unlawful for any person to navigate any aircraft within this state otherwise than in conformity with said air traffic rules.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c157.pdf?cite=1929%20c%20157%20§%205[1929 c 157 § 5]; RRS § 2722-5; ]

== 14.16.060 - Penalty.
Any person who violates any provision of this chapter shall be guilty of an offense punishable by a fine of not exceeding five hundred dollars or by imprisonment not exceeding six months, or by both such fine and imprisonment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c157.pdf?cite=1929%20c%20157%20§%206[1929 c 157 § 6]; RRS § 2722-6; ]

== 14.16.080 - Downed aircraft rescue transmitter required—Exceptions.
Any aircraft used to carry persons or property for compensation, or any aircraft that is rented or leased without a pilot, shall be equipped with a fully functional downed aircraft rescue transmitter and it shall be unlawful for any person to operate such aircraft without such a transmitter: PROVIDED, HOWEVER, Nothing in this section shall apply to (1) instructional flights by an air school, with the exception of solo flights by students; (2) aircraft owned by and used exclusively in the service of the United States government; (3) aircraft registered under the laws of a foreign country; (4) aircraft owned by the manufacturer thereof while being operated for test or experimental purposes, or for the purpose of training crews for purchasers of the aircraft; and (5) aircraft used by any air carrier or supplemental air carrier operating in accordance with the provisions of a certificate of public conveyance and necessity under the provisions of the Federal Aviation Act of 1958, Public Law 85-726, as amended.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c273.pdf?cite=1987%20c%20273%20§%201[1987 c 273 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c205.pdf?cite=1969%20ex.s.%20c%20205%20§%202[1969 ex.s. c 205 § 2]; ]

== 14.16.090 - Certain aircraft to carry survival kit—Contents—Misdemeanor to operate without—Exceptions.
. Any aircraft used to carry persons or property for compensation, or any aircraft that is rented or leased without a pilot shall be equipped with a survival kit consisting of those items prescribed by the department of transportation, which shall include, at least the following: (a) A tube tent or similar sheltering device; (b) a horn, whistle, or similar audible device capable of emitting a signal one-quarter of a mile; (c) a mirror; (d) matches; (e) a candle and/or another fire-starting device; and (f) survival instruction.

. It shall be unlawful for any person to operate such aircraft without such a survival kit: PROVIDED, HOWEVER, That nothing in this section shall apply to: (a) Instructional flights by an air school, with the exception of solo flights by students; (b) aircraft owned by and exclusively in the service of the United States government; (c) aircraft registered under the laws of a foreign country; (d) aircraft owned by the manufacturer thereof while being operated for test or experimental purposes, or for the purpose of training crews for purchasers of the aircraft; and (e) aircraft used by any air carrier or supplemental air carrier operating in accordance with the provisions of a certificate of public conveyance and necessity under the provisions of the federal aviation act of 1958, Public Law 85-726, as amended.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c273.pdf?cite=1987%20c%20273%20§%202[1987 c 273 § 2]; ]

== 14.16.100 - Guyed towers—Requirements—Definitions—Application of section—Penalty.
. Except as provided otherwise in this section, a guyed tower twenty-five feet or more in height that is located outside the boundaries of an incorporated city or town on land that is primarily rural or undeveloped or used for agricultural purposes, or that is primarily desert, and where such guyed tower's appearance is not otherwise governed by state or federal law, rule, or regulation, is subject to the following requirements:

.. The tower must be painted in five foot high alternating bands of aviation orange and white.

.. The tower must have a flashing light at the top of the tower. The light must be visible in clear air from a distance of two thousand feet when flashing. Such a light must also be visible with night vision goggles.

.. The surface area under the footprint of the tower and the circular area surrounding each outer tower anchor, with a radius of six feet, should have a contrasting appearance with any surrounding vegetation.

.. Two marker balls must be attached to and evenly spaced on each of the outside guy wires.

.. The tower must have a seven foot long safety sleeve at each anchor point and must extend from the anchor point along each guy wire attached to the anchor point.

. Any guyed tower that was erected prior to June 12, 2014, must be modified as required under this section within one year of June 12, 2014.

. The definitions in this subsection apply throughout this section unless the context clearly requires otherwise.

.. "Guyed tower" means a tower that is supported in whole or in part by guy wires and ground anchors or other means of support besides the superstructure of the tower itself.

.. "Height" means the distance measured from the original grade at the base of the tower to the highest point of the tower.

. This section does not apply to:

.. Guyed towers used for military purposes;

.. Power poles or nonguyed tower structures owned and operated by an electric utility as defined in RCW 80.80.010;

.. Any structure for which the primary purpose is to support telecommunications equipment, such as equipment for amateur radio and broadcast radio and television services regulated by the federal communications commission;

.. Any guyed tower that is within fifty feet of a structure or vegetation of equal or greater height; and

.. Any guyed tower that is attached to a large mobile motorized machine with a large visible base equipped with wheels, tracks, or skids and with winches and utilized to lift or pull heavy loads, such as a tower used to yard logs.

. A person who violates a provision of this section is guilty of a misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6054-S.SL.pdf?cite=2014%20c%20134%20§%202[2014 c 134 § 2]; ]

