= 72.06 - Mental health.
:toc:

== 72.06.010 - "Department" defined.
"Department" for the purposes of this chapter shall mean the department of social and health services.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c18.pdf?cite=1970%20ex.s.%20c%2018%20§%2059[1970 ex.s. c 18 § 59]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c28.pdf?cite=1959%20c%2028%20§%2072.06.010[1959 c 28 § 72.06.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c272.pdf?cite=1957%20c%20272%20§%209[1957 c 272 § 9]; ]

== 72.06.050 - Mental health—Dissemination of information and advice by department.
The department shall cooperate with other departments of state government and its political subdivisions in the following manner:

. By disseminating educational information relating to the prevention, diagnosis and treatment of mental illness.

. Upon request therefor, by advising public officers, organizations and agencies interested in the mental health of the people of the state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c80.pdf?cite=1977%20ex.s.%20c%2080%20§%2046[1977 ex.s. c 80 § 46]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c28.pdf?cite=1959%20c%2028%20§%2072.06.050[1959 c 28 § 72.06.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c136.pdf?cite=1955%20c%20136%20§%202[1955 c 136 § 2]; ]

== 72.06.060 - Mental health—Psychiatric outpatient clinics.
The department is hereby authorized to establish and maintain psychiatric outpatient clinics at such of the several state mental institutions as the secretary shall designate for the prevention, diagnosis and treatment of mental illnesses, and the services of such clinics shall be available to any citizen of the state in need thereof, when determined by a physician that such services are not otherwise available, subject to the rules of the department.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20185[1979 c 141 § 185]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c80.pdf?cite=1977%20ex.s.%20c%2080%20§%2047[1977 ex.s. c 80 § 47]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c28.pdf?cite=1959%20c%2028%20§%2072.06.060[1959 c 28 § 72.06.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c136.pdf?cite=1955%20c%20136%20§%203[1955 c 136 § 3]; ]

== 72.06.070 - Mental health—Cooperation of department and state hospitals with local programs.
The department and the several state hospitals for the mentally ill shall cooperate with local mental health programs by providing necessary information, recommendations relating to proper aftercare for patients paroled or discharged from such institutions and shall also supply the services of psychiatrists, psychologists and other persons specialized in mental illness as they are available.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c28.pdf?cite=1959%20c%2028%20§%2072.06.070[1959 c 28 § 72.06.070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c136.pdf?cite=1955%20c%20136%20§%204[1955 c 136 § 4]; ]

