= 72.02 - Adult corrections.
:toc:

== 72.02.015 - Powers of court or judge not impaired.
Nothing in this chapter shall be construed to restrict or impair the power of any court or judge having jurisdiction to pronounce sentence upon a person to whom this chapter applies, to fix the term of imprisonment and to order commitment, according to law, nor to deny the right of any such court or judge to sentence to imprisonment; nor to deny the right of any such court or judge to suspend sentence or the execution of judgment thereon or to make any other disposition of the case pursuant to law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c143.pdf?cite=1988%20c%20143%20§%209[1988 c 143 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c214.pdf?cite=1959%20c%20214%20§%2013[1959 c 214 § 13]; ]

== 72.02.040 - Secretary acting for department exercises powers and duties.
The secretary of corrections acting for the department of corrections shall exercise all powers and perform all duties prescribed by law with respect to the administration of any adult correctional program by the department of corrections.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c136.pdf?cite=1981%20c%20136%20§%2079[1981 c 136 § 79]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c18.pdf?cite=1970%20ex.s.%20c%2018%20§%2057[1970 ex.s. c 18 § 57]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c28.pdf?cite=1959%20c%2028%20§%2072.02.040[1959 c 28 § 72.02.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c272.pdf?cite=1957%20c%20272%20§%2016[1957 c 272 § 16]; ]

== 72.02.045 - Superintendent's authority.
The superintendent of each institution has the powers, duties, and responsibilities specified in this section.

. Subject to the rules of the department, the superintendent is responsible for the supervision and management of the institution, the grounds and buildings, the subordinate officers and employees, and the prisoners committed, admitted, or transferred to the institution.

. Subject to the rules of the department and the director of the division of prisons or his or her designee and the Washington personnel resources board, the superintendent shall appoint all subordinate officers and employees.

. The superintendent, subject to approval by the secretary, has the authority to determine the types and amounts of property that convicted persons may possess in department facilities. This authority includes the authority to determine the types and amounts that the department will transport at the department's expense whenever a convicted person is transferred between department institutions or to other jurisdictions. Convicted persons are responsible for the costs of transporting their excess property. If a convicted person fails to pay the costs of transporting any excess property within ninety days from the date of transfer, such property shall be presumed abandoned and may be disposed of in the manner allowed by RCW 63.42.040 (1) through (3). The superintendent shall be the custodian of all funds and valuable personal property of convicted persons as may be in their possession upon admission to the institution, or which may be sent or brought in to such persons, or earned by them while in custody, or which shall be forwarded to the superintendent on behalf of convicted persons. All such funds shall be deposited in the personal account of the convicted person and the superintendent shall have authority to disburse moneys from such person's personal account for the personal and incidental needs of the convicted person as may be deemed reasonably necessary. When convicted persons are released from the custody of the department either on parole, community placement, community custody, community supervision, or discharge, all funds and valuable personal property in the possession of the superintendent belonging to such convicted persons shall be delivered to them. In no case shall the state of Washington, or any state officer, including state elected officials, employees, or volunteers, be liable for the loss of such personal property, except upon a showing that the loss was occasioned by the intentional act, gross negligence, or negligence of the officer, official, employee, or volunteer, and that the actions or omissions occurred while the person was performing, or in good faith purporting to perform, his or her official duties. Recovery of damages for loss of personal property while in the custody of the superintendent under this subsection shall be limited to the lesser of the market value of the item lost at the time of the loss, or the original purchase price of the item or, in the case of hand-made goods, the materials used in fabricating the item.

. The superintendent, subject to the approval of the director of the division of prisons and the secretary, shall make, amend, and repeal rules for the administration, supervision, discipline, and security of the institution.

. When in the superintendent's opinion an emergency exists, the superintendent may promulgate temporary rules for the governance of the institution, which shall remain in effect until terminated by the director of the division of prisons or the secretary.

. The superintendent shall perform such other duties as may be prescribed.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2282.SL.pdf?cite=2005%20c%20382%20§%201[2005 c 382 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2054-S.SL.pdf?cite=1993%20c%20281%20§%2063[1993 c 281 § 63]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c143.pdf?cite=1988%20c%20143%20§%202[1988 c 143 § 2]; ]

== 72.02.055 - Appointment of associate superintendents.
The superintendent, subject to the approval of the director of the division of prisons and the secretary, shall appoint such associate superintendents as shall be deemed necessary, who shall have such qualifications as shall be determined by the secretary. In the event the superintendent is absent from the institution, or during periods of illness or other situations incapacitating the superintendent from properly performing his or her duties, one of the associate superintendents of such institution as may be designated by the director of the division of prisons and the secretary shall act as superintendent.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c143.pdf?cite=1988%20c%20143%20§%203[1988 c 143 § 3]; ]

== 72.02.100 - Earnings, clothing, transportation, subsistence payments, and rental vouchers upon release of certain prisoners.
. Any person serving a sentence for a term of confinement in a state correctional facility for convicted felons, pursuant to court commitment, who is thereafter released upon an order of parole of the indeterminate sentence review board, or who is discharged from custody upon expiration of sentence, or who is ordered discharged from custody by a court of appropriate jurisdiction, shall be entitled to retain his or her earnings from labor or employment while in confinement and shall be supplied by the superintendent of the state correctional facility with suitable and presentable clothing, the sum of forty dollars for subsistence, and transportation by the least expensive method of public transportation not to exceed the cost of one hundred dollars to his or her place of residence or the place designated in his or her parole plan, or to the place from which committed if such person is being discharged on expiration of sentence, or discharged from custody by a court of appropriate jurisdiction: PROVIDED, That up to sixty additional dollars may be made available to the parolee for necessary personal and living expenses upon application to and approval by such person's community corrections officer. If in the opinion of the superintendent suitable arrangements have been made to provide the person to be released with suitable clothing and/or the expenses of transportation, the superintendent may consent to such arrangement. If the superintendent has reasonable cause to believe that the person to be released has ample funds, with the exception of earnings from labor or employment while in confinement, to assume the expenses of clothing, transportation, or the expenses for which payments made pursuant to this section or RCW 72.02.110 or any one or more of such expenses, the person released shall be required to assume such expenses.

. Within existing resources, the department of corrections may provide temporary housing assistance for a person being released from the Washington corrections center for women or mission creek corrections center for women through the use of rental vouchers, for a period not to exceed three months, if such assistance will support the person's release into the community. The department's authority to provide vouchers under this section is independent of its authority under RCW 9.94A.729.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2017%20c%20214%20§%201[2017 c 214 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20455[2012 c 117 § 455]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c143.pdf?cite=1988%20c%20143%20§%205[1988 c 143 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c171.pdf?cite=1971%20ex.s.%20c%20171%20§%201[1971 ex.s. c 171 § 1]; ]

== 72.02.110 - Weekly payments to certain released prisoners.
As state, federal or other funds are available, the secretary of corrections or his or her designee is authorized, in his or her discretion, not to provide the forty dollars subsistence money or the optional sixty dollars to a person or persons released as described in RCW 72.02.100, and instead to utilize the authorization and procedure contained in this section relative to such person or persons.

Any person designated by the secretary serving a sentence for a term of confinement in a state correctional facility for convicted felons, pursuant to court commitment, who is thereafter released upon an order of parole of the indeterminate sentence review board, or is discharged from custody upon expiration of sentence, or is ordered discharged from custody by a court of appropriate jurisdiction, shall receive the sum of fifty-five dollars per week for a period of up to six weeks. The initial weekly payment shall be made to such person upon his or her release or parole by the superintendent of the institution. Subsequent weekly payments shall be made to such person by the community corrections officer at the office of such officer. In addition to the initial six weekly payments provided for in this section, a community corrections officer and his or her supervisor may, at their discretion, continue such payments up to a maximum of twenty additional weeks when they are satisfied that such person is actively seeking employment and that such payments are necessary to continue the efforts of such person to gain employment: PROVIDED, That if, at the time of release or parole, in the opinion of the superintendent funds are otherwise available to such person, with the exception of earnings from labor or employment while in confinement, such weekly sums of money or part thereof shall not be provided to such person.

When a person receiving such payments provided for in this section becomes employed, he or she may continue to receive payments for two weeks after the date he or she becomes employed but payments made after he or she becomes employed shall be discontinued as of the date he or she is first paid for such employment: PROVIDED, That no person shall receive payments for a period exceeding the twenty-six week maximum as established in this section.

The secretary of corrections may annually adjust the amount of weekly payment provided for in this section to reflect changes in the cost of living and the purchasing power of the sum set for the previous year.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20456[2012 c 117 § 456]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c143.pdf?cite=1988%20c%20143%20§%206[1988 c 143 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c136.pdf?cite=1981%20c%20136%20§%2080[1981 c 136 § 80]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c171.pdf?cite=1971%20ex.s.%20c%20171%20§%202[1971 ex.s. c 171 § 2]; ]

== 72.02.150 - Disturbances at state penal facilities—Development of contingency plans—Scope—Local participation.
The secretary or the secretary's designee shall be responsible for the preparation of contingency plans for dealing with disturbances at state penal facilities. The plans shall be developed or revised in cooperation with representatives of state and local agencies at least annually. Contingency plans developed shall encompass contingencies of varying levels of severity, specific contributions of personnel and material from participating agencies, and a unified chain of command. Agencies providing personnel under the plan shall provide commanders for the personnel who will be included in the unified chain of command.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c49.pdf?cite=1982%20c%2049%20§%201[1982 c 49 § 1]; ]

== 72.02.160 - Disturbances at state penal facilities—Utilization of outside law enforcement personnel—Scope.
Whenever the secretary or the secretary's designee determines that due to a disturbance at a state penal facility within the jurisdiction of the department that the assistance of law enforcement officers in addition to department of corrections' personnel is required, the secretary may notify the Washington state patrol, the chief law enforcement officer of any nearby county and the county in which the facility is located, and the chief law enforcement officer of any municipality near the facility or in which the facility is located. These law enforcement agencies may provide such assistance as expressed in the contingency plan or plans, or as is deemed necessary by the secretary, or the secretary's designee, to restore order at the facility, consistent with the resources available to the law enforcement agencies and the law enforcement agencies' other statutory obligations. While on the grounds of a penal facility and acting under this section, all law enforcement officials shall be under the immediate control of their respective supervisors who shall be responsive to the secretary, or the secretary's designee, which designee need not be an employee of the department of corrections.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c49.pdf?cite=1982%20c%2049%20§%202[1982 c 49 § 2]; ]

== 72.02.200 - Reception and classification units.
There shall be units known as reception and classification centers which, subject to the rules and regulations of the department, shall be charged with the function of receiving and classifying all persons committed or transferred to the institution, taking into consideration age, type of crime for which committed, physical condition, behavior, attitude and prospects for reformation for the purposes of confinement and treatment of offenders convicted of offenses punishable by imprisonment, except offenders convicted of crime and sentenced to death.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c143.pdf?cite=1988%20c%20143%20§%207[1988 c 143 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c214.pdf?cite=1959%20c%20214%20§%2011[1959 c 214 § 11]; ]

== 72.02.210 - Sentence—Commitment to reception units.
Any offender convicted of an offense punishable by imprisonment, except an offender sentenced to death, shall, notwithstanding any inconsistent provision of law, be sentenced to imprisonment in a penal institution under the jurisdiction of the department without designating the name of such institution, and be committed to the reception units for classification, confinement and placement in such correctional facility under the supervision of the department as the secretary shall deem appropriate.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c143.pdf?cite=1988%20c%20143%20§%208[1988 c 143 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c136.pdf?cite=1981%20c%20136%20§%2095[1981 c 136 § 95]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20206[1979 c 141 § 206]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c214.pdf?cite=1959%20c%20214%20§%2012[1959 c 214 § 12]; ]

== 72.02.220 - Cooperation with reception units by state agencies.
The indeterminate sentence review board and other state agencies shall cooperate with the department in obtaining necessary investigative materials concerning offenders committed to the reception unit and supply the reception unit with necessary information regarding social histories and community background.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c143.pdf?cite=1988%20c%20143%20§%2010[1988 c 143 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20207[1979 c 141 § 207]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c214.pdf?cite=1959%20c%20214%20§%2014[1959 c 214 § 14]; ]

== 72.02.230 - Persons to be received for classification and placement.
The division of prisons shall receive all persons convicted of a felony by the superior court and committed by the superior court to the reception units for classification and placement in such facility as the secretary shall designate. The superintendent of these institutions shall only receive prisoners for classification and study in the institution upon presentation of certified copies of a judgment, sentence, and order of commitment of the superior court and the statement of the prosecuting attorney, along with other reports as may have been made in reference to each individual prisoner.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c143.pdf?cite=1988%20c%20143%20§%2011[1988 c 143 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c114.pdf?cite=1984%20c%20114%20§%204[1984 c 114 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20208[1979 c 141 § 208]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c214.pdf?cite=1959%20c%20214%20§%2015[1959 c 214 § 15]; ]

== 72.02.240 - Secretary to determine placement—What laws govern confinement, parole and discharge.
The secretary shall determine the state correctional institution in which the offender shall be confined during the term of imprisonment. The confinement of any offender shall be governed by the laws applicable to the institution to which the offender is certified for confinement, but parole and discharge shall be governed by the laws applicable to the sentence imposed by the court.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c143.pdf?cite=1988%20c%20143%20§%2012[1988 c 143 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20209[1979 c 141 § 209]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c214.pdf?cite=1959%20c%20214%20§%2016[1959 c 214 § 16]; ]

== 72.02.250 - Commitment of convicted female persons—Procedure as to death sentences.
All female persons convicted in the superior courts of a felony and sentenced to a term of confinement, shall be committed to the Washington correctional institution for women. Female persons sentenced to death shall be committed to the Washington correctional institution for women, notwithstanding the provisions of RCW 10.95.170, except that the death warrant shall provide for the execution of such death sentence at the Washington state penitentiary as provided by RCW 10.95.160, and the secretary of corrections shall transfer to the Washington state penitentiary any female offender sentenced to death not later than seventy-two hours prior to the date fixed in the death warrant for the execution of the death sentence. The provisions of this section shall not become effective until the secretary of corrections certifies to the chief justice of the supreme court, the chief judge of each division of the court of appeals, the superior courts and the prosecuting attorney of each county that the facilities and personnel for the implementation of commitments are ready to receive persons committed to the Washington correctional institution for women under the provisions of this section.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c3.pdf?cite=1983%20c%203%20§%20185[1983 c 3 § 185]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c136.pdf?cite=1981%20c%20136%20§%2097[1981 c 136 § 97]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971c81.pdf?cite=1971%20c%2081%20§%20134[1971 c 81 § 134]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c122.pdf?cite=1967%20ex.s.%20c%20122%20§%208[1967 ex.s. c 122 § 8]; ]

== 72.02.260 - Letters of inmates may be withheld.
Whenever the superintendent of an institution withholds from mailing letters written by inmates of such institution, the superintendent shall forward such letters to the secretary of corrections or the secretary's designee for study and the inmate shall be forthwith notified that such letter has been withheld from mailing and the reason for so doing. Letters forwarded to the secretary for study shall either be mailed within seven days to the addressee or, if deemed objectionable by the secretary, retained in a separate file for two years and then destroyed.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c143.pdf?cite=1988%20c%20143%20§%2013[1988 c 143 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c136.pdf?cite=1981%20c%20136%20§%2087[1981 c 136 § 87]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20192[1979 c 141 § 192]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c28.pdf?cite=1959%20c%2028%20§%2072.08.380[1959 c 28 § 72.08.380]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c61.pdf?cite=1957%20c%2061%20§%201[1957 c 61 § 1]; ]

== 72.02.270 - Abused victims—Murder of abuser—Notice of provisions for reduction in sentence.
The department shall advise all inmates in the department's custody who were convicted of a murder that the inmate committed prior to July 23, 1989, about the provisions in RCW 9.95.045, 9.95.047, and 9.94A.890. The department shall advise the inmates of the method and deadline for submitting petitions to the indeterminate sentence review board for review of the inmate's sentence. The department shall issue the notice to the inmates no later than July 1, 1993.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1343-S.SL.pdf?cite=1993%20c%20144%20§%206[1993 c 144 § 6]; ]

== 72.02.280 - Motion pictures.
Motion pictures unrated after November 1968 or rated X or NC-17 by the motion picture association of America shall not be shown in adult correctional facilities.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=1994%20sp.s.%20c%207%20§%20808[1994 sp.s. c 7 § 808]; ]

