= 72.04A - Probation and parole.
:toc:

== 72.04A.050 - Transfer of certain powers and duties of board of prison terms and paroles to secretary of corrections.
The powers and duties of the state *board of prison terms and paroles, relating to (1) the supervision of parolees of any of the state penal institutions, (2) the supervision of persons placed on probation by the courts, and (3) duties with respect to persons conditionally pardoned by the governor, are transferred to the secretary of corrections.

This section shall not be construed as affecting any of the remaining powers and duties of the *board of prison terms and paroles including, but not limited to, the following:

. The fixing of minimum terms of confinement of convicted persons, or the reconsideration of its determination of minimum terms of confinement;

. Determining when and under what conditions a convicted person may be released from custody on parole, and the revocation or suspension of parole or the modification or revision of the conditions of the parole, of any convicted person.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c136.pdf?cite=1981%20c%20136%20§%2081[1981 c 136 § 81]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20173[1979 c 141 § 173]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c134.pdf?cite=1967%20c%20134%20§%207[1967 c 134 § 7]; ]

== 72.04A.070 - Plans and recommendations for conditions of supervision of parolees.
The secretary of corrections shall cause to be prepared plans and recommendations for the conditions of supervision under which each inmate of any state penal institutions who is eligible for parole may be released from custody. Such plans and recommendations shall be submitted to the *board of prison terms and paroles which may, at its discretion, approve, reject, or revise or amend such plans and recommendations for the conditions of supervision of release of inmates on parole, and, in addition, the board may stipulate any special conditions of supervision to be carried out by a probation and parole officer.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c136.pdf?cite=1981%20c%20136%20§%2082[1981 c 136 § 82]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20174[1979 c 141 § 174]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c134.pdf?cite=1967%20c%20134%20§%209[1967 c 134 § 9]; ]

== 72.04A.080 - Parolees subject to supervision of department—Progress reports.
Each inmate hereafter released on parole shall be subject to the supervision of the department of corrections, and the probation and parole officers of the department shall be charged with the preparation of progress reports of parolees and to give guidance and supervision to such parolees within the conditions of a parolee's release from custody. Copies of all progress reports prepared by the probation and parole officers shall be supplied to the *board of prison terms and paroles for their files and records.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c136.pdf?cite=1981%20c%20136%20§%2083[1981 c 136 § 83]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20175[1979 c 141 § 175]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c134.pdf?cite=1967%20c%20134%20§%2010[1967 c 134 § 10]; ]

== 72.04A.090 - Violations of parole or probation—Revision of parole conditions—Detention.
Whenever a parolee breaches a condition or conditions under which he or she was granted parole, or violates any law of the state or rules and regulations of the indeterminate sentencing [sentence] review board, any probation and parole officer may arrest, or cause the arrest and suspension of parole of, such parolee without a warrant, pending a determination by the board. The facts and circumstances of such conduct of the parolee shall be reported by the probation and parole officer, with recommendations, to the indeterminate sentence review board, who may order the revocation or suspension of parole, revise or modify the conditions of parole or take such other action as may be deemed appropriate in accordance with RCW 9.95.120. The indeterminate sentence review board, after consultation with the secretary of corrections, shall make all rules and regulations concerning procedural matters, which shall include the time when state probation and parole officers shall file with the board reports required by this section, procedures pertaining thereto and the filing of such information as may be necessary to enable the indeterminate sentence review board to perform its functions under this section.

The probation and parole officers shall have like authority and power regarding the arrest and detention of a probationer who has breached a condition or conditions under which he or she was granted probation by the superior court, or violates any law of the state, pending a determination by the superior court.

In the event a probation and parole officer shall arrest or cause the arrest and suspension of parole of a parolee or probationer in accordance with the provisions of this section, such parolee or probationer shall be confined and detained in the county jail of the county in which the parolee or probationer was taken into custody, and the sheriff of such county shall receive and keep in the county jail, where room is available, all prisoners delivered thereto by the probation and parole officer, and such parolees shall not be released from custody on bail or personal recognizance, except upon approval of the indeterminate sentence review board and the issuance by the board of an order of reinstatement on parole on the same or modified conditions of parole.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20457[2012 c 117 § 457]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c136.pdf?cite=1981%20c%20136%20§%2084[1981 c 136 § 84]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20176[1979 c 141 § 176]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c98.pdf?cite=1969%20c%2098%20§%201[1969 c 98 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c134.pdf?cite=1967%20c%20134%20§%2011[1967 c 134 § 11]; ]

== 72.04A.120 - Parolee supervision intake fees.
. Any person placed on parole shall be required to pay the supervision intake fee, prescribed under RCW 9.94A.780(3). The department may exempt a person from the payment of all or any part of the assessment based upon any of the following factors:

.. The offender has diligently attempted but has been unable to obtain employment which provides the offender sufficient income to make such payments.

.. The offender is a student in a school, college, university, or a course of vocational or technical training designed to fit the student for gainful employment.

.. The offender has an employment handicap, as determined by an examination acceptable to or ordered by the department.

.. The offender's age prevents him or her from obtaining employment.

.. The offender is responsible for the support of dependents and the payment of the assessment constitutes an undue hardship on the offender.

.. Other extenuating circumstances as determined by the department.

. The department of corrections shall adopt a rule prescribing the amount of the assessment.

. Payment of the assessed amount shall constitute a condition of parole for purposes of the application of RCW 72.04A.090.

. All amounts required to be paid under this section shall be collected by the department of corrections and deposited by the department in the dedicated fund established pursuant to RCW 72.11.040.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20458[2012 c 117 § 458]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5891-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2040%20§%2012[2011 1st sp.s. c 40 § 12]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1371.SL.pdf?cite=1991%20c%20104%20§%202[1991 c 104 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c252.pdf?cite=1989%20c%20252%20§%2020[1989 c 252 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c207.pdf?cite=1982%20c%20207%20§%201[1982 c 207 § 1]; ]

== 72.04A.900 - RCW  72.04A.050 through  72.04A.090 inapplicable to felonies committed after July 1, 1984.
The following sections of law do not apply to any felony offense committed on or after July 1, 1984: RCW 72.04A.050, 72.04A.070, 72.04A.080, and 72.04A.090.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c137.pdf?cite=1981%20c%20137%20§%2034[1981 c 137 § 34]; ]

