= 72.40 - State schools for blind, deaf, sensory handicapped.
:toc:

== 72.40.010 - Schools established—Purpose—Direction.
There are established at Vancouver, Clark county, a school which shall be known as the state school for the blind, and a separate school which shall be known as the state school for the deaf. The primary purpose of the state school for the blind and the state school for the deaf is to educate and train hearing and visually impaired children.

The school for the blind shall be under the direction of the superintendent with the advice of the board of trustees. The school for the deaf shall be under the direction of the director of the center or the director's designee and the board of trustees.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1879-S2.SL.pdf?cite=2009%20c%20381%20§%203[2009 c 381 § 3]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6558-S.SL.pdf?cite=2002%20c%20209%20§%201[2002 c 209 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c378.pdf?cite=1985%20c%20378%20§%2011[1985 c 378 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c28.pdf?cite=1959%20c%2028%20§%2072.40.010[1959 c 28 § 72.40.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c10.pdf?cite=1913%20c%2010%20§%201[1913 c 10 § 1]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1886%20p%20136%20§%201[1886 p 136 § 1]; RRS § 4645; ]

== 72.40.015 - Center for deaf and hard of hearing youth—Functions.
. The Washington center for deaf and hard of hearing youth is established to provide statewide leadership for the coordination and delivery of educational services to children who are deaf or hard of hearing. The activities of the center shall be under the authority of the director and the board of trustees. The superintendent and board of trustees of the state school for the deaf shall be the director and board of trustees of the center.

. The center's primary functions are:

.. Managing and directing the supervision of the state school for the deaf;

.. Providing statewide leadership and support for the coordination of regionally delivered educational services in the full range of communication modalities, for children who are deaf or hard of hearing; and

.. Collaborating with appropriate public and private partners for the training and professional development of educators serving children who are deaf or hard of hearing.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1604.SL.pdf?cite=2019%20c%20266%20§%201[2019 c 266 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1879-S2.SL.pdf?cite=2009%20c%20381%20§%202[2009 c 381 § 2]; ]

== 72.40.019 - Center for deaf and hard of hearing youth—Appointment of director—Qualifications.
The governor shall appoint a director for the Washington center for deaf and hard of hearing youth. The director shall have a master's or higher degree from an accredited college or university in school administration or deaf education, five or more years of experience teaching or providing habilitative services to deaf or hard of hearing students, and three or more years administrative or supervisory experience in programs for deaf or hard of hearing students.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1604.SL.pdf?cite=2019%20c%20266%20§%202[2019 c 266 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1879-S2.SL.pdf?cite=2009%20c%20381%20§%204[2009 c 381 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c378.pdf?cite=1985%20c%20378%20§%2014[1985 c 378 § 14]; ]

== 72.40.0191 - Center for deaf and hard of hearing youth—Director's powers and duties.
In addition to any other powers and duties prescribed by law, the director of the Washington center for deaf and hard of hearing youth:

. Shall be responsible for the supervision and management of the center, including the state school for the deaf, and the property of various kinds. The director may designate an individual to oversee the day-to-day operation and supervision of students at the school;

. Shall employ members of the faculty, administrative officers, and other employees, who shall all be subject to chapter 41.06 RCW, the state civil service law, unless specifically exempted by other provisions of law;

. Shall provide technical assistance and support as appropriate to local and regional efforts to build critical mass and communication-rich networking opportunities for children who are deaf or hard of hearing and their families;

. Shall establish the course of study including vocational training, with the assistance of the faculty and the approval of the board of trustees;

. Shall, as approved by the board of trustees, control and authorize the use of the facilities for night school, summer school, public meetings, applied research and training for the instruction of students who are deaf or hard of hearing, outreach and support to families of children who are deaf or hard of hearing, or other purposes consistent with the purposes of the center;

. Shall purchase all supplies and lease or purchase equipment and other personal property needed for the operation or maintenance of the center;

. Shall prepare, submit to the board of trustees for approval, and administer the budget consistent with RCW 43.88.160 and the budget and accounting act, chapter 43.88 RCW generally, as applicable;

. Shall provide technical assistance and support to educational service districts for the regional delivery of a full range of educational services to students who are deaf or hard of hearing, including but not limited to services relying on American Sign Language, auditory oral education, total communication, and signed exact English;

. As requested by educational service districts, shall recruit, employ, and deploy itinerant teachers to provide in-district services to children who are deaf or hard of hearing;

. May establish criteria, in addition to state certification, for the teachers at the school and employees of the center;

. May establish, with the approval of the board of trustees, new facilities as needs demand;

. May adopt rules, under chapter 34.05 RCW, as approved by the board of trustees and as deemed necessary for the governance, management, and operation of the center;

. May adopt rules, as approved by the board of trustees, for pedestrian and vehicular traffic on property owned, operated, and maintained by the center;

. Except as otherwise provided by law, may enter into contracts as the director deems essential to the purpose of the center;

. May receive gifts, grants, conveyances, devises, and bequests of real or personal property from whatever source, as may be made from time to time, in trust or otherwise, whenever the terms and conditions will aid in carrying out the programs of the center; sell, lease, or exchange, invest, or expend the same or the proceeds, rents, profits, and income thereof except as limited by the terms and conditions thereof; and adopt rules to govern the receipt and expenditure of the proceeds, rents, profits, and income thereof;

. May adopt rules, as approved by the board of trustees, providing for the transferability of employees between the center and the school for the blind consistent with collective bargaining agreements in effect; and

. May adopt rules under chapter 34.05 RCW, as approved by the board of trustees, and perform all other acts not forbidden by law as the director deems necessary or appropriate to the administration of the center.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1604.SL.pdf?cite=2019%20c%20266%20§%203[2019 c 266 § 3]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1879-S2.SL.pdf?cite=2009%20c%20381%20§%205[2009 c 381 § 5]; ]

== 72.40.020 - State school for the blind—Appointment of superintendent—Qualifications.
The governor shall appoint a superintendent for the state school for the blind. The superintendent shall have a master's degree from an accredited college or university in school administration or blind education, five years of experience teaching blind students in the classroom, and three years administrative or supervisory experience in programs for blind students.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c378.pdf?cite=1985%20c%20378%20§%2013[1985 c 378 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20247[1979 c 141 § 247]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c28.pdf?cite=1959%20c%2028%20§%2072.40.020[1959 c 28 § 72.40.020]; 1909 c 97 p 258 § 5; RRS § 4649; ]

== 72.40.022 - Superintendent of the state school for the blind—Powers and duties.
In addition to any other powers and duties prescribed by law, the superintendent of the state school for the blind:

. Shall have full control of the school and the property of various kinds.

. May establish criteria, in addition to state certification, for teachers at the school.

. Shall employ members of the faculty, administrative officers, and other employees, who shall all be subject to chapter 41.06 RCW, the state civil service law, unless specifically exempted by other provisions of law.

. Shall establish the course of study including vocational training, with the assistance of the faculty and the advice of the board of trustees.

. May establish new facilities as needs demand.

. May adopt rules, under chapter 34.05 RCW, as deemed necessary for the government, management, and operation of the housing facilities.

. Shall control the use of the facilities and authorize the use of the facilities for night school, summer school, public meetings, or other purposes consistent with the purposes of the school.

. May adopt rules for pedestrian and vehicular traffic on property owned, operated, and maintained by the school.

. Shall purchase all supplies and lease or purchase equipment and other personal property needed for the operation or maintenance of the school.

. Except as otherwise provided by law, may enter into contracts as the superintendent deems essential to the purpose of the school.

. May receive gifts, grants, conveyances, devises, and bequests of real or personal property from whatever source, as may be made from time to time, in trust or otherwise, whenever the terms and conditions will aid in carrying out the programs of the school; sell, lease or exchange, invest, or expend the same or the proceeds, rents, profits, and income thereof except as limited by the terms and conditions thereof; and adopt rules to govern the receipt and expenditure of the proceeds, rents, profits, and income thereof.

. May, except as otherwise provided by law, enter into contracts the superintendent deems essential for the operation of the school.

. May adopt rules providing for the transferability of employees between the *school for the deaf and the school for the blind consistent with collective bargaining agreements in effect.

. Shall prepare and administer the school's budget consistent with RCW 43.88.160 and the budget and accounting act, chapter 43.88 RCW generally, as applicable.

. May adopt rules under chapter 34.05 RCW and perform all other acts not forbidden by law as the superintendent deems necessary or appropriate to the administration of the school.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6558-S.SL.pdf?cite=2002%20c%20209%20§%202[2002 c 209 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5556-S.SL.pdf?cite=1993%20c%20147%20§%201[1993 c 147 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c378.pdf?cite=1985%20c%20378%20§%2015[1985 c 378 § 15]; ]

== 72.40.024 - Superintendents and director—Additional powers and duties.
In addition to the powers and duties under RCW 72.40.022 and 72.40.0191, the superintendent of the school for the blind and the director of the Washington center for deaf and hard of hearing youth, or the director's designee, shall:

. Monitor the location and educational placement of each student reported to the superintendent and the director, or the director's designee, by the educational service district superintendents;

. Provide information about educational programs, instructional techniques, materials, equipment, and resources available to students with visual or auditory impairments to the parent or guardian, educational service district superintendent, and the superintendent of the school district where the student resides; and

. Serve as a consultant to the office of the superintendent of public instruction, provide instructional leadership, and assist school districts in improving their instructional programs for students with visual or hearing impairments.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1604.SL.pdf?cite=2019%20c%20266%20§%204[2019 c 266 § 4]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1879-S2.SL.pdf?cite=2009%20c%20381%20§%206[2009 c 381 § 6]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6558-S.SL.pdf?cite=2002%20c%20209%20§%204[2002 c 209 § 4]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5556-S.SL.pdf?cite=1993%20c%20147%20§%202[1993 c 147 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c378.pdf?cite=1985%20c%20378%20§%2017[1985 c 378 § 17]; ]

== 72.40.028 - Teachers' qualifications—Salaries—Provisional certification.
All teachers employed by the Washington center for deaf and hard of hearing youth and the state school for the blind shall meet all certification requirements and the programs shall meet all accreditation requirements and conform to the standards defined by law or by rule of the Washington professional educator standards board or the office of the state superintendent of public instruction. The superintendent and the director, by rule, may adopt additional educational standards for their respective facilities. Salaries of all certificated employees shall be based on the statewide average salary set forth in RCW 28A.150.410, adjusted by the regionalization factor that applies to the school district in which the program or facility is located. The superintendent and the director may provide for provisional certification for teachers in their respective facilities including certification for emergency, temporary, substitute, or provisional duty.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1604.SL.pdf?cite=2019%20c%20266%20§%205[2019 c 266 § 5]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6362-S2.SL.pdf?cite=2018%20c%20266%20§%20405[2018 c 266 § 405]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1879-S2.SL.pdf?cite=2009%20c%20381%20§%207[2009 c 381 § 7]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/3098-S2.SL.pdf?cite=2006%20c%20263%20§%20829[2006 c 263 § 829]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c378.pdf?cite=1985%20c%20378%20§%2018[1985 c 378 § 18]; ]

== 72.40.031 - School year—School term—Legal holidays—Use of schools.
The school year for the state school for the blind and the state school for the deaf shall commence on the first day of July of each year and shall terminate on the 30th day of June of the succeeding year. The regular school term shall be for a period of nine months and shall commence as near as reasonably practical at the time of the commencement of regular terms in other public schools, with the equivalent number of days as are now required by law, and the regulations of the superintendent of public instruction as now or hereafter amended, during the school year in other public schools. The school and the center shall observe all legal holidays, in the same manner as other agencies of state government, and will not be in session on such days and such other days as may be approved by the superintendent or the director. During the period when the schools are not in session during the regular school term, schools may be operated, subject to the approval of the superintendent or the director or the director's designee, for the instruction of students or for such other reasons which are in furtherance of the objects and purposes of the respective facilities.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1879-S2.SL.pdf?cite=2009%20c%20381%20§%2012[2009 c 381 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c378.pdf?cite=1985%20c%20378%20§%2016[1985 c 378 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20248[1979 c 141 § 248]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c50.pdf?cite=1970%20ex.s.%20c%2050%20§%206[1970 ex.s. c 50 § 6]; ]

== 72.40.040 - Who may be admitted.
. The schools shall be free to residents of the state between the ages of three and twenty-one years, who are blind/visually impaired or deaf/hearing impaired, or with other disabilities where a vision or hearing disability is the major need for services.

. The schools may provide nonresidential services to children ages birth through three who meet the eligibility criteria in this section, subject to available funding.

. Each school shall admit and retain students on a space available basis according to criteria developed and published by each school superintendent in consultation with each board of trustees and school faculty: PROVIDED, That students over the age of twenty-one years, who are otherwise qualified may be retained at the school, if in the discretion of the superintendent in consultation with the faculty they are proper persons to receive further training given at the school and the facilities are adequate for proper care, education, and training.

. The admission and retention criteria developed and published by each school superintendent shall contain a provision allowing the schools to refuse to admit or retain a student who is an adjudicated sex offender except that the schools shall not admit or retain a student who is an adjudicated level III sex offender as provided in RCW 13.40.217(3).

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6361-S.SL.pdf?cite=2000%20c%20125%20§%208[2000 c 125 § 8]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5556-S.SL.pdf?cite=1993%20c%20147%20§%203[1993 c 147 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c378.pdf?cite=1985%20c%20378%20§%2019[1985 c 378 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c160.pdf?cite=1984%20c%20160%20§%204[1984 c 160 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c80.pdf?cite=1977%20ex.s.%20c%2080%20§%2068[1977 ex.s. c 80 § 68]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c39.pdf?cite=1969%20c%2039%20§%201[1969 c 39 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c28.pdf?cite=1959%20c%2028%20§%2072.40.040[1959 c 28 § 72.40.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c260.pdf?cite=1955%20c%20260%20§%201[1955 c 260 § 1]; 1909 c 97 p 258 § 3; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1903c140.pdf?cite=1903%20c%20140%20§%201[1903 c 140 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1897c118.pdf?cite=1897%20c%20118%20§%20229[1897 c 118 § 229]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1886%20p%20136%20§%202[1886 p 136 § 2]; RRS § 4647; ]

== 72.40.050 - Admission of nonresidents.
. The superintendents may admit to their respective schools visually or hearing impaired children from other states as appropriate, but the parents or guardians of such children or other state will be required to pay annually or quarterly in advance a sufficient amount to cover the cost of maintaining and educating such children as set by the applicable superintendent.

. The admission and retention criteria developed and published by each school superintendent shall contain a provision allowing the schools to refuse to admit or retain a nonresident student who is an adjudicated sex offender, or the equivalent under the laws of the state in which the student resides, except that the schools shall not admit or retain a nonresident student who is an adjudicated level III sex offender or the equivalent under the laws of the state in which the student resides.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6361-S.SL.pdf?cite=2000%20c%20125%20§%209[2000 c 125 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c378.pdf?cite=1985%20c%20378%20§%2020[1985 c 378 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20249[1979 c 141 § 249]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c28.pdf?cite=1959%20c%2028%20§%2072.40.050[1959 c 28 § 72.40.050]; 1909 c 97 p 258 § 4; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1897c118.pdf?cite=1897%20c%20118%20§%20251[1897 c 118 § 251]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1886%20p%20141%20§%2032[1886 p 141 § 32]; RRS § 4648; ]

== 72.40.060 - Duty of school districts.
It shall be the duty of all school districts in the state, to report to their respective educational service districts the names of all visually or hearing impaired youth residing within their respective school districts who are between the ages of three and twenty-one years.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c378.pdf?cite=1985%20c%20378%20§%2021[1985 c 378 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c275.pdf?cite=1975%201st%20ex.s.%20c%20275%20§%20151[1975 1st ex.s. c 275 § 151]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c176.pdf?cite=1969%20ex.s.%20c%20176%20§%2097[1969 ex.s. c 176 § 97]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c28.pdf?cite=1959%20c%2028%20§%2072.40.060[1959 c 28 § 72.40.060]; 1909 c 97 p 258 § 6; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1897c118.pdf?cite=1897%20c%20118%20§%20252[1897 c 118 § 252]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c497.pdf?cite=1890%20p%20497%20§%201[1890 p 497 § 1]; RRS § 4650; ]

== 72.40.070 - Duty of educational service districts.
It shall be the duty of each educational service district to make a full and specific report of visually impaired or deaf or hard of hearing youth to the superintendent of the school for the blind or the director of the Washington center for deaf and hard of hearing youth, or the director's designee, as the case may be and the superintendent of public instruction, annually. The superintendent of public instruction shall report about the deaf or hard of hearing or visually impaired youth to the school for the blind and the Washington center for deaf and hard of hearing youth, as the case may be, annually.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1604.SL.pdf?cite=2019%20c%20266%20§%206[2019 c 266 § 6]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1879-S2.SL.pdf?cite=2009%20c%20381%20§%2018[2009 c 381 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c378.pdf?cite=1985%20c%20378%20§%2022[1985 c 378 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20250[1979 c 141 § 250]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c275.pdf?cite=1975%201st%20ex.s.%20c%20275%20§%20152[1975 1st ex.s. c 275 § 152]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c176.pdf?cite=1969%20ex.s.%20c%20176%20§%2098[1969 ex.s. c 176 § 98]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c28.pdf?cite=1959%20c%2028%20§%2072.40.070[1959 c 28 § 72.40.070]; 1909 c 97 p 259 § 7; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1897c118.pdf?cite=1897%20c%20118%20§%20253[1897 c 118 § 253]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c497.pdf?cite=1890%20p%20497%20§%202[1890 p 497 § 2]; RRS § 4651; ]

== 72.40.080 - Duty of parents.
It shall be the duty of the parents or the guardians of all such visually or hearing impaired youth to send them each year to the proper school. Full and due consideration shall be given to the parent's or guardian's preference as to which program the child should attend. The educational service district superintendent shall take all action necessary to enforce this section.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5556-S.SL.pdf?cite=1993%20c%20147%20§%204[1993 c 147 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c378.pdf?cite=1985%20c%20378%20§%2023[1985 c 378 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c275.pdf?cite=1975%201st%20ex.s.%20c%20275%20§%20153[1975 1st ex.s. c 275 § 153]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c176.pdf?cite=1969%20ex.s.%20c%20176%20§%2099[1969 ex.s. c 176 § 99]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c28.pdf?cite=1959%20c%2028%20§%2072.40.080[1959 c 28 § 72.40.080]; 1909 c 97 p 259 § 8; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1897c118.pdf?cite=1897%20c%20118%20§%20254[1897 c 118 § 254]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c498.pdf?cite=1890%20p%20498%20§%203[1890 p 498 § 3]; RRS § 4652; ]

== 72.40.090 - Weekend transportation—Expense.
Notwithstanding any other provision of law, the state school for the blind and the *school for the deaf may arrange and provide for weekend transportation to and from schools. This transportation shall be at no cost to students and parents, as allowed within the appropriations allocated to the schools.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5556-S.SL.pdf?cite=1993%20c%20147%20§%205[1993 c 147 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c378.pdf?cite=1985%20c%20378%20§%2024[1985 c 378 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975c51.pdf?cite=1975%20c%2051%20§%201[1975 c 51 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c28.pdf?cite=1959%20c%2028%20§%2072.40.090[1959 c 28 § 72.40.090]; 1909 c 97 p 259 § 9; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1899c142.pdf?cite=1899%20c%20142%20§%2028[1899 c 142 § 28]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1899c81.pdf?cite=1899%20c%2081%20§%202[1899 c 81 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1897c118.pdf?cite=1897%20c%20118%20§%20255[1897 c 118 § 255]; RRS § 4653; ]

== 72.40.100 - Penalty.
Any parent, guardian, or educational service district superintendent who, without proper cause, fails to carry into effect the provisions of this chapter shall be guilty of a misdemeanor, and upon conviction thereof, upon the complaint of any officer or citizen of the county or state, before any district or superior court, shall be fined in any sum not less than fifty nor more than two hundred dollars.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c202.pdf?cite=1987%20c%20202%20§%20229[1987 c 202 § 229]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c378.pdf?cite=1985%20c%20378%20§%2025[1985 c 378 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c275.pdf?cite=1975%201st%20ex.s.%20c%20275%20§%20154[1975 1st ex.s. c 275 § 154]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c176.pdf?cite=1969%20ex.s.%20c%20176%20§%20100[1969 ex.s. c 176 § 100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c28.pdf?cite=1959%20c%2028%20§%2072.40.100[1959 c 28 § 72.40.100]; 1909 c 97 p 259 § 10; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1897c118.pdf?cite=1897%20c%20118%20§%20256[1897 c 118 § 256]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c498.pdf?cite=1890%20p%20498%20§%205[1890 p 498 § 5]; RRS § 4654; ]

== 72.40.110 - Employees' hours of labor.
Employees' hours of labor shall follow all state merit rules as they pertain to various work classifications and current collective bargaining agreements.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5556-S.SL.pdf?cite=1993%20c%20147%20§%206[1993 c 147 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c378.pdf?cite=1985%20c%20378%20§%2012[1985 c 378 § 12]; ]

== 72.40.120 - Center for deaf and hard of hearing youth—School for the blind—Appropriations.
Any appropriation for the Washington center for deaf and hard of hearing youth or the school for the blind shall be made directly to the center or the school for the blind.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1604.SL.pdf?cite=2019%20c%20266%20§%207[2019 c 266 § 7]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1879-S2.SL.pdf?cite=2009%20c%20381%20§%208[2009 c 381 § 8]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5779.SL.pdf?cite=1991%20c%2065%20§%201[1991 c 65 § 1]; ]

== 72.40.200 - Safety of students and protection from child abuse and neglect.
The Washington center for deaf and hard of hearing youth and the state school for the blind shall promote the personal safety of students and protect the children who attend from child abuse and neglect as defined in RCW 26.44.020.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1604.SL.pdf?cite=2019%20c%20266%20§%208[2019 c 266 § 8]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1879-S2.SL.pdf?cite=2009%20c%20381%20§%209[2009 c 381 § 9]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6361-S.SL.pdf?cite=2000%20c%20125%20§%201[2000 c 125 § 1]; ]

== 72.40.210 - Reports to parents—Requirement.
The director of the Washington center for deaf and hard of hearing youth and the superintendent of the state school for the blind or their designees shall immediately report to the persons indicated the following events:

. To the child's parent, custodian, or guardian:

.. The death of the child;

.. Hospitalization of a child in attendance or residence at the facility;

.. Allegations of child abuse or neglect in which the parent's child in attendance or residence at the facility is the alleged victim;

.. Allegations of physical or sexual abuse in which the parent's child in attendance or residence at the facility is the alleged perpetrator;

.. Life-threatening illness;

.. The attendance at the facility of any child who is a registered sex offender under RCW 9A.44.130 as permitted by RCW 4.24.550.

. Notification to the parent shall be made by the means most likely to be received by the parent. If initial notification is made by telephone, such notification shall be followed by notification in writing within forty-eight hours after the initial verbal contact is made.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1604.SL.pdf?cite=2019%20c%20266%20§%209[2019 c 266 § 9]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1879-S2.SL.pdf?cite=2009%20c%20381%20§%2010[2009 c 381 § 10]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6361-S.SL.pdf?cite=2000%20c%20125%20§%202[2000 c 125 § 2]; ]

== 72.40.220 - Behavior management policies, procedures, and techniques.
. The director of the Washington center for deaf and hard of hearing youth, or the director's designee, and the superintendent of the state school for the blind shall maintain in writing and implement behavior management policies and procedures that accomplish the following:

.. Support the child's appropriate social behavior, self-control, and the rights of others;

.. Foster dignity and self-respect for the child;

.. Reflect the ages and developmental levels of children in care.

. The state school for the deaf and the state school for the blind shall use proactive, positive behavior support techniques to manage potential child behavior problems. These techniques shall include but not be limited to:

.. Organization of the physical environment and staffing patterns to reduce factors leading to behavior incidents;

.. Intervention before behavior becomes disruptive, in the least invasive and least restrictive manner available;

.. Emphasis on verbal de-escalation to calm the upset child;

.. Redirection strategies to present the child with alternative resolution choices.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1604.SL.pdf?cite=2019%20c%20266%20§%2010[2019 c 266 § 10]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1879-S2.SL.pdf?cite=2009%20c%20381%20§%2019[2009 c 381 § 19]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6361-S.SL.pdf?cite=2000%20c%20125%20§%203[2000 c 125 § 3]; ]

== 72.40.230 - Staff orientation and training.
. The *state school for the deaf and the state school for the blind shall ensure that all staff, within two months of beginning employment, complete a minimum of fifteen hours of job orientation which shall include, but is not limited to, presentation of the standard operating procedures manual for each school, describing all policies and procedures specific to the school.

. The *state school for the deaf and the state school for the blind shall ensure that all new staff receive thirty-two hours of job specific training within ninety days of employment which shall include, but is not limited to, promoting and protecting student personal safety. All staff shall receive thirty-two hours of ongoing training in these areas every two years.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6361-S.SL.pdf?cite=2000%20c%20125%20§%204[2000 c 125 § 4]; ]

== 72.40.240 - Residential staffing requirement.
The residential program at the *state school for the deaf and the state school for the blind shall employ residential staff in sufficient numbers to ensure the physical and emotional needs of the residents are met. Residential staff shall be on duty in sufficient numbers to ensure the safety of the children residing there.

For purposes of this section, "residential staff" means staff in charge of supervising the day-to-day living situation of the children in the residential portion of the schools.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6361-S.SL.pdf?cite=2000%20c%20125%20§%205[2000 c 125 § 5]; ]

== 72.40.250 - Protection from child abuse and neglect—Supervision of employees and volunteers—Procedures.
In addition to the powers and duties under RCW 72.40.022 and 72.40.024, the director of the Washington center for deaf and hard of hearing youth, or the director's designee, and the superintendent of the state school for the blind shall:

. Develop written procedures for the supervision of employees and volunteers who have the potential for contact with students. Such procedures shall be designed to prevent child abuse and neglect by providing for adequate supervision of such employees and volunteers, taking into consideration such factors as the student population served, architectural factors, and the size of the facility. Such procedures shall include, but need not be limited to, the following:

.. Staffing patterns and the rationale for such;

.. Responsibilities of supervisors;

.. The method by which staff and volunteers are made aware of the identity of all supervisors, including designated on-site supervisors;

.. Provision of written supervisory guidelines to employees and volunteers;

.. Periodic supervisory conferences for employees and volunteers; and

.. Written performance evaluations of staff to be conducted by supervisors in a manner consistent with applicable provisions of the civil service law.

. Develop written procedures for the protection of students when there is reason to believe an incident has occurred which would render a minor student an abused or neglected child within the meaning of RCW 26.44.020. Such procedures shall include, but need not be limited to, the following:

.. Investigation. Immediately upon notification that a report of child abuse or neglect has been made to the department of social and health services or a law enforcement agency, the superintendent or the director, or the director's designee, shall:

... Preserve any potential evidence through such actions as securing the area where suspected abuse or neglect occurred;

... Obtain proper and prompt medical evaluation and treatment, as needed, with documentation of any evidence of abuse or neglect; and

... Provide necessary assistance to the department of social and health services and local law enforcement in their investigations;

.. Safety. Upon notification that a report of suspected child abuse or neglect has been made to the department of social and health services or a law enforcement agency, the superintendent or the director or his or her designee, with consideration for causing as little disruption as possible to the daily routines of the students, shall evaluate the situation and immediately take appropriate action to assure the health and safety of the students involved in the report and of any other students similarly situated, and take such additional action as is necessary to prevent future acts of abuse or neglect. Such action may include:

... Consistent with federal and state law:

(A) Removing the alleged perpetrator from the school;

(B) Increasing the degree of supervision of the alleged perpetrator; and

(C) Initiating appropriate disciplinary action against the alleged perpetrator;

... Provision of increased training and increased supervision to volunteers and staff pertinent to the prevention and remediation of abuse and neglect;

... Temporary removal of the students from a program and reassignment of the students within the school, as an emergency measure, if it is determined that there is a risk to the health or safety of such students in remaining in that program. Whenever a student is removed, pursuant to this subsection (2)(b)(iii), from a special education program or service specified in his or her individualized education program, the action shall be reviewed in an individualized education program meeting; and

... Provision of counseling to the students involved in the report or any other students, as appropriate;

.. Corrective action plans. Upon receipt of the results of an investigation by the department of social and health services pursuant to a report of suspected child abuse or neglect, the superintendent or the director, or the director's designee, after consideration of any recommendations by the department of social and health services for preventive and remedial action, shall implement a written plan of action designed to assure the continued health and safety of students and to provide for the prevention of future acts of abuse or neglect.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1604.SL.pdf?cite=2019%20c%20266%20§%2011[2019 c 266 § 11]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1879-S2.SL.pdf?cite=2009%20c%20381%20§%2020[2009 c 381 § 20]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6361-S.SL.pdf?cite=2000%20c%20125%20§%206[2000 c 125 § 6]; ]

== 72.40.260 - Protection from child abuse and neglect—Student instruction.
In consideration of the needs and circumstances of the program, the *state school for the deaf and the state school for the blind shall provide instruction to all students in techniques and procedures which will enable the students to protect themselves from abuse and neglect. Such instruction shall be described in a written plan to be submitted to the board of trustees for review and approval, and shall be:

. Appropriate for the age, individual needs, and particular circumstances of students, including the existence of mental, physical, emotional, or sensory disabilities;

. Provided at different times throughout the year in a manner which will ensure that all students receive such instruction; and

. Provided by individuals who possess appropriate knowledge and training, documentation of which shall be maintained by the school.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6361-S.SL.pdf?cite=2000%20c%20125%20§%207[2000 c 125 § 7]; ]

== 72.40.270 - Protection from sexual victimization—Policy.
. The schools shall implement a policy for the children who reside at the schools protecting those who are vulnerable to sexual victimization by other children who are sexually aggressive and residing at the schools. The policy shall include, at a minimum, the following elements:

.. Development and use of an assessment process for identifying children, within thirty days of beginning residence at the schools, who present a moderate or high risk of sexually aggressive behavior for the purposes of this section. The assessment process need not require that every child who is adjudicated or convicted of a sex offense as defined in RCW 9.94A.030 be determined to be sexually aggressive, nor shall a sex offense adjudication or conviction be required in order to determine a child is sexually aggressive. Instead, the assessment process shall consider the individual circumstances of the child, including his or her age, physical size, sexual abuse history, mental and emotional condition, and other factors relevant to sexual aggressiveness. The definition of "sexually aggressive youth" in RCW 74.13.075 does not apply to this section to the extent that it conflicts with this section;

.. Development and use of an assessment process for identifying children, within thirty days of beginning residence at the schools, who may be vulnerable to victimization by children identified under (a) of this subsection as presenting a moderate or high risk of sexually aggressive behavior. The assessment process shall consider the individual circumstances of the child, including his or her age, physical size, sexual abuse history, mental and emotional condition, and other factors relevant to vulnerability;

.. Development and use of placement criteria to avoid assigning children who present a moderate or high risk of sexually aggressive behavior to the same sleeping quarters as children assessed as vulnerable to sexual victimization, except that they may be assigned to the same multiple-person sleeping quarters if those sleeping quarters are regularly monitored by visual surveillance equipment or staff checks;

.. Development and use of procedures for minimizing, within available funds, unsupervised contact in the residential facilities of the schools between children presenting moderate to high risk of sexually aggressive behavior and children assessed as vulnerable to sexual victimization. The procedures shall include taking reasonable steps to prohibit any child residing at the schools who present a moderate to high risk of sexually aggressive behavior from entering any sleeping quarters other than the one to which they are assigned, unless accompanied by an authorized adult.

. For the purposes of this section, the following terms have the following meanings:

.. "Sleeping quarters" means the bedrooms or other rooms within a residential facility where children are assigned to sleep.

.. "Unsupervised contact" means contact occurring outside the sight or hearing of a responsible adult for more than a reasonable period of time under the circumstances.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6361-S.SL.pdf?cite=2000%20c%20125%20§%2010[2000 c 125 § 10]; ]

== 72.40.280 - Monitoring of residential program by department of social and health services—Recommendations—Comprehensive child health and safety reviews—Access to records and documents—Safety standards.
. The department of social and health services must periodically monitor the residential program at the state school for the deaf, including but not limited to examining the residential-related policies and procedures as well as the residential facilities. The department of social and health services must make recommendations to the director and the board of trustees of the center or its successor board on health and safety improvements related to child safety and well-being. The department of social and health services must conduct the monitoring reviews at least annually. The director or the director's designee may from time to time request technical assistance from the department of social and health services.

. The department of social and health services must conduct a comprehensive child health and safety review, as defined in rule, of the residential program at the state school for the deaf every three years. 

. The state school for the deaf must provide the department of social and health services' staff with full and complete access to all records and documents that the department staff may request to carry out the requirements of this section. The department of social and health services must have full and complete access to all students and staff of the state school for the deaf to conduct interviews to carry out the requirements of this section.

. For the purposes of this section, the department of social and health services must use the safety standards established in this chapter when conducting the reviews.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1879-S2.SL.pdf?cite=2009%20c%20381%20§%2021[2009 c 381 § 21]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2568-S.SL.pdf?cite=2002%20c%20208%20§%202[2002 c 208 § 2]; ]

== 72.40.290 - Center for deaf and hard of hearing youth account.
The center for deaf and hard of hearing youth account is created in the custody of the state treasurer. All receipts from contracts, grants, gifts, conveyances, devises, and bequests of real or personal property, or payments received from RCW 72.40.0191 (14) and (15) and 72.40.050 must be deposited into the account. Expenditures from the account may be used only for duties related to RCW 72.40.0191 (14) and (15) and 72.40.050. Only the director of the center for deaf and hard of hearing youth or the director's designee may authorize expenditures from the account. The account is subject to allotment procedures under chapter 43.88 RCW, but an appropriation is not required for expenditures.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1604.SL.pdf?cite=2019%20c%20266%20§%2012[2019 c 266 § 12]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2757-S.SL.pdf?cite=2012%20c%20114%20§%201[2012 c 114 § 1]; ]

== 72.40.300 - School for the blind account.
The school for the blind account is created in the custody of the state treasurer. All receipts from contracts, grants, gifts, conveyances, devises, and bequests of real or personal property, or payments received from RCW 72.40.022 (10) and (11) and 72.40.050 must be deposited into the account. Expenditures from the account may be used only for duties related to RCW 72.40.022 (10) and (11) and 72.40.050. Only the superintendent of the school for the blind or the superintendent's designee may authorize expenditures from the account. The account is subject to allotment procedures under chapter 43.88 RCW, but an appropriation is not required for expenditures.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2757-S.SL.pdf?cite=2012%20c%20114%20§%202[2012 c 114 § 2]; ]

