= 72.62 - Vocational education programs.
:toc:

== 72.62.010 - Purpose.
The legislature declares that programs of vocational education are essential to the habilitation and rehabilitation of residents of state correctional institutions and facilities. It is the purpose of this chapter to provide for greater reality and relevance in the vocational education programs within the correctional institutions of the state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c7.pdf?cite=1972%20ex.s.%20c%207%20§%201[1972 ex.s. c 7 § 1]; ]

== 72.62.020 - "Vocational education" defined.
When used in this chapter, unless the context otherwise requires:

The term "vocational education" means a planned series of learning experiences, the specific objective of which is to prepare individuals for gainful employment as semiskilled or skilled workers or technicians or subprofessionals in recognized occupations and in new and emerging occupations, but shall not mean programs the primary characteristic of which is repetitive work for the purpose of production, including the correctional industries program. Nothing in this section shall be construed to prohibit the department of corrections from identifying and establishing trade advisory or apprenticeship committees to advise them on correctional industries work programs.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1371-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2021%20§%2039[2011 1st sp.s. c 21 § 39]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c185.pdf?cite=1989%20c%20185%20§%2012[1989 c 185 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c7.pdf?cite=1972%20ex.s.%20c%207%20§%202[1972 ex.s. c 7 § 2]; ]

== 72.62.030 - Sale of products—Recovery of costs.
Products goods, wares, articles, or merchandise manufactured or produced by residents of state correctional institutions or facilities within or in conjunction with vocational education programs for the training, habilitation, and rehabilitation of inmates may be sold on the open market. When services are performed by residents within or in conjunction with such vocational education programs, the cost of materials used and the value of depreciation of equipment used may be recovered.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c255.pdf?cite=1983%20c%20255%20§%206[1983 c 255 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c7.pdf?cite=1972%20ex.s.%20c%207%20§%203[1972 ex.s. c 7 § 3]; ]

== 72.62.040 - Crediting of proceeds of sales.
The secretary of the department of social and health services or the secretary of corrections, as the case may be, shall credit the proceeds derived from the sale of such products, goods, wares, articles, or merchandise manufactured or produced by inmates of state correctional institutions within or in conjunction with vocational education programs to the institution where manufactured or produced to be deposited in a revolving fund to be expended for the purchase of supplies, materials and equipment for use in vocational education.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c136.pdf?cite=1981%20c%20136%20§%20107[1981 c 136 § 107]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c7.pdf?cite=1972%20ex.s.%20c%207%20§%204[1972 ex.s. c 7 § 4]; ]

== 72.62.050 - Trade advisory and apprenticeship committees.
Labor-management trade advisory and apprenticeship committees shall be constituted by the department for each vocation taught within the vocational education programs in the state correctional system.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c7.pdf?cite=1972%20ex.s.%20c%207%20§%205[1972 ex.s. c 7 § 5]; ]

