= 72.66 - Furloughs for prisoners.
:toc:

== 72.66.010 - Definitions.
As used in this chapter the following words shall have the following meanings:

. "Department" means the department of corrections.

. "Emergency furlough" means a specially expedited furlough granted to a resident to enable him or her to meet an emergency situation, such as the death or critical illness of a member of his or her family.

. "Furlough" means an authorized leave of absence for an eligible resident, without any requirement that the resident be accompanied by, or be in the custody of, any law enforcement or corrections official while on such leave.

. "Resident" means a person convicted of a felony and serving a sentence for a term of confinement in a state correctional institution or facility, or a state approved work or training release facility.

. "Secretary" means the secretary of corrections, or his or her designee or designees.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20486[2012 c 117 § 486]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c136.pdf?cite=1981%20c%20136%20§%20113[1981 c 136 § 113]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c20.pdf?cite=1973%20c%2020%20§%202[1973 c 20 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c58.pdf?cite=1971%20ex.s.%20c%2058%20§%202[1971 ex.s. c 58 § 2]; ]

== 72.66.012 - Granting of furloughs authorized.
The secretary may grant a furlough but only if not precluded from doing so under RCW 72.66.014, 72.66.016, 72.66.018, 72.66.024, 72.66.034, or 72.66.036.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c20.pdf?cite=1973%20c%2020%20§%203[1973 c 20 § 3]; ]

== 72.66.014 - Ineligibility.
A resident may apply for a furlough if he or she is not precluded from doing so under this section. A resident shall be ineligible to apply for a furlough if:

. He or she is not classified by the secretary as eligible for or on minimum security status; or

. His or her minimum term of imprisonment has not been set; or

. He or she has a valid detainer pending and the agency holding the detainer has not provided written approval for him or her to be placed on a furlough-eligible status. Such written approval may include either specific approval for a particular resident or general approval for a class or group of residents.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20487[2012 c 117 § 487]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c20.pdf?cite=1973%20c%2020%20§%204[1973 c 20 § 4]; ]

== 72.66.016 - Minimum time served requirement.
. A furlough shall not be granted to a resident if the furlough would commence prior to the time the resident has served the minimum amounts of time provided under this section:

.. If his or her minimum term of imprisonment is longer than twelve months, he or she shall have served at least six months of the term;

.. If his or her minimum term of imprisonment is less than twelve months, he or she shall have served at least ninety days and shall have no longer than six months left to serve on his or her minimum term;

.. If he or she is serving a mandatory minimum term of confinement, he or she shall have served all but the last six months of such term.

. A person convicted and sentenced for a violent offense as defined in RCW 9.94A.030 is not eligible for furlough until the person has served at least one-half of the minimum term.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5891-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2040%20§%2035[2011 1st sp.s. c 40 § 35]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c255.pdf?cite=1983%20c%20255%20§%208[1983 c 255 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c20.pdf?cite=1973%20c%2020%20§%205[1973 c 20 § 5]; ]

== 72.66.018 - Grounds for granting furlough.
A furlough may only be granted to enable the resident:

. To meet an emergency situation, such as death or critical illness of a member of his or her family;

. To obtain medical care not available in a facility maintained by the department;

. To seek employment or training opportunities, but only when:

.. There are scheduled specific work interviews to take place during the furlough;

.. The resident has been approved for work or training release but his or her work or training placement has not occurred or been concluded; or

.. When necessary for the resident to prepare a parole plan for a parole meeting scheduled to take place within one hundred and twenty days of the commencement of the furlough;

. To make residential plans for parole which require his or her personal appearance in the community;

. To care for business affairs in person when the inability to do so could deplete the assets or resources of the resident so seriously as to affect his or her family or his or her future economic security;

. To visit his or her family for the purpose of strengthening or preserving relationships, exercising parental responsibilities, or preventing family division or disintegration; or

. For any other purpose deemed to be consistent with plans for rehabilitation of the resident.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20488[2012 c 117 § 488]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c20.pdf?cite=1973%20c%2020%20§%206[1973 c 20 § 6]; ]

== 72.66.022 - Application—Contents.
Each resident applying for a furlough shall include in his or her application for the furlough:

. A furlough plan which shall specify in detail the purpose of the furlough and how it is to be achieved, the address at which the applicant would reside, the names of all persons residing at such address[,] and their relationships to the applicant;

. A statement from the applicant's proposed sponsor that he or she agrees to undertake the responsibilities provided in RCW 72.66.024; and

. Such other information as the secretary shall require in order to protect the public or further the rehabilitation of the applicant.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20489[2012 c 117 § 489]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c20.pdf?cite=1973%20c%2020%20§%207[1973 c 20 § 7]; ]

== 72.66.024 - Sponsor.
No furlough shall be granted unless the applicant for the furlough has procured a person to act as his or her sponsor. No person shall qualify as a sponsor unless he or she satisfies the secretary that he or she knows the applicant's furlough plan, is familiar with the furlough conditions prescribed pursuant to RCW 72.66.026, and submits a statement that he or she agrees to:

. See to it that the furloughed person is provided with appropriate living quarters for the duration of the furlough;

. Notify the secretary immediately if the furloughed person does not appear as scheduled, departs from the furlough plan at any time, becomes involved in serious difficulty during the furlough, or experiences problems that affect his or her ability to function appropriately;

. Assist the furloughed person in other appropriate ways, such as discussing problems and providing transportation to job interviews; and

. Take reasonable measures to assist the resident to return from furlough.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20491[2012 c 117 § 491]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20490[2012 c 117 § 490]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c20.pdf?cite=1973%20c%2020%20§%208[1973 c 20 § 8]; ]

== 72.66.026 - Furlough terms and conditions.
The terms and conditions prescribed under this section shall apply to each furlough, and each resident granted a furlough shall agree to abide by them.

. The furloughed person shall abide by the terms of his or her furlough plan.

. Upon arrival at the destination indicated in his or her furlough plan, the furloughed person shall, when so required, report to a state probation and parole officer in accordance with instructions given by the secretary prior to release on furlough. He or she shall report as frequently as may be required by the state probation and parole officer.

. The furloughed person shall abide by all local, state, and federal laws.

. With approval of the state probation and parole officer designated by the secretary, the furloughed person may accept temporary employment during a period of furlough.

. The furloughed person shall not leave the state at any time while on furlough.

. Other limitations on movement within the state may be imposed as a condition of furlough.

. The furloughed person shall not, in any public place, drink intoxicating beverages or be in an intoxicated condition. A furloughed person shall not enter any tavern, bar, or cocktail lounge.

. A furloughed person who drives a motor vehicle shall:

.. Have a valid Washington driver's license in his or her possession;

.. Have the owner's written permission to drive any vehicle not his or her own or his or her spouse's;

.. Have at least minimum personal injury and property damage liability coverage on the vehicle he or she is driving; and

.. Observe all traffic laws.

. Each furloughed person shall carry with him or her at all times while on furlough a copy of his or her furlough order prescribed pursuant to RCW 72.66.028 and a copy of the identification card issued to him or her pursuant to RCW 72.66.032.

. The furloughed person shall comply with any other terms or conditions which the secretary may prescribe.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20492[2012 c 117 § 492]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c20.pdf?cite=1973%20c%2020%20§%209[1973 c 20 § 9]; ]

== 72.66.028 - Furlough order—Contents.
Whenever the secretary grants a furlough, he or she shall do so by a special order which order shall contain each condition and term of furlough prescribed pursuant to RCW 72.66.026 and each additional condition and term which the secretary may prescribe as being appropriate for the particular person to be furloughed.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20493[2012 c 117 § 493]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c20.pdf?cite=1973%20c%2020%20§%2010[1973 c 20 § 10]; ]

== 72.66.032 - Furlough identification card.
The secretary shall issue a furlough identification card to each resident granted a furlough. The card shall contain the name of the resident and shall disclose the fact that he or she has been granted a furlough and the time period covered by the furlough.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20494[2012 c 117 § 494]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c20.pdf?cite=1973%20c%2020%20§%2011[1973 c 20 § 11]; ]

== 72.66.034 - Applicant's personality and conduct—Examination.
Prior to the granting of any furlough, the secretary shall examine the applicant's personality and past conduct and determine whether or not he or she represents a satisfactory risk for furlough. The secretary shall not grant a furlough to any person whom he or she believes represents an unsatisfactory risk.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20495[2012 c 117 § 495]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c20.pdf?cite=1973%20c%2020%20§%2012[1973 c 20 § 12]; ]

== 72.66.036 - Furlough duration—Extension.
. The furlough or furloughs granted to any one resident, excluding furloughs for medical care, may not exceed thirty consecutive days or a total of sixty days during a calendar year.

. Absent unusual circumstances, each first furlough and each second furlough granted to a resident shall not exceed a period of five days and each emergency furlough shall not exceed forty-eight hours plus travel time.

. A furlough may be extended within the maximum time periods prescribed under this section.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c255.pdf?cite=1983%20c%20255%20§%207[1983 c 255 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c20.pdf?cite=1973%20c%2020%20§%2013[1973 c 20 § 13]; ]

== 72.66.038 - Furlough infractions—Reporting—Regaining custody.
Any employee of the department having knowledge of a furlough infraction shall report the facts to the secretary. Upon verification, the secretary shall cause the custody of the furloughed person to be regained, and for this purpose may cause a warrant to be issued.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c20.pdf?cite=1973%20c%2020%20§%2014[1973 c 20 § 14]; ]

== 72.66.042 - Emergency furlough—Waiver of certain requirements.
In the event of an emergency furlough, the secretary may waive all or any portion of RCW 72.66.014(2), 72.66.016, 72.66.022, 72.66.024, and 72.66.026.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c20.pdf?cite=1973%20c%2020%20§%2015[1973 c 20 § 15]; ]

== 72.66.044 - Application proceeding not deemed adjudicative proceeding.
Any proceeding involving an application for a furlough shall not be deemed an adjudicative proceeding under the provisions of chapter 34.05 RCW, the Administrative Procedure Act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c175.pdf?cite=1989%20c%20175%20§%20144[1989 c 175 § 144]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c20.pdf?cite=1973%20c%2020%20§%2016[1973 c 20 § 16]; ]

== 72.66.050 - Revocation or modification of furlough plan—Reapplication.
At any time after approval has been granted for a furlough to any prisoner, such approval or order of furlough may be revoked, and if the prisoner has been released on an order of furlough, he or she may be returned to a state correctional institution, or the plan may be modified, in the discretion of the secretary. Any prisoner whose furlough application is rejected may reapply for a furlough after such period of time has elapsed as shall be determined at the time of rejection by the superintendent or secretary, whichever person initially rejected the application for furlough, such time period being subject to modification.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20496[2012 c 117 § 496]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c58.pdf?cite=1971%20ex.s.%20c%2058%20§%206[1971 ex.s. c 58 § 6]; ]

== 72.66.070 - Transportation, clothing and funds for furloughed prisoners.
The department may provide or arrange for transportation for furloughed prisoners to the designated place of residence within the state and may, in addition, supply funds not to exceed forty dollars and suitable clothing, such clothing to be returned to the institution on the expiration of furlough.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c58.pdf?cite=1971%20ex.s.%20c%2058%20§%208[1971 ex.s. c 58 § 8]; ]

== 72.66.080 - Powers and duties of secretary—Certain agreements—Rules and regulations.
The secretary may enter into agreements with any agency of the state, a county, a municipal corporation or any person, corporation or association for the purpose of implementing furlough plans, and, in addition, may make such rules and regulations in furtherance of this chapter as he or she may deem necessary.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20497[2012 c 117 § 497]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c58.pdf?cite=1971%20ex.s.%20c%2058%20§%209[1971 ex.s. c 58 § 9]; ]

== 72.66.090 - Violation or revocation of furlough—Authority of secretary to issue arrest warrants—Enforcement of warrants by law enforcement officers—Authority of probation and parole officer to suspend furlough.
The secretary may issue warrants for the arrest of any prisoner granted a furlough, at the time of the revocation of such furlough, or upon the failure of the prisoner to report as designated in the order of furlough. Such arrest warrants shall authorize any law enforcement, probation and parole or peace officer of this state, or any other state where such prisoner may be located, to arrest such prisoner and to place him or her in physical custody pending his or her return to confinement in a state correctional institution. Any state probation and parole officer, if he or she has reasonable cause to believe that a person granted a furlough has violated a condition of his or her furlough, may suspend such person's furlough and arrest or cause the arrest and detention in physical custody of the furloughed prisoner, pending the determination of the secretary whether the furlough should be revoked. The probation and parole officer shall report to the secretary all facts and circumstances and the reasons for the action of suspending such furlough. Upon the basis of the report and such other information as the secretary may obtain, he or she may revoke, reinstate, or modify the conditions of furlough, which shall be by written order of the secretary. If the furlough is revoked, the secretary shall issue a warrant for the arrest of the furloughed prisoner and his or her return to a state correctional institution.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20498[2012 c 117 § 498]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c58.pdf?cite=1971%20ex.s.%20c%2058%20§%2010[1971 ex.s. c 58 § 10]; ]

== 72.66.900 - Construction—Chapter applicable to state registered domestic partnerships—2009 c 521.
For the purposes of this chapter, the terms spouse, marriage, marital, husband, wife, widow, widower, next of kin, and family shall be interpreted as applying equally to state registered domestic partnerships or individuals in state registered domestic partnerships as well as to marital relationships and married persons, and references to dissolution of marriage shall apply equally to state registered domestic partnerships that have been terminated, dissolved, or invalidated, to the extent that such interpretation does not conflict with federal law. Where necessary to implement chapter 521, Laws of 2009, gender-specific terms such as husband and wife used in any statute, rule, or other law shall be construed to be gender neutral, and applicable to individuals in state registered domestic partnerships.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%20171[2009 c 521 § 171]; ]

