= 23B.03 - Powers and purposes.
:toc:

== 23B.03.010 - Purposes.
. Every corporation incorporated under this title has the purpose of engaging in any lawful business unless a more limited purpose is set forth in the articles of incorporation.

. Corporations organized for the purposes of banking or engaging in business as an insurer shall not be organized under this title.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%2033[1989 c 165 § 33]; ]

== 23B.03.020 - General powers.
. Unless its articles of incorporation provide otherwise, every corporation has perpetual duration and succession in its corporate name.

. Unless its articles of incorporation provide otherwise, every corporation has the same powers as an individual to do all things necessary or convenient to carry out its business and affairs, including without limitation, power:

.. To sue and be sued, complain, and defend in its corporate name;

.. To have a corporate seal, which may be altered at will, and to use it, or a facsimile of it, by impressing or affixing it or in any other manner reproducing it;

.. To make and amend bylaws, not inconsistent with its articles of incorporation or with the laws of this state, for managing the business and regulating the affairs of the corporation;

.. To purchase, receive, lease, or otherwise acquire, and own, hold, improve, use, and otherwise deal with, real or personal property, or any legal or equitable interest in property, wherever located;

.. To sell, convey, mortgage, pledge, lease, exchange, and otherwise dispose of all or any part of its property;

.. To purchase, receive, subscribe for, or otherwise acquire; own, hold, vote, use, sell, mortgage, lend, pledge, or otherwise dispose of; and deal in and with shares or other interests in, or obligations of, any person;

.. To make contracts, incur liabilities, borrow money, issue its notes, bonds, and other obligations, which may be convertible into or include the option to purchase other securities of the corporation, and secure any of its obligations by mortgage or pledge of any of its property, franchises, or income;

.. To make guarantees respecting the contracts, securities, or obligations of any person; including, but not limited to, any shareholder, affiliated or unaffiliated individual, domestic or foreign corporation, partnership, association, joint venture or trust, if such guarantee may reasonably be expected to benefit, directly or indirectly, the guarantor corporation. As to the enforceability of the guarantee, the decision of the board of directors that the guarantee may be reasonably expected to benefit, directly or indirectly, the guarantor corporation shall be binding in respect to the issue of benefit to the guarantor corporation;

.. To lend money, invest and reinvest its funds, and receive and hold real and personal property as security for repayment;

.. To be a promoter, partner, member, associate, or manager of any partnership, joint venture, trust, or other entity;

.. To conduct its business, locate offices, and exercise the powers granted by this title within or without this state;

.. To elect, appoint, or hire officers, employees, and other agents of the corporation, define their duties, fix their compensation, and lend them money and credit;

.. To fix the compensation of directors, and lend them money and credit;

.. To pay pensions and establish pension plans, pension trusts, profit sharing plans, share bonus plans, share option plans, and benefit or incentive plans for any or all of its current or former directors, officers, employees, and agents;

.. To make donations for the public welfare or for charitable, scientific, or educational purposes;

.. To transact any lawful business that will aid governmental policy; and

.. To make payments or donations, or do any other act, not inconsistent with law, that furthers the business and affairs of the corporation.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%2034[1989 c 165 § 34]; ]

== 23B.03.030 - Emergency powers.
. In anticipation of or during an emergency defined in subsection (4) of this section, the board of directors of a corporation may:

.. Modify lines of succession to accommodate the incapacity of any director, officer, employee, or agent; and

.. Relocate the principal office, designate alternative principal offices or regional offices, or authorize the officers to do so.

. During an emergency defined in subsection (4) of this section, unless emergency bylaws provide otherwise:

.. Notice of a meeting of the board of directors need be given only to those directors whom it is practicable to reach and may be given in any practicable manner, including by publication and radio; and

.. One or more officers of the corporation present at a meeting of the board of directors may be deemed to be directors for the meeting in order of rank and within the same rank in order of seniority, as necessary to achieve a quorum.

. Corporate action taken in good faith during an emergency under this section to further the business affairs of the corporation:

.. Binds the corporation; and

.. May not be used to impose liability on a corporate director, officer, employee, or agent.

. An emergency exists for purposes of this section if a quorum of the corporation's directors cannot readily be assembled because of some catastrophic event.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%2035[1989 c 165 § 35]; ]

== 23B.03.040 - Ultra vires.
. Except as provided in subsection (2) of this section, corporate action may not be challenged on the ground that the corporation lacks or lacked power to act.

. A corporation's power to act may be challenged:

.. In a proceeding by a shareholder against the corporation to enjoin the act;

.. In a proceeding by the corporation, directly, derivatively, or through a receiver, trustee, or other legal representative, against an incumbent or former director, officer, employee, or agent of the corporation; or

.. In a proceeding by the attorney general under RCW 23B.14.300.

. In a shareholder's proceeding under subsection (2)(a) of this section to enjoin an unauthorized corporate act, the court may enjoin or set aside the act, and may award damages for loss suffered by the corporation or another party because of enjoining or setting aside the unauthorized act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%2036[1989 c 165 § 36]; ]

