= 23B.06 - Shares and distributions.
:toc:

== 23B.06.010 - Authorized shares.
. The articles of incorporation must prescribe the classes of shares and the number of shares of each class that the corporation is authorized to issue.

.. If more than one class of shares is authorized, the articles of incorporation must prescribe a distinguishing designation for each class, and, prior to the issuance of shares of a class, the preferences, limitations, voting powers, and relative rights of that class must be described in the articles of incorporation.

.. Preferences, limitations, voting powers, or relative rights of or on any class or series of shares or the holders thereof may be made dependent upon facts objectively ascertainable outside the articles of incorporation in accordance with RCW 23B.01.200(3).

.. All shares of a class must have preferences, limitations, voting powers, and relative rights identical with those of other shares of the same class except to the extent otherwise permitted by (b) of this subsection or RCW 23B.06.020.

. The articles of incorporation must authorize (a) one or more classes of shares that together have unlimited voting rights, and (b) one or more classes of shares, which may be the same class or classes as those with voting rights, that together are entitled to receive the net assets of the corporation upon dissolution.

. The articles of incorporation may authorize one or more classes of shares that:

.. Have special, conditional, or limited voting rights, or no right to vote, except to the extent prohibited by this title;

.. Are redeemable or convertible as specified in the articles of incorporation (i) at the option of the corporation, the shareholder, or another person or upon the occurrence of a designated event, (ii) for cash, indebtedness, securities, or other property, (iii) in a designated amount or in an amount determined in accordance with a designated formula;

.. Entitle the holders to distributions calculated in any manner, including dividends that may be cumulative, noncumulative, or partially cumulative; or

.. Have preference over any other class of shares with respect to distributions, including dividends and distributions upon the dissolution of the corporation.

. Terms of shares may be made dependent on facts objectively ascertainable outside the articles of incorporation in accordance with RCW 23B.01.200(3).

. The description of the designations, preferences, limitations, and relative rights of share classes in subsection (3) of this section is not exhaustive.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2020%20c%20194%20§%205[2020 c 194 § 5]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2387.SL.pdf?cite=1998%20c%20104%20§%201[1998 c 104 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%2044[1989 c 165 § 44]; ]

== 23B.06.020 - Terms of class or series.
. If the articles of incorporation so provide, the board of directors may determine, in whole or part, the preferences, limitations, voting powers, and relative rights, within the limits set forth in RCW 23B.06.010(1)(b) and this section of (a) any class of shares before the issuance of any shares of that class, or (b) one or more series within a class, and designate the number of shares within that series, before the issuance of any shares of that series.

. Each series of a class must be given a distinguishing designation.

. All shares of a series must have preferences, limitations, voting powers, and relative rights identical with those of other shares of the same series, except to the extent otherwise permitted by RCW 23B.06.010(1)(b). All shares of a series must have preferences, limitations, voting powers, and relative rights identical with those of shares of other series of the same class, except to the extent otherwise provided in the description of the series.

. Before issuing any shares of a class or series created under this section, the corporation must deliver to the secretary of state for filing articles of amendment, which are effective without shareholder approval, that set forth:

.. The name of the corporation;

.. The text of the amendment determining the terms of the class or series of shares;

.. The date it was adopted; and

.. The statement that the amendment was duly adopted by the board of directors.

. Unless the articles of incorporation provide otherwise, the board of directors may, after the issuance of shares of a series whose number it is authorized to designate, amend the resolution establishing the series to decrease, but not below the number of shares of such series then outstanding, the number of authorized shares of that series, by filing articles of amendment, which are effective without shareholder approval, in the manner provided in subsection (4) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1068.SL.pdf?cite=2009%20c%20189%20§%206[2009 c 189 § 6]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2387.SL.pdf?cite=1998%20c%20104%20§%202[1998 c 104 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%2045[1989 c 165 § 45]; ]

== 23B.06.030 - Issued and outstanding shares.
. A corporation may issue the number of shares of each class or series authorized by the articles of incorporation. Shares that are issued are outstanding shares until they are reacquired, redeemed, converted, or canceled.

. The reacquisition, redemption, or conversion of outstanding shares is subject to the limitations of subsection (3) of this section and to RCW 23B.06.400.

. At all times that shares of the corporation are outstanding, one or more shares that together have unlimited voting rights and one or more shares that together are entitled to receive the net assets of the corporation upon dissolution must be outstanding.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2020%20c%20194%20§%2014[2020 c 194 § 14]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2301-S.SL.pdf?cite=2002%20c%20297%20§%2017[2002 c 297 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%2046[1989 c 165 § 46]; ]

== 23B.06.040 - Fractional shares.
. A corporation may:

.. Issue fractions of a share or pay in money the value of fractions of a share;

.. Arrange for disposition of fractional shares by the shareholders;

.. Issue scrip in registered or bearer form entitling the holder to receive a full share upon surrendering enough scrip to equal a full share.

. Each certificate representing scrip must be conspicuously labeled "scrip" and must contain the information required by RCW 23B.06.250(2).

. The holder of a fractional share is entitled to exercise the rights of a shareholder, including the right to vote, to receive dividends, and to participate in the assets of the corporation upon liquidation. The holder of scrip is not entitled to any of these rights unless the scrip provides for them.

. The board of directors may approve the issuance of scrip subject to any condition considered desirable, including:

.. That the scrip will become void if not exchanged for full shares before a specified date; and

.. That the shares for which the scrip is exchangeable may be sold and the proceeds paid to the scripholders.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1068.SL.pdf?cite=2009%20c%20189%20§%207[2009 c 189 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%2047[1989 c 165 § 47]; ]

== 23B.06.200 - Subscription for shares before incorporation.
. A written subscription for shares entered into before incorporation is irrevocable for six months unless the subscription agreement provides a longer or shorter period or all the subscribers agree to revocation.

. The board of directors may determine the payment terms of subscriptions for shares that were entered into before incorporation, unless the subscription agreement specifies them. A call for payment by the board of directors must be uniform so far as practicable as to all shares of the same class or series, unless the subscription agreement specifies otherwise.

. Shares issued pursuant to subscriptions entered into before incorporation are fully paid and nonassessable when the corporation receives the consideration specified in the subscription agreement.

. If a subscriber defaults in payment of money or property under a subscription agreement entered into before incorporation, the corporation may collect the amount owed as any other debt. Alternatively, unless the subscription agreement provides otherwise, the corporation may rescind the agreement and may sell the shares if the debt remains unpaid more than twenty days after the corporation delivers a written demand for payment to the subscriber.

. A subscription agreement entered into after incorporation is a contract between the subscriber and the corporation subject to RCW 23B.06.210.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2043[2020 c 57 § 43]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%2048[1989 c 165 § 48]; ]

== 23B.06.210 - Issuance of shares.
. The powers granted in this section to the board of directors may be reserved to the shareholders by the articles of incorporation.

. Any issuance of shares must be approved by the board of directors. Shares may be issued for consideration consisting of any tangible or intangible property or benefit to the corporation, including cash, promissory notes, services performed, contracts for services to be performed, or other securities of the corporation.

. A good faith determination by the board of directors that the consideration received or to be received for the shares to be issued is adequate is conclusive insofar as the adequacy of consideration relates to whether the shares are validly issued, fully paid and nonassessable. When the board of directors has made such a determination and the corporation has received the consideration, the shares issued therefor are fully paid and nonassessable.

. The corporation may place in escrow shares issued for a contract for future services or benefits or a promissory note, or make other arrangements to restrict the transfer of the shares, and may credit distributions in respect to the shares against their purchase price, until the services are performed, the benefits are received, or the note is paid. If the services are not performed, the benefits are not received, or the note is not paid, the shares escrowed or restricted and the distributions credited may be canceled in whole or part.

. Where it cannot be determined that outstanding shares are fully paid and nonassessable, there shall be a conclusive presumption that such shares are fully paid and nonassessable if the board of directors makes a good faith determination that there is no substantial evidence that the full consideration for such shares has not been paid.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1068.SL.pdf?cite=2009%20c%20189%20§%208[2009 c 189 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%2049[1989 c 165 § 49]; ]

== 23B.06.220 - Liability of shareholders.
A purchaser from a corporation of its own shares is not liable to the corporation or its creditors with respect to the shares except to pay the consideration for which the shares were approved to be issued under RCW 23B.06.210 or specified in the subscription agreement under RCW 23B.06.200.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1068.SL.pdf?cite=2009%20c%20189%20§%209[2009 c 189 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%2050[1989 c 165 § 50]; ]

== 23B.06.230 - Share dividends.
. Unless the articles of incorporation provide otherwise, shares may be issued pro rata and without consideration to the corporation's shareholders or to the shareholders of one or more classes or series. An issuance of shares under this subsection is a share dividend.

. Shares of one class or series may not be issued as a share dividend in respect to shares of another class or series unless (a) the articles of incorporation so authorize, (b) a majority of the votes entitled to be cast by the class or series to be issued approve the issue, or (c) there are no outstanding shares of the class or series to be issued.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%2051[1989 c 165 § 51]; ]

== 23B.06.240 - Share options.
. Unless the articles of incorporation provide otherwise, a corporation may issue rights, options, or warrants for the purchase of shares of the corporation. The board of directors shall determine the terms upon which the rights, options, or warrants are issued, their form and content, and the terms and conditions relating to their exercise, including the time or times, the conditions precedent, and the consideration for which and the holders by whom the rights, options, or warrants may be exercised.

. The terms of rights, options, or warrants, including the time or times, the conditions precedent, and the consideration for which and the holders by whom the rights, options, or warrants may be exercised, as well as their duration (a) may preclude or limit the exercise, transfer, or receipt of such rights, options, or warrants or invalidate or void any rights, options, or warrants and (b) may be made dependent upon facts ascertainable outside the documents evidencing them or outside the resolution or resolutions adopted by the board of directors creating such rights, options, or warrants if the manner in which those facts operate on the rights, options, or warrants or the holders thereof is clearly set forth in the documents or the resolutions. For purposes of this section, "facts ascertainable outside the documents evidencing them or outside the resolution or resolutions adopted by the board of directors creating such rights, options, or warrants" includes, but is not limited to, the existence of any condition or the occurrence of any event, including, without limitation, a determination or action by any person or body, including the corporation, its board of directors, or an officer, employee, or agent of the corporation.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2020%20c%20194%20§%206[2020 c 194 § 6]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2387.SL.pdf?cite=1998%20c%20104%20§%203[1998 c 104 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%2052[1989 c 165 § 52]; ]

== 23B.06.250 - Certificates.
. Shares may, but need not, be represented by certificates. Unless this title or another statute expressly provides otherwise, the rights and obligations of shareholders are identical regardless of whether their shares are represented by certificates.

. At a minimum each share certificate must state on its face:

.. The name of the issuing corporation and that it is organized under the laws of this state;

.. The name of the person to whom issued; and

.. The number and class of shares and the designation of the series, if any, the certificate represents.

. If the issuing corporation is authorized to issue different classes of shares or different series within a class, the designations, relative rights, preferences, and limitations applicable to each class and the variations in rights, preferences, and limitations determined for each series, and the authority of the board of directors to determine variations for future series, must be summarized on the front or back of each certificate. Alternatively, each certificate may state conspicuously on its front or back that the corporation will furnish the shareholder this information without charge on request in writing.

. Each share certificate (a) must be executed by two officers designated in the bylaws or by the board of directors and (b) may bear the corporate seal or its facsimile.

. If the person who executed a share certificate no longer holds office when the certificate is issued, the certificate is nevertheless valid.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2044[2020 c 57 § 44]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%2053[1989 c 165 § 53]; ]

== 23B.06.260 - Shares without certificates.
. Unless the articles of incorporation or bylaws provide otherwise, the board of directors of a corporation may approve the issuance of some or all of the shares of any or all of its classes or series without certificates. The approval does not affect shares already represented by certificates until they are surrendered to the corporation.

. Within a reasonable time after the issuance or transfer of shares without certificates, the corporation shall deliver to the shareholder a written statement containing the information required on certificates by RCW 23B.06.250 (2) and (3), and, if applicable, RCW 23B.06.270.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2045[2020 c 57 § 45]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1068.SL.pdf?cite=2009%20c%20189%20§%2010[2009 c 189 § 10]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2301-S.SL.pdf?cite=2002%20c%20297%20§%2018[2002 c 297 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%2054[1989 c 165 § 54]; ]

== 23B.06.270 - Restriction on transfer of shares and other securities.
. The articles of incorporation, bylaws, an agreement among shareholders, or an agreement between shareholders and the corporation may impose restrictions on the transfer or registration of transfer of shares of the corporation. A restriction does not affect shares issued before the restriction was adopted unless the holders of the shares are parties to the restriction agreement or voted in favor of the restriction.

. A restriction on the transfer or registration of transfer of shares is valid and enforceable against the holder or a transferee of the holder if the restriction is authorized by this section and its existence is noted conspicuously on the front or back of the certificate or is contained in the information statement required by RCW 23B.06.260(2). Unless so noted, a restriction is not enforceable against a person without knowledge of the restriction.

. A restriction on the transfer or registration of transfer of shares is authorized:

.. To maintain the corporation's status when it is dependent on the number or identity of its shareholders;

.. To preserve exemptions under federal or state

securities law; or

.. For any other reasonable purpose.

. A restriction on the transfer or registration of transfer of shares may:

.. Obligate the shareholder first to offer the corporation or other persons, separately, consecutively, or simultaneously, an opportunity to acquire the restricted shares;

.. Obligate the corporation or other persons, separately, consecutively, or simultaneously, to acquire the restricted shares;

.. Require the corporation, the holders of any class of its shares, or another person to approve the transfer of the restricted shares, if the requirement is not manifestly unreasonable; or

.. Prohibit the transfer of the restricted shares to designated persons or classes of persons, if the prohibition is not manifestly unreasonable.

. For purposes of this section, "shares" includes a security convertible into or carrying a right to subscribe for or acquire shares.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%2055[1989 c 165 § 55]; ]

== 23B.06.280 - Expense of issue.
A corporation may pay the expenses of selling or underwriting its shares, and of organizing or reorganizing the corporation, from the consideration received for shares.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%2056[1989 c 165 § 56]; ]

== 23B.06.300 - Shareholders' preemptive rights.
. The shareholders of a corporation do not have a preemptive right to acquire the corporation's unissued shares except to the extent the articles of incorporation provide otherwise or as set forth in subsection (2) of this section. A statement included in the articles of incorporation that "the corporation elects to have preemptive rights," or words of similar import, means that the provisions set forth in subsection (3) of this section apply except to the extent that the articles of incorporation provide otherwise.

. Unless the articles of incorporation provide otherwise, the shareholders of a corporation formed before January 1, 2020, have a preemptive right to acquire the corporation's unissued shares.

. If shareholders of a corporation have a preemptive right to acquire the corporation's unissued shares under this section, the following provisions apply:

.. Unless the articles of incorporation provide otherwise, such preemptive right is granted on uniform terms and conditions prescribed by the board of directors to provide a fair and reasonable opportunity to exercise the right, to acquire proportional amounts of the corporation's unissued shares upon the decision of the board of directors to issue them.

.. Unless the articles of incorporation provide otherwise, a shareholder may waive the shareholder's preemptive right. A waiver evidenced by a writing is irrevocable even though it is not supported by consideration.

.. Unless the articles of incorporation provide otherwise, there is no preemptive right with respect to:

... Shares issued as compensation to directors, officers, agents, employees, or other service providers of the corporation, or its subsidiaries or affiliates;

... Shares issued to satisfy conversion or option rights created to provide compensation to directors, officers, agents, or employees of the corporation, or its subsidiaries or affiliates;

... Shares issued pursuant to the corporation's initial plan of financing; and

... Shares issued for consideration other than money.

.. Unless the articles of incorporation provide otherwise:

... Holders of shares of any class without general voting rights but with preferential rights to distributions or assets have no preemptive rights with respect to shares of any class; and

... Holders of shares of any class with general voting rights but without preferential rights to distributions or assets have no preemptive rights with respect to shares of any class with preferential rights to distributions or assets unless the shares with preferential rights are convertible into or carry a right to subscribe for or acquire shares without preferential rights.

.. Unless the articles of incorporation provide otherwise, shares subject to preemptive rights that are not acquired by shareholders may be issued to any person for a period of one year after being offered to shareholders at a consideration set by the board of directors that is not lower than the consideration set for the exercise of preemptive rights. An offer at a lower consideration or after the expiration of one year is subject to the shareholders' preemptive rights.

.. For purposes of this section, "shares" includes a security convertible into or carrying a right to subscribe for or acquire shares.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2046[2020 c 57 § 46]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5003-S.SL.pdf?cite=2019%20c%20141%20§%202[2019 c 141 § 2]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2301-S.SL.pdf?cite=2002%20c%20297%20§%2019[2002 c 297 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%2057[1989 c 165 § 57]; ]

== 23B.06.310 - Corporation's acquisition of its own shares.
. A corporation may acquire its own shares and shares so acquired constitute authorized but unissued shares.

. If the articles of incorporation prohibit the reissue of acquired shares, the number of authorized shares is reduced by the number of shares acquired, effective upon amendment of the articles of incorporation.

. The board of directors may adopt articles of amendment under this section without shareholder approval and deliver them to the secretary of state for filing. The articles must set forth:

.. The name of the corporation;

.. The reduction in the number of authorized shares, itemized by class and series; and

.. The total number of authorized shares, itemized by class and series, remaining after reduction of the shares.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1068.SL.pdf?cite=2009%20c%20189%20§%2011[2009 c 189 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%2058[1989 c 165 § 58]; ]

== 23B.06.400 - Distributions to shareholders.
. A board of directors may approve and the corporation may make distributions to its shareholders subject to restriction by the articles of incorporation and the limitation in subsection (2) of this section.

. No distribution may be made if, after giving it effect:

.. The corporation would not be able to pay its liabilities as they become due in the usual course of business; or

.. The corporation's total assets would be less than the sum of its total liabilities plus, unless the articles of incorporation permit otherwise, the amount that would be needed, if the corporation were to be dissolved at the time of the distribution, to satisfy the preferential rights upon dissolution of shareholders whose preferential rights are superior to those receiving the distribution.

. For purposes of determinations under subsection (2) of this section:

.. The board of directors may base a determination that a distribution is not prohibited under subsection (2) of this section either on financial statements prepared on the basis of accounting practices and principles that are reasonable in the circumstances or on a fair valuation or other method that is reasonable in the circumstances; and

.. Indebtedness of a corporation, including indebtedness issued as a distribution, is not considered a liability if its terms provide that payment of principal and interest are made only if and to the extent that payment of a distribution to shareholders could then be made under this section.

. The effect of a distribution under subsection (2) of this section is measured:

.. In the case of a distribution of indebtedness, the terms of which provide that payment of principal and interest are made only if and to the extent that payment of a distribution to shareholders could then be made under this section, each payment of principal or interest is treated as a distribution, the effect of which is measured on the date the payment is actually made; or

.. In the case of any other distribution:

... If the distribution is by purchase, redemption, or other acquisition of the corporation's shares, the effect of the distribution is measured as of the earlier of the date any money or other property is transferred or debt incurred by the corporation, or the date the shareholder ceases to be a shareholder with respect to the acquired shares;

... If the distribution is of indebtedness other than that described in subsection (4) (a) and (b)(i) of this section, the effect of the distribution is measured as of the date the indebtedness is distributed; and

... In all other cases, the effect of the distribution is measured as of the date the distribution is approved if payment occurs within one hundred twenty days after the date of approval, or the date the payment is made if it occurs more than one hundred twenty days after the date of approval.

. A corporation's indebtedness to a shareholder incurred by reason of a distribution made in accordance with this section is at parity with the corporation's indebtedness to its general, unsecured creditors except to the extent provided otherwise by agreement.

. In circumstances to which this section and related sections of this title are applicable, such provisions supersede the applicability of any other statutes of this state with respect to the legality of distributions.

. A transfer of the assets of a dissolved corporation to a trust or other successor entity of the type described in RCW 23B.14.030(4) constitutes a distribution subject to subsection (2) of this section only when and to the extent that the trust or successor entity distributes assets to shareholders.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1068.SL.pdf?cite=2009%20c%20189%20§%2012[2009 c 189 § 12]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6596.SL.pdf?cite=2006%20c%2052%20§%202[2006 c 52 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c178.pdf?cite=1990%20c%20178%20§%2010[1990 c 178 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%2059[1989 c 165 § 59]; ]

