= 23B.900 - Construction.
:toc:

== 23B.900.010 - Savings provisions—1989 c 165.
. Except as provided in subsection (2) of this section, the repeal of a statute by this title does not affect:

.. The operation of the statute or any action taken under it before its repeal;

.. Any ratification, right, remedy, privilege, obligation, or liability acquired, accrued, or incurred under the statute before its repeal;

.. Any violation of the statute, or any penalty, forfeiture, or punishment incurred because of the violation, before its repeal; or

.. Any proceeding, reorganization, or dissolution commenced under the statute before its repeal, and the proceeding, reorganization, or dissolution may be completed in accordance with the statute as if it had not been repealed.

. If a penalty or punishment imposed for violation of a statute repealed by this title is reduced by this title, the penalty or punishment if not already imposed shall be imposed in accordance with this title.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%20202[1989 c 165 § 202]; ]

== 23B.900.030 - Repealer—1989 c 165.
See 1989 c 165 s 204.

[ ]

== 23B.900.040 - Effective date—1989 c 165.
This title shall take effect July 1, 1990.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%20205[1989 c 165 § 205]; ]

== 23B.900.050 - Section headings—1989 c 165.
Section headings as used in this title do not constitute any part of the law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%20206[1989 c 165 § 206]; ]

