= 23B.30 - Defective corporate actions.
:toc:

== 23B.30.010 - Definitions.
As used in this chapter:

. "Date of the defective corporate action" means the date the defective corporate action was purported to have been taken, or, if the exact date is unknown, the approximate date thereof.

. "Defective corporate action" means (a) any corporate action purportedly taken that is, and at the time such corporate action was purportedly taken would have been, within the power of the corporation, but is void or voidable due to a failure of authorization, and (b) an overissue.

. "Failure of authorization" means the failure to authorize, approve, or otherwise effect a corporate action in compliance with the provisions of this title, the articles of incorporation or bylaws of the corporation, a corporate resolution, or any plan or agreement to which the corporation is a party, if and to the extent such failure would render such corporate action void or voidable.

. "Overissue" means the purported issuance of:

.. Shares of a class or series in excess of the number of shares of a class or series the corporation was authorized to issue in accordance with RCW 23B.06.010 at the time of such purported issuance; or

.. Shares of any class or series that was not authorized for issuance by the articles of incorporation at the time of such purported issuance.

. "Putative shares" means the shares of any class or series of the corporation (including shares issuable upon exercise of rights, options, warrants, or other securities convertible into shares of the corporation, or interests with respect thereto) that were purportedly created or issued as a result of a defective corporate action, that:

.. But for any failure of authorization would constitute valid shares; or

.. Cannot be determined by the board of directors to be valid shares.

. "Valid shares" means the shares of any class or series of the corporation that have been duly authorized and validly issued in accordance with this title, including as a result of ratification or validation in accordance with this chapter.

. [Empty]
.. "Validation effective time," with respect to any defective corporate action ratified or validated in accordance with this chapter, means the later of:

... The time at which the ratification of the defective corporate action is approved by shareholders, or if approval of shareholders is not required, the time at which the notice required by RCW 23B.30.050 becomes effective in accordance with RCW 23B.01.410; and

... The time at which any articles of validation filed in accordance with RCW 23B.30.070 become effective.

.. The validation effective time will not be affected by the commencement or pendency of any proceeding in accordance with RCW 23B.30.080(1)(b) or otherwise, unless otherwise ordered by the court.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5011.SL.pdf?cite=2017%20c%2028%20§%201[2017 c 28 § 1]; ]

== 23B.30.020 - Chapter not exclusive.
. A defective corporate action is not void or voidable solely as a result of a failure of authorization if ratified in accordance with RCW 23B.30.030 or validated in accordance with RCW 23B.30.080.

. Ratification under RCW 23B.30.030 or validation under RCW 23B.30.080 is not the exclusive means of ratifying or validating any defective corporate action, and the absence or failure of ratification or validation in accordance with this chapter does not, of itself, affect the validity or effectiveness of any corporate action properly ratified under common law or otherwise, nor does it create a presumption that any such corporate action is or was a defective corporate action or void or voidable.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5011.SL.pdf?cite=2017%20c%2028%20§%202[2017 c 28 § 2]; ]

== 23B.30.030 - Ratification.
. Except as otherwise required by subsection (2) of this section, to ratify a defective corporate action under this chapter, the board of directors must adopt a resolution stating:

.. The defective corporate action to be ratified and, if the defective corporate action involved the purported issuance of putative shares, the number and class or series of putative shares purportedly issued;

.. The date of the defective corporate action and, if the defective corporate action involved the purported issuance of putative shares, the date or dates on which the putative shares were purportedly issued;

.. The nature of the failure of authorization with respect to the defective corporate action to be ratified; and

.. That the ratification of the defective corporate action is approved.

. To ratify a defective corporate action under this chapter involving the election of the initial board of directors of the corporation under RCW 23B.02.050(1)(b), a majority of the persons who, at the time of the ratification, are exercising the powers of directors must adopt a resolution stating:

.. The name of the person or persons who first purportedly approved corporate action as initial directors of the corporation;

.. The earlier of the date on which that person or those persons first purportedly approved corporate action or purportedly were elected as initial directors; and

.. That the ratification of the election of that person or those persons as the initial directors of the corporation is approved.

. If any provision of this title, the articles of incorporation or bylaws, any corporate resolution, or any plan or agreement to which the corporation is a party at the time the resolution required by subsection (1) of this section is adopted, would have required shareholder approval of the defective corporate action to be ratified, either on the date of the defective corporate action or at the time the resolution required by subsection (1) of this section is adopted, for the ratification of the defective corporate action to be approved:

.. The board of directors must submit the ratification of the defective corporate action for approval by the shareholders in accordance with RCW 23B.30.040;

.. The board of directors must recommend the ratification of the defective corporate action to the shareholders unless (i) the board of directors determines that because of conflict of interest or other special circumstances it should make no recommendation or (ii) RCW 23B.08.245 applies, and in either case the board of directors communicates the basis for so proceeding to the shareholders; and

.. The shareholders entitled to vote must approve the ratification of the defective corporate action as provided in RCW 23B.30.040.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5011.SL.pdf?cite=2017%20c%2028%20§%203[2017 c 28 § 3]; ]

== 23B.30.040 - Ratification—Quorum—Voting.
. The quorum and voting requirements applicable to the adoption by the board of directors of the resolution required by RCW 23B.30.030(1) are the quorum and voting requirements that would be applicable if the defective corporate action was being approved at the time the resolution required by RCW 23B.30.030(1) is adopted.

. Except as provided in subsection (3) of this section, the quorum and voting requirements applicable to the approval by shareholders of the ratification of the defective corporate action required by RCW 23B.30.030(3) are the quorum and voting requirements that would be applicable if the defective corporate action was being approved at the time the ratification of the defective corporate action is approved.

. The approval by shareholders of the ratification of a defective corporate action under this chapter involving the election of directors requires that the votes cast within a voting group favoring such ratification exceed the votes cast within the voting group opposing such ratification at a meeting at which a quorum is present.

. Putative shares on the record date for determining the shareholders entitled to vote on any matter submitted to shareholders in accordance with RCW 23B.30.030(3) (and without giving effect to any ratification of a defective corporate action involving the purported issuance of putative shares that would become valid shares as a result of the approval of such matter) are neither entitled to vote nor to be counted for quorum purposes in any vote to approve the ratification of any defective corporate action.

. If the ratification of a defective corporate action involving the purported issuance of putative shares would result in an overissue, in addition to the approval required by RCW 23B.30.030, the board of directors and shareholders must approve an amendment to the articles of incorporation in accordance with chapter 23B.10 RCW to increase the number of shares of a class or series that the corporation is authorized to issue or to create a class or series of shares that the corporation is authorized to issue so there would be no overissue.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5011.SL.pdf?cite=2017%20c%2028%20§%204[2017 c 28 § 4]; ]

== 23B.30.050 - Ratification and validation—Notice.
. If the ratification of a defective corporate action does not require approval of the shareholders under RCW 23B.30.030(3):

.. The corporation shall notify, promptly after the adoption of the resolution described in RCW 23B.30.030 (1) or (2), each holder of valid shares and putative shares, whether or not entitled to vote, as of the date of the adoption of that resolution by the board of directors, that the ratification of a defective corporate action has been approved by the board of directors pursuant to RCW 23B.30.030. This notice must also be given to each person who was a holder of valid shares or putative shares, whether or not entitled to vote, as of the date of the defective corporate action, other than to those persons whose identities or addresses for notice cannot be determined from the records of the corporation.

.. The notice specified in (a) of this subsection must contain or be accompanied by (i) a copy of the resolution adopted by the board of directors in accordance with RCW 23B.30.030 (1) or (2), or (ii) the information required by RCW 23B.30.030 (1) (a) through (d) or (2) (a) through (c), as applicable. This notice must also include a statement that any action before a court to determine whether the ratification of the defective corporate action complied with the requirements imposed by this chapter must be brought within sixty days from the validation effective time.

. If the ratification of a defective corporate action requires approval of the shareholders under RCW 23B.30.030(3), and if the approval of the shareholders is to be given at a meeting:

.. The corporation shall notify each holder of valid shares and putative shares, whether or not entitled to vote, as of the record date for the meeting, of the proposed meeting of shareholders at which the ratification is to be submitted for approval in accordance with RCW 23B.07.050. This notice must also be given to each person who was a holder of valid shares or putative shares, whether or not entitled to vote, as of the date of the defective corporate action, other than to those persons whose identities or addresses for notice cannot be determined from the records of the corporation; and

.. The notice specified in (a) of this subsection must state that the purpose, or one of the purposes, of the meeting is to consider ratification of a defective corporate action and must contain or be accompanied by (i) a copy of the resolution adopted by the board of directors in accordance with RCW 23B.30.030(1), or (ii) the information required by RCW 23B.30.030(1) (a) through (d). This notice must also include a statement that any action before a court to determine whether the ratification of the defective corporate action complied with the requirements imposed by this chapter must be brought within sixty days from the validation effective time.

. If the ratification of a defective corporate action requires approval of the shareholders under RCW 23B.30.030(3), and if the approval of the shareholders is to be without a meeting or a vote in accordance with RCW 23B.07.040:

.. The corporation or the person soliciting consents shall give the notice required under RCW 23B.07.040(3)(a) and the corporation shall give the notice required under RCW 23B.07.040(3)(b) to each holder of valid shares and putative shares, whether or not entitled to vote, as of the record date for the shareholder consent. These notices must also be given to each person who was a holder of valid shares or putative shares, whether or not entitled to vote, as of the date of the defective corporate action, other than to those persons whose identities or addresses for notice cannot be determined from the records of the corporation; and

.. The notices specified in (a) of this subsection must describe the ratification of the defective corporate action being approved and must contain or be accompanied by (i) a copy of the resolution adopted by the board of directors in accordance with RCW 23B.30.030 (1) or (2), or (ii) the information required by RCW 23B.30.030 (1)(a) through (d) or (2)(a) through (c), as applicable. These notices must also include a statement that any action before a court to determine whether the ratification of the defective corporate action complied with the requirements imposed by this chapter must be brought within sixty days from the validation effective time.

. If a defective corporate action is validated in accordance with RCW 23B.30.080:

.. The corporation shall notify, promptly after the validation, each holder of valid shares and putative shares, whether or not entitled to vote, as of the date of the validation, that the validation of a defective corporate action has taken place pursuant to RCW 23B.30.080. This notice must also be given to each person who was a holder of valid shares or putative shares, whether or not entitled to vote, as of the date of the defective corporate action, other than to those persons whose identities or addresses for notice cannot be determined from the records of the corporation.

.. The notice specified in (a) of this subsection must contain or be accompanied by a copy of the information required by RCW 23B.30.080(2).

. Any notice required by this section may be given in any manner permitted by RCW 23B.01.410 and, for any corporation subject to the reporting requirements of section 13 or 15(d) of the securities exchange act of 1934, as amended, may be given by filing or furnishing the notice with the United States securities and exchange commission.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5011.SL.pdf?cite=2017%20c%2028%20§%205[2017 c 28 § 5]; ]

== 23B.30.060 - Ratification and validation—Effect.
From and after the validation effective time:

. Each defective corporate action ratified in accordance with RCW 23B.30.030 or validated in accordance with RCW 23B.30.080:

.. Is not void or voidable as a result of the failure of authorization identified (i) in the resolution adopted by the board of directors in accordance with RCW 23B.30.030 (1) or (2), or (ii) by the court in accordance with RCW 23B.30.080(2); and

.. Is deemed to be a valid corporate action taken on the date of the defective corporate action;

. The issuance of each putative share or fraction of a putative share purportedly issued pursuant to a defective corporate action identified in the resolution adopted by the board of directors in accordance with RCW 23B.30.030(1) or by the court in accordance with RCW 23B.30.080(2) is not void or voidable as a result of the failure of authorization identified in that resolution or by that court, and each such putative share or fraction of a putative share is deemed to be an identical valid share or fraction of a valid share issued at the time it was purportedly issued; and

. Any corporate action taken subsequent to the date of the defective corporate action ratified or validated in accordance with this chapter in reliance on that defective corporate action having been validly taken, and any subsequent defective corporate action resulting directly or indirectly from that original defective corporate action, is deemed to be valid as of the time that corporate action was taken.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5011.SL.pdf?cite=2017%20c%2028%20§%206[2017 c 28 § 6]; ]

== 23B.30.070 - Defective corporate action—Filings—Articles of validation.
. If a defective corporate action ratified or validated under this chapter would have required under any other section of this title a document to be filed with the secretary of state, then, whether or not a document was previously filed in respect of that defective corporate action and in lieu of filing the document otherwise required by this title, the corporation shall deliver to the secretary of state for filing articles of validation setting forth:

.. The defective corporate action that was ratified or validated and, if the defective corporate action involved the purported issuance of putative shares, the number and class or series of putative shares purportedly issued;

.. The date of the defective corporate action that was ratified or validated and, if the defective corporate action involved the purported issuance of putative shares, the date or dates on which the putative shares were purportedly issued;

.. The nature of the failure of authorization with respect to the defective corporate action that was ratified or validated;

.. A statement that the defective corporate action was (i) ratified in accordance with RCW 23B.30.030, including the date on which the board of directors ratified the defective corporate action and the date, if any, on which the shareholders approved the ratification of the defective corporate action, or (ii) validated in accordance with RCW 23B.30.080, including the date on which the court validated the defective corporate action; and

.. The information required by subsection (2) of this section.

. The articles of validation must also contain the following information:

.. If the corporation previously filed a document in respect of a defective corporate action that was ratified or validated and no changes to that document are required to give effect to the ratification or validation of the defective corporate action in accordance with RCW 23B.30.040(5), the corporation shall (i) describe the document, together with any articles of correction thereto, including its filing date, in the articles of validation, and (ii) attach a copy of the document, together with any articles of correction thereto, to the articles of validation;

.. If the corporation previously filed a document in respect of a defective corporate action that was ratified or validated and any change to that document is required to give effect to the ratification or validation of the defective corporate action in accordance with RCW 23B.30.040(5), the corporation shall (i) describe the previously filed document, together with any articles of correction thereto, including its filing date, (ii) attach a copy of the document containing all of the information required to be included under the applicable section or sections of this title to give effect to the defective corporate action that was ratified or validated to the articles of validation, and (iii) state the date and time that the filing is deemed to have become effective; or

.. If the corporation did not previously file a document in respect of a defective corporate action that was ratified or validated and that defective corporate action would have required a filing under any other section of this title, the corporation shall (i) attach a copy of a document containing all of the information required to be included under the applicable section or sections of this title to give effect to the defective corporate action that was ratified or validated to the articles of validation, and (ii) state the date and time that the filing is deemed to have become effective.

. Articles of validation that comply with this section supersede any other document in respect of a defective corporate action that was ratified in accordance with RCW 23B.30.030 or validated in accordance with RCW 23B.30.080.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2079[2020 c 57 § 79]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5011.SL.pdf?cite=2017%20c%2028%20§%207[2017 c 28 § 7]; ]

== 23B.30.080 - Judicial proceedings to validate or challenge ratification.
. Upon application by the corporation, any successor entity to the corporation, a director of the corporation, or any shareholder of the corporation, including any person who was a shareholder of the corporation as of the date of a defective corporate action, the superior courts may:

.. Validate any defective corporate action that has not been ratified in accordance with RCW 23B.30.030; or

.. Determine that any ratification of a defective corporate action under RCW 23B.30.030 is not valid or effective because it failed to comply with the procedural requirements imposed by this chapter.

. In connection with a proceeding under subsection (1)(a) of this section, the court shall identify the defective corporate action to be validated, including the information required under RCW 23B.30.030 (1)(a) through (c) or (2)(a) and (b), as applicable, and may make such findings or orders as it deems proper under the circumstances. In determining whether to validate a defective corporate action under subsection (1)(a) of this section, the court may consider the following:

.. Whether the defective corporate action was originally approved or effectuated with the belief that the approval or effectuation was in compliance with the provisions of this title, the articles of incorporation or bylaws of the corporation, and any corporate resolution or plan or agreement of or to which the corporation is a party that would be relevant in determining whether there was a failure of authorization;

.. Whether the corporation and board of directors has treated the defective corporate action as a valid action or transaction;

.. Whether any person has acted in reliance on the public record that the defective corporate action was valid or would be harmed by the failure to validate the defective corporate action;

.. Whether any person would be harmed by the validation of the defective corporate action, excluding any harm that would have resulted if the defective corporate action had been valid when approved or effectuated; and

.. Any other factors or considerations that the court deems proper in the circumstances.

. The court shall stay any proceeding brought under subsection (1)(a) of this section during any ratification process under RCW 23B.30.030 involving the defective corporate action that is the subject of the proceeding until the earlier of:

.. The validation effective time; and

.. [Empty]
... If shareholder approval is not required for ratification, the date on which the board of directors votes, but fails to ratify, the defective corporate action, (ii) if shareholder approval is required for ratification in accordance with RCW 23B.30.040 and is to be given at a meeting, the date on which the shareholders vote, but fail to ratify, the defective corporate action, or (iii) if shareholder approval is required for ratification in accordance with RCW 23B.30.040 and is to be given without a meeting, sixty days after the date of execution indicated on the earliest dated shareholder consent approving the ratification that is delivered to the corporation, even though that shareholder consent may not have been delivered to the corporation on that date, if consents executed by a sufficient number of shareholders to approve the ratification are not delivered to the corporation during that sixty-day period.

. Notwithstanding any other provision of this section or otherwise under applicable law, any proceeding asserting a claim under subsection (1)(b) of this section must be brought within sixty days after the validation effective time, except that this subsection will not apply to any person to whom notice of the ratification was required to have been given pursuant to RCW 23B.30.050, but to whom such notice was not given. Claims under subsection (1)(b) of this section are to be the exclusive basis for challenging the validity or effectiveness of a defective corporate action ratified under RCW 23B.30.030.

. Service of process on the corporation for any proceeding under this section may be made in any manner provided by statute of this state or by rule of the court for service on the corporation, and no other party need be joined in order for the court to adjudicate the matter. In a proceeding commenced by the corporation, the court may require notice of the proceeding to be provided to other persons specified by the court and permit such other persons to intervene in the proceeding.

. For purposes of this section, "shareholder" includes a beneficial owner whose shares are held in a voting trust or held by a nominee on behalf of the beneficial owner.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5011.SL.pdf?cite=2017%20c%2028%20§%208[2017 c 28 § 8]; ]

