= 23B.01 - General provisions.
:toc:

== 23B.01.010 - Short title.
This title shall be known and may be cited as the "Washington business corporation act."

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%201[1989 c 165 § 1]; ]

== 23B.01.020 - Reservation of power to amend or repeal.
The legislature has power to amend or repeal all or part of this title at any time and all domestic and foreign corporations subject to this title are governed by the amendment or repeal.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%202[1989 c 165 § 2]; ]

== 23B.01.200 - Filing requirements.
. A document required or permitted by this title to be filed in the office of the secretary of state must satisfy the requirements of Article 2 of chapter 23.95 RCW, this section, and any other section that adds to or varies from these requirements, to be entitled to filing by the secretary of state.

. Unless otherwise indicated in this title, all documents delivered to the secretary of state for filing must be executed:

.. By the chairperson of the board of directors of a domestic or foreign corporation, by its president, or by another of its officers;

.. If directors have not been selected or the corporation has not been formed, by an incorporator; or

.. If the corporation is in the hands of a receiver, trustee, or other court-appointed fiduciary, by that fiduciary.

. Whenever a provision of this title permits any of the terms of a plan or a filed document to be dependent on facts objectively ascertainable outside the plan or filed document, the following provisions apply:

.. The manner in which the facts will operate upon the terms of the plan or filed document must be included in the plan or filed document.

.. The facts may include:

... Any of the following that is available in a nationally recognized news or information medium, either in print or electronically: Statistical or market indices, market prices of any security or group of securities, interest rates, currency exchange rates, or similar economic or financial data;

... A determination or action by any person or body, including the corporation, its board of directors, an officer, an employee, or an agent of the corporation, or any other party to a plan or filed document; or

... The terms of, or actions taken under, an agreement to which the corporation is a party, or any other agreement or document.

.. As used in this subsection (3):

... "Filed document" means a document filed by the secretary of state under any provision of this title, except chapter 23B.15 RCW or RCW 23.95.255 with respect to business corporations.

... "Plan" means a plan of conversion, merger, or share exchange.

.. The following provisions of a plan or filed document may not be made dependent on facts outside the plan or filed document:

... The name and address of any person required in a filed document;

... The registered agent of any entity required in a filed document;

... The duration of the corporation's existence, if less than perpetual;

... The number of authorized shares and designation of each class or series of shares;

.. The effective date of a filed document; and

.. Any required statement in a filed document of the date on which the underlying transaction was approved or the manner in which that approval was given.

.. If a provision of a filed document is made dependent on a fact ascertainable outside of the filed document and that fact is not ascertainable by reference to a source described in (b)(i) of this subsection or another publicly available or accessible document, then the corporation must either (i) notify the affected shareholders of the fact, or (ii) file with the secretary of state articles of amendment to the filed document stating the fact, in either case promptly after the time when the fact is first ascertainable or thereafter changes.

.. Unless the articles of incorporation, a bylaw, or a resolution adopted or approved by the board of directors or shareholders provide otherwise, articles of amendment under (e) of this subsection are deemed to be adopted or approved by the adoption or approval of the original filed document to which they relate and may be filed by the corporation without further adoption or approval by the board of directors or the shareholders.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2020%20c%20194%20§%204[2020 c 194 § 4]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2034[2020 c 57 § 34]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%202101[2015 c 176 § 2101]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2301-S.SL.pdf?cite=2002%20c%20297%20§%201[2002 c 297 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=1991%20c%2072%20§%2024[1991 c 72 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%203[1989 c 165 § 3]; ]

== 23B.01.202 - Certificate of authority as insurance company—Filing of records.
For those corporations that have a certificate of authority, are applying for, or intend to apply for a certificate of authority from the insurance commissioner as an insurance company under chapter 48.05 RCW, whenever under this chapter corporate records are required to be filed with the secretary of state, the records shall be filed with the insurance commissioner rather than the secretary of state.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2301-S.SL.pdf?cite=2002%20c%20297%20§%202[2002 c 297 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1065-S2.SL.pdf?cite=1998%20c%2023%20§%205[1998 c 23 § 5]; ]

== 23B.01.204 - Certificate of authority from department of financial institutions—Filing of records.
For those corporations that have a certificate of authority, are applying for, or intend to apply for a certificate of authority from the department of financial institutions as a bank, trust company, or the holding company thereof, under *Title 30 RCW, or as a savings bank or holding company thereof, under Title 32 RCW, or for any other corporation or other entity which is or purports to be a bank, savings bank, savings and loan association, trust company, industrial loan bank, credit union, bank holding company, financial services holding company, or savings and loan holding company, whenever under this chapter corporate records are required to be filed with the secretary of state, the records shall be filed with the department of financial institutions.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2831.SL.pdf?cite=2010%20c%2088%20§%201[2010 c 88 § 1]; ]

== 23B.01.220 - Fees.
Corporations are subject to the applicable fees, charges, and penalties established by the secretary of state under RCW 23.95.260 and 43.07.120.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%202102[2015 c 176 § 2102]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2301-S.SL.pdf?cite=2002%20c%20297%20§%203[2002 c 297 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5492-S.SL.pdf?cite=1993%20c%20269%20§%202[1993 c 269 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6461-S.SL.pdf?cite=1992%20c%20107%20§%207[1992 c 107 § 7]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=1991%20c%2072%20§%2026[1991 c 72 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c178.pdf?cite=1990%20c%20178%20§%201[1990 c 178 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%205[1989 c 165 § 5]; ]

== 23B.01.230 - Effective time and date of document.
A document filed with the secretary of state is effective as provided in RCW 23.95.210, and may state a delayed effective date and time in accordance with RCW 23.95.210.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2035[2020 c 57 § 35]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%202103[2015 c 176 § 2103]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2301-S.SL.pdf?cite=2002%20c%20297%20§%204[2002 c 297 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%206[1989 c 165 § 6]; ]

== 23B.01.240 - Correcting filed documents.
A domestic or foreign corporation may correct a document filed by the secretary of state in accordance with RCW 23.95.220.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2036[2020 c 57 § 36]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%202104[2015 c 176 § 2104]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2301-S.SL.pdf?cite=2002%20c%20297%20§%205[2002 c 297 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%207[1989 c 165 § 7]; ]

== 23B.01.250 - Filing duty of secretary of state.
RCW 23.95.225 governs the secretary of state's duty to file documents delivered to the secretary of state for filing, the manner and effect of filing, and procedures that apply when the secretary of state refuses to file a document.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2037[2020 c 57 § 37]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%202105[2015 c 176 § 2105]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2301-S.SL.pdf?cite=2002%20c%20297%20§%206[2002 c 297 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%208[1989 c 165 § 8]; ]

== 23B.01.280 - Certificate of existence or registration.
Any person may apply to the secretary of state under RCW 23.95.235 to furnish a certificate of existence for a domestic corporation or a certificate of registration for a foreign corporation.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%202106[2015 c 176 § 2106]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=1991%20c%2072%20§%2027[1991 c 72 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%2011[1989 c 165 § 11]; ]

== 23B.01.290 - Penalty for signing false document.
RCW 23.95.240 governs the penalty that applies for executing a false document that is intended to be delivered to the secretary of state for filing.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2038[2020 c 57 § 38]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%202107[2015 c 176 § 2107]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%2012[1989 c 165 § 12]; ]

== 23B.01.300 - Powers.
The secretary of state has the power reasonably necessary to perform the duties required of the secretary of state by this title, including adoption, amendment, or repeal of rules for the efficient administration of this title.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%2013[1989 c 165 § 13]; ]

== 23B.01.400 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this title.

. "Articles of incorporation" include amended and restated articles of incorporation and articles of merger.

. "Authorized shares" means the shares of all classes a domestic or foreign corporation is authorized to issue.

. "Conspicuous" means so prepared that a reasonable person against whom the writing is to operate should have noticed it. For example, text in italics, boldface, contrasting color, capitals, or underlined is conspicuous.

. "Controlling interest" means ownership of an entity's outstanding shares or interests in such number as to entitle the holder at the time to elect a majority of the entity's directors or other governors without regard to voting power which may thereafter exist upon a default, failure, or other contingency.

. "Corporate action" means any resolution, act, policy, contract, transaction, plan, adoption or amendment of articles of incorporation or bylaws, or other matter approved by or submitted for approval to a corporation's incorporators, board of directors or a committee thereof, or shareholders.

. "Corporation" or "domestic corporation" means a corporation for profit, including a social purpose corporation, which is not a foreign corporation, incorporated under or subject to the provisions of this title.

. "Deliver" or "delivery" means any method of delivery used in conventional commercial practice, including delivery by hand, mail, commercial delivery, and, if authorized in accordance with RCW 23B.01.410, by electronic transmission.

. "Distribution" means a direct or indirect transfer of money or other property, except its own shares, or incurrence of indebtedness by a corporation to or for the benefit of its shareholders in respect to any of its shares. A distribution may be in the form of a declaration or payment of a dividend; a distribution in partial or complete liquidation, or upon voluntary or involuntary dissolution; a purchase, redemption, or other acquisition of shares; a distribution of indebtedness; or otherwise.

. "Document" means:

.. Any tangible medium on which information is inscribed, and includes handwritten, typed, printed, or similar instruments or copies of such instruments; and

.. An electronic record.

. "Electronic" means relating to technology having electrical, digital, magnetic, wireless, optical, electromagnetic, or similar capabilities.

. "Electronic mail" means an electronic transmission directed to a unique electronic mail address, which electronic mail will be deemed to include any files attached thereto and any information hyperlinked to a web site if the electronic mail includes the contact information of an officer or agent of the corporation who is available to assist with accessing such files and information.

. "Electronic mail address" means a destination, commonly expressed as a string of characters, consisting of a unique user name or mailbox, commonly referred to as the "local part" of the address, and a reference to an internet domain, commonly referred to as the "domain part" of the address, whether or not displayed, to which electronic mail can be sent or delivered.

. "Electronic record" means information that is stored in an electronic or other nontangible medium and is retrievable in paper form through an automated process used in conventional commercial practice, unless otherwise authorized in accordance with RCW 23B.01.410(10).

. "Electronic transmission" or "electronically transmitted" means internet transmission, telephonic transmission, electronic mail transmission, transmission of a telegram, cablegram, or datagram, the use of, or participation in, one or more electronic networks or databases including one or more distributed electronic networks or databases, or any other form or process of communication, not directly involving the physical transfer of paper or another tangible medium, which:

.. Is suitable for the retention, retrieval, and reproduction of information by the recipient; and

.. Is retrievable in paper form by the recipient through an automated process used in conventional commercial practice, unless otherwise authorized in accordance with RCW 23B.01.410(10).

. "Employee" includes an officer but not a director. A director may accept duties that make the director also an employee.

. "Entity" includes a corporation and foreign corporation, not-for-profit corporation, business trust, estate, trust, partnership, limited liability company, association, joint venture, two or more persons having a joint or common economic interest, the state, United States, and a foreign governmental subdivision, agency, or instrumentality, or any other legal or commercial entity.

. "Execute," "executes," or "executed" means, with present intent to authenticate or adopt a document:

.. To sign or adopt a tangible symbol to the document, and includes any manual, facsimile, or conformed signature;

.. To attach or logically associate with an electronic transmission an electronic sound, symbol, or process, and includes an electronic signature; or

.. With respect to a document to be filed with the secretary of state, in compliance with the standards for filing with the office of the secretary of state as prescribed by the secretary of state.

. "Foreign corporation" means a corporation for profit incorporated under a law other than the law of this state.

. "Foreign limited partnership" means a partnership formed under laws other than of this state and having as partners one or more general partners and one or more limited partners.

. "General social purpose" means the general social purpose for which a social purpose corporation is organized as set forth in the articles of incorporation of the corporation in accordance with RCW 23B.25.040(1)(c).

. "Governmental subdivision" includes authority, county, district, and municipality.

. "Governor" has the meaning given that term in RCW 23.95.105.

. "Includes" denotes a partial definition.

. "Individual" includes the estate of an incompetent or deceased individual.

. "Limited partnership" or "domestic limited partnership" means a partnership formed by two or more persons under the laws of this state and having one or more general partners and one or more limited partners.

. "Means" denotes an exhaustive definition.

. "Notice" has the meaning provided in RCW 23B.01.410.

. "Person" means an individual, corporation, business trust, estate, trust, partnership, limited liability company, association, joint venture, government, governmental subdivision, agency, or instrumentality, or any other legal or commercial entity.

. "Principal office" means the office, in or out of this state, so designated in the annual report where the principal executive offices of a domestic or foreign corporation are located.

. "Proceeding" includes civil suit and criminal, administrative, and investigatory action.

. "Public company" means a corporation that has a class of shares registered with the federal securities and exchange commission pursuant to section 12 or 15 of the securities exchange act of 1934, or section 8 of the investment company act of 1940, or any successor statute.

. "Qualified director" means (a) with respect to a director's conflicting interest transaction as defined in RCW 23B.08.700, any director who does not have either (i) a conflicting interest respecting the transaction, or (ii) a familial, financial, professional, or employment relationship with a second director who does have a conflicting interest respecting the transaction, which relationship would, in the circumstances, reasonably be expected to exert an influence on the first director's judgment when voting on the transaction; (b) with respect to RCW 23B.08.735, a qualified director under (a) of this subsection if the business opportunity were a director's conflicting interest transaction; and (c) with respect to *RCW 23B.02.020(5)(k), a director who is not a director (i) to whom the limitation or elimination of the duty of an officer to offer potential business opportunities to the corporation would apply, or (ii) who has a familial, financial, professional, or employment relationship with another officer to whom the limitation or elimination would apply, which relationship would, in the circumstances, reasonably be expected to exert an influence on the director's judgment when voting on the limitation or elimination.

. "Record date" means the date established under chapter 23B.07 RCW on which a corporation determines the identity of its shareholders and their shareholdings for purposes of this title. The determinations shall be made as of the close of business on the record date unless another time for doing so is specified when the record date is fixed.

. "Registered office" means the address of the corporation's registered agent.

. "Secretary" means the corporate officer to whom the board of directors has delegated responsibility under RCW 23B.08.400(3) for custody of the minutes of the meetings of the board of directors and of the shareholders and for authenticating records of the corporation.

. "Shareholder" means the person in whose name shares are registered in the records of a corporation or the beneficial owner of shares to the extent of the rights granted by a nominee certificate on file with a corporation.

. "Shares" means the units into which the proprietary interests in a corporation are divided.

. "Social purpose" includes any general social purpose and any specific social purpose.

. "Social purpose corporation" means a corporation that has elected to be governed as a social purpose corporation under chapter 23B.25 RCW.

. "Specific social purpose" means the specific social purpose or purposes for which a social purpose corporation is organized as set forth in the articles of incorporation of the corporation in accordance with RCW 23B.25.040(2)(a).

. "State," when referring to a part of the United States, includes a state and commonwealth, and their agencies and governmental subdivisions, and a territory and insular possession, and their agencies and governmental subdivisions, of the United States.

. "Subscriber" means a person who subscribes for shares in a corporation, whether before or after incorporation.

. "Subsidiary" means an entity in which the corporation has, directly or indirectly, a controlling interest.

. "United States" includes a district, authority, bureau, commission, department, and any other agency of the United States.

. "Voting group" means all shares of one or more classes or series that under the articles of incorporation or this title are entitled to vote and be counted together collectively on a matter at a meeting of shareholders. All shares entitled by the articles of incorporation or this title to vote generally on the matter are for that purpose a single voting group.

. "Writing" or "written" means any information in the form of a document.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2039[2020 c 57 § 39]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5003-S.SL.pdf?cite=2019%20c%20141%20§%205[2019 c 141 § 5]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5011.SL.pdf?cite=2017%20c%2028%20§%2012[2017 c 28 § 12]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%202148[2015 c 176 § 2148]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5031.SL.pdf?cite=2015%20c%2020%20§%201[2015 c 20 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2239-S.SL.pdf?cite=2012%20c%20215%20§%2017[2012 c 215 § 17]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1068.SL.pdf?cite=2009%20c%20189%20§%201[2009 c 189 § 1]; prior:  2002 c 297 § 9; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2299.SL.pdf?cite=2002%20c%20296%20§%201[2002 c 296 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2321-S.SL.pdf?cite=2000%20c%20168%20§%201[2000 c 168 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6169-S.SL.pdf?cite=1996%20c%20155%20§%204[1996 c 155 § 4]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5334-S.SL.pdf?cite=1995%20c%2047%20§%201[1995 c 47 § 1]; prior:  1991 c 269 § 35; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=1991%20c%2072%20§%2028[1991 c 72 § 28]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%2014[1989 c 165 § 14]; ]

== 23B.01.410 - Notice.
. A notice under this title must be in writing, except that oral notice of any meeting of the board of directors may be given if expressly authorized by the articles of incorporation or bylaws. A notice includes material that this title requires to accompany the notice. Unless otherwise agreed between the sender and the recipient, words in a notice or other communication under this title must be in English.

. A notice or other communication may be given by any method of delivery, except that electronic transmissions must be in accordance with this section. If the methods of delivery are impracticable, a notice or other communication may be given by means of a broad nonexclusionary distribution to the public, which may include a newspaper of general circulation in the area where published; radio, television, or other form of public broadcast communication; or other methods of distribution that the corporation has previously identified to its shareholders.

. A notice or other communication to a domestic or foreign corporation registered to do business in this state may be delivered to the corporation's registered agent or to the secretary at its principal office shown in its most recent annual report or, in the case of a foreign corporation that has not yet delivered an annual report, in its foreign registration statement.

. A notice or other communications may be delivered by electronic transmission if consented to by the recipient or if authorized by subsection (10) of this section; except that if the articles of incorporation or bylaws authorize or require delivery of notices of meetings of directors by electronic transmission, then no consent to delivery of such notices by electronic transmission is required.

. Any consent under subsection (4) of this section may be revoked by the person who consented by written notice to the person to whom the consent was delivered. Any such consent is deemed revoked if:

.. The corporation is unable to deliver two consecutive electronic transmissions given by the corporation in accordance with such consent; and

.. Such inability becomes known to the secretary or to the transfer agent, or other person responsible for the giving of notice or other communications. The inadvertent failure to treat such inability as a revocation will not invalidate any meeting or other corporate action.

. Unless otherwise agreed between the sender and the recipient, an electronic transmission is received when:

.. If by electronic mail, it is directed to the recipient's electronic mail address including, in the case of a shareholder, to the shareholder's electronic mail address as it appears in the corporation's records;

.. If by posting on an electronic network, upon the later of such posting and the delivery of separate notice to the recipient of such specific posting together with comprehensible instructions regarding how to obtain access to the posting on the electronic network; and

.. If by any other electronic transmission, it enters an information processing system that the recipient has designated or uses for the purposes of receiving electronic transmissions or information of the type sent, and from which the recipient is able to retrieve the electronic transmission and it is in a form capable of being processed by that system.

. Receipt of an electronic acknowledgment from an information processing system described in subsection (6)(c) of this section establishes that an electronic transmission was received but, by itself, does not establish that the content sent corresponds to the content received.

. An electronic transmission is received under this section even if no person is aware of its receipt.

. A notice or other communication, if in a comprehensible form or manner, is effective at the earliest of the following:

.. If in a physical form, the earliest of when it is actually received, or when it is left at:

... A shareholder's address as it appears in the corporation's records;

... A director's residence or usual place of business; or

... The corporation's principal office;

.. If mailed to a shareholder, upon deposit in the United States mail with first-class postage prepaid and correctly addressed to the shareholder's mailing address as it appears in the corporation's records;

.. If mailed to a recipient other than a shareholder, the earliest of when it is actually received, or:

... If sent by registered or certified mail, return receipt requested, the date shown on the return receipt signed by or on behalf of the addressee; or

... Five days after it is deposited in the United States mail with first-class postage prepaid and correctly addressed to the recipient;

.. If sent by air courier, when dispatched and correctly addressed to a shareholder's mailing address as it appears in the corporation's records;

.. If an electronic transmission, when it is received as provided in subsection (6) of this section; and

.. If oral, when communicated.

. A notice or other communication may be in the form of an electronic transmission that cannot be directly reproduced in paper form by the recipient through an automated process used in conventional commercial practice only if:

.. The electronic transmission is otherwise retrievable in perceivable form; and

.. The sender and the recipient have consented in writing to the use of such form of electronic transmission.

. Notwithstanding anything to the contrary in this section or any other section of this title, if this title requires that a notice to shareholders be accompanied by certain material, a public company may satisfy such a requirement, whether or not a shareholder has consented to receive electronically transmitted notice, by (a) posting the material on an electronic network (either separate from, or in combination or as part of, any other materials the public company has posted on the electronic network in compliance with applicable federal law) at or prior to the time that the notice is delivered to the public company's shareholders entitled to receive the notice, and (b) delivering to the public company's shareholders entitled to receive the notice a separate record of the posting (which record may accompany, or be contained in, the notice), together with comprehensible instructions regarding how to obtain access to the posting on the electronic network. In such a case, the material is deemed to have been delivered to the public company's shareholders at the time the notice to the shareholders is effective under this section. A public company that elects pursuant to this section to post on an electronic network any material required by this title to accompany a notice to shareholders is required, at its expense, to provide a copy of the material in a tangible medium (alone or in combination or as part of any other materials the public company has posted on the electronic network in compliance with federal law) to any shareholder entitled to such a notice who so requests.

. If this title prescribes requirements for notices or other communications in particular circumstances, those requirements govern. If articles of incorporation or bylaws prescribe requirements for notices or other communications, not inconsistent with this section or other provisions of this title, those requirements govern. The articles of incorporation or bylaws may authorize or require delivery of notices of meetings of directors by electronic transmission.

. In the event that any provisions of this title are deemed to modify, limit, or supersede the federal electronic signatures in global and national commerce act, 15 U.S.C. Sec. 7001 et seq., the provisions of this title will control to the maximum extent permitted by section 102(a)(2) of that federal act.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2040[2020 c 57 § 40]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%202108[2015 c 176 § 2108]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1068.SL.pdf?cite=2009%20c%20189%20§%202[2009 c 189 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2499.SL.pdf?cite=2008%20c%2059%20§%201[2008 c 59 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2301-S.SL.pdf?cite=2002%20c%20297%20§%2010[2002 c 297 § 10]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=1991%20c%2072%20§%2029[1991 c 72 § 29]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c178.pdf?cite=1990%20c%20178%20§%202[1990 c 178 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%2015[1989 c 165 § 15]; ]

== 23B.01.420 - Notice—Common address—Address defined—Shareholders consent.
. A corporation has delivered written notice or any other report or statement to all shareholders of record who share a common address if all of the following requirements are met:

.. The corporation delivers one copy of the notice, report, or statement to the common address;

.. The corporation addresses the notice, report, or statement to the shareholders who share that address either as a group or to each of the shareholders individually; and

.. Each of those shareholders consents to delivery of a single copy of such notice, report, or statement to the shareholders' common address, and the corporation notifies each shareholder of the duration of that shareholder's consent, and explains the manner by which the shareholder can revoke the consent.

. For purposes of this section, "address" means a street address, a post office box number, a facsimile telephone number, an address, location, or system for electronic transmissions, an email address, or another similar destination to which records are delivered.

. If a shareholder delivers written notice of revocation to consent to delivery of a single copy of any notice, report, or statement to a common address, or delivers written notice to the corporation that the shareholder wishes to receive an individual copy of any notice, report, or statement, the corporation shall begin sending individual copies to that shareholder within thirty days after delivery of the written notice.

. Prior to the delivery of notice by electronic transmission to a common address, each shareholder consenting to receive notice under this section must also have consented to the receipt of notices by electronic transmission as provided in RCW 23B.01.410.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2041[2020 c 57 § 41]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5123.SL.pdf?cite=2003%20c%2035%20§%201[2003 c 35 § 1]; ]

== 23B.01.520 - Domestic corporations—Filing, initial, and annual license fees.
For the privilege of doing business, every domestic corporation, except one for which existing law provides a different fee schedule, shall pay a fee for the filing of its articles of incorporation and its first year's license, and an annual license fee for each year following incorporation on or before the expiration of its corporate license, in an amount established by the secretary of state under RCW 23.95.260.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%202109[2015 c 176 § 2109]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%2018[1989 c 165 § 18]; ]

== 23B.01.540 - Foreign corporations—Filing and annual license fees.
A foreign corporation doing an intrastate business or seeking to do an intrastate business in the state of Washington shall pay for the privilege of so doing the same filing and annual license fees prescribed in RCW 23B.01.520 for domestic corporations.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%202110[2015 c 176 § 2110]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%2020[1989 c 165 § 20]; ]

== 23B.01.570 - Penalty for nonpayment of annual corporate license fees and failure to file a substantially complete annual report—Payment of delinquent fees—Rules.
In the event any domestic corporation fails to file a full and complete initial report under RCW 23.95.255, or in the event any corporation, foreign or domestic, does business in this state without having paid its annual corporate license fee and without having filed a substantially complete annual report under RCW 23.95.255 when either is due, there shall become due and owing the state of Washington a penalty as established by rule by the secretary under RCW 23.95.260.

A corporation organized under this title may at any time prior to its dissolution as provided in Article 6 of chapter 23.95 RCW, and a foreign corporation registered to do business in this state may at any time prior to the termination of its registration as provided in RCW 23.95.550, pay to the state of Washington its current annual license fee, provided it also pays an amount equal to all previously unpaid annual license fees plus the penalty established by rule by the secretary under RCW 23.95.260.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5040.SL.pdf?cite=2017%20c%2031%20§%204[2017 c 31 § 4]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%202111[2015 c 176 § 2111]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6230-S.SL.pdf?cite=1994%20c%20287%20§%206[1994 c 287 § 6]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=1991%20c%2072%20§%2030[1991 c 72 § 30]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%2023[1989 c 165 § 23]; ]

== 23B.01.590 - Public service companies entitled to deductions.
The annual fee required to be paid to the Washington utilities and transportation commission by any public service corporation shall be deducted from the annual license fee provided in this title and the excess only shall be collected.

It shall be the duty of the commission to furnish to the secretary of state on or before July 1st of each year a list of all public service corporations with the amount of annual license fees paid to the commission for the current year.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%2025[1989 c 165 § 25]; ]

