= 23B.13 - Dissenters' rights.
:toc:

== 23B.13.010 - Definitions.
As used in this chapter:

. "Corporation" means the issuer of the shares held by a dissenter before the corporate action, or the surviving or acquiring corporation by merger or share exchange of that issuer.

. "Dissenter" means a shareholder who is entitled to dissent from corporate action under RCW 23B.13.020 and who exercises that right when and in the manner required by RCW 23B.13.200 through 23B.13.280.

. "Fair value," with respect to a dissenter's shares, means the value of the shares immediately before the effective date of the corporate action to which the dissenter objects, excluding any appreciation or depreciation in anticipation of the corporate action unless exclusion would be inequitable.

. "Interest" means interest from the effective date of the corporate action until the date of payment, at the average rate currently paid by the corporation on its principal bank loans or, if none, at a rate that is fair and equitable under all the circumstances.

. "Record shareholder" means the person in whose name shares are registered in the records of a corporation or the beneficial owner of shares to the extent of the rights granted by a nominee certificate on file with a corporation.

. "Beneficial shareholder" means the person who is a beneficial owner of shares held in a voting trust or by a nominee as the record shareholder.

. "Shareholder" means the record shareholder or the beneficial shareholder.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%20140[1989 c 165 § 140]; ]

== 23B.13.020 - Right to dissent.
. A shareholder is entitled to dissent from, and obtain payment of the fair value of the shareholder's shares in the event of, any of the following corporate actions:

.. A plan of merger, which has become effective, to which the corporation is a party (i) if shareholder approval was required for the merger by RCW 23B.11.030, 23B.11.080, or the articles of incorporation, and the shareholder was entitled to vote on the merger, or (ii) if the corporation was a subsidiary and the plan of merger provided for the merger of the subsidiary with its parent under RCW 23B.11.040;

.. A plan of share exchange, which has become effective, to which the corporation is a party as the corporation whose shares have been acquired, if the shareholder was entitled to vote on the plan;

.. A sale, lease, exchange, or other disposition, which has become effective, of all, or substantially all, of the property and assets of the corporation other than in the usual and regular course of business, if the shareholder was entitled to vote on the sale, lease, exchange, or other disposition, including a disposition in dissolution, but not including a disposition pursuant to court order or a disposition for cash pursuant to a plan by which all or substantially all of the net proceeds of the disposition will be distributed to the shareholders within one year after the date of the disposition;

.. An amendment of the articles of incorporation, whether or not the shareholder was entitled to vote on the amendment, if the amendment effects a redemption or cancellation of all of the shareholder's shares in exchange for cash or other consideration other than shares of the corporation;

.. Any action described in RCW 23B.25.120;

.. Any corporate action approved pursuant to a shareholder vote to the extent the articles of incorporation, bylaws, or a resolution of the board of directors provides that voting or nonvoting shareholders are entitled to dissent and obtain payment for their shares; or

.. A plan of entity conversion in the case of a conversion of a domestic corporation to a foreign corporation, which has become effective, to which the domestic corporation is a party as the converting entity, if: (i) The shareholder was entitled to vote on the plan; and (ii) the shareholder does not receive shares in the surviving entity that have terms as favorable to the shareholder in all material respects and that represent at least the same percentage interest of the total voting rights of the outstanding shares of the surviving entity as the shares held by the shareholder before the conversion.

. A shareholder entitled to dissent and obtain payment for the shareholder's shares under this chapter may not challenge the corporate action creating the shareholder's entitlement unless the action fails to comply with the procedural requirements imposed by this title, RCW 25.10.831 through 25.10.886, the articles of incorporation, or the bylaws, or is fraudulent with respect to the shareholder or the corporation.

. The right of a dissenting shareholder to obtain payment of the fair value of the shareholder's shares shall terminate upon the occurrence of any one of the following events:

.. The proposed corporate action is abandoned or rescinded;

.. A court having jurisdiction permanently enjoins or sets aside the corporate action; or

.. The shareholder's demand for payment is withdrawn with the written consent of the corporation.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5011.SL.pdf?cite=2017%20c%2028%20§%2014[2017 c 28 § 14]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5999.SL.pdf?cite=2014%20c%2083%20§%2015[2014 c 83 § 15]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1148.SL.pdf?cite=2013%20c%2097%20§%201[2013 c 97 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1068.SL.pdf?cite=2009%20c%20189%20§%2041[2009 c 189 § 41]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201404[2009 c 188 § 1404]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5123.SL.pdf?cite=2003%20c%2035%20§%209[2003 c 35 § 9]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5148.SL.pdf?cite=1991%20c%20269%20§%2037[1991 c 269 § 37]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%20141[1989 c 165 § 141]; ]

== 23B.13.030 - Dissent by nominees and beneficial owners.
. A record shareholder may assert dissenters' rights as to fewer than all the shares registered in the shareholder's name only if the shareholder dissents with respect to all shares beneficially owned by any one person and delivers to the corporation a notice of the name and address of each person on whose behalf the shareholder asserts dissenters' rights. The rights of a partial dissenter under this subsection are determined as if the shares as to which the dissenter dissents and the dissenter's other shares were registered in the names of different shareholders.

. A beneficial shareholder may assert dissenters' rights as to shares held on the beneficial shareholder's behalf only if:

.. The beneficial shareholder delivers to the corporation the record shareholder's executed written consent to the dissent not later than the time the beneficial shareholder asserts dissenters' rights; and

.. The beneficial shareholder does so with respect to all shares of which such shareholder is the beneficial shareholder or over which such shareholder has power to direct the vote.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2068[2020 c 57 § 68]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2301-S.SL.pdf?cite=2002%20c%20297%20§%2035[2002 c 297 § 35]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%20142[1989 c 165 § 142]; ]

== 23B.13.200 - Notice of dissenters' rights.
. If proposed corporate action creating dissenters' rights under RCW 23B.13.020 is submitted for approval by a vote at a shareholders' meeting, the meeting notice must state that shareholders are or may be entitled to assert dissenters' rights under this chapter and be accompanied by a copy of this chapter.

. If corporate action creating dissenters' rights under RCW 23B.13.020 is submitted for approval without a vote of shareholders in accordance with RCW 23B.07.040, the shareholder consent described in RCW 23B.07.040(1)(b) and the notice described in RCW 23B.07.040(3)(a) must include a statement that shareholders are or may be entitled to assert dissenters' rights under this chapter and be accompanied by a copy of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1068.SL.pdf?cite=2009%20c%20189%20§%2042[2009 c 189 § 42]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2301-S.SL.pdf?cite=2002%20c%20297%20§%2036[2002 c 297 § 36]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%20143[1989 c 165 § 143]; ]

== 23B.13.210 - Notice of intent to demand payment.
. If proposed corporate action creating dissenters' rights under RCW 23B.13.020 is submitted to a vote at a shareholders' meeting, a shareholder who wishes to assert dissenters' rights must (a) deliver to the corporation before the vote is taken written notice of the shareholder's intent to demand payment for the shareholder's shares if the proposed corporate action is effected, and (b) not vote such shares in favor of the proposed corporate action.

. If proposed corporate action creating dissenters' rights under RCW 23B.13.020 is submitted for approval without a vote of shareholders in accordance with RCW 23B.07.040, a shareholder who wishes to assert dissenters' rights must not execute the consent or otherwise vote such shares in favor of the proposed corporate action.

. A shareholder who does not satisfy the requirements of subsection (1) or (2) of this section is not entitled to payment for the shareholder's shares under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2069[2020 c 57 § 69]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1068.SL.pdf?cite=2009%20c%20189%20§%2043[2009 c 189 § 43]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2301-S.SL.pdf?cite=2002%20c%20297%20§%2037[2002 c 297 § 37]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%20144[1989 c 165 § 144]; ]

== 23B.13.220 - Dissenters' rights—Notice.
. If proposed corporate action creating dissenters' rights under RCW 23B.13.020 is approved at a shareholders' meeting, the corporation shall within ten days after the effective date of the corporate action deliver to all shareholders who satisfied the requirements of RCW 23B.13.210(1) a notice in compliance with subsection (5) of this section.

. If proposed corporate action creating dissenters' rights under RCW 23B.13.020 is approved without a vote of shareholders in accordance with RCW 23B.07.040, the notice delivered pursuant to RCW 23B.07.040(3)(b) to shareholders who satisfied the requirements of RCW 23B.13.210(2) shall comply with subsection (5) of this section.

. In the case of proposed corporate action creating dissenters' rights under RCW 23B.13.020(1)(a)(ii), the corporation shall within ten days after the effective date of the corporate action deliver to all shareholders of the subsidiary other than the parent a notice in compliance with subsection (5) of this section.

. In the case of proposed corporate action creating dissenters' rights under RCW 23B.13.020(1)(d) that, pursuant to RCW 23B.10.020(4)(b), is not required to be approved by the shareholders of the corporation, the corporation shall within ten days after the effective date of the corporate action deliver to all shareholders entitled to dissent under RCW 23B.13.020(1)(d) a notice in compliance with subsection (5) of this section.

. Any notice under subsection (1), (2), (3), or (4) of this section must:

.. State where the payment demand must be sent and where and when certificates for certificated shares must be deposited;

.. Inform holders of uncertificated shares to what extent transfer of the shares will be restricted after the payment demand is received;

.. Supply a form for demanding payment that includes the date of the first announcement to news media or to shareholders of the terms of the proposed corporate action and requires that the person asserting dissenters' rights certify whether or not the person acquired beneficial ownership of the shares before that date;

.. Set a date by which the corporation must receive the payment demand, which date may not be fewer than thirty nor more than sixty days after the date the notice in subsection (1), (2), (3), or (4) of this section is delivered; and

.. Be accompanied by a copy of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1148.SL.pdf?cite=2013%20c%2097%20§%202[2013 c 97 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1068.SL.pdf?cite=2009%20c%20189%20§%2044[2009 c 189 § 44]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2301-S.SL.pdf?cite=2002%20c%20297%20§%2038[2002 c 297 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%20145[1989 c 165 § 145]; ]

== 23B.13.230 - Duty to demand payment.
. A shareholder sent a notice described in RCW 23B.13.220 must demand payment, certify whether the shareholder acquired beneficial ownership of the shares before the date required to be set forth in the notice pursuant to RCW 23B.13.220(5)(c), and deposit the shareholder's certificates, all in accordance with the terms of the notice.

. The shareholder who demands payment and deposits the shareholder's share certificates under subsection (1) of this section retains all other rights of a shareholder until the proposed corporate action is effected.

. A shareholder who does not demand payment or deposit the shareholder's share certificates where required, each by the date set in the notice, is not entitled to payment for the shareholder's shares under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1148.SL.pdf?cite=2013%20c%2097%20§%203[2013 c 97 § 3]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2301-S.SL.pdf?cite=2002%20c%20297%20§%2039[2002 c 297 § 39]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%20146[1989 c 165 § 146]; ]

== 23B.13.240 - Share restrictions.
. The corporation may restrict the transfer of uncertificated shares from the date the demand for payment under RCW 23B.13.230 is received until the proposed corporate action is effected or the restriction is released under RCW 23B.13.260.

. The person for whom dissenters' rights are asserted as to uncertificated shares retains all other rights of a shareholder until the effective date of the proposed corporate action.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1068.SL.pdf?cite=2009%20c%20189%20§%2045[2009 c 189 § 45]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%20147[1989 c 165 § 147]; ]

== 23B.13.250 - Payment.
. Except as provided in RCW 23B.13.270, within thirty days of the later of the effective date of the proposed corporate action, or the date the payment demand is received, the corporation shall pay each dissenter who complied with RCW 23B.13.230 the amount the corporation estimates to be the fair value of the shareholder's shares, plus accrued interest.

. The payment must be accompanied by:

.. The corporation's balance sheet as of the end of a fiscal year ending not more than sixteen months before the date of payment, an income statement for that year, a statement of changes in shareholders' equity for that year, and the latest available interim financial statements, if any;

.. An explanation of how the corporation estimated the fair value of the shares;

.. An explanation of how the interest was calculated;

.. A statement of the dissenter's right to demand payment under RCW 23B.13.280; and

.. A copy of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%20148[1989 c 165 § 148]; ]

== 23B.13.260 - Failure to take corporate action.
. If the corporation does not effect the proposed corporate action within sixty days after the date set for demanding payment and depositing share certificates, the corporation shall return the deposited certificates and release any transfer restrictions imposed on uncertificated shares.

. If after returning deposited certificates and releasing transfer restrictions, the corporation wishes to effect the proposed corporate action, it must deliver a new dissenters' notice under RCW 23B.13.220 and repeat the payment demand procedure.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2070[2020 c 57 § 70]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1068.SL.pdf?cite=2009%20c%20189%20§%2046[2009 c 189 § 46]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%20149[1989 c 165 § 149]; ]

== 23B.13.270 - After-acquired shares.
. A corporation may elect to withhold payment required by RCW 23B.13.250 from a dissenter unless the dissenter was the beneficial owner of the shares before the date set forth in the dissenters' notice as the date of the first announcement to news media or to shareholders of the terms of the proposed corporate action.

. To the extent the corporation elects to withhold payment under subsection (1) of this section, after the effective date of the proposed corporate action, it shall estimate the fair value of the shares, plus accrued interest, and shall pay this amount to each dissenter who agrees to accept it in full satisfaction of the dissenter's demand. The corporation shall deliver with its offer an explanation of how it estimated the fair value of the shares, an explanation of how the interest was calculated, and a statement of the dissenter's right to demand payment under RCW 23B.13.280.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2071[2020 c 57 § 71]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1068.SL.pdf?cite=2009%20c%20189%20§%2047[2009 c 189 § 47]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%20150[1989 c 165 § 150]; ]

== 23B.13.280 - Procedure if shareholder dissatisfied with payment or offer.
. A dissenter may deliver a notice to the corporation informing the corporation of the dissenter's own estimate of the fair value of the dissenter's shares and amount of interest due, and demand payment of the dissenter's estimate, less any payment under RCW 23B.13.250, or reject the corporation's offer under RCW 23B.13.270 and demand payment of the dissenter's estimate of the fair value of the dissenter's shares and interest due, if:

.. The dissenter believes that the amount paid under RCW 23B.13.250 or offered under RCW 23B.13.270 is less than the fair value of the dissenter's shares or that the interest due is incorrectly calculated;

.. The corporation fails to make payment under RCW 23B.13.250 within sixty days after the date set for demanding payment; or

.. The corporation does not effect the proposed corporate action and does not return the deposited certificates or release the transfer restrictions imposed on uncertificated shares within sixty days after the date set for demanding payment.

. A dissenter waives the right to demand payment under this section unless the dissenter notifies the corporation of the dissenter's demand under subsection (1) of this section within thirty days after the corporation made or offered payment for the dissenter's shares.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1068.SL.pdf?cite=2009%20c%20189%20§%2048[2009 c 189 § 48]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2301-S.SL.pdf?cite=2002%20c%20297%20§%2040[2002 c 297 § 40]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%20151[1989 c 165 § 151]; ]

== 23B.13.300 - Court action.
. If a demand for payment under RCW 23B.13.280 remains unsettled, the corporation shall commence a proceeding within sixty days after receiving the payment demand and petition the court to determine the fair value of the shares and accrued interest. If the corporation does not commence the proceeding within the sixty-day period, it shall pay each dissenter whose demand remains unsettled the amount demanded.

. The corporation shall commence the proceeding in the superior court of the county where a corporation's principal office, or, if none in this state, its registered office, is located. If the corporation is a foreign corporation without a registered office in this state, it shall commence the proceeding in the county in this state where the registered office of the domestic corporation merged with or whose shares were acquired by the foreign corporation was located.

. The corporation shall make all dissenters, whether or not residents of this state, whose demands remain unsettled, parties to the proceeding as in an action against their shares and all parties must be served with a copy of the petition. Nonresidents may be served by registered or certified mail or by publication as provided by law.

. The corporation may join as a party to the proceeding any shareholder who claims to be a dissenter but who has not, in the opinion of the corporation, complied with the provisions of this chapter. If the court determines that such shareholder has not complied with the provisions of this chapter, the shareholder shall be dismissed as a party.

. The jurisdiction of the court in which the proceeding is commenced under subsection (2) of this section is plenary and exclusive. The court may appoint one or more persons as appraisers to receive evidence and recommend decision on the question of fair value. The appraisers have the powers described in the order appointing them, or in any amendment to it. The dissenters are entitled to the same discovery rights as parties in other civil proceedings.

. Each dissenter made a party to the proceeding is entitled to judgment (a) for the amount, if any, by which the court finds the fair value of the dissenter's shares, plus interest, exceeds the amount paid by the corporation, or (b) for the fair value, plus accrued interest, of the dissenter's after-acquired shares for which the corporation elected to withhold payment under RCW 23B.13.270.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%20152[1989 c 165 § 152]; ]

== 23B.13.310 - Court costs and counsel fees.
. The court in a proceeding commenced under RCW 23B.13.300 shall determine all costs of the proceeding, including the reasonable compensation and expenses of appraisers appointed by the court. The court shall assess the costs against the corporation, except that the court may assess the costs against all or some of the dissenters, in amounts the court finds equitable, to the extent the court finds the dissenters acted arbitrarily, vexatiously, or not in good faith in demanding payment under RCW 23B.13.280.

. The court may also assess the fees and expenses of counsel and experts for the respective parties, in amounts the court finds equitable:

.. Against the corporation and in favor of any or all dissenters if the court finds the corporation did not substantially comply with the requirements of RCW 23B.13.200 through 23B.13.280; or

.. Against either the corporation or a dissenter, in favor of any other party, if the court finds that the party against whom the fees and expenses are assessed acted arbitrarily, vexatiously, or not in good faith with respect to the rights provided by chapter 23B.13 RCW.

. If the court finds that the services of counsel for any dissenter were of substantial benefit to other dissenters similarly situated, and that the fees for those services should not be assessed against the corporation, the court may award to these counsel reasonable fees to be paid out of the amounts awarded the dissenters who were benefited.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c165.pdf?cite=1989%20c%20165%20§%20153[1989 c 165 § 153]; ]

