= 7.04A - Uniform arbitration act.
:toc:

== 7.04A.010 - Definitions.
The definitions set forth in this section apply throughout this chapter.

. "Arbitration organization" means a neutral association, agency, board, commission, or other entity that initiates, sponsors, or administers arbitration proceedings or is involved in the appointment of arbitrators.

. "Arbitrator" means an individual appointed to render an award in a controversy between persons who are parties to an agreement to arbitrate.

. "Authenticate" means:

.. To sign; or

.. To execute or adopt a record by attaching to or logically associating with the record, an electronic sound, symbol, or process with the intent to sign the record.

. "Court" means a court of competent jurisdiction in this state.

. "Knowledge" means actual knowledge.

. "Person" means an individual, corporation, business trust, estate, trust, partnership, limited liability company, association, joint venture, or government; governmental subdivision, agency, or instrumentality; public corporation; or any other legal or commercial entity.

. "Record" means information that is inscribed on a tangible medium or that is stored in an electronic or other medium and is retrievable in perceivable form.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1054-S.SL.pdf?cite=2005%20c%20433%20§%201[2005 c 433 § 1]; ]

== 7.04A.020 - Notice.
Unless the parties to an agreement to arbitrate otherwise agree or except as otherwise provided in this chapter, a person gives notice to another person by taking action that is reasonably necessary to inform the other person in ordinary course, whether or not the other person acquires knowledge of the notice. A person has notice if the person has knowledge of the notice or has received notice. A person receives notice when it comes to the person's attention or the notice is delivered at the person's place of residence or place of business, or at another location held out by the person as a place of delivery of such communications.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1054-S.SL.pdf?cite=2005%20c%20433%20§%202[2005 c 433 § 2]; ]

== 7.04A.030 - When chapter applies.
. Before July 1, 2006, this chapter governs agreements to arbitrate entered into:

.. On or after January 1, 2006; and

.. Before January 1, 2006, if all parties to the agreement to arbitrate or to arbitration proceedings agree in a record to be governed by this chapter.

. On or after July 1, 2006, this chapter governs agreements to arbitrate even if the arbitration agreement was entered into before January 1, 2006.

. This chapter does not apply to any arbitration governed by chapter 7.06 RCW.

. This chapter does not apply to any arbitration agreement between employers and employees or between employers and associations of employees.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1054-S.SL.pdf?cite=2005%20c%20433%20§%203[2005 c 433 § 3]; ]

== 7.04A.040 - Effect of agreement to arbitrate—Nonwaivable provisions.
. Except as otherwise provided in subsections (2) and (3) of this section, the parties to an agreement to arbitrate or to an arbitration proceeding may waive or vary the requirements of this chapter to the extent permitted by law.

. Before a controversy arises that is subject to an agreement to arbitrate, the parties to the agreement may not:

.. Waive or vary the requirements of RCW 7.04A.050(1), 7.04A.060(1), 7.04A.080, 7.04A.170 (1) or (2), 7.04A.260, or 7.04A.280;

.. Unreasonably restrict the right under RCW 7.04A.090 to notice of the initiation of an arbitration proceeding;

.. Unreasonably restrict the right under RCW 7.04A.120 to disclosure of any facts by a neutral arbitrator; or

.. Waive the right under RCW 7.04A.160 of a party to an agreement to arbitrate to be represented by a lawyer at any proceeding or hearing under this chapter.

. The parties to an agreement to arbitrate may not waive or vary the requirements of this section or RCW 7.04A.030 (1)(a) or (2), 7.04A.070, 7.04A.140, 7.04A.180, 7.04A.200 (3) or (4), 7.04A.220, 7.04A.230, 7.04A.240, 7.04A.250 (1) or (2), 7.04A.901, 7.04A.903, section 50, chapter 433, Laws of 2005, or section 51, chapter 433, Laws of 2005.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1054-S.SL.pdf?cite=2005%20c%20433%20§%204[2005 c 433 § 4]; ]

== 7.04A.050 - Application to court.
. Except as otherwise provided in RCW 7.04A.280, an application for judicial relief under this chapter must be made by motion to the court and heard in the manner and upon the notice provided by law or rule of court for making and hearing motions.

. Notice of an initial motion to the court under this chapter must be served in the manner provided by law for the service of a summons in a civil action unless a civil action is already pending involving the agreement to arbitrate.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1054-S.SL.pdf?cite=2005%20c%20433%20§%205[2005 c 433 § 5]; ]

== 7.04A.060 - Validity of agreement to arbitrate.
. An agreement contained in a record to submit to arbitration any existing or subsequent controversy arising between the parties to the agreement is valid, enforceable, and irrevocable except upon a ground that exists at law or in equity for the revocation of contract.

. The court shall decide whether an agreement to arbitrate exists or a controversy is subject to an agreement to arbitrate.

. An arbitrator shall decide whether a condition precedent to arbitrability has been fulfilled and whether a contract containing a valid agreement to arbitrate is enforceable.

. If a party to a judicial proceeding challenges the existence of, or claims that a controversy is not subject to, an agreement to arbitrate, the arbitration proceeding may continue pending final resolution of the issue by the court, unless the court otherwise orders.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1054-S.SL.pdf?cite=2005%20c%20433%20§%206[2005 c 433 § 6]; ]

== 7.04A.070 - Motion to compel or stay arbitration.
. On motion of a person showing an agreement to arbitrate and alleging another person's refusal to arbitrate pursuant to the agreement, the court shall order the parties to arbitrate if the refusing party does not appear or does not oppose the motion. If the refusing party opposes the motion, the court shall proceed summarily to decide the issue. Unless the court finds that there is no enforceable agreement to arbitrate, it shall order the parties to arbitrate. If the court finds that there is no enforceable agreement, it may not order the parties to arbitrate.

. On motion of a person alleging that an arbitration proceeding has been initiated or threatened but that there is no agreement to arbitrate, the court shall proceed summarily to decide the issue. If the court finds that there is an enforceable agreement to arbitrate, it shall order the parties to arbitrate. If the court finds that there is no enforceable agreement, it may not order the parties to arbitrate.

. The court may not refuse to order arbitration because the claim subject to arbitration lacks merit or grounds for the claim have not been established.

. If a proceeding involving a claim referable to arbitration under an alleged agreement to arbitrate is pending in court, a motion under this section must be filed in that court. Otherwise a motion under this section may be filed in any court as required by RCW 7.04A.270.

. If a party files a motion with the court to order arbitration under this section, the court shall on just terms stay any judicial proceeding that involves a claim alleged to be subject to the arbitration until the court renders a final decision under this section.

. If the court orders arbitration, the court shall on just terms stay any judicial proceeding that involves a claim subject to the arbitration. If a claim subject to the arbitration is severable, the court may sever it and limit the stay to that claim.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1054-S.SL.pdf?cite=2005%20c%20433%20§%207[2005 c 433 § 7]; ]

== 7.04A.080 - Provisional remedies.
. Before an arbitrator is appointed and is authorized and able to act, the court, upon motion of a party to an arbitration proceeding and for good cause shown, may enter an order for provisional remedies to protect the effectiveness of the arbitration proceeding to the same extent and under the same conditions as if the controversy were the subject of a civil action.

. After an arbitrator is appointed and is authorized and able to act, the arbitrator may issue such orders for provisional remedies, including interim awards, as the arbitrator finds necessary to protect the effectiveness of the arbitration proceeding and to promote the fair and expeditious resolution of the controversy, to the same extent and under the same conditions as if the controversy were the subject of a civil action. After an arbitrator is appointed and is authorized and able to act, a party to an arbitration proceeding may move the court for a provisional remedy only if the matter is urgent and the arbitrator is not able to act timely or if the arbitrator cannot provide an adequate remedy.

. A motion to a court for a provisional remedy under subsection (1) or (2) of this section does not waive any right of arbitration.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1054-S.SL.pdf?cite=2005%20c%20433%20§%208[2005 c 433 § 8]; ]

== 7.04A.090 - Initiation of arbitration.
. A person initiates an arbitration proceeding by giving notice in a record to the other parties to the agreement to arbitrate in the agreed manner between the parties or, in the absence of agreement, by mail certified or registered, return receipt requested and obtained, or by service as authorized for the initiation of a civil action. The notice must describe the nature of the controversy and the remedy sought.

. Unless a person interposes an objection as to lack or insufficiency of notice under RCW 7.04A.150(3) not later than the commencement of the arbitration hearing, the person's appearance at the hearing waives any objection to lack of or insufficiency of notice.

. A claim sought to be arbitrated is subject to the same limitations of time for the commencement of actions as if the claim had been asserted in a court.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1065.SL.pdf?cite=2013%20c%2092%20§%201[2013 c 92 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1054-S.SL.pdf?cite=2005%20c%20433%20§%209[2005 c 433 § 9]; ]

== 7.04A.100 - Consolidation of separate arbitration proceedings.
. Except as otherwise provided in subsection (3) of this section, upon motion of a party to an agreement to arbitrate or to an arbitration proceeding, the court may order consolidation of separate arbitration proceedings as to all or some of the claims if:

.. There are separate agreements to arbitrate or separate arbitration proceedings between the same persons or one of them is a party to a separate agreement to arbitrate or a separate arbitration proceeding with a third person;

.. The claims subject to the agreements to arbitrate arise in substantial part from the same transaction or series of related transactions;

.. The existence of a common issue of law or fact creates the possibility of conflicting decisions in the separate arbitration proceedings; and

.. Prejudice resulting from a failure to consolidate is not outweighed by the risk of undue delay or prejudice to the rights of or hardship to parties opposing consolidation.

. The court may order consolidation of separate arbitration proceedings as to certain claims and allow other claims to be resolved in separate arbitration proceedings.

. The court may not order consolidation of the claims of a party to an agreement to arbitrate that prohibits consolidation.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1054-S.SL.pdf?cite=2005%20c%20433%20§%2010[2005 c 433 § 10]; ]

== 7.04A.110 - Appointment of arbitrator—Service as a neutral arbitrator.
. If the parties to an agreement to arbitrate agree on a method for appointing an arbitrator, that method must be followed, unless the method fails. If the parties have not agreed on a method, the agreed method fails, or an arbitrator appointed fails or is unable to act and a successor has not been appointed, the court, on motion of a party to the arbitration proceeding, shall appoint the arbitrator. The arbitrator so appointed has all the powers of an arbitrator designated in the agreement to arbitrate or appointed under the agreed method.

. An arbitrator who has a known, direct, and material interest in the outcome of the arbitration proceeding or a known, existing, and substantial relationship with a party may not serve as a neutral arbitrator.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1054-S.SL.pdf?cite=2005%20c%20433%20§%2011[2005 c 433 § 11]; ]

== 7.04A.120 - Disclosure by arbitrator.
. Before accepting appointment, an individual who is requested to serve as an arbitrator, after making a reasonable inquiry, shall disclose to all parties to the agreement to arbitrate and arbitration proceeding and to any other arbitrators any known facts that a reasonable person would consider likely to affect the impartiality of the arbitrator in the arbitration proceeding, including:

.. A financial or personal interest in the outcome of the arbitration proceeding; and

.. An existing or past relationship with any of the parties to the agreement to arbitrate or the arbitration proceeding, their counsel or representatives, witnesses, or the other arbitrators.

. An arbitrator has a continuing obligation to disclose to all parties to the agreement to arbitrate and arbitration proceedings and to any other arbitrators any facts that the arbitrator learns after accepting appointment that a reasonable person would consider likely to affect the impartiality of the arbitrator.

. If an arbitrator discloses a fact required by subsection (1) or (2) of this section to be disclosed and a party timely objects to the appointment or continued service of the arbitrator based upon the disclosure, the objection may be a ground to vacate the award under RCW 7.04A.230(1)(b).

. If the arbitrator did not disclose a fact as required by subsection (1) or (2) of this section, upon timely objection of a party, an award may be vacated under RCW 7.04A.230(1)(b).

. An arbitrator appointed as a neutral who does not disclose a known, direct, and material interest in the outcome of the arbitration proceeding or a known, existing, and substantial relationship with a party is presumed to act with evident partiality under RCW 7.04A.230(1)(b).

. If the parties to an arbitration proceeding agree to the procedures of an arbitration organization or any other procedures for challenges to arbitrators before an award is made, substantial compliance with those procedures is a condition precedent to a motion to vacate an award on that ground under RCW 7.04A.230(1)(b).

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1054-S.SL.pdf?cite=2005%20c%20433%20§%2012[2005 c 433 § 12]; ]

== 7.04A.130 - Action by majority.
If there is more than one arbitrator, the powers of the arbitrators must be exercised by a majority of them.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1054-S.SL.pdf?cite=2005%20c%20433%20§%2013[2005 c 433 § 13]; ]

== 7.04A.140 - Immunity of arbitrator—Competency to testify—Attorneys' fees and costs.
. An arbitrator or an arbitration organization acting in that capacity is immune from civil liability to the same extent as a judge of a court of this state acting in a judicial capacity.

. The immunity afforded by this section supplements any other immunity.

. If an arbitrator does not make a disclosure required by RCW 7.04A.120, the nondisclosure does not cause a loss of immunity under this section.

. In any judicial, administrative, or similar proceeding, an arbitrator or representative of an arbitration organization is not competent to testify or required to produce records as to any statement, conduct, decision, or ruling occurring during the arbitration proceeding to the same extent as a judge of a court of this state acting in a judicial capacity. This subsection does not apply:

.. To the extent necessary to determine the claim of an arbitrator or an arbitration organization or a representative of the arbitration organization against a party to the arbitration proceeding; or

.. If a party to the arbitration proceeding files a motion to vacate an award under RCW 7.04A.230(1) (a) or (b) and establishes prima facie that a ground for vacating the award exists.

. If a person commences a civil action against an arbitrator, an arbitration organization, or a representative of an arbitration organization arising from the services of the arbitrator, organization, or representative or if a person seeks to compel an arbitrator or a representative of an arbitration organization to testify in violation of subsection (4) of this section, and the court decides that the arbitrator, arbitration organization, or representative of an arbitration organization is immune from civil liability or that the arbitrator or representative of the organization is incompetent to testify, the court shall award to the arbitrator, organization, or representative reasonable attorneys' fees and other reasonable expenses of litigation.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1054-S.SL.pdf?cite=2005%20c%20433%20§%2014[2005 c 433 § 14]; ]

== 7.04A.150 - Arbitration process.
. The arbitrator may conduct the arbitration in such manner as the arbitrator considers appropriate so as to aid in the fair and expeditious disposition of the proceeding. The authority conferred upon the arbitrator includes the power to hold conferences with the parties to the arbitration proceeding before the hearing and to determine the admissibility, relevance, materiality, and weight of any evidence.

. The arbitrator may decide a request for summary disposition of a claim or particular issue by agreement of all interested parties or upon request of one party to the arbitration proceeding if that party gives notice to all other parties to the arbitration proceeding and the other parties have a reasonable opportunity to respond.

. The arbitrator shall set a time and place for a hearing and give notice of the hearing not less than five days before the hearing. Unless a party to the arbitration proceeding interposes an objection to lack of or insufficiency of notice not later than the commencement of the hearing, the party's appearance at the hearing waives the objection. Upon request of a party to the arbitration proceeding and for good cause shown, or upon the arbitrator's own initiative, the arbitrator may adjourn the hearing from time to time as necessary but may not postpone the hearing to a time later than that fixed by the agreement to arbitrate for making the award unless the parties to the arbitration proceeding consent to a later date. The arbitrator may hear and decide the controversy upon the evidence produced although a party who was duly notified of the arbitration proceeding did not appear. The court, on request, may direct the arbitrator to promptly conduct the hearing and render a timely decision.

. If an arbitrator orders a hearing under subsection (3) of this section, the parties to the arbitration proceeding are entitled to be heard, to present evidence material to the controversy, and to cross-examine witnesses appearing at the hearing.

. If there is more than one arbitrator, all of them shall conduct the hearing under subsection (3) of this section; however, a majority shall decide any issue and make a final award.

. If an arbitrator ceases, or is unable, to act during the arbitration proceeding, a replacement arbitrator must be appointed in accordance with RCW 7.04A.110 to continue the hearing and to decide the controversy.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1054-S.SL.pdf?cite=2005%20c%20433%20§%2015[2005 c 433 § 15]; ]

== 7.04A.160 - Representation by lawyer.
A party to an arbitration proceeding may be represented by a lawyer.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1054-S.SL.pdf?cite=2005%20c%20433%20§%2016[2005 c 433 § 16]; ]

== 7.04A.170 - Witnesses—Subpoenas—Depositions—Discovery.
. An arbitrator may issue a subpoena for the attendance of a witness and for the production of records and other evidence at any hearing and may administer oaths. A subpoena must be served in the manner for service of subpoenas in a civil action and, upon motion to the court by a party to the arbitration proceeding or the arbitrator, enforced in the manner for enforcement of subpoenas in a civil action.

. On request of a party to or a witness in an arbitration proceeding, an arbitrator may permit a deposition of any witness, including a witness who cannot be subpoenaed for or is unable to attend a hearing, to be taken under conditions determined by the arbitrator for use as evidence in order to make the proceeding fair, expeditious, and cost-effective.

. An arbitrator may permit such discovery as the arbitrator decides is appropriate in the circumstances, taking into account the needs of the parties to the arbitration proceeding and other affected persons and the desirability of making the proceeding fair, expeditious, and cost-effective.

. If an arbitrator permits discovery under subsection (3) of this section, the arbitrator may order a party to the arbitration proceeding to comply with the arbitrator's discovery-related orders, including the issuance of a subpoena for the attendance of a witness and for the production of records and other evidence at a discovery proceeding, and may take action against a party to the arbitration proceeding who does not comply to the extent permitted by law as if the controversy were the subject of a civil action in this state.

. An arbitrator may issue a protective order to prevent the disclosure of privileged information, confidential information, trade secrets, and other information protected from disclosure as if the controversy were the subject of a civil action in this state.

. All laws compelling a person under subpoena to testify and all fees for attending a judicial proceeding, a deposition, or a discovery proceeding as a witness apply to an arbitration proceeding as if the controversy were the subject of a civil action in this state.

. The court may enforce a subpoena or discovery-related order for the attendance of a witness within this state and for the production of records and other evidence issued by an arbitrator in connection with an arbitration proceeding in another state upon conditions determined by the court in order to make the arbitration proceeding fair, expeditious, and cost-effective. A subpoena or discovery-related order issued by an arbitrator must be served in the manner provided by law for service of subpoenas in a civil action in this state and, upon motion to the court by a party to the arbitration proceeding or the arbitrator, enforced in the manner provided by law for enforcement of subpoenas in a civil action in this state.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1054-S.SL.pdf?cite=2005%20c%20433%20§%2017[2005 c 433 § 17]; ]

== 7.04A.180 - Court enforcement of preaward ruling by arbitrator.
If an arbitrator makes a preaward ruling in favor of a party to the arbitration proceeding, the party may request the arbitrator to incorporate the ruling into an award under RCW 7.04A.190. The successful party may file a motion to the court for an expedited order to confirm the award under RCW 7.04A.220, in which case the court shall proceed summarily to decide the motion. The court shall issue an order to confirm the award unless the court vacates, modifies, or corrects the award of the arbitrator under RCW 7.04A.230 and 7.04A.240.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1054-S.SL.pdf?cite=2005%20c%20433%20§%2018[2005 c 433 § 18]; ]

== 7.04A.190 - Award.
. An arbitrator shall make a record of an award. The record must be authenticated by any arbitrator who concurs with the award. The arbitrator or the arbitration organization shall give notice of the award, including a copy of the award, to each party to the arbitration proceeding.

. An award must be made within the time specified by the agreement to arbitrate or, if not specified therein, within the time ordered by the court. The court may extend or the parties to the arbitration proceeding may agree in a record to extend the time. The court or the parties may do so within or after the time specified or ordered. A party waives any objection that an award was not timely made unless the party gives notice of the objection to the arbitrator before receiving notice of the award.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1054-S.SL.pdf?cite=2005%20c%20433%20§%2019[2005 c 433 § 19]; ]

== 7.04A.200 - Change of award by arbitrator.
. On motion to an arbitrator by a party to the arbitration proceeding, the arbitrator may modify or correct an award:

.. Upon the grounds stated in RCW 7.04A.240(1) (a) or (c);

.. Because the arbitrator has not made a final and definite award upon a claim submitted by the parties to the arbitration proceeding; or

.. To clarify the award.

. A motion under subsection (1) of this section must be made and served on all parties within twenty days after the movant receives notice of the award.

. A party to the arbitration proceeding must serve any objections to the motion within ten days after receipt of the notice.

. If a motion to the court is pending under RCW 7.04A.220, 7.04A.230, or 7.04A.240, the court may submit the claim to the arbitrator to consider whether to modify or correct the award:

.. Upon the grounds stated in RCW 7.04A.240(1) (a) or (c);

.. Because the arbitrator has not made a final and definite award upon a claim submitted by the parties to the arbitration proceeding; or

.. To clarify the award.

. An award modified or corrected under this section is subject to RCW 7.04A.220, 7.04A.230, and 7.04A.240.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1054-S.SL.pdf?cite=2005%20c%20433%20§%2020[2005 c 433 § 20]; ]

== 7.04A.210 - Remedies—Fees and expenses of arbitration proceeding.
. An arbitrator may award punitive damages or other exemplary relief if such an award is authorized under the applicable law in a civil action involving the same claim and the evidence produced at the hearing justifies the award under the legal standards otherwise applicable to the claim.

. An arbitrator may award attorneys' fees and other reasonable expenses of arbitration if such an award is authorized by law in a civil action involving the same claim or by the agreement of the parties to the arbitration proceeding.

. As to all remedies other than those authorized by subsections (1) and (2) of this section, an arbitrator may order such remedies as the arbitrator considers just and appropriate under the circumstances of the arbitration proceeding. The fact that such a remedy could not or would not be granted by the court is not a ground for refusing to confirm an award under RCW 7.04A.220 or for vacating an award under RCW 7.04A.230.

. An arbitrator's expenses and fees, together with other expenses, must be paid as provided in the award.

. If an arbitrator awards punitive damages or other exemplary relief under subsection (1) of this section, the arbitrator shall specify in the award the basis in fact justifying and the basis in law authorizing the award and state separately the amount of the punitive damages or other exemplary relief.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1054-S.SL.pdf?cite=2005%20c%20433%20§%2021[2005 c 433 § 21]; ]

== 7.04A.220 - Confirmation of award.
After a party to the arbitration proceeding receives notice of an award, the party may file a motion with the court for an order confirming the award, at which time the court shall issue such an order unless the award is modified or corrected under RCW 7.04A.200 or 7.04A.240 or is vacated under RCW 7.04A.230.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1054-S.SL.pdf?cite=2005%20c%20433%20§%2022[2005 c 433 § 22]; ]

== 7.04A.230 - Vacating award.
. Upon motion of a party to the arbitration proceeding, the court shall vacate an award if:

.. The award was procured by corruption, fraud, or other undue means;

.. There was:

... Evident partiality by an arbitrator appointed as a neutral;

... Corruption by an arbitrator; or

... Misconduct by an arbitrator prejudicing the rights of a party to the arbitration proceeding;

.. An arbitrator refused to postpone the hearing upon showing of sufficient cause for postponement, refused to consider evidence material to the controversy, or otherwise conducted the hearing contrary to RCW 7.04A.150, so as to prejudice substantially the rights of a party to the arbitration proceeding;

.. An arbitrator exceeded the arbitrator's powers;

.. There was no agreement to arbitrate, unless the person participated in the arbitration proceeding without raising the objection under RCW 7.04A.150(3) not later than the commencement of the arbitration hearing; or

.. The arbitration was conducted without proper notice of the initiation of an arbitration as required in RCW 7.04A.090 so as to prejudice substantially the rights of a party to the arbitration proceeding.

. A motion under this section must be filed within ninety days after the movant receives notice of the award in a record under RCW 7.04A.190 or within ninety days after the movant receives notice of an arbitrator's award in a record on a motion to modify or correct an award under RCW 7.04A.200, unless the motion is predicated upon the ground that the award was procured by corruption, fraud, or other undue means, in which case it must be filed within ninety days after such a ground is known or by the exercise of reasonable care should have been known by the movant.

. In vacating an award on a ground other than that set forth in subsection (1)(e) of this section, the court may order a rehearing before a new arbitrator. If the award is vacated on a ground stated in subsection (1)(c), (d), or (f) of this section, the court may order a rehearing before the arbitrator who made the award or the arbitrator's successor. The arbitrator must render the decision in the rehearing within the same time as that provided in RCW 7.04A.190(2) for an award.

. If a motion to vacate an award is denied and a motion to modify or correct the award is not pending, the court shall confirm the award.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1054-S.SL.pdf?cite=2005%20c%20433%20§%2023[2005 c 433 § 23]; ]

== 7.04A.240 - Modification or correction of award.
. Upon motion filed within ninety days after the movant receives notice of the award in a record under RCW 7.04A.190 or within ninety days after the movant receives notice of an arbitrator's award in a record on a motion to modify or correct an award under RCW 7.04A.200, the court shall modify or correct the award if:

.. There was an evident mathematical miscalculation or an evident mistake in the description of a person, thing, or property referred to in the award;

.. The arbitrator has made an award on a claim not submitted to the arbitrator and the award may be corrected without affecting the merits of the decision upon the claims submitted; or

.. The award is imperfect in a matter of form not affecting the merits of the decision on the claims submitted.

. If a motion filed under subsection (1) of this section is granted, the court shall modify or correct and confirm the award as modified or corrected. Otherwise, the court shall confirm the award.

. A motion to modify or correct an award under this section may be joined with a motion to vacate the award.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1054-S.SL.pdf?cite=2005%20c%20433%20§%2024[2005 c 433 § 24]; ]

== 7.04A.250 - Judgment on award—Attorneys' fees and litigation expenses.
. Upon granting an order confirming, vacating without directing a rehearing, modifying, or correcting an award, the court shall enter a judgment in conformity with the order. The judgment may be recorded, docketed, and enforced as any other judgment in a civil action.

. A court may allow reasonable costs of the motion and subsequent judicial proceedings.

. On application of a prevailing party to a contested judicial proceeding under RCW 7.04A.220, 7.04A.230, or 7.04A.240, the court may add to a judgment confirming, vacating without directing a rehearing, modifying, or correcting an award, attorneys' fees and other reasonable expenses of litigation incurred in a judicial proceeding after the award is made.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1054-S.SL.pdf?cite=2005%20c%20433%20§%2025[2005 c 433 § 25]; ]

== 7.04A.260 - Jurisdiction.
. A court of this state having jurisdiction over the dispute and the parties may enforce an agreement to arbitrate.

. An agreement to arbitrate providing for arbitration in this state confers exclusive jurisdiction on the court to enter judgment on an award under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1054-S.SL.pdf?cite=2005%20c%20433%20§%2026[2005 c 433 § 26]; ]

== 7.04A.270 - Venue.
A motion under RCW 7.04A.050 must be filed in the court of the county in which the agreement to arbitrate specifies the arbitration hearing is to be held or, if the hearing has been held, in the court of the county in which it was held. Otherwise, the motion must be filed in any county in which an adverse party resides or has a place of business or, if no adverse party has a residence or place of business in this state, in the court of any county in this state. All subsequent motions must be filed in the court hearing the initial motion unless the court otherwise directs.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1054-S.SL.pdf?cite=2005%20c%20433%20§%2027[2005 c 433 § 27]; ]

== 7.04A.280 - Appeals.
. An appeal may be taken from:

.. An order denying a motion to compel arbitration;

.. An order granting a motion to stay arbitration;

.. An order confirming or denying confirmation of an award;

.. An order modifying or correcting an award;

.. An order vacating an award without directing a rehearing; or

.. A final judgment entered under this chapter.

. An appeal under this section must be taken as from an order or a judgment in a civil action.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1054-S.SL.pdf?cite=2005%20c%20433%20§%2028[2005 c 433 § 28]; ]

== 7.04A.290 - Relationship to electronic signatures in global and national commerce act.
The provisions of this chapter governing the legal effect, validity, and enforceability of electronic records or electronic signatures, and of contracts performed with the use of such records or signatures conform to the requirements of section 102 of the electronic signatures in global and national commerce act.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1054-S.SL.pdf?cite=2005%20c%20433%20§%2032[2005 c 433 § 32]; ]

== 7.04A.900 - Effective date—2005 c 433.
This act takes effect January 1, 2006.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1054-S.SL.pdf?cite=2005%20c%20433%20§%2051[2005 c 433 § 51]; ]

== 7.04A.901 - Uniformity of application and construction—2005 c 433.
In applying and construing this uniform act, consideration must be given to the need to promote uniformity of the law with respect to its subject matter among states that enact it.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1054-S.SL.pdf?cite=2005%20c%20433%20§%2029[2005 c 433 § 29]; ]

== 7.04A.903 - Savings—2005 c 433.
This act does not affect an action or proceeding commenced or right accrued before January 1, 2006.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1054-S.SL.pdf?cite=2005%20c%20433%20§%2031[2005 c 433 § 31]; ]

