= 7.07 - Uniform mediation act.
:toc:

== 7.07.010 - Definitions.
In this chapter:

. "Mediation" means a process in which a mediator facilitates communication and negotiation between parties to assist them in reaching a voluntary agreement regarding their dispute.

. "Mediation communication" means a statement, whether oral or in a record or verbal or nonverbal, that occurs during a mediation or is made for purposes of considering, conducting, participating in, initiating, continuing, or reconvening a mediation or retaining a mediator.

. "Mediator" means an individual who conducts a mediation.

. "Nonparty participant" means a person, other than a party or mediator, that participates in a mediation.

. "Mediation party" means a person that participates in a mediation and whose agreement is necessary to resolve the dispute.

. "Person" means an individual, corporation, business trust, estate, trust, partnership, limited liability company, association, joint venture, government; governmental subdivision, agency, or instrumentality; or public corporation, or any other legal or commercial entity.

. "Proceeding" means:

.. A judicial, administrative, arbitral, or other adjudicative process, including related prehearing and posthearing motions, conferences, and discovery; or 

.. A legislative hearing or similar process.

. "Record" means information that is inscribed on a tangible medium or that is stored in an electronic or other medium and is retrievable in perceivable form.

. "Sign" means:

.. To execute or adopt a tangible symbol with the present intent to authenticate a record; or

.. To attach or logically associate an electronic symbol, sound, or process to or with a record with the present intent to authenticate a record.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5173-S.SL.pdf?cite=2005%20c%20172%20§%202[2005 c 172 § 2]; ]

== 7.07.020 - Scope.
. Except as otherwise provided in subsection (2) or (3) of this section, this chapter applies to a mediation in which:

.. The mediation parties are required to mediate by statute or court or administrative agency rule or referred to mediation by a court, administrative agency, or arbitrator;

.. The mediation parties and the mediator agree to mediate in a record that demonstrates an expectation that mediation communications will be privileged against disclosure; or

.. The mediation parties use as a mediator an individual who holds himself or herself out as a mediator or the mediation is provided by a person that holds itself out as providing mediation.

. This chapter does not apply to a mediation:

.. Conducted by a judge who might make a ruling on the case; or

.. Conducted under the auspices of:

... A primary or secondary school if all the parties are students; or

... A correctional institution for youths if all the parties are residents of that institution.

. If the parties agree in advance in a signed record, or a record of proceeding reflects agreement by the parties, that all or part of a mediation is not privileged, the privileges under RCW 7.07.030 through 7.07.050 do not apply to the mediation or part agreed upon. However, RCW 7.07.030 through 7.07.050 apply to a mediation communication made by a person that has not received actual notice of the agreement before the communication is made.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5173-S.SL.pdf?cite=2005%20c%20172%20§%203[2005 c 172 § 3]; ]

== 7.07.030 - Privilege against disclosure—Admissibility—Discovery.
. Except as otherwise provided in RCW 7.07.050, a mediation communication is privileged as provided in subsection (2) of this section and is not subject to discovery or admissible in evidence in a proceeding unless waived or precluded as provided by RCW 7.07.040.

. In a proceeding, the following privileges apply:

.. A mediation party may refuse to disclose, and may prevent any other person from disclosing, a mediation communication;

.. A mediator may refuse to disclose a mediation communication, and may prevent any other person from disclosing a mediation communication of the mediator; and

.. A nonparty participant may refuse to disclose, and may prevent any other person from disclosing, a mediation communication of the nonparty participant.

. Evidence or information that is otherwise admissible or subject to discovery does not become inadmissible or protected from discovery solely by reason of its disclosure or use in a mediation.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5173-S.SL.pdf?cite=2005%20c%20172%20§%204[2005 c 172 § 4]; ]

== 7.07.040 - Waiver and preclusion of privilege.
. A privilege under RCW 7.07.030 may be waived in a record or orally during a proceeding if it is expressly waived by all parties to the mediation and:

.. In the case of the privilege of a mediator, it is expressly waived by the mediator; and

.. In the case of the privilege of a nonparty participant, it is expressly waived by the nonparty participant.

. A person that discloses or makes a representation about a mediation communication which prejudices another person in a proceeding is precluded from asserting a privilege under RCW 7.07.030, but only to the extent necessary for the person prejudiced to respond to the representation or disclosure.

. A person that intentionally uses a mediation to plan, attempt to commit, or commit a crime, or to conceal an ongoing crime or ongoing criminal activity is precluded from asserting a privilege under RCW 7.07.030.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5173-S.SL.pdf?cite=2005%20c%20172%20§%205[2005 c 172 § 5]; ]

== 7.07.050 - Exceptions to privilege.
. There is no privilege under RCW 7.07.030 for a mediation communication that is:

.. In an agreement evidenced by a record signed by all parties to the agreement;

.. Made during a session of a mediation which is open, or is required by law to be open, to the public;

.. A threat or statement of a plan to inflict bodily injury or commit a crime of violence;

.. Intentionally used to plan a crime, attempt to commit or commit a crime, or to conceal an ongoing crime or ongoing criminal activity;

.. Sought or offered to prove or disprove a claim or complaint of professional misconduct or malpractice filed against a mediator;

.. Except as otherwise provided in subsection (3) of this section, sought or offered to prove or disprove a claim or complaint of professional misconduct or malpractice filed against a mediation party, nonparty participant, or representative of a party based on conduct occurring during a mediation; or

.. Sought or offered to prove or disprove abuse, neglect, abandonment, or exploitation in a proceeding in which a child or adult protective services agency is a party, unless the public agency participates in the child or adult protection mediation.

. There is no privilege under RCW 7.07.030 if a court finds, after a hearing in camera, that the party seeking discovery or the proponent of the evidence has shown that the evidence is not otherwise available, that there is a need for the evidence that substantially outweighs the interest in protecting confidentiality, and that the mediation communication is sought or offered in:

.. A criminal court proceeding involving a felony; or

.. Except as otherwise provided in subsection (3) of this section, a proceeding to prove a claim to rescind or reform or a defense to avoid liability on a contract arising out of the mediation.

. A mediator may not be compelled to provide evidence of a mediation communication referred to in subsection (1)(f) or (2)(b) of this section.

. If a mediation communication is not privileged under subsection (1) or (2) of this section, only the portion of the communication necessary for the application of the exception from nondisclosure may be admitted. Admission of evidence under subsection (1) or (2) of this section does not render the evidence, or any other mediation communication, discoverable or admissible for any other purpose.

. Records of mediation communications that are privileged under this chapter are exempt from the requirements of chapter 42.56 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2520.SL.pdf?cite=2006%20c%20209%20§%201[2006 c 209 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5173-S.SL.pdf?cite=2005%20c%20172%20§%206[2005 c 172 § 6]; ]

== 7.07.060 - Prohibited mediator reports.
. Except as provided in subsection (2) of this section, a mediator may not make a report, assessment, evaluation, recommendation, finding, or other communication regarding a mediation to a court, administrative agency, or other authority that may make a ruling on the dispute that is the subject of the mediation.

. A mediator may disclose:

.. Whether the mediation occurred or has terminated, whether a settlement was reached, attendance, and efforts to schedule a mediation ordered by a court, administrative agency, or other authority that may make a ruling on the dispute;

.. A mediation communication as permitted under RCW 7.07.050; or

.. A mediation communication evidencing abuse, neglect, abandonment, or exploitation of an individual to a public agency responsible for protecting individuals against such mistreatment.

. A communication made in violation of subsection (1) of this section may not be considered by a court, administrative agency, or arbitrator.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5173-S.SL.pdf?cite=2005%20c%20172%20§%207[2005 c 172 § 7]; ]

== 7.07.070 - Confidentiality.
Unless subject to chapter 42.30 RCW, mediation communications are confidential to the extent agreed by the parties or provided by other law or rule of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5173-S.SL.pdf?cite=2005%20c%20172%20§%208[2005 c 172 § 8]; ]

== 7.07.080 - Mediator's disclosure of conflicts of interest—Background.
. Before accepting a mediation, an individual who is requested to serve as a mediator shall:

.. Make an inquiry that is reasonable under the circumstances to determine whether there are any known facts that a reasonable individual would consider likely to affect the impartiality of the mediator, including a financial or personal interest in the outcome of the mediation and an existing or past relationship with a mediation party or foreseeable participant in the mediation; and

.. Disclose any such known fact to the mediation parties as soon as is practical before accepting a mediation.

. If a mediator learns any fact described in subsection (1)(a) of this section after accepting a mediation, the mediator shall disclose it as soon as is practicable.

. At the request of a mediation party, an individual who is requested to serve as a mediator shall disclose the mediator's qualifications to mediate a dispute.

. A person that violates subsection (1) or (2) of this section is precluded by the violation from asserting a privilege under RCW 7.07.030.

. Subsections (1) through (3) of this section do not apply to an individual acting as a judge.

. This chapter does not require that a mediator have a special qualification by background or profession.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5173-S.SL.pdf?cite=2005%20c%20172%20§%209[2005 c 172 § 9]; ]

== 7.07.090 - Participation in mediation.
An attorney or other individual designated by a party may accompany the party to and participate in a mediation, except that if the dispute being mediated is the subject of pending proceedings under chapter 12.40 RCW, then a party may not be represented by an attorney in mediation unless the party may be represented by an attorney in the proceedings under chapter 12.40 RCW. A waiver of participation given before the mediation may be rescinded.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5173-S.SL.pdf?cite=2005%20c%20172%20§%2010[2005 c 172 § 10]; ]

== 7.07.100 - Relation to electronic signatures in global and national commerce act.
This chapter modifies, limits, or supersedes the federal electronic signatures in global and national commerce act (15 U.S.C. Sec. 7001 et seq.), but this chapter does not modify, limit, or supersede section 101(c) of that act or authorize electronic delivery of any of the notices described in section 103(b) of that act.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5173-S.SL.pdf?cite=2005%20c%20172%20§%2011[2005 c 172 § 11]; ]

== 7.07.110 - Uniformity of application and construction.
In applying and construing this chapter, consideration should be given to the need to promote uniformity of the law with respect to its subject matter among states that enact it.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5173-S.SL.pdf?cite=2005%20c%20172%20§%2012[2005 c 172 § 12]; ]

== 7.07.900 - Short title—2005 c 172.
This act may be cited as the Uniform Mediation Act.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5173-S.SL.pdf?cite=2005%20c%20172%20§%201[2005 c 172 § 1]; ]

== 7.07.903 - Application to existing agreements or referrals.
. This chapter governs a mediation pursuant to a referral or an agreement to mediate made on or after January 1, 2006.

. If all parties agree in a signed record or a record of proceeding reflects such an agreement by all parties, then this chapter governs a mediation pursuant to a referral or an agreement to mediate whenever made.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5173-S.SL.pdf?cite=2005%20c%20172%20§%2022[2005 c 172 § 22]; ]

== 7.07.904 - Effective date—2005 c 172.
This act takes effect January 1, 2006.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5173-S.SL.pdf?cite=2005%20c%20172%20§%2023[2005 c 172 § 23]; ]

