= 7.16 - Certiorari, mandamus, and prohibition.
:toc:

== 7.16.010 - Parties, how designated.
The party prosecuting a special proceeding may be known as the plaintiff and the adverse party as the defendant.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c65.pdf?cite=1895%20c%2065%20§%201[1895 c 65 § 1]; RRS § 999; ]

== 7.16.020 - Judgment, motion, and order defined.
A judgment in a special proceeding is the final determination of the rights of the parties therein. The definitions of a motion and an order in a civil action are applicable to similar acts in a special proceeding.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c65.pdf?cite=1895%20c%2065%20§%202[1895 c 65 § 2]; RRS § 1000; ]

== 7.16.030 - Certiorari defined.
The writ of certiorari may be denominated the writ of review.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c65.pdf?cite=1895%20c%2065%20§%203[1895 c 65 § 3]; RRS § 1001; ]

== 7.16.040 - Grounds for granting writ.
A writ of review shall be granted by any court, except a municipal or district court, when an inferior tribunal, board or officer, exercising judicial functions, has exceeded the jurisdiction of such tribunal, board or officer, or one acting illegally, or to correct any erroneous or void proceeding, or a proceeding not according to the course of the common law, and there is no appeal, nor in the judgment of the court, any plain, speedy and adequate remedy at law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c202.pdf?cite=1987%20c%20202%20§%20130[1987 c 202 § 130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c65.pdf?cite=1895%20c%2065%20§%204[1895 c 65 § 4]; RRS § 1002; ]

== 7.16.050 - Application for writ—Notice.
The application must be made on affidavit by the party beneficially interested, and the court may require a notice of the application to be given to the adverse party, or may grant an order to show cause why it should not be allowed, or may grant the writ without notice.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c65.pdf?cite=1895%20c%2065%20§%205[1895 c 65 § 5]; RRS § 1003; ]

== 7.16.060 - Writ, to whom directed.
The writ may be directed to the inferior tribunal, board or officer, or to any other person having the custody of the record or proceedings to be certified. When directed to a tribunal the clerk, if there be one, must return the writ with the transcript required.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c65.pdf?cite=1895%20c%2065%20§%206[1895 c 65 § 6]; RRS § 1004; ]

== 7.16.070 - Contents of writ.
The writ of review must command the party to whom it is directed to certify fully to the court issuing the writ, at a specified time and place, a transcript of the record and proceedings (describing or referring to them with convenient certainty), that the same may be reviewed by the court, and requiring the party, in the meantime, to desist from further proceedings in the matter to be reviewed.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c65.pdf?cite=1895%20c%2065%20§%207[1895 c 65 § 7]; RRS § 1005; ]

== 7.16.080 - Stay of proceedings.
If a stay of proceedings be not intended, the words requiring the stay must be omitted from the writ. These words may be inserted or omitted, in the sound discretion of the court, but if omitted the power of the inferior court or office is not suspended or the proceedings stayed.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c65.pdf?cite=1895%20c%2065%20§%208[1895 c 65 § 8]; RRS § 1006; ]

== 7.16.100 - Service of writ.
The writ may be served as follows, except where different directions respecting the mode of service thereof are given by the court granting it:

. Where it is directed to a person or persons by name or by his or her official title or titles, or to a municipal corporation, it must be served upon each officer or other person to whom it is directed, or upon the corporation, in the same manner as a summons.

. Where it is directed to a court, or to the judges of a court, having a clerk appointed pursuant to law, service upon the court or the judges thereof may be made by filing the writ with the clerk.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c65.pdf?cite=1895%20c%2065%20§%2010[1895 c 65 § 10]; RRS § 1008; ]

== 7.16.110 - Defective return—Further return—Hearing—Judgment.
If the return of the writ be defective, the court may order a further return to be made. When a full return has been made, the court must hear the parties, or such of them as may attend for that purpose, and may thereupon give judgment, either affirming or annulling or modifying the proceedings below.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c65.pdf?cite=1895%20c%2065%20§%2011[1895 c 65 § 11]; RRS § 1009; ]

== 7.16.120 - Questions involving merits to be determined.
The questions involving the merits to be determined by the court upon the hearing are:

. Whether the body or officer had jurisdiction of the subject matter of the determination under review.

. Whether the authority, conferred upon the body or officer in relation to that subject matter, has been pursued in the mode required by law, in order to authorize it or to make the determination.

. Whether, in making the determination, any rule of law affecting the rights of the parties thereto has been violated to the prejudice of the relator.

. Whether there was any competent proof of all the facts necessary to be proved, in order to authorize the making of the determination.

. Whether the factual determinations were supported by substantial evidence.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c7.pdf?cite=1989%20c%207%20§%201[1989 c 7 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c51.pdf?cite=1957%20c%2051%20§%206[1957 c 51 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c65.pdf?cite=1895%20c%2065%20§%2012[1895 c 65 § 12]; RRS § 1010; ]

== 7.16.130 - Copy of judgment to inferior tribunal, board, or officer.
A copy of the judgment signed by the clerk, must be transmitted to the inferior tribunal, board or officer having the custody of the record or proceeding certified up.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c65.pdf?cite=1895%20c%2065%20§%2013[1895 c 65 § 13]; RRS § 1011; ]

== 7.16.140 - Judgment roll.
A copy of the judgment signed by the clerk, entered upon or attached to the writ and return, constitute the judgment roll.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c65.pdf?cite=1895%20c%2065%20§%2014[1895 c 65 § 14]; RRS § 1012; ]

== 7.16.150 - Mandamus defined.
The writ of mandamus may be denominated a writ of mandate.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c65.pdf?cite=1895%20c%2065%20§%2015[1895 c 65 § 15]; RRS § 1013; ]

== 7.16.160 - Grounds for granting writ.
It may be issued by any court, except a district or municipal court, to any inferior tribunal, corporation, board or person, to compel the performance of an act which the law especially enjoins as a duty resulting from an office, trust or station, or to compel the admission of a party to the use and enjoyment of a right or office to which the party is entitled, and from which the party is unlawfully precluded by such inferior tribunal, corporation, board or person.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c202.pdf?cite=1987%20c%20202%20§%20131[1987 c 202 § 131]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c3.pdf?cite=1987%20c%203%20§%203[1987 c 3 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c65.pdf?cite=1895%20c%2065%20§%2016[1895 c 65 § 16]; RRS § 1014; ]

== 7.16.170 - Absence of remedy at law required—Affidavit.
The writ must be issued in all cases where there is not a plain, speedy and adequate remedy in the ordinary course of law. It must be issued upon affidavit on the application of the party beneficially interested.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c65.pdf?cite=1895%20c%2065%20§%2017[1895 c 65 § 17]; RRS § 1015; ]

== 7.16.180 - Alternative or peremptory writs—Form.
The writ may be either alternative or peremptory. The alternative writ must state generally the allegation against the party to whom it is directed, and command such party, immediately after the receipt of the writ, or at some other specified time, to do the act required to be performed, or to show cause before the court, at a specified time and place, why he or she has not done so. The peremptory writ must be in some similar form, except the words requiring the party to show cause why he or she has not done as commanded must be omitted and a return day inserted.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20165[2011 c 336 § 165]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c65.pdf?cite=1895%20c%2065%20§%2018[1895 c 65 § 18]; RRS § 1016; ]

== 7.16.190 - Notice of application—No default.
When the application to the court is made without notice to the party, and the writ be allowed, the alternative must be first issued; and if the application be upon due notice and the writ be allowed, the peremptory writ may be issued in the first instance. The notice of the application, when given, must be at least ten days. The writ cannot be granted by default. The case must be heard by the court, whether the adverse party appear or not.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c65.pdf?cite=1895%20c%2065%20§%2019[1895 c 65 § 19]; RRS § 1017; ]

== 7.16.200 - Answer.
On the return of the alternative, or the day on which the application for the writ is noticed, the party on whom the writ or notice has been served may show cause by answer, under oath, made in the same manner as an answer to a complaint in a civil action.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c65.pdf?cite=1895%20c%2065%20§%2020[1895 c 65 § 20]; RRS § 1018; ]

== 7.16.210 - Questions of fact, how determined.
If an answer be made which raises a question as to a matter of fact essential to the determination of the motion, and affecting the substantial rights of the parties, and upon the supposed truth of the allegation of which the application for the writ is based, the court may, in its discretion, order the question to be tried before a jury, and postpone the argument until such trial can be had, and the verdict certified to the court. The question to be tried must be distinctly stated in the order for trial, and the county must be designated in which the same shall be had. The order may also direct the jury to assess any damages which the appellant may have sustained, in case they find for him or her.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20166[2011 c 336 § 166]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c65.pdf?cite=1895%20c%2065%20§%2021[1895 c 65 § 21]; RRS § 1019; ]

== 7.16.220 - Applicant may demur to answer or countervail it by proof.
On the trial the applicant is not precluded by the answer from any valid objections to its sufficiency, and may countervail it by proof, either in direct denial or by way of avoidance.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c65.pdf?cite=1895%20c%2065%20§%2022[1895 c 65 § 22]; RRS § 1020; ]

== 7.16.230 - Motion for new trial, where made.
The motion for new trial must be made in the court in which the issue of fact is tried.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c65.pdf?cite=1895%20c%2065%20§%2023[1895 c 65 § 23]; RRS § 1021; ]

== 7.16.240 - Certification of verdict—Argument.
If no notice of a motion for a new trial be given, or if given, the motion be denied, the clerk, within five days after rendition of the verdict or denial of the motion, must transmit to the court in which the application for the writ is pending, a certified copy of the verdict attached to the order of trial, after which either party may bring on the argument of the application, upon reasonable notice to the adverse party.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c65.pdf?cite=1895%20c%2065%20§%2024[1895 c 65 § 24]; RRS § 1022; ]

== 7.16.250 - Hearing.
If no answer be made, the case must be heard on the papers of the applicant. If the answer raises only questions of law, or puts in issue immaterial statements not affecting the substantial rights of the party, the court must proceed to hear or fix a day for hearing the argument of the case.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c65.pdf?cite=1895%20c%2065%20§%2025[1895 c 65 § 25]; RRS § 1023; ]

== 7.16.260 - Judgment for damages and costs—Peremptory mandate.
If judgment be given for the applicant he or she may recover the damages which he or she has sustained, as found by the jury or as may be determined by the court or referee, upon a reference to be ordered, together with costs; and for such damages and costs an execution may issue, and a peremptory mandate must also be awarded without delay.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20167[2011 c 336 § 167]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c65.pdf?cite=1895%20c%2065%20§%2026[1895 c 65 § 26]; RRS § 1024; ]

== 7.16.270 - Service of writ.
The writ must be served in the same manner as a summons in a civil action, except when otherwise expressly directed by order of the court. Service upon a majority of the members of any board or body is service upon the board or body, whether at the time of the service the board or body was in session or not.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c65.pdf?cite=1895%20c%2065%20§%2027[1895 c 65 § 27]; RRS § 1025; ]

== 7.16.280 - Enforcement of writ—Penalty.
When a temporary mandate has been issued and directed to any inferior tribunal, corporation, board or person upon whom the writ has been personally served and such tribunal, corporation, board, or person has without just excuse, refused or neglected to obey the same, the court may, upon motion, impose a fine not exceeding one thousand dollars. In case of persistence in a refusal or disobedience, the court may order the party to be imprisoned until the writ is obeyed, and may make any orders necessary and proper for the complete enforcement of the writ.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c51.pdf?cite=1957%20c%2051%20§%207[1957 c 51 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c65.pdf?cite=1895%20c%2065%20§%2028[1895 c 65 § 28]; RRS § 1026; ]

== 7.16.290 - Prohibition defined.
The writ of prohibition is the counterpart of the writ of mandate. It arrests the proceedings of any tribunal, corporation, board or person, when such proceedings are without or in excess of the jurisdiction of such tribunal, corporation, board or person.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c65.pdf?cite=1895%20c%2065%20§%2029[1895 c 65 § 29]; RRS § 1027; ]

== 7.16.300 - Grounds for granting writ—Affidavit.
It may be issued by any court, except district or municipal courts, to an inferior tribunal, or to a corporation, board or person, in all cases where there is not a plain, speedy and adequate remedy in the ordinary course of law. It is issued upon affidavit, on the application of the person beneficially interested.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c202.pdf?cite=1987%20c%20202%20§%20132[1987 c 202 § 132]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c65.pdf?cite=1895%20c%2065%20§%2030[1895 c 65 § 30]; RRS § 1028; ]

== 7.16.310 - Alternative or peremptory writs—Form.
The writ must be either alternative or peremptory. The alternative writ must state generally the allegations against the party to whom it is directed, and command such party to desist or refrain from further proceedings in the action or matter specified therein until the further order of the court from which it is issued, and to show cause before such court, at a specified time and place, why such party should not be absolutely restrained from any further proceedings in such action or matter. The peremptory writ must be in a similar form, except that the words requiring the party to show cause why he or she should not be absolutely restrained, etc., must be omitted and a return day inserted.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20168[2011 c 336 § 168]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c65.pdf?cite=1895%20c%2065%20§%2031[1895 c 65 § 31]; RRS § 1029; ]

== 7.16.320 - Provisions relating to mandate applicable.
The provisions of this chapter relating to writ of mandate, apply to this proceeding.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c65.pdf?cite=1895%20c%2065%20§%2032[1895 c 65 § 32]; RRS § 1030; ]

== 7.16.330 - When writs may be made returnable.
Writs of review, mandate, and prohibition issued by the supreme court, the court of appeals, or by a superior court, may, in the discretion of the court issuing the writ, be made returnable, and a hearing thereon be had at any time.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971c81.pdf?cite=1971%20c%2081%20§%2029[1971 c 81 § 29]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c65.pdf?cite=1895%20c%2065%20§%2033[1895 c 65 § 33]; RRS § 1031; ]

== 7.16.340 - Rules of practice.
Except as otherwise provided in this chapter, the provisions of the code of procedure concerning civil actions are applicable to and constitute the rules of practice in the proceedings in this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c65.pdf?cite=1895%20c%2065%20§%2034[1895 c 65 § 34]; RRS § 1032; ]

== 7.16.350 - Appellate review.
From a final judgment in the superior court, in any such proceeding, appellate review by the supreme court or the court of appeals may be sought as in other actions.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c202.pdf?cite=1988%20c%20202%20§%204[1988 c 202 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971c81.pdf?cite=1971%20c%2081%20§%2030[1971 c 81 § 30]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c65.pdf?cite=1895%20c%2065%20§%2035[1895 c 65 § 35]; RRS § 1033; ]

== 7.16.360 - Inapplicability to action reviewable under Administrative Procedure Act or Land Use Petition Act.
This chapter does not apply to state agency action reviewable under chapter 34.05 RCW or to land use decisions of local jurisdictions reviewable under chapter 36.70C RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1724-S.SL.pdf?cite=1995%20c%20347%20§%20716[1995 c 347 § 716]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c175.pdf?cite=1989%20c%20175%20§%2038[1989 c 175 § 38]; ]

