= 7.25 - Declaratory judgments of local bond issues.
:toc:

== 7.25.005 - Definitions.
As used in this chapter, the following terms have the meanings indicated unless the context clearly requires otherwise:

. "Government entity" means the state of Washington, the state finance committee, any county, city, school district, other municipal corporation, taxing district, or any agency, instrumentality, or public corporation thereof.

. "Bonds" means one or more bonds, notes, or other evidences of indebtedness.

. "Interested parties" means all taxpayers, ratepayers, or any other persons who have any obligations, rights, or other interests in the bonds or issuance thereof, or the project or purpose for which the bonds were issued or are to be issued.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5728-S.SL.pdf?cite=1999%20c%20284%20§%202[1999 c 284 § 2]; ]

== 7.25.010 - Validity of bond issues may be tested.
Whenever the legislative or governing body of the state or any county, city, school district, other municipal corporation, taxing district, or any agency, instrumentality, or public corporation thereof shall desire to issue bonds of any kind and shall have passed an ordinance or resolution authorizing the same, the validity of such proposed bond issue may be tested and determined in the manner provided in this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5728-S.SL.pdf?cite=1999%20c%20284%20§%201[1999 c 284 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c263.pdf?cite=1983%20c%20263%20§%201[1983 c 263 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c153.pdf?cite=1939%20c%20153%20§%201[1939 c 153 § 1]; RRS § 5616-11; ]

== 7.25.020 - Complaint—Defendants—Service—Intervention—Attorneys' fee—Notice of action.
A complaint shall be prepared and filed in the superior court by such government entity setting forth such ordinance or resolution and that it is the purpose of the plaintiff to issue and sell bonds as stated therein and that it is desired that the right of the plaintiff to so issue such bonds and sell the same shall be tested and determined in said action. In said action all interested parties shall be deemed to be defendants. The title of the action shall be "In re (name of bond issue)." Upon the filing of the complaint the court shall, upon the application of the plaintiff, enter an order naming one or more interested parties upon whom service in said action shall be made as the representative of all interested parties, except such as may intervene as herein provided, and in such case the court shall fix and allow a reasonable attorneys' fee in said action to the attorney who shall represent the representative interested parties as aforesaid, and such fee and all taxable costs incurred by such representative interested parties shall be taxed as costs against the plaintiff: PROVIDED, That if the interested parties appointed by the court shall default, the court shall appoint an attorney who shall defend said action on behalf of all interested parties, and such attorney shall be allowed a reasonable fee and taxable costs to be taxed against the plaintiff: PROVIDED FURTHER, That after filing the complaint, the plaintiff shall twice place a notice in a newspaper of general circulation within the boundaries of the government entity, stating the title of the action, informing the interested parties that the action has been commenced testing the validity of the bonds, and stating that any interested parties, as that term is defined herein, may intervene in such action and be represented therein by his or her own attorney. Thereupon, any interested parties who desire to intervene must apply to the court to intervene within ten days after the second publication of the notice.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20169[2011 c 336 § 169]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5728-S.SL.pdf?cite=1999%20c%20284%20§%203[1999 c 284 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c263.pdf?cite=1983%20c%20263%20§%202[1983 c 263 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c153.pdf?cite=1939%20c%20153%20§%202[1939 c 153 § 2]; RRS § 5616-12; ]

== 7.25.030 - Judgment as to validity of all or part of bond issue—Effect.
The court in such action shall enter its judgment determining whether or not the bonds as proposed will be valid, and if the court finds that a portion, but not all, of the said bond issue is authorized by law, the court shall so declare, and find by its judgment what portion of such bond issue will be valid, and the judgment in said action shall be conclusive and binding upon all interested parties and upon all other persons.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5728-S.SL.pdf?cite=1999%20c%20284%20§%204[1999 c 284 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c153.pdf?cite=1939%20c%20153%20§%203[1939 c 153 § 3]; RRS § 5616-13; ]

== 7.25.040 - Other declaratory judgment provisions applicable.
Except as otherwise herein provided, all the provisions of the laws of Washington relating to declaratory judgments shall apply to the action herein provided for. The remedy and procedure herein provided shall be in addition to other remedies and procedures now provided by law.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5728-S.SL.pdf?cite=1999%20c%20284%20§%205[1999 c 284 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c153.pdf?cite=1939%20c%20153%20§%204[1939 c 153 § 4]; RRS § 5616-14; ]

