= 7.48A - Moral nuisances.
:toc:

== 7.48A.010 - Definitions.
The definitions set forth in this section shall apply throughout this chapter.

. "Knowledge" or "knowledge of such nuisance" means having knowledge of the contents and character of the patently offensive sexual or violent conduct which appears in the lewd matter, or knowledge of the acts of lewdness or prostitution which occur on the premises, or knowledge that controlled substances identified in Article II of chapter 69.50 RCW and not authorized by that chapter, are manufactured, delivered or possessed, or where any such substance not obtained in a manner authorized by chapter 69.50 RCW is consumed by ingestion, inhalation, or injection or any other means.

. "Lewd matter" is synonymous with "obscene matter" and means any matter:

.. Which the average person, applying contemporary community standards, would find, when considered as a whole, appeals to the prurient interest; and

.. Which explicitly depicts or describes patently offensive representations or descriptions of:

... Ultimate sexual acts, normal or perverted, actual or simulated; or

... Masturbation, fellatio, cunnilingus, bestiality, excretory functions, or lewd exhibition of the genitals or genital area; or

... Violent or destructive sexual acts, including but not limited to human or animal mutilation, dismemberment, rape or torture; and

.. Which, when considered as a whole, and in the context in which it is used, lacks serious literary, artistic, political, or scientific value.

. "Lewdness" shall have and include all those meanings which are assigned to it under the common law.

. "Live performance" means any play, show, skit, dance, or other exhibition performed or presented to or before an audience of one or more, in person or by electronic transmission, with or without consideration.

. "Matter" shall mean a live performance, a motion picture film, or a publication or any combination thereof.

. "Motion picture film" shall include any:

.. Film or plate negative;

.. Film or plate positive;

.. Film designed to be projected on a screen for exhibition;

.. Film, glass slides, or transparencies, either in negative or positive form, designed for exhibition by projection on a screen;

.. Videotape or any other medium used to electronically reproduce images on a screen.

. "Person" means any individual, partnership, firm, association, corporation, or other legal entity.

. "Place" includes, but is not limited to, any building, structure, or places, or any separate part or portion thereof, whether permanent or not, or the ground itself.

. "Prurient" means that which incites lasciviousness or lust.

. "Publication" shall include any book, magazine, article, pamphlet, writing, printing, illustration, picture, sound recording, or coin-operated machine.

. "Sale" means a passing of title or right of possession from a seller to a buyer for valuable consideration, and shall include, but is not limited to, any lease or rental arrangement or other transaction wherein or whereby any valuable consideration is received for the use of, or transfer of possession of, lewd matter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c152.pdf?cite=1990%20c%20152%20§%204[1990 c 152 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c141.pdf?cite=1988%20c%20141%20§%202[1988 c 141 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c184.pdf?cite=1982%20c%20184%20§%201[1982 c 184 § 1]; ]

== 7.48A.020 - Moral nuisances—Declaration of.
The following are declared to be moral nuisances:

. Any and every place in the state where lewd films are publicly exhibited as a regular course of business, or possessed for the purpose of such exhibition, or where lewd live performances are publicly exhibited as a regular course of business;

. Any and every lewd film which is publicly exhibited, or possessed for such purpose at a place which is a moral nuisance under this section;

. Any and every place of business in the state in which lewd publications constitute a principal part of the stock in trade;

. Every place which, as a regular course of business, is used for the purpose of lewdness or prostitution, and every such place in or upon which acts of lewdness or prostitution are conducted, permitted, carried on, continued, or exist;

. All houses, housing units, other buildings, or places of resort where controlled substances identified in Article II of chapter 69.50 RCW and not authorized by that chapter, are manufactured, delivered, or possessed, or where any such substance not obtained in a manner authorized by chapter 69.50 RCW is consumed by ingestion, inhalation, injection, or any other means.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c152.pdf?cite=1990%20c%20152%20§%205[1990 c 152 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c141.pdf?cite=1988%20c%20141%20§%203[1988 c 141 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c184.pdf?cite=1982%20c%20184%20§%202[1982 c 184 § 2]; ]

== 7.48A.030 - Civil actions—Who may bring.
Any of the following parties may bring a civil action in the superior court of any county where a moral nuisance is alleged to have been maintained:

. The prosecuting attorney for the county where the alleged moral nuisance is located;

. The city attorney for the city where the alleged moral nuisance is located; or

. The attorney general.

The rules of evidence, burden of proof, and all other rules of court shall be the court rules generally applicable to civil cases in this state: PROVIDED, That the standard of proof on the issue of obscenity shall be clear, cogent, and convincing evidence.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c184.pdf?cite=1982%20c%20184%20§%203[1982 c 184 § 3]; ]

== 7.48A.040 - Maintenance of moral nuisance—Fine—Maximum.
. No person shall with knowledge maintain a moral nuisance.

. Upon a determination that a defendant has with knowledge maintained a moral nuisance, the court shall impose a civil fine and judgment of an amount as the court shall determine to be appropriate. In imposing the civil fine, the court shall consider the wilfulness of the defendant's conduct and the profits made by the defendant attributable to the lewd matter, lewdness, or prostitution, whichever is applicable. In no event shall the civil fine exceed the greater of twenty-five thousand dollars or these profits.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c235.pdf?cite=1985%20c%20235%20§%201[1985 c 235 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c184.pdf?cite=1982%20c%20184%20§%204[1982 c 184 § 4]; ]

== 7.48A.050 - Fines—Payment.
All civil fines assessed under RCW 7.48A.040 shall be paid into the general treasury of the governmental unit commencing the civil action.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c235.pdf?cite=1985%20c%20235%20§%202[1985 c 235 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c184.pdf?cite=1982%20c%20184%20§%205[1982 c 184 § 5]; ]

== 7.48A.060 - Exceptions to application of chapter.
Nothing in this chapter applies to the circulation of any material by any recognized historical society or museum, any library of any college or university, or to any archive or library under the supervision and control of the state, county, municipality, or other political subdivision.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c184.pdf?cite=1982%20c%20184%20§%206[1982 c 184 § 6]; ]

== 7.48A.070 - Findings.
The legislature finds that actions against moral nuisances as declared in RCW 7.48A.020 (1) through (4) involve balancing the safeguards necessary to protect constitutionally protected speech and the community and law enforcement efforts to curb dissemination of obscene matters. The legislature finds that the difficulty in ascertaining and obtaining originals and copies of obscene matters for evidentiary purposes thwarts legitimate enforcement efforts. The legislature finds that the balancing of the concerns warrants specific discovery procedures applicable to actions against moral nuisances involving obscene matters.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c70.pdf?cite=1989%20c%2070%20§%201[1989 c 70 § 1]; ]

== 7.48A.080 - Temporary injunction.
After the plaintiff files a civil action under this chapter, the plaintiff may apply to the superior court in which the plaintiff filed the action for a temporary or preliminary injunction. The court shall grant a hearing within ten days after the plaintiff applies for a temporary injunction.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c70.pdf?cite=1989%20c%2070%20§%202[1989 c 70 § 2]; ]

== 7.48A.090 - Restraining order—Service—Violation of order or injunction.
After the plaintiff applies for a temporary or preliminary injunction, the court may, upon a showing of good cause, issue an ex parte restraining order restraining the defendant and all other persons from removing or in any manner interfering with the personal property and contents of the place where the nuisance is alleged to exist, until the court grants or denies the plaintiff's application for a temporary or preliminary injunction or until further order of the court. However, pending the court's decision on the injunction, the temporary restraining order shall not restrain the exhibition or sale of any film, publication or item of stock in trade. The order may require that at least one original of each film or publication shall be preserved pending the hearing on the injunction. The court may require an inventory and full accounting of all business transactions.

The officer serving the restraining order or preliminary injunction may serve the order by handing to and leaving a copy with any person in charge of the place or residing in the place, or by posting a copy in a conspicuous place at or upon one or more of the principal doors or entrances to the place, or by both delivery and posting. The officer serving the restraining order or injunction shall forthwith make and return to the court, an inventory of the personal property and contents situated in and used in conducting or maintaining the alleged nuisance.

Any violation of the temporary order or injunction is a contempt of court. Mutilation or removal of a posted order that is in force is a contempt of court if the posted order or injunction contains a notice to that effect.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c70.pdf?cite=1989%20c%2070%20§%203[1989 c 70 § 3]; ]

== 7.48A.100 - When bond or security not required.
A bond or security shall not be required of the city attorney, the prosecuting attorney, or the attorney general.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c70.pdf?cite=1989%20c%2070%20§%204[1989 c 70 § 4]; ]

== 7.48A.110 - Hearing—Service of notice.
A copy of the complaint, together with a notice of the time and place of the hearing on the application for a temporary injunction, shall be served upon the defendant at least three business days before the hearing. Service may also be made by posting the required documents in the same manner as is provided in RCW 7.48A.090. If the defendant requests a continuance of the hearing, all temporary restraining orders and injunctions shall be extended as a matter of course.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c70.pdf?cite=1989%20c%2070%20§%205[1989 c 70 § 5]; ]

== 7.48A.120 - Production of discovery materials—Temporary injunction.
If the court finds at the hearing for an injunction, that the accounting, inventory, personal property, and contents of the place alleged to be a nuisance provide evidence of a moral nuisance as defined by RCW 7.48A.020 (1) through (4), the court may order the defendant to produce to the plaintiff a limited number of original films, film plates, publications, videotapes, any other obscene matter, and other discovery materials the court determines is necessary for evidentiary purposes to resolve the action on the merits.

The court may issue a temporary injunction enjoining the defendant and all other persons from removing or in any manner interfering with the court-ordered discovery. This discovery procedure supplements and does not replace any other discovery procedures and rules generally applicable to civil cases in this state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c70.pdf?cite=1989%20c%2070%20§%206[1989 c 70 § 6]; ]

== 7.48A.130 - Precedence of hearing on injunction.
The hearing on the injunction shall have precedence over all other actions, except prior matters of the same character, criminal proceedings, election contests, hearings on temporary restraining orders and injunctions, and actions to forfeit vehicles used in violation of the uniform controlled substances act, chapter 69.50 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c70.pdf?cite=1989%20c%2070%20§%207[1989 c 70 § 7]; ]

== 7.48A.140 - Violation of order or injunction—Penalties.
An intentional violation of a restraining order, preliminary injunction, or injunction under this chapter is punishable as a contempt of court.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c70.pdf?cite=1989%20c%2070%20§%208[1989 c 70 § 8]; ]

