= 7.40 - Injunctions.
:toc:

== 7.40.010 - Who may grant restraining orders and injunctions.
Restraining orders and injunctions may be granted by the superior court, or by any judge thereof.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c9.pdf?cite=1957%20c%209%20§%2011[1957 c 9 § 11]; Code 1881 § 153; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2032%20§%20153[1877 p 32 § 153]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2038%20§%20151[1869 p 38 § 151]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20152%20§%20111[1854 p 152 § 111]; RRS § 718; ]

== 7.40.020 - Grounds for issuance.
When it appears by the complaint that the plaintiff is entitled to the relief demanded and the relief, or any part thereof, consists in restraining the commission or continuance of some act, the commission or continuance of which during the litigation would produce great injury to the plaintiff; or when during the litigation, it appears that the defendant is doing, or threatened, or is about to do, or is procuring, or is suffering some act to be done in violation of the plaintiff's rights respecting the subject of the action tending to render the judgment ineffectual; or where such relief, or any part thereof, consists in restraining proceedings upon any final order or judgment, an injunction may be granted to restrain such act or proceedings until the further order of the court, which may afterwards be dissolved or modified upon motion. And where it appears in the complaint at the commencement of the action, or during the pendency thereof, by affidavit, that the defendant threatens, or is about to remove or dispose of his or her property with intent to defraud his or her creditors, a temporary injunction may be granted to restrain the removal or disposition of his or her property.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20194[2011 c 336 § 194]; Code 1881 § 154; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2033%20§%20154[1877 p 33 § 154]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2038%20§%20152[1869 p 38 § 152]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20152%20§%20112[1854 p 152 § 112]; RRS § 719; ]

== 7.40.030 - Malicious erection of structure may be enjoined.
An injunction may be granted to restrain the malicious erection, by any owner or lessee of land, of any structure intended to spite, injure or annoy an adjoining proprietor. And where any owner or lessee of land has maliciously erected such a structure with such intent, a mandatory injunction will lie to compel its abatement and removal.

[ 1883 p 44 § 1, part; Code 1881 § 154 1/2; RRS § 720; ]

== 7.40.040 - Time of granting.
The injunction may be granted at the time of commencing the action, or at any time afterwards, before judgment in that proceeding.

[ Code 1881 § 155; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2033%20§%20155[1877 p 33 § 155]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2039%20§%20153[1869 p 39 § 153]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20153%20§%20113[1854 p 153 § 113]; RRS § 721; ]

== 7.40.050 - Notice—Restraining orders in emergencies.
No injunction shall be granted until it shall appear to the court or judge granting it, that some one or more of the opposite party concerned, has had reasonable notice of the time and place of making application, except that in cases of emergency to be shown in the complaint, the court may grant a restraining order until notice can be given and hearing had thereon.

[ Code 1881 § 156; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2033%20§%20156[1877 p 33 § 156]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2039%20§%20154[1869 p 39 § 154]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20153%20§%20114[1854 p 153 § 114]; RRS § 722; ]

== 7.40.060 - Affidavits at hearing.
On the hearing of an application for an injunction, each party may read affidavits.

[ Code 1881 § 157; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2033%20§%20157[1877 p 33 § 157]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2039%20§%20155[1869 p 39 § 155]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20153%20§%20115[1854 p 153 § 115]; RRS § 723; ]

== 7.40.070 - Terms and conditions may be imposed.
Upon the granting or continuing an injunction, such terms and conditions may be imposed upon the party obtaining it as may be deemed equitable.

[ Code 1881 § 158; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2033%20§%20158[1877 p 33 § 158]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2039%20§%20156[1869 p 39 § 156]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20153%20§%20116[1854 p 153 § 116]; RRS § 724; ]

== 7.40.080 - Injunction bond.
No injunction or restraining order shall be granted until the party asking it shall enter into a bond, in such a sum as shall be fixed by the court or judge granting the order, with surety to the satisfaction of the clerk of the superior court, to the adverse party affected thereby, conditioned to pay all damages and costs which may accrue by reason of the injunction or restraining order. The sureties shall, if required by the clerk, justify as provided by law, and until they so justify, the clerk shall be responsible for their sufficiency. The court in its sound discretion may waive the required bond in situations in which a person's health or life would be jeopardized.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5449.SL.pdf?cite=1994%20c%20185%20§%205[1994 c 185 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c51.pdf?cite=1957%20c%2051%20§%209[1957 c 51 § 9]; Code 1881 § 159; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2033%20§%20159[1877 p 33 § 159]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2039%20§%20157[1869 p 39 § 157]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20153%20§%20117[1854 p 153 § 117]; RRS § 725; ]

== 7.40.085 - Injunction bonds for injunctions affecting public construction contracts.
In determining the amount of the bond required by RCW 7.40.080 as now or hereafter amended, with respect to an injunction or restraining order that will delay or enjoin a notice to proceed or the performance of work under a construction contract for a public contracting body among the factors regarded in the exercise of its discretion, the court shall consider:

. All costs and liquidated damages provided for in the contract or otherwise that may result from such delay;

. The probable costs to the public in terms of inconvenience, delayed use of the proposed facilities, and escalation of costs of delayed construction of the proposed facilities that may be incurred as a result of a delay subsequently found to be without good cause; and

. The procedures for consideration of objections to proposed construction and the opportunity the one seeking the injunction had for objecting prior to the letting of the contract.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c153.pdf?cite=1974%20ex.s.%20c%20153%20§%201[1974 ex.s. c 153 § 1]; ]

== 7.40.090 - Bond for injunction after temporary restraining order.
When an injunction is granted upon the hearing, after a temporary restraining order, the plaintiff shall not be required to enter into a second bond, unless the former shall be deemed insufficient, but the plaintiff and his or her surety shall remain liable upon his or her original bond.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20195[2011 c 336 § 195]; Code 1881 § 160; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2033%20§%20160[1877 p 33 § 160]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2039%20§%20158[1869 p 39 § 158]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20153%20§%20118[1854 p 153 § 118]; RRS § 726; ]

== 7.40.100 - Copy of order serves as writ.
It shall not be necessary to issue a writ of injunction, but the clerk shall issue a copy of the order of injunction duly certified by him or her, which shall be forthwith served by delivering the same to the adverse party.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20196[2011 c 336 § 196]; Code 1881 § 161; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2033%20§%20161[1877 p 33 § 161]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2039%20§%20159[1869 p 39 § 159]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20153%20§%20119[1854 p 153 § 119]; RRS § 727; ]

== 7.40.110 - Stay of judgment—Release of errors.
In application to stay proceedings after judgment, the plaintiff shall endorse upon his or her complaint a release of errors in the judgment whenever required to do so by the judge or court.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20197[2011 c 336 § 197]; Code 1881 § 162; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2033%20§%20162[1877 p 33 § 162]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2039%20§%20160[1869 p 39 § 160]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20153%20§%20120[1854 p 153 § 120]; RRS § 728; ]

== 7.40.120 - Injunction, who is bound by.
An order of injunction shall bind every person and officer restrained from the time he or she is informed thereof.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20198[2011 c 336 § 198]; Code 1881 § 163; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2033%20§%20163[1877 p 33 § 163]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2040%20§%20161[1869 p 40 § 161]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20153%20§%20121[1854 p 153 § 121]; RRS § 729; ]

== 7.40.130 - When adverse party becomes bound.
When notice of the application for an injunction has been served upon the adverse party, it shall not be necessary to serve the order upon him or her, but he or she shall be bound by the injunction as soon as the bond required of the plaintiff is executed and delivered to the proper officer.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20199[2011 c 336 § 199]; Code 1881 § 164; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2034%20§%20164[1877 p 34 § 164]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2040%20§%20162[1869 p 40 § 162]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20154%20§%20122[1854 p 154 § 122]; RRS § 730; ]

== 7.40.140 - Disposition of money collected on enjoined judgment.
Money collected upon a judgment afterward enjoined, remaining in the hands of the collecting officer, shall be paid to the clerk of the court granting the injunction, subject to the order of the court.

[ Code 1881 § 165; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2034%20§%20165[1877 p 34 § 165]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2040%20§%20163[1869 p 40 § 163]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20154%20§%20123[1854 p 154 § 123]; RRS § 731; ]

== 7.40.150 - Contempt for disobedience.
Whenever it shall appear to any court granting a restraining order or an order of injunction, or by affidavit, that any person has willfully disobeyed the order after notice thereof, such court shall award an attachment for contempt against the party charged, or an order to show cause why it should not issue. The attachment or order shall be issued by the clerk of the court, and directed to the sheriff, and shall be served by him or her.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20200[2011 c 336 § 200]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c9.pdf?cite=1957%20c%209%20§%2012[1957 c 9 § 12]; Code 1881 § 166; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2034%20§%20166[1877 p 34 § 166]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2040%20§%20164[1869 p 40 § 164]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20154%20§%20124[1854 p 154 § 124]; RRS § 732; ]

== 7.40.160 - Attachment and arrest—Indemnity of plaintiff.
The attachment for contempt shall be immediately served, by arresting the party charged, and bringing him or her into court, if in session, to be dealt with as in other cases of contempt; and the court shall also take all necessary measures to secure and indemnify the plaintiff against damages in the premises.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20201[2011 c 336 § 201]; Code 1881 § 167; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2034%20§%20167[1877 p 34 § 167]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2040%20§%20165[1869 p 40 § 165]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20154%20§%20125[1854 p 154 § 125]; RRS § 733; ]

== 7.40.170 - Bond for appearance.
If the court is not in session the officer making the arrest shall cause the person to enter into a bond, with surety, to be approved by the officer, conditioned that he or she personally appear in open court whenever his or her appearance shall be required, to answer such contempt, and that he or she will pay to the plaintiff all his or her damages and costs occasioned by the breach of the order; and in default thereof he or she shall be committed to the jail of the county until he or she shall enter into such bond with surety, or be otherwise legally discharged.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20202[2011 c 336 § 202]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c56.pdf?cite=1891%20c%2056%20§%201[1891 c 56 § 1]; Code 1881 § 168; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2034%20§%20168[1877 p 34 § 168]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2040%20§%20166[1869 p 40 § 166]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20154%20§%20126[1854 p 154 § 126]; RRS § 734; ]

== 7.40.180 - Motion to dissolve or modify.
Motions to dissolve or modify injunctions may be made in open court, or before a judge of the superior court, at any time after reasonable notice to the adverse party.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c36.pdf?cite=1891%20c%2036%20§%201[1891 c 36 § 1]; Code 1881 § 169; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2034%20§%20169[1877 p 34 § 169]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2040%20§%20167[1869 p 40 § 167]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20154%20§%20127[1854 p 154 § 127]; RRS § 735; ]

== 7.40.190 - Damages on dissolution of injunction to stay judgment.
When an injunction to stay proceedings after judgment for debt or damages shall be dissolved, the court shall award such damages not exceeding ten percent on the judgment, as the court may deem right, against the party in whose favor the injunction issued.

[ Code 1881 § 170; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2034%20§%20170[1877 p 34 § 170]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2041%20§%20168[1869 p 41 § 168]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20154%20§%20128[1854 p 154 § 128]; RRS § 736; ]

== 7.40.200 - Damages for rents and waste.
If an injunction to stay proceedings after verdict or judgment in an action for the recovery of real estate, or the possession thereof, be dissolved, the damages assessed against the party obtaining the injunction, shall include the reasonable rents and profits of the lands recovered, and all waste committed after granting injunction.

[ Code 1881 § 171; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2035%20§%20171[1877 p 35 § 171]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2041%20§%20169[1869 p 41 § 169]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20154%20§%20129[1854 p 154 § 129]; RRS § 737; ]

== 7.40.210 - Motion to reinstate.
Upon an order being made dissolving or modifying an order of injunction, the plaintiff may move the court to reinstate the order, and the court may, in its discretion, allow the motion, and appoint a time for hearing the same before the court, or a time and place for hearing before some judge thereof, and upon the hearing, the parties may produce such additional affidavits or depositions as the court shall direct, and the order of injunction shall be dissolved, modified, or reinstated, as the court or judge may deem right. Until the hearing of the motion to reinstate the order of injunction, the order to dissolve or modify it, shall be suspended.

[ Code 1881 § 172; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2035%20§%20172[1877 p 35 § 172]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2041%20§%20170[1869 p 41 § 170]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20154%20§%20130[1854 p 154 § 130]; RRS § 738; ]

== 7.40.230 - Injunctions—Fraud in obtaining telecommunications service.
. Whenever it appears that any person is engaged in or about to engage in any act that constitutes or will constitute a violation of RCW 9.26A.110, 9.26A.115, or 9.26A.090, the prosecuting attorney, a telecommunications company, or any person harmed by an alleged violation of RCW 9.26A.110, 9.26A.115, or 9.26A.090 may initiate a civil proceeding in superior court to enjoin such violation, and may petition the court to issue an order for the discontinuance of the specific telephone service being used in violation of RCW 9.26A.110, 9.26A.115, or 9.26A.090.

. An action under this section shall be brought in the county in which the unlawful act or acts are alleged to have taken place, and shall be commenced by the filing of a verified complaint, or shall be accompanied by an affidavit.

. If it is shown to the satisfaction of the court, either by verified complaint or affidavit, that a person is engaged in or about to engage in any act that constitutes a violation of RCW 9.26A.110, 9.26A.115, or 9.26A.090, the court may issue a temporary restraining order to abate and prevent the continuance or recurrence of the act. The court may direct the sheriff to seize and retain until further order of the court any device that is being used in violation of RCW 9.26A.110, 9.26A.115, or 9.26A.090. All property seized pursuant to the order of the court shall remain in the custody of the court.

. The court may issue a permanent injunction to restrain, abate or prevent the continuance or recurrence of the violation of RCW 9.26A.110, 9.26A.115, or 9.26A.090. The court may grant declaratory relief, mandatory orders, or any other relief deemed necessary to accomplish the purposes of the injunction. The court may retain jurisdiction of the case for the purpose of enforcing its orders.

. If it is shown to the satisfaction of the court, either by verified complaint or affidavit, that a person is engaged in or is about to engage in any act that constitutes a violation of RCW 9.26A.110, 9.26A.115, or 9.26A.090, the court may issue an order which shall be promptly served upon the person in whose name the telecommunications device is listed, requiring the party, within a reasonable time, to be fixed by the court, from the time of service of the petition on the party, to show cause before the judge why telephone service should not promptly be discontinued. At the hearing the burden of proof shall be on the complainant.

. Upon a finding by the court that the telecommunications device is being used or has been used in violation of RCW 9.26A.110 or 9.26A.115, the court may issue an order requiring the telephone company which is rendering service over the device to disconnect such service. Upon receipt of such order, which shall be served upon an officer of the telephone company by the sheriff or deputy of the county in which the telecommunications device is installed, the telephone company shall proceed promptly to disconnect and remove such device and discontinue all telephone service until further order of the court, provided that the telephone company may do so without breach of the peace or trespass.

. The telecommunications company that petitions the court for the removal of any telecommunications device under this section shall be a necessary party to any proceeding or action arising out of or under RCW 9.26A.110 or 9.26A.115.

. No telephone company shall be liable for any damages, penalty, or forfeiture, whether civil or criminal, for any legal act performed in compliance with any order issued by the court.

. Property seized pursuant to the direction of the court that the court has determined to have been used in violation of RCW 9.26A.110 or 9.26A.115 shall be forfeited after notice and hearing. The court may remit or mitigate the forfeiture upon terms and conditions as the court deems reasonable if it finds that such forfeiture was incurred without gross negligence or without any intent of the petitioner to violate the law, or it finds the existence of such mitigating circumstances as to justify the remission or the mitigation of the forfeiture. In determining whether to remit or mitigate forfeiture, the court shall consider losses that may have been suffered by victims as the result of the use of the forfeited property.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%205[2003 c 53 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c11.pdf?cite=1990%20c%2011%20§%204[1990 c 11 § 4]; ]

