= 7.52 - Partition.
:toc:

== 7.52.010 - Persons entitled to bring action.
When several persons hold and are in possession of real property as tenants in common, in which one or more of them have an estate of inheritance, or for life or years, an action may be maintained by one or more of such persons, for a partition thereof, according to the respective rights of the persons interested therein, and for sale of such property, or a part of it, if it appear that a partition cannot be made without great prejudice to the owners.

[ Code 1881 § 552; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20117%20§%20557[1877 p 117 § 557]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20133%20§%20505[1869 p 133 § 505]; RRS § 838; ]

== 7.52.020 - Requisites of complaint.
The interest of all persons in the property shall be set forth in the complaint specifically and particularly as far as known to the plaintiff, and if one or more of the parties, or the share or quantity of interest of any of the parties be unknown to the plaintiff, or be uncertain or contingent, or the ownership of the inheritance depend upon an executory devise, or the remainder be a contingent remainder, so that such parties cannot be named, that fact shall be set forth in the complaint.

[ Code 1881 § 553; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20117%20§%20558[1877 p 117 § 558]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20133%20§%20506[1869 p 133 § 506]; RRS § 839; ]

== 7.52.030 - Lien creditors as parties defendant.
The plaintiff may, at his or her option, make creditors having a lien upon the property or any portion thereof, other than by a judgment or decree, defendants in the suit. When the lien is upon an undivided interest or estate of any of the parties, such lien, if a partition be made, is thenceforth a lien only on the share assigned to such party; but such share shall be first charged with its just proportion of the costs of the partition, in preference to such lien.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20221[2011 c 336 § 221]; Code 1881 § 554; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20117%20§%20559[1877 p 117 § 559]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20133%20§%20507[1869 p 133 § 507]; RRS § 840; ]

== 7.52.040 - Notice.
The notice shall be directed by name to all the tenants in common, who are known, and in the same manner to all lien creditors who are made parties to the suit, and generally to all persons unknown, having or claiming an interest or estate in the property.

[ Code 1881 § 555; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20117%20§%20560[1877 p 117 § 560]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20133%20§%20508[1869 p 133 § 508]; RRS § 841; ]

== 7.52.050 - Service by publication.
If a party, having a share or interest in, or lien upon the property, be unknown, or either of the known parties reside out of the state or cannot be found therein, and such fact be made to appear by affidavit, the notice may be served by publication, as in ordinary cases. When service is made by publication, the notice must contain a brief description of the property which is the subject of the suit.

[ Code 1881 § 556; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20117%20§%20561[1877 p 117 § 561]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20134%20§%20509[1869 p 134 § 509]; RRS § 842; ]

== 7.52.060 - Answer—Contents.
The defendant shall set forth in his or her answer, the nature, and extent of his or her interest in the property, and if he or she be a lien creditor, how such lien was created, the amount of the debt secured thereby and remaining due, and whether such debt is secured in any other way, and if so, the nature of such other security.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20222[2011 c 336 § 222]; Code 1881 § 557; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20118%20§%20562[1877 p 118 § 562]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20134%20§%20510[1869 p 134 § 510]; RRS § 843; ]

== 7.52.070 - Trial—Proof must be taken.
The rights of the several parties, plaintiffs as well as defendants, may be put in issue, tried and determined in such suit, and where a defendant fails to answer, or where a sale of the property is necessary, the title shall be ascertained by proof to the satisfaction of the court, before the decree for partition or sale is given.

[ Code 1881 § 558; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20118%20§%20563[1877 p 118 § 563]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20134%20§%20511[1869 p 134 § 511]; RRS § 844; ]

== 7.52.080 - Order of sale or partition.
If it be alleged in the complaint and established by evidence, or if it appear by the evidence without such allegation in the complaint, to the satisfaction of the court, that the property or any part of it, is so situated that partition cannot be made without great prejudice to the owners, the court may order a sale thereof, and for that purpose may appoint one or more referees. Otherwise, upon the requisite proofs being made, it shall decree a partition according to the respective rights of the parties as ascertained by the court, and appoint three referees, therefor, and shall designate the portion to remain undivided for the owners whose interests remain unknown or are not ascertained.

[ Code 1881 § 559; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20118%20§%20564[1877 p 118 § 564]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20134%20§%20512[1869 p 134 § 512]; RRS § 845; ]

== 7.52.090 - Partition, how made.
In making the partition, the referees shall divide the property, and allot the several portions thereof to the respective parties, quality and quantity relatively considered, according to the respective rights of the parties as determined by the court, designating the several portions by proper landmarks, and may employ a surveyor with the necessary assistants to aid them therein. The referees shall make a report of their proceedings, specifying therein the manner of executing their trust, describing the property divided and the shares allotted to each party, with a particular description of each share.

[ Code 1881 § 560; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20118%20§%20565[1877 p 118 § 565]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20134%20§%20513[1869 p 134 § 513]; RRS § 846; ]

== 7.52.100 - Report of referees, confirmation—Effect.
The court may confirm or set aside the report in whole or in part, and if necessary, appoint new referees. Upon the report being confirmed a decree shall be entered that such partition be effectual forever, which decree shall be binding and conclusive:

. On all parties named therein, and their legal representatives who have at the time any interest in the property divided, or any part thereof as owners in fee, or as tenants for life or for years, or as entitled to the reversion, remainder or inheritance of such property or any part thereof, after the termination of a particular estate therein, or who by any contingency may be entitled to a beneficial interest in the property, or who have an interest in any undivided share thereof, as tenants for years or for life.

. On all persons interested in the property to whom notice shall have been given by publication.

. On all other persons claiming from or through such parties or persons or either of them.

[ Code 1881 § 561; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20118%20§%20566[1877 p 118 § 566]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20135%20§%20514[1869 p 135 § 514]; RRS § 847; ]

== 7.52.110 - Decree does not affect tenant.
Such decree and partition shall not affect any tenants for years or for life, of the whole of the property which is the subject of partition, nor shall such decree and partition preclude any persons, except such as are specified in RCW 7.52.100, from claiming title to the property in question, or from controverting the title of the parties between whom the partition shall have been made.

[ Code 1881 § 562; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20119%20§%20567[1877 p 119 § 567]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20135%20§%20515[1869 p 135 § 515]; RRS § 848; ]

== 7.52.120 - Costs.
The expenses of the referees, including those of a surveyor and his or her assistants, when employed, shall be ascertained and allowed by the court, and the amount thereof, together with the fees allowed by law to the referees, shall be paid by the plaintiff and may be allowed as costs.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20223[2011 c 336 § 223]; Code 1881 § 563; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20119%20§%20568[1877 p 119 § 568]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20135%20§%20516[1869 p 135 § 516]; RRS § 849; ]

== 7.52.130 - Sale of property.
If the referees report to the court that the property, of which partition shall have been decreed, or any separate portion thereof is so situated that a partition thereof cannot be made without great prejudice to the owners, and the court is satisfied that such report is correct, it may thereupon by an order direct the referees to sell the property or separate portion thereof.

[ Code 1881 § 564; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20119%20§%20569[1877 p 119 § 569]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20135%20§%20517[1869 p 135 § 517]; RRS § 850; ]

== 7.52.140 - Estate for life or years to be set off.
When a part of the property only is ordered to be sold, if there be an estate for life or years in an undivided share of the property, the whole of such estate may be set off in any part of the property not ordered sold.

[ Code 1881 § 565; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20119%20§%20570[1877 p 119 § 570]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20136%20§%20518[1869 p 136 § 518]; RRS § 851; ]

== 7.52.150 - Lien creditors to be brought in.
Before making an order of sale, if lien creditors, other than those by judgment or decree, have not been made parties, the court, on motion of either party, shall order the plaintiff to file a supplemental complaint, making such creditors defendants.

[ Code 1881 § 566; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20119%20§%20571[1877 p 119 § 571]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20136%20§%20519[1869 p 136 § 519]; RRS § 852; ]

== 7.52.160 - Clerk's certificate of unsatisfied judgment liens.
If an order of sale be made before the distribution of the proceeds thereof, the plaintiff shall produce to the court the certificate of the clerk of the county where the property is situated, showing the liens remaining unsatisfied, if any, by judgment or decree upon the property or any portion thereof, and unless he or she do so the court shall order a referee to ascertain them.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20224[2011 c 336 § 224]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c51.pdf?cite=1957%20c%2051%20§%2013[1957 c 51 § 13]; Code 1881 § 567; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20119%20§%20570[1877 p 119 § 570]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20136%20§%20520[1869 p 136 § 520]; RRS § 853; ]

== 7.52.170 - Ascertainment of liens—Priority.
If it appear by such certificate or reference, in case the certificate is not produced, that any such liens exist, the court shall appoint a referee to ascertain what amount remains due thereon or secured thereby respectively, and the order of priority in which they are entitled to be paid out of the property.

[ Code 1881 § 568; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20119%20§%20571[1877 p 119 § 571]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20136%20§%20521[1869 p 136 § 521]; RRS § 854; ]

== 7.52.180 - Notice to lienholders.
The plaintiff must cause a notice to be served at least twenty days before the time for appearance on each person having such lien by judgment or decree, to appear before the referee at a specified time and place to make proof by his or her own affidavit or otherwise, of the true amount due or to become due, contingently or absolutely on his or her judgment or decree.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20225[2011 c 336 § 225]; Code 1881 § 569; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20120%20§%20572[1877 p 120 § 572]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20136%20§%20522[1869 p 136 § 522]; RRS § 855; ]

== 7.52.190 - Proceedings and report of referee.
The referee shall receive the evidence and report the names of the creditors whose liens are established, the amounts due thereon, or secured thereby, and their priority respectively, and whether contingent or absolute. He or she shall attach to his or her report the proof of service of the notices and the evidence before him or her.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20226[2011 c 336 § 226]; Code 1881 § 570; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20120%20§%20573[1877 p 120 § 573]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20136%20§%20523[1869 p 136 § 523]; RRS § 856; ]

== 7.52.200 - Exceptions to report—Service of notice on absentee.
The report of the referee may be excepted to by either party to the suit, or to the proceedings before the referee, in like manner and with like effect as in ordinary cases. If a lien creditor be absent from the state, or his or her residence therein be unknown, and that fact appear by affidavit, the court or judge thereof may by order direct that service of the notice may be made upon his or her agent or attorney of record, or by publication thereof, for such time and in such manner as the order may prescribe.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20227[2011 c 336 § 227]; Code 1881 § 571; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20120%20§%20574[1877 p 120 § 574]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20137%20§%20524[1869 p 137 § 524]; RRS § 857; ]

== 7.52.210 - Order of confirmation is conclusive.
If the report of the referee be confirmed, the order of confirmation is binding and conclusive upon all parties to the suit, and upon the lien creditors who have been duly served with the notice to appear before the referee, as provided in RCW 7.52.180.

[ Code 1881 § 572; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20120%20§%20575[1877 p 120 § 575]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20137%20§%20525[1869 p 137 § 525]; RRS § 858; ]

== 7.52.220 - Distribution of proceeds of sale.
The proceeds of the sale of the encumbered property shall be distributed by the decree of the court, as follows:

. To pay its just proportion of the general costs of the suit.

. To pay the costs of the reference.

. To satisfy the several liens in their order of priority, by payment of the sums due, and to become due, according to the decree.

. The residue among the owners of the property sold, according to their respective shares.

[ Code 1881 § 573; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20120%20§%20576[1877 p 120 § 576]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20137%20§%20526[1869 p 137 § 526]; RRS § 859; ]

== 7.52.230 - Other securities to be first exhausted.
Whenever any party to the suit, who holds a lien upon the property or any part thereof, has other securities for the payment of the amount of such lien, the court may in its discretion, order such sureties to be exhausted before a distribution of the proceeds of sale, or may order a just deduction to be made from the amount of the lien on the property on account thereof.

[ Code 1881 § 574; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20121%20§%20577[1877 p 121 § 577]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20137%20§%20527[1869 p 137 § 527]; RRS § 860; ]

== 7.52.240 - Lien proceedings not to delay sale.
The proceedings to ascertain the amount of the liens, and to determine their priority as above provided, or those hereinafter authorized to determine the rights of parties to funds paid into court, shall not delay the sale, nor affect any other party, whose rights are not involved in such proceedings.

[ Code 1881 § 575; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20121%20§%20578[1877 p 121 § 578]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20137%20§%20528[1869 p 137 § 528]; RRS § 861; ]

== 7.52.250 - Distribution at direction of court.
The proceeds of sale, and the securities taken by the referees, or any part thereof, shall be distributed by them to the persons entitled thereto, whenever the court so directs. But if no such direction be given, all such proceeds and securities shall be paid into court, or deposited as directed by the court.

[ Code 1881 § 576; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20121%20§%20579[1877 p 121 § 579]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20138%20§%20529[1869 p 138 § 529]; RRS § 862; ]

== 7.52.260 - Continuance of suit to determine claims.
When the proceeds of sale of any shares or parcel belonging to persons who are parties to the suit and who are known, are paid into court, the suit may be continued as between such parties, for the determination of their respective claims thereto, which shall be ascertained and adjudged by the court. Further testimony may be taken in court, or by a referee at the discretion of the court, and the court may, if necessary, require such parties to present the facts or law in controversy, by pleadings as in an original suit.

[ Code 1881 § 577; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20121%20§%20580[1877 p 121 § 580]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20138%20§%20530[1869 p 138 § 530]; RRS § 863; ]

== 7.52.270 - Sales to be by public auction.
All sales of real property made by the referees shall be made by public auction, to the highest bidder, in the manner required for the sale of real property on execution. The notice shall state the terms of sale, and if the property, or any part of it is to be sold, subject to a prior estate, charge or lien, that shall be stated in the notice.

[ Code 1881 § 578; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20121%20§%20581[1877 p 121 § 581]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20138%20§%20531[1869 p 138 § 531]; RRS § 864; ]

== 7.52.280 - Terms of sale to be directed by court.
The court shall, in the order of sale, direct the terms of credit which may be allowed for the purchase money of any portion of the premises, of which it may direct a sale on credit; and for that portion of which the purchase money is required by the provisions hereinafter contained, to be invested for the benefit of unknown owners, infants or parties out of the state.

[ Code 1881 § 579; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20121%20§%20583[1877 p 121 § 583]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20138%20§%20532[1869 p 138 § 532]; RRS § 865; ]

== 7.52.290 - Referee may take security.
The referees may take separate mortgages, and other securities for the whole, or convenient portions of the purchase money, of such parts of the property as are directed by the court to be sold on credit, in the name of the clerk of the court, and his or her successors in office; and for the shares of any known owner of full age, in the name of such owner.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20228[2011 c 336 § 228]; Code 1881 § 580; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20121%20§%20584[1877 p 121 § 584]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20138%20§%20533[1869 p 138 § 533]; RRS § 866; ]

== 7.52.300 - Estate of tenant for life or years may be sold.
When the estate of any tenant for life or years, in any undivided part of the property in question, shall have been admitted by the parties, or ascertained by the court to be existing at the time of the order of sale, and the person entitled to such estate shall have been made a party to the suit, such estate may be first set off out of any part of the property, and a sale made of such parcel, subject to the prior unsold estate of such tenant therein; but if in the judgment of the court, a due regard to the interest of all the parties require that such estate be also sold, the sale may be so ordered.

[ Code 1881 § 581; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20122%20§%20585[1877 p 122 § 585]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20138%20§%20534[1869 p 138 § 534]; RRS § 867; ]

== 7.52.310 - Tenant for life or years may receive sum in gross—Consent.
Any person entitled to an estate for life or years in any undivided part of the property, whose estate shall have been sold, shall be entitled to receive such sum in gross as may be deemed a reasonable satisfaction for such estate, and which the person so entitled shall consent to accept instead thereof, by an instrument duly acknowledged and filed with the clerk.

[ Code 1881 § 582; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20122%20§%20586[1877 p 122 § 586]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20139%20§%20535[1869 p 139 § 535]; RRS § 868; ]

== 7.52.320 - Court to determine sum if consent not given.
If such consent be not given, as provided in RCW 7.52.310, before the report of sale, the court shall ascertain and determine what proportion of the proceeds of the sale, after deducting expenses, will be a just and reasonable sum to be invested for the benefit of the person entitled to such estate for life, or years, and shall order the same to be deposited in court for that purpose.

[ Code 1881 § 583; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20122%20§%20587[1877 p 122 § 587]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20139%20§%20536[1869 p 139 § 536]; RRS § 869; ]

== 7.52.330 - Protection of unknown tenant.
If the persons entitled to such estate, for life or years, be unknown, the court shall provide for the protection of their rights in the same manner, as far as may be, as if they were known and had appeared.

[ Code 1881 § 584; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20122%20§%20589[1877 p 122 § 589]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20139%20§%20538[1869 p 139 § 538]; RRS § 870; ]

== 7.52.340 - Contingent or vested estates.
In all cases of sales in partition, when it appears that any person has a vested or contingent future right or estate therein, the court shall ascertain and settle the proportionate value of such contingent or vested right or estate, and shall direct such proportion of the proceeds of sale to be invested, secured or paid over in such manner as to protect the rights and interests of the parties.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c51.pdf?cite=1957%20c%2051%20§%2014[1957 c 51 § 14]; Code 1881 § 585; RRS § 871. Cf. Laws 1881 § 586; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20122%20§%20590[1877 p 122 § 590]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20140%20§%20539[1869 p 140 § 539]; ]

== 7.52.350 - Terms of sale must be made known.
In all cases of sales of property the terms shall be made known at the time, and if the premises consist of distinct farms or lots, they shall be sold separately or otherwise, if the court so directs.

[ Code 1881 § 586; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20122%20§%20591[1877 p 122 § 591]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20140%20§%20540[1869 p 140 § 540]; RRS § 872; ]

== 7.52.360 - Referees or guardians not to be interested in purchase.
Neither of the referees, nor any person for the benefit of either of them, shall be interested in any purchase, nor shall the guardian of an infant be an interested party in the purchase of any real property being the subject of the suit, except for the benefit of the infant. All sales contrary to the provisions of this section shall be void.

[ Code 1881 § 587; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20122%20§%20592[1877 p 122 § 592]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20140%20§%20541[1869 p 140 § 541]; RRS § 873; ]

== 7.52.370 - Referees' report of sale—Contents.
After completing the sale, the referees shall report the same to the court, with a description of the different parcels of land sold to each purchaser, the name of the purchaser, the price paid or secured, the terms and conditions of the sale, and the securities, if any, taken. The report shall be filed with the clerk.

[ Code 1881 § 588; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20122%20§%20593[1877 p 122 § 593]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20140%20§%20542[1869 p 140 § 542]; RRS § 874; ]

== 7.52.380 - Exceptions—Confirmation.
The report of sale may be excepted to in writing by any party entitled to a share of the proceeds. If the sale be confirmed, the order of confirmation shall direct the referees to execute conveyances and take securities pursuant to such sale.

[ Code 1881 § 589; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20123%20§%20594[1877 p 123 § 594]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20140%20§%20543[1869 p 140 § 543]; RRS § 875; ]

== 7.52.390 - Purchase by interested party.
When a party entitled to a share of the property, or an encumbrancer entitled to have his or her lien paid out of the sale, becomes a purchaser, the referees may take his or her receipt for so much of the proceeds of the sale as belong to him or her.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20229[2011 c 336 § 229]; Code 1881 § 590; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20123%20§%20595[1877 p 123 § 595]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20140%20§%20544[1869 p 140 § 544]; RRS § 876; ]

== 7.52.400 - Investment of proceeds of unknown owner.
When there are proceeds of sale belonging to an unknown owner, or to a person without the state who has no legal representative within it, or when there are proceeds arising from the sale of an estate subject to the prior estate of a tenant for life or years, which are paid into the court or otherwise deposited by order of the court, the same shall be invested in securities on interest for the benefit of the persons entitled thereto.

[ Code 1881 § 591; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20123%20§%20596[1877 p 123 § 596]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20140%20§%20545[1869 p 140 § 545]; RRS § 877; ]

== 7.52.410 - Investment in name of clerk.
When the security for the proceeds of sale is taken, or when an investment of any such proceeds is made, it shall be done, except as herein otherwise provided, in the name of the clerk of the court and his or her successors in office, who shall hold the same for the use and benefit of the parties interested, subject to the order of the court.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20230[2011 c 336 § 230]; Code 1881 § 592; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20123%20§%20597[1877 p 123 § 597]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20141%20§%20546[1869 p 141 § 546]; RRS § 878; ]

== 7.52.420 - Securities to parties entitled to share when proportions determined.
When security is taken by the referees on a sale, and the parties interested in such security by an instrument in writing under their hands, delivered to the referees, agree upon the share and proportions to which they are respectively entitled, or when shares and proportions have been previously adjudged by the court, such securities shall be taken in the names of and payable to the parties respectively entitled thereto, and shall be delivered to such parties upon their receipt therefor. Such agreement and receipt shall be returned and filed with the clerk.

[ Code 1881 § 593; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20123%20§%20598[1877 p 123 § 598]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20141%20§%20547[1869 p 141 § 547]; RRS § 879; ]

== 7.52.430 - Duties of clerk in making investments.
The clerk in whose name a security is taken, or by whom an investment is made, and his or her successors in office, shall receive the interest and principal as it becomes due, and apply and invest the same as the court may direct, and shall file in his or her office all securities taken and keep an account in a book provided and kept for that purpose in the clerk's office, free for inspection by all persons, of investments and moneys received by him or her thereon, and the disposition thereof.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20231[2011 c 336 § 231]; Code 1881 § 594; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20123%20§%20599[1877 p 123 § 599]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20141%20§%20548[1869 p 141 § 548]; RRS § 880; ]

== 7.52.440 - Unequal partition—Compensation adjudged.
When it appears that partition cannot be made equal between the parties according to their respective rights, without prejudice to the rights and interests of some of them, the court may adjudge compensation to be made by one party to another on account of the inequality of partition; but such compensation shall not be required to be made to others by owners unknown, nor by infants, unless in case of an infant it appear that he or she has personal property sufficient for that purpose, and that his or her interest will be promoted thereby.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20232[2011 c 336 § 232]; Code 1881 § 595; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20124%20§%20600[1877 p 124 § 600]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20141%20§%20549[1869 p 141 § 549]; RRS § 881; ]

== 7.52.450 - Infant's share of proceeds to guardian.
When the share of an infant is sold, the proceeds of the sale may be paid by the referees making the sale, to his or her general guardian, or the special guardian appointed for him or her in the suit, upon giving the security required by law, or directed by order of the court.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20233[2011 c 336 § 233]; Code 1881 § 596; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20124%20§%20601[1877 p 124 § 601]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20142%20§%20550[1869 p 142 § 550]; RRS § 882; ]

== 7.52.460 - Guardian or limited guardian of incompetent or disabled person may receive proceeds—Bond.
The guardian or limited guardian who may be entitled to the custody and management of the estate of an incompetent or disabled person adjudged incapable of conducting his or her own affairs, whose interest in real property shall have been sold, may receive in behalf of such person his or her share of the proceeds of such real property from the referees, on executing a bond with sufficient sureties, approved by the judge of the court, conditioned that he or she faithfully discharge the trust reposed in him or her, and will render a true and just account to the person entitled, or to his or her legal representative.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20234[2011 c 336 § 234]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c80.pdf?cite=1977%20ex.s.%20c%2080%20§%209[1977 ex.s. c 80 § 9]; Code 1881 § 597; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20124%20§%20602[1877 p 124 § 602]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20142%20§%20551[1869 p 142 § 551]; RRS § 883; ]

== 7.52.470 - Guardian or limited guardian may consent to partition.
The general guardian of an infant, and the guardian or limited guardian entitled to the custody and management of the estate of an incompetent or disabled person adjudged incapable of conducting his or her own affairs, who is interested in real estate held in common or in any other manner, so as to authorize his or her being made a party to an action for the partition thereof, may consent to a partition without suit and agree upon the share to be set off to such infant or other person entitled, and may execute a release in his or her behalf to the owners of the shares or parts to which they may respectively be entitled, and upon an order of the court.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20235[2011 c 336 § 235]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c80.pdf?cite=1977%20ex.s.%20c%2080%20§%2010[1977 ex.s. c 80 § 10]; Code 1881 § 598; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20124%20§%20603[1877 p 124 § 603]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20142%20§%20552[1869 p 142 § 552]; RRS § 884; ]

== 7.52.480 - Apportionment of costs.
The cost of partition, including fees of referees and other disbursements including reasonable attorney fees to be fixed by the court and in case the land is ordered sold, costs of an abstract of title, shall be paid by the parties respectively entitled to share in the lands divided, in proportion to their respective interests therein, and may be included and specified in the decree. In that case there shall be a lien on the several shares, and the decree may be enforced by execution against the parties separately. When, however, a litigation arises between some of the parties only, the court may require the expense of such litigation to be paid by the parties thereto, or any of them.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c9.pdf?cite=1923%20c%209%20§%201[1923 c 9 § 1]; Code 1881 § 599; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%20124%20§%20604[1877 p 124 § 604]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20142%20§%20553[1869 p 142 § 553]; RRS § 885; ]

