= 7.77 - Uniform collaborative law act.
:toc:

== 7.77.010 - Definitions.
In this chapter:

. "Collaborative law communication" means a statement, whether oral or in a record, or verbal or nonverbal, that:

.. Is made to conduct, participate in, continue, or reconvene a collaborative law process; and

.. Occurs after the parties sign a collaborative law participation agreement and before the collaborative law process is concluded.

. "Collaborative law participation agreement" means an agreement by persons to participate in a collaborative law process.

. "Collaborative law process" means a procedure intended to resolve a collaborative matter without intervention by a tribunal in which persons:

.. Sign a collaborative law participation agreement; and

.. Are represented by collaborative lawyers.

. "Collaborative lawyer" means a lawyer who represents a party in a collaborative law process.

. "Collaborative matter" means a dispute, transaction, claim, problem, or issue for resolution, including a dispute, claim, or issue in a proceeding, which is described in a collaborative law participation agreement.

. "Law firm" means:

.. Lawyers who practice law together in a partnership, professional corporation, sole proprietorship, limited liability company, or association; and

.. Lawyers employed in a legal services organization, or the legal department of a corporation or other organization, or the legal department of a government or governmental subdivision, agency, or instrumentality.

. "Nonparty participant" means a person, other than a party and the party's collaborative lawyer, that participates in a collaborative law process.

. "Party" means a person that signs a collaborative law participation agreement and whose consent is necessary to resolve a collaborative matter.

. "Person" means an individual, corporation, business trust, estate, trust, partnership, limited liability company, association, joint venture, public corporation, government or governmental subdivision, agency, or instrumentality, or any other legal or commercial entity.

. "Proceeding" means a judicial, administrative, arbitral, or other adjudicative process before a tribunal, including related prehearing and posthearing motions, conferences, and discovery.

. "Prospective party" means a person that discusses with a prospective collaborative lawyer the possibility of signing a collaborative law participation agreement.

. "Record" means information that is inscribed on a tangible medium or that is stored in an electronic or other medium and is retrievable in perceivable form.

. "Related to a collaborative matter" means involving the same parties, transaction or occurrence, nucleus of operative fact, dispute, claim, or issue as the collaborative matter.

. "Sign" means, with present intent to authenticate or adopt a record:

.. To execute or adopt a tangible symbol; or

.. To attach to or logically associate with the record an electronic symbol, sound, or process.

. "Tribunal" means a court, arbitrator, administrative agency, or other body acting in an adjudicative capacity which, after presentation of evidence or legal argument, has jurisdiction to render a decision affecting a party's interests in a matter.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1116-S.SL.pdf?cite=2013%20c%20119%20§%202[2013 c 119 § 2]; ]

== 7.77.020 - Applicability.
. This chapter applies to a collaborative law participation agreement that meets the requirements of RCW 7.77.030 signed on or after July 28, 2013.

. The use of collaborative law applies only to matters that would be resolved in civil court and may not be used to resolve matters in criminal cases.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1116-S.SL.pdf?cite=2013%20c%20119%20§%203[2013 c 119 § 3]; ]

== 7.77.030 - Collaborative law participation agreement—Requirements.
. A collaborative law participation agreement must:

.. Be in a record;

.. Be signed by the parties;

.. State the parties' intention to resolve a collaborative matter through a collaborative law process under this chapter;

.. Describe the nature and scope of the matter;

.. Identify the collaborative lawyer who represents each party in the process; and

.. Contain a statement by each collaborative lawyer confirming the lawyer's representation of a party in the collaborative law process.

. Parties may agree to include in a collaborative law participation agreement additional provisions not inconsistent with this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1116-S.SL.pdf?cite=2013%20c%20119%20§%204[2013 c 119 § 4]; ]

== 7.77.040 - Beginning and concluding collaborative law process.
. A collaborative law process begins when the parties sign a collaborative law participation agreement.

. A tribunal may not order a party to participate in a collaborative law process over that party's objection.

. A collaborative law process is concluded by a:

.. Resolution of a collaborative matter as evidenced by a signed record;

.. Resolution of a part of the collaborative matter, evidenced by a signed record, in which the parties agree that the remaining parts of the matter will not be resolved in the process; or

.. Termination of the process.

. A collaborative law process terminates:

.. When a party gives notice to other parties in a record that the process is ended; or

.. When a party:

... Begins a proceeding related to a collaborative matter without the agreement of all parties; or

... In a pending proceeding related to the matter:

(A) Initiates a pleading, motion, order to show cause, or request for a conference with the tribunal without the agreement of all parties as to the relief sought;

(B) Requests that the proceeding be put on the tribunal's active calendar; or

(C) Takes similar contested action requiring notice to be sent to the parties; or

.. Except as otherwise provided by subsection (7) of this section, when a party discharges a collaborative lawyer or a collaborative lawyer withdraws from further representation of a party.

. A party's collaborative lawyer shall give prompt notice to all other parties in a record of a discharge or withdrawal.

. A party may terminate a collaborative law process with or without cause.

. Notwithstanding the discharge or withdrawal of a collaborative lawyer, a collaborative law process continues, if not later than thirty days after the date that the notice of the discharge or withdrawal of a collaborative lawyer required by subsection (5) of this section is sent to the parties:

.. The unrepresented party engages a successor collaborative lawyer; and

.. In a signed record:

... The parties consent to continue the process by reaffirming the collaborative law participation agreement;

... The agreement is amended to identify the successor collaborative lawyer; and

... The successor collaborative lawyer confirms the lawyer's representation of a party in the collaborative law process.

. A collaborative law process does not conclude if, with the consent of the parties, a party requests a tribunal to approve a resolution of the collaborative matter or any part thereof as evidenced by a signed record.

. A collaborative law participation agreement may provide additional methods of concluding a collaborative law process.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1116-S.SL.pdf?cite=2013%20c%20119%20§%205[2013 c 119 § 5]; ]

== 7.77.050 - Proceedings pending before tribunal—Status report.
. Persons in a proceeding pending before a tribunal may sign a collaborative law participation agreement to seek to resolve a collaborative matter related to the proceeding. Parties shall file promptly with the tribunal a notice of the agreement after it is signed. Subject to subsection (3) of this section and RCW 7.77.060 and 7.77.070, the filing operates as an application for a stay of the proceeding.

. The parties shall file promptly with the tribunal notice in a record when a collaborative law process concludes. The stay of the proceeding under subsection (1) of this section is lifted when the notice is filed. The notice may not specify any reason for termination of the process.

. A tribunal in which a proceeding is stayed under subsection (1) of this section may require the parties and collaborative lawyers to provide a status report on the collaborative law process and the proceeding. A status report may include only information on whether the process is ongoing or concluded. It may not include a report, assessment, evaluation, recommendation, finding, or other communication regarding a collaborative law process or collaborative matter.

. A tribunal may not consider a communication made in violation of subsection (3) of this section.

. A tribunal shall provide parties notice and an opportunity to be heard before dismissing a proceeding in which a notice of collaborative law process is filed based on delay or failure to prosecute.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1116-S.SL.pdf?cite=2013%20c%20119%20§%206[2013 c 119 § 6]; ]

== 7.77.060 - Emergency order.
During a collaborative law process, a tribunal may issue emergency orders to protect the health, safety, welfare, or interest of a party or of a family or household member or intimate partner, as defined in RCW 26.50.010.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2473-S.SL.pdf?cite=2020%20c%2029%20§%201[2020 c 29 § 1]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1116-S.SL.pdf?cite=2013%20c%20119%20§%207[2013 c 119 § 7]; ]

== 7.77.070 - Approval of agreement by tribunal.
A tribunal may approve an agreement resulting from a collaborative law process.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1116-S.SL.pdf?cite=2013%20c%20119%20§%208[2013 c 119 § 8]; ]

== 7.77.080 - Disqualification of collaborative lawyer and lawyers in associated law firm.
. Except as otherwise provided in subsection (3) of this section, a collaborative lawyer is disqualified from appearing before a tribunal to represent a party in a proceeding related to the collaborative matter.

. Except as otherwise provided in subsection (3) of this section and RCW 7.77.090, a lawyer in a law firm with which the collaborative lawyer is associated is disqualified from appearing before a tribunal to represent a party in a proceeding related to the collaborative matter if the collaborative lawyer is disqualified from doing so under subsection (1) of this section.

. A collaborative lawyer or a lawyer in a law firm with which the collaborative lawyer is associated may represent a party:

.. To ask a tribunal to approve an agreement resulting from the collaborative law process; or

.. To seek or defend an emergency order to protect the health, safety, welfare, or interest of a party, or family or household member or intimate partner, as defined in RCW 26.50.010, if a successor lawyer is not immediately available to represent that person.

. If subsection (3)(b) of this section applies, a collaborative lawyer, or lawyer in a law firm with which the collaborative lawyer is associated, may represent a party or family or household member or intimate partner only until the person is represented by a successor lawyer or reasonable measures are taken to protect the health, safety, welfare, or interest of the person.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2473-S.SL.pdf?cite=2020%20c%2029%20§%202[2020 c 29 § 2]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1116-S.SL.pdf?cite=2013%20c%20119%20§%209[2013 c 119 § 9]; ]

== 7.77.090 - Governmental entity as party.
. The disqualification of RCW 7.77.080(1) applies to a collaborative lawyer representing a party that is a government or governmental subdivision, agency, or instrumentality.

. After a collaborative law process concludes, another lawyer in a law firm with which the collaborative lawyer is associated may represent a government or governmental subdivision, agency, or instrumentality in the collaborative matter or a matter related to the collaborative matter if:

.. The collaborative law participation agreement so provides; and

.. The collaborative lawyer is isolated from any participation in the collaborative matter or a matter related to the collaborative matter through procedures within the law firm which are reasonably calculated to isolate the collaborative lawyer from such participation.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1116-S.SL.pdf?cite=2013%20c%20119%20§%2010[2013 c 119 § 10]; ]

== 7.77.100 - Disclosure of information.
Except as provided by law other than this chapter, during the collaborative law process, on the request of another party, a party shall make timely, full, candid, and informal disclosure of information related to the collaborative matter without formal discovery. A party also shall update promptly previously disclosed information that has materially changed. The parties may define the scope of disclosure during the collaborative law process.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1116-S.SL.pdf?cite=2013%20c%20119%20§%2011[2013 c 119 § 11]; ]

== 7.77.110 - Standards of professional responsibility and mandatory reporting not affected.
. This chapter does not affect the professional responsibility obligations and standards applicable to a lawyer or other licensed professional or relieve a lawyer or other licensed professional from the duty to comply with all applicable professional responsibility obligations and standards.

. This chapter does not affect the obligation of a person to report abuse or neglect, abandonment, or exploitation of a child or adult under the law of this state.

. Noncompliance with an obligation or prohibition imposed by this chapter does not in itself establish grounds for professional discipline.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1116-S.SL.pdf?cite=2013%20c%20119%20§%2012[2013 c 119 § 12]; ]

== 7.77.120 - Appropriateness of collaborative law process.
Before a prospective party signs a collaborative law participation agreement, the prospective party must:

. Be advised as to whether a collaborative law process is appropriate for the prospective party's matter;

. Be provided with sufficient information to make an informed decision about the material benefits and risks of a collaborative law process as compared to the material benefits and risks of other reasonably available alternatives for resolving the proposed collaborative matter, such as litigation, mediation, arbitration, or expert evaluation;

. Be informed that after signing an agreement if a party initiates a proceeding or seeks tribunal intervention in a pending proceeding related to the collaborative matter, the collaborative law process terminates;

. Be informed that participation in a collaborative law process is voluntary and any party has the right to terminate unilaterally a collaborative law process with or without cause; and

. Be informed that the collaborative lawyer and any lawyer in a law firm with which the collaborative lawyer is associated may not appear before a tribunal to represent a party in a proceeding related to the collaborative matter, except as authorized by law or court rule.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1116-S.SL.pdf?cite=2013%20c%20119%20§%2013[2013 c 119 § 13]; ]

== 7.77.130 - Coercive or violent relationship among parties.
. Before a prospective party signs a collaborative law participation agreement, a prospective collaborative lawyer shall make reasonable inquiry whether the prospective party has a history of a coercive or violent relationship with another prospective party.

. Throughout a collaborative law process, a collaborative lawyer reasonably and continuously shall assess whether the party the collaborative lawyer represents has a history of a coercive or violent relationship with another party.

. If a collaborative lawyer reasonably believes that the party the lawyer represents or the prospective party who consults the lawyer has a history of a coercive or violent relationship with another party or prospective party, the lawyer may not begin or continue a collaborative law process unless:

.. The party or the prospective party requests beginning or continuing a process; and

.. The collaborative lawyer reasonably believes that the safety of the party or prospective party can be protected adequately during a process.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1116-S.SL.pdf?cite=2013%20c%20119%20§%2014[2013 c 119 § 14]; ]

== 7.77.140 - Confidentiality of collaborative law communication.
Subject to RCW 7.77.110, a collaborative law communication is confidential to the extent agreed by the parties in a signed record or as provided by law of this state other than this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1116-S.SL.pdf?cite=2013%20c%20119%20§%2015[2013 c 119 § 15]; ]

== 7.77.150 - Privilege against disclosure for collaborative law communication—Admissibility—Discovery.
. Subject to RCW 7.77.160 and 7.77.170, a collaborative law communication is privileged under subsection (2) of this section, is not subject to discovery, and is not admissible in evidence.

. In a proceeding, the following privileges apply:

.. A party may refuse to disclose, and may prevent any other person from disclosing, a collaborative law communication.

.. A nonparty participant may refuse to disclose, and may prevent any other person from disclosing, a collaborative law communication of the nonparty participant.

. Evidence or information that is otherwise admissible or subject to discovery does not become inadmissible or protected from discovery solely because of its disclosure or use in a collaborative law process.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1116-S.SL.pdf?cite=2013%20c%20119%20§%2016[2013 c 119 § 16]; ]

== 7.77.160 - Waiver and preclusion of privilege.
. A privilege under RCW 7.77.150 may be waived in a record or orally during a proceeding if it is expressly waived by all parties and, in the case of the privilege of a nonparty participant, it is also expressly waived by the nonparty participant.

. A person that makes a disclosure or representation about a collaborative law communication which prejudices another person in a proceeding may not assert a privilege under RCW 7.77.150, but this preclusion applies only to the extent necessary for the person prejudiced to respond to the disclosure or representation.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1116-S.SL.pdf?cite=2013%20c%20119%20§%2017[2013 c 119 § 17]; ]

== 7.77.170 - Limits of privilege.
. There is no privilege under RCW 7.77.150 for a collaborative law communication that is:

.. Available to the public under chapter 42.56 RCW or made during a session of a collaborative law process that is open, or is required by law to be open, to the public;

.. A threat or statement of a plan to inflict bodily injury or commit a crime of violence;

.. Intentionally used to plan a crime, commit or attempt to commit a crime, or conceal an ongoing crime or ongoing criminal activity; or

.. In an agreement resulting from the collaborative law process, evidenced by a record signed by all parties to the agreement.

. The privileges under RCW 7.77.150 for a collaborative law communication do not apply to the extent that a communication is:

.. Sought or offered to prove or disprove a claim or complaint of professional misconduct or malpractice arising from or related to a collaborative law process;

.. Sought or offered to prove or disprove abuse, neglect, abandonment, or exploitation of a child or adult, unless the child protective services agency or adult protective services agency is a party to or otherwise participates in the process; or

.. Sought or offered to prove or disprove stalking or cyberstalking of a party or child.

. There is no privilege under RCW 7.77.150 if a tribunal finds, after a hearing in camera, that the party seeking discovery or the proponent of the evidence has shown the evidence is not otherwise available, the need for the evidence substantially outweighs the interest in protecting confidentiality, and the collaborative law communication is sought or offered in:

.. A court proceeding involving a felony or misdemeanor; or

.. A proceeding seeking rescission or reformation of a contract arising out of the collaborative law process or in which a defense to avoid liability on the contract is asserted.

. If a collaborative law communication is subject to an exception under subsection (2) or (3) of this section, only the part of the communication necessary for the application of the exception may be disclosed or admitted.

. Disclosure or admission of evidence excepted from the privilege under subsection (2) or (3) of this section does not make the evidence or any other collaborative law communication discoverable or admissible for any other purpose.

. The privileges under RCW 7.77.150 do not apply if the parties agree in advance in a signed record, or if a record of a proceeding reflects agreement by the parties, that all or part of a collaborative law process is not privileged. This subsection does not apply to a collaborative law communication made by a person that did not receive actual notice of the agreement before the communication was made.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1116-S.SL.pdf?cite=2013%20c%20119%20§%2018[2013 c 119 § 18]; ]

== 7.77.180 - Authority of tribunal in case of noncompliance.
. If an agreement fails to meet the requirements of RCW 7.77.030, or a lawyer fails to comply with RCW 7.77.120 or 7.77.130, a tribunal may nonetheless find that the parties intended to enter into a collaborative law participation agreement if they:

.. Signed a record indicating an intention to enter into a collaborative law participation agreement; and

.. Reasonably believed they were participating in a collaborative law process.

. If a tribunal makes the findings specified in subsection (1) of this section, and the interests of justice require, the tribunal may:

.. Enforce an agreement evidenced by a record resulting from the process in which the parties participated;

.. Apply the disqualification provisions of RCW 7.77.040, 7.77.050, 7.77.080, and 7.77.090; and

.. Apply a privilege under RCW 7.77.150.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1116-S.SL.pdf?cite=2013%20c%20119%20§%2019[2013 c 119 § 19]; ]

== 7.77.900 - Short title.
This chapter may be known and cited as the "uniform collaborative law act."

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1116-S.SL.pdf?cite=2013%20c%20119%20§%201[2013 c 119 § 1]; ]

== 7.77.901 - Uniformity of application and construction.
In applying and construing this uniform act, consideration must be given to the need to promote uniformity of the law with respect to its subject matter among states that enact it.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1116-S.SL.pdf?cite=2013%20c%20119%20§%2020[2013 c 119 § 20]; ]

== 7.77.902 - Relation to electronic signatures in global and national commerce act.
This chapter modifies, limits, and supersedes the federal electronic signatures in global and national commerce act, 15 U.S.C. Sec. 7001, et seq., but does not modify, limit, or supersede section 101(c) of that act, 15 U.S.C. Sec. 7001(c), or authorize electronic delivery of any of the notices described in section 103(b) of that act, 15 U.S.C. Sec. 7003(b).

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1116-S.SL.pdf?cite=2013%20c%20119%20§%2021[2013 c 119 § 21]; ]

