= 7.80 - Civil infractions.
:toc:

== 7.80.005 - Legislative finding—1987 c 456.
The legislature finds that many minor offenses that are established as misdemeanors are obsolete or can be more appropriately punished by the imposition of civil fines. The legislature finds that some misdemeanors should be decriminalized to allow resources of the legal system, such as judges, prosecutors, juries, and jails, to be used to punish serious criminal behavior, since acts characterized as criminal behavior have a tremendous fiscal impact on the legal system.

The establishment of a system of civil infractions is a more expeditious and less expensive method of disposing of minor offenses and will decrease the cost and workload of the courts of limited jurisdiction.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c456.pdf?cite=1987%20c%20456%20§%206[1987 c 456 § 6]; ]

== 7.80.010 - Jurisdiction of courts.
. All violations of state law, local law, ordinance, regulation, or resolution designated as civil infractions may be heard and determined by a district court, except as otherwise provided in this section.

. Any municipal court has the authority to hear and determine pursuant to this chapter civil infractions that are established by municipal ordinance or by local law or resolution of a transit agency authorized to issue civil infractions, and that are committed within the jurisdiction of the municipality.

. Any city or town with a municipal court under chapter 3.50 RCW may contract with the county to have civil infractions that are established by city or town ordinance and that are committed within the city or town adjudicated by a district court.

. District court commissioners have the authority to hear and determine civil infractions pursuant to this chapter.

. Nothing in this chapter prevents any city, town, or county from hearing and determining civil infractions pursuant to its own system established by ordinance.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5513-S.SL.pdf?cite=2009%20c%20279%20§%202[2009 c 279 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c456.pdf?cite=1987%20c%20456%20§%209[1987 c 456 § 9]; ]

== 7.80.020 - Issuance of process.
Notwithstanding any other provision of law governing service of process in civil cases, a court of limited jurisdiction having jurisdiction over an alleged civil infraction may issue process anywhere within the state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c456.pdf?cite=1987%20c%20456%20§%2010[1987 c 456 § 10]; ]

== 7.80.030 - Training of judicial officers.
All judges and court commissioners adjudicating civil infractions shall complete such training requirements as are promulgated by the supreme court.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c456.pdf?cite=1987%20c%20456%20§%2011[1987 c 456 § 11]; ]

== 7.80.040 - "Enforcement officer" defined.
As used in this chapter, "enforcement officer" means a person authorized to enforce the provisions of the title or ordinance in which the civil infraction is established.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c456.pdf?cite=1987%20c%20456%20§%2012[1987 c 456 § 12]; ]

== 7.80.050 - Notice of infraction—Issuance, service, filing.
. A civil infraction proceeding is initiated by the issuance, service, and filing of a notice of civil infraction.

. A notice of civil infraction may be issued by an enforcement officer when the civil infraction occurs in the officer's presence.

. A court may issue a notice of civil infraction if an enforcement officer files with the court a written statement that the civil infraction was committed in the officer's presence or that the officer has reasonable cause to believe that a civil infraction was committed.

. Service of a notice of civil infraction issued under subsection (2) or (3) of this section shall be as provided by court rule. Until such a rule is adopted, service shall be as provided in *JTIR 2.2(c)(1) and (3), as applicable.

. A notice of infraction shall be filed with a court having jurisdiction within forty-eight hours of issuance, excluding Saturdays, Sundays, and holidays. A notice of infraction not filed within the time limits prescribed in this section may be dismissed without prejudice.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c456.pdf?cite=1987%20c%20456%20§%2013[1987 c 456 § 13]; ]

== 7.80.060 - Person receiving notice—Identification and detention.
A person who is to receive a notice of civil infraction under RCW 7.80.050 is required to identify himself or herself to the enforcement officer by giving his or her name, address, and date of birth. Upon the request of the officer, the person shall produce reasonable identification, including a driver's license or identicard.

A person who is unable or unwilling to reasonably identify himself or herself to an enforcement officer may be detained for a period of time not longer than is reasonably necessary to identify the person for purposes of issuing a civil infraction.

Each agency authorized to issue civil infractions shall adopt rules on identification and detention of persons committing civil infractions.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c456.pdf?cite=1987%20c%20456%20§%2014[1987 c 456 § 14]; ]

== 7.80.070 - Notice—Determination final unless contested—Form.
. A notice of civil infraction represents a determination that a civil infraction has been committed. The determination is final unless contested as provided in this chapter.

. The form for the notice of civil infraction shall be prescribed by rule of the supreme court and shall include the following:

.. A statement that the notice represents a determination that a civil infraction has been committed by the person named in the notice and that the determination is final unless contested as provided in this chapter;

.. A statement that a civil infraction is a noncriminal offense for which imprisonment may not be imposed as a sanction;

.. A statement of the specific civil infraction for which the notice was issued;

.. A statement of the monetary penalty established for the civil infraction;

.. A statement of the options provided in this chapter for responding to the notice and the procedures necessary to exercise these options;

.. A statement that at any hearing to contest the determination the state has the burden of proving, by a preponderance of the evidence, that the civil infraction was committed and that the person may subpoena witnesses including the enforcement officer who issued the notice of civil infraction;

.. A statement that at any hearing requested for the purpose of explaining mitigating circumstances surrounding the commission of the civil infraction, the person will be deemed to have committed the civil infraction and may not subpoena witnesses;

.. A statement that the person must respond to the notice as provided in this chapter within fifteen days;

.. A statement that failure to respond to the notice or a failure to appear at a hearing requested for the purpose of contesting the determination or for the purpose of explaining mitigating circumstances will result in a default judgment against the person in the amount of the penalty and that this failure may be referred to the prosecuting attorney for criminal prosecution for failure to respond or appear;

.. A statement that failure to respond to a notice of civil infraction or to appear at a requested hearing is a misdemeanor and may be punished by a fine or imprisonment in jail.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1650-S.SL.pdf?cite=2006%20c%20270%20§%205[2006 c 270 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c456.pdf?cite=1987%20c%20456%20§%2015[1987 c 456 § 15]; ]

== 7.80.080 - Response to notice—Contesting determination—Mitigating circumstances—Hearing—Failure to respond or appear.
. Any person who receives a notice of civil infraction shall respond to such notice as provided in this section within fifteen days of the date of the notice.

. If the person determined to have committed the civil infraction does not contest the determination, the person shall respond by completing the appropriate portion of the notice of civil infraction and submitting it, either by mail or in person, to the court specified on the notice. A check or money order in the amount of the penalty prescribed for the civil infraction must be submitted with the response. The clerk of a court may accept cash in payment for an infraction. When a response which does not contest the determination is received, an appropriate order shall be entered in the court's records.

. If the person determined to have committed the civil infraction wishes to contest the determination, the person shall respond by completing the portion of the notice of civil infraction requesting a hearing and submitting it, either by mail or in person, to the court specified on the notice. The court shall notify the person in writing of the time, place, and date of the hearing, and that date shall not be earlier than seven days nor more than ninety days from the date of the notice of hearing, except by agreement.

. If the person determined to have committed the civil infraction does not contest the determination but wishes to explain mitigating circumstances surrounding the infraction, the person shall respond by completing the portion of the notice of civil infraction requesting a hearing for that purpose and submitting it, either by mail or in person, to the court specified on the notice. The court shall notify the person in writing of the time, place, and date of the hearing, and that date shall not be earlier than seven days nor more than ninety days from the date of the notice of hearing, except by agreement.

. The court shall enter a default judgment assessing the monetary penalty prescribed for the civil infraction and may notify the prosecuting attorney of the failure to respond to the notice of civil infraction or to appear at a requested hearing if any person issued a notice of civil infraction:

.. Fails to respond to the notice of civil infraction as provided in subsection (2) of this section; or

.. Fails to appear at a hearing requested pursuant to subsection (3) or (4) of this section.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c456.pdf?cite=1987%20c%20456%20§%2016[1987 c 456 § 16]; ]

== 7.80.090 - Hearings—Rules of procedure—Counsel.
. Procedures for the conduct of all hearings provided in this chapter may be established by rule of the supreme court.

. Any person subject to proceedings under this chapter may be represented by counsel.

. The attorney representing the state, county, city, town, or transit agency authorized to issue civil infractions may appear in any proceedings under this chapter but need not appear, notwithstanding any statute or rule of court to the contrary.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5513-S.SL.pdf?cite=2009%20c%20279%20§%201[2009 c 279 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c456.pdf?cite=1987%20c%20456%20§%2017[1987 c 456 § 17]; ]

== 7.80.100 - Hearings—Contesting determination that infraction committed—Appeal.
. A hearing held for the purpose of contesting the determination that a civil infraction has been committed shall be without a jury and shall be recorded in the manner provided for in courts of limited jurisdiction.

. The court may consider the notice of civil infraction and any other written report made under oath submitted by the enforcement officer who issued the notice or whose written statement was the basis for the issuance of the notice in lieu of the officer's personal appearance at the hearing. The person named in the notice may request the court for issuance of subpoena of witnesses, including the enforcement officer who issued the notice, and has the right to present evidence and examine witnesses present in court.

. The burden of proof is upon the state to establish the commission of the civil infraction by a preponderance of the evidence.

. After consideration of the evidence and argument, the court shall determine whether the civil infraction was committed. Where it has not been established that the civil infraction was committed, an order dismissing the notice shall be entered in the court's records. Where it has been established that the civil infraction was committed, an appropriate order shall be entered in the court's records.

. An appeal from the court's determination or order shall be to the superior court in the manner provided by the Rules for Appeal of Decisions of Courts of Limited Jurisdiction. The decision of the superior court is subject only to discretionary review pursuant to the Rules of Appellate Procedure.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c456.pdf?cite=1987%20c%20456%20§%2018[1987 c 456 § 18]; ]

== 7.80.110 - Hearings—Explanation of mitigating circumstances.
. A hearing held for the purpose of allowing a person to explain mitigating circumstances surrounding the commission of a civil infraction shall be an informal proceeding. The person may not subpoena witnesses. The determination that a civil infraction has been committed may not be contested at a hearing held for the purpose of explaining mitigating circumstances.

. After the court has heard the explanation of the circumstances surrounding the commission of the civil infraction, an appropriate order shall be entered in the court's records.

. There is no appeal from the court's determination or order.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c456.pdf?cite=1987%20c%20456%20§%2019[1987 c 456 § 19]; ]

== 7.80.120 - Monetary penalties—Restitution.
. A person found to have committed a civil infraction shall be assessed a monetary penalty.

.. The maximum penalty and the default amount for a class 1 civil infraction shall be two hundred fifty dollars, not including statutory assessments, except for an infraction of state law involving (i) potentially dangerous litter as specified in RCW 70A.200.060(4) or violent video or computer games under RCW 9.91.180, in which case the maximum penalty and default amount is five hundred dollars; or (ii) a person's refusal to submit to a test or tests pursuant to RCW 79A.60.040 and 79A.60.700, in which case the maximum penalty and default amount is one thousand dollars; or (iii) the misrepresentation of service animals under RCW 49.60.214, in which case the maximum penalty and default amount is five hundred dollars;

.. The maximum penalty and the default amount for a class 2 civil infraction shall be one hundred twenty-five dollars, not including statutory assessments;

.. The maximum penalty and the default amount for a class 3 civil infraction shall be fifty dollars, not including statutory assessments; and

.. The maximum penalty and the default amount for a class 4 civil infraction shall be twenty-five dollars, not including statutory assessments.

. The supreme court shall prescribe by rule the conditions under which local courts may exercise discretion in assessing fines for civil infractions.

. Whenever a monetary penalty is imposed by a court under this chapter it is immediately payable. If the person is unable to pay at that time the court may grant an extension of the period in which the penalty may be paid. If the penalty is not paid on or before the time established for payment, the court may proceed to collect the penalty in the same manner as other civil judgments and may notify the prosecuting authority of the failure to pay.

. The court may also order a person found to have committed a civil infraction to make restitution.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1192.SL.pdf?cite=2021%20c%2065%20§%208[2021 c 65 § 8]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2822-S.SL.pdf?cite=2018%20c%20176%20§%205[2018 c 176 § 5]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5437-S.SL.pdf?cite=2013%20c%20278%20§%203[2013 c 278 § 3]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1009-S.SL.pdf?cite=2003%20c%20365%20§%203[2003 c 365 § 3]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1409-S.SL.pdf?cite=2003%20c%20337%20§%204[2003 c 337 § 4]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1429-S.SL.pdf?cite=1997%20c%20159%20§%202[1997 c 159 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c456.pdf?cite=1987%20c%20456%20§%2020[1987 c 456 § 20]; ]

== 7.80.130 - Order of court—Civil nature—Modification of penalty—Community restitution.
. An order entered after the receipt of a response which does not contest the determination, or after it has been established at a hearing that the civil infraction was committed, or after a hearing for the purpose of explaining mitigating circumstances is civil in nature.

. The court may waive, reduce, or suspend the monetary penalty prescribed for the civil infraction. If the court determines that a person has insufficient funds to pay the monetary penalty, the court may order performance of a number of hours of community restitution in lieu of a monetary penalty, at the rate of the then state minimum wage per hour.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6627.SL.pdf?cite=2002%20c%20175%20§%201[2002 c 175 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c456.pdf?cite=1987%20c%20456%20§%2021[1987 c 456 § 21]; ]

== 7.80.140 - Costs and attorney fees.
Each party to a civil infraction case is responsible for costs incurred by that party, but the court may assess witness fees against a nonprevailing respondent. Attorney fees may be awarded to either party in a civil infraction case.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c456.pdf?cite=1987%20c%20456%20§%2022[1987 c 456 § 22]; ]

== 7.80.150 - Notices—Record of—Cancellation prohibited, penalty—Audit.
. Every law enforcement agency in this state or other agency authorized to issue notices of civil infractions shall provide in appropriate form notices of civil infractions which shall be issued in books with notices in quadruplicate and meeting the requirements of this section, or issued by an electronic device capable of producing a printed copy and electronic copies of the citations.

The chief administrative officer of every such agency shall be responsible for the issuance of such books or electronic devices and shall maintain a record of every such book or electronic device and each notice contained therein issued to individual members or employees of the agency and shall require and retain a receipt for every book or electronic device so issued.

. Every law enforcement officer or other person upon issuing a notice of civil infraction to an alleged perpetrator of a civil infraction under the laws of this state or of any ordinance of any city or town shall deposit the original or a printed or electronic copy of such notice of civil infraction with a court having competent jurisdiction over the civil infraction, as provided in RCW 7.80.050.

Upon the deposit of the original or a printed or electronic copy of such notice of civil infraction with a court having competent jurisdiction over the civil infraction, the original or copy may be disposed of only as provided in this chapter.

. It is unlawful and is official misconduct for any law enforcement officer or other officer or public employee to dispose of a notice of civil infraction or copies thereof or of the record of the issuance of the same in a manner other than as required in this section.

. The chief administrative officer of every law enforcement agency or other agency authorized to issue notices of civil infractions shall require the return to him or her of a copy of every notice issued by a person under his or her supervision to an alleged perpetrator of a civil infraction under any law or ordinance and of all copies of every notice which has been spoiled or upon which any entry has been made and not issued to an alleged perpetrator.

Such chief administrative officer shall also maintain or cause to be maintained in connection with every notice issued by a person under his or her supervision a record of the disposition of the charge by the court in which the original or copy of the notice was deposited.

. Any person who cancels or solicits the cancellation of any notice of civil infraction, in any manner other than as provided in this section, is guilty of a misdemeanor.

. Every record of notices required in this section shall be audited monthly by the appropriate fiscal officer of the government agency to which the law enforcement agency or other agency authorized to issue notices of civil infractions is responsible.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2583.SL.pdf?cite=2004%20c%2043%20§%201[2004 c 43 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c456.pdf?cite=1987%20c%20456%20§%2023[1987 c 456 § 23]; ]

== 7.80.160 - Failure to exercise notice options—Failure to satisfy penalty.
. Any person who, after receiving a statement of the options provided in this chapter for responding to the notice of civil infraction and the procedures necessary to exercise these options, fails to exercise one of the options in a timely manner is guilty of a misdemeanor regardless of the disposition of the notice of civil infraction. A notice of civil infraction may be complied with by an appearance by counsel.

. A person who willfully fails to pay a monetary penalty or to perform community restitution as required by a court under this chapter may be found in contempt of court as provided in chapter 7.21 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1650-S.SL.pdf?cite=2006%20c%20270%20§%206[2006 c 270 § 6]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6627.SL.pdf?cite=2002%20c%20175%20§%202[2002 c 175 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c373.pdf?cite=1989%20c%20373%20§%2012[1989 c 373 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c456.pdf?cite=1987%20c%20456%20§%2024[1987 c 456 § 24]; ]

== 7.80.900 - Decriminalization of certain municipal ordinances.
Any municipal criminal ordinance in existence on the January 1, 1989, which is the same as or substantially similar to a statute which is decriminalized by sections 25 through 30 and 32, chapter 456, Laws of 1987 is deemed to be civil in nature and shall be punished as provided in this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c456.pdf?cite=1987%20c%20456%20§%2031[1987 c 456 § 31]; ]

== 7.80.901 - Effective date—1987 c 456 §§ 9-31.
Sections 9 through 31 of this act shall take effect January 1, 1989.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c456.pdf?cite=1987%20c%20456%20§%2034[1987 c 456 § 34]; ]

