= 7.90 - Sexual assault protection order act.
:toc:

== 7.90.005 - Legislative declaration. (Effective until July 1, 2022.)
Sexual assault is the most heinous crime against another person short of murder. Sexual assault inflicts humiliation, degradation, and terror on victims. According to the FBI, a woman is raped every six minutes in the United States. Rape is recognized as the most underreported crime; estimates suggest that only one in seven rapes is reported to authorities. Victims who do not report the crime still desire safety and protection from future interactions with the offender. Some cases in which the rape is reported are not prosecuted. In these situations, the victim should be able to seek a civil remedy requiring that the offender stay away from the victim. It is the intent of the legislature that the sexual assault protection order created by this chapter be a remedy for victims who do not qualify for a domestic violence order of protection.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1555-S.SL.pdf?cite=2007%20c%20212%20§%201[2007 c 212 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2576-S.SL.pdf?cite=2006%20c%20138%20§%201[2006 c 138 § 1]; ]

== 7.90.010 - Definitions. (Effective until July 1, 2022.)
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Electronic monitoring" means the same as in RCW 9.94A.030.

. "Nonconsensual" means a lack of freely given agreement.

. "Nonphysical contact" includes, but is not limited to, telephone calls, mail, email, fax, and written notes.

. "Petitioner" means any named petitioner for the sexual assault protection order or any named victim of nonconsensual sexual conduct or nonconsensual sexual penetration on whose behalf the petition is brought.

. "Sexual assault protection order" means an ex parte temporary order or a final order granted under this chapter, which includes a remedy authorized by RCW 7.90.090.

. "Sexual conduct" means any of the following:

.. Any intentional or knowing touching or fondling of the genitals, anus, or breasts, directly or indirectly, including through clothing;

.. Any intentional or knowing display of the genitals, anus, or breasts for the purposes of arousal or sexual gratification of the respondent;

.. Any intentional or knowing touching or fondling of the genitals, anus, or breasts, directly or indirectly, including through clothing, that the petitioner is forced to perform by another person or the respondent;

.. Any forced display of the petitioner's genitals, anus, or breasts for the purposes of arousal or sexual gratification of the respondent or others;

.. Any intentional or knowing touching of the clothed or unclothed body of a child under the age of thirteen, if done for the purpose of sexual gratification or arousal of the respondent or others; and

.. Any coerced or forced touching or fondling by a child under the age of thirteen, directly or indirectly, including through clothing, of the genitals, anus, or breasts of the respondent or others.

. "Sexual penetration" means any contact, however slight, between the sex organ or anus of one person by an object, the sex organ, mouth, or anus of another person, or any intrusion, however slight, of any part of the body of one person or of any animal or object into the sex organ or anus of another person, including but not limited to cunnilingus, fellatio, or anal penetration. Evidence of emission of semen is not required to prove sexual penetration.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5149-S2.SL.pdf?cite=2020%20c%20296%20§%203[2020 c 296 § 3]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2576-S.SL.pdf?cite=2006%20c%20138%20§%202[2006 c 138 § 2]; ]

== 7.90.020 - Petition for a sexual assault protection order—Creation—Contents—Administration. (Effective until July 1, 2022.)
There shall exist an action known as a petition for a sexual assault protection order.

. A petition for relief shall allege the existence of nonconsensual sexual conduct or nonconsensual sexual penetration, and shall be accompanied by an affidavit made under oath stating the specific facts and circumstances from which relief is sought. Petitioner and respondent shall disclose the existence of any other litigation or of any other restraining, protection, or no-contact orders between the parties.

. A petition for relief may be made regardless of whether or not there is a pending lawsuit, complaint, petition, or other action between the parties.

. Within ninety days of receipt of the master copy from the administrative office of the courts, all court clerk's offices shall make available the standardized forms, instructions, and informational brochures required by RCW 7.90.180 and shall fill in and keep current specific program names and telephone numbers for community resources. Any assistance or information provided by clerks under this section does not constitute the practice of law and clerks are not responsible for incorrect information contained in a petition.

. Forms and instructional brochures and the necessary number of certified copies shall be provided free of charge.

. A person is not required to post a bond to obtain relief in any proceeding under this section.

. If the petition states that disclosure of the petitioner's address would risk abuse of the petitioner or any member of the petitioner's family or household, that address may be omitted from all documents filed with the court. If the petitioner has not disclosed an address under this subsection, the petitioner shall designate an alternative address at which the respondent may serve notice of any motions.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1149.SL.pdf?cite=2019%20c%20258%20§%202[2019 c 258 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1437.SL.pdf?cite=2007%20c%2055%20§%201[2007 c 55 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2576-S.SL.pdf?cite=2006%20c%20138%20§%205[2006 c 138 § 5]; ]

== 7.90.030 - Petition—Who may file. (Effective until July 1, 2022.)
. A petition for a sexual assault protection order may be filed by a person:

.. Who does not qualify for a protection order under chapter 26.50 RCW and who is a victim of nonconsensual sexual conduct or nonconsensual sexual penetration, including a single incident of nonconsensual sexual conduct or nonconsensual sexual penetration; or

.. On behalf of any of the following persons who is a victim of nonconsensual sexual conduct or nonconsensual sexual penetration and who does not qualify for a protection order under chapter 26.50 RCW:

... A minor child;

... A vulnerable adult as defined in RCW 74.34.020 or * 74.34.021; or

... Any other adult who, because of age, disability, health, or inaccessibility, cannot file the petition.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1555-S.SL.pdf?cite=2007%20c%20212%20§%202[2007 c 212 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2576-S.SL.pdf?cite=2006%20c%20138%20§%203[2006 c 138 § 3]; ]

== 7.90.040 - Petition—Additional requirements. (Effective until July 1, 2022.)
. Any person may seek relief under this chapter by filing a petition with a court alleging that the person has been the victim of nonconsensual sexual conduct or nonconsensual sexual penetration committed by the respondent.

. A person under eighteen years of age who is sixteen years of age or older may seek relief under this chapter and is not required to seek relief by a guardian or next friend.

. No guardian or guardian ad litem need be appointed on behalf of a respondent to an action under this chapter who is under eighteen years of age if such respondent is sixteen years of age or older.

. The court may, if it deems necessary, appoint a guardian ad litem for a petitioner or respondent who is a party to an action under this chapter. The appointment shall be at no cost to either party.

. Jurisdiction of the courts over proceedings under this chapter shall be the same as jurisdiction over domestic violence protection orders under *RCW 26.50.020(5).

. An action under this chapter shall be filed in the county or the municipality where the petitioner resides.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1307-S.SL.pdf?cite=2013%20c%2074%20§%201[2013 c 74 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2576-S.SL.pdf?cite=2006%20c%20138%20§%204[2006 c 138 § 4]; ]

== 7.90.050 - Petition—Hearings prior to issuance of protection order. (Effective until July 1, 2022.)
Upon receipt of the petition, the court shall order a hearing which shall be held not later than fourteen days from the date of the order. The court may schedule a hearing by telephone pursuant to local court rule, to reasonably accommodate a disability, or in exceptional circumstances to protect a petitioner from further nonconsensual sexual conduct or nonconsensual sexual penetration. The court shall require assurances of the petitioner's identity before conducting a telephonic hearing. Personal service shall be made upon the respondent not less than five court days prior to the hearing. If timely personal service cannot be made, the court shall set a new hearing date and shall either require additional attempts at obtaining personal service or permit service by publication as provided in RCW 7.90.052 or service by mail as provided in RCW 7.90.053. The court shall not require more than two attempts at obtaining personal service and shall permit service by publication or service by mail unless the petitioner requests additional time to attempt personal service. If the court permits service by publication or service by mail, the court shall set the hearing date not later than twenty-four days from the date of the order. The court may issue an ex parte temporary sexual assault order pending the hearing as provided in RCW 7.90.110.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1307-S.SL.pdf?cite=2013%20c%2074%20§%202[2013 c 74 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2576-S.SL.pdf?cite=2006%20c%20138%20§%206[2006 c 138 § 6]; ]

== 7.90.052 - Service by publication—When authorized. (Effective until July 1, 2022.)
. The court may order service by publication instead of personal service under the following circumstances:

.. The sheriff or municipal peace officer files an affidavit stating that the officer was unable to complete personal service upon the respondent. The affidavit must describe the number and type of attempts the officer made to complete service;

.. The petitioner files an affidavit stating that the petitioner believes the respondent is hiding from the server to avoid service. The petitioner's affidavit must state the reasons for the belief that the respondent is avoiding service;

.. The server has deposited a copy of the summons, in substantially the form prescribed in subsection (3) of this section, notice of hearing, and the ex parte order of protection in the post office, directed to the respondent at the respondent's last known address, unless the server states that he or she does not know the respondent's address; and

.. The court finds reasonable grounds exist to believe the respondent is concealing himself or herself to avoid service, and that further attempts to personally serve the respondent would be futile or unduly burdensome.

. If the court orders service by publication, it shall also reissue the temporary order of protection not to exceed another twenty-four days from the date of reissuing the ex parte protection order and order that service by publication be provided.

. The publication must be made in a newspaper of general circulation in the county where the petition was brought and in the county of the last known address of the respondent once a week for three consecutive weeks. The newspaper selected must be one of the three most widely circulated papers in the county. The publication of summons must not be made until the court orders service by publication under this section. Service of the summons is considered complete when the publication has been made for three consecutive weeks. The summons must be signed by the petitioner. The summons must contain the date of the first publication, and must require the respondent upon whom service by publication is desired, to appear and answer the petition on the date set for the hearing. The summons must also contain a brief statement of the reason for the petition and a summary of the provisions under the ex parte order. The summons must be essentially in the following form:

In the  . . . . . . . . . court of the state of Washington for the county of  . . . . . . . . . . . . . . . . . . . . . . . ., Petitioner vs. No.  . . . . . . . . . . . . . . . . . . . . ., Respondent The state of Washington to  . . . . . . . . . (respondent):You are hereby summoned to appear on the  . . . . day of  . . . . . ., (year) . . . ., at  . . . . a.m./p.m., and respond to the petition. If you fail to respond, an order of protection will be issued against you pursuant to the provisions of the sexual assault protection order act, chapter 7.90 RCW, for a minimum of one year from the date you are required to appear. A temporary order of protection has been issued against you, restraining you from the following: (Insert a brief statement of the provisions of the ex parte order). A copy of the petition, notice of hearing, and ex parte order has been filed with the clerk of this court. . . . . Petitioner . . . .

In the  . . . . . . . . . court of the state of Washington for the county of  . . . . . . . . .

 . . . . . . . . . . . . . . ., Petitioner

 

vs.

 

No.  . . . . . .

 . . . . . . . . . . . . . . ., Respondent

 

The state of Washington to  . . . . . . . . . (respondent):

You are hereby summoned to appear on the  . . . . day of  . . . . . ., (year) . . . ., at  . . . . a.m./p.m., and respond to the petition. If you fail to respond, an order of protection will be issued against you pursuant to the provisions of the sexual assault protection order act, chapter 7.90 RCW, for a minimum of one year from the date you are required to appear. A temporary order of protection has been issued against you, restraining you from the following: (Insert a brief statement of the provisions of the ex parte order). A copy of the petition, notice of hearing, and ex parte order has been filed with the clerk of this court.

 

. . . .

 

Petitioner . . . .

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1307-S.SL.pdf?cite=2013%20c%2074%20§%206[2013 c 74 § 6]; ]

== 7.90.053 - Service by mail—When authorized. (Effective until July 1, 2022.)
. In circumstances justifying service by publication under RCW 7.90.052, if the serving party files an affidavit stating facts from which the court determines that service by mail is just as likely to give actual notice as service by publication and that the serving party is unable to afford the cost of service by publication, the court may order that service be made by mail. The service must be made by any person over eighteen years of age, who is competent to be a witness, other than a party, by mailing copies of the order and other process to the party to be served at his or her last known address or any other address determined by the court to be appropriate. Two copies must be mailed, postage prepaid, one by ordinary first-class mail and the other by a form of mail requiring a signed receipt showing when and to whom it was delivered. The envelopes must bear the return address of the sender.

. Proof of service under this section must be consistent with court rules for civil proceedings.

. Service under this section may be used in the same manner and has the same jurisdictional effect as service by publication for purposes of this chapter. Service is deemed complete upon the mailing of the two copies as prescribed in this section.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1307-S.SL.pdf?cite=2013%20c%2074%20§%207[2013 c 74 § 7]; ]

== 7.90.054 - Issuance of order following service by publication or mail. (Effective until July 1, 2022.)
Following completion of service by publication as provided in RCW 7.90.052 or service by mail as provided in RCW 7.90.053, if the respondent fails to appear at the hearing, the court may issue an order of protection as provided in RCW 7.90.140. That order must be served pursuant to RCW 7.90.140 and forwarded to the appropriate law enforcement agency pursuant to RCW 7.90.160.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1307-S.SL.pdf?cite=2013%20c%2074%20§%208[2013 c 74 § 8]; ]

== 7.90.055 - Fees not permitted—Filing, service of process, certified copies. (Effective until July 1, 2022.)
No fees for filing or service of process may be charged by a public agency to petitioners seeking relief under this chapter. Petitioners shall be provided the necessary number of certified copies at no cost.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1437.SL.pdf?cite=2007%20c%2055%20§%202[2007 c 55 § 2]; ]

== 7.90.060 - Sexual assault advocates. (Effective until July 1, 2022.)
Sexual assault advocates, as defined in RCW 5.60.060, shall be allowed to accompany the victim and confer with the victim, unless otherwise directed by the court. Court administrators shall allow sexual assault advocates to assist victims of nonconsensual sexual conduct or nonconsensual sexual penetration in the preparation of petitions for sexual assault protection orders. Sexual assault advocates are not engaged in the unauthorized practice of law when providing assistance of the types specified in this section. Communications between the petitioner and a sexual assault advocate are protected as provided by RCW 5.60.060.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2576-S.SL.pdf?cite=2006%20c%20138%20§%207[2006 c 138 § 7]; ]

== 7.90.070 - Appointment of counsel. (Effective until July 1, 2022.)
The court may appoint counsel to represent the petitioner if the respondent is represented by counsel.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2576-S.SL.pdf?cite=2006%20c%20138%20§%208[2006 c 138 § 8]; ]

== 7.90.080 - Evidence. (Effective until July 1, 2022.)
. In proceedings for a sexual assault protection order and prosecutions for violating a sexual assault protection order, the prior sexual activity or the reputation of the petitioner is inadmissible except:

.. As evidence concerning the past sexual conduct of the petitioner with the respondent when this evidence is offered by the respondent upon the issue of whether the petitioner consented to the sexual conduct with respect to which the offense is alleged; or

.. When constitutionally required to be admitted.

. No evidence admissible under this section may be introduced unless ruled admissible by the court after an offer of proof has been made at a hearing held in camera to determine whether the respondent has evidence to impeach the witness in the event that prior sexual activity with the respondent is denied. The offer of proof shall include reasonably specific information as to the date, time, and place of the past sexual conduct between the petitioner and the respondent. Unless the court finds that reasonably specific information as to date, time, or place, or some combination thereof, has been offered as to prior sexual activity with the respondent, counsel for the respondent shall be ordered to refrain from inquiring into prior sexual activity between the petitioner and the respondent. The court may not admit evidence under this section unless it determines at the hearing that the evidence is relevant and the probative value of the evidence outweighs the danger of unfair prejudice. The evidence shall be admissible at trial to the extent an order made by the court specifies the evidence that may be admitted and areas with respect to which the petitioner may be examined or cross-examined.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2576-S.SL.pdf?cite=2006%20c%20138%20§%209[2006 c 138 § 9]; ]

== 7.90.090 - Burden of proof—Issuance of protection order—Remedies—Violations. (Effective until July 1, 2022.)
. [Empty]
.. If the court finds by a preponderance of the evidence that the petitioner has been a victim of nonconsensual sexual conduct or nonconsensual sexual penetration by the respondent, the court shall issue a sexual assault protection order; provided that the petitioner must also satisfy the requirements of RCW 7.90.110 for ex parte temporary orders or RCW 7.90.120 for final orders.

.. The petitioner shall not be denied a sexual assault protection order because the petitioner or the respondent is a minor or because the petitioner did not report the assault to law enforcement. The court, when determining whether or not to issue a sexual assault protection order, may not require proof of physical injury on the person of the victim or proof that the petitioner has reported the sexual assault to law enforcement. Modification and extension of prior sexual assault protection orders shall be in accordance with this chapter.

. The court may provide relief as follows:

.. Restrain the respondent from having any contact, including nonphysical contact, with the petitioner directly, indirectly, or through third parties regardless of whether those third parties know of the order;

.. Exclude the respondent from the petitioner's residence, workplace, or school, or from the day care or school of a child, if the victim is a child;

.. Prohibit the respondent from knowingly coming within, or knowingly remaining within, a specified distance from a specified location; and

.. Order any other injunctive relief as necessary or appropriate for the protection of the petitioner.

. In issuing the order, the court shall consider the provisions of RCW 9.41.800, and shall order the respondent to surrender, and prohibit the respondent from possessing, all firearms, dangerous weapons, and any concealed pistol license as required in RCW 9.41.800.

. In cases where the petitioner and the respondent are under the age of eighteen and attend the same public or private elementary, middle, or high school, the court, when issuing a protection order and providing relief, shall consider, among the other facts of the case, the severity of the act, any continuing physical danger or emotional distress to the petitioner, and the expense difficulty, and educational disruption that would be caused by a transfer of the respondent to another school. The court may order that the person restrained in the order not attend the public or approved private elementary, middle, or high school attended by the person under the age of eighteen protected by the order. In the event the court orders a transfer of the restrained person to another school, the parents or legal guardians of the person restrained in the order are responsible for transportation and other costs associated with the change of school by the person restrained in the order. The court shall send notice of the restriction on attending the same school as the person protected by the order to the public or approved private school the person restrained by the order will attend and to the school the person protected by the order attends.

. Denial of a remedy may not be based, in whole or in part, on evidence that:

.. The respondent was voluntarily intoxicated;

.. The petitioner was voluntarily intoxicated; or

.. The petitioner engaged in limited consensual sexual touching.

. Monetary damages are not recoverable as a remedy.

. A knowing violation of a court order issued under this section is punishable under RCW 26.50.110.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1786-S.SL.pdf?cite=2019%20c%20245%20§%204[2019 c 245 § 4]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2576-S.SL.pdf?cite=2006%20c%20138%20§%2010[2006 c 138 § 10]; ]

== 7.90.100 - Accountability for conduct of others. (Effective until July 1, 2022.)
For the purposes of issuing a sexual assault protection order, deciding what relief should be included in the order, and enforcing the order, RCW 9A.08.020 shall govern whether the respondent is legally accountable for the conduct of another person.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2576-S.SL.pdf?cite=2006%20c%20138%20§%2011[2006 c 138 § 11]; ]

== 7.90.110 - Ex parte temporary sexual assault protection orders—Issuance. (Effective until July 1, 2022.)
. An ex parte temporary sexual assault protection order shall issue if the petitioner satisfies the requirements of this subsection by a preponderance of the evidence. The petitioner shall establish that:

.. The petitioner has been a victim of nonconsensual sexual conduct or nonconsensual sexual penetration by the respondent; and

.. There is good cause to grant the remedy, regardless of the lack of prior service of process or of notice upon the respondent, because the harm which that remedy is intended to prevent would be likely to occur if the respondent were given any prior notice, or greater notice than was actually given, of the petitioner's efforts to obtain judicial relief.

. In issuing the order, the court shall consider the provisions of RCW 9.41.800, and shall order the respondent to surrender, and prohibit the respondent from possessing, all firearms, dangerous weapons, and any concealed pistol license as required in RCW 9.41.800.

. If the respondent appears in court for this hearing for an ex parte temporary order, he or she may elect to file a general appearance and testify under oath. Any resulting order may be an ex parte temporary order, governed by this section.

. If the court declines to issue an ex parte temporary sexual assault protection order, the court shall state the particular reasons for the court's denial. The court's denial of a motion for an ex parte temporary order shall be filed with the court.

. A knowing violation of a court order issued under this section is punishable under RCW 26.50.110.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1786-S.SL.pdf?cite=2019%20c%20245%20§%205[2019 c 245 § 5]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1555-S.SL.pdf?cite=2007%20c%20212%20§%203[2007 c 212 § 3]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2576-S.SL.pdf?cite=2006%20c%20138%20§%2012[2006 c 138 § 12]; ]

== 7.90.120 - Ex parte orders—Duration. (Effective until July 1, 2022.)
. [Empty]
.. An ex parte temporary sexual assault protection order shall be effective for a fixed period not to exceed fourteen days. A full hearing, as provided in this chapter, shall be set for not later than fourteen days from the issuance of the temporary order or not later than twenty-four days if service by publication or service by mail is permitted. If the court permits service by publication or service by mail, the court shall also reissue the ex parte temporary protection order not to exceed another twenty-four days from the date of reissuing the ex parte protection order. Except as provided in RCW 7.90.050, 7.90.052, or 7.90.053, the respondent shall be personally served with a copy of the ex parte temporary sexual assault protection order along with a copy of the petition and notice of the date set for the hearing.

.. Any ex parte temporary order issued under this section shall contain the date and time of issuance and the expiration date and shall be entered into a statewide judicial information system by the clerk of the court within one judicial day after issuance.

. Except as otherwise provided in this section or RCW 7.90.150, a final sexual assault protection order shall be effective for a fixed period of time or be permanent.

. Any sexual assault protection order which would expire on a court holiday shall instead expire at the close of the next court business day.

. The practice of dismissing or suspending a criminal prosecution in exchange for the issuance of a sexual assault protection order undermines the purposes of this chapter. This section shall not be construed as encouraging that practice.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5256-S.SL.pdf?cite=2017%20c%20233%20§%201[2017 c 233 § 1]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1307-S.SL.pdf?cite=2013%20c%2074%20§%203[2013 c 74 § 3]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2576-S.SL.pdf?cite=2006%20c%20138%20§%2013[2006 c 138 § 13]; ]

== 7.90.121 - Renewal of ex parte order. (Effective until July 1, 2022.)
. Any ex parte temporary or nonpermanent final sexual assault protection order may be renewed one or more times, as required.

. The petitioner may apply for renewal of the order by filing a motion for renewal at any time within the three months before the order expires. The motion for renewal shall state the reasons why the petitioner seeks to renew the protection order.

. [Empty]
.. The court shall grant the motion for renewal unless the respondent proves by a preponderance of the evidence that there has been a material change in circumstances such that the respondent is not likely to engage in or attempt to engage in physical or nonphysical contact with the petitioner when the order expires.

.. For purposes of this subsection (3), a court shall determine whether there has been a material change in circumstances by considering only factors which address whether the respondent is likely to engage in or attempt to engage in physical or nonphysical contact with the petitioner when the order expires. The passage of time and compliance with the existing protection order shall not, alone, be sufficient to meet this burden of proof. The court may renew the sexual assault protection order for another fixed time period or may enter a permanent order as provided in this section.

.. In determining whether there has been a material change in circumstances, the court may consider the following unweighted factors, and no inference is to be drawn from the order in which the factors are listed:

... Whether the respondent has committed or threatened sexual assault, domestic violence, stalking, or other violent acts since the protection order was entered;

... Whether the respondent has violated the terms of the protection order and the time that has passed since the entry of the order;

... Whether the respondent has exhibited suicidal ideation or attempts since the protection order was entered;

... Whether the respondent has been convicted of criminal activity since the protection order was entered;

.. Whether the respondent has either acknowledged responsibility for acts of sexual assault that resulted in entry of the protection order or successfully completed sexual assault perpetrator treatment or counseling since the protection order was entered;

.. Whether the respondent has a continuing involvement with drug or alcohol abuse, if such abuse was a factor in the protection order;

.. Whether the respondent or petitioner has relocated to an area more distant from the other party, giving due consideration to the fact that acts of sexual assault may be committed from any distance such as via cybercrime;

.. Other factors relating to a material change in circumstances.

. [Empty]
.. If the motion is contested, upon receipt of the motion, the court shall order that a hearing be held not later than fourteen days from the date of the order.

.. The court may schedule a hearing by telephone pursuant to local court rule, to reasonably accommodate a disability, or in exceptional circumstances to protect a petitioner from further nonconsensual sexual conduct or nonconsensual sexual penetration. The court shall require assurances of the petitioner's identity before conducting a telephonic hearing.

.. The respondent shall be personally served not less than five court days prior to the hearing. If timely personal service cannot be made, the court shall set a new hearing date and shall either require additional attempts at obtaining personal service or permit service by publication as provided in RCW 7.90.052 or service by mail as provided in RCW 7.90.053. The court shall not require more than two attempts at obtaining personal service and shall permit service by publication or service by mail unless the petitioner requests additional time to attempt personal service. If the court permits service by publication or service by mail, the court shall set the hearing date not later than twenty-four days from the date of the order.

. Renewals may be granted only in open court.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5256-S.SL.pdf?cite=2017%20c%20233%20§%202[2017 c 233 § 2]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1307-S.SL.pdf?cite=2013%20c%2074%20§%204[2013 c 74 § 4]; ]

== 7.90.130 - Sexual assault protection orders—Contents. (Effective until July 1, 2022.)
. Any sexual assault protection order shall describe each remedy granted by the court, in reasonable detail and not by reference to any other document, so that the respondent may clearly understand what he or she must do or refrain from doing.

. A sexual assault protection order shall further state the following:

.. The name of each petitioner that the court finds was the victim of nonconsensual sexual conduct or nonconsensual sexual penetration by the respondent;

.. The date and time the sexual assault protection order was issued, whether it is an ex parte temporary or final order, and the duration of the order;

.. The date, time, and place for any scheduled hearing for renewal of that sexual assault protection order or for another order of greater duration or scope;

.. For each remedy in an ex parte temporary sexual assault protection order, the reason for entering that remedy without prior notice to the respondent or greater notice than was actually given;

.. For ex parte temporary sexual assault protection orders, that the respondent may petition the court, to reopen the order if he or she did not receive actual prior notice of the hearing and if the respondent alleges that he or she had a meritorious defense to the order or that the order or its remedy is not authorized by this chapter.

. A sexual assault protection order shall include the following notice, printed in conspicuous type: "A knowing violation of this sexual assault protection order is a criminal offense under chapter 26.50 RCW and will subject a violator to arrest. You can be arrested even if any person protected by the order invites or allows you to violate the order's prohibitions. You have the sole responsibility to avoid or refrain from violating the order's provisions. Only the court can change the order."

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2576-S.SL.pdf?cite=2006%20c%20138%20§%2014[2006 c 138 § 14]; ]

== 7.90.140 - Sexual assault protection orders—Service to respondent. (Effective until July 1, 2022.)
. An order issued under this chapter shall be personally served upon the respondent, except as provided in subsection (6) of this section.

. The sheriff of the county or the peace officers of the municipality in which the respondent resides shall serve the respondent personally unless the petitioner elects to have the respondent served by a private party. If the order includes a requirement under RCW 9.41.800 for the immediate surrender of all firearms, dangerous weapons, and any concealed pistol license, the order must be served by a law enforcement officer.

. If service by a sheriff or municipal peace officer is to be used, the clerk of the court shall have a copy of any order issued under this chapter electronically forwarded on or before the next judicial day to the appropriate law enforcement agency specified in the order for service upon the respondent. Service of an order issued under this chapter shall take precedence over the service of other documents unless they are of a similar emergency nature.

. If the sheriff or municipal peace officer cannot complete service upon the respondent within ten days, the sheriff or municipal peace officer shall notify the petitioner. The petitioner shall provide information sufficient to permit notification.

. Returns of service under this chapter shall be made in accordance with the applicable court rules.

. If an order entered by the court recites that the respondent appeared in person before the court, the necessity for further service is waived and proof of service of that order is not necessary.

. If the court previously entered an order allowing service of the notice of hearing and temporary order of protection by publication under RCW 7.90.052 or service by mail under RCW 7.90.053, the court may permit service by publication or service by mail of the order of protection issued under this chapter. Service by publication must comply with the requirements of RCW 7.90.052 and service by mail must comply with the requirements of RCW 7.90.053. The court order must state whether the court permitted service by publication or service by mail.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1786-S.SL.pdf?cite=2019%20c%20245%20§%206[2019 c 245 § 6]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1307-S.SL.pdf?cite=2013%20c%2074%20§%205[2013 c 74 § 5]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2576-S.SL.pdf?cite=2006%20c%20138%20§%2015[2006 c 138 § 15]; ]

== 7.90.150 - Court initiated issuance of sexual assault protection orders—Terms, conditions, requirements, etc. (Effective until July 1, 2022. Recodified as RCW  9A.44.210.)
. [Empty]
.. When any person charged with or arrested for a sex offense as defined in RCW 9.94A.030, a violation of RCW 9A.44.096, a violation of RCW 9.68A.090, or a gross misdemeanor that is, under chapter 9A.28 RCW, a criminal attempt, criminal solicitation, or criminal conspiracy to commit an offense that is classified as a sex offense under RCW 9.94A.030, is released from custody before arraignment or trial on bail or personal recognizance, the court authorizing the release may prohibit that person from having any contact with the victim. The jurisdiction authorizing the release shall determine whether that person should be prohibited from having any contact with the victim. If there is no outstanding restraining or protective order prohibiting that person from having contact with the victim, the court authorizing release may issue, by telephone, a sexual assault protection order prohibiting the person charged or arrested from having contact with the victim or from knowingly coming within, or knowingly remaining within, a specified distance of a location.

.. In issuing the order, the court shall consider the provisions of RCW 9.41.800.

.. The sexual assault protection order shall also be issued in writing as soon as possible.

. [Empty]
.. At the time of arraignment or whenever a motion is brought to modify the conditions of the defendant's release, the court shall determine whether a sexual assault protection order shall be issued or extended. If a sexual assault protection order is issued or extended, the court may also include in the conditions of release a requirement that the defendant submit to electronic monitoring. If electronic monitoring is ordered, the court shall specify who shall provide the monitoring services, and the terms under which the monitoring shall be performed. Upon conviction, the court may require as a condition of the sentence that the defendant reimburse the providing agency for the costs of the electronic monitoring.

.. A sexual assault protection order issued by the court in conjunction with criminal charges shall terminate if the defendant is acquitted or the charges are dismissed, unless the victim files an independent action for a sexual assault protection order. If the victim files an independent action for a sexual assault protection order, the order may be continued by the court until a full hearing is conducted pursuant to RCW 7.90.050.

. [Empty]
.. The written order releasing the person charged or arrested shall contain the court's directives and shall bear the legend: "Violation of this order is a criminal offense under chapter 26.50 RCW and will subject a violator to arrest. You can be arrested even if any person protected by the order invites or allows you to violate the order's prohibitions. You have the sole responsibility to avoid or refrain from violating the order's provisions. Only the court can change the order."

.. A certified copy of the order shall be provided to the victim at no charge.

. If a sexual assault protection order has been issued prior to charging, that order shall expire at arraignment or within seventy-two hours if charges are not filed. Such orders need not be entered into the computer-based criminal intelligence information system in this state which is used by law enforcement agencies to list outstanding warrants.

. Whenever an order prohibiting contact is issued pursuant to subsection (2) of this section, the clerk of the court shall forward a copy of the order on or before the next judicial day to the appropriate law enforcement agency specified in the order. Upon receipt of the copy of the order, the law enforcement agency shall enter the order for one year or until the expiration date specified on the order into any computer-based criminal intelligence information system available in this state used by law enforcement agencies to list outstanding warrants. Entry into the computer-based criminal intelligence information system constitutes notice to all law enforcement agencies of the existence of the order. The order is fully enforceable in any jurisdiction in the state.

. [Empty]
.. When a defendant is found guilty of a sex offense as defined in RCW 9.94A.030, any violation of RCW 9A.44.096, or any violation of RCW 9.68A.090, or any gross misdemeanor that is, under chapter 9A.28 RCW, a criminal attempt, criminal solicitation, or criminal conspiracy to commit an offense that is classified as a sex offense under RCW 9.94A.030, and a condition of the sentence restricts the defendant's ability to have contact with the victim, the condition shall be recorded as a sexual assault protection order.

.. The written order entered as a condition of sentencing shall contain the court's directives and shall bear the legend: "Violation of this order is a criminal offense under chapter 26.50 RCW and will subject a violator to arrest. You can be arrested even if any person protected by the order invites or allows you to violate the order's prohibitions. You have the sole responsibility to avoid or refrain from violating the order's provisions. Only the court can change the order."

.. A final sexual assault protection order entered in conjunction with a criminal prosecution shall remain in effect for a period of two years following the expiration of any sentence of imprisonment and subsequent period of community supervision, conditional release, probation, or parole.

.. A certified copy of the order shall be provided to the victim at no charge.

. A knowing violation of a court order issued under subsection (1), (2), or (6) of this section is punishable under RCW 26.50.110.

. Whenever a sexual assault protection order is issued, modified, or terminated under subsection (1), (2), or (6) of this section, the clerk of the court shall forward a copy of the order on or before the next judicial day to the appropriate law enforcement agency specified in the order. Upon receipt of the copy of the order, the law enforcement agency shall enter the order for one year or until the expiration date specified on the order into any computer-based criminal intelligence information system available in this state used by law enforcement agencies to list outstanding warrants. Entry into the computer-based criminal intelligence information system constitutes notice to all law enforcement agencies of the existence of the order. The order is fully enforceable in any jurisdiction in the state. Upon receipt of notice that an order has been terminated under subsection (2) of this section, the law enforcement agency shall remove the order from the computer-based criminal intelligence information system.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2576-S.SL.pdf?cite=2006%20c%20138%20§%2016[2006 c 138 § 16]; ]

== 7.90.155 - Sexual assault protection orders—Personal jurisdiction—Nonresident individuals. (Effective until July 1, 2022.)
. In a proceeding in which a petition for a sexual assault protection order is sought under this chapter, a court of this state may exercise personal jurisdiction over a nonresident individual if:

.. The individual is personally served with a petition within this state;

.. The individual submits to the jurisdiction of this state by consent, entering a general appearance, or filing a responsive document having the effect of waiving any objection to consent to personal jurisdiction;

.. The act or acts of the individual or the individual's agent giving rise to the petition or enforcement of a sexual assault protection order occurred within this state;

.. [Empty]
... The act or acts of the individual or the individual's agent giving rise to the petition or enforcement of a sexual assault protection order occurred outside this state and are part of an ongoing pattern of sexual assaults or stalking that has an adverse effect on the petitioner or a member of the petitioner's family or household and the petitioner resides in this state; or

... As a result of acts of stalking or a sexual assault, the petitioner or a member of the petitioner's family or household has sought safety or protection in this state and currently resides in this state; or

.. There is any other basis consistent with RCW 4.28.185 or with the constitutions of this state and the United States.

. For jurisdiction to be exercised under subsection (1)(d)(i) or (ii) of this section, the individual must have communicated with the petitioner or a member of the petitioner's family, directly or indirectly, or made known a threat to the safety of the petitioner or member of the petitioner's family while the petitioner or family member resides in this state. For the purposes of subsection (1)(d)(i) or (ii) of this section, "communicated or made known" includes, but is not limited to, through the mail, telephonically, or a posting on an electronic communication site or medium. Communication on any electronic medium that is generally available to any individual residing in the state shall be sufficient to exercise jurisdiction under subsection (1)(d)(i) or (ii) of this section.

. For the purposes of this section, an act or acts that "occurred within this state" includes, but is not limited to, an oral or written statement made or published by a person outside of this state to any person in this state by means of the mail, interstate commerce, or foreign commerce. Oral or written statements sent by electronic mail or the internet are deemed to have "occurred within this state."

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2777-S.SL.pdf?cite=2010%20c%20274%20§%20307[2010 c 274 § 307]; ]

== 7.90.160 - Law enforcement agencies—Entry of protection order data. (Effective until July 1, 2022.)
. A copy of a sexual assault protection order granted under this chapter shall be forwarded by the clerk of the court on or before the next judicial day to the appropriate law enforcement agency specified in the order. Upon receipt of the order, the law enforcement agency shall immediately enter the order into any computer-based criminal intelligence information system available in this state used by law enforcement agencies to list outstanding warrants. The order shall remain in the computer for one year or until the expiration date specified on the order. Upon receipt of notice that an order has been terminated, the law enforcement agency shall remove the order from the computer-based criminal intelligence information system. The law enforcement agency shall only expunge from the computer-based criminal intelligence information system orders that are expired, vacated, terminated, or superseded. Entry into the law enforcement information system constitutes notice to all law enforcement agencies of the existence of the order. The order is fully enforceable in any county in the state.

. The information entered into the computer-based criminal intelligence information system shall include notice to law enforcement whether the order was personally served, served by publication, or served by mail.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2576-S.SL.pdf?cite=2006%20c%20138%20§%2017[2006 c 138 § 17]; ]

== 7.90.170 - Modification or termination of protection orders. (Effective until July 1, 2022.)
. Upon a motion with notice to all parties and after a hearing, the court may terminate or modify the terms of an existing sexual assault protection order, including terms entered pursuant to RCW 9.41.800 related to firearms or other dangerous weapons or to concealed pistol licenses.

. [Empty]
.. A respondent's motion to terminate or modify a sexual assault protection order must include a declaration setting forth facts supporting the requested order for termination or modification. The nonmoving parties to the proceeding may file opposing declarations. The court shall deny the motion unless it finds that adequate cause for hearing the motion is established by the declarations. If the court finds that the respondent established adequate cause, the court shall set a date for hearing the respondent's motion.

.. The court may terminate or modify the terms of a sexual assault protection order, including terms entered pursuant to RCW 9.41.800 related to firearms or other dangerous weapons or to concealed pistol licenses, if the respondent proves by a preponderance of the evidence that there has been a material change in circumstances such that the respondent is not likely to engage in or attempt to engage in physical or nonphysical contact with the persons protected by the protection order if the order is terminated or modified. The petitioner bears no burden of proving that he or she has a current reasonable fear of harm by the respondent.

.. A respondent may file a motion to terminate or modify pursuant to this section no more than once in every twelve-month period that the order is in effect, starting from the date of the order and continuing through any renewal.

.. A court may require the respondent to pay the petitioner for costs incurred in responding to a motion to terminate or modify pursuant to this section, including reasonable attorneys' fees.

. The court shall order that a hearing on the motion for termination or modification of the order be held not later than fourteen days from the date of the order. The nonmoving party shall be personally served not less than five days before the hearing. If timely service cannot be made, the court shall set a new hearing date and shall either require additional attempts at obtaining personal service or permit service by publication as provided in RCW 7.90.052 or service by mail as provided in RCW 7.90.053. If the court permits service by mail or service by publication, the court shall set the new hearing date not later than twenty-four days from the date of the order.

. In any situation where an order is terminated or modified before its expiration date, the clerk of the court shall forward on or before the next judicial day a true copy of the modified order or the termination order to the appropriate law enforcement agency specified in the modified or termination order. Upon receipt of the order, the law enforcement agency shall promptly enter it in the computer-based criminal intelligence information system, or if the order is terminated, remove the order from the computer-based criminal intelligence information system.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5256-S.SL.pdf?cite=2017%20c%20233%20§%203[2017 c 233 § 3]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1307-S.SL.pdf?cite=2013%20c%2074%20§%209[2013 c 74 § 9]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2576-S.SL.pdf?cite=2006%20c%20138%20§%2018[2006 c 138 § 18]; ]

== 7.90.180 - Administrative office of the courts—Court clerks—Instructional and informational material. (Effective until July 1, 2022.)
. The administrative office of the courts shall develop and prepare instructions and informational brochures required under RCW 7.90.020, standard petition and order for protection forms, and a court staff handbook on sexual assault, and the protection order process. The standard petition and order for protection forms must be used after September 1, 2006, for all petitions filed and orders issued under this chapter. The instructions, brochures, forms, and handbook shall be prepared in consultation with interested persons, including a representative of the state sexual assault coalition, judges, and law enforcement personnel.

.. The instructions shall be designed to assist petitioners in completing the petition, and shall include a sample of standard petition and order for protection forms.

.. The informational brochure shall describe the use of and the process for obtaining, modifying, and terminating a protection order as provided under this chapter.

.. The order for protection form shall include, in a conspicuous location, notice of criminal penalties resulting from violation of the order, and the following statement: "You can be arrested even if the person or persons who obtained the order invite or allow you to violate the order's prohibitions. The respondent has the sole responsibility to avoid or refrain from violating the order's provisions. Only the court can change the order upon written application."

.. The court staff handbook shall allow for the addition of a community resource list by the court clerk.

. All court clerks shall obtain a community resource list from a sexual assault program serving the county in which the court is located. The community resource list shall include the names and telephone numbers of sexual assault programs serving the community in which the court is located, including law enforcement agencies, domestic violence agencies, sexual assault agencies, legal assistance programs, interpreters, multicultural programs, and batterers' treatment programs. The court shall make the community resource list available as part of or in addition to the informational brochures described in subsection (1) of this section.

. The administrative office of the courts shall distribute a master copy of the petition and order forms, instructions, and informational brochures to all court clerks and shall distribute a master copy of the petition and order forms to all superior, district, and municipal courts.

. For purposes of this section, "court clerks" means court administrators in courts of limited jurisdiction and elected court clerks.

. The administrative office of the courts shall determine the significant non-English-speaking or limited English-speaking populations in the state. The administrator shall then arrange for translation of the instructions and informational brochures required by this section, which shall contain a sample of the standard petition and order for protection forms, into the languages spoken by those significant non-English-speaking populations and shall distribute a master copy of the translated instructions and informational brochures to all court clerks by December 1, 2006.

. The administrative office of the courts shall update the instructions, brochures, standard petition and order for protection forms, and court staff handbook when changes in the law make an update necessary.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2576-S.SL.pdf?cite=2006%20c%20138%20§%2019[2006 c 138 § 19]; ]

== 7.90.190 - Admissibility of ex parte temporary orders in civil actions. (Effective until July 1, 2022.)
An ex parte temporary order issued under this chapter shall not be admissible as evidence in any subsequent civil action for damages arising from the conduct alleged in the petition or the order.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2576-S.SL.pdf?cite=2006%20c%20138%20§%2020[2006 c 138 § 20]; ]

== 7.90.900 - Short title—2006 c 138. (Effective until July 1, 2022.)
This act may be cited as the sexual assault protection order act.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2576-S.SL.pdf?cite=2006%20c%20138%20§%2028[2006 c 138 § 28]; ]

